### ISSUE TITLE
Filter by device does not work when querying for modules.

### ISSUE THREAD

**Issue by agreusel** [netbox-community/netbox#10006]
### NetBox version

v3.2.7

### Python version

3.10

### Steps to Reproduce

https://ipam.network.anduril.dev/api/dcim/modules/?device=device_xyz

Returns all modules, ignoring the filter. If you change the request to:

-------

https://ipam.network.anduril.dev/api/dcim/interfaces/?device=device_xyz

Only the interfaces for device_xyz are returned.

### Expected Behavior

Using a 'device = device_xyz' filter should only return modules assigned to device_xyz.

### Observed Behavior

All modules were returned.

**Comment by jeremystretch** [comment]
I'm closing this as you have not provided any reproduction steps. If you'd like to invest some time into rewriting this as a valid bug report, you're welcome to do so, and I'll be happy to re-open it once it meets the standards set forth in the bug report template.
