### ISSUE TITLE
Fragmentation of available IP addresses

### ISSUE THREAD

**Issue by lmelcher1** [netbox-community/netbox#10013]
### NetBox version

v3.2.8

### Python version

3.8

### Steps to Reproduce

1. Click on prefixes
2. Click on some of them
3. Click on Ip Adresses tab
 
![image](https://user-images.githubusercontent.com/55697949/184607857-4f9d19f6-02a6-45dc-8710-0ebae91380a6.png)

### Expected Behavior

One block between each assigned ip address with count of available

### Observed Behavior

![image](https://user-images.githubusercontent.com/55697949/184607904-d99fb79b-6954-4e48-adac-8627e18301af.png)

Available ips are fragmented into blocks

**Comment by jeremystretch** [comment]
> 1. Click on prefixes
> 2. Click on some of them
> 3. Click on Ip Adresses tab

I'm closing this as you have not provided any reproduction steps. If you'd like to invest some time into rewriting this as a valid bug report, you're welcome to do so, and I'll be happy to re-open it once it meets the standards set forth in the bug report template.
