### ISSUE TITLE
Filter subnets based on tenants

### ISSUE THREAD

**Issue by Dirimsa** [netbox-community/netbox#10018]
### NetBox version

v3.2.8

### Feature type

Change to existing functionality

### Proposed functionality

Filter and assign subnets based on the tenant which it is assigned to.

When you have a huge network with multiple tenants which overlay some network areas then the child subnets are assigned to all the parent subnets and are not filtered any further.

- Tenant A: 10.0.0.0/8
- Tenant B: 10.0.0.0/8
- Tenant C: 10.0.0.0/8
- Tenant A First Subnet: - 10.120.24.0/22
- Tenant A Second Subnet: -- 10.120.25.0/24

When you have a setup like the above the the 2 child subnets from Tenant A are assigned to the parent subnets of Tenant A and Tenant B and Tenant C as well.

Having a filter in place which assigns children based on the tenant would further increase the visibility and accessibility towards the data in a huge network environment. 

### Use case

Adding this functionality increases

- visibility 
- data quality 
- tenant management with their subnets

in larger network areas which are assigned in netbox

**Comment by jeremystretch** [comment]
It's not clear from your description exactly what you're trying to accomplish. It looks like you have three tenants with overlapping IP space, in which case you'll need to use VRF assignment to create separate tables in addition to the tenant relationships.

**Comment by jsenecal** [comment]
I actually do exactly what Jeremy described. You create VRFs for each of your tenants because these actually represent different "realms", or routing space.
Tenancy has no meaning in routing. Route tables (VRFs) do.

**Comment by Dirimsa** [comment]
I can confirm that creating VRFs and assigning them to the prefixes gives me the desired result.

Thanks for the answer and solution provided.
