### ISSUE TITLE
Add tags to import CSV

### ISSUE THREAD

**Issue by Dirimsa** [netbox-community/netbox#10019]
### NetBox version

v3.2.8

### Feature type

Change to existing functionality

### Proposed functionality

Add tags as a funtionality when importing data via .csv File to directly add tags to imported ressources. 

### Use case

Directly add tags to the imported data from .csv files and eliminate the functionality to add the tags via custom scripts or via hand after having all the data imported.

**Comment by jeremystretch** [comment]
Thank you for submitting this issue, however it appears that this topic has already been raised. Please see issue #7376 for further discussion.
