### ISSUE TITLE
Table pagination issue 

### ISSUE THREAD

**Issue by atownson** [netbox-community/netbox#10017]
### NetBox version

v3.2.8

### Python version

3.8

### Steps to Reproduce

1. Create 26 Device Types of any kind
2. Navigate to the Device Types list table page: https://demo.netbox.dev/dcim/device-types/
3. Select 25 items per page

### Expected Behavior

Selecting 25 items per page should result in two pages, one with items 1-25 and another with item 26.

### Observed Behavior

All 26 items are returned on a single page:
![image](https://user-images.githubusercontent.com/52260120/184662417-c3fdbb1b-98d4-4280-8969-abe199fdd54b.png)
I was able to reproduce this on demo.netbox.dev.
This is also affecting the Interfaces table (and possibly others) in our environment:
![image](https://user-images.githubusercontent.com/52260120/184664816-79348f4e-4fa3-4db4-94fa-0698dc645aa8.png)

**Comment by jeremystretch** [comment]
This is a convenience feature. The paginator will automatically include the last few items in a set of results (up to 5 for page sizes up to 50) rather than showing a successive page. This avoid having to paginate one more time to view the final results with minimal additional overhead.
