### ISSUE TITLE
Filter by device does not work when querying for modules via API

### ISSUE THREAD

**Issue by agreusel** [netbox-community/netbox#10023]
### NetBox version

v3.2.7

### Python version

3.10

### Steps to Reproduce

1. Create module-type (module_a)

2. Create device type with module bay (device_type_a)

3. Create multiple devices using device_type_a (device_a, device_b)

4. Add modules to the module bays of each device created (device_a + module_a, device_b + module_b)

5. Confirm modules exist via GUI and API and have a device associated with them

6. Query the API with a filter for "device=device_a"
https://mynetboxinstance.com/api/dcim/modules/?device=device_a

7. Receive results for all modules in inventory, not just the one assigned to device_a (module_a & module_b)

### Expected Behavior

API query should only return module_a (associated with device_a)

### Observed Behavior

All modules in the database are returned (module_a & module_b)

**Comment by jeremystretch** [comment]
There is no `device` fitler for modules. You can use the `device_id` filter to search for modules installed within a particular device.
