### ISSUE TITLE
Automatically build JSON schema for the device type library with each release

### ISSUE THREAD

**Issue by jeremystretch** [netbox-community/netbox#10030]
### NetBox version

v3.2.9

### Feature type

New functionality

### Proposed functionality

Implement a mechanism for generating JSON schema for device type and related definitions. This could be a Django management command (e.g. `manage.py buildschema`), the output of which would be included with each NetBox release.

### Use case

The NetBox [devicetype library](https://github.com/netbox-community/devicetype-library) includes [JSON schema](https://github.com/netbox-community/devicetype-library/tree/master/schema) for validating device and module type definitions. These definitions must be kept up-to-date with NetBox itself, which is currently a manual process. Generating the schema automatically and publishing it with each NetBox release will remove this administrative burden.

Additionally, once we implement #4347, schema can be generated for all relevant models as an additional resource.

**Comment by ryanmerolle** [comment]
This could be a good candidate for 3.6

**Comment by danner26** [comment]
I agree this would be great!

**Comment by danner26** [comment]
I have marked the PR as ready for review. This should be ready to be merged. Let me know if you need anything changed
