### ISSUE TITLE
Display device name, as well as interface name, when listing terminations on an L2VPN

### ISSUE THREAD

**Issue by candlerb** [netbox-community/netbox#10035]
### NetBox version

v3.3-beta2

### Feature type

Change to existing functionality

### Proposed functionality

When you view an L2VPN, the page includes a table of terminations.  If those terminations are device or VM interfaces, then currently it shows only the interface name and not the device name.

This means it's very unclear, e.g. in the following these are actually two different interfaces on two different devices:
![image](https://user-images.githubusercontent.com/44789/184940298-5fc76423-52a4-4231-9d6c-c40825cd22e6.png)

I propose showing the device/VM name as well.

### Use case

UX: be able to see immediately which devices are involved.  Currently the only way to establish which devices these terminations go to is to click through them one by one.

### Database changes

None

### External dependencies

None

**Comment by candlerb** [comment]
Ref discussion: https://github.com/netbox-community/netbox/discussions/9727#discussioncomment-3409332

Implementation issue from @DanSheps:

> currently `display_name` for interface only shows the interface name. We could switch it to a template field, but then we will lose sorting

**Comment by jeremystretch** [comment]
There's already a separate column for displaying the assigned object's parent. This can be enabled by configuring the table under the L2VPN terminations list view. It probably makes sense to designate it as a default column though.

**Comment by candlerb** [comment]
That applies to the global list of terminations (`/ipam/l2vpn-terminations/`), but not where I was looking, which was the view page for a particular L2VPN (`/ipam/l2vpns/1/`).  There is a table of terminations but it is not configurable.

![image](https://user-images.githubusercontent.com/44789/185173336-12e7bb22-cba6-47c0-8e4a-08b3a715a4fb.png)

**Comment by jeremystretch** [comment]
Right, but it uses the same underlying table class, so the same configuration is used. Once you add the column to the L2VPN terminations table, it will show up here too. (We _should_ add a configure button to all such embedded tables, but that's a broader initiative.)

**Comment by candlerb** [comment]
I see... if I go to `/ipam/l2vpn-terminations/` and modify the table there, then return to `/ipam/l2vpns/1/`, it does show the extra column.
