### ISSUE TITLE
Global Search for Rack Reservation did not work

### ISSUE THREAD

**Issue by whtkam** [netbox-community/netbox#10057]
### NetBox version

v3.3.0

### Python version

3.9

### Steps to Reproduce

- Create a rack reservation from a rack
- Then use the global search to search for that rack (with the reservation)
- The following error message is displayed

<class 'AttributeError'>

Cannot find 'site' on RackReservation object, 'site' is an invalid parameter to prefetch_related()

Python version: 3.9.11
NetBox version: 3.3.0

### Expected Behavior

that the global search works as usual

### Observed Behavior

server error is displayed:

<class 'AttributeError'>

Cannot find 'site' on RackReservation object, 'site' is an invalid parameter to prefetch_related()

Python version: 3.9.11
NetBox version: 3.3.0

**Comment by arthanson** [comment]
I can take this
