### ISSUE TITLE
Wrong label for POE type in interface GUI

### ISSUE THREAD

**Issue by pdenessen** [netbox-community/netbox#10056]
### NetBox version

v3.3.0

### Python version

3.10

### Steps to Reproduce

1. Create an interface if not available
2. Select the interface and find 2x POE mode labels. The 2nd one must be POE Type instead of POE mode

### Expected Behavior

Display POE Type instead of POE mode

### Observed Behavior

POE mode is displayed 

![image](https://user-images.githubusercontent.com/11139454/185356666-58823372-afd1-4023-90c0-7e90461c7ad5.png)

**Comment by arthanson** [comment]
I can take this.
