### ISSUE TITLE
Include journal entries in global search

### ISSUE THREAD

**Issue by aswen** [netbox-community/netbox#10060]
### NetBox version

v3.2.7

### Feature type

Change to existing functionality

### Proposed functionality

When a search term is entered in the top-global search function, the contents of the journal should be searched as well.

### Use case

When I leave (for example) an issue number in a journal entry, it would be nice if I later were able to find all devices with that reference number in their journal. This way one can quickly see which devices were involved in an issue/incident.

### Database changes

As far as I can tell: no changes to the DB.

### External dependencies

No dependencies either.

**Comment by jeremystretch** [comment]
Blocked by #7016

**Comment by jeremystretch** [comment]
On second thought, I think we can proceed with including journal entries in the current implementation.
