### ISSUE TITLE
Static Media Failure appears sometimes

### ISSUE THREAD

**Issue by tobikris** [netbox-community/netbox#10069]
### NetBox version

v3.3.0

### Python version

3.10

### Steps to Reproduce

1. Go to https://demo.netbox.dev/ (happens only sometimes)

### Expected Behavior

The dashboard should be shown.

### Observed Behavior

I am occasionally redirected to https://demo.netbox.dev/media-failure/?filename=netbox-print.css. Retrying solves the issue.
I noticed this behavior first on my local instance and assumed a wrong configuration on my side.
Now it also happened on the demo instance.

**Comment by jeremystretch** [comment]
I'm not able to reproduce this. It may be an issue your browser's cache.
