### ISSUE TITLE
Slug for L2VPN has no unique constraint

### ISSUE THREAD

**Issue by v0tti** [netbox-community/netbox#10070]
### NetBox version

v3.3.0

### Python version

3.9

### Steps to Reproduce

1. Create a L2VPN with name `Test` and slug `test`
2. Create a L2VPN with name `Test2` and slug `test`

### Expected Behavior

I expect a warning to be displayed when trying to create the second L2VPN with the same slug as the one before. The slug should be an unique attribute. It is unique for other models i.e. Tenants.

### Observed Behavior

The second L2VPN is created without a warning or an error. Two L2VPN with the same slug exist at the same time.

**Comment by jeremystretch** [comment]
@DanSheps is this intentional or a bug?

**Comment by DanSheps** [comment]
This would be a bug.  Slug should have been unique.
