### ISSUE TITLE
Add device status color next to the device image in the rack view

### ISSUE THREAD

**Issue by salvadorb** [netbox-community/netbox#10083]
### NetBox version

v3.2.4

### Feature type

New functionality

### Proposed functionality

Add a small column with color according to the status of the device next to the device image in the rack view, 
<img width="1034" alt="Screen Shot 2022-08-20 at 08 21 30" src="https://user-images.githubusercontent.com/23199382/185748265-63dfdebe-6990-4675-832b-791a4e0df056.png">

### Use case

Facilitates the identification of the real status of the device in the rack is installed (active), planned, decommissioning or another status. Because in the current rack view it's not possible to see the real status in the rack, since many device could be planned but not installed in the rack, and the only way to see that is in the device list.

### Database changes

N/A

### External dependencies

N/A

**Comment by jeremystretch** [comment]
Thank you for submitting this issue, however it appears that this topic has already been raised. Please see issue #6059 for further discussion.
