### ISSUE TITLE
Add "switch utilization" - just like "rack utilization"

### ISSUE THREAD

**Issue by rtxtmardesen** [netbox-community/netbox#10084]
### NetBox version

v3.2.5

### Feature type

New functionality

### Proposed functionality

Just like the "Rack Utilization" information point, it would be great to see a switch and see how many ports are taken up. Beyond that, it would also be great to see (as an aggregate) the number of open ports that all the switches have in a specific rack. Maybe even site, location, etc.

### Use case

As a company who has netbox fully implemented, I am deciding which location/site to place a large unracked device that consumes 10+ ports on a switch. being able to see which lab has the most available ports would help solve this situation. 

Also, "do I need to purchase another switch?" questions can be solved sooner.

### Database changes

I know this would change some schema a little bit, unsure the finite details.

**Comment by DorianXGH** [comment]
At first glance, I think this can be done _relatively_ easily by :
 - Having an "interface utilization" for devices
 - Having a toggle for use in aggregate for each device (to distinguish switch-like devices from others)

**Comment by jeremystretch** [comment]
This doesn't seem practical IMO, for several reasons:

1. It's not typical that you decide where to put a device based on how many interfaces are available on a switch.
2. Your proposed implementation completely ignores interface types.
3. Utilization would be reported for _every_ device. Devices with a single connected interface would report 100% utilization.
