### ISSUE TITLE
Tags extra fields

### ISSUE THREAD

**Issue by AndreasMoe** [netbox-community/netbox#10085]
### NetBox version

V3.2.7

### Feature type

Change to existing functionality

### Proposed functionality

Possibility to use custom fields on Tags? Or add more fields? For example Comments in addition to description

### Use case

Adding extra information on what a tag is used for. For example "imported using script xxx"

**Comment by jeremystretch** [comment]
Tags are used for classifying other objects. They are not intended to store data themselves. You can add custom fields directly to other objects for this purpose.
