### ISSUE TITLE
Prefix cannot be assigned if the site is a member of a sitegroup

### ISSUE THREAD

**Issue by heiko-ma** [netbox-community/netbox#10104]
### NetBox version

v3.2.9

### Python version

3.10

### Steps to Reproduce

1. Create a VLAN Group (e.g. Global) with no scope filtering (should be usable everywhere)
2. Create a VLAN and assign it to the created VLAN group
3. Create a Prefix and assign it to any site which is a member of a sitegroup
4. Try to assign the Prefix to the created VLAN

### Expected Behavior

The VLAN group and the VLAN is selectable as the group has no filtering and should be considered "global".

### Observed Behavior

The VLAN group selection returns not results and the only usable VLANs are the ones assigned directly to the site or site group.
![image](https://user-images.githubusercontent.com/64192965/186125500-a9248e7a-d64f-421b-9330-b3097d41e202.png)

The interesting thing about this is the following:
When you remove all site and site group assignments and assign the VLAN group and VLAN, the site and site group can be assigned afterwards resulting in the following constillation:
![image](https://user-images.githubusercontent.com/64192965/186125411-9724927a-b693-4ec5-85bd-999d29c02214.png)

Is this a wanted behavior? I believe there is something wrong with the API-Request and there are to many filters so that no result is returned.

I want to provide a little context as why this is a problem:
We have some VLANs we use at every site of ours (e.g. VLAN 10). Instead of creating this vlan for every site, we'd like to create it once and assign all corresponding prefixes to it, resulting in a more structured VLAN database.

**Comment by IdRatherStand** [comment]
I can't help as to whether this is a bug or not - but we currently assign both a Site + Vlan Group as per your second screenshot, if the ability to do this is removed then this would cause us some headaches (we stretch some L2 between sites and the only way to represent this is in a VLAN group AFAIK)

**Comment by DanSheps** [comment]
I would call this more of a feature request.

Would you be willing to re-open this as such (Should be specific to prefixes, I don't think there are any data model changes needed, depending on what is being done)?

Also, I see this being related to #10054 somewhat

**Comment by heiko-ma** [comment]
Thank you for your response. If this isn't wanted behavior, I'll create a feature request as this could be useful for a couple of cases.
