### ISSUE TITLE
Issue creating virtual-machine with only cluster field filled in 

### ISSUE THREAD

**Issue by joeribloemen** [netbox-community/netbox#10131]
### NetBox version

v3.3.0

### Python version

3.10

### Steps to Reproduce

1. Go to virtual-machines tab under Virtualization
2. Click add virtual machine
3. Fill in name and cluster 
4. Click create and recieve error: the selected cluster (**** is not assigned to this site (None).)

### Expected Behavior

In the patch notes it stands that either site or/and cluster need to be assigned to the virtual machine. 

![image](https://user-images.githubusercontent.com/18398257/186421055-11370080-365a-4a37-90be-38a6327c75ff.png)

I expected if the site field is not filled in, the site field is just inherted from the cluster object.

Is this behavior normal ?

### Observed Behavior

Error
![image](https://user-images.githubusercontent.com/18398257/186422217-2720ac00-74db-4743-8455-5b6281def5fc.png)

**Comment by jeremystretch** [comment]
You've skipped the part where you create the cluster. If the cluster to which you're assigning the VM is associated with a site, then this is expected: Both the VM and its cluster must belong to the same site, or to no site.

I can confirm that creating a new cluster with no site assigned, and then creating a new VM assigned to that cluster works as expected on v3.3.0.

**Comment by joeribloemen** [comment]
Okey, Thanks for the explanation. 

Have a great day!

**Comment by bb-Ricardo** [comment]
Hey, just wondering. If the site is enforced by the cluster, and NetBox is aware of the cluster site, then why do I need to specify a site for the VM if the VM will be assigned to a cluster?

**Comment by jeremystretch** [comment]
VMs can also be assigned to a site without specifying a cluster, so an explicit entry is necessary for validation.

**Comment by bb-Ricardo** [comment]
That is a great feature, but then the site and cluster attribute should be mutually exclusive. You either select a site OR a cluster as the cluster enfaces the site attribute.
