### ISSUE TITLE
Minify response HTML

### ISSUE THREAD

**Issue by jeremystretch** [netbox-community/netbox#10138]
### NetBox version

v3.3.0

### Feature type

New functionality

### Proposed functionality

I'm opening this issue to explore the feasibility of implementing an HTML minifier such as [django-htmlmin](https://github.com/cobrateam/django-htmlmin) to optimize response body sizes for UI requests. Implementation seems pretty straightforward, however we'll need to do some testing to determine whether it's worth the additional overhead and dependency.

### Use case

Ostensibly removing unnecessary white space from response bodies will shrink their total size and result in slightly more efficient response times overall. However, as mentioned we'll need to evaluate the practical implications of implementing this.

**Comment by DanSheps** [comment]
How would this impact something like Napalm and the running config?  Can we wrap this in such a way we can exclude views from being minified?
