### ISSUE TITLE
Internal server error when searching for "SV" or "ME"

### ISSUE THREAD

**Issue by heiko-ma** [netbox-community/netbox#10146]
### NetBox version

v3.3.0

### Python version

3.10

### Steps to Reproduce

1. enter "SV" or "ME" in global search bar

### Expected Behavior

The search results are returned.

### Observed Behavior

The following error occurs:
![image](https://user-images.githubusercontent.com/64192965/186627188-e0c5bb74-a490-447c-939e-33b8ded8f9c2.png)

I didn't check every two letter combination but the error is always the same. I couldn't reproduce the error in the public demo instance. We currently use some rack reservations but none include the strings  above.

**Comment by jeremystretch** [comment]
Thank you for submitting this issue, however it appears that this topic has already been raised. Please see issue #10057 for further discussion.
