### ISSUE TITLE
More media types needed

### ISSUE THREAD

**Issue by rfreddy** [netbox-community/netbox#10153]
### NetBox version

V3.3.0

### Feature type

Change to existing functionality

### Proposed functionality

Please add more media types for the interfaces: 10GBASE-LR, 40GBASE-SR4, 100GBASE-LR4

### Use case

There are a myriad of interfaces media types for fiber links: XXGBASE-YY, where XX can be 10, 25, 50, 100 or 400 and YY can be SR4, LR4 or CR4. And new types keep coming up, can you please make this easy to add like a text file or a dictionary where we can add them?

**Comment by jeremystretch** [comment]
Interface types and media types are different attributes. Optical transceivers which service different media types can still use a common interface type (e.g. SFP+). That's why these don't exist in NetBox.
