### ISSUE TITLE
Inconclusive Commit Rate for Circuits for Germans

### ISSUE THREAD

**Issue by prauscher** [netbox-community/netbox#10157]
### NetBox version

v3.2.4

### Feature type

Change to existing functionality

### Proposed functionality

Change `humanize_speed` to always only show one decimal place

### Use case

German viewers can easily be confused when entering a Commit Rate for a circuit of 2048 Kbps. This will be rendered as "2.048 Mbps" with a default english locale. In german, this can easily be interpreted as "2048 Mbps" by interpreting the decimal dot as a thousand separator.

### Database changes

None

### External dependencies

None

**Comment by jeremystretch** [comment]
We're not going to exclude data for the sake of satisfying alternative interpretations. I'd be happy to start a conversation (in a new feature request) about the benefits and implications of [enabling localization](https://docs.djangoproject.com/en/4.1/topics/i18n/formatting/), but it needs to be handled properly.
