### ISSUE TITLE
Add a "best practices" guide for common modeling questions

### ISSUE THREAD

**Issue by jeremystretch** [netbox-community/netbox#10169]
### Change Type

Addition

### Area

Other

### Proposed Changes

Add a new section to the NetBox documentation to provide guidance on how best to model common scenarios. Example include:

* Determining when a custom field or plugin is appropriate
* VLANs which span an arbitrary domain
* How to handle dual-mode (multiple media) interfaces

Ideally, we should expand this content every time a similar question is raised by a user.

**Comment by DanSheps** [comment]
I know it isn't strictly related to code/docs, but we may want to add a "How do I do x" tag for discussions so we can more easily locate the types of questions too.

**Comment by arcticash** [comment]
Would definitely like this to become a feature, quite a few times I've wondered if I'm configuring things following best practice when setting up a new instance of NetBox.

**Comment by eronlloyd** [comment]
I will help with this effort. I'm currently working on a best practices blog post for modeling optical devices now that #9102 has been resolved, but will start a list of other common cases.
