### ISSUE TITLE
Space utilization starts at 1.2% for a new rack

### ISSUE THREAD

**Issue by abhi1693** [netbox-community/netbox#10176]
### NetBox version

3.3.1

### Python version

3.10

### Steps to Reproduce

1. Create a new rack named `Rack1`
2. Open the `Rack1` detail page and notice the space utilization value

### Expected Behavior

Space utilization for a new rack should always start at 0%

### Observed Behavior

Space utilization starts at 1.2%

![image](https://user-images.githubusercontent.com/5083532/187031378-f404e70b-daf4-40a4-b954-d8c4ec6eb171.png)

**Comment by kkthxbye-code** [comment]
I believe it's caused by Rack.get_available_units() not returning 42.5 as a valid position in a 42 U rack but Rack.units does include 42.5 as a valid position. So avaliable units in a 42 U rack will be 83 but the total units will be 84.

**Comment by VitMain** [comment]
It is also related to the problem with reservations. 
For example, we have a 46RU server cabinet, I reserved 1-46RU, and space utilization says that this cabinet is used only for 51.1%.
