### ISSUE TITLE
DCIM->Device: Add Manufacturer field to in single-device overview

### ISSUE THREAD

**Issue by pwrgfi** [netbox-community/netbox#10178]
### NetBox version

v3.3.1

### Feature type

New functionality

### Proposed functionality

The overview page for a single device, https://netbox/dcim/devices/1234/ , displays the "Device Type" attribute of the device, but not the manufacturer.

The Devices table on the other hand,  https://netbox/dcim/devices/  displays both columns by default and next to each other, so it's only once you actually click on one of those devices that you get less detail rather than more, losing the manufacturer.

Likely an oversight to not have it included on the single Device overview, or would there be a reason against?

Please add the Manufacturer (right before the Device Type line).

### Use case

We've got devices of several different manufacturers whose naming schema is surprisingly similar and displaying the model only leads to confusion that would be easily resolved with this simple change.

**Comment by jeremystretch** [comment]
IIRC the device type attribute previously displayed both the manufacturer name and model number, however we omitted the manufacturer from the DeviceType model's `__str__()` method some time back. We can add the manufacturer, but it should go on the same line as the device type model, as both are attributes of the assigned device type rather than the device itself.

**Comment by pwrgfi** [comment]
OK, so I didn't remember it wrong and it had been there in the past.

Both attributes in the same line was my first intuition as well, so no opposition from me. Link the "manufacturer" part to the manufacturer entry, analogous to the current "device type" hyperlink?

**Comment by jeremystretch** [comment]
> Link the "manufacturer" part to the manufacturer entry, analogous to the current "device type" hyperlink?

IMO we should keep the single link to the device type, to avoid confusion.

**Comment by jeremystretch** [comment]
Reclassifying this as a bug since omitting the manufacturer name was not intended behavior.
