### ISSUE TITLE
Vertical spacing uneven on child elements in table rows with non-standard height

### ISSUE THREAD

**Issue by ljarasius** [netbox-community/netbox#10184]
### NetBox version

v3.3.1

### Python version

3.10

### Steps to Reproduce

1. Create a device and assign to a rack
2. View the device in the UI
3. Observe the details under Device > Device > Rack

### Expected Behavior

Text within row is evenly spaced vertically
![image](https://user-images.githubusercontent.com/19970910/187103130-5afe1f57-f0cb-4b65-934e-cadfa2cd56be.png)

### Observed Behavior

Text within row is unevenly spaced vertically
![image](https://user-images.githubusercontent.com/19970910/187103090-7b089d8c-49d4-4d91-b68a-9d617db8b3e8.png)

**Comment by ljarasius** [comment]
Simply needs `vertical-align: middle;` added to the child elements within the table rows, happy to open a PR and complete this.

**Comment by jeremystretch** [comment]
Sounds good. Please ensure that the style is applied consistently to all attribute tables (not just the one in the example).

**Comment by jeremystretch** [comment]
> Simply needs `vertical-align: middle;` added to the child elements within the table rows

I think it's slightly more tricky than that because we're floating the button to the righthand side. I think I've devised a solution using BS5's [position utilities](https://getbootstrap.com/docs/5.0/utilities/position/) though.
