### ISSUE TITLE
Changelog Model

### ISSUE THREAD

**Issue by PaulR282** [netbox-community/netbox#10191]
### NetBox version

v3.2.9

### Feature type

Data model extension

### Proposed functionality

If you need the changelog for automation, currently you can only see it via the API. It would be great to have a model for internal use. 

### Use case

You need this model when writing a report where you need the changelog.

**Comment by jeremystretch** [comment]
It sounds like you're looking for assistance interacting with the ObjectChange model. Please open a [discussion](https://github.com/netbox-community/netbox/discussions/new) for this type of assistance rather than a feature request.

**Comment by PaulR282** [comment]
Thanks, I couldn't find the ObjectChange model, because it's not in the [documentaiton](https://docs.netbox.dev/en/stable/development/models/)
