### ISSUE TITLE
Enable support for half-rack width devices in Netbox

### ISSUE THREAD

**Issue by EduardMRG** [netbox-community/netbox#10192]
### NetBox version

v3.3.1

### Feature type

New functionality

### Proposed functionality

Enable support for half-rack width devices in Netbox (like Dell S5212F-ON for example).

### Use case

Some customers are using half-rack width devices in their datacenter, like our team and they need the same functionalities that Netbox is supporting for a full rack unit device to be applied on half-rack width devices.

Equipment example: Dell S5212F-ON (https://www.delltechnologies.com/asset/en-us/products/networking/technical-support/dell_emc_networking-s5200_on_spec_sheet.pdf)

**Comment by jeremystretch** [comment]
Thank you for submitting this issue, however it appears that this topic has already been raised. Please see issue #2467 for further discussion.
