### ISSUE TITLE
add cable type of 'console'.

### ISSUE THREAD

**Issue by ThomasADavis** [netbox-community/netbox#10209]
### NetBox version

v3.3.0

### Feature type

Change to existing functionality

### Proposed functionality

It's difficult to search in the new cable model for console cables.   I'd like to see the type of 'console' (like 'power') added to the cable choices.

### Use case

Searching for just console cables in the connections page is currently impossible.

### Database changes

Add 'console' to the cable types.

### External dependencies

None

**Comment by jeremystretch** [comment]
This is a good example of why NetBox does not permit users to define arbitrary cable types. "Console" is not a cable type: it is a functional classification. For example, a CAT5e cable could be used for either network or console connectivity.

> Searching for just console cables in the connections page is currently impossible.

There's a dedicated list of console connections under Connections > Console Connections.
