### ISSUE TITLE
Interface table row dropdown not rendered in Device Interfaces tab for users with correct permissions

### ISSUE THREAD

**Issue by atownson** [netbox-community/netbox#10208]
### NetBox version

v3.3.1

### Python version

3.8

### Steps to Reproduce

1. Create a user with permissions to view, add, and change dcim.device and dcim.interface.
2. Log in as the user created.
3. Select a Device (one that contains interfaces) and navigate to its details page and select the Interfaces tab.

### Expected Behavior

The blue dropdown should be rendered for each row.

![image](https://user-images.githubusercontent.com/52260120/187336685-699e77c5-74d2-4b38-8e8f-3b173ea87bcc.png)

### Observed Behavior

The blue dropdown is not rendered.

![image](https://user-images.githubusercontent.com/52260120/187336436-a37e00f6-c988-4ed9-b4dd-ddec20dd85e1.png)

**Comment by atownson** [comment]
There is a typo in [netbox/dcim/tables/template_code.py](https://github.com/netbox-community/netbox/blob/develop/netbox/dcim/tables/template_code.pyl) on line 229 causing this issue:

```
...
INTERFACE_BUTTONS = """
{% if perms.dcim.edit_interface %}
  <span class="dropdown">
...
```

Should be:

```
...
INTERFACE_BUTTONS = """
{% if perms.dcim.change_interface %}
  <span class="dropdown">
...
```

I can submit a PR for this if accepted.

**Comment by jeremystretch** [comment]
Thanks @atownson, I'll fix it. How else will I learn?
