### ISSUE TITLE
Rack links don't prepend HTTPS using documented RequestHeader "X-Forwarded-Proto"

### ISSUE THREAD

**Issue by tsbates** [netbox-community/netbox#10207]
### NetBox version

v3.2.8

### Python version

3.8

### Steps to Reproduce

1. Navigate to Organization, Racks & select a rack with an added device.
2. Click the device in the rack view

### Expected Behavior

The device appears on screen

### Observed Behavior

The page results in a 404 Not Found as 'https'.

**Comment by tsbates** [comment]
The apache configuration file within /contrib states the RequestHeader should be 
"RequestHeader set "X-Forwarded-Proto" expr=%{REQUEST_SCHEME}", however this fails to start apache. Setting "RequestHeader set "X-Forwarded-Proto" expr="%{REQUEST_SCHEME}e"" allows apache to start, however the observed behaviour is still present.

Setting the RequestHeader as follows results in the correct behaviour:

"RequestHeader set X-Forwarded-Proto https env=HTTPS"

**Comment by jeremystretch** [comment]
I have verified that the configuration as it exists now works as expected under Apache 2.4.29:

```
RequestHeader set "X-Forwarded-Proto" expr=%{REQUEST_SCHEME}
```

With this line in place, absolute URLs (such as those within rack elevations) are generated with the `https://` prefix. Without it, the prefix does not appear. If this is not the case for you, it's likely that you need to upgrade your Apache installation.

I'm going to close this report as invalid. If you need further assistance please open a new [discussion](https://github.com/netbox-community/netbox/discussions/new).
