### ISSUE TITLE
IPAM Services retrievable by API 

### ISSUE THREAD

**Issue by D1StrX** [netbox-community/netbox#10219]
### NetBox version

v3.3.1

### Feature type

New functionality

### Proposed functionality

Extension on existing functionality IPAM -> Services. It is nice that service ports can be added to devices/virtual machines through GUI. Would be nice to be able to retrieve/put the data listed under IPAM -> Services and/or get Services associated with Virtualmachine/Device back when using /virtualization/virtual-machines.

### Use case

Automate stuff that require (service)ports. For example for Ansible to configure Firewalls. HAproxy loadbalancers to automate backends (IP + Port). Probably a lot of more use cases, hopefully getting added in the comments.

### Database changes

I don't know. Probably yes.

### External dependencies

Don't think so.

**Comment by jeremystretch** [comment]
A REST API endpoint (`/api/ipam/services/`) already exists to facilitate the creation of services and their attachment to devices and virtual machines. If this is not what you're requesting, please rewrite your initial post above to more clearly convey the proposed change(s).

**Comment by D1StrX** [comment]
Refined the description

**Comment by jeremystretch** [comment]
> When requesting a Virtual-machine data through GET it doesn't return the associated Service ports.

This is an established pattern for all related objects in NetBox and we won't deviate from it. You can use the services endpoint I mentioned to retrieve this data.

> Improved search on the RestAPI docs page

This needs to be a separate FR.
