### ISSUE TITLE
Tracing single cable to multiple front-ports with separate rear-ports causes exception

### ISSUE THREAD

**Issue by DanSheps** [netbox-community/netbox#10217]
### NetBox version

v3.3.1

### Python version

3.10

### Steps to Reproduce

1. Create Site
2. Create Device Role
3. Create Device Type for switch (at least 1 interface)
4. Create Device Type for patch panel (at least 2 rear ports with 1 position each connected to 2 front ports)
5. Create 2 Devices for patch panel
6. Create 1 Device for switch
7. Connect interface on switch to 2 front ports
8. Connect rear ports on patch panel 1 to rear ports on patch panel 2
9. Attempt a trace

### Expected Behavior

Trace completes successfully

### Observed Behavior

Trace fails with exception:

```
ValueError at /dcim/interfaces/2374/trace/
Cannot query "<FrontPort on Panel 1>": Must be "RearPort" instance.
Request Method:	GET
Request URL:	http://127.0.0.1:8000/dcim/interfaces/2374/trace/
Django Version:	4.0.7
Exception Type:	ValueError
Exception Value:	
Cannot query "<FrontPort on Panel 1>": Must be "RearPort" instance.
```

**Comment by DanSheps** [comment]
I have added a diagram for clarity:

![Diagram](https://user-images.githubusercontent.com/11049792/187531275-2bcc9707-0429-4a52-907b-8056e35832f3.PNG)

**Comment by jeremystretch** [comment]
To be clear, tracing across the first topology is not supported as the path splits across multiple cables. However, tracing in this situation should inform the user of a split path and present options for continuing the trace, rather than raising an exception.
