### ISSUE TITLE
Bulk Edit for Newly Imported Items

### ISSUE THREAD

**Issue by NavyWings** [netbox-community/netbox#10242]
### NetBox version

v3.2.2

### Feature type

Change to existing functionality

### Proposed functionality

After bulk importing of items (Devices in this particular example), the "Import Completed" page is displayed with a list of items imported. I propose adding a "Bulk Edit" option similar to most lists of objects in Netbox.

<img width="911" alt="image" src="https://user-images.githubusercontent.com/48529747/187970499-2f589df2-8a6f-4d4b-9895-daf5abbcf23a.png">

### Use case

Imports may or may not require corrections following import. After import, there may not be a unique way of selecting the new objects that were imported if edits need to be made. By having a bulk edit feature available on the "Import Completed" page, it would easily allow edits to be made to the newly imported objects.

### Database changes

Likely no new DB changes

### External dependencies

None

**Comment by jeremystretch** [comment]
I think the ideal approach here would be to ditch the static rendering of imported objects, and replace it with a redirect to the normal objects list that's been filtered to display only the newly-imported items. I'm just not sure how to best do that short of appending a ton of `?id=101&id=102&id=103` cruft. Will have to think about this some more.

**Comment by jeremystretch** [comment]
@DanSheps Possibly, but it probably wouldn't be very efficient. We'd probably also be risking a race condition since the creation of change records is queued.

**Comment by jeremystretch** [comment]
I've opened #11494 to test out Dan's idea above. Marking this as blocked for now, but the approach seems very promising.
