### ISSUE TITLE
Add custom validation functionality for the models' delete method

### ISSUE THREAD

**Issue by atownson** [netbox-community/netbox#10244]
### NetBox version

v3.3.1

### Feature type

New functionality

### Proposed functionality

NetBox's extensible custom validation is a very nice feature which allows users to inject their own business-specific logic into the models' create and update methods. I'm proposing to add the same functionality to the delete method.

### Use case

Users would be able to add their own logic to ensure instantiated models are not unintentionally deleted or to better control cascading effects of a delete. One example use case would be to ensure no IP addresses are assigned to a device's or virtual machine's interfaces before deleting either the device/VM or one of its interfaces. In our deployment of NetBox we track a good bit of metadata associated with IP addresses (such as NATs, ICMP polling status, and monitoring flags) and typically assign already created IPs to interfaces rather than creating them when assigning them.

### Database changes

None

### External dependencies

None

**Comment by jeremystretch** [comment]
Interesting idea. We could probably implement this by hooking into the `pre_delete` signal to run validation. But how should we differentiate save and deletion validation rules? (Presumably they're likely to be different.)

**Comment by jeremystretch** [comment]
Maybe we call them something like "protection rules" instead, and just use the same configuration format that we do for validators.

**Comment by kkthxbye-code** [comment]
I think this would be a good addition. Open to any contributors, otherwise I'll pick it up when I get time.

**Comment by jeremystretch** [comment]
I'm going to tag this as `needs milestone`; hopefully we can get to it in a future release.

**Comment by BarbarossaTM** [comment]
Love this! This would be very handy for us so only devices in a certain status could be deleted (we've introduced `Disposed` in our life cycle).

**Comment by pv2b** [comment]
Hi!

I'd be interested to volunteer on implementing this, it seems like a small, self-contained feature and straight-forward enough. But it's set as "needs milestone", I'm not sure what that means in the context of this project?

**Comment by jeremystretch** [comment]
@pv2b I've just tagged this for the upcoming v3.7 release if you'd like to work on it. (Please base your work on the `feature` branch.)

**Comment by pv2b** [comment]
> @pv2b I've just tagged this for the upcoming v3.7 release if you'd like to work on it. (Please base your work on the `feature` branch.)

I'll be happy to work on this, but I'd like to see some progress on my other PR's on this project for work on accepted bug fixes before I do. I don't want to add too much to the projects backlog of pull requests.
