### ISSUE TITLE
Prefixes list from Aggregates list does not work

### ISSUE THREAD

**Issue by zuokot** [netbox-community/netbox#10259]
### NetBox version

v3.3.2

### Python version

3.8

### Steps to Reproduce

Add Aggregate 192.168.0.0/21
Add Prefix 192.168.0.0/24
Go to Aggregates and open the Aggregate 192.168.0.0/21, and then click "Prefixes"

### Expected Behavior

There should be a list of prefixes beloging to 192.168.0.0/21, in this case 192.168.0.0/24

By creating additional "Container" status type of prefix 192.168.0.0/21, there is the expected behavior.

### Observed Behavior

The outcome is:
--------
Server Error
There was a problem with your request. Please contact an administrator.

The complete exception is provided below:

<class 'django.urls.exceptions.NoReverseMatch'>

Reverse for 'prefix' with arguments '(None,)' not found. 1 pattern(s) tried: ['ipam/prefixes/(?P<pk>[0-9]+)/\\Z']

Python version: 3.8.10
NetBox version: 3.3.2
---------

By creating additional "Container" status type of prefix 192.168.0.0/21, there is the expected behavior.
![prefix_error](https://user-images.githubusercontent.com/91075161/188440343-750b2309-4936-4975-8b26-b4f1acb8a0b1.PNG)

**Comment by jeremystretch** [comment]
Thank you for opening a bug report. I was unable to reproduce the reported behavior on NetBox v3.3.2. Please re-confirm the reported behavior on the current stable release and adjust your post above as necessary. Remember to provide detailed steps that someone else can follow using a clean installation of NetBox to reproduce the issue. Remember to include the steps taken to create any initial objects or other data.

**Comment by zuokot** [comment]
Hi, 
Interesting founding which corrected the issue.
On the "Prefixes" page there is for some reason a header column "Prefix (flat)" chosen instead of "Prefix" and as soon as changed it to back to "Prefix", the problem disappeared. 

![prefixes_headers](https://user-images.githubusercontent.com/91075161/188913652-58ff5593-ad41-4b21-affb-56ba577bc490.PNG)
