### ISSUE TITLE
Device components: Extend filter criteria by "device type"

### ISSUE THREAD

**Issue by Daniel841511** [netbox-community/netbox#10251]
### NetBox version

v3.2.2

### Feature type

New functionality

### Proposed functionality

Currently device components like interfaces, ports or module bays can be filtered in device section by region, site group, site, location, virtual chassis and device. I would propose to add "device type". This can be helpful updating components from multiple existing devices.

### Use case

If there is a mistake in the modelling of a device type (e.g. wrong interface type or missing labels on components) and the components needs to be updated, deleted and recreated. 
This applies mainly to the situation when you must not delete existing devices from that type (e.g since devices are already transfered to other IT systems with its parameters).
By filtering device compoentes (like interfaces) by device type you could easily delete them and insert new ones by CSV import fuction.

### Database changes

no changes to db

### External dependencies

no dependencies

**Comment by jeremystretch** [comment]
There is no relationship from an instantiated component (such as an interface) to the device type from which it was originally defined (if there even was one), so I don't think what you're describing is feasible.

> If there is a mistake in the modelling of a device type (e.g. wrong interface type or missing labels on components) and the components needs to be updated, deleted and recreated.

You can easily write a [report](https://docs.netbox.dev/en/stable/customization/reports/) to perform this validation across all devices if needed.

**Comment by jeremystretch** [comment]
I'm going to close this as the proposed functionality doesn't seem feasible, and there are other potential solutions available. However you're welcome to ask that this be re-opened if you would like to draft a specific implementation that you believe would deliver the prescribed functionality.
