### ISSUE TITLE
UI Improvements for Cables with multiple terminations on different devices

### ISSUE THREAD

**Issue by liquid-metal** [netbox-community/netbox#10264]
### NetBox version

v3.3.2

### Feature type

Change to existing functionality

### Proposed functionality

When a cable with multiple terminations is connected to different devices on the same side, the UI could be improved in two places:

- On the "Add a new cable" page: When interfaces of multiple devices are selected, the associated device in the interface section is not clear. In the following screenshot, I have connected test-device1(i1) with test-device2(i1), test-device3(i2) and test-device3(i3). This is not clear in the selection. Proposal: if interfaces of multiple devices are present, add the device name (e.g. i1 (test-device2), i2 (test-device3), i3 (test-device3) in the example):
![2022-09-06_13 06 52_screenshot](https://user-images.githubusercontent.com/56035107/188621282-9d19813b-e459-45fb-b6f0-7ee75ab4110f.png)

- ~In the cable trace view: Same scenario as described above. If I trace the cable now, it is not clear which termination belongs to which device. I would propose that the boxes for the terminations do not fill the entire width, but they should be grouped by the corresponding device.~
![2022-09-06_13 11 32_screenshot](https://user-images.githubusercontent.com/56035107/188622181-8c96abcc-5ec6-4fe3-9aef-2915607763e1.png)

### Use case

Improve visibility in the UI

### Database changes

Probably none

### External dependencies

none

**Comment by jeremystretch** [comment]
> In the cable trace view

Please open a separate FR for this as it is unrelated to the first item.

**Comment by DanSheps** [comment]
A similar issue happens with vlans.  Perhaps it might be useful to have a "verbose" display name on all models which includes some parent model information (Device/Site/etc)

**Comment by jeremystretch** [comment]
I'd still like to tackle this. We just need to figure out how to implement the logic in the SVG rendering.

**Comment by DanSheps** [comment]
Pretty sure this should still be opened...
