### ISSUE TITLE
Display updates available for current major version

### ISSUE THREAD

**Issue by PieterL75** [netbox-community/netbox#10269]
### NetBox version

v3.3.2

### Feature type

Change to existing functionality

### Proposed functionality

The 'new update available' always shows the newest available version.
It would benefit, if the updates for the current main version are displayed, in addition to the latest available.

### Use case

We have to stick with 3.2 due to the API changes in 3.3
The update versions show the latests availabe (3.3.2). but not if there is a new version for the current train (3.2.9)
This causes us to miss out on patch releases of the current major/minor version

**Comment by jeremystretch** [comment]
> We have to stick with 3.2 due to the API changes in 3.3

There are no v3.2 releases after v3.3.0, so once you've upgraded to the last v3.2 release, you can simply disable the release checking if desired by setting [`RELEASE_CHECK_URL`](https://docs.netbox.dev/en/stable/configuration/miscellaneous/#release_check_url) to `None`.
