### ISSUE TITLE
Display whole rackunits in stead of .0

### ISSUE THREAD

**Issue by PieterL75** [netbox-community/netbox#10268]
### NetBox version

v3.3.2

### Feature type

Change to existing functionality

### Proposed functionality

Netbox supports half rack units ss of 3.3.0,
As of then, all units are displayed with a .0 in the end

This causes some confusion, as people did not notice the dot on their 4K screen with very small fonts (sigh)

Is it possible to show only the .5 when used and drop the .0 at all times ?

### Use case

The .0 can cause confusion (unit 1.0 could be read as unit 10)
If you don't use half units at all in your dcim, then it looks like a bug to display the .0 at the end

### Database changes

None

### External dependencies

None

**Comment by jeremystretch** [comment]
> Is it possible to show only the .5 when used and drop the .0 at all times ?

We always treat the unit number as a decimal value for consistency. Having to accommodate both integers and decimal values for a field would make development in a strongly-typed language such as Go extremely difficult.

> This causes some confusion, as people did not notice the dot on their 4K screen with very small fonts (sigh)

I'm sure this won't come as a surprise, but this isn't valid justification for changing how NetBox conveys numeric values.

**Comment by PieterL75** [comment]
I'm very sorry to say, but this .0 after the rackunits so... 'unprofessional' (for lack of a better word).
It really looks like you forgot to cleanup the output.

Do give it some second thoughts, I'll appreciate it.
I'm even good to give it a go to implement it
may with a configuration variable (show decimal rack units), that people can choose how it is displayed.

**Comment by jeremystretch** [comment]
> I'm very sorry to say, but this .0 after the rackunits so... 'unprofessional' (for lack of a better word).

You're welcome to your opinion, but as I've explained this is not a cosmetic decision and won't be changed.

**Comment by jeremystretch** [comment]
@PieterL75 were you referring to the display of the assigned position of a device under the UI?

![Screenshot 2022-09-07 at 12-14-18 dmi01-albany-rtr01 NetBox](https://user-images.githubusercontent.com/13487278/188928363-15c328a1-c5be-434a-8984-eca2a65fa889.png)

I'd be fine with omitting the trailing .0 there, just not in the API or programmatic representation of the `position` value. (We already do this for the selection dropdown as pictured below.)

![Screenshot from 2022-09-07 12-17-02](https://user-images.githubusercontent.com/13487278/188929241-6ba2615c-3ef7-4857-a9aa-919673946496.png)

**Comment by PieterL75** [comment]
Jeremy,
Yes, that is exactly what I was referring to.
also the Position(U) field in the device list
https://demo.netbox.dev/dcim/devices/

I agree that it should not be changed in the API or anywhere also, only in some visualization on the GUI

thx to reconsider !
