### ISSUE TITLE
"Create & Add Another" is not working for rack photos

### ISSUE THREAD

**Issue by Petrapana** [netbox-community/netbox#10278]
### NetBox version

v3.3.2

### Python version

3.8

### Steps to Reproduce

1. Open your RACK
2. Click on "Attach an image"
3. Select an image you want to add, put some name
4. Click on  "Create & Add Another is not working"
5. Netbox will add the image correctly, but forward URL is not correct and you are forwarded to "https://server/extras/image-attachments/add/" instead of "https://server/extras/image-attachments/add/?content_type=31&object_id=<dependsOnYourRackID>"

### Expected Behavior

You are forwarded to the same URL as used while clicking to "Attach an image" from the "rack page"

### Observed Behavior

"Page Not Found" is shown

**Comment by jeremystretch** [comment]
Could be a regression of #7741
