### ISSUE TITLE
Create pyproject.toml to define linter rules

### ISSUE THREAD

**Issue by jeremystretch** [netbox-community/netbox#10298]
### Proposed Changes

A proposal was raised during today's maintainers' meeting to introduce a `pyproject.toml` (see [PEP 518](https://peps.python.org/pep-0518/)) file to define the linting rules used in the project. We currently have a pre-commit hook which (among other things) runs `pycodestyle` with a few arguments to control the rules being applied. The goal here is to document these rules for discovery by a contributor's IDE.

### Justification

Lowers development friction for contributors using different IDEs and tool sets.

**Comment by jsenecal** [comment]
Turns out that pycodestyle rejected the idea of supporting pyproject.toml file for configuration as noted in [this pinned issue](https://github.com/PyCQA/pycodestyle/issues/813) (Thanks Jeremy)

This may end up bigger than expected if we have to move to something else?
