### ISSUE TITLE
Add svg support for device type pictures

### ISSUE THREAD

**Issue by PaulR282** [netbox-community/netbox#10295]
### NetBox version

v3.3.2

### Feature type

New functionality

### Proposed functionality

It would be nice to have support for .svg files when uploading a picture for a device type.

### Use case

You often get vector graphics, like SVG files when downloading pictures of devices. We also youse vector graphics when creating images of devices you can't find online. It would be nice to be able to upload a vector graphic file since the rack view is also rendered as SVG.

**Comment by jeremystretch** [comment]
There are a few consideration with this. The first is that Django's ImageField doesn't support SVG images. We could work around that by switching to a generic FileField, however we lose some of ImageField's convenience.

The other concern would be handling SVG images embedded within a rack elevation, which is itself an SVG image. We currently embed raster images via the `<image>` element. AFAICT this should work for SVG images as well, though I'm not sure if there are any caveats regarding browser support, etc.

**Comment by jeremystretch** [comment]
Going to punt on this until we have a better idea of how to handle SVG images in general. Definitely seems like something that should be handled either upstream in Django itself, or via a third party library.
