### ISSUE TITLE
run script permission constraint

### ISSUE THREAD

**Issue by swoga** [netbox-community/netbox#10306]
### NetBox version

v3.3.2

### Python version

3.10

### Steps to Reproduce

1. Create a custom script eg. `ip_assign.py` with class `IpAssign`
2. Confirm `id` via API: `/api/extras/scripts/ip_assign.IpAssign`
3. Create a new permission (`/admin/users/objectpermission/add`) with following properties:
Actions: `Can view`
Additional actions: `run`
Object types: `Extras > script`
Constraints: `{"id": "ip_assign.IpAssign"}`
5. Exception is thrown

### Expected Behavior

new permission with constraint to run this script

### Observed Behavior

<class 'ValueError'>

Field 'id' expected a number but got 'ip_assign.IpAssign'.

**Comment by kkthxbye-code** [comment]
This is not a bug, using the object permissions on individual scripts is not supported. You are welcome to create a feature request instead.
