### ISSUE TITLE
Interface PoE type reference error

### ISSUE THREAD

**Issue by endreszabo** [netbox-community/netbox#10307]
### NetBox version

v3.3.2

### Python version

3.10

### Steps to Reproduce

When choosing interface PoE type, select `Passive 48V (2-pair)`, option `Passive 48V (4-pair)` will be chosen instead.

PoE type of `Passive 48V (2-pair)` could not be selected as `Passive 48V (4-pair)` had the same key for that value.

### Expected Behavior

Option `Passive 48V (2-pair)` should be selected.

### Observed Behavior

Option `Passive 48V (4-pair)` will be chosen instead.

**Comment by endreszabo** [comment]
The first item in the tuple is wrong here: https://github.com/netbox-community/netbox/blob/develop/netbox/dcim/choices.py#L1099

**Comment by arthanson** [comment]
@endreszabo Thanks for tracking this down.
