### ISSUE TITLE
Missing serializer for LinkPeer

### ISSUE THREAD

**Issue by tobikris** [netbox-community/netbox#10308]
### NetBox version

v3.3.2

### Python version

3.10

### Steps to Reproduce

1. Download the OpenAPI schema from http://demo.netbox.dev/api/docs/\?format\=openapi
2. Investigate the Schema for CircuitTermination.

### Expected Behavior

The Schema should include a NestedLinkPeer representation including its attributes.

### Observed Behavior

Instead it seems there is some kind of dummy in the schema.

```
                    "title": "Link peer",
                    "description": "\nReturn the appropriate serializer for the link termination model.\n",
                    "type": "object",
                    "additionalProperties": {
                        "type": "string",
                        "x-nullable": true
                    },
                    "readOnly": true
```

The same thing applies to several other models (I think all that can have link peers).

I went searching through the code but unfortunately do not understand the details of the automatically generated schema.
I would love to get this fixed as it currently requires me to fix the generated code manually and updates are very hard in this way.
Let me know if I can be of any help here.

**Comment by arthanson** [comment]
marking as blocked for #9608 see: https://stackoverflow.com/questions/36576447/swagger-specify-two-responses-with-same-code-based-on-optional-parameter 
This isn't really a dummy return, there is no NestedLinkPeer model, the return can be one of a couple different types, but OpenAPI 2 doesn't look like it can support this.  OpenAPI 3 does have a convention for this.
