### ISSUE TITLE
Cloning Custom Fields does not clone anything

### ISSUE THREAD

**Issue by dreng** [netbox-community/netbox#10304]
### NetBox version

v.3.3.2

### Python version

3.9

### Steps to Reproduce

1. Navigate to "Other -> Custom Fields"
2. Click any Custom Field in order to show its details
3. Click the green "Clone" button

### Expected Behavior

Some values of the cloned Custom Field should be adopted, at least Model(s), Type, Object Type, Required, Filter logic, UI visibility.

### Observed Behavior

There's no difference whether you press Clone or Add (in Custom Fields overview). Cloning behaves just like adding a new Custom Field.

**Comment by jeremystretch** [comment]
It would make sense to enable this for custom links as well.
