### ISSUE TITLE
Virtual Chassis master field cannot be null according to the API

### ISSUE THREAD

**Issue by RobinGeuze** [netbox-community/netbox#10305]
### NetBox version

v3.2.9

### Python version

3.10

### Steps to Reproduce

1. Submit API write request to the VirtualChassis with "master": null in it

### Expected Behavior

Requests is accepted and the master is unset for the specific VirtualChassis

### Observed Behavior

HTTP 400 is returned with the message: `[{"master":["This field may not be null."]}]`

**Comment by RobinGeuze** [comment]
It probably needs allow_null=True and default=None here: https://github.com/netbox-community/netbox/blob/master/netbox/dcim/api/serializers.py#L1079

**Comment by DanSheps** [comment]
@RobinGeuze do you want to take this issue?

**Comment by sasschary** [comment]
I'll grab this if not, seems like a simple enough fix

**Comment by RobinGeuze** [comment]
I won't really have time to pick this up myself the coming weeks, so if somebody else could pick this up it would really be appreciated :)
