### ISSUE TITLE
1/2 Width Rack Items

### ISSUE THREAD

**Issue by Memorist23** [netbox-community/netbox#10303]
### NetBox version

v3.2.7

### Feature type

New functionality

### Proposed functionality

Tick box for 1/2 Width item
Maybe next to Full Depth Check box?

### Use case

There are more and more compact devices for small to medium companies coming out.
Specifically for storage fabric layers.
Mellanox now Nvidia have a few in their SN2000 series we have a few [SN2100's.](https://support.mellanox.com/s/productdetails/a2v50000000dZMZAA2/sn2100)
Cisco, FS, Netgear have models in this range that i know of. I'm sure other vendors do too.

[Demuxs](https://www.fs.com/au/products/126902.html) for Site to Site Dark fiber connection over different light waves are usually 1/2 width, we have 4 of these.
Primarily used for Office to DC's.

I would love to have this option available.

### Database changes

No sure, There will be some graphical change in the Rack section.
Other than that I can't see much more of a change.

### External dependencies

No i doubt it.

**Comment by jeremystretch** [comment]
Thank you for submitting this issue, however it appears that this topic has already been raised. Please see issue #2467 and #6591 for further discussion.
