### ISSUE TITLE
Option to edit a device directly out of the rack view

### ISSUE THREAD

**Issue by heiko-ma** [netbox-community/netbox#10329]
### NetBox version

v.3.3.2

### Feature type

New functionality

### Proposed functionality

When selecting device in a rack, the device overview is opened and the device must be edited via the corresponding button. After saving the changes, the user gets redirected back to the device overview.
When editing multiple devices in a rack (e.g. moving many patchpanels), this flow can be tedious as the user must navigate back to the rack every time.
It would be benificient if there would be a button beside the rack device which leads directly to the editing dialog and returns to the rack after editing
The flow would be like this:
- Open rack "foo"
- Edit the device "bar" via the button
- Make the changes and click "save"
- Get redirected back to rack "foo"

This can be achieved by inserting an identifier in the edit url which represents the rack id from which the request originated from:
/dcim/devices/1633/edit/?rack_id=80
Alternatively, the rack id can be retrieved through the device itself as it is linked with the rack.

This kind of flow could also be implemented for creating new devices.

### Use case

This change would benefit the fluentness of editing a multiple devices in a rack as the user gets redirected to the rack every time and doesn't need to navigate back to it.

**Comment by jeremystretch** [comment]
> It would be benificient if there would be a button beside the rack device which leads directly to the editing dialog and returns to the rack after editing

There are several challenges to this. First, where would you put the button? The rack elevations are already pretty crowded as-is. Second, you would need a mechanism to include the button only when appropriate. Rack elevations may be embedded on pages outside of NetBox (e.g. in a corporate wiki) where it would not make sense to display such controls.

> When editing multiple devices in a rack (e.g. moving many patchpanels), this flow can be tedious as the user must navigate back to the rack every time.

Apologies if this sounds blunt, but why not just open the device view in a new browser tab each time?

**Comment by heiko-ma** [comment]
> There are several challenges to this. First, where would you put the button? The rack elevations are already pretty crowded as-is. Second, you would need a mechanism to include the button only when appropriate. Rack elevations may be embedded on pages outside of NetBox (e.g. in a corporate wiki) where it would not make sense to display such controls.

To clarify, I'm not talking about the rack elevations, you're right, it wouldn't make sense to display those controls there. I'm talking about the rack itself:
![image](https://user-images.githubusercontent.com/64192965/189694563-36ff17fc-9d29-49bf-9ed9-bfd3c7c5991b.png)

I think, it would be possible to display a button next to each height unit.

> Apologies if this sounds blunt, but why not just open the device view in a new browser tab each time?

No worries, I can see where you're coming from, and in a normal desktop environment this procedure works just fine. Currently, we are testing out using netbox on android tablets in order to quicker document racks while on site. On android, navigation through those tabs can be quite a drag (especially when you have a ton of devices to edit) whereas the rest of the workflow is really smooth because you get redirected to the right page after each edit (e.g. connecting devices or creating interfaces). I hope this could clarify our approach and why i made this FR

**Comment by jsenecal** [comment]
Just throwing ideas here, would it work if you were to be redirected back to the Rack elevation page when editing a device if you accessed said device from a Rack elevation ?

**Comment by jeremystretch** [comment]
> To clarify, I'm not talking about the rack elevations, you're right, it wouldn't make sense to display those controls there. I'm talking about the rack itself:

When I say "elevations" I'm referring to the images on the righthand side of the screenshot you shared, showing the front and back of the rack. (We use the term "elevation" as in an architectural drawing showing a building as viewed from the street.) Is that what you're referring to?

**Comment by heiko-ma** [comment]
> When I say "elevations" I'm referring to the images on the righthand side of the screenshot you shared, showing the front and back of the rack. (We use the term "elevation" as in an architectural drawing showing a building as viewed from the street.) Is that what you're referring to?

That is correct.

> Just throwing ideas here, would it work if you were to be redirected back to the Rack elevation page when editing a device if you accessed said device from a Rack elevation ?

That was my first thought, though it would be a bit difficult to determine if the device was accessed via an elevation.
