### ISSUE TITLE
Option to add interfaces

### ISSUE THREAD

**Issue by KaleBrink** [netbox-community/netbox#10332]
### NetBox version

v3.3.2

### Feature type

New functionality

### Proposed functionality

I maintain the Netbox environment for the company I work for. I got a question if it was possible to add interface types to Netbox. I told them that out of the box it is not possible. But I did find out that I can edit the choises.py file and add the requested interfaces from there. But I need to copy those changes after each Netbox update.

Would it be possible to have an include file? So I can make the changes wanted by my colleague in that file, and with a Netbox update I only need to copy the files. Instead of going thru the file again to see where I made the changes.

### Use case

Netbox users are then able to add interfaces them self. If a interfaces is out of the scope of Netbox, like SAS, the user is still able to add these interfaces, and is responsible for his own changes.

**Comment by jeremystretch** [comment]
Please see [this FAQ](https://github.com/netbox-community/netbox/wiki/Frequently-Asked-Questions#how-can-i-add-new-interface-types) on our wiki.
