### ISSUE TITLE
Document how plugin settings are used

### ISSUE THREAD

**Issue by hagbarddenstore** [netbox-community/netbox#10346]
### Change Type

Addition

### Area

Functionality/features

### Proposed Changes

In the plugin development section, it is not documented how a plugin should access its own settings.

```
from django.conf import settings

settings.PLUGINS_CONFIG['plugin_name']['settings_key']
```

This method works and is Django standard, but NetBox populates the dict with the defaults from the plugin configuration.

I think this should be documented.

**Comment by DanSheps** [comment]
I think an associated templatetag might also be wise.
