### ISSUE TITLE
Add new interface and cable types to model direct interface connections to backplanes

### ISSUE THREAD

**Issue by phurrelmann** [netbox-community/netbox#10356]
### NetBox version

v3.3.0

### Feature type

New functionality

### Proposed functionality

Blades (and router/switch modules) often provide network connections via direct physical connections on their backplane. The interface then is directly wired over the backplane. There are proper IEEE standards defined for 1G (1000BASE-KX, see https://en.wikipedia.org/wiki/Gigabit_Ethernet), for 10G (10GBASE-KX4 and 10GBASE-KR, see https://en.wikipedia.org/wiki/10_Gigabit_Ethernet#10GBASE-KR), for 40G and 100G (40GBASE-KR4, 100GBASE-KP4, 100GBASE-KR2 and 100GBASE-KR4, see https://en.wikipedia.org/wiki/100_Gigabit_Ethernet).

To model and trace backplane network interfaces I'd also like to add the generic cable type "Backplane" to document, that the cable is indeed a direct physical copper connection.

**Summary:**

1. Add new cable type "Backplane" to section of copper cables
2. Add new interface types to section "Ethernet (fixed)"

Interface types to be added:

- 1000BASE-KX
- 10GBASE-KR
- 10GBASE-KX4
- 40GBASE-KR4
- 100GBASE-KP4
- 100GBASE-KR2
- 100GBASE-KR4

If accepted I'll try to add/implement those new interface and cable type myself and submit a PR.

### Use case

Model physical interfaces connected directly to a backplane and make this visible with the correct cable of type "Backplane".
We have lots of bladecenters and blades where the interfaces of blades blade are directly wired to the backplane. Currenlty this physical connection can't be properly modeled and its not visible for the users that the cable is indeed a backplane connection.

This feature could also be handy when using the new modules feature in combination with modular switches where some internal interfaces are realized with direct backplane connectivity.

### Database changes

none, only new interface and cable type definitions are needed.

### External dependencies

none

**Comment by phurrelmann** [comment]
To not clutter the interface type section "Ethernet (fixed)" a new section "Backplane" or "Ethernet (Backplane)" could be added, too. But I'll leave this open for discussion.

**Comment by jeremystretch** [comment]
> Backplane Ethernet, also known by the name of the task force that developed it, 802.3ap, is used in [backplane](https://en.wikipedia.org/wiki/Backplane) applications such as [blade servers](https://en.wikipedia.org/wiki/Blade_servers) and [modular](https://en.wikipedia.org/wiki/Modular#Modularity_in_technology_and_management) network equipment with upgradable [line cards](https://en.wikipedia.org/wiki/Line_card).

Would it make sense to refer to these as 802.3ap types?

**Comment by jeremystretch** [comment]
Sorry, yes, I was referring to the group. We could maybe call it "Backplane (802.3p)" to better differentiate from the general Ethernet types.

**Comment by phurrelmann** [comment]
> Sorry, yes, I was referring to the group. We could maybe call it "Backplane (802.3ap)" to better differentiate from the general Ethernet types.

Sounds good to me 👍
I'll try to implement this ticket, if accepted.

**Comment by phurrelmann** [comment]
just a quick update. I'm still interested in implementing this and have planned this for next week

**Comment by jeremystretch** [comment]
@phurrelmann is this ready for a PR?

**Comment by phurrelmann** [comment]
Need to do some checks and will submit the PR tomorrow. Thx for your patience
