### ISSUE TITLE
Custom Field Not Redering in UI in L2VPN Terminations

### ISSUE THREAD

**Issue by kvedder-amplex** [netbox-community/netbox#10362]
### NetBox version

v3.3.1

### Python version

3.8

### Steps to Reproduce

1. Create a custom field, assign it to the L2VPNTermination Model. I tried "text" and "object".

### Expected Behavior

I expected to be able to edit the custom field in the UI.

### Observed Behavior

The custom field doesn't appear in the UI. It does appear in the API. I did not see this fixed in 3.3.2, as best I can tell.

![image](https://user-images.githubusercontent.com/44881775/190187551-59fafb97-4877-4351-a318-e18be4a4f21b.png)

``` {
    "count": 1,
    "next": null,
    "previous": null,
    "results": [
        {
            "id": 1,
            "url": "https://***REDACTED***/api/ipam/l2vpn-terminations/1/",
            "display": "ce51 <> car3-wireless",
            "l2vpn": {
                "id": 1,
                "url": "https://***REDACTED***/api/ipam/l2vpns/1/",
                "display": "car3-wireless",
                "identifier": null,
                "name": "car3-wireless",
                "slug": "car3-wireless",
                "type": "vpls"
            },
            "assigned_object_type": "dcim.interface",
            "assigned_object_id": 119,
            "assigned_object": {
                "id": 119,
                "url": "https://***REDACTED***/api/dcim/interfaces/119/",
                "display": "ce51",
                "device": {
                    "id": 5,
                    "url": "https://***REDACTED***/api/dcim/devices/5/",
                    "display": "hq-core-02",
                    "name": "hq-core-02"
                },
                "name": "ce51",
                "cable": null,
                "_occupied": false
            },
            "tags": [],
            "custom_fields": {
                "service_template": null
            },
            "created": "2022-09-14T14:39:07.664945Z",
            "last_updated": "2022-09-14T14:39:07.664966Z"
        }
    ]
} ```

**Comment by kvedder-amplex** [comment]
I think https://github.com/netbox-community/netbox/issues/5509 may have caught this, and may prevent this in the future?

**Comment by DanSheps** [comment]
I don't think it will catch it completely.

This is likely because we use a custom form on the termination edit to handle the various different types of terminations.

**Comment by kvedder-amplex** [comment]
Yeah I am putting in a PR right now. I think `netbox/templates/ipam/l2vpntermination_edit.html` is missing the code to render the custom fields.
