### ISSUE TITLE
List of tagged objects does not comply constraints for permissions

### ISSUE THREAD

**Issue by n00n3L** [netbox-community/netbox#10378]
### NetBox version

v3.3.2

### Python version

3.10

### Steps to Reproduce

1. Click en Other > Tags
2. Click on any tag

### Expected Behavior

The user should only view the objects that match the his constraints for permission.

### Observed Behavior

The user can list all objects for any chosen tag, even if not match the imposed his constraints for permission.

**Comment by jeremystretch** [comment]
This is expected behavior. View permissions do not hide that an object exists; they prevent a user from accessing the details of that object.

**Comment by n00n3L** [comment]
Apology for reopening this. 

I'm trying to use tags for accomplish multi tenancy. The only thing, that I'm aware of, that prevent that a given user can see any other object except his is the possibility to list tagged objects. I maintained the possibility to view the created tags so they can use it during the creation of a new object.       

Maybe this is not the right way to do this.

**Comment by n00n3L** [comment]
I will move this to Discussions.
