### ISSUE TITLE
Assign non-racked devices to rack position by drag & drop or by clicking on slot.

### ISSUE THREAD

**Issue by severgun** [netbox-community/netbox#10372]
### NetBox version

v3.3.2

### Feature type

New functionality

### Proposed functionality

Add abbility to place devices in rack slots from Rack info page.
Currently you can only create new device by clicking on slot.

### Use case

I did inport csv with devices but did not define rack position. Would be nice to drag and drop them in place.

**Comment by jeremystretch** [comment]
This idea has been raised in multiple past issues (see #6726, #7957) however no one has proposed an actual implementation strategy. I'm going to close this as a duplicate, however if you would like to edit your post to include a detailed proposed solution - citing any necessary database changes, new dependencies, etc. - I'd be happy to re-open it.

**Comment by severgun** [comment]
Obviously I'm not netbox system architect, so I will not plan solution. This is just feature request from user.

When you have interactive visual representation, common expectation is to be able to interact with items. Move around, get info about items inplace but not going to new pages back and forth, etc.

> assigning device positions curing bulk import.

I know that I can set position in multiple ways. But this is not drag and drop. This is different user experience.
