### ISSUE TITLE
Status field for modules

### ISSUE THREAD

**Issue by severgun** [netbox-community/netbox#10371]
### NetBox version

v3.3.2

### Feature type

Data model extension

### Proposed functionality

Would be nice to have state field for modules.
Active, Failed, somethink like that.

### Use case

For example there is device with failed Fan. Replacement part is scheduled for delivery, but currently failed module stays in slot and would be nice to have ability to keep track of that fact.

### Database changes

Add new field 'status' to modules.

**Comment by severgun** [comment]
Nevermind. Custom fields are here for that.

**Comment by jeremystretch** [comment]
> Nevermind. Custom fields are here for that.

Custom fields can work certainly, however I think it's worth exploring interest in a native `status` field for modules. I think it could be generally useful.
