### ISSUE TITLE
Allow assigning multiple devices roles

### ISSUE THREAD

**Issue by dreng** [netbox-community/netbox#10384]
### NetBox version

v3.3.2

### Feature type

Change to existing functionality

### Proposed functionality

In the current situation you are able to assign exactly one device role to a device. I'd propose the possibility to assign multiple device roles to a device.

### Use case

In the real world it is a common scenario to have more than one role for a device. E.g. a switch could be a switch (obviously) and a DHCP-Relay or a Firewall could be an Intrusion Protection System and a VPN connector. A virtual machine could be a domain controller, a DNS-Server and a DHCP-Server (which is a very common scenario for SMEs).

### Database changes

class Device: device_role needs to be a ManyToManyField.
Change would break API queries on device role.

### External dependencies

none

**Comment by jsenecal** [comment]
Why not using tags for this ?

**Comment by jeremystretch** [comment]
> In the real world it is a common scenario to have more than one role for a device.

I disagree. In my experience, every infrastructure device is easily classified by its primary function, and the device role model works very well for this. From your examples above, it seems you're more interested in tracking a matrix of specific features or configurations, which is a supplementary information to a node's role.

**Comment by dreng** [comment]
@jeremystretch Thank you for your comment. I agree that every device can be classified by its primary function. The Idea is to have every role (primary or not) documented and be able to search/filter for it. What would you suggest how the situation should be mapped in NetBox? @jsenecal suggested to use tags. What I don't like about that proposal is that you can use tags for virtually anything. But it is not the purpose of a database to use one field for everything you can imagine.

**Comment by jeremystretch** [comment]
You can use tags, custom fields, or a custom plugin to achieve what you want to do. There are pros and cons to each approach. However, the function of the device role is well established, and changing it would be both unnecessary and disruptive for many, many users. For this reason I'm going to decline this proposal. Thanks for your consideration.

**Comment by DanSheps** [comment]
Personally, I would make a custom plugin that adds "features" to a device/device-type.
