### ISSUE TITLE
Access to Config Context from Custom Link

### ISSUE THREAD

**Issue by tomasherout** [netbox-community/netbox#10402]
### NetBox version

v.3.3.4

### Feature type

New functionality

### Proposed functionality

_Custom Link_ has access to _Custom Fields_ via `{{ object.cf.foo }}` but seems it can't access to  _Config Context_ of particular device.

### Use case

Provide link to other systems where related data are stored in Config Context.

**Comment by kkthxbye-code** [comment]
It works for me when testing:

`{{object.get_config_context().name_of_key}}`

**Comment by tomasherout** [comment]
Cool, works. Many thanks 👍 

It would be good to mention it at https://docs.netbox.dev/en/stable/customization/custom-links/

**Comment by kkthxbye-code** [comment]
I think it's a hard balance, as we already mention the following:

>Checking the REST API representation of an object is generally a convenient way to determine what attributes are available. _**You can also reference the NetBox source code directly for a comprehensive list.**_

Custom scripts, reports, custom URL's etc. are really all power user features and it's impossible to document everything that is possible with the internal netbox objects. If you feel like config contexts deserves a concrete mention in the docs you are welcome to create a documentation issue instead.
