### ISSUE TITLE
Allow Virtual Machines as Devices in Cluster

### ISSUE THREAD

**Issue by cstueckrath** [netbox-community/netbox#10401]
### NetBox version

v3.3.4

### Feature type

Change to existing functionality

### Proposed functionality

Curretly clusters can only be formed using physical devices and can only host virtual machines.
It should be possible to create application clusters from virtual machines, too.

* "Clusters" might move from "Virtualization" to "IPAM"
* When editing a Cluster: Change "Add Virtual Machine" to "Add Cluster Role" (which can be a Virtual Machine, too)
* Change "Assign Device" to "Add Node", which can be Virtual machines, too

A workaround, where FHRP-Groups are used for this is not ideal because of the problems mentioned here: https://github.com/netbox-community/netbox/discussions/9515#discussioncomment-2944159

### Use case

With this change we could document our SQL Clusters or file clusters as well as other application clusters, too.
Often those clusters are guest clusters, formed from virtual machines as nodes.

**Comment by hagbarddenstore** [comment]
Clusters are used to document hypervisors, not other kinds of clusters.

For other kinds of clusters, find a plugin or develop a plugin which better documents the specific kind of cluster.

**Comment by cstueckrath** [comment]
Hence the request for a new feature.
I am aware that clusters are currently only used to document hypervisors. It would still be helpful to have a function to assign VIPs to multiple objects (including VMs) without having to use FHRP Groups to do so.

**Comment by jeremystretch** [comment]
As @hagbarddenstore points out, the purpose of clusters in NetBox is already very well defined and serves a specific purpose. We won't be changing this. However, you might consider developing a [custom plugin](https://docs.netbox.dev/en/stable/plugins/development/) that implemented the functionality you desire.
