### ISSUE TITLE
Create comments section for vlan

### ISSUE THREAD

**Issue by jcralbino** [netbox-community/netbox#10413]
### NetBox version

V3.3.4

### Feature type

Data model extension

### Proposed functionality

Currently the vlan model does not include a comments section as used in other models (freeform Markdown text field).

I would like to add a new field , like the one existing in devices to allow comments to be introduced to the vlan 

### Use case

The additional comments field will allow a better documentation of the relevant objects 

### Database changes

Add the comments field as used in devices 

### External dependencies

None

**Comment by jeremystretch** [comment]
Folding this into #10545
