### ISSUE TITLE
new custom field type: data rate

### ISSUE THREAD

**Issue by swoga** [netbox-community/netbox#10415]
### NetBox version

v.3.3.4

### Feature type

New functionality

### Proposed functionality

Add a new type of custom field for data rates that use the `SelectSpeedWidget` for input and `humanize_speed` for representation in table views.

### Use case

We would like to document the bandwidth for L2VPN entries, so we would create a custom field.
The widget would make it easier to enter values and the pretty formatting would greatly improve readability.

(I think adding such a field to the general L2VPN model doesn't make sense in the context of multipoint connections, hence an individual solution via a custom field.)

### Database changes

none

### External dependencies

none

**Comment by jsenecal** [comment]
Would a `Bandwidth` field make sense with the [L2VPNTermination Model](https://github.com/netbox-community/netbox/blob/develop/netbox/ipam/models/l2vpn.py#L83) ?

NetBox already has somewhat similar functionality on the models for [CircuitTerminations `port_speed` field](https://github.com/netbox-community/netbox/blob/develop/netbox/circuits/models/circuits.py#L183) which is optional... Perhaps this would work here as well...

**Comment by jeremystretch** [comment]
> Add a new type of custom field for data rates that use the SelectSpeedWidget for input and humanize_speed for representation in table views.

I'm sorry but that's a bit too niche for custom fields, and would be very difficult for us to maintain long-term. You'll have to stick with a normal integer field, or as @jsenecal suggests perhaps propose adding a built-in field for this purpose.
