### ISSUE TITLE
Journal entries: dcim.interface - can create but no Journal tab for interfaces and error generated in Journal viewer

### ISSUE THREAD

**Issue by palmersample** [netbox-community/netbox#10423]
### NetBox version

v3.2.7

### Python version

3.9

### Steps to Reproduce

1. Create a journal entry using the REST API. Target: ```/api/extras/journal-entries```  Payload:
```python
{
    "assigned_object_type": "dcim.interface",
    "assigned_object_id": 163,
    "kind": "info",
    "comments": "Hey.  I assigned an IP address to this interface as a test."
}
```
2. HTTP status ```201 Created``` received.
3. Navigate to the interface page, no Journal tab is listed.
4. Navigate to **Other** -> **Journal Entries** and journal entry is listed
<img width="1019" alt="image" src="https://user-images.githubusercontent.com/40956652/191370386-1faf74d0-164b-412b-9ae9-55d0ee0236ae.png">
5. Click on journal entry, an error is generated:
<img width="897" alt="image" src="https://user-images.githubusercontent.com/40956652/191370452-e143bf94-4867-486a-8663-97620ae2030d.png">

My apologies is this has been corrected in 3.3, unable to update at this time so reporting as a 3.2.7 problem.

### Expected Behavior

Ability to view journal entries for an interface, either on the interface page or via the journal viewer.

### Observed Behavior

Successfully submitted a journal entry via REST API but unable to view in either the interface or journal viewer context.

**Comment by jsenecal** [comment]
Hi @palmersample, this was likely an oversight and should not be made available from the API at all.

What is the intended use of the journaling functionality on interfaces ?

**Comment by DanSheps** [comment]
Journalling was added under #151.

I don't see a reason not to extend journalling to components.

**Comment by jeremystretch** [comment]
Currently, we don't officially support journaling for interfaces, or for any other models where no "Journal" tab appears within its UI view. However, there's no firm validation in place to prevent the creation of journal entries for unsupported types. (This is a byproduct of these models inheriting from the `NetBoxFeatureSet` class.)

I see two options:

1. Implement validation to prevent the creation of journal entries for unsupported models.
2. Officially extend journaling support to these other models.

If we pick option two, it would probably make sense to implement #9072 first, as that should allow us to more easily register journal views for each model. (This is currently done via a manual URL path definition for each model in its respective `urls.py` file.)

**Comment by jeremystretch** [comment]
I'm going to proceed with option 1 above to resolve this bug. Happy to revisit expanding support for journaling to other models once #9072 has been addressed if there's demand for it.
