### ISSUE TITLE
Add a filter for Device-Type in the Device Components searches

### ISSUE THREAD

**Issue by martinum4** [netbox-community/netbox#10428]
### NetBox version

v3.3.2

### Feature type

Change to existing functionality

### Proposed functionality

A filter for device types would greatly improve the search and bulk edit of data.

### Use case

After Changes in the NetBox Data Model (in this case the addition of PoE) it can be necessary to bulk-edit existing objects.

Device-Types usually share the same nomenclature across multiple types and vendors (e.g. Slot/Module/Port for switches, Power Ports…).
Selecting the right objects to mass-edit can be greatly amplified by being able to select all ports of a specific device type, e.g. to mark them as PSE or PD.

### Database changes

All required datasets are already contained within NetBox.

### External dependencies

Probably none.

**Comment by kkthxbye-code** [comment]
If I understand your request properly, it is not possible. The device components (like the Interface model) are not the same as the templates (InterfaceTemplate in this case). So while InterfaceTemplates have a direct relationship to a DeviceType or ModuleType, Interfaces do not.

You could select the **current** DeviceType from the parent interface, but I really don't see how it makes sense from a datamodel perspective, as you can change the devicetype of a device after creation. What DeviceType does the device components "belong" to then?

I get the need from a usability standpoint, I just don't see a good way to implement it without it being confusing.

Please correct me if I misunderstood what you are suggesting.

**Comment by martinum4** [comment]
Yes, it would be an indirect relationship.

I think for the most usecases described here the current DeviceType is just fine.

Personally i don't really find it confusing, if you know the limitations (DeviceType can be changed after Device creation, only instanced at creation, etc.).

I think you got me right and i see your concerns.

**Comment by jeremystretch** [comment]
Closing this out as the proposal does not seem to be feasible.
