### ISSUE TITLE
Cannot change device for inventory item

### ISSUE THREAD

**Issue by dsl81** [netbox-community/netbox#10437]
### NetBox version

v3.3.4

### Python version

3.9

### Steps to Reproduce

Click on existing inventory item or create one.
Click edit.

### Expected Behavior

Be able to select device from drop down menu.

### Observed Behavior

Device drop down menu is grey and disabled.

![inventory_item](https://user-images.githubusercontent.com/3961842/191754684-2a2aa770-d0ed-459d-9d2c-c17f014cba93.png)

**Comment by jsenecal** [comment]
This is not a bug, but the intended functionality.

Please open a feature request with a proper use case if you would like to alter this behavior.

See: 
https://github.com/netbox-community/netbox/blob/master/netbox/dcim/forms/models.py#L1230

Thanks!
