### ISSUE TITLE
Adding new VM Cluster does not save when site is left blank

### ISSUE THREAD

**Issue by daniejstriata** [netbox-community/netbox#10436]
### NetBox version

v3.3.4

### Python version

3.8

### Steps to Reproduce

1. Create a new Region.
2. Create a Site Group
3. Create a new Virtualization Cluster
4. Edit Cluster 
5. Assign Region and Site group to Cluster
6. Click Save
![image](https://user-images.githubusercontent.com/13314239/191738120-51d10568-6c44-4a07-ad3b-899ec60a5bc9.png)
7. Go back to edit the Cluster.
8. The Region and site is not saved as seen in item 6.
![image](https://user-images.githubusercontent.com/13314239/191738450-5ec7804a-2e7a-4464-92fb-2dcf6e2d95b9.png)

When a new site was created and assigned to the Region and Site Group and selected when updating the Cluster, then all three values will be saved.
![image](https://user-images.githubusercontent.com/13314239/191739200-114ad2a4-cc9e-4d2d-98ef-4e4b2cb4ee2b.png)

### Expected Behavior

If all three values are required to save a cluster's Site then there should not be a successful green confirmation that the items were saved.

### Observed Behavior

The Update is not saved but when clicked Netbox stated that the change was saved. Going back to the Cluster does not show the added Site or Site Group.

**Comment by arthanson** [comment]
This is sort of interesting as the Region and Site group are just filters for the Site, not actually saved - only the Site is saved.  If the site is saved then the Region and Site group come from the saved site when edited.

**Comment by daniejstriata** [comment]
If it is an EC2 instance should I add them in Virtualization or add them ad you'd add physical devices?

**Comment by kkthxbye-code** [comment]
I really don't think there is anything to do here specifically. It should be covered by https://github.com/netbox-community/netbox/issues/10054. It's also the intended functionality currently, so not really a bug imo.

**Comment by jeremystretch** [comment]
> I really don't think there is anything to do here specifically. It should be covered by #10054. It's also the intended functionality currently, so not really a bug imo.

Agreed. The site group and region fields exist solely to aid in the selection of a site for the cluster; there is no direct relationship from a cluster to these objects. Admittedly this can be a bit confusing, but that's why #10054 has been raised.

> I only wanted to assign a region to the VM cluster as it did not have a site.

It's not possible to assign a cluster to a region, however the assignment of a site is optional. For e.g. an AWS cluster you can simply not assign a site.
