### ISSUE TITLE
Image being reference to several objects

### ISSUE THREAD

**Issue by jcralbino** [netbox-community/netbox#10438]
### NetBox version

v3.3.4

### Feature type

Change to existing functionality

### Proposed functionality

Currently we are able to upload an image to several data models, namely to Site, Locations for example.

What i propose is that we enable the option to be able to reference the same image to several objects.

### Use case

When documenting for example the building layout we can do the following:

Site : BuildingA-: Represents Building-A -> Image uploaded can represent the building.
Location: Floor-0-BLDA  -> Parent is BuildingA : Used Represents Building-A 
       -> Image ImgFloor0: uploaded represents the floorplan in that building.
Location: Room00SG10  -> Parent is Floor-0-BLDA: Usedto represent a room in level 0 in Building-A 
       -> Image Room00SG10: uploaded represents details in the room of that building.

If we can reference previous uploaded images, here we could add additional images in Location "Room00SG10 " refering for example the ImgFloor0 and Room00SG10, within the Location Room00SG10  .

This way we will have all the details needed within one page, not requiring to browse to different places.

### Database changes

Create a table for Uploaded images that references the uploaded and with the locations where they should be viewed. 

### External dependencies

none

**Comment by jeremystretch** [comment]
It sounds like perhaps you have more complex requirements than what NetBox's image attachment feature is intended to serve. You're likely better off using a general purpose external file store and linking NetBox objects to it.

**Comment by jcralbino** [comment]
I believe that this is not the only use case where a user can upload the same image to more objects 

I understand that netbox is not meant to store documents, but the way it handles images can be improved. This seems a feature that is quite useful for several reasons
