### ISSUE TITLE
Missing widget on field `Airflow` in DeviceTypeForm

### ISSUE THREAD

**Issue by miaow2** [netbox-community/netbox#10439]
### NetBox version

v3.3.4

### Feature type

Change to existing functionality

### Proposed functionality

Field `Airflow` in DeviceTypeForm is missing widget `StaticSelect`.
![image](https://user-images.githubusercontent.com/28296817/191788926-0287534c-e3a8-49d3-94a1-7a88307c98d3.png)

### Use case

You can assign this issue to me and I will create a pull request

**Comment by jsenecal** [comment]
Great catch @miaow2, would you like to submit a PR to address this ?

**Comment by miaow2** [comment]
@jsenecal yeah, I would like to create PR

**Comment by kkthxbye-code** [comment]
All yours @miaow2
