### ISSUE TITLE
Possibility to change device when editing inventory item.

### ISSUE THREAD

**Issue by dsl81** [netbox-community/netbox#10447]
### NetBox version

v3.3.4

### Feature type

Change to existing functionality

### Proposed functionality

Return ability to change device when editing inventory item.

### Use case

We are using inventory items to account transceivers. When transceiver is moved to another device it should be reflected in netbox. [Here](https://github.com/netbox-community/netbox/issues/10437) it is said that this "feature" was removed for some reason, but if we have to recreate items we will lose history and the hole process of moving items becomes very burdensome.

![inventory_item](https://user-images.githubusercontent.com/3961842/191916313-f35d3259-1d09-4bd9-a475-f3b33a3430f4.png)

**Comment by jsenecal** [comment]
Only Inventory items would require this ability to be reassigned, right ?

**Comment by dsl81** [comment]
Sorry, I did not quite understand what you mean by "only". Things like device modules should also be able to be reassigned. Or I got you wrong?

**Comment by dsl81** [comment]
Are there any news on this?

**Comment by cpmills1975** [comment]
Argh. Did this functionality go away?  Perhaps as part of some larger change to standardise a bunch of forms?

I currently use inventory items to track line cards etc and until I'm able to migrate to using Modules, will continue to do so. Line cards move between devices from time to time and not having the ability to make this change without deleting and re-creating the inventory item is going to pain me greatly.

**Comment by dsl81** [comment]
> Argh. Did this functionality go away? Perhaps as part of some larger change to standardise a bunch of forms?
> 
> I currently use inventory items to track line cards etc and until I'm able to migrate to using Modules, will continue to do so. Line cards move between devices from time to time and not having the ability to make this change without deleting and re-creating the inventory item is going to pain me greatly.

Yes it was removed. Besides the pain we will lose all history for the item. So we will not be to track them.

**Comment by robduffy2010** [comment]
We also made extensive use of this feature until it was removed.  It would help a lot to have it added back.

**Comment by Xanawatt** [comment]
Is there a reason that this was removed? With an inventory tracking program, the ability to track device history across locations is heavily desired.

**Comment by kkthxbye-code** [comment]
It's still possible to change the device id via. the API. At the very least we should align the UI and API.

See also: #9898

**Comment by cichutkiii** [comment]
I updated yesterday from version 3.3.2 to 3.3.8 and I see this issue too. 
Interesting thing is if you want to change it by bulk edit button, then it works.

**Comment by phurrelmann** [comment]
This is needed pretty much. We're assigning several hundreds of transceivers to interfaces. They all have custom fields for e.g. the programmed compatibility. Having to recreate all that data when a transceiver is moved to a different device is just a PITA. Ideally we even would like to create an inventory item without a device and assign it only later, when the transceiver is plugged. But of course this out of this ticket's scope.
