### ISSUE TITLE
Can't find journalentry permissions

### ISSUE THREAD

**Issue by aswen** [netbox-community/netbox#10459]
### NetBox version

v3.3.4

### Python version

3.8

### Steps to Reproduce

1. Create a new user.
2. Try to grant the user the permission to add a journal entry.

### Expected Behavior

Expected to find the following permissions:
* `extras.add_journalentry`
* `extras.change_journalentry`
* `extras.delete_journalentry`
* `extras.view_journalentry`

### Observed Behavior

No permissions related to journal entries found.

(Ref: #151 & #5999)
The permission is referenced [here](https://github.com/netbox-community/netbox/pull/5999/files#diff-df7f21221afb12c7bacdc6242136ca7ea0d2b9178eaf9117a5821d265878775aR7)

**Comment by kkthxbye-code** [comment]
Thank you for your report. The issue you are having is not a bug however. Originally netbox came pre-populated with permissions for all objects, but that has not been the case for a good while.

To create permissions for journal entry go to http://netbox.local/admin/users/objectpermission/add/ choose `Extras > journal entry`. You can then create the the four permissions you are missing, or just the ones you need.

**Comment by aswen** [comment]
Thanks @kkthxbye-code I had no idea permissions should be created by admins. Why is that?

**Comment by kkthxbye-code** [comment]
@aswen - It was always possible to create them, they were just pre-generated on install way back when. Creating them yourself provides better flexibility, as an example I could have a "Read-only IPAM" permission that includes all IPAM objects with only the read flag set. IMO this is easier than adding several distinct read permissions to each user/group.
