### ISSUE TITLE
Multiselect field producing error when attempting to populate via REST API

### ISSUE THREAD

**Issue by adfrost81** [netbox-community/netbox#10453]
### NetBox version

v3.2.3

### Python version

3.8

### Steps to Reproduce

1. Created multiselect custom field "str_small_printers" with the following options: HP LaserJet M402dn,HP LaserJet M404dn

2. Sent the following JSON script via Postman:

`[
    {
        "id": 809,
        "custom_fields": {
            "str_small_printers": "HP LaserJet M402dn"
        }
    }
]`

![2022-09-23 17_10_50-Postman](https://user-images.githubusercontent.com/91818709/192063648-11afd8cc-7b71-4d72-8545-86714b3c60f6.png)

### Expected Behavior

The custom field should have been populated with the value provided.

Formatting and spelling were verified to match multiselect choices. Verified JSON syntax is correct.

### Observed Behavior

Field is not populated. Received the following error response:

`{
    "__all__": [
        "Invalid value for custom field 'str_small_printers': Invalid choice(s) (H, P,  , L, a, s, e, r, J, e, t,  , M, 4, 0, 2, d, n). Available choices are: HP LaserJet M402dn, HP LaserJet M404dn"
    ]
}`

**Comment by jeremystretch** [comment]
The value of a multi-select field must be sent as a list, not a string.
