### ISSUE TITLE
Missing connection details below cable on several objects views since v3.3

### ISSUE THREAD

**Issue by phurrelmann** [netbox-community/netbox#10460]
### NetBox version

v3.3.4

### Python version

3.10

### Steps to Reproduce

As Netbox 3.3 introduced multi-connection cables some parts weren't updated to the new code and the following templates are not showing any connection detail below "Cable". 

- consoleport
- consoleserverport
- interface
- powerfeed
- poweroutlet
- powerport

The powerfeed view additionally lacks to power usage and the capacity graph.

I already have a PR ready and are happy to submit if this bug is accepted.

### Expected Behavior

Connection details are again visible below Cable on the views/templates for:

- consoleport
- consoleserverport
- interface
- powerfeed
- poweroutlet
- powerport

Power usage and the capacity graph are visible on the powerfeed again.

Examples for fixed views:

![powerfeed_fixed](https://user-images.githubusercontent.com/10113716/192275761-b9faebba-185f-4ab5-bb9a-270731bf240b.png)

![powerport_fixed](https://user-images.githubusercontent.com/10113716/192275806-722f3b19-d1aa-47db-a0a4-ef3dd0fb7b66.png)

### Observed Behavior

The mentioned templates/view only show the cable itself, but no connection details and status.
Powerfeed doesn't show the connected device and only show N/A as power usage.

Examples of broken views:

![powerfeed_broken](https://user-images.githubusercontent.com/10113716/192275931-59fd73a8-25a5-49e2-97ac-459ce23a9fd0.png)

![powerport_broken](https://user-images.githubusercontent.com/10113716/192275961-47c016e7-cec7-486c-8112-3d57c58cff27.png)

**Comment by jeremystretch** [comment]
> I already have a PR ready and are happy to submit if this bug is accepted.
Thanks @phurrelmann!

**Comment by phurrelmann** [comment]
I just submitted a PR for this. Please consider it as a "hack". It works for me, but may not be the correct or intended fix as I'm lacking in details knowledge on Django.

**Comment by jeremystretch** [comment]
@phurrelmann thanks, I missed that bit! Fixed in 53f5f4603. Thanks for the heads up!
