### ISSUE TITLE
2FA via TOTP or Yubikey

### ISSUE THREAD

**Issue by jf-sfy** [netbox-community/netbox#10464]
### NetBox version

v3.3.4

### Feature type

New functionality

### Proposed functionality

Would be useful to add two factor authentication to netbox.

Users would register their 2fa either as a TOTP app such as the google authenticator, or via a physical device such as a yubikey. 

Once registered, when the user tries to login, once they have done username and password, they will be asked for their 2nd factor code, either as a 6 digit TOTP code, or by touching their yubikey, granting them access. 

### Use case

While many people use LDAP authentication, and the 2fa options provided by a single sign on. This creates a dependency on the LDAP server to be able to login. In the event that the AD/LDAP server is down, being unable to login to netbox, to work out where in the DC the machine is located would be rather embarrassing. The option for enhancing security through TOTP or yubikey authentication would be a great improvement. 

### Database changes

Not sure. I'm not a developer, and I don't know the code base so I can't say what would need changing in the internals. 

### External dependencies

 Ideally none, totp and yubikey should be possible in a standalone way such that as long as the machine netbox is running is up, it works, without needing to federate authentication against another device.

**Comment by jeremystretch** [comment]
Thank you for your interest in extending NetBox. Unfortunately, the information you have provided does not constitute an actionable feature request. Per our [contributing guide](https://github.com/netbox-community/netbox/blob/develop/CONTRIBUTING.md), a feature request must include a thorough description of the proposed functionality, including any database changes, new views or API endpoints, and so on. It must also include a detailed use case justifying its implementation. If you would like to elaborate on your proposal, please modify your post above. If sufficient detail is not added, this issue will be closed.

**Comment by jeremystretch** [comment]
For anyone interested, @k1nky created a [plugin](https://github.com/k1nky/netbox-otp-plugin) that seems to fulfill this function.
