### ISSUE TITLE
NAPALM Hostname split at .

### ISSUE THREAD

**Issue by b66renr** [netbox-community/netbox#10468]
### NetBox version

v3.3.4

### Feature type

Change to existing functionality

### Proposed functionality

Hello! I'm setting up Netbox for an existing ISP network, and have run into the issue mentioned in #1810, where hostnames are split at the first .
I see an open issue for this with interface names, but only the previous one for device hostname. Apologies if I've missed any.

I understand the issue, where devices are adding their domain name to the end (and our Juniper devices do it), but this adds an issue depending on how hostnames are built (not an easy change). Random examples, rtr1.london.uk, and rtr1.nyc.us both become rtr1.

There were a few comments after #1810 was rejected with some suggestions. Would it be possible to look into either of these options, being:
- Platforms can have options to not strip domain (less friendly as it requires putting the domain into the device name)
- Having a configuration option somewhere to specify the domain name section of the hostname, that will then be removed.

Thanks

### Use case

Hostnames with . in would work correctly in LLDP neighbors. Currently, all devices show in red in the LLDP neighbors page indicating a mismatch.

### Database changes

Likely new field(s) in Platforms, if done this way, or maybe new config option "NAPALM_DOMAIN_NAME".

**Comment by jeremystretch** [comment]
Marking as blocked pending #10520

**Comment by jeremystretch** [comment]
Closing this out as NAPALM integration is being moved to a plugin in NetBox v3.5.
