### ISSUE TITLE
Bug in related path table on trace view

### ISSUE THREAD

**Issue by dssdss** [netbox-community/netbox#10485]
### NetBox version

v3.3.5

### Python version

3.9.2

### Steps to Reproduce

**1. Reproduce network scheme like below**
![download](https://user-images.githubusercontent.com/14805815/193833862-d240e184-e4c8-43e6-91ee-8fadae502bf3.svg)

Add 3 device type
1) Switch 24 interfaces, name ge1 - ge24 ; type 100BASE-TX (10/100ME)
2) Media Convertor: 1 Rear Ports, name fc[1] TX/RX, type SC -- 1 Front Ports name ge1, type 8P8C
3) Patch panel 16 port Fiber SC: 1 Rear Ports, Positions 16, name R2-3, type SC -- 16 Front Ports, name F1-2 - F16-2, type SC 

Add 6 device:
1) 24 Interfaces Switch, name angw.comita.lan 
2) 24 Interfaces Switch, name topgw.comita.lan
3) Media Convertor, name mc_an_201r_1
4) Media Convertor, name mc_bur_8r_3
5) Patch panel 16 port Fiber SC, name oc_an_201r_3
6) Patch panel 16 port Fiber SC, name oc_an_1r_1

Make connections:
1) oc_an_201r_3, Rear Ports R2-3 --- oc_an_1r_1, Rear Ports R2-3 ; type Singlemode Fiber (OS2)
2) angw.comita.lan, interface ge23 --- mc_an_201r_1, Front Ports ge1 ; type CAT5e
3) mc_an_201r_1, Rear Ports fc[1] TX/RX Split Patching --- oc_an_201r_3, Front Ports F2-2, F3-2 ; type Singlemode Fiber
4) mc_bur_8r_3, Rear Ports fc[1] TX/RX Split Patching --- oc_an_1r_1, Front Ports F2-2, F3-2 ; type Singlemode Fiber
5) topgw.comita.lan, interface ge17 ---  mc_bur_8r_3, Front Ports ge1 ; type CAT5e

**2. Press trace button on network interface ge23 on Switch angw.comita.lan - we got Related Paths table empty**

### Expected Behavior

But if we press Trace button not on interface but on any port (front, rear) - Related Paths table contain information.

For example I press Trace on device mc_an_201r_1 Front Port ge1 
![image](https://user-images.githubusercontent.com/14805815/192551517-38b70186-a28e-4132-8837-98af2d0a549b.png)

### Observed Behavior

We see, that Related Paths table is empty if we press Trace button on the switch angw.comita.lan interface ge23

![image](https://user-images.githubusercontent.com/14805815/192549724-63c1cad1-e1f3-40aa-9dc5-f4e15f9a04f9.png)

**Comment by dssdss** [comment]
And it would be just wonderful if you add DEVICE NAME to the Related Paths table

**Comment by jeremystretch** [comment]
Thank you for opening a bug report. Unfortunately, the information you have provided is not sufficient for someone else to attempt to reproduce the reported behavior. Remember, each bug report must include detailed steps that someone else can follow on a clean, empty NetBox installation to reproduce the exact problem you're experiencing. These instructions should include the creation of any involved objects, any configuration changes, and complete accounting of the actions being taken. Also be sure that your report does not reference data on the public NetBox demo, as that is subject to change at any time by an outside party and cannot be relied upon for bug reports.

**Comment by dssdss** [comment]
We added more detailed steps to reproduce. Did we write clearly now?
It would be much better if you had a separate private instance, where we could reproduce bugs.

**Comment by dssdss** [comment]
> Unfortunately, the information you have provided is not sufficient...

We added more detailed steps to reproduce. Did we write clearly now?
It would be much better if you had a separate private instance, where we could reproduce bugs.

**Comment by dssdss** [comment]
Also, we can see the same problem between 2 Cisco devices on demo: https://demo.netbox.dev/dcim/interfaces/170/trace/

**Comment by jeremystretch** [comment]
> We added more detailed steps to reproduce. Did we write clearly now?

I'm sorry, but no, I still don't follow what you're expecting to happen here. As far as I can tell, everything is working as expected: The terminating interface will only have one path traversing it, so you should not expect to see any related paths listed.

**Comment by dssdss** [comment]
I apologize, I completely confused you, because of my first simple scheme.
Now, I replaced it with the original Cable trace – see my fist long image “1. Reproduce network scheme like below”.
You can see 2 switches on the top - angw.comita.lan interface ge23, and on the bottom - topgw.comita.lan interface ge17.
Only 2 devices have interfaces – switches. Other patch panels and mediaconverters (mc_an_201r_1, mc_bur_8r_3) have only ports (front and rear).

==================================================================
**So, case #1 – start tracing from port ge1 on mc_an_201r_1:**

1) Click on port ge1 mc_an_201r_1 (here and below images are cut, because they are very high):
![image](https://user-images.githubusercontent.com/14805815/193841651-75f9a9d4-deaf-4dd3-8e54-35a9367310b4.png)

2)  Click Trace button on front port ge1:
![image](https://user-images.githubusercontent.com/14805815/193842681-9090eb79-c391-4f70-bd30-877f466e4c78.png)

**We've got Cable full cable trace but with duplicated ports on Related Paths table.
I think that the table should have only 2 lines with interfaces ge23 and ge17 , or am I mistaken (image was cut, because its very high)?**
![image](https://user-images.githubusercontent.com/14805815/193843169-a9c3bbd6-e051-462c-9ab3-49a6723f3a6c.png)

==================================================================
**So, case #2 – start tracing from interface ge23 on switch angw.comita.lan:**

1) Click on interface ge23 switch angw.comita.lan:
![image](https://user-images.githubusercontent.com/14805815/193844298-b0c584c0-5c44-4dcb-bf24-e6283ef49adf.png)

2)  Click Trace button on interface  ge23 :
![image](https://user-images.githubusercontent.com/14805815/193844790-3d9fddae-4259-4ead-9ea7-0214da9f6255.png)

**And we get empty Related Patchs table!**
![image](https://user-images.githubusercontent.com/14805815/193846537-a0f73c72-6f06-432d-93d4-9fb8c9267868.png)

**Comment by dssdss** [comment]
> I'm sorry, but no, I still don't follow what you're expecting to happen here.
ermy, I changed the main tracer scheme and described all the actions and the result with the pictures in detail with the pictures

**Comment by dssdss** [comment]
> As far as I can tell, everything is working as expected: The terminating interface will only have one path traversing it, so you should not expect to see any related paths listed.
Update our Netbox to v3.3.5 - the same thing. See our detailed comics - that we posted above. Tracing on port also have bugs

**Comment by jeremystretch** [comment]
I'm afraid that after several attempts I'm still not able to follow what's happening here, and I believe this is part of the problem:

> case #1 you fixed, but case #2 - still no

There should never be more than one specific set of reproduction steps in a single bug report. Additionally, several potentially relevant cabling bugs have been fixed since this issue was last updated, so it's possible this is no longer needed.

Let's do this: I'm going to close out this issue as I expect attempting to clarify the above comments is only going to result in more confusion. I expect to release NetBox v3.4.3 within the next week or so, which will include all the more recent bug fixes. Once that release is available, please check whether you're able to reproduce your issue. If so, you're welcome to submit a new bug report with a new, clarified set of reproduction instructions pertinent to the specific behavior you'd like to address. Then we can work forward from there with a clean slate. Thanks!
