### ISSUE TITLE
Multiple Mark/Dismark connected (Treat as if a cable is connected)

### ISSUE THREAD

**Issue by ShellBoyAFK** [netbox-community/netbox#10493]
### NetBox version

v3.3.4

### Feature type

Change to existing functionality

### Proposed functionality

It would be nice if the disconnect button would also solve Marked as Connected Cables

### Use case

I often mark several front or rear ports as connected via the collective edit function. 

You can obviously select all of them as "Marked as Connect", but you can't unmark them.

**Comment by jeremystretch** [comment]
Thank you for your interest in extending NetBox. Unfortunately, the information you have provided does not constitute an actionable feature request. Per our [contributing guide](https://github.com/netbox-community/netbox/blob/develop/CONTRIBUTING.md), a feature request must include a thorough description of the proposed functionality, including any database changes, new views or API endpoints, and so on. It must also include a detailed use case justifying its implementation. If you would like to elaborate on your proposal, please modify your post above. If sufficient detail is not added, this issue will be closed.
