### ISSUE TITLE
Changes on IP_Ranges

### ISSUE THREAD

**Issue by pboatone** [netbox-community/netbox#10495]
### NetBox version

v3.3.4

### Feature type

Change to existing functionality

### Proposed functionality

1. View IP-Ranges unter IP-Adress, not only under Child Ranges
2. Under IP-Ranges a checkbox like Prefixes (Mark utilized)
3. Search -> IP Ranges not found with "ALL Objects"
4. If someone wants to add IP-Address in a IP-Range, a warning that it is an IP-Range 

### Use case

1. -> To see which IP-Address is blocked by an IP-Range
2. -> to mark DHCP Ranges as used for static addresses 
3. -> IP-Ranges can't found in Search
4. -> IP-Addresses should not be able to add to IP-Adress, if they are in an IP-Range, only they are marked as fixed

**Comment by jeremystretch** [comment]
If you'd like to propose multiple changes, you'll need to open a separate feature request for each one. When doing so, please ensure that you provide sufficient detail for each as required by the FR template.
