### ISSUE TITLE
Custom Fields depend on device roles

### ISSUE THREAD

**Issue by NEXYR18** [netbox-community/netbox#10492]
### NetBox version

3.2.3

### Feature type

Change to existing functionality

### Proposed functionality

Custom fields are able to create condition to display depend on attribute in object

### Use case

custom field "isLB_member" will displayed, if dcim/devices.devicerole = Server
custom field "is_Admin" will displayed, if custom field "username" is not null

### Database changes

not sure

### External dependencies

no

**Comment by kkthxbye-code** [comment]
Thank you for your interest in extending NetBox. Unfortunately, the information you have provided does not constitute an actionable feature request. Per our [contributing guide](https://github.com/netbox-community/netbox/blob/develop/CONTRIBUTING.md), a feature request must include a thorough description of the proposed functionality, including any database changes, new views or API endpoints, and so on. It must also include a detailed use case justifying its implementation. If you would like to elaborate on your proposal, please modify your post above. If sufficient detail is not added, this issue will be closed.

**Comment by jeremystretch** [comment]
Closing this as there's been no further reply.
