### ISSUE TITLE
Allow bulk creation on netbox_device_interface_template

### ISSUE THREAD

**Issue by jsalatiel** [netbox-community/netbox#10505]
### NetBox version

v3.2.5

### Feature type

Change to existing functionality

### Proposed functionality

One should be able to create interfaces in bulk using , for example, [ge,xe]-0/0/[0-9].
Right now If we use that in the name parameter, it will be created 1 single interface as literal instead of expanding for the 20 interfaces it should create when using the webui.

### Use case

Add interfaces in bulk.

**Comment by kkthxbye-code** [comment]
Thank you for your interest in extending NetBox. Unfortunately, the information you have provided does not constitute an actionable feature request. Per our [contributing guide](https://github.com/netbox-community/netbox/blob/develop/CONTRIBUTING.md), a feature request must include a thorough description of the proposed functionality, including any database changes, new views or API endpoints, and so on. It must also include a detailed use case justifying its implementation. If you would like to elaborate on your proposal, please modify your post above. If sufficient detail is not added, this issue will be closed.
