### ISSUE TITLE
Changes on IP-Ranges for better view in prefixes

### ISSUE THREAD

**Issue by pboatone** [netbox-community/netbox#10506]
### NetBox version

v3.3.4

### Feature type

Change to existing functionality

### Proposed functionality

It should be possible for IP ranges to be marked as "Mark utilized", so that the IP range is not only displayed under "Child Ranges" in a prefix, but also under IP address.
This offers the possibility to see directly in an IP prefix which IP addresses are not free.

It is currently the case that the IP addresses in the IP prefix are displayed as free despite the existing range.

In addition, when creating IP addresses, a warning would be useful if this collided with an IP range. It would be possible to define an IP as static for this range.

### Use case

It simplifies entering IP addresses and you can see directly whether an IP address collides with a range that serves as an example for DHCP.

### Database changes

-

### External dependencies

-

**Comment by jeremystretch** [comment]
Thank you for submitting this issue, however it appears that this topic has already been raised. Please see issue #7947 for further discussion.
