### ISSUE TITLE
Include asset_tag in module display name (and remove pk)

### ISSUE THREAD

**Issue by cpmills1975** [netbox-community/netbox#10512]
### NetBox version

v3.3.4

### Feature type

Change to existing functionality

### Proposed functionality

Having started dabbling with adding modules to devices, I'd like to suggest a different display naming scheme for modules.

At present Module.__str__ returns a combination of the module bay name, the module type and the module's pk. I'd suggest the pk means very little to the vast majority of NetBox users and should therefore be displayed only as a last option when all other means of identifying an instance have been exhausted.

I'd like to suggest the following:

- Drop the module bay name completely

  Both the device interfaces table and the modules table allow the module bay name to be displayed if this is important to the viewer

  However, there is one place where the module bay name makes sense - when editing an interface and choosing to add the interface to a module. If multiple instances of a similar module exist, then without a user settable module name, it makes sense to include the module bay name.

- Replace the pk with the asset_tag if present

  The pk means nothing to most people most of the time and because it is currently impossible to move a module, deleting and re-adding the module will mean a new pk anyway.

### Use case

With line cards for most large network device types costing more than the chassis that houses it most companies would likely want to add an asset tag to a line card and, if that is present, it makes sense to include it in the display name. Similarly, the presence of the pk in the display name likely means nothing to most people.

### Database changes

None

### External dependencies

None

**Comment by jeremystretch** [comment]
Where specifically are you proposing the format of the name be changed in the UI/API?
