### ISSUE TITLE
Allow templating of virtual chassis position in templated component names on modules

### ISSUE THREAD

**Issue by cpmills1975** [netbox-community/netbox#10514]
### NetBox version

v3.3.4

### Feature type

New functionality

### Proposed functionality

When templating component names, e.g. interfaces, it is possible to include {module} in the name and have this replaced with the module position on instantiation. I'd like to propose expanding the selection of available templates to include the virtual chassis position.

### Use case

Perhaps a bit of an edge case, but I was adding modules to a device that was already part of a virtual chassis. In the case of a JunOS or Cisco module, the interface names should would ideally be instantiated as _interface-type_/_virtual chassis FPC number or FEX number_/_module slot/PIC number_/_interface number_ e.g. xe-1/2/3, Eth101/2/3, etc.

I was able to template the module/PIC number using the {module} tag, but not the FPC/FEX number. Had I been able to template the interface names as xe-{vcposition}/{module}/[0-7] or Eth{vcposition}/{module}/[1-8], I'd not have had to subsequently rename the interfaces that were instantiated.

### Database changes

None

### External dependencies

None

**Comment by jeremystretch** [comment]
Makes sense. We should be able to follow the same pattern we use for module position. I don't have a strong opinion the token name but `vc_position` might offer slightly better readability.

**Comment by cpund** [comment]
I believe this is also related to #8648, which is something I'd also like to see implemented at one point. Still want to look at the code a bit before I commit to working on this myself. Would really like to see a better way to implement virtual chassis though. Having each member of a switch stack show as -0X in the device list gets a little wonky and less intuitive than just seeing the name of the stack itself.

**Comment by cpmills1975** [comment]
It seems this is a duplicate of #8648 and some interesting points were raised by @jeremystretch at the time regarding devices and their components being instantiated before being added to a VC rather than at the same time. @DanSheps suggestion to offer the ability to template but with a default makes a lot of sense - in the case of Juniper ports, AFAIK the FPC number will always be zero unless the device is part of a VC so templating `{vc_position:0}` or something like that would be helpful here.
