### ISSUE TITLE
Webhook conditions primary_ip is defined not working

### ISSUE THREAD

**Issue by stefanmarti** [netbox-community/netbox#10519]
### NetBox version

v3.2.5

### Python version

3.8

### Steps to Reproduce

Create webhook on event `update` and model `device` with the following condition:
```
{
   "and":[
      {
         "attr":"status.value",
         "value":"active"
      },
      {
         "attr":"primary_ip",
         "value":"",
         "negate":true
      }
   ]
}
```

### Expected Behavior

Webhook shoud not get fired if device doesn't have a primary_ip set

### Observed Behavior

Webhook get fired also for devices without a primary_ip set

**Comment by jeremystretch** [comment]
Thank you for opening a bug report. Unfortunately, the information you have provided is not sufficient for someone else to attempt to reproduce the reported behavior. Remember, each bug report must include detailed steps that someone else can follow on a clean, empty NetBox installation to reproduce the exact problem you're experiencing. These instructions should include the creation of any involved objects, any configuration changes, and complete accounting of the actions being taken. Also be sure that your report does not reference data on the public NetBox demo, as that is subject to change at any time by an outside party and cannot be relied upon for bug reports.

**Comment by jeremystretch** [comment]
Closing as there's been no further reply.
