### ISSUE TITLE
New Rack types - Vertical wall-mount (open frame and enclosed cabinet)

### ISSUE THREAD

**Issue by ZPrimed** [netbox-community/netbox#10516]
### NetBox version

v3.3.4

### Feature type

Data model extension

### Proposed functionality

There are several types of racks defined in the Rack data model, but there is no representation for a Vertical rack.

[Here's a 6U example from a well-known vendor (TrippLite)](https://www.tripplite.com/smartrack-6u-vertical-wall-mount-rack-bracket~SRWALLBRKT6U). 
[This is an example of an enclosed/cabinet-style from Navepoint.](https://navepoint.com/navepoint-4u-vertical-wall-mountable-server-rack/)

These may not be common in a true "datacenter," but in Real World IT, they definitely exist and are in use.

An interesting side-effect of the two-post / open frame form of these is that they are effectively "infinite" depth, or at least the depth of the rack is only limited by the height it is situated from the ground, or other devices mounted to the same wallboard within that volume. 

I'm not sure if this warrants any further discussion or extension of the model to properly document that quirk?
Obviously one could simply measure from floor to rail face to document the true maximum depth... this works great, until an overworked telco installer mounts something to the wallboard "inside" the rack space. 😆 

### Use case

Additional rack types would help to properly document the real world 😉 
For now, I am using "Wall-mounted frame" with additional details in the Notes, but the correct Type would be helpful!

### Database changes

Uncertain of necessary DB changes but suspect only minor, unless it is deemed necessary to try to describe "infinite" depth.

### External dependencies

(no external deps)

**Comment by jeremystretch** [comment]
Seems like the proposal is to add two new rack types:

* Wall-mounted frame (vertical)
* Wall-mounted cabinet (vertical)

If that's accurate I think it makes sense to do so.

**Comment by ZPrimed** [comment]
Yep, those two types would resolve my primary request here. 

I just wasn't sure if there is any concern around the potentially indeterminate / variable "depth" of a "Wall-mounted frame (vertical)". But depth can always be left empty, too. 😉

**Comment by postilion** [comment]
I concur that this is a real need.  We have a couple of 2U vertical Tripp-Lite cabinets, which I have replicated using a wall-mounted cabinet, 3U high (it's a 2U cabinet, with a 1U patch bay), but the orientation is goofy.
-nic
![QPmhSgpZ](https://user-images.githubusercontent.com/4181980/201143651-1c118a62-a8c7-42c8-a4ab-ef088c5b500b.svg)
