### ISSUE TITLE
Move NAPALM proxy functionality to a plugin

### ISSUE THREAD

**Issue by jeremystretch** [netbox-community/netbox#10520]
### NetBox version

v3.3.4

### Feature type

Change to existing functionality

### Proposed functionality

Move all NALPAM functionality out of NetBox core into a separate plugin that users can install as needed. (This is similar to what we did with secrets in v3.0; see #5278.) This includes:

- Removing the `/api/dcim/devices/$id/napalm/` endpoint
- Removing the device status, LLDP neighbors, and configuration UI views
- Removing the `napalm_driver` and `napalm_args` from the Platform model

Replicating this functionality in a plugin will require the completion of #9072, to enable the injection of object detail view tabs. Additionally, it will likely require a change to the REST API endpoint.

### Use case

NetBox's NAPALM API proxy was never intended to be more than a convenience, and is not encompassed by NetBox's core mission of serving as a source of truth. Additionally, issues concerning changes to NAPALM functionality distract from core development. Some examples include:

- #4980
- #7197
- #8079
- #8152
- #8861
- #10468 
- #10518

Moving this feature into a standalone project should help draw more development interest, as it will no longer have to compete for attention among core development efforts. It also opens the door for additional functionality via the introduction of new models and API endpoints.

**Comment by PieterL75** [comment]
I'd really love to see a SuzieQ integration also :-)
not as realtime as napalm, but is for sure will be faster :-)

**Comment by ryanmerolle** [comment]
> I'd really love to see a SuzieQ integration also :-) not as realtime as napalm, but is for sure will be faster :-)

This would really help users who want to integrate applications like suzie-q, librenms, zabbix, IP Fabric, Forward Networks, and the like by providing a reference model.  I'm not sure the maintainer team is volunteering at this point to develop these plugins in house.

**Comment by PieterL75** [comment]
Since the tabs can be added by a plugin, i think this is a good step to move napalm to a plugin, and indeed hope that other product maintainers hop on

**Comment by renatoalmeidaoliveira** [comment]
About the plugin migration, how the mantainer team are thinking about it?
My concern is about multi vendor support, for example it would be ok to add an folder to Netbox folder structure like reports, and scripts for custom parsers?

**Comment by jeremystretch** [comment]
We've retained the NAPALM fields on the Platform model for now to help with the migration. They'll be removed in a future NetBox release.
