### ISSUE TITLE
IPAM doesn't import interfaces

### ISSUE THREAD

**Issue by flinky50** [netbox-community/netbox#10536]
### NetBox version

3.2.0

### Python version

3.8

### Steps to Reproduce

1. Click on IP address
2. Click import
3. set address,status,description,interface as CSV fields
4. EG 192.168.0.0/24,active,My Server,device1

### Expected Behavior

IP Address to be created with an interface linked to it.

### Observed Behavior

![image](https://user-images.githubusercontent.com/114894442/193498332-ef23f307-3542-43d4-ad93-9040e94433e4.png)

**Comment by kkthxbye-code** [comment]
It is indicating that you have no interface named `device1` (would also be a weird name for an interface). When importing ip addresses you should provide both device name and interface name.

If you are actually wanting to import interfaces like the title of the issue suggests, that is not done in under IP Addresses, that's done under Interfaces.

Feel free to open a discussion if you have more trouble with the import forms.

**Comment by flinky50** [comment]
My interface isn’t called that. On my device I’ve created an interface called port 1. No matter what I enter it still throws that error

**Comment by kkthxbye-code** [comment]
According to your issue this is what you are trying to import as an IP address:

| address        | status | description | interface |
|----------------|--------|-------------|-----------|
| 192.168.0.0/24 | active | My Server   | device1   |

In english that would be an IP address with the address of 192.168.0.0/24 with the description "My Server" attached to the interface called "device1" on an unknown device.

You need to use the correct interface name and you need to add device. Please open a discussion if you have any more issues understanding the CSV import forms.

I would also recommend reading the documentation: https://demo.netbox.dev/static/docs/models/ipam/ipaddress/
