### ISSUE TITLE
Add Comments field to Locations (similar to Site functionality)

### ISSUE THREAD

**Issue by ZPrimed** [netbox-community/netbox#10530]
### NetBox version

v3.3.4

### Feature type

Data model extension

### Proposed functionality

I am proposing the addition of a "Comments" field to the Location model, with behavior identical to the Comments field on a Site (freeform Markdown text field).

### Use case

The "Comments" section of a Site is very useful to help provide access instructions or other general Site-related information.

Since Locations sit inside Sites, it would be helpful to have a similar Comments field to record additional information about each individual Location (like walking directions to access the Location, or notes about which specific Site Contact to use if there are locked doors, etc).

### Database changes

New `comments` field would be required on the Location class; I don't believe anything else would be required database-wise?

### External dependencies

(no external deps)

**Comment by jeremystretch** [comment]
Let's fold this into #10545
