### ISSUE TITLE
NGINX - 504 Error

### ISSUE THREAD

**Issue by apellini** [netbox-community/netbox#10535]
### NetBox version

v3.3.2

### Python version

3.9

### Steps to Reproduce

I have a netbox istance with 84k and 6k prefixes inserted and I have written a script that populates them daily.

The script collect all IP Addresses present in netbox and after check with external db to perform CRUD operation.

But many times I receive a 504 error from NGINX and I have no logs that could help me to find a feasible solution.

### Expected Behavior

I expect that script works correctly.

### Observed Behavior

504 Error timeout and sometimes 404.

**Comment by kkthxbye-code** [comment]
Thank you for your issue, however with the current description we cannot accept it as a netbox issue. Feel free to raise a discussion asking for help though.

A good start might be raising the timeout of nginx. If you manage to replicate this as a netbox specific bug, feel free to open a new issue, but please remember to follow the template and provide reproduction steps.
