### ISSUE TITLE
Add description & comments fields to all primary models

### ISSUE THREAD

**Issue by jeremystretch** [netbox-community/netbox#10545]
### NetBox version

v3.3.4

### Feature type

Data model extension

### Proposed functionality

This issue proposes adding an optional `comments` field to all [primary models](https://docs.netbox.dev/en/stable/development/models/#primary-models) that don't already have one. The list of relevant models includes:

* dcim.Cable
* dcim.PowerPanel
* dcim.RackReservation
* dcim.VirtualChassis
* ipam.Aggregate
* ipam.ASN
* ipam.FHRPGroup
* ipam.IPAddress
* ipam.IPRange
* ipam.L2VPN
* ipam.Prefix
* ipam.RouteTarget
* ipam.Service
* ipam.VLAN
* ipam.VRF
* wireless.WirelessLAN
* wireless.WirelessLink

### Use case

The application of comment fields to NetBox models has been somewhat arbitrary over time. It's fair to assume a use case for each primary model to have a comments field suitable for storing incidental notes.

**Comment by jeremystretch** [comment]
We should also consider adding a `comments` field to all organizational and nested group models.

**Comment by jcralbino** [comment]
Can we have this added also to the Image Attachments?
Currently only the Name field can be used to provide additional details but this is limited in size.

**Comment by jeremystretch** [comment]
Following discussion from today's maintainers meeting, I'm going to refine the scope of this as ensuring all primary models have both a description and comments field to ensure consistency across the application.
