### ISSUE TITLE
Introduce a utility function for accessing plugin configuration parameters

### ISSUE THREAD

**Issue by jeremystretch** [netbox-community/netbox#10543]
### NetBox version

v3.3.4

### Feature type

New functionality

### Proposed functionality

Introduce a simple utility function that plugin authors can use to reference specific plugin configuration parameters. Such a solution might look like this:

```python
from extras.plugins import get_plugin_config

myvar = get_plugin_config('plugin_name', 'myvar')
```

### Use case

This proposal was prompted by #10346, which seeks to better document the intended method for referencing plugin configuration parameters (which is currently achieved by referencing `settings.PLUGINS_CONFIG`). This approach is offered as a more convenient mechanism for plugin authors.

**Comment by cyberndj** [comment]
Would this mean we could change plugin entries in plugins.py?

**Comment by jeremystretch** [comment]
> Would this mean we could change plugin entries in plugins.py through the web interface?

No; it has nothing to do with manipulating installed plugins.
