### ISSUE TITLE
Add device interface description to global search

### ISSUE THREAD

**Issue by joubbi** [netbox-community/netbox#10553]
### NetBox version

v3.3.4

### Feature type

New functionality

### Proposed functionality

If you go to "DEVICE COMPONENTS" -> "Interfaces" and enter a word to search for in the search bar named "Quick search", it will find interfaces containing the searched for word in the Description field. This is just as I would expect. Great!

But if you enter the same word in the global search bar at the top of the page, it will not find the interface containing the searched for word in the in the description field of the interface. This is not intuitive.

It would be nice if the global search would look at the device interface descriptions as well.

### Use case

We document connected device names in the interface description field.
It is quite often we search netbox for hostnames in order to figure out on which device and interface they are connected to.
As it is now, we need to click on interfaces and use the Quick search on that page. It would be easier if the search bar at the top of the first page could be used instead.

**Comment by jeremystretch** [comment]
The current global search implementation does not include device components due to performance constraints. #10560 has been opened to track the development of an improved global search function, planned for release in NetBox v3.4. Please share any input you have under that issue.
