### ISSUE TITLE
Ability to view the endpoint of a trace within the interface view of a device

### ISSUE THREAD

**Issue by shatt79** [netbox-community/netbox#10561]
### NetBox version

v3.3.4

### Feature type

Change to existing functionality

### Proposed functionality

Currently, we can only see the other end of the attached cable connected to an interface or port when viewing a device.  Many times, there are multiple patch panels between the A and Z devices.  If I'm looking at the A device, I'd like to be able to see the Z endpoint of the trace without clicking on the trace button.  Maybe make it a column that could be added to the view...?

The first interface shows what it looks like when there are patch panels involved.  You can't see the Z device from this view.  The second interface shows what it looks like when the Z device is directly connected to the interface.  I would like to be able to see the Z device on the first line without clicking the trace button.

![image](https://user-images.githubusercontent.com/103387334/193934276-9aa500e3-0fce-4c7b-a1d2-8252e2156802.png)

### Use case

This would be helpful for when you need to quickly look through a device to find a specific circuit without having to click on the trace button for every interface/port. 

### Database changes

Not familiar enough with the schema to know if any changes are necessary.  At the surface, it appears like it would be a simple addition.

**Comment by joaolucasmacedo** [comment]
I guess it is already working. You need to select the appropriate columns, namely "link peers and connection.
See the pictures below where I can see 2 patch panel front ports directly connected to the G0/0/3 interface and the "Z end" interface of another device. If I click trace there are 2 more patch panels involved.

![Link peer2](https://user-images.githubusercontent.com/66760118/194558296-f02cc3d8-5202-44eb-9083-69f58b5b7faa.png)


I'm running Netbox 3.3.2.

**Comment by jeremystretch** [comment]
As noted above, this is already possible today by adding the desired column to the table. Closing this out as there's been no further reply from OP.
