### ISSUE TITLE
VM Import can generate duplicates

### ISSUE THREAD

**Issue by MattBoxIT** [netbox-community/netbox#10564]
### NetBox version

3.3.3

### Python version

3.9

### Steps to Reproduce

1. Click on import VM
2. Insert a VM with the same name, status, site and cluster as an existing VM

### Expected Behavior

Error: A virtual machine with this name already exists in the assigned cluster

### Observed Behavior

Import is succesful and the new VM with same name, status, site and cluster is generated.

The observed behavior happens once.
Trying to import the same VM again throws the error "Error: A virtual machine with this name already exists in the assigned cluster"

**Comment by kkthxbye-code** [comment]
Thank you for opening a bug report. Unfortunately, the information you have provided is not sufficient for someone else to attempt to reproduce the reported behavior. Remember, each bug report must include detailed steps that someone else can follow on a clean, empty NetBox installation to reproduce the exact problem you're experiencing. These instructions should include the creation of any involved objects, any configuration changes, and complete accounting of the actions being taken. Also be sure that your report does not reference data on the public NetBox demo, as that is subject to change at any time by an outside party and cannot be relied upon for bug reports.

**Comment by MattBoxIT** [comment]
I figured out that this only happens when VM to import has blank or different tenant, so it should be the expected Behavior.
