### ISSUE TITLE
Okta OIDC integration requires additional Python packages

### ISSUE THREAD

**Issue by skoobasteeve** [netbox-community/netbox#10575]
### NetBox version

v3.3.5

### Python version

3.10

### Steps to Reproduce

1. Install Netbox on Ubuntu 22.04 by following the official documentation.
2. Configure the Okta integration by following the official documentation.
3. Try to log in via Okta

### Expected Behavior

Netbox logs in successfully.

### Observed Behavior

A Django error page loads ands shows an error:
`ModuleNotFoundError: No module named 'jose'` 

I'm able to resolve the issue by installing `python-jose` using the below steps:
``` 
sudo -i
source /opt/netbox/venv/bin/activate
sudo pip install python-jose[openidconnect]
sudo pip install python-jose[cryptography]
deactivate
sudo systemctl restart netbox netbox-rq
```
It's possible that those commands are redundant, but either way I needed `python-jose` to make Okta work. After installing Okta sign-in works without issue. Perhaps this could be resolved in the future by adding python-jose to the requirements.txt? Let me know if you need any more info.

Thank you for all your work!

**Comment by skoobasteeve** [comment]
Amazing, thank you @jeremystretch

**Comment by jeremystretch** [comment]
This was all @arthanson actually :slightly_smiling_face:

**Comment by skoobasteeve** [comment]
@arthanson Thank you both for the quick response!
