### ISSUE TITLE
Cable tracing to/from Circuit Termination not working in v3.3.4

### ISSUE THREAD

**Issue by Wexter** [netbox-community/netbox#10579]
### NetBox version

v3.3.4

### Python version

3.10

### Steps to Reproduce

1. Create Provider Network
2. Create any device with at least one network interface
3. Create Circuit
4. Connect Termination A or Z to Provider Network
5. Connect second termination to device site and connect it with cable to device interface

### Expected Behavior

Cable trace from Circuit Termination should show Destination

### Observed Behavior

Destination shows "Incomplete", instead of Provider Network.
Also Cable connection in device interface shown as Not Reachable

Working example in 3.2.9 https://youtu.be/LhyJyduvS8w
Not working example in 3.3.4 https://youtu.be/dUaFSslZncU

**Comment by Wexter** [comment]
I've done some debugging and probably fixed this problem by setting CablePath.is_complete=True for Circuit Termination connected to Provider Network.
At least `./manage.py test dcim.tests.test_cablepaths` were OK and trace now works as I expect.

**Comment by jeremystretch** [comment]
Thanks for digging into this @Wexter, and apologies for the delay in getting around to it.
