### ISSUE TITLE
Custom fields for Users

### ISSUE THREAD

**Issue by PieterL75** [netbox-community/netbox#10572]
### NetBox version

v3.3.0

### Feature type

Change to existing functionality

### Proposed functionality

Custom fields are currently supported for Netbox Models.
Can this be extended to Users also

### Use case

We have now a situation where we would like to store custom data on a user object.
This additional data is only related to that Used and not to any objects they create.

This additional account data, is required for API integrations in webhooks.

### Database changes

Probably need to extend the Djange User Model with customfieldmixin

**Comment by jeremystretch** [comment]
> Can this be extended to Users also

We're not able to easily extend the built-in Django User model without a fairly disruptive migration to a custom user model, unfortunately. Instead, the recommended approach would be to write a plugin that introduces a model to hold the desired data and its relation to a NetBox user.
