### ISSUE TITLE
Implement pagination, filtering, and export functionality for report and script results

### ISSUE THREAD

**Issue by atownson** [netbox-community/netbox#10587]
### NetBox version

v3.3.5

### Feature type

New functionality

### Proposed functionality

My proposal is to implement pagination, filtering, and export options for the report Report Results panel and the script Script Log panel.

For pagination, implement pagination for reports (Report Results panel) and scripts (Script Log panel) in the same manner as the model table pages, with a **Per Page** input.

As far as filtering for reports, the current **Report Methods** panel provides hyperlinks to the method results in the **Report Results** panel. Instead of grouping the results by **Method** in the **Report Results** panel, create a new "Method" column which could be filtered. Perhaps the **Report Methods** panel hyperlinks could be transitioned to provide quick filters rather than hyperlinks. My suggestion for filtering options would be to provide dropdown inputs to filter the **Method** and **Level** fields and textboxes to filter the **Object** and **Message** fields. Filters could be provided in a **Filters** tab, similar to the model table pages, to conserve real estate on the page.

My suggestion for filtering the **Script Log** for scripts would be to provide a dropdown input to filter the **Level** field and a textbox to search the **Message** field. 

For export, implement exporting for reports (Report Results panel) and scripts (Script Log panel) in a similar manner as the model table pages, with an **Export** dropdown. I don't see a need for export template functionality. But rather simply "Export All" and "Export Filtered" options to export all results and the currently filtered results respectively.

### Use case

Pagination would prevent the page content from becoming too large if many results are returned.

Filtering would allow users to better organize or search the results.

Export functionality would allow the results to be used outside the NetBox environment (i.e. emailed to users to correct certain modeling mistakes).

### Database changes

None

### External dependencies

None

**Comment by atownson** [comment]
Sure, here's an illustration for Scripts:
![image](https://user-images.githubusercontent.com/52260120/194366299-8d829610-a6c0-4fb0-bf1f-b5d7c15daf5f.png)

**Comment by atownson** [comment]
@kkthxbye-code, here's an illustration for Reports:
![image](https://user-images.githubusercontent.com/52260120/194371854-516aed62-f08c-4483-a106-c9602bcd2d8e.png)

**Comment by jeremystretch** [comment]
Related: #9376

**Comment by renatoalmeidaoliveira** [comment]
@atownson since you are working in scripts, maybe some kind of "script hook" could be a nice feature.
That way the user can setup a script to be runned when something changes in Netbox

**Comment by jeremystretch** [comment]
Great idea! @renatoalmeidaoliveira I just opened FR #11827 for this.

**Comment by ryanmerolle** [comment]
pushed to 3.6 milestone

**Comment by lucasalvatore** [comment]
👋 would love to be able to filter reports on the UI based on level (or any other row heading really)
