### ISSUE TITLE
Way to document brushpanel/cablemanager

### ISSUE THREAD

**Issue by PieterL75** [netbox-community/netbox#10617]
### NetBox version

v3.3.5

### Feature type

New functionality

### Proposed functionality

It would be great that we could mark units in a rack as 'occupied with brushpanel/cableguide', without the need of creating them as devices.

### Use case

In our the rack elevation, there are many empty slots.
This is mainly because there no easy way to document brushpanels and cableguides.
The only way is to create a device per panel and populate that in the rack, and that is a lot of work and not really relevant to the device objects lifecycle

This will make the presentation of the rack elevations better, and will give us a better overview of the unit usage of the racks.

### Database changes

- extra csv field of 'occupied' units in a rack.
- optional a 'type' field of the used rackunit (brushpanel, cableguide, ...)

**Comment by jeremystretch** [comment]
Thank you for submitting this issue, however it appears that this topic has already been raised. Please see issue #9129 for further discussion.

**Comment by PieterL75** [comment]
I overlooked that topic, as it was closed already.
It handles mainly about blank panels. but those are not the goal of my request. 
I don't see any value in keeping track of blank panels, the solution to that, is to make the background of a rack black :-)

My aim , is to document Units that are occupied by items that are not devices (no ports, no power, no serial, no asset tag)
It is import for planning to know what units are in use by those items.

Creating a device for each brushpanel is too much overhead. How to call those ? and what status do you give them ?

It would be easier to just be able to mark units as in use per rack, with an optional idea to use a dropdown to select what the unit is used by.

**Comment by PieterL75** [comment]
also seeing https://github.com/netbox-community/netbox/issues/417 all with a lot of thumsup...

We did document those things as devices in the past, but that was not workable.. we had 1/4 of our devices being brushpanels..
In our old cmdb we did create the 'occupied slot' feature and that really made things feel more 'real'

**Comment by kkthxbye-code** [comment]
> How to call those ?

You don't have to call them anything, devices can be unnamed.

> and what status do you give them ?

Active?

**Comment by PieterL75** [comment]
Not active, just dead? Never tried unnamed devices, strange idea..

Devices are really not the way to put this in.
It is not a device, just a panel that lies en mass in the datacenter and don't need lifecycle, monitoring, ticketing, ...

Maybe we should get back to another FR, and that is too hide devices from the default view (like 'out of production'). Then those panels can still be a device, but will not show up in a simple search, only when a specific status is selected...

**Comment by DanSheps** [comment]
> We did document those things as devices in the past, but that was not workable.. we had 1/4 of our devices being brushpanels..
> 
> In our old cmdb we did create the 'occupied slot' feature and that really made things feel more 'real'

I have 11261 "Devices".  I would say over 3/4 of them are not traditional "devices".  I have some devices which are simply a front and a rear-port to represent a wall/ceiling termination.

You can model any items using Devices.  As mentioned, you don't need to give these devices names and the bare minimum of information is all that is required.

> It is not a device, just a panel that lies en mass in the datacenter and don't need lifecycle, monitoring, ticketing, ...

A panel is still a [device ](https://www.merriam-webster.com/dictionary/device) (Definition: "a piece of equipment or a mechanism designed to serve a special purpose or perform a special function"), just not a device that has any interfaces.

> Maybe we should get back to another FR, and that is too hide devices from the default view (like 'out of production'). Then those panels can still be a device, but will not show up in a simple search, only when a specific status is selected...

There are a number of filters you can already employ to remove these from view

**Comment by PieterL75** [comment]
Having no need for a name of a device is indeed a + for not investing time in my proposal.. 
So I'll pass the word and get going with unnamed brushpannels..

What filters do you mean? Can i set default filters for device views for all users?
