### ISSUE TITLE
Trace only works when an interface is connected.

### ISSUE THREAD

**Issue by LHBL2003** [netbox-community/netbox#10648]
### NetBox version

v3.5.4

### Python version

3.10

### Steps to Reproduce

Create 2 to 3 devices with at least one front port and rear port. 

Link the front and rear ports together.

Form a chain 

Device 1 Front Port --> Rear Port --> Device 2 Rear Port --> Front Port --> Device 3 Rear Port --> Front Port

You now have e.g. three patch panels connected to each other.

### Expected Behavior

The Trace button can be operated at Rear Port 1 of Device 1. However, "No paths found" is displayed.

### Observed Behavior

On Device 1 I go to the Rear Port
Now I click on Trace at Rear Port 1.
Result: I do not see the connections between the patch panels. (No paths found)

Navigate to the front ports of Device 1.
Connect port 1 to an interface.
Result 1: The trace symbol can be operated at the front port. The complete cable path is displayed.
Result 2: The trace symbol can still be operated at the front port. The complete cable path is now also displayed here.

![image](https://user-images.githubusercontent.com/46369917/195791426-24a6aa71-81ae-456e-abfd-a1b14398915f.png)

![image](https://user-images.githubusercontent.com/46369917/195791464-7019858b-2111-4e1f-ad1c-de7dc8295b2d.png)

Please also show the cable path if no interface is connected.

This shows from where to where e.g. a network socket is patched via the patch panels before connecting a device. Sometimes no device is connected to the Netbox, e.g. staff workstations with notebooks. Nevertheless, we would like to be able to trace where the cable routes lead to.

Many thanks

**Comment by jeremystretch** [comment]
This is intended behavior, however FR #9718 has been opened to explore the feasibility of implementing the described changes.
