### ISSUE TITLE
prechange_data in changelog empty for frontports if rearport gets deleted

### ISSUE THREAD

**Issue by PaulR282** [netbox-community/netbox#10647]
### NetBox version

v3.3.5

### Python version

3.10

### Steps to Reproduce

1. Create device with a rearport
2. Add frontports to the device, which connect to the rearport
3. Delete the rearport (the frontports get deleted too)
4. Go to the changelog item of a deleted frontport

### Expected Behavior

The Pre-Change Data should be filled with the attributes the frontport had.

### Observed Behavior

Pre-Change Data is empty

**Comment by jeremystretch** [comment]
Thank you for submitting this issue, however it appears that this topic has already been raised. Please see issue #6389 for further discussion.
