### ISSUE TITLE
Natural sorting for Circuits

### ISSUE THREAD

**Issue by mrgromdd** [netbox-community/netbox#10644]
### NetBox version

v2.11.6

### Feature type

Data model extension

### Proposed functionality

When showing a list of Circuits, use "natural" sorting so that e.g. c2 becomes before c10

### Use case

Easier to find things when scanning through or paging through listings

### Database changes

Possibly a _name field padded in the same way that interfaces are

### External dependencies

nope

**Comment by mrgromdd** [comment]
![image](https://user-images.githubusercontent.com/28609214/195642460-48a775f9-af77-4817-a794-2db269400b1c.png)

**Comment by jeremystretch** [comment]
Folding this into a broader conversation around natural ordering under #11279.
