### ISSUE TITLE
Add multiple images at once

### ISSUE THREAD

**Issue by PaulR282** [netbox-community/netbox#10649]
### NetBox version

v3.3.5

### Feature type

Change to existing functionality

### Proposed functionality

It would be nice to be able to select multiple images at once when uploading images to a rack.

### Use case

This makes it easier when you have multiple images of a rack you want to document.

**Comment by cpund** [comment]
I'll take this.

**Comment by jeremystretch** [comment]
@cpund are you still planning to work on this? If not I'd like to remove you from the issue.

**Comment by cpund** [comment]
@jeremystretch hey sorry, forgot about it. I'll make some time in the next week to work on it.

**Comment by cpund** [comment]
Yeah, sooo. I lied about a week. I am now looking over it all now - trying to learn how the whole image selection process goes, as well as how the form is built so that I can figure out how to implement selecting multiple images at once. Great learning opportunity for me!

**Comment by cpund** [comment]
@jeremystretch judging by what I've been able to ascertain so far, I could either use a formset with a given amount of images (maybe allow up to 5 at once?) and users would be able to rename the files, BUT they'd have to choose each file individually (meaning opening the file picker 5 times) ORRRR I could allow selection of multiple images from the file picker, but then we couldn't apply a new name to each. Personally, I lean to the latter for ease of convenience and renaming files on one's computer prior is easy enough (unless you're doing this from your phone, which one very well may be if they're taking pictures of the rack on the spot). 

Thoughts?
