### ISSUE TITLE
All tables' Contacts field now contains pointer to the item

### ISSUE THREAD

**Issue by atownson** [netbox-community/netbox#10655]
### NetBox version

v3.3.5

### Python version

3.8

### Steps to Reproduce

1. Create a VM
2. Add a Contact to the VM
3. Add the Contacts column to the Virtual Machines table
4. View the VM in the Virtual Machines table

### Expected Behavior

The contact is displayed for the Contacts field.

### Observed Behavior

The contact is displayed for the Contacts field with a reference to the VM.

![image](https://user-images.githubusercontent.com/52260120/195859938-31917e45-b114-4158-8e09-efc9374a1749.png)

**Comment by atownson** [comment]
This appears to be the case for the Contacts field for all model tables.

**Comment by jeremystretch** [comment]
This is a regression from #10491. We probably just need to tweak the display of the contact assignment in the column.
