### ISSUE TITLE
Prohibit multiple connections

### ISSUE THREAD

**Issue by powerscooter** [netbox-community/netbox#10684]
### NetBox version

v3.3.5

### Feature type

New functionality

### Proposed functionality

I need a function to disallow the new "multiple connections" feature.
We automate a lot with Netbox. With the new function it is not possible to build automation in our setup. Because we need to document 1 to 1 connections.

A multiple connection of one interface to several is difficult to evaluate.
We always name the interfaces in Netbox as they are called in the system of the device.
So you can always document a 1 to 1 connection here.

### Use case

To avoid errors I must be able to switch off this function. Otherwise errors can occur in the automation.

**Comment by jeremystretch** [comment]
There's nothing preventing you from continuing to model one-to-one connections; _most_ connections are one-to-one, and that hasn't changed. Only the way in which cables are modeled has changed. If you need assistance adapting to the new API format, please consider opening a [discussion](https://github.com/netbox-community/netbox/discussions/new).
