### ISSUE TITLE
Hyperlinks for the Connections panel in the dashboard do not filter for connected models

### ISSUE THREAD

**Issue by atownson** [netbox-community/netbox#10682]
### NetBox version

v3.3.5

### Python version

3.8

### Steps to Reproduce

1. Create a device and two interfaces on the device
2. Create a cable for one of the interfaces on the device
3. On the dashboard, click the Interfaces hyperlink on the Connections panel

### Expected Behavior

The table is filtered to the connected interfaces only.

### Observed Behavior

The table displays all interfaces.

This behavior applies to the Console, Interfaces, and Power Connections hyperlinks on the Connections panel.

The fix would be to add the **cabled** parameter:
Console : .../dcim/console-ports/?cabled=True
Interfaces : .../dcim/interfaces/?cabled=True
Power Connections : .../dcim/power-ports/?cabled=True

**Comment by jeremystretch** [comment]
> 3. On the dashboard, click the Interfaces hyperlink on the Connections panel

Sorry, where exactly are you clicking?

**Comment by atownson** [comment]
![image](https://user-images.githubusercontent.com/52260120/196568801-38dbc45a-7bf5-4547-8653-d0868360eb76.png)

**Comment by jeremystretch** [comment]
Ah, I follow now, thanks. I was clicking the navigation link.
