### ISSUE TITLE
Custom links are showing up as column options in the model's table view

### ISSUE THREAD

**Issue by atownson** [netbox-community/netbox#10693]
### NetBox version

v3.3.5

### Python version

3.8

### Steps to Reproduce

1. Create a new Custom Link for model Device
![image](https://user-images.githubusercontent.com/52260120/196690383-238f904d-a56f-49a3-8f82-0ce868fe42ce.png)

2. Navigate to the Devices table page
3. Click the Configure Table button
4. Notice the name of the Custom Link appears as a column option
![image](https://user-images.githubusercontent.com/52260120/196690862-9b321489-c529-4da6-a319-4b6fd57f074d.png)

### Expected Behavior

The Custom Link is not an available column

### Observed Behavior

The Custom Link is presented as an available column.
![image](https://user-images.githubusercontent.com/52260120/196691161-df324c5c-06d6-45d6-88c9-1943d859838a.png)

Clicking the hyperlink returns a 404 -> .../dcim/devices/interfaces (based on the configured Custom Link above).

**Comment by kkthxbye-code** [comment]
This is intended and not a bug.

**Comment by jeremystretch** [comment]
This feature was introduced in #6782

**Comment by atownson** [comment]
OK, thanks for the clarification. We typically use Custom Links in the details page. So the configured link renders .../dcim/devices/1/interfaces in that context (which is correct).
