### ISSUE TITLE
Content type column should display model name only, omitting app name

### ISSUE THREAD

**Issue by jeremystretch** [netbox-community/netbox#10698]
### NetBox version

v3.3.5

### Feature type

Change to existing functionality

### Proposed functionality

Table columns which indicate an object/content type should display only the model name, without its parent app. For example, when viewing a list of custom fields assigned to the site model, the "content types" column should display "Site" rather than "DCIM > site".

### Use case

Omitting the app name for each type provides a cleaner view. While it's possible that plugins may introduce identical model names, this is unlikely to be problematic in practice, and viewing and this change is limited to lists of multiple objects. Viewing a single object would still display the associated app in additional to the model.

**Comment by jcralbino** [comment]
I think the users creating customs fields should be already aware of the model structure of netbox. 

As a user I have accustomed to its view. 

As a newbie developer i believe there is a strong possibility of collisions for the plug-in owner to create similar names to others already existing in netbox. 
Can you force plug-in datamodel to appear with their "Pluginname > object ", while removing the primary only for netbox core models
