### ISSUE TITLE
Unable To Assign Child Interface in VC to LAG Interface

### ISSUE THREAD

**Issue by michaelmcdonald** [netbox-community/netbox#10705]
### NetBox version

v3.3.5

### Python version

3.8

### Steps to Reproduce

1. Create two switch devices
2. Create a virtual chassis device
3. Assign switch devices to virtual chassis device
4. Assign a "Master" switch in the virtual chassis device
5. Create a LAG interface on the master switch device
6. Edit switch device interface on 1st member switch, LAG interface is present
7. Edit switch device interface on 2nd member switch, LAG interface is _not_ present

This is identical in behavior to Bug #9306 which itself was identical to #6426

### Expected Behavior

Expect to be able to assign child interfaces to LAG interface

### Observed Behavior

Interfaces on the master switch are available for being assigned as child interfaces of the LAG interface; however the interfaces on any subsequent switch devices within the virtual chassis are _not_ available for the LAG interface.

**Comment by jeremystretch** [comment]
Thank you for submitting this issue, however it appears that this topic has already been raised. Please see issue #10610 for further discussion.
