### ISSUE TITLE
assigned_object_id type does not match id type in graphql output

### ISSUE THREAD

**Issue by neuro42** [netbox-community/netbox#10702]
### NetBox version

v3.3.4

### Python version

3.9

### Steps to Reproduce

1. Have a device created with a primary_ip4 assigned to one of its interfaces
2. GraphQL query such as:
```
{
  device_list(name:"DEVICE") {
    primary_ip4 {
      assigned_object_id
    }
    interfaces {
      id
    }
  }
}
```

### Expected Behavior

primary_ip4.assigned_object_id and interfaces.id to have the same type so they can be compared without typecasting either assigned_object_id to a string, or the object id to an integer.  This may affect other models than primary_ip#, but is where I ran into it.

### Observed Behavior

assigned_object_id is an integer (unquoted) in GraphQL output, while the id returned from the interface is a string (quoted) in GraphQL output.

**Comment by arthanson** [comment]
Closing, this becomes a non-issue with the 3.4 updates.  now instead of assigned_object_id it is assigned_object and you can use fragments to get the id.
