### ISSUE TITLE
link console speed on device with console server port speed

### ISSUE THREAD

**Issue by powerscooter** [netbox-community/netbox#10704]
### NetBox version

v3.3.5

### Feature type

New functionality

### Proposed functionality

Hello all,

when I configure the speed of the console port of a device, I have to configure this on the console server port as well.

Since these values must be the same on both devices for console access to work, it would be very helpful if these values would always sync.

### Use case

When I configure the console port from the device. It would be nice if this changes directly on the connected console server port.

Thanks!

**Comment by ryanmerolle** [comment]
Feels like a good report or script you could create to address this.

**Comment by jeremystretch** [comment]
> Since these values must be the same on both devices for console access to work, it would be very helpful if these values would always sync.

NetBox intentionally does not make any assumptions about correct values on behalf of the user, as doing so would be very dangerous. For example, if you connected a console port configured with an incorrect speed of 9600bps to a console server port with a correct speed of 115200bps, the proposed implementation would erroneously adjust the server port, resulting in an incorrect state.

Instead, as @ryanmerolle suggests, you can leverage a [report](https://docs.netbox.dev/en/stable/customization/reports/) or [custom validation](https://docs.netbox.dev/en/stable/customization/custom-validation/) to automatically check for and correct these conditions as necessary.
