### ISSUE TITLE
Add optional Site field to WirelessLAN model

### ISSUE THREAD

**Issue by tyler-8** [netbox-community/netbox#10711]
### NetBox version

v3.3.5

### Feature type

Data model extension

### Proposed functionality

Add an optional `ForeignKey` field pointing to `Site` for the `WirelessLAN` model.

Also show the `Site` relation in the various GUI components where applicable: WirelessLAN detail & list views (as column and filter), the Site detail page "Related Objects" table, etc.

### Use case

With more than a few SSIDs in NetBox it can be a challenge to identify where exactly a WLAN resides without digging into the related VLAN information, or the related interface/device attachments.

Additionally, given that VLAN<->site membership is optional, and a WLAN may be documented without physical interface relationships, it creates more possible confusion. Having the Site relationship be clearly & directly established with the WirelessLAN would improve the documentation capabilities vastly.

### Database changes

New ForeignKey field on WirelessLAN model

### External dependencies

N/A

**Comment by tb-killa** [comment]
The combination of Wifi on Site would allow specific selection per SSID on Site like Prime for example.
