### ISSUE TITLE
CustomField of the type DateTime

### ISSUE THREAD

**Issue by PieterL75** [netbox-community/netbox#10729]
### NetBox version

v3.2.9

### Feature type

New functionality

### Proposed functionality

Create a new Custom Field of the type 'DateTime'

### Use case

I need to store date and time values in a custom field. Currently this is only possible in a text field, but then the sorting is off.
A date-time fieldtype could be very useful,

**Comment by jeremystretch** [comment]
Closing this as it might involve working with timezones again. /s

This is probably doable if we normalize to an ISO timestamp. I assume we'd store values using the system's timezone and adjust on display to the user.

**Comment by PieterL75** [comment]
since NetBox is in only one timezone (and not per user), it would be good to store the UTC timestamp and convert it to the timezone of NetBox during the display.
