### ISSUE TITLE
Add small delay to the menu onmouseover

### ISSUE THREAD

**Issue by jhammond-git** [netbox-community/netbox#10720]
### NetBox version

v3.3.4

### Feature type

Change to existing functionality

### Proposed functionality

I would like to see a (possibly optional) delay for collapsed menu fly-out.

When using a collapsed menu, the mouseover delay is effectively 0, meaning that if you move your mouse just a little too far and click, you end up navigating to whatever your mouse happens to be over once the menu expands.  Adding a small delay would reduce the number of accidental navigation errors and delays.

I acknowledge that this is a minor annoyance, but I hope that it's a minor fix.

### Use case

Reduces delay and mis-clicks for those that use a collapsed menu.

### Database changes

None

### External dependencies

None

**Comment by PieterL75** [comment]
I have a branch ready that adds a 200ms delay to the navbar opening.. Might be a little too much, but lets see what it feels like
https://github.com/PieterL75/netbox/tree/isssue10720_delaynavbar

I can create a PR if that is ok

**Comment by jeremystretch** [comment]
As this seems to require a disproportionate amount of effort to implement, I'm closing this out in favor of the planned migration to Tabler (see #12128).
