### ISSUE TITLE
Option to hide half-height (.5) positions when selecting device position

### ISSUE THREAD

**Issue by szeestraten** [netbox-community/netbox#10728]
### NetBox version

v3.3.5

### Feature type

Change to existing functionality

### Proposed functionality

Add option to hide half-height (.5) positions when selecting device position.

![image](https://user-images.githubusercontent.com/614823/197483079-b6061fb7-ea36-4d89-83eb-99c7c16f2781.png)
*Hide the ones in red*

### Use case

Half-height rack units (#51) were introduced in v3.3.0.

The list of positions is now quite a bit longer and prone to misclicking when manually selecting the position of a device.

Adding the option/preference to hide half-height positions for those of us without half-height units would simplify things.

**Comment by kkthxbye-code** [comment]
> and prone to misclicking when manually selecting the position of a device.

I'm not sure I follow why it would be easier to misclick. The distance between elements in the list is the same. The amount of options displayed at once is the same. Why is it easier to misclick U41.5 than to misclick U42 before half-height? Or instead of misclicking do you mean that your users are not seeing the `.5`.

**Comment by szeestraten** [comment]
> I'm not sure I follow why it would be easier to misclick. The distance between elements in the list is the same. The amount of options displayed at once is the same. Why is it easier to misclick U41.5 than to misclick U42 before half-height? Or instead of misclicking do you mean that your users are not seeing the `.5`.

Misclick might be poor choice of word here, sorry.

I mean users (me and my colleagues) not seeing the `.5` part.
The `.5` positions also gets sorted to the top (first choice) when filtering the dropdown.

**Comment by kkthxbye-code** [comment]
> I mean users (me and my colleagues) not seeing the .5 part.

I have a really hard time seeing how. Maaaybe if they were the same length U4.0 and U4.5, but they are very clearly distinguished currently. Is this a text size issue? How does it look on your screen?

> The .5 positions also gets sorted to the top (first choice) when filtering the dropdown.

They get sorted oposite when you choose decending order for your rack. I don't see it making sense changing this behavior.

Currently I don't see a compelling reason for accepting this FR, but I'm open to being convinced. My best advice would be to register a custom validator and reject setting the position to a .5 on devices.

**Comment by szeestraten** [comment]
> > I mean users (me and my colleagues) not seeing the .5 part.
> 
> I have a really hard time seeing how. Maaaybe if they were the same length U4.0 and U4.5, but they are very clearly distinguished currently. Is this a text size issue? How does it look on your screen?

It looks normal as in the screenshot above, but I guess reading left to right we interpret the first part (**`U42`**) of `U42.5` and then think that's the right choice when in a hurry not expecting half-height units.

> > The .5 positions also gets sorted to the top (first choice) when filtering the dropdown.
> 
> They get sorted oposite when you choose decending order for your rack. I don't see it making sense changing this behavior.

Ah, that makes sense.

> Currently I don't see a compelling reason for accepting this FR, but I'm open to being convinced. My best advice would be to register a custom validator and reject setting the position to a .5 on devices.

That's fair. It's just an UX noise thing in our opinion when we don't have any half-height devices.

Thanks for the custom validator tip, I didn't think of that!

**Comment by PieterL75** [comment]
I'm not fond of those half heights neither... We dont use then at all in our DC's (500+ racks)
I would love an option to disable that if not being used.. 
Or that you can set per rack if halfheights are supported or not.

**Comment by IdRatherStand** [comment]
We also have no half-heights specified so this is worse for us UX wise, having said that for us it would be lower down on our list of FRs to be worked on.

**Comment by cyr0nk0r** [comment]
I agree. For certain environments, half height devices are useful, but there are also a lot of environments that don't need this. It would be nice to be able to turn this feature off. Ideally, a master setting that turns it off environment wide.

**Comment by kkthxbye-code** [comment]
Personally I don't see this as a good feature for a few reasons:

- I don't feel like there's been any compelling objective arguments as to why this is a UX issue. Not using the feature is not enough reason for us to implement a toggle.
- I dislike the idea of adding toggles for features like this. It makes the codebase more complex for (imo) little gain.
- I think time is better spent elsewhere.

@netbox-community/netbox-core - Any other opinions?

**Comment by PieterL75** [comment]
Still wondering how much this half height is used by the community.
Another option, is to redesign the way devices are placed in a rack. Why not make it a nice UI based thing using the track elevation.
Then we can't be annoyed by the half units in the drop-down.

**Comment by PieterL75** [comment]
I wish I had the skills to build it... Looks like I'm better in propagating BGP routes and protecting layer 2 domains, then coding UI's

I would still love to see the option to remove the .5 units from the drop-down. Not a global setting, but an option per rack would be awesome. It is very confusing for people who don't ever use .5 units

P

**Comment by pobk** [comment]
Sub-U addressing is useful for instance where network taps (e.g. Microtel T-30). However, I think the rack position selection process is a bit clunky.

It has a few UI issues... For example, the shading on "consumed" slots in the rack is not absolutely clear so it's sometimes a chore to scroll through to identify the available slots in the list. (This is also the same issue when connecting ports/cables).

Personally, I would have preferred text-field in place of a select box with a bit of client side validation.

I would support some UI options to hide .5Us options.

**Comment by stovakor** [comment]
Honestly I like the idea of an input box for the rack unit number a lot better than a drop down.
It's much faster to just type 18, than it is to scroll down fast to get to the bottomish of the drop down and then scroll slow to find exactly RU18.

If my device is at 18.5 .. great, I just type 18.5.

**Comment by PieterL75** [comment]
Isn't it already like that? When clicking the position, it gives a drop-down that has a text filter field..

But this deviates from the question : an option to hide the half rack units ( from some racks)

**Comment by stovakor** [comment]
You're right, but it would be nice if hitting 'enter' after typing a value would actually input the value instead of having to click on the number anyway.

**Comment by sbingner** [comment]
This "feature" is cluttering the selection and making life difficult. Half RU is a very edge case that should not be shown with no option to get rid of it.  Of course having a UI to drop templates onto racks and drag connections for cables would fix all this...

**Comment by jeremystretch** [comment]
@sbingner cool, so I take it you're interested in contributing a proposed improvement?
