### ISSUE TITLE
Custom field objects sort by ID rather than what they display

### ISSUE THREAD

**Issue by neuro42** [netbox-community/netbox#10721]
### NetBox version

v3.3.6

### Python version

3.9

### Steps to Reproduce

1. Add a custom field
   1. Model: IPAM > prefix
   2. Name: gateway
   3. Type: object
   4. Object type: IPAM > IP address
2. Add some IP addresses (being out of sorted order)
   1. 172.16.42.1/24
   2. 172.16.10.1/24
   3. 172.16.128.1/24
   4. 172.16.6.1/24
3. Add some prefixes, using the added IP address objects for the custom gateway field
   1. 172.16.42.0/24 w/ 172.16.42.1/24
   2. 172.16.10.0/24 w/ 172.16.10.1/24
   3. 172.16.128.0/24 w/ 172.16.128.1/24
   4. 172.16.6.0/24 w/ 172.16.6.1/24
4. View the prefix list, and configure the table to include the custom gateway field
5. click on the gateway column header to sort by the custom field 

### Expected Behavior

Gateway column to be in sorted IP address order:
172.16.6.1/24
172.16.10.1/24
172.16.42.1/24
172.16.128.1/24

### Observed Behavior

Gateway column is sorted by object id (creation order):
172.16.42.1/24
172.16.10.1/24
172.16.128.1/24
172.16.6.1/24

Non-custom columns (eg: site) are sorted by their name, and not their ID

**Comment by jeremystretch** [comment]
Thank you for opening a bug report. Unfortunately, the information you have provided is not sufficient for someone else to attempt to reproduce the reported behavior. Remember, each bug report must include detailed steps that someone else can follow on a clean, empty NetBox installation to reproduce the exact problem you're experiencing. These instructions should include the creation of any involved objects, any configuration changes, and complete accounting of the actions being taken. Also be sure that your report does not reference data on the public NetBox demo, as that is subject to change at any time by an outside party and cannot be relied upon for bug reports.

**Comment by neuro42** [comment]
Steps to reproduce rewritten
