### ISSUE TITLE
Old doc files still exist and reachable on https://demo.netbox.dev/

### ISSUE THREAD

**Issue by ypid** [netbox-community/netbox#10722]
### Change Type

Cleanup (formatting, typos, etc.)

### Area

Other

### Proposed Changes

I noticed that https://demo.netbox.dev/static/docs/core-functionality/power/ is still deployed even though it is not contained in the lastest release anymore. I suspect you just copy over the generated files over to the webserver without deleting files that don’t exist anymore. This can be confusion because search engines still have this URL indexed, also note that the table of contents if different as soon as you click on a link in in the table of contents that is still contained in the lastest release.

**Comment by jeremystretch** [comment]
Thanks for the heads up, however I'm going to close this as it's not relevant to the code base.
