### ISSUE TITLE
Edit ip address - change device assignment, doesnt clear interface assignment. causes confusion

### ISSUE THREAD

**Issue by ITJamie** [netbox-community/netbox#10757]
### NetBox version

v3.3.5

### Python version

3.10

### Steps to Reproduce

1. goto an ip address with an existing assignment, eg https://demo.netbox.dev/ipam/ip-addresses/186/
2. edit the ip address, change the vm or device assignment, eg from vm1 to vm2.
3. Notice that interface field below still says eth0
(its not obvious but that eth0 field is still set to eth0 on vm1, not eth0 on vm2 which is selected above)
4. user saves form, result is accepted. however interface assignment is still set to vm1 - eth0.

### Expected Behavior

I would expect that at step 2 once the device or vm relationship was changed that the interfaces field would empty out

OR

that during the save process data validation would fail and tell the user that the device / virtual machine assignment + interface are not part of the same device.

OR

maybe the interface assignment (eth0) should also have the vm or device name listed after it? making it obvious that the field above didnt change anything and is just a filter?

### Observed Behavior

assignment does not change in netbox. user gets no warning that there was a conflict or no change made

**Comment by a084ed22** [comment]
From experience, the device/virtual machine dropdowns are meant to be only filters for the respective interface field. Only the interface field matters in terms of association with the IP, therefore just changing the virtual machine won't result in any change to the association.

**Comment by kkthxbye-code** [comment]
This is a common issue with fields that filter other fields. The obvious solution would be to clear dependent fields after updating the parent. Not sure if there are any usability issues to consider though.

Code for the API select fields can be found here if anyone wants to give it a shot:

https://github.com/netbox-community/netbox/blob/develop/netbox/project-static/src/select/api/apiSelect.ts

**Comment by ITJamie** [comment]
Another (quicker) option would be to also show the name of the attached device/vm in brackets after the interface name. 

Eg right now it just shows "eth0" but it could show "eth0 (device1)" in the interface name field. It would at least make it slightly more obvious that the data didnt update when you change the field above

**Comment by PieterL75** [comment]
something  like this  

apiSelect.ts
add on line 604:
    // Remove the existing select option, as the parent changed, and the current selected options is not relevant to the new parent
    this.resetOptions()

This will remove the data of a child selection if the parent has changed value.

**Comment by ITJamie** [comment]
My worry about doing it for every parent child field is that in some cases the current logic is actually useful. 

Eg if your editing an interfaces vlan tags. I have several interfaces where there are vlans in multiple different vlan groups that need to be tagged on one interface. 

So with the change above if i changed the vlan group to find another vlan i need to tag on that interface, it would clear out the existing tagged vlans.

**Comment by PieterL75** [comment]
maybe, the element that is displayed in the list needs to show more information.
Currently you only see the value of the listiems (ex eth1, eth1, eth2, eth2, ...)

What if the list is dependent on another list, then show that too.
VM1/Eth1
VM2/Eth2
VM1/Eth1
VM2/Eth2.

Then the current logic can remain, but the confusion on what the relation of the Eth1 is to the parent is more clear

**Comment by jeremystretch** [comment]
@DanSheps why did you mark this as blocked?

**Comment by DanSheps** [comment]
No idea, might have been by accident

**Comment by DanSheps** [comment]
There is an identical one however that would be fixed by moving to the new filtering logic.  I am willing to take both of those

**Comment by jeremystretch** [comment]
What is the other issue? Can we consolidate them?

**Comment by DanSheps** [comment]
Pretty sure you just closed it out:  #11477

If we move to the new filtering mechanism, it would remove the "device assignment" all together, and make it clear that you can only assign an ip address to a interface.

**Comment by ITJamie** [comment]
the new filtering mechanism should solve this right? https://twitter.com/jstretch85/status/1631677080252424192?s=20

**Comment by DanSheps** [comment]
Yeah, it should solve it.  Would solve the other one too
