### ISSUE TITLE
For selection type custom fields, allow a single option

### ISSUE THREAD

**Issue by decoupca** [netbox-community/netbox#10762]
### NetBox version

v3.3.6

### Feature type

Change to existing functionality

### Proposed functionality

When creating a selection custom field, allow a single option. Currently, selection type custom fields require at least two available options.

### Use case

Some scenarios restrict acceptable value to a few choices (not freeform text), but for which there is, at least currently, only one viable option.

For example, I want to assign a named SNMPv3 credential set to devices which I model as a custom field called `snmpv3_ro_cred_name`. I want to eliminate any possibility of invalid input, so I prefer a selection field over text. But as we only have one valid SNMPv3 credential set defined, I can't use selection field type, which requires at minimum two available options.

### Database changes

None

### External dependencies

None

**Comment by proudbro** [comment]
Why don't you use boolean type of cf?

**Comment by decoupca** [comment]
> Why don't you use boolean type of cf?

because eventually this cf will have multiple choices, just at this point it only has one.
