### ISSUE TITLE
Support pagination for available IPs endpoints

### ISSUE THREAD

**Issue by ajm5774** [netbox-community/netbox#10777]
### NetBox version

v3.3.6

### Feature type

New functionality

### Proposed functionality

I would like to specify an "offset" in the prefix available-ips endpoint query string parameters. Currently there is the capability to add "limit" to the query string parameters which defaults to 50, but "offset" is ignored.

Example:
https://demo.netbox.dev/api/ipam/prefixes/96/available-ips/?limit=1&offset=5

### Use case

List out all available IP addresses for a prefix.

For our case in particular, we are using this to calculate the percent utilization for a prefix. We alert on prefixes that are over-utilized so that we can take action before running out of available IPs.

**Comment by SignalR-Dev** [comment]
Just 1 Up for the Issue , 
Foolish work arround in the mean time (not preferable sollution)
As the API still Honors the Pagination value Global set a setting of
`PAGINATE_COUNT: "510"`
gives you the result. (at least up to a /23 Netmask)
Downside the UI Reflects this Value in Defrault Tables as well + there is noc way to tell .next if the Prefix is bigger

**Comment by jeremystretch** [comment]
> For our case in particular, we are using this to calculate the percent utilization for a prefix

This specific use case should be covered by #9649.

**Comment by jeremystretch** [comment]
Marking this as blocked by #12180.
