### ISSUE TITLE
Installation instructions for CentOS should be updated

### ISSUE THREAD

**Issue by joubbi** [netbox-community/netbox#10771]
### Change Type

Correction

### Area

Installation/upgrade

### Proposed Changes

I reported this some time ago:
https://github.com/netbox-community/netbox/issues/8354

I created a pull request:
https://github.com/netbox-community/netbox/pull/10767

1. The documentation has the header CentOS. I think RHEL makes more sense.
2. The documentation is missing the steps needed to upgrade Python.
3. There is a missing step for installing LDAP on RHEL based distros. I could update the documentation with this as well, if you want.

**Comment by jeremystretch** [comment]
> The documentation has the header CentOS. I think RHEL makes more sense.

The documentation is written for CentOS, not RHEL.

> The documentation is missing the steps needed to upgrade Python.

This process is not unique to NetBox and thus outside the scope of our documentation.

> There is a missing step for installing LDAP on RHEL based distros.

Again, our documentation is limited to Ubuntu and CentOS. You can find instructions for both under the [LDAP configuration docs](https://docs.netbox.dev/en/stable/installation/6-ldap/).
