### ISSUE TITLE
Prevent duplicate IPs unless they have 'Anycast' role.

### ISSUE THREAD

**Issue by mkurjanski** [netbox-community/netbox#10775]
### NetBox version

v3.3.5

### Feature type

New functionality

### Proposed functionality

The ENFORCE_GLOBAL_UNIQUE flag turned to True blocks any duplicate Prefixes and IPs within the same VRF.
The caveat of ENFORCE_GLOBAL_UNIQUE is it also blocks any duplicate IPs even if they have the 'Anycast' role set.

It would be great to be able to have a setting that blocks duplicate IPs unless they're of the 'Anycast' role.
This could be achieved by modifying the behaviour of ENFORCE_GLOBAL_UNIQUE or adding a new configuration flag.

### Use case

Netbox would prevent duplicate prefixes and IP addresses in most cases but allowing duplicate IPs in the 'anycast' scenario.

**Comment by jeremystretch** [comment]
> The caveat of ENFORCE_GLOBAL_UNIQUE is it also blocks any duplicate IPs even if they have the 'Anycast' role set.

IP addresses with a role of anycast are already excluded from the enforcement of `ENFORCE_GLOBAL_UNIQUE`. You can verify this by setting `ENFORCE_GLOBAL_UNIQUE = True` in `configuration.py` and creating multiple IPs with the same address and a role of anycast in the global table.
