### ISSUE TITLE
"Kind" column is invisible on the Journal page for a Device

### ISSUE THREAD

**Issue by jeffmacdonald** [netbox-community/netbox#10786]
### NetBox version

3.3.4

### Python version

3.8

### Steps to Reproduce

1. Go to a Device
2. Go to Journal
3. Create a joural entry
4. See the "Kind" column text is white on white background.

### Expected Behavior

Kind text should have black text.

### Observed Behavior

Kind text has white text on white background.

**Comment by arthanson** [comment]
I wonder if this is possibly configuration on your setup.  I tried the steps above but am not seeing the white text.  I tried looking on the list view, detail view and under Journal entries and it all appears as shown below.  Can you provide a screenshot of what you are seeing?
![kind](https://user-images.githubusercontent.com/99642/198672849-cb4338e1-746d-44e2-9ce0-ddb5d6ce0b00.png)

**Comment by jeffmacdonald** [comment]
It could be. Here is a screen shot as well as my "Kinds" Configuration.
![Screen Shot 2022-10-28 at 12 37 11 PM](https://user-images.githubusercontent.com/2640973/198677428-d93f20ed-ea0d-48ad-b68f-e440478011c7.png)

```
# Configure Field choices for Journal "kinds"
FIELD_CHOICES = {
    'extras.journal-entries.kind': (
        ('broken', 'Broken', 'Red'),
        ('repaired', 'Repaired', 'Green'),
        ('repair-logs', 'Repair-logs', 'Blue'),
        ('intentionally-off', 'Intentionally Off', 'Yellow'),
    )
}
```

**Comment by kkthxbye-code** [comment]
As the documentations specifies, the color names are lower case.

https://docs.netbox.dev/en/stable/configuration/data-validation/#field_choices
