### ISSUE TITLE
Don't hide locations parent when searching

### ISSUE THREAD

**Issue by JoeIzzard** [netbox-community/netbox#10785]
### NetBox version

3.2.1

### Feature type

Change to existing functionality

### Proposed functionality

When searching the location field for example when adding a new rack, the parent locations should still be shown as multiple child locations can exist with different parents and the same name. For example, we have three venues with the same child locations, such as control room. When I add a rack to this location I have to go through the list as searching control room results in three results with no way to tell which is which.

### Use case

For sites with multiple locations that have the same name. For example we have:

- Venue 1-3
-  -> Control Room
-  -> Dimmer Room
-  -> Grid
-  -> Sound Control Room
-  -> DSM Control Room

When I search Control Room I currently get:
```
- Control Room
- Control Room
- Control Room
```

It would be ideal if instead we could have:
```
- Venue 1
-  -> Control Room
- Venue 2
-  -> Control Room
- Venue 3
-  -> Control Room
```

### Database changes

None

### External dependencies

None

**Comment by jeremystretch** [comment]
When you search for items in a dropdown, the API is matching on individual objects only. The behavior you're describing I'm afraid isn't possible without completely overhauling the filter backend. However, you can easily navigate by parent object instead.
