### ISSUE TITLE
Ability to filter Journals by location

### ISSUE THREAD

**Issue by jeffmacdonald** [netbox-community/netbox#10783]
### NetBox version

v3.3.4

### Feature type

Change to existing functionality

### Proposed functionality

I'd like to be able to filter journals by location. 

### Use case

We have 10 data centers globally. When techs arrive at one, they'd like to be able to pull a report of all machines that have a certain type and tag on their journals, but for that location specifically.

### Database changes

I don't think any new fields would be necessary.

### External dependencies

I don't think any are needed. It's just a new filter field.

**Comment by jeremystretch** [comment]
Journal entries can be attached to many different object types, most of which have no relationship to a location. I'm not sure it's possible to filter across a GenericForeignKey relationship in this manner.

**Comment by jeremystretch** [comment]
Closing this as it doesn't appear to be feasible.
