### ISSUE TITLE
Descending units fail to support half-height devices

### ISSUE THREAD

**Issue by jbakklund** [netbox-community/netbox#10795]
### NetBox version

v3.3.6

### Python version

3.9

### Steps to Reproduce

1. Create a rack with descending units, where the units are numbered top-to-bottom.
2. Add a device consuming the upper half of a rack position.
3. Try to add a half-height device in the bottom half of the same position.
 
![Add 0 5U device in position U2](https://user-images.githubusercontent.com/33431806/198998638-53997e79-cee1-4a76-81de-996ead137b29.png)

### Expected Behavior

The half-height device should be allowed to consume the available rackspace between 1.5 and 2.0 in the same way as for a normal rack where units are numbered in ascending order as illustrated below, where a half-height device were allowed to consume rackspace between 41 and 41.5

![Added 0 5U device in position U41](https://user-images.githubusercontent.com/33431806/198998666-af5d6ad7-f75b-4130-8eb0-fbd92f9dc5a8.png)

### Observed Behavior

![Observed behavior](https://user-images.githubusercontent.com/33431806/198986955-fb6a82df-f443-4460-bda5-d77ec00a9f87.png)

**Comment by jeremystretch** [comment]
As the error message indicates, the U2 position is occupied by the 1.5U device. You need to assign the second device (which is 0.5U high) to the U2.5 position:

![Screenshot 2022-11-01 at 15-32-30 Rack R1 NetBox](https://user-images.githubusercontent.com/13487278/199322285-755d8fb0-577f-4532-857e-cbb4e0a33ab3.png)

**Comment by jbakklund** [comment]
Ah, sorry! My brain didn’t handle the wraparound to consider that the anchor point at the lowest number is now actually at the uppermost edge of the new device.

I should rather file a new feature request then; suggesting to modify the ‘add device’ link in the rack elevation diagram to use the next available position within the unit, instead of integers – to something like: https://netbox.marlink.com/dcim/devices/add/?site=1&location=35&rack=90&face=front&position=2.5

Best regards,
Jostein Bakklund
