### ISSUE TITLE
Add Azure AD SSO Setup Instructions

### ISSUE THREAD

**Issue by szollin** [netbox-community/netbox#10800]
### Change Type

Addition

### Area

Installation/upgrade

### Proposed Changes

Currently, the documentation has a section for enabling LDAP authentication as an optional configuration method. Based on what I see in previous Discussions, PRs, and Issues, it would be helpful to have an extra optional configuration section for setting up SSO with Azure AD.

**Comment by jeremystretch** [comment]
Such documentation [already exists](https://docs.netbox.dev/en/stable/administration/authentication/microsoft-azure-ad/).
