### ISSUE TITLE
Deleting all Device/VM interfaces should redirect to details page

### ISSUE THREAD

**Issue by hagbarddenstore** [netbox-community/netbox#10808]
### NetBox version

v3.3.6

### Python version

3.10

### Steps to Reproduce

1. Create any Device/Virtual Machine
2. Add one or more interfaces
3. Go to the Device/Virtual Machine Interfaces tab
4. Select all interfaces and click the bulk Delete button

### Expected Behavior

I expected to be redirected to the details page since there are no interfaces to display and the Interfaces tab is hidden.

### Observed Behavior

Interfaces page is displayed with 0 interfaces, no Interfaces tab for Virtual Machines, Interfaces tab visible for Device.

**Comment by jeremystretch** [comment]
IMO this is desired behavior: The user is consistently redirected to the previous view regardless of the action taken.

**Comment by hagbarddenstore** [comment]
I agree, consistency is important.Perhaps we should force the tab to be visible if you’re on the interfaces tab/view.Right now it’s a bit confusing because there’s no tab showing you which tab you’re on.On 1 Nov 2022, at 20:38, Jeremy Stretch ***@***.***> wrote:﻿
IMO this is desired behavior: The user is consistently redirected to the previous view regardless of the action taken.
