### ISSUE TITLE
systemctl enable --now 

### ISSUE THREAD

**Issue by PenelopeFudd** [netbox-community/netbox#10807]
### Change Type

Addition

### Area

Installation/upgrade

### Proposed Changes

On https://docs.netbox.dev/en/stable/installation/4-gunicorn/ , the commands
```
sudo systemctl start netbox netbox-rq
sudo systemctl enable netbox netbox-rq
```
Could be simplified to
```
sudo systemctl enable --now netbox netbox-rq
```

**Comment by DanSheps** [comment]
Not every version of Linux supports the now flag, notibly a large number of CentOS 7 boxes (it is EoL I believe but it is still very much out there).

I think we can add it as a option, but I think preserving the current functionality makes more sense currently.

Important caveat with this:

> The start or stop operation is only carried out when the respective enable or disable operation has been successful.

**Comment by PenelopeFudd** [comment]
Huh.  TIL!   :-)

I'm having difficulty thinking of a situation where it's not possible to enable/disable yet it is possible to start/stop.  Would that be if it's already been enabled/disabled (e.g. "you can't disable that, it's already disabled", or maybe if the service file has been deleted?  In those cases, I'm not sure how systemd would know how to start or stop the service, the required definitions have been deleted from memory.  Or at least, that's how I'm imagining it, I haven't tested it.

The more I read the installation instructions, the more I like them; they're solid.  In fact, they're good enough that they could be turned into an interactive shell script without much difficulty.  Initially, anyway.  :-)
