### ISSUE TITLE
Allow disabling password login

### ISSUE THREAD

**Issue by supertassu** [netbox-community/netbox#10827]
### NetBox version

v3.3.7

### Feature type

Change to existing functionality

### Proposed functionality

When using SSO for authentication, it should be possible to disable the default password based authentication.

### Use case

The login page will no longer have options that are not being used.

### Database changes

no

### External dependencies

no

**Comment by jeremystretch** [comment]
> When using SSO for authentication, it should be possible to disable the default password based authentication.

Local authentication is always enabled to ensure administrative access remains available in the event of an SSO provider outage or compromise. If this does not meet your needs, you have the option of disabling all local accounts.
