### ISSUE TITLE
Add support for delegating rack/patching request

### ISSUE THREAD

**Issue by kifeo** [netbox-community/netbox#10836]
### NetBox version

v3.3.7

### Feature type

New functionality

### Proposed functionality

add support for requesting a new / change / removal of racking of a device or patching cables from devies to another team.

### Use case

Now that remote work is getting more and more accepted, this would add the possibility to the product to add the request to another team to handle the datacenter physical management.

This would also allow a single team be able to handle the workflow of handling the racking and patching.

**Comment by jeremystretch** [comment]
Implementing a change control process is out of scope for NetBox core, but could work very well as a plugin.
