### ISSUE TITLE
Audit to add gettext to strings to support internationalization

### ISSUE THREAD

**Issue by arthanson** [netbox-community/netbox#10833]
### Proposed Changes

Previous PR added in gettext around help_text and labels, further work would be needed to actually support translation:

1. There are some strings encased in tripe-quotes or f-strings that aren't converted as they require more work and the f-strings especially need to be tested individually.
2. ValidationError( strings have not been converted (quite a few are f-strings).
3. Model verbose names and method decorators

### Justification

Would allow NetBox to support translation into other languages.

**Comment by jeremystretch** [comment]
This ended up getting broken into multiple other issues due to the scope of work involved.
