### ISSUE TITLE
class 'jwt.exceptions.ImmatureSignatureError'

### ISSUE THREAD

**Issue by crato-ctl** [netbox-community/netbox#10844]
### NetBox version

3.3.5

### Python version

3.8

### Steps to Reproduce

![image](https://user-images.githubusercontent.com/74680992/200017235-d40d20a3-e6f6-4295-9007-7ec04bf3e936.png)

### Expected Behavior

![Sin título](https://user-images.githubusercontent.com/74680992/200017110-0a3b36ff-ce76-4aa8-82d5-7f88e80f1ff1.png)

### Observed Behavior

I m ussing SSO, when i try to connect I observe 
![image](https://user-images.githubusercontent.com/74680992/200016948-642f07b5-21a9-4344-b28d-dbacf9416610.png)

**Comment by jeremystretch** [comment]
See discussion #10846
