### ISSUE TITLE
Strange behavior when changing the parent location with [Bulk Edit]

### ISSUE THREAD

**Issue by mscpik** [netbox-community/netbox#10875]
### NetBox version

v3.3.8 (fresh installation)

### Python version

3.10

### Steps to Reproduce

I create locations in a hierarchical order with 3 layers.

Layer 1: buildings
> Layer 2: floors
> > Layer 3: rooms

like this
![image](https://user-images.githubusercontent.com/114069964/202457015-d8b18b28-998c-4c85-97bc-5f72ee178e9c.png)

I created child locations(rooms) with "Add Child Location" button and some of them on the wrong floor.
![image](https://user-images.githubusercontent.com/114069964/202458444-8a3c8963-9de7-4048-8bcd-0e70bb0e91d4.png)

To correct this I edit (single edit) the location with the wrong floor and change the parent of this location object to the right one.
Here for locations "building A_room 0.01" and "building A_room 0.02" to change the parent to "building A - ground" with no problems.
![image](https://user-images.githubusercontent.com/114069964/202505627-c347478d-c4b0-49b7-8c86-0102d8cd8a40.png)

But if I use "Bulk Edit" over the "Edit Selected" button(from a VM snapshot), here for locations "building A_room 0.01" and "building A_room 0.02", to change the parent to "building A - ground", I get this as result.
The hierarchical order of this locations is destroyed/mixed up. 
![image](https://user-images.githubusercontent.com/114069964/202498980-19d2e53e-a42f-4e8a-b08c-37ff58d60256.png)
location "building A - ground"
![image](https://user-images.githubusercontent.com/114069964/202500688-9e42cf88-2460-44e2-9996-50ce1e40185a.png)
location "building A - room 0.01"
![image](https://user-images.githubusercontent.com/114069964/202502241-1a58f279-0044-43e1-ab64-ba8d8cb1f80f.png)

### Expected Behavior

Move all selected locations with "bulk edit" to the correct parent location.

### Observed Behavior

Rooms seems to be in more than one parent location and some location objects not moveable/editable any more, even if want to remove(Set Null) the parent in the location object, independent of the edit mode I used.
In some situations I also get an server error if I want to remove a parent of  a location.
Like this location object
![image](https://user-images.githubusercontent.com/114069964/202561176-4b9ba5ca-c888-4d79-9f27-079b17bbcaef.png)
In edit location I removed the parent location and get this error message.
![image](https://user-images.githubusercontent.com/114069964/202559494-e83f6604-d327-4ea4-9f87-d5d320e61c1e.png)
Complete error message:

> <class 'django.db.utils.IntegrityError'>
> 
> new row for relation "dcim_location" violates check constraint "dcim_location_level_check"
> DETAIL:  Failing row contains (2022-11-17 14:15:01.236855+00, 2022-11-17 14:15:01.236905+00, {}, 30, building A - ground, building-a-ground, , 2, 23, 2, -1, 27, 1, null, active).
> 
> 
> Python version: 3.10.6
> NetBox version: 3.3.8

**Comment by mscpik** [comment]
I have edited the original bug report and am using a fresh install of https://github.com/netbox-community/netbox-docker to test.
It is very hard to reproduce the error and in my opinion it has to do with [Bulk Edit] of locations.
With direct editing/changing the parent of a location where seems to be no problems.

**Comment by mscpik** [comment]
In search of a solution to repair my productive database I found this an older closed bug report:
 "Misassignment of Locations parents" #9196
 
The method to rebuild location objects from nbshell worked to correct the parent child relations between the locations.

**Comment by arthanson** [comment]
Potentially dependent on #6587

**Comment by mscpik** [comment]
> Potentially dependent on #6587
You might be right
A description how [MPTT tree](https://django-mptt.readthedocs.io/en/latest/index.html) works on https://github.com/netbox-community/netbox/discussions/8987#discussioncomment-2461021
