### ISSUE TITLE
Contact Roles link to Assignments leads to wrong view

### ISSUE THREAD

**Issue by v0tti** [netbox-community/netbox#10874]
### NetBox version

v3.3.7

### Python version

3.9

### Steps to Reproduce

1. Create Contact Role "Foo"
2. Create Contact "Bar"
3. Create Site "Baz"
4. Assign Contact "Foo" to Site "Baz" as Contact Role "Bar"
5. Open Contact Role "Bar", click on the number next to "Assignments".

### Expected Behavior

I expect to see the assignments of Contacts using this Contact Role.

### Observed Behavior

The link leads to `/tenancy/contacts/?role=bar` which is a filter option that does not exist.

**Comment by arthanson** [comment]
@v0tti I think step 4 is off, you have Contact Role "Bar" but your contact Role in step 1 in "Foo".  I tried the steps as:
4. Assign Contact "Bar" to site "Baz" as Contact Role "Foo" The filter option does exist but I am seeing some possible wrong results which I'm checking. But can you please double check if those are the right repro steps?

**Comment by jeremystretch** [comment]
Seems like the issue is just that there's no view for a contact assignments list, so the count shouldn't be a link, which #10879 addresses.
