### ISSUE TITLE
Contact can not be assigned to Contact Role

### ISSUE THREAD

**Issue by v0tti** [netbox-community/netbox#10873]
### NetBox version

v3.3.2

### Python version

3.9

### Steps to Reproduce

1. Create a new Contact Role "Foo"
2. Create a new Contact "Bar" and try to assign it to the Contact Role "Foo"

### Expected Behavior

I expect to be able to assign the Contact "Bar" to the Contact Role "Foo".

### Observed Behavior

There is no field to assign a Contact to a Contact Role.
This is consistent with documentation where no assignment field for Contact Roles is mentioned, however I don't think Contact Roles can be used in any other way. In my understanding Contact Roles should behave like Contact Groups.

**Comment by jeremystretch** [comment]
Contacts are assigned a role when attached to an object, not individually. For example, a person might be an administrative contact for one site but a billing contact for another.

**Comment by v0tti** [comment]
Well that's not very clear from documentation than. Maybe it can be improved.
Additionally, Contact Roles have a link to "Assignments" which link to `/tenancy/contacts/?role=<role>`. That does not seem to be correct if I understand you correctly. Should I open another issue?

**Comment by jeremystretch** [comment]
The link appears to be wrong, yes. You're welcome to open a separate bug report for that. Thanks!
