### ISSUE TITLE
Upgrade instructions fail to mention creating /opt/netbox/logs 

### ISSUE THREAD

**Issue by PenelopeFudd** [netbox-community/netbox#10880]
### Change Type

Correction

### Area

Installation/upgrade

### Proposed Changes

On the page https://docs.netbox.dev/en/stable/installation/upgrading/#5-restart-the-netbox-services , it should have a step "4.5" that says:

> Create a new log directory:
```
sudo install -o netbox -g netbox -m 755 -d /opt/netbox/logs
```

Or you could move or copy the old log directory, YMMV.

**If this is not done, step 5 will cause netbox to break!**
Error message: 

> Server Error
> 
> There was a problem with your request. Please contact an administrator.
> 
> The complete exception is provided below:
> 
> <class 'FileNotFoundError'>
> 
> [Errno 2] No such file or directory: '/opt/netbox/logs/django-ldap-debug.log'
> 
> Python version: 3.8.10
> NetBox version: 3.3.7
> 
> If further assistance is required, please post to the [NetBox discussion forum](https://github.com/netbox-community/netbox/discussions) on GitHub.

**Comment by PenelopeFudd** [comment]
Alternative code: 
```
sudo mkdir /opt/netbox/logs
sudo chown netbox:netbox /opt/netbox/logs
sudo chmod 755 /opt/netbox/logs
```

**Comment by PieterL75** [comment]
Better place for the logs is
/opt/netbox/netbox/local/logs/
That folder is excluded from git.

**Comment by PenelopeFudd** [comment]
Just remembered that git doesn't work with directories, only files.  If we want it to create a log directory, we have to put a placeholder file in it.  

After that, we can add (e.g.) `logs/*.log` in `.gitignore`, and have the best of both worlds: git will auto-create the log directory and won't accidentally commit log files.

**Comment by PenelopeFudd** [comment]
What would the next step be?

**Comment by jeremystretch** [comment]
Nothing should be logging to `/opt/netbox/logs`; there is no action to take here. You may want to evaluate your `django-auth-ldap` configuration. Please consider starting a [discussion](https://github.com/netbox-community/netbox/discussions/new/choose) if you need further assistance.
