### ISSUE TITLE
Missing widgets in FHRPGroupForm

### ISSUE THREAD

**Issue by miaow2** [netbox-community/netbox#10897]
### NetBox version

v3.3.7

### Python version

3.10

### Steps to Reproduce

1. Open `add` or `edit` form for FHRPGroup
2. fields `Protocol`, `Authentication type`, `Status` are missing `StaticSelect` widget

### Expected Behavior

 Fields `Protocol`, `Authentication type`, `Status` should use `StaticSelect` widget

### Observed Behavior

You can assign this issue to me and I will create a pull request

**Comment by jeremystretch** [comment]
Thanks for calling attention to this!
