### ISSUE TITLE
Render Specified Front and Rear Port Colors During Cable Trace 

### ISSUE THREAD

**Issue by TheZackCodec** [netbox-community/netbox#10904]
### NetBox version

v3.3.7

### Feature type

Change to existing functionality

### Proposed functionality

Currently it is possible to specify colors for Front and Rear Ports. However, when running a cable trace, the port colors are not reflected in the rendered SVG.  Cable colors can be specified and are already rendered during cable traces, it only makes sense that the same logic should apply for the Front and Rear Ports. Additionally, when no color is specified, the port color should revert to the current default. 

## Current Functionality
![Current Functionality Netbox](https://user-images.githubusercontent.com/31785616/201547734-59d5c121-0f96-4e1c-a880-d44082291507.png)

## Proposed Functionality
![Proposed Functionality Netbox](https://user-images.githubusercontent.com/31785616/201547772-8e37eef6-e21e-485b-a5a1-12ba65120920.png)

### Use case

Sometimes specific patch panel ports and/or network drop keystone colors are used to help identify specific traces in the real world. Adding this functionality would not only be simple but would further help users visualize and identify traces.

### Database changes

None

### External dependencies

None

**Comment by TheZackCodec** [comment]
@dvigne

**Comment by TheZackCodec** [comment]
Thank @dvigne

**Comment by dvigne** [comment]
@jeremystretch much appreciated. Thank you.
