### ISSUE TITLE
Endpoint wrong if bridged device in cable path

### ISSUE THREAD

**Issue by lagrip** [netbox-community/netbox#10912]
### NetBox version

v.3.3.7

### Python version

3.10

### Steps to Reproduce

1. Create the following devices: Switch, Patchpanel with Front- and Rear-Ports, PoE Injector, Access Point
2. Set both Ports of PoE Injector in bridged mode
3. Connect the devices as show below

```
[ switch]                [ Patchpanel ]                       [ PoE Inj ]                  [ AP]
 [ iface ] ------- [ front]         [ rear] ----------- [ iface ]  [ iface ] ------- [ iface ]
            cable1                            cable2       |             |    cable3
                                                            +-- bridge --+
```

### Expected Behavior

On the interface tab of the switch the interface should show the endpoint on the 'connection' row. In this case the access point.

### Observed Behavior

On the 'connection' row it shows the next component. In this case the PoE Injector. This is OK for the "Link Peers" but not for the endpoint.
By the way: The cable trace works fine. It shows all components and cable from the switch to the AP. Thus, the information is available, but on the interface tab it shows a wrong device.

**Comment by jeremystretch** [comment]
This is working as intended. An interface always represents the end of a cable path. When tracing a cable, NetBox will follow a bridged relationship from the end of one cable path to the beginning of _another_ cable path for convenience, but these are still two separate paths. An interface will only ever show the far end of its directly connected cable path for various reasons, mostly relating to performance and validation.

(If you want to show the end-to-end path, I'd suggest changing the PoE injector terminations to front & rear ports.)
