### ISSUE TITLE
Better modelling of datacentre crossconnects

### ISSUE THREAD

**Issue by b66renr** [netbox-community/netbox#10917]
### NetBox version

v3.3.7

### Feature type

New functionality

### Proposed functionality

Hello! This is written with the view of a service provider with network devices in third party datacentres, but I think applies to own datacentres reasonably well too. Forgive me if I've missed a simple way to address this!

Use case: Crossconnects purchased from a datacenter provider, e.g Equinix, between two racks. Generally presented on a patch panel, but sometimes on a hanging fibre lead in the rack (ahem, Telehouse).

I've started modelling these crossconnects as Circuits, so that they have a provider, a reference, can have contacts assigned to the provider, and because the routing of the cable and segments within it are somewhat unknown/uninteresting from this level of modelling. Downsides of using cables being the opposite of this, so no supplier/reference/etc.

However the downsides of using Circuits is that I'm having to run additional cables in Netbox, so the topology should look like:

Router <cable> Front Port - Datacentre Patch Panel - Rear Port - Crossconnect - Rear Port - Datacentre Patch Panel - Front Port <cable> Router.
2 cables, one at each end from the patch panels to the router, with the crossconnect directly between the rear ports of the patch panels in each rack.

However it ends up looking like:
Router <cable> Front Port - Datacentre Patch Panel - Rear Port <cable> Circuit termination A - crossconnect "circuit" - Circuit termination B <cable> Rear Port - Datacentre Patch Panel - Front Port <cable> Router.

Which means creating 4 cables, one at each end from the patch panels to the router, and an additional 2 from the rear port of the patch panel, to the "Circuit Termination".

It would be great to have, for example an additional section under the "Circuits" dropdown for Crossconnects, where the circuit would function more like a cable, allowing it to be directly plugged to ports. Being able to plug it directly into both patch panel rear ports, and interfaces, would account for both datacenters that present on patch panels, and those that leave a hanging cable in the rack.

Ideally, these crossconnects would also be able to span sites like circuits do, due to you often being able to purchase a crossconnect between different sites in the same datacentre campus/metro area.

Thanks!

### Use case

Currently (unless I'm missing a better way of doing this), datacentre crossconnects seem to fit into an awkward gap between cables and circuits. Hoping to address that with the above information.

### Database changes

New model, much alike a circuit?

**Comment by jeremystretch** [comment]
> It would be great to have, for example an additional section under the "Circuits" dropdown for Crossconnects, where the circuit would function more like a cable, allowing it to be directly plugged to ports. Being able to plug it directly into both patch panel rear ports, and interfaces, would account for both datacenters that present on patch panels, and those that leave a hanging cable in the rack.

This option already exists: You can terminate a circuit directly to the device interface, bypassing the patch panel entirely (but perhaps annotating it in the circuit's comments). Which approach is best is left to the determination of the user. But ultimately the line of demarcation must be drawn somewhere.
