### ISSUE TITLE
Allow config contexts to append to existing values

### ISSUE THREAD

**Issue by WhaleJ84** [netbox-community/netbox#10916]
### NetBox version

v3.3.7

### Feature type

Change to existing functionality

### Proposed functionality

I'm proposing some way for users to append to existing values in configuration contexts rather than just overwriting. An example of current and desired behavior is explained in the Use Case section below.

### Use case

Currently, if I create two tags `["Service-HTTP", "Service-HTTPS"]` with the intent of applying these tags to a device that has two services `[{"name": "HTTP", "ports": [80]}, {"name": "HTTPS", "ports": [443]}]`, with the config-contexts: 
```
[
    {
        "name": "Service-HTTP-config",
        "weight": 1000,
        "data": {
            {"ports:" [80]}
        }
    },
    {
        "name": "Service-HTTPS-config",
        "weight": 1000,
        "data": {
            {"ports:" [443]}
        }
    }
]
```
then the device's config-context would only render `{"ports": [80]}`. Likewise, changing with *Service-HTTPS-config* context weightings would overwrite the config and be `{"ports": [443]}`.

However, in this example, I want to dynamically render the planned open ports on the device so the firewall can be automatically configured from the context `{"ports": [80, 443]}`. I've looked at the documentation but did not notice a way to append to existing values - only overwrite.

**Comment by jeremystretch** [comment]
> I'm proposing some way for users to append to existing values in configuration contexts rather than just overwriting.

What is the specific implementation you're proposing?

**Comment by WhaleJ84** [comment]
Possibly with a new checkbox on the creation screen to determine whether the context is weightless? If checked, then whatever value is entered in the mandatory 'Weight' field is ignored and other weightless contexts with the same data keys have their values merged in situations where possible (e.g. lists, dicts.).

I mocked up the image below to show it, but I have no experience with Django, so cannot say how it could be implemented into the code.
![image](https://user-images.githubusercontent.com/43613409/210837561-32d9aef9-9d40-42a1-aeff-b3b1a1679ad5.png)

In my mind, the logic would be: *if contexts are weightless AND data keys are matching* (in this example "ports"), *then merge values*.
Would that work?

**Comment by WhaleJ84** [comment]
Thinking of a more complex scenario, I think weightless contexts should be used as a base - take the following contexts:
**Service-HTTP** (weightless)
`{"ports": [80], "applications": {"web-server": "nginx"}}`

**Service-HTTPS** (weightless)
`{"ports": [443], "applications": {"web-server": "nginx", "ssl-certificates": "letsencrypt"}}`

**Application-Web-Server** (weight 1000)
`{"applications": {"web-server": "apache"}}`

As the two services are weightless, they get added to the context regardless, but the application context has weight, so that would take priority and overwrite the corresponding key to make this:

```json
{
    "ports": [80, 443],
    "applications": {
        "web-server": "apache",
        "ssl-certificates": "letsencrypt"
    }
}
```

By having some way to append as well as overwriting values, this could allow for some really creative contexts to be made and used in things like Ansible to dynamically provision devices.
