### ISSUE TITLE
Search doesn't search Overlays/L2VPNs

### ISSUE THREAD

**Issue by jaannnis** [netbox-community/netbox#10928]
### NetBox version

v3.3.7

### Feature type

Change to existing functionality

### Proposed functionality

Currently L2VPNs/Overlays are not searched in the global search. Is there a reason as to why?
If not the proposed functionality would be to be able to search and filter the search on L2VPNs

### Use case

Finding L2VPNs and terminations

### Database changes

I don't think there are changes necessary.

### External dependencies

I don't think there are external dependencies necessary.

**Comment by abhi1693** [comment]
This is updated for v3.4 upcoming release: 

https://github.com/netbox-community/netbox/blob/feature/netbox/ipam/search.py#L59-L66

I'm not sure if this i=will be fixed for the current release though

**Comment by jaannnis** [comment]
Thanks, searched but didn't find!
