### ISSUE TITLE
Bulk update data type is incorrect in swagger spec

### ISSUE THREAD

**Issue by abhi1693** [netbox-community/netbox#10922]
### NetBox version

v3.3.7

### Python version

3.10

### Steps to Reproduce

As per the swagger doc, the bulk payload requires a dict
![image](https://user-images.githubusercontent.com/5083532/201976485-b0f1178f-66ec-487d-9fac-7c1ed3936804.png)

However, when trying to run the same, it throws an error

![image](https://user-images.githubusercontent.com/5083532/201976682-21121789-fe6e-49a8-bc3d-0576a8696c14.png)

The issue is seen for all models in the spec for PUT and PATCH using the bulk operations

### Expected Behavior

The spec should display that the required payload should be a List of items/dictionaries

### Observed Behavior

The spec displays it needs a dictionary

**Comment by jeremystretch** [comment]
Thanks @abhi1693!

**Comment by jeremystretch** [comment]
We discovered during review of PR #11481 that resolving this adequately will likely require a significant amount of further work. Given the upcoming release of NetBox v3.5, which replaces the current schema with OpenAPI 3.0 (see #9608), we're going to abandon this change.
