### ISSUE TITLE
Improve diff display of configuration context changelog entries

### ISSUE THREAD

**Issue by ggidofalvy-tc** [netbox-community/netbox#10924]
### NetBox version

v3.3.7

### Feature type

Change to existing functionality

### Proposed functionality

The proposed change would make the Changelog functionality intelligently display only the altered parts of the Configuration Context JSONs.

See below for an example, a single-line change to a Configuration Context.

![20221115_19h02m04s_grim](https://user-images.githubusercontent.com/69459847/201996691-633f6acf-1b9a-4d0c-8010-50c038bc0f05.png)

The side-by-side "Pre-Change Data" and "Post-Change Data" section of the page could be used by NetBox users to compare two versions of the configuration context JSON by only highlighting the changed lines. A mockup of this can be seen below.

![20221115_19h06m48s_grim](https://user-images.githubusercontent.com/69459847/201995094-acfd3bfd-d9cd-4d08-814d-fca1a4649331.png)

The "Difference" section, at least when it comes to separate Configuration Contexts, is not very useful at the moment. See below for an example.

![20221115_19h07m31s_grim](https://user-images.githubusercontent.com/69459847/201995644-ff0abdd8-912d-4dba-95ff-b8c518c38f60.png)

If one were to make changes to the Changelog item page specifically for Configuration Contexts to implement this improvement, doing away with the "Differences" field and integrating the "Previous/Next" toggles to the side-by-side comparison would also probably make more sense.

### Use case

At the moment, an external application is required to figure out the differences between Configuration Contexts, and the current NetBox UI does not allow for easy tracking of changes made to Configuration Contexts. This is especially evident when handling multiple Configuration Contexts.

The same issue occurs when handling Local Configuration Contexts. If the improvements made to the Configuration Context Changelog pages can be extended to Changelog entries that involve the Local Configuration Context, that would be quite helpful in tracking changes made to these as well.

**Comment by jeremystretch** [comment]
I've done a bit of work in 83679ecb8 to optimize `shallow_compare_dict()`, however we'll need to devise a solution for processing nested values.

**Comment by ggidofalvy-tc** [comment]
@jeremystretch have you folks made any progress in regards to this issue? Thanks!
