### ISSUE TITLE
Link in the Netbox upgrade documentation is wrong

### ISSUE THREAD

**Issue by F3d0s** [netbox-community/netbox#10934]
### NetBox version

v3.3.7

### Python version

3.8

### Steps to Reproduce

Wrong command in the documentation

### Expected Behavior

wget command should work as expected

### Observed Behavior

I noticed that the `wget` command used to download the netbox release, documented in [Upgrading Netbox documentation](https://docs.netbox.dev/en/stable/installation/upgrading/#:~:text=wget%20https%3A//github.com/netbox%2Dcommunity/netbox/archive/vX.Y.Z.tar.gz) is wrong, it should be `https://github.com/netbox-community/netbox/archive/refs/tags/vX.Y.Z.tar.gz` instead of `https://github.com/netbox-community/netbox/archive/vX.Y.Z.tar.gz`, e.g. v3.3.7 can be downloaded at `https://github.com/netbox-community/netbox/archive/refs/tags/v3.3.7.tar.gz`.

**Comment by jeremystretch** [comment]
Thanks for the report!
