### ISSUE TITLE
Possibility to change device when module

### ISSUE THREAD

**Issue by dsl81** [netbox-community/netbox#10951]
### NetBox version

3.3.8

### Feature type

Change to existing functionality

### Proposed functionality

Return ability to change device when editing module

### Use case

Module can be moved between compatible bays on different devices. For example router line card or power supply can be inserted in any chassis but we cannot move it in netbox now. We can only change bays in one device. When editing module field "device" is disabled. Same as here  https://github.com/netbox-community/netbox/issues/10447 if we have to recreate modules we will loose history of valuable equipment.
![module](https://user-images.githubusercontent.com/3961842/202460988-88e8eed5-d0b1-46e2-8b2b-b4a2665c4ae0.png)

**Comment by kkthxbye-code** [comment]
Can you elaborate on what the intended functionality is here? Moving modules do not move the associated components, so when moving modules before the components would stay on the same device and reference a module on another device, which is obviously not valid. Are you expecting the module to be moved barebones and the original components having their module reference nulled? As there is no way to repopulate module components, it seems like a weird usecase unless you are using modules with no components.

**Comment by dsl81** [comment]
Moving a module should not move associated components. I expect that component reference to module shoud be removed. The component should remain on "old" device. Maybe option to remove associated components would be useful.
