### ISSUE TITLE
Primary IPv6 for VDC filters IPv4

### ISSUE THREAD

**Issue by abhi1693** [netbox-community/netbox#10950]
### NetBox version

v3.4-beta1

### Python version

3.10

### Steps to Reproduce

1. Click on Add on the VDC page
2. Choose `ncsu-coreswitch1` on the device drop-down
3. Click on Primary IPv6 dropdown

### Expected Behavior

Only IPv6 addresses should be displayed

### Observed Behavior

IPv4 addresses are displayed
![image](https://user-images.githubusercontent.com/5083532/202446333-c039a05c-3858-416f-b7e5-627fc6bda988.png)

**Comment by kkthxbye-code** [comment]
For context it's missing something equivalent to this logic (example for devices):

https://github.com/netbox-community/netbox/blob/ebf555e1fb1267348ca620c15ce456767d91042a/netbox/dcim/forms/model_forms.py#L614-L638

**Comment by DanSheps** [comment]
> For context it's missing something equivalent to this logic (example for devices):

I think we can get away with just simple filters on this one as I don't think we care about NAT since this would be for management.  TBH I am not sure why we care about nat_inside for regular devices either.
