### ISSUE TITLE
Create 0.0.0.0/0 as prefix.

### ISSUE THREAD

**Issue by romanlocal** [netbox-community/netbox#10968]
### NetBox version

v3.3.8

### Feature type

Change to existing functionality

### Proposed functionality

Create 0.0.0.0/0 as prefix.

### Use case

In our organization, we use the ZTP. In this ZTP we can deploy some 'prefixes' from Netbox (our S-o-T) to devices (for examle some static routes). But here's the problem, we can't deploy 0.0.0.0/0 because we can't create own. I read #6825 #6030. But there I meet the opinion that the prefix 0.0.0.0/0 should not be in principle. Ok, then why i can create 0.0.0.0/1 and 128.0.0.0.1? (Actually, for now, we use this case a such a crutch).

I guess this would be a useful feature, because I want to use netbox as base to generate some configs for ZTP.

**Comment by jeremystretch** [comment]
> But there I meet the opinion that the prefix 0.0.0.0/0 should not be in principle

Correct; this has not changed.

> Ok, then why i can create 0.0.0.0/1 and 128.0.0.0/1?

Because these each identify a specific portion of the available IP space, rather than all of it.
