### ISSUE TITLE
Improve wording of Link Peers in device interface table

### ISSUE THREAD

**Issue by clerie** [netbox-community/netbox#10967]
### NetBox version

v3.3.8

### Python version

3.9

### Steps to Reproduce

1. Create a device
2. Add an interface to the device
3. View interfaces tab
4. Configure table
5. Add "Link Peers" column

### Expected Behavior

I would expect the column showing me the next connection in my trace to be named with something containing connection. I.e. "Connection Peer".

### Observed Behavior

The column in question is called link, but this word is only used with wireless connections in the documentation.

**Comment by jeremystretch** [comment]
The link peers column displays the peer connections on the directly connected link, whether that be a cable or a wireless link. If you'd like to propose changing this, please submit a [feature request](https://github.com/netbox-community/netbox/issues/new?assignees=&labels=type%3A+feature&template=feature_request.yaml) citing your justification for the community to review.
