### ISSUE TITLE
AttributeError exception raised when viewing invalid changelog entry

### ISSUE THREAD

**Issue by jeremystretch** [netbox-community/netbox#10977]
### NetBox version

v3.3.8

### Python version

3.8

### Steps to Reproduce

This issue presents itself when an object change record refers to a type of object that no longer exists; e.g. because a plugin has been uninstalled.

### Expected Behavior

Rendering a change referring to an unknown object type should fail elegantly, without raising an exception.

### Observed Behavior

An AttributeError exception raised when viewing the home page or change log:

```
AttributeError at /

'NoneType' object has no attribute '_base_manager'
```

**Comment by jeremystretch** [comment]
This is revisiting the root problem originally captured in #7149.

**Comment by jeremystretch** [comment]
Unfortunately I haven't been able to find any clever solution to this problem: The exception originates deep within the queryset and is due to prefetching a GFK for an object type which no longer exists. As this scenario arises only in very particular circumstances (i.e. when a previously existing model has been removed without cleaning up the database) and is itself non-destructive, I'm okay with leaving it as-is. Perhaps a future release of Django will make this more feasible to tackle.

**Comment by pdenessen** [comment]
Hi Jeremy, is there a way to include a clean-up script then which checks the log and removes wrong entries which causes this error?
