### ISSUE TITLE
Show rack-list dropdown in rack view

### ISSUE THREAD

**Issue by PieterL75** [netbox-community/netbox#10987]
### NetBox version

v3.3.8

### Feature type

Change to existing functionality

### Proposed functionality

When viewing a rack, you have the 'previous' and 'next' button.
![image](https://user-images.githubusercontent.com/74899468/202899042-3d989f36-d4d4-4020-a673-d0d1e903b3e3.png)

Add a 'dropdown' between those 2 buttons, so that all racks of a location (or site if no location is set) are selectable
![image](https://user-images.githubusercontent.com/74899468/202899269-f6008738-18b1-4c67-9a41-047b382d940a.png)

### Use case

This will provide a faster navigation between the racks.
Another option, is to display all racks in a full-width bar with horizontal scrolling
![image](https://user-images.githubusercontent.com/74899468/202899501-162233a8-2f40-486e-b9eb-b632ea56455a.png)

**Comment by ITJamie** [comment]
I also like this idea. Racktables had a left and right button when viewing a rack to quickly move between racks in a row. It was useful if for getting to the rack ether side of current rack in a single click

**Comment by PieterL75** [comment]
@jeremystretch I found the BS classes to auto hide/show the 2 different navs, depending on the size of the screen.
I like it :-)

**Comment by PieterL75** [comment]
The bar might get pretty wide when there are a lot of racks in one site.. Maybe a 'pagination' style would be a better approach, showing only 3 racks before and 3 racks behind the current rack, with arrows
 < R201 R203 R204 [R205] R206 R207 R208 >
