### ISSUE TITLE
Conditions for custom fields

### ISSUE THREAD

**Issue by Metrax** [netbox-community/netbox#10990]
### NetBox version

v3.3.7

### Feature type

Change to existing functionality

### Proposed functionality

It would be nice to have conditions for custom fields, that dedice when the field will be visible (or disabled/enabled) in create/edit/show mask or can be filled by API.

2 examples:
- a custom field in dcim.devices like "HPE Support URL", should only be visible/editable, if the condition manufacturer name "HPE" is matching.
- a custom field in virtualization.virtual-machines like "VNC Port" should only be visible/editable, if the cluster type is "KVM".

### Use case

For instances that have a lot of custom fields, this would make it easier to keep the overview in the UI and prohibit accidentally filled custom fields. In my example, i have an automation behind netbox and from time to time, the users are filling custom fields which only apply for other device types. This results in problems with the scripts of the automation.

**Comment by jeremystretch** [comment]
Thank you for your interest in extending NetBox. Unfortunately, the information you have provided does not constitute an actionable feature request. Per our [contributing guide](https://github.com/netbox-community/netbox/blob/develop/CONTRIBUTING.md), a feature request must include a thorough description of the proposed functionality, including any database changes, new views or API endpoints, and so on. It must also include a detailed use case justifying its implementation. If you would like to elaborate on your proposal, please modify your post above. If sufficient detail is not added, this issue will be closed.
