### ISSUE TITLE
Power utilization is not shown per feed in the rack anymore

### ISSUE THREAD

**Issue by markkuleinio** [netbox-community/netbox#10999]
### NetBox version

v3.3.8

### Python version

3.9

### Steps to Reproduce

Setup:

1. Add manufacturer "Test"
1. Add device type "TestType" (manufacturer Test)
1. Add device role "Test"
1. Add site "TestSite"
1. Add rack "TestRack" (site = TestSite)
1. Add power panel "TestPanel" (site = TestSite)
1. Add power feed "TestFeed1" (panel TestPanel, rack TestRack, AC, 120V, 15A, single-phase, max 80%)
1. Add power feed "TestFeed2" (panel TestPanel, rack TestRack, AC, 120V, 15A, single-phase, max 80%)
1. Add device "PowerRail" (role = Test, type = TestType, site = TestSite, rack = TestRack)
1. For PowerRail, add power port "Upstream1", and then connect it to power feed TestFeed1
1. For PowerRail, add power port "Upstream2", and then connect it to power feed TestFeed2
1. For PowerRail, add power outlet "Outlet1" (power port = Upstream1)
1. For PowerRail, add power outlet "Outlet2" (power port = Upstream2)
1. Add device "MyDevice1" (role = Test, type = TestType, site = TestSite, rack = TestRack, rack face = Front, position = U40)
1. For MyDevice1, add power port "PS1" (maximum draw = 400, allocated draw = 400), and then connect it to PowerRail port Outlet1
1. Add device "MyDevice2" (role = Test, type = TestType, site = TestSite, rack = TestRack, rack face = Front, position = U41)
1. For MyDevice2, add power port "PS1" (maximum draw = 1000, allocated draw = 1000), and then connect it to PowerRail port Outlet2

Now the full chain should be complete: Power panel -> power feed -> PDU -> power supply in the device (for two devices, connected in different feeds that represent different phases).

### Expected Behavior

This is what was observed in NetBox 3.1.5 and this was useful:

1. Go to **TestFeed1**, see that Utilization (Allocated) is 400VA / 1440VA = 28%
1. Go to **TestFeed2**, see that Utilization (Allocated) is 1000VA / 1440VA = 69%
1. Go to **PowerRail**, see that Power Utilization for **Upstream1** is Allocated = 400VA, Available = 1440VA, Utilization = 28%, and for **Upstream2** Allocated = 1000VA, Available 1440VA, Utilization = 69%
1. Go to **TestRack**, see that Power Utilization is 48%, and Power Feeds list shows **TestFeed1** utilization as 28%, and **TestFeed2** utilization as 69%:

![image](https://user-images.githubusercontent.com/25136274/203325949-49d8f374-e4d6-403a-b645-c850e36c507d.png)

The power utilization can be seen per feed in any of these locations, and in the rack there is a list of all the feeds and their utilizations.

The Power Utilization value in the rack shows 48%, which is some kind of average.

### Observed Behavior

Observed in NetBox 3.3.8:

1. Go to **TestFeed1**, see that Utilization (Allocated) is 400VA / 1440VA = 28.0% (~correct)
1. Go to **TestFeed2**, see that Utilization (Allocated) is 1000VA / 1440VA = 69.0% (~correct)
1. Go to **PowerRail**, see that Power Utilization for **Upstream1** is Allocated = 400VA, Available = **empty**, Utilization = **empty**, and for **Upstream2** Allocated = 1000VA, Available = **empty**, Utilization = **empty**
1. Go to **TestRack**, see that Power Utilization is 48.0%, and the Power Feeds list shows **TestFeed1** utilization as **N/A** and **TestFeed2** utilization as **N/A**:

![image](https://user-images.githubusercontent.com/25136274/203326059-8ad88f55-5968-42a4-8d7c-3cae2fb478d5.png)

Now it is not possible to see the per-feed utilization anymore in the rack level.

**Comment by mik0s** [comment]
After updating from 3.2 to 3.3.8, I don’t see recycling anywhere at all - not in feeds, not in racks
<img width="558" alt="3" src="https://user-images.githubusercontent.com/18553944/203636871-e421dc00-74cd-42a3-a394-6cb5caa58abb.png">
<img width="868" alt="2" src="https://user-images.githubusercontent.com/18553944/203636877-03b07846-e3cd-481d-8d70-1d9fff6db975.png">
<img width="561" alt="1" src="https://user-images.githubusercontent.com/18553944/203636880-d37ec282-0f60-4bc8-bf79-c8527b699a3a.png">

**Comment by arthanson** [comment]
@markkuleinio  I'll take a look at rack as well, missed that one - thanks for mentioning it.

**Comment by markkuleinio** [comment]
Thanks for the fixes! Missed from the 3.3.9 release notes list though
