### ISSUE TITLE
Extend webhooks to support webhook weight

### ISSUE THREAD

**Issue by kemeris2000** [netbox-community/netbox#11005]
### NetBox version

Extend webhooks to support webhook weight

### Feature type

New functionality

### Proposed functionality

Extend the Webhook model to support the webhook weight.

### Use case

We use webhooks to trigger ansible playbook executions on Linux platform device. When multiple webhooks are triggered by one device update event, multiple queued jobs are created in certain order. We need ability to control this order.

**Comment by kkthxbye-code** [comment]
Thank you for your interest in extending NetBox. Unfortunately, the information you have provided does not constitute an actionable feature request. Per our [contributing guide](https://github.com/netbox-community/netbox/blob/develop/CONTRIBUTING.md), a feature request must include a thorough description of the proposed functionality, including any database changes, new views or API endpoints, and so on. It must also include a detailed use case justifying its implementation. If you would like to elaborate on your proposal, please modify your post above. If sufficient detail is not added, this issue will be closed.

**Comment by jeremystretch** [comment]
Closing this as there's been no further clarification of the proposed functionality.
