### ISSUE TITLE
Add rename button in Device and Virtualiastion interface lists

### ISSUE THREAD

**Issue by pdenessen** [netbox-community/netbox#11007]
### NetBox version

v3.3.8

### Feature type

Change to existing functionality

### Proposed functionality

If we want to rename a selection of interfaces from a single device or VM then this is possible via the rename button in the interfaces list. If we have to rename the same interface of a  number of devices then this is not possible as the "rename" button is not present in these views.

### Use case

I have 39 VMs with an interface called "Management" these all needs to be renamed to "Management-old"

Add a "rename" button and functionality to the interface views under devices and Virtualization section, similar as they are present in the views of a single Device or VM

### Database changes

Dont think this is needed.

### External dependencies

None

**Comment by rganascim** [comment]
I have a sugestion to solve this issue:
- create a new action called _bulk_rename_ to be used in the object_list.html template
- add the new button model bulk_rename (html template and the def bulk_rename_button)
- in every view that you want to "bulk rename", activate in the actions, e.g:
`actions = ('import', 'export', 'bulk_edit', 'bulk_delete', 'bulk_rename')`

**Comment by rganascim** [comment]
@jeremystretch could you check this solution? It adds the new action "bulk_rename" and can be used in any view.
