### ISSUE TITLE
Change maximum possible power draw from 32767 Watt

### ISSUE THREAD

**Issue by martinum4** [netbox-community/netbox#11017]
### NetBox version

v3.3.8

### Feature type

Change to existing functionality

### Proposed functionality

Increase the maximum possible power draw from ~32kW to any positive value.

### Use case

We tried to map our (hardwired) UPS-systems in NetBox, they have a possible power output of more than 120kW.

### Database changes

Probably none required.

### External dependencies

Probably none required.

**Comment by martinum4** [comment]
Ok, we have a [Riello MPW 300 ](https://www.riello-ups.com/products/1-ups/94-multi-power) mapped as an unracked device with 2 communication module slots (For [Network-Modules](https://www.riello-ups.com/products/4-software-connectivity/85-netman-204)) and Power Module Slots (NetBox used for Inventory Tracking of Power Modules).

Due to the high power demand the UPS is hardwired and can consume/provide up to 125kVA (VA is roughly Watt, depending on power factor) 32kW as maximum for a power port is just not enough, when trying to create a 125kW Power Port in NetBox the following error message appears:
![netbox error message](https://user-images.githubusercontent.com/18295403/204317367-bcae3db3-531d-4845-a254-01b537c7e26d.png)

Does this clear up the use case?

**Comment by jeremystretch** [comment]
> Does this clear up the use case?

I'm afraid it doesn't. From your description, it sounds like you're attempting to model the aggregate output of an UPS as opposed to an individual connection. Where in your network do you have a _single_ power port consuming more than 32kW of power?

**Comment by elipsion** [comment]
Here in Europe it's a very valid power port. We have extension cords rated for 400V/63A three phase (which turns into a bit over 37kW). And there are [CEE17](https://en.wikipedia.org/wiki/CEE_17) plugs available for up to 800A.

**Comment by elipsion** [comment]
What revisions are needed, @jeremystretch?

I'm trying to model a couple of [APC PDPM](https://www.se.com/ww/en/product/PDPM277H/apc-modular-remote-power-panel-277kva-400a-400v-72-pole-300mm/)s with Module bays, if that helps.
