### ISSUE TITLE
Support for multiple environment

### ISSUE THREAD

**Issue by gtherond** [netbox-community/netbox#11010]
### NetBox version

v3.3.3

### Feature type

Data model extension

### Proposed functionality

Implement ability to create various environments such as PROD/STAGING/DEVS.

### Use case

Many companies distinguish hardware between various environment even on the same location/rack or DC.

According to those environment, the hardware do keep the naming convention of the production and is only distinguished from prod by various elements such as IPs, subdomain variation on FQDN or simply OS hostnamectl environment tag.

As for now, we can't get multiple environment easily on DCIM as a device with a non-unique name located on the same tenant/rack can't be added.

If there is another DCIM way to do that please let me know, but for now there is nothing on the documentation regarding this topic to my knowledge.

### Database changes

device name should be allowed do be duplicated.
introduce a environment (table?/row?) concept.

### External dependencies

none

**Comment by jeremystretch** [comment]
Thank you for your interest in extending NetBox. Unfortunately, the information you have provided does not constitute an actionable feature request. Per our [contributing guide](https://github.com/netbox-community/netbox/blob/develop/CONTRIBUTING.md), a feature request must include a thorough description of the proposed functionality, including any database changes, new views or API endpoints, and so on. It must also include a detailed use case justifying its implementation. If you would like to elaborate on your proposal, please modify your post above. If sufficient detail is not added, this issue will be closed.

**Comment by gtherond** [comment]
Will work on that and came back later on with additional information.

**Comment by stovakor** [comment]
Couldn't you accomplish this with Tags?

**Comment by gtherond** [comment]
Nope, even using tags, when you try to put two servers named the same way on the same rack or location netbox throw away an exception about duplicated name.

**Comment by jeremystretch** [comment]
Closing this out as no additional implementation details have been provided. If you would like to edit your post to add sufficient detail and context, I'll be happy to re-open the issue.
