### ISSUE TITLE
Additional Cable Types

### ISSUE THREAD

**Issue by mstoop71** [netbox-community/netbox#11019]
### NetBox version

v3.3.7

### Feature type

Data model extension

### Proposed functionality

Add on Connection types for the interfaces:

- HDMI (Normal, Mini)
- DisplayPort (DP) (Normal, Mini)
- USB-A (Version 1, 2, 3.0, 3.1, 3.2)
- USB-B (Version 1, 2, 3.0, 3.1, 3.2)
- USB-C (Version 1, 2, 3.0, 3.1, 3.2)
- HDBaseT (RJ45)
- XLR 
- Mini-XLR
- Terminalblock (3pin, 4pin & 5pin)

### Use case

In the current age a lot of MERs and SERs are also equipped with AudioVisual equipment (e.g. Matrix Switchers, HDMI Encoders, Decoders, Videowall processors, Audio DSP's etc).
When adding the additional porttypes to the Database devices can more accurately reflect the connectivity options within a single rack but can also start to map out connectivity within e.g. meetingrooms largely extending the use of Netbox. We are currently piloting this at a University where the connectivity options widely vary (Adding displays with HDMI, touchplays with USB, Cameras with USB-c, PC's with HDMI and/or Displayport, etc.).
Having these additions (or even better the option to add our own port types) Netbox suddenly becomes a relevant tool in the AV but also Video Surveillance industry (Cameras also have lots of additional connection types (e.g. SDI in different types).

### Database changes

Probably no database changes are required as within the "Physical Media Classification" it just requires the additional options.

**Comment by jeremystretch** [comment]
> In the current age a lot of MERs and SERs are also equipped with AudioVisual equipment

As has been discussed in numerous other issues, A/V equipment management is out of scope for NetBox.

**Comment by mstoop71** [comment]
Dear Jeremy,

thanks for the response. I'm sorry to hear this though as adding a few additional cable types would hugely increase the potential usecase and accuracy for this. I currently work with the Cable type other and I can efficiently create rooms filled with camera's in custom brackets connecting through USB etc. Adding a few names would make it more accurate whilst it is not doing anything to the structure of the database. Whether I would have an OC-1 or OC-99, an Cat6a or Cat9Z cable should be arbitrary. Yet to anyone working in equipment rooms it would be a huge help.

In any real environment the IT rooms are not just equipped with Network switches and servers, there are KVM consoles (which use VGA or HDMI and PS2 or USB ) there are Mountable displays, etc. etc.

Either way I do appreciate the response and consideration but I think you should reconsider the possibilities you would create and the potential extra audience you would gain access to.

I'm happy to discuss and elaborate if required,

Kind regards,

Micha van der Stoop
+31622493696
________________________________
