### ISSUE TITLE
Commit Rate Consistent Labeling

### ISSUE THREAD

**Issue by ejstover** [netbox-community/netbox#11015]
### NetBox version

v3.2.7

### Feature type

Change to existing functionality

### Proposed functionality

Column header for Commit Rate includes (kbps), but the table changes the units to gbps, mbps, kbps. Would probably be best to eliminate the (kbps) from the column header.
![2022-11-23 22_42_49-Circuits _ NetBox — Mozilla Firefox](https://user-images.githubusercontent.com/19699277/203689151-7188798e-52af-4fa8-8602-801b48361c7f.png)
 

### Use case

Clarity. That's it.

**Comment by renatoalmeidaoliveira** [comment]
The commit rate are stored as an integer in the database, and even with different units in the dropdown, when you select a value it's added in the field in kbps.
Also to enable the user to add any custom value other than the fixed ones, the unit must be explicit.
 With that said I don't think that showing that unit any kind of lack of consistency, indeed I think it's a requirement in order  to keep database consistency when you consider multiple users editing that field without knowing that field unit.
