### ISSUE TITLE
Upgrade instructions is not correct

### ISSUE THREAD

**Issue by F3d0s** [netbox-community/netbox#11027]
### Change Type

Correction

### Area

Installation/upgrade

### Proposed Changes

I'm upgrading Netbox from 2.11.11 to the latest stable version 3.3.8 following the instructions. 

In the page [Upgrading Netbox](https://docs.netbox.dev/en/stable/installation/upgrading/#:~:text=Copy%20local_requirements.txt%2C%20configuration.py%2C%20and%20ldap_config.py%20(if%20present)%20from%20the%20current%20installation%20to%20the%20new%20version%3A) it say "Copy `local_requirements.txt`, `configuration.py`, and `ldap_config.py` (if present) from the current installation to the new version", following these instructions I noticed that none of these files are present in /opt/netbox-3.3.8/. Same thing for `gnunicorn.py`, but on the guide it say to copy the configuration file in `/opt/netbox`.

This is the content of `v3.3.8.tar.gz` which have been unpacked in `/opt/netbox-3.3.8`:
````
$ ls -al /opt/netbox-3.3.8/
total 120
drwxrwxr-x  7 root root  4096 Nov 16 16:32 .
drwxr-xr-x  6 root root  4096 Nov 25 08:47 ..
-rw-rw-r--  1 root root   222 Nov 16 16:32 .gitattributes
drwxrwxr-x  4 root root  4096 Nov 16 16:32 .github
-rw-rw-r--  1 root root   474 Nov 16 16:32 .gitignore
-rw-rw-r--  1 root root   156 Nov 16 16:32 .readthedocs.yaml
-rw-rw-r--  1 root root   111 Nov 16 16:32 CHANGELOG.md
-rw-rw-r--  1 root root  9156 Nov 16 16:32 CONTRIBUTING.md
-rw-rw-r--  1 root root 10174 Nov 16 16:32 LICENSE.txt
-rw-rw-r--  1 root root   316 Nov 16 16:32 NOTICE
-rw-rw-r--  1 root root  5702 Nov 16 16:32 README.md
-rw-rw-r--  1 root root  2094 Nov 16 16:32 SECURITY.md
-rw-rw-r--  1 root root  3554 Nov 16 16:32 base_requirements.txt
drwxrwxr-x  2 root root  4096 Nov 16 16:32 contrib
drwxrwxr-x 16 root root  4096 Nov 16 16:32 docs
-rw-rw-r--  1 root root 12648 Nov 16 16:32 mkdocs.yml
drwxrwxr-x 17 root root  4096 Nov 16 16:32 netbox
-rw-rw-r--  1 root root   416 Nov 16 16:32 pyproject.toml
-rw-rw-r--  1 root root   817 Nov 16 16:32 requirements.txt
drwxrwxr-x  3 root root  4096 Nov 16 16:32 scripts
-rwxrwxr-x  1 root root  4657 Nov 16 16:32 upgrade.sh
````

**Comment by kkthxbye-code** [comment]
>Copy local_requirements.txt, configuration.py, and ldap_config.py (if present) *from the current installation* to the new version

> I noticed that none of these files are present *in /opt/netbox-3.3.8/*.

They are not supposed to be present in the new version, as the instructions you pasted clearly mentions they are to be copied from the old version as they are user created configuration files.

> Same thing for gnunicorn.py, but on the guide it say to copy the configuration file in /opt/netbox.

Again, it's not incorrect. Here's what it says:

> If you followed the original installation guide to set up gunicorn, be sure to copy its configuration as well:
> `sudo cp /opt/netbox-X.Y.Z/gunicorn.py /opt/netbox/`

And here's the [original installation guide](https://docs.netbox.dev/en/stable/installation/4-gunicorn/):

> NetBox ships with a default configuration file for gunicorn. To use it, copy /opt/netbox/contrib/gunicorn.py to /opt/netbox/gunicorn.py. (We make a copy of this file rather than pointing to it directly to ensure that any local changes to it do not get overwritten by a future upgrade.)

Again, the file is not supposed to be in the zip for the new version at that path. It's supposed to be copied from the old version, or alternatively from the contrib folder in the new version.

Closing this as there's nothing to change.

**Comment by F3d0s** [comment]
> They are not supposed to be present in the new version, as the instructions you pasted clearly mentions they are to be copied from the old version as they are user created configuration files.

Then maybe I misunderstood what the guide says, copying the files from the installation directory (unpacking `v3.3.8.tar.gz` in `/opt` create the folder `/opt/netbox-3.3.8`) to the current installation with `sudo cp /opt/netbox-X.Y.Z/file.py /opt/netbox/ `.
