### ISSUE TITLE
Clone option Locations in its entirety

### ISSUE THREAD

**Issue by mstoop71** [netbox-community/netbox#11021]
### NetBox version

v3.3.7

### Feature type

New functionality

### Proposed functionality

Clone an entire location, all equipment and all internal connections

### Use case

In order to speed up deployments of standardized rooms (e.g. meetingrooms) it would be extremely useful to be able to clone an entire room and all racks and devices in it.
When a room is created (of which an enterprise and a university have dozens or more) the process of recreating the rooms is a bit tedious. When a room could be cloned listing all racks, racked equipment, non-racked equipment as well as all internal connections I could rename a copy of Room 1 as Room 2 and through export/import or manually add/change Serial numbers, MAC address, IP addresses, etc. 
Cloning would reduce the risk of errors or ommissions when recreating identical rooms. It would also allow to use a master room template to used for smaller room types by just removing equipment not in use in that room.

**Comment by jeremystretch** [comment]
> Clone an entire location, all equipment and all internal connections

This is far from trivial to accomplish, and not a goal of NetBox's object cloning feature, which exists merely as a convenience. You can, however, write a custom script to facilitate this process, including logic to handle the myriad potential problems that may surface when attempting to blindly replicate a large number of objects.
