### ISSUE TITLE
Bulk Edit WiFi interfaces

### ISSUE THREAD

**Issue by cyberndj** [netbox-community/netbox#11038]
### NetBox version

v3.3.6

### Python version

3.10.6

### Steps to Reproduce

Under Interfaces: 
-- Filter of Kind: Wireless 
Select more than one Wireless interface.
Select the yellow "Edit Selected" button at the bottom. 

### Expected Behavior

Have the fields "Wireless LAN group" and "Wireless LANs" show up in the Wireless section so we can mass edit those fields. 

### Observed Behavior

The Fields "Wireless LAN group" and "Wireless LANs" are missing.

**Comment by jeremystretch** [comment]
Please resubmit this issue as a [feature request](https://github.com/netbox-community/netbox/issues/new?assignees=&labels=type%3A+feature&template=feature_request.yaml).
