### ISSUE TITLE
Add a link to the parent Prefix in IP Ranges

### ISSUE THREAD

**Issue by a-belhadj** [netbox-community/netbox#11039]
### NetBox version

v.3.3.6

### Feature type

Change to existing functionality

### Proposed functionality

I want to see the parent prefix of an IP range when I look at my IP range (https://mynetbox/ipam/ip-ranges/2/)
A simple way to implement that is to display the prefix of a random IP in the range, but it will not work if the range goes through multiple prefixes.

### Use case

We want to move our "fake" prefixes to IP ranges, but it's hard to know the parent prefix of an IP Address.

### Database changes

It should be a computed value and shouldn't change the database

### External dependencies

No dependencies

**Comment by elipsion** [comment]
This is implemented in #10692.

**Comment by jeremystretch** [comment]
Marking this as blocked by #7845. We need to determine an efficient way of automatically mapping child IP addresses, ranges, and prefixes to their parent prefixes.

**Comment by jeremystretch** [comment]
Absent a solution for #7845, we can just do what we do for IP prefixes currently: Dynamically resolve any containing prefixes and list them in a table on the page.
