### ISSUE TITLE
Default values in custom fields applied to imported data

### ISSUE THREAD

**Issue by ejstover** [netbox-community/netbox#11040]
### NetBox version

v3.2.7

### Feature type

Change to existing functionality

### Proposed functionality

A custom field with a default value should always be applied to all future new objects, including objects that are imported. 

### Use case

I personally use the DeviceTypeLibrary, plus a [Zabbix sync script](https://github.com/TheNetworkGuy/netbox-zabbix-sync) to sync NetBox inventory to Zabbix monitoring via API. Part of the requirements of the sync script is a custom field in the dcim.devicetype that specifies the Zabbix monitoring template to use. I've defined a default value that is applied when manually creating a device type, but not when imported via YAML/JSON.
![2022-11-28 20_54_34-Add a new device type _ NetBox — Mozilla Firefox](https://user-images.githubusercontent.com/19699277/204419331-83c157c3-7a82-4224-9846-3fece3943f9f.png)
![2022-11-28 20_55_02-Editing device type MX84 _ NetBox — Mozilla Firefox](https://user-images.githubusercontent.com/19699277/204419333-78f33295-2a56-45e7-9ae4-f025c25b8348.png)

I could see reasoning against this functionality. I have patch panel device types that don't apply to the use case I've listed above.

**Comment by atownson** [comment]
I have found if you define a required custom field for Interfaces with a defined default value, when instantiating a new Device, the value of that custom field for the created Interfaces is `null`. Could we please expand the scope of this request to more than the bulk import functionality and ensure all means of creating models are covered (device templates, scripts, etc.)? Thanks.

**Comment by jeremystretch** [comment]
This can likely be addresses using the same approach as #11565.

**Comment by abhi1693** [comment]
@jeremystretch The issue that you have mentioned as a reference, should that not be applied commonly to all models?

**Comment by jeremystretch** [comment]
Treating this as a bug per #16073
