### ISSUE TITLE
View DNS name of IP object from interface / device interface view.

### ISSUE THREAD

**Issue by rhyser9** [netbox-community/netbox#11058]
### NetBox version

v3.3.8

### Feature type

New functionality

### Proposed functionality

Would like the ability to see the DNS names associated with IP addresses assigned to an interface from the `devices/xxx/interfaces/` table and the `interfaces/xxx/` > IP Addresses table.

### Use case

Would allow for easy DNS name <> device / interface association, such as a host with multiple interfaces which have separate DNS names (i.e. ftxgm01-dmz.domain.com and ftxgm01-db.domain.com or similar).

**Comment by ShellBoyAFK** [comment]
nice

**Comment by jeremystretch** [comment]
There's only so much data we can reasonably fit into the table, and IMO the current implementation is about at the practical limit. Maybe there's some alternative approach leveraging dynamically-loaded content that would be more appropriate, but I'm not sure what that would look like.
