### ISSUE TITLE
Allow interface MAC address to accept spaces during input validation

### ISSUE THREAD

**Issue by stovakor** [netbox-community/netbox#11080]
### NetBox version

v3.4-beta1

### Python version

3.8

### Steps to Reproduce

Add a MAC address value to an interface
The following formats are accepted
>00:12:37:F9:5B:7C
00-12-37-F9-5B-7C
001237-F95B7C
001237F95B7C

The following format is not accepted
`00 12 37 F9 5B 7C`

### Expected Behavior

Several devices output their MAC address with spaces.
When inputting a MAC address with spaces NetBox should allow the validation and strip whitespaces.

### Observed Behavior

When attempting to add a MAC address with spaces in it, the validation fails.
![1](https://user-images.githubusercontent.com/119611316/205179639-81955ecf-7c98-4c4b-91c4-e483cbfd48eb.png)

**Comment by jeremystretch** [comment]
The specified format is not supported. If you would like to introduce support for it, please submit a [feature request](https://github.com/netbox-community/netbox/issues/new?assignees=&labels=type%3A+feature&template=feature_request.yaml).
