### ISSUE TITLE
Add new status for IP Address

### ISSUE THREAD

**Issue by stovakor** [netbox-community/netbox#11104]
### NetBox version

v3.3.9

### Feature type

Change to existing functionality

### Proposed functionality

IP Addresses within NetBox have allowed statues of the following:
- Active
- Reserved
- Deprecated
- DHCP
- SLAAC

I would like to request to add an additional statuses
- Available
- Inactive

It would be nice to have both for the greatest flexibility in use cases.

### Use case

In my specific use case, it would be nice to be able to add IP addresses and mark their status as 'available' for use. The IP's aren't 'active' in the sense they have a device attached to them and are pingable. So we prefer not to mark IP's as active unless they are associated with a device.

By adding the additional status we would add an IP address to NetBox and mark it as available so other team members knew this IP was available for whatever role. We understand there is a status of 'reserved', but in this example the IP's aren't reserved for any particular device/function .. they are available for someone to assign. (manually, and not DHCP so status of DHCP also doesn't apply)

### Database changes

None

### External dependencies

None

**Comment by kkthxbye-code** [comment]
Already possible to add custom status choices.

https://docs.netbox.dev/en/stable/configuration/data-validation/#field_choices

**Comment by stovakor** [comment]
Thank you! That is exactly what I was looking for.
