### ISSUE TITLE
Allow filtering of L2VPN based on slug

### ISSUE THREAD

**Issue by wouterdb** [netbox-community/netbox#11119]
### NetBox version

3.3.9

### Feature type

Change to existing functionality

### Proposed functionality

1. Currently, is seems to be impossible to query `L2VPN`s by slug.
2. However, for the `L2VPNTermination` the slug if the primary ID to refer to an L2VPN

This inconsistent handling of ID's makes automated handling of the API very difficult. 

# References
https://github.com/netbox-community/netbox/blob/develop/netbox/ipam/filtersets.py#L933
https://github.com/netbox-community/netbox/blob/develop/netbox/ipam/filtersets.py#L981

### Use case

Consistently using the same field as ID for the same object simplifies integration with this API

**Comment by wouterdb** [comment]
@jeremystretch thank you for this super fast fix. 

I'm building/generating an integration with netbox, so I'm going through the API definition with a fine comb.
Would it be useful if I report all inconsistencies I find? If so, what is the preferred form? (one ticker per issue, one big monster ticket, put it in the discussion,....)

**Comment by jeremystretch** [comment]
@wouterdb that would be great, thanks! An individual GitHub issue per bug is generally preferred to aid in efficient triage, unless there's a common pattern across multiple issues. For example, if multiple API endpoints exhibit the same undesired behavior, it would be fine to capture them all under a single issue. If in doubt we can always break out/consolidate issues as needed. Let me know if I can be of any help!
