### ISSUE TITLE
Allow VLAN filtering based on L2VPN termination

### ISSUE THREAD

**Issue by TheNetworkGuy** [netbox-community/netbox#11118]
### NetBox version

v3.3.9

### Feature type

New functionality

### Proposed functionality

Allow (API) filtering VLAN's based on L2VPN termination. Currently i can filter VLAN's based on description, ID etc. But not with their corresponding VXLAN VNI identifier.

If this functionality is already present in a different way (get all L2VPN's with linked VLAN's) then that would also fulfill our use-case.

### Use case

This would allow us to get a list of all VLAN's which would be active in our VXLAN environment with the API call "L2VPN_termination__n='null'".

### Database changes

No DB change required

### External dependencies

No new external dependencies.

**Comment by TheNetworkGuy** [comment]
To comment on this issue, maybe we are trying to filter the wrong way around. Instead of filtering on the VLAN object we can also perform a query on the L2 Terminations object:

https://netbox.local/api/ipam/l2vpn-terminations/?assigned_object_type_id=49

**Comment by abhi1693** [comment]
@jeremystretch I'd like to take this

**Comment by kkthxbye-code** [comment]
@abhi1693 - All yours.

**Comment by jeremystretch** [comment]
I've extended this functionality to device & VM interfaces as well in 4bfc3bf41.
