### ISSUE TITLE
Bulk Rack Reservation Import not working (Unexpected column header "﻿site" found.)

### ISSUE THREAD

**Issue by ouberlord** [netbox-community/netbox#11120]
### NetBox version

v3.3.6

### Python version

3.8

### Steps to Reproduce

1. Navigate to the "Rack Reservation Bulk Import" page (https://netbox/dcim/rack-reservations/import/).
2. Click on "CSV File Upload.
3. Choose the file using the button.
4. Click the "Submit" button.

### Expected Behavior

The import should properly import the data and then go to the screen that details the objects that were created, such as with the other file-based bulk imports elsewhere in NetBox.

### Observed Behavior

An error appears, "Unexpected column header "﻿site" found", though "site" should be an expected column.

However, if the exact contents of the CSV file are copied and pasted into the "CSV Data" view, the import works properly. This implies it is an issue with the file-based import process, and not with the data contained within the CSV file.

**Comment by jeremystretch** [comment]
Thank you for opening a bug report. Unfortunately, the information you have provided is not sufficient for someone else to attempt to reproduce the reported behavior. Remember, each bug report must include detailed steps that someone else can follow on a clean, empty NetBox installation to reproduce the exact problem you're experiencing. These instructions should include the creation of any involved objects, any configuration changes, and complete accounting of the actions being taken. Also be sure that your report does not reference data on the public NetBox demo, as that is subject to change at any time by an outside party and cannot be relied upon for bug reports.

**Comment by jeremystretch** [comment]
> If the latter, would including an example CSV file be needed?

That would be the place to start. Your report above doesn't include any actual data being sent to NetBox, so there's no way for us to test reproduction. You don't have to post the exact file you tried uploading originally, but it has to be enough to trigger the error.

**Comment by jeremystretch** [comment]
Closing thus out as no further reproduction details have been provided.
