### ISSUE TITLE
API Documentation is Missing dns_name__empty for /ipam/ip-addresses

### ISSUE THREAD

**Issue by Spaceman1701** [netbox-community/netbox#11151]
### NetBox version

v3.3.9

### Python version

3.8

### Steps to Reproduce

1. view `/ipam/ip-address` in the swagger REST API docs  and notice that `dns_name__empty` is listed as a parameter
2. make an HTTP GET to `/api/ipam/ip-addresses/?dns_name__empty=0` and `/api/ipam/ip-addresses/?dns_name__emtpy=1` and observe that the query parameter has the desired effect

### Expected Behavior

The `/ipam/ip-addresses` endpoint should list the `dns_name__empty` query parameter in the Swagger API Docs

### Observed Behavior

The Swagger API docs are missing the `dns_name__emtpy` query parameter for `GET /ipam/ip-addresses` in the Swagger docs. The actual API still seems to honor this parameter. I've observed this in Netbox 3.3.9. 

This is easy to observe on the demo instance: 
https://demo.netbox.dev/api/ipam/ip-addresses/?dns_name__empty=1
https://demo.netbox.dev/api/ipam/ip-addresses/?dns_name__empty=0

**Comment by fabi125** [comment]
We have some automation around the auto-generated api documentation and this is causing some issues for us. Could someone point me in the right direction on what might have caused this? I'm happy to take a stab at fixing it.

**Comment by kkthxbye-code** [comment]
I tested on v3.3.9 and v3.4.0 and this seems to have been fixed. In v3.3.9 dns_name__empty is missing and in v3.4.0+:

![image](https://user-images.githubusercontent.com/400797/218498788-abb75b46-fa27-4ca6-8bd6-97b86c417aa2.png).
