### ISSUE TITLE
Provide Saved Filters dropdown field on Results tab

### ISSUE THREAD

**Issue by dreng** [netbox-community/netbox#11153]
### NetBox version

v3.4-beta1

### Feature type

Change to existing functionality

### Proposed functionality

Please move Saved Filters dropdown from Filters tab to Results tab or just add the dropdown to Results and leave a copy where it is now.

### Use case

As stated in the discussion #11016, the new Saved Filters dropdown field should allow for a quicker workflow.

In order to select another Saved Filter you have to change the tab, chose the filter and click search (which kicks you back to the Results tab). It would be quicker and more convenient to have that functionality on the Results tab. The best thing would be to select the filter from a dropdown field on the Results tab and have the result displayed directly (without having to click on another button like "Search").

### Database changes

None

### External dependencies

None

**Comment by stovakor** [comment]
agree. NetBox requires too many clicks as it is. The goal of streamlining is to reduce the number of clicks.

**Comment by stovakor** [comment]
Why are comments that are advocating for this feature being deleted? How is the community supposed to voice their support for something if their comments are deleted?

**Comment by jeremystretch** [comment]
I've experimented with this a bit, and while it seems very feasible, we'll need to spend some time devising the ideal widget display as I don't believe there's an existing pattern to follow.

**Comment by PieterL75** [comment]
Can we get this FR open again ?
I really would like to see the saved filters right on the table, and not in the 'filter' tab
Also move those badges next to the quicksearch, to preserve space
![image](https://github.com/netbox-community/netbox/assets/74899468/5cebbbd8-3e09-4c58-b0e1-3b6615785545)
