### ISSUE TITLE
Auto-detect format during bulk import

### ISSUE THREAD

**Issue by jeremystretch** [netbox-community/netbox#11163]
### NetBox version

v3.4-beta1

### Feature type

Change to existing functionality

### Proposed functionality

Try to automatically detect the data format (CSV, JSON, or YAML) during import by default. Retain the explicit options as well to ensure the user can specify the format should auto-detection fail.

### Use case

Automatically detecting the format is a bit more convenient for the user.

**Comment by jsenecal** [comment]
Could this be done with a series of regex lookup of the first few chars to make it fast? 
ie:
{ or [ is json;
^(---\n)?\w+:\n for yaml (something like that)
anything with a series of , and strings a csv...

**Comment by jeremystretch** [comment]
@jsenecal that's my hope. I'd like to stop short of initiating the loader for each type directly, and just infer the type from the first line. If we encounter some scenario where it's not possible to tell, we can just raise a validation error asking the user to specify the type.

**Comment by kkthxbye-code** [comment]
Do note that YAML is a superset of JSON, so all JSON is valid YAML.
