### ISSUE TITLE
Import > export to other netbox with csv files fails

### ISSUE THREAD

**Issue by deku-m** [netbox-community/netbox#11176]
### NetBox version

v3.3.9

### Python version

3.8

### Steps to Reproduce

1. Using docker netbox, deploy and fill in information.
2. Click on providers or anything 
3. Go to export > all data
4. Download csv file
5. Import on other netbox with csv file upload.
6. Error "Unexpected column header ""Name" found.

### Expected Behavior

The downloaded csv file should be uploaded. The format should be valid but doesnt look like it.

### Observed Behavior

 Error "Unexpected column header ""Name" found.
See attachments of csv files.
[netbox_providers.csv](https://github.com/netbox-community/netbox/files/10226636/netbox_providers.csv)
[netbox_regions.csv](https://github.com/netbox-community/netbox/files/10226637/netbox_regions.csv)
[netbox_RIRs.csv](https://github.com/netbox-community/netbox/files/10226638/netbox_RIRs.csv)

**Comment by czarnian** [comment]
Export and Import features use very different data structure - column names and order, capitalization, etc., which can get very annoying. There are several reasons for that, some were explained in previous issues.

Currently the best approach for data migration is database dump. The process is described in documentation https://docs.netbox.dev/en/stable/administration/replicating-netbox/

**Comment by deku-m** [comment]
> Export and Import features use very different data structure - column names and order, capitalization, etc., which can get very annoying. There are several reasons for that, some were explained in previous issues.
> 
> Currently the best approach for data migration is database dump. The process is described in documentation https://docs.netbox.dev/en/stable/administration/replicating-netbox/

Ok thanks for the explaination but if i only want a couple things exported doesnt make sense to dump the entire database for only one or two specific parts

**Comment by czarnian** [comment]
Then you will have to manually edit the exported data to fit to the import format, as described on the respective Import pages. Keep in mind that there are dependencies between some item types, so you have to find a proper order of imports.

**Comment by kkthxbye-code** [comment]
https://github.com/netbox-community/netbox/wiki/Frequently-Asked-Questions#why-cant-i-pass-exported-data-directly-into-the-import-form
