### ISSUE TITLE
Pressing the Enter key in the Quick Search textbox activates the Bulk Edit button

### ISSUE THREAD

**Issue by atownson** [netbox-community/netbox#11178]
### NetBox version

v3.3.9

### Python version

3.8

### Steps to Reproduce

1. Navigate to any model's list view (i.e. .../dcim/devices/).
2. Ensure there is at least one instantiated model present.
3. Type something in the Quick Search textbox and hit the Enter key when done.

### Expected Behavior

The search is performed once the Enter key is pressed.

### Observed Behavior

The Enter key activates the Bulk Edit button, and an exception that no items were selected is shown.

![image](https://user-images.githubusercontent.com/52260120/207628284-50523c47-63a1-42c8-be4a-6616ad4d1755.png)

The workaround for this is to obviously not hit the Enter key, but rather wait on the search to be applied. I believe this behavior was introduced in v3.3.8.

**Comment by kkthxbye-code** [comment]
Regression from https://github.com/netbox-community/netbox/pull/10848

The quick search input element is now inside the form. @arthanson
