### ISSUE TITLE
Wrong SVG visualization with multiple path in Circuits Terminations

### ISSUE THREAD

**Issue by renatoalmeidaoliveira** [netbox-community/netbox#11184]
### NetBox version

v3.3.10

### Python version

3.8

### Steps to Reproduce

1. Create a Circuit (Multi-Root)
2. Create a Circuit (Multi-100)
3. Create a Circuit (Multi-200)
4. Create on each Circuit a termination in the same site, and connect Multi-100 and Multi-200 to Multi-Root
5.  Connect the other Circuit termination to some device interface

### Expected Behavior

When you render the connection trace in the interface connected to the Multi-Root all other circuits and device interfaces are show in the svg

### Observed Behavior

# Trace from the interface connected to the Multi-Root Circuit:

![image](https://user-images.githubusercontent.com/16046203/207743493-e57def12-d47a-4b71-97f0-b8d98db57745.png)

# Trace from the interface connected to the Multi-100 Circuit:
![image](https://user-images.githubusercontent.com/16046203/207743580-794adde8-ca00-41ac-b3d2-9a72b82b9da3.png)

# Trace from the interface connected to the Multi-200 Circuit:
![image](https://user-images.githubusercontent.com/16046203/207743663-6f1e96fa-22e9-4655-a671-f72175363d9a.png)

**Comment by jeremystretch** [comment]
> 4. Create on each Circuit a termination in the same site, and connect Multi-100 and Multi-200 to Multi-Root

Please expand on this, as it's not clear exactly what connections are to be made.

**Comment by renatoalmeidaoliveira** [comment]
@jeremystretch
1 - For all Circuits create Termination A on the same site.
2 - In the Circuit Multi-Root go in Termination A and click in connect and choose Circuit Termination
3 - In the Side B, add the Side B termination of the other Circuits (Multi-100 and Multi-200)

**Comment by jeremystretch** [comment]
> When you render the connection trace in the interface connected to the Multi-Root all other circuits and device interfaces are show in the svg

We can only render cable paths up to the point where there's a divergent split, which in this case is the two far-end circuit terminations. The correct behavior should be to convey that the path splits and give the user the option of choosing one branch to follow. Here's what I've implemented:

![Screenshot 2022-12-16 at 16-27-29 Cable Trace for Interface GigabitEthernet0_1_2 NetBox](https://user-images.githubusercontent.com/13487278/208191903-d84f1ab1-23da-4a25-af73-9c706381bc40.png)
