### ISSUE TITLE
Unable to view script results

### ISSUE THREAD

**Issue by sleepinggenius2** [netbox-community/netbox#11185]
### NetBox version

v3.4.0

### Python version

3.8

### Steps to Reproduce

1. Have a script in the scripts directory
2. Navigate to **Other > Scripts**
3. Click on the **Last Run** link or **Run Script** button for the script
4. Receive error

### Expected Behavior

The script results should be displayed.

### Observed Behavior

**Server Error**
There was a problem with your request. Please contact an administrator.

The complete exception is provided below:

```
<class 'django.template.exceptions.TemplateSyntaxError'>

Invalid filter: 'naturaltime'

Python version: 3.8.9
NetBox version: 3.4.0
```

It looks like this was introduced in 4297c65f874fd30cf24bc1977025065072a47717 and is caused by a missing `{% load humanize %}` line in `netbox/templates/extras/htmx/script_result.html`, but that line is present in `netbox/templates/extras/htmx/report_result.html` and I can confirm that reports are unaffected, it's just scripts.

**Comment by jeremystretch** [comment]
> It looks like this was introduced in https://github.com/netbox-community/netbox/commit/4297c65f874fd30cf24bc1977025065072a47717 and is caused by a missing {% load humanize %} line

Confirmed; this was an oversight on my part. :disappointed:

**Comment by Arshnika** [comment]
I had the same issue. The good news is the issue has been fixed by adding {% load humanize %} to the top of netbox/templates/extras/htmx/script_result.html file as per Jermey's advise.
