### ISSUE TITLE
Document supported child objects on bulk import views

### ISSUE THREAD

**Issue by jeremystretch** [netbox-community/netbox#11204]
### NetBox version

v3.4.0

### Feature type

Change to existing functionality

### Proposed functionality

Certain types of objects in NetBox, such as device types and module types, support the simultaneous import of various child objects (e.g. component templates) during bulk import. However, these child objects are not documented as supported under each form as they local fields ares. Ideally, we should annotate support for child objects wherever relevant.

### Use case

This will convey to users that the functionality exists where they might not otherwise realize, and serve as a reference.

**Comment by vyas-n** [comment]
Hi @jeremystretch I'd like to volunteer for documenting this behaviour.

Anything I need to communicate beforehand, or should I start with a PR?
