### ISSUE TITLE
MAC Address tracking for virtual machines

### ISSUE THREAD

**Issue by dutchman80** [netbox-community/netbox#11208]
### NetBox version

v3.4

### Feature type

Data model extension

### Proposed functionality

Add a MAC Address tracker to the Virtualization section, and allow MAC Addresses to be associated with individual VMs

### Use case

VMware (and perhaps others virtualization platforms?) have a range of MAC addresses that you can statically assign to VMs.  This is very useful when using a VM with RLM or FlexLM licensed software (where the MAC address is what's used to generate the licenses), as you can perpetually reserve a specific MAC for a specific software license.  I see this operating exactly like the Static IP list in the IPAM section.

**Comment by kkthxbye-code** [comment]
I'm not sure I understand here. You can already specify the MAC address on VM interfaces. I know very little about vmware, but I'm not sure I see how assigning a MAC address to the vm itself makes sense. Could you elaborate on your proposal?

**Comment by kkthxbye-code** [comment]
This seems like a fairly rare usecase and I really don't see IP addresses and MAC addresses as comparable. While MAC's are assignable to some degree, they are really intended as hardware addresses.

I recommend that you implement this as a plugin as this is not something likely to be included in core netbox.

**Comment by jeremystretch** [comment]
This will likely be addressed by FR #4867.
