### ISSUE TITLE
Power feeds not registering chained devices

### ISSUE THREAD

**Issue by dutchman80** [netbox-community/netbox#11215]
### NetBox version

v3.4

### Python version

3.9

### Steps to Reproduce

Create Power Feed "pf1"
Create UPS "ups1" and connect Power Port to Power Feed "pf1"
Create PDU "pdu1" and connect Power Port to "ups1" Power Outlet
Create Switch "switch1" and connect Power Port to "pdu1" Power Outlet

Power chain is now: switch1 > pdu1 > ups1 > pf1

When connected in this manner, no load is being registered on the power feed "pf1"

If I remove the UPS from the chain, connecting "pdu1" directly to "pf1", then load from "switch1" starts registering on "pf1"

This was called out in the past in issue #7565...maybe a regression?

### Expected Behavior

A power feed should register the load from all devices in the power chain

### Observed Behavior

Power feeds only seem to be registering loads from devices connected one layer deep in the power chain

**Comment by jeremystretch** [comment]
> When connected in this manner, no load is being registered on the power feed "pf1"

You've not specified a power draw for any of the ports.

**Comment by dutchman80** [comment]
The switch device connected to the PDU has a registered power draw.  If I connect the PDU to the power feed directly, I see load on the power feed.  It's just when the PDU is connected to the UPS (which is connected to the power feed) that I don't see load on the power feed.

**Comment by jeremystretch** [comment]
Please update your issue above to provide steps that someone else can follow to replicate the reported problem. No one else has access to your installation to verify how it is configured.

**Comment by jeremystretch** [comment]
Closing this out as sufficient detail to reproduce the reported behavior has not been provided.

**Comment by dutchman80** [comment]
Hi, I didn't see your last reply; sorry for the delay in commenting.

I'm not sure what other steps I can provide to reproduce the issue, other than the steps I provided in the initial issue.  What further detail can I give?

Basically, if you have more than one pass-through device (i.e. PDU & UPS) between the power feed and the device consuming the power, then the power feed registers 0 utilization.
