### ISSUE TITLE
Device Roles: Add Virtual Maschines view

### ISSUE THREAD

**Issue by ShellBoyAFK** [netbox-community/netbox#11228]
### NetBox version

v3.3.9

### Feature type

Change to existing functionality

### Proposed functionality

Under Device Roles, only the Devices are displayed in the detailed view of the individual roles.

But not the virtual machines associated with them.

This does not look complete. Maybe this was forgotten.

![vms](https://user-images.githubusercontent.com/96151517/208300381-3bebcccb-7698-4dc4-9d3d-8c44323d4d6a.PNG)

### Use case

I think the use case is obvious or?

So that you can see immediately in the respective role which VMs have this role 

### Database changes

?

### External dependencies

?

**Comment by jeremystretch** [comment]
IMO it doesn't make sense to display two potentially large tables one on top of the other. Viewing the VMs table would require the user to scroll through the entire devices table, assuming they even know it's there. Maybe child tabs (like for components under the device view) would be more suitable?

**Comment by jeremystretch** [comment]
@hagbarddenstore just an FYI, when you reply to an issue via email for some reason GitHub is tacking on the quoted portion of the message. Not sure why, as it seems to work fine for others. (I've been editing out the cruft as it pops up, which is why you'll see the "edited by" note on some of your comments.)

**Comment by ShellBoyAFK** [comment]
sound good thx

**Comment by hagbarddenstore** [comment]
> @hagbarddenstore just an FYI, when you reply to an issue via email for some reason GitHub is tacking on the quoted portion of the message. Not sure why, as it seems to work fine for others. (I've been editing out the cruft as it pops up, which is why you'll see the "edited by" note on some of your comments.)

Ah thanks. Seems to be an iOS thing (Or my incompetence...)

**Comment by abhi1693** [comment]
@jeremystretch I'd like to take this

**Comment by kkthxbye-code** [comment]
@abhi1693 - All yours.
