### ISSUE TITLE
dns_name is enforcing lower case

### ISSUE THREAD

**Issue by olafhering** [netbox-community/netbox#11220]
### NetBox version

v3.3.7

### Python version

3.8

### Steps to Reproduce

open `https://host/ipam/ip-addresses/1/edit/`
type a FQDN with an upper case letter in the hostname part.
click on `Save`
The `IP Address` overview part shows the `DNS Name` in all lower case.

### Expected Behavior

The entered data should arrive "as is" in the database.

### Observed Behavior

The data are somewhat corrupted, the upper/lower-case info is lost.

**Comment by kkthxbye-code** [comment]
I'm gonna close this as DNS names are intentionally lowercased in netbox:

https://github.com/netbox-community/netbox/blob/3675ad2539400038af6797140ddca3679b8bca30/netbox/ipam/models/ip.py#L873-L874

From a very short googling, it seems like DNS names are case insensitive. If we were to change this behavior your would need to create a feature request instead, but you would have to provide a very good reason for why it should be changed, as it seems to be a very niche case to want case sensitive DNS names.

My best advice is to create a custom field on the IPAddress model for your case sensitive DNS records.

**Comment by olafhering** [comment]
There is now a feature for this bug.
