### ISSUE TITLE
Add support for 800G interface types

### ISSUE THREAD

**Issue by dare-to-recurse** [netbox-community/netbox#11227]
### NetBox version

v3.4.1

### Feature type

New functionality

### Proposed functionality

Add the following options to the type selector

- OSFP800 (800GE)
- QSFP-DD800 (800GE)

---

The preferred names for the interface types according to the published specifications seems to be _OSFP800_ and _QSFP-DD800_ (though it remains to be seen if vendors diverge from this)

QSFP-DD800 specification (see page 1 - document title): http://www.qsfp-dd.com/wp-content/uploads/2022/07/QSFP-DD-Hardware-Rev6.3-final.pdf
OSFP800 specification (see page 13): https://osfpmsa.org/assets/pdf/OSFP_Module_Specification_Rev5_0.pdf

### Use case

800G interfaces/transceivers seem to be appearing on the market, and implementing support for these interface types enables accurate modeling of 800G connections.

### Database changes

I don't believe this should require database changes.

### External dependencies

None.

**Comment by reishoku** [comment]
Hello @jeremystretch , I would like to open a PR to close this issue.

**Comment by kkthxbye-code** [comment]
@reishoku - All yours!
