### ISSUE TITLE
Reindex command does not accept app_label as argument

### ISSUE THREAD

**Issue by Alef-Burzmali** [netbox-community/netbox#11223]
### NetBox version

v3.4.1

### Python version

3.10

### Steps to Reproduce

1. Look at the help of the reindex management command: it accepts ```app_label[.ModelName]```
```
$ python /opt/netbox/netbox/manage.py reindex -h
[...]
positional arguments:
  app_label[.ModelName]
                        One or more apps or models to reindex
```
2. Reindex all models of a plugin or an app:
```
$ python /opt/netbox/netbox/manage.py reindex dcim
CommandError: Invalid model: dcim. Model names must be in the format <app_label>.<model_name>.
```

The use case is reindexing all the models of a plugin after adding SearchIndex for my models.

### Expected Behavior

The command reindexes all the the models of the plugin/app corresponding to app_label.

### Observed Behavior

```
CommandError: Invalid model: dcim. Model names must be in the format <app_label>.<model_name>.
```

The current code does not allow selecting all the models of an app. ```registry['search']``` could be iterated to find all the models of the app if there is no dot in model_names, or simpler, the args of the command could be updated to remove that possibility.

https://github.com/netbox-community/netbox/blob/3675ad2539400038af6797140ddca3679b8bca30/netbox/extras/management/commands/reindex.py#L29-L40

**Comment by kkthxbye-code** [comment]
@Alef-Burzmali - All yours
