### ISSUE TITLE
Webfrontend with database in readonly mode

### ISSUE THREAD

**Issue by PieterL75** [netbox-community/netbox#11233]
### NetBox version

v3.3.9

### Feature type

Change to existing functionality

### Proposed functionality

The current 'Maintenance mode' ensures that no writes are done to the database. It also displays a banner that the instance is in maintenance mode.

I would like to have a 'ReadOnly' mode that
- like maintenance mode, prevents updates by logins.
- don't display a banner (custom banner can be set with the BANNER_TOP)
- don't do any database updates with the upgrade.sh script
- optionally: provide a message to the user if he tries to do a write operation, with info to the read/write
- optionally: use a separate database for session logs

### Use case

We use postgres WAL to create a almost-realtime readonly copy of our production database.
This can be used to poll data from with API calls and the GUI.

In order to maintain this node, we need to patch the upgrade.sh (remove database operation), but that breaks the git pull.
Also, that banner that is show is not relevant to the state of our instance. It is not in maintenance, it is in readonly.
The sessionpath is an option, but I would rather like to send that to a separate database (different postgresql server) to maintain the session state across webfrontends

**Comment by jeremystretch** [comment]
I'd really like to see this as well, however I'm not sure if we can elegantly hook into the database connection to catch and prevent write operations cleanly. Anyone have any ideas?

**Comment by talha700** [comment]
Same case here, we are using postgres streaming replication and setup up 2 instances of Netbox, It would be cool if user can login (we are using LDAP for remote auth) to replica instance of Netbox as read-only.

I'm still seeing logs after turning MAINTENANCE_MODE=True,  is it not supposed to update the last login etc... ? 

![Screenshot 2023-01-10 123633](https://user-images.githubusercontent.com/40869474/211490030-59891d44-70df-4daf-b589-44a338bc13d7.png)

**Comment by kkthxbye-code** [comment]
@talha700 - https://django-auth-ldap.readthedocs.io/en/latest/reference.html#auth-ldap-always-update-user

**Comment by abhi1693** [comment]
@jeremystretch Can I take a try at this? I have a solution which involves overriding `CursorWrapper` to raise exception in maintenance mode which in turn disallows write operations and gracefully informs the user via django message framework.

![image](https://user-images.githubusercontent.com/5083532/212469501-691cf4d4-ccb4-4a88-9348-bf975680abd9.png)

**Comment by abhi1693** [comment]
I don't have a setup for that yet so I cannot say

**Comment by pycolas** [comment]
I am also interested with this feature.
A primary netbox instance where read/write operations are possible on sensitive network, and some read only instances reachable from less sensitive networks in the company (or in remote offices with huge latency with central).

Django as a database router functionnality. Maybe it can help in order to separate R/W operations for frontend user experience, and read operations for models storage ?
Or maybe in my usecase I can simply declare users with no write privileges at all.
