### ISSUE TITLE
New search feature: vid doesn't match when queried

### ISSUE THREAD

**Issue by cs-1** [netbox-community/netbox#11232]
### NetBox version

v3.4.1

### Python version

3.8

### Steps to Reproduce

1. Create a VLAN with vid 1234.
2. Search for "1234" in search field.

### Expected Behavior

A search for "1234" should yield the created VLAN in the results.

### Observed Behavior

VLAN 1234 isn't found.

I've looked at the new search mechanism in > v3.4.0 and at least in [netbox/netbox/ipam/search.py](https://github.com/netbox-community/netbox/blob/93685d92a40de88688b24ab7150d549275b236e9/netbox/ipam/search.py) I can find

```python
@register_search
class VLANIndex(SearchIndex):
    model = models.VLAN
    fields = (
        ('name', 100),
        ('vid', 100),
        ('description', 500),
        ('comments', 5000),
    )
```

which means that `vid` should be used as "Primary human identifier" to find the VLAN. But it reproducibly doesn't  work.

**Comment by cs-1** [comment]
P. S.: Changing the Lookup from "Partial match" to "Exact match" will give me a result for "1234". Is this a typing issue (string vs. integer) in partial matching?

**Comment by kkthxbye-code** [comment]
> Is this a typing issue (string vs. integer) in partial matching?

Looking at the code, it's an intended choice.

https://github.com/netbox-community/netbox/blob/3675ad2539400038af6797140ddca3679b8bca30/netbox/netbox/search/backends.py#L102-L104

I'm guessing the idea is that it would be annoying searching for e.g. VLAN 20 and then getting all VLAN's with 20 somewhere in the number string. @jeremystretch would have to weigh in here though.

**Comment by cs-1** [comment]
It would be helpful to have partial searches for VLAN IDs as well (as it used to be in v3.3.10 and earlier.

**Comment by PieterL75** [comment]
partial vlan id's are something that I use.. regex would even be better. I would like to search for a free vlan starting with 301 (so 3010-3019), that whould work with '301' and it would be awesome to work with regex 300[0-9]

**Comment by cs-1** [comment]
> Correct; that was the design intent. Imagine trying to search for VID 1 and receiving results for all VIDs containing a 1.

But using the "Exact match" option will prevent this and "Partial match" not doing what it says it does for vids is counterintuitive. I agree with @PieterL75, we use "Partial match" regularly to get tons of results because we actually use "Partial match" as an intended feature. Partial match was the default search behaviour in NetBox v3.3.x and earlier so we've been using it on a day-to-day basis for VLAN searches being fully aware that it'll produce tons of results when only entering partial vids.

> I agree regular expressions are best suited for this use case. Incidentally, regex search _should_ work for this, but accommodations for the existing logic were overlooked during the implementation of #11090. It's an easy fix.

Regex would be great, too. However, my request would be to enable "Partial match" for vids because the other use case is already covered by the "Exact match" option.

**Comment by jeremystretch** [comment]
Ok, we'll try enabling partial matching and see how it works out. Worst case, we can have the option of falling back to regex for more intelligent matching.

> Partial match was the default search behaviour in NetBox v3.3.x and earlier

This is incorrect. The legacy search function used a variety of different lookups, each specific to the particular field being queried on each model. VLANs, for instance, would only match on complete VID values, just as the new global search does currently.

**Comment by cs-1** [comment]
> Ok, we'll try enabling partial matching and see how it works out. Worst case, we can have the option of falling back to regex for more intelligent matching.

Thanks, it's highly appreciated!

> This is incorrect. The legacy search function used a variety of different lookups, each specific to the particular field being queried on each model. VLANs, for instance, would only match on complete VID values, just as the new global search does currently.

Huh! You're right! I mixed vids up with our internal site numbers that are part of the "name" field (a string field which is partially matched). I'm terribly sorry. I now realise that what got us stumbling was the fact that you didn't get any match for VLAN 1234 in v3.4.x when entering "1234" in the search field when doing a "Partial match" search but only when doing an "Exact match" search. Sorry for the mixup.
