### ISSUE TITLE
Multiple unnamed device in same site isn't supported (dcim_device_unique_name_site)

### ISSUE THREAD

**Issue by ChrisdAutume** [netbox-community/netbox#11265]
### NetBox version

3.4.1

### Python version

3.9

### Steps to Reproduce

- Create several unnamed devices in the same site

### Expected Behavior

- Device are created and excluded from dcim_device_unique_name_site constraint

### Observed Behavior

Cannot create several unnamed devices in same site.

**Comment by PaulR282** [comment]
I couldn't reproduce it. Just creating 2 unnamed devices that are identical in the same rack or as non-racked worked for me.

**Comment by Bierfass** [comment]
I also couldn't reproduce it in our testing.

**Comment by ChrisdAutume** [comment]
Well, to be more precise. It's happening during migration process when django is applying the new constraint. I checked through psql
```
netbox=# select lower(name::text), count(*) from dcim_device group by lower(name::text) having count(*) > 1;
 lower | count 
-------+-------
       |  1100
       |   201
(2 rows)

```

**Comment by Bierfass** [comment]
Looks like the same issue #11266 and is very likely relating to the breaking change in 3.4.0 see (https://github.com/netbox-community/netbox/releases/tag/v3.4.0)

> - Device and virtual machine names are no longer case-sensitive. Attempting to create e.g. "device1" and "DEVICE1" within the same site will raise a validation error.

**Comment by ChrisdAutume** [comment]
I founded out that somes devices names was empty but not null in the DB.

`update dcim_device set name=NULL where name='';`

Correct the problems.
