### ISSUE TITLE
Date/Timeset formatting is not working

### ISSUE THREAD

**Issue by mmfreitas** [netbox-community/netbox#11268]
### NetBox version

v3.4.1

### Python version

3.9

### Steps to Reproduce

1. Change date formatting in configuration.py to the following:

DATE_FORMAT = 'j N, Y'
SHORT_DATE_FORMAT = 'd-m-Y'
TIME_FORMAT = 'H:i:s'
SHORT_TIME_FORMAT = 'H:i:s'
DATETIME_FORMAT = 'j N, Y G:i:s'
SHORT_DATETIME_FORMAT = 'd-m-Y H:i'

2. Restart netbox, and verify that dates don't change at all. This was working on 3.3.9.

### Expected Behavior

Dates and timeset should be formatted as indicated in configuration.py.

### Observed Behavior

Dates don't change.

**Comment by jeremystretch** [comment]
This has been resolved for now by disabling localization (see #11271).
