### ISSUE TITLE
permit mixed case in dns_name field

### ISSUE THREAD

**Issue by olafhering** [netbox-community/netbox#11260]
### NetBox version

v3.3.7

### Feature type

Change to existing functionality

### Proposed functionality

As noted in #11220 all data arriving in the `dns_name` field are forced to lower case.
commit e1bca52d57440ceecded5387d35a82e17a77f845 gave no reason why it was done that way.

All hostnames, and also all FQDN, are meant for human consumption. A DNS zone admin is free to send any (valid) FQDN string for the reverse lookup of an IP address, which includes mixed case.

(DNS itself of course remains to be case-insensitive. The Net would be cumbersome to work with if the names were case sensitive...)

### Use case

My usage of netbox will include building the zone files for a DNS zone from data in a local netbox instance. This is currently blocking me because existing mixed-case strings would be corrupted, by being forced to be all lower case.

**Comment by jeremystretch** [comment]
> This is currently blocking me because existing mixed-case strings would be corrupted, by being forced to be all lower case.

DNS itself is case-insensitive. Why would you need store case-sensitive records?

**Comment by olafhering** [comment]
The command `host 1.2.3.4` will return `MyHostName.sub.dom.tld.` because such info is stored in the reverse zone of `sub.dom.tld`.
I would like to store such hostname in netbox verbatim, to be able to build the relevant DNS zones from netbox data.

**Comment by jeremystretch** [comment]
> to be able to build the relevant DNS zones from netbox data

This isn't a supported use case for the core NetBox application; the `dns_name` field exists merely as a means of correlation for external consumers. If you're interested in managing DNS records in NetBox, consider the [netbox-dns](https://github.com/auroraresearchlab/netbox-dns) plugin.

**Comment by olafhering** [comment]
Sorry, I already have my tooling to maintain dns.
Until the `dns_name` field returns verbatim data, I will use the existing `description` field, which returns the data entered into it verbatim.

**Comment by jeremystretch** [comment]
Sounds like you've found a solution that fits your needs then. I'll go ahead and close this out.
