### ISSUE TITLE
Allow selection of results to filter by model on new global search

### ISSUE THREAD

**Issue by mmfreitas** [netbox-community/netbox#11261]
### NetBox version

v3.4.1

### Feature type

Change to existing functionality

### Proposed functionality

First of all congrats on the new global search, amazing work!

In my opinion there is just a functionality missing that was very useful in the old search. 
In the old global search engine, I found very useful the fact that I could search for something and then use the provided button to filter the results for a specific model, and then update the provided results at once.

Is it possible to in the new global search, implement this funcionality? Maybe by adding a checkbox on the results and allow the selection to provide an edit for each model?

### Use case

Having a quick way to, from global search results, select multiple instances for updating or deleting records.

**Comment by jeremystretch** [comment]
What you're describing isn't really feasible under the new search engine, as results are now ranked by relevance without regard to object type. However, the legacy search behavior you describe is still available under each model-specific list view.

**Comment by mmfreitas** [comment]
> What you're describing isn't really feasible under the new search engine, as results are now ranked by relevance without regard to object type. However, the legacy search behavior you describe is still available under each model-specific list view.

I see, maybe it's just an issue of the user getting accustomed to this, the shortcut was very handy though!
Thank you for your quick reply. You may close this if you wish :)
