### ISSUE TITLE
Extend the use of natural ordering to additional models

### ISSUE THREAD

**Issue by JohannesKreuzer** [netbox-community/netbox#11279]
### NetBox version

v3.4.1

### Feature type

Data model extension

### Proposed functionality

Extend Virtualisation Cluster model to use natualsorting by the cluster name.

### Use case

Better sorting of the clusters without padding the numbers in the name.

**Comment by jeremystretch** [comment]
IMO it doesn't make sense to do this only for clusters. We use [natural ordering](https://stackoverflow.com/questions/5167928/what-is-natural-ordering-when-we-talk-about-sorting) for a few models in NetBox currently; namely sites, racks, devices, device components, VMs, and VM interfaces. This is accomplished by including a "hidden" `_name` field which stores a naturalized representation of the object's `name` suitable for database ordering.

While I'm not opposed to enabling natural ordering on other models, if we decide to do so, we should:

1. Re-evaluate the current implementation to determine if a better approach exists
2. Identify _all_ suitable models and implement the change on all
3. Ensure that the implementation is scalable (e.g. via a mixin class vs. explicit field definitions as we do currently)

**Comment by kkthxbye-code** [comment]
> * Re-evaluate the current implementation to determine if a better approach exists

Maybe we can use postgres collation as there is support for natural ordering.

We would have to create the collation in a migration with raw sql I assume, like:

```SQL
CREATE COLLATION natural_sort (provider = icu, locale = 'en@colNumeric=yes');
```

And then the collation can be specified on the field like:

```python
name = models.CharField(
    max_length=100,
    db_collation='numeric'
)
```

It also seems possible to specify it at query time.

**Comment by jeremystretch** [comment]
Collation definitely seems like the path forward, if it proves feasible. I recall going down this road a bit in the past but ran into limitations on older PostgreSQL versions. Django 4.2 drops support for PostgreSQL 11 (see #12237), so maybe that will free us up some?
