### ISSUE TITLE
tzdata error 'No time zone found with key America/Ciudad_Juarez'

### ISSUE THREAD

**Issue by nicoovh** [netbox-community/netbox#11277]
### NetBox version

v3.3.8

### Python version

3.9

### Steps to Reproduce

1. pip install -r requirements.txt
2. launch manage.py migrate with a plugin that has date related fields
3. error happens:
``zoneinfo._common.ZoneInfoNotFoundError: 'No time zone found with key America/Ciudad_Juarez'``

seems related to many previous raised bugs, usually fixed by pinning tzdata in requirements.txt
due to the new release of tzdata/pytz 2022.7 

### Expected Behavior

application shall not crash

### Observed Behavior

application crash

**Comment by jeremystretch** [comment]
> launch manage.py migrate with a plugin that has date related fields

I'm afraid we can't accept such a vague bug report. If you're able to reproduce the reported behavior in NetBox itself, please update your description above and I'll be happy to reopen it. However, if this bug is related to the installation of a particular plugin, you'll need to submit a bug report to its maintainer.

**Comment by cpmills1975** [comment]
I've hit this issue today trying to run vanilla NetBox 3.2.8 in the official python:3.11 container (I'm trying to write some unit tests for my own plugin code). While it's likely an issue with the container/python installation more than it is NetBox, installing tzdata==2022.7 as suggested did fix it and pinning it in requirements.txt would be a minor change I'd suggest.

**Comment by Millnert** [comment]
Hit the same issue while updating from 3.0.1 towards 3.4.2 (through 3.1.0, 3.2.0, 3.3.4), no plugins present.  It hit on the 3.2.0 step. bumping tzdata from 2022.1 to 2022.7 in requirements.txt solved the problem here as well.
