### ISSUE TITLE
Error when saving device position

### ISSUE THREAD

**Issue by PaulR282** [netbox-community/netbox#11272]
### NetBox version

v3.4.1

### Python version

3.10

### Steps to Reproduce

1. Open Netbox in chrome (it works in firefox)
2. Go to a device 
3. Click edit. The position should say something like UX.0
4. Click save without changing anything

### Expected Behavior

The device should be saved with the position UX.0 or UX

### Observed Behavior

The UX.0 gets transformed to UX,0 which can't be saved and an error occurs.

**Comment by arthanson** [comment]
Just a note, this is related to internationalization (the browser being set to a locale with commas as a separator) - Floats are output with localized decimal separator.

**Comment by jeremystretch** [comment]
This has been resolved for now by disabling localization (see #11271).
