### ISSUE TITLE
Change width, depth and weight fields from integer to decimal

### ISSUE THREAD

**Issue by mmfreitas** [netbox-community/netbox#11281]
### NetBox version

v3.4.1

### Feature type

Change to existing functionality

### Proposed functionality

Currently max weight and mounting_depth fields in the racks model are integer values, while rack weight is a decimal value.
Values related to width, depth and weight should be decimal to provide an accurate representation of the object.

![image](https://user-images.githubusercontent.com/91552302/208964890-55e86e0d-10fe-462d-8535-f1d032e2f978.png)

### Use case

In our Data Center we have racks which have a mounting depth of 72.2 cm for example. The use case is to record this information accurately.

### Database changes

Change of these fields from integer to decimal?

**Comment by danner26** [comment]
Just a heads up, weight is a decimal:
```
weight = models.DecimalField(
        max_digits=8,
        decimal_places=2,
        blank=True,
        null=True
    )
```

**Comment by mmfreitas** [comment]
> Just a heads up, weight is a decimal:
> 
> ```
> weight = models.DecimalField(
>         max_digits=8,
>         decimal_places=2,
>         blank=True,
>         null=True
>     )
> ```

Yes, sorry. I meant maximum weight as decimal, as you can see in the image above it is not rendered in decimal.

**Comment by jeremystretch** [comment]
> In our Data Center we have racks which have a mounting depth of 72.2 cm for example. The use case is to record this information accurately.

A rack's mounting depth is measured in millimeters, so you would enter a value of 722. And there should be no need to ever declare fractional units for a rack's maximum weight (which is itself always a conservative estimate).
