### ISSUE TITLE
Cluster usage fields

### ISSUE THREAD

**Issue by abhi1693** [netbox-community/netbox#11296]
### NetBox version

v3.4.0

### Feature type

Data model extension

### Proposed functionality

Add new fields for CPU, memory, and disk to the cluster model. When a user views the cluster page, they should see the current usage vs total allocated in human-readable form. The usage fields can be cached fields or computed fields and should not be editable directly by a human.

Similar information should be provided over the API (maybe using bytes?).

The fields can remain optional to provide backward functionality.

### Use case

When clusters are created for virtualization, they need to be planned with the what devices they will contain and how much total capacity is required. When the cluster is put into use, over time the capacity starts to deplete based on the virtual machines deployed within the said cluster. It will be helpful from the perspective of capacity planning to get the current usage vs total usage in both the UI and the API.

### Database changes

`vcpus` - positive integer, optional, help_text=total allocated vcpu
`memory` - positive decimal, optional, help_text=total allocated memory
`disk` - positive decimal, optional, help_text=total allocated disk

**Comment by zmaster7** [comment]
I would almost say having cpu, memory, disk as fields on a device level would make more sense, and have it calculate the totals at the cluster level as hosts are added/removed from the cluster. However, it seems adding these fields have been brought up before under #6743, and wouldn't apply to all devices.
