### ISSUE TITLE
Costum Links: Change single Content Type Field to multipe Content Types Field

### ISSUE THREAD

**Issue by ShellBoyAFK** [netbox-community/netbox#11298]
### NetBox version

v3.9

### Feature type

Change to existing functionality

### Proposed functionality

My wish would be that the Content Type field under Costum Links behaves exactly like the Content Types field under Costum Fields

Costum Fields
------
1. Click Other
2. Click Custom Fields
3. Click Add
4. Click Model(s)* 
5. Add some Model(s)* (Content types) 👍 

In Costum Fields you can assign a field to multiple Content Types. 

Costum Links
------
1. Click Other
2. Click Custom Links
3. Click Add
4. Click Content type
5. Add a single Content Type 👎 

In Costum Links you can only assign one Content Type in the field. 
------

### Use case

We have several links to our external documentation (3rd party systems) like internal wiki website or web management tools and read out the data via Jinja2 script and transfer them via costum link to the external website to open the Link in for example Wiki. 

We do this in meanwhile >16 menus (views) in Netbox. Unfortunately we have to create the same costum link over and over again. This is extremely annoying because the clone button never copies the link text and the script. 

Maybe others have this case too

### Database changes

?

### External dependencies

?

**Comment by kkthxbye-code** [comment]
This was already added in 3.4.0

**Comment by ShellBoyAFK** [comment]
okidoki 
Thx
