### ISSUE TITLE
Cable Trace - Fix cable name truncation

### ISSUE THREAD

**Issue by brainsfull** [netbox-community/netbox#11299]
### NetBox version

v3.4.1

### Python version

3.8

### Steps to Reproduce

1. Click on a cable trace with a cable that has a long cable name. 

### Expected Behavior

The full cable name would be visible and not truncated. The cable name would either:

- be fully visible on a single line (preferred)
- use wrap text to show the full cable name on 2 or more lines. 

### Observed Behavior

When this occurs the cable name is truncated as can be seen in the example below:
![image](https://user-images.githubusercontent.com/7419642/209333814-fb133727-2472-4cc5-a78f-af881fcee7c9.png)

**Comment by kkthxbye-code** [comment]
Duplicate of https://github.com/netbox-community/netbox/issues/8450
