### ISSUE TITLE
when use api to change the ipam prefix custom fields, the change can't be displayed on the web. 

### ISSUE THREAD

**Issue by zhufall** [netbox-community/netbox#11309]
### NetBox version

v3.3.9

### Python version

3.10

### Steps to Reproduce

when I use the API to set the value for one prefix in custom fields and has checked using API, it looks like working well. 
but, when I go back to check the web, the custom fields of the prefix still display the original state, with nothing to change. 
<img width="1253" alt="20221226211437" src="https://user-images.githubusercontent.com/60817674/209553054-45300ae6-80c8-4708-926e-aa60e386536c.png">
<img width="1631" alt="20221226211600" src="https://user-images.githubusercontent.com/60817674/209553060-cb14cca7-aad2-45fd-99ab-7d2c35301339.png">

### Expected Behavior

the web displays the change when the API finished 

### Observed Behavior

with nothing changed on the web.

**Comment by kkthxbye-code** [comment]
Please provide proper replication steps and make sure you replicate it on the newest version (4.0.1).

**Comment by markkuleinio** [comment]
In the screenshot there is no command even attempted to save the custom field change to NetBox API, so this is not a NetBox issue with that information.

**Comment by hagbarddenstore** [comment]
@zhufall You're missing `w.save()` as the last thing.

**Comment by jeremystretch** [comment]
Closing this out as there's insufficient detail to warrant a bug report and there has been no further response from OP.
