### ISSUE TITLE
Open custom URL fields in a new window/tab

### ISSUE THREAD

**Issue by ShellBoyAFK** [netbox-community/netbox#11300]
### NetBox version

v3.3.9

### Feature type

New functionality

### Proposed functionality

Costum Fields

1. Click Other
2. Click Costum Fields
3. Click Add
4. Add some Mockup Data for Testing. In my Case i select "DCIM > Sides" for example under Models and Name "Test Website".
5. Click Type and select "Type" to URL
6. Click Save
7. Click Organization 
8. Click Site (my Case)
9. Select a random Site in your List and click on it
10. Click on Edit Button  
11. Fill a URL unter Custom Fields like xmas.shellboy.org
12. Click Save
13. Click on the Link now my Site (XMAS greetings surprise for all Netbox Issue reader)  opens in the same windows as netbox 👎 

### Use case

Realy Clear or?

It would be really nice if there would be the possibility that the link also (as with Costum Link) opens in a new window. So that Netbox does not fall out of focus. 

### Database changes

?

### External dependencies

?

**Comment by jeremystretch** [comment]
One thing I've learned from previous issues is that people generally dislike having a new tab or window forced upon them in any scenario. IMO it would be better to always let the user opt to open the link in a new tab (e.g. by control-clicking).

**Comment by ITJamie** [comment]
There is an option for that in the custom links objects already... feels odd that the same wasnt added to the URL custom field type. that we would argue that forcing open in a new window/tab be allowed for the custom links is ok but not a url custom field is a bit odd

It would be nice to have a config option on url custom fields to change the default url target for that specific custom_field.

**Comment by ShellBoyAFK** [comment]
I can not understand the agumentation of Jeremy?

If I offer the option "open in new window" under "custom links" and under  "custom field" under URL not..... how consistent i'am? Sorry.

It's about how a user uses the program. In my experience I want to open a link in a new tab and then click on another device in Netbox and click again on the same link and it opens again in a new tab. This is my naive stupid expectation from a program which is used for documentation purposes. Maybe the user wants to go back to Netbox to look at something else. 

We use this for example to open a MediaWiki entry about this object, or the website of the customer from this site/tenant, or a search link in WEBAPP A or B or C if the same device role is set . Then the user wants to go back to Netbox and clicks on the next object or simply closes the tab after work is done and is back in netbox. Isn't it nice? Right Click "open link in a new Tab" is useful. It is only an option, no more and no less. 

If the user (netbox admin) would like to open everything in the same window. good it's done - feature is still there 
If the user (netbox admin) would like to open the link in another window. - Sorry my dear.  Make right click on the link and select "Open Link in a New Window". ----- "Hey but in Costum L..." "Yes my friend i know...  that's ... a thing... you know"

**Comment by jeremystretch** [comment]
> I can not understand the agumentation of Jeremy?

The user already has the option of opening any link in a new tab or window. By forcing a link to open in a new tab, you are removing that choice from them.

**Comment by ShellBoyAFK** [comment]
Question!
Why is the Option in Custom Links?

**Comment by ShellBoyAFK** [comment]
Bad idea but ok

**Comment by jeremystretch** [comment]
I guess we'll see: #11446

**Comment by ShellBoyAFK** [comment]
and now? same feature as Costum links?

**Comment by jeremystretch** [comment]
Opposition to removing existing functionality does not equate to justification for replicating that functionality elsewhere. I remain convinced that the described behavior should be discouraged for all the reasons I cited in #11446 and won't be taking action on this FR, but you're welcome to convince another maintainer.

**Comment by PieterL75** [comment]
I think that it is upto the company to decide if they want links to open in a new tab or not.
Our way of working is, that links to the same application (NetBox) remain in the same tab. But links to external applications (zabbix, observium, servicenow, ...) open by default in a fresh tab. 
So having this option there is providing flexibility to owner of the application to decide if they want to open links in a new tab or now.

**Comment by ITJamie** [comment]
can this be re-opened? Ive made a PR for it. #12753

**Comment by ShellBoyAFK** [comment]
Can this be re-opened? It is still a problem for my users. Thx

**Comment by ShellBoyAFK** [comment]
https://github.com/netbox-community/netbox/pull/12753#issuecomment-1567505876

Nice Idea @ITJamie. Looks great!
