### ISSUE TITLE
Add bulk import for Contact Assignments

### ISSUE THREAD

**Issue by stavr666** [netbox-community/netbox#11307]
### NetBox version

v3.4.1

### Feature type

New functionality

### Proposed functionality

Add bulk import functionality for Contact Assignments.

### Use case

We use contacts to describe the following entities:
- Physical server owner;
- Virtual server users (from business-PoV);
- Financially responsible unit (for any type of assets);
- On-site and competence-related engineers;
- External support/contractors;
- Maintenance notifications targets (this one currently in json file on Git, but transition in process).

Often it turns out, that some contacts changes over time or server usage scenarios changed. So, bunch of assignments must be updated.
For some reason, there is no way to do it in UI, only by API.

**Comment by jeremystretch** [comment]
> Add UI-way (user-friendly) to bulk-add and bulk-update for Contact Assignments.

Please provide more detail in your proposal. What is the specific workflow you envision? What new UI controls, if any, will be needed to accomplish this?

**Comment by stavr666** [comment]
> What is the specific workflow you envision? What new UI controls, if any, will be needed to accomplish this?

Dunno how your code build (or if it's actually hard to make), but from user's perspective result must look pretty similar to Interfaces panel in Devices/VMs, in Tenant Section.

We already have Contact Assignment in api, just add it's representation in GUI. As result, all already working in GUI flows with bulk change/remove/update for interfaces must work similar for Assigned Contacts, with (almost) same "object" field, bunch of filters (by role, by group, by priority) and ability to change or upload list of updated/new assignments. ID of assignment as key, object not changeable. Contact, role, group and priority updatable.

**Comment by jdavidson2021** [comment]
Would it be possible to extend the field import list on the racks, devices, and virtual machine imports to include contact_name, contact_group, contact_role, & contact_priority as optional fields (similar to tenant assignments)?  This would allow for the contact assignments to be created or updated via import since we can now update objects via import.

**Comment by stavr666** [comment]
Looks like #11584 added working assignment view to 3.5.0. Export also seems fine.

@jeremystretch any chance, someone will work on adding import/update functionality to this view in nearby future?

P.S. Add button not working [on demo](https://demo.netbox.dev/tenancy/contact-assignments/add/), it's internal bug or global?

**Comment by jeremystretch** [comment]
This has been open for months without any real implementation proposed. @stavr666 would you like to revise your proposal above with sufficient detail, or should we close this out?

**Comment by stavr666** [comment]
> without any real implementation proposed

I'm sorry, missed the point, that my FR not readable (does not involved in other projects as much, as Netbox, you improving really fast).

I see realization of Import (with Update) UI similar to how it works with Cables.

While Importing, we must have:

- **Object Type** - required
- **Object** - required
- **Contact** - required
- **Role** - optional if update, required if create new
- **Priority** - optional
- **ID** - optional, indicating update logic

**Comment by jdavidson2021** [comment]
I didn't get a reply to my previous comment.  Is this possible?

Would it be possible to extend the field import list on the racks, devices, virtual machine, and tenant imports to include contact_name, contact_group, contact_role, & contact_priority as optional fields (similar to tenant assignments on devices/racks)? This would allow for the contact assignments to be created or updated via import since we can now update objects via import.

Also, the Add button on Contact Assignments on the Demo gives you the following error:

/tenancy/contact-assignments/add/
The requested page does not exist.

**Comment by opericgithub** [comment]
Just to summarize my other post which was rejected due to this similar post:

```
"Currently there is no gui possibility to bulk-assign many contacts to many objects. The only way we have found is by directly modifying database with "insert into tenancy.contact (...) values (...)(...) etc " which may be very hazardous.

There should be an gui option to link the ID of the contact with the ID of the object, let's say a device.

Use case
We have thousands of devices representing physical IP phones, and also have thousands of contacts, each of them representing the phone number of the IP phone.

We would like to link all of the contacts to all of the devices, but there is no way to do that by bulk editing (importing) devices because there is no available contact field option.

If such field existed, it would be easy to link let's say a list of device id's with a list of contact id's.

As for now, we have to edit thousands of devices one-by-one and click "add a contact" button on every single one of them."
```

So, it seams that this functionality might be implemented in "contact assignment" section of netbox, where you could allow a button for importing values from csv file. Relevant table columns should be object-id, contact-id, contact-role-id (because it's now required in gui assignment) and object-type-id (so one could define whether he is assigning contacts to devices or tenants etc).

Is this enough info or do you need more details?

**Comment by opericgithub** [comment]
> We already have Contact Assignment in api, just add it's representation in GUI.

@stavr666 can you please explain to us in detail how did you assign contacts via api ?

**Comment by stavr666** [comment]
@opericgithub 
![image](https://github.com/netbox-community/netbox/assets/84839985/3aefb136-d7e4-40e7-ac5c-00d8a3fab27d)

**Comment by opericgithub** [comment]
Thanx @stavr666.

As Dakson13 pointed out, there are few fields that can be used in GUI "contact assignment" section, to assign contacts to objects. Combined with this stavr666's API screenshot, those fields would be: "content_type_id", "object_id", "contact_id", "role_id" and maybe priority. 



> Is this enough info or do you need more details?

@jeremystretch I'm sorry, maybe I wasn't clear enough, this question above was meant for you :)

**Comment by abhi1693** [comment]
Please update your description with the proposal.

**Comment by opericgithub** [comment]
> Please update your description with the proposal.

"contact assignment" section (organization ->  contacts -> contact assignment) should have a new import button, which will allow to bulk import (and probably also update) contact assignments via CSV file. Relevant fields should be: "content_type_id", "object_id", "contact_id", "role_id" and maybe "priority".

**Comment by kkthxbye-code** [comment]
I think we can accept this if it is for the bulk import, that is csv/json/yaml import/update, however the original FR makes it sound like an UI view (i.e. a form) is what is requested. @stavr666 could you clarify the original post?

**Comment by stavr666** [comment]
> the original FR makes it sound like an UI view (i.e. a form) is what is requested

We need a way to upload dozens contacts in UI, so adding/updating can be delegated in Netbox (without API-related code).

The way it works with interfaces totally fine:
![image](https://github.com/netbox-community/netbox/assets/84839985/4fc4088c-2261-490d-a747-9cebb7c5b20b)

**Comment by kkthxbye-code** [comment]
I've accepted this with the caveat that I don't know if there's any good reason why it can't be done easily. The accepted FR is only for the bulk import view, that is csv/json/yam import+update.

Open for volunteers.
