### ISSUE TITLE
"Connection" not showing on Interfaces tab anymore?

### ISSUE THREAD

**Issue by markd69** [netbox-community/netbox#11304]
### NetBox version

v3.4.1

### Python version

3.10

### Steps to Reproduce

1. Visit the Interfaces tab on any device/server
2. At any interface that should have a "Connection" there should be a connection that is shown for example to a switch or to another device

### Expected Behavior

There should be a Connection that is shown that is connected to another device, switch, etc.

### Observed Behavior

It shows a "-" instead of the proper connection
<img width="667" alt="image" src="https://user-images.githubusercontent.com/44349634/209394986-1a29def7-d569-4a04-8384-ec1bddac5702.png">

**Comment by kkthxbye-code** [comment]
Please provide proper replication steps. I cannot replicate it from your description.

**Comment by jeremystretch** [comment]
Closing as OP has not provided any further detail.
