### ISSUE TITLE
Representation of data in YANG format

### ISSUE THREAD

**Issue by misch42** [netbox-community/netbox#11338]
### NetBox version

v.3.3

### Feature type

New functionality

### Proposed functionality

Hi,

I asked this feature in issue #4318 for a data representation in YANG format.

From my question on the community day I open this issue again.

### Use case

Modern devices can be configured with data in YANG representation direct. So it would be cool to have a API entry point to gather the device data direct in YANG format. Configuration of devices or elements of devices could be applied directly  without the need of re-formatting the data in ansible or saltstack.

This will make the configuration of devices out of netbox much easier.

### Database changes

none.

### External dependencies

none

**Comment by jsenecal** [comment]
Hi @misch42, did you have any implementation details in mind for this? As mentioned in the previous [issue](https://github.com/netbox-community/netbox/issues/4318#issuecomment-598508587) this is quite the undertaking.

**Comment by misch42** [comment]
I can imagine that this is a quite big task. On the other hand the reward would be quite interesting. I thought about a secondary API entry point that shows all the data in YANG format. Like https://netbox/api/yang/interfaces/42/.

A config management system could use these data direct and push this config via netconf to the device.

At the moment ansible or saltstack has to re-format the data from the netbox api into a format the the device understands.

An additional advantage would be that the config data of devices in YANG format in an ideal world would NOT be manufacturer dependent any more. A management system could push the config for the same device today to a device of manufacturer A and tomorrow to a device of manufacturer B.

Michael.
