### ISSUE TITLE
Broken progress bars

### ISSUE THREAD

**Issue by rendxq** [netbox-community/netbox#11332]
### NetBox version

v3.4.1

### Python version

3.10

### Steps to Reproduce

In 3.4.1 was broken progress bars in different tables. Let me show this problem at pictures way
![image](https://user-images.githubusercontent.com/27946443/209907422-3e83d971-332f-46e7-b6ee-5d0e52842a12.png)

### Expected Behavior

Expecting that progress bar is filled according to calculated values

### Observed Behavior

In 3.4.1 I see progress bar doesn't match with calculated values.
50% looks like 25%

**Comment by jeremystretch** [comment]
This results from enabling localization, and has been captured under #11271.
