### ISSUE TITLE
 Reverse for 'sitegroup-trace' not found. 'sitegroup-trace' is not a valid view function or pattern name.

### ISSUE THREAD

**Issue by arthanson** [netbox-community/netbox#11348]
### NetBox version

v3.4.1

### Python version

3.8

### Steps to Reproduce

1. Load the demo data (https://github.com/netbox-community/netbox-demo-data)
2. Go to device "dmi01-akron-rtr01" Interfaces tab
3. For "GigabitEthernet0/0/0" click the trace button

### Expected Behavior

A valid trace should appear

### Observed Behavior

NoReverseMatch at /dcim/interfaces/1/trace/
Reverse for 'sitegroup-trace' not found. 'sitegroup-trace' is not a valid view function or pattern name.

**Comment by jeremystretch** [comment]
Seems like we have some corrupt data in the v3.4 demo dump, as the content types for many path objects are invalid. I'll regenerate the demo data.

**Comment by jeremystretch** [comment]
Ok, figured it out. Something in the v3.4 migrations (likely the introduction of a new model) has skewed some of the content type IDs from what they previously defaulted to, resulting in invalid object references within cable paths. 

Unfortunately there's no good way to ensure consistent content type IDs with the current import/export process we use to generate the demo data. I'll need to look into this some more. I'm going to close this out and track work toward a solution under [this issue](https://github.com/netbox-community/netbox-demo-data/issues/6) as this isn't technically a NetBox bug.
