### ISSUE TITLE
Bulk import Interface Templates from API

### ISSUE THREAD

**Issue by AlexandrePoix** [netbox-community/netbox#11356]
### NetBox version

v3.4.1

### Feature type

Change to existing functionality

### Proposed functionality

Bulk import interfaces in interface-templates from the API as it is in the web interface. See screenshots attached.
Exemple 0/[0-23]
1 : import from the web interface
2 : result form web interface
3 : import from API
4 : result from API
![image](https://user-images.githubusercontent.com/115186238/210236469-1214e39d-cac4-44f5-8ea4-bfd25a885df5.png)
![image](https://user-images.githubusercontent.com/115186238/210236498-cb3c1779-ee6c-45d3-b49e-d9493d5927ec.png)
![image](https://user-images.githubusercontent.com/115186238/210236573-9c529033-1ba0-4b03-b6ea-d5b56c36be3c.png)
![image](https://user-images.githubusercontent.com/115186238/210236620-47d60ab3-42d8-4410-abfb-53de7dad2f3d.png)

Thank you.

### Use case

Make the import of interface-templates easier from the API.

**Comment by jeremystretch** [comment]
Bulk creation is already supported. Please see [the REST API documentation](https://docs.netbox.dev/en/stable/integrations/rest-api/#creating-multiple-objects).

**Comment by AlexandrePoix** [comment]
In that case being able to create an interface named 0/[0-23] from the API and not the web interface is a bug no ?

**Comment by jeremystretch** [comment]
No, it's not a bug. The REST API and UI are two entirely different interfaces, each with their own design logic. Again, if you familiarize yourself with the API documentation this will become clear.
