### ISSUE TITLE
API can't get vlangroups information

### ISSUE THREAD

**Issue by zhufall** [netbox-community/netbox#11364]
### NetBox version

v3.3.9

### Python version

3.10

### Steps to Reproduce

when using API to get the vlangroups information, but get nothing 
<img width="1248" alt="20230103170410" src="https://user-images.githubusercontent.com/60817674/210327098-0d5659df-9127-4a25-978b-787346d31998.png">
<img width="1024" alt="20230103170035" src="https://user-images.githubusercontent.com/60817674/210327113-c75ed712-8d21-4ac8-8514-0144c147014c.png">

### Expected Behavior

get vlangroups information like get vlans , could have all the vlan groups information. 

### Observed Behavior

use 'nb.ipam.vlangroups.all()' can't get the vlan groups information.

**Comment by kkthxbye-code** [comment]
It's `vlan_groups` not `vlangroups`.

`nb.ipam.vlan_groups.all()`

In the future if the issue is with pynetbox, please remember to [create the issue in that repo](https://github.com/netbox-community/pynetbox).
