### ISSUE TITLE
Global search does not return parent prefix for a non-existing IP address in Netbox

### ISSUE THREAD

**Issue by erdems** [netbox-community/netbox#11378]
### NetBox version

v3.4.2

### Python version

3.8

### Steps to Reproduce

1. Create a prefix, for instance 10.11.12.0/24.

2. Search for 10.11.12.100 in global search

### Expected Behavior

When 10.11.12.12 is searched, the parent prefix of 10.11.12.0/24 should be returned as a result, as it was done in previous versions of Netbox.

### Observed Behavior

The search does not return a result.

**Comment by kkthxbye-code** [comment]
Duplicate of https://github.com/netbox-community/netbox/issues/11378

**Comment by erdems** [comment]
Hello again, I'm sorry if I've missed a duplicate but this one is 11378 so the mark is a bit confusing.

**Comment by kkthxbye-code** [comment]
@erdems - Sorry, I must have copy pasted wrong. This is the duplicate:

https://github.com/netbox-community/netbox/issues/11315
