### ISSUE TITLE
globalsearch: search result view: ordering results by object_type not working

### ISSUE THREAD

**Issue by ITJamie** [netbox-community/netbox#11383]
### NetBox version

v3.4.2

### Python version

3.10

### Steps to Reproduce

goto: https://demo.netbox.dev/search/?q=100
press "Type" on the search results table header, results do not re-order

### Expected Behavior

objects to be grouped together by object type when sorted by object_type. instead "field" seems to take precidence

### Observed Behavior

Some of the same object types are split apart, eg on the demo site some of the device types are separated, also when you try and order in reverse the order does not seem to change.

In our internal instance we sometimes see devices intermingled with other objects. 

sorting by "field" works as expected, sorting by "type" does not and seems to fallback to sorting by "field"

**Comment by ITJamie** [comment]
still an issue as of v3.4.5

**Comment by decoupca** [comment]
Spent some time in the debugger looking through the result object list, but I couldn't find a single accessor that works across all search result object types. Any accessor I pass to `order_by` only works on a subset of results, i.e., some of the results are ordered alphabetically like you'd expect, but others aren't. And as far as I can tell, there is no way to provide conditional accessors to `order_by`. Unless I missed a universal property/accessor that renders an object's name across all object types, the only solution I see would be to add such a universal property/accessor to all object types, but that's clearly beyond the scope of this issue.

I have the original issue resolved. @kkthxbye-code do you want me to move forward with that as a PR and leave object sorting as a separate bug, or do you have another idea on how to take care of object sorting too?

**Comment by decoupca** [comment]
@jeremystretch care to weigh in here? I can submit a PR for the original bugfix & open a new issue but wanted maintainer input first.
