### ISSUE TITLE
Cannot Search Custom Field on Inventory Items via DCIM/Devices

### ISSUE THREAD

**Issue by dwi2214** [netbox-community/netbox#11399]
### NetBox version

v3.4.2

### Python version

3.9

### Steps to Reproduce

1. Create Custom Field 
    - name: "Disk_Condition" 
    - content types: "DCIM > Inventory Items"

2. Open DCIM Devices (ex: 27), 
3. Add Component -> Add a new inventory item
![image](https://user-images.githubusercontent.com/116805958/210741428-e0713b2e-1cb4-4183-b6e6-2510ff739d3f.png)

4. Add name "Disk" and Scrolling down Custom Field "Disk_Condition" -> Input "Degraded"
![image](https://user-images.githubusercontent.com/116805958/210741196-db87706b-ad01-4434-aa23-46a043308ab5.png)

5. Open https://demo.netbox.dev/dcim/devices/ and search "Degraded"
![image](https://user-images.githubusercontent.com/116805958/210741304-26364fb3-c4f3-4d81-9f83-9489bf60dde0.png)

### Expected Behavior

(example) Devices "dmi01-akron-pdu01" is it possible to show on search result

### Observed Behavior

When I trying moving "Degraded" from custom_field "Disk_Condition" to field "Serial", found result

Moving to "Serial"
![image](https://user-images.githubusercontent.com/116805958/210742690-60747aef-925c-472e-87c8-7dd58c7bb553.png)

Retry search
![image](https://user-images.githubusercontent.com/116805958/210742064-32ef0f67-0666-4d3b-8c22-a04caffeba60.png)

I think why only "Serial" that searchable, is it bug or expected
Thank you!!

**Comment by jeremystretch** [comment]
This is expected behavior. The object filters do not match against custom fields. (Global search does, but only against directly relevant attributes; relations to other objects are not considered for search.)
