### ISSUE TITLE
Display a floorplan of all racks in a site

### ISSUE THREAD

**Issue by fourg** [netbox-community/netbox#114]
Ability to drag and drop existing racks within a site to create their physical topology.  Bonus points for displaying how many free U's each rack has.

**Comment by bellwood** [comment]
I've already have this setup in a customeware application I wrote.

I make use of pgSQL's point coordinates for storing the location of racks, CRV's, UPS's on a grid and then displaying racks, birds eye with:

1) rack temp color adjusted by chromatic scale with a hover graph to show the last 10 temp points for trending

2) clickable icons for switches in the racks that modal to show interfaces, toggle control, port descriptions, vlan information

3) pdu's in the rack and the power they are consuming

4) crv's showing input and output temps and humidity

5) UPS input and output + battery state and runtime

**Comment by ryanmerolle** [comment]
A room / bird's eye view makes sense.  We may need to first address how to relate rooms, private cages, or floors in the same site.  You may want to only take a birds eye view by these sub-units/groups.

**Comment by bellwood** [comment]
Yes, you'd ideally want to limit the display to each "rack group" - which for us is a single containment pod but could be anything.

Realistically you are only limited to screen real-estate for what you want to show however there are other considerations if you want live data:

-will the data come live or from a stored system that is polling (like rrdtool)

-if its coming live, how many devices are you calling live and what impact that may have on your network

My implementation does everything live via ajax (we are relatively small) but at scale that simply doesn't work.

My thought for my next version was to use cacti to collect all the data and pull it to the interface with command line calls to rra's, however that means adding devices in two places and also doing all graph templating with cacti and a slew of other things.

It certainly would be an advanced implementation to add live/delayed data to the overview but not impossible.

Simply displaying the visual layout though is real easy, involving some CSS and placement decisions based on grid.

Each rackUnit (yeah bad name) in my pgsql table (which consists of 'types' e.g rack, gap, ups, battery, bypass, transformer, cooler, etc) has a "coord" field that is (x,y) and I display my rackUnits out where: 

0,0 is top left -> end of row
1,0 is bottom left -> end of row

...this is per rackGroup.

Based on the type and facility ID for those items I have CSS classes setup to handle the display for that item.

**Comment by ollyg** [comment]
I thought the idea of netbox is not to have live or polled data but to be an authoritative source of truth curated by a human. I would really like to see this feature but it need only be the room view exactly as @ryanmerolle said. Then we could browse down from the org level to each data centre space or room  and then down to the rack level.

**Comment by bellwood** [comment]
One of the tenants of netbox is to document things as they exist in the real world.

So auto-polling interfaces, assuming connections, etc is not done.

The temperature of a rack, of the runtime of a UPS battery string, are real world items and critical to DCIM.

My previous reply was simply shared to provide insight as to how I accomplished my needs for our software.

**Comment by Armadill0** [comment]
Awesome, searching for "map" instead of "overview" was to easy to find this issue, sorry. :smile:

**Comment by candlerb** [comment]
As well as "bird eye view" I'd also like a front and back view of all the racks in a site or rack group. At the moment you can only get this one rack at a time.

**Comment by snowie-swe** [comment]
Would be very nice to see a basic layout picture next to the rack

![image](https://user-images.githubusercontent.com/41901413/43674221-a870bb6a-97d0-11e8-9298-acbf6c04da7a.png)

**Comment by Ricaz** [comment]
@bellwood, have you made any further progress on this? Any work you would like to share? I'm looking at implementing this in our setup in the coming week.

**Comment by bellwood** [comment]
I have it working based on some static data, however, until FR #20 and #1044 are completed and we can move away from 6connect entirely Netbox remains a backwater project in my org.

<.02>Netbox really needs a version(s) dedicated to catching up on the legacy requests. </.02>

**Comment by ndom91** [comment]
Yeah I'd really like something like this as well - Im somewhat handy with front end web dev stuff as well so I am more than happy to help!

**Comment by tb-killa** [comment]
Hi @bellwood, have you made any further progress on this?

**Comment by tb-killa** [comment]
@jeremystretch: Question: Is this extension really implemented in Netbox (Core) or should it appear as an extension ?
I'm asking because the JS based site topology map was rejected back then (#1827) and this is ultimately a similar extension.

We would be happy if the floorplans would actually come.

**Comment by DanSheps** [comment]
@tb-killa #1827 is an extension to the topology map, this is more of a site rack/rack group layout, which is slightly different and more similar to the current front-view rack layout.

**Comment by tb-killa** [comment]
@DanSheps thanks for your answer.
This sounds nice.

**Comment by tb-killa** [comment]
Hi @jeremystretch:
I´m thinking about a simple solution to get this feature implemented:

First of all.. what is the exactly need of a "floorplan" ?
Normaly as we want to document "DataCenter" we doesn´t use the Term of "Floorplan" as we use the Term of DataCenterGrid.

How to build DataCenterGrid ?
I would use as simple as possible the function from bootstrap themselve to draw the "grid".
Maybe extension with allow upload of big background graphic?

But first .. on which point we could build our DataCenterGrid ?
We need a starting point with a input field who you could define number of rows and columns who define the "Size" of your DataCenter.
Does we use this on the "Site" or should we define a new Implementation with Django and call the App "DataCenter-Visualisation" ?
This need some Linkings too from Site and Rackgroup and Racks.

**Comment by Xelinor** [comment]
So, at least with my implementation, we use the logical name of the rack for the name, and the facility ID is the physical location within the data center grid. My understanding is that is fairly common practice: RackRow.Rack#

**Comment by GameMaster47** [comment]
Hi all,

Is there any advance to this feature?
We recently started to explore netbox as a replacement of a old in-house DCIM in our company and since we have around 50 to 80 racks per site, the ability to have a room plant with rack information and position in the room is something important.

**Comment by DanSheps** [comment]
Please do not ask for updates to feature requests.  They will be released when they are released.

**Comment by jeremystretch** [comment]
This is one of our oldest feature requests, and to be honest I just don't see it ever becoming a priority.

I'm going to close this out as a core feature request, however I do think it would make an excellent [plugin](https://netbox.readthedocs.io/en/stable/plugins/development/). Hopefully someone in the community will take interest in building it.
