### ISSUE TITLE
Exporting to CSV uses capitalized fieldnames but lowercase is required for import

### ISSUE THREAD

**Issue by fatman00** [netbox-community/netbox#11401]
### NetBox version

v3.4.2

### Python version

3.8

### Steps to Reproduce

1. Export Regions or Sites
2. Import it on another netbox instance
3. The import gives an error on the import with "Record 1 name: This field is required."
4. The export CSV creates a field called Name but the import expects the field to be name.

### Expected Behavior

Import and export should be a seamless workflow

### Observed Behavior

Record 1 name: This field is required.

**Comment by jeremystretch** [comment]
As has been discussed many times in various issues, import & export are entirely separate functions. The supported fields for each object type are clearly documented beneath every bulk import form.
