### ISSUE TITLE
VLAN Group Scoping and Virtual Machines

### ISSUE THREAD

**Issue by adparis99** [netbox-community/netbox#11408]
### NetBox version

v3.3 (Also Tested in v3.4.2 demo)

### Python version

3.10

### Steps to Reproduce

1. Create a VLAN Group (Group X) scoped to Site X, Location X
2. Create a VLAN (VLAN X) assigned to Group X
3. Create a virtual host device (Device X) that is assigned to a cluster, site (Site X), and location (Location X)
4. Create a virtual machine (VM X) assigned to Device X
5. Add an interface to VM X
6. Attempt to assign VLAN X to the newly created interface on VM X

### Expected Behavior

I expected VLAN X to be available to be assigned to the new interface for VM X. It seems logical for a VM to have access to any VLANs that its host device has access to.

### Observed Behavior

VLAN X doesn't show up in the list of VLANs available to be assigned to the virtual machine interface. Other VLANs that are in groups scoped directly to Site X as well as those not in groups show up as available, but not any VLANs scoped directly to Location X. My best guess is this has to do with the fact that both clusters and virtual machines can only be assigned to sites, while devices can be assigned to both sites and locations.

**Comment by jeremystretch** [comment]
> 1. Create a VLAN Group (Group X) scoped to Site X, Location X

You've limited the VLAN group to a specific location, whereas VMs must be assigned to sites and/or clusters. If you scope the group to the site, and then assign either the VM or its cluster to that site, the VLAN will be available.

>  It seems logical for a VM to have access to any VLANs that its host device has access to.

We can't make this assumption on behalf of the user. Physical and logical infrastructures often have very different topologies.
