### ISSUE TITLE
Error when using two users via netbox.authentication.LDAPBackend that only differ in case

### ISSUE THREAD

**Issue by k3x** [netbox-community/netbox#11405]
### NetBox version

v3.4.2

### Python version

3.8

### Steps to Reproduce

1. Create User "abc" in AD
2. Create USer "ABC" in AD
3. use these Settings:
```REMOTE_AUTH_ENABLED = True
REMOTE_AUTH_BACKEND = 'netbox.authentication.LDAPBackend'
REMOTE_AUTH_HEADER = 'HTTP_REMOTE_USER'
REMOTE_AUTH_AUTO_CREATE_USER = True
REMOTE_AUTH_DEFAULT_GROUPS = []
REMOTE_AUTH_DEFAULT_PERMISSIONS = {}
```
6. Login as user abc
7. Logout
8. Login as User ABC
9. Error

### Expected Behavior

In Django and Netbox it is possible to use two users abc/ABC without problems. So i think netbox.authentication.LDAPBackend should also support it.

### Observed Behavior

![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/4257211/210804519-9947afa9-3107-464a-b3c0-8518c453bde8.png)

**Comment by ziggekatten** [comment]
Active Directory is case insensitive, so you would always get more than one user back in the response. 

So it's really not a netbox issue. 

Why one would like to have two users, one with lowercase and one uppercase I can't really find the usecase for.

**Comment by k3x** [comment]
Well in fact it should be the same user in our company, but somehow it was created in Netbox with different lowercase/uppercase letters resulting in the error above.

I didn't notive AD is case-insensitive. Maybe netbox.authentication.LDAPBackend should call lower() on all usernames to mitigate these problems?

**Comment by jeremystretch** [comment]
> Maybe netbox.authentication.LDAPBackend should call lower() on all usernames to mitigate these problems?

This would be dangerous, as AD does track these as two different accounts. If we were to treat them as one, it would potentially allow a user to authenticate as account A with credentials for account B.

Can you share a complete stack trace so I get a better idea of what's happening to trigger the exception?

**Comment by jeremystretch** [comment]
Closing this out as it doesn't appear to require any further action.
