### ISSUE TITLE
Quick Search on VLANs Behaving Improperly

### ISSUE THREAD

**Issue by adparis99** [netbox-community/netbox#11412]
### NetBox version

v3.4.2

### Python version

3.10

### Steps to Reproduce

Use VLAN  Quick Search and enter a single digit, such as 5

### Expected Behavior

VLANs with an ID that includes 5 come up, such as 5, 50, 150, 500, etc.

### Observed Behavior

VLANs with an ID that match the specific digit come up, such as 5. VLANs that have a name that includes 5 also come up. But VLANs with IDs that include but do not equal 5 do not show up.

**Comment by jeremystretch** [comment]
This is working as intended. NetBox intentionally matches only on full VLAN IDs to avoid returning excessive irrelevant results.
