### ISSUE TITLE
Allow for PowerFeeds to be searched from their related objects name

### ISSUE THREAD

**Issue by jsenecal** [netbox-community/netbox#11422]
### NetBox version

v3.4.1

### Feature type

Change to existing functionality

### Proposed functionality

When searching for a PowerFeed, its is not currently possible to use the PowerPanel name as a "quick" filter in the search field.

The proposal is to add these to the filterset at [dcim/filtersets.py#L1841](https://github.com/netbox-community/netbox/blob/develop/netbox/dcim/filtersets.py#L1841)

### Use case

Colocation providers will sometimes name their circuits in a way that would not identify their panel, 

POWER0175624P > MTL71.4.415.0.RPP.B6.UPS500-B

Searching for "UPS500" yields no results in that case.

### Database changes

None

### External dependencies

None

**Comment by jeremystretch** [comment]
@jsenecal do you still intend to work on this?
