### ISSUE TITLE
Disallow changing CustomField type after creation

### ISSUE THREAD

**Issue by kkthxbye-code** [netbox-community/netbox#11431]
### NetBox version

v3.4.2

### Feature type

Change to existing functionality

### Proposed functionality

Disallow changing CustomField type after creation.

### Use case

Currently we allow changing the type after creation, but if there's already custom field data saved on an object, in most cases it will cause exceptions in the UI and API when the custom field data is deserialized. Currently there is no logic to handle changing the type. Even if we created logic for converting between all types, it would be a very slow process and error prone as most types are not compatible (float -> int, int -> date etc.).

### Database changes

None

### External dependencies

None

**Comment by PieterL75** [comment]
Even renaming a custom field can cause problems. It sometimes times out before all objects have been updated....

**Comment by jeremystretch** [comment]
Does this need a milestone? Seems reasonable to implement in v3.4.x IMO.

**Comment by kkthxbye-code** [comment]
No, the PR should be good to merge into develop if the approach for limiting field in the API is good enough.
