### ISSUE TITLE
GraphQL Custom Field Object & Multi-Object fields

### ISSUE THREAD

**Issue by ryanmerolle** [netbox-community/netbox#11434]
### NetBox version

v3.4.2

### Feature type

Change to existing functionality

### Proposed functionality

GraphQL currently returns Custom Field Object & Multi-Object fields as their object ids.  Similar to the REST API, it would be nice to display the related  object details in their entirety.

### Use case

The point of graphql is to minimize the number of api queries, but currently this is not the case for custom fields.

### Database changes

none

### External dependencies

none

**Comment by ryanmerolle** [comment]
@arthanson sorry to tag you here, but your opinion here on effort and if it should even be tackled is paramaount given your recent work with GraphQL.

**Comment by arthanson** [comment]
Not sure off-hand. I'll take a look into it...

**Comment by arthanson** [comment]
@ryanmerolle can you expand on this a bit, I'm not sure I'm understanding it.  For example I have a custom-field set up on tenants, if I do the query:
```
{
  tenant_list {
    id
    custom_fields
  }
}
```
I get back:
```
{
  "data": {
    "tenant_list": [
      {
        "id": "7",
        "custom_fields": {
          "cust_id": "CYB01"
        }
      },
      {
        "id": "5",
        "custom_fields": {
          "cust_id": "DMI01"
        }
      },
      {
        "id": "1",
        "custom_fields": {
          "cust_id": "INI04"
        }
      },

```
So in this case it is expanded.  Can you include a query that shows the issue?

**Comment by ryanmerolle** [comment]
Yea I might have been to hasty to include this.  I am not sure how this would get tackled, but the point of this FR was to try to follow the relationship of the custom_fields that are related to other objects.  IE instead of an id of the field, it would include more about the related object similar to what is found in the api.

I raised it off the back of a user inquiry in slack.  Happy to close this if this seems too vague or not worth any ROI.

**Comment by jeremystretch** [comment]
Going to close this out as there doesn't seem to be a clear path forward. Happy to revisit should additional detail surface.
