### ISSUE TITLE
Allow linking of rack power to PDUs or UPSs

### ISSUE THREAD

**Issue by dutchman80** [netbox-community/netbox#11435]
### NetBox version

v3.4.0

### Feature type

Change to existing functionality

### Proposed functionality

Within a rack, allow the selection of any devices with "Power Outlets" (like PDUs and UPSs) as the "Power Feeds" for that rack.  Selecting a device would supplant the default "Power Feeds" that show up now, when a rack is associated with a power feed in the power feed's definition.

The "Maximum Draw" setting of the power device (and any preceding power devices that it's plugged into) could define the total amount of power that device can feed to the rack.

For example, for power path:

    power feed (30A max) -> ups (20A max) -> pdu (15A max)

the rack where the pdu is installed would have a max amperage draw of 15A

### Use case

This greatly increases flexibility.  Right now, a rack's power consumption is tracked by which power feeds are associated with that rack.  This would allow you to instead tie a rack's power consumption to specific PDUs, specific UPSs, etc.

This leads to more accurate power tracking when cross wiring devices (i.e. power feed -> ups -> rack1 pdu & rack2 pdu), and also when a rack's PDU has a lower max amperage than the power feed that it's plugged into.

**Comment by eronlloyd** [comment]
I agree with the concept of shifting the power path modeling from racks to devices as part of a broader goal to properly model the entire DC electrical system (at a practical level). In DC design, racks are not the focus, but devices are.

For each utility source delivered to the DC, it follows through a topology of equipment within a distribution path including UPS, switch board, PDU, RPP (remote power panel), power strips, etc. Racks or cabinets are important for organizing devices, but shouldn't be the unit of power consumption. The system itself, and the power devices included in it, should track consumption.

Below is example of a fault tolerant DC design from the ANSI/BICSI 002-2019 Data Center Design and Implementation Best Practices manual. I would love to help improve NetBox's power and mechanical system modeling to improve the representation of these aspects.

![image](https://github.com/netbox-community/netbox/assets/197778/55f8466b-73b5-491e-aabf-6cc6a22b5256)

**Comment by justin-davisibm** [comment]
More complete power mapping is sorely needed on the DCIM side - The ability to extend the existing Power Panel concept and link multiple together would be a potential first-step.

**Comment by jeremystretch** [comment]
After being open for nine months, there has unfortunately not been any real discussion or detailing of the changes proposed here. (It would not make sense to treat a device or set of devices as "power feeds.") The FR does not even provide a response under the "database changes" section, so I'm not sure what work anyone was expecting to take place. While it is clear this is an area of interest, there has not been any effort made to propose specific data model or API changes, or any consideration paid to how this would impact the current model. As such, I'm going to close it out.

If anyone would like to submit a new feature request to to propose a _specific set of changes_, including options for migrating existing power feed associations, you are welcome to do so in a new issue.

@eronlloyd the diagram you shared above represents datacenter facility power design. The scope of NetBox's power model encompasses only the PDUs and critical load portions of that diagram. Anything beyond that is well out of scope for this particular feature request, but similarly you are welcome to submit a new FR to extend the data model northbound if you think it would be appropriate for the application.
