### ISSUE TITLE
Enable Report results to be exported as an external file.

### ISSUE THREAD

**Issue by renatoalmeidaoliveira** [netbox-community/netbox#11430]
### NetBox version

v3.4.2

### Feature type

New functionality

### Proposed functionality

Allow the users to export the results of a report to a csv or a custom implementation in the Report Class.
I think that can be achieved by replicating the export functionality of the ListViews to the ExportResultView, and in the Report Class implement an export method called by the ExportResultView when 'export' is in the request with the results as an input.
 

### Use case

The Report Result View page is limited when there several results and limits the way the user can interact with the results, with a exported csv the user can interact with the report data in some spreadsheet software and uses that data later to run scripts in nbshell or anything he whants.

### Database changes

None

### External dependencies

None

**Comment by ryanmerolle** [comment]
This seems to be a part of a large feature request to improve reports and script output.  Let's close this feature request and track in #10587
