### ISSUE TITLE
Add ForcePoint CVI protocol to the options of the FHRP Group

### ISSUE THREAD

**Issue by hovrashko** [netbox-community/netbox#11448]
### NetBox version

v3.3.7

### Feature type

Change to existing functionality

### Proposed functionality

Currently the FHRP Group does not support CVI protocol used by ForcePoint, and only available option would be to use Other

Available options in v3.3.7 (and 3.4.2) are seen bellow:
![image](https://user-images.githubusercontent.com/61986752/211404602-06706076-726c-47e2-b1b1-90a56f0d328a.png)

I propose to add another Protocol to the dropdown list that is CVI for ForcePoint type Firewall. 

### Use case

Improve the modelling of the FHRP when using ForcePoint firewalls

**Comment by jeremystretch** [comment]
Could you link to some documentation of this protocol for reference?

**Comment by jeremystretch** [comment]
The documentation you linked suggests CVI stands for "Cluster Virtual IP," rather than itself being a wire protocol. This should be modeled as a VIP in NetBox.

**Comment by hovrashko** [comment]
Hey @jeremystretch ,
 Yes, they are VIP's but the protocol still a CVI not "other". 
![image](https://user-images.githubusercontent.com/61986752/225707747-e84ed864-e95f-43aa-854b-77dd550ade5c.png)

It wont change the structure, but it's a proper way to document the network. Otherwise the FHRP list only would have "other" in it. 
 Jeremy, please correct me if im mistaken, or it doesn't make sense. 

Regards, 
Thank you!

**Comment by hovrashko** [comment]
Hi there,
  So, seems like all the information provided.  Can we add the ForcePoint CVI FHRP protocol to the next NetBox version?

Thank you!

**Comment by jeremystretch** [comment]
Again, you've provided no indication that CVI is a wire protocol, so it would not make sense to add it to the list. If you can provide a reference to the specific wire protocol in use, we'll be happy to add it.

**Comment by hovrashko** [comment]
Hi,
 It has been a while and the question is explained over and over several times by several different approaches it is a FHRP.  When can we add ForcePoint CVI's to FHRP? 

Would appreciate the relevant approach from someone who understand what FHRP is and what it does. 

Thank you.
