### ISSUE TITLE
Incorrect display  status bar in % "Utilization", "Space".

### ISSUE THREAD

**Issue by aurus686** [netbox-community/netbox#11447]
### NetBox version

v3.4.1

### Python version

3.8

### Steps to Reproduce

1. Go to the IPAM-Prefixes
2. Select in table configuration available column "Utilization"

### Expected Behavior

The demo version correctly displays the status bar.
![Annotation 2023-01-09 173919](https://user-images.githubusercontent.com/122287115/211334081-63f652dc-4c8b-4ef5-8e81-95d111cda3f5.jpg)

### Observed Behavior

Incorrect display status bar
![Annotation 2023-01-09 174150](https://user-images.githubusercontent.com/122287115/211334690-60381491-5f13-46cb-b2fb-316eb89cc188.jpg)
![Annotation 2023-01-09 174223](https://user-images.githubusercontent.com/122287115/211334727-c4a71981-38e3-4636-b14e-43ec197d0323.jpg)

**Comment by jeremystretch** [comment]
This has been resolved in v3.4.2. Please see #11273.
