### ISSUE TITLE
Error IPV6 launch Netbox version v3.4.1

### ISSUE THREAD

**Issue by chrisho95** [netbox-community/netbox#11452]
### NetBox version

v3.4.1

### Python version

3.10

### Steps to Reproduce

When I launch Netbox version 3.4.1 with docker-compose, I have the following error coming up.

2023/01/10 13:50:17 [notice] 7#7 process 14 exited with code 0
2023/01/10 13:50:17 [info] 16#16 router started
2023/01/10 13:50:17 [info] 16#16 OpenSSL 3.0.2 15 Mar 2022, 30000020
âï¸ Applying configuration from /etc/unit/nginx-unit.json
**2023/01/10 13:50:18 [alert] 7#7 socket(\"[::]:8080\") failed (97: Address family not supported by protocol)**
2023/01/10 13:50:18 [alert] 16#16 failed to apply new conf
â ï¸ Could no load Unit configuration
2023/01/10 13:50:18 [notice] 7#7 process 12 exited with code 1
2023/01/10 13:50:18 [notice] 7#7 process 15 exited with code 0
2023/01/10 13:50:18 [notice] 7#7 process 16 exited with code 0

The "nginx-unit.json" file has a new session in the file:

  **"listeners": {
    "0.0.0.0:8080": {
      "pass": "routes"
    },
    "[::]:8080": {
      "pass": "routes"
    }
  },**

When I remove the IPV6 part, Netbox launches correctly. 

  **"listeners": {
    "0.0.0.0:8080": {
      "pass": "routes"
    }
    },**

I would like to not use IPV6 IPs but don't modify the file "nginx-unit.json".

BR,

Chris.

### Expected Behavior

The launch of netbox is going well.

### Observed Behavior

2023/01/10 13:50:17 [notice] 7#7 process 14 exited with code 0
2023/01/10 13:50:17 [info] 16#16 router started
2023/01/10 13:50:17 [info] 16#16 OpenSSL 3.0.2 15 Mar 2022, 30000020
âï¸ Applying configuration from /etc/unit/nginx-unit.json
**2023/01/10 13:50:18 [alert] 7#7 socket(\"[::]:8080\") failed (97: Address family not supported by protocol)**
2023/01/10 13:50:18 [alert] 16#16 failed to apply new conf
â ï¸ Could no load Unit configuration
2023/01/10 13:50:18 [notice] 7#7 process 12 exited with code 1
2023/01/10 13:50:18 [notice] 7#7 process 15 exited with code 0
2023/01/10 13:50:18 [notice] 7#7 process 16 exited with code 0

**Comment by kkthxbye-code** [comment]
Please check the netbox-docker repo instead.
