### ISSUE TITLE
IPAddress model accepts inconsistent data for GenericForeignKey "assigned_object"

### ISSUE THREAD

**Issue by moonrail** [netbox-community/netbox#11454]
### NetBox version

v3.4.2

### Python version

3.10

### Steps to Reproduce

1. Have a Device/VM with Interface
2. Have an IP
3. Assign IP to Interface
4. PATCH /ipam/ip-addresses/{id}/ and send only either `assigned_object_type` or `assigned_object_id` with value `null`

### Expected Behavior

Request either fails with HTTP 400 and an explanation why the client sent inconsistent data or the backend sets the other attribute, that is not sent, to null/None as well.

Or - if the current behaviour is accepted - the UI does not fail with HTTP 500 `'NoneType' object has no attribute 'get_absolute_url'` like described in https://github.com/netbox-community/netbox/discussions/11112

### Observed Behavior

Backend does exactly what the client requests and sets only the sent attribute to the value.
So now IP-Address has one `assigned_object_` value referencing something and one `assigned_object_` value not referencing something.

Causes this issue in the UI: https://github.com/netbox-community/netbox/discussions/11112

'NoneType' object has no attribute 'get_absolute_url'

**Comment by jeremystretch** [comment]
> 4. PATCH /ipam/ip-addresses/{id}/ and send only either assigned_object_type or assigned_object_id with value null

Please share the complete API request you're sending.

**Comment by moonrail** [comment]
@jeremystretch 
Here you go, straight from Swaggerui:
```bash
curl -X 'PATCH' \
  'https://netbox.domain.tld/api/ipam/ip-addresses/123/' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -H 'X-CSRFToken: XYZ' \
  -d '{
  "assigned_object_id": null
}'
```

**Comment by jeremystretch** [comment]
This seems to overlap quite a bit with #10221. I'm not sure yet whether the fix for one will effectively resolve the other, but it's likely.

**Comment by abhi1693** [comment]
@jeremystretch I'd like to take this

**Comment by DanSheps** [comment]
@abhi1693 Going to assign this to you, feel free to proceed.

**Comment by abhi1693** [comment]
@DanSheps Can I also get #10221? My solution fixes these both together
