### ISSUE TITLE
GraphQL returns all objects if tag doesn't exist

### ISSUE THREAD

**Issue by 4xoc** [netbox-community/netbox#11473]
### NetBox version

v3.4.2

### Python version

3.10

### Steps to Reproduce

1. query GraphQL for device/interface with a tag that doesn't exist

### Expected Behavior

Resulting list of devices/interfaces only contains devices matching the tags or none if no device exists with matching tags.

### Observed Behavior

All devices/interfaces are returned no matter what tag filter has been applied. Same seems to apply for all kinds of filters that can be defined in GraphQL. No errors are returned.

Example below

query:
`{
  device_list(tag: "blablalba") {
    id
    name
    tags {
      name
    }
  }
    interface_list(tag: "not-ipmi_exporter") {
    id
    device {
      id
    }
     tags {
      name
    }
  }
}
`

result:
`{
  "data": {
    "device_list": [
      {
        "id": "1",
        "name": "device-A",
        "tags": [
          {
            "name": "node_exporter"
          }
        ]
      },
      {
        "id": "2",
        "name": "device-B",
        "tags": [
          {
            "name": "node_exporter"
          }
        ]
      }
    ],
    "interface_list": [
      {
        "id": "1",
        "device": {
          "id": "1"
        },
        "tags": [
          {
            "name": "ipmi_exporter"
          }
        ]
      },
      {
        "id": "2",
        "device": {
          "id": "2"
        },
        "tags": [
          {
            "name": "ipmi_exporter"
          }
        ]
      }
    ]
  }
}`

**Comment by aronbj20** [comment]
I think this could be solved by checking if the filterset is valid in ObjectListField.list_resolver() static method and returning an empty queryset if not valid.

I can take a look at this.

**Comment by aronbj20** [comment]
@jeremystretch can you assign this to me?

**Comment by kkthxbye-code** [comment]
@aronbj20 - I've assigned it to you.

**Comment by 4xoc** [comment]
Thanks for fixing this
