### ISSUE TITLE
CSV File import ignores "label" field

### ISSUE THREAD

**Issue by dutchman80** [netbox-community/netbox#11471]
### NetBox version

v3.4.0

### Python version

3.9

### Steps to Reproduce

Create a CSV file for a single cable import, including the "label" field
Go to "Upload File" and upload the CSV

### Expected Behavior

The specified label would be attached to the cable

### Observed Behavior

Cable is created, but no label is attached to it

However, if you just take the text of the CSV file and copy/paste it into the "Data Import" field, then the label import works as expected.

**Comment by jeremystretch** [comment]
Please share example data that can be used to reproduce the behavior.

**Comment by dutchman80** [comment]
So I ran into this issue over and over again when bulk importing cables yesterday, but now I can't replicate it at all.  I have no idea what I'm doing differently.  If it comes up again, I'll play closer attention and open a new bug.
