### ISSUE TITLE
Add SAS  interfaces and cable types

### ISSUE THREAD

**Issue by PaulR282** [netbox-community/netbox#11474]
### NetBox version

v3.4.2

### Feature type

Data model extension

### Proposed functionality

Add External Mini SAS Male (SFF-8088) cables
Add External Mini SAS Female (SFF-8088) Interface type for devices
Add External Mini SAS HD Male (SFF-8644) cables
Add External Mini SAS HD Female (SFF-8644) interface type for devices

### Use case

I know there were FR #3617 and #2715 for this but they were never implemented. I think these should be added to properly document the connection within a storage array. And since the development has made great progress since #2715, especially in the variety of cable and interface types, it is now time to add these.

**Comment by czarnian** [comment]
This would be nice and not only for storage/tapeloaders - some Aruba switches use MiniSAS for stacking.

**Comment by PaulR282** [comment]
This feature is still needed by some of us. So this is just a comment to not have this fr in stale.
