### ISSUE TITLE
IP Address Interface Assignment silently discards selected Device if no Interface is selected

### ISSUE THREAD

**Issue by clerie** [netbox-community/netbox#11477]
### NetBox version

v3.4.2

### Python version

3.8

### Steps to Reproduce

1. Create a Device
2. Fill out required fields
3. Save Device
4. Create IP Address
5. Fill out required fields
6. Choose the created Device in the Interface Assignment
7. Do not choose any Interface in the Interface Assignment
8. Save IP Address

### Expected Behavior

When saving the IP Address object the form gets validated and at this point I expect to get a warning which tells me to choose an interface in case I want to assign this IP Address to the Device, else to clear the device field.

### Observed Behavior

The device selection gets silently discarded. Users can't find the IP Address they have "assigned" to a Device anywhere. Only on editing the IP Address again shows that the value never got stored.

**Comment by jeremystretch** [comment]
> I expect to get a warning which tells me to choose an interface in case I want to assign this IP Address to the Device, else to clear the device field.

We're working an improvement for this in #10054, which will replace the current set of form fields and hopefully make the process of selecting a related object much more natural. I'm not sure there's anything we can do before that to improve this that wouldn't require an unjustifiable amount of development effort, but I'm open to suggestions.

**Comment by jeremystretch** [comment]
Closing this out as no specific improvements have been proposed.
