### ISSUE TITLE
GraphQL attribute types are inconsistent and documentation is incorrect

### ISSUE THREAD

**Issue by 4xoc** [netbox-community/netbox#11472]
### NetBox version

v3.4.2

### Python version

3.10

### Steps to Reproduce

This issue ticket covers two problems going hand in hand. First is the incorrect schema documentation in GraphiQL, the other is incorrect use of types (always string for nummeric values)

Incorrect docs:
1. Use GraphiQL to look into schemas for queries and attributes returned. Everything is a string except a few bools

Incorrect use of types:
1. query for any object with id

Type missmatch between docs and reality:
1. query for interface_list with mtu attribute. It is described as string type but int is returned.

### Expected Behavior

1. The Schema in GraphiQL represents the correct attribute type identical to the REST API.

2. Nummerical values are returned as numbers in the response just like with the REST API.

3. The Schema in GraphiQL actually describes attributes in the correct type they are being returned in.

### Observed Behavior

1. Schema always uses strings for all non-boolean attributes even though many attributes are clearly numbers (like ids). 

2. Many attributes that could be represented as numbers are strings like ids.

3. Some attributes actually return ints like mtu on interfaces when docs say it's a string.

**Comment by ryanmerolle** [comment]
@4xoc great issue!  Would you be able to tackle this?

**Comment by 4xoc** [comment]
I'm afraid my knowledge of Python and Django is close to nothing. From looking at things I would suspect [this](https://github.com/netbox-community/netbox/blob/develop/netbox/netbox/graphql/utils.py#L5) being the main cause. IDs are generally uint64 which may not be part of `NumberFilter` and thus cause the fallback to string. But this is nothing more than a guess. Not sure how that would explain differences between the docs and the actual returned type though.

**Comment by 4xoc** [comment]
Apparently GraphQL doesn't support uint64 by default. One can create a [custom scalar](https://docs.graphene-python.org/en/latest/types/scalars/#custom-scalars) which should work for such cases.

**Comment by rmanyari** [comment]
Happy to take a look at this, that being said, this is part of the public facing API and changes to types would imply breaking backwards compatibility (perhaps it will need a minor or even major release?)

I'm new to the project and would love the input from one of the more tenured members or maintainers.

* How do we typically approach these types of changes and what type of backwards compatibility guarantees we offer to users?
* Is there appetite for this type of changes ATM?
* From what I've seen so far the UI only uses the REST API, so this wouldn't involve UI changes, can someone confirm?

Thanks!

**Comment by 4xoc** [comment]
Yeah I looked at interface_list definition and arguments of it where MTU must be string. An interface object itself returns int correctly. To rephrase point no 3 from observed behavior: filter arguments that are int in the actual object are required to be string. In my mind id being a string is the biggest issue here.

**Comment by bluikko** [comment]
I also was wondering about this when starting to move from REST to GraphQL. I believe this issue refers to example like this:
![image](https://user-images.githubusercontent.com/14869000/230541659-785e038a-122a-4b0b-982a-cbc97fafdfc1.png)
Is this the correct example? Note how all the IDs are of type "String" - in fact almost everything is "String" except some Booleans.

**Comment by 4xoc** [comment]
> Is this the correct example? Note how all the IDs are of type "String" - in fact almost everything is "String" except some Booleans.

That's exactly it. I believe to have seen some other cases in but can't find any example so I may confuse this again with query parameters (which is probably worth fixing as well).

**Comment by arthanson** [comment]
I'm not sure this is a bug, the above screenshot looks like it is from the GraphiQL browser schema pane which shows things like id as "id: [String]" but if you look at the actual schema definition yaml file it is type array of integers, which the GraphiQL is unhelpfully showing as String. From the yaml file:

```
      - in: query
        name: id
        schema:
          type: array
          items:
            type: integer
            format: int32
        explode: true
        style: form
```
That does look correct.

**Comment by 4xoc** [comment]
The result from graphql certainly is a string and is required to be a string for queries too. I believe that int32 is incorrect too, some time ago all IDs got changed to int64. IDs definitely are represented as strings.

![image](https://github.com/netbox-community/netbox/assets/12109998/366b850d-2d67-4b30-af70-4cc280d6407c)

**Comment by arthanson** [comment]
Okay, makes sense - was getting a bit confused as I was talking about query params instead of the object itself.  Probably using type ID (https://graphql.org/learn/schema/#scalar-types) would be the most correct:

"ID: The ID scalar type represents a unique identifier, often used to refetch an object or as the key for a cache. The ID type is serialized in the same way as a String; however, defining it as an ID signifies that it is not intended to be human‐readable."

**Comment by arthanson** [comment]
As stated above GraphQL doesn't natively support int64 but you can use scalars, when we move to strawberry #9856 we can replace it with https://strawberry.rocks/docs/types/scalars#int64

**Comment by 4xoc** [comment]
I've not yet had a chance to look into a 4.x installation but looking through the documentation it appears as using ID type scalar solves the issue of supplying integers for queries.

However, on the return side of things it'll still return a string that has to be parsed client side. Looking at the docs it looks to me like maybe using BigInt (https://strawberry.rocks/docs/types/scalars#bigint-64-bit-integers) would be a better way to go. Afaik IDs in Netbox are unsigned 64 bit integers and thus should be returned as such. I don't think Python itself sees a difference as everything is just int so it probably works with bigint out of the box.
