### ISSUE TITLE
Description missing in API representation of multiple models

### ISSUE THREAD

**Issue by rodvand** [netbox-community/netbox#11488]
### NetBox version

v3.4.2

### Python version

3.8

### Steps to Reproduce

1. Create a Virtual Machine named vm1
2. Visit the virtual machine in the GUI - note the description field
3. Visit the virtual machine's API representation - note that description is missing

Alternative just go to https://demo.netbox.dev/api/virtualization/virtual-machines/363/ and see that we are missing description. 

Also found to be missing on Device model.

### Expected Behavior

A description field.

### Observed Behavior

It's missing.

**Comment by abhi1693** [comment]
@jeremystretch I'd like to take this up

**Comment by jeremystretch** [comment]
Thanks @abhi1693!
