### ISSUE TITLE
Date Custom Field Display Doesn't Match Install Date

### ISSUE THREAD

**Issue by nick-bogle** [netbox-community/netbox#11483]
### NetBox version

v3.4.2

### Python version

3.9

### Steps to Reproduce

1.) Create a custom field with a date type for Circuit model
2.) Add a circuit that has both an install date, and a date set in your new custom field
3.) View circuit and see that Install Date shows "MM/DD/YYYY", where as the custom field displays "Mon. DD, YYYY".

### Expected Behavior

The dates should be consistently displayed throughout the UI - personal preference of DD/MM/YYYY format.

### Observed Behavior

 Install Date shows "MM/DD/YYYY", where as the custom field displays "Mon. DD, YYYY".

**Comment by jeremystretch** [comment]
> Install Date shows "MM/DD/YYYY"

The install and termination dates will be formatted according to the [`SHORT_DATE_FORMAT`](https://docs.netbox.dev/en/stable/configuration/date-time/#date-and-time-formatting) configuration parameter, which defaults to the `YYYY-MM-DD` format. The custom field is not currently subject to any particular formatting, and is defaulting to the native string representation for a Python date object.
