### ISSUE TITLE
Clone Saved Filters without function

### ISSUE THREAD

**Issue by ShellBoyAFK** [netbox-community/netbox#11496]
### NetBox version

v3.4.2

### Python version

3.10

### Steps to Reproduce

1. Click Other
2. Click Saved Filters
3. Click Add
4. Fill the necessary fields with data
5. Click Create 
6. Click on the New Saved Filter 
7. Click Clone
8. See Nothing :

### Expected Behavior

A clone function should clone something!
FMO I would have expected that I only have to fill in or change the name* and the slug*.

### Observed Behavior

-

**Comment by jeremystretch** [comment]
> A clone function should clone something!

It does: The `enabled` and `weight` values are cloned. The name and slug are not, because these fields must be unique.

**Comment by ShellBoyAFK** [comment]
Hm! Not even that good ...

In my imagination (usability)! I imagine (as a pure work relief) that everything that is cloned is also copied. With Uniqen fields you can add a "_copy" or a "(1...)". Be creative. 

The current "clone function" does not help me personally. The fields especially the Jinja2 must be adapted in my use case only slightly and Uniqe fields will adapt as a user of course itself.   

Anyway, then keep it that way! I thought that was forgotten or the function does not apply here.

**Comment by ShellBoyAFK** [comment]
oh sorry i mean 

- Content types
- Description
- Parameters (JSON)

**Comment by FliesLikeABrick** [comment]
@jeremystretch  can you re-evaluate this bug report based on the last comment above, which was after closure ?  Cloning a saved filter in the UI does not clone the content types, description, or parameters -- i.e. the substance of the saved filter.  Or should a new bug report be opened for a cleaner history on the issue?
