### ISSUE TITLE
unexpected Behavior for IP address serach in Global search

### ISSUE THREAD

**Issue by tikondrus** [netbox-community/netbox#11493]
### NetBox version

v3.4.2

### Python version

3.8

### Steps to Reproduce

1. enter IP in global search like 

### Expected Behavior

after searching any IP (url like /search/?q=10.111.227.75)  in netbox 3.3.х I received a list of prefixes and Aggregates
<img width="1257" alt="1" src="https://user-images.githubusercontent.com/34535914/212368169-179c5d71-257a-4da1-809a-7d8fa021cfb0.png">

### Observed Behavior

after searching any IP (url like /search/?q=10.111.227.75) I've got — No results found — if IP doesn't exist

now I should  use filter in prefixes /ipam/prefixes/?q=10.111.227.75
<img width="1175" alt="2" src="https://user-images.githubusercontent.com/34535914/212368477-f4a40c20-5dec-497e-9598-87a990650660.png">
<img width="1067" alt="3" src="https://user-images.githubusercontent.com/34535914/212368490-db135199-a8a9-4734-8f09-8b69ac1c0601.png">

**Comment by jeremystretch** [comment]
Thank you for submitting this issue, however it appears that this topic has already been raised. Please see issue #11315 for further discussion.
