### ISSUE TITLE
Full support of inventory item templates

### ISSUE THREAD

**Issue by AndMrzv** [netbox-community/netbox#11520]
### NetBox version

v3.3.7

### Feature type

New functionality

### Proposed functionality

Netbox already has inventory item template feature now available only via device templates. And fields for these templates are now set in stone.
![Снимок экрана-20230117140836-944x582](https://user-images.githubusercontent.com/99031446/212883897-64c848d1-f10a-45ae-94e8-fb0f455cf38b.png)

Would be nice if inventory item templates were fully editable similar to how it works for device templates (types) or at least inherited same attributes a user can add for inventory items  with custom fields.

### Use case

Users may have some characteristics of inventory items stored in their custom fields (for example: model, weight, spares location, etc). Since inventory item templates don't have the same custom fields available to store the values, you have to fill it in by hand (or script, doesn't really matter) for every inventory item created from templates. Having fixed values stored in an inventory item template would allow for created item to inherit the values, reducing the need to fill info manually and the human factor.
I know Netbox is not about inventory management but maybe more people would find this proposal useful.

**Comment by jeremystretch** [comment]
Thank you for submitting this issue, however it appears that this topic has already been raised. Please see issue #10289 for further discussion.
