### ISSUE TITLE
Filter custom field of type 'selection' for value is null or not-null

### ISSUE THREAD

**Issue by candlerb** [netbox-community/netbox#11538]
### NetBox version

v3.4.2

### Feature type

Change to existing functionality

### Proposed functionality

I would like a way to be able to filter on custom fields of type "selection", to see if they are set (with any value) or unset.

There is an `empty` filter [documented](https://docs.netbox.dev/en/stable/reference/filtering/#string-fields) although only for string fields. There are no examples of how to use it, and no test cases for it in `netbox/utilities/tests/test_filters.py`

Given a custom selection field `snmp_module`, the following experimentally don't work:

```
# These return all devices
/api/dcim/devices/?cf_snmp_module__empty
/api/dcim/devices/?cf_snmp_module__empty=

# These always return zero devices
/api/dcim/devices/?cf_snmp_module__empty=true
/api/dcim/devices/?cf_snmp_module__empty=false
/api/dcim/devices/?cf_snmp_module__empty=1
/api/dcim/devices/?cf_snmp_module__empty=0
```

It does work with regular string fields though (e.g. `name__empty=0` and `name__empty=1` are fine).

There are other filters which do work on this custom field.  The following returns all devices where the custom field is set and the value contains an underscore:

```
/api/dcim/devices/?cf_snmp_module__ic=_
```

The following returns all devices where the custom field is non-null, and also does not contain 'z':

```
/api/dcim/devices/?cf_snmp_module__nic=z
```

The following returns all devices where the custom field is non-null and does not start with `xxxxx` (and therefore works as an ugly workaround for what I want):

```
/api/dcim/devices/?cf_snmp_module__nisw=xxxxx
```

But the following doesn't work, as it returns all devices (whether or not the field is null):

```
/api/dcim/devices/?cf_snmp_module__n=xxxxx
```

What I'm requesting in this feature request is either:

* the existing `empty` condition to be extended to mean "null/not null" for selection custom fields; or
* a new condition, e.g. `__null=1` or `__null=0`

-----
Aside: it's unclear to me whether "empty" was intended to work this way (i.e. this is a bug, not a feature request). I found this code in `netbox/netbox/filtersets.py`:

```
        elif isinstance(existing_filter, (
            django_filters.ModelChoiceFilter,
            django_filters.ModelMultipleChoiceFilter,
            TagFilter
        )) or existing_filter.extra.get('choices'):
            # These filter types support only negation
            return FILTER_NEGATION_LOOKUP_MAP
```

This suggests to me that choices should only support negation (n) - but I've already shown that "ic" and "nic" do work, so maybe these "selection" fields are being considered as strings anyway.

### Use case

To be able to filter devices depending on the presence/absence of a value in a selection custom field.

Specifically: I use the custom field `snmp_module` to choose an appropriate SNMP mobile to scrape by Prometheus.  I need to query Netbox to get a list of targets to scrape, and really that should just be exactly those devices where `snmp_module` has been set.

Currently I have to use a tag to achieve this: I can filter on `tag=prom_snmp`.  But this requires setting *both* the custom field *and* a tag on the device.

### Database changes

None

### External dependencies

None

**Comment by candlerb** [comment]
I should add, to find devices with custom field unset I also tried

```
/api/dcim/devices/?cf_snmp_module=
```

but that returns all devices. In any case, what I need is the opposite: "all devices where `cf_snmp_module` is set to any (non-empty) value"

**Comment by jeremystretch** [comment]
#11539 may be related to this, though I don't believe it's blocking.

**Comment by jwbensley** [comment]
This request is to add the `__empty=` filter to custom fields which are lists/selections. This filter is currently only available on string/text fields which are native fields on objects in NetBox. I would like to see this filter on custom fields which are strings/text too. We have the need to filter custom fields which are strings, for all which are empty / not empty.

**Comment by candlerb** [comment]
By chance I came across this in `netbox/netbox/settings.py`:

```
FILTERS_NULL_CHOICE_LABEL = 'None'
FILTERS_NULL_CHOICE_VALUE = 'null'
```

It looks like there's a magic string value here, and experimentally, the following filters *do* appear to work:

```
/api/dcim/devices/?cf_snmp_module=null
/api/dcim/devices/?cf_snmp_module__n=null
```

The latter one is exactly what I was looking for (custom field value is not null).

I would therefore be happy to close this issue, except that as far as I can tell, this functionality is completely undocumented and therefore I'm loathe to depend on it.  Could it be documented [here](https://docs.netbox.dev/en/stable/reference/filtering/)?  And could it be made clear what the intended difference is between `foo__empty=1` and `foo=null` for filtering?

I observe that there are just two tests using `settings.FILTERS_NULL_CHOICE_VALUE` in `netbox/utilities/tests/test_filters.py`

**Comment by candlerb** [comment]
Unfortunately, now I need this custom field to be `multiselect` instead of `select`, and the filter no longer works.

`cf_snmp_module=null` raises an exception:

```
Internal Server Error: /api/dcim/devices/

ValueError at /api/dcim/devices/
Cannot use None as a query value

Request Method: GET
Request URL: https://netbox.example.net/api/dcim/devices/?cf_snmp_module=null
Django Version: 4.1.10
Python Executable: /opt/netbox/venv/bin/python3.8
Python Version: 3.8.10
Python Path: ['/opt/netbox/netbox', '/opt/netbox', '/opt/netbox/venv/bin', '/usr/lib/python38.zip', '/usr/lib/python3.8', '/usr/lib/python3.8/lib-dynload', '/opt/netbox/venv/lib/python3.8/site-packages']
Server time: Tue, 29 Aug 2023 20:25:45 +0000
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django.contrib.humanize',
 'corsheaders',
 'debug_toolbar',
 'graphiql_debug_toolbar',
 'django_filters',
 'django_tables2',
 'django_prometheus',
 'graphene_django',
 'mptt',
 'rest_framework',
 'social_django',
 'taggit',
 'timezone_field',
 'core',
 'circuits',
 'dcim',
 'ipam',
 'extras',
 'tenancy',
 'users',
 'utilities',
 'virtualization',
 'wireless',
 'django_rq',
 'drf_spectacular',
 'drf_spectacular_sidecar',
 'netbox_prometheus_sd.PrometheusSD',
 'netbox_topology_views.TopologyViewsConfig']
Installed Middleware:
['graphiql_debug_toolbar.middleware.DebugToolbarMiddleware',
 'django_prometheus.middleware.PrometheusBeforeMiddleware',
 'corsheaders.middleware.CorsMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'django.middleware.security.SecurityMiddleware',
 'netbox.middleware.RemoteUserMiddleware',
 'netbox.middleware.CoreMiddleware',
 'netbox.middleware.MaintenanceModeMiddleware',
 'django_prometheus.middleware.PrometheusAfterMiddleware']


Traceback (most recent call last):
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 55, in wrapped_view
    return view_func(*args, **kwargs)
  File "/opt/netbox/venv/lib/python3.8/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/opt/netbox/netbox/netbox/api/viewsets/__init__.py", line 91, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/opt/netbox/venv/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/opt/netbox/venv/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/opt/netbox/venv/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/opt/netbox/venv/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/opt/netbox/netbox/netbox/api/viewsets/mixins.py", line 95, in list
    return super().list(request, *args, **kwargs)
  File "/opt/netbox/venv/lib/python3.8/site-packages/rest_framework/mixins.py", line 38, in list
    queryset = self.filter_queryset(self.get_queryset())
  File "/opt/netbox/venv/lib/python3.8/site-packages/rest_framework/generics.py", line 150, in filter_queryset
    queryset = backend().filter_queryset(self.request, queryset, self)
  File "/opt/netbox/venv/lib/python3.8/site-packages/django_filters/rest_framework/backends.py", line 74, in filter_queryset
    return filterset.qs
  File "/opt/netbox/venv/lib/python3.8/site-packages/django_filters/filterset.py", line 230, in qs
    qs = self.filter_queryset(qs)
  File "/opt/netbox/venv/lib/python3.8/site-packages/django_filters/filterset.py", line 213, in filter_queryset
    queryset = self.filters[name].filter(queryset, value)
  File "/opt/netbox/venv/lib/python3.8/site-packages/django_filters/filters.py", line 263, in filter
    qs = self.get_method(qs)(q)
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/db/models/query.py", line 1421, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/db/models/query.py", line 1439, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/db/models/query.py", line 1446, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1532, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1562, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1388, in build_filter
    return self._add_q(
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1562, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1478, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1308, in build_lookup
    raise ValueError("Cannot use None as a query value")

Exception Type: ValueError at /api/dcim/devices/
Exception Value: Cannot use None as a query value
Raised during: dcim.api.views.DeviceViewSet
Request information:
USER: admin

GET:
cf_snmp_module = 'null'

POST: No POST data

FILES: No FILES data

COOKIES: No cookie data
```

`cf_snmp_module__n=null` does nothing: all devices are shown, regardless of whether this custom field is set or not.

**Comment by llamafilm** [comment]
I need this feature too, for multi selects
