### ISSUE TITLE
Add Tenant and Tenant Group to virtual chassis

### ISSUE THREAD

**Issue by ShellBoyAFK** [netbox-community/netbox#11530]
### NetBox version

v3.4.2

### Feature type

Change to existing functionality

### Proposed functionality

Some of our virtual chassis are located in different sites and in different tenants. Until now, the individual tenants always see all virtual chassis of the other tenants.
This is due to the fact that until now you don't have the possibility to assign them to a teanant / tenant group. So I can not regulate them with permissions in the Django admin area.  

### Use case

If necessary this would be good, if 

- Tenant A only sees virtual chassis from Tenant A
- Tenant B sees only virtual chassis of Tenant B 

### Database changes

?

### External dependencies

?

**Comment by jeremystretch** [comment]
I don't think it makes sense to assign tenancy to a virtual chassis directly. Why wouldn't this be inferred from its master/member devices?

**Comment by ShellBoyAFK** [comment]
in short: security/data protection we call it (EU-DSGVO, DS-GVO ISO27001 / ISMS / KHZG) authorisations.

So we don't want tenant A to see tenant B's virtual chassis.

If someone has permission to do something, then they are allowed to do it. 

In short, all users, are in different and distinct groups and these have different permissions filtered on tenants and tenants groups. 

It's not my fault that security is a by-product in our society.

**Comment by DanSheps** [comment]
> So we don't want tenant A to see tenant B's virtual chassis.

You would add a constraint to handle this:

`{"master__tenant": "Tenant B"}`

I agree and do not see a need for tenancy here.
