### ISSUE TITLE
VLAN - Site Information is empty when "VLAN Group with site scope is used" -

### ISSUE THREAD

**Issue by GSeiNet** [netbox-community/netbox#11535]
### NetBox version

v3.4.1

### Python version

3.8

### Steps to Reproduce

If a create VLAN Group belongs to a site (scope type site)
and create VLAN with this group.
VLAN is created, but the site field for this VLAN is empty.
It is not possible to assign the site Information to this vlan.
Only VLAN Group information is 

### Expected Behavior

Site field is automated filled when a VLAN Group belog to a site

### Observed Behavior

Site field from vlan is empty

**Comment by DanSheps** [comment]
This is in fact not a bug and an intended behavior.

There are two ways to assign vlans to a site, through a scoped group or directly using the site attribute on the vlan.

This second method is what the site attribute is for.
