### ISSUE TITLE
2 inventory items with same names in one parent

### ISSUE THREAD

**Issue by g0ha1** [netbox-community/netbox#11549]
### NetBox version

v3.4.2

### Python version

3.8

### Steps to Reproduce

1. create A inventory item with name "item1" in some device (for example with id 32):
a_item = nb.dcim.inventory_items.create(device = 32, name = 'item1')

2. create B inventory item with name "item1" in same device (with id 32):
b_item = nb.dcim.inventory_items.create(device = 32, name = 'item1')

3. create C  inventory item with name "parent" in same device (with id 32):
c_item = nb.dcim.inventory_items.create(device = 32, name = 'parent')

4. add C item as parent to A item and save
a_item.parent = c_item['id']
a_item.save()
True

5. add C item as parent to B item and save

### Expected Behavior

Expectred the same behavior as in step 4:
b_item.parent = c_item['id']
b_item.save()
True

### Observed Behavior

Got error "Inventory item with this Device, Parent and Name already exists."

**Comment by jeremystretch** [comment]
This is intended behavior: Each child item must have a unique name. Otherwise, it may be impossible to distinguish between them.
