### ISSUE TITLE
Numbering/Ordening on interfaces on switch is off (when using Virtual chassis.)

### ISSUE THREAD

**Issue by deku-m** [netbox-community/netbox#11562]
### NetBox version

v3.3.9

### Python version

3.8

### Steps to Reproduce

1. Create several devices (switches) with same name but number them 
    - ITA-LN1-switch01-1 / ITA-LN1-switch01-2 / ITA-LN1-switch01-3
2. Create Virtual Chassis
    - Name it ITA-LN1-switch01 
3. Set member to 
    - ITA-LN1-switch01-1
4. Now check all interfaces under a member
    - ITA-LN1-switch01-1
    
**You notice that number is off icm with device name would hope it also follows that number. 
Not sure if this is a bug and fixed in 3.4.x but reading the release notes i couldnt find it.
See added screenshots.**

### Expected Behavior

The numbering on the device from switch 1/2/3 member also to be starting at Gi1/0/1 and so on.

### Observed Behavior

The numbering start randomly:
**Filtering on interfaces:**
![afbeelding](https://user-images.githubusercontent.com/37069737/213978280-475c22df-00cc-4f6a-94ba-f092b2c69482.png)
**Filtering on devicename:**
![afbeelding](https://user-images.githubusercontent.com/37069737/213978297-0ea4171f-502d-4216-bde2-f1a24a12c93d.png)

**Comment by jeremystretch** [comment]
Looks like we still had an `ordering` meta attribute set on the device interfaces table, which was ignoring the device with respect to ordering. Removing this restores the expected ordering behavior.

Thanks for submitting the bug!
