### ISSUE TITLE
Multiple files upload in Scripts

### ISSUE THREAD

**Issue by dainok** [netbox-community/netbox#11561]
### NetBox version

v3.4.2-dev

### Feature type

Change to existing functionality

### Proposed functionality

Script FileVar is supporting single file upload only. Django FileFieldForm now supports multiple files:

https://docs.djangoproject.com/en/4.1/topics/http/file-uploads/#uploading-multiple-files

Netbox FileVar should reflect Django FileFieldForm .

See also: https://github.com/netbox-community/netbox/issues/11536

### Use case

If Scripts can be executed once with multiple files, currently user has to start the Script multiple times.

**Comment by dainok** [comment]
@jeremystretch in my idea it should be possible to maintain backward-compatibility, returning a file as a default, or a list of file if more files are uploaded.
I tried to go deeper, but I lost myself reading the code.

**Comment by jeremystretch** [comment]
Native support for multi-file upload was added in Django 4.2, so I'm going to mark this as blocked by #12237 for now.

**Comment by jeremystretch** [comment]
As NetBox now has the ability to synchronize custom scripts from [remote data sources](https://docs.netbox.dev/en/stable/features/synchronized-data/) I don't believe there's still a strong need for the ability to upload multiple scripts at once. It would also greatly complicate the logic for validating scripts as they are uploaded.
