### ISSUE TITLE
Allow input over 64 Chars (200 Chars needed in my case) for name fields on both VLANs and Vitulization Interfaces.

### ISSUE THREAD

**Issue by jamesdio** [netbox-community/netbox#11573]
### NetBox version

v3.4.3

### Feature type

Data model extension

### Proposed functionality

Increase the length of the name fields on both VLANs and Vitulization Interfaces beyond the current 64 character limit (200 Chars in my case)

### Use case

Those who managing SDDC with NetBox can easily recognize where the interface is attached on and what VM the interface belongs to as soon as reading the interface name which is included with distributed port group name like below

### example 

- `NIC Seq. (Distibuted Port Group name) (VM name)`

```
vNIC 1 (vxw-dvs-120-virtualwire-16-sid-5020-LS-PRD-MSA-Service-192_168_201_0-24) (usw-prd-msa-lgs-01)
```

### Database changes

I think interface name fields are located on both ipam_vlan and virtualization_vminterface tables. but I'm not confident if there are more fields to alter.

### External dependencies

None

**Comment by jeremystretch** [comment]
I should clarify that while this makes sense for VLANs, I _don't_ agree that we should lengthen component names. In your example above, the interface name would be `vNIC 1`, and the other attributes should be recorded as other parameters (either in the description or as custom fields).

**Comment by jamesdio** [comment]
> I should clarify that while this makes sense for VLANs, I _don't_ agree that we should lengthen component names. In your example above, the interface name would be `vNIC 1`, and the other attributes should be recorded as other parameters (either in the description or as custom fields).

Thanks for your suggestion. I didn't even think about using custom fields. You've given me insights.
