### ISSUE TITLE
Add a general purpose contact assignment list view

### ISSUE THREAD

**Issue by jeremystretch** [netbox-community/netbox#11584]
### NetBox version

v3.4.3

### Feature type

New functionality

### Proposed functionality

Add an object list view for contact assignments. This list will show all contact assignments across all objects.

### Use case

Currently, it is possible to view contact assignments in the UI only by viewing specific contacts or objects. Adding this global list will enable more convenient searching for assigned contacts and enable us to embed the table in other views.

**Comment by jdavidson2021** [comment]
Could this feature be expanded to also allow an import of contact assignments to racks, devices, and virtual machines?  It is very tedious to assign contacts to objects via the UI.  You have to go to each object and select "Add a contact".

**Comment by jdavidson2021** [comment]
Sorry, I just noticed that there was a feature request for this already #11307.  I'll add my comments to that feature request.
