### ISSUE TITLE
Virtual Chassis - Add all interfaces under VC from all members

### ISSUE THREAD

**Issue by PVM-NL** [netbox-community/netbox#11590]
### NetBox version

v3.3.9

### Feature type

New functionality

### Proposed functionality

**From deku-m discussion:**
As i see value in this. But can be that its not accepted ofcourse.
For now the individual switches that are member of a VC are getting all the interfaces from the members as well.
Wondering how the idea is on a Virtual Chassis as now we create the chassis and add the members under it.

Looking at how Cisco models their "stacking switches" you notice that they also create some sort of virtual switch with all members under them and when asking, "show interfaces" the numbering is like 1/0/1-1/0/2, 2/0/1, 2/0/2. While you cant acces the underlaying second or third switch. Because it reachable by primary/master only by console. Physically they are still separated switches of course.

Isnt it an idea to add all interfaces combined under a tab in virtual chassis and let the members have their own interfaces like now? Most beautiful thing would be that, it will also create the interfaces like for example Cisco does. 
But i can imagine this isnt possible or to hard to implement.

**Mock up:**
![image](https://user-images.githubusercontent.com/120473446/214821441-9f6559e4-e731-4a6e-b5b0-9f54bd94efa7.png)

### Use case

Overview of all interfaces immediatly under Virtual Chassis instead of adding them to the physical device from other devices (switch 1/2/3/4) 

### Database changes

Dont know?

### External dependencies

None?

**Comment by PVM-NL** [comment]
> You need to designate one of the switches as the [master for the virtual chassis](https://docs.netbox.dev/en/stable/models/dcim/virtualchassis/). All member interfaces will then appear on that switch.

I know that the member(master) gets the interfaces (of all switches) but i was just thinking of having those interfaces as extentions on the VC overview as well. Like the mockup.

**Comment by jeremystretch** [comment]
This would be completely redundant to viewing the master device. (And not just interfaces; _all_ components would need to be replicated.)
