### ISSUE TITLE
Expose FILE_UPLOAD_MAX_MEMORY_SIZE as a setting in core netbox

### ISSUE THREAD

**Issue by dmulyalin** [netbox-community/netbox#11592]
### NetBox version

v3.3.9

### Feature type

New functionality

### Proposed functionality

Raised [this issue](https://github.com/netbox-community/netbox-docker/issues/897) to investigate it and was advised that FILE_UPLOAD_MAX_MEMORY_SIZE setting is not configurable, hence need to raise a request to add it to core Netbox functionality.

### Use case

To be able to upload files bigger than 2.5Mbyte to custom scripts for processing.

### Database changes

Nill

### External dependencies

Nill

**Comment by jeremystretch** [comment]
Sorry @aronbj20, I missed this earlier. All yours!
