### ISSUE TITLE
Cable trace with extra socket 

### ISSUE THREAD

**Issue by tomaszcwik1** [netbox-community/netbox#11594]
### NetBox version

3.3.7

### Python version

3.8

### Steps to Reproduce

i add relation from Patch Panel - > Socket (similar to Patch pannel Rear port + Front Port) -> then to Access point
 trace from AP is OK:
 
![image](https://user-images.githubusercontent.com/111953230/214847813-ed59538f-b174-4f0c-9199-53bfb6f45bc3.png)

but from Switch i don,t see connection from this perspective
![image](https://user-images.githubusercontent.com/111953230/214847974-a7c283fa-d290-4fe4-aeaa-69a0aeed0ec0.png)

and from trace :
![image](https://user-images.githubusercontent.com/111953230/214848040-16c03cd2-6bbf-404f-b79f-f995114d7f73.png)

but if i go to Socket 129 
![image](https://user-images.githubusercontent.com/111953230/214848217-dd7aff7c-b31f-473b-a93e-a64c2fc22b4e.png)

and then pick relation
![image](https://user-images.githubusercontent.com/111953230/214848412-be7463a9-122b-4406-bb1d-3be8e931cb6d.png)

i see two different Relater Paths
![image](https://user-images.githubusercontent.com/111953230/214848605-d42ecaf2-a0aa-4132-8c74-aaf6cd8cee62.png)

![image](https://user-images.githubusercontent.com/111953230/214848652-e6fe950f-3d8c-4ccb-9c76-aa86539a45ec.png)

 

### Expected Behavior

Proper display relation from Switch perspective

### Observed Behavior

no error just no display relation

**Comment by jeremystretch** [comment]
Thank you for opening a bug report. Unfortunately, the information you have provided is not sufficient for someone else to attempt to reproduce the reported behavior. Remember, each bug report must include detailed steps that someone else can follow on a clean, empty NetBox installation to reproduce the exact problem you're experiencing. These instructions should include the creation of any involved objects, any configuration changes, and complete accounting of the actions being taken. Also be sure that your report does not reference data on the public NetBox demo, as that is subject to change at any time by an outside party and cannot be relied upon for bug reports.

**Comment by tomaszcwik1** [comment]
i try add this in demo, but issue is not effect.
could you please analize screanshot what i prepare

**Comment by tomaszcwik1** [comment]
in device side i see proper connection,
![image](https://user-images.githubusercontent.com/111953230/214851528-d2095935-8993-43c4-985d-4ff7a955cb88.png)
but from SWT i don't see relation
![image](https://user-images.githubusercontent.com/111953230/214851720-14a65b8e-7071-4b08-b9ba-0a5af18bbed2.png)

**Comment by jeremystretch** [comment]
> i try add this in demo, but issue is not effect.

Which suggests that the issue has either likely be resolved, or your steps to replicate the behavior are inaccurate. Either way, you'll need to make some effort on your end to determine the appropriate next steps. I suggest starting by upgrading to the most recent NetBox release (v3.4.3).

**Comment by tomaszcwik1** [comment]
ok so i try to update netbox thanks
