### ISSUE TITLE
The selection of the "Wireless LAN group" is not saved in the Device Interface.  

### ISSUE THREAD

**Issue by LHBL2003** [netbox-community/netbox#11600]
### NetBox version

v3.4.3

### Python version

3.11

### Steps to Reproduce

- Create a wireless LAN group.
- Create a wireless LAN
- Create a Device
- Create a WLAN type interface
- Enter the Wireless LAN group
- Enter the Wireless LAN
- Save the interface
- Open the interface

### Expected Behavior

Wireless LAN group should be displayed

### Observed Behavior

Wireless LAN group is not displayed
--------- is still displayed.

**Comment by kkthxbye-code** [comment]
This is intended, wireless lan group is not a field on the interface model, it is purely used to filter the wireless lan.

Please see this FR which is currently planned for 3.5, which seeks to make this more obvious.

**Comment by LHBL2003** [comment]
I'm glad to hear about FR 3.5.
We have the same WLAN name at many locations, and you can tell from the group name that you have selected the right WLAN.

It's similar with the VLANs. Oh, we have the same VLANs at many locations, so it would be more transparent with the group name.

But I'm just seeing that the behaviour there is also the same. I remembered it differently.
That's why we also wrote the group name in front of the VLAN name. 
The display then shows the recognition:

E.g.

Groupname | vLanName (2000)

Translated with www.DeepL.com/Translator (free version)
