### ISSUE TITLE
Report failures are amibigous

### ISSUE THREAD

**Issue by abhi1693** [netbox-community/netbox#11614]
### NetBox version

v3.4.3

### Feature type

Change to existing functionality

### Proposed functionality

Add tracebacks to the logger when an exception is raised

### Use case

I wrote a report with pre_run that raises exceptions when prerequisites are not met. The console only displayed `Error during execution of report test.myreports.Report001`. This does not provide any context of why the execution failed.

**Comment by jsenecal** [comment]
Hi @abhi1693 , 
Stack traces can often leak sensitive information. I would rather opt for the report developer to properly handle exceptions when writing them to begin with.
Let us know what you think.

**Comment by abhi1693** [comment]
Then, can a better exception logger be added? Something like 

```
try:
  ...
except Exception as e:
  logger.error(e)
```

**Comment by jeremystretch** [comment]
I agree with @jsenecal that we should not decide on behalf of the script author how much detail is prudent to provide in the event of an error. The onus is on the author to handle errors that result from script execution, and IMO we have sufficient logging utilities in place. Happy to discuss further if anyone would like to propose a specific improvement in a new FR.
