### ISSUE TITLE
Cannot add tagged VLAN from other site on multiple port edit

### ISSUE THREAD

**Issue by marinus81** [netbox-community/netbox#11619]
### NetBox version

v3.4.2

### Python version

3.8

### Steps to Reproduce

I have come across an issue adding VLANs to an interface if I arrive at the interfrace configuration page from the  DEVICES -> Device Components -> Interfaces page, and try to edit multiple interface from the list (on the same device). I can only add VLANs as tagged VLANs if they are allocated to the same Site as the Device. This issue does not exist if I go to the Device Page and from there the Interfaces sub-page.

1. Create Site "SITE_TEST"
2. Create vlan 10 in Site "SITE_TEST"
3. Create vlan 20 in no Site
4. Create a device "DEV_TEST" in Site "SITE_TEST" with at leasttwo interfaces
5. Navigate to DEVICES -> Device Components -> Interfaces
6. Filter for all interfaces from device "DEV_TEST"
7. OK: Edit single interface -> 802.1Q Switching Mode: Tagged -> Tagged VLANs includes  VLAN 10 and 20 -> as expected
8. NOK: Edit multiple interfaces -> 802.1Q Switching Mode: Tagged -> Tagged VLANs includes ony  VLAN 10 -> not expected

### Expected Behavior

Same behavior between "Device -> Interfaces sub-page" and "DEVICES -> Device Components -> Interfaces + filter for a device"

### Observed Behavior

"Device -> Interfaces sub-page" - I can add VLANs from same site or VLANs without Site assigned
"DEVICES -> Device Components -> Interfaces + filter for a device" - I can only add VLANs from same Site as Device

**Comment by HolySephi** [comment]
This bug is also present in editing a prefix. Only site specific VLANs are shown - not site-less VLANs.
I guess because the site field for the prefix is also a filter for the VLAN field.
If should always list site-specific VLANs and site-less VLANs (for example if you want prefixes to be assigned to a site but not VLANs)

**Comment by dhenschen** [comment]
I'm interested in taking ownership of this issue.

I've ran into this before while using NetBox and would like to see it fixed.

**Comment by dhenschen** [comment]
I opened https://github.com/netbox-community/netbox/issues/12622 to track a related bug that impacts the creation and import of prefixes in IPAM. The fix for that issue is different than what will be required for this issue.
