### ISSUE TITLE
Add `request` context to Reports

### ISSUE THREAD

**Issue by abhi1693** [netbox-community/netbox#11612]
### NetBox version

v3.4.3

### Feature type

Change to existing functionality

### Proposed functionality

I'm not sure at the implementation but similar to Scripts implementation. More discussion can be found at: https://netdev-community.slack.com/archives/C01P0FRSXRV/p1674851789623179

### Use case

I want to create reports which also sends the data to external tools. From such tools, I want the user's to be able to click on the objects in the message and return back to NetBox. Currently, this is not possible to do as the base URL is not accessible.

As bonus, I'd like to have the following implementations as well:

- Request User
- When a job is scheduled, the request context is still available in automated runs

**Comment by jsenecal** [comment]
Please expand on the _proposed functionality_ as the slack link may not be available down the road. But otherwise I think the general consensus based on that conversation was that this would be a good thing :)

**Comment by abhi1693** [comment]
@jeremystretch Could this be taken up for 3.5 release within the new reports functionality?

**Comment by abhi1693** [comment]
Since this hasn't had much traction, we may not need this due to deprecation in https://github.com/netbox-community/netbox/issues/12510

**Comment by jeremystretch** [comment]
Agreed; I'm going to punt on this.
