### ISSUE TITLE
Global search not returning prefixes that contain an IP address

### ISSUE THREAD

**Issue by c0herent** [netbox-community/netbox#11627]
### NetBox version

v3.4.3

### Python version

3.8

### Steps to Reproduce

1. When logged into the NetBox UI, enter a specific IP address in the global search box at the top, such as 10.44.20.34
2. Click the search button or hit enter

### Expected Behavior

If there is a record for the IP address, that record should be returned.  If there is a prefix that contains the IP address, that prefix should also be returned.

If there is no record for the IP address, but a prefix containing that IP address exists, the prefix should be returned.

### Observed Behavior

If there is a record for both the IP address and the prefix, only the IP address is returned.  If there is only a record for the prefix but not the specific IP address, "- no results found-" is returned.

This issue started to occur after upgrading from NetBox 3.1.8 to 3.4.3.  This breaks one of our largest use cases for NetBox, which is being able to easily find what prefix an IP address belongs to.

**Comment by jeremystretch** [comment]
Thank you for submitting this issue, however it appears that this topic has already been raised. Please see issue #11315 for further discussion.

**Comment by c0herent** [comment]
Thanks!  I didn't see that issue when searching but it does match the issue I am having.  I will reference that thread going forward.
