### ISSUE TITLE
Hide WIFI password

### ISSUE THREAD

**Issue by deku-m** [netbox-community/netbox#11623]
### NetBox version

v3.4.3

### Feature type

Change to existing functionality

### Proposed functionality

Is it possible to hide the WIFI password as well? As now when you add the password it is added as plain-text.
Can this be a hidden password with "*********" and icon on the side to make it visible?

Or does it needs to be moved to "secret(store) plugin?

### Use case

Well i think passwords dont need to be visible until you want it to be. 
The best part is that you ofcourse need to be logged in to see this. 
But some think this needs to be secure and im not sure if this is also plain text in the database itself? 

### Database changes

Probally yes encrypted and hidden

### External dependencies

Maybe the secret plugin.

**Comment by abhi1693** [comment]
I extended the original secretstore plugin to allow to be used with any object in NetBox. You can check it at https://github.com/Onemind-Services-LLC/netbox-secrets if this resolves the issue

**Comment by jsenecal** [comment]
It would definitely be quite the undertaking to re-implement reversible encryption in the database for this field. However a UI change to _hide_ and _show_ the password [should be fairly easy to do](https://www.w3schools.com/howto/howto_js_toggle_password.asp).

**Comment by deku-m** [comment]
> I extended the original secretstore plugin to allow to be used with any object in NetBox. You can check it at https://github.com/Onemind-Services-LLC/netbox-secrets if this resolves the issue

I need to look into that. Youu need additional config in plugin_config right?

**Comment by deku-m** [comment]
> It would definitely be quite the undertaking to re-implement reversible encryption in the database for this field. However a UI change to _hide_ and _show_ the password [should be fairly easy to do](https://www.w3schools.com/howto/howto_js_toggle_password.asp).

That could be a valid in between solution yes

**Comment by abhi1693** [comment]
> > I extended the original secretstore plugin to allow to be used with any object in NetBox. You can check it at https://github.com/Onemind-Services-LLC/netbox-secrets if this resolves the issue
> 
> I need to look into that. Youu need additional config in plugin_config right?

Yes, you need to configure the `apps` to which the secrets should be applied. To provide some backwards compatibility, the defaults are device and virtual machine. You can provide any object from NetBox as the list of options and it'll work from there including the API calls.

**Comment by jeremystretch** [comment]
I'm going to mark this as open for volunteers with the understanding that the scope of the FR is merely to toggle visibility of the field value, and does not encompass any form of encryption or other obfuscation.

**Comment by deku-m** [comment]
I forgot to respond to the solutions that abhi1693 also provided with secrets plugin. 
My workaround for that was to place a comment in the PSK with remark to "See Secrets". Because with the plugin it provide a new view (Secrets) but that works ok. 

Dont know if the option is to inject the secrets, the create WPA-PSK field in the provided field from netbox from the plugin?
But then again you also have a dependency from the plugin.

**Comment by jacobpfickes** [comment]
I'd like to pickup this FR if it still available

**Comment by jacobpfickes** [comment]
@jeremystretch sorry for the late reply. My laptop actually broke so I need to save up for a new one. Feel free to release this or assign to someone else for now.

**Comment by decoupca** [comment]
I'll take this one
