### ISSUE TITLE
Cable trace in cable view

### ISSUE THREAD

**Issue by CaptainBalou** [netbox-community/netbox#11622]
### NetBox version

v3.4.3

### Feature type

Change to existing functionality

### Proposed functionality

It would be awesome to have the possibility to click on tracing a cable while viewing the cable (e.g. https://localhost/dcim/cables/1/)

![image](https://user-images.githubusercontent.com/17015872/215703252-3cdb0b51-04e5-4ccb-8ddc-f1ab56fbded0.png)

as well as on the list view

![image](https://user-images.githubusercontent.com/17015872/215703468-eeece04c-9102-41b2-be0d-daccb64159f7.png)

### Use case

Being in the data center, seeing a cable without knowing whats connected would involve searching for the cable ID printed on the cable label. After finding it in Netbox it would be nice to see a trace icon ![image](https://user-images.githubusercontent.com/17015872/215700241-748e7062-4742-4f74-b49e-c5771be6146c.png) in the list overview as well as in the details page of each cable to be able to directly get a trace to each end without the need of click of one connected interface to click on trace there (see example screenshots above in the proposal).

**Comment by jeremystretch** [comment]
I'll note that cable traces need to start from a specific termination point (rather than from the cable itself) to imbue a direction of the trace, but we can add trace buttons to the termination objects.

**Comment by PieterL75** [comment]
I was looking into this.. The only place that I can add the trace, is on the Cable page, on the interface (if shown).
![image](https://user-images.githubusercontent.com/74899468/221815450-256193f7-1b01-4970-a994-cd92ef189fbd.png)

As a cable can have multiple interfaces on each termination side, it is not possible to create a 'trace' button for the 'cable' or show it in the cable list.
Unless we assume that is the a_terminations[0] or b_terminations[0] exists, that we can start the trace from there..

**Comment by PieterL75** [comment]
2 options for the 'list' view : 
![image](https://user-images.githubusercontent.com/74899468/221866739-cc5ca5bf-2811-4f09-95c7-543bed04dfc3.png)
either a button next to the termination or a dropdown with all possible traces of that cable.
The first one is easy, then I can decide in the python code of the interface is a 'interface/front/rear', other types are not traceable. The dropdown is more difficult (I think) as it there is no type of the termination/cable passed to the django template

**Comment by PieterL75** [comment]
I think I have something that works. See PR.. 
If we start the trace of any termination of that cable, we get the trace. You won't be able to trace from A-Z or Z-A, just the first valid iface is picked.
In the end, the result is that the cable is shown.

**Comment by CaptainBalou** [comment]
@jeremystretch @PieterL75 

Hello,

I really appreciate that you guys are thinking about this directly. Thanks. @PieterL75 is even faster in changing the code then I had the time to look at the proposals. Awesome. :-)
Because the list is not very crowded I would prefer the icon directly in the list. But a drop-down would also be good. Both makes it easier for users to reach the trace with fewer clicks.

Kind regards
Marco
