### ISSUE TITLE
Add HTTP redirect to reference Apache configuration

### ISSUE THREAD

**Issue by jeremystretch** [netbox-community/netbox#11638]
### Change Type

Addition

### Area

Installation/upgrade

### Proposed Changes

Extend the [reference Apache server configuration](https://github.com/netbox-community/netbox/blob/develop/contrib/apache.conf) that ships with NetBox to include a rule that redirects all HTTP requests to HTTPS. (This is already included in the nginx config.)

**Comment by rganascim** [comment]
I can add this configuration if you allow it.

Configuration sequence:
- add the virtualhost for the port 80 in the netbox file (redirect using the mod_rewrite way)
- disable the default web site: sudo a2dissite 000-default
- enable mod_rewrite: sudo a2enmod rewrite
- restart apache2: sudo systemctl restart apache2

Add to apache2.conf netbox template:
```
<VirtualHost *:80>
   ServerName netbox.same.as.443.port
   RewriteEngine On
   RewriteCond %{HTTPS} !=on
   RewriteRule ^/?(.*) https://%{SERVER_NAME}/$1 [R,L]
</VirtualHost>

```
