### ISSUE TITLE
Multiple Object Type Filter on ChangeLog List just uses last one 

### ISSUE THREAD

**Issue by SignalR-Dev** [netbox-community/netbox#11631]
### NetBox version

v3.4.3

### Python version

3.8

### Steps to Reproduce

1. Create a Vm and a Device in the dev enviroment
2. Filter the list of changes to display VM and Device
[dev](https://demo.netbox.dev/extras/changelog/?changed_object_type_id=9&changed_object_type_id=59)

### Expected Behavior

The List should be Filtered by both Content Types

### Observed Behavior

Just the last Content Type of the Query gets honored

**Comment by jeremystretch** [comment]
The same limitation is present when filtering journal entries as well.
