### ISSUE TITLE
Missing example diagram in docs/features/facilities.md

### ISSUE THREAD

**Issue by vicbreen** [netbox-community/netbox#11648]
### Change Type

Correction

### Area

Features

### Proposed Changes

[Permalink to the .md](https://github.com/netbox-community/netbox/blob/fb2771370cdf7f1d17db8e0f3985785333372d79/docs/features/facilities.md)

Very minor issue. There's just a missing example diagram referenced in the below "!!! tip".

> !!! tip "Devices" You'll notice in the diagram above that a device can be installed within a site, location, or rack. This approach affords plenty of flexibility as not all sites need to define child locations, and not all devices reside in racks.

**Comment by jeremystretch** [comment]
Sorry, I don't follow. What do you believe is missing? The note references the diagram at the top of the page.

**Comment by vicbreen** [comment]
Ah, I totally misunderstood it. My bad!
