### ISSUE TITLE
Creating interface with duplicate name does not return error

### ISSUE THREAD

**Issue by koratfood** [netbox-community/netbox#11650]
### NetBox version

v3.4.3

### Python version

3.10

### Steps to Reproduce

1. Create a device called "Device1"
2. Create an interface on the device called "Ethernet1"
3. Try to create another interface on the device called "Ethernet1"

### Expected Behavior

Netbox throws an error saying names cannot be duplicated.

### Observed Behavior

"Add a new interface" page reloads, no error is thrown/shown.

**Comment by jeremystretch** [comment]
Looks like the error message is getting attached to the individual model form and not replicated to the "parent" form that enables multi-component creation.
