### ISSUE TITLE
Updated files are not updated when syncing a DataSource

### ISSUE THREAD

**Issue by kkthxbye-code** [netbox-community/netbox#11659]
### NetBox version

v3.5.0-dev

### Python version

3.10

### Steps to Reproduce

1. Create a DataSouce pointing to a local directory
2. Create a file in the local directory
3. Sync the DataSource
4. Change the contents of the file in the local directory
5. Sync the DataSource again

### Expected Behavior

The contents of the file should be updated.

### Observed Behavior

The file is not updated, only the file hash is.

I believe this:

https://github.com/netbox-community/netbox/blob/a46112333666660db6d899445b13f8ea97423d52/netbox/core/models/data.py#L171

Should be changed to this:

```updated_count = DataFile.objects.bulk_update(updated_files, ['hash', 'last_updated', 'size', 'data'])```

**Comment by jeremystretch** [comment]
Whoops, yeah. I had stripped those out at some point during testing. Thanks!
