### ISSUE TITLE
Allow virtual interface objects in separate VDCs to have the same name

### ISSUE THREAD

**Issue by koratfood** [netbox-community/netbox#11651]
### NetBox version

v3.4.3

### Feature type

Change to existing functionality

### Proposed functionality

Allow multiple virtual interfaces (i.e. types Bridge, LAG and Virtual) on a single device to be created with the same name as long as each of them are tied to separate Virtual Device Contexts.

### Use case

Ability to model real-world Cisco Nexus switch deployments (e.g. 7000 series) where, for example, SVIs and Port-channels can exist on multiple VDCs with the same name.

### Database changes

Unknown as I am not a programmer, but I would expect some challenges aligning such a change with uniqueness constraints.

**Comment by jeremystretch** [comment]
Further research and discussion is needed before this can proceed. NetBox currently functions with the understanding that interfaces are unique per device/VM, and changing this could have wide-reaching effects across the application. The first step in this proposal would be to identify what those effects would be and how they can be mitigated.

**Comment by koratfood** [comment]
Could the per-device interface uniqueness constraint be based on interface object ID rather than interface name? That way, the actual interfaces remain unique in NetBox even though they have a name attribute in common.

Bear in mind I have very little knowledge of NetBox' (let alone Django's) inner workings, so I appreciate the answer potentially being something along the lines of "that's not how it works".
