### ISSUE TITLE
Add Status column to Module Bays tables

### ISSUE THREAD

**Issue by sleepinggenius2** [netbox-community/netbox#11652]
### NetBox version

v3.4.3

### Feature type

Change to existing functionality

### Proposed functionality

A *Status* field was added to *Modules* in #10371. I am proposing making that field available as a column on the *Module Bays* tables (full list and tab under a device). There is existing precedent for *Module* fields to be added as column options for those tables, like *Serial number* and *Asset tag*. I would additionally propose adding that column as one of the defaults on those tables, as was done for the *Modules* table.

### Use case

Adding this as a table column would increase its visibility and make it easier to understand at a glance the status of all the modules in a shelf. Currently, a user would need to click into a given module in the list to see its status, which becomes cumbersome on a shelf with many modules.

### Database changes

None

### External dependencies

None

**Comment by jeremystretch** [comment]
It should be straightforward to add the table column, however a solution will be needed to display the badge label color correctly.

**Comment by abhi1693** [comment]
I'll take a stab at this.
