### ISSUE TITLE
Multi-termination jumper deletion creates front port inconsistency

### ISSUE THREAD

**Issue by marcusyuri** [netbox-community/netbox#11667]
### NetBox version

v3.4.4

### Python version

3.8

### Steps to Reproduce

1. Create 2 devices with interfaces, say for example Router1 and Router2 (can use for example the Juniper MX80 from netbox demo site)
2. Create 4 devices with several front ports and one rear port, say for example PP01, PP02, PP03 and PP04 (can use for example Generic 48 Fiber Panel from netbox demo site)
3. Connect PP01 rear port <-- --> PP02 rear port and PP03 rear port <-- --> PP04 rear port
4. Connect Router1 interface with 2 PP01 front port and Router2 interface with 2 PP04 front port 
![Trace from router 1](https://user-images.githubusercontent.com/54281804/216821384-ebcb9afb-0457-4dc6-b8c6-91fa17bfdf3b.png)
![Trace from router 2](https://user-images.githubusercontent.com/54281804/216821387-d734375f-28b7-4f6c-977e-3a98f380222d.png)
5. Connect front PP02 front port 1 <-- --> PP03 front port 1, and a second cable from PP02 front port 2 <-- --> PP03 front port 2
6. 
![Jumper](https://user-images.githubusercontent.com/54281804/216821767-951ea5df-2bb2-4b5f-82fd-40d7315110be.png)
7. Repeat the trace. Now you see 'split path'. 
![Splt path](https://user-images.githubusercontent.com/54281804/216821909-038ff6fd-8714-467b-97a3-379219cbab62.png)
8. Click on the first node. Now you can see an empty trace.
9. 
![Problem 1 - Empty split path trace](https://user-images.githubusercontent.com/54281804/216822041-4695c801-eded-45be-b9e2-e8c28dd2b869.png)
10. Delete the connections  PP02 front port 1 <-- --> PP03 front port 1, and a second cable from PP02 front port 2 <-- --> PP03 front port
11. Repeat the trace from router1 interface
![Problem 2 - Missing front port from cable tracing](https://user-images.githubusercontent.com/54281804/216822190-1d026294-a884-420e-bdaf-a2a4f4ebf1ac.png)

### Expected Behavior

Problem #1. We see split path between PP02 and PP03.
Problem #2. After deleting the cables between PP02 and PP03, and repeating the trace, the front ports disappears from the PP02 and PP03, and the split path message remains, even if the are no cables.

### Observed Behavior

Problem #1 After create two jumpers from PP02 <--> PP03, the trace from Router1 interface should by complete to router 2 interface, since we make a multipath conection on each interface to the patch panels (use case: model a jumper from an optical interface using a duplex fiber cable - TX and RX), and also make two discrete single fiber jumpers between PP02 and PP03.
Problem #2 After we delete the two discrete single fiber jumpers between PP02 and PP03, the trace starting from router interface should be exact the same as before the creating of the jumper, showing the ports 1 and 2, without any split path message.
![Problem 1 - Empty split path trace](https://user-images.githubusercontent.com/54281804/216823696-d4846888-b352-4e71-95cb-4687554c123f.png)
![Problem 2 - Missing front port from cable tracing](https://user-images.githubusercontent.com/54281804/216823699-aa380ff7-0d1d-421f-934d-3b22ad9f7299.png)

**Comment by dboissat** [comment]
Hi, 

I currently working on my Netbox to modify many paths with the point-multipoint cables and during my first tests, I observed a similar issue.
You can't trace a path if somewhere you have two different cables.
You need to create a multipoint-multipoint cable between your PP02 and PP03: 2 front ports to 2 front ports.

Please note, after creating this multipoint-multipoint cable, an error "path split" is possible.
But I found a tip to fix the issue on my side. I selected the cable "rear port" or "rear splice" and I changed his status: from "connected" to "planned" and to "connected" again. 

On my side, in all cases, the path is correctly working after that.

For example, in my case, I needed to change the state of cables 5132 and 5109 and the path will be fixed correctly.
![image](https://user-images.githubusercontent.com/124785245/217520318-da73759a-5278-4d43-8196-eb50b093db02.png)

**Comment by marcusyuri** [comment]
I make some additional testing, and found another workaround for the problem #1, but the bug remains for the problem #2.

The workaround, in my example, is to use a double termination cable between PP02 front ports 1 and 2, and PP03 front ports 1 and 2, as show below - Cable #134:

![Duplex cable](https://user-images.githubusercontent.com/54281804/218092441-9c0da25d-d79c-4170-ba7b-31377e4400fd.svg)

But the problem #2 remains - if I create two separates cables from PP02 front port 1 <-- --> PP3 front port 1 and PP02 front port 2 <-- --> PP3 front port 2, as see in below manually editted diagram:

![Expected Cable Trace](https://user-images.githubusercontent.com/54281804/218093540-a5909dac-5753-43d1-91ad-76311754e046.png)

This is the expected cable trace, but instead we get a split path. The real problem is that even if we delete the two separates cables, and recreate the connection using a duplex cable, and change back and forth the status from connect to planned and vice-versa, we cannot get the trace complete, as the first picture on this post. It appears that the deletion of the simplex cable breaks (or delete) something else, and we cannot go back to the previous netbox database state, before we create these two cables.

**Comment by jaylik** [comment]
@jeremystretch - Would it be possible to fix this bug anytime soon? This is causing major headache with fiber joint enclosures modeled with 1:1 cables between different fibers.

**Comment by marcusyuri** [comment]
I understand that the problem #1 is not supported (#10355), but the problem #2 remains - the front ports disappears if you delete the cable...

**Comment by jeremystretch** [comment]
Marking this as blocked by #11079 for now. We can re-evaluate once #13337 has been merged.

**Comment by jeremystretch** [comment]
Confirmed that this has been addressed by PR #13337 as the fix for #11079, and will be fixed in v3.6.3.

**Comment by marcusyuri** [comment]
Congratulations, Jeremy and all Netbox Team! It is working flawless. Also confirmed that the port inconsistency after delete was fixed, as we can see in the following picture - Ports 1 and 2 of PP02 now apears correctly after deleting the cable.

![Fixed Port Inconsistency After Delete](https://github.com/netbox-community/netbox/assets/54281804/f6ae4237-00e9-43d3-8b3e-4bca653b708a)

Thanks for the fix!
