### ISSUE TITLE
Block availability and creation of IPs in IP Ranges

### ISSUE THREAD

**Issue by iamjla** [netbox-community/netbox#11678]
### NetBox version

v3.4.2

### Feature type

Change to existing functionality

### Proposed functionality

We would suggest "IP Ranges" gets the following 2 new booleans:

 - "Exclude from Available IPs"
     This still allows creation of IPs of this IP Range but prohibits them from being used in available ip logic (API&UI)

 - "Block creation of IPs in this Range"
     As the name suggests, any IP creation in this range should be blocked

### Use case

General IP Ranges for DHCP
or
Exclude ranges for automatic short lived DHCP deployments to avoid collisions which later get proper IPs assigned
and
To avoid blocking e.g. 2000 (or IPv6-scale amounts of) IPs in the database manually

Something similar came up in https://github.com/netbox-community/netbox/discussions/7516 though it was about utilization and making them unavailable for other uses.

https://github.com/netbox-community/netbox/issues/9763 captures a possible UI solution

**Comment by do9xe** [comment]
We're also looking into how we could leverage the ranges to define DHCP-Pools for our deployments. I also thought about using the "is a pool" flag, but it has another purpose. I'd love to see a possibility to model DHCP-Ranges in NetBox.

**Comment by jsenecal** [comment]
Thinking this should be handled by what would be done in https://github.com/netbox-community/netbox/issues/9763.

Feel free to discuss your booleans in there, or, any additional requirements.
