### ISSUE TITLE
Add Position to Cable trace

### ISSUE THREAD

**Issue by davidoffx3m** [netbox-community/netbox#11671]
### NetBox version

v3.4.4

### Feature type

Change to existing functionality

### Proposed functionality

It would be great to add the Position to Cable trace Output, that will show the Rack Unit. Output should contain following information:
Site/Location/Rack/Position

### Use case

This can help to provide information for patching and troubleshooting connection in DataCenter for local staff.

**Comment by DanSheps** [comment]
I would be willing to take this on.  It might actually make things slightly more simple for some of the logic within the cable trace system.

**Comment by DanSheps** [comment]
Going to wait on this until the other cable SVG work is done.

**Comment by DanSheps** [comment]
Blocked by PR: #14750

**Comment by jeremystretch** [comment]
@DanSheps could you take another look at this now?

**Comment by davidoffx3m** [comment]
Any updates regarding the issue?

**Comment by DanSheps** [comment]
Thanks for the bump.  I re-read this and completely missed-understood the goal last time for some stupid reason.  Simple one, should have a PR in for it shortly.
