### ISSUE TITLE
Import Device/Module Weight

### ISSUE THREAD

**Issue by danner26** [netbox-community/netbox#11670]
### NetBox version

v3.4.4

### Feature type

Change to existing functionality

### Proposed functionality

Since we already have weight as an option, we now need to add the ability to import weight data via the CSV/YAML/JSON import. Module Types and Device Types currently do not have weight as an option to import.

NetBox devicetype-library currently has this implemented using [weight value and unit](https://github.com/netbox-community/devicetype-library/blob/7bf2f659b3695a11750e85cd8bc16ae4b5741915/device-types/Inspur/NF5180M6.yaml). We can modify the devicetype-library if needed to support this import functionality.

### Use case

Adding weight to an object is currently supported in the single import option, but not within the bulk import.

**Comment by dhenschen** [comment]
I noticed that this issue is currently marked as "needs owner" and I would like to volunteer to take ownership of it. This is my first contribution to Netbox, but I am eager to learn and contribute to the project.

**Comment by jeremystretch** [comment]
Thanks @dhenschen!
