### ISSUE TITLE
Show containing Prefixes and Aggregates when doing a site-wide partial search

### ISSUE THREAD

**Issue by kkthxbye-code** [netbox-community/netbox#11685]
### NetBox version

v3.4.4

### Feature type

Change to existing functionality

### Proposed functionality

Relevant bug report: https://github.com/netbox-community/netbox/issues/11315
Relevant discussion: https://github.com/netbox-community/netbox/discussions/11665

In short the goal is to find prefixes and aggregates based on the input, if the input is parsable as an netaddr.IPNetwork.

### Use case

It is useful to get the parent prefix if searching for both existing and non-existent IPAddresses and more closely matches the previous global search. More reasoning can be found in the linked bug report.

### Database changes

While no actual database changes should be necessary, changing the CachedValue.value field to a custom field type inherating TextField generates a migration, but there should be no actual SQL schema changes. See the PR.

### External dependencies

None

**Comment by PieterL75** [comment]
I'm really waiting for this one before I push 3.4 to production. The search results are indeed lacking this information and is a requirement for my users. 
Too bad I did not catch that in the beta tests I did. Just overwhelmed by the speed and nice results :-)
