### ISSUE TITLE
Limiting access to "Other" objects (Tags, Config Contexts)

### ISSUE THREAD

**Issue by stavr666** [netbox-community/netbox#11695]
### NetBox version

v3.4.3

### Feature type

New functionality

### Proposed functionality

Add ability to assign limited access to Tags and Config Contexts.

Assigning Tenant and use it as access role filter is fine, but as it's actually can cause recursive references, new field possible needed.

### Use case

While adopting config contexts (bound to tags) to store device and VM options for external orchestrators and monitoring, we encountered and issue, when we can either add user ability to change any CC/tags, or block all changes.

We need mechanics, working similar to other objects in Netbox: limiting access to several CC and/or tags. This way, changing network configs (bound to network devices, already limited in DCIM) will be possible by person with access to network devices, and changing VM CC's will be possible only by virtualization team.

**Comment by jeremystretch** [comment]
Closing this as there's been no further response from OP.
