### ISSUE TITLE
Support custom fields on interfaces at the device type level

### ISSUE THREAD

**Issue by samschmitt22** [netbox-community/netbox#11705]
### NetBox version

v3.4.4

### Feature type

Data model extension

### Proposed functionality

Netbox has previously added support for creating custom fields at the interface level for devices. However these are not supported at the device type level. I.E. interfaces on device type cannot have custom interfaces.

### Use case

We track several additional fields such as NIC chipset, NIC PCIe address, etc that would be well suited to track at the device type level since they are associated with different device models. Currently we have to manually populate those fields each time we create a new device of that device type.

**Comment by jeremystretch** [comment]
Thank you for submitting this issue, however it appears that this topic has already been raised. Please see issue #9243 for further discussion.
