### ISSUE TITLE
add REMOTE_AUTH_EMAIL_HEADER and REMOTE_AUTH_NAME_HEADER

### ISSUE THREAD

**Issue by davama** [netbox-community/netbox#11708]
### NetBox version

v3.4.4

### Feature type

Change to existing functionality

### Proposed functionality

There has been some great work on the REMOTE_AUTH portion, thank you for this!!

My request:

Map the `REMOTE_AUTH_EMAIL_HEADER` header to the email field in an account's profile.
Same with `REMOTE_AUTH_NAME_HEADER` header, map it to the First/Last name of the account's profile

### Use case

The account data for any particular profile would be now complete with all their respective fields filled. This is mostly cosmetic.

### Database changes

n/a

### External dependencies

n/a

Thank you,
Dave

**Comment by jeremystretch** [comment]
This looks like it was implemented in NetBox v3.4.9 under #12226. Not sure why that FR was never identified as overlapping with this one.
