### ISSUE TITLE
Accessing saved filters gives permissions error

### ISSUE THREAD

**Issue by FliesLikeABrick** [netbox-community/netbox#11716]
### NetBox version

v3.4.4

### Python version

3.8

### Steps to Reproduce

Database was upgraded from 2.x to current over time, not a fresh install.  In a clean install of netbox (or in a brand new containerized environment and database), this issue is not seen
Browse to prefixes
Switch to "Filters" tab
Click on "Saved Filter"
Observe error: Error Fetching Options for field 'filter_id'
   You do not have permission to perform this action

### Expected Behavior

User should be able to access or define saved filters,  or in our case observe that none exist yet
-- or --
NetBox documentation should be improved to explain the permissions that need to be granted to make this feature work after an upgrade that provides the new feature.

### Observed Behavior

Error Fetching Options for field 'filter_id'

You do not have permission to perform this action

**Comment by FliesLikeABrick** [comment]
I originally posted this as a discussion at https://github.com/netbox-community/netbox/discussions/11654

**Comment by jeremystretch** [comment]
Thank you for opening a bug report. Unfortunately, the information you have provided is not sufficient for someone else to attempt to reproduce the reported behavior. Remember, each bug report must include detailed steps that someone else can follow on a clean, empty NetBox installation to reproduce the exact problem you're experiencing. These instructions should include the creation of any involved objects, any configuration changes, and complete accounting of the actions being taken. Also be sure that your report does not reference data on the public NetBox demo, as that is subject to change at any time by an outside party and cannot be relied upon for bug reports.

**Comment by FliesLikeABrick** [comment]
@jeremystretch  this issue is inherently not reproducible in a clean install, I mentioned that in the post.  This currently is a requst for some guidance that would allow me to investigate further, or allow me to open a PR so that I may improve documentation.

I need some information about the permissions model associated with Prefix "saved filters" - as all of our users get an error when clicking on that field.    Admin>Users>Permissons may be missing entries that allow this feature to work, which were missing during database upgrades.  However there does not appear to be documentation on what permissions are needed.  Browsing "Object Types" in /admin/users/objectpermission/add/ -- there are no entries pertaining to custom filters.

If any guidance can be provided on the fundamental permissions needed to allow this feature to work, I can dig in more and figure out how to shape an issue that is either about missing documentation, or missing database migration.  Hopefully this input helps make this issue more actionable
