### ISSUE TITLE
Searching for a Cross-Connect ID links to the  Site instead to the circuit-termination

### ISSUE THREAD

**Issue by lairsdragon** [netbox-community/netbox#11723]
### NetBox version

v3.4.4

### Python version

3.10

### Steps to Reproduce

- Add a Cross-Connect ID to a Cirtuit Termination 
- Search for the ID
- Inspect the Link Target under Object 

![cross-connect-search](https://user-images.githubusercontent.com/1344232/218131484-0f867bf6-f56a-4e42-a67f-225df046a5c8.png)

### Expected Behavior

Under Object I expect a Link back to the Circuit
![circuit](https://user-images.githubusercontent.com/1344232/218131491-0ae74481-e02c-4045-801f-8ee30a221f45.png)

### Observed Behavior

Under Object a Link to the Site is generated

**Comment by kkthxbye-code** [comment]
> Under Object I expect a Link back to the corresponding Circuit Termination

There's no details nor list pages for CircuitTerminations. Can you provide an example URL of what you want it to link to?

In any case the current functionality is intended, and you probably need a feature request if you want to suggest that it should be changed.

**Comment by lairsdragon** [comment]
I missed that there is not detail page for Cirtciut Termination.

A link back to the matching Circuit would be helpful. At the moment I have to visit all Circuits of a site and  that way its not better than what I could have  done without the search.

I have edited the initial command and edited screenshots from a test in the demo site.

**Comment by jsenecal** [comment]
So technically this is pretty simple and makes sense as we only need to change from which related object the url is generated in here:
https://github.com/netbox-community/netbox/blob/develop/netbox/circuits/models/circuits.py#L201

**Comment by PieterL75** [comment]
This is a common thing.. the relation of a circuit is to the site.. Clicking that link always brings you to the Site object.
It would be more intuitive that clicking a A/Z side brings you to the Circuit page in stead of the 'Site'

**Comment by jsenecal** [comment]
@PieterL75 Circuit Table Side A/Z Links to a `Provider Network` if the circuit termination is of the other kind. What's your thought on that?

**Comment by jeremystretch** [comment]
Seems like the simplest solution is to change the default representation of a CircuitTermination to "$circuit: Termination A/Z" and have it link to its parent circuit. This should only impact cases where circuit terminations are shown independently (e.g. in search results or the change log); it won't affect the circuits list, which shows the A and Z terminations for each circuit.
