### ISSUE TITLE
Aggregate utilization should not consider a prefix of type `container` as 100% utilized

### ISSUE THREAD

**Issue by BrunoBlanes** [netbox-community/netbox#11736]
### NetBox version

v3.4.4

### Feature type

Change to existing functionality

### Proposed functionality

Whenever calculating prefix/aggregate utilization, do not consider a prefix with status of `container` as 100% utilized, instead take into account its child prefixes and addresses.

## The reasoning behind it

As per the [documentation](https://demo.netbox.dev/static/docs/models/ipam/prefix/#status), the `container` prefix exists only for **organizational** purposes and therefore has a [special](https://demo.netbox.dev/static/docs/features/ipam/#utilization-stats) way of calculating utilization.

By that definition, the general understanding is that this is not a _real_ prefix, it shouldn't exist on the actual network, it is purely for organizing child prefixes which in turn **are** real. And it makes sense for it to be this way, but this is inconsistent in some areas.

## Our use case as an ISP

We have been allocated some prefixes by our local RIR; they live in the aggregate menu. On the prefix menu we create several `/24` prefixes, as those are a common way to divide the network due to how BGP works. Not all of these are actually reachable on the network, most of them have been created on Netbox as a `container`.

The idea behind it being that Netbox's prefix utilization feature would be able to help us properly manage allocations to our network.

## The problem

**Prefixes of type `container` are considered, by their parent aggregate, as 100% allocated.**

<br>

I assume that containers are supposed to be the root prefix, therefore nesting these, although possible, shouldn't be done. However, by default, prefixes are children of aggregates, and they too have a utilization meter.

In the afore-mentioned use case this causes our aggregates utilization to always be set to 100%, even though that's not true, and in the same way we consider prefix utilization to be a very important measure in our network, aggregate utilization too is important, but currently unusable for us.

### Database changes

None.

### External dependencies

None.

**Comment by mobrowse** [comment]
Hello, we too are experiencing this same problem.
