### ISSUE TITLE
Add UI controls to provision available prefixes from a parent

### ISSUE THREAD

**Issue by jeremystretch** [netbox-community/netbox#11739]
### NetBox version

v3.4.4

### Feature type

New functionality

### Proposed functionality

Add a button/form in the UI to automatically provision some number of prefixes from a parent, similar to what the "available prefixes" REST API endpoint does. The user would need to specify 1) the number of prefixes desired and 2) the length of each prefix. If successful, the user should be redirected to the list of newly created prefixes.

### Use case

This is essentially replicating the REST API endpoint functionality in the UI. While not intended for programmatic consumption, it can reduce the time needed to provision multiple sibling prefixes.

**Comment by mlyko** [comment]
Is there any reason for not to implement the available prefixes feature for Aggregates?
