### ISSUE TITLE
Provide utilization on vlan groups

### ISSUE THREAD

**Issue by abhi1693** [netbox-community/netbox#11738]
### NetBox version

v3.4.4

### Feature type

New functionality

### Proposed functionality

Add `utlization` property which adds to the following views

- Object view
- Table column
- API

This similar to `prefixes` and `aggregates` functionality.

### Use case

As an engineer, I'd like to see at a glance how many VLANs are utilized in a group. Using this information via the API, I'd also like to perform certain maintenance tasks in my automation workflow.

**Comment by jeremystretch** [comment]
Seems like a good idea. Related to (but not necessarily blocked by) #9627.

**Comment by abhi1693** [comment]
If you want, I can provide a PR for this which in the current form should be good for develop branch
