### ISSUE TITLE
Aggregate utilization should consider a prefix of type "container"'s utilization in the calculation instead of assuming 100%

### ISSUE THREAD

**Issue by BrunoBlanes** [netbox-community/netbox#11734]
### NetBox version

v3.4.4

### Python version

3.8

### Steps to Reproduce

1. Create an aggregate of subnet mask /23 or higher
2. Create prefixes with subnet mask /24 and set them as containers

### Expected Behavior

Expected aggregate utilization to be based on prefixes created, except when using containers, in which case utilization should take into consideration the container's utiliation.

### Observed Behavior

Aggregate utilization goes to 100%.

**Comment by jeremystretch** [comment]
This is expected behavior. If you would like to propose a change, please submit a [feature request](https://github.com/netbox-community/netbox/issues/new?assignees=&labels=type%3A+feature&template=feature_request.yaml) citing your use case.
