### ISSUE TITLE
Multiple issues with the new ContactAssignmentListView added in #11595

### ISSUE THREAD

**Issue by kkthxbye-code** [netbox-community/netbox#11750]
### NetBox version

v3.5.0-dev

### Python version

3.10

### Steps to Reproduce

First issue:

1. Go to the contact assignment list view
2. Click the add button

Second issue:
1. Go to the contact assignment list view

Third issue:
1. Go to the contact assignment list view
2. Click the filter tab
3. Type something in the q filter

### Expected Behavior

First issue:
There should not be an Add button as adding a contact assignment is not supported without doing it from the target object

Second issue:
There should be a Bulk delete button

Third issue:
The table should filter by the search query

### Observed Behavior

First issue:
There's an Add button which throws an Exception if pressed because the edit form expects a reference to the target object passed.

Second issue:
The table has the pk select boxes but no bulk action buttons.

Third issue:
The ltable is not filtered.

**Comment by jeremystretch** [comment]
Thanks for tracking these down @kkthxbye-code!
