### ISSUE TITLE
Plugin menu label consisting of url unsafe characters breaks unfolding menu

### ISSUE THREAD

**Issue by samk-acw** [netbox-community/netbox#11758]
### NetBox version

v3.4.4

### Python version

3.10

### Steps to Reproduce

Create a plugin menu with any url unsafe character (eg. { } / \ # < > ~ | ^) in its label:
```
menu = PluginMenu(
    label='menu with /slash',
    groups=(
        ('menu item', [menu_item]),
    ),
    icon_class='mdi mdi-format-list-text'
)
```
After restarting NetBox, open the GUI at the main menu
Click on the plugin menu name

### Expected Behavior

The plugin menu opens, showing the menu items.

### Observed Behavior

The plugin menu is displayed in the side bar, but does not unfold when clicking on it.

This issue is the same as https://github.com/netbox-community/netbox/issues/10984, only with url unsafe characters instead of spaces, eg ` { } / \ # < > ~ | ^`

**Comment by jsenecal** [comment]
Please update the steps to reproduce as they are from the referenced issue. Unless you are implying that https://github.com/netbox-community/netbox/commit/150cb772fe519404857f48e894737f0570c4bc56 did not fix it.

Thanks,

**Comment by samk-acw** [comment]
sorry, copy paste fail. I've updated it now.

**Comment by jsenecal** [comment]
> sorry, copy paste fail. I've updated it now.

Thanks 😄

**Comment by rganascim** [comment]
I think we need to modify the PluginMenu class, in the return of the def name (netbox/extras/plugins/navigation.py). Now it only replaces the blank spaces, and if we change to rename all the special chars (prohibited in the html element names) things will work again.

If you want I can try to fix it.
