### ISSUE TITLE
Add additional Coaxial cable type to choices.py

### ISSUE THREAD

**Issue by davidabuckner** [netbox-community/netbox#11783]
### NetBox version

v3.4.4

### Feature type

Change to existing functionality

### Proposed functionality

Add the following section to choices.py

    # Coaxial
    TYPE_DOCSIS = 'docsis'
	TYPE_BNC = "bnc'
	
	
        (
            'Coaxial',
            (
                (TYPE_DOCSIS, 'DOCSIS'),
				(TYPE_BNC, 'BNC'),
            )
        ),

### Use case

This is to support devices such as a Grandmaster clock with GPS antennas

### Database changes

none

### External dependencies

None

**Comment by davidabuckner** [comment]
Not sure how it added the extra tab in
(TYPE_DOCSIS, 'DOCSIS'),
			(TYPE_BNC, 'BNC'),

Should read
(TYPE_DOCSIS, 'DOCSIS'),
(TYPE_BNC, 'BNC'),

**Comment by jeremystretch** [comment]
DOCSIS is a protocol, and BNC is a connector type. Neither of these would make sense to add as a cable type.

**Comment by davidabuckner** [comment]
Okay even weirder that it removed the tab in the comment.

**Comment by davidabuckner** [comment]
I thought that was odd, but the coaxial section under interfaces show the DOCIS type as an option.

**Comment by davidabuckner** [comment]
Maybe replace DOCIS with BNC?

**Comment by davidabuckner** [comment]
@jeremystretch Okay I see now where I was confused.  BNC is already listed under "front port" types.  I guess that makes sense since interface type isn't a "connector". Thanks for helping me through my senior moment.

**Comment by davidabuckner** [comment]
Only issue now is that I have to add a rear port when I'm creating a front port.  That doesn't make sense when I'm adding a port to a device to connect something external.

**Comment by jeremystretch** [comment]
You can add rear ports without associating a front port. The front/rear declaration is only for differentiating between mapped ports.

I'm going to close this out as the FR is untenable.
