### ISSUE TITLE
Add "Parent object" in search result

### ISSUE THREAD

**Issue by dboissat** [netbox-community/netbox#11782]
### NetBox version

v3.4.4

### Feature type

Change to existing functionality

### Proposed functionality

In the search result, add the parent object when is possible.

Example :
- For an interface, add the parent object device where the interface is present.
- For a front/rear port, add the parent object device.
- For a Circuit termination, add the parent object circuit. #11723
- For an IP address, add the parent prefix. #11685

If there is no parent object, the field is empty.

### Use case

The search functionality is powerful, but in some cases, we need to search again or navigate between some pages to go to the wanted information.

When I search a Circuit ID for a point-to-point circuit, I find 2 interfaces without any idea of the associated device. I need to open both links and navigate to the device.
Same thing with the front/rear port of the patch panel.

![image](https://user-images.githubusercontent.com/124785245/219720439-0d3bc29a-07fe-4ab2-817b-8b9f8eb3f1eb.png)

When I search for a cross-connect reference, I find the Termination, but the link is to the Site, not to the circuit. And it's complicated to find the concern Circuit. Issue #11723
![image](https://user-images.githubusercontent.com/124785245/219720404-1ee3f23a-8284-499d-8cea-0a9f9c89f8a7.png)

![image](https://user-images.githubusercontent.com/124785245/219720380-1fa8e550-ab90-4e93-8f76-b14e4b221985.png)

### Database changes

I do not think so

### External dependencies

I do not think so

**Comment by jsenecal** [comment]
All the referenced issues now have a fix in the latest NetBox release (v3.4.5). Is this issue still relevant? Your suggested feature would require a way to determine the "parent" object type and relationship for every model, which is not a small change and would incur a significant amount of supplementary database lookups, and thus affect performance of the global search when displaying its results.

**Comment by dboissat** [comment]
Hello, 

Indeed we installed and tested version v3.4.5.
Now, we find the prefixes when we search for an IP address. Perfect.
When we search for a cross-connect reference, the link goes to the circuit. Perfect too.

It missing to identify the device when we search for an interface description.
But I understood that it's not easy and will impact the performance. I will continue to click on each interface to check the device.
