### ISSUE TITLE
Don't persist page size preference across views

### ISSUE THREAD

**Issue by jeremystretch** [netbox-community/netbox#11807]
### NetBox version

v3.4.5

### Feature type

Change to existing functionality

### Proposed functionality

When viewing a list of objects in the NetBox UI, the user can select a page size to determine how many objects to render in one view. (Default options range between 25 and 1000 objects.) Once a page size has been selected, it will persist as the user navigates to other areas of the application. This FR proposes removing the persistence, so that navigating to a different object view returns the default page size.

### Use case

We've found that users will often increase the page size while viewing one type of object for a specific purpose, without realizing as they navigate elsewhere in NetBox that the page size has remained in effect. This can lead to frustration stemming from unnecessarily long load times as many more objects than required are being fetched.

**Comment by jsenecal** [comment]
Would persistence follow the page size preference of the individual user ?

**Comment by jeremystretch** [comment]
@jsenecal are you referring to the "page size" user preference?

![Screenshot 2023-02-23 at 16-13-36 User Preferences NetBox](https://user-images.githubusercontent.com/13487278/221031597-abeb4452-eb7f-4ae9-9afa-dd9a08fd8413.png)

I think we'd still allow a user to set their global preference this way; we just wouldn't update it automatically when specifying a page size under a specific table.

**Comment by jsenecal** [comment]
Yes, this is what I had in mind. The behavior you described works for me. I would change the description to `The default number of objects to display per page` however.
