### ISSUE TITLE
Go to Rack Button direct by Rack View

### ISSUE THREAD

**Issue by LHBL2003** [netbox-community/netbox#11802]
### NetBox version

v3.4.5

### Feature type

New functionality

### Proposed functionality

If a rack is directly assigned to a device, then the rack is directly visible.
Please add a button "Go to Rack" to the rack view within a device.

![image](https://user-images.githubusercontent.com/46369917/220657572-dd301eb8-93d0-4e50-9023-e7a937fb3467.png)

### Use case

Especially if you have to sort many devices into the rack, you always have to go back to the rack "...dcim/racks/x/".

For this purpose, I have already built in a user-defined button so that I can get there directly. But you always have to scroll way up.

Selecting the rack via the button on the left in the "Device" area is also not that effective. Here you also have to scroll up and search for the right line.

A button directly next to the rack would be more convenient.
It is also easier to see that you are in the device.

**Comment by jeremystretch** [comment]
There's already a link to the rack in the device panel at top left (not shown in your screenshot). It even includes a button to highlight the device in the rack.

**Comment by LHBL2003** [comment]
Yes, I know the link, but:
- You have to scroll up a whole screen.
- You have to optically focus this link between the links.

If you often have to go to the main track, this is not quite as effective.

It would also be enough to place the link directly underneath, as with Elevations.

![image](https://user-images.githubusercontent.com/46369917/220698831-1638a8dd-3868-4538-aa9c-199996183a72.png)

**Comment by jeremystretch** [comment]
I'm going to close this out as I don't see any justification for the redundant link, and it hasn't found any support in the community.
