### ISSUE TITLE
Move non-racked devices to a separate tab under the rack view

### ISSUE THREAD

**Issue by LHBL2003** [netbox-community/netbox#11803]
### NetBox version

v3.4.5

### Feature type

Change to existing functionality

### Proposed functionality

Set the list "Non-Racked Devices" via the rack or as a separate tab/register

![image](https://user-images.githubusercontent.com/46369917/221256776-a4529e4d-97b3-413b-86a9-79be97d26c1a.png)

Maybe even with a signal colour so that you can recognise more quickly that there is a special feature here, which is not the case with every rack.
![image](https://user-images.githubusercontent.com/46369917/221257534-4fdc34c3-accb-4891-9e7a-1dd1f7c94cb5.png)

THX to @abhi1693 for the basic image.

### Use case

I have been thinking about raising this point for months. But I realise again and again that it is important.

Racks with 42 units are so long that you can't see the "non-racked devices" area on a 24" monitor. That's why you don't pay attention to them. Either they are devices that are not sorted or devices that cannot be installed in a unit, e.g. socket outlets, small devices that are screwed to the rack, e.g. temperature monitors. 

Translated with www.DeepL.com/Translator (free version)

**Comment by abhi1693** [comment]
I think non racked devices should simply be moved to a view tab. That way if they exist you see them at the top of the page with a count.

**Comment by LHBL2003** [comment]
Do I understand that correctly, is that a counter-suggestion from you?  Or does this function exist?

**Comment by abhi1693** [comment]
It's a counter suggestion and something once accepted can be implemented natively. I already have a patch that does exactly this in our netbox

**Comment by jsenecal** [comment]
@abhi1693 do you have an issue # for that feature request ?

**Comment by abhi1693** [comment]
@jsenecal I'm sorry but I don't follow you.

**Comment by jsenecal** [comment]
> I already have a patch that does exactly this in our netbox. It basically moves the list at the bottom to a tab at the top with a count

**Comment by abhi1693** [comment]
Oh, I never opened an issue for this and directly applied the patch in my Netbox code. So, if the suggestion counter to adding the label is accepted, for this issue itself I'll raise the pr

**Comment by jsenecal** [comment]
@LHBL2003 If you are happy with what @abhi1693 suggested, please update your proposal to reflect this.

Thank you all,

**Comment by LHBL2003** [comment]
I think that's a great idea. Maybe you could make sure that the grey background is orange?
Then it would be more eye-catching that there is a special feature that is not present in every rack.

**Comment by abhi1693** [comment]
I don't think color would change as that's netbox internal AFAIK. Rest as shown in my screenshot is applicable.

**Comment by LHBL2003** [comment]
OK

**Comment by LHBL2003** [comment]
@jsenecal: Then I would say @abhi1693  suggestion should go into the release function or?

**Comment by jeremystretch** [comment]
Is there a real benefit of establishing a tabbed view for these devices as opposed to just linking to the filtered devices list?

**Comment by JoeIzzard** [comment]
I'd rather it be a tab than a link to the Device list so I can easily change back. If it's a link to the device list then I wouldn't have an easy way to tab back to the rack view which I may be switching between several times.

**Comment by jsenecal** [comment]
Based on https://github.com/netbox-community/netbox/issues/11803#issuecomment-1442403948, @abhi1693, I think you already had a fix implemented for this, is that right ?
