### ISSUE TITLE
Save button always visible in the edit window

### ISSUE THREAD

**Issue by LHBL2003** [netbox-community/netbox#11804]
### NetBox version

v3.4.5

### Feature type

Change to existing functionality

### Proposed functionality

Position the Save button so that it is always visible.

![image](https://user-images.githubusercontent.com/46369917/220664527-5cc71263-d9c2-4f29-9cec-5869eb00b25e.png)

### Use case

Often you only have to change one little thing. But you always have to scroll all the way down to save it.
Especially if you adjust something at the top and have to scroll all the way down, it's a long way.
It is good if the Save and Cancel buttons are always displayed.

**Comment by jeremystretch** [comment]
Thank you for submitting this issue, however it appears that this topic has already been raised. Please see issue #9386 for further discussion.
