### ISSUE TITLE
GraphQL timezone doesn't match REST API

### ISSUE THREAD

**Issue by tagur87** [netbox-community/netbox#11806]
Seems like this issue hasn't been resolved like was originally mentioned below. Could this be revisited now that graphene has been updated?

    I'm going to close this out both because no work has been done and because it will likely become moot per #9856.

_Originally posted by @jeremystretch in https://github.com/netbox-community/netbox/issues/7466#issuecomment-1197210723_

**Comment by jsenecal** [comment]
I am going to close this issue as it does not conform to the established templates when submitting feature requests or bugs. Feel free to reopen following our [contributing guidelines](https://github.com/netbox-community/netbox/blob/develop/CONTRIBUTING.md)
