### ISSUE TITLE
Termination Type is not parsed

### ISSUE THREAD

**Issue by miyuk** [netbox-community/netbox#11819]
### NetBox version

v3.4.5

### Python version

3.8

### Steps to Reproduce

1. create device interfaces and connect by cable interface (ex. https://demo.netbox.dev/api/dcim/cable-terminations/)
2. seach cable terminations of filterd by termination type `dcim.interface` (ex. https://demo.netbox.dev/api/dcim/cable-terminations/?termination_type=dcim.interface)

### Expected Behavior

return cable terminatin objects filterd by termination_type

### Observed Behavior

return error message with below

```json
{
    "termination_type": [
        "Select a valid choice. That choice is not one of the available choices."
    ]
}
```

**Comment by jeremystretch** [comment]
Thank you for opening a bug report. Unfortunately, the information you have provided is not sufficient for someone else to attempt to reproduce the reported behavior. Remember, each bug report must include detailed steps that someone else can follow on a clean, empty NetBox installation to reproduce the exact problem you're experiencing. These instructions should include the creation of any involved objects, any configuration changes, and complete accounting of the actions being taken. Also be sure that your report does not reference data on the public NetBox demo, as that is subject to change at any time by an outside party and cannot be relied upon for bug reports.

**Comment by miyuk** [comment]
sorry for the late reply.
I understood.

Our main problem to resolve is that find `cable` object by `cable-terminaion`.

specific Steps to Reproduce is below

## Steps to Reproduce

1. Create two devices and each interfaces with type `1000BASE-T` (`1000BSE-T` is type of `dcim.interface`).
2. Connect cables between device interfaces from interfaces list.
3. Find API cable termination object by `termination_type` and `termination_id`  such as below data
    `/api/dcim/cable-terminations/?termination_id=<interface id>&termination_type=dcim.interface`

**Comment by abhi1693** [comment]
I think adding `ContentTypeFilter` field on the filterset should resolve this issue. Can I take this is this is accepted?

**Comment by jeremystretch** [comment]
Thanks @abhi1693!
