### ISSUE TITLE
Add connected_enpoints property to graphql api

### ISSUE THREAD

**Issue by basti1508** [netbox-community/netbox#11817]
### NetBox version

v.3.4.5

### Feature type

Change to existing functionality

### Proposed functionality

The netbox graphql api should expose the same connected_endpoints property as the rest api.
This makes it easier to resolve complete paths via graphql.

A query would look like:

```{
  device(id:xx) {
    id
    name
    interfaces {
      name
      connected_endpoints {
        ... on InterfaceType {
          ip_addresses {
            address
          }
          device {
            name
            device_role {
              slug
            }
          }
        }
      }
    }
  }
}
```

### Use case

This function helps on making graphql information analog to rest-Api information.

**Comment by basti1508** [comment]
@maintainers: The pull request for this would be ready to be submitted, as soon as this issue is assigned to me.

**Comment by basti1508** [comment]
ah sorry. Draft PR is more the just a draft..
I'll create a new one then if assigned.

**Comment by ryanmerolle** [comment]
Relates to #7125
