### ISSUE TITLE
3.5 feature device role ui slug field broken

### ISSUE THREAD

**Issue by ryanmerolle** [netbox-community/netbox#11829]
### NetBox version

v3.5.0 / feature

### Python version

3.10

### Steps to Reproduce

1. Click Add Device Role
2. Add a name to the name field
3. Click the slug field "refresh icon"
4. Watch slugify not kick in

### Expected Behavior

slugify function should kick in

### Observed Behavior

slugify function does not kick in

**Comment by kkthxbye-code** [comment]
Duplicate of https://github.com/netbox-community/netbox/issues/11753
