### ISSUE TITLE
Bridge interface not appear in parent field on interface screen

### ISSUE THREAD

**Issue by mlimalotic** [netbox-community/netbox#11824]
### NetBox version

v3.4.5

### Python version

3.9

### Steps to Reproduce

Bridge interface not appear in parent field on interfaces screen
To see we need enter in bridge interface
![bridge-interface](https://user-images.githubusercontent.com/18513223/221279648-bacdf36b-352a-4ffe-b726-c0eae194d3e4.png)
![interface-screen](https://user-images.githubusercontent.com/18513223/221279657-001edeb9-b11e-419d-9694-ea3d4369ff37.png)

### Expected Behavior

Parent interface parent listed in main interfaces screen

### Observed Behavior

no error

**Comment by jeremystretch** [comment]
It's not clear from your description exactly what you're trying to achieve, but this does not appear to be a bug. (Parent and bridge interfaces are separate relations.) Please consider starting a [discussion](https://github.com/netbox-community/netbox/discussions/new/choose) for assistance.
