### ISSUE TITLE
Wrong icon for Cable status

### ISSUE THREAD

**Issue by B-z-F** [netbox-community/netbox#11830]
### NetBox version

v3.4.5

### Python version

3.10

### Steps to Reproduce

1. On Device; Interfaces select Connect cable -> Interface
2. select A Side interface and B Side interface (Cable Status: Connected)
3. Create

### Expected Behavior

Icon for connection status should be in aqua color with connected line.

### Observed Behavior

Icon for connection status is in yellow color with 'x' instead of line.

**Comment by jeremystretch** [comment]
The button indicates the action that will be taken if pressed. A connected cable shows a button that will mark it as "planned."
