### ISSUE TITLE
FILE_UPLOAD_MAX_MEMORY_SIZE configuration parameter is missing

### ISSUE THREAD

**Issue by Ren60FHk** [netbox-community/netbox#11839]
### NetBox version

3.4.5

### Python version

3.8

### Steps to Reproduce

1. Upgrade to version 3.4.5.

### Expected Behavior

Presence of the `FILE_UPLOAD_MAX_MEMORY_SIZE` configuration parameter in the **configuration_example.py**.

### Observed Behavior

Absence of the `FILE_UPLOAD_MAX_MEMORY_SIZE` configuration parameter in the **configuration_example.py**.

P.S. I'm sure this is not a bug, actually, but I didn't find the appropriate place to inform about it.

**Comment by jeremystretch** [comment]
Not every potential configuration parameter is listed in the example configuration. Please consult [the documentation](https://docs.netbox.dev/en/stable/configuration/) for a complete listing.
