### ISSUE TITLE
Add field grouping function to scripts function

### ISSUE THREAD

**Issue by ryanmerolle** [netbox-community/netbox#11833]
### NetBox version

v3.4.5

### Feature type

New functionality

### Proposed functionality

Similar to fieldsets in forms or group_names in  custom_fields, it would be useful to allow scripts to have some sort of grouping of fields.

### Use case

Scripts with a number of input fields could really stand to leverage some grouping.

### Database changes

None

### External dependencies

None

**Comment by sleepinggenius2** [comment]
To add to this, it would be nice to move the scheduling fields to their own fieldset too, as the layout is a little confusing at the moment.
