### ISSUE TITLE
Enable support to HTTP/2 by default

### ISSUE THREAD

**Issue by MuriloChianfa** [netbox-community/netbox#11848]
### NetBox version

v3.4.5

### Feature type

New functionality

### Proposed functionality

Nowsaday we have new HTTP procotol versions, one of this is HTTP2, and my feature request is to enable the support for it.

### Use case

This functionality improve the load speed of severs requests, one of your most important improviment is the multiplexing feature, speeuping the requests.

### External dependencies

Guide to implement HTTP/2 support:
https://httpd.apache.org/docs/2.4/howto/http2.html

**Comment by jeremystretch** [comment]
> and my feature request is to enable the support for it.

By making what changes, specifically?

**Comment by MuriloChianfa** [comment]
maybe adding a new apache2 config file at /etc/apache2/conf-available/http2.conf
```bash
<IfModule http2_module>
    Protocols h2 h2c http/1.1
    H2Direct on
</IfModule>
```
enabling http2 apache module
```bash
sudo a2enconf http2
```
and restarting the server
```bash
sudo service apache2 restart
```

the instructions of load module can be added in documentation at installation topic
https://docs.netbox.dev/en/stable/installation/5-http-server/

but it is only for apache2, for nginx i dont know how to do it >.<

**Comment by jeremystretch** [comment]
There are myriad additional configurations that could be made to the HTTP daemon to support different features; these are out of scope for the NetBox documentation. The reference configuration is a minimal example to get users up and running. Are you aware of any changes that would need to be made to the code itself?
