### ISSUE TITLE
Being able to assign ASN to Aggregates.

### ISSUE THREAD

**Issue by joaolucasmacedo** [netbox-community/netbox#11844]
### NetBox version

v3.4.4

### Feature type

Change to existing functionality

### Proposed functionality

It would be nice to be able to assign ASN objects to aggregates, since aggregates may represent address blocks delegated by a RIR to a specific ASN.

### Use case

Being able to assign ASN to Aggregates, so a ASN will be shown on Aggregates table and a list of aggregates will be shown at the ASN view.

It is useful, for instance, if you need to pull a list of prefixes that belong to a ASN to use on routing policies and firewall rules.

**Comment by ryanmerolle** [comment]
I get the thought.  I am not sure it will get accepted, but you should be able to achieve this same sort of functionality with custom fields using object types.  Then you can select the ASN object type.

**Comment by joaolucasmacedo** [comment]
> I get the thought. I am not sure it will get accepted, but you should be able to achieve this same sort of functionality with custom fields using object types. Then you can select the ASN object type.

I'm sure I can do it with custom fields, and I already do. But I'm rising this because I thing it is a intrinsic relationship.

**Comment by jeremystretch** [comment]
Let's fold this into #8782 as it seems like an extension of that discussion.
