### ISSUE TITLE
Feature Request: Have Virtual Chassis own control plane resources

### ISSUE THREAD

**Issue by marcartz** [netbox-community/netbox#11840]
### NetBox version

v3.4.5

### Feature type

Data model extension

### Proposed functionality

The virtual chassis model is ideal to represent stacks of networks switches (e.g. VSS, StackWise, etc.)
Give virtual chassis the possibility to directly own control plane resources: SVIs, Management IPs and Router-Ids/Loopback-Interfaces.
Also add meta-information: site, location, vendor, type
Current options, like assigning those resources to a random stack member does badly represent the actual function of a stack: The control plane is assigned to an elected master, which could potentially be any of the available stack members (the ID of a potential master is non-deterministic).
Currently I use a fake stack member with the same name as the VC, which owns the control plane resources, while the actual stack members have only a serial number assigned.

### Use case

Real-Life representation of stacks of network switches in Netbox.

### Database changes

# Virtual Chassis
- Interfaces
- IP addresses
- Site
- Location
- Vendor
- Type

**Comment by jeremystretch** [comment]
> Current options, like assigning those resources to a random stack member does badly represent the actual function of a stack

The current implementation most closely mirrors the way a stack actually functions: The master device is responsible for operation of the control plane. I'm sorry if the was this is implemented in NetBox does not meet your needs, but we will not be changing it.
