### ISSUE TITLE
Add miniSAS interface type

### ISSUE THREAD

**Issue by PieterL75** [netbox-community/netbox#11855]
### NetBox version

v3.4.5

### Feature type

Data model extension

### Proposed functionality

Add the 'miniSAS' connector to the interfaces model.
https://en.wikipedia.org/wiki/Serial_Attached_SCSI
external Mini-SAS HD 
![image](https://user-images.githubusercontent.com/74899468/221920245-5c6cfc33-fca7-4808-8b82-13cd7f6bd16e.png)

### Use case

Document the connection of external netapp diskshelfs to the controller

**Comment by jeremystretch** [comment]
Looks like this would be covered by #11474.

**Comment by PieterL75** [comment]
Missed that one.. sry for the duplicate
