### ISSUE TITLE
Circuit Termination: BiDi Circuit and Interface Support

### ISSUE THREAD

**Issue by InsaneSplash** [netbox-community/netbox#11865]
### NetBox version

v3.4.5

### Feature type

New functionality

### Proposed functionality

Provide the ability to split 1 physical circuit into 2 individual circuits. In other words, allow 1 circuit to be attached to 2 physical interfaces by using 1 strand. When making use of BiDi optics, only 1 strand of the fibre pair is required, however, the circuit provided is normally ordered as a single link. (pair).

When a circuit is provided for example by a data centre, it would be a Single-Mode Fibre pair but can use split using BiDi optics in to 2 circuits.

### Use case

Bi-Directional (BiDi) Transceiver is a compact optical transceiver module that uses WDM (wavelength division multiplexing) technology and is compliant with the SFP multi-source agreement (MSA). Bi-Directional technology means a communication mode that processes data in both directions (send and receive) over optical fibre, which allows transceiver modules to transmit and receive data to/from the interconnected network devices (like network switches or routers) via a single optical fibre.

**How Does BiDi Module Work?**
BiDi modules are equipped with WDM couplers/diplexers to combine or separate data transmitted over a single fibre using different wavelengths of light. Like traditional transceivers, BiDi transceivers should be deployed in pairs. However, for BiDis, we should use two modules: one for the upstream ("U") direction and another for the downstream ("D")—each part transmits at an opposite wavelength. For example, from point A we have installed a transceiver that transmits TX on 1310nm towards point B on a single fibre. In point B there is a transceiver that receives RX on 1310 nm and transmits back to point A on 1490nm on the same fibre. In point A the RX frequency is listening on 1490nm.

[BiDi Transeiver Working Principle
](https://media.fs.com/images/community/upload/kindEditor/202106/01/bidi-transeiver-working-principle-1622516147-5CFncvxO1a.jpg)

![image](https://user-images.githubusercontent.com/16985649/222130421-ec648f6a-e375-42bf-83f1-212300f9878a.png)

**How Many BiDi Module Types?**
The common types of BiDi transceivers used in today's networks are 1G/10G BiDi SFPs. The most common optical wavelengths for this transceiver are 1310/1490 nm, 1490/1550 nm, and 1310/1550 nm. They are designed for 1/10 GB deployment and can reach up to 80km distance. BiDi variants are also available for the form factor XFP X2 for 10G, GBIC for 1G.

The 25G SFP28 BiDi transceiver supports connections up to 10km over single-mode fibre and uses LC connectors. The wavelengths are 1330TX/1270RX and 1270TX/1330RX.

The 100G QSFP28 BiDi CWDM4 transceiver supports connections up to 2km over single-mode fibre and uses LC connectors. The wavelengths are 1271 nm, 1291 nm, 1311 nm, and 1331 nm.

The 40GBase QSFP+ BiDi has two 20G channels that support connections up to 100 meters on OM3 MMF and up to 150 meters on OM4 MMF. It uses an LC Duplex connector and the wavelength is 850nm. QSFP+ BiDi is a cost-effective solution for a 10G to 40G upgrade.

**Why BiDi Module?**
This single-fibre BiDi transmission gradually becomes a popular and cost-effective solution for today's data centre and IT infrastructure because of its unbeatable advantages:

Double Your Network Capacity – One benefit of BiDi is that it allows you to make full use of all your fibre strands and can therefore double your network capacity. This is because one strand is used to carry information in both directions, for example, if you have a six-strand cable you would be able to utilize all six stands rather than three for one direction and three for the other.

Reliability – Another benefit is increased reliability, single strand solutions are less prone to connection errors due to fewer connections and endpoints.

Cost – With the reduction of fibre strands by half, the number of patch cords and patch panel ports can be reduced accordingly, as well as reducing the amount of tray space dedicated to fibre management.

**Where BiDi Modules Are Used?**
BiDi modules are usually deployed in applications like access PON networks deployment P2P (point-to-point) connection, Digital Video, and Closed Circuit Television (CCTV) applications. They can be installed on servers, switches, routers, OADM to provide high-speed and stable optical transmission systems, and Metropolitan Area Networks (MAN). In addition, 25/50G BiDi transceivers are welcomed by 5G networks since they can save fibre resources and support high bandwidth, ultra-low latency, and high reliability for data transmissions.

[https://community.fs.com/blog/a-brief-introduction-of-bidi-sfp-transceiver.html](https://community.fs.com/blog/a-brief-introduction-of-bidi-sfp-transceiver.html)

### Database changes

I would suspect a new interface would be required and an additional way to split/link a single circuit to 2 interfaces.

**Comment by tbaczynski** [comment]
I think it's related to #6824

**Comment by CADbloke** [comment]
Related discussion: https://github.com/netbox-community/netbox/discussions/11909
