### ISSUE TITLE
Change status of site-related object when site is retired

### ISSUE THREAD

**Issue by mplanicka** [netbox-community/netbox#11868]
### NetBox version

v3.4.4

### Feature type

New functionality

### Proposed functionality

It would be great when site is retired, to change status of all site related objects eg. prefixes, vlans, devices etc. to deprecated (IPAM) and decommissioning/inventory (DCIM).

### Use case

No need to manually change status of all site related objects after site is retired.

### Database changes

none

### External dependencies

none

**Comment by jeremystretch** [comment]
I'm afraid this isn't something we can build into NetBox as it makes assumptions about the intended states of various objects which may or may not be applicable for a given organization or user. Instead, what you can do is write a [custom script](https://docs.netbox.dev/en/stable/customization/custom-scripts/) that can be used to retire a site and update its related objects according to your specific needs.
