### ISSUE TITLE
Weight Unit Preference

### ISSUE THREAD

**Issue by danner26** [netbox-community/netbox#11873]
### NetBox version

v3.4.5

### Feature type

Data model extension

### Proposed functionality

When importing a device type with a weight of KG it would be nice to see values displayed in the frontend in LBs rather than KGs. My suggestion is to add a pre-user preference which will let you specify whether you prefer metric or imperial measurements. Once the preferred unit of measurement is selected by a user, it should be translated within the user interface as applicable. 

By default I suggest that it displays the data as-is in the database. 

### Use case

Some vendors list items in LBs, others in KGs as well as others in both. The devicetype-library is a mix of KG and LB depending on who creates the files. Being in America myself, we prefer pounds whereas someone in Germany might prefer kilograms. It would be helpful to have these automatically translated in the UI as a UX improvement

**Comment by jeremystretch** [comment]
This might actually tie into our higher-level efforts to support localization, if it can be inferred from the user's locale. However there may also be a benefit to providing a discrete control for it.

**Comment by danner26** [comment]
Hey Jeremy, just circuling back around on this. Is this something we want to tie into the localization effort?

**Comment by danner26** [comment]
I agree once localization support is implemented this will fall in line with that effort

**Comment by jeremystretch** [comment]
Let's wrap this into #13915, which proposes the ability to set user-preferred units for both length and weight measurements.
