### ISSUE TITLE
Document uplaod other than only pictures

### ISSUE THREAD

**Issue by hdse** [netbox-community/netbox#11882]
### NetBox version

V3.4.5

### Feature type

New functionality

### Proposed functionality

It would be very nice if we could also upload other documents to devices.

### Use case

It would be very nice if we could also upload other documents to devices.
No matter which device we define, it should be possible to attach documents.

**Example:**

- Contracts
- Measurement protocols of cables
- Invoices
- etc

At the moment this is not possible and you need a second system for that.

**Comment by jeremystretch** [comment]
This has been proposed in past feature requests and rejected as a core feature, however you might consider the [netbox-attachments plugin](https://github.com/Kani999/netbox-attachments).
