### ISSUE TITLE
Add possiblity for multiple Napalm device credentials to be added 

### ISSUE THREAD

**Issue by tobicodesstuff** [netbox-community/netbox#11881]
### NetBox version

v3.4.5

### Feature type

Change to existing functionality

### Proposed functionality

- Make it possible to add NAPALM_USERNAME and NAPALM_PASSWORD per device. 
- Relevant code is at /netbox/dcim/api/views.py (lines 488-491) and /netbox/netbox/config/parameters.py (lines 153-183)
- The device in question is available within /netbox/dcim/api.views.py at line 438, my idea was to possibly add a custom field following a certain pattern probably (NAPALM_DEVICE_{PK}_USERNAME?) and to check if such a field is present. If yes, override the credentials present, if not proceed as usual.

Nice to have:
- A further implementation could be to have a device tab to edit such variables
- A table somewhere containing the login credentials for all devices in a central place

### Use case

- Would like to use Napalm to inspect multiple devices, but having a single credential set for possibly tens of devices seems like a security risk

### Database changes

None (custom field solution) or new configuration table (further more central implementation)

### External dependencies

None

**Comment by candlerb** [comment]
Another option would be to defined name sets of credentials, which could just be arguments to the napalm driver:

```
NAPALM_CREDENTIALS = {
    "default": {
        "username": "foo",
        "password": "bar",
    },
    "firewall": {
        "username": "baz",
        "password": "qux",
        "optional_args": {"port": 12443},
    },
}
```

Then the per-device setting would just be the credential type (e.g. "default" or "firewall") and the actual values are not exposed to the UI or the database at all.

Another option would be to get the settings through the config contexts mechanism.

**Comment by jeremystretch** [comment]
We're not accepting new feature requests for the NAPALM integration as it's being removed in NetBox v3.5 (see #10520). However, you're welcome to submit feature requests against the new [`netbox-napalm`](https://github.com/netbox-community/netbox-napalm) plugin once it's released.

**Comment by tobicodesstuff** [comment]
Thank you for the reply, I have seen the plugin and have played around with it, but didn't see #10520.

**Comment by tobicodesstuff** [comment]
> Another option would be to defined name sets of credentials, which could just be arguments to the napalm driver:
> 
> ```
> NAPALM_ARGUMENTS = {
>     "default": {
>         "username": "foo",
>         "password": "bar",
>     },
>     "firewall": {
>         "username": "baz",
>         "password": "qux",
>         "optional_args": {"port": 12443},
>     },
> }
> ```
> 
> Then the per-device setting would just be the credential type (e.g. "default" or "firewall") and the actual values are not exposed to the UI or the database at all.
> 
> Another option would be to get the settings through the config contexts mechanism.

@candlerb I've mentioned your suggestion in the new issue as it seemed helpful.
