### ISSUE TITLE
Update the `tx_power` field to be a double instead of an integer

### ISSUE THREAD

**Issue by BrunoBlanes** [netbox-community/netbox#11897]
### NetBox version

v3.4.5

### Feature type

Change to existing functionality

### Proposed functionality

I propose to update the afore mentioned field to a double in order to be more precise as to the power set and observed.

### Use case

Although initially proposed on #7606 as a means to indicate configured transmit power, it became one too effective way of documenting the default transmit power of optical SFP modules in order to diagnose potencial degradation of performance over time.

Changing it to a double would improve this behavior by more accurately representing powers as given by most equipment:
![image](https://user-images.githubusercontent.com/28227097/222719468-faf1a5ca-ed09-4cd2-bbab-11ab27628d27.png)

### Database changes

Probably a minor no breakable change.

### External dependencies

None that I am aware of.

**Comment by jeremystretch** [comment]
> I propose to update the afore mentioned field to a double in order to be more precise as to the power set and observed.

I assume you mean a decimal (float)?

> Although initially proposed on https://github.com/netbox-community/netbox/issues/7606 as a means to indicate configured transmit power, it became one too effective way of documenting the default transmit power of optical SFP modules in order to diagnose potencial degradation of performance over time.

The purpose of the field is to track the _configured_ value, so any change would require a use case relevant to this purpose. Can you provide one?

> Probably a minor no breakable change.

This would be a breaking API change because the type of the field will change.

**Comment by BrunoBlanes** [comment]
> I assume you mean a decimal (float)?

Yes.

> The purpose of the field is to track the configured value, so any change would require a use case relevant to this purpose. Can you provide one?

The idea is to use this field when installing a new optical transceiver and document its initial power output so that we would be able to compare it later and see how it has degraded.

Usually they have an operational range (see [this datasheet](http://cn.opwaytech.com/szsgwg202103054174/uploads/allimg/210726/3-210H6163035493.pdf)) which means that its power output could vary a lot from one to another, in the case of this model it could vary up to *5dB*, and so being able to refer to its actual initial power output (with multiple decimal place precision) means I'd be able to approximate a date in the future when it would be out of range and in need of replacement.
