### ISSUE TITLE
CSV export should match CSV import

### ISSUE THREAD

**Issue by Ximalas** [netbox-community/netbox#11895]
### NetBox version

v3.4.5

### Python version

3.9

### Steps to Reproduce

1. Export IP addresses by selecting Export and Current view. Save the .csv file. Open the .csv file in an editor.
2. Observe the fields are named: IP Address,VRF,Status,Role,Tenant,Assigned,DNS Name,Description
3. When importing:
3a. The above fields must be named: address,vrf,status,role,tenant,interface,dns_name,description
3b. The value “Active” isn't accepted for the field status, but the value “active” (lowercase a) is.

### Expected Behavior

I expected an import to accept NetBox' own export format without a hitch. It certainly makes for a better user experience for a newcomer.

### Observed Behavior

Complaints about unknown fields, etc.

**Comment by jeremystretch** [comment]
This has already been discussed and rejected numerous times. Please use the search function before opening new issues.
