### ISSUE TITLE
Leverage HTMX to simplify rendering of complex form fields

### ISSUE THREAD

**Issue by jeremystretch** [netbox-community/netbox#11891]
### NetBox version

v3.4.5

### Feature type

Change to existing functionality

### Proposed functionality

#11625 introduced the ability to dynamically render object edit forms in response to changing field selections. We can leverage this new ability to simplify forms which have fields that can reference different types of related objects.

For example, the circuit termination edit form allows the user to select either a site or a provider network as the "attached" object:

![Screenshot 2023-03-02 at 13-34-09 Editing circuit termination 1002840283 Termination Z NetBox](https://user-images.githubusercontent.com/13487278/222520428-6d0f8a98-f6da-4b7e-abd6-de4bf1635c03.png)

When the "site" tab is selected, the three relevant fields (region, group, and site) are displayed. When the "provider network" tab is selected, these are replaced with two different fields (provider and provider network). All five of these fields are declared on the form, and the values of all five are sent when the form is submitted. This can be confusing to the user, especially when field validation error messages end up on a hidden tab (as in #11816, for instance).

We can change the tabs to a dropdown selection field that triggers the form to re-render automatically in response to the related object type changing, and return only the relevant fields.

### Use case

This change will simplify the appearance of forms within the UI, obviating the need to hide some fields behind tabs. It will also eliminate the need for many of our custom form templates.

**Comment by dhenschen** [comment]
I would like to take ownership of this issue please.

**Comment by arthanson** [comment]
@dhenschen I'm working on something related to this for cabling, so let me know any progress you get on this and I will let you know what I come up with.

**Comment by dhenschen** [comment]
@arthanson, Are these the HTMX changes you were referencing: https://github.com/netbox-community/netbox/pull/12491

**Comment by dhenschen** [comment]
@jeremystretch, I've identified the following templates that follow the same pattern as circuit termination and could potentially benefit from HTMX improvements:

- [ ] circuittermination_edit.html
- [ ] inventoryitem_edit.html
- [ ] l2vpntermination_edit.html
- [ ] service_edit.html
- [ ] vlan_edit.html
- [ ] ipaddress_edit.html

To clarify the scope of this issue, would you like all forms that follow the same model as circuit termination to be updated as part of this issue? If so, would you prefer separate pull requests for each form to facilitate the review process?

**Comment by dhenschen** [comment]
@arthanson, https://github.com/netbox-community/netbox/pull/12675 contains my progress on this issue so far.

**Comment by DanSheps** [comment]
Re-opening this as I believe it was closed in error.  @jeremystretch do we still want to move forward with this?

**Comment by jeremystretch** [comment]
No; it's too broad. We'll need to open more detailed FRs scoping specific work to move this initiative forward.
