### ISSUE TITLE
Primary IP on Virtual Machine not sync with IPAM

### ISSUE THREAD

**Issue by dwi2214** [netbox-community/netbox#11905]
### NetBox version

v3.4.5

### Python version

3.9

### Steps to Reproduce

1. Update primary ip4 on VM using api (via ipam.ip_addresses) --> Update successful
2. Remove IP from IPAM via GUI to not assigned any VM --> Update successfull
3. Check on VM, primary ip still exist using that IP

![image](https://user-images.githubusercontent.com/116805958/222878538-12a68d48-3dff-4b66-bfb1-f5a7a03e6bad.png)

### Expected Behavior

- Sync between IPAM IPaddresses and Virtual Machine Primary IP

### Observed Behavior

IP Address updated to not assigned to any VM, but VM still has assigned to that IP

**Comment by jeremystretch** [comment]
Thank you for opening a bug report. Unfortunately, the information you have provided is not sufficient for someone else to attempt to reproduce the reported behavior. Remember, each bug report must include detailed steps that someone else can follow on a clean, empty NetBox installation to reproduce the exact problem you're experiencing. These instructions should include the creation of any involved objects, any configuration changes, and complete accounting of the actions being taken. Also be sure that your report does not reference data on the public NetBox demo, as that is subject to change at any time by an outside party and cannot be relied upon for bug reports.

**Comment by drossy** [comment]
I've just realised this looks similar to #11934 which I submitted a couple of days ago

**Comment by jeremystretch** [comment]
Okay. Would you like to close this issue, or extend the description above so that it can be treated as its own separate issue?
