### ISSUE TITLE
Add Coaxial Connectors BNC and SMA to Device Interface

### ISSUE THREAD

**Issue by brainsfull** [netbox-community/netbox#11915]
### NetBox version

v3.4.5

### Feature type

Change to existing functionality

### Proposed functionality

Add the following types of connectors to the available Interfaces for Devices and Modules.

- BNC
- SMA
- F-type

### Use case

Connection to timing and synchronization equipment from vendors such as Microchip S650. Example below:
![image](https://user-images.githubusercontent.com/7419642/223213767-bcbc53e9-a7a7-4796-9de3-7de2d4dbd0b1.png)

### Database changes

Addition of port types BNC, SMA, and F-type to Interfaces Component. 

### External dependencies

None.

**Comment by brainsfull** [comment]
> I would also suggest throwing in "F Type" to the list.

I have added to the request.

**Comment by jeremystretch** [comment]
These do not appear to be network interfaces. A network interface is something that sends and receives packetized data, and typically has resources such as VLANs and/or IP addresses associated with it.

Instead, you should model these as front/rear ports (which already list the request types as available options).

**Comment by cyberndj** [comment]
Howdy,

There are many pieces of equipment that have these types of ports on them.
- For F type connectors, look at the common broadband cable providers, they use modems typically with a F Type coax to connect back to the providers equipment. They will have a MAC that gets an assigned public IP so it can connect up to the Interwebs
- BNC Connectors have been used in the past for ATM/T3/E3 transmissions. (RIP ATM....) Modern uses of BNC include AV/Radio/TV transmissions. Other uses of BNC include Time Clock/Code, and GPS receivers for NTP/PTP. Ex. the picture in the OP. ( My company has 15 different locations with cable co. modems for internet access). Ex. the picture in the OP.
- SMA Connectors are often used with Access Points and external antennas. These external antennas can have 10's to 100's of feet of cable that extends to different locations.
- N connections (although they aren't listed), I believe are more used in radio communications and higher power broadband service. We have 2 connections in hour HQ building that come in on a N type and goes into a 24 port F type splitter that then goes into a a few cable modems and tv receivers.

Try to take it from a perspective of a 2-5 person team. If they have one location with a bunch of cables that run in and out of the location, along with a bunch of connections in the room, wouldn't it be nice to document all (or as much as possible) of the equipment that is in the room and their connections? For every example above, the equipment can be rack mounted, on a shelf,  mounted to a wall; but all have various types/numbers of interfaces on the device including F, SMA, BNC and N. 
Patch panels (aka Front/Rear) ports are awesome and they can represent one aspect of how a location is set up. I believe that NetBox is robust and developed enough to start integrating the less common interface types.

I believe that having these connectors added will benefit everyone from the large datacenters to the small 1 person IT support tech in documenting their networks. I kindly ask that this FR be reopened and be allowed to move forward.

/r
Jake
