### ISSUE TITLE
Pre-patched cable without termination for future use

### ISSUE THREAD

**Issue by mchlrv** [netbox-community/netbox#11913]
### NetBox version

v3.4.5

### Feature type

New functionality

### Proposed functionality

This is basically the reopening of issue #9300 which has been closed due to overhaul of the entire cabling model at that time. Looking at the new model it still doesn't seem possible to define pre-patched cables without a termination point.

We pre-patch all our switches in the datacenter with fibers, but they are not terminated anywhere yet as cross connects will be installed on a request basis. After a new cross connect is requested and terminated at a patch panel, we raise a smart hands and ask the field engineer of the datacenter to patch the new cross connect using our pre-patched and labeled fiber after which the cable is connected.

So it would be helpful to have a functionality to have a cable connected to an interface on a device (switch) but not have it terminated on the B-side yet as this is cable is reserved / planned for future use.

### Use case

By allowing this we can already note the cable specifications (type, label, color, length) in Netbox and only have to select a B side once it is being used.

### Database changes

- Add cable status: reserved (future use)
- Don't make B side mandatory

**Comment by xkilian** [comment]
I would suggest a slider to manually choose to remove de B side connection obligation.
This way, the current default remains and is desirable IMO.
