### ISSUE TITLE
Change from name of custom fields to label in the search page

### ISSUE THREAD

**Issue by haki99** [netbox-community/netbox#11910]
### NetBox version

v3.4.5

### Feature type

Change to existing functionality

### Proposed functionality

When I search for any data which are existing in a custom field, the opened search page shows the name of the custom field, not the label.

For example in my case: 

- "cf_contact_person", not "Contact Person"
- "cf_it_responsible", not "IT Responsible"

![image](https://user-images.githubusercontent.com/51157531/223077286-08e94ca3-1be8-44b9-9cad-b2a23a2ad296.png)

It would be better if it shows the label of the custom field, because it will increase the readability of the search results for all the users, especially for the non-admin users.

### Use case

 It will increase the readability of the search results for all the users, especially for the non-admin users.

### Database changes

Change in the search query is necessary for this feature change.

### External dependencies

No need to add or modify external dependecies.

**Comment by kkthxbye-code** [comment]
I think this makes sense, open for anyone who wants to give it a shot. Beware that it might require a reindex.

**Comment by jeremystretch** [comment]
I see two issues with this:

1. The custom fields would need to be retrieved separately and their labels applied to the search results, imposing additional overhead.
2. Custom field labels are not required to be unique (whereas names are). This can lead to confusion when a user interprets two discrete fields as one.
