### ISSUE TITLE
"Add child interface" button should inherit VDC from parent

### ISSUE THREAD

**Issue by mgoetze5** [netbox-community/netbox#11922]
### NetBox version

v3.4.5

### Feature type

Change to existing functionality

### Proposed functionality

When using the "add child interface" button, either from an interface or a table of interfaces from a device or VDC, the form should be prefilled with the VDC(s) of the parent interface, if any.

### Use case

It seems rather unlikely that if a parent interface is already in a VDC the child interface would not also be in the same VDC, so this should save clicks in the vast majority of cases.

### Database changes

None

**Comment by kkthxbye-code** [comment]
@jeremystretch - What's the best way to do this? Are we doing it anywhere else for other many to many fields? If we want to built it into the template, we need to generate the following in the url:

`vdcs=1&vdcs=2&vcds=3` from the many to many field. 

I guess we could do a loop in the template to built it or a templatetag.

**Comment by jeremystretch** [comment]
I don't have a great answer for the "how." Seems like it would be messy to implement in the template alone.
