### ISSUE TITLE
Typo in PluginConfig _load_resource method

### ISSUE THREAD

**Issue by JulianJacobi** [netbox-community/netbox#11927]
### NetBox version

v3.4.5

### Python version

3.11

### Steps to Reproduce

1. Create a plugin, that uses some resource loading (i.e. `template_extensions`) and explicitly define this resource path in `PluginConfig` class with `template_extensions = 'template_extensions'`
2. Install Plugin
3. Start Netbox

### Expected Behavior

Netbox should start normally, with plugin loaded.

### Observed Behavior

An ImportError exception is raised saying that the plugin has not defined an attribute/class called exactly like the name of the plugin.

**Comment by JulianJacobi** [comment]
It seems that the problem is related to fbc9fea0. 

IMHO [this line](https://github.com/netbox-community/netbox/blob/33286aad391de51a460189649c5187ddbd8ed4ce/netbox/extras/plugins/__init__.py#L82) 

`return import_string(f"{self.__module__}.{self.name}")` should be `return import_string(f"{self.__module__}.{getattr(self, name)}")`

**Comment by abhi1693** [comment]
That's a really good find. I too see this exact issue and your fix does seem to be loading it correctly.
