### ISSUE TITLE
Make VDC Interface tables configurable

### ISSUE THREAD

**Issue by mgoetze5** [netbox-community/netbox#11920]
### NetBox version

v3.4.5

### Feature type

New functionality

### Proposed functionality

When viewing a VDC in the web interface e.g. https://demo.netbox.dev/dcim/virtual-device-contexts/1/ it should be possible to configure which columns to display in the table of interfaces with a "Configure Table" button like the one present when viewing the interfaces of a device.

(Alternatively, the same configuration could be applied in both cases, though I personally believe it would be better to be able to configure this seperately.)

### Use case

Allows users to be able to see desired information more quickly without having to check each interface individually.

### Database changes

Presumably requires a new field in the user preferences.

**Comment by jeremystretch** [comment]
The interfaces table displayed under the VDC view employs the same configuration as the global interfaces table (DCIM > interfaces). Changes made to the table there will be replicated to the VDC view.
