### ISSUE TITLE
Sort images by date

### ISSUE THREAD

**Issue by kmorin18** [netbox-community/netbox#11932]
### NetBox version

v3.4.1

### Feature type

New functionality

### Proposed functionality

It would be great to be able to sort the "images" table based on the "created" date

[Image](https://imgur.com/a/rsu0Nil)

### Use case

Easily find the latest pictures

**Comment by jeremystretch** [comment]
There's a design pattern for this in the upcoming v3.5 release, under #8184. However it will necessitate the introduction of a UI list view for all image attachments.
