### ISSUE TITLE
Allow custom fields on webhooks

### ISSUE THREAD

**Issue by abhi1693** [netbox-community/netbox#11936]
### NetBox version

v3.4.5

### Feature type

Data model extension

### Proposed functionality

Add `CustomFieldsMixin` on the `Webhook` model

### Use case

I'd like to implement some extra fields on my webhook which are not a part of standard installation or shoould not be added to the core NetBox code. Like knowing how many instances of webhook receiver are registered on it. Such functionality will allow me to create clustered receivers and I will be able to scale them up/down depending on the load on NetBox.

Since this is my custom requirement, it makes sense for to be able to utilise custom fields as per my requirements.

### Database changes

Adds a new field automatically to the Webhook model via the mixin as described above.

**Comment by jeremystretch** [comment]
I'm afraid I don't understand your use case. Could you provide an example of what you're trying to implement?

**Comment by abhi1693** [comment]
So, I have a webhook receivers that when online, auto-registers themselves with NetBox by creating relevant webhook object. Now, I'd like to scale such receivers in count befind the same recever ingress. The problem is that I want to maintain a count of how many receivers are listening on the webhook object (can be done using custom field). The count will help me to either scale up or down when needed depending on pending tasks in the queues. I have noticed that when my webhook listeners are processing slowly due to whatever reason, the other tasks on netbox keeps getting piled up and that delays execution by alot. Scaling the rq workers can be a fix but that's temporary and sometimes our en can have 300+ changes on the webhook at once and having that many rq workers can be quite expensive for us to scale to.

This is one such use case for myself wherein a custom field will help me keep metadata for the webhook data.

**Comment by jeremystretch** [comment]
It probably makes sense to enable tags for webhooks as well.
