### ISSUE TITLE
Front&Back image on device overview page

### ISSUE THREAD

**Issue by deku-m** [netbox-community/netbox#11931]
### NetBox version

v3.4.5

### Feature type

Change to existing functionality

### Proposed functionality

Add the ability to add/upload device images to the front and back of device overview like they are already in devicetype.
See screenshot:
![afbeelding](https://user-images.githubusercontent.com/37069737/223712951-0a9cbeb5-d665-44f3-9890-ca7c0bd42de4.png)

As we got a simple idea to just use a design we created in Excel document as it also gives us an example of the port allocation by color which you could bind to perhaps cables/roles/vlans with something like a legenda.  
As extra if possible it would be great if a legenda could be added as table/column.

As shown below:
![afbeelding](https://user-images.githubusercontent.com/37069737/223713057-d588692b-907b-431d-b2ea-508291648afb.png)
![afbeelding](https://user-images.githubusercontent.com/37069737/223713119-53147781-da1b-4eb9-91e6-13112f50b068.png)

I am not talking about the rack picture that is added in the rack but mainly a bigger picture overview like shown in device-type.
As images attachment dont immediatly show the front or back images when opening the device overview and device-type does.

This also means that every created device might have there own images perhaps.

Also there is no copyright issue with device images that are taking from vendors as it is a simple design that could work for maybe all devices.

### Use case

For us  it gives us an example of the port allocation by color which we could bind to perhaps cables/roles/vlans with something like a legenda

### Database changes

Dont know

### External dependencies

Dont know

**Comment by jeremystretch** [comment]
The device type images are intended to represent the physical device only. What you're proposing appears to be aimed toward representing the device's _configured_ state. Not only would this be an incredibly slow, inefficient, and error-prone process, it's also unnecessary, as the configuration data is already available natively within NetBox.

If this is something you're committed to pursuing, I'd suggest developing a [plugin](https://docs.netbox.dev/en/stable/plugins/development/) to manage and embed the images on the device view.
