### ISSUE TITLE
Clone Saved Filters does not clone parameters+content types

### ISSUE THREAD

**Issue by FliesLikeABrick** [netbox-community/netbox#11933]
### NetBox version

3.4.5

### Python version

3.10

### Steps to Reproduce

1. Browse to /extras/saved-filters with at least one saved filter defined
2. Browse into a filter's details and select "Clone" 
4. Observe that the prepared filter does not have the key fields "content types" and "parameters" populated

### Expected Behavior

A cloned filter should inherit/copy the "content types" and "parameters" fields from the filter being cloned, as these are the defining characteristics of the filter's behavior

### Observed Behavior

The only field copied from the existing filter is "weight"; the fields of primary value for defining (and therefore cloning to edit) a filter are "content types" and parameters

**Comment by FliesLikeABrick** [comment]
With a little bit of pointers towards the right part of the code base, I'm happy to open a PR for this.

**Comment by arthanson** [comment]
@jeremystretch the content_types is an M2M field which CloningMixin.clone doesn't look like it handles.  Would this be something we'd want to add support for (ability to clone M2M fields)?
