### ISSUE TITLE
IPAM - IP Address - Tags in bulk import not working

### ISSUE THREAD

**Issue by Danielcraft15** [netbox-community/netbox#11947]
### NetBox version

v3.4.5

### Python version

3.8

### Steps to Reproduce

Navigate to the area: IPAM - IP Address - Bulk Import and execute the following variations:
 Variation 1:
`
address,tag,status
148.156.37.85/24,"echo",active
` 
Variation 2:
`
address,tag,status
148.156.37.85/24,echo,active
`
Variation 3:
`
address,tag,status
148.156.37.85/24,Echo,active
`

![image](https://user-images.githubusercontent.com/122042242/224330419-a64863f9-5c1d-4604-94d7-0de6e9ade237.png)

### Expected Behavior

I expect the tags to be applied after pressing "Submit".
Like it is shown in this screenshot:
![image](https://user-images.githubusercontent.com/122042242/224329525-fb250f87-c00b-4ec1-9bc1-5cc210b45852.png)

### Observed Behavior

None of the variations shown above creates the expected result.
![image](https://user-images.githubusercontent.com/122042242/224329190-20b3a9ee-c09f-4ac0-9fcf-e2472f49a3cb.png)

**Comment by jeremystretch** [comment]
The name of the field is `tags` (plural), not `tag`. (See the list of supported fields below the import form.) Correct the field name and tag assignment will work as expected.

**Comment by Danielcraft15** [comment]
Thanks for the fast reply, @jeremystretch. Three people with six eyes missed out on it! Have a great day!
