### ISSUE TITLE
Basic Module Compatibility "Form Factor"

### ISSUE THREAD

**Issue by Nealtron** [netbox-community/netbox#11959]
### NetBox version

v3.4.4

### Feature type

New functionality

### Proposed functionality

Create a new data point for both device module slots and modules that would could be used to filter compatible modules based on form factor.

I understand that this can get wildly complicated, but I'd recommend limiting this iteration to some form of field or tag matching. 

### Use case

To filter out incompatible devices when attempting to assign a module to a device, especially when that device uses an industry standard spot and accepts modules form many manufacturers. 

Ex1: Prevents an SFP from being "installed" into a PSU slot.
Ex2: Makes it easier to find all compatible LGX fiber optic modules that are manufactured by dozens of companies.

**Comment by jeremystretch** [comment]
Thank you for your interest in extending NetBox. Unfortunately, the information you have provided does not constitute an actionable feature request. Per our [contributing guide](https://github.com/netbox-community/netbox/blob/develop/CONTRIBUTING.md), a feature request must include a thorough description of the proposed functionality, including any database changes, new views or API endpoints, and so on. It must also include a detailed use case justifying its implementation. If you would like to elaborate on your proposal, please modify your post above. If sufficient detail is not added, this issue will be closed.

**Comment by jeremystretch** [comment]
Closing this as there's been no further response from OP.
