### ISSUE TITLE
Interface connection fills out some A side and some B side

### ISSUE THREAD

**Issue by wxnarwhal** [netbox-community/netbox#11970]
### NetBox version

v3.4.5

### Python version

3.8

### Steps to Reproduce

1. Go to interface or port 
2. click "Connect" and select interface.

### Expected Behavior

Expected behavior should be that all information from the interface I selected should populate on the A side.  Before I make the connection NetBox has no idea if the the B side is in the same room, or even the same site.

### Observed Behavior

Device and port/interface populate on A side, but the site and rack populate on the B side.

Verified on the demo site, one site I have running v3.4.5, and one site I have running v3.3.7.

**Comment by wxnarwhal** [comment]
Attaching screenshot.
![Screenshot_20230313_105711](https://user-images.githubusercontent.com/10369715/224793163-56ef1fb4-2ad3-4692-90fb-7bd0121e622b.png)

**Comment by jeremystretch** [comment]
The cable creation form has been significantly simplified for the upcoming v3.5 release. The region, site group, site, location, and rack fields have been removed in favor of a device selector widget (see #10054).
