### ISSUE TITLE
Add  "device template" function for device types that uses module types

### ISSUE THREAD

**Issue by muppaduppa** [netbox-community/netbox#11989]
### NetBox version

v3.4.6

### Feature type

New functionality

### Proposed functionality

Add a device template function. Device template would exist of a device type and a set of module types that that device types uses that are predefined.

As an example a device type could have 10 module bays. But standard device that gets deployed, always has a specific line card in one bay/power supply in one bay/Route Proccessor in the same bay and so on. 
Example picture below
<img width="1005" alt="image" src="https://user-images.githubusercontent.com/26269494/225542637-d5490d9d-9e4b-4a63-9af3-ebc737047e0d.png">
This standard device would be saved as an device template that you can add/remove/edit as with other device functions.

When adding a new device in UI you would then use this device template and have the standard device added with the correct set of modules directly. Instead of adding device and then add modules one by one.

You could create this standard device today as a device type but then you would loose the ability to change modules and if you need to change something you would need to delete/add device again. 

### Use case

Would save alot of time when adding new devices in UI and reduce errors when creating a new device. Instead of adding the device and then adding modules to the right bay this would be defined in device template.  

### Database changes

"Device template" need to be stored in database

### External dependencies

none

**Comment by jeremystretch** [comment]
This sounds like a subset of the "deployment template" functionality proposed back in #1364. It's something worth exploring further, but needs a lot more detail around the proposed implementation. @muppaduppa would you like to flesh this out some?
