### ISSUE TITLE
The 404 error page for the docs is displayed without styling

### ISSUE THREAD

**Issue by PenelopeFudd** [netbox-community/netbox#11997]
### NetBox version

v3.4.6

### Python version

3.8

### Steps to Reproduce

If you go to an invalid page on netbox.readthedocs.io (e.g. https://netbox.readthedocs.io/en/stable/installation/xyz/), you get a very weird page:
![image](https://user-images.githubusercontent.com/1606480/225760952-b69cacc2-9523-47b7-a081-e15d8d609a90.png)

If you scroll down far enough, you can see this message:

> 404 - Not found
Made with [Material for MkDocs ](https://squidfunk.github.io/mkdocs-material/)

### Expected Behavior

A nice and readable error page.

### Observed Behavior

An error on the error page.

**Comment by decoupca** [comment]
Looks like this is a known issue in mkdocs [under discussion](https://github.com/mkdocs/mkdocs/discussions/3153).
