### ISSUE TITLE
URL change in /opt/netbox-3.3.7/netbox/netbox/ldap_config.py

### ISSUE THREAD

**Issue by PenelopeFudd** [netbox-community/netbox#11994]
### NetBox version

v3.4.6

### Python version

3.8

### Steps to Reproduce

1. In a shell window, type `head -n 4 /opt/netbox-3.4.6/netbox/netbox/ldap_config.py`
2. Try going to the url shown there: https://netbox.readthedocs.io/en/stable/installation/5-ldap/

### Expected Behavior

Expected to see the documentation on enabling LDAP for NetBox.

### Observed Behavior

Got a page with a really big icon on it; scrolling down will reveal that it's a 404 error page.

The correct link is now https://netbox.readthedocs.io/en/stable/installation/6-ldap/

It'd probably be a good idea to fix the 404 error page too.   I checked with and without an adblocker, it's broken either way.

**Comment by kkthxbye-code** [comment]
That is a file you have created yourself, so we sadly cannot modify the URL present in it as it is only stored on your machine.

**Comment by PenelopeFudd** [comment]
Did I?  Whoops.

The 404 page is still a problem, however.

**Comment by kkthxbye-code** [comment]
> The 404 page is still a problem, however.

Do you mind creating a new issue for that? Gets a bit messy if you edit this one and our comments talk about the old issue.
