### ISSUE TITLE
ipam/prefix , a "container" prefix with no vrf assigned doesn't show children in other vrfs

### ISSUE THREAD

**Issue by anubisg1** [netbox-community/netbox#12009]
### NetBox version

3.4.5

### Python version

3.8

### Steps to Reproduce

1. create a prefix, assign role container and do not assign a vrf (this will make netbox automatically assign global)
2. create another prefix, children of the container and assign it to a vrf

### Expected Behavior

while it is clear that a vrf is a separate "ip stack" , a prefix marked as "container" should be considered a different object especially when it is not associated to a vrf.

by mean of being a "container" it should display all children prefixes across all different vrfs

view of the same object across different pages should be consistent 

### Observed Behavior

- ipam/prefix will share no parent/child relation what so ever
- opening the prefix specific page, and clicking on children prefixes, will show children prefixes in other vrfs but without depth indicators 

![image](https://user-images.githubusercontent.com/4518931/226307362-91dd75a9-5b46-4e86-bf04-f187ddb93a34.png)

![image](https://user-images.githubusercontent.com/4518931/226307531-e7c0681a-829a-49ca-bff6-a13b30f2a36c.png)

![image](https://user-images.githubusercontent.com/4518931/226307778-d8f4e513-6f15-425f-ad2c-79e39b67f327.png)

**Comment by bobbwest** [comment]
I disagree with your idea of "container".

If I am allocating addresses in my global table, and in VRFs, from a specific prefix, I want an specific container to allocate these from, regardless of whether it's global or a VRF.

The downside of including all VRFs under a container without an assigned VRF is that it's almost impossible to work out what has and hasn't been allocate in global: there's no way to filter Child Prefixes like there is for the IPAM > Prefixes table.

The downside of not including all VRFs under a container is that you might need to duplicate a few prefix containers, one for each VRF (and global).  This is easier to work around than the former.

**Comment by DanSheps** [comment]
> I disagree with your idea of "container".

Unfortuantely, this idea of "container" is the documented behaviour of container, with respect to the global table.  If you assign a VRF to a container, it operates as a container for prefixes within that VRF only.

**Comment by anubisg1** [comment]
> @anubisg1 It properly shows the prefixes, it just is an inconsistent display, correct?

That's what I see.

If you are in the prefixes page, it shows only nested prefixes from the global vrf, but if you open the prefix in the prefix specific page and click on child prefixes page, then it shows them all as I would expect

**Comment by DanSheps** [comment]
Could you provide some data to reproduce this properly?

**Comment by jeremystretch** [comment]
Closing this out as I see nothing to indicate unexpected behavior, and OP has not responded to a request for additional information.
