### ISSUE TITLE
Add device type/role to Interface filter

### ISSUE THREAD

**Issue by ty8berg** [netbox-community/netbox#12015]
### NetBox version

v3.4.4

### Feature type

New functionality

### Proposed functionality

Add the ability to filter interfaces by device types or device roles. I would like to review a set of devices that all fall under one device type or device role, and check whether a connection has been made to the interface. However, to do this, I have to search for each device individually and select every one into the filter to display what would be the same result if I could just filter by device type/role.

### Use case

The use case for this would be reviewing and checking interfaces easily for specific device types or roles. More specifically, the ability to see cables and their connections for device types and roles.

**Comment by jeremystretch** [comment]
If undertaken, this should be implemented consistently for all device components (not just interfaces).

**Comment by ty8berg** [comment]
Hi Jeremy, 

Yes I agree, the ability to filter any of the device's components by device roles or device types would be highly beneficial
