### ISSUE TITLE
KeyError when adding Module Bays to devices

### ISSUE THREAD

**Issue by MarioSpenc** [netbox-community/netbox#12011]
### NetBox version

3.4.6

### Python version

3.10

### Steps to Reproduce

1. Add device
2. Goto devices overview 
3. mark new device
4. click on "Add Components"
5. click on "Module Bays"
6. Fill in "Name"
7. click "Create"

### Expected Behavior

New Module Bay should be added.

### Observed Behavior

Error Message:
Server Error
There was a problem with your request. Please contact an administrator.

The complete exception is provided below:

class 'KeyError'

'position'

Python version: 3.10.6
NetBox version: 3.4.6

**Comment by GoldyXXD** [comment]
I also get this error when I'm trying to bulk add Module Bays to multiple devices. It doesn't error out for me if I do it for a single device though. Started happening after the update to 3.4.5. I've just tested 3.4.7 and issue still occurs.
