### ISSUE TITLE
Global to model refined search

### ISSUE THREAD

**Issue by PieterL75** [netbox-community/netbox#12017]
### NetBox version

v3.4.5

### Feature type

Data model extension

### Proposed functionality

With the new search, the option to go to the 'Refine Search' is gone.
This was a very handy feature. If the search result returned what you needed, it brought you direct to the details page of the model.

I would like to make the 'model' column of the global search a link, that brings you to the model-list with the filter applied.
![image](https://user-images.githubusercontent.com/74899468/226554892-12fb1d3d-3ae9-42b5-b918-711ea457d75c.png)
In the above image, the 'Device' could become a link that brings you to https://demo.netbox.dev/dcim/devices/?q=-rtr

The only caveat is the Lookup type... if using anything else then partial, it will return different values in the model-search

### Use case

One-click forward to details of the searchresult

**Comment by jeremystretch** [comment]
I'm going to close this out as the proposed implementation doesn't appear to be feasible and there's been no further discussion.
