### ISSUE TITLE
Bulk rename of rear-ports duplicates replace pattern

### ISSUE THREAD

**Issue by phurrelmann** [netbox-community/netbox#12019]
### NetBox version

v.3.4.3

### Python version

3.9

### Steps to Reproduce

Select a range of rear-ports and try to bulk rename them.
The static part of the replace pattern is being duplicated.

Steps to reproduce:

1. Create a device multiple rear-ports.
2. Select multiple of rear-ports and hit rename to open the bulk rename template
3. Enter the regex "(.*)" into the find field and enter "Dummy\1" into the replace field
4. Hit Preview

### Expected Behavior

All rear-ports are renamed and prepended with the prefix "Dummy"

### Observed Behavior

All rear-ports are renamed and prepended **and** appended with "Dummy".

Screenshot from our local installation (v.3.4.3):
![image](https://user-images.githubusercontent.com/10113716/226578103-8ec730a9-1ea7-4cf4-9ed1-ac8326ee8660.png)

Screenshot from netbox demo (v3.4.6):
![image](https://user-images.githubusercontent.com/10113716/226577889-4854be41-5a5c-472c-9501-0e9fee4769fb.png)

**Comment by phurrelmann** [comment]
The same behavior is seen on bulk-rename of interfaces and front-ports.
A workaround is to make the regex match the start, too by using "^(.*)".

**Comment by decoupca** [comment]
I'll take this one

**Comment by kkthxbye-code** [comment]
Maybe I'm misunderstanding, but how is this a bug?

The * token means zero or more, which matches empty string and the string. The + token means one or more:

<img width="1172" alt="image" src="https://user-images.githubusercontent.com/400797/226665910-f22d7cb8-7cfc-43a8-b3cd-76222031b87a.png">

**Comment by kkthxbye-code** [comment]
> Understood. There are several ways to match. But not the matching seems to be the problem, but the replace. Both (your and my example) match the whole source as a group and that retained in the replace by "\1". The question is why is "Dummy" prepended _and_ appended in my example, but not in others.
> 
> Working correctly: match: "^(.*)" and "(.+)"
> 
> not working: match: "(.*)"

I'm saying this is how regex engines work to my knowledge. Here's regexr.com:

<img width="562" alt="Screenshot 2023-03-21 at 17 06 47" src="https://user-images.githubusercontent.com/400797/226669330-85713eea-9f0e-4cc9-9d9d-ed2284721c83.png">

Do you have an example where this causes an issue when using the right regex token?

**Comment by phurrelmann** [comment]
Ok, so I was mistakenly expecting it to work like re.sub with "count=1". if the defaults are fine for everyone, then this is no bug and the issue can be closed.

Thanks for the fast responses from all and sorry for the noise.
