### ISSUE TITLE
Not Paths Found on cable tracing of Rear Ports with Modules

### ISSUE THREAD

**Issue by jonatangobbato** [netbox-community/netbox#12025]
### NetBox version

v3.4.5

### Python version

3.9

### Steps to Reproduce

1. Create a device A (Switch) and add some Interface SFP+
2. Create a device B (Fiber Patch Panel) and add a Module with 12 Front ports (LC [1-12]) and 12 Rear Ports (SC [1-12])
3. Create a device C (Fiber Patch Panel) and add a Module with 12 Front ports (LC [1-12]) and 12 Rear Ports (SC [1-12])
4. Create a device D (Switch) and add some Interface SFP+
5. Connect interface of Device A to 2 front Ports Of Device B LC 1 and LC2
6. Connect the rear interfaces SC 1 and SC 2 of Device B to the rear interfaces SC 1 and SC 2 of the Device C
7. Connect SFP+ interface of Device D to the front interfaces LC 1 and LC 2 of the device C.

### Expected Behavior

When click on cable trace of the interface SFP+ of the device A, show the entire trace of the cable to the Device D, including the fiber patch panels on the way.

### Observed Behavior

When click on the cable trace of Device A interface, only the trace to the device B are show, and a "Path split!" Warning appears and ask to select what nodes have to continue. When i click on one node, a page with the "No paths found" appears.

![image](https://user-images.githubusercontent.com/29125329/226637540-6f3cb5ef-cff8-4568-8494-5a0c0b8deed4.png)

![image](https://user-images.githubusercontent.com/29125329/226637613-8afbc4e3-d041-4b93-8978-03f83c0115ae.png)

**Comment by jonatangobbato** [comment]
Update.
IF no Module on device B and dedvice C, the trace works fine.

![image](https://user-images.githubusercontent.com/29125329/226641242-adde16ba-576d-4fbf-b67f-66053f5cb591.png)

**Comment by DanSheps** [comment]
This might be fixed with #11079, I will test when I have time

**Comment by arthanson** [comment]
@DanSheps were you able to test if this was fixed?

**Comment by arthanson** [comment]
@jonatangobbato would you be able to test this with NetBox v3.6.3?  I think it is probably fixed

**Comment by DanSheps** [comment]
I think the big thing is going to be you shouldn't be using multi-position rear ports with multi-plex cables as we have no easy/clean way of telling which cable which rear port should connect to.  You should instead use a single cable for each rear port (typically rear ports will be your plant fiber, if you are using multi-position ports, that is your "buffer" (12 fibers strands bundled).  If you think of a 244, you would have:

* 288 strands total
* 24 buffers (Buffer tube really, Blue, Green, ... Blue-1, Green-1, etc)
* 12 strands per buffer

Rear ports, with 12 positions, should be a single cable that is your "buffer".  You shouldn't try and connect 2 "buffers" to 2 rear-ports.

**Comment by DanSheps** [comment]
Tried 2 different ways:

![image](https://github.com/netbox-community/netbox/assets/11049792/1146a6a1-21f2-49aa-9af2-a4001069466e)
https://demo.netbox.dev/dcim/interfaces/3079/trace/

![image](https://github.com/netbox-community/netbox/assets/11049792/55ced87d-adb7-4b66-9038-4753912596ec)
https://demo.netbox.dev/dcim/interfaces/3080/trace/

I would say 100% fixed
