### ISSUE TITLE
Overlapping/Multiple NAT Support

### ISSUE THREAD

**Issue by engageant** [netbox-community/netbox#1202]
Issue Type: Feature Request

Currently, netbox only allows a 1:1 mapping of inside IPs to outside IPs.  If an inside IP is homed to several ISPs each with their own address space, we cannot accurately represent the NAT configuration in netbox:
**IP address with this NAT IP (inside) already exists.**
Currently, what I'm doing is adding the primary outside IP as the NAT address, then I add the secondary outside IP as an additional IP on the interface - not ideal.  Would it be possible to extend the NAT functionality to allow one-to-many (inside to outside) mappings?

**Comment by jeremystretch** [comment]
Not sure how I feel about this. The outside-to-inside mapping is currently one-to-one. Relaxing this constraint so that multiple outside IPs can share a single inside IP opens the door for ambiguity. If A and B are both outside IPs for C, then we have no way of discerning what our outside IP will be in a scenario where we only know C.

**Comment by engageant** [comment]
Hmmm...any ideas on how to better accomplish this with the functionality
already in place?

**Comment by traveler3468** [comment]
Thanks for getting me on the right discussion @jeremystretch. Sorry I missed it. 
For me since this is a documentation tool I think it would be helpful to just be able to see that information. 
IP C is NAT'd to both A and B, but for different destinations. On the IP address page for IP C you can look in the NAT (outside) section and see the IP's that it may be getting NAT'd to. But if you look at one of the outside addresses it will only be related to the one inside address

**Comment by cslingerland** [comment]
What if you were to add a "destination" IP field for the NATs. Then you could have multiple NATs sourcing from a single IP, and you'd be able to tell the difference based on the destination.

**Comment by achard** [comment]
> Not sure how I feel about this. The outside-to-inside mapping is currently one-to-one. Relaxing this constraint so that multiple outside IPs can share a single inside IP opens the door for ambiguity. If A and B are both outside IPs for C, then we have no way of discerning what our outside IP will be in a scenario where we only know C.

I would point out that the ambiguity you are talking about is already there in the real world that is being modelled. If you only know C, and only one of the outside NAT addresses is listed in Netbox, somebody looking at Netbox may not realise that there are other addresses that could be a NAT outside address for this inside address.

This seems pretty straight forward on the surface.. change the OneToOneField to a ForeignKey.. plus the UI changes to accommodate multiple values :/

**Comment by dubblies** [comment]
Any traction here? Would love the ability to do this, beyond a small business, i dont know why you would restrict your NATs on a single IP...

**Comment by samuryan89** [comment]
Would also be interested in this. We have several external IP's that are NAT'd to multiple internal IP's and there's no way to model this in Netbox?

**Comment by vsvetlov** [comment]
Hello,

@jeremystretch 
As a temp solution, I would suggest updating a list of the roles for IP address object type with something like:
- Static NAT
- Dynamic NAT
The reason for it is that a NAT IP address is usually served by a network device (router or firewall) and should be assigned to its interface but this use case is not covered by VIP, Secondary or HSRP roles.

**Comment by jennec** [comment]
Did this ever get implemented?  

We have soo many instances of multuiple outside IPs NAT'ing to a single Inside I which just can;t be documented in NetBox.  

I have been trying to get colleauges to adopt NetBox as a documentation source for years now and they will not buy into it if it can't document what is percevied to be (rightly or wrongly) a standard within the industry.  

@jeremystretch any chance this can be be revisited?

**Comment by jennec** [comment]
To add to my issues, I also have 1:Many NATs that route to different internal IPs fro a single external IP based on the service (port number) that is used.  I would like to be able to respresent this also.

**Comment by achard** [comment]
This is not just an issue for Overloaded NATs. It seems a little like you have made a decision that static 1:1 NAT is the only legitimate use of NAT.

The world I am trying to model in Netbox is AWS. I need to be able to assign Elastic IPs (Which are essentially DNATs) to VPC addresses. Sometimes an internal address will have multiple EIPs. I dont think its Netbox's job to resolve the above mentioned ambiguity.

**Comment by BatmanAMA** [comment]
to add to the support, we have many services that are offered internally to multiple private networks managed by different groups and those services are natted into their networks - documenting this mass of nats is critical to being able to support it and even more critical to automating DNS management

**Comment by ruant** [comment]
Any plans on what milestone this is gonna be in?
PAT support is a must.

**Comment by samfroggy** [comment]
Hi All,
Did this get anywhere, we're looking at adopting this for our clients internally.

We also have multiple (inside) NATing, i.e
External IP A, maps to multiple internal IPs B and C.

Thanks

**Comment by agowa338** [comment]
no, not until now...

**Comment by noide35** [comment]
Hello,

no news for this request ?
I currently have the same need which is NOT PAT but be able to NAT one real/inside IP to multiple outside/natted IP.
So this is not PAT but NAT depending on the external network/isp/view. And it is the subject of the first message of this issue.

So in that case we still have a one-to-one IP mapping regarding the outside IP.
To do that, we need to be able to list have a list of outside NAT IP in the Real IP.  The opposit of today where we indicate a real/inside IP in the outside one.

**Comment by dmoranf** [comment]
Hi,

Same use case here, it would be great if we can associate and have a list of multiple inside/outside NATs for a unique Real IP since we are doing different NAT for different source networks / clients.

**Comment by achard** [comment]
Got tired of waiting, anyone interested can support the issue here too
https://github.com/nautobot/nautobot/issues/630

**Comment by agowa338** [comment]
Is everything ok within netbox-community? There are so many deleted comments.
Was an account of the organization hacked?

**Comment by jeremystretch** [comment]
Per our contributing policy, comments with no substance or which do not relate to the topic at hand are removed to preserve the conversation's focus.

**Comment by apellini** [comment]
Also for me this feature could be useful.

I have multiple customer that I see using NAT 1:1 but Customer sees my services with different NAT IP of my service.

For example:

Service A Real IP on VRF PROD: 10.1.1.1
NAT IP Service A on VRF CustomerA: 10.20.20.1
NAT IP Service A on VRF CustomerB: 10.20.30.1

So I need to correlate 10.20.20.1 and 10.20.30.1 to 10.1.1.1 so I could have the correct NAT Table represented on NetBox.

Thanks in advance. If I could help tell me.

**Comment by maw1146** [comment]
Hi Guys,
why my comment was deleted? I have just asked if there was any update on this case...

**Comment by jeremystretch** [comment]
Per the [contributing guide](https://github.com/netbox-community/netbox/blob/develop/CONTRIBUTING.md):

> Only comment on an issue if you are sharing a relevant idea or constructive feedback. **Do not** comment on an issue just to show your support (give the top post a :+1: instead) or ask for an ETA. These comments will be deleted to reduce noise in the discussion.

If there were any updates on this issue, they would appear here. There is no reason to ask.

**Comment by jsenecal** [comment]
As discussed over in Slack, I would be willing to take ownership of this Feature Request if contributions are accepted.

**Comment by jeremystretch** [comment]
I'm going to tag this for v3.3 with the understanding that its implementation is limited to extending the current model to allow many-to-one NAT mapping. Because it has come up in conversation, I want to be clear that this FR _does not_ entail L4 port mapping: Some additional data model (to be proposed in a future FR) would be needed to support that.
