### ISSUE TITLE
Allow IP address to be assigned to VDC interface

### ISSUE THREAD

**Issue by kzhang1310** [netbox-community/netbox#12037]
### NetBox version

v3.4.5

### Feature type

Change to existing functionality

### Proposed functionality

Allow IP address to be assigned to VDC interface
![image](https://user-images.githubusercontent.com/26172689/226982194-2c7b3d86-8b03-4fef-a082-3847fdf66140.png)

### Use case

currently allow  IP addresses to be assigned to physical and VM devices

**Comment by DanSheps** [comment]
Do you have any suggested implementation details for this?

**Comment by jeremystretch** [comment]
Closing as there's been no further response from OP.
