### ISSUE TITLE
Propagate Tags to Components when adding object

### ISSUE THREAD

**Issue by jclbc** [netbox-community/netbox#12032]
### NetBox version

v3.4.1

### Feature type

New functionality

### Proposed functionality

e.g.: when adding module or device is it possible to add, for components created with this new object,:
-checkbox "propagate Tags to components"
or
-new field "tags for components"

### Use case

I'm using tags on all objects (for permissions), I would like to propagate tags from object to components.
for now, when a user add new module, he doesn't have permissions on interfaces

### Database changes

none

### External dependencies

none

**Comment by jeremystretch** [comment]
Thank you for your interest in extending NetBox. Unfortunately, the information you have provided does not constitute an actionable feature request. Per our [contributing guide](https://github.com/netbox-community/netbox/blob/develop/CONTRIBUTING.md), a feature request must include a thorough description of the proposed functionality, including any database changes, new views or API endpoints, and so on. It must also include a detailed use case justifying its implementation. If you would like to elaborate on your proposal, please modify your post above. If sufficient detail is not added, this issue will be closed.

**Comment by jeremystretch** [comment]
This issue is being closed as no further information has been provided. If you would like to revisit this topic, please first modify your original post to include all the requested detail, and then ask that the issue be reopened.
