### ISSUE TITLE
Provide Scripts/Reports a feature to standardize send_email output

### ISSUE THREAD

**Issue by ryanmerolle** [netbox-community/netbox#12041]
### NetBox version

v3.4.6

### Feature type

New functionality

### Proposed functionality

As stated in the documents, you can setup send_mail in the configuration.  It would be nice to add an additional feature to:

1. Enable automatic email of "job" (script and email) completion - should be a boolean sort of like `commit`
2. Provide a message variable where you can feed it markdown, but if not set would the email message to send the script/report summary table (already rendered in netbox) and a link to the specific report job results.

### Use case

Remove the barrier to entry for users creating reports and scripts that want to fire off emails.

### Database changes

None

### External dependencies

None

**Comment by jeremystretch** [comment]
@ryanmerolle could you expand the above to include a mock-up of the proposed implementation? I think the fundamental functionality is clear but I'd like to see some discussion around a concrete implementation. Thanks!
