### ISSUE TITLE
Allow custom scripts to specify which users and/or groups are allowed to run them 

### ISSUE THREAD

**Issue by BarbarossaTM** [netbox-community/netbox#12050]
### NetBox version

v.3.4.6

### Feature type

New functionality

### Proposed functionality

Allow custom scripts to specify which users and/or groups are allowed to run them and bail out of the user isn't allowed.

### Use case

We are starting to write a number of custom scripts, either to be run by operators via the WebUI or via the API, and want to enforce RBAC to scripts as we do for manual changes to the data (models).

The overall intention here is to codify processes, make sure they are followed, data is validated before put into NetBox, and also reduce toil from operators by automating multi-step tasks. One example would be to set up a link between two devices, meaning set up the Cable, create a LAG, assign IPs left and right (on the right interfaces), make sure the IPs are in the same subnet, etc. and in the future adding more steps into this process, like allocating the next-free prefix, choose ports, etc.

To keep our role-based permission managed in check we want to be able to defined who is allowed to run each script. To the best of my knowledge this isn't easily possible today.

### Database changes

None.

### External dependencies

None.

**Comment by BarbarossaTM** [comment]
Our current approach is a wrapper class for our Scripts which does the checking. I think it might be worth having this as part of the NetBox Script class, so this available for everyone. Maybe the same is even relevant for Reports?

Our current approach looks like this:

```
from extras.scripts import Script

from utilities.exceptions import AbortScript

from django.contrib.auth.models import User

class ACMEScript(Script):
    """Common wrapper class for all ACME NetBox scripts.

    No script should directly inherit from this class, but rather from
    - ACMEUIScript for interactive scripts, or
    - ACMEAPIScript for scripts to be called via the API
  
    This class handles permission handling and acts according to the presence (or absence)
    of the following class-level variables:
    - require_user_and_group (bool): If True, validate user and group list, by default one is enough.
    - allowed_users (list): List of usernames allowed to execute this scripts
    - allowed_groups (list): List of groups (of users) allowed to execute this scripts
    """

    def validate_permissions(self):
        # Lots of checks here, raise Exception if user/group is not allowed
```

I'm happy to open a PR to add this to the base class if this is deemed useful :-)

**Comment by jeremystretch** [comment]
In NetBox v3.5, report and script modules will manifest as database objects, which opens the door for object-based permissions controls. This would only be granular to the module and not individual reports/scripts, but that may be sufficient.
