### ISSUE TITLE
NetBox 3.5 unauthenticated user homepage issues

### ISSUE THREAD

**Issue by ryanmerolle** [netbox-community/netbox#12061]
### NetBox version

v3.5.0-dev

### Python version

3.8

### Steps to Reproduce

1. login window shows up in change log dashboard
2. instead of lock icons (current 3.4 approach), all object counters show 0

### Expected Behavior

1. no change log widget shown when not authenticated(current 3.4 behavior) or an empty widget with possibly a lock icon
2. lock icons instead of zeroed out object counters.

Not a huge item, just bring to attention before the beta.  This can also just be ignored if deemed to little of an issue.

### Observed Behavior

![image](https://user-images.githubusercontent.com/9010275/227754362-0ea87bc2-fd89-46ac-af50-dc64fea8b787.png)

**Comment by abhi1693** [comment]
This does not happen when `LOGIN_REQUIRED=True`. I came across this as well during development although wasnt sure if this was intentional change or not.
