### ISSUE TITLE
Allow processing webhooks when global config context has been updated

### ISSUE THREAD

**Issue by abhi1693** [netbox-community/netbox#12064]
### NetBox version

v3.4.6

### Feature type

Change to existing functionality

### Proposed functionality

When a user makes a change to the global config context, the webhooks should be triggered automatically for the affected devices.

### Use case

We manage our syslog configuration by site/tenant via the global config context. In some cases, it needs a little tweak now and then when a new platform is added or to comply with our organization policy. It becomes harder to track down all the devices that are affected by the config context and do a fake update just to trigger the webhooks.

The auto-trigger of the webhooks will geatly reduce the time needed to re-run the hooks manually, will avoid human errors wherein a device could be missed.

I have thought of applying the content types of config context as well on the webhook and then use the DB ID as the condition but that seems like a hack and feels more error prone if a user deletes the context and re-creates it (for whatever reason), the hook will never be triggered.

**Comment by kkthxbye-code** [comment]
I don't see any way to feasibly implement this. Imagine the following netbox instance:

* 10k devices
* 1k virtual machines
* 500 modules

Someone creates, edits or deletes a config context with no filters (will apply to all devices, vms and modules). The result would be 11500 webhooks being queued. The webhooks themselves are sent in a background task, but all 11500 objects must be serialized and queued in the same request as the save. Conservatively this would take minutes to complete.

Do you have a proposed implementation of your FR?

**Comment by abhi1693** [comment]
I guess this should be blocked until https://github.com/netbox-community/netbox/issues/11202 is implemented. With background processing, your concern should be addressed

**Comment by kkthxbye-code** [comment]
> I guess this should be blocked until #11202 is implemented. With background processing, your concern should be addressed

As I said, webhooks are already processed in the background, but you still need to serialize the objects up front. So we still need a proposed implementation here.

**Comment by abhi1693** [comment]
I'll try to think of something then. I thought serialisation would also be off loaded to the worker.
