### ISSUE TITLE
Unable to add changelog widget

### ISSUE THREAD

**Issue by abhi1693** [netbox-community/netbox#12063]
### NetBox version

v3.5.0

### Python version

3.10

### Steps to Reproduce

I mistakenly deleted the changelog widget and when I tried adding it back, there was no such option in the drop-down menu

### Expected Behavior

Changelog widget should be available as an option

### Observed Behavior

Changelog widget not visible in the drop-down menu for selection

**Comment by kkthxbye-code** [comment]
The changelog widget was previously a standalone widget type but is now just an ObjectListWidget.

**Comment by abhi1693** [comment]
That's very inconvinient to be removed. It helped alot just to see the latest changes right from the homepage. 

If this is not planned, it should not be a part of the default dashboard either but since it is provided initially, a user should be able to add it back into the homepage.

![image](https://user-images.githubusercontent.com/5083532/227786342-3a895c2f-3921-48cc-831e-1794ed9878ac.png)


The `ObjectListWidget` is not the same as `ChangelogWidget` as I'm interested to see the changes not the objects themselves.

**Comment by kkthxbye-code** [comment]
> The ObjectListWidget is not the same as ChangelogWidget as I'm interested to see the changes not the objects themselves.

How so? Can you show what you mean?

This is from the demo site:

![image](https://user-images.githubusercontent.com/400797/227787361-77bc6bcf-2f0e-4787-a93c-2a44c779dfb8.png)

This is from the feature branch:

![image](https://user-images.githubusercontent.com/400797/227787378-00d6fe02-26dc-439d-a4d9-17c47c254395.png)

**Comment by kkthxbye-code** [comment]
This is me re-adding the widget after removing it:

![image](https://user-images.githubusercontent.com/400797/227787443-c15fbff8-dcf8-4234-814a-a0c6dcc488f1.png)

![image](https://user-images.githubusercontent.com/400797/227787455-a523b676-ca37-4e90-b427-ac995d3bc1ab.png)
