### ISSUE TITLE
Extend default MIME type for export templates to specify UTF-8

### ISSUE THREAD

**Issue by gdprdatasubect** [netbox-community/netbox#12095]
### NetBox version

v3.4.7

### Python version

3.8

### Steps to Reproduce

1. Create an object where the name contains UTF8-Characters (E.g. a device containing é )
2. Create a custom Export templates that accesses said object names (E.g.: `{%for device in queryset%}{{device.name}}{%endfor%}
`
3. Use the Export template on previously created objects

### Expected Behavior

Same as with "Current View" and "All Data (CSV)", there it works just fine:
![grafik](https://user-images.githubusercontent.com/101808236/228752851-a76b31c3-22af-43a4-ac75-f71f2c88101d.png)

### Observed Behavior

![grafik](https://user-images.githubusercontent.com/101808236/228752734-b7b39be5-054c-4542-9620-9e29ea0dd9bf.png)
Characters get mangled up

**Comment by jeremystretch** [comment]
This doesn't happen for me; the content comes through as expected. However I suspect this is occurring because the default MIME type for an export template is `text/plain`. Try setting this to `text/csv; charset=utf-8` in your export template.

**Comment by jeremystretch** [comment]
Thanks @gdprdatasubect! I've reclassified this as an enhancement just because I think it's _slightly_ more accurate relative to existing behavior, though admittedly it's a gray area.
