### ISSUE TITLE
Widget UI enhancement on site pages

### ISSUE THREAD

**Issue by thefreakquency** [netbox-community/netbox#12098]
### NetBox version

v3.4.3

### Feature type

Change to existing functionality

### Proposed functionality

As available on main page where you can click on a line to get redirected to the corresponding section, it would be a great to have the same behavior on site pages. 

Homepage:  If we click anywhere on the line, (in this example, Devices), we are sent to the /dcim/devices/ page.
![image](https://user-images.githubusercontent.com/25624251/228868139-ec4962b6-d3d6-4020-bba8-963b0c7761ad.png)

However, in a site page (/dcim/sites/#/), if you hover a line in the Related Objects widget, it is highlighted but if you click on it, nothing happens:
![image](https://user-images.githubusercontent.com/25624251/228867932-f5037906-2bbb-4b0c-92bd-c09b5dc721bd.png)
In order to consult the corresponding item, you have to click on the number on the right. 

I suggest the UX be the same for widgets. I believe the full-line approach would be more convenient to the users. 

### Use case

This is simply to enhance the user experience. 

### Database changes

None

### External dependencies

None

**Comment by jeremystretch** [comment]
As luck would have it, this has already been tackled under #11517 for the upcoming v3.5 release. Each row in the list is clickable as you describe.

![Screenshot 2023-03-30 at 10-47-43 DM-Akron NetBox](https://user-images.githubusercontent.com/13487278/228875226-f5af0598-67f5-40db-85e1-e41a0cd50014.png)

I'm going to close this out as having already been addressed, but please do follow up with any feedback regarding the beta release (which should be out very soon).
