### ISSUE TITLE
NetBox 3.5 beta via mobile is overly challenging due draggable function

### ISSUE THREAD

**Issue by ryanmerolle** [netbox-community/netbox#12108]
### NetBox version

v3.5.0-dev

### Python version

3.8

### Steps to Reproduce

1. Open NetBox via mobile.
2. Draggable widgets and touchscreen scrolling do not mix well.  You scroll and accidentally move widgets.

You have 2 options to tackle this issue.  You can start with 1 or apply both:

1. Seems like we can override the `draggable` parameter in gridstack.js to just work with the widget heading
2. Set a dashboard lock option that is enabled by default.  Users can select edit and the "draggability" of the dashboard is enabled.

### Expected Behavior

Be able to scroll

### Observed Behavior

Draggable widgets and touchscreen scrolling do not mix well.  You scroll and accidentally move widgets.

**Comment by jeremystretch** [comment]
FWIW I don't think those options are mutually exclusive. I think it's worth doing both.

**Comment by PieterL75** [comment]
I would suggest that the all is locked by default.. and that you get an 'Edit Dashboard' button at the bottom. Once clicked it is replaced with 'Save Dashboard' and 'Cancel', while all widgets are draggable/editable..

**Comment by ryanmerolle** [comment]
> FWIW I don't think those options are mutually exclusive. I think it's worth doing both.

Yep that was what I was trying to articulate.  I think you apply both options, but I did not want to fully prescribe the approach if there were better ideas.

**Comment by jeremystretch** [comment]
I've opened #12119 to track the lock toggling separately as an enhancement, but will use this issue to address limiting the draggable area of a widget.
