### ISSUE TITLE
Define error responses for endpoints in the OpenAPI spec

### ISSUE THREAD

**Issue by amhn** [netbox-community/netbox#12116]
### NetBox version

v3.5-beta

### Feature type

Change to existing functionality

### Proposed functionality

This is based on #4986

The new API definition only includes the default response for a path. This makes it hard for code generators to create working code.

Adding the following responses to the relevant paths would help:
400: All responses?
404: All except post and bulk actions
403: All responses with security

### Use case

More correct API definition to help library developers and automatic code generators

**Comment by arthanson** [comment]
I think this is a partial solution, see the discussion: https://github.com/tfranzel/drf-spectacular/issues/101#issuecomment-1497790997 The ValidationError is problematic according to spectacular maintainer.  Something like https://github.com/ghazi-git/drf-standardized-errors would be a more complete solution (also integrates with spectacular) but would change the error return format for all APIs, not sure what ramifications if any this would have - also would be another package to add... investigating.
