### ISSUE TITLE
Error when creating device from device type with parent inventory item

### ISSUE THREAD

**Issue by aurelienbyi** [netbox-community/netbox#12118]
### NetBox version

v3.4.7

### Python version

3.10

### Steps to Reproduce

1. Create a new Device Types
2. Add 1st Component :  Inventory Item
3. Add 2nd Component : Inventory Item, with 1st component as Parent
4. Create a new Device from this Device type

### Expected Behavior

New device created with Inventory Items from Device Type

### Observed Behavior

Server error : 

```
<class 'dcim.models.device_components.InventoryItem.DoesNotExist'>

InventoryItem matching query does not exist.

Python version: 3.10.6
NetBox version: 3.4.7
```

with debug : 

```
DoesNotExist at /dcim/devices/add/
InventoryItem matching query does not exist.

Request Method:  POST
Django Version: 4.1.7
Exception Type: DoesNotExist
Exception Value: InventoryItem matching query does not exist.
Exception Location: /opt/netbox/venv/lib/python3.10/site-packages/django/db/models/query.py, line 650, in get
Raised during: dcim.views.DeviceEditView
Python Executable: /opt/netbox/venv/bin/python
Python Version: 3.10.6
Python Path : ['/opt/netbox/netbox/',  '/usr/lib/python310.zip',  '/usr/lib/python3.10',  '/usr/lib/python3.10/lib-dynload',  '/opt/netbox/venv/lib/python3.10/site-packages']
```

**Comment by kkthxbye-code** [comment]
This needs some logic like I created here in 3.5 for interface bridges:

https://github.com/netbox-community/netbox/pull/11869/files#diff-242fa4d6e937ebcf01bba9f882cf4f17a40799ef33b5637a00726fbfbaec7c1fR463-R476
