### ISSUE TITLE
Add the option to automatically push changes to objects when synchronizing data sources

### ISSUE THREAD

**Issue by jeremystretch** [netbox-community/netbox#12129]
### NetBox version

v3.5-beta1

### Feature type

Change to existing functionality

### Proposed functionality

#11558 introduced the ability to populate certain object data from remote data sources. Currently, this is a two-step process:

1. Run a synchronization job to create/update local DataFile objects from the source.
2. Individually sync NetBox objects to reflect the new data in those DataFiles.

This separation of tasks is intentional, and ensures a decoupling of synchronization jobs (which are expected to be automated) from effecting a change to production data. However, there may be cases where it's desirable to effect changes immediately upon synchronization with the remote source.

This FR proposes the addition of an `auto_sync` boolean field to the `SyncedDataMixin` class. Any object with `auto_sync` set to true shall have its `sync_data()` method called automatically upon its associated DataFile being updated.

### Use case

This provides an alternative direct coupling approach to employing synchronized object data, while preserving the existing loose coupling as the default option.

**Comment by arjenvri** [comment]
This is a great feature! Would this also allow for existing object data update and removal possibly based on the remote data source data?
