### ISSUE TITLE
v3.5-beta1: Allow Object Count and Object Lists widgets on the Dashboard to accept filters

### ISSUE THREAD

**Issue by gdprdatasubect** [netbox-community/netbox#12136]
### NetBox version

v3.5-beta1

### Feature type

Change to existing functionality

### Proposed functionality

Allow the Object Count and Object Lists  widgets on the Dashboard to accept filters per selected object type in the same way as object filters work on the normal pageview URL, e.g. "manufacturer_id=5&platform_id=15&cf_fieldname=xyz" or "filter_id=1".
Ideally the identifier for this would have it's own label, because in the example "Devices" is kinda non-descriptive when filters are applied.

### Use case

Advantages include:
* Controlling your personal assigned "IT-assets under management"
* Easier inventory control
* Quick linking to relevant information

### Database changes

New field to save the filter and its name

**Comment by peteeckel** [comment]
I have the exact same feature suggestion. There are a lot of use cases, e.g. not displaying deactivated or disconnected items, or being able to separately list objects that belong to different realms such as sites, tenants etc., so this would really improve the dashboard functionality a lot.
