### ISSUE TITLE
Custom Field information/hint button

### ISSUE THREAD

**Issue by opensourceXnetbox** [netbox-community/netbox#12131]
### NetBox version

v3.4.7

### Feature type

New functionality

### Proposed functionality

In my opinion, an information description for a specific `custom field` is missing. If the `Custom Field` is very specific, an expandable information text would be very helpful.
The Custom Field `inBackup` serves as an example. In this case, a functional description can be quite helpful.

![netbox-information](https://user-images.githubusercontent.com/110609354/229208168-5de3cea2-fd20-495d-934f-8325b3533ba7.png)
collapsed information button
![netbox-information-open](https://user-images.githubusercontent.com/110609354/229208185-61251a95-f021-4b28-9062-fd4dc178097c.png)
folded out information button
![netbox-information-edit](https://user-images.githubusercontent.com/110609354/229208191-73d75847-dda8-4bb7-885f-6d19db928da8.png)
Custom Field setting

### Use case

Especially new and inexperienced NetBox users would get a better overview of the special functions and backgrounds of this custom field. Users with reading rights also have no possibility to view the description during the editing process or under the tab `Other`.

### Database changes

Nothing

**Comment by jeremystretch** [comment]
While I see the value in adding a pop-up explaining the field, I would think showing the field's description is sufficient. I don't see a need for a separate field.

**Comment by opensourceXnetbox** [comment]
Hey @jeremystretch , I think so too. For my use cases it's enough if the `Description` field is displayed as pop up.

**Comment by jeremystretch** [comment]
Sounds good. Tagging this as `needs owner` with the understanding that no new fields are being introduced.

**Comment by decoupca** [comment]
The description is already in the title text of the field name. Adding a blue info icon to every custom field may get cluttered. Might it be more appropriate to give a more subtle hint that more info is available by hovering over the field title, maybe a help cursor?

<img width="740" alt="Screenshot 2023-04-05 at 4 27 51 PM" src="https://user-images.githubusercontent.com/94914780/230216359-d05e9a84-2c13-4144-bfe2-b79d8cc543ad.png">

**Comment by opensourceXnetbox** [comment]
Hey @decoupca, I have thought about this again and see a clear hint button or hint field as very useful. In my opinion, people with little NetBox experience should also be given the opportunity to understand everything as quickly as possible. But the color and form of the hint can also be adapted. This was my first suggestion, which should not be considered as final.

**Comment by decoupca** [comment]
> Hey @decoupca, I have thought about this again and see a clear hint button or hint field as very useful. In my opinion, people with little NetBox experience should also be given the opportunity to understand everything as quickly as possible. But the color and form of the hint can also be adapted. This was my first suggestion, which should not be considered as final.

to your point, I mouseover tooltips don't work on mobile, so a clickable/tappable icon would be more accessible.

**Comment by abhi1693** [comment]
@jeremystretch Need some clarity on this. I maybe understanding the requirement wrong. The code already has a description on the hover, should I move this to `<i>` with an icon just like you have done for deprecated fields?

```
<span title="{{ field.description|escape }}">{{ field }}</span>
```
