### ISSUE TITLE
Render config for device is not consistent between UI and API

### ISSUE THREAD

**Issue by abhi1693** [netbox-community/netbox#12144]
### NetBox version

v3.5-beta1

### Python version

3.10

### Steps to Reproduce

1. Create a GIT datasource using https://github.com/jeremystretch/example-config-templates and sync
2. Create a config template and choose the file `roles/access-switch.j2`
3. Add local config context that can be used in the rendering
4. Apply the config template on your device
5. Call the API at `/api/dcim/devices/<id>/render-config/`

### Expected Behavior

The render config should automatically take the device context into the rendering process

### Observed Behavior

Rendered config does not have context data

**Comment by abhi1693** [comment]
@jeremystretch Would you like me to submit the PR as I already have the commit ready?

**Comment by jeremystretch** [comment]
I've performed a bit of additional cleanup as well, but thank you!
