### ISSUE TITLE
Selector should not be displayed for disabled fields

### ISSUE THREAD

**Issue by abhi1693** [netbox-community/netbox#12146]
### NetBox version

v3.5-beta1

### Python version

3.10

### Steps to Reproduce

Go to any interface edit page and notice the selector field. You can open it and choose a different device and the same will reflect in the UI. Upon save, no error is throw, however, this **does not** change the device.

### Expected Behavior

The selector should not be visible when the field is disabled

### Observed Behavior

Selector is displayed which misleads the user into thinking the change is still possible.

![image](https://user-images.githubusercontent.com/5083532/229295190-8378f556-27cf-441d-a55d-846e134128eb.png)
![image](https://user-images.githubusercontent.com/5083532/229295211-771c5868-8c17-46ef-b837-947acb46b396.png)
![image](https://user-images.githubusercontent.com/5083532/229295219-7aebebda-fb07-4552-9e4d-b9ff87ed3baf.png)

**Comment by jeremystretch** [comment]
@abhi1693 already taken care of, thanks though!
