### ISSUE TITLE
Allow VLAN Group hierarchy with specific scopes

### ISSUE THREAD

**Issue by BrunoBlanes** [netbox-community/netbox#12147]
### NetBox version

v3.4.5

### Feature type

Change to existing functionality

### Proposed functionality

Propose to expand the current VLAN Group model to allow nesting to itself given specific scopes. See *Use case* section for better understanding.

### Use case

We as an ISP have VLAN Groups for dedicated link clients. We use this group throughout our network in all of our sites therefore it is scoped to the major region that we cover. However, within this region and group, we have subsets of VLAN Groups specific to the sites present in this region.

Consider the VLAN Group `A` being scoped to region `USA` and having a range set as `1000-2000`. This range is only to be used for dedicated link clients in major cities. This range is then subdivided into smaller ranges for each major city.

I'd like to be able to create a VLAN Group `B` that belongs to group `A` and is instead scoped to a site or region belonging to the region `USA` or to some region that has a child relationship with the `USA` region, i.e. `Florida`, and has a range that is limited, but not necessarily equal to, its parent range, i.e. `2100-2050`.

### Database changes

Unsure, but definitely some major relationship additions, it shouldn't break any existing ones or be a breaking change.

**Comment by jeremystretch** [comment]
> Unsure, but definitely some major relationship additions, it shouldn't break any existing ones or be a breaking change.

I'm sorry but you're going to need to provide much more detail about the proposed implementation. A use case alone is not sufficient. If you're unsure of what to propose, please consider closing this FR and starting a [discussion](https://github.com/netbox-community/netbox/discussions/new/choose) instead to collaborate with others who may be able to help devise an implementation.

**Comment by jeremystretch** [comment]
This issue is being closed as no further information has been provided. If you would like to revisit this topic, please first modify your original post to include all the requested detail, and then ask that the issue be reopened.
