### ISSUE TITLE
Datasheet Attribute for Device Types

### ISSUE THREAD

**Issue by phillf** [netbox-community/netbox#12154]
### NetBox version

v3.4.7

### Feature type

New functionality

### Proposed functionality

- Add attribute to device types and module types for datasheet URLs
- Append a link with the display text of "View Datasheet" to the Description field of the Chassis/Module Type table 

### Use case

Creating a consistent expectation of where the reference to the datasheet is found and how it's referenced. 

### Database changes

Create new field named DatasheetUrl for Device and Module Types.

**Comment by abhi1693** [comment]
This may also be useful in module types

**Comment by phillf** [comment]
> This may also be useful in module types

Agreed. Feature Request amended.

**Comment by jeremystretch** [comment]
I find myself on the fence here. Most people just link to relevant documentation in the object's comments. This enables the addition of context pertaining to each link as well.

> Creating a consistent expectation of where the reference to the datasheet is found and how it's referenced.

- Is there a need to consume these links programmatically?
- What do you do if there are multiple links to relevant documentation?
- Is a custom field not sufficient for this purpose?

**Comment by phillf** [comment]
> * Is there a need to consume these links programmatically?
I could see this being useful where other tools are concerned when it comes to pulling data out of Netbox via API. Having it it as "free text" in the comments doesn't really make it easy to pull this data whereas having it as discrete data would easily allow this.

> * What do you do if there are multiple links to relevant documentation?
Maybe adding an attribute of the link being something like "Publication Type" would be useful here. (ie. Service Manual, Parts Catalogue, Datasheet, etc)

> * Is a custom field not sufficient for this purpose?
That would be but the point of the feature request was to make this more consistent across instances. Relying on the custom field means that it could be named slightly differently from instance to instance.

This request was actually inspired by reading through some of the device-type template YML files and wondering why the datasheet links were free text comments rather than discreet data.

**Comment by DanSheps** [comment]
From a technical standpoint, I ManyToOne (FK) or a M2M relationship would be best for this with a new model "ExternalLinks".  Similar to how our contacts are done.  That said, this could also be perfectly suited for a plugin.

A rough model:

```
LinkType:
  int id
  str name

Link:
  int id
  LinkType type
  str name
  str url

LinkAssignment:
  GFK object
  Link link
```

**Comment by phillf** [comment]
@jeremystretch, Given the answers I provided and @DanSheps sggested model I am curious where you stand now.

**Comment by jeremystretch** [comment]
I don't see any reason this use case isn't served by a custom field. And I definitely don't think there's any need for a separate model tracking discrete links.

**Comment by DanSheps** [comment]
I have to agree with @jeremystretch here.  Custom fields, in conjunction with custom links perhaps, are the best to provide the right set of options.

However, if there is a need for more robust tracking, I would encourage you to create a plugin for it and publish it so that is can be consumed by others.
