### ISSUE TITLE
Add support for TCP6 and UDP6 protocols in service templates and services

### ISSUE THREAD

**Issue by Sow1995** [netbox-community/netbox#12163]
### NetBox version

v3.4.7

### Feature type

Data model extension

### Proposed functionality

TCP6 and UDP6 are not available in the protocol dropdown when creating a service.

It's proposed to add UDP6 and TCP6 to the protocols list

### Use case

Currently it is not possible to add TCP6 and UDP6 connections to services. Being able to add services that use the TCP6 and/or UDP6 protocol makes it possible to distinguish between the two when adding a service that has both an IPv4 and a IPv6 connection.

**Comment by Sow1995** [comment]
I can provide a PR as well, when this has been approved.

**Comment by jeremystretch** [comment]
TCP6 and UDP6 aren't actual protocols. Rather, they're just shorthand used by some applications to imply that a port is bound to an IPv6 address (which can already be modeled explicitly in NetBox).

**Comment by DanSheps** [comment]
I agree with @jeremystretch on this.

You can determine if it is TCP6 by the type of address assigned.

**Comment by jeremystretch** [comment]
Closing this as it does not seem to warrant any action.
