### ISSUE TITLE
VNI ranges

### ISSUE THREAD

**Issue by ciroiriarte** [netbox-community/netbox#12168]
### NetBox version

v3.4.5

### Feature type

Data model extension

### Proposed functionality

It's currently possible to document VXLAN Network Identifiers (VNI) using the Overlay logic/module:

![image](https://user-images.githubusercontent.com/1750260/229821474-719c11e8-2108-4e0f-8d53-dcdcfc0b935f.png)

But we're missing the range tracking as we have for VLANs. The proposed functionality would be to track VNI assignment to be able to request "next available in range".

### Use case

Proper tracking for VNI assignments, as done with VLAN ranges.

### Database changes

No proficient in the DB schema, but would asume at least range definition & VNI to range relationship.

**Comment by ciroiriarte** [comment]
> Can you give me an example of how a VNI range is used in production or is this more of an organizational thing?

Hello!, yes it's more an organization thing. The current use case:
- Ranges are assigned to different datacenters, in case EVPN type 2 is required at some point in time, we won't have a clash.
Site A: Range1
Site B: Range2
Site C: Range3
Cross datacenters: Range 4
- In some scenarios, we have more than one provisioning team per site (different business units), so we also need to assign more than one range per site so those teams can provision independently in the same  IP Fabric.
- Domain is tracked via tags, with a domain being an administrative domain or network (Datacenter IPFabric vs IPRAN vs ISP core vs Fixed access). That's used for all the constructions and doesn't require any change in Netbox.
- Also, for provisioning we need a way of tracking VNI usage. The idea would be for a script to:
1. ask Netbox "give me next VLAN in range for X site & Y domain"
2. ask Netbox "give me next VNI in range for X site & Y domain"
3. set the VNI to VLAN relationship
4. provision the VNI within the fabric & matching VLANs towards the servers (trunk mode)
5. provisiong the VLAN tagging configuration on the server side

**Comment by jeremystretch** [comment]
Thanks for the proposal, but I'm afraid it's too short on detail. What would the proposed VNI range model look like?
