### ISSUE TITLE
Inherit interface VLAN assignments from VLAN groups

### ISSUE THREAD

**Issue by oneone84** [netbox-community/netbox#12173]
### NetBox version

v3.4.3

### Feature type

New functionality

### Proposed functionality

I would like to have the option to inherit all vlans in a vlan group (dynamically) to an interface. As it is now, I seem to be able to select a VLAN Group for an interface, but the only functionality it seems to provide, is to filter the list of selectable tagged/untagged vlans.

If I associate an interface to a vlan group and then later on change the vlans in the group, the changes should be inherited to the interface.

I would however, be able to loop the vlans in a group, if only the interface's association with a vlan group is saved. This might be easier to implement.

### Use case

It is usefull to be able to quickly modify many interfaces configured with vlan group, by changing the group instead of all those interfaces. One example could be maintining a list of vlans trunked to all hypervisors in a network.

### Database changes

I would imagine that an interface would need to associate with a VLAN Group, today when selected, the group settings is lost immediately.

### External dependencies

None

**Comment by jeremystretch** [comment]
We could associate an interface with a VLAN group, but I can't see how we'd do this in a way that doesn't break the existing direct VLAN associations. Additionally, doing so would impose a dangerous scenario where adding or removing a VLAN would result in the automatic (and potentially unexpected) manipulation of an interface's configuration.
