### ISSUE TITLE
Device Image url on the Rack sesion has absolute url and not relative

### ISSUE THREAD

**Issue by enribla** [netbox-community/netbox#12176]
### NetBox version

v3.3.8

### Python version

3.9

### Steps to Reproduce

1. Create a rack
2.  Create a device and put it on the rack
3. go to the rack menu and select the rack
4. click on the device. You will be redirected if you are using a proxy with a different url

### Expected Behavior

the expected behaviour is to confinue with the same url, for that we need relative values for the url. If not we are going to bypass the proxy.

### Observed Behavior

The url is redirected to the url behind the proxy.

**Comment by jeremystretch** [comment]
This is a configuration issue. Please see [this FAQ on our wiki](https://github.com/netbox-community/netbox/wiki/Common-Issues#rack-elevation-links-use-wrong-domain).
