### ISSUE TITLE
Search for Prefix on VLANs Page Produces No Result

### ISSUE THREAD

**Issue by michaelmcdonald** [netbox-community/netbox#12177]
### NetBox version

v3.4.7

### Python version

3.8

### Steps to Reproduce

1. Create a new VLAN with an ID and name
2. Create a new prefix, assigning it a subnet, a description, and associate it with the previously created VLAN
3. go to VLANs page and search for previously created prefix in "Quick search" field

### Expected Behavior

Results should be limited to the prefix / VLAN searched for (just like when searching for VLAN number, VLAN name, VLAN description).

### Observed Behavior

Results display "No VLANs found" message.

**Comment by jeremystretch** [comment]
Thank you for opening a bug report. Unfortunately, the information you have provided is not sufficient for someone else to attempt to reproduce the reported behavior. Remember, each bug report must include detailed steps that someone else can follow on a clean, empty NetBox installation to reproduce the exact problem you're experiencing. These instructions should include the creation of any involved objects, any configuration changes, and complete accounting of the actions being taken. Also be sure that your report does not reference data on the public NetBox demo, as that is subject to change at any time by an outside party and cannot be relied upon for bug reports.

**Comment by michaelmcdonald** [comment]
I'm going to assume this is actually expected behavior. Tried searching for the VLAN name on the Prefix page and a similar result occurred.

**Comment by jeremystretch** [comment]
> I'm going to assume this is actually expected behavior.

That's correct; the quick filter for VLANs does not match against assigned prefixes due to the overhead involved.
