### ISSUE TITLE
Racks with units starting > 1

### ISSUE THREAD

**Issue by bebehei** [netbox-community/netbox#12175]
### NetBox version

87e7cc4867d1 (v3.4.6)

### Feature type

Data model extension

### Proposed functionality

Currently, it is possible to assign a rack an arbitrary number of height units (usually 42 or 47). The starting point is fixed to `1`, so all Devices in this Rack are located in RU `{1..Y}`.

This GitHub issue requests, that the starting point does not start hard coded from 1.

### Use case

If you rent a quarter half/quarter/third rack, the starting point is not fixed necessarily fixed to Rack Unit 1. To talk to remote hands, this is quite confusing.

Current possible workarounds:

- You could currently work around by creating a full rack and assigning Rack Reservations.
    - CON: This will falsely blow up the actual space utilisation of your rack. (e.g. quarter rack used with 2 Rack units displays 80% Rack Usage, while actually only 10% are used.)
- Assign the rack the actual height and use instead of 41-60 the units 1-20.
    - CON: You have to convert this when talking to remote hands (error prone).
    - CON: Rack Photos show the actual rack unit and not the virtual unit
- Tenancy should be a possibilty, but I haven't found anything to work around this with tenancy.

**Comment by jeremystretch** [comment]
It sounds like adding a `starting_unit` integer field to the Rack model would suffice. We'd no doubt have to dig through a lot of logic that assumes a starting unit of 1, but it should be feasible.

**Comment by bebehei** [comment]
Thank you all for adding this feature!
