### ISSUE TITLE
Add interface type "20GBASE-KX4 (20GE)" in Ethernet (backplane)

### ISSUE THREAD

**Issue by a-belhadj** [netbox-community/netbox#12174]
### NetBox version

v3.4.4

### Feature type

Data model extension

### Proposed functionality

We have some hardware with HP FlexFabric 20Gb 2-port 630FLB ADAPTER interfaces. We would like to have `20gbase-kx4`. 

### Use case

Add  'HPE BL460c Gen9 - 727021-B21' devices in Netbox.

**Comment by jsenecal** [comment]
Do you have a link to supporting documentation to provide ?

**Comment by a-belhadj** [comment]
Hello Jonathan, 

Here is the official documentation of BL460c Gen9 https://www.hpe.com/psnow/doc/c04380273.html?jumpid=in_lit-psnow-red

In the chapter "Technical specification", you can find: `HPE FlexFabric 20Gb 2-port 650FLB FlexibleLOM`


![image](https://user-images.githubusercontent.com/82872898/231156923-7bb7e6a0-a01b-4a2a-a124-80a6f255686c.png)

Maybe it's KR4 instead of KX4, let you decide.

Is it what you need ?

**Comment by bitcollector1** [comment]
Can we add the 400G as well, I'm looking at deploying some of these NIC's for our Snake Test Traffic Generators running iperf :)  

https://www.nvidia.com/content/dam/en-zz/Solutions/networking/ethernet-adapters/connectx-7-datasheet-Final.pdf

**Comment by jeremystretch** [comment]
> Maybe it's KR4 instead of KX4, let you decide.

You want us to add an interface type to NetBox, but you're not sure what it's called? Please do some more research to determine exactly what it is you want to add.
