### ISSUE TITLE
Cloning a device type does not clone any interface or component

### ISSUE THREAD

**Issue by TnTBass** [netbox-community/netbox#12179]
### NetBox version

v3.4.7

### Python version

3.10

### Steps to Reproduce

1. Select an existing device type with interfaces, console ports and power ports
2. Select "Clone"
3. Name your new device type

### Expected Behavior

I would expect a clone of the device type to come with all interfaces/ports/etc for easier editing. There is no benefit to cloning a template over creating a brand new one.

### Observed Behavior

Discover no interfaces, console ports or power ports come pre-populated

**Comment by jeremystretch** [comment]
This is expected behavior, and consistent with the cloning of every other object type in NetBox. Replicating every related component has been proposed (see #5536) but no one has ever volunteered to own its implementation. You're welcome to open a new FR for it if you'd like to volunteer.

**Comment by jsenecal** [comment]
This was proposed in https://github.com/netbox-community/netbox/issues/4065 and again in https://github.com/netbox-community/netbox/issues/5536 and https://github.com/netbox-community/netbox/issues/8840, but no one was interested in owning the implementation.

**Comment by jsenecal** [comment]
Lol @jeremystretch beat me to it.
