### ISSUE TITLE
FHRP groups: should support scopes

### ISSUE THREAD

**Issue by SteveRodrigue** [netbox-community/netbox#12185]
### NetBox version

v.3.3.10

### Feature type

New functionality

### Proposed functionality

At the moment, FHRP groups are global (no scope). Because of that, it's impossible to create the same group in different routers/locations/clusters. Which is possible and often the case in practice.

FHRP groups should have a scope like VLAN groups.

### Use case

The feature is not usable as soon you want to reuse the same group ID in 2 locations router pairs, etc.

Typical setup when you have multiple locations/group of routers:
Router A and B in location X = VRRPv3 group id #10
Router C and D in location Y = VRRPv3 group id #10

At the moment, it's impossible to add/attach multiple group with the same ID.

**Comment by jeremystretch** [comment]
How would this help if routers A and B are in the same location? Or the same rack? It's a nice idea but I don't see this really working in practice. Instead, you can assign a unique name to each group for better identification. Granted it's not a great solution, but I don't see a scope assignment being of much help.
