### ISSUE TITLE
Decrease amount of padding in data tables from the current 64% of vertical space

### ISSUE THREAD

**Issue by bluikko** [netbox-community/netbox#12199]
### NetBox version

v3.4.7

### Feature type

Change to existing functionality

### Proposed functionality

Currently there is more vertical padding in data tables than there is actual data. Taking an example from the demo site:
![image](https://user-images.githubusercontent.com/14869000/230545413-5abe8074-3259-48ad-a61a-0ff6e6bd4949.png)
Whitespace below row separator line until tickbox is 14 pixels.
The tickbox at the left is vertically 16 pixels.
Whitespace below until row separator line is 14 pixels.

Taking into account the actual row separator lines it means roughly 35% of vertical space in the table is actual data and the rest is just padding!

Data is one of the main points of NetBox. So it should be the main point, front and center.  
Reducing padding would assist in reaching that.

Of course there needs to be some amount of padding to keep the data readable. But look at spreadsheet programs - they have minimal padding and people have no trouble using them all day. In fact, people who use those programs each day *require* there to be minimal padding since they want to see the data (the reason for the whole exercise) and not scroll all the time just to see more padding.

The correct amount of padding surely is less than about 90% of actual data at the above and another 90% at the below?  
Experiments would show what is the minimal usable amount of padding; or just start decreasing it every version and pull back when complaints start.

I would guess the real reasonable number is somewhere less than half of the current amount. For data rows:
- Current _effective_ CSS padding seems to be 1rem.
- At least in 3.0.6 padding used to be 11px above/9 px below in data rows and in 3.4.7 it is 14/14px measured at the same position, an increase of around half.
- Below examples concentrate on what seems to be `padding` in `html[data-netbox-color-mode=dark] .table>:not(caption)>*>*` / files `netbox-{dark,light}.css`.
- Conservative reduction could be to reduce _effective_ padding to 0.5rem for data rows.
- More aggressive but at least on 1080p screens perfectly legitimate reduction would be to 0.2rem.
- This should be tested on hiDPI screens, especially the more aggressive reduction to 0.2rem.
- For accessibility concerns, reduction to 0.2rem still seems to satisfy AA-level WCAG.

Make data great again!

### Use case

To efficiently view data, the reason why NetBox exists.

### Database changes

None.

### External dependencies

None.

**Comment by jsenecal** [comment]
Could you provide a screenshot of the intended looks of it and potential CSS values ? (Using chrome dev tools should work for this purpose)

**Comment by bluikko** [comment]
I do not understand at all what @sleepinggenius2 is trying to say but it seems like this

> WCAG target size requirement is 24px x 24px for AA conformance and 44px x 44px for AAA conformance for pointer inputs

is supposedly trying to say that any clickable control should be "24px x 24px" for "AA" level accessibility and "44px x 44px" for "AAA" level, where more As supposedly are "better"?

I think that it would not be realistic to propose changing that selection tickbox at the left of each data row that's currently about 16x16 px to 24x24 or even 44x44.  
Does that have something to do with padding?

I am all for accessibility but 24x24 or 44x44 minimum control sizes are just not possible without majorly ruining the experience for everyone else.  
It is surely better to let those who need "AA or AAA level accessibility" to zoom the page in (or let them use OS level settings to make everything bigger) instead of forcing everyone else (99% of users) to zoom out.  
Even Windows Explorer at default 100% setting does not have "24x24 or 44x44" "pointer inputs" (whatever that may mean).

@jsenecal I will have a look at what I can do to test. It's not something I'm familiar with but sounds straightforward.

**Comment by sleepinggenius2** [comment]
@bluikko, it sounds like you are not a frontend developer or, if you are, then your response is very concerning, as all frontend web developers should be intimately familiar with WCAG. Here is a link to some more information on target sizes: [Understanding Target Size](https://www.w3.org/WAI/WCAG22/Understanding/target-size-minimum).

**Comment by bluikko** [comment]
@sleepinggenius2 That's right - I am not a frontend developer. I do however have a long history using various software and I know very well how an efficient UI works. An efficient UI does not have two thirds of whitespace and one third of data.

I had followed with admiration your accessibility work. But it must not come at the price of efficiency for everyone else.  
So I repeat what I said: it makes no sense to make an inefficient UI for the sake of less than 1% of users.

**Comment by sleepinggenius2** [comment]
I can completely understand that perspective, which is why I proposed adding a user preference to control the density of lists and data table rows. UX design is a complex field and the "efficiency" of an interface can take many factors into account. In addition to the biological factors, people have screens with different pixel densities, different mouse sensitivities, different lighting conditions, the list goes on and on. Imposing one person's preferences on the entire user base, especially when they don't necessarily meet established web accessibility standards, is not really fair. I have seen in the code where ARIA attributes have been included, in addition to discussions made during the last UI redesign, which indicate that accessibility is a concern of the NetBox developers. I support this feature request, but I was merely bringing attention to the fact that it is not as simple as just making willy nilly changes to the CSS.

**Comment by bluikko** [comment]
Some example screenshots.

The starting point from demo instance:
![image](https://user-images.githubusercontent.com/14869000/231043097-45c954d1-6b11-439f-bbf1-4f8bf6e3968d.png)

Here the padding is decreased from 1 rem (!!) to 0.2 rem, which is a rather conservative decrease (it could be decreased even further but I wanted to stay at the magical 24 px even though I've not seen any policy regarding NetBox and accessibility):
![image](https://user-images.githubusercontent.com/14869000/231042381-2829372e-b225-4f39-b2fb-4ec0a2d00997.png)

The "target size" seems to still be above the "AA" level at 24x31.38.  
The amount of data lines on the first page increases from 17 to 21, that's a _massive gain of almost a fourth_ and full data pages gain proportionally even more. And all by this simple change that takes NetBox more towards how it used to be with _data_ being the main point.

Note how now the padding at left/right is so pronounced. This is all just wasted space but reducing it is not so simple in order to keep the controls neat:

![image](https://user-images.githubusercontent.com/14869000/231042462-4770d0c4-5c5c-464f-bffa-9f31e319f821.png)

Here I decreased the padding around the table which is simple and gains good results. But there is still 1-2 levels of padding at the sides - chiefly the are highlighted by the blue line at the left.  
But this padding at the left/right side should not be decreased willy-nilly, since the padding highlighted with the green boxes should probably be taken into account/kept as is.

I would definitely look at reducing at least some of that padding highlighted with the blue line.

A separate proposal, if it is too much for this issue, should probably look at decreasing padding at left/right of the data tables to.. dare I say it: **zero**.

**Comment by bluikko** [comment]
And here is a tighter example with 3 different padding changed:
```css
html[data-netbox-color-mode=dark] .table>:not(caption)>*>* {
    padding: 0.1rem; /* decrease from 1rem */
}

html[data-netbox-color-mode=dark] .card-body {
    padding: 0.2rem; /* decrease from 1rem */
}

html[data-netbox-color-mode=dark] .tab-content {
    padding-left: 0.2rem; /* added, padding was 1rem */
    padding-right: 0.2rem; /* added, padding was 1rem */
}
```

![image](https://user-images.githubusercontent.com/14869000/231046711-bdaedee6-78a1-41ee-a311-c168b270f617.png)

Another 3 lines are gained in the first page and horizontal padding gain is more than the yellow control at the right.  
Please note that we are still staying at the 24px magical double-A limit!

But the header row doesn't look good, it would need some additional padding.

**Comment by bluikko** [comment]
>Please link them for context, it helps gauge actual interest.

In addition to that 11682, 6975, 6372 come up with keyword "padding" and they seem to be relevant to general "whitespace"/"padding".

I note that some of those are even pre-3.0 and if I remember correctly the amount of whitespace has really blown up at/after 3.0.  
2.x was much more conservative with whitespace and I do not recall anyone requesting for more padding or complaining. I could not find any such issues either.

> My personal opinion is that trying to make netbox look like a spreadsheet, as seem to be your goal, is not a great way to design modern websites

Nowhere do I argue for zero padding between rows. Initially I had proposed halving from the current 1rem but looking at the results (in the above screenshots) I feel that the 0.2rem may be closer to the sweet spot *on my current 1080p screen*.

> Your last example here would look absolutely terrible on any monitor with a larger resolution imo.

I am currently not with my high-dpi screen and unfortunately may not be with it in some weeks so I could not answer to this right now. Maybe you have an example then?  
However - I suspect that those users who want to have larger UI elements would have configured their OS-level controls according to their screen and personal preferences.  
I totally agree that this scenario is *absolutely* something that needs to be considered!

I also want to return to your statement about "not a great way to design modern websites". Would you care to expand this with something constructive?  
In my OP I had stated my rationale and I try to rephrase it here: the main point of NetBox is to show data tables. The reason it exists is for data which may be sometimes be viewed by users through the web interface. Shouldn't that data then be the basis of the design and not "making it look shiny" or "fruity" or "trendy"?  
Some whitespace is definitely a requirement due to our neurophysiology. But what argument is there for having two thirds of vertical screen real estate as padding? One of the features that help here, shading alternating rows with slightly different background colors has seemingly been dropped at some point - I think it used to be done before (together with much less vertical padding).
  
There is currently a trend towards excessive whitespace everywhere and this can be seen even in Windows 11. Whitespace may be a usability requirement for touch UI but as I had argued above I suspect that these users are in an overwhelming minority and as such could be satisfied with a responsive design instead of making a suboptimal experience for traditional pointer users.

**Comment by kkthxbye-code** [comment]
There seems to be a communication barrier here that I'm not sure we'll be able to surmount and to be frank you have a very combative way of arguing that seems less than constructive. 

I'll refrain from handling this, but please update your FR to contain the specific changes you are suggesting. If it needs more discussion before you can propose the actual change, feel free to create a discussion instead.

**Comment by jeremystretch** [comment]
A few thoughts:

1. The depth of discussion here is _wildly_ disproportionate to the change being proposed, and the wording of this proposal is unnecessarily assertive and confrontational.
2. I'm not interested in making any substantial changes to the UI styling at this time. We're planning to migrate to Tabler for v4.0 (see #12128) in the near future.
3. Bootstrap 5 provides a `table-sm` (small) class that reduces cell padding by 50%, which I believe is the ultimate goal of this FR. I've included screenshots below showing the original and reduced padding.

There are two options moving forward:

1. Adopt the reduced padding style provided by BS5.
2. Do nothing.

Please limit discussion to the merits of either of these two options.

![original_padding](https://user-images.githubusercontent.com/13487278/231161508-f6d6f10b-7aa5-4b03-a537-a83a8ad4cb50.png)
![reduced_padding](https://user-images.githubusercontent.com/13487278/231161514-d40ab7a4-97f4-47e9-bd71-3368b8c12e77.png)

**Comment by jsenecal** [comment]
I would also like to remember everyone interested that user-space utilities like [Greasemonkey/Tampermonkey](https://somethingididnotknow.wordpress.com/2013/07/01/change-page-styles-with-greasemonkeytampermonkey/) exist for those situations where the UI doesn't look the way an individual requires it.
