### ISSUE TITLE
Use whitenoise so that netbox can be deployed without an additional webserver.

### ISSUE THREAD

**Issue by vyas-n** [netbox-community/netbox#12208]
### NetBox version

v3.4.7

### Feature type

New functionality

### Proposed functionality

I'd like to add whitenoise as a dependency so that Netbox can serve static files and not need an additional webserver to be deployed with the static files copied over to it.

If it's approved, then I'd be willing to create the PR to add this functionality.

This is admittedly a duplicate of #2463, but I'd like for this to be reconsidered, and that ticket is closed for comments.

### Use case

While the nginx/Apache config is standard practice for server-based deployments, it's usually redundant in k8s environments since k8s-native features (Loadbalancer service-type, Ingress resources, API Gateway resources, ...) can handle routing and load balancing http connections better.

This allows k8s users to simplify their cluster setup and remove the complexity of building another container image for their deployments.

This also enables compression & caching throughout the network path (browser-level, loadbalancer-level, CDN-level, ...) so that static files end up using less network bandwidth and get served less frequently.

### Database changes

N/A

### External dependencies

whitenoise pip package:
- pypi: https://pypi.org/project/whitenoise/
- docs: https://whitenoise.readthedocs.io/en/latest/

**Comment by tobiasge** [comment]
You can use [netbox-docker](https://github.com/netbox-community/netbox-docker) in Kubernetes.

**Comment by vyas-n** [comment]
Hi @tobiasge,

Mind explaining what the solution would be? I already have a netbox container that I'm building as a part of my helm chart. Perhaps I can use the same technique in my container as you used in yours?

**Comment by tobiasge** [comment]
You don't have to build the image. Just point a deployment configuration to it an set the environment variables as needed.
There is also a Helm chart: https://github.com/bootc/netbox-chart

**Comment by vyas-n** [comment]
Thanks @tobiasge, for the link to the helm chart (I'll take a look and consider using it within my organization), but I'm still left with my original question unanswered.

Would you mind providing the solution for how can Netbox be deployed without nginx/Apache or any other webserver?

If not, then can Netbox consider using the whitenoise pip package as a solution?

**Comment by tobiasge** [comment]
In the Docker image [Nginx Unit](https://unit.nginx.org/) is used as web server. It can run the Python application and serve static files.

**Comment by vyas-n** [comment]
Thanks @tobiasge, that works for my use-case!

Should i close this issue, or leave it open in case anyone else needs this?

**Comment by DanSheps** [comment]
It is possible that there might still be some benefit to this, I did a little bit of looking into whitenoise and it is interesting what it lets you do, that said, not sure if there is enouhgh value in it to introduce another dependancy.

**Comment by jeremystretch** [comment]
It sounds like a solution has been identified for the use case cited. (Please correct me if this is wrong.) I'm going to close this out as not currently requiring further action, but happy to revisit in light of a new use case.
