### ISSUE TITLE
Ability to Update Devices en Masse by Importing CSV

### ISSUE THREAD

**Issue by kalazzawi** [netbox-community/netbox#12215]
### NetBox version

v3.4.7

### Python version

3.10

### Steps to Reproduce

1. Navigate to Devices > Export > create CSV file.
2. Modify existing records CSV file, netbox_devices.  Remove all other rows that will not be modified.  In the example below, add TBA03270652 into one filed in the serial number column.  
3. Save the CSV file.
4. Upload the CSV file by navigating to Devices > Import.

### Expected Behavior

1. Navigate to Devices > Export > create CSV file.
2. Modify existing records CSV file, netbox_devices.  Remove all other rows that are not be modified.  In the example below, I added TBA03270652 into one filed in the serial number column.  
3. Save the CSV file.
4. Upload the CSV file by navigating to Devices > Import.
5. Error messages.

![netbox_devices](https://user-images.githubusercontent.com/17362831/230802002-97d187c3-30e1-455c-8363-437fe265f92b.png)

### Observed Behavior

It would be a nice feature to UPDATE entries in mass from a CSV file.  Currently, there is only a way to ADD new entries through the GUI.  Error message observed (below).
![2023-04-09 19_46_26-Device Bulk Import _ NetBox and 20 more pages - Work - Microsoft​ Edge](https://user-images.githubusercontent.com/17362831/230802114-eba3862f-f3d4-4d82-8feb-4740d8f6fad5.png)

**Comment by kkthxbye-code** [comment]
The export format is not meant to be used directly as input, which is told you in the last issue as well. Here is the link again:

https://github.com/netbox-community/netbox/wiki/Frequently-Asked-Questions#why-cant-i-pass-exported-data-directly-into-the-import-form

> It would be a nice feature to UPDATE entries in mass from a CSV file.

That is already possible.

> Currently, there is only a way to ADD new entries through the GUI.

No that is not true. Bulk update was added in version 3.4:

https://docs.netbox.dev/en/stable/release-notes/version-3.4/#update-existing-objects-via-bulk-import-7961
