### ISSUE TITLE
New dashboard widgets have insufficient header contrast in dark mode

### ISSUE THREAD

**Issue by sleepinggenius2** [netbox-community/netbox#12219]
### NetBox version

v3.5.0-dev

### Python version

3.8

### Steps to Reproduce

1. Navigate to the dashboard screen with the new widgets.

### Expected Behavior

The text and icon colors within the card header should maintain at least the same contrast ratio between light and dark modes. You can see this done within the search and log in buttons in the screenshots below.

### Observed Behavior

Currently, the colors used for the text and icons for card headers in dark mode do not provide much contrast against the background, making them very difficult to see. Screenshots below for reference.

![beta-demo netbox dev_light](https://user-images.githubusercontent.com/24281183/231177958-95e85747-d315-48d9-9738-1c5b4acab55e.png)
![beta-demo netbox dev_dark](https://user-images.githubusercontent.com/24281183/231177957-b4edc302-60f1-4842-b931-8bea66a1a37c.png)

**Comment by mmfreitas** [comment]
For the lighter colors this happens:
![image](https://user-images.githubusercontent.com/91552302/231199538-638cbb65-e460-400d-9d2e-adffc470c730.png)

Could this be fixed the same way the #8088 was?

**Comment by jeremystretch** [comment]
I don't think we'll be able to use `foreground_color()` directly, because it takes a discrete RGB value, whereas in this case we're working with named colors (e.g. `blue` vs. `#0000ff`). But we should be able to come up with a similar approach.

**Comment by jsenecal** [comment]
Actually, just removing the class `bg-secondary` on the `card-header` div makes this much more readable and looks a bit more like the original ui:
![image](https://user-images.githubusercontent.com/1564902/234748366-6f06b9ab-3ba0-43b6-939f-ea93b106cded.png)

The _lighter_ version still needs it or at least the text and icons need a different class:
![image](https://user-images.githubusercontent.com/1564902/234748754-12aae83a-c6e7-48ec-926c-3dcb3c24014d.png)

Same with `text-dark` applied:
![image](https://user-images.githubusercontent.com/1564902/234749383-4ab10b40-4abe-499a-a351-b424e2dad421.png)

If the proposed solution is accepted I can take ownership of this.

**Comment by jsenecal** [comment]
It wouldn't change the ability to change colors, only change the default gray looking one @jeremystretch .

**Comment by heroin-moose** [comment]
Bump? Really an issue.

**Comment by heroin-moose** [comment]
This is really an issue, because even for the demo site we have either:

- Barely readable Default color in light mode
- Barely readable Gray color in dark mode
