### ISSUE TITLE
Add colors to Circuit Types model and use this when rendering cable traces

### ISSUE THREAD

**Issue by decoupca** [netbox-community/netbox#12216]
### NetBox version

v3.4.6

### Feature type

New functionality

### Proposed functionality

As described in [this discussion](https://github.com/netbox-community/netbox/discussions/12035), make it possible to identify the type of circuit that's involved in a cable trace by color-coding circuit types, and including the circuit type's name in the circuit's block in the diagram.

This would involve:
* Extending the circuit type model to include a color value (identical to how device roles are color-coded);
* Updating the cable trace view to reflect the circuit type's color and name.

This FR proposes no changes to cable traces that do not involve a circuit.

### Use case

Currently there is no way to identify the type of a circuit involved in a cable trace just by looking at the diagram. Color-coding and labeling circuit types adds convenience when looking at multiple cable traces, especially if the cable trace is exported or viewed by someone without access to NetBox, and hence can't resolve the circuit type by clicking on it, or looking it up.

### Database changes

Circuit types need a field for color value.

### External dependencies

None.

**Comment by decoupca** [comment]
If approved I can implement this.

**Comment by decoupca** [comment]
@jeremystretch Is there anything I can contribute to assist the review? This feature has come up a few times on my team. Thanks!

**Comment by jasonbothe-moodys** [comment]
@jeremystretch I would really really like to like some traction on this. Would it be possible to elevate it? Many thanks to @decoupca for the willingness to contribute in making this feature a reality.

**Comment by DanSheps** [comment]
Make sure you "thumbs up" the main issue, that is how we triage featurues

**Comment by jeremystretch** [comment]
@decoupca I assigned this to @arthanson before I noticed your comment above. Would you like to own this one?

**Comment by jasonbothe** [comment]
Thank you gents!
