### ISSUE TITLE
Add Support for Tenant Associations for Power Feeds/Panels

### ISSUE THREAD

**Issue by djmelik** [netbox-community/netbox#12210]
### NetBox version

v3.4.7

### Feature type

Data model extension

### Proposed functionality

I would like to request support for native tenant association for Power Feeds and Power Panels. Currently, I am having to rely on Custom Fields to achieve this functionality which seems more of a "hack" when given that *every* other Object ie. Circuits, Racks, Locations, Sites, Prefixes, ASNs, etc. within Netbox has native tenant association.

I think this change would further polish the Netbox DCIM/IPAM platform; by promoting greater consistency and standardization. Currently, it feels like the the Power objects are incomplete and not as polished as the rest.

It would also be nice to add Power Feeds under the stats section on the Tenant Page.

### Use case

It would allow users to natively associate and assign power feeds/panels to their respective tenants.

### Database changes

Unfortunately, I am not a developer and I do not know how to meaningfully answer this. Thank you for your consideration! 

### External dependencies

N/A

**Comment by jsenecal** [comment]
Quick questions:

Do you often have multiple different tenants per rack with their own dedicated Power?
How many different Power Panels of different tenancy do you intent to model ?

**Comment by djmelik** [comment]
Hi @jsenecal,

To your questions:

>Do you often have multiple different tenants per rack with their own dedicated Power?
We do not have multiple different tenants per rack with their own dedicated power. Power feeds are generally always provisioned to a single tenant, and in instances of shared racks and shared power, the rack and feed are assigned to *our* organization (we have a tenant objecting reflecting our organization for all internal resources).

>How many different Power Panels of different tenancy do you intent to model ?
I advised to also extend tenancy to power panels for consistency and standardization. That said, I did come to learn that we do have two entire power panels dedicated to two different organizations. For our Netbox instance, if this feature request is approved, most panels will be assigned to our organization; and the feeds themselves will be further organized into downstream tenants.

Please let me know if my answers are reasonable.

**Comment by jsenecal** [comment]
Would it then be better to just use existing information from related objects? I.e, if a power feed is "racked" then its table view and filter could use the tenant field from the rack itself.
I do not think it makes sense to duplicate this information.

**Comment by djmelik** [comment]
I was thinking this over; what about in situations where a power feed does not belong to a rack -- for instance, standalone power circuits within cages or offices. 

I think native tenancy or natively mapping tenants for all power objects is more extensible, offers greater scope and flexible, and is future proof for unaccounted use cases.

**Comment by jeremystretch** [comment]
I can see the use case for power feeds, but power panels seems odd. I'm not necessarily _opposed_ to it, I just find it difficult to envision a use case.

Going to mark this as `needs milestone` with the understanding that we'll at least add the assignment to power feeds.

**Comment by djmelik** [comment]
Thanks guys! Looks great :)
