### ISSUE TITLE
Allow Full Name to be set by remote authentication

### ISSUE THREAD

**Issue by heapdavid** [netbox-community/netbox#12226]
### NetBox version

v3.4.7

### Feature type

Change to existing functionality

### Proposed functionality

Add a variable `REMOTE_AUTH_FULL_NAME` or similar which would define a header that provides the user's full name. This would then update the Full Name field in the user's profile.

### Use case

Netbox displays the full name in various places since https://github.com/netbox-community/netbox/issues/8556 and https://github.com/netbox-community/netbox/issues/8894, so it would be good to be able to automatically populate that field.

### Database changes

n/a

### External dependencies

n/a

**Comment by stuntguy3000** [comment]
Happy to take this on board.
