### ISSUE TITLE
Order items inside a widget in the dashboard

### ISSUE THREAD

**Issue by mmfreitas** [netbox-community/netbox#12221]
### NetBox version

v3.5.0-dev

### Feature type

New functionality

### Proposed functionality

We would like to be able to order items inside a card widget on the new dashboard.

Could this be accomplished by using the same way that columns are organized in tables? Through the "configure table" button and use that same logic to reorder inside the widget.

Instead of having this field type inside the widget definition:
![image](https://user-images.githubusercontent.com/91552302/231214668-bdaa4feb-ec90-471b-a899-4babd2b07656.png)

Have this:
![image](https://user-images.githubusercontent.com/91552302/231212058-97d5efeb-9cd6-4803-9682-5f73c92876bc.png)

Instead of columns the objects on the list would be the models. This should also allow for multiple selection and quick organization in removing or adding items in certain widget.

Another way could be to drag and drop inside the widget (only needs to move up or down), the same way the widgets are draggable.
Not sure which is easier to implement at this stage or if any of these proposals are feasible...

### Use case

This would allow for more customization, instead of having it alphabetically ordered.

### Database changes

Not sure if any are required.

**Comment by jeremystretch** [comment]
> We would like to be able to order items inside a card widget on the new dashboard.

How? Please edit your post above to include more detail about the proposed change(s).
