### ISSUE TITLE
Update to Django 4.2 and psycopg3

### ISSUE THREAD

**Issue by arthanson** [netbox-community/netbox#12237]
### Proposed Changes

Django 4.2 has been released and it has support for the new psycopg3 (instead of the current psycopg2).

Also note: https://docs.djangoproject.com/en/4.2/releases/4.2/#index-together-option-is-deprecated-in-favor-of-indexes index-together is deprecated for indexes and we have this in a couple places in the code.

### Justification

From the Django release notes: "Support for psycopg2 is likely to be deprecated and removed at some point in the future.

Be aware that psycopg 3 introduces some breaking changes over psycopg2. As a consequence, you may need to make some changes to account for differences from psycopg2."

**Comment by jeremystretch** [comment]
It's worth calling out that Django 4.2 also [drops support for PostgreSQL 11](https://docs.djangoproject.com/en/4.2/releases/4.2/#dropped-support-for-postgresql-11).
