### ISSUE TITLE
"Invalid value for custom field: Value must be a string" when bulk updating

### ISSUE THREAD

**Issue by domainzero** [netbox-community/netbox#12235]
### NetBox version

v3.4.4

### Python version

3.9

### Steps to Reproduce
1. Create a device custom field with type `Integer` and any name.
2. Create two or more devices, filling in the new custom field with any integer.
3. Change the custom field created in step one to type `Text`.
4. Select the devices that were just created and edit, changing anything but the custom field.

### Expected Behavior

All items bulk update successfully.

### Observed Behavior

I receive the following error: `Invalid value for custom field 'field': Value must be a string`. This error does not occur if I edit a device individually.

**Comment by jeremystretch** [comment]
Thank you for opening a bug report. Unfortunately, the information you have provided is not sufficient for someone else to attempt to reproduce the reported behavior. Remember, each bug report must include detailed steps that someone else can follow on a clean, empty NetBox installation to reproduce the exact problem you're experiencing. These instructions should include the creation of any involved objects, any configuration changes, and complete accounting of the actions being taken. Also be sure that your report does not reference data on the public NetBox demo, as that is subject to change at any time by an outside party and cannot be relied upon for bug reports.

**Comment by domainzero** [comment]
Thanks Jeremy. I have updated the initial bug report.

**Comment by arthanson** [comment]
@domainzero this was fixed with "[#11431](https://github.com/netbox-community/netbox/issues/11431) - Disallow changing custom field type after creation" in NetBox v3.4.8. Changing the type of the custom field is not allowed after creation.
