### ISSUE TITLE
"Allowed IPs" for APIs not enterable

### ISSUE THREAD

**Issue by gdprdatasubect** [netbox-community/netbox#12238]
### NetBox version

v3.4.8

### Python version

3.8

### Steps to Reproduce

Reproducable in demo.netbox.dev

1. Navigate to HOSTNAME/user/api-tokens/add/
2. Enter any IP-Address  e.g. "127.0.0.1/24"
3. Click on "Create"
4. Receive Error-Message "Item 1 in the array did not validate:"

### Expected Behavior

Creation of new API-Key and honoring of IP-based access-restrictions

### Observed Behavior

API-Key is not created

**Comment by kkthxbye-code** [comment]
While the error message is not great, it is supposed to deny it as it is an invalid IPv4Network. Try with 127.0.0.0/24.

**Comment by jeremystretch** [comment]
I'll fix the error message but @kkthxbye-code is correct.
