### ISSUE TITLE
Move the related IPs list under the IP address view to a separate tab

### ISSUE THREAD

**Issue by ThomasADavis** [netbox-community/netbox#12233]
### NetBox version

v3.5-beta1

### Feature type

Change to existing functionality

### Proposed functionality

When you view the IP address page, there is table of related IP addresses.  An example page is at https://demo.netbox.dev/ipam/ip-addresses/181/

This table really isn't related to the IP addresses, it's more of a query of the db, and gets the first X number of ip addresses from the subnet IP address is located in, where X is current default paging value.  In the demo, this is 100.

The listed IP's are not the IP's from the before/after the current viewed IP address.  The list starts at the beginning of the subnet.

The listed IP's are not paged, they are simply truncated to the default paging value.
If you pick a large default paging value, this can be 50 or more values.  If your viewing a large subnet, with many IP's defined, you can have a very large table generated.

Replacing the related table with a direct link to the subnet IP addresses tab is better than looking at a related table that is either incomplete or not truly related.

I also remember the devices page also had a related table and was removed for some reason (looking for the issue related to this)

I've attached a set of screen shots that shows this, along with how the values presented are not truly related other than by subnet.

![Screenshot_2023-04-12_10-53-26](https://user-images.githubusercontent.com/12158973/231543062-3a2c8651-7d30-4a28-bf53-60dc30144e47.png)
![Screenshot_2023-04-12_10-52-43](https://user-images.githubusercontent.com/12158973/231543070-ab59ccd3-724f-4730-ae4f-c0ad16993777.png)

### Use case

Removing this table would speed up the page load and remove a possible large db query.  

It would also reduce the amount of scrolling need to view the full contents of the page.

### Database changes

None.

### External dependencies

None

**Comment by DanSheps** [comment]
Maybe instead of removing it, perhaps moving it to another tab would be a better way to go.

**Comment by ThomasADavis** [comment]
Found the feature request for the device related object..  

https://github.com/netbox-community/netbox/issues/8083

**Comment by abhi1693** [comment]
Moving it to a tab is probably better because in my setup related IPs are really helpful due to the way our infrastructure is implemented.

**Comment by jsenecal** [comment]
I also vote for putting this in another view in a dedicated tab.
