### ISSUE TITLE
Footer doesn't reflect update from 3.4.7 -> 3.4.8?

### ISSUE THREAD

**Issue by DonMusto** [netbox-community/netbox#12247]
### NetBox version

v3.4.8

### Python version

3.10

### Steps to Reproduce

Upgrade standard implementation of NetBox from 3.4.7 to 3.4.8

### Expected Behavior

Footer should read `DATETIME HOSTNAME (v3.4.8)`

### Observed Behavior

Footer reads `DATETIME HOSTNAME (v3.4.7)`

**Comment by abhi1693** [comment]
This works for me

![image](https://user-images.githubusercontent.com/5083532/231869606-b4f9aa99-bd57-4a63-9881-43b6b51b88b6.png)

**Comment by jeremystretch** [comment]
I've confirmed that the version is defined correctly in the release. You likely still need to restart your NetBox services.
