### ISSUE TITLE
Can't bulk import cables

### ISSUE THREAD

**Issue by itijoux** [netbox-community/netbox#12243]
### NetBox version

v3.4.1

### Python version

3.10

### Steps to Reproduce
1-Start with an empty Netbox instance. 
2-Create a device type with interfaces ( interface exemple :  .1/2/C1 ,1/2/C2 .... ,1/2/C18)
4-Create Site A and Site B.
3-Instance 2 devices , one in each site , DeviceA in Site A and DeviceB in Site B .  
4- Go to cables
3- Click import
4- Try to import this :

side_a_device,side_a_type,side_a_name,side_b_device,side_b_type,Interface
DeviceA,dcim.interface,1/2/C2,DeviceB,dcim.interface,1/2/C2

### Expected Behavior

creations of the cable 

### Observed Behavior

Debug mode is active and it shows this : 
The Traceback

Environment:

Request Method: POST
Request URL: https://10.10.0.10/dcim/cables/import/

Django Version: 4.1.4
Python Version: 3.10.6
Installed Applications:
['django.contrib.admin',
'django.contrib.auth',
'django.contrib.contenttypes',
'django.contrib.sessions',
'django.contrib.messages',
'django.contrib.staticfiles',
'django.contrib.humanize',
'corsheaders',
'debug_toolbar',
'graphiql_debug_toolbar',
'django_filters',
'django_tables2',
'django_prometheus',
'graphene_django',
'mptt',
'rest_framework',
'social_django',
'taggit',
'timezone_field',
'circuits',
'dcim',
'ipam',
'extras',
'tenancy',
'users',
'utilities',
'virtualization',
'wireless',
'django_rq',
'drf_yasg',
'django3_saml2_nbplugin.Django3AuthSAML2Plugin',
'netbox_metrics_ext.MetricsExtConfig',
'netbox_topology_views.TopologyViewsConfig',
'netbox_prometheus_sd.PrometheusSD']
Installed Middleware:
['graphiql_debug_toolbar.middleware.DebugToolbarMiddleware',
'django_prometheus.middleware.PrometheusBeforeMiddleware',
'corsheaders.middleware.CorsMiddleware',
'django.contrib.sessions.middleware.SessionMiddleware',
'django.middleware.locale.LocaleMiddleware',
'django.middleware.common.CommonMiddleware',
'django.middleware.csrf.CsrfViewMiddleware',
'django.contrib.auth.middleware.AuthenticationMiddleware',
'django.contrib.messages.middleware.MessageMiddleware',
'django.middleware.clickjacking.XFrameOptionsMiddleware',
'django.middleware.security.SecurityMiddleware',
'netbox.middleware.ExceptionHandlingMiddleware',
'netbox.middleware.RemoteUserMiddleware',
'netbox.middleware.LoginRequiredMiddleware',
'netbox.middleware.DynamicConfigMiddleware',
'netbox.middleware.APIVersionMiddleware',
'netbox.middleware.ObjectChangeMiddleware',
'django_prometheus.middleware.PrometheusAfterMiddleware']

Traceback (most recent call last):
File "/opt/netbox/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
response = get_response(request)
File "/opt/netbox/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "/opt/netbox/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 103, in view
return self.dispatch(request, *args, **kwargs)
File "/opt/netbox/netbox/netbox/views/generic/base.py", line 77, in dispatch
return super().dispatch(request, *args, **kwargs)
File "/opt/netbox/netbox/utilities/views.py", line 99, in dispatch
return super().dispatch(request, *args, **kwargs)
File "/opt/netbox/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 142, in dispatch
return handler(request, *args, **kwargs)
File "/opt/netbox/netbox/netbox/views/generic/bulk_views.py", line 442, in post
new_objs = self.create_and_update_objects(form, request)
File "/opt/netbox/netbox/netbox/views/generic/bulk_views.py", line 400, in create_and_update_objects
if model_form.is_valid():
File "/opt/netbox/netbox/utilities/forms/forms.py", line 69, in is_valid
is_valid = super().is_valid()
File "/opt/netbox/venv/lib/python3.10/site-packages/django/forms/forms.py", line 205, in is_valid
return self.is_bound and not self.errors
File "/opt/netbox/venv/lib/python3.10/site-packages/django/forms/forms.py", line 200, in errors
self.full_clean()
File "/opt/netbox/venv/lib/python3.10/site-packages/django/forms/forms.py", line 439, in full_clean
self._post_clean()
File "/opt/netbox/venv/lib/python3.10/site-packages/django/forms/models.py", line 492, in _post_clean
self.instance.full_clean(exclude=exclude, validate_unique=False)
File "/opt/netbox/venv/lib/python3.10/site-packages/django/db/models/base.py", line 1452, in full_clean
self.clean()
File "/opt/netbox/netbox/dcim/models/cables.py", line 148, in clean
if self.pk is None and (not self.a_terminations or not self.b_terminations):
File "/opt/netbox/netbox/dcim/models/cables.py", line 117, in a_terminations
ct.termination for ct in self.terminations.all() if ct.cable_end == CableEndChoices.SIDE_A
File "/opt/netbox/venv/lib/python3.10/site-packages/django/db/models/manager.py", line 164, in all
return self.get_queryset()
File "/opt/netbox/venv/lib/python3.10/site-packages/django/db/models/fields/related_descriptors.py", line 689, in get_queryset
raise ValueError(

Exception Type: ValueError at /dcim/cables/import/
Exception Value: 'Cable' instance needs to have a primary key value before this relationship can be used.

**Comment by jeremystretch** [comment]
Thank you for opening a bug report. Unfortunately, the information you have provided is not sufficient for someone else to attempt to reproduce the reported behavior. Remember, each bug report must include detailed steps that someone else can follow on a clean, empty NetBox installation to reproduce the exact problem you're experiencing. These instructions should include the creation of any involved objects, any configuration changes, and complete accounting of the actions being taken. Also be sure that your report does not reference data on the public NetBox demo, as that is subject to change at any time by an outside party and cannot be relied upon for bug reports.

**Comment by jsenecal** [comment]
Hi @itijoux, 

You need to edit the "Steps to Reproduce" section of your original message to reproduce your issue **with an empty netbox installation** the steps you provided only work if you have the devices and interfaces/ports already which is not easy to reproduce. 

As mentionned by Jeremy, each bug report must include detailed steps that someone else can follow on a clean, empty NetBox installation to reproduce the exact problem you're experiencing. **These instructions should include the creation of any involved objects, any configuration changes, and complete accounting of the actions being taken.**

Failure to provide this information will result in the closure of the issue.

**Comment by itijoux** [comment]
Hi @jsenecal  , thanks for the reply  ! i have modified my initial report with more dertails , I hope this is enough to reproduce the issue .

**Comment by itijoux** [comment]
Sorry for Wasting your time ! the error came from me ! thanks any way for the feedback .
