### ISSUE TITLE
Inventory item cannot be reassgined to another device

### ISSUE THREAD

**Issue by ntopee** [netbox-community/netbox#12255]
### NetBox version

v3.4.8

### Python version

3.8

### Steps to Reproduce

1. Click on Edit on any inventory item in the UI
2. Edit Device field
3. Click save

### Expected Behavior

The inventory item should be assigned to the selected device.

### Observed Behavior

"Components cannot be moved to a different device." validation error is shown
This validation is introduced in #11567 , but I don't think the change that even inventory items cannot be reassigned to another device via the UI was intended.

**Comment by kkthxbye-code** [comment]
> but I don't think the change that even inventory items cannot be reassigned to another device via the UI was intended.

Correct, it was specified in both the original issue and a comment to the PR, that it was to only apply to InterfaceComponents other than InterfaceItem. Not sure what went wrong here.

@arthanson
