### ISSUE TITLE
Highlight only custom fields that have changed in change log

### ISSUE THREAD

**Issue by decoupca** [netbox-community/netbox#12273]
### NetBox version

v3.4.8

### Feature type

Change to existing functionality

### Proposed functionality

Currently, changes to any custom field highlights all custom fields in the diff. This makes drilling down exactly what changed difficult, especially for objects with many custom fields. I propose to modify behavior so only changed custom fields are highlighted.

### Use case

- For objects with many custom fields, the current diff and highlight behavior makes it hard to see at a glance which custom field (or fields) have changed. Highlighting only those that have changed will make this easier, and is more semantic—it's counter-intuitive to highlight any item in a diff that hasn't actually changed.

**Comment by jeremystretch** [comment]
Thank you for submitting this issue, however it appears that this topic has already been raised. Please see issue #10924 for further discussion.
