### ISSUE TITLE
Add Total Weight/Dimensions to Device view

### ISSUE THREAD

**Issue by sleepinggenius2** [netbox-community/netbox#12286]
### NetBox version

v3.4.8

### Feature type

New functionality

### Proposed functionality

When #9654 was completed, the `total_weight` property was added to the `Device` and `Rack` models, but only the `Rack` model current displays it in the UI. I propose adding this to the view for a `Device` as well. Ideally, this would be in a separate *Dimensions* card, like under the `Rack` view, that could also include the Height from the device type, as well as width and depth values, if those are ever added.

### Use case

The `total_weight` field can already be accessed programmatically, so it makes sense to include it in the UI for visibility and there is already precedent for the `Rack` model.

### Database changes

None

### External dependencies

None

**Comment by sleepinggenius2** [comment]
The merged PR for this is not correct and is only taking the weight from the device type, not the `total_weight` field from the device, which includes populated modules.

**Comment by abhi1693** [comment]
I'll raise another PR to include the modules as well. Since it was not called out in the original request, it got missed.
