### ISSUE TITLE
Implement modular power port

### ISSUE THREAD

**Issue by benwa** [netbox-community/netbox#12303]
### NetBox version

V3.4.8

### Feature type

Data model extension

### Proposed functionality

Make power ports have the ability to have multiple connector types.

### Use case

Data center PDUs are now being sold with 4-in-1 ports that cover C13/C15/C19/C21 in one form factor. I can certainly see this as a standard onto itself, it a mix and match situation.

**Comment by DanSheps** [comment]
Can you give us an example of the PDU?

**Comment by benwa** [comment]
Absolutely, APC's NetShelter Rack PDU Advanced line has them, for example, the [APDU10450ME](https://www.apc.com/us/en/product/APDU10450ME/apc-netshelter-rack-pdu-advanced-metered-3ph-43-5kw-400v-63a-or-34-6kw-415v-60a-42-outlets-iec309/)
![image](https://user-images.githubusercontent.com/1351571/233444192-c0ad50aa-b3a5-4b26-90cb-ebcef17977b2.png)

**Comment by ThomasADavis** [comment]
https://www.servertech.com/solutions/flexibility-hdotcx/ is another dual use socket.

**Comment by jeremystretch** [comment]
This is the "HDOT Cx" outlet type, which is already available in NetBox as a choice under the "proprietary" heading.

**Comment by benwa** [comment]
@jeremystretch the HDOT Cx is not the plug type from the OP.

**Comment by jeremystretch** [comment]
@benwa please provide a link to the outlet's formal spec.

**Comment by benwa** [comment]
I did some sleuthing, but it doesn't look like APC publishes that. The best I could find is for a PDU that has both C13/C15 and C13/C15/C19/C21 ports.  
https://www.se.com/ww/en/product/download-pdf/APDU10351SW

**Comment by jeremystretch** [comment]
Understood. Unfortunately, we can't add a type that hasn't been assigned a canonical name.

**Comment by jeremystretch** [comment]
No; this is still a single discrete type of outlet. It just happens to be compatible with multiple types of ports.

**Comment by benwa** [comment]
Understood. From an operations point of view, what would be your suggestion for modeling this?

**Comment by jeremystretch** [comment]
Use the "other" type.
