### ISSUE TITLE
Remove the Django admin UI

### ISSUE THREAD

**Issue by jeremystretch** [netbox-community/netbox#12325]
### Proposed Changes

Disable the Django admin UI entirely. The few functions it still performs currently will be migrated to dedicated views within the primary UI.

### Justification

All aspects of NetBox should be accessible via its primary user interface. Disabling the standalone Django admin UI will allow us to deliver a single, cohesive interface, while eliminating dependencies on `django.contrib.admin`.

### Impact

The following admin views will be migrated to the primary UI (some have already been moved):

- ~Users~
- ~Groups~
- ~Config revisions~
- ~Permissions~
- ~Tokens~
- Background tasks
- Installed plugins

The following admin views will be removed entirely:

- Views registered by `python-social-auth`
- Any _admin_ views registered by plugins

**Comment by stavr666** [comment]
> deliver a single, cohesive interface

Speaking of it. There is some rework with constrains needed, so API and saved filters paths will have same naming rules, as new Admin panel.

For example:
IP address have ?tenant_id= and ?tenant= filters, but "tenant_id"= and "tenant__slug"= in admin panel.

**Comment by kkthxbye-code** [comment]
@stavr666 - Please create a seperate issue. Also do note that you are comparing filterset filters with queryset filters, which are not the same. This is not going to change. If you are missing a filterset filter, a FR is the right way to request it.

**Comment by abhi1693** [comment]
It's not a concern but https://github.com/Onemind-Services-LLC/netbox-secrets/ will need to redesign the UIs to allow for this change. Currently, an admin activates the user key from the admin panel and this list of keys is also only visible on the admin side as the `UserKey` model does not inherit most of the common functionality of NetBox. Atleast for this plugin, apart from moving the UI to tabler it'll basically be a complete UI overhaul along with the core

**Comment by peteeckel** [comment]
No problem here - admin functionality was removed from `netbox-plugin-dns ` a while ago.

**Comment by jeremystretch** [comment]
After further discussion, we've decided to stop short of completely eliminating support for the Django admin UI. Instead, we'll disable it by default and provide a configuration parameter to enable it, to support any plugins which still require it.

The admin UI will likely be fully removed in a future release.
