### ISSUE TITLE
Remove the `napalm_driver` and `napalm_args` fields from Platform

### ISSUE THREAD

**Issue by jeremystretch** [netbox-community/netbox#12320]
### Proposed Changes

Remove the `napalm_driver` and `napalm_args` fields from the Platform model.

### Justification

NAPALM integration was moved to a [plugin](https://github.com/netbox-community/netbox-napalm) in NetBox v3.5 under #10520. These fields were retained to ease migration to the plugin, but are no longer needed once the plugin has been installed.

**Comment by PieterL75** [comment]
@jeremystretch Can we keep the 'driver' field ? 
My automation uses napalm, and gets the driver from the Platform assigned to the Device.
Maybe just rename it to 'DeviceDriver' in stead of NapalmDriver ?
Other option is to use CustomFields, but it feels like a proper field to retain on the Platform model
