### ISSUE TITLE
Changing Device type - allowing type template to populate existing device

### ISSUE THREAD

**Issue by andyb2000** [netbox-community/netbox#12348]
### NetBox version

v3.4.6

### Feature type

Change to existing functionality

### Proposed functionality

Initially most people will populate devices with a list of existing hardware, from import, script, etc. In my case this list does not contain the device type, so I use a catch-all "Unknown".
Later, devices are updated (in my case via script from netdoc) to use the correct Device Type (Mainly from the https://github.com/netbox-community/devicetype-library library).
This does not then pull in associated modules, power, U size, etc, from Device Types (I assume because this could overwrite the defined values already in the device).

My request is an option to FORCE overwrite of device parameters based on a changed device type, i.e. to import the template/type regardless of overwriting fields.

### Use case

This would allow devices that were created using a bulk import/script to later be updated with the correct device type and inherit the defined device type values such as interfaces, console ports, power, modules, etc.

**Comment by kkthxbye-code** [comment]
For reference, this is what the FAQ states:

https://github.com/netbox-community/netbox/wiki/Frequently-Asked-Questions#why-arent-device-type-component-modifications-retroactive

We just use a script similar to this one:

https://github.com/netbox-community/customizations/blob/master/scripts/add_device_type_components.py

I don't have any strong feelings about supporting this in core, personally I might lean on the side of it not being necessary. I'll leave it open to feedback.

**Comment by 2code4me** [comment]
Hi, I have a similar issue.
At the moment I need to fast compile an inventory of a data center. As you can imagine I have tons of device type to create so at the moment I've created some "Generic 1RU, Generic 2RU" and so on device type. 
This is to quickly have an inventory ready for consultation with the idea of adding details in the near future.

I then tried to change the device type using some that I had already created (for example a Dell Server) but I see that details like PSU, interfaces and so on are not compiled so I have to delete and recreate the object every time.

It would be a lot time saving if, when you change the device type, the object could update automatically the device details.

Even in the case of errors in the selection of the device type, you could update the data without the need to delete and recreate the object each time.

Thank you
