### ISSUE TITLE
Populate UI default fields for a device type when creating a new device

### ISSUE THREAD

**Issue by ryanmerolle** [netbox-community/netbox#12342]
### NetBox version

v3.5

### Feature type

Change to existing functionality

### Proposed functionality

Right now if fields like platform and airflow can be set as a default for a devicetype, but if you go to create a device of a devicetype with the default fields it will not show in the UI.

### Use case

- Allow users to see that a default field will be applied to a device.
- Allows users to remove the field value if they would like to unset it.

**Comment by jeremystretch** [comment]
Just to clarify: If I create a device type with a default platform and airflow, and then create a device using that device type, the new device's platform and airflow fields are populated with the values specified by the device type. This much is expected.

Is the intent to update the device creation form in the UI immediately upon selecting a device type, prior to actually creating the device? That might be feasible by leveraging HTMX to re-render the form upon selecting the device type.

**Comment by ryanmerolle** [comment]
Yes it is just a confusing UI experience.

- User does not set a platform for a device, and unknowingly a default platform is associated to a device.  Maybe they are not intending to apply a platform because they are deciding on a new OS for whitebox devices, and they just want it blank for now.
- User does the same sort of input as above but clicks Create & Add Another which then populates the platform even though they did not do that with the first device.
