### ISSUE TITLE
Add ability to hide URL in custom field but show appearance in Custom links

### ISSUE THREAD

**Issue by deku-m** [netbox-community/netbox#12346]
### NetBox version

v3.4.7

### Feature type

Change to existing functionality

### Proposed functionality

When using the combination of custom field and custom links to show something as a top button. 
These custom field can be hidden from the UI. 
But then it is not possible anymore to fill in the information on the editting page and reuse it to create a custom link for a button on the top without showing the custom field.

Suggestion is to hide from overview (as a hidden custom field) and have possibility to fill in the information when editted the page.
Showing up on top as a button. This also saves some space on the general overview page where you provide the custom field.

### Use case

Just hiding the information that might be implemented once and dont show the link twice in the overview.
Custom field and as custom links button.

### Database changes

Dont know

### External dependencies

Dont know

**Comment by jeremystretch** [comment]
Thank you for your interest in extending NetBox. Unfortunately, the information you have provided does not constitute an actionable feature request. Per our [contributing guide](https://github.com/netbox-community/netbox/blob/develop/CONTRIBUTING.md), a feature request must include a thorough description of the proposed functionality, including any database changes, new views or API endpoints, and so on. It must also include a detailed use case justifying its implementation. If you would like to elaborate on your proposal, please modify your post above. If sufficient detail is not added, this issue will be closed.

**Comment by deku-m** [comment]
As with the combination of custom fields and customlinks you can create a button to forward to a website of your choice as seen in the 2 screenshots created for example cisco site.
**Custom field:**
![afbeelding](https://user-images.githubusercontent.com/37069737/236743593-08498aba-b4d9-46e3-9237-6652e5a62f38.png)
**Custom links:**
![afbeelding](https://user-images.githubusercontent.com/37069737/236744357-70114451-fda6-4c33-a38f-813d320d6088.png)

**Overview:**
![afbeelding](https://user-images.githubusercontent.com/37069737/236744622-80ec5253-ea43-410c-81b6-ef6e6d132205.png)
You see the button and the create links which are connected.

I was wondering with this request if you can add the ability to hide it on the overview only in the customfield but still can edit it on the edit page and show it as button only in the right top corner.

Because when setting the UI visibility is set to hidden:
![afbeelding](https://user-images.githubusercontent.com/37069737/236745007-b87e9b17-0ad6-47c8-ab43-8c014020676a.png)
You are not able to change it anymore afterwards until je unhide and hide it again.
So i was asking if the hidden function perhaps could have a 4th option or something to have the hidden function only on the overview but not on the editting page? So it is still possible to change the URL in editting mode and not being showed on the customfield part in the overview.

**Comment by deku-m** [comment]
Is this not under review by netbox crew? Before closure?
