### ISSUE TITLE
Validate device config

### ISSUE THREAD

**Issue by RenatoPereira91** [netbox-community/netbox#12353]
### NetBox version

v3.4.8

### Feature type

New functionality

### Proposed functionality

Hi teams,

Anyome function that possibility that validate config of the devices to compliance, the netbox had one plugin netbox-plugin-config-officer but dont work today.

My ideia is deploy the plugin with one funcion inside netbox the that plugin netbox-plugin-config-officer offered.

### Use case

The Benefit for compliance of the devices inside Netbox, one good form for documentation and maintain.

**Comment by jeremystretch** [comment]
This isn't something we'd able to take on in NetBox core, but as you mention would make for an excellent plugin. Hopefully we can find an interested party to take it on.

**Comment by RenatoPereira91** [comment]
Hi @jeremystretch 

I think this plugin is very good and have one ideia very good.

It have 2 years without update.

The nautobot have same ideia, but with good dashboard the name Nautobot Golden Config
