### ISSUE TITLE
New paragraph line breaks do not render in journal entry table comments

### ISSUE THREAD

**Issue by mattspera** [netbox-community/netbox#12363]
### NetBox version

v3.3.7

### Python version

3.8

### Steps to Reproduce

1. Click on **Devices** in the side menu and then select **Devices** from the Devices submenu
2. Click on a Device object and select the **Journal** tab
3. Create a new journal entry and enter the following in the comments section:

![image](https://user-images.githubusercontent.com/10584226/234857345-c35a767c-7ac6-45cc-9561-136015ff3b37.png)

### Expected Behavior

The journal entry comments attribute within the device object's journal entry table should render a line break between the two paragraphs.

This behaviour is correctly demonstrated when clicking into the Journal Entry object and observing the **Comments** attribute:
![image](https://user-images.githubusercontent.com/10584226/234858565-ba7a7460-6a8b-4ae0-a15c-96ecf66e286e.png)

### Observed Behavior

The journal entry comments attribute within the device object's journal entry table does not render a line break between the two paragraphs:
![image](https://user-images.githubusercontent.com/10584226/234856787-8c8d63f1-10d7-4106-b02b-7d7ea9eee451.png)

Prior to the user interface updates in v3, the journal entry comments attribute within the device object's journal entry table would correctly render new paragraph line breaks.

**Comment by jeremystretch** [comment]
The underlying rendering is functioning correctly, however we have CSS in place that removes the bottom margin from `<p>` elements within a table.
