### ISSUE TITLE
Extend Backplane communication options to FC switches and cards

### ISSUE THREAD

**Issue by stavr666** [netbox-community/netbox#12362]
### NetBox version

v3.4.3

### Feature type

Change to existing functionality

### Proposed functionality

Addition to this FR: https://github.com/netbox-community/netbox/issues/10356

Add ability to document backplane connections for Fiber Channel in blade systems.

### Use case

In out case, we have HPE C7000 and HPE C12000 blade frames.
First one have HPE B-series 8/24c AJ821B onboard (8 external SFP+, 16 internal backplane-mapped ports), second one - HPE Brocade 16Gb/12 FC Switch Module K2Q83A (24 external SFP+, 12 internal backplane-mapped ports).

Right now, we have no way to distinguish external ports from backplane "virtual" ports, except naming scheme or putting something to description.
But we'd like to have more consistent way to filter external connections for reports, monitoring (and provisioning at some point).

**Comment by jeremystretch** [comment]
What are the specific changes you are proposing?

**Comment by stavr666** [comment]
> What are the specific changes you are proposing?

1. Add new interface type group "FibreChannel (backplace)"
2. Duplicate list of FC types with bonus label "internal" to clearly (filtrable) indicate, that ports not have external optical cable connections.

Last part arguable must have declared standard types, but I didn't find any clues about industry-level standard for things like this:

![image](https://github.com/netbox-community/netbox/assets/84839985/aa81f64f-7d40-4939-a716-29bf17270899)
