### ISSUE TITLE
Separate field for postal code

### ISSUE THREAD

**Issue by candlerb** [netbox-community/netbox#12399]
### NetBox version

v3.4.10

### Feature type

Data model extension

### Proposed functionality

Although in general I approve of simple, unstructured data for physical address and shipping address, it would be very helpful to have a separate field for "Postal code".

### Use case

I need to be able to view, sort and filter on postal codes, and for cross-referencing to other data sources.

Right now I have created a custom field on Site for postal code, and this works fine.  There's only one problem: I have removed the postal code from physical address to avoid data duplication, but now the "Map" link button doesn't have that information available to it, making the map lookups less accurate.

Ideally, the Map button would combine physical address and postal code for sending to Google Maps. To do that, it needs the postal code in an official model field (or for the physical address map button to be a user-defined template).

### Database changes

Separate field in Site for postal code.

----
Aside: I observe that different countries have different postal code schemes, so in principle you'd need the tuple of (country, postal code) to identify a geographical area. However, the country information is likely to exist already in the Region hierarchy; and for the benefit of Google Maps, you can still include the country within the physical address field.

### External dependencies

None

**Comment by candlerb** [comment]
Workaround: add a custom link

```
# Link text
{% if object.physical_address or object.cf.postcode %}
Map
{% endif %}

# Link URL
https://maps.google.com?q={{ object.physical_address }} {{object.cf.postcode}}
```

However, I don't see a way to disable the existing "Map" button which sits over the physical_address field.

That could be done with a small patch to templates/dcim/site.html:

```
              {% if object.physical_address %}
```

becomes

```
              {% if object.physical_address and config.MAPS_URL %}
```

**Comment by jeremystretch** [comment]
This was discussed under #9617, however no progress was made due to the lack of a well-defined international standard detailing what the supported address fields should be. IMO it doesn't make sense to add a discrete field just for postal code, which we wouldn't even be able to validate.
