### ISSUE TITLE
Circuit Provider Account field required API not in GUI

### ISSUE THREAD

**Issue by arjenvri** [netbox-community/netbox#12396]
### NetBox version

v3.5.0

### Python version

3.8

### Steps to Reproduce

1. Use the REST API to create a new circuit
`
{
    "cid": "12345",
    "provider": 1,
    "type": 1,
}
`
Error: {"provider_account":["This field is required."]}
2. Use the GUI to add circuit, `provider_account` is an optional field
3. Try to add circuit with provider_account set as 0
`
{
    "cid": "12345",
    "provider": 1,
    "type": 1,
    "provider_account": 0
}
`
Error: {"provider_account":["Related object not found using the provided numeric ID: 0"]}
4. Read existing migrated circuit from netbox
` ...."provider_account":null ...
` 

### Expected Behavior

The circuit `provider_account` field should be optional in the RESTAPI as it current is in the GUI.

### Observed Behavior

Error was shown requiring the provider_account field to be defined

**Comment by zeddD1abl0** [comment]
If you leave the provider_account out of the request entirely does it break? Because if it's not there, it should be null. But if you provide a value, that value needs to exist.

I.E. :
`{ "cid": "12345", "provider": 1, "type": 1 }`

**Comment by arjenvri** [comment]
Without provider_account it breaks indeed. See above step 1
