### ISSUE TITLE
"Create & Add Another" action is broken

### ISSUE THREAD

**Issue by duckw** [netbox-community/netbox#12395]
### NetBox version

v3.5.0

### Python version

3.8

### Steps to Reproduce

1. Create a custom field to apply to the device or site object.  Issue observed when there is a custom text field added (no special configuration is needed).
2. Create a new device or site but click on the "Create & Add Another" button.
Note: I have only tested with devices and sites but the behaviour appears the same for both.  The issue does not happen when the custom field is not present.

### Expected Behavior

Object is created and returns to the filled out create page.

### Observed Behavior

Object gets created but returns:
```
<class 'AttributeError'>

'str' object has no attribute 'is_cloneable'

Python version: 3.8.10
NetBox version: 3.5.0
```

**Comment by kkthxbye-code** [comment]
Thank you for your bug report, however I was not able to reproduce it. Please double check to make sure the replication steps are accurate.

**Comment by duckw** [comment]
Re-tested on the demo instance (again) and couldn't reproduce it this time.

After adding a new (text) custom field for DCIM/Site and re-testing, the issue can be reproduced.

Seems to be something to do with the presence of custom fields that stops this function from working.

**Comment by kkthxbye-code** [comment]
Thanks, please update the issue to include all replication steps.

It seems like something is overwriting the model instance `custom_fields` field. Normally `custom_fields` is a `QuerySet` of `CustomFields`, however when the following code is executed:

```
  File "/home/xxx/devel/netbox-development/netbox/netbox/views/generic/object_views.py", line 282, in post
    params = prepare_cloned_fields(obj)
  File "/home/xxx/devel/netbox-development/netbox/utilities/utils.py", line 350, in prepare_cloned_fields
    attrs = instance.clone()
  File "/home/xxx/devel/netbox-development/netbox/netbox/models/features.py", line 134, in clone
    if field.is_cloneable:
```

`obj.custom_fields` returns:

```
obj.custom_fields
{'testf': None}
```

Before the form is saved, it looks correct:

```
obj.custom_fields
<RestrictedQuerySet [<CustomField: Testf>]>
````

So it's probably something in the form that overwrites the field with a dict.
