### ISSUE TITLE
Custom links documentation not fully updated for `obj` removal

### ISSUE THREAD

**Issue by jzinkweg** [netbox-community/netbox#12422]
### Change Type

Correction

### Area

Customization

### Proposed Changes

#8684 missed some references to ```obj```, so the documentation is now outdated (it should refer to ```object```).

I'd like to submit a pull request to correct this.
https://github.com/jzinkweg/netbox/commit/6c9c8ac71cba17d6df16654db5825f09f52cb2ec

**Comment by jeremystretch** [comment]
Thanks for catching this!
