### ISSUE TITLE
'str' object has no attribute 'is_cloneable' on Device "Create and Add Another"

### ISSUE THREAD

**Issue by FenixVale** [netbox-community/netbox#12438]
### NetBox version

v3.5.0

### Python version

3.10

### Steps to Reproduce

1. Click create a device
2. Populate the information for the device
3. Click "Create & Add Another"

### Expected Behavior

A new page should load with much of the information pre-populated to continue created new devices

### Observed Behavior

The error would appear instead.

<class 'AttributeError'>

'str' object has no attribute 'is_cloneable'

%Versions
![Screenshot 2023-05-02 144948](https://user-images.githubusercontent.com/33432475/235760460-e64dd133-0391-4316-856d-cf8972d72f86.png)

**Comment by FenixVale** [comment]
Additional note, the issue appears to be very similar to [Issue 12395](https://github.com/netbox-community/netbox/issues/12395), however I do not have any custom fields.

**Comment by FenixVale** [comment]
> I'm afraid the reproduction steps you've provided aren't sufficient to reproduce the issue. I'd be very surprised if it's not resolved by the fix for #12395 however.

Would this fix already have been implemented in the latest release, or will I have to do so manually / wait until next release? I executed my update this morning which was when the bug arose

**Comment by jeremystretch** [comment]
The fix has been merged into the `develop` branch and will ship with the upcoming v3.5.1 release, expected in the next day or two.

**Comment by jeremystretch** [comment]
Closing this out as it does not appear reproducible on the current stable release, and v3.5.1 has been released. Happy to re-open if suitable reproduction steps can be identified.
