### ISSUE TITLE
Documentation does not list ALTER ROLE netbox CREATEDB requirement to execute unittests

### ISSUE THREAD

**Issue by dhenschen** [netbox-community/netbox#12444]
### Change Type

Addition

### Area

Development

### Proposed Changes

I followed through the Development documentation and did not find much information on how to run the tests. I executed the following commands under `sudo -u postgres psql` based on the [PostgreSQL Database Installation](https://docs.netbox.dev/en/stable/installation/1-postgresql/) documentation and the configuration_testing.py file. I'm running Ubuntu 22.04.

```
CREATE DATABASE netbox;
CREATE USER netbox WITH PASSWORD 'netbox';
ALTER DATABASE netbox OWNER TO netbox;
```

After creating the database, I tried to run the tests and encountered the following error:

```
(venv) dohenschen@desktop:~/Documents/netbox/netbox/netbox$ export NETBOX_CONFIGURATION=netbox.configuration_testing
(venv) dohenschen@desktop:~/Documents/netbox/netbox/netbox$ cd ..
(venv) dohenschen@desktop:~/Documents/netbox/netbox$ python manage.py test
Found 5774 test(s).
Creating test database for alias 'default'...
Got an error creating the test database: permission denied to create database
```

The following StackOverflow post led me to the missing command: https://stackoverflow.com/questions/43734650/createdb-database-creation-failed-error-permission-denied-to-create-database

```
(venv) dohenschen@desktop:~/Documents/netbox/netbox$ sudo -u postgres psql
[sudo] password for dhenschen:
could not change directory to "/home/dohenschen/Documents/netbox/netbox": Permission denied
psql (14.7 (Ubuntu 14.7-0ubuntu0.22.04.1))
Type "help" for help.

postgres=# ALTER ROLE netbox CREATEDB;
ALTER ROLE
postgres=# \q
```

Once I added the CREATEDB Attribute to the `netbox` user I was able to run the tests without the permission denied error.

I think it would be helpful to list this step in the documentation to help newcomers get the tests up and running without permission errors. 

Note: I would be willing to open a pull request for this documentation if others think that it would be beneficial.

**Comment by jeremystretch** [comment]
To be clear, the production database user should **not** have permission to create other databases; this is needed only for development purposes (to create the test database). We can add this as a note in the development documentation, but it should not be added to the general installation instructions.

@dhenschen assigning this to you. Thanks!
