### ISSUE TITLE
Make "Context Data" collapsed by default on "Render config" view

### ISSUE THREAD

**Issue by peterbaumert** [netbox-community/netbox#12470]
### NetBox version

v3.5.0

### Feature type

Change to existing functionality

### Proposed functionality

Looking at the "Render Config" tab always show first the "Context Data", this can be quite big. So i always need to scroll down very far to see the rendered config. I think it would be more user friendly if the "Context Data" would be collapsed by default.

### Use case

Getting faster to rendered config without need to scroll for a long time.

**Comment by DanSheps** [comment]
I think that it might be resonable to add a collapse to the context data.  Should be a simple bootstrap change.
