### ISSUE TITLE
Limit amount of locations shown on site view

### ISSUE THREAD

**Issue by tijshuisman** [netbox-community/netbox#12489]
### NetBox version

3.5.0

### Feature type

Change to existing functionality

### Proposed functionality

When opening a site there currently is no limitations in the locations table on the amount of locations shown. Similairly to the limitation of max 10 non-racked devices shown in the site view (implemented in #8920), there should also be a limit to 10 locations shown.

### Use case

On some sites we have 1k+ locations in NetBox. This creates issues like having to scroll for 10 seconds to get to images or the non-racked device table, plus increased unnecessary load times for the site page.

**Comment by arthanson** [comment]
I think this will be addressed via #8184
