### ISSUE TITLE
l2vpn-terminations interface is missing Device field

### ISSUE THREAD

**Issue by vaneuk** [netbox-community/netbox#12500]
### NetBox version

v3.5.0

### Python version

3.8

### Steps to Reproduce

go to https://demo.netbox.dev/ipam/l2vpn-terminations/add/. When attaching to Device there is just interface field, no device selection field

### Expected Behavior

There should be Device field (it is present in 3.4.6).

### Observed Behavior

There is no Device field. When you select interface you have no idea to which device it belongs.

3.5.0
<img width="1029" alt="image" src="https://user-images.githubusercontent.com/31311894/236429127-a0387e2a-c3aa-4b5c-b653-871472e9327b.png">

3.4.6
<img width="1093" alt="image" src="https://user-images.githubusercontent.com/31311894/236429203-cd6d71f9-de90-4f59-91c8-1e353f10a899.png">

**Comment by kkthxbye-code** [comment]
This is intentional. Click the botton to the right of the interface field.
