### ISSUE TITLE
Slug value changes automatically by clicking (in Network Roles section- GUI issue)

### ISSUE THREAD

**Issue by MaZzikeen** [netbox-community/netbox#12519]
### NetBox version

v3.2.3

### Python version

3.8

### Steps to Reproduce

1.go to IPAM--->Prefix Vlans&Roles
2.choose one role and click on edit button
3.click on name and then click on slug

it automatically changes the value of slug to the value of the Name

### Expected Behavior

not to change the value of slug with clicking

### Observed Behavior

NA (GUI issue)

**Comment by kkthxbye-code** [comment]
This was fixed in 3.2.7 and is thus invalid.

[#9749](https://github.com/netbox-community/netbox/issues/9749) - Retain original slug values when modifying object names
