### ISSUE TITLE
Show 'asset_tag' in the rack view

### ISSUE THREAD

**Issue by PieterL75** [netbox-community/netbox#12518]
### NetBox version

v3.4.10

### Feature type

Data model extension

### Proposed functionality

Add 'Asset tag' to the dropdown of the 'rack view'
![image](https://user-images.githubusercontent.com/74899468/236801478-9a921c9a-62ed-4005-96c2-7b54fc623583.png)

### Use case

In our datacenter, we only have the assettags labeled on the devices, not the hostnames.
Currently we can see the assettag if we 'hover' over the name of the device, but it would be better to see the asset in the view direct

**Comment by jeremystretch** [comment]
This probably isn't something we can support without the introduction of a customization mechanism for the device label. It wouldn't make sense to add "asset tags" as an alternative directly to the images/labels dropdown.

**Comment by PieterL75** [comment]
The Assettag is the unique physical identifier of an Asset. The little sticker (actually a pretty big one on front and back) that we put on the device, to identify it in the datacenter, without the burden of (changing) naming standards. 
Having a RackView with Assettag is pretty logical to me..

The PR I have takes care of that, and provides 2 means of creating that view
- with the dropdown
- with an extra parameter "use_assettag=true" to the vsg generating url

That allows us to get that view in automation and in the gui

Pieter

**Comment by PieterL75** [comment]
@jeremystretch Shall I submit the PR ? then you can review how it works.
This FR will only add an extra view pane to the racks, nothing more.

**Comment by PieterL75** [comment]
Can this be reviewed again ?
I would very much like to see that 'asset_tag' as labels in the view, rather than the 'devicename'
In our datacenters, the physical world works only with 'asset tags' and not with devicenames.
