### ISSUE TITLE
Unable to use plugin models in custom scripts

### ISSUE THREAD

**Issue by Bapths** [netbox-community/netbox#12515]
### NetBox version

v3.4.3

### Python version

3.10

### Steps to Reproduce

1. Add a custom script using an installed plugin:
   ```py
   from myplugin.models import MyPluginModel
   from extras.scripts import *
   
   class MyCustomScript(Script):
       class Meta:
           name = 'My Custom Script'
           description = 'My Custom Script Description'
       
       def run(self, data, commit):
           return 'Test script'
   ```
2. Save the file and run the script from the Netbox Web UI.

### Expected Behavior

The script should run and output `Test script`.

### Observed Behavior

The script is stuck in pending state.
When we look for the job in the admin panel we can see that the status is `failed` with the following Exception:
```
[...]
RuntimeError: Model class myplugin.models.MyPluginModel doesn't declare an explicit app_label and isn't in an application in INSTALLED_APPS.
```

**Comment by jsenecal** [comment]
How are you running netbox ?

**Comment by jsenecal** [comment]
Is your worker process running off the same python (virtual?) environment? It seems to me that your plugin is not "installed" for the worker.
