### ISSUE TITLE
"No Scripts Found" for non superusers.

### ISSUE THREAD

**Issue by gennit** [netbox-community/netbox#12516]
### NetBox version

v3.5.1

### Python version

3.8

### Steps to Reproduce

Login as Active user (with or without staff but not superuser) with "extras | script" actions set to run, view.
Select Customization > Scripts
![image](https://user-images.githubusercontent.com/51842481/236793465-c23ecba3-1a0e-4c7f-a9db-17b3918aa26c.png)

### Expected Behavior

Expect to see list of scripts that are available in Netbox.

### Observed Behavior

Page reports "No Scripts Found"
![image](https://user-images.githubusercontent.com/51842481/236792900-03fcee52-28a5-4bb4-a7ca-5ec0b0fd37f1.png)

If the same user is set to Superuser and page refreshed, then all scripts are listed.  Unset superuser and refresh, returns to "No Scripts Found"

Issue occurs with local and LDAP authenticated users.

**Comment by abhi1693** [comment]
I have not tested this but try adding view permission to `extras > script module` along with `scripts`.

**Comment by gennit** [comment]
That is already the case:
![image](https://user-images.githubusercontent.com/51842481/236938809-e62867ad-7bca-45e5-8f16-eabc0983984e.png)

Also of note, this was working fine prior to upgrade to 3.5.0

**Comment by abhi1693** [comment]
Your screenshot still doesn't show if you have selected script module. Note that script is different than script module.

**Comment by gennit** [comment]
Thank you, greatly appreciated.  A simple fix for reference:
![image](https://user-images.githubusercontent.com/51842481/236963741-a2f25eaf-f8a1-4124-9f00-a620ee789ea5.png)

Not sure if this is an additional permission that has appeared since 3.5.0 but that makes all the difference.
