### ISSUE TITLE
Open image attachments in new tab

### ISSUE THREAD

**Issue by blindzero** [netbox-community/netbox#12539]
### NetBox version

v3.5.1

### Feature type

New functionality

### Proposed functionality

When opening an image attachment (e.g. on a device / device type) you "leave" your netbox context and the image is opened in your tab / window where netbox were.
It would be great if attachments as images would open in a new tab.

### Use case

It is most likely that you use an attachment as additional info while maintaining an object. Hence it would be an improvement of usability if attachments would not force you to "leave" your netbox context and force you to navigate back.

**Comment by abhi1693** [comment]
You can Ctrl+click the link to open in a new tab.

**Comment by jeremystretch** [comment]
As has been discussed in other threads, it is considered poor practice to force a link to open in a new window/tab. This should be left to the user's discretion.

**Comment by blindzero** [comment]
Ok, seems I have to accept that perspective ;-)
but from a usability perspective it is not good if the user leaves its originated context for additional / attached information.
None of our tools handles it like this ;-)
