### ISSUE TITLE
Field virtual Machine is missing in IPAM IP address assignment

### ISSUE THREAD

**Issue by hdse** [netbox-community/netbox#12542]
### NetBox version

3.5.1

### Python version

3.10

### Steps to Reproduce

1. Click IPAM
2. IP Addresses
3. Select an IP address
4. goto Edit
5. Interface Assignment Virtual Machine

### Expected Behavior

Since version update from 3.5.0 to 3.5.1 the field **Virtual Machine** is missing.
Be for there was a field **Virtual **Machine** and  the **Interface** field. Now it is unable to select the right virtual machine.

### Observed Behavior

![IF](https://github.com/netbox-community/netbox/assets/35737837/8d9ec72d-e73f-429b-b9f9-e5368abd29e2)

**Comment by kkthxbye-code** [comment]
You need to use the advanced filter button at the right side of the field. Click that, click virtual machine, choose the vm, click search and click on the interface you want.
