### ISSUE TITLE
Add PDF attachments to device and device type

### ISSUE THREAD

**Issue by blindzero** [netbox-community/netbox#12541]
### NetBox version

v3.5.1

### Feature type

New functionality

### Proposed functionality

I wanted to upload and add a PDF of a device spec sheet to a device type, so all - even more detailed - information is available to the user. Unfortunately, I was not able to achieve this as the uploads only support images and custom fields do not support uploads either.

### Use case

Lookup of vendor specific detailed information. Just linking to spec sheets results in changed vendor links and lost information.

**Comment by kkthxbye-code** [comment]
This is a duplicate: https://github.com/netbox-community/netbox/issues/3404, https://github.com/netbox-community/netbox/issues/1039, https://github.com/netbox-community/netbox/issues/5783, [#3681](https://github.com/netbox-community/netbox/issues/3681)

See also the FAQ:

https://github.com/netbox-community/netbox/wiki/Frequently-Asked-Questions#user-content-why-does-netbox-support-only-image-attachments

There's also a plugin that allows file uploads: https://github.com/Kani999/netbox-attachments
