### ISSUE TITLE
Show or link front / rear image from device type to device

### ISSUE THREAD

**Issue by blindzero** [netbox-community/netbox#12540]
### NetBox version

v3.5.1

### Feature type

New functionality

### Proposed functionality

A front / rear image on a device type should be easily accessible from a device by a link or even be shown.

### Use case

Usability improvement, less back and forth navigation.

**Comment by abhi1693** [comment]
On the device page, you get the full rack view which displays the images as well. Does that not suffice here?

**Comment by jeremystretch** [comment]
You can also just follow the link to the device's device type. I see no reason to embed the device type elevations within the device view, which is already quite busy.

**Comment by blindzero** [comment]
The device type is some template. So the important instance is the device itself, right?
Hence, a dedicated front / rear attachment is more important on the device itself, but not existing there.
This would be ok if the information from the template would be accessible more easily. Other tools often work with modal displays etc in these cases.
