### ISSUE TITLE
No longer able to select a range of rear ports to associate with a group of front ports

### ISSUE THREAD

**Issue by shatt79** [netbox-community/netbox#12550]
### NetBox version

3.5

### Feature type

Change to existing functionality

### Proposed functionality

Prior to 3.5, when creating front ports on a device, we could shift+click a range of rear ports to tie the front ports to.  Now, we have to click rear ports one at a time.  I'd like for the old method to return, if possible.

### Use case

When creating 288ct patch panels, it's extremely cumbersome to have to individually click each rear port.  What used to take 2 seconds now takes 20+ minutes.  Being able to select a range of rear ports will greatly speed up this process.

**Comment by kkthxbye-code** [comment]
I don't think this was intended, so not sure if this is actually a feature request. I think it changed as part of the stuff @jeremystretch did with regards to allowing components to be added from the sidebar link.

**Comment by jeremystretch** [comment]
Was just looking into this; can confirm it's a bug and was not intentional. I think it actually stems from some earlier changes I made to the `BootstrapMixin` class which are affecting how the widget is being rendered. We don't have many multi-select fields that render as expanded as fields, so I'm guessing this was simply overlooked. Need to dig into it some more.

**Comment by shatt79** [comment]
Wow!  Thanks for the quick response!  Will this be in the next release?  3.5.2?

**Comment by jeremystretch** [comment]
Yep, it will be in v3.5.2.

**Comment by shatt79** [comment]
@jeremystretch 
I'm still seeing the same behavior in 3.5.2.  I can only click one rear port at a time when adding front ports.  Is there some kind of keyboard shortcut I'm missing?

**Comment by shatt79** [comment]
Hmm...

![image](https://github.com/netbox-community/netbox/assets/103387334/4f74557c-96db-4289-9479-ed17555eb7ea)

**Comment by kkthxbye-code** [comment]
@shatt79 gotcha, please create a new issue with the new replication steps.
