### ISSUE TITLE
Add IP address to auth log output

### ISSUE THREAD

**Issue by adamboutcher** [netbox-community/netbox#12562]
### NetBox version

v3.5.1

### Feature type

Change to existing functionality

### Proposed functionality

Change the Netbox logger (netbox.auth.login) for authentication failure to include the remote IP address, this.

### Use case

The change would allow for parsing of the logs easier to detect brute force authentication attacks (i.e. Fail2Ban etc).

`May 11 12:58:20 netbox NetBox: level=INFO,logger=netbox.auth.login,msg=Failed login attempt for username: test-fail`
to
`May 11 12:58:20 netbox NetBox: level=INFO,logger=netbox.auth.login,msg=Failed login attempt for username: test-fail from x.y.1.1`

### Database changes

NA.

### External dependencies

This may have to use the X-Real-IP header?

**Comment by adamboutcher** [comment]
Possibly need the output to be easier to parse?

Such as:
`May 11 12:58:20 netbox NetBox: level=INFO,logger=netbox.auth.login,msg=Failed login attempt; username: test-fail; from: x.y.1.1;`

You could parse using the deliminators ; then :

**Comment by DanSheps** [comment]
I noticed you are using 3.4.2.  I am assuming this is still present in 3.5.1, however could you confirm this on 3.5.1 and update your FR?

**Comment by adamboutcher** [comment]
> I noticed you are using 3.4.2. I am assuming this is still present in 3.5.1, however could you confirm this on 3.5.1 and update your FR?

Yes, still the same in 3.5.1, updated the original post to reflect this.
