### ISSUE TITLE
Config Context: FieldError

### ISSUE THREAD

**Issue by drobnymichal** [netbox-community/netbox#12570]
### NetBox version

v3.5.1

### Python version

3.10

### Steps to Reproduce

1. Click on the Config Context link in the MENU
2. Press the Sync header in the table to sort by is_synced

### Expected Behavior

List of Config Context objects should appear.

### Observed Behavior

I got this error:

```
<class 'django.core.exceptions.FieldError'>

Cannot resolve keyword 'is_synced' into field. Choices are: auto_sync_enabled, cluster_groups, cluster_types, clusters, created, data, data_file, data_file_id, data_path, data_source, data_source_id, data_synced, description, device_types, id, is_active, last_updated, locations, name, platforms, regions, roles, site_groups, sites, tags, tenant_groups, tenants, weight

Python version: 3.10.6
NetBox version: 3.5.1
```

**Comment by kkthxbye-code** [comment]
Changed the replication steps to include what is actually failing. The sync table column is a computed property, so ordering by it fails as the database field doesn't exist.

The same issue is present for Configuration Templates and Export Templates.
