### ISSUE TITLE
Adding Abnormal status to IP Address

### ISSUE THREAD

**Issue by apellini** [netbox-community/netbox#12582]
### NetBox version

v3.5.1

### Feature type

Change to existing functionality

### Proposed functionality

Adding Abnormal on status for IP Address could help to manage hosts that exists in network but are not registered on CMDB.

### Use case

Registering IP that exists in network and not in CMDB.

**Comment by jeremystretch** [comment]
This would not make sense to add as a core status value, but you're free to define your own [custom statuses](https://docs.netbox.dev/en/stable/configuration/data-validation/#field_choices) for IP addresses locally.
