### ISSUE TITLE
Introduce a UI view for altering NetBox's dynamic configuration parameters

### ISSUE THREAD

**Issue by jeremystretch** [netbox-community/netbox#12591]
### NetBox version

v3.5.1

### Feature type

New functionality

### Proposed functionality

Introduce a UI view which allows administrators to alter NetBox's [dynamic configuration parameters](https://docs.netbox.dev/en/stable/configuration/#dynamic-configuration-parameters), and remove this functionality from the Django admin UI.

### Use case

The admin UI is being removed in NetBox v4.0 (see https://github.com/netbox-community/netbox/issues/12325).

**Comment by emersonfelipesp** [comment]
Hi @jeremystretch, will this page include support to change `PLUGINS` and `PLUGINS_CONFIG` variables?

**Comment by deku-m** [comment]
Would be nice to also have the LDAP/SSO/SAML config in there maybe?

**Comment by jeremystretch** [comment]
The scope of this issue is limited to moving the existing view from the admin UI to the regular frontend.
