### ISSUE TITLE
Dashboards/Widgets: no documentation

### ISSUE THREAD

**Issue by stavr666** [netbox-community/netbox#12595]
### NetBox version

v3.5.1

### Feature type

Change to existing functionality

### Proposed functionality

Add information about [Customizable Dashboards](https://docs.netbox.dev/en/stable/release-notes/version-3.5/#customizable-dashboard-9416) and logic behind models/filters to official documentation.

### Use case

- Creating personal dashboards.
- Provisioning [default model](https://docs.netbox.dev/en/stable/configuration/default-values/#default_dashboard) for new users.
- Fixing issues about not-working functionality (checking if something working some way by design, or if no one tested it yet).

**Comment by jeremystretch** [comment]
Please use the [documentation change](https://github.com/netbox-community/netbox/issues/new?assignees=&labels=type%3A+documentation&projects=&template=documentation_change.yaml) template for proposed changes to the documentation.
