### ISSUE TITLE
Dashboard "object counts" widgets can't filter on multiple tenants

### ISSUE THREAD

**Issue by eric-eisenhart** [netbox-community/netbox#12598]
### NetBox version

v3.5.1

### Python version

3.9

### Steps to Reproduce

1. Create or edit a widget of type "objects type list".
2. Select Models of "DCIM > Cable", "DCIM > Device", "DCIM > Rack", and "DCIM > Site". 
3. Give it an object filter of `{"tenant_id": ["19", "34"]}`. (pick tenant ids that exist in this specific install)

### Expected Behavior

Save widget and widget shows me counts for the total of things for both those tenants.

Similar syntax works to filter an object list "object change" list (changelog) by changed_object_type_id: 
`{"changed_object_type_id": ["14", "27", "30", "23", "51", "80", "87", "130", "78", "79", "8", "67", "70", "68", "69", "86"]}`
![image](https://github.com/netbox-community/netbox/assets/1577595/0a7e7ee9-f251-4599-a799-3c19f460399b)

### Observed Behavior

Error: "Invalid filter specification for cables." and can't save.

![image](https://github.com/netbox-community/netbox/assets/1577595/e7955673-eebc-46cc-8cb9-50276f1ee945)

(changing to any single one of the models does not make it work)

**Comment by abhi1693** [comment]
You need to use `tenant_id__in` to filter using list.

**Comment by eric-eisenhart** [comment]
Does that make this a duplicate of #12595?

FYI: the main way I know to work out the json filter syntax is to go to something like /dcim/devices, filter the list, then "save" and copy the "Parameters". If I filter to those two tenants, I get:
```json
{
    "tenant_id": [
        "19",
        "34"
    ]
}
```
