### ISSUE TITLE
Carry filters over when clicking on object list in dashboard widget

### ISSUE THREAD

**Issue by eric-eisenhart** [netbox-community/netbox#12599]
### NetBox version

v3.5.1

### Feature type

Change to existing functionality

### Proposed functionality

I have an "Object Count" widget with a Devices/Cables/Racks/Sites and tenant filter `"{"tenant_id": "19"}`. I'd like if I click (for example) on "Devices" that I get `/dcim/devices/?tenant_id=19` instead of `/dcim/devices/`.

### Use case

Makes widgets with filters more useful if clicking on something gives a page with the actual items in the count instead of _all_ objects of that type. And can make the dashboard widgets a handy way to get to what that user needs to see.

**Comment by stavr666** [comment]
Gonna fill the report about it too, but since there is no sane description of intended and planned functionality yet ( #12595 ), delayed the report before clarification from devs.

**Comment by jeremystretch** [comment]
Per the contributing guide:

> Don't prepend your issue title with a label like [Bug]; the proper label will be assigned automatically.

**Comment by jeremystretch** [comment]
Marking this as blocked by #12742 as its implementation depends on adjusting the widget to support FilterSet filters rather than QuerySet filters.

**Comment by jeremystretch** [comment]
I'll take this as I just pushed a fix for #12742.
