### ISSUE TITLE
Custom Field UI visibility option "Hidden if unset"

### ISSUE THREAD

**Issue by eric-eisenhart** [netbox-community/netbox#12597]
### NetBox version

v3.5.1

### Feature type

Change to existing functionality

### Proposed functionality

On the custom-fields edit page, add "Hidden if unset" option to the "UI visibility" selection, and on the object view page, if that's set on definition of a custom field _and_ the field is unset hide that custom field (instead of showing `-`).

### Use case

We have devices managed by a few groups with different needs, and we're using custom fields to help with some of that. This would keep the display of a device (or virtual-machine) cleaner when custom fields aren't used on a specific device.

Use cases are similar to #12423, but I suspect the code would be much simpler.

**Comment by gabrielat** [comment]
Hello! Is it possible to enable this feature in Custom Links too? I have a custom link that calls a custom field and it is useless if the custom field is not set.

**Comment by jeremystretch** [comment]
@gabrielat custom links which do not render a text value will be hidden. You can simply craft your links to not display any text if the custom field is empty.
