### ISSUE TITLE
Add LX.5 port type

### ISSUE THREAD

**Issue by mihacucek** [netbox-community/netbox#12605]
### NetBox version

v3.4.10

### Feature type

Change to existing functionality

### Proposed functionality

Add port types:

1. LX.5 PC/UPC  
2. LX.5 APC  
3. LX.5 

### Use case

Modelling optical ports with LX.5 connector type.

1. - LX.5 single mode PC/UPC
2. - LX.5 single mode APC
3. - LX.5 multimode

![image](https://github.com/netbox-community/netbox/assets/65233127/d62aa2bf-453a-4743-a78d-0a6511bcc33e)
I started with discussion but decided to open issue for enhancement.

Standards defining LX.5 connector type are IEC 61754-23 and TIA 604-13

https://github.com/netbox-community/netbox/discussions/12545

### Database changes

/

### External dependencies

/

**Comment by decoupca** [comment]
I'll take this one
