### ISSUE TITLE
VRF-independent prefix children

### ISSUE THREAD

**Issue by marcartz** [netbox-community/netbox#12608]
### NetBox version

v3.5.1

### Feature type

Change to existing functionality

### Proposed functionality

New prefix view: Please provide a flag to configure a prefix display view in a way that child prefixes are included purely based on their address, ignoring their VRF membership.

### Use case

When using VRFs to enforce security zones, as common in many Cisco designs, children prefixes of a given supernet may belong to different VRFs. A central routing instance interconnects all VRFs in a single shared routing table ([Fusion Router](https://www.cisco.com/c/en/us/support/docs/cloud-systems-management/dna-center/213525-sda-steps-to-configure-fusion-router.html)).
While Prefixes are technically unique to a given VRF in this scenario some coordination (uniqueness) of networks across VRFs is still required.

**Comment by jeremystretch** [comment]
> When using VRFs to enforce security zones

This is not the purpose of VRFs. Each VRF represents a discrete routing table. I'd suggest using tags, custom fields, or a plugin to effect the association of prefixes to security zones, as doing so is wholly independent from VRF assignment.
