### ISSUE TITLE
GraphQL timezone doesn't match REST API

### ISSUE THREAD

**Issue by tagur87** [netbox-community/netbox#12611]
### NetBox version

3.5.1

### Python version

3.8

### Steps to Reproduce

1. Run curl to API endpoint and get the `time_zone` field from first result
```
curl -X 'GET' 'http://localhost:8001/api/dcim/sites/'  -H 'accept: application/json' -H 'Content-Type: application/json' \    
  -H 'Authorization: Token 0123456789abcdef0123456789abcdef01234567' | jq -r '.results[0].time_zone'

Asia/Dhaka
```

2. Run curl to graphql endpoint for same 
```
curl -X 'POST' 'http://localhost:8001/graphql/'  -H 'accept: application/json' -H 'Content-Type: application/json' \
  -H 'Authorization: Token 0123456789abcdef0123456789abcdef01234567' --data '{"query": "query{site_list{id time_zone}}"}' | jq -r '.data.site_list[0].time_zone' 

ASIA_DHAKA
```

### Expected Behavior

The format of the `time_zone` field should be the same between the api and the graphql endpoints.

### Observed Behavior

The `time_zone` field formatting is different between the api and graphql endpoints.

**Comment by tagur87** [comment]
Related to #11806 & #7466

**Comment by jeremystretch** [comment]
@tagur87 as this has already been discussed under #7466 and abandoned, re-opening the issue will require an owner. Are you willing to commit to doing this work?

**Comment by tagur87** [comment]
> @tagur87 as this has already been discussed under #7466 and abandoned, re-opening the issue will require an owner. Are you willing to commit to doing this work?

You mentioned originally:

>I'm going to close this out both because no work has been done and because it will likely become moot per https://github.com/netbox-community/netbox/issues/9856.

However this never actually went through.

I don't have any ideas of where to start on this. Not sure why the difference? Is it b/c of different libraries used?

**Comment by tagur87** [comment]
Ahh, I actually see that django-strawberry issue got reopened....

**Comment by jeremystretch** [comment]
Yeah, the intent currently is to replace `django-graphene` with `django-strawberry` in v4.0, although work has not yet begun on that initiative.

**Comment by jeremystretch** [comment]
As this has already been raised and will likely be moot upon adopting django-strawberry, I'm going to close this out.
