### ISSUE TITLE
Ability to attach documents to the device types templates

### ISSUE THREAD

**Issue by pharalambiev** [netbox-community/netbox#12613]
### NetBox version

v.3.5.1

### Feature type

New functionality

### Proposed functionality

Hi all,

Firstly, I want to thank you for the great product you have created!

My request is for a new feature related to to DCIM - Device types:
As a user I want to be able to attach additional documents like .pdf and .txt (or other format) to the template.

### Use case

My use case is as follows:
In my company we are maintaining huge variety of network devices (switches, routers, OLTs). Sometimes, more often than anticipated, we need to refer to a specific documentation related to these devices. The documentation we referring for the time being is mostly detailed technical specifications and SNMP MIB files.
If we were able to attach such files to the device templates we would have had all needed information for a particular device in one place and this could transform Netbox as a real single source of truth.

### Database changes

I'm not aware if this will require data base schema change. I assume that a new columns should be added.

### External dependencies

Not required.

**Comment by jeremystretch** [comment]
Thank you for submitting this issue, however it appears that this topic has already been raised. Please see issue #3404 for further discussion.
