### ISSUE TITLE
Add missing 400GE interface types

### ISSUE THREAD

**Issue by sleepinggenius2** [netbox-community/netbox#12629]
### NetBox version

v3.5.1

### Feature type

Change to existing functionality

### Proposed functionality

There are existing 400GE interface types for QSFP-DD and OSFP. This proposal is to add the missing types for CDFP (400GE) and CFP8 (400GE). I don't have experience at this time with 800GE, but my research has indicated that neither of these form factors are currently valid for that speed.

### Use case

This would allow for the ability to properly document devices that have started coming out with these new interface types.

### Database changes

None

### External dependencies

None

**Comment by sleepinggenius2** [comment]
@DanSheps, I think you assigned this to the wrong person. It looks like @apellini has already linked a PR for this.

**Comment by jeremystretch** [comment]
@apellini would you mind commenting here so that we can assign this issue to you please? (GitHub will not permit us to otherwise.)

**Comment by apellini** [comment]
I have published pull request to this requests

**Comment by DanSheps** [comment]
Sorry about that.  That was my B.
