### ISSUE TITLE
The sync permission for Data Source is not documented

### ISSUE THREAD

**Issue by kkthxbye-code** [netbox-community/netbox#12623]
### Change Type

Addition

### Area

Integrations/API

### Proposed Changes

I was unable to find any documentation of the required permission to sync a data source. Looking at the code, the additional action `sync` is needed for the `Data Source` object permission.

**Comment by hhopjh** [comment]
Any chance to fix this? At this point the only way to grant user permission to sync the Data Source is grant the user Super Admin right.

**Comment by kkthxbye-code** [comment]
> At this point the only way to grant user permission to sync the Data Source is grant the user Super Admin right.

No, this is only a documentation change. As is stated, the user just need to have the `sync` additional action assigned for the `Data Store` object permission. The issue is that is is not documented, but it should work fine.

**Comment by hhopjh** [comment]
Thanks for comment! Which object type is responsible for the `sync` permission? 

<img width="829" alt="Screenshot 2023-08-14 at 12 44 14" src="https://github.com/netbox-community/netbox/assets/18419207/f16651da-8ee8-494d-a209-a1ddd7e6958b">

**Comment by hhopjh** [comment]
Oh I see. It should be configured like this:

<img width="950" alt="Screenshot 2023-08-14 at 13 01 53" src="https://github.com/netbox-community/netbox/assets/18419207/fd0bc99d-6a58-485e-b44f-d758a3eb7ec5">
