### ISSUE TITLE
Add django-admin-honeypot?

### ISSUE THREAD

**Issue by tobicodesstuff** [netbox-community/netbox#12637]
### NetBox version

v3.5.1

### Feature type

Change to existing functionality

### Proposed functionality

Add the 'django-admin-honeypot'. The package does not seem fully up to date though, so probably when it is again updated?

### Use case

Hide the /admin login mask, log access attempts and hide the proper admin login.

### Database changes

Third party package migrations.

### External dependencies

django-admin-honeypot

**Comment by jeremystretch** [comment]
I don't see why this would be needed for a proper production deployment, when plenty of options exist for limiting access to the UI.
