### ISSUE TITLE
Bulk contact-to-object assignments

### ISSUE THREAD

**Issue by opericgithub** [netbox-community/netbox#12631]
### NetBox version

v3. 5.1

### Feature type

New functionality

### Proposed functionality

Currently there is no gui possibility to bulk-assign many contacts to many objects. The only way we have found is by directly modifying database with "insert into tenancy.contact (...) values (...)(...) etc " which may be very hazardous.

There should be an gui option to link the ID of the contact with the ID of the object, let's say a device. 

### Use case

We have thousands of devices representing physical IP phones, and also have thousands of contacts, each of them representing the phone number of the IP phone.

We would like to link all of the contacts to all of the devices, but there is no way to do that by bulk editing (importing) devices because there is no available contact field option. 

If such field existed, it would be easy to link let's say a list of device id's with a list of contact id's.

As for now, we have to edit thousands of devices one-by-one and click "add a contact" button on every single one of them.

**Comment by jeremystretch** [comment]
Thank you for submitting this issue, however it appears that this topic has already been raised. Please see issue #11307 for further discussion.
