### ISSUE TITLE
Add bulk interface validation missing causes server error

### ISSUE THREAD

**Issue by rfl64** [netbox-community/netbox#12639]
### NetBox version

v3.5.1

### Python version

3.8

### Steps to Reproduce

1 click in add interface on any device
2 try to create severals interfaces in bulk mode for example Gi[11-8] (of course wrong interface order should not cause application error)
![add a new interface v3 5 1 bug](https://github.com/netbox-community/netbox/assets/57568271/ee4e1895-09d5-4bb9-a0c1-c11760e14ef3)
![github 3 5 1 interface bug](https://github.com/netbox-community/netbox/assets/57568271/cef37695-21ef-450a-ae29-6bc6e4e37f49)

3 click save button

### Expected Behavior

a warning message would be spected to correct wrong interface order

### Observed Behavior

Server Error
contact server admin message raised.
![github 3 5 1 interface bug](https://github.com/netbox-community/netbox/assets/57568271/b9b549f1-6ad3-4ac2-9bb4-7997f608aefb)

**Comment by dhenschen** [comment]
I would like to take ownership of this issue.

**Comment by arthanson** [comment]
@dhenschen do you still want to take ownership of this?

**Comment by dhenschen** [comment]
@arthanson You can move this back to unassigned. Thanks!
