### ISSUE TITLE
Display headers while scrolling

### ISSUE THREAD

**Issue by nicksonthegithub** [netbox-community/netbox#12641]
### NetBox version

v3.5.1

### Feature type

Change to existing functionality

### Proposed functionality

Freeze the top pane or have the column headers able to float with the data to keep from having to jump around on the page. Example of what is meant by column headers attached.

![netbox column headers request](https://github.com/netbox-community/netbox/assets/106605365/40bd3361-ad10-4549-aaff-a40671df21d3)

### Use case

Like many others leveraging NetBox, within our environment we have hundreds of rows of data available in most sections. We end up jumping back to the top of the page to validate what the header is for the column we're viewing.

**Comment by PieterL75** [comment]
Could be looked at together with #9386 ?
