### ISSUE TITLE
Ability to configure edit ribbon location on page

### ISSUE THREAD

**Issue by nicksonthegithub** [netbox-community/netbox#12640]
### NetBox version

v3.5.1

### Feature type

Change to existing functionality

### Proposed functionality

Make an option available in a configuration file to set if the edit ribbon is at the bottom of the pages (where it currently lives), at the top of the page, or available at both the top and bottom of a page. Screen shot of what I'm trying to convey with "edit ribbon".

![netbox 3 5 1  edit bar](https://github.com/netbox-community/netbox/assets/106605365/5b2ec9ff-254b-4482-96af-e99b094484b9)

### Use case

A lot of the pages within our various sections have hundreds of rows. The goal with this request is to make editing sections more intuitive for some of our staff newer to NetBox.

**Comment by PieterL75** [comment]
Or as in #9386 (Make form/pagination button stick at the bottom) make them stick at the bottom/top ?
