### ISSUE TITLE
New SAS/SFP+ interface types 

### ISSUE THREAD

**Issue by artiomello** [netbox-community/netbox#12651]
### NetBox version

v3.5.1

### Feature type

Data model extension

### Proposed functionality

Hi,

As per [How Can I Add New Interface Types](https://github.com/netbox-community/netbox/wiki/Frequently-Asked-Questions#how-can-i-add-new-interface-types), requesting to please add 

1. `SAS/mini-SAS` interface types, which, for some reason, are missing altogether from Netbox. [More info here.
](https://en.wikipedia.org/wiki/Serial_Attached_SCSI#Connectors)
2. `32GFC `and `64GFC `to Fiber Channel SFP+ selection, which currently tops out at 16GFC. 
32/64GCF SFP+ seems to be a Lenovo/Brocade offering. [More info here.](https://lenovopress.lenovo.com/lp1358-thinksystem-db720s-gen7-fc-san-switch#transceivers-and-cables)

### Use case

Due to the fact that both SAS/mini-SAS and 32/64GCF SFP+ inteface types are missing from Netbox, we cannot properly document our equipment.

**Comment by DanSheps** [comment]
The SAS/mini-SAS would likely be added as part of #11506 if that is undertaken.  Otherwise, this has been proposed before and did not gain enough traction:

* #11855
* #11474
* #10265
* #6549
* #3617
* #2715
* #659

**Comment by artiomello** [comment]
Well, while I'm definitely for the expansion of what Netbox has to offer, I personally don't see the added benefit of documenting disk and raid properties here in Netbox. 

With that said, `interface type` is just a hardcoded string that does not require any additional development whatsoever. At least from what I've been configuring, the interface object properties don't change depending on its type. 

What I'm requesting, as per the FAQ, is to add "_a commercially-available interface type that has not yet been added to NetBox_". And from the perspective of it being just a plain old hardcoded string, I don't see a problem in adding neither `32/64GCF SFP+` nor `miniSAS` connectors.

Half of the available ones just as easily could be replaced with the nondescript Other type. Therefore I don't see why it would hurt anyone to have a better way of describing the storage "network"/connections.

**Comment by danb21t** [comment]
I'd like to see SAS interfaces added to the Netbox Interface Types.

Currently fitting out our DCIM and have a lot of NetApp hardware of which this would be beneficial.

**Comment by DanSheps** [comment]
> I'm fine to try that so I'm reading [submitting-pull-requests](https://github.com/netbox-community/netbox/blob/develop/CONTRIBUTING.md#arrow_heading_up-submitting-pull-requests) and I see:

What would the scope be?  As mentioned, the SAS interfaces would likely be added as part of a larger storage management change.  Would you be interested in just modelling the extra SFP+ modules for now?

**Comment by jose-d** [comment]
@DanSheps, I thought I'd in `choices.py` add into `class InterfaceTypeChoices`:

```python
...
# Storage
    TYPE_SFF_8614 = 'sff-8614'
...
CHOICES = (
...
        (
            'Storage',
            (
                (TYPE_SFF_8614, 'SFF-8614 (Mini-SAS HD)'),
            )
        ),
...
)
...
```

**Comment by DanSheps** [comment]
As mentioned above, SAS storage interfaces would be captured by the above FR and would be be accepted under this.  I don't think there is much to do here right now.
