### ISSUE TITLE
Assigning an IP to a device interface is now overly cumbersome?

### ISSUE THREAD

**Issue by mgob** [netbox-community/netbox#12669]
### NetBox version

v3.5.1

### Python version

3.8

### Steps to Reproduce

1. Find an available IP address
2. Click edit or Add
3. Navigate to assgin to device, interfaces for ALL devices are listed by default but you have to open the enhanced search window to the right to get to search by device.  This did not used to be the case.  

### Expected Behavior

Ability to filter by device FIRST before filtering by interface

### Observed Behavior

Interfaces are listed without devices for assigning to a device.

Either this is a regression or a poor UI change that adds an unnecessary step to assigning an IP to a device interface.  Alternatively I'm a moron and missed a settings change somewhere along the way to make this not the default behavior LOL.

![IMG_0106](https://github.com/netbox-community/netbox/assets/6238776/03a6937a-4590-4d9c-9d52-8d3c7f68d8d4)

**Comment by mgob** [comment]
It would appear this is related to #10757 ?

**Comment by jsenecal** [comment]
Have you tried clicking on the little button right to the interface field ?

**Comment by jsenecal** [comment]
Thank you for opening a bug report. It seems that the described functionality is intended behavior. If you meant to open a feature request instead, please close this issue and open a new one using the [feature request template](https://github.com/netbox-community/netbox/issues/new?template=feature_request.md). Otherwise, please revise your post above to elaborate on why you believe the observed behavior is flawed.

**Comment by mgob** [comment]
> Thank you for opening a bug report. It seems that the described functionality is intended behavior. If you meant to open a feature request instead, please close this issue and open a new one using the [feature request template](https://github.com/netbox-community/netbox/issues/new?template=feature_request.md). Otherwise, please revise your post above to elaborate on why you believe the observed behavior is flawed.

It’s very odd intended behavior if it truly is, I’ll open a feature request. I’ve got numerous user complaints over this change.
