### ISSUE TITLE
IP address to Device/VM assignment bug

### ISSUE THREAD

**Issue by kotso** [netbox-community/netbox#12661]
### NetBox version

v3.5.1

### Python version

3.8

### Steps to Reproduce

1. Edit IP address you want to assign.
2. When you are choosing to assign IP to Device/Virtual Machine/FHRP Group, before there where 2 inputs, one to find VM/Device/ and second to choose interface of selected item.
3. Now I only see single input, interface, that comes with all interfaces in same location. And in listing there is only interface name, no reference to device. I think it's just mistakenly hidden from interface, was working correctly in 3.5.0

### Expected Behavior

Device/VM/etc... selection input to be displayed

### Observed Behavior

no device/vm/group selection input

**Comment by kotso** [comment]
<img width="809" alt="Screenshot 2023-05-19 at 12 35 21" src="https://github.com/netbox-community/netbox/assets/1928528/fdc83326-6987-46e2-8a12-db1e3abacea3">

**Comment by kotso** [comment]
even if I try to assign ip from device, by searching it. Same interface shows up, so did not find any workaround to make assignment in latest version.

**Comment by kotso** [comment]
same issue is observed on https://demo.netbox.dev/

**Comment by DanSheps** [comment]
This has been switched over to the new "selector".  You need to select the dialog to the right of the dropdown and filter your interfaces using the options there.  This includes filtering by device, site, whatever.

**Comment by kotso** [comment]
@DanSheps ok, then I do not get point how to identify device.

<img width="957" alt="Screenshot 2023-05-20 at 15 55 10" src="https://github.com/netbox-community/netbox/assets/1928528/a6faa1dd-e477-4d9d-9f7f-38fd3c14c28c">

Here is example, I see list of interface in same location where IP is assigned but how should I understand which eth0 belongs to my vm I'm looking for?

**Comment by kotso** [comment]
oh.... I got it now. 

small icon with very powerful search functionality.

Will need some time to get used to it but seems to be big improvement.
