### ISSUE TITLE
Add "Create/Add" Buttons to Cables/Wireless Links Sidebar Menu

### ISSUE THREAD

**Issue by stuntguy3000** [netbox-community/netbox#12674]
### NetBox version

v3.5.1

### Feature type

New functionality

### Proposed functionality

The new functionality will streamline the adding of new Cables and Wireless Links by adding "Create/Add" buttons to these sidebar menu options.

![image](https://github.com/netbox-community/netbox/assets/1522389/18a783be-c670-4aa3-9d45-23a2ea1753df)

_Happy to implement myself if approved._

### Use case

This speeds up the addition of adding these objects making documentation quicker to do. 

For example, when onboarding devices, it is significantly faster to use the Cables menu to connect interfaces together by searching for them.

### Database changes

None required.

### External dependencies

The Cables form currently does not have a functional "blank form" state (https://github.com/netbox-community/netbox/issues/12579) and this will need to be resolved prior to enable this functionality.

**Comment by jeremystretch** [comment]
Thank you for submitting this issue, however it appears that this topic has already been raised. Please see issue #12127 for further discussion.
