### ISSUE TITLE
Markdown in custom field descriptions not rendered in object edit view

### ISSUE THREAD

**Issue by decoupca** [netbox-community/netbox#12685]
### NetBox version

v3.5.2

### Python version

3.8

### Steps to Reproduce

1. Create a custom field with a description that uses markdown
2. Assign that custom field to an object type
3. Create an object of that type
4. Edit that object

### Expected Behavior

Description below custom field should render markdown.

### Observed Behavior

Markdown not rendered.

I have a PR ready for this one.

**Comment by abhi1693** [comment]
I think the fix you have will not only affect custom field description but any other field that relies on `render_field`. I don't think that would be the intended fix for this issue.

**Comment by decoupca** [comment]
Would passing a field's help text through the markdown filter incur some unintended side effect? In any case, seems like supporting markdown on all help texts is the direction we want to go?

**Comment by jeremystretch** [comment]
> Would passing a field's help text through the markdown filter incur some unintended side effect?

Potentially. We should expect that all native `help_text` strings may contain HTML, so we should avoid processing them as Markdown.

> In any case, seems like supporting markdown on all help texts is the direction we want to go?

No; we should only support Markdown for user-sourced content. (Anything built-in will just use HTML directly.)

**Comment by decoupca** [comment]
> Potentially. We should expect that all native help_text strings may contain HTML, so we should avoid processing them as Markdown.

Ah, I see.

Do I then understand correctly that there is not currently a clear path forward to fixing this bug? Sounds like to target only user-sourced content we would need to separate the field rendering templates.
