### ISSUE TITLE
Improve user experience when adding cables: restore previous selection behaviour

### ISSUE THREAD

**Issue by martinum4** [netbox-community/netbox#12704]
### NetBox version

v3.5.2

### Feature type

Change to existing functionality

### Proposed functionality

Use Rack and Location as default search filters again when adding cables (restore old behaviour)

### Use case

When adding cables between devices via the NetBox Web-Interface (especially on mobile) there are more steps required than pre v3.5, which makes the experience not as fast, especially in bigger environments.

### Database changes

Probably none

### External dependencies

Probably none

**Comment by jeremystretch** [comment]
Thank you for your interest in extending NetBox. Unfortunately, the information you have provided does not constitute an actionable feature request. Per our [contributing guide](https://github.com/netbox-community/netbox/blob/develop/CONTRIBUTING.md), a feature request must include a thorough description of the proposed functionality, including any database changes, new views or API endpoints, and so on. It must also include a detailed use case justifying its implementation. If you would like to elaborate on your proposal, please modify your post above. If sufficient detail is not added, this issue will be closed.

**Comment by martinum4** [comment]
What kind of revisions are needed?

This was the old behaviour:
![grafik](https://github.com/netbox-community/netbox/assets/18295403/58fbc87b-5964-49e0-b7af-de4af7ad8224)
(Screenshot from https://youtu.be/b-H-tSlZmZA?t=453 )
Rack and Site were preselected as search filters.

This is the current behaviour:
![grafik](https://github.com/netbox-community/netbox/assets/18295403/4552a7c4-7725-4723-ac78-d0e23a7b21c3)
No Rack or Site are preselected as filter

This FR proposes to add these filters as default again.

**Comment by jeremystretch** [comment]
While we welcome suggestions to improve the experience, we will not be reverting this intentional change. The new selection mechanism was added to provide much more advanced functionality while greatly simplifying the cable creation form. If you would like to propose _specific improvements_ to the new selection mechanism, you are welcome to do so by opening a new feature request.

**Comment by martinum4** [comment]
Ah, that explains it, i didn't know this was intentional and thought it just was forgotten to add back in when changing to the new form
