### ISSUE TITLE
Improve user experience when adding cables: Extend Search

### ISSUE THREAD

**Issue by martinum4** [netbox-community/netbox#12705]
### NetBox version

v3.5.2

### Feature type

Change to existing functionality

### Proposed functionality

Make the search field when selecting devices for adding cables consider the Netbox internal IDs too.
Currently:
![grafik](https://github.com/netbox-community/netbox/assets/18295403/e3ab679d-b849-482f-9ff9-ec1738bb6f79)
Proposed:
![grafik](https://github.com/netbox-community/netbox/assets/18295403/6eeba120-12c4-4d9b-a14a-d942e0b0f9c9)

### Use case

When adding cables between devices via the NetBox Web-Interface (especially on mobile) there are more steps required than pre v3.5, which makes the experience not as fast, especially in bigger environments.

This FR aims to improve the handling of unnamed devices and help people that remember stuff via IDs

### Database changes

Probably none

### External dependencies

Probably none

**Comment by PaulR282** [comment]
I started a discussion for enhancing the search. Have a look at #12695
