### ISSUE TITLE
Changelog view "Difference" of custom_fields shouild only show changed custom_fields instead of the whole dict "changed"

### ISSUE THREAD

**Issue by MalfuncEddie** [netbox-community/netbox#12709]
### NetBox version

v3.3.5

### Feature type

Change to existing functionality

### Proposed functionality

When a custom field is changed the changelog shows the entire dict of custom_fields is marked as changed. This is correct but it would be nice to have a diff of the custom_fields instead of the whole updated dict.

Work around is copy paste the dicts to https://www.jsondiff.com/

### Use case

When having a lot of custom_fields it is not quite visible what has been changed. 

### Database changes

None

### External dependencies

None,

**Comment by abhi1693** [comment]
This seems like it's captured by https://github.com/netbox-community/netbox/issues/10924, which proposes the same idea but for the entire diff body.
