### ISSUE TITLE
"Connection" column does not shows other end through 2 patch panels, also when tracing it does stop on the second panel

### ISSUE THREAD

**Issue by jmacias-packet** [netbox-community/netbox#12712]
### NetBox version

v3.3.7

### Python version

3.8

### Steps to Reproduce

1. Create switch A
2. Create patch panel 1
3. Create patch panel 2
4. Create switch B
5. patch switch A - port 1 -> patch panel 1 - Front port 1A
6. patch patch panel 1 - Rear port 1A to patch panel 2 - Rear port 1a
7. patch patch panel 2 - Front port 1A to switch B - port 1

Click Trace either from switch A port 1 or switch B port 1

### Expected Behavior

I should see a full trace of the link, as it happens when there is only 1 patch panel in between.

### Observed Behavior

Some times shows "Patch split" at the bottom, then you choose the cable and it shows full trace correctly, but when you click trace again it happens again. Other times it just shows from switch A port 1 to the second patch panel and thats' it, it should show the full patch between both switches.
It never shows the "connection" info, just after "cable", as it does when you patch straight between switches or only through 1 patch panel.
![Screenshot 2023-05-25 at 14 18 33](https://github.com/netbox-community/netbox/assets/69234931/daf6c015-e9a8-4096-a62c-1f1e28ebc30b)
From the screenshot, you can see ethernet49/1 and 50/1 wrong, and 51/1 correctly working.

**Comment by jmacias-packet** [comment]
Another example is connecting to a circuit through 1 patch panel, it does trace correctly from the interface on the device but it does not show anything in "Connection" column.

**Comment by Tene-brious** [comment]
I had to do something similar to this, feel free to correct me if I'm wrong but I did the following: Created two switches and two patch panels. From there - Switch 1 - Gi1(Interface) connected to 1(Rear Port) of Panel 1 followed by 1(Front Port) of Panel 1 connects to 1(Rear Port) of Panel 2. This ends with Switch 2 - Gi1(Interface) connecting to 1(Front Port) of Panel 2. I can see the whole trace. 

![image](https://github.com/netbox-community/netbox/assets/128482272/6e2eb013-9d15-4017-a2b4-4cf41cf8d348)

Not sure if this is exactly what you tried to highlight or not but I was having the same issue and then realized it was Layer 8 problem (me configuring)

**Comment by Tene-brious** [comment]
No, because as I was saying it was an issue on my side. I was able to replicate something similar and I can see the whole _trace_ of the cables I connected. I changed the names so it is a bit more clear but I tried to change the order in which the panels connect to see if the bug happened but it works as it should.

![image](https://github.com/netbox-community/netbox/assets/128482272/89fd2b81-b8af-4fb6-9307-bcc51280a3ea)

**Comment by jmacias-packet** [comment]
What NB version you using?

**Comment by Tene-brious** [comment]
v3.5.2

**Comment by jmacias-packet** [comment]
Hi Tene, I upgraded to 3.5.3 version and tried it again, it is weird because from switch A to switch B, it traces well when at A side, but from 4 or 5 tests I did, 1 of them does not show well a
![Screenshot 2023-06-09 at 14 00 48](https://github.com/netbox-community/netbox/assets/69234931/fc7a6f23-a878-4e3d-a8a9-ab5c9a779f15)
![Screenshot 2023-06-09 at 14 00 41](https://github.com/netbox-community/netbox/assets/69234931/734ba60b-3916-4ecb-8199-2549a7379568)

t B side, I mean, it does not show the Connection and trace shows a split, see a couple of screenshots.
I followed the sense of switch A - front | rear -> rear | front -> switch B.

**Comment by Tene-brious** [comment]
I see, you're able to see the initial part of the trace but it does not show where it ends for you being from the front-port of the second patch panel to the second switch, is that what the problem is? Have you tried using a copper cable as a termination (at switch B)? I find it very odd that this does not work for you :/

**Comment by jmacias-packet** [comment]
Let me try but should be the same and we use fiber, there must be a bug because doing the same way for all 4 connections, that one is not working properly :(
No one from netbox replied or acknowledged this report yet..

**Comment by Tene-brious** [comment]
I agree it should function exactly the same with fiber or copper connection. Just found it weird that I am not able to replicate this again on my end. Have you tried creating a separate rack with only 4 equipments to test this out?
You can always create a thread on slack (which is where I usually hang around and ask whenever I'm in doubt) to see if anyone else has this issue and maybe they can help.

**Comment by jmacias-packet** [comment]
Hello Tene-brious, do you have the slack link? Maybe asking there will be quicker to get a reply from them.
Thank you

**Comment by Tene-brious** [comment]
https://join.slack.com/t/netdev-community/shared_invite/zt-1xg6cjhvn-ICQUUJTSQgWgjxLczd4CwQ thought you had joined already but here you go!
Have a nice weekend

**Comment by jmacias-packet** [comment]
Thank you! Have a wonderful one!
