### ISSUE TITLE
Custom field type object 2way visibility

### ISSUE THREAD

**Issue by kirillmuravyev** [netbox-community/netbox#12711]
### NetBox version

v3.5.2

### Feature type

Data model extension

### Proposed functionality

Hi All.
I was playing with custom fields a little bit and noticed interesting thing that might be useful to implement.
I have creates a custom field with type "object" in "dcim -> device", object type is "virtual machine".
So I want to link some devices to virtual machines.
BTW, there is no way to model virtual network devices deployed on cloud VMs, when you have a virtual machine in cloud and network device software deployed on it. And we treat those things differently, vurtual machine itself is supported by one team, but virtual network device installed on that machine is supported by another team.
That is why I want to link device and virtual machine together.

So, when I did the above relation, I can open device and link it to virtual machine, but from the virtual machine perspective I do not see that relation.

I think would be good to see that relation automatically if I reference object in custom field. Otherwise you have to create 2 custom fields and maintain them in order to track it from both sides

### Use case

Ability to see that specific instance of object is referenced by another one with custom field.

**Comment by jeremystretch** [comment]
Thank you for your interest in extending NetBox. Unfortunately, the information you have provided does not constitute an actionable feature request. Per our [contributing guide](https://github.com/netbox-community/netbox/blob/develop/CONTRIBUTING.md), a feature request must include a thorough description of the proposed functionality, including any database changes, new views or API endpoints, and so on. It must also include a detailed use case justifying its implementation. If you would like to elaborate on your proposal, please modify your post above. If sufficient detail is not added, this issue will be closed.
