### ISSUE TITLE
Switch and Patch Panel Diagrams 

### ISSUE THREAD

**Issue by opensourcefan** [netbox-community/netbox#12728]
### NetBox version

v3.5.2

### Feature type

Data model extension

### Proposed functionality

It seems as though we have all the data present to create a very informative diagram depicting port mapping for our switches and patch panels.

Simply just horizontal tables with labels for connections. Maybe even have a mechanism to sort the device stacks and show connections. 

### Use case

It will provide a visual into our switch port assignments as well as connections, ie to patch panel. 

Can be printed and used as a log or template for reconfiguring etc.

**Comment by abhi1693** [comment]
This seems like a good candidate for a plugin IMO.

**Comment by jeremystretch** [comment]
Agreed. Please feel free to submit your idea to the [NetBox plugin ideas board](https://plugin-ideas.netbox.dev/). However, I'll caution that you'll need to provide _much_ more detail about the proposed implementation if you want to attract interest.

**Comment by peterbaumert** [comment]
@opensourcefan I built fast a alpha like plugin over here https://github.com/peterbaumert/netbox-device-view
you can have a look if this seems promising to you and leave feedback or even help :D
