### ISSUE TITLE
Parent Child Tenant Hierarchy

### ISSUE THREAD

**Issue by wirestar** [netbox-community/netbox#12727]
### NetBox version

3.4.3

### Feature type

New functionality

### Proposed functionality

We would like to add the parent field on tenant creation, and be able to select another tenant as the parent. 

Other records, like regions, and locations have this similar parent field that "can be nested recursively to construct a hierarchy" functionality. 

### Use case

A tenant is considered a customer for us. Our accounting and billing systems allow for parent and child relationships for customers. 
I am aware of tenant groups, and those have the parent field to select another group, but this is not quite the same. This is a grouping of tenants, but doesn't show the hierarchy or relationship of tenants.

### Database changes

Unknown 

### External dependencies

Unknown

**Comment by abhi1693** [comment]
I'm not sure if this will be accepted but this will be blockde until https://github.com/netbox-community/netbox/issues/12552 is resolved.

**Comment by jeremystretch** [comment]
You haven't explained your use case. NetBox provides for [contact assignments](https://docs.netbox.dev/en/stable/features/contacts/) where separate points of contact must be tracked within a tenant. Can you provide an example where this would not be sufficient?

**Comment by wirestar** [comment]
@jeremystretch I am not understanding how contact assignments would show the hierarchies and relationships between tenants? Can you explain as I might be overlooking something?

"A contact represent an individual" person whereas "tenants are used to represent individual customers or internal departments within an organization" according to the NetBox documentation. 

Most of the large CRMs like Salesforce or ERPs have the concept of a tenant being a customer, and an employee working at the customer being a contact linked to that customer or vendor.

Our use case would be to have our existing CRMs and ERPs integrated to NetBox. So when a parent customer is created in the CRM or ERP, it syncs to NetBox using the API. If a child record is created, it pushes that as well also showing the parent as it does in the CRM or ERP. 

Some areas of NetBox support this concept today such as regions and locations, but then other sections don't but allow a parent to be define but instead have groups (tenants and sites for example). Why is there a difference between these object types?
