### ISSUE TITLE
New model for High Availability clusters

### ISSUE THREAD

**Issue by kirillmuravyev** [netbox-community/netbox#12737]
### NetBox version

v3.5.2

### Feature type

Data model extension

### Proposed functionality

Some network devices (e.g. firewall) supports HA cluster setup which is different to virtual chassis as they do not share the chassis.

Proposal is to add new data model to properly document HA network device clusters and their modes (Active/Passive; Active/Active)
Within the cluster devices usually share the same configuration with some exceptions,
Within HA cluster device do not share chassis and interfaces are not stacked like with switch stack.

### Use case

Any network device HA cluster (Palo Alto, Cisco ASA, CheckPoint) works different to virtual chassis

**Comment by abhi1693** [comment]
Thank you for your interest in extending NetBox. Unfortunately, the information you have provided does not constitute an actionable feature request. Per our [contributing guide](https://github.com/netbox-community/netbox/blob/develop/CONTRIBUTING.md), a feature request must include a thorough description of the proposed functionality, including any database changes, new views or API endpoints, and so on. It must also include a detailed use case justifying its implementation. If you would like to elaborate on your proposal, please modify your post above. If sufficient detail is not added, this issue will be closed.
