### ISSUE TITLE
Failed to load API definition

### ISSUE THREAD

**Issue by kirillmuravyev** [netbox-community/netbox#12736]
### NetBox version

v3.5.2

### Python version

3.8

### Steps to Reproduce

1. From NetBox URL click "REST API Documentation"

### Expected Behavior

Opened API docs

### Observed Behavior

![image](https://github.com/netbox-community/netbox/assets/40544508/a09ded8d-68ae-4cef-a443-dc0f6731651d)

**Comment by kkthxbye-code** [comment]
You did not provide proper replication steps. It seems likely that this is the issue: https://github.com/mattieserver/netbox-topology-views/issues/295

Disable that plugin and try again. I'll close this as there's nothing to do with this little info.

**Comment by kirillmuravyev** [comment]
How could this be related to that plugin if I am trying to open API docs page?
This was working before I upgraded to version 3.52 from 3.4.8, with topology views plugin installed.
We use that plugin. so disabling it is not a solution for us

**Comment by kkthxbye-code** [comment]
The api docs is dynamic, it shows API endpoints from plugins as well.

> We use that plugin. so disabling it is not a solution for us

I'll link it again. This is where to take your feedback: https://github.com/mattieserver/netbox-topology-views/issues/295

**Comment by kirillmuravyev** [comment]
ok, got it
thank you @kkthxbye-code  !
