### ISSUE TITLE
Add Hide/Show Connected to Device Interface Summary Filter

### ISSUE THREAD

**Issue by stuntguy3000** [netbox-community/netbox#12732]
### NetBox version

v3.5.1

### Feature type

Change to existing functionality

### Proposed functionality

I'd love to see an option here to Hide/Show interfaces that are **connected**.

![image](https://github.com/netbox-community/netbox/assets/1522389/c5b3bd5e-dab4-4ebb-aac4-57bec3ce01b3)

### Use case

Makes it easier to summarize the connections a device's interfaces have at a glance, especially when the connected interfaces are buried into other pages.

### Database changes

None

### External dependencies

None

**Comment by stuntguy3000** [comment]
This FR should not be stale, I'm willing to implement it once it is approved.

**Comment by bitcollector1** [comment]
I approve, nice change :)
