### ISSUE TITLE
Device --> "Assign IP" befor "Add a new IP address"

### ISSUE THREAD

**Issue by LHBL2003** [netbox-community/netbox#12735]
### NetBox version

V3.5.2

### Feature type

Change to existing functionality

### Proposed functionality

Navigating to:
- devices
- Select device with an interface
- Plus icon to add IP address to the device.

Very often the IP address has already been created before the device is created.

You always have to change the tab to first check whether you already have an IP address.

I and others working on the system should always check whether an IP address already exists before creating a new IP address. This avoids errors in the documentation.

Newcomers always create a new IP first because this is the focus.

But that's not particularly great.

![image](https://github.com/netbox-community/netbox/assets/46369917/446e3ee7-0c18-4e7d-8562-0fb50b5347fe)

### Use case

- Less false documentation.
- An intuitive user guide through the Netbox system.

**Comment by bitcollector1** [comment]
I made this same recommendation over in the slack channel and got some pushback. Making it user configurable options we be great balance!

**Comment by ITJamie** [comment]
I would also agree on this. we have ended up with duplicate ip objects (usually an additional incorrect one set in the global vrf) because of this flow. if assign was the default (or a new view was made where you search first then create new if not exists) it would reduce these errors

**Comment by LHBL2003** [comment]
Even though I would still like to see the tab order adjusted. I would like to recommend this parrameter to everyone who is struggling with the same problem. Because I had to delete 300 duplicate IP addresses again today.

This prevents duplicate (dead / incorrect) addresses being found everywhere.

https://demo.netbox.dev/static/docs/configuration/dynamic-settings/#enforce_global_unique
https://github.com/netbox-community/netbox/issues/14492
![image](https://github.com/netbox-community/netbox/assets/46369917/aa0f47b9-4a0d-4cca-9ea8-6407b789a4a2)
