### ISSUE TITLE
Custom validators unable to validate tag presence 

### ISSUE THREAD

**Issue by stuntguy3000** [netbox-community/netbox#12731]
### NetBox version

v3.5.1

### Python version

3.10

### Steps to Reproduce

1. Set the Custom Validators setting to validate tag requirements
```
CUSTOM_VALIDATORS = {
        "ipam.ipaddress": [{"tags": {"required": True}}],
        "dcim.site": [{"tags": {"required": True}}],
        "dcim.region": [{"tags": {"required": True}}]
}
```
2. Create a new object defined in the list above with/without tags defined.

_(This error is not exclusive to those object types)_

### Expected Behavior

I expected NetBox to validate if that particular object has tags set.

### Observed Behavior

```
<class 'ValueError'>

IPAddress objects need to have a primary key value before you can access their tags.

Python version: 3.10.6
NetBox version: 3.5.1
```

I'm not sure if I'm asking too much from the Custom Validators here, or if another method to enforce the existence of Tags is available.

**Comment by netopsab** [comment]
Hi,

This is the only way I have found to catch tags (or other m2m fields) with CustomValidator :

```
from netbox.context import current_request
from extras.models import Tag

request = current_request.get()
tags = Tag.objects.filter(id__in=request._post.getlist('tags')).values_list('name', flat=True)
```

Note : this is for the 'standard' edit form. For bulk edit (or import form), you have to dig with other fields (like add_tags, remove_tags) and check the view name before (with object `request.resolver_match.view_name`).

```
from extras.models import Tag

tags = set(instance.tags.names()).union(
    Tag.objects.filter(id__in=post.getlist('add_tags')).values_list('name', flat=True)
).difference(
    Tag.objects.filter(id__in=post.getlist('remove_tags')).values_list('name', flat=True)
)
```

Hope this can help you.

**Comment by arthanson** [comment]
@Urth stated he wanted to work on this.

**Comment by Urth** [comment]
yes, please assign it to me :+1:

**Comment by jeremystretch** [comment]
@Urth have you been able to make any progress on this?
