### ISSUE TITLE
locations view - request for link to "View Elevations" on single location view

### ISSUE THREAD

**Issue by ITJamie** [netbox-community/netbox#12748]
### NetBox version

v3.5.2

### Feature type

restore old functionality

### Proposed functionality

on a location (eg a row) with no child locations. there is no link to view elevations of that location. in previous versions there was a "view elevations" button to the right of the rack count, which was on the left hand side list. this was lost when the list of object types was moved to the right

eg: https://demo.netbox.dev/dcim/locations/1/
this location has 8 racks but theres no single click way to get from the location to the elevation of this location.

### Use case

Single click link from a single location view to elevations view

**Comment by ITJamie** [comment]
older versions view elevations link
![previous view elevations link](https://github.com/netbox-community/netbox/assets/1613241/05361335-0ddd-4950-a05c-5760a772f672)

**Comment by DrumSlayers** [comment]
+1, It was easy & fast.
Now it requires additional client actions.

**Comment by ITJamie** [comment]
I am willing to make a pr for this if its accepted

**Comment by jeremystretch** [comment]
@ITJamie where are you proposing a link be added? As I mentioned on PR #12834, it would not be appropriate to add it as an object action button. (A modified screenshot showing your intended design may be helpful.)

**Comment by ITJamie** [comment]
I have attempted to make a version of this where it puts an extra button in the related_objects row on the rack item. However my CSS skills are lacking, any attempt to add another button inline ether creates the button after the rack row.

<img width="1510" alt="Screenshot 2023-10-22 at 16 34 20" src="https://github.com/netbox-community/netbox/assets/1613241/aa4f9c01-a7d4-445e-8888-aa3914d6663e">

so above I quickly added it to the "location" object list as an idea. (also note the broken attempt at adding an inline elevations button on the related_objects list due to CSS)
