### ISSUE TITLE
Add manufacturer to platform of virtual machines

### ISSUE THREAD

**Issue by kirillmuravyev** [netbox-community/netbox#12741]
### NetBox version

v3.5.2

### Feature type

Data model extension

### Proposed functionality

Add "manufacturer" field before "platform" selection inside virtual machine configuration

### Use case

Currently, when you create a device you should choose it's vendor and platform, and drop down list of platform filters to that vendor.
With that approach you can create platforms as software versions with specific manufacturer.

But when you choose platform for virtual machine it is one list which becomes confusing without vendor

### Database changes

Add field "manufacturer" to Virtualization -> Virtual Machine to filter platforms

**Comment by jeremystretch** [comment]
This can be addressed by enabling the object selector widget for the platform field. This should be done for the device model as well.

**Comment by kprince28** [comment]
Can you please assign this to me ?
