### ISSUE TITLE
autofocus on netbox search bar on dashboard page

### ISSUE THREAD

**Issue by ITJamie** [netbox-community/netbox#12749]
### NetBox version

v3.5.2

### Feature type

New functionality

### Proposed functionality

when netbox loads it would be great if the netbox search box had autofocus enabled on the dashboard page.

that way when a user loads the netbox default page url, they can instantly start searching for objects without having to tab to or click into the search box.

### Use case

user accessability / ease of use adjustment

**Comment by PieterL75** [comment]
I once submitted the same FR https://github.com/netbox-community/netbox/issues/7839 and took a shot at the implementation.
But having the focus there, is not very practical when being on an edit form, then de focus should be on the main field..
that logic was very hard to handle (for me at least)

**Comment by ITJamie** [comment]
I think it should only have the autofocus flag if it is on the dashboard page

**Comment by abhi1693** [comment]
Instead of auto-focusing, we can add a way that when you hit `/` on your keyboard, the search comes into focus. This will avoid making too much logic of when it should or should not be in focus. You can test this feature via GitHub as well to get a taste of this. :)

**Comment by PieterL75** [comment]
Now that sounds like an excellent idea !
can you submit the FR? I got a feeling that if your name is in the request, it is pickup up better by the maintainers

**Comment by yash-pal1** [comment]
assign to me

**Comment by goteamkor** [comment]
please don't close. There is certainly value in being able to quickly jump to the global search via keyboard shortcut.
