### ISSUE TITLE
Improve URL type custom field

### ISSUE THREAD

**Issue by OliElli** [netbox-community/netbox#12756]
### NetBox version

v3.5.1

### Feature type

Change to existing functionality

### Proposed functionality

Extending https://github.com/netbox-community/netbox/issues/7118

I would like a markdown style "display name" for a URL, Eg:

Current field:
http://example.com/a-very-long/link/that/makes/things/look/messy?in_the_ui

Proposed field:
`[nice text](http://example.com/a-very-long/link/that/makes/things/look/messy?in_the_ui)`

That renders like this:
[nice text](http://example.com/a-very-long/link/that/makes/things/look/messy?in_the_ui)

### Use case

Makes the URL custom field look neater

**Comment by DanSheps** [comment]
https://docs.netbox.dev/en/stable/reference/markdown/#links  This appears to be already implemented with the base markdown.  If it is not working, please open a bug report.

**Comment by DanSheps** [comment]
Seems reasonable, not sure how the best way to implement this would be.

Might be easier to allow markdown rendering in a regular text field to allow for this and not worry about the URL field.  It looks like long text you can already render a markdown URL.

**Comment by stavr666** [comment]
> It looks like long text you can already render a markdown URL

It works in demo:
![image](https://github.com/netbox-community/netbox/assets/84839985/09511cb9-b036-4845-a97a-f4b65bf910c2)

**Comment by OliElli** [comment]
So it does! I'll use that field then and close this.

**Comment by DanSheps** [comment]
It might still be worth it adding markdown to the "Text" custom field type, if you desire that, feel free to open up a FR for that.
