### ISSUE TITLE
Add further filter for custom field with type "date"

### ISSUE THREAD

**Issue by martinum4** [netbox-community/netbox#12752]
### NetBox version

v.3.5.2

### Feature type

Change to existing functionality

### Proposed functionality

Using Django low-level-filter-options is not for everyone and can get confusing and doesn't have an integrated function to compare to today (that I'm aware of)

Example: it's the 01.01.2023, we have devices A-B with the following custom field "warranty_end":
A 2022-12-01
B 2023-02-28

A filter proposed by this FR finds all devices where the date is already in the past or due in the next X days. e.g.: X=90 finds devices A and B

This seems not to be covered with #7604 since one would have to manually define today every time when accessing the filters mentioned there.

### Use case

- Have a list of devices that require a warranty renewal/compliance-check
- Track UPS Battery-Replacement
- further extend the function of device lists and counts with the upcoming changes of #12742  

### Database changes

None expected due to all being django filtering.

### External dependencies

None expected due to all being django filtering.

**Comment by martinum4** [comment]
I am willing to set out a bounty of 10€ for this feature if anyone wants to implement it, is there a issue bounty entity that NetBox is working with?

**Comment by jeremystretch** [comment]
Closing as stale
