### ISSUE TITLE
Detailed view of Tenants show unrelated contacts

### ISSUE THREAD

**Issue by jbakklund** [netbox-community/netbox#12763]
### NetBox version

v3.5.2

### Python version

3.9

### Steps to Reproduce

1. Create some sites, tenants, and contacts.
2. Ensure that there are no contacts assigned to tenant number 1 at /tenancy/tenants/1/contacts/
3. Add contacts to site number 1 at /dcim/sites/1/contacts/
4. Navigate to /tenancy/tenants/1/contacts/

### Expected Behavior

No contacts should be listed.

### Observed Behavior

All contacts related to Site-ID 1 are listed under Tenant-ID 1.

**Comment by jbakklund** [comment]
Looks like the same Contacts related to a specific Site-ID are misinterpreted as contacts for Circuit Provider with Provider-ID equal to the Site-ID.

**Comment by abhi1693** [comment]
Duplicate of #12730
