### ISSUE TITLE
Uploading a report with syntax error prevent access to report section and cannot delete it

### ISSUE THREAD

**Issue by kawalex** [netbox-community/netbox#12771]
### NetBox version

v3.5.2

### Python version

3.9

### Steps to Reproduce

1. Upload a new report with inconsistent use of tabs and spaces in indentation error
2. Try to access to report menu in customization section.

### Expected Behavior

We expect to see list of report to delete the faulty one

### Observed Behavior

Get a Server Error page stating:
 There was a problem with your request. Please contact an administrator.

The complete exception is provided below:

<class 'TabError'>

inconsistent use of tabs and spaces in indentation (netbox-report-test.py, line 14)

Python version: 3.10.6
NetBox version: 3.5.2

**Comment by jeremystretch** [comment]
Merging this into #12842.
