### ISSUE TITLE
Make NetBox views not dependent on NetBox models and RestrictedQuerySet

### ISSUE THREAD

**Issue by arthanson** [netbox-community/netbox#12796]
### Proposed Changes

Currently if you use generic.ObjectListView (and probably the bulk edit views) there are assumptions in the view code that the models are derived from NetBox models and using the RestrictedQuerySet.  See: https://github.com/netbox-community/netbox/blob/develop/netbox/utilities/views.py#L82

### Justification

This change would allow any model to use ObjectListView and the other bulk import views.  This issue was a blocker for moving the User and Group admin into NetBox as those models are not derived from NetBox models.

**Comment by DanSheps** [comment]
@arthanson 

Can you not use a proxy model to handle this or could we not use just a regular views.View?  I think the whole point of "ObjectView" "ObjectListView" is that they are tied to an Object (Model) so removing this sort of defeats the purpose of the view itself.

I think a BaseView/BaseListView might be nice, but I don't think we should go mucking with the ObjectListView/ObjectView directly as they are also directly usable by plugins.

**Comment by abhi1693** [comment]
Here is an implementation that I did one weekend, if you want to refer: https://github.com/Onemind-Services-LLC/netbox-users/tree/dev
