### ISSUE TITLE
Unable to assign last IPv6 address in /127 or /128 subnet to an interface

### ISSUE THREAD

**Issue by matejv** [netbox-community/netbox#12798]
### NetBox version

v3.5.2

### Python version

3.10

### Steps to Reproduce

(Following up from #12687)

1. Navigate to device interface
2. Click "Add IP address"
3. On "Add a new IP address" form set Address: 2001:db8::1/127 and click Create

### Expected Behavior

A new IP Address object for 2001:db8::1/127 should be created and assigned to interface.

### Observed Behavior

An error is shown:

2001:db8::1/127 is a broadcast address, which may not be assigned to an interface. 

Additional notes:

This affects IPv6 /127 and /128 subnets. For IPv4 /31 and /32 subnets you are able to assign all addresses in the subnet to an interface.

**Comment by jeremystretch** [comment]
@decoupca said:

> If you have a confirmed failure of assigning a /31 address, open a bug report with full details on how to reproduce.

That is not what your description above entails.
