### ISSUE TITLE
When using XSS in Wireless LANs, a displaying errors occurs

### ISSUE THREAD

**Issue by StackNeverFlow** [netbox-community/netbox#12797]
### NetBox version

v3.5.0

### Python version

3.8

### Steps to Reproduce

1. Create Wireless LAN with name/SSID of `<svg/onload=alert(1)>`
2. Going to add a new Wireless Interface to a device
3. Click on `Select Wireless LANs`

### Expected Behavior

Expected to see the name `<svg/onload=alert(1)>`

### Observed Behavior

A "blank box" is shown.

<img width="459" alt="1685660492dkF9BDxCleZO0dThK54ubfYWo8s6ZYT0vxUPKmTlyHkr9DV8" src="https://github.com/netbox-community/netbox/assets/50374560/73814921-9d8b-4f7a-b7b1-debb5f5e866a">

**Comment by StackNeverFlow** [comment]
_Addendum_

Image of the dialog box, when I selected the SSID.

<img width="448" alt="1685661116Lv2QWsXC68FmOM683g6fo0joyRTgX4Q6pBbcl5IDsYIFVDwx" src="https://github.com/netbox-community/netbox/assets/50374560/7cc1760f-8bd4-466d-89e0-e768481d472d">

**Comment by kkthxbye-code** [comment]
Duplicate of https://github.com/netbox-community/netbox/issues/12745

Please remember to search before opening an issue.
