### ISSUE TITLE
sort journal entries also by object

### ISSUE THREAD

**Issue by opericgithub** [netbox-community/netbox#12802]
### NetBox version

v3.5.2

### Feature type

Change to existing functionality

### Proposed functionality

The only two columns in journal entries table, which are not sortable, are "Object" and "Tags". Is there any particular reason for this behaviour? I don't see any obstacle to make these two columns also sortable.

### Use case

We use journal entries table as a form of to-do reminder. In fact, this is the list of preparation tasks and activities that are to be done by our technicians before and when they visit any of our multiple sites. Here is an example:

![image](https://github.com/netbox-community/netbox/assets/65983735/61c60710-db83-4d3c-b7af-d6cf9b46fdd0)

The above list is sorted randomly, but we would like to be able to sort it by object column (in this case the particular site), so all activities for one site would be listed in one place (one group). like this:

![image](https://github.com/netbox-community/netbox/assets/65983735/df48234f-e7b2-47b6-904c-61e58e28c124)

In this way, all the to-do activities for one site would be grouped into one or more consecutive rows.

**Comment by kkthxbye-code** [comment]
> Is there any particular reason for this behaviour? I don't see any obstacle to make these two columns also sortable.

Yes, the ordering is done in the database and Object being a generic foreign key, it's not possible to order them when selecting from the extras_journalentry. The display value, which is what you want to order by, is fetched after the journal entries are fetched and is generated in python code. Ordering after quering data does not work as pagination would make it inconsistent.

So in short we currently have no way to do what you are requesting.

**Comment by jeremystretch** [comment]
Closing this out as the proposal does not appear to be feasible, and no solution has been offered.
