### ISSUE TITLE
Config context added to all devices without assignment

### ISSUE THREAD

**Issue by MarianRychtecky** [netbox-community/netbox#12800]
### NetBox version

v3.5.1

### Python version

3.9

### Steps to Reproduce

1. Create config context under Provisioning with no assignments
![image](https://github.com/netbox-community/netbox/assets/36925394/c5eb2216-da7e-4d6a-987d-013fa8806337)
2. Every device has a newly created context shown under "Config Context" and "Rendered Context"
3. Disabling config context will remove config context from all devices

### Expected Behavior

Do not show Config context on the device without the assignment

### Observed Behavior

Displayed with every device, even without assignment

**Comment by kkthxbye-code** [comment]
I'm pretty sure this is intended, and as such should be a feature request. However even as a feature request I'm not sure I see why it should be changed.

**Comment by MarianRychtecky** [comment]
I understand what you mean. But how can I create a "Config context" not assigned to any device?

**Comment by kkthxbye-code** [comment]
Just remove the checkmark from "Is active" and it wont render for any devices.

**Comment by kkthxbye-code** [comment]
It makes decent sense to me and is explained in the documentation:

https://docs.netbox.dev/en/stable/models/extras/configcontext/

>**Object Assignment**
Each configuration context may be assigned with any number of objects of the supported types. **If no related objects are selected, it will be considered a "global" config context and apply to all devices and virtual machines.**

As this is intended I'll close this out, but you are welcome to open a feature request. Just make sure you specify exactly what changing this would solve and why it would be a positive change.
