### ISSUE TITLE
Error while trying to bulk import modules after deleting them ( I mean modules that had the same values) 

### ISSUE THREAD

**Issue by roys10** [netbox-community/netbox#12819]
### NetBox version

v3.3.4

### Python version

3.10

### Steps to Reproduce

1. create a module
2. delete it
3. try to create the same module with bulk import

### Expected Behavior

A new module attached to the given device and module bay is created.

### Observed Behavior

Server Error -  <class 'django.db.utils.integrityError'>

duplicate key value violates unique constraint "dcim_interface_device_id_name_bffc4ec4_uniq"
DETAIL: Key (device_id, name)=(<an id>, <interface name>) already exists.

**Comment by kkthxbye-code** [comment]
Cannot replicate this on 3.5.3. The replication steps are missing the csv or json for the import as well. The replication steps are also missing creation instructions for the objects in use.

This is such a long way from being an actionable bug report that I'll close it. Feel free to edit it with proper replication steps for the current version of netbox and ping me, then I'll re-open it.

**Comment by roys10** [comment]
> Cannot replicate this on 3.5.3. The replication steps are missing the csv or json for the import as well. The replication steps are also missing creation instructions for the objects in use. Also it seems like you edited the error message.
> 
> This is such a long way from being an actionable bug report that I'll close it. Feel free to edit it with proper replication steps for the current version of netbox and ping me, then I'll re-open it.
> 
> What is likely happening here is that when deleting the module for some reason you didn't remove all the interfaces on the device, causing one of the interfaces that the module provides still being present on the target device.

Hey sorry about the poor replication steps. I checked to see if after I deleted the modules there were still interfaces of the module, but there aren't any.
