### ISSUE TITLE
Hide plugin models from widgets if desired

### ISSUE THREAD

**Issue by dreng** [netbox-community/netbox#12810]
### NetBox version

v3.5.4-dev

### Feature type

Change to existing functionality

### Proposed functionality

Please implement a parameter for plugin models in order to make them hide from widgets' config. Something like:

```
class Meta:
    widget = False
```

### Use case

It turned out that a misconfiguration within a widget may render NetBox unusable. See #12520. In this case a user tried to create a widget that contains a model from the NetBox Topology Views Plugin. This model has never been intended to be listed or counted. It has only one special custom view and no list view.

Adding this model will result in an error. As a result, no page can be opened any more. It is not exactly a bug, but it looks like one to the user.

Implementing the proposed parameter let plugin developers prevent this misconfiguration.

Another Solution would be to check if the model supports being counted before it shows up in the widget configuration. I don't know if that would be an easier way.

### Database changes

None

### External dependencies

None that I am aware of.

**Comment by jeremystretch** [comment]
> This model has never been intended to be listed or counted. It has only one special custom view and no list view.

This touches on the recurring theme of "public" vs "private" models in NetBox. We don't have a good solution for this currently.

**Comment by jeremystretch** [comment]
I think this will be captured under #13427, so let's capture any further conversation related to this use case under that issue.
