### ISSUE TITLE
remove add button if not needed.

### ISSUE THREAD

**Issue by Gabrielsc** [netbox-community/netbox#12848]
### NetBox version

v3.5.3

### Feature type

Change to existing functionality

### Proposed functionality

Since the add button is not suitable to be on the virtualization -> interfaces page as mentioned by @abhi1693 in #12847 , I propose to remove the add button in the image below.
![image](https://github.com/netbox-community/netbox/assets/8128226/4797ff91-91a2-4d8c-a1ad-356b366656c5)

Stay like on other pages that don't need the add button.
![image](https://github.com/netbox-community/netbox/assets/8128226/d8cb4939-e1a6-4516-8e18-0af58ad6ebaf)

### Use case

simplify usability.

**Comment by arthanson** [comment]
@sudheesh001 did you want to work on this one?

**Comment by sudheesh001** [comment]
Yes please, thank you so much! I'll take a shot at this as a part of the hackathon

**Comment by kkthxbye-code** [comment]
I'm sorry how does this fr make sense? The button was just recently added?

**Comment by arthanson** [comment]
@kkthxbye-code yes, look like these are reversed, this should be closed and #12847 should be opened / fixed.

**Comment by arthanson** [comment]
Closing this as the real issue should be fixed in #12847
