### ISSUE TITLE
Include "add" button on page heading for virtual machine interfaces list

### ISSUE THREAD

**Issue by Gabrielsc** [netbox-community/netbox#12847]
### NetBox version

v3.5.3

### Python version

3.9

### Steps to Reproduce

1. Click on Virtualization
2. Click on Interfaces

### Expected Behavior

I don't know if it would be exactly a bug or if something like that has already been opened (at least I didn't find it), but I believe that the "add" button previously existed in that part marked in red. At least in this version, there is this button on several other pages of the system. Sorry the English.
![image](https://github.com/netbox-community/netbox/assets/8128226/1592d274-3131-462e-8f77-3ebaf1d662b2)

### Observed Behavior

That the button existed, since items can be added.

**Comment by abhi1693** [comment]
This is not a bug and is expected.

**Comment by arthanson** [comment]
I think this should be re-opened, we now have the add button in the sidebar so the add button should appear here.

**Comment by sudheesh001** [comment]
I can take this instead then during the hackathon!
