### ISSUE TITLE
Pagination not working on "Related IPs" tab

### ISSUE THREAD

**Issue by stavr666** [netbox-community/netbox#12845]
### NetBox version

v3.5.3

### Python version

3.10

### Steps to Reproduce

Describing tested scenario (reproducible on Demo). It's possible, that UI elements not working on other non-primary tabs.

1. Go to user preferences and change default page length to 25.
2. Go to IPAM > Prefixes, create any /26 or wider prefixes.
3. Go to IP Addresses tab, bulk create 30+ IPs (for pagination).
4. Click on any of created IPs, go to "Related IPs tab".
5. Click on 2+ pages or select 50+ Per page values.

### Expected Behavior

Pages will change (?page=<NUM> added to address) and/or number of displayed IPs changed (?per_page=<NUM> added).

### Observed Behavior

Buttons not working. Nothing added to address string.

**Comment by jeremystretch** [comment]
Looks like the `<div>` is missing the `htmx-container` CSS class.
