### ISSUE TITLE
Enhance ImageAttachment model to allow uploading multiple images to NetBox models

### ISSUE THREAD

**Issue by F3d0s** [netbox-community/netbox#12844]
### NetBox version

v3.4.4

### Feature type

New functionality

### Proposed functionality

I'd like to propose adding the ability to attach multiple images to the ImageAttachment model, allowing users to upload and manage multiple images in a single action. Currently, users can only attach one image at a time, which can be slow and cumbersome when dealing with something that requires multiple images for documentation purposes (i.e. a device or a location).

This should be possible by:

1. Modify the ImageAttachment model to include a new field, images, which will store the uploaded images.
2. Enhance the user interface to provide a bulk upload functionality for adding multiple images.
3. Update the API endpoints to support the bulk upload of images.
4. Implement appropriate validation and error handling to ensure the integrity of the uploaded images.

### Use case

This functionality would greatly benefit NetBox users, particularly those who heavily rely on visual documentation for their devices and locations. With the ability to attach multiple images, users can conveniently upload and manage all relevant images in one go, significantly reducing the time and effort required to document devices.

By implementing this feature, Netbox can offer a more robust and user-friendly experience, empowering users to manage and document their devices with greater flexibility efficiently.

**Comment by ThomasADavis** [comment]
See https://github.com/Kani999/netbox-attachments - does more than just devices.

**Comment by F3d0s** [comment]
> Any reason this can't be done using device types? It provides images to be uploaded. 

Maybe I'm missing something, but I don't see how can I add several images to a specific device from `Device Types`.

This is where I'd like to select more the one image and add it to a device or location. Now it can be done by selecting a single image file each time, but it will take a lot of time when someone needs to add many image files.

![1](https://i.imgur.com/opjYPie.png)

![2](https://i.imgur.com/avMcpRa.png)

![3](https://i.imgur.com/zpDzWwZ.png)

> Your proposal also somewhat lacks details about how this bulk update feature should be implemented. You have also asked to add a new field in your proposal and yet you have mentioned no database changes are required. Your use case also does not justify the change you have proposed.

I agree that adding a new field won't be necessary, I am sorry, but I'm not familiar enough with the schema to know if any changes are necessary, and maybe I should keep the request simple. On the surface, it appears like it would be a simple addition. However, I think that the ability to bulk upload images will be appreciated by many admin users; imagine having to add 20 images to a single device or location, and you can do it in a few clicks instead of repeating the process for every single image.

**Comment by jeremystretch** [comment]
Your proposal appears to be written for devices and locations specifically but these models make use of the same ImageAttachment model that many other NetBox models also use for the same purpose. Is your intent to support bulk image attachments more generally? If so, please edit your initial post above to reflect that.

**Comment by F3d0s** [comment]
> Is your intent to support bulk image attachments more generally?

Yes, this would benefit the way to upload the images on netbox, as I think that now the procedure is rather slow and cumbersome.

**Comment by jeremystretch** [comment]
@F3d0s please edit your original post and title to reflect this.

**Comment by F3d0s** [comment]
@jeremystretch I hope it's correct now.
