### ISSUE TITLE
Config table button on contacts tab is unclickable.

### ISSUE THREAD

**Issue by Dakson13** [netbox-community/netbox#12850]
### NetBox version

v3.5.3

### Python version

3.8

### Steps to Reproduce

When trying to open the Configure table (Table that shows the Available Columns and the Selected Columns) by pressing the button in the upper right page corner, in the Contacts tab of any object, the table configuration is not displayed.

1. Click on Organization (or Devices or anywhere you can add a contact)
2. Click on Sites (or Tenants or any other objects)
3. Click on any Site in your list
4. Click on Contacts tab
5. Click on the "Configure table" button. 

### Expected Behavior

The Table Configuration should be displayed.

![image](https://github.com/netbox-community/netbox/assets/133873660/56c27989-011a-4002-8105-7d4df10731e1)

### Observed Behavior

The Table Configuration is not displayed. The button turns black but nothing happens.

![image](https://github.com/netbox-community/netbox/assets/133873660/c12b441e-0309-443f-a80f-20b49d3f98e4)

**Comment by stavr666** [comment]
Sorting (or disabling existing) also not working, it's replicated from tenancy/contact-assignments/ settings.
