### ISSUE TITLE
EDT timezone causes 502 Bad Gateway error

### ISSUE THREAD

**Issue by BH-NetAdmin** [netbox-community/netbox#12852]
### NetBox version

v3.5.3

### Python version

3.10

### Steps to Reproduce

set time zone to EDT in configuration.py and restart netbox service

### Expected Behavior

for netbox to accept EDT timezone and not error out

### Observed Behavior

502 Bad Gateway when trying to access netbox

**Comment by abhi1693** [comment]
Thank you for opening a bug report. Unfortunately, the information you have provided is not sufficient for someone else to attempt to reproduce the reported behavior. Remember, each bug report must include detailed steps that someone else can follow on a clean, empty NetBox installation to reproduce the exact problem you're experiencing. These instructions should include the creation of any involved objects, any configuration changes, and complete accounting of the actions being taken. Also be sure that your report does not reference data on the public NetBox demo, as that is subject to change at any time by an outside party and cannot be relied upon for bug reports.

**Comment by stuntguy3000** [comment]
Adding to this, @BH-NetAdmin please try to use a timezone from https://en.wikipedia.org/wiki/List_of_tz_database_time_zones.

It sounds like you've entered "EDT", which would be invalid. NetBox will not boot, and then the 502 will be returned from the reverse proxy because NetBox isn't running.

**Comment by jeremystretch** [comment]
As @stuntguy3000 points out, the list of valid timezones is referenced in [the documentation for the config parameter](https://docs.netbox.dev/en/stable/configuration/date-time/#time_zone). "EDT" is not a valid timezone.
