### ISSUE TITLE
API-Version header could be more precise

### ISSUE THREAD

**Issue by CADbloke** [netbox-community/netbox#12879]
### NetBox version

3.5.3

### Feature type

Change to existing functionality

### Proposed functionality

API header `API-Version` for API calls to https://demo.netbox.dev/api/ is 3.5 but https://demo.netbox.dev/api/status/ says "netbox-version": "3.5.3". There are differences between versions 3.5.1 & 3.5.3, for example, so the version header could be more precise. 

In some cases the difference is significant. When integer maximums change, sat from 2147483647 to 32767 it changes the expected type in many strongly-typed languages. This example is from `PowerPortRequest.allocated_draw`

### Use case

Object validation which differs between API versions

### Database changes

none.

### External dependencies

none.

**Comment by jeremystretch** [comment]
The status endpoint reports the specific NetBox version; the API itself is versioned only to the minor release, as it is not intended to change between e.g. 3.4 and 3.5.

> In some cases the difference is significant. When integer maximums change, sat from 2147483647 to 32767 it changes the expected type in many strongly-typed languages. This example is from PowerPortRequest.allocated_draw

You could make a case that such changes should be deferred to the next minor release, however that did not seem to be a concern regarding this particular change.
