### ISSUE TITLE
Add DATA_UPLOAD_MAX_MEMORY_SIZE as an configurable variable

### ISSUE THREAD

**Issue by ziggekatten** [netbox-community/netbox#12872]
### NetBox version

v3.5.3

### Feature type

New functionality

### Proposed functionality

Add to settings.py: DATA_UPLOAD_MAX_MEMORY_SIZE = getattr(configuration, 'DATA_UPLOAD_MAX_MEMORY_SIZE', 2621440)

### Use case

We use custom scripts, called through the API for data validation, and there is an hard limit on 2,6MB on the payload (body). We have cases were we are well above that (posting an JSON with all VM's fron an vCenter for validation), and I therefore suggest that variable is being added to the settings.py just as the file upload variable. Tests by setting this in settings.py our selves solves the challenge, but one must remember this when upgrading....

### Database changes

None

### External dependencies

None

**Comment by jeremystretch** [comment]
Does this need to be configurable? Should we just set it to a much higher (but sane) value, or disable it entirely?

**Comment by ziggekatten** [comment]
I suggest it to be configured so one can limit it to its own needs.
