### ISSUE TITLE
Support for setting expiration time when using the API token provisioning endpoint (/api/users/tokens/provision/)

### ISSUE THREAD

**Issue by iamroddo** [netbox-community/netbox#12870]
### NetBox version

v3.5.3

### Python version

3.10

### Steps to Reproduce

API ignores "expires" attribute when generating a token for a user and sets value to null.

```
curl 'https://<netbox hostname>/api/users/tokens/provision/' \
-H 'Content-Type: application/json' \
-H 'Accept: application/json' \
-d '{
    "username": "admin",
    "password": "<admin password>",
    "expires": "2023-06-12T12:47:47.245Z"
}'
```

`{"id":40,"url":"https://<netbox hostname>/api/users/tokens/40/","display":"<key>","user":{"id":1,"url":"https://<netbox hostname>/api/users/users/1/","display":"admin","username":"admin"},"created":"2023-06-12T12:51:57.222273Z","expires":null,"last_used":null,"key":"<key>","write_enabled":true,"description":"","allowed_ips":null}`

If an invalid date string is set to the value of "expires" the same thing happens.

### Expected Behavior

The response should be that the "expires" is set to that which is in the request payload, or an error if it is invalid and not setting it to null which has the result that the token has unlimited validity.

### Observed Behavior

All tokens set via the API have unlimited validity.

**Comment by abhi1693** [comment]
@stuntguy3000 Can you please comment on the issue so that I can it this to you?

**Comment by stuntguy3000** [comment]
> @stuntguy3000 Can you please comment on the issue so that I can it this to you?

Sure
