### ISSUE TITLE
toggle_available show condition is not correct

### ISSUE THREAD

**Issue by miyuk** [netbox-community/netbox#12886]
### NetBox version

v3.5.3

### Python version

3.8

### Steps to Reproduce

N/A

### Expected Behavior

This code was inserted by [this PR](https://github.com/netbox-community/netbox/commit/dcfd332cbfb2817b91ec744933291a718b3ebbdd#diff-3028b3070117917182aa0bc725bdfe53fb81475a51764ff738b9c06bbe6c582bR3)

When current if statement, below pattern doesn't show toggle.
```python
show_assigned = 0 # if 0 => False
show_available = None # if None is not None => False 
```

I don't know mean this if statement.
I guess to fix as below code.
```html
{% if show_assigned is not None or show_available is not None %}
```

Thanks

### Observed Behavior

N/A

**Comment by miyuk** [comment]
@jeremystretch 
Thank you for your reply.

Unfortunately, this bug cannnot reproduce because only source code problem.

**Comment by jeremystretch** [comment]
In its current form, your report is not actionable. Please provide all information requested in the bug report template. Otherwise, it will be closed.

**Comment by miyuk** [comment]
@jeremystretch 
Excuse me,  this bug cannot reproduce in production because it is potential bug.
So, please close this issue.

I only tell you about below souce code is not good as python.

```python
show_assigned or show_available is not None
```
https://github.com/netbox-community/netbox/blob/develop/netbox/templates/ipam/inc/toggle_available.html#L3
