### ISSUE TITLE
Make botocore dependency (AWS S3 backend) optional

### ISSUE THREAD

**Issue by jirutka** [netbox-community/netbox#12906]
### NetBox version

v3.5.3

### Feature type

Change to existing functionality

### Proposed functionality

[botocore](https://pypi.org/project/botocore/) is a really huge library, it consumes ~88 MiB of disk space. Since the data synchronization feature is optional and S3 is only one of the multiple backends, not all users will need it. The v3.5 release increased the disk size by a factor of 1.5 due to this dependency.

Please consider making this dependency optional.

### Use case

Saving disk space / making smaller container images, decreasing the number of dependencies.

**Comment by jeremystretch** [comment]
IMO this should apply to the `dulwich` library (used for the git backend) as well, and any additional backends we introduce in the future.
