### ISSUE TITLE
Display Danger & Warning Journal entries on an Objects landing page

### ISSUE THREAD

**Issue by scott-donnelly** [netbox-community/netbox#12910]
### NetBox version

v3.5.3

### Feature type

Change to existing functionality

### Proposed functionality

Add the ability to display Danger and Warning Journal entries on an objects landing page.

### Use case

Adding this feature allows users to quickly see important information relating to the object they are looking at, rather than having to dig through journal entries. 

### Database changes

nil

### External dependencies

nil

**Comment by martinum4** [comment]
That seems highly workflow-depended, at my workplace we collect the entries to have a history of the device and it's problems…

You could introduce a custom field like "is this solved?" for Journal entries and just display them on the Dashboard
![grafik](https://github.com/netbox-community/netbox/assets/18295403/f65f9ca2-4b93-439c-bae3-f42ed785fb83)
while still having a history:
![grafik](https://github.com/netbox-community/netbox/assets/18295403/a4ecfbe4-e2f2-481a-a8de-33ecd1062b0e)

**Comment by scott-donnelly** [comment]
That wouldn't work in our specific case as we have lots of devices with various notes, some that will always be present.

For example say that we have a server on faulty rails. If onsite staff were to work on the server they would first open the device page to locate the server and see the warning. They don't have to dig into the Journal tab, which may have hundreds of logs, to find a warning/danger entry that may or may not exist.

**Comment by martinum4** [comment]
But what do you do after the issue is fixed? Delete the Entry? Change from Warning to Info? Because even with your proposed FR the entry would continue to exist and displayed.

**Comment by jeremystretch** [comment]
I don't think this would make sense for most users, so I'm going to decline it. However, if it's something you'd like to pursue, it should be quite easy to implement as a plugin.
