### ISSUE TITLE
Add PLR4 40G optic type.

### ISSUE THREAD

**Issue by davesbell** [netbox-community/netbox#12933]
### NetBox version

v3.5.3

### Feature type

Data model extension

### Proposed functionality

Please can you add a new optic type 'PLR4'

These are the correct optic type to use when going from a 40G port to 4x10G ports.

https://www.flexoptix.net/en/q-1340g-10.html

### Use case

Allows us to correctly model our optic. The current QSFP+ 40G optic type isn't the same as a PLR4 40G optic.

### Database changes

To fit into the current naming scheme, it could probably be correctly represented by something like 'QSFP+ (4x10G)'

**Comment by pobradovic08** [comment]
I'm not sure that this is something that doesn't fall under QSFP+ 40G (It is a QSFP+ form factor, and it has 40G bitrate). All QSFP+ transcievers are 4x10G (the Q in the name), the only difference here is that it has those 4 channels on different fibers so you can easily break them out. This also holds true for QSFP+ 40G SR4 for example, as it also has an MPO connector and can be split to 4x10G easily, but is still modeled as just QSFP+ 40G.

**Comment by apellini** [comment]
From SR4 it is different because this is a SM connector and has MPO interface that permits breakout. I think that is better to add.

**Comment by jeremystretch** [comment]
There appears to be some conflation above of the _optic_ type with its _media_ type. As @pobradovic08 these should be modeled using one of the existing interface types.
