### ISSUE TITLE
Firefox 112 can not load rack front/rear images - Authentication credentials were not provided

### ISSUE THREAD

**Issue by jsalatiel** [netbox-community/netbox#12931]
### NetBox version

v3.5.3

### Python version

3.8

### Steps to Reproduce

Just try to load the rack page. The front and rear images wont load.
![image](https://github.com/netbox-community/netbox/assets/5522389/6fad661e-cb6c-4344-9bc5-fbed506fe0e5)

x-frame-options is set to SAMEORIGIN 
![image](https://github.com/netbox-community/netbox/assets/5522389/bb8b61c0-079d-4712-9fa5-5443c2f14f01)

Response returns:
Authentication credentials were not provided.

![image](https://github.com/netbox-community/netbox/assets/5522389/43c4ab81-e8d0-471c-8c23-adc9917ad6a0)

If I click Download SVG I can see the image

Also, google chrome works just fine.

### Expected Behavior

It shoud display the image as expected

### Observed Behavior

No images displayed.

**Comment by kkthxbye-code** [comment]
Thank you for opening a bug report. Unfortunately, the information you have provided is not sufficient for someone else to attempt to reproduce the reported behavior. Remember, each bug report must include detailed steps that someone else can follow on a clean, empty NetBox installation to reproduce the exact problem you're experiencing. These instructions should include the creation of any involved objects, any configuration changes, and complete accounting of the actions being taken. Also be sure that your report does not reference data on the public NetBox demo, as that is subject to change at any time by an outside party and cannot be relied upon for bug reports.

For reference, I tested with Firefox 114 and it works fine for me. Likely something outside netbox is messing it up.

**Comment by jeremystretch** [comment]
This is likely due to an error in your web server's configuration. Please see [this entry](https://github.com/netbox-community/netbox/wiki/Common-Issues#rack-elevations-do-not-display-v27) on our wiki.

**Comment by jsalatiel** [comment]
@jeremystretch I do not think it is a webserver problem, as i posted the configuration is as expected and works just fine on Chrome. Maybe a Firefox problem then.
