### ISSUE TITLE
Only one device is displayed for multi-termination cables

### ISSUE THREAD

**Issue by pobradovic08** [netbox-community/netbox#12951]
### NetBox version

v3.5.4

### Python version

3.8

### Steps to Reproduce

1. Create a cable that has multiple one side terminations on different devices
2. Go to the Cable page
3. Observe side with multiple terminations (device and interface listed)

### Expected Behavior

To display the device and it's interface (tightly coupled together) if there are multiple terminations, like in interface table view:
![image](https://github.com/netbox-community/netbox/assets/5007811/ff0bd20c-d3d1-4d88-9901-5064d30a53c5)
Something like:
![image](https://github.com/netbox-community/netbox/assets/5007811/dd468cd3-1f18-4ea0-98b2-db4b833f2d4a)

### Observed Behavior

Device is displayed only for first termination:
![image](https://github.com/netbox-community/netbox/assets/5007811/e8d5e650-7555-49b2-adb4-971409d842cd)

All interfaces are displayed, but it's not clear to which device they belong to.

**Comment by pobradovic08** [comment]
I have https://github.com/netbox-community/netbox/commit/83fd181c26304d0271bf0d480ea093a89f4ff88a as a quick fix* for this (but didn't want to open a PR yer since it's not assigned to me).

*This is more of an improvement then a fix of the root issue as the same applies to Rack (and maybe even Location and Site), as there is the possibility to have termination in different racks. The current format of Termination data presentation is not optimized for displaying multiple terminations, and might be better to have a table where each row would have all relevant information for each termination.

As the current interface list is really confusing, can we include this partial fix?

**Comment by jeremystretch** [comment]
@pobradovic08 sounds good, assigning this to you.

**Comment by pobradovic08** [comment]
Thank you @jeremystretch! I had some time to look at this further, and it seems that my concerns from the previous comment can be easily fixed by just chaging a couple of templates.

My proposal would be to have a table with each termination as a row. I would also move A and B sides to be horizontally distributed (instead of one above the other) as that looks better to me, but I would like to hear other's opinion.

Interface (with overall layout):
<img width="1185" alt="image" src="https://github.com/netbox-community/netbox/assets/5007811/f4f69e8e-c991-48fc-8e9b-ff2ab688f235">

Power feed:
<img width="1188" alt="image" src="https://github.com/netbox-community/netbox/assets/5007811/ab78797a-1840-4b6b-876f-5869a5760556">

Power outlet:
<img width="1182" alt="image" src="https://github.com/netbox-community/netbox/assets/5007811/ad62d282-951e-4431-9e22-87b227a4ea4f">

Circuits:
<img width="1182" alt="image" src="https://github.com/netbox-community/netbox/assets/5007811/145e9329-4a7b-40f0-8bf0-4f2b8bc0f6e1">
