### ISSUE TITLE
Brave UI Error

### ISSUE THREAD

**Issue by lp-2** [netbox-community/netbox#12974]
### NetBox version

v.3.5.4

### Python version

3.9

### Steps to Reproduce

1. open Brave-Browser version 114.0.5735.133 
2. go to racks
3. select desired rack 
4. select Patchpanel
5. click on delete
6.  nothing happens, but in inspector mode you can see that an http response (html) arrives, but this is not displayed as a popup in the UI

```

<form action="/dcim/devices/176/delete/" method="post">
  <input type="hidden" name="csrfmiddlewaretoken" value="<SOMETOKEN>">
  <div class="modal-header">
    <h5 class="modal-title">Confirm Deletion</h5>
  </div>
  <div class="modal-body">
    <p>Are you sure you want to <strong class="text-danger">delete</strong> device <strong>Patch Panel 1/1</strong>?</p>
    


    <input type="hidden" name="return_url" class=" form-control" id="id_return_url">

    <input type="hidden" name="confirm" value="True" class=" form-control" required="required" id="id_confirm">



  </div>
  <div class="modal-footer">
    
      <button type="button" class="btn btn-outline-secondary" data-bs-dismiss="modal">Cancel</button>
    
    <button type="submit" class="btn btn-danger">Delete</button>
  </div>
</form>

```

### Expected Behavior

a popup opens where i can confirm that i want to delete the component 

### Observed Behavior

I use the Brave Browser, but since the last version of the netbox, neither I nor my colleague can delete patch panels or remove patch cables, 

There is also no confirmation pop-up 

Other websites do not cause any problems 

Brave Version:
[Version 1.52.126 Chromium: 114.0.5735.133 (Offizieller Build) (64-Bit)](https://brave.com/latest/)

**Comment by kkthxbye-code** [comment]
I installed brave and was unable to replicate this. Does it work in other browsers? Does it work on demo.netbox.dev?

Please also check the javascript console for errors.
