### ISSUE TITLE
Allow custom fields on device interfaces

### ISSUE THREAD

**Issue by twiclo** [netbox-community/netbox#12972]
### NetBox version

v3.5.4

### Feature type

Data model extension

### Proposed functionality

Allow creation of custom fields on an interface similar to what can be done on a device.

### Use case

At our WISP we have access points that have two or more antennae. We've decided to store these as interfaces to the access point device. We would like to store the azimuth for these antennae on their respective interfaces. For now we're doing it in the description.

### Database changes

You would need to modify the interfaces table to mimic the devices table with custom interfaces

### External dependencies

None

**Comment by kkthxbye-code** [comment]
Not sure I understand here. Custom fields can already be added to interfaces.

**Comment by twiclo** [comment]
I'm sorry I'm not seeing it. Here's where I'm looking: https://demo.netbox.dev/dcim/interfaces/110/

**Comment by kkthxbye-code** [comment]
@twiclo - You add custom fields here before you can use them: https://demo.netbox.dev/extras/custom-fields/add/

**Comment by twiclo** [comment]
Perfect, thanks
