### ISSUE TITLE
Accessing /api/docs/ returns a 404

### ISSUE THREAD

**Issue by palmersample** [netbox-community/netbox#12970]
### NetBox version

v3.5.3, v3.5.4

### Python version

3.8

### Steps to Reproduce

Was contacted by someone asking if this problem was occurring for me also. Running v3.4.2 locally and accessing https://netbox-url/api/docs/ opens the Swagger UI.

On v3.5.3 and v3.5.4, this location results in Page not found - BUT clicking the API documentation link at the bottom of the dashboard (the "page" icon) opens Swagger at the location /api/schema/swagger-ui/

This is observable on https://demo.netbox.com:

<img width="697" alt="image" src="https://github.com/netbox-community/netbox/assets/40956652/4a01ad11-057b-4888-8fb4-a9c73dab8727">

And the working link:
<img width="501" alt="image" src="https://github.com/netbox-community/netbox/assets/40956652/e4a6a4dc-20d7-4f9e-b32a-b513375fe8c1">

### Expected Behavior

Swagger UI to open with API documentation

### Observed Behavior

Page not found error when accessing /api/docs/

**Comment by kkthxbye-code** [comment]
Please read the release notes, it's right there.

https://github.com/netbox-community/netbox/releases/tag/v3.5.0

>Breaking Changes

> * The REST API schema is now generated using the OpenAPI 3.0 spec
> * The URLs for the REST API schema documentation have changed:
> * * /api/docs/ is now /api/schema/swagger-ui/
> * * /api/redoc/ is now /api/schema/redoc/

**Comment by palmersample** [comment]
Totally understand about the search results - just wanted to bring it to your attention. Thank you! -P

**Comment by jeremystretch** [comment]
> Not sure how to fix google

FWIW I did tackle this a while back under #9994 but it appears to not be working anymore. Will need to dig into that. Thanks for the heads up @palmersample!

**Comment by palmersample** [comment]
No problem. And I was able to confirm this was the source of confusion for the person that reported the issue to me as well.

If there's anything I can do to help, please let me know!

**Comment by bluikko** [comment]
The URL https://demo.netbox.dev/static/docs/rest-api/overview/#interactive-documentation definitely still claims the API docs are at `/api/docs/`
