### ISSUE TITLE
Bulk edit of models with M2M fields can clear the M2M field

### ISSUE THREAD

**Issue by Urth** [netbox-community/netbox#12983]
### NetBox version

v3.5.4 and tested on develop

### Python version

3.10

### Steps to Reproduce

1. Create an interface with one or more tagged_vlans.
2. Use bulk edit on the interface to change something unrelated like the speed.
3. Observe the changelog with the tagged_vlans being removed.

### Expected Behavior

The untagged_vlans should remain unchanged if none are selected and set null is unchecked.

### Observed Behavior

The untagged_vlans are removed from the interface.

Caused by https://github.com/netbox-community/netbox/blob/develop/netbox/netbox/views/generic/bulk_views.py#L554-L555
In https://github.com/netbox-community/netbox/commit/41c92483a0b9b820dd0ca0c43c6c6d6e560043ed the truthy check on the m2m queryset was removed. Django querysets evaluate to False if the queryset is empty.

**Comment by netopsab** [comment]
Hello,

I'm facing this issue too... Also and for clarification, you mention the untagged_vlan field (excepted / observed behavior section). However, as you mentioned, this issue occurs with m2m fields, so with tagged_vlans (not untagged_vlan).

**Comment by abhi1693** [comment]
@netopsab Would you like to submit a pr?

**Comment by netopsab** [comment]
why not ... :)

**Comment by Urth** [comment]
The change proposed by @netopsab does not fix the problem. The bulk edit form always includes m2m fields in the cleaned_data. Otherwise the old code would trigger a `KeyError`. The problem is that the cleaned_data is an empty queryset when nothing is selected. My PR checks if the queryset is non-empty like the code before 41c92483a0b9b820dd0ca0c43c6c6d6e560043ed was applied.
