### ISSUE TITLE
Cannot set `/128` IPv6 address to an interface

### ISSUE THREAD

**Issue by BrunoBlanes** [netbox-community/netbox#12996]
### NetBox version

v3.5.3

### Python version

3.8

### Steps to Reproduce

1. Create a device with a virtual interface
2. Create a prefix pool and a `128` mask length IPv6 address
3. Try and add said address to the virtual interface.

### Expected Behavior

Expected to be able to set the address as primary loopback address of a device.

### Observed Behavior

`fd9b:58:30ac::1/128 is a broadcast address, which may not be assigned to an interface.`

**Comment by zombah** [comment]
It looks like this is already fixed in 3.5.4

**Comment by BrunoBlanes** [comment]
Will update today and let you know if it solves my issue.

**Comment by BrunoBlanes** [comment]
Yep, looks legit fixed, thanks @zombah.
