### ISSUE TITLE
Add Brazilian power outlet standard

### ISSUE THREAD

**Issue by BrunoBlanes** [netbox-community/netbox#13009]
### NetBox version

v3.5.4

### Feature type

Data model extension

### Proposed functionality

Add Brazilian power outlet standard as a power outlet type.

### Use case

Power outlets in Brazil are standardized by the Brazilian Association of Technical Standards (ABNT - Associação Brasileira de Normas Técnicas).
Our outlets were standardized in 2006 and have been enforced since 2011, making every manufacture that wishes to sell its products within national territory to comply with it. The standard is called [NBR 14136](https://en.wikipedia.org/wiki/IEC_60906-1#Brazilian_NBR_14136_standard_) and is based on the [IEC 60906-1](https://pt.wikipedia.org/wiki/IEC_60906-1) standard.

**Comment by DanSheps** [comment]
What is the difference between the two?

**Comment by BrunoBlanes** [comment]
The main difference is that while the European is limited to 16A, our standard defines two types of plugs:

- 10A (4mm pins)
- 20A (4.8mm pins)

That was made to stop users from overloading circuits.

**Comment by DanSheps** [comment]
So you would need two plugs, correct?

**Comment by BrunoBlanes** [comment]
Mostly, if your equipment is rated for 10A+, it would need to have a 20A plug, otherwise 10A.
So yes, two new plug types.

**Comment by BrunoBlanes** [comment]
I could take this issue if you'd like.
