### ISSUE TITLE
Some Reports have no "last run" in the overview

### ISSUE THREAD

**Issue by PaulR282** [netbox-community/netbox#13019]
### NetBox version

v3.5.4

### Python version

3.10

### Steps to Reproduce

1. Import a script (after investigation I found it only occurs on reports that have functions defined, like the DuplicatedSerial from the customization repo or a custom report)
2. Run it
3. Go to Customization/Reports

### Expected Behavior

The script should show a "Last Run" with the status

### Observed Behavior

Last Run: Never
Status: -

Also, when the report is open, there are no jobs shown in the "Jobs" tab but the number next to "Jobs" is right.

![image](https://github.com/netbox-community/netbox/assets/47193860/fd046036-a1fb-48d4-bf11-a1565a46849b)
![image](https://github.com/netbox-community/netbox/assets/47193860/62e44646-24af-46d6-bcd1-7c75acd1a5b8)

**Comment by bitcollector1** [comment]
seeing the same issue with most of my scripts, all but 1 fails to report any "completion" status.

![Screenshot 2023-07-05 at 09 28 52](https://github.com/netbox-community/netbox/assets/50723251/ccd24834-39e2-4c9c-914d-2f1e6fafdc02)

**Comment by cholyoak** [comment]
I can confirm this is an issue for both Reports and Scripts. It looks like the id for the Job and the key used to filter the results are inconsistent, sometimes using, for example, `report.name` and sometimes `report.class_name`. This is an issue if the script or report sets a `name` different to the default. I have a small patch that fixes this for me if you'd like me to submit a PR.

**Comment by cholyoak** [comment]
I think this also relates to #13061.

**Comment by jeremystretch** [comment]
Confirmed, this has been resolved under #13061.
