### ISSUE TITLE
api request for trace produce error 404 for front or rear ports

### ISSUE THREAD

**Issue by hvdort** [netbox-community/netbox#13020]
### NetBox version

v3.5.4

### Python version

3.8

### Steps to Reproduce

Requesting the cable trace using de GUI works fine. For interfaces as well as for front-ports and rear-ports. However, the REST-API seems to be only support the trace starting by an interface. If I request the trace starting from an front- or rear-port, I receive error 404.

working url's:
/dcim/interfaces/{id}/trace/
/dcim/front-ports/{id}/trace/
/dcim/rear-ports/{id}/trace/

and also working:
/api/dcim/interfaces/{id}/trace/

but not working url's:
/api/dcim/front_ports/{id}/trace/
/api/dcim/rear_ports/{id}/trace/

### Expected Behavior

implementing trace option also using the API.

### Observed Behavior

error 404 (not found)

**Comment by kkthxbye-code** [comment]
Hi, this is not a bug an intended. If you want to change the functionality, you need to create a feature request. The way it works currently is that rear and front ports implement the `/paths` endpoint which essentially will return all CablePaths that run through the port.

**Comment by hvdort** [comment]
Sorry, I hadn't discovered that option yet...
