### ISSUE TITLE
Reports and Scripts definitions are missing from OpenAPI

### ISSUE THREAD

**Issue by abhi1693** [netbox-community/netbox#13036]
### NetBox version

v3.5.4

### Python version

3.10

### Steps to Reproduce

This can be seen on the demo instance under extras at https://demo.netbox.dev/api/schema/swagger-ui/#/extras. There are no definitions displayed pertaining to scripts or reports.

You can still see these partially at https://demo.netbox.dev/api/extras/scripts/ and https://demo.netbox.dev/api/extras/reports/.

However, the same was available in v3.4.10.

### Expected Behavior

GET and POST definitions for scripts and reports should be visible under OpenAPI.

### Observed Behavior

No definitions for scripts and reports are visible in OpenAPI definition

**Comment by arthanson** [comment]
The reports and scripts are not direct models so have to be done a bit different, as these will probably be combined together in  4.0 it makes sense to wait for then to do this.

**Comment by abhi1693** [comment]
Blocked by #14438

**Comment by arthanson** [comment]
This is fixed as part of #14438 which will be in NB 4.0 (see screenshot of swagger docs) so closing.
![Monosnap NetBox REST API 2024-02-27 10-18-28](https://github.com/netbox-community/netbox/assets/99642/f7eb0239-0cff-4d77-bd2e-5e55aa49cf84)
