### ISSUE TITLE
I can add duplicate IP

### ISSUE THREAD

**Issue by advoenkin** [netbox-community/netbox#13031]
### NetBox version

v3.5.3

### Python version

3.10

### Steps to Reproduce

1. Click **IP Addresses** and press  **+Add**
2. In field **Address pattern** put **10.[22-32].[1-8].[1-42]/32**
3. Set status "Active", all other null.
4. Wait a bit and repeat 1, 2, 3 punts.

### Expected Behavior

When we try repeat it, netbox i think sould say "This IP address already exists".

### Observed Behavior

1. When we add to much range, Netbox return 504 status code. 
2. Netbox do not check duplicate or unique IP.

**Comment by abhi1693** [comment]
This is not a bug and is intended. You can enforce this check by setting [ENFORCE_GLOBAL_UNIQUE](https://docs.netbox.dev/en/stable/configuration/miscellaneous/#enforce_global_unique)
