### ISSUE TITLE
add formatted speed column to interface lists

### ISSUE THREAD

**Issue by matejv** [netbox-community/netbox#13033]
### NetBox version

v3.5.4

### Feature type

New functionality

### Proposed functionality

I propose adding a new column `Speed` to `InterfaceTable` that would show interface speed but formatted the same way it is shown on interface details view. This column would be added in addition of existing column `Speed (kbps)`. 

It would not be shown by default. Users could choose the column to be shown to show speed ether in kbps as now or shown formatted as 10 Gbps... 

### Use case

Currently it is difficult to determine if a speed is set to 1G, 10G or 100G without carefully counting if there are 6, 7 or 8 zeroes after 1. 

![image](https://github.com/netbox-community/netbox/assets/1256843/66b5d6c2-7a4d-4232-917f-7d99a100031d)

With this change:

![image](https://github.com/netbox-community/netbox/assets/1256843/8d2013f8-a694-42aa-9a8d-1d6d0074462c)

### Database changes

None

### External dependencies

None

**Comment by jeremystretch** [comment]
Just to reiterate, this would introduce a _new_ column, leaving the current column in place. The existing column works better for programmatic consumption; the new column better serves human readability.

**Comment by matejv** [comment]
That is correct. 

I can take this it's OK, as I already have the modifications made locally.

**Comment by jeremystretch** [comment]
Thanks @matejv!
