### ISSUE TITLE
Rack Elevation Download SVG option does not respect Image/Label dropdown

### ISSUE THREAD

**Issue by arcticash** [netbox-community/netbox#13046]
### NetBox version

v3.5.4

### Python version

3.10.7

### Steps to Reproduce

1. Open up a Rack View window
2. Top right of the rack elevations there is a dropdown to choose Images and Labels, Images Only or Labels Only - select any option other than "Images and Labels"
3. The correct rack elevation is displayed embedded into the page
4. Pressing the Download SVG button results in the Images and Labels view to be rendered, regardless of the option selected or what's currently being displayed.

### Expected Behavior

I would expect the Rendered SVG image to match what was displayed above the button, respecting the display option.

### Observed Behavior

The rendered SVG always shows both Images and Labels.

**Comment by jeremystretch** [comment]
> I would expect the Rendered SVG image to match what was displayed above the button, respecting the display option.

This is not the intended behavior: The SVG image for a rack's elevation does not consider the application of labels or device images. The visibility of these layers within the image is being toggled by the UI using Javascript in the browser. There is no mechanism by which a user can craft a request to render a rack elevation with only labels, for example.

You're welcome to propose a feature request for this (citing a use case), however it would need to entail the introduction of new query parameters for the API endpoint to control the rendered image.
