### ISSUE TITLE
Change conditions doc

### ISSUE THREAD

**Issue by bnoahpro** [netbox-community/netbox#13048]
### Change Type

Correction

### Area

Reference

### Proposed Changes

In the [conditions documentation](https://demo.netbox.dev/static/docs/reference/conditions/) you show of how to check whether a variable is filled or not.

But when I try, I get an error **Unsupported value type : <class 'NoneType'>**

my code : {"attr": "custom_fields.dhcp_server", "value": null, "negate": true}

The solution proposed in the documentation does not work.

If this problem is due to an implementation error, please change the label to BUG.

**Comment by kkthxbye-code** [comment]
`custom_fields` does not contain the custom field data but is just a reverse relation to the CustomField table. You probably want `custom_field_data`.
