### ISSUE TITLE
VLAN Group site scope not working 

### ISSUE THREAD

**Issue by bkampsnl** [netbox-community/netbox#13054]
### NetBox version

v3.5.2

### Python version

3.8

### Steps to Reproduce

1. Create VLAN group
2. Set scope to site A
3. Select the edit page of an interface of a device on site B
4. View list of VLAN group and see VLAN group you created for site A

Maybe this is the same issue as: 
https://github.com/netbox-community/netbox/discussions/8523#discussion-3850724

### Expected Behavior

Only vlan groups that have the scope of site A should be visible.

### Observed Behavior

A vlan group that does not belong to the scope of the site is visible in the list of vlan groups.

**Comment by bkampsnl** [comment]
I see in netbox/dcim/forms/model_forms.py in class class InterfaceForm :

`
    vlan_group = DynamicModelChoiceField(
        queryset=VLANGroup.objects.all(),
        required=False,
        label=_('VLAN group')
    )
`

It retrieves all vlangroups, there is no scope where clause. 

Is this intended ?

**Comment by kkthxbye-code** [comment]
> I see in netbox/dcim/forms/model_forms.py in class class InterfaceForm :
>vlan_group = DynamicModelChoiceField( queryset=VLANGroup.objects.all(), required=False, label=_('VLAN group') )
>It retrieves all vlangroups, there is no scope where clause.
>Is this intended ?

Yes, that is intended. The queryset is not used for filtering in DynamicModelChoiceFields.

**Comment by bkampsnl** [comment]
Usability thing, not really a bug.
