### ISSUE TITLE
Allow the "markdown" template filter to add css class names to the rendered div class attribute

### ISSUE THREAD

**Issue by jsenecal** [netbox-community/netbox#13055]
### NetBox version

v3.5.4

### Feature type

Change to existing functionality

### Proposed functionality

As implemented in https://github.com/netbox-community/netbox/pull/12664/commits/3e852acc8ec48f5b7d32811f4d9dec0ccdfa5970, this would allow the `div` generated by the `markdown` template filter to have additional custom classes appended to the list of classes.

### Use case

This extends usability of the template filter for use cases where one needs to add CSS classes in a specific rendering context.

### Database changes

None

### External dependencies

None

**Comment by jsenecal** [comment]
This FR is related to #12664

**Comment by jeremystretch** [comment]
> This extends usability of the template filter for use cases where one needs to add CSS classes in a specific rendering context.

Can you cite an instance where this is needed, and wrapping the Markdown content in another `<div>` isn't sufficient? It feels like this should be handled in the template.

**Comment by jsenecal** [comment]
> Can you cite an instance where this is needed, and wrapping the Markdown content in another `<div>` isn't sufficient? It feels like this should be handled in the template.

When rendering markdown widgets, this is required to address #13079 as the look and feel is inconsistent without adding a class to the rendered div (which uses the generic widget template, in that use-case)

I guess it's dependant on the acceptation of that other FR as it is related.

**Comment by jeremystretch** [comment]
I'm going to close this out as I've declined to implement #13079, and there has been no further justification offered for its implementation. As we're moving to adopt a new UI theme anyway, it's best to avoid any style changes in the interim where possible.
