### ISSUE TITLE
Add the ability to track "Inventory Items" not associated to devices

### ISSUE THREAD

**Issue by noisev2** [netbox-community/netbox#13062]
### NetBox version

3.5.4

### Feature type

Change to existing functionality

### Proposed functionality

At the moment you must assign for example a transceiver to a device in the inventory section.
But when we have spare transceiver there's no way to track it in netbox (the Device is obligatory).
Another example:
I created an Inventory Item Role named "Disks" and i tracked each disk for every device.
But i don't have the ability to track also the unused disks (this could be very useful to check if we have a specific type of disk or a SFP as i said above).

The only workaround would be create a fake device but that's not the clean way to go.

### Use case

This would be very useful to track disks, transceiver and any component in our inventory and could be faster the process of check the availability of this one.

**Comment by abhi1693** [comment]
There is a plugin that already exists for this feature: https://github.com/ArnesSI/netbox-inventory

**Comment by jeremystretch** [comment]
Asset tracking has been intentionally omitted from NetBox's feature scope at this time. It's possible we may consider adding it in the future, but it is not currently under consideration.
