### ISSUE TITLE
Make the dashboard cards/widget headers taller/bigger

### ISSUE THREAD

**Issue by jsenecal** [netbox-community/netbox#13079]
### NetBox version

v3.5.4

### Feature type

Change to existing functionality

### Proposed functionality

Prior to the implementation of Dashboard widgets introduced by #9416, the dashboards had taller headers which, looked better IMHO. Lets bring them back.

![image](https://github.com/netbox-community/netbox/assets/1564902/a63bbe40-c575-4ca8-ba02-14fda2eb12c1)
Versus:
![image](https://github.com/netbox-community/netbox/assets/1564902/3e288f16-4869-4e7f-a4e2-2dadd2e90936)

(Screenshots include other changes from https://github.com/netbox-community/netbox/issues/13077, sorry for this)

### Use case

Brings a more consistent look and feel to the dashboard page.

### Database changes

None

### External dependencies

None

**Comment by jeremystretch** [comment]
> Prior to the implementation of Dashboard widgets introduced by https://github.com/netbox-community/netbox/issues/9416, the dashboards had taller headers which, looked better IMHO. Lets bring them back.

This proposal would roughly double the amount of valuable screen space consumed by each header while conveying no additional information to the user. But this is a moot point as we're planning to move to [Tabler](https://tabler.io/) in NetBox v4.0, and will be adopting its card styling.
