### ISSUE TITLE
Support configuring card/widget header icon on dashboard page

### ISSUE THREAD

**Issue by jsenecal** [netbox-community/netbox#13078]
### NetBox version

v3.5.4

### Feature type

New functionality

### Proposed functionality

Related to https://github.com/netbox-community/netbox/pull/12664/commits/7d566837b6700acc904711952f50606a4ae2fec1

Allow for dashboard cards to have an icon added.

### Use case

The dashboard purpose is to allow users the opportunity to customize this view to include only the information most relevant to them.
Adding visual cues as to the content of the widgets/cards makes it even better (and prettier).

![image](https://github.com/netbox-community/netbox/assets/1564902/a108fbda-613d-4537-bebf-5570c65c3f8c)

### Database changes

None

### External dependencies

None

**Comment by stavr666** [comment]
I have several widget with mixed content. How will the header icon be defined? By selector?
Unicode is not enough?

**Comment by stavr666** [comment]
P.S. Text shadow or more contrast text colors for some header colors will be much more appreciated imho:

![image](https://github.com/netbox-community/netbox/assets/84839985/c3732b6f-f0f6-4709-b65e-7087ffadb428)

**Comment by jsenecal** [comment]
Hi @stavr666, 
The plan was to define icon names from Material Design Icons. 

Something like that:
```html
<h6 class="card-header text-center">
        {% if widget.icon_name %}<i class="mdi mdi-{{ widget.icon_name }}"></i>{% endif %}
        <span class="ms-1">{{ widget.title }}</span>
</h6>
```

Nothing would prevent you from using your method as well.

**Comment by jsenecal** [comment]
https://github.com/netbox-community/netbox/issues/12128 is probably blocking this

**Comment by jeffgdotorg** [comment]
@jsenecal now that #12128 is completed, would you like to take a fresh look at this issue?

**Comment by jsenecal** [comment]
It really depends on @jeremystretch tbh @jeffgdotorg

**Comment by jeremystretch** [comment]
I've not been involved with this FR at all.

**Comment by jeremystretch** [comment]
Closing this out at stale as there's been no further discussion.
