### ISSUE TITLE
Remove scrollbars from grid stack cards but still allow scrolling

### ISSUE THREAD

**Issue by jsenecal** [netbox-community/netbox#13076]
### NetBox version

v3.5.4

### Feature type

Change to existing functionality

### Proposed functionality

Related to https://github.com/netbox-community/netbox/commit/725c0b56c76a12d458bcba04724b2e80c98b6038;
Currently, grid cards have scrollbars when they overflow their containers. Lests hide them where it makes sense.

### Use case

These scrollbars look odd to me and consume visual space in the dashboard while not providing much functionality (scrolling with the mouse or with a finger on touch enabled devices works just fine):
![image](https://github.com/netbox-community/netbox/assets/1564902/09fb1d60-6b98-4676-bc8e-4fc6d8dd30ea)

This, combined with the grid size sometimes creates situations where a scrollbar is visible, but only because of the padding on the elements within the cards.

Adding css styles to hide the scrollbars on the appropriate classes addresses that as implemented [here](https://github.com/netbox-community/netbox/pull/12664/commits/725c0b56c76a12d458bcba04724b2e80c98b6038#diff-b406ba2282b6d6e3d3e0ae61257f4f05871819123c20a5947ede59f175cec32fR111-R123) fixes that

### Database changes

None

### External dependencies

None

**Comment by stavr666** [comment]
I'm totally support padding fix.

**Examples.**
Minimal widget unusable with 1 string:
![image](https://github.com/netbox-community/netbox/assets/84839985/fe8b297d-8913-45fd-8a3e-19aa4171be33)
2nd height have scrollbar with 3 strings:
![image](https://github.com/netbox-community/netbox/assets/84839985/b0a035b9-f35e-4e3c-bd76-627ff96fc22d)
3rd height have either space or scroll with 5-6 strings:
![image](https://github.com/netbox-community/netbox/assets/84839985/a85aea31-7ac3-4c96-b584-cc7ae3b9271c)

**Comment by jsenecal** [comment]
https://github.com/netbox-community/netbox/issues/12128 is probably blocking this

**Comment by jeremystretch** [comment]
> Currently, grid cards have scrollbars when they overflow their containers. Lests hide them where it makes sense.

This would be problematic from a UX perspective, as the absence of a scrollbar can obscure the existence of additional content. For instance, in your own screenshot above, removing the scrollbar would suggest that "VLANs" is the last item in the list, when there is actually more content to reveal.
