### ISSUE TITLE
Option to clone/inherit contact from Region/Location to locations/racks/devices

### ISSUE THREAD

**Issue by deku-m** [netbox-community/netbox#13087]
### NetBox version

v3.5.4

### Feature type

New functionality

### Proposed functionality

When adding contacts, you need to add a contact to every locations/racks/devices. 

If we can have some sort of inherit question option to also add the contact to the location and rack, this would save time. This could be a bulk/clone form or just asking do you also want to copy to your location/racks.

**For example:** 
I add a contact to a region who is responsable for that, but they also have multiple locations under them.
You then need to add the same contact one by one on every location/rack and maybe even devices.
While i mostly see and think that someone is responsible for the location/region and also the racks.
When you add the contact now to a site you wont find it on the location or rack. But i would like to see this a

I understand that devices can have different contacts or someone different who is responsible.
But main case is to minimize the adding of contact to underlaying hierachy and inheritet or clone.
Its almost the same as bulk adding functionality or maybe provide a bulk import at contact assignment.

### Use case

Providing a inherit function when adding a contact to a site with the automatically understanding that you also need it for a location or rack will  save time adding the same contact to every underlaying location and rack under the site. Mostly you have a floormanager who is responsible for that site or location with the racks he has. There are also cases in datacenters that you have different contacts for different racks or locations. But providing a inherit button or question or even a attach to location/racks will save time to not add it to every single location and rack under the responsible person of that site

### Database changes

Dont know exactly what.

### External dependencies

N/A

**Comment by jsenecal** [comment]
Thank you for your interest in extending NetBox. Unfortunately, the information you have provided does not constitute an actionable feature request. Per our [contributing guide](https://github.com/netbox-community/netbox/blob/develop/CONTRIBUTING.md), a feature request must include a thorough description of the proposed functionality, including any database changes, new views or API endpoints, and so on. It must also include a detailed use case justifying its implementation. If you would like to elaborate on your proposal, please either modify your original proposal or start a GitHub discussion to discuss the proposed feature.

**Comment by deku-m** [comment]
Updated case.

**Comment by abhi1693** [comment]
Bulk import of contact assignment is already an accepted issue https://github.com/netbox-community/netbox/issues/11307.
