### ISSUE TITLE
Add separate paginator placement for Changelog widget

### ISSUE THREAD

**Issue by stavr666** [netbox-community/netbox#13083]
### NetBox version

v3.5.3

### Feature type

Change to existing functionality

### Proposed functionality

Changelog widget must have separate settings for pagination, since it have sense this elements to be paced in both upper and lower part of page for 25-100+ elements, but for widget we define page size separately.

### Use case

![image](https://github.com/netbox-community/netbox/assets/84839985/65bdb147-3aad-466b-8873-75a68bfeadd7)
![image](https://github.com/netbox-community/netbox/assets/84839985/d41b16a2-f659-4bad-843b-7eecd84def7c)
![image](https://github.com/netbox-community/netbox/assets/84839985/832fd79a-1dcd-4b76-8772-afe33bb359f9)

**Comment by jeremystretch** [comment]
Thank you for your interest in extending NetBox. Unfortunately, the information you have provided does not constitute an actionable feature request. Per our [contributing guide](https://github.com/netbox-community/netbox/blob/develop/CONTRIBUTING.md), a feature request must include a thorough description of the proposed functionality, including any database changes, new views or API endpoints, and so on. It must also include a detailed use case justifying its implementation. If you would like to elaborate on your proposal, please modify your post above. If sufficient detail is not added, this issue will be closed.

**Comment by stavr666** [comment]
Screenshots is ignored?

1. You **already** have _Paginator placement_ setting in User preference, as well as Page length setting.
2. You have **Page size** setting in _Object list_ widget (my bad, I called it "change log" in description, since use list only for log now).
3. I ask you to add **Paginator placement** setting to widgets as well, so small widget size can be used more effective without scroll bars.

**Comment by abhi1693** [comment]
Paginators are already provided for widgets. In this screenshot, I have used the placement setting as `both` in my preference and it reflects the same inside the widget.

![image](https://github.com/netbox-community/netbox/assets/5083532/e5742b69-ce0f-4216-a9f6-ddbbba7ee060)

**Comment by kkthxbye-code** [comment]
He wants a settings on the widget that overrides the global setting. It's just not very well explained.

**Comment by jeremystretch** [comment]
That doesn't make any sense, and no justification has been provided. Closing this out.
