### ISSUE TITLE
Cannot search virtual device context by name

### ISSUE THREAD

**Issue by uedvt359** [netbox-community/netbox#13100]
### NetBox version

3.5.4

### Python version

3.8

### Steps to Reproduce

reproduced on demo.netbox.dev. it does not matter if any VDCs exist

1. search for a VDC by name, like so: https://demo.netbox.dev/dcim/virtual-device-contexts/?q=asdf

### Expected Behavior

a list of VDCs matching the name `asdf` is returned

### Observed Behavior

the following server error is returned:

```
<class 'ValueError'>

Field 'identifier' expected a number but got 'asdf'.

Python version: 3.8.10
NetBox version: 3.5.4
```

**Comment by kkthxbye-code** [comment]
Issue is here:

https://github.com/netbox-community/netbox/blob/07ae7c8a6e04ecc6e641044330fd4d03e4997252/netbox/dcim/filtersets.py#L1082

The search method searcher an integer field without checking if the query is an integer. So it works for q=1 but not for q=string.

An example of how we've done this other places:

https://github.com/netbox-community/netbox/blob/07ae7c8a6e04ecc6e641044330fd4d03e4997252/netbox/dcim/filtersets.py#L167-L170

**Comment by uedvt359** [comment]
just as a quick aside, searching by name specifically does work with e.g. https://demo.netbox.dev/dcim/virtual-device-contexts/?name=foo
