### ISSUE TITLE
Post API on available IP in prefix (/32) marked fully utilized

### ISSUE THREAD

**Issue by Etibru** [netbox-community/netbox#13105]
### NetBox version

v3.5.4

### Python version

3.10

### Steps to Reproduce

1. Create prefixes (ex: 10.10.10.1/32) **and check "Mark utilized"**
2. From the API, use endpoint "/api/ipam/prefixes/{id}/available-ips/" with Request body empty or not
==> Error 500: Internal Server Error

Problem found on netbox version 3.4.8 and tested if still pressing on latest version 

### Expected Behavior

We would like to have the IP created back

### Observed Behavior

Error  Error 500: Internal Server Error
```json
{
  "error": "'list' object has no attribute 'size'",
  "exception": "AttributeError",
  "netbox_version": "3.5.4",
  "python_version": "3.10.6"
}

```
Or in netbox version 3.4.8 : 
erreur 500 : Internal server Error

```html
<!DOCTYPE html>
<html lang="en">

<head>
    <title>Server Error</title>
    <link rel="stylesheet" href="/static/netbox-light.css" />
    <meta charset="UTF-8">
</head>

<body>
    <div class="container-fluid">
        <div class="row">
            <div class="col col-md-6 offset-md-3">
                <div class="card border-danger mt-5">
                    <h5 class="card-header">
                        <i class="mdi mdi-alert"></i> Server Error
                    </h5>
                    <div class="card-body">
                        
                            <p>
                                There was a problem with your request. Please contact an administrator.
                            </p>
                        
                        <hr />
                        <p>
                            The complete exception is provided below:
                        </p>
<pre class="block"><strong>&lt;class &#x27;AttributeError&#x27;&gt;</strong><br />
&#x27;list&#x27; object has no attribute &#x27;size&#x27;

Python version: 3.10.6
NetBox version: 3.4.8</pre>
                        <p>
                            If further assistance is required, please post to the <a href="https://github.com/netbox-community/netbox/discussions">NetBox discussion forum</a> on GitHub.
                        </p>
                        <div class="text-end">
                            <a href="/" class="btn btn-primary">Home Page</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>

</html>
```

**Comment by abhi1693** [comment]
Thank you for opening a bug report. Unfortunately, the information you have provided is not sufficient for someone else to attempt to reproduce the reported behavior. Remember, each bug report must include detailed steps that someone else can follow on a clean, empty NetBox installation to reproduce the exact problem you're experiencing. These instructions should include the creation of any involved objects, any configuration changes, and complete accounting of the actions being taken. Also be sure that your report does not reference data on the public NetBox demo, as that is subject to change at any time by an outside party and cannot be relied upon for bug reports.
