### ISSUE TITLE
Update Virtual chassis Member error

### ISSUE THREAD

**Issue by ThierryGUI** [netbox-community/netbox#13122]
### NetBox version

v3.5.4

### Python version

3.11

### Steps to Reproduce

Hi all, 
Here is the situation I'am facing with Netbox 3.4.5 with a stack of switch.

1 - First tenant creation in a particular site / rack
2 - Second tenant creation in the same particular site / rack

3 - First device creation with name (switch-test) recorded in the first tenant. 
4  - Second device creation with same name (switch-test) recorded in the second tenant. 

At This step, I've in the same rack, two differents devices in two different tenant, devices with same name as they are part of stack. 

5 - Virtual chassis creation in the concerned rack. 
6 - Adding in the Virtual Chassis, 2 devices  (switch-test) - with same name as they are both members of virtual chassis. 

At this step, I've a stack of 2 switchs (this same name) in a particular rack. 

![image](https://github.com/netbox-community/netbox/assets/138896306/12957ad1-cedb-411f-9402-0def353bb894)

![image](https://github.com/netbox-community/netbox/assets/138896306/ed4ee469-a384-4edf-a8d0-770ad1ec7bfa)

### Expected Behavior

When I want to connect a particular interface of first Switch (StackWise480 1) (using CONNECT Button of interface page) to a particular interface of second switch (StackWise480 2), I'd like a single connection appear : 

First switch interface StackWise480 1 (object id : 1216) CONNECTED TO second Switch interface StackWise480 2 (object id : 1217) 

### Observed Behavior

First switch interface StackWise480 1 (object id : 1216) IS CONNECTED TO first Switch interface StackWise480 2 (object id : 1216)  - same switch

Is there something wrong this Netbox, or am I doing the wrong way ? 

Any help would be appreciated ! 

Regards 
```[tasklist]
### Tasks
```

**Comment by kkthxbye-code** [comment]
Thank you for opening a bug report. Unfortunately, the information you have provided is not sufficient for someone else to attempt to reproduce the reported behavior. Remember, each bug report must include detailed steps that someone else can follow on a clean, empty NetBox installation to reproduce the exact problem you're experiencing. These instructions should include the creation of any involved objects, any configuration changes, and complete accounting of the actions being taken. Also be sure that your report does not reference data on the public NetBox demo, as that is subject to change at any time by an outside party and cannot be relied upon for bug reports.

**Comment by ThierryGUI** [comment]
Closed by mistake sorry !

**Comment by ThierryGUI** [comment]
Closed By mistake Sorry

**Comment by jeremystretch** [comment]
This issue is being closed as no further information has been provided. If you would like to revisit this topic, please first modify your original post to include all the requested detail, and then ask that the issue be reopened.
