### ISSUE TITLE
Adding Front Ports with range

### ISSUE THREAD

**Issue by bsdking** [netbox-community/netbox#13120]
### NetBox version

v3.5.5

### Python version

3.9

### Steps to Reproduce

Goto Device.
Add 'Add a new front port'
Select Device
Give name [0-9]
Assign Type
Assign Rear Port

Get error:

### Expected Behavior

To see the range of ports created

### Observed Behavior

Get error:

Server Error
There was a problem with your request. Please contact an administrator.

The complete exception is provided below:
<class 'IndexError'>

list index out of range

Python version: 3.9.16
NetBox version: 3.5.5

**Comment by kkthxbye-code** [comment]
Thank you for opening a bug report. Unfortunately, the information you have provided is not sufficient for someone else to attempt to reproduce the reported behavior. Remember, each bug report must include detailed steps that someone else can follow on a clean, empty NetBox installation to reproduce the exact problem you're experiencing. These instructions should include the creation of any involved objects, any configuration changes, and complete accounting of the actions being taken. Also be sure that your report does not reference data on the public NetBox demo, as that is subject to change at any time by an outside party and cannot be relied upon for bug reports.

**Comment by kkthxbye-code** [comment]
Closing as there has been no response.
