### ISSUE TITLE
Bug : 'ImageDraw' object has no attribute 'textsize'

### ISSUE THREAD

**Issue by Trusthier** [netbox-community/netbox#13133]
### NetBox version

V3.5.5

### Python version

3.8

### Steps to Reproduce

1. Upgrade netbox 3.5.4 to 3.5.5
2. Go to devices
3. Selecte one device

### Expected Behavior

We should have access to the equipment detail

### Observed Behavior

Server Error
There was a problem with your request. Please contact an administrator.

The complete exception is provided below:

<class 'AttributeError'>

'ImageDraw' object has no attribute 'textsize'

Python version: 3.8.13
NetBox version: 3.5.5
If further assistance is required, please post to the [NetBox discussion forum](https://github.com/netbox-community/netbox/discussions) on GitHub.

**Comment by abhi1693** [comment]
Duplicate of #13115
