### ISSUE TITLE
Global search on IP address with mask not giving results

### ISSUE THREAD

**Issue by aodix** [netbox-community/netbox#13143]
### NetBox version

3.5.4

### Python version

3.8

### Steps to Reproduce

1. Create IP with subnet (ex: 10.0.0.105/32)
2. use search function with exact match or Partial match to find the IP 
![image](https://github.com/netbox-community/netbox/assets/20492819/e5befecf-d410-4988-b050-3ae75066881a)

### Expected Behavior

find the ip address when available in netbox
![image](https://github.com/netbox-community/netbox/assets/20492819/b3bc148b-8e78-4d04-ac3e-aa65a695c8fd)

### Observed Behavior

No results found when searching
![image](https://github.com/netbox-community/netbox/assets/20492819/adf111ef-d14a-4d1f-9fed-f4b50ba6de8b)

**Comment by jeremystretch** [comment]
Thank you for opening a bug report. Unfortunately, the information you have provided is not sufficient for someone else to attempt to reproduce the reported behavior. Remember, each bug report must include detailed steps that someone else can follow on a clean, empty NetBox installation to reproduce the exact problem you're experiencing. These instructions should include the creation of any involved objects, any configuration changes, and complete accounting of the actions being taken. Also be sure that your report does not reference data on the public NetBox demo, as that is subject to change at any time by an outside party and cannot be relied upon for bug reports.

**Comment by abhi1693** [comment]
Thank you for opening a bug report. I was unable to reproduce the reported behavior on NetBox v3.5.6. Please re-confirm the reported behavior on the current stable release and adjust your post above as necessary. Remember to provide detailed steps that someone else can follow using a clean installation of NetBox to reproduce the issue. Remember to include the steps taken to create any initial objects or other data.

**Comment by kkthxbye-code** [comment]
Closing as there has been no response. The likely culprit would be the index haven been cleared but not regenerated. This can be fixed by running the `manage.py reindex` command.
