### ISSUE TITLE
When creating new IP in IPAM the Interface Assignment option Virtual Machine dropdown won´t show vms anymore, shows interfaces only

### ISSUE THREAD

**Issue by replior** [netbox-community/netbox#13145]
### NetBox version

v.3.5.5

### Python version

3.8

### Steps to Reproduce

1. Under IPAM Ip addresses , click plus to add new address
2. third block where you point the new ip to either a device, virtual machine or FHRP Group, when working, the drop down menu below changed what was selectable ,(device= interfaces, Virtual Machine=list of vm:s, FHRP Group=list of FHRP Groups)

### Expected Behavior

A vm list should appear and when selecting a vm, another field showing it´s interfaces so one can select the correct one.

### Observed Behavior

A list of interfaces appears instead of vm list

**Comment by kkthxbye-code** [comment]
Hi

Use this button to filter the interfaces.

![image](https://github.com/netbox-community/netbox/assets/400797/c25d2915-b6c9-4a48-a136-4b09a1dbb4e8)

**Comment by replior** [comment]
1. I figured out how one can filter vm:s, but how do I filter corresponding vms interfaces? ended up connecting ip to wrong vm:s interface ....hard to find correct eth0 amongst hundreds of vm:s
2. This is time consuming to say the least, I hope it is a temporary workaround while the earlier functionality is restored.

**Comment by replior** [comment]
So, it´s not a bug, just a "bad development" as usability decreases??
