### ISSUE TITLE
Add prefix key/value to the ipam/ip-addresses API endpoint response

### ISSUE THREAD

**Issue by atownson** [netbox-community/netbox#13152]
### NetBox version

v3.5.5

### Feature type

Change to existing functionality

### Proposed functionality

I propose to add a `prefix` (or `parent_prefix`) key/value to the response from the ipam/ip-addresses API endpoint that relates the IP address to the smallest parent prefix.

For example, if you have prefixes 192.168.0.0/20 and 192.168.128.0/24 in the global VRF and 192.168.0.0/25 in another VRF, IP address 192.168.0.1/24 with no VRF assignment would return 192.168.0.0/24 as the prefix.

This would need to be a nested object representing at least the `id`, `prefix`, and `vrf` values of the prefix.

This request might be related to #7845 but might not be blocked by it.

### Use case

It is somewhat challenging to relate IP addresses to their parent prefixes via the API. Currently, we are getting all prefixes from the ipam/prefixes endpoint and iterating over each prefix invoking a GET request to ipam/ip-addresses?parent=prefix. One issue with this approach is that you're not guaranteed a complete list of IP addresses with this method (excludes any IP without a parent prefix). Implementing the change requested will reduce the number of API calls needed.

### Database changes

Unknown

### External dependencies

None

**Comment by jsenecal** [comment]
Slightly related to #7845
