### ISSUE TITLE
Keep filters when navigating through netbox 

### ISSUE THREAD

**Issue by carlo-4ip** [netbox-community/netbox#13162]
### NetBox version

v3.5.4

### Feature type

Change to existing functionality

### Proposed functionality

I would like to propose a filter which kind of would work like a "workspace". This filter would be filtering on tenant level, so when filtering on a certain tenant and then clicking the "devices" it shows only the devices of this tenant.

It should be active on every tenant-related page with a list/table that the user visits, like Devices, IP addresses, Prefixes, Wireless LAN, etc. Only resetting this filter should show everything again, so the user is in control.

The more general pages, like Manufacturers or Device Types should not be filtered, as these are applicable for all tenants.

#### Positioning and design
The filter should be easily accessible in the top left or right corner, so changing from one "workspace" to another is quick and simple.

I would propose something like shown in the following image, but added to this a simple search bar at the top.
https://user-images.githubusercontent.com/12944771/236021102-d95d59e7-a775-42c0-a15f-53973b436d71.png

### Use case

As discussed here:
https://github.com/netbox-community/netbox/discussions/12341#discussioncomment-6059217

For example, when navigating to a tenant and see all devices we have a filter of the tenant. But then, if we open a device an want to return to the device list the filter is gone (clicking "devices" in the menu).

The proposed feature would allow for a kind of "workspace" (being the tenant) where the user can search all tenant related info, like devices or IP addresses, while still being able to work with the Netbox menu to switch modules (within that tenant filter). It lets users focus on a certain tenant without having to rebuild the filter each time they click a menu item. Just select the tenant you need in the filter and you can use the menu to switch modules and not be overwhelmed with thousands of entries.

### Database changes

I don't think there would be need for database changes.

### External dependencies

None.

**Comment by carlo-4ip** [comment]
Hi,

I'm sorry for that, I'm quite new to the community and to Netbox. I have a lot of colleagues looking to me for a good working environment to work in. Our last tool didn't fulfill the requirements anymore.

I've updated the request, I hope this is more like you want it to be.

**Comment by jsenecal** [comment]
So something like "Sticky filters" then, you set them in some UI modal and they stick across pages. A Banner should remember the user that they have some sticky filters activated.

This is a lot of work to implement though, not sure there is substantial ROI however.

**Comment by carlo-4ip** [comment]
Hi Jonathan,

Yes, you are correct. I didn't know this request was a lot of work. I thought, since there is already a filtering function, there could be some code for re-usage.

However, I should think there have to be more of your users that are in an MSP environment and are dying for a way to work on 1 customer (tenant) at a time.

Please think about it. I would like to hear your thoughts.

Kind regards,
Carlo Vos
________________________________

**Comment by tjdavis3** [comment]
I think the "sticky filters" idea is best.  Having to set filters over and over again is one of the most frustrating things about working in Netbox.  We don't deal with tenants so much, but we do have multiple sites and when working on a given site (eg. doing an audit) it is painful to have to reset the filter every time we edit a device and go back to the list.

**Comment by Eideen** [comment]
Can it be done somethling like this?

### Short demo to combined `localStorage` (Persistent filters) and `URL parmeters` (Current filter).

````html
<!DOCTYPE html>
<html>
<script>
        function GetURLParameter(sParam) {
                var sPageURL = window.location.search.substring(1);
                var sURLVariables = sPageURL.split('&');
        

            document.getElementById("myText").innerHTML = number;

        }
        function myFunction() {
            var number = "123";
            document.getElementById("myText").innerHTML = number;
        }
</script>
<body  onload="myFunction()">
    <input type="text" id="header" name="header" placeholder="Enter data">
    <p><button onclick="Apply_and_save_To_Storage()" type="button">Apply!</button></p>
    <p><button onclick="Load_from_Storage()" type="button">Remember me!</button></p>
    
    <script>
        function Apply_and_save_To_Storage() {
            window.localStorage['header'] = document.getElementById('header').value;
        }
    
        function Load_from_Storage() {
            document.getElementById('header').value = window.localStorage['header'];
        }


        
        
        window.addEventListener('load', Load_from_Storage);

    </script>

<h1>URL Parameters</h1>
    <p id="parameter-output"></p>

    <script>
        // JavaScript code for capturing and printing URL parameters
        // Get the query string from the URL
        const queryString = window.location.search;

        // Create a URLSearchParams object to parse the query string
        const urlParams = new URLSearchParams(queryString);

        // Create an empty array to store the parameters
        const parametersArray = [];

        // Iterate through the parameters and add them to the array
        urlParams.forEach((value, key) => {
            parametersArray.push({ key, value });
        });

        // Retrieve values from localStorage and combine with URL parameters
        const localStorageValue = localStorage.getItem("header");

        if (localStorageValue) {
            parametersArray.push({ "header": localStorageValue });
        }


        // Print the array of parameters and values to the page
        const parameterOutput = document.getElementById("parameter-output");
        parameterOutput.textContent = JSON.stringify(parametersArray, null, 2);

    </script>
</body>
</html>
````

I am a noob when it comes to HTML, but from that combind array you can pass that on to the current filter.

**Comment by ITJamie** [comment]
Another example would be when filtering changelogs and you want to use the next/previous options but based on the filtered list

**Comment by jeremystretch** [comment]
While I appreciate the perspectives shared here, it seems we still haven't arrived at an actionable proposal. Several immediate considerations still have not been addressed:

* What is the proposed workflow for enabling a "sticky" filter, versus setting it for one-time use?
* How should NetBox handle a sticky filter when viewing a model with no applicable filter (e.g. when viewing the interfaces list with a tenant filter enabled)?
* How can a user disable the sticky filter?

I'm sure there are others. The discussion thus far seems to have focused more on enabling a particular feature and less on the workflows involved.

I'm going to close out this FR as I don't believe attempting to salvage the proposal at this stage makes sense. Instead, I invite anyone interested in doing to so to [submit a new FR](https://github.com/netbox-community/netbox/issues/new?assignees=&labels=type%3A+feature&projects=&template=feature_request.yaml) leveraging what has been discussed here and adding sufficient supporting context and detail. An actionable FR will include the specific mechanism being proposed, ideas for its technical implementation, a set of requirements for how it should function for both applicable and non-applicable views, and example workflows.

Looking forward to rebooting this proposal!
