### ISSUE TITLE
Custom fields with option to be hidden (treat like secret)

### ISSUE THREAD

**Issue by mtnetronik** [netbox-community/netbox#13177]
### NetBox version

v3.5.5

### Feature type

Change to existing functionality

### Proposed functionality

This request is related to #11623.
Is it possible to add option in custom field that this field will be hidden, like field from Wireless -> Wireless LAN -> PSK ?

In the other words:
In Wireless -> Wireless LANs you added additional field "Pre-shared key" and it store in DB in wireless_wirelesslan table in auth_psk. When you try to view this value on right of this field you have button show/hide secret. When you try to edit this field you see dots instead real value.
So it is possible to add this option (button with show/hide secret and dots when editing) to use in Custom Fields?

### Use case

For example for Mikrotik wireless devices where we are using few wireless protocols like 802.11 and nv2 and passwords are different.

### Database changes

Yes, I think - new column in extras_customfield table what will store information if custom field will be treated like secret or not.

**Comment by abhi1693** [comment]
Thank you for your interest in extending NetBox. Unfortunately, the information you have provided does not constitute an actionable feature request. Per our [contributing guide](https://github.com/netbox-community/netbox/blob/develop/CONTRIBUTING.md), a feature request must include a thorough description of the proposed functionality, including any database changes, new views or API endpoints, and so on. It must also include a detailed use case justifying its implementation. If you would like to elaborate on your proposal, please modify your post above. If sufficient detail is not added, this issue will be closed.

**Comment by mtnetronik** [comment]
@abhi1693 Thank you for response. I am user not programmer, so it would be nice if you helped me describe it correctly.
In my words:
In this topic #11623
In Wireless -> Wireless LANs you added additional field "Pre-shared key" and it store in DB in wireless_wirelesslan table in auth_psk. When you try to view this value on right of this field you have button show/hide secret. When you try to edit this field you see dots instead real value.
So it is possible to add this option (button with show/hide secret and dots when editing) to use in Custom Fields?

**Comment by abhi1693** [comment]
Please update this in your description in your original post so that other maintainers can also look into this.

**Comment by mtnetronik** [comment]
Any news?
