### ISSUE TITLE
IPAM can not change current ip address assignment when the ip is assigned to a virtual host

### ISSUE THREAD

**Issue by replior** [netbox-community/netbox#13178]
### NetBox version

v.3.5.5

### Python version

3.8

### Steps to Reproduce

<img width="785" alt="Screenshot 2023-07-13 at 16 00 18" src="https://github.com/netbox-community/netbox/assets/139224912/50723975-0ae0-41a3-ab40-22952774ed34">

Can not remove current vm (which is not even shown in this view), or the interface as one can not click on the x

### Expected Behavior

Earlier versions allowed deselecting vm and interface

### Observed Behavior

nothing happens other than a "no parking" sign showing up at mouse over...

**Comment by jeremystretch** [comment]
This issue is being closed as no further information has been provided. If you would like to revisit this topic, please first modify your original post to include all the requested detail, and then ask that the issue be reopened.
