### ISSUE TITLE
INFO level for auth log

### ISSUE THREAD

**Issue by dmgeurts** [netbox-community/netbox#13194]
### NetBox version

v3.5.1

### Feature type

Change to existing functionality

### Proposed functionality

The django_auth_logging only supports the DEBUG level. Limiting the logging to auth success or failure would be great, rather than all the LDAP DEBUG detail.

Currently, I'm interested in logging failed auth attempts. LDAP is working fine, so I have no need for DEBUG-level logs.

### Use case

Reduce the volume of logging to what is required when tracking an audit trail as opposed to full DLAP debugging.

### Database changes

n/a

### External dependencies

LDAP authentication.

**Comment by abhi1693** [comment]
Is this what you are looking for?

https://github.com/netbox-community/netbox/blob/develop/netbox/users/signals.py

**Comment by dmgeurts** [comment]
> Is this what you are looking for?
> 
> https://github.com/netbox-community/netbox/blob/develop/netbox/users/signals.py

Yes, 100%, thank you. No harm in also logging successful logins but at a minimum the failed logins are essential for logging to Elastic/Splunk/etc.

**Comment by DanSheps** [comment]
Do you need this FR anymore then since it appears to be logged?

**Comment by jeremystretch** [comment]
I'm going to close this out as there's been no further response.
