### ISSUE TITLE
Add SNIP and Other IP Address Roles

### ISSUE THREAD

**Issue by etherwrangler** [netbox-community/netbox#13190]
### NetBox version

v3.5.6

### Feature type

Data model extension

### Proposed functionality

Add "SNIP" and "Other" to the ipam.IPAddress.role field or make this field support custom FIELD_CHOICES.

### Use case

Citrix NetScalers have an IP type called a SNIP (Subnet IP) that would be useful to track as separate from a VIP when added to an FHRP Group.

### Database changes

None.

### External dependencies

None.

**Comment by jsenecal** [comment]
I am not in favor to add proprietary protocols to that list, but would be in favor to support `FIELD_CHOICES` for this field.

**Comment by ITJamie** [comment]
if we were to enable FIELD_CHOICES for that list we would want to make sure that we have a way to mark wether choices are anycast or not (aka allowing duplicate ips) right now there are hard coded checks for some of the choices to ignore duplicate IP logic in vrf's

**Comment by DanSheps** [comment]
I have used Citrix Netscaler and SNIP is just a VIP, there isn't any special protocol with the IP itself, it is all handled as part of the Netscaler clustering protocol.

IMO, not in favor of this and really utlimately not in favor of even opening IP roles to FIELD_CHOICES.

**Comment by etherwrangler** [comment]
Going to close this request.  We'll use tag's instead of this.  When the request was made was not aware that this field has logic built in based on some choices as @ITJamie mentioned.  Given that I feel it would be overburdening to request this be implemented.
