### ISSUE TITLE
Depth/Max Length for Child Prefixes 

### ISSUE THREAD

**Issue by a173tfo** [netbox-community/netbox#13197]
### NetBox version

v3.5.3

### Feature type

Data model extension

### Proposed functionality

Ability to use Max Dept and Max Length functions into a child prefix in the same way as for prefixes.

### Use case

This will enable more convenient sorting of a large number of child prefixes.

**Comment by jeremystretch** [comment]
Thank you for your interest in extending NetBox. Unfortunately, the information you have provided does not constitute an actionable feature request. Per our [contributing guide](https://github.com/netbox-community/netbox/blob/develop/CONTRIBUTING.md), a feature request must include a thorough description of the proposed functionality, including any database changes, new views or API endpoints, and so on. It must also include a detailed use case justifying its implementation. If you would like to elaborate on your proposal, please modify your post above. If sufficient detail is not added, this issue will be closed.

**Comment by a173tfo** [comment]
I mean, it would be convenient to use this Max Depth and Max Length functions:
![11](https://github.com/netbox-community/netbox/assets/104919266/5dded358-10fb-4b63-928e-86384f9b2e65)

into the tab Child Prefixes:
![22](https://github.com/netbox-community/netbox/assets/104919266/a6af9e89-763d-4ba4-ac15-0eb986350182)
