### ISSUE TITLE
Add Interface 100Base-Fx as an interface type

### ISSUE THREAD

**Issue by AlexisQM88** [netbox-community/netbox#13191]
### NetBox version

v3.5.4

### Feature type

New functionality

### Proposed functionality

Interface 100Base-Fx is a fiber interface that exchange data between two devices through a fiber cable.

### Use case

Fiber interface 100Base-Fx doesn't exist in Netbox platform and it's necessary to define this interface as a fiber connection.
The closest option of this is the interface type 100Base-Tx, but this interface represent a copper connections (UTP Cat 5E, 6)

![100BaseFx ](https://github.com/netbox-community/netbox/assets/139709937/30543475-1b20-4775-ada0-1d6a9765a9d1)

**Comment by jeremystretch** [comment]
100Base-FX is already available as an interface type in NetBox.
