### ISSUE TITLE
API returns empty list 

### ISSUE THREAD

**Issue by grethler** [netbox-community/netbox#13205]
### NetBox version

v3.5.6

### Python version

3.11

### Steps to Reproduce

Use the following code with the link of your netbox instance and a token that has the right permissions to view:

```
import requests
TENANT = ""
TOKEN= ""

header = {"Authorization":TOKEN}
rep = requests.get(f"https://{TENANT}/api/extras/reports/", headers=header)

print(rep.json()
```

### Expected Behavior

Return of json like in browser

### Observed Behavior

Returns empty list

**Comment by abhi1693** [comment]
Thank you for opening a bug report. I was unable to reproduce the reported behavior on NetBox v3.5.6. Please re-confirm the reported behavior on the current stable release and adjust your post above as necessary. Remember to provide detailed steps that someone else can follow using a clean installation of NetBox to reproduce the issue. Remember to include the steps taken to create any initial objects or other data.

**Comment by grethler** [comment]
Solved the Problem by changing:
`header = {"Authorization":TOKEN}`
to
`header = {"Authorization": f"Token {TOKEN}}"`
