### ISSUE TITLE
L2VPN no filter for indentifier in GUI

### ISSUE THREAD

**Issue by GSeiNet** [netbox-community/netbox#13223]
### NetBox version

v.3.5.4

### Feature type

Change to existing functionality

### Proposed functionality

In Overlay / L2VPN
Searching for an VNI ID for example is not possible based on VNI_ID Value.
No Filter for identifier is available in GUI
Quicksearch don´t search in "identifier table"

### Use case

Quicksearch of VNI ID in GUI

### Database changes

no changes needed

**Comment by jeremystretch** [comment]
The quick search for L2VPN objects _does_ match against the identifier, as you can see here:

https://github.com/netbox-community/netbox/blob/0f0cf683c44f058a72a50fa90b889ab3fc6bea08/netbox/ipam/filtersets.py#L1060-L1068

If you believe you've encountered a bug, please open a bug report instead, with **explicit reproduction steps**.
