### ISSUE TITLE
Content-Types only fetchable as logged in user

### ISSUE THREAD

**Issue by fabi125** [netbox-community/netbox#13237]
### NetBox version

v3.5.6

### Python version

3.11

### Steps to Reproduce

Config settings:
```
LOGIN_REQUIRED = False
EXEMPT_VIEW_PERMISSIONS = ["*"]
```

Try to access `/api/extras/content-types/`

### Expected Behavior

List of content types is returned.

### Observed Behavior

`{"detail":"Authentication credentials were not provided."}`

This view only uses `IsAuthenticated` while other views use `IsAuthenticatedOrLoginNotRequired`, which I believe is what should be used for `ContentTypeViewSet` as well.

**Comment by kkthxbye-code** [comment]
> This view only uses IsAuthenticated while other views use IsAuthenticatedOrLoginNotRequired, which I believe is what should be used for ContentTypeViewSet as well.

Seems right on the money. Would you like to submit a PR?

**Comment by fabi125** [comment]
> > This view only uses IsAuthenticated while other views use IsAuthenticatedOrLoginNotRequired, which I believe is what should be used for ContentTypeViewSet as well.
> 
> Seems right on the money. Would you like to submit a PR?

Sure! I'll put one up today or tomorrow!
