### ISSUE TITLE
Allow certain device type to be excluded from rack utilization percentage

### ISSUE THREAD

**Issue by thefreakquency** [netbox-community/netbox#13230]
### NetBox version

v3.5.6

### Feature type

Change to existing functionality

### Proposed functionality

Currently, any device that is assigned to a rack unit counts towards the percentage of use of the given rack. 
As an example, when documenting what has been installed, if someone puts in the blank panels as it's really installed in the rack for airflow management, rack utilization can go up to 100% when in fact, "real" equipment is only partially using the overall space. 

I would like to have a way to discriminate what is counted, so we can have a real idea of the current real use. By having a flag in the Device Type, or on the device itself, that allow the user to specify this should be excluded from utilization calculation. 

### Use case

We document everything that is installed in the rack. This helps planner know that if a 5U filler plate has to be replaced for something smaller, that he takes that into account when he plan a server install. Same goes for hardware removal. 

### Database changes

Adding the new "flag" would most likely require a single new field in either Device Type or Device Table. 

### External dependencies

None

**Comment by SirVilhelm** [comment]
I stumbled across this while googling for this exact solution. We record rack fillers and they make each of our racks show 100% utilization
