### ISSUE TITLE
Issue saving group ruleset with permissions on DCIM>Interfaces and Virtualization>Interfaces

### ISSUE THREAD

**Issue by ConvexSERV** [netbox-community/netbox#13240]
### NetBox version

v3.5.5

### Python version

3.8

### Steps to Reproduce

Added a Group Permission on DCIM > Interface, applied to a given group, and constrained by `{"device__tenant__slug": "tenant-name"}`.

Then add another Group Permission on Virtualization > Interface, applied to the same group, and constrained by  `{"virtual_machine__tenant__slug": "tenant-name"}`.

I was unable to save the ruleset for the group with the following error: Objectpermission-group relationship with this Objectpermission and Group already exists.

### Expected Behavior

The ruleset should save without errors.

### Observed Behavior

Error returned is: Objectpermission-group relationship with this Objectpermission and Group already exists.

I found a workaround, which is to apply the rule to each user in the group instead of the group. I can save the permission and the effect is the same in the application. 
Afterwards, I can go back into the permission entry (the group will be there already), and remove the users. Then ruleset will save without an error.

BTW - Thanks for all of your hard work!

**Comment by kkthxbye-code** [comment]
I cannot replicate this. Please revise your steps.

![image](https://github.com/netbox-community/netbox/assets/400797/adcec7c0-f628-4c5a-9d9e-4192708c6a26)

**Comment by DanSheps** [comment]
I think this is, unfortunately, a quirk of the Django permissions system.

The permission creation window is opened in a new tab/window, when you create the permission, you can assign it to the group within hte permission.  This doesn't update it within the group itself, but the permission is already assigned to the group from assigning it in the  permission creation page.

**Comment by ConvexSERV** [comment]
@DanSheps that sounds right to me. I was originally thinking that it had to do with device and vm interfaces, but when I went in to reproduce the error, I found the same behavior setting a permission on a completely different object. Please close for now. The work around works if I run into it again.
