### ISSUE TITLE
Accept prefix_length parameter on GET Request

### ISSUE THREAD

**Issue by shepherdjay** [netbox-community/netbox#13268]
### NetBox version

v3.5.4

### Feature type

New functionality

### Proposed functionality

Currently the API only accepts a `prefix_length` parameter to POST. This request is to also allow the parameter to be provided via the GET method.

### Use case

Would allow for performing simpler analysis and/or filtering for a parent prefix by providing support native to the API instead of relying on user to perform instead.

### Database changes

N/A

### External dependencies

N/A

**Comment by jeremystretch** [comment]
The `mask_length` filter is available to filter prefixes by length.
