### ISSUE TITLE
Custom Field Bulk Import | Server Error 

### ISSUE THREAD

**Issue by Etibru** [netbox-community/netbox#13263]
### NetBox version

3.5.6

### Python version

3.10

### Steps to Reproduce

1. From a new Netbox installation
2. Create a basic custom field 
3. Export user interface custom field in CSV format
4. Delete the last custom field created  
5. Import from files (with last CSV)

--> Server Error 

### Expected Behavior

We should have the custom field imported into netbox

### Observed Behavior

Server Error
There was a problem with your request. Please contact an administrator.

The complete exception is provided below:

<class 'AttributeError'>

'NoneType' object has no attribute 'app_label'

Python version: 3.10.6
NetBox version: 3.5.6

**Comment by jeremystretch** [comment]
Thank you for opening a bug report. Unfortunately, the information you have provided is not sufficient for someone else to attempt to reproduce the reported behavior. Remember, each bug report must include detailed steps that someone else can follow on a clean, empty NetBox installation to reproduce the exact problem you're experiencing. These instructions should include the creation of any involved objects, any configuration changes, and complete accounting of the actions being taken. Also be sure that your report does not reference data on the public NetBox demo, as that is subject to change at any time by an outside party and cannot be relied upon for bug reports.

**Comment by Etibru** [comment]
The easiest way to reproduce the error is to follow the _Steps to reproduce_ in my last comment.

With the latest Netbox installation, you go through the user interface to http://{MyNetboxUrl}/extras/custom-fields/import/ and you can choose Direct Import or Upload File and you put this file following CSV (the csv is created by the Netbox custom fields export) :

```cvs
Name,Content types,Label,Group name,Type,Required,Description,ID,Default,Search weight,Filter logic,UI visibility,Cloneable,Display weight,Choices,Created,Last updated
Test,circuits.circuit,,,Text,False,,2,,1000,Loose,Read/Write,False,100,[],2023-07-25 14:18,2023-07-25 14:18

```

**Comment by kkthxbye-code** [comment]
Your column names are wrong, please check the FAQ:

https://github.com/netbox-community/netbox/wiki/Frequently-Asked-Questions#why-cant-i-pass-exported-data-directly-into-the-import-form
