### ISSUE TITLE
Device ID / Primary MAC Address

### ISSUE THREAD

**Issue by CADbloke** [netbox-community/netbox#13276]
### NetBox version

3.5.6

### Feature type

Data model extension

### Proposed functionality

related to #8137 could we also please add the Device's `Chassis Id` /  primary MAC address to the Device model?  

### Use case

Network Ops guys / gals said it would be really handy. Correlates with LLDP reports.

### Database changes

add a `Chassis Id` field to the device table.

### External dependencies

none

**Comment by kkthxbye-code** [comment]
Thank you for your interest in extending NetBox. Unfortunately, the information you have provided does not constitute an actionable feature request. Per our [contributing guide](https://github.com/netbox-community/netbox/blob/develop/CONTRIBUTING.md), a feature request must include a thorough description of the proposed functionality, including any database changes, new views or API endpoints, and so on. It must also include a detailed use case justifying its implementation. If you would like to elaborate on your proposal, please modify your post above. If sufficient detail is not added, this issue will be closed.

**Comment by jeremystretch** [comment]
You also have not provided a use case.

**Comment by jeremystretch** [comment]
This issue is being closed as no further information has been provided. If you would like to revisit this topic, please first modify your original post to include all the requested detail, and then ask that the issue be reopened.

**Comment by CADbloke** [comment]
### use case: 
I am not a network ops person so I cannot give a specific detailed use-case. I could invent one but I don't think it would be convincing. They told me it would be useful to see Chassis ID / MAC as part of the device data and I believed them. I suppose they identify devices by their MAC address. 

- The Database change **is** in the issue request. 
- The Device view would need to include the Chassis Id. 
- no new API endpoints

If you don't feel this is a useful addition then just say "no". We will just have to use a custom field instead. I thought others may find it handy too.
