### ISSUE TITLE
Cables/UI: Unable to change from front to rear while editing cable

### ISSUE THREAD

**Issue by jweiher** [netbox-community/netbox#13278]
### NetBox version

v3.5.6

### Feature type

Change to existing functionality

### Proposed functionality

Currently, if someone accidentally connects a cable to the rear port instead of the front port, the entire cable must be deleted and created again. It would be nice to be able to change not only the port number but also the location (front/rear) when editing the cable. This might just be an ui change as the api seems to allow to change it.

### Use case

It is not necessary to delete the cable and enter all information (label, length etc) again. You can just reconnect it.

**Comment by atolgac** [comment]
More broadly , same applies if you need to change termination type (front , rear , interface etc.) of one end you have to delete cable (and lose history)

**Comment by jeffgdotorg** [comment]
Giving this one a little bump. Who wants to take a run at it?

**Comment by eronlloyd** [comment]
This would be very helpful. One of our team members spent a whole entering cable terminations in the wrong direction, and being able to edit this instead of starting over would be fantastic.
