### ISSUE TITLE
Keycloak SSO

### ISSUE THREAD

**Issue by grethler** [netbox-community/netbox#13289]
### NetBox version

v3.5.6

### Python version

3.10

### Steps to Reproduce

Follow this tutorial: https://python-social-auth.readthedocs.io/en/latest/backends/keycloak.html and add those to the configuration.py.
Then on the login screen klick "keycloak"
![image](https://github.com/netbox-community/netbox/assets/94571573/006166f1-983c-466e-bab7-fcf33c7c8c28)

### Expected Behavior

Login

### Observed Behavior

URI:
`https://<tenant>/oauth/login/keycloak/None?client_id=None&redirect_uri=https://<tenant>/oauth/complete/keycloak/&state=<state>&response_type=code
`
PAGE NOT FOUND:
/oauth/login/keycloak/None
The requested page does not exist.

**Comment by jeremystretch** [comment]
Thank you for opening a bug report. Unfortunately, the information you have provided is not sufficient for someone else to attempt to reproduce the reported behavior. Remember, each bug report must include detailed steps that someone else can follow on a clean, empty NetBox installation to reproduce the exact problem you're experiencing. These instructions should include the creation of any involved objects, any configuration changes, and complete accounting of the actions being taken. Also be sure that your report does not reference data on the public NetBox demo, as that is subject to change at any time by an outside party and cannot be relied upon for bug reports.

**Comment by abdurrm** [comment]
i use latest release, and keycloak working fine.

check your config, maybe you need add this to your env
REMOTE_AUTH_BACKEND=social_core.backends.keycloak.KeycloakOAuth2

**Comment by grethler** [comment]
@abdurrm These are the configs I have:
REMOTE_AUTH_ENABLED=True
REMOTE_AUTH_BACKEND="social_core.backends.keycloak.KeycloakOAuth2"
SOCIAL_AUTH_KEYCLOAK_KEY="<key>"
SOCIAL_AUTH_KEYCLOAK_SECRET="<secret>"
SOCIAL_AUTH_KEYCLOAK_PUBLIC_KEY="<pub_key>"
SOCIAL_AUTH_KEYCLOAK_AUTHORIZATION_URL="<url>"
SOCIAL_AUTH_KEYCLOAK_ACCESS_TOKEN_URL="<url>"
SOCIAL_AUTH_KEYCLOAK_ID_KEY="email"

**Comment by grethler** [comment]
I am using netbox-docker aswell.

**Comment by deto1986** [comment]
@grethler I have a fix, set these parameters in not in the .env file, instead you have set these parameters directly in the configuration/configuration.py file as python variables. I think the documentation is kinda misleading here but more or less the documentations tells us that we have to use the configuration.py and not environment variables.

I now can login with keycloak but after that my new created user have no authority to do something. I have not seen that I can use claims from the OpenID Connect provider to make this work. The python-social-auth documentation is a bit hard to read :(

**Comment by abdurrm** [comment]
Yes, me too. I login as admin (local), then manually set the keycloak users
to superuser.

**Comment by jeremystretch** [comment]
There does not appear to be any action needed on this issue, so I'm going to close it.

**Comment by delbra1n** [comment]
> @grethler I have a fix, set these parameters in not in the .env file, instead you have set these parameters directly in the configuration/configuration.py file as python variables. I think the documentation is kinda misleading here but more or less the documentations tells us that we have to use the configuration.py and not environment variables.
> 
> 
> 
> I now can login with keycloak but after that my new created user have no authority to do something. I have not seen that I can use claims from the OpenID Connect provider to make this work. The python-social-auth documentation is a bit hard to read :(

This is the Solution.
