### ISSUE TITLE
Unable to move primary IP to interface on the same device

### ISSUE THREAD

**Issue by PieterL75** [netbox-community/netbox#13292]
### NetBox version

v3.5.6

### Python version

3.10

### Steps to Reproduce

1. Create a device with 2 interfaces 
2. Create an IP
3. Assign the IP to Interface1 and make it the  primary ip for the device
4. Edit the IP and re-assign it to Interface2 of that device

### Expected Behavior

The widget should allow to move the IP to an interface of the same device

### Observed Behavior

The Widget is totally grayed out. Moving an IP to another interface on the same device is not possible.
![image](https://github.com/netbox-community/netbox/assets/74899468/fb79fc3d-fa72-4900-aaa9-b15344ff6b33)

This is introduced in https://github.com/netbox-community/netbox/issues/11934
That Bugreport is about moving it to another device. 
But due to the improvement of our netbox data, we have to move IPs from the 'general' IPs interface to a more specific interface on the device.

**Comment by jeremystretch** [comment]
This is a known limitation of the solution implemented to resolve #11934. The designation of the IP address as primary for the device must be removed before the IP address can be reassigned.
