### ISSUE TITLE
IPAddress Interface dropdown shows all interfaces, not only device ones

### ISSUE THREAD

**Issue by PieterL75** [netbox-community/netbox#13293]
### NetBox version

v3.5.6

### Python version

3.8

### Steps to Reproduce

1. Create several devices with interfaces
2. create an IP address
3. assign the IP to an interface

This IP is now assigned to an interface of a device

1. edit the IP adress
2. open the dropdown of the 'interfaces
![image](https://github.com/netbox-community/netbox/assets/74899468/1333bd83-9029-4dac-a79c-10e63d4c21d4)

### Expected Behavior

The dropdown should only display the interfaces of the device it is assigned to.
If it needs to move to another device, then the 'filter' can be used.

That filter also is not aware of the device the IP/Interface belonged to
![image](https://github.com/netbox-community/netbox/assets/74899468/470fbf94-582a-482e-b2b4-8bb150bb3f75)
It should at least already show the 'Device' field with the device.

### Observed Behavior

All interfaces of all devices are in the dropdown
The filter is not helping a lot, and needs a lot of clicking to get the proper filter setup (Click Filter, Check Device, Click devicefield, Type devicename, Click proper device, click to close the dropdown, click search)

**Comment by DanSheps** [comment]
Once PR #13296 is merged. we can piggyback to fix this one too, at least the first part of it.

**Comment by ITJamie** [comment]
related: https://github.com/netbox-community/netbox/issues/12751

**Comment by ITJamie** [comment]
> Once PR #13296 is merged. we can piggyback to fix this one too, at least the first part of it.

@DanSheps now that the above got merged is there anything blocking this?

**Comment by jeremystretch** [comment]
Marking this as blocked by #12751 for now.
