### ISSUE TITLE
Quick search on circuit doesn't match terminations (side A & Z)

### ISSUE THREAD

**Issue by CTV-2023** [netbox-community/netbox#13295]
### NetBox version

v3.5.6

### Python version

3.8

### Steps to Reproduce

Reproduced on demo website
1. Create a circuit
2. "Attach" the circuit to a termination (side A and/or Z)
![image](https://github.com/netbox-community/netbox/assets/64533932/b791c00b-ae87-4b3b-9517-5e6aa90b1ca0)

4. Run a quick search on a termination
![image](https://github.com/netbox-community/netbox/assets/64533932/3bdde993-33e3-4e91-85c9-0f212df37193)

 

### Expected Behavior

The quick search should match terminations

### Observed Behavior

Nothing is found. 
The only ways to find the termination (in this example circuit details for Site called "Port Mahon") are : 
- Searching the info from the site itself
- Using filters, which makes the search far longer and less user friendly (more clicks)
- Using control + f if you display enough lines / don't have a big circuit database
- As a workaround with quick search, add the site name in description or comments field

**Comment by jeremystretch** [comment]
This is intentional behavior. If you would like to propose this as new functionality, please submit a feature request including justification.
