### ISSUE TITLE
Replace format() with f-strings

### ISSUE THREAD

**Issue by DanSheps** [netbox-community/netbox#13298]
### Proposed Changes

Replacing any instance of format() with f-strings.

### Justification

As per @jsenecal in [#13296](https://github.com/netbox-community/netbox/pull/13296#discussion_r1277904558_) f-strings offer some minor optimizations for performance and code readability.

We should replace format() where possible

**Comment by jeremystretch** [comment]
As I explained on Friday, the use of `format()` in many places is required to support translation, which is currently an ongoing initiative for v4.0. Please do not start making blanket changes to format strings until that work has been completed.

In the meantime, I'll point out that there are currently [41 open bug reports](https://github.com/netbox-community/netbox/issues?q=is%3Aissue+is%3Aopen+no%3Aassignee+label%3A%22type%3A+bug%22) looking for owners.

**Comment by jeremystretch** [comment]
We can continue to replace calls to `format()` opportunistically where appropriate, but I don't think we'll ever be in a place to justify the effort of a concerted audit for this.
