### ISSUE TITLE
Custom Field UI - hidden if unset - independent of rw/ro

### ISSUE THREAD

**Issue by whtkam** [netbox-community/netbox#13299]
### NetBox version

v3.5.7

### Feature type

Change to existing functionality

### Proposed functionality

I have many custom fields which only apply to a part of e.g. devices. With the "UI visibility" = "Hidden(if unset)" you can keep the UI clean for each device and you only see those that are set for the device. The problem and hence the feature reqest the "if unset" option should be independent of "Read/Write" or "Read only" option.

**UI visibility:**
- Read/Write
- Read/Write(if unset)
- Read-only
- Read-only(if unset)
- Hidden

or maybe with a checkbox

**UI visibility:**
- Read/Write
- Read-only
- Hidden

- [ ] Hidden if unset

### Use case

I have custom fields that are Ready-only but I don't want them to appear in the UI on every device as they have no meaning for those devices. So it would be good if I could select read-only and "hidden if unset". Maybe there is another way to achieve this, but I haven't found any.

**Comment by jeremystretch** [comment]
I'm going to propose replacing the current `ui_visibility` field with two new fields:

* `ui_editable` (boolean): True or false
* `ui_visible` (choice): Always, if set, hidden

The former will control whether the custom field value can be modified using the web UI; the later will control whether a custom field is displayed in the web UI. As with the current field, neither will have any impact on REST or GraphQL API operation.

This will obviously result in a breaking API change, but we'll be able to migrate existing custom fields automatically.

**Comment by jeremystretch** [comment]
Thinking about this further, it might make sense to give `ui_editable` three options:

* Yes
* No
* Hidden

Selecting "no" would still include the custom field in the object edit form with a read-only (disabled) widget. Selecting "hidden" would omit it completely.

**Comment by thefreakquency** [comment]
I would looooooove if this could also apply to other default fields showed in UI, as described in https://github.com/netbox-community/netbox/issues/5777 .

**Comment by jeremystretch** [comment]
> I'm curious what others' use case is for showing readonly fields within the add/edit form, if their value cannot be changed there.

For me it's about providing consistency. A user may be confused if they see a custom field displayed in the UI but absent in the object edit form. Rendering it as a disabled form field provides assurance that the field is not "missing." Some administrators still may prefer to omit it from the form anyway, so we provide both options.

**Comment by cpund** [comment]
Could I suggest another option to `ui_visible`? It'd be nice to have a field hidden when viewing (not editing) a device? While not a huge necessity, it's nice to clean out some cruft when just viewing the device. My use case for this is when creating a device, I've got a custom field that stores the SolarWinds NodeID of a device. This field powers the custom link to link directly to the monitoring page for the device. Something like this custom field doesn't need to be shown when just viewing a device.

**Comment by mmahacek** [comment]
What about these settings?

- `ui_editmode` (choice): Read/Write, Read-Only, hidden
- `ui_viewmode` (choice): Always, if set, hidden
