### ISSUE TITLE
Software and Hardware  lifecycle management

### ISSUE THREAD

**Issue by ognjen011** [netbox-community/netbox#13305]
### NetBox version

v3.5.6

### Feature type

Data model extension

### Proposed functionality

We have a bunch of different types of routers/servers with different OS versions. Under Devices a new option for Software and Hardware lifecycle or somewhere there with sub menu to divide software from the hardware.  It would be really nice to be able to have as part of Netbox different images versions so that we can track the following options about these images,  recommended version, current version installed, end of life for software ,LTS versions releases  for the images. Same thing for the hardware to be able to see end of support for hardware, end of support contract with a vendor. End of software support end of security patches for the given hardware. 

### Use case

We have a bunch of different types of routers/servers with different OS versions. This would help with automating and planning upgrades. This allows better planing of the current inventory. It will prevent for the most part running versions of images that might already be  end of life and unsupported by the vendor. I guess it will help to make sure that a specific reales that are running in the network do not have any serious vulnerability attached to that version of software release. 

### Database changes

Not sure what needs to change in the DB

### External dependencies

None

**Comment by abhi1693** [comment]
Thank you for your interest in extending NetBox. Unfortunately, the information you have provided does not constitute an actionable feature request. Per our [contributing guide](https://github.com/netbox-community/netbox/blob/develop/CONTRIBUTING.md), a feature request must include a thorough description of the proposed functionality, including any database changes, new views or API endpoints, and so on. It must also include a detailed use case justifying its implementation. If you would like to elaborate on your proposal, please modify your post above. If sufficient detail is not added, this issue will be closed.

**Comment by jsenecal** [comment]
@ognjen011, I would recommend looking for similar conversations in discussions (or start one) but otherwise this seems more like a feature that would be implemented in a plugin.
