### ISSUE TITLE
Sensitive parameter masking broken

### ISSUE THREAD

**Issue by ryanmerolle** [netbox-community/netbox#13304]
### NetBox version

v3.5.7

### Python version

3.10

### Steps to Reproduce

Browse to a datasource such as https://demo.netbox.dev/core/data-sources/1/

### Expected Behavior

The password should be hidden as per #12625

### Observed Behavior

The password is seen.

**Comment by abhi1693** [comment]
If you are looking as admin that must be why you are still seeing the password. It's only hidden when you don't have the appropriate change permission for the data source

**Comment by ryanmerolle** [comment]
Ah my bad.  Maybe I’ll change this to a documentation update to make it clear
