### ISSUE TITLE
Deletion of interface silently deletes all assigned IPs

### ISSUE THREAD

**Issue by aldem** [netbox-community/netbox#13307]
### NetBox version

v3.5.7

### Python version

3.11

### Steps to Reproduce

1. Create one or more IPs and assign them to an interface on any device
2. Delete the interface
3. Observe that all associated IPs are deleted

### Expected Behavior

Either this should not be possible at all or at least confirmation must be required, though I would prefer to just remove assignments from IPs (as an optional choice on confirmation form).

### Observed Behavior

All assigned IPs are silently deleted.

Cascading deletion of associated data without even asking confirmation is quite unexpected behavior, especially taking into account that there is no "undo".

There is a similar issue reported long time ago (https://github.com/netbox-community/netbox/issues/6015) for NetBox v2, but problem is still here - and it is a real problem, especially if there are multiple IPs assigned.

**Comment by jeremystretch** [comment]
This is expected behavior. If you would like to propose a change to this behavior, as in #6015, please submit a detailed feature request proposing the new behavior and citing justification for the change.
