### ISSUE TITLE
Copy tags from Device-Type when creating new device

### ISSUE THREAD

**Issue by ekrichbaum** [netbox-community/netbox#13318]
### NetBox version

v3.5.7

### Feature type

Change to existing functionality

### Proposed functionality

Copy any tags applied to the device-type to a newly created device of that type.

### Use case

With bulk edit, we can easily add a tag to existing items. Creating a new device of a specific type would not need an edit if the tags propagated to the device.

A tag, such as "End of Sale - Nov 2023", can be then applied to any devices created as they come into the warehouse and will be visible on a list without further edits. Our warehouse doesn't have any information about EOS/EOL etc. and doesn't handle the ordering, just the addition to inventory.

### Database changes

None

### External dependencies

None

**Comment by kkthxbye-code** [comment]
My personal opinion is that this isn't a great idea. We use tags on device types and we use tags on devices, and they can differ. Tags on devicetypes apply to all the devices of that devicetype, while individual devices of that devicetype can have different tags based on different characteristics.

If we were to do this, I think we should retain the current functionality, but provide a new field with "Replicated tags" or whatever you want to call it.

**Comment by jeremystretch** [comment]
> A tag, such as "End of Sale - Nov 2023", can be then applied to any devices created as they come into the warehouse and will be visible on a list without further edits. 

But this designation applies to the device _type_, not the individual devices. For example, it wouldn't make sense to label one device EoS and not label another of the same model. I suggest keeping the tags on the device type, and then filtering devices by those types to find all affected devices.

**Comment by ekrichbaum** [comment]
The reason it came up was that a tenant filtered list of inventory can show tags but wouldn't in that case. Someone would have to either a.) know that a particular device type has a tag, or manually look up each type of device and add tags to the exported inventory.

Right now, one process is to create the device, assign the same tags. Another is to filter all devices from the device type and bulk add the tags. Neither are horrible, just an extra step. The thought being if I am creating a new device, that step should be removed. Not even considering the second case.

**Comment by jeremystretch** [comment]
Closing this out due to the opposition as noted above.
