### ISSUE TITLE
New custom field data type, time

### ISSUE THREAD

**Issue by Xemanth** [netbox-community/netbox#13331]
### NetBox version

v3.5.6

### Feature type

Data model extension

### Proposed functionality

I could find from the custom fields only field types:
Date & time
Date

Is it possible to have a custom field type for only "Time"?

### Use case

This field is needed; for example, if I want to assign to a virtual machine daily reboot time, clock 21:00.

**Comment by ITJamie** [comment]
out of interest, how would you handle timezone with this field...

**Comment by Xemanth** [comment]
> out of interest, how would you handle timezone with this field...

I would handle timezone similarly as Netbox handles it with "Date" & "Date&Time"field types.
If it would not follow Netbox's timezone, I would then type to my Time field label what timezone it is. In my case, it would be UTC+3.
