### ISSUE TITLE
Visual glitch in pagination

### ISSUE THREAD

**Issue by peteeckel** [netbox-community/netbox#13351]
### NetBox version

v3.6-beta1

### Python version

3.8

### Steps to Reproduce

Open any list view

### Expected Behavior

The pagination indicator at the bottom shows something like "Showing 1-25 of 123"

### Observed Behavior

The pagination indicator at the bottom shows "Showing - of"

![Screenshot 2023-08-02 at 19 52 20](https://github.com/netbox-community/netbox/assets/6815386/c5fd301d-c58f-47c3-9c8b-7b8950cfe866)

**Comment by peteeckel** [comment]
That's probably the same issue, correct?

![Screenshot 2023-08-02 at 20 29 59](https://github.com/netbox-community/netbox/assets/6815386/fa82b3f0-af00-41b4-9717-05abecb40eb2)

**Comment by jeremystretch** [comment]
> That's probably the same issue, correct?

Correct. Pushing a fix in a few minutes.
