### ISSUE TITLE
object location history - track where objects have been

### ISSUE THREAD

**Issue by ITJamie** [netbox-community/netbox#13357]
### NetBox version

v3.5.7

### Feature type

Change to existing functionality

### Proposed functionality

When a device is added/removed or its position moved in a rack it would be awesome if there was a changelog visible on the rack object (this could be in a separate panel rather than in the existing changelog).

On device save it would check to see if the position/rack changes. if so insert the change into the new model (see below)

### Use case

when viewing a rack it would be great to see the "related" changes to the rack.

### Database changes

I believe trying to filter the existing changelog for this information would be computationally expensive, so a new model would probably be recommended

model to hold a list of device position changes:
 - datetimestamp?
 - device id
 - rack_id_before_change
 - rack_id_after_change
 - position_before_change
 - position_after_change
 - device_changelog_id (useful to be able to link to the full device changelog where, until that changelog is purged...)

**Comment by abhi1693** [comment]
This feels like an anti-pattern for Changelog to me. Although, the request sounds good but having a separate changelog for such a specific purpose does not feel right. This can be achieved using a plugin that intercepts the post_save signals and then processes the information into the DB as you have mentioned. You can then attach a tab to the view and get a similar implementation.

**Comment by bitcollector1** [comment]
I kind of like this idea. I'm using SUZIEQ to track where a mac address has been but this could be a nice feature to have in NetBox itself.

**Comment by jsenecal** [comment]
Marking this as a plugin candidate - Thanks for your suggestion @ITJamie
