### ISSUE TITLE
Allow for base choices only in CustomFieldChoices

### ISSUE THREAD

**Issue by rodvand** [netbox-community/netbox#13361]
### NetBox version

v3.6-beta1

### Feature type

Change to existing functionality

### Proposed functionality

Remove the required flag on the Extra Choices field on Custom Field Choices.

### Use case

If I want a custom field with only the airport codes, I don't want to add any extra choices. I would like to select the Base Choices and leave it at that. Currently I am forced to add an extra choice to be able to use the base choices.

### Database changes

I assume it means the extra choices field must be set to not required. It will however need extra validation to make sure you either choose a set of base choices or add some extra choices.

**Comment by jeremystretch** [comment]
This field is meant to be optional (and is on the model itself). Looks like a bug with the form.
