### ISSUE TITLE
custom field - selection - object - custom filter

### ISSUE THREAD

**Issue by ITJamie** [netbox-community/netbox#13364]
### NetBox version

v3.5.7

### Feature type

Data model extension

### Proposed functionality

On custom fields where Type is Object or Multiple Objects it would be great to have a filter option to limit the objects available to choose.
It would be great if that filter supported referencing the current object too.

### Use case

for example. 

new custom field
contenttype: device, Type:object, Object Type: IP address. 

a custom filter (similar to the dashboard filter logic) to limit the choices could be defined, thus when editing a device it would limit the amount of ips available to choose from. 

uses:
on a device/vm object: limiting IP address's to ones assigned to the device/vm
on a device object: limiting a device selection to devices in the same rack as the object
on a rack object: limiting a device selection to items in that rack

### Database changes

additional field on custom fields model to store filter string

**Comment by jeremystretch** [comment]
@ITJamie I'm afraid it's not clear from your description what specific change(s) you're proposing. Would you like to expand on the implementation you have in mind? How would the "filter string" you mention work?

**Comment by jeremystretch** [comment]
This issue is being closed as no further information has been provided. If you would like to revisit this topic, please first modify your original post to include all the requested detail, and then ask that the issue be reopened.
