### ISSUE TITLE
Custom Field Choice Sets - not working

### ISSUE THREAD

**Issue by whtkam** [netbox-community/netbox#13393]
### NetBox version

v3.6-beta1

### Python version

3.8

### Steps to Reproduce

I tried the new Custom Field Choice Set on the demo instance.

1. Create Custom Field Choice Sets: "123"
2. define 3 choices
_1,ONE
2,TWO
3,THREE_
3. Create a Custom Field: object type: "dcim | device" name: "123" label:"123" group:"Special" type: "Selection" Choice Set:"123"
4. Edit custom field: "123" on existing device --> error pops up

### Expected Behavior

Select a choice without error

### Observed Behavior

Error-Popup

 _Markdown syntax is supported
2023-08-06 08:29 UTC netbox-beta (v3.6-beta1)
Error Fetching Options for field 'cf_123'_

**Comment by jeremystretch** [comment]
I'm not able to reproduce this on the current `feature` branch. It's likely the bug has already been resolved under #13363.

**Comment by wypxl** [comment]
> I'm not able to reproduce this on the current `feature` branch. It's likely the bug has already been resolved under #13363.
I saw you are very active in the community, can you tell me how to add a choice set？
