### ISSUE TITLE
Upgrade GraphiQL

### ISSUE THREAD

**Issue by arthanson** [netbox-community/netbox#13396]
### Proposed Changes

Upgrade GraphiQL - the current stack uses "graphiql": "1.4.1" which is several major versions behind.  The new version is 3.0.5.  Also the netbox-graphiql uses an abandoned subscriptions-transport-ws which is superseded by graphql-ws.

### Justification

Using a several major version outdated version of GraphiQL and it is using a package that is no longer maintained.  I also believe there is are several security patches for GraphiQL.

**Comment by mr1716** [comment]
Even an upgrade to 1.4.7 would fix some of the security issues. If desired in the short term
