### ISSUE TITLE
Issue with any object that touches device

### ISSUE THREAD

**Issue by DamienUKCEH** [netbox-community/netbox#13398]
### NetBox version

V3.5.7

### Python version

3.10

### Steps to Reproduce

create a text field object on device 
I added
![Screenshot 2023-08-07 122854](https://github.com/netbox-community/netbox/assets/98539593/66053dc8-5b90-40c3-b6aa-b6df70995a76)

then open devices

Server Error
There was a problem with your request. Please contact an administrator.

The complete exception is provided below:

<class 'AttributeError'>

'ImageDraw' object has no attribute 'textsize'

Python version: 3.10.6
NetBox version: 3.5.7

When removing the text object this hasn't fix the issue.

### Expected Behavior

Expected is the device page opens as normal.

### Observed Behavior

Server Error
There was a problem with your request. Please contact an administrator.

The complete exception is provided below:

<class 'AttributeError'>

'ImageDraw' object has no attribute 'textsize'

Python version: 3.10.6
NetBox version: 3.5.7

![Screenshot 2023-08-07 122813](https://github.com/netbox-community/netbox/assets/98539593/71ddcf35-8863-40ab-8a1b-14922127e9bb)

**Comment by jeremystretch** [comment]
This is not a NetBox bug and has already been raised several times. Please remember to search existing issues before creating a new one.
