### ISSUE TITLE
Circuits should relate to sites

### ISSUE THREAD

**Issue by travisjohnsonga** [netbox-community/netbox#13407]
### NetBox version

v3.5.3

### Feature type

Change to existing functionality

### Proposed functionality

Circuits should have site association with them rather than tenant.  

### Use case

Circuits are installed at sites more specifically than tenants.

Tenants -> Sites -> Circuits

### Database changes

foreign key relationship between circuits and sites

### External dependencies

none that I am aware of

**Comment by kkthxbye-code** [comment]
> Circuits should have site association with them rather than tenant.

I would recommend reading the docs, as it seems like you are using circuits for something they are not intended for.

https://docs.netbox.dev/en/stable/features/circuits/#circuits_1

>A circuit is a physical connection between two points, which is installed and maintained by an external provider. For example, an Internet connection delivered as a fiber optic cable would be modeled as a circuit in NetBox.

https://docs.netbox.dev/en/stable/models/circuits/circuit/

> A circuit represents a physical point-to-point data connection, typically used to interconnect sites across considerable distances (e.g. to deliver Internet connectivity).

Circuits gets their site associations from the A and/or Z termination. A circuit within one site would just be a cable imo. I'll close this as it really doesn't make any sense with the netbox datamodel and there really isn't enough in this FR to be actionable anyway.

Feel free to update it and ping me, and I'll have another look.
