### ISSUE TITLE
Request to add SFP28 (64GFC) and SFP28-DD (32GFC) interface type options

### ISSUE THREAD

**Issue by pdehaas** [netbox-community/netbox#13429]
### NetBox version

v3.5.7

### Feature type

Data model extension

### Proposed functionality

Currently the SFP28 (64GFC) interface is missing from the interface list.
this exists on broadcom switches as described below

SFP28-DD (32GFC) is in use in the following hardware
both interfaces are available on the device below

https://docs.broadcom.com/doc/G720-Switch-PB

### Use case

This allows us to specify the correct interface type when modeling our dc in netbox because we use this hardware.

### Database changes

i assume no database changes are required not required as the field already exists.

### External dependencies

none

**Comment by DanSheps** [comment]
Are you sure they are SFP28?  According to the datasheet, they are SFP+

**Comment by apellini** [comment]
Yes they use the same standard for SFF committee but are different IEEE standard and having different functionalities and peculiarities it is better to have this choice because sometimes helps knows it. For example if you insert a sfp28 into a sfp+ port it doesn’t work and having this information could help light-out operations.

**Comment by pdehaas** [comment]
Apologies. I'm simply a pass through to our networking team. It seems to indeed be a sfp+ port

**Comment by jeremystretch** [comment]
The SFP+ interface type is limited to 16 Gbps operation; I'm fairly certain 64GFC should be QSFP+, which already exists as an option in NetBox (`QSFP+ (64GFC)`).

It appears that no action is needed. If there _is_ still a need to introduce a new interface type, please submit a new FR linking to the relevant spec and/or product page.
