### ISSUE TITLE
make it more obvious which objects permissions are selected/unselected

### ISSUE THREAD

**Issue by ITJamie** [netbox-community/netbox#13435]
### NetBox version

v3.6-beta1

### Feature type

Change to existing functionality

### Proposed functionality

instead of a current selection box, change to using the selector (move to form on right if selected) type of form field.

### Use case

due to the long list of permissions it can be difficult to notice that some features are not enabled on a permission object.

if the selector type was changed to the type used on the "configure table" popup used on list items (available columns vs selected columns) it would make it more visible as to what permissions are missing

this can be a bit of a pain currently after upgrading netbox when new permissions are added and need to be enabled

### Database changes

n/a

### External dependencies

n/a

**Comment by jeffgdotorg** [comment]
We're going to fold this issue into #14297 and approach both by switching to a dynamic multi-select control.
