### ISSUE TITLE
Add a rename button to the device interfaces list

### ISSUE THREAD

**Issue by opensourceXnetbox** [netbox-community/netbox#13444]
### NetBox version

v3.5.7

### Feature type

New functionality

### Proposed functionality

Rename button under Interfaces, for bulk renaming of interfaces, as available for Devices.

Currently:
![image](https://github.com/netbox-community/netbox/assets/110609354/db719af0-c000-4802-a146-2617f98003d4)

### Use case

Due to different operating systems, the names of the interfaces may change. A bulk update would facilitate the adaptation process.

### Database changes

I do not think so, not sure

**Comment by tagur87** [comment]
@opensourceXnetbox - This functionality is available, but it's under the interfaces tab of a specific device, not under the global device interfaces list. 

See the demo site for an example: https://demo.netbox.dev/dcim/devices/1/interfaces/

**Comment by opensourceXnetbox** [comment]
> @opensourceXnetbox - This functionality is available, but it's under the interfaces tab of a specific device, not under the global device interfaces list.
> 
> See the demo site for an example: https://demo.netbox.dev/dcim/devices/1/interfaces/

Hey @tagur87, yes i know and usually ich will update my interface names via api. But in this case, i will bulk update the interface names from more than one device over GUI, its not possible.

**Comment by tagur87** [comment]
> > @opensourceXnetbox - This functionality is available, but it's under the interfaces tab of a specific device, not under the global device interfaces list.
> 
> > 
> 
> > See the demo site for an example: https://demo.netbox.dev/dcim/devices/1/interfaces/
> 
> 
> 
> Hey @tagur87, yes i know and usually ich will update my interface names via api. But in this case, i will bulk update the interface names from more than one device over GUI, its not possible.

Gotcha, I wondered if that's what you wanted. But wanted to make sure you saw the option under the device. 

I'll take a look at how difficult it is to implement.

**Comment by opensourceXnetbox** [comment]
> > > @opensourceXnetbox - This functionality is available, but it's under the interfaces tab of a specific device, not under the global device interfaces list.
> > 
> > 
> > > 
> > 
> > 
> > > See the demo site for an example: https://demo.netbox.dev/dcim/devices/1/interfaces/
> > 
> > 
> > Hey @tagur87, yes i know and usually ich will update my interface names via api. But in this case, i will bulk update the interface names from more than one device over GUI, its not possible.
> 
> Gotcha, I wondered if that's what you wanted. But wanted to make sure you saw the option under the device.
> 
> I'll take a look at how difficult it is to implement.

@tagur87 really cool, thanks!

**Comment by tagur87** [comment]
I looked it over for about an hour or so, and it's a bit more than I'm capable of. The interfaces view uses the `object_list` base template. It would be quite a bit of work to update that to be like devices. Probably better for a maintainer to do than me.

**Comment by jeremystretch** [comment]
IMO it wouldn't make sense to support this ability for interfaces but not for other device components. We already support bulk renaming under the device-based views for all component types. If we're going to extend this to the global list views as well, we should be consistent.
