### ISSUE TITLE
Interface Speed: 400Gbps 

### ISSUE THREAD

**Issue by bitcollector1** [netbox-community/netbox#13442]
### NetBox version

v3.5.7

### Feature type

Data model extension

### Proposed functionality

Add 400G to the Speed 

<img width="898" alt="Screenshot 2023-08-10 at 17 24 19" src="https://github.com/netbox-community/netbox/assets/50723251/9d9fe02a-ce46-4c18-9cf4-6bb1a2dc053f">

### Use case

We have 400G interfaces and would like to set the speed in NetBox.

**Comment by jeremystretch** [comment]
Assigned to you, @tagur87. I suggest adding an auto-complete option for 200 Gbps as well.

**Comment by tagur87** [comment]
Agreed @jeremystretch 

I have a PR up for review. Let me know if there's anything missing.

**Comment by jdavidson2021** [comment]
> Let's not over-rotate on this. The dropdown is provided merely as a convenience; it is not intended to contain an exhaustive list of options.

We use NetBox device details to auto-generate configs for our network gear.  We utilize the interface speeds in NetBox to define the device interface speed when we are deviating from the default.  So you may not intend for the list to contain an exhaustive list of interface speed options, not keeping the list up to date could cause down-stream problems for tools developed by user of NetBox.

**Comment by bitcollector1** [comment]
I did not even know you could manually add the entries until after I created this request. Anyway, thanks for taking it up.
