### ISSUE TITLE
MPO Connector Type Improvement

### ISSUE THREAD

**Issue by JoeIzzard** [netbox-community/netbox#13447]
### NetBox version

v3.2.1

### Feature type

Change to existing functionality

### Proposed functionality

Expand the MPO connector types to be more detailed. Currently it only lists MPO, however the number of fibre's within the MPO connector are an important aspect. As such we should add:

- MPO12
- MPO16
- MPO24
- MPO36
- MPO48

I would suggest we leave MPO in place so we don't break anyones existing data, and just add the new ones to allow you to be more precise if you want to.

### Use case

Better documentation, especially in connection with #13375 

We mostly use MPO12 however have on occasion found other versions which we only realise at the last minute. Having this documented would be a big improvement.

### Database changes

None, only requires adding more hardcoded connector types.

### External dependencies

None

**Comment by DanSheps** [comment]
I haven't seen 32 and 48 connectors, but apparently they are out there.  IMO I would omit them until someone asks for it.

That said, I would perhaps add 4 and 8.

**Comment by JoeIzzard** [comment]
I am happy to take this work on if I can get approval to do so.

**Comment by DanSheps** [comment]
Assigned to you @JoeIzzard
