### ISSUE TITLE
https://server/netbox/login/?next=/netbox/media-failure/%3Ffilename%3Dsetmode.js

### ISSUE THREAD

**Issue by litebito** [netbox-community/netbox#13462]
### NetBox version

v3.5.7

### Python version

3.11

### Steps to Reproduce

After fresh installation in the following setup:
CentOS Stream 8
following the installation instructions, 
using httpd as webserver

When I browse to the URL
https://server/netbox 
I get nothing more than a white screen, and the browser keeps looping with the URL below:
https://server/netbox/login/?next=/netbox/media-failure/%3Ffilename%3Dsetmode.js

When using the builtin test server on port 8000, I get the login screen.

After this, I also tried with nginx as webserver, this showed the same issue

### Expected Behavior

When browsing to https://server/netbox for the first time
I expected to see the netbox login screen.

### Observed Behavior

I get nothing more than a white screen, and the browser keeps looping with the URL below:
https://server/netbox/login/?next=/netbox/media-failure/%3Ffilename%3Dsetmode.js

**Comment by jeremystretch** [comment]
> NOTE: This form is only for reporting reproducible bugs in a current NetBox installation. If you're having trouble with installation or just looking for assistance with using NetBox, please visit our [discussion forum](https://github.com/netbox-community/netbox/discussions) instead.
