### ISSUE TITLE
Display Manufacturer along with Device type when adding a new device

### ISSUE THREAD

**Issue by pharalambiev** [netbox-community/netbox#13469]
### NetBox version

v3.5.4

### Feature type

Change to existing functionality

### Proposed functionality

When adding a new device in Netbox we need to choose what is its type from a drop-down menu.
If you have more than one device named the same way there is no way to distinguish between different device types, as there are common devices produced by multiple manufacturers. 
In my case its a battery which does not have unique product number or other specific characteristic which can help me to distinguish between different products.

If we can display Manufacturer in the Device type field, or create another field to select the manufacturer, this will solve the issue.
![Screenshot 2023-08-15 134322](https://github.com/netbox-community/netbox/assets/68070717/07a31ce1-74f1-4526-8b7c-12bbec6c5534)
![Screenshot 2023-08-15 134359](https://github.com/netbox-community/netbox/assets/68070717/840fa4b9-a37a-4c40-a421-d91d52c234cb)

### Use case
When you add device and need to select its type, if you have the same device type from multiple manufacturers, you cannot distinguish between them from the drop-down menu.

**Comment by jeremystretch** [comment]
The selector button to the right of the fields opens an advanced filter dialog, which allows you to filter device types by manufacture as well as other attributes.

FYI, the device model in NetBox is not intended to model batteries. You're likely to encounter difficulty using it this way.

**Comment by pharalambiev** [comment]
Thank you Jeremy!

Honestly, I haven't noticed the selector button until you brang it to my
attention :)

This will do the trick!

На вт, 15.08.2023 г. в 15:01 ч. Jeremy Stretch ***@***.***>
написа:
