### ISSUE TITLE
Viewing the changelog of an updated image throws a missing template exception

### ISSUE THREAD

**Issue by gurretp** [netbox-community/netbox#13463]
### NetBox version

v3.5.6

### Python version

3.8

### Steps to Reproduce

1. add a rack
2. upload an image for this rack
3. edit the image and change for a new one
4. save
5. click on the changelog of this particular image

### Expected Behavior

being able to view the previous image

### Observed Behavior

<class 'django.template.exceptions.TemplateDoesNotExist'>

extras/imageattachment.html

Python version: 3.8.16
NetBox version: 3.5.6

**Comment by abhi1693** [comment]
This fails even when the image is uploaded for the 1st time. This is because the changelog expects an object view but the image attachments does not have any
