### ISSUE TITLE
XSS in tenant name

### ISSUE THREAD

**Issue by GJSBRT** [netbox-community/netbox#13476]
### NetBox version

3.4.7

### Python version

3.10

### Steps to Reproduce

1. Create a tenant with the following name ` "><img src=x onerror=alert(1)>`
2. Edit an IP address
3. Open the tenant dropdown menu
4. Observe a alert menu

### Expected Behavior

No js should be executed

### Observed Behavior

An alert was opened

**Comment by kkthxbye-code** [comment]
Duplicate of https://github.com/netbox-community/netbox/issues/12745

Fixed in 3.5.3, please remember to search before opening an issue and always validate on the newest release.
