### ISSUE TITLE
Allow IP addresses or IP Ranges to be assigned to a site like Prefixes ?

### ISSUE THREAD

**Issue by LeDistordu** [netbox-community/netbox#13484]
### NetBox version

v3.5.8

### Feature type

New functionality

### Proposed functionality

Allow IP Addresses and IP Ranges to be assigned to a Site/VLAN like Prefixes

### Use case

Hi, Many of my sites use the same IP ranges and inevitably the same IPs. The philosophy on the Prefixes side is good, but it would be necessary to push the allocation of sites / vlan to IP addresses and ranges.

### Database changes

none

### External dependencies

none

**Comment by LeDistordu** [comment]
sorry, it should be more understandable now

**Comment by jsenecal** [comment]
Unfortunately @LeDistordu this Feature Request is not really actionnable right as it is right now, even more so with your recent edits.

Please make sure your feature request conveys the intent and purpose of such feature and how others could benefit for it and again, perhaps an issue is not the right place to discuss this if you don't have a fully fleshed out idea as explained in our [contributing guide](https://github.com/netbox-community/netbox/blob/develop/CONTRIBUTING.md#bulb-feature-requests)

**Comment by LeDistordu** [comment]
Hi, ok you can close, i open discussion on forum : https://github.com/netbox-community/netbox/discussions/13492
