### ISSUE TITLE
Documentation Error

### ISSUE THREAD

**Issue by kh4y4m** [netbox-community/netbox#13482]
### Change Type

Correction

### Area

Installation/upgrade

### Proposed Changes

Hello :wave:,
there is an error in the documentation under the section: NetBox Documentation > Installation & Upgrade > Upgrading NetBox. At the second step "3. Install the Latest Release" > "Option A: Download a Release".

the following Bash command has to be corrected:
```
# Set $OLDVER to the NetBox version currently installed
NEWVER=3.4.9
sudo cp /opt/netbox-$OLDVER/local_requirements.txt /opt/netbox/
sudo cp /opt/netbox-$OLDVER/netbox/netbox/configuration.py /opt/netbox/netbox/netbox/
sudo cp /opt/netbox-$OLDVER/netbox/netbox/ldap_config.py /opt/netbox/netbox/netbox/
```

`NEWVER=3.4.9` needs to be `OLDVER=3.4.9`

**Comment by jeremystretch** [comment]
Thank you for the notice. This has already been addressed by #13474 and will be corrected upon the next release.
