### ISSUE TITLE
ASN asdot notation

### ISSUE THREAD

**Issue by Serazio** [netbox-community/netbox#13481]
### NetBox version

v3.5.8

### Feature type

New functionality

### Proposed functionality

While adding a new ASN, it should be possible to add the ASN in asdot notation. If asdot notation is used, netbox should automatically calculate the correct asplain for that ASN. 

The same should be possible for ASN ranges. Furthermore the ASDOT notation column should be possible to select in ASN ranges view  

### Use case

Better usability for users. No need for a asdot calculator

**Comment by jsenecal** [comment]
Thank you for your interest in extending NetBox. Unfortunately, the information you have provided does not constitute an actionable feature request. Per our [contributing guide](https://github.com/netbox-community/netbox/blob/develop/CONTRIBUTING.md), a feature request must include a thorough description of the proposed functionality, including any database changes, new views or API endpoints, and so on. **It must also include a detailed use case justifying its implementation.** If you would like to elaborate on your proposal, please modify your post above. If sufficient detail is not added, this issue will be closed. 

I also had to lookup what ASDOT notation was and I'm working for a service provider so this is definitely not common knowledge or widely used as a standard.

**Comment by ITJamie** [comment]
One of my network engineers has requested the ability to display ASN's in ASDOT.
From our POV we would like the ASDOT number displayed on API views and ASN object views in netbox as a read only value.

Here is an example python library that can convert ASN numbers to ASDOT syntax https://github.com/tbaschak/asdot-asplain

I however don't see the value of this request of being able to ADD new asns using ASDOT notation...

**Comment by jeremystretch** [comment]
> Furthermore the ASDOT notation column should be possible to select in ASN ranges view

This is a separate feature request. Please open a separate issue for it.

**Comment by jeremystretch** [comment]
I understand the use case here: the flexibility to input a 32-bit AS number in either ASPLAIN or [ASDOT format](https://datatracker.ietf.org/doc/html/rfc5396) (e.g. as `65536` or `1.0`). This would require extending the relevant form field to accept either format.

I'm marking this as `needs owner` with the understanding that this is the scope of the FR.

(Additionally, I'll note that there is an optional ASDOT column available on the ASN lists.)
