### ISSUE TITLE
Loading Script Issue

### ISSUE THREAD

**Issue by SirHardware** [netbox-community/netbox#13496]
### NetBox version

v3.5.8

### Python version

3.10

### Steps to Reproduce

1. Containerized Netbox Installation
2. Add Git Datasource
3. Add Script from Git Datasource (with Autosync enabled)
4. Make Changes to Script via Git
5. Sync Datasource
6. Script can't be loaded
![image](https://github.com/netbox-community/netbox/assets/58984793/c268bcb7-3694-4d72-8be6-83813fcbb78b)
7. If error doesn't occur repeat steps 4 and 5 until it does

### Expected Behavior

The Script in Netbox gets updated

### Observed Behavior

The Scipt can't be loaded und thus not executed

In the Filesystem the Script is correct with the updated content

**Comment by jeremystretch** [comment]
> 1. Containerized Netbox Installation

This repo accepts issues only for the core NetBox application. If you're experiencing an issue using a containerized deployment, please consider submitting a bug to that repo.
