### ISSUE TITLE
copying logs to new NetBox version

### ISSUE THREAD

**Issue by kh4y4m** [netbox-community/netbox#13493]
### Change Type

Addition

### Area

Installation/upgrade

### Proposed Changes

Hey,
please add the step, in which you need to copy the logs directory and it's file to the new NetBox directory, otherwise your running into an error.

**Comment by kkthxbye-code** [comment]
As far as I can tell, there's no instructions regarding setting up logging in the install guide, so there should be no "logs directory" for the user to move. It would also be uncommon to store logs in the netbox install folder in the first place. Can you elaborate on why you think it makes sense to include what you requested?
