### ISSUE TITLE
vlan groups - vlan group single object view - edit selected / delete selected buttons missing from vlan list on view

### ISSUE THREAD

**Issue by ITJamie** [netbox-community/netbox#13494]
### NetBox version

v3.5.8

### Python version

3.8

### Steps to Reproduce

1. create a vlan group and assign multiple vlans to it.
2. goto the vlan group ( eg https://demo.netbox.dev/ipam/vlan-groups/2/ )
3. select multiple vlans
4. scroll to the bottom, there is no "edit selected" / "delete selected" buttons 

### Expected Behavior

since there are selection boxes on the list I would expect to be able to edit / delete the vlans in bulk

### Observed Behavior

there is no bulk edit/delete buttons even though there are selection buttons on the list

**Comment by jeremystretch** [comment]
This has been addressed by #13536 (thanks @abhi1693!)
