### ISSUE TITLE
prefix view - add ip address range button

### ISSUE THREAD

**Issue by ITJamie** [netbox-community/netbox#13515]
### NetBox version

v3.5.8

### Feature type

Change to existing functionality

### Proposed functionality

when on prefix view - ip address tab (eg https://demo.netbox.dev/ipam/prefixes/1/ip-addresses/) add a button to add IP range

### Use case

it would be great to be able to add an IP address range quickly from the prefix view, it should autofill the vrf etc based on the prefix details and have the first and last IP already filled out from that prefix

**Comment by jeremystretch** [comment]
There's a button to add an IP range under the child IP ranges view, just like the "add an IP" button under the child IPs view.
