### ISSUE TITLE
PR #13387 broke the documented get_plugin_config method as it is documented

### ISSUE THREAD

**Issue by kkthxbye-code** [netbox-community/netbox#13516]
### Change Type

Correction

### Area

Plugins

### Proposed Changes

Not sure if this should be a bug report or a documentation change, as I'm not sure what the intention was. PR #13387 moved get_plugin_config from `extras.plugins` to `extras.plugins.util`. This seems like an undocumented backwards incompatible change to the plugin API. It broke netbox-napalm for instance:

https://github.com/netbox-community/netbox-napalm/issues/16

The change should either be rolled back or the documentation should be changed here:

https://github.com/netbox-community/netbox/blob/4004966b16269c96c09540c011a5aea2267bc226/docs/plugins/development/index.md?plain=1#L119-L126

If the change is to stay, we should edit the release notes on github for 3.5.8 indicating that there's a BC break.

**Comment by jeremystretch** [comment]
> This seems like an undocumented backwards incompatible change to the plugin API.

This was not intentional; it was an oversight on my part. We can fix it by importing the utility functions in `extras.plugins`.
