### ISSUE TITLE
Prefix filter on Site level due to the double prefix use

### ISSUE THREAD

**Issue by mikehak74** [netbox-community/netbox#13529]
### NetBox version

v3.5.8

### Feature type

Change to existing functionality

### Proposed functionality

There would be great to have to assign the IP Address to a site and later you can check the Prefix on Site level.  So double used IP can be filtered on the Prefix in the ipam and you can also see which ip address is free on which Site 

### Use case

The problem is, we have a network with different sites and some sites have the same prefix as the other site. On prefix you can add the site, if you now add an ip address which is in the IP address of the Prefix which is available in more than one site you will see it on all site. And in this case you can't use the IPAM functionality to see if an ip is used on a specific Site.

**Comment by jeremystretch** [comment]
> The problem is, we have a network with different sites and some sites have the same prefix as the other site.

You can use VRFs and/or tenant assignments to manage overlapping space. It would not make sense to assign individual IP addresses to sites as that is already implied by the assignment of the containing prefixes.
