### ISSUE TITLE
IP prefix, when nest a /30 into a /29 the subnetID and Broadcast ID are available for IP assignment in the /29 prefix

### ISSUE THREAD

**Issue by Taz86** [netbox-community/netbox#13523]
### NetBox version

V3.5.8

### Python version

3.11

### Steps to Reproduce

Example:
Go to IPAM and create some prefixes

- Create /29 prefix 10.0.0.0/29
- Create 2x /30 prefix 10.0.0.0/30 and 10.0.0.4/30 (no pool)
- Assign 2 available IP adresses in both /30 prefixes

### Expected Behavior

Expect:
/29 is full, no available IP adresses

### Observed Behavior

Result:
10.0.0.3 and 10.10.0.4 are available for assignment

**Comment by jeremystretch** [comment]
This is expected behavior: The "IP addresses" tab under the parent prefix is showing what IPs are available within the context of _that_ prefix, regardless of its child assignments. There are many scenarios where this is useful and necessary.
