### ISSUE TITLE
Search results page column customisation

### ISSUE THREAD

**Issue by andyb2000** [netbox-community/netbox#13524]
### NetBox version

v3.4.6

### Feature type

New functionality

### Proposed functionality

On the search results page (/search/?q=test) it would be useful to be able to specify the columns shown to the user, preferable by a configuration.py configurable option to give further information on the results.
The principle is when returning data it can be confusing to know which element to click on when multiple devices share similar descriptions (value column).

### Use case

Take for example when searching for a specific description that appears on multiple switches, you'd receive a list similar to:

<html>
<body>

Type | Object | Field | Value
-- | -- | -- | --
Interface | GigabitEthernet1/0/4 (gi1/0/4) | Description | Customer: MyClientInterface - customer data
Interface | GigabitEthernet1/0/4 (gi1/0/4) | Description | Customer: MyClientInterface - customer data

</body>
</html>

In the above the two interfaces are on separate devices and you cannot see that on the results display, so adding a column of the device (or being able to customise) would be useful.

**Comment by jeremystretch** [comment]
What you're describing is not feasible for the global search, which can return many different types of objects. For example, what if your results include two interfaces, a rack, three VLANs, and a tenant?

**Comment by andyb2000** [comment]
Yes, I was aware that it's a multi-function results page, but having an optional column (even if blank) for specific fields would help end-users out hugely when results are returned, at the moment the search pages cause confusion.

**Comment by jeremystretch** [comment]
Following this strategy would quickly result in dozens of (mostly empty) columns across as many different models. The global search results would turn into a giant unreadable mess. Imagine having to side scroll through a dozen empty columns just to find something relevant to a specific result.

**Comment by jeremystretch** [comment]
I'm going to close this out as the proposed implementation does not seem feasible.
