### ISSUE TITLE
Time zones should be user-settable

### ISSUE THREAD

**Issue by pv2b** [netbox-community/netbox#13533]
### NetBox version

v3.5.8

### Feature type

New functionality

### Proposed functionality

The proposed functionality is a user-specific setting to set their preferred time zone for displaying the NetBox web UI.

### Use case

In order to support teams that work in multiple timezones, it would be helpful if time zone display could be localized to a specific user.

It would also be useful for teams where some team members prefer having times displayed in UTC, and others prefer having them displayed in local time.

### Database changes

There would need to be a field added to wherever the user preferences live, to allow for a timezone field.

### External dependencies

No new dependencies should be needed. It appears that NetBox currently just passes TIME_ZONE down to Django anyway, and Django already provides functionality for user-specific timezones that could be leveraged by NetBox.

https://docs.djangoproject.com/en/4.2/topics/i18n/timezones/

**Comment by pv2b** [comment]
As an side, it probably is a good way to have a way for the administrator to enable/disable this feature. Some organizations, for example, might have a mandate to always display times in a certain way (in UTC for example). A global toggle to enable/disable the feature might be a good idea.

**Comment by ITJamie** [comment]
Ui changes would likely be needed to allow for setting a timezone on datetime fields (or at least notifying the user that their timezone is different from "default" timezone set in netbox and to account for any difference).

**Comment by pv2b** [comment]
> Ui changes would likely be needed to allow for setting a timezone on datetime fields (or at least notifying the user that their timezone is different from "default" timezone set in netbox and to account for any difference).

That's probably a good idea, even seperate from timezones being implemented. The UI isn't always very clear in telling the user what timezone is set in Netbox, often the only way to see is to scroll down to the bottom of the page and look at the tiny text down there.

**Comment by abhi1693** [comment]
> The UI isn't always very clear in telling the user what timezone is set in Netbox

This is on every page at the bottom right side

![image](https://github.com/netbox-community/netbox/assets/5083532/54d0650a-c7e7-4e7e-844c-7078a3269c0b)

**Comment by pv2b** [comment]
> > The UI isn't always very clear in telling the user what timezone is set in Netbox
> 
> This is on every page at the bottom right side
> 
> ![image](https://user-images.githubusercontent.com/5083532/262760798-54d0650a-c7e7-4e7e-844c-7078a3269c0b.png)

Thank you for proving my point. Users often won't notice stuff at the very end, or at the bottom of the page, or fine print.

For example, in the post you just quoted, right after the piece you cut off (and I assume didn't notice because it was there at the very end), I wrote:

> often the only way to see is to scroll down to the bottom of the page and look at the tiny text down there.

Which is essentially exactly what you just said.
