### ISSUE TITLE
Clarify TIME_ZONE documentation - why is UTC recommended?

### ISSUE THREAD

**Issue by pv2b** [netbox-community/netbox#13532]
### Change Type

Removal

### Area

Configuration

### Proposed Changes

The [current documentation](https://demo.netbox.dev/static/docs/configuration/optional-settings/#time_zone) for the `TIME_ZONE` configuration parameter reads:

> TIME_ZONE
> 
> Default: UTC
> 
> The time zone NetBox will use when dealing with dates and times. It is recommended to use UTC time unless you have a specific need to use a local time zone. Please see the [list of available time zones](https://en.wikipedia.org/wiki/List_of_tz_database_time_zones).

Let's go focus on this sentence:

> It is recommended to use UTC time unless you have a specific need to use a local time zone.

This is far too vague. As a reader, I'm not sure why this recommendation exists, or why it's a good idea. Reading between the lines, I'm left wondering, is it maybe "recommended" to use UTC because there are some unspecified or unknown bugs that might happen, or some weird side effects? (Also see #13531, it's not clear what "dealing with" means in this context.)

My *guess* as to what's going on here is that Netbox is trying to encourage administrators towards a best practice of using UTC for display time. It's certainly a legitimate opinion that using UTC for display everywhere makes communication between team members easier, and provides a common frame of reference unaffected by Daylight Savings Time, especially spanning multiple time zones.

Another reason why UTC might be a good idea for Netbox specifically, is that Netbox currently doesn't allow user-specific time display options, so if you have a timezone-distributed organization, setting a specific timezone for everyone's a pretty bad idea. 

In my opinion, the Netbox documentation isn't really the place to be making best-practices recommendations for how organizations should approach internally communicating times and dates, so in my opinion, this sentence should be removed from the documentation, so that users aren't discouraged from making the choice that's right for their org by a vague "don't do that".

The other option is to write up a paragraph explaining *why* UTC is recommended, or linking to some outside article on that subject. Or even just mention that if you have team members in different timezones that, because Netbox can't do user-specific timezones currently, keeping it to UTC will be your best option to keep things neutral.

In my case, my org is completely based in one time zone, and we don't use UTC under normal circumstances, so setting display time to local time makes the most sense for us in our current culture. (And changing it shouldn't be within the scope of adopting Netbox, specifically.)

**Comment by jeremystretch** [comment]
The consistent use of UTC is considered best practice in the industry. An explanation behind it is out of scope for the NetBox documentation. If you have a reason to use a different time zone, use that.

**Comment by pv2b** [comment]
> The consistent use of UTC is considered best practice in the industry. An explanation behind it is out of scope for the NetBox documentation. If you have a reason to use a different time zone, use that.

I agree, and to clarify, that is why my primary suggestion was to compeltely remove the recommendation to use UTC. As written right now, it's possible to misunderstand the documentation as a warning that some Netbox functionality might be negatively impacted by changing the session. Best to remove the sentence altogether.
