### ISSUE TITLE
Support LAG interfaces in Device type definition

### ISSUE THREAD

**Issue by oneone84** [netbox-community/netbox#13541]
### NetBox version

v.3.6 beta2

### Feature type

Data model extension

### Proposed functionality

When defining a device type I want to be able to set a parent LAG interface in the interface template. As of now, It seems like I can only connect them to a bridge interface.
![bild](https://github.com/netbox-community/netbox/assets/44062096/d3647a64-88de-4d60-a183-810fd28c744d)

Also, when cloning a device I would like the clone to retain child interface to LAG relationship on the cloned device (to the new interface of course).

### Use case

We always connect our servers using one or more LAG interfaces with 2 physical child interfaces and as of now we have to click alot to relate the physical interfaces to the LAG interface.

I would wish to create this from template, or as a workaround at least be able to clone a server with this already setup.

### Database changes

don't think so.

### External dependencies

don't think so.

**Comment by jeremystretch** [comment]
The device type is a hardware definition, and has only attributes which are consistent among all its instances. A LAG is a software configuration that varies among instances, so it would not be appropriate to add to the interface template model.

You might consider using custom scripts to automate the creation of LAG interfaces and other configuration items when instantiating devices.
