### ISSUE TITLE
LAG-type interfaces missing from interface bulk edit view

### ISSUE THREAD

**Issue by AesoSpadez** [netbox-community/netbox#13569]
### NetBox version

v3.5.8

### Python version

3.9

### Steps to Reproduce

1. Create a device with multiple physical interfaces
2. Create a LAG-type interface on the device
3. From the interfaces tab on the device, select multiple physical interfaces. Then click 'Edit Selected'

### Expected Behavior

The newly-created LAG-type interface should be selectable for LAG under the Related Interfaces section.

### Observed Behavior

The LAG field is greyed out.

**Comment by jeremystretch** [comment]
Looks like the `device` parameter was inadvertently dropped from the form action URL as part of a recent template refactoring.
