### ISSUE TITLE
Add unit to power port overview on device view

### ISSUE THREAD

**Issue by rodvand** [netbox-community/netbox#13587]
### NetBox version

v3.5.8

### Feature type

New functionality

### Proposed functionality

On the power ports view within a device, add the unit to the Maximum draw and Allocated draw. 
From this:
<img width="526" alt="Screenshot 2023-08-28 at 21 14 29" src="https://github.com/netbox-community/netbox/assets/56864/d2a60eab-0466-4b30-b915-29af3e2596f7">

To this
<img width="526" alt="Screenshot 2023-08-28 at 21 14 29" src="https://github.com/netbox-community/netbox/assets/56864/fb5f081f-a406-4a7a-85cd-18241ba77fd0">

### Use case

Just makes it more apparent for users that the unit of power is W.

**Comment by jeremystretch** [comment]
Does it make sense to replicate the unit for each value in the column? It's always going to be the same; maybe annotating it in the column header would be more efficient. Typically we want to avoid attaching units to numeric data, especially when being exported e.g. as CSV.

**Comment by jeremystretch** [comment]
Another option would be to render the unit in the UI, but omit it for CSV export. This would keep the exported data "cleaner" by retaining the native integer format.
