### ISSUE TITLE
Enable filtering for null numeric values using the `empty` lookup

### ISSUE THREAD

**Issue by jeremystretch** [netbox-community/netbox#13585]
### NetBox version

v3.5.8

### Feature type

New functionality

### Proposed functionality

NetBox currently supports checking for empty string fields using the `empty` lookup (e.g. `?description__empty=true`). This FR proposes extending that functionality to numeric fields as well, to match null/non-null values.

### Use case

This enables a user to query numeric fields generally for null or non-null values. For example, `?position__empty=true` would return devices which do not have a rack position defined.

**Comment by stavr666** [comment]
Greatly appreciate this FR and instant implementation 👍🏿
