### ISSUE TITLE
Device selector missing when trying to assign an IP address

### ISSUE THREAD

**Issue by telmich** [netbox-community/netbox#13594]
### NetBox version

v3.5.8

### Python version

3.8

### Steps to Reproduce

1. Create an IP address
2. Try to assign it to a device

The only drop down seen is the interface list, but for a few versions the device drop down is missing.

The problem is happening on create and edit.

![2023-08-29-065245_767x227_scrot](https://github.com/netbox-community/netbox/assets/9397/7e61666e-cfa2-42a3-8191-039e7badceec)

### Expected Behavior

A device can be selected

### Observed Behavior

I am using the docker image and the database is a few years old and I have upgraded using docker images

**Comment by kkthxbye-code** [comment]
Use the object selector by clicking the button to the right of the drop-down.
