### ISSUE TITLE
User to access only specific site/region related data

### ISSUE THREAD

**Issue by trs91km** [netbox-community/netbox#13597]
### NetBox version

v3.5.4

### Feature type

New functionality

### Proposed functionality

Our netbox is accessed by many team in different region, I want to restrict users from US region only to access data for US alone

### Use case

This will help us to restrict users to access/modify data only belongs to them

**Comment by abhi1693** [comment]
Thank you for your interest in extending NetBox. Unfortunately, the information you have provided does not constitute an actionable feature request. Per our [contributing guide](https://github.com/netbox-community/netbox/blob/develop/CONTRIBUTING.md), a feature request must include a thorough description of the proposed functionality, including any database changes, new views or API endpoints, and so on. It must also include a detailed use case justifying its implementation. If you would like to elaborate on your proposal, please modify your post above. If sufficient detail is not added, this issue will be closed.

**Comment by Mailstorm-ctrl** [comment]
I'm not sure if it's available in your version, but you can already do this permission constraints
https://demo.netbox.dev/static/docs/administration/permissions/

**Comment by trs91km** [comment]
@Mailstorm-ctrl excellent, this is exactly what I need, thanks

@abhi1693 I will close this, thanks much
