### ISSUE TITLE
Cannot read VLANS by tenant in newer version of Netbox

### ISSUE THREAD

**Issue by MichaelPHolstein** [netbox-community/netbox#13604]
### NetBox version

V.3.2.4

### Python version

3.11

### Steps to Reproduce

We have 2 types of netbox servers. The acceptation version is currently running on V3.0.7 and our production version is running on V3.2.4

The following endpoint returns a different response for both versions.

`/api/ipam/vlans/?tenant=DB0001`

**Version 3.0.7:**
Within this version it returns the desired response:

**Version 3.2.4**
Within this version the same endpoint returns:
```
{
    "tenant": [
        "Select a valid choice. DB0001 is not one of the available choices."
    ]
}
```

How can I list all VLANS by providing the tenant name.

### Expected Behavior

I expect a list of VLAN's that are linked to the debtor that has the name we provide just like V3.0.7

### Observed Behavior

It returns the error message like described above:
```
{
    "tenant": [
        "Select a valid choice. DB0001 is not one of the available choices."
    ]
}
```

**Comment by aopdal** [comment]
Just checked using my 3.3.2 and 3.5.9 and filter VLAN using tenant slug is working. I don't have any 3.0.7 to check if it was the tenant name there.

**Comment by jeremystretch** [comment]
> The acceptation version is currently running on V3.0.7 and our production version is running on V3.2.4

Both versions of NetBox you're using to test are very outdated. Please update to the latest stable release (currently v3.5.9) as you will likely find that the problem has already been addressed.
