### ISSUE TITLE
Customisable Sites Pages

### ISSUE THREAD

**Issue by ataylor93** [netbox-community/netbox#13603]
### NetBox version

v3.5.2

### Feature type

New functionality

### Proposed functionality

1. Similar to the new customisable dashboards feature, add the ability to customise site pages to allow widgets to pull information on related objects, e.g circuits associated to the site page you are on, Currently we dig into the "Related Objects" widget to take us to the information we are looking for.

2. In addition to above allow any customisations to be applied globally to users on netbox rather than on an individual user basis.

### Use case

I've had a number of users on our netbox instance request the ability to present key information without so many clicks to present information they are looking for.

**Comment by jeremystretch** [comment]
Unfortunately dynamic or personalized UI layouts is not something that's feasible for us to implement in the core application. Instead, you can create a [custom plugin](https://docs.netbox.dev/en/stable/plugins/development/) to provide the specific views you need.
