### ISSUE TITLE
rack "side" view + actual device depth

### ISSUE THREAD

**Issue by ITJamie** [netbox-community/netbox#13624]
### NetBox version

v3.5.9

### Feature type

Change to existing functionality

### Proposed functionality

a new field would exist on devicetype models which knew the actual depth of a device, this could be used to calculate if a device can fit into a rack & if it would be full or partial depth in that rack. 

along with the front/rear elevation view of a rack a "side" view would be useful. this would be especially useful on two post racks which can sometimes need to be balanced (not have all heavy devices hanging to one side). 

### Use case

- quicker ability to visualize a rack
- potentially flag where devices are too long to fit into a rack (device depth vs rack dimensions)
- we could potentially drop the current depth boolean in the future and instead calculate full depth vs half depth based on rack depth and device type dimensions. 

### Database changes

add a new device_depth (int) field to device type model 

### External dependencies

n/a

**Comment by ITJamie** [comment]
related: #13555

**Comment by thefreakquency** [comment]
Duplicate of https://github.com/netbox-community/netbox/issues/1627
