### ISSUE TITLE
Problem on new and old users after migrating Netbox to v3.6.0

### ISSUE THREAD

**Issue by agusadjadj** [netbox-community/netbox#13658]
### NetBox version

v3.6.0

### Python version

3.11

### Steps to Reproduce

On old users (Migrated):
1. Go to Users
2. Click on username
3. Error raise

On new user:
1. Add a new user with common data
2. After click create, error raise

### Expected Behavior

On click user, have to see the user parameters. If i check the user, and click edit user, have the permission to see the user, but in a window before for "Bulk" and not the edit page instead.

### Observed Behavior

A Server Error Raised
![Captura desde 2023-09-01 12-09-49](https://github.com/netbox-community/netbox/assets/32807381/8708d02d-c699-403e-a736-08142ea53252)

**Comment by jeremystretch** [comment]
Thank you for opening a bug report. I was unable to reproduce the reported behavior on NetBox v3.6.0. Please re-confirm the reported behavior on the current stable release and adjust your post above as necessary. Remember to provide detailed steps that someone else can follow using a clean installation of NetBox to reproduce the issue. Remember to include the steps taken to create any initial objects or other data.

You might also consider disabling your installed plugins as one of them may be the culprit.

**Comment by agusadjadj** [comment]
Update: With the current build (v3.6.1) seems the error dissapears, without plugins and with them.

It seems that report #13622 had some inference (it's my theory).
I close the report, thank you!
