### ISSUE TITLE
Add the ability to use prefix on Redis

### ISSUE THREAD

**Issue by ArpStorm1** [netbox-community/netbox#13663]
### NetBox version

v3.5.8

### Feature type

New functionality

### Proposed functionality

Hello netbox community!

We are running a Redis on production, and in order to distinguish applications we made sure each of our applications would use prefix, so we can identify them.

Adding prefix is also supported on django using the KEY_PREFIX keyword.

However, when I tried to add this to the configuration,py, I noticed the netbox ignored completly from this configuration.

### Use case

Using prefix can help to distingusih applications in the same database, so netbox user can ask for one database from redis

**Comment by jeremystretch** [comment]
Best practice is to run separate Redis instances for each application, for many reasons. Prefixes are not meant to be used for this purpose.
