### ISSUE TITLE
Bulk deletion of Prefix objects will only delete the first selected

### ISSUE THREAD

**Issue by endreszabo** [netbox-community/netbox#13672]
### NetBox version

v3.5.8

### Python version

3.11

### Steps to Reproduce

- Select multiple Prefixes in the Web UI.
- Click on delete button below the table.
- Landing page only shows 1 (one) prefix selected for deletion.
- DevTools confirms that multiple Prefix model `pk` values have been POSTed individually, overwriting each other.

### Expected Behavior

Prefixes-to-be-deleted `pk`s should have been POSTed as a list.

### Observed Behavior

Only one Prefix (the first one in the submitted form) is to be removed.

**Comment by endreszabo** [comment]
Closing for now as even I can't reproduce it once I deleted the prefixes via the API.

**Comment by kkthxbye-code** [comment]
> DevTools confirms that multiple Prefix model pk values have been POSTed individually, overwriting each other.

Just for reference, that's not how it works. It's pretty standard to parse repeated keys as a list, so django converts `test=123&test=321` to something like `{'test': ['123', '321']}`.
