### ISSUE TITLE
import doesn't work even on export 

### ISSUE THREAD

**Issue by ArdeSeadis** [netbox-community/netbox#13678]
### NetBox version

v3.5.8

### Python version

3.8

### Steps to Reproduce

Hello, 
If a create an export in csv of VLAN
and If I import again it doesnt' work

And even If I remove all devices from my export on netbox
Import doesn't work

I don't know If it's lowercase or other thinks but I don't understand why after an export on netbox, 
and If we import again, there is errors

Thanks

### Expected Behavior

export import working 

### Observed Behavior

Record 1 vid: This field is required.

 Record 1 name: This field is required.

 Record 1 status: This field is required.

**Comment by jeremystretch** [comment]
This is not a bug, and has already been discussed many times. The supported fields are detailed below the import form.
