### ISSUE TITLE
Server Error accessing specific Report via API

### ISSUE THREAD

**Issue by Haeki** [netbox-community/netbox#13674]
### NetBox version

v3.6.0

### Python version

3.11

### Steps to Reproduce

1. Go to /api/extras/reports/
2. Got to any of the URLs returned in the "url" fields
3. Server Error:
![image](https://github.com/netbox-community/netbox/assets/6272118/4e166494-2695-4f5f-ae2a-c92859b1d97e)

### Expected Behavior

The API should return the Details of the specific report.
Working example in NetBox v3.4.4:
![image](https://github.com/netbox-community/netbox/assets/6272118/d850c3c5-5d17-4c8d-9599-909040aa070a)

### Observed Behavior

Accessing  `/api/extras/reports/datacenter_sites.ErrorCheckSummary/` in NetBox v3.6.0 does not return an answer like in v3.4 but instead creates a Server Error.

**Comment by kkthxbye-code** [comment]
Thanks for the report, I managed to replicate it fine by uploading the [example report from the docs](https://docs.netbox.dev/en/stable/customization/reports/#writing-reports).

Seems to have been broken for a while, it was still broken on 3.5.0 at least.
