### ISSUE TITLE
Custom Scripts are not visible for LDAP and Local users

### ISSUE THREAD

**Issue by Arshnika** [netbox-community/netbox#13675]
### NetBox version

v3.6.0

### Python version

3.10

### Steps to Reproduce

1. A superuser admin logs in to NetBox and add custom scrips under the Customization > REPORTS & SCRIPTS > Scripts:

![image](https://github.com/netbox-community/netbox/assets/95662911/7a004b4a-bd62-4caf-976f-1141d5eabc1f)

![image](https://github.com/netbox-community/netbox/assets/95662911/d72e98bb-d658-480c-9a0b-81933aaac145)

3. End users login to NetBox using their local or LDAP user. Please note users do not have superuser privilege. However, they do have run and view permissions for "Scripts" and "Script Module" object types.
4. They go to Customization > REPORTS & SCRIPTS > Scripts.

### Expected Behavior

Local and LDAP users must be able to see all scripts.

### Observed Behavior

Scripts are not visible. Instead, users face the message "No Scripts Found". However, superusers are able to see the scrips.

![image](https://github.com/netbox-community/netbox/assets/95662911/40836aec-b88c-45c7-bc6c-973f5783c7a1)

**Comment by Arshnika** [comment]
Here is the screenshot of the issue:

![image](https://github.com/netbox-community/netbox/assets/95662911/08b5b7ca-50bb-4d30-a5df-eb9bde337af0)

**Comment by jeremystretch** [comment]
Thank you for opening a bug report. Unfortunately, the information you have provided is not sufficient for someone else to attempt to reproduce the reported behavior. Remember, each bug report must include detailed steps that someone else can follow on a clean, empty NetBox installation to reproduce the exact problem you're experiencing. These instructions should include the creation of any involved objects, any configuration changes, and complete accounting of the actions being taken. Also be sure that your report does not reference data on the public NetBox demo, as that is subject to change at any time by an outside party and cannot be relied upon for bug reports.

**Comment by Arshnika** [comment]
Hi Jeremy,

I have updated the information with more details and screenshots.

Thanks.

**Comment by Arshnika** [comment]
Just to give an update that the issue has been resolved.

With this NetBox release, users must also have permission for "**Core > Managed File**" object. After adding the permission, users are now able to see all scripts.

![image](https://github.com/netbox-community/netbox/assets/95662911/442ae422-5340-4ba5-a958-72bf903a1981)

![image](https://github.com/netbox-community/netbox/assets/95662911/ac394379-2e98-4fc2-ad5e-c08e8dbd2edd)

**Comment by Arshnika** [comment]
The issue has been resolved.
