### ISSUE TITLE
TypeError when resolving custom field choice set with a not "required" multiselect

### ISSUE THREAD

**Issue by DanSheps** [netbox-community/netbox#13681]
### NetBox version

v3.6.0

### Python version

3.9

### Steps to Reproduce

1. Have a multi selection custom field from a previous version of NetBox that is not "required" and the default value being "Network Staff" (not "null")
   a) Name: Allowed Access
   b) Choice Set: "Network Staff", "Server Staff"
   c) Connected to Device Type
2. Upgrade to 3.6
3. Add a Device Type

Note: Reproducable from scratch as well after some other issues have been resolved with custom fields

### Expected Behavior

The add Device Type form should appear

### Observed Behavior

TypeError: 'in <string>' requires string as left operand, not NoneType

**Comment by jeremystretch** [comment]
I'm not able to reproduce this following these steps:

1. Install NetBox v3.5.9
2. Create a custom field with the following attributes:
  - Content types: Device type
  - Name: `allowed_access`
  - Type: Multi-select
  - Required: False
  - Default value: `["Network Staff"]`
  - Choices: `Network Staff,Server Staff`
3. Upgrade to NetBox v3.6.0
4. Create a new device type

The new device type is created successfully, with its `allowed_access` custom field set to "Network Staff."

**Comment by DanSheps** [comment]
Yes, diving into it a little more it may have been partially a pre-2.10 issue that got carried over.  At that time, the default was stored as a varying char and the default value was `"Network Staff"` and not `["Network Staff"]`. It looks like at the time, SELECT/MULTISELECT wasn't taken into account and the default was carried over as a string.

It seems to be a very specific set of circumstances and it took most of the day to get to this:

* Start with v2.9.11
* Create a custom field:
  * Object: dcim > device type
  * Name: department
  * Choices: network, server, admin, business
  * Default: network (string, not a string in an array)
* Upgrade to 2.11.12
* Upgrade to 3.0.0
* Upgrade to 3.5.9
* Upgrade to 3.6.0
* Try to create a device type

You will notice, if you go edit the custom field, that the custom field is a string and not an array with a string for the choice.  This is a legacy of 2.9.x (Pre 2.10.x).  The 2.10.x converts everything to a jsonb but doesn't take into account selection objects and just preserves the default as a string.

**Comment by DanSheps** [comment]
Converted the PR to a draft and we can discuss whehther this is an important item to even take into account.

It looks like it was a combination of:

1. Bad data that persisted from 2.9.11 to 2.11.12 up to 3.5.9 and then finally 3.6.0.  It was never found because the check in validate() for the default ignores data that is blank.  You can save "" right now in 3.6.0 so the change in 2.11.12 would have not been caught.
2. Data was never updated to trigger a validation check.

I am okay with skipping on this, but I do think we should:

1. Proceed with this fix (in the PR) or insert a migration to properly migrate string defaults in custom fields that are part of a multi-select to an array
2. Add a check for a this condition (blank default on a multi-select)

**Comment by DanSheps** [comment]
I came across this again in a slightly different manner.  I think I have a way to reproduce this consistently.

**Comment by jeremystretch** [comment]
@DanSheps have you made any progress on this?

**Comment by DanSheps** [comment]
Looking into this, I think this all has to do with old (not nessicarily bad) data from previous upgrades over the years.

I cannot reproduce this on a clean instance because of the way the UI has changed and you can no longer do things (such as change a select to a mutliselect) in the UI that was possible previously.

I would say it is best to close this out for now and if I run into it again I will try and get some more information when it happened.  I stupidly did not save the traceback and it wasn't captured in sentry.
