### ISSUE TITLE
Cannot add a new custom field of type selection/multiple selection list

### ISSUE THREAD

**Issue by DanSheps** [netbox-community/netbox#13682]
### NetBox version

v3.6.0

### Python version

3.9

### Steps to Reproduce

1. Add a choice field set named Test with the following choices:
    ````
    test,Test
    tester,Tester
    testing,Testing
    ````
3. Add a custom field
    a. Name: Test
    b: Object: Circuits
    c: Type: Multiple Selection (Selection also has an issue)
    d: Required: True
    e: Default: "test"
    f: Choice Set: Test
4. Save

### Expected Behavior

Custom Field Saves

### Observed Behavior

`AttributeError: 'CustomField' object has no attribute 'message'`

Nested Exception: 
`ValidationError: Invalid choice(s) (t, e, s, t). Available choices are: `

Alternatively, if default is set to "", the nested exception is:

`ValidationError: 'Required field cannot be empty.'`

**Comment by DanSheps** [comment]
Turns out, the list was added wrong on my end.

That said, there is an issue with the validation still of a default field.  `self.default and self.default not in self.choices:` won't work

We could actually remove line 321 to 326 as that validation logic is also part of the default check at the top.

**Comment by wypxl** [comment]
Hi, i dont know how to add a choice field,I can't find the button on the netbox,can you tell me how to define a choice filed?

**Comment by DanSheps** [comment]
You should [Read the Docs](https://docs.netbox.dev/en/stable/customization/custom-fields/#custom-selection-fields)
