### ISSUE TITLE
search filter to bookmark

### ISSUE THREAD

**Issue by tosolini** [netbox-community/netbox#13694]
### NetBox version

V3.6.0

### Feature type

Change to existing functionality

### Proposed functionality

Can be useful bookmark the saved search. I suppose the saved search filter can be useful and used many times. In my case i put some device without rack position, because i know they exist but not where they are. So, i put a "non-rackable" filter as reminder list for "treasury hunt".

### Use case

Fast access to a saved filter. Now the only way to access, is going to filters tab, request from the dropdown list previous saved filter, scroll down below and press search. A bookmark for this, can save lot of time and lot of clicks.

### External dependencies

nothing

**Comment by DCAuto** [comment]
I would like to second this request. Being able to quickly view a subset of devices or interfaces is something that my organization would benefit from .
