### ISSUE TITLE
Allow different equipment to be installed front and rear on the same rack position level

### ISSUE THREAD

**Issue by smarteyesi** [netbox-community/netbox#13698]
### NetBox version

v3.6.0

### Feature type

Change to existing functionality

### Proposed functionality

Allow different devices to be installed in front and rear.

With short-depth devices, it is possible to put a patch panel in the rear while putting another device in the front.

### Use case

With short-depth devices, it is possible to put a patch panel in the rear while putting another device in the front.

Example:
42U-front: 48x port switch
42U-rear: 8x ports power distribution unit (PDU)

both are having the same rack position namelijk 42, but its a different device in the front and the rear

### Database changes

the tool pathfinder resolves this problem by allowing different levels (up to 4) for front and rear so you can place/view another device depending on the level.

### External dependencies

no external dependencies are required

**Comment by pv2b** [comment]
Hello!

If I've understood your request correctly, this is already possible today with NetBox. When you're creating a device type, if you specify that it's "Full Depth", then it will occupy both front and rear faces of the rack when installed.

However, if you create a device that's not marked as "Full Depth", then it'll only occupy one face.

If you're looking for something more than that, please clarify.
