### ISSUE TITLE
Enable Inventory Item column in Device's Interface tab

### ISSUE THREAD

**Issue by jayGG83** [netbox-community/netbox#13723]
### NetBox version

v3.5.4

### Feature type

Change to existing functionality

### Proposed functionality

The inventory Items tab inside the device allows to show the interface to which it is linked (column Component)
The proposed functionality is to also enable as a column option the other way around; showing the inventory item linked to the interface

### Use case

Currently in our case, we use a custom field to show the item linked to the interface. Allowing this column would allow a more synchronized data and to be shown in a quick glance.
![image](https://github.com/netbox-community/netbox/assets/132988868/63d84347-2e29-4dac-860c-ee1a1c034421)

### Database changes

None

### External dependencies

None

**Comment by bitcollector1** [comment]
I like this request, I've also made a similar request 

Cable Trace: Add Inventory Component Table if applicable
https://github.com/netbox-community/netbox/issues/12658
