### ISSUE TITLE
Data source username and password are visible in the changelog

### ISSUE THREAD

**Issue by mtbutler07** [netbox-community/netbox#13729]
### NetBox version

v3.6.1

### Feature type

Change to existing functionality

### Proposed functionality

When creating a new data source (git) in NetBox with username/password fields populated, a changelog entry is created that contains the diff of the username/password in plain text. 

![Screenshot from 2023-09-08 13-30-35](https://github.com/netbox-community/netbox/assets/33135168/2bcf9596-a25b-439c-ae59-691ccda7a633)

This is not ideal for a number of reasons, the primary one being that it exposes credentials to other users that can view the NetBox changelog.

I'm proposing that the the username and password fields be masked or excluded entirely from the changelog entry to prevent exposing credentials.

### Use case

It would prevent exposing credentials to other users that are able to view the changelog.

**Comment by mtbutler07** [comment]
For the Amazon S3 type, it appears the `aws_access_key_id` and `aws_secret_access_key` are displayed in plain text as well.

**Comment by jsenecal** [comment]
We probably need a custom method in the serializers for those models to obfuscate specific fields.

**Comment by abhi1693** [comment]
We set `sensitive_parameters` on the `DataBackend` class, maybe there is a way to call this within the `to_objectchange` method

https://github.com/netbox-community/netbox/blob/2dfbd72f10f8bfddbee3c54a275d73c953d0af4b/netbox/core/data_backends.py#L40

**Comment by teixemf** [comment]
IMO this Issue label should be changed from "feature" to "security vulnerability"

**Comment by jeffgdotorg** [comment]
This one and feels important enough to rescue, for the sake of our security posture.

**Comment by abhi1693** [comment]
I'll take a stab at this and see if it's doable

**Comment by abhi1693** [comment]
I cannot find a way to pop out sensitive parameters from both pre and post change data. The most I was able to do was remove from post change using a hack but it caused slight performance degradation. Maybe another maintainer can help fix this.

**Comment by jeremystretch** [comment]
Talked about this a bit with @jeffgdotorg this morning. IIRC we have a mechanism in place already to denote sensitive parameters. I'll take a shot at incorporating this into the serialization logic for data sources.
