### ISSUE TITLE
When creating a new prefix and selecting a site VLANs are not filtered

### ISSUE THREAD

**Issue by patrickfnielsen** [netbox-community/netbox#13721]
### NetBox version

v3.6.1

### Python version

3.11

### Steps to Reproduce
- Create two new sites with the following names, and mark them active: site1 and site2
- On both sites create the following VLANs:
  - VID: 10, Name: Test
  - VID: 20, Name: Test2
- Create a new prefix
  - Any prefix will do
  - Select site1
  - Notice that when selecting VLAN's you can select VLAN's from both sites

### Expected Behavior

Before the new selector widget was added VLANs would be filtered when you selected a site, that is not the case anymore. When you select a site all VLANs are still shown, and you have to use the new selector widget to select the site once again.

### Observed Behavior

VLANs are not filtered, instead all VLANs are shown

**Comment by jeremystretch** [comment]
Thank you for opening a bug report. Unfortunately, the information you have provided is not sufficient for someone else to attempt to reproduce the reported behavior. Remember, each bug report must include detailed steps that someone else can follow on a clean, empty NetBox installation to reproduce the exact problem you're experiencing. These instructions should include the creation of any involved objects, any configuration changes, and complete accounting of the actions being taken. Also be sure that your report does not reference data on the public NetBox demo, as that is subject to change at any time by an outside party and cannot be relied upon for bug reports.

**Comment by patrickfnielsen** [comment]
I have updated the issue.
