### ISSUE TITLE
Error returns on the Render Config tab for VM

### ISSUE THREAD

**Issue by VitMain** [netbox-community/netbox#13727]
### NetBox version

v.3.6.1

### Python version

3.8

### Steps to Reproduce

1. Open Virtualization -> Virtual Machines list
2. Open any existing VM, then click on the Render Config tab and get the error page. 

I tried creating the new VM and got the same result with the error.

Also tried to reproduce on the empty, fresh new database.

1. Drop database
2. Create database
3. Granted permissions for the user
4. Run update.sh
5. logged in to the netbox
6. Created cluster type
7. Created cluster
8. Created VM, with name and cluster, did not fill role.
9. Clicked on the Render Config tab for VM, then got the error page.

In the case of assigning the role to the VM (for the existing or new VMs), the problem is gone. 

### Expected Behavior

Open the tab without any errors.

### Observed Behavior

Server Error

There was a problem with your request. Please contact an administrator.

The complete exception is provided below:

<class 'AttributeError'>

'NoneType' object has no attribute 'config_template'

Python version: 3.8.10
NetBox version: 3.6.1
Plugins: None installed

If further assistance is required, please post to the [NetBox discussion forum](https://github.com/netbox-community/netbox/discussions) on GitHub.

**Comment by DanSheps** [comment]
Marking this as low priority.

Condition to trigger:  Role is null
