### ISSUE TITLE
Range "568" is invalid when creating interface with names vlan [568,570]

### ISSUE THREAD

**Issue by pv2b** [netbox-community/netbox#13722]
### NetBox version

v3.6.1

### Python version

3.11

### Steps to Reproduce

1. Go to an existing device and click on add interfaces.
2. Set the interface name to `vlan [568,570]`
3. Fill in a type (any type is fine)

### Expected Behavior

Two interfaces named `vlan 568` and `vlan 570` are created.

### Observed Behavior

An error message is shown:

Range "568" is invalid

NOTE: The below works but will of course not create the appropriate names:
`vlan [a568,a570]`

I believe the error is in parse_alphanumeric_range in netbox/utilities/forms/utils.py. I think that function is a little overdue for some refactoring, and I'm happy to take it on if accepted.

**Comment by jeremystretch** [comment]
Thanks @pv2b, I've assigned this to you.

**Comment by DanSheps** [comment]
This also shows up with interfaces, FYI.

**Comment by pv2b** [comment]
> This also shows up with interfaces, FYI.

This bug report is about interfaces, yes. I'm not sure what you mean to say with this?

**Comment by DanSheps** [comment]
> > This also shows up with interfaces, FYI.
> 
> This bug report is about interfaces, yes. I'm not sure what you mean to say with this?

Sorry, case of the fridays, was thinking it was with vlans.

**Comment by markh0338** [comment]
I'll just add that we're running into this issue as well and merging in #13730 seems to resolve our problems. It would be nice to see this merged into a release.
