### ISSUE TITLE
SVG Rack Display - Show VC Member Name

### ISSUE THREAD

**Issue by shepherdjay** [netbox-community/netbox#13736]
### NetBox version

v3.6.1

### Feature type

Change to existing functionality

### Proposed functionality

Per #13725 the Rack View shows a virtual chassis name and position instead of the device name. 

Proposal is to remove this section of code that makes that distinction

https://github.com/netbox-community/netbox/blob/a8a36c0a8fa39250792abeb493ed3065bf0d9fdc/netbox/dcim/svg/racks.py#L32-L33

### Use case

Rack diagrams should reflect, as much as possible, the real world labeling that might exist on a device in a rack. Users who wish to use the labeling format of `{device.virtual_chassis.name}:{device.vc_position}` are able to name the devices in that manner.

### Database changes

None

### External dependencies

None

**Comment by DanSheps** [comment]
> Rack diagrams should reflect, as much as possible, the real world labeling that might exist on a device in a rack. Users who wish to use the labeling format of `{device.virtual_chassis.name}:{device.vc_position}` are able to name the devices in that manner.

I would like to add a counter point:

"Real World", the labelling would likely be the VC name, not the `switch name`.

VC is meant to capture the usage of technologies like "Stackwise" and "Virtual Stackwise" (I cannot speak to Juniper or HP as I have never stacked those), both of which only have a single name for both the VC and the individual switch hostname.  It is not meant for: vPC/MC-LAG, Firewall HA (in most cases), or similar situated technologies.

So, outside of corner cases where people are not using the VC as intended (to show a cluster between firewalls for example), the real world would actually be to show the VC name and annotate the rack drawing with a position indicator

**Comment by shepherdjay** [comment]
> the real world would actually be to show the VC name and annotate the rack drawing with a position indicator

This use case is still available if the code is removed. If you name your member devices in the same format Netbox currently imposes then there will be no change to the rack diagrams for that use case.

For better or worse we have physically labeled our members differently than `<vc_name>:<position>`  on our switch stacks. Similarly, others might have yet other ways they physically label the member devices (or don't label at all).
