### ISSUE TITLE
GPS search only accepts whole numbers for latitude and longitude

### ISSUE THREAD

**Issue by apm6** [netbox-community/netbox#13731]
### NetBox version

v3.1.5

### Python version

3.10

### Steps to Reproduce

Search for a site with a specific latitude or longitude: '/dcim/sites?latitude=43.378470'

### Expected Behavior

The API should return a site at that coordinate if there is one.

### Observed Behavior

Response is a 400: {'latitude': ['Enter a whole number.']}

I uncovered this issue while trying to search for sites within a gps range. I found that "latitude__lte", "latitude__gte", etc only worked with whole numbers.

**Comment by jeremystretch** [comment]
I cannot replicate this on NetBox v3.6.1.

> v3.1.5

Your version of NetBox is _very_ old. Please upgrade to the most recent stable release, as it appears the bug no longer exists.
