### ISSUE TITLE
Aditional Data in Script Errors

### ISSUE THREAD

**Issue by renatoalmeidaoliveira** [netbox-community/netbox#13732]
### NetBox version

v3.6.1

### Feature type

Change to existing functionality

### Proposed functionality

Add Script input data along with the error stack trace when a script fails

### Use case

When you have a script with multiple input variables, and are maintained by different teams it's useful to know what were the script inputs to correctly troubleshoot the error.

### Database changes

None

### External dependencies

None

**Comment by eronlloyd** [comment]
Being able to see the traceback more easily would be a great enhancement.

**Comment by abhi1693** [comment]
Blocked by #14438
