### ISSUE TITLE
Sort on module bay status field error

### ISSUE THREAD

**Issue by ahlee1** [netbox-community/netbox#13756]
### NetBox version

v3.6.1

### Python version

3.10

### Steps to Reproduce

1. Create a module bay
2. Sort Module bay on Status
3. Click on module bay tab again

### Expected Behavior

Either:
1. Sort on Module Bay Status
2. No sorting on module bay status allowed

### Observed Behavior

`<class 'django.core.exceptions.FieldError'>`

![image](https://github.com/netbox-community/netbox/assets/55637410/3a2f1cc6-abd6-4dea-a7f2-ace3892feadc)

**Comment by pv2b** [comment]
This seems to be valid, I can repro this in my own instance. Worse still, the error seems to be persistent, making it impossible to view any more module bays, even after removing browser cookies, implying the corrupted configuration is stored server-side somewhere.

**Comment by abhi1693** [comment]
You can clear the table configuration from your profile

**Comment by pv2b** [comment]
> You can clear the table configuration from your profile

Thanks for this, I was half-way through trying to figure out how to do it in nbshell, but the workaround if you get stuck in this place is:

1. Click your username in top right and select Preferences.
2. Under "Table Configurations" heading, under the "Clear table preferences" section, check the checkbox next to "ModuleBayTable" and press submit.
