### ISSUE TITLE
Add Contact to Prefix or Aggregate

### ISSUE THREAD

**Issue by francesco-noc** [netbox-community/netbox#13764]
### NetBox version

v3.7.3

### Feature type

New functionality

### Proposed functionality

The proposed functionality is to allow a Contact to be added to a Prefix or Aggregate. The changes required are very low-impact and mainly concern views, I already made them in our Netbox instance.

### Use case

In large organization (e.g. we own two class B networks) probably some aggregates or some prefix are managed by different people/groups. So, for instance, in the event of security incident or simply the deploy of new workstation/server it's necessary to contact that subnet's referent and it should be useful find it in Netbox.

**Comment by whtkam** [comment]
We also have such a need, we would even need it for IP addresses.

**Comment by francesco-noc** [comment]
Given our other needs and also requests here and in other discussions. I have implemented the ability to add contacts to Aggregates, Prefixes, IP ranges and IP addresses.

[Here](https://github.com/netbox-community/netbox/compare/develop...francesco-noc:netbox:13764-add-contact-to-ipam-objects) you can see the changes.

**Comment by francesco-noc** [comment]
This issue was opened with version 3.6.1 but my proposed implementation is for 3.7.3
