### ISSUE TITLE
Make bulk import/update header fields case-insensitive

### ISSUE THREAD

**Issue by peteeckel** [netbox-community/netbox#13775]
### NetBox version

v3.6.1

### Feature type

Change to existing functionality

### Proposed functionality

Based on the brief discussion of #13773 I suggest that the handling of the header line in bulk import/update should be case insensitive.

### Use case

This would avoid a couple of apparently common cases where data is silently ignored because of casing, which is often introduced when data from an export is converted to input data.

### Database changes

None

### External dependencies

None

**Comment by jeremystretch** [comment]
This would work for all built-in model fields, but it's not currently feasible for custom fields as we don't enforce case insensitivity on custom field names. For example, a model could have custom fields named `foo` and `Foo`. It's a terrible idea, of course, however it is currently a valid scenario.

**Comment by peteeckel** [comment]
Yuck. Well, once the PR for #11617 is implemented that won't be as much of an issue anymore either, so never mind.
