### ISSUE TITLE
Enable the device to which a module is assigned to be changed

### ISSUE THREAD

**Issue by francesco-noc** [netbox-community/netbox#13779]
### NetBox version

v3.6.1

### Feature type

Change to existing functionality

### Proposed functionality

Enable the device to which the module is assigned to be changed, as for inventory items.
This is not really a functionality, but more of an adaptation. 
In the ModuleForm class, change self.fields['device'].disabled from True to False.

### Use case

It may happen that a module (as well as an inventory item) is moved from one device to another and it would be useful not to have to delete and recreate it.

**Comment by francesco-noc** [comment]
Exactly. We have about a thousand network devices and it is a common occurrence for modules as well.

**Comment by jeremystretch** [comment]
A note for anyone who would like to tackle this implementation: Bear in mind that any components assigned to the module will need to be updated as well, as will the component counts of the former and new device.

**Comment by francesco-noc** [comment]
Hi @jeremystretch , as you suggested I did a [more detailed feature request](https://github.com/netbox-community/netbox/issues/15289) and I'm sorry, maybe this issue could be closed.
Anyway I proposed [an implementation](https://github.com/netbox-community/netbox/compare/develop...francesco-noc:netbox:13779-change-device-to-module) that destroy and recreate components when the module is edited.

**Comment by jeremystretch** [comment]
Ok, thanks. I'm going to close this one as a duplicate.
