### ISSUE TITLE
FIELD_CHOICES for dcim.PowerFeed.type

### ISSUE THREAD

**Issue by krasotinpa** [netbox-community/netbox#13780]
### NetBox version

v3.6.1

### Feature type

Change to existing functionality

### Proposed functionality

Hi 

Let's add  configurable choices to the dcim.PowerFeed.type field.
I've made appropriate changes to netbox/dcim/choices.py on our Netbox installation.
Now configuration.py accepts this config, for example:

```
FIELD_CHOICES = {
    'dcim.PowerFeed.type': (
        ('primary', 'Primary', 'blue'),
        ('redundant','Redundant', 'red'),
    ),
}
```

I'm ready to make pull 

### Use case

Power cables in our DC center have different colors for primary and backup power supply.
I think it's good practice to have these colors match the NETBOX.

**Comment by jeremystretch** [comment]
I appreciate the use case for adding colors, but we could do that internally without extending the choices. I don't see a use case for altering or extending the feed types themselves, and allowing that may preclude future functionality that relies on known values.

**Comment by krasotinpa** [comment]
OK, Jeremy.
Closing it
