### ISSUE TITLE
Add hint that drag/drop is possible when adding images

### ISSUE THREAD

**Issue by pv2b** [netbox-community/netbox#13788]
### NetBox version

v3.6.1.

### Feature type

Change to existing functionality

### Proposed functionality

I propose adding a hint label to /extras/image-attachments/add reading something like:

> You can also drag and drop an image file onto the field above to upload an image.

### Use case

Being able to drag/drop images is a cool feature, and it's a great timesaver for me, that way I don't have to to find the same image twice when uploading images from a large library. Putting a text label here would help inform other users about this cool pre-existing functionality that as far as I can tell is completely undocumented.

### Database changes

None.

### External dependencies

None.

**Comment by jeremystretch** [comment]
NetBox itself has no such feature. The ability to drag and drop a file into the form is browser-dependent, and we can't assume that it's supported.
