### ISSUE TITLE
option to hide script classes from being visible

### ISSUE THREAD

**Issue by FliesLikeABrick** [netbox-community/netbox#13795]
### NetBox version

v3.6.1

### Feature type

New functionality

### Proposed functionality

We would like to add a way to hide certain script classes from the UI when they do not have user-facing functionality (no run method).  There seem to be a few ways this could be implemented:
- Hide scripts that do not contain a run() method.  This check could potentially be added into is_script() so that scripts without a run() method are inherently hidden.  That is, codify the fact that a script without a run() method is not actually a script.
- Add an option to the script module similar to script_order that lists classes which should be suppressed (something like "script_hide=(MyScript)), then use that list in the creation of sxripts to exclude those scripts.  Add a check like "if cls not in script_hide" to the logic that creates the list of scripts)
- Add an option to the script module which says that "script_order" is an absolute/complete list, and those scripts not listed should not be visible.    Right now, any script not listed in "script_order" is just appended to the end.  Such an option perhaps would be a boolean script_display_unordered=True/False

### Use case

We have a class hierarchy for our Netbox scripts, to abstract common functionality.  We do not want our intermediate classes from the module(s) being visible in the UI, as those classes do not contain user functionality

### Database changes

None

### External dependencies

None

**Comment by FliesLikeABrick** [comment]
I have a branch ready for a pull request, if this issue/request is accepted.

**Comment by FliesLikeABrick** [comment]
@abhi1693  can this feature request be evaluated by the team? I have a branch ready to contribute but am unable to open a PR until this is accepted

**Comment by tibobo67** [comment]
+1 for this feature, anyway you prefer to do it !

**Comment by FliesLikeABrick** [comment]
Hello, it has been 5 months since this was reported and I have offered a code fix - is anyone available to triage this request  or provide feedback on the solution offered?  I am not sure why the last two comments were deleted.

**Comment by jeremystretch** [comment]
IIRC inheriting from `BaseScript` rather than `Script` prevents a class from being listed. @FliesLikeABrick have you tried that?

I'm going to mark this as blocked by #12510 for now as I want to avoid potential conflicts with work we're doing on the Script class for v4.0.

**Comment by FliesLikeABrick** [comment]
@jeremystretch  thank you for the reply - we are inheriting from Script() currently and our intermediate class is appearing in the UI

class CNVRScript(Script):

**Comment by arthanson** [comment]
Closing as can use BaseScript

**Comment by rizlas** [comment]
Hi,
I have a case where an option to hide will be perfect. Inheriting from BaseScript is not possible because it would also make the script that inherits from the base class disappear. 

I've opened a discussion with example here: https://github.com/netbox-community/netbox/discussions/17040
