### ISSUE TITLE
"Mark Installed" tooltip doesn't properly update to "Mark Planned" 

### ISSUE THREAD

**Issue by pv2b** [netbox-community/netbox#13806]
### NetBox version

v3.6.1

### Python version

3.8

### Steps to Reproduce

1. Go to an enabled non-virtual interface with an installed cable in the device interface view.
2. Edit the cable and mark it as planned. (Important, do it this way, not through the "mark planned" button.)
3. Hover over the "mark installed" button, notice that it says "mark installed".
4. Click the "mark installed" button to mark the cable as installed.
5. WITHOUT navigating away from the page, hover over the button again and read the tooltip on the button.

### Expected Behavior

The tooltip should read "mark planned" since the cable is now marked as installed and the change would be to mark it as planned.

### Observed Behavior

The tooltip actually reads "mark installed".

**Comment by pv2b** [comment]
I found this bug when working on a fix for #13712, going to send in a fix for this in the same PR

**Comment by DanSheps** [comment]
Since the previous issue was closed due to a lack of activity, I am putting this back to needs owner for now.  If someone would like to take this on, just reply here.

**Comment by pv2b** [comment]
Hello,

The lack of activity is due to a lack of feedback from the Netbox developer side to my pull requests.

There's a pull request #13874 that's been avaiting maintainer feedback for the last 6 months that addresses this issue.

I also have other pull requests in for the Netbox projects that you have accepted me as an assignee on and then subsequently have seen no review from your side. It's disappointing since I've put effort into the project only for it to get ignored, which means I've not really been interested in contributing more to the project.

I'm happy to work with you on any concerns you have with any of my open issues or PR's, but I won't be contributing anything more until those existing PR's are addressed in some way other than a Github stalebot.

**Comment by DanSheps** [comment]
@pv2b I will re-assign you.

In  the future, perhaps make sure you make "request review" from at least Jeremy (unless you feel it is better suited for someone else).  To be clear, I am not saying this is your fault at all, but it serves as a reminder for the people you request a review of to review it (it also shows in our notifications as a pending review request)

**Comment by DanSheps** [comment]
Closed by #13874
