### ISSUE TITLE
Add render-config API endpoint for virtual machine

### ISSUE THREAD

**Issue by pkorovin** [netbox-community/netbox#13808]
### NetBox version

v3.6.2-dev

### Feature type

New functionality

### Proposed functionality

Add config template rendering API endpoint for virtual machine.
Config template rendering feature was added in the interface, but there's no corresponding API endpoint: /api/virtualization/virtual-machines/{id}/render-config/

### Use case

Allow config template rendering for virtual machines using NetBox API.

**Comment by LuPo** [comment]
Can I take  this issue on me?

**Comment by jeremystretch** [comment]
@LuPo do you think you'd be able to submit a PR for it by early next week? We're due to release the first v3.7 beta by the end of November, so we'll need to have all milestone issues completed very soon.

**Comment by LuPo** [comment]
Yes, I will submit a PR for review today.

**Comment by jeremystretch** [comment]
@LuPo awesome, thank you for stepping up!

**Comment by LuPo** [comment]
@pkorovin Ah, I have noticed that you have also stepped in just now. I'll close my PR at this point because you have opened the issue :)
