### ISSUE TITLE
Missing header for `description` field in customfield template

### ISSUE THREAD

**Issue by miaow2** [netbox-community/netbox#13802]
### NetBox version

v3.6.1

### Python version

3.10

### Steps to Reproduce

1. Create custom field
2. open custom field view
3. description field is missing header

![image](https://github.com/netbox-community/netbox/assets/28296817/0a3c2bdf-8747-4201-a69f-c50241e42186)

### Expected Behavior

description field should have header `Description`

[customfield.html](https://github.com/netbox-community/netbox/blob/develop/netbox/templates/extras/customfield.html#L35) is missing `{% trans "Description" %}`

### Observed Behavior

description field header empty

**Comment by jeremystretch** [comment]
Thanks for the report @miaow2!
