### ISSUE TITLE
New interface Type 

### ISSUE THREAD

**Issue by maxencewrt** [netbox-community/netbox#13801]
### NetBox version

v3.6.1

### Feature type

Data model extension

### Proposed functionality

Hello,
First of all thanks a lot for all the job done on this incredible app.
I'm reaching you to ask you a Data Model Extension. 
Can you please add new Interface Type : 
-> RJ45 
-> LC/UPC + LC/APC 
-> E2000/PS + E2000/LC 

For some devices (mostly the DWDM device) there is no plug-able in it. 
You just have a connector. 

For example on the attached picture all the port in blue are LC (but we don't have a pluggable SFP or QSFP inside) 
![bastos](https://github.com/netbox-community/netbox/assets/22428740/0149eca1-95ee-47b1-9100-fbf2d2f63a6c)

### Use case

DWDM devices 

### Database changes

Interface -> Type 

### External dependencies

none

**Comment by jeremystretch** [comment]
> Can you please add new Interface Type :
> -> RJ45
> -> LC/UPC + LC/APC
> -> E2000/PS + E2000/LC

These are port form factors, not interface types. RJ45 is actually 8P8C, and both LC/UPC and LC/APC already exist. E-2000 appears to be some form of proprietary hardware.

**Comment by maxencewrt** [comment]
Hellor @jeremystretch,
Thanks for your reply. 
So what's your recommendation for Optical equipment as you can see on the picture ? 
In the same line card we can have QSFP module and form factors connector.
Max

**Comment by jeremystretch** [comment]
@maxencewrt I'm afraid feature requests are only for well-formed proposals effecting a change in the code base. For help with modeling specific objects or topologies, please consider starting a [discussion](https://github.com/netbox-community/netbox/discussions/new/choose).

I'm going to close this issue as it's not actionable in its current form.
