### ISSUE TITLE
Impossible to import a yaml file in Journal Entry section

### ISSUE THREAD

**Issue by MrReeseRUThere** [netbox-community/netbox#13810]
### NetBox version

v3.5.1

### Python version

3.8

### Steps to Reproduce

1.Click on "Journal Entries"
2.Click on "Import"
3.Choose file in the Upload file section

### Expected Behavior

A new Journal Entry get created.

### Observed Behavior

![Screenshot from 2023-09-19 07-31-09](https://github.com/netbox-community/netbox/assets/145418977/d16e1de2-b0a5-4cea-9abf-5f460efd282b)

**Comment by jeremystretch** [comment]
Thank you for opening a bug report. Unfortunately, the information you have provided is not sufficient for someone else to attempt to reproduce the reported behavior. Remember, each bug report must include detailed steps that someone else can follow on a clean, empty NetBox installation to reproduce the exact problem you're experiencing. These instructions should include the creation of any involved objects, any configuration changes, and complete accounting of the actions being taken. Also be sure that your report does not reference data on the public NetBox demo, as that is subject to change at any time by an outside party and cannot be relied upon for bug reports.

**Comment by jeremystretch** [comment]
This issue is being closed as no further information has been provided. If you would like to revisit this topic, please first modify your original post to include all the requested detail, and then ask that the issue be reopened.
