### ISSUE TITLE
Regression in Import form Field Options color

### ISSUE THREAD

**Issue by sleepinggenius2** [netbox-community/netbox#13839]
### NetBox version

v3.6.2

### Python version

3.8

### Steps to Reproduce

1. Navigate to any Import form
2. Observe the low contrast on the Field and Accessor columns of the Field Options table

### Expected Behavior

The Field and Accessor columns of the Field Options table of an Import form should have sufficient contrast.

### Observed Behavior

#13827 was introduced in v3.6.2 to fix #13653, but as a side effect, it changed the color of all `<code>` tags, which caused this regression.

**Comment by sleepinggenius2** [comment]
Before:
![image](https://github.com/netbox-community/netbox/assets/24281183/19df9ea0-a3ee-4cb3-b3d2-ba48ed8dd9bc)

After:
![image](https://github.com/netbox-community/netbox/assets/24281183/a75ecfa1-9769-4329-b1a4-cffb5c2be2e2)

**Comment by jeremystretch** [comment]
Ok, that's what I see too. So it's not that the text is unreadable, it just has less contrast than before in dark mode.
