### ISSUE TITLE
Missing dependency on requirements.txt

### ISSUE THREAD

**Issue by aseques** [netbox-community/netbox#13850]
### NetBox version

develop

### Python version

3.8

### Steps to Reproduce

On commit d87235af2fc560731802ba475018b13a0c82af5c from 20230426 an import of the module requests was added into netbox/settings.py

It needs to be added into the general requirements.txt because it's missing on default installs

`ModuleNotFoundError: No module named 'requests'`

### Expected Behavior

Update should have taken care of this new dependency

### Observed Behavior

`ModuleNotFoundError: No module named 'requests'`

**Comment by jeremystretch** [comment]
`requests` is not specifically called out in `requirements.txt` but is pulled in via two required packages, so if you have installed NetBox per the documentation this condition should not occur.

**Comment by jeremystretch** [comment]
We've added `requests` to `requirements.txt`, although it's still not clear how the situation above developed.

**Comment by aseques** [comment]
Thansk @jeremystretch  unfortunately I wasn't able to create  reproducible setup but I'm glad it's fixed now
