### ISSUE TITLE
Full trace with splitter cable between patch panels

### ISSUE THREAD

**Issue by opensourceXnetbox** [netbox-community/netbox#13865]
### NetBox version

v3.6.1

### Feature type

New functionality

### Proposed functionality

In one scenario, a switch is connected to another switch via the passive cabling using splitting/breakout cables. The split cables are physically two cables between one patch panel and the other patch panel. Currently the NetBox sol cannot display a split, which is why the trace does not work and no `connection` is displayed. Currently the NetBox can only display these two physical cables as one with multi-terminations, i.e. there are two terminations on each side. However, this does not correspond to reality. Therefore I propose the change that the NetBox displays in this case both paths between the splitting cables, because the start and end point is exactly the same.
 Here is a before and after picture:
![netbox-trace-problem](https://github.com/netbox-community/netbox/assets/110609354/3bca42a9-f18d-4bf6-bb3f-b447bf648773)
![image](https://github.com/netbox-community/netbox/assets/110609354/b9079695-ae6e-48b0-bf69-aab4a37c17c0)
The last picture shows my customization

### Use case

The use case is a complete cable trace with splitting cables across multiple patch panels. This means that the end point is correctly displayed under the interface connection.

### Database changes

I'm not deep enough into it, but I don't think so, since the general connection is currently already working

**Comment by jsenecal** [comment]
Already covered by PR #12929 I believe...

**Comment by jsenecal** [comment]
Already covered by PR https://github.com/netbox-community/netbox/pull/13337 I believe...
