### ISSUE TITLE
Object list dashboard widgets always show a horizontal scrollbar

### ISSUE THREAD

**Issue by heroin-moose** [netbox-community/netbox#13863]
### NetBox version

v3.6.2

### Python version

3.10

### Steps to Reproduce

1. Open a dashboard

### Expected Behavior

Change Log contents fits the card.

### Observed Behavior

For some reason it's always impossible to resize Change Log in to fit all the contents without scrollbars. I have a laptop with 3120x2080 on a 14" display and this is what I get:

![image](https://github.com/netbox-community/netbox/assets/15263497/50925a85-d38c-4119-8ef2-e9f7dacb7079)

Both horizontal and vertical bars are present, unless I make the card really long. If I do that, I end with a lot of wasted blank space in the card that look odd. I can't get rid of horizontal scrolling unless I zoom out the page a bit.

**Comment by jeremystretch** [comment]
This isn't specific to the changelog itself; it can be seen with any embedded table within a dashboard widget. It's likely we just need to adjust the padding or overflow of an HTML element.

**Comment by jsenecal** [comment]
Somewhat related to: https://github.com/netbox-community/netbox/issues/13076

**Comment by jeremystretch** [comment]
Marking this as blocked by #12128

**Comment by arthanson** [comment]
This is no longer an issue in NB v4.0 (Beta) so closing
