### ISSUE TITLE
API location filter wrong datatype

### ISSUE THREAD

**Issue by aauerswald** [netbox-community/netbox#13881]
### NetBox version

v.3.6.2

### Python version

3.8

### Steps to Reproduce

- Add a location to netbox and a rack assigned to these location. remember id and slug of the location.
- Go to your site api/schema/swagger-ui/#/dcim/dcim_racks_list
- Navigate to location filter:
 - location array
 - location__narray
- try the location slug and location id

### Expected Behavior

using a slug as filter in field location array/location__narray result the filtered racks list

### Observed Behavior

no result by using the id (Select a valid choice ....)
no result by using the slug (index0errorValue must be an integer)

**Comment by jeremystretch** [comment]
Thank you for opening a bug report. Unfortunately, the information you have provided is not sufficient for someone else to attempt to reproduce the reported behavior. Remember, each bug report must include detailed steps that someone else can follow on a clean, empty NetBox installation to reproduce the exact problem you're experiencing. These instructions should include the creation of any involved objects, any configuration changes, and complete accounting of the actions being taken. Also be sure that your report does not reference data on the public NetBox demo, as that is subject to change at any time by an outside party and cannot be relied upon for bug reports.

**Comment by aauerswald** [comment]
I changed the report.

**Comment by jeremystretch** [comment]
Please specify the exact API request you're sending.

**Comment by aauerswald** [comment]
curl -X 'GET' \
  'https://YOURDOMAIN/api/dcim/racks/?location=YOUR-LOCATION-ID' \
  -H 'accept: application/json'
