### ISSUE TITLE
Display Total Weight in Rack View

### ISSUE THREAD

**Issue by darcynz** [netbox-community/netbox#13895]
### NetBox version

v3.5.8

### Feature type

New functionality

### Proposed functionality

Now that we can that total rack weight is calculated and displayed on a single Rack it would be great to be able to see that when viewing and filtering racks. 

A bonus would be able to see that as a utilization bar against the max weight field in a similar way that 'Space' is displayed.

### Use case

Enable decisions decision makers to be able to easily see which racks might be approaching or maxing out weight restrictions.

### Database changes

No Database change required.

### External dependencies

No External dependency

**Comment by jeremystretch** [comment]
Thank you for your interest in extending NetBox. Unfortunately, the information you have provided does not constitute an actionable feature request. Per our [contributing guide](https://github.com/netbox-community/netbox/blob/develop/CONTRIBUTING.md), a feature request must include a thorough description of the proposed functionality, including any database changes, new views or API endpoints, and so on. It must also include a detailed use case justifying its implementation. If you would like to elaborate on your proposal, please modify your post above. If sufficient detail is not added, this issue will be closed.

**Comment by darcynz** [comment]
I've had a look at the contribution guide, and the request is pretty simple/straightforward. I'm happy to provide more detail, but simply just seeing the total weight field that is visible in rack view. Can add a screenshot if that would help?
