### ISSUE TITLE
Addition of default tenant to user profile

### ISSUE THREAD

**Issue by SpudDogg** [netbox-community/netbox#13908]
### NetBox version

v3.6.1

### Feature type

New functionality

### Proposed functionality

Addition of a field to user profile to allow tenant definition.  This could then be used to auto-populate the tenant field when adding an item to various areas of Netbox.

### Use case

When manually adding several devices, vLANs, IP ranges, etc this would save a couple clicks and some scrolling time per entry.

**Comment by indy-independence** [comment]
I also think this would be a great addition!
