### ISSUE TITLE
device.interfaces.all() on Master Virtual Chassis device, returning only Master interfcaces

### ISSUE THREAD

**Issue by jonatangobbato** [netbox-community/netbox#13904]
### NetBox version

v3.6.1

### Python version

3.8

### Steps to Reproduce

1. Creates a config template with:

{% for interface in device.interfaces.all() %}
{{ interface.name }}
{% endfor %}

2. Render a config for a Master Device of Virtual Chassis with 2 members.

### Expected Behavior

A rendered config with all interfaces of master device and the second devices of virtual chassis.

Like:

1/1/1
1/1/2
1/1/x
2/1/1
2/1/2
2/1/x

### Observed Behavior

Only interfaces of master devices are rendered.

I dont know if it is a bug or im using wrong view for the template, if its the case, i need a help to set correct view on template to render all interfaces o virtual chassis.

thanks

**Comment by jeremystretch** [comment]
This is working as intended. You'll need to use the `vc_interfaces()` method on the Device model for interfaces that belong to peer VC members.

**Comment by jonatangobbato** [comment]
Thanks @jeremystretch thats worked. Where can i get thats methos for use in config templates?
