### ISSUE TITLE
Available IP address not appears on Prefix IP Addresses Menu

### ISSUE THREAD

**Issue by jonatangobbato** [netbox-community/netbox#13913]
### NetBox version

v3.6.3

### Python version

3.10

### Steps to Reproduce

1. Create a prefix: 10.3.36.0/23
2. Open new prefix and click on Ip Addresses

### Expected Behavior

Netbox shows available IP adresses.

### Observed Behavior

Available IP Address does not appears:

![image](https://github.com/netbox-community/netbox/assets/29125329/d94d4cae-46d8-4ea0-a25c-c546a05c5a8a)

**Comment by abhi1693** [comment]
Thank you for opening a bug report. Unfortunately, the information you have provided is not sufficient for someone else to attempt to reproduce the reported behavior. Remember, each bug report must include detailed steps that someone else can follow on a clean, empty NetBox installation to reproduce the exact problem you're experiencing. These instructions should include the creation of any involved objects, any configuration changes, and complete accounting of the actions being taken. Also be sure that your report does not reference data on the public NetBox demo, as that is subject to change at any time by an outside party and cannot be relied upon for bug reports.

**Comment by jonatangobbato** [comment]
im revert to backup to version 3.6.1, on version 3.6.1, the available Ip Addressess option appears normaly.

![image](https://github.com/netbox-community/netbox/assets/29125329/1dbf4405-62c9-4d15-b6c4-52d27619ae4c)

After upgrade to versions 3.6.2 following the instructions 

https://docs.netbox.dev/en/stable/installation/upgrading/

the Available IP Addresses does not appears anymore.

![image](https://github.com/netbox-community/netbox/assets/29125329/8db5ab3c-c5c4-45bf-88c0-14a808f26a8f)


I have only few customizations to default netbox versions:

I have the plugin "topology_views", the error continues when disabling the plugin and i have some custom validators on the confgiuration.py file:

below my configuration.py file:

`import re
from extras.validators import CustomValidator

class cvReservationMAC(CustomValidator):
    def validate(self, instance):
        if instance.status == 'dhcp' and not instance.cf["MAC_Address"]:
            self.fail("DHCP Reservations must have Mac Address!", field='cf_MAC_Address')

class cvReservationDNSName(CustomValidator):
    def validate(self, instance):
        if instance.status == 'dhcp' and not instance.dns_name:
            self.fail("DHCP Reservations must have DNS Name!", field='dns_name')

CUSTOM_VALIDATORS = {
    'ipam.ipaddress': (
        cvReservationMAC(),
        cvReservationDNSName(),
    )
}

#########################
#                       #
#   Required settings   #
#                       #
#########################

# This is a list of valid fully-qualified domain names (FQDNs) for the NetBox server. NetBox will not permit write
# access to the server via any other hostnames. The first FQDN in the list will be treated as the preferred name.
#
# Example: ALLOWED_HOSTS = ['netbox.example.com', 'netbox.internal.local']
ALLOWED_HOSTS = ['*']

# PostgreSQL database configuration. See the Django documentation for a complete list of available parameters:
#   https://docs.djangoproject.com/en/stable/ref/settings/#databases
DATABASE = {
    'NAME': 'netbox',         # Database name
    'USER': 'netbox',               # PostgreSQL username
    'PASSWORD': 'XXXXXXXXXXXXXXXXXXXXX',           # PostgreSQL password
    'HOST': 'localhost',      # Database server
    'PORT': '',               # Database port (leave blank for default)
    'CONN_MAX_AGE': 300,      # Max database connection age
}

# Redis database settings. Redis is used for caching and for queuing background tasks such as webhook events. A separate
# configuration exists for each. Full connection details are required in both sections, and it is strongly recommended
# to use two separate database IDs.
REDIS = {
    'tasks': {
        'HOST': 'localhost',
        'PORT': 6379,
        # Comment out `HOST` and `PORT` lines and uncomment the following if using Redis Sentinel
        # 'SENTINELS': [('mysentinel.redis.example.com', 6379)],
        # 'SENTINEL_SERVICE': 'netbox',
        'USERNAME': '',
        'PASSWORD': '',
        'DATABASE': 0,
        'SSL': False,
        # Set this to True to skip TLS certificate verification
        # This can expose the connection to attacks, be careful
        # 'INSECURE_SKIP_TLS_VERIFY': False,
        # Set a path to a certificate authority, typically used with a self signed certificate.
        # 'CA_CERT_PATH': '/etc/ssl/certs/ca.crt',
    },
    'caching': {
        'HOST': 'localhost',
        'PORT': 6379,
        # Comment out `HOST` and `PORT` lines and uncomment the following if using Redis Sentinel
        # 'SENTINELS': [('mysentinel.redis.example.com', 6379)],
        # 'SENTINEL_SERVICE': 'netbox',
        'USERNAME': '',
        'PASSWORD': '',
        'DATABASE': 1,
        'SSL': False,
        # Set this to True to skip TLS certificate verification
        # This can expose the connection to attacks, be careful
        # 'INSECURE_SKIP_TLS_VERIFY': False,
        # Set a path to a certificate authority, typically used with a self signed certificate.
        # 'CA_CERT_PATH': '/etc/ssl/certs/ca.crt',
    }
}

# This key is used for secure generation of random numbers and strings. It must never be exposed outside of this file.
# For optimal security, SECRET_KEY should be at least 50 characters in length and contain a mix of letters, numbers, and
# symbols. NetBox will not run without this defined. For more information, see
# https://docs.djangoproject.com/en/stable/ref/settings/#std:setting-SECRET_KEY
SECRET_KEY = 'XXXXXXXXXXXXXXXXXXXXXX'


#########################
#                       #
#   Optional settings   #
#                       #
#########################

# Specify one or more name and email address tuples representing NetBox administrators. These people will be notified of
# application errors (assuming correct email settings are provided).
ADMINS = [
    # ('John Doe', 'jdoe@example.com'),
]

# Permit the retrieval of API tokens after their creation.
ALLOW_TOKEN_RETRIEVAL = False

# Enable any desired validators for local account passwords below. For a list of included validators, please see the
# Django documentation at https://docs.djangoproject.com/en/stable/topics/auth/passwords/#password-validation.
AUTH_PASSWORD_VALIDATORS = [
    # {
    #     'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    #     'OPTIONS': {
    #         'min_length': 10,
    #     }
    # },
]

# Base URL path if accessing NetBox within a directory. For example, if installed at https://example.com/netbox/, set:
# BASE_PATH = 'netbox/'
BASE_PATH = ''

# API Cross-Origin Resource Sharing (CORS) settings. If CORS_ORIGIN_ALLOW_ALL is set to True, all origins will be
# allowed. Otherwise, define a list of allowed origins using either CORS_ORIGIN_WHITELIST or
# CORS_ORIGIN_REGEX_WHITELIST. For more information, see https://github.com/ottoyiu/django-cors-headers
CORS_ORIGIN_ALLOW_ALL = False
CORS_ORIGIN_WHITELIST = [
    # 'https://hostname.example.com',
]
CORS_ORIGIN_REGEX_WHITELIST = [
    # r'^(https?://)?(\w+\.)?example\.com$',
]

# The name to use for the CSRF token cookie.
CSRF_COOKIE_NAME = 'csrftoken'

# Set to True to enable server debugging. WARNING: Debugging introduces a substantial performance penalty and may reveal
# sensitive information about your installation. Only enable debugging while performing testing. Never enable debugging
# on a production system.
DEBUG = False

# Set the default preferred language/locale
DEFAULT_LANGUAGE = 'en-us'

# Email settings
EMAIL = {
    'SERVER': 'localhost',
    'PORT': 25,
    'USERNAME': '',
    'PASSWORD': '',
    'USE_SSL': False,
    'USE_TLS': False,
    'TIMEOUT': 10,  # seconds
    'FROM_EMAIL': '',
}

# Localization
ENABLE_LOCALIZATION = False

# Exempt certain models from the enforcement of view permissions. Models listed here will be viewable by all users and
# by anonymous users. List models in the form `<app>.<model>`. Add '*' to this list to exempt all models.
EXEMPT_VIEW_PERMISSIONS = [
    # 'dcim.site',
    # 'dcim.region',
    # 'ipam.prefix',
]

# HTTP proxies NetBox should use when sending outbound HTTP requests (e.g. for webhooks).
# HTTP_PROXIES = {
#     'http': 'http://10.10.1.10:3128',
#     'https': 'http://10.10.1.10:1080',
# }

# IP addresses recognized as internal to the system. The debugging toolbar will be available only to clients accessing
# NetBox from an internal IP.
INTERNAL_IPS = ('127.0.0.1', '::1')

# Enable custom logging. Please see the Django documentation for detailed guidance on configuring custom logs:
#   https://docs.djangoproject.com/en/stable/topics/logging/
LOGGING = {}

# Automatically reset the lifetime of a valid session upon each authenticated request. Enables users to remain
# authenticated to NetBox indefinitely.
LOGIN_PERSISTENCE = False

# Setting this to True will permit only authenticated users to access any part of NetBox. By default, anonymous users
# are permitted to access most data in NetBox but not make any changes.
LOGIN_REQUIRED = False

# The length of time (in seconds) for which a user will remain logged into the web UI before being prompted to
# re-authenticate. (Default: 1209600 [14 days])
LOGIN_TIMEOUT = None

# The view name or URL to which users are redirected after logging out.
LOGOUT_REDIRECT_URL = 'home'

# The file path where uploaded media such as image attachments are stored. A trailing slash is not needed. Note that
# the default value of this setting is derived from the installed location.
# MEDIA_ROOT = '/opt/netbox/netbox/media'

# Expose Prometheus monitoring metrics at the HTTP endpoint '/metrics'
METRICS_ENABLED = False

# Enable installed plugins. Add the name of each plugin to the list.
PLUGINS = ["netbox_topology_views"]

# Plugins configuration settings. These settings are used by various plugins that the user may have installed.
# Each key in the dictionary is the name of an installed plugin and its value is a dictionary of settings.
PLUGINS_CONFIG = {
    'netbox_topology_views': {
        'allow_coordinates_saving': True
    }
}

# Remote authentication support
REMOTE_AUTH_ENABLED = False
REMOTE_AUTH_BACKEND = 'netbox.authentication.LDAPBackend'
REMOTE_AUTH_HEADER = 'HTTP_REMOTE_USER'
REMOTE_AUTH_AUTO_CREATE_USER = True
REMOTE_AUTH_DEFAULT_GROUPS = []
REMOTE_AUTH_DEFAULT_PERMISSIONS = {}

# This repository is used to check whether there is a new release of NetBox available. Set to None to disable the
# version check or use the URL below to check for release in the official NetBox repository.
RELEASE_CHECK_URL = None
# RELEASE_CHECK_URL = 'https://api.github.com/repos/netbox-community/netbox/releases'

# The file path where custom reports will be stored. A trailing slash is not needed. Note that the default value of
# this setting is derived from the installed location.
# REPORTS_ROOT = '/opt/netbox/netbox/reports'

# Maximum execution time for background tasks, in seconds.
RQ_DEFAULT_TIMEOUT = 300

# The file path where custom scripts will be stored. A trailing slash is not needed. Note that the default value of
# this setting is derived from the installed location.
# SCRIPTS_ROOT = '/opt/netbox/netbox/scripts'

# The name to use for the session cookie.
SESSION_COOKIE_NAME = 'sessionid'

# By default, NetBox will store session data in the database. Alternatively, a file path can be specified here to use
# local file storage instead. (This can be useful for enabling authentication on a standby instance with read-only
# database access.) Note that the user as which NetBox runs must have read and write permissions to this path.
SESSION_FILE_PATH = None

# By default, uploaded media is stored on the local filesystem. Using Django-storages is also supported. Provide the
# class path of the storage driver in STORAGE_BACKEND and any configuration options in STORAGE_CONFIG. For example:
# STORAGE_BACKEND = 'storages.backends.s3boto3.S3Boto3Storage'
# STORAGE_CONFIG = {
#     'AWS_ACCESS_KEY_ID': 'Key ID',
#     'AWS_SECRET_ACCESS_KEY': 'Secret',
#     'AWS_STORAGE_BUCKET_NAME': 'netbox',
#     'AWS_S3_REGION_NAME': 'eu-west-1',
# }

# Time zone (default: UTC)
TIME_ZONE = 'UTC'

# Date/time formatting. See the following link for supported formats:
# https://docs.djangoproject.com/en/stable/ref/templates/builtins/#date
DATE_FORMAT = 'N j, Y'
SHORT_DATE_FORMAT = 'Y-m-d'
TIME_FORMAT = 'g:i a'
SHORT_TIME_FORMAT = 'H:i:s'
DATETIME_FORMAT = 'N j, Y g:i a'
SHORT_DATETIME_FORMAT = 'Y-m-d H:i'
ENFORCE_GLOBAL_UNIQUE = True


def regex_replace(value, filter, new_value):
    return re.sub(str(filter),str(new_value),str(value))

JINJA2_FILTERS = {
    'regex_replace': regex_replace,
}
`

Its basically a default netbox install, can i collect more logs to help track the bug?

**Comment by jonatangobbato** [comment]
Problem persists even when commenting the lines of custom validators and Jinja Filters on configuration.py

**Comment by haki99** [comment]
I have the same problem. Our service desk uses the Netbox's IPAM part to reserve IP addresses on the DHCP server (A script was written to keep Netbox's IPAM data up-to-date with the DHCP server)

For convenience the team filtered the IP's by status in a prefix, so the available IP's appeared in the top or bottom, but now it's not possible after the changes. I received multiple tickets about the missing available IP's and it took me a while to figure it out and it's hard to reteach people how to use it.

I tried to find the change about this, sadly I didn't find anything. I think it should be wise to note these changes about the fronted usage of Netbox in the future.

I [read this issue](https://github.com/netbox-community/netbox/issues/13868), IMHO now it's not a good behavior as it works, it should be working as previously, because 'available' is also a status of an IP address. I kindly ask to revert it back as it was, because if someone is using the IPAM part of Netbox as a living clone of a DHCP server, the available IP's should be also part of a status ordering.

**Comment by jonatangobbato** [comment]
I think that relates to this [https://github.com/netbox-community/netbox/issues/11209](url)

**Comment by jonatangobbato** [comment]
@abhi1693 can we help with some more information?

**Comment by jonatangobbato** [comment]
@jeremystretch , i have no ordering set for Ip Address Table, only for show colums:

![image](https://github.com/netbox-community/netbox/assets/29125329/ef2de955-4822-43ad-a9de-1ae161264eea)

But, whem removing the user preference in Ip Address Table, Available IPs appears normally after upgrade.

After upgrade, i have added the columns to the table and the Available IPs appears normally, seems to be something with the upgrade proccess when preferences are set, ordering preferences or any other.

For now, thats worked. Thank you @jeremystretch

**Comment by jeremystretch** [comment]
@jonatangobbato thanks for following up. It's very strange that clearing the table preferences resolved the issue when no ordering was set. Maybe it was tied to a custom field that had since been deleted? It's difficult to know without inspecting the raw preferences data (which is gone now).

I'm going to close this out as I don't believe there's anything further we can do at this point without confirmed reproduction steps. I'm happy to re-open this if anyone encounters the same issue and can successfully reproduce it.
