### ISSUE TITLE
Make L2VPN identifier required and unique and add it to search index

### ISSUE THREAD

**Issue by dejantep** [netbox-community/netbox#13927]
### NetBox version

v3.5.7

### Feature type

Change to existing functionality

### Proposed functionality

IMHO "identifier" is the field that should enforce uniqueness because of its nature. "Identifier" field is already limited to numbers and it fits the purpose.

Apply similar functionality as to VLAN. It could be globally unique or with option to assing it to site or region depending on implementation strategy. 

Add it to search index

### Use case

When creating L2VPNs field "slug" is used to enforce uniqueness. It derives from human friendly field for "Name".
It's not suitable for enforcing uniqueness.

IMHO "identifier" is the field that should enforce uniqueness since all l2vpn services have an ID. It could be globally unique or with option to assing it to  site or region depending on your naming strategy. Similar functionality to VLAN.

"Identifier" field is already limited to numbers and it fits the purpose.

### Database changes

dont know

### External dependencies

dont know

**Comment by DanSheps** [comment]
> Apply similar functionality as to VLAN. It could be globally unique or with option to assing it to site or region depending on implementation strategy.

By their nature, L2VPN's are global (they do not belong to a specific site, and this for the most part is true in the real world), however the identifier are reusable within separate "fabrics" so using it as the sole value to determine uniqueness, for me, is a non-starter.  We cannot use site or region in combination to determine uniqueness either as a fabric can span multiple sites or regions.

**Comment by dejantep** [comment]
Maybe i'm confused by field naming but to me _name_ is something proprietary and _identifier_ something unique as the name suggests. Would you say that _identifier_ is regarded as vc-id?

**Comment by DanSheps** [comment]
> Maybe i'm confused by field naming but to me _name_ is something proprietary and _identifier_ something unique as the name suggests. Would you say that _identifier_ is regarded as vc-id?

Identifier is a generic identifier, if whatever overlay you are using supports a generic identifier.  This was made not required as we don't know what types of l2vpns people might be modelling or even if every type has an identifier attached to it (maybe it doesn't)
