### ISSUE TITLE
SVG error when rendering uneven interfaces

### ISSUE THREAD

**Issue by cpmills1975** [netbox-community/netbox#13922]
### NetBox version

v3.6.3

### Python version

3.8

### Steps to Reproduce

- Create three devices, two with at least one interface (device A and device B), one with at least two (device C), and a fourth device with at least three front and rear ports (device D).
- Connect the interface of device A to the four front ports of device D.
- Connect one of the rear ports to the interface on device B.
- Connect the other two rear ports to the two interfaces on device C.

View the cable trace from the connected port on Device A

### Expected Behavior

Device B should clearly show it has one interface and Device C should show that it has two interfaces.

### Observed Behavior

It looks like there are three interfaces spread equally across two devices.

<img width="438" alt="Screenshot 2023-09-27 at 23 50 11" src="https://github.com/netbox-community/netbox/assets/1878544/2c3f87ac-62ba-4549-9d1f-bd6045295ce3">

**Comment by jeremystretch** [comment]
@Moehritz would you mind commenting here so I can assign this issue to you as well please (for PR #14750)?

**Comment by Moehritz** [comment]
sure
