### ISSUE TITLE
Bug in the parser part that declares Interface, etc. together.

### ISSUE THREAD

**Issue by penM000** [netbox-community/netbox#13924]
### NetBox version

v3.6.3

### Python version

3.8

### Steps to Reproduce

1. IF[a,b,c,d]" generates "IFa, IFb, IFc, IFd".
![image](https://github.com/netbox-community/netbox/assets/33054826/88a06ba5-70e0-428b-911d-4738c25017f0)
![image](https://github.com/netbox-community/netbox/assets/33054826/d05eeb63-d31a-41c4-8f0a-d57403db6e5a)

2. Enter "IF[1,2,3,4]" and try to create "IF1,IF2,IF3,IF4".
![image](https://github.com/netbox-community/netbox/assets/33054826/d8ad6990-4e68-4f60-89d5-250489b89166)
3. Range "1" is invalid." is displayed and cannot be created.
![image](https://github.com/netbox-community/netbox/assets/33054826/70e6dc8e-45ab-42bb-812a-6c32c52354fb)

### Expected Behavior

We expect to be able to generate the specified number of combinations containing integer values.
For example, IF[1,3,5,8] would be expected to generate IF1, IF3, IF5, and IF8.

### Observed Behavior

Range {int} is invalid." is displayed and the data is not created together.

**Comment by pv2b** [comment]
Hello!

This appears to be a duplicate of https://github.com/netbox-community/netbox/issues/13722

There's a Pull Request under review to fix this, and if you're impatient, you could always try merging it into your own install: https://github.com/netbox-community/netbox/pull/13730

**Comment by penM000** [comment]
Thank you!
I could not notice.
Thanks for letting me know!
