### ISSUE TITLE
Reverse for 'platform-trace' not found. 'platform-trace' is not a valid view function or pattern name.

### ISSUE THREAD

**Issue by davekempe** [netbox-community/netbox#13933]
### NetBox version

v3.6.3

### Python version

3.11

### Steps to Reproduce

I built a fresh 3.6.3 from scratch for a demo I'm working on. I loaded the demo data from the netbox data site and get this error when clicking on cable trace:

Device -> Interface -> trace

```
<class 'django.urls.exceptions.NoReverseMatch'>

Reverse for 'platform-trace' not found. 'platform-trace' is not a valid view function or pattern name.

Python version: 3.11.2
NetBox version: 3.6.3
Plugins: None installed
```
https://mydemo-netbox/dcim/interfaces/1/trace/ throws this error.

https://demo.netbox.dev/dcim/interfaces/2/trace/ seems to work OK

### Expected Behavior

It displays the cable trace. 

### Observed Behavior

```
<class 'django.urls.exceptions.NoReverseMatch'>

Reverse for 'platform-trace' not found. 'platform-trace' is not a valid view function or pattern name.

Python version: 3.11.2
NetBox version: 3.6.3
Plugins: None installed
```

I have re-run upgrade.sh and it completed OK. 
I loaded the data by doing this:

```
./manage.py loaddata -v 3 --traceback /srv/netbox/netbox-demo-v3.6.json
Loading '/srv/netbox/netbox-demo-v3.6' fixtures...
Checking '/srv/netbox' for fixtures...
Installing json fixture 'netbox-demo-v3.6' from '/srv/netbox'.
Processed 6915 object(s).
Resetting sequences
Installed 6915 object(s) from 1 fixture(s)
```

I also get this error sometimes:
```
<class 'IndexError'>

list index out of range

Python version: 3.11.2
NetBox version: 3.6.3
Plugins: None installed
```

[upgrade.sh.output.txt](https://github.com/netbox-community/netbox/files/12754458/upgrade.sh.output.txt)

**Comment by arthanson** [comment]
This looks like an issue with the demo data, if you run the management command 'trace_paths --force" it works okay afterwards.

**Comment by jeremystretch** [comment]
Good catch @arthanson! I've added a warning to the [netbox-demo-data](https://github.com/netbox-community/netbox-demo-data) README noting this. Hopefully we can move the demo data from JSON to raw SQL dumps in the near future, which will sidestep this issue entirely.

Closing this out as no action is needed within NetBox itself.
