### ISSUE TITLE
Add filters by primary_ips to VirtualMachine, VirtualDeviceContext models

### ISSUE THREAD

**Issue by miaow2** [netbox-community/netbox#13936]
### NetBox version

v3.6.3

### Feature type

Change to existing functionality

### Proposed functionality

At this moment you can't filter virtual machines and virtual device contexts by `primary_ip4` and `primary_ip6` fields.

### Use case

At my job, we have a workaround when we need to find a virtual machine by primary IP address. Also, I've noticed that `VirtualDeviceContext` model does not have these filters.
It would be great to add this functionality, I can create PR with this feature.

### Database changes

No

### External dependencies

No

**Comment by abhi1693** [comment]
On both the models you have `has_primary_ip` filter which will provide a list of objects on the table. Could you specify in more details what exactly you are proposing to be changed?

**Comment by miaow2** [comment]
@abhi1693 I want to add the same functionality as on `DeviceFilterSet`, https://github.com/netbox-community/netbox/blob/develop/netbox/dcim/filtersets.py#L996 `primary_ip4_id` and `primary_ip6_id` attributes

For example, I have address 1.1.1.1/24 in NetBox, with `has_primary_ip` filter I will get all vms with primary_ips then iterate through them and find vm with primary_ip 1.1.1.1/24.
With db `id` of  1.1.1.1/24 I want to filter vms like this
`/api/virtualization/virtual-machines/?primary_ip4_id=xxxx`

**Comment by jeremystretch** [comment]
These filters were added to DeviceFilterSet under #11150 but for some reason not replicated for virtual machines.

**Comment by miaow2** [comment]
@jeremystretch you can assign this issue to me
