### ISSUE TITLE
Enable API filtering of foreign key properties by null value

### ISSUE THREAD

**Issue by decoupca** [netbox-community/netbox#13932]
### NetBox version

v3.6.3

### Feature type

New functionality

### Proposed functionality

Currently, properties of foreign key relationships can only be [filtered by negation](https://docs.netbox.dev/en/stable/reference/filtering/#foreign-keys-other-fields). As far as I can tell, there is no way to filter foreign key properties based on whether or not a value exists.

This FR would introduce the ability to filter foreign key properties by null value using boolean logic, exactly how numeric and string properties [can be filtered with the `empty` operator](https://docs.netbox.dev/en/stable/reference/filtering/#string-fields).

### Use case

Many use cases may benefit from looking up objects with properties that are currently null.

For example, I want to find a list of all interfaces that are connected. If this feature were implemented, I could construct a query like this: `/api/dcim/interfaces/?connected_endpoints__empty=false`

### Database changes

None

### External dependencies

None

**Comment by miaow2** [comment]
Hi @decoupca, you can filter foreign key properties based on whether or not a value exists

for example:
filter devices with assigned tenants
https://demo.netbox.dev/dcim/devices/?tenant_id__n=null

filter devices without tenants
https://demo.netbox.dev/dcim/devices/?tenant_id=null

**Comment by decoupca** [comment]
@miaow2 Correct. You can filter foreign key properties based on null value. I didn't use the right terms in the FR. The core issue I face is that I can't do the same for a property like `connected_endpoints`. I'm not sure what type of property `connected_endpoints` is, but it's not filterable by null value.

These don't work:
* `/api/dcim/interfaces/?connected_endpoints__n=null`
* `/api/dcim/interfaces/?connected_endpoints__empty=false`

**Comment by miaow2** [comment]
@decoupca you can't filter property `connected_endpoints` because there is no filter on this property

you can try 
`/api/dcim/interfaces/?cabled=true` or `/api/dcim/interfaces/?cabled=false`
or
`/api/dcim/interfaces/?connected=true` or `/api/dcim/interfaces/?cabled=false`

check swagger for filters https://demo.netbox.dev/api/schema/swagger-ui/#/dcim/dcim_interfaces_list
