### ISSUE TITLE
Render Custom Field Choices as label instead of value in UI

### ISSUE THREAD

**Issue by sleepinggenius2** [netbox-community/netbox#13950]
### NetBox version

v3.6.3

### Feature type

Change to existing functionality

### Proposed functionality

When using the new Custom Field Choices, you are able to set a value and a label for each choice. When editing an object with a custom field that uses a Choice Set that has different labels and values like that, the label is shown in the dropdown, but the value is shown in the object view and in the corresponding table column. My proposal is to use the label value for display purposes everywhere in the UI.

### Use case

This proposal would bring the Custom Field Choices functionality in line with the native choice fields in how they are rendered in the UI and would provide a cleaner experience to the end users. I feel that this is also in alignment with the original feature request #13241.

### Database changes

None

### External dependencies

None

**Comment by stavr666** [comment]
Against the idea.

Label - for UI. Value - for APIs. Imho. That's how we use it now: human readable representation of IDs and GUIDs.

**Comment by sleepinggenius2** [comment]
@stavr666 I'm really confused by your response. You say you're against the idea, but then you say label for UI and value for APIs, which is exactly what I've proposed.

**Comment by jeremystretch** [comment]
> My proposal is to use the label value for display purposes everywhere in the UI.

I agree with this. For example, if you have a choice with the value `00ff00` and the label `Green`, the user would expect to see the label. Prior to v3.6 this was not a concern because NetBox did not offer support for custom field choice labels.

**Comment by arthanson** [comment]
I will assign it to you @sleepinggenius2
