### ISSUE TITLE
Add dns_name filter on IP Addresses page

### ISSUE THREAD

**Issue by jacobw** [netbox-community/netbox#13957]
### NetBox version

v.3.6.3

### Feature type

Change to existing functionality

### Proposed functionality

It is currently possible to filter on dns_name on the IP Addresses page.

The proposed functionality is to add the ability to filter on the dns_name field.

### Use case

1: A user may want to determine how many IP Addresses have dns_names that wall within a particular sub domain. It is currently only possibly to do this by creating an export filter and using Jinja to filter, and Jinja has limited filtering capabilities.

2: A user may want to check if there are dns_name duplicates for a specific fqdn.

### Database changes

None

### External dependencies

None

**Comment by kprince28** [comment]
Can you please assign this issue to me ?
