### ISSUE TITLE
Feed Connection Error Not Handled

### ISSUE THREAD

**Issue by adhoniran** [netbox-community/netbox#13956]
### NetBox version

v3.6.3

### Python version

3.11

### Steps to Reproduce

1. Opening NetBox application while server don't have Internet connection or DNS resolution don't works.

### Expected Behavior

NetBox displaying a graceful notification on feed widget informing a getting feed problem

### Observed Behavior

NetBox is displaying a unhandled notification

**Comment by adhoniran** [comment]
Hi,
Thanks for your feedback.

It's in the main page, before login included...
I just attached some screenshots:

[image: Captura de tela 2023-10-03 140032.png]


[image: Captura de tela 2023-10-03 135812.png]


Best Regards


Em ter., 3 de out. de 2023 às 12:56, Jeremy Stretch <
***@***.***> escreveu:

**Comment by jeremystretch** [comment]
@adhoniran I'm afraid the screenshots aren't showing. Could you try to upload them via GitHub's web interface?

**Comment by adhoniran** [comment]
Files added again...


![feed-conf](https://github.com/netbox-community/netbox/assets/13842906/4be06ad0-15e4-439f-8a28-2cfe425c5a75)


![feed-error](https://github.com/netbox-community/netbox/assets/13842906/fea3be11-bbb5-40ff-b81d-78830146487a)

**Comment by jeremystretch** [comment]
I've reclassified this as a feature request, as upon further consideration I don't believe the error message can be considered as a bug. The exception is not unhandled as the original issue suggests; rather the error message is simply presented in its raw form to the user.

**Comment by adhoniran** [comment]
I agree about the feature request classification, I can treat the main error reasons and write a code proposal.
