### ISSUE TITLE
Hide Tokens in 'API Tokens' list

### ISSUE THREAD

**Issue by PieterL75** [netbox-community/netbox#13965]
### NetBox version

v3.6.3

### Feature type

Change to existing functionality

### Proposed functionality

When opening the 'API Tokens' list, all tokens are fully displayed.
These should be either 'starred', 'shortened (first2/last4)' or not shown at all.
The key can still be retrieved when opening the token itself

### Use case

Showing all keys at once is a security concern. It will raise a redflag by our SOC when this is seen.

**Comment by arthanson** [comment]
This has already been implemented - You can toggle ALLOW_TOKEN_RETRIEVAL config param to change this, see: https://docs.netbox.dev/en/stable/configuration/security/#allow_token_retrieval.
