### ISSUE TITLE
Add a copy-to-clipboard button to the API token creation form

### ISSUE THREAD

**Issue by jeremystretch** [netbox-community/netbox#13962]
### NetBox version

v3.6.3

### Feature type

New functionality

### Proposed functionality

On the API token creation form, add a button to conveniently copy the randomly-generated API token value to the system clipboard.

![API token creation form](https://github.com/netbox-community/netbox/assets/13487278/b8ffa826-c713-4f5b-8ca4-56309e68d215)

### Use case

Convenience

**Comment by jsenecal** [comment]
Isn't that already supported by  [netbox/templates/account/token.html#L20](https://github.com/netbox-community/netbox/blob/v3.6.3/netbox/templates/account/token.html#L20) and [netbox/templates/account/token.html#L32]( https://github.com/netbox-community/netbox/blob/v3.6.3/netbox/templates/account/token.html#L32) -> [copy_content.html](https://github.com/netbox-community/netbox/blob/v3.6.3/netbox/utilities/templates/builtins/copy_content.html) ?
