### ISSUE TITLE
Support for webproxy

### ISSUE THREAD

**Issue by maekee** [netbox-community/netbox#13971]
### NetBox version

v3.6.3

### Feature type

New functionality

### Proposed functionality

Do not know if this is something that actually works or is in need of feature.
We are using netbox behind a web proxy (web security gateway) and in v3.6.3 the dashboard says:

 _There was a problem fetching the RSS feed: HTTPConnectionPool(host='netbox.dev', port=80): Max retries exceeded with url: /rss/ (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f284c247400>: Failed to resolve 'netbox.dev' ([Errno -3] Temporary failure in name resolution)"))_

We do not allow direct access to internet or DNS lookups for internal clients, they need to go through the webproxy.
So if i could configure a proxyserver, proxy port that would help the request to be redirected there instead of directly.

### Use case

Companys that use a explicit web proxy before accessing internet

**Comment by jeremystretch** [comment]
Yep, this is already supported in NetBox. You can set the [`HTTP_PROXIES`](https://docs.netbox.dev/en/stable/configuration/system/#http_proxies) configuration parameter to specify the HTTP(S) proxies to use.

**Comment by maekee** [comment]
Great, worked fine. Thanks alot.
