### ISSUE TITLE
Separate Address Fields for Site

### ISSUE THREAD

**Issue by i3D-RyanHamel** [netbox-community/netbox#13973]
### NetBox version

3.3.10

### Feature type

Data model extension

### Proposed functionality

Add separate fields for country, country + province/state, city, and postal/zip code. 

### Use case

For issue #9617, how about using [RFC8805](https://datatracker.ietf.org/doc/html/rfc8805) as the reason to have specific fields for the country, country + province/state, city, and postal/zip code. Geofeeds are important when it comes to having geo IP database vendors like MaxMind poll in data changes on a periodic basis.

**Comment by jsenecal** [comment]
I am totally in support for this improvement. I had to rely on using google places ID in a customfield to be able to reliably store address information in a reliable form. 

An alternative would be to write address in yaml ? But then end users could mess up the format and we end up with parsing errors... Unless using custom validators?... Down goes the rabbit hole 😄

**Comment by Cormoran96** [comment]
Someone create an alternative to do this:

https://github.com/FrumentumNL/GeoBox
