### ISSUE TITLE
Custom Fields: showing value instead of label

### ISSUE THREAD

**Issue by jayGG83** [netbox-community/netbox#13988]
### NetBox version

v3.6.3

### Python version

3.10

### Steps to Reproduce

1. Create a Custom Field Choice:
![image](https://github.com/netbox-community/netbox/assets/132988868/55bdd0da-7253-416f-a94e-41b32ce7ed4f)
2. Create a Custom Field for that choice (this was created to be visible for Device, Interface and Module type)
![image](https://github.com/netbox-community/netbox/assets/132988868/8bc50d6e-f090-49b8-bb9e-0a63d28f0fc0)
3. Create/Edit a Device/Interface/Module Type with this custom field
![image](https://github.com/netbox-community/netbox/assets/132988868/629338aa-1238-4982-a493-f7de2ba6c22e)

### Expected Behavior

The expected behaviour is to show the Label (Alpha) and not the Value (A)

### Observed Behavior

UI shows the custom field value instead of the label. Label only shows in the drolist options (Edit UI). Also tested in other objects with identical behaviour

**Comment by jeremystretch** [comment]
This change was actually just implemented under #13950 and will be included in the upcoming v3.6.4 release.
