### ISSUE TITLE
Export CSV should be able to import with requiring modification

### ISSUE THREAD

**Issue by dionrowney** [netbox-community/netbox#13985]
### NetBox version

v3.6.1

### Python version

3.9

### Steps to Reproduce

- Select Manufacters (or any other list view that only has CSV export)
- Select Export CSV
- Delete all Manufacturers
- Select Import CSV
- Data import fails with variety of errors relating to field names and field values

### Expected Behavior

What is exported should be able to be imported without ANY modification to the file of data

### Observed Behavior

It would error out and the following items had to be fixed in the text content of the csv file:
- header displayed Label version of field name not the required field name
- values with choices like "active" were "Active" with uppercase A and had to have the value changed to choice value not label value.  And there was no way to export to determine what the correct value needed to be.  so you could not export it, get the correct value for some selection.

**Comment by jeremystretch** [comment]
This has been discussed numerous times previously. Please use the search function before submitting new issues.
