### ISSUE TITLE
Custom Field Choice Set Bulk Import error "Nested arrays must have same length"

### ISSUE THREAD

**Issue by jayGG83** [netbox-community/netbox#13983]
### NetBox version

v3.6.3

### Python version

3.10

### Steps to Reproduce

1. Select Custom Field Choices import
2. Data to import:

CSV:
```
name;description;extra_choices
numbers;Numbers;7,13,18,23,26,32,38,80
```

JSON:
```
{
    "name": "numbers",
    "description": "Numbers",
    "extra_choices": [7,13,18,23,26,32,38,80]
}
```

YAML:
```
---
name: numbers
description: Numbers
extra_choices: 7,13,18,23,26,32,38,80
```

3. Click Submit

### Expected Behavior

It is expected to create the cusotm field choices

### Observed Behavior

Returns this error in all cases: Record 1 extra_choices: Nested arrays must have the same length.

**Comment by jeremystretch** [comment]
The root issue here is that each choice value is being interpreted as an array, such that e.g. `13` becomes `["1", "3"]`. The error message is a bit of a red herring, and presents only if all the choice values are not of the same length. For example, importing a field value of `A1,B2,C3` will result in choices `[(A, 1), (B, 2), (C, 3)]`.

I'm not sure we have a great option for handling nested arrays in CSV data, but we should seek to support them when expressed via JSON/YAML.

**Comment by sleepinggenius2** [comment]
I ran into a similar requirement recently in a plugin I was working on and defining the field like below on the `*ImportForm` class has worked great for CSV data. Admittedly, I have not tried importing JSON or YAML.

```python
field = SimpleArrayField(
    base_field=SimpleArrayField(
        base_field=CharField(),
        min_length=2,
        max_length=2,
    ),
    delimiter=';',
    required=False,
    help_text=_('Semicolon-separated list of comma-separated pairs, encased with double quotes (e.g. "value1,Label 1;value2,Label 2")'),
)
```

**Comment by arthanson** [comment]
We could potentially have a "CSV string delimiter" along with the "CSV delimiter" with a none option default.  If set to semicolon then it could parse string arrays based on it.  But this might be overly-complicated and would need to be made clear in the UI.

There would have to be some validation that the two delimiter fields are not set to the same value.
