### ISSUE TITLE
No TAGs when webhook is used to create new device

### ISSUE THREAD

**Issue by hrleinonen** [netbox-community/netbox#13981]
### NetBox version

v3.6.3

### Python version

3.8

### Steps to Reproduce

Hi,

I tried to create webhook automation and it seems that when I create new host there is no TAGs in webhook.

Here is snip in webhook output:

      "description":"",
      "comments":"",
      "config_template":"None",
      "local_context_data":"None",
      "tags":[
         
      ],
      "custom_fields":{
         
      },
      "created":"2023-10-05T14:03:52.577257Z",
      "last_updated":"2023-10-05T14:03:52.577283Z",
      "console_port_count":0,

I test webhook in version v3.3.4 also and there is TAGs in webhook

### Expected Behavior

'custom_fields': {}, 'tags': ['Testing tags']}

### Observed Behavior

No TAGs in webhook.

**Comment by jeremystretch** [comment]
Thank you for opening a bug report. Unfortunately, the information you have provided is not sufficient for someone else to attempt to reproduce the reported behavior. Remember, each bug report must include detailed steps that someone else can follow on a clean, empty NetBox installation to reproduce the exact problem you're experiencing. These instructions should include the creation of any involved objects, any configuration changes, and complete accounting of the actions being taken. Also be sure that your report does not reference data on the public NetBox demo, as that is subject to change at any time by an outside party and cannot be relied upon for bug reports.

**Comment by hrleinonen** [comment]
Reinstallation resolved the problem.
