### ISSUE TITLE
Server Error by Syntax Error in custom scripts

### ISSUE THREAD

**Issue by JonasEinfach** [netbox-community/netbox#13990]
### NetBox version

3.5.0

### Python version

3.11

### Steps to Reproduce

1. Create Custom Script with a Syntax Error
2. Add Script

--> Than I get a Server Error

### Expected Behavior

It's not possible to remove the scripts. If you want to access the script part on the netbox I got an Server Error. If one script have an syntax error you can't access any script.

### Observed Behavior

There was a problem with your request. Please contact an administrator.

<class 'SyntaxError'>

expression cannot contain assignment, perhaps you meant "=="? (test.py, line 72)

Python version: 3.11.1
NetBox version: 3.5.0

**Comment by jeremystretch** [comment]
Your NetBox version is out of date. Please upgrade to the current stable release (v3.6.3) and see if this is still an issue.

**Comment by jeremystretch** [comment]
This issue is being closed as no further information has been provided. If you would like to revisit this topic, please first modify your original post to include all the requested detail, and then ask that the issue be reopened.
