### ISSUE TITLE
Add  "IEC 60130-10" (DC) to power port types

### ISSUE THREAD

**Issue by ZPrimed** [netbox-community/netbox#14010]
### NetBox version

v3.6.3

### Feature type

Data model extension

### Proposed functionality

The existing model for "power ports" includes a very large amount of AC-type ports, but not much in the way of DC power.
It would be nice to have better documentation about what specific type of connector(s) a device has.

I would like to propose these additions:
* Barrel connector (ideally, a list of various ID & ODs for the barrel would be nice, but this gets to be a mess very quickly - there is currently not even a generic "barrel plug" option and I'd be happy with that)
* Bolt-through terminal (is this what "hardwired" under "Other" is meant to be? or is hardwired actually intended for a "permanent, requires electrician" connection?)
* [Screw-down wire-clamp terminal](https://mou.sr/45Q6xC9) 
* [Removable Terminal Block connector](https://mou.sr/3ZMNMye) (there are a slew of these as well, I guess technically "DC Terminal" would cover this as a generic, but documenting at least some of the more common connector types would be "better")

### Use case

Attempting to correctly model real-world equipment requires the port types to be defined. 😉 

### Database changes

(no db changes expected?)

**Comment by jeffgdotorg** [comment]
@ZPrimed this issue is at risk of being auto-closed, and I think it would be a shame if that happened, so I'm using my privilege to give it a bump and asking for a little more detail in the form of a list of specific connector type enum IDs, descriptive names, and slug names that you propose to add. You might refer to PR #8415 to get an idea of what we're looking for.

**Comment by ZPrimed** [comment]
Well, at a bare minimum, the [IEC 60130-10 standard coaxial/barrel connectors](https://en.wikipedia.org/wiki/Coaxial_power_connector#IEC_60130-10) should probably be included as sub-types of "DC":

Coaxial Barrel - IEC 60130-10 
- Type A1: 5.5 mm OD, 2.1 mm ID (with optional screw lock)
- Type A2: 5.5 mm OD, 2.5 mm ID (with optional screw lock)  [yes, there are two *different* "Type A" standards 🙄 ]
- Type B1: 6.0 mm OD, 2.1 mm ID
- Type B2: 6.0 mm OD, 2.5 mm ID  [and also two different "Type B" standards 🙄 ]
- Type C: 3.8 mm OD, 1.1 mm ID
- Type D: 6.3 mm OD, 3.1 mm ID
- Type E: 3.4 mm OD, 1.3 mm ID

A generic "Other Barrel Plug" would probably be a useful catch-all as well...

A design question:
The current power connector list never seems to go below one "level". 
Would there be any objection to having a "sub-heading" below "DC" of "Coaxial Barrel - IEC 60130-10" and then listing out the individual "types" below that sub-heading?

Additionally, is it "redundant" to include "DC" as part of the description for the connector, since that is already included in the heading above it?

**Comment by arthanson** [comment]
Note: This would be an addition to dcim.choices.PowerPortTypeChoices

**Comment by arthanson** [comment]
@ZPrimed can you please look at PR #16206 see if that would address your request?

**Comment by ZPrimed** [comment]
Looks great to me. A couple of those do have a positive-retention (screw-down) variant, wasn't sure if those should be included as well? IMO it's always useful to know if a connector is capable of "locking"...

**Comment by arthanson** [comment]
@ZPrimed do you know the other side (female) of these connectors?  We need both sides to be added for these, taking a Quick Look at the specs I didn't see these defined.

**Comment by ZPrimed** [comment]
> @ZPrimed do you know the other side (female) of these connectors? We need both sides to be added for these, taking a Quick Look at the specs I didn't see these defined.

@arthanson I've never heard of anything beyond simply "male" and "female" for these plugs & jacks. They get described by the ID/OD and inner pin size.

**Comment by eronlloyd** [comment]
I don't have the specs handy, but [this article](https://www.instructables.com/Reusing-Wall-Warts/) seems to reference quite a few based on the IEC 60130-10:1971, EIAJ (Japan), and DIN (Germany).
