### ISSUE TITLE
Backup and Restore

### ISSUE THREAD

**Issue by RenatoPereira91** [netbox-community/netbox#14016]
### NetBox version

v3.6.3

### Feature type

New functionality

### Proposed functionality

Via GUI a way to config external backup and restore, generate the backup and send to other server, if will get the server problem we can restore via GUI.

### Use case

Easy restore of NETBOX if get crash of server

**Comment by DanSheps** [comment]
Thank you for submitting your idea. Unfortunately, the proposed feature falls outside the scope of functionality that NetBox aims to provide. As NetBox is an open source application with limited development resources and a persistent backlog of existing work, it is crucial that we limit the scope of development to ensure it remains a maintainable project for many years to come. Thank you for your understanding.
