### ISSUE TITLE
Error when deleting multiple cables

### ISSUE THREAD

**Issue by penM000** [netbox-community/netbox#14023]
### NetBox version

v3.6.3

### Python version

3.8

### Steps to Reproduce

1. Registers wiring that would result in an L2 loop to the same device.
2. Select these two to delete the cable.
3. An error occurs and the cable is not deleted.
![image](https://github.com/netbox-community/netbox/assets/33054826/e464e8c4-2b38-46b8-a8b9-120a61a0fb97)
![image](https://github.com/netbox-community/netbox/assets/33054826/77b4e264-0a1a-4ce4-9a6e-4cd1ec1927bd)
![image](https://github.com/netbox-community/netbox/assets/33054826/cd4d62dd-e00a-475b-8ec7-86d73d195b9c)
![image](https://github.com/netbox-community/netbox/assets/33054826/3d48fbc0-a980-46b3-84a1-836a856be860)

### Expected Behavior

Expect the cable to be removed.

### Observed Behavior

The error shown in the image has been identified.

**Comment by DanSheps** [comment]
This same issue is also present (or at least was) when deleting duplex cables to a different device.

The solution is to get the cables and build a unique set.

**Comment by jeremystretch** [comment]
This issue was originally titled "Error when deleting multiple wires." In the future, please be careful to use accurate terminology when filing issues, both to prevent confusion and to ensure your issue appears in relevant searches.
