### ISSUE TITLE
Permission tenancy

### ISSUE THREAD

**Issue by venomnom** [netbox-community/netbox#14032]
### NetBox version

v3.6.2

### Feature type

Change to existing functionality

### Proposed functionality

A new field for permissions where it is possible (not forced) to add tenants or tenant groups, where this permission should be granted. 
If no tenant is added, it is enabled globally, if one or more are added, the permissions are only granted for devices within these tenants or tenant groups.

This is currently very hard to impossible with constraints as many objects do not posses a field for a tenant. For every one of these it would be needed to create a new permission with the specific constraint to find the tenant, which is a big waste of time and the count of needed permissions.

### Use case

At my workplace we are planning to roll NetBox out to all our other locations and with the current permission model it is next to impossible to create a proper access control where NetBox users are only allowed to access the objects from their location and not others. To create a reliable source of truth, from our point of view it is necessary to restrict write permissions to ones own location only for most colleagues.

With this in place, it would also be possible for housing service providers, to have a NetBox instance to be shared with their customers where everyone has his own tenant and can only manage, see and create devices within his own tenant.

### Database changes

Added field for nullable foreign keys for tenants in users_objectpermission table

**Comment by jeremystretch** [comment]
You may be misunderstanding how permissions are applied: There is no relationship between tenant objects and NetBox users or groups. You can accomplish what you want to do using groups. Please consider starting a [discussion](https://github.com/netbox-community/netbox/discussions/new/choose) if you'd like assistance with this.
