### ISSUE TITLE
Job result not visible when running a script via the call command

### ISSUE THREAD

**Issue by kprince28** [netbox-community/netbox#14053]
### NetBox version

v3.5.9

### Python version

3.10

### Steps to Reproduce

1. Navigate to the NetBox application.
2. Access the script execution section.
3. Select a script to execute using the call command.
4. Observe the job that is created after executing the script.

### Expected Behavior

1. The job should display the result of the executed script.
2. The job should be named after the class name of the script.
3. The job badges in the script view of the jobs tab should show the accurate number of jobs created for each script.

### Observed Behavior

1. The job does not show any result of the executed script.
2. The job is named after the script itself rather than the class name.
3. The job badges in the script view of the jobs tab show the total number of scripts but do not reflect the actual number of jobs created.

**Comment by jeremystretch** [comment]
Thank you for opening a bug report. Unfortunately, the information you have provided is not sufficient for someone else to attempt to reproduce the reported behavior. Remember, each bug report must include detailed steps that someone else can follow on a clean, empty NetBox installation to reproduce the exact problem you're experiencing. These instructions should include the creation of any involved objects, any configuration changes, and complete accounting of the actions being taken. Also be sure that your report does not reference data on the public NetBox demo, as that is subject to change at any time by an outside party and cannot be relied upon for bug reports.
