### ISSUE TITLE
Device Platform selection is not limited by Manufacturer

### ISSUE THREAD

**Issue by sleepinggenius2** [netbox-community/netbox#14058]
### NetBox version

v3.6.3

### Python version

3.8

##### Device

1. Click on "Devices" > "Add"
2. Select a "Device type" under the "Hardware" section
3. Click on the "Platform" dropdown under the "Management" section
4. The list includes all Platform values

##### Device Type

1. Click on "Device Types" > "Add"
2. Select a "Manufacturer" under the "Device Type" section
3. Click on the "Default platform" dropdown under the "Device Type" section
4. The list includes all Platform values

### Expected Behavior

The available list of platforms should be limited by the selected manufacturer.

### Observed Behavior

All Platform objects are available for selection.

It looks like when #11952 was implemented it caused a regression in how this worked for Devices, as the Manufacturer was previously filtered on in the UI. There is still a check in place on the `Device.clean` method to perform this validation, so it seems to just be a UI bug for Devices at this time.

For Device Types, it does not appear that filtering or validation were ever added for the `default_platform` field.

**Comment by sleepinggenius2** [comment]
Yes, the filter previously included platforms with no manufacturer set. I would just like to have pre-3.5 functionality restored in the UI for devices at a minimum. The Device Type functionality would actually be easier to implement, as it still has the Manufacturer field, it just looks like it was never implemented when the default_platform field was added. From a UX standpoint, if I have a Cisco device, I should see IOS, but not Junos listed, and I might still have something like Linux listed (no manufacturer set). This is how it worked in 3.4, before we lost the Manufacturer field, when it was incorporated into the object selector for the Device Type.

**Comment by Katharta** [comment]
Agree with cpmills1975... I would like to notate the manufacturer for server OSes for inventory purposes, but locking the available device types to said manufacturer ideally should be a separate option or checkbox.
