### ISSUE TITLE
No 'Pre-Change Data' when updating interface via CSV import

### ISSUE THREAD

**Issue by mlazzarotto** [netbox-community/netbox#14056]
### NetBox version

v3.6.3

### Python version

3.8

### Steps to Reproduce

1. Accidentally change names on a dozen of interfaces using a CSV import
2. Check the changelog
3. See **None** as **Pre-Change Data**

### Expected Behavior

**Pre-Change Data** should list the fields before the change.
**Difference** should show the difference

### Observed Behavior

![image](https://github.com/netbox-community/netbox/assets/8932945/ca16c839-c1f9-4424-89bd-7822266d4dd8)

**Comment by jeremystretch** [comment]
I believe this would be resolved by FR #14059.
