### ISSUE TITLE
POST api/virtualization/clusters. Can't use name as cluster type.

### ISSUE THREAD

**Issue by JaedanC** [netbox-community/netbox#14066]
### NetBox version

v3.6.5-dev

### Python version

3.11

### Steps to Reproduce

1. Create a Cluster Type (any name & slug). eg: "My Type" and "my-type"
2. Use the API to try to create a Cluster using that Cluster Type:

`POST /api/virtualization/clusters/`
```json
{
    "name": "My VM",
    "type": "My Type",
    "status": "active"
}
```

The VM will not be created. If you use that exact JSON inside the Cluster "import" in the NetBox gui, the insert will work. Only the API does not. The API only works if you use the Cluster Type's `id`.

`POST /api/virtualization/clusters/`
```json
{
    "name": "My VM",
    "type": 5,
    "status": "active"
}
```

### Expected Behavior

You should be able to use the Cluster Type's `name` (or `slug`) in the API just like how the import Cluster feature works. There is an inconsistency here.

### Observed Behavior

An error code of 400 is returned which means the API request is invalid.

**Comment by JaedanC** [comment]
I have also observed not being able to create/update a cluster assigned to a site by using the site's slug. I must use the site's id as well.

**Comment by jeremystretch** [comment]
This is not a valid format for REST API data. Please consult the documentation for [referencing related objects](https://docs.netbox.dev/en/stable/integrations/rest-api/#related-objects) for examples of the supported formats.

**Comment by JaedanC** [comment]
According to the documentation:

> When performing write API actions (POST, PUT, and PATCH), related objects may be specified by either numeric ID (primary key), or by a set of attributes sufficiently unique to return the desired object.

With this information, this should be a valid payload for the API. 

```json
{
    "name": "My VM",
    "type": {"slug", "my-type"},
    "status": "active"
}
```

The Cluster-type **is uniquely identified** by the slug by definition. But this also does not work. I do not believe this issue should be closed.
