### ISSUE TITLE
Bulk Import of Custom Field Choice Set fails

### ISSUE THREAD

**Issue by marehler** [netbox-community/netbox#14073]
### NetBox version

v3.6.2

### Python version

3.11

### Steps to Reproduce

1. Navigate to Customization -> Custom Fields -> Custom Field Choices
2. Click Import 
3. Paste sample data:
````
name,extra_choices
test_set,"enabled,disabled"
````
4. Click Submit

### Expected Behavior

The custom field choice set is added.

### Observed Behavior

An error occurs: "Record 1 extra_choices: Nested arrays must have the same length."

**Comment by jeremystretch** [comment]
Thank you for submitting this issue, however it appears that this topic has already been raised. Please see issue #13983 for further discussion.
