### ISSUE TITLE
config context not applied on devices when using tag filter on cluster object

### ISSUE THREAD

**Issue by soofff** [netbox-community/netbox#14083]
### NetBox version

v3.5.8

### Python version

3.8

### Steps to Reproduce

1. create cluster and (create+) assign hosts
2. create/assign tag to cluster e.g. `TAG1`
3. create config context and assign `TAG1`

### Expected Behavior

i would expect that the config context is assigned to all devices where the cluster(s) have the assigned tag.
when i use cluster assignment instead of tags, everything works as expected.

### Observed Behavior

no config context is rendered/shown on the device which are a part of the tagged cluster.

**Comment by jeremystretch** [comment]
Config contexts consider only tags which are assigned directly to a device or virtual machine. They intentionally don't consider tags which are applied to the cluster in which a VM is assigned, as that could be very difficult to manage at scale.

Instead, you can either apply the tags directly to the desired VM, or associate the config context with the appropriate cluster(s). Hope that helps!
