### ISSUE TITLE
French translation

### ISSUE THREAD

**Issue by jsenecal** [netbox-community/netbox#14096]
### Language

French

### ISO 639-1 code

fr

### Volunteer

Yes

**Comment by jeremystretch** [comment]
Marking this as blocked by #14075 for now. Will open it back up once we've gotten the base translation strings cleaned up (see #14111 and undoubtedly others that will be opened).

**Comment by jeremystretch** [comment]
This is blocked by #14141

**Comment by MartinMDS** [comment]
Thinks, it's not working on my 3.7.0 installation.
Is it a work in progress task ?
And same for Spanish and Portuguese, for what i saw. 
Do you need help for translation ?
Thanks

**Comment by thefreakquency** [comment]
It's not working for me either. I tried in private mode and tested also on the demo site. Results were the same. I will open a new GH issue for that.

**Comment by thefreakquency** [comment]
@MartinMDS see https://github.com/netbox-community/netbox/issues/14708
