### ISSUE TITLE
VirtualMachine created by the provided "create_vm.py" script does not show correct interface count

### ISSUE THREAD

**Issue by derdeagle** [netbox-community/netbox#14090]
### NetBox version

v.3.6.4

### Python version

3.11

### Steps to Reproduce

1. Download the [provided customizations script](https://github.com/netbox-community/customizations/blob/master/scripts/create_vm.py)
2. Add the script to Netbox
3. Fill in the required fields to create a VM
4. Open the created VM
5. Observe the "Interfaces" tab of the VM

### Expected Behavior

I expect to see a "1" in the "Interfaces" tab button as there is one interface for the VM.

### Observed Behavior

There is no number shown in the "Interfaces" tab button.
When adding an interface manually via the frontend there is a "1" shown even though there are two interfaces then. Upon deleting this manually created interface there is again no number shown in the "Interfaces" tab button.

**Comment by jsenecal** [comment]
Wouldn't this be better suited for [the `netbox-community/customizations` issue tracker](https://github.com/netbox-community/customizations/issues)?

**Comment by derdeagle** [comment]
I cannot tell if the script is doing something wrong or not. I can at least imagine it being more of an internal Netbox / Django problem. What else should I be supposed to than creating the VM and assigning the interface to it? The interface itself is there, just the counting in the webui is misleading / wrong.

To be frank I found this script after I wrote my own one and noticing this bug - I thought I did something wrong so I searched for examples. Then I tried this provided script and it showed the same result.

**Comment by derdeagle** [comment]
I thought some screenshots of examples could be of help.

**How it _should_ look like** (VM with a manually created interface)

![screenshot_2023-10-25_09-54-43](https://github.com/netbox-community/netbox/assets/11424540/6e27204e-fc94-43b2-ad8a-ef689ec9a1d1)

**How it actually looks like** (VM with the interface created via script)

![screenshot_2023-10-25_09-43-23](https://github.com/netbox-community/netbox/assets/11424540/036574fd-b439-4619-b52a-3911876c709c)

**Comment by kkthxbye-code** [comment]
https://github.com/netbox-community/customizations/blob/69882088da5214529328c04057e4aba1580bc25e/scripts/create_vm.py#L100

Insert before the above line:

`vm.refresh_from_db()`

Netbox 3.6 added cached counters: https://github.com/netbox-community/netbox/issues/6347

While the implementation of those are pretty half-baked imo (there's multiple issues currently breaking it), the reason it breaks here is that saving the vm again after the first save, overwrites whatever changes are done in signal handlers, which is where the  cached counters are handled.

**Comment by kkthxbye-code** [comment]
@derdeagle - Calling snapshot on an object saves the pre-change snapshot used for changelogs. If it is not called, the `Pre-Change Data` will be empty when viewing an objectchange.

**Comment by derdeagle** [comment]
@kkthxbye-code Thanks a lot. As I don't see a bug in Netbox here I will just close this issue. Again, thanks all.
