### ISSUE TITLE
Add VARP as IP Role

### ISSUE THREAD

**Issue by PieterL75** [netbox-community/netbox#14102]
### NetBox version

v3.6.4

### Feature type

Data model extension

### Proposed functionality

Add 'VARP' as an IP Role

https://www.arista.com/en/um-eos/eos-vrrp-and-varp

### Use case

Arista EVPN uses 'VARP' ips for VXLAN gateways

Virtual VRRP (VARP) allows multiple switches to simultaneously route packets from a common IP address in an active-active router configuration. Each switch is configured with the same set of virtual IP addresses on corresponding VLAN interfaces and a common virtual MAC address.

**Comment by jsenecal** [comment]
Maybe adding this field to [`field_choices`](https://docs.netbox.dev/en/stable/configuration/data-validation/#field_choices) would make sense here.
