### ISSUE TITLE
If you create a port in Alphanumeric ranges with not enough Rear ports, a server error will be displayed.

### ISSUE THREAD

**Issue by penM000** [netbox-community/netbox#14117]
### NetBox version

v3.6.4

### Python version

3.8

### Steps to Reproduce

1. Create a rear port, with position 1.
2. When creating a front port, use Alphanumeric ranges to create a front port that is greater than or equal to the rear port.
3. Server error is confirmed.
![image](https://github.com/netbox-community/netbox/assets/33054826/f815c224-9558-4870-9968-8013d34da3d8)
![image](https://github.com/netbox-community/netbox/assets/33054826/88cc2b6a-4a52-4d04-9555-a13ee1a032bc)

### Expected Behavior

Expect that the creation process will not take place. If no rear port is selected, no creations can be made.

### Observed Behavior

The create process could be performed with no available rear ports.

**Comment by DanSheps** [comment]
> 3. Server error is confirmed.

To be clear, you would like a proper error to be displayed, not the generic Django error, correct? 

> The create process could be performed with no available rear ports.

It dooesn't actually create anything, it generates an erro, this is expected.

**Comment by penM000** [comment]
> To be clear, you would like a proper error to be displayed, not the generic Django error, correct?
Yes, I thought this error was not appropriate and reported it.
