### ISSUE TITLE
Inventory Item view - show child objects on parent

### ISSUE THREAD

**Issue by ITJamie** [netbox-community/netbox#14112]
### NetBox version

v3.6.4

### Feature type

Change to existing functionality

### Proposed functionality

when viewing an inventory item there should be a table listing child objects of that inventory item

### Use case

when documenting inventory items (eg ssd's, in a raid controller) it would be great if the child items showed in a list when viewing the parent inventory item.

**Comment by DanSheps** [comment]
This should be fairly trivial to do, we simply need to add a new ObjectChildrenView that filters on the parent.
