### ISSUE TITLE
Remove static labels from filters in filtersets

### ISSUE THREAD

**Issue by jeremystretch** [netbox-community/netbox#14111]
### Proposed Changes

Remove the static `label` parameter passed to filters where they do not convey meaningful context. For example:

```python
class SomeFilterSet(NetBoxModelFilterSet):
    site_id = django_filters.ModelMultipleChoiceFilter(
        queryset=Site.objects.all(),
        label=_('Site (ID)'),
    )
    site = django_filters.ModelMultipleChoiceFilter(
        field_name='site__slug',
        queryset=Site.objects.all(),
        to_field_name='slug',
        label=_('Site (slug)'),
    )
```

The `Site (ID)` and `Site (slug)` labels would be removed. Any filter labels which go beyond echoing the name of the filter itself to provide genuinely useful context can be retained.

As an alternative to dropping such labels outright, we could instead simplify them by omitting the ID or slug suffix, which would obviate the need for additional string translations.

### Justification

Removing these extra labels greatly reduces the number of strings which must be translated, without significantly detracting from the API schema definitions. These labels add little value:

![Screenshot 2023-10-24 at 16-15-27 NetBox REST API](https://github.com/netbox-community/netbox/assets/13487278/97b274a1-1ded-4e34-a8c5-5301cd1b9e60)

**Comment by jeffgdotorg** [comment]
@jeremystretch do we want to let this one get auto-closed just as we're starting to get uptake on some new translations?

**Comment by jeremystretch** [comment]
I'll close it out for now. We might revisit the idea during future work on filters.
