### ISSUE TITLE
Update plugin development documentation for pyproject.toml

### ISSUE THREAD

**Issue by arthanson** [netbox-community/netbox#14121]
### Change Type

Addition

### Area

Plugins

### Proposed Changes

https://docs.netbox.dev/en/stable/plugins/development/ Specifically "Development Installation" section covers using setup.py, but pyproject.toml is the new suggested format and the documentation can include a line to use 

```
pip install -e ./
```

**Comment by jeremystretch** [comment]
@arthanson can I assign this to you?
