### ISSUE TITLE
Name expansion doesn't allow for comma separated values

### ISSUE THREAD

**Issue by kr3ator** [netbox-community/netbox#14139]
### NetBox version

v3.6.4

### Python version

3.8

### Steps to Reproduce

1. For an existing device or a device template click _Add components --> Interface_
2. Set type to _Virtual_ and in the Name field enter: Eth[0,4,2-3]
3. Click Create

### Expected Behavior

Four new virtual interfaces should be created: Eth0, Eth4, Eth2, Eth3.

### Observed Behavior

A template validation error is thrown: "Range '0' is invalid."

This bug was introduced by [this commit](https://github.com/netbox-community/netbox/pull/13326/commits/9972ed7cfa86a6771261f9b60cc4913f711f6788)

**Comment by jeremystretch** [comment]
Thank you for submitting this issue, however it appears that this topic has already been raised. Please see issue #13722 for further discussion.
