### ISSUE TITLE
An API method to get Contacts and/or Contacts Group for a Site Group (or Site)?

### ISSUE THREAD

**Issue by lamoni** [netbox-community/netbox#14133]
### NetBox version

v3.2.6

### Feature type

Data model extension

### Proposed functionality

Given a specific site name, I'm trying to use the API (pynetbox, specifically) to get to the site's site-group's contacts. I know we're running a bit older version but the swagger docs for the newest version didn't have the output either mentioned in the response example, but apologies anyway if this is in a newer version.

Example:

Site: ABC123
Site Group: ABCs
Contacts: abc-member@abc.com (which are also in a Contacts Group called ABC Staff)

If I start out with a site name and try to follow the API breadcrumbs (Ideally I could go: /dcim/sites -> /dcim/site-groups -> /tenancy/contacts), it goes cold at Site Group -> Contacts because the /site-groups GET output doesn't contain anything about its contacts or contact groups that are associated with it. 

Example of the /dcim/site-groups output:

`
{'_depth': 0,
 'created': '2023-10-27T18:01:32.758424Z',
 'custom_fields': {},
 'description': '',
 'display': 'ABCs,
 'id': 10,
 'last_updated': '2023-10-27T18:12:18.259881Z',
 'name': 'ABCs',
 'parent': None,
 'site_count': 1,
 'slug': 'abcs',
 'tags': [],
 'url': 'http://netbox.blahblah.com/api/dcim/site-groups/10/'}
`

I would expect to see a list of contacts there.

I then try to go backwards and pull all contacts and see if there is any reference in the GET output to their associated objects, and there isn't (which I wouldn't expect to be coming from this direction, but I did check)

### Use case

We want to use the Contacts in our Site Groups as a SoT for who to contact when alerting triggers for a site under that Site Group. We're able to figure out which site group a given site name is in, but can't get to the Contacts associated with the Site Groups.

I should mention that just adding the Contacts directly to the Site also doesn't help because the Site's GET output doesn't contain contacts data

### Database changes

N/A

### External dependencies

N/A

**Comment by Lisa94p** [comment]
Hello, I would like to link a similar requirement to this thread. 
I kindly need to retrieve the contacts associated with a circuit or with a provider, from the browser the pages consulted would be:
https://cmdb.skl.one/circuits/providers/33/contacts/
https://cmdb.skl.one/circuits/circuits/26/contacts/
but I can't find an associated API. Also by doing only
GET https://cmdb.skl.one/circuits/providers/33/   or
GET https://cmdb.skl.one/circuits/circuits/26/
I do not see anything regarding the associated contacts.

Looking forward for an update on this.
Many thanks

**Comment by DanSheps** [comment]
> ### Use case
> We want to use the Contacts in our Site Groups as a SoT for who to contact when alerting triggers for a site under that Site Group. We're able to figure out which site group a given site name is in, but can't get to the Contacts associated with the Site Groups.
> 
> I should mention that just adding the Contacts directly to the Site also doesn't help because the Site's GET output doesn't contain contacts data

This would require a separate API call to the /api/tenancny/contact-assignments API too get the associated contacts, however I just checked and it does look like the contact assignment is missing the correct filter fields to make this happen.

**Comment by jeremystretch** [comment]
Closing this out as stale as there's been no further discussion.
