### ISSUE TITLE
Tags are not displayed in the L2VPN Terminations - Table Configuration menu

### ISSUE THREAD

**Issue by fishdrummer** [netbox-community/netbox#14148]
### NetBox version

v3.6.4

### Python version

3.11

### Steps to Reproduce

In the L2VPN Terminations menu, in Table Configuration, it is not possible to display the "Tags" column.
Would it be possible to add it?

### Expected Behavior

The tags column is available in Table Configuration.

### Observed Behavior

Column not displayed at the moment in Table Configuration.

**Comment by kprince28** [comment]
Can anyone please assign this issue to me ?

**Comment by jeremystretch** [comment]
@kprince28 have you made any progress on this?
