### ISSUE TITLE
Use datasource file as custom validator

### ISSUE THREAD

**Issue by kuhball** [netbox-community/netbox#14158]
### NetBox version

v3.6.4

### Python version

3.10

### Steps to Reproduce

1. Create a datasource containing a custom validator class within a python file
2. Import the class within the gui via admin / current config using the displayed path within the datasource
3. Try to create / edit the model the validator is applied to

### Expected Behavior

The class can be imported and used as a validator analog to custom scripts.

Due to the new admin menu the current config and custom validator settings can be accessed from the ui. This would make a great addition to reduce manual configuration within the netbox host. 

Not sure if this correctly classified as a bug or rather a FR. 

### Observed Behavior

The class cannot be found when using the displayed path from the ui.

**Comment by jeremystretch** [comment]
What you're trying to do is not supported. Custom validator classes must be loaded into the Python virtual environment at runtime; they cannot be read from a remote file.
