### ISSUE TITLE
Changelog retention defaults to 90 days after upgrade, all prior changelogs are lost.

### ISSUE THREAD

**Issue by julianstolp** [netbox-community/netbox#14182]
### NetBox version

v3.6.4

### Python version

3.8

### Steps to Reproduce

1. Set the changelog retention days to other value than 90 days with a new configuration revision
2. Do upgrade as described in documentation [docs.netbox.dev](https://docs.netbox.dev/en/stable/installation/upgrading/)
3. Log in to your netbox instance and go to /extras/changelog and the changelog retention days have been defaulted to 90 days all prior logs are deleted.

### Expected Behavior

The changelog retention days should not default back to 90 days after upgrade. 

### Observed Behavior

/core/config/
![image](https://github.com/netbox-community/netbox/assets/41152397/fe85280c-5690-451f-946a-1f3e0d4badc2)

/extras/changelog/
![image](https://github.com/netbox-community/netbox/assets/41152397/57e2d792-c913-4d4d-b309-3b6627af3c5b)

/extras/config-revisions/add/
![image](https://github.com/netbox-community/netbox/assets/41152397/da4b7d97-8797-422b-b9f4-22ba57373deb)

**Comment by julianstolp** [comment]
@abhi1693 I can confirm that #14178 is actually the root cause for the behavior i have observed.

**Comment by abhi1693** [comment]
The issue is with the clearcache command that cleans out the config revisions.

**Comment by jeremystretch** [comment]
Rather than working around the specific cache entry, a more robust solution may be to move the designation of the active config version into the database. We could do this with a boolean column and a constraint limiting the table to a single true value.
