### ISSUE TITLE
Add ability to display parent location on dcim locations table

### ISSUE THREAD

**Issue by drossy** [netbox-community/netbox#14207]
### NetBox version

v3.6.4

### Feature type

Change to existing functionality

### Proposed functionality

Add parent location to the fields able to be displayed on the Locations table displayed on /dcim/locations.

### Use case

Adding the ability to display the parent Location on the /dcim/locations page would make it easier to distinguish between identically named Locations which have different Location hierarchies in the same Site.

We are looking to implement a new hierarchy in our netbox instance where our data centre is a Site and the multiple data centre rooms inside are Locations; and individual rows in those rooms are Locations whose parent is the Location corresponding to the appropriate room. These rows are labelled e.g. "Row 1", etc in each room. However the /dcim/locations table does not make it easy to distinguish between Row 1 in Room 1 and Row 1 in Room 2, as it only shows the Site.

### Database changes

None I believe - parent is an existing entry in the location api object

### External dependencies

None

**Comment by abhi1693** [comment]
I dont think this is a valid/actionable FR as the parent field on the locations page will be redundant due to the hierarchical structure which already exists.

![image](https://github.com/netbox-community/netbox/assets/5083532/dd5b3dcc-110c-4504-a492-a9a86d79d260)

**Comment by drossy** [comment]
If you filter for the specific name of the child location then its becomes less obvious:
![Screenshot 2023-11-10 at 09 53 46](https://github.com/netbox-community/netbox/assets/923739/cdbf1bc7-3c60-40af-96c5-4751bb62c7c2)

**Comment by jeremystretch** [comment]
We should also omit the leading hierarchy bullets from the "Name" column when a filter is in place.

**Comment by drossy** [comment]
I'm happy to take a look at implementing this if no one else is going to?

**Comment by jeremystretch** [comment]
@drossy are you still planning to work on this?

**Comment by arthanson** [comment]
un-assigning as no action on this.
