### ISSUE TITLE
Request to add SFP+ types

### ISSUE THREAD

**Issue by ljem86** [netbox-community/netbox#14206]
### NetBox version

v3.4.5

### Feature type

Change to existing functionality

### Proposed functionality

Netbox currently supports:

    # Fibrechannel
    TYPE_1GFC_SFP = '1gfc-sfp'
    TYPE_2GFC_SFP = '2gfc-sfp'
    TYPE_4GFC_SFP = '4gfc-sfp'
    TYPE_8GFC_SFP_PLUS = '8gfc-sfpp'
    TYPE_16GFC_SFP_PLUS = '16gfc-sfpp'
    TYPE_32GFC_SFP28 = '32gfc-sfp28'
    TYPE_64GFC_QSFP_PLUS = '64gfc-qsfpp'
    TYPE_128GFC_QSFP28 = '128gfc-qsfp28'

What we need to add:

    TYPE_32GFC_SFP_PLUS = '32gfc-sfpp’          => [Brocade 32Gb/s SWL SFP+ Product Brief](https://urldefense.com/v3/__https:/docs.broadcom.com/docs/GA-DS-2048__;!!BhdT!ls37dMy4pnF-6hdYjEYU8fb0n6iAjFY6b79usqjQOZ2rQE8wrRVNwh-m5e35xVboDcJ1jLAri-dA37NF2R1jRDFY$)
    TYPE_64GFC_SFP_PLUS = '64gfc-sfpp’          => [Brocade 32Gb/s SWL SFP+ Product Brief](https://urldefense.com/v3/__https:/docs.broadcom.com/docs/GA-DS-2048__;!!BhdT!ls37dMy4pnF-6hdYjEYU8fb0n6iAjFY6b79usqjQOZ2rQE8wrRVNwh-m5e35xVboDcJ1jLAri-dA37NF2R1jRDFY$)
    TYPE_64GFC_SFP_DD = '64gfc-sfpdd'            => [Brocade 64G SWL SFP-DD Product Brief](https://urldefense.com/v3/__https:/docs.broadcom.com/docs/SFP-DD-64G-SWL-PB__;!!BhdT!ls37dMy4pnF-6hdYjEYU8fb0n6iAjFY6b79usqjQOZ2rQE8wrRVNwh-m5e35xVboDcJ1jLAri-dA37NF2eSQwXt0$)

### Use case

We need to have above types added to Netbox as we are using them to build out DC. It will be usefull for the other users building the environment by Brocade vendor devices.

**Comment by apellini** [comment]
if @jeremystretch approves I could do that

**Comment by crijnsj** [comment]
@jeremystretch would you be so kind to approve. All NetBox users having Brocade FC SAN network switches Gen6, Gen7 will benefit from this change. Thanks in advance.

**Comment by DanSheps** [comment]
@apellini I have assigned this to you.

**Comment by eltoli01** [comment]
@jeremystretch Please approve since zCloud is using Gen6 already. We were forced to enter wrong information now.

**Comment by markkuleinio** [comment]
@jeremystretch I can do this
