### ISSUE TITLE
Let users edit `AUTH_EXEMPT_PATHS` configuration variable

### ISSUE THREAD

**Issue by miaow2** [netbox-community/netbox#14204]
### NetBox version

v3.6.4

### Feature type

Change to existing functionality

### Proposed functionality

NetBox has `AUTH_EXEMPT_PATHS` variable in which stored urls that exempted from authentication if `LOGIN_REQUIRED` is true.
At this moment user can't modify `AUTH_EXEMPT_PATHS` variable in `configuration.py`.
My idea is to move  `AUTH_EXEMPT_PATHS` variable definition from `settings.py` to `configuration.py`, so user can change the variable.

> 

### Use case

At my daily job we developed some plugins for NetBox (in NetBox instance `LOGIN_REQUIRED` is set to true), we want to provide access to some pages in these plugins without authentication and don't change NetBox source code.
So it would be great to have the opportunity to change `AUTH_EXEMPT_PATHS` variable.
Also, you can assign this issue to me, and I will create PR.

### Database changes

No changes.

### External dependencies

No dependencies.

**Comment by abhi1693** [comment]
Rather than allowing the user's to edit, we should extent the variable `AUTH_EXEMPT_PATHS` with the user provided values. This will ensure the defaults are not altered.

**Comment by miaow2** [comment]
Hi @abhi1693, this is a good point about extending the variable instead of editing, if your team is ok with that approach, I can implement this (extend variable `AUTH_EXEMPT_PATHS `) in PR
