### ISSUE TITLE
Configurable default device role color

### ISSUE THREAD

**Issue by kennethdammyr** [netbox-community/netbox#14228]
### NetBox version

v3.6.4

### Feature type

New functionality

### Proposed functionality

When creating a new Device Role in DCIM, the default color is "Grey". One should be able to change the default color. The setting should _not_ need to be dynamically configured (via Netbox admin interface), but should be statically set in the configuration file.

### Use case

In order for equipment to be categorized into correct device roles, I would argue that Device Role creation should be available to a lot of users. But then you might risk that they do not care to set the correct Color of the Device Role. The current default color of grey may not align with an organizations internal color scheme.

This would further enhance NetBox' ability to present infrastructure in a user friendly manner.

**Comment by abhi1693** [comment]
Although, I'm not convinced with the use case and its implementation, however, if accepted, I would argue that this should be extended to all such fields to provide default color selections to keep consistent behaviour throughout the application.
