### ISSUE TITLE
Cable edit not working

### ISSUE THREAD

**Issue by ramyalexis** [netbox-community/netbox#14234]
### NetBox version

3.6.4

### Python version

3.8

### Steps to Reproduce

Checked on demo site.
1. Pick any device with connected cables
2. Go to interface and edit cable from there.
3. Pick NEW device (just pick random one) for cable endpoint but leave OLD interface
4. Click save and observe "Success message"
![image](https://github.com/netbox-community/netbox/assets/278362/48c316f5-1798-4761-8a63-4ad3ec994460)
![image](https://github.com/netbox-community/netbox/assets/278362/32c3807a-6e3c-4f7e-956d-d927086c48df)
![image](https://github.com/netbox-community/netbox/assets/278362/878ccb71-8b9f-4c1a-9b78-1b7ce69145af)

### Expected Behavior

Cable endpoint changed. For example, you relink to the other switch, and it has same interface number, so device change should be enough without port change.
If this is not possible, generate an error. Like destination device does not have such port or something.
Do not fool user with success when no actual changes were made and it is in fact failed.

### Observed Behavior

In reality - no change is made. Can be confirmed at looking at the device interfaces. Old cable stays the same
Confusing log with change but nothing changed. Technically log is correct. Indeed, noting changed. But why it is then here  if this is **change log**?
![image](https://github.com/netbox-community/netbox/assets/278362/0339dfbe-b263-4bd7-8ab0-e25ab3e74143)

**Comment by abhi1693** [comment]
Device is not a discrete field on the cable model, it's provided for filtering purposes. So, the behaviour mentioned is expected.

**Comment by ramyalexis** [comment]
I am not aware of technical internal, but the fact is this is not working "correct".
In short - you change something. You got success message. Nothing changed. Do this sounds ok?

**Comment by jeremystretch** [comment]
@abhi1693 is correct: You changed the device field but did not make any change to the interface field. The device form field exists only to assist in filtering the interfaces list; changing it alone has no bearing on the assigned interface.

This in itself is not a bug, though I can see why it may be confusing. I've opened FR #14237 to propose a UI improvement to address this.

**Comment by kkthxbye-code** [comment]
@jeremystretch 

> This in itself is not a bug, though I can see why it may be confusing. I've opened FR https://github.com/netbox-community/netbox/issues/14237 to propose a UI improvement to address this.

Maybe I'm misunderstanding, but I don't believe that FR would fix anything in this particular case. Cables can terminate multiple interfaces on different devices. Clearing the multi-select cable termination field when changing the device would not really make sense.
