### ISSUE TITLE
Add Additional PON Interface Types

### ISSUE THREAD

**Issue by nick-bogle** [netbox-community/netbox#14250]
### NetBox version

v3.6.5

### Feature type

Data model extension

### Proposed functionality

I propose adding a new Interface Type of the following, that will be nested underneath the PON category in Netbox:

- BPON (622 Mbps / 155Mbps)
- 25G-PON (25 Gbps)

### Use case

Currently the Interface Types in Netbox include 6 other PON port types, but notably missing are:
BPON (Broadband PON) which was what came before GPON. This would be helpful for users that still have BPON in their networks.

25G-PON is a new PON standard that has been implemented by Nokia and while it is still pre-standard, is being deployed by several telecommunications companies.

### Database changes

N/A

### External dependencies

N/A

**Comment by apellini** [comment]
if @jeremystretch approves I could do that

**Comment by DorianXGH** [comment]
I would even go as far as to add the 50G-PON Huawei has been doing recently.
All in all, no reason not to add them.

**Comment by arthanson** [comment]
@nick-bogle can you please take a look at PR #16208 - would this address your request?

**Comment by nick-bogle** [comment]
> @nick-bogle can you please take a look at PR #16208 - would this address your request?

I'd personally not make the 50G-PON type Huawei specific. While Hauwei is the first to market with an option for this, it is really being defined under ITU G.9804.3, and is being implemented and tested actively by ZTE, Nokia, and others.

**Comment by arthanson** [comment]
thanks @nick-bogle

**Comment by DorianXGH** [comment]
@arthanson going through the changes, I just noticed I made a typo in the label of GPON when I wrote it, there's a missing 'b' in 'Gbps': `(TYPE_GPON, 'GPON (2.5 Gbps / 1.25 Gps)')` mayhaps this PR is a good opportunity to fix it ?
