### ISSUE TITLE
Add FXS Interface Type

### ISSUE THREAD

**Issue by nick-bogle** [netbox-community/netbox#14251]
### NetBox version

v3.6.5

### Feature type

Data model extension

### Proposed functionality

I propose adding a new interface group of Analog, and a new interface type of FXO/FXS.

### Use case

This would be a useful interface type to use on ATA devices, widely used in Enterprises and Service Providers. This would also be useful on any device that has a phone line interface of any kind (e.g. dial up modems for OOB, access control panels, fire alarm stations, etc).

### Database changes

N/A

### External dependencies

N/A

**Comment by apellini** [comment]
if @jeremystretch approve I could do that.

**Comment by nick-bogle** [comment]
@jeremystretch Why was this closed? I don't quite understand why voice ports would be ignored in this project, they're quite common in almost every enterprise, education, and service provider network. Analog Telephone Adapters still have a huge presence and would be very useful to document in Netbox.

**Comment by mhansen453** [comment]
I missed this feature request so I just created a new one asking for almost the exact same thing.
