### ISSUE TITLE
Russian translation

### ISSUE THREAD

**Issue by miaow2** [netbox-community/netbox#14266]
### Language

Russian

### ISO 639-1 code

ru

### Volunteer

Yes

**Comment by jeremystretch** [comment]
@miaow2 We've finally got things set up in Transifex. Would you like to own this effort? If so, we can get you set up in Transifex to start reviewing Russian string translations.

**Comment by miaow2** [comment]
@jeremystretch yeah, I would like to own this effort

**Comment by jeremystretch** [comment]
@miaow2 Excellent! The first step is to join [our Transifex project](https://explore.transifex.com/netbox-community/netbox/), then I can add you as a translation reviewer. Let me know if you encounter any issues signing up.

**Comment by opericgithub** [comment]
@jeremystretch I'm considering contributing to the Serbian translation. I have no experience with the Transifex project. Could you please inform me about the required skills (e.g., programming, scripting) and provide an estimate of the time it takes to complete the translation?

**Comment by stavr666** [comment]
Will test the translation on release 👍🏿

**Comment by miaow2** [comment]
> The first step is to join [our Transifex project](https://explore.transifex.com/netbox-community/netbox/), then I can add you as a translation reviewer.

@jeremystretch I've sent request for joining NetBox project

**Comment by click0** [comment]
I'm considering contributing to the Ukranian translation.
