### ISSUE TITLE
Warning when delete Interface or Ports with cable attached

### ISSUE THREAD

**Issue by rizlas** [netbox-community/netbox#14269]
### NetBox version

v3.6.4

### Feature type

Change to existing functionality

### Proposed functionality

Raise a warning in the popup window when deleting an interface or front/rear port with an attached cable.

![immagine](https://github.com/netbox-community/netbox/assets/8522635/69b00fec-1d90-461e-80c0-62e8db0db092)

### Use case

Warn the user that his action is going to influence other netbox entities.

**Comment by dejantep** [comment]
In my opinion warning should be "Denied - port/interface in use"
This should be core feature. General idea should also be expanded to virtual or LAG interfaces that have physical ports as parent.

**Comment by jeremystretch** [comment]
This is satisfied by FR #13690 (implemented in NetBox v3.7), which lists all dependent objects to be deleted.

@dejantep you're welcome to submit your own FR including a detailed implementation proposal and justifying your use case.
