### ISSUE TITLE
Allow default statuses to be customised

### ISSUE THREAD

**Issue by cmccallan** [netbox-community/netbox#1426]
Issue type: Feature Request

**Python version:**
**NetBox version:**

Currently when new IP addresses, Prefixes and VLANs are created their Status is defaulted to Active. This sometimes leads to issues of Netbox no longer being a source of truth if someone creates an IP/prefix/vlan and doesn't know/realise that it needs to be set to Reserved until it is actually active.
 What we'd ideally like to have is to be able to set Reserved to be the default, and then it can be changed to Active/Deprecated/DHCP when it is actually in that state. This would prevent having multiple IPs/prefixes/VLANs assigned Active that are not and improve reliability of our setup.

**Comment by jeremystretch** [comment]
This is similar to #492 (and probably some others) in that it would require a mechanism for storing preferences for individual users. I'd like to implement a simple sort of key/value store for this (rather than continually extending a profile model). Need to look more into what would work best.

**Comment by cmccallan** [comment]
Potential workaround could be making it a mandatory field and setting default to a null value? Might not be ideal but would prevent wrong provisioning if a user has to manually select a status.

**Comment by puck** [comment]
For simple arbitrary key/value store, see the JSONB data type I just mentioned on #1349. :)

**Comment by jeremystretch** [comment]
@puck v2.2 will require PostgreSQL 9.4+ to support JSONB anyway (for storing report data), so that's a very appealing solution.

**Comment by jeremystretch** [comment]
Blocked by #3294

**Comment by jeremystretch** [comment]
Rather than requiring the user to pick a specific default status (for this and numerous other objects), it might make more sense for NetBox to "remember" the last-chosen status used when creating/editing that type of object. This would work similarly to how NetBox remembers table column preferences for individual users.
