### ISSUE TITLE
Extend customvalidators with user request information

### ISSUE THREAD

**Issue by ITJamie** [netbox-community/netbox#14279]
### NetBox version

v.3.6.5

### Feature type

Change to existing functionality

### Proposed functionality

Extend customvalidators with an additional variable - request user details

### Use case

It would be great it customvalidators had a way to check what users are making the request. in some situations, it can make sense to allow one user/usergroup/API integration the ability to skip a specific validation.

for example we wish to use an ipaddress validator to make sure rfc 1918 ip's don't end up in the global vrf, however there is one particular api integration that is going to take quite awhile to update to support vrf lookup's, in the meantime we want to stop any other rfc 1918 ip's getting added to the global vrf. being able to write the validator with an exclusion for a particular user would be great.

I understand that sometimes the supplied user would also need to be None/False as changes from nbshell wouldn't have an attached user.

**Comment by ITJamie** [comment]
some examples of integrations that right now don't have vrf support so it would be great to be able to exclude the related user from an rfc1918 validator
plugin: netbox-proxmox
external integration: xoa (it uses the API & has no concept of a vrf)

**Comment by peteeckel** [comment]
Thanks! I support that and suggest extending the concept to the new ProtectionRule feature to be introduced with version 3.7.

**Comment by jeremystretch** [comment]
Historically this has not been possible as custom validators are processed via the `post_clean` signal, and signal handlers have no direct access to the request being processed. However, I believe this is now feasible with the somewhat recent introduce of the `current_request` context variable, which can be referenced fro inside the signal receiver.

Also, the `CustomValidator` class will need to be extended to support the inclusion of request context in addition to the object itself.
