### ISSUE TITLE
Add Configuration Template Variable Table

### ISSUE THREAD

**Issue by MCDELTAT** [netbox-community/netbox#14277]
### Change Type

Addition

### Area

Features

### Proposed Changes

Should we add an exhaustive list of variables that can be used in Jinja Configuration Templates? At the moment, it does not appear any reference exists at all.

I found this tutorial from Netbox Labs [here][1]. I also found the short snippet that exists in the `Configuration Rendering` page of the official docs [here][2].

I noticed that many of the items are simply the JSON path of the Device API Response such as `device.device_type.manufacturer.slug`. However, on testing some like `device.device_type.display` did not render, telling me there are exceptions to the API response. In the first example, it also calls things like `device.interfaces.all()`, when there is no direct `device.interfaces` object on the API response. Are there additional functions? What are they? I think the doc would be helpful in referencing all of this.

This seems like a good first ticket and I wouldn't mind picking it up if it isn't a quick write up for a current maintainer.

Thanks.

[1]: https://netboxlabs.com/blog/how-to-generate-device-configurations-with-netbox/
[2]: https://docs.netbox.dev/en/stable/features/configuration-rendering/

**Comment by YooBZH** [comment]
Hi,

I second this demand, I am struggling with Netbox templating because of that.
I managed to find a few examples on the web but that is about it.

A documentation could solve this problem, or maybe there is a way to "explore" by ourselves ?
Like creating a dummy template and trying things like (this does not work, dont bother trying) :
```jinja2
{% for x in device | items() %}
{{ x }}
{% endfor %}
```
Or something equivalent, so we can discover by ourselves all the capabilities of an object.

I tried a lot of things, like accessing `device.__dict__()` or `device.__dir__()` but this does not work because of security reason.

```python
jinja2.exceptions.SecurityError: access to attribute '__dir__' of 'Device' object is unsafe.
```
If anyone has any hint I think a lot of use would appreciate that :)

Bonus note:
while writing this comment I experimented a bit and found out that you can list ipam capabilities with :
```jinja2
{% for x in ipam | items() %}
{{ x }}
{% endfor %}
```

Which render to : 
```python
('IPAddress', <class 'ipam.models.ip.IPAddress'>)

('RIR', <class 'ipam.models.ip.RIR'>)

('ASN', <class 'ipam.models.asns.ASN'>)

('VRF', <class 'ipam.models.vrfs.VRF'>)

('FHRPGroup', <class 'ipam.models.fhrp.FHRPGroup'>)

('Aggregate', <class 'ipam.models.ip.Aggregate'>)

('Prefix', <class 'ipam.models.ip.Prefix'>)

('IPRange', <class 'ipam.models.ip.IPRange'>)

('Role', <class 'ipam.models.ip.Role'>)

('ASNRange', <class 'ipam.models.asns.ASNRange'>)

('VLANGroup', <class 'ipam.models.vlans.VLANGroup'>)

('ServiceTemplate', <class 'ipam.models.services.ServiceTemplate'>)

('L2VPN', <class 'ipam.models.l2vpn.L2VPN'>)

('Service', <class 'ipam.models.services.Service'>)

('RouteTarget', <class 'ipam.models.vrfs.RouteTarget'>)

('VLAN', <class 'ipam.models.vlans.VLAN'>)

('L2VPNTermination', <class 'ipam.models.l2vpn.L2VPNTermination'>)
```

I dont know how to dig further.

**Comment by MCDELTAT** [comment]
Two weeks later and I haven't been able to figure out what the available items by looping over things either. I tried reading the code but honestly there's a lot of Django magic going on.

Files of interest:
1. `netbox/templates/dcim/device/render_config.html` -> Where the rendered config shows up on the device.
2. `netbox/dcim/views.py` -> `class DeviceRenderConfigView`
3. `netbox/dcim/api/views.py` -> `class DeviceViewSet`

So I forged on without docs and have several questions. Is there a way to get IPs on the interface? I.E. `interface.ip`. Would this be an array for interfaces with multiple IPs?

**Comment by YooBZH** [comment]
@MCDELTAT here are some ways to work with device interfaces and their IP addresses.

Print all interfaces and their first assigned IP address : 
```jinja2
{% for intf in device.interfaces.all() %}
{{ intf }} ip address : {{ intf.ip_addresses.first() }}
{% endfor %}
```

To access the IP address of a specific interface you can filter the interface by name, something like :

```jinja2
{{ device.interfaces.filter(name="GigabitEthernet0/0/0").0.ip_addresses.first() }}
```

If the interface has more than one IP address, you can loop over all of them :
```jinja2
{% for ip_address in device.interfaces.filter(name="GigabitEthernet0/0/0").0.ip_addresses.all() %}
{{ ip_address }}
{% endfor %}
```

I hope this will help you and others, it will certainly help me when I will have forgotten about all of that :)

**Comment by jacobw** [comment]
@MCDELTAT I've been using ./manage.py nbshell to explore the data models when working up a template. I find it quite easy to figure out what's available once you get the hang of it. The main thing that helps is tab completion, and instant results.
