### ISSUE TITLE
Airflow not shown on device view if only set on the devicetype

### ISSUE THREAD

**Issue by PieterL75** [netbox-community/netbox#14280]
### NetBox version

v3.6.5

### Python version

3.10

### Steps to Reproduce

1. Create a devicetype without an airflow
2. Create a device, based on that devicetype, but leave the airflow undefined
3. update the devicetype and set an airflow
4. Open the device page

### Expected Behavior

If no airflow is set on the device, but one is set on the devicetype, then the airflow of the devicetype should be shown in the deviceview

### Observed Behavior

The airflow is a 'placeholder' (dashes).
it only shows when the airflow is set on the device.

**Comment by jeremystretch** [comment]
> If no airflow is set on the device, but one is set on the devicetype, then the airflow of the devicetype should be shown in the deviceview

This gets a little murky. The device view is showing the value of the device's own `airflow` field, which happens to be null. While I understand the assumption that this value should "default" to the setting on the assigned device type, this would be dangerous and inaccurate without some canonical logic in place to make that connection. For instance, looking at the device view alone, how would you know if you're seeing the airflow value of the device itself or of the device type? And what if they're both set to different values?

I see a couple options:

1. Leave the display as-is, and modify the device creation form to default the airflow field to an "inherit" option, which would automatically replicate the new device's `airflow` field to the value set on the device type. (We'd still want to retain an option for "none" as well.)
2. Establish some property which represents the inferred value, preferring the local `airflow` value but defaulting to the device type's `airflow` value. This would need to be conveyed via the API as well.

**Comment by PieterL75** [comment]
The second option comes closest to what I have in mind.
It kind of makes sense, that the device's airflow overrides the device type's airflow.
Maybe if this is clearly documented?

What does the current api call is a device gives you, when getting the airflow? When none is set on the device, or when the device has a different airflow than the device type 

Pierer

**Comment by jvalente-salemstate** [comment]
I think a good, and usable, middle ground would be a button in the device (and device type, for bulk changes) to populate empty properties from the device type.  If a device type is created without a property, airflow for example, and devices are created from that template then the template is later updated, this will fetch those fields.
