### ISSUE TITLE
Column VLAN Tagged VLANs as summary.

### ISSUE THREAD

**Issue by LHBL2003** [netbox-community/netbox#14285]
### NetBox version

v.3.6.5

### Feature type

Change to existing functionality

### Proposed functionality

We have around 100 tagged VLANs on some ports, e.g. 2000-2100 for development systems.

The Tagged VLANs column can be displayed in the interface overview. The only problem is that the view then explodes.

It would be good to have a Short Tagged VLANs column, where only the numbers are listed as a summary. As is the case with some switch manufacturers, for example. So e.g. VLAN: 1;5;10;2000-2100

Before
![image](https://github.com/netbox-community/netbox/assets/46369917/ad63282a-45b5-4cd3-8acd-72a28a7b7261)

Afterwards
![image](https://github.com/netbox-community/netbox/assets/46369917/5e25bb99-93f1-409c-9d25-5bfd661bdc76)

### Use case

The overview in the list view for the interfaces is retained. If 30 ports with VLAN 2000 to 2100 are tagged on a 48 port switch, you lose the overview. The Short VLANs column would maintain clarity despite the large amount of information.

**Comment by abhi1693** [comment]
How do you propose to linkfy the items? Or is the intent to not have a way to link the items at all?

**Comment by jeremystretch** [comment]
One option would be to list only _n_ items, and if the total count exceeds _n_ display a link to the filtered list view in addition to the objects listed.

**Comment by LHBL2003** [comment]
I also like your solution very much. Anything is better than having to scroll 2 screens for an interface. :)

**Comment by dejantep** [comment]
> One option would be to list only _n_ items, and if the total count exceeds _n_ display a link to the filtered list view in addition to the objects listed.

Or maybe even just a count of VLANS as an integer. The view is pretty jammed with info and imho it would be good to keep it as clean as possible

**Comment by LHBL2003** [comment]
This would then correspond to the picture above.
Personally, I like both ideas better than the current situation.

**Comment by LHBL2003** [comment]
@jeremystretch 
Could you accept a variant as a suggestion for improvement, I don't care which one, the main thing is that the overview improves.
Thank you

**Comment by jeremystretch** [comment]
Please stop pinging me. I will spend time on this issue when I am able.

**Comment by LHBL2003** [comment]
The current situation is that if I have set the tagged VLAN 2000 to 2100 on a switch port, I now only document the first and last VLAN in Netbox. Because the current form of the table display obscures my view. It doesn't have to be that the current column display is replaced. Perhaps it is possible to offer further column displays.

**Idea (Very short)**
If there were another column display, then this would certainly be the best choice. Because it is short and crisp.
By clicking on the link you can then access a filtered VLAN list for this interface.

Example representation: 
![image](https://github.com/netbox-community/netbox/assets/46369917/fcdc0a73-99b8-4898-9452-db22b0ee0bb3)

**Idea (Short but very informative)**
However, I don't think Jeremystretch's variant is bad either, which limits the list to e.g. 3 to 10 items and everything else is accessed via e.g. 3 points. 

![image](https://github.com/netbox-community/netbox/assets/46369917/9dca3ee5-f0af-4fc3-a543-552ee16b8650)

So that you don't have to click so much, you can hover over the 3 points and get a tooltip where more is displayed in advance.

![image](https://github.com/netbox-community/netbox/assets/46369917/6eb3aa01-7034-4322-b4b5-f030ded20b42)
`<a title="Test 0 (2000)&#013;Test 1 (2001)" href="/ipam/vlans/32/">...</a>`

I won't be able to realise it. I don't have the experience to debug everything properly. But I have tried whether the tooltip can be solved via Google Chrome :) In combination with Jeremystretch's train of thought, this second idea could be really good.
