### ISSUE TITLE
Child site group not selectable in vlan group as scope

### ISSUE THREAD

**Issue by rizlas** [netbox-community/netbox#14282]
### NetBox version

v3.6.4

### Python version

3.11

### Steps to Reproduce

1. Create a Site Group
2. Add a Site Group Child to the previous Site group created
2. Create a VLAN Group and select Site Group as Scope type 
3. Created child site group is not listed in Site group

### Expected Behavior

Possibility to select child site group as vlan group scope.

### Observed Behavior

Not possible to select child site group

**Comment by jeremystretch** [comment]
Thank you for opening a bug report. Unfortunately, the information you have provided is not sufficient for someone else to attempt to reproduce the reported behavior. Remember, each bug report must include detailed steps that someone else can follow on a clean, empty NetBox installation to reproduce the exact problem you're experiencing. These instructions should include the creation of any involved objects, any configuration changes, and complete accounting of the actions being taken. Also be sure that your report does not reference data on the public NetBox demo, as that is subject to change at any time by an outside party and cannot be relied upon for bug reports.

**Comment by rizlas** [comment]
I'll close this. Maybe was a temporary error in the filter used by drop down menu. Sorry for bothering you.
