### ISSUE TITLE
Menu Option To Include Licensing Applied To Devices

### ISSUE THREAD

**Issue by JosephLive93** [netbox-community/netbox#14304]
### NetBox version

v3.6.5

### Feature type

Data model extension

### Proposed functionality

A non mandatory field to list license information for devices that are within Netbox. This may be in the best form as a field since licensing names can vary. Some devices could include multiple licenses, so maybe an option to be able to select multiple licenses.

### Use case

Most network devices have some sort of licensing that can or is already applied to devices so it would benefit to to have this as a default menu option without having to make a custom field for this.

**Comment by abhi1693** [comment]
Thank you for your interest in extending NetBox. Unfortunately, the information you have provided does not constitute an actionable feature request. Per our [contributing guide](https://github.com/netbox-community/netbox/blob/develop/CONTRIBUTING.md), a feature request must include a thorough description of the proposed functionality, including any database changes, new views or API endpoints, and so on. It must also include a detailed use case justifying its implementation. If you would like to elaborate on your proposal, please modify your post above. If sufficient detail is not added, this issue will be closed.

**Comment by jeremystretch** [comment]
This issue is being closed as no further information has been provided. If you would like to revisit this topic, please first modify your original post to include all the requested detail, and then ask that the issue be reopened.
