### ISSUE TITLE
Inactive Replicate components and Adopt components fields after installing the module in the device

### ISSUE THREAD

**Issue by Breadberry07** [netbox-community/netbox#14300]
### NetBox version

v3.6.5

### Python version

3.8

### Steps to Reproduce

I apologize in advance, maybe this is not a bug, but it would be cool if you could activate the "Replicate components" and "Adopt components" fields so that when you move a previously installed module to another slot on the device, the interfaces also change their number to the slot number (this behavior is relevant for all versions of 3.6+). 

This is how it manifests itself:
1. Create some device with "Slots" (in example MX960 chassis)
![image](https://github.com/netbox-community/netbox/assets/122742913/4bcb3a3d-90b4-4982-98e9-7c6de00a7773)

2.  Create some modules with "interfaces" (in example MX960 MPC5 card)
![image](https://github.com/netbox-community/netbox/assets/122742913/a9385193-99f0-412f-8460-d262625a3940)

3. Install this Module to Device and activate the points "Replicate components" and "Adopt components"
![image](https://github.com/netbox-community/netbox/assets/122742913/ecf10c5f-b431-4c81-9f8f-99a90aa696ef)

4. You can see how the interface numbers have been adapted to the slot number
![image](https://github.com/netbox-community/netbox/assets/122742913/4121dafd-8ae8-4dc9-87e9-dedfba0b1497)

5. Let's try to move the module to another slot of the device and see that the "Replicate components" and "Adopt components" fields cannot be activated, respectively, because of this, the module port numbering does not change
![image](https://github.com/netbox-community/netbox/assets/122742913/c08fcc8e-a130-40a2-94cc-3b6605fe77b5)

### Expected Behavior

It was expected that it would be possible to adapt the numbering of interfaces when transferring the module from one slot of the device to another

### Observed Behavior

It is not possible to automatically change the numbering of the module interfaces after it is installed in the device

**Comment by jeremystretch** [comment]
This would be a feature request, not a bug. You're welcome to [submit one](https://github.com/netbox-community/netbox/issues/new?assignees=&labels=type%3A+feature&projects=&template=feature_request.yaml) citing your proposed implementation and use case, but bear in mind doing so will involve capturing the logic to reverse engineer the templatized slot and position identifiers. This is not a trivial task, so please be sure to include your proposed solution if you decide to proceed with a feature request.
