### ISSUE TITLE
Allow VM to be assigned to device without the need for a cluster object

### ISSUE THREAD

**Issue by empusas** [netbox-community/netbox#14301]
### NetBox version

v3.6.5

### Feature type

Change to existing functionality

### Proposed functionality

It would be nice if the cluster would be optional if a VM is assigned to a device. Currently it requires to create fake cluster object to assign a VM to a single device. That should be a optional relation, not a mandatory one.

### Use case

Network virtualization platforms like Cisco CSP have a local hypervisor like KVM that allows to run VMs. VMs are local to those machines

### Database changes

None

### External dependencies

None

**Comment by jeremystretch** [comment]
Thank you for submitting this issue, however it appears that this topic has already been raised. Please see issue #12024 for further discussion.
