### ISSUE TITLE
Netbox API ignores PATCH request to remove tag from device

### ISSUE THREAD

**Issue by BackblazeJeremy** [netbox-community/netbox#14303]
### NetBox version

v3.6.3

### Python version

3.11

### Steps to Reproduce

1. Create device with tag `webhook-test`.
2. Edit attached Python script to set valid API token and device ID.
3. Run Python script and review output.
[remove_tag.py.txt](https://github.com/netbox-community/netbox/files/13419195/remove_tag.py.txt)

The API key used to reproduce this error in our instance was read/write and was attached to an account that is in a group with every permission assigned.

### Expected Behavior

1. The request should return JSON for the device with the amended tag list
2. Netbox should show the device without the tag that we requested to remove
3. Netbox should show this change in the changelog

### Observed Behavior

1. Observe that the request in the script returned with code `200` an unchanged device object.
2. In Netbox UI, see that tag is still present and that the changelog has an entry with no changes.
[remove_tag.log](https://github.com/netbox-community/netbox/files/13419196/remove_tag.log)

**Comment by jeremystretch** [comment]
We are not able to evaluate custom scripts as part of the bug reporting process. Please revise your post above to include complete reproduction steps, and distill your code to the raw API request you believe demonstrates the reported behavior.

**Comment by jeremystretch** [comment]
This issue is being closed as no further information has been provided. If you would like to revisit this topic, please first modify your original post to include all the requested detail, and then ask that the issue be reopened.
