### ISSUE TITLE
Bulk editing interfaces clears the tagged VLAN list

### ISSUE THREAD

**Issue by dpotter-intoto** [netbox-community/netbox#14316]
### NetBox version

v3.5.3

### Python version

3.8

### Steps to Reproduce

1.  In a list of interfaces, select the checkbox near a number of interfaces, some of which are in 802.1Q "Tagged" mode and have a list of 802.1q tagged VLANs
2.  Click "Edit"
3. Change any property of the interface (e.g. description, tags). Do NOT click "Set to null" next to the "Tagged VLANs' field.
4. Click "Apply"
5. Observe that the interfaces are still in tagged mode, but no longer have a list of VLANs

### Expected Behavior

Unless the "Tagged VLANs" "set to null" checkbox is selected, the field should not be cleared.

### Observed Behavior

The "Tagged VLANs" field was cleared

**Comment by jeremystretch** [comment]
It looks like you've run into bug #12983, which was resolved in NetBox v3.5.5. Please upgrade to this or a later release to resolve the issue.
