### ISSUE TITLE
Move L2VPN models to new vpn app

### ISSUE THREAD

**Issue by jeremystretch** [netbox-community/netbox#14311]
### Proposed Changes

FR #9816 (VPN tunnel modeling) has introduced a new `vpn` app. This issue proposes moving the L2VPN and L2VPN Termination models and all their related resources from the `ipam` app to the `vpn` app.

### Justification

There was discussion at the time when L2VPN support was being added about whether it made sense to create a new app for it. Although we opted not to at the time, it would be prudent to move these now as the `vpn` app is a much more suitable home for these models.

Unfortunately, this will effect a breaking change in the REST API, however it should be easily manageable.

**Comment by abhi1693** [comment]
Will bookmarks remain unaffected?

**Comment by jeremystretch** [comment]
I expect related objects, content types, etc. to all be unaffected; that's the plan at least. We've never actually moved a model between apps before IIRC, but I don't _think_ it will be too disruptive.
