### ISSUE TITLE
Front Ports count is not updated when removing rear ports.

### ISSUE THREAD

**Issue by Chiniquy** [netbox-community/netbox#14323]
### NetBox version

v3.6.5

### Python version

3.8

### Steps to Reproduce

Create a device (preferably of a device type without any front or rear ports).
On this device, create a rear port with name "test" and type "Other", with 2 positions.
Create 2 frontports by using "test [1-2]" as name, with type "Other", and select the 2 positions of the newly created rear port.
Now remove the rear port that you created.
On the device view you will now see a "2" on the Front port tab, but there will be no Front Ports inside the tab. 

### Expected Behavior

If the Front Ports are deleted, then the "2" on the Front Port tab should not be there, and the tab should not be visible.

### Observed Behavior

The Front Port tab shows the number "2", indicating the existance of 2 Front Ports. However, when clicking on the Front Port tab, no Front Ports are visible.

**Comment by jeremystretch** [comment]
It seems that the cascading deletion triggered by removing the rear port is not detected by the tracking logic.
