### ISSUE TITLE
Perform an update of the devices already created, when their device_type is modified

### ISSUE THREAD

**Issue by ShadowCipher09** [netbox-community/netbox#14320]
### NetBox version

v3.6.4

### Feature type

Data model extension

### Proposed functionality

Could it be that when a device_type is modified, the devices of that "device_type" are modified, even though they are already created? That is to say, that the devices already made are updated

### Use case

Keeping the devices updated or giving the option of when a device_type to update the old ones or not, if not I have to modify the existing ones one by one and when I have more than 300 it is very heavy...

### Database changes

Perform an update of the devices already created

**Comment by abhi1693** [comment]
Thank you for your interest in extending NetBox. Unfortunately, the information you have provided does not constitute an actionable feature request. Per our [contributing guide](https://github.com/netbox-community/netbox/blob/develop/CONTRIBUTING.md), a feature request must include a thorough description of the proposed functionality, including any database changes, new views or API endpoints, and so on. It must also include a detailed use case justifying its implementation. If you would like to elaborate on your proposal, please modify your post above. If sufficient detail is not added, this issue will be closed.

**Comment by jeremystretch** [comment]
@gdprdatasubect this is precisely why the functionality does not exist today. NetBox should never make assumptions on behalf of the user. It has been discussed at length in previous issues, and no workable implementation has been proposed.

**Comment by jeremystretch** [comment]
Closing this out as  this proposal has already been considered and rejected in the past for the reason I cite above, and no further detail has been offered.
