### ISSUE TITLE
User password update via REST API is not hashed

### ISSUE THREAD

**Issue by fanshan** [netbox-community/netbox#14339]
### NetBox version

v3.6.5

### Python version

3.11

### Steps to Reproduce

1. Create a new User with password (username: test, password: test). For the request use a user with user creation permission:
```
curl --location 'http://netbox/api/users/users/' \
--header 'Authorization: Token 45202..6e9e092df' \
--header 'Content-Type: application/json' \
--data '{
    "username": "test",
    "password": "test"
}'
```
2. Update the new created user's password with a new one. For the request use a user with user change permission and the created user `{id}`:
```
curl --location --request PATCH 'http://netbox/api/users/users/{id}/' \
--header 'Authorization: Token 45202..6e9e092df' \
--header 'Content-Type: application/json' \
--data '{
    "password": "newpassword"
}'
```

### Expected Behavior

The password stored on the database must be hashed, so user with the password updated is able to login on the Netbox instance.

### Observed Behavior

The password stored on the database is not hashed, so user with the password updated is not able to login on the Netbox instance.

Connected on the database, do (where `{id}` is the created user's id) :

`SELECT password FROM auth_user WHERE id={id}`

Result `"newpassword"`

**Comment by abhi1693** [comment]
Thank you for opening a bug report. I was unable to reproduce the reported behavior on NetBox v3.6.5. Please re-confirm the reported behavior on the current stable release and adjust your post above as necessary. Remember to provide detailed steps that someone else can follow using a clean installation of NetBox to reproduce the issue. Remember to include the steps taken to create any initial objects or other data.

Barring the canned message, I followed the exact steps you have provided and my DB has the hashed password

![image](https://github.com/netbox-community/netbox/assets/5083532/f5716932-c714-4924-b2b4-ad7ca5e8e993)
