### ISSUE TITLE
Hide webhook bearer tokens

### ISSUE THREAD

**Issue by arjenvri** [netbox-community/netbox#14345]
### NetBox version

v3.6.5

### Feature type

Change to existing functionality

### Proposed functionality

Add the possibility to hide webhook additional headers information for all users just having read-only rights for webhooks.
One solution would be adding an additional field for secrets that is hidden for read-only users and can be referred to as variable in the additional headers and payload configuration.

### Use case

For many webhooks,  headers are used for bearer token style authentication. Currently these secrets can be read by users with read-only rights, although these secrets could be sensitive.

### Database changes

Add additional webhook field to store an api secret.

**Comment by jeremystretch** [comment]
Thank you for your interest in extending NetBox. Unfortunately, the information you have provided does not constitute an actionable feature request. Per our [contributing guide](https://github.com/netbox-community/netbox/blob/develop/CONTRIBUTING.md), a feature request must include a thorough description of the proposed functionality, including any database changes, new views or API endpoints, and so on. It must also include a detailed use case justifying its implementation. If you would like to elaborate on your proposal, please modify your post above. If sufficient detail is not added, this issue will be closed.

**Comment by arjenvri** [comment]
thank you, updated with an actionable suggestion.

**Comment by arthanson** [comment]
This would be addressed by #14008

**Comment by jeremystretch** [comment]
It certainly seems like the use case cited here would be covered by #14008, so I'm going to close this out. Please comment under that issue if there are specific other details you'd like considered as part of that work.
