### ISSUE TITLE
Add "set rack" option in bulk change for multiple devices

### ISSUE THREAD

**Issue by ultrapista** [netbox-community/netbox#14341]
### NetBox version

v3.6.5

### Feature type

Change to existing functionality

### Proposed functionality

Currently if the user wants to edit multiple devices (bulk edit), which are already positioned in the same rack, and wants to move them to different location, NetBox throws out alert notification: **Rack XX does not belong to location XX**. 
\
If it is possible to demount them from the rack with this bulk change and move them to another location with the option to mount them to different rack (**Position: Not racked**) or implement **Set Null** option for the Rack field.
![Screenshot (57)](https://github.com/netbox-community/netbox/assets/83075719/ef5605d6-ed45-4ef8-89fe-a7ba0407334c)

### Use case

- Users do not have to demount devices from the rack manually for multiple devices
- Moving devices to different location (for example storage) would be much easier

### Database changes

None

### External dependencies

None

**Comment by jeremystretch** [comment]
Thank you for submitting this issue, however it appears that this topic has already been raised. Please see issue #4268 for further discussion.
