### ISSUE TITLE
Ability to add a submodule into a module

### ISSUE THREAD

**Issue by a173tfo** [netbox-community/netbox#14359]
### NetBox version

v3.5.3

### Feature type

Data model extension

### Proposed functionality

Is it possible to change the data model in such a way that it is possible to add submodules inside the module? For example, in order to correctly create a device that has slots for interface cards and the interface cards themselves have only slots for interface subcards with network interfaces, as in the figure:

![netb](https://github.com/netbox-community/netbox/assets/104919266/a18826e6-198f-457f-b923-6c8ac8416264)

### Use case

This will help to correctly create devices of this type.

**Comment by jeremystretch** [comment]
Thank you for submitting this issue, however it appears that this topic has already been raised. Please see issue #10500 for further discussion.
