### ISSUE TITLE
Allow configuration templates to reference other templates

### ISSUE THREAD

**Issue by elipsion** [netbox-community/netbox#14356]
### NetBox version

v3.6.4

### Feature type

Change to existing functionality

### Proposed functionality

Amend the template loader (`netbox/utilities/jinja2.py`) to also fetch templates from the database, via some virtual path.

A suggested virtual path structure is to follow the `/dev/disk/by-xxx` model of udev, but the actual format is up to NetBox maintainers. It is probably best examplified:

- `/netbox/by-name/My generic template`
- `/netbox/by-id/4`

The risk of someone naming their templates as such in a Data Source is probably slim.

### Use case

When writing configuration templates directly (i.e. not via Data Sources), I would like to reference other templates.

### Database changes

None that I can think of.

### External dependencies

No.

### Considered alternatives

I tried to dig through the NetBox data model and render the template manually (`{{ extras.ConfigTemplate.objects.get(name="Default").render() }}`) but:

1. This requires needlessly high knowledge of the data model for an average user.
2. It's unclear how/if the configuration environment is passed along
3. Only `WebHook` and `JournalEntry` are present in `extras`

**Comment by elipsion** [comment]
@jeremystretch, did you have a chance to look at this?

**Comment by jeremystretch** [comment]
It is already possible to reference other templates from within the same data source using the standard Jinja2 `{% include %}` tag. Please open a discussion if you need assistance utilizing this feature.
