### ISSUE TITLE
Add a description field to the Webhook model

### ISSUE THREAD

**Issue by jeremystretch** [netbox-community/netbox#14361]
### NetBox version

v3.6.5

### Feature type

Data model extension

### Proposed functionality

Add a standard description field to the Webhook model.

### Use case

This will enable users to record a brief description concerning the use of the webhook. This has become more important in the wake of #14267, which separates the event logic from the webhook definition using the new EventRule model.

### Database changes

Add a new CharField

### External dependencies

None

**Comment by jacobpfickes** [comment]
I'd like to contribute to this issue

**Comment by jeremystretch** [comment]
@jacobpfickes I really appreciate the interest and normally I'd be happy to assign this to you, however we're in a bit of a time crunch right now as we need to release the v3.7 beta by end of week. There might also be some conflicts with other ongoing work that could complicate the PR process. So I'm going to knock this out myself real quick, but I encourage you to browse some of our other [open issues](https://github.com/netbox-community/netbox/issues?q=is%3Aissue+is%3Aopen+label%3A%22status%3A+needs+owner%22) to see if there's anything else you'd like to take on.

**Comment by jacobpfickes** [comment]
@jeremystretch Ok completely understand. I have a changes on my fork and ready to submit a PR right now if that helps. If not then no worries. It is my fault for not getting it assigned before working on it.
