### ISSUE TITLE
Allow assignment for custom fields similar to config contexts

### ISSUE THREAD

**Issue by TribuneX** [netbox-community/netbox#14360]
### NetBox version

v3.6.3

### Feature type

New functionality

### Proposed functionality

Allow to add assignments to custom fields (similar to the assignment in config contexts)

Might be dependent on the refactoring planned in https://github.com/netbox-community/netbox/issues/14000

### Use case

We created a custom field for interfaces, which should only be available on interfaces which are part of a virtual chassis with a certain device type.
Therefore, we would like to add an assignment to this custom field similar to assignments available on config contexts.

This is the UI available for config contexts, which could look similar in custom fields:
<img width="766" alt="Screenshot 2023-11-28 at 11 58 39" src="https://github.com/netbox-community/netbox/assets/7440759/5d814988-d366-4780-882c-8c833c513c22">

**Comment by jeremystretch** [comment]
Thank you for submitting this issue, however it appears that this topic has already been raised. Please see issue #11367 for further discussion.

**Comment by TribuneX** [comment]
Thanks for the reference. I am wondering why config contexts are allowed to be assigned to certain types but custom fields should not be. Thats not part of the linked discussion yet.
Building a plugin just for a single extra field introduces a lot of overhead for just little functionality.

**Comment by jeremystretch** [comment]
I think you misunderstand how config contexts work: They are not defined per-object, whereas custom fields are. They are entirely separate concepts and used very differently.
