### ISSUE TITLE
ability to add custom links to config templates

### ISSUE THREAD

**Issue by rrizun** [netbox-community/netbox#14366]
### NetBox version

v3.6.5

### Feature type

Data model extension

### Proposed functionality

ability to add custom links to config templates .. the custom link 'content-types' selection ( here: https://demo.netbox.dev/extras/custom-links/add/ ) has many netbox object types .. but config-templates is currently not one of them

implementation-wise I think this means adding CustomLinksMixin to ConfigTemplate model amongst other things?

so, proposed functionality here would mean to add "Extras > Config Template" to the custom-link content-types drop down selection

### Use case

my use case is I would like to add a custom link to a config template so that I can render the template using 'general purpose use' https://docs.netbox.dev/en/stable/features/configuration-rendering/ .. in my use case I use templates in situations other than per-device situations .. being able to add a custom-link will let me point to my custom script do perform custom rendering of the config template

**Comment by jeremystretch** [comment]
Thank you for your interest in extending NetBox. Unfortunately, the information you have provided does not constitute an actionable feature request. Per our [contributing guide](https://github.com/netbox-community/netbox/blob/develop/CONTRIBUTING.md), a feature request must include a thorough description of the proposed functionality, including any database changes, new views or API endpoints, and so on. It must also include a detailed use case justifying its implementation. If you would like to elaborate on your proposal, please modify your post above. If sufficient detail is not added, this issue will be closed.
