### ISSUE TITLE
 Add NIC chipset, and PCI address at the device type level that will propagate to the device level

### ISSUE THREAD

**Issue by dfitzpatrick128** [netbox-community/netbox#14389]
### NetBox version

v3.4.4

### Feature type

Data model extension

### Proposed functionality

Adding an optional field for NIC chipset, and PCI address at the device type level that will propagate to the device level. We currently do this as custom fields at the device level. It is in my opinion very very laborious to do this when deploying 10s of the same device only to have to repopulate each device with the chipset and pci that is the same. 

Follow up to
https://github.com/netbox-community/netbox/issues/9243
and 
https://github.com/netbox-community/netbox/issues/13540#issuecomment-1691574308

### Use case

We track several additional fields such as NIC chipset, NIC PCIe address, etc that would be well suited to track at the device type level since they are associated with different device models. Currently we have to manually populate those fields each time we create a new device of that device type.

**Comment by dfitzpatrick128** [comment]
If a PR was opened to add this functionality @jeremystretch  would it be struck down/ not allowed? It seems like a small PR

**Comment by jeremystretch** [comment]
> I would also like this proposed functionality!

Please use :+1: and :-1: reactions on issues to vote.

> If a PR was opened to add this functionality @jeremystretch would it be struck down/ not allowed? It seems like a small PR

Per our [contributing guide](https://github.com/netbox-community/netbox/blob/develop/CONTRIBUTING.md#arrow_heading_up-submitting-pull-requests):

> It's very important that you not submit a pull request until a relevant issue has been opened and assigned to you. Otherwise, you risk wasting time on work that may ultimately not be needed.

@dfitzpatrick128 please add more detail to your FR, as it's not actionable in its current form. You propose the addition of new database fields yet don't list anything under "database changes." Please also describe the intended replication behavior as it's not clear from your description above.

**Comment by bitcollector1** [comment]
I'm currently using the label to denote the PCI BUS address for our server interfaces, but an official place holder would be welcomed by me.  

We also track things like drivers and firmware levels for all these server interfaces, so that would also be welcomed, currently we track a bunch of things in custom fields or tag it in inventory.

**Comment by jeremystretch** [comment]
This issue is being closed as no further information has been provided. If you would like to revisit this topic, please first modify your original post to include all the requested detail, and then ask that the issue be reopened.
