### ISSUE TITLE
Unable to trigger a webhook via script execution

### ISSUE THREAD

**Issue by jeremystretch** [netbox-community/netbox#14382]
### NetBox version

v3.6.5

### Python version

3.10

### Steps to Reproduce

1. Upload a simple script that executes cleanly. (It doesn't have to do anything.)
2. Create a webhook.
    * Content types: Extras > Script
    * Events: Job executions, job terminations
    * URL: Where you have a receiver running (can use the `webhook_receiver` management command locally)
3. Ensure the RQ worker process is running.
4. Run the script you uploaded and verify that it completes successfully.

### Expected Behavior

Two webhooks should be sent: One when the script starts, and another when it ends.

### Observed Behavior

The webhook is not triggered for either event. This is because the content type with which the webhook is associated (`extras.Script`) differs from the job's object type (`extras.ScriptModule`). This can be confirmed by inspecting the completed job under operations > jobs.

**Comment by jeremystretch** [comment]
Blocked by #14438

**Comment by jeremystretch** [comment]
Unblocking this as #14438 has been completed for the upcoming v4.0 release.

**Comment by arthanson** [comment]
This is fixed in NB 4.0 due to the changes in #14438 so closing.  Tested in NB 4, webhooks are successfully sent.
