### ISSUE TITLE
Admin panel bulk operations are broken

### ISSUE THREAD

**Issue by abhi1693** [netbox-community/netbox#14392]
### NetBox version

v3.6.6

### Python version

3.10

### Steps to Reproduce

1. Navigate to your admin panel at `/admin`
2. Create a nonce object (values do not matter) at `/admin/social_django/nonce/`
3. From the list page, try to perform a bulk operation on the selected (1 or many) objects

### Expected Behavior

The bulk operation should not crash

### Observed Behavior

Log:

```
<class 'ValueError'>

Field 'id' expected a number but got ''.

Python version: 3.8.10
NetBox version: 3.6.6
Plugins: 
  netbox_demo: 0.3.1
```

This issue was first seen at https://github.com/Onemind-Services-LLC/netbox-secrets/issues/106 and the temporary fix can be implemented by any plugin developer. However, this will not fix other admin models registered on the backend like `django-social-auth`.

The issue was due to the implementation of https://github.com/netbox-community/netbox/pull/13963

Here is a potential fix if this issue is not resolved within the core for other plugin developers: https://github.com/Onemind-Services-LLC/netbox-secrets/commit/768fc16474e7e97860b1c36a70ee7748f1c81ee6

**Comment by kkthxbye-code** [comment]
See also: https://github.com/mattieserver/netbox-topology-views/issues/407

The clean fix for plugin authors is to just revert back to the normal form renderer:

https://github.com/mattieserver/netbox-topology-views/pull/408/files
