### ISSUE TITLE
Add the ability to see images assigned to subobjects

### ISSUE THREAD

**Issue by drobnymichal** [netbox-community/netbox#14411]
### NetBox version

v3.6.5

### Feature type

New functionality

### Proposed functionality

We would like to add the ability to view images assigned to subobjects. For example, view all images assigned to Devices within a single Rack or Location.

At the moment I can only think of one way and that is to define different queries depending on what device it would be. The downside of this solution would be that it would not be generic.

Next, I can think of building some new filter for Image Attachment type objects.

I would be happy to open a discussion over this topic.

### Use case

In our organization, we use images to provide detailed documentation of the condition of equipment. We encounter situations where we would like to see pictures of all the equipment in one room or rack, for example.

### Database changes

None

### External dependencies

None

**Comment by jeremystretch** [comment]
Thank you for your interest in extending NetBox. Unfortunately, the information you have provided does not constitute an actionable feature request. Per our [contributing guide](https://github.com/netbox-community/netbox/blob/develop/CONTRIBUTING.md), a feature request must include a thorough description of the proposed functionality, including any database changes, new views or API endpoints, and so on. It must also include a detailed use case justifying its implementation. If you would like to elaborate on your proposal, please modify your post above. If sufficient detail is not added, this issue will be closed.

**Comment by tippenring** [comment]
I just came here to look if this feature request was already submitted. To add details from my perspective, here's an example use case. I have switch A in rack B in location C at site D. If switch A has an image attached, that image should show up in the available images for the object rack B, location C, and site D. Ideally each image line item would include the path to the object to which it is attached with URL as well.

**Comment by jeremystretch** [comment]
I think what people are after here is a mechanism to view arbitrary sets of image attachments irrespective of their direct parent object. This would entail introducing a new dedicated list view for image attachments and filters to query by ancestor objects (e.g. rack, location, site).

However, I see limited utility in listing _all_ images attached to descendant objects under the site view. This could potentially be hundreds or thousands of images across many locations, racks, etc. with no convenient mechanism to narrow them down.

**Comment by tippenring** [comment]
> I see limited utility in listing all images attached to descendant objects under the site view. This could potentially be hundreds or thousands of images across many locations, racks, etc.

True. Showing all child images under site does not scale well. However, trying to locate an image attached to a device in a rack in a location at a site is not user friendly due to the number of pages a user must click through to locate the desired image(s). 

I'm not sure there is a one-size-fits-all solution here. In my use case, showing all child object images scales nicely. Perhaps adding a preference option to list child objects with attached images?
