### ISSUE TITLE
Provide documentation explaining what fields should be used for (their purpose)

### ISSUE THREAD

**Issue by jwbensley** [netbox-community/netbox#14417]
### Change Type

Addition

### Area

Features

### Proposed Changes

As I pointed out in this issue: https://github.com/netbox-community/netbox/issues/13027
Lots of people have opened issues over the years requesting field lengths be extended.
My issues was because of the facility name being too short, which resulted in this dedicated sub-issue being opened: https://github.com/netbox-community/netbox/issues/13316

My parent and sub-issue were both closed because they are examples (according to Jeremy) of how data should not be modelled in NetBox, abusing the fields/data model. This also applies to the various issues I linked to in 13027, lots of them were closed due to incorrect use of the NetBox data model in Jeremy's eyes.

It's fine to close tickets with this reason, **if** the purpose of these fields/the correct usage of these fields, is actually documented somewhere, which it isn't.

If you want users to store specific information and specific fields, and use that as a valid reason to close issues, you need to document how the fields should be used.

I still have the problem that I have facilities with a name longer than 50 characters and I can't store this in NetBox. It's a totally legit request that was denied. But it also applies to many other fields too. So I think we need documentation so that we don't waste time opening more GitHub issues.

**Comment by jeremystretch** [comment]
As @Chiniquy points out, the specific purpose of each model field is already well documented. It appears that your only motivation for opening this issue is to complain about other issues being closed, so it too is being closed.

NetBox is open source software. If you disagree with the decisions of its maintainers, you have complete freedom to modify it as you see fit.
