### ISSUE TITLE
Interface Description not copied from Device Type template to new Device

### ISSUE THREAD

**Issue by dreng** [netbox-community/netbox#14453]
### NetBox version

v3.6.6

### Python version

3.11

### Steps to Reproduce

1. Create new Device Type
2. Create Interface within new Device Type and enter a Description
3. Create new Device based on the previously created Device Type
4. Click the Interfaces tab and have a look at the Interface that's been created from the template

### Expected Behavior

The Interface should have a description like defined in the template.

### Observed Behavior

Description value is missing for the Interface.

**Comment by jeremystretch** [comment]
This is expected behavior. Please see issue #13540 for further discussion.

**Comment by dreng** [comment]
I searched for a similar bug report but didn't find #13540. So nevermind, thank you for the clarification and sorry for the extra work.
