### ISSUE TITLE
Reset dashboard for a selection or all users

### ISSUE THREAD

**Issue by YoucefYousfi** [netbox-community/netbox#14460]
### NetBox version

v3.6.1

### Feature type

Change to existing functionality

### Proposed functionality

Currently, modifying the default dashboard doesn't take effect for any user that has viewed the dashboard previously. If there is a change on the configuration for the default dashboard, the only way to view it is to reset the dashboard. It would be nice as an admin to have the ability to force reset the dashboard of a selection or all users. By default, users who made changes to their dashboard could be ignored by this reset.

### Use case

Without any user interaction, users could take benefit of a default dashboard change. It may be hard to push all users to reset their dashboard when there are a lot of users, and that is for each default dashboard change.

More specifically, this would also allow admins to display things on the dashboard that can dynamically change, though it would probably require for the default dashboard to be editable without restarting Netbox for this specific use case.

**Comment by ITJamie** [comment]
One alternative: "saved" dashboards with a dropdown choice list, With the default being available and customised ones. 
So when a user saves their dashboard they would get the option of naming it and possibly making it "public" for other users. 

This way the "default" dashboard would become a starting point but always be available. People who choose to use the default dashboard would always get the uptodate copy.

**Comment by wriedel** [comment]
Hi Folks,
just wonder if there is a way to export a dashboard so I can make it the default dashbord ?
I have invested lots of effort in getting a dashboard right for our environment and would like to share it with others.
Maybe an admin could share it and make it available as a "public" dashboard?
It's solved nicely within LibreNMS where I can choose to keep it privat or make it public. The public dashboard name is just prefixed with the username.
