### ISSUE TITLE
Show existing and new connections

### ISSUE THREAD

**Issue by Projects0987** [netbox-community/netbox#14475]
### NetBox version

3.6.6

### Feature type

New functionality

### Proposed functionality

The ability to have on an interface a new (purposed) connection so that it can show a connection to a new interface on a future moved,

### Use case

If moving connections on a future project/move you can show on an interface the new connection.  For example there is a connection from Device A - Device B and there is plans to move the connection on Device A to Device C.  This would a an option similar to a virtual interface but can create a connection showing that it a planned/new connection.  This would show up under the existing connection.

### Database changes

Add to an interface the ability to create a planned connection under the existing connection.

**Comment by jeffgdotorg** [comment]
Thanks for your request to add new functionality to NetBox. The *proposed functionality* section of your issue appears to be cut off, did you mean to write more?

The idea of a “connection in waiting” has clear value in networks that see regular changes. When gamed out, though, it appears at risk of blossoming into a major engineering project. It seems the network model in NetBox would need to be versioned much like a source control repository. That is a beautiful dream, but probably somewhat impractical.

If this assessment is off base, please update your issue to clarify the scope of your vision for the requested functionality.

**Comment by Projects0987** [comment]
Sorry to make the proposed not fully clear.  Right now you can create a child interface but it is only a virtual interface.  What I'm proposing is the ability to add a something like a child interface but it be able to make a connection from that "child interface" to either another "child interface" or just a normal interface and have it marked as planed.  Hope this makes it clearer.

**Comment by PieterL75** [comment]
I thought I once submitted a similar FR, but can't find it anymore. 

My proposal would be to allow 2 cables to one interface.
Only one can be in connected state, the other should be in planned or decommissioning state.
That way, you don't need to create temp interfaces and rename them.

**Comment by jeremystretch** [comment]
> My proposal would be to allow 2 cables to one interface.

This would be in stark violation of a guiding tenet: Model the real world. Not to mention it would be incredibly complex to validate, and offers no additional potential between two possible states.

What this FR boils down to is attempting to track multiple states in parallel, which is not something that NetBox currently supports. Although it's something we may explore in the future, this is a much, _much_ broader topic than the representation of cables. I'm going to close this out as something that we're not currently able to support.
