### ISSUE TITLE
custom field with UI-Editable is hidden shown when editing an object

### ISSUE THREAD

**Issue by whtkam** [netbox-community/netbox#14472]
### Deployment Type

Self-hosted

### NetBox Version

v3.7-beta1

### Python Version

3.8

### Steps to Reproduce

When editing an object, a custom field appears with the UI Editable option set to Hidden
![nbox](https://github.com/netbox-community/netbox/assets/89918174/2bdf5aa3-a640-4925-ac24-15c0b2d8e9d1)

### Expected Behavior

The field should not be displayed when editing an object

### Observed Behavior

no

**Comment by jeremystretch** [comment]
Thanks for the report!
