### ISSUE TITLE
Make error highlighting across custom field and custom validator consistent

### ISSUE THREAD

**Issue by dejantep** [netbox-community/netbox#14478]
### NetBox version

v3.5.7

### Feature type

Change to existing functionality

### Proposed functionality

When setting custom field to "required" its functionality appears as red frame around field which is easy to spot but no text message. This is also the case with Netbox native required fields.

When using custom vaildator to "required: true" it appears as red text below actual object. Allthough message is clear it can be hard to spot.

### Use case

Netbox and its users would benefit from consistency in how this type of messages are handled.  I would like to see red frame around field and error message like "field is required" or similar
Another option would be to display popup/modal.

### Database changes

No changes as far as i know

### External dependencies

probably none. It seems as everything is in place just needs rework

**Comment by ITJamie** [comment]
we have had a few users say this. on our device model we have a lot of custom fields (45) and if validation fails on one it isn't obvious as to why save hasn't worked as there's no popup but a custom field offscreen now has a red border.

**Comment by dejantep** [comment]
There is also an issue if you are doing bulk edits, let's say 3 ip addresses, and use custom validation. then you get popup warning at the bottom right sof the screen saying "This field must not be empty" or similar but no indication about which field.

**Comment by ITJamie** [comment]
Id be willing to take a go at this if the issue could be assigned to me?

**Comment by jeremystretch** [comment]
@ITJamie I've assigned this to you. Be sure to work off of the current `feature` branch as the entire UI (and much of the forms) have been refreshed for the upcoming v4.0 release.

**Comment by ITJamie** [comment]
I think this might be solved in 4.0
it now scrolls up to the field which hasn't been filled in

from my POV that has solved my issue with this.

**Comment by jeremystretch** [comment]
Closing this out as likely resolved in v4.0.
