### ISSUE TITLE
Cannot move primary IP from device to VM or vice versa

### ISSUE THREAD

**Issue by devon-mar** [netbox-community/netbox#14482]
### Deployment Type

Self-hosted

### NetBox Version

v3.6.6

### Python Version

3.8

### Steps to Reproduce

1. Add an IP to a device and set it as the device's primary IP address
2. On a VM interface, assign the IP from step 1 and check "Make this the primary IP for the device/VM"
3. On save, a `ValueError` is raised

This bug also works the other way around (VM to Device).

### Expected Behavior

The IP address should be assigned to the VM interface.

### Observed Behavior

```
<class 'ValueError'>

'IPAddressForm' has no field named 'assigned_object'.

Python version: 3.8.10
NetBox version: 3.6.6
Plugins: 
  netbox_demo: 0.3.1
```

**Comment by jeremystretch** [comment]
To be clear, moving the primary IP for a device/VM is *not* supported. However, attempting to do so should return a validation error rather than raise an exception.
