### ISSUE TITLE
beta 3.7: VPN IKE Proposal : LocalID missing

### ISSUE THREAD

**Issue by PieterL75** [netbox-community/netbox#14486]
### Deployment Type

Self-hosted

### NetBox Version

v3.7-beta1

### Python Version

3.8

### Steps to Reproduce

1. Create a VPN IKE Proposal

### Expected Behavior

Ability to document the LocalID
![image](https://github.com/netbox-community/netbox/assets/74899468/347bc66a-ade9-47cf-a5be-62a14d9d97ae)

### Observed Behavior

the LocalID field is missing.
This can be a free-text form, as a lot of possible LocalID's are possible (fqdn, IP, free text)

**Comment by jeremystretch** [comment]
Please resubmit this as a [feature request](https://github.com/netbox-community/netbox/issues/new?assignees=&labels=type%3A+feature&projects=&template=feature_request.yaml).
