### ISSUE TITLE
Ability to 'hide' fields from models

### ISSUE THREAD

**Issue by PieterL75** [netbox-community/netbox#14481]
### NetBox version

v3.6.6

### Feature type

Data model extension

### Proposed functionality

My proposal is providing an ability to hide (non-required) fields from the view, table and editform of a model.
This could be done through settings on the configuration.py, or even better through the admin module.

### Use case

As netbox grows, more and more field are added to the models. 
Most of them have a very generic purpose, and are relevant.
Other are very specific for certain use cases or data modeling and not relevant to oher.
For ex, the GPS coordinates in devices. We don't use those, as all of our gear is in a datacenter with racks.

New FR like https://github.com/netbox-community/netbox/issues/14389 add extra fields to models.
Having that many fields confuses users and are not helping to make the editform shorter and quicker to fill in.

### Database changes

Extra table that keeps track of what fields should be enabled for what models

**Comment by jeremystretch** [comment]
I'm sorry, but the development and maintenance burden to support something like this _far_ exceeds any perceived value, so this is going to be a "no." If you have no use for certain fields, simply don't use them. NetBox is a highly customizable tool, but we have to draw the line somewhere, and this is it.

If you _really_ need to remove core fields for some reason, you'll need to fork the code base yourself to make (and be responsible for) those changes.
