### ISSUE TITLE
Report Page has broken image

### ISSUE THREAD

**Issue by dionrowney** [netbox-community/netbox#14480]
### Change Type

Correction

### Area

Administration

### Proposed Changes

On the following page:

https://netbox.exotec.com/static/docs/customization/reports/

In the "Running Reports" section where the docs say "To run a report, a user must be assigned the extras.run_report permission" and there appears to be an image clarifying how to do this that is missing and is a broken link to the image.

I was having troubles getting this run report button to appear for users and feel this pic has the key to the solution (or there is another bug)

**Comment by abhi1693** [comment]
You are running a very old version of NetBox. This issue is not present in v3.6.6.

**Comment by dionrowney** [comment]
Sorry, I thought I was looking at netbox official docs but the the url was someone elses docs (exotec?).  Apologies.  see it now.  thanks
