### ISSUE TITLE
beta 3.7: global search Attribute badge

### ISSUE THREAD

**Issue by PieterL75** [netbox-community/netbox#14484]
### Deployment Type

Self-hosted

### NetBox Version

v3.7-beta1

### Python Version

3.8

### Steps to Reproduce

1. Search something in the global search
2. results are returned with extra info

### Expected Behavior

Extra results.

### Observed Behavior

The extra info that is returned is a real added value to the global search.
The only minor issue, is they are colored gray, and taking all the focus on the search result.
![image](https://github.com/netbox-community/netbox/assets/74899468/15fe4031-937d-4e65-8984-3121686109a8)
My eyes keep going to the big gray field, in stead of the actual results

Can those results have the same color as the rest of the page ?

**Comment by jeremystretch** [comment]
This is the third instance where you've submitted a bug report for something that is clearly a request for a new feature or enhancement. Bug reports are for reporting unintended behavior; the attributes are being rendered as intended. If you would like to propose a specific improvement, please open a [feature request](https://github.com/netbox-community/netbox/issues/new?assignees=&labels=type%3A+feature&projects=&template=feature_request.yaml) detailing your proposal.

**Comment by PieterL75** [comment]
My sincere apologies for not selecting the proper form when reporting back on beta testing
As this is beta, a bugreport seemed good enough to me.

Just take my reports into account. I'm not going to create a new FR for this
