### ISSUE TITLE
beta 3.7: VPN proposal algorithm list - customizable

### ISSUE THREAD

**Issue by PieterL75** [netbox-community/netbox#14485]
### Deployment Type

Self-hosted

### NetBox Version

v3.7-beta1

### Python Version

3.8

### Steps to Reproduce

1. create a new IKE Proposal

### Expected Behavior

Ability to select the algorithms available on the firewall

### Observed Behavior

Only a limited set of proposals is selectable from the dropdown.
Firewalls have a lot of algorithms that are no part of the dropdown, and the posibility exists that new FR's are raised to add the new proposals.
Ne proposal types are added frequently, while others are deprecated, or even not allowed to be used by the company.

It would be easier of the list can be editable though something like "FieldChoices set", like the CustomFieldChoices.

**Comment by jeremystretch** [comment]
If you would like to propose the addition of a new cryptographic or authentication algorithm, please use a [feature request](https://github.com/netbox-community/netbox/issues/new?assignees=&labels=type%3A+feature&projects=&template=feature_request.yaml) to do so. When doing so, be sure to cite the standardized name and publicly-available documentation for the proposed addition(s).
