### ISSUE TITLE
VPN PFS Group - None is missing

### ISSUE THREAD

**Issue by PieterL75** [netbox-community/netbox#14487]
### Deployment Type

Self-hosted

### NetBox Version

v3.7-beta1

### Python Version

3.8

### Steps to Reproduce

1. Create an IKE or IPSec policy
2. set PFS to 'None'

### Expected Behavior

None is not a valid option.

### Observed Behavior

PFS is not always configured and then set to None. The dashes do not reflect that properly.

**Comment by jeremystretch** [comment]
> 1. Create an IKE or IPSec policy

Which is it? PFS group applies only to IPSec policies.

> PFS is not always configured and then set to None.

In which case, the field is left null. What specifically do you believe warrants a bug report?

**Comment by PieterL75** [comment]
Leaving it blank is not specific enough. Having 'None' in there, really shows that there was no oversight in selecting the group.
You have DH in IPSec PFS DH GRoup and also in IKE DH Groups

**Comment by jeremystretch** [comment]
Agree with @DanSheps; this is standard convention across the entire application.
