### ISSUE TITLE
2 locations with the same prefix and IPs are not separated.

### ISSUE THREAD

**Issue by LHBL2003** [netbox-community/netbox#14492]
### Deployment Type

Self-hosted

### NetBox Version

v3.6.6

### Python Version

3.8

### Steps to Reproduce

Create 2 Idenic subnets at two locations (e.g. for guest WLAN)

![image](https://github.com/netbox-community/netbox/assets/46369917/475dcf7f-1473-4db5-a863-89db54002606)

Create an IP in the first prefix
![image](https://github.com/netbox-community/netbox/assets/46369917/8dbc7db5-e632-42df-a8cb-1d27db136b90)

Refresh the view for the second prefix
![image](https://github.com/netbox-community/netbox/assets/46369917/7835fd34-e640-49cb-a450-166e81c8c8f5)

### Expected Behavior

The IP is only available for the first prefix

### Observed Behavior

The IP address is displayed in both prefixes, although this was only created for the first prefix.

**Comment by ITJamie** [comment]
theres no vrf assigned in this example so both prefixes are considered to be in the global vrf.

**Comment by LHBL2003** [comment]
Oh thank you, now I understand why VRF.
I will also try the configuration parameter tomorrow: ENFORCE_GLOBAL_UNIQUE tomorrow. Because I've already had duplicate IPs a few times that I didn't want :)

Thank you, I've learnt something new

**Comment by LHBL2003** [comment]
@ITJamie 

Does it make sense to create a VRF entry for each location and to set the VRF of the location in each prefix?

If I have a WiFi network at each location, which is always set up in the same way, should I set the VRF prefix to Global so that I don't have to create the same prefix x times, or would it be better to define the prefix for each location?

What is your experience with this?

**Comment by DanSheps** [comment]
Unfortunately this is 100% indended.

Our current data model does not take into account actual physical location of the prefix and only assigns a prefix to an IP based on the VRF (or lack of VRF) and prefix match.

I personally would like to see the IP address <> prefix link be made explicit (assigned and not derived) as you could allow for these unique circumstances.

**Comment by LHBL2003** [comment]
@DanSheps 

So I understand that VFR is a workaround in my case. Because VFR is actually (basic idea like VLAN) intended for the virtual separation of routers. And not to map individual firewalls (routers) in the company, where there are identical segments that are not routed.

**Comment by jeremystretch** [comment]
A [VRF](https://en.wikipedia.org/wiki/Virtual_routing_and_forwarding) is essentially an isolated routing domain, _roughly_ similar in concept to a VLAN at layer two. It's not a workaround; it's how multiple L3 forwarding tables are maintained across an IP network. If you'd like to discuss your options further, please open a [discussion](https://github.com/netbox-community/netbox/discussions/new/choose).

As the behavior described above is expected, I'm going to close this bug report.
