### ISSUE TITLE
Print NetBox version when running upgrade.sh

### ISSUE THREAD

**Issue by markkuleinio** [netbox-community/netbox#14507]
### NetBox version

v3.7-beta1

### Feature type

New functionality

### Proposed functionality

When running upgrade.sh it would be beneficial to see what is the actual NetBox version that is being prepared. 

Something like

```
echo "NetBox version is $(grep ^VERSION netbox/netbox/settings.py | cut -d\' -f2)"
NetBox version is 3.7-beta1
```

would maybe be enough somewhere in the beginning of upgrade.sh.

### Use case

Sometimes there is confusion when symlinking or pulling the versions here and there and running upgrade.sh, what is the actual codebase that is being activated.

### Database changes

None

### External dependencies

None

**Comment by DanSheps** [comment]
I would add, it might be wise too break until there is input after that (unless running non-interactively).

**Comment by markkuleinio** [comment]
I can submit the PR. I can add the pause in interactive mode (let's discuss in the PR if something needs adjusting).
