### ISSUE TITLE
Add status attribute in the search results for devices

### ISSUE THREAD

**Issue by markkuleinio** [netbox-community/netbox#14503]
### NetBox version

V3.7-beta1

### Feature type

Change to existing functionality

### Proposed functionality

Currently (in the new search result list of v3.7-beta1) the following fields/attributes are shown for devices that are shown in search results:

'site', 'location', 'rack', 'device_type', 'role', 'tenant', 'platform', 'serial', 'asset_tag', 'description',

I propose adding status field there as well, preferably somewhere near the beginning of the list.

### Use case

When search results are shown it is important to see which devices (if any) are active and which are decommissioning etc.

### Database changes

None

### External dependencies

None (as far as I understand)

**Comment by jeremystretch** [comment]
It's probably worth doing a full audit across all models to identify any other fields that were omitted in error.

**Comment by sleepinggenius2** [comment]
Would it be possible to make these lists configurable, maybe like we can do for choice sets today? For example, I can think of scenarios within our deployment where it would be nice to include particular custom fields in the display attributes on search results.
