### ISSUE TITLE
Bring back power feed utilisation graph to rack view

### ISSUE THREAD

**Issue by cpmills1975** [netbox-community/netbox#14518]
### NetBox version

v3.6.6

### Feature type

Change to existing functionality

### Proposed functionality

The rack view used to show power feeds in a panel complete with a utilisation graph for each individual feed. While the overall power capacity is still shown, since the removal of this panel it is difficult to see whether the power utilisation is unbalanced between feeds in a rack.

I'd like to propose that the utilisation graph is made available in the power feeds list view. This would be included by default when viewing the filtered power feeds list reached through the 'related objects' link on the rack view.

### Use case

I have a custom script which retrieves live(ish) power consumption statistics from my power management system and populates the power allocation field in the connected power ports. This information informs the power feed utilisation and allows me to see whether individual PDUs in a rack are balanced. More importantly, seeing the individual utilisation helps me ensure I'm not overloading one feed while under loading another - at present all I'd see is that the power availability on the rack is safely within parameters.

### Database changes

None

### External dependencies

None

**Comment by RichZad** [comment]
This function existed in 3.2.9 .   Why was it removed?
This is critical to managing a robust data center operation.

**Comment by jeremystretch** [comment]
>  Why was it removed?

IIRC there were several issues with utilization being reported inaccurately.
