### ISSUE TITLE
Sort "Related Objects" Pane

### ISSUE THREAD

**Issue by DCAuto** [netbox-community/netbox#14510]
### NetBox version

v3.6.6

### Feature type

Change to existing functionality

### Proposed functionality

Request to sort the "related object" types when viewing an object. Either by name or number of occurrences.

e.g.
When viewing a tenant the Related Object Pane lists object types without order:
"""
Sites —
Racks —
Rack Reservations —
Locations —
Devices —
Virtual Device Contexts 
...
"""

It is not super intuitive to find the related object you are looking for.

### Use case

This is mainly a housekeeping request. This would make locating the related object more intuitive.

**Comment by abhi1693** [comment]
This was implemented in https://github.com/netbox-community/netbox/pull/14196, however, it looks like we need to take another look to ensure this is consistently implemented.

**Comment by jeremystretch** [comment]
Related objects are ordered alphabetically by name in v3.7-beta1.
