### ISSUE TITLE
Bring back 'Add Reservation' to rack view

### ISSUE THREAD

**Issue by cpmills1975** [netbox-community/netbox#14517]
### NetBox version

v3.6.6

### Feature type

Data model extension

### Proposed functionality

In older versions of NetBox, when reservations were shown in a panel on the rack page, adding a new reservation to the rack was a one-click action.

Since this panel was removed, there is, as far as I can see, no quick way to add a reservation to a rack from the rack view and the only option appears to create a new reservation though the reservations list.

The gold plated solution would be to allow reservations to be created by clicking on a rack U space and selecting either add reservation or add device, but _a_ solution would also be to add a button to the control group at the top of the page, but this runs the risk of cluttering the control group too much.

### Use case

I routinely plan new installation work by creating reservations and linking them to my ticketing system. Sometime before 3.6, the single click action to add a reservation was removed. This FR seeks to bring that back, perhaps in a better way.

### Database changes

None

### External dependencies

None.

**Comment by bitcollector1** [comment]
What would REALLY be awesome is if you could reserve devices!

**Comment by jeremystretch** [comment]
This is a bug. The reservations list was moved to a separate tab under the rack view, but the tab doesn't show up unless at least one reservation exists already.

**Comment by dionrowney** [comment]
I also am intuitively wanting it to be in the rack unit visualization like cpmills1975 wants as his gold plated solution: 
"... to allow reservations to be created by clicking on a rack U space and selecting either add reservation"  Can this be added as a longer term feature request please?
