### ISSUE TITLE
Deleting connected Interface leaves Server Error-prone Cable behind

### ISSUE THREAD

**Issue by koratfood** [netbox-community/netbox#14527]
### Deployment Type

Self-hosted

### NetBox Version

v3.6.6

### Python Version

3.10

### Steps to Reproduce

1. Create two devices (e.g.: DevA and DevB, of any Device Type and at any Location you want)
2. Add an interface (name: "TestInt", type: 1GE) to each of the devices you created
3. Connect a cable between testint on DevA and testint on DevB
4. Delete interface TestInt on DevB
5. Attempt to edit the still-existing Cable object on DevA

### Expected Behavior

If the Cable object's continued existence in NetBox is even justifiable past reproduction step no. 4, the Cable should remain editable so that the user can reterminate it. Alternatively, there should at the very least be a proper error message telling the user why it is not, and what to do about it.

### Observed Behavior

![Screenshot_20231214_202036](https://github.com/netbox-community/netbox/assets/64777963/69f8ac5c-9257-4651-9857-6b59680bccb0)

**Comment by jeremystretch** [comment]
Thank you for submitting this issue, however it appears that this topic has already been raised. Please see issue #11460 for further discussion.
