### ISSUE TITLE
Front/rear port additions

### ISSUE THREAD

**Issue by bobisaperson1** [netbox-community/netbox#14531]
### NetBox version

v3.6.6

### Feature type

Change to existing functionality

### Proposed functionality

Add all port types from existing options from other components selections (Power outlet, console ports, interfaces etc)

### Use case

Can be used to model modular patch panels, that have more than just ethernet and/or fibre connections, such as PowerCON or USB.
![image](https://github.com/netbox-community/netbox/assets/43870324/7e81ac2a-57f1-4895-8740-314f7202bc43)

**Comment by jeremystretch** [comment]
These all exist as separate models for good reason. Please consult [NetBox's documentation](https://docs.netbox.dev/en/stable/features/devices-cabling/) for details on how each type of component is used.
