### ISSUE TITLE
Wireless links: one to many interface support

### ISSUE THREAD

**Issue by jdreichmann** [netbox-community/netbox#14537]
### NetBox version

v3.6.6

### Feature type

Change to existing functionality

### Proposed functionality

Currently, wireless interfaces can only be connected using wireless links which are 1:1. The proposal is to change this to 1:n, where a wireless interface with "Access point" status can be connected with many interfaces which have a (new?) type of "Client".

(see https://demo.netbox.dev/static/docs/core-functionality/wireless/#wireless-links "A wireless link represents a connection between exactly two wireless interfaces")

### Use case

This allows modelling "those devices are connected to this wifi/access point".

**Comment by jeremystretch** [comment]
This seems like it would be covered by #9641, so I'm going to close this out as a duplicate. @jdreichmann please feel free to tack on any of your additional requirements or considerations to the other issue.
