### ISSUE TITLE
Using a custom LOGIN_URL for SSO

### ISSUE THREAD

**Issue by CTV-2023** [netbox-community/netbox#14540]
### NetBox version

v3.6.6

### Feature type

New functionality

### Proposed functionality

Hi,

Following this discussion https://github.com/netbox-community/netbox/discussions/14535

Provide a configuration option to modify the default login behaviour to redirect to a specific login by default while still maintaining the ability to access the old login via manually typing in the login URL or through other means (dropdown from the login button, etc)
Note : as saml logs user automatically, the login button won't be used, the login url might be easier

### Use case

In our organization, we only use SSO for authentication to NetBox and would prefer for our users to be redirected directly to the SSO login page automatically to prevent attempts to login without SSO 

### Database changes

None I think

### External dependencies

None I think

**Comment by DanSheps** [comment]
> Hi,
> 
> Following this discussion #14535
> 
> I have a use case where my lazy users would like to be authenticated with SSO without the need to click on the link below "Or use a single sign-on (SSO) provider:".
> 
> For instance, it would be cool to be able to have a specific login page using the SSO /oauth/login/saml/?idp=MY-IDP
> 
> I understand from previous discussions you don't want to hide or disable the default login page : either by adding a specific parameter "?redirect=0" or by having 2 possible login pages

I am going to edit your proposal to make it more clear, and I am going to change from the above to:

"Provide a configuration option to modify the default login behaviour to redirect to a specific login by default while still maintaining the ability to access the old login via manually typing in the login URL or through other means (dropdown from the login button, etc)"

> ### Use case
> Automatic connection of users using SSO.

Likewisie, you should change this to:

"In our organization, we only use SSO for authentication to NetBox and would prefer for our users to be redirected directly to the SSO login page automatically".

**Comment by llamafilm** [comment]
It looks like there is already a PR for this: #13003.

**Comment by CTV-2023** [comment]
> It looks like there is already a PR for this: #13003.

Which might not work, see https://github.com/netbox-community/netbox/discussions/14535

**Comment by benley** [comment]
I'd like to see this implemented at some point, please don't auto-close the ticket.
