### ISSUE TITLE
Allow duplicate device names based on cluster.

### ISSUE THREAD

**Issue by emersonfelipesp** [netbox-community/netbox#14546]
### NetBox version

v3.6.7

### Feature type

Change to existing functionality

### Proposed functionality

Currently device names can be duplicated if its on different **Site** or **Tenants**. I would like to propose the same "allow duplicate" behavior, but based on the **Cluster** field only (not needing to fill Site or Tenants field).

### Lets consider this scenario:

![netbox_duplicate_device_names drawio](https://github.com/netbox-community/netbox/assets/24397251/0048794c-2862-4c66-a2d4-e95090779b23)

On my hypervisor, I have different Clusters that shares the same Nodes names as described on the image, but **both clusters resides on the same physical site building.** (I separated it on different racks just to illustrate)

### My current workaround is to add "fictional" site like this:

| Site | Cluster | Device |
|-----|---------|---------|
| Site A | Cluster A | Node A |
| Site B | Cluster B | Node A |

- The **Site B** was created just to allow **duplicated device names**

### But on on my scenario, the solution should be:

| Site | Cluster | Device |
|-----|---------|---------|
| Building A | Cluster A | Node A |
| Building A | Cluster B | Node A |

- Where the differentiation to allow duplicate device name is now based on the Cluster, not the Site.

**Comment by jeremystretch** [comment]
I'm going to decline this change as the designation of a device as a cluster host should not be considered as part of its identifier. (There's also no justification offered above for having duplicate device names within the same site.)
