### ISSUE TITLE
Saved Filter doesn't appear in cable add view

### ISSUE THREAD

**Issue by llamafilm** [netbox-community/netbox#14544]
### Deployment Type

Self-hosted

### NetBox Version

v3.6-2.7.0

### Python Version

3.11

### Steps to Reproduce

1. Create a saved filter with type "DCIM Device" and parameters `{"location_id": ["5"]}`
2. Select a device interface and try to connect it
3. On the "add a new cable" page, open the selector dialog

### Expected Behavior

I should be able to see the saved filter

### Observed Behavior

I see an empty list.

If I uncheck and re-check the saved filter section then it works, as shown in this video.

https://github.com/netbox-community/netbox/assets/3991046/08ab875c-6d04-446f-9bd1-b9f4e8ae80e6

**Comment by DanSheps** [comment]
Thank you for opening a bug report. I was unable to reproduce the reported behavior on NetBox v3.6.6. Please re-confirm the reported behavior on the current stable release and adjust your post above as necessary. Remember to provide detailed steps that someone else can follow using a clean installation of NetBox to reproduce the issue. Remember to include the steps taken to create any initial objects or other data.

**Comment by kkthxbye-code** [comment]
> v3.6-2.7.0

That netbox-docker tag can be different versions depending on when the image was pulled. The issue you describe was fixed in 3.6.7 and looking at the video it seems you are not on that version.

For posterity, it was fixed in this PR: https://github.com/netbox-community/netbox/pull/14387

> The typescript change was because of a bug that was also present for the Saved Filter field. If a collapsible field is defaulted to be shown, the list will not populate when opening like it is supposed to, but only when the user starts typing.

**Comment by llamafilm** [comment]
@kkthxbye-code thanks, I thought that version tag was enough.  I don't understand why that tag has 2 different version strings (3.6 and 2.7).  I just updated the docker image to the latest and can confirm it's fixed now.
