### ISSUE TITLE
Job results are not available when executing custom scripts via the runscript command 

### ISSUE THREAD

**Issue by erikastr** [netbox-community/netbox#14549]
### Deployment Type

Self-hosted

### NetBox Version

v3.6.6

### Python Version

3.11

### Steps to Reproduce

1. Create/upload any custom script (e.g. the example script from documentation)
2. Try to execute the script via `runscript` command 
```
/opt/netbox/venv/bin/python /opt/netbox/netbox/manage.py runscript example.NewBranchScript --commit --loglevel debug --data '{"site_name": "testing", "switch_count": 1, "switch_model": 11}'
```

### Expected Behavior

Script is completed and job results are available

### Observed Behavior

Script gets completed, but a KeyError exception gets raised when trying to access the job results
<img width="564" alt="image" src="https://github.com/netbox-community/netbox/assets/87935328/52557547-6fc4-41d0-98f5-83fa8909ce5b">

It seems that an incorrect name tries to get accessed when the script is ran through the `runscript` command, as compared to running the script via the GUI

<img width="1169" alt="image" src="https://github.com/netbox-community/netbox/assets/87935328/1bd7a06d-4a5a-4899-ade3-1ca7ada8277f">

**Comment by jeffgdotorg** [comment]
Thanks for your report. The team will get to work on it as capacity allows.

**Comment by kprince28** [comment]
Can anyone please assign this to me ?
