### ISSUE TITLE
Extend VLAN group scoping to include device purpose

### ISSUE THREAD

**Issue by moffitj** [netbox-community/netbox#14563]
### NetBox version

3.6.6

### Feature type

Data model extension

### Proposed functionality

The VLAN group scoping should be extended to include purpose in addition to physical location.

The current model of VLAN scoping assumes that a VLAN is only present at a single geographic location, and that devices at any site all share the same responsibilities.

### Use case

At Site A, I have OOB devices, Metro ethernet devices with S, C, and T tags, Internet VLANs, and internal VLANs. All of these network have VLANs that at least potentially overlap.

It seems like the only way to scope these devices correctly is to create a bunch of sites:
Site A - OOB
Site A - Metro S
Site A - Metro C
...etc.

I'd like to be able to scope a VLAN group to a purpose rather than a site. I don't know if the tag system could be extended but if I could scope a VLAN group to all devices with a particular tag, that would be nice. Otherwise a new field analogous to Device Role, like Device Environment/Purpose/Use.

**Comment by jeremystretch** [comment]
Thank you for your interest in extending NetBox. Unfortunately, the information you have provided does not constitute an actionable feature request. Per our [contributing guide](https://github.com/netbox-community/netbox/blob/develop/CONTRIBUTING.md), a feature request must include a thorough description of the proposed functionality, including any database changes, new views or API endpoints, and so on. It must also include a detailed use case justifying its implementation. If you would like to elaborate on your proposal, please modify your post above. If sufficient detail is not added, this issue will be closed.

**Comment by jeremystretch** [comment]
This issue is being closed as no further information has been provided. If you would like to revisit this topic, please first modify your original post to include all the requested detail, and then ask that the issue be reopened.
