### ISSUE TITLE
Usage of exclamation mark (!) in Custom Links not possible

### ISSUE THREAD

**Issue by Azmodeszer** [netbox-community/netbox#14560]
### Deployment Type

Self-hosted

### NetBox Version

3.6.6

### Python Version

3.11

### Steps to Reproduce

1. Set up a Custom Link.
2. Put `https://<IP>/screens/dashboard.html#!/APView/{{ object.interfaces.filter(mac_address__isnull=False).first().mac_address }}` as the Link URL.

Similar to #13011. Also see #14553.

### Expected Behavior

The URL should be rendered with the ! intact.

### Observed Behavior

The ! is encoded as %21, resulting in a broken link.

**Comment by jeremystretch** [comment]
The exclamation mark probably needs to be added to the list of characters excluded from escaping when calling `urllib.parse.quote()`.

**Comment by Azmodeszer** [comment]
I can own this and do the pull request, no problem.
