### ISSUE TITLE
Export current view of IP Addresses

### ISSUE THREAD

**Issue by mburgholte** [netbox-community/netbox#14567]
### Deployment Type

Self-hosted

### NetBox Version

v3.6.7

### Python Version

3.8

### Steps to Reproduce

Tested with demo.netbox.dev
1. Select IPAM -> IP Addresses (on the top Results shows 183)
![image](https://github.com/netbox-community/netbox/assets/28727337/67bc8fdf-4fbb-4943-8769-92786054a20d)
2.  Quick search 172.16  (Results stays on 183)
![image](https://github.com/netbox-community/netbox/assets/28727337/2ced8e52-32a9-49b1-b20c-2e7045f97c22)
4. Export Current view 
![image](https://github.com/netbox-community/netbox/assets/28727337/bd42ed2f-118d-434d-8915-b301556839d2)

### Expected Behavior

Shouldn't it be the case that when filtering by addresses, the number of results is reduced and accordingly the export of the current view only contains the filtered addresses?

### Observed Behavior

When exporting, all addresses are always exported.

**Comment by jsenecal** [comment]
@jeremystretch I could work on that one, I have a good idea how to fix this.

**Comment by arthanson** [comment]
@jsenecal do you still want to pick this one up?

**Comment by jsenecal** [comment]
Hey @arthanson, sorry nobody msgd me when I got it assigned to me and I did not notice nor specifically looked for issues assigned to me. 

I'm not familiar with the new v4 codebase yet however so it may take some time.

**Comment by jeremystretch** [comment]
FWIW I don't _think_ there are any noteworthy changes in v4.0 that would interfere with this work. (The UI changes are primarily cosmetic.)

**Comment by jeffgdotorg** [comment]
Tagging @Julio-Oliveira-Encora so that I can assign him

**Comment by Julio-Oliveira-Encora** [comment]
Could you please assign it to me?
