### ISSUE TITLE
Add oidc to auth backends to clean up the display

### ISSUE THREAD

**Issue by DanSheps** [netbox-community/netbox#14587]
### Proposed Changes

Add:

```
    'oidc': ('OpenID Connect', None),
```

to the `AUTH_BACKEND_ATTRS` in netbox/netbox/authentication.py

### Justification

Currently, the social auth displays the various SSO options under the login page.  This uses the dict "AUTH_BACKEND_ATTRS" to translate the driver name (google-openidconnect for example) to a more user friendly name "Google".

Currently "oidc" is missing from this dict, which is the very basic level of openidconnect and if you need to connect to a non-listed driver when setting up social-auth it simply displays the driver name (oidc) instead of a more user friendly name,

**Comment by llamafilm** [comment]
Can we also have a way to customize the displayed text?  My organization uses a custom identity provider so I'd like to use that name instead of `OpenID Connect`.

<img width="373" alt="Screenshot 2024-01-04 at 1 34 52 PM" src="https://github.com/netbox-community/netbox/assets/3991046/8d0a39a1-9017-427a-bd40-ee75e350b731">

**Comment by llamafilm** [comment]
I would suggest a new config option called `REMOTE_AUTH_NAME` which would apply to any social auth backend, where the user can enter any custom string.  If this option is missing, then use a sane default as @DanSheps described above.

**Comment by llamafilm** [comment]
I made these 2 fixes in my own fork.  I'd be happy to submit a PR if this is accepted.  https://github.com/netbox-community/netbox/compare/develop...llamafilm:netbox:develop

**Comment by DanSheps** [comment]
> I would suggest a new config option called `REMOTE_AUTH_NAME` which would apply to any social auth backend, where the user can enter any custom string. If this option is missing, then use a sane default as @DanSheps described above.

I don't think we would go with "REMOTE_AUTH_NAME" as you could enable more then 1 SSO provider that might be missing details and need to provide data.  It might also be useful to be able to override provided defaults (maintainers will need to discuss)

**Comment by llamafilm** [comment]
How would it be possible to enable more than one SSO provider?  From what I can tell, `REMOTE_AUTH_BACKEND` is a single string?  In my fork I actually called it `REMOTE_AUTH_DISPLAYNAME` for more clarity.

**Comment by EHRETic** [comment]
I'll just upvote the possibility to have a nice OIDC button (same style as normal "sign in" button) with a custom label 😉
