### ISSUE TITLE
SDI Interface Types

### ISSUE THREAD

**Issue by gpmidi** [netbox-community/netbox#14597]
### NetBox version

v3.6.7-ls167

### Feature type

Data model extension

### Proposed functionality

Add new interface types to support various SDI connections for video hardware. Both BNC (coax lines) and SDI-SFP (optical or coax) should be supported for all major speeds (3g, 6g, 12g, and 24g). For instance my [2U VideoHub 40](https://www.blackmagicdesign.com/products/blackmagicvideohub/techspecs/W-VHS-08) has 82 BNC connectors on it for SDI all by itself. 

### Use case

I keep track of a good bit of BlackMagic gear in Netbox. Having connector types beyond "Other" for the hundreds of SDI interfaces I have would be VERY useful. 

### Database changes

Add the following interface choices: 
```python
class InterfaceTypeChoices(ChoiceSet):
   # ...

    # SDI
    TYPE_SDI_BNC_3G = 'sdi-bnc-3g'
    TYPE_SDI_BNC_6G = 'sdi-bnc-6g'
    TYPE_SDI_BNC_12G = 'sdi-bnc-12g'
    TYPE_SDI_BNC_24G = 'sdi-bnc-24g'
    TYPE_SDI_SFP_3G = 'sdi-sfp-3g'
    TYPE_SDI_SFP_6G = 'sdi-sfp-6g'
    TYPE_SDI_SFP_12G = 'sdi-sfp-12g'
    TYPE_SDI_SFP_24G = 'sdi-sfp-24g'
   # ...
   CHOICES = (
   # ...
        (
            _('SDI'),
            (
                (TYPE_SDI_BNC_3G, '3G-SDI (BNC)'),
                (TYPE_SDI_BNC_6G, '6G-SDI (BNC)'),
                (TYPE_SDI_BNC_12G, '12G-SDI (BNC)'),
                (TYPE_SDI_BNC_24G, '24G-SDI (BNC)'),
                (TYPE_SDI_SFP_3G, '3G-SDI (SFP)'),
                (TYPE_SDI_SFP_6G, '6G-SDI (SFP)'),
                (TYPE_SDI_SFP_12G, '12G-SDI (SFP)'),
                (TYPE_SDI_SFP_24G, '24G-SDI (SFP)'),
            )
        ),
   # ...
   )
```

### External dependencies

None

**Comment by gpmidi** [comment]
I have a [basic patch ready for the above](https://github.com/gpmidi/netbox/tree/add-sdi).

**Comment by jeffgdotorg** [comment]
Hi there, and thanks for your proposal to extend the NetBox data model.

We love that people want to use NetBox to model all the things they're passionate about. We're also committed to keeping the core of NetBox tightly focused on IP networking. SDI feels far enough over that line that we hope you'll consider reframing your proposal as [a NetBox plugin](https://docs.netbox.dev/en/stable/plugins/).

If you need help getting started beyond what's in the docs, the [NetDev chat](https://netdev.chat/) may be a good resource.

**Comment by gpmidi** [comment]
@jeffgdotorg I thought, [based on this](https://docs.netbox.dev/en/stable/configuration/data-validation/#field_choices) and [this](https://docs.netbox.dev/en/stable/configuration/data-validation/#field_choices), that you couldn't modify the interface types from a plugin.

**Comment by jeffgdotorg** [comment]
We talked this out a bit in [a Slack thread](https://netdev-community.slack.com/archives/C01P0FRSXRV/p1703717746476929).

Following up for completeness with a link to the [plugin ideas board](https://plugin-ideas.netbox.dev/).
