### ISSUE TITLE
Japanese translation 

### ISSUE THREAD

**Issue by grncbg** [netbox-community/netbox#14611]
### Language

Japanese

### ISO 639-1 code

ja

### Volunteer

Yes

**Comment by jeffgdotorg** [comment]
Thank you for your interest in helping translate NetBox to Japanese! We're eager to support as many languages as possible, and it's fantastic that you've indicated a willingness to bring your own skills to bear on the effort.

Please be patient as we sort out our a repeatable process for bringing new translation projects online in the third-party translation platform that we use for this work. When we're ready to start work on this translation, we will contact you via this issue with instructions on how to move forward.

**Comment by jeremystretch** [comment]
I've added the Japanese language to the project on Transifex and populated the initial (machine-generated) translations. Please [sign up](https://explore.transifex.com/netbox-community/netbox/) if you'd like to contribute!
