### ISSUE TITLE
Drop support for Python 3.8 and 3.9

### ISSUE THREAD

**Issue by jeremystretch** [netbox-community/netbox#14638]
### Proposed Changes

Increase the minimum supported Python version from 3.8 to 3.10. Remove tests for Python <3.10.

### Justification

We'll be adopting Django 5.0 in NetBox v4.0 (see #14637), which [requires Python 3.10 or later](https://docs.djangoproject.com/en/5.0/releases/5.0/#python-compatibility).

Additionally, Python versions earlier than 3.11 are no longer receiving bug fixes per the [Python release cycle](https://devguide.python.org/versions/).

### Impact

NetBox deployments running Python 3.9 or earlier will need to upgrade their Python version to 3.10 or later.

**Comment by ekrichbaum** [comment]
I'm all for it and don't see any glaring issues up to and including 3.11.  3.12 opens a lot of cases in downstreams of downstreams to need updates or unpinning of specific older versions.
