### ISSUE TITLE
Ukrainian translation

### ISSUE THREAD

**Issue by kornix** [netbox-community/netbox#14639]
### Language

Ukrainian

### ISO 639-1 code

uk

### Volunteer

Yes

**Comment by click0** [comment]
I'll join.

**Comment by jeffgdotorg** [comment]
Thank you for your interest in helping translate NetBox to Ukrainian! We're eager to support as many languages as possible, and it's fantastic that you've indicated a willingness to bring your own skills to bear on the effort.

Please be patient as we sort out our a repeatable process for bringing new translation projects online in the third-party translation platform that we use for this work. When we're ready to start work on this translation, we will contact you via this issue with instructions on how to move forward.

**Comment by romarioZ1000** [comment]
Hello!
i'm ready too! :) 
and i have small team!

**Comment by jeremystretch** [comment]
Support for Ukrainian will be available in NetBox v4.0.3. Please register on [Transifex](https://explore.transifex.com/netbox-community/netbox/) if you'd like to help improve these translations.

**Comment by click0** [comment]
Прошу, панове, поактивніше перекладати, бо машинний переклад - повна жерсть.

**Comment by click0** [comment]
Я глянув перші 200 фраз.
Але там треба визначитись з единообразною термінологію.

**Comment by click0** [comment]
> Я глянув перші 200 фраз. Але там треба визначитись з единообразною термінологію.

Я зробив гіст файл [Cловник термінів для проекту Netbox](https://gist.github.com/click0/1485399b5962a0e849ec32974eaf7643).

Та для оперативних питань пропоную зробити приватну группу у телеграм.
