### ISSUE TITLE
Dutch translation

### ISSUE THREAD

**Issue by deku-m** [netbox-community/netbox#14640]
### Language

Dutch

### ISO 639-1 code

nl

### Volunteer

Yes

**Comment by Flapp3n** [comment]
Can I be of any assistance here?

**Comment by deku-m** [comment]
> Can I be of any assistance here?

Of course the saying is in dutch "vele handen maken licht werk" xD 
But i am not seeing the task not there yet in https://explore.transifex.com/netbox-community/netbox/

**Comment by jeffgdotorg** [comment]
Thank you for your interest in helping translate NetBox to Dutch! We're eager to support as many languages as possible, and it's fantastic that you've indicated a willingness to bring your own skills to bear on the effort.

Please be patient as we sort out our a repeatable process for bringing new translation projects online in the third-party translation platform that we use for this work. When we're ready to start work on this translation, we will contact you via this issue with instructions on how to move forward.

**Comment by powerburner-nl** [comment]
I'd like to join the translation effort. I'm a freelance translator next to my daytime job.
I already have experience translating software.
