### ISSUE TITLE
Adding power cable dropdown should filter for devices that have outlets

### ISSUE THREAD

**Issue by llamafilm** [netbox-community/netbox#14644]
### NetBox version

v3.7.0

### Feature type

Change to existing functionality

### Proposed functionality

From a Power Port page, when I click the blue button to connect it to a Power Outlet, the B Side dropdown shows a huge list of all devices.  I suggest automatically filtering this list by `power_outlets=true`.

### Use case

From a Power Port page, when I click the blue button to connect it to a Power Outlet, the B Side dropdown shows a huge list of all devices which makes it hard to find what I'm looking for.  It would be easier to use if it only showed devices like PDU, UPS, etc.  I realize this is already possible if I open the "select device" dialog but that adds an extra step for no reason.
<img width="1080" alt="image" src="https://github.com/netbox-community/netbox/assets/3991046/eee4f5bd-47ad-42ab-8033-02fbf8d73de2">

### Database changes

none

### External dependencies

none

**Comment by llamafilm** [comment]
The same logic applies when connecting an ethernet cable to an interface, it should filter by `interfaces=true`.

**Comment by jeremystretch** [comment]
Thank you for submitting this issue, however it appears that this topic has already been raised. Please see issue #6101 for further discussion.
