### ISSUE TITLE
Document method for rendering configurations as raw text

### ISSUE THREAD

**Issue by jeremystretch** [netbox-community/netbox#14655]
### Change Type

Addition

### Area

Features

### Proposed Changes

The current documentation for [configuration rendering](https://docs.netbox.dev/en/stable/features/configuration-rendering/) explains how a REST API request can be made to render a configuration template, which will return a JSON response. This are should be extended to also note how the rendered configuration can be returned in plaintext (by setting the `Accept: text/plain` HTTP header).

**Comment by bluikko** [comment]
Took a stab at this since it's been weeks & seemed like quite a simple thing to do. Not sure what is the preferred verbosity level of the text so kept it very simple, hope the style is acceptable for the project.
