### ISSUE TITLE
Custom Fields of IP Ranges and IP Addresses not included in Global Search

### ISSUE THREAD

**Issue by proy-rbbn** [netbox-community/netbox#14671]
### Deployment Type

Self-hosted

### NetBox Version

v3.5.1

### Python Version

3.8

### Steps to Reproduce

1. Create a custom field and include it in IPAM > IP Range .
2. Create an IP Range and in the new custom field enter a distinct string "find-me-now-please"
3. Do a global search for find-me-now-please
4. Unfortunately no search results are provided.

Note that global search does work for IPAM | Prefix, just not for IP Address or IP Range object types.

### Expected Behavior

The global search should have returned an IP Range object within which custom field was set to "find-me-now-please"

### Observed Behavior

no search results are provided.

**Comment by jeffgdotorg** [comment]
Thanks for reporting a bug in NetBox.

We've attempted to reproduce this problem, without success, in both 3.7.0 and 3.6.6. Therefore I'm closing this issue. If you're somehow able to reproduce the problem on a current release, please reopen the issue.

**Comment by proy-rbbn** [comment]
I upgraded to 3.7.0 and could reproduce the issue readily... cannot search for text in custom fields on both IP Range and IP Address still.
