### ISSUE TITLE
Custom Fields of IP Ranges and IP Addresses not included in Global Search on 3.7.0

### ISSUE THREAD

**Issue by proy-rbbn** [netbox-community/netbox#14680]
### Deployment Type

Self-hosted

### NetBox Version

v3.7.0

### Python Version

3.8

### Steps to Reproduce

I upgrade to v3.7.0 as requested in closed ticket #14671.
1. Create a custom field called "cloud_net_name" and include it in IPAM > IP Range .
2. Create an IP Range and in the new custom field enter a distinct string "find-me-now-please"
3. Do a global search for find-me-now-please
4. Unfortunately no search results are provided.
Note that global search does work for IPAM | Prefix, just not for IP Address or IP Range object types.

### Expected Behavior

Should find IP Range search result

### Observed Behavior

 no search results are found.

**Comment by abhi1693** [comment]
What type of custom field are you creating?

**Comment by jeremystretch** [comment]
This issue is being closed as no further information has been provided. If you would like to revisit this topic, please first modify your original post to include all the requested detail, and then ask that the issue be reopened.
