### ISSUE TITLE
German Translation

### ISSUE THREAD

**Issue by Creepios** [netbox-community/netbox#14686]
### Language

German

### ISO 639-1 code

de

### Volunteer

Yes

### Comments

I would and could contribute to the translation map, but I don't have that much of time to translate every single word. So I will help but it will takes time.

**Comment by jeffgdotorg** [comment]
Thank you for your interest in helping translate NetBox to German! We're eager to support as many languages as possible, and it's fantastic that you've indicated a willingness to bring your own skills to bear on the effort.

Please be patient as we sort out our a repeatable process for bringing new translation projects online in the third-party translation platform that we use for this work. When we're ready to start work on this translation, we will contact you via this issue with instructions on how to move forward.

**Comment by kraileth** [comment]
I'm volunteering to contribute as well.

**Comment by borisv** [comment]
To become part of the efforts to translate NetBox to German seems like a good fit for me too.
I have been contributing to several translation projects in the past (withastro, Sonic-PI among others). No explicit experience with transifex, but I am keen to adapt)))

**Comment by fepilins** [comment]
I also would like to contribute

**Comment by mrtn-r** [comment]
I would love to contribute too.

Is there an ETA when the Translation will be possible?

**Comment by odysseus31** [comment]
I'm in

**Comment by julianstolp** [comment]
Would like to contribute too

**Comment by Azmodeszer** [comment]
Count me in.

**Comment by robinreinhardt** [comment]
Would like to contribute too

**Comment by chbally** [comment]
Is there a timeline, when German speaking users can expect the German translation?
Thanks in advance for this job.

**Comment by chbally** [comment]
Thanks @jeremystretch 
At app.transifex.com the German Translation Box can be found. Be invited to join the German team.
I switch german now, because we need to discuss a translation:

Hallo zusammen,
die Frage, die ich mir schon die ganze Zeit stelle, wie wir Tenant übersetzen wollen?!
Die vorgeschlagene Übersetzung ist Mieter - das trifft es finde ich nicht, es sie denn, man ist RZ Betreiber und vermietet Serverschränke. Wollen wir den Begriff Kunde verwenden oder habt ihr eine andere Idee?

**Comment by Creepios** [comment]
Link zu Transiflex: [https://explore.transifex.com/netbox-community/netbox/](https://explore.transifex.com/netbox-community/netbox/)

@chbally Jap damit hab ich auch so meine Schwierigkeiten, das zu übersetzen. Die wortwörtliche Übersetzung der Beschreibung von Tenant lautet ja wie folgend: 

> Ein Tenant stellt eine diskrete Gruppierung von Ressourcen dar, die für Verwaltungszwecke verwendet wird. In der Regel werden Tenants verwendet, um einzelne Kunden oder interne Abteilungen innerhalb einer Organisation zu repräsentieren.

Ich find da ja Abteilung ein gutes Wort für, dann ist es ein wenig verallgemeinerter. Wenn man Kunde nimmt, wäre es ja tatsächlich dann ein Kunde des Unternehmens. Wenn man Abteilung nimmt, könnte man zum einen auch Kunden damit beschreiben und zum anderen sehe ich da aufgrund dessen mehr Sinn drin, dass man z.B. wie in meinem Fall bei einer Stadtverwaltung, die viele verschiedene Themenabteilungen innerhalb einer Site hat (z.B. Verwaltung, Personalwesen, Bauamt), gut unter gruppieren könnte.

**Comment by Creepios** [comment]
Alternative Wörter, die mir gerade noch so zu Abteilung einfallen sind und gewissermaßen auch passen sind: Bereich; Einheit; Sektor; Abteil

**Comment by fepilins** [comment]
Moin zusammen,

mir ist als Übersetzung Mandant geläufig. Ist damit ja auch eher Allgemein gehalten und könnte für Kunde und Abteilung gleichermaßen verwendet werden.

Gruß Felix

**Comment by mrtn-r** [comment]
"Mandant" kenne ich auch für so was, wem das nicht gefällt der könnte es vielleicht mit "Verwender"/"Endverwender" übersetzen…

**Comment by chbally** [comment]
Ich fasse mal zusammen.
Stimmt doch bitte mal durch Nennung der Nummer ab, um mal ein Meinungsbild zu bekommen.

1. Kunde
2. Mandant
3. Abteilung
4. Verwender
5. Endverwender
6. Einheit
7. Sektor
8. Abteil

**Comment by chbally** [comment]
2. Mandant

**Comment by Creepios** [comment]
Ich bin da tatsächlich nun auch für 
2. Mandant
da es mir auch sehr passend erscheint.

**Comment by fepilins** [comment]
2 MandantAm 15.05.2024 um 21:48 schrieb chbally ***@***.***>:﻿

Mandant

**Comment by jeremystretch** [comment]
Support for German will be available in NetBox v4.0.3. Please register on [Transifex](https://explore.transifex.com/netbox-community/netbox/) if you'd like to help improve these translations.

**Comment by chbally** [comment]
@jeremystretch thanks for the info.
We are using this platform for a vote for the translation of tenant, because there are 8 different possibilities to translate.
Let’s find out what fits the best.

**Comment by jeremystretch** [comment]
@chbally this issue exists merely to track the implementation of support for the language. Please use the Transifex platform for all discussion pertaining to the translations themselves.

**Comment by mrtn-r** [comment]
Thanks for enabling the translation.

Could you maybe undo all the automated translations? They seem very wrong (translating slug with snail etc.) and having all "completed" doesn't make it easier to spot such automated mistakes

**Comment by jeremystretch** [comment]
@mrtn-r you can filter by "unreviewed" to show the translations that require human review.

**Comment by mrtn-r** [comment]
@jeremystretch
there are zero reviewers for german, so it's impossible to differentiate by that attribute because no one can review:
![grafik](https://github.com/netbox-community/netbox/assets/153684711/2ea26a39-d1d2-4a4c-8492-5c03438e409d)

**Comment by Creepios** [comment]
and I was wondering why I can't review anything 😅

**Comment by mrtn-r** [comment]
> and I was wondering why I can't review anything 😅

Yeah same, i tried the keyboard-shortcuts but they don't even give an error message or similar if you have no permission.

I volunteer as reviewer btw, someone has to do it after all :D

**Comment by chbally** [comment]
I have left the project and rejoined it.
@jeremystretch could you give me the rights of a reviewer.
I would like to marc all the surely right translated strings as approved to get a better overview.

**Comment by jeremystretch** [comment]
I've promoted everyone who has joined as a German translator on Transifex to reviewer. You should be able to review these translations now.

**Comment by chbally** [comment]
> I've promoted everyone who has joined as a German translator on Transifex to reviewer. You should be able to review these translations now.
I guess this is not the best idea, because reviewers cannot change, as far as Imknow.

Can you please approve me again?

**Comment by mrtn-r** [comment]
Ich hab mal eine Diskussion angefangen damit wir Dinge diskutieren können ohne dieses Issue weiter vollzusammen: https://github.com/netbox-community/netbox/discussions/16171
(I started a discussion to keep this issue a bit less spammed)
