### ISSUE TITLE
Interface Description Field length is too short

### ISSUE THREAD

**Issue by SteveRodrigue** [netbox-community/netbox#14695]
### NetBox version

v3.7.0

### Feature type

Change to existing functionality

### Proposed functionality

The (device) interface description field should be longer. The current limit is 200 characters, some platform supports longer description field.

### Use case

JunOS supports [unlimited description](https://www.juniper.net/documentation/en_US/junos/topics/reference/configuration-statement/add-interface-text-description-radius-options.html#:~:text=There%20is%20no%20character%20limit,characters%2C%20the%20description%20is%20truncated.) field length.

Netbox should offer a longer interface description field.

### Database changes

Increase the size/length of the Interface description field or make it "text" (unlimited length).

### External dependencies

N/A

**Comment by i3D-RyanHamel** [comment]
An increase to 255 characters would be a suitable middle ground, as that is the max limit for Arista, Fortinet, and a few other manufacturers.

**Comment by i3D-RyanHamel** [comment]
https://github.com/netbox-community/netbox/issues/3249#issuecomment-588517221

While I see the meaning behind this, it saves the engineers time by having a subset of the information available in the description. This is a known practice by many carriers.

**Comment by SteveRodrigue** [comment]
I understand your stance... Even if I don't fully agree.
Thanks for your quick response @jeremystretch .

For posterity, some example of Network OS limits:
Arista - 255 characters
Cisco - 240 characters
Fortinet - 255 characters
HPe (old) - 64 characters
Nokia - 160 Characters

**Comment by kmorin18** [comment]
I agree that the max should at least match what is available in actual network devices
The point of netbox is to represent reality

**Comment by jeremystretch** [comment]
> The point of netbox is to represent reality

Rest assured, it does. The description field in NetBox is for exactly that: the human-readable free-form _text description_. Everything else should go in a different field (core or custom) or tag. These other attributes might be combined to **generate** a longer string for the configuration to be provisioned - hence the support longer strings in the actual network OS - but should not live there.

This has been discussed ad nauseam and the decision has already been made, so I'm going to lock this as resolved.
