### ISSUE TITLE
Translation not applied

### ISSUE THREAD

**Issue by thefreakquency** [netbox-community/netbox#14708]
### Deployment Type

Self-hosted

### NetBox Version

v3.7.0

### Python Version

3.8

### Steps to Reproduce

Log into Netbox, access your profile preferences (/user/preferences/), select a language other than Auto. 
Click Save, and logout. 
Log back in

### Expected Behavior

UI should show the translated strings as per selected language. 

### Observed Behavior

Selected language is not applied. 

Tested in both on-prem and demo site, with Firefox, Chrome and Edge.

**Comment by jeremystretch** [comment]
Do you have [localization enabled](https://docs.netbox.dev/en/stable/configuration/system/#enable_localization)? Set `ENABLE_LOCALIZATION = True` set in `configuration.py`.

**Comment by thefreakquency** [comment]
Didn't thought of that as the option was available for the user without it. Added the option and it worked as expected. Thanks!
I will close this Bug and instead open a feature request to hide the language selection when `ENABLE_LOCALIZATION` is set to False. 
Thanks!
