### ISSUE TITLE
Change "Interface" to "Tunnel interface" in tunnel termination form

### ISSUE THREAD

**Issue by markkuleinio** [netbox-community/netbox#14707]
### NetBox version

v3.7.0

### Feature type

Change to existing functionality

### Proposed functionality

I'm proposing changing the "**Interface**" field to "**Tunnel interface**" in the VPN tunnel termination form.

### Use case

The current terminology talking about "tunnel termination" and then asking for **interface** hints the user that this is the actual tunnel starting point (outside interface).

However, the real purpose of the field is to designate the **route-based tunnel interface** (inside interface), not the tunnel source/destination (outside) interface. This is somewhat confusing, especially when the next field is called "Outside IP" that definitely talks about the tunnel outside interface. (That's logical thinking in other cases for me at least: first you select interface, then you select the IP of that interface)

Example issue of the current confusion is #14681.

Renaming the interface field to "**Tunnel interface**" would guide the user to use the tunnel (inside) interface, not the outside interface.

### Database changes

Not sure if this naming change should involve changing some internal structures as well

**Comment by jeffgdotorg** [comment]
If I've understood your proposal correctly, this change can be made without model changes, just a wording change to the tunnel termination creation form. Go ahead with a PR if you agree.
