### ISSUE TITLE
Manufacturer displayed as required for Device import

### ISSUE THREAD

**Issue by wz4** [netbox-community/netbox#14714]
### Deployment Type

Self-hosted

### NetBox Version

v3.7.0

### Python Version

3.10

### Steps to Reproduce

'Device' import displays 'manufacturer' as a required field, but manufacturer is not associated with the Device model.

### Expected Behavior

Manufacturer should not be listed as a required field for Device import.

### Observed Behavior

Failed: Device() got unexpected keyword arguments: 'manufacturer'

**Comment by CTV-2023** [comment]
Maybe because you also need to provide a device type, linked to a manufacturer ? (I don't remember if you can have two identical devices types with different manufacturers, seems strange but there might be an use case)

**Comment by ross-cello** [comment]
I don't think you can create a device type without specifying a manufacturer?

**Comment by wz4** [comment]
Yes, but for a device csv import only device_type is required. I’m sure there are other instances with nested requirements that are not explicitly listed as in this case.

**Comment by jeremystretch** [comment]
Thank you for opening a bug report. Unfortunately, the information you have provided is not sufficient for someone else to attempt to reproduce the reported behavior. Remember, each bug report must include detailed steps that someone else can follow on a clean, empty NetBox installation to reproduce the exact problem you're experiencing. These instructions should include the creation of any involved objects, any configuration changes, and complete accounting of the actions being taken. Also be sure that your report does not reference data on the public NetBox demo, as that is subject to change at any time by an outside party and cannot be relied upon for bug reports.

**Comment by wz4** [comment]
I am going to close this, because csv import still works if manufacturer is listed. I referenced the required fields when creating a custom script, which resulted in the error. Source code should be used to validate model fields.
