### ISSUE TITLE
UI Enhancements for Translation feature

### ISSUE THREAD

**Issue by thefreakquency** [netbox-community/netbox#14710]
### NetBox version

v3.7.0

### Feature type

Change to existing functionality

### Proposed functionality

As I discovered in https://github.com/netbox-community/netbox/issues/14708, having `ENABLE_LOCALIZATION` set to False (default), translation features are not applied, but the user still has access to the Language field in User Preferences..  

I would like to suggest the following changes:

- In /user/preferences/ when `ENABLE_LOCALIZATION` is set to false, have one of the following:
  * Hide the language field
  * Have it grayed-out. 
  * Have a mention that this field is not applied until Localization is enabled by an admin. 

- Have the available language list display both the language names in current language and in native name. This would allow a user to change it to something he would know (as an example, Cyrillic alphabet is not a given for everyone).  
   As an example:
![image](https://github.com/netbox-community/netbox/assets/25624251/4a933bcb-7bcf-4a1d-80e4-fb2fb93ce278) ![image](https://github.com/netbox-community/netbox/assets/25624251/4653ba29-91bd-4e69-8044-60a1fcde9d52) 

- Allow the user to change language from login page (same as the light/dark option already available). Could be by a small drop-down in the footer showing the language list as above (or only the ISO 639 abbreviations for a minimalist approach).

- Allow the Admin to choose which languages are available to the users (either using `configuration.py` or UI (/core/config/).

- Allow the admin to have Login, Footer and Maintenance banners showing in user's language.  

### Use case

This would enhance user experience and make that great new feature even more enjoyable. 

### Database changes

none AFAIK

### External dependencies

none AFAIK

**Comment by jeffgdotorg** [comment]
Good suggestion. Thanks for the specificity and for the mocked-up screenshots in particular.
