### ISSUE TITLE
Allow for drag'n'drop files to import feature

### ISSUE THREAD

**Issue by fatman00** [netbox-community/netbox#14758]
### NetBox version

v3.6.5

### Feature type

New functionality

### Proposed functionality

In the user interface it is already possible to bulk import data using various methods.  Direct Import, Upload File and Data file.
Instead of having to find the entry in the menu, press import -> Upload File - Submit. It would be great if it was possible to just drag'n'drop a file on the import button in the menu.

### Use case

When we create sites we have a baseline file with VLANs and IP prefixes we edit and upload using the GUI, it would be way faster if it was possible to just drag the csv/yaml file onto the import button in the menu, and it would submit it right away.

### Database changes

none

### External dependencies

none

**Comment by jeremystretch** [comment]
Marking this as blocked by #12128 for now.

**Comment by fatman00** [comment]
I am not sure an extra widget would be needed. 
My thought was just that instead of having to click the import button on the sidebar menu, click upload tap, drag a file to it and click submit. 
It would simplify the workflow of working with import of files if it was possible to just drag a file to the import button in the menu sidebar. And that would automatically upload and submit the file.
