### ISSUE TITLE
Add "max depth" functionality to child prefix pages

### ISSUE THREAD

**Issue by craigmcfly** [netbox-community/netbox#14774]
### NetBox version

v3.7.0

### Feature type

New functionality

### Proposed functionality

On /ipam/prefixes/ you can choose the max depth that you want to see.

This would be useful on child pages, i.e. /ipam/prefixes/XXX/prefixes/ to avoid having to look at pages of /31s to see usage. 

### Use case

I have several /24s broken down into /25s, then so on until /31s for point-to-points. I don't want to have to scroll through pages of /31s to look at just the /25s.

**Comment by jeremystretch** [comment]
This idea was proposed in #13197 but did not find anyone interested in implementing it. @craigmcfly would you like to volunteer to own this work?

**Comment by craigmcfly** [comment]
> This idea was proposed in #13197 but did not find anyone interested in implementing it. @craigmcfly would you like to volunteer to own this work?

I'm afraid I lack any sort of technical skill to be able to implement anything.

**Comment by jeremystretch** [comment]
Unfortunately without anyone willing to own the work we'll have to keep this closed. We'll be happy to re-open the FR in the event a volunteer steps up.
