### ISSUE TITLE
Get closest parent prefix from an IP Address

### ISSUE THREAD

**Issue by llamafilm** [netbox-community/netbox#14788]
### NetBox version

v3.6.9

### Feature type

New functionality

### Proposed functionality

Given an IP address, I'd like to get the _closest_ prefix which contains that address. I see FR #1737 raised for exactly this, but the fix seems to miss the mark. The `contains` filter returns _all_ containing prefixes, and the original request was to return only the closest one.  For example, `api/ipam/prefixes/?contains=10.37.152.65/32` returns both 10.37.0.0/16 and 10.37.152.64/26.

### Use case

I'd like to create DHCP reservations in BloxOne DDI based on an IP Address / MAC combination from Netbox.  ~~The BloxOne [API call](https://csp.infoblox.com/apidoc?url=https%3A%2F%2Fcsp.infoblox.com%2Fapidoc%2Fdocs%2FIpamsvc#/fixed_address/fixed_addressCreate) requires the parent ID for this.  So I've added Parent ID as a custom field to all prefixes in Netbox.~~

**Comment by llamafilm** [comment]
I must have misread the documentation or it changed.  Parent ID is actually not required by BloxOne.  So I don't actually need this feature, although I still think it might be useful in some circumstances.

**Comment by jeffgdotorg** [comment]
Closing since OP indicates the functionality described is not actually needed for their use case, and is achievable via minimal post-processing in case someone else out there turns out to need it.

**Comment by jeremystretch** [comment]
> The contains filter returns all containing prefixes, and the original request was to return only the closest one.

You can just grab the last prefix in the list.

**Comment by markkuleinio** [comment]
I think Jeremy is meaning that the prefixes are always returned in IP-numerical order, and in your case (= overlapping prefixes) the last one always happens to be the longest prefix as well.
