### ISSUE TITLE
Stale reports remain in Netbox after modifying the Python code

### ISSUE THREAD

**Issue by llamafilm** [netbox-community/netbox#14799]
### Deployment Type

Self-hosted

### NetBox Version

v3.7.0

### Python Version

3.10

### Steps to Reproduce

1. Create a local data source with URL like `file:///etc/netbox/config/reports`
2. Create a file there with contents from this example: https://github.com/netbox-community/customizations/blob/master/reports/ipam-reports/ip-duplicate.py
3. Add a new report module from this file via the local data source
4. Delete the report module
5. Modify the Python code to remove the `UniquePrefixReport` class
6. Resync the data source
7. Add a new report module from the same Python file

### Expected Behavior

It should show only one report for `UniqueIPReport`

### Observed Behavior

It still shows both reports.
<img width="1223" alt="image" src="https://github.com/netbox-community/netbox/assets/3991046/13e4beac-cd44-497f-8f8a-4ab4dfd07dc9">

Trying to view the source results in an error.  `/extras/reports/ip_duplicate/UniquePrefixReport/source/`
<img width="738" alt="image" src="https://github.com/netbox-community/netbox/assets/3991046/3cbb1273-74bd-4ee9-963e-8de774eba07a">

**Comment by markkuleinio** [comment]
The same happens with **scripts**: if the class name is changed, then there are two scripts listed, but only the "current one" works.

**Comment by markkuleinio** [comment]
Apparently restarting NetBox services after deleting the script helps: then only the correct class is shown in the list when the script is added again.

**Comment by kkthxbye-code** [comment]
@markkuleinio - This was one of the silent removals in 3.5 with the new script system. Pre-3.5 there was code present to ensure that the sys.modules cache was cleared on script load, however this code was removed. So I assume it's intentional not supporting reloading scripts without restarting netbox anymore.

**Comment by jeremystretch** [comment]
> So I assume it's intentional not supporting reloading scripts without restarting netbox anymore.

No, this is not intentional, and you can very easily see that uploading new reports/scripts works without needing to restart any services. @kkthxbye-code since you've already tracked this down perhaps you'd like to put in a PR?
