### ISSUE TITLE
Polish Translation

### ISSUE THREAD

**Issue by Simplicity-Poland** [netbox-community/netbox#14792]
### Language

Polish

### ISO 639-1 code

pl

### Volunteer

Yes

**Comment by jeffgdotorg** [comment]
Thank you for your interest in helping translate NetBox to Polish! We're eager to support as many languages as possible, and it's fantastic that you've indicated a willingness to bring your own skills to bear on the effort.

Please be patient as we sort out our a repeatable process for bringing new translation projects online in the third-party translation platform that we use for this work. When we're ready to start work on this translation, we will contact you via this issue with instructions on how to move forward.

**Comment by jeremystretch** [comment]
Closed in #16810
