### ISSUE TITLE
Quick search breaks available IPs search results

### ISSUE THREAD

**Issue by charlespick** [netbox-community/netbox#14791]
### Deployment Type

Self-hosted

### NetBox Version

3.7.0

### Python Version

3.10

### Steps to Reproduce

View prefix and use "quick search" to filter ip addresses

### Expected Behavior

Available IPs should not change. I would argue that available IPs should not show up in quick search results at all. 

### Observed Behavior

The available IPs increases with the number of IP addresses filtered out. The IPs are however not actually available. Clicking on the available IPs goes onto provision an IP that is already assigned. 
![image](https://github.com/netbox-community/netbox/assets/17918019/60269f99-dffe-4c65-a022-51a0289258c4)

**Comment by jeremystretch** [comment]
Looks like a regression introduced in e4cb0c3cc2738369c71484ff188a6a741c510351
