### ISSUE TITLE
Assigning Virtual interface as Parent interface on Device is not possible

### ISSUE THREAD

**Issue by fikusir** [netbox-community/netbox#14801]
### Deployment Type

Self-hosted

### NetBox Version

v3.7.0

### Python Version

3.10

### Steps to Reproduce

1. Create Virtual interface on a device with name **Uplink**
2. Create 1000BASE-T interface on a device **LAN1**
3. Set on the interface **LAN1** "Parent interface" to **Uplink**

### Expected Behavior

That the system will allow me to assign the Virtual interface

### Observed Behavior

When editing 1000BASE-T field "Parent interface" where I try to put the Virtual interface created in step nr.1 system tell me "Only virtual interfaces may be assigned to a parent interface.". But in this case it is really Virtual interface.

**Comment by DanSheps** [comment]
> * Create Virtual interface on a device with name **Uplink**
> * Create 1000BASE-T interface on a device **LAN1**
> * Set on the interface **LAN1** "Parent interface" to **Uplink**

I don't think this model is valid.  Could you explain more about what you are trying to do here?

> When editing 1000BASE-T field "Parent interface" where I try to put the Virtual interface created in step nr.1 system tell me "Only virtual interfaces may be assigned to a parent interface.". But in this case it is really Virtual interface.

Supported parent/children relationships:

* Physical (parent) to physical (child)
* Physical (parent) to virtual (child)
* Virtual (parent) to virtual (child)


Unsupported:

* Virtual (parent) to physical (child)
