### ISSUE TITLE
Extend VLAN Group scoping to Devices and Virtual Chassis

### ISSUE THREAD

**Issue by dago158** [netbox-community/netbox#14803]
### NetBox version

v3.6.4

### Feature type

Data model extension

### Proposed functionality

Extended to enable scoping of VLAN Groups to DCIM > Devices an DCIM > Virtual Chassis

### Use case

Actually, VLAN Group scoping is currently limited to clusters (virtualization) or locations (DCIM).

In Layer 3 leaf-spine networks configurations include access VLAN networks that are specific to spines,wether individual switches or switches pair (MLAG).

It's not possible to properly link the information between the VLANs / VLAN Group and devices that way,
as there can be multiple VLANs with same ID at the same site/location/rack but on different devices.

### Database changes

None

### External dependencies

None

**Comment by jeffgdotorg** [comment]
Thanks for your interest in helping improve NetBox. I'm moving this issue along for engineering review, because I'm not sure whether this work can be done within an existing release train. It may need to be scheduled out for a minor release boundary.

**Comment by jeremystretch** [comment]
It sounds like what you're really after is probably captured by #14451.
