### ISSUE TITLE
Turkish Translation

### ISSUE THREAD

**Issue by mbrksntrk** [netbox-community/netbox#14808]
### Language

Turkish

### ISO 639-1 code

tr

### Volunteer

Yes

### Comments

I would like to be volunteer of Turkish translation of netbox

**Comment by iuzn** [comment]
I'll join

**Comment by Fykarababa** [comment]
I'll join

**Comment by onurfeyyaz** [comment]
I'll join too

**Comment by burakbektas0** [comment]
I'll join

**Comment by gryhkn** [comment]
I'll join

**Comment by petekharun** [comment]
I will join

**Comment by jeffgdotorg** [comment]
Thank you for your interest in helping translate NetBox to Turkish! We're eager to support as many languages as possible, and it's fantastic that you've indicated a willingness to bring your own skills to bear on the effort. It appears there's quite some interest in joining this particular effort, and we're glad to have you all along for the journey.

Please be patient as we sort out our a repeatable process for bringing new translation projects online in the third-party translation platform that we use for this work. When we're ready to start work on this translation, we will contact you via this issue with instructions on how to move forward.

**Comment by jeremystretch** [comment]
I've added the Turkish language to the project on Transifex and populated the initial (machine-generated) translations. Please [sign up](https://explore.transifex.com/netbox-community/netbox/) if you'd like to contribute!

**Comment by mbrksntrk** [comment]
Join request sent over transifex, please accept.
