### ISSUE TITLE
Importing IKE proposal without authentication method is not possible

### ISSUE THREAD

**Issue by markkuleinio** [netbox-community/netbox#14817]
### Deployment Type

Self-hosted

### NetBox Version

v3.7.0

### Python Version

3.11

### Steps to Reproduce

Go to **VPN - IKE Proposals - Add**
1. Name = GUITEST
2. Authentication method = PSK
3. Encryption algorithm = 256-bit AES (GCM)
4. Group = Group 20
5. Create

(= is successful)

Go to **VPN - IKE Proposals - Import**, use the same fields as above:

```
name,authentication_method,encryption_algorithm,group
IMPORTTEST,preshared-keys,aes-256-gcm,20
```

### Expected Behavior

IKE proposal is imported successfully.

### Observed Behavior

Error is shown:

**Record 1 authentication_algorithm: This field is required.** 

In the import field options the `authentication_algorithm `field is shown as required even though it is not required in GUI.

Also, in the `authentication_algorithm `value list there is no "empty" option to use, thus it is not possible to import IKE proposals that use GCM, unless you fake the algorithm during the import.

Also note that if authentication algorithm is nevertheless set and you want to remove it, you have to **single-edit** the proposal: it is not possible to select all proposals in the list and use **Edit Selected**, as it is not possible to clear the field there.

Related to #14499 where GUI requirement for the authentication method was relaxed.

**Comment by jeremystretch** [comment]
Seems like this was an oversight during the work on #14499.

**Comment by jeremystretch** [comment]
A similar discrepancy exists with the `encryption_algorithm` and `authentication_algorithm` fields on the IPSec proposal bulk import form.
