### ISSUE TITLE
Simple condition (without and/or) does not work in event rule

### ISSUE THREAD

**Issue by markkuleinio** [netbox-community/netbox#14829]
### Deployment Type

Self-hosted

### NetBox Version

v3.7.0

### Python Version

3.11

### Steps to Reproduce

1. Create webhook: Name = Test, URL = http://127.0.0.1:9000 (doesn't matter in this case, it won't be triggered but is required to configure event rule)
2. Go to **Event rules - Add**:
- Name = Test
- Content types = Circuit
- select Updates
- set Conditions:
```
{
    "attr": "status.value",
    "value": "active"
}
```

- Action type = Webhook
- Webhook = Test
- **Create**

### Expected Behavior

Event rule is created

### Observed Behavior

Error is shown about the condition:

**Ruleset must have exactly one logical operator (found 2)** 

The examples in https://docs.netbox.dev/en/stable/reference/conditions/ look the same: simple JSON object with attributes `attr` and `value`.

**Comment by Julio-Oliveira-Encora** [comment]
Please, someone could assign it to me?
