### ISSUE TITLE
Cannot edit cable after Termination is deleted

### ISSUE THREAD

**Issue by PaulR282** [netbox-community/netbox#14844]
### Deployment Type

Self-hosted

### NetBox Version

v3.7.0

### Python Version

3.11

### Steps to Reproduce

1. Create Frontport that is mapped to a rear port
2. Connect a cable from the FP to somewhere else
3. Delete the FP
4. Go to the cable and try to edit it

### Expected Behavior

The cable should be deleted or be editable

### Observed Behavior

```
<class 'AttributeError'>

'str' object has no attribute 'label'

Python version: 3.11.4
NetBox version: 3.7.0
```

**Comment by jeremystretch** [comment]
Thank you for submitting this issue, however it appears that this topic has already been raised. Please see issue #11460 for further discussion.
