### ISSUE TITLE
Localization: Russian translation errors and inconsistencies

### ISSUE THREAD

**Issue by stavr666** [netbox-community/netbox#14845]
### Deployment Type

Self-hosted

### NetBox Version

v3.7.1

### Python Version

3.11

### Steps to Reproduce

1. Learn to read Russian
2. Change Netbox interface language to Russian

### Expected Behavior

Translations correct in general, but have minor typos.

### Observed Behavior

Translation mostly non-contextual, have not general rules and common terminology across the board.

Fastest way to show it: user's Preferences menu.
![image](https://github.com/netbox-community/netbox/assets/84839985/d85358cc-e467-4574-a25e-4f50f25efcf9)
![image](https://github.com/netbox-community/netbox/assets/84839985/af53413d-ea47-4be5-9238-9913df811a40)

It's "Preferences" in Eng, but "Предпочтения" => "Пользовательсккие (=User) Настройки" (correct) => tab "Предпочтения" (wrong again).

Suggestion: show me where translation stored and I'll try to edit whole bunch of errors (also, will fix not translated stuff).

**Comment by jeremystretch** [comment]
Please note that issues with specific translations are not tracked on GitHub. There's a link to report translation issues via [Transifex](https://explore.transifex.com/netbox-community/netbox/), our translation platform, on the "new issue" page.

![screenshot](https://github.com/netbox-community/netbox/assets/13487278/13c1f35a-a0b3-4022-9bfc-85e7d854ae3b)
