### ISSUE TITLE
Event Rule breaks when script is deleted

### ISSUE THREAD

**Issue by renatoalmeidaoliveira** [netbox-community/netbox#14852]
### Deployment Type

Self-hosted

### NetBox Version

v3.7.0

### Python Version

3.8

### Steps to Reproduce

1. Create a Script
2. Create a EventRule linked with the created Script
3. Delete the Script
4. Try to open the EventRule

### Expected Behavior

The Script deletion cascades the deletion of the EventRule

### Observed Behavior

```
<class 'django.urls.exceptions.NoReverseMatch'>

Reverse for 'script' with keyword arguments '{'module': '', 'name': 'EventRule'}' not found. 1 pattern(s) tried: ['extras/scripts/(?P<module>[^/]+)/(?P<name>[^/]+)/\\Z']

Python version: 3.10.13
NetBox version: 3.7.0
```

**Comment by renatoalmeidaoliveira** [comment]
The user can't manually delete the EventRule either, it trows the error:
```<class 'AttributeError'>

'NoneType' object has no attribute 'scripts'

Python version: 3.10.13
NetBox version: 3.7.0
```

**Comment by jeffgdotorg** [comment]
#14438 is related. We should handle this one today since the other issue is scheduled for 4.0.
