### ISSUE TITLE
Cannot delete a user that has bookmarks

### ISSUE THREAD

**Issue by NetTech2001** [netbox-community/netbox#14851]
### Deployment Type

Self-hosted

### NetBox Version

v3.7.0

### Python Version

3.8

### Steps to Reproduce

Click Admin
Click Users
Attempt to delete a use who has a bookmark defined on their dashboard.

### Expected Behavior

Deleting an account should just delete the associated bookmarks, maybe with a warning.

### Observed Behavior

Get error that account cannot be deleted because there is a dependancy. The dependancy will be the device they have bookmarked.
Deleting the bookmark allows the account to be deleted.

**Comment by jeffgdotorg** [comment]
We should change the constraint in this relationship to cascade rather than protect.
