### ISSUE TITLE
Inconsistent GUI to API path for VM disks

### ISSUE THREAD

**Issue by stavr666** [netbox-community/netbox#14861]
### NetBox version

v3.7.1

### Feature type

Change to existing functionality

### Proposed functionality

By now, any GUI path that look like:
> http(s)://netbox/something/?filters

Can be easy switched to API dataset by adding /api:
> http(s)://netbox/api/something/?filters

With VM disk model, for some reason it's looks like:
> http(s)://netbox/virtualization/disks/?filters

in GUI. But api path looks like:
> http(s)://netbox/api/virtualization/virtual-disks/?filters

Use same pattern, please. Fix GUI path, I suppose, it will not break API solutions.

### Use case

Switching back and forth between GUI and API data representation.

**Comment by abhi1693** [comment]
This is a breaking change and will have to wait until the next minor/major release.

**Comment by jeffgdotorg** [comment]
Thanks for catching this inconsistency.

I'm flagging it for engineering review to determine whether we want to tackle it during the v4.0 beta period, or defer it to v4.1 main development.

**Comment by jeremystretch** [comment]
To be clear, keeping URL paths consistent between the UI and REST API is _not_ a design goal; it generally happens out of coincidence as both are structured very similarly. There are however plenty of examples where they diverge, and this is perfectly fine.

Maybe #15156 would obviate the perceived need for them to match?
