### ISSUE TITLE
OOB IP: Add checkbox to ip-addresses to easily assign IP to an interface in one step

### ISSUE THREAD

**Issue by bitcollector1** [netbox-community/netbox#14876]
### NetBox version

v3.7.1

### Feature type

Change to existing functionality

### Proposed functionality

Add a checkbox to the ip-addresses page for OOB IP; just like the Primary IP address. 

<img width="765" alt="OOB_IP" src="https://github.com/netbox-community/netbox/assets/50723251/ddfca11b-7c1c-4ca6-946a-9cf845c47306">

### Use case

currently it's not a one step process to assign an IP address and associate it to OOB IP.  

I'm requesting that this option be added so the functionality is the same as the primary IP address.

**Comment by bitcollector1** [comment]
this change has to be super easy and is probably one that I should do myself, to give back to the project.....but I'm assuming it will take 2 min for one of the core developers to do. Sometimes, these low effort tickets are appreciated by devs ;)

**Comment by DanSheps** [comment]
Honestly

I am kind of against this.  It is going to be too confusing for a user I think when we present it in the UI.  It is also going to add excess clutter where it doesn't need to be.

**Comment by jeremystretch** [comment]
It also would be poor UX to provide a checkbox for both the primary and OOB IP roles, and then scold the user with an error message if they check both.

**Comment by bitcollector1** [comment]
Well since you brought it up, there is no reason to admonish the user as apparently you can set the same IP for both roles ;) 

<img width="341" alt="Screenshot 2024-01-23 at 09 54 55" src="https://github.com/netbox-community/netbox/assets/50723251/2bf44db2-0bf7-40e6-becd-703862ca2c9b">

I had no idea a simple checkbox would cause so much pushback; consider the request withdrawn ;)

**Comment by bitcollector1** [comment]
meh

**Comment by DanSheps** [comment]
> I had no idea a simple checkbox would cause so much pushback; consider the request withdrawn.

I will have to check the logic and the PR, I honestly though (but tested it and discovered it wasn't which is why I didn't say anything) that they were mutually exclusive.

> I had no idea a simple checkbox would cause so much pushback; consider the request withdrawn.

Don't take it the wrong way, I think that `primary_ip` makes sense to be assignable right off the get-go, but I think for oob_ip it makes more sense in that it is optional and assignable only by editing the device.

**Comment by ITJamie** [comment]
Instead of a checkbox it could be converted to a dropdown allowing a selection of roles/functions? None being the default
