### ISSUE TITLE
DataBackend typo in plugin documentation

### ISSUE THREAD

**Issue by minijackson** [netbox-community/netbox#14889]
### Deployment Type

Self-hosted

### NetBox Version

3.7.0

### Python Version

3.11

### Steps to Reproduce

Hello, I'm packaging the 3.7.1 version of NetBox, but the griffe build fails due to this link introduced in #14095:

https://github.com/netbox-community/netbox/blob/develop/docs/plugins/development/data-backends.md?plain=1#L23

Which from my understanding should be `netbox.data_backends.DataBackend`

### Expected Behavior

Griffe successfully builds the documentation.

### Observed Behavior

Griffe fails with:

```
ERROR   -  Error reading page 'plugins/development/data-backends.md': Could not resolve alias core.data_backends.DataBackend pointing at netbox.data_backends.DataBackend (in netbox/core/data_backends.py:13)
```

**Comment by jeffgdotorg** [comment]
Can you please help me understand your packaging target, and especially what a griffe build is? We're not familiar with that build framework.

**Comment by jeremystretch** [comment]
The NetBox documentation is built by calling `mkdocs` directly:

```
$ mkdocs build
INFO    -  Cleaning site directory
INFO    -  Building documentation to directory: /home/jstretch/projects/netbox/netbox/project-static/docs
INFO    -  The following pages exist in the docs directory, but are not included in the "nav" configuration:
             - index.md
INFO    -  Documentation built in 3.74 seconds
```

**Comment by minijackson** [comment]
That's weird, from reading the source code of mkdocs this shouldn't be any different. I should investigate why it works on your end and not mine.

Though I still feel that the documentation I linked has a typo, `DataBackend` is defined in `netbox.data_backends`, and not `core.data_backends`

**Comment by jeremystretch** [comment]
The `DataBackend` class is imported into `core.data_backends`, which is why [the documentation](https://docs.netbox.dev/en/stable/plugins/development/data-backends/#netbox.data_backends.DataBackend) renders correctly.

I'm fine with updating its location in the Markdown file to be more correct, though I couldn't say whether it will solve your problem. I'm going to make that change and close this out as it's not a NetBox issue.

**Comment by minijackson** [comment]
Thank you! This helps
