### ISSUE TITLE
Add support for YAML format in JSON text areas

### ISSUE THREAD

**Issue by balporig** [netbox-community/netbox#14883]
### NetBox version

v3.7.1

### Feature type

Change to existing functionality

### Proposed functionality

Add support for entering YAML instead of JSON in all text input areas that currently accept only JSON such as Config Contexts. The field previews already have the option to view between JSON/YAML

### Use case

YAML is more human-readable and less verbose. Useful in cases you have the data already in YAML format for eg. coming from Ansible group vars, and you don't want to deal with JSON conversion

**Comment by jeffgdotorg** [comment]
Thanks for your interest in helping make NetBox better. I'm moving this issue along to `needs owner` so that a developer with spare capacity can pick it up.

**Comment by jeffgdotorg** [comment]
Tagging @doxic here as somebody who gave a 👍 to this issue and also took the time to ask for a priority bump in a separate channel. At the moment I cannot promise when we might get this FR scheduled, given the existing volume of planned work for the 4.1 release. Your best shot for moving the needle is to comment with the particulars of your use case that make it especially important to you, with the aim of convincing a developer with the necessary skills and capacity to take it up. Viel Glück!

**Comment by jeremystretch** [comment]
Closing this as stale.
