### ISSUE TITLE
Option to not verify SSL Certificate for RSS Feed

### ISSUE THREAD

**Issue by YoucefYousfi** [netbox-community/netbox#14887]
### NetBox version

v3.7.1

### Feature type

Change to existing functionality

### Proposed functionality

For the RSS Feed, adding the option of not verifying the SSL Certificate.
In UI : a checkbox to add "verify=False" option to the rss feed request
In default dashboard configuration : a simple verify=False line added

### Use case

This would allow users to use unverified URLs for RSS Feeds optionally.

**Comment by DanSheps** [comment]
> This would allow users to use unverified URLs for RSS Feeds optionally.

I think an additional use case might be to allow a MitM for things like corporate firewalls without having to load and maintain the certificate (although you should IMO)

**Comment by jeremystretch** [comment]
IMO, as an industry we are by now beyond this. Management of TLS certificates has become so easy and commonplace, there's really no excuse for having an invalid certificate. (I'm aware we have an option on the webhook model to disable certificate validation; I think we should get rid of it.)

**Comment by jeremystretch** [comment]
I'm going to close this out as the proposal pretty starkly violates good security practice.
