### ISSUE TITLE
Implement new customizable date/time format settings, compatible with Translations

### ISSUE THREAD

**Issue by stavr666** [netbox-community/netbox#14890]
### NetBox version

v3.7.1

### Feature type

New functionality

### Proposed functionality

According to #14862, with `ENABLE_LOCALIZATION = True` local datetime culture linked to selected language, ignoring all `_FORMAT` options from config. 

Add user-side option to allow customize datetime format(s) to either entered pattern(s) or predefined presets.

### Use case

Allow users to have best-perceived experience, with both native language and familiar date and time formats.

### Database changes

None.

**Comment by jeremystretch** [comment]
This has been addressed in #15735 by adopting standardized ISO 8601 date & time formatting consistently throughout the NetBox UI. This change will be implemented in NetBox v4.0.
