### ISSUE TITLE
dashboard change log: second name appears twice

### ISSUE THREAD

**Issue by fansari** [netbox-community/netbox#14897]
### Deployment Type

Self-hosted

### NetBox Version

v3.7.1

### Python Version

3.11

### Steps to Reproduce

1. Login using SSO with authentik.
2. Check entries in the "Change Log" widget from the dashboard.

### Expected Behavior

In the "Change Log" widget names in column "Full Name" should be "first name last name".

### Observed Behavior

After updating to 3.7.1 (I use the docker version) I noticed that in all "Change Log" entries my surname appears twice ("Frank Ansari Ansari" instead of "Frank Ansari") in "Full Name".

**Comment by abhi1693** [comment]
Thank you for opening a bug report. I was unable to reproduce the reported behavior on NetBox v3.7.1. Please re-confirm the reported behavior on the current stable release and adjust your post above as necessary. Remember to provide detailed steps that someone else can follow using a clean installation of NetBox to reproduce the issue. Remember to include the steps taken to create any initial objects or other data.

**Comment by jeremystretch** [comment]
> 1. Login using SSO with authentik.

This is likely due to a misconfiguration of your SSO provider. Note that a user's first and last names are displayed as expected when using a locally-defined account.

**Comment by fansari** [comment]
I authentik when I click on "Settings" and check the "Name" field I see "Frank Ansari".

**Comment by fansari** [comment]
I have now copied this default SOCIAL_AUTH_PIPELINE into my config and just disabled this:

# Update the user record with any changed info from the auth service.
#    'social_core.pipeline.user.user_details',
