### ISSUE TITLE
Redis GPG key and source missing

### ISSUE THREAD

**Issue by Doessing** [netbox-community/netbox#14916]
### Change Type

Addition

### Area

Installation/upgrade

### Proposed Changes

When trying to install Redis, it cannot locate the package redis-server.

> sudo apt install -y redis-server
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package redis-server

![image](https://github.com/netbox-community/netbox/assets/50447646/fc48fb9b-ed1d-408b-ba8d-c888cf447913)

To fix this a gpg key and source is needed.
Possible solution: 
Add the following before sudo apt update:

`curl` -fsSL https://packages.redis.io/gpg | sudo gpg --dearmor -o /usr/share/keyrings/redis-archive-keyring.gpg

`echo` "deb [signed-by=/usr/share/keyrings/redis-archive-keyring.gpg] https://packages.redis.io/deb $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/redis.list

**Comment by jeffgdotorg** [comment]
Hi, and thanks for your interest in improving the NetBox documentation. We're glad to have you along for the ride!

We need a bit more context around this report before we can even attempt to reproduce the problem, though. Please indicate which DEB-based distribution and version you're using, and which install flavor (minimal, server, workstation...).

**Comment by jeremystretch** [comment]
This issue is being closed as no further information has been provided. If you would like to revisit this topic, please first modify your original post to include all the requested detail, and then ask that the issue be reopened.
