### ISSUE TITLE
Adding tooltip to menus, etc.

### ISSUE THREAD

**Issue by KongNan** [netbox-community/netbox#14911]
### NetBox version

v3.7

### Feature type

Change to existing functionality

### Proposed functionality

Adding tooltip to menus.  See the screenshot and description below:

GMail's: ![image](https://github.com/netbox-community/netbox/assets/5051591/36a21435-28c7-4491-be5d-fa7235cd0549)

Moodle's: ![image](https://github.com/netbox-community/netbox/assets/5051591/57d4b526-39fa-4dfa-89e9-6b087551ec14)

### Use case

In order to better reflect the real world, netbox uses many different terms (OR "classes"), which may not be easy for new users to understand the meaning at first sight, and this affects the ease of use to some extent.

NetBox gives many examples of these classes in the demo, and explains them well in the documentation, and even draws some relationship diagrams, all of which can effectively help users to understand.

Further, it would be nice to have a tooltip that allows the user to find the entry point they need in the menu at a glance. You can refer to the top tab in Gmail inbox and Moodle.

(btw: there are many tools/techniques available. For example, html title, css, bootstrap, even django's own, just choose what you want).

### External dependencies

/

**Comment by jeffgdotorg** [comment]
Hi @KongNan, and thanks for your interest in helping improve NetBox! I appreciate you providing concrete examples in the form of screenshots.

I'm closing this issue as "not planned" for two reasons:

1. We already have an established pattern for integrating links to the docs in the NetBox UI; there's a "Help" button at the top right of every interface for adding a new object. Adding tooltips to the menus feels redundant with that existing, perfectly adequate access to help.
2. We're also currently under a fairly strict freeze where UI changes are concerned, ahead of reviewing our overall UX picture over the course of the next few releases.
