### ISSUE TITLE
No longer be able assign IP address to Devices management Interface

### ISSUE THREAD

**Issue by kzhang1310** [netbox-community/netbox#14910]
### Deployment Type

Self-hosted

### NetBox Version

v3.6.5

### Python Version

3.8

### Steps to Reproduce

1. when I add mgmt IP to device as primary IP, the GUI no longer allow to pick the device from drop down, only interface show up as drop down
2. the device default to first device in the database.
![netbox](https://github.com/netbox-community/netbox/assets/26172689/17007a8e-32c6-4059-8ecb-4dfb172a077a)

### Expected Behavior

It was working before in 3.4.5.

### Observed Behavior

when I add mgmt IP to device as primary IP, the GUI no longer allow to pick the device from drop down, only interface show up as drop down

**Comment by jeremystretch** [comment]
Thank you for opening a bug report. Unfortunately, the information you have provided is not sufficient for someone else to attempt to reproduce the reported behavior. Remember, each bug report must include detailed steps that someone else can follow on a clean, empty NetBox installation to reproduce the exact problem you're experiencing. These instructions should include the creation of any involved objects, any configuration changes, and complete accounting of the actions being taken. Also be sure that your report does not reference data on the public NetBox demo, as that is subject to change at any time by an outside party and cannot be relied upon for bug reports.

**Comment by kzhang1310** [comment]
in netbox 3.4.5, when you create mgmt IP for a device, In the IPAM, when you edit the IP address, you can assign it to a device and it's interface. See attached screenshot, the Device Icon is in the GUI, but there is not drop down for which device you want to assign.

**Comment by bluikko** [comment]
I think you need to click the little button on the right from the interface selection drop-down.

**Comment by jeremystretch** [comment]
> I think you need to click the little button on the right from the interface selection drop-down.

Yep. This was introduced back in v3.5; see #10054.
