### ISSUE TITLE
Server error (500) on NetBox demo

### ISSUE THREAD

**Issue by thiagomarafeli** [netbox-community/netbox#14926]
### Deployment Type

NetBox Cloud

### NetBox Version

v3.7.1

### Python Version

3.8

### Steps to Reproduce

1. Access https://demo.netbox.dev/ and log in
2. Access DCIM > Devices

### Expected Behavior

Load the devices screen

### Observed Behavior

A server error (500) and a detailed error showed up:

![image](https://github.com/netbox-community/netbox/assets/70313778/297131c0-ed56-4541-8b49-6aa223579154)

**Comment by jeremystretch** [comment]
Per the bug report template:

> Additionally, **do not rely on the demo instance** for reproducing suspected bugs, as its data is prone to modification or deletion at any time.

Also, please remember to search existing issues before opening a new one. A quick search for the error message immediately turns up #14840. We'll have to assume this is related as reproduction steps have not been provided.
