### ISSUE TITLE
Add option export a Netbox compatible CSV

### ISSUE THREAD

**Issue by thiagomarafeli** [netbox-community/netbox#14925]
### NetBox version

v3.6.7

### Feature type

New functionality

### Proposed functionality

Nowadays, if you do an export of DCIM > Platform (e.g.) and try to import it later in any other instance with a running NetBox, it will have an error saying there is no <Field> because the field is not present in that visualization, but it's not exacly that.

The problem is that there is Fields starting with a capital letter and it may have a different display name.

The error:
![image](https://github.com/netbox-community/netbox/assets/70313778/ba813200-0ada-40c1-8afa-0937f98fa085)

The data (exported into a CSV):
![image](https://github.com/netbox-community/netbox/assets/70313778/33f47945-5cd2-4095-acc5-87d455f3bb81).

The fields:
![image](https://github.com/netbox-community/netbox/assets/70313778/d0e59a7b-25e3-4852-9602-a95c3392cfd3)

Isn't there a way to do such and export option that will allow us to import using the adequate fields? At least the ones that do not depend on others or vice versa. If so, I believe it would be a great feature, without having to create a custom template.

It would be helpful, because nowadays it only works after getting rid and adapting some fields from the CSV and this is time consuming.

Ps: I'm new to NetBox and english is not my first language

### Use case

- Import some table into another NetBox instance
- Work over the exported data and maybe getting back on (bulk edit)
- Backup some specific table, without having to backup the database itself or accessing it

**Comment by jeremystretch** [comment]
Thank you for submitting this issue, however it appears that this topic has already been raised. Please see issue #14502 for further discussion.
