### ISSUE TITLE
Change definition of completed cable path for connection column

### ISSUE THREAD

**Issue by julianstolp** [netbox-community/netbox#14949]
### NetBox version

v3.7.1

### Feature type

Change to existing functionality

### Proposed functionality

The "Connection" field in the interface table should show the device connected at the other end, regardless of the interface type. If I remember correctly, this was implemented in the early 3.x versions.

![image](https://github.com/netbox-community/netbox/assets/41152397/1d5870f0-856a-473c-a8fe-b27d545407cd)
![image](https://github.com/netbox-community/netbox/assets/41152397/01f7a0e8-45ae-4ec3-9e23-b9fc8e1c0dec)

see https://github.com/netbox-community/netbox/discussions/14819

### Use case

This would be useful for modelling network sockets in offices or other unused ports that currently have no end device. In the current implementation, you have to click on the cable trace for each interface to see what device is connected to the other end, which can quickly become tedious. 
Of course, this can be circumvented by modelling such sockets as interface types, but if a device is connected there, the interface must then be deleted and the cables have to be connected to the front port and rear port. Also this does not model the real world correctly.

I want to be able to tell immediately which device is connected at the far-end of a cable path.

**Comment by jeremystretch** [comment]
Thank you for submitting this issue, however it appears that this topic has already been raised. Please see issue #14155 for further discussion.
