### ISSUE TITLE
Changelog entry missing for tag change

### ISSUE THREAD

**Issue by kuhball** [netbox-community/netbox#14947]
### Deployment Type

Self-hosted

### NetBox Version

v3.7.1

### Python Version

3.11

### Steps to Reproduce

1. Edit an Interface / Device / Site
2. Add / remove a tag

Reproducible within demo.netbox.dev.

### Expected Behavior

After adding / removing the tag I would expect to see a changelog entry. 

### Observed Behavior

No changelog entry is created.

**Comment by jeremystretch** [comment]
Seems like a regression introduced in v3.7.0 by #14147.
