### ISSUE TITLE
Add "has_virtual_device_context" filter to device filters in UI and API

### ISSUE THREAD

**Issue by SaschaSchwarzK** [netbox-community/netbox#14948]
### NetBox version

v3.7.1

### Feature type

Change to existing functionality

### Proposed functionality

The only way to find devices that have virtual device context is to get all virtual-device-contexts and extract the list of related devices from that. Similar to the has_primary_ip filter.

### Use case

Get the list of devices with have or have not a virtual-device-context with a simple boolean filter.

### Database changes

Not required

### External dependencies

None

**Comment by jeremystretch** [comment]
There's ongoing work under #15237 to identify and test for missing filters. It hasn't yet expanded to checking reverse ForeignKey relationships but should eventually cover this sort of thing.
