### ISSUE TITLE
If Search result returns 1 item, automatically redirect to it

### ISSUE THREAD

**Issue by david-ramsden** [netbox-community/netbox#14951]
### NetBox version

v3.7.1

### Feature type

Change to existing functionality

### Proposed functionality

When searching for something within the NetBox UI, if only 1 result is returned, automatically redirect the user to the result.

For example: If searching for "CORE01" only returns 1 result, which might be a device within the DCIM, automatically redirect the user to "/dcim/devices/175/"

### Use case

Removes an action that the user needs to perform if only 1 search result is returned, i.e. click the hyperlink.

**Comment by jeremystretch** [comment]
Thank you for submitting this issue, however it appears that this topic has already been raised. Please see issue #2668 for further discussion.
