### ISSUE TITLE
Allow Custom Choices for VPN Tunnel Encapsulation

### ISSUE THREAD

**Issue by JohannesKreuzer** [netbox-community/netbox#14969]
### NetBox version

v3.7.1

### Feature type

Change to existing functionality

### Proposed functionality

allow TunnelEncapsulationChoices to be customized via FIELD_CHOICES config by adding the key attribute to the Choices Class.

### Use case

Modelling additional VPN types using VPN models.

**Comment by jeremystretch** [comment]
> Modelling additional VPN types using VPN models.

NetBox does not permit users to add arbitrary encapsulation types because it would not reflect real-world modeling. If there is a specific, well-defined encapsulation method you'd like to see added in NetBox, please open a feature request for it.
