### ISSUE TITLE
Show device location in breadcrumbs

### ISSUE THREAD

**Issue by llamafilm** [netbox-community/netbox#14972]
### NetBox version

v3.7.0

### Feature type

Change to existing functionality

### Proposed functionality

When viewing a device, the breadcrumbs at the top of the page currently show the site and parent device.  I'd like to also include the location here.  Mockup image:

<img width="470" alt="image" src="https://github.com/netbox-community/netbox/assets/3991046/b45e4c6f-7079-4bdc-a7a1-57570a9d33af">

### Use case

My devices are primarily organized using the hierarchy Site > Location > Device.  This would save a lot of time when editing a device, to be able to quickly jump to a list of other devices in the same location.  (By the way, location means room name in my system).

### Database changes

none

### External dependencies

none

**Comment by llamafilm** [comment]
At first glance, it seems like all that is required is adding these lines in `netbox/templates/dcim/device/base.html`

```html
  {% if object.location %}
    <li class="breadcrumb-item"><a href="{% url 'dcim:device_list' %}?site_id={{ object.site.pk }}&location_id={{ object.location.pk }}">{{ object.location }}</a></li>
  {% endif %}
```

**Comment by sleepinggenius2** [comment]
As Locations can be nested, I would assume that the full hierarchy would be desirable, so the code would be a little more complicated. It looks like it's already being done on MPTT views themselves, like Location, Region, and Site Group, so it would probably make sense to make a template tag like the existing nested_tree one to handle this use case.

**Comment by llamafilm** [comment]
You're right, the full hierarchy would be better.  I guess there would need to be some limit in case the string is too long, shortening the middle with ellipses to fit on screen.
