### ISSUE TITLE
Extend bulk creation support to the label field in creation and editing mode

### ISSUE THREAD

**Issue by LLFT** [netbox-community/netbox#14977]
### NetBox version

v3.7.1

### Feature type

Change to existing functionality

### Proposed functionality

When editing a selection of front or rear ports, you can rename the name or label as you do during creation. At the same time extend the option to the label during creation. Which is not currently the case.

### Use case

Each port of a copper ring road made up of 24 ports are physically named RC25-001 to RC25-024. From the web interface, it is not possible to rename the name or label of the ports according to the mask RC25-[001-0024] so that each port is assigned a name or label: RC25-001,RC25-002 ,RC25-003,...,RC25-024

**Comment by DanSheps** [comment]
> From the web interface, it is not possible to rename the name or label of the ports according to the mask RC25-[001-0024] so that each port is assigned a name or label: RC25-001,RC25-002 ,RC25-003,...,RC25-024

This is currently possible.  You need to set your regex within the label field as well.

**Comment by LLFT** [comment]
I understand that it's possible to rename ports in bulk as indicated on this website: https://constantpinger.home.blog/2022/05/13/renaming-interfaces-in-bulk-in-netbox/

But I don't want to rename them, I want to increment the value of the label and name, at least the label.

Here's my context:

I have five copper backplanes with 24 ports each. The labels of the ports on the first backplane range from 1 to 24, the second backplane has labels from 25 to 48, and so on until the last backplane with labels ranging from 97 to 120.

Currently, I have to make the declaration one by one.

Using an incrementation with a regex [25-48] seems more accessible to me.

**Comment by DanSheps** [comment]
> Currently, I have to make the declaration one by one.
> 
> Using an incrementation with a regex [25-48] seems more accessible to me.

When you are creating:

Name: somename[25-48]
Label: somelabel[25-48]

Will do what you want.
