### ISSUE TITLE
Swagger vs REST API: Interface.wireless_lans array

### ISSUE THREAD

**Issue by janhlavin** [netbox-community/netbox#14982]
### Deployment Type

Self-hosted

### NetBox Version

v3.7.1

### Python Version

3.11

### Steps to Reproduce

1. create wireless lan
2. create device with interface
3. associate wireless lan to interface

### Expected Behavior

items in `Interface.wireless_lans` collection of **WirelessLAN** object in Swagger schema

### Observed Behavior

items in `Interface.wireless_lans` collection of _number_ in Swagger schema, but REST API return **WirelessLAN** objects

**Comment by Smixi** [comment]
Hi, I made some investigation. All fields using `SerializedPKRelatedField` are correctly represented for the request, but doesn't use the serializer for response. I can make a PR

**Comment by Smixi** [comment]
Any news ?

**Comment by abhi1693** [comment]
Looks like there is another PR #15449 that solves a similar issue.

**Comment by Smixi** [comment]
Arf, it got duplicated. Did the other PR works ? I checked but it seems it doesn't looks for the direction value to use int for request.
