### ISSUE TITLE
Cables not editable after deleting Device

### ISSUE THREAD

**Issue by Berni9** [netbox-community/netbox#14993]
### Deployment Type

Self-hosted

### NetBox Version

v3.7.1

### Python Version

3.8

### Steps to Reproduce

1. Create two new Device with Interfaces or Front Ports
2. Create Cables between the Interfaces of the created Devices in Step 1
3. Delete one of the Devices created before
4. Open the remaining Device and go to Interfaces-Tab
5. Click on "Edit Cable" at a Cable that was connected to the deleted Device

### Expected Behavior

Cable sholud be editable, but I think it would be better, if Cables are deleted with the Device.

### Observed Behavior

The Cables connected to the deleted Device are not deleted and not editable. The Cable has to be deleted manually to connect the Interface again. The following Error is shown after clicking on "Edit Cable":
![grafik](https://github.com/netbox-community/netbox/assets/112371896/d111b1fb-bcc9-4bf1-bcb5-fb32ba5b7daa)

**Comment by PaulR282** [comment]
This is already been discussed in #11460
