### ISSUE TITLE
Add custom fields to templates

### ISSUE THREAD

**Issue by llamafilm** [netbox-community/netbox#15011]
### NetBox version

v3.7.0

### Feature type

Data model extension

### Proposed functionality

I’d like to enter custom fields on a Device Type (template). When instantiating a new Device, it will copy custom field values from the template. After that, the fields can be customized on each device, just like any other field.

The same thing would apply to all other types of templates, like Power Outlets, etc.

### Use case

I use a multi-select custom field on all Devices called `telegraf_config` that defines which Telegraf input template should be used to monitor its health. This field is usually the same for all devices of a given type.

Another use case, described in #14971: I would add a Boolean field to each power outlet to indicate whether it’s controllable.

Another use case: a custom field called `uri_handler` with values such as http, ssh, vnc,rdp. I would use this field in custom links like this: `{{object.cf.uri_handler}}://{{object.primary_ip}` to make it easy to connect to each device’s management interface.

### Database changes

I suppose it would need a new field on each template.

### External dependencies

None

**Comment by jeremystretch** [comment]
Thank you for submitting this issue, however it appears that this topic has already been raised. Please see issue #9243 for further discussion.

**Comment by llamafilm** [comment]
Thanks, I hadn’t seen the other issue. That one is closed and locked so further discussion is not possible. It looks like several users have requested this feature, and nobody raised any counter argument. So why close the discussion?
