### ISSUE TITLE
Add function to trim whitespaces in config templates

### ISSUE THREAD

**Issue by heiko-ma** [netbox-community/netbox#15049]
### NetBox version

v3.7.1

### Feature type

Change to existing functionality

### Proposed functionality

When creating a config template, it would be useful if the jinja2 whitespace trimming feature (trim_blocks and lstrip_blocks) could be toggled on and off. 
Currently, only manual trimming is available and it's a tedius task, especially with long config files.

### Use case

We're currently implementing templates for our switch configs. To keep those templates somewhat readable and understandable (Jinja2 can be quite a mess sometimes) without needing to check every control clause for manual trimming, a switch to control this behavior would be really useful.

**Comment by jeremystretch** [comment]
> When creating a config template, it would be useful if the jinja2 whitespace trimming feature (trim_blocks and lstrip_blocks) could be toggled on and off.

This is achieved by passing the relevant [Jinja2 environment parameters](https://jinja.palletsprojects.com/en/3.1.x/api/#jinja2.Environment) when creating the config template.

![screenshot](https://github.com/netbox-community/netbox/assets/13487278/6714949d-aedf-4631-a3c3-5da207cd130a)
