### ISSUE TITLE
Create a plugin migration guide for NetBox v4.0

### ISSUE THREAD

**Issue by jeremystretch** [netbox-community/netbox#15043]
### Change Type

Addition

### Area

Plugins

### Proposed Changes

Add a migration guide to the plugin development documentation detailing relevant changes in NetBox v4.0 for plugin maintainers. Example topics include:

- Any breaking changes to the plugins API
- Relocation/removal of internal components
- HTML template changes
- UI design changes

**Comment by peteeckel** [comment]
Some input from the migration of NetBox DNS to 4.0:

https://github.com/peteeckel/netbox-plugin-dns/pull/153

This PR will be updated over time, following the development of the NetBox feature branch.
