### ISSUE TITLE
Example custom script fails

### ISSUE THREAD

**Issue by aharrisson** [netbox-community/netbox#15052]
### Change Type

Correction

### Area

Customization

### Proposed Changes

The example custom script fails since it creates Device objects with the old "role" field, rather than "device_role".

**Comment by jeffgdotorg** [comment]
Good catch. Thanks for the issue and PR.

For future reference, our workflows require an accepted issue before a PR will be considered valid. For a one-line docs fix on a first issue, I'm going to let that go 😉

**Comment by aharrisson** [comment]
Thank for the merge, @jeffgdotorg. 👍 

Sorry. I did actually read the contribution rules, but it seemed like a lot of overhead for such a minor change. I will make sure to follow the correct process in the event of any future contributions.

**Comment by jeffgdotorg** [comment]
Glad to do it, and glad to have you as a contributor!

Process wise there's a little bit of play in the gears for fixes as straightforward as this one. It matters more for changes with a broader scope.
