### ISSUE TITLE
Undefined symbol in source

### ISSUE THREAD

**Issue by francois-vincent** [netbox-community/netbox#15058]
### Deployment Type

Self-hosted

### NetBox Version

v3.7.2

### Python Version

3.10

### Steps to Reproduce

❯ ruff check | grep F821
core/api/schema.py:139:79: F821 Undefined name `serializers`

### Expected Behavior

add the required import in file schema.py

### Observed Behavior

missing import

**Comment by francois-vincent** [comment]
my bad it's actually VERSION = '3.7.3-dev'

**Comment by jeremystretch** [comment]
Thank you for opening a bug report. Unfortunately, the information you have provided is not sufficient for someone else to attempt to reproduce the reported behavior. Remember, each bug report must include detailed steps that someone else can follow on a clean, empty NetBox installation to reproduce the exact problem you're experiencing. These instructions should include the creation of any involved objects, any configuration changes, and complete accounting of the actions being taken. Also be sure that your report does not reference data on the public NetBox demo, as that is subject to change at any time by an outside party and cannot be relied upon for bug reports.

**Comment by jeremystretch** [comment]
This issue is being closed as no further information has been provided. If you would like to revisit this topic, please first modify your original post to include all the requested detail, and then ask that the issue be reopened.

**Comment by abhi1693** [comment]
It's not undefined. Are you by any chance running a forked version of netbox where you have made changes?

![image](https://github.com/netbox-community/netbox/assets/5083532/0f366bf9-f6aa-4560-b386-6a37b93e281d)

**Comment by francois-vincent** [comment]
It is definitely undefined.

The undefined symbol is serializers with final s, not serializer !!!

To reproduce, just follow these steps (as described in the issue but I
reproduce it here) :
- Download the current zip from the github repo, then unzip it
- cd netbox-develop/netbox
- pip install ruff
- ruff check | grep F821
--> core/api/schema.py:139:79: F821 Undefined name serializers

or open core/api/schema.py in a smart editor (I use pycharm)

I guess that this undefined symbol went unnoticed because it is hidden
behind an 'and' in a case that
is never unit tested.

Let me know,
François

**Comment by francois-vincent** [comment]
👍🏼
