### ISSUE TITLE
Add "Maintenance" as a status for devices

### ISSUE THREAD

**Issue by aaron-iles** [netbox-community/netbox#15075]
### NetBox version

v3.6.9

### Feature type

Change to existing functionality

### Proposed functionality

Acknowledging that this issue has already been raised in #4283 , I am requesting that "Maintenance" be added as a status to devices.

### Introduction
Again acknowledging that this was discussed in #4283 , our team sees "Maintenance" as a status that is fairly long lived at times in our use case (sometimes weeks). We don't necessary care about the previous status when maintenance is complete since we will reevaluate it and update the status as necessary.

### Examples
- A device with a status of  "Active" gets into a funky state that requires attention. The device's status is changed to "Maintenance" while techs evaluate it. They discover a new part is needed and two weeks later, the part arrives. After installation, the device is reevaluated to determine its new status.
- A device with a status of  "Active" is working properly, but requires an upgrade of a part. The device's status is changed to "Maintenance" while the upgrade is performed. The upgrade finishes 3 days later and the device is tested to determine its new status. Tests indicate a severe problem prompting us to change the status to "Failed".
- A device with a status of  "Inventory" is currently not in use. Needs dictate that it be turned on and brought into service. Before this can be done, it needs parts replaced to be compatible with the rest of the pool of resources. The status is changed to "Maintenance". When the replacements are complete and tests succeed, the device's status is changed to "Active".

**Comment by aaron-iles** [comment]
I will submit a pull request momentarily. Just making sure all of the updated unit tests pass.

**Comment by jeremystretch** [comment]
We declined to add this as a stock choice in #4283 for the reason given [here](https://github.com/netbox-community/netbox/issues/4283#issuecomment-592555768). If you want to add this as a choice in your own NetBox deployment, you can do so by defining [custom choices](https://docs.netbox.dev/en/stable/configuration/data-validation/#field_choices) for `dcim.Device.status`.

**Comment by aaron-iles** [comment]
I was not aware of the ability to nicely inject extra choices like that. Awesome idea! Thank you for pointing that out.
