### ISSUE TITLE
Module type power ports should not be unique on same device

### ISSUE THREAD

**Issue by dejantep** [netbox-community/netbox#15078]
### Deployment Type

Self-hosted

### NetBox Version

3.5.7

### Python Version

3.8

### Steps to Reproduce

1. Create device with two module bays
2. Create module type
3. Add power port to module type and give it a name
4. Install module in first bay
5. Install same module in second bay

### Expected Behavior

Device with module bays shouls be able to install same modules in different bays. Lets say line cards or mda etc
Power ports / connectors are the same

### Observed Behavior

Error - Port name already exists on this device

**Comment by jeremystretch** [comment]
This is not a bug. Uniqueness is enforced for power port names on a device.
