### ISSUE TITLE
API virtualmachine config_template data is missing

### ISSUE THREAD

**Issue by nicolai-hornung-bl** [netbox-community/netbox#15070]
### Deployment Type

Self-hosted

### NetBox Version

v3.7.1

### Python Version

3.8

### Steps to Reproduce

Query the API Object of any VM. While the render-config endpoint was added in v3.7.1 with PR #14287 the corresponding config_template value cannot be queried or set using the API. 

### Expected Behavior

I want to be able to assign and query config templates to virtualmachines using the API as I am able to do with Devices and in the GUI.

### Observed Behavior

The config_template key is missing.

**Comment by jeremystretch** [comment]
Looks like the field was mistakenly omitted from `VirtualMachineWithConfigContextSerializer`. (The base serializer has it defined.)
