### ISSUE TITLE
"Add export template" button doesn't pass content type

### ISSUE THREAD

**Issue by alehaa** [netbox-community/netbox#15084]
### Deployment Type

Self-hosted

### NetBox Version

v3.7.2

### Python Version

3.11

### Steps to Reproduce

1. Navigate to `Customization` > `Export Templates`.
2. Click button `Export` > `Add export template...`

### Expected Behavior

Form has field `Content types` prefilled.

### Observed Behavior

Field `Content types` is empty, as URL parameter is not properly set. It needs to be `content_types` not `content_type` (missing s).

I can provide a PR for this issue.

**Comment by jeremystretch** [comment]
> 1. Navigate to Customization > Export Templates.

Just to clarify because this could be confusing: The bug affects the "add export template" dropdown item under the "export" button for _all_ objects.
