### ISSUE TITLE
Missing device-field for interface assignment when editing/creating an IP Address 

### ISSUE THREAD

**Issue by nomad-cyanide** [netbox-community/netbox#15083]
### Deployment Type

Self-hosted

### NetBox Version

3.6.9

### Python Version

3.10

### Steps to Reproduce

1. Select a prefix
2. Click an available ip
3. Under "interface assignment" there should be the possibility to select a device or vm, but only a list of interfaces are shown.
![Screenshot 2024-02-08 at 12 31 02](https://github.com/netbox-community/netbox/assets/47887698/6c95b113-aabe-4032-b04b-9c76cd849a75)

### Expected Behavior

Field for selecting the device or vm should be visible.

### Observed Behavior

No field for selecting the device or vm should be visible.

**Comment by jeremystretch** [comment]
Click the button next to the field.
