### ISSUE TITLE
Remove "# TODO: Remove in v4.0" code

### ISSUE THREAD

**Issue by arthanson** [netbox-community/netbox#15088]
### Proposed Changes

There are a couple places in the code with "# TODO: Remove in v4.0" tags:

* netbox/dcim/filtersets.py
* netbox/utilities/fields.py

### Justification

They are already slated to be removed, just a housekeeping task to track removing these.

**Comment by jeremystretch** [comment]
Thanks for calling this out. I've opened #15099 and #15100 to track these individually.
