### ISSUE TITLE
Allow filtering of VLAN Groups by Cluster and Cluster Group

### ISSUE THREAD

**Issue by Chiniquy** [netbox-community/netbox#15119]
### NetBox version

v3.7.2

### Feature type

New functionality

### Proposed functionality

VLAN Groups can be scoped by Cluster or Cluster Group today, but it seems that the ability to filter VLAN Groups by these criteria in the Netbox frontend is missing.

![image](https://github.com/netbox-community/netbox/assets/10709382/04f3ce14-2796-4bf5-898c-4c8c3e965df3)

I propose that Virtualization > Cluster and Virtualization > Cluster Group are added to the filter. 
They may need a new category in the filter menu, in the same way that Region, Site, etc. have "Location" as a category in the filter menu. 

 

### Use case

This would allow Netbox users to filter VLAN Groups by Scope = Cluster and Scope = Cluster Group. 

### Database changes

I am not aware of any necessary database changes. 

### External dependencies

I am not aware of any external dependencies for this feature request.

**Comment by xkilian** [comment]
Same issue with Prefixes, vlans are exposed there but can't be filtered...

**Comment by jeffgdotorg** [comment]
Thanks for catching this mismatch between the API and the frontend. I verified that the requested enhancement has not been implemented in 4.0-b1, so I'm marking it as `needs owner`. If you are interested in working it through to a PR, please say so and somebody will assign it to you.

**Comment by Julio-Oliveira-Encora** [comment]
Could you please assign it to me?
