### ISSUE TITLE
Server Error when creating permission with constraints

### ISSUE THREAD

**Issue by Kani999** [netbox-community/netbox#15115]
### Deployment Type

Self-hosted

### NetBox Version

v3.7.1

### Python Version

3.10

### Steps to Reproduce

1. Add new Permission https://demo.netbox.dev/users/permissions/add/ 
2. Setup **Constraints** as `{"role": "server"}`
3. Create
4. Obtain Server Error
```
<class 'ValueError'>

Field 'id' expected a number but got 'server'.

Python version: 3.8.10
NetBox version: 3.7.1
Plugins: 
  netbox_demo: 0.3.1
```

### Expected Behavior

Server Error 500 should not be raised. 
It should display some kind of validation popup.

### Observed Behavior

Server Error occurs
```
<class 'ValueError'>

Field 'id' expected a number but got 'server'.

Python version: 3.8.10
NetBox version: 3.7.1
Plugins: 
  netbox_demo: 0.3.1
```

**Comment by Kani999** [comment]
Recreated from #15017 because I cannot reopen the issue. 
I suppose the problem still needs to be fixed.

**Comment by DanSheps** [comment]
See: #15019
