### ISSUE TITLE
No Change Log entries created by updates to the Tags on an object

### ISSUE THREAD

**Issue by ed-ud** [netbox-community/netbox#15123]
### Deployment Type

Self-hosted

### NetBox Version

v3.7.1

### Python Version

3.9

### Steps to Reproduce

1. Change the Tags on an object such as a VM or IP Address
2. Look at the Change Log for the object - no new entry

### Expected Behavior

Changing the Tags on an object should cause a Change Log entry to be logged.

### Observed Behavior

No Change Log entry gets created when Tags are changed on an object.

**Comment by arthanson** [comment]
I think this is the same issue as #14947 which was fixed in #14986

**Comment by ed-ud** [comment]
Excellent... and thank you!  I don't know why my searches for this problem came up empty so that I could avoid a duplicate bug report.
