### ISSUE TITLE
Transmit Power Field in Interface Model

### ISSUE THREAD

**Issue by moetezz** [netbox-community/netbox#15124]
### NetBox version

v3.6.2

### Feature type

Data model extension

### Proposed functionality

I am proposing to Add a Transmit Power (dBm) Field in the Interface along with Channel Frequency and Width as It is also important for WiFi devices. The field would have numeric values

### Use case

in some cases, Engineers might want to specify the value of Transmit Power (dBm ) for the installation team to configure it as documented, And the best method to use NetBox for this.

### Database changes

Yes this would require to add a field to the Database. So new migration will be needed

**Comment by sleepinggenius2** [comment]
Transmit power was added to interfaces back in v3.1 with #7606. It shows as "Transmit power (dBm)" under the "Operation" field set on the Interface add/edit form and the "tx_power" field under the interface import form.

**Comment by moetezz** [comment]
My bad, Guess I wasn't paying attention to Operation section. Was looking for it in the Wireless section. Closing #15124
