### ISSUE TITLE
IPAM Site Prefixes render children indent when the parent is not assigned.

### ISSUE THREAD

**Issue by jchambers2012** [netbox-community/netbox#15142]
### Deployment Type

Self-hosted

### NetBox Version

3.7.2 and 3.6.5

### Python Version

3.11

### Steps to Reproduce

`Hide Depth Indicators` work as expected but with the indicator on can cause some confusion.
1. Navigate to IPAM -> Prefixes
2. Add new prefix with the following settings.
    PREFEX: 10.112.157.0/24
    DESCRIPTION: BROKEN PARENTS
    Site: DM-Akron
3. Create
4. Navigate to Organization -> Site -> DM-Akron -> Click Prefixes
5. 10.112.157.0/24 looks like it a child of 10.112.128.0/22
![image](https://github.com/netbox-community/netbox/assets/6090690/3100c4f9-83e0-4dd9-a797-fde7f4ced374)

This can be more "confusing" when adding more 45.x.x.x/x networks:
For example add the following Prefixes: 
- 45.0.0.0/8
- 45.25.0.0/16
- 45.25.25.0/24
- 45.25.25.0/29 - Assign to Site: DM-Akron

Global Prefixes View: 
Navigate to IPAM -> Prefixes
![image](https://github.com/netbox-community/netbox/assets/6090690/784c0226-9339-4321-9732-45cc577b77c3)

Site Prefixes View: 
Navigate to Organization -> Site -> DM-Akron -> Click Prefixes
![image](https://github.com/netbox-community/netbox/assets/6090690/c6118a68-f59a-4152-a106-144094b28e83)

### Expected Behavior

Since the parent is not "linked" to this Site the three dots should not be rendered or some other GUI object should be rendered pointing to it true parent? 

One thought when in this filter view:
- 10.112.128.0/22 should have 0 dots
  - 10.112.128.0/22 children should have 1 dot
- 10.112.157.0/24 should have 0 dots

### Observed Behavior

All prefix are indented based on where they live on the global prefix list:
![image](https://github.com/netbox-community/netbox/assets/6090690/f7c54728-4b54-47f2-b1f0-6952a9b649f4)

**Comment by jeremystretch** [comment]
> Goto https://demo.netbox.dev/ipam/prefixes/

Please revise your report above to remove all references to the demo instance.

**Comment by jchambers2012** [comment]
@jeremystretch  - removed - let me know if that will work as having existing data from the demo site was used in the screenshot examples above.

**Comment by jeremystretch** [comment]
This is working as expected; the indentation annotates each prefix's depth in the hierarchy. If you'd prefer not to see this, you can replace the default "prefix" column in the table configuration with "prefix (flat)", which does not annotate depth.
