### ISSUE TITLE
Defined range exceeds maximum supported size (4294967295) IPAM

### ISSUE THREAD

**Issue by altf4arnold** [netbox-community/netbox#15168]
### Deployment Type

Self-hosted

### NetBox Version

v.3.7.2

### Python Version

3.11

### Steps to Reproduce

Go to create a IP range in Ipam. 

Create an IPv6 /56 pool

### Expected Behavior

Creates a pool with a /56

### Observed Behavior

Marks :

```
Defined range exceeds maximum supported size (4294967295) 
```

It has a limit for v4 only

**Comment by altf4arnold** [comment]
This one looks easy enough that I could make a PR myself to fix this (and maybe try to fix the form in case of inserting a v6 prefix).

I just want to make sure I'm using this right and if there is no one already working on this

**Comment by jeremystretch** [comment]
Thank you for submitting this issue, however it appears that this topic has already been raised. Please see issue #12236 for further discussion.
