### ISSUE TITLE
Cable Trace and Rack not display SVG image.

### ISSUE THREAD

**Issue by chrisho95** [netbox-community/netbox#15161]
### Deployment Type

Self-hosted

### NetBox Version

v3.7.2

### Python Version

3.11

### Steps to Reproduce

1. Click on "RACKS -> Elevations"

2. See BAIE and SVG.

3. Image SVG is not displayed.

or

1. Click on a "DEVICE COMPONENTS -> Interfaces" 

2. Choose one "Name" who enabled and click

3. On the page, click on button "Trace" in "Connection -> Cable"

4. Image SVG is not displayed.

### Expected Behavior

I was expecting to see the image SVG.

![image](https://github.com/netbox-community/netbox/assets/82440344/4c1ef615-643a-4c00-a5cd-8a08621370ce)

![image](https://github.com/netbox-community/netbox/assets/82440344/5e4beac9-1d25-498b-b86c-ebdb1eeabbd4)

### Observed Behavior

When from the interface page of a device I click on the "Trace" button, I don't see the "live" SVG image representing the connections between the 2 devices and ports.

Same with the “Racks Eleveations” page.

However, I can still download the SVGs.

**Comment by jeremystretch** [comment]
Please see [this page](https://github.com/netbox-community/netbox/wiki/Common-Issues#rack-elevations-do-not-display-v27) in our wiki for tips on fixing your web server configuration to enable embedded SVG images.
