### ISSUE TITLE
Add interface type `DECT`

### ISSUE THREAD

**Issue by tschmidtb51** [netbox-community/netbox#15178]
### NetBox version

v3.7.2

### Feature type

Data model extension

### Proposed functionality

The interface type definition should be extended to allow for `DECT` interfaces.

### Use case

Currently, it is possible represent common DSL routers (e.g. AVM FRITZ!BOX 7590) in Netbox. However, interfaces that use the [DECT](https://en.wikipedia.org/wiki/Digital_enhanced_cordless_telecommunications) standard can't be modeled. However, that would be helpful as DECT can be used:
- for machine-to-machine communication (see DECT-2020, aka NR+)
- for smart home solutions, including but not limited to switch power sockets
- for voice transmissions
- as covered or unexpected channel by an attacker.

To enable the modeling in all of these scenarios (foremost the machine-to-machine communication), Netbox should include a generic value `dect`.

### Database changes

The new value must be inserted in the `netbox/dcim/choices.py`.

I'm not aware of any other changes.

### External dependencies

None.

**Comment by alehaa** [comment]
Adding a new type in the choices should be sufficient. I could provide a PR, But I'm unsure whether this is a category on its own or part of the existing Wireless / Cellular.

**Comment by jeremystretch** [comment]
My (admittedly very limited) understanding of DECT is that it is a communications standard rather than an interface type.

**Comment by tschmidtb51** [comment]
> My (admittedly very limited) understanding of DECT is that it is a communications standard rather than an interface type.

I would argue that it is an interface type and communication standard. It support similar features as Wifi/Celluar networks which are listed as interface types.

**Comment by tschmidtb51** [comment]
> Adding a new type in the choices should be sufficient. I could provide a PR, But I'm unsure whether this is a category on its own or part of the existing Wireless / Cellular.

I that case, I would probably sort it into cellular:

```suggestion
    TYPE_OTHER_WIRELESS = 'other-wireless'

    # Cellular
    TYPE_DECT = 'dect'
    TYPE_GSM = 'gsm'
