### ISSUE TITLE
Add "Last Login" to per user view and API output

### ISSUE THREAD

**Issue by zacho112** [netbox-community/netbox#15177]
### NetBox version

v3.7.2

### Feature type

Change to existing functionality

### Proposed functionality

Expose the `last_login` in the specific user view (GUI), as well as include it in the API response `api/users/users/`, just as `date_joined`.

### Use case

Ease user management/cleanup. Data is already present in the DB, just not visible via API.

**Comment by zacho112** [comment]
I guess this is a fairly simple changes to the template files `user/user.html` and maybe also `account/profile.html`, and the `users/api/serializers.py`

I can provide the PR my self if needed

**Comment by jeremystretch** [comment]
Assigned to you @zacho112, thanks for volunteering.
