### ISSUE TITLE
ASN Uniqueness between Private RIR

### ISSUE THREAD

**Issue by richard25000** [netbox-community/netbox#15172]
### Deployment Type

Self-hosted

### NetBox Version

v3.7.1

### Python Version

3.8

### Steps to Reproduce

Create a private RIR of A
Create a private RIR of B

### Expected Behavior

Add AS 65000 in A
Add AS 65000 in B

Both should work

Adding AS65000 again in either should fail.

### Observed Behavior

Cannot add AS65000 in B as exists in A.

Do not want to disable global uniqueness, but like in VRF's where duplicate IP's may exist between VRF's it is expected that duplicate AS's would exist between private RIR's.

**Comment by jeremystretch** [comment]
This is not a bug: Uniqueness for AS numbers is intentionally enforced globally. If you like like to propose changing this, please do so by submitting a detailed [feature request](https://github.com/netbox-community/netbox/issues/new?assignees=&labels=type%3A+feature&projects=&template=feature_request.yaml) including your use case.

**Comment by richard25000** [comment]
Then my question would be, what does the private tick box actually do..?

**Comment by jeremystretch** [comment]
This is explained [in the documentation](https://docs.netbox.dev/en/stable/models/ipam/rir/#private). Please note that privacy and uniqueness are unrelated aspects.
