### ISSUE TITLE
ASN Range check does not satisfy IANA ASN distribution

### ISSUE THREAD

**Issue by kornix** [netbox-community/netbox#15170]
### Deployment Type

Self-hosted

### NetBox Version

v3.7.2

### Python Version

3.9

### Steps to Reproduce

1. Add new ASN range;
2. Insert RIPE-2 ASN range start (2043) and end (2043) values (according to https://www.iana.org/assignments/as-numbers/as-numbers.xml);
3. Submit form.

### Expected Behavior

Since IANA assigned several single-AS ranges (e. g. 2043, 2047) to RIPE i propose:
- either allow range start value to be less **or equal** to range end value (preferred);
- or make range end value to be not mandatory.

### Observed Behavior

ASN Range form throws "Starting ASN (2043) must be lower than ending ASN (2043)." error message.

**Comment by jeremystretch** [comment]
This is not a bug: An range of ASNs (or really any type of object) requires a separate starting and ending value. Instead, you should create this as a single ASN if you need to track it.
