### ISSUE TITLE
Need ability to write plugins that contributes actions to objects.

### ISSUE THREAD

**Issue by rkiss** [netbox-community/netbox#15189]
### NetBox version

v3.7.2

### Feature type

New functionality

### Proposed functionality

Quite often I need to perform an action or trigger an external process starting from a specific object or set of objects.
While this is perfectly possible with Netbox scripts or external scripts that use Netbox API I believe it will be much more intuitive and open Netbox to a whole new set of use cases if a plugin can contribute actions to objects.
Such actions should show every time a table with such objects are presented or when the such an object is viewed or edited.
Additionally, such plugins could specify certain limitations like it should be active only on devices of a particular device type or role.
When such an action is triggered the plugin can show a dialog where more information can be collected from user then it would execute a `run` method in a similar way a Netbox script works.

### Use case

Possible applications:
- Send emails to a set of tenants. The email could be based on a template.
- Act upon a network range or device.
- Trigger some sort of automation for one or more devices.
- Trigger a "clone" operation over a device/location/site. Or a validation.

### Database changes

No change in database

### External dependencies

No extra dependencies needed. However, some plugins might require additional dependencies but that is not in scope.

**Comment by jeremystretch** [comment]
Thank you for your interest in extending NetBox. Unfortunately, the information you have provided does not constitute an actionable feature request. Per our [contributing guide](https://github.com/netbox-community/netbox/blob/develop/CONTRIBUTING.md), a feature request must include a thorough description of the proposed functionality, including any database changes, new views or API endpoints, and so on. It must also include a detailed use case justifying its implementation. If you would like to elaborate on your proposal, please modify your post above. If sufficient detail is not added, this issue will be closed.

**Comment by jeremystretch** [comment]
This issue is being closed as no further information has been provided. If you would like to revisit this topic, please first modify your original post to include all the requested detail, and then ask that the issue be reopened.
