### ISSUE TITLE
Make it possible to customize the default value for choice-set fields of various models (DCIM)

### ISSUE THREAD

**Issue by ihumster** [netbox-community/netbox#15225]
### NetBox version

v3.7.3

### Feature type

New functionality

### Proposed functionality

Ability to configure default values ​​for fields in forms for creating new items.

### Use case

For example, I need to change the default value of the `status` field for new `Devices` (`Planned` instead `Active`).

**Comment by jeremystretch** [comment]
Thank you for your interest in extending NetBox. Unfortunately, the information you have provided does not constitute an actionable feature request. Per our [contributing guide](https://github.com/netbox-community/netbox/blob/develop/CONTRIBUTING.md), a feature request must include a thorough description of the proposed functionality, including any database changes, new views or API endpoints, and so on. It must also include a detailed use case justifying its implementation. If you would like to elaborate on your proposal, please modify your post above. If sufficient detail is not added, this issue will be closed.

**Comment by ihumster** [comment]
@jeremystretch I'm not a developer and can't offer a description of the required changes to the codebase or database or views/api.

Use case for this functionality is lifecycle of devices in ours (and not only in ours) company - devices starts with 
`planned` status (They may be purchased, located at a supplier or warehouse, or even rack-mounted, but not yet in `active` status). It would be nice to be able to change the default status for newly created devices (now as I understand it, this is hadrcode).

**Comment by jeremystretch** [comment]
I'm going to close this out as no reasonably detailed implementation has been proposed. If anyone would like to spend some time thinking through that and sharing a plan, I'll be happy to re-open the issue for further discussion.
