### ISSUE TITLE
Interface VLAN group (Memory last filter) --> New Ideea: Replace VLAN group

### ISSUE THREAD

**Issue by LHBL2003** [netbox-community/netbox#15273]
### NetBox version

v3.7.1

### Feature type

Change to existing functionality
The original idea behind this feature request was to save the VLAN group filter field. Due to a revised proposal on the subject of tagged VLANs (https://github.com/netbox-community/netbox/issues/15530), my opinion has changed somewhat.

### Proposed functionality

Remove the VLAN group field and replace it with the Open Selector. This will better guide the user to make fewer incorrect selections.

The topic Multiselector for the Tagged VLAN field is suggested here as FR.
https://github.com/netbox-community/netbox/issues/15530

![image](https://github.com/netbox-community/netbox/assets/46369917/9308ec71-bcb9-4f42-b3e9-c403401cfcfa)

If possible, it would be good if the following fields are also preselected: 
- Tenant group
- Tenant
- VLAN group
![image](https://github.com/netbox-community/netbox/assets/46369917/320427d9-b6aa-42bc-a6a9-a4eba80ac013)

### Use case

We group the VLANs by location. We almost always have the same VLANs at all locations. If you do not select the VLAN group filter on the device interface, you may end up using the wrong VLAN.

**Comment by jeremystretch** [comment]
It wouldn't make sense to enable this behavior for a single field, and enabling it more generally would require a lot more consideration around the specific implementation: UI controls, example workflows, potential trade-offs, etc. @LHBL2003 would you like to add more detail to your proposal?

**Comment by LHBL2003** [comment]
I don't know what other details to add?
I also don't know where there are other fields that serve as filters and are not cached. Currently I only know "VLAN group" which serves as a filter in the properties.

The only main wish I have here is to save the selected value of VLAN group.

I know this is a filter field. But why doesn't it make sense to save it? After all, in my opinion, 99% of the time you select it over and over again.

Maybe you can tell me why it makes no sense to save the VLAN group field?

If you only have 5 VLANs, this may not matter. But if you have the same VLAN about 120 times at each location, then it's a different story. Or am I seeing this wrong?

**Comment by LHBL2003** [comment]
Hello Jeremystretch,

So I have reworked the case https://github.com/netbox-community/netbox/issues/15530 with another idea. I have also revised this suggestion again. I hope you like this idea. 

Personally, I have a good gut feeling that you might like this idea :D
