### ISSUE TITLE
Free IP addresses indicators gone

### ISSUE THREAD

**Issue by shunt24** [netbox-community/netbox#15275]
### Deployment Type

Self-hosted

### NetBox Version

v3.7.3

### Python Version

3.9

### Steps to Reproduce

click IPAM -> Prefixes -> IP Addresses

### Expected Behavior

In the list of IP Addresses shown there was always the status "available" with the grouped number of free IPs. 

### Observed Behavior

This "available" indicator is now gone. 

![Screenshot from 2024-02-26 14-30-59](https://github.com/netbox-community/netbox/assets/161326399/9fc517c1-376d-4df9-899b-d224ac1b36fa)

**Comment by jeremystretch** [comment]
> In the list of IP Addresses shown there was always the status "available" with the grouped number of free IPs.

Available IP addresses are annotated only when viewing the IP addresses under a specific prefix.

**Comment by shunt24** [comment]
Sorry for not describing my Issue clear enough. I have updated my Issue text. I am not seeing "available" under a specific prefix.

**Comment by jeremystretch** [comment]
The annotations appear only when no custom filtering or ordering is present. Once the table has been ordered by a specific column, the annotations are removed. You can reset the table to restore them.

**Comment by Melmaryul** [comment]
Hi Jeremy,

It appears that I am facing the same issue.
I just updated to the latest version (v3.7.6) and I can no longer see the available IP addresses under a specific prefix. I made sure that no filtering or ordering is present.

You can see the screenshot below:
![netboxprefixissue](https://github.com/netbox-community/netbox/assets/168092336/f4d09222-0cad-479d-95a2-06cebd5d95cd)
