### ISSUE TITLE
Support images as front view image in rack

### ISSUE THREAD

**Issue by taenzerme** [netbox-community/netbox#1529]
### Issue type
[x] Feature request

### Environment
* Python version:  3.4.2
* NetBox version: v2.1.5-dev

### Description
As netbox did add support for images with devices it would be great to support choosing one of these as a front view image that is displayed in the rack view. 

I already tried to implement this:

![screenshot 2017-09-22 13 11 31](https://user-images.githubusercontent.com/3618912/30742024-a215bcac-9f97-11e7-8e60-7a4b90ce9fcd.png)

![screenshot 2017-09-22 13 15 55](https://user-images.githubusercontent.com/3618912/30742157-2e192d74-9f98-11e7-8fa6-3ea4b751a931.png)

I did some quick code changes in my fork at https://github.com/taenzerme/netbox/tree/image-as-frontview. I guess doing it with a seperate <img/> element (and some z-index/position tweaking) inside the markup would be the cleaner way, but the inline style CSS works for me at the moment.

Maybe this could be helpful for the rest, too?

**Comment by jeremystretch** [comment]
We wouldn't want to use the ImageAttachment model here: we can just add `front_image` and `rear_image` file fields to the DeviceType model.

The hard part is manipulating the uploaded image to look halfway decent in the rack elevation. A 1U device in NetBox is rendered as a 226x19 pixel block, so there isn't a lot of space to work with. An uploaded image would need to be stripped of bordering whitespace and manipulated to ensure its height and width meet the specified dimensions. We _could_ allow for larger images, but that would require downsizing in the browser which probably wouldn't look great.

**Comment by darkstar** [comment]
Just something to consider early:
since devices can contain subdevices that can be slotted into them, there will be a desire to also have those slot devices represented with an image overlay. I'm thinking of a blade chassis, for example.

**Comment by jeremystretch** [comment]
> since devices can contain subdevices that can be slotted into them, there will be a desire to also have those slot devices represented with an image overlay

The ratio of development time needed to value delivered for a feature like this is _extremely_ high. It would take quite a bit of time and effort to implement such a novelty. I think it's reasonable to support elevation images as requested in the initial comment, but that's probably as far as we'll go. (For the people who _really_ want pretty pictures, there are several tools costing $10K+/yr that will provide them.)

**Comment by cyberjacob** [comment]
Could this (and the sub-devices) be handled more easily with SVGs?

**Comment by taenzerme** [comment]
@jeremystretch I understand where you're coming from. My request was not intended to go into a "full blown" solution for this. I never thought about sub-devices and wouldn't go as far as taking it there at all. If someone really needs to represent its blade server structure one can always do this - in Photoshop ;-)

@cyberjacob I thought about this, too. Actually I don't know if that really is worth the effort as we're simply taking photos of our racks with a smartphone and slice them in Photoshop. 

The real value of photos here is that it helps in support on site when you have racks that have several different types of hardware (i.e. "It's the NIC port on the far right!")

**Comment by jeremystretch** [comment]
@cyberjacob brings up an interesting idea. Can we render the entire rack elevation in SVG using the HTML5 canvas? Would be nice to ditch the convoluted layered approach currently in use.

**Comment by Schnatterowski** [comment]
I just had a look at the way opendcim is handling this. They're downsizing larger PNGs to 226x21 pixels in the browser. You can look at it here (login with dcim/dcim): 

http://www.opendcim.org/demo/cabnavigator.php?cabinetid=1

If you look at the Cisco switch, the original image is 501x48 pixels. I think the browser-downsized version looks OK. Anyway, one could argue that it's the user's responsibility to use front/rear device images that look good enough for his/her purpose.

I vote for browser-downsizing, as it's more flexible. One can use perfectly fitting images in the target resolution, then there's nothing to downsize. Anybody using larger images, even with a different ratio, would have to decide for himself if he's happy with the result.

A max resolution and file size check could (and probably should) still be implemented.

Thanks for considering this.

**Comment by jeremystretch** [comment]
Blocked by #2248

**Comment by cyberjacob** [comment]
That sounds very reasonable for an MVP, and should be fairly easy to expand on in the future.

**Comment by jsalatiel** [comment]
Any progress on this ?
