### ISSUE TITLE
API filter of assigned_object_id fails, but nbshell is correct

### ISSUE THREAD

**Issue by josh-belwave** [netbox-community/netbox#15309]
### Deployment Type

Self-hosted

### NetBox Version

v3.7.2

### Python Version

3.8

### Steps to Reproduce

curl -X GET "https://netbox.example.com/api/ipam/ip-addresses/?assigned_object_id=5597" -H "Authorization: Token <redacted>" 

nbshell#
>>> IPAddress.objects.filter(assigned_object_id='5597')
<RestrictedQuerySet [<IPAddress: x.x.x.x/32>]>

### Expected Behavior

API call should be the same filtered result

### Observed Behavior

curl statement returns all ip-addresses

nbshell provides correct filtered data

**Comment by josh-belwave** [comment]
I stumbled on this issue with the following function using pynetbox:

ip_obj = netbox.ipam.ip_addresses.filter(assigned_object_id=loopback_interface.id)

**Comment by jeremystretch** [comment]
URL query parameters and Python ORM filters are entirely different. Please consult the API documentation to determine what filters are supported for each type of object.

**Comment by josh-belwave** [comment]
I’ve looked through the doc’s can you provide a link that shows these supported filters?



On Feb 29, 2024, at 6:57 AM, Jeremy Stretch ***@***.***> wrote:

﻿

URL query parameters and Python ORM filters are entirely different. Please consult the API documentation to determine what filters are supported for each type of object.
