### ISSUE TITLE
Can't select 3DES encryption algorithm in IKE Proposals.  Selection changed to DES.

### ISSUE THREAD

**Issue by cloudcapps** [netbox-community/netbox#15316]
### Deployment Type

Self-hosted

### NetBox Version

v3.7.3

### Python Version

3.10

### Steps to Reproduce

1. Cilck into the IKE Proposals section under VPN > Security.
2. Click to add a new IKE Proposal or edit an existing proposal.
3. Select 3DES from the encryption algorithm dropdown.
4. Selection will instantly be changed to DES instead.

### Expected Behavior

I should be able to select 3DES as an encryption algorithm.

### Observed Behavior

My selection was changed to DES instead.

**Comment by jeremystretch** [comment]
This is a bug in the form field choices; the value for 3DES is show twice:

```python
        (ENCRYPTION_3DES, '3DES'),
        (ENCRYPTION_3DES, 'DES'),
```

Thanks for catching this!
