### ISSUE TITLE
Device Types "All Data (YAML)" export does not include Description

### ISSUE THREAD

**Issue by szeestraten** [netbox-community/netbox#15322]
### Deployment Type

Self-hosted

### NetBox Version

v3.7.3

### Python Version

3.8

### Steps to Reproduce

1. Create Device Type with a description
2. Export Device Types with "All Data (YAML)" export
3. Examine export which does not include the Description field of the device type the set description that was set

Reproducible on demo.netbox.dev

### Expected Behavior

Expect the Description field to be present in export.

### Observed Behavior

No Description field is present in export.

**Comment by jeremystretch** [comment]
Looks like the description field is missing from the `to_yaml()` method on the DeviceType model. It's probably worth a quick audit for missing fields in the method on other models too.

**Comment by jeremystretch** [comment]
The `description` field is missing from ModuleType as well.
