### ISSUE TITLE
Free IP addresses are no longer visible under prefixes

### ISSUE THREAD

**Issue by sirsnork** [netbox-community/netbox#15345]
### Deployment Type

Self-hosted

### NetBox Version

v3.7.2

### Python Version

3.11

### Steps to Reproduce

1. On IPAM
2. Prefixes
3. Select a prefix
4. IP Addresses

### Expected Behavior

Free IP addresses are displayed (and clickable) under IPAM -> Prefixes -> IP Addresses

### Observed Behavior

There appears to be a reversion of issue [8131](https://github.com/netbox-community/netbox/issues/8131). 

I see a list of existing IP's but do not see the free IP blocks that were present on previous versions. This is on a non full prefix with full permissions. I don't see mention of this being resolved already int he 3.7.3 release notes.

**Comment by sirsnork** [comment]
Ok so this appears to be due to a Table Configuration under User Preferences. But not the prefix table as I deleted that by itself and the problem remained, wiping out all my table configs and I get free IP addresses showing again.

**Comment by PieterL75** [comment]
This happens when you sort the table.
It is not possible to show free ip address, If sorted in another way that per ip address.

Solution is to click the little red x on the table headers to remove the sorting

**Comment by sirsnork** [comment]
Ahh, thank you! I'm betting that was it. I was probably sorting by IP Address anyway so didn't even think to look there
