### ISSUE TITLE
The VirtualMachineType in GraphQL is missing the `contacts` property

### ISSUE THREAD

**Issue by klstilling** [netbox-community/netbox#15347]
### NetBox version

v3.7.3

### Feature type

Data model extension

### Proposed functionality

I propose that the `ContactMixin` class is added to the `VirtualMachineType` class in the GraphQL files. I was wondering where I could find it, as I could find the property in the `DeviceType` class. I have a pull request ready which I'd be happy to submit for review.

### Use case

It allows users to get information about contacts associated with virtual machine objects

### Database changes

None

### External dependencies

None

**Comment by jeremystretch** [comment]
Sounds like a bug.

**Comment by klstilling** [comment]
@jeremystretch I'd be happy to help. By applying the changes in https://github.com/klstilling/netbox/commit/e76b0184a7235209a36fe49e0d6a2c47043a2d57 the property becomes available in the GraphQL API. If there's anything I can do, just poke me.

**Comment by arthanson** [comment]
This is blocked by #9856 as it is completely rewritten what is returned.

**Comment by jeremystretch** [comment]
Although we are completely gutting the GraphQL code with the move to Strawberry in v4.0, this seems like a simple fix we can squeeze into the current code base without much hassle.
