### ISSUE TITLE
Quick access to SavedFilters

### ISSUE THREAD

**Issue by PieterL75** [netbox-community/netbox#15348]
### NetBox version

v3.7.3

### Feature type

Change to existing functionality

### Proposed functionality

The Saved Filters #9623 are a nice feature. But I would to a more intuitive access in the UI to that
- Show the saved filters in a dropdown on the model page
![image](https://github.com/netbox-community/netbox/assets/74899468/76bb3497-a7b1-4e4b-9671-06a7f4d12211)

### Use case

In orde to access the saved filter, I have to
- open de model
- click 'filter'
- select the filter from the dropdown
- scroll all the way down
- click search

Having the saved filters on the model search page will make it a single-click action

**Comment by jeremystretch** [comment]
I've opened this for an owner, with the caveat that any work be based on the `feature` branch due to the UI overhaul for the upcoming v4.0 release.

**Comment by Julio-Oliveira-Encora** [comment]
Could you please assign it to me?

**Comment by Julio-Oliveira-Encora** [comment]
@jeremystretch Should I work on it using the v4?

**Comment by jeremystretch** [comment]
Thanks for all your work on this @Julio-Oliveira-Encora!

![screenshot](https://github.com/netbox-community/netbox/assets/13487278/97a801ce-55d1-463f-b992-9da14bb5e745)
