### ISSUE TITLE
Fix flicker on page load when color mode is set to dark

### ISSUE THREAD

**Issue by jeremystretch** [netbox-community/netbox#15340]
### Deployment Type

NetBox Cloud

### NetBox Version

v4.0

### Python Version

3.11

### Steps to Reproduce

1. Open the NetBox UI as an anonymous user (not logged in)
2. Click the toggle button at top right to switch to dark mode
3. Navigate among pages several times

### Expected Behavior

The application of the dark mode theme should persistent without interruption between page loads.

### Observed Behavior

A "flicker" is sometimes visible when a new page loads, as the DOM is initially rendered in light mode and then switched to dark mode. This occurs because the user's preferred theme is being read from local storage _after_ the DOM has finished loading.

Note that this does _not_ occur when authenticated as a known user with the color preference set to dark mode. (In this case, `data-bs-theme="dark"` is set on each page's `<body>` tag directly in the page source.)

**Comment by samumatic** [comment]
This only works in Chrome, in Firefox the theme resets after a reload.
