### ISSUE TITLE
virtual machine model - field adjustments to better suit vm concepts

### ISSUE THREAD

**Issue by ITJamie** [netbox-community/netbox#15359]
### NetBox version

v3.7.3

### Feature type

Data model extension

### Proposed functionality

new fields:
  "is_template" field - boolean type - to denote if a VM is a template VM which gets used to clone new vms
  "bios_type" field - choices - legacy or uefi options

adjustments:
  status field - extend default choices with - suspended (or paused)

### Use case

the status field doesn't account for the fact that vms can be paused

the template field would be useful for documenting what templates exist in a cluster
the bios type field would let us document if a VM is uefi or legacy bios

these are pretty standard concepts across most hypervisors (vmware vcenter, proxmox, xcp-ng as examples where all the above apply) and would be useful in the standard model rather than custom fields

### Database changes

two additional fields on virtual machine model

**Comment by troycarpenter** [comment]
FYI, the status field can already be extended using the [FIELD_CHOICES](https://netbox.spwifi.arrisi.com/static/docs/configuration/data-validation/#field_choices) configuration parameter in configuration.py.  In fact, I added "Paused" and "Template" to my installation based on your suggestion.

**Comment by jeremystretch** [comment]
@ITJamie you've proposed three somewhat related but separate changes. Please open a separate FR for each, including detailed use cases.
