### ISSUE TITLE
Allow for custom names for Identity Provider text in the Login link

### ISSUE THREAD

**Issue by vmorris** [netbox-community/netbox#15375]
### NetBox version

v3.7.3

### Feature type

Change to existing functionality

### Proposed functionality

Recently `oidc` was added to the auth backend (https://github.com/netbox-community/netbox/issues/14587) to make the login link more user friendly.

In the issue, @llamafilm also requested the ability to customize this text, as there are many different OIDC IdP. (https://github.com/netbox-community/netbox/issues/14587#issuecomment-1877804701)

This request is to add that functionality to specify a custom name in the login link for any social login provider.

### Use case

There are many different social IdPs and users will appreciate knowing which one they are going to be authenticating to.

### Database changes

None

### External dependencies

None

**Comment by alehaa** [comment]
IMHO this shouldn't be exclusive to OIDC. Defining a custom name for other social auth types like KeyCloak or SAML would be good, too.

**Comment by llamafilm** [comment]
Agreed. @vmorris Can you edit this request to make it generic?  I have a patch already, I can make a PR.

**Comment by vmorris** [comment]
@llamafilm okay, updated, thanks!

**Comment by tobast** [comment]
Hello,
I may submit a PR for this if you want.

**Comment by vmorris** [comment]
@tobast yes please!
