### ISSUE TITLE
Point out a possible cause of requiring migrations to be run is the addition of new plugins

### ISSUE THREAD

**Issue by Supermathie** [netbox-community/netbox#15371]
### Change Type

Addition

### Area

Development

### Proposed Changes

If someone installs a plugin that has migrations of its own, they may not know to run migrations.

For example: https://netdev-community.slack.com/archives/C01P0FRSXRV/p1709851212417359?thread_ts=1709848122.367389&cid=C01P0FRSXRV

Adding this case to the error message may help remind people to do so.

**Comment by jeremystretch** [comment]
Migrations are only one part of installing a plugin. Each plugin is responsible for maintaining its own installation documentation, and the administrator performing the installation is obligated to follow it. It would not be feasible to prescribe sufficient installation instructions for every potential plugin in the NetBox documentation.
