### ISSUE TITLE
Help links in the Event Rules form provide erroneous information

### ISSUE THREAD

**Issue by rboucher-me** [netbox-community/netbox#15370]
### Deployment Type

NetBox Cloud

### NetBox Version

v3.7.3

### Python Version

3.11

### Steps to Reproduce

1. Create or Edit an Event Rule (Operations > Event Rules >  +Add)
2. Scroll down to "Conditions" input text box
3. Click on "JSON" help link below it (Enter parameters to pass to the action in JSON format.)
4. Scroll down to "Action data" input text box
5. Click on "JSON" help link below it (Enter parameters to pass to the action in JSON format.) 

In both cases, the links take you to the [json.org](https://www.json.org/json-en.html) homepage, which does not provide relevant information.

### Expected Behavior

The "Conditions" text box should provide help links to the following documentation sections:
- [Event Rules](https://docs.netbox.dev/en/stable/features/event-rules/) (ideally expanded to include information about the available context data, which I believe is only `data`)
- [Conditions](https://docs.netbox.dev/en/stable/reference/conditions/)

The "Action data" text box should provide a help link to an expanded version of [Event Rules](https://docs.netbox.dev/en/stable/features/event-rules/) that includes information about the available context data (which I believe is `event`, `model`, `timestamp`, `username`, `request_id`, and `data`).

### Observed Behavior

Help links go to [json.org](https://www.json.org/json-en.html)

**Comment by jeremystretch** [comment]
The hyperlinks provided in the form field help texts are correct. The intent is merely to indicate to the user the supported data format, in case they are not familiar with JSON.

> The "Action data" text box should provide a help link to an expanded version of [Event Rules](https://docs.netbox.dev/en/stable/features/event-rules/) that includes information about the available context data (which I believe is event, model, timestamp, username, request_id, and data).

There is no such context; any optional action data associated with an event rule is completely arbitrary.
