### ISSUE TITLE
Improved help links in the Event Rules form

### ISSUE THREAD

**Issue by rboucher-me** [netbox-community/netbox#15384]
### NetBox version

v3.7.3

### Feature type

Change to existing functionality

### Proposed functionality

Update the existing link to [json.org](https://www.json.org/json-en.html) in the Event Rules form to the relevant NetBox documentation pages.

Under the "Conditions" input text box, the following documentation links could be provided:
- [Event Rules](https://docs.netbox.dev/en/stable/features/event-rules/) 
- [Conditions](https://docs.netbox.dev/en/stable/reference/conditions/)

### Use case

This would guide users new to the Event Rules feature to the appropriate syntax expected for defining conditions.

**Comment by rboucher-me** [comment]
I'd like to volunteer to submit a suggested implementation for this (in part to learn the process)

**Comment by jeremystretch** [comment]
@rboucher-me I've assigned this to you
