### ISSUE TITLE
Netbox openapi schema is generating incorrect response types

### ISSUE THREAD

**Issue by deathbeam** [netbox-community/netbox#15404]
### Deployment Type

Self-hosted

### NetBox Version

v3.7.3

### Python Version

3.9

### Steps to Reproduce

1. Check swagger for /api/dcim/sites
2. Create some dummy site with random ASN
3. Observe that swagger openapi schema tells that response for site.asns is supposed to be list of integers (e.g ids)
4. Observe that actual rest response for site.asns is the asns objects themselves

![image](https://github.com/netbox-community/netbox/assets/5115805/d4fbb74b-c38f-4faa-a18e-0ad65fa481f5)

![image](https://github.com/netbox-community/netbox/assets/5115805/4d39aad6-34f8-4b6f-bc99-5dfe78204028)

### Expected Behavior

Openapi schema and actual API response must always match otherwise the schema is basically unusable. The response and schema used to match in past (confirmed on 3.4.5 at least) so something broke since.

### Observed Behavior

Schema and response do not match. Observed behaviour is for site.asns, configcontext.roles, configcontext.tenants, virtualizationinterface.tagged_vlans, but there are probably more.

**Comment by deathbeam** [comment]
Is this really low severity? This breaks clients that use the openapi to generate/implement clients for netbox and its pretty big regression.

**Comment by jeremystretch** [comment]
Yes, it's considered low severity as only the schema is affected; the function of the API itself is not.

Of course, if this is pressing for you, you are more then welcome to submit a PR for it. Can I assign this to you?

**Comment by olekgo** [comment]
Interface.TaggedVlans is another one

**Comment by deathbeam** [comment]
Looks like this is now mostly resolved
