### ISSUE TITLE
Rack Order / Rack Weights - currently theres no way to define which rack is to the left or right of a rack.

### ISSUE THREAD

**Issue by ITJamie** [netbox-community/netbox#15412]
### NetBox version

v3.7.3

### Feature type

Data model extension

### Proposed functionality

add an "order/weight" field to rack objects.
use this weight field to decide the order of racks. currently, this happens by name of racks. which may not be correct and may be inverted if a row counts from a higher number on the left to lower numbers on the right.

### Use case

places this info would be used:
- elevation views - to sort order of racks
- rack view - on the breadcrumb menu there are left and right arrows to step through the rack that is left or right of the current rack

**Comment by ravinald** [comment]
When viewing racks you can do a reverse sort as a workaround.  I was pondering this similar issue and how to make the sort order persistent.  It probably makes sense to have this at the location object.

**Comment by jeremystretch** [comment]
> use this weight field to decide the order of racks. currently, this happens by name of racks. which may not be correct and may be inverted if a row counts from a higher number on the left to lower numbers on the right.

NetBox itself does not attempt to track the physical location of racks relative to one another; there is no concept of "left" or "right." Further, a simple weight or ordering field would not be sufficient to convey this, as it does not address grouping or the orientation of individual racks. Introducing such a field would predictably beget additional feature requests for modeling more advanced layouts, which is currently our of scope for the core product.

Fortunately, there is a [floorplan plugin](https://github.com/netbox-community/netbox-floorplan-plugin) which provides this functionality and more.
