### ISSUE TITLE
Data source for Amazon S3 being able to accept S3 compatible server

### ISSUE THREAD

**Issue by javierdelapuente** [netbox-community/netbox#15427]
### NetBox version

v3.7.4

### Feature type

Change to existing functionality

### Proposed functionality

Data sources of type `Amazon S3` do not work with compatible S3 servers. The proposal is to allow S3 compatible servers to be used as data sources.

Currently, there is a datasource of type "Amazon S3", that uses Amazon S3 in AWS. When creating the data source, the URL protocol and domain/netloc are not taken into account (except to obtain the region), so by default only AWS can be used.

The proposal is to add the argument `endpoint_url` to construct the boto3.resource, so S3 compatible servers can be used. The proposed change will be located in here: https://github.com/netbox-community/netbox/blob/4adb44f60d91fec19c800ea0e03800e2eb338f06/netbox/core/data_backends.py#L147

As a workaround, environment variables can be used (like `AWS_ENDPOINT_URL`), but that limits all S3 data sources to reside in that url.

### Use case

This feature will allow NetBox users to use other cloud providers or to host their own S3 compatible servers instead of using AWS to store their scripts and reports for `Amazon S3` datasources.

### Database changes

None

### External dependencies

None

**Comment by jeremystretch** [comment]
@javierdelapuente would you like to own this?

**Comment by javierdelapuente** [comment]
Yes, I will pleased to help!

**Comment by jeremystretch** [comment]
@javierdelapuente thanks, I've assigned this to you.
