### ISSUE TITLE
Add VLANs & VLAN Groups to related objects of site groups

### ISSUE THREAD

**Issue by PaulR282** [netbox-community/netbox#15429]
### NetBox version

v3.7.4

### Feature type

Change to existing functionality

### Proposed functionality

Add VLAN Groups and VLANs to the related objects of site groups.

### Use case

Since VLANs and VLAN Groups can be assigned to site groups, they should appear in the related objects of the site groups.
Current situation:
![image](https://github.com/netbox-community/netbox/assets/47193860/e75f436a-c256-471d-b7b6-f6d7ed711451)

**Comment by jeremystretch** [comment]
> Since VLANs and VLAN Groups can be assigned to site groups

VLANs cannot be assigned to site groups. VLANs can be assigned to site or to _VLAN_ groups, and a VLAN group may be scoped to a site group. But why did you single out site groups in your proposal? VLAN groups can also be assigned to regions, sites, locations, cluster groups, and clusters: Only the site view currently included VLAN groups under related objects. We should be consistent.

**Comment by PaulR282** [comment]
> > Since VLANs and VLAN Groups can be assigned to site groups
> 
> VLANs cannot be assigned to site groups. VLANs can be assigned to site or to _VLAN_ groups, and a VLAN group may be scoped to a site group. But why did you single out site groups in your proposal? VLAN groups can also be assigned to regions, sites, locations, cluster groups, and clusters: Only the site view currently included VLAN groups under related objects. We should be consistent.

Yes, that is right, my bad. So the functionality should be adding VLAN Groups to the related objects of site groups, regions, site, locations, cluster groups and clusters.
