### ISSUE TITLE
Add Relevant Cloud Product Links

### ISSUE THREAD

**Issue by jordanrvillarreal** [netbox-community/netbox#15434]
### Change Type

Addition

### Area

Other

### Proposed Changes

The open source documentation is currently linked from the NBL Cloud application.  While the documentation itself largely holds consistent, there are some small areas that can be confusing for Cloud users.  

One example is the steps for configuring Azure/Entra SSO. The OSS documents point to manipulating the configuration.py file, where as the Cloud product does not support direct configuration.py editing.  There is a separate set of instructions for enabling that on the NBL docs page.

It would be helpful for the documentation to provide relevant links to the Cloud documentation where feature disparity exists.  
```[tasklist]
### Tasks
```

**Comment by jeffgdotorg** [comment]
I'll own this issue for the time being. I'm going to start by doing some research on how other projects approach this kind of challenge.

**Comment by jeremystretch** [comment]
@jeffgdotorg are you still planning to make these changes?
