### ISSUE TITLE
Missing information reference for Apps and models in Netbox

### ISSUE THREAD

**Issue by SebastianClaesson** [netbox-community/netbox#15459]
### Change Type

Correction

### Area

Configuration

### Proposed Changes

Adding a new informational box with;

> [!TIP]
> All default apps and models can be found at https://github.com/netbox-community/netbox/tree/develop/docs/models.

This might be unclear as the models and apps are named differently from the Netbox REST API, which was the natural location for me to look for the naming convention.

For example, the rest api uses the following names for models;
![image](https://github.com/netbox-community/netbox/assets/34689432/4f829ecd-f4b4-4a08-9dc7-c59ebe557e23)

While these are the correct ones;
![image](https://github.com/netbox-community/netbox/assets/34689432/b037ed52-05e6-4364-b7d3-8dd51026a2ee)

**Comment by jeremystretch** [comment]
All models are [documented](https://docs.netbox.dev/en/stable/models/circuits/circuit/) under the "Data Model" section of the documentation.
