### ISSUE TITLE
Quality of Life for creating Devices/VMs: Option to directly create a loopback interface

### ISSUE THREAD

**Issue by CoLuxe** [netbox-community/netbox#15458]
### NetBox version

v3.7.4

### Feature type

Data model extension

### Proposed functionality

While creating a device or VM, adding an option/checkbox to automatically add a loopback interface in combination with the standard loopack ip adresses -> #15457 

### Use case

Almost every device/Host/VM has a loopback interface with the standard ip adresses.
Making it possible to add this while creating the device/Host/VM makes it much easier and faster -> QoL

**Comment by jeremystretch** [comment]
Thank you for your interest in extending NetBox. Unfortunately, the information you have provided does not constitute an actionable feature request. Per our [contributing guide](https://github.com/netbox-community/netbox/blob/develop/CONTRIBUTING.md), a feature request must include a thorough description of the proposed functionality, including any database changes, new views or API endpoints, and so on. It must also include a detailed use case justifying its implementation. If you would like to elaborate on your proposal, please modify your post above. If sufficient detail is not added, this issue will be closed.

**Comment by jeremystretch** [comment]
This issue is being closed as no further information has been provided. If you would like to revisit this topic, please first modify your original post to include all the requested detail, and then ask that the issue be reopened.
