### ISSUE TITLE
Add a field for height

### ISSUE THREAD

**Issue by mrtn-r** [netbox-community/netbox#15455]
### NetBox version

v3.7.4

### Feature type

Data model extension

### Proposed functionality

Add a field for "height" in the "Location"-section of the device under "longitude", together with a "units" field.

The "height" field should accept any positive or negative numeric value, while the "units" field should accept anything. 
Examples (height; units):
-  "1.5; Level" Height could be a level in a building
- "-5; m NAP" Physical height with accompanying vertical reference [^1]

[^1]:There are multiple vertical reference points, depending on the country you're in, see for example https://en.wikipedia.org/wiki/Vertical_datum#/media/File:Vertical_references_in_Europe.svg

### Use case

When having multi-story buildings, latitude and longitude are just not enough to locate a device on a map.

### Database changes

Two new fields are required

**Comment by jeremystretch** [comment]
This would make sense only for a handful of cases, and would be confusing in others. (What is the "height" of a building or room? Why would we care?) You can add a [custom field](https://docs.netbox.dev/en/stable/features/customization/#custom-fields) to the location model in your NetBox deployment to track this information if it makes sense for your use case.

**Comment by mrtn-r** [comment]
Maybe you misread, i meant the location-section of devices, not locations itself.
 mean the locations section where devices got the coordinate fields via #11305

**Comment by jeremystretch** [comment]
I'm afraid that doesn't make any more sense. Again, you can add a custom field to hold this data if it makes sense for your specific use case.

**Comment by jeremystretch** [comment]
This issue is being closed as no further information has been provided. If you would like to revisit this topic, please first modify your original post to include all the requested detail, and then ask that the issue be reopened.
