### ISSUE TITLE
Allow localhost more than one time (127.0.0.1 & ::1)

### ISSUE THREAD

**Issue by CoLuxe** [netbox-community/netbox#15457]
### NetBox version

v3.7.4

### Feature type

Change to existing functionality

### Proposed functionality

Currently every IP Adress is unique. So one IP adress can only exist once.
Since every device has a Loopback Interface and a standard IP adress assigned too it (127.0.01 & ::1) it should be possible, to create both IPs for every device/VM once.

### Use case

When using applications on devices or VMs, often you dont use the build-in webserver for security reasons.
So the application only runs on the loopback interface and a reverse proxy redirecting to that.

**Comment by jeremystretch** [comment]
This issue is being closed as no further information has been provided. If you would like to revisit this topic, please first modify your original post to include all the requested detail, and then ask that the issue be reopened.
