### ISSUE TITLE
Add possibility of defining custom field choices for cable status

### ISSUE THREAD

**Issue by edaleand** [netbox-community/netbox#15460]
### NetBox version

v3.7.3

### Feature type

Change to existing functionality

### Proposed functionality

Add cable status to the list of configurable field values:

https://docs.netbox.dev/en/stable/configuration/data-validation/#field_choices

### Use case

Users would be able to define custom cable statuses. In our case we often pull the cables before the equipment is mounted in the rack, so wire crew would like a status for cables that are done but not connected ("pulled" or "installed", for instance).

**Comment by jeremystretch** [comment]
Custom cable statuses are not supported because the hard-coded values have special significance and are referenced e.g. by the toggle button on the device interfaces list.

> so wire crew would like a status for cables that are done but not connected

This is the purpose of the "planned" status.
