### ISSUE TITLE
Increase documentation on related objects

### ISSUE THREAD

**Issue by jvalente-salemstate** [netbox-community/netbox#15470]
### Change Type

Addition

### Area

Other

### Proposed Changes

Within Netbox itself, the only information about related fields seems to be at the bottom of the page.

`Related objects may be referenced by any unique attribute. For example, vrf.rd would identify a VRF by its route distinguisher`

Regardless of whether the objects being uploaded have a VRF attribute, it’s the example given. It’s not clear how and where to do this. Is this `{{vrf.rd}}` or just `vrf.rd`? Do all fields accept this, or just certain ones? Can these be nested? Eg can an interface get the part number of its parent device’s device type? The vrf example is also entirely unhelpful to someone who may have no idea what a VRF is and solely has permissions to update Rack and cable information. 

The example seems straightforward but what about a reference to the device and interface to which an IP is assigned? It’s not `.device` or `.device.name`, unless it works differently here from the REST API and export templates. 

Going off the example, not many would guess it’s `.assigned_object.device.name`

Taking a look at the documentation, the term “related object” has a single result with information. It’s the output of an example REST API request. It’s how I figured out the device name but no still have no about interface name.

Export templates also has a few examples, with `{{ device.primary_ip.address.ip }}` being the most complex. 

Currently it seems my options are making REST api queries, and noting the schema of the response or delving into the code. Personally, yeah, I and most of the folks filing GitHub issues know how to do it. However, it’s a usability issue—and deterrent to implementing netbox—for those who are not familiar with making API calls or don’t know enough Python to read the code base. Fortunately the solution would just be checking documentation.

I am suggesting:

- Documentation, seems like Data Models would be best, on which attributes of related objects can be accessed and how.
- Either a footer with an applicable example for each upload page or at least one with a higher degree of relevancy to most than vrf. For both,  link to the docs for in depth info. 

If there is documentation somewhere then it’s just a matter of making it more accessible because I could not find it, even with the search on the docs site.

**Comment by jeremystretch** [comment]
> Documentation, seems like Data Models would be best, on which attributes of related objects can be accessed and how.

The fields of each model are already documented in the "Data Model" section of the [documentation](https://docs.netbox.dev/en/stable/). What specifically are you proposing be added?

> Either a footer with an applicable example for each upload page or at least one with a higher degree of relevancy to most than vrf.

This would be extremely cumbersome to maintain, and largely redundant to the model documentation that already exists.

**Comment by jvalente-salemstate** [comment]
@jeremystretch I am referring to the related fields (more specifically how to reference them) and not the fields of the objects themselves. Those are definitely clearly documented in detail. 

I am proposing adding a bit more documentation on how to reference an object's related objects and its fields, and within the data model documentation would be a good location. For many objects it's straight forward, like `rack.site.name` but if it's an IP, the information about serialization and generic relations is the REST API docs and it doesn't list all the cases, just noting:


> Some objects within NetBox have attributes which can reference an object of multiple types, known as generic relations. For example, an IP address can be assigned to either a device interface or a virtual machine interface. When making this assignment via the REST API, we must specify two attributes...

A more specific list would be helpful, for example.

The information is present in the documentation but is not as accessible or intuitively placed for users who may not be the administrators of Netbox or don't have or need that in depth knowledge of the data model. 

It would help with allowing people who aren't_really in a role where _that's_ their responsibility to still work with Netbox. That could be the people responsible for the VM clusters making uploads or creating an export template, or someone just working with physical inventory and sites.  If they're reading the documentation on the data model to read the field names for an ip and a device it isn't obvious that they should read the REST API docs on serialization for referencing different types of objects. 

A link telling them to check the API docs or a tip on pages like IPAddress that it should use `assigned_object` would be enough I think. On the export template page there is a section about using the API to retrieve templates. Maybe something here to direct the reader to the full api documentation for the related object fields. 

When I couldn't find it in the device model documentation I went to the API docs and found the information or how to get it. I'm familiar with APIs and figured it'd be there but that may be the case for all users. My suggestion is just adding those details, or info on where it's documented, so those users within Netbox and more readily find it in the documentation.

**Comment by jeremystretch** [comment]
@jvalente-salemstate I've assigned this to you. Please submit a PR with your proposed changes and we can discuss.

**Comment by jvalente-salemstate** [comment]
@jeremystretch Thanks. It may be a few days so I can try to work out how to approach that (I'll have one our student staff, who'd be doing some of the work but not administration of netbox note where it's clear or unclear to them) and read up on anything i may need specific to mkdocs.

Also, not entirely in this scope but certainly helpful for documentation: can I fix the example(s) in the REST API docs?

The id and URL don't match in a few cases and even I had to stop and think for a second whether I was misunderstanding something about the assignments.  See: the id and url for the interface

```json
{
    "id": 56296,
    "url": "http://netbox/api/ipam/ip-addresses/56296/",
    "assigned_object_type": "dcim.interface",
    "assigned_object_id": 69000,
    "assigned_object": {
        "id": 69000,
        "url": "http://netbox/api/dcim/interfaces/69023/",
        "device": {
            "id": 2174,
            "url": "http://netbox/api/dcim/devices/2174/",
            "name": "device105",
            "display_name": "device105"
        },
        "name": "ge-0/0/0",
        "cable": null,
        "connection_status": null
    },
```

**Comment by jeremystretch** [comment]
@jvalente-salemstate are you still planning to work on this?

**Comment by jvalente-salemstate** [comment]
> @jvalente-salemstate are you still planning to work on this?

Yeah, just been in the weeds with NIST audit.  If it's fine to submit a PR with this closed, you can also close this and I'll submit it later on. I don't want to add a backlog of open issues for you if not necessary since it may still be another few weeks. 

One of the folks I did have look it found looking at the objects via the interactive API helped with this as well knowing the attribute's name vs label. So I'd likely be looking at adding a section to the documentation with the schema for each model.

**Comment by jeremystretch** [comment]
>  If it's fine to submit a PR with this closed, you can also close this and I'll submit it later on.

We cannot accept PRs for closed issues, but you can ask that it be re-opened prior to beginning work if you find the time for it.

> So I'd likely be looking at adding a section to the documentation with the schema for each model.

We won't add anything to the documentation which duplicates information available by viewing the source code, as it would be infeasible to maintain long-term.
