### ISSUE TITLE
Set Default Filter for Users on Virtual Machine creation

### ISSUE THREAD

**Issue by tkn2023** [netbox-community/netbox#15483]
### NetBox version

v.3.7.4

### Feature type

New functionality

### Proposed functionality

It would be great to set a saved filter query as default for a selection field in virtual machine creation.

### Use case

I have a lot of "Platforms" and for my users I only want them to see and select a selection of "Platforms".
I have created a custom field as boolean and set the "Platforms" that should be visible to true. This saved filter query I would like to use as default on virtual machine creation for every user, so when they want to select platforms they will be presented with the once that have the custom field value "True". 
I am fine that if they select the Query themselfes that they can see every platform available but to make it much faster in the creation and user friendly I would like to set it to default for every user.

**Comment by jeremystretch** [comment]
Thank you for your interest in extending NetBox. Unfortunately, the information you have provided does not constitute an actionable feature request. Per our [contributing guide](https://github.com/netbox-community/netbox/blob/develop/CONTRIBUTING.md), a feature request must include a thorough description of the proposed functionality, including any database changes, new views or API endpoints, and so on. It must also include a detailed use case justifying its implementation. If you would like to elaborate on your proposal, please modify your post above. If sufficient detail is not added, this issue will be closed.

**Comment by tkn2023** [comment]
Opened an idea in discussion and will create a new feature request after that.
