### ISSUE TITLE
Filtering for Custom Field

### ISSUE THREAD

**Issue by Creepios** [netbox-community/netbox#15507]
### NetBox version

v3.7.4

### Feature type

Change to existing functionality

### Proposed functionality

Add filtering for custom fields. This doesnt work currently. Was already mentioned in Discussion #7907 
Especially string fields should be possible to be filtered.

### Use case

My own example is that I have some custom field with an seperate string id for a device type which I would like to filter for via API **with exact matching**.

**Comment by jeremystretch** [comment]
Thank you for your interest in extending NetBox. Unfortunately, the information you have provided does not constitute an actionable feature request. Per our [contributing guide](https://github.com/netbox-community/netbox/blob/develop/CONTRIBUTING.md), a feature request must include a thorough description of the proposed functionality, including any database changes, new views or API endpoints, and so on. It must also include a detailed use case justifying its implementation. If you would like to elaborate on your proposal, please modify your post above. If sufficient detail is not added, this issue will be closed.

**Comment by jeremystretch** [comment]
This issue is being closed as no further information has been provided. If you would like to revisit this topic, please first modify your original post to include all the requested detail, and then ask that the issue be reopened.
