### ISSUE TITLE
Additional Custom-Field Type for passwords

### ISSUE THREAD

**Issue by di5s1** [netbox-community/netbox#15519]
### NetBox version

v3.7.3

### Feature type

Data model extension

### Proposed functionality

I use some custom fields to store device information, which cannot be stored in all other fields so far. For authentication I added custom-fields for user / password for my devices. Unfortunately the password can only be stored as "text" - which would be shown in plaintext as soon as the device is selected. 
It would be great if there will be another custom-field-type for passwords (text which would be hidden at first in the device view)

### Use case

confidential information (plaintext passwords) would not be shown during live share sessions and so on.

### Database changes

I am not sure how the model looks like regarding custom fields. 
Maybe all these types are hard coded in the source and there is only an addition in the UI necessary...

**Comment by jeremystretch** [comment]
Thank you for submitting this issue, however it appears that this topic has already been raised. Please see issue #13177 for further discussion.
