### ISSUE TITLE
Virtual Device Contexts View generates a Server Error

### ISSUE THREAD

**Issue by CooperCOK** [netbox-community/netbox#15516]
### Deployment Type

Self-hosted

### NetBox Version

v3.7.4

### Python Version

3.11

### Steps to Reproduce

1. Click on Devices -> Virtual Device Contexts

### Expected Behavior

See a list of Virtual Device Contexts

### Observed Behavior

![image](https://github.com/netbox-community/netbox/assets/7281717/acf104f1-4c97-49bf-8308-217edc1aeb23)

**Comment by CooperCOK** [comment]
API is working fine. it returns a list of Virtual Device Contexts

**Comment by jeremystretch** [comment]
Thank you for opening a bug report. Unfortunately, the information you have provided is not sufficient for someone else to attempt to reproduce the reported behavior. Remember, each bug report must include detailed steps that someone else can follow on a clean, empty NetBox installation to reproduce the exact problem you're experiencing. These instructions should include the creation of any involved objects, any configuration changes, and complete accounting of the actions being taken. Also be sure that your report does not reference data on the public NetBox demo, as that is subject to change at any time by an outside party and cannot be relied upon for bug reports.
