### ISSUE TITLE
Interface - Tagged VLAN - Multiselect (Selection of 100 consecutive VLANS)

### ISSUE THREAD

**Issue by LHBL2003** [netbox-community/netbox#15530]
### NetBox version

v3.7.4

### Feature type

Change to existing functionality

### Proposed functionality

There is an interface for one device. Several tagged VLANs can be assigned to each interface. However, you must click on each VLAN individually. (Example path: https://netbox/dcim/interfaces/xxxx/edit/?return_url=/dcim/devices/xxx/interfaces/)

**Function extension proposal:**

There is an "open selector" Function in the "IPAM --> Edit prefix" area, perhaps you can use this function here. (Only with multiselector function.)
- The X button is used to delete the entire content.
- The "open Selector" button is used for multiple selection and adds further VLANs to the "Tagged VLANs" field.

![image](https://github.com/netbox-community/netbox/assets/46369917/2ec03f4c-a61c-4ac6-864b-e8babe4fe615)

- I think a very good solution that can be useful in many areas is to have checkboxes. (See picture below) Either you tick what you need.
- Or if you filter well, then you can select everything via "Check All" and add it to the existing selection.

 (This will certainly work even better than with the current DropDown field. Because every time the DropDown list gets bigger, the selection area also jumps a little).

![image](https://github.com/netbox-community/netbox/assets/46369917/9a388f3e-4c96-45ad-8241-9af9926d188a)

**For example:**
There is an open selector in the "Editing prefix" area.

### Use case
Much faster documentation of large VLAN numbers.

### The reason why, after much deliberation, I would like to have this function after all:

In the previous post, the behaviour when selecting VLANs in the device interface configuration was improved. (Because every time the drop-down list gets bigger, the selection area also jumps a little.). https://github.com/netbox-community/netbox/issues/9307

Unfortunately, it is still very tedious to click on 100 VLANs. We have more and more locations where we set up a lot of consecutive VLAN IDs. It's super easy in a switch and super time-consuming in Netbox.

**For the feeling**

----------------------------------------------------------------------
**HP Switch:**

```
config t
interface 10 tagged vlan 2000-2100
save
```
Finish

----------------------------------------------------------------------
**Netbox Tagged VLANs Dropdown List:**

2000 ... Click
2001 ... Click
2002 ... Click
2003 ... Click
A long moment later.
2100 ... Click

----------------------------------------------------------------------

The result is that you no longer document correctly in Netbox. In the meantime, you only click on the first and last VLAN in the series in Netbox, e.g. 2000 and 2100. The VLANs 2001 to 2099 are not assigned to the interface. However, they are all configured in the switch. It is therefore important to realise that only partial documentation is carried out here.

It would therefore be very, very, very nice if you could somehow click on all consecutive VLANs at the same time.

### Database changes

I would say no, as the operation of the front end is customised.

### External dependencies

Unknown

**Comment by jeremystretch** [comment]
Thank you for your interest in extending NetBox. Unfortunately, the information you have provided does not constitute an actionable feature request. Per our [contributing guide](https://github.com/netbox-community/netbox/blob/develop/CONTRIBUTING.md), a feature request must include a thorough description of the proposed functionality, including any database changes, new views or API endpoints, and so on. It must also include a detailed use case justifying its implementation. If you would like to elaborate on your proposal, please modify your post above. If sufficient detail is not added, this issue will be closed.

**Comment by LHBL2003** [comment]
Sorry I hope that fits better?

**Comment by LHBL2003** [comment]
Especially in combination with these topics, it should be a strong further development for netbox on the topic of many VLANS.

Column VLAN Tagged VLANs as summary. 
https://github.com/netbox-community/netbox/issues/14285

Interface VLAN group (Memory last filter)
https://github.com/netbox-community/netbox/issues/15273

**Comment by jdavidson2021** [comment]
VLAN assignments in NetBox are still our biggest complaint with the tool.  Making it easier to assign VLANs to an interface in the UI would be helpful, but our preference would be to assign the list of vlans to an interface during the interface csv import process.  Similar to the this open issue request: #14171

**Comment by jeremystretch** [comment]
@jdavidson2021 would you like to volunteer to implement this FR?

**Comment by jeremystretch** [comment]
Closing this out as there have been no volunteers.
