### ISSUE TITLE
autotype_decorator fails on annotated fields

### ISSUE THREAD

**Issue by arthanson** [netbox-community/netbox#15532]
### Deployment Type

Self-hosted

### NetBox Version

v4.0

### Python Version

3.8

### Steps to Reproduce

1. Create an annotated field for a model
2. Add it to the filterset for the model
3. Use the autotype_decorator for the filterset

Run into by peteeckel when migrating the DNS plugin to NB 4

**For example:**

Definition of the annotation:
```
    def get_queryset(self):
        return (
            super()
            .get_queryset()
            .annotate(
                active=ExpressionWrapper(
                    Q(status__in=Zone.ACTIVE_STATUS_LIST), output_field=BooleanField()
                )
            )
        )
```
Definition in the filterset:
```
    active = django_filters.BooleanFilter(
        label="Zone is active",
    )
```

### Expected Behavior

autotype_decorator should not throw an error

### Observed Behavior

autotype_decorator throws a FieldDoesNotExist error.

**Comment by peteeckel** [comment]
I'm not sure a fix is necessary after all, at least not for the annotation I added.

After removing the decorator from `fields` and just leaving a `BooleanFilter` for the annotated field in place, the `@autotype_decorator` created a functional filter without any further measures:

```
$ curl -s -H "Authorization: Token xxxxxxxxxxxxxxxxxxxxx" -H "Content-Type: application/json" -H "Accept: application/json"  https://netbox.example.com/graphql/ --data '{"query": "query {netbox_dns_zone_list(filters: {active: false}) {view {name}, name, status, active}}" }' | json_pp
{
   "data" : {
      "netbox_dns_zone_list" : [
         {
            "active" : false,
            "name" : "zone13.example.com",
            "status" : "reserved",
            "view" : null
         }
      ]
   }
}
```

So after removing the annotation from `fields` all seems to be OK.

**Comment by jeremystretch** [comment]
@arthanson can you confirm the above? And if not, could you please assign a severity to the bug?
