### ISSUE TITLE
Add Custom Field Choice Sets for Device Type

### ISSUE THREAD

**Issue by Sergio-MT** [netbox-community/netbox#15545]
### NetBox version

v.3.7.4

### Feature type

New functionality

### Proposed functionality

Add Custom Field Choice Sets for once Device Type. When creating new Device Type add the ability add custom field with previously created custom choice set. Now I can add Custom field for all Device Types with Multiple Selection mode and choose one cusom choice set, but I need for each Device Type add self custom choice set. This will be used to indicate installed options for device.

### Use case

Created Custom Field Choice Set named "<Manufaturer><Model> options". Created Device Type for <Manufaturer><Model> and add choice set with availability options which may be opened on this device. Create Device and choose installed options.
Also add any custom choice set for each Device Type

**Comment by abhi1693** [comment]
Thank you for your interest in extending NetBox. Unfortunately, the information you have provided does not constitute an actionable feature request. Per our [contributing guide](https://github.com/netbox-community/netbox/blob/develop/CONTRIBUTING.md), a feature request must include a thorough description of the proposed functionality, including any database changes, new views or API endpoints, and so on. It must also include a detailed use case justifying its implementation. If you would like to elaborate on your proposal, please modify your post above. If sufficient detail is not added, this issue will be closed.

**Comment by jeremystretch** [comment]
This issue is being closed as no further information has been provided. If you would like to revisit this topic, please first modify your original post to include all the requested detail, and then ask that the issue be reopened.

**Comment by jeremystretch** [comment]
I'm honestly not sure what is being proposed here; device types already support custom fields. I'm going to close this out as no further information has been provided in response to the request above.
