### ISSUE TITLE
Unable to Edit Component-Associations on InventoryItemTemplates

### ISSUE THREAD

**Issue by chadhpaine** [netbox-community/netbox#15541]
### Deployment Type

Self-hosted

### NetBox Version

v3.7.4

### Python Version

3.9

### Steps to Reproduce

1. Create a device-type.
2. Add an InventoryItemTemplate on the device-type created in step 1.
2a. Observe the lack of a 'Component' subsection in the Create Template view.
3. Observe that the table for the InventoryItemTemplates shows a 'Component' column.
3a. Observe that the value of the 'Component' column is empty.
5. Edit the InventoryItemTemplate created in step 2.
4a. Observe the lack of a 'Component' subsection in the Edit Template view.

### Expected Behavior

It should be possible to edit the 'Component' field of an InventoryItemTemplate from the UI.

### Observed Behavior

It doesn't appear that the 'Component' field is exposed for editing within the UI of the InventoryItemTemplate type.

**Comment by arthanson** [comment]
This actually shows as non-editable fields on NB4
![Monosnap Editing inventory item template InvTemplate1 | NetBox 2024-03-26 15-16-38](https://github.com/netbox-community/netbox/assets/99642/e29b08ba-c576-439b-bfdf-b5293b2086af)
