### ISSUE TITLE
Virtual Chassis on multiple Rack

### ISSUE THREAD

**Issue by sgelineau17** [netbox-community/netbox#15546]
### NetBox version

v3.7.4

### Feature type

Change to existing functionality

### Proposed functionality

Hello,

We have deployed 8 switchs of Alcatel-Lucent 6360-P24X (on 4 racks on two rooms of our Data Center) for connect the OOB interface of each equipments. We have one virtual chassis per room for 4 switches. (2 virtual chassis of total)

We have create the 8 switches of Netbox and I have try to create a 2 virtual chassis, one per room. When I try to associate the second switch of a virtual chassis it's not working, I get an error message, because I can't define a position of my virtual chassis "DeviceVCMembershipForm" because it is distributed in several racks.

![2024-03-27 12_13_43-Server Error](https://github.com/netbox-community/netbox/assets/61157268/4f594222-03ec-4f68-97a3-ce214ae6fb2d)

Thanks,

### Use case

I would like it to be possible to create a virtual chassis with switches that are in different racks of the same location.

**Comment by DanSheps** [comment]
Position is a required field for a virtual chassis unfortunately.  Position of the VC does not indicate position in a rack.  It is the "position" in the virtual stack (chassis 1 or chassis 2 or chassis 5).

I switched this to a bug.  If you can please provide reproduction steps we can at least clean up that error.

**Comment by jeremystretch** [comment]
This issue is being closed as no further information has been provided. If you would like to revisit this topic, please first modify your original post to include all the requested detail, and then ask that the issue be reopened.
