### ISSUE TITLE
API key not related to Netbox user, but for system account to automate stuff

### ISSUE THREAD

**Issue by RemcoVroman** [netbox-community/netbox#15561]
### NetBox version

v3.7.2

### Feature type

New functionality

### Proposed functionality

Let the admin users create a api key for automation purposes and is not related to a netbox user. With the API key there should be a description possebility to register what the key is for. Also the rights and experation date should be possible.

### Use case

We will use this for automation purposes. The api kesy are now related to a person who might leave the organisation and then the key becomes invallid. However the automation process will need to continue.

**Comment by jeremystretch** [comment]
This is not feasible: All permission controls and change logging in NetBox is built on the user & group models. You simply need to create a "system" account to which API tokens can be assigned.
