### ISSUE TITLE
Nullable fields not nullable in the OpenAPI spec

### ISSUE THREAD

**Issue by fbs** [netbox-community/netbox#15588]
### Deployment Type

Self-hosted

### NetBox Version

v3.7.4

### Python Version

3.11

### Steps to Reproduce

Compare the API spec on dcim/devices to the actual API response

### Expected Behavior

An unknown number of fields should be marked nullable in the openapi spec

This include at least:

- `primary_ip` on `VirtualMachineWithConfigContext`
- `primary_ip` on `DeviceWithConfigContext`

I think there are more as I expect this an issue with how the spec is generated from properties

### Observed Behavior

```
$ curl -s -X 'GET' 'http://localhost:9876/api/dcim/devices/?name=NAME' -H 'accept: application/json' -H 'Authorization: token KEY' | jq '.results[0]|[.role, .primary_ip, .primary_ip4 ]'
[
  {
    "id": 15,
    "url": "http://localhost:9876/api/dcim/device-roles/15/",
    "display": "Server",
    "name": "Server",
    "slug": "server"
  },
  null, # <- primary_ip
  null  # <- primary_ip4
]
```

compared to the spec:

```
$ curl -s http://localhost:9876/api/schema/ | yq '.components.schemas.VirtualMachineWithConfigContext.properties.primary_ip'
allOf:
  - $ref: '#/components/schemas/NestedIPAddress'
readOnly: true
```

Note how primary_ipv4 is marked nullable, as expected
```
$ curl -s http://localhost:9876/api/schema/ | yq '.components.schemas.VirtualMachineWithConfigContext.properties.primary_ip4'
allOf:
  - $ref: '#/components/schemas/NestedIPAddress'
nullable: true
```

The above is just one instance, it happens to other schemas as well. E.g. `DeviceWithConfigContext` has the same problem

**Comment by fbs** [comment]
My guess would be that this comes from the primary_ip being a [property](https://github.com/netbox-community/netbox/blob/699dd7259761da0d70f1a1bf94b088d44090f56d/netbox/dcim/models/devices.py#L1439), making it read only but not nullable. But I'm not sure whether thats in the right direction.

I'd be open to fixing this but will need some pointers

**Comment by jeremystretch** [comment]
> These fields should be nullable

Please spend some more time on your report. Without an explicit list of fields which you believe to be erroneously defined, this is not actionable.

**Comment by fbs** [comment]
> > These fields should be nullable
> 
> Please spend some more time on your report. Without an explicit list of fields which you believe to be erroneously defined, this is not actionable.

Sorry, I've updated the issue description  to list the fields I identified.

I think we can identify all fields impacted when we understand what is causing the spec for these to be wrong
