### ISSUE TITLE
Document the value behind "Default" for the Custom Link "Button Class"

### ISSUE THREAD

**Issue by maddin8** [netbox-community/netbox#15597]
### Change Type

Addition

### Area

Customization

### Proposed Changes

I would like to propose that aside from the possible non-default values for "Button Class"/"button_class" of Custom Links, documentation is updated to include the information that the value displayed as "Default" in the Netbox UI is actually called "outline-dark". "Default" is as well included in CSV exports of Custom Links from already populated instances, which makes it harder for non-experienced users to determine what value to provide when mass-importing Custom Links with a button_class of "Default"(/"outline-dark").

I originally raised this in #15596 which hopefully provides enough reason why I think this should be included in the documentation.

**Comment by maddin8** [comment]
Updated formatting of the table in the second commit.

**Comment by jeremystretch** [comment]
It would not be appropriate to duplicate all these entries in the written documentation. Instead, the field definition under the CSV import form should include a help button which displays the available choices, as exists for similar fields. (`button_class` should be defined on the form as a CSVChoiceField.)

@maddin8 do you want to try this?

**Comment by jeremystretch** [comment]
Reclassified this as a bug, as the import form field is not of the correct type.
