### ISSUE TITLE
CustomScript LDAP sync for contacts

### ISSUE THREAD

**Issue by sgabenov** [netbox-community/netbox#15591]
### Change Type

Addition

### Area

Integrations/API

### Proposed Changes

There was a reply for issue "sync contacts with LDAP" that to do the task, we can create custom script to sync contacts with ldap:
https://github.com/netbox-community/netbox/issues/8614#issuecomment-1038892062

If it is possible, could you please provide an example of such script somewhere (probably in documentation), so we can reuse such functionality.
It seems that task to sync users from ldap may be very helpful @PieterL75

**Comment by jeremystretch** [comment]
Exhibiting specific functionality is outside the scope of the NetBox documentation. You might consider adding an example script to the [customizations collection](https://github.com/netbox-community/customizations).
