### ISSUE TITLE
Add 5G as an option to the Cellular device interface section

### ISSUE THREAD

**Issue by KPTheProf** [netbox-community/netbox#15603]
### NetBox version

v3.7.4

### Feature type

Change to existing functionality

### Proposed functionality

With reference to [Interface Type Additions for LTE Standards #2866](https://github.com/netbox-community/netbox/issues/2866) could we add 5G to list of cellular interface types to differentiate those devices that support 5G as apposed to 4G/LTE.

### Use case

We are rolling out [Cradlepoint W1850](https://cradlepoint.com/product/endpoints/w1850-series/) 5G devices and would like to differentiate 5G devices from older LTE models.

**Comment by Julio-Oliveira-Encora** [comment]
Could you please assign this task to me?

**Comment by jeremystretch** [comment]
This needs more discussion before it can be accepted. Is there consensus that adding a single "5G" type is sufficient? Concern was raised in #2866 that adding a single generic "LTE" type would be limiting. I'm not sure that's come up again more recently, but we should give this proposal the same consideration.

**Comment by RasmusThing** [comment]
> This needs more discussion before it can be accepted. Is there consensus that adding a single "5G" type is sufficient? Concern was raised in #2866 that adding a single generic "LTE" type would be limiting. I'm not sure that's come up again more recently, but we should give this proposal the same consideration.

I agree - and what about 4G?
4G and LTE networks are not the same. LTE came out before 4G to offer a slightly better speed and performance than its predecessor, 3G. Later, LTE-A emerged and delivered an even higher performance, which is almost as good as the real 4G.

**Comment by KPTheProf** [comment]
> I agree - and what about 4G? 4G and LTE networks are not the same. LTE came out before 4G to offer a slightly better speed and performance than its predecessor, 3G. Later, LTE-A emerged and delivered an even higher performance, which is almost as good as the real 4G.
I'm quite happy accept adding both 4G and 5G, we were initially using LTE as there was no 4G device type.
