### ISSUE TITLE
Display of space utilization in rack table is broken

### ISSUE THREAD

**Issue by julianstolp** [netbox-community/netbox#15619]
### Deployment Type

Self-hosted

### NetBox Version

v4.0-beta1

### Python Version

3.10

### Steps to Reproduce

1. Open the rack table view /dcim/racks
2. See `SPACE` column

### Expected Behavior

Open the prefix table view /ipam/prefixes/. The values are displayed so one can read these.
![image](https://github.com/netbox-community/netbox/assets/41152397/87267db6-ccf4-4ee0-b55e-000a0ecfadb3)

### Observed Behavior

Space utilization values are not readable
![image](https://github.com/netbox-community/netbox/assets/41152397/82da0775-e55a-4ae5-b1b6-5e274637da05)

**Comment by DanSheps** [comment]
This appears to be a dark ui issue, does this issue persist on the light UI as well?

**Comment by julianstolp** [comment]
It also persists in the light UI as well. I guess it works for the prefix table because the name `utilization` is longer than `space` so the  progressbar gets more space.

**Comment by jeremystretch** [comment]
It seems the issue here is simply that the column can be too narrow? Setting a minimum width on the bar graph should be sufficient to fix this.
