### ISSUE TITLE
Missing Login/Logout buttons

### ISSUE THREAD

**Issue by renatoalmeidaoliveira** [netbox-community/netbox#15613]
### Deployment Type

NetBox Cloud

### NetBox Version

v4.0-beta1

### Python Version

3.8

### Steps to Reproduce

1. Open beta-demo.netbox.dev
2. Click on the menu drop down
3. Doesn't find the Login button

### Expected Behavior

The Login button is visible

### Observed Behavior

No Login Button.

**Comment by DanSheps** [comment]
Thank you for opening a bug report. I was unable to reproduce the reported behavior on NetBox v4.0-beta1. Remember to provide detailed steps that someone else can follow using a clean installation of NetBox to reproduce the issue. Remember to include the steps taken to create any initial objects or other data.

**Comment by abhi1693** [comment]
![Screenshot_20240404-102939.png](https://github.com/netbox-community/netbox/assets/5083532/4b6eea5e-6c18-476a-8eed-8fe1954fb201)


It's actually missing on the site.

**Comment by renatoalmeidaoliveira** [comment]
@DanSheps 
Digging a bit it seens that it only affects mobile, or smaller screans
When the screens is smaller than 992px it activates the css class .d-none and hides the login/logout buttons

**Comment by julianstolp** [comment]
> @DanSheps Digging a bit it seens that it only affects mobile, or smaller screans When the screens is smaller than 992px it activates the css class .d-none and hides the login/logout buttons

Also when logged in on a mobile device the complete user menu is missing.
