### ISSUE TITLE
Add examples for ordering results to REST API documentation

### ISSUE THREAD

**Issue by jeremystretch** [netbox-community/netbox#15622]
### Change Type

Addition

### Area

Integrations/API

### Proposed Changes

Add a brief section on ordering to the REST API documentation, including examples. For instance,

```
GET /api/dcim/sites/?ordering=-name
```

will return all sites sorted by name in reverse alphabetical order.

**Comment by muTeREdO** [comment]
This is technically covered in the [docs/reference/filtering.md](https://github.com/netbox-community/netbox/blob/develop/docs/reference/filtering.md) documentation.  

I do have a slight modification based on your feedback that shows a brief example building off the filtering example under [Endpoint Hierarchy](https://github.com/netbox-community/netbox/blob/develop/docs/integrations/rest-api.md#endpoint-hierarchy).  I'd be happy to put a PR in for it.

**Comment by jeremystretch** [comment]
> This is technically covered in the [docs/reference/filtering.md](https://github.com/netbox-community/netbox/blob/develop/docs/reference/filtering.md) documentation.

Ha, I _thought_ we had added it at some point. Maybe we should just add a note & link on the main API documentation to it. @muTeREdO happy to assign this to you if you'd like to own it.

**Comment by muTeREdO** [comment]
@jeremystretch, sure assign it over and I'll take care of it!

**Comment by muTeREdO** [comment]
[PR submitted.](https://github.com/netbox-community/netbox/pull/15627)
