### ISSUE TITLE
User preference table is aligned right side

### ISSUE THREAD

**Issue by julianstolp** [netbox-community/netbox#15620]
### Deployment Type

Self-hosted

### NetBox Version

v4.0-beta1

### Python Version

3.10

### Steps to Reproduce

Also present in lower NetBox versions.

1. Log in to NetBox
2. Go to /user/preferences/

### Expected Behavior

The user preferences should be styled like any other edit form in NetBox for consistency reasons

![image](https://github.com/netbox-community/netbox/assets/41152397/fafec006-accc-405d-96b4-50c0d9ccbd37)

### Observed Behavior

1. See the differences between edit form styling and user preferences.
![image](https://github.com/netbox-community/netbox/assets/41152397/841d258b-465c-4a2e-b6ba-d6eab062fc7a)
2. You can even click the very left side to activate the fields which is very annoying.
![image](https://github.com/netbox-community/netbox/assets/41152397/56464b18-a543-4063-a238-4824dfef605a)

From observing with the developer console you can see the differences

1. any object edit eg. /ipam/prefixes/xxx/edit/
![image](https://github.com/netbox-community/netbox/assets/41152397/484b4c09-2ef7-4839-95d1-fdfe24c4b68d)
2. /user/preferences/
![image](https://github.com/netbox-community/netbox/assets/41152397/877460ea-d615-4f0b-8660-210d8f59dfc8)

**Comment by julianstolp** [comment]
Also preset on any model that have filters. I don't want to open the dropdown menus if I'm clearly not clicking anywhere near the name or the selector.

**Comment by jeremystretch** [comment]
> Also preset on any model that have filters. I don't want to open the dropdown menus if I'm clearly not clicking anywhere near the name or the selector.

This would need a separate bug report.
