### ISSUE TITLE
Links within embedded tables do not load when HTMX is enabled

### ISSUE THREAD

**Issue by julianstolp** [netbox-community/netbox#15637]
### Deployment Type

Self-hosted

### NetBox Version

v4.0-beta1

### Python Version

3.10

### Steps to Reproduce

1. Go to user preferences and enable HTMX Navigation
2. Go to a site and attach an image
3. Click on the parent of that image, which should be the site itself
4. Opens the card `Site` and `Custom Fields` within `Images`

### Expected Behavior

It opens the site in the same tab like every other link.

### Observed Behavior

![error1](https://github.com/netbox-community/netbox/assets/41152397/3c85c7bb-d8c2-4324-a394-81e101828ad5)

**Comment by julianstolp** [comment]
And in addition, the edit button does not work. The dropdown menu is also displayed in the card body instead of beyond the edge of the card.

![image](https://github.com/netbox-community/netbox/assets/41152397/039d5320-7cf9-40a8-9fb2-2ae712a32d71)

**Comment by jeremystretch** [comment]
> The dropdown menu is also displayed in the card body instead of beyond the edge of the card.

Tagging #15536 as the same fix is likely needed here.

**Comment by jeremystretch** [comment]
Changed the issue title as this seems to impact all embedded tables, not just image attachments.
