### ISSUE TITLE
Saved filters are displayed on any models not only the assigned models

### ISSUE THREAD

**Issue by julianstolp** [netbox-community/netbox#15638]
### Deployment Type

Self-hosted

### NetBox Version

v4.0-beta1

### Python Version

3.10

### Steps to Reproduce

1. Go to customization -> saved filters /extras/saved-filters/
2. create a filter named Test and assign it to object type `DCIM > Site`
```
{
    "q": [
        ""
    ],
    "status": [
        "planned"
    ]
}
```
3. Go to /dcim/devices/ and click on tab `Filters` select filter test hit search button
4. Filter works as intended or returns any object, depending on whether the models share all elements of the filter

### Expected Behavior

Filter not visible if the object type does not match the assigned model.

### Observed Behavior

All filters are visible regardless of whether they match the object type or not.

**Comment by arthanson** [comment]
@julianstolp this is working fine when I try it (v4.0-beta1) can you please check if there are other steps needed or special conditions.

**Comment by julianstolp** [comment]
I created the filter on your beta demo instance also happening there.

- https://beta-demo.netbox.dev/extras/saved-filters/1/
- https://beta-demo.netbox.dev/tenancy/tenants/?q=&filter_id=1&cf_cust_id=

![grafik](https://github.com/netbox-community/netbox/assets/41152397/e062a45d-8524-4750-92cb-20d66bdc038a)
![grafik](https://github.com/netbox-community/netbox/assets/41152397/cda9a2c7-4ea5-4cf8-a357-06d56d5294a3)
