### ISSUE TITLE
Image attachments show up under wrong related objects

### ISSUE THREAD

**Issue by julianstolp** [netbox-community/netbox#15636]
### Deployment Type

Self-hosted

### NetBox Version

v4.0-beta1

### Python Version

3.10

### Steps to Reproduce

1. Create site 1 /dcim/site/1
2. create site 2 /dcim/site/2
3. Create rack 1 /dcim/rack/1 and add it to site2
4. Add image to rack 1
5. Go to site 1 look at `Images`
6. Image from rack 1 is visible at site 1

Also happens to every other object type if `Images` is present

### Expected Behavior

Images are displayed only if they are related in any way but not the primary key.

### Observed Behavior

![error](https://github.com/netbox-community/netbox/assets/41152397/319190dc-383d-43bc-ae2c-fcacdc59fd43)

**Comment by jeffgdotorg** [comment]
Thanks for the bug report. Confirmed I can reproduce on a pristine v4.0b1 install.

**Comment by jeremystretch** [comment]
> Image from rack 1 is visible at site 1

Only images attached to site 1 will be listed when viewing the site. You need to view the specific rack to see images attached to it.
