### ISSUE TITLE
Switch between dark/light mode doesn't take effect until user logs out and back in

### ISSUE THREAD

**Issue by jhammond-git** [netbox-community/netbox#15630]
### Deployment Type

Self-hosted

### NetBox Version

v4.0-beta1

### Python Version

3.10

### Steps to Reproduce

1. Log in as a user.
2. Click on the User menu in the top right
3. Click Preferences
4. Change color mode, and click Save at the bottom

### Expected Behavior

Color mode changes as soon as Save is clicked and the page refreshes to the new mode.

### Observed Behavior

Color mode doesn't change until user logs out of Netbox and back in.

**Comment by jhammond-git** [comment]
I went back to my production (3.7.4) and discovered it does the same in the Preferences menu, but also found the menu item for light/dark mode switch which takes effect immediately.  That led me to the button which I noticed in beta that has the same function, but I didn't realize it was a button before.

Having said all that, I don't see why the preference can't change mode on Save, but I can also see why that wouldn't be a reasonable use of development time.

**Comment by jeffgdotorg** [comment]
The first time I tried to reproduce this issue (going from dark to light), it behaved as expected. Each subsequent time I was able to reproduce it consistently regardless of which direction the color mode was going.

**Comment by DanSheps** [comment]
> Honestly it feels like overkill to track light/dark mode as a preference anyway. I can easily see this being device- or time-dependent, and the live toggle makes much more sense IMO. Maybe we should just ditch the stored preference altogether.

The one arguement I could see is that if you move to new devices frequently, however I think that is a corner case and not the norm so we might not even care about it.
