### ISSUE TITLE
API not consistent for VM -> Interface -> IP

### ISSUE THREAD

**Issue by Daniel-Dietz** [netbox-community/netbox#15632]
### NetBox version

v3.7.4

### Feature type

Change to existing functionality

### Proposed functionality

The behavior of the API is not consistent  

The Return of the VM contains the ID needed to create the Interfaces for the VM, 
the Return of the Interface does contain an ID but the IPAM IP-Address Body does not accept it.

```
{
  "address": "string",
  "vrf": 0,
  "tenant": 0,
  "status": "active",
  "role": "loopback",
  "assigned_object_type": "string",
  "assigned_object_id": 9223372036854776000,
  "nat_inside": 0,
  "dns_name": "df",
  "description": "string",
  "comments": "string",
  "tags": [
    {
      "name": "string",
      "slug": "dfsas",
      "color": "5a7bfe"
    }
  ],
  "custom_fields": {
    "additionalProp1": "string",
    "additionalProp2": "string",
    "additionalProp3": "string"
  }
}
```

Proposed change add the field vminterface to the API where the ID of an VM Interface is accepted, this would put it inline with the Web UI where the assignment is triggered via https://netbox/ipam/ip-addresses/add/?vminterface=764

### Use case

Ease of use for API development and consistency across multiple API Functions

**Comment by jeremystretch** [comment]
There is no `vminterface` relation for IP addresses. IP addresses can be assigned to several types of objects (device interfaces, VM interfaces, or FHRP groups) using a generic foreign key relation. This is done by specifying both the related object type (`assigned_object_type`) and numeric ID (`assigned_object_id`) as documented in the schema. This is standard convention for all generic foreign key relations in NetBox.

**Comment by Daniel-Dietz** [comment]
@jeremystretch  Would it be possibel to include the object_id in the Return of POST /virtualization/virtualization_interfaces_create
