### ISSUE TITLE
Links in dashboard change log open in change log widget

### ISSUE THREAD

**Issue by devon-mar** [netbox-community/netbox#15648]
### Deployment Type

Self-hosted

### NetBox Version

v4.0-beta1

### Python Version

3.8

### Steps to Reproduce

Reproduced on beta-demo.netbox.dev

1. Click on a link in the change log such as `GigabitEthernet1/0/5`
![image](https://github.com/netbox-community/netbox/assets/24482041/96bbb91c-d491-40e2-87bc-c4ded3933e8a)

### Expected Behavior

The browser is navigated to the target of the link.

### Observed Behavior

The URL in the address bar changes to the clicked link, but the page is displayed in the change log box.

![image](https://github.com/netbox-community/netbox/assets/24482041/b9a0fe33-b5e8-4fd3-9ce0-52bd70960282)

**Comment by jeremystretch** [comment]
This has been resolved under #15637. Please pull down the `feature` branch to get the latest v4.0 code, which includes the fix (or wait for the next beta release).
