### ISSUE TITLE
Add L2VPN identifier field to the search index for L2VPN objects

### ISSUE THREAD

**Issue by rwxd** [netbox-community/netbox#15640]
### NetBox version

v3.7.4

### Feature type

Change to existing functionality

### Proposed functionality

Add the `identifier` field of `L2VPN` to the corresponding SearchIndex, so that it's possible to enter an L2VPN identifier into the global search and turn up the corresponding L2VPN object in the results.

### Use case

We use the `identifier` field of `L2VPN` to note a vxlan id.
It would be nice to also see the l2vpn, when we search for the vxlan id.

![image](https://github.com/netbox-community/netbox/assets/40308458/1abf8a74-3a5b-4191-ab79-9a765fcf1a5b)

#13927 exists, but the issue was also about making the identifier unique & required.

**Comment by jeffgdotorg** [comment]
Thanks for your interest in helping improve NetBox.

I've moved this issue into `needs owner` status. If you are interested in working it through to a PR, let us know and we'll assign the issue to you. Otherwise, any developer with the skills and capacity can request to work on it.

**Comment by rwxd** [comment]
Thanks. I'm interested in doing the PR

**Comment by jeremystretch** [comment]
Thanks @rwxd, I've assigned this to you.
