### ISSUE TITLE
Add the ability to configure HSTS in NetBox

### ISSUE THREAD

**Issue by sarhaynes** [netbox-community/netbox#15644]
### NetBox version

v3.7.3

### Feature type

New functionality

### Proposed functionality

Currently NetBox does not have configuration entries for HSTS.  In order to enable this security feature it is necessary to set the following Django settings (see https://docs.djangoproject.com/en/5.0/ref/middleware/#http-strict-transport-security)

The recommend change to settings.py:
```
SECURE_HSTS_SECONDS =  getattr(configuration, 'SECURE_HSTS_SECONDS', 0) 
SECURE_HSTS_INCLUDE_SUBDOMAINS = getattr(configuration, 'SECURE_HSTS_INCLUDE_SUBDOMAINS', False)
SECURE_HSTS_PRELOAD = getattr(configuration, 'SECURE_HSTS_PRELOAD', False)
```

### Use case

Add the ability to enable HSTS in configuration.py.

### Database changes

None

### External dependencies

None

**Comment by Julio-Oliveira-Encora** [comment]
Please, could you assign it to me?
