### ISSUE TITLE
Filter IP Address by assigned_object__empty not working

### ISSUE THREAD

**Issue by aaronhuff** [netbox-community/netbox#15643]
### Deployment Type

Self-hosted

### NetBox Version

v3.7.4

### Python Version

3.8

### Steps to Reproduce

1. GET /api/ipam/ip-addresses/?assigned_object__empty=False
or
2. IPAddress.objects.filter(assigned_object__empty=False)

### Expected Behavior

Returns ip addresses that assigned object is not empty/null.

### Observed Behavior

Returns all ip addresses. Same result with = True.

**Comment by arthanson** [comment]
@aaronhuff  I think you want ?assigned=false ?  Does that work for you?

**Comment by aaronhuff** [comment]
> @aaronhuff I think you want ?assigned=false ? Does that work for you?

That's what I was looking for, Thanks! Is that anywhere in the docs, that that is how I was supposed to filter it?
