### ISSUE TITLE
Unable to select additional query fields in advanced object selector

### ISSUE THREAD

**Issue by v0tti** [netbox-community/netbox#15641]
### Deployment Type

NetBox Cloud

### NetBox Version

v4.0-beta1

### Python Version

3.8

### Steps to Reproduce

1. Edit an IP address e.g. https://beta-demo.netbox.dev/ipam/ip-addresses/31/edit/
2. Open the advanced object selector to assign the IP address to an interface
3. Try to enable additional query fields by clicking on the items to the left

### Expected Behavior

I expect the selected query fields to appear or disappear by clicking on the elements of the list.

### Observed Behavior

Nothing changes. No query fields get added or removed.

**Comment by jeremystretch** [comment]
The issue appears to be that the field selectors along the lefthand side of the modal are not properly initialized after the modal's content is loaded via HTMX.
