### ISSUE TITLE
Confirm which Inventory Item(s) will be deleted when deleting associated Component(s)

### ISSUE THREAD

**Issue by chadhpaine** [netbox-community/netbox#15665]
### NetBox version

v3.7.4

### Feature type

New functionality

### Proposed functionality

When deleting an Interface, Power Port, or other Device Component tied to an Inventory Item by a Component Association (#7846), the Inventory Item is also deleted (#15586). Netbox does not currently warn of the pending deletion of those Inventory Items from the bulk-deletion menu, but it would be great if it did.

### Use case

Inventory Items have the ability to carry serial-numbers ([doc](https://docs.netbox.dev/en/stable/models/dcim/inventoryitem/)) which, being unique to the inventory, may not be duplicated or annotated in any other location within Netbox; and which, thanks to the ability to move inventory-items between devices (#3818), could be tracked as first-class metadata within Netbox: like child-devices (but unlike modules (#15289)), inventory-items don't have to be deleted and recreated to reassociate with other objects, implying that the serial-number field can be treated as persistent, and that Netbox could be used for the long-term tracking of retained inventory-serials.

In that deletion of inventory-items associated to other components, when those associated components are deleted, is an intended operation (#15586), this issue requests implementation of a warning on deletion of those components that the inventory-items to which they relate will also be deleted, from all contexts from which they could be deleted. In lieu of support enabling the aggregation of inventory-item relationships as columns across all component-types (#14653), this change would at least provide a 'one-last-chance' to the instance-maintainer to identify the associated inventory, and to take the actions appropriate to retain it if relevant, before continuing with deletion of the targeted components. 

While it has been shown \[[1](https://github.com/netbox-community/netbox/issues/15665#issuecomment-2066586599)] that the atomic-deletion mechanism for components other than inventory-items do in-fact show the inventory-items that will be deleted when the component is deleted, the bulk-deletion menu does not provide such insight at this time \[[2](https://github.com/netbox-community/netbox/issues/15665#issuecomment-2066745390)].

### Database changes

n/a

### External dependencies

n/a

**Comment by jeremystretch** [comment]
> When deleting an Interface, Power Port, or other Device Component tied to an Inventory Item by a Component Association (https://github.com/netbox-community/netbox/issues/7846), the Inventory Item is also deleted (https://github.com/netbox-community/netbox/issues/15586). Netbox does not currently warn of the pending deletion of those Inventory Items, but it would be great if it did.

NetBox v3.7.5 shows the following warning when deleting an interface with an inventory item associated with it:

![screenshot](https://github.com/netbox-community/netbox/assets/13487278/1f2288fc-afaf-4bf0-b626-ff0f3f2d98c0)

@chadhpaine what specifically are you proposing be implemented?

**Comment by chadhpaine** [comment]
@jeremystretch I hadn't observed that screen before, but this is exactly what I was looking for. When I mentioned deleting the interface, I may have used the bulk-deletion feature (select the checkbox for the interface from the list, then click Delete Selected), which is where I noticed the lack of warning, rather than atomic-component-deletion, which does indeed pull-up the view you screen-grabbed.

Cloning your setup, note the lack of mention of MyItem1234.
![image](https://github.com/netbox-community/netbox/assets/71343685/f6c6b1be-e56d-40e4-916a-2622f3d28603)

**Comment by arthanson** [comment]
@chadhpaine can you please rework this as a general feature request to for bulk-delete to show dependent objects?  This doesn't just effect inventory-items, dependent objects are not shown in any bulk operations.  See #14488 which was brought up before but never turned into a feature request.

**Comment by chadhpaine** [comment]
@arthanson per your request, I created https://github.com/netbox-community/netbox/issues/16191; since that issue encompasses this request, feel free to close this as subordinate.

**Comment by arthanson** [comment]
closing as replaced by a feature request.
