### ISSUE TITLE
virtual disks tab on virtual machine view not showing for non-superadmins

### ISSUE THREAD

**Issue by ITJamie** [netbox-community/netbox#15668]
### Deployment Type

NetBox internal

### NetBox Version

v.3.7.5

### Python Version

3.11

### Steps to Reproduce

1: create a new permission set with all permissions enabled across all objects
2: create a new user and add that permission set
3: login as the new user.
4: create a VM

- on the VM view page. the virtual disks tab will be missing

5: increase the users permission to superuser
- on the VM view page logged in as the new user the virtual disks tab will appear

### Expected Behavior

that virtual disks tab was visible on the VM view for users with permissions

### Observed Behavior

virtual disk tab did not show.

**Comment by ITJamie** [comment]
without superuser role
![without superuser](https://github.com/netbox-community/netbox/assets/1613241/e96ae227-7a1e-479e-ae66-b73d60cc8865)

with superuser role
![with superuser](https://github.com/netbox-community/netbox/assets/1613241/37a0625c-251f-4f66-8404-042b6b8905b3)

**Comment by jeffgdotorg** [comment]
Good catch, @ITJamie. Thanks for the report. I was able to reproduce the issue on a fresh 3.7.5 install.

![image](https://github.com/netbox-community/netbox/assets/1209268/f4cfddd9-413e-4818-a9ea-ce63b388729e)

PS I think the deployment type might be incorrect, please double check and edit if appropriate.

**Comment by Julio-Oliveira-Encora** [comment]
Could you please assign it to me?
