### ISSUE TITLE
Add Ukrainian

### ISSUE THREAD

**Issue by SmalLPUUP** [netbox-community/netbox#15682]
### Language

Ukrainian

### ISO 639-1 code

UA

### Volunteer

Yes

### Comments

Good afternoon.
I am sure that your project will be popular among Ukrainian-speaking specialists.

Thank you for a good product.

**Comment by jeffgdotorg** [comment]
Thanks for your interest in helping translate NetBox. This issue is a duplicate of #14639 so I'm resolving it as such.
