### ISSUE TITLE
Migration "Applying users.0006_custom_group_model" to 4.0-beta1 fails

### ISSUE THREAD

**Issue by tobiasge** [netbox-community/netbox#15695]
### Deployment Type

Self-hosted

### NetBox Version

v4.0-beta1 (89dd4230807bf5d8f6de586d86120d8148d23eb1)

### Python Version

3.11

### Steps to Reproduce

1. Netbox setup with 3.7.5 (upgraded from 2.5)
2. Migrate to `v4.0-beta1 (89dd4230807bf5d8f6de586d86120d8148d23eb1)`

### Expected Behavior

Successful run of all migrations

### Observed Behavior

Migration `Applying users.0006_custom_group_model` fails with this error:
```
psycopg.errors.ForeignKeyViolation: update or delete on table "auth_group" violates foreign key constraint "auth_group_permissions_group_id_b120cbf9_fk_auth_group_id" on table "auth_group_permissions"
DETAIL:  Key (id)=(10) is still referenced from table "auth_group_permissions".
```

Table list pre migration: https://gist.github.com/tobiasge/382ec52aaca740b622d480c75f95acf6#file-3-7-5-table-list-txt
Full stack trace: https://gist.github.com/tobiasge/382ec52aaca740b622d480c75f95acf6#file-exception-txt
Table list after migration try: https://gist.github.com/tobiasge/382ec52aaca740b622d480c75f95acf6#file-4-0-beta-table-list-txt

**Comment by jeremystretch** [comment]
@tobiasge it looks like you have one or more legacy permissions in the `auth_group_permissions` table referencing the stock Group model. NetBox moved to a custom object-based permission model back in v2.9, and the legacy permissions are no longer used for anything. There was a [migration](https://github.com/netbox-community/netbox/blob/v2.9.0/netbox/users/migrations/0009_replicate_permissions.py) to copy the legacy permissions into the new table but I don't believe the old ones were ever deleted.

Could you try clearing out that table and re-running the v4.0 migration? (`DELETE FROM auth_group_permissions` in the `dbshell` should do it.)

**Comment by tobiasge** [comment]
```sql
DELETE FROM auth_group_permissions
DELETE 627
```
After this the `Applying users.0006_custom_group_model` was successful.

**Comment by tobiasge** [comment]
Just for completeness: I did some research and figured out that the first installation with this database was on Netbox 2.2.9
