### ISSUE TITLE
Not able to specify multiple terminations for either end of a cable when bulk importing using the CSV method

### ISSUE THREAD

**Issue by netravnen** [netbox-community/netbox#15719]
### Deployment Type

Self-hosted

### NetBox Version

v3.7.4

### Python Version

3.11

### Steps to Reproduce

1. Create a LC patch panel ([Generic/LC-24-port-fiber-patch-panel-half-depth](https://github.com/netbox-community/devicetype-library/blob/master/device-types/Generic/LC-24-port-fiber-patch-panel-half-depth.yaml))
2. Create a SC patch panel ([Generic/SC-24-port-fiber-patch-panel-half-depth](https://github.com/netbox-community/devicetype-library/blob/master/device-types/Generic/SC-24-port-fiber-patch-panel-half-depth.yaml))
3. Run the CSV importer with the following data (only the required fields mentioned here)
   ```
   side_a_device,side_a_type,side_a_name,side_b_device,side_b_type,side_b_name
   PP1,dcim.frontport,Port 2,PP2,dcim.frontport,"11,12"
   ```
4. B-side here is a double port in an SC panel. Each side marked with its own number.
   ![image](https://github.com/netbox-community/netbox/assets/1938389/616a1d85-a51a-4175-b64f-4015bc85fa01)
5. A-side is your typical 24-port LC patch panel.

### Expected Behavior

Importer should succed. Used the exact same format the CSV data exporter outputs for the Cable (if created manually in the Web-UI).

### Observed Behavior

The bulk importer fails the creation of the cable. ⛔

![image](https://github.com/netbox-community/netbox/assets/1938389/1822755b-0d94-479b-9be0-cc2ab88b601e)

Creating of the same cable using the Web-UI wizard successfully completes the cable creation. ✅

![image](https://github.com/netbox-community/netbox/assets/1938389/47abeb38-4d37-4570-99c0-d470a5baa7bc)

I use the CSV format for the importer.

**Comment by jsenecal** [comment]
I too suffer from this. Is there another case of bulk import that supports many-to-one imports ? I would volunteer to fix this bug if there is.

**Comment by netravnen** [comment]
> I too suffer from this. Is there another case of bulk import that supports many-to-one imports ? I would volunteer to fix this bug if there is.

@jsenecal I would _guess_ using the REST API to create the objects works. But I not tested this.

**Comment by jsenecal** [comment]
> > I too suffer from this. Is there another case of bulk import that supports many-to-one imports ? I would volunteer to fix this bug if there is.
> 
> @jsenecal I would _guess_ using the REST API to create the objects works. I have not tested this.

The REST API is not on topic here. I'm asking about another model that uses the CSV importer _the right way_ with many-to-one relations

**Comment by netravnen** [comment]
> Is there another case of bulk import that supports many-to-one imports

Afaik, no.

I use CSV importing for data to a certain extent for several object types.

I only ran into this issue when LC / SC panels assigned numbers for _all_ positions on the panel.

**Comment by jeremystretch** [comment]
Closing this out as stale as no one has volunteered to own the work.
