### ISSUE TITLE
Devices - Virtual Chassis Domain Name field limiting entries

### ISSUE THREAD

**Issue by mprindle8598** [netbox-community/netbox#15713]
### Deployment Type

Self-hosted

### NetBox Version

v3.7.3

### Python Version

3.10

### Steps to Reproduce

1. Add a new virtual chassis
2. Attempt to enter a domain longer than 30 characters
3. Longer than 30 characters is not allowed.

### Expected Behavior

Expected is a string longer than 30 characters. In our case we need around 33.

### Observed Behavior

The field entry is set at a max of 30.

**Comment by jeremystretch** [comment]
The 30-character limit is intentional. If you would like to propose raising the limit, please submit a [feature request](https://github.com/netbox-community/netbox/issues/new?assignees=&labels=type%3A+feature%2Cneeds+triage&projects=&template=feature_request.yaml) citing justification for doing so.
