### ISSUE TITLE
Unable to assign VM/Device in one site to cluster that has no site

### ISSUE THREAD

**Issue by jon-nfc** [netbox-community/netbox#15717]
### Deployment Type

Self-hosted

### NetBox Version

v3.7.5

### Python Version

3.11

### Steps to Reproduce

1. create vm/device and assign it to a site
2. create a cluster, don't assign any site
3. attempt to assign the created device/vm in step 1 to the cluster

Error message `The selected cluster (<cluster name>) is not assigned to this site (<site name>)`

### Expected Behavior

If a cluster has no site set, then a VM/device from any site should be assignable to it. Without being able to do this, it's not possible to track a cluster that spans multiple DC.

### Observed Behavior

Can't assign a device/vm with a defined site to a cluster with no defined site (`null`)

**Comment by nopg** [comment]
I'm looking for 'easy' first bug fixes to help with for NetBox. This issue appears to have been accepted, so does that mean the powers-that-be are good with allowing VM's assigned to a site to be associated with a Cluster that doesn't have a Site? 

Seems fairly basic, I'm just wondering if and how I could help. Looks like a simple tweak to: https://github.com/netbox-community/netbox/blob/3c3943c809aa16499d603acdd160fe431bd8720c/netbox/virtualization/models/virtualmachines.py#L180 . 

Should it only be allowed for clusters without a Site assigned, should Clusters be allowed to be assigned to multiple Sites, etc?

**Comment by jon-nfc** [comment]
> Should it only be allowed for Clusters without a Site assigned, should Clusters be allowed to be assigned to multiple Sites, etc?

A Cluster, like in my case can span the globe. Different providers in different regions. The VM's that the cluster runs on, in this case kubernetes do have a site, being their DC.

**Comment by nopg** [comment]
I can submit a PR allowing device/vm's with a site, to be assigned to a non-site cluster as described above, if allowed :)

**Comment by jon-nfc** [comment]
> I can submit a PR allowing device/vm's with a site, to be assigned to a non-site cluster as described above, if allowed :)

Don't know what this allow business is? Generally with Open Source projects, you raise the PR and submit. That's generally the only time you'll have input. Obviously I'm all for the issue being fixed!!

**Comment by nopg** [comment]
I'm new here but I believe I have to be assigned to the issue before I can/should submit the PR. I have it ready to submit (diff at link below), it appears Devices already have this logic, so I updated VM's to match, added a new test for VM's, and all the similar tests to Devices since they didn't already exist.

https://github.com/netbox-community/netbox/compare/develop...nopg:netbox:15717-vm-cluster-site?diff=split&w=

**Comment by jon-nfc** [comment]
> I believe I have to be assigned to the issue before I can/should submit the PR

Where'd that come from? If that's the policy to contribute to this repo, I can't imagine anyone coming back, let alone starting in the first place. 2-3 days avg turn around, it'd be a week before you even had the PR started. All that time wasted just for a line of code. When in the end all that is needed is to submit the PR, if it's not good to go, it'll be denied.

**Comment by jeremystretch** [comment]
@jon-nfc please take some time to read our [contributing policy](https://github.com/netbox-community/netbox/blob/develop/CONTRIBUTING.md). These policies have been put in place to protect everyone's time. If you find yourself unable or unwilling to abide by it, please respectfully refrain from engaging with the project.

**Comment by jon-nfc** [comment]
@peteeckel @jeremystretch

Until such a time that I have done something wrong, both of you need to pull your head in. What the two of you have done is attacked a person without just cause and for a general remark that doesn't warrant any such response the two of you have provided. 


This is the icing on the cake....

> @jon-nfc please take some time to read our contributing policy. These policies have been put in place to protect everyone's time. If you find yourself unable or unwilling to abide by it, please respectfully refrain from engaging with the project.

.... A Netbox official statement.

Here's my response... No, that's not your responsibility, and no.


_"Those who would give up essential liberty, to purchase a little temporary safety, deserve neither liberty nor safety."_ Benjamin Franklin

**Comment by DanSheps** [comment]
@nopg I am going to assign this to you.  Feel free to submit the PR when you are ready.
