### ISSUE TITLE
Quick search affects available prefixes listed in IPAM

### ISSUE THREAD

**Issue by allenderj** [netbox-community/netbox#15714]
### Deployment Type

Self-hosted

### NetBox Version

3.6.4

### Python Version

3.8

### Steps to Reproduce

Select prefix, navigate to child prefixes, select show available. Put a CIDR notation query in the quick search form. 

### Expected Behavior

Should filter down the available prefixes that match the CIDR notation being searched for.

### Observed Behavior

The entire list of available prefixes appears to be recalculated. The available prefixes observed after are not available for assignment.

**Comment by jeremystretch** [comment]
> The entire list of available prefixes appears to be recalculated. The available prefixes observed after are not available for assignment.

Yes, this is working as intended. Available prefixes are not (and cannot) be annotated when viewing a filtered list of prefixes.
