### ISSUE TITLE
Add Image Attachments to Virtual Machines

### ISSUE THREAD

**Issue by Hedius** [netbox-community/netbox#15712]
### NetBox version

4.0

### Feature type

New functionality

### Proposed functionality

Extend virtual machines with the ability to add image attachments.

1. Inherit the ImageAttachmentsMixin in the  VirtualMachine model.
2. Add the required template to the object view for VMs

https://github.com/Hedius/netbox/tree/15712-add_imageattachments_to_virtualmachines

### Use case

I acknowledge that this feature (according to the FAQ) is or was initially meant for uploading photos of hardware and racks.

Our NetBox partly evolved into us uploading diagrams etc. into devices to extend the comment section with them.
(We document there what a host / server is doing etc.)
It would be a nice to have if we can do the same in virtual machines.
Main advantage is that you have those images directly linked to the host.

I do not know how other organizations use this feature, but having the same abilities for bare metal servers and virtual machines seems right to me.

Would this change be acceptable to you?

Adding the modal to VMs would not extend the complexity of NetBox.

### Database changes

None

### External dependencies

None

**Comment by Hedius** [comment]
I would like to open a pull request for this if this request gets accepted: https://github.com/Hedius/netbox/tree/15712-add_imageattachments_to_virtualmachines provides the required changes.

**Comment by jeffgdotorg** [comment]
Thanks for your interest in helping improve NetBox, and especially for the well-reasoned issue body. It makes sense to me even though the front / rear image support for Devices exists at the Device Type level, for which no analog currently exists in VMs.

I'm moving this issue into `accepted` and assigning to you for implementation. Two caveats:

- I notice that the FR specifies NetBox 4.0, while your branch appears to be based on `develop`. You'll need to rebase against `feature` if that's the release you mean to target.
- The `accepted` status label is provisional; I'm just triaging at this point.

**Comment by jeremystretch** [comment]
Tagging this for v4.0.
