### ISSUE TITLE
Rack Elevation Background

### ISSUE THREAD

**Issue by mmfreitas** [netbox-community/netbox#15722]
### Deployment Type

Self-hosted

### NetBox Version

v4.0-beta1

### Python Version

3.8

### Steps to Reproduce

![image](https://github.com/netbox-community/netbox/assets/91552302/31ed27c5-9176-4be5-9bc2-fbc1c81c7e18)

Background of rack elevations does not have dark theme.

### Expected Behavior

Rack elevation blends into dark background

### Observed Behavior

Rack elevation background is white

**Comment by jeremystretch** [comment]
This was resolved under #15617 and will be fixed in the next release.
