### ISSUE TITLE
Removal of `staff_only=True` from Admin menu items

### ISSUE THREAD

**Issue by markkuleinio** [netbox-community/netbox#15754]
### NetBox version

v4.0-beta1

### Feature type

Change to existing functionality

### Proposed functionality

The proposal is to remove `staff_only=True` condition from Admin menu items.

Some additional changes will be required to ensure that a normal user (without Superuser access) does not see the Admin menu items where they don't have access anyway.

### Use case

Currently, if a Superuser has the Staff status removed, the user cannot access the Admin menu items anymore.

Discussed in #15733. Related comments also in the mainteners meeting minutes in #15089

### Database changes

None

### External dependencies

None

**Comment by jeremystretch** [comment]
Some additional context:

- In NetBox v3.6, the UI views for managing users, groups, permissions, API tokens, and configuration revisions were moved from the "backend" Django admin UI to the primary UI.
- In NetBox v4.0, the remaining admin views were relocated to the primary UI, and the Django admin UI is disabled by default. (It can still be enabled for plugins which require it.)
- A custom user model was introduced in NetBox v4.0.

As our ultimate goal is to remove the Django admin UI from NetBox entirely, and as we now have the ability to customize fields on the user model, IMO we should drop the `is_staff` field entirely and rely on the permissions framework to control the display of individual navigation menu items.
