### ISSUE TITLE
Tags Bulk Importer - Allow specifying the id column to bulk update existing tags

### ISSUE THREAD

**Issue by netravnen** [netbox-community/netbox#15771]
### NetBox version

v3.7.5

### Feature type

Data model extension

### Proposed functionality

Allow field option `id` of the existing tags. Currently only columns "name;slug;color;description" are allowed when using the importer.

![image](https://github.com/netbox-community/netbox/assets/1938389/2f06a820-da72-4f8d-b9cb-1f2c851d0973)

### Use case

to be able to bulk update tags using the "Tag Bulk Import"at `https://demo.netbox.dev/extras/tags/import/`

### Database changes

None

### External dependencies

None

**Comment by jeremystretch** [comment]
FYI this functionality is supported today. It's just that the `id` field isn't listed as a supported column in the reference panel.

**Comment by netravnen** [comment]
> It's just that the `id` field isn't listed as a supported column in the reference panel.

Oh :open_mouth: I see :sweat_smile:

**Comment by Julio-Oliveira-Encora** [comment]
I tested, and if you add an "id" of an existing TAG, that tag will be updated; that is, the functionality exists. Adding instructions for the bulk update may be suitable.
