### ISSUE TITLE
Make the "Related Objects" pane of all models dynamic

### ISSUE THREAD

**Issue by alehaa** [netbox-community/netbox#15794]
### NetBox version

v3.7.5

### Feature type

Change to existing functionality

### Proposed functionality

In #13794, extending the "Related Objects" by other showing other models was requested and implemented by dynamically listing counts for all `ManyToMany` reverse relationships. Now, I'd like to copy this functionality to all other uses of the "Related Objects" pane,

### Use case

As described in #13794, it might be useful for plugins to link their data to existing NetBox core models. However, this is not only useful for tenancy, but any object relationship could benefit from this. 

A real life example is covered by the [NetBox inventory](https://github.com/ArnesSI/netbox-inventory) plugin: Hardware assets are related to `dcim.Device`, `dcim.Manufacturer`, `dcim.Site` and `dcim.Location`. They would benefit from quick access to a list of related assets for these models. Right now an extra pane needs to be implemented, so there are actually two "Related Objects" panes per details page.

Also, this would make this feature work consistently across all views in NetBox, so the maintenance overhead should theoretically be reduced.

### Database changes

None

### External dependencies

None

**Comment by alehaa** [comment]
I've already tested using the code from `TenantView ` in other views and can provide a PR for the changes requested.

**Comment by arthanson** [comment]
@alehaa sounds good, I'll assign to you -  Note: you should capture the existing logic into a reusable function (vs. copying and pasting the current get_extra_context() for TenantView)
