### ISSUE TITLE
Dark mode anchor contrast to low

### ISSUE THREAD

**Issue by alehaa** [netbox-community/netbox#15802]
### Deployment Type

Self-hosted

### NetBox Version

v4.0-beta1

### Python Version

3.11

### Steps to Reproduce

1. Activate dark mode
2. Navigate to Site list
3. Inspect first columns site name with the browser debug toolbar
4. Check text color and background color attributes
5. Calculate contrast ratio.

### Expected Behavior

According to WCAG 2.1 accessibility standard, a bare minimum contrast ratio of 3:1 is required, 4.5:1 would be better.

### Observed Behavior

A ratio of 2.92:1 was calculated.

Responsible for the link color is the CSS variable `--tblr-link-color-rgb`. I found that the [Tabler Demo](https://preview.tabler.io/tables.html) uses slightly different colors. However, I can't find the cause why, as [netbox.scss](https://github.com/netbox-community/netbox/blob/v4.0-beta1/netbox/project-static/styles/netbox.scss) doesn't seem to change related Tabler variables.

**Comment by jeffgdotorg** [comment]
Thanks for your report. We're aware that 4.0-beta1 has many low visual contrast problems and we hope to address them before the final.
