### ISSUE TITLE
Menu not collapsing properly

### ISSUE THREAD

**Issue by PieterL75** [netbox-community/netbox#15814]
### Deployment Type

Self-hosted

### NetBox Version

v4.0-beta1

### Python Version

3.8

### Steps to Reproduce

open the 'devices' menu
open a menu item near the bottom of the screen

### Expected Behavior

The newly opened menu his sub items are visible.
Any other open (the devices in this case) is closed

### Observed Behavior

The submenu items are off-screen.

**Comment by arthanson** [comment]
This is not considered a bug, it is the way the new menu works - it does allow you to keep different menu items open and you can scroll the menu.  That said, if you think it should be changed, please open a feature request or discussion.

**Comment by PieterL75** [comment]
Its a behavior change that is not in the releasenotes,  it looks like a bug...
IT for sure does not work properly, even with the idea that this is the new behaviour, to keep the menu op.

If I open a menu item at the bottom of the page, the menu should scroll to see all submenu items right away.
