### ISSUE TITLE
Multiselect has no 'delete' option on the values

### ISSUE THREAD

**Issue by PieterL75** [netbox-community/netbox#15817]
### Deployment Type

NetBox Cloud

### NetBox Version

v4.0-beta1

### Python Version

3.8

### Steps to Reproduce

Open a device and edit
go to the tags fiels
Add some tags

### Expected Behavior

Each tag should have an 'x' so that the tag can be removed from the multiselect

### Observed Behavior

no 'x'
![image](https://github.com/netbox-community/netbox/assets/74899468/53d8e5bb-a876-4b37-95c8-a72a3da91993)

this seems to be the case on all multivalue fields, and not only tags

**Comment by jeremystretch** [comment]
This is not a bug; it's how [Tom-Select](https://tom-select.js.org/examples/) works. Selected items can be removed using the delete or backspace keys. Please submit a [feature request](https://github.com/netbox-community/netbox/issues/new?assignees=&labels=type%3A+feature%2Cstatus%3A+needs+triage&projects=&template=feature_request.yaml) if you would like to propose an additional mechanism for deleting items.

**Comment by PieterL75** [comment]
It is hard to tell what you guys define as a change or as a bug.
As there was an X in v3, I would assume that there is still an X in v4.

Changing that behaviour is counter productive, I have to release my mouse and press backspace and get my mouse again...
To me, this is a bug/oversight and not a new feature

**Comment by jeremystretch** [comment]
> It is hard to tell what you guys define as a change or as a bug.

I believe the [contributing guide](https://github.com/netbox-community/netbox/blob/develop/CONTRIBUTING.md#bug-reporting-bugs) is quite clear:

> Bug reports are used to call attention to some unintended or unexpected behavior in NetBox, such as when an error occurs or when the result of taking some action is inconsistent with the documentation. **Bug reports may not be used to suggest new functionality**; please see "feature requests" below if that is your goal.

If you find yourself having difficulty making the distinction for a particular issue, submit is as a feature request.
