### ISSUE TITLE
Limit Access

### ISSUE THREAD

**Issue by RenatoPereira91** [netbox-community/netbox#15810]
### NetBox version

v3.7.3

### Feature type

New functionality

### Proposed functionality

I'm trying to allow control access for other employers, but always have one thing that not show, example the interfaces of devices.

I would like one way that I can easier set (site or tenant) that one user can access and all thing under can access too.

### Use case

Ease way to segregate access

**Comment by DanSheps** [comment]
Hello @RenatoPereira91,

Thank you for your interest in extending NetBox. Unfortunately, the information you have provided does not constitute an actionable feature request. Per our [contributing guide](https://github.com/netbox-community/netbox/blob/develop/CONTRIBUTING.md), a feature request must include a thorough description of the proposed functionality, including any database changes, new views or API endpoints, and so on. It must also include a detailed use case justifying its implementation. If you would like to elaborate on your proposal, please modify your post above. If sufficient detail is not added, this issue will be closed.

**Comment by jeffgdotorg** [comment]
Thank you for your interest in extending NetBox. Unfortunately, the information you have provided does not constitute an actionable feature request. Per our [contributing guide](https://github.com/netbox-community/netbox/blob/develop/CONTRIBUTING.md), a feature request must include a thorough description of the proposed functionality, including any database changes, new views or API endpoints, and so on. It must also include a detailed use case justifying its implementation. If you would like to elaborate on your proposal, please modify your post above. If sufficient detail is not added, this issue will be closed.
