### ISSUE TITLE
UI sometimes becomes unresponsive with HTMX navigation enabled after configuring table columns

### ISSUE THREAD

**Issue by opericgithub** [netbox-community/netbox#15820]
### Deployment Type

Self-hosted

### NetBox Version

v4.0-beta2

### Python Version

3.10

### Steps to Reproduce

1. enable HTMX navigation in user preferences
2. go to any table (i.e. devices -> device roles)
3. click "Configure Table" in the upper right corner
4a. make any change in the sense of adding or removing columns (use add/remove buttons) and click Save, or just simple:
4b. click Save without any add/remove changes

### Expected Behavior

new arrangement of columns should be applied

### Observed Behavior

UI sometimes becomes unresponsive, page reload is required

**Comment by julianstolp** [comment]
Have also observed this issue with the color theme toggle https://github.com/netbox-community/netbox/issues/15819#issuecomment-2072170045
