### ISSUE TITLE
Rename Microsoft Azure AD to Microsoft Entra ID

### ISSUE THREAD

**Issue by zacho112** [netbox-community/netbox#15829]
### Netbox version

v4.0.2

### Feature type

Change to existing functionality

### Proposed functionality

[Microsoft renamed Azure AD to Entra ID](https://learn.microsoft.com/en-us/entra/fundamentals/new-name)

Rename string and filenames in [these files](https://github.com/search?q=repo%3Anetbox-community%2Fnetbox%20Microsoft%20Azure%20AD&type=code).

Most important I'd like to get the wording on the frontpage changed to match the correct and new name, Microsoft Entra ID.
<img width="351" alt="image" src="https://github.com/netbox-community/netbox/assets/5525192/511091dd-54f2-450d-a15b-417234870bab">

Also update the documentation as well

### Use case

Makes name match Microsoft's new branding

### Database changes

None

### External dependencies

None.

I'd gladly create the PR and update the files my self.

**Comment by jeffgdotorg** [comment]
Thanks for opening this issue. One clarification before we'll be able to talk about a PR:

> I'd like to get the wording on the frontpage changed
Is this ask specific to the docs, or is it scoped to the NetBox UI itself? In the latter case, please revise this issue's body to remove it and create a separate enhancement issue.

**Comment by zacho112** [comment]
Most important I'd like the UI to change :) But I think it would be great to have the docs updated as well, which is why I created both in the same issue, but I understand if I need to split it up.

So just to ensure that I'm doing it the right way, I edit this issue to only take care of the actual docs, and create a new issue that handles the string/code changes in the codebase?

**Comment by arthanson** [comment]
@zacho112 I think we can keep it as a single issue, I changed the format to be a feature request as it requires code changes.

**Comment by Julio-Oliveira-Encora** [comment]
Could you please assign it to me?

**Comment by alehaa** [comment]
I can provide a PR for this.
