### ISSUE TITLE
EXEMPT_EXCLUDE_MODELS contains old user and group models

### ISSUE THREAD

**Issue by tobiasge** [netbox-community/netbox#15826]
### Deployment Type

Self-hosted

### NetBox Version

v4.0-beta2 (e05ca710ae47db49f8552a77b996ab4f69abaedc)

### Python Version

3.11

### Steps to Reproduce

1. None; `EXEMPT_EXCLUDE_MODELS` is a hard coded setting

### Expected Behavior

`EXEMPT_EXCLUDE_MODELS` has the new user and group model

### Observed Behavior

`EXEMPT_EXCLUDE_MODELS` contains old models

**Comment by arthanson** [comment]
I'm not certain if those still need to be there, can probably be removed but needs to be checked.
