### ISSUE TITLE
AttributeError: 'datetime.date' object has no attribute 'utcoffset'

### ISSUE THREAD

**Issue by nascimbe** [netbox-community/netbox#15838]
### Deployment Type

Self-hosted

### NetBox Version

v4.0-beta2

### Python Version

3.11

### Steps to Reproduce

1. Assign a date type custom-field to any object-type in NetBox v3.7.6 (found in IP address, Virtual Machines)
2. Migrate to NetBox v4.0-beta2 using upgrade.sh
3. Open any object instance with a date custom field assigned

### Expected Behavior

The object page is shown correctly

### Observed Behavior

Server Error

```
<class 'AttributeError'>

'datetime.date' object has no attribute 'utcoffset'

Python version: 3.11.5
NetBox version: 4.0-beta2
Plugins: None installed
```

Removing custom-fields of type date resolves the issue

**Comment by cs-1** [comment]
Same problem for Racks.

**Comment by opericgithub** [comment]
We have the same problem. Makes the v4.0 unusable since almost all our devices have custom field of type date.
