### ISSUE TITLE
Display the TAG column in the journal (E.g. device journal).

### ISSUE THREAD

**Issue by LHBL2003** [netbox-community/netbox#15859]
### NetBox version

v3.7.6

### Feature type

Change to existing functionality

### Proposed functionality

Add the TAG column to the Journal overview, as this can also be specified. (https://netbox/dcim/devices/XXX/journal/)
Better clarity as the tags are also displayed. This also applies to device types, for example.

![image](https://github.com/netbox-community/netbox/assets/46369917/87b76dbf-ff11-4e25-a411-8f8cec8dc213)

### Use case

Better overview in the list.

### Database changes

none

**Comment by jeremystretch** [comment]
The object journal table uses the same configuration as the global table. You can enable the tags column for both views by going to Operations > Journal entries, clicking the "configure" button, and adding the column:

![screenshot](https://github.com/netbox-community/netbox/assets/13487278/8c3bc47c-795a-4895-ad12-ed1bba41746c)

Then you'll see the column displayed under the object journal:

![screenshot](https://github.com/netbox-community/netbox/assets/13487278/74f980ac-15b5-41c3-8b8d-c3befd29ba91)
