### ISSUE TITLE
SVG UI elements background issues in dark mode

### ISSUE THREAD

**Issue by jsenecal** [netbox-community/netbox#15853]
### Deployment Type

Self-hosted

### NetBox Version

v4.0-beta2

### Python Version

3.11

### Steps to Reproduce

1- Create a 42 RU rack
2- Create two devices-types with interfaces, then two devices of this type and assign them to this rack.
3- Connect the interfaces together using a cable
4- Navigate the Rack elevation or perform a cable trace

(step 4 can also be simply executed on https://beta-demo.netbox.dev/ with existing demo data)

### Expected Behavior

SVG objects should have their color-scheme set to auto, which should display a transparent background, and white text for labels in dark mode.

![image](https://github.com/netbox-community/netbox/assets/1564902/fea33c29-f1f7-4f74-ab29-e7259c89bf21)
![image](https://github.com/netbox-community/netbox/assets/1564902/31461b67-8912-4e37-a40a-8d57a084c47b)

### Observed Behavior

SVG objects are displaying a white background (and black text) with bad looking padding which is not aligned with the rest of the UI. This is observed on a chrome based browser. Safari seems to have a transparent background which lack contrast with the text.

![image](https://github.com/netbox-community/netbox/assets/1564902/6aaf4398-bc1c-434e-b68a-75b4216293fd)
![image](https://github.com/netbox-community/netbox/assets/1564902/22d53d5d-2e8d-4452-86fc-22aee229bc41)

**Comment by arthanson** [comment]
This is a superset of #15819 leaving this one open as it shows there are more effects then just the rack-elevation.

**Comment by arthanson** [comment]
The rack one I think is HTMX enabled issue only, it works fine on mine if that is not enabled.  I do see the cable trace one being the wrong background even if HTMX is not enabled. Strangely safari displays it fine but chrome does not.
