### ISSUE TITLE
Restrict bulk edit dropdown choices to valid ones

### ISSUE THREAD

**Issue by llamafilm** [netbox-community/netbox#15857]
### NetBox version

v3.7.3

### Feature type

Change to existing functionality

### Proposed functionality

When bulk editing multiple devices, it would be helpful to restrict the dropdown choices to valid ones.

### Use case

For example, I have 10 devices in the same site, and I want to move them from one location to another location within that site.  In the bulk edit page, the `Location` dropdown list shows all locations, which is several thousand to sort through.  If I accidentally choose a location from a different site, I get an error like _Location A Beautiful Life does not belong to site LA-EGT._

It's even more problematic if I have multiple locations with the same name.

### Database changes

none

### External dependencies

none

**Comment by jeffgdotorg** [comment]
If you set the Site field during a bulk edit, the previously wide-open list of available Location values is automagically reduced to just ones at the selected Site. I just verified this in both 3.7.4 and 4.0-beta1. This auto-winnowing also applies to other hierarchical objects such as Manufacturer and Device Type.

Closing not-planned for this specific, narrow use case.

**Comment by llamafilm** [comment]
Thanks for testing. I did not think to try that, because when bulk editing I try to make the change as narrow as possible. But this makes perfect sense, so I agree there’s no need for a change.
