### ISSUE TITLE
Add GPON OLT Interface Type

### ISSUE THREAD

**Issue by brandan-schmitz** [netbox-community/netbox#15854]
### NetBox version

v3.7.6

### Feature type

Data model extension

### Proposed functionality

I would like to see an additional interface type of GPON OLT added to Netbox.

### Use case

Calix E7-2 GPON-8 cards use these type of ports as a way to collect many different fibers from various ONT's into a single port. They are different than a standard GPON port. They are also used by the GPON-8r2 cards.

https://www.opticalsolutions.com.au/wp-content/uploads/2018/11/clx-100-03006.pdf

**Comment by sleepinggenius2** [comment]
On the E7-2, we just model our GPON-8 cards with the existing GPON interface type, and likewise the XG801 cards with the existing XGS-PON interface type. For us at least, it just allows us to distinguish the technology in use (GPON vs XGS-PON), but we haven't found a need to distinguish the OLT and ONT side as different interface types.

**Comment by jeremystretch** [comment]
I'll admit I'm not personally familiar with PON technologies, but @sleepinggenius2's approach seems to be the preferred approach.
