### ISSUE TITLE
Unable to log in using remote auth after upgrade

### ISSUE THREAD

**Issue by johnmc-ucdavis** [netbox-community/netbox#15866]
### Deployment Type

Self-hosted

### NetBox Version

v3.7.6

### Python Version

3.10

### Steps to Reproduce

Attempt to log in to NetBox using remote login. Remote login completes but user is not logged in.

### Expected Behavior

User is logged in. 

### Observed Behavior

User is not logged in. Users can log in using local passwords. 

`REMOTE_USER` variable is set. We have also tried changing it to `HTTP_REMOTE_USER`. 

Same remote auth is working for several other web apps. It was working in v3.7.5 prior to upgrade.

Two users were able to remain logged in via. remote auth. We had one of these users log out and now this user does not get logged in when using remote auth.

**Comment by jeremystretch** [comment]
@johnmc-ucdavis this sounds like it's likely the same root issue as #15811. Please try downgrading gunicorn and let us know if that resolves the issue:

```
pip3 install gunicorn==21.2.0
```

(Don't forget to restart the NetBox service afterward!)

**Comment by johnmc-ucdavis** [comment]
That was indeed the problem. Thanks!

**Comment by apollo13** [comment]
Instead of down-grading you can probably configure `header-map` (https://docs.gunicorn.org/en/stable/settings.html#header-map) accordingly, but be aware of the downsides.
