### ISSUE TITLE
Usability Issue: Limit of visbile IP addresses

### ISSUE THREAD

**Issue by johannwagner** [netbox-community/netbox#15879]
### Deployment Type

Self-hosted

### NetBox Version

v3.7.5

### Python Version

3.11

### Steps to Reproduce

1. Add more than 3 IP addresses to a single interface

### Expected Behavior

See the first ~10 IP addresses and then a "See More" indicator or something more explaining than "3" or "12" in the interface or device table.

We have quite a lot of interfaces with four IP addresses, e.g. two device-specific IP addresses and two anycast IP addresses, one per protocol each. I support the general limitation of the visible IP addresses, but 3 is a little on the low side. 

### Observed Behavior

You see a hyperlink called "3" without any explanation.

**Comment by jeremystretch** [comment]
This is functioning as intended per #14645. If you would like to propose a change, please open a [feature request](https://github.com/netbox-community/netbox/issues/new?assignees=&labels=type%3A+feature%2Cstatus%3A+needs+triage&projects=&template=feature_request.yaml) citing your justification.
