### ISSUE TITLE
This function does not seem to exist: Show assigned IP address(es) of attached interface when viewing a circuit #661 

### ISSUE THREAD

**Issue by emallette** [netbox-community/netbox#15882]
### Deployment Type

Self-hosted

### NetBox Version

v3.7.6

### Python Version

3.8

### Steps to Reproduce

1. Create a circuit
2. Attach the circuit on both A Side and Z Side to interfaces.
3. Add an IPv4 address and an IPv6 address on the interface on Side Z.
4. Note: The IPv4 and IPv6 address show up in the IPAM address list.
5. Note: Neither the IPv4 or IPv6 address show up associated with the circuit.

### Expected Behavior

Based on Issue #661 this function is supposed to be available.

### Observed Behavior

There was no noticeable change to the circuit - there doesn't seem to be a place for the IPv4 or IPv6 address to show up along with the circuit.

**Comment by jeremystretch** [comment]
Please use the [feature request template](https://github.com/netbox-community/netbox/issues/new?assignees=&labels=type%3A+feature%2Cstatus%3A+needs+triage&projects=&template=feature_request.yaml) to propose new functionality.
