### ISSUE TITLE
No Reverse Match for l2vpntermination_list

### ISSUE THREAD

**Issue by ajackson79** [netbox-community/netbox#15899]
### Deployment Type

Self-hosted

### NetBox Version

3.7.3

### Python Version

3.10

### Steps to Reproduce

Create a tag with the following type:
L2VPN Termination

Then create an L2VPN termination and include this tag. In the main list of all the l2vpn terminations add the tag column so it is visible.

Then anytime you try and view the l2vpn termination main page the server throughs an exception error

### Expected Behavior

Expect to see the l2vpn termination list without the error

### Observed Behavior

Server exception error.
<img width="997" alt="image" src="https://github.com/netbox-community/netbox/assets/26445346/9b8c9de7-16b8-44ae-acca-46e66e32f2b0">

**Comment by jeremystretch** [comment]
Thanks for the report. Looks like the table column is being initialized with an outdated view name.
