### ISSUE TITLE
L2VPN add route target for multiple edit 

### ISSUE THREAD

**Issue by GSeiNet** [netbox-community/netbox#15892]
### NetBox version

3.7.5

### Feature type

Change to existing functionality

### Proposed functionality

select some l2vpn
edit botton
GUI have no import / export route target field

### Use case

edit multiple l2vpn with same values 

### Database changes

no changes

### External dependencies

no

###
If i edit one L2VPN, GUI have route targets fields, if i select many L2VPNs and edit, GUI have no route target fields.
Please add the fields

**Comment by arthanson** [comment]
I don't think there would be any issue adding these two fields, but would need more in-depth checking.

**Comment by jeremystretch** [comment]
@GSeiNet please edit your post above to detail specifically what functionality you're proposing be added.

**Comment by GSeiNet** [comment]
@jeremystretch: If i edit one L2VPN, GUI have route targets fields, if i select many L2VPNs and edit, GUI have no route target fields.
