### ISSUE TITLE
Label custom script debug messages properly

### ISSUE THREAD

**Issue by llamafilm** [netbox-community/netbox#15905]
### NetBox version

v3.7.3

### Feature type

Change to existing functionality

### Proposed functionality

When printing debug messages with `self.log_debug()`, I think these messages should be labeled as"Debug" in the GUI.  Currently they are labeled "Default".

![image](https://github.com/netbox-community/netbox/assets/3991046/75952789-cc51-428f-97ac-0f61a5c4e6ca)

### Use case

Current behavior doesn't make sense

### Database changes

none

### External dependencies

none

**Comment by abhi1693** [comment]
This works as expected in v4.0
![image](https://github.com/netbox-community/netbox/assets/5083532/423085a1-c8fe-443f-aad5-9e2517039230)

**Comment by llamafilm** [comment]
@abhi1693 I’m curious how you created 80K devices that fast!
