### ISSUE TITLE
Interface mark planned/installed not working (4.0b2)

### ISSUE THREAD

**Issue by PieterL75** [netbox-community/netbox#15919]
### Deployment Type

NetBox Cloud

### NetBox Version

v4.0b2

### Python Version

3.10

### Steps to Reproduce

Using the public beta portal
https://beta-demo.netbox.dev/dcim/devices/2/interfaces/
Both icons for 'mark planned' and 'mark installed' are visible. 
I assume only the status the link is not in, should be displayed ?

Click the icons for 'mark planned' or 'mark installed'. 

### Expected Behavior

The status of the link changes to the clicked status

### Observed Behavior

Nothing happens

**Comment by PieterL75** [comment]
Strange.. On a local fresh insttalled it works as expected.
![image](https://github.com/netbox-community/netbox/assets/74899468/d6c6ab9d-29ed-47b6-9227-ecb3fce8a33f)


but on the public beta it does not
https://beta-demo.netbox.dev/dcim/devices/2/interfaces/
![image](https://github.com/netbox-community/netbox/assets/74899468/42343583-ed58-4db9-a798-d8b5b97039b4)

I cleared cache etc, but stil the same..

**Comment by jeremystretch** [comment]
Marking this as closed as the issue appears to be resolved. It was likely fixed under #13874.
