### ISSUE TITLE
slim-select-pagination-bug : user not able to load more than one page of data after a text search in slim select search box

### ISSUE THREAD

**Issue by MaxBear** [netbox-community/netbox#15917]
### Deployment Type

NetBox Cloud

### NetBox Version

v3.7.7-dev

### Python Version

3.11

### Steps to Reproduce

1. insert enough entries in extras_tag table such that for a search string "x" there are more than 50 (default max page size) items returned
2. open edit page for a dcim device interface
3. open tag dialogue box which uses a slim select GUI control under the hood, enter search string "x" in the filter search box
4. scroll down to the bottom of the returned list 
5.  notice you cannot get more items behind the first page of returned items although an api call to the next page is already made

### Expected Behavior

When user reaches the end of currently returned list of items more items will be extended to the list if there are more.  

### Observed Behavior

Current behaviour is that user will not be able to go behind the first page of returned items.

**Comment by MaxBear** [comment]
correction: the deployment type is `self-hosted`

**Comment by arthanson** [comment]
@MaxBear I see you have a PR in for this so assigning it to you.

**Comment by MaxBear** [comment]
Thanks @arthanson have you had a chance to code review my pr ?

**Comment by arthanson** [comment]
Actually @MaxBear this library has been completely removed in NB v4, so this would no longer apply.  Going to close this.

**Comment by MaxBear** [comment]
@arthanson we are still on v.3.4.10 for our netbox installation. Will my [fix ](https://github.com/netbox-community/netbox/pull/15918) still be looked at and included in a patch release ?

**Comment by jeremystretch** [comment]
Re-opening this for review as it looks like we'll end up cutting a v3.7.8 release for some unrelated bug fixes.
