### ISSUE TITLE
From VM INterface view clicking on the number of IPs assigned should send to IP list with an applied filter

### ISSUE THREAD

**Issue by xkilian** [netbox-community/netbox#15914]
### NetBox version

v3.7.2

### Feature type

Change to existing functionality

### Proposed functionality

When a VM Interface has more than 4(I think) IPs assigned it will show the count of assigned IP.
Clicking on this count should bring the IPAM/IP view with an applied filter of Assigned VM == "virtual_machine".

Currently clicking on the IP count simply brings us to the default IPAM/IP view.

### Use case

Show what IP adresses are assigned to a VM Interface.

### Database changes

None

### External dependencies

None

**Comment by jeremystretch** [comment]
This appears to have been addressed in a past release, as this is the current behavior on v4.0.8.
