### ISSUE TITLE
Please add Hybrid as an option for 802.1Q Mode for device interfaces

### ISSUE THREAD

**Issue by rfreddy** [netbox-community/netbox#15910]
### NetBox version

3.7.5

### Feature type

Change to existing functionality

### Proposed functionality

Some Dell switches use **portmode hybrid** in order to accept both tagged and untagged frames, set a physical port or port-channel. The explained use and syntax of this mode can be found here:
https://www.dell.com/support/manuals/en-in/dell-emc-os-9/s5048f-on-9.14.2.5-cli-pub/portmode-hybrid?guid=guid-3280b4ea-bb9f-4ca2-8d0f-9cb146504b1b&lang=en-us
The way Netbox is configured right now is to have the interface 802.1Q Mode on Access, Tagged or Tagged-all that allows the port to be in one mode either untagged or tagged but in Hybrid mode the port can be on both.

### Use case

This option will be useful when creating a config template to add the following command 'portmode hybrid' into the switch interface allowing to have untagged and tagged vlans on it.   

### Database changes

No change needed in database or fields, it only an additional text field 

### External dependencies

None

**Comment by jeremystretch** [comment]
> Some Dell switches use portmode hybrid in order to accept both tagged and untagged frames, set a physical port or port-channel.

This is synonymous with the concept of a "native" VLAN; the VLAN into which any untagged frames are placed. NetBox permits you to assign both tagged VLANs and the untagged VLAN for an interface.

**Comment by jeremystretch** [comment]
Closing this as it appears the proposed functionality is already supported.
