### ISSUE TITLE
Filter Multiselect behaviour change with empty query string (v3.7 vs v4.0)

### ISSUE THREAD

**Issue by PieterL75** [netbox-community/netbox#15920]
### NetBox version

v4.0b2

### Feature type

Change to existing functionality

### Proposed functionality

In v3.7, a multiselect field had a text filter where values could be searched.
In v4.0, the multiselect is a scrollfield showing all values, and a CTRL-click is required to select multiple fields

This happens when the query string is empty

Ex: working as before (click the 'filters' tab)
https://beta-demo.netbox.dev/dcim/devices/?q=&serial=&asset_tag=&mac_address=&console_ports=&console_server_ports=&power_ports=&power_outlets=&interfaces=&pass_through_ports=&has_primary_ip=&has_oob_ip=&virtual_chassis_member=&config_template_id=1&local_context_data=&cf_testing=

Unintentionally filled fields : https://beta-demo.netbox.dev/dcim/devices/?config_template_id=1

### Use case

Even with a simple query string, the form should only prefill the values from the query

**Comment by jeffgdotorg** [comment]
I'm not having any luck reproducing what you describe, or perhaps I've misunderstood your meaning.

The second link selects only the `gre` config template, even if I try to tickle a corner case by picking values for a few other fields, submitting, then editing the URL to include only the `config_tempalte_id` param. I also tried this with HTMX navigation both enabled and disabled, and it made no difference – although with HTMX enabled, the natural URLs created looked like the first one, compared to ones like the second one with HTMX disabled. That might be a clue.

**Comment by jeremystretch** [comment]
This issue is being closed as no further information has been provided. If you would like to revisit this topic, please first modify your original post to include all the requested detail, and then ask that the issue be reopened.
