### ISSUE TITLE
Custom link confirmation dialog box

### ISSUE THREAD

**Issue by akshay225063** [netbox-community/netbox#15927]
### NetBox version

v3.6.9

### Feature type

Change to existing functionality

### Proposed functionality

I have created 2 custom links "Block company" and "Unblock company" .
Currently If I click on any of the button then it will do the required operation but I need to add a confirmation dialog before it will do any operation just like we have inbuilt confirmation dialog added for "delete" button.

![first_img](https://github.com/netbox-community/netbox/assets/67414818/fdba5b60-6049-4601-b191-651f2860e2f0)
![second_img](https://github.com/netbox-community/netbox/assets/67414818/9bf4d82d-03a7-4648-9d31-ea749217312d)

### Use case

Currently we only add this feature for delete button where confirmation of the user is required but for other custom links this feature is not implemented.
![second_img](https://github.com/netbox-community/netbox/assets/67414818/fb78bf58-6c68-4227-8197-b995654ea29a)

**Comment by jeremystretch** [comment]
Thank you for your interest in extending NetBox. Unfortunately, the information you have provided does not constitute an actionable feature request. Per our [contributing guide](https://github.com/netbox-community/netbox/blob/develop/CONTRIBUTING.md), a feature request must include a thorough description of the proposed functionality, including any database changes, new views or API endpoints, and so on. It must also include a detailed use case justifying its implementation. If you would like to elaborate on your proposal, please modify your post above. If sufficient detail is not added, this issue will be closed.

**Comment by arthanson** [comment]
@akshay225063 can you please expand on what you want here?  It sounds like you have added some extra code for the block and unblock but want us to add a custom dialog for it?  You can look at the code for the delete confirmation modal and potentially use that for your confirmation modal.  Or are you looking for some type of extension mechanism?

**Comment by arthanson** [comment]
Closing as no feedback.

**Comment by akshay225063** [comment]
Hello @arthanson 
Yes you are correct I have block and unblock code which get executed when custom link block and unblock company clicked.
But when It clicked instead of executing the code user should get custom dialog to confirm 
it . 
Now I don't know how I can do this integration because for custom links I cannot do any modifications in the code even if I have deleted confirmation modal code but I am not able to implement same with block and unblock custom links. 
Note: I have implemented these custom links in Site modal .

Please let me know if any more information required.
