### ISSUE TITLE
Support for half-width device type v2

### ISSUE THREAD

**Issue by vinceberg** [netbox-community/netbox#15945]
### NetBox version

v3.7.3

### Feature type

Data model extension

### Proposed functionality

Under Device Type, add a check box "Is Half-width".
Under Device\Location, change "Position" to include "Left" and "Right" in the drop down when the device type is half-width.

### Use case

The currently supported approach to modeling half-width devices does not support modular chassis.
We do have HP EL8000 Chassis that have 8 half U bays(https://www.hpe.com/psnow/doc/a00067727enw). If I create a parent device as a place holder for the right and left chassis, I cannot create the chassis as a parent and therefore cannot install the blade server childs.

**Comment by jeffgdotorg** [comment]
This FR will need significant expansion if we're to accept it. The flexibility required to support this kind of device simply isn't supported at the moment, so many aspects of the NetBox model for racks and devices would need updating.

As a starting point, we need a reasonably detailed outline of a proposal for fundamentally overhauling our current approach to modeling the racking of devices, so that it accommodates things that behave like half-width blade servers. Your use case would also need to articulate additional examples of device types that behave this way, so that the team knows they're not sinking a huge amount of work into enabling a niche use case.

**Comment by ITJamie** [comment]
some examples of half-width devices ive seen:

opengear om1200's - https://resources.opengear.com/om/datasheets/om1200/ (there's quite a few opengear devices based on this chassis)
ecler gear https://www.ecler.com/products/1uhrmkit/ ( a lot of audio industry devices are half-width )
qnap m2106pr-2s2t https://www.qnap.com/en/product/qsw-m2106pr-2s2t

its not uncommon to see the above devices mounted with just one "ear" depending on the side of the rack it's mounted to

**Comment by DrDoc777** [comment]
We also have half-width devices in racks (e.g. RME ADI-4 DD & MOXA UPort 1610-8 ) and still haven't found a no solution how to get these documented on same RU in netbox. 
There's definitely a use-case for half-width devices. 
If it's possible to define "front-side" & "rear-side" as installation in a rack, then "left-side" & "right-side" should be possible too. Tricky part might be the appropriate visualization in the rack-view.

**Comment by jeremystretch** [comment]
@vinceberg as @jeffgdotorg points out above, this FR requires a _much_ more detailed technical proposal to move forward. Please spend some time getting familiar with how NetBox currently models racked devices, consider how this model might be expanded to serve your use case, and update your proposal above accordingly. If you're not yet ready to submit a concrete feature request, please consider starting a [discussion](https://github.com/netbox-community/netbox/discussions/new/choose) to exchange ideas with other users instead.

**Comment by ymjpajak** [comment]
Is it possible to add this feature to NetBox? I need to visualize a  rack with 8 chassis , four on the left and four on the right side, and I already use device bays  (parent-child relation) to implement blades in the chassis ( and inventory items for servers in the blade).
