### ISSUE TITLE
VRF-id / RD as input field Prefix Import

### ISSUE THREAD

**Issue by oceans1908** [netbox-community/netbox#15958]
### NetBox version

v3.7.6

### Feature type

New functionality

### Proposed functionality

With Prefix Bulk Import function, it is not possible to select a VRF when there are multiple VRF's with the same name. An extra field for RD or vrf-id (which are always unique), would allow to use the import function.

### Use case

As we use multiple VRF's with the same name (we use the same VRF naming over multiple locations) we can't use the Bulk Import function.

**Comment by jeremystretch** [comment]
Closing this as the proposed functionality is already possible AFAICT and there's been no further discussion.
