### ISSUE TITLE
VPN IKE policies exported CSV contains HTML code

### ISSUE THREAD

**Issue by igsh667** [netbox-community/netbox#15960]
### Deployment Type

Self-hosted

### NetBox Version

v3.7.7

### Python Version

3.8

### Steps to Reproduce

Export to CSV of IKE policies contains HTML code "<a href=..." in Proposals column.

### Expected Behavior

Should not contain HTML code in exported file.

### Observed Behavior

Contains HTML code in exported file.

**Comment by jeremystretch** [comment]
There are a few instances where this happens because we're using the stock ManyToManyColumn instead of our own, which causes this issue:

* Interface `inventory_items`
* IPAddress `nat_outside`
* IKEPolicy `proposals`
* IPSecPolicy `proposals`
* TunnelTermination `ip_addresses`
