### ISSUE TITLE
System & background tasks menu items should display only for authenticated users

### ISSUE THREAD

**Issue by jeremystretch** [netbox-community/netbox#15977]
### Deployment Type

NetBox Cloud

### NetBox Version

v4.0.0

### Python Version

3.11

### Steps to Reproduce

1. Ensure that `EXEMPT_VIEW_PERMISSIONS` is not set in the configuration and that `LOGIN_REQUIRED` is false.
2. Open the NetBox UI as an unauthenticated user.

### Expected Behavior

The navigation menu should be empty.

### Observed Behavior

Links to the system and background task views are displayed under the "admin" heading in the menu. (Neither link works as both views require authentication.)

**Comment by jadyndev** [comment]
The above mentioned menu items are still shown to (authenticated) users without the required permissions to use these menus.
