### ISSUE TITLE
Assign VLAN to device

### ISSUE THREAD

**Issue by PieterL75** [netbox-community/netbox#15985]
### NetBox version

v4.0.0

### Feature type

Change to existing functionality

### Proposed functionality

Currently VLAN can be linked to interfaces (tagged and untagged).
My proposal is the ability to link VLANs to devices.

### Use case

Not all vlans that are on an interface are actual vlans on the device. If you have a routed port with subinterfaces, then the vlan on the subinterface is never in the layer2 of the device.

Being able to link the vlans to a devices, tells me what VLANs I have to configure in the vlan database.

Another option would be a 'flag' or interfacetype that would tell that the vlan is not part of the layer2domain of the switch

The goals is the ability to generate VLAN configurations from the dcim, without over-creating vlans (like from the routed subinterface)

**Comment by jeremystretch** [comment]
I believe this would be covered by #14451.
