### ISSUE TITLE
'group' required on create API call in tenant

### ISSUE THREAD

**Issue by rodvand** [netbox-community/netbox#15995]
### Deployment Type

Self-hosted

### NetBox Version

v4.0.0

### Python Version

3.10

### Steps to Reproduce

1. Try to create a tenant with only a name and a slug (which works through the GUI)
```
curl -s -X POST \
-H "Authorization: Token 0123456789abcdef0123456789abcdef01234567" \
-H "Content-Type: application/json" \
http://localhost:32768/api/tenancy/tenants/ \
--data '{"name": "Tenant 2", "slug": "tenant-2"}' | jq '.'
```

### Expected Behavior

Tenant to be created

### Observed Behavior

```
{
  "group": [
    "This field is required."
  ]
}
```

**Comment by jeremystretch** [comment]
I'm not able to reproduce this on v4.0.0:

```
$ curl -X POST \
-H "Authorization: Token $TOKEN" \
-H "Content-Type: application/json" \
-H "Accept: application/json; indent=4" \
http://netbox:8000/api/tenancy/tenants/ \
--data '{"name": "My Tenant 1", "slug": "my-tenant-1"}'
{
    "id": 14,
    "url": "http://netbox:8000/api/tenancy/tenants/14/",
    "display": "My Tenant 1",
    "name": "My Tenant 1",
    "slug": "my-tenant-1",
    "group": null,
    "description": "",
    "comments": "",
    "tags": [],
    "custom_fields": {
        "cust_id": null
    },
    "created": "2024-05-07T13:14:00.997561Z",
    "last_updated": "2024-05-07T13:14:00.997578Z"
}
```

I can't think of anything that would cause this. Do you have any custom validation rules enabled for tenants by chance?

**Comment by rodvand** [comment]
This is a fresh install (netbox-docker) and I'm just trying to populate it with some data. I get the same error by using the Swagger interface, as well as trying against demo.netbox.dev:
```
curl -X POST \
-H "Authorization: Token TOKEN" \
-H "Content-Type: application/json" \
-H "Accept: application/json; indent=4" \
https://demo.netbox.dev/api/tenancy/tenants/ \
--data '{"name": "My Tenant 1", "slug": "my-tenant-1"}'
{
    "group": [
        "This field is required."
    ]
}
```

**Comment by rodvand** [comment]
Could it maybe be fixed with something like this https://github.com/netbox-community/netbox/commit/bfc1cab6dfe620d6d0615158b4730fb5af7ede19 ?

**Comment by jeremystretch** [comment]
Ok, turns out I was mistakenly running and older version of DRF (from working on another bug) when I attempted to reproduce it. Can confirm this is a bug. Funny that it works fine under DRF 3.14.

**Comment by jeremystretch** [comment]
> Could it maybe be fixed with something like this https://github.com/netbox-community/netbox/commit/bfc1cab6dfe620d6d0615158b4730fb5af7ede19 ?

Adding `default=None` _does_ seem to fix the issue, but we need to identify the root cause. There are plenty of similar foreign key fields defined that work as expected without explicitly declaring a null default value. I suspect it might be related to the uniqueness constraint on the Tenant model; we've run into similar problems in the past.

**Comment by jeremystretch** [comment]
In case it was not obvious, a workaround for this is to include `"group": null` in the request when creating a new tenant.

**Comment by jeremystretch** [comment]
Confirmed that it's the uniqueness constraints on the Tenant model causing this. It's probably related to [this change](https://github.com/encode/django-rest-framework/pull/7438) in DRF v3.15.

**Comment by jeremystretch** [comment]
I've identified the same issue affecting the following model fields:

- CircuitTermination `provider_account`
- ProviderAccount `name`
- VirtualDeviceContext `identifier`
- Location `parent`
- Tenant `group` (this issue)
