### ISSUE TITLE
French login prompt overflows on lines

### ISSUE THREAD

**Issue by altf4arnold** [netbox-community/netbox#15999]
### Deployment Type

Self-hosted

### NetBox Version

v4.0.0

### Python Version

3.11

### Steps to Reproduce

go to login prompt when your browser is in french.

### Expected Behavior

the name "nom d'utilisateur" sould not end up with single words on same line

### Observed Behavior

<img width="459" alt="Screenshot 2024-05-07 at 14 53 12" src="https://github.com/netbox-community/netbox/assets/23227801/3ec0832d-5c67-440c-93b2-4a9228562604">

**Comment by jeremystretch** [comment]
We can address this by moving the field labels above the fields as per the Tabler example:

![screenshot](https://github.com/netbox-community/netbox/assets/13487278/28d4a466-3a88-4a5b-8b8f-f35dddd50edb)

**Comment by altf4arnold** [comment]
I can take a look to fix that. Do you want me to work on a PR for it?

**Comment by jeremystretch** [comment]
@altf4arnold sure, go for it!

**Comment by altf4arnold** [comment]
There we go
