### ISSUE TITLE
Netbox 4 cannot bulk delete IP addresses when using google chrome

### ISSUE THREAD

**Issue by falz** [netbox-community/netbox#15991]
### Deployment Type

Self-hosted

### NetBox Version

v4.0.0

### Python Version

3.10

### Steps to Reproduce

Cannot bulk delte IP addresses, clicking the confirmation button does nothing. 'network' inspect says 404. 

Testing on demo site. with IP's created under this prefix: https://demo.netbox.dev/ipam/prefixes/7/ip-addresses/

Using google chrome   "Version 124.0.6367.118 on Linux". flushed cache, tried in private browser as well. 

Firefox works fine.

1) navigate to a prefix
2) create a few ip addresses
3) select the IP's -> delete selected butt
4) you will be at the "bulk delete confirmation page"
5) clicking "delete 2 ip addresse" button does nothing

![image](https://github.com/netbox-community/netbox/assets/707319/85bd6115-92f0-42cc-a13c-1b1690a72a6c)

inspect -> network in browser shows a 404:
![image](https://github.com/netbox-community/netbox/assets/707319/63328960-e330-4d65-93b3-9eef4ce6f0bf)

### Expected Behavior

deleting works

### Observed Behavior

button press does nothing in google chrome

**Comment by DanSheps** [comment]
Thank you for opening a bug report. I was unable to reproduce the reported behavior on NetBox v4.0.0. Please re-confirm the reported behavior on the current stable release and adjust your post above as necessary. Remember to provide detailed steps that someone else can follow using a clean installation of NetBox to reproduce the issue. Remember to include the steps taken to create any initial objects or other data.

**Comment by falz** [comment]
I just re-tried on demo site today (re-created IP addresses) and it's now working. feel free to close, maybe it was an issue with the demo site?

**Comment by DanSheps** [comment]
Thanks for the update!

It is possible it was an issue with the demo site or something unrelated
