### ISSUE TITLE
Make a printer friendly layout of all racks for auditing.

### ISSUE THREAD

**Issue by RyanMonkey** [netbox-community/netbox#160]
I think it would be amazing to have a nice printout of the rack plans. Mainly for auditing (And keeping the bosses happy)

Something like, 4 racks to a page, with U Numbers, server names etc.

Thanks!

**Comment by bellwood** [comment]
I would suggest a rack per-page for readability and to give room for notes or anything else - especially if you are printing to A4

**Comment by bellwood** [comment]
@RyanMonkey just a follow up - would this be something you'd like at the rack group level or site level or installation level, etc.

**Comment by RyanMonkey** [comment]
@bellwood I think a site level and individual rack level would be great!

**Comment by jscobbie73** [comment]
Any update on this request?  Certainly something I am looking forward to as well.

**Comment by harsh-kotak** [comment]
Any update or timeline on this request? The lack of a feature to export/print Rack elevations is making us maintain additional spreadsheets to send out to lab technicians. The print view could be at rack group level with Name and Device Type displayed in elevations.

**Comment by DanSheps** [comment]
I would love a feature like this.  Here are the two parts I would love to see:

1. Printer Friendly export of layout from the Rack Page (Single Rack, Front and Back)
2. Printer Friendly export of layout from the Rack Group Page (Multiple Racks, 2-4 per page, Front or Back only, Configurable)
3. Printer Friendly export of layout from the Site Page (Multiple Racks, 2-4 per page, Front or Back only, Configurable)

I might actually give this a wack if Jeremy doesn't mind.  I have never coded Python but I imagine a view is rather easy.

**Comment by jeremystretch** [comment]
Blocked by #2248

**Comment by jameswhite4684** [comment]
A printer friendly view would be great, like excluding search bar and navigation links.

**Comment by em-winterschon** [comment]
Exporting rack elevation data to CSV would be very useful, in addition to the printing support already mentioned. There's a CSV export function for rack list, but not for elevation data (serial numbers, hostname, location, etc).

**Comment by jameswhite4684** [comment]
Rack Elevations / Group View view printing displays scrollbar and white space where search bar would be, thus distorting the print job.

[Rack.Elevations.-.NetBox.pdf](https://github.com/digitalocean/netbox/files/3262945/Rack.Elevations.-.NetBox.pdf)

**Comment by rbenigno** [comment]
Looks like the blockers for this have been closed?

**Comment by jeremystretch** [comment]
Looking for volunteers to take on this work. It should be fairly straightforward given that rack elevations are now rendered as SVG images.
