### ISSUE TITLE
Cached `setmode.js` is retained across upgrades, breaking dark mode support temporarily

### ISSUE THREAD

**Issue by JohannesKreuzer** [netbox-community/netbox#16003]
### Deployment Type

Self-hosted

### NetBox Version

v4.0.0

### Python Version

3.11

### Steps to Reproduce

 enable dark mode on a page. then navigate to another page.

### Expected Behavior

Dark mode stays enabled.

### Observed Behavior

Dark mode is automatically disabled and page is shown in bright mode again

**Comment by JohannesKreuzer** [comment]
A clearing of the browser cache resolved the issue.

Remaining issue is that the setmode.js is not postpended by the version as query param and so it is cached across netbox upgrades.

**Comment by arthanson** [comment]
@JohannesKreuzer can you please edit this bug report (title, reproduce steps) for the setmode.js issue as the current description / title is resolved.

**Comment by jeremystretch** [comment]
@arthanson I just updated the title. Will knock this out in a minute.
