### ISSUE TITLE
Add additional `save / create / cancel` buttons to top of forms (or make existing buttons stay visible)

### ISSUE THREAD

**Issue by ITJamie** [netbox-community/netbox#16009]
### NetBox version

v4.0.0

### Feature type

New functionality

### Proposed functionality

Add `save / create / cancel` buttons to top of forms (or make existing buttons stay visible )

### Use case

when a model has a lot of fields/custom fields (or is being used on a small display) there can be a lot of scrolling to get to the save / create buttons. 
it would be great if there was a copy of those buttons at the top of the form or if the existing buttons were always visible on the form

### Database changes

N/A

### External dependencies

N/A

**Comment by jeremystretch** [comment]
There was some discussion around this idea way back in #2237. Unfortunately it never found an owner.

**Comment by ITJamie** [comment]
What would be deemed acceptable? 
- An extra set of buttons at the top of the form
- Some kind of "fixed" bar with the action buttons

If it was just an extra set of buttons at the top I could likely take a stab at it.

**Comment by jeremystretch** [comment]
IMO a single set of fixed/floating buttons would be ideal. Rendering multiple buttons that do the same thing can be confusing and error-prone.

**Comment by paynl-wesley** [comment]
> What would be deemed acceptable?
> 
> * An extra set of buttons at the top of the form
> * Some kind of "fixed" bar with the action buttons
> 
> If it was just an extra set of buttons at the top I could likely take a stab at it.

IMHO a fixed bar with the action buttons on the bottom would be awesome!

**Comment by atownson** [comment]
Any thoughts on this approach?

Added this CSS to the buttons div:
```
position: sticky;
bottom: 0px;
padding: 2px 0px 10px 0px;
z-index: 1;
background-color: var(--tblr-bg-surface-tertiary)
```
Result:

https://github.com/user-attachments/assets/4e230529-82ab-4641-a677-e3399af5c637

**Comment by paynl-wesley** [comment]
Awesome!

**Comment by jeremystretch** [comment]
Thanks @atownson I've assigned this to you for a PR.
