### ISSUE TITLE
Django 5.0.5 yanked

### ISSUE THREAD

**Issue by ljarasius** [netbox-community/netbox#16017]
### Deployment Type

Self-hosted

### NetBox Version

v4.0.0

### Python Version

3.10

### Steps to Reproduce

https://github.com/netbox-community/netbox/blob/a9a012daf02d5ddfe043b6643cde0c99447202aa/requirements.txt#L1

https://pypi.org/project/Django/5.0.5/
> Reason this release was yanked:
>
> Release files have Windows end-of-line characters and are missing executable bits.

### Expected Behavior

No installation warning

### Observed Behavior

> WARNING: The candidate selected for download or install is a yanked version: 'django' candidate (version 5.0.5 at https://files.pythonhosted.org/packages/60/5d/d829755fee56176e0cdb4aa0fa9bf09e4ee687d3ef508f43e64ed9ab9712/Django-5.0.5-py3-none-any.whl (from https://pypi.org/simple/django/) (requires-python:>=3.10))
Reason for being yanked: Release files have Windows end-of-line characters and are missing executable bits.

**Comment by ljarasius** [comment]
Bug probably isn't the right classification, however I didn't feel that any other option (apart from codebase, which was marked as developer only) was the right fit.

**Comment by jeremystretch** [comment]
Huh, well that's a first for me. Thanks for the heads up.
