### ISSUE TITLE
docs: uWSGI typo

### ISSUE THREAD

**Issue by llamafilm** [netbox-community/netbox#16016]
### Deployment Type

NetBox Enterprise

### NetBox Version

v4.0.0

### Python Version

3.11

### Steps to Reproduce

https://docs.netbox.dev/en/stable/installation/4b-uwsgi/

There is a typo on this page

### Expected Behavior

pyuwsgi

### Observed Behavior

pyuwgsi

**Comment by jeremystretch** [comment]
Please remember to use the [documentation change](https://github.com/netbox-community/netbox/issues/new?assignees=&labels=type%3A+documentation%2Cstatus%3A+needs+triage&projects=&template=documentation_change.yaml) issue template for changes to the documentation.

**Comment by llamafilm** [comment]
Ah, sorry I didn’t notice that
