### ISSUE TITLE
Show python version in system status

### ISSUE THREAD

**Issue by JohannesKreuzer** [netbox-community/netbox#16020]
### NetBox version

v4.0.0

### Feature type

Change to existing functionality

### Proposed functionality

Add python version to system status view, addionally to netbox & django version.

### Use case

Determin the running python version

### Database changes

N/A

### External dependencies

No

**Comment by jeremystretch** [comment]
The Python version was [meant to be included](https://github.com/netbox-community/netbox/blob/b87d1eca98142b1850f9a291ca35351a89f1152f/netbox/core/views.py#L544) but it was erroneously omitted from the HTML template.
