### ISSUE TITLE
Disable uWSGI logging by default

### ISSUE THREAD

**Issue by markkuleinio** [netbox-community/netbox#16034]
### NetBox version

v4.0.0

### Feature type

Change to existing functionality

### Proposed functionality

Currently the NetBox-default uWSGI configuration causes all requests to be logged in uWSGI level, in addition to the normal reverse proxy level, thus consuming the journal log in systemd configuration.

I propose defaulting to uWSGI request logging disabled, while still logging application errors.

### Use case

Current uWSGI request logging consumes the systemd journal log capacity, possibly causing other application logs to purge when journal log limits are exceeded.

Since the default NetBox installation already logs the requests in the reverse proxy logs, uWSGI-level logging can be limited to error logging only.

If someone needs the uWSGI logging as well, they can easily change the configuration setting present in the default NetBox `uwsgi.ini`.

### Database changes

None

### External dependencies

None

**Comment by markkuleinio** [comment]
If this is accepted, I can submit the PR.

**Comment by jeremystretch** [comment]
@markkuleinio sounds reasonable. I've assigned this to you. (Also reclassified this as a documentation change as the reference uWSGI config isn't part of the NetBox code base.)

**Comment by markkuleinio** [comment]
Thanks. I was going to add the config lines to the end of `uwsgi.ini`, but I already have https://github.com/netbox-community/netbox/pull/16035 touching the same position, so I'll hold this for now.
