### ISSUE TITLE
uWSGI install docs don't lead to a working setup

### ISSUE THREAD

**Issue by markkuleinio** [netbox-community/netbox#16032]
### Deployment Type

Self-hosted

### NetBox Version

v4.0.0

### Python Version

3.11

### Steps to Reproduce

1. Use the install documentation https://docs.netbox.dev/en/stable/installation/4b-uwsgi/ to configure NetBox with uWSGI
2. Start `netbox` service

### Expected Behavior

`netbox` service is started

### Observed Behavior

```
May 08 16:06:17 netbox-lab systemd[1]: Started netbox.service - NetBox WSGI Service.
May 08 16:06:17 netbox-lab uwsgi[568130]: [uWSGI] getting INI configuration from /opt/netbox/uwsgi.ini
May 08 16:06:17 netbox-lab uwsgi[568130]: *** Starting uWSGI 2.0.23 (64bit) on [Wed May  8 16:06:17 2024] ***
...
May 08 16:06:17 netbox-lab uwsgi[568130]: current working directory: /opt/netbox
...
May 08 16:06:17 netbox-lab uwsgi[568130]: *** no app loaded. GAME OVER ***
May 08 16:06:17 netbox-lab systemd[1]: netbox.service: Main process exited, code=exited, status=22/n/a
```

= it cannot find `/opt/netbox/netbox/netbox/wsgi.py` file.

Workaround: add these in `uwsgi.ini`:

```
chdir = netbox
wsgi-file = netbox/wsgi.py
# or, instead of wsgi-file:
module = netbox.wsgi:application
```

**Comment by markkuleinio** [comment]
I'm willing to submit PR for that fix

**Comment by julianstolp** [comment]
Can confirm this issue, see: https://github.com/netbox-community/netbox/discussions/16030

**Comment by jeremystretch** [comment]
Thanks @markkuleinio, I've assigned this to you.
