### ISSUE TITLE
Scheduled jobs; Hundreds of duplicate jobs scheduled somehow overnight

### ISSUE THREAD

**Issue by bitcollector1** [netbox-community/netbox#16042]
### Deployment Type

Self-hosted

### NetBox Version

v4.0.0

### Python Version

3.12

### Steps to Reproduce

Schedule a job and wait until the next day and all of a sudden I have hundreds (880) of the same jobs scheduled and tons of script failures! 

<img width="1317" alt="Screenshot 2024-05-08 at 07 39 36" src="https://github.com/netbox-community/netbox/assets/50723251/5d875653-9f95-4d49-8a3c-f775a0517856">

<img width="197" alt="Screenshot 2024-05-08 at 07 39 58" src="https://github.com/netbox-community/netbox/assets/50723251/95fe0f12-2a8d-4b23-bf72-47645528c3c5">

### Expected Behavior

Script runs as scheduled under NetBox 3.7.x 

### Observed Behavior

Duplicate jobs scheduled resulting in failure of the scripts to complete. This seems to be a loop now, every time I delete the scheduled jobs they come right back :( 

<img width="1302" alt="Screenshot 2024-05-08 at 07 49 17" src="https://github.com/netbox-community/netbox/assets/50723251/bad0e2c4-2d43-4002-86fd-5701cdc9c647">

**Comment by bitcollector1** [comment]
I just deleted all scheduled jobs a few min ago and already these are all back! 

<img width="1325" alt="Screenshot 2024-05-08 at 07 50 36" src="https://github.com/netbox-community/netbox/assets/50723251/28f6fcd7-d68c-4940-9704-9399276f94b6">

Everything was working fine last night, woke up this morning to this issue and I can't seem to make it stop :(

**Comment by bitcollector1** [comment]
had to remove the scripts and restart netbox to make the madness stop!  The scripts just kept rescheduling themselves and running over and over no matter how many times I deleted them!

**Comment by bitcollector1** [comment]
Not sure if this is related to the timezone bug that I also submitted but the issue did not seem to present itself until I woke up this morning; before that the scheduled jobs would run once every 15 min as desired. I've been using these scripts for months without any issues.

**Comment by bitcollector1** [comment]
I just added the script back and rescheduled the job for every 15 min. I will monitor and report back if/when it goes off the rails.

**Comment by arthanson** [comment]
Timezone issue is #15984

**Comment by bitcollector1** [comment]
Script just completed first iteration successfully but now a second instance has been scheduled. 

<img width="1330" alt="Screenshot 2024-05-08 at 08 32 11" src="https://github.com/netbox-community/netbox/assets/50723251/9a02143a-a0a7-402f-8758-2b3701ca4245">

**Comment by bitcollector1** [comment]
FYI, I do have multiple workers defined in my setup.....not sure if this is coming into play here.....but the multiple workers were also setup under 3.7.x and working well.

**Comment by bitcollector1** [comment]
Thinking back......I believe I updated this setting from False to True yesterday afternoon while troubleshooting timezone stuff. I'm going to try setting it back to False. 

# Localization
ENABLE_LOCALIZATION = True

**Comment by bitcollector1** [comment]
Looks to me like the root cause to all of this is related to the timezone stuff. I will see how this job goes the rest of the day and will update if it goes off the rails again :)

**Comment by bitcollector1** [comment]
Scheduled jobs are working as expected since I changed the Localization setting to False. 

![Uploading Screenshot 2024-05-08 at 10.24.03.png…]()

**Comment by jeremystretch** [comment]
I'm not sure what's going on here. The `ENABLE_LOCALIZATION` config parameter was [removed](https://github.com/netbox-community/netbox/issues/15752) in v4.0, so setting/changing it should not have any effect.

**Comment by bitcollector1** [comment]
hmmmm.....I'm not sure myself :( 

let me try to enable it again and see if I can recreate again.

**Comment by bitcollector1** [comment]
Looks like this may have been the issue all along.....sorry for wasting your time on this.

**Comment by jeremystretch** [comment]
Huh, that's really strange. Even having multiple workers should result in an issue like this. Well, glad you got it sorted. And thanks for following up with the resolution!

**Comment by bitcollector1** [comment]
Hopefully the issue does not pop up again. I will let you folks know if I bump into it again.

**Comment by DanSheps** [comment]
FYI, the backup plugin uses multiple rq workers heavily and this shouldn't normally result in multiple jobs firing off.  There must be something else with the way those workers are configured that is causing issues.

Perhaps it is related to localization as far as start time and workers aren't properly starting "on-time" (to early or to late)

**Comment by bitcollector1** [comment]
Happy to say this issue seems to be a one off related to the migration and the multiple workers. I'm really not sure but I do appreciate you folks offering insights. Thanks again for supporting an amazing product and sorry to add to your burden. 

Cheers!
