### ISSUE TITLE
Add workaround to make reloads work with `pyuwsgi`

### ISSUE THREAD

**Issue by markkuleinio** [netbox-community/netbox#16056]
### Change Type

Addition

### Area

Installation/upgrade

### Proposed Changes

As discussed in https://github.com/netbox-community/netbox/issues/16043, when using `pyuwsgi` package (as used in the current NetBox instructions) there is a problem where uWSGI detects the Python binary incorrectly, and consequently uWSGI reloads won't work.

Other references:
- https://github.com/unbit/uwsgi/issues/2478
- https://github.com/lincolnloop/pyuwsgi-wheels/issues/23

I'm proposing adding the identified workaround in the NetBox-provided `uwsgi.ini`:

```
; workaround to make uWSGI reloads work with pyuwsgi (not to be used if using uwsgi package instead)
binary-path = venv/bin/python
```

**Comment by markkuleinio** [comment]
If this is accepted, I can send the PR.

**Comment by jeffgdotorg** [comment]
LGTM. Thanks @markkuleinio.
