### ISSUE TITLE
Bulk Create tab not showing when creating IP Addresses

### ISSUE THREAD

**Issue by Ben0it** [netbox-community/netbox#16054]
### Deployment Type

Self-hosted

### NetBox Version

v4.0.0

### Python Version

3.11

### Steps to Reproduce

1. Click on **IPAM**.
2. Click on **IP Addresses**.
3. Click on **+ Add** button.
4. Tab **Bulk Create** does not appear on the right of tab **Create** :
![image](https://github.com/netbox-community/netbox/assets/25719453/53f90250-c418-4242-998a-1eaed70f3865)

### Expected Behavior

Tab **Bulk Create** should appear on the right of **Create** tab.

### Observed Behavior

Tab **Bulk Create** is not displayed on the User Interface.

Additional information : 

- When replacing **add** by **bulk-add** in the URL, the **Bulk Create** tab & form both appear and are functional :
![image](https://github.com/netbox-community/netbox/assets/25719453/cf10752e-91cd-470f-b73d-457cdc0fa69c)

 - When clicking on **Create** tab, **Bulk Create** tab disappears again.

**Comment by jeremystretch** [comment]
I believe this was addressed under #15982 and will be fixed in the upcoming v4.0.1 release.
