### ISSUE TITLE
 The empty_text in BaseTable is not translatable because it does not utilize gettext_lazy

### ISSUE THREAD

**Issue by grncbg** [netbox-community/netbox#16051]
### Deployment Type

Self-hosted

### NetBox Version

v4.0.0

### Python Version

3.10

### Steps to Reproduce

The empty_text in BaseTable is not translatable because it does not utilize gettext_lazy.
https://github.com/netbox-community/netbox/blob/0cc2963e6f9b4f5c644201099fa9b204044653e2/netbox/netbox/tables/tables.py#L54-L55

English
![English](https://github.com/netbox-community/netbox/assets/20819471/3d6e9604-b501-4135-ae51-174721f7ea14)

Japanese
![Japanese](https://github.com/netbox-community/netbox/assets/20819471/4d80cb07-7f7c-4805-b74a-3ab579445333)

### Expected Behavior

empty_text can be translated

### Observed Behavior

empty_text cannot be translated

**Comment by abhi1693** [comment]
@grncbg I have assigned the bug to you since you already have a fix.

**Comment by jeremystretch** [comment]
Please remember to assign a severity when triaging bug reports.
