### ISSUE TITLE
Clean up obsolete mentions of graphene in official docs

### ISSUE THREAD

**Issue by jeffgdotorg** [netbox-community/netbox#16059]
### Change Type

Correction

### Area

Development

### Proposed Changes

While triaging #16024 I noticed that the docs still refer to graphene in a few places where strawberry should be. The needed updates span several doc areas; I picked _Development_ because it came up first alphabetically. I think this list captures all the files that need touching:

- `development/adding-models.md`
- `integrations/graphql-api.md`
- `plugins/development/graphql-api.md`

**Comment by arthanson** [comment]
@jeffgdotorg can you please check the latest docs, I think these were all cleaned up in a previous PR.  Searching the codebase for graphene shows nothing except in release notes and such.

**Comment by jeffgdotorg** [comment]
I had `feature` checked out when I made the list above. If that's expected at this stage, then this issue is moot.

**Comment by jeffgdotorg** [comment]
Disregard, I had the wrong branch checked out.
