### ISSUE TITLE
Interfaces - Multi-Personality/Shared Interface

### ISSUE THREAD

**Issue by retrogamer999** [netbox-community/netbox#16057]
### NetBox version

v4.0.0

### Feature type

New functionality

### Proposed functionality

Going through the list of interfaces that are available there is no reference for interfaces that have multiple personalities i.e. Port 17-20 on a FortiGate 100F has SFP or Copper compatibility

### Use case

More accurate documentation

### Database changes

unknown

### External dependencies

unknown

**Comment by a084ed22** [comment]
dual-personality interfaces have been a topic discussed before. As far as I remember, the solutions offered were to either manually change the interface type depending on your needs, or to populate both i.e. in device templates, and let people pick the correct one as needed, differentiating between them with a suffix.

**Comment by sleepinggenius2** [comment]
We've been experimenting with modeling dual-mode ports like this (1/1/1 in this example):

Logical:
* 1/1/1 - Type Bridge

Physical:
* 1/1/1|Copper - Type 1000BASE-T (1GE), Bridged interface 1/1/1
* 1/1/1|SFP - Type SFP (1GE), Bridged interface 1/1/1

**Comment by jeremystretch** [comment]
This issue is being closed as no further information has been provided. If you would like to revisit this topic, please first modify your original post to include all the requested detail, and then ask that the issue be reopened.
