### ISSUE TITLE
Custom field's default value not respected when using bulk import CSV

### ISSUE THREAD

**Issue by diondohmen** [netbox-community/netbox#16073]
### Deployment Type

Self-hosted

### NetBox Version

v4.0.1

### Python Version

3.12

### Steps to Reproduce

P.S.
Tested this also with the current public demo instance of Netbox giving the same result.

1. Add a new custom field with the following specs:
- Object-type: DCIM > Device
- Name: '_test_default_'
- Type: _**Boolean**_ 
- Required: **False**
- Default: true 

![afbeelding](https://github.com/netbox-community/netbox/assets/60485478/d1f5c01b-183d-4047-a5d4-29f0fbccfe81)

![afbeelding](https://github.com/netbox-community/netbox/assets/60485478/b2a481f6-bb78-453a-8fde-c4aa1881660d)

3. Use 'Device Bulk Import' feature together with the following CSV file.
   The CSV doesn't mention the **cf_test_default** column/value so you would expect Netbox to enter the default value

[public_dev_netbox_devices_import_ttt.csv](https://github.com/netbox-community/netbox/files/15271733/public_dev_netbox_devices_import_ttt.csv)

![afbeelding](https://github.com/netbox-community/netbox/assets/60485478/75a3a11c-6221-441a-895f-a4644292f7d6)

5. After submitting you can see the device has been added but the custom field '_test_default_' is empty.
![afbeelding](https://github.com/netbox-community/netbox/assets/60485478/66052d7c-50aa-4ae5-8d98-cf1ce5c112c4)

### Expected Behavior

The custom field's value should be 'True' like in the following screen:
![afbeelding](https://github.com/netbox-community/netbox/assets/60485478/3241ef57-73bf-4b7c-b809-485ca86ae104)

### Observed Behavior

The custom field's value is empty/null using the Device Bulk Import.
When adding a device manually, the dropdown box is pre-filled with the correct default value of True

**Comment by arthanson** [comment]
@abhi1693 are you still planning to work on this?

**Comment by abhi1693** [comment]
Sorry, won't be able to work on this
