### ISSUE TITLE
Menu collapse behavior change (in 4.0 vs 3.7)

### ISSUE THREAD

**Issue by PieterL75** [netbox-community/netbox#16074]
### NetBox version

v4.0.1

### Feature type

Change to existing functionality

### Proposed functionality

In v3, the menu collapsed when another main menu item was selected.
in v4 all submenu's remain open
This causes a very inefficient UI experience.

### Use case

navigating the menu has become more click/scroll heavy.
As you mentioned in #15814, this change in behavior was done intentionally.

I would propose to either
- return the v3 behavior
- add a 'quicksearch' to the top of the navigation bar, so quickly look for submenu items and auto collapse/expand the menu's

**Comment by arthanson** [comment]
Closing as dupe of #15614

**Comment by PieterL75** [comment]
@arthanson I think you miss interpreted my request.
This is not about the menu bar siding left/right
But about the sub menu opening and closing. 

Can you please review my FR?

Pieter

**Comment by arthanson** [comment]
ah okay, that makes sense.

**Comment by rhcinos** [comment]
I like the idea of a search box.
Another option might be for a user preference to switch between tab collapse modes.

**Comment by jeremystretch** [comment]
I'm going to close this as redundant to #16392, which (despite being opened more recently) better captures the proposed change and work to be done.
