### ISSUE TITLE
Weird font style when doing name that contains "<number>x<number>"

### ISSUE THREAD

**Issue by Mailstorm-ctrl** [netbox-community/netbox#16083]
### Deployment Type

Self-hosted

### NetBox Version

v4.0.1

### Python Version

3.10

### Steps to Reproduce

1. Make a device (or anything really) and put something similar to 0x3 or 0x2 in the name.

### Expected Behavior

A normal looking x in the name

### Observed Behavior

A weird style of font on the x.
![image](https://github.com/netbox-community/netbox/assets/53045430/a9e5f15c-b200-400a-b49c-6f4d3f23a637)
![image](https://github.com/netbox-community/netbox/assets/53045430/79eaf56b-b6df-42c1-ac61-5da2c2d40120)

**Comment by bitcollector1** [comment]
I saw the same thing on my serial numbers now that you mention it, nice find.

**Comment by arthanson** [comment]
Looks like from the font-family, interpreting it as a hex code.  Didn't even realize that was a thing.  I'm not sure, but I think possibly the only way to change this is to change the font that is being used.

**Comment by sleepinggenius2** [comment]
What you're encountering is font ligatures. You have `font-feature-settings: "liga" 0;` under the body style in the stylesheet, but it looks like that isn't working as expected. If you also add `font-variant-ligatures: none;`, that seems to resolve the issue.

**Comment by DanSheps** [comment]
This piqued my interest.  Should be simple to solve but I kind of want to learn more about ligatures now.

**Comment by DanSheps** [comment]
So, did a little poking:

* Not ever font contains ligatures
* Chrome (possibly any Chromium, not sure) requires both `font-feature-settings: "liga" 0;` and `font-variant-ligatures: none;`
* `font-feature-settings: "liga" 0;` completely disables ligatures, so setting `font-variant-ligatures: none;` also shouldn't be a problem
* For future reference, `common-ligatures` includes things like `fi` () `ffi` `th`

To fix this, I am going to add the `font-variant-ligatures: none;` to the CSS.   `font-feature-settings: "liga" 0;`  does the same thing however Chrome requires both to be present for some reason.
