### ISSUE TITLE
Allow any hardware to accept any OEM software/firmware 'Platform'

### ISSUE THREAD

**Issue by systemcrash** [netbox-community/netbox#16097]
### NetBox version

v4.0.0

### Feature type

Data model extension

### Proposed functionality

I run openwrt on a number of OTS devices, e.g. TP-Link. But TP-Link devices implicitly expect a `Platform` produced by TP-Link. Can this be relaxed?

### Use case

Also have some HP PC, which run... MS windows.

**Comment by jeremystretch** [comment]
When assigning the platform for a device, NetBox will show as options all platforms that either a) are associated with the device type's manufacturer or b) have no manufacturer assignment. You can remove the manufacturer association of the platform you've defined to enable it as an option for all devices.
