### ISSUE TITLE
4.0.2 scripts can only be launched by api with ID and no longer with a name. 

### ISSUE THREAD

**Issue by MalfuncEddie** [netbox-community/netbox#16145]
### Deployment Type

Self-hosted

### NetBox Version

v4.0.2

### Python Version

3.10

### Steps to Reproduce

see #16123

In the past I could run the script with "https://netbox-test/api/extras/scripts/scriptA.class"
This does not work anymore and I need an ID ;(

Exception Value: | Field 'id' expected a number but got 'ProcessLogging'.

### Expected Behavior

it works lik in 3.7.7

### Observed Behavior

ValueError at /api/extras/scripts/ProcessLogging/

launching it with /api/extras/scripts/6/

Does work.

**Comment by jeffgdotorg** [comment]
Thanks for reporting a problem you've encountered in NetBox.

Although the OpenAPI schema does not indicate that scripts can be invoked by name, the [4.0.2 docs](https://github.com/netbox-community/netbox/blob/v4.0.2/docs/customization/custom-scripts.md#via-the-api) do provide an example in that style, so this feels like a regression against a documented behavior.

**Comment by MalfuncEddie** [comment]
Hi,

Most definitely a regression. Problem is that you cannot change the id so if you delete the script and add it again it gets a new id and then you have to change all your endpoints that use it.

**Comment by MalfuncEddie** [comment]
It works again! 
You might not hear this enough but thank you for this fix and this great project!
