### ISSUE TITLE
Global search by tag no longer working

### ISSUE THREAD

**Issue by BrunoBlanes** [netbox-community/netbox#16147]
### Deployment Type

Self-hosted

### NetBox Version

v4.0.2

### Python Version

3.12

### Steps to Reproduce

1. Search for a tag description in the global search box

### Expected Behavior

Expected the tags with the matching description to be returned in the results, as per #8629

### Observed Behavior

There are no tags in the results and no way to filter by them in "Object Types"

**Comment by BrunoBlanes** [comment]
A good option would be to have a tag field where I could select all tags who's objects I'd like to see.

![image](https://github.com/netbox-community/netbox/assets/28227097/5e7df996-180f-4b4f-9c57-801f62288fda)

**Comment by abhi1693** [comment]
I do not believe that tags were ever searchable using global search. I'll mark this under review but I feel like this is a feature request more than a bug

**Comment by BrunoBlanes** [comment]
I read through the old pull request that closed #8629 and indeed it seems that they were not included in the global search, so it makes sense to convert this into a feature request.

**Comment by jeremystretch** [comment]
Closing this as it's not a valid bug report. @BrunoBlanes please submit a new [feature request](https://github.com/netbox-community/netbox/issues/new?assignees=&labels=type%3A+feature%2Cstatus%3A+needs+triage&projects=&template=feature_request.yaml) if you would like to propose this functionality.
