### ISSUE TITLE
Missing "Run Script" button from Custom Scripts

### ISSUE THREAD

**Issue by kollross** [netbox-community/netbox#16153]
### Deployment Type

Self-hosted

### NetBox Version

v4.0.2

### Python Version

3.10

### Steps to Reproduce

1. Click on Customizations -> Scripts
2. Can view script in the list (has edit, and delete buttons)
3. No "Run Script option"

This script was working yesterday, I upgraded to 4.0.2 today and now that script is missing the button.    Other scripts still have the "Run Script" option.

### Expected Behavior

"Run Script" button be present and clickable. 

### Observed Behavior

emptyness

**Comment by arthanson** [comment]
@kollross  Thank you for opening a bug report. I was unable to reproduce the reported behavior on NetBox v4.0.2.  "that script is missing the button." I don't know what that script is - the existing scripts I have on my installation still have the Run Script button.  Can you please check what is different about the script then your other scripts, generally a run script button missing would indicate that there is an issue with the script code.

**Comment by bitcollector1** [comment]
man....I'm running into so many issues with these scripts I'm really regretting upgrading to 4.0. Feels like it was rushed for sure! Lesson learned not to be too eager to update!

**Comment by bitcollector1** [comment]
I believe I have the same issue. 

![Screenshot 2024-05-15 at 15 39 27](https://github.com/netbox-community/netbox/assets/50723251/003812db-b882-4eab-bfb5-d53ad64b86d3)

What is worse is there is no way to delete the script now
![Screenshot 2024-05-15 at 15 39 33](https://github.com/netbox-community/netbox/assets/50723251/82b5c62f-a513-4c50-b590-e9ee83fec545)

![Screenshot 2024-05-15 at 15 39 38](https://github.com/netbox-community/netbox/assets/50723251/56d0318f-1411-4b53-8977-baa5399769c5)

**Comment by bitcollector1** [comment]
Same issue, my script was working fine and then suddenly stopped working and when trying to delete the script and recreate I ended up in this situation :(

**Comment by bitcollector1** [comment]
Script was working fine as seen here 
```
14:26:25:  ebay@netdevbox:~$ curl -X POST "http://netdevbox.hwe.ebay.com/api/extras/scripts/23/" -H "accept: application/json; indent=4" -H "Authorization: Token 0ee9654cccaa1d17fabb2f689c3587262300163d" -H "Content-Type: application/json" --data '{"commit":true,"data":{"serial_num": "S375578X9830314D"}}'
14:26:26:  {
14:26:26:      "id": 23,
14:26:26:      "url": "http://netdevbox.hwe.ebay.com/api/extras/scripts/23/",
14:26:26:      "module": 404,
14:26:26:      "name": "CURL_NETBOX_REFRESH_TOOL",
14:26:26:      "description": "Updates ALL NetBox Info, Including NIC Details and Network Connection to Switch",
14:26:26:      "vars": {},
14:26:26:      "result": {
14:26:26:          "id": 47072,
14:26:26:          "url": "http://netdevbox.hwe.ebay.com/api/core/jobs/47072/",
14:26:26:          "display": "1baae519-c255-466d-b5b9-4df05dec2f0b",
14:26:26:          "object_type": "extras.script",
14:26:26:          "object_id": 23,
14:26:26:          "name": "CURL_NETBOX_REFRESH_TOOL",
14:26:26:          "status": {
14:26:26:              "value": "pending",
14:26:26:              "label": "Pending"
14:26:26:          },
14:26:26:          "created": "2024-05-15T14:26:26.419266-07:00",
14:26:26:          "scheduled": null,
14:26:26:          "interval": null,
14:26:26:          "started": null,
14:26:26:          "completed": null,
14:26:26:          "user": {
14:26:26:              "id": 5,
14:26:26:              "url": "http://netdevbox.hwe.ebay.com/api/users/users/5/",
14:26:26:              "display": "dnoland (Duane Noland)",
14:26:26:              "username": "dnoland"
14:26:26:          },
14:26:26:          "data": null,
14:26:26:          "error": "",
14:26:26:          "job_id": "1baae519-c255-466d-b5b9-4df05dec2f0b"
14:26:26:      },
14:26:26:      "display": "CURL_NETBOX_REFRESH_TOOL (netbox_curl_refresh)",
14:26:26:      "is_executable": true
```

Changed some permissions and ran again and the script failed
```
14:30:41:  ebay@netdevbox:/opt/netbox/netbox/scripts$ sudo chmod 777  netbox_curl_refresh.py
14:30:42:  ebay@netdevbox:/opt/netbox/netbox/scripts$ 
14:30:42:  ebay@netdevbox:/opt/netbox/netbox/scripts$ 
14:30:42:  ebay@netdevbox:/opt/netbox/netbox/scripts$ 
14:30:42:  ebay@netdevbox:/opt/netbox/netbox/scripts$ 
14:30:55:  ebay@netdevbox:/opt/netbox/netbox/scripts$ 
14:30:56:  ebay@netdevbox:/opt/netbox/netbox/scripts$ 
14:30:56:  ebay@netdevbox:/opt/netbox/netbox/scripts$ 
14:30:57:  ebay@netdevbox:/opt/netbox/netbox/scripts$ curl -X POST "http://netdevbox.hwe.ebay.com/api/extras/scripts/23/" -H "accept: application/json; indent=4" -H "Authorization: Token 0ee9654cccaa1d17fabb2f689c3587262300163d" -H "Content-Type: application/json" --data '{"commit":true,"data":{"serial_num": "S375578X9830314D"}}'
14:30:58:  {"error": "'NoneType' object has no attribute 'class_name'", "exception": "AttributeError", "netbox_version": "4.0.2", "python_version": "3.12.3"}ebay@netdevbox:/opt/netbox/netbox/scripts$ 

```

**Comment by bitcollector1** [comment]
more pain :( 

All I did is edit a script and now it can no longer be run :( 

![Screenshot 2024-05-15 at 15 39 38](https://github.com/netbox-community/netbox/assets/50723251/b01e2499-3240-4538-8114-60f9af4c5068)

**Comment by arthanson** [comment]
@bitcollector1 "What is worse is there is no way to delete the script now" please file a separate issue if you are running into this and can reproduce.

**Comment by arthanson** [comment]
Note: There is a PR #15441 that adds better script error reporting (to show errors in the script code) - I'm guessing (without a repo scenario) that the scripts without the run button has an error, that PR would make it easier to find.

**Comment by bitcollector1** [comment]
just added a new script and have same issue, no button to run it. This seems to be a new issue related to 4.0.2?   

![Screenshot 2024-05-15 at 16 02 16](https://github.com/netbox-community/netbox/assets/50723251/9788d95e-87ee-4883-814d-e74aeddc2c24)

**Comment by bitcollector1** [comment]
I was able to delete my script that had issues but going into the shell and deleting the event rule that was causing the issue 
```
>>> EventRule.objects.all()
<RestrictedQuerySet [<EventRule: IP Updated>]>

>>> EventRule.objects.all().delete()
(2, {'extras.EventRule_object_types': 1, 'extras.EventRule': 1})
>>> 
>>> EventRule.objects.all().delete()
(0, {})
```

**Comment by bitcollector1** [comment]
I can see my script now, it was in fact related to an error in the code that was preventing it from loading correctly.

**Comment by kollross** [comment]
During the upgrade to 4.0.2 one of the required pip modules wasn't installed.  But because I couldn't run the script from the GUI, there was no viable output to tell me it had a missing module.  Deleting the script, and re-adding it produced a buttonless section of the script.   Tailing the logs when deleting and re-adding the script also produced no errors.   The only way I was able to troubleshoot to was to drop into /opt/netbox/venv/bin/python and running the script line by line to see where the erroring out. 

Thank goodness for "https://github.com/netbox-community/netbox/discussions/12813" otherwise this sort of thing would also impossible to troubleshoot.
