### ISSUE TITLE
Displayed ID instead of name when None is selected on the Filters.

### ISSUE THREAD

**Issue by Julio-Oliveira-Encora** [netbox-community/netbox#16164]
### Deployment Type

Self-hosted

### NetBox Version

v4.0.3-dev

### Python Version

3.12

### Steps to Reproduce

1. Go to Devices;
2. Go to Filters;
3. In  "Tenant ID"  select None and another option
4. Click on Search

### Expected Behavior

The Results page should display "None" and the name of the Tenant selected in the "Steps to Reproduce".

### Observed Behavior

The Result page displays "None" and the ID of the Tenant selected in the "Steps to Reproduce".
![None](https://github.com/netbox-community/netbox/assets/149191228/c0c5e0f4-433a-450c-8af2-855df8ec2b36)

**Comment by Julio-Oliveira-Encora** [comment]
Could you please assign it to me?

**Comment by jeffgdotorg** [comment]
Thanks, Julio.
