### ISSUE TITLE
Logical MUX ability in switches

### ISSUE THREAD

**Issue by TheWidowLicker** [netbox-community/netbox#16175]
### NetBox version

v4.0.2

### Feature type

New functionality

### Proposed functionality

Allow logical MUX and replication group options in switches.

### Use case

On Arista 7130L and 7130LB switches (as well as other switches), you can have multiple interfaces be the ingress (RX) of a MUX group and a single interface be the egress (TX) of the same MUX group. This is good if you want to have multiple hosts sending onto the same line.
In reverse of this you can have 1 port be the ingress (RX) from a line and then have it send to the egress (TX) on multiple ports so that a line can be replicated to multiple hosts.

### Database changes

None that I know of

### External dependencies

None that I know of

**Comment by jeremystretch** [comment]
Thank you for your interest in extending NetBox. Unfortunately, the information you have provided does not constitute an actionable feature request. Per our [contributing guide](https://github.com/netbox-community/netbox/blob/develop/CONTRIBUTING.md), a feature request must include a thorough description of the proposed functionality, including any database changes, new views or API endpoints, and so on. It must also include a detailed use case justifying its implementation. If you would like to elaborate on your proposal, please modify your post above. If sufficient detail is not added, this issue will be closed.

**Comment by TheWidowLicker** [comment]
Updated now

**Comment by jeremystretch** [comment]
> Allow logical MUX and replication group options in switches.

This is not an actionable feature request. Please spend some time thinking through exactly what change(s) you're proposing and provide enough detail in your description above that they can be sufficiently considered and discussed. If you have not fully formed your proposed implementation yet, please try starting a [discussion](https://github.com/netbox-community/netbox/discussions/new/choose) instead.
