### ISSUE TITLE
Specify Which User Groups Can View And Use Specific Saved Filters

### ISSUE THREAD

**Issue by mr1716** [netbox-community/netbox#16205]
### NetBox version

v3.7.8

### Feature type

Change to existing functionality

### Proposed functionality

This would allow admins to specify which Groups can use specific Saved Filters. Currently, if I have 10 Saved Filters, I believe that if all users can view that object, they will all be able to view all 10 Saved Filters, even if they're not needed or applicable.

### Use case

The use case is that I have 2 teams using Netbox, and I have 10 filters. 4 specific to team A, 3 to team B, and 3 shared. Therefore, I would want team A to view 7 Saved Filters (1-4 and 7-10) and team B view 6 filters (5-10). Showing a more limited number of Saved Filters based on Group Permissions would provide an improved, faster, and decluttered Saved Filter experience.

**Comment by mr1716** [comment]
Edited the title to be clear. Didn’t realize that the title didn’t reflect the body of the request so updated it!! I know this would be a change, but think it would be helpful!

**Comment by mr1716** [comment]
@jeffgdotorg you are correct

**Comment by mr1716** [comment]
@jeffgdotorg my question and I think use case is: if 2 user groups have access to the same object that the Saved Filters are applied against, is there a way to limit which groups can view those Saved Filters?

for example, I want to limit the Group Users to only see the Saved Filter for Active DCIM Device Objects, but not Needs Refresh Saved Filter for DCIM Device Objects. But I want the Group Power Users to be able to view both Saved a filters.

**Comment by mr1716** [comment]
Hey, just wanted to see if this was something that is a feature request or something that can already be done?

**Comment by jeffgdotorg** [comment]
Maybe it's just because it's late in my workday, but I've gone a bit crosseyed parsing your comment of May 23. Would you please edit it for clarity, or follow it up with another clarifying comment?

**Comment by jeremystretch** [comment]
This issue is being closed as no further information has been provided. If you would like to revisit this topic, please first modify your original post to include all the requested detail, and then ask that the issue be reopened.
