### ISSUE TITLE
4.0.2 API Docs Page Not Found

### ISSUE THREAD

**Issue by tgoodsell-tempus** [netbox-community/netbox#16207]
### Deployment Type

Self-hosted

### NetBox Version

v4.0.2

### Python Version

3.11

### Steps to Reproduce

1. View documentation stating Interactive REST API Docs located at `/api/docs/`: https://demo.netbox.dev/static/docs/rest-api/overview/#interactive-documentation
2. Try to browse that location on a self hosted netbox instance while logged in as a super user.

### Expected Behavior

Viewing the expected Interactive Documentation page.

### Observed Behavior

Get a 404 - "The requested page does not exist" error.

**Comment by tgoodsell-tempus** [comment]
Based upon some references to it and my own use of the endpoint, maybe this is just a doc change to reference `/api/schema/swagger-ui/` instead? Provided what was referred to in the original document effectively means this swagger doc.

**Comment by arthanson** [comment]
@tgoodsell-tempus that could be something left over in static, what are you doing to navigate to that link?  Did you follow this link from an old install of NetBox?  The link for this should be at https://docs.netbox.dev/en/stable/integrations/rest-api/ which does work on both the demo and local install.

**Comment by arthanson** [comment]
@tgoodsell-tempus I'll close this issue and create a housekeeping issue to cleanup old links on the demo instance.  Thanks for alerting us to this.
