### ISSUE TITLE
Tunnel Terminations Server error

### ISSUE THREAD

**Issue by RenJiangZhou2163** [netbox-community/netbox#16214]
### Deployment Type

Self-hosted

### NetBox Version

4.0.2

### Python Version

3.11.6

### Steps to Reproduce

1、clicked on “Tunnel Terminations”,

### Expected Behavior

In normal cases, the /vpn/tunnel-terminations / page should be displayed

### Observed Behavior

Server Error
There was a problem with your request. Please contact an administrator.

The complete exception is provided below:

<class 'django.core.exceptions.FieldError'>

Field 'termination' does not generate an automatic reverse relation and therefore cannot be used for reverse querying. If it is a GenericForeignKey, consider adding a GenericRelation.

Python version: 3.11.6
NetBox version: 4.0.2
Plugins: None installed
If further assistance is required, please post to the [NetBox discussion forum](https://github.com/netbox-community/netbox/discussions) on GitHub.

**Comment by RenJiangZhou2163** [comment]
This problem was normal until I added some tunnels and deleted them
After the tunnel is deleted, the three VPN-related tables in the netbox database are empty and the same error is reported

**Comment by DanSheps** [comment]
> This problem was normal until I added some tunnels and deleted them After the tunnel is deleted, the three VPN-related tables in the netbox database are empty and the same error is reported

Are you saying this only is a problem if you delete the tunnel or interface?

**Comment by RenJiangZhou2163** [comment]
At the time of deployment, the page is normal
I added the device and added the GRE tunnel, and then removed the added device and tunnels. Then the problem occurred. I checked the database and found that the three VPN-related entries were empty. The database looks normal, because I have deleted the added data, but an error is reported on the  “Tunnel Terminationsl" page.

**Comment by jeremystretch** [comment]
@RenJiangZhou2163 in order for us to accept your bug report, you'll need to identify and detail steps that someone else can take on an unmodified NetBox instance to reproduce the reported problem. Without sufficient instructions to reproduce the bug, this issue will be closed.
