### ISSUE TITLE
Next Available IP Address missing

### ISSUE THREAD

**Issue by hendrikbl** [netbox-community/netbox#16215]
### Deployment Type

Self-hosted

### NetBox Version

v4.0.2

### Python Version

3.11

### Steps to Reproduce

I'm not sure if this is a bug or if this feature was removed intentionally. I used this feature a lot to find free addresses at a glance.

1. Create a prefix e.g. 10.24.0.0/16
2. Create a few but not all of this prefixes addresses
3. Open the IP Addresses tab of the prefix created in step 1

### Expected Behavior

In version 3.7 the available IP addresses were displayed as rows in the ip address table. They also allowed users to quickly add the next available ip address from this free range. I found a screenshot from the issue this was initially discussed  #1246

![image](https://github.com/netbox-community/netbox/assets/9558391/8be705ce-5e62-4cdc-946a-2016b276775e)

### Observed Behavior

The mentioned rows are missing and only the created addresses are displayed.

![image](https://github.com/netbox-community/netbox/assets/9558391/92a7343b-1e4f-4f13-9f03-195bfad5fa7e)

**Comment by ibuclaw** [comment]
@hendrikbl this bit me on 3.7 too a few months back. Next available IP is not shown when the contents are sorted (click that little red :x: in the second screenshot).

**Comment by abhi1693** [comment]
This is working as expected

![image](https://github.com/netbox-community/netbox/assets/5083532/3935f45e-258a-4013-ab91-e1b1d3e5117a)
