### ISSUE TITLE
Employ `pre-commit` for commit validation

### ISSUE THREAD

**Issue by jeremystretch** [netbox-community/netbox#16248]
### Proposed Changes

Replace our current [pre-commit hook script](https://github.com/netbox-community/netbox/blob/develop/scripts/git-hooks/pre-commit) with [`pre-commit`](https://pre-commit.com/).

### Justification

Obviates the need for a custom script while at the same time exposing more powerful validation features.

**Comment by ITJamie** [comment]
Im a heavy pre-commit user, i am happy to make a pr towards this
