### ISSUE TITLE
Multiple editing issue

### ISSUE THREAD

**Issue by xenonn97** [netbox-community/netbox#16258]
### Deployment Type

Self-hosted

### NetBox Version

v4.0.2

### Python Version

3.12

### Steps to Reproduce

1. Selecting multiple subnets
2. Pressing the edit button and changing the status of the subnets
3. Pressing the Apply button without anything happening

### Expected Behavior

As with the older versions, when pressing Apply, all the selected subnets were changed

### Observed Behavior

I can't do multiple editing on version 4.0.2, on the older version it works without problems

**Comment by jeffgdotorg** [comment]
Thanks for taking the time to report a problem you're having with NetBox.

To help the maintainer team efficiently triage your issue, please update your issue body to expand the **Steps to Reproduce** section. This section should assume that a fresh, empty install of NetBox is the starting point, and it needs to enumerate each object that needs to be created to set the scene for the problem to appear. We recognize this represents an additional ask of your time; please bear in mind that we get several new issues each week, and we are a small team.
