### ISSUE TITLE
Allow alphabetical ordering of bookmarks on dashboard

### ISSUE THREAD

**Issue by AliMickey** [netbox-community/netbox#16256]
### NetBox version

v4.0.2

### Feature type

Change to existing functionality

### Proposed functionality

Add additional order by options for bookmarks on the dashboard. 

### Use case

Alphabetical ordering is useful, and also matches the default table ordering of other sections.

**Comment by jeremystretch** [comment]
> Add additional order by options for bookmarks on the dashboard.

Please expand on your proposal. How would bookmark ordering be specified? Are you asking that the widget itself be extended?

**Comment by AliMickey** [comment]
I didn't think I'd need to expand, sorry if I wasn't clear.

I am referencing the bookmarks widget on the dashboard, within which the configuration for it there is an 'Order by' field, the only two options are newest and oldest. I am suggesting that there be a third option called 'Alphabetical' which does what it means... sorts the bookmarks alphabetically.

![image](https://github.com/netbox-community/netbox/assets/60691199/27bca0f3-b25a-4bef-a26e-d6e6cb08ff4c)

**Comment by jeremystretch** [comment]
Unfortunately alphabetical ordering is not feasible as there's no way to reliably and efficiently order by the name of generic related objects. (Not all objects have a `name` field.)

**Comment by jeremystretch** [comment]
It could _probably_ be done in memory on the string representations of each object, given that the list of bookmarks typically shouldn't be very long. I'll open this for any volunteers.

**Comment by BrendanHalley** [comment]
+1 this would be useful

**Comment by Julio-Oliveira-Encora** [comment]
Could you please assign it to me?
