### ISSUE TITLE
Custom Script `description` not displayed in v4.0.2

### ISSUE THREAD

**Issue by Kani999** [netbox-community/netbox#16257]
### Deployment Type

Self-hosted

### NetBox Version

v4.0.2

### Python Version

3.10

### Steps to Reproduce

1.    Navigate to the custom scripts section in NetBox.
2.    Upload a script that includes a description metadata.
3.    Observe that the description is not displayed anywhere in the interface.

### Expected Behavior

The description provided in the custom script metadata should be displayed as it was in version 3.7.

### Observed Behavior

The description is not displayed anywhere in the interface. This was working in the previous version 3.7 but seems to be missing in version 4.0.2

**Comment by jeremystretch** [comment]
I believe this has been captured by #16050 and is currently being addressed.
