### ISSUE TITLE
Make an easy way to pre-fill custom script variables

### ISSUE THREAD

**Issue by llamafilm** [netbox-community/netbox#16250]
### NetBox version

v3.7.3

### Feature type

Change to existing functionality

### Proposed functionality

When selecting dropdown variables in a custom script, update the URL immediately with the currently selected options, so it can be easily bookmarked.  This answer describes a simple way to do this: https://stackoverflow.com/questions/3338642/updating-address-bar-with-new-url-without-hash-or-reloading-the-page

### Use case

I have an "add device" script with lots of variables.  When adding several devices to the same site/rack, I create a browser bookmark with those query params, so I can keep coming back to the script with those fields pre-filled.  It would be much easier if those query params were added to the URL immediately after entering the dropdowns.  As it is now, I have to open a new tab to find the ID for each of those objects, and type a long query string by hand.

https://github.com/netbox-community/netbox/assets/3991046/8c46f4eb-6e66-44f3-afa3-b6ff9ff192dc

### Database changes

none

### External dependencies

none

**Comment by jeremystretch** [comment]
> When selecting dropdown variables in a custom script, update the URL immediately with the currently selected options, so it can be easily bookmarked.

I'm afraid this is not a tenable proposal, but I suspect the proposal in #9609 would suit your use case.

**Comment by llamafilm** [comment]
That other issue might help, depending how it’s implemented. If you add a single button `Rerun with same values` that would not help here. 
If, instead, you display the form again with pre-filled values and the ability to edit them, that should work.

To clarify the use case: I want to run the script 10 times with different values, but some of the values are the same (site, location, rack). So I’m trying to save time re-entering those 3 variables every time.

**Comment by jeremystretch** [comment]
Ok, let's wait until #9609 gets implemented and go from there. Feel free to add your use case on that FR.
