### ISSUE TITLE
Child Devices Creation / Assignation in web UI

### ISSUE THREAD

**Issue by thefreakquency** [netbox-community/netbox#1626]
### Issue type
[ X ] Feature request 

### Environment
* Python version:  3.5.4
* NetBox version:  2.2.1

### Description
From the "Add a new device" page, when adding a device with a type declared as a Child device, it would be useful to have the option to assign it directly to a device with an empty slot. (i.e.: in the "location section" of the page, the rack face & position could probably switched to "a field showing the available devices with a free slot".

Also, when looking at a device page ( /dcim/devices/xxxx/ ), when clicking on the green plus sign of a vacant slot to "install a device", it currently shows already created devices. Adding a "Create a new child device and assign to current parent" would be a real time saver. 

When we create a server, our current data model requires us to separate the management port (i.e. iDrac, ILOM, RMM, etc.) from the server but we attach it to the main server as a separate device. The reason for this is that the management port has it's own device name & OS and is separate from the main box. 

We have to create the server as a device, than create a management device, then go back to the server and assign it.

**Comment by jeremystretch** [comment]
> From the "Add a new device" page, when adding a device with a type declared as a Child device, it would be useful to have the option to assign it directly to a device with an empty slot.

While I agree that this would be a welcome improvement, it would require considerable development effort to implement, including:

* Determining whether the selected device type is a child device
* Dynamically altering the form to hide rack face and position, and show a list of parent devices
* Populating available device bays in the form after selecting a parent device

I'll leave this open if someone wants to take a shot at it, but it's going to challenging with the current UI.
