### ISSUE TITLE
Planned cables not highlighted on front / rear ports

### ISSUE THREAD

**Issue by ChrisRecioHive** [netbox-community/netbox#16272]
### Deployment Type

Self-hosted

### NetBox Version

v4.0.2

### Python Version

3.11

### Steps to Reproduce

1. Create a patch panel or device with front / rear ports
2. Create a cable with a termination as a front or rear port and set it as "Planned"

### Expected Behavior

Cables set as planned should display with a different background color, similar to how it is shown on interfaces

![image](https://github.com/netbox-community/netbox/assets/143728336/1a0a31f8-76a1-409c-89c8-242c013a5517)

### Observed Behavior

Planned cables on front and rear ports do not have a different background color. Interfaces display planned cables properly with a different background color.

![image](https://github.com/netbox-community/netbox/assets/143728336/6f0b338a-823c-4d9e-8175-a290e8476da2)

**Comment by Chiniquy** [comment]
We have an issue where we are not seeing front ports highlighted at all when they are connected. Not sure if it is related.

**Comment by Chiniquy** [comment]
I believe this is not just for planned cables, but for connected cables on front ports as well.

**Comment by jeremystretch** [comment]
This has already been raised in #16039. Please remember to search for open issues before submitting a new bug report.
