### ISSUE TITLE
Do not forget when updating. (/opt/netbox/validators/ )

### ISSUE THREAD

**Issue by LHBL2003** [netbox-community/netbox#16278]
### Change Type

Addition

### Area

Installation/upgrade

### Proposed Changes

I implemented my first validator class in Netbox today. However, the update documentation does not mention that the "/opt/netbox/validators/" folder must also be copied as an option. I would like to document this.
I would therefore ask for permission to do so.

**Comment by PieterL75** [comment]
I think that the place for custom code is in in /opt/netbox/netbox/local
That folder is excluded from git updates. So running a git command will not complain about any folder/file you added.
you can import your validator as local.yourfilename.classname

**Comment by jeremystretch** [comment]
The documentation does not prescribe a specific location for custom validators, and thus it cannot advise on specific additional steps pursuant to an upgrade. Ideally any such custom code should be installed via separate Python package entirely.

**Comment by jeffgdotorg** [comment]
Closing issue as not planned.

@LHBL2003 thanks for flagging a potential pitfall and looking out for future users in your position. If you would like to open a new docs PR to capture the availability of the `netbox/local` directory for protecting local resources from git-meddling, you're welcome to do so.
