### ISSUE TITLE
Custom Script StringVar is not JSON serializable

### ISSUE THREAD

**Issue by willikubny** [netbox-community/netbox#16279]
### Deployment Type

Self-hosted

### NetBox Version

v4.0.3

### Python Version

3.11

### Steps to Reproduce

With a StringVar or TextVar as input variable in a NetBox custom script the script is working through the UI, but fails to view through the REST API browser or get/execute with the REST API.

If the StringVar is removed from the NetBox custom script, then the REST API works fine again.

### Expected Behavior

StringVar or TextVar in NetBox custom script should be serialized correctly.

### Observed Behavior

<class 'TypeError'>

Object of type StringVar is not JSON serializable

Python version: 3.11.6
NetBox version: 4.0.3
Plugins: 
  netbox_device_support_plugin: 1.0.5
  netbox_napalm_plugin: 0.2.0

**Comment by jeremystretch** [comment]
Thank you for opening a bug report. Unfortunately, the information you have provided is not sufficient for someone else to attempt to reproduce the reported behavior. Remember, each bug report must include detailed steps that someone else can follow on a clean, empty NetBox installation to reproduce the exact problem you're experiencing. These instructions should include the creation of any involved objects, any configuration changes, and complete accounting of the actions being taken. Also be sure that your report does not reference data on the public NetBox demo, as that is subject to change at any time by an outside party and cannot be relied upon for bug reports.

**Comment by willikubny** [comment]
Sorry for opening a wrong bug. I found my mistake...

I've named the input StringVar variable "description" and that caused the issue. After naming the variable ap_description it's working.

Thank you anyway for your fast response.
Keep up the good work as NetBox is a great product.

**Comment by llamafilm** [comment]
I just found this same issue!  Took me awhile to figure this out.  I would say this is a bug.  To reproduce, create a custom script with the following contents.  It runs fine in the UI, but /api/extras/scripts throws the exception as the OP described.  Renaming the `description` variable makes it work.

```py
from extras.scripts import Script, StringVar

class AddDevice(Script):

    class Meta:
        name = "Add Device"

    description = StringVar()

    def run(self, data, commit):
        self.log_debug(data)
        return
```
