### ISSUE TITLE
Typo in Documentation for NetBoxModelBulkEditForm 

### ISSUE THREAD

**Issue by JonasEinfach** [netbox-community/netbox#16284]
### Change Type

Cleanup (formatting, typos, etc.)

### Area

Development

### Proposed Changes

I think in the documentation of the NetboxModelBulkEditForm is a typo: https://netboxlabs.com/docs/netbox/en/stable/plugins/development/forms/#netboxmodelbulkeditform

![image](https://github.com/netbox-community/netbox/assets/100405740/ef841fbb-ab3b-4461-855f-69f49b6e39e7)

That should be the NetBoxModelBulkEditForm?

**Comment by arthanson** [comment]
Looks like it should be NetBoxModelForm, thanks for the catch
