### ISSUE TITLE
Connected power cables not highlighted

### ISSUE THREAD

**Issue by amit177** [netbox-community/netbox#16283]
### Deployment Type

Self-hosted

### NetBox Version

v4.0.3

### Python Version

3.10

### Steps to Reproduce

1. Create a device with power ports - device A
2. Create a device with power outlets - device B
3. Go to device A and connect one of the power ports to device B with the Connected status
4. The power port shows no highlight at all and shows the "Mark Installed' button

### Expected Behavior

The power port should have had a green highlight indicating it is connected.

### Observed Behavior

The power port was not showing any highlight.
It seems like marking it as planned does not show highlight either.

**Comment by jeremystretch** [comment]
This appears to be covered by #16039.
