### ISSUE TITLE
Add ability to search for provider accounts

### ISSUE THREAD

**Issue by pv2b** [netbox-community/netbox#16286]
### Deployment Type

Self-hosted

### NetBox Version

v4.0.3

### Python Version

3.10

### Steps to Reproduce

1. Add a provider account
2. Try to search for it

### Expected Behavior

Provider account is listed

### Observed Behavior

No search results found for the provider

**Comment by arthanson** [comment]
@pv2b yes, looks like a bug - I've converted the issue to a bug format for tracking.  Thanks for bringing this to our attention.
