### ISSUE TITLE
Colum headlines in dashboard are not translated in foreign languages

### ISSUE THREAD

**Issue by chbally** [netbox-community/netbox#16281]
### Deployment Type

Self-hosted

### NetBox Version

v4.0.3

### Python Version

3.10

### Steps to Reproduce

1. Make a screenshot of the English Dashboard.
2. Goto User Preferences and Change Language to what ever
3. Go back to the Dashboard: The Headlines will not have been translated

### Expected Behavior

Headlines shown as translated.

### Observed Behavior

Only native english language is shown
The content is shown in the right translation

**Comment by arthanson** [comment]
DEFAULT_DASHBOARD strings aren't internationalized.

**Comment by jeremystretch** [comment]
The widget titles aren't translated because they're meant to be user-generated; the default configuration is just a placeholder. We could add translation support, but understand that it's going to be of very limited utility, because translation is accomplished via static string mappings. For example, if a user creates a widget with the title "My custom widget," NetBox won't know how to translate it.

**Comment by chbally** [comment]
I don't agree with you @jeremystretch . 
For Organiszation, Tenants and so on, they are normaly following the translation and I would expect that for the dashboard as well.
Only for custom widgets you are right. But if I create a custom widget as native german speaker, i wouldn't name it "Custom Widget" but "Benutzerdefiniertes Widget" and only because there is no german word for widget.

We do the translationen stuff to raise the acceptance of Netbox in the use of foreign languages - most of us work with english speaking systems every day.
In 25 years of implemanting software in companys, I've seen quite some software projects fail, because the users didn't recognize their regular wording in the first occasion the see the software.
From the same perspective I would also recommend, to have some system defined translation for major objects - such as site, location, system and tenant. 
In the german translation we haven't found an agreement for the translation of "Location" yet, because almost everybody has a different translation and usage to it.
For tenant we agreed on "Mandant" but even "Kunde" (client), "Abteilung" (department) could be a personal choice vor companys installation.

**Comment by jeremystretch** [comment]
Yes, that's what I mean by "very limited utility:" Only the words NetBox knows can be translated.

**Comment by chbally** [comment]
Sorry, we don’t get together here yet.
A newly crated user, will find on the dashboard in a totally translated software not translated items such as organization, tenant, site location and so on, when he firstly opens the software.
For the users point of view, that doesn’t make sense.
Iif sit yourself on the chair of this user without knowing any code, you know, I’m right.
And to use your own argument: Netbox can translate oranization, tenant, site and location and so on.
