### ISSUE TITLE
GraphQL interface_list query returns all interfaces if filter contains non-existing device

### ISSUE THREAD

**Issue by dmulyalin** [netbox-community/netbox#16299]
### Deployment Type

Self-hosted

### NetBox Version

v4.0.3

### Python Version

3.10

### Steps to Reproduce

Run query like this:

```
{
  interface_list(filters: {device: ["fceos21", "ceos1"]}) {
    name
  }
}
```

where fceos21 is a device not defined in Netbox and ceos1 is a device that exists in Netbox, that query returns ALL interfaces defined in Netbox for all devices

### Expected Behavior

Query returns interfaces only for existing devices, if none of the devices from query filter exists in Netbox return None

### Observed Behavior

query returns all interfaces defined in Netbox if non existing device given in query filter

**Comment by jeffgdotorg** [comment]
Thanks for reporting a problem you've encountered in NetBox.

I've managed to reproduce the problem in the lab, but in future, please remember to assume a pristine, unpopulated NetBox install as the starting point, and to specify all the objects that need creating to make the problem reproducible.

**Comment by jeremystretch** [comment]
@jeffgdotorg please assign a severity level for this.

**Comment by arthanson** [comment]
This is actually the same as #16024 (this would result in an AND query).  closing this and noting in that issue to make sure this syntax is tested as well.
