### ISSUE TITLE
Patch Panel, Racks etc. should be separated from Managed devices.

### ISSUE THREAD

**Issue by jinu18** [netbox-community/netbox#16308]
### NetBox version

v4.0.3

### Feature type

Change to existing functionality

### Proposed functionality

I propose that NetBox separate infrastructure components such as patch panels, racks, and other similar items from managed devices. When viewing the devices list on a site, it should include only managed devices such as switches and routers, and not infrastructure components. This separation would improve clarity and usability by ensuring that the devices list accurately reflects the count of managed network devices without being inflated by passive infrastructure items.

### Use case

NetBox users range from network engineers to top management, each with different needs and perspectives. Here are some scenarios highlighting the benefits of this proposed change:

Engineers and Technicians: When performing tasks such as network audits, capacity planning, or troubleshooting, engineers need an accurate view of the active network devices at each site. The current system can be misleading, as it inflates the device count with passive components like patch panels and racks. This separation would streamline their workflows, making it easier to focus on critical network elements.

Management and Reporting: Management often relies on NetBox for high-level overviews and reporting. Seeing a large number of "devices" that includes infrastructure components can be confusing and misleading. For instance, a report showing a site with 150 "devices" might be misinterpreted if half of those are actually patch panels and rack accessories. By categorizing these separately, reports and dashboards will provide clearer insights into the actual count of active network devices versus passive infrastructure.

Inventory Management: Accurate inventory management is crucial for operational efficiency. Separating managed devices from infrastructure components aids in better inventory tracking and management, ensuring that asset counts reflect true operational resources.

User Experience: Improving the clarity of device listings enhances the overall user experience for all NetBox users. Users can quickly access the information they need without sifting through irrelevant items, leading to increased efficiency and satisfaction.

**Comment by jeremystretch** [comment]
Thank you for your interest in extending NetBox. Unfortunately, the information you have provided does not constitute an actionable feature request. Per our [contributing guide](https://github.com/netbox-community/netbox/blob/develop/CONTRIBUTING.md), a feature request must include a thorough description of the proposed functionality, including any database changes, new views or API endpoints, and so on. It must also include a detailed use case justifying its implementation. If you would like to elaborate on your proposal, please modify your post above. If sufficient detail is not added, this issue will be closed.
