### ISSUE TITLE
Cant filter changelog by object type (no results found)

### ISSUE THREAD

**Issue by ITJamie** [netbox-community/netbox#16315]
### Deployment Type

Self-hosted

### NetBox Version

v4.0.3

### Python Version

3.11

### Steps to Reproduce

goto changelog
goto filters tab
select object type dropdown.

### Expected Behavior

list of netbox object types to be selectable

### Observed Behavior

 "no results found" appears in dropdown list
 
<img width="1506" alt="Screenshot 2024-05-28 at 12 44 26" src="https://github.com/netbox-community/netbox/assets/1613241/f71824ea-c22b-4d65-85d8-5de1ae13b551">

**Comment by ITJamie** [comment]
the same issue is also impacting "journal-entries" filtering. the object type dropdown is returning no results found

**Comment by Julio-Oliveira-Encora** [comment]
Could you please assign it to me?

**Comment by arthanson** [comment]
@Julio-Oliveira-Encora assigned
