### ISSUE TITLE
Filter interfaces to device only when adding new IP

### ISSUE THREAD

**Issue by PieterL75** [netbox-community/netbox#16327]
### NetBox version

v4.0.3

### Feature type

Data model extension

### Proposed functionality

When adding an IP to an interface, the edit form shows all possible interfaces available, and not only those from the device where the IP is added to.
This was addressed in #13293, but only works when editing an existing IP

step:
create an IP
create a device with interfaces
on the device/interface list, click the blue '+ IP Address'

Check the dropdown for the assigned interfaces. That one shows all interfaces available
![image](https://github.com/netbox-community/netbox/assets/74899468/2d1716a9-8afc-4a48-84b5-1dde5dcb0abf)
 

### Use case

Same as in #13293 : reduce effort when adding IPs to a device.
When a wrong interface was selected and noticed in the AddIP form, then changing the interface will be more straightforward

**Comment by jeremystretch** [comment]
> When adding an IP to an interface, the edit form shows all possible interfaces available, and not only those from the device where the IP is added to.

Why would it be necessary to limit the list of interfaces? The field is already pre-populated with the original interface, and it's perfectly acceptable for the user to change it to an interface on a different device. (We include the advanced selector button on this field for this purpose.)

**Comment by PieterL75** [comment]
Because you start of a device, and it makes sense to show only the device's interfaces, and not all the rest.
If you just create an IP, then I agree that it should show any interface, and that AdvancedSelector could be used.

If you by accident used the wrong interface on a device to add an IP, then it is again a click-click to get to the right interface.
This would also make the user experience the same for adding or updating an IP, when starting from a device
