### ISSUE TITLE
Tenant grp and Tenant are reset when choosing "Create & Add Another"

### ISSUE THREAD

**Issue by nerfux** [netbox-community/netbox#16357]
### Deployment Type

Self-hosted

### NetBox Version

v4.0.3

### Python Version

3.12

### Steps to Reproduce

1. Create a cable, and assign it to a tenant group and tenant
2. Click "Create & Add Another"
3. all fields are pre-defined from last section, but tenant/tentant groups are empty

### Expected Behavior

Tenant / Tenant group fields are pre-defined from last creation of the cable

### Observed Behavior

none

**Comment by jeffgdotorg** [comment]
Thanks for reporting a problem you're having with NetBox.

In attempting to reproduce this problem on a fresh, empty 4.0.3 installation, I'm in fact seeing none of the field values carried over from the previous creation of the first cable. This leads me to think the behavior is expected. Labeling under review while the other maintainers weigh in.

**Comment by nerfux** [comment]
But the devices from the orginal cable created are filled out?
