### ISSUE TITLE
Enable plugins to inject content within the top navigation bar

### ISSUE THREAD

**Issue by jeremystretch** [netbox-community/netbox#16359]
### NetBox version

v4.0.3

### Feature type

New functionality

### Proposed functionality

It is currently possible for a plugin to embed custom content in NetBox core views by employing one or more of the available [extension methods](https://netboxlabs.com/docs/netbox/en/stable/plugins/development/views/#extra-template-content) of the PluginTemplateExtension class. This proposal would add a new method, `navbar()`, to enable a plugin to inject custom content within the top navigation bar, to the left of the user menu (opposite the global search bar).

This will also require slight modification to the logic for [registering template extensions](https://github.com/netbox-community/netbox/blob/05c69f84e69ac4ea8197452a75837e07d032993f/netbox/netbox/plugins/registration.py#L35), which currently requires the association of an extension with a particular NetBox model.

### Use case

It may be desirable for a plugin to embed a notification or control widget of some kind which persists across multiple views.

### Database changes

None

### External dependencies

None

**Comment by PieterL75** [comment]
Funny, we had a discussion in the #netbox-plugin-development on this :-)
There was the question what the best way is to inject CSS or JS.
BOTTOM_BANNER was the best solution for now.

So can we extend this FR to include a mean to inject something like CSS and JS ?
Or should we open another FR for this

**Comment by jeremystretch** [comment]
@PieterL75 what would not be in scope for this FR.
