### ISSUE TITLE
Global Search Box present when horizontal screen < 992px

### ISSUE THREAD

**Issue by multco-troy** [netbox-community/netbox#16375]
### NetBox version

v4.0.3

### Feature type

Change to existing functionality

### Proposed functionality

Search box to be in the header with the logo, or accessible via the hamburger menu when horizontal screen < 992px

### Use case

Currently you can only search per section when screen size is limited (mobile, or users with low resolution screens due to vision impairment).  This isn't ideal for those users who my not know the exact hierarchy of the item they're looking for.

**Comment by jeremystretch** [comment]
It would probably need to go in the menu, as we can't guarantee sufficient space in the header. It's also probably not desirable to display the search box constantly on mobile.

**Comment by jirutka** [comment]
We have also run into this problem now. It’s not just missing global search; the new UI is almost unusable on mobile phones.
