### ISSUE TITLE
GraphQL interface_list filtering by type does not work

### ISSUE THREAD

**Issue by dmulyalin** [netbox-community/netbox#16378]
### Deployment Type

Self-hosted

### NetBox Version

v4.0.3

### Python Version

3.10

### Steps to Reproduce

1. Create device in netbox (fceos4 in this example)
2. Create interface of type LAG
3. Create interface of any other non-lag type
4. run query

```
{
  interface: interface_list(
    filters: {
      device: ["fceos4"], 
      type: {exact: "lag"}
    }
  ) {
    name
    type
    device {
      name
    }
  }
}
```

or this variant:

```
{
  interface: interface_list(
    filters: {
      device: ["fceos4"], 
      AND: {type: {exact: "lag"}}
    }
  ) {
    name
    type
    device {
      name
    }
  }
}
```

### Expected Behavior

Only should return interface of type `lag`

### Observed Behavior

Returns device interface of all types ignoring the filter.

**Comment by jeremystretch** [comment]
Confirmed on v4.0.3. Wonder if it's a similar issue to #16261.

**Comment by arthanson** [comment]
This is actually a dupe of #16024 closing this one
