### ISSUE TITLE
status color background is not distinguishable

### ISSUE THREAD

**Issue by opericgithub** [netbox-community/netbox#16385]
### Deployment Type

Self-hosted

### NetBox Version

v4.0.3

### Python Version

3.10

### Steps to Reproduce

Not actually a real bug, but more of a suggestion. 
When changing the background color values ​​for the prefix statuses in the "FIELD_CHOICES" section of the configuration.py file, it is very difficult to distinguish black, gray and white colors. in the previous version (v3.x) the difference was much more obvious.

### Expected Behavior

v3 black:
![image](https://github.com/netbox-community/netbox/assets/65983735/f0437843-7884-482b-9cfa-21c497f4afa8)

v3 gray:
![image](https://github.com/netbox-community/netbox/assets/65983735/89cffa3c-c2c8-4657-9828-9b51d71aa276)

v3 white:
![image](https://github.com/netbox-community/netbox/assets/65983735/6e45f663-aa5b-4102-a3b0-17d083e59106)

### Observed Behavior

v4 black:
![image](https://github.com/netbox-community/netbox/assets/65983735/2f12f7ee-0281-4a76-a74e-f0701503e22d)

v4 gray:
![image](https://github.com/netbox-community/netbox/assets/65983735/43830d32-8d9d-46fb-b8e4-f47371c72f76)

v4 white:
![image](https://github.com/netbox-community/netbox/assets/65983735/63f43524-91a4-4d5a-9636-6d5095f501e5)

**Comment by jeffgdotorg** [comment]
Thanks for reporting this low visual contrast issue. I'm putting it through and assigning low severity, partly because there's a comprehensive rework of contrast planned for v4.1 under #16390.

**Comment by jeremystretch** [comment]
Looks like we lost the black, white, and gray styles during the move to Bootstrap v5.3. We probably just need to create aliases for the native styles:

* `black` -> `dark`
* `white` -> `light`
* `gray` -> `secondary`

**Comment by jeremystretch** [comment]
[Bootstrap docs](https://getbootstrap.com/docs/5.3/utilities/colors/) for reference. Custom colors need to be defined in `styles/overrides/_bootstrap.scss`.
