### ISSUE TITLE
Cable trace for rear ports

### ISSUE THREAD

**Issue by yangsystem** [netbox-community/netbox#16389]
### Deployment Type

Self-hosted

### NetBox Version

v4.0.3

### Python Version

3.10

### Steps to Reproduce

1. create a new device
2. add interface connect cables to another device (a switch through  some patch panels that are linked together via backports and front ports)
3. add power port and connect to a PDU outlet
4. add 2 rear ports:
 4.1 link first to another device also that has rear port
 4.2 link second rear port through patch panel front port (rear port is connected to other patch panel) connect patch panel 2 front port to other device

![image](https://github.com/netbox-community/netbox/assets/6049104/2012ddcc-9ec8-47d5-8ede-cacca8c739c7)
![image](https://github.com/netbox-community/netbox/assets/6049104/83866f3c-bab0-44b2-a048-7788e3fa3a55)
![image](https://github.com/netbox-community/netbox/assets/6049104/c6878ca3-ae0b-41bc-be92-8cc7e60b5643)

### Expected Behavior

when I trace the rear ports I do not get the cables.
![image](https://github.com/netbox-community/netbox/assets/6049104/359c19dc-3559-4630-9f43-83f20850fed1)
![image](https://github.com/netbox-community/netbox/assets/6049104/0e83a7ea-e42d-417e-9d7a-bc0f0ce5a0a6)

power and interface are working
![image](https://github.com/netbox-community/netbox/assets/6049104/a9bbac5e-ec62-41c0-a763-e3bdf90dd891)
![image](https://github.com/netbox-community/netbox/assets/6049104/2cacce62-6d50-40db-b2c6-248eb04c967b)

no worries about IP's and names of the device, nobody will find them as they are not connected to the internet.

### Observed Behavior

As you can see from the pictures above there is no picture or any trace for that cable.
I understand that I did not declare that as a copper RJ45 interface but I use RJ45 connectors and I transport legacy voice signal on that wire. I expect the platform to not care of what type of signal is there if there is any at all, just to trace the cables and show the trace (with names length's colors and where it is connected each segment)

**Comment by arthanson** [comment]
@yangsystem Thank you for opening a bug report. Unfortunately, the information you have provided is not sufficient for someone else to attempt to reproduce the reported behavior. Remember, each bug report must include detailed steps that someone else can follow on a clean, empty NetBox installation to reproduce the exact problem you're experiencing. These instructions should include the creation of any involved objects, any configuration changes, and complete accounting of the actions being taken. Also be sure that your report does not reference data on the public NetBox demo, as that is subject to change at any time by an outside party and cannot be relied upon for bug reports.

Can you please expand on the reproduction steps, step 2 is fairly ambiguous and 4.1 and 4.2 it's not clear which device you are talking about (or if they were created previously), for an example:

1. Create "Device A".
2. Create "Device B"
3. Create front-port "fp1" on Device A
4. Create back-port "bp1" on Device B
5. Create cable connecting "fp1" to ...

**Comment by yangsystem** [comment]
ok:
1. define a rack
2. define 2 patch panels patch-a and patch-b
3. define 2 rear ports on each patch-a and patch-b 
4. define 2 front ports on each patch-a and patch-b and link them to the back patch-a/front/1-patch-a/back/1 patch-a/front/2-patch-a/back/2 patch-b/front/1-patch-b/back/1 patch-b/front/2-patch-b/back/2
5. link patch-a/back/1 to patch-b/back/1 and patch-a/back/2 to patch-b/back/2 with cable1 (2m long white) and cable2 (2m long purple)
![image](https://github.com/netbox-community/netbox/assets/6049104/349fefcd-1308-4a0d-8e7c-f7dc1a0bd72a)
6. now if you want to trace cable1 (#670 in picture) or cable2 (#671 in picture) you will get a no path found. and clearly the cable is connected to rear ports of patch-a/back/1 and patch-b/back/1 
![image](https://github.com/netbox-community/netbox/assets/6049104/13619051-22db-4acb-bbed-6c00d1d75c4a)
7. add a device name "radio-rx" , define interface "lan1" (type 1000 base-T not important), define a rear port: name "radio-rx/rear/1" type "8P6C" position "1"
8. add a switch: name "switch-1", with interfaces "port[1-8]", name port[1-8], type "1000 base-t"
9. connect switch-1/port1 to patch-a/front/1 , type "cat6", color "red", length "2 meters"
10. connect radio-rx/lan1 to patch-b/front/1, type "cat6", color "red", length "0.5 meters"
11. if you trace the cable all is OK
![image](https://github.com/netbox-community/netbox/assets/6049104/c149dc92-5c5b-44e9-86ac-b25de3616088)
12. connect radio-rx/rear/1 to patch-b/front/2, type "cat6", color ""purple, length "5 meters"
![image](https://github.com/netbox-community/netbox/assets/6049104/c4d7c75d-e387-4bcc-98cb-49b05e4a533a)
13. trace the new cable and nothing show's up
![image](https://github.com/netbox-community/netbox/assets/6049104/42962e2b-6760-434f-938f-f38819e0e478)
14. mark patch-a/front/2 as connected and do a trace on cable from radio-rx/rear/1 and nothing will show up.
I was expecting to see some cables there: 6m purple to patch-b/front/1 followed by 2m purple to patch-a/rear/2 followed by a block marked as connected (for now I do not have there a device defined but I want to know that is connected)

extra pictures:
![image](https://github.com/netbox-community/netbox/assets/6049104/c32e7e86-ddec-452e-b3dc-d5b812031ea8)
![image](https://github.com/netbox-community/netbox/assets/6049104/72cf2e05-33c4-41d8-bf31-4ec1c75db7ed)
![image](https://github.com/netbox-community/netbox/assets/6049104/2d480cf1-c2ec-4977-89b3-27435e493b93)
![image](https://github.com/netbox-community/netbox/assets/6049104/ff02b563-4e78-450b-88e4-66b0dfb8e7f3)
![image](https://github.com/netbox-community/netbox/assets/6049104/5810337d-c6bc-40dc-af77-d5be89db41f9)
![image](https://github.com/netbox-community/netbox/assets/6049104/d55e70c0-3bed-4fd3-9d30-b99baac18896)
![image](https://github.com/netbox-community/netbox/assets/6049104/a7a9480a-b927-43e9-aa38-638f4642f45e)
![image](https://github.com/netbox-community/netbox/assets/6049104/c824117e-3f78-4ccc-bbe0-fbd94d16bd25)

hope I was accurate now.

**Comment by Chiniquy** [comment]
Seems to be the same issue as https://github.com/netbox-community/netbox/issues/14155.

**Comment by arthanson** [comment]
@yangsystem this does look like the same issue as #14155 mentioned above.  There are several technical hurdles to doing this and a discussion is at #12094 please add to the discussion there to share their ideas and collaborate with others. Once a functioning implementation has been fleshed out, it can be proposed in a new feature request.
