### ISSUE TITLE
Add hx-indicator to nav links spinner for HTMX navigation

### ISSUE THREAD

**Issue by tbotnz** [netbox-community/netbox#16397]
### NetBox version

v4.0.3

### Feature type

Change to existing functionality

### Proposed functionality

Add a loading spinner by utilizing hx-indicator for nav clicks when using HTMX navigation

### Use case

When using HTMX navigation, sometimes it feels weird for the user how the page loads, providing feedback on navlink clicks via hx-indicator will help 

### Database changes

none

**Comment by jeremystretch** [comment]
Duplicate of #15762
