### ISSUE TITLE
Distinguish product types visually (OSS, Cloud, Enterprise)

### ISSUE THREAD

**Issue by andrewgormley** [netbox-community/netbox#16394]
### NetBox version

v4.0.3

### Feature type

New functionality

### Proposed functionality

Distinguish between OSS, Cloud and Enterprise products through visual changes when users are logged in. This should occur through slightly different branded experiences such as adding a label below the logo with the name of the product type. Also using an alternate colour/gradient to subtly alter the theme which is bespoke to that product type.

### Use case

Users will immediately know which application they are using. By adding this feature it will also open the door to future theming and branded experiences.

**Comment by jeremystretch** [comment]
> This should occur through slightly different branded experiences such as adding a label below the logo with the name of the product type.

@andrewgormley how would you like to accomplish this? Do we need to package alternative logos (images), or will this be text-based?

Also, marking this as blocked by #15908, which will introduce support for declaring a NetBox "edition" (e.g. Cloud, Enterprise, community).

**Comment by jeremystretch** [comment]
Just noting that this is no longer blocked as #15908 has been completed. Let's prioritize this work for next week.
