### ISSUE TITLE
Problem to restore configuration from history

### ISSUE THREAD

**Issue by ravenrs** [netbox-community/netbox#16400]
### Deployment Type

NetBox Cloud

### NetBox Version

v4.0.4

### Python Version

3.10

### Steps to Reproduce

![2024-06-04_14-46-12](https://github.com/netbox-community/netbox/assets/16837927/f6711366-af57-4a68-bc21-86da05b37eab)
1. Click https://demo.netbox.dev/core/config-revisions/
2. Create new configuraton
3. Delete active configuration
4. Click to restore the previous configuration
5. Get error messageconfiguration

### Expected Behavior

previous configuration should be restored.

### Observed Behavior

error was raised.

**Comment by Julio-Oliveira-Encora** [comment]
Could you please assign it to me?
