### ISSUE TITLE
Missing filter for test cases in custom scripts

### ISSUE THREAD

**Issue by hackcl** [netbox-community/netbox#16402]
### Deployment Type

Self-hosted

### NetBox Version

v4.0.0

### Python Version

3.10

### Steps to Reproduce

1. Run a custom script with multiple test cases
2. See results
3. Click on one of the test hyperlinks of the test cases in the "Test Summary"

e. g.: 
![image](https://github.com/netbox-community/netbox/assets/43070830/a62558b0-158f-4323-bf85-db3a388a5d1c)

### Expected Behavior

Filter for log entries based on the specific test case.
In case of my example, by clicking on test_vrf_set, only show the log entires related to this test case

### Observed Behavior

Nothing. Change in URL.
e.g.:
/netbox/extras/scripts/results/1200/?page=37#test_vrf_set

As it is an hyperlink, I would expect it to be filter. 
If this is not the expected behavior, then I would propose it as a feature.

**Comment by jeffgdotorg** [comment]
Thanks for reporting a problem you've encountered in NetBox.

Please provide more detail in your *Steps to Reproduce*, including a minimal script that enables a user to start from a fresh, empty install of NetBox and arrive at the problem behavior you describe.

**Comment by hackcl** [comment]
Sorry, I was on vacation and forgot about it. I try to do it until beginning of next week.

**Comment by hackcl** [comment]
I was able to do it quickly code a small script. It contains two duplicate test cases with different names.
It checks whether a tenant is set for the device but it is not relevant.

### Script
[example.zip](https://github.com/user-attachments/files/15901519/example.zip). 

### Other Requirements
Some existing devices. Setting a tenant is irrelevant.

### After Execution
After execution it should look like this. 
![image](https://github.com/netbox-community/netbox/assets/43070830/7c786628-c9a4-4c30-bb7e-02036547e0b9)

Now I would expect if I click in the "Test Summary" on "test_if_tenant_is_set2" to only see log messages from this test case. This dont happen.

The only thing that changes if clicking on one of the two test cases is the url:
`/netbox/extras/scripts/results/1372/#test_if_tenant_is_set`
`/netbox/extras/scripts/results/1372/#test_if_tenant_is_set2`

**Comment by jeremystretch** [comment]
The page anchor is a remnant of the legacy report results view. It no longer has any function and can be removed.

**Comment by hackcl** [comment]
I don't think it should be removed as it would be quit helpful for cases with a lot of log entries. 

I would try to implement it but I don't have the time currently.
