### ISSUE TITLE
Busy port illumination

### ISSUE THREAD

**Issue by bee-media** [netbox-community/netbox#16413]
### NetBox version

v4.0.3

### Feature type

New functionality

### Proposed functionality

Please return the backlighting of the busy port in the crossover, as it was before in the old version.
Now you can understand whether the port is busy or not by the black square.
![345](https://github.com/netbox-community/netbox/assets/25938240/2b3f9d38-e224-4fa6-8a5a-487b13ea4488)

### Use case

If you use netbox (v4.0.3) on your phone, it is very inconvenient to use the (cross) mode, since you need to peer into the black square.

**Comment by Chiniquy** [comment]
Duplicate of https://github.com/netbox-community/netbox/issues/16039 ?

**Comment by bee-media** [comment]
> Duplicate of #16039 ?

No, they returned the backlighting on the interfaces, but did not return the front and rear ports of the crossover.

**Comment by bee-media** [comment]
The topic can be closed. This question has already been asked. I'll keep an eye on the updates.
