### ISSUE TITLE
Allow filtering of Devices by Cluster and Cluster Group

### ISSUE THREAD

**Issue by ITJamie** [netbox-community/netbox#16424]
### NetBox version

v4.0.3

### Feature type

Change to existing functionality

### Proposed functionality

Allow filtering Devices in the UI by Cluster and or Cluster Group.

### Use case

Being able to filter the device list view by members of a cluster group or individual cluster would be very useful.
It would allow for mass updating devices based on their clusters.

### Database changes

N/A

### External dependencies

N/A

**Comment by Julio-Oliveira-Encora** [comment]
Could you please assign it to me?
