### ISSUE TITLE
Inconsistency Swagger schema vs API (model Interface)

### ISSUE THREAD

**Issue by janhlavin** [netbox-community/netbox#16423]
### Deployment Type

Self-hosted

### NetBox Version

v4.0.3

### Python Version

3.11

### Steps to Reproduce

1. create Manufacturer, Device type, Device role, Site and Device+Interface
2. call GET to /api/dcim/interfaces/$InterfaceID/

### Expected Behavior

return property "device" as "model.NestedDevice" in Swagger schema

### Observed Behavior

by Swagger schema object type of "device" is "model.Device", but API return "model.NestedDevice"

**Comment by Julio-Oliveira-Encora** [comment]
Could you please assign it to me?

**Comment by arthanson** [comment]
I think this is related to #16670

**Comment by arthanson** [comment]
closing as dupe of #16670
