### ISSUE TITLE
add a human readable summary column to `updated` changelogs

### ISSUE THREAD

**Issue by ITJamie** [netbox-community/netbox#16428]
### NetBox version

v4.0.3

### Feature type

Data model extension

### Proposed functionality

Addition of a read-only text field containing an autogenerated string of a high-level list of changes in that changelog.
examples of summarys:
- `Name and Custom field X,Y & Z updated`
- `Primary IP assigned`
- `Name Updated, OOB IP assigned`
- `Tags removed`

### Use case

when looking at an object with a large list of `updated` changelogs it can take a while to track down the specific change you're looking for.
Having a quick `summary` text field that had a human-readable list of high-level changes that happened in that update would be fantastic to limit the amount of individual changelogs you need to look at when trying to find a specific change event

This was flagged to me by a staff member who pointed out that the change-logs in our old system(racktables) had a summary view of what fields changed in a changelog event which made it easier to track down a specific change without looking through potentially hundreds of `updated` changelog entrys on an object

### Database changes

a text field to store the "summary" if we choose to store the value rather than generate on the fly

### External dependencies

N/A

**Comment by jeffgdotorg** [comment]
I'd like to understand the comparative use case a little better. Could you please link me to a place in the [racktables demo](https://demo.racktables.org/) where I can see the feature that inspired this FR? I spent a few minutes looking for it, but it's eluding me.

**Comment by ITJamie** [comment]
apologies. it turns out that the extra log items were a custom extension in racktables that a previous staff member had made rather than a native function of racktables.
it is still quite a useful feature request to have a quick summary of the fileld names where the value changed on each change request.
