### ISSUE TITLE
pt_BR translation - help offer

### ISSUE THREAD

**Issue by gabrielat** [netbox-community/netbox#16436]
### Language

Brazillian Portuguese

### ISO 639-1 code

pt

### Volunteer

Yes

### Comments

Hello. I'm from Brazil and I'd like to offer help with brazillian portuguese translations.

**Comment by jeffgdotorg** [comment]
Thanks for your patience – we've sorted out most aspects of the GitHub / Transifex integration, but the flow of work for locale-specific translations is still on our TODO list.
