### ISSUE TITLE
Tracing only works on the first occupied position on a splitter with 2 rear positions with 2 front ports mapped

### ISSUE THREAD

**Issue by royanl** [netbox-community/netbox#16442]
### Deployment Type

Self-hosted

### NetBox Version

v4.0.2

### Python Version

3.10

### Steps to Reproduce

1. create device (splitter)
2. add rear port with positions: 2
3. add 2 front ports
4. map the first front port to position 1 of the rear port
5. map the second front port to position 2 of the rear port
6. create multiple extra devices with some interfaces.
7. link 1 device port to the first front port of the splitter
8. link 1 device port to the second port of the splitter
9. link 1 device port to the rear port of the splitter
10. navigate to the the splitter 'Front Ports'
11. Click on the trace button of the first front port, you will get a result
12. Do the same by clicking on the trace port of the second front port, no result.
13. Also when navigating to the 'Rear Ports' of the splitter an doing a trace on the rear port, it only shows a trace what is linked to the first front port of the splitter.

### Expected Behavior

Atleast showing the trace of second, third, fourth etc. port of a multiple positions rear port.
When doing a trace the other way around, you get a Splitted trace shown with the ports that are included in the split.

### Observed Behavior

Traces on multiple position rear ports only work on the first occupied position.

**Comment by jeffgdotorg** [comment]
Thanks for reporting a problem you've encountered in NetBox.

I'm unable to reproduce the reported problem on a freshly installed NetBox 4.0.5 instance. The trace from the second front port works as expected (see first screenshot) and a split-path indication when tracing from the rear port.

![image](https://github.com/netbox-community/netbox/assets/1209268/f8c67d65-8cda-4507-ade5-5d11e6507ec1)
![image](https://github.com/netbox-community/netbox/assets/1209268/69459f35-9611-4fae-8727-4af64477c5f1)

Please see if you're able to reproduce with v4.0.5 and update accordingly.

**Comment by royanl** [comment]
@jeffgdotorg It works after upgrading to 4.0.5 and creating the traces all over again, issue solved, thanks.
