### ISSUE TITLE
No maxlength attribute on input fields for GPS coordinates

### ISSUE THREAD

**Issue by RasmusThing** [netbox-community/netbox#16451]
### Deployment Type

Self-hosted

### NetBox Version

v4.0.5

### Python Version

3.11

### Steps to Reproduce

When entering latitude and longitude for a site object in NetBox, there is no max length on the input fields.
This shows an error when entering coordinates longer than what is permitted in NetBox.

<img width="728" alt="image" src="https://github.com/netbox-community/netbox/assets/11932377/97e5f918-d67b-4e76-b012-7a84ae3c557e">

### Expected Behavior

For a better user experience, both input fields should have a maxlength attribute added to automatically cut off the excessive decimals.
<img width="728" alt="image" src="https://github.com/netbox-community/netbox/assets/11932377/5874ce6c-b0a5-4a86-a850-4934fdb14edf">

### Observed Behavior

When entering GPS coordinates for a site object in NetBox that are longer than whats permitted, an error is shown instead of cutting off the coordinates automatically.

**Comment by Julio-Oliveira-Encora** [comment]
Could you please assign it to me?

**Comment by arthanson** [comment]
I don't think this is fixable as-is, as the decimalfield uses NumberInput and in current HTML, there is no support for the size and maxlength attributes for the number input field.  @RasmusThing I will close this, can you please open a feature request if you still desire this as it isn't a bug per-se and would require a custom input widget.
