### ISSUE TITLE
"Map"-button on site addresses with multiple lines is extended

### ISSUE THREAD

**Issue by RasmusThing** [netbox-community/netbox#16452]
### Deployment Type

Self-hosted

### NetBox Version

v4.0.5

### Python Version

3.11

### Steps to Reproduce

When an address is added to a site object in NetBox and the address contains new lines, the **Map** button is messed up.

### Expected Behavior

In NetBox pre-version 4, the button height was normalized and in center.
<img width="690" alt="image" src="https://github.com/netbox-community/netbox/assets/11932377/a9a5283a-c776-4086-a879-0743358b9e08">

### Observed Behavior

Button height is extended and the text is not in center.
<img width="690" alt="image" src="https://github.com/netbox-community/netbox/assets/11932377/53f8db81-e3e9-4d7d-bb4a-6d874e01669f">

**Comment by jbakklund** [comment]
The 'Map' button for GPS coordinates is still bigger than the other buttons in this view. It would look more consistent if this button also used the "btn-sm" class.

**Comment by goteamkor** [comment]
> The 'Map' button for GPS coordinates is still bigger than the other buttons in this view. It would look more consistent if this button also used the "btn-sm" class.

https://github.com/netbox-community/netbox/issues/17353
