### ISSUE TITLE
django.po files have unclear copyright and license statements

### ISSUE THREAD

**Issue by koratfood** [netbox-community/netbox#16459]
### Deployment Type

Self-hosted

### NetBox Version

v4.0.5

### Python Version

3.12

### Steps to Reproduce

cd /opt/netbox
grep -e '^# Copyright' -e '^# .\+license' netbox/translations/*/LC_MESSAGES/django.po

### Expected Behavior

All PO files state how they are licensed (or at least refer to NetBox instead of a placeholder value), and to whom the copyright belongs.

### Observed Behavior

netbox/translations/de/LC_MESSAGES/django.po:# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
netbox/translations/de/LC_MESSAGES/django.po:# This file is distributed under the same license as the PACKAGE package.
netbox/translations/en/LC_MESSAGES/django.po:# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
netbox/translations/en/LC_MESSAGES/django.po:# This file is distributed under the same license as the PACKAGE package.
netbox/translations/es/LC_MESSAGES/django.po:# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
netbox/translations/es/LC_MESSAGES/django.po:# This file is distributed under the same license as the PACKAGE package.
netbox/translations/fr/LC_MESSAGES/django.po:# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
netbox/translations/fr/LC_MESSAGES/django.po:# This file is distributed under the same license as the PACKAGE package.
netbox/translations/ja/LC_MESSAGES/django.po:# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
netbox/translations/ja/LC_MESSAGES/django.po:# This file is distributed under the same license as the PACKAGE package.
netbox/translations/pt/LC_MESSAGES/django.po:# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
netbox/translations/pt/LC_MESSAGES/django.po:# This file is distributed under the same license as the PACKAGE package.
netbox/translations/ru/LC_MESSAGES/django.po:# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
netbox/translations/ru/LC_MESSAGES/django.po:# This file is distributed under the same license as the PACKAGE package.
netbox/translations/tr/LC_MESSAGES/django.po:# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
netbox/translations/tr/LC_MESSAGES/django.po:# This file is distributed under the same license as the PACKAGE package.
netbox/translations/uk/LC_MESSAGES/django.po:# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
netbox/translations/uk/LC_MESSAGES/django.po:# This file is distributed under the same license as the PACKAGE package.
netbox/translations/zh/LC_MESSAGES/django.po:# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
netbox/translations/zh/LC_MESSAGES/django.po:# This file is distributed under the same license as the PACKAGE package.

**Comment by jeremystretch** [comment]
This is not a bug.

> This file is distributed under the same license as the PACKAGE package.

Like everything else in the project, these file are distributed under [the Apache 2.0 license](https://github.com/netbox-community/netbox/blob/develop/LICENSE.txt).

**Comment by koratfood** [comment]
Ok, how can it be reported, then? The legal ambiguity remains in your .po files, and stating their license in your reply here does not resolve it.

**Comment by jsenecal** [comment]
@koratfood They have the same licence as the package they are distributed with, AKA NetBox. 
NetBox license is [the Apache 2.0 license](https://github.com/netbox-community/netbox/blob/develop/LICENSE.txt).

There is no legal ambiguity.

**Comment by koratfood** [comment]
> @koratfood They have the same licence as the package they are distributed with, AKA NetBox. NetBox license is [the Apache 2.0 license](https://github.com/netbox-community/netbox/blob/develop/LICENSE.txt).

Great. Then it should be no problem to make this glaringly obvious in the .po files by changing "PACKAGE" to "NetBox" and either fixing or removing the placeholder copyright lines entirely.

> There is no legal ambiguity.

So long as this issue remains dismissed/ignored, there is. Stating _here_ (i.e. in this thread) what license the files are issued under does not resolve it.
