### ISSUE TITLE
Enhancements on filtering objects by date

### ISSUE THREAD

**Issue by FliesLikeABrick** [netbox-community/netbox#16509]
### NetBox version

v4.0.5

### Feature type

New functionality

### Proposed functionality

Allow for filtering dates based on greater than, less than, and/or ranges;  This would be valuable for date of creation of records, as well as date/time custom field values.

Additionally, expose "Created date" and "modified date" as fields in filters.

### Use case

While testing and documenting workflows for auditing/cleaning up date in our NetBox implementation (chiefly IPAM Prefixes and IP Addresses, but other types as well), we have continued to run into a shortcoming with the ability to provide our administrators with saved filters/queries that can let them review stale items.  For example, we can have a saved query for "Prefix with status Reserveed", but cannot do a key part such as "created before 6 months ago".

We want to perform such queries based on created date, modified date, and custom fields specific to our environment.

The only way we can do this today is by exporting large amounts of data to Excel, and filtering there; or by using the API with custom tooling which is not as accessible to our administrators/supportable in our environment.

**Comment by arthanson** [comment]
@FliesLikeABrick are you looking for something like what is in Jobs (see screenshot) and would this be for just the API or in the UI?
![Monosnap Jobs | NetBox 2024-06-11 08-37-34](https://github.com/netbox-community/netbox/assets/99642/00c88df3-4c65-463c-92de-b62106132f0f)

**Comment by jeremystretch** [comment]
> Allow for filtering dates based on greater than, less than, and/or ranges;

@FliesLikeABrick please expand your post above to detail specifically what you are proposing be added and where.

> Additionally, expose "Created date" and "modified date" as fields in filters.

This would need to be a separate FR, and again needs more detail.
