### ISSUE TITLE
Fix formatting in upgrading.md

### ISSUE THREAD

**Issue by brunosardinepi** [netbox-community/netbox#16514]
### Change Type

Cleanup (formatting, typos, etc.)

### Area

Installation/upgrade

### Proposed Changes

In the "Run the Upgrade Script" section, there are unnecessary indentions causing formatting issues on the codeblock about including Python 3.10 in the PATH variable:

![Screenshot 2024-06-11 at 7 40 22 AM](https://github.com/netbox-community/netbox/assets/22970115/e8e1211b-2de6-44d3-a282-39addc2fe54b)

Additionally, there is an unnecessary indention in the section "Clone the Git Repository". It doesn't break anything but can be cleaned up:

![Screenshot 2024-06-11 at 7 42 02 AM](https://github.com/netbox-community/netbox/assets/22970115/b7f87234-633f-48d5-a523-9405473382cf)

To resolve these issues, the unnecessary indention should be removed from both sections. I will be submitting a pull request to resolve these issues.

**Comment by jeremystretch** [comment]
You appear to be viewing the raw Markdown files via GitHub, rather than the rendered HTML documentation. I can confirm that the documentation renders correctly:

![screenshot](https://github.com/netbox-community/netbox/assets/13487278/4c2f6f75-749c-48dc-84fd-06b15b997913)
