### ISSUE TITLE
Way To Hide Blank/Empty Cards In UI When Not Used

### ISSUE THREAD

**Issue by mr1716** [netbox-community/netbox#16513]
### NetBox version

v4.0.5

### Feature type

New functionality

### Proposed functionality

Currently in the Netbox UI, when there are cards that are not found or assigned such as shown in the screenshot below, it only makes the UI more crowded. It would be nice to have some way (unsure how it would be implemented) to provide users with a way to hide or show those cards.
![Netbox Blank Cards](https://github.com/netbox-community/netbox/assets/9115680/60d87257-0bc8-40a2-8f53-e631555b7d3d)

### Use case

In instances where there are multiple blank cards, such as [Public Netbox Interfaces Example](https://demo.netbox.dev/dcim/interfaces/1723/), the page is significantly longer and harder to understand/read/use than it would and needs to be if these blank cards are not there. It would save time and make the tool easier to view.

**Comment by jeremystretch** [comment]
These cards are still shown because conveying that there are no such associated objects is still necessary information. For example, if we were to hide the tags panel when there are no tags assigned, users would likely become confused, unable to determine where to find tags for the object. We avoid this confusion by always presenting such information in a consistent manner.

**Comment by mr1716** [comment]
That makes sense. So does that mean that the system always shows cards like Custom Fields as well even if there are no custom fields? To keep the same consistency?

**Comment by jeremystretch** [comment]
Yes, any custom fields which have been defined are always displayed.

**Comment by mr1716** [comment]
> Yes, any custom fields which have been defined are always displayed.

So when custom fields are NOT defined, does that mean that the Custom Fields card does NOT show up?

**Comment by jeremystretch** [comment]
Bud you obviously can test this out yourself. I've explained why the proposed changes aren't going to be made. If you would prefer them, you're free to fork the project and make the changes yourself.

**Comment by mr1716** [comment]
@jeremystretch i understand that. But I’m letting you know that basing your decision on “this would likely confuse the users” but not have consistency in other areas, it really hurts the usability of the tool. And it looks like a design decision rather than one that’s actually been based on the user experience.

**Comment by jeremystretch** [comment]
> And it looks like a design decision rather than one that’s actually been based on the user experience.

No, it's based on eight years of experience as both a user and a maintainer, and upon interactions with thousands of other users, rather than subjective opinion.

Locking as this has been rejected.
