### ISSUE TITLE
Cannot distinguish between master and standby device of Virtual Chassis

### ISSUE THREAD

**Issue by shaderecker** [netbox-community/netbox#16523]
### Deployment Type

Self-hosted

### NetBox Version

v4.0.5

### Python Version

3.11

### Steps to Reproduce

1. Have a virtual chassis with a master and standby device.
2. Open one (or both) of the devices.
3. Check in the Virtual Chassis section of the device.
4. See that the current device isn't highlighted there.

### Expected Behavior

A visible visual distinction/highligting of the current device in the virtual chassis section

### Observed Behavior

No highlighting of the current device in the Virtual Chassis section.
This is a regression in Netbox v4.

**Comment by jeffgdotorg** [comment]
Thanks for reporting this problem. I agree it's a regression.

For the benefit of whomever picks it up, here are screenshots illustrating the highlighting in 3.7.8:
![image](https://github.com/netbox-community/netbox/assets/1209268/d918a4e3-a771-48ef-b202-aa84b862cc01)

And the lack of it in the same install upgraded to 4.0.5:
![image](https://github.com/netbox-community/netbox/assets/1209268/abb8513e-0de0-489f-8cc9-9e84eba13a2c)

 The fix may be a straightforward CSS change.
