### ISSUE TITLE
Define a `get_absolute_url()` method on NetBoxModel

### ISSUE THREAD

**Issue by jeremystretch** [netbox-community/netbox#16546]
### Proposed Changes

Add a [`get_absolute_url()`](https://docs.djangoproject.com/en/5.0/ref/models/instances/#get-absolute-url) method on NetBoxModel to dynamically return the appropriate URL based on the model's `app_label` and `model_name` Meta attributes:

```python
    def get_absolute_url(self):
        return reverse(f'{self._meta.app_label}:{model_name}', args=[self.pk])
```

### Justification

The vast majority of models in NetBox declare this method explicitly. Moving it to NetBoxModel allows us to remove boilerplate code while still permitting customization on individual models.

**Comment by sleepinggenius2** [comment]
Would the proposed solution work for plugin models that inherit from NetBoxModel too? It would be nice to do away with the boilerplate there as well.

**Comment by jeremystretch** [comment]
A `get_absolute_url()` method has been added to the NetBoxFeatureSet mixin, which is used by NetBoxModel, OrganizationalModel, and NestedGroupModel.
