### ISSUE TITLE
Filter VRF on GraphQL ip_address does not filter

### ISSUE THREAD

**Issue by antoinekh** [netbox-community/netbox#16623]
### Deployment Type

Self-hosted

### NetBox Version

4.0.5

### Python Version

3.10

### Steps to Reproduce

1. Create IP addresses on multiple VRF
2. Make a graphQL request to get IP addresse on a dedicated VRF

Easy to test https://demo.netbox.dev/graphql/ as there is already IP not on dedicated VRF.

### Expected Behavior

Filter the request with the VRF name and only display

### Observed Behavior

GraphQL request 
```
query GetIP {
  ip_address_list (filters: {vrf : "ABC"}){
    id
    display
    vrf {
      id
      name
    }
  }
}
```

I also tried with 
```
query GetIP {
  ip_address_list (filters: {vrf :{name:{contains: "ABC"}}}){
    id
    display
    vrf {
      id
      name
    }
  }
}
```

But this seems not supported:

```
{
  "data": null,
  "errors": [
    {
      "message": "String cannot represent a non string value: {name: {contains: \"ABC\"}}",
      "locations": [
        {
          "line": 2,
          "column": 35
        }
      ]
    }
  ]
}
```

**Comment by jeremystretch** [comment]
The `vrf` filter references the VRF's [route distinguisher](https://netboxlabs.com/docs/netbox/en/stable/models/ipam/vrf/#route-distinguisher) value, not its name.
