### ISSUE TITLE
README contains old link

### ISSUE THREAD

**Issue by AliMickey** [netbox-community/netbox#16621]
### Change Type

Cleanup (formatting, typos, etc.)

### Area

Other

### Proposed Changes

README.md

https://github.com/netbox-community/netbox?tab=readme-ov-file#project-stats

The above hyperlink is found at the top of the file that does not link to anywhere on the page, most likely an old link from when there used to be stats referenced.

**Comment by jeffgdotorg** [comment]
Thanks for spotting this problem; the section in question was removed about a month ago. I'll remove the dead link.
