### ISSUE TITLE
Allow nat ip addresses to be filled with bulk import

### ISSUE THREAD

**Issue by dhoffend** [netbox-community/netbox#16646]
### NetBox version

v4.0.5

### Feature type

New functionality

### Proposed functionality

Allow nat ip address fields in the bulk import dialog.

### Use case

We're trying to migrate a bigger number of ip addresses with static nat translations into the netbox. The current bulk csv import header fields don't allow those fields to be imported.

**Comment by peteeckel** [comment]
This is not as trivial as it seems at first, I'm afraid.

I see two options to implement this:
* Using the `pk` of the referenced `nat_inside` address object (unambiguous, but not very user-friendly)
* Using the `address` of the referenced `nat_inside` address object (might be ambiguous or even wrong in some cases, e.g. if there is an object with the specified `address`, but not in the correct VRF).

Any ideas on how to best solve this? I'm afraid the only safe implementation is the one using `pk`.
