### ISSUE TITLE
Ability to filter by "Contact in Devices table"

### ISSUE THREAD

**Issue by ILcampfire** [netbox-community/netbox#16641]
### NetBox version

v4.0.5

### Feature type

New functionality

### Proposed functionality

Add the ability to filter the devices table by contacts. 

### Use case

Add the ability to filter the devices table by contacts. 

### Database changes

No change to database expected

### External dependencies

None

**Comment by jeffgdotorg** [comment]
Thanks for your interest in helping improve NetBox.

The described feature already exists. The following screenshot is taken from a v4.0.5 system in which device `rdu01-splitter01` is assigned to contact `ILCampfire` and device `rdu01-sw01` is assigned to contact `jeffgdotorg`. I filtered the devices list to include both contacts. The remaining device inventory is not assigned to any contact, and is correctly excluded from the list.

**Comment by jeffgdotorg** [comment]
Requested functionality already implemented.

**Comment by ILcampfire** [comment]
It's not working even on the demo site:
![netbox contacts](https://github.com/netbox-community/netbox/assets/169136302/e6804371-4f6e-4be9-b62a-d089a169a7c4)
