### ISSUE TITLE
Missing parent in inventory item when using bulk/csv import

### ISSUE THREAD

**Issue by siku4** [netbox-community/netbox#16654]
### Deployment Type

Self-hosted

### NetBox Version

v4.0.5

### Python Version

3.10

### Steps to Reproduce

1. Open Inventory items
2. Click on import button
3. Enter test data set, make sure that the parent inventory item already exists:
```csv
device,name,parent
test_device,test_child_inventory_item,test_parent_inventory_item
```
4. Click on submit
5. Open the new inventory item `test_child_inventory_item`

### Expected Behavior

The parent inventory item `test_parent_inventory_item` is present or referenced within the child inventory item just created.

### Observed Behavior

The parent item field is empty

**Comment by siku4** [comment]
I have already identified the problem and would like to create a PR

**Comment by siku4** [comment]
@jeremystretch Could you please assign it to me?

**Comment by jeremystretch** [comment]
@siku4 yes, sorry I missed your comment above. Thanks!
