### ISSUE TITLE
Mismatch of parameters in OpenAPI schema and actual Netbox API (for POST /api/ipam/prefixes/{id}/available-prefixes/ endpoint)

### ISSUE THREAD

**Issue by Emreu** [netbox-community/netbox#16652]
### Change Type

Correction

### Area

Integrations/API

### Proposed Changes

Problem with endpoint: [POST /api/ipam/prefixes/{id}/available-prefixes/](https://demo.netbox.dev/api/schema/swagger-ui/#/ipam/ipam_prefixes_available_prefixes_create)
Right now in **PrefixRequest** model required field is _"prefix"_ which is actually ignored by API, however API requires _"prefix_length"_ field which is absent in the model.
Since API client libraries are generated from OpenAPI spec this mismatch makes them hard to use (if ever usable for specific endpoint).
I use [go client]( https://github.com/netbox-community/go-netbox) which allows to add custom fields to request, but its quite an unpleasant workaround. I don't have enough skill with python and django to provide fix myself so relying this problem to community.

**Comment by jeffgdotorg** [comment]
Thanks for reporting this problem. We're aware that this kind of mismatch is not uncommon, but the team's current capacity does not permit us to make a major push to address the problem at its root.

Moving along to `needs owner`; anybody who has the requisite skills and capacity is welcome to pick it up and work through to a PR. Just comment on the issue expressing your interest, and a maintainer will assign the issue to you.
