### ISSUE TITLE
Search: Object type(s) ignore user language settings

### ISSUE THREAD

**Issue by stavr666** [netbox-community/netbox#16657]
### Deployment Type

Self-hosted

### NetBox Version

v4.0.3

### Python Version

3.11

### Steps to Reproduce

1. Enter anything in searchbox
2. Open "Object type(s) selector

### Expected Behavior

Types must be in same language, as all other UI elements.

### Observed Behavior

Types for some reason in Russian:
![image](https://github.com/netbox-community/netbox/assets/84839985/e250bf3e-cd22-4451-8b8a-a59a1294861f)

Browser settings:
![image](https://github.com/netbox-community/netbox/assets/84839985/7dbdb322-b230-400b-968a-51d486a647cd)
App's User Preferences:
![image](https://github.com/netbox-community/netbox/assets/84839985/4b78b2b9-3bde-42d2-acec-576835e80d9d)

**Comment by Julio-Oliveira-Encora** [comment]
Could you please assign it to me?
