### ISSUE TITLE
Use ngettext for strings with count

### ISSUE THREAD

**Issue by afranke** [netbox-community/netbox#16660]
### Proposed Changes

`netbox/dcim/views.py` has  `_("Disconnected {count} {type}")` where `count` is as far as I can tell an arbitrary number and `type` a pre-baked plural. This cannot be properly translated in some languages, because plurals don’t work the same way as they do in English.

You need to:

1. use [`ngettext`](https://docs.djangoproject.com/en/5.0/topics/i18n/translation/#pluralization) for the count part, so plural forms can be handled properly.
2. use one full string per type, because that’s the only way nouns can be declined as necessary.

This would result in something along the lines of

```
…
ngettext("Disconnected 1 device", "Disconnected {count} devices", count)
…
ngettext("Disconnected 1 client", "Disconnected {count} clients", count)
…
```

with something like a switch-case to match a given type with a given ngettext call.

Sorry for using client and device instead of actual types, I couldn’t easily find the type list.

### Justification

You shouldn’t make up your own plural handling. There are tools for that, and good reasons to use them.

See #16659 for a similar but different situation.

**Comment by afranke** [comment]
I only mentioned one string because it’s the one I could find, but there may be other ones that are affected by this issue.

**Comment by afranke** [comment]
And of course right after I post that comment, I find more:

* `netbox/virtualization/models/clusters.py` has `"{count} devices are assigned as hosts for this cluster but are not in site {site}"`
* `netbox/utilities/error_handlers.py` has `"Unable to delete <strong>{objects}</strong>. {count} dependent objects were found: "`
* `netbox/utilities/forms/utils.py` has `"Row {row}: Expected {count_expected} columns but found {count_found}"`
* `netbox/dcim/models/device_component_templates.py` has `"Invalid rear port position ({position}); rear port {name} has only {count} positions"`

I may still be missing some more.

**Comment by afranke** [comment]
I’m sorry but I won’t be able to. I can review a PR to check if it’s doing the right thing from an i18n perspective though.

**Comment by Julio-Oliveira-Encora** [comment]
Could you please assign it to me?

**Comment by arthanson** [comment]
@afranke In this case In netbox/dcim/views.py if we used the line:
```
                messages.success(request, _(ngettext(
                    "Disconnected 1 {type}",
                    "Disconnected {count} {type_plural}",
                    count,
                )).format(
                    count=count,
                    type=self.queryset.model._meta.verbose_name,
                    type_plural=self.queryset.model._meta.verbose_name_plural
                ))
```
Would that work for pluralization as you mentioned for Polish?  We just have the singular and pluralized model name.

**Comment by afranke** [comment]
No, it wouldn’t work. See point 2 in the issue description.

**Comment by arthanson** [comment]
Putting this back in the backlog - more research needs to be done on a viable solution as it's probably not viable to create a separate string per type there.

**Comment by afranke** [comment]
Let me try one more time, and add a bit more context. First of all, I am neither a user nor a translator for your software. I am a free software translator, both as a volunteer and professionally, with twenty years of experience, including as an internationalisation coordinator for GNOME. A friend of mine uses your software and told me about it. Out of curiosity, I looked into the quality of your translations, because that’s something I do: sharing my expertise with smaller projects who aren’t lucky enough to have someone with the necessary knowledge, in order to improve the commons. That is not to say that you should blindly trust me, but hopefully it helps you understand where I’m coming from and indeed trust me a bit more.

> Putting this back in the backlog - more research needs to be done on a viable solution as it's probably not viable to create a separate string per type there.

But it is the one correct way to do this. You shouldn’t be worried about adding a dozen more strings (which is peanuts compared to the 3k+ strings you already have). You should be worried about doing things correctly so translators can effectively do their work.
