### ISSUE TITLE
Full definitons of swagger responses are possibly being replaced with brief definitions due to nested serializers

### ISSUE THREAD

**Issue by deathbeam** [netbox-community/netbox#16670]
### Deployment Type

Self-hosted

### NetBox Version

v4.0.3

### Python Version

3.11

### Steps to Reproduce

Check swagger JSON, all model representations of responses are only using `brief` definitions.

### Expected Behavior

Swagger responses should `always` match real responses.

### Observed Behavior

Brief representations are being returned, making it effectivelly impossible to use the swagger json.

**Comment by deathbeam** [comment]
As a side note, most likely caused by this change https://github.com/netbox-community/netbox/pull/15281 by @jeremystretch as im assuming that the generated model response is simply being replaced with nested definition of the same name.

**Comment by arthanson** [comment]
What's happening is the nested=True serializer is getting instantiated first and it looks like Spectacular is caching the fields from this call and using that.  So it is hit or miss depending if the full serializer or the nested serializer is getting hit first.
