### ISSUE TITLE
Utilization of parent range not correct, if sub-range marked as marked utilized

### ISSUE THREAD

**Issue by blindzero** [netbox-community/netbox#16678]
### Deployment Type

Self-hosted

### NetBox Version

v4.0.5

### Python Version

3.12

### Steps to Reproduce

1. Create an IP Range with prefix-mask `/23`
2. Create an sub IP Range within the parent range with prefix-mask `/24`
3. Mark sub IP range as "is utilized"
4. Go to ranges overview 

### Expected Behavior

Mark 50% of parent-range as marked.

The use-case is following:
* sub-range is a "self-service" range we do not manage or control at all --> is utilized --> 100% used (from our perspective).
* parent-range can only be used 50% from our perspective

### Observed Behavior

-> parent IP ragne is utilized 0%, while sub-range is 100%

![image](https://github.com/netbox-community/netbox/assets/13959569/770c1564-d489-4968-990f-3bc390ee4eab)

**Comment by Chiniquy** [comment]
Have you tried putting the parent prefix as "Container"?

**Comment by jeremystretch** [comment]
Your reproduction steps indicate the creation of IP ranges, but your screenshot shows prefixes; these are two very different types of records. Please revise your issue to clearly indicate the steps your are taking to reproduce the reported behavior.

**Comment by blindzero** [comment]
Sorry, I meant the paar in the Prefixes, filled by the ranges.
It seems that the bar is now updated. Is that maybe some asynchronous housekeeping job?

**Comment by jeremystretch** [comment]
> Is that maybe some asynchronous housekeeping job?

No, the utilization is calculated live.
