### ISSUE TITLE
"Current Configuration" of /core/system/ does not take configuration file into account

### ISSUE THREAD

**Issue by mrtn-r** [netbox-community/netbox#16689]
### Deployment Type

Self-hosted

### NetBox Version

v4.0.5

### Python Version

3.11

### Steps to Reproduce

1. Set up a netbox instance.
2. Change some value via the configuration.py, e.g. the login banner

### Expected Behavior

Expect the changes in the config file to affect the "Current Configuration" part of NETBOXURL/core/system/

### Observed Behavior

Changes are not displayed and the default values are used.
However when creating a new config revision and changing exactly nothing, the config file is parsed

**Comment by mrtn-r** [comment]
Here's a video because maybe my wording isn't clear enough: 

https://github.com/netbox-community/netbox/assets/153684711/c054ee03-b413-4b5a-a009-8f16689e2e75

**Comment by jeremystretch** [comment]
Thank you for opening a bug report. I was unable to reproduce the reported behavior on NetBox v4.0.5. Please re-confirm the reported behavior on the current stable release and adjust your post above as necessary. Remember to provide detailed steps that someone else can follow using a clean installation of NetBox to reproduce the issue. Remember to include the steps taken to create any initial objects or other data.

**Comment by azuercher** [comment]
Hello,
I think I may be seeing similar issue on 4.0.5.    I upgraded from 3.7.1.   I noticed that netbox is not using my local timezone so I was investigating the issue and it lead me to this report.

I checked configuration.py and it has the timezone set same as previous version (configuration.py was copied during upgrade).   If I look at Admin > System is shows my system time is correct:
![image](https://github.com/netbox-community/netbox/assets/1099965/a7c1ae77-f0bc-4a2a-bdcb-29e39fe21613)


However when updating or editing an object the time displayed is UTC:

![image](https://github.com/netbox-community/netbox/assets/1099965/7f8ab09f-a156-49ec-b400-28f44d06ae8c)


Additionally, I noticed my configuration.py has 
PREFER_IPV4 = True

but in the Admin > System is shows off.
![image](https://github.com/netbox-community/netbox/assets/1099965/c5da0c11-3190-4594-b864-8330aa87c52b)


Thanks

**Comment by tobiasge** [comment]
I can see the same issue with our installation on v4.0.6. In my `configuration.py` I have set `CHANGELOG_RETENTION = 0`. When I navigate to `/core/config-revisions/add/` The field for the changelog retention is correctly greyed out and the value is 0. Looking at `/core/system/` the value is displayed as 90 (the default I think).
