### ISSUE TITLE
Creating Dual Personality Port Types In Interface Templates 

### ISSUE THREAD

**Issue by Theyouth1** [netbox-community/netbox#16695]
### NetBox version

v4.0.5

### Feature type

Data model extension

### Proposed functionality

Hi Netbox Community,

I have come across a few devices which utilize a dual personality port but have found there is no good way to list these interfaces under the currently available interfaces types.

I would like to suggest another category under the ethernet section much like the "ethernet (fixed)" and "ethernet (modular)" sections. I would suggest "ethernet (Dual Personality)" as the section header and each interface type under this section could be labelled:
1000BASE-T or SFP
10GBASE-T or SFP+
as a few examples

### Use case

Currently users have to rely on using the description when using the interface template to let other users know if an interface is dual personality. 

From adding a dual personality interface section and related types, users could clearly label a port as dual personality with out having to rely on the description. Meaning data could be more accurately and consistently be recorded as types is a required field when using the template.

### Database changes

I apologise but I am not sure if this would require changes to the data schema. I would imagine it will require new entries to the existing interface types database. But I don't believe it will require any new tables. Apologies if I am incorrect about this.

### External dependencies

No new external dependencies would be required for this.

**Comment by jeremystretch** [comment]
This has been proposed in the past and no workable solution has been achieved. The physical state of an interface cannot be ambiguous; it **must** be one type or another. The recommended practice is to define the interface using whichever physical type is in use, as that most accurately reflects reality.
