### ISSUE TITLE
Define a default `help_text` for ColorField

### ISSUE THREAD

**Issue by jeremystretch** [netbox-community/netbox#16704]
### Proposed Changes

Set a default `help_text` value on the ColorField model/form field.

### Justification

There are many places where we currently define a help text for these fields as

```
mark_safe(_('RGB color in hexadecimal. Example:') + ' <code>00ff00</code>')
```

Creating a a reusable form field for these will eliminate this redundant code.

**Comment by Julio-Oliveira-Encora** [comment]
Could you please assign it to me?
