### ISSUE TITLE
Device Roles in Device Types

### ISSUE THREAD

**Issue by LHBL2003** [netbox-community/netbox#16718]
### NetBox version

v4.0.3

### Feature type

Data model extension

### Proposed functionality

Add the Device Roles field as optional in Device Types 

![image](https://github.com/netbox-community/netbox/assets/46369917/ddf02c23-76ba-4bd6-9f76-dad31178d94f)

and enable the enumeration in the Device Roles properties under "Related Objects".
![image](https://github.com/netbox-community/netbox/assets/46369917/5ce53f7d-d8c5-4da4-a388-cd31151bf331)

The number should then also be listed in the Device Roles area.
![image](https://github.com/netbox-community/netbox/assets/46369917/7a1bf751-6552-45f5-aea3-6d4cbd9c22b5)

### Use case

In Netbox, we maintain the device roles for the devices and VMs. These are often designations such as firewall, printer, fax, access point, etc. Most roles are hardware-specific. We would also like to reuse the device roles in the Device Types area. At the moment, we have solved this by using a TAG with the same name or by creating a customer field. However, after clicking on the link under "Related Objects" in the Customer Field, the Device Types area is not displayed, which is not so nice.

We would therefore prefer a proper integration of the Device Role field. Or the adjustment that the Device Types are also listed under Related Objects.

**Comment by jeremystretch** [comment]
> Add the Device Roles field as optional in Device Types

This would not make sense as there is no consistent correlation between a device type and role: A single device type may function in one of several different roles depending on how it is deployed. For example, a single model of switch might be used as either a core, distribution, or access switch; a particular router might be used in the backbone or at the edge.

> and enable the enumeration in the Device Roles properties under "Related Objects".

It might be feasible to include statistics about the number of roles in which each device type has been deployed without altering the current model. Is this what you're after?

**Comment by sleepinggenius2** [comment]
I just added this as a multi-object custom field on Device Types within our environment, so that it can be used within a custom validator and for filtering. To @jeremystretch's point, a single model can generally have multiple roles, which is why we implemented it as a multi-object field. It would be nice to integrate that functionality into the core, but so far the custom configuration seems to be working in our environment.

**Comment by LHBL2003** [comment]
> This would not make sense as there is no consistent correlation between a device type and role: A single device type may function in one of several different roles depending on how it is deployed. For example, a single model of switch might be used as either a core, distribution, or access switch; a particular router might be used in the backbone or at the edge.

At first I didn't understand why you didn't think it made sense. Until I understood your point of view. :D In a nutshell: The device role on the device type is primarily used to group the device types, as the device roles are 90% identical to those of the device instances. Of course, it would also be nice if the stored device role were proposed as a template when a device instance is created, as it can be changed when it is created if necessary. But I hadn't thought that far ahead, as the device role should primarily be used to group the device types.

![image](https://github.com/netbox-community/netbox/assets/46369917/8eba7fd6-49d1-4352-97e7-ea3a581216ab)

As with the VMs, you could also create a checkbox for the device roles so that the device role is displayed or not displayed for the device types. 
![image](https://github.com/netbox-community/netbox/assets/46369917/128e188c-8623-4523-8514-f2174840047e)

So if I want to filter how many models of managed switches we have, I have to create a TAG parallel to the device role or implement the device role as a customer field. 

Disadvantage A: No coloring as with device instances and VMs
![image](https://github.com/netbox-community/netbox/assets/46369917/795f015b-071c-4217-8a28-34a8a69f0ab2)


> and enable the enumeration in the Device Roles properties under "Related Objects".

Disadvantage B: After clicking, the "Switch l LAN Managed (SW)" Link. Missing information on how many device types have this role.
![image](https://github.com/netbox-community/netbox/assets/46369917/18c11b41-f12a-4d25-b311-ccebd602e334)
