### ISSUE TITLE
Add NAT outside address for out-of-band IP in GUI on device page

### ISSUE THREAD

**Issue by ziggekatten** [netbox-community/netbox#16716]
### NetBox version

v4.0.6

### Feature type

Change to existing functionality

### Proposed functionality

Make it as easy to see the NAT address for a device's out-of-band IP as it is to see the NAT address of the device's primary IP
![image](https://github.com/netbox-community/netbox/assets/1209268/0bce408a-3c86-455f-a66a-f834246d663d)

### Use case

Simple time-saving feature for users who also do NAT on iDRAC/LOM OOB, it would make life easier for technicians to just copy the IP directly when looking at an device without having to click on the IP.

### Database changes

None

### External dependencies

None

**Comment by jeffgdotorg** [comment]
Thanks for your interest in helping improve NetBox. This idea should be quick and simple to implement, and as you say, it ought to be a time-saver for a decent number of users.

I've made some edits to your issue body to improve ease of understanding for a prospective implementor who might not be familiar with the UI that would need enhancing. I'm moving the issue along to `needs owner` status. If you or another developer with the requisite skills and capacity would like to work it through to a PR, please say so and a maintainer will assign the issue to you.

**Comment by jeremystretch** [comment]
@RobertH1993 could you please leave a comment here so the issue can be assigned to you?

**Comment by RobertH1993** [comment]
> @RobertH1993 could you please leave a comment here so the issue can be assigned to you?

Yes!
