### ISSUE TITLE
Cloning DeviceType with 0U height doesn't work

### ISSUE THREAD

**Issue by llamafilm** [netbox-community/netbox#16714]
### Deployment Type

NetBox Cloud

### NetBox Version

v4.0.5

### Python Version

3.12

### Steps to Reproduce

1. Import any Device Type with 0U height ([example](https://github.com/netbox-community/devicetype-library/blob/4b7eb415fb14aa35fe7c00d77fcdd20c47e3b88b/device-types/HPE/t740.yaml))
2. Clone it

### Expected Behavior

The mandatory `height` field should be pre-filled with the number 0.

### Observed Behavior

The `height` field is blank.

The Clone button URL is missing the number: `https://localhost/dcim/device-types/add/?manufacturer=173&u_height=&is_full_depth=&airflow=right-to-left&weight=2.93&weight_unit=lb`

**Comment by jeffgdotorg** [comment]
Thanks for the report @llamafilm. I've reproduced it in a fresh NetBox 4.0.6 instance and confirmed that hacking the `a.href` of the Clone button element to include `u_height=0.0` results in the value carrying over to the Add form.

Moving along to `needs owner` status. If you or anybody else with the requisite skills and capacity would like to work it through to a PR, just chime in and a maintainer will assign the issue to you.

**Comment by llamafilm** [comment]
Looks like just one line, I can fix it
