### ISSUE TITLE
Missing fields in openapi Rack and Site schemas

### ISSUE THREAD

**Issue by grimurd** [netbox-community/netbox#16719]
### Deployment Type

Self-hosted

### NetBox Version

v4.0.6

### Python Version

3.12

### Steps to Reproduce

Make a request to  /api/dcim/racks/{id} or /api/dcim/sites/{id} and compare it to the respective openapi schemas

### Expected Behavior

Schema and response should be the same

### Observed Behavior

Rack and Site schema and response are wildly different, schemas are missing most fields from the response

**Comment by arthanson** [comment]
This is a dupe of #16670, closing.
