### ISSUE TITLE
The admin section should always come last in the navigation menu

### ISSUE THREAD

**Issue by jeremystretch** [netbox-community/netbox#16725]
### NetBox version

v4.0.6

### Feature type

Change to existing functionality

### Proposed functionality

Tweak the navigation menu logic to ensure that the admin section always comes last, after any installed plugins.

### Use case

This approach provides more consistency and feels more natural, as most users will probably utilize plugins more frequently than administrative functions.

### Database changes

None

### External dependencies

None

**Comment by Julio-Oliveira-Encora** [comment]
Could you please assign it to me?
