### ISSUE TITLE
Upgrade script installs venv in wrong directory if pwd-returned directory contains spaces

### ISSUE THREAD

**Issue by prryplatypus** [netbox-community/netbox#16723]
### Deployment Type

Self-hosted

### NetBox Version

v2.9.1

### Python Version

3.11

### Steps to Reproduce

1. Clone netbox into a directory with spaces (e.g.: `~/Documents/Some Folder/Repos/netbox`)
2. Follow the installation instructions

### Expected Behavior

The `upgrade.sh` script creates the venv in `~/Documents/Some Folder/Repos/netbox/venv` and completes successfully.

### Observed Behavior

The `upgrade.sh` script creates the venv in `~/Documents/Some` and the script fails.

**Comment by prryplatypus** [comment]
As a potential fix: escape spaces in the `VIRTUALENV` variable using something like: `printf "%q/venv\n" "$(pwd -P)"`

**Comment by prryplatypus** [comment]
Small snippet that might be useful for escaping spaces: `printf "%q/venv\n" "$(pwd -P)"`

**Comment by RangerRick** [comment]
it's actually being called in an `eval` so it needs double-quoting... should be able to quote anywhere `eval` is called, and then also quote any arguments inside that are dynamic, eg, replace:

```bash
# Create a new virtual environment
COMMAND="${PYTHON} -m venv ${VIRTUALENV}"
echo "Creating a new virtual environment at ${VIRTUALENV}..."
eval $COMMAND || {
```
...with:
```bash
# Create a new virtual environment
COMMAND="${PYTHON} -m venv \"${VIRTUALENV}\""
echo "Creating a new virtual environment at ${VIRTUALENV}..."
eval "$COMMAND" || {
```

Might be worth adding `shellcheck` to the CI/CD pipeline to catch stuff like this.

**Comment by prryplatypus** [comment]
I can open a PR to fix this later today

**Comment by jeremystretch** [comment]
Thanks @prryplatypus, I've assigned this to you.
