### ISSUE TITLE
Empty object list does not show object count in "results" tab

### ISSUE THREAD

**Issue by jeremystretch** [netbox-community/netbox#16735]
### Deployment Type

Self-hosted

### NetBox Version

v4.0.6

### Python Version

3.10

### Steps to Reproduce

1. View an empty object list

### Expected Behavior

The "results" tab at top should show either a count of zero or no badge.

### Observed Behavior

An empty badge (which renders as a dot) is displayed:

![screenshot](https://github.com/netbox-community/netbox/assets/13487278/228f21fe-8f1c-4b78-aadb-dbea6ff45951)

This is a regression introduced under #16252.

**Comment by Julio-Oliveira-Encora** [comment]
Could you please assign it to me?
