### ISSUE TITLE
editing selection of devices via quick search 

### ISSUE THREAD

**Issue by GeertReijnders** [netbox-community/netbox#16733]
### Deployment Type

Self-hosted

### NetBox Version

v4.0.5

### Python Version

3.12

### Steps to Reproduce

1. Click on devices
2. type your searchwords in quick search
3. click Select all ... devices matching query
![image](https://github.com/netbox-community/netbox/assets/30795671/a17684c5-03bc-43f3-a829-8d45673b68fc)

4. click edit selected devices
5. At the left upper corner you will see another amount of devices which are going to be edited. In the selected devices tab you will see other devices selected than you searched for.
![image](https://github.com/netbox-community/netbox/assets/30795671/e910ec92-f344-43b2-8b10-d6999c320228)

### Expected Behavior

I would expect that only the devices I searched for should be edited.

### Observed Behavior

All devices were selected.

**Comment by jeremystretch** [comment]
The bulk form target URL needs to be updated when the quicksearch value is updated, to ensure that `?q=foo` is passed along as a query parameter to the bulk edit/delete view.

**Comment by Julio-Oliveira-Encora** [comment]
Could you please assign it to me?

**Comment by arthanson** [comment]
Issue is in object_list.html the bulk-edit buttons are outside the table htmx so request.GET is the original page params and not from the htmx updates.

**Comment by talbers-ocient** [comment]
Just ran into this. Nice find!
