### ISSUE TITLE
Documentation regarding the removal of plugin models from the database is incomplete

### ISSUE THREAD

**Issue by peteeckel** [netbox-community/netbox#16748]
### Change Type

Addition

### Area

Administration

### Proposed Changes

https://netboxlabs.com/docs/netbox/en/stable/plugins/removal/ describes the removal of a plugin's models from the database.

What's missing however is the information how to remove a plugin's resources from the database so that it can be reinstalled at a later time. The problem is that the plugin's migrations are not deleted from `django_migrations`, so any attempt to install the plugin at a later time will fail because Django thinks that the migrations have already been executed.

The documentation should describe how to remove the migration entries from `django_migrations` as well.

**Comment by peteeckel** [comment]
Hi @arthanson. You can assign that one to me as well. It's just two sentences in the docs.

**Comment by arthanson** [comment]
@peteeckel done. Thank you.
