### ISSUE TITLE
htmx navigation - assign ip flow - odd rendering

### ISSUE THREAD

**Issue by ITJamie** [netbox-community/netbox#16757]
### Deployment Type

On prem

### NetBox Version

v4.0.6

### Python Version

3.11

### Steps to Reproduce

1. enable htmx navigation on user
2. goto ipam > ip addresses, create an ip
3. create a device
4. create an interface on that device
5. on the interfaces list view, press the + button and choose to add an IP address
6. choose assign IP tab on top left
7. Fill in the previously created IP address and press search
8. click the ip in the list
9. note that now loaded edit ip address page has rendered weirdly and has two copies of the footer.

### Expected Behavior

edit ip address page should render normally

### Observed Behavior

odd rendering + dual footers (bar in the middle is from screenshot tool scrolling)

![odd rendering](https://github.com/netbox-community/netbox/assets/1613241/7a3ecb01-a01b-4838-a24f-5484289d9318)

**Comment by jeffgdotorg** [comment]
Thanks for reporting this problem. I was able to reproduce it on a fresh 4.0.6 installation. Note also the double appearance of the header (search box and user menu), which shows up in Jamie's screenshot too. This does not happen with HTMX navigation disabled.

![image](https://github.com/netbox-community/netbox/assets/1209268/d0e726b1-a677-459f-9f57-f7d9b8b19d79)

**Comment by arthanson** [comment]
blocked by. #17571
