### ISSUE TITLE
new interface type for radio systems

### ISSUE THREAD

**Issue by sgvfr** [netbox-community/netbox#16778]
### NetBox version

4.06

### Feature type

New functionality

### Proposed functionality

adding a new interface type for radio systems, which use N-type, TNC, or BNC connectors on the hardware. such as the Codan MT-4E transmitter/receiver cards (using N-type)

### Use case

hardware used in radio systems, especailly uhf/vhf are hybrid, and can conbine IP interfaces with standard ethernet, and legacy connections to the field and antennas.

### Database changes

i dont' belive this will need a new field.. but i'm not a coder.

**Comment by jeremystretch** [comment]
Please update the text of your issue above to list the exact types being proposed and a technical reference for each.

**Comment by sgvfr** [comment]
Thanks, I will gather more information for you

**Comment by sgvfr** [comment]
@jeremystretch 
apologies for the delay.    updating for consideration and re-opening?

**Comment by sgvfr** [comment]
@jeremystretch    shall I create a new request?
