### ISSUE TITLE
Add Status field to inventory items

### ISSUE THREAD

**Issue by ITJamie** [netbox-community/netbox#16783]
### NetBox version

v4.0.6

### Feature type

Data model extension

### Proposed functionality

add a "status" field to the inventory item model

### Use case

being able to document the state of inventory items would be useful.
example states:
- active
- failed
- missing/removed (to document that an inventory item wasn't seen during last audit/check)

it would be great if this choices list could be extended like some of the status fields can be

### Database changes

add a status field to the inventory item model

### External dependencies

n/a

**Comment by thefreakquency** [comment]
Couldnt the Custom Fields be leveraged for that?

**Comment by ITJamie** [comment]
Im happy to make a PR for this
