### ISSUE TITLE
Script Results Showing Logs as JSON

### ISSUE THREAD

**Issue by jchambers2012** [netbox-community/netbox#16795]
### Deployment Type

Self-hosted

### NetBox Version

4.0.5

### Python Version

3.10

## Scripts Page
1. Update load the following script called Log Test

  ```python
  from extras.scripts import *
  class testScript(Script):
      class Meta:
          name = "Log Test"
          scheduling_enabled = False
          description = ""
      def run(self, data, commit):
          for i in range(6):
              self.log_info(f"Log Test - Sleeping for 1 Sec - {i}")
          return str("")
  ```

2. Run the script – The script will render with each log will be shown as html via the `/extras/scripts/results/<int:pk>/` URL
3. Go back the Script View (`/extras/scripts/`)
4. Click on the job “Log Test”
5. Click on the Jobs tab
![image](https://github.com/netbox-community/netbox/assets/6090690/7cc2aa49-2f9d-4dbc-9f50-83109a7553c8)

7. Click on the ID of the job and the script goes to a URL of `/core/jobs/<int:pk>/`
8. Script is showing logs as a JSON Object

### Expected Behavior
The URL of `/extras/scripts/results/<int:pk>/` should be called

### Observed Behavior

Scripts are using the default job template that is dumping the logs as a JSON object

![image](https://github.com/netbox-community/netbox/assets/6090690/1c384f5f-fb2f-480a-9d18-7d626c9fd239)

**Comment by jchambers2012** [comment]
Maybe related #16785

**Comment by alehaa** [comment]
Yep, its the same problem and I also overlooked there is already a feature request for this: #15983

**Comment by jchambers2012** [comment]
This one might be able to be fixed by updating the table's URL it links too as this is still under the /extras/scripts/##/ URLs  - but if the links cant be updated then #15983 would be the parent.

**Comment by alehaa** [comment]
Fixing the link was rejected in my PR. Please see the maintainers last comment, I think the desired behavior is reasonable.
