### ISSUE TITLE
OOB IP bulk import

### ISSUE THREAD

**Issue by PelochoV** [netbox-community/netbox#16801]
### NetBox version

v4.0.3

### Feature type

New functionality

### Proposed functionality

Can assign OOB IP to a server on IP Adress bulk import like you can assign primary ipv4

### Use case

Import BMC IPs as OOB IP

**Comment by jeremystretch** [comment]
Thank you for your interest in extending NetBox. Unfortunately, the information you have provided does not constitute an actionable feature request. Per our [contributing guide](https://github.com/netbox-community/netbox/blob/develop/CONTRIBUTING.md), a feature request must include a thorough description of the proposed functionality, including any database changes, new views or API endpoints, and so on. It must also include a detailed use case justifying its implementation. If you would like to elaborate on your proposal, please modify your post above. If sufficient detail is not added, this issue will be closed.

**Comment by PelochoV** [comment]
Hi Jeremy,

The main point of the request is to assign out-of-band IPs during the bulk process. Like when you are importing new IPs you can assign if it is primary or not. I don't know if this is useful for you and your team.

**Comment by jeremystretch** [comment]
@PelochoV please modify your original post above to clearly indicate what field(s) you're proposing be added to which bulk import forms.
