### ISSUE TITLE
Add more commit rate values

### ISSUE THREAD

**Issue by AdamBrutsaert** [netbox-community/netbox#16817]
### NetBox version

v4.0.6

### Feature type

Data model extension

### Proposed functionality

Add 200 and 400 GBPS commit rate for circuits 

### Use case

As #16791 added 200 and 400 GBPS circuit termination port speed, that would be also a QOL feature for circuit's commit rate

**Comment by AdamBrutsaert** [comment]
I'm willing to take ownership if needed to make a PR,

It is just adding two lines there https://github.com/netbox-community/netbox/blob/develop/netbox/circuits/choices.py#L30C1-L43C6

```python
        (200000000, '200 Gbps'),
        (400000000, '400 Gbps'),
```

**Comment by jeremystretch** [comment]
@AdamBrutsaert thanks, I've assigned this to you.
