### ISSUE TITLE
Notification displayed multiple times after deleting a dashboard widget

### ISSUE THREAD

**Issue by Olling** [netbox-community/netbox#16818]
### Deployment Type

Self-hosted

### NetBox Version

v4.0.6

### Python Version

3.11

### Steps to Reproduce

First "create" a popup in the corner.
1. Delete a widget on your dashboard
2. Close the "Deleted widget: 123" popup

Then do something else on the dashboard:
3. Click the cog icon on any other widget. 
4. Close the Configuration Window and the "Deleted widget: 123" popup
5. Unlock the dashboard
6. Click "Add Widget" 

### Expected Behavior

When a popup have been ignored or been closed it should not pop up again indefinitely. 

### Observed Behavior

The popup reappears again and again

I can reproduce the behavior on demo.netbox.dev

**Comment by jeremystretch** [comment]
I believe this was resolved in v4.0.9 under #17144.
