### ISSUE TITLE
Contact Assignments redirects to a "Page not found" when clicking Create & Add Another

### ISSUE THREAD

**Issue by Olling** [netbox-community/netbox#16820]
### Deployment Type

Self-hosted

### NetBox Version

v4.0.6

### Python Version

3.11

### Steps to Reproduce

1. Go to Virtualization / Virtual Machines
2. Click on a random Virtual Machine
3. Go to the Contacts tab, and click "+ Add a contact"
4. Fill-out the required fields, and click "Create & Add Another"

### Expected Behavior

The Contact Assignment should be created, and the form should reappear to allow the user to add another assignment. 

### Observed Behavior

The Contact Assignment is created, but the user is redirected to a missing page:
![image](https://github.com/netbox-community/netbox/assets/16271163/dc8c7013-5a8f-4364-b02f-82ed17887a68)

**Comment by jeremystretch** [comment]
This has already been addressed in #16806.
