### ISSUE TITLE
ActionsColumn fails to render extra_buttons when actions tuple is empty

### ISSUE THREAD

**Issue by kprince28** [netbox-community/netbox#16838]
### Deployment Type

Self-hosted

### NetBox Version

v4.0.7

### Python Version

3.12

### Steps to Reproduce

- Created a table. In this table, there's a feature to show extra buttons next to each row. However, I noticed that these extra buttons don't show up when I set another feature called "actions" to an empty list.

1. Initialize an `ActionsColumn` with an empty `actions` tuple and valid `extra_buttons`:

```
actions = columns.ActionsColumn(
    actions=(),
    extra_buttons=ACTIVATE_BUTTON
)
```

2. Render the table and observe the output.

### Expected Behavior

The extra buttons should render correctly even when the actions parameter is empty.

### Observed Behavior

When I explicitly set actions to an empty tuple (actions=()), the extra buttons (ACTIVATE_BUTTON) do not appear. They only show up when actions are not defined at all or are set differently.

**Comment by jeffgdotorg** [comment]
Hi Prince, thanks for reporting this problem. I'm advancing it to `needs owner` status, and would love to assign it to you for work-through. Please advise and I or another maintainer will make it so.
