### ISSUE TITLE
Ability To Export Cards

### ISSUE THREAD

**Issue by mr1716** [netbox-community/netbox#16858]
### NetBox version

v4.0.6

### Feature type

New functionality

### Proposed functionality

The request would be to have the ability to export card table data for individual records. For example, if I added a template_content.py from a plugin to dcim.devices with some filters, I would be able to easily export that data.

### Use case

When extending Netbox and adding in custom tables using Plugins, it would be beneficial to have a way to easily export those tables without having to go elsewhere to find that data

**Comment by jeremystretch** [comment]
Cards are strictly a UI construct, and merely render data provided by the UI view; they do not and cannot have any export capability. There are plenty of other robust ways to export data from NetBox, including the REST & GraphQL APIs, as well as customizable export templates.
