### ISSUE TITLE
Improve display for long-text custom fields

### ISSUE THREAD

**Issue by raphis** [netbox-community/netbox#16857]
### NetBox version

v.4.0.6

### Feature type

Change to existing functionality

### Proposed functionality

This is a followup on issue https://github.com/netbox-community/netbox/issues/16830 (opened as bug).

Long text variables make the read-only overview page (e.g. of a device) nearly unusable as it needs a lot of scrolling.

Suggestion: Use a defined height for the text (long) type of custom field and add a scrollbar as it's shown in the edit-view of an object.

<img width="875" alt="long-text_view" src="https://github.com/netbox-community/netbox/assets/7922644/0ca4705a-c2a6-4b63-922f-4a394479b48c">
<img width="601" alt="long-text_edit" src="https://github.com/netbox-community/netbox/assets/7922644/55a85e79-33b9-43be-93b3-1fd39e2dba54">

### Use case

To reproduce:

1. Create a type "Text (long)" custom field for Devices
2. Save a very long text into this field
3. Access the device in the "read-only" view
4. The page gets very long and the user needs to scroll

### Database changes

none

### External dependencies

none

**Comment by Brucegyx** [comment]
Hi, I also noticed the same behaviour when viewing a long comment on the Device page. It looks like a styling change may do the work.
