### ISSUE TITLE
Allow light theme for navigation UI (tabler)

### ISSUE THREAD

**Issue by goteamkor** [netbox-community/netbox#16876]
### NetBox version

4.0.7

### Feature type

Change to existing functionality

### Proposed functionality

Hot on the heels of #16842, it would be nice to be able to select the 'light' version of the navbar. Currently, the gray on blue can be hard to read.

Current UI: https://preview.tabler.io/layout-vertical.html
Proposed option: https://preview.tabler.io/layout-vertical-transparent.html

This would not replace, but be a configurable option either per user or globally.

### Use case

Current navbar color scheme can be hard to read and distinguish sections and sub sections.
In addition, when netbox is using the light theme for the content displays, the navbar should also reflect the theme preference, and not have 'dark' mode for the navigation be the only available option.

### Database changes

Possible database change to allow global and per user settings of navbar theme.

### External dependencies

tabler.

**Comment by jeremystretch** [comment]
This was already proposed and rejected in #15615. Additionally, there is currently an effort under way to [improve the overall styling of the UI in general](https://github.com/netbox-community/netbox/issues?q=is%3Aopen+is%3Aissue+author%3Aandrewgormley+label%3A%22topic%3A+UI%2FUX%22), and no substantial changes will be considered until that work has been completed.

**Comment by goteamkor** [comment]
Is there a possibility to reconsider this? You've given no other explanation in #15615 other than "you quite like it". I mean, good for you, but clearly others don't. Or would at least like the option of choosing the light theme.
If you expect others to submit technical reasons for why a feature request has merit, I think its fair for you to do the same. 

Can you provide a technical reason why this can't be implemented?

**Comment by jeremystretch** [comment]
This FR, on its own, has already been proposed and rejected. But as I said, the entire UI is currently being restyled and improved. You are invited to share your thoughts on the updated styling when it is released, which should be in v4.0 beta 1 in early August.

**Comment by goteamkor** [comment]
Not to hammer a point, but in my other FR, you shoot down my opinion of the horizontal nav bar being easier to navigate because it's an opinion, and yet your rejection of this FR (from #15615) appears to also be based solely on your opinion of liking the dark theme better.

Are there technical reasons why you're rejecting the ability to utilize the light theme other than your personal preference for the dark theme?

**Comment by jeremystretch** [comment]
Neither FR offered any objective justfication for a change. Should we change it to light mode because you like it better, and then change it back to dark mode because someone else likes _that_ better? We're not going to make arbitrary changes just because people have a difference of opinion.

I've said all I'm going to on this matter, because it's not worth discussing further.
