### ISSUE TITLE
Move the search bar to the current position and extend also

### ISSUE THREAD

**Issue by suzukiautomation** [netbox-community/netbox#16873]
### NetBox version

v4.0

### Feature type

Change to existing functionality

### Proposed functionality

Move the search bar to the current position and extend also

### Use case

Move the search bar to the current position and extend also

### Database changes

Move the search bar to the current position and extend also

### External dependencies

Move the search bar to the current position and extend also

**Comment by jsenecal** [comment]
@suzukiautomation this submission is of terrible quality, the information you have provided does not constitute an actionable feature request. 

Have a look at the [contributing guide](https://github.com/netbox-community/netbox/blob/develop/CONTRIBUTING.md)!

A feature request must include a thorough description of the proposed functionality, including any database changes, new views or API endpoints, and so on. It must also include a detailed use case justifying its implementation. If you would like to elaborate on your proposal, please modify your post above. If sufficient detail is not added, this issue will be closed by one of the maintainers.

**Comment by jeffgdotorg** [comment]
Thanks for your interest in helping improve NetBox. As @jsenecal points out, this issue does not come close to meeting quality standards, and I'm therefore closing it. Please feel free to try again after reviewing the contributing guide linked above.

**Comment by suzukiautomation** [comment]
Very bad that’s not planned!

Med vänlig hälsning/ best regards/ mit freundlichen Grüßen

Daniel Laube
Global Automation Engineer

Suzuki Garphyttan AB
Bruksvägen 3
719 41 Garphyttan
Phone: +46 (0)19 295 100
Cell: +46 (0)73 065 52 14
www.suzuki-garphyttan.com<http://www.suzuki-garphyttan.com/>
***@***.******@***.***>
