### ISSUE TITLE
Cleaner "Installed Module" column for the "Device Bays" tab of a device.

### ISSUE THREAD

**Issue by grbeneke** [netbox-community/netbox#16895]
### NetBox version

v4.0.7

### Feature type

Change to existing functionality

### Proposed functionality

Update the structure of the text for the "Installed Module" column of the "Device Bays" tab of a device.  

- Remove the text at the start of the string up to the colon and space. This is a duplication of the string which already appears in the "Name" column.
- Remove the number in brackets at the end of the string. This is the backend/database id for the object and has limited relevance to front-end users. Value can be derived in other ways for API users.

### Use case

Reduce duplication and clutter in the user interface.

### Database changes

none

### External dependencies

none

**Comment by arthanson** [comment]
@grbeneke Can you please provide a screenshot of the issue, not sure exactly what you are referring to here (see screenshot):
<img width="1128" alt="tmodulebay | NetBox 2024-07-17 12-34-47" src="https://github.com/user-attachments/assets/a78b2315-4735-4f2c-a5ee-3da70250a3a1">

**Comment by Azmodeszer** [comment]
I think they are actually referring to _Module_ Bays, not _Device_ Bays and want to get rid of the slot and ID info in the Installed Device column, arguing the information is redundant.

![image](https://github.com/user-attachments/assets/90ad82f2-ecda-4f97-aa6b-aa7629ba48e0)

**Comment by goteamkor** [comment]
+1 for removing the redundant information.

![image](https://github.com/user-attachments/assets/e8147f80-3189-4319-9bb2-3b45cdd409bf)
