### ISSUE TITLE
Missing description for installed module in module bays list

### ISSUE THREAD

**Issue by grbeneke** [netbox-community/netbox#16894]
### Deployment Type

Self-hosted

### NetBox Version

v4.0.7

### Python Version

3.10

### Steps to Reproduce

1. Access the "Module Bays" tab of a device with module bays.
2. Select the "Install module" option on an empty bay.
3. Fill "Module Type" and "Description" fields and select "Create"
4. After returning to the "Module Bay" page the "Description" column remains blank.

### Expected Behavior

The "Description" column of the "Module Bays" list should show the description entered when installing the module.

### Observed Behavior

The "Description" column of the "Module Bays" list is blank.  

It appears that the value entered in the "Description" field is not lost and is visible when displaying the 'module' object individually. The value displayed in the "Module Bays" listing of the device appears to be derived from a "Description" field which exists separately in the 'module bay' object.

**Comment by arthanson** [comment]
@grbeneke It looks like you are talking about the table field highlighted below?  That is the description of the bay, not the child device. If you click the edit button to the right hand side and edit the bay you can set a description for the bay which is how I got "foo" to show there.

<img width="1137" alt="tmodulebay | NetBox 2024-07-12 16-58-16" src="https://github.com/user-attachments/assets/f42471ab-db93-4625-ae4d-bc45f7538514">

**Comment by arthanson** [comment]
Closing as looks like non issue

**Comment by grbeneke** [comment]
> @grbeneke It looks like you are talking about the table field highlighted below? That is the description of the bay, not the child device.
The screen-shot shows **Device** Bays - my bug report relates to **Module** Bays.

In the Module Bays tab - the two columns ahead of _Description_ are _Module Type_ (a field from the Module object) and _Module Status_ (also a field from the Module object). This UI layout would intuitively lead the user to believe that the _Description_ field also relates the the Module object.

> If you click the edit button to the right hand side and edit the bay you can set a description for the bay which is how I got "foo" to show there.
I expect that most front-end users are editing the Description field like this to describe the function of the _Module_ rather than the _Bay_. Describing the active installed component will typically have much more operational value than a description of the empty/underlying bay. It seems preferable to rather display the module description.
