### ISSUE TITLE
Allow filtering of Inventory Items by Device Status

### ISSUE THREAD

**Issue by jasonyates-thg** [netbox-community/netbox#16905]
### NetBox version

3.7.8

### Feature type

New functionality

### Proposed functionality

Extend the filterable options for Inventory Items to include Device Status

### Use case

Currently the Filter tab on Inventory Items allows you to filter by Device Type, Device Role & Device. We use the Device Status attribute to determine if a server is actively provisioned in our environment or not so it would be useful to be able to filter Inventory Items by device status to assist in locating an unused server with a given inventory. 

i.e. 
Site: London
Device Status: Inventory
Role: CPU
Label Contains: Gold

**Comment by dannywade** [comment]
I would like to own this issue.

**Comment by jeremystretch** [comment]
Thanks @dannywade, I've assigned this to you!

**Comment by dannywade** [comment]
I opened a PR but still have a bug I'm trying to figure out. Details are in the PR. I'm open to suggestions!

**Comment by jeremystretch** [comment]
Opening this back up for anyone else who wants to take a stab at it.
