### ISSUE TITLE
Netbox 4.0 'admin' section of nav bar hidden by URL popup in Chrome, Firefox

### ISSUE THREAD

**Issue by falz** [netbox-community/netbox#16913]
### Deployment Type

Self-hosted

### NetBox Version

v4.0.7

### Python Version

3.10

### Steps to Reproduce

1. run netbox 4.x
2. Expand a section so that the 'Admin' text is at the bottom left of your web browser
3. Move mouse around the left navbar area
4. Chrome and Firefox pop showing the URL of what your mouse is over
5. 'Admin' link

### Expected Behavior

All navbar elements are visible 

### Observed Behavior

We recently upgraded and I was very confused for a while where the Admin area went, a few times.

Likely a trivial fix such as forcing some whitespace in that area.

![netbox-menu-issue](https://github.com/user-attachments/assets/d823bf71-95b9-4b34-a453-60d64fa8d09f)

This is obviously the behaviour of the web brower itsself, tested in Chrome and Firefox and both act the same. However, it seems like the only workaround would be to adjust Netbox.

**Comment by jeffgdotorg** [comment]
Thanks for reporting this problem in NetBox.

We happen to have @andrewgormley doing some work in the UI so I've assigned to him to implement. Since Andrew's current project is targeted to the v4.1 release, there's a chance the fix won't land in a v4.0.x patch release, just by way of setting expectations.

**Comment by jeffgdotorg** [comment]
Assigning medium severity. There's a case for making it low, but the impact is fairly disruptive and no workaround is available.

**Comment by jeremystretch** [comment]
This has been addressed under the UI refresh in v4.1.
