### ISSUE TITLE
Add extra UI element to non-community instances

### ISSUE THREAD

**Issue by jeffgdotorg** [netbox-community/netbox#16928]
### NetBox version

v4.0.7

### Feature type

Change to existing functionality

### Proposed functionality

On instances where `settings.RELEASE.edition != 'community'`, add a [question-answer icon](https://fonts.google.com/icons?selected=Material+Icons+Outlined:question_answer:&icon.query=chat&icon.set=Material+Icons&icon.size=24&icon.color=%23e8eaed) element In the scroll-sticky portion of the base template. Ideal placement is to the left of the light mode / dark mode toggle element. The element's `id` attribute should be stable, and similar to `launch-help-center`.

### Use case

In some NetBox product editions, this element will serve as a trigger to launch an interactive help center.

### Database changes

None

### External dependencies

None

**Comment by jeremystretch** [comment]
We can add a button for this to the top navigation bar, but it should be hidden (i.e. `display: hidden`) by default to ensure that it's only visible if the associated tooling has been successfully initialized.
