### ISSUE TITLE
Add USB type to Front/Rear Ports choices

### ISSUE THREAD

**Issue by Brian-Chow** [netbox-community/netbox#16926]
### NetBox version

v4.0.7

### Feature type

Data model extension

### Proposed functionality

I propose to add USB choices for Front/Rear ports.
Changes proposed include modifying dcim/choices.py to add USB front and rear ports.
No other data or UI changes required beyond the addition of USB choices

### Use case

Use Cases:
* Patch Panels with modular/keystone ports and pass-through USB keystones. 
* USB WiFi and Network Adapters

Specific Scenario:
Firewalla sells a 1u rack adapter/shelf for their Firewalla GOLD line of firewall appliances.  It has an optional USB Wifi adapter that they provide keystone slots to move from the rear of the firewalla appliance to the front of the 1u rack adapter.

General other benefits:
Netbox already supports USB cable types for consoles, but does not have a way to model using a usb cable and a patch panel to relocate the port from the rear/inside the rack to the front/outside of the rack.  These cables should be treated as any other patch cable.
This modification could also support USB attached celluar backup modems, and USB attached SMS gateways.

Code changes already completed in fork, just waiting on approval to submit a PR.

### Database changes

n/a -- only requires adding lines to dcim/choices.py

### External dependencies

n/a

**Comment by jeffgdotorg** [comment]
Thanks for your interest in improving NetBox!

I've moved this issue to `accepted` status and assigning it to you for implementation, since you've expressed interest in working it through to a PR.
