### ISSUE TITLE
Escape config-revision banner values by default

### ISSUE THREAD

**Issue by jeffgdotorg** [netbox-community/netbox#16934]
### NetBox version

v4.0.7

### Feature type

Change to existing functionality

### Proposed functionality

- The values of the banner fields (login, maintenance, top, bottom) are escaped by default before displaying
  - Nice to have / bonus: Banners support Markdown rendering
- A new configuration parameter, e.g. `ESCAPE_BANNERS`, is available and can be set to `False` to override the default behavior
- Configuration Documentation updated to mention this new configuration parameter
- Names of all dependent objects are escaped before displaying in error messages when parent object deletion fails

### Use case

- Our users trust NetBox to be a safe and secure place to store sensitive information about the actual and intended state of their networks
- Many users need to include formatting, hyperlinks, or even arbitrary markup in the values of their system banners.
- All users benefit from a system whose security posture defaults to protecting them from malicious content, which threat actors are very good at finding ways to inject

### Database changes

None

### External dependencies

None

**Comment by minhquan202** [comment]
no bro, not fix

**Comment by jeremystretch** [comment]
As has been discussed in previous conversations, these banners are intended to support raw HTML. Users do not have permission to set any of this content by default; only administrators may modify the content. This change is not needed.
