### ISSUE TITLE
No MAC address displayed

### ISSUE THREAD

**Issue by deanfourie1** [netbox-community/netbox#16935]
### Deployment Type

Self-hosted

### NetBox Version

v4.0.7

### Python Version

3.10

### Steps to Reproduce

1. Go To Devices,
2. Select a Device
3. Check under "Management" section.
4. The MAC address used to be displayed here along with the IP address.

### Expected Behavior

The MAC address to be displayed.
Is there a way to resolve this?

### Observed Behavior

MAC address is not displayed.

![image](https://github.com/user-attachments/assets/3f47cc7f-160e-46c7-9aea-63c4137a0a3c)

**Comment by jeremystretch** [comment]
To the best of my recollection, this panel has never displayed a MAC address. MAC addresses are not assigned to devices in NetBox, but rather to interfaces on a device.

If you would like to propose including additional information within this panel on the UI, please submit a [feature request](https://github.com/netbox-community/netbox/issues/new?assignees=&labels=type%3A+feature%2Cstatus%3A+needs+triage&projects=&template=feature_request.yaml).

**Comment by deanfourie1** [comment]
Ok, maybe you are right I cannot remember now. Thanks I will submit a feature request.
