### ISSUE TITLE
Filter reset button does not reset filter

### ISSUE THREAD

**Issue by mhdask** [netbox-community/netbox#16959]
### Deployment Type

Self-hosted

### NetBox Version

v4.0.7

### Python Version

3.10

### Steps to Reproduce

1. Click on Devices (I think any model that can be filtered will do)
2. Click on filter
3. Apply any filter (I used Status PLANNED for device)
4. Press Reset
5. Observe filter is still applied

### Expected Behavior

The filter should have been removed / reset

### Observed Behavior

The filter did not get removed / reset

**Comment by arthanson** [comment]
It looks like this routine: 
```
  /**
   * Initialize any adjacent reset buttons so that when clicked, the page is reloaded without
   * query parameters.
   */
  private initResetButton(): void {
    const resetButton = findFirstAdjacent<HTMLButtonElement>(
      this.base,
      'button[data-reset-select]',
    );
    if (resetButton !== null) {
      resetButton.addEventListener('click', () => {
        window.location.assign(window.location.origin + window.location.pathname);
      });
    }
  }

```
from the old apiSelect.ts is missing.
