### ISSUE TITLE
Page not found (404) for certain actions in a list view when a user is part of more than one group

### ISSUE THREAD

**Issue by papounaise** [netbox-community/netbox#16968]
### Deployment Type

Self-hosted

### NetBox Version

v3.7.6

### Python Version

3.12

### Steps to Reproduce

When objects are displayed in a list view , a user may have different permissions  for each object. For example, in a device list view, a user can have 'Can view' for tenant1 and [Can view, Can add, Can change and Can delete] for tenant2.

The devices displayed in that list view all have the same buttons (including delete). Trying to delete a device related to tenant1 will result in a 404 

<img width="1026" alt="404" src="https://github.com/user-attachments/assets/a49e03c3-287e-446e-8eb6-b0f091e5fed5">

When different permissions are involved in a list view, would it be possible to display a message like 

![Capture d’écran, le 2024-07-24 à 06 31 54](https://github.com/user-attachments/assets/307a845e-7240-4ddf-8a76-0ce69daf3d59)

instead of the 404 error ?

### Expected Behavior

A message like  

![Capture d’écran, le 2024-07-24 à 06 31 54](https://github.com/user-attachments/assets/b3935203-00c1-455d-a6e7-64b6aa7b2db0)

### Observed Behavior

<img width="1026" alt="221955573-e5590eb3-e00e-49ec-8c78-58336fafe284" src="https://github.com/user-attachments/assets/2201ebf0-fc65-4274-9f53-030e6baef8b3">

**Comment by jeremystretch** [comment]
Thank you for opening a bug report. Unfortunately, the information you have provided is not sufficient for someone else to attempt to reproduce the reported behavior. Remember, each bug report must include detailed steps that someone else can follow on a clean, empty NetBox installation to reproduce the exact problem you're experiencing. These instructions should include the creation of any involved objects, any configuration changes, and complete accounting of the actions being taken. Also be sure that your report does not reference data on the public NetBox demo, as that is subject to change at any time by an outside party and cannot be relied upon for bug reports.

**Comment by papounaise** [comment]
I just updated the steps to reproduce part.

**Comment by jeremystretch** [comment]
You've already opened issue #11812 for this, which did not yield any tenable implementations.

I'm going to close this out as a duplicate. If you'd like to propose a specific implementation to improve this behavior, please submit a new feature request detailing the proposed solution.
