### ISSUE TITLE
Providers list view "ACCOUNT COUNT" column using wrong attribute name in link

### ISSUE THREAD

**Issue by jsenecal** [netbox-community/netbox#16963]
### Deployment Type

Self-hosted

### NetBox Version

v4.0.7

### Python Version

3.10

### Steps to Reproduce

1. Create at least two Providers
2. Create at least two Provider Accounts linked to multiple different Providers
3. Navigate to Providers list view and click on a non-zero "ACCOUNT COUNT" (notice the Provider name)
4. Notice that the url filter is using `account_id` instead of `provider_id` which results in the list not being properly filtered for that Provider

### Expected Behavior

The resulting Provider Account list should be filtered to only display Accounts belonging to that Provider

### Observed Behavior

All the Accounts are displayed, unfiltered, due to the url parameter applied is `account_id` instead of `provider_id`

**Comment by jsenecal** [comment]
I believe this is caused by [circuits/tables/providers.py#L28](https://github.com/netbox-community/netbox/blob/develop/netbox/circuits/tables/providers.py#L28)

**Comment by jsenecal** [comment]
I volunteer @arthanson, please assign this to me.

**Comment by jeremystretch** [comment]
Thanks @jsenecal, I've assigned you.
