### ISSUE TITLE
Add search operators

### ISSUE THREAD

**Issue by Shourai** [netbox-community/netbox#16970]
### NetBox version

v4.0.7

### Feature type

New functionality

### Proposed functionality

Add the possibility to use search operators.

The global search on the main page is often used and it brings you to the search page where you have the option to drill down using the object type field and lookup field..
However, if you have a large database and you want to search for something specific you have to select those options every time.

Adding search operators like

```
vlan: 
rack:
device:
...
```
would improve the user experience for searching.

For example I need to lookup `vlan 100`, with the search operator I would type `vlan: 100` in the global search field and the search automatically 
selects the object type `vlan`.

It would somehow have to translate it into `/search/?q=100&obj_types=ipam.vlan`

Additionally if regex is used it would also select regex as lookup field.
E.g.
`vlan: ^100$`
This would filter for only vlan 100 and not vlan 1000.

### Use case

This addition would improve the user experience when searching for specific object types.

**Comment by jeremystretch** [comment]
It sounds like you have the start of an idea, but this needs to be fleshed out much more before it can be considered for implementation. Would you like to take some time exploring how the global search engine currently works, and devising a (high level) potential implementation to support your proposal?

**Comment by Shourai** [comment]
I will look into it and see what I can do, although I have no experience with Django.

**Comment by PieterL75** [comment]
I had a similar proposal https://github.com/netbox-community/netbox/issues/12959
Hope this gets implemented

**Comment by jeremystretch** [comment]
Closing this out as no further detail has been provided.
