### ISSUE TITLE
Add support for DNS

### ISSUE THREAD

**Issue by kclif9** [netbox-community/netbox#16998]
### NetBox version

v4.0.7

### Feature type

Data model extension

### Proposed functionality

Add support for DNS models to the Netbox core project. 

### Use case

This would allow users to maintain their DNS record documentation through the Netbox product alongside their other infrastructure documentation. 

### Database changes

The data model would contain support for registrars, domain names, and DNS records. A records would be mapped to existing objects within Netbox. CNAME's could be mapped to other domain names where relevant.

### External dependencies

Not that I can foresee

**Comment by jeremystretch** [comment]
I'm afraid this is out of scope for the core NetBox project, but have a look a @peteeckel's [DNS plugin](https://github.com/peteeckel/netbox-plugin-dns).
