### ISSUE TITLE
Get a role what only displays contact relates to object with permission

### ISSUE THREAD

**Issue by karolyczovek** [netbox-community/netbox#16996]
### NetBox version

v4.0.7

### Feature type

New functionality

### Proposed functionality

Currently 
1) no device contact is displayed until I don't allow global contact read 
2) in case i set allow contact, all contacts are exposed, not only ones with relates to allowed objects

### Use case

User should access to contacts relates to allowed objects/devices to see.

**Comment by arthanson** [comment]
@karolyczovek Thank you for opening a bug report, Unfortunately there is probably a language issue here, I'm not sure exactly what you are describing here and the information you have provided is not sufficient for someone else to attempt to reproduce the reported behavior. Can you please provide the reproduction steps for what you are seeing. 

Remember, each bug report must include detailed steps that someone else can follow on a clean, empty NetBox installation to reproduce the exact problem you're experiencing. These instructions should include the creation of any involved objects, any configuration changes, and complete accounting of the actions being taken. Also be sure that your report does not reference data on the public NetBox demo, as that is subject to change at any time by an outside party and cannot be relied upon for bug reports.

**Comment by karolyczovek** [comment]
Problem: (or question): how to allow ppl with access to certain devices only to get device/site related contacts, not all.

**Comment by arthanson** [comment]
@karolyczovek can you please open this as a GitHub discussion as jsenecal pointed out. Closing this issue.
