### ISSUE TITLE
Add Wi-Fi 7 ieee802.11be to the list of available interface connection types

### ISSUE THREAD

**Issue by chaydock** [netbox-community/netbox#17006]
### NetBox version

v4.07

### Feature type

Change to existing functionality

### Proposed functionality

In the file [netbox\netbox\dcim\choices.py](https://github.com/netbox-community/netbox/blob/develop/netbox/dcim/choices.py), at line 881 is a list of available Wi-Fi standards. The list is presently missing support for the latest [Wi-Fi 7 standard IEEE 802.11be](https://en.wikipedia.org/wiki/IEEE_802.11be)

### Use case

Allows users to add new devices that are supporting Wi-Fi 7 such as the [Unifi U7-Pro](https://store.ui.com/us/en/collections/unifi-wifi-flagship-high-capacity/products/u7-pro)

### Database changes

I don't believe this would require a schema change... just an extension of list of supported standards already present

### External dependencies

None

**Comment by jeremystretch** [comment]
Back in my day the only 802.11b was 11 Mbps, and we were happy to have it!

**Comment by mcmehrtens** [comment]
I can work on this! I’d like to dip my toes into this codebase :)

**Comment by jeremystretch** [comment]
@mcmehrtens go for it!
