### ISSUE TITLE
SSO icon is not centered when there is no text

### ISSUE THREAD

**Issue by mcmehrtens** [netbox-community/netbox#17007]
### Deployment Type

Self-hosted

### NetBox Version

v4.0.8

### Python Version

3.11

### Steps to Reproduce

1. Set the `SOCIAL_AUTH_BACKEND_ATTRS` variable in the configuration directory to have an icon and an empty string as the text:

```python
SOCIAL_AUTH_BACKEND_ATTRS = {
    "oidc": ("", "https://mehrtens-cc.pages.dev/netbox/netbox_sso_icon.svg"),
}
```

2. Restart NetBox.

### Expected Behavior

The SSO button shows on the login screen with only a centered icon.

<img width="506" alt="image" src="https://github.com/user-attachments/assets/72371055-5b2c-482a-999b-91ae2550f719">

_Note: in the image, the rulers are off by 0.5 pts due to aliasing._

### Observed Behavior

The SSO button shows on the login screen with the icon noticeably off-center, due to a 5rem margin on the right of the icon.

<img width="529" alt="image" src="https://github.com/user-attachments/assets/a981ab4b-e0ff-4b04-a20d-cb2722469784">

**Comment by mcmehrtens** [comment]
I'd love to fix this quickly myself. I've never contributed to an open-source project before!

**Comment by mcmehrtens** [comment]
Just want to double-check that I can open a PR for this :)

**Comment by arthanson** [comment]
@mcmehrtens yes, and thank you.  Will assign to you.

**Comment by jeremystretch** [comment]
@mcmehrtens are you still planning to work on this issue?

**Comment by mcmehrtens** [comment]
> @mcmehrtens are you still planning to work on this issue?

I'm so sorry, yes. I'll do it tonight. I was moving in to a new apartment last week :)
