### ISSUE TITLE
Rack Width property for devices

### ISSUE THREAD

**Issue by llamafilm** [netbox-community/netbox#17021]
### NetBox version

v4.0.8

### Feature type

Data model extension

### Proposed functionality

I'd like to have a new `rack_width` field on Device Types with options of 1/4, 1/3, 1/2, and full.  Full is the default, and would continue the current behavior.  If this is set to anything other than full, then allow installing multiple devices in the same RU, without needing a “child” designation, as long as the sum of their widths is less than 1.
The rack elevation view would show all devices with their names and photos, and you can click directly on each one.

### Use case

Many rack-mount devices are less than a full 19" width.  Some examples:
- Mellanox SX6012 switch
- Palo Alto PA-220 firewall
- Phabrix QxL rasterizer
- Leader LV5600 waveform monitor
- QSC Qsys Core Nano processor
- QSC SPA4-100 amplifier

These devices are usually designed with two different mounting options:
1. Side by side in the same RU with a joiner plate.
2. One by itself by rotating the rack ear 90 degrees to make it a half-width blank

Currently, modeling two devices in the same RU requires designating them as "children", and making up a bogus parent device. Even when installing one by itself, you still have to create the parent.

This would make the rack elevation view more useful, and reduce busy work of creating unnecessary parent devices.

### Database changes

a new `rack_width` field on the DeviceType and Device.

### External dependencies

none

**Comment by kmorin18** [comment]
I would recommend using shelves and add module with device bays to insert each device into :)

**Comment by DanSheps** [comment]
Could you provide some examples of these joiner plates?  Everything I have seen indicates that these go into custom shelves which would be modeled as a device.

**Comment by kmorin18** [comment]
Yes the shelf itself is a device that has device bays
![image](https://github.com/user-attachments/assets/2437db55-56bf-4b55-866b-1c6dfcd3a97e)

**Comment by llamafilm** [comment]
Here's a drawing from QSC showing a half rack mounting option. It references the IEC60297-3-100 spec but I don't have access to that.

https://www.qsys.com/resource-files/productresources/dn/dsp_cores/core_nano/q_dn_core_nano_halfrack_2ddrawing.pdf

The joining plate is not shown there but it's mentioned in the manual: https://www.qsys.com/resource-files/productresources/dn/dsp_cores/q_dn_core_nano_8flex_usermanual.pdf

https://support.qsys.com/faq-%7C-faq-can-12-and-14-rack-1u-q-sys-devices-mount-side-by-side

Mellanox sells a rail kit, which can be used to mount either 1 or 2 units. Rail kits are required for most equipment but are never modeled in Netbox.

https://docs.nvidia.com/networking/display/sn2000pub/SN2100/SN2010+Side+by+Side+Mounting+Rail+Kit

https://docs.paloaltonetworks.com/hardware/pa-220-hardware-reference/install-the-pa-220-firewall/install-the-pa-220-firewall-in-an-equipment-rack/install-the-pa-220-firewall-using-the-pan-pa-220-rack-single#id8c951c90-edb5-445b-8085-a11c66c2ba0d

For comparison, Arista 710P is a 1U device which also requires an extra rack-mount bracket. I'm sure nobody would want to make this bracket a "parent".

https://www.arista.com/en/qsg-710p-series/710p-series-mounting-the-switch

**Comment by jeremystretch** [comment]
As other have mentioned, the solution to modeling this in NetBox is to device a parent device type with device bays to house the child devices. NetBox's data model cannot support arbitrary device widths.
