### ISSUE TITLE
Include TPID in VLAN model

### ISSUE THREAD

**Issue by movedempackets** [netbox-community/netbox#17046]
### NetBox version

v4.0.8

### Feature type

Data model extension

### Proposed functionality

The VLAN model does not include the tag protocol ID (TPID) field. The TPID value can be used to distinguish tagged frames (for example a TPID: 0x8100 VID: 1 tagged frame is not equal to a TPID: 0x88a8 VID: 1 tagged frame). 

> It's unsuitable for Administrators to apply a TPID custom field to the VLAN model. When a VLAN belongs to a group it's constrained by "ipam_vlan_unique_group_vid" UNIQUE CONSTRAINT, btree (group_id, vid). Therefore VLAN's of equal VID but of unequal TPID cannot be contained in the same group.

I propose that the VLAN model include the TPID field, which can be a choice of valid TPID values. I can contribute to the implementation of this feature, if accepted. 

### Use case

Users can now specify the VLAN TPID value.

### Database changes

The `ipam_vlan` table should include a new column named `tpid`. The `ipam_vlan_unique_group_vid` unique constraint should include the `tpid` column.

**Comment by DanSheps** [comment]
After discussing and reviewing this with other maintainers, there appears to be a lot of overlap with #13428 and we should proceed with all work under that FR.
