### ISSUE TITLE
Bulk import/assign OOB addresses

### ISSUE THREAD

**Issue by andy-lawson** [netbox-community/netbox#17071]
### NetBox version

v3.7.5

### Feature type

New functionality

### Proposed functionality

Add the capability to add or assign device out-of-band IP addresses by bulk import or update.

*Add an "is_oob" field to the IP address bulk import feature*

### Use case

- When importing IPs, it is currently possible to assign those IPs as the "Primary" IP for a device.
- Out-of-band IP status cannot be assigned in this manner during the bulk import or subsequent bulk update of IPs or devices.
- Out-of-band IP status is frequently overlooked because it cannot be bulk added or updated.

### Database changes

None.

### External dependencies

None.

*Edit for clarity*

**Comment by andy-lawson** [comment]
May be a duplicate of [16801](https://github.com/netbox-community/netbox/issues/16801), but that issue has closed for no update.

**Comment by arthanson** [comment]
@andy-lawson please modify your original post above to clearly indicate what field(s) you're proposing be added to which bulk import forms.

**Comment by andy-lawson** [comment]
Updated as requested.

**Comment by pl0xym0r** [comment]
Was working on it and was wondering : if implemeted on bulk_import, shouldn't be added on `IPAddressForm` too to keep consistency ? It could be a box to check (like : "make it primary") under : 

![image](https://github.com/user-attachments/assets/d9e82b6f-e89a-42f3-84d8-a0921441510a)

**Comment by M00SE80** [comment]
I too would like to see this functionality added.

Currently there is an option to make an address the primary using the is_primary field under the bulk add IP Address form.
It would be good to have something like this for the OOB here also as @andy-lawson has suggested like is_oob
