### ISSUE TITLE
Make 'Phone' Field Values clickable in "Contact Assignments" Table

### ISSUE THREAD

**Issue by opericgithub** [netbox-community/netbox#17072]
### NetBox version

v4.0.7

### Feature type

Change to existing functionality

### Proposed functionality

In the current version of NetBox, the value of the Contact's "Phone" field in the "Contact Assignments" table is **not** clickable. This contrasts with the "Phone" field in the "Contacts" table, where the value **is** clickable and can be interacted with directly with some phone dialing app.

"Contact Assignments" Table (Phone value not clickable) :
![image](https://github.com/user-attachments/assets/dc766c59-addf-4da3-a932-ed796900be72)

"Contacts" Table (Phone Value clickable) :
![image](https://github.com/user-attachments/assets/6f27361c-442d-4f8b-9191-d40fedefc3ad)

### Use case

I propose enhancing the functionality so that the 'Phone' field value in the "Contact Assignments" table is also clickable. This will allow users to interact directly with phone numbers using phone dialing apps.

### Database changes

n/a

### External dependencies

n/a

**Comment by jeremystretch** [comment]
Per #17197 the email values should be rendered as hyperlinks as well.
