### ISSUE TITLE
Clickable area of input fields extends too far left

### ISSUE THREAD

**Issue by Chiniquy** [netbox-community/netbox#17083]
### Deployment Type

NetBox Cloud

### NetBox Version

v4.0.8

### Python Version

3.10

### Steps to Reproduce

(Previous issue #16302 was closed, but I am pretty certain that this is in fact a bug, not an intended feature.)

This seems to be the case for all objects in Netbox, both in the Create New screen and in the Edit screen. I will use an IP address for this example.

Click on "Add new IP address"
Left click to the left of the name of any field (see the red X in the image below)
![image](https://github.com/user-attachments/assets/c49c4aef-40e7-4932-abcc-157cea6a0143)

The field will now act as if it was clicked, even though it obviously was not clicked
There seems to be a limit to how far left you can go before this stops occuring.

### Expected Behavior

When clicking outside of the field, the field should not act as if it was clicked.
Clicking on the red X in the image should do nothing (and close any open drop-downs).

### Observed Behavior

The field acts as if it was clicked, and the drop down opens up.

**Comment by DanSheps** [comment]
This is a result of <label> being used for the column definition.  It should be fairly trivial to wrap the label in a "col-sm-3" div and then have the label just there but I have not tested or anything.

If anyone is interested in taking this up, please feel free to ask for assignment here.
