### ISSUE TITLE
Allow Plugins to extend core filters

### ISSUE THREAD

**Issue by 9er-tom** [netbox-community/netbox#17084]
### NetBox version

v4.0.6

### Feature type

New functionality

### Proposed functionality

Plugins should be able to extend existing core filter sets, e.g. I have a custom assignment model which maps my custom model `System` to core model `Device`, similar to contact assignments.

I would now like to have the option to extend the Devices filter set to be able to filter for devices that are mapped to a specific `System`

### Use case

Mapping plugin models to core models seems like a widely used use-case. Being able to filter for said plugin models would enhance usability and be in line with core functionality.

**Comment by jeremystretch** [comment]
@9er-tom this is not an actionable FR in its current form. Please revise your post above to include a detailed implementation proposal.

**Comment by 9er-tom** [comment]
thanks for the response, I might take a look at the source code and try to implement a solution myself as soon as I find time for it.

I will close this for now
