### ISSUE TITLE
Exception for job details if object not set

### ISSUE THREAD

**Issue by alehaa** [netbox-community/netbox#17086]
### Deployment Type

Self-hosted

### NetBox Version

v4.1-beta1

### Python Version

3.11

### Steps to Reproduce

1. Create a new `JobRunner`.
2. Schedule the job runner without an instance being passed to `enqueue()`.
3. Navigate to jobs view
4. Open List item for newly created job

### Expected Behavior

Job details are shown.

### Observed Behavior

An exception is raised due to accessing `_meta` of the Job's `object`. However `object` is `None` as scheduled above.

This is due to 3028f26 introducing breadcrumbs for jobs. However, d6432fbcb886a8d900b2b24df85512371fa78d80 introduced the job object being optional around the same time.

**Comment by arthanson** [comment]
@alehaa do you want to take this one?

**Comment by alehaa** [comment]
@arthanson yep! :)
