### ISSUE TITLE
Add "auto" wireless channel

### ISSUE THREAD

**Issue by goteamkor** [netbox-community/netbox#17119]
### NetBox version

v4.0.8

### Feature type

Change to existing functionality

### Proposed functionality

There are many different channel selection options when selecting the 'wireless channel' dropdown in the 'wireless' section of adding/editing an interface.

Please add 'Auto' as an option.

### Use case

Many access points these days are managed in such a way that a central controller (on-prem or cloud) is constantly listening on all the radios to check for interference. And if found, will automatically change the channel on the radio for an access point.

Having an option to select 'auto' would correctly model access point radio interfaces that automatically change/update the channel they use rather than having an individual channel specifically assigned.

### Database changes

None

### External dependencies

None.

**Comment by jeremystretch** [comment]
Leaving the channel undefined for the interface implies that it is to be selected automatically; an explicit option for this is unnecessary.
