### ISSUE TITLE
Branch Activated notification duplicated on device edit

### ISSUE THREAD

**Issue by tardoe** [netbox-community/netbox#17114]
### Deployment Type

Self Hosted

### NetBox Version

v4.1-beta1

### Python Version

3.10

### Steps to Reproduce

1. Create a device
2. Create a new branch.
3. Activate the branch
4. Edit the device and click save

### Expected Behavior

When the branch is activated (step 3), the notification toast should be shown. When editing and saving the device under the branch, the "Branch Activated" notification toast shouldn't be shown or duplicated. 

### Observed Behavior

On save, multiple "Branch Activated" notifications are shown.
![Screenshot 2024-08-09 at 12 13 46](https://github.com/user-attachments/assets/0e465087-c6f9-472c-a7a3-bd08012827e6)

**Comment by jeremystretch** [comment]
@tardoe this report depends on the installation of a plugin which has not yet been released publicly. Have you been able to reproduce this in NetBox without involving a plugin?

**Comment by jeremystretch** [comment]
I've created #17144 to address this as a generic bug in NetBox v4.0.
