### ISSUE TITLE
Plugin Registry has incorrect information

### ISSUE THREAD

**Issue by peteeckel** [netbox-community/netbox#17116]
### Deployment Type

Self-hosted

### NetBox Version

v4.1-beta1

### Python Version

3.11

### Steps to Reproduce

1. Look into the "Plugins" view under "Admin"/"System"

### Expected Behavior

Correct information about installed and available plugins, obviously :-)

### Observed Behavior

The NetBox DNS plugin is listed twice, probably because I have it installed.

Once under the correct name "NetBox DNS", which is listed in the section where installed plugins reside. It's marked as uncertified there.

Another entry shows it under the name "DNS", with the correct author information but marked as "not local", "not installed", and "Not certified".

Apparently, neither entry is correct.

<img width="1262" alt="Screenshot 2024-08-09 at 21 09 40" src="https://github.com/user-attachments/assets/d51afded-529f-4c7d-b371-895442b82916">

**Comment by jeremystretch** [comment]
Please provide reproduction steps. This plugin does not appear in the list without being installed locally.

**Comment by peteeckel** [comment]
I have a version installed on my development system, so the first entry is most definitely referring to this installation. But even if you disregard that one, the second one has the wrong certification status and the wrong name.

**Comment by peteeckel** [comment]
This is also consistent with the screenshot from the blog - wrong name, wrong status.

<img width="968" alt="Screenshot 2024-08-10 at 16 10 38" src="https://github.com/user-attachments/assets/c517d0f3-a5c5-4bb9-8351-7507a6a28585">

**Comment by peteeckel** [comment]
Probably the two entries are a result of the name mismatch, which makes it impossible to correlate the installed one to the one from the registry. That leads me to the assumption that the entry in the registry is incorrect.

**Comment by jeremystretch** [comment]
Ok, if the issue is simply that the plugins catalog has incorrect data, that's not something we can address in NetBox itself (and should not be filed as a bug report).

Could you please send an email to `plugincatalog@netboxlabs.com` with the details to be corrected?

**Comment by peteeckel** [comment]
> Could you please send an email to `plugincatalog@netboxlabs.com` with the details to be corrected?

Sure, will do - thanks.

**Comment by peteeckel** [comment]
Hi @jeremystretch. meanwhile, thanks the help of Nat the information in the registry is fixed.

Certification status, author, publish and update time are still wrong once the plugin is installed. 

<img width="1280" alt="Screenshot 2024-08-13 at 11 43 11" src="https://github.com/user-attachments/assets/545252ff-a01e-4d76-b88a-018d8e38c261">

So I think this issue should be reopened.

**Comment by peteeckel** [comment]
Current "feature" has this fixed - thanks!
