### ISSUE TITLE
New interface types for IP radio / wireless networking.

### ISSUE THREAD

**Issue by sgvfr** [netbox-community/netbox#17128]
### NetBox version

4.06

### Feature type

Data model extension

### Proposed functionality

NetBox version
4.06

Feature type
New functionality

Proposed functionality
adding a new interface type for radio systems, which use N-type, TNC, or BNC connectors on the hardware. such as the Codan MT-4E transmitter/receiver cards (using N-type)

Use case
hardware used in radio systems, especially uhf/vhf are hybrid, and can combine IP interfaces with standard ethernet, and legacy connections to the field and antennas.

Database changes
i don't' believe this will need a new field.. but I'm not a coder.

External dependencies
No response

update

Apologies for the delay. I was on VA without internet access.

I am proposing 4 new connector types be included for device interfaces to accommodate a wide range of IP Radio rack mounted hardware currently in use by communications carriers and network providers. below are the most common types I used in the field, most often the "plug/male" is the cable connector, and the "jack/female" is the equipment side.

N-Type: (both plug and jack)
https://www.amphenolrf.com/rf-connectors/n-type-connectors.html
https://en.wikipedia.org/wiki/N_connector

TNC: (both plug and jack)
https://www.amphenolrf.com/rf-connectors/tnc-connectors.html
https://en.wikipedia.org/wiki/TNC_connector

BNC: (both plug and jack)
https://www.amphenolrf.com/rf-connectors/bnc-connectors.html
https://en.wikipedia.org/wiki/BNC_connector

SMA: (both plug and jack)
https://www.amphenolrf.com/rf-connectors/sma-connectors.html
https://en.wikipedia.org/wiki/SMA_connector

I hope this is enough for technical references you were looking for. If not let me know and I'll do what I can to provide you the right information.

some come in a "mini" size but for the purposes of netbox perhaps it doesn't need that much granularity?

Thank you!

### Use case

These additions include interface types available in many carrier grade IP wireless and radio systems available to communications provider networsk.

### Database changes

no database changes needed.. just additional interface types

**Comment by jeremystretch** [comment]
What you've listed are physical connector types for attaching an external antenna; they don't govern the transmission or receipt of data. The network interface type would likely be one of the IEEE 802.11 variants NetBox supports.

**Comment by sgvfr** [comment]
hi @jeremystretch    I'm not sure what you mean here??  how can I specify the correct interface for the module/device/port for a piece of radio equipment that uses these physical interface types?   Physically, the antenna is not connected to this device, a patch cable is connected to a ground bar with lighting arrestors, the lighting arrestors are connected to another cable, which in turn is connected to the antenna.. the actual antenna does not connect to the back of these devices.  These are absolutely not "WiFi" devices, they are UHF/VHF/Microwave radio systems powering carrier level communications networks.

![image](https://github.com/user-attachments/assets/0bbf6afb-13e1-4539-8662-dbe2191b75e2)

Rx and Tx are for transmitting and receiving data over the air..  how is the medium, which is LMR-400  or RG-142 copper cable any different than an ethernet patch cable in terms of physical connectivity?  Is there a different place i should put this request?

**Comment by DanSheps** [comment]
> Rx and Tx are for transmitting and receiving data over the air.. how is the medium, which is LMR-400 or RG-142 copper cable any different than an ethernet patch cable in terms of physical connectivity? Is there a different place i should put this request?

For wireless, we model the 802.11## variants, the physical infrastructure between the access point and the end of the antenna is not modelled

**Comment by sgvfr** [comment]
Ok, so what about modeling different wireless technologies?   802.11 varients are wifi, but that is not the only wireless in use, especially for carrier systems and point2point networks.   I do see a coaxial section, could these technologies not be put there instead?   "Other" is just very generic, while these are specific.On Aug 18, 2024 09:56, Daniel Sheppard ***@***.***> wrote:

Rx and Tx are for transmitting and receiving data over the air.. how is the medium, which is LMR-400 or RG-142 copper cable any different than an ethernet patch cable in terms of physical connectivity? Is there a different place i should put this request?

For wireless, we model the 802.11## variants, the physical infrastructure between the access point and the end of the antenna is not modelled

**Comment by sgvfr** [comment]
perhaps this will help me explain better

`If you wanted to model this, you would model your antenna as a separate device and then the stuff in between would be front/rear ports, but I don't think it would translate well IMO.`

 if I add a rear port, I can use BNC / N-type / SMA ect.. however, that doesn't really work as there wouldn't be a "front port" like it would be in a patch panel or 1:1 device such as a media converter, it does work with the lightning arrestors however, they are non-racked devices with N connectors.  Not ideal, but it works
![image](https://github.com/user-attachments/assets/7ca932f0-6adb-40c5-a192-1eca377e783b)


Here are the Interfaces used, which at this point is electrical, no different than an RJ-45 10/100 "interface"  which really is just electrical voltage across copper pairs..  the UHF/VHF radio frequency is also just a modulated AC voltage using a copper medium such as coaxial (LMR-400, RG-58, RG-142)
![image](https://github.com/user-attachments/assets/28ab85d0-c991-4c78-8ccc-12395456b3d6)

But, there are no options for this other than "WiFi".    There is a coaxial section, but only DOCSIS for what is usually a Cable ISP
![image](https://github.com/user-attachments/assets/6e5b2141-99c3-42fa-ba88-cc21df4b4be4)

It seems like the "device interface" is a technology, while a device front or rear "port" is a physical connection and not a technology.    IMO the physical connection would be perfectly suited in the interface "type" dropdown.    Or a new dropdown added for "physical connection type" where these could be selected for the technology/protocol ?

hope that helps describe a little better?

**Comment by DanSheps** [comment]
You need to think of the rear port as internal to the device
