### ISSUE TITLE
circuit type 'color' does not work

### ISSUE THREAD

**Issue by goteamkor** [netbox-community/netbox#17135]
### Deployment Type

Self-hosted

### NetBox Version

v.4.0.8

### Python Version

3.10

### Steps to Reproduce

Create a circuit type
Assing it a color (lets say indigo)
Create a circuit and assign it the circuit type

### Expected Behavior

When viewing the circuit, the 'type' column should highlight the type's value in the selected color.

### Observed Behavior

Circuit type only displays text, no colors.

Maybe I'm dumb and the circuit type color is meaningful somewhere else in NetBox?

**Comment by jeremystretch** [comment]
Please resubmit this as a [feature request]() as it is not intended behavior.

> Maybe I'm dumb and the circuit type color is meaningful somewhere else in NetBox?

Per #12216 color support was added to circuit types for cable tracing purposes.
