### ISSUE TITLE
Front/Rear Port Support for Power

### ISSUE THREAD

**Issue by adaemmer** [netbox-community/netbox#17140]
### NetBox version

v4.0.8

### Feature type

Change to existing functionality

### Proposed functionality

It shall be possible to route power through front port / rear port connection panel. Currently this is not possible for power connections.

### Use case

We have some maintenance connection panels in our racks and for some use cases we have a power patched through.

### Database changes

I guess there need to be some changes, but I not that deep into the schema.

### External dependencies

No new dependencies.

**Comment by alehaa** [comment]
I assume this use case should already be possible, using Power Ports and Outlets. You can create them with a 1:1 or 1:n mapping. However, the cable trace will stop at this device and traverse as for front/rear ports.

**Comment by arthanson** [comment]
@adaemmer is the power trace through the front/rear ports the main thing you are looking for?  Can you please update the feature request and provide some additional details?

**Comment by adaemmer** [comment]
@alehaa yes, this will do the trick, thank for clarifying and sorry for creating an issue for this.
@arthanson power trace was on hold with us for reasons I don't remember but as @alehaa pointed me to the existing solution I close this issue. Thanks for your comment.
