### ISSUE TITLE
Cluster objects do not properly honor tenancy

### ISSUE THREAD

**Issue by christopher-horn** [netbox-community/netbox#17156]
### Deployment Type

Self-hosted

### NetBox Version

v4.0.8

### Python Version

3.10

### Steps to Reproduce

1. Create a site called "site1" with no associated tenant so can be shared across tenants.
2. Create a tenant called "tenant1"
3. Create a tenant called "tenant2"
4. Create a cluster with the name "cluster" with site set to "site1" and tenant set to "tenant1"
5. Try to create a cluster with the same name "cluster" with site also set to "site1" but with tenant set to "tenant2"

### Expected Behavior

With no tenancy restriction on the site, I expect a new cluster to be created with the same name at the same site for the different tenant.

### Observed Behavior

The create fails with the error "Cluster with this Site and Name already exists."

**Comment by jeremystretch** [comment]
This is intended behavior. Each cluster must have a name unique to its site, as indicated by the error message, irrespective of its assignment to a particular tenant.

**Comment by christopher-horn** [comment]
But why should tenancy for a cluster behave any differently than it does for a device or virtual machine? We have multiple virtual machines with the same name in the same site but in different tenants without an issue. So I am very curious about the reasoning behind the design decision here.

**Comment by jeremystretch** [comment]
> So I am very curious about the reasoning behind the design decision here.

You are welcome to explore past discussion around the feature's implementation.
