### ISSUE TITLE
Debug toolbar fails to load css and scripts

### ISSUE THREAD

**Issue by theS1LV3R** [netbox-community/netbox#17158]
### Deployment Type

Self-hosted

### NetBox Version

v4.0.8

### Python Version

3.11

### Steps to Reproduce

1. Set `INTERNAL_IPS` to the correct IPs and `DEBUG` to true to allow the toolbar to be loaded

### Expected Behavior

Toolbar loads with correct styling and functionality

### Observed Behavior

HTML loads correctly, and requests are made by the browser to load css and js as well, however netbox returns a 404 and fails the loading.

Requests are made to `/static/debug_toolbar/css/toolbar.css`, `/static/debug_toolbar/css/print.css` and `/static/debug_toolbar/js/toolbar.js`, all three returns the same 404.

**Comment by arthanson** [comment]
@theS1LV3R can you please double-check, I run debug toolbar all day and just retried it, pip installed clean and cleared caches and it was fine.

**Comment by theS1LV3R** [comment]
I forgot to mention that I am running with Docker, if that affects anything. However I am using the standard [netbox Docker image](https://github.com/netbox-community/netbox-docker/pkgs/container/netbox).

But I have now retried, and still failed to load CSS and JS. I'll attempt a fresh install with the toolbar and update further. Would be weird if it occurred in docker but not otherwise.

**Comment by theS1LV3R** [comment]
The debug toolbar loads successfully when running the dev server as per [the installation instructions](https://netboxlabs.com/docs/netbox/en/stable/installation/3-netbox/). Is this maybe a docker specific issue in this case?

Reason for attempting to load the debug toolbar in the docker container is to investigate some slowness we're experiencing in our installation at my company that doesn't seem to be caused by hardware limitations, so we were hoping the debug toolbar may point us in the right direction.

**Comment by arthanson** [comment]
@theS1LV3R sounds like a docker issue as it loads successfully using the default install. I'd suggest opening up a discussion (https://github.com/netbox-community/netbox/discussions) as there are a lot in the community running under docker and they could help debug it.  Closing this issue.
