### ISSUE TITLE
IPAM page shows all services with IP's, not services associated with the IP.

### ISSUE THREAD

**Issue by ThomasADavis** [netbox-community/netbox#17163]
### Deployment Type

Self-hosted

### NetBox Version

netbox-687679c4bb-hrt96 NetBox Community v4.1.0-beta1

### Python Version

3.12

### Steps to Reproduce

1) create two devices with two different IP's.
2) create on each device, two different services.
3) check the IP page, and note that all services are listed, not just the one associated with the IP.

### Expected Behavior

Only services associated with the IP should show up.

### Observed Behavior

All services show up under the IP address.

same db copied between two instances shows this with the v4.07:
![Screenshot_2024-08-14_11-46-00](https://github.com/user-attachments/assets/89ab83dc-d053-486e-a317-cd48ae2dae6f)

and this with the v4.1beta1 instance:

![Screenshot_2024-08-14_11-47-07](https://github.com/user-attachments/assets/369c282b-7141-455b-816e-49c5a468e8b8)

I've stripped the netbox  v4.1b1 instances of all plugins and check to make sure this still occurs.

**Comment by arthanson** [comment]
If you just add the service and don't specifically associate it with the IP it will still show, tested on develop and it does not show.
