### ISSUE TITLE
Facility field missing in filters tab of locations

### ISSUE THREAD

**Issue by kipp-lucas** [netbox-community/netbox#17175]
### Deployment Type

Self-hosted

### NetBox Version

v4.0.8

### Python Version

3.10

### Steps to Reproduce

1. Click on Organization -> Locations -> filters

### Expected Behavior

A search field to search for a specific facility.

### Observed Behavior

There is no seperate search field for the facility. If I append to the url ``?facility=<my facility>``, I can search for a specific facility. But the field on the filters tab is missing.

**Comment by jeremystretch** [comment]
This is not a bug, as the facility filter is functional and just not included on the page, but you're welcome to resubmit this as a [feature request](https://github.com/netbox-community/netbox/issues/new?assignees=&labels=type%3A+feature%2Cstatus%3A+needs+triage&projects=&template=feature_request.yaml).

**Comment by jsenecal** [comment]
Related FR: https://github.com/netbox-community/netbox/issues/17177
