### ISSUE TITLE
option to easily filter/display only configured interfaces

### ISSUE THREAD

**Issue by goteamkor** [netbox-community/netbox#17187]
### NetBox version

v.4.0.8

### Feature type

New functionality

### Proposed functionality

Let's say you have a switch device that has 48 interfaces. Pretty common.
Let's say that only 19 of those interfaces are actually configured. Configured would be defined as having an IP, vlan, cable, connection, etc. associated with them.
It would be handy to check a box or toggle on the interfaces display page that would filter out all interfaces that are essentially "blank" so I can have only interfaces that are meaningful displayed in my view.

### Use case

Maybe 48 interfaces is paginated across 3 pages. But if only 19 of them are important to me, I can see all of them on the first page, without having to click through to multiple pages, or change my pagination settings and scroll up and down the screen having to mentally ignore interfaces that are unconfigured.

See screenshots. You are sort of able to accomplish something similar with the quick search and the view filter like "hide disabled", "hide disconnected", etc., but they only work if you actually type something in the quick search field. 

This toggle would work to basically just filter out any interface that has zero config associated with it.

![image](https://github.com/user-attachments/assets/9215445a-d7ac-4968-a4c8-33bb190353bf)

![image](https://github.com/user-attachments/assets/bcc9d925-fc65-4ed0-9686-937655569514)

### Database changes

none.

### External dependencies

none.

**Comment by jeremystretch** [comment]
The device interfaces list, like it peer component views, serves as a convenient listing of the interfaces assigned to a particular device. It is not intended to provide advanced filtering functionality. Instead, interfaces can be grouped by device and filtered by practically any attribute under the global interfaces list (`/dcim/interfaces/`).

> Configured would be defined as having an IP, vlan, cable, connection, etc. associated with them.

Those are all different qualifiers, and cannot be functionally lumped together as one. Alternatively, if you find yourself frequently searching for interfaces with a specific set of attributes, you can create a saved filter for these, which _can_ be applied to the device interfaces list.
