### ISSUE TITLE
Default class custom links invisible in dark mode

### ISSUE THREAD

**Issue by llamafilm** [netbox-community/netbox#17186]
### Deployment Type

NetBox Enterprise

### NetBox Version

v4.0.8

### Python Version

3.12

### Steps to Reproduce

1. Create a working custom link
2. Enable dark mode

### Expected Behavior

Button should be visible

### Observed Behavior

Button is invisible until you mouse over.
mouseover: <img width="85" alt="Screenshot 2024-08-15 at 10 50 07 PM" src="https://github.com/user-attachments/assets/b0f79530-cba5-461d-9c90-876a8c3719ea">
regular: <img width="104" alt="Screenshot 2024-08-15 at 10 50 03 PM" src="https://github.com/user-attachments/assets/2f1d6152-f9ed-400a-a100-11b4467a3422">

A similar bug was fixed in #15616 but for some reason it only fixes non-working links.  Working links are still invisible.

**Comment by arthanson** [comment]
Issue is here https://github.com/netbox-community/netbox/blob/develop/netbox/netbox/choices.py#L87 as btn-outline-dark is not visible in dark-mode.  However this would require a migration to change the values as the choice is stored in the DB, there are also a lot of references to btn-outline-dark in https://github.com/netbox-community/netbox/blob/develop/netbox/dcim/tables/template_code.py and https://github.com/netbox-community/netbox/blob/develop/netbox/templates/extras/inc/format_toggle.html which should probably be changes to btn-outline-secondary.
