### ISSUE TITLE
Add color to PDU outlets

### ISSUE THREAD

**Issue by ChrisRecioHive** [netbox-community/netbox#17195]
### NetBox version

v4.0.9

### Feature type

Data model extension

### Proposed functionality

Allow PDU power outlets to be assigned a color similarly to keystone and cable colors.

### Use case

Some PDU models have colored power outlets. Assigning a color to an outlet could allow for easier identification of plugs. For example, certain PDU models do not have numbered or labeled outlets but are instead identified by color. Another use case would be a quick way to identify different circuits within the PDU.

![image](https://github.com/user-attachments/assets/7fa71809-7e43-4c7e-a05c-6eb644823fe2)

**Comment by goteamkor** [comment]
This is an interesting request, but where in Netbox would the colors be reflected? 
On what pages or table views would the colors be significant?

**Comment by ChrisRecioHive** [comment]
> This is an interesting request, but where in Netbox would the colors be reflected? On what pages or table views would the colors be significant?

I believe it would be most useful on PDU power outlets table. Below are a couple ideas of how it could be implemented. 

![image](https://github.com/user-attachments/assets/7a0f3d25-ab4f-4191-8fab-b4f9e6d96c45)
![image](https://github.com/user-attachments/assets/ef624d99-e4b2-461f-a306-f6def8f091f1)
![image](https://github.com/user-attachments/assets/87125427-224a-4bd8-865c-3cf368fbb30c)

**Comment by jeremystretch** [comment]
We added color support to front & rear pass-through ports a while back. I assume we would just replicate that functionality for power ports & outlets.

**Comment by jeremystretch** [comment]
Should we add a `color` field for power ports as well?
