### ISSUE TITLE
Description not saved when assigning module to a slot

### ISSUE THREAD

**Issue by sgvfr** [netbox-community/netbox#17203]
### Deployment Type

Self-hosted

### NetBox Version

v4.0.9

### Python Version

3.12

### Steps to Reproduce

create device with module bays
create module with interfaces
assign module to a device module slot and fill in description
save.

description is not saved, but does when editing the module assignment after.

### Expected Behavior

I expected the description to be saved.

### Observed Behavior

description is not saved, no error message

**Comment by jeremystretch** [comment]
I assume you're referring to module _types_ and not modules, though it's difficult to tell from your extremely low-effort description above.

As has been pointed out in numerous previous issues, descriptions are intentionally not replicated from component templates. This would not make sense as it would merely result in duplicated data. Please remember to search for existing issues before opening a new one.

**Comment by sgvfr** [comment]
Wow, that was pretty uncalled for @jeremystretch 

This is not the module type.  I will create a new issue that perhaps pleases you with more effort..

**Comment by jeremystretch** [comment]
> Wow, that was pretty uncalled for @jeremystretch

This is not a support forum. Please be respectful of others' time and invest more effort when opening a GitHub issue.

> I will create a new issue that perhaps pleases you with more effort..

It's not a matter of pleasing me, but of simply following directions:

> Describe in detail the exact steps that someone else can take to reproduce this bug using the current stable release of NetBox. Begin with the creation of any necessary database objects and call out every operation being performed explicitly.
