### ISSUE TITLE
Add EVPN-VPWS to the L2VPNTypeChoices Choice set. 

### ISSUE THREAD

**Issue by caskings** [netbox-community/netbox#17216]
### NetBox version

v4.0.9

### Feature type

Data model extension

### Proposed functionality

EVPN-VPWS is a point to point L2VPN service that breaks the current model for VPWS and other P2P types in the L2VPN termination list as it allows for multiple interfaces across multiple network devices to the same endpoint or location. In either an Active / Active or Active / Passive mode. 

Suggested change 

Add TYPE_EVPN_VPWS to the L2VPNTypeChoices class, but don't add it to L2VPNTypeChoices.P2P

Relevant RFC: https://datatracker.ietf.org/doc/html/rfc8214

### Use case

This would allow Netbox users to model EVPN-VPWS separately from RFC4664 type VPWS which doesn't support Active / Active across multiple devices to the same location.

**Comment by Brekmister** [comment]
My work is moving towards EVPN-VPWS as well. This would be a nice addition to model.

**Comment by caskings** [comment]
@DanSheps I'm happy to have a go at creating a pull request for this.

**Comment by ajackson79** [comment]
Adding another voice to this in hopes it gets added.

**Comment by DanSheps** [comment]
@caskings Added you to work on it, please proceed with the PR
