### ISSUE TITLE
Version information in the plugin information page is not current

### ISSUE THREAD

**Issue by peteeckel** [netbox-community/netbox#17213]
### Deployment Type

Self-hosted

### NetBox Version

v4.1-beta1

### Python Version

3.11

### Steps to Reproduce

1. Click on 'Admin'/'Plugins'
2. Click on the title of the 'NetBox DNS' plugin

### Expected Behavior

The version tab on the right hand side shows current version and release information

### Observed Behavior

<img width="560" alt="Screenshot 2024-08-20 at 09 28 21" src="https://github.com/user-attachments/assets/0cd537e7-0ddb-4260-bad8-111d1bfff461">

1. Versions 1.0.5 (released to PyPI on July 22nd) and 1.0.6 (released to PyPI on August 14th) are missing
2. The release dates are incorrect (all of them, and neither matches a real release date)
3. The compatibility information shows NetBox 4.0.8, which was released on July 26th, well after DNS 1.0.5, which is missing

**Comment by arthanson** [comment]
This looks like an issue with the API.
