### ISSUE TITLE
Edit button and co. difficult to access for many columns from version 4.xx onwards.

### ISSUE THREAD

**Issue by LHBL2003** [netbox-community/netbox#17224]
### Deployment Type

Self-hosted

### NetBox Version

v4.0.9

### Python Version

3.10

### Steps to Reproduce

- Open device list (Device --> Device menu)
- Many entries (add more than one display height)
- Show many columns. (More than the screen width supports.)

### Expected Behavior

A horizontal scroll bar should be displayed in the lower view area so that you can reach the editing buttons of the row.
This was possible before version 4.

### Observed Behavior

Since version 4 and the revised design, horizontal scrolling is only possible if you scroll to the end of the list or have a mouse with a horizontal scroll function. So you have to scroll all the way down, slide to the right and scroll up again. Or reduce the view to 50%. Or you buy a curved monitor. The list should again be scrollable horizontally and vertically via the mouse pointer.

![image](https://github.com/user-attachments/assets/8779bcd9-2d31-4d42-8cbd-0a2bae2bdc6d)

**Comment by arthanson** [comment]
So this basically works the same in v3.7 and v4.1 the difference is the collapsible sidebar in v3.7 and the columns are spaced a bit different (wider) in v4.1.  See screenshot, the v3.7 has the buttons partially obscured at this width, going smaller will just collapse the sidebar in v3.7.

If we needed to add scrollbars to the top of the table a potential solution might be: https://stackoverflow.com/questions/3934271/horizontal-scrollbar-on-top-and-bottom-of-table

![Devices | NetBox 2024-09-23 10-37-11](https://github.com/user-attachments/assets/88c3e003-b6c3-4c82-8144-4f9ff4e1086b)

**Comment by LHBL2003** [comment]
In fact, the scrollbar only appears when you are at the very bottom. I remembered it differently. Maybe I had fewer lines at the time.
![image](https://github.com/user-attachments/assets/92e05360-5c30-4c25-aeb3-602eb746ebcf)


The idea of having the scrollbar at the top is not bad. However, you would have to fix the table header, because otherwise you can't scroll horizontally in the middle again. A positive side effect would be that you always know which column it is.
![image](https://github.com/user-attachments/assets/0ff3b458-65bc-4ac2-9408-be0d556e656e)

Would this be a good idea?
Can you customize this?

**Comment by arthanson** [comment]
Closing as needs to be a feature request.
