### ISSUE TITLE
Device platform and device type platform

### ISSUE THREAD

**Issue by lucafabbri365** [netbox-community/netbox#17231]
### NetBox version

v4.0.9

### Feature type

Change to existing functionality

### Proposed functionality

- Assuming a device type **ProLiant X** from manufacturer **HPE**
- Assuming the device platform **VMware ESXi Y** from manufacturer **VMware**
- Assuming a device **SRV01** created from the device type ProLiant X
- Device SRV01 hosts VMware ESXi Y as OS

I cannot assign platform **VMware ESXi Y** to device **SRV01**; Error: _The assigned platform is limited to VMware device types, but this device's type belongs to HPE._

How about allowing the assignment of a platform from a specific manufacturer (_e.g. VMware_) to a device created from a device type of another manufacturer (_e.g. HPE_) ?

### Use case

In a real world I could have a device from one manufacturer (e.g. HPE) and an OS (platform) from another manufacturer (e.g. VMware or Microsoft).

**Comment by stavr666** [comment]
Platform = Firmware.
We use custom field (Object: Platform type) for described case. But it's kinda inconvenient, since not visible in platform table.

Good way to fix it: add optional "Installed OS" field (like optional OOB IP) for devices with Platform selector without vendor-lock.

**Comment by jeremystretch** [comment]
[Per the documentation](https://netboxlabs.com/docs/netbox/en/stable/models/dcim/platform/#manufacturer), the manufacturer field is used to optionally limit the device types on which a platform may be installed. For example, Cisco IOS can only be installed on Cisco devices. If this does not apply to a platform, as in your scenario, simply leave it blank.

This has been discussed in previous issues. Please remember to search closed issues before opening a new one.
