### ISSUE TITLE
add return_url  to 'xx ips available' buttom

### ISSUE THREAD

**Issue by PieterL75** [netbox-community/netbox#17255]
### NetBox version

v4.0.8

### Feature type

Change to existing functionality

### Proposed functionality

In a prefix-ipaddress overview, there is a label with available ips'.
clicking that brings you to the edit page of the first ip available.
https://netbox/ipam/ip-addresses/add/?address=172.26.24.133/27&vrf=9
![image](https://github.com/user-attachments/assets/5387355e-557d-4ca5-9ca6-c245f8212371)

my proposal is to add a 'return_url' to that link, similar as on the '+ Add IP Address' button on the topright
https://netbox/ipam/ip-addresses/add/?address=172.26.24.133/27&vrf=9&return_url=/ipam/prefixes/8755/ip-addresses/
![image](https://github.com/user-attachments/assets/a79f137f-377a-45be-a9b4-5f75ad9f3b12)

### Use case

This will make the behavior consistent for both buttons.

**Comment by alehaa** [comment]
I can file a PR for this.
