### ISSUE TITLE
Add a few cm / inches of free space under the “Admin” menu item. 

### ISSUE THREAD

**Issue by LHBL2003** [netbox-community/netbox#17252]
### NetBox version

v4.0.9

### Feature type

Change to existing functionality

### Proposed functionality

Add a few cm / inches of free space under the “Admin” menu item. 

### Use case

To make it easier to recognize the last element when scrolling, you need more space under the last menu item. This is because the https://... text gets in the way. This was not a problem in version 3.x.x.
![image](https://github.com/user-attachments/assets/430e80d7-1a36-4dd7-b727-c81f07a06fc3)

### Database changes

no

### External dependencies

no

**Comment by goteamkor** [comment]
related: https://github.com/netbox-community/netbox/issues/16725

**Comment by jeremystretch** [comment]
This was addressed at some point during the v4.1 beta release, though I couldn't find the specific commit. Extra vertical padding has been added to the end of the navigation menu.

![screenshot](https://github.com/user-attachments/assets/5829f44d-ff08-4c7a-ac08-c4af4e031fdc)
