### ISSUE TITLE
Path splitt! in one direction, reverse way OK.

### ISSUE THREAD

**Issue by ByteAndBits** [netbox-community/netbox#17273]
### Deployment Type

Self-hosted

### NetBox Version

4.0.9

### Python Version

3.10

### Steps to Reproduce

1. Create a device (DA)with interface
2. create a patchpannel (PA)with one front und on rear port (1:1)
3. create a second patchpannel (PB) with two font and two rearports (1:1)
4. create a second device (DB)
5. Connect DA -> front port PA 
6. Connect DB -> both front ports PB
7. Connect Rearport PA -> both rear Ports PB
8. Run Trace from both devices

### Expected Behavior

The trace from both sides shoud work. But only from on side working.
If you click to select a node, the trace worked from both sides

![1](https://github.com/user-attachments/assets/119b9d07-3c28-4bde-bf63-69e5b4c132a6)
![2](https://github.com/user-attachments/assets/2448c58f-9f99-4c40-a2ab-04405ec9f6fc)

### Observed Behavior

The trace only worked from the side with the both front ports correctly. from the side with on front port path splitt.

That´s a normal situation for us. LWL duplex to LWL simplex.

**Comment by bctiemann** [comment]
This is duplicated by https://github.com/netbox-community/netbox/issues/17400. Going to close this one and refer to that issue as it has more detailed repro steps, but this one is also valuable so I'll maintain a backlink.
