### ISSUE TITLE
The main menu on the left site didn't get updated in the transalated version (german)

### ISSUE THREAD

**Issue by chbally** [netbox-community/netbox#17304]
### Deployment Type

Self-hosted

### NetBox Version

v.4.0.10

### Python Version

3.12

### Steps to Reproduce

Several Buttons still have the original text, even if they are translated:
![grafik](https://github.com/user-attachments/assets/f22818a3-03c3-49fb-909d-fe25a62a3a7b)

### Expected Behavior

We translated all dash connected words in single words: "Rack-Rollen" to "Rackrollen" English original is: rack-rolls
On every page this is changed - but not in the menu.

### Observed Behavior

Translated words also in menu

**Comment by jeremystretch** [comment]
It looks like the updated strings were pulled for the v4.0.10 but didn't compiled. This will be fixed in the next release (v4.0.11).
