### ISSUE TITLE
Plugin navigation menu buttons' background color differs from built-in navigation menu buttons

### ISSUE THREAD

**Issue by atownson** [netbox-community/netbox#17316]
### Deployment Type

Self-hosted

### NetBox Version

v4.1.0-beta1

### Python Version

3.12

### Steps to Reproduce

Install a plugin with navigation menu items that contain buttons (i.e. Add item button).

Light mode test:
1. Set the UI to Light mode.
3. Observer the plugin buttons background color compared to the built-in buttons.
4. Hover over the plugin buttons and observe the background color transition compared to the built-in buttons.

Dark mode test:
1. Set the UI to Dark mode.
2. Observe the plugin buttons background color compared to the built-in buttons.
3. Hover over the plugin buttons and observe the background color transition compared to the built-in buttons.

### Expected Behavior

The plugin button background colors match the built-in button background colors, both with and without hovering over the buttons.

### Observed Behavior

The background colors differ.

Light mode result:
![image](https://github.com/user-attachments/assets/222b6c80-f37e-44f4-8b25-866205ecf515)
Light mode result when hovering:
![image](https://github.com/user-attachments/assets/278d8863-2639-423f-a399-bf4f9d587673)

Dark mode result:
![image](https://github.com/user-attachments/assets/2b411a37-f486-498b-ba42-5af479565ef9)

**Comment by jeremystretch** [comment]
I believe this was addressed indirectly via one of the cosmetic bug fixes in the recent v4.0.10 release. Plugin menu buttons now render identically to native menu buttons in the current `feature` branch.

**Comment by atownson** [comment]
Awesome, thank you.
