### ISSUE TITLE
Trace entire cable path from power port to upstream power panel

### ISSUE THREAD

**Issue by mathieumd** [netbox-community/netbox#17335]
### NetBox version

v4.0.9

### Feature type

Change to existing functionality

### Proposed functionality

As described in #9518, power cables should be traceable from panel to end-device.

I may be wrong, but according to https://github.com/netbox-community/netbox/issues/17140#issuecomment-2286958498, it's still not possible.

### Use case

See at a glance the full path of power circuit.

**Comment by mathieumd** [comment]
I can test and debug the feature, but unfortunately have no the skills to code it... I tried to look the files to see if I can find the starting point, but even this was a failure :-/

**Comment by jeremystretch** [comment]
Ok, then there's no need to open a duplicate issue for the original one.
