### ISSUE TITLE
Add Nema L22-20 outlet type

### ISSUE THREAD

**Issue by ChrisRecioHive** [netbox-community/netbox#17347]
### NetBox version

v4.0.11

### Feature type

Data model extension

### Proposed functionality

Include both Nema L22-20P and L22-20R connector types to power ports and power outlet types.

### Use case

Certain PDUs use these connectors and there is currently no available outlet type to document these PDUs.

**Comment by kmorin18** [comment]
For reference, this is similar to #7892 but a different Amperage

**Comment by jeremystretch** [comment]
@amit177 please comment here so that the issue can be assigned to you and your PR can be reviewed.

**Comment by amit177** [comment]
Opened PR #17399 for this
