### ISSUE TITLE
Text only printable view for cable trace 

### ISSUE THREAD

**Issue by dionrowney** [netbox-community/netbox#17351]
### NetBox version

v4.0.7

### Feature type

New functionality

### Proposed functionality

Selectable text only version or printable view that prints nicer cable trace 

### Use case

We often have cable paths with 3-4+ hops from device to device through panels.

Our technicians would often like to have a paper version in the field.

Our legacy system allowed users to print off the path in about 2 inches on a single page.  If you print the trace in netbox the SVG makes it about 6 pages.

I was able to make a script to do this but it is not easy nor convenient and I cannot add a custom button/link to the trace screen. 

Would having a selectable text version or print view that prints nicer be possible?  There is already a SVG link, can we have a Text Version Link under that?

### Database changes

none

### External dependencies

none

**Comment by dionrowney** [comment]
Can plugins add to the existing trace screen?  If it should I dont know how to do that.

**Comment by jeremystretch** [comment]
@dionrowney @arthanson means you'll need to develop a custom plugin to provide a separate view providing the data the way you want to see it displayed. This isn't something we'll pursue in core NetBox.
