### ISSUE TITLE
htmx:targetError on home page of NetBox

### ISSUE THREAD

**Issue by TheGuardianLight** [netbox-community/netbox#17359]
### Deployment Type

Self-hosted

### NetBox Version

v4.1.0

### Python Version

3.10

### Steps to Reproduce

Click on the cog icon on the ‘NetBox News’ widget

### Expected Behavior

Display “NetBow News”'s widget settings

### Observed Behavior

After updating to NetBox 4.1.0, I can no longer open the settings for the "NetBow News" widget on the home page.

On the browser console, I get this error:
![image](https://github.com/user-attachments/assets/ec6d2227-6d39-4a54-a8c7-4318b341c0e4)

The error occurs for any other widget on the home page.

**Comment by arthanson** [comment]
@TheGuardianLight can you please re-check the reproduction steps, I can click on the gear / cog icon fine and it brings up the settings dialog fine.
![Home | NetBox 2024-09-04 07-20-27](https://github.com/user-attachments/assets/63647236-1cce-4b69-ab4a-bb71090338a4)

**Comment by TheGuardianLight** [comment]
> can you please re-check the reproduction steps

Sadly I can't do more.
There is a video of my problem : 

https://github.com/user-attachments/assets/0d6c3847-fd14-4011-b99f-f4703aed8973

**Comment by TheGuardianLight** [comment]
I would like to point out that this works on another instance, another server. I don't understand what the problem is.
