### ISSUE TITLE
Directory Browsing is Enabled for Static file path in Apache2 config that ships with NetBox

### ISSUE THREAD

**Issue by marsteel** [netbox-community/netbox#17375]
### Deployment Type

Self-hosted

### NetBox Version

v4.1.0

### Python Version

3.10

### Steps to Reproduce

1. access URL/static 
2. static files are browseable

Root cause:

Indexes is enabled for /static in
https://github.com/netbox-community/netbox/blob/684cdda8f4dcf408b462b8b632446f4b5df7fb67/contrib/apache.conf#L23

```
    <Directory /opt/netbox/netbox/static>
        Options Indexes FollowSymLinks MultiViews
        AllowOverride None
        Require all granted
    </Directory>
```

Suggestion:

Remove Indexes so Directory Browsing is disabled for static file path. 

### Expected Behavior

1. access URL/static 
2. static files are hidden
 `Forbidden
You don't have permission to access this resource.`

### Observed Behavior

static files are browseable

**Comment by arthanson** [comment]
@marsteel do you want to submit a PR to change this?
