### ISSUE TITLE
'Changelog' tab not visible for non-admin accounts

### ISSUE THREAD

**Issue by peteeckel** [netbox-community/netbox#17387]
### Deployment Type

Self-hosted

### NetBox Version

4.1.0

### Python Version

3.12

### Steps to Reproduce

1. Create a user with view permission for all object types and log in as that user.
2. Open an object detail view for an arbitrary object (e.g. an IPAM IP Address).

### Expected Behavior

The 'Changelog' tab should be visible.

### Observed Behavior

No 'Changelog' tab is shown.

**Comment by peteeckel** [comment]
The issue is in the definition of the `ObjectChangeLogView` class. The permission that is required according to the class is `extras.view_objectchange` while it should be `core.view_objectchange`.

I'll provide a PR if accepted.

**Comment by peteeckel** [comment]
In fact there are multiple instances of the same bug:
```
(netbox) [root@dns netbox]# git grep 'extras\..*_objectchange'
netbox/netbox/views/generic/feature_views.py:        permission='extras.view_objectchange',
netbox/templates/account/profile.html:  {% if perms.extras.view_objectchange %}
netbox/templates/users/user.html:  {% if perms.extras.view_objectchange %}
```

**Comment by arthanson** [comment]
I've assigned to you @peteeckel
