### ISSUE TITLE
Table rendering inconsistencies between NetBox 3.7 and 4.1 during copy-paste

### ISSUE THREAD

**Issue by Dakson13** [netbox-community/netbox#17398]
### Deployment Type

Self-hosted

### NetBox Version

v4.1.0

### Python Version

3.10

### Steps to Reproduce

I've encountered a significant difference in how tables are rendered between NetBox 3.7 and 4.1 when copying data into Word documents. As part of my task to document the current state of our network infrastructure, I often copy tables from NetBox and paste them into Word.
In NetBox version 3.7, the table formatting in Word closely matches the original NetBox table. However, in version 4.1, the table formatting appears different, with certain elements either missing or altered. This discrepancy complicates the process and creates inconsistencies in documentation.
I've attached screenshots comparing the two versions to illustrate the issue:

1.	In NetBox 4.1, copy a table.
2.	Paste the table into a Word document.
3.	Compare the formatting and structure with the same process in NetBox 3.7.

![ss1](https://github.com/user-attachments/assets/ed12e550-618d-44cc-b905-2ac85bfa9c90)
![ss2](https://github.com/user-attachments/assets/f467849f-a69b-4fb0-af4f-5dc2de2010c0)

### Expected Behavior

The table formatting in NetBox 4.1 should remain consistent with the previous version when copied into Word, preserving all elements and structure.

### Observed Behavior

In version 4.1, the table formatting appears different, with certain elements either missing or altered.

**Comment by jeremystretch** [comment]
Copying and pasting HTML content from the user interface into a word processor has never been a supported function in NetBox. If it ever worked on a previous release it's entirely coincidental. If this is something you need to do, you'll need to craft a custom [export template](https://netboxlabs.com/docs/netbox/en/stable/customization/export-templates/) to generate the desired HTML markup.
