### ISSUE TITLE
Move Netbox Version number to a more sensible and always accessible area

### ISSUE THREAD

**Issue by bluealein56** [netbox-community/netbox#17396]
### NetBox version

v3.78

### Feature type

Change to existing functionality

### Proposed functionality

Move the Netbox version nunber to a more appropriate place, which imo makes sense that it would go in the info drop down menu in the top right corner of every page. 

<img width="156" alt="Screenshot 2024-09-06 at 2 59 44 AM" src="https://github.com/user-attachments/assets/3a40b4e1-8bd5-4c05-8750-ea23a73e2e6b">

### Use case

This menu is always accessible no matter where you are in the app and without having to scroll. It also frees up space making the page more appeasing and less cluttered. The version number isnt something that necessarily needs to be displayed on every page at all times, more often than not, it is not needed, and when it is, you may have to scroll through 500 lines of devices, or whatever. just add a new option in the drop down or just display the netbox version here wihtout any additional clicks or scrolling. 

### Database changes

i do not believe this would require a db change

**Comment by goteamkor** [comment]
How is at the bottom right corner of every single page not sensible or always accessible?

![image](https://github.com/user-attachments/assets/f9ff2dc9-bfcb-49ca-a659-f3c0c6787900)

**Comment by bluealein56** [comment]
> > This menu is always accessible no matter where you are in the app and without having to scroll
> 
> How is at the bottom right corner of every single page not sensible or always accessible? It's always accessible no matter where you are in the app, and I don't have to click 2 or 3 times to find it.   ![image](https://private-user-images.githubusercontent.com/174816558/365231909-f9ff2dc9-bfcb-49ca-a659-f3c0c6787900.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU2Mzk0MzcsIm5iZiI6MTcyNTYzOTEzNywicGF0aCI6Ii8xNzQ4MTY1NTgvMzY1MjMxOTA5LWY5ZmYyZGM5LWJmY2ItNDljYS1hNjU5LWYzYzBjNjc4NzkwMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwNlQxNjEyMTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xZGQ1OWMzOWFiZmQyOGM0Yjk2YzUyNzZjNTY3NTQxMGVkZmI3MjQwZmNkMzEzOGUxNGRjNThhOTdiMjUxMjA0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.MEw2-9P0lYKuZvXmfGGerfh5oVD3t9F9vuIxtewIIfI)

It could be at the bottom of a 500 line page and you have to scroll to get to it. One click at the top of the page no matter where your scroll is would give you the needed info, not 2-3 clicks or 10 seconds of scrolling.

**Comment by jeremystretch** [comment]
It's at the bottom of the page because it's not something users frequently need to reference. And on the rare occasion you do, pressing the "end" key on your keyboard takes you to it immediately.
