### ISSUE TITLE
Unable to trace cables with a Path Split on two sides of a path

### ISSUE THREAD

**Issue by derjam** [netbox-community/netbox#17400]
### Deployment Type

Self-hosted

### NetBox Version

v4.1.0

### Python Version

3.12

### Steps to Reproduce

We have an Evironment with 40G Switch Ports, which we split up with a cable to 4 x LC Connections. to a patch Panel. On the other side we have the same cable and go from 4 x LC to one 40G Switch Port. I found the error in our self-hosted netbox with a bit more complicated setting. But I was able to reproduce it with the netbox demo environment.

1. Create a Switch called SwitchA
2. Create a Switch called SwitchB
3. Create a Patch Panel called PP1
4. Create a Patch Panel called PP2
5. Cable Front Ports 1-4 from PP1 to Front Ports 1-4 to PP2
6. Cable GigabitEthernet1/0/1 from SwitchA to PP1 Rear Ports 1-4
7. Cable GigabitEthernet1/0/1 from SwitchB to PP2 Rear Ports 1-4

### Expected Behavior

You should be able to do a cable trace.
First you get a Path Split and select one Path:
![netbox2](https://github.com/user-attachments/assets/b7ba786a-9235-4d91-b100-c6d0bebd451e)
And then you should see the trace:
![netbox3](https://github.com/user-attachments/assets/e5359637-e81d-4e28-9be4-1f02278a1211)

### Observed Behavior

You get the Path Split and you can select one Path:
![netbox2](https://github.com/user-attachments/assets/b7ba786a-9235-4d91-b100-c6d0bebd451e)#
But instead you get a Error, no Path is found:
![netbox4](https://github.com/user-attachments/assets/b9a37639-599b-4eef-bc21-7bf9a224d025)

But when you change the connection from one switch interface to only one rear Port on the Patch Panel it works and you are able to trace this connection. 

So you go from this:
![netbox6](https://github.com/user-attachments/assets/37f4e60d-939b-49b5-98c3-33bab4fcdd0b)
To this setting:
![netbox7](https://github.com/user-attachments/assets/0e404fb5-ad2c-470c-85d4-1c75cf4a0c06)
It works, you can trace from both directions.

**Comment by bctiemann** [comment]
See also https://github.com/netbox-community/netbox/issues/17273 which I closed as a duplicate though it was opened earlier; its repro steps are also valid but are less detailed than in this one.

**Comment by bctiemann** [comment]
By all means!
