### ISSUE TITLE
wrong order of module bays

### ISSUE THREAD

**Issue by Jarod2801** [netbox-community/netbox#17449]
### Deployment Type

Self-hosted

### NetBox Version

v4.0.9

### Python Version

3.10

### Steps to Reproduce

1. create a device type
2. create modile bays in this device type
    a.) Name: "Slot [0-16]"
    b.) Label: "Slot [0-16]"
    c.) Position: "[0-16]"
3. create a device of that type

In the created device, module bays are shown but in wrong order.
Expected orden would be
0-1-2-3-4-5-6-7-8-9-10-11-12-13-14-15-16
But the order is
0-1-10-11-12-13-14-15-16-2-3-4-5-6-7-8-9

This is really annoying when having a 16 Slot-Shelf in front of you and NetBox is displaying the Slots in a wrong order.

### Expected Behavior

order 
0-1-2-3-4-5-6-7-8-9-10-11-12-13-14-15-16

### Observed Behavior

order
0-1-10-11-12-13-14-15-16-2-3-4-5-6-7-8-9

**Comment by arthanson** [comment]
@Jarod2801 can you please check this on NetBox v4.1 as I think it is either fixed or I can't reproduce.  I just created a new device type and added the module bays as per your repro and the ordering was correct:
![APC tdev1 | NetBox 2024-09-11 07-42-10](https://github.com/user-attachments/assets/044e6d25-afe5-4a7c-9e91-fe2c424681b5)

**Comment by Jarod2801** [comment]
Have you created a device as of that type?

I am offline ATM but I think it happened when creating the device, not the module bays in the device type

**Comment by arthanson** [comment]
@Jarod2801  yes, it looks fine:
![aaa | NetBox 2024-09-11 07-56-13](https://github.com/user-attachments/assets/6856bb39-9156-4f09-8039-381e26222ff7)

**Comment by Jarod2801** [comment]
Hm.

I will have to recheck.

**Comment by Jarod2801** [comment]
I tried to reproduce but it looks like I made sth. wrong yesteday.
Order looks fine.

So I also can`t reproduce
