### ISSUE TITLE
Event Rules not creating jobs

### ISSUE THREAD

**Issue by PaulR282** [netbox-community/netbox#17444]
### Deployment Type

Self-hosted

### NetBox Version

v4.1.0

### Python Version

3.12

### Steps to Reproduce

1. Create an Event Rule to e.g. trigger a script when a device is created
2. Create a device

### Expected Behavior

Job should be created running the script

### Observed Behavior

No job is created. (Docker Container) console output:
`Cannot import events pipeline extras.events.process_event_queue error: core.models.jobs.Job.enqueue() got multiple values for keyword argument 'name'`

**Comment by aaronhuff** [comment]
I have the same problem with my post upgrade testing. I replicated this in both my dev and test environments.
