### ISSUE TITLE
Add monit integration to wiki

### ISSUE THREAD

**Issue by thomas-mc-work** [netbox-community/netbox#17461]
### Change Type

Addition

### Area

Plugins

### Proposed Changes

Hello,

could you please add this integration to [the community contribution in the wiki](https://github.com/netbox-community/netbox/wiki/Community-Contributions#integrations):

[netbox2monit](https://codeberg.org/thomas-mc-work/netbox2monit) – creates a monit configuration based on the machines of a Netbox instance

Thank you!

**Comment by jeremystretch** [comment]
Added
