### ISSUE TITLE
Add Outlet type C39

### ISSUE THREAD

**Issue by Etibru** [netbox-community/netbox#17471]
### NetBox version

v4.0

### Feature type

Data model extension

### Proposed functionality

It would be interesting to have the C39 outlet type (C13/C19 
COMPATIBLE)

### Use case

Add PDU models or other Eaton brand equipment to Netbox

### Database changes

```json
"type": {
        "value": "iec-60320-c39",
        "label": "C39"
    },
```
or 
```json
"type": {
        "value": "eaton-c39",
        "label": "C39"
    },
```

**Comment by jeremystretch** [comment]
AFAICT C39 is not an [IEC 60320](https://en.wikipedia.org/wiki/IEC_60320) standard outlet type, but rather a proprietary form factor produced by Eaton. Is that accurate?

**Comment by Etibru** [comment]
Exactly, it's an Eaton design, a bit like Juniper's VPC ports :
```json
    "type": {
        "value": "juniper-vcp",
        "label": "Juniper VCP"
    },
```

**Comment by jeremystretch** [comment]
Ok, just noting that this will need to be listed under the proprietary group and not IEC 60320.

**Comment by jsenecal** [comment]
You can assign this to me
https://github.com/jsenecal/netbox/tree/17471-c39
