### ISSUE TITLE
Add generic device in rack (cable managers, covers, etc)

### ISSUE THREAD

**Issue by Etibru** [netbox-community/netbox#17473]
### NetBox version

v4.0

### Feature type

New functionality

### Proposed functionality

It would be interesting to be able to add equipment to the Racks that are neither devices nor reservations. For example, grommet, cable Managers, covers, etc.
This would provide a better representation of the reality of datacenter racks

### Use case

On a rack to occupy rack Units (U) but without unique modeling as could be done with devices or rack reservations.

**Comment by Etibru** [comment]
Yes, you're right, it can be a functional model, but from my point of view, a blanking panel, drawer or cable manager isn't really a device. Despite that, i think it's the only way to model it effectively.

**Comment by goteamkor** [comment]
> Yes, you're right, it can be a functional model, but from my point of view, a blanking panel, drawer or cable manager isn't really a device. Despite that, i think it's the only way to model it effectively.

https://demo.netbox.dev/static/docs/core-functionality/devices/
> Every piece of hardware which is installed within a site or rack exists in NetBox as a device.

Not saying your point of view is wrong, but NetBox's point of view is clear.

**Comment by alehaa** [comment]
I think this was already discussed in https://github.com/netbox-community/netbox/issues/16308.

**Comment by jeremystretch** [comment]
It has been raised several times. As has been discussed in previous issues, there is no substantial difference between the cited objects and other devices. They can be modeled in NetBox as unnamed devices quite easily.
