### ISSUE TITLE
Can not create rack reservation without rights to read all system users

### ISSUE THREAD

**Issue by stavr666** [netbox-community/netbox#17486]
### Deployment Type

NetBox Cloud

### NetBox Version

v4.0.8

### Python Version

3.11

### Steps to Reproduce

1. Create permission set with view+add+change+delete rights to devices, racks and rack reservations
2. Assign permission set to new user (without any other rights)
3. As created user try to make new reservation to any rack

### Expected Behavior

User can create reservation to herself.
Null-valued field "user" acceptable and interpreted by the system as "reservation assigned to me" without knowing how many users in system.

### Observed Behavior

During reservation process field "user" is required and admin must add user access to (full?) list for any operations requiring this field.
![image](https://github.com/user-attachments/assets/0af65507-146f-4f3f-a0b3-12bec0392536)

Bug reproducible in 4.1.1 demo.

**Comment by jeremystretch** [comment]
This is not a bug. If you want to limit the set of users to which one user may assign a reservation, you can use [permission constraints](https://netboxlabs.com/docs/netbox/en/stable/administration/permissions/#constraints) to do so.

**Comment by stavr666** [comment]
> This is not a bug. If you want to limit the set of users to which one user may assign a reservation, you can use [permission constraints](https://netboxlabs.com/docs/netbox/en/stable/administration/permissions/#constraints) to do so.

I wish that every user could create reservation, as long as he have access to CREATE RESERVATION. As it was in 3.0.

Without giving access to full list of users. As it **required** now without any reason (when this is not required).
