### ISSUE TITLE
Link issue when viewing a Rack

### ISSUE THREAD

**Issue by Solarlight1** [netbox-community/netbox#17496]
### Deployment Type

NetBox Cloud

### NetBox Version

v4.1.0

### Python Version

3.10

### Steps to Reproduce

I have specific URL pointing to netbox - for example netbox,domain.com 

When navigating around netbox, this works perfect, except when viewing a rack, where if you hover over a device in the rack from the Rack Diagram, the URL is the IP Address:port of the hosting server.

So instead of pointing to: https://netbox.domain.com/dcim/device/2/
it is showing and linking to http://<SERVER_IP>:<PORT>/dcim/device/2/

### Expected Behavior

Link to https://netbox.domain.com/dcim/device/2/ and not the local IP of the server if called via Domain Name.

### Observed Behavior

System works if using internally (which we do) but we are planning allow external access via a Proxy Server with Authentication

**Comment by jeremystretch** [comment]
Your deployment is misconfigured. Please see [the wiki entry](https://github.com/netbox-community/netbox/wiki/Common-Issues#rack-elevation-links-use-wrong-domain) pertaining to this problem.
