### ISSUE TITLE
Event rule not creating jobs

### ISSUE THREAD

**Issue by neuro42** [netbox-community/netbox#17495]
### Deployment Type

Self-hosted

### NetBox Version

v4.0.9, v4.1.1

### Python Version

3.11

### Steps to Reproduce

1. Create an Event Rule to e.g. trigger a script when an IP Address is created/modified/deleted on 3.7.4
2. Upgrade to 4.0.9 or 4.1.1
3. Modify an IP Address

### Expected Behavior

Job should be created to run the script

### Observed Behavior

No job is created, with this error logged:
Cannot import events pipeline extras.events.process_event_queue error: 'ScriptModule' object has no attribute 'python_class'
Manually running the job works, but the name field in the job list is blank; runs on 3.7.x had this populated

**Comment by neuro42** [comment]
I've seen the same problem on 4.0.9 and 4.1.1, upgrading directly from the same 3.7.4 instance.  This leads me to believe it's something in the 3.7 -> 4.0 upgrade migrations that is being missed, as it's not just 4.1.1 where the problem is seen.

**Comment by neuro42** [comment]
Additional information was provided.  This has been reproduced with a 3.7.4 added script in upgrades to both 4.0.9 and 4.1.1, as described above.

**Comment by jeremystretch** [comment]
I was able to reproduce this by upgrading from v3.7.4 to v4.0.9. Looks like there's a bug in the 4.0 migration causing the event rule to lose it association with the specific script.

Unfortunately there's nothing we can do to address it at this point, as the 3.7 release is no longer maintained. However, it's very easy to recreate the event rule to restore the original functionality after upgrading.

**Comment by neuro42** [comment]
It also appeared in a direct migration to 4.1.1.  The only difference with readding the job again, is all of the past history of the job running gets lost/split between the old one and the new one.
