### ISSUE TITLE
The default font "Plus Jakarta Sans" supports only Latin writing system.

### ISSUE THREAD

**Issue by welqd** [netbox-community/netbox#17511]
### Deployment Type

Self-hosted

### NetBox Version

v4.1.0

### Python Version

3.11

### Steps to Reproduce

Hello.
Firstly, thank you for all your work.

The problem is that the default font "Plus Jakarta Sans" is not very versatile, I believe it only supports the Latin writing system. 
This results in an inconsistent look as shown below on the screen (Russian interface language).

![image](https://github.com/user-attachments/assets/f832438d-1fe8-4d63-9eff-f2093fb10c6a)

Screen from Google fonts.
![image](https://github.com/user-attachments/assets/96f6cb9b-0d20-4873-87f7-86941e334e8c)

I believe it was introduced in the pull request https://github.com/netbox-community/netbox/pull/16848 through variable
```css
 --tblr-font-sans-serif: "Plus Jakarta Sans Variable", system-ui, sans-serif;
```

### Expected Behavior

Since the project aims to support multiple languages, choose a more universal font, if possible.

### Observed Behavior

---

**Comment by jeremystretch** [comment]
> I believe it only supports the Latin writing system.

Per [Google Fonts](https://fonts.google.com/specimen/Plus+Jakarta+Sans) this appears to be accurate. I think what you're seeing in the screenshots is one of the fallback system fonts.

**Comment by goteamkor** [comment]
> IMO we should move back to the original [Inter](https://fonts.google.com/specimen/Inter) font.

agree.
