### ISSUE TITLE
Add a function "reset to device type / template"

### ISSUE THREAD

**Issue by tpx-mk** [netbox-community/netbox#17528]
### NetBox version

v4.1

### Feature type

New functionality

### Proposed functionality

Add a button in the device overview or the device edit form to reset the device properties including interfaces, components, etc. to the default of the device type / template.

### Use case

I'm creating devices via API called by another (basically a ticket) system which is generating the asset tag and links its device entry to the netbox one. As the other system doesn't know about device types it always creates a dummy device.
Afterwards I change the device type to the real one - but then the device type configured properties, interfaces, etc are not created.
Having a button to reset a object to a state like it was just created with its current device type would be very helpful. 

### Database changes

Don't think so.

### External dependencies

Don't think so.

**Comment by jeremystretch** [comment]
This functionality has been suggested many times in the past and rejected because it would be dangerous to implement. Please remember to search closed issues before submitting new ones.
