### ISSUE TITLE
Misaligned "Add" button on Device Type sub-tab list pages

### ISSUE THREAD

**Issue by bctiemann** [netbox-community/netbox#17536]
### Deployment Type

NetBox Cloud

### NetBox Version

v4.1.0

### Python Version

3.10

### Steps to Reproduce

1. Navigate to Device Types and select an item
2. Click the "Power Ports" or "Power Outlets" tab

### Expected Behavior

"+Add" button at bottom of table should be in line with the other action buttons.

### Observed Behavior

<img width="703" alt="Screenshot 2024-09-18 at 9 59 07 PM" src="https://github.com/user-attachments/assets/36a78f27-5ecc-424d-9553-b8d7301fefb5">

**Comment by goteamkor** [comment]
Duplicate: https://github.com/netbox-community/netbox/issues/17460
