### ISSUE TITLE
ASN Ranges are not searchable by name

### ISSUE THREAD

**Issue by dmulyalin** [netbox-community/netbox#17537]
### Deployment Type

Self-hosted

### NetBox Version

v4.1.1

### Python Version

3.10

### Steps to Reproduce

1. Go to IPAM -> ASN Ranges
2. Add new range, give it a name
3. Try to search range by name either using global search or by using quick search or by using search

### Expected Behavior

Searching ranges by name works

### Observed Behavior

Ranges are not searchable by name, I remember that was working in 3.7.8 version

**Comment by jeremystretch** [comment]
Thank you for opening a bug report. Unfortunately, the information you have provided is not sufficient for someone else to attempt to reproduce the reported behavior. Remember, each bug report must include detailed steps that someone else can follow on a clean, empty NetBox installation to reproduce the exact problem you're experiencing. These instructions should include the creation of any involved objects, any configuration changes, and complete accounting of the actions being taken. Also be sure that your report does not reference data on the public NetBox demo, as that is subject to change at any time by an outside party and cannot be relied upon for bug reports.

**Comment by dmulyalin** [comment]
Updated steps to reproduce @jeremystretch

**Comment by dmulyalin** [comment]
Tests it on Netbox 3.7.8, 4.0.10 and 4.1.1 - all having same behavior, ASN Ranges are not searchable by their name, should this search index have added name field to get it working - https://github.com/netbox-community/netbox/blob/2dd5c82845a1eab2a746cbeec33a350ac4e4a1dc/netbox/ipam/search.py#L29 

The way how I came across the issue was running custom script to pull ASN ranges using this query for dropdown menu form, but it is not returning all ASN ranges, only some of them, it was working fine on version 3.7.8 but not on 4.x - all existing asn ranges were available in drop down on 3.7.8 while only some on 4.0.11.:

```
from ipam.models import ASNRange, ASN, RIR
from extras.scripts import *

class test_asn_ranges(Script):
   
    asn_range = ObjectVar(
        label="ASN Range",
        description="Name of the ASN Range to allocate next available ASN from",
        model=ASNRange,
    ) 

    def run(self, data, commit):
        pass
```

**Comment by dmulyalin** [comment]
Oh, actually I know why it was working for some asn ranges and for some not, cause ASNRangeIndex uses description to search for asn range:
https://github.com/netbox-community/netbox/blob/2dd5c82845a1eab2a746cbeec33a350ac4e4a1dc/netbox/ipam/search.py#L25

and I did populate description field with value equal to range name for some of them but not for all.

**Comment by dmulyalin** [comment]
If possible, could ASN range search index be updated to include ASN Range's name field please.
