### ISSUE TITLE
Device list filtered by rack should include child devices

### ISSUE THREAD

**Issue by dpotter-intoto** [netbox-community/netbox#17546]
### Deployment Type

Self-hosted

### NetBox Version

v3.7.1

### Python Version

3.10

### Steps to Reproduce

1. Create a child device
2. Install it in a parent device's device-bay
3. Navigate to devices
4. Filter by the rack that the parent device is in
5. Observe that the parent device is present in the list, but not the child device

### Expected Behavior

I expected the child device to appear in the device list when the filter included the rack of the parent device.

### Observed Behavior

The child device did not appear in the device list when the filter included the rack of the parent device.

**Comment by arthanson** [comment]
@dpotter-intoto can you please re-check the reproduction steps as I'm not seeing this.  You actually have to assign the child device to the site and rack of the parent device for it to show up in the assignment interface.  When I go to the filter of the rack.  In the screenshot below I have Device1 with a device bay and children device installed to it and when I filter I see both.

Also see the second screen-cap of the populate device bay where it shows the child device must be already assigned.
![Devices | NetBox 2024-09-26 09-05-03](https://github.com/user-attachments/assets/e21f9610-3fb6-465b-84e5-2c3cbfcf373c)
![Populate tdevbay | NetBox 2024-09-26 09-06-15](https://github.com/user-attachments/assets/016bd939-41e2-405a-9e69-ab76bed20461)
