### ISSUE TITLE
Add 802.15.4 Wireless Interface

### ISSUE THREAD

**Issue by iamk3** [netbox-community/netbox#17550]
### NetBox version

v4.1.1

### Feature type

Change to existing functionality

### Proposed functionality

Netbox currently doesn't have an option for [Zigbee](https://en.wikipedia.org/wiki/Zigbee) other [IEEE 802.15.4](https://en.wikipedia.org/wiki/IEEE_802.15.4) based RF interfaces. 

I would like to try my hand at adding this functionality.

### Use case

Outside of Wi-Fi versions, only Bluetooth and "Other" exist. The 802.15.4 stack is becoming more and more relevant and I would like to see it as an option for my Enterprise Access Points. It is already a feature that is built in to current generation Enterprise Access Points.

### Database changes

I don't believe that this will require any database changes, just an extension of the existing standards already in place.

### External dependencies

none

**Comment by iamk3** [comment]
As mentioned in the "Proposed functionality", I would love to try contributing to this.

**Comment by DanSheps** [comment]
@iamk3 Assigned to you

**Comment by iamk3** [comment]
I have submitted a pull request to add the interface type.
