### ISSUE TITLE
Unable to assign VLAN group to Device Interface

### ISSUE THREAD

**Issue by c-po** [netbox-community/netbox#17569]
### Deployment Type

NetBox Cloud

### NetBox Version

v4.1.1

### Python Version

3.10

### Steps to Reproduce

1. Create a new device e.g. Cisco ISR1111-8P in `JBB Branch 109` site
2. Create new Interface configuration on said new device
3. Add VLAN Group to tagged port
 ![image](https://github.com/user-attachments/assets/0fc0294a-7d26-4da1-ac3a-add577b393dd)

4. Save confiruration change -> You will see a green modified banner on the bottom right
![image](https://github.com/user-attachments/assets/0aed4189-b9db-4257-b474-37ba86d8278a)

Nothing has been changed on that interface.

### Expected Behavior

The newly assigned VLAN group should be displayed as part of the interface configuration

### Observed Behavior

Requested change in Port configuration is not applied.

The changelog just states that tagging was activated for the port in question

![image](https://github.com/user-attachments/assets/2dc016e6-57b0-416f-81e4-9c259668f391)

**Comment by arthanson** [comment]
The vlan_group is actually just for filtering the tagged and untagged vlans, it isn't stored.  Probably should have a help-text to clarify that.

**Comment by c-po** [comment]
I guess it would be a super cool feature to do so, too - if it's not yet supported.

Imagine I have a bunch of Hypervisor nodes all consume the same set of VLANs. It would be easier to simply select the VLAN group. And if I need an additional VLAN, I just add it to the VLAN group.

That simplifies the single source of truth.
