### ISSUE TITLE
Cannot connect to redis over IPv6

### ISSUE THREAD

**Issue by skwerlman** [netbox-community/netbox#17567]
### Deployment Type

Self-hosted

### NetBox Version

v4.1.1

### Python Version

3.12

### Steps to Reproduce

1. Install redis with on a server with an IPv6 address
2. Install netbox on another server
3. configure netbox to connect to redis by ip address
4. start netbox

### Expected Behavior

netbox should connect to redis without issue

### Observed Behavior

netbox returns an http 400 error with this message
```
<class 'ValueError'>

Port could not be cast to integer value as '0:0:1:0:0:1:2121:6379'

Python version: 3.12.6
NetBox version: 4.1.1
Plugins: 
  netbox_dns: 1.1.1
  netbox_topology_views: 4.1.0
```

The REDIS section of my configuration.py looks like this:
```
REDIS = {
    'tasks': {
        'HOST': 'fc00:0:0:1:0:0:1:2121',
        'PORT': 6379,
        'USERNAME': '',
        'PASSWORD': '<redacted>',
        'DATABASE': 5,
        'SSL': False,
    },
        'caching': {
        'HOST': 'fc00:0:0:1:0:0:1:2121',
        'PORT': 6379,
        'USERNAME': '',
        'PASSWORD': '<redacted>',
        'DATABASE': 6,
        'SSL': False,
    }
}
```

**Comment by marsteel** [comment]
@skwerlman, can you try to add brackets?
`        'HOST': '[fc00:0:0:1:0:0:1]:2121',`

**Comment by jeremystretch** [comment]
As @marsteel points out above, IPv6 addresses must be enclosed by brackets when appending a port number. This is a convention of IPv6 addressing and not specific to NetBox.

**Comment by skwerlman** [comment]
that is not a port number at the end; the port number is the default for redis (6379)

**Comment by marsteel** [comment]
@skwerlman  what is the output if you use native redis cli to connect to redis server over IPv6 on the host where Netbox runs? https://redis.io/docs/latest/develop/connect/cli/ Just to make sure IPv6 can work on Netbox host.

Or try create DNS name with AAAA record for redis server IPv6 address.

**Comment by skwerlman** [comment]
i am able to connect successfully to the redis server using `redis-cli -h fc00:0:0:1:0:0:1:2121`

**Comment by marsteel** [comment]
@skwerlman   please try create DNS name with AAAA record for redis server IPv6 address. 
see https://stackoverflow.com/questions/77739970/cant-connect-on-remote-redis-with-hostname-when-bind-on-ipv6

**Comment by marsteel** [comment]
@skwerlman DNS AAAA record can work.     v6.magang.name is a DNS name with only AAAA record
`
        'HOST': 'v6.magang.name',

ping v6.magang.name
PING v6.magang.name(ip6-localhost (::1)) 56 data bytes
64 bytes from ip6-localhost (::1): icmp_seq=1 ttl=64 time=0.033 ms

        'HOST': 'v6.magang.name',

â— netbox-rq.service - NetBox Request Queue Worker
     Loaded: loaded (/etc/systemd/system/netbox-rq.service; enabled; vendor preset: enabled)
     Active: active (running) since Wed 2024-09-25 10:53:56 UTC; 58s ago
       Docs: https://docs.netbox.dev/
   Main PID: 1484788 (python3)
      Tasks: 3 (limit: 28681)
     Memory: 144.6M
        CPU: 6.438s
     CGroup: /system.slice/netbox-rq.service
             â”œâ”€1484788 /opt/netbox/venv/bin/python3 /opt/netbox/netbox/manage.py rqworker high default low
             â””â”€1484857 /opt/netbox/venv/bin/python3 /opt/netbox/netbox/manage.py rqworker high default low

Sep 25 10:53:56 linux-machine systemd[1]: Started NetBox Request Queue Worker.
Sep 25 10:53:57 linux-machine python3[1484788]: redis://v6.magang.name:6379/1
Sep 25 10:54:09 linux-machine python3[1484788]: 10:54:09 Worker rq:worker:730d22f93d20469db4ac758dea818614 started with PID 1484788, version 1.15.1
Sep 25 10:54:09 linux-machine python3[1484788]: 10:54:09 Subscribing to channel rq:pubsub:730d22f93d20469db4ac758dea818614
Sep 25 10:54:09 linux-machine python3[1484788]: 10:54:09 *** Listening on high, default, low...
Sep 25 10:54:09 linux-machine python3[1484857]: 10:54:09 Scheduler for default, low, high started with PID 1484857
Sep 25 10:54:09 linux-machine python3[1484788]: 10:54:09 Cleaning registries for queue: high
Sep 25 10:54:09 linux-machine python3[1484788]: 10:54:09 Cleaning registries for queue: default
Sep 25 10:54:09 linux-machine python3[1484788]: 10:54:09 Cleaning registries for queue: low
`

You can try skwerlman.magang.name 

        'HOST': skwerlman.magang.name ',
Non-authoritative answer:
Name:   skwerlman.magang.name
Address: fc00::1:0:0:1:2121

**Comment by skwerlman** [comment]
yes, AAAA does work. in my case i have worked around this by setting an entry in /etc/hosts:

```
fc00:0:0:1:0:0:1:2121 redis.pve.lan
```

however, i believe using ipv6 addresses directly should still be supported, or be documented to not work as expected

**Comment by skwerlman** [comment]
@jeremystretch can this issue be reopened? it still exists for me, and i would like to see it get fixed, even though there is a workaround

**Comment by marsteel** [comment]
@skwerlman  @jeremystretch It could be a bug in django-redis or redis-py. But it can be documented in Netbox docs.
