### ISSUE TITLE
Missing default value in Object module custom fields 

### ISSUE THREAD

**Issue by Etibru** [netbox-community/netbox#17565]
### Deployment Type

Self-hosted 

### NetBox Version

v4.1.1

### Python Version

3.12

### Steps to Reproduce

1. Create a required custom field and set a default value. Choose an object like DCIM > Interface.
2. Create a module type with a few interfaces.
3. Create a device, create a module bay on this device.
4. Connect a module with the module type 

### Expected Behavior

We should have the default value and not null. on the same way as on a device type with interfaces, when the device is created, there will be the default value on the interfaces custom field.

### Observed Behavior

Interfaces added to the device have no default value in the cusom field.

**Comment by jeremystretch** [comment]
Thank you for opening a bug report. Unfortunately, the information you have provided is not sufficient for someone else to attempt to reproduce the reported behavior. Remember, each bug report must include detailed steps that someone else can follow on a clean, empty NetBox installation to reproduce the exact problem you're experiencing. These instructions should include the creation of any involved objects, any configuration changes, and complete accounting of the actions being taken. Also be sure that your report does not reference data on the public NetBox demo, as that is subject to change at any time by an outside party and cannot be relied upon for bug reports.

**Comment by Etibru** [comment]
1. Create a required custom field and set a default value. Choose an object like DCIM > Interface.
```json
{
    "id": 8,
    "display": "My cf",
    "object_types": [
        "dcim.interface"
    ],
    "type": {
        "value": "text",
        "label": "Text"
    },
    "related_object_type": null,
    "data_type": "string",
    "name": "My_CF",
    "label": "",
    "group_name": "",
    "description": "",
    "required": true,
    "unique": false,
    "search_weight": 1000,
    "filter_logic": {
        "value": "loose",
        "label": "Loose"
    },
    "ui_visible": {
        "value": "always",
        "label": "Always"
    },
    "ui_editable": {
        "value": "yes",
        "label": "Yes"
    },
    "is_cloneable": false,
    "default": "default_value",
    "related_object_filter": null,
    "weight": 100,
    "validation_minimum": null,
    "validation_maximum": null,
    "validation_regex": "",
    "choice_set": null,
    "comments": "",
}
```

2. Create a module type with a few interfaces.

![image](https://github.com/user-attachments/assets/1ff2a903-2f2e-474f-ad09-ae73b9c87d22)

3. Create a device, create a module bay on this device.
![image](https://github.com/user-attachments/assets/05af9f42-b721-4625-9d09-5ace45f84c0a)


4. Connect a module with the module type
![image](https://github.com/user-attachments/assets/c0728c88-d2d4-4378-babd-5a45a59dec4f)


Now, we have the interfaces from the type module that have been added to the device.
![image](https://github.com/user-attachments/assets/ea937f6a-f1d3-44cc-ba76-133634ff0a27)

And if we see an Interface: 
![image](https://github.com/user-attachments/assets/bf977eb2-e8e1-4fb2-bbdb-a1c917ef3fdf)

We can see that the default value has not been set.
```json
"custom_fields": {
        "My_CF": null
    },
```

**Comment by Etibru** [comment]
Is any information still missing?
The bug is rather annoying, we have to run a script to correct custom fields that are set to null when they shouldn't be (must have a default value).

**Comment by Etibru** [comment]
I've had a quick look at where the SET default value is missing.


[HERE](https://github.com/netbox-community/netbox/blob/ead6e637f4aecc4717b10c71f9140c94040da264/netbox/dcim/models/devices.py#L1018C17-L1021C33), when a device is created and components added, the custom field value is set to default.
```py
               # Set default values for any applicable custom fields
                if cf_defaults := CustomField.objects.get_defaults_for_model(model):
                    component.custom_field_data = cf_defaults
                component.save()
```

For module bay components, you'll need to add more or less the same resonance [HERE](https://github.com/netbox-community/netbox/blob/ead6e637f4aecc4717b10c71f9140c94040da264/netbox/dcim/models/devices.py#L1276).

Something like this :
```py
                for component in create_instances:
                    if cf_defaults := CustomField.objects.get_defaults_for_model(component_model):
                        component.custom_field_data = cf_defaults
                    post_save.send(
                        sender=component_model,
                        instance=component,
                        created=True,
                        raw=False,
                        using='default',
                        update_fields=None
                    )
```

**Comment by Etibru** [comment]
@jeremystretch do you have enough information? do I need to go into more detail? :)
