### ISSUE TITLE
Device type power outlet component power port dropdown

### ISSUE THREAD

**Issue by ChrisRecioHive** [netbox-community/netbox#17636]
### Deployment Type

Self-hosted

### NetBox Version

v4.1.1

### Python Version

3.11

### Steps to Reproduce

1. Open a device type
2. Add a power outlet component
3. Open the "Power port" dropdown menu

### Expected Behavior

The power port dropdown menu would display only the power ports associated with that device type.
Ex: Creating a PDU device type. Associate power outlets with the power port on the PDU

### Observed Behavior

The power port dropdown menu displays every device types power ports. 
![image](https://github.com/user-attachments/assets/c978f264-8762-4dae-b4ce-abe57f307ff2)

**Comment by wksaminieminen** [comment]
More details:
After creating a device from a template which has no power port connected, the filtering works.
But filtering does not work on Device Types.

This works in 4.0.8, but does not work on 4.2.x or later.

Screenshot from 4.0.8 self hosted device template:
![No issue on 4.0.8](https://github.com/user-attachments/assets/9591f02e-92b8-4181-b4ce-8ed3849dd6cf)

Snapshot from 4.1.1 self hosted device template:
![Issue on 4.1.1](https://github.com/user-attachments/assets/ce2a0632-a572-42bc-8cc1-df4a37992636)

Screenshot from 4.1.1 self hosted device view:
![No issue on 4.1.1 device view:](https://github.com/user-attachments/assets/1d7570f9-737a-48b4-9127-f5881cb32448)
