### ISSUE TITLE
Device Interface "VLAN group" Filter deletes “Untagged VLAN” and “Tagged VLANs” entry. "Netbox Version V4"

### ISSUE THREAD

**Issue by LHBL2003** [netbox-community/netbox#17643]
### Deployment Type

Self-hosted

### NetBox Version

v4.1.2

### Python Version

3.10

### Steps to Reproduce

Since some sub-versions of version 4, the settings of “Untagged VLAN” and “Tagged VLANs” are deleted as soon as “VLAN group” is selected again for a device interface.

I thought I had already reported this, but unfortunately not.

1. create 2 VLAN groups (VLAN Group A, VLAN Group B) with 2 VLANs each (Test A.1, Test A.2, Test B.1, Test B.2).
2. open a device interface.
3. 802.1Q Switching:
    - 802.1Q Mode = Tagged
    - VLAN group = VLAN Group A
    - Untagged VLAN = Test A.1 (1234)
    - Tagged VLANs = Test A.1 (1234)
4. change “VLAN group” to “VLAN Group B”

Result, “Untagged VLAN” and “Tagged VLANs” are emptied.

![2024-09-30_09h13_50](https://github.com/user-attachments/assets/66cd05e4-8303-468d-aabc-48a299bb2529)

Jeremy's statement years ago was that “VLAN group” is only a filter to be able to search better in “Untagged VLAN” “Tagged VLANs”. This is also the reason why “VLAN group” is not saved.

The fact that “VLAN group” now empties the entries “Untagged VLAN” and “Tagged VLANs” is not good.

### Expected Behavior

“Untagged VLAN” and ‘Tagged VLANs’ remain unchanged when ‘VLAN group’ is changed.

### Observed Behavior

VLAN group” empties ‘Untagged VLAN’ and ‘Tagged VLANs’.

**Comment by jeremystretch** [comment]
This is working as intended. Selecting a new VLAN group obviously invalidates any selections made under a previous group.

**Comment by LHBL2003** [comment]
@jeremystretch: Sorry that was closed far too quickly for me.

But that was never the case in version 3.
What sense does that make?
Why is it being done differently now? Netbox V3 to V4?

Now it works worse than ever before. I understood that the group name is not saved. But someone must have decided that the other fields are suddenly cleared as soon as the group filter is used.

We know that many locations often have the same VLAN name. That's why we have given the VLAN groups a location abbreviation. But now we also have several topics at one location, and we may also need a VLAN from another group, which in turn has names that exist at other locations.
