### ISSUE TITLE
When a background job is scheduled without an instance, delete() on the job model will throw exceptions

### ISSUE THREAD

**Issue by DanSheps** [netbox-community/netbox#17648]
### Deployment Type

Self-hosted

### NetBox Version

v4.1.2

### Python Version

3.12

### Steps to Reproduce

1. Create a JobRunner class
2. Do not assign an object to the job instance
3. Add the JobRunner.enqueue_once to the ready() of a plugin

### Expected Behavior

NetBox will function normally

### Observed Behavior

AttributeError is raised in `Job.delete()`

**Comment by alehaa** [comment]
I believe this is because `delete()` doesn't check if `object_type` is `None`.

```Python
rq_queue_name = get_config().QUEUE_MAPPINGS.get(self.object_type.model, RQ_QUEUE_DEFAULT)
```

In `enqueue()` this is handled by:

```Python
rq_queue_name = get_queue_for_model(object_type.model if object_type else None)
```

I suggest using the same lookup in both instances and add to add a test checking jobs actually can be deleted. If this is accepted, I volunteer for a PR.

**Comment by DanSheps** [comment]
Yup, I knew the problem, but thanks for pointing out the `get_queue_for_model` method.

**Comment by alehaa** [comment]
It seems that deleting jobs is already covered by a test case (`test_enqueue_once_twice_different_schedule_at` internally triggers a `job.delete()`). However, this only applies to jobs with an `instance` set. I'll add tests for jobs without instances during implementation of #16971, so this will be covered as well.
