### ISSUE TITLE
Limit VLANs displayed on interface tables

### ISSUE THREAD

**Issue by thordreier** [netbox-community/netbox#17655]
### NetBox version

v4.1.2

### Feature type

Change to existing functionality

### Proposed functionality

Limit number of tagged VLANs shown on interface/vminterface table to 3 VLANs. If interface is connected to more than 3 VLANs, then show a link to full list. Just like with IP addresses, that was implemented in #14645

### Use case

Make overview of interfaces more readable, if a device has some interfaces that's connected to many VLANs.

**Comment by thordreier** [comment]
Suggested solution can be found in this commit: https://github.com/thordreier/netbox/commit/9495964987844374ca8557d343a230133e94ba3d

**Comment by DanSheps** [comment]
@thordreier Since you have a commit for this, I am just going to make the leap that you would like to submit a PR.

**Comment by salfers** [comment]
Will there be an option to change the display limit or disable it?
I understand the readability concern but rather prefer to have all information on the interfaces page so I can ctrl+f for VLANs.
