### ISSUE TITLE
Type interface filter not working since 4.1.2

### ISSUE THREAD

**Issue by ITJamie** [netbox-community/netbox#17663]
### Deployment Type

Self-hosted

### NetBox Version

V4.1.2

### Python Version

3.10

### Steps to Reproduce

Example urls which fail
- https://demo.netbox.dev/api/dcim/interfaces/?type__isw=bridge
- https://demo.netbox.dev/api/dcim/interfaces/?type__nic=bridge

### Expected Behavior

Api response to work (fails in swagger example too)

### Observed Behavior

```
HTTP 400 Bad Request
Allow: GET, POST, PUT, PATCH, DELETE, HEAD, OPTIONS, TRACE
Content-Type: application/json
Vary: Accept

{
    "type__nic": [
        "Select a valid choice. bridge is not one of the available choices."
    ]
}
```

Example response

**Comment by sleepinggenius2** [comment]
Can confirm that this is still present in 4.1.3 and seems to be a general issue with such filters on choice fields, as I just had it happen to me after upgrading from 4.1.1 with `type__n` on a model for a plugin I'm working on.

**Comment by ITJamie** [comment]
I expected that change too when i was looking over the commits. Cant confirm as I'm mobile only for the next week

**Comment by sleepinggenius2** [comment]
@bctiemann I know you are still working on the PR, but I just applied your changes locally and can confirm that they resolve the issue I was having.
