### ISSUE TITLE
Job.clean() not called

### ISSUE THREAD

**Issue by alehaa** [netbox-community/netbox#17685]
### Deployment Type

Self-hosted

### NetBox Version

v4.1.3

### Python Version

3.11

### Steps to Reproduce

1. Create a new `JobRunner`.
2. Schedule the job runner without with `enqueue(interval=0)`.

### Expected Behavior

Getting a `ValidationError`: 

```Python
django.core.exceptions.ValidationError: {
  '__all__': [
    'Jobs cannot be assigned to this object type (None).'
  ]
}
```

### Observed Behavior

Nothing happens, as neither `Job.enqueue()`, `Job.start()` nor `Job.terminate()` trigger `Job.clean()`.

**Comment by alehaa** [comment]
This error occured during testing of similar issues, as `Job.clean()` (like #17682, #17086 and #17648) assumes the `object_type` field is not `None`. If its decided `Job` should call `clean()`, this should be fixed as well (could happen in conjunction with #17682). Otherwise the method could be removed IMHO.

**Comment by jeremystretch** [comment]
@alehaa could you please elaborate on your steps to reproduce above? It is not clear exactly what you're doing. Example code would be helpful.

**Comment by alehaa** [comment]
During the implementation of #16971, I tested whether NetBox would raise exceptions on incorrectly configured jobs, and whether separate tests needed to be added to the system job registration. I added this (abbreviated) code to NetBox:

```Python
class SampleJob(JobRunner):
    def run(self, *args, **kwargs):
        pass

SampleJob.enqueue_once(interval=0)
```

The job can be scheduled without error. However, this should fail for two reasons:

1. `interval=0` violates the field's `MinValueValidator(1)`.
2. As no instance is set, `clean()` would raise an exception as it doesn't take into account `self.object_type` can be `None`. That's a bug related to #17682, #17086 and #17648, but didn't attract attention before, as `clean()` isn't called by any of the other methods in `Job`.

As this is not a cause of system jobs (#16971), but the `Job` model itself, I see this as a separate issue / bug.

**Comment by alehaa** [comment]
@jeremystretch Did you have a chance to review the additional information above?

**Comment by jeremystretch** [comment]
@alehaa pk, I'll flag this for an owner, unless you'd like to take it?

**Comment by alehaa** [comment]
I can provide a PR. As this is a fix for existing functionality I assume `develop` is the right branch?

**Comment by jeremystretch** [comment]
@alehaa great, thanks! And yeah, `develop` please.
