### ISSUE TITLE
Hide fields for specific user groups

### ISSUE THREAD

**Issue by powerscooter** [netbox-community/netbox#17715]
### NetBox version

v4.0.7

### Feature type

New functionality

### Triage priority

N/A

### Proposed functionality

This will probably be a big feature request now. We have been using Netbox for several years and it has become one of the most important tools for us. 
Netbox is getting more and more functions, which means more and more fields in all screens. For example, if we want to create a device, we only have to fill in 8 fields. All the others are not necessary in our case.
For even better user-friendliness, it would therefore be nice to be able to hide fields that are not required. 

### Use case

We often discover that some users are overwhelmed because they don't know whether a field has to be filled in or not. If you can set the fields that are displayed for users or perhaps based on user groups, the user-friendliness would be improved once again. The error rate when creating different data would also be minimized. As no unnecessary information would be entered.

**Comment by alehaa** [comment]
I fear this has been discussed before, at least in #16882 and #14481.

**Comment by jeremystretch** [comment]
Thank you for submitting this issue, however it appears that this topic has already been raised. Please see issue #14481 for further discussion.
