### ISSUE TITLE
The diagram in Power Tracking is not fully readable

### ISSUE THREAD

**Issue by markkuleinio** [netbox-community/netbox#17724]
### Change Type

Correction

### Area

Features

### Proposed Changes

https://netboxlabs.com/docs/netbox/en/stable/features/power-tracking/:

![image](https://github.com/user-attachments/assets/ef6070f1-cc7c-4c90-9ac3-e97ae69663db)
(= missing texts and groupings)

https://netboxlabs.com/docs/netbox/en/stable/media/power_distribution.png:

![image](https://github.com/user-attachments/assets/8fa10403-4bf3-4791-bae7-8b7bdc027853)

--> Some adjustment is needed for the image to show correctly.

**Comment by bctiemann** [comment]
Same issue as https://github.com/netbox-community/netbox/issues/17732, with same solution; closing this as duplicate.
