### ISSUE TITLE
API filtering with 'status__n' on Object (prefix, device, ..) NOT Working 

### ISSUE THREAD

**Issue by Etibru** [netbox-community/netbox#17721]
### Deployment Type

Self-hosted

### Triage priority

**It's an important regretion**

### NetBox Version

v4.1.2

### Python Version

3.12

### Steps to Reproduce

1. Call the API on : 
- http://X.X.X.X/api/ipam/prefixes/?status__n=container
- http://X.X.X.X/api/dcim/devices/?status__n=planned

The problem seems to be on all API `status__n` object filters, maybe even others. 

### Expected Behavior

This should return the list filtered by status

### Observed Behavior

```
{
    "status__n": [
        "Select a valid choice. container is not one of the available choices."
    ]
}
{
  "status__n": [
    "Select a valid choice. planned is not one of the available choices."
  ]
}

```

**Comment by sleepinggenius2** [comment]
This was already fixed in #17670, which should be included in the 4.1.4 release.
