### ISSUE TITLE
Server error at home page

### ISSUE THREAD

**Issue by llamafilm** [netbox-community/netbox#17756]
### Deployment Type

Self-hosted

### Triage priority

This is preventing me from using NetBox

### NetBox Version

v4.1.3

### Python Version

3.12

### Steps to Reproduce

1. Upgrade from 4.0.8 to 4.1.3 and install the netbox-branching plugin
2. Try to access the root URL at https://netbox.mydomain.net

### Expected Behavior

I should be redirected to the `/login/` page.

### Observed Behavior

Server error
![image](https://github.com/user-attachments/assets/4fc065dd-60ef-4dfa-a153-d9eab0b0e047)

**Comment by llamafilm** [comment]
This looks similar to #15815.  With debug enabled I see this:

![image](https://github.com/user-attachments/assets/4e0957dc-f8ed-4661-9f86-4526137ba4a5)

**Comment by jeremystretch** [comment]
@llamafilm I'm not able to reproduce this. After upgrading from v4.0.8 to v4.1.3 and installing and enabling the netbox-branching plugin, NetBox works as expected. This might be related to a specific dashboard configuration, or one of the other plugins you have installed. Please try resetting your default dashboard configuration and/or temporarily disabling your other plugins.

**Comment by llamafilm** [comment]
Thanks for pointing me in the right direction.  The issue was caused by this section in my default dashboard configuration:
```py
    {
        'widget': 'extras.ObjectListWidget',
        'width': 12,
        'height': 5,
        'title': 'Change Log',
        'color': 'blue',
        'config': {
            'model': 'extras.objectchange',
            'page_size': 25,
        }
    },
```

Changing that to `core.objectchange` fixes it.
