### ISSUE TITLE
Git-type data-source sync fails

### ISSUE THREAD

**Issue by Syl4r-v** [netbox-community/netbox#17758]
### Deployment Type

Self-hosted

### Triage priority

This is preventing me from using NetBox

### NetBox Version

v4.1.3

### Python Version

3.11

### Steps to Reproduce

1. adding new data source
2. set type to git
3. give all the details and create
4. try to sync but the job fails with error.

Doesn't matter if I use project token, personal token etc.

### Expected Behavior

Netbox to fetch data from the remote repo.

### Observed Behavior

sync job fails with: UnboundLocalError("cannot access local variable '_' where it is not associated with a value")

**Comment by Syl4r-v** [comment]
Okay, it was about issue #14371, problem is now solved. It  would be nice to mention somewhere in the docs that you need Dulwich installed because it's not in the requirements.

**Comment by jeremystretch** [comment]
> It would be nice to mention somewhere in the docs that you need Dulwich installed because it's not in the requirements.

It is noted in NetBox's [installation instructions](https://netboxlabs.com/docs/netbox/en/stable/installation/3-netbox/#remote-data-sources), as well as in the [synchronized data](https://netboxlabs.com/docs/netbox/en/stable/features/synchronized-data/) feature guide.
