### ISSUE TITLE
Group.objects.all() returns an empty QuerySet

### ISSUE THREAD

**Issue by jhofmueller** [netbox-community/netbox#17753]
### Deployment Type

Self-hosted

### Triage priority

This is preventing me from using NetBox

### NetBox Version

v4.1.3

### Python Version

3.12

### Steps to Reproduce

1. Have a netbox instance that has at least one group configured
2. Start 'nbshell'
3. Import Group from django.contrib.auth.models
4. Run `Group.objects.all()`

### Expected Behavior

A QuerySet with the groups configured in NetBox.

### Observed Behavior

An empty QuerySet is returned.

**Comment by Omripresent** [comment]
I believe as part of v4.0 the user group model was changed to https://github.com/netbox-community/netbox/blob/55fad2f533d9a0190ee9b5cf7c32bf173c982794/netbox/users/models/users.py#L26

Try using `from users.models import Group` and then `Group.objects.all()`

**Comment by jhofmueller** [comment]
Shame on me! I missed the "NetBox now uses custom User and Group models rather than the stock models provided by Django". Thanks for the hint!
