### ISSUE TITLE
Custom Objects or DNS Aliases

### ISSUE THREAD

**Issue by joshuahornig** [netbox-community/netbox#17799]
### NetBox version

v4.0.8

### Feature type

Data model extension

### Triage priority

N/A

### Proposed functionality

We Manage through Automation all of our Static DNS Entrys via Netbox and it would be great to have the option to Manage DNS Aliases also in Netbox, or maybe more Generell a option to create a custom Object would be very usefull.

### Use case

we are Using currently an Automation that sets the dns_name automatic in DNS Server when our Custom field with the name static DNS Entry is set to true
now an option to add multiple Aliases to a ip Address would be very great to map

**Comment by alehaa** [comment]
Maybe the [NetBox DNS Plugin](https://github.com/peteeckel/netbox-plugin-dns) is what you're searching for?

**Comment by joshuahornig** [comment]
yes that would also be an option and looks great for us Thank you
