### ISSUE TITLE
Add a new site map view to site section

### ISSUE THREAD

**Issue by ryanmerolle** [netbox-community/netbox#178]
Not really necessary, but a nice wow function for any DCIM tool that tracks sites.

You could pass an array of addresses to google maps which include an address and pin name to be mapped on a view of the globe.

Possible ways to implement:
- gmapi
- geodjango

**Comment by ryanmerolle** [comment]
adding some other implementation:
- https://github.com/bashu/django-easy-maps / https://pypi.python.org/pypi/django-easy-maps
- https://github.com/googlemaps/google-maps-services-python / https://pypi.python.org/pypi/googlemaps/

**Comment by thefreakquency** [comment]
+1 for this request :)

Maps could be represented at different levels:
* On the site page (/dcim/sites/Site_Slug/)
* On a Region page (/dcim/sites/?region=Region_Slug)
* On the main page (/)

Site placement could be done automagically either via the physical address field or a Lat/Long custom property of some sort.

Basing the placement of sites only on addresses could be problematic for some users, especially Telcos that have shelters/towers in the middle of nowhere or on mountain tops. 

In an ideal world, we should have the option to host internally the tile server as some users don't have internet access from their network, but I understand this would require a lot of work. As a starting point, showing a map from OpenStreetMap or similar provider should be a great start.

I understand that a possible workaround would be to use the graph feature, but it's not available first hand on the page, nor feasible on a bigger scale (multi site placement for regions or main page).

This feature would provide a great visual overview. Navigation could be enhanced if sites waypoints were clickable. This is something that gives my organization loves in some tools (Like SolarWinds NPM or internal apps).

**Comment by M4lik** [comment]
Hey there. Just wanted to ask quickly if this is already in development, because I think it's a really nice feature. :smile: I would do it myself, but neither have I currently the time, nor do I understand enough of netbox to make it happen.

**Comment by tb-killa** [comment]
I think lefleat could be also great because you could define own maps as base structure.

**Comment by ryanmerolle** [comment]
With the introduction of plugins, I feel like this could be a third party plugin instead of a core feature.

**Comment by jeremystretch** [comment]
@ryanmerolle agreed. Going to close this out.
