### ISSUE TITLE
Update the list view bulk Rename buttons to have an opaque background

### ISSUE THREAD

**Issue by atownson** [netbox-community/netbox#17802]
### Deployment Type

Self-hosted

### Triage priority

I volunteer to perform this work (if approved)

### NetBox Version

v4.1.4

### Python Version

3.10

### Steps to Reproduce

1. Create about 20 devices and navigate to the Device list view
2. Select/check one or more of the rows so the bulk operations buttons float

Templates affected:
1. templates/dcim/device_list.html
2. templates/dcim/component_list.html

These templates were overlooked in #17523. Adding the `btn-float` class to the Rename button fixes the issue.

### Expected Behavior

The Rename button should have an opaque background to avoid clashing with the form list items.

![image](https://github.com/user-attachments/assets/d9964924-4e20-47e7-957e-3951d707814f)

### Observed Behavior

The Rename button has a transparent background.

![image](https://github.com/user-attachments/assets/b3f3dbb7-cb72-40fa-b0e5-df455f238bee)

**Comment by arthanson** [comment]
@atownson I've assigned you the issue.
