### ISSUE TITLE
Manufacturer-based Config Context Assignment

### ISSUE THREAD

**Issue by paulcarre07** [netbox-community/netbox#17818]
### NetBox version

v4.1.4

### Feature type

Data model extension

### Triage priority

This is a very minor change

### Proposed functionality

I propose adding the ability to assign a config context directly to a manufacturer. Currently, it's not possible to apply a config context across all devices from a given manufacturer.
 
This enhancement could involve updates to the config context assignment workflows and may require adjustments to the data model to support manufacturer-level scoping in addition to device type and role scoping. Ideally, the user interface would provide a new option under config contexts where manufacturers could be selected alongside the existing device role and type options

### Use case

This feature would be particularly helpful for users who manage large-scale deployments where many devices from the same manufacturer share the same configuration. Instead of manually applying a config context to each device type or role, users could apply it once at the manufacturer level, ensuring consistency across all devices from that manufacturer. This would simplify the configuration process, reduce human error, and save time in maintaining and updating configurations, especially in environments with multiple devices from the same vendor

**Comment by chris240189** [comment]
I use the platform specific config context for that.
That is how all my arista EOS switches get some defaults.

**Comment by pl0xym0r** [comment]
Workaround is to use tags:
Create tag for manufacturer
Create cc and assign tag
Assign tag to your device

Device will inherit the cc

**Comment by paulcarre07** [comment]
> Workaround could be tags: Create tag for manufacturer Create cc and assign tag Assign tag to your device
> 
> Device will inherit the cc

Thank you for the suggestion! I'll go ahead and implement the workaround with tags for now.

**Comment by jeremystretch** [comment]
Thank you for submitting this issue, however it appears that this topic has already been raised. Please see issue #14508 for further discussion.
