### ISSUE TITLE
GUI is broken for limited users

### ISSUE THREAD

**Issue by barmalej1** [netbox-community/netbox#17823]
### Deployment Type

Self-hosted

### Triage priority

N/A

### NetBox Version

v4.1.3

### Python Version

3.12

### Steps to Reproduce

I have 3 user groups, Admins, Users and Viewers. Admins have access to everything, Users don't have access to the following permissions:

- admin.*, auth.*, secrets.*, sessions.*, users.*

only read-only access is allowed for Viewers. 

Steps to recreate:

I am running the latest NetBox docker version. I was able to recreate the issue by doing a fresh install and moving the database to the new installation

1. Login to NetBox as User

### Expected Behavior

All user groups should have access to the search functionality

### Observed Behavior

When I login as user, since upgrading to 4.1 from 4.0, I cannot see the search box at the top. When I select any item on the left, the display is missing the quick search box (only filters box is displayed), the tabs are missing. and checkboxes next to each listed item. If I login as Viewer everything is displayed correctly. Upon closer inspection, everything on the left is cut off and most of the font is displayed in Italics

![2024-10-23_15-34-06](https://github.com/user-attachments/assets/fb7eb7f6-c89a-469a-8da4-fda363da4ced)

This doesn't happen if I login as admin or read-only user

**Comment by jeremystretch** [comment]
Thank you for opening a bug report. Unfortunately, the information you have provided is not sufficient for someone else to attempt to reproduce the reported behavior. Remember, each bug report must include detailed steps that someone else can follow on a clean, empty NetBox installation to reproduce the exact problem you're experiencing. These instructions should include the creation of any involved objects, any configuration changes, and complete accounting of the actions being taken. Also be sure that your report does not reference data on the public NetBox demo, as that is subject to change at any time by an outside party and cannot be relied upon for bug reports.

**Comment by barmalej1** [comment]
Very strange issue. I cannot even recreate it in my stage environment.
