### ISSUE TITLE
Make it possible to add relations to plugin models to GraphQL types

### ISSUE THREAD

**Issue by peteeckel** [netbox-community/netbox#17826]
### NetBox version

v4.1.4

### Feature type

New functionality

### Triage priority

N/A

### Proposed functionality

Currently the relations that can be retrieved with the GraphQL `TenantType` object type are hard-coded in `tenancy/graphql/types.py`.

I suggest adding a way to register plugin models with GraphQL so that it's possible to retrieve plugin objects together with tenanty, like this:
```
query { tenant_list { plugin_object { id } } }
```

Currently only the opposite direction works:
```
query { plugin_object_list { tenant { name } } }
```

### Use case

I am maintaining a plugin that supports tenancy for some of its models. It would be useful be able to get a list of plugin objects when querying a tenant.

### Database changes

None

**Comment by TribuneX** [comment]
[This request](https://github.com/129828) seems to ask for a similar feature.

**Comment by peteeckel** [comment]
Um ... which request? The link is to a user.
