### ISSUE TITLE
In DCIM Device page, saving device information not working

### ISSUE THREAD

**Issue by Xemanth** [netbox-community/netbox#17837]
### Deployment Type

Self-hosted

### Triage priority

This is preventing me from using NetBox

### NetBox Version

v4.1.4

### Python Version

3.12

### Steps to Reproduce

1. Open some DCIM device
2. Click in the bottom "save"

### Expected Behavior

Save button saves the page data

### Observed Behavior

Save button doesn't react.

Tested with Firefox and Chrome.
In the organization, site pages saving works, so it's clearly focuses to devices.

**Comment by jeremystretch** [comment]
Please include more detail about what specifically you're doing, and how someone else can reproduce the problem. Just saving a device work. It's likely you're running into some frontend validation failure.

**Comment by Xemanth** [comment]
> Please include more detail about what specifically you're doing, and how someone else can reproduce the problem. Just saving a device work. It's likely you're running into some frontend validation failure.

When I try to edit any field on a device and click save, nothing happens. The service does not save the changes, nor does it show any error message explaining why. The same issue occurs when I try to clone an existing device and save it as a new one. I have filled in all the required fields, but the service still doesn't save the data or provide any feedback.

**Comment by Xemanth** [comment]
I cleared my Firefox cache and cookies. Now when I try to save device data I get this kind of server error:
![image](https://github.com/user-attachments/assets/339406a9-c6ca-4f2b-b361-c3e527279122)

Does this help understanding the issue?

**Comment by Xemanth** [comment]
> The `validate()` method of your custom validator must accept both the `instance` and `request` arguments; see [the docs](https://netboxlabs.com/docs/netbox/en/stable/customization/custom-validation/#custom-validation-logic) for an example. (This was changed in NetBox v4.0 under FR #14279.)
Changing the customer validator fixed my issue!
Weird though that it didn't first give any error message until I made full cache wipe :(
