### ISSUE TITLE
Add reverse_sql in 0117_move_objectchange.py

### ISSUE THREAD

**Issue by mulmat** [netbox-community/netbox#17830]
### Proposed Changes

I was in need of downgrading and stumbled upon `extras/migrations/0117_move_objectchange.py` not allowing downgrade. I've modified `0117_move_objectchange.py` to allow for downgrade and can submit a PR for it.

### Justification

Always nice to be able to downgrade.

**Comment by jeremystretch** [comment]
NetBox does not support reverse migrations, as there are many scenarios where this is untenable. The recommended course of action is always to save a copy of your database prior to running any migrations.
