### ISSUE TITLE
Fix shebang in netbox/manage.py

### ISSUE THREAD

**Issue by xee8ai** [netbox-community/netbox#17838]
### Deployment Type

Self-hosted

### Triage priority

I volunteer to perform this work (if approved)

### NetBox Version

v.4.1.4

### Python Version

3.12

### Steps to Reproduce

The shebang on netbox/manage.py is ambiguous.

Not really a bug but e.g. causing rpmbuild to stop with an error.

### Expected Behavior

File netbox/manage.py starts with

`#!/usr/bin/env python3`

### Observed Behavior

File netbox/manage.py starts with

`#!/usr/bin/env python`

**Comment by candlerb** [comment]
> File netbox/manage.py starts with
> 
> `#!/usr/bin/env python`

If the virtualenv is active, that will work just fine (python and python3 both exist in the venv).

If the virtualenv is inactive, then `#!/usr/bin/env python3` will run the global python interpreter with the wrong libraries, and Bad Things™ will happen.

Personally, I'd suggest removing the shebang entirely, and well as the eXecute bit. Users can run it with:

```
/opt/netbox/venv/bin/python /opt/netbox/netbox/manage.py ...
```

and not worry about activating the virtualenv manually, or what directory they are in.

Alternatively, the shebang could be changed to `#!/opt/netbox/venv/bin/python[3]`
