### ISSUE TITLE
Power Utilization not fully calculated

### ISSUE THREAD

**Issue by craigmoscardini** [netbox-community/netbox#17843]
### Deployment Type

Self-hosted

### Triage priority

N/A

### NetBox Version

4.0.9

### Python Version

3.11

### Steps to Reproduce

1. Create power panel & power feed assigned to rack
2. Connect PDUs and devices and see power utilization on the rack does not work correctly

In my initial example I had

- Panel
  - Feed
    - PDU 1
      - PDU 2
        - Devices
      - UPS
        - Devices

In this example the UPS has a maximum and assigned draw and is included in the calculation.
PDUs do not have a power draw assigned
All devices do have a power draw assigned

Set up like this no devices connected to the PDUs are included in the calculation. By setting a draw on PDU2 it was included in the calculation but never including the connected devices downstream from it.

I can reproduce this same behaviour on the current demo v4.1.4

### Expected Behavior

Rack power utilization should be a sum of all correctly cabled devices that have maximum/allocated power draw on the device

### Observed Behavior

Power calculation is incomplete. It does not propagate through all downstream devices regardless of configuration

**Comment by sleepinggenius2** [comment]
This is a known issue and there was a lot of discussion on the topic back in #3377, but unfortunately it has never gotten to an acceptable implementation.

**Comment by arthanson** [comment]
@craigmoscardini can you please re-open this as a feature request and link it to #3377
