### ISSUE TITLE
Custom Link is not shown with example out of docs/customization/custom-links.md

### ISSUE THREAD

**Issue by h0-online** [netbox-community/netbox#17850]
### Deployment Type

Self-hosted

### Triage priority

N/A

### NetBox Version

v4.1.4

### Python Version

3.10

### Steps to Reproduce

1. Enter the following from custom-links.md
![image](https://github.com/user-attachments/assets/949e11e2-596d-47f0-99d7-7b9485b82b7e)
2. Take any active device (I took from your netbox.dev the 1st active device https://demo.netbox.dev/dcim/devices/88/ )
![image](https://github.com/user-attachments/assets/978e3988-a882-4d8c-89e9-7dfd1f3976d0)
3. unfortunately no link occurs, neither in Overview nor in Edit... Even when not using any Jinja2 content, everything in regards to custom links are empty

### Expected Behavior

expectation is that a link button for each active device will occur or in case of no Jinja2 content a simple static link will occur...

### Observed Behavior

Unfortunately no error is occuring the description of both JInja2 fields are showing that each empty link will not be shown so it seems to be that the content of Link Text and Link URL are always treated as empty content
due to the fact that we have upgraded yesterday to 4.1.4 and we introduced this feature today in our local installation I am not able to ask if this was coming with your GUI Updates since 4.1. 
This feature will be mandatory for us to get NetBox really as single source of truth in our production environment where the custom links bring us dynamically to our device correspondent systems..

**Comment by arthanson** [comment]
@h0-online Can you please re-check the reproduction steps and try in the latest NetBox, it seems to work fine for me.

![PP:B117 | NetBox 2024-10-25 07-52-34](https://github.com/user-attachments/assets/21c97ed4-35ba-4346-af96-75376c84cba9)

**Comment by h0-online** [comment]
Dear Arthur,

thx for your explanation, but to be honest, I was not looking for the link at this position AND it is more or less hidden for the first glance...
![image](https://github.com/user-attachments/assets/b399fa37-f74f-47ad-9aa0-869d95678fd3)
I was also searching for my link with CTRL-F where it was not found before clicking on "Links" and looking at the expected location in within the Custom Fields it wasn't found too.
Now you have to look at the top under the topic "Links", click on it and find it there
![image](https://github.com/user-attachments/assets/8d99ab98-1ee5-4575-b451-4360ae9e2a4e)
As it is nowhere mentioned, hard to find... I think there is a need now to explain it in our local User Manual...

By the way: is there a description of database fields which can be addressed by the Link Text and Link URL using Jinja2 for each table? Searching via PgAdmin in each table and hope that this is the expected table and attribute is like a detective game... Is there a abstract database model which shows the corresponding table and attribute to each menu item (where maybe the label differs from attribute name) without looking in the python source?

Thx for your support so far, ticket can be closed as the main issue (not shown) is non-existent but from my perspective documentation should be more clearer...

//Ulf
