### ISSUE TITLE
Power and console cables status isn't shown correctly

### ISSUE THREAD

**Issue by Pesk0v** [netbox-community/netbox#17851]
### Deployment Type

Self-hosted

### Triage priority

N/A

### NetBox Version

4.0.2

### Python Version

3.12

### Steps to Reproduce

The problem occurs only for console ports and power ports. Connected ports on the Power Ports, Power Outlets, Console Ports, Console Server Ports tabs are not highlighted in color, no matter what cable status set ('Installed' or 'Planned').

### Expected Behavior

Right after a cable is created to connect two ports, the rows corresponding to connected ports are expected to be highlighted in green by default.  The toggle should be orange and change cable status from 'Installed' to 'Planned'.

### Observed Behavior

Once a cable for connection two either console or power ports has been created, the port (in tabs Power Ports, Power Outlets, Console Ports, Console Server Ports) which the cable is connected to is shown like it wouldn't be connected though the connection is correctly indicated in row. At that there is the 'Mark Installed' blue button in the port row.
![image](https://github.com/user-attachments/assets/1ec3849b-2b7b-4ecc-a25d-58a7dcf1d73e)
When clicking on the button everything seems back to normality, i.e. the row is highlighted in green, and the blue toggle turns orange toggle switching port status into 'Mark Planned'. In other words the toggle gets working as expected, switching the cable status between 'Planned' and 'Installed' with the correct color highlighting of the port row.
But all rows corresponding to the connected ports are not highlighted again and **everything returns to the abnormal state** when pressing F5 (refresh screen) or reopening the tab. 
Worth noting that interface ports are not affected by this problem.

**Comment by arthanson** [comment]
@Pesk0v Thank you for the bug report, can you please add more reproduction steps to this.   It's not clear in the steps to reproduce exactly what you are doing to see the problem.

Unfortunately, the information you have provided is not sufficient for someone else to attempt to reproduce the reported behavior. Remember, each bug report must include detailed steps that someone else can follow on a clean, empty NetBox installation to reproduce the exact problem you're experiencing. These instructions should include the creation of any involved objects, any configuration changes, and complete accounting of the actions being taken. Also be sure that your report does not reference data on the public NetBox demo, as that is subject to change at any time by an outside party and cannot be relied upon for bug reports.

This is what I'm seeing:
![PP:B117 | NetBox 2024-10-25 07-46-42](https://github.com/user-attachments/assets/01f9c763-4166-426e-a2b9-78d41bcaff54)

**Comment by Pesk0v** [comment]
Hello Arthur,
Thank you for your attention to this problem.
As I reported the problem appears whenever I create a connection cable
between console/power ports.
The problem appeared some time ago after updating the netbox version from
3.6.6 to 4.0.2
To show how the problem shows itself, a screenshot of a newly created
server is here

[image: image.png]
No ports have been connected yet.
Now, I'm going to connect the PWR1 port to a power supply.
[image: image.png]
The port is connected to PDU1 and gets status 'Connected'
[image: image.png]
After I press the 'Create' button I see that the connection is in place (it
is correctly shown in the 'Connection' column).
The row should have been highlighted in green. However, in my case the line
is not highlighted in any way.
In addition the toggle button ('Mark Installed' / 'Mark Planned') is blue
and when I hover my mouse over this button, a tooltip 'Mark Installed' pops
up, i.e. like the just created connection is treated as a *planned *connection
but not *installed*.
[image: image.png]
When I press the toggle, everything falls into place. The row is
highlighted in green, the toggle turns orange and a tooltip 'Mark Planned'
appears when I hover my mouse over.
[image: image.png]
From this moment on, when you click on the toggle again and again,
everything is displayed correctly and every next click on the toggle
changes cable status so that 'planned' connection turns to 'installed' and
v.v., and the row is highlighted in a such manner that it turn green for
'installed' connections and blue for 'planned' connections. In other words
this really meets expectations on how the toggle color and assigned action
to the toggle, the port row color and the cable status depends on each
other.
Thus, next click on the toggle gives this -
[image: image.png]
...next click gives this -
[image: image.png]
..and so on.
Everything looks fine until the browser screen is refreshed or this page is
reopened. After that, the port is shown exactly as it did immediately after
creation, and the same problem appears again.
So, if you refresh the screen it will look like on the pic below

[image: image.png]


Kind regards,
Nikolai Peskov,
*TECHNO*
***@***.***
+7(903)212-7703
