### ISSUE TITLE
Feature Request: Adding Assignment to Custom Field

### ISSUE THREAD

**Issue by remchuk** [netbox-community/netbox#17856]
### Change Type

Addition

### Area

Features

### Proposed Changes

Adding assignment to custom field.
It doesn't have to be a required field but it could help a lot of people.

I want to have the option to link 2 custom field.
Meaning I would like to have 2 custom fields, which one is assigned to other,
it will act as "is_primary" in the IPAM --> IP Addresses. and "Primary IPv4"  in DCIM --> Devices.

Currently there is no real option to do this, and developing a plugin for this fills like a huge overkill.
Is there a reason for not having this?

**Comment by jeremystretch** [comment]
We've had a problem with our issue templates today, but it's been fixed. Please resubmit this as a [feature request](https://github.com/netbox-community/netbox/issues/new?assignees=&labels=type%3A+feature%2Cstatus%3A+needs+triage&projects=&template=01-feature_request.yaml). Apologies for the confusion.
