### ISSUE TITLE
SSO "Microsoft Azure AD" box changed to "azuread-tenant-oauth2" after updating from 4.1.3 to 4.1.4

### ISSUE THREAD

**Issue by monteroman** [netbox-community/netbox#17870]
### Deployment Type

Self-hosted

### Triage priority

N/A

### NetBox Version

v4.1.4

### Python Version

3.10

### Steps to Reproduce

1. Follow the Git instructions for upgrading Netbox.
2. Restart services after update from 4.1.3 to 4.1.4.
3. Login prompt now shows "azuread-tenant-oauth2" instead of "Microsoft Azure AD"
4. Flushed browser cache; tried another browser entirely; same issue.
5. Rolled back VM snapshot back to 4.1.3. The login prompt shows "Microsoft Azure AD" again.
6. Re-ran the process to upgrade to 4.1.4 and the same behavior appears.

### Expected Behavior

The login prompt should still show "Microsoft Azure AD" for SSO logins.

![image](https://github.com/user-attachments/assets/9a244efc-0f09-4876-a40a-f490c838a8eb)

### Observed Behavior

![image](https://github.com/user-attachments/assets/2d3cdfbe-dbf6-4544-bcb3-0550c560fb2b)

The login still works, but the visualization is broken for the login prompt.

**Comment by jeremystretch** [comment]
This was addressed in #17774 and will be fixed in NetBox v4.1.5.
