### ISSUE TITLE
Add Cluster to Bulk Edit Device

### ISSUE THREAD

**Issue by remchuk** [netbox-community/netbox#17871]
### NetBox version

v3.5.6

### Feature type

Data model extension

### Triage priority

N/A

### Proposed functionality

When editing a several Devices there is currently no option to change Cluster in bulk.
I think it is a simple addition that might benefit for who ever needs it. 

### Use case

My team and I have a webhook that when a device is changed it will run and trigger some automatons,
This include Vlan change and more, We do it by editing the Cluster, But there is no way to bulk edit the Cluster so we either have to do it one by one or going From the Cluster side.

**Comment by pl0xym0r** [comment]
can implement it if needed

**Comment by bctiemann** [comment]
Seems straightforward. @pl0xym0r please feel free to take this up.
