### ISSUE TITLE
[Blocks all PRs] Failing test_background_task_stop test

### ISSUE THREAD

**Issue by prryplatypus** [netbox-community/netbox#17879]
### Deployment Type

Self-hosted

### Triage priority

N/A

### NetBox Version

v4.1.5

### Python Version

3.10

### Steps to Reproduce

1. Run the tests

### Expected Behavior

Tests pass

### Observed Behavior

Tests fail

**Comment by jeremystretch** [comment]
This has already been addressed in NetBox v4.1.5.

**Comment by PieterL75** [comment]
Maybe interesting to mention this in the docs, for those who are running >4.1.5 ?
