### ISSUE TITLE
Checkbox to assign OOB on IP address creation

### ISSUE THREAD

**Issue by remchuk** [netbox-community/netbox#17889]
### NetBox version

v3.6.6

### Feature type

New functionality

### Triage priority

N/A

### Proposed functionality

This is a duplicate of [#14594](https://github.com/netbox-community/netbox/discussions/14594).

I propose adding a checkbox labeled "Make this the Out-of-band IP for a device, just as we have with "Make this the Primary IP"

### Use case

It a small change in favor of QoL.
This will save us a lot of time and double work.
I allows a much better work with bulk editing when it comes to a lot of IP Addresses.

**Comment by jeremystretch** [comment]
@pl0xym0r could you leave a comment here so I can assign this FR to you please?

**Comment by pl0xym0r** [comment]
fixed by #18057
