### ISSUE TITLE
Custom Script Scheduling Broken

### ISSUE THREAD

**Issue by wz4** [netbox-community/netbox#17921]
### Deployment Type

Self-hosted

### Triage priority

N/A

### NetBox Version

v4.1.6

### Python Version

3.10

### Steps to Reproduce

In Netbox v4.1.6 schedule a recurring custom script. The first job will get scheduled, but subsequent jobs are not.

Test Script

```
from extras.scripts import Script

class TestScript(Script):
    class Meta:
        name = "Test Script"
        description = "Hello"
        scheduling_enabled = True

    def run(self, data, commit):

        return "HELLO"
```

### Expected Behavior

After a scheduled job completes, the next scheduled job should appear with a status of 'Scheduled'.

### Observed Behavior

No observed error

**Comment by arthanson** [comment]
@alehaa can you comment on this and I can assign your.

**Comment by alehaa** [comment]
I can take a look into it.
