### ISSUE TITLE
Also changelog non-request-based changes

### ISSUE THREAD

**Issue by mulmat** [netbox-community/netbox#17941]
### NetBox version

v4.1.6

### Feature type

Change to existing functionality

### Triage priority

I volunteer to perform this work (if approved)

### Proposed functionality

Currently, the `handle_changed_object` function bails out if the change does not originate from a request.

It would be desirable to log these changes as well.

### Use case

We have added custom management commands that alter data, but the changes never appear in the change log.

**Comment by jeremystretch** [comment]
Change logging unfortunately is not something that can be implemented in a blanket fashion. You'll need to employ the change logging context manager explicitly within your custom logic if you rely on its functionality.
