### ISSUE TITLE
Module bays description not defines when creating new device

### ISSUE THREAD

**Issue by elixdreamer** [netbox-community/netbox#17948]
### Deployment Type

Self-hosted

### Triage priority

N/A

### NetBox Version

NetBox Community v4.1.6 (2024-10-31)

### Python Version

3.10

### Steps to Reproduce

1. Define a description on a module bay in a device type.
https://demo.netbox.dev/dcim/device-types/3/module-bays/
![image](https://github.com/user-attachments/assets/adb88abd-2ea1-478d-af13-5d28610e7b37)

2. Add a new device of this type
![image](https://github.com/user-attachments/assets/4c5b4d9f-da32-4098-80ad-ff8041d1d26f)

3. check module bays description
![image](https://github.com/user-attachments/assets/0cb36bcc-478d-43ee-9d0d-a55ddd108df6)

### Expected Behavior

That the description from the device type is being imported to the newly created device.

### Observed Behavior

description is missing

**Comment by jeremystretch** [comment]
This is intended behavior. As with other component template, the description is not meant to be replicated on individual modules/devices, as that would merely produce redundant data.

This has been raised in prior issues. Please remember to search existing issues before submitting a new one.
