### ISSUE TITLE
Netbox Documentation Markdown Not Working Correctly

### ISSUE THREAD

**Issue by JosephLive93** [netbox-community/netbox#17957]
### Deployment Type

Self-hosted

### Triage priority

I'm a NetBox Labs customer

### NetBox Version

v4.1.6

### Python Version

3.12

### Steps to Reproduce

1. In the documentation under 'Getting Started' -> 'Planning' 
2. The flow charts at the bottom do not display correctly

### Expected Behavior

![image](https://github.com/user-attachments/assets/3b5f9409-ac4b-4aaf-baef-19785dbc206f)

### Observed Behavior

![image](https://github.com/user-attachments/assets/7a60f4eb-8997-4780-95c0-fd1b9312375a)

**Comment by JosephLive93** [comment]
@jeremystretch Thanks for the response. I'm accessing the documentation from the web interface from the icons at the bottom of the page. See picture below for reference.

![image](https://github.com/user-attachments/assets/94e7ad8b-6747-444f-adf6-2c77a6627f5d)

**Comment by jsenecal** [comment]
I can't replicate this on my install. perhaps you are missing a specific library ?
