### ISSUE TITLE
Server Error on exporting netbox "System Info"

### ISSUE THREAD

**Issue by maxzapp** [netbox-community/netbox#17969]
### Deployment Type

Self-hosted

### Triage priority

N/A

### NetBox Version

V4.1.6

### Python Version

3.10

### Steps to Reproduce

1. Click on Admin
2. Click on System
3. Click on Export

### Expected Behavior

Export of shown Data eg in Text or CSV

### Observed Behavior

A Server Error raised:

<class 'AttributeError'>

'ConfigRevision' object has no attribute 'ALLOWED_URL_SCHEMES'

Python version: 3.10.12
NetBox version: 4.1.6
Plugins: None installed

**Comment by jeremystretch** [comment]
I'm able to replicate this only when at least one configuration revision has been created. However, the specific exception message I receive is

> 'ConfigRevision' object has no attribute 'BANNER_BOTTOM'
