### ISSUE TITLE
Select all with bulk edit only changes the currently visible objects

### ISSUE THREAD

**Issue by julianstolp** [netbox-community/netbox#17963]
### Deployment Type

Self-hosted

### Triage priority

N/A

### NetBox Version

v4.1.6

### Python Version

3.12

### Steps to Reproduce

1. select all objects using the `Toggle all` checkbox
2. tick the box `Select all xxx object matching query`
3. go to `Edit Selected`
4. change something and go to `Apply`

### Expected Behavior

All selected objects will be modified.

### Observed Behavior

Only the current visible objects get changed, if all objects are visible all get changed. The bulk delete is unaffected. 
![image](https://github.com/user-attachments/assets/7b1d54f6-ccf5-4564-8765-ec09fe05cb00)
![image](https://github.com/user-attachments/assets/934cd88a-4625-448f-832f-ebace4eddd0a)

**Comment by jeremystretch** [comment]
I've traced this to a regression in 6a316df787915141f8038507c531cdcfaffc2b39, where the bulk edit form is initialized using POST data. This specific change doesn't _appear_ to be needed for the functionality implemented under #17789, so I'm going to remove it.
