### ISSUE TITLE
Fibre Optic Cable with Tube modelling

### ISSUE THREAD

**Issue by Etibru** [netbox-community/netbox#18031]
### NetBox version

v4.1.6

### Feature type

Data model extension

### Triage priority

N/A

### Proposed functionality

In many cases, the modeling of fiber cables in Netbox is not precise enough. It would be very interesting to model a fiber cable that contains tubes, which themselves contain fibers.
For example, in the vast majority of cases, a 48-fiber cable is made up of several different-colored tubes, each containing different-colored fibers.
![image](https://github.com/user-attachments/assets/0776e81a-7bb2-4dad-9ea5-d46bd942fd35)

![image](https://github.com/user-attachments/assets/4304a956-f1bf-4bda-befa-e4dc17b29e36)

### Use case

In a datacenter, fiber rocades are positioned between the MMR (meet me room) and the IT rooms. Very often these are several cables with different optical fiber capacities (24, 48, 72, 128, ...) and at each end we have patch panels. 
To be able to identify a particular fiber in a cable, you'd need to know that its position on a patch panel refers to the purple fiber in the blue tube of cable XXX.

**Comment by jeremystretch** [comment]
Thank you for your interest in extending NetBox. Unfortunately, the information you have provided does not constitute an actionable feature request. Per our [contributing guide](https://github.com/netbox-community/netbox/blob/develop/CONTRIBUTING.md), a feature request must include a thorough description of the proposed functionality, including any database changes, new views or API endpoints, and so on. It must also include a detailed use case justifying its implementation. If you would like to elaborate on your proposal, please modify your post above. If sufficient detail is not added, this issue will be closed.
