### ISSUE TITLE
Connect wireless devices?

### ISSUE THREAD

**Issue by deanfourie1** [netbox-community/netbox#18034]
### Deployment Type

Self-hosted

### Triage priority

I'm a NetBox Labs customer

### NetBox Version

v4.1.6

### Python Version

3.12

### Steps to Reproduce

Attempt to connect devices to access points wifi interfaces (multiple)

### Expected Behavior

The ability to add multiple wireless links between client devices and access points.

### Observed Behavior

I can only connect 1 device to the wireless interface. Then the interface does not allow any more devices to be connected to it.

**Comment by jeremystretch** [comment]
Closing this as it's not a valid bug report. Maybe try a [discussion](https://github.com/netbox-community/netbox/discussions/new?category=help-wanted) if you're unsure of how to achieve what you want to accomplish.

**Comment by deanfourie1** [comment]
I disagree. It is a bug as there is no way to do it. I have seen multiple reports of the same issue.
