### ISSUE TITLE
Stored Cross Site Scripting Vulnerability in "Configuration History" function in Netbox 4.1.6

### ISSUE THREAD

**Issue by tu3n4nh** [netbox-community/netbox#18043]
### Deployment Type

Self-hosted

### Triage priority

I volunteer to perform this work (if approved)

### NetBox Version

v4.1.6

### Python Version

3.12

### Steps to Reproduce

# Version: 4.1.6
## Description:
An authenticated malicious user can take advantage of a Stored XSS vulnerability in "Configuration History" function in the "Admin" feature.
### Step 1: Go to `/core/config-revisions/`, click "Add" and insert payload "`<script>alert(document.domain)</script>`" in "Top banner" field.
![image](https://github.com/user-attachments/assets/74931794-0fb8-44c3-acc8-65a77e927972)
### Step 2: Click "Create".
![image](https://github.com/user-attachments/assets/71b399ce-c783-454c-93ea-db40fda46adc)
### Step 3: Script excuted.
![image](https://github.com/user-attachments/assets/d2b3ab95-8c27-41c4-89b4-280e781c64df)

### Expected Behavior

If an attacker can control a script that is executed in the victim's browser, then they can typically fully compromise that user.
![image](https://github.com/user-attachments/assets/d2b3ab95-8c27-41c4-89b4-280e781c64df)

### Observed Behavior

If an attacker can control a script that is executed in the victim's browser, then they can typically fully compromise that user.
![image](https://github.com/user-attachments/assets/d2b3ab95-8c27-41c4-89b4-280e781c64df)

**Comment by bctiemann** [comment]
@tu3n4nh this seems potentially fairly serious; do you have a solution planned for the near future?
