### ISSUE TITLE
Enable assigning a new MAC address while editing an interface using the "quick add" feature

### ISSUE THREAD

**Issue by jeremystretch** [netbox-community/netbox#18045]
### NetBox version

v4.2-beta

### Feature type

New functionality

### Triage priority

I volunteer to perform this work (if approved)

### Proposed functionality

Following the implementation of #4867, MAC addresses are now managed as discrete objects (rather than as attributes on interfaces). This means that MAC addresses must now be created and explicitly assigned to an interface.

It should be possible to quickly create and assign a new MAC address when editing an interface, directly from within the interface edit form. This functionality was recently introduced by #5858, however additional work is needed to facilitate the automatic population of fields within a "quick add" form.

### Use case

This will provide a much smoother workflow for the user, allowing a MAC address to be assigned to an interface while editing other attributes of the interface.

### Database changes

N/A

### External dependencies

N/A

**Comment by ITJamie** [comment]
when creating new mac's it really would be useful to be able to select the OUI the mac should be coming from (related to request https://github.com/netbox-community/netbox/issues/18040) and generate a new mac on the fly.

in the case of virtual machines, bridges, bonds etc mac addresses need to be created. depending on if netbox is acting as a source of truth vs a source of record it would be great if netbox could generate next available mac from a pool of oui's
