### ISSUE TITLE
An error was reported when Adding Virtual Chassis

### ISSUE THREAD

**Issue by Blackwhite-Edward** [netbox-community/netbox#18049]
### Deployment Type

Self-hosted

### Triage priority

N/A

### NetBox Version

4.1.6

### Python Version

3.12

### Steps to Reproduce

![image](https://github.com/user-attachments/assets/bb7b7a4c-71e0-43f7-a022-e09f3a142a24)
An exception occurred when I added multiple members to the virtual cluster
One member is located in 38U of cabinet N02, and the other member is located in 38U of cabinet N03. However, when I was adding members, a message was displayed indicating that the two members cannot enter 38U at the same time. I understand that the virtual cluster can distinguish devices in different cabinets.

### Expected Behavior

An exception occurred when I added multiple members to the virtual cluster
One member is located in 38U of cabinet N02, and the other member is located in 38U of cabinet N03. However, when I was adding members, a message was displayed indicating that the two members cannot enter 38U at the same time. I understand that the virtual cluster can distinguish devices in different cabinets.

### Observed Behavior

Errors
Position
A virtual chassis member already exists in position 38.

**Comment by jeremystretch** [comment]
The position field is the member's logical position within the virtual chassis, not it's physical position in a rack. The VC position is administratively assigned and must be unique for each member.

**Comment by Blackwhite-Edward** [comment]
Tks.
