### ISSUE TITLE
Render Config fails with DataFile templates using dynamic include statements

### ISSUE THREAD

**Issue by ed-ud** [netbox-community/netbox#18066]
### Deployment Type

Self-hosted

### Triage priority

N/A

### NetBox Version

v4.1.4

### Python Version

3.12

### Steps to Reproduce

1. Create a Data Source with several Jinja2 template files:

start.j2:
{%- set PATH = 'my/prefix/' %}
{%- include PATH + 'test.j2' %}

my/prefix/test.j2:
SOME RENDERED TEXT

2. Create Config Template using the Data Source and the Data File start.j2
3. Attach Config Template to a Device
4. Select the Render Config tab on the Device

### Expected Behavior

Should not fail to render.

### Observed Behavior

Fails to render with TemplateNotFound 'my/prefix/test.j2' exception.

**Comment by ed-ud** [comment]
A potential fix is the recognize when the Jinja template files are using dynamic includes (the list of referenced_templates contains None entries) and in that case, include all DataFiles from the DataSource. 
In utilities/jinja2.py:
`
diff jinja2.py.orig jinja2.py
32,35c32,41
<             self.cache_templates({
<                 df.path: df.data_as_string for df in
<                 DataFile.objects.filter(source=self.data_source, path__in=referenced_templates)
<             })
---
>             if None in referenced_templates:
>                 self.cache_templates({
>                     df.path: df.data_as_string for df in
>                     DataFile.objects.filter(source=self.data_source)
>                 })
>             else:
>                 self.cache_templates({
>                     df.path: df.data_as_string for df in
>                     DataFile.objects.filter(source=self.data_source, path__in=referenced_templates)
>                 })
`

**Comment by pl0xym0r** [comment]
same as #17490

**Comment by jeremystretch** [comment]
Thank you for submitting this issue, however it appears that this topic has already been raised. Please see issue #17490 for further discussion.
