### ISSUE TITLE
Custom Links not working with all custom links: "rdp://" 

### ISSUE THREAD

**Issue by malte325** [netbox-community/netbox#18073]
### Deployment Type

Self-hosted

### Triage priority

I volunteer to perform this work (if approved)

### NetBox Version

v4.1.2

### Python Version

3.10

### Steps to Reproduce

Cusomization->Custom Links->Add:

- This Link is working: "ssh://some_ip"
- This Link is not Working "rdp://some_ip"
![ssh_config](https://github.com/user-attachments/assets/9dac608f-4da5-4670-8caf-7e60b0ba69c4)

When i klick on the ssh field the address is: "ssh/some_ip"
When i klick on the rdp field the address is: "https://netbox.local/dcim/devices/780/"

### Expected Behavior

That the Link is working!

### Observed Behavior

Thank you guys for your great work

**Comment by malte325** [comment]
![rdp_config](https://github.com/user-attachments/assets/7bf39d2a-cc31-408d-9470-6ec1ad3460be)

**Comment by jmcguir** [comment]
What do your allowed URL schemes have in them:

By default RDP isn't in that list. 

https://github.com/netbox-community/netbox/blob/develop/docs/configuration/security.md#allowed_url_schemes

**Comment by malte325** [comment]
Thank you!
