### ISSUE TITLE
HTTP_PROXIES no_proxy option gets completely ignored

### ISSUE THREAD

**Issue by Zombie-Toad** [netbox-community/netbox#18112]
### Deployment Type

Self-hosted

### Triage priority

N/A

### NetBox Version

v4.1.7

### Python Version

3.11

### Steps to Reproduce

1. Set HTTP_PROXIES settings in configuratoin.py
HTTP_PROXIES = {
  'http':'http://myproxy.com:8080',
  'https':'http://myproxy.com:8080',
  'no_proxy':'mydomain.com'
}
2. Restart netbox and netbox-rq services
3. Access internal Website via webhook

### Expected Behavior

For internal domains/subnets the "no_proxy"-setting should be used.

### Observed Behavior

Setting the proxy settings allows me to install plugins, but I can't access my internal websites via webhook. Netbox tries to connect to my internal websites via proxy no matter what I put into the no_proxy settings (subnet, domain, fqdn of the destination server).
There is no authentication needed for the proxy connection.

**Comment by DanSheps** [comment]
This is an upstream bug: psf/requests#4871, unfortunately we have no control over if/when this gets fixed

**Comment by YoucefYousfi** [comment]
@Zombie-Toad As a workaround until it is fixed, you should remove this configuration from configuration.py and instead modify the netbox systemd service file by adding the following :
```
[Service]
Environment='http_proxy=<your_proxy>'
Environement='https_proxy=<your_proxy>'
Environment='no_proxy=<your_no_proxy>'

```

I had the same problem when upgrading to 4.1 to use the plugin catalog and that's how I got around it until it gets fixed.
