### ISSUE TITLE
Create custom views to extend export templates feature

### ISSUE THREAD

**Issue by YoucefYousfi** [netbox-community/netbox#18129]
### NetBox version

v4.1.7

### Feature type

New functionality

### Triage priority

N/A

### Proposed functionality

This feature would allow to create a custom view that can cross-display columns from different tables based on a reconciliation key. For example, a custom view that displays a device display name, primary ip, serial and site tenant (or any other field from the Site view).

### Use case

This could be used to avoid creating export templates to cross the data for users, or export both tables and cross it themselves, especially when the goal is only to view the data and not work with it. Additionally, it could expand export templates to use those views as a base with filtering logic if needed.

**Comment by jeremystretch** [comment]
I'm afraid the proposed functionality exceeds the intended scope of custom export templates. Instead, I recommend you consider developing a [plugin](https://netboxlabs.com/docs/netbox/en/stable/plugins/) to achieve the desired view(s).
