### ISSUE TITLE
Add branching provider to configuration

### ISSUE THREAD

**Issue by arthanson** [netbox-community/netbox#18136]
### NetBox version

v4.1.7

### Feature type

New functionality

### Triage priority

N/A

### Proposed functionality

Add branching provider support as a configuration parameter and modify the script running code to take into account branching support.

### Use case

This will allow scripts with script parameters to be run while in the context of a branch.  This requires changes to the core of NetBox in the script running code as well as the branching plugin to support this.

### Database changes

N/A

### External dependencies

N/A

**Comment by jeremystretch** [comment]
Going to close this out in favor of the similar but more generic approach proposed in FR #18211 (which largely builds on the work in @arthanson's PR #18137).
