### ISSUE TITLE
Add dependancy graph visualisation tab

### ISSUE THREAD

**Issue by sgabenov** [netbox-community/netbox#18152]
### NetBox version

v4.1.7

### Feature type

Other

### Triage priority

N/A

### Proposed functionality

On netbox there are several places where objects are grouped and they have a parent or children. For such structures, like 'sites', 'tenants', 'contacts' we can build a dependancy graph and it can be visualised. 
I assume, it can be an additional tab, where this dependancy is drawn.
I have found some article, where there was a graph for db dependancy, so probably it can be done similar to object representation.

Should look something like this:
<img width="829" alt="graph" src="https://github.com/user-attachments/assets/031a8258-02e9-4254-a247-6df26cfe3a35">

The image is taken from this article: https://www.opticoreit.com/learning-development-blog/netbox-entity-relationship-diagrams/

### Use case

We can view a relationship for objects. Sometimes netbox can be used as a place to store org structure contacs and it will help to display a structure of a company

**Comment by jeremystretch** [comment]
I'm afraid this is out of scope for NetBox core, but I encourage you to consider building a plugin to implement this functionality.
