### ISSUE TITLE
Prefix (Container) utilization does not calculate correctly when has children is Container

### ISSUE THREAD

**Issue by emallette** [netbox-community/netbox#18176]
### Deployment Type

Self-hosted

### Triage priority

N/A

### NetBox Version

v4.1.7

### Python Version

3.12

### Steps to Reproduce

1. I create a Container (Top-Level-Container) say 10.0.0.0/8
2. I create a sub-tended container say 10.0.0.0/9.

The utilization of the top-level-container is immediately 50%.  The sub-tended container utilization is 0%.  Shouldn't it aggregate the utilization of the sub-tended containers ?  It does not.

### Expected Behavior

I would expect the top-level container to correctly reflect the utilization based on the sub-tended containers.  In this case I would expect 0% utilization to still be shown.

### Observed Behavior

50% utilization was  shown rather than 0% utilization.
![IPAM-Container](https://github.com/user-attachments/assets/0b88e779-a8b5-4d2b-ad9f-320de5132219)

**Comment by jeremystretch** [comment]
This is working as expected: The /9 container allocates 50% of its parent /8.
