### ISSUE TITLE
Can not create a Duplicate IP-Range with ENFORCE_GLOBAL_UNIQUE set to false

### ISSUE THREAD

**Issue by antonvdl** [netbox-community/netbox#18198]
### Deployment Type

Self-hosted

### Triage priority

N/A

### NetBox Version

V4.1.7

### Python Version

3.12

### Steps to Reproduce

Configuration parameter ENFORCE_GLOBAL_UNIQUE set to false

1. Click on IPAM -> IP Ranges
2. Click on Add
3. Add an IP range (Leave VRF empty)
4. Add the same IP range again (Leave VRF empty)

### Expected Behavior

An overlapping IP range should be created

### Observed Behavior

Error message:
Defined addresses overlap with range xxx.xxx.xxx.xxx-xxx/xx in VRF None

**Comment by jeremystretch** [comment]
This is intended behavior: Per the error message, IP ranges are not permitted to overlap with one another.

**Comment by antonvdl** [comment]
Hi @jeremystretch,

what is the logic behind it that we can create duplicate IP addresses, duplicate Prefixes but not duplicate IP-ranges?
