### ISSUE TITLE
unable to create a mac-address linked to a virtual machine interface via api

### ISSUE THREAD

**Issue by leelists** [netbox-community/netbox#18201]
### Deployment Type

Self-hosted

### Triage priority

N/A

### NetBox Version

v4.1.7

### Python Version

3.12

### Steps to Reproduce

POST to http://netbox:8000/api//dcim/mac-addresses/
with body :
{
  "assigned_object_id" : 9,
  "assigned_object_type" : "virtualization.vminterface",
  "mac_address" : "BC:24:11:10:2E:1F"
}

returns {"assigned_object_id":["This field cannot be null."]}

the same action via the gui works : 

tags: []
comments: ""
description: ""
mac_address: "BC:24:11:10:2E:1F"
custom_fields: {}
assigned_object_id: 9
assigned_object_type: 127

### Expected Behavior

linking mac adresse to virtual interface should work via api

### Observed Behavior

{"assigned_object_id":["This field cannot be null."]}

**Comment by bctiemann** [comment]
@leelists This will likely change behavior in v4.2 as MAC addresses are now handled as discrete objects in the schema rather than fields on interfaces. Could you please revisit this after 4.2 is available (or in the beta)?

**Comment by leelists** [comment]
I will give the beta a try, thanks
