### ISSUE TITLE
'VirtualMachine' object has no attribute 'oob_ip_id'

### ISSUE THREAD

**Issue by krasotinpa** [netbox-community/netbox#18230]
### Deployment Type

Self-hosted

### Triage priority

N/A

### NetBox Version

v4.1.8

### Python Version

3.12

### Steps to Reproduce

1. Assign IP address to VM's interface
2. Try to Edit assigned IP

### Expected Behavior

Editing of IP address is available

### Observed Behavior

```
<class 'AttributeError'>

'VirtualMachine' object has no attribute 'oob_ip_id'

Python version: 3.12.8
NetBox version: 4.1.8
Plugins: None installed
```
![image](https://github.com/user-attachments/assets/ceb437a4-5c14-4238-8f0d-35f262522d9b)

**Comment by kukabu** [comment]
Hello
I don't agree with this fix. I think better to add oob_ip_id to VM.
For example, Cisco Catalyst 9800-CL Wireless Controller for Cloud Deployment has OOB.
https://www.cisco.com/c/en/us/td/docs/wireless/controller/9800/technical-reference/c9800-cl-dg.html#9800CLnetworkinterfacemappings

**Comment by bctiemann** [comment]
@kukabu If you think it's worth adding that functionality, please open a feature request.
