### ISSUE TITLE
MAC Addresses table missing Description column

### ISSUE THREAD

**Issue by sleepinggenius2** [netbox-community/netbox#18278]
### Deployment Type

Self-hosted

### Triage priority

N/A

### NetBox Version

v4.2-beta1

### Python Version

3.12

### Steps to Reproduce

1. Click on `Devices > Addressing > MAC Addresses` in the main menu
2. The table does not have a `Description` column by default
3. Click on the `Configure Table` button
4. There is no option to select the `Description` column

### Expected Behavior

The `Description` column is available on the `MAC Addresses` table. I believe it should be a default column as well, as it seems to be for most of the other tables, and that one in particular doesn't have very many columns to start with.

### Observed Behavior

The `Description` column is not available on the `MAC Addresses` table.

**Comment by jeremystretch** [comment]
It appears that the comments and tags columns have been mistakenly omitted as well.
