### ISSUE TITLE
Assign existing device to rack from rack layout window

### ISSUE THREAD

**Issue by tbasten** [netbox-community/netbox#1830]
[x] Feature request
[ ] Bug report
[ ] Documentation
Environment

    Python version: 3.5.2
    NetBox version: 2.2.8

Description

Would love to be able to assign existing devices to a rack slot when you click Add Device from the rack layout Window.

I see it being similar to how you can search for an IP address when assigning an IP to a management interface.

**Comment by thefreakquency** [comment]
Pretty please!!! ;)

**Comment by tb-killa** [comment]
For this we should add "dropdown" Menu on the Button Layer "add device" who open two Subs:
- Add New Device
- Add existing Device

If existing Device is selected we could use "select2" work and bring in search bar who you type the name of your device like a live search and select.

This would be the simplest solution i think.

**Comment by PeepOks** [comment]
It think better "add-device" to rack can be done same way like "Add IP Address" to interface is done. 
"Add device" view should include "add existing device" tab. In this view only devices, that are in same "Site" as rack is, should be listed.

After new or existing device is added to rack, there should be redirect to rack view where we started. I think "return_url" variable can be used for that.

**Comment by kobayashi** [comment]
As discussed in PR #4190 , we should consider again this function.

**Comment by jeremystretch** [comment]
I'm closing this feature as we've found that the development overhead it requires outweighs the minor convenience it provides.
