### ISSUE TITLE
Device Physical Port Utilization

### ISSUE THREAD

**Issue by tuxmelv** [netbox-community/netbox#1957]
### Issue type
[ X ] Feature request 
[ ] Bug report      
[ ] Documentation   

### Environment
* Python version:  3.5.2
* NetBox version:  2.3.1

### Description
It would be nice to have a per device Interface Utilization based on Connections already in Netbox vs the total number of physical ports configured. Virtual interfaces would be excluded. Utilization graph would be present on the Devices list as well as in the header of the "Interfaces" table when viewing a specific Device. The ability to exclude interfaces from this feature would allow uplink ports to not be counted.

If possible, a stacked graph that shows used ports similar to the existing Rack or Prefix utilization graphs, but also includes another color for planned connections.

Feature would assist in Capacity Planing based on Physically available ports in a readily viable format

**Comment by snowie-swe** [comment]
As it has to do with capacity planning I believe it’s good that you have the option in settings or elsewhere to toggle how this should be counted

Ie

- connected
- planned
- interface with description
