### ISSUE TITLE
Add a query filter for every object type

### ISSUE THREAD

**Issue by jeremystretch** [netbox-community/netbox#2101]
### Issue type
[x] Feature request 
[ ] Bug report      
[ ] Documentation   

### Environment
* Python version:  3.5.2
* NetBox version:  2.3.3

### Description
For the sake of consistency, we should have a query filter for each object type, even if it's empty. Some views, like BulkEditView and BulkDeleteView, rely on the presence of a filter for performing bulk operations on _all_ objects matching a parameter (e.g. deleting all devices matching a certain name, instead of just those selected in the list).

This was inspired by the issue raised in #2097.

**Comment by mkerins** [comment]
Hi @jeremystretch , do you mean make sure each `<model>ListView` and `<model>BulkDeleteView` has has a `filter = filters.<model>Filter`? For example `RackRoleListView` and `RackRoleBulkDeleteView` in `dcim/views.py` don't have `filter = filters.RackRoleFilter` even though they exist in `dcim/filters.py`

**Comment by jeremystretch** [comment]
Per #3998 this should include the console/power/interface connection views as well.
