### ISSUE TITLE
Create duplicate [update], [create] and [cancel] button at the top of the page

### ISSUE THREAD

**Issue by SandMouse** [netbox-community/netbox#2237]
As a new user to this very helpful software I find my self scrolling down to the bottom of the page to click [create], [update] or [cancel] (etc, etc) many times a day. Since I'm still trying to find my way in and around this software I keep making many, many -small- changes. Mainly to the fields in the first part of different pages. After those changed I need to scroll down and choose a command to finish my input. E.g. [create], [update] or [cancel]. Would it be possible to add a duplicate set of buttons one can find at the bottom of the page, at the top of the page? See attached mock-up.
![screen_shot_2018-07-13_at_15_51_28](https://user-images.githubusercontent.com/5917501/42695367-80b12ca8-86b5-11e8-9071-63ad68228184.jpg)

**Comment by mmahacek** [comment]
Yes please.

**Comment by jeremystretch** [comment]
Buttons are included only at the bottom to ensure that the user sees the entire form. Not sure about adding a duplicate set of buttons. How about moving the buttons to a fixed position to the right of the edit form, so that the buttons stay in one place as the user scrolls?

**Comment by mmahacek** [comment]
I like the idea of floating buttons. I would not need buttons at the top when creating a new item as much as they would help modifying an existing item.

**Comment by hellerve** [comment]
While this generally seems to work just fine, this will break the responsiveness of the site. Once the page width is under certain threshold, the form takes up the whole width of the page. Making the buttons float would make them float over the form. So I guess this type of fix will in fact only affect people who use Netbox on their desktop computer with the window larger than a certain width (992px seems to be the magic number).

This is good enough for me, but I’m not sure whether this is congruent to the fix that was originally envisioned.
