### ISSUE TITLE
Documentation for extras.reports missing

### ISSUE THREAD

**Issue by konaya** [netbox-community/netbox#2317]
### Change Type
[X] Addition
[ ] Correction
[ ] Deprecation
[ ] Cleanup (formatting, typos, etc.)

### Proposed Changes
The extras.reports endpoint is completely absent from the Swagger /api/docs/ thingy.

**Comment by TakeMeNL** [comment]
Seems fine for me

**Comment by Gelob** [comment]
It is there for me on 2.6.5. This can probably be closed.
![Screen Shot 2019-10-02 at 11 59 13 AM](https://user-images.githubusercontent.com/422752/66064987-1c610780-e50c-11e9-83c9-4cabce902ffa.png)

**Comment by kobayashi** [comment]
Yes, the feature is there.
