### ISSUE TITLE
Adding view option on rack

### ISSUE THREAD

**Issue by snowie-swe** [netbox-community/netbox#2380]
**Feature request.**

### Environment
NetBox version: 2.4.3

### Proposed Functionality

Under rack view add the possibility to toggle between all/active/planned devices.

### Use Case

When sending out fieldworkers to rack devices we would like to highlight the current equipment and what is planned to be added. In many cases a device can be listed as planned for weeks before its mounted. So it would be nice to be able to take out 2 views from netbox.
Excising and then how it should look like when done.

**Comment by jeremystretch** [comment]
Marking this as blocked until we get SVG rack rendering in place (#2248).
