### ISSUE TITLE
Add a "Create and assign IP" button to interface creation dialog

### ISSUE THREAD

**Issue by kasimon** [netbox-community/netbox#2434]
### Environment
* Python version: 2.7.13
* NetBox version: 2.4.4

### Proposed Functionality
Add another blue "Create and assign IP" button to the interface creation dialog that results in the same view as pressing the green "+" on a interface.

### Use Case
Often when adding an interface, users also want to assign an IP address to it. Also the distinction between interface itself and ip addresses configured on the interface (that makes perfectly sense) can be a difficulty to grasp. They have to find the mouseover on the green plus of the created interface to find out how to configure an address to the interface. Having a shortcut directly from the interface creation dialog would result in a much more streamlined experience.

### Database Changes
None.

### External Dependencies
None.

**Comment by kasimon** [comment]
I will try to come up with a patch myself.

**Comment by jeremystretch** [comment]
Assigning to @kasimon

**Comment by jeremystretch** [comment]
@kasimon Are you still working on this?

**Comment by kasimon** [comment]
@jeremystretch I still intend to do so. Haven't had the time for it yet unfortunately.

**Comment by jeremystretch** [comment]
@kasimon have you been able to make any progress on this?

**Comment by kasimon** [comment]
Thank a lot for implementing this, @checktheroads!
