### ISSUE TITLE
Add a group ID field to the IP address model

### ISSUE THREAD

**Issue by jeremystretch** [netbox-community/netbox#2456]
### Environment
* Python version: 3.5.2
* NetBox version: 2.4.4

### Proposed Functionality
Add a numeric `group_id` field to the ipam.IPAddress model, which accept a value between 0 and 255 (incusive).

### Use Case
Although NetBox allows for the designation of an IP address as a virtual/shared IP address (e.g. VRRP, HSRP, etc.), it does not provide a mechanism to associate the IP with a particular group within an interface. For example, VRRP requires the definition of a group ID (0-255), which is used to generate the virtual MAC address for the shared IP address.

### Database Changes
Add the field to the IPAddress model. This will require a new database migration.

### External Dependencies
None

**Comment by TechRazor** [comment]
@jeremystretch the range 0 to 255 will cover VRRP and HSRPv1, but HSRPv2 has an extended range of 0 to 4095. I like to match up the HSRP group to the vlan number for consistency so I have a lot of HSRP groups above 255.

**Comment by lunarthegrey** [comment]
I'd like to see this added a lot :+1:

**Comment by ebais** [comment]
We came to the same 'issue' that we wanted to register VR-ID's .. For now we ended up adding a custom field to a vlan.

**Comment by jeremystretch** [comment]
Closing this in favor of a more complete implementation as proposed under #6235.
