### ISSUE TITLE
Toggle the display of available child prefixes

### ISSUE THREAD

**Issue by snowie-swe** [netbox-community/netbox#2598]
**Environment**
NetBox version: 2.4.6

**Proposed Functionality**
Under Child prefixes add a toggle button to view available prefixes or not.
Default option in my opinion should be to have the available prefix hidden.

If you add a 10.0.0.0/8 as prefix you will automatically get several hundreds of available lines when viewing it under child prefixes that interfere with the user experience of the GUI.

![image](https://user-images.githubusercontent.com/41901413/48769475-0c598400-ecbc-11e8-911d-d5ddc95562f1.png)

**Use Case**
User friendliness

**Database Changes**

**External Dependencies**

**Comment by jeremystretch** [comment]
Please note that this change would require substantial work on the UI and likely won't be implemented for some time.

**Comment by snowie-swe** [comment]
Asked our devops to fix it in our production env.
If its of interest i will ask them to upload the code changes needed. 

![image](https://user-images.githubusercontent.com/41901413/50041270-a6f67a00-0052-11e9-8aff-e362c7f5069f.png)

![image](https://user-images.githubusercontent.com/41901413/50041278-c55c7580-0052-11e9-9a1a-0fb664e923fd.png)
