### ISSUE TITLE
End-to-end cable trace with "You are here!"

### ISSUE THREAD

**Issue by lcioltan** [netbox-community/netbox#2942]
### Environment
* Python version:  3.5.3
* NetBox version:  v2.5.7

### Proposed Functionality
When using the Trace option, it would be nice to always output the whole path 
and mark the place from where the Trace option has been called.

### Use Case
Let's use the following scenario. "Router-1" is connected to "Router-2" via 3 patchpanels:
Router-1/Port1 **--->** PP-A/Port-3  **--->** PP-B/Port-7 **--->** PP-C/Port-6 **--->** Router-2/Port-2

1. in Netbox, if I select Router-1 and use the Trace option for "Port-1", the whole path will be displayed:
Router-1/Port-1 ---> PP-A/Port-3  ---> PP-B/Port-7 ---> PP-C/Port-6 ---> Router-2/Port-2

2. If I select patchpanel "PP-A" and use the Trace option for "Port-3", the following 2 paths 
will be displayed, depending on whether I use the front or the rear port:
PP-A/Port-3 (Front): Router-1/Port-1 ---> PP-A/Port-3 
PP-A/Port-3 (Rear): PP-A/Port-3  ---> PP-B/Port-7 ---> PP-C/Port-6 ---> Router-2/Port-2

With my proposal, I would like to have the complete path permanently displayed and to just mark the position from where the Trace function has been called.
1. **Router-1/Port-1** ---> PP-A/Port-3  ---> PP-B/Port-7 ---> PP-C/Port-6 ---> Router-2/Port-2
2. Router-1/Port-1 ---> **PP-A/Port-3**  ---> PP-B/Port-7 ---> PP-C/Port-6 ---> Router-2/Port-2

### Database Changes
None.

### External Dependencies
None.

**Comment by DanSheps** [comment]
I will be honest, I think this would be a lot of development work for very little reward.

**Comment by tb-killa** [comment]
It's the same FR like https://github.com/digitalocean/netbox/issues/2758.
There we do the same discussion and it seems to be possible.

**Comment by jbakklund** [comment]
This seems to be a task for a recursive function, searching in both directions for the next port until it hits an interface, and then return the path.

**Comment by jameswhite4684** [comment]
This is a great functionality and this can help anyone understand the cable flow of the network. That is one of the toughest things to map out and understand what is connected where without having to be inside the network device.

**Comment by jameswhite4684** [comment]
It seems to work on add-on t1 cards now, I thought that wasn't working before but now I see it is. Great job there!

**Comment by seismiccollision** [comment]
+1 
I think the expected result for clicking on a trace would be seeing interface-to-interface regardless of where in the path the trace was called. If it is difficult to do, maybe a compromise would be having the ability to initiate a trace from the far-end back within any trace? This would at least save users the step of next clicking into a device and scrolling down to the right interface

**Comment by jeremystretch** [comment]
Leaving this open for grabs if someone wants to pick it up. Otherwise, it will be closed after a month for inactivity.
