### ISSUE TITLE
API spec requires model fields on PATCH

### ISSUE THREAD

**Issue by lampwins** [netbox-community/netbox#3007]
### Environment
* Python version:  3.7
* NetBox version:  develop-2.6

### Steps to Reproduce
1. Load the API spec `/api/swagger.json`

### Expected Behavior
Model PATCH methods should not define required fields.

### Observed Behavior
PATCH methods use the same definitions as POST and PUT methods, which define required model fields.

<img width="621" alt="Screen Shot 2019-03-14 at 2 53 56 PM" src="https://user-images.githubusercontent.com/1297132/54383825-500c3b00-4669-11e9-88fb-3c9952e6883b.png">
<img width="314" alt="Screen Shot 2019-03-14 at 2 54 03 PM" src="https://user-images.githubusercontent.com/1297132/54383835-57cbdf80-4669-11e9-9a12-a5013ca80594.png">

This is an extension of conversations in #2665. @axnsan12 would you have any input on this? It seems like one way to do it would be to define separate serializers, but that doesn't seem fun and from reading the drf-yasg docs, picking the serializer based the request method isn't recommended anyway.

**Comment by jeremystretch** [comment]
AFAICT this seems to be a bug in drf_yasg, where required fields are marked without respect to the type of request being made. I don't think this is something that we can reasonably fix within NetBox, but I may be wrong. Closing this out but will re-open if anyone wants to propose a specific fix.
