### ISSUE TITLE
Allow filtering cables by tenant of connected device

### ISSUE THREAD

**Issue by xonacs** [netbox-community/netbox#3021]
### Environment
* Python version:  3.6.6
* NetBox version:  2.5.8

### Proposed Functionality
Currently, a tenant's device might be linked to another tenant or provider device via one ore more cables.  It is not possible to see easily identify all connections across tenants. Therefore Cables need to have a tenant ownership or else there needs to be a view that shows all cables related to a tenant.

### Use Case
As a data center and that uses Netbox we maintain a full list of equipment, customer and own.  Currently it is possible to assign an ID to all services provided to a customer (tenant).  Prior to the introduction of cables in Netbox, a Circuit (type: "Uplink") was used to indicate the physical link providing the customer connectivity.  The tenant of such an ID was the customer.  This allows for a comprehensive view of everything a customer(tenant) has, i.e. all devices, racks, vlans, IPs, physical uplinks, circuits etc.  

Having a cable that is assignable to a tenant or being able to filter all cables connecting to a tenant's device would restore this ability without having to resort to using Circuits (which is incorrect as it creates two cables when there would be one).

**Comment by jeremystretch** [comment]
There is no need to declare an explicit relationship to a tenant on the cable model, as the endpoints of a cable already have this association. (It also begs the question: who would own a cable connecting tenants A and B?)

It sounds like you want to be able to filter cables based on the tenant assigned to either end. If this is the case, please revise your FR to better capture the use case and remove the proposed relationship (or close this and open a new FR if you prefer).

**Comment by xonacs** [comment]
Updated FR, thanks.
