### ISSUE TITLE
Improve documentation for API filtering

### ISSUE THREAD

**Issue by ajknv** [netbox-community/netbox#3037]
### Environment
* Python version:  3.6.8
* NetBox version:  2.5.7

### Steps to Reproduce
1. Try to query interfaces using multiple filter values for "mac_address", or "device_id".

### Expected Behavior

The API should return all of the records matching any of the filter values as documented.

### Observed Behavior

Only results matching the final filter value are returned, contrary to the documentation indicating that a logical OR should have been performed.

The patch applied for https://github.com/digitalocean/netbox/issues/2577 still results in quite deficient documentation. "Certain filters can be included multiple times" -- how can we know or determine *which* ones? Any why only those ones? At the very least if the filter cannot be properly honored with multiple values the API should respond with an error, so consumers of the API aren't potentially just chugging along with missing data that was silently dropped.

**Comment by shanemadden** [comment]
Coverage in the docs of what filters are supported on what endpoints would be great as well - the handful of attributes that don't filter can be a little surprising, like `dcim/interface-templates/?device_type=<device_type_id>`

**Comment by jeremystretch** [comment]
IMO this is not a documentation problem, but a bug with the filters.

**Comment by hSaria** [comment]
Referring to the bug, this is fixed in v2.6.12 (possibly earlier, but didn't check); you can specify multiple values and they'll be OR-ed.

**Comment by jeremystretch** [comment]
Agreed. Going to consider this resolved.
