### ISSUE TITLE
Visibility of tags in Device listing

### ISSUE THREAD

**Issue by candlerb** [netbox-community/netbox#3064]
### Environment
* Python version:  3.5.2
* NetBox version:  2.5.10

### Proposed Functionality

I would like to be able to see tags in the Device listing.

Possible ways to achieve this:

* Include tags in the 'role' column
* Make it customisable which columns are visible; I could then replace Tenant with Tags
* View tags when hovering over device (less desirable, I really want to see them)
* A separate devices-with-tags view
* A checkbox on the device listing, which toggles between the normal view and the tags view (for example, Type and IP Address could be replaced with Tags when this is checked)

### Use Case

I am using tags for several purposes.  Seeing the set of tags for a device quickly lets me home in on devices of interest; it also lets me see quickly if there are conflicting tags which don't make sense (e.g. someone has added a tag but forgotten to remove an old one).

At the moment, the only way to see tags is (a) to drill down to individual devices one by one, or (b) to filter devices by tag (in which case, I still can't see what *other* tags are on a device, without drilling down)

### Database Changes

None

### External Dependencies

None

**Comment by candlerb** [comment]
In addition: I would like to see Inventory Item tags in the Inventory listing (`/dcim/devices/<pk>/inventory/`)

At the moment you can't see the tags unless you drill down to individual items, and the only way to filter inventory items by tag (AFAICT) is to browse to `/extras/tags/<name>/` and look for tagged inventory items

**Comment by jeremystretch** [comment]
I'd like to do this, but realistically, the only we can accommodate tags in object list display is to switch to a multi-row object representation. This would allow us to display object fields on one line and tags on another.

Currently, object lists are rendered as a simple HTML table, which each object in the list corresponding to a single row in the table. We would need to extend this to either a) use multiple rows to represent each object, or b) embed a smaller table/div structure within each row. Neither approach is likely to work well with `django-tables2`. Need to dig into this further.

**Comment by Armadill0** [comment]
I'm quite interested in this because this would also be very interesting for the ip-addresses listing (/ipam/ip-addresses/ and /ipam/prefixes/<prefix-id>/ip-addresses/).

Use case: Tagging an ip address within a prefix e.g. as "gateway" to be able to use those information on our servers for the network setup. But the information is currently only shown in the IP address detail page which makes it annoying to check the prefix if a gateway has already been defined.

Should I open another feature request for that?

**Comment by fallenfuzz** [comment]
+1 
To see tags everywhere in columns, prefixed, ip addresses etc

Thanks

**Comment by a-d-v** [comment]
+1 This would be a very useful addition indeed!

**Comment by jeremystretch** [comment]
Reminder: Please use :+1: or :-1: on the issue to indicate support or the lack thereof. Redundant comments will be deleted.

**Comment by jeremystretch** [comment]
With #492 in place, we can now add a "Tags" column to the relevant tables, which can be toggled on and off as the user desires. For particularly large tables, such as the devices table, it is assumed the user will hide uninteresting columns to make room if there is a large number of tags.
