### ISSUE TITLE
Allow filtering interfaces by type on device view

### ISSUE THREAD

**Issue by jeremystretch** [netbox-community/netbox#3090]
### Environment
* Python version:  3.5.6
* NetBox version:  2.5.10

### Proposed Functionality
Add a dropdown menu at the top of the device interfaces tables (next to "show IPs") to allow filtering interfaces by form factor/type. ~We don't have any sufficient UI framework in place yet to do this dynamically, so for now we're looking at a full page refresh: A link to something like `/dcim/devices/123/?interface_type=800`.~ A search box with some jQuery to display only interfaces with a matching name should suffice.

### Use Case
Some switches, especially large chassis switches, can have hundreds of interfaces. Sometimes a user may want to edit all interfaces of a certain type in bulk. Currently, this requires selecting each interface individually.

### Database Changes
None

### External Dependencies
None

**Comment by mmahacek** [comment]
Maybe also a filter for connected/not connected or enabled/disabled? I don't know that I see a benefit to having all fields filterable here.  However, being able to sort by any column on the fly would be nice.
I would also suggest adding a count of interfaces to the table header, so users know how many are filtered out.  Mock up images attached.

![image](https://user-images.githubusercontent.com/26419758/56431526-d6c2c200-627e-11e9-98af-2c84122b94cd.png)
![image](https://user-images.githubusercontent.com/26419758/56431535-e17d5700-627e-11e9-86bd-d49a5ea44dbe.png)
