### ISSUE TITLE
Replace all instances of .extra() in QuerySets with annotations

### ISSUE THREAD

**Issue by jeremystretch** [netbox-community/netbox#3117]
### Proposed Changes
There are several instances where `.extra()` is used to extend a QuerySet. These should be replaced with `.annotate()` using `RawSQL` where necessary.

### Justification
`.extra()` is [planned for deprecation](https://docs.djangoproject.com/en/2.2/ref/models/querysets/#extra).

**Comment by KhaledTo** [comment]
Looks like it's done (looking at master branch). Can someone confirm that?

**Comment by KhaledTo** [comment]
Would like to work on this.

**Comment by kobayashi** [comment]
closed in e223c88
