### ISSUE TITLE
Improve documentation of the distinction among power ports, outlets, feeds, and panels

### ISSUE THREAD

**Issue by lampwins** [netbox-community/netbox#3135]
### Environment
* Python version:  
* NetBox version:  

### Proposed Functionality
With the advent of the new power related functionality in 2.6, we need to better distinguish between the intended use of the various power components.

### Use Case
As a person that is by no means an expert or even a novice when it comes to power infrastructure, I myself still get confused between the proper use of power outlets and power ports. Now that we have the concept of a power feed, that gets even more confusing. Certainly, some of this can be cleared up with more/better documentation, but I feel there may also be room to better qualify in the UI what these components are meant to do, so the UX becomes more intuitive.

I propose a couple of options:

1. Anywhere "Power Ports" is referenced in the UI, append "(Input)" and anywhere "Power Outlets" is referenced, append "(Output)".
2. In the UI either refer to Power Ports as "Power Supply Ports" or officially rename the model. To that end, maybe there is a better name/word to use?

### Database Changes
By making changes in the UI only, no DB changes are needed, but the option of renaming a model would ensure a migration.

### External Dependencies
N/A

**Comment by jeremystretch** [comment]
IMO "outlet" is a pretty common household word. ("I need to vacuum, where's the nearest outlet?") The word itself implies that power is being _let out_. I don't think it needs any further explanation.

Granted, "power port" is more ambiguous, but what would you rename it to? Power input? Power inlet?

Also, while I always strive to make things as intuitive as possible, I don't think that asking a user to remember that a "power port" consumes power is unreasonable.

**Comment by candlerb** [comment]
I think "Power Inlet" is clear and unambiguous, and is the obvious counterpart to "Power Outlet" - whereas a "power port" could be in or out.

**Comment by wols** [comment]
Let yourself be inspired eg. [Rittal - Power distribution - IT power - ...](https://www.rittal.com/com-en/product/list.action?categoryPath=/PG0001/PG0229STV1/PG7274STV1l)

**Comment by jeremystretch** [comment]
So this didn't make it into the beta; next change would be v2.7. Renaming the model would require a large amount of work for very little gain and a considerable amount of confusion and downstream work (people updating the field name in API consumer logic). Is this really worth keeping open?

**Comment by MarcHagen** [comment]
Maybe adding this to #792? Because that's a big feature with lots off work.

**Comment by flashbyte** [comment]
HI, 
as a not native speaker I am quid confused about the different power components in netbox. I don't need  the models to be change, but would really much appreciate and updated in the documentation. Maybe even a small diagram to explain what goes where and it intended usage.

**Comment by sdktr** [comment]
> HI,
> as a not native speaker I am quid confused about the different power components in netbox. I don't need the models to be change, but would really much appreciate and updated in the documentation. Maybe even a small diagram to explain what goes where and it intended usage.

Fully agree, diagrams that can be looked up in the documentation and/or referenced from the GUI would be nice for non-native speakers

**Comment by jeremystretch** [comment]
Accepting this as a documentation improvement. (To be clear, none of the model names will change as that would be very disruptive.)

**Comment by hSaria** [comment]
I'll work on a `Power` page under `Core Functionality`. Structuring it hierarchically (i.e. starting at closest to power origin, ending closest to the device) should reduce reduce confusion for the reader and hopefully allow people to model their power circuits appropriately on the first try.
