### ISSUE TITLE
Add support for a deprecated status on cables

### ISSUE THREAD

**Issue by yarnocobussen** [netbox-community/netbox#3145]
### Environment
* NetBox version: 2.5.12

### Proposed Functionality
Add a deprecated status to cables.

### Use Case
Used in the workflow of cable management.

Racks provide clarity on physically adding and removing through the states reserved and deprecated. Devices have planned and decommissioning. The cable planned state can't tell you if a cable needs adding or removing.

We generate work orders for datacenter personnel by querying Netbox's API and creating tickets with the data parsed into tasks. This way we integrate our source of truth into projects and force callbacks to the Netbox system. It would be great to be able to integrate our cable management into this as well.

### Database Changes
None

### External Dependencies
None

**Comment by DanSheps** [comment]
Just to add a little information for discussion:

Currently cable status is a boolean (0,1) value.  With 0 being planned and 1 being connected.

This would obviously require a change to that.  Are there any other potential status values that might ne desired?


(Keep in mind, I am not saying this is accepted or rejected, just for more informational purposes)

**Comment by yarnocobussen** [comment]
My apologies for missing that detail. That means accepting this request would lead to a change in functionality, instead of an addition.

We're requesting this because interfaces and cables are ineligible for custom fields. Tags seem an inappropriate alternative, but we could at least have a working solution with them if this request were to be rejected.

If this request does turn out to be acceptable, a failed state might be desirable as well. It would indicate the cable needs replacing. This also fits with the device model, which has this status type as well.

**Comment by candlerb** [comment]
Aside: Device has a recently-added "Decommissioning" status, which also captures the idea of "scheduled to be removed".

**Comment by louis-oui** [comment]
Hello, any news on the topic ?

**Comment by Xelinor** [comment]
> Aside: Device has a recently-added "Decommissioning" status, which also captures the idea of "scheduled to be removed".

I would agree with this. It would make more sense to re-use a term used elsewhere for consistency.

Now, going against my own reccomendation above, I would also reccomend 'Inactive' as another valid choice to be included. My company often plans out patch panels for future expansion, and the wiring between the patch panels sits dark for months or even years, simply ready to be used when needed.
