### ISSUE TITLE
Direct link from Site to Elevations

### ISSUE THREAD

**Issue by candlerb** [netbox-community/netbox#3152]
### Environment
* Python version:  3.5.2
* NetBox version:  2.5.12

### Proposed Functionality

On the Site detail page (`/dcim/sites/foo/`), include a link to the elevations for that site (`/dcim/rack-elevations/?site=foo`)

I suggest this belongs near the "Images" pane.

### Use Case

At the moment, to see elevations for a given site, you first have to navigate to `Racks > Elevations`, then apply a filter for the site.  Even if you've already navigated to the relevant Site (which is easy from a device), you have to search for the site again.

Elevations are the chief visualization provided by Netbox, and I think it should be easier to navigate to them.

### Database Changes

None

### External Dependencies

None

**Comment by tb-killa** [comment]
@candlerb If you create ``Rack Groups`` with your Racks and go to the ``Site`` you will see this ones:

![image](https://user-images.githubusercontent.com/932481/57209748-0d683e80-6fda-11e9-8860-c3d950df7207.png)

If you click on the Button (marked yellow) you will return to the ``Rack Elevations`` with URL-Parameters ``/dcim/rack-elevations/?group_id=3``.

If this would be accepted and implemented i prefer the Link for the ``Rack Elevations`` on the ``Sites`` Template as an own "Panel" with URL Link like ``/dcim/rack-elevations/?sites_id=XXX``

**Comment by jeremystretch** [comment]
I've looked at this for a while and I honestly can't find a good place to put a link. Doesn't make sense to put it inside the rack groups panel.

**Comment by bellwood** [comment]
Under the details for a site, why not just add another tab between "Site" and "Change Log" called "Elevations" and let it take the user to the elevations for a site and if they need to drill down further, they can filter as needed (Rack group, etc)

**Comment by jeremystretch** [comment]
I snuck an "all racks" entry into the rack groups table.
