### ISSUE TITLE
Pre-populate Site and Rack for cable endpoint

### ISSUE THREAD

**Issue by candlerb** [netbox-community/netbox#3177]
### Environment
* Python version:  3.5.2
* NetBox version:  2.5.12

### Proposed Functionality

When you add a new cable (by clicking the "connect" button next to an interface/port), the right-hand side offers two tabs to select the remote device: "Search" or "Select".

The "Select" tab has five fields: Site, Rack, Device, Type, Name.

I propose that in the "Select" tab, the Site and Rack be pre-selected as the Site and Rack of the originating connection (but still changeable).

### Use Case

Many connections are made within a rack, e.g. from device to top-of-rack switch or patch panel.

Being able to go to "Select" and finding the Site/Rack preselected makes data entry quicker and easier: you can quickly select from a short list of devices within that rack.  It also reduces the risk of accidentally creating a cross-rack or cross-site connection when that was not intended.

### Additional notes

The above feature request is complete for Netbox 2.5 as-is.

However I note from #2669 that from 2.6 device names need not be globally unique.  The current "Search" tab therefore might need a Site field adding.  In this case, it would still be helpful to have the Site pre-selected (on the basis that most connections made are within a Site).

At this point, it would seem to make sense to combine the Search and Select options into a single option with 5 fields (Site, Rack, Device, Type, Name).  The logic would be:

* If you type into the Device search when Site has not been selected, then you search globally across all devices
* If you type into the Device search when Site has been selected but Rack has not, then you search across all devices within this site

It may also make sense to have a sixth field for Tenant, given that the same name may be reused by different tenants.

### Database Changes

None

### External Dependencies

None

**Comment by jeremystretch** [comment]
Superseded by #3310 for NetBox v2.6
