### ISSUE TITLE
Allow arbitrary rack selection in Rack Elevation view

### ISSUE THREAD

**Issue by BlessJah** [netbox-community/netbox#3187]
### Environment
* NetBox version:  2.5.11

### Proposed Functionality

Allow selection of arbitrary racks in Rack Elevations view.

### Use Case

It is not always possible to limit racks shown in Rack Elevations using existing filters. Physical DC layout might be misaligned with groups/tenants/roles, or racks are shared.

Following feature and MR would allow operator to select arbitrary racks for Rack Elevation and other view where `RackFilterForm` is used.

### Database Changes

None.

### External Dependencies

None.

**Comment by jeremystretch** [comment]
What is the specific implementation being proposed?

**Comment by BlessJah** [comment]
I propose adding multiple choice field to rack search form.

Current set of fields does not include multiple choice of racks. Search field provides "fuzzy" search as opposed to arbitrary selection, thus new field  is complementary to existing fields.

![select_rack](https://user-images.githubusercontent.com/835808/58588840-e01d5200-8260-11e9-991d-7f49beb8c7d1.png)

**Comment by cpmills1975** [comment]
If racks can be displayed in the order they are added, that would be useful. Looking towards the front of some of my racks, they are numbered 100, 99, 98 in that order - the front faces in to the cold aisle and the numbering goes up the hall so racks on the left of the cold aisle are numbered 98, 99, 100, but on the right the order appears right to left.

**Comment by jeremystretch** [comment]
Related to #1755
