### ISSUE TITLE
Swagger doesn't show required field "prefix_length" in available-prefixes POST request

### ISSUE THREAD

**Issue by KhaledTo** [netbox-community/netbox#3240]
### Change Type
[X ] Addition
[ ] Correction
[ ] Deprecation
[ ] Cleanup (formatting, typos, etc.)

### Environment
NetBox version: 2.5.13

### Proposed Change

Add `prefix_length` field in Swagger docs, something like:

prefix_length* integer
title: Prefix length
Size of this prefix 

In /ipam/prefixes/{id}/available-prefixes/ POST request

![prefixes](https://user-images.githubusercontent.com/20525775/58911018-397cf980-8717-11e9-9964-d82a805f0778.png)

**Comment by jeremystretch** [comment]
Marking this as blocked by #2769

**Comment by chbndrhnns** [comment]
The blocker seems to be resolved. I also faced that issue today.

**Comment by thadc23** [comment]
Same here.  Using swagger codegen to create the client forces me to try to provide an entire WritablePrefix object as opposed to an object with a single field `prefix_length`. It may just be a matter of creating a new object with a single field to be used as the data to the POST.

**Comment by jeremystretch** [comment]
@chbndrhnns @thadc23 If you're willing to commit to working on this I'm happy to assign you the issue.

**Comment by jeremystretch** [comment]
Reclassified this as a bug since the fix will involve manipulating code.
