### ISSUE TITLE
Incorrect order of interfaces that start with numbers

### ISSUE THREAD

**Issue by zelfix** [netbox-community/netbox#3242]
### Environment
* Python version:  3.6.7
* NetBox version:  2.5.13

Huawei CE switches can have interface names start with numbers, for example: 10GE1/0/1 or 40GE1/0/5. Such names have incorrect order in the list of interfaces.

### Steps to Reproduce
1. Add interfaces with names 10GE1/0/[1-48] to device

### Expected Behavior
list of interfaces with ascending order

### Observed Behavior
Natural ordering doesn't work correctly
![image](https://user-images.githubusercontent.com/10135380/58948390-b26d6700-8792-11e9-9dd3-485c31b8cc77.png)

**Comment by jeremystretch** [comment]
NetBox employs [custom logic](https://github.com/digitalocean/netbox/blob/develop/netbox/dcim/managers.py#L27) to naturally order interfaces as best we can. Unfortunately, it is not feasible to accommodate every naming scheme.

I'm going to close this as non-actionable. However, if you'd like to propose a specific modification to the existing logic that will address your use case without impacting any of [the existing test cases](https://github.com/digitalocean/netbox/blob/develop/netbox/dcim/tests/test_natural_ordering.py#L6), I'm happy to re-open it.
