### ISSUE TITLE
Health Check

### ISSUE THREAD

**Issue by szechyjs** [netbox-community/netbox#3291]
### Proposed Functionality

Add a health check endpoint.

### Use Case

Having a health check endpoint helps with load balancers and monitoring services.

### Database Changes

N/A

### External Dependencies
Several out of the box options:
- https://github.com/KristianOellegaard/django-health-check
- https://github.com/mwarkentin/django-watchman

**Comment by jeremystretch** [comment]
Monitoring is out of scope for NetBox. Please see [the documentation](https://netbox.readthedocs.io/en/stable/#what-netbox-is-not).

**Comment by szechyjs** [comment]
I think you misunderstood the point of this. This is not to monitor other network assets, this is to have an endpoint within netbox itself that is able to report the health of **itself**. In other words, is netbox healthy and operational?

**Comment by jeremystretch** [comment]
IMO the functionality proposed does not meet the bar for introducing a new dependency (`django-watchman`).

**Comment by lampwins** [comment]
This is why we implemented Prometheus metrics. You don't have to use a Prometheus server to use the exposed metrics as a health page.

**Comment by jeremystretch** [comment]
I don't think this belongs in core. Maybe a good candidate for a plugin in a future release.
