### ISSUE TITLE
API filtering 'OR' logic not working when filtering components by device ID

### ISSUE THREAD

**Issue by ajknv** [netbox-community/netbox#3293]
### Environment
* Python version:  3.6.8
* NetBox version:  2.6.0

### Steps to Reproduce
1. Issue an API query with filter parameters specifying two different related object IDs, for example:
https://netbox/api/dcim/interfaces/?device_id=2761&device_id=2762

### Expected Behavior
API will return interfaces associated with the devices having ids 2761 and 2762.

### Observed Behavior
API returned only the interfaces associated with the last given device id, in this case 2762.

**Comment by jeremystretch** [comment]
FYI this is because we're employing a method-based filter to also match on devices belonging to the same virtual chassis, so it's not covered by the default `MultiValue*` filters.
