### ISSUE TITLE
Introduce a mechanism for storing individual user preferences

### ISSUE THREAD

**Issue by jeremystretch** [netbox-community/netbox#3294]
### Environment
* Python version: 3.6.8
* NetBox version: 2.6.0

### Proposed Functionality
Introduce a model for storing the preferences of an individual user. A simple model providing arbitrary JSON data storage associated one-to-one with user accounts is probably sufficient. This will allow a user to set a preferred item (e.g. the default status for new prefixes) that will persist indefinitely.

### Use Case
This has been highlighted as a requirement for several other features:

* #492 - Customized table column ordering
* #1426 - Customized default statuses

### Database Changes
Introduce a new model under the `users` app, e.g. `UserPreferences`.

### External Dependencies
None

**Comment by tb-killa** [comment]
Maybe this could help? https://pypi.org/project/django-jsonstore/
