### ISSUE TITLE
GET request for interfaces with device and mac as parameters returns nothing

### ISSUE THREAD

**Issue by Mellow420** [netbox-community/netbox#3300]
### Environment
* Python version: 3.6 
* NetBox version:  2.6

### Steps to Reproduce
1. Create a device and assign a interface
2. Request the created interface from the API by doing a GET interfaces with device and mac as parameters.
`http://0.0.0.0:32776/api/dcim/interfaces/?device=example_devicet&mac_address=00%3A56%3A50%3A6d%3A2d%3A5a

### Expected Behavior
Return the object that was created at the start of this test.

### Observed Behavior
The API returns an empty response
After a while it does return the correct object so this might have something to do with the new caching?

**Comment by Mellow420** [comment]
After some testing i found out that this problem is likely caused by the new caching system.
With caching disabled the API functions as expected.

**Comment by jeremystretch** [comment]
Please indicate your Python version as required by the template.

**Comment by Mellow420** [comment]
> Please indicate your Python version as required by the template.

Sorry, fixed it

**Comment by jeremystretch** [comment]
Rolling this into #3428
