### ISSUE TITLE
Power Feed Cable bulk edit gives failed validation

### ISSUE THREAD

**Issue by wols** [netbox-community/netbox#3312]
### Environment
* Python version:  3.6.5
* NetBox version:  2.6.1

### Steps to Reproduce
1. Use Menu: Device > Cables
2. Search and Select one or more Power Feed Cable
3. [Edit selected]
2. Change any data

### Observed Behavior
`FUSE1 failed validation: {'termination_b_type': ['content type instance with id 75 does not exist.']} `

The cable detail view shows `termination_a` on `Device` but `termination_b` on `Provider`.
Is here the "Power Provider" planned/missing?

**Comment by jeremystretch** [comment]
I'm not able to replicate this on v2.6.1. The error suggests a problem with your installation: You have a record referring to an invalid ContentType ID.

**Comment by wols** [comment]
My update seemed to go through error free.
I will set up a fresh installation again and get in touch shortly.

**Comment by wols** [comment]
New installation, empty database - same error:
A cable between a `Device Power Port` and a `Power Feed` has no `Termination B` (the Power Feed) and is not editable.

#  Device
![netbox-2 6 1_device](https://user-images.githubusercontent.com/764167/60581411-1467bf00-9d87-11e9-9604-fb06180ef5ee.png)
# Feed
![netbox-2 6 1_feed](https://user-images.githubusercontent.com/764167/60581431-1c276380-9d87-11e9-8a3e-c25231513051.png)
# Cables
![netbox-2 6 1_cables](https://user-images.githubusercontent.com/764167/60581511-42e59a00-9d87-11e9-970d-141b92ab5528.png)
# Cable
![netbox-2 6 1_cable](https://user-images.githubusercontent.com/764167/60581535-4da02f00-9d87-11e9-8cae-ebe977122c7f.png)
# Trace
![netbox-2 6 1_trace](https://user-images.githubusercontent.com/764167/60581553-57c22d80-9d87-11e9-887b-b0b140c24dcd.png)

**Comment by DanSheps** [comment]
I am unable to replicate this.

Please provide **step-by-step** instructions for replicating this issue, starting from initial device/power feed creation and going all the way through to produce the error.

**Comment by wols** [comment]
Now, my private test system - fresh install today:
- Oracle Linux 7
- `postgresql11-11.4-1PGDG.rhel7.x86_64`
- Python 3.6.8
- NetBox v2.6.2-dev develop 3da9af5
- superuser `netbox`

Step-by-step as comments...

**Comment by wols** [comment]
Minimal preparations
- Region 1
  - Site 01
    - Group 001
      - Rack 0001

![01_Rack](https://user-images.githubusercontent.com/764167/61086946-7e8dfd00-a434-11e9-8eec-97b589e6e5bb.png)

**Comment by wols** [comment]
A device with one power port

![02_Device](https://user-images.githubusercontent.com/764167/61087000-a4b39d00-a434-11e9-81ea-42ca75ab2ff8.png)

**Comment by wols** [comment]
A power outlet `USV1` with one power port `Fuse 1` and four outlets `Power [1-4]`

![03_PowerOutlet](https://user-images.githubusercontent.com/764167/61087074-d62c6880-a434-11e9-8b86-f1738d3b902c.png)

**Comment by wols** [comment]
Power Panel / 01 / 001 / USV

![04_PowerPanel](https://user-images.githubusercontent.com/764167/61087273-771b2380-a435-11e9-9de2-d3021db058b4.png)

**Comment by wols** [comment]
Power Panel `USV` details from changelog

![05_PowerPanel_changelog](https://user-images.githubusercontent.com/764167/61087309-90bc6b00-a435-11e9-9767-45c57f5513bc.png)

**Comment by wols** [comment]
The Power Feed / 01 / USV / 0001 / Fuse 1

![06_PowerFeed](https://user-images.githubusercontent.com/764167/61087378-bf3a4600-a435-11e9-9be7-a7c7e6493c1d.png)

**Comment by wols** [comment]
Power Feed `Fuse 1` object data from changelog

![07_PowerFeed_changelog](https://user-images.githubusercontent.com/764167/61087430-ee50b780-a435-11e9-92ad-804df17a12d3.png)

**Comment by wols** [comment]
Connect power outlet `USV1` Power Port `Fuse 1` to Power Feed `Fuse 1`.
Create Power Cable `FUSE1`

![08_PowerPort_connect](https://user-images.githubusercontent.com/764167/61087592-57d0c600-a436-11e9-8651-a3f4ca1b918c.png)

**Comment by wols** [comment]
Connected! Power Utilization Available.

![09_PowerOutlet_connected](https://user-images.githubusercontent.com/764167/61087677-98304400-a436-11e9-8e9d-50cf38204deb.png)

**Comment by wols** [comment]
See Cable (ID 1) in list

![10_Cables](https://user-images.githubusercontent.com/764167/61087731-c6158880-a436-11e9-87c8-bcedf9bc50c9.png)

**Comment by wols** [comment]
The Main Changelog:

![11_MainChangelog](https://user-images.githubusercontent.com/764167/61087763-dd547600-a436-11e9-8411-99d4a52a5528.png)

**Comment by wols** [comment]
Power Feed `Fuse 1` connected now

![12_PowerFeed](https://user-images.githubusercontent.com/764167/61087814-ff4df880-a436-11e9-88be-6a4b8aee90b3.png)

**Comment by wols** [comment]
Power Feed `Fuse 1` changelog - two updates with identical Request ID

![13_PowerFeed_changelog](https://user-images.githubusercontent.com/764167/61087845-17257c80-a437-11e9-8706-c7b85337dc23.png)

**Comment by wols** [comment]
`changelog/36`

![14_PowerFeed_changelog_36](https://user-images.githubusercontent.com/764167/61088024-8a2ef300-a437-11e9-8d01-2bc80cec420e.png)

`changelog/38`

![15_PowerFeed_changelog_38](https://user-images.githubusercontent.com/764167/61088042-94e98800-a437-11e9-8040-e681f8942293.png)

**Comment by wols** [comment]
Cable `FUSE1` - see **Termination B**

![16_Cable_FUSE1](https://user-images.githubusercontent.com/764167/61088088-b8acce00-a437-11e9-9d45-94bc4e56b1f6.png)

**Comment by wols** [comment]
Cable `FUSE1` changelog

![17_Cable_FUSE1_changelog](https://user-images.githubusercontent.com/764167/61088119-d4b06f80-a437-11e9-825e-aa8a459acddd.png)

### Note and notice **`termination_b_type: 44`**

![18_Cable_FUSE1_changelog_39](https://user-images.githubusercontent.com/764167/61088207-16d9b100-a438-11e9-99c8-8f2ed7506411.png)

**Comment by wols** [comment]
Try to edit Cable `FUSE1`...

![19_Cables_select_1](https://user-images.githubusercontent.com/764167/61088311-628c5a80-a438-11e9-8a1e-45b90893bd64.png)

...change color `black`

![20_Cables_edit_1](https://user-images.githubusercontent.com/764167/61088350-7b950b80-a438-11e9-97d5-90010c394009.png)

**Comment by wols** [comment]
`FUSE1 failed validation` witch id **`44`**

![21_Cables_failed_1](https://user-images.githubusercontent.com/764167/61088510-c9117880-a438-11e9-8785-adcbf8fc8184.png)

**Comment by wols** [comment]
Cable trace "Far End" missing (the Power Feed `Fuse 1`)

![22_Cable_trace_1](https://user-images.githubusercontent.com/764167/61088591-0249e880-a439-11e9-813e-6da358a21475.png)

### ...last step here.

**Comment by jeremystretch** [comment]
Closing this out as no one has been able to replicate the reported behavior.

**Comment by jeremystretch** [comment]
Ended up running into this on v2.6.7. Not sure why it wasn't occurring earlier, but I'll re-open this to resolve it.
