### ISSUE TITLE
Increase max length of platform name field

### ISSUE THREAD

**Issue by CaptAintHere** [netbox-community/netbox#3318]
### Environment
* Python version:   3.6.8
* NetBox version:   2.6.0

### Proposed Functionality
Increase the platform name field to more than 65 characters. Optionally, increase the platform slug field accordingly.

### Use Case
We would like to set the platform name of our Windows machines like we did with our Linux ones. Currently, we are using Ansible to gather facts about our hosts and then format a platform name by concatenating `ansible_distribution`, `ansible_distribution_version` and `ansible_architecture` variables.

Examples:
- CentOS 7.5.1804 (x86_64)
- Ubuntu 18.04 (x86_64)
- Microsoft Windows Server 2012 R2 Standard 6.3.9600.0 (64-bit)
- Microsoft Windows Server 2016 Standard 10.0.14393.0 (64-bit)

### Database Changes
Increase max_length of platform name field and platform slug field to more than 65 chars.

### External Dependencies
No dependency.

**Comment by DanSheps** [comment]
Is there any reason why 65 characters was chosen?  The longest microsoft one is only 61 characters.  We currently have a length of 64 characters for a few model name fields in dcim already.

**Comment by CaptAintHere** [comment]
No I gave it as an example. Any higher value than 62 characters (the longest one is Windows Server 2012 R2) will be enough.
