### ISSUE TITLE
Show reservation descriptions in rack model

### ISSUE THREAD

**Issue by swerveshot** [netbox-community/netbox#3320]
### Environment
* NetBox version: 2.6.1

### Proposed Functionality
Have reservation descriptions show in the rack model

### Use Case
When using the DCIM feature I found that rack reservations are a great way to get some temporary registration of what is installed in a rack. At least before you are able to properly model the device types you eventually want to use.

However if you use rack reservations the rack model just shows the rack units as occupied. In my opinion it would be much nicer if it would show the description from the reservation as well.

#### Mockup of desired functionality
![image](https://user-images.githubusercontent.com/10358044/60553359-418a8200-9d33-11e9-895f-9f2b1baec98e.png)

**Comment by jeremystretch** [comment]
Reservation descriptions are displayed when you hover the mouse over a reserved unit. We won't be making any modifications to the elevation diagrams until #2248 has been implemented.
