### ISSUE TITLE
Doc incorrectly states child devices shown as non-racked

### ISSUE THREAD

**Issue by lassebm** [netbox-community/netbox#3324]
### Change Type
[ ] Addition
[x] Correction
[ ] Deprecation
[ ] Cleanup (formatting, typos, etc.)

### Proposed Changes
The section Core Functionality → Devices → Device Bays incorrectly states that child devices are shown as non-racked. This behavior was changed in aa6c840c457f62ff1761cee2dd1610cd98bd999d. Let me know if I should submit PR.

**Comment by DanSheps** [comment]
You can go ahead and submit a PR
