### ISSUE TITLE
Open page immediately when typing exact devicename, ip address, site,...

### ISSUE THREAD

**Issue by 33Fraise33** [netbox-community/netbox#3328]
### Proposed Functionality
It would be nice when you type the exact name of some items to open the page directly or have it suggested under the search field while typing so you jump immediately to the page of the item. 

recommended items: 
- Sites
- Tenants
- Device
- VM
- IP
- Rack
- ...

### Use Case
The use case for this would be to win time navigating through the netbox interface. Lot's of times I know the exact name of the device but I have to open netbox, open the search field, type in the name, click enter, click the device. 

### Database Changes
Not sure about this one, this will need correct indexes but as the search functionality is already working as expected I think this should not be an issue. 

### External Dependencies
Unsure about this one as well.

**Comment by jeremystretch** [comment]
NetBox used to do this, but it was decided that this can lead to unexpected behavior regarding missing devices, etc., so the current behavior was adopted.
