### ISSUE TITLE
URL to local storage

### ISSUE THREAD

**Issue by lmgonzalezl** [netbox-community/netbox#3331]
### Proposed Changes
**URL to internal storage.**

In our organization we store photos and documents related to a tenant. I have tried adding a personal label to internal storage but NetBox does not recognize the string as a valid URL.

Example of the required url:
storage1\systems_redes\Location of Nodes

Even if I use the url storage1\sistemas_redes\ without spaces netbox does not recognize it.

I have tried with file: //storage1/systems_redes/ but it does not work either.

Is it possible for NetBox to open a file browser from a supplied URL?

### Justification
Link documents to a tenant on an internal storage server.

Thank you

**Comment by jeremystretch** [comment]
> I have tried adding a personal label

What are you referring to? A custom link? NetBox simply outputs the specified URL inside an HTML tag, like this:

```
<a href="{{ URL }}">{{ TEXT }}</a>
```

How the browser handles that is outside of NetBox's control.

**Comment by lmgonzalezl** [comment]
Hi Jeremy.

What I would like to do is that the link make reference to a directory in a local server in our network, because i need to open a file browser that contains a photo gallery.

**Comment by tyler-8** [comment]
@lmgonzalezl You need three slashes when doing file URLs: `<a href="file:///C:\Videos\lecture.mp4">Link 2</a>`

More info:
https://stackoverflow.com/a/18246357/6412005

**Comment by lmgonzalezl** [comment]
What I need is legacy URLs.

[https://en.wikipedia.org/wiki/File_URI_scheme](url)

Example of my URL: file:////storage1/sistemas_redes/LogoAPTF.jpg

When I save the changes Netbox removes the ip from the server.

**Comment by candlerb** [comment]
You should be able to generate `file:///` URLs from custom links - Netbox just outputs whatever URL you generate, and you provide the scheme part in your template.

This sounds like a support question for the [google group](https://groups.google.com/forum/#!forum/netbox-discuss), where you can show what strings you've given for "Text" and "URL" for your custom ilnk.

**Comment by jeremystretch** [comment]
As @candlerb points out, NetBox lets you output whatever you want for the URL. How your web bowser handles that is beyond what NetBox can control.
