### ISSUE TITLE
Ability to disconnect cable without deleting it

### ISSUE THREAD

**Issue by TeroPihlaja** [netbox-community/netbox#3332]
### Proposed Functionality
Ability to disconnect cables without removing cable details (label, length, color, type etc.) from Netbox.

This would be useful when reusing cables that have a global label (for example Patchbox cables:
https://patchbox.com/patchbox-plus )

Open question:
Should disconnecting cable disconnect only one end or both?

**Comment by jeremystretch** [comment]
NetBox is intended to track only installed cables; that is, cables with both ends connected.
