### ISSUE TITLE
Add leg field on single phase feed

### ISSUE THREAD

**Issue by vink78** [netbox-community/netbox#3335]
### Environment
* Python version:  3.5.2-2ubuntu0~16.04.5
* NetBox version:  2.6.1

### Proposed Functionality

I would like to indicate which leg is used (A, B or C) when single phase power feed is used on a rack. 

### Use Case

My power feed can deliver three-phase to a rack (for high density rack), or, only a single-phase  (low density rack).

I would like to keep information of which leg is used on which rack to optimize leg utilization on a single site.

**Comment by jeremystretch** [comment]
Leg assignment is tracked within a PDU: You can connect a PDU to a three-phase power feed to a PDU and assign individual outlets to one of the three legs (A, B, or C). If the feed itself is a single leg of an upstream three-phase supply, that falls beyond the scope of power modeling in NetBox.
