### ISSUE TITLE
Return site in circuit-list API

### ISSUE THREAD

**Issue by tyler-8** [netbox-community/netbox#3338]
### Environment
* Python version:  3.6.8
* NetBox version:  2.5.13

### Proposed Functionality
Add `a_site` and `z_site` keys to output of `/circuits/circuits`

### Use Case
In the GUI when viewing the circuit listing, the table has a column that shows the site names for each termination (if it exists). This is extremely useful for filtering by site and generally viewing the circuit list.  The API for circuits does not return this matched data however. In order to get the site, you also have to call `/circuits/circuit-terminations/` as well, then pair the data up. This is a slow workflow within a script, and even more-so when trying to represent the data in an external tool.

The circuit API does allow you to filter by sites so it would also make it more manageable to know which circuit belongs to which site if you're filtering on multiple sites, without having to do even more API calls.

### Database Changes
N/A

### External Dependencies
N/A

**Comment by jeremystretch** [comment]
If we're going to go that route, it would probably make more sense to return the whole termination rather than just the assigned site.

**Comment by tyler-8** [comment]
Fair point - I'd considered that but opted for the 'lighter' output. Having the terminations would definitely have value as well.
