### ISSUE TITLE
Connect on patchpanel is not possible to Console (Server) Ports

### ISSUE THREAD

**Issue by dxks** [netbox-community/netbox#3340]
### Environment
* Python version:  3.6.8
* NetBox version:  2.6.1

### Steps to Reproduce
1. Create a Patchpanel with Frontports
2. Click on connect icon and you can only select Interface, Front/Rear Port, Circuit Termination

### Expected Behavior
Connection to/from Console-Porst can also be initiated starting with the patchpanel as RJ45 is a normal style of console-ports and cross-rack connections are always possible. 

### Observed Behavior
Connections can only be initiated from the console-server or the device itself. Doing a documentation step-by-step (hopping from device to console server) is not possible at all.

Connection on patchpanel:
![connecti-selection-panel](https://user-images.githubusercontent.com/44632742/60949863-5bf5ca00-a2f6-11e9-92cd-c620689df774.PNG)

Connection on Console-Server:
![connecti-selection-conserver](https://user-images.githubusercontent.com/44632742/60949862-5b5d3380-a2f6-11e9-995d-7eb478d2685e.PNG)

**Comment by DanSheps** [comment]
Looks like it may have been something missed.  Will look into it and get back to you.

**Comment by kobayashi** [comment]
Taking a look at templates, This needs to add a line at line 65-71 in /netbox/netbox/templates/dcim/inc/frontport.html .
```
<li><a href="{% url 'dcim:frontport_connect' termination_a_id=frontport.pk termination_b_type='console-port' %}?return_url={{ device.get_absolute_url }}">Console Port</a></li>
```
