### ISSUE TITLE
PowerDNS Integration as an app that can be enabled disabled.

### ISSUE THREAD

**Issue by kvedder-amplex** [netbox-community/netbox#3344]
### Environment
* Python version:  3.6
* NetBox version:  2.6.0

### Proposed Functionality
 I work for a small ISP and we are currently in the process of deploying Netbox as our IPAM. We are exploring options for integrating PowerDNS into the ecosystem to be fed by Netbox's data. 

I was considering having the team here write a Django app within Netbox that perhaps could be enabled and disabled that would store information about the PowerDNS server's it would communicate with. As changes are made in the IPAM, it could update the database on the DNS servers as needed. 

Another option would be to build a separate service that would translate the webhooks into the proper API query to PowerDNS. It could be installed on the IPAM server, but be entirely separate from Netbox.

Its worth noting that we haven't fully flushed out any design yet. I wanted to hear from the community and project leaders as to weather or not this is something that would be acceptable or if it deviated too much from the core functions of the IPAM.

### Use Case
One potential use case:    
A device is added into Netbox, once added an API call is made to the configured PowerDNS server(s) adding the necessary records.

### Database Changes
A new model and template/view would be needed to enable, disable, and configure the integration. Perhaps the webhooks model could be extended to enable some of this functionality.

### External Dependencies
I don't envision there being any new dependencies.

**Comment by lampwins** [comment]
This is the intended use case for webhooks. Adding this sort of thing to the core of NetBox only serves to create bloat, which in turn creates maintenance overhead for a feature on a subset of the userbase cares about.

**Comment by kvedder-amplex** [comment]
Thanks for the feedback. Looks like we should build the functionality into a separate tool that will translate the webhooks from Netbox into the appropriate calls to the PowerDNS API. Perhaps once complete the code could be added to netbox-community as a separate repository.
