### ISSUE TITLE
Upgrade pathway 2.4 -> 2.6

### ISSUE THREAD

**Issue by trinkleinj** [netbox-community/netbox#3348]
### Environment
* NetBox version:  2.4.4
* Ubuntu 16.04

### Steps to Reproduce
1. Running Netbox 2.4.4
2. Used upgrade guide from Netbox documentation to move to Netbox 2.6.1
3. Upgrade fails on upgrade.sh due to missing "REDIS" section in configuration.py

### Expected Behavior
Expected successful upgrade.

### Observed Behavior
Errors regarding new REDIS service for Netbox. Rolled back upgrade using backup VM snapshot to return environment to working order.

What is the correct upgrade procedure from v2.4.4 to v2.6.1?

**Comment by DanSheps** [comment]
GitHub issues is for bugs/feature requests.

Please use the mailing list for general help and troubleshooting
