### ISSUE TITLE
Device search limited to non-racked devices when creating a new connection

### ISSUE THREAD

**Issue by shugotek** [netbox-community/netbox#3349]
### Environment
* Python version:  3.6.7
* NetBox version:  2.6.1

### Steps to Reproduce
(Same problem that 3044 (https://github.com/netbox-community/netbox/issues/3044)
1.Go on device
2.Select "Connect" on one interface
3.Search a device directly without specify a rack

### Expected Behavior
List all device, and can filter if we write anything

### Observed Behavior
List only non-racked device and finally we lost time

**Comment by candlerb** [comment]
You have to select from the Site and Rack dropdowns first.

I agree that the default behaviour (of allowing you to see unracked devices only) is not helpful.

I proposed a change of behaviour in #3310.

It might also be helpful, if no site/rack is selected, to allow searching across all device - but beware that in future, it has been proposed that device names will only be unique within a site.

**Comment by jeremystretch** [comment]
> List all device, and can filter if we write anything

This is what happens on v2.6.4. Not sure when/if the behavior changed.
