### ISSUE TITLE
Demo Website

### ISSUE THREAD

**Issue by sasschary** [netbox-community/netbox#3355]
Hi,

I just was wondering about any progress on a demo website. Did anything ever come out of looking for someone to provide a dataset on the Google group? If not, I would be happy to create some sample data, as long as somewhere to host it is provided as I cannot actually host the server myself.

Zach

**Comment by jeremystretch** [comment]
Thank you for your interest in NetBox. GitHub issues are intended for reporting reproducible bugs and requesting features, and must be submitted using one of the templates provided [here](https://github.com/digitalocean/netbox/issues/new/choose). For general discussion, questions, or assistance with installation issues, please post to our [mailing list](https://groups.google.com/forum/#!forum/netbox-discuss) instead.
