### ISSUE TITLE
Available IP OpenAPI schema incorrect

### ISSUE THREAD

**Issue by Marlinc** [netbox-community/netbox#3356]
### Environment
* Python version:  3.6.7
* NetBox version:  2.6.1

### Steps to Reproduce
1. Go to `/api/docs/`, scroll to `/api/ipam/prefixes/{id}/available-ips/` and see the response being defined as a prefix model instead of a list of IP addresses

### Expected Behavior

I expected the right documentation to be set in the OpenAPI schema so that my generated API client would work. Now it gives errors because it expects a prefix but is getting a list of IPs instead.

The same also applies to the POST call.

### Observed Behavior

I'd expect the OpenAPI schema to be as follows:
```
[
  {
    "family": 6,
    "address": "some-ip/64",
    "vrf": null
  },
  {
    "family": 6,
    "address": "some-ip/64",
    "vrf": null
  }
]
```

Which is what NetBox is actually returning.

**Comment by jeremystretch** [comment]
Related to #2769
