### ISSUE TITLE
Feature Request: Webhook On Selectable Fields

### ISSUE THREAD

**Issue by jvanderaa** [netbox-community/netbox#3360]
### Environment
* Python version:   3.6.3
* NetBox version:   2.5.8

### Proposed Functionality

Looking to select which fields that are modified to trigger a webhook instead of any device update. Extend to the custom fields selection as well.

### Use Case

We are currently using a custom_field of `Monitored` to give a source of truth of whether or not a device is monitored. Some clients choose not to have monitoring enabled. Thus the need to monitor some and not others.

We would like to trigger a process using just standard webhook to kick off jobs when the custom field and possibly other attributes that could be selected get updated. 

### Database Changes

Unsure

**Comment by jeremystretch** [comment]
Webhooks are implemented so that one is sent in response to _any_ change in an associated object. It is left to the receiver to decide whether they should act on the information being sent.
