### ISSUE TITLE
Enable ability to skin the title of a model for greater customization

### ISSUE THREAD

**Issue by Xelinor** [netbox-community/netbox#3362]
### Proposed Functionality
Allow re-naming (skinning) of the models in Netbox from the Admin console so that they display under different names on the web front end

### Use Case
'Tenants' is an overloaded term in my company. In my production environment, I go into the HTML template and essentially skin it so that it shows up as 'Environments' instead. It's still tenants in the back-end, just the front end appears to show differently to users because to them, a 'Tenant' is an entirely different thing in our business, and it was extremely confusing for our users.

I believe this functionality could be baked into the admin page to allow skinning for several of the models. Someone might want to change 'Sites' to 'Campus' or 'Floor', for example, or regions to 'Building'. The purpose is for better clarity of terms.

There are plenty of use cases where various organizational types are re-purposed by users, giving the admins the ability to change that in the UI would save a lot of time.

### Database Changes
A table would need to be added that would give the 1 to 1 correlation between the real name and the fake name so that the django template could call it correctly on render...other then that, no changes needed.

### External Dependencies
None. This can be done with Django templating.

**Comment by jeremystretch** [comment]
This is not something that can be undertaken without an unreasonable amount of developer effort, and ultimately would only lead to confusion.

**Comment by Xelinor** [comment]
> This is not something that can be undertaken without an unreasonable amount of developer effort

Maybe I'm confused about this, but at least how I imagined this being accomplished, this should be as simple as adding a django template tag with a very simple text replacement function to the navigation menus and table headers, a very very small and repeatable change...is there a gotcha I'm not aware of somewhere? I do basically do this already in my own Netbox, just hard-coding the replacement template tag rather then making it part of the admin page...

(To be clear, not arguing about the decision, it was just something I figured might add value but it definitely could add confusion, just wondering if I'm missing something now that might bite me later?)
