### ISSUE TITLE
Cache not invalidated when interface name changed

### ISSUE THREAD

**Issue by candlerb** [netbox-community/netbox#3363]
### Environment
* Python version:  3.5.2
* NetBox version:  2.6.10

### Steps to Reproduce
1. Create switch A and switch B
2. Connect one or more interfaces on switch A to switch B
3. View switch A, and look at the list of interfaces which show connections to B
4. Click on one of the switch B interfaces, go to edit, change its name, save
5. View switch A again

### Expected Behavior

The list of connected interfaces on A would show the new name of the interface on B

### Observed Behavior

The list of connected interfaces on A still shows the old name of the interface on B

**Comment by a31amit** [comment]
Not sure if these two are related - https://github.com/netbox-community/netbox/issues/3366

**Comment by jeremystretch** [comment]
Rolled into #3428
