### ISSUE TITLE
Can't import Cables (resubmission)

### ISSUE THREAD

**Issue by StevenRB** [netbox-community/netbox#3365]
### Environment
* Python version:  3.5.3 
* NetBox version:  2.6.1

### Steps to Reproduce
1. Select import cables
2. input data. All interfaces exist on the mentioned devices. example data below:
```
side_a_type,side_b_type,side_a_device,side_b_device,side_a_name,side_b_name
Interface,Interface,GJCORE01,GJSW08,GigabitEthernet2/18,GigabitEthernet0/1
Interface,Interface,GJCORE01,GJSW09,GigabitEthernet2/19,GigabitEthernet0/1
Interface,Interface,GJCORE01,GJSW06,GigabitEthernet2/23,GigabitEthernet0/2
Interface,Interface,GJCORE01,GJSW24,GigabitEthernet3/4,GigabitEthernet0/2
Interface,Interface,GJCORE01,GJSW07,GigabitEthernet2/17,GigabitEthernet0/1
```
3. Click submit

### Expected Behavior
Cables created linking the stated interfaces/devices

### Observed Behavior
Netbox returned an error:
```Request Method: | POST
-- | --
https://netbox.xxxx.com/dcim/cables/import/
2.1.4
RelatedObjectDoesNotExist
Cable has no termination_a_type.
/home/service.net.scripts@xxxx.com/.local/lib/python3.5/site-packages/django/db/models/fields/related_descriptors.py  in __get__, line 188
/usr/bin/python3
3.5.3
['/opt/netbox/netbox',  '/opt/netbox-2.6.1/netbox',  '/usr/local/bin',  '/usr/lib/python35.zip',  '/usr/lib/python3.5',  '/usr/lib/python3.5/plat-x86_64-linux-gnu',  '/usr/lib/python3.5/lib-dynload',  '/home/service.net.scripts@corpit.startek.com/.local/lib/python3.5/site-packages',  '/usr/local/lib/python3.5/dist-packages',  '/usr/lib/python3/dist-packages']
Mon, 22 Jul 2019 17:55:36 +0000
```

This happened under 2.5.1 as well but, taking the advice given in #2801 I upgraded. The issue has persisted

**Comment by jeremystretch** [comment]
`Interface` is not a valid type: use `interface` (with a lowercase `i`).

**Comment by StevenRB** [comment]
Thank you. I had tried that but it turned out I had a misspelling in one of the interface names. Maybe a minor feature request for cable import to tell you which line of the import was causing the trouble instead of throwing the exception?
