### ISSUE TITLE
device search by macaddress broken

### ISSUE THREAD

**Issue by a31amit** [netbox-community/netbox#3366]
### Environment
* Python version:  3.7
* NetBox version:  2.6.1 or develop 

it looks to be an issue with netbox caching or search by mac address. I tried with Redis caching to 0, it is still broken. 
for some reasons it's working for old existing devices in the database but whenever I create a new device or new interface, its broken. I tried with Redis flush but its same, doubt if logic in netbox core may need to check. 

### Steps to Reproduce
1. Create a New Interface with its valid mac address
2. Search Mac Address in Search Box of netbox

### Expected Behavior
netbox should return the device in search.

### Observed Behavior
It doesn't return anything. Also, it seems the same for API as well.

**Comment by jeremystretch** [comment]
Please indicate the exact values you are using to produce this issue.

**Comment by a31amit** [comment]
1. Click on Add New Interface with Name eth1 or with some other name which doesn't exist for the same device. 
2. Update a valid Mac Address for example - b0:35:9f:8a:2d:e8 
3. Save
4. Search a Mac Address in global Search

Result - Nothing Returns. 

For old devices and their interfaces with mac address which exist before migration to 2.6.0 or everything which was in netbox 2.5.13 still searchable

**Comment by jeremystretch** [comment]
See, this:

> Search a Mac Address in global Search

is different from your original post:

> Search Mac Address in Search Box of netbox

Global search doesn't match on MAC addresses. The `mac_address` filter does this and works as expected.
