### ISSUE TITLE
BNC port and Coax cable types

### ISSUE THREAD

**Issue by ragzilla** [netbox-community/netbox#3367]
### Environment
* Python version:  3.6.8
* NetBox version: 2.6.1

### Proposed Functionality
Patch panels and cables should support at a minimum BNC/Coaxial cables to document cross connecting T3/E3 interfaces.  Currently you can create a Serial interface on a Device with an interface type of T3/E3 but there are no suitable front/rear port types to connect it to on a panel.

### Use Case
Documentation of T3/E3 interconnects within a datacenter, or to external T3/E3 circuits.

### Database Changes
No DB changes needed, just new enums in PORT_TYPE_CHOICES and CABLE_TYPE_CHOICES

### External Dependencies
None

**Comment by ragzilla** [comment]
Proposed changes ready for pull in commit https://github.com/ragzilla/netbox/commit/99fc8f469b40b8be53dce76422d9db64f0b0c1a1#diff-586a99dcc48544d0f3261dfe26d69972

**Comment by jeremystretch** [comment]
Looks good to submit a PR. One note: I'd change "coax" to "coaxial" just to be technically correct.
