### ISSUE TITLE
New API method for ip-addresses to get all parent prefixes like GUI

### ISSUE THREAD

**Issue by Renji-FR** [netbox-community/netbox#3373]
### Environment
* Python version:  3.6.9
* NetBox version:  59139502ac7d (v2.6.1)

### Proposed Functionality
Create a new request (method) from ip-addresses API to get all parent prefixes like GUI.
Client can use built-in functions to get parent prefixes and avoid many API calls and many process to retrieve theses prefixes.

### Use Case
From IP address, client would like retrieve all parent prefixes to retrieve after other informations like site.
Call:
`curl -H "Accept: application/json; indent=4" -H "Authorization: Token 0123456789abcdef0123456789abcdef01234567" "http://localhost:32768/api/ipam/ip-addresses/"`
can return prefixes field like:
```json
"prefixes":
{
    [
        "id": 1,
        "url": "http://localhost:32768/api/ipam/prefixes/1/",
        "name": "myPrefix",
        "slug": "myprefix",
    ],
    ...
}
```

### Database Changes
Nothing change about database.

### External Dependencies
Don't require any new dependency.

**Comment by jeremystretch** [comment]
You want the `contains` filter. Example: `GET /api/ipam/prefixes/?contains=192.168.200.0/24` would return 192.168.0.0/16 and 192.168.128.0/18 as they both _contain_ 192.168.200.0/24.

**Comment by Renji-FR** [comment]
@jeremystretch You use ipam/prefixes but my feature request use ipam/ip-addresses!
NetBox has built-in functions to retrieve parents prefixes from address, GUI use it.

To avoid many API calls, API can permit to retrieve parent prefixes from ip-addresses like GUI.

**Comment by Renji-FR** [comment]
Your solution is correct only with VRF filter but we don't use built-in function.
