### ISSUE TITLE
Idea to enhance the cables features

### ISSUE THREAD

**Issue by quentindavid** [netbox-community/netbox#3374]
### Environment
* Python version:  3.6.8
* NetBox version:  2.5.7

It could be very useful being able to connect a cable only on one side of it, even if you don't know where it's connected on the other side. In this way, we could inventory a DC and find where the cable goes.

### Proposed Functionality
When you do the inventory of the DC, you can just enter the cables connected and identify them by its label. Once you find the other side of the cable, Netbox could recognize that the cable mentioned is already connected on one side, but left unconnected on the other.

### Use Case
Not sure it implies a lot of modifications in the data model, but it add a lot of flexibility.
We can also think to a new view where we see the cables connected only on one side.

### Database Changes
To be determined :)

### External Dependencies
No dependencies

**Comment by lukasodhner** [comment]
I am also in need of more cable details and options. Specifically I would want additional cable status options beyond connected and planned. Ideally there would be deprecated, failed, tested, and probably a few more. Of course some of these would qualify as “connected” and some “disconnected (planned)” state of the current Boolean cable status. I would also really love to have comments and tags on cables. Perhaps this can be addressed in Jeremys suggestion for plugins, although I think it fits into the netbox core and is a natural extension of the cables model. 

For your needs Quentindavid perhaps one option is to create a device called “unknown destination” and add 100 ports or interfaces to it. When you need to show a single ended cable connect it to that device and you can add information about where you think it might go on the port/interface of the unknown device.

**Comment by jeremystretch** [comment]
Sorry folks, the cable model in place now is the result of lengthy discussion leading up to the v2.5 release and won't be modified any time soon. Development is focused in other areas.
