### ISSUE TITLE
Show/hide Custom Links based on object data

### ISSUE THREAD

**Issue by 2bithacker** [netbox-community/netbox#3375]
### Environment
* Python version:  
* NetBox version:  

### Proposed Functionality

The ability to show/hide custom links based on data in the object currently being viewed. For example, only show the custom link if a device has a specific role.

For flexibility, it might be nice to make the conditional a Jinja template that is evaluated for a true/false value, allowing users to have arbitrarily complex logic for button display.

### Use Case

We have an external system which contains more information about certain devices. It would be nice to have a link in Netbox to that system, but only for devices of a specific role.

### Database Changes

Probably an additional field on the Custom Link model for storing the conditional.

**Comment by jeremystretch** [comment]
Custom links will only display if the rendered link text is not empty. So, you can do something like this:

```
{% if obj.role.slug == 'foo' %}{{ obj.name }}{% endif %}
```

Then the link will only display if the role's slug is `foo`.
