### ISSUE TITLE
Add utilization feature for VM Clusters

### ISSUE THREAD

**Issue by valumar** [netbox-community/netbox#3378]
### Proposed Functionality

Please add the column `Utilization` in Clusters view (`/virtualization/clusters/`) as it's already done for Prefixes.

### Use Case
All hypervisors have the perfomance parameters such as Memory Usage, CPU Usage, Storage Usage. Exporting these parameters is not a problem. It would be great to view some type of utilization percentage in Netbox for VM Clusters to identify its utilization level.

For example:

![image](https://user-images.githubusercontent.com/7857900/62206829-4dea1500-b39b-11e9-839b-1f3338ed4492.png)

**Comment by jeremystretch** [comment]
The individual VMs have these attributes defined, but the clusters/hosts do not, so there's no maximum value to compare against. And even if there was, VMs are commonly over-provisioned to varying degrees. Capacity planning in this regard is best left to an orchestration system.
