### ISSUE TITLE
Caching issue: Renaming a slave device is not visible on the parent device

### ISSUE THREAD

**Issue by phurrelmann** [netbox-community/netbox#3382]
### Environment
* Python version:  3.5.3
* NetBox version:  2.6.1

### Steps to Reproduce
1. Rename a child device that is assigned to a parent
2. Go back to the parent
3. The parent still shows the old name of the child
4. Go to the child and verify that it really was renamed
5. After the cache expired the new name is visble on the parent, too

### Expected Behavior
The child device is immediatly shown with its new name (when looked from the parent)

### Observed Behavior
The child device is still shown with its old name (when looked from the parent) until the cache expires (default 900s).

**Comment by phurrelmann** [comment]
The same happens for the device status. A change in a child's device status is not seen on the parent until the cache expires.

**Comment by Solvik** [comment]
I've stumpled upon this case and others
From what I can see, the cache invalidation upon modification isn't working correctly.. it requires to wait for the cache expiration

**Comment by MrXermon** [comment]
Same problem here. The list on the parent is not rehresehd if the name of the child device is updated.

**Comment by jeremystretch** [comment]
Rolled into #3428
