### ISSUE TITLE
Power Maximum draw/Allocated draw missing on Device Types

### ISSUE THREAD

**Issue by KennethFoliJorgensen** [netbox-community/netbox#3384]
### Environment
* Python version:  3.6.3
* NetBox version:  2.6.1

### Steps to Reproduce
1. Create a new Device Type
2. Add Component -> Power Port

### Expected Behavior
that i am able on Power Port to add data to the power consumption fields maximum_draw and allocated_draw.

### Observed Behavior
you are only able to add name

**Comment by DanSheps** [comment]
I can get behind this, most device types are all going to have a similar base power draw (Example, Cisco Cat 9300's, while it depends on the PSU, the PSU we use is always 1100W).

By contrast, we might want to look at removing "Power Feed" from Power Outlet, as most device types won't be connected to the same feed.

**Comment by jeremystretch** [comment]
These fields were added to the model originally, but were not added to the form.
