### ISSUE TITLE
export templates authentication

### ISSUE THREAD

**Issue by neilfab** [netbox-community/netbox#3389]
### Environment
* Python version:  2.7.16
* NetBox version:  v2.6.2

Export templates now require auth to view

Unauthenticated read-view used to work in v2.5.12 but since upgrading to v2.6.2 this now requires auth.  Web auth works fine but this doesn't work via curl and API auth does not work.

Export Template:
[{% for device in queryset %}{% if device.status == 1 %}{"name":"{{ device.name }}","model":"{{ device.device_type.model}}","role":"{{ device.device_role.slug }}"},{% endif %}{% endfor %}{}]

Expected Behavior:
Allow unauthenticated read only view or API authentication method the same for export templates ?

**Comment by jeremystretch** [comment]
Please see the v2.6 release notes for information about view permissions.
