### ISSUE TITLE
Netbox LLDP pages are not showing all interfaces/devices, the API works fine

### ISSUE THREAD

**Issue by dafflinch** [netbox-community/netbox#3397]
### Environment
* Python version:  3.6.8
* NetBox version:  v2.6.2

### Description

LLDP Neighbors not showing all interfaces/devices on Netbox UI

![image](https://user-images.githubusercontent.com/53815190/62526525-b4f34800-b839-11e9-8022-3ef13aee65c0.png)

But we can see all interfaces/devices via API

![image](https://user-images.githubusercontent.com/53815190/62526677-0a2f5980-b83a-11e9-972d-13df6c1913e0.png)

Napalm Driver: Junos

Status and configuration are working correctly through Netbox UI.

**Comment by jeremystretch** [comment]
You need to define the local interfaces on the device in NetBox. If you need further assistance, please post to the mailing list.
