### ISSUE TITLE
Add a rack model number and vendor field into the standard rack data model

### ISSUE THREAD

**Issue by ryanmerolle** [netbox-community/netbox#3400]
### Environment
Python version: 3.6.8
NetBox version: 2.6.2

### Proposed Functionality
Add a rack model number and vendor field into the standard rack data model.  

### Use Case
The vendor field, if it extends the model too much, does not have to be enforced, but it helps if anyone ever wants to create reports to show all assets associated to a vendor across all asset types.  If you were to extend the model some more, then you could have a rack type similar to a device type where you would not have to individually set the rack details for every rack,

**Comment by a31amit** [comment]
I believe it can be achieve with using custom field which is existing functionality

**Comment by ryanmerolle** [comment]
Totally, that is what I am doing now.  I have a custom field for manufacturers (a selection where I maintain a list of vendors) and a custom field for Part Number (a selection where I maintain a list of models).  At least the manufacturers field seems redundant and not able to be linked within the data model for the manufacturers data model.

**Comment by bellwood** [comment]
One could argue pretty much everything physical in Netbox would have a Manufacturer/Model/Serial - Racks, servers, PDU's, breakers, whips, etc.

Might we consider making these fields standard across the model and let custom fields address anything above and beyond?

**Comment by ryanmerolle** [comment]
I agree with @bellwood.

**Comment by ryanmerolle** [comment]
@jeremystretch do you need more feedback?  I would be happy to provide more if so.  I also understand if this feature is deprioritized or not in scope.  I just ask as I do my pre-spring cleaning.

**Comment by jeremystretch** [comment]
It doesn't look like this has drawn much interest in the six months it's been open. I appreciate the use case but I don't think many network engineers particularly care to track rack models. I'm going to close this out, but maybe we'll revisit the idea in the future once we've taken care of the more pressing backlogged items.
