### ISSUE TITLE
Unify status options

### ISSUE THREAD

**Issue by Bitsky** [netbox-community/netbox#3401]
### Environment
* Python version:  2.7.5
* NetBox version:  2.6.1

### Proposed Functionality
It looks like the Status dropdown has a wide range of varying options. Wouldn't it make sense to have them unified so every dropdown list has the same options?

Here are a few:
- Powerfeed: Active, Offline, Planned, Failed
- Device: Active, Offline, Planned, Staged, Failed, Inventory, Decommissioning
- Rack: Active, Planned, Reserved, Available, Deprecated
- Circuit: Planned, Provisioning, Active, Offline, Deprovisioning, Decommissioned
- Virtual Machine: Active, Offline, Staged
- Cluster: (no status)
- Cable: Planned, Connected

I noticed because I wanted to set a powerfeed to Reserved. It would make sense to merge all them into a single list only which is sorted by "on/off".

### Use Case
Having a streamlined status list would let users expect what they can set without checking different status dropdowns first. Racks can be reserved, Powerfeeds can't. Devices can be failed, Cabled can't. Clusters can't be anything.

### Database Changes
A compiled and sorted list of current different Stati would be something like this:

Active
Inactive
Online
Offline
Connected
Disconnected
Available
Unavailable
Provisioning
Deprovisioning
Decommissioned
Deprecated
Planned
Staged
Reserved
Failed

**Comment by jeremystretch** [comment]
> Wouldn't it make sense to have them unified so every dropdown list has the same options?

This approach was intentionally avoided, as many of the statuses do not make sense for every model (for example, an "offline" rack).

**Comment by Bitsky** [comment]
I beg to differ on that one, as it would give more flexibility to the users if it is their decision to make sense of a status. It's not really a huge change, but would widen the options a lot to cover more use-cases.

Like, you can have a bad CAT cable in a bonded network; it's not a huge drama because the bond will generally be set up to provide fault tolerance, but you would want to mark the cable as failed so next time you go to the location for maintenance you don't forget to replace it. Granted the NICs could be bad, but then you'd still want to replace the cable to check.

Or like in my case where I wanted to set a powerfeed to reserved.
