### ISSUE TITLE
Tenancy for Power Feeds

### ISSUE THREAD

**Issue by Bitsky** [netbox-community/netbox#3402]
### Environment
* Python version:  2.7.5
* NetBox version:  2.6.1

### Proposed Functionality
It would be helpful if power feeds could be assigned to tenants and groups too. 

### Use Case
Devices and racks can be dedicated to a customer, and often customers have a dedicated powerfeeds too where they can plug in their devices.

### Database Changes
Add tentants/tenant group information to powerfeeds and -panels.

**Comment by bellwood** [comment]
My .02

From a facility perspective, no tenant would ever be able to manage a power panel, breaker or whip. Sure I may hand a client a whip they can plug a PDU or device into, but, they cannot manage it (energize/de-energize) Things outside a tenants control should remain outside of their tenancy.

Today, creating a power feed already has a rack relationship, racks that have tenancy attributes and those racks have devices that also have tenancy attributes.

What does adding tenancy to power feeds and panels add that existing relationships does not already achieve/solve?

**Comment by jeremystretch** [comment]
I agree with @bellwood, I don't think this makes sense given how NetBox uses the concept of tenancy. And even if you have actual power feeds that are dedicate to a specific tenant, that assignment can be conveyed by assigned the attached PDU (of which there can only be one) to that tenant. Tenant assignment can be used on the associated rack as well.
