### ISSUE TITLE
Inventory "NAME:" Field - increase character limit

### ISSUE THREAD

**Issue by darcynz** [netbox-community/netbox#3403]
# Environment
* NetBox version:  

### Proposed Functionality
When entering in the modules for our environment there are exceptions that cannot be entered as per the device with out truncating the NAME: Field due to the 50 characters limit. E.g

NAME: "ADSL/VDSL over POTS supporting ADSL1, ADSL2, ADSL2+ and VDSL2 on Slot 0 SubSlot 0",

Increasing the character limit for the name record to 100 would resolve this.

### Use Case
Being able to add all inventory items as per it's device.

### Database Changes
None

### External Dependencies
None I am aware of

**Comment by jeremystretch** [comment]
That looks like a module description rather than a name. The item name should match its unique system identifier.
