### ISSUE TITLE
Generic attachment support

### ISSUE THREAD

**Issue by chas0rde** [netbox-community/netbox#3404]
### Proposed Functionality
Allow attachment of general files instead of only images

### Use Case
It would be handy to be able to upload general files instead of only images to various parts of the DCIM. Some examples:
- Attach Power panel documentation to power panel (e.g. fuse layout et cetera)
- Attach test protocols to fiber cables
- Attach various other documentation to various places

**Comment by DanSheps** [comment]
Duplicate of #1039
