### ISSUE TITLE
Add GPS position of rack

### ISSUE THREAD

**Issue by chas0rde** [netbox-community/netbox#3406]
### Proposed Functionality
Extend the Longitude / Latitude feature of sites to racks

### Use Case
We use Netbox for Datacenter and IDF documentation
It would be handy to also link the GPS position to the rack (in our case the IDF) so netbox (as a single source of truth) might hold that information for other systems that allow mapping to positions of the components

**Comment by jeremystretch** [comment]
Can you describe a use case where you know the site at which a rack exists, but cannot locate it using any means other than GPS coordinates?

**Comment by chas0rde** [comment]
We structure as follows:
Regions:         DE > Campus
Sites:              Building on Campus
Rack group:    Set for datacenters
Rack:              Rack in Datacenter, IDF for rest of buildings

This way we are able to document datacenter as well as campus cabling with netbox

So a building (site) might be 3000sqm in size (with machinery in it and so-forth) and have some racks (maybe 3 IDFs) located at different specific positions within the building.

So if the rack would have a (precise) GPS location this would make a big difference to the sneaker-admin getting send somewhere to e.g. patch some port.

**Comment by millijuna** [comment]
This would be useful for me as well. I'm using Netbox to track the IDFs and other gear across a 25 acre/10 hectare campus. I tread the main campus as one site, and our remote gear off-campus as different sites.

Within the campus itself, I can generally locate everything based on a building name/room description. However, in continuing with the mantra of "Source of Truth" having geographical coordinates would allow the linking into OpenStreetmap or similar to produce a visual representation.

**Comment by lampwins** [comment]
This sort of thing is a fringe use case. Can you please explain why custom fields would not cover your needs? This is exactly why they exist.

**Comment by chas0rde** [comment]
Of course it could be done with custom field. But so could it be on sites ;)
My point is that with coordinates being on rack other things for visualization would also become possible (e.g. floor plans)

**Comment by jeremystretch** [comment]
> Of course it could be done with custom field. But so could it be on sites ;)

Tracking the GPS coordinates for individual sites is a _far_ more common use case than for individual racks, which is why the site model has these fields built-in and the rack model does not. I'm going to pass on this one since it seems like a pretty niche requirement, and as @lampwins points out can be met using custom fields anyway.
