### ISSUE TITLE
Create better upgrade documentation and clear link to release notes

### ISSUE THREAD

**Issue by lampwins** [netbox-community/netbox#3409]
### Change Type
[ x ] Addition
[ x ] Correction
[ ] Deprecation
[ x ] Cleanup (formatting, typos, etc.)

### Proposed Changes
The official documentation for upgrading NetBox is quite generic and does nothing to account for the many important considerations and action items included in the last several major releases.

Currently, all of our release notes are contained within a GitHub release. This creates a separate source of pertinent information that is not included in our official documentation.

I propose two things here:
1. Move our changelog to be a part of the official documentation. Since the file is already markdown, should not be very hard. We can retain the CHANGELOG.md file in the root of the repo, and simply provide a link to the docs from there. This also does not hinder the ability to include changelog items in a GitHub release, since those are just copy/pasted.
2. Revamp the upgrade section to ensure users account for important changes and action items in a given release. This includes making the aforementioned changelog more readily apparent from this section. I would also like to see this section discuss specific upgrade steps for users moving a recent version of NetBox with new dependencies. I.e. moving to 2.6 when Redis became required.

**Comment by hellerve** [comment]
I love step 2 especially, since I’ve been a little careless when updating in the past and sometimes missed important updates. Having them highlighted for me would be a huge help!

**Comment by jeremystretch** [comment]
Removing the the 2.7 milestone; happy to implement this under v2.6.x.
