### ISSUE TITLE
Impossibility of getting info about interface object that's hanged on VM

### ISSUE THREAD

**Issue by Dmitresso** [netbox-community/netbox#3417]
### Environment
* Python version:  3.6
* NetBox version:   2.6.1, two instances

### Steps to Reproduce
1. Send http request to get information about interface hanged on VM

### Expected Behavior
Get information about interface hanged on VM

### What happened instead?
NetBox responses
425{"detail":"Not found."}
(first three ciphers are random, can't see any logic)
I have two NetBox instances, tested on both (the same behavior).
1-st and 2-nd requests to interfaces that are hanged on devices, all's ok. 3-d, 4-th interfaces are hanged on Virtual Machines, here I get "detail":"Not found."
![netbox bug via console](https://user-images.githubusercontent.com/15903451/62759570-de1b0f00-baab-11e9-9b8a-0c2a4e1bbd59.png)
The same via browser:
![netbox test instance interface on device request](https://user-images.githubusercontent.com/15903451/62760011-21c24880-baad-11e9-8efc-f4ff6dc717ee.png)
![netbox prod instance interface on device request](https://user-images.githubusercontent.com/15903451/62760009-21c24880-baad-11e9-92c5-580cd9f7a74a.png)
![netbox test instance interface on vm request](https://user-images.githubusercontent.com/15903451/62760012-225adf00-baad-11e9-8de2-c5b869cb4fb9.png)
![netbox prod instance interface on vm request](https://user-images.githubusercontent.com/15903451/62760010-21c24880-baad-11e9-95d4-715afcf13468.png)

**Comment by phurrelmann** [comment]
You should probably use the proper API endpoint für VMs: /api/virtualization/interfaces and not /api/dcim/interfaces

**Comment by Dmitresso** [comment]
> 
> 
> You should probably use the proper API endpoint für VMs: /api/virtualization/interfaces and not /api/dcim/interfaces

Ok, I'have got the interface I need following by your advice, thanks.
But why all the interfaces I add for VM get link like "/dcim/interfaces/\d+" ()? I think to rename topic because that's really discourages and this is a main problem.

**Comment by jeremystretch** [comment]
Thank you for your interest in NetBox. GitHub issues are intended for reporting reproducible bugs and requesting features, and must be submitted using one of the templates provided [here](https://github.com/digitalocean/netbox/issues/new/choose). For general discussion, questions, or assistance with installation issues, please post to our [mailing list](https://groups.google.com/forum/#!forum/netbox-discuss) instead.
