### ISSUE TITLE
Netbox IPAM like GestioIP ?

### ISSUE THREAD

**Issue by Minahora** [netbox-community/netbox#3418]
Hello,

In my current company, we use a tool called "GestioIP" that retrieves the addresses of our subnets and list them as a web page.

GestioIP makes pings and name resolutions based on time.

An example in my current business:
http://prntscr.com/oqfvdz

It recovers the FQDN
70-96.rand.local
70-80.rand.local
76 ....
In red, when the ping has failed so the equipment is disabled or absent from the network
In green, when the ping succeeds and when the equipment is on the network.

Netbox being an IPAM, from what I could see, it is necessary to manually fill in the IP addresses and the fqdn.

Is there an extension with Netbox that does the same thing as GestioIP?

thank you

**Comment by DanSheps** [comment]
Thank you for your interest in NetBox. GitHub issues are intended for reporting reproducible bugs and requesting features, and must be submitted using one of the templates provided [here](https://github.com/digitalocean/netbox/issues/new/choose). For general discussion, questions, or assistance with installation issues, please post to our [mailing list](https://groups.google.com/forum/#!forum/netbox-discuss) instead.
