### ISSUE TITLE
Devices search via web is case insensitive yet it is case-sensitive via api

### ISSUE THREAD

**Issue by frebib** [netbox-community/netbox#3420]
### Environment
* Python version:  No idea
* NetBox version:  2.5.13

### Steps to Reproduce
1. Create a device with a serial number
2. Search web-ui with any case variant and always find the device
3. Search for the device through the api and only find it when the exact same casing is used

### Expected Behavior
Some way to find the find the device through the api with a case-insensitive lookup is a must.

We have a lot of servers and the information is sometimes entered by humans which means it's inconsistent and casing isn't always the same. It's unreasonable to perform multiple lookups for the same device, and even then that still only works if the case is all-lower or all-upper.

### Observed Behavior
Only found the device when the exact same casing is used as is stored in the database

**Comment by jeremystretch** [comment]
To clarify, the GUI and the API both use the same `serial` filter, which is case-sensitive. I assume you're using the general search function under the UI, which is actually the `q` filter (e.g. `?q=foo`), which is case-insensitive and matches on much more than just the serial field.

What you want is to modify the `serial` filter to be case-insensitive.

**Comment by jeremystretch** [comment]
Will also update the `serial` filters for Rack and InventoryItem.

**Comment by frebib** [comment]
Damn, thanks for the really quick response!
