### ISSUE TITLE
Navigation menu overlaps page content in narrow windows

### ISSUE THREAD

**Issue by Pelt10** [netbox-community/netbox#3422]
### Environment
* Python version:  3.5.3
* NetBox version:  2.6.2

### Steps to Reproduce
1. Open Netbox main page
2. Reduce size of the window

### Observed Behavior
The search box disappear under the menu.

![image](https://user-images.githubusercontent.com/7582586/62861871-0e111f00-bd05-11e9-8c03-581da1775c3d.png)

**Comment by megazloj** [comment]
If you will reduce it little more, then search field appears again

![image](https://user-images.githubusercontent.com/7577925/62874936-c0a7a880-bd2a-11e9-9860-a4ab30d1648d.png)
