### ISSUE TITLE
interface tags in devices view are rendered with "label-default" gray background

### ISSUE THREAD

**Issue by LuPo** [netbox-community/netbox#3424]
### Environment
* Python version: 3.7.4
* NetBox version: 2.6.2

### Steps to Reproduce
1. Create a tag and assign it a color
2. Assign tag to an interface

### Expected Behavior
Newly assigned tag should be rendered with a chosen color 

### Observed Behavior
interface tags are always gray

![Tag color](https://user-images.githubusercontent.com/29463/63019951-0b493200-be9d-11e9-95af-96500f0e24c2.png)

**Comment by jeremystretch** [comment]
Just a note: This is a bug in the tag HTML template which affects any instance of a tag rendered without a link (not just interfaces).
