### ISSUE TITLE
Cannot add VLAN with ID 4095 for VGT mode in vSphere

### ISSUE THREAD

**Issue by JQ-KH** [netbox-community/netbox#3425]
### Environment
* Python version:   3.6.8
* NetBox version:  2.6.2

We are using VGT mode (Virtual Guest Tagging) for some virtual machines and this requires setting the VLAN on the virtual switch port to 4095.
See https://kb.vmware.com/s/article/1004252

### Steps to Reproduce
1. Try to add a VLAN with ID 4095

### Observed Behavior
Error: Ensure this value is less than or equal to 4094.
![netbox-vlan-4095-error](https://user-images.githubusercontent.com/54115206/63039493-b8cf3c00-bec3-11e9-918b-e307db3f9541.png)

**Comment by LBegnaud** [comment]
But that's not a valid vlan. It's a vmware way of defining a trunk port, isn't it?

**Comment by JQ-KH** [comment]
It's hard to come by reliable information regarding this, but 4095 is a valid VLAN ID.
Officially VLAN 0 and 4095 are reserved IDs. 
As far as I was able to understand they are both for system use.
VLAN 0 packets can carry an 802.1p priority but are handled like an untagged packet.
VLAN 4095 is "for internal use"
And for me the use case of vSphere internal switching with VLAN ID 4095 is "internal use"  ;)

**Comment by jeremystretch** [comment]
if it's used internally there should be no need to model it in NetBox. If you need some way to indicate that VGT is in use for a specific interface, consider using a tag instead.
