### ISSUE TITLE
VRF information lost during Import/Export of Prefix

### ISSUE THREAD

**Issue by xjs678qr** [netbox-community/netbox#3435]
### Environment
* Python version:  2.7.15+
* NetBox version: 2.6.2

### Steps to Reproduce
1. Create a VRF (named 10DMZ in my case)
2. Create a Prefix beloning to the VRF (e.g. 10.210.0.0/21)
3. Export the Prefixes to CSV. In the Export, the VRF column is empty.

Reversely, 
1. import a list of Prefixes and fill out the existing VRF 
2. The iùmport succeeds, but the prefixes are assigned to the 'GLOBAL' table

### Expected Behavior
VRF information to be present in the CSV during export

VRF Information to be taken into account during import

### Observed Behavior
VRF information is missing the exported CSV

VRF information during import is ignored.

**Comment by jeremystretch** [comment]
> Python version: 2.7.15+

Please specify your actual Python version.

**Comment by xjs678qr** [comment]
It states literally 2.7.15+:

$ python -V
Python 2.7.15+

**Comment by jeremystretch** [comment]
NetBox 2.5 and later requires Python 3.5 or higher. Please verify the version of Python under which NetBox is running.

**Comment by xjs678qr** [comment]
Indeed, it's python3:

$python3 -V
Python 3.6.8

**Comment by jeremystretch** [comment]
The issue here is that the default CSV generator outputs the VRF RD only (which used to be a required field), so if a VRF does not have an RD assigned, the column will be empty. We should probably change it to output the VRF name instead of the RD to ensure consistency.
