### ISSUE TITLE
Connect a fiber cable to two different ports in a patch panel

### ISSUE THREAD

**Issue by FranSoft** [netbox-community/netbox#3442]
### Environment
* Python version:  3.6
* NetBox version:  2.6.1

### Proposed Functionality
Sometimes, it is necessary to indicate that one cable (fiber cable) in a switch is connected to two different ports in a patch panel. It should be possible to do that. You can see more information in the "Use Case" section.

### Use Case
You can see the situation in the following image:
![imagen](https://user-images.githubusercontent.com/2214054/63442232-a789b080-c42a-11e9-9243-a65179855978.png)

One fiber cable on one switch interface is connected to port1 in the patch panel but the second fiber cable is connected to port4 in the patch panel. We can fill this situation in NetBox.

**Comment by tb-killa** [comment]
We have the same requirement. We exclusively use ST Lwl connections, so that exactly the result shown in the picture is achieved.
It would be great if this kind of connections were also implemented in Netbox.

**Comment by jeremystretch** [comment]
You'll need to label the ports e.g. `1/2` and `3/4`. NetBox does not support modeling individual fiber strands within a duplex cable.
