### ISSUE TITLE
Add Site field to Cables page

### ISSUE THREAD

**Issue by ctrusler** [netbox-community/netbox#3444]
### Environment
currently running NetBox version:  2.6.1
### Proposed Functionality

Add a column on the cables page to see what site the cables are in.  Also add it to the search for the cables page

### Use Case

we only keep cable numbers specific per site and not global.  

today we can filter cables by color, type, and status.  when trying to find the next available number for a specific type of cable in a specific site it would be easier if we could also filter by site.

**Comment by lampwins** [comment]
How would you handle the case of a cable connection that spans sites?

**Comment by tb-killa** [comment]
I think the FR is to be understood as follows:

Display the site on each side of the cable connection, parallel to the racks.

Thus the respective endpoint can be referred directly to the site. 

The filter could be difficult.
This need some more input how does should work.

**Comment by ctrusler** [comment]
since cables themselves don't have a site it would need to reference the site the device/ports it connects to are in.

After looking at it more, I thought it would be an quick and easy lookup but it won't be that simple.  I don't think patch ports have a site label for them so it would also need to check the parent patch panel for that also.

**Comment by jeremystretch** [comment]
Covered by #3259
