### ISSUE TITLE
Cisco devices status page shows 'Invalid' in power and fans sections

### ISSUE THREAD

**Issue by asand3r** [netbox-community/netbox#3450]
### Environment
* Python version:  3.6.8
* NetBox version:  2.6.1

When connecting to Cisco IOS devices with NAPALM and look at Status tab Netbox shows strange result for power and fans modules. It mark it with green, but types 'Invalid' near.
![изображение](https://user-images.githubusercontent.com/13959303/63670733-3e1cef80-c7e6-11e9-98af-119e9c22b00c.png)

### Steps to Reproduce
1. Configure Cisco IOS device with Cisco IOS platform
2. Click on 'Status' tab

### Expected Behavior
I don't know, maybe it should show somelike "OK" or "Good" mark.

**Comment by jeremystretch** [comment]
This data is reported by the device via NAPALM. NetBox has no control over it.
