### ISSUE TITLE
Show cable colors on device page

### ISSUE THREAD

**Issue by Bitsky** [netbox-community/netbox#3457]
### Environment
* Python version:  2.7.5
* NetBox version:  2.6.1

### Proposed Functionality
Show the colors of cables on the interfaces list of a device. Right now it's just a blue dash after the cable number/name. To make the color stand out better, maybe change eg "#123 -" into buttons (like "[#123]") similar to those [Primary]/[Active] ones in the Status/Role column. Besides, because most cables are gray by default, undefined colors should fallback to gray instead of blue; or have the button transparent with only the "#123" text.

### Use Case
When you work in the rack, you want a quick overview of the device you're working on. Right now you have to click on every cable to see its color.

### Database Changes
None

### External Dependencies
None

**Comment by jeremystretch** [comment]
> because most cables are gray by default, undefined colors should fallback to gray instead of blue

One cannot assume what the most popular cable color is, and there is no default cable color in NetBox.

**Comment by Bitsky** [comment]
Well, that's why I added:
>or have the button transparent with only the "#123" text

If you consider the current dash to somehow relate to cables and their colors, blue would be less common than gray. But that's beside the point. It should be an easy change which increases the general overview of a device.
