### ISSUE TITLE
Font color of color picker broken

### ISSUE THREAD

**Issue by Carbenium** [netbox-community/netbox#3464]
### Environment
* Python version:  3.7.3
* NetBox version:  2.6.2

### Steps to Reproduce
1. Open any form with a color picker (e.g 'Add a new device role')
2. Select black as color

### Expected Behavior
Font color matches the ```.color-selection-*``` definition so it stays readable.

### Observed Behavior
The default font color of the select2 container is used, which is not really readable with a dark background color.

Screenshot:
![image](https://user-images.githubusercontent.com/3409500/63898646-27e77d00-c9fa-11e9-8e96-5fc9dcab8e75.png)

**Comment by lampwins** [comment]
We have a unity function for choosing the correct foreground color, so we just need to render the full list in the template and do the mapping.
