### ISSUE TITLE
Add custom field and/or tag on vlan group

### ISSUE THREAD

**Issue by shugotek** [netbox-community/netbox#3465]
### Environment
* Python version:  3.6.7
* NetBox version:  2.6.2

### Proposed Functionality
Add possibility to create a custom field for a vlan group to tenant or to add a tag on a Vlan Group.

### Use Case
Need to add information for attach a vlan group to specific "environment"

**Comment by lampwins** [comment]
Expansion of custom fields is not being considered at this time. Please see https://github.com/netbox-community/netbox/wiki/Frequently-Asked-Questions#can-we-add-custom-fields-to-more-models

**Comment by shugotek** [comment]
Ok for custom field, but why not a tag?
