### ISSUE TITLE
Device Type (template) Comments not applied to newly created Devices

### ISSUE THREAD

**Issue by jennec** [netbox-community/netbox#3466]
### Environment
* Python version:  2.7.12
* NetBox version:  2.6.2

### Steps to Reproduce
1. Create a Device Type Template
2. Populate Template with relevant details for that device
3. Add comments in the Comments field for this Device Type.
4: Create a Device from this Device Type Template
6: Observe no comments on the newly created Device Type.

### Expected Behavior
Comments from the Device Type Template to show on the newly created device.

### Observed Behavior
No comments on the newly created device.

**Comment by lampwins** [comment]
The comments field on the DeviceType model is intended for comments directed at that DeviceType, not that those comments would expand to the Devices using that DeviceType. You are likely trying to use DeviceTypes as more of templates than they are intended to represent, which is just hardware configurations shipped by a vendor.

You will likely be interested in #1364 and also #3423
