### ISSUE TITLE
Impossible to connect multiple Mux between them

### ISSUE THREAD

**Issue by Pelt10** [netbox-community/netbox#3467]
### Environment
* Python version: 3.5.3
* NetBox version:  2.6.2

### Steps to Reproduce
1. Create "Mux" device like this :
![image](https://user-images.githubusercontent.com/7582586/63949885-56596c80-ca7b-11e9-9835-90beeb2ca0d6.png)
2. Rack 2 "mux" devices, a "CWDM" mux and a "DWDM" mux
3. Connect Rx COM of the DWDM mux to any Rx port of the CWDM mux.

### Expected Behavior
It connect correctly, to respect this architecture: 
![image](https://user-images.githubusercontent.com/7582586/63950280-fadbae80-ca7b-11e9-8344-dc5b061d0e6f.png)

### Observed Behavior
This error occurred : 
![image](https://user-images.githubusercontent.com/7582586/63950401-35dde200-ca7c-11e9-8051-8977bdc4c39f.png)

**Comment by jeremystretch** [comment]
Connections cannot be condensed via rear ports multiple times. This is a limitation of the cable model we've chosen.
