### ISSUE TITLE
Expand search for Front Ports

### ISSUE THREAD

**Issue by MeisiCB** [netbox-community/netbox#3468]
### Environment

    Python version: 3.5.2
    NetBox version: 2.6.2

### Proposed Functionality

It would be great if you can expand the global search to find front ports with her name.

### Use Case

Our Front Ports on the Patchpanel are labeled like "1.0.14/2A" for Room 1.0.14 and Port 2A. The Label on the Port in the Room is also "1.0.14/2A". I want to search what is connected to Front Port "1.0.14/2A" (to find the switch port).

### Database Changes

No

### External Dependencies

None

**Comment by jeremystretch** [comment]
Device components are not included within global search.
