### ISSUE TITLE
non-device rack items

### ISSUE THREAD

**Issue by ryanmerolle** [netbox-community/netbox#3470]
### Environment
* Python version:  3.6.8
* NetBox version:  2.6.2

### Use Case

Basic non-IP asset for signifying "blank plate" RU covers, wire management, and other similar misc non-IP, non connection/cable panels.

**Comment by jeremystretch** [comment]
This has been discussed many times. You'll need to use devices to represent all objects.

**Comment by ryanmerolle** [comment]
My apologies for adding to your groundhog day.  Thanks as always!
