### ISSUE TITLE
Ability to add bookmarks

### ISSUE THREAD

**Issue by Bitsky** [netbox-community/netbox#3472]
### Environment
* Python version:   2.7.5
* NetBox version:   2.6.1

### Proposed Functionality
Since requests for storing files have been rejected (eg #1408), I would be helpful to at least have the option to store (multiple) URLs per entry which are then displayed in related entries.

For example:
* create manufacturer "ACME" and add URL "https://acme.com/"
* create platform "Superlinux 8" with URL "https://superlinux/8/"
* create device type "1U Case" from ACME, with URL ""https://acme.com/1u-info.html"
* add device with URLs "https://storage/prodsheet-123.pdf", ""https://storage/234-deliverynote.jpg" in a "1U Case" on platform "Superlinux 8".

Now when you access the device, you get a list of all these related URLs. When accessing "1U Case", you see links to the product and the manufacturer.

I'm aware of custom URLs, but this way random URLs can be easily attached to any item.

### Use Case
We have various files related to objects in the inventory. Being able to at least link to them easily would be a big benefit for connecting them. This is not limited to documents, but also files unique for devices, like e.g. configuration dumps, install media or backup locations.

### Database Changes
Create a table for URLs. Important would be target URL, link title and optionally a flag for setting target=_blank.

### External Dependencies
None

**Comment by jeremystretch** [comment]
Custom fields are available for this purpose.

**Comment by Bitsky** [comment]
Actually custom fields are totally impracticable for that because an admin has to define them before they can be used. Plus, custom fields appear on every item they are created for.

So let's say you have a special device where you have 10 or 20 bookmarks pointing to various resources. First, you need the admin to set up custom fields which then will appear on all devices, but remain empty. Furthermore, you can only use generic names, like "URL 1" because the links can point to random targets for different devices what makes it impossible to hint at what the link is for.
Also, from what I've seen, custom fields are not imported from related objects, so a link in a custom field in e.g. a platform entry won't show up on a device that is linked to that platform.

Custom fields have very good use-cases, but for storing random amounts of bookmarks for various items they are completely useless. Or are we supposed to create e.g. 20 dummy custom fields for every item avilable in the admin section, bloating up the interface?
