### ISSUE TITLE
Improve inventory-items' description field

### ISSUE THREAD

**Issue by juan-vg** [netbox-community/netbox#3473]
### Environment
* Python version: 3.5.3
* NetBox version: 2.6.2

### Proposed Functionality
* Allow multi-line (line breaks)
* Allow more than 100 chars

### Use Case
A perfect use case is a RAM (memory) module. Apart from the already present fields I would like to store some details about the module itself such as capacity, speed, class, etc..

Be able to store something like this json example would be awesome
```json
{
   "size": "8 GiB",
   "type": "DIMM DDR3 Synchronous Registered (Buffered)",
   "ecc": true,
   "speed": "1333 MHz",
   "latency": "0.8 ns",
   "width": 64
}
```

### Database Changes
Extend the size of the inventory-items' description field

### External Dependencies
None

**Comment by jeremystretch** [comment]
> I would like to store some details about the module itself such as capacity, speed, class, etc..

It sounds like you're trying to squeeze inventory management functions out of an application that isn't designed for it. This is one reason some of the fields intentionally restrict length: to dissuade users from trying to store data which extends beyond the model.

**Comment by bcohee** [comment]
Hmmm - then why track inventory-items at all in Netbox if there is not a future path to properly manage them?

Netbox has DCIM, and proper DCIM is infrastructure / inventory management.

I don’t agree this should be immediately closed instead of backlogged for a future future version.

**Comment by juan-vg** [comment]
@jeremystretch The description of this project is: "IP address management (IPAM) and data center infrastructure management (DCIM) tool.". It's clear, IPAM & DCIM. DCIM stands for DataCenter Inventory Management, which means all the stuff you have there and not only devices. So my question is.. **Why the model is limiting people to store useful data instead of encouraging it?**
