### ISSUE TITLE
PowerFeed associated to a Datacenter and power consumption report

### ISSUE THREAD

**Issue by Solvik** [netbox-community/netbox#3476]
### Environment
* Python version:  2.6.2
* NetBox version:  3.6.8

### Steps to Reproduce
1. Create Power Feed for a given datacenter, let the Rack field empty
2. Create rack within the datacenter
3. Create device and power ports, report fake consumption

Datacenter:
<img width="910" alt="Capture d’écran 2019-09-04 à 15 14 22" src="https://user-images.githubusercontent.com/201761/64258089-de7dbd00-cf26-11e9-9bfa-f6532afdf6fc.png">

Power Feed:
<img width="911" alt="Capture d’écran 2019-09-04 à 15 14 31" src="https://user-images.githubusercontent.com/201761/64258091-de7dbd00-cf26-11e9-8bf4-cde586ed3849.png">

Server PSU
<img width="783" alt="Capture d’écran 2019-09-04 à 15 17 06" src="https://user-images.githubusercontent.com/201761/64258194-184ec380-cf27-11e9-8400-bd2da8530663.png">

### Expected Behavior

By assigning Power Feed to the datacenter, I supposed the power consumption of a rack would still be reported in the column "Power" of the rack list. 

### Observed Behavior

In the list of the dacenter's racks, we should see the power consumption of the rack.
But because the Power Feed isn't assigned to the Rack but to the whole datacenter, the power consumption reports 0 (see screenshot)

I understand the documentation isn't very complete for this part of the project (I'll try to make a PR about it), but from what I understand, it's not necessary to create as much Power Feed as there's racks

**Comment by jeremystretch** [comment]
Please revise your issue to specify exactly what you're doing, including the precise numbers you're getting and how they differ from what you were expecting.

**Comment by Solvik** [comment]
I've updated the issue a bit, it made me understand the complete workflow, I think

If I assign a `Power Feed` to a `Site` (and leave the `Rack` field empty) netbox code won't be able to guess the power utilization for a given rack.

**Can you confirm this ?**

So the correct usage is to create a `Power Feed` per `Rack`.
In case of a dual Power Feed of 30A rack with 208V, it gives us a 2x 6.2 kVA which makes a 2x 6.2kW for a power factor of 1.
Netbox will then report the actual consumption (if reported on the Device's `Power Ports`).

In the case of a room with 45kW but 10x 6kW racks, how can you monitor that the rack's total consumption doesn't exceed the room's electric capacity ? 
Is that a missing feature of `Power Panel` ?

**Comment by wols** [comment]
Do you have devices via PDU on the feeds?

![power-racks](https://user-images.githubusercontent.com/764167/66391476-84f92a00-e9cd-11e9-84f3-0e1d87aeb886.png)

![power-feeds](https://user-images.githubusercontent.com/764167/66391485-89bdde00-e9cd-11e9-83a7-38670d51539d.png)

![power-fuse](https://user-images.githubusercontent.com/764167/66391503-9cd0ae00-e9cd-11e9-95f8-393df22cf191.png)

![power-pdu-in](https://user-images.githubusercontent.com/764167/66391511-a22df880-e9cd-11e9-9fae-783ea64004db.png)

![power-pdu-out](https://user-images.githubusercontent.com/764167/66391516-a528e900-e9cd-11e9-861d-6a5797185334.png)

I'll be creating a howto soon: https://github.com/wols/awesome-netbox

**Comment by jeremystretch** [comment]
I think there's some confusion about how power is modeled in NetBox. In order to convey power utilization for a rack, it _must_ have at least one power feed associated with it. No assumptions are made about how power is delivered to a rack beyond that. A rack with no power feeds assigned to it will always show 0% utilization.
