### ISSUE TITLE
Cannot create VLAN in VLAN group via API

### ISSUE THREAD

**Issue by ollehjohansson** [netbox-community/netbox#3479]
### Environment
* Python version:  3.5.3
* NetBox version:  2.6.3

Create VLAN via API in a specific group

### Steps to Reproduce
1.  From <server-url>/api/docs under /ipam/vlans/ ipam_vlans_create create VLAN with a group ID: 
{
  "group": 1,
  "vid": 2,
  "name": "string",
  "status": 1,
  "description": "string",
  "tags": [
    "string"
  ],
  "custom_fields": {}
}

A VLAN should be created in VLAN group with ID 1

Gets HTML error outpus that says: VLANGroup: object is not iterable

When creating same VLAN without VLAN group it works

**Comment by DanSheps** [comment]
Thank you for your interest in NetBox. GitHub issues are intended for reporting reproducible bugs and requesting features, and must be submitted using one of the templates provided [here](https://github.com/digitalocean/netbox/issues/new/choose). For general discussion, questions, or assistance with installation issues, please post to our [mailing list](https://groups.google.com/forum/#!forum/netbox-discuss) instead.
