### ISSUE TITLE
Error when creating a power outlet template via API

### ISSUE THREAD

**Issue by tkupari** [netbox-community/netbox#3480]
### Environment
* Python version:  3.7.4 
* NetBox version:  2.6.2 

### Steps to Reproduce
1. Add device type "Model 1" in Netbox for "Some Manufacturer"
2. Create power port named "pp1" for device type
3. Attempt to create power outlet on device type by sending a POST request to /dcim/power-outlet-templates/ API

Data for creating a power outlet with reference to an existing power port:
```
{
  "device_type": 64,
  "name": "power outlet 1",
  "power_port": {
    "device_type": {
      "manufacturer": {
        "name": "Some Manufacturer",
        "slug": "some-manufacturer"
      },
      "model": "Model 1",
      "slug": "model-1"
    },
    "name": "pp1",
    "maximum_draw": 100,
    "allocated_draw": 100
  },
  "feed_leg": 1
}
```
Data for creating a power outlet with a reference to non-existing power port:
```
{
  "device_type": 64,
  "name": "power outlet 1",
  "power_port": {
    "device_type": {
      "manufacturer": {
        "name": "Some Manufacturer",
        "slug": "some-manufacturer"
      },
      "model": "Model 1",
      "slug": "model-1"
    },
    "name": "pp2",
    "maximum_draw": 100,
    "allocated_draw": 100
  },
  "feed_leg": 1
}
```

### Expected Behavior

Power outlet template is created

### Observed Behavior

When using existing power port name, status code 400 with following error

```
{
  "power_port": {
    "non_field_errors": [
      "The fields device_type, name must make a unique set."
    ]
  }
}
````

When using non-existing power port name, status code 500 with following error
```
<class 'ValueError'>

Cannot assign "OrderedDict([('device_type', <DeviceType: Model 1>), ('name', 'pp2'), ('maximum_draw', 100), ('allocated_draw', 100)])": "PowerOutletTemplate.power_port" must be a "PowerPortTemplate" instance.
```

**Comment by jeremystretch** [comment]
Your description doesn't make sense. Are you trying to create a power port or a power outlet? They are different objects.

**Comment by tkupari** [comment]
I'm trying to create a power outlet that is connected to an existing power port tempate on the device type. 

Here's a screen capture what I'm trying to do, but instead of using the UI, I'm using the API

![image](https://user-images.githubusercontent.com/631762/64350910-19a0ee80-d002-11e9-89c2-8151179044b1.png)

**Comment by tkupari** [comment]
Is there still something that can be done to clarify this issue?

**Comment by jeremystretch** [comment]
Thank you for your interest in NetBox. GitHub issues are intended for reporting reproducible bugs and requesting features, and must be submitted using one of the templates provided [here](https://github.com/digitalocean/netbox/issues/new/choose). For general discussion, questions, or assistance with installation issues, please post to our [mailing list](https://groups.google.com/forum/#!forum/netbox-discuss) instead.
