### ISSUE TITLE
How to enable webhook when object create/update/delete

### ISSUE THREAD

**Issue by yangcaixing** [netbox-community/netbox#3481]
Hi all, 
   When I enable webhook via Extras>webhooks for object changed, but it seems it doesn't work, I don't know if any extra configure needed,  so if anyone else also has the same issue, thanks very much.

**Comment by jeremystretch** [comment]
Thank you for your interest in NetBox. GitHub issues are intended for reporting reproducible bugs and requesting features, and must be submitted using one of the templates provided [here](https://github.com/digitalocean/netbox/issues/new/choose). For general discussion, questions, or assistance with installation issues, please post to our [mailing list](https://groups.google.com/forum/#!forum/netbox-discuss) instead.
