### ISSUE TITLE
Allow referencing custom field values in custom link templates.

### ISSUE THREAD

**Issue by fknorn** [netbox-community/netbox#3483]
### Environment
* Python version: 3.6.8
* NetBox version: 2.6.2

### Proposed Functionality
Allow referencing of custom fields in custom links. Right now, it seems I cannot reference for instance  `obj.custom_fields.prtg_id` in a custom link template.

### Use Case
I have an external monitoring tool where devices have their own unique ID. I added a custom field for storing this ID, and I now would like to create deeplink to the device in the monitoring tool using that custom field.

### Database Changes
Unsure, but I believe none, since the custom field functionality is already implemented.

### External Dependencies
None.

### Current result if attempting this
I am using this as Text in the custom link:

`https://monitoring.example.com/device.htm?id={{ obj.custom_fields.prtg_id }}&tabid=1`

but upon redering the device page, I get an exception
```
<class 'jinja2.exceptions.UndefinedError'>

'dcim.models.Device object' has no attribute 'custom_fields'
```

However, looking at the corresponding page with the API viewer that field is there:

```
HTTP 200 OK
Allow: GET, PUT, PATCH, DELETE, HEAD, OPTIONS
Content-Type: application/json
Vary: Accept

{
    "id": 2,
[ -- snip -- ]
    "comments": "",
    "local_context_data": null,
    "tags": [],
    "custom_fields": {
        "prtg_id": 13951
    },
    "config_context": {},
[ -- snip -- ]
}
```

**Comment by rmrf-run** [comment]
have you tried `https://monitoring.example.com/device.htm?id={{obj.cf['prtg_id']}}&tabid=1`? that is how my custom links are working with my monitoring tool

**Comment by jeremystretch** [comment]
As @rmrf-run points out, custom fields are accessible under the `cf` property.
