### ISSUE TITLE
Ability to assign IP address to virtualization/clusters/[entity]

### ISSUE THREAD

**Issue by kdhlab** [netbox-community/netbox#3484]
### Environment
* Python version:  3.6.6
* NetBox version:  v2.6.2

### Proposed Functionality

I would like the ability to assign IP addresses and virtual interfaces to a virtual cluster. 

### Use Case

Some virtualization environments, such as Nutanix AHV have a cluster management IP on a virtual interface that is floating across the cluster members. I would like to be able to add the IP of the cluster to the cluster object itself. Currently as a work-around I am just assigning the IP with the cluster name in the description which does not actually associate it with the cluster which does not model the cluster accurately.

Utilizing virtual chassis does not model this correctly either since there is no Master in a virtualization cluster and the members are still distinct entities with distinct interfaces.

### Database Changes
N/A
### External Dependencies
N/A

**Comment by jeremystretch** [comment]
This might partially be addressed by #2456, but we won't be making any modifications to the IP model beyond that due to development constraints.
