### ISSUE TITLE
Allow Graphs on Devices views

### ISSUE THREAD

**Issue by fknorn** [netbox-community/netbox#3485]
### Environment
* Python version:  Python version: 3.6.8
* NetBox version:  NetBox version: 2.6.2

### Proposed Functionality
Currently, Graphs are only supported in the site, provider, and interface views. It would be great to extend this functionality to Device views.

### Use Case
While I understand that netbox is not destined to replace monitoring systems and that the device page is already pretty full, it would be handy to be given the ability to add some representative graph for a device as well.

Ideally in a "conditional" / "templaty" kind of way similar to custom links, whereby one could add jinja-based {% if %} statement to not show the graph / panel in case a specific variable is not set.

### Database Changes
None

### External Dependencies
None

**Comment by fknorn** [comment]
Thank you, Jeremy! I really appreciate your efforts with netbox!

**Comment by bluikko** [comment]
The documentation at https://netbox.readthedocs.io/en/stable/additional-features/graphs/ says:
> Type: Site, provider, or interface.

"devices" should probably be added there.
