### ISSUE TITLE
Allow shift-clicking for selecting/unselecting multiple rows at once

### ISSUE THREAD

**Issue by fknorn** [netbox-community/netbox#3487]
### Environment
* Python version:  Python version: 3.6.8
* NetBox version:  NetBox version: 2.6.2

### Proposed Functionality
Support shift-clicking to select/unselect multiple rows. 

### Use Case
Currently, if one needs to select multiple rows in the various views (e.g. interface table), one needs to click on each checkbox individually. Oftentimes one has to select a "contiguous" range of elements though, so it would be nice to be able to click one row (start), then shift-click another (end) to have that range checked. Just how one is already used to in the various OS file browsers, Excel, etc etc.  

### Database Changes
None

### External Dependencies
None

### Links
It appears to be relatively easy to implement, but there are also many out-of-the-box implementations, e.g. https://www.jqueryscript.net/table/jQuery-Plugin-To-Enable-Multi-Rows-Selection-On-Table-Row-Selector.html

**Comment by jeremystretch** [comment]
We won't be making any significant UI changes until development time frees up to facilitate the transition to an API-driven UI using React, Angular, or a similar framework (likely in NetBox v3.0).
