### ISSUE TITLE
InventoryItem name attribute size

### ISSUE THREAD

**Issue by Solvik** [netbox-community/netbox#3488]
### Proposed Changes

I'd like to extend the size of `InventoryItem` `name` attribute, [see here](https://github.com/netbox-community/netbox/blob/develop/netbox/dcim/models.py#L2600).

### Justification

I'm reporting the local hardware of servers using InventoryItem. Such as RAID Cards, Memory DIMM, Motherboard and such.
I'm reporting the name of DIMM memory like `DIMM DDR4 Synchronous Registered (Buffered) 2400 MHz (0.4 ns) (16.0GB)`

Since the size is currently limited to 50 chars, I'd like to raise this size to a more appropriate one, say 128 chars ?

If validated (feature and size), I can propose a PR.

**Comment by DanSheps** [comment]
This issue has been closed as it does not conform to one of the [provided templates](https://github.com/digitalocean/netbox/issues/new/choose) as required by the [contributing guide](https://github.com/digitalocean/netbox/blob/master/CONTRIBUTING.md). If you'd like to request that your issue be re-opened, please first update the content so that it matches the appropriate template (this may require rewriting your issue entirely).

**Comment by jeremystretch** [comment]
> `DIMM DDR4 Synchronous Registered (Buffered) 2400 MHz (0.4 ns) (16.0GB)`

FYI item names must be unique to the device/parent item in which they are installed. The above is a description that's likely to be identical for each installed module; its name would be something like `DIMM1`.

**Comment by Solvik** [comment]
Name is not unique in the model
And there's no description field 

For the uniqueness I'm using the serial field or the asset field

**Comment by jeremystretch** [comment]
> Name is not unique in the model

It is part of a unique set:

```
class InventoryItem(ComponentModel):
    ...
    class Meta:
        unique_together = ['device', 'parent', 'name']
```

**Comment by Solvik** [comment]
That's  because `parent` is None in my case

<img width="946" alt="Capture d’écran 2019-09-07 à 10 12 01" src="https://user-images.githubusercontent.com/201761/64472005-76aeb880-d158-11e9-86e7-cd6ec197c50d.png">
