### ISSUE TITLE
Circuit Termination issue when connected to a rear port with N front ports

### ISSUE THREAD

**Issue by laguyle** [netbox-community/netbox#3492]
### Environment
* Python version:  3.6.7
* NetBox version:  2.6.3

### Steps to Reproduce

1. Connect A side and Z side of a circuit to a rear port of a device on both side with N front ports associated (in our case a multiplexer)
2. Connect front port 1 of the multiplexer on side A to an interface 1 of a device X
3. Connect front port 1 of the multiplexer on side Z to an interface 1 of a device Y
4. Connect front port 2 of the multiplexer on side A to an interface 2 of a device X
5. Connect front port 2 of the multiplexer on side Z to an interface 2 of a device Y

Here is a network diagram to understand our case:

![image](https://user-images.githubusercontent.com/39376910/64680154-880c0380-d47d-11e9-9763-d7a048750b7c.png)

### Expected Behavior

We should see interfaces 1 and 2 of device X connected to interfaces 1 and 2 of device Y through the circuit.

### Observed Behavior

Only interfaces 1 of devices X and Y are well linked through the circuit.
Interfaces 2 are not totally linked.
I supposed it's due to the fact that when we link the first front port of each mux to interfaces 1 of devices X and Y, terminations of the circuit is moved to Device X - port 1 on A side and Device Y - port 1 on Z side.
I think terminations of the circuit should always stay as the first port or interface it is linked, in our case the rear port of each MUX.

**Comment by wols** [comment]
NetBox version: 2.6.5
I wanted to adjust the config, but get the error message when connecting the MUX rear ports:
`Side A has 1 positions and rear has 2. Both terminations must have the same number of positions.`
My MUX (X side):
![mux-x](https://user-images.githubusercontent.com/764167/66390137-4f9f0d00-e9ca-11e9-8c75-ff3f16e9a821.png)

**Comment by zelfix** [comment]
I have the same error, as a result, I have to use interfaces on the passive DWDM device instead of rear and front physical ports.

**Comment by wols** [comment]
Suggestion: if you bring all interfaces to one vlan(group) you can see them as vlan members ;-)

**Comment by laguyle** [comment]
I don't want to define interfaces on my DWDM devices, this doesn't make sense.
The functionnality to associate several front ports to one rear port is exactly what we need.

But I think there is a limitation somewhere in the code that requires that a rear port has to be DIRECTLY connected to a rear port of another device with exactly the same number of front ports on each devices.
But in our case, rear ports are not directly connected because we want to insert a circuit between them.

**Comment by wols** [comment]
I unterstand. My intention was [Replicate the Real World](https://netbox.readthedocs.io/en/stable/#replicate-the-real-world) (multiplexing is not direct connection).

HACK: You could use Device Power Ports with the appropriate caption.
Add one Power Port "Rear" and any Power Outlets "Front [1-n]" connected to Input/Leg `Rear`...

**Comment by jeremystretch** [comment]
Just realized this is the same issue as described in #3288
