### ISSUE TITLE
Example in jinja2 conditional rendering for custom URLs has typo

### ISSUE THREAD

**Issue by ctullos** [netbox-community/netbox#3495]
### Change Type
[x] Addition
[x] Correction
[ ] Deprecation
[ ] Cleanup (formatting, typos, etc.)

### Proposed Corrections
----------------------------------------------------------------------------------------------------------
* Please correct typo in existing documentation (see below) 
 https://netbox.readthedocs.io/en/stable/additional-features/custom-links/#custom-links
```
For example, if you only want to display a link for active devices, you could set the link text to

{% if device.status == 1 %}View NMS{% endif %}
```  
example should state:  

```
{% if obj.status == 1 %}View NMS{% endif %}
```

 ### Proposed Additions
----------------------------------------------------------------------------------------------------------

* Custom URLs are a very useful feature, coupled with Jinja2 templating it is very extensible. Can you please provide a few more examples and/or pointer to the subclasses that can be called?

For instance, I wanted to conditionally render based on device type. So I tried:

```
{% if obj.type == 1 %}View NMS{% endif %}
```

instead of:
```
{% if obj.device_type.model == 'TESTNAME' %}View NMS{% endif %}
```

**Comment by DanSheps** [comment]
obj.device_type.name is not a valid path, it would have to be:

obj.device_type

or

obj.device_type.model

**Comment by ctullos** [comment]
sorry about that, updated OP to reflect obj.device_type.model
