### ISSUE TITLE
Add Textbox to to Custom Scripts.

### ISSUE THREAD

**Issue by michaelpsomiadis** [netbox-community/netbox#3497]
### Environment
* Python version: 3.6.8
* NetBox version:  v2.6.3

### Proposed Functionality
Adding Multiline TextBox to Custom Scripts. Something similar to the following screenshot.
![image](https://user-images.githubusercontent.com/49224103/64838573-242d3a80-d637-11e9-9513-72b1c50c2059.png)

### Use Case
I often use a external python script that uses the API and takes a CSV formatted text to bulk add cables (power/network) between different devices as they are relationship dependent.
I used this the most when moving to netbox and it's still useful to have when provisioning new gear in netbox.

### Database Changes / External Dependencies
As far as i'm aware no database or dependency changes are needed to add this.

**Comment by jeremystretch** [comment]
Use `TextVar` for this instead of `StringVar`.

Note: There's currently a bug (see #3514) which causes TextVars to render without a label, though I should have this fixed shortly.
