### ISSUE TITLE
webhooks: allow overwriting certificate bundle used to verify requests

### ISSUE THREAD

**Issue by uedvt359** [netbox-community/netbox#3499]
### Environment
* Python version:  3.6.8
* NetBox version:  v2.6.3

### Proposed Functionality

Requests, which is used to call webhooks, vendors its own CA bundle. This is a problem in our environment, where we sign our certs with our own internal CA. You can override the used CA bundle by setting session.verify to a path (instead of True). 

We propose adding a configuration option to set the path to the CA bundle used to verify TLS certificates. We have implemented the [changes already in this branch](https://github.com/dvtirol/netbox/tree/pr-cabundle) ([direct link to commit](https://github.com/dvtirol/netbox/commit/88c6a8be0150ac62e47bc9667f4dde41fe333353)), and will open a PR once this enhancement gets accepted.

### Use Case

We sign our internal certificates with our own (internal; non-default) CA. Adding such a configuration flag would allow us to turn on certificate verification for webhooks.

### Database Changes

none.

### External Dependencies

none.

**Comment by tyler-8** [comment]
`requests` is actually using the `certifi` package for CA information. The better solution, rather than modifying `netbox` IMO, is to follow the outline here: https://incognitjoe.github.io/adding-certs-to-requests.html and append your internal CAs to the `certifi` bundle.

**Comment by uedvt359** [comment]
Thanks for your reply. 

We'd rather not modify certifi, for two reasons: 
1. This will become reverted with every update to the library, increasing maintenance costs and (if someone forgets to monkey-patch it back in) breakage of the webhooks. 
2. We use the same virtual environment for multiple programs on multiple hosts. We need to be able to verify certs signed by public CAs in some applications, and only certs signed by us in others (including Netbox).
3. To me, and this is purely subjectively, modifying certifi is the wrong layer to handle this. Requests supports supplying a custom CAbundle, only Netbox doesn't expose that functionality.

While not relevant for us directly, [some distributions](https://src.fedoraproject.org/rpms/python-certifi/blob/master/f/certifi-2018.10.15-use-system-cert.patch) patch certifi to use the system CA bundle. With such a setup, using a custom CA just for validating webhooks becomes impossible without clobbering certs for the whole system.

I still believe that such a configuration option is useful to have in Netbox.

**Comment by lampwins** [comment]
IMO @uedvt359 is correct here. The certifi method makes more sense if you control the flow end to end. Adding a CA file path field to the Webhook model on the end hand is more explicit and would be less error-prone for users.
