### ISSUE TITLE
Add colored badge to IPAddress Family value in detail view

### ISSUE THREAD

**Issue by Grokzen** [netbox-community/netbox#3500]
### Environment
* Python version: 3.7.x  
* NetBox version: 2.6.3  

### Proposed Functionality

A small cosmetic change to the details page of IPAddress detail view where the family field could be altered to a colored badge to make it easier to spot if the address is a IPv4 or IPv6 address.

Attached example image of how it can look

![image](https://user-images.githubusercontent.com/892309/64859387-61d79680-d62a-11e9-885b-168e3f5a4d59.png)

![image](https://user-images.githubusercontent.com/892309/64859403-6bf99500-d62a-11e9-9ede-166e308eb2fc.png)

### Use Case

Adding color to this field makes it easier to spot and recognize what IPAddress family that is set on a IPAddress object. We added this to our internal fork and it was well recieved.

### Database Changes
None

### External Dependencies
None

**Comment by jeremystretch** [comment]
Honestly this doesn't seem useful IMO. The address family is already immediately apparent just from the format of the address itself.

Also, the built-in context colors are meant to convey certain conditions (green means success, cyan means informational, etc.). We should avoid assigning these to attributes which are not inherently indicative of a particular context.

**Comment by Grokzen** [comment]
What we noticed was that you had to look at the acctual IPAddress itself above the tabs to determine what it was. Yes IPv4 and IPv6 addresses themself sticks out much more then the small text difference in IPv4 and IPv6. Adding the color makes it much faster to detect and recognize what it is.

I do agree with your point that the built-in colors is not super good in this scenario as they are commonly used to other things. If accepted, yes some slight different colors might have to be chosen to represent this.

**Comment by jeremystretch** [comment]
Closing this out as there hasn't been any additional supportive feedback.
