### ISSUE TITLE
What name am i supposed to use for this file? And what extension do i use?  I keep getting the following error

### ISSUE THREAD

**Issue by iambrianoh** [netbox-community/netbox#3502]
### Change Type
[X ] Addition
[ ] Correction
[ ] Deprecation
[ ] Cleanup (formatting, typos, etc.)

### Proposed Changes
What name am i supposed to use for this file? And what extension do i use?  I keep getting the following error

root@ubuntu:/etc/nginx/sites-enabled/netbox# sudo nginx -t
nginx: [crit] pread() "/etc/nginx/sites-enabled/netbox" failed (21: Is a directory)
nginx: configuration file /etc/nginx/nginx.conf test failed

![image](https://user-images.githubusercontent.com/33033803/64885473-1ec0f780-d619-11e9-8389-0676037fbfa3.png)

**Comment by lampwins** [comment]
Thank you for your interest in NetBox. GitHub issues are intended for reporting reproducible bugs and requesting features, and must be submitted using the template provided [here](https://raw.githubusercontent.com/digitalocean/netbox/develop/.github/ISSUE_TEMPLATE.md). For general discussion, questions, or assistance with installation issues, please post to our [mailing list](https://groups.google.com/forum/#!forum/netbox-discuss).

A quick hint... `/etc/nginx/sites-enabled/netbox` is a file, not a directory. There is no file extension, this is Linux. `nginx -t` is clearly telling you the error.
