### ISSUE TITLE
Feed Legs not created/displayed in PDU Devices

### ISSUE THREAD

**Issue by clatini** [netbox-community/netbox#3503]
### Environment
* Python version:  3.7.3
* NetBox version:  2.6.3

### Steps to Reproduce
1. Define a Power Feed 'Feed1' (for example: 380V,  16A,  Three-Phase);
2. Define a new Device Type 'Test PDU' adding a Power Port 'Input1' with maximum draw of 11600W and a number of outlets associated to the three legs (for example: 12 for Leg A,  12 for Leg B,  12 for Leg C);
3. Create a new device 'PDU1' with 'Device Role 'PDU' using the Device Type template previously created;
4. Attach the Power Port 'Input1' to the feed 'Feed1';

The 'Power Utilization' box doesn't show the Feed Legs.

![1](https://user-images.githubusercontent.com/2264300/64914407-ede3de00-d750-11e9-8045-c2f172de450d.JPG)

### Expected Behavior
Same as Netbox 2.6.2, after attaching the feed to the PDU Power Port,  the Feed Legs are displayed in the 'Power Utilization' box.

![2](https://user-images.githubusercontent.com/2264300/64914409-048a3500-d751-11e9-9fb7-54cf931c5516.JPG)

**Comment by jeremystretch** [comment]
This is happening because you've manually defined a maximum aggregate draw for the power port. If you remove that, NetBox will dynamically calculate the draw per leg based on connected outlets.
