### ISSUE TITLE
Interface ordering Arista EOS

### ISSUE THREAD

**Issue by maartenbollen** [netbox-community/netbox#3505]
### Environment
* Python version: 3.6.8
* NetBox version: 2.5.12

Ordering of interfaces for Arista devices is not working as intended. Interface naming looks like it's based as newest first. Naming scheme is: "EthernetX" when interfaces are 100/1000/10000 mbit, and "EthernetX/Y" when using 25/40/100G interfaces.

In the DCIM overview I can see:
Ethernet53/1
Ethernet53/2
Ethernet53/3
Ethernet53/4
Ethernet1
Ethernet2
Loopback0

### Proposed Functionality
Sorting to be:
Ethernet1
Ethernet2
Ethernet53/1
Ethernet53/2
Ethernet53/3
Ethernet53/4
Loopback0

**Comment by jeremystretch** [comment]
> NetBox version: 2.5.12

The current stable release is v2.6.3. Please ask to re-open this if you're able to replicate the issue on v2.6.3.

**Comment by maartenbollen** [comment]
Please reopen. Problem persists after upgrading to v2.6.3

**Comment by jeremystretch** [comment]
Per the [natural ordering tests](https://github.com/netbox-community/netbox/blob/develop/netbox/dcim/tests/test_natural_ordering.py), this is intended behavior. Interfaces with a single trailing numeric ID as ordered after those following a slot/port scheme. This is to ensure that interfaces like `Loopback0` come after `Ethernet1/1`. Unfortunately, it is not feasible to accommodate every quirk of every platform, at least not with the current approach to natural ordering.
