### ISSUE TITLE
API filtering 'OR' logic not working when filtering IP addresses by device ID

### ISSUE THREAD

**Issue by ajknv** [netbox-community/netbox#3507]
### Environment
* Python version:  3.6.8
* NetBox version:  2.6.3

### Steps to Reproduce
Issue an API query with filter parameters specifying two different device IDs, for example:
https://netbox/api/ipam/ip-addresses/?device_id=13441&device_id=13442

### Expected Behavior
API will return IP addresses associated with the devices having ids 13441 and 13442.

### Observed Behavior
API returned only the IP addresses associated with the last given device id, in this case 13442.

**Comment by DanSheps** [comment]
device_id in ipam/filters.py is a NumberFilter.

This could at least be upgraded to a ModelMultipleChoiceFilter.
