### ISSUE TITLE
Setting tags attribute for a rear_port/front_port conducts in HTTP error 500

### ISSUE THREAD

**Issue by louis-oui** [netbox-community/netbox#3513]
### Environment
* Python version:  3.6.6
* NetBox version:  2.5.13 & 2.6.3

### Steps to Reproduce

1. Add a device => ID 1
2. Add a rear_port by API with data  - usings tags => ID 1
{
  "device": 1,
  "name": "5",
  "type": 2500,
  "positions": 12,
  "description": "",
  "tags": []
}
3. Add a rear_port by API with data => ID 2
{
  "device": 1,
  "name": "1",
  "type": 2500,
  "positions": 12,
  "description": ""
}
4. Add a front_port by API with data   - usings tags
{'device_id': 1, 'name': '1', 'type': 2300, 'rear_port_id': 1, 'rear_port_position': 1, 'description': '', 'tags': []}
5. Add a front_port by API with data
{'device_id': 1, 'name': '2', 'type': 2300, 'rear_port_id': 2, 'rear_port_position': 1, 'description': ''}

### ObservedBehavior
- at step 2, rear_port is created but error 500 is reported
- at step 3, rear_port is created without error
- at step 4, front_port is created but error 500 is reported
- at step 5, front_port is created without error

### Expected Behavior
- at step 2, rear_port is created without error
- at step 4, front_port is created without error

**Comment by louis-oui** [comment]
Suggested solution. Remove tags attributes for front/rear ports

**Comment by jeremystretch** [comment]
The exception is due to the changelog routine not being able to parse tags correctly, but the root issue is that the front and rear port serializers don't inherit from `TaggitSerializer` as they should. Thank you for the report!
