### ISSUE TITLE
Inventory Items Export Template

### ISSUE THREAD

**Issue by darcynz** [netbox-community/netbox#3515]
### Environment
* NetBox version:  <!-- Example: v2.6.3)

### Proposed Functionality
Being able to create export templates to extract inventory information. 

### Use Case
Extract Inventory information with associated data, eg device data or perhaps location/region data. Export could be created depending on the use case.

### Database Changes
None expected.

### External Dependencies
None Expected.

**Comment by kobayashi** [comment]
Is this different with the issue https://github.com/netbox-community/netbox/issues/2090 ?

**Comment by darcynz** [comment]
Similar but not the same, this is for the inventory model not the custom fields model.

**Comment by jeremystretch** [comment]
> Being able to create custom exports to extract inventory information.

This is not sufficient detail for a feature request. Please describe the exact functionality you are proposing.

**Comment by darcynz** [comment]
> > Being able to create custom exports to extract inventory information.
> 
> This is not sufficient detail for a feature request. Please describe the exact functionality you are proposing.

Apologies of the generic nature of this request.

The specific use case is that we would like to filter Inventory Items by the devices status via the gui. Eg Show all inventory items for Active Devices. 

We are wanting to use inventory items more and we noticed that this model does not allow export templates to be written. Also tried to get this data by the device export but I can't see a device method to show related inventory items. 

We have a workaround by tagging inventory items. But this shouldn't be necessary. Also Tags are not clickable on the inventory page.

**Comment by jeremystretch** [comment]
Ok, so this is just to enable the creation custom export template for inventory items? I thought that was an option already but apparently not.

> we would like to filter Inventory Items by the devices status via the gui.

This would need a separate feature request.
