### ISSUE TITLE
Allow Jinja commands in Graph / Link URL

### ISSUE THREAD

**Issue by fknorn** [netbox-community/netbox#3520]
### Environment
* Python version:  Python version: 3.6.8
* NetBox version:  NetBox version: 2.6.4

### Proposed Functionality
For Extras / Graphs - support Jinja template commands in **Link URL** fields.

### Use Case
When using different monitoring tools for different types of devices. That way, if-then-else statements could be used based on custom variables to create appropriate links to the respective tools.

### Database Changes
None

### External Dependencies
None

**Comment by jeremystretch** [comment]
I should point out that NetBox _does_ currently support template rendering using the Django language, as noted [in the docs](https://netbox.readthedocs.io/en/stable/additional-features/graphs/). However, we are moving to Jinja2 for all user-facing templating.
