### ISSUE TITLE
Unable to modify or change position of a device within a rack due to javascript error in parseURL

### ISSUE THREAD

**Issue by kabaga** [netbox-community/netbox#3521]
**Environment**

    Python version: 3.6.8
    NetBox version: 2.6.4

**Steps to Reproduce**

1. Go on Device
2. Create a device
 2.1. Go to Location section and populate the Site, Rack, Rack Face 
 2.2. The Position drop-down menu is stuck in "Searching..." and U# is not showing up

**Expected Behavior**

In steps 2.2., the Position drop-down menu should show the list of U# for the specified rack.

**What's working**
Only for new devices that are created in the rack's "add device" button.
I can add a "new" device to the rack only if the device is newly created in the Racks/Site/Name/clicking on "add device" in the rack.
Also, in Rack/Elevations/clicking on "add device" in the rack.

**Comment by JuergenKammer** [comment]
Same problem here. This was working on an earlier version of netbox (i *think* 2.6.3). Trying to change the position of a device in a rack leads to the same not-opening drop-down.

**Comment by aamsaleg** [comment]
Hi,
Exactly the same problem here.

**Comment by DanSheps** [comment]
This was fixed in a1216fc1b7f48be207de7ea99ea1a957a9a1a458 I believe.

**Comment by lampwins** [comment]
FYI for all, v2.6.5 was released today and addresses this issue, please upgrade.
