### ISSUE TITLE
Multiple lldp neighbors returned for interface

### ISSUE THREAD

**Issue by navigateitservices** [netbox-community/netbox#3523]
### Environment
* Python version:  3.6.8
* NetBox version:  2.6.4

When viewing LLDP neighbours, LLDP Device and LLDP Interface sometimes show incorrect settings due to multiple neighbours returned by the lldp request and only the first being used.
As en example:
some lldp port return multiple neighbours, with every neighbour except the last being empty.
I propose a change to always use the last returned lldp neighbor.

### Steps to Reproduce
1. Click on any device configured with napalm
2. Click on LLDP Neighbours

 Devices and ports of the lldp neighbours are shown correctly

Some devices are not shown properly since since lldp neighbours returned multiple object and only the first is being used

Proposed change in "netbox/templates/dcim/device_lldp_neighbors.html"

`- var neighbor = neighbors[0];`
`+ var neighbor = neighbors[neighbors.length-1];`

**Comment by DanSheps** [comment]
> some lldp port return multiple neighbours, with every neighbour except the last being empty.

This would be vendor specific LLDP implementation functionality

> I propose a change to always use the last returned lldp neighbor.

I don't feel this would be a reasonable change, the current functionality of using the first neighbor makes the most sense.  I could see altering this to include all neighbors on a port, however this might require significant code changes.

As it stands right now, the LLDP functionality is sufficient for most needs.
