### ISSUE TITLE
Allow multiple search terms when searching for IP addresses

### ISSUE THREAD

**Issue by muroj** [netbox-community/netbox#3525]
### Environment
* Python version: Python 3.6.8
* NetBox version:  NetBox 2.6.3

### Proposed Functionality

It would be useful to perform a bulk attribute update on a range of IP's within a subnet. For example, adding (or removing) tag `tester-tom` to addresses `10.20.102.[50-100]`. Right now the IP search is string based (#1620), so searching for `10.20.102.5` will find addresses `10.20.102.5,[10.20.102.50-10.20.102.59], [10.20.102.500-599]`. In this scenario, to assign hosts `10.20.102.50/24-10.20.102.100/24` to Tester Tom, we have to perform five searches: `10.20.102.[5,6,7,8,9]`: for each search, select all addresses matching the query -> Edit All -> Add/Remove Tags -> Save.  One suggestion is to allow the range syntax that is supported on the IP bulk add UI: i.e. `10.20.102.[50-100]`.  Yet another suggestion, allow for multiple comma-separated search strings e.g.: `10.20.102.5,10.20.102.6`.

### Use Case

We oftentimes designate blocks of IP addresses within a subnet for certain purposes. For example, within a given subnet we may assign fifty contiguous addresses for use by a particular developer/tester, or for exclusive use by VMs on a given host system. We plan on "assigning" the IPs using tags, as I don't see a concept of IP "ownership" within netbox (although maybe I can use the custom data feature). These designations change fairly rapidly, so the multiple/search update workflow will become very tedious.

This request seems similar to #1410 (but is different), and is somewhat related to #834

**Comment by DanSheps** [comment]
The comma syntax would diverge from the API where we use commas to designate "and" logic.

**Comment by jeremystretch** [comment]
It should be possible to pass the `address` filter multiple times in a URL to `OR` multiple values. However, I think this is not currently possible because we're using a method filter for this field.

Additionally, I'll note that the `parent` filter allows you to find all IPs within a given prefix.

**Comment by jeremystretch** [comment]
Marking this accepted with the understanding that it entails improving the current filter behavior to allow multiple parameters. For example, `/api/ipam/ip-address/?address=192.0.2.1&address=192.0.2.2` should return IPs matching either address.

**Comment by kobayashi** [comment]
Is this issue for filtering multiple ipaddresses? Or more enhancement mentioned in original proposal?

**Comment by kobayashi** [comment]
Take a look at `ipam/filters.py`,

We can do address filtering like this with a new custom lookups.

```
def filter_address(self, queryset, name, value):
    address_prefix, address_nonprefix = [], []
    try:
        for address in value:
            if '/' in address:
                address_prefix.append(address)
            else:
                address_nonprefix.append(address)

        return queryset.filter(
            Q(address__in=address_prefix) |
            Q(address__net_host_list=address_nonprefix)
        )

    except ValidationError:
        return queryset.none()
```
