### ISSUE TITLE
Problem with changing/add position of a device

### ISSUE THREAD

**Issue by vinii8817** [netbox-community/netbox#3533]
We are running netbox in docker environment with the last stable release:
### Environment
* Python version:  Docker (Python 3.7.4)
* NetBox version:  v2.6.4

When we are trying to add a device, in the location form, the input "POSITION" is always trying to find the "U" (it keeps searching without find it). The same happens when we try to edit the device after create it. **Atached we have a screenshot with the problem and the JS error showed by the browser (we tried in chrome, firefox and IE).**

If we go to the rack and insert the device clicking in the corresponded "U" it works fine. The problem only happens editing or add a "device" object.

The screenshots are attached, let me know if you need more information about it.

### Steps to Reproduce
1. Clicking in add a device (green plus sign) in the device pane
2. After adding all the device and hardware information 
3. When select the location/position input, it opens a box saying Searching... even trying to type for example "U10" you cant apply.

### Expected Behavior
Apply the rack position of a device without having to select it in the rack itself, and change the position of the device in the rack without having to recreate it.

### Observed Behavior
A searching message with a js error.
<br><br>

![Screenshot_33](https://user-images.githubusercontent.com/20617848/65443452-83900500-de04-11e9-9d1d-ba2c46223a19.png)

**Comment by DanSheps** [comment]
Duplicate #3521

**Comment by DanSheps** [comment]
Duplicate: #3521
