### ISSUE TITLE
Add REST API endpoint for executing custom scripts

### ISSUE THREAD

**Issue by jeremystretch** [netbox-community/netbox#3538]
### Environment
* Python version: 3.6.8
* NetBox version: 2.6.4

### Proposed Functionality
Add a REST API endpoint for executing custom scripts, similar to the endpoint which exists for executing validation reports (`/api/extras/reports/`).

### Use Case
This will allow custom scripts to be triggered by remote systems in addition to web UI users.

### Database Changes
None

### External Dependencies
None

**Comment by chaomodus** [comment]
One minor request here, if there were a way to pass some custom data not as a log message back, such as a dictionary that, in the API form, was converted to part of the JSON response, but pretty printed as part of the result in the web UI response.
