### ISSUE TITLE
Adding a link to Kubernetes manifests as an Alternative Installation method in the README

### ISSUE THREAD

**Issue by mohahmed13** [netbox-community/netbox#3541]
### Change Type
[X] Addition
[ ] Correction
[ ] Deprecation
[ ] Cleanup (formatting, typos, etc.)

### Proposed Changes
Add a link to an external repo that has sample NetBox manifests which can be deployed on top of a running Kubernetes environment. The proposed change is to simply add a link to the README file under the "Alternative Installations". 

There was a PR here already: https://github.com/netbox-community/netbox/pull/3508. The original issue was closed as it was thought that the changes would be to the main docs, which it's not.

**Comment by jeremystretch** [comment]
Merged #3508
