### ISSUE TITLE
Trying to change U position in rack throws ReferenceError

### ISSUE THREAD

**Issue by LibreBeats** [netbox-community/netbox#3542]
* Python version:  3.5.3
* NetBox version:  2.6.4

When trying to change the position of a device in a rack,by going to a device, editing the device, 
and trying to change position inside the Location section, the search bar just hangs and does not return any result. 
The console returns ReferenceError, untagged is undefined. It starts on tthis line:
 "filter_field = $('#id_' + match[1]);untagged"

### Steps to Reproduce
1. Go to devices, and edit some.
2. Try to change the location in a rack.

### Expected Behavior
I can select, say, U20.

### Observed Behavior
I can't select anything, and cannot change U.

**Comment by DanSheps** [comment]
Duplicate: #3521
