### ISSUE TITLE
Inline VLAN editing missing from Virtualization

### ISSUE THREAD

**Issue by DanSheps** [netbox-community/netbox#3543]
### Environment
* Python version:  3.6
* NetBox version:  2.5.5-dev

### Steps to Reproduce
1. Edit a virtual machine interface

### Expected Behavior
Proper inline field should be visible

### Observed Behavior
Regular dropdown menu is available, no filtering is done to filter the queryset.  This will have performance implications.

**Comment by lassebm** [comment]
@jeremystretch In 2.6.5, an interface configured in "Access" mode with an already configured untagged VLAN results in an empty "Untagged VLAN" field.

**Comment by DanSheps** [comment]
@lassebm Have you collected static?

I just tested this on master and I am not seeing this behaviour.  Please provide reproducible steps (if you  need, you can use https://master.netbox.dansheps.com for testing as this is the current master branch)

**Comment by lassebm** [comment]
@DanSheps I have, yes. It's reproduced here: https://master.netbox.dansheps.com/virtualization/vm-interfaces/17/edit/?return_url=/virtualization/virtual-machines/37/

**Comment by DanSheps** [comment]
Alright, I see what is going on, thanks.

**Comment by DanSheps** [comment]
Will be fixed under #3574
