### ISSUE TITLE
MultiSelectbox variable for scripts

### ISSUE THREAD

**Issue by darcynz** [netbox-community/netbox#3545]
NetBox version: 2.6.5
Python version: 3.7

### Proposed Functionality
Add a multiselectbox variable so that multiple arbitrary devices can be modified via Scripts.

Combining this with Select2 like functionality (as per #3516) would enable this further.

### Use Case
Being able to mass update existing devices in bespoke manner. EG Select devices for a 'Stage' device Script, that checks fields are completed correctly (hostname, IP etc), changes their status and moves their location.

### Database Changes
Not that i'm aware off.
### External Dependencies
Not that i'm aware off.

**Comment by jeremystretch** [comment]
Please specify your NetBox and Python versions as required by the issue template.

**Comment by darcynz** [comment]
> Please specify your NetBox and Python versions as required by the issue template.
Thanks/Sorry - Updated
