### ISSUE TITLE
Napalm drivers

### ISSUE THREAD

**Issue by SerhiiZahuba** [netbox-community/netbox#3546]
### Change Type
[ ] Addition
[ ] Correction
[ ] Deprecation
[ *] Cleanup (formatting, typos, etc.)

### Proposed Changes

![image](https://user-images.githubusercontent.com/36307887/65677899-14601e00-e05b-11e9-97f3-1e9e451d325f.png)

What needs to be written in the line Napalm drivers?

**Comment by jeremystretch** [comment]
Thank you for your interest in NetBox. GitHub issues are intended for reporting reproducible bugs and requesting features, and must be submitted using one of the templates provided [here](https://github.com/digitalocean/netbox/issues/new/choose). For general discussion, questions, or assistance with installation issues, please post to our [mailing list](https://groups.google.com/forum/#!forum/netbox-discuss) instead.
