### ISSUE TITLE
Unable to get session key working in Firefox version above 69.0.0

### ISSUE THREAD

**Issue by 33Fraise33** [netbox-community/netbox#3547]
### Environment
* NetBox version:  2.6.1

### Steps to Reproduce
1. Download latest firefox
2. Try to unlock a secret with a correct session key.
3. No popup or confirmation happens, in network debugger I get 400 bad request, invalid private key
4. This key does work on Google Chrome (with exactly the same copy paste)

### Expected Behavior
Api call is done correct and key is unlocked.

### Observed Behavior
400 bad request in network debugger

### Comments

I'm unsure if I need to report this with Firefox or if this is something that can be fixed from netbox side.

**Comment by CosmoMyzrailGorynych** [comment]
> Please try upgrading to the current stable release (v2.6.5) and seeing if this problem persists. If so, please ask to re-open this issue.

Reopen, then.

v2.6.6
Firefox Dev edition v71.0b9.
My key is unlocked by admin, I have admin rights, privkey is valid. The `admin` user can create and read secrets, I can't.

**Comment by kobayashi** [comment]
I tried this on v2.6.6 with firefox 72.0b2.
- registered a rsa public key in my account `kobayashi`.
- activated it by admin
- registered a device secret (session key was generated at this operation.)

This worked to me.
Could you try again with non openssh format?

**Comment by kobayashi** [comment]
@CosmoMyzrailGorynych Please try general rsa key and If you have the same issue, open new issue because the original issue is not reproduced.
