### ISSUE TITLE
Manage.py rqworker not starting

### ISSUE THREAD

**Issue by mackeyja** [netbox-community/netbox#3548]
Hello, 
I installed netbox on RHEL 7.7 2 days ago from the stable release.
I followed the steps in the documentation.
When running "manage.py help" , rqworker is not listed as an available command.
Is this simply something in the documentation that needs to be updated?
Also for the installation I cloned the github repository instead of downloading the .tar/.zip file.
Any assistance is appreciated.

Regards,
Joseph Mackey III

**Comment by jeremystretch** [comment]
Thank you for your interest in NetBox. GitHub issues are intended for reporting reproducible bugs and requesting features, and must be submitted using one of the templates provided [here](https://github.com/digitalocean/netbox/issues/new/choose). For general discussion, questions, or assistance with installation issues, please post to our [mailing list](https://groups.google.com/forum/#!forum/netbox-discuss) instead.
