### ISSUE TITLE
Netbox - No CSS loading with Apache2

### ISSUE THREAD

**Issue by ecsgh** [netbox-community/netbox#3555]
### Environment
* Python version:  3.6.5
* NetBox version: 2.6.5

By default, the look is normal. All CSS seem to be loaded.
Except the page Admin. Here the CSS does not seem to load.

```
<title>Site administration | NetBox</title>
<link rel="stylesheet" type="text/css" href="/static/admin/css/base.css">
<link rel="stylesheet" type="text/css" href="/static/admin/css/dashboard.css">
   <meta name="viewport" content="user-scalable=no, width=device-width, initial-scale=1.0, maximum-scale=1.0">
<link rel="stylesheet" type="text/css" href="/static/admin/css/responsive.css">
```
The first error is in vhost.conf
netbox/netbox/ static does not exist in the source.
There is only project-static.
Means that in vhost.conf .../netbox/netbox/static must be replaced with ../netbox/project-static .

Second bug I could not fix is that under static, alias from project-static, there is no admin/css/..
Only one css/base.css

https://github.com/netbox-community/netbox/issues/3381

### Steps to Reproduce
1. Open startpage
2. Open Admin Page
3.

### Expected Behavior
That css is okay under Adminpage

**Comment by jeremystretch** [comment]
Thank you for your interest in NetBox. GitHub issues are intended for reporting reproducible bugs and requesting features, and must be submitted using one of the templates provided [here](https://github.com/digitalocean/netbox/issues/new/choose). For general discussion, questions, or assistance with installation issues, please post to our [mailing list](https://groups.google.com/forum/#!forum/netbox-discuss) instead.

**Comment by ecsgh** [comment]
I have use the template!

**Comment by DanSheps** [comment]
This is not reproducible on the current master and develop branches.

Please use the mailing list for assistance with configuration.
