### ISSUE TITLE
Custom script log functions do not escape HTML entities

### ISSUE THREAD

**Issue by fchiron-qualys** [netbox-community/netbox#3556]
### Environment
* Python version:  3.6.8
* NetBox version:  2.6.5

### Steps to Reproduce
1. Create a custom with logs containing HTML tag-looking data like output of python type()
2. Run the script

```
from extras.scripts import Script

class LogBugScript(Script):
    description = "HTML entities not escaped"

    def run(self, data):
        self.log_debug("int type: {}".format(type(2)))
        self.log_success("int type [fixed]: {}".format(type(2)).replace("<", "&lt;"))
        self.log_info("<pre>Can be nice</pre>")
        self.log_warning("<pre>Or not</pre>")
        self.log_failure("JS injection...<script lang='javascript'>alert('XSS')</script>")

```

![output](https://user-images.githubusercontent.com/55992072/65899904-04c33b00-e3b5-11e9-8bc0-9363718308c9.jpg)

log_* functions should escape HTML entities

log_* just output passed string as-is avoiding output of some texts and opening possibility of code injection.

**Comment by jeremystretch** [comment]
Folding this into #3471
