### ISSUE TITLE
host devices in cluster api

### ISSUE THREAD

**Issue by soofff** [netbox-community/netbox#3558]
### Environment
* Python version:  3
* NetBox version:  2.6.5

### Proposed Functionality
Host devices are listed under `/virtualization/clusters/123` but not in api.
That would make cluster api much more useful.

I think that’s the opposite of https://github.com/netbox-community/netbox/issues/1540.
### Use Case
If you want to get the host devices to a cluster but you only know the cluster name.

### Database Changes
(I suspect) None

### External Dependencies
None

**Comment by jeremystretch** [comment]
> If you want to get the host devices to a cluster but you only know the cluster name.

Devices are accessed via the `/api/dcim/devices/` endpoint. The following will filter devices by cluster ID:

```GET /api/dcim/devices/?cluster_id=123```

Note that virtual machines are retrieved in the same manner, at `/api/virtualization/virtual-machines/`.

I will note that NetBox does not have a filter for matching either type of object by cluster _name_; seems like this was overlooked back when clusters were introduced. We could add one, but this would need to be a separate FR.
