### ISSUE TITLE
Config Contexts changes not tracked

### ISSUE THREAD

**Issue by chonty** [netbox-community/netbox#3566]
### Environment
* Python version:  3.5.1-3
* NetBox version:  2.6.5

### Steps to Reproduce
Create/modify/delete a config context object

### Expected Behavior
Log of config context object creation/modification/deletion to appear in the changelog

### Observed Behavior
No change logged

**Comment by jeremystretch** [comment]
This is intentional: ConfigContexts are not change-logged models. Please open a feature request if you would like to propose changing this.
