### ISSUE TITLE
Custom scripts UI throws a <class 'OSError'> exception when scripts are renamed

### ISSUE THREAD

**Issue by benjy44** [netbox-community/netbox#3579]
### Environment
* Python version:  3.5.2
* NetBox version:  2.6.5

### Steps to Reproduce
1. Create a custom script class called MyClass(Script):
2. Rename it to MyNewClass(Script):
3. Refresh the /extras/scripts/ page will throw a <class 'OSError'> exception
4. If I rename back the class to MyClass(Script), the scripts page may load but randomly will throw the same error

### Expected Behavior
The scripts page loads normally

### Observed Behavior
Exception thrown:
![image](https://user-images.githubusercontent.com/47328447/66390526-2468ed80-e9cb-11e9-83e3-f983d8bd5954.png)

Apologies if this has been reported already, I didn't find a similar bug report.

**Comment by jeremystretch** [comment]
You'll need to either manually restart the WSGI process (e.g. gunicorn or uWSGI) whenever you make a change, or configure it to reload automatically when it detects a file change. See the discussion in #1590.
