### ISSUE TITLE
CustomScript should not default to commit changes

### ISSUE THREAD

**Issue by Grokzen** [netbox-community/netbox#3581]
### Environment
* Python version: 3.6.x  
* NetBox version: 2.6.5  

### Proposed Functionality

Right now the default in the `ScriptForm` for the commit option is to default to commit the changes on the script run. This sounds like a dangerous option. Change this to default to `False` in the form.

### Use Case

This would prevent scripts form accidentally run and commit things that might not be the correct thing to run. Commiting changes through this feature should be Opt-in and not Opt-out.

**Comment by jeremystretch** [comment]
How about an attribute on Script that allows the author to override the default behaviour? Example:

```
class MyScript(Script):
    description = "Does something potentially dangerous"
    default_commit = False
```

**Comment by Grokzen** [comment]
I do not agree with your argument that it is better to have commiting changes on by default and not even with a ConfirmForm in between. But, a flag to change it is better then not having it yes.
