### ISSUE TITLE
User with no permissions can view custom_field_choices API endpoint

### ISSUE THREAD

**Issue by Grokzen** [netbox-community/netbox#3583]
### Environment
* Python version: 3.6.x  
* NetBox version: 2.6.5  

### Steps to Reproduce
1. Create a user with no permissions or groups attached to it
2. Access to http://localhost/api/extras/_custom_field_choices/

### Expected Behavior
This API endpoint can possibly leak additional information that it should not as it exposes a lot of internal field values and data that you might not want to expose without controll.

### Observed Behavior
User could see all data in that API endpoint

**Comment by jeremystretch** [comment]
This is expected. NetBox permissions deal only with view, create, update, and delete functions on objects: There are no permissions which imply access to potential field values. If you have a set of potential attributes that is itself considered sensitive (and enforcing `LOGIN_REQUIRED` does not provide sufficient protection), it would not be advisable to store them as custom field choices.
