### ISSUE TITLE
Problem with Cable automation

### ISSUE THREAD

**Issue by Cob87** [netbox-community/netbox#3586]
### Environment
* Python version: 3.7 
* NetBox version:  2.6.5

Hello guys,

I'm trying to automate the "cable" part but I'm having some problems.
Here is the data I send to my netbox:
"
{'termination_a_id': '11120',
 'termination_a_type': 'dcim.interface',
 'termination_b_id': '11121',
 'termination_b_type': 'dcim.interface',
 'terminaton_a': {'device': {'id': 398, 'name': 'v3aw33-lsw01'},
                  'id': '11120',
                  'name': 'ETH1/31'},
 'terminaton_b': {'device': {'id': 399, 'name': 'v3aw33-lsw02'},
                  'id': '11121',
                  'name': 'ETH1/31'}}
"
All the information is correct but I note that the information sent to my netbox are different and false ...

"MGMT <> ETH1/1" and an reversal between termination_a and b

Is it a bug or did anyone manage to make it work?

Thx

**Comment by Cob87** [comment]
Hum excuse me, I forgot to mention that I use "pynetbox" :)

**Comment by jeremystretch** [comment]
Thank you for your interest in NetBox. GitHub issues are intended for reporting reproducible bugs and requesting features, and must be submitted using one of the templates provided [here](https://github.com/digitalocean/netbox/issues/new/choose). For general discussion, questions, or assistance with installation issues, please post to our [mailing list](https://groups.google.com/forum/#!forum/netbox-discuss) instead.
