### ISSUE TITLE
local_config_context accepts non-object JSON

### ISSUE THREAD

**Issue by Wiston999** [netbox-community/netbox#3588]
### Environment
* Python version:  3.7-alpine3.10
* NetBox version:  2.6.5

### Steps to Reproduce
1.Store in a dcim.device object the string `"null"` in `config_context` field.
2.Try to retrieve the object using `/api` endpoint

### Expected Behavior

The object's JSON representation should be returned.

### Observed Behavior

It's failing with a message like:
```
                        </p>
<pre><strong>&lt;class &#39;AttributeError&#39;&gt;</strong><br />
&#39;str&#39; object has no attribute &#39;items&#39;</pre>
                        <p>
                            If further assistance is required, please post to the <a href="https://groups.google.com/forum/#!forum/netbox-discuss">NetBox mailing list</a>.
                        </p>
```

**Comment by jeremystretch** [comment]
This is a validation error. The `local_config_context` field should only accept JSON in object form, similar to a regular ConfigContext.
