### ISSUE TITLE
Examples in webhooks.md need updating

### ISSUE THREAD

**Issue by markkuleinio** [netbox-community/netbox#3600]
### Change Type
[ ] Addition
[X ] Correction
[ ] Deprecation
[ ] Cleanup (formatting, typos, etc.)

### Proposed Changes

In webhooks.md, the POST request examples need adjusting:
- signal_received_timestamp -> timestamp, and the example format is incorrect
- username is missing
- request_id is missing

**Comment by lampwins** [comment]
Closed in #3615
