### ISSUE TITLE
Can't select position in a rack

### ISSUE THREAD

**Issue by nicochouette** [netbox-community/netbox#3614]
### Environment
* Python version:  2.7.13
* NetBox version:  2.6.4

### Steps to Reproduce
1. Choose an existing device
2. Change the position of this device in the rack (or in an other rack)

### Expected Behavior
Select a position for a device in the rack

### Observed Behavior
Can't select a position in the rack, select input displaying "Searching..."

**Comment by brusilov** [comment]
As of version 2.5, NetBox no longer supports Python 2. Python 3 is required to run any 2.5 release or later.
https://netbox.readthedocs.io/en/stable/installation/migrating-to-python3/

**Comment by jeremystretch** [comment]
This sounds like a recent bug that has been resolved. Please upgrade to NetBox v2.6.6.

**Comment by nicochouette** [comment]
@brusilov in fact we are using Python 3.5, I didn't see that we were using virtualenv.

**Comment by nicochouette** [comment]
@jeremystretch Cool, we had no doubts it was a bug. Thanks, we will upgrade.

**Comment by nicochouette** [comment]
Upgrade to 2.6.6 OK.
Now it's working, we can set a position to a device.
