### ISSUE TITLE
Add 400G OSFP Interface type

### ISSUE THREAD

**Issue by mrevilme** [netbox-community/netbox#3619]
### Proposed Functionality
New interface type in constants.py

### Use Case
We need to have 400G OSFP Interface type defined in the Netbox Model for documenting interfaces

### Database Changes
None

### External Dependencies
None

**Comment by DanSheps** [comment]
I am thinking we should wait until we get #3569 finished first.  Anyone else have a strong opinion one way or the other?

**Comment by jeremystretch** [comment]
I don't see any reason to wait on this: It'll just get converted along with the other types when/if #3569 gets implemented. (I am however holding off on introducing any new ChoiceFields.)
