### ISSUE TITLE
Improve interfaces templates: allow word expansion

### ISSUE THREAD

**Issue by fser** [netbox-community/netbox#3623]
### Environment
* Python version:  3.7
* NetBox version:  2.6.6

### Proposed Functionality
In the template interface, allow user to expand names. For example `Interface/[FRONT|BACK]/Eth[1-10]` would produce:

```
Interface/FRONT/Eth1
Interface/FRONT/Eth2
Interface/FRONT/Eth3
Interface/FRONT/Eth4
Interface/FRONT/Eth5
Interface/FRONT/Eth6
Interface/FRONT/Eth7
Interface/FRONT/Eth8
Interface/FRONT/Eth9
Interface/FRONT/Eth10
Interface/BACK/Eth1
Interface/BACK/Eth2
Interface/BACK/Eth3
Interface/BACK/Eth4
Interface/BACK/Eth5
Interface/BACK/Eth6
Interface/BACK/Eth7
Interface/BACK/Eth8
Interface/BACK/Eth9
Interface/BACK/Eth10
```

### Use Case

We need such expansion pattern for our device templates. Maybe others do as well!

### Database Changes
None

### External Dependencies
None

**Comment by kobayashi** [comment]
Thank you for opening this issue. 
Could you let me know what kind of devices have both front/back interface?

**Comment by fser** [comment]
Hello,

from my understanding, mostly patch panels.

**Comment by DanSheps** [comment]
Are you using interfaces or front/rear ports?

**Comment by jeremystretch** [comment]
Two thoughts. First, we should stick to comma-delimited values since that's the current convention. Second, we should be able to tweak `parse_alphanumeric_range()` to simply ignore values which don't specify a range and pass them through.

**Comment by fser** [comment]
Sorry for the delay!
@DanSheps : I asked my colleague, and he told me he uses interfaces because the "front/back" thing didn't exist at the time when they created the template. Does that answer your question?

@jeremystretch : I tried to tweak it using commas (by the way, why does the regex allow so many delimiter `[?:,-]` if only the coma is valid?) but I couldn't identify the case where expansion was required instead of enumeration. See my PR if that can be relevant.

Thanks anyway for the interest!
