### ISSUE TITLE
Correct use of custom fields in reports

### ISSUE THREAD

**Issue by wols** [netbox-community/netbox#3625]
### Change Type
[x] Addition
[ ] Correction
[ ] Deprecation
[ ] Cleanup (formatting, typos, etc.)

### Proposed Changes

Please add an example for the correct use of current custom fields in [Reports - Netbox](https://netbox.readthedocs.io/en/stable/additional-features/reports/)

E.g check boolean `custom_field` for `unset|true|false`...

**Comment by kobayashi** [comment]
Hello @wols,
Thank you for taking your time for this issue. Are you interested in making the PR to add the part to the docs?

**Comment by wols** [comment]
Sure - but the issue was triggered by ignorance:

Python version: 3.6.9
NetBox version: 2.6.6
```
from dcim.models import Device
from extras.models import CustomFieldValue
```

My first test...
```
for device in Device.objects.all():
    test = CustomFieldValue.objects.filter(obj_id=device.id)
    if test:
        self.log_info(
            device,
            "custom_fields on {} : {}".format(device.name, test)
        )
```
...any results - but **What the right way to filter for a boolean CustomField `my_field`?**

**Comment by jeremystretch** [comment]
@wols Please post to the mailing list if you need assistance with reports.
