### ISSUE TITLE
Add a note to invalidate cache after performing DB dump

### ISSUE THREAD

**Issue by bdlamprecht** [netbox-community/netbox#3626]
### Change Type
[X] Addition
[ ] Correction
[ ] Deprecation
[ ] Cleanup (formatting, typos, etc.)

### Proposed Changes
Add some type of note regarding the need to invalidate the cache when migrating the Postgres DB between different machines.

I'll open a PR soon that addresses this fairly simple change.

**Comment by sdktr** [comment]
Could you elaborate on:
1) the scenario you are hinting at (what is migrated? Only the app, the cache or the DB is moved?)
2) why invalidation is needed in this scenario, what problem does it solve?
