### ISSUE TITLE
Occasional object deletions being missed

### ISSUE THREAD

**Issue by stuntguy3000** [netbox-community/netbox#3628]
### Environment
* Python version:  2.7.5
* NetBox version:  v2.6.6

### Steps to Reproduce
Unable to determine steps to reproduce, investigating further.

### Expected Behavior
Every object deletion to be shown.

### Observed Behavior
Sometimes they are missed. As shown in this screenshot, once it is was missed, and in my production environment I see it more often.

![image](https://user-images.githubusercontent.com/1522389/67155047-9556c080-f34e-11e9-8019-02f8c9a8624b.png)

**Comment by jeremystretch** [comment]
> Unable to determine steps to reproduce, investigating further.

Bug reports must be at least partially reproducible. Please request that this issue be reopened if you are able to identify a replication pattern.
