### ISSUE TITLE
Display port-id in LLDP panel

### ISSUE THREAD

**Issue by BegBlev** [netbox-community/netbox#3629]
### Environment
* Python version:  3.7.3
* NetBox version:  2.5.11

### Proposed Functionality
Currently, when displaying the LLDP tab on a JunOS device, the "port description" is displayed if present in the equipment.
![image](https://user-images.githubusercontent.com/27002365/67210213-f945bb80-f418-11e9-9687-12dd165886dd.png)

The reason for that is that Napalm used function is "get_lldp_neighbors". This function returns "port description" in the "port" field if available. If not it returns "port-id".
This does not seem the best behaviour as the LLDP panel with its color code (white, blue, green and red) is used to compare Netbox declared connectivity to real (LLDP) connectivity.

The proposed enhancement consists in using "get_lldp_neighbors_detail" Napalm function. The use of this function allows to explicitly retrieve LLDP "port-id".
![image](https://user-images.githubusercontent.com/27002365/67210306-25f9d300-f419-11e9-9664-103e06f54759.png)

### Use Case
Using "port-id" instead of "port description" allows to easily check connectivity consistency.

### Database Changes
None

### External Dependencies
None

**Comment by jeremystretch** [comment]
This issue has been closed as it does not conform to one of the [provided templates](https://github.com/digitalocean/netbox/issues/new/choose) as required by the [contributing guide](https://github.com/digitalocean/netbox/blob/master/CONTRIBUTING.md). If you'd like to request that your issue be re-opened, please first update the content so that it matches the appropriate template (this may require rewriting your issue entirely).

**Comment by BegBlev** [comment]
This patch is a 4 lines source modification and is already ready and working in our Netbox instance.

**Comment by DanSheps** [comment]
Could you provide me with the patch here?  I would like to test this before we decide to accept/not accept.

**Comment by BegBlev** [comment]
You can directly get the modification from my netbox fork.
https://github.com/BegBlev/netbox
Branch is 'lldp-port-id'

If you prefer a patch file... just let me know.

Regards
Vince

**Comment by jeremystretch** [comment]
@BegBlev please submit a pull request with your changes adhering to the [contributing guide](https://github.com/netbox-community/netbox/blob/develop/CONTRIBUTING.md).
