### ISSUE TITLE
Cannot get Webhooks to work

### ISSUE THREAD

**Issue by gerpion** [netbox-community/netbox#3634]
### Environment
* Python version:  
* NetBox version:  

I'm trying to configure the Webhooks but then Netbox Worker service doesnt start

### Steps to Reproduce
1. Modify configuration.py => WEBHOOKS_ENABLED = True
2. restart services

3.

### Expected Behavior
root@MER-R1-NBX-001:/opt/netbox/netbox/netbox# supervisorctl restart netbox
netbox: stopped
netbox: started
root@MER-R1-NBX-001:/opt/netbox/netbox/netbox# supervisorctl restart netbox-rqworker
netbox-rqworker: stopped
netbox-rqworker: started

### Observed Behavior

I got a HTTP 503 error.

Thanks for your help

**Comment by lampwins** [comment]
Thank you for your interest in NetBox. GitHub issues are intended for reporting reproducible bugs and requesting features, and must be submitted using the template provided [here](https://raw.githubusercontent.com/digitalocean/netbox/develop/.github/ISSUE_TEMPLATE.md). For general discussion, questions, or assistance with installation issues, please post to our [mailing list](https://groups.google.com/forum/#!forum/netbox-discuss).
