### ISSUE TITLE
Connecting Interface to Rear Port half fails

### ISSUE THREAD

**Issue by millijuna** [netbox-community/netbox#3644]
### Environment
* Python version:  3.7.3
* NetBox version:  2.6.6

Connecting a device Interface to a patch panel rear port does not work correctly if that rear port is not associated with a front port. Netbox throws the following error:

<class 'ValueError'>

Connected endpoint must be an Interface or CircuitTermination, not <class 'dcim.models.RearPort'>.

The model becomes inconsistent in this state. The patch panel shows the rear port connected to the device interface, but the interface on the device does not show it as connected to the rear port. Likely the best behaviour here would be to prevent the user from making this connection (to an unconnected rear port) until it's associated with a front port.

### Steps to Reproduce
1. Create a patch panel with just a 110 punchdown rear port, and not associated with a front port
2. Create a simple device with a basic 8P8C interface
3. Connect the interface to the rear port on the patch panel
4. Observe the error
5. Look at the status of the patch panel and note that it shows the rear port as connected
6. Look at the status of the device, and note that it shows the interface as not connected.

### Expected Behavior

Either prevent the connection to the unassociated rear port, or allow it without the errors.

**Comment by DanSheps** [comment]
I am unable to reproduce this following the steps outlined.

Please review your steps to reproduce.

**Comment by millijuna** [comment]
Huh... 

Just walking through this right now:

1) Create a new 2U rack (named "Test Rack")
2) Create a new Generic Patch Panel in bottom U (named "Test Patch") at the start, it has no front/rear ports.
3) Create a rear port on the Generic Patch Panel (named it "Rear Port 20") of type 110, and 1 position.
4) Create a new generic device that is not in a rack (In my case, it's an access point, but that's largely irrelevant). 
5) On that device page create an interface (if it doesn't already exist, as it does in my template). In my case, "Gig 0"
6) Click on the "Connect" icon for that interface, and select "Rear Port" and navigate to the rear port created in step 3) above. Select Cat 5e for type, distance to say 50' and colour to blue.

And it blows up with the error as mentioned in the initial report.

it's relatively minor, as the problem goes away when that rear port is associated with a front port. It's mostly a problem with the initial workflow I was doing as I was documenting how my APs connect. I don't have my Patch Panel templates fully populated, as they often have 25 pair trunks hanging off the back, and the occasional AP direclty punched down on them.
