### ISSUE TITLE
Sort results when querying objects (such as IP Addresses) via the API

### ISSUE THREAD

**Issue by xucito** [netbox-community/netbox#3650]
### Environment
* NetBox version:  v2.3.5

### Proposed Functionality
When querying the API, the results should be sortablable via a sort attribute which will sort on the given field name.

This should function similar to the UI interface i.e. <url>/ipam/ip-addresses/?sort=tenant

Order by descending can specified using "-" before the field name.

### Use Case

Paging with a sort using the API Directly.

### Database Changes

None.

### External Dependencies

None.

**Comment by kobayashi** [comment]
Checked this in netbox 2.6.7 also. The straight forward way is just adding `filter_backends`, `ordering_fields` described in [django-rest-framework](https://www.django-rest-framework.org/api-guide/filtering/#orderingfilter), but not seems efficient to implement to all viewsets. :thinking: 

Any idea for this?

Here is a sample.
```
class IPAddressViewSet(CustomFieldModelViewSet):
    queryset = IPAddress.objects.prefetch_related(
        'vrf__tenant', 'tenant', 'nat_inside', 'interface__device__device_type', 'interface__virtual_machine',
        'nat_outside', 'tags',
    )
    serializer_class = serializers.IPAddressSerializer
    filterset_class = filters.IPAddressFilter

    # ADD THESE LINES
    filter_backends = [rest_filters.OrderingFilter]
    ordering_fields = ['id', 'vrf__tenant', 'tenant', 'nat_inside', 'interface__device__device_type', 'interface__virtual_machine',
'nat_outside', 'tags',]
```

**Comment by xucito** [comment]
Looks that is the easiest way to implement the ordering. You might be able to use the _meta API to get all the fields of the model object you are returning.

https://docs.djangoproject.com/en/2.2/ref/models/meta/#module-django.db.models.options

I do not use django so I just briefly looked at the docs.
