### ISSUE TITLE
User Permissions

### ISSUE THREAD

**Issue by Dustin-RW** [netbox-community/netbox#3653]
Using Chrome

### Environment
* Python version:  
* NetBox version:  v2.5.3

Creating a user, or group, without any user permissions still allows them to view content that should be either empty or blocked.

### Steps to Reproduce
1. As an Admin, create user or group
2. Dont provide any permissions, example: "Can view attached images" is NOT selected.  User set to active though
3.  Log out, and log in as new User
4. New User still able to see all information, Circuits, Racks, Attached Images.

**Comment by jeremystretch** [comment]
The current stable release of NetBox is v2.6.6. Please upgrade your installation and report back if you can reproduce this bug on the current release.
