### ISSUE TITLE
Add description field to role objects

### ISSUE THREAD

**Issue by soer7022** [netbox-community/netbox#3655]
### Proposed Functionality
In the current version of NetBox you can add comments to devices. This is convenient if you want to keep different information, that doesn't require custom fields.

However when creating a device role, such comments would also be useful, to describe behaviour and what the role is used for.

### Use Case
See section above

### Database Changes
Should require an added comment field to device-roles

### External Dependencies
None that I'm aware of

**Comment by Kosire** [comment]
I agree. We need this aswell since we have a ton of device roles where a description could help describe what the role is for.

**Comment by zacho112** [comment]
I agree on this!

**Comment by jeremystretch** [comment]
Reminder: Please use a :+1: reaction to show support for an issue. Individual comments are not reflected in any metric.

**Comment by jeremystretch** [comment]
Expanding the scope of this FR to include:

* RackRoles
* DeviceRoles
* ipam.Roles (prefixes/VLANs)
* SecretRoles
