### ISSUE TITLE
Add max_requests parameters to Gunicorn example config

### ISSUE THREAD

**Issue by tyler-8** [netbox-community/netbox#3658]
### Change Type
[X] Addition
[ ] Correction
[ ] Deprecation
[ ] Cleanup (formatting, typos, etc.)

### Proposed Changes

Related issue: https://github.com/netbox-community/netbox/issues/3598

As a general best practice with `gunicorn` webapps, it's a good idea to recycle the worker processes. This is done by using `max_requests` in the `gunicorn` config. It should be paired with `max_requests_jitter` to prevent all the gunicorn workers from being restarted at nearly the same time. 

I'd like to add these parameters to this section of the docs:
https://github.com/netbox-community/netbox/blob/develop/docs/installation/3-http-daemon.md#gunicorn-installation

```no-highlight
command = '/usr/bin/gunicorn'
pythonpath = '/opt/netbox/netbox'
bind = '127.0.0.1:8001'
workers = 3
user = 'www-data'
max_requests = 1000
max_requests_jitter = 200
```

**Comment by kobayashi** [comment]
This is good idea!
How about add the link to [gunicorn docs](https://docs.gunicorn.org/en/stable/settings.html#max-requests) also?
