### ISSUE TITLE
LLDP Neighbour portmap broken since Netbox 2.6.7

### ISSUE THREAD

**Issue by garnser** [netbox-community/netbox#3662]
### Environment
* Python version:  3.6.8
* NetBox version:  2.6.7
* Arista EOS

### Steps to Reproduce
1. Go into the LLDP Neighbour Tab of a DCIM with LLDP configured
2. Look at the port-map table 

### Expected Behavior
Expected and previous behaviour is that LLDP port-mapping retreived from the switch was populated in the table.

### Observed Behavior
Although the Napalm is still  function (retreiving config works for example). Netbox is no longer  populating the port-map table based on LLDP neighbours. This is true for all Napalm enabled devices.

This issue seams to be caused by https://github.com/netbox-community/netbox/pull/3645 which was introduced with 2.6.7, reverting the patch restores previous behaviour.

Old view:
<img width="1573" alt="Screenshot 2019-11-02 at 18 06 11" src="https://user-images.githubusercontent.com/3099060/68074504-f5605480-fd9b-11e9-8a6e-6ed4e85ad82d.png">

New view:
<img width="1570" alt="Screenshot 2019-11-02 at 18 07 32" src="https://user-images.githubusercontent.com/3099060/68074505-f8f3db80-fd9b-11e9-81f7-a6a65aad2cf6.png">

Log attached during page-load:
[lldp_neighbour_log.txt](https://github.com/netbox-community/netbox/files/3800867/lldp_neighbour_log.txt)

**Comment by garnser** [comment]
Log attached during page-load:

[lldp_neighbour_log.txt](https://github.com/netbox-community/netbox/files/3800729/lldp_neighbour_log.txt)

**Comment by garnser** [comment]
This issue seams to be caused by https://github.com/netbox-community/netbox/pull/3645 which was introduced with 2.6.7

**Comment by kobayashi** [comment]
Thanks to let us know this issue.
Could you let me know both versions?
- napalm version
- Arista EOS version

From [napalm docs](https://napalm.readthedocs.io/en/latest/support/index.html#getters-support-matrix), `get_lldp_neibors_detail` should work for all devices.
Napalm itself seems to support at least EOS version 4.15.0F.

**Comment by DanSheps** [comment]
@garnser Where does that log come from exactly?  It looks like the response from the ajax request but it doesn't correspond 100% to what I would expect.

Could you print out the exception from the ajax request?  If you want you can go to:

/api/dcim/devices/433/napalm/?method=get_lldp_neighbors_detail

**Comment by garnser** [comment]
As pointed out in the previous post the issue boiled down to SW version on the switch.

Daniel if you’d like I can perform the request you’ve mentioned, otherwise this can be closed.

________________________________

**Comment by DanSheps** [comment]
> As pointed out in the previous post the issue boiled down to SW version on the switch.

If you are confident of that, then all good
