### ISSUE TITLE
API filter by created, last_updated

### ISSUE THREAD

**Issue by struppinet** [netbox-community/netbox#3663]
### Environment
* Python version:  3.7.3
* NetBox version:  2.6.6

### Proposed Functionality

The date fields (created, last_updated) added in Version 2.3.0 should also be filterable.

### Use Case

Get a List of all Racks that have been changed > yyyy-mm-dd

### Database Changes

none

### External Dependencies

none added

**Comment by struppinet** [comment]
Working code:
```python
    created = django_filters.DateFilter()
    created__gt = django_filters.DateFilter(
        field_name='created',
        lookup_expr='gte'
    )
    created__lt = django_filters.DateFilter(
        field_name='created',
        lookup_expr='lte'
    )
    last_updated = django_filters.DateTimeFilter()
    last_updated__gt = django_filters.DateTimeFilter(
        field_name='last_updated',
        lookup_expr='gte'
    )
    last_updated__lt = django_filters.DateTimeFilter(
        field_name='last_updated',
        lookup_expr='lte'
    )
```

Will also create a Pull Request with the changes if accepted.

**Comment by jeremystretch** [comment]
I'll point out that if this is implemented, it must be implemented consistently for all models which have these fields (not just within DCIM). This is best done by creating a new class that the applicable existing FilterSets inherit.

@struppinet If you're willing to commit to this work I'm happy to assign this issue to you.

**Comment by struppinet** [comment]
I'm totally with you, just unsure about namings and implementation.

How about that?:
```python
class ChangeLoggedFilter(django_filters.FilterSet):
    created = django_filters.DateFilter()
    created__gte = django_filters.DateFilter(
        field_name='created',
        lookup_expr='gte'
    )
    created__lte = django_filters.DateFilter(
        field_name='created',
        lookup_expr='lte'
    )
    last_updated = django_filters.DateTimeFilter()
    last_updated__gte = django_filters.DateTimeFilter(
        field_name='last_updated',
        lookup_expr='gte'
    )
    last_updated__lte = django_filters.DateTimeFilter(
        field_name='last_updated',
        lookup_expr='lte'
    )

// example piece
class RackFilter(TenancyFilterSet, CustomFieldFilterSet, ChangeLoggedFilter):
```

**Comment by jeremystretch** [comment]
That looks good! I think it makes sense to have `exact`, `gte`, and `lte` filters for the `created` and `last_updated` fields as you have above. Marking this as accepted and assigning to you for a PR. Thanks!
