### ISSUE TITLE
Config context by tags

### ISSUE THREAD

**Issue by itmicus** [netbox-community/netbox#3664]
### Environment
* Python version:   3.7.3
* NetBox version:  2.6.6

### Proposed Functionality

Add to the config context assignment field with tags

### Use Case
I use the tag "monitored_by_zabbix" for devices and VMs wich will be monitoring in our Zabbix system.
I want to create config contex with config for Zabbix for this devices/vms

### Database Changes
Yes

### External Dependencies
None

**Comment by kobayashi** [comment]
Could you give us more detail of your usecase step-by-step?

**Comment by wfrced** [comment]
I believe I have a somewhat similar usecase, so will chime in.
With these changes I'd be able to:  

1. Get a list of hosts using Netbox plugin for Ansible;  
2. Create Ansible groups using tag names and add my hosts to these groups;  
3. Add tag's Config Context to group variables;
2. Create/Update hosts in Zabbix using Zabbix plugin for Ansible.  

Basically, it would allow me to use Config Contexts as Ansible groups.  
Or I could simply store a more general Zabbix config for, say, a Tenant or a Site, and use tag's CC to store a boolean - whether to enable monitoring for this host.

**Comment by kobayashi** [comment]
I am taking this
