### ISSUE TITLE
Clarify the setup instructions for rqworker

### ISSUE THREAD

**Issue by johnjwang** [netbox-community/netbox#3670]
### Change Type
[ ] Addition
[x] Correction
[ ] Deprecation
[ ] Cleanup (formatting, typos, etc.)

### Proposed Changes

On the [supervisord setup instructions](https://netbox.readthedocs.io/en/latest/installation/3-http-daemon/#supervisord-installation), it should be stated that if the `WEBHOOKS_ENABLED` setting is False, then `netbox-rqworker` should not be running. Otherwise, it can lead to performance issues as described in [this discussion](https://groups.google.com/d/topic/netbox-discuss/SrhbmNG6fvw/discussion). I suggest adding `autostart = false` to the `[program:netbox-rqworker]` configuration block to disable it.

Alternatively, `WEBHOOKS_ENABLED` is False in the default config as of v2.6.7 (9f7313e). If the intent was to enable webhooks by default, you may want to change that to True to help new users avoid this issue.

**Comment by jeremystretch** [comment]
This will be addressed in v2.7. Please see #3408.

**Comment by squigley** [comment]
Just wanted to add that this is still an issue in 2.6.12, but I acknowledge that it is not expected to be fixed until 2.7. Perhaps 2.6.13+ could have a note added to the configuration.py suggesting that it be enabled? as immediately setting  "WEBHOOKS_ENABLED = True", and doing nothing else immediately resolved the restarting/high CPU issue.
