### ISSUE TITLE
netbox-formula for saltstack

### ISSUE THREAD

**Issue by Ali-Yazdani** [netbox-community/netbox#3671]
### Change Type
[ ] Addition
Readme.md alternative installations:
Saltstack formula -> <https://github.com/Ali-Yazdani/netbox-formula>

### Proposed Changes
To expand alternative ways to installation the NetBox in environments that use the Saltstack.

**Comment by jeremystretch** [comment]
I've moved the alternative installation links to [the wiki](https://github.com/netbox-community/netbox/wiki/Community-Contributions) and added this project.

**Comment by joni1993** [comment]
May i suggest my alternative to this formula (https://github.com/joni1993/netbox-formula) which features automated tests, complete dynamic config generation, systemd support, autoupdate support and running netbox as seperate user.

**Comment by jeremystretch** [comment]
@joni1993 Thanks, I've added it [here](https://github.com/netbox-community/netbox/wiki/Community-Contributions)
