### ISSUE TITLE
Change IP/Prefix Import to use VRF Name instead of VRF RD

### ISSUE THREAD

**Issue by Wally1169** [netbox-community/netbox#3676]
### Environment
* Python version:  3.6.7
* NetBox version:  2.6.6

### Proposed Functionality
IP Prefix Import, VRF field currently only imports based on the RD assigned to the VRF.  Per Jeremy Stretch, this is because RD used to be a required field, but is no longer.  With Name now being the only required field on VRF, it might make more sense to import the VRF field of the IP Prefix using the VRF Name instead of the RD.

### Use Case
Simplified import for users using VRFs not for a situation involving RDs (i.e. MPLS) but instead using it to just group IP Prefixes into a logical grouping

### Database Changes
None known

### External Dependencies
None known

**Comment by Wally1169** [comment]
Addendum: this would also theoretically apply to the IP Address Import as well

**Comment by jeremystretch** [comment]
One issue here is that the VRF name is not unique, whereas the RD (if present) is.

**Comment by Wally1169** [comment]
That's an viable and excellent point

**Comment by jeremystretch** [comment]
This really hits on a recurring theme, where it would be nice to have control over the field through which we reference a related object. Maybe something like

```
vrf.name,prefix,status
FooBarVRF,192.0.2.0/24,Active
```

for importing by VRF name, and

```
vrf.rd,prefix,status
65000:123,192.0.2.0/24,Active
```

for importing by VRF RD. I'm not sure how complicated that would get as far as the CSV import form goes though. We'd also still need a default behavior for the field.

**Comment by Wally1169** [comment]
That's a really cool idea.  Hope you're able to implement it
