### ISSUE TITLE
How can i get the napalm username and password for naplam.

### ISSUE THREAD

**Issue by tariqulislam** [netbox-community/netbox#3677]
In documentation there is clear instruction how to get the napalm username and password. can you please explain how to get it. or how to create it.

**Comment by jeremystretch** [comment]
Thank you for your interest in NetBox. GitHub issues are intended for reporting reproducible bugs and requesting features, and must be submitted using one of the templates provided [here](https://github.com/digitalocean/netbox/issues/new/choose). For general discussion, questions, or assistance with installation issues, please post to our [mailing list](https://groups.google.com/forum/#!forum/netbox-discuss) instead.
