### ISSUE TITLE
IP losses interface assignment when edited trough an interface

### ISSUE THREAD

**Issue by benjaminwaas** [netbox-community/netbox#3679]
### Environment
* Python version:  python 3.6.7
* NetBox version:  netbox 2.6.7

Hello, The IP will lose its interface assignment when you edit it through a interface of a device.

steps to reproduce the issue:

* Go to device, e.g. /dcim/devices/<X>/
* Click on the interface *name* e.g. eth0; this takes you to /dcim/interfaces/<N>/
* On this page is a list of IP addresses.  Click one one of them; this takes you to /ipam/ip-addresses/<N>/edit/?interface=&return_url=

I have send this question to the mailing list and they told me this could be the fix:

"I think the interface is blank because "interface=" in the query string in the generated link.  If I manually change it to "interface=<N>" and refresh then it's fine."

What did you expect to happen?
IP keeps its interface assigment.

What happened instead?
IP loses its interface assignment

**Comment by kobayashi** [comment]
I can reproduce this issue v2.6.7. The link should be fixed.
