### ISSUE TITLE
Add ability to store attachments with Tenants

### ISSUE THREAD

**Issue by mgob** [netbox-community/netbox#3681]
### Environment
* Python version:  3.5.1
* NetBox version:  2.6.7

### Proposed Functionality
Add the ability to upload/store files and images that are associated with a tenant under that tenant.

### Use Case
Documentation related to a tenant such as network diagrams, support and escalation documents etc.

### Database Changes
Unsure of the database file structure, would presume either a flag or key would need to link to the tenant versus a rack/device attachment.

### External Dependencies
None

**Comment by ryanmerolle** [comment]
Per the [FAQ: Why Does Netbox Support Only Image Attachments](https://github.com/netbox-community/netbox/wiki/Frequently-Asked-Questions#user-content-why-does-netbox-support-only-image-attachments), I am not sure this will go anywhere.  You can create custom links per tenant linking to a document hosting tool.

**Comment by jeremystretch** [comment]
Please see #1039
