### ISSUE TITLE
Dockerized Netbox 2.6.7 + Napalm

### ISSUE THREAD

**Issue by rendxq** [netbox-community/netbox#3683]
Hello!
 I have some issue with collect data from Cisco devices via NETBOX+NAPALM. As I know there is set of napalm drivers in dockerized Netbox. In order to use it I've done NAPALM-configuration according to NETBOX-wiki (https://github.com/netbox-community/netbox-docker/wiki/NAPALM-Configuration), but it didn't help. Let me discribe situation.

### Environment
* NetBox version:  v.2.6.7

### Steps to Reproduce
1. Under Device content click on "Status"
![image](https://user-images.githubusercontent.com/27946443/68471851-a90c8d00-0251-11ea-9e3b-c44a853ffbc2.png)

### Expected Behavior
I expect to get status information...

### Observed Behavior
Recieve error window 
![image](https://user-images.githubusercontent.com/27946443/68472031-2f28d380-0252-11ea-8cbb-bb0745a4e3da.png)

In cisco log I see record where there isn't username
`%SEC_LOGIN-4-LOGIN_FAILED: Login failed [user: ] [Source: 192.168.xx.yy] [localport: 22] [Reason: Login Authentication Failed]`

Aslo if I connect to netbox-container console and do napalm's request to cisco I get correct result.
Example:
![image](https://user-images.githubusercontent.com/27946443/68472603-6c419580-0253-11ea-95c8-53f791495b48.png)

Need help!

**Comment by kobayashi** [comment]
Thank you for your interest in NetBox. GitHub issues are intended for reporting reproducible bugs and requesting features, and must be submitted using one of the templates provided [here](https://github.com/netbox-community/netbox/issues/new/choose). For general discussion, questions, or assistance with installation issues, please post to our [mailing list](https://groups.google.com/forum/#!forum/netbox-discuss) instead.
