### ISSUE TITLE
Device. LLDP Neighbors. No DATA

### ISSUE THREAD

**Issue by rendxq** [netbox-community/netbox#3686]
### Environment
* Netbox v2.6.7 docker container (https://hub.docker.com/layers/netboxcommunity/netbox/v2.6.7/images/sha256-fb35d5659e3810bd51e47de374a09d91e955a38f5a8065cad043dbd10efde683)
* Python version:  3.7.5.
* NetBox version:  2.6.7
* Cisco ISR 4431

### Steps to Reproduce
Click on "LLDP Neighbors" 

### Expected Behavior
Colums "LLDP Device" and "LLDP Interface" have to contain information 

### Observed Behavior
Colums "LLDP Device" and "LLDP Interface" are empty
![image](https://user-images.githubusercontent.com/27946443/68654786-47099b80-0561-11ea-9cdc-3dc92ca45670.png)

API shows me that request is OK and returns data:
![image](https://user-images.githubusercontent.com/27946443/68655483-addb8480-0562-11ea-99fd-22029d61d1f3.png)

Router sees LLDP neighbors:
```
RT-01#sh lldp neighbors
Capability codes:
    (R) Router, (B) Bridge, (T) Telephone, (C) DOCSIS Cable Device
    (W) WLAN Access Point, (P) Repeater, (S) Station, (O) Other

Device ID           Local Intf     Hold-time  Capability      Port ID
SW-2                 Gi0/0/0        120        B               Gi0/36
SW-2                 Gi0/0/1        120        B               Gi0/35

Total entries displayed: 2

```

**Comment by inetman28** [comment]
Also I note that in column "LLDP Interfaces" was added double quotes for interface item. Its behavior does not allow get true information about cable management in data center because line color is painted red. 

v2.6.7

![image](https://user-images.githubusercontent.com/45913745/68662542-13714600-054e-11ea-9c22-0a6fc707b153.png)

**Comment by kobayashi** [comment]
@rendxq napalm driver needs same interface name. Can you try the interface name in netbox from "Gi0/0/0" to "GigabitEthernet0/0/0" ?

**Comment by rendxq** [comment]
> @rendxq napalm driver needs same interface name. Can you try the interface name in netbox from "Gi0/0/0" to "GigabitEthernet0/0/0" ?

Good news!
I've chanched "Gi" to "GigabitEthernet" and it works. Thanks for advise.
I haven't known  about such behavie before. 
![image](https://user-images.githubusercontent.com/27946443/68736349-fe121f80-0612-11ea-8480-02572e19c03b.png)
