### ISSUE TITLE
Device info on hover

### ISSUE THREAD

**Issue by StevenRB** [netbox-community/netbox#3694]
### Environment
* Python version: 3.5.3 
* NetBox version: 2.6.1 

### Proposed Functionality

I would like to be able to see some basic data on hover on a device hostname. For example, if you're on the page of one device, it'd be nice to be able to hover over another device under related devices and see it's manufacturer, model, and primary IP

### Use Case
It would make it easier to get info at a glance. Hostnames aren't always as descriptive as we'd hope and it'd be nice to confirm some basic info about a device before we click it.

### Database Changes

None

### External Dependencies

None. This can all be done with existing functionality django/javascript

**Comment by jeremystretch** [comment]
This is something we might take on once we've moved to an API-driven UI, but the additional queries and Javscript hackery that would be required by the current UI implementation make this unpalatable. I'm going to close this as there's nothing we can do to address it in the near future in a manner that would be maintainable.
