### ISSUE TITLE
Missing A Side/Z Side Details in search results

### ISSUE THREAD

**Issue by harmey** [netbox-community/netbox#3695]
### Environment
* NetBox version:  2.6.6

### Steps to Reproduce
1. Create circuit A "TPG.1000M.CAN.BUN"
2. Add Termination Side A, Select any Site and Speed.
3. Add Termination Side B, Select any Site and Speed.
4. On Circuits Page, Search for "TPG.1000M", successful result showing A and Z Side site names.
5. From Global Search, Search for "TPG.1000M", results do not show A Size or Z Side site names.

What did you expect to happen?
The search results under the circuits heading should show the A Side and Z Side site name.

What happened instead?
The A Side and Z Side site names are blank (dash). If you click refine search and are taken to the circuits view the details are then visible. The other two fields, Tenant and Description do still show a value.

**Comment by jeremystretch** [comment]
Please revise your issue to state the exact values you're using both when creating the objects and when searching.

**Comment by harmey** [comment]
These are the steps I can reproduce the issue with.

1. Create circuit A "TPG.1000M.CAN.BUN"
2. Add Termination Side A, Select any Site and Speed.
3. Add Termination Side B, Select any Site and Speed.
4. On Circuits Page, Search for "TPG.1000M", successful result showing A and Z Side site names.
4. From Global Search, Search for "TPG.1000M", results do not show A Size or Z Side site names.

Note: The other two fields, Tenant and Description do still show a value.

**Comment by DanSheps** [comment]
Please update the main body of your issue.  I am going to re-open as I can confirm that this is a bug.
