### ISSUE TITLE
Doc error in custom_scripts

### ISSUE THREAD

**Issue by candlerb** [netbox-community/netbox#3697]
### Change Type
[ ] Addition
[X] Correction
[ ] Deprecation
[ ] Cleanup (formatting, typos, etc.)

### Proposed Changes

At [this point](https://netbox.readthedocs.io/en/latest/additional-features/custom-scripts/#script-attributes) is says there is a Meta attribute called `field_order`

But in [the example](https://netbox.readthedocs.io/en/latest/additional-features/custom-scripts/#example) it shows it as `fields`

One of these must be wrong.  By experimentation, the correct attribute is `field_order`

**Comment by hSaria** [comment]
@candlerb, are you gonna raise a PR for the correction or shall I?

**Comment by candlerb** [comment]
Please go ahead.
