### ISSUE TITLE
Provide a mode for API pagination backed by CursorPagination

### ISSUE THREAD

**Issue by ajknv** [netbox-community/netbox#3699]
### Environment
* Python version:  3.6.8
* NetBox version:  2.6.7

### Proposed Functionality
When making a GET request that will provide paginated results, have an additional query parameter option to request that the pagination be backed by DRFs CursorPagination instead of the current/default behavior of using LimitOffsetPagination.

### Use Case
The most specific use case is that of trying to delete all the records that match a particular query, wherein one issues the query and then iterates through all the results and makes delete requests on each corresponding ID. The current pagination behavior creates a subtle bug in this seemingly-straightforward approach, namely that as records are deleted from a given page, the offset for the next page request will now result in the skipping of other valid records; i.e. at the end of the full iteration not all of the records will be deleted. The overall algorithm thus has to be written to "converge" through multiple loops through the query-and-delete iteration until the query itself no longer returns any records. This is more cumbersome, and arguably can be viewed as a violation of the principle of least surprise for a fairly basic operation.

Attempts to work around the problem, such as by gathering all of the IDs on a first pass, also cannot be guaranteed to be reliable in the face of RW access by multiple clients/users. If another client issues a delete during the ID-gathering iteration, the current pagination mechanism will still cause some IDs to potentially be missed.

The problem also generalizes to any attempt to modify the state of (not just delete) all of a set of particular records matching a query, in the face of potential concurrent modification by multiple clients. This is actually even harder to deal with, as it may require implementing semantic-specific diff logic for each kind of update scenario and then verifying the effect on all target records using the same overall convergence approach.

As a separate but potentially significant point, the Django documention also notes that CursorPagination is the only approach with (roughly) constant-time scaling to larger datasets. Thus at least having the option of using it may become an important perf consideration for users with larger deployments managed in Netbox, which I would view as an independent positive of implementing this RFE.

### Database Changes
Nothing that I would anticipate.

### External Dependencies
None new that I would anticipate.

**Comment by DanSheps** [comment]
I see a few problems with moving to CursorPagination:

> The cursor-based pagination presents an opaque "cursor" indicator that the client may use to page through the result set. This pagination style only presents forward and reverse controls, and does not allow the client to navigate to arbitrary positions.

I would say that, this right here is a non-starter for moving to CursorPagination.

**Comment by ajknv** [comment]
Please note that this RFE is not requesting that the API move to CursorPagination in lieu of the current behavior, but merely to add support for it as an alternate option. Limitations that arise from choosing the alternate mode could of course simply be documented, allowing clients to assess the tradeoffs to any particular use case.

As to the unchanging value concern, seems like the queries could utilize the record (row) ID -- even if only internally -- for the key.

**Comment by ajknv** [comment]
RFE activity to preserve interest.

**Comment by DanSheps** [comment]
@ajknv Would you be willing to implement these changes as well as own the changes for a period of time (support, maintenance, etc)?

**Comment by ajknv** [comment]
Perhaps
