### ISSUE TITLE
Config contexts for tags

### ISSUE THREAD

**Issue by candlerb** [netbox-community/netbox#3704]
### Environment
* Python version:  3.5.2
* NetBox version:  2.6.7

### Proposed Functionality

Now that tags are objects which are visible and editable in their own right, I would like to be able to create Config Contexts on tags.

### Use Case

Tags are the only *generic* grouping mechanism which exists in Netbox.  A device can only belong to one Role, one Site, one Platform and one Tenant.

Roles are not always sufficiently fine-grained for applying configuration.  You don't want to have to create a separate role for every combination of tags (e.g. `Production_Database_Slave_Canary`)

### Database Changes

Extra column on tag: config context

### External Dependencies

None

**Comment by jeremystretch** [comment]
Is this a duplicate of #3664?

**Comment by candlerb** [comment]
Yes, sorry I hadn't noticed that other issue.
