### ISSUE TITLE
Prefix export fails when importing back in due to VRF name instead of RD

### ISSUE THREAD

**Issue by nomad-cyanide** [netbox-community/netbox#3707]
### Environment
* Python version: 2.7.5 - python3 = 3.6.8
* NetBox version: 2.6.7

### Steps to Reproduce
1. Make sure you have prefixes defined in a VRF other than Global and those VRF's have both name and RD defined
2. Open /ipam/prefixes/ 
3. Click Export to export all prefixes defined. Save file locally
4. Take a clean install of Netbox (I have a test instance) where VRF's are already defined. (also imported the same way from prod)
5. Open /ipam/prefixes/ 
6. Click Import and paste the contents of the export from step 3 into the import box
7. Watch it complain that VRF is not found. Because RD is not exported and Import-function expects RD to be defined.

To be able to export prefixes and import it into a clean Netbox installation for testing purposes.

Prefixes attached to other VRF's than Global could not be imported, because RD is not defined in the exported output. RD need to be included in the prefix-export output, rather than the VRF-name.

**Comment by jeremystretch** [comment]
This is addressed by #3676
