### ISSUE TITLE
Components are not included when exporting devices.

### ISSUE THREAD

**Issue by nomad-cyanide** [netbox-community/netbox#3708]
### Environment
* Python version: 2.7.5 - python3 = 3.6.8
* NetBox version:  2.6.7

### Steps to Reproduce
1. Open /dcim/devices/ and click Export. Save file locally
2. Take a clean install of Netbox (I have a test instance), where prerequisites are already imported, like sites, racks, etc etc. 
3. Open /dcim/devices/ and click import.
4. Paste the exported output from step 1 into the import-function.

Devices with all components the be imported into the test-instance.

Devices are imported, but without any of the components.

**Comment by jeremystretch** [comment]
This is intended behavior. It is not possible to express different models in the same CSV table.

**Comment by nomad-cyanide** [comment]
Well, that's disappointing. So what you are saying is, that there are no way to export the devices with all details attached? 
If that is true, that make exporting devices kind of useless.
