### ISSUE TITLE
[Help] netbox is not rendering correctly in any browser new install

### ISSUE THREAD

**Issue by AdamWorkAccount** [netbox-community/netbox#3710]
Hi,

I have installed the latest Netbox on the following infrastructure:

Ubuntu 18.0.4.3 
Apache 2.4.29
Pyhthon 2.7.15+

I have tried Netbox in internet explorer 11, latest chrome and Firefox and it loads as per the screenshot image

![Netbox Rendering](https://user-images.githubusercontent.com/21357223/69433321-4deb9780-0d33-11ea-9e2e-9a3e15c8739b.PNG)

This is my config in /etc/supervisor/conf.d/netbox.conf

[program:netbox]
command = gunicorn -c /opt/netbox/gunicorn_config.py netbox.wsgi
directory = /opt/netbox/netbox/netbox/
user = www-data

![Netbox conf](https://user-images.githubusercontent.com/21357223/69433648-e3872700-0d33-11ea-8ea8-4bf23bdfec85.PNG)

[program:netbox-rqworker]
command = python3 /opt/netbox/netbox/netbox/manage.py rqworker
directory = /opt/netbox/netbox/netbox/
user = www-data
~

![Netbox Conf1](https://user-images.githubusercontent.com/21357223/69433826-4c6e9f00-0d34-11ea-9626-161cce821110.PNG)

This is my config for /opt/netbox/gunicorn_config.py

command = '/usr/local/bin/gunicorn'
pythonpath = '/usr/bin/python'
bind = '127.0.0.1:8001'
workers = 3
user = 'www-data'
max_requests = 5000
max_requests_jitter = 500

![Componenet location](https://user-images.githubusercontent.com/21357223/69434000-a2434700-0d34-11ea-964b-ceaa2be43683.PNG)

Any help appreciated please, wearing my stress ball out !

Have tried rebooting which did not help

Thank you

--edit just to add it loaded fine when doing the test below

python3 manage.py runserver 0.0.0.0:8000 --insecure

**Comment by DanSheps** [comment]
Thank you for your interest in NetBox. GitHub issues are intended for reporting reproducible bugs and requesting features, and must be submitted using one of the templates provided [here](https://github.com/digitalocean/netbox/issues/new/choose). For general discussion, questions, or assistance with installation issues, please post to our [mailing list](https://groups.google.com/forum/#!forum/netbox-discuss) instead.
