### ISSUE TITLE
Using non-ascii characters in tags is not working

### ISSUE THREAD

**Issue by liisberg** [netbox-community/netbox#3714]
### Environment
* Python version:  3.6.8 
* NetBox version:  2.5.3 

### Steps to Reproduce
1. Add a tag to a prefix containing an non-ascii character.
Attachment 1: ![image](https://user-images.githubusercontent.com/2950767/69541004-643e6100-0f88-11ea-92e6-72b035574d6d.png)
2. The tag is added correctly and represented correctly in the UI. See attachment 1.
3. Non-ascii characters is removed from the tag when the URL is represented. 
Attachment 2: 
![image](https://user-images.githubusercontent.com/2950767/69541123-b7b0af00-0f88-11ea-8120-ae90635415a9.png)

### Expected Behavior
The expected behavior is that characters would not be present in URL (../ipam/prefixes/?tag=<tag>) when filtering with non-ascii characters, as they are not valid in an URL. However, searching for the tag should return the prefix(es) assign to the tag.

### Observed Behavior
Searching for an assigned tag including an non-ascii character does not yield any results. However, using the slug value, which does not contain non-ascii characters, the prefix(es) returned is correct.

Using the API it should be possible to filter by the full tag including non-ascii characters, since it is correctly represented:
`
{
            "id": 12,
            "name": "höst",
            "slug": "host",
            "tagged_items": 1
        },
`

**Comment by jeremystretch** [comment]
This is intended behavior. Tags are referenced by their slug values.
