### ISSUE TITLE
Improve the openapi definition of custom_fields

### ISSUE THREAD

**Issue by smutel** [netbox-community/netbox#3715]
### Environment
* Python version:  3.5.2
* NetBox version:  2.6.7

### Proposed Functionality
Currently custom_fields are described as below in the swagger.json:

```json
"custom_fields": {                                                      
  "title": "Custom fields",
  "type": "object"
},  
```

We this kind of definition, it's not easy to parse code retrieved from the api. In particular to develop a terraform provider or to use this plugin for openapi: https://github.com/dikhan/terraform-provider-openapi.

The author of this plugin suggest to define custom_fields as below:

```json
"custom_fields":
  "title": "Custom fields",  
  "type": "array"
    "items":
      $ref: '#/definitions/custom_fields'

  "custom_field":
    "type": "object"
    "properties":
      "property_name":
        "type": "string"
      "property_type":
        "type": "string"
      "property_value":
        "type": "string"
```

### Use Case

* Make easy the code to use this part of this API
* Automation

### Database Changes

I don't think so that a dabase change is needed.

### External Dependencies

Don't know.

**Comment by kobayashi** [comment]
Do want to add custom fields through api? or let me know more specific use case for this?

**Comment by smutel** [comment]
Creating a terraform provider for netbox.

**Comment by kobayashi** [comment]
Nice! Is it related to change the scheme though?  If that would be recommendation from your reference, please let me clear reason why that is recommended. Sorry but I am not familiar much with how to create a terraform provider.

**Comment by saper** [comment]
Yes, this could be improved, but custom fields are more complex than just name/value of a string.

There are 6 different types (https://netbox.readthedocs.io/en/stable/additional-features/custom-fields/) and there some rules that can be attached. It looks more complex that what is proposed here.

**Comment by saper** [comment]
It looks more complex like this - custom fields can have 6 types. For example, a boolean field will be returned by API like this:

```
    "custom_fields": {
        "test_field": null
      },
```

This will not work with something like `name`/`value`

**Comment by saper** [comment]
The question is - should swagger API definition change every time we add/delete a custom field?

**Comment by lampwins** [comment]
> The question is - should swagger API definition change every time we add/delete a custom field?

My take on this is yes. In NetBox methodology, custom fields are a part of the model schema and realistically change infrequently.

We could do this with a custom field inspector but the problem is it would require a DB query to get the field definitions. It has been proposed in the past that we switch the schema to be served as static content instead of being rendered on the fly, which would probably make this more feasible.

**Comment by saper** [comment]
>  It has been proposed in the past that we switch the schema to be served as static content instead of being rendered on the fly, which would probably make this more feasible.

Thank you. This makes perfect sense. An additional advantage of static API definitions is that it might be easier to version them - it should be possible to understand when and why the API has changed. 

This opens up a (remote) possibility to support multiple versions of API in the future at the same time.

(We are considering opening up netbox API to a wide range of internal consumers and it would be great to have ability to control the stability of the interface definitions somehow).
