### ISSUE TITLE
Connected endpoint must be an Interface or CircuitTermination, not <class 'dcim.models.RearPort'>.

### ISSUE THREAD

**Issue by robbagithub** [netbox-community/netbox#3716]
### Environment
* Python version: 3.7.3
* NetBox version: 2.6.7

### Steps to Reproduce
1. Add device into rack that contains Front ports and rear ports, mapped in a 1:1 relationship
2. 'Connect' first Front port by clicking on green plus sign
3. Choose 'Interface'
4. Search for device that has interfaces to be connected to 
5. Complete remaining options as seen in image below. 
6. Press 'Connect' and error appears.

### What did you expect to happen? 
1.  Front port to have a connection created to the interface of chosen switch without error page.

###  What happened instead? 
1. Error page delivered.
2. Front port connection created to the interface of chosen switch

Connection is created, however the error page is displayed.  I've tried creating rear port connections first however this still did not produce a clean addition of a link.

###  Screenshots
1. **Setup of ports on new patch panel**
![ports](https://user-images.githubusercontent.com/22147754/69601901-d5097a00-1069-11ea-9e4a-4364965d7bc4.jpg)

 2. **Connection creation**
![conndection creation](https://user-images.githubusercontent.com/22147754/69601974-0f731700-106a-11ea-8571-dd20a842fb78.jpg)

3. **Error Page**
![error_page](https://user-images.githubusercontent.com/22147754/69601986-17cb5200-106a-11ea-9e8c-c15fe20f4c69.jpg)

4.**Post error page, cables and connections created**
![connected_ports](https://user-images.githubusercontent.com/22147754/69602007-26196e00-106a-11ea-94ce-fe083a5d7d01.jpg)

**Comment by DanSheps** [comment]
Have you made any modifications to your code?  I have never seen this myself, but I will try and reproduce it on the current master branch.

**Comment by DanSheps** [comment]
I was unable to reproduce following the steps provided.  Please provide **exact** steps, with exact specifications of all devices, connections, etc involved.

**Comment by mskalecki** [comment]
It's odd to me that you have Rear Ports named "Front Port N".  I think the problem is that you've created both your Front and Rear ports as Rear ports.

I'm able to reproduce this issue when attempting to connect an interface to a Rear Port that doesn't have an associated Front port.

**Comment by robbagithub** [comment]
I've made no modifications to the code. 
The copper patch panel has 16 front ports 1:1 mapped to the rear port, hence that device has 16 front ports and 16 rear ports. 
In the screen shot above all rear ports are named "rear port" and all front ports are named front port.

I'll attempt to add more exact steps in next post

**Comment by robbagithub** [comment]
So 100% user error!! 

Thanks for the find there @mskalecki, the device type had been incorrectly created. 32 rear ports added instead of 16 front and 16 rear.  Apologies there.  This wasn't an issue in the other device types of patch panels where the ports had been added correctly. We're predominately 12 and 24 ports.

Apologies again and thanks for the assistance.
