### ISSUE TITLE
Circuits > Export > Comprehensive throws error

### ISSUE THREAD

**Issue by tlofreso** [netbox-community/netbox#3718]
### Environment
* Python version:  3.6.8
* NetBox version:  2.6.7

### Steps to Reproduce
1. Navigate to Circuits page
2. Click "Export > Comprehensive"

### Expected Behavior
Comprehensive export of circuits occurs.

### Observed Behavior
Netbox throws a bootstrap Danger message:
`There was an error rendering the selected export template (Comprehensive): 'circuits.models.Circuit object' has no attribute 'circuit'`

This happens whether you select circuits, or not prior to clicking the export button.

**Comment by jeremystretch** [comment]
> 2. Click "Export > Comprehensive"

This is a custom export template and not part of NetBox. You'll need to work with whomever in your organization authored the template to resolve the error.
