### ISSUE TITLE
Can't assign ip address to vm

### ISSUE THREAD

**Issue by rom5a** [netbox-community/netbox#3727]
### Environment
* Python version:  
* NetBox version:  

### Steps to Reproduce
1.
2.
3.

**Comment by rom5a** [comment]
when I try to add some ip address from drop down menu, I can't find any think.
But prefix and ip address created

**Comment by kobayashi** [comment]
Thank you for your interest in NetBox. GitHub issues are intended for reporting reproducible bugs and requesting features, and must be submitted using one of the templates provided [here](https://github.com/netbox-community/netbox/issues/new/choose). For general discussion, questions, or assistance with installation issues, please post to our [mailing list](https://groups.google.com/forum/#!forum/netbox-discuss) instead.
