### ISSUE TITLE
Add support for API-only custom fields

### ISSUE THREAD

**Issue by ananace** [netbox-community/netbox#3728]
### Environment
* Python version: 3.7.5
* NetBox version: 2.6.7

### Proposed Functionality

Add a flag for setting custom fields as API use only, to allow for better system interoperability without cluttering the UI with non-user editable fields.

### Use Case

We're looking at integrating NetBox into several internal systems, some of which all collaborate to build the full view of the devices we manage.  
Custom fields containing remote IDs has proven to work well for this, though the fields can be confusing for our users as they're only ever supposed to be filled in by automated API communication between the linked system.

### Database Changes

This would most likely require adding a new boolean field to the custom field table, if a field should be user-editable or only accessible by API.

**Comment by yarnocobussen** [comment]
This was previously rejected in #2132

**Comment by ananace** [comment]
Apparently I need to practice my google-fu a bit, didn't find that previous issue in any of my searches.

Unfortunately config contexts might not quite be able to fill the entire reason why we're looking to have API-only fields - as we're hoping to add mappings not only for devices, but also tenants, sites, racks, and possibly even more in the future.

**Comment by hSaria** [comment]
Another option would be to keep them in the web UI but show them under a collapsed section by default so the user will need to expand that section to see the details, so less visible clutter yet a consistent view in the web UI and the API (the reason #2132 got closed). It'd basically be a `conceal` toggle.

**Comment by lampwins** [comment]
As pointed out, this aligns with #2132

Note you can use the field label to "signal" that the field should not be modified by an operator in the UI.
