### ISSUE TITLE
Standardize naming of FilterSet classes

### ISSUE THREAD

**Issue by jeremystretch** [netbox-community/netbox#3729]
### Proposed Changes
Ensure that all child classes of Django's `FilterSet` class end in `FilterSet` (not just `Filter`) and rename the `filter` property on view classes to `filterset`.

### Justification
This makes for cleaner code and should help reduce confusion when distinguishing between a filter set and individual filters.

**Comment by hSaria** [comment]
Can I take a swing at this or would you prefer to do it yourself (you know the project more so you may notice other things to change while fixing this issue)?

Also, do you want to wait until after v2.7 before doing this? I imagine merging this change into `develop-2.7` would be a mess of conflicts and would probably miss a couple of new filters only present in v2.7.

**Comment by jeremystretch** [comment]
I'll take this on. It needs to be coordinated carefully to avoid invalidating other work. Thanks though!

**Comment by jeremystretch** [comment]
Merged into `develop-2.7`
