### ISSUE TITLE
Change names of vlan

### ISSUE THREAD

**Issue by Soeren-FT** [netbox-community/netbox#3734]
### Environment
* Python version:  3.6.9
* NetBox version:  2.6.7

### Proposed Functionality
Change the name of existing vlans.
![image](https://user-images.githubusercontent.com/51915902/70314849-949fbe00-1818-11ea-8eca-57769a5fa08b.png)

### Use Case
This function is useful when different people enter information and do not adhere to the naming convention. A second person could then correct these entries again.

**Comment by jeremystretch** [comment]
> Change the name of existing vlans.

This of course is already supported.
