### ISSUE TITLE
Add Power Panel or Power Feed Chaining or a Description Field to Power Panel

### ISSUE THREAD

**Issue by jlhuston** [netbox-community/netbox#3736]
### Environment
* Python version:  
* NetBox version:  

### Proposed Functionality
It would be useful to show chaining of electrical power as it flows from panel to subpanel (to distribution panel, etc.) before heading to individual feeds that are then connected to equipment.

An alternative solution would be to allow for a Markup description field on the Power Panel where I can add comments that describe the feed and then be able to search on it.

An alternate alternative would be to use a made up device to model circuit panels and daisychain feeds (similar to a PDU device), in which case, this is moot?

### Use Case
This will allow for answering questions about what is impacted if a major power line outage is expected (as in, "we're disconnecting the high-voltage feed to panel H1D3 on Friday; will that impact the data center?" We could then use this chain of connections to trace the output of H1D3 to one or more panels and one or more feeds to equipment in order to assess impacts).

It would also be useful to summarize power utilization (I saw another feature request in place for showing power utilization up and down the chain of power usage).

### Database Changes
For the relationship-based solution, allowing Power Panels to have a Power Port of their own that can connect to another Power Panel or Power Feed or device output (as in, a hardwired UPS or Transformer output).

For the description solution, the addition of a text field.

### External Dependencies
None

**Comment by jeremystretch** [comment]
The model is limited to Power Panel -> Power Feed -> PDU -> Device because representing facility power infrastructure is out of scope for NetBox, which is primarily a network management tool.

> An alternative solution would be to allow for a Markup description field on the Power Panel where I can add comments that describe the feed and then be able to search on it.

Please open a separate FR with a specific use case if you'd like to propose this.
