### ISSUE TITLE
Add Visual Subnet

### ISSUE THREAD

**Issue by rogerwiklund** [netbox-community/netbox#3737]
### Environment
* Python version:  3.7.5
* NetBox version:  2.6.7

### Proposed Functionality

Add support for Visual Subnet like phpIPAM does. Much easier to see what IPs are free, reserved, DHCP pool etc.
![visual_subnet](https://user-images.githubusercontent.com/7275992/70394338-a2aa3600-19f4-11ea-906d-f1c412693ef6.PNG)

### Use Case

Faster way of adding/editing IPs by clicking on the IP in the Visual Subnet.

**Comment by ananace** [comment]
A screenshot from how the InfoBlox IPAM displays a similar visual view - with some added clutter due to DHCP, DNS, and discovery features;
![Screenshot_20191209_101214](https://user-images.githubusercontent.com/534460/70422671-62869a00-1a6c-11ea-8911-298aac764b4c.png)

**Comment by hSaria** [comment]
I'll give this a try. It *should* be simple to implement.
