### ISSUE TITLE
Add an OS field to Virtual Machines

### ISSUE THREAD

**Issue by xelarate86** [netbox-community/netbox#3739]
### Environment
* Python version:  3.6.9
* NetBox version:  2.6.7

### Proposed Functionality
On the Virtual Machines page, add a field for Operating System. This would let my team keep track of our network environment and see what we're running in a smoother way than searching through comments.

### Use Case
Tracking VM state.

### Database Changes
Add field under Virtual Machines.

### External Dependencies
N/A

**Comment by kobayashi** [comment]
This is aleready possible with platform. It's described in [docs](https://netbox.readthedocs.io/en/stable/core-functionality/devices/#platforms)

**Comment by xelarate86** [comment]
@kobayashi Is there a way I can get that on the Virtual Machines Page?

**Comment by jeremystretch** [comment]
@xelarate86 The platform field is not included in the device or VM lists. It is not currently possible to customize table columns, however FR #492 is open for this.
