### ISSUE TITLE
Ability to add relations between device roles and prefix role

### ISSUE THREAD

**Issue by vsvetlov** [netbox-community/netbox#3743]
### Environment
* Python version:  3.5.4
* NetBox version:  2.6.7

### Proposed Functionality
Specific VLAN role and the associated prefix is usually used for specific types of servers. 
It would be really helpful to track this relationship. 
It is related to #3655 for a better definition of roles. The description field for prefix roles also would be useful.

### Use Case
Can be used in many cases.
For automated network allocation during server provisioning or to build ACLs. 

### Database Changes
Add one-to-many relationship between prefix roles table and device role table

**Comment by jeremystretch** [comment]
There is no relationship between devices and prefixes in NetBox, so this would not make sense.
