### ISSUE TITLE
IPAM Container Prefix Grouping with Tenants

### ISSUE THREAD

**Issue by a-d-v** [netbox-community/netbox#3748]
### Environment
* Python version:  2.7.15
* NetBox version:  2.6.8

### Steps to Reproduce
When adding overlapping scopes with different Tenants the container prefix grouping seems to not take into account the Tenant. Should different Tenants provide a logical border with grouping prefixes?

1. Create two parent prefixes with range 172.16.0.0/12, assign both to a different Tenant and set prefix type to Container
2. Add two child prefixes, one 172.17.24.0/24 and another 172.17.48.0/24. Assign one prefix to the first Tenant created in step 1, the other prefix to the other Tenant created in step 1
3. Notice that the grouping of the child subnets will not occur under the parent prefix with the same Tenant. They all will be grouped under one of the two parent prefixes randomly

### Expected Behavior
Grouping based on prefix within a tenant.

### Observed Behavior
![NetboxContainerGrouping](https://user-images.githubusercontent.com/44755022/70551716-57b92b80-1b78-11ea-8344-88332c40f577.PNG)

**Comment by jeremystretch** [comment]
Please provide a specific list of steps to recreate the reported behavior.

**Comment by a-d-v** [comment]
thank you, updated ticket with steps

**Comment by tyler-8** [comment]
I don't think Tenants are expected to be a border for overlapping prefixes. What you're describing would be better handled by the VRF functionality (which exists already). Notice you have both containers in the Global VRF. You could create a VRF with the name of the tenant if you need to break it up that way.

**Comment by a-d-v** [comment]
Okay, I guess that will also work in many cases. I was assuming tenant to be useful for segregation also when no VRFs are actually in use in different locations. But we could make "dummy vrfs".

**Comment by hSaria** [comment]
I think the tenancy system is meant to be administrative. The tenancy of an IP is indicative of who owns or uses it.
