### ISSUE TITLE
Unable to assign IP to interface

### ISSUE THREAD

**Issue by abrahamvegh** [netbox-community/netbox#3757]
### Environment
* Python version: 3.7.3
* NetBox version: 2.6.8

### Steps to Reproduce
1. From a Device with an Interface, click the ‘Add IP address’ button
2. Click the ‘Assign IP’ tab
3. Search for an IP
4. Click an IP in the search results

### Expected Behavior
The IP address link should contain the ID of the `interface` we are attempting to assign to.

### Observed Behavior
For IPs not currently assigned to an interface, the `interface` URL parameter is empty.  
For IPs currently assigned to an interface, the `interface` URL parameter is the ID of the interface it is currently assigned to, not the one we are attempting to assign to.

### Notes
It appears this was introduced by #3687. I’m not familiar enough with Python or the codebase to determine what the correct fix would be that would satisfy both the bug being addressed by that PR and this regression. In the meantime, it is still possible to assign an IP by manually inserting the ID of the correct interface into the link URL.

**Comment by kobayashi** [comment]
Thank you for letting me know.
Yes, that PR fixed to see correct ip assign information (device -> interface -> ip address), but makes this bug. I am taking this issue.
