### ISSUE TITLE
Add asset tag to the virtual machine model

### ISSUE THREAD

**Issue by josarts** [netbox-community/netbox#3758]
**Issue type**
[x] Feature request
[ ] Bug report
[ ] Documentation

**Environment**
Python version: N/A
NetBox version: N/A

**Description**
Add asset tag to the virtual machine model 

**Use case**
like other assets (devices, rack) it helps to uniquely identify a given virtual machine.
This Asset tag could be fill by an UUID or an instance id.

**Comment by jeremystretch** [comment]
Asset tags are used to track physical assets only, thus they do not apply to VMs. You might use a custom field if you need something analogous to asset tags for virtual resources.
