### ISSUE TITLE
Add a "How do I..." section to the documentation

### ISSUE THREAD

**Issue by jeremystretch** [netbox-community/netbox#3759]
### Change Type
[x] Addition
[ ] Correction
[ ] Deprecation
[ ] Cleanup (formatting, typos, etc.)

### Proposed Changes
Introduce a new section in the documentation featuring example solutions for common use cases that might not be immediately apparent. Some example "How do I..." topics include:

* Model a fabric extender switch?
* Combine multiple prefixes into a single, large prefix?
* Represent data center power distribution?
* Create a device type for patch panels?
* Import circuits and their terminations?

**Comment by nathbooth** [comment]
I would suggest also;
- Front and rear ports on devices
- Device Bays on devices

**Comment by jeremystretch** [comment]
This should be a really good opportunity for volunteers to contribute without having to code.
