### ISSUE TITLE
Add "copy to clipboard" button for API tokens

### ISSUE THREAD

**Issue by jeremystretch** [netbox-community/netbox#3761]
### Environment
* Python version: 3.6.8
* NetBox version: 2.6.8

### Proposed Functionality
Add a "copy to clipboard" button next to the edit and delete buttons on a user's API token. (This functionality already exists in other areas of the UI.)

### Use Case
This makes it slightly more convenient to copy an API token.

### Database Changes
None

### External Dependencies
Nothing new

**Comment by hSaria** [comment]
Shall I take care of that? I've added the copy button for the secrets so I figure this should be fairly straight-forward.

**Comment by jeremystretch** [comment]
@hSaria Go for it!
