### ISSUE TITLE
Datetime picker

### ISSUE THREAD

**Issue by hSaria** [netbox-community/netbox#3762]
### Environment
* Python version:  3.6.3
* NetBox version:  2.6.8

### Proposed Functionality
Add a datetime selector to all datetime input fields.

### Use Case
Simplifies the process of specifying a date, especially considering the current implementation relies on a human to match the format. Examples of this:

* Change Log search form
* Aggregates' created field
* Circuits' install date field
* Users' token expire field

### Database Changes
None

### External Dependencies
Probably going to need a JS library for that, like [flatpickr](https://github.com/flatpickr/flatpickr) or something else.

**Comment by steffann** [comment]
I can see the usefulness of this. I'd be willing to implement this is it gets accepted.

**Comment by hSaria** [comment]
Same here; was waiting for this to be accepted before I put any work into it. Understandably, there are better things to focus on. This is just a QoL change.

**Comment by hSaria** [comment]
If anyone has any suggestions for the library to use, I’m all ears. Going to use some clean, maintained, modern library; no preference really.
