### ISSUE TITLE
Expose API_SELECT widget to custom scripts.

### ISSUE THREAD

**Issue by pszulczewski** [netbox-community/netbox#3766]
### Environment
* Python version:  3.6.8
* NetBox version:  2.6.6

### Proposed Functionality
Add more advanced ObjectVar filtering mechanism in Custom Scripts.
Custom script to use widgets like API_SELECT to relate second ObjectVar on already selected first ObjectVar.

### Use Case
Use Case 1
Two ObjectVars
1st Device
2nd Interfaces
Second ObjectVar is limited to interfaces only for selected device in first ObjectVar

Use Case 2
Two ObjectVars
1st Site
2nd Device
Second ObjectVar is limited to Devices only for selected site in first ObjectVar

### Database Changes
None

### External Dependencies
None

**Comment by lampwins** [comment]
We need to do this but I am not sure our current widget API will work very well. We likely need to investigate modifying it or creating a new one for use with custom scripts.

**Comment by DanSheps** [comment]
I have managed to expost the widget API for my own custom scripts, I will have to see what changes I made.  I believe I simply had it inherit something additional.

**Comment by DanSheps** [comment]
Yeah, it looks like I just created separate classes within the individual scripts:

```

class WidgetIntegerVar(IntegerVar):
    def __init__(self, widget, required=False, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.field_attrs['widget'] = widget
        self.field_attrs['required'] = required

    def as_field(self):
        """
        Render the variable as a Django form field.
        """
        form_field = self.form_field(**self.field_attrs)
        form_field.widget.attrs['class'] += ' form-control'

        return form_field


class WidgetObjectVar(ObjectVar):
    def __init__(self, queryset, widget, *args, **kwargs):
        super().__init__(queryset, *args, **kwargs)
        self.field_attrs['widget'] = widget

    def as_field(self):
        """
        Render the variable as a Django form field.
        """
        form_field = self.form_field(**self.field_attrs)
        form_field.widget.attrs['class'] += ' form-control'

        return form_field


class WidgetMultipleObjectVar(WidgetObjectVar):
    form_field = forms.ModelMultipleChoiceField


class ChoiceVar(ScriptVariable):
    form_field = forms.ChoiceField

    def __init__(self, choices, widget=StaticSelect2(), *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.field_attrs['widget'] = widget
        self.field_attrs['choices'] = choices

    def as_field(self):
        """
        Render the variable as a Django form field.
        """
        form_field = self.form_field(**self.field_attrs)
        form_field.widget.attrs['class'] += ' form-control'

        return form_field
```

**Comment by pszulczewski** [comment]
Hi Daniel,

Thanks for sharing the code.
I added the second class to the custom script and APISelect works fine.
```
    upstream_port = WidgetObjectVar(
        queryset=Interface.objects.all(),
        widget=APISelect(
            api_url="/api/dcim/interfaces/",
            disabled_indicator='cable',
            additional_query_params={
                'kind': 'physical',
                'device_id': '75',
            }
        )
    )
```
But the problem is that device ID above is static and I would like to dynamically pass device id depending on previously selected device in another ObjectVar.
All ObjectVars seems to be added to "data" upon running the script, but I don't see any method accessing them before the script is run to pass device_id to the widget.

**Comment by DanSheps** [comment]
@pszulczewski  Please take any help requests to the discussion group.

**Comment by DanSheps** [comment]
I am going to  take this on (unless someone else wants to give it a shot).
