### ISSUE TITLE
Unable to assign IP Address to interface

### ISSUE THREAD

**Issue by clatini** [netbox-community/netbox#3769]
### Environment
* Python version:  3.7.3 
* NetBox version:  2.6.8 

### Steps to Reproduce
1. In IPAM/IP Addresses, create a new IP Address; populate only mandatory fields (Address, Status);
2. In Devices, select an existing device, then select an existing interface and select '+' icon to add an IP Address;
3. Now, click 'Assign IP' Tab, then search for the previously created IP Address;
4. In the list, the IP Address link is something like this:

http://netbox.test.local/ipam/ip-addresses/395/edit/?interface=&return_url=/ipam/ip-addresses/assign/

### Expected Behavior

The 'interface' field in the URL must reference the interface id

### Observed Behavior

The 'interface' field is blank

Note: If the ip address is already assigned, the 'interface' field is correctly referenced.

**Comment by kobayashi** [comment]
Thank you for opening this issue. This is duplicated issue with #3757 which was fixed. Please see it for the detail.
