### ISSUE TITLE
Circuit search filter does not work properly

### ISSUE THREAD

**Issue by lmgonzalezl** [netbox-community/netbox#3771]
### Environment
* Python version:  3.5
* NetBox version: 2.6.8 

### Steps to Reproduce
When trying to filter by region or site the search does not work, it shows zero records.

### Expected Behavior
Show records that match the filter

### Observed Behavior
There are no problems with the records even when there is information that matches the filter applied

**Comment by jeremystretch** [comment]
Please outline the specific steps need to reproduce the reported behavior, including circuit creating and the filter value(s) you are using.

**Comment by lmgonzalezl** [comment]
I have several circuits associated with different tenants

![image](https://user-images.githubusercontent.com/51785108/70923359-aefb4800-201f-11ea-89d5-d84bbc10b2aa.png)

I don't see how to associate circuits with regions and sites. In any case, the tenants should be associated with a site so that the relationship  can exist "circuit <-> Tenant <-> region".

Example. Circuit 386******640 is associated to the tenant LCR-01 that corresponds to the port of the Christians. If I apply the Region: Puerto de los Cristianos filter, the search does not yield results

![image](https://user-images.githubusercontent.com/51785108/70924077-dbfc2a80-2020-11ea-9eb1-8af03a4745e6.png)

![image](https://user-images.githubusercontent.com/51785108/70924153-f6ce9f00-2020-11ea-8da4-0dbf4c9d95b8.png)

**Comment by tyler-8** [comment]
A `Circuit` is associated to a `Site` by creating a `CircuitTermination` that is attached to the `Site`. A `Circuit` by itself does not associate with a `Site`.

`Site` can be attached to `Region`. The `Tenant` doesn't come in to play at all in the `Region` relationship.

The site `SC5 - Edificio JOP` needs to attached to the `Los Cristianos` region in order for the filter to show the `38100001066107` circuit.

**Comment by jeremystretch** [comment]
Hopefully @tyler-8's explanation above addresses the confusion. If not, please start a thread on our [mailing list](https://groups.google.com/forum/#!forum/netbox-discuss). Closing this out as it does not appear to be a bug.
