### ISSUE TITLE
Possible bug or I am going crazy...

### ISSUE THREAD

**Issue by cfox1455** [netbox-community/netbox#3773]
We have putting in a lot of our prefixes into Netbox over the past few days, and we have one that will just not show up as a "valid" prefix, even though it is, and all the existing ones and free areas overlap properly.  Anyone have any ideas?  We are basically trying to add the prefix as a /28 and it keeps saying it is invalid, but I don't see any data to support that.  Thanks!

**Comment by LBegnaud** [comment]
what `/28` are you trying to add? Perhaps you aren't using the network number. Also your issue will likely be closed for not following the format requirements.

**Comment by cfox1455** [comment]
Sorry, didn’t know I had done that.  I have a large /22 that is broken up into /29s, 28s, etc.  This falls right along those lines as it should and those around it do as well, but it just won’t take it.


Christopher Fox
Chief Technology Officer
[cid:IdealIntegrations_ee791edc-fea4-4fa0-a108-e8f88152f341.png]
Ideal Integrations, Inc. | 800 Regis Avenue | Pittsburgh, PA 15236
E-Mail: cfox@idealintegrations.net<mailto:cfox@idealintegrations.net> | Phone: 412-349-6680 x1111 | Direct: 412-349-6666
Web: http://www.idealintegrations.net<http://www.idealintegrations.net/> | Service Desk: 412-349-6678 | Fax: 412-349-6670

**Comment by jeremystretch** [comment]
Thank you for your interest in NetBox. GitHub issues are intended for reporting reproducible bugs and requesting features, and must be submitted using one of the templates provided [here](https://github.com/digitalocean/netbox/issues/new/choose). For general discussion, questions, or assistance with installation issues, please post to our [mailing list](https://groups.google.com/forum/#!forum/netbox-discuss) instead.
