### ISSUE TITLE
LDAP cannot be disabled

### ISSUE THREAD

**Issue by xucito** [netbox-community/netbox#3776]
### Environment
* Python version:  
2.7
* NetBox version:  
2.3.5

### Steps to Reproduce
1. Enable LDAP by adding the `ldap_config.py` as defined by [docs](https://netbox.readthedocs.io/en/stable/installation/4-ldap/)
2. Access Netbox successfully using a LDAP user
3. Remove the `ldap_config.py` file
4. Restart Netbox
5. Try login, Netbox will still try access the LDAP server first before searching for local application users

### Expected Behavior
LDAP authentication will not be attempted

### Observed Behavior
Logs show that LDAP server is trying to be contacted

### Note
This is especially an issue for situations where the LDAP provider becomes unavailable as the attempt to contact the LDAP server has a longer timeout then the default gunicorn timeout therefore login attempts will fail with a 502 result.

This can be diagnosed by then running the Netbox in test mode via the console

**Comment by jeremystretch** [comment]
> NetBox version: v2.3.5

This is a very old release. Please upgrade to the current stable release (v2.6.9) and ask to re-open this issue if you are still able to reproduce the reported problem.
