### ISSUE TITLE
smallint is too small for dcim_powerfeed.available_power

### ISSUE THREAD

**Issue by zenches** [netbox-community/netbox#3781]
### Environment
* Python version:  3.7.3
* NetBox version:  v2.6.9

### Proposed Functionality
Change datatype for column available_power to integer.

### Use Case
smallint for available_power is not enough, when i creating new power feed with parameters:
- Voltage: 380
- Amperage: 63
- Phase: Three-phase

These options corresponds to my UPS manual and implemented on my datacenter.
Changing data type to integer helps me.

### Database Changes
`netbox=# ALTER TABLE dcim_powerfeed ALTER COLUMN available_power SET DATA TYPE integer;`

### External Dependencies
Probably, no dependencies.

**Comment by DanSheps** [comment]
Thank you for submitting this issue, however it appears that this topic has already been raised. Please see issue #3706  for further discussion.
