### ISSUE TITLE
Http Deamon

### ISSUE THREAD

**Issue by abdulbaazit** [netbox-community/netbox#3785]
I would be appreciate if the documentation for http deamon would be improve, as the documentation are not clear and my configuration are stuck in the middle.

NGINX configuratio is not clear for e.g. 

1. config file name  ? No config file name mentioned ?
2./etc/nginx/sites-available/netbox    this directory doesn't exist after installation. 
             a.  I still created this sites-available directory manually, however next steps doesn't imply for e.g. to delete default
             b. i create nebox file and paste the config content as mention in the documentations, but its not not applicable i guess ?
             c.  There is conf.d directory which is empty
[root@sendbox conf.d]# pwd
/etc/nginx/conf.d
[root@sendbox conf.d]# ll
total 0
            d , there is
[root@sendbox default.d]# pwd
/etc/nginx/default.d
[root@sendbox default.d]# ll
total 0

P.S my Linux Machine is Centos 8 . thx

Regards,
a.baazit

for example no documentation details for httpd in Centos/RHEL and i am using specifically HTTPD not Apache what will configuration details  ? 

### Change Type
[ ] Addition
[ ] Correction
[ ] Deprecation
[ ] Cleanup (formatting, typos, etc.)

**Comment by kobayashi** [comment]
Thank you for your interest in NetBox. GitHub issues are intended for reporting reproducible bugs and requesting features, and must be submitted using one of the templates provided [here](https://github.com/digitalocean/netbox/issues/new/choose). For general discussion, questions, or assistance with installation issues, please post to our [mailing list](https://groups.google.com/forum/#!forum/netbox-discuss) instead.
