### ISSUE TITLE
nginx incomplete configuration 

### ISSUE THREAD

**Issue by abdulbaazit** [netbox-community/netbox#3786]
Hi All,

I am new into the Netbox.i am having a problem while configuration http deamon (nginx).

1. After nginx installation there is no sites-available directory inside /etc/nginx which is mentioned by documentation ? -- > /etc/nginx/sites-available/netbox.
2. I created sites-available directory manually.
3. I created netbox file manually and pasted the content as per the documentation.
4. Can not delete "default".

Can some body please help me to explain which file suppose to be add the configuration for nginx to be able to read the nebox pages and its configuration.
I got nginx.conf file

I Got conf.d directory inside.
nclude /etc/nginx/conf.d/*.conf;
    server {
        listen       80 default_server;
        listen       [::]:80 default_server;
        server_name  _;
        root         /usr/share/nginx/html;

        # Load configuration files for the default server block.
        include /etc/nginx/default.d/*.conf;

        location / {
        }

root@sendbox nginx]# ll
total 68
drwxr-xr-x 2 root root    6 Oct  8 05:18 conf.d
drwxr-xr-x 2 root root    6 Oct  8 05:18 default.d
-rw-r--r-- 1 root root 1077 Oct  8 05:17 fastcgi.conf
-rw-r--r-- 1 root root 1077 Oct  8 05:17 fastcgi.conf.default
-rw-r--r-- 1 root root 1007 Oct  8 05:17 fastcgi_params
-rw-r--r-- 1 root root 1007 Oct  8 05:17 fastcgi_params.default
-rw-r--r-- 1 root root 2837 Oct  8 05:17 koi-utf
-rw-r--r-- 1 root root 2223 Oct  8 05:17 koi-win
-rw-r--r-- 1 root root 5170 Oct  8 05:17 mime.types
-rw-r--r-- 1 root root 5170 Oct  8 05:17 mime.types.default
-rw-r--r-- 1 root root 2469 Oct  8 05:17 nginx.conf
-rw-r--r-- 1 root root 2656 Oct  8 05:17 nginx.conf.default
-rw-r--r-- 1 root root  636 Oct  8 05:17 scgi_params
-rw-r--r-- 1 root root  636 Oct  8 05:17 scgi_params.default
drwxr-xr-x 2 root root   20 Dec 24 12:56 sites-available
-rw-r--r-- 1 root root  664 Oct  8 05:17 uwsgi_params
-rw-r--r-- 1 root root  664 Oct  8 05:17 uwsgi_params.default
-rw-r--r-- 1 root root 3610 Oct  8 05:17 win-utf

[root@sendbox conf.d]# ll ../default.d/
total 0
[root@sendbox conf.d]# ll ../conf.d/
total 0

### Proposed Changes

Please help me to solve this problem as i am stuck with the configurations. thx

**Comment by DanSheps** [comment]
Thank you for your interest in NetBox. GitHub issues are intended for reporting reproducible bugs and requesting features, and must be submitted using one of the templates provided [here](https://github.com/digitalocean/netbox/issues/new/choose). For general discussion, questions, or assistance with installation issues, please post to our [mailing list](https://groups.google.com/forum/#!forum/netbox-discuss) instead.
