### ISSUE TITLE
API endpoint for NetBox (or API) version

### ISSUE THREAD

**Issue by richardtector** [netbox-community/netbox#3787]
### Environment
* Python version:  3.6.8
* NetBox version:  2.6.9

### Proposed Functionality
As changes are often made to the API data models, it would be useful to be able to check the NetBox version programmatically in order that integrations can modify their behaviour, accordingly. Perhaps GET /api/netbox/version, or GET /api/netbox could return the version plus any other relevant bits of information about the installation.

Alternatively the API could be versioned, however this might limit development flexibility.

### Use Case
A recent example that caught me out going from 2.4 to 2.6 was the prefix address family being just a number in the JSON in 2.4 changing to an object with 'value' and 'label' keys. This broke an integration that I had written. Where to check in the JSON could be modified according to the NetBox version.

### Database Changes
None expected.

### External Dependencies
None expected.

**Comment by markkuleinio** [comment]
Each API call (like http://netbox.example.com/api) response has an `API-Version` header included. See an example of `pynetbox` usage in https://github.com/netbox-community/netbox/issues/3416#issuecomment-565806949.

**Comment by kobayashi** [comment]
Yes, the current version can be found in response headers. Thanks @markkuleinio
