### ISSUE TITLE
Partial search for inventory items

### ISSUE THREAD

**Issue by aventrax** [netbox-community/netbox#3788]
### Environment
* Python version:  3.6.3
* NetBox version:  2.6.9

### Steps to Reproduce
1. Add an inventiry item with an "asset tag" like this: cespite001
2. Search for it with a partial match via API: https://netbox.local/api/dcim/inventory-items/?q=cespite 

### Expected Behavior
The item should be found.

### Observed Behavior
The item is not found.

**Comment by DanSheps** [comment]
Unlink devices, the query on inventory items uses exact string insensitive match for searching.

This should be changed to match devices in how they search the asset tag for a partial match
