### ISSUE TITLE
how can I fill in IP address for a device

### ISSUE THREAD

**Issue by bybai** [netbox-community/netbox#3791]
### Environment
* Python version:  3.6 
* NetBox version:  latest 

### Steps to Reproduce
I am a fresh man, I have a try to netbox, but I hit problems, thanks for your help about the following questions.
1. when I add devices and IP addresses, how can I assign an IP address to a device. I cannot find a edit for a IP address.
2. how can I add interfaces?

**Comment by DanSheps** [comment]
Thank you for your interest in NetBox. GitHub issues are intended for reporting reproducible bugs and requesting features, and must be submitted using one of the templates provided [here](https://github.com/digitalocean/netbox/issues/new/choose). For general discussion, questions, or assistance with installation issues, please post to our [mailing list](https://groups.google.com/forum/#!forum/netbox-discuss) instead.
