### ISSUE TITLE
CSRF when switching to HTTPS

### ISSUE THREAD

**Issue by misch42** [netbox-community/netbox#3792]
I installed netbox on a fresh CentOS8. All according to the install guide. nginx as frontend. when I switch from HTTP to HTTPS in nginx.conf I get CSRF verification failed, request aborted on every POST request.

### Environment
```
# python --version
Python 3.6.8

netbox cloned on Dec 22th.

### Steps to Reproduce
nginx.conf: listen 80;

eveything works.

when switching to listen 443 ssl;

I get "CSRF verification failed, request aborted" on login and other POST request.

**Comment by DanSheps** [comment]
Thank you for your interest in NetBox. GitHub issues are intended for reporting reproducible bugs and requesting features, and must be submitted using one of the templates provided [here](https://github.com/digitalocean/netbox/issues/new/choose). For general discussion, questions, or assistance with installation issues, please post to our [mailing list](https://groups.google.com/forum/#!forum/netbox-discuss) instead.
