### ISSUE TITLE
The proxy server could not handle the request GET /dcim/sites/add/.

### ISSUE THREAD

**Issue by kasatka231** [netbox-community/netbox#3794]
[netbox_log.txt](https://github.com/netbox-community/netbox/files/4004952/netbox_log.txt)
<img width="960" alt="netbox_error" src="https://user-images.githubusercontent.com/42998974/71512777-b08f0080-28a8-11ea-9b80-bd6ff0edd2c1.png">

[Fri Dec 27 03:12:46.018138 2019] [proxy_http:error] [pid 6530:tid 140174033938176] (20014)Internal error (specific information not available): [client x.x.x.x:43488] AH01102: error reading status line from remote server 127.0.0.1:8001, referer: http://netbox/
[Fri Dec 27 03:12:46.018203 2019] [proxy:error] [pid 6530:tid 140174033938176] [client x.x.x.x:43488] AH00898: Error reading from remote server returned by /dcim/sites/add/, referer: http://netbox/
[Fri Dec 27 03:29:07.873674 2019] [proxy_http:error] [pid 7243:tid 140610241488640] (20014)Internal error (specific information not available): [client x.x.x.x:43490] AH01102: error reading status line from remote server 127.0.0.1:8001
[Fri Dec 27 03:29:07.873746 2019] [proxy:error] [pid 7243:tid 140610241488640] [client x.x.x.x:43490] AH00898: Error reading from remote server returned by /dcim/sites/add/
[Fri Dec 27 03:34:59.536749 2019] [proxy_http:error] [pid 7456:tid 140610350593792] (20014)Internal error (specific information not available): [client x.x.x.x:43510] AH01102: error reading status line from remote server 127.0.0.1:8001, referer: http://netbox/dcim/sites/
[Fri Dec 27 03:35:29.730714 2019] [proxy_http:error] [pid 7456:tid 140610495588096] (20014)Internal error (specific information not available): [client x.x.x.x:43514] AH01102: error reading status line from remote server 127.0.0.1:8001, referer: http://netbox/dcim/sites/
[Fri Dec 27 03:35:29.730768 2019] [proxy:error] [pid 7456:tid 140610495588096] [client x.x.x.x:43514] AH00898: Error reading from remote server returned by /dcim/sites/add/, referer: http://netbox/dcim/sites/
[Fri Dec 27 03:46:33.191998 2019] [proxy_http:error] [pid 9116:tid 140458785240832] (20014)Internal error (specific information not available): [client x.x.x.x:43562] AH01102: error reading status line from remote server 127.0.0.1:8001, referer: http://netbox/
[Fri Dec 27 04:29:08.761711 2019] [proxy_http:error] [pid 9116:tid 140458239977216] (20014)Internal error (specific information not available): [client x.x.x.x:43584] AH01102: error reading status line from remote server 127.0.0.1:8001, referer: http://netbox/dcim/sites/
[Fri Dec 27 04:29:08.761782 2019] [proxy:error] [pid 9116:tid 140458239977216] [client x.x.x.x:43584] AH00898: Error reading from remote server returned by /dcim/sites/add/, referer: http://netbox/dcim/sites/

**Comment by jeremystretch** [comment]
Thank you for your interest in NetBox. GitHub issues are intended for reporting reproducible bugs and requesting features, and must be submitted using one of the templates provided [here](https://github.com/digitalocean/netbox/issues/new/choose). For general discussion, questions, or assistance with installation issues, please post to our [mailing list](https://groups.google.com/forum/#!forum/netbox-discuss) instead.
