### ISSUE TITLE
How to run python script from local machine to netbox nbshell ?

### ISSUE THREAD

**Issue by ranjeetjangra** [netbox-community/netbox#3795]
Hi Experts ,
I have installed Netbox docker in my Centos server .
I want to execute my python script from local machine into nbshell , how can i do that .
I prepared the python script for bulk import (data from csv file to netbox nbshell )

Method 1:
I tried ./manage.py < script.py
This method reads script.py line by line and fires at nbshell irrespective of its a class or a function (unlike python interpreter)

Method 2
I tried by saving my script in PYTHONPATH folder and importing my main function into nbshell
that way also doesn't work .

Snapshots attached for reference .

Regards
Ranjeet

![image](https://user-images.githubusercontent.com/50072052/71514703-fc03d780-28c5-11ea-8994-025e6b719161.png)

![image](https://user-images.githubusercontent.com/50072052/71514724-07570300-28c6-11ea-928e-c7180be77799.png)

**Comment by jeremystretch** [comment]
Thank you for your interest in NetBox. GitHub issues are intended for reporting reproducible bugs and requesting features, and must be submitted using one of the templates provided [here](https://github.com/digitalocean/netbox/issues/new/choose). For general discussion, questions, or assistance with installation issues, please post to our [mailing list](https://groups.google.com/forum/#!forum/netbox-discuss) instead.
