### ISSUE TITLE
The proxy server could not handle the request GET /dcim/sites/add/.

### ISSUE THREAD

**Issue by kasatka231** [netbox-community/netbox#3796]
### Environment
* Python version:  
* NetBox version:  
### Steps to Reproduce
1. Open from browser http://netbox/Organization/sites/add
2. open from browser https://netbox/Organization/sites/add
3.

### Expected Behavior
I can add sites to the netbox

### Observed Behavior
I see a error.
Proxy Error 
The proxy server received an invalid response from an upstream server
The proxy server could not handle the request GET /dcim/sites/add
Reason ERROR reading from remote server

configuration Apache:
[root@netbox ~]# cat /etc/httpd/conf.d/netbox.conf 
<VirtualHost *:80>
  ProxyPreserveHost On
  ServerAdmin 
  ErrorLog "/var/www/netbox/logs/netbox-error_log"
  TransferLog "/var/www/netbox/logs/netbox-access_log"
  ServerName netbox.global.sberbank.ru
  Alias /static /opt/netbox/netbox/static
    <Directory /opt/netbox/netbox/static>
         Options Indexes FollowSymLinks MultiViews
         AllowOverride None
         Require all granted
    </Directory>
    <Location /static>
         ProxyPass !
    </Location> 
 
RequestHeader set "X-Forwarded-Proto" expr=%(REQUEST_SCHEME)
  ProxyPass / http://127.0.0.1:8001/
  ProxyPassReverse / http://127.0.0.1:8001/
</VirtualHost>

<VirtualHost *:443>
  ProxyPreserveHost On 
  ServerAdmin  
  ServerName netbox 
  Alias /static /opt/netbox/netbox/static
  SSLEngine on
  SSLCertificateFile "/etc/ssl/certs/netbox_ssl.crt"
  SSLCertificateKeyFile "/etc/pki/tls/private/netbox_ssl.key" 
    <Directory /opt/netbox/netbox/static>          
         Options Indexes FollowSymLinks MultiViews 
         AllowOverride None 
         Require all granted 
     </Directory>
    <Location /static>
         ProxyPass ! 
    </Location> 
 RequestHeader set "X-Forwarded-Proto" expr=%(REQUEST_SCHEME)
  ProxyPass / http://127.0.0.1:8001/ 
  ProxyPassReverse / http://127.0.0.1:8001/ 
</VirtualHost>

Configuration supervisord 
root@netbox ~]# cat /etc/supervisord.
supervisord.conf  supervisord.d/    
[root@netbox ~]# cat /etc/supervisord.d/netbox.ini 
[program:netbox]
command = gunicorn -c /opt/netbox/gunicorn_config.py netbox.wsgi
directory = /opt/netbox/netbox/
user = apache

[program:netbox-rqworker]
command = python3 /opt/netbox/netbox/manage.py rqworker
directory = /opt/netbox/netbox/
user = apache

[root@netbox ~]# cat /opt/netbox/gunicorn_config.py 
command = '/usr/bin/gunicorn'
pythonpath = '/opt/netbox/netbox'
bind= '127.0.0.1:8001'
workers = 3
user = 'apache'
max_requests = 5000
max_requests_jitter = 500

Logs from httpd
root@netbox ~]# cat /var/www/netbox/logs/netbox-access_log 
x.x.x.x - - [27/Dec/2019:03:12:08 -0500] "GET / HTTP/1.1" 200 238618
x.x.x.x - - [27/Dec/2019:03:12:09 -0500] "GET /static/font-awesome-4.7.0/fonts/fontawesome-webfont.woff2?v=4.7.0 HTTP/1.1" 304 -
x.x.x.x - - [27/Dec/2019:03:12:09 -0500] "GET /static/debug_toolbar/img/djdt_vertical.png HTTP/1.1" 304 -
x.x.x.x - - [27/Dec/2019:03:12:15 -0500] "GET /dcim/sites/add/ HTTP/1.1" 502 409
x.x.x.x - - [27/Dec/2019:03:28:43 -0500] "GET / HTTP/1.1" 200 538277
x.x.x.x - - [27/Dec/2019:03:29:03 -0500] "GET /tenancy/tenants/add/ HTTP/1.1" 200 240477
x.x.x.x - - [27/Dec/2019:03:29:07 -0500] "GET /dcim/regions/add/ HTTP/1.1" 200 214143
x.x.x.x - - [27/Dec/2019:03:28:37 -0500] "GET /dcim/sites/add/ HTTP/1.1" 502 409
x.x.x.x - - [27/Dec/2019:03:29:10 -0500] "GET /dcim/racks/add/ HTTP/1.1" 200 444383
x.x.x.x - - [27/Dec/2019:03:29:15 -0500] "GET /dcim/rack-groups/add/ HTTP/1.1" 200 217471
x.x.x.x - - [27/Dec/2019:03:29:18 -0500] "GET /dcim/devices/add/ HTTP/1.1" 200 762588
x.x.x.x - - [27/Dec/2019:03:29:22 -0500] "GET /dcim/device-types/add/ HTTP/1.1" 200 341098
x.x.x.x - - [27/Dec/2019:03:29:30 -0500] "GET /ipam/vrfs/add/ HTTP/1.1" 200 269632
x.x.x.x - - [27/Dec/2019:03:29:33 -0500] "GET /virtualization/clusters/add/ HTTP/1.1" 200 352056
x.x.x.x - - [27/Dec/2019:03:29:36 -0500] "GET /circuits/providers/add/ HTTP/1.1" 200 219834
x.x.x.x - - [27/Dec/2019:03:34:08 -0500] "GET /circuits/providers/add/ HTTP/1.1" 200 180224
x.x.x.x - - [27/Dec/2019:03:34:11 -0500] "GET / HTTP/1.1" 200 257869
x.x.x.x - - [27/Dec/2019:03:34:26 -0500] "GET /dcim/sites/ HTTP/1.1" 200 350304
x.x.x.x - - [27/Dec/2019:03:34:27 -0500] "GET /static/bootstrap-3.4.1-dist/fonts/glyphicons-halflings-regular.woff2 HTTP/1.1" 200 18028
x.x.x.x - - [27/Dec/2019:03:34:29 -0500] "GET /dcim/sites/add/ HTTP/1.1" 200 -
x.x.x.x - - [27/Dec/2019:03:34:59 -0500] "GET /dcim/sites/add/ HTTP/1.1" 502 409
x.x.x.x - - [27/Dec/2019:03:41:45 -0500] "GET / HTTP/1.1" 200 206229
x.x.x.x - - [27/Dec/2019:03:41:45 -0500] "GET /static/bootstrap-3.4.1-dist/css/bootstrap.min.css HTTP/1.1" 200 121457
x.x.x.x - - [27/Dec/2019:03:41:45 -0500] "GET /static/font-awesome-4.7.0/css/font-awesome.min.css HTTP/1.1" 200 31000
x.x.x.x - - [27/Dec/2019:03:41:45 -0500] "GET /static/jquery-ui-1.12.1/jquery-ui.css HTTP/1.1" 200 37326
x.x.x.x - - [27/Dec/2019:03:41:45 -0500] "GET /static/select2-4.0.5/css/select2.min.css HTTP/1.1" 200 15196
x.x.x.x - - [27/Dec/2019:03:41:45 -0500] "GET /static/select2-bootstrap-0.1.0-beta.10/select2-bootstrap.min.css HTTP/1.1" 200 16792
x.x.x.x - - [27/Dec/2019:03:41:45 -0500] "GET /static/css/base.css?v2.6.9 HTTP/1.1" 200 11867
x.x.x.x - - [27/Dec/2019:03:41:45 -0500] "GET /static/img/netbox_logo.png HTTP/1.1" 200 2257
x.x.x.x - - [27/Dec/2019:03:41:45 -0500] "GET /static/js/jquery-3.4.1.min.js HTTP/1.1" 200 88145
x.x.x.x - - [27/Dec/2019:03:41:45 -0500] "GET /static/jquery-ui-1.12.1/jquery-ui.min.js HTTP/1.1" 200 253669
x.x.x.x - - [27/Dec/2019:03:41:45 -0500] "GET /static/bootstrap-3.4.1-dist/js/bootstrap.min.js HTTP/1.1" 200 39680
x.x.x.x - - [27/Dec/2019:03:41:45 -0500] "GET /static/select2-4.0.5/js/select2.min.js HTTP/1.1" 200 66606
x.x.x.x - - [27/Dec/2019:03:41:45 -0500] "GET /static/js/forms.js?v2.6.9 HTTP/1.1" 200 14330
x.x.x.x - - [27/Dec/2019:03:41:45 -0500] "GET /static/clipboard-2.0.4.min.js HTTP/1.1" 200 10754
x.x.x.x - - [27/Dec/2019:03:41:45 -0500] "GET /static/debug_toolbar/css/toolbar.css HTTP/1.1" 200 14835
x.x.x.x - - [27/Dec/2019:03:41:45 -0500] "GET /static/debug_toolbar/css/print.css HTTP/1.1" 200 41
x.x.x.x - - [27/Dec/2019:03:41:45 -0500] "GET /static/debug_toolbar/js/toolbar.js HTTP/1.1" 200 13188
x.x.x.x - - [27/Dec/2019:03:41:45 -0500] "GET /static/debug_toolbar/js/toolbar.timer.js HTTP/1.1" 200 2754
x.x.x.x - - [27/Dec/2019:03:41:45 -0500] "GET /static/debug_toolbar/js/toolbar.sql.js HTTP/1.1" 200 121
x.x.x.x - - [27/Dec/2019:03:41:46 -0500] "GET /static/img/netbox.ico HTTP/1.1" 200 1174
x.x.x.x - - [27/Dec/2019:03:41:46 -0500] "GET /static/font-awesome-4.7.0/fonts/fontawesome-webfont.woff2?v=4.7.0 HTTP/1.1" 200 77160
x.x.x.x - - [27/Dec/2019:03:45:55 -0500] "GET / HTTP/1.1" 200 551803
x.x.x.x - - [27/Dec/2019:03:46:19 -0500] "GET /dcim/regions/ HTTP/1.1" 200 200239
x.x.x.x - - [27/Dec/2019:03:46:22 -0500] "GET /dcim/sites/ HTTP/1.1" 200 302232
x.x.x.x - - [27/Dec/2019:03:46:03 -0500] "GET /dcim/sites/add/ HTTP/1.1" 200 -
x.x.x.x - - [27/Dec/2019:03:50:52 -0500] "GET /admin/ HTTP/1.1" 200 222703
x.x.x.x - - [27/Dec/2019:03:50:53 -0500] "GET /static/admin/css/base.css HTTP/1.1" 200 16378
x.x.x.x - - [27/Dec/2019:03:50:53 -0500] "GET /static/admin/css/dashboard.css HTTP/1.1" 200 412
x.x.x.x - - [27/Dec/2019:03:50:53 -0500] "GET /static/admin/css/responsive.css HTTP/1.1" 200 17944
x.x.x.x - - [27/Dec/2019:03:50:53 -0500] "GET /static/admin/css/fonts.css HTTP/1.1" 200 423
x.x.x.x - - [27/Dec/2019:03:50:53 -0500] "GET /static/admin/img/icon-addlink.svg HTTP/1.1" 200 331
x.x.x.x - - [27/Dec/2019:03:50:53 -0500] "GET /static/admin/img/icon-changelink.svg HTTP/1.1" 200 380
x.x.x.x - - [27/Dec/2019:03:50:53 -0500] "GET /static/admin/fonts/Roboto-Regular-webfont.woff HTTP/1.1" 200 85876
x.x.x.x - - [27/Dec/2019:03:50:53 -0500] "GET /static/admin/fonts/Roboto-Light-webfont.woff HTTP/1.1" 200 85692
x.x.x.x - - [27/Dec/2019:03:50:53 -0500] "GET /static/admin/fonts/Roboto-Bold-webfont.woff HTTP/1.1" 200 86184
x.x.x.x - - [27/Dec/2019:03:51:06 -0500] "GET /admin/extras/topologymap/ HTTP/1.1" 200 216234
x.x.x.x - - [27/Dec/2019:03:51:09 -0500] "GET /static/admin/css/changelists.css HTTP/1.1" 200 6170
x.x.x.x - - [27/Dec/2019:03:51:09 -0500] "GET /static/admin/js/jquery.init.js HTTP/1.1" 200 363
x.x.x.x - - [27/Dec/2019:03:51:09 -0500] "GET /static/admin/js/core.js HTTP/1.1" 200 7099
x.x.x.x - - [27/Dec/2019:03:51:09 -0500] "GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 200 271817
x.x.x.x - - [27/Dec/2019:03:51:09 -0500] "GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 200 6918
x.x.x.x - - [27/Dec/2019:03:51:09 -0500] "GET /static/admin/js/actions.js HTTP/1.1" 200 6766
x.x.x.x - - [27/Dec/2019:03:51:09 -0500] "GET /static/admin/js/urlify.js HTTP/1.1" 200 8941
x.x.x.x - - [27/Dec/2019:03:51:09 -0500] "GET /static/admin/js/prepopulate.js HTTP/1.1" 200 1530
x.x.x.x - - [27/Dec/2019:03:51:09 -0500] "GET /static/admin/js/vendor/xregexp/xregexp.js HTTP/1.1" 200 128820
x.x.x.x - - [27/Dec/2019:03:51:09 -0500] "GET /admin/jsi18n/ HTTP/1.1" 200 3380
x.x.x.x - - [27/Dec/2019:03:51:09 -0500] "GET /static/admin/img/tooltag-add.svg HTTP/1.1" 200 331
x.x.x.x - - [27/Dec/2019:03:51:12 -0500] "GET /admin/ HTTP/1.1" 200 222692
x.x.x.x - - [27/Dec/2019:03:51:15 -0500] "GET /admin/extras/webhook/ HTTP/1.1" 200 248977
x.x.x.x - - [27/Dec/2019:03:51:16 -0500] "GET /admin/jsi18n/ HTTP/1.1" 200 3380
x.x.x.x - - [27/Dec/2019:03:51:19 -0500] "GET /admin/ HTTP/1.1" 200 222692
x.x.x.x - - [27/Dec/2019:03:51:21 -0500] "GET /admin/extras/graph/ HTTP/1.1" 200 219052
x.x.x.x - - [27/Dec/2019:03:51:22 -0500] "GET /admin/jsi18n/ HTTP/1.1" 200 3380
x.x.x.x - - [27/Dec/2019:03:51:23 -0500] "GET /admin/ HTTP/1.1" 200 222694
x.x.x.x - - [27/Dec/2019:04:28:37 -0500] "GET /dcim/sites/add/ HTTP/1.1" 502 409
[root@netbox ~]# cat /var/www/netbox/logs/netbox-error_log 
[Fri Dec 27 03:12:46.018138 2019] [proxy_http:error] [pid 6530:tid 140174033938176] (20014)Internal error (specific information not available): [client x.x.x.x:43488] AH01102: error reading status line from remote server 127.0.0.1:8001, referer: http://netbox/
[Fri Dec 27 03:12:46.018203 2019] [proxy:error] [pid 6530:tid 140174033938176] [client x.x.x.x:43488] AH00898: Error reading from remote server returned by /dcim/sites/add/, referer: http://netbox/
[Fri Dec 27 03:29:07.873674 2019] [proxy_http:error] [pid 7243:tid 140610241488640] (20014)Internal error (specific information not available): [client x.x.x.x:43490] AH01102: error reading status line from remote server 127.0.0.1:8001
[Fri Dec 27 03:29:07.873746 2019] [proxy:error] [pid 7243:tid 140610241488640] [client x.x.x.x:43490] AH00898: Error reading from remote server returned by /dcim/sites/add/
[Fri Dec 27 03:34:59.536749 2019] [proxy_http:error] [pid 7456:tid 140610350593792] (20014)Internal error (specific information not available): [client x.x.x.x:43510] AH01102: error reading status line from remote server 127.0.0.1:8001, referer: http://netbox/dcim/sites/
[Fri Dec 27 03:35:29.730714 2019] [proxy_http:error] [pid 7456:tid 140610495588096] (20014)Internal error (specific information not available): [client x.x.x.x:43514] AH01102: error reading status line from remote server 127.0.0.1:8001, referer: http://netbox/dcim/sites/
[Fri Dec 27 03:35:29.730768 2019] [proxy:error] [pid 7456:tid 140610495588096] [client x.x.x.x:43514] AH00898: Error reading from remote server returned by /dcim/sites/add/, referer: http://netbox/dcim/sites/
[Fri Dec 27 03:46:33.191998 2019] [proxy_http:error] [pid 9116:tid 140458785240832] (20014)Internal error (specific information not available): [client x.x.x.x:43562] AH01102: error reading status line from remote server 127.0.0.1:8001, referer: http://netbox/
[Fri Dec 27 04:29:08.761711 2019] [proxy_http:error] [pid 9116:tid 140458239977216] (20014)Internal error (specific information not available): [client x.x.x.x:43584] AH01102: error reading status line from remote server 127.0.0.1:8001, referer: http://netbox/dcim/sites/
[Fri Dec 27 04:29:08.761782 2019] [proxy:error] [pid 9116:tid 140458239977216] [client x.x.x.x:43584] AH00898: Error reading from remote server returned by /dcim/sites/add/, referer: http://netbox/dcim/sites/

Configuration gunicorn:
cat /opt/netbox/gunicorn_config.pu
Command = /opt/netbox/netbox
Bind = 127.0.0.1:8001
Workers = 3
user = apache 
max_request = 5000
max_request_jitter = 500

**Comment by jeremystretch** [comment]
Thank you for your interest in NetBox. GitHub issues are intended for reporting reproducible bugs and requesting features, and must be submitted using one of the templates provided [here](https://github.com/netbox-community/netbox/issues/new/choose). For general discussion, questions, or assistance with installation issues, please post to our [mailing list](https://groups.google.com/forum/#!forum/netbox-discuss) instead.

**Comment by hSaria** [comment]
@kasatka231, your issue may be similar to https://github.com/netbox-community/netbox/issues/3746; try adding a timeout to gunicorn.

**Comment by kasatka231** [comment]
Work for me:
Adding timeout to gunicorn did the trick
timeout = 60

@hSaria thank your!
