### ISSUE TITLE
Upgrade Select2

### ISSUE THREAD

**Issue by hSaria** [netbox-community/netbox#3805]
### Proposed Changes
Upgrade the Select2 library to the latest patch (4.0.12)

### Justification
Mainly for https://github.com/select2/select2/pull/5222 (keep select open if the CTRL/CMD key is held down, which lowers the number of queries to the server by not reloading the available options then force-scrolling after the query finishes – gets proportionately more annoying the higher the latency), but also to keep up with all of the improvements.

**Comment by jeremystretch** [comment]
Static libraries are upgraded during minor version bumps (e.g. v2.6 o v2.7). This has already occurred for the v2.7 beta release and will be included in the v2.7 final release.

**Comment by hSaria** [comment]
Thanks. I'll go ahead and close the PR then.
