### ISSUE TITLE
custom script example NewBranchScript can not select switch_model

### ISSUE THREAD

**Issue by bybai** [netbox-community/netbox#3808]
### Environment
* Python version: 3.6
* NetBox version:  2.6.9

### Steps to Reproduce
1. copy example  NewBranchScript  in /opt/netbox/netbox/scripts
2. open http://127.0.0.1:11111/extras/scripts/example/NewBranchScript/
3. I cannot select switch model, the switch model is "--------------"

### Expected Behavior
expect show correct switch model.

### Observed Behavior
<img width="1074" alt="屏幕快照 2019-12-30 下午3 32 09" src="https://user-images.githubusercontent.com/6743951/71572453-31086800-2b1a-11ea-8e18-365d917206d6.png">

**Comment by MathijsVanWilligen** [comment]
did you have modified the "manufacturer_name" and the "model_in" parameters to your manufacturer/models?

    switch_model = ObjectVar(
        description="Access switch model",
        queryset = DeviceType.objects.filter(
            manufacturer__name='<your manufacturer name>',
            model__in=['<your models>']
        )
    )

**Comment by bybai** [comment]
I used the example code from this page:
https://netbox.readthedocs.io/en/stable/additional-features/custom-scripts/

**Comment by bybai** [comment]
Hi @MathijsVanWilligen,
My code is 
```
    switch_model = ObjectVar(
        description="Access switch model",
        queryset = DeviceType.objects.filter(
            manufacturer__name='Cisco',
            model__in=['Catalyst 3560X-48T', 'Catalyst 3750X-48T']
        )
    )
``` 
I used example from https://netbox.readthedocs.io/en/stable/additional-features/custom-scripts/

**Comment by MathijsVanWilligen** [comment]
hi @bybai,
I apologize if I don't understand your question correctly but when you don't have an "Cisco" manufacturer type in your netbox envrionment with one of these models: "Catalyst 3560X-48T", "Catalyst 3750X-48T", you can't select other types. (i think)

for example: if you have an Cisco C1117-4P router you have to create this type in netbox under the Cisco manufacturer type, and add "C1117-4P" into the 'model__in' parameter -> 
` model__in=['Catalyst 3560X-48T', 'Catalyst 3750X-48T', 'C1117-4P']`.

i hope this helps you.

**Comment by bybai** [comment]
@MathijsVanWilligen 
Thank your reply, I added 'Cisco' under manufacturer type , but I think there is no 'models' under manufacturer. Is 'device type' 'model__in' parameter?

**Comment by bybai** [comment]
@MathijsVanWilligen,
It works, after I added 'device type'. Now I knew 'device type' is 'model__in'. Thanks.
