### ISSUE TITLE
Addition of Logical Interface Type

### ISSUE THREAD

**Issue by nathbooth** [netbox-community/netbox#3824]
### Environment
* Python version:  3.7
* NetBox version:  v2.6.9

Addition of sub-interface in dcim/interfaces as an interface type
### Proposed Functionality
Addition of type: 'logical' to interface types under 'Virtual Interfaces' with no restriction on parent LAGs, the current type of virtual is restricted to not allow that parent to be a LAG.

### Use Case
When using Link Aggregation on layer-3 capable devices it is common to have layer 3 sub-interfaces on devices. At present this is possible, but the type can only be defined at 'Other'

### Database Changes
None
### External Dependencies
None

**Comment by DanSheps** [comment]
Hello nathbooth,

For a layer3 sub-interface on a LAG, you would still use Virtual.  Parent LAG's associate Physical ports as members of that port channel.  A logical interface that is set with a parent lag would be considered part of that port channel (member interface).

You would have them setup in the following manner:

Port-Channel1 - LAG
Port-Channel1.23 - Virtual (This is one of your L3 Po's)
Port-Channel1.45 - Virtual (This is one of your L3 Po's)

If you have further questions regarding this, please head on over to the netbox discussion group at https://groups.google.com/forum/#!forum/netbox-discuss and feel free to ask some more questions there.

I am going to close this out for now.
