### ISSUE TITLE
The documentation is missing a "How to backup and restore" section

### ISSUE THREAD

**Issue by 991jo** [netbox-community/netbox#3832]
### Change Type
[X] Addition
[ ] Correction
[ ] Deprecation
[ ] Cleanup (formatting, typos, etc.)

### Proposed Changes

Currently the netbox documentation does not include a section on what has to be backup to restore a complete netbox installation.
I do not propose that netbox should consider the exact commands because depending on how you may or may not automate your netbox installation those may vary.
But a list of all things that have to be considered would be nice.

- Is everything that is relevant contained in the psql database?
- Or is there something in redis that wants to be backed up?
- Do I have to backup the SECRET_KEY from the config?
- Where is the master key used to store secrets?
- What about reports, media and scripts?
- Are there any other things?

I think that backing up netbox is a very important topic because as a single source of truth the impact of data loss might be a catastrophe. Adding a "How to backup" section to the configuration that tells me what is important would give me a lot of confidence in my netbox installation.

A related issue might be: https://github.com/netbox-community/netbox/issues/567

**Comment by jeremystretch** [comment]
Replicating NetBox is documented [here](https://netbox.readthedocs.io/en/stable/administration/replicating-netbox/).

**Comment by 991jo** [comment]
If this is the guide that tells me how to backup my netbox installtion then the word "backup" should be found somewhere on that page. Someone who searches for "backup" in the documentation does not find this site.

**Comment by LBegnaud** [comment]
But that isn't how to back it up. That documentation instructs how to create a new netbox instance with an existing netbox as a seed of data. Backups would be best done following standard practices likely of VM-level snapshots with maybe rolling pg_dumps into a directory. you could use that above doc as a guide to know what needs to be backed up, though.

**Comment by hSaria** [comment]
I think that's out of scope because it isn't related to NetBox. Backing up your OS/VM/Container and/or your database is not application-dependent; they're things you would do in your own infrastructure.
