### ISSUE TITLE
Netbox 2.7 beta /api/dcim/cables/

### ISSUE THREAD

**Issue by louis-oui** [netbox-community/netbox#3835]
### Environment
* Python version:  3.6.6
* NetBox version:  last commit of branch develop-2.7
commit 1d63a30b7ad1fdc5c3569287f999c8ec72ec7c4c
Merge: 6544489 c2dc243
Author: Jeremy Stretch <stretch@packetlife.net>
Date:   Thu Jan 2 17:21:15 2020 -0500

    Merge branch 'develop' into develop-2.7

### Steps to Reproduce
1. Get api/dcim/cables/
2.
3.

### Observed Behavior

Got :
```
 Server Error
There was a problem with your request. Please contact an administrator.

The complete exception is provided below:

<class 'KeyError'>

'true'
If further assistance is required, please post to the NetBox mailing list.
```

**Comment by jeremystretch** [comment]
The `develop-2.7` branch is under active development and should not be assumed stable at any point. Please open bug reports only against tagged releases. Thanks!
