### ISSUE TITLE
Add California Style Power connection types

### ISSUE THREAD

**Issue by ryanmerolle** [netbox-community/netbox#3841]
### Environment
* Python version: 3.6.3
* NetBox version: 2.7

### Proposed Functionality
California Style Connectors seem to be missing from the current power_port and power_outlet types.  

### Use Case
Many PDUs use these connector type.

### Database Changes
Add a new data model type with the fields mentioned in the proposed functionality.

### External Dependencies
N/A

**Comment by jeremystretch** [comment]
Please list the specific values you're proposing.

**Comment by ryanmerolle** [comment]
https://www.lockingpowercords.com/category/5-50a-locking-extension-cords.aspx
For devices like https://www.apc.com/shop/us/en/products/Rack-PDU-2G-Metered-ZeroU-10-0kW-208V-36-C13-6-C19/P-AP8868

- cs6360c
- cs6361c
- cs6364c
- cs6365c
- cs8164c
- cs8165c
- cs8264c
- cs8265c
- cs8364c
- cs8365c
- cs8464c
- cs8465c
