### ISSUE TITLE
The last_updated field is not available on interface models

### ISSUE THREAD

**Issue by synackray** [netbox-community/netbox#3850]
### Environment
* Python version:  3.6.8
* NetBox version:  2.6.11

### Steps to Reproduce
1. Browse to the `/api/dcim/interfaces/{id}` or `/api/virtualization/interfaces/{id}` URLs.

### Expected Behavior
The `last_updated` field exists and returns the timestamp of the objects last modification.

### Observed Behavior
The `last_updated` field does not exist. It is available for the object models in which the interfaces relate to (parents and children) but not the interfaces themselves.

![image](https://user-images.githubusercontent.com/24757919/71843997-7b16be00-30c5-11ea-984b-2a8e6ab8d6c8.png)

**Comment by synackray** [comment]
As always, thanks to the NetBox team for their time reviewing this. I wasn't sure if this was better suited as a bug or enhancements. Apologies if I chose incorrectly.

**Comment by jeremystretch** [comment]
This is expected: device components models (such as the Interface model) do not have `created` or `last_updated` fields. If you would like to propose adding these fields, please open a new feature request, and be sure to cite your use case.
