### ISSUE TITLE
Custom Circuit Columns

### ISSUE THREAD

**Issue by realged13** [netbox-community/netbox#3852]
### Environment
* Python version:  2.7.5
* NetBox version:  2.6.2

### Use Case

Would like to be able to customize the columns headers of circuits.  Circuit speed (Commit Rate) is one I would like to be present on the dashboard.  Also being able to remove other headers we don't deem necessary.

**Comment by jeremystretch** [comment]
Thank you for submitting this issue, however it appears that this topic has already been raised. Please see issue #492 for further discussion.
