### ISSUE TITLE
Allow multiple connections to a single power feed

### ISSUE THREAD

**Issue by lps-rocks** [netbox-community/netbox#3855]
### Environment
* Python version:  3.7.3
* NetBox version:  2.6.9

### Proposed Functionality

Add the ability to connect multiple devices to a single power feed. 

### Use Case

This is useful where a single physical circuit is being used for drops to multiple PDUs. e.g. 3-phase 208/120V via L21-30R to multiple 208 single phase / multiple 120V single phase connections.

### Database Changes

Probably None.

### External Dependencies

None

**Comment by jeremystretch** [comment]
The current model was decided upon after feedback from the v2.6 beta. It is no longer open for discussion, as development focus has moved elsewhere.

**Comment by hSaria** [comment]
@lps-rocks wouldn't it make sense to model the circuit as a power panel (the source of the circuit) and each of the drops as individual power feeds?
