### ISSUE TITLE
Escaping double quotes in plaintext secret in csv upload

### ISSUE THREAD

**Issue by EugeniaWong** [netbox-community/netbox#3861]
### Environment
* Python version:  3.5.2
* NetBox version:  2.5.6

### Proposed Functionality

To allow the use of double quotes in secrets. At the moment, double quotes cannot be part of a plaintext secret as they are used to wrap multi-line data nad values containing commas.

### Use Case

To allow the use of double quotes in secrets.

**Comment by hSaria** [comment]
As with Excel CSVs, you can put double-quotes in your data by replacing it with **a pair of double-quotes**.

For example, here are two secrets.
```
name,device,role,plaintext
secret1,as-01,bla,hello""world
secret2,as-01,bla,"hello
""
world"
```

They are represented in JSON (i.e. the API) as:
```json
"plaintext": "hello\"\"world\"\""
"plaintext": "hello\r\n\"\r\nworld"
```

**Comment by jeremystretch** [comment]
FYI this is a function of Python's `csv` library. From [the docs](https://docs.python.org/3.6/library/csv.html#csv.Dialect.doublequote):

> **Dialect.doublequote**
> Controls how instances of quotechar appearing inside a field should themselves be quoted. When True, the character is doubled. When False, the escapechar is used as a prefix to the quotechar. It defaults to True.
