### ISSUE TITLE
Unable to add interface to virtual machine

### ISSUE THREAD

**Issue by a-d-v** [netbox-community/netbox#3868]
### Environment
* Python version:  3.6
* NetBox version:  2.7-beta1

### Steps to Reproduce
1. Navigate to virtualization, virtual machines
2. Edit an virtual machine
3. Click 'Add interfaces'
4. Add 'LAN' as name field
5. Select create

### Expected Behavior
Would expect a new interface to be added to the VM

Screen refreshes after clicking create and returns to same create screen. No interface is added. This problem does not occur with version 2.6.11.

**Comment by hSaria** [comment]
I couldn't recreate this with v2.6.11. Any other special things about the deployment?

**Comment by jeremystretch** [comment]
You've listed your NetBox version as v2.7-beta1 but then indicate it occurs on v2.6.11. Which is it?

**Comment by a-d-v** [comment]
Apologies, this problem does NOT occur on 2.6.11. It occurs only with the 2.7-beta1
