### ISSUE TITLE
Docker LDAP error

### ISSUE THREAD

**Issue by ozmend** [netbox-community/netbox#3870]
Hi, I'm using netbox-ldap docker version.

when i use the local admin account, it works normally
if i try to login with ldap user

I'm getting this error;

Caught LDAPError while authenticating ozmend@example.com: LDAPError(0, 'Error')
netbox_1         | 13:50:10: Caught LDAPError while authenticating ozmend@example.com: LDAPError(0, 'Error')

in the netbox.env file

AUTH_LDAP_BIND_DN='CN=testuser,OU=ServiceUsers,OU=Users,DC=EXAMPLE,DC=COM'
AUTH_LDAP_BIND_PASSWORD='password'
AUTH_LDAP_SERVER_URI="ldaps://dc01.example.com" or "ldaps://dc02.example.com"
AUTH_LDAP_USER_SEARCH_BASEDN='OU=Users,DC=EXAMPLE,DC=COM'
AUTH_LDAP_GROUP_SEARCH_BASEDN='OU=Groups,DC=EXAMPLE,DC=COM'
AUTH_LDAP_REQUIRE_GROUP_DN='CN=TEST_Users,OU=Groups,DC=EXAMPLE,DC=COM'
AUTH_LDAP_IS_SUPERUSER_DN='CN=TEST_Users,OU=Groups,DC=EXAMPLE,DC=COM'
AUTH_LDAP_IS_ADMIN_DN='CN=TEST_Admins,OU=Groups,DC=EXAMPLE,DC=COM'
LDAP_IGNORE_CERT_ERRORS='True'
AUTH_LDAP_ATTR_FIRSTNAME='givenName'
AUTH_LDAP_USER_SEARCH_ATTR='sAMAccountName'
AUTH_LDAP_GROUP_SEARCH_CLASS='group'

could you help me to fix the error
Thanks

**Comment by jeremystretch** [comment]
Thank you for your interest in NetBox. GitHub issues are intended for reporting reproducible bugs and requesting features, and must be submitted using one of the templates provided [here](https://github.com/netbox-community/netbox/issues/new/choose). For general discussion, questions, or assistance with installation issues, please post to our [mailing list](https://groups.google.com/forum/#!forum/netbox-discuss) instead.

Please note that any issues related to a Docker installation are outside the scope of this project; see [netbox-docker](https://github.com/netbox-community/netbox-docker).
