### ISSUE TITLE
Copper Patch / Darkfiber option for Circuit Termination (instead of/extra option in) Port Speed

### ISSUE THREAD

**Issue by martijngoorman** [netbox-community/netbox#3874]
# Environment
NetBox version: 2.6.7

# Proposed Functionality
Circuit termination between two patch panels needs a port speed to be filled in.
Physically this is a patch, so the choice for a copper patch of dark fiber would be great.

# Use Case
Connect two patch panels via a circuit/cross connect that is owned by the data center provider

**Comment by jeremystretch** [comment]
It sounds like you're using the Circuit model where a Cable would be more appropriate. If I've misunderstood, please revise your issue to more clearly convey the requested featured.
