### ISSUE TITLE
Increment/Decrement Integer on Site AS Number Does not Function (Chrome/Safari)

### ISSUE THREAD

**Issue by jvanderaa** [netbox-community/netbox#3876]
### Environment
* Python version:  3.6.8
* NetBox version:  v2.7 beta1 & v2.7 beta2

### Steps to Reproduce
A. Open Google Chrome 79.0.3945.88 (MacOS)
1. Go to sites
2. Edit a site
3. Click on the integer increment button

Firefox works just fine. Safari has a whole different issue (report coming soon). Not sure if this is a browser function or a function of a library Netbox uses? 

### Expected Behavior
Expected to have the integers increment and decrement based on number of mouse clicks.

### Observed Behavior
The number stays the same

**Comment by hSaria** [comment]
This currently happens on the latest stable version, v2.6.11.

**Comment by hSaria** [comment]
This seems to be caused by the `min` and `max` attributes being set to absurdly high numbers
```html
```

**Comment by jeremystretch** [comment]
> absurdly high numbers

**Comment by jeremystretch** [comment]
> absurdly high numbers

Well excuse me for future-proofing! :stuck_out_tongue: 

The root issue is that we use a `BigInt` for the field (`dcim.fields.ASNField`) to hold a 32-bit value, which does have intelligent min/max values defined, however they aren't getting replicated to the field's widget. We should be able to set these widget attributes directly on `ASNField`.

**Comment by hSaria** [comment]
No need to set them via the widget. Check out #3879.
