### ISSUE TITLE
Safari - Site ASN Increment/Decrement Functions Changes to Exponential Number

### ISSUE THREAD

**Issue by jvanderaa** [netbox-community/netbox#3877]
### Environment
* Python version:  3.6.8
* NetBox version:  2.7-beta2
* OS: MacOS 10.15

### Steps to Reproduce
1. Open Safari
2. Navigate to sites
3. Edit a site
4. Attempt to use the increment/decrement for the site ASN that has the value `65002` set in it

Not sure if it is related to #3876 but I thought I would get these documented, or maybe they are just a function of the browser.

### Expected Behavior
Expected to increment up or down based on mouse clicks

### Observed Behavior
At that point the values move to exponential numbers. Such as `6.5e+4`.

**Comment by hSaria** [comment]
This currently happens on the latest stable version, v2.6.11.

**Comment by hSaria** [comment]
As this has the same cause as #3876.

**Comment by jeremystretch** [comment]
One issue is enough for this bug.
