### ISSUE TITLE
Link to latest version

### ISSUE THREAD

**Issue by AnaelMobilia** [netbox-community/netbox#3884]
### Change Type
[x] Addition
[ ] Correction
[ ] Deprecation
[ ] Cleanup (formatting, typos, etc.)

### Proposed Changes
Add link to the latest release on the installation documentation

**Comment by jeremystretch** [comment]
The documentation already links to the list of most recent releases. This allows users to conveniently review the release notes from previous releases as well.

**Comment by AnaelMobilia** [comment]
Hello,

The documentation say "Download *the* latest stable release from GitHub" and provide a link to the list of releases.
Why giving choices to a new user if the goal is to make him choose the latest release ?

Regards,
Anael
