### ISSUE TITLE
Cluster assignment under Config Context

### ISSUE THREAD

**Issue by soofff** [netbox-community/netbox#3886]
### Environment
* Python version:  3
* NetBox version:  2.6.11

### Proposed Functionality
It is currently not possible to assign config context to cluster.
I would expect to have the possibility to assign cluster under `/extras/config-contexts/1/`.
Devices and virtual machines(?) would have the assigned config context.

### Use Case
Devices in a cluster could have their own cluster configuration. If you have various cluster configuration you could easily assign them to the cluster which affects to all devices and maybe virtual machines.

### Database Changes
I think this will need some small database changes. New cluster assignment field and references must be stored.

### External Dependencies
None

**Comment by jeremystretch** [comment]
I think this makes sense. Should be pretty straightforward. Need another maintainer to :+1:
