### ISSUE TITLE
Message when disconnecting a cable not showing ID

### ISSUE THREAD

**Issue by hSaria** [netbox-community/netbox#3898]
### Environment
* Python version: 3.6.8
* NetBox version: 2.6.12-dev

### Steps to Reproduce
1. Go to a device (e.g. `dcim/devices/1/`)
2. Disconnect a cable

### Expected Behavior
The message says `Deleted cable #5` where 5 is the ID of the cable.

### Observed Behavior
The message says `#None`

This is similar to https://github.com/netbox-community/netbox/issues/2984

**Comment by phurrelmann** [comment]
Maybe it would even be better to display the label if it is given. This would mimic the behaviour as shown on the device/interface view where the cable id is only displayed when the cable has no label set.

**Comment by hSaria** [comment]
It already does. The issue is that `self.id_string` wasn't assigned prior to getting deleted.

https://github.com/netbox-community/netbox/blob/b7e78028ce6e998dc9172bd41bc602045daeb1ea/netbox/dcim/models.py#L3030-L3038

**Comment by phurrelmann** [comment]
perfect, then I misunderstood your comment. Sorry and thank you for your impressive work on old tickets over he last days :+1:

**Comment by hSaria** [comment]
Nothing to be sorry for. In fact, I appreciate you looking out, so thanks for that and keep it coming. And I'm just giving back some love to this project that clearly deserves it.
