### ISSUE TITLE
Get GPS Coordinates from image for Site object

### ISSUE THREAD

**Issue by itmicus** [netbox-community/netbox#3904]
### Environment
Python version: 3.5.2
NetBox version: 2.6.11

### Proposed Functionality
Get GPS Cooridnates from image while it uploding to Site Object.

### Use Case
User can make photo on mobile from physical Site. User can upload photo to Site object and if photo has GPS coordinates, Netbox ask him set coordinate for Site object, if yes, GPS coordinates from photo set to Site object automatically.

### Database Changes

No

### External Dependencies

No

**Comment by jeremystretch** [comment]
I'm rejecting this for several reasons:

1. The canonical coordinates of a site are typically set to something specific (e.g. the building's front entrance) or they are copied from a mapping service.
2. Uploading different photos, even those taken in the same vicinity, would alter the coordinates as consumer grade GPS positioning is typically not 100% accurate.
3. The quality of image metadata can be unreliable.
