### ISSUE TITLE
hostname & hyphen cutoff in rack elevations view

### ISSUE THREAD

**Issue by ryanmerolle** [netbox-community/netbox#3907]
### Environment
* Python version:  3.6.3
* NetBox version:  2.6.11

### Steps to Reproduce
1. Add a device to a rack with 32 or more characters and include hyphens in the name.
2. Navigate to the webpage of the associated rack & observe that the hostname is cutoff after the first occurrence of the hyphen.

### Expected Behavior
Not cut off at the hyphen, and either show as much of the hostname as it can or something else.

### Observed Behavior
The rack elevation will show the hostname is cutoff after the first occurrence of the hyphen no matter where in the hostname the hyphen exists.

**Comment by jeremystretch** [comment]
I'm going to close this as the current logic for rendering rack elevations has been gutted and replaced with SVG images in v2.7. As the v2.7 release is due very soon (this week, hopefully) no further development effort is being spent on the legacy rendering logic.

**Comment by ryanmerolle** [comment]
Sounds good to me.  I forgot you migrated to SVG images.
