### ISSUE TITLE
Remove ChainedFieldsMixin

### ISSUE THREAD

**Issue by hSaria** [netbox-community/netbox#3912]
### Proposed Changes
Remove the `ChainedFieldsMixin`, `ChainedModelChoiceField`, and `ChainedModelMultipleChoiceField`.

### Justification
Chaining has been replaced with APISelect's `filter_for` and is no longer required. It updates the queryset, but it is entirely ignored by the API call. And ever since #3812, only the selected option (if any) in the queryset is rendered, so limiting makes very little difference.

**Comment by jeremystretch** [comment]
This isn't as simple as just ripping out the chained fields logic, unfortunately. There's more going on here than UI rendering: Foreign key fields frequently need to have their querysets limited in various scenarios to avoid thrashing the database during form validation. It's no doubt something we should look into eventually but it's a huge project and not a priority at this time.

**Comment by hSaria** [comment]
With #4108 implemented, would it now be safe to remove chaining as the APISelect now limits the queryset to only the existing selection?
