### ISSUE TITLE
Get changelog from API

### ISSUE THREAD

**Issue by TawR1024** [netbox-community/netbox#3917]
Environment
Python version: 3.6.3
NetBox version: 2.6.6
Proposed Functionality
Get device changelog from api.

Use Case
Show diff between versions and fast revert device state. Using PATCH request based on info from change log

Database Changes
NA

External Dependencies
N/A

**Comment by jeremystretch** [comment]
There already exists an API endpoint to retrieve changelog entries: `/api/extras/object-changes/`

> Show diff between versions

See #2511

> fast revert device state

Not something we can reasonably undertake for myriad reasons.

When opening issues in the future, please be sure to preserve the template's markup for better readability, and open a separate issue for each distinct proposed feature.
