### ISSUE TITLE
Add search functionality back to Interface Connections and Console Connections

### ISSUE THREAD

**Issue by KevinMDerelanko** [netbox-community/netbox#3931]
### Environment
* Python version:  3.6
* NetBox version:  2.6.12

### Proposed Functionality
Requesting to have a free-form search box added to the Interface Connections page and Console Connections page. It seems it was removed in 80d1f80.

### Use Case
It's helpful to have when prepping labels for multiple networking devices.

### Database Changes
NA

### External Dependencies
NA

**Comment by jeremystretch** [comment]
Please rewrite your issue to include a detailed description of the proposed feature.
