### ISSUE TITLE
Enable filtering before/after custom date fields

### ISSUE THREAD

**Issue by jeremystretch** [netbox-community/netbox#3933]
### Environment
* Python version: 3.6.8
* NetBox version: 2.6.12

### Proposed Functionality
Provide the ability to filter before or after a custom date field value. For example, where a CustomField named `eol_date` exists on the Device model:

`GET /api/dcim/devices/?cf_eol_date__lt=2020-01-15`

### Use Case
This allows a user to find objects based on a minimum/maximum date.

### Database Changes
None

### External Dependencies
None

**Comment by DanSheps** [comment]
Would this be captured by #4121?

**Comment by jeremystretch** [comment]
Yes it would; going to close this one out.
