### ISSUE TITLE
Nested tenant groups

### ISSUE THREAD

**Issue by ebusto** [netbox-community/netbox#3939]
### Environment
* Python version:  3.6
* NetBox version:  2.6.12

### Proposed Functionality
Similar to regions, tenant groups should be nestable, in order to represent organizations with more than two levels.

For example: IT -> Infrastructure -> Network Support

### Use Case
This allows companies of any appreciable size to share one NetBox instance, while tracking organizational and team level ownership accurately, without having to resort to ugly hacks or naming conventions. 

### Database Changes
Add a `parent` attribute to the `TenantGroup` model.

### External Dependencies
None.

**Comment by tb-killa** [comment]
https://github.com/netbox-community/netbox/issues/2815

**Comment by jeremystretch** [comment]
This differs from #2815, which was to allow the assignment of a Tenant to multiple TenantGroups. Here, Tenants are still limited to a single TenantGroup association, but TenantGroups themselves can belong to other TenantGroups (similar to how Regions can be nested).

**Comment by jeremystretch** [comment]
Cross-referencing with #1754 (RackGroup nesting)

**Comment by itmicus** [comment]
May be it is part of it #554

**Comment by ebusto** [comment]
I don't think it should be coupled to #554.

I've implemented [RBAC for NetBox](https://pypi.org/project/netbox-rbac/), and as it is a non-trivial task, it would unnecessarily delay this simple change.
