### ISSUE TITLE
Netbox still showing v2.6.1.1 after migrating to 2.7.1

### ISSUE THREAD

**Issue by Djf2884** [netbox-community/netbox#3947]
Hello Guys, 

My netbox server is still showing old versionning on the frontpage after applying 2.7 upgrade, is this something normal, anybody seen the same?

![image](https://user-images.githubusercontent.com/10075667/72609534-7ce24c00-3925-11ea-9cf4-b85e8a504460.png)

Thx you :)

**Comment by hSaria** [comment]
For something like this, it is best to use the [mailing list](https://groups.google.com/forum/#!forum/netbox-discuss). And did you restart gunicorn?

**Comment by Djf2884** [comment]
> For something like this, it is best to use the [mailing list](https://groups.google.com/forum/#!forum/netbox-discuss). And did you restart gunicorn?

Thx it solved it. i completly forgot about this.

**Comment by hSaria** [comment]
You're welcome, but please use the mailing list next time. A lot of people watch this space for development-related activities.
