### ISSUE TITLE
Device "Create and Add Another" does not retain Manufacturer and Device Type

### ISSUE THREAD

**Issue by candlerb** [netbox-community/netbox#3950]
### Environment
* Python version: 3.5.2
* NetBox version:  2.7.1

### Steps to Reproduce
1. Add Device
2. Enter Name, Role, Manufacturer, Device Type, Site and Rack (optionally Tags and Comments)
3. Click "Create and Add Another"

### Expected Behavior

Given the new feature in 2.7, I was expecting the fields to be carried forward into the next form.

### Observed Behavior

Manufacturer and Device Type are *not* carried forward (neither are Comments)

However: Role, Site, Rack and Tags *are* carried forward.

**Comment by jeremystretch** [comment]
This is a bug with the form widgets. We're passing an initial value for the `device_type` field, however that field is chained to `manufacturer`, which has no initial value, so the set of available choices for `device_type` is empty.

**Comment by hSaria** [comment]
@jeremystretch checkout #3912 as it removed chaining (no longer needed, explanation in the ticket). It's also the cause of the issue you noticed in https://github.com/netbox-community/netbox/pull/3893#discussion_r365908986.
