### ISSUE TITLE
Remove Tenants and replace with Tags

### ISSUE THREAD

**Issue by tb-killa** [netbox-community/netbox#3956]
### Environment
* Python version:  3.6
* NetBox version:  2.7.1

### Proposed Functionality
Remove the actually Tenant implementation and reuse Tags as replacement. 

### Use Case
Many users use the tenants excessively to document different affiliations.
Since tenants currently cannot be structured hierarchically, the tag function should be used.
For this Tags has to be implement on every part who actually could use Tenant. 

### Database Changes
Tags have to be available on every part as Tenant is actually usable. 

### External Dependencies
None

**Comment by kobayashi** [comment]
It is not the reason to remove Tenants. As described in the [docs](https://netbox.readthedocs.io/en/stable/core-functionality/tenancy/), Tenants represents departments or customers within an organization and is hierarchical under Tenant Group. Tags are used for wider purpose depending on a usecase and not the same as Tenants. For this reason, I would like to regject this FR.
