### ISSUE TITLE
Status tab claims device is inactive

### ISSUE THREAD

**Issue by lukasjuhrich** [netbox-community/netbox#3960]
### Environment
* Python version: 3.7.6
* NetBox version: 2.7.1

### Steps to Reproduce
1. Have DCIM devices which are `active` (in the sense of the `dcim_device.status` column in the database) and have a valid database navigation
2. Navigate to the device overview

### Expected Behavior
The `status` tab should be enabled and clickable.

### Observed Behavior
The `status` tab is not clickable, instead it reports `device must be in active status`.
However, manually navigating to `status/` works perfectly fine and displays all desired data.

### Probable reason
The [template](https://github.com/netbox-community/netbox/blob/v2.7.1/netbox/templates/dcim/device.html#L87) still checks `device.status == 1` using the legacy numerical value (although this might be plain wrong because I don't know the codebase).

**Comment by kobayashi** [comment]
Confirmed and accepted this as bug.
