### ISSUE TITLE
Reference to incorrect files in migrating-to-systemd.md

### ISSUE THREAD

**Issue by mikewright** [netbox-community/netbox#3961]
### Change Type
[ ] Addition
[X] Correction
[ ] Deprecation
[ ] Cleanup (formatting, typos, etc.)

### Proposed Changes
In `migrating-to-systemd.md`:
- there is a section referring to non existent `contrib/netbox.env`
- references to `gunicorn.conf` should be to `gunicorn.py` 

`3-http-daemon.md` has the correct instructions

**Comment by jeremystretch** [comment]
@DanSheps can you fix this up please?

**Comment by candlerb** [comment]
It also says "If using CentOS/RHEL." (with a trailing full stop), making it unclear which of the following step(s) it qualifies.
