### ISSUE TITLE
SVG rack elevations: devices should have borders separating them

### ISSUE THREAD

**Issue by hellerve** [netbox-community/netbox#3964]
### Environment
* Python version:  
* NetBox version:  

Quoting from #3958:
> For devices which are butted together and have the same role/colour, there is no longer any line separating them - see example below. This comprises two 2U boxes and a 4U box, but is now very hard to see.

![](https://user-images.githubusercontent.com/44789/72678862-bc35a780-3aa1-11ea-8c35-8db1f0d7209d.png)

**Comment by candlerb** [comment]
This is much better, thank you.  There's just one minor point remaining.

When full-depth devices are mounted at the front of the rack, and I view from the front, then I see the borders as expected.  But I don't see the borders when viewing from the rear:

![image](https://user-images.githubusercontent.com/44789/72841431-404c8280-3c8e-11ea-85ff-d36a94a66454.png)

I'm not 100% sure that they had borders in the old HTML version, but I thought they did.  It would be a "nice to have".

**Comment by hellerve** [comment]
I didn’t touch the rear part. It shouldn’t be a problem to add (basically the same change that I did for the front); if we get buy-in from @jeremystretch I’ll add it tomorrow.

**Comment by hellerve** [comment]
Maybe we should open a new issue for this?

**Comment by DanSheps** [comment]
You can open a new issue, I can approve it for you right away if you want to start on the PR

**Comment by hellerve** [comment]
Thanke @DanSheps, I just opened #4019. I’ll first be able to fix it tomorrow, though, since it’s getting pretty late over here in Europe! :)
