### ISSUE TITLE
Add USB-C as console form factor

### ISSUE THREAD

**Issue by hklygre** [netbox-community/netbox#3968]
### Environment
* Python version:  Example: 3.5.3
* NetBox version:  Example: 2.7.1

### Proposed Functionality
Would like USB-C as a form factor for console ports
https://www.arubanetworks.com/products/networking/switches/6300-series/ - see "Specifications".

### Use Case
The new Aruba 6300-series switches uses the USB-C form factor. I am assuming more will.

**Comment by jeremystretch** [comment]
"USB type C" is already an available option.
