### ISSUE TITLE
IPv6 network discovery

### ISSUE THREAD

**Issue by raghunathnagepalli** [netbox-community/netbox#3976]
Hello Gents,

I deployed NetBox for one of our lab environments, which has IPv6 only addresses with Cisco, Ubiquiti and Microtik Switches. 
As NetBox doesn't support auto-network discovery by default - I installed Network Scanner, which uses nmap for discovery. But for some reasons this scanning isn't working. 
Can someone please help on how to get auto network discovery working for IPv6 address space?

Thank you,
Raghunath

**Comment by jeremystretch** [comment]
Thank you for your interest in NetBox. GitHub issues are intended for reporting reproducible bugs and requesting features, and must be submitted using one of the templates provided [here](https://github.com/netbox-community/netbox/issues/new/choose). For general discussion, questions, or assistance with installation issues, please post to our [mailing list](https://groups.google.com/forum/#!forum/netbox-discuss) instead.
