### ISSUE TITLE
IPv6 Auto Network Discovery

### ISSUE THREAD

**Issue by raghunathnagepalli** [netbox-community/netbox#3977]
Hi Jeremy,

In one of our lab environments in FB, I deployed NetBox to take care of IP Address Management. We are using mostly IPv6 address space with Cisco, Ubiquiti and Microtik switches. I installed Network Scanner with nmap feature to be able to perform automatic network discovery. But this isn't working for me. Is there a feature or a method available to scan IPv6 address space?

Thank you,
Raghu

**Comment by jeremystretch** [comment]
Please stop opening issues for this. See my reply to #3976.
