### ISSUE TITLE
Add VRF to drop-down when selecting IP addresses

### ISSUE THREAD

**Issue by chuckbales** [netbox-community/netbox#3978]
### Environment
* Python version:  3.6.9
* NetBox version: v2.6.12

Add the VRF name (or some other identifying value) to the drop-down box for IP addresses so that duplicate IPs can be differentiated

When adding a NAT entry and selecting the corresponding IP address, all IPs are shown with only the CIDR notation displayed. When the same IP is in the database under different VRFs, there is no way to differentiate when looking at the IPs in the drop-down field. Having the VRF name appended to the IP address, or a field to enter the desired VRF and limit the results, would help users to know which IP they're selecting.

**Comment by chuckbales** [comment]
Screenshot for example, 10.79.10.1/28 exists in two VRFs, but with this view I can't tell which one I'm actually selecting

![image](https://user-images.githubusercontent.com/13427789/72835283-6eaf6b00-3c58-11ea-94e5-1464fcb77da9.png)

**Comment by kobayashi** [comment]
I would accept this feature request as enhancement.
