### ISSUE TITLE
Add WLAN model for creating/connecting wireless PtP/PtMP links

### ISSUE THREAD

**Issue by cbock-clairglobal** [netbox-community/netbox#3979]
### Environment
* Python version:  3.5.4
* NetBox version:  v2.6.11

### Proposed Functionality

Ability to create wireless interfaces such as `wlan0` or `br0` and then connect them to each other as either wireless point-to-point or point-to-multipoint connections.  This is similar but in contrast to a cable connection, which is admittedly not the right way to document a 5 mile wireless bridge between two radios.  This would allow WISPs and other RF operators to more accurately document wireless L2 connections between sites.

Key fields to add for further documenting radio links would be:

`Channel/Frequency` : *2412MHz/Chan1, 2437MHz/Chan6, 5805MHz/Chan161,  60.48GHz, etc*
`Channel-width` : *20MHz, 40MHz, 80MHz, etc*
`RSSI` :  *-55db, -70db, -90db, etc*
`SSID` : *yourSSIDhere*
`Distance`: *100m 5km, 100', etc*

### Use Case

This functionality would allow for documenting:

- Point-to-point Links
*A typical example would be a connection from device `ubnt-nanostation-ap` on interface `br0` to `ubnt-nanostation-st` on `br0.`  From there, the devices would also have your traditional `eth0` interfaces that connect the radios back VIA cabling to a switch or POE injector.  This would allow a full cable *and* WLAN trace from one end to another.*

- Point-to-multipoint Links
*Similar to PTP links with the exception that multiple remote radio `br0` interfaces would be connecting back to a single AP `br0` interface.*  

Example:  Interface `br0` on `ubnt-nanostation1-st`, `ubnt-nanostation2-st`, `ubnt-nanostation3-st` all connect back to interface `br0` on the primary backhaul radio `ubnt-nanostation-ap`

- Meshed WLAN
*This would typically be a situation where an access point is providing a meshed wireless uplink to a nearby access point that isn't directly connected to the network otherwise.  For instance, a guard station in the middle of a parking lot might have a small office with no network cabling/infrastructure.  A common solution would be to power an isolated AP via a POE injector, and then "mesh" over wireless to the nearest AP.  This could look like `meraki-mr74-outside` connected via `wlan0` to `meraki-mr74-inside`*

### Database Changes

N/A (that I'm aware of)

### External Dependencies

N/A (that I'm aware of)

**Comment by kvedder-amplex** [comment]
As I work for a WISP with many thousands of customers, I would love to see any feature to make managing that hardware easier.

**Comment by MajesticFalcon** [comment]
+1 as a WISP FISP

**Comment by sazzouz** [comment]
Also working for a WISP in London and would definitley **love** to see this implemented!

**Comment by jeremystretch** [comment]
Per the contributing guide:

> Only comment on an issue if you are sharing a relevant idea or constructive feedback. Do not comment on an issue just to show your support (give the top post a :+1: instead) or ask for an ETA. These comments will be deleted to reduce noise in the discussion.

**Comment by DanSheps** [comment]
This was previously discussed here: #2067 and there are a number of duplicates linked as well

**Comment by jeremystretch** [comment]
The previous issues were to extend the cable model to support wireless connections, which obviously does not make sense. I believe this is the first proper FR we've had for modeling wireless networks, so I'm fine with leaving it open for discussion.

**Comment by tyler-8** [comment]
`rssi` is a measurement of the signal's environment rather than a setting attached to a device. IMO that would fall under monitoring data and be outside the scope of Netbox.

I do like this idea however, it could potentially function for LTE/5G connectivity modeling.

**Comment by cbock-clairglobal** [comment]
> 
> 
> `rssi` is a measurement of the signal's environment rather than a setting attached to a device. IMO that would fall under monitoring data and be outside the scope of Netbox.
> 

True and fair enough.  I only proposed it as RSSI is one of the key metrics useful to document and reference should issues pop up or the environment change.  👍

**Comment by millijuna** [comment]
Except for the fact that Netbox deliberately seems to avoid having per-interface info other than IP and so froth, I think EIRP would be a better metric to record, rather than RSSI. That said, adding similar functionality for fiber links might also be good (record wavelength for CWDM/DWDM links, and Tx power for long-haul links). The latter is probably its own FR though.

**Comment by mokas01** [comment]
wouldn't it be useful to know which config (PtP or PtMP) has been set on each AP antenna ? Could avoid some trouble on the field (at least some PtMP AP kick all connected clients if you try to connect to them with a PtP configured station)

**Comment by MajesticFalcon** [comment]
> > `rssi` is a measurement of the signal's environment rather than a setting attached to a device. IMO that would fall under monitoring data and be outside the scope of Netbox.
> 
> @tyler-8
> True and fair enough. I only proposed it as RSSI is one of the key metrics useful to document and reference should issues pop up or the environment change. 👍

I agree. It it extremely useful to know what the "installed rssi" is. Same with fiber. "installed tx-power" and "installed rx-power." Your monitoring system "should" be able to maintain these values, but it having it documented as a custom field would also be helpful.

**Comment by MajesticFalcon** [comment]
As I am mid way through attempting to migrate different portions of our entire device management software over to netbox I have now encountered why it might not fit as well as originally hoped. We have just under 1000 radio links and there is specific information that needs to be coupled with the radio. I started using custom fields, but then quickly realized that you can't add a custom field to a specific device type. It definitely doesn't pertain to everybody, but we have the following fields for each radio. Freqency band, Service class (backhaul, repeater, access), SSID, Channel Width, Center Frequency, Azimuth, Beamwidth, Downtilt, height.

https://github.com/netbox-community/netbox/issues/722

**Comment by MajesticFalcon** [comment]
I am a little unfamiliar with the process new features go through. Does "needs milestone" mean this has been accepted and will be implemented?

**Comment by jeremystretch** [comment]
@MajesticFalcon you can see the description of each issue label [here](https://github.com/netbox-community/netbox/labels). This FR has been shelved until it gets designated as part of a future NetBox release.

**Comment by BarbarossaTM** [comment]
I really like this idea/feature and am looking for something like this for a while <3

I would propose a little different approach than the original idea an allow to only link interfaces of a WIFI type as this describes the reality better. Linking bridges might be correct most of the times, but isn't what really happens over the air.

What I'm wondering is how to denote the wifi mode (AP PTP, AP PTMP, Station) of a device/an interface/a SSID. Usually it probably will be a setting for the whole device but actually be a setting of the wifi interface/SSID.

**Comment by MajesticFalcon** [comment]
I am very excited to see this be accepted. This will allow me to finally move our entire equipment database off our custom solution to Netbox. Thank you.

**Comment by jeremystretch** [comment]
I'd like to work on fleshing out the proposed data model so that we can move forward with the feature. It's been a _long_ time since I worked directly with wireless in a professional setting, so I'll be leaning on the more familiar folks for guidance here.

In its most basic form, we can consider a wireless LAN to be a "layer one" concept; essentially a bus network. However, in practice, we often employ WLANs in one of two specific topologies:

* Point-to-point (a direct link between exactly two nodes)
* Point-to-multipoint (a multiaccess link with all spokes communicating to a common node/access point)

If we care about differentiating these topologies, the data model needs to support that.

Additionally, I could use some help determining exactly which attributes of a WLAN we need to track, and what the potential values are for each. For example:

* Type: 802.11a, 802,11g, 802.11n, ...
* Channel: Frequency, number and/or width?
* SSID
* Authentication type: None, PSK, EAP, others?

As mentioned above, we want to stick to attributes that are _administratively configurable_; so not, for example, receive signal strength or noise ration. It's also important to distinguish between attributes of the WLAN and attributes of the _interfaces_ which attach to it.

**Comment by MajesticFalcon** [comment]
I wrote a plugin model for us. Some of the features include:
Antenna gain (in dBi)
Radio max power (in dBm)
Beamwidth
Channel width
Frequency
Licensed
Dynamic frequency selection
Lan mode (routed or bridged)
Type (siso, Mimo, mumimo)

There’s probably more, but those are off the top of my head. They may not fit into the core Netbox, but they are values I wrote in the Netbox plug-in for us. Let me know if you have any more questions!

On Mar 4, 2021, at 12:21 PM, Jeremy Stretch <notifications@github.com> wrote:

﻿

I'd like to work on fleshing out the proposed data model so that we can move forward with the feature. It's been a long time since I worked directly with wireless in a professional setting, so I'll be leaning on the more familiar folks for guidance here.

In its most basic form, we can consider a wireless LAN to be a "layer one" concept; essentially a bus network. However, in practice, we often employ WLANs in one of two specific topologies:

  *   Point-to-point (a direct link between exactly two nodes)
  *   Point-to-multipoint (a multiaccess link with all spokes communicating to a common node/access point)

If we care about differentiating these topologies, the data model needs to support that.

Additionally, I could use some help determining exactly which attributes of a WLAN we need to track, and what the potential values are for each. For example:

  *   Type: 802.11a, 802,11g, 802.11n, ...
  *   Channel: Frequency, number and/or width?
  *   SSID
  *   Authentication type: None, PSK, EAP, others?

As mentioned above, we want to stick to attributes that are administratively configurable; so not, for example, receive signal strength or noise ration. It's also important to distinguish between attributes of the WLAN and attributes of the interfaces which attach to it.

**Comment by BarbarossaTM** [comment]
Hi Jeremy,

> In its most basic form, we can consider a wireless LAN to be a "layer one" concept; essentially a bus network. However, in practice, we often employ WLANs in one of two specific topologies:
> 
> Point-to-point (a direct link between exactly two nodes)
> Point-to-multipoint (a multiaccess link with all spokes communicating to a common node/access point)
> If we care about differentiating these topologies, the data model needs to support that.

Indeed. I propose a new type like "SSID" (for a lack of a better name) which is a representation of a "wireless cable/switch". I'm not having a useful word here, but I hope you see where I'm going with this.

Ideally this object has a boolean parameter for PTP vs. PTMP and depending on this setting two or more endpoints can be connected if they are compatible (see below). This way it would be possible to later "just" switch from PTP to PTMP and not having to remove and recreate the "SSID". I think this way would be preferable over two different object types even if one would have to distinguish between PTP and PTMP. On first glance it looks to my like this would only be relevant when connecting endpoint.

> Additionally, I could use some help determining exactly which attributes of a WLAN we need to track, and what the potential values are for each. For example:
> 
> Type: 802.11a, 802,11g, 802.11n, ...

One could argue that this could be defined through the endpoints being connected to the wireless connection thingy by leveraging the type of the interfaces being connected by using the first one connected and checking that the 2. one (and possibly others) are compatible (or strictly the same?).

> Channel: Frequency, number and/or width?
> SSID
> Authentication type: None, PSK, EAP, others?

Yes, those are required.

I propose:

- SSID
- Frequency (MHz)
- Channel width (MHz) (drop down with 20/40/80/160?)

Auth is harder, the obvious choices are None, WPA2-PSK and then it's getting complicated as there are a number of options for WPA2 Enterprise stuff (EAP with PAP, CHAP, TLS, TTLS, ...) and WPA3 as well as iPSK (different keys can be mapped to different networks). I'm unsure how to model this. It might be worth having something like "auth type" being one of { None, WPA2-PSK, WPA2-Enterprise, WPA3, iPSK } and having different fields for details of those. 

> It's also important to distinguish between attributes of the WLAN and attributes of the interfaces which attach to it.

Where exactly do you see the line between those parts?

Best
Max

**Comment by cbock-clairglobal** [comment]
I think most of the comments here are right on regarding common settings/fields.  To add to what’s already been said, see this screenshot<https://i.imgur.com/X2eTii3.png> taken from the wireless settings page of a newer Ubiquiti LTU Rocket.  The settings circled in red are found on pretty much all PTP/PTMP wireless bridge radios.  Those settings are:

- SSID / LINK NAME
- Key / Password
- Channel Frequency
- Channel Bandwidth
- Radio Mode (Access Point or Station)
- Access Point Mode (PTP or PtMP)
- Radio Gain / Output Power / Tx Power (dBm)
- Antenna Gain (dBm)
- Antenna Type (maybe this is just an inventory item?)

Couple notes:

Channel Frequency:  For a PTP/PTMP wireless bridge this is often represented as either a common channel number or the “center frequency” (depending on how wide the channel is).  While the channel numbers do reference particular center frequencies (see here<https://en.wikipedia.org/wiki/List_of_WLAN_channels#5_GHz_(802.11a/h/j/n/ac/ax)>), it seems like most wireless bridge radios explicitly list the center frequency in the settings pages.  Having said that, WiFi WAPs --like the kind found in buildings to connect end users to the wired network-- typically reference the operating frequency by the channel number instead (e.g. 2.4GHz channels are set to 1, 6 or 11).

One thing to keep in mind is that most wireless devices now have numerous radios-- 3x3 MIMO has 1x 2.4GHz and 2x 5GHz radios, while some<https://store.ui.com/collections/operator-airmax-and-ltu/products/gbe> PTP radios use a primary (60GHz) and failover (5GHz) radio for redundancy.   In these situations one of the device radios might mesh with another device for an uplink, while the remaining radios service clients.  That’s the case with Meraki WAPs where the  2.4GHz radios can be used to bridge/mesh a WAP while the 5GHz radios broadcast SSIDs for end user connectivity.  In those cases I could see each radio being a type of ‘interface’ with certain trackable fields being associated (SSID/VLAN, Password, Freq/Chan, Chan Width).

Radio Mode / Access Point Mode: Wireless bridges are either an AP or a station, and APs are typically set to either PTP or PTMP mode.

Type: As you mentioned, WiFi has numerous versions of 802.11 that could be referenced. As opposed to a PTP/PTMP radios which use a variety of protocols (for instance, Ubiquiti’s proprietary AirMAX<https://dl.ubnt.com/datasheets/airmax/UBNT_DS_airMAX_TDMA.pdf>) that are not 802.11 at all.  Not sure how that would be modelled or if it is even necessary.  Typically I’ve tracked/inferred that information by the model number of the devices themselves (Cisco Catalyst 9130AX = 802.11ax/WiFi6).

**Comment by cbock-clairglobal** [comment]
I think most of the comments here are right on regarding common settings/fields.  To add to what’s already been said, see [this screenshot](https://i.imgur.com/X2eTii3.png) taken from the wireless settings page of a newer Ubiquiti LTU Rocket.  The settings circled in red are found on pretty much all PTP/PTMP wireless bridge radios.  Those settings are:

**- SSID / LINK NAME**
**- Key / Password**
**- Channel Frequency**
**- Channel Bandwidth**
**- Radio Mode** (Access Point or Station)
**- Access Point Mode** (PTP or PtMP)
**- Radio Gain / Output Power / Tx Power** (dBm)
**- Antenna Gain** (dBm)
**- Antenna Type** (maybe this is just an inventory item?)

**Couple notes:**

**Channel Frequency:**  For a PTP/PTMP wireless bridge this is often represented as either a common channel number or the “center frequency” (depending on how wide the channel is).  While the channel numbers do reference particular center frequencies ([see here](https://en.wikipedia.org/wiki/List_of_WLAN_channels#5_GHz_(802.11a/h/j/n/ac/ax))), it seems like most wireless bridge radios explicitly list the center frequency in the settings pages.  Having said that, WiFi WAPs --like the kind found in buildings to connect end users to the wired network-- typically reference the operating frequency by the channel number instead (e.g. 2.4GHz channels are set to 1, 6 or 11).

One thing to keep in mind is that most wireless devices now have numerous radios-- 3x3 MIMO has 1x 2.4GHz and 2x 5GHz radios, while [some PTP radios](https://store.ui.com/collections/operator-airmax-and-ltu/products/gbe) use a primary (60GHz) and failover (5GHz) radio for redundancy.   In these situations one of the device radios might mesh with another device for an uplink, while the remaining radios service clients.  That’s the case with Meraki WAPs where the  2.4GHz radios can be used to bridge/mesh a WAP while the 5GHz radios broadcast SSIDs for end user connectivity.  In those cases I could see each radio being a type of ‘interface’ with certain trackable fields being associated (SSID/VLAN, Password, Freq/Chan, Chan Width).

**Radio Mode / Access Point Mode**: Wireless bridges are either an AP or a station, and APs are typically set to either PTP or PTMP mode.

**Type:** As you mentioned, WiFi has numerous versions of 802.11 that could be referenced. As opposed to a PTP/PTMP radios which use a variety of protocols (for instance, Ubiquiti’s proprietary [AirMAX](https://dl.ubnt.com/datasheets/airmax/UBNT_DS_airMAX_TDMA.pdf) which don't use 802.11 at all.  Not sure how that would be modeled or if it is even necessary.  Typically I’ve tracked/inferred that information by the model number of the devices themselves (Cisco Catalyst 9130AX = 802.11ax/WiFi6).

**Comment by bburrow** [comment]
More vendor agnostic interface labeling would help in cases where a Cambium or Siklu radio is used vs. Ubiquiti. Cambium does not use SSID but color codes (CC) and MAC addresses for interface referencing.

**Comment by mjducharme** [comment]
I think "Estimated Capacity" would probably be a useful metric to have as well, as the estimated maximum rate that the wireless link will be able to handle. The reason is for planning purposes - if a customer says they want a 100Mbps circuit from point A to point Z with dedicated bandwidth, you need to be able to easily make sure that you have the bandwidth available before agreeing to sell the service. Looking at live traffic for that information is not necessarily a good metric because there may be an outage that is temporarily removing some of the traffic that would normally be travelling across those links, and also the need to make sure enough bandwidth is left over for retail customers to use.

**Comment by mattguthmiller** [comment]
In an enterprise/carrier setting, microwave links do not transmit and receive on the same frequency, so it would be helpful to have separate fields for each.

**Comment by JumperPunk** [comment]
Can I get some clarification on the scope of this? Most of the comments seem centered around wireless connections between managed devices (e.g., mesh), but some of the conversation seems to also relate to APs for end users to connect to (e.g., AP to STA). Is the second one in scope here?

> Auth is harder, the obvious choices are None, WPA2-PSK and then it's getting complicated as there are a number of options for WPA2 Enterprise stuff (EAP with PAP, CHAP, TLS, TTLS, ...) and WPA3 as well as iPSK (different keys can be mapped to different networks). I'm unsure how to model this. It might be worth having something like "auth type" being one of { None, WPA2-PSK, WPA2-Enterprise, WPA3, iPSK } and having different fields for details of those.

Technically, the different authentication methods within WPA2 (non psk) is a a function of the authentication server, not the AP. Of course, if you are also configuring the STA (e.g., the remote end of a bridge), then these things still need to be configured.

> Radio max power

This can mean several different things:
- max power that can be configured (a hardware limit of the radio/antenna)
- max power allowed by the regulatory domain (what the FCC will allow for this radio/antenna)
- upper end of the range the admin set to allow the AP to choose within (note, this also implies a min power)

**Comment by jeremystretch** [comment]
> Can I get some clarification on the scope of this?

I find myself asking the same question. :laughing:

As we've seen, there's certainly a lot involved in modeling wireless connections. I think my biggest hurdle at this point is properly decoupling the physical layer (channel frequency and bandwidth) from the data layer (SSID, AP mode, etc.). It's also evident from the discussion that some distinction needs to be made between traditional WLAN point-to-point links and those which utilize microwave transponders.

As we're currently targeting early April for the first v2.11 beta release, I'm not sure we'll have sufficient time to form and flesh out a suitable model. IMO it would be best at this point to punt this implementation to v2.12 and dedicate more time to ensuring we our modeling approach is correct. It would be ideal to form a sort of working group with several wireless experts to help guide this initiative.

**Comment by jeremystretch** [comment]
We're going to have to punt this from v2.11 unfortunately, to provide time to identify and draft a sufficiently robust implementation of the wireless model.

**Comment by jeremystretch** [comment]
Tentatively tagging this for v2.12, though we clearly still need a game plan.

**Comment by millijuna** [comment]
IMHO, the KISS principle should be followed as much as possible. The critical info for wireless links seems to be frequency, wireless type, and unit role. My biggest concern is that adding wireless type as an enumerated type would lead to the same situation that's with cable interface types, which becomes a maintenance problem for maintainers. Could not the other functions mentioned (max power, antenna gain, etc... ) be handled through custom fields or similar?

**Comment by martinum4** [comment]
Maybe separate Wireless networks and the interface stuff from each other, kind of similar to the Provider Networks feature.
E.g. Model the wireless network first, then add a connection between interface and network.

Preferably we would have the options for antennas too and have them integrated in a trace feature.

Example-Trace: 
Device A;Interface A <-> Cable-A1 <-> Patchpanel A <-> Cable-A2<-> Antenna-A <-> Wireless-network <-> Antenna-B <-> Cable-B <-> Device B; Interface B 

Location of the Antennas can be done conventionally over the locations (e.g. Location Mast A, sublocation 20 Meters, sublocation 40 Meters)

Also, why stop at WLAN? In the basic this feature could be useful for cellular or WiMAX network operators too.

**Comment by jeremystretch** [comment]
Bumping this from v2.12 as we've decided to focus primarily on the UI overhaul for this release. Will revisit soon. I'd actually like to put together a working group of wireless experts in the meantime to help inform the modeling.

**Comment by ZPrimed** [comment]
My employer is a non-profit WISP using multiple different technologies (5GHz P2MP, 60GHz & 80GHz mmWave P2P and P2MP, and soon, LTE over CBRS), so I'm very interested in this. It's definitely worth noting that not all links necessarily follow the same "WLAN" standards (802.11a/b/g/n/ac/ax behave somewhat differently from ad & ay, and then there are vendors who have their own "special sauce" so they don't work like a normal "WLAN" product), and hence not every field will apply to every "wireless link".

I'd be happy to provide insight into some of the tech and useful fields to document (most have already been mentioned), but I'm unfortunately not much of a coder. 

The biggest thing that I'd add is that some additional physical info about the radios / endpoint devices would be useful as well, like installation height, azimuth, antenna beamwidth, downtilt, and possibly something like mast / pole number (e.g. for building rooftops with multiple installation locations, although I suppose that could be faked as multiple "racks" at a site).

**Comment by jeremystretch** [comment]
> I'd be happy to provide insight into some of the tech and useful fields to document (most have already been mentioned), but I'm unfortunately not much of a coder.

We're actually planning to set up a volunteer working group to gather feedback on the proposed data model from wireless experts. Be sure to stay subscribed to this issue for more info on that in the near future!

**Comment by DevilWAH** [comment]
Would like to see this one develop, aside from the point to point links 

I would also like to be able to record what controls an AP belong to and what SSID it should be broadcasting / templates applied, with several 100 offices the same SSID my be configured differently between locations, different methods for authentication / tunneling. and some SSID should only be broadcast is specific locations. So the ability for each AP to say 

1. WLC = <link to device>
2. Wireless template = .....
3. SSID list = .....
4. Channel = ...
5. TX power = ....

would help when requesting 3rd party support need to deploy or replace AP's 

Our method of working is to configure netbox with what needs to be deployed and hand over to a 3rd party to do it. The clearer we can make this information the less change there is for confusion.

**Comment by jeremystretch** [comment]
> We're actually planning to set up a volunteer working group to gather feedback on the proposed data model from wireless experts. 

And here it is! Please sign up [using this form](https://forms.gle/18kRuKDAYpJvNDZv6) if you'd like to participate. We're hoping to form a small but diverse group, so we may not be able to include everyone at this stage.
