### ISSUE TITLE
SVG rack elevations: No pop-ups for reserved units

### ISSUE THREAD

**Issue by megazloj** [netbox-community/netbox#3982]
### Environment
* Python version:  3.6.9
* NetBox version:  2.7.2

Previously you could hover over a reserved object and a window pops up with information about the tenant / description of this reservation.

### Expected Behavior
Pop-up appear over reserved unit on mouse hover.

### Observed Behavior
Pop-up not showing up.

![image](https://user-images.githubusercontent.com/7577925/72877687-26e51e00-3d02-11ea-8770-c58710f86b65.png)
![image](https://user-images.githubusercontent.com/7577925/72877719-306e8600-3d02-11ea-88b8-62b321fd123b.png)

**Comment by jeremystretch** [comment]
@hellerve Do you want to take this one too? If not I'll give it a shot.

**Comment by hellerve** [comment]
I can take this on; it shouldn’t be too hard!
