### ISSUE TITLE
Printing a rack is not as expected

### ISSUE THREAD

**Issue by aamsaleg** [netbox-community/netbox#3986]
### Environment
* Python version:  3.6.9
* NetBox version:  2.7.2

Hi

Printing a rack on paper and/or pdf show devices under U1.
Here an example of a rack with version 2.7.2
<img width="614" alt="rack-2 7 2" src="https://user-images.githubusercontent.com/25366020/72915028-ef956200-3d3f-11ea-906d-0dfd0b0eb931.png">

Here, the same rack with version 2.6.11
<img width="687" alt="rack-2 6 11" src="https://user-images.githubusercontent.com/25366020/72915091-09cf4000-3d40-11ea-8a8b-dc88f03cf830.png">

### Steps to Reproduce
1. choose a rack with devices
2. print it on pdf (or use preview on MacOS)
3. All devices appears under the floor :)

### Expected Behavior
Devices are in the rack

### Observed Behavior
Devices are under the rack

**Comment by candlerb** [comment]
What you describe appears to be similar to #4110 - a side-effect of changing to SVG (#2435)

Related printing issues: #160 #2248  #3175

(Aside: the bot seems overly zealous to mark this issue as "stale" and "wontfix" so quickly)
