### ISSUE TITLE
Supervisord contrib config file and documentation update

### ISSUE THREAD

**Issue by pobk** [netbox-community/netbox#3992]
### Change Type
[x] Addition
[ ] Correction
[ ] Deprecation
[ ] Cleanup (formatting, typos, etc.)

### Proposed Changes

I've put together a documentation update and included a contrib config file for *nix systems that don't have systemd (e.g. FreeBSD) to deploy supervisord instead of systemd.

Pull request pending approval of this FR/Doc update.

**Comment by jeremystretch** [comment]
Although I appreciate the effort, I'm afraid we can't accept the burden of maintaining this in addition to what we have already. However I'd be happy to link to it from [our wiki](https://github.com/netbox-community/netbox/wiki/Community-Contributions) if you'd like to publish it separately.

**Comment by pobk** [comment]
I think it's a shame the netbox community is favouring documenting a systemd approach...

Docs added to a separate repo: https://github.com/pobk/netbox-supervisord
