### ISSUE TITLE
Navigation bar too tall

### ISSUE THREAD

**Issue by hSaria** [netbox-community/netbox#3995]
### Environment
* Python version: 3.6.8
* NetBox version: 2.7.2

### Steps to Reproduce
1. Go to a page that is not too long (`/dcim/manufacturers/` or `/dcim/regions/` are good examples as long as you only have a couple of objects)
2. Expand one of the long drop down menus, like `Devices` and have it extend beyond the page's contents
3. Attempt to reach the lower options in the drop down menu 

### Expected Behavior

The navigation bar and its dropdown menus are scrollable

### Observed Behavior

The overflowing elements are unreachable

Dropdown menu
<img width="523" alt="image" src="https://user-images.githubusercontent.com/34197532/73017172-36a25680-3e17-11ea-8140-28ae5151e715.png">

Navbar is not scrollable
<img width="505" alt="image" src="https://user-images.githubusercontent.com/34197532/73017366-9bf64780-3e17-11ea-8902-5d8f65b10773.png">

**Comment by hSaria** [comment]
This ought to fix it.

```diff
diff --git a/netbox/project-static/css/base.css b/netbox/project-static/css/base.css
index 45babe70..f9d8e1fa 100644
--- a/netbox/project-static/css/base.css
+++ b/netbox/project-static/css/base.css
@@ -62,8 +62,20 @@ footer p {
     }
 }
 
+/* Scroll the drop-down menus at or above 768px wide to match bootstrap's behavior for hiding dropdown menus */
+@media (min-width: 768px) {
+    .navbar-nav>li>ul {
+        max-height: 70vh;
+        overflow-y: scroll;
+    }
+}
+
 /* Collapse the nav menu on displays less than 980px wide */
 @media (max-width: 979px) {
+    #navbar {
+        max-height: 70vh;
+        overflow-y: scroll;
+    }
     .navbar-header {
         float: none;
     }
```

**Comment by DanSheps** [comment]
Hey @hSaria, if you are willing to do the PR for this, I do agree this is probably something that should be fixed.

**Comment by hSaria** [comment]
@DanSheps could you reopen #3997 please? I'm all open for constructive criticism; I only picked the values to address the issue and look relatively neat, but I've no scientific reason for them specifically.
