### ISSUE TITLE
Errors in migrating-to-systemd instructions

### ISSUE THREAD

**Issue by candlerb** [netbox-community/netbox#3996]
### Change Type

[ ] Addition
[X] Correction
[ ] Deprecation
[ ] Cleanup (formatting, typos, etc.)

### Proposed Changes

There are several issues with the migrating to systemd instructions at https://netbox.readthedocs.io/en/latest/installation/migrating-to-systemd/

1. It says `If using CentOS/RHEL.` (with a trailing full stop), making it unclear which of the following step(s) it qualifies.

2. It talks about creating `/etc/sysconfig/netbox.env`.  This is completely redundant; all other references to netbox.env were removed in commit 9352867c

3. It tells you to create `gunicorn.conf`, whereas it should be `gunicorn.py`.  Looking through git history, at previous times in development it went through `gunicorn.conf` and `gunicorn_config.py`, and I don't know what 2.6 users would have had.  Maybe existing users can rename their existing file - or at worst they create  `gunicorn.py` from scratch from the `contrib/` sample.

In general, I think this doc needs to be made consistent with the primary installation instructions for systemd at https://netbox.readthedocs.io/en/latest/installation/3-http-daemon/#systemd-configuration

**Comment by jeremystretch** [comment]
FYI we don't use checkbox markup in the template because GitHub interprets them as tasks to be completed:
![Screenshot_2020-01-23 netbox-community netbox](https://user-images.githubusercontent.com/13487278/73020180-19f42780-3df3-11ea-9518-e7d964b63981.png)

**Comment by kobayashi** [comment]
@candlerb 
Is this duplicated #3961? If so, please comment to the issue for further discussion.
