### ISSUE TITLE
Add General Search to Console/Power/InterfaceConnection Views

### ISSUE THREAD

**Issue by zachmoody** [netbox-community/netbox#3998]
### Environment
* Python version:  3.6.9
* NetBox version:  2.6.12

### Proposed Functionality
Add a general `CharFilter` field search to Console/Power/InterfaceConnections views, similar to the `q` filters found elsewhere that allow filtering by partial device name.

### Use Case
Before https://github.com/netbox-community/netbox/commit/80d1f80b61e7887bc6c2a88244b0bf2f16f84e17 the Console/Power/InterfaceConnectionFilter's filter_device method searched partial device names. That's since been replaced with a select2 form field for device, but that approach somewhat limits the ability to search for a group of connections that share the same partial device names for export into CSV or export templates for things like cable labels.

### Database Changes
N/A

### External Dependencies
N/A

**Comment by zachmoody** [comment]
:wave: Happy to make the PR on this, just wanted to know if it's a feature yall want and if that's a decent approach.

**Comment by DanSheps** [comment]
Hey @zachmoody,

Sorry I didn't catch this.  Is this something that the q= filter is not catching?

**Comment by zachmoody** [comment]
Hey @DanSheps 👋 - well I'm looking to see if a q= filter is something yall would be open to adding on these endpoints, afaict, there isn't one there now.

I did make a pass at if we could use the q= filter on Cables instead but ran into an issue of there of it being limited in scope to just cable labels (iirc) and not the devices they're connected to.

**Comment by jeremystretch** [comment]
This should be covered by #2101, which applies to _all_ models/views. Honestly there's probably not much left to do for that one at this point. I'll take another look at it.
