### ISSUE TITLE
Custom field with type Text/Selection from remote URL

### ISSUE THREAD

**Issue by itmicus** [netbox-community/netbox#4003]
### Environment
* Python version:  3.5
* NetBox version:  2.7

### Proposed Functionality
Custom filed type Text or Selection can also be requested from an external source using a "remote URL". URL to remote JSON Service for example:
https://db.company.local/options?opt1={{obj.name}}
Also may be add feature to sort values, URL contains jinja templating with fields from netbox object.

### Use Case
You can assign data to the custom field from the external system for create relations between them.

### Database Changes
may be

### External Dependencies
no

**Comment by jeremystretch** [comment]
Sorry, this would be way out of scope for custom fields and very difficult to implement.
