### ISSUE TITLE
Invalid choice when changing tenant

### ISSUE THREAD

**Issue by hSaria** [netbox-community/netbox#4015]
### Environment
* Python version:  3.6.8
* NetBox version:  2.7.2

### Steps to Reproduce
1. Create tenant group `tg1`, tenant `t1` in group `tg1`, and tenant `t0` with no group
2. Create site and set tenant to `t1` (in a group)
3. Edit the site, clean the tenant group, and set tenant to `t0` (not in a group).

> This affects any object that supports tenancy; I used Site as an example.
 
The chain is limiting the queryset, and therefore the choices, to only those in the current group during form initialization. 

https://github.com/netbox-community/netbox/blob/7a548e806da74b6ae53529411c65400b080b67ef/netbox/tenancy/forms.py#L136-L140

### Expected Behavior
Tenant is changed

### Observed Behavior
Validation error indicating that the choice is not available. The workaround is to remove the tenant entirely, save the object, then add the new tenant.

**Comment by jeremystretch** [comment]
The issue seems to be that `tenant_group` is not being sent in the form data. The form relies upon `tenant_group` being set to `null` for validation. I'm not sure why the field is being omitted. (Other ForeignKey fields, such as region, are included even when null.)

**Comment by hSaria** [comment]
Another related bug is selecting a tenant that is in a group, but not populating the tenant group field. Like most other hierarchical fields, the tenant group should only be there to limit the tenant choices (i.e. someone can pick a tenant without needing to specify the group).

I'm not sure if this related bug is fixed if the tenant group was included with value of null.

**Comment by hSaria** [comment]
This is fixed indirectly with #3912.
