### ISSUE TITLE
Update markdown dependency to markdown 3.x

### ISSUE THREAD

**Issue by robbat2** [netbox-community/netbox#4018]
### Proposed Changes
Update `markdown` to `markdown-3`. This does require reviewing for breaking changes in line with the new major version.

### Justification
- Markdown 2.x is more than 2 years old now, and all future development upstream is on Markdown 3.x series. 
- Future security issues found in Markdown 2.x will not be fixed there.

**Comment by jeremystretch** [comment]
[py-gfm](https://github.com/Zopieux/py-gfm) requires Markdown < 3.0.

If there is a specific feature you'd like to request or bug you'd like to report, please use the applicable issue template.
