### ISSUE TITLE
Create devices without specifying a name

### ISSUE THREAD

**Issue by marcelb98** [netbox-community/netbox#4020]
### Environment
* Python version:  3.7.6
* NetBox version:  a9ff06a6ee4e (v2.7.2)

### Steps to Reproduce
1. Create a rack
2. Add a new device to the rack, without defining a name for the new device

### Expected Behavior
Since the name for devices is not marked as a mandatory field, it should be possible to create a device without specifying a name.
![grafik](https://user-images.githubusercontent.com/20777899/73141857-dc103100-4088-11ea-9353-b5d862e50f57.png)

For some devices (e.g. cable routing) the name is irrelevant, the only necessary information is the existence of the device. The name of the corresponding device type could be used for the name of the device.

This was possible in previous versions of Netbox.

### Observed Behavior
Submitting the form without specifying a device name results in an error:
![grafik](https://user-images.githubusercontent.com/20777899/73141911-71132a00-4089-11ea-97b5-2829b97499aa.png)

Typing in the name of the device type manually isn't a fix since it would be only possible to create a single device of this type with the name of the type.

**Comment by hSaria** [comment]
This was fixed in #3983 which will be included in the next version of NetBox (v2.7.3).
