### ISSUE TITLE
Different colours for "planned" and "connected" cables

### ISSUE THREAD

**Issue by candlerb** [netbox-community/netbox#4025]
### Environment
* Python version:  3.5.2
* NetBox version:  2.7.2

### Proposed Functionality

Currently, in cable trace view, both "Planned" and "Connected" statuses are shown in green.  I would like to see a contrasting colour.

![image](https://user-images.githubusercontent.com/44789/73218131-3aa0e200-4151-11ea-844c-7ec9fabee5ba.png)

### Use Case
Browsing cable path; identifying patch leads which have yet to be installed (or documented as installed)

### Database Changes
None

### External Dependencies
None

**Comment by hSaria** [comment]
This looks like bug as the cable list (`/dcim/cables/`) correctly shows planned as light blue. At any rate, fixing this is pretty simple

```diff
--- a/netbox/templates/dcim/cable_trace.html
+++ b/netbox/templates/dcim/cable_trace.html
@@ -32,7 +32,7 @@
                             {% if cable.label %}<code>{{ cable.label }}</code>{% else %}Cable #{{ cable.pk }}{% endif %}
                         </a>
                     </h4>
-                    <p><span class="label label-{% if cable.status %}success{% else %}info{% endif %}">{{ cable.get_status_display }}</span></p>
+                    <p><span class="label label-{{ cable.get_status_class }}">{{ cable.get_status_display }}</span></p>
                     <p>{{ cable.get_type_display|default:"" }}</p>
                     {% if cable.length %}{{ cable.length }} {{ cable.get_length_unit_display }}{% endif %}
                     {% if cable.color %}
```

**Comment by jeremystretch** [comment]
I can't wait to see how many more of these we find. :unamused:

**Comment by hSaria** [comment]
Already found a whole bunch of them on the device's interface templates. If an interface's cable is planned, the background is still green.
