### ISSUE TITLE
IPAddress DHCP status is not migrated

### ISSUE THREAD

**Issue by shuichiro-makigaki** [netbox-community/netbox#4027]
### Environment
* Python version:  3.7
* NetBox version:  2.7.2

### Steps to Reproduce
1. Upgrade from v2.6.3
2. Execute migration
2. Show IPAddress whose status is "DHCP"

### Expected Behavior
Show the IP correctly

### Observed Behavior
* The status column/row shows nothing (actually, shows string "5" as Invisible Man)
* IPAddress resource API returns an error: `Key Not Found: '5'`

**Comment by DanSheps** [comment]
Thank you for your interest in NetBox. GitHub issues are intended for reporting reproducible bugs and requesting features, and must be submitted using one of the templates provided [here](https://github.com/digitalocean/netbox/issues/new/choose). For general discussion, questions, or assistance with installation issues, please post to our [mailing list](https://groups.google.com/forum/#!forum/netbox-discuss) instead.

**Comment by DanSheps** [comment]
To be clear, I have attempted to reproduce this at https://master.netbox.dansheps.com and I am unable to.

Please provide exact steps to reproduce if you wish for us to revisit this, however this seems like it may be a missing step in a upgrade rather then a bug at first glance.

**Comment by shuichiro-makigaki** [comment]
@DanSheps 
Thank you for your quick response. I added some reproducing procedures.

It seems that ba8f324 does not migrate the status "DHCP" to slug.

**Comment by DanSheps** [comment]
Alright, this helps now, I will have to go back to 2.6.x and test this out

**Comment by DanSheps** [comment]
Just as a quick update, the migration code is in there, so unless something else is happening it should migrate.

Are you fully migrated (can you try running the migrations again?)

**Comment by shuichiro-makigaki** [comment]
> Are you fully migrated

Yes. By running `manage.py migrate`.

https://github.com/netbox-community/netbox/blob/master/netbox/ipam/migrations/0029_3569_ipaddress_fields.py#L4

`IPADDRESS_STATUS_CHOICES` should contain `(5, 'dhcp')`, I think.
The `0029` migration updates IPAddress status to slug, except for DHCP.

**Comment by shuichiro-makigaki** [comment]
> (can you try running the migrations again?)

It is hard to rerun the migration. I have already created a new migration patch and applied it.
(https://github.com/shuichiro-makigaki/netbox/commit/2897232af5c7cf24b50f1a5be4f1d7ba0866ba1d_
As a result, this problem is solved by the patch.

**Comment by candlerb** [comment]
FYI: I see the same problem.  In a system migrated from 2.6 to 2.7:

```
netbox=# select status,count(*) from ipam_ipaddress group by status;
   status   | count
------------+-------
 5          |   134
 deprecated |    18
 active     |  1230
 reserved   |    28
(4 rows)
```

I hadn't noticed until now - thanks for detecting this.

In the GUI, status displays as a white 5 on a white background, which is invisible.  When you hover over it, the background changes to grey so it is visible (just).

**Comment by jeremystretch** [comment]
The PR above will fix this, but if you'd rather not wait for the next release, you can do this to apply the fix immediately:

```$ ./manage.py nbshell
### NetBox interactive shell (jstretch-workstation)
### Python 3.6.9 | Django 2.2.9 | NetBox 2.7.3-dev
### lsmodels() will show available models. Use help(<model>) for more info.
>>> IPAddress.objects.filter(status='5').update(status='dhcp')
0
```

(The number returned at the end indicates the number of IP addresses updated.)
