### ISSUE TITLE
Non-ascii tag on site breaks tag listing and home page

### ISSUE THREAD

**Issue by dare-to-recurse** [netbox-community/netbox#4028]
### Environment
* Python version:  3.6.8
* NetBox version:  2.7.2

### Steps to Reproduce
1. Create site with name Demo Site
2. Edit "Demo Site", tag it with länk
3. Navigate to Organization > Tags

### Expected Behavior
To see the listing of tags or home page

### Observed Behavior
Server error with the following message

```
<class 'django.urls.exceptions.NoReverseMatch'>

Reverse for 'tag' with arguments '('länk',)' not found. 1 pattern(s) tried: ['extras\\/tags\\/(?P<slug>[-a-zA-Z0-9_]+)\\/$']
```

**Comment by jeremystretch** [comment]
This was missed in the work on #3721. We need to extend the URL pattern to match Unicode characters in the slug.
