### ISSUE TITLE
Support Internal Certificate Authority Validation for LDAPS

### ISSUE THREAD

**Issue by newlandk** [netbox-community/netbox#4038]
### Environment
* Python version:  3
* NetBox version:  2.7.2

### Proposed Functionality
Support providing the path to a custom certificate authority certificate bundle for validating LDAPS server certificate.

Add a `getatter` similar to https://github.com/netbox-community/netbox/blob/develop/netbox/netbox/settings.py#L381-L382 for setting the OPT_X_TLS_CACERTFILE to allow validation of internal certificate authorities. This support appears to be missing from the django-ldap-auth backend natively.

### Use Case
Enhance security throughout the LDAP bind process.

### External Dependencies
python-ldap
django-ldap-auth

**Comment by newlandk** [comment]
If this is a feature the maintainers deem appropriate for addition in the netbox project, I can make a PR for this functionality. Thank you!

**Comment by DanSheps** [comment]
External authentication is going to be abstracted away as per #2328.

I am going to close this out due to that reason.

**Comment by hSaria** [comment]
This is already possible. In `ldap_config.py`, put:
```
import ldap

# Set the CA certificate location for LDAP
ldap.set_option(ldap.OPT_X_TLS_CACERTFILE, '/path/to/cacert.pem')
```

**Comment by hSaria** [comment]
This is already possible. In `ldap_config.py`, put:
```
import ldap

ldap.set_option(ldap.OPT_X_TLS_CACERTFILE, '/path/to/ca_cert.pem')
```

**Comment by newlandk** [comment]
Thank you @hSaria that is what I had working, I wasn't sure if there was interest in having it be a more explicit option since there is the getattr to disable validation.

**Comment by hSaria** [comment]
If it were up to me, I'd take `LDAP_IGNORE_CERT_ERRORS` entirely out and just tell people about the ability to modify ldap options as this isn't something limited to NetBox, but as DanSheps mentioned, this whole thing is gonna get reworked eventually.
