### ISSUE TITLE
Update LDAP Cache Configuration Docs

### ISSUE THREAD

**Issue by newlandk** [netbox-community/netbox#4039]
### Change Type
[ ] Addition
[X] Correction
[X] Deprecation
[ ] Cleanup (formatting, typos, etc.)

### Proposed Changes
Update LDAP caching configuration. https://github.com/netbox-community/netbox/pull/4037

django-ldap-auth uses new configuration for caching as of 1.6.0

Reference to settings.py configuration: 695a07d#diff-a1b75c101e583ea1264c4c0c390db558R297

**Comment by DanSheps** [comment]
External authentication is going to be abstracted away as per #2328.

I am going to close this out due to that reason.
