### ISSUE TITLE
Access (View) permissions per site

### ISSUE THREAD

**Issue by Soeren-FT** [netbox-community/netbox#4040]
### Environment
* Python version:  3.6
* NetBox version:  2.7.2

### Proposed Functionality
Set Access permissions for netbox user for each site.

### Use Case
We have several sites with individual administrators and would like to restrict access to the individual sites.

**Comment by sdktr** [comment]
https://github.com/netbox-community/netbox/issues/554 coversthe multi-tenancy / object based permissions you're looking for
