### ISSUE TITLE
Setting required=False on a custom script variable has no effect

### ISSUE THREAD

**Issue by HaehnleinMar** [netbox-community/netbox#4043]
Using NetBox 2.7.3 all fields in custom scripts are required (in the html input the required flag is set, when sending it anyways NetBox reports that the field is required).

# Environment
* Python version:  3.7.6
* NetBox version:  2.7.3

### Steps to Reproduce
1. Have a custom script with a field with `required = False`
2. Try leaving the field empty
3. Fail

### Expected Behavior
The html input is not required and a submit with the field being empty succeeds.

### Observed Behavior
The html input is required and a submit with the field being empty fails.

**Comment by jeremystretch** [comment]
Will be fixed in v2.7.4, but as a temporary workaround you can do this:

```python
class MyCustomScript(Script):
    foo = StringVar()

    def __init__(self):
        super().__init__()
        self.foo.field_attrs['required'] = False
```
