### ISSUE TITLE
Increase maximum cable segment length

### ISSUE THREAD

**Issue by agebel** [netbox-community/netbox#4045]
### Environment
* Python version:  3.6.8
* NetBox version:  2.7.2

### Proposed Functionality
 Increase maximum length of a given cable segment to facilitate recording inter-site connections, backhaul runs, etc.

### Use Case
Currently, the maximum length for a given cable segment is 32767 meters. This creates difficulty when documenting cable runs (e.g. fiber connections) connecting sites more than 33 km apart. Network operators, those leasing dark fiber point-to-point connections, etc would benefit from being able to document longer connections.

### Database Changes
I'm still learning Django, so can't say for sure, but I think perhaps simply changing the cable model's _length_ field from `'length', models.PositiveSmallIntegerField` to 
`'length', models.PositiveIntegerField` would suffice as it would allow for 2B+ meter runs at a maximum cost of just 2 bytes per instance.

Perhaps it would make sense to update the field so that a validator is used to limit the length to a rational maximum.

If accepted, I would be more than happy to attempt to implement any recommended/desired changes and submit any necessary pull requests.

### External Dependencies
None (that I can tell)

**Comment by jeremystretch** [comment]
Cables are intended to represent contiguous physical connections between two points. To represent a long-haul communications circuit, use the circuit model.
