### ISSUE TITLE
systemd unit file note

### ISSUE THREAD

**Issue by oidz1234** [netbox-community/netbox#4046]
### Change Type
[X ] Addition
[ ] Correction
[ ] Deprecation
[ ] Cleanup (formatting, typos, etc.)

### Proposed Changes

I would like to contribute a note to the documentation. It will inform the reader of the need to change the user the services are running as. The reason for this is that on different distributions Apache runs as different users. For example, On Ubuntu the user is "www-data" Whereas on CentOS it is "apache"

**Comment by dsg-anthony** [comment]
Should users use the www-data/apache user or should users create a separate user to run the netbox service?

**Comment by oidz1234** [comment]
I belive it to be fine to use whatever the default system user that apache runs as.

**Comment by jeremystretch** [comment]
What specifically do you want to add/change?

**Comment by oidz1234** [comment]
I would like to add a small note about making sure your netbox systemd service is running under the correct user.
Please see this closed PR:
https://github.com/netbox-community/netbox/pull/4042

**Comment by DanSheps** [comment]
I do think we should have something, not sure what the best way to phrase it would be.

Nginx runs as nobody on Centos by default

**Comment by dsg-anthony** [comment]
You could just create a new system user
 
`useradd -r netbox`

This should work on all mainstream Linux distros and reduce the confusion on what account to run with. 😉

It does add a bit of confusion when managing file permissions though.

**Comment by oidz1234** [comment]
I think using the default system user for installation is best practice. Also I have only installed netbox under Apache. If default Nginx user differs between distributions then this will also need a note.

**Comment by candlerb** [comment]
I'd say creating a distinct 'netbox' user is best practice (and this is what I do).  If you have multiple web apps on a server, then for security you want them all running as distinct uids, not all as "www-data" or whatever.

There is some potential for confusion for existing users though, if the documentation now changes to using a "netbox" user.

**Comment by oidz1234** [comment]
If that is the agreed method then fine. Although there will be many more places (I expect) In the documentation that will need to be updated also.

**Comment by DanSheps** [comment]
I think the only issue with this is certain files need to be readable by the webserver, so either they need to be chgrp to the webserver group or world readable

**Comment by jeremystretch** [comment]
Let's be cognizant of the scope of the documentation we provide. It's very easy to wander away from installing NetBox to discussing alternative installations, best configuration practices, and so on. The installation docs have always assumed a basic level of understanding around configuring an HTTP service, which includes determining the user under which the service should run.

I think it's fine to mention creating a "netbox" user as an option, but let's not deviate any further from what exists today.

**Comment by jeremystretch** [comment]
This was ultimately addressed during the alteration of the installation instructions under #3949.
