### ISSUE TITLE
Deleting a device photo does not remove the image from external storage.

### ISSUE THREAD

**Issue by dsg-anthony** [netbox-community/netbox#4047]
### Environment
* Python version: 3.6
* NetBox version: 2.7.1

### Steps to Reproduce
1. Add photo to device
2. Remove device or device photo

### Expected Behavior
Deleting a device or device photo should remove the image from the external storage

### Observed Behavior
Image is deleted from netbox but the photo is left untouched in the external storage. In my case this is a Google Cloud Bucket.

**Comment by jeremystretch** [comment]
Please provide the complete set of steps necessary for someone else to reproduce this issue, including your storage configuration.

This sounds like an issue with the external storage library, [django-storages](https://django-storages.readthedocs.io/en/stable/). If that's the case, you'll need to raise an issue against that project as NetBox has no control over how it handles files.

**Comment by dsg-anthony** [comment]
Well I just tested it again and it worked. If it happens again I'll capture some logs and the complete steps.

For documentation sake here is my storage configuration for external storage for google cloud storage.

```
from google.oauth2 import service_account
STORAGE_BACKEND = 'storages.backends.gcloud.GoogleCloudStorage'
GS_CREDENTIALS=service_account.Credentials.from_service_account_file("/etc/netbox/login-creds.json")
STORAGE_CONFIG = {
    'GS_BUCKET_NAME': 'netbox_prod',
    'GS_PROJECT_ID': 'ID_GOES_HERE',
    'GS_CREDENTIALS': GS_CREDENTIALS,
}
```
