### ISSUE TITLE
Allow planned cables to use currently used interfaces

### ISSUE THREAD

**Issue by jpqpi** [netbox-community/netbox#4058]
### Environment

NetBox version:   2.7.2 

### Proposed Functionality

Currently there doesn't seem to be a way to facilitate planned upcoming cable moves without deleting (and therefore losing) the current connectivity info because NetBox won't allow a planned cable to use an interface that is currently in use. 

Similar to VIP IP addresses allowing duplicate entries in the database, allowing "planned" cables to use interfaces that are currently marked "active" would better capture a future planned move for this cable while preserving the current state.

### Use Case

By allowing "planned" and "active" cables to the same interface in the database, users would see both the current state of the connectivity and the future planned state. when the operational works are complete the active cable could then be easily deleted and the planned cable could be changed to active instead of either a) overwriting the current connectivity with planned works or b) having to wait till after the work is completed to update the design.

### Database Changes

Allow both a "planned" and an "active" connection to each interface in the cable section of the database.

**Comment by DanSheps** [comment]
This issue has been closed as it does not conform to one of the [provided templates](https://github.com/digitalocean/netbox/issues/new/choose) as required by the [contributing guide](https://github.com/digitalocean/netbox/blob/master/CONTRIBUTING.md). If you'd like to request that your issue be re-opened, please first update the content so that it matches the appropriate template (this may require rewriting your issue entirely).

**Comment by jpqpi** [comment]
Hi Dan, I'm sorry but I'm not sure how to request that this to be reopened. Could you help me?

**Comment by phurrelmann** [comment]
this feature would ease refactoring and rewiring of racks. currently one has to plan the cabling outside of netbox, because the new cables can't be modeled unless the productive ones are removed.

**Comment by jeremystretch** [comment]
While I agree that this would be a nice feature, it would be an absolute nightmare to implement. It would require largely reworking the entire physical cabling model, not to mention devising a mechanism to toggle between "current" and "future" views in the UI. It's just not something we'll be able to spend the necessary development time on in the near future.

**Comment by jpqpi** [comment]
Thanks for getting back to me on this, its highly appreciated.

Paul
