### ISSUE TITLE
migrating to systemd referncing contrib files that do not exist.

### ISSUE THREAD

**Issue by TBTT** [netbox-community/netbox#4059]
### Change Type
[ ] Addition
[X] Correction
[ ] Deprecation
[ ] Cleanup (formatting, typos, etc.)

While upgrading from v2.6.7, I noted reference to NetBox installation documentation has been updated to provide instructions for managing the WSGI and RQ services using systemd instead of supervisor. This removes the need to install supervisor and simplifies administration of the processes.

According to the [migrating to systemd](https://netbox.readthedocs.io/en/stable/installation/migrating-to-systemd/) document, instructions are to copy **contrib/netbox.env** and **contrib/gunicorn.conf**, however, neither of these files exist in contrib.

Please advise.

**Comment by DanSheps** [comment]
Thank you for submitting this issue, however it appears that this topic has already been raised. Please see issue #3961 for further discussion.

**Comment by TBTT** [comment]
When do proposed changes with correct instructions get pushed out?
