### ISSUE TITLE
List ChoiceField choices in Swagger as enum

### ISSUE THREAD

**Issue by deathbeam** [netbox-community/netbox#4062]
### Environment
* Python version:  3.7.3
* NetBox version:  2.7.2

### Proposed Functionality

Based on this specification https://swagger.io/docs/specification/data-models/enums/ the ChoiceField choices for label and value can (and should) be listed as enums.

### Use Case

Proper generation of API model from openapi specification for 3rd party projects without requirement to query OPTIONS for each endpoint to receive extra data from django. For example we are generating Java API for Netbox based on openapi spec from Netbox. Also having the choices listed on api/docs Swagger UI is very helpful when browsing through the API docs.

### Database Changes

None

### External Dependencies

None

**Comment by deathbeam** [comment]
![screenie](https://user-images.githubusercontent.com/5115805/73547863-12aaca80-4440-11ea-8d95-47102559ec22.png)

Example of generated data with enum support

**Comment by jeremystretch** [comment]
This issue has been closed as it does not conform to one of the [provided templates](https://github.com/netbox-community/netbox/issues/new/choose) as required by the [contributing guide](https://github.com/netbox-community/netbox/blob/master/CONTRIBUTING.md). If you'd like to request that your issue be re-opened, please first update the content so that it matches the appropriate template (this may require rewriting your issue entirely).

**Comment by deathbeam** [comment]
@jeremystretch Updated, can you reopen?

**Comment by kobayashi** [comment]
I would Approve this as Enhancement

**Comment by jeremystretch** [comment]
I don't have any objection to this, but do we have a good understanding of what might break by making the change? Thinking about pynetbox specifically, and similar API clients.

**Comment by deathbeam** [comment]
It is just extra `enum` field next to `type` field that was not there before, so as long as consumers of the spec are ignoring unknown fields when parsing it should not affect anything.

**Comment by kobayashi** [comment]
Yes, this should not affect to pynetbox. While playing with pynetbox, this change seems to not affect to the client. For go-netbox, I can make some fix for this.
