### ISSUE TITLE
Allow filtering by Parent device in Interfaces view

### ISSUE THREAD

**Issue by megazloj** [netbox-community/netbox#4100]
### Environment
* Python version:  3.6.9
* NetBox version:  2.7.4

### Proposed Functionality
Allow interfaces to be filtered also by Parent device. Field should allow to select multiple devices.

### Use Case
We're using tags to mark free/reserved/special interfaces to be able later select them and count/review. Now Netbox displaying all interfaces from all devices that matching criteria such as Name/Region/Site/Tags. Ability to filter by Parent device will help alot to find interfaces with selected tags on one/multiple devices.

**Comment by hSaria** [comment]
Fairly simple. This is somewhat similar to #3122. If there are no objections, I'd like to work on this (I've missed adding `filter_for` on the `site` field for `device_id`, so I'd improve that in the process).

**Comment by DanSheps** [comment]
> Fairly simple. This is somewhat similar to #3122. If there are no objections, I'd like to work on this

Done

> I've missed adding `filter_for` on the `site` field for `device_id`, so I'd improve that in the process

Not sure @jeremystretch view on this, but I would probably want this as a separate Issue/PR
