### ISSUE TITLE
FR: devicetype-library: allow creation of manufacturer by Users-Choice

### ISSUE THREAD

**Issue by tb-killa** [netbox-community/netbox#4103]
### Environment
* Python version: 3.6  
* NetBox version: 2.7.4  

### Proposed Functionality
if populating device types from https://github.com/netbox-community/devicetype-library it would be good if in the same step there is the possibility to create the manufacturer directly, if it does not exist yet. This could be decided by the user himself with a checkbox whether e.g. the missing manufacturer should be created from the import or not 

### Use Case
Allow autocreation of manufacturer if populating device types from https://github.com/netbox-community/devicetype-library, selectable by Users-Choice via Checkbox.

### Database Changes
None.

### External Dependencies
None.

**Comment by jeremystretch** [comment]
Automatically creating parent objects would extend beyond the scope of importing a new device type. It's important that we retain a specific scope for every feature to ensure future maintainability, and this would violate that principle. It's also worth pointing out that creating a new manufacturer manually takes at most a few seconds, and is needed only once per set of device types belonging to that manufacturer. For these reasons, I'm going to decline this FR.
