### ISSUE TITLE
Manually record a change

### ISSUE THREAD

**Issue by rainerduffner** [netbox-community/netbox#4106]
### Environment
* Python version:  3
* NetBox version:  2.7.4

### Proposed Functionality
Is there a way to add entries to the "changelog" manually?

### Use Case
In our current system, we can add entries to a device like "upgraded OS" or "restarted webserver because of hanging application X" or "replaced fan". These entries create a rolling log of the history of the machine.

### Database Changes
unknown

### External Dependencies
unknown

**Comment by jeremystretch** [comment]
The changelog provides an audit trail of changes that are made in NetBox only. You probably want what's been proposed in #151, which is currently open but I cannot provide any sort of ETA.

**Comment by rainerduffner** [comment]
Thanks for the pointer.
