### ISSUE TITLE
Unable to view visualization in rack (front and rear) after update to 2.7.3

### ISSUE THREAD

**Issue by madeus** [netbox-community/netbox#4107]
### Environment
* Centos:  7.7
* PostgreSQL:  9.2.24
* Python version:  3.6
* NetBox version:  2.7.3

### Steps to Reproduce
1. Update from 2.6.9 to 2.7.3 (or 2.7.4)

During the update I can see in the log:

 ```
Validating Python dependencies (pip3 check)...
flex 6.13.2 has requirement click<7,>=3.3, but you have click 7.0.
flex 6.13.2 has requirement PyYAML<4,>=3.11, but you have pyyaml 5.3.
******** PLEASE FIX THE DEPENDENCIES BEFORE CONTINUING ********
* Manually install newer version(s) of the highlighted packages
* so that 'pip3 check' passes. For more information see:
* https://github.com/pypa/pip/issues/988 
 ```

So I uninstalled click 7.0 and installed click version 3.3 and PyYAML version 3.13. Then I did the update again. And again in log I see:

 ```
ERROR: flex 6.13.2 has requirement PyYAML<4,>=3.11, but you'll have pyyaml 5.3 which is incompatible.
Installing collected packages: PyYAML
  Attempting uninstall: PyYAML
    Found existing installation: PyYAML 3.13
    Uninstalling PyYAML-3.13:
      Successfully uninstalled PyYAML-3.13
    Running setup.py install for PyYAML ... done
Successfully installed PyYAML-5.3
Validating Python dependencies (pip3 check)...
flex 6.13.2 has requirement PyYAML<4,>=3.11, but you have pyyaml 5.3.
******** PLEASE FIX THE DEPENDENCIES BEFORE CONTINUING ********
* Manually install newer version(s) of the highlighted packages
* so that 'pip3 check' passes. For more information see:
* https://github.com/pypa/pip/issues/988
 ``` 

### Expected Behavior
Full view (visualization) of the rack panel as here:
https://github.com/netbox-community/netbox/blob/develop/docs/media/screenshot2.png

Interestingly, when I use the API, the rack shows up correctly: /api/dcim/racks/same_id/elevation/?render=svg

### Observed Behavior
Rack panel (front and rear) is empty and not clickable (should be).

**Comment by DanSheps** [comment]
Thank you for your interest in NetBox. GitHub issues are intended for reporting reproducible bugs and requesting features, and must be submitted using one of the templates provided [here](https://github.com/digitalocean/netbox/issues/new/choose). For general discussion, questions, or assistance with installation issues, please post to our [mailing list](https://groups.google.com/forum/#!forum/netbox-discuss) instead.
