### ISSUE TITLE
Boolean Custom Fields shows 'not defined' on 'false' value

### ISSUE THREAD

**Issue by basti1508** [netbox-community/netbox#4120]
### Environment
* Python version:  3.6.9
* NetBox version:  2.7.4

### Steps to Reproduce
1. Create a new custom field with type Boolean and check required flag and assign it to dcim>devices
2. Create a new device or use an exisiting one (same bahaviour there)
3. Set the custom field value to false on this device

### Expected Behavior
The Custom Field view should show the value as false.

### Observed Behavior
The Custom Field view shows the value as 'Not defined'
If i check the value of the field via api, it is shown as false correctly

**Comment by jeremystretch** [comment]
This has been fixed under #4090 and will be resolved in v2.7.5.
