### ISSUE TITLE
VM to HOST Mapping

### ISSUE THREAD

**Issue by lyndonvi** [netbox-community/netbox#4123]
Firstly, congrats on a great solutions for IPAM and DC's in general.

I'm mentioning this here as a BUG and not a feature request as it pertains to #142.

I just came across NETBOX and begun evaluating it as an option alternative to Racktables and Device42 etc.

How is it possible that you one is unable to associated a VM with a Physical host?

I can see you have created this "CLUSTERS" concept. But frankly, this feature has been poorly understood from the outset.

For example - A cluster is meaningless if the underlying relationship between a physical machine, say running Proxmox, and the VM's hosted on that machine, can't be created.

Sure, have your "Clusters" and "Cluster Groups" for the VMWare fan boys. But the current implementation is flawed and for us a deal breaker.

Happy to pay $ to have this very simple piece fixed in the back end tables.

Love your work so far. Please fix and provide details of where I can send my money :-)

**Comment by DanSheps** [comment]
Thank you for your interest in NetBox. GitHub issues are intended for reporting reproducible bugs and requesting features, and must be submitted using one of the templates provided [here](https://github.com/digitalocean/netbox/issues/new/choose). For general discussion, questions, or assistance with installation issues, please post to our [mailing list](https://groups.google.com/forum/#!forum/netbox-discuss) instead.

**Comment by DanSheps** [comment]
Duplicate: #2587 #3075 #2553 #142 #4143 #4140
