### ISSUE TITLE
LDAP auth login not working netbox 2.7.4

### ISSUE THREAD

**Issue by fmax** [netbox-community/netbox#4124]
we are using LDAP auth.
config file `/opt/netbox/netbox/ldap_config.py` got copied from 2.7.1 version before.

### Environment
* Python version:  3.6.8
* NetBox version:  2.7.4

### Steps to Reproduce
update from v2.7.1 to v2.7.4
1. follow update option A: https://netbox.readthedocs.io/en/stable/installation/upgrading/
2. ./upgrade.sh ran successfully
3. restarted netbox and netbox-rqworker

### Expected Behavior
login in netbox installation after update procedure

### Observed Behavior
cannot login in netbox web-ui
`Errors`
`    Please enter a correct username and password. Note that both fields may be case-sensitive.`

**Comment by DanSheps** [comment]
Thank you for your interest in NetBox. GitHub issues are intended for reporting reproducible bugs and requesting features, and must be submitted using one of the templates provided [here](https://github.com/digitalocean/netbox/issues/new/choose). For general discussion, questions, or assistance with installation issues, please post to our [mailing list](https://groups.google.com/forum/#!forum/netbox-discuss) instead.
