### ISSUE TITLE
Add Show VLANs button

### ISSUE THREAD

**Issue by Shm013** [netbox-community/netbox#4126]
### Environment
* Python version: 3.6.17
* NetBox version: 2.7.4

### Proposed Functionality
Add new toggle button "Show VLANs" into device view in interfaces table like a "Show IPs" button.

### Use Case
I would like to see all ports with assigned information about VLANs instead open each port. It is very convenient during VLANs configuration in commutators.

### Database Changes
No

### External Dependencies
No

**Comment by kobayashi** [comment]
I would accept this issue.

**Comment by jeremystretch** [comment]
We need to overhaul the templates used for displaying device components before we extend them any further. The interfaces template in particular has become quite a mess, with tables inside tables. Let's work on devising a more sustainable approach before we try to cram any more data in there.

**Comment by jeremystretch** [comment]
Opened #4193 for the above; marking this as blocked.

**Comment by jeremystretch** [comment]
This is no longer needed as the interface table columns are now configurable.
