### ISSUE TITLE
Was the initial_data dataset fixture removed?

### ISSUE THREAD

**Issue by raddessi** [netbox-community/netbox#4132]
### Environment
* Python version:  3.6.9
* NetBox version:  2.7.3

### Steps to Reproduce
On a fresh install I do not see any initial data in the database and running `python ./manage.py loaddata initial_data` results in `CommandError: No fixture named 'initial_data' found.`

### Expected Behavior
The import command runs fine and the basic prefixes RIRs etc are present in the db afterwards.

### Observed Behavior
Was this moved to another method of import or just dropped? I found it quite useful. I've searched through the issue tracker and repo and can't find anything relevant.

**Comment by hSaria** [comment]
It was removed as part of 85563e21db396e596836269300fffc7de724091f as it was no longer maintained.
