### ISSUE TITLE
describe computing and storage resourcea for device

### ISSUE THREAD

**Issue by azatuni** [netbox-community/netbox#4140]
### Environment
* Python version:  3.6.8
* NetBox version:  2.7.3

### Proposed Functionality
It would be nice if netbox will support also computing resource of device (RAM, CPU, Storage). It will be very useful in case of if device is hypervisor or just a server Thanks beforehand.

**Comment by jeremystretch** [comment]
This has been proposed in the past and has been decided out of scope for NetBox.

**Comment by azatuni** [comment]
But in case if you can descibe VM resources you shoould be available to describe a  VM cluster and hypervisor resources too, right?
