### ISSUE TITLE
Virtual Machines and Physical Machine relationship is missing - Why?

### ISSUE THREAD

**Issue by lyndonvi** [netbox-community/netbox#4143]
Firstly, congrats on a great solutions for IPAM and DC's in general.

I'm mentioning this here as a BUG and not a feature request as it pertains to #142.

I just came across NETBOX and begun evaluating it as an option alternative to Racktables and Device42 etc.

How is it possible that we are unable to associate a VM with a Physical host?

I can see you have created this "CLUSTERS" concept. But frankly, this feature has been poorly understood from the outset.

For example - A cluster is meaningless if the underlying relationship between a physical machine, say running Proxmox, and the VM's hosted on that machine, can't be created in Netbox.

Sure, have your "Clusters" and "Cluster Groups". But the current implementation is flawed and for us a deal breaker.

Happy to pay $ to have this very simple piece fixed in the back end tables.

Love your work so far. Please fix and provide details of where I can send my money :-)

**Comment by DanSheps** [comment]
Thank you for submitting this issue, however it appears that this topic has already been raised. Please see issue #4140, #3075, #2553 and #142 for further discussion.
