### ISSUE TITLE
Import cable issue

### ISSUE THREAD

**Issue by User-HAS** [netbox-community/netbox#4145]
### Environment
* NetBox version:  2.5.7

### Steps to Reproduce
1. Attemp to import cable using the following syntax:
device1,rearport,R-X9/X10,device2,rearport,R-X9/X10

### Expected Behavior
The cable will be created

### Observed Behavior
Error message:
![image](https://user-images.githubusercontent.com/60884083/74240262-dac24380-4cd9-11ea-964f-cc12c601c9a4.png)
The export cable format contains Terminations ID (dcim.interface). "termination_a_type,termination_a_id,termination_b_type,termination_b_id,type"
Is there a way to extract all the termination IDs of the devices ?

**Comment by kobayashi** [comment]
Could you give us more detailed steps to reproduce this issue?
For my environment, I cannot reproduce.
Or there is the same error case #3716

**Comment by jeremystretch** [comment]
> NetBox version: 2.5.7

Please upgrade to the most recent stable release (currently v2.7.4) as it is very likely your issue has already been resolved, as @kobayashi has indicated. If you can replicate this issue on the current stable release please ask to reopen this bug.
