### ISSUE TITLE
Render rack elevation SVG with absolute URLs

### ISSUE THREAD

**Issue by ananace** [netbox-community/netbox#4147]
### Environment
* Python version: 3.7.6
* NetBox version: 2.7.4

### Proposed Functionality
The current SVG rendering for rack elevations results in SVGs containing URLs that are relative, this makes it a slight bit more intricate to embed those SVG images in other systems without moving the image query and embedding into the client's browser.  
If instead all `a` tags in the elevation SVGs were rendered with absolute URLs, then the resulting image could be cached and re-served as part of a server-side render in a completely different system, without requiring rewriting the image on the server.

### Use Case
With absolute URLs, rack views could be embedded into systems with different access rules than NetBox itself, letting the server retrieve and display the images in unmodified form to clients, while still easily allowing privileged users to click through into NetBox proper.

**Comment by jeremystretch** [comment]
My only potential concern would be that we're hard-coding URLs for non-API views in content delivered via the API. That should be okay though, since it's difficult to imagine a use case where the links within an SVG image (obviously intended for human consumption) would need to hit the API views.

**Comment by jeremystretch** [comment]
Also: Can this be solved by adding a `<base>` tag to the SVG document, rather than directly specifying absolute URLs for every element?

**Comment by ananace** [comment]
I had that thought as well, though I wasn't able to find any useful answers on how well the use of a `<base>` tag in an SVG would work.

**Comment by jeremystretch** [comment]
Just took a few minutes to dig into this. AFAICT using `<base>` doesn't seem feasible with svgwrite: We'll have to hard-code full URLs for all links.
