### ISSUE TITLE
Remove topology-maps.md from mkdocs.yml

### ISSUE THREAD

**Issue by TheRealBecks** [netbox-community/netbox#4148]
### Change Type
[ ] Addition
[ ] Correction
[ ] Deprecation
[X] Cleanup (formatting, typos, etc.)

### Area
[ ] Installation instructions
[ ] Configuration parameters
[ ] Functionality/features
[ ] REST API
[ ] Administration/development
[X] Other

### Proposed Changes
Topology maps as a feature have already been removed from netbox, so also the topology-maps.md vanished from the docs. But the link to that deleted file still exists:
https://github.com/netbox-community/netbox/blob/develop/mkdocs.yml#L44
Because of that 'Topology Maps' can still be clicked on https://netbox.readthedocs.io/en/stable/ but the site is missing.

**Comment by jeremystretch** [comment]
Thank you for reporting the oversight!
