### ISSUE TITLE
Netbox Homepage Database Connections

### ISSUE THREAD

**Issue by dsg-anthony** [netbox-community/netbox#4149]
### Environment
* Python version:  3.6.8
* NetBox version:  2.7.1

I have 2 netbox servers running behind a load balancer, the load balancer checks the root path every x amount of times to make sure the app is still running. CACHE is also disabled on these servers.

### Steps to Reproduce
1. Set LOGIN_REQUIRED to **false** in the configuration.py
2. Hit the homepage with traffic that is not authenticated 
3. Set LOGIN_REQUIRED to **true** in the configuration.py
4. Hit the homepage with traffic that is not authenticated 

### Expected Behavior
Traffic to not create any database connections

### Observed Behavior
Traffic to the homepage causes the application to execute database connections even though no data is presented to the user.

I've attached a graph to illustrate what I'm seeing. At 10:16 I restarted 1 of my netbox servers with LOGIN_REQUIRED which forwards traffic from / to /login 

![image](https://user-images.githubusercontent.com/43544235/74349442-4364fb00-4d82-11ea-933f-4d6dd4b8d348.png)

**Comment by jeremystretch** [comment]
> Traffic to not create any database connections

Django always creates a database connection. This is not a bug. (Besides, what good would the check be if it _didn't_ connect to the database? The backend database could be down, rendering NetBox inoperable, but your monitoring would report green based on the HTTP daemon being responsive.)

**Comment by dsg-anthony** [comment]
That's what I figured. Maybe this is more of an unexpected behavior type thing.

semi related to #3291

I've changed the health check to hit /metrics which from what I can tell has no database dependency.
