### ISSUE TITLE
YAML rendering for config contexts with overlapping nested dictionary is incorrect

### ISSUE THREAD

**Issue by vsvetlov** [netbox-community/netbox#4150]
### Environment
* Python version:  3.7.3 
* NetBox version:  2.7.4

### Steps to Reproduce
1. Create config context region1
```
{
    "attributes": {
        "key10": "value10"
    }
}
```
2. Create config context site1
```
{
    "attributes": {
        "key20": "value20"
    }
}
```
3. These config contexts should be applied to the same device

### Expected rendered context
```
attributes:
  key10: value10
  key20: value20
```

### Observed rendered context
```
attributes: !!python/object/apply:collections.OrderedDict
- - - key10
    - value10
  - - key20
    - value20
```

**Comment by DanSheps** [comment]
@hSaria I believe you did the YAML formatting, is this something you could look at?

**Comment by hSaria** [comment]
Sure thing. I’ll take care of it.
