### ISSUE TITLE
Config Contexts by Racks

### ISSUE THREAD

**Issue by sakbhav** [netbox-community/netbox#4158]
### Environment
* Python version:  3.6.3
* NetBox version:  2.7.4

### Proposed Functionality

To be able to set config context per rack basis.

### Use Case

I want to set some rack specific configurations (e.g. static routes/network switch related configs etc.) via ansible using netbox as inventory.  Though this can be achieved by setting a tag and defining config context on that tag but it won't scalable for large number of servers.
 
### Database Changes
Yes

### External Dependencies
None

**Comment by jeremystretch** [comment]
> I want to set some rack specific configurations (e.g. static routes/network switch related configs etc.)

A device's physical location shouldn't have any bearing on its function, so inferring characteristics of a device from the rack in which it's installed strikes me as backwards. It sounds like you're using the rack as a proxy for some other piece(s) of information, which will inevitably present a problem at some point down the road.

> Though this can be achieved by setting a tag and defining config context on that tag but it won't scalable for large number of servers.

Why don't you expect the use of tags to scale?

**Comment by sakbhav** [comment]
> A device's physical location shouldn't have any bearing on its function, so inferring characteristics of a device from the rack in which it's installed strikes me as backwards.
Well, device's physical location does have bearing with its function when we need to reduce the network latency to its minimum.

> It sounds like you're using the rack as a proxy for some other piece(s) of information, which will inevitably present a problem at some point down the road.
In my case, I am trying to keep server's static route information (which are different for each rack) in config context.
Rack config context can also be used in a more general case like if you want to set the hostname/alias of servers based on the rack it is present in etc.

> Why don't you expect the use of tags to scale?
This will involve tagging all the servers in a rack with same tag which is cumbersome and error prone.  Also this is going to be redundant information.

I understand that this use case might not be a very general one, but if this can be easily done and doesn't have huge performance overhead then please enable config context to be defined per rack.

**Comment by jeremystretch** [comment]
> In my case, I am trying to keep server's static route information (which are different for each rack) in config context.

It's not different for each rack: It's different for each _prefix_, and you just happen to allocate (presumably) one prefix per rack. If one prefix were to span two racks, all the devices in both racks would still use the same gateway. Similarly, there may be two prefixes within a single rack which use different gateways. There is no direct correlation of rack to IP gateway.

I'm going to decline this FR because using a device's rack as a proxy for other information is unnecessary and there are mechanisms available in NetBox better suited for this purpose.
