### ISSUE TITLE
Allow for Adding Database Connection Options

### ISSUE THREAD

**Issue by dstarner** [netbox-community/netbox#4160]
### Environment
* Python version:  3.7
* NetBox version:  2.7.2

### Proposed Functionality
Django supports the `OPTIONS` keyword for a database configuration. This could be used to pass custom options & context when connecting to the database.

```python
# In configuration.py

DATABASE = {
    # ... other currently existing values ...
    'CONN_MAX_AGE': 300,      # Max database connection age
    'OPTIONS': {
        # connect only to the netbox schema since thats all our db user has access to
        'options': '-c search_path=%s' % os.getenv('POSTGRES_SCHEMA', 'netbox')
    }
}
```

By default, `OPTIONS` can be an empty dictionary `{}`

```python
DATABASE = {
    # ...other currently existing values ...
    'CONN_MAX_AGE': 300,      # Max database connection age
    'OPTIONS': {}
}

```

### Use Case
For instance, in certain circumstances, such as with shared databases, NetBox may not have full admin privilege over the  database and may need to be limited to a specific schema. Not only may this be preferred, but in some environments, it might be necessary due to the availability of developer environments.

### Database Changes
None

### External Dependencies
None

**Comment by jeremystretch** [comment]
NetBox does support passing `OPTIONS` currently; it's just not documented as a supported parameter. I suppose we can add a link to the [relevant Django docs](https://docs.djangoproject.com/en/stable/ref/settings/#databases) in the config documentation.

**Comment by dstarner** [comment]
Ah, I didnt realize it was pass-through, that makes sense then
