### ISSUE TITLE
Inconsistent role requirement on virtual machine between API and WebUI

### ISSUE THREAD

**Issue by cloos** [netbox-community/netbox#4168]
### Environment
* Python version:  3.6.9
* NetBox version:  2.7.6

### Steps to Reproduce
1. create virtual machine by API: role is not required
2. create virtual machine in WebUI: role is required

### Expected Behavior
If a role for a virtual machine is required or not should be the same for API and WebUI.

### Observed Behavior
If you create a virtual machine by API, role isn't  required.
If you create a virtual machine in the WebUI, role is required.

The VirtualMachine model defines `blank=True`and `null=True`, which makes role not required by API:
https://github.com/netbox-community/netbox/blob/v2.7.6/netbox/virtualization/models.py#L212-L219

The VirtualMachineForm doesn't have a `required=False` for role, which makes role required in the WebUI:
https://github.com/netbox-community/netbox/blob/v2.7.6/netbox/virtualization/forms.py#L352-L360

**Comment by hSaria** [comment]
You're correct. This happened during some internal housekeeping (#3912). The solution would be to add `required=False` as you described.
