### ISSUE TITLE
Bulk editing of objects can cause an error when using a filtered list

### ISSUE THREAD

**Issue by Douglas-Farley** [netbox-community/netbox#4175]
### Environment
* Python version:  2.6.8
* NetBox version:  v2.7.6

### Steps to Reproduce
1.  Navigate to Manufacturer Page
2. Select a Manufacturer
3. Select the Device Type view from Manufacturer
4.  Select any number of devices
5.  Execute "Edit Selected"

### Expected Behavior
Get Edit dialog. 

### Observed Behavior

TypeError at /dcim/device-types/edit/
int() argument must be a string, a bytes-like object or a number, not 'list'

Request Method: | POST
-- | --
https://netbox/dcim/device-types/edit/?manufacturer=oem
2.2.10
TypeError
int() argument must be a string, a bytes-like object or a number, not 'list'
get_prep_value, line 972
/usr/local/bin/uwsgi
3.6.8

**Comment by hSaria** [comment]
This also affects other views, like platforms `http://netbox/dcim/devices/?platform=junos` and then bulk edit.

**Comment by jeremystretch** [comment]
The root issue here is that the query parameters are erroneously being passed as initial data for the bulk editing form. This should not affect unfiltered lists.

**Comment by robbagithub** [comment]
#4188 does not appear to be fixed in v2.7.7   If I read the above comments correctly, I would have expected the merged fix for #4216 to be in v2.7.7

**Comment by hSaria** [comment]
I just tried it and it works fine. Did you restart the NetBox service (i.e. gunicorn) after upgrading? In other words, do you see the new version in the footer? I doubt caching has anything to do with it, but you may also want to try to clear the cache with `python3 manage.py invalidate all`.

**Comment by robbagithub** [comment]
Yep was restarted and I checked the version info is at 2.7.7

I'll try the invalidation.

**Comment by robbagithub** [comment]
Strangely I've just removed all the old invalid reports and they are still appearing in the UI. We've issued the invalidate and restarted. 

Is there some other cache I'm unaware of?
