### ISSUE TITLE
Device Depth field and Half Depth options missing from Edit and View for Devices but not Elevation View

### ISSUE THREAD

**Issue by Douglas-Farley** [netbox-community/netbox#4176]
### Environment
* Python version: 2.6.8
* NetBox version: v2.7.6

### Steps to Reproduce
1. Goto Device View
2. Goto Device Edit

### Expected Behavior
Depth attribute on a device shows up in list view. 

### Observed Behavior
Rack Elevation show's previously added devices that have half depth.  
When viewing or editing devices via Devices -> Devices, the Depth attribute seems missing, and filters for "Is full depth" seem missing.
Device Types still lets you Filter by "Is full depth", but doesn't let you set/change Depth.

**Comment by jeremystretch** [comment]
The description above doesn't make sense. There seems to be some confusion regarding the device type's `is_full_depth` property. This is not editable or filterable on any device view; it is applicable only to device types, because it is the same for all instances of a device type.
