### ISSUE TITLE
Bulk rename interfaces when create Virtual Chassis

### ISSUE THREAD

**Issue by vsvetlov** [netbox-community/netbox#4177]
### Environment
* Python version:  3.7.3
* NetBox version:  2.7.4

### Proposed Functionality
Optionally rename interfaces automatically when adding a device to a virtual chassis according to the predefined find/replace/regex variables.

### Use Case
Usually name convention for interfaces in virtual chassis is slightly different than for standalone devices.
It depends on vendor implementation. For example, if for standalone switch interface name is GigabitEthernet10, then for virtual chassis it can be GigabitEthernet1/10 where 1 is prefix that points to device priority in the virtual chassis.

Actually bulk renaming already implemented. We need to call it when adding a device to virtual chassis. It would really help in the case of many virtual chassis.

### Database Changes
None

### External Dependencies
None

**Comment by jeremystretch** [comment]
> Optionally rename interfaces automatically when adding a device to a virtual chassis according to the predefined find/replace/regex variables.

This needs far more detail to be actionable. What is the proposed workflow? What modifications to existing forms are necessary? How will validation be handled?

**Comment by vsvetlov** [comment]
I agree it can be difficult to rename during the procedure of adding a device to VC.
An option to consider device position in bulk renaming for VC would be enough. 
It can be done by using a special pattern to highlife a position in interface name when we want to put device number. For example, we have 4 switches in VC with interfaces GigiabitEthernet[1-24] which we want to rename to GigiabitEthernet[1-4]/[1-24] 

Find: GigabitEthernet
Replace: GigabitEthernet{p}/

where {p} is a pattern we should replace with number of device position before regex().
I think more intelligent regex also can be used.
