### ISSUE TITLE
warn about IP conflict

### ISSUE THREAD

**Issue by jkldgoefgkljefogeg** [netbox-community/netbox#418]
no warning was given when duplicated IP address in the same VRP configured on multiple devices (device edit => assign IP address)

**Comment by jkldgoefgkljefogeg** [comment]
The current duplicated IP check under IP addresses may show only 1 IP address under conflict if the IP address was created from DCIM and then removed from interface.

**Comment by jeremystretch** [comment]
We can probably add a warning on the IP creation form. It's worth noting however that you can disable duplicate IPs and prefixes entirely by enforcing unique space within the VRF (by toggling "Enforce unique space") and/or global table (using the `ENFORCE_GLOBAL_UNIQUE` configuration setting).

> If device primary IP is added from assign IP address. When the assigned IP address gets deleted, primary IP is not cleared, leaving an orphaned IP usage.

All IPs assigned to an interface on a deleted device get deleted. You're probably seeing the duplicate IP that's left after the other IP is deleted.

**Comment by fallenfuzz** [comment]
Hi,

A button for overlapping check would be nice too in IP Address / IP preffix creation.

![43589114-b60621da-9676-11e8-9f40-bac8a53c7c97](https://user-images.githubusercontent.com/13089287/43920007-66ee81be-9c20-11e8-8922-59b2df41b0a1.png)

**Comment by DanSheps** [comment]
Do we want to revisit this?  I don't see any value to be gained by this with both the enforce uniqueness on a per-vrf or global basis.  I think it could only confuse things to if a IP address was assigned a FHRP role and was duplicated (since you want a duplicate in that instance).

I can see the logic for checking this getting unnecessarily complex.

**Comment by jeremystretch** [comment]
It doesn't look like this ever got any traction. I've tagged it as `needs owner` in case anyone wants to volunteer. If not, it will end up getting closed and possibly reconsidered during a future UI refresh.

**Comment by Kircheneer** [comment]
I would be willing to implement the check @fallenfuzz has proposed. I think it has value for those cases where you explicitly do not want to create a container allocation but rather allocate a new subnet. What do you guys think?
