### ISSUE TITLE
Cannot save aggregate by using .save() in custom script

### ISSUE THREAD

**Issue by slinderud** [netbox-community/netbox#4180]
### Environment
* Python version:  3.5.3
* NetBox version:  2.7.6

### Steps to Reproduce
1. Create a new aggregate prefix.
2. Upload this script to ```/opt/netbox/netbox/scripts```:
```
from extras.scripts import *

from ipam.constants import *
from ipam.models import Aggregate, Prefix, IPAddress

import netaddr

class BugTest(Script):

    class Meta:
        name = "Change prefix recursive"
        description = "Change a top level prefix"
        field_order = ['old_prefix', 'new_prefix']

    old_prefix = ObjectVar(
        description="Prefix you want to change",
        queryset = Aggregate.objects.all()
    )

    new_prefix = IPNetworkVar(
        description="The new prefix"
    )

    def run(self, data):
        old_prefix = str(data['old_prefix'])
        new_prefix = str(data['new_prefix'])

        aggregate_dict_obj = Aggregate.objects.get(prefix=old_prefix)
        aggregate_dict_obj.prefix = new_prefix
        aggregate_dict_obj.save()
        self.log_success("Converted old aggregate: {} to new aggregate: {}".format(old_prefix, new_prefix))
```
3. Use the custom script to try change the aggregate prefix to something new.

### Expected Behavior
The aggregate would change

### Observed Behavior
```
Traceback (most recent call last):
  File "/opt/netbox/netbox/extras/scripts.py", line 395, in run_script
    output = script.run(data)
  File "/opt/netbox/netbox/scripts/bugfail.py", line 31, in run
    aggregate_dict_obj.save()
  File "/opt/netbox/netbox/ipam/models.py", line 240, in save
    self.family = self.prefix.version
AttributeError: 'str' object has no attribute 'version'
```

It seems like the save function assumes it's a netaddr.IPNetwork type give it's looking for the .version attribute that doesn't exists.
https://github.com/netbox-community/netbox/blob/1a8eea5aa943f4f63b76ecadcf9ee7c4ab60e6e2/netbox/ipam/models.py#L231

We can confirm this by changing this line:
``` aggregate_dict_obj.prefix = new_prefix```
to
``` aggregate_dict_obj.prefix = netaddr.IPNetwork(new_prefix)```

Now it works!

Most likely the save function has to be changed to something like the one used in Prefix:
https://github.com/netbox-community/netbox/blob/1a8eea5aa943f4f63b76ecadcf9ee7c4ab60e6e2/netbox/ipam/models.py#L419

**Comment by DanSheps** [comment]
As you discovered, the model is looking for a IPNetwork, not a string.  As such, you need to pass the IPNetwork object yourself derived from the string.

My personal view is this is not a bug.  If you need field validation before saving you should call clean() before calling save()

**Comment by slinderud** [comment]
I would agree if saving a prefix would behave the same way.

```
prefix_dict_obj = Prefix.objects.get(prefix=str(p))
prefix_dict_obj.prefix = str(conv_prefix)
prefix_dict_obj.save()
```

This works fine. 

Handling these who differently doesn't make much sense to me.

**Comment by jeremystretch** [comment]
```python
new_prefix = str(data['new_prefix'])
aggregate_dict_obj.prefix = new_prefix
```

As @DanSheps points out, you can simply assign the field value directly:

```python
aggregate_dict_obj.prefix = data['new_prefix']
```

The `family` attribute is being removed in v2.8 anyway (see #4081) so there's no action worth taking here.
