### ISSUE TITLE
If multiple RD value with separator will be set in VRF, we can get unusable situation for parse result and automation

### ISSUE THREAD

**Issue by pnpwin** [netbox-community/netbox#4184]
### Environment
* Python version:  3.7.6
* NetBox version:  2.7.6

Hi. Because you use in https://github.com/netbox-community/netbox/blob/151943bfbc8e0d2b2a5055dc5ab03d7c1ea6847d/netbox/ipam/models.py#L46 model CharField - we can get unusable situations like this:
![telegram-cloud-photo-size-2-5354915051301088467-y](https://user-images.githubusercontent.com/25432591/74610866-0ee99a00-5108-11ea-8741-78003980bba9.jpg)

If multiple RD value with separator will be in this field, we can get unusable situation for parse result and automation.

Maybe you can use model for RD field and try to check-on-save value with this description https://tools.ietf.org/html/rfc4364#page-14 ?

### Steps to Reproduce
1. Open or create VRF;
2. Set multiple RD value with separator;
3. Save.

**Comment by DanSheps** [comment]
The route distinguisher field is a free-form field.  I don't believe we do any validation on the RD field, as this is more of a end user thing.

If you would like to have a FR for some more validation around the field, please request a re-open with a use case around the change and what database changes may be required.
