### ISSUE TITLE
Child Devices visualization in Rack View

### ISSUE THREAD

**Issue by abhilashchinthalapudi** [netbox-community/netbox#4187]
### Environment
* Python version:  3.6.8 
* NetBox version:  2.7.3 and 2.6.12 (We hav two instances)

### Proposed Functionality

  As we are on 2.7 Now ,Is there any plan to consider adding Child Devices in rack view for each parent Device.We had lot of requests for this in backlog like https://github.com/netbox-community/netbox/issues/1911.Which were closed out as a last updated mentioned we can revisit after 2.7

### Use Case

We have a lot of 2U chassis with 4 blades and we do not have a better visualization for DC engineers to take a look at the child device in rack view .This would be a great add on 

### Database Changes
I am not sure

-->
### External Dependencies
NA

**Comment by jeremystretch** [comment]
Sorry, but no. This would require a huge amount of development effort to implement and wouldn't even result in a useful rendering in many cases. The examples given in #1911 were contrived to use very short names to fit in the allotted space: Real-world examples would be far less accommodating. For instance, I have a 1U device with four bays in it. There's no other information I can display in that space that isn't already present on the elevation diagram.
