### ISSUE TITLE
UI: Prefixes Table Utilization Bar points to IP Addresses

### ISSUE THREAD

**Issue by elju** [netbox-community/netbox#4191]
### Environment
* Python version:  Python 3.6.8
* NetBox version: 2.7.4

### Proposed Functionality
Make the Utilization bar in the prefixes table a direct shortcut to the list of ip addresses

### Use Case
Netbox users now can directly jump to the ip address which saves time

### Database Changes
None

### External Dependencies
None

**Comment by jeremystretch** [comment]
Utilization is calculated differently for container and non-container prefixes, so a link to IP addresses would not make sense. (Containers calculate utilization based on child prefixes.)

Also, if we're going to provide a link, IMO it should be a total count of the child object to remain consistent with other views.
