### ISSUE TITLE
Allow two hostnames under DNS Name

### ISSUE THREAD

**Issue by rivest1000** [netbox-community/netbox#4197]
### Environment
* Python version:  Python 2.7.13
* NetBox version:  v2.6.7

### Proposed Functionality
    Please allow multiple FQDN's (separated by commas) under DNS name field so that we can have many A records in DNS for one IP address

### Use Case
    We have a python script that scrapes our netbox API everyday for IP addresses and their hostnames associated with them. It creates zone files that is used for unbound/nsd. Right now, in order to have two A records for one IP, we have to create a VIP role for that IP and assign the IP twice and create a hostname for each one. It would make it much easier to have the IP listed in the DB one time with two hostnames associated with it.

**Comment by jeremystretch** [comment]
NetBox is not intended to be used as a full DNS management application. The `dns_name` field is provided as a convenience to hold a single name only, and employs validation to enforce this.
