### ISSUE TITLE
Ports of the CFP type

### ISSUE THREAD

**Issue by ArtemSannikov** [netbox-community/netbox#4200]
### Environment
* NetBox 2.7.4
* Python 3.6.9
* OS: Ubuntu 18.04 LTS

### Proposed Functionality

To add ports of the CFP type with a speed of 40G

**Comment by jeremystretch** [comment]
Interface types in NetBox describe the physical port, not the optic, so for a 40GE CFP transceiver you would still use the "CFP" type. This is similar to how an SFP+ can operate with a 1GE optic.

**Comment by walday** [comment]
Good day, I have WS-C6509-E with a board WS-X6904-40G and on it physically CFP ports are only at a speed of 40G (not 100G with support for 40G) and the description in Netbox 100G introduces some incorrectness in the formation of scripts based on the speed of the interface
