### ISSUE TITLE
Added a serial console_port type rj-11 for a POTS modem connection

### ISSUE THREAD

**Issue by wtinetworkgear** [netbox-community/netbox#4206]
### Environment
* Python version: 3.6.9
* NetBox version: 2.7.6

### Proposed Functionality
The WTI line of Console Servers have an optional console port that could be a built in modem which has an rj-11 type of connector. We would like to add an RJ-11 type to netbox/dcim/choices.py

In the WTI box where the modem is installed a proper inventory could be listed

None

None

**Comment by jeremystretch** [comment]
Makes sense to me.
