### ISSUE TITLE
Filter 'Enabled' on interface views. 

### ISSUE THREAD

**Issue by darcynz** [netbox-community/netbox#4209]
### Environment
* Python version:   3.7
* NetBox version:   2.7.6

### Proposed Functionality
a) On the interface components page have a filter so that interfaces can be filtered by their enabled state (True / False). 
netbox/dcim/interfaces/

~b) On a device page, have a button to hide disabled interfaces. This could be next to the who IP's button.
netbox/dcim/devices/1~

### Use Case
To easily allow users to only show Enabled interfaces. Usually when we look at a devices we want to just see the enabled interfaces. However many may appear if they currently disabled.

### Database Changes
None

### External Dependencies
None

**Comment by jeremystretch** [comment]
> On a device page, have a button to hide disabled interfaces. This could be next to the who IP's button.

Please submit a separate feature request for that as it is not directly related to the first point.
