### ISSUE TITLE
Cisco DNA Center - Netbox Integration

### ISSUE THREAD

**Issue by sebastienremaud** [netbox-community/netbox#4210]
### Environment
* Python version:   3.7.3
* NetBox version:  2.7.4 

### Proposed Functionality

In our company we are starting to use Cisco DNA center.
We did some research and we saw that any IPAM can integrate DNA center
Is it possible that Netbox integrate the fully REST API of Cisco DNA center?

This document provides an overview and REST API specification for an external IP Address Management (IPAM) Provider Service for integration with a Cisco DNA Center : 
https://developer.cisco.com/docs/dna-center/#!cisco-dna-center-ipam-integration-api-introduction/cisco-dna-center-ip-address-management-provider-integration  

### Use Case

  No

### Database Changes

   No

### External Dependencies

  Yes -> Cisco DNA Center

**Comment by DanSheps** [comment]
We already provide the following for integration:

* Webhooks
* REST API
* Scripts
* Plugins (Coming soon)

As much as I would love to see something for DNAC, it is such a minor audience we can justify spending time developing only for it.
