### ISSUE TITLE
Interface naturalization function discards non-matching portion of value

### ISSUE THREAD

**Issue by jeremystretch** [netbox-community/netbox#4211]
### Environment
* Python version: 3.6.9
* NetBox version: 2.7.6

### Steps to Reproduce
1. Create eight interfaces on a device using the pattern `PCIe[2-3]-p[1-4]`
2. View the device's interfaces list

### Expected Behavior
All interfaces should appear in order

### Observed Behavior
Interfaces are not ordered with respect to the portion of the name following the hyphen. For example, PCIe2-p4 may appear before PCIe2-p1.

**Comment by tfboy** [comment]
Thank you! :)
Xavier
