### ISSUE TITLE
get all prefixes by vlan id

### ISSUE THREAD

**Issue by Dimaqa** [netbox-community/netbox#4212]
### Environment
* Python version:  3.6.9 
* NetBox version:  2.7.6

So if we have 2 vlans with the same id and 2 prefixes in those vlans, api get all prefixes by vlan_id
will get only 1 result

### Steps to Reproduce
1. Create 2 vlans with same id
2. Create 2 prefixes and place them in different vlans
3. get /api/ipam/prefixes/?vlan_id={created id}

### Expected Behavior

Should get all prefixes

### Observed Behavior

Got only one result

**Comment by jeremystretch** [comment]
`vlan_id` references the database ID of a particular VLAN object (which is assigned by NetBox). You want `vlan_vid`, which references the 802.1Q identifier (1-4094) assigned to the VLAN.
