### ISSUE TITLE
Negative Voltage Support on Power Feeds

### ISSUE THREAD

**Issue by craized** [netbox-community/netbox#4218]
### Environment
* Python version:  3.6.8
* NetBox version:  2.7.7

### Proposed Functionality
I would like to support negative voltage on power feeds.
This support could come from a change in data sanitization of the 'voltage' field
Alternatively, a negative_voltage boolean could be added (this one seems like too much trouble)

### Use Case
In DC power plant applications, it's common to receive -48V DC power feeds. Specifically, this application is used in all AT&T central offices, although I'm quite certain other facilities have gone this route as well.

### Database Changes
No change required for the first proposed option
For the second proposed option, a boolean field would need to be added to the dcim_powerfeed table

### External Dependencies
None

### Extra Notes
I posted this request on the Google Group, but haven't gotten any feedback at this point
https://groups.google.com/forum/#!topic/netbox-discuss/pJA6cRqAbqg

**Comment by craized** [comment]
This references previous issue  #4205 which didn't match a valid request template

**Comment by jeremystretch** [comment]
I'm honestly a little surprised this hasn't come up until now.
