### ISSUE TITLE
Visibility of Tags missing under Devices and VirtualMachine Listing

### ISSUE THREAD

**Issue by abhilashchinthalapudi** [netbox-community/netbox#4219]
### Environment
* Python version:   3.6.8 
* NetBox version:  2.7.7

I have this under 2.6.12 
### Steps to Reproduce
1. Go to Devices
2.Scroll to Bottom 
3.We should be able to see Tags associated with all devices in Right Bottom Corner

1. Go to Virtual Machines
2.Scroll to Bottom 
3.We should be able to see Tags associated with all devices in Right Bottom Corner

### Expected Behavior
There should be a Tags Component that has all the defined Tags

### Observed Behavior
No Tags Visible under Devices and Virtual Machine

**Comment by hSaria** [comment]
As of https://github.com/netbox-community/netbox/issues/2921, these have been replaced with a drop down menu, like the rest of the filter fields.

**Comment by abhilashchinthalapudi** [comment]
Ahh @hSaria  Thank you for that .Missed it
