### ISSUE TITLE
utilities/api.py uses the wrong comparison operator in a few cases

### ISSUE THREAD

**Issue by ebusto** [netbox-community/netbox#4220]
# Environment
* Python version:  3.8
* NetBox version:  2.7.7

### Steps to Reproduce
Start NetBox with Python 3.8 or newer.

### Expected Behavior
No warnings.

### Observed Behavior
Python emits the following warnings.

```
/opt/netbox/netbox/utilities/api.py:94: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if obj is '':
/opt/netbox/netbox/utilities/api.py:109: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if data is '':
```

**Comment by kobayashi** [comment]
Thank you for submitting your issue. NetBox does not support python 3.8 right now. Please try version 3.5 or 3.6 for now.

**Comment by ebusto** [comment]
This isn't an incompatibility. Rather, Python 3.8 is informing the developer that they used the wrong operator. This is a trivial fix, so why not do the right thing?

**Comment by jeremystretch** [comment]
Official support for Python 3.8 is being discussed elsewhere (see #4229), but aside from that I don't think we need bug reports for warning messages. They will be identified and addressed as needed through the course of development.
