### ISSUE TITLE
Importing csv exports breaks if a combination of quotes and line breaks are used in the comment field

### ISSUE THREAD

**Issue by dare-to-recurse** [netbox-community/netbox#4222]
### Environment
* Python version: 3.6.8
* NetBox version:  2.7.7

### Steps to Reproduce
1. Create site "Demo site" with the following in the comment field:
```
This is "broken" due to quotes in comment content
Some additional text on a new line.
```

3. Export sites to a csv file using the Export button
4. Delete "Demo site" from NetBox
5. Open page for importing sites
6. Copy the content of the exported file into the import form for sites.
7. Click Submit button

### Expected Behavior
Import to succeed and "Demo site" to be created again with the same information as what was exported.

### Observed Behavior
Import fails with message "Row 2: Expected 17 columns but found 1"

**Comment by hSaria** [comment]
I think we need to replace every instance of `"` with `""` when exporting, as per 2.7. in [RFC4180](https://tools.ietf.org/html/rfc4180#page-3). So something like this would do it:
```diff
diff --git a/netbox/utilities/utils.py b/netbox/utilities/utils.py
index 6969a60e..83442566 100644
--- a/netbox/utilities/utils.py
+++ b/netbox/utilities/utils.py
@@ -31,9 +31,9 @@ def csv_format(data):
         if not isinstance(value, str):
             value = '{}'.format(value)
 
-        # Double-quote the value if it contains a comma
-        if ',' in value or '\n' in value:
-            csv.append('"{}"'.format(value))
+        # Double-quote the value if it contains a comma and replace double-quotes in the data with 2x double-quotes.
+        if ',' in value or '\n' in value or '"' in value:
+            csv.append('"{}"'.format(value.replace('"', '""')))
         else:
             csv.append('{}'.format(value))
```
