### ISSUE TITLE
Omit internal fields from change logs

### ISSUE THREAD

**Issue by hSaria** [netbox-community/netbox#4227]
### Proposed Changes

Omit private/internal model fields from change logs. The current list of private fields:

* `_name`: used for ordering
* (`dcim.Interface`) `_connected_circuittermination`, `_connected_interface`: unsure if they're meant to be visible in the change logs
* (`dcim.Region`) `level`, `lft`, `rght`, `tree_id`: the MPTT fields
* (`dcim.Cable`) `_abs_length`, `_termination_a_device`, `_termination_b_device`: normalization/caching

### Justification

The fields do not serve any purpose outside of NetBox. By removing them from the change logs, they will look more readable to a user. This idea surfaced in https://github.com/netbox-community/netbox/issues/4183#issuecomment-587141060.

**Comment by hSaria** [comment]
Here's an example of how a region's change log would benefit from this.

#### Before
```json
{
    "created": "2020-02-10",
    "last_updated": "2020-02-10T13:19:37.319Z",
    "level": 0,
    "lft": 1,
    "name": "'murica",
    "parent": null,
    "rght": 2,
    "slug": "murica",
    "tree_id": 2
}
```


#### After
```json
{
    "created": "2020-02-10",
    "last_updated": "2020-02-10T13:19:37.319Z",
    "name": "'murica",
    "parent": null,
    "slug": "murica"
}
```

**Comment by kobayashi** [comment]
That make sense. I accept this

**Comment by jeremystretch** [comment]
We need to devise a robust mechanism for controlling whether a field appears in the serialized representation. I would prefer to avoid making any static declarations (like what we do for CSV headers) as they're tedious to maintain. Simply ignoring fields prefaced with an underscore probably takes care of 80% of this. We can implement/tweak `to_objectchange()` on the remaining models to suppress any unwanted fields.

**Comment by DanSheps** [comment]
> We need to devise a robust mechanism for controlling whether a field appears in the serialized representation. I would prefer to avoid making any static declarations (like what we do for CSV headers) as they're tedious to maintain.

What about a hybrid, allows us to handle the MPTT case as that isn't captured by the underscore case.

**Comment by jeremystretch** [comment]
I think it's reasonable to tackle that using a custom `to_objectchange()` method on the Region model.

**Comment by hSaria** [comment]
I see this was accepted. Anyone working on this or shall I?

I was gonna follow what Jeremy said and pop any fields prefixed with `_` in `ChangeLoggedModel.to_objectchange` and override `Region.to_objectchange` to additionally remove the MPTT fields.

**Comment by jeremystretch** [comment]
@hSaria feel free to take this one if you'd like.
