### ISSUE TITLE
Add supported python version

### ISSUE THREAD

**Issue by kobayashi** [netbox-community/netbox#4229]
### Change Type
[x] Addition
[ ] Correction
[ ] Deprecation
[ ] Cleanup (formatting, typos, etc.)

### Area
[x] Installation instructions
[ ] Configuration parameters
[ ] Functionality/features
[ ] REST API
[ ] Administration/development
[ ] Other

### Proposed Changes
There are no description which python versions are currently supported. Worth add the list of python version in the docs or README. I think [Install Python Packges](https://netbox.readthedocs.io/en/mkdocs-testing/installation/2-netbox/#install-python-packages) in the docs the place to add the list

**Comment by jeremystretch** [comment]
We should also consider testing. We currently test against only the minimum supported Python version (which will change to 3.6 with NetBox v2.8). We can [test against multiple versions](https://docs.travis-ci.com/user/languages/python/#specifying-python-versions) but is it going to be worth the overhead to tests on every push/merge?

**Comment by DanSheps** [comment]
I haven't looked too much into travis, but is it possible to perform certain tests only on master/develop and not each PR?  I think testing on a merge to develop would still be wise, but perhaps not on every PR.

**Comment by lampwins** [comment]
> We can test against multiple versions but is it going to be worth the overhead to tests on every push/merge?
I vote yes. I really don't cost us anything then maybe having to wait an extra minute or two every once in a while. I don't see this as reason _not_ to test, as it will begin to identify issues like #4220.

**Comment by kobayashi** [comment]
The place to add the description about supported version is better under [Application Stack](https://netbox.readthedocs.io/en/stable/#application-stack) like this.

![image](https://user-images.githubusercontent.com/8712070/75159960-34b60680-56e7-11ea-8339-37bf28129997.png)

Also, I supports @lampwins's idea, so simply would add python version to the current travis.yml for testing.

```
python:
  - "3.5"
  - "3.6"
  - "3.7"
```

Any thoughts?
