### ISSUE TITLE
Unable to filter by rack unit on elevations endpoint

### ISSUE THREAD

**Issue by DanSheps** [netbox-community/netbox#4230]
### Environment
* Python version:  3.6.8
* NetBox version:  2.7.8-dev

### Steps to Reproduce
1. Create a site
2. Create a rack
3. Perform API query against /api/dcim/racks/###/elevation?q=23

### Expected Behavior

Only position 23 should be returned

### Observed Behavior

All positions are returned

**Comment by DanSheps** [comment]
https://github.com/netbox-community/netbox/blob/20b36f910f45563f05ef7295dd7cb705afad3af3/netbox/dcim/api/views.py#L239

Insert after:

```
            # Enable filtering rack units by ID
            q = request.GET.get('q', None)
            if q:
                elevation = [u for u in elevation if q in str(u['id'])]
```

**Comment by lampwins** [comment]
Ha, that the time this was taken out, no one could answer what it was used for. Now that we know, it would be really nice to have a test for it.

**Comment by DanSheps** [comment]
Yeah, I was thinking we could add just a simple API test for it.  Couple of queries against a rack, make sure we get back stuff that makes sense.
