### ISSUE TITLE
Import device inventory items from the Status menu output.

### ISSUE THREAD

**Issue by saneksun** [netbox-community/netbox#4231]
### Environment
* Python version:  3.6.9
* NetBox version:  2.7.7 

### Proposed Functionality

As a Netbox user I would like to have the ability to add Device Status menu output (chassis, modules models/serial numbers) to Device Inventory Hardware tab. 

### Use Case

This feature would be beneficial in the case of using Netbox as an hardware inventory DB. 

### External Dependencies
![device_show_output](https://user-images.githubusercontent.com/39739673/75055196-90dc1900-54a2-11ea-90ad-6e291c6e0e68.PNG)

**Comment by jeremystretch** [comment]
We are not entertaining the extension of the InventoryItem model at this time beyond what has already been proposed in existing issues.
