### ISSUE TITLE
Add Version Control

### ISSUE THREAD

**Issue by samlambert13** [netbox-community/netbox#4234]
### Environment
* Python version:  3.6.8
* NetBox version:  2.6.11

### Proposed Functionality
Would a version control feature would be realistic ? Like after you made X number of change, you perform a version control to have an historic of what where the configuration at an X date.
This could be perform by a button an a second screen to enter the information about the change control (like a title (username_date_time))

### Use Case
I'm working in pharma, and everithing need to be tracable and documented. And for the moment, the only way I can have version control for our documentation is in a spreadsheet, that we make a new version each time we do a modification. This is part of Data Governance/Integrity.

### Database Changes
I don't think about any change on this level. 

### External Dependencies
None

**Comment by jeremystretch** [comment]
NetBox already provides a detailed change history for most objects. See also #151 for a proposed journaling implementation.
