### ISSUE TITLE
Support for creation of ConfigContexts using YAML-formatted data

### ISSUE THREAD

**Issue by jeremystretch** [netbox-community/netbox#4236]
### Environment
* Python version: 3.6.9
* NetBox version: 2.7.7

### Proposed Functionality
Implement the ability to create and edit config context data in YAML format. (Currently only JSON is available.) This follows #3313, which enabled the display of data in YAML format.

### Use Case
Offers convenience for users who have data already in YAML format, and achieves parity with the current ability to display data in either YAML or JSON.

### Database Changes
None

### External Dependencies
None

**Comment by sdktr** [comment]
What to do with fields that are a superset of JSON? Like comments and anchor options?

**Comment by jeremystretch** [comment]
The data is still stored as JSON in the database, so we either strip them silently or fail on validation.
