### ISSUE TITLE
VRF/VLAN status and VXLAN field

### ISSUE THREAD

**Issue by tomicke** [netbox-community/netbox#4243]
### Environment
* Python version:  3.6.9 
* NetBox version:  2.6.7

We have started to test Netbox with our new datacenter currently being deployed and apart from documenting the installation from rack to device and VRF/VLAN/VXLAN we would like to use Netbox to provision VRF and VLAN segments and document allocated VXLAN IDs(VNI).

### Proposed Functionality

I'm proposing to add status field to VRFs and complement current status field for VLANs. Currently i'm using the reserved and deprecated status choices. I would love some of the same choices you find under devices/racks.

I also propose to add a separate value field to VRF and VLANs so it is possible to document allocated VNIs

VRF:
Add status field with the following choices
- Active
- Planned
- Decommissioning

VLAN:
Add more choices to current status field
- Planned
- Decommissioning

VXLAN:
Add extra value field for VRF/VLANs to document VNIs 

### Use Case

To make it possible to add/remove planned or decommissioned VRF/VLANs in production with Python/Ansible and to document the VNIs used.

### Database Changes

Unknown

### External Dependencies

Unknown

**Comment by DanSheps** [comment]
I don't think it makes sense to add a status field to VRF.  Neither does it make sense to add the additional status fields for VLAN (Planned, you can use reserved, Decommissioning, you can use Deprecated).

VXLAN has been asked for alot, I could see a use case for it, but if you can build up a better use case (not just "to document" as that can be done with tags) for VXLAN and perhaps flesh out a model (There have been previously discussed VXLAN issues: #3738, #2800, #1800, #1725, #1058, #825, #777) this could be something we could revisit.  Keep in mind, we are pretty backlogged with only 4 maintainers with other commitments outside of this.
