### ISSUE TITLE
Allow comments in device type import model

### ISSUE THREAD

**Issue by jmanteau** [netbox-community/netbox#4245]
### Environment
* Python version:  3.6.9
* NetBox version:  2.7.7

### Proposed Functionality
Currently device type import does not propose comments to the import. (Original PR #451).
This feature request is to propose adding the support of comments to the device type import model.

### Use Case
This would allow to add information regarding a model such as:

* WS-C2960-48TC-L: Catalyst 2960 - 48 100M data-only copper ports with dual-purpose ports (10/100/1000 or SFP) uplinks - LAN Base
* add the URL to the vendor website.
* etc

This could be interesting when coupled  with https://github.com/netbox-community/devicetype-library

### Database Changes

None

### External Dependencies

None

**Comment by jeremystretch** [comment]
This was considered and declined during implementation of the import function. Comments are not included because they are not part of the real-world device definition.
