### ISSUE TITLE
Hide disabled interfaces when viewing Device

### ISSUE THREAD

**Issue by darcynz** [netbox-community/netbox#4247]
### Environment
* Python version:  3.7
* NetBox version: 2.7.6

### Proposed Functionality
On a device page, have a button to hide disabled interfaces. This could be next to the show IP's button.
netbox/dcim/devices/1

### Use Case
To easily allow users to only show Enabled interfaces. Usually when we look at a devices we want to just see the enabled interfaces. However many may appear if they are currently disabled.

### Database Changes
None

### External Dependencies
None

**Comment by jeremystretch** [comment]
Blocked by #4193.

**Comment by darcynz** [comment]
When this is unblocked.. it  would be ideal if there is an option to either:
a) Show all interfaces (default)
b) Hide disabled interfaces
c) Hide enabled interfaces

**Comment by jeremystretch** [comment]
We can still do this, but I don't think it needs to be a v3.0 milestone.
