### ISSUE TITLE
API: Power Outlet Template Bug

### ISSUE THREAD

**Issue by minitriga** [netbox-community/netbox#4252]
### Environment
* Python version:  3.7
* NetBox version:  2.7.7

When creating a device type with the API adding a power outlet template to the device type produces errors.

### Steps to Reproduce
1. Create Device Type 
2. Add Power Port
3. Adding a power outlet template via API with the minimum amount of information required works (name, device_type) but this does not create a power outlet that is related to a power port. 
```
{
  "device_type": 297,
  "name": "1"
}
```
4. Trying again on a new outlet number adding in the power_port information fails. Using the minimum amount of information required by the swagger API docs.
```
{
  "device_type": 297,
  "name": "2",
  "power_port": {
    "name": "Power Port",
    "device_type": {
      "model": "Test PDU",
      "slug": "test-pdu"
    }
  }
}
```
This produces the following error:
```
{
  "power_port": {
    "non_field_errors": [
      "The fields device_type, name must make a unique set."
    ]
  }
}
```

### Expected Behavior
That a power outlet template is added to the database that is linked to a power port template for a device type. 

### Observed Behavior
Adding a power outlet fails as with the description following error:
```
{
  "power_port": {
    "non_field_errors": [
      "The fields device_type, name must make a unique set."
    ]
  }
}
```

I wonder if we could just use the ID of the power_port and make sure the power port is linked to the same device_type. 

Thank you.

**Comment by jeremystretch** [comment]
```
{
  "device_type": 297,
  "name": "2",
  "power_port": {
    "name": "Power Port"
  }
}
```

The above should be all you need to create a new power outlet template on a device type. (Note that you could optionally use a dictionary specifying the device type manufacturer and model instead of its primary key if you prefer.) The commit pushed above should resolve this.
