### ISSUE TITLE
Extend "Add Device" field with drop-down of Device-Type

### ISSUE THREAD

**Issue by rafac92** [netbox-community/netbox#4254]
### Environment
* Python version:  3.6.8
* NetBox version:  2.7.7

### Proposed Functionality
I would like to have additional Drop-Down menus (like in the attached picture)

![image](https://user-images.githubusercontent.com/59090943/75164726-811e3800-5721-11ea-99bd-06ad09679db6.png)

to already have some values predefined (depending on the selection) when adding new devices

### Use Case
When I add a new Device I need to fill a lot of Fields. With the proposed functionality I could just choose the device-type I want to add and within this, several fields could be prefilled so there is no unnecessary entry needed.
For Example there would be the drop-down entry "ProLiant DL380 Gen10". 
If this is selected, the Fields "Device role", "Manufacturer" and maybe customfields could already be prefilled with the values "Server", "HPE", ...

### Database Changes
-

### External Dependencies
-

**Comment by jeremystretch** [comment]
This would greatly complicate the UI for no real benefit: you still have to select the device type either way. It's better to do so on the actual form where we already have the widget and scripting in place to allow dynamic filtering.
