### ISSUE TITLE
Rack view - New Item for passive components

### ISSUE THREAD

**Issue by rafac92** [netbox-community/netbox#4256]
### Environment
* Python version:  3.6.8
* NetBox version:  2.7.7

### Proposed Functionality
In the "Rack Elevation" or "Rack" View I would like to have the possibility to also document Items which are currently not devices, such as Rack-Panales or cable management items. 
So I would like to have the possibility to add those Items to Racks. 

![image](https://user-images.githubusercontent.com/59090943/75169135-52f02680-5728-11ea-8ae2-fb404f2f2c13.png)
![image](https://user-images.githubusercontent.com/59090943/75169233-7b782080-5728-11ea-8920-f963d69c387c.png)

In the best case it would be good if these Items are not devices since I don't see there a need to have unique Names/IDs or the need of Manufacturors.

### Use Case
Within this functionality you could depict the Rack as it is with all the passive components

### External Dependencies

Sources of images: 
https://www.reichelt.de/rangierpanel-19-5-port-1-he-delock-42116-p163146.html?PROVID=2788&gclid=EAIaIQobChMI8M_FpMnq5wIVkud3Ch2hkQpDEAQYAiABEgL5wPD_BwE&&r=1
and
https://www.alleskabel.de/installation/anschlussfelder-19/rack-panel-zur-ventilation-1-2-mm-stahl-2-he-schwarz

**Comment by jeremystretch** [comment]
These should be modeled as devices in NetBox. Please see the discussion #417.
