### ISSUE TITLE
Rack elevations stopped displaying after 2.6.7 upgrade to 2.7.5

### ISSUE THREAD

**Issue by j-munroe** [netbox-community/netbox#4259]
### Environment
* Python version:  3.6.9
* NetBox version:  2.5.7

### Steps to Reproduce
1. Via webui, goto Organizations -> Racks -> "pick a rack #"
2. All that is displayed on the right hand side is the Front and Rear text headers with no image display.
![BUG](https://user-images.githubusercontent.com/19651699/75176588-ce42df80-570a-11ea-9777-d72e1bab52f5.JPG)

### Expected Behavior

Front and rear view of rack displayed with assigned equipment displayed? :-)

### Observed Behavior

No svg images, please see attachment of actual display.  Last note, this worked fine under 2.6.7 prior to upgrading to 2.7.

**Comment by jeremystretch** [comment]
This issue occurs when the HTTP server (e.g. nginx or Apache) is configured to set the `X-Frame-Options` response header to `DENY`. Please see [this wiki article](https://github.com/netbox-community/netbox/wiki/Common-Issues#rack-elevations-do-not-display-v27) for help resolving the issue.

**Comment by j-munroe** [comment]
Thank You!  That was the issue on my nginx deployment.  Sorry I didn't even see that wiki entry.
