### ISSUE TITLE
Support for subfolders in Reports/Scripts

### ISSUE THREAD

**Issue by mmahacek** [netbox-community/netbox#4260]
### Environment
* Python version:  3.6
* NetBox version:  2.7.7

### Proposed Functionality

Support for detecting files in subfolders of Reports/Scripts

### Use Case

The community repository has reports sorted into subfolders, and it could be helpful to users that want to just pull down the report repo structure as is, to more easily maintain changes to the files over time.

### Database Changes

None

### External Dependencies

None

**Comment by jeremystretch** [comment]
This would be a real pain to accommodate in the UI and API. It's also likely to frustrate future efforts around auto-detecting changes. I have to decline this one as the development burden it would introduce is disproportionate to the negligible benefit gained.
