### ISSUE TITLE
Tags Select2 filter presents union results for multiple groups

### ISSUE THREAD

**Issue by darcynz** [netbox-community/netbox#4266]
### Environment
* Python version: 3.7  
* NetBox version: 2.7.6  

### Steps to Reproduce
1. On any page that allows filtering by tags
2. Select multiple tag groups and search

### Expected Behavior
Any object that contain's one of the tags is presented.

### Observed Behavior
Only objects are presented that contain all tags specified in query (union results).

**Comment by jeremystretch** [comment]
> Only objects are presented that contain all tags specified in query (union results).

This is the expected behavior. Please see #2558.
