### ISSUE TITLE
Incorrect IPs displaying while filtering interface

### ISSUE THREAD

**Issue by Arkasha99** [netbox-community/netbox#4270]
### Environment
* Python version:  3.6.17
* NetBox version:  2.7.4

### Steps to Reproduce
1.Open device view
2.Find interfaces table
3.Display IPs using "show IPs" button, don't turn it off.
4.Find particular interface with filter 

### Expected Behavior
The expected result was the interface with related IPs

### Observed Behavior
I got interface with the list of all IPs. They're not even related to my interface.

**Comment by hSaria** [comment]
I couldn't replicate this on v2.7.4 nor v2.7.7. Could you clarify step 4, possibly by providing the filter and a couple of the interfaces' names?

**Comment by Arkasha99** [comment]
Sorry, it looks like my own local changes created this issue.
Sorry for wasting your time.
