### ISSUE TITLE
Explore using API serializer for ObjectChange representation

### ISSUE THREAD

**Issue by jeremystretch** [netbox-community/netbox#4273]
### Proposed Changes
Explore the benefits and drawbacks of replacing the current ObjectChange serialization mechanism with the REST API serializers. I haven't dug into this yet but believe it's worth a look.

### Justification
Consolidating serializers would allow us to ditch some code while ensuring a consistent representation of serialized objects throughout NetBox.

**Comment by sdktr** [comment]
Ditching duplicate (functionality wise) code, +1

**Comment by ebusto** [comment]
I took this approach in the NetBox Kafka producer [plugin](https://github.com/ebusto/netbox-kafka-producer/blob/master/netbox_kafka_producer/middleware.py#L17), and it works like a charm. Having slightly more information in place of foreign keys is really handy.
