### ISSUE TITLE
IP Prefix Family returned doesn't match swagger definition

### ISSUE THREAD

**Issue by z4ce** [netbox-community/netbox#4274]
### Environment
* Python version:   3.7.6
* NetBox version:  v2.7.7

Swagger definition for Prefix.Family does not match the swagger definition.

### Steps to Reproduce
1. Get a prefix object `wget http://netbox/api/ipam/prefixes/210/`
2. Notice object is like
```
  "family": {
    "value": 4,
    "label": "IPv4"
  },
```
3. Notice definition is
```
  "family": {
    "label": "string",
    "value": "string"
  },
```

### Expected Behavior
Object returned matches definition. I'm not sure if the definition needs to be fixed or the returned value type needs to be changed.

### Observed Behavior
Object doesn't match definition

**Comment by z4ce** [comment]
cc @wbean1

**Comment by tyler-8** [comment]
What specifically are you calling out here? The ordering of the fields or the data type returned for the `value` key?

**Comment by z4ce** [comment]
`value` is returned as an integer and not a string as the swagger definition calls out. According the swagger the prefix family should be:

```
"family": {
    "value": "4",
    "label": "IPv4"
  },
```

Or if the returned type is correct then the swagger should be:
```
  "family": {
    "label": "string",
    "value": "integer"
  },
```

**Comment by kobayashi** [comment]
ChoiceField which contains `int` values like `IPAddressFamilyChoices` and `RackWidthChoices` has the same issue.
