### ISSUE TITLE
TypeError exception when editing IP address

### ISSUE THREAD

**Issue by rodvand** [netbox-community/netbox#4279]
### Environment
* Python version:  3.6.8
* NetBox version:  2.7.8

### Steps to Reproduce
1. Edit IP address of any device or VM 

### Expected Behavior
The form with option of editing the IP address to load.

### Observed Behavior
Exception: int() argument must be a string, a bytes-like object or a number, not 'TenantGroup'.

This only happens when the IP address is assigned a tenant.

**Comment by rodvand** [comment]
This only happens when a tenant is specified.

**Comment by jeremystretch** [comment]
I'm not able to replicate this. Please extend the issue to include the specific steps needed to reproduce this bug, beginning with the device/IP creation.

**Comment by rodvand** [comment]
Yeah, after a couple of restarts I am also unable to replicate this on my test instance. I'm closing it for now.
