### ISSUE TITLE
Allow filtering device component lists by type (where applicable)

### ISSUE THREAD

**Issue by candlerb** [netbox-community/netbox#4281]
### Environment
* Python version:  3.5.2
* NetBox version:  2.7.8

### Proposed Functionality

At the interfaces listing page (`/dcim/interfaces/`), allow filtering by interface Type.

(Potentially could also be done for other components like console ports and power ports; I wouldn't use that as much)

### Use Case

* Show me all virtual interfaces
* Show me all LAG interfaces
* Show me all SFP+ interfaces (etc)

### Database Changes

None

### External Dependencies

None

**Comment by DanSheps** [comment]
I think this should come after #4193

**Comment by DanSheps** [comment]
Blocked: #4193

**Comment by jeremystretch** [comment]
I don't think this is related to #4193: we're looking at the global interfaces list rather than the individual device view. Should just need to add a `type` field to InterfaceFilterForm.

**Comment by jeremystretch** [comment]
Extending this to incorporate all device components with a type.
