### ISSUE TITLE
DeviceType export button mentions CSV instead of YAML

### ISSUE THREAD

**Issue by Alex131089** [netbox-community/netbox#4282]
### Environment
* Python version:  3.7-alpine (docker)
* NetBox version:  2.7.8-ldap (docker)

### Steps to Reproduce
1. Go to device-types list: /dcim/device-types/
2. Click `Export` button

### Expected Behavior
To see `YAML (default)`

### Observed Behavior
I see `CSV (default)`

### Notes:

This is following https://github.com/netbox-community/netbox/issues/3801.

I guess the related files are:
* https://github.com/netbox-community/netbox/blob/v2.7.8/netbox/dcim/views.py#L563
* https://github.com/netbox-community/netbox/blob/v2.7.8/netbox/utilities/views.py#L60
* https://github.com/netbox-community/netbox/blob/v2.7.8/netbox/extras/models.py#L576
* https://github.com/netbox-community/netbox/blob/v2.7.8/netbox/utilities/templates/buttons/export.html

**Comment by jeremystretch** [comment]
Note: To reproduce this, you must have at least one export template defined for device types.
