### ISSUE TITLE
Add MRJ21 as port type as well as MRJ21 cable assembly as cable type

### ISSUE THREAD

**Issue by marktizzard** [netbox-community/netbox#4284]
### Environment
* Python version:  3.6.8
* NetBox version:  2.7.7

### Proposed Functionality
Add additional port type of "MRJ21" port for pre-terminated cable deployments as well as addition cable type of 'MRJ21 cable assembly' for connection between MRJ21 ports.

### Use Case
This would aid users who currently use modular components to build data center infrastructure, rather than traditional individual cable pulls with standard terminations for copper cabling (Cat5e\Cat6\Cat6a). For example we employ the use of pre-terminated MRJ21 cable assemblies in pre-determined lengths to be able to add capacity on the fly without a cabling tech to perform terminations of tradition category cabling. While the configuration described can be modeled using existing cable types and connectors within the tool, the ability to denote the difference between pre-terminated vs traditional terminated cable would be useful in the tool.

Included device drawings as an example of what the system looks like:

Cable assembly:
https://www.commscope.com/globalassets/digizuite/43343-2111439-c-pdf.pdf

Cassette with 6 8P8C front and 1 MRJ21 rear:
https://www.commscope.com/globalassets/digizuite/42255-1479459-c-pdf.pdf

However just the addition of the MRJ21 connector would allow these and other similar devices to be modeled by the end user.

### Database Changes
Not entirely sure - I suspect it is just an addition of another cable and connector type the list of existing types. I am not familiar with the relationships between types and connectors and if that would change database relationships or schemas.

### External Dependencies
None

**Comment by jeremystretch** [comment]
What's the canonical name for the cable itself? "MRJ21 Trunk" would probably work but should we stick to something more generic?

**Comment by marktizzard** [comment]
"MRJ21 Trunk" would be best here - this would be the most generic way to describe this cable assembly type amongst different vendors. The canonical name would be "MRJ21 Cable Assembly" - which could mean different things depending on the termination and\or breakouts, so in this application trunk makes most sense as it is a trunk in data networking terms.
