### ISSUE TITLE
Incorrect Type for Device & VM `local_context_data`

### ISSUE THREAD

**Issue by dstarner** [netbox-community/netbox#4288]
### Environment
* Python version:  3.7
* NetBox version:  2.7.8

### Steps to Reproduce
1. Add config context to a device
1. Using any generated Swagger client - we used go-netbox - try to hit one of the list routes `/devices` or `/virtual-machines`
1. Watch the strongly-typed swagger client explode as it tries to convert a dict/map into a string

### Expected Behavior

`local_context_data` should be defined in the Swagger documentation as either `null` or as an object/dict/map so that it can be handled correctly by strongly typed swagger clients.

### Observed Behavior

![Screen Shot 2020-02-26 at 2 12 26 PM](https://user-images.githubusercontent.com/10478871/75379979-4395e800-58a4-11ea-9127-bb4850c24b74.png)

`local_context_data` is type-unaware and its converted into a string, meaning that Swagger clients will try to parse it out as a string, which will cause type errors on strongly typed systems

**Comment by dstarner** [comment]
Solving this would require a similar approach as what is done in the following
https://github.com/netbox-community/netbox/blob/62efe0621f710310f9bceb46fd6d27b0d57bfb3c/netbox/dcim/api/serializers.py#L426-L428

Pull it out as a serializer method and decorate it with the correct type

**Comment by jeremystretch** [comment]
Open for volunteers.

**Comment by dstarner** [comment]
@jeremystretch can you assign me? I can make a PR for this. Its a pretty easy fix
