### ISSUE TITLE
Incorrect Authorization Header included in swagger curl Examples

### ISSUE THREAD

**Issue by dstarner** [netbox-community/netbox#4289]
### Environment
* Python version:  3.7
* NetBox version:  2.7.8

### Observed Behavior

NetBox's Swagger documentation does not include the `Token` prefix in the `Authorization` header. This makes it misleading of how to connect correctly to the API. The picture below is old, please see @kobayashi 's screenshot below.

![Screen Shot 2020-02-26 at 2 45 44 PM](https://user-images.githubusercontent.com/10478871/75381411-af795000-58a6-11ea-82a4-94fea65be8d8.png)

### Expected Behavior

I should be able to copy and paste a `curl` command (almost) and dump it into into a terminal for it to work. I would like to see something like `-H "Authorization: Token $NETBOX_TOKEN"` so that I could use it as a valid example.

**Comment by kobayashi** [comment]
You can see it after you set apikey through "Authorized" button which is placed right side of top.

![Screenshot from 2020-02-28 00-06-06](https://user-images.githubusercontent.com/8712070/75512037-28b79680-59be-11ea-963f-2990b7aeaeeb.png)

**Comment by dennisgove** [comment]
Yes, that header information is displayed. However, the actual header that needs to be sent in is `Authorization: Token <actual token>`. The `Token ` prefix before the actual token doesn't appear in this header.

**Comment by jeremystretch** [comment]
Open for volunteers.

**Comment by kobayashi** [comment]
Ah, sorry I miss understood this issue. `Token ` prefix before the value could not be in OPENAPI Spec v2.0 which is generated in drf-yasg. To make it possible, you have to add the prefix when set your token in authenticate window like `Token <token here>`. The similar issue was asked [here](https://github.com/axnsan12/drf-yasg/issues/46)

**Comment by dstarner** [comment]
Ah, okay then, interesting. So this is probably something we can close then? Or is there a way we can show it without hacking drf-yasg? It would be helpful since NetBox relies on the `Bearer` being there

**Comment by kobayashi** [comment]
I would like to avoid to add some hacking way for this because it might leads not follow the spec version. Or, it will be difficult maintain and upgrade drf-yasg in the future.
If the purpose of this issue is to copy & paste, we can do it even though a little tricky :stuck_out_tongue:
BTY, I think we can set the value after drf-yasg will supports openapi spec v3.0 probably.

**Comment by kobayashi** [comment]
Close this because openapi spec v2.0 (current drf-yasg supported) is not supported to show `Token` prefix in curl example.
