### ISSUE TITLE
Loosening Circuit Unique ID

### ISSUE THREAD

**Issue by darcynz** [netbox-community/netbox#4291]
### Environment
* Python version:  3.7 
* NetBox version:  2.7.6 

### Proposed Functionality
Circuit ID field is not required to be unique

### Use Case
Circuit ID is quite often not known until it is provision. In the interim state ('planned') a value can be entered but represents placeholder data  eg 'TBA1', or 'Circuit1'.

Uniqueness can be enforced by other methods, eg netbox reports.

This request would also reflect consistency with recent decision to make device names non unique.

### Database Changes
Field change - circuit ID

### External Dependencies
None

**Comment by jeremystretch** [comment]
Enforcing circuti ID uniqueness is crucial in many applications. If you need to work around this, you can use dummy IDs until the circuit has been fully provisioned.
