### ISSUE TITLE
Checkbox for extended search by port description

### ISSUE THREAD

**Issue by gorbushka** [netbox-community/netbox#4292]
[x] Feature request

### Environment
* Python version:  3.7
* NetBox version:  2.6.12

### Proposed Functionality
It would be very useful to enable **"enhanced search" checkbox** to search by all description fields of devices. I know It was already be closed without satisfaction in [#1363](https://github.com/netbox-community/netbox/issues/1363) and [#3468](https://github.com/netbox-community/netbox/issues/3468) and [#3076](https://github.com/netbox-community/netbox/issues/3076) but i want to show 2 use cases.

### Use Case

1. To document far end device without creating it in netbox if it couldn't be in netbox according to accepted gathering data depth.
2. Search some lost forgotten port or connection

**Comment by jeremystretch** [comment]
This has been proposed and declined. Please don't open duplicate issues.
