### ISSUE TITLE
Parent LAG box grayed out when editing interfaces in bulk

### ISSUE THREAD

**Issue by s-fu** [netbox-community/netbox#4295]
### Environment
* Python version:  3.6.9
* NetBox version:  2.7.8

### Steps to Reproduce
1. Create a device "switch" on web GUI
2. Create interface "Po1" with LAG type 
3. Checkbox multiple physical interfaces
4. Scroll down and click edit

### Expected Behavior
All the attributes should be editable.

### Observed Behavior
"Parent LAG" is grayed out, while "set null" works if there is an existing parent LAG. I can also edit the parent LAG attribute when editing a single interface.
![image](https://user-images.githubusercontent.com/43026027/75484457-b1521a80-595d-11ea-8e07-e0d03fe4b10a.png)

**Comment by JerradGit** [comment]
I was about to post this issue as well
