### ISSUE TITLE
Redis service start / Selinux configuration

### ISSUE THREAD

**Issue by git-eugene** [netbox-community/netbox#4296]
### Change Type
[X] Addition
[ ] Correction
[ ] Deprecation
[ ] Cleanup (formatting, typos, etc.)

### Area
[X] Installation instructions
[ ] Configuration parameters
[ ] Functionality/features
[ ] REST API
[ ] Administration/development
[ ] Other

### Proposed Changes
Hello NetBox Support Team!

Please add to the NetBox installation documentation points about the need to start the Redis service, as well as the need to configure Selinux or disable it.
The latter is one of the causes of the 502 Bad Gateway error.
This will save a lot of time that you have to spend on debugging.
Both changes are relevant at least for Centos/Fedora installations.

Thanks!

**Comment by jeremystretch** [comment]
> the need to start the Redis service

The Redis server should start automatically upon installation on most distributions.

> as well as the need to configure Selinux or disable it

Our documentation doesn't cover installation on SE Linux.
