### ISSUE TITLE
Add support for PON modular interface types

### ISSUE THREAD

**Issue by janchrillesen** [netbox-community/netbox#4302]
### Environment

* Python version:  3.6.8
* NetBox version:  2.7.8

### Proposed Functionality

Add support for PON types of optics/modules. This has been proposed earlier in issue 2882 where it was requested to provide a complete list of port types. The following is the types we have been able to identify

Category: PON modular

SFP (GPON OLT) 2,5G
SFP (XGS-PON OLT)  10G
SFP (CPON OLT) 10G/2,5G
SFP (EPON OLT) 1G
SFP (EPON OLT) 10G
SFP (DWDM-PON OLT) 10G
XFP (XGS-PON OLT) 10G
XFP (DWDM-PON OLT) 10G

### Use Case

This enhancement would allow us to properly support the PON interfaces on Nokia ISAM (and many other PON platforms). PON is a widely used access technology for residential fiber. Currently we're using ethernet ports to model the PON ports. Please notice that the PON optics are different from ethernet SFP and XFP modules.

### Database Changes

The proposed change would require a number of new interface types to be added to the existing list of types. However no new fields are required

### External Dependencies

None

**Comment by sdktr** [comment]
Just curious: how do you model a PON based access network in NetBox? How’s the passive splitter represented etc?

**Comment by DanSheps** [comment]
We typically don't model speed with interface port/types, it may seem like it but it is modeled as a by-product of the type (SFP+ is 10GE but it can also be 8GFC or 16GFC)

With that in mind, are these:

SFP (EPON OLT) 1G
SFP (EPON OLT) 10G

two discrete interface types?

**Comment by janchrillesen** [comment]
> Just curious: how do you model a PON based access network in NetBox? How’s the passive splitter represented etc?

We have decided to implement the splitter as a device with interfaces. For instance a 1:32 splitter has 33 interfaces (one uplink and 32 customer ports) - same concept as an unmanaged switch/hub. The concept of front and rear ports used for DDF/ODF panels, does not seem to allow a one-to-many mapping. It's the same issue with modelling DWDM filters.

That's the simple answer. It gets a bit more complicated when you have physical 1:32 splitters but want to do 1:64 or 1:128 split. It's often implemented by chaining splitters, for instance one 1:2 splitter feeding 2x 1:32 splitters, for a 1:64 split. We're still trying to decide on the best way to do this. 

- just model it as a 64 port splitter. Simple but makes changing the split ratio from 64 to 32 harder
- model it as a device with groups of ports (for instance port 1:[1-32], 2[1-32]
- model the actual implemention with 3 different splitters cabled together. This adds some complexity since all 3 splitters can be housed as modules within 1 rack unit, and netbox currently doesn't fully support the concept of modular devices (inventory is different from, say, linecards). To add further complexity, not all over installations have homerun of fiber, and the different splitters belonging to a single PON can be spread across several locations.

Our usecase is purely to allocate splitter ports for end-users, and modelling the cabling from splitter towards OLT

**Comment by janchrillesen** [comment]
> With that in mind, are these:
> 
> SFP (EPON OLT) 1G
> SFP (EPON OLT) 10G

They are different types. There exist a SFP based module that support 1G only, and SFP+ based modules that supports 10G and other support dual-rate 1G+10G (very similar to ethernet modules). Some OLT vendors calls their 10G based modules SFP, and not SFP+, however I think this is a mistake and merely used to differentiate between SFP and XFP form factors. 
The correct solution would be to change the formfactor of the 10G EPON from SFP to SFP+

- SFP (EPON OLT) 1G
- SFP+ (EPON OLT) 10G

Should I update the original request to reflect this, or just leave it here as a comment?

**Comment by jeremystretch** [comment]
Can anyone provide an authoritative list of the PON interface types currently available on the market? I'm not familiar with the technology myself and we need to be sure interface types we add are real and correct. It would also be nice to get them all added at the same time.

**Comment by BachuDevnet** [comment]
It would be great for this case to be re-opened and implemented.

Netbox lacks proper identification for optical interfaces used by the vast majority of access service providers.

Support for PON types on the Interfaces templates woulb be beneficial for those who deal with fiber documentation.
