### ISSUE TITLE
Edit multiple devices fails when filtered by tenant

### ISSUE THREAD

**Issue by joni1993** [netbox-community/netbox#4307]
### Environment
* Python version:  3.5.2
* NetBox version:  v2.7.9-dev

### Steps to Reproduce
1. Filter devices by tenant 
2. Select one or more elements
3. Edit selected

### Expected Behavior
Multiedit form opens

### Observed Behavior
```
<class 'ValueError'>

invalid literal for int() with base 10: 'tenant-slug-you-filtered-for'
```

Probably related to: https://github.com/netbox-community/netbox/issues/3292, https://github.com/netbox-community/netbox/commit/653770ede90f9eaeabbb2f2b769b2b7bd0cba75a

**Comment by jeremystretch** [comment]
>  v2.7.9-dev

Please update your issue to reference a current stable release.

**Comment by joni1993** [comment]
Indeed it does not happen on 2.7.8, sorry for bringing this issue up
