### ISSUE TITLE
Manufacturers Service Contract form

### ISSUE THREAD

**Issue by saneksun** [netbox-community/netbox#4314]
### Environment
* Python version:  Python 3.6.9
* NetBox version:  2.7.8

### Proposed Functionality
Hello, 
I think it will be nice to have a form where will be possible to store the following information about manufacturers support service (like Netbox has for Providers):
1. Agreement/contract #
2. End-user name
3. Contract start-date
4. Contract end-date
5. Contact information

Additionally it would be nice to have possibility to attach a pdf file!

### Use Case

This feature could help to store a global support contract information (per each vendor) in one place that will make easy to use Netbox as a  full inventory system.

**Comment by jeremystretch** [comment]
This is similar to #182 and would be out of scope for a core NetBox feature, unfortunately.
