### ISSUE TITLE
one VIP for more servers feature request

### ISSUE THREAD

**Issue by bybai** [netbox-community/netbox#4316]
### Environment
* Python version:  3.6.9
* NetBox version:  3.6

### Proposed Functionality
I found one IP is only for one device. But I want to add VIP for 2 devices. How can I to that?
I think in lots cases: VIP is used common, and one VIP is for 2 devices.

### Use Case
In HA situation, 2 servers share one VIP.

**Comment by DanSheps** [comment]
Thank you for your interest in NetBox. GitHub issues are intended for reporting reproducible bugs and requesting features, and must be submitted using one of the templates provided [here](https://github.com/digitalocean/netbox/issues/new/choose). For general discussion, questions, or assistance with installation issues, please post to our [mailing list](https://groups.google.com/forum/#!forum/netbox-discuss) instead.

**Comment by bybai** [comment]
@DanSheps  I can not open your mailing list in my country, could you provider another way to access mailing list?
