### ISSUE TITLE
Data representation in yang format

### ISSUE THREAD

**Issue by misch42** [netbox-community/netbox#4318]
### Environment
* Python version:  3
* NetBox version:  2.7.3

### Proposed Functionality
It would be rather cool to have data representation in the API in a format given by the YANG modeling. i.e. the interfaces would follow the RFC 8343 model.

With that data representation the data from netbox could directly used to configure the lasted deivce models of the big vendors.

### Use Case

USe data from netbox directly to configure devices independent from the vendor.

At the moment we have to use ansbile or saltstack to configure devices according to their vendor. Also an ansible playbook configuring switch interfaces is quite large.

So, besides the normal data repesentation in the API, you could perhaps add a switch like (?format=<yang|netbox> to choose which form to output.

### Database Changes

No.

### External Dependencies
No.

**Comment by jeremystretch** [comment]
Sorry, this is way too big an undertaking to consider at this time. Maybe we can revisit it in the future.
