### ISSUE TITLE
Editing termination sides of a cable

### ISSUE THREAD

**Issue by Yentel** [netbox-community/netbox#4319]
### Environment
* Python version:  irrelevant
* NetBox version:  2.7.3

### Proposed Functionality
When editing a cable, you are only able to edit the cable properties (cable type, cable color, cable length). However, once you've created a cable between device A port A and device B port B, you are not able to edit these terminations.

When you want to move one side of the cable to a different port, or a different device, you have to remove and re-create the cable.

### Use Case
Editing existing cables that are moved to a different port or device

### Database Changes
None, front-end addition

### External Dependencies
None

**Comment by hSaria** [comment]
I don't think you're supposed to be able to modify a cable's endpoint (see https://github.com/netbox-community/netbox/issues/2994#issuecomment-480928474).

**Comment by Yentel** [comment]
So, you never move a cable on a switch from port 1 to port 2? ;-)

**Comment by hSaria** [comment]
In the read world, you do. In NetBox (as per https://github.com/netbox-community/netbox/issues/2994#issuecomment-480928474):
> the cable should be deleted and a new one created with the desired endpoints.

**Comment by Yentel** [comment]
Was just able to view the referred comment from PC. Previous reply was via mail.

However, I still stand my case that it seems like an easy fix (have not checked the logics that are going on when creating or editing a cable yet) but I don't understand why:

> This was never part of the intended workflow

**Comment by DanSheps** [comment]
> like an easy fix (have not checked the logics that are going on when creating or editing a cable yet) but I don't understand why

Certain checks and table updates happen on the backend that make this a not ideal workflow.  It is simply easier to delete and re-create the cable.
