### ISSUE TITLE
Vertical power outlet in rack 

### ISSUE THREAD

**Issue by cosmo222** [netbox-community/netbox#4329]
### Environment
* Python version: 3.5.3
* NetBox version: 2.7.7

### Proposed Functionality
I saw that this feature was reported in ticket no. #3733 but it was wrong set as a issue, so I'm using feature template. 
My idea is to allow create vertical pdu, something like APC AP6007A, it not need to be managed but good to have sth., vertical.
I thing many of users are using vertical pdu in their rack.

**Comment by DanSheps** [comment]
There is already the required functionality:

* Create a zero-u device type
* Assign it to a rack without a face or position

It will show up as a "non-racked" device.  

If you want it to visually display on the rack diagram, I don't think we can accommodate that as there are a number of positions you can place a vertical pdu and we can't model them effectively without severely distorting the rack diagram.  The same reasoning applies to why we don't model the vertical cable management or other features of a cabinet.
