### ISSUE TITLE
Display error message when CSS doesn't load

### ISSUE THREAD

**Issue by jeremystretch** [netbox-community/netbox#4332]
### Environment
* Python version: 3.6.9
* NetBox version: 2.7.9

### Proposed Functionality
Display an error message on the home page when static resources (CSS, JS, etc.) don't load. I haven't worked out yet specifically how we might implement this, just wanted to get the ball rolling.

### Use Case
We've seen a number of issues where people have trouble serving static files once NetBox has installed. Although this should work without issue if the installation instructions are followed, there may be exceptions in specific installation environments that are throwing people off. Presenting a user-friendly error message along with some common issues to check would greatly expedite the troubleshooting process.

### Database Changes
None

### External Dependencies
Probably none.

**Comment by tb-killa** [comment]
Maybe something like this?

`
<script type="text/javascript">
if (typeof jQuery == 'undefined') {
	alert('jQuery is not loaded');
}
</script>
`
Maybe some sort of redirect to documentation website for fix this issue could be added too.

**Comment by jeremystretch** [comment]
I ended up just using `onerror` on the CSS/JS inclusions to force a redirect to a new view:

![netbox_media_failure](https://user-images.githubusercontent.com/13487278/76250178-2dc8e100-621b-11ea-8970-64e6ccfea040.png)
