### ISSUE TITLE
Hide Tags Option when viewing interfaces

### ISSUE THREAD

**Issue by darcynz** [netbox-community/netbox#4341]
### Environment
* Python version:  
* NetBox version:  

### Proposed Functionality
When viewing interfaces on a device page, there is a button (similar to hide IPs), that hides tags listed under each of the interfaces.

### Use Case
Use case is to present a cleaner view to the user when viewing  a device. There maybe other ways to solve this, but currently it is quite clutter at times depending upon how many tags are associated with an interfaces.

We would not want to remove interface tags from the view entirely but if they could be hidden that would be one way to improve presentation to the user.

### Database Changes
None

### External Dependencies
none

**Comment by darcynz** [comment]
Predict this is Blocked by #4193.

**Comment by jeremystretch** [comment]
Let's wait and see how #4193 turns out before we open any more feature requests that may or may not be needed after its implementation.
