### ISSUE TITLE
Add .env Support to Manage Script and WSGI Application Module

### ISSUE THREAD

**Issue by dstarner** [netbox-community/netbox#4344]
### Environment
* Python version:  3.7
* NetBox version:  2.7.10

### Proposed Functionality

Add automatic support for reading from a `.env` file, if present in the root directory of the project. Most likely using the [`python-dotenv`](https://github.com/theskumar/python-dotenv) module.

### Use Case

This would make it much easier to develop and test locally as it provides a simple, top-level interface that manages all the available configuration. `.env` files are easier to add quick overrides than in the nested `netbox/configuration.py` file and I prefer using it over going into the django settings so that I can have one consistent `configuration.py` file that just reads from the environment, instead of needing different versions for different connection variations.

### Database Changes

None!

### External Dependencies
https://github.com/theskumar/python-dotenv would be added to assist in loading the environment.

**Comment by jeremystretch** [comment]
Why not just modify your `configuration.py` to read environment variables?

**Comment by dstarner** [comment]
We do that already, and thats one of the use cases for implementing this. Then a user could define values in `.env` and read them via `os.getenv` calls in the `configuration.py` file. Without reading `.env` you need to prefix each `manage.py` call or container with the list of environment variables desired.

**Comment by jeremystretch** [comment]
But you could just direct your `configuration.py` to read from a specific file.

The system we have in place for configuration is well-established and IMO plenty flexible. I'd rather not commit resources to implementing, documenting, and testing an abstraction layer around it, particularly if it is of little value to regular users.
