### ISSUE TITLE
LLDP Neighbors not populating for FlexFabric devices

### ISSUE THREAD

**Issue by Joneees** [netbox-community/netbox#4345]
Using this napalm community library: https://github.com/firefly-serenity/napalm-flexfabric

REST API shows the data correctly:
![image](https://user-images.githubusercontent.com/22350850/76434686-a9af5e80-63be-11ea-9304-12c537dc4fa9.png)

![image](https://user-images.githubusercontent.com/22350850/76435061-365a1c80-63bf-11ea-8a6f-2a7f3c98cd4e.png)

LLDP Neighbors loads for ~20-30 seconds, then nothing. I have tried renaming the Interface to anything that could work but nope.
![image](https://user-images.githubusercontent.com/22350850/76434821-dc595700-63be-11ea-8967-95882909abb5.png)

Other models such as ArubaOS and provision work just fine

**Comment by jeremystretch** [comment]
None of your interfaces in NetBox are named to match the interfaces being reported by the device. There should be no guesswork involved here, as you can see from the API output what the names should be:

* `GE1/0/6`
* `GE1/0/18`
* `XGE1/0/25`

**Comment by Joneees** [comment]
Same thing happens
![image](https://user-images.githubusercontent.com/22350850/76505740-a1a0fe80-6452-11ea-8dc3-d6ad0763a1a8.png)

**Comment by kobayashi** [comment]
LLDP Neighbors Tab uses `get_lldp_neighbors_detail` to display remote device connectoins.
Could you share the result of `get_lldp_neighbors_detail`?

**Comment by Joneees** [comment]
Output of that command is empty.. So it looks like the that napalm library is lacking that function.
Will be closing this since it's the driver's fault.
