### ISSUE TITLE
Revamp process for decrypting secrets

### ISSUE THREAD

**Issue by jeremystretch** [netbox-community/netbox#4346]
### Proposed Changes
We need to revisit the current process of encrypting and decrypting secrets in NetBox. Ideally, we should allow the user to retrieve decrypted data by passing a single string, similar to the session key in the current process.

### Justification
Requiring the transfer of a complete RSA key is unwieldy, error-prone, and may be confusing to the user.

**Comment by jeremystretch** [comment]
I was a bit eager in tagging this for v2.10. This should really include a firm proposal for the changes to be made before we can assign it a milestone.

**Comment by jeremystretch** [comment]
Marking this as blocked, as we're currently investigating the feasibility of moving the secrets app to a plugin.

**Comment by DanSheps** [comment]
Blocked by: #5278

**Comment by jeremystretch** [comment]
Going to go ahead and close this as secrets is definitely being split out into a plugin.
