### ISSUE TITLE
Add Custom Links to Interfaces

### ISSUE THREAD

**Issue by darcynz** [netbox-community/netbox#4352]
### Environment
* Python version:  3.7 
* NetBox version: 2.7.8 

### Proposed Functionality
Extend custom links so that they can appear on interfaces.

### Use Case
1. Being able to click to other tools to provide information about the interface, eg Utilisation, Errors, Confirm config etc.
2. Link to Scripts to implement automation for the interface. EG update Interface Description on Device.

### Database Changes
none

### External Dependencies
None

**Comment by minitriga** [comment]
I have needed this in the past. Could see this being handy for multiple people if they have external systems that could be easily linked to. I have created a PR for this.

**Comment by jeremystretch** [comment]
Closing this until we standardize on views for all device components, probably under #4116.
