### ISSUE TITLE
Custome fields on manufacturers

### ISSUE THREAD

**Issue by kafeinnet** [netbox-community/netbox#4355]
### Environment
* Python version:  3.7
* NetBox version:  2.7.9

### Proposed Functionality
Could you allow custom fields for manufacturers. 

### Use Case
Here are some examples of custom fields I could add :
* **Support website** with an URL to the support site of the manufacturer,
* **Support contact** (same reason),
* **Internal reference** allowing to link to our ERP

**Comment by jeremystretch** [comment]
We are not currently accepting requests for the extension of custom fields. Please see the wiki: https://github.com/netbox-community/netbox/wiki/Frequently-Asked-Questions#can-we-add-custom-fields-to-more-models
