### ISSUE TITLE
Add 'brief' and 'exclude' to Swagger Documentation

### ISSUE THREAD

**Issue by dstarner** [netbox-community/netbox#4356]
### Change Type
[X] Addition
[ ] Correction
[ ] Deprecation
[ ] Cleanup (formatting, typos, etc.)

### Area
[ ] Installation instructions
[ ] Configuration parameters
[ ] Functionality/features
[X] REST API
[ ] Administration/development
[ ] Other

### Proposed Changes

Add the `brief` and `exclude` parameters to the Swagger API for appropriate routes such as list devices and get device so that they can be used by Swagger clients. They should be included in the same manner that the `q` parameter is.

**Comment by kobayashi** [comment]
Is this the same as #4357?

**Comment by dstarner** [comment]
No, this is to add documentation on it, since neither variables are present in the Swagger documentation

**Comment by dstarner** [comment]
@kobayashi / @jeremystretch is this something that can be approved so that I can create a PR for it?

**Comment by dstarner** [comment]
Anything on this?
