### ISSUE TITLE
Setting to Return Brief API Responses by Default

### ISSUE THREAD

**Issue by dstarner** [netbox-community/netbox#4357]
### Environment
* Python version:  3.7
* NetBox version:  2.7.10

### Proposed Functionality

Implement a setting such as `REST_FRAMEWORK['DEFAULT_TO_BRIEF_RESPONSE']` (or something named better that would default list/get endpoints to return the brief response (no config_context to details other than ID, name, slug).

```python
REST_FRAMEWORK = {
    'DEFAULT_TO_BRIEF_RESPONSE': [True|False]
}
```

If this setting is `False`, then default to doing it as it happens now...Return the detailed response by default and pass `brief=true` for brevity.

If this setting is `True`, then default to returning the brief contents of the data and the caller must pass `detail=True` to get the full details.

### Use Case

In many of our use cases, API callers just want to get a list of all known devices but don't need all of the detail that adds expensive overhead to compute. And due to `brief` and `exclude` not being in the Swagger documentation (see #4356) this means that a naive Swagger client is now sitting for a long period of time as unneeded data is computed. It would be nice to default to the brief view and have the client explicitly ask for the detailed view, as this fits most of our use cases.

### Database Changes
None

### External Dependencies
None

**Comment by jeremystretch** [comment]
One of the core tenets of an API is to be consistent, and this would lead to inconsistency. Given that the client already has the option of passing `brief` as a request parameter, I do not see value in this.
