### ISSUE TITLE
Rename ChoiceField "label" field to "display_name" in REST API

### ISSUE THREAD

**Issue by jeremystretch** [netbox-community/netbox#4358]
### Environment
* Python version: 3.6.9
* NetBox version: 2.7.10

### Proposed Functionality
The representation of a ChoiceField value in the REST API looks like this:

```json
"status": {
    "value": "active",
    "label": "Active",
},
```

The `value` field indicates the "raw" database value, and the `label` field conveys a human-friendly string for display to the user. This issue proposes renaming the `label` field to `display_name`:

```json
"status": {
    "value": "active",
    "display_name": "Active",
},
```

If approved, we'll continue to send both the `label` and `display_name` fields with equivalent values for at least the duration of the NetBox v2.8 release to maintain backward-compatibility.

### Use Case
`display_name` is more canonical to Django, and OpenAPI introspection already assumes (incorrectly) that a `display_name` field is present in choice representations.

### Database Changes
None

### External Dependencies
None

**Comment by dstarner** [comment]
Don't the new enumeration types use `label` though? Isn't this becoming more of a standard? I feel like either way is fine, since `display_name` is the older way and `label` is the newer way.

**Comment by jeremystretch** [comment]
If that's the case I'm happy to stick with `label`, just want to the introspection to be consistent.

**Comment by jeremystretch** [comment]
We'll stick with `label`.
