### ISSUE TITLE
Some NullBooleanFields Are Documented as Integers

### ISSUE THREAD

**Issue by dstarner** [netbox-community/netbox#4361]
### Change Type
[ ] Addition
[X] Correction
[ ] Deprecation
[ ] Cleanup (formatting, typos, etc.)

### Area
[ ] Installation instructions
[ ] Configuration parameters
[ ] Functionality/features
[X] REST API
[ ] Administration/development
[ ] Other

### Proposed Changes
Im not sure if this is a NetBox or lower issue, maybe in [drf-yasg](https://github.com/axnsan12/drf-yasg/), but the Swagger documentation is listing certain `NullBooleanField`s as integers. This is causing issues when it comes to generation swagger clients because then it tries to marshal a boolean into an `int` variable, which inevitably explodes. These should be listed as a nullable boolean.

<img width="667" alt="Screen Shot 2020-03-12 at 1 23 16 PM" src="https://user-images.githubusercontent.com/10478871/76548397-082f1800-6465-11ea-88f2-e5c93495f64c.png">

**Comment by kobayashi** [comment]
Could you let us know which exact fields should be `NullBooleanFields`?

**Comment by dstarner** [comment]
Sorry @kobayashi I didn't see your comment. It appears to be anything that extends from [`ConnectedEndpointSerializer`](https://github.com/netbox-community/netbox/blob/62efe0621f710310f9bceb46fd6d27b0d57bfb3c/netbox/dcim/api/serializers.py#L29)

**Comment by dstarner** [comment]
Also I should mention that I notice this on the associated `connection_status` field

**Comment by kobayashi** [comment]
Thanks to let us know.
I found this is set in the if statement.

https://github.com/netbox-community/netbox/blob/e04a5dc81fc41769069609e992699dffe4a3d79f/netbox/utilities/custom_inspectors.py#L95-L97

`isinstance(bool, int)` handles bool as int because `bool` is subclass of `int`.

```
>>> isinstance(False, int)
True
>>> isinstance(True, int)
True
```

Is there much better way than this? :thinking: 

```
if  not isinstance(choice_value[0], bool) and isinstance(choice_value[0], int):
    # Change value_schema for IPAddressFamilyChoices, RackWidthChoices
    value_schema = openapi.Schema(type=openapi.TYPE_INTEGER, enum=choice_value)
```
