### ISSUE TITLE
Standardize rack reservation creation URL

### ISSUE THREAD

**Issue by jeremystretch** [netbox-community/netbox#4362]
### Proposed Changes
Change the URL for creating new RackReservations to match the standard form for all models; from

```
/dcim/racks/<id>/reservations/add/
```

to

```
/dcim/rack-reservations/add/?rack_id=<id>
```

### Justification
This provides a more consistent URL scheme and allows us to include the view using our stock test case without modifications. It also makes for a slightly cleaner user experience.

**Comment by mtinberg** [comment]
I'm not sure how to report this but the URL change to rack.html is typo'd, the '&' should be '?' the current URls get "Page Not Found" errors if you try to edit or delete a Rack Reservation from the Rack page.

`diff --git a/netbox/templates/dcim/rack.html b/netbox/templates/dcim/rack.html
index 756f9619..8bfac85d 100644
--- a/netbox/templates/dcim/rack.html
+++ b/netbox/templates/dcim/rack.html
@@ -289,12 +289,12 @@
                             </td>
                             <td class="text-right noprint">
                                 {% if perms.dcim.change_rackreservation %}
-                                    <a href="{% url 'dcim:rackreservation_edit' pk=resv.pk %}&return_url={{ rack.get_absolute_url }}" class="btn btn-warning btn-xs" title="Edit reservation">
+                                    <a href="{% url 'dcim:rackreservation_edit' pk=resv.pk %}?return_url={{ rack.get_absolute_url }}" class="btn btn-warning btn-xs" title="Edit reservation">
                                         <i class="glyphicon glyphicon-pencil" aria-hidden="true"></i>
                                     </a>
                                 {% endif %}
                                 {% if perms.dcim.delete_rackreservation %}
-                                    <a href="{% url 'dcim:rackreservation_delete' pk=resv.pk %}&return_url={{ rack.get_absolute_url }}" class="btn btn-danger btn-xs" title="Delete reservation">
+                                    <a href="{% url 'dcim:rackreservation_delete' pk=resv.pk %}?return_url={{ rack.get_absolute_url }}" class="btn btn-danger btn-xs" title="Delete reservation">
                                         <i class="glyphicon glyphicon-trash" aria-hidden="true"></i>
                                     </a>
                                 {% endif %}
@@ -307,7 +307,7 @@
             {% endif %}
             {% if perms.dcim.add_rackreservation %}
                 <div class="panel-footer text-right noprint">
-                    <a href="{% url 'dcim:rackreservation_add' %}?rack={{ rack.pk }}&return_url={{ rack.get_absolute_url }}" class="btn btn-primary btn-xs">
+                    <a href="{% url 'dcim:rackreservation_add' %}?rack={{ rack.pk }}?return_url={{ rack.get_absolute_url }}" class="btn btn-primary btn-xs">
                         <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
                         Add a reservation
                     </a>
`
