### ISSUE TITLE
Bulk IP edit - 'str' object has no attribute '_meta'

### ISSUE THREAD

**Issue by jamiek23** [netbox-community/netbox#4365]
### Environment
* Python version:  3.6.9 (with VirtualEnv 15.1.0)
* NetBox version:  2.7.10
* Operating system: Ubuntu 18.04.4 LTS

### Steps to Reproduce
1. Log in to netbox, if necessary.
2. Navigate to https://netbox.hostname/ipam/ip-addresses/bulk-add/
3. Observe error.

### Expected Behavior
It should display the bulk IP edit page.

### Observed Behavior
A server error is returned. Exception is included below:
```
<class 'AttributeError'>

'str' object has no attribute '_meta'
```
Screenshot:
![image](https://user-images.githubusercontent.com/1812841/76619220-450d1480-6522-11ea-8f62-68bf9cf88820.png)

And finally here's a traceback from debug mode: [traceback.log](https://github.com/netbox-community/netbox/files/4329457/traceback.log)

**Comment by jeremystretch** [comment]
As a temporary workaround until the next release, you can set `DOCS_ROOT = None` in `configuration.py` to avoid the exception.
