### ISSUE TITLE
Custom/Additional Interfaces

### ISSUE THREAD

**Issue by mddeff** [netbox-community/netbox#4371]
I know this issue has been addressed in #2865, #2882, #97, and many others I'm sure, but I wanted to throw my 2c in on this given those tickets are closed.

I have a need to track RF cables in my environment.  90% of my sites have primary or secondary WAN connectivity via SatCom or 4G connectivity which employ custom antennas.  Many of my sites have VHF/UHF or microwave point to point IP radios which also use custom antennas.  Finally, most of my sites have GPS for precise NTP and timing.  Again, more RF cabling.

I think this brings up the need for for user-defined interfaces and cabling types.  I know @jeremystretch has cited scope creep and performance degradation as specific reasons to not do a user-defined list of cable and interface types.  At least as it relates performance, I'd be interested to see how much performance actually degrades as users start to define their own interfaces.  

I'm sure many users here would be willing to accept some level of performance degradation in favor of having one solution to track their entire infrastructure.  Even if you had custom interfaces disabled out of the box and a giant "Caveat Emptor" performance impact banner when they enable it.  I'd happily accept that risk (or scale out my NetBox deployment appropriately).

The litmus test in all of the tickets seems to be "is this an IP interface".  In the use cases of SatCom, 4G, PtP VHF/UHF, and PtP Microwave, the RF interfaces on the Modems all have IPs assigned to them, and encapsulate and transport IP traffic in one way or another.  The only difference are the layer 1 and 2 standards they abide by.

## Barring that
I'd like to have RF/Coax cabling and appropriate physical interfaces added.  Happy to attempt a pull request as appropriate. I can also provide a list of cable and connector types if accepted.

Or maybe this should just be a plugin. as suggested in #3351

Either way, thank you all for making a fantastic open source product and continuously supporting it.  Your work doesn't go unnoticed.  Thanks!

**Comment by lampwins** [comment]
This issue has been closed as it does not conform to one of the [provided templates](https://github.com/digitalocean/netbox/issues/new/choose) as required by the [contributing guide](https://github.com/digitalocean/netbox/blob/master/CONTRIBUTING.md). If you'd like to request that your issue be re-opened, please first update the content so that it matches the appropriate template (this may require rewriting your issue entirely).

**Comment by mddeff** [comment]
Fixed formatting.  Sorry, I found the formatting template after I had submitted the issue.

**Comment by mddeff** [comment]
@lampwins  I addressed the formatting issue, can we re-open this for discussion?

**Comment by mddeff** [comment]
This issue is less about tracking the wireless link itself (which, is also important), but tracking the cabling between the antenna and the modem/transceiver.
