### ISSUE TITLE
Generate cabling diagrams

### ISSUE THREAD

**Issue by mddeff** [netbox-community/netbox#4372]
### Environment
Docker-latest

### Proposed Functionality
The ability to generate SVGs that are block diagrams of physical cabling for a specific device.
The user should be able to:
- have specific interface types shown or hidden in the diagram (show network connections but hide power and console)
-  the diagram should show the device names, cable identifier, cable properties, connector properties.  Again, user selectable what fields/properties are shown.

### Use Case
I need to provide physical cabling diagrams to technicians so they can build or re-cable racks or when we want to red line a drawing when undocumented changes are made and we dont have access to netdata.  See attached for example, sorry for the crudity.  This would be if you hit generate on the switch1 device and selected network cables.

![Screenshot from 2020-03-14 02-00-58](https://user-images.githubusercontent.com/16808640/76676247-ee422200-6597-11ea-8c5d-949c566950d8.png)
### External Dependencies
netbox can already generate SVGs for the rack elevations, I'm not sure if there would be others.

**Comment by tb-killa** [comment]
Like the idea, sounds more like you should rename the FR to "allow Cable Trace render as svg"

**Comment by jeremystretch** [comment]
Out of scope for NetBox. We purposely removed the topology diagram function in v2.7. I'm sure we'll seem plugins for this sort of thing once v2.8 launches.

**Comment by kevinpm** [comment]
There was a patch providing this functionality in the past. I forked it and made it work with the current netbox version (2.7.3) https://github.com/kevinpm/netbox_topology
