### ISSUE TITLE
Getting prefixes by vrf name fails

### ISSUE THREAD

**Issue by Dimaqa** [netbox-community/netbox#4378]
### Environment

Python version: 3.6.9
NetBox version: 2.7.6, same behavior on 2.7.9-dev

### Steps to Reproduce

GET /api/ipam/prefixes/?vrf=FOR-TESTS

Probably its a swagger bug and you cant really get prefixes by vrf name directrly (There are two fields: vrf and vrf_id), because if you search through netbox unterface, it replaces vrf name with id in query

### Observed Behavior

400 Bad Request: {'vrf': ['Select a valid choice. TEST-VRF is not one of the available choices.']}

**Comment by jeremystretch** [comment]
> NetBox version: develop

We do not accept bug reports for anything other than a recent stable release. Please attempt to reproduce the behavior on a current release and update your issue accordingly.

**Comment by Dimaqa** [comment]
Same behavior on 2.7.6 and 2.7.9-dev

**Comment by Dimaqa** [comment]
Getting prefixes by vrf name makes things awkward if we have 2 vrf with the same name. So maybe you should just delete this field from swagger. Also rename vrf to vrf_id on creation would be nice, because this naming breaks my mind every time

**Comment by jeremystretch** [comment]
The ` vrf` filter references VRF objects buy RD, not by name.

**Comment by Dimaqa** [comment]
Thank you! But but thats really strange way to name RD, since vrf is vrf_id on creation (POST).

**Comment by jeremystretch** [comment]
`vrf_id` the VRF's primary key; `vrf` is its RD. This is analogous to `site` referencing a site's slug and `site_id` its PK.
