### ISSUE TITLE
Change RQ worker status page URL to be generic

### ISSUE THREAD

**Issue by lampwins** [netbox-community/netbox#4386]
### Environment
* Python version:  3.7
* NetBox version:  2.7.10

### Proposed Functionality
As a part of implementing #738 we turned the rq background processing into a more generic solution, rather than being specific to webhooks. As such, we should probably modify the admin status url for the rq-worker urls to be more generic.

### Use Case
Today the route is `admin/webhook-backend-status/`. I propose changing this to `admin/background-worker-status/`. 

### Database Changes
None

### External Dependencies
None

**Comment by jeremystretch** [comment]
Might tack on a redirect for the old URL for a bit, too.
