### ISSUE TITLE
LLDP interface showing with quotes

### ISSUE THREAD

**Issue by inetman28** [netbox-community/netbox#4390]
### Environment
* Python version:  3.6.8
* NetBox version:  2.7.8
* Napalm version: 2.3.3

### Steps to Reproduce
1. Navigate to a device and click the "LLDP Neighbors" tab

### Expected Behavior
I must see green line if configured interface == lldp interface

### Observed Behavior

Because LLDP interface show with quotes then str did not match, for example see below screen
![image](https://user-images.githubusercontent.com/45913745/77159190-f0374400-6ab5-11ea-8160-4409a40c52d6.png)

**Comment by jeremystretch** [comment]
What does the raw API response look like? (Go to `http://netbox/api/dcim/devices/<id>/napalm/?method=get_lldp_neighbors_detail` in your browser see the response.)

**Comment by inetman28** [comment]
remote_port with double quotes )
```
         "Ethernet49/1": [
            {
                "parent_interface": "Ethernet49/1",
                "remote_port": "\"Ethernet49/1\"",
                "remote_port_description": "SOMETHING DESCRIPTION",
                "remote_system_name": "DC1-SW4",
                "remote_system_description": "Arista Networks EOS version 4.22.3M running on an Arista Networks DCS-7060SX2-48YC6",
                "remote_chassis_id": "98:5D:82:62:BD:ВВ",
                "remote_system_capab": [
                    "bridge",
                    "router"
                ],
                "remote_system_enable_capab": [
                    "bridge",
                    "router"
                ]
            }
        ],
```

**Comment by jeremystretch** [comment]
That makes sense, then. NetBox is merely a proxy for the data returned by the NAPALM driver. Seems like a bug in the NAPALM driver to me, though it might also be something oddly platform-specific. In any case, it's not something we can fix in NetBox unfortunately.

**Comment by inetman28** [comment]
thanks you. I opened new issue in napalm repo:
https://github.com/napalm-automation/napalm/issues/1153

**Comment by asergeant01** [comment]
I have it that this will be addressed by Arista.....

> LLDP thing is fixed under Bug 480042 so it should start making it to releases in the next few weeks
> One caveat though is that to preserve existing behaviour (to stop changes from potentially breaking existing automation deployments) we are adding "interfaceId_v2": "Ethernet1  rather then changing interfaceId
