### ISSUE TITLE
Extend installation docs to include HTTPS configuration

### ISSUE THREAD

**Issue by jeremystretch** [netbox-community/netbox#4391]
### Change Type
[x] Addition
[ ] Correction
[ ] Deprecation
[ ] Cleanup (formatting, typos, etc.)

### Area
[x] Installation instructions
[ ] Configuration parameters
[ ] Functionality/features
[ ] REST API
[ ] Administration/development
[ ] Other

### Proposed Changes
Extend the reference configurations for nginx and Apache to include HTTPS setup. This doesn't really pertain to NetBox specifically, but a few people have reported problems relating to CSRF validation when HTTPS is in use, so it may help to provide a correct configuration for reference.

**Comment by ech1965** [comment]
Great Idea.

May I request to cover the configuration where the reverse proxy is in DMZ ( https)  proxying a netbox instance running https in a private lan

THANKS
EC
