### ISSUE TITLE
Wrong type in swagger docs on field count_ipaddresses of interface

### ISSUE THREAD

**Issue by mraerino** [netbox-community/netbox#4395]
### Environment
* Python version: 3.7.5
* NetBox version: 2.7.10

### Steps to Reproduce
1. Start a fresh netbox installation (e.g. https://netboxdemo.com/)
2. Go to the swagger docs (e.g. https://netboxdemo.com/api/docs/)
3. Go to the definition for `/dcim/interfaces/{id}/`
4. See that the field `count_ipaddresses` has type `string`

### Expected Behavior
Since the json from the API response returns an unquoted number, the type needs to be `integer`.

### Observed Behavior
The field has type `string` which causes deserialisation in some client libraries to fail.
E.g. https://github.com/netbox-community/go-netbox/pull/67

**Comment by stefanmcshane** [comment]
@DanSheps Can we get an update on accepting this? 
Blocking use of the Go client library since 2.7 update for us

If not, is there a better process we can use for updating types as it breaks statically typed client libraries

Thanks!

**Comment by stefanmcshane** [comment]
@DanSheps Any update on this?
