### ISSUE TITLE
webhook jinja2 does not work

### ISSUE THREAD

**Issue by andershagman** [netbox-community/netbox#4405]
### Environment
* Python version:  3.6.9
* NetBox version:  2.7.8

### Steps to Reproduce
0. Have a working webhook receiver.

1. Make a webhook with a jinja2 body that trigger create, modify or delete IP addresses.
Example body for extract gateway and mask part:
{
   "data": {
     "gateway": "{{ data.address.network + 1 }}",
     "metmask": "{{ data.address.netmask }}"
   }
}

2. activate the webbook by adding an IP address.
create -> 10.1.10.3/24

3. Observe the sent data by using tshark.

### Expected Behavior
{
   "data": {
     "network": "10.1.10.1",
     "netmask": "255.255.255.0"
   }
}

### Observed Behavior
No key values are sent.
{
   "data": {
     "network": "",
     "netmask": ""
   }
}

**Comment by jeremystretch** [comment]
`data.address` is a string representation if the IPAddress' `address` field, not a netaddr object, so it doesn't have those methods available.
