### ISSUE TITLE
Need help

### ISSUE THREAD

**Issue by fireman0865** [netbox-community/netbox#4409]
Hi all particulary to Jeremy ,
I would like that you help me because i am using Netbox but i just want to deblok it that devices can inherit from devices types even when device types is modified .
Cordially

**Comment by jeremystretch** [comment]
Thank you for your interest in NetBox. GitHub issues are intended for reporting reproducible bugs and requesting features, and must be submitted using one of the templates provided [here](https://github.com/netbox-community/netbox/issues/new/choose). For general discussion, questions, or assistance with installation issues, please post to our [mailing list](https://groups.google.com/forum/#!forum/netbox-discuss) instead.

**Comment by fireman0865** [comment]
Hi jeremy ,how are you ? My name is salman and i am using netbox .Can you
help le please do that device inherit from device types after changement
.Thanks you in advance

Le jeu. 26 mar. 2020 à 14:29, Jeremy Stretch <notifications@github.com> a
écrit :
