### ISSUE TITLE
Increase the maximum tenant and tenant group name length.

### ISSUE THREAD

**Issue by ebusto** [netbox-community/netbox#4411]
### Environment
* Python version:  3.6.9
* NetBox version:  2.7.10

### Proposed Functionality
Increase max_length for tenant and tenant group names to 128.

### Use Case
Large organizations often have descriptive team names which exceed the current length limit. I'm frequently bumping up against the current limit, and there is a [thread](https://groups.google.com/forum/#!topic/netbox-discuss/tFW5NRM67uY) on the netbox-discuss mailing list indicating I'm not alone.

### Database Changes
Two changes in tenancy/models.py, along with corresponding migrations. Trivial.

### External Dependencies
None.

**Comment by jeremystretch** [comment]
Covered by #4416

**Comment by dmn1n** [comment]
Can we manually modify the character length ? any documentation on this will be helpful.
