### ISSUE TITLE
Tenants should be ordered only by name.

### ISSUE THREAD

**Issue by ebusto** [netbox-community/netbox#4413]
### Environment
* Python version:  3.6.9 
* NetBox version:  2.7.10

### Proposed Functionality
Rather than order tenants by `['group', 'name']`, they should simply be ordered by `['name']`.

### Use Case
Given the way tenants show up in UI elements, such as the tenant table and form inputs, they appear essentially unordered unless a tenant group is selected first.

It would be cleaner if they were simply ordered by `name`.

### Database Changes
A simple model change.

### External Dependencies
None

**Comment by jeremystretch** [comment]
> they appear essentially unordered unless a tenant group is selected first.

They are ordered by group by default, which makes far more sense in most use cases. If you want to order them by name, you have the option of doing so. This ordering has been in place for years, and I see no reason to change it.

**Comment by ebusto** [comment]
I suspect you're referring to the list of tenants, presented in table form. Sure, I could click on the "name" column to reorder, but typically data presented in tabular format is ordered by the first column, in ascending order, by default. Not the second column.

There are some UI elements where ordering tenants by name is not possible, such as when performing bulk updates of VMs and devices. Filtering by tenant group in the bulk update form is not possible, so you're stuck hunting through an unordered list.

For other forms that allow tenant filtering by tenant group, tenants should still be displayed in order by default. They'll still be ordered when the tenant list is revised if a tenant group is selected.

I'm simply arguing for NetBox to adhere to UI best practices. Just because it has worked the way it does for years isn't a valid reason to dismiss a suggestion. I've definitely become blind to warts in software I've been hacking away at for years; it happens.

**Comment by jeremystretch** [comment]
> I'm simply arguing for NetBox to adhere to UI best practices.

It's not best practice, it's merely your opinion. For my use cases, and I suspect many others, it would be extremely irritating to receive by default a list intermingling customers, internal organizations, and miscellaneous other groups.

Once #3294 is in place, you might be able to save your preferred ordering. But we're not going to change the database-level ordering that is currently in place.
