### ISSUE TITLE
Standardize attributes and views for all primary models

### ISSUE THREAD

**Issue by jeremystretch** [netbox-community/netbox#4416]
### Proposed Changes
Standardize common attributes and views for all [primary models](https://docs.google.com/spreadsheets/d/1UFoJHwCvpmPqTN6ARS977NFB5BLDvBiKlyIvlZpvUcg/edit#gid=0). This work has been underway sporadically for the past few months, but needs to be formalized.

### Justification
Establishes consistency for all models, and simplifies development and testing.

**Comment by xkilian** [comment]
Has the normalisation process considered adding the Status attribute for a cable? I saw that custom fields where flagged as missing and aimed to be normalised, but there was no indication for Status. I can open an issue if this was not already planned.

**Comment by jeremystretch** [comment]
@xkilian Off-topic for this issue.

**Comment by jeremystretch** [comment]
I'm going to consider this issue closed at this point. There remains a lot of work to be done around different models, however it's not practical to continue tracking it all under a single issue. This may be a good use case for GitHub projects.
