### ISSUE TITLE
Can't create racks in 2.7.10

### ISSUE THREAD

**Issue by jacekf** [netbox-community/netbox#4420]
### Environment
* Python version:  3.6.3
* NetBox version:  2.7.10

After upgrading to 2.7.10 most things works fine besides racks. I can't add racks or enter API for racks because I got the following error:

 The complete exception is provided below:

<class 'django.db.utils.DataError'>

invalid input syntax for integer: "available"
LINE 1: ... 'Test_Rack', 'Test_Rack', NULL, 158, NULL, NULL, 'available...

### Steps to Reproduce
1. Try to create rack using 2.7.10
2.
3.

### Expected Behavior
I expect a rack to be successfully created

### Observed Behavior
Error 500

**Comment by jeremystretch** [comment]
I'm not able to reproduce this. The exception suggests a problem with your database; likely a missing migration. Please consider posting to the [mailing list](https://groups.google.com/forum/#!forum/netbox-discuss) for assistance.
