### ISSUE TITLE
Allow Change of Default For Config-Context YAML JSON toggle mode

### ISSUE THREAD

**Issue by a31amit** [netbox-community/netbox#4421]
### Environment
* Python version:  3.6 
* NetBox version:  2.7 latest 

### Proposed Functionality
Please allow a Configuration option for Default Setting Config-Context YAML JSON toggle mode.

### Use Case
This will help netbox admins and users to set the preferred mode for their userbase  

### Database Changes
None

### External Dependencies
None

**Comment by DanSheps** [comment]
Similar to #1426 and would be blocked by #3294, I can get behind this however, once #3294 is implemented.

**Comment by a31amit** [comment]
While this can be a per-user basis,  adding a new default global configuration options would also help to change global behaviors. currently, default is JSON without any option to configure in configuration.py.

**Comment by jeremystretch** [comment]
A per-user toggle for this would be sufficient. We want to avoid clogging up the global configuration with niche toggles.
