### ISSUE TITLE
/api/secrets/get-session-key without a trailing slash returns 405 Method Not Allowed

### ISSUE THREAD

**Issue by dmfigol** [netbox-community/netbox#4424]
### Environment
* Python version:  3.7.6
* NetBox version:  2.7.9

### Steps to Reproduce
1. POST `/api/secrets/get-session-key` with payload `{"private_key": "whatever"}`

### Expected Behavior
Expected to work it the same regardless if the trailing slash is there or not, like the rest of API endpoints

### Observed Behavior
Response is **405 Method Not Allowed**

**Comment by jeremystretch** [comment]
> Expected to work it the same regardless if the trailing slash is there or not, like the rest of API endpoints

Just a note: the trailing slash is always needed. Without it, a 302 redirect is returned for the correct URL.

**Comment by jeremystretch** [comment]
I'm going to close this as this is expected behavior. Per the RuntimeError exception (raised when `DEBUG` is true):

> RuntimeError: You called this URL via POST, but the URL doesn't end in a slash and you have APPEND_SLASH set. Django can't redirect to the slash URL while maintaining POST data. Change your form to point to localhost:8000/api/secrets/get-session-key/ (note the trailing slash), or set APPEND_SLASH=False in your Django settings.
