### ISSUE TITLE
Add two words to the comment for RELEASE_CHECK_TIMEOUT

### ISSUE THREAD

**Issue by nepeat** [netbox-community/netbox#4425]
### Change Type
[X] Addition
[ ] Correction
[ ] Deprecation
[ ] Cleanup (formatting, typos, etc.)

### Area
[ ] Installation instructions
[X] Configuration parameters
[ ] Functionality/features
[ ] REST API
[ ] Administration/development
[ ] Other

### Proposed Changes
Add a comment to describe the unit of RELEASE_CHECK_TIMEOUT in the configuration example file. Similar change was pushed in netbox-community/netbox-docker#263 with the same comments from the example copy and pasted.

Issue made to satisfy the Fixes requirement.

**Comment by jeremystretch** [comment]
We only accept issues for specific releases. The v2.8 documentation is still under development.
