### ISSUE TITLE
Export fields do not always match import fields.

### ISSUE THREAD

**Issue by ryanmerolle** [netbox-community/netbox#4429]
### Environment
* Python version:  3.6.9
* NetBox version:  2.7.11

### Steps to Reproduce
1. Export any sort of data type.
2. Delete associated data.
3. Import same csv/data into netbox
4. Import fails for a number of fields:
 - Any custom field is exported as the custom field's name like `field1`, but the import requires `cf_field1`
- Units such as outer_unit (racks) export outputs `in` instead of the expected `Inches`
- I will go throug some other exports to document what else does not match.

### Expected Behavior
Any export would be able to work as an import assuming the linked records are present(manufacture for example with device type).

### Observed Behavior
- Field names do not match export and import (at least for custom fields missing the `cf_`  prefix).
- Exported field values do not match allowed schema/constraints for the data model / import.

**Comment by jeremystretch** [comment]
They're not always going to match, for various reasons. This was never a design goal.
