### ISSUE TITLE
Adding a termination to a circuit is very slow when you have a large list of sites

### ISSUE THREAD

**Issue by ctrowat** [netbox-community/netbox#4430]
#4037 # Environment
* Python version:  3.7
* NetBox version:  2.7.10

We have about 14,000 sites in our netbox deployment.  When creating terminations for the A and Z sides of a circuit the page to configure these (`/circuits/circuit-terminations/<id>/edit/` or `/circuits/circuits/<id>/terminations/add/?term_side=A`) takes 4-5 seconds to load and causes the browser to hang severely on lower powered computers.  This appears to be because netbox is populating a selection control with the complete list of sites.

Compare this to the devices page (or many others) where the sites list uses lazy loading and performs extremely well.

It would greatly improve our user experience if this lazy loading was also implemented on the circuit termination configuration page.

### Steps to Reproduce
1.  Add a large number of sites to netbox (i.e. 14,000)
2.  Create a circuit
3.  Attempt to configure the A or Z side of the circuit

### Expected Behavior
The page should load quickly, and selecting a site on this page should be as performant as selecting a site on the device configuration page.

### Observed Behavior
The page itself takes (for us) 4-5 seconds to load, and trying to select a site can cause the browser to hang for upwards of 30 seconds on lower powered computers.

**Comment by jeremystretch** [comment]
This was fixed in v2.7.11 under #4374. Probably should have been added to the release notes.
