### ISSUE TITLE
Pass model object to webhook

### ISSUE THREAD

**Issue by andershagman** [netbox-community/netbox#4435]
### Environment
* Python version:  3.6.x
* NetBox version:  2.7.x

### Proposed Functionality
Change the webhook code to receive the whole model object, not just a serialized stream of json,  to be able to manipulate the data with jinja2 in the same manner as with custom links.

### Use Case
To be able to pass more correct data to a webhook receiver. Especially if the receiver can not be tampered with. 
Ex: from model ipaddress
prefix -> obj.address.network
gateway -> obj.address.network + 1
netmask -> obj.address.netmask
broadcast -> obj.address.broadcast
first address -> obj.address.network + 1
last address -> obj.address.broadcast - 1
dhcp range start -> if obj.address.size > 255 -> obj.address.network + 30
dhcp range end -> obj.address.broadcast - 1

### Database Changes
beyond my knowledge

### External Dependencies
none

**Comment by jeremystretch** [comment]
I'm not sure this is feasible, given that the model must be serialized for queuing. @lampwins do you have any ideas?

Tagging this as `needs owner` in case someone wants to volunteer to dig into it more.

**Comment by lampwins** [comment]
@jeremystretch one thing that comes to mind is to pass the content type and pk into the job and then do a query for the actual object inside the job. This is a common enough pattern and is similar to what we do today with the JobResult instances. If this is something you want to do, I can take it. It should be relatively simple.

**Comment by jeremystretch** [comment]
> query for the actual object inside the job

I don't think we can make the assumption that the object has not changed between the point in time when the job is queued and the time when it is executed. Consider bulk changes of many hundreds or thousands of objects, for instance. We need a mechanism by which we can freeze the object at the exact point in time.

**Comment by lampwins** [comment]
Yeah good point, it also doesn't work for deleted objects.
