### ISSUE TITLE
Cannot delete cable linked to PowerFeeds

### ISSUE THREAD

**Issue by coloHsq** [netbox-community/netbox#4438]
### Environment
* Python version:  3.6.7
* NetBox version: 2.7.11

### Steps to Reproduce
1. Just try to delete a cable connected to a PowerFeed.

### Expected Behavior
The cable should be deleted without problems.

### Observed Behavior
A missing attribute error is raised : 'PowerFeed' object has no attribute 'parent'.
Looking at stack trace and code, the problem seems to be caused (and confined) by a logger in cable termination trace method, as it tries to write info about the termination parent, which however does not exist for PowerFeeds.

**Comment by neilatrevains** [comment]
### **Environment**

- Python version: 3.6.9
- NetBox version: 2.7.11

### **Steps** to Reproduce and Observed Behaviour

1. Attempt to connect rack PDU power port to power feed
2. After selecting/entering all of the appropriate entries, pressing 'Connect' results in an error:

> <class 'AttributeError'>
> 
> 'PowerFeed' object has no attribute 'parent'

3. Pressing 'Home Page' and then reviewing the device shows a cable created and associated, where 'Termination A' is correct (the power port on the PDU) but 'Termination B' refers to 'Provider' and 'Circuit' - would expect this to be 'Power Panel' and 'Power Feed'.
4. In the device's 'Console / Power' section, the power port shows as 'Not connected' and pressing 'Trace' results in the same <class 'AttributeError'>.
