### ISSUE TITLE
Add comments field to ipam>prefix

### ISSUE THREAD

**Issue by The-Only-God** [netbox-community/netbox#4441]
### Environment
* Python version:  
* NetBox version:  

### Proposed Functionality
Add comments field to Prefix

### Use Case
I have development department, that create subnets in Azure. I need better notes about prefix to be stored. Description filed is only one line and not enough.

**Comment by The-Only-God** [comment]
Also other idea for me, is to add Comments field to custom fields type, if better, let me know and I will create other issue. But it's harder to develop i guess.

**Comment by jeremystretch** [comment]
Covered by #4416
