### ISSUE TITLE
Django 3.x X_FRAME_OPTIONS default changed from SAMEORIGIN to DENY breaking Rack SVG

### ISSUE THREAD

**Issue by mtinberg** [netbox-community/netbox#4442]
### Environment
* Python version:  3.6.8
* NetBox version:  develop-2.8

### Steps to Reproduce
1. Install develop-2.8 branch from lae.netbox Ansible playbook in venv with Django 3.x
2. Navigate to Rack or Rack Elevations display, embedded SVG is retrieved but does not display
3. TCPDump between HTTPD and uWSGI shows header X-Frame-Options: DENY
4. This can be fixed by adding X_FRAME_OPTIONS = "SAMEORIGIN" to settings.py

### Expected Behavior
Display embedded SVG

### Observed Behavior
Empty box where object should be

### Fix action
X_FRAME_OPTIONS = "SAMEORIGIN" in settings.py
https://docs.djangoproject.com/en/3.0/ref/settings/#std:setting-X_FRAME_OPTIONS

**Comment by jeremystretch** [comment]
We don't track bugs for branches under active development, but I've noticed this behavior and have it on my to-do list.
