### ISSUE TITLE
Facility / Provider separation 

### ISSUE THREAD

**Issue by ibivibiv** [netbox-community/netbox#4444]
### Environment
* Python version:  3.6.x
* NetBox version:  2.7.11 (changes obviously to occur in major release after this one)

### Proposed Functionality

It seems to me that the 'Facility' field on the site object is a concatenated field that is actually holding 2 things today.  I am thinking that facility is more than just an unchecked free text.  It has a name and it has details.  The one given is the provider.  I have also seen an issue for asking for GPS coords etc.  To me those are custom field candidates.  I would like to propose that Facility is more of an enumerated field referencing an actual data object albeit a small one with some decorators.  I'll work on a proper data model design for this, but for now I thought I'd raise the issue as a feature request.  I am not expecting someone else to do the work btw.  I am looking to build this out and add it in as part of the community process.

### Use Case
As a user I need to designate facilities as an element of a site.
As a user I need to clearly enumerate facilities.
As a user I need to search and designate facilities by providers
As a user I need to search and designate sites by the providers of the facilities they reside in

### Database Changes
Changes would be made to create a facility object and change the site field to be a foreign key to this new objects primary key.  The new object would get the decorators of providers and any additional custom fields.  There would also most likely be a new providers object that would be a foreign key in the facility object.

### External Dependencies
None that I can think of.

**Comment by jeremystretch** [comment]
`facility` is merely an additional free-form field provided for convenience. It does not point to any other object in NetBox. For example, some people use it to denote a secondary name for a site, such as a data center ID or alternate building code. We're not going to change this as the organizational model for sites in NetBox is already well-established.

**Comment by ibivibiv** [comment]
No worries, we were considering a companion app that will wrap NetBox and provide some much needed logistics and lifecycle management.  We can just add a locality enhancement there.  Hopefully that can get open sourced as well and then we can push it out to fill some of these things that data center inventory and operations staff do.  Tracking and searching by providers of rental facilities etc.  I can see that the core app might not want these. We can absolutely take that up then.  Thanks for the consideration though.
