### ISSUE TITLE
When querying objects via API, Netbox would return the whole list if the object doesn't have that field in its attributes.

### ISSUE THREAD

**Issue by drixo** [netbox-community/netbox#4445]
### Environment
* Python version:  3.5 
* NetBox version:  2.7.8 

I'm not sure if this is a bug or not, but anyways I wanted to give you a warning. 

I needed to remove several sites and its inventory (Racks, Devices, Cables, etc.), as this cannot be done in the UI I started working on a script to delete any objects related to the site_id via API.

So I'm basically getting lists of the different components filtering by site_id, for example for devices

https://netbox.my.local:443/api/dcim/devices/?site_id=114

then proceed to delete whatever is in the list, however I noticed that when I filter objects that doesn't have site_id in their attributes I would get the whole list of objects, like for example IP-Addressses

https://netbox.my.local:443/api/ipam/ip-addresses/?site_id=114

This would return the whole list of IPs in IPAM. which can be dangerous given that a wrong field name can make you do stuff in bulk on an undesirable group of objects. 

### Steps to Reproduce
1. curl -H "Authorization: Token **********************" -H "Accept: application/json; indent=4" https://netbox.my.local:443/api/ipam/ip-addresses/?site_id=114
2.
3.

### Expected Behavior
Should return an empty list or an error

### Observed Behavior
Returns the whole list of objects

**Comment by jeremystretch** [comment]
> however I noticed that when I filter objects that doesn't have site_id in their attributes I would get the whole list of objects, like for example IP-Addressses

`site_id` is not a valid filter for IP addresses, so it is ignored. This is expected.
