### ISSUE TITLE
Allow termination of circuits with another circuit 

### ISSUE THREAD

**Issue by lucasalvatore1** [netbox-community/netbox#4448]
### Environment
* Python version:  3.7
* NetBox version:  2.6.11

### Proposed Functionality
Allow termination of circuits with another circuit

### Use Case
The use case is for when we connect to an ISP via a 3rd party wavelength / metro connect.  It would be great if netbox could show something like:

```
my_router xe-0/0/0 > wavelength > ISP circuit
```

### Database Changes
Unknown

### External Dependencies
None

**Comment by jeremystretch** [comment]
You'd still need a cable to connect the two circuit terminations. It would look like this:

```
[ device ] [ interface ] ---- [ termination ] [ circuit ] [ termination ] ---- [ termination ] [ circuit ] [ termination ] ---- [ interface ] [ device ]
```

Validation doesn't currently allow one termination to attach to another directly, but I don't think this is a limitation of the model itself.
