### ISSUE TITLE
DeviceType not rendering in ObjectVar

### ISSUE THREAD

**Issue by rodvand** [netbox-community/netbox#4453]
### Environment
* Python version:  3.6.8
* NetBox version:  2.7.11

### Steps to Reproduce
1. Create a custom script using ObjectVar and DeviceType as queryset
```
from extras.script import Script
from dcim.models import DeviceType

class Test(Script):
    dt = ObjectVar(
        queryset = DeviceType.objects.all()
    )

def run(self, data, commit):
    pass
```
### Expected Behavior
Expected to be able to select a device type from the device type library in the dropdown menu.

### Observed Behavior
No entries showing up in the dropdown menu.

**Comment by jeremystretch** [comment]
The `APISelect` widget looks for a `name` field by default, which the DeviceType model does not have. You need to define it manually:

```python
from extras.scripts import Script, ObjectVar
from dcim.models import DeviceType
from utilities.forms import APISelect


class Test(Script):
    dt = ObjectVar(
        queryset=DeviceType.objects.all(),
        widget=APISelect(
            display_field='model'
        )
    )

    def run(self, data, commit):
        pass
```

I realize this isn't the most convenient implementation, but it is what we currently have. If you get stuck again, remember that you can always look through the NetBox source for examples of what you're trying to achieve.
