### ISSUE TITLE
<class 'ImportError'>  cannot import name 'CONNECTION_STATUS_PLANNED'

### ISSUE THREAD

**Issue by A888R** [netbox-community/netbox#4454]
### Environment
* Python version: 3.6.9
* NetBox version:  2.7.11

### Steps to Reproduce
1. Create file in _/opt/netbox/netbox/reports_ (example: https://github.com/netbox-community/netbox/blob/626513a8b20d07e6339605e2652aceaae29b8e7f/docs/additional-features/reports.md)
2. Use _from dcim.constants import CONNECTION_STATUS_PLANNED_
3. Open _/extras/reports/_

### Expected Behavior
Open list reports.

### Observed Behavior
Error:
**<class 'ImportError'> cannot import name 'CONNECTION_STATUS_PLANNED'**

**Comment by jeremystretch** [comment]
Thank you for your interest in NetBox. GitHub issues are intended for reporting reproducible bugs and requesting features, and must be submitted using one of the templates provided [here](https://github.com/netbox-community/netbox/issues/new/choose). For general discussion, questions, or assistance with installation issues, please post to our [mailing list](https://groups.google.com/forum/#!forum/netbox-discuss) instead.

**Comment by DanSheps** [comment]
@A888R, if you need assistance building a report, please go to the mailing list as specified and ask for assistance there.
