### ISSUE TITLE
Child prefixes change order in the aggregate's list when Hide available is selected

### ISSUE THREAD

**Issue by markkuleinio** [netbox-community/netbox#4455]
### Environment
* Python version:  3.7.3
* NetBox version:  2.7.11

### Steps to Reproduce
1. Create RIR for example "RFC1918"
1. Create Aggregate 10.0.0.0/8 with RIR RFC1918
1. Create VRF for example "Test VRF"
1. Create prefix 10.1.0.0/16 in "Test VRF"
1. Create prefix 10.2.0.0/16 with no VRF (= Global)
1. Go to **Aggregates - 10.0.0.0/8**
1. See that the list shows prefixes in IP-ordered: 10.1.0.0/16, 10.2.0.0/16 (as well as available prefixes)
1. Click **Hide available**

### Expected Behavior
The active prefixes would still show in the same order: 10.1.0.0/16, 10.2.0.0/16, just the available prefixes hidden

### Observed Behavior
The prefixes are shown in reverse order 10.2.0.0/16, 10.1.0.0/16 (i.e. Global prefix is shown first, VRF second)

**Comment by DanSheps** [comment]
I think this might be related to the same issue with IP Prefix hierarchy getting broken, FYI.

**Comment by jeremystretch** [comment]
Tagging as possibly related to #4617
