### ISSUE TITLE
New lines broken in comment display

### ISSUE THREAD

**Issue by Epaphus** [netbox-community/netbox#4456]
### Environment
* Python version:  3.6.8
* NetBox version:  v2.7.11

### Steps to Reproduce
1. Save a comment over multiple lines
2. View comment and it will be on a single line.

### Expected Behavior
Entering in the following comment box:

> This a comment.
> This is on a new line.

![image](https://user-images.githubusercontent.com/720274/78576649-de2f0280-7824-11ea-94c3-c8ba49e17c38.png)

### Observed Behavior
This a comment. This is on a new line.

![image](https://user-images.githubusercontent.com/720274/78576681-ebe48800-7824-11ea-93f7-db1a6a97c0c5.png)

This  used to work and changed recently, I suspect it might be linked to the Markdown changes in #4343
If you go to edit the comment it still shows the text on new lines as entered.

**Comment by jeremystretch** [comment]
Add two trailing spaces to the first line, [per the Markdown spec](https://www.markdownguide.org/basic-syntax#line-breaks).
