### ISSUE TITLE
Breadcrumb navigation improvement

### ISSUE THREAD

**Issue by Yannis100** [netbox-community/netbox#4461]
### Environment
* Python version:  3.6.10 
* NetBox version:  2.7.11 

### Proposed Functionality
Standardize Breadcrumbs in IPAM and Devices

Currently, the breadcrumbs (I hope it's the right word) are not very useful when browsing IP addresses and prefixes, it's better for Devices and Organizational objects but it could be improved in my opinion :
| Type       | Current                              | After                                                        | Comment                                              |
| ---------- | ------------------------------------ | ------------------------------------------------------------ | ---------------------------------------------------- |
| Device     | sitename / Racks / rackname / device | sitename / Racks / rackgroup / rackname / tenant / device    | tenant link to devices of the `tenant`               |
| Prefix     | Prefixes / prefix                    | site / tenant / prefix                                       | tenant link to prefixes assigned to the `tenant`     |
| IP Address | IP Addresses / IPAddress             | IP Addresses / ParentPrefixName / TenantName / DeviceName / IPAddress | include all parent prefixes ? Linked Device optional (already a link) |

I'm sure missing some others objects that would benefit from an improvement, but before I dig more into it, is anyone interested ?

### Use Case
Better navigation

### Database Changes
None I think

### External Dependencies
None

**Comment by DanSheps** [comment]
Tenant doesn't form part of the hierarchy for most of these models, as such it doesn't make sense to include them in the breadcrumb.

**Comment by Yannis100** [comment]
Thanks for your input
Ok then, maybe not in breadcrumb but what about a way to quickly navigate to the list of prefixes with tenant filter on from the prefix details page ? Same for ip address and so on.
It could be done with custom link but I would prefer to have it integrated?

**Comment by jeremystretch** [comment]
As @DanSheps pointed out, tenancy is not part of the hierarchy for these items, so it doesn't appear in the breadrcrumbs.

> what about a way to quickly navigate to the list of prefixes with tenant filter on from the prefix details page ? Same for ip address and so on.

You'd have to open a new issue proposing specific changes, as this differs from the proposal in this FR.

**Comment by Yannis100** [comment]
Fine I'll open a new FR
Still I find breadcrumbs a bit not straightforward, at least for IP Addresses and Prefix; in contrast VLAN breadcrumbs are exactly the way I imagine them (link to the list with filter on)
