### ISSUE TITLE
ObjectVar queryset returns all items - does not filter

### ISSUE THREAD

**Issue by darcynz** [netbox-community/netbox#4463]
### Environment
* Python version:  3.7 
* NetBox version: 2.7.11  

### Steps to Reproduce
1.  Added following code as per the Netbox New Branch Script example

```
    class Meta:
        name = "New Branch"
        description = "Provision a new branch site"
        fields = ['site_name', 'switch_count', 'switch_model']

    site_name = StringVar(
        description="Name of the new site"
    )
    switch_count = IntegerVar(
        description="Number of access switches to create"
    )
    switch_model = ObjectVar(
        description="Access switch model",
        queryset = DeviceType.objects.filter(
            manufacturer__name='Cisco',
            model__in=['Catalyst 3560X-48T', 'Catalyst 3750X-48T']
        ),
        widget=APISelect(display_field='model')
    )
```

2. Go the script page and click the model type drop down.

### Expected Behavior
Only 'Catalyst 3560X-48T', 'Catalyst 3750X-48T'] are displayed.

### Observed Behavior
All model types are displayed.

FURTHER INFO ---
I've been having this issue on a Site.objects.Filter() i've created that i could not get to work (it would display all records.

Tried to replicate via the site script example as above. But no fields would display initially.

Read the previous article related to widget=APISelect(display_field='model') and added that. Then saw it also displayed all device types instead of just two.

**Comment by darcynz** [comment]
Further to the above, when you run the script it returns an error if the filtered objects are not selected. Indicating that the problem is just what items in the dropdown list are displayed.

**Comment by DanSheps** [comment]
Please update the version information

**Comment by darcynz** [comment]
Done, sorry was commented out

**Comment by kobayashi** [comment]
To filter display objects, query parameters have to be in `APISelect`.

```
switch_model = ObjectVar(
    description="Access switch model",
    queryset=DeviceType.objects.all(),
    widget=APISelect(
        api_url='/api/dcim/device-types/',
        display_field='model',
        additional_query_params={'model': ['Catalyst 3560X-48T', 'Catalyst 3750X-48T']}
    ),

```

I will make PR to update [custom script section](https://netbox.readthedocs.io/en/stable/additional-features/custom-scripts/)

**Comment by darcynz** [comment]
Thanks, got it working...

One question, can additional_query_params, take a Danjo Queries?
eg DeviceType.objects.all(Q(model='Catalyst 3560X-48T')

Regards, Darcy

**Comment by kobayashi** [comment]
ObjectVar is filtered by `APISelect` widget which calls API to get objects. This has some parameters to filter objects. I will document these parameters also.

https://github.com/netbox-community/netbox/blob/5aadfff1de2ba7a07faa327c519df4038bab6e7e/netbox/utilities/forms.py#L252-L270

**Comment by ctrowat** [comment]
This is maybe a little bit on the periphery but still related to the subject of this issue.

My problem occurs on the scripts page, before executing a given script, when selecting an object of a given type:

When clicking into the dropdown the repeated sequential requests are made for item information (`?q=&limit=50&offset=<x>&brief=true`) until it has fetched all objects of a given type.  For example, when selecting Prefixes (of which we have a total of over 6000) this takes a substantial amount of time and does not seem like desired behaviour.  On other pages when using similar controls to select items it only makes a single request initially and waits until you scroll to the bottom of the results or type text in the box to make any additional requests.

**Comment by tyler-8** [comment]
@kobayashi In light of https://github.com/netbox-community/netbox/issues/4791 - does this issue still fit in to the 'documentation' category or could this issue be used to cover creating a publicly available API for Custom Script ObjectVar filtering as mentioned [here](https://github.com/netbox-community/netbox/pull/4509#issuecomment-616647816)?

**Comment by jeremystretch** [comment]
I've opened #4982 to address this functionality, which will entail its documentation as well.
