### ISSUE TITLE
Rack width of 21 inches for ETSI racks

### ISSUE THREAD

**Issue by toerb** [netbox-community/netbox#4464]
### Environment
* Python version: 3.6.8
* NetBox version: 2.7.11

### Proposed Functionality
Currently only rack widths of 10, 19 and 23 inches are supported.
I do have some ETSI sized racks (for european telecommunication) which is often referred to as 21 inch racks.
Here is a reference to them: https://en.wikipedia.org/wiki/19-inch_rack#ETSI_rack

### Use Case
I would like to document and plan my infrastructure in NetBox. Since I have 19 and 21 inch racks I need another option to accomplish this.

### Database Changes
The choices for rack width have to be updated.

### External Dependencies
None

**Comment by kobayashi** [comment]
I would like to accept this issue. The usecase is enough to add the choice.

**Comment by jeremystretch** [comment]
Does it make sense to name this option `21 inches (ETSI)` for clarification?

**Comment by toerb** [comment]
From my point of view `21 inches` would be more in line with the other options.
The 21 inch telecommunications rack from Europe is equivalent to the 23 inch rack in the US.

If you are okay with `21 inches` then feel free to re-open and merge my pull request (#4465).
