### ISSUE TITLE
Custom Links Filter not working as in 2.6

### ISSUE THREAD

**Issue by chas0rde** [netbox-community/netbox#4466]
### Environment
* Python version:  3.6.9
* NetBox version:  2.7.11

### Steps to Reproduce
1. Add custom link applied to devices
2. Set **Text** as follows:
`{% if  obj.status == 1 and obj.asset_tag %}Open management{% endif %}`
3. Set some URL

### Expected Behavior
Devices with asset tag set and status 1 (active) should render the link

### Observed Behavior
No link rendered.
If instead filter is set as follows it works (but this is not really the same filter as it matches other obj.status than 1 as well)
`{% if  obj.status and obj.asset_tag %}Open management{% endif %}`

**Comment by jeremystretch** [comment]
Choice field values were changed from integers to strings in v2.7. Please see the v2.7 release notes.

```
{% if obj.status == 'active' and obj.asset_tag %}
```

**Comment by chas0rde** [comment]
I was pretty sure that I tried that as well and it didn't work but I can verify that this works.
Maybe the documentation (https://netbox.readthedocs.io/en/stable/additional-features/custom-links/) should be updated accordingly as the example states the old syntax

Thanks for the quick reply :)
