### ISSUE TITLE
Fix the DeviceType filtering example in Custom Scripts

### ISSUE THREAD

**Issue by markkuleinio** [netbox-community/netbox#4472]
### Change Type
[ ] Addition
[X] Correction
[ ] Deprecation
[ ] Cleanup (formatting, typos, etc.)

### Area
[ ] Installation instructions
[ ] Configuration parameters
[X] Functionality/features
[ ] REST API
[ ] Administration/development
[ ] Other

### Proposed Changes
The object filtering example does not work in [Custom Scripts](https://netbox.readthedocs.io/en/stable/additional-features/custom-scripts/) (the device list stays empty even though the device models exist in NetBox, tested with NetBox 2.7.11):

```
    switch_model = ObjectVar(
        description="Access switch model",
        queryset = DeviceType.objects.filter(
            manufacturer__name='Cisco',
            model__in=['Catalyst 3560X-48T', 'Catalyst 3750X-48T']
        )
    )
```

I propose updating the example with a working code.

In #4453 there is a mention about `APISelect` but I cannot figure out the correct filtering use of it to submit a PR on this.

**Comment by jeremystretch** [comment]
This looks to be essentially the same issue reported under #4463, and should be resolved by the same work. Going to mark it as a duplicate.
