### ISSUE TITLE
Device type does not populate when bulk editing devices.

### ISSUE THREAD

**Issue by ebusto** [netbox-community/netbox#4474]
### Environment
* Python version:  3.6.9
* NetBox version:  2.7.12

### Steps to Reproduce
On the device list page, select a few devices, then click "Edit Selected". 

This is reproducible on DanShep's [demo site](https://master.netbox.dansheps.com/) running 2.7.11, as well as our instance running 2.7.12.

### Expected Behavior
The "Device type" field in the form should populate when selected.

### Observed Behavior
The "Device type" field remains empty. Other fields populate correctly.

**Comment by kobayashi** [comment]
Thanks to let us know this! this needs some fix in a js file. `device_type` does not have name attribute to assign here.

https://github.com/netbox-community/netbox/blob/c593eca9364e0fcca54b7cd4986470da795cb065/netbox/project-static/js/forms.js#L223-L225
