### ISSUE TITLE
Fix infiniband misspelling

### ISSUE THREAD

**Issue by solj** [netbox-community/netbox#4476]
### Environment
* Python version:  3.6.8
* NetBox version:  2.7.10

### Steps to Reproduce
1. Try to add an infiniband interface via the API using the correct spelling.

### Expected Behavior

The interface should be added.

### Observed Behavior

 The request failed with code 400 Bad Request: {'type': ['infiniband-hdr is not a valid choice.']}

**Comment by sdktr** [comment]
What’s your exact API request that failes? From the current info it’s not deducible what your definition or ‘correct spelling’ entails? Merci!

**Comment by solj** [comment]
The problem is detailed in #4475. Basically, the current choices are spelled inifiband instead of infiniband.

**Comment by sdktr** [comment]
Ah, missed that PR. Good ol’ inifiband, never made it to mainstream usage🤐

**Comment by kobayashi** [comment]
Thanks to follow the template. I am accepting this for fixing the spell. Another maintainers will accept to go further.

**Comment by jeremystretch** [comment]
@kobayashi Just to clarify, the two-maintainer requirement is only for FRs. Only one approval is needed for confirmed bugs.
