### ISSUE TITLE
Capitalization not respected in Custom Field

### ISSUE THREAD

**Issue by cpajr** [netbox-community/netbox#4480]
### Environment
* Python version: 3.7.7
* NetBox version: 2.7.12

When creating a custom field, Netbox will only respect the first letter capitalization in the first word but no other letters following that.  This is particularly seen with the name "DNS Entry"

### Steps to Reproduce
1. Create a custom field with the name "DNS Entry" for a DCIM device
2. Within a DCIM device, find the field.  
3. The field with be presented as "Dns entry" as opposed to "DNS Entry"

### Expected Behavior
Expecting that capitalization be respected.  

### Observed Behavior
First letter of the first word is the only one capitalized.  

![image](https://user-images.githubusercontent.com/36517688/79133243-edeca080-7d68-11ea-9b0e-dd10a0789238.png)

**Comment by candlerb** [comment]
This is not a bug.  You need to write:

```
dns_entry = StringVar(label="DNS Entry")
```

**Comment by cpajr** [comment]
Probably helps if I read the documentation a little more closely.  Thanks.

**Comment by jeremystretch** [comment]
I think @candlerb's example above pertains to custom _scripts_; for a custom field, you just need to specify the desired human-friendly label in the admin UI:

![Screenshot_2020-04-13 Change custom field NetBox](https://user-images.githubusercontent.com/13487278/79144576-31f19c80-7d8d-11ea-83e3-7aab11a4d3bf.png)

**Comment by cpajr** [comment]
@jeremystretch Thanks.  That is exactly what I did.

**Comment by candlerb** [comment]
Sorry, my mistake to mix up Custom Script fields with Custom Fields.  But glad it's sorted :-)
