### ISSUE TITLE
Disable "Logout" menu item when remote auth enabled

### ISSUE THREAD

**Issue by candlerb** [netbox-community/netbox#4484]
### Environment
* Python version:  3.6.9
* NetBox version:  2.8.0

### Proposed Functionality

Netbox v2.8.0 / #2328 now includes remote authentication via HTTP header.

In the simplest case, I propose that the "Logout" menu item is hidden or disabled when `REMOTE_AUTH_ENABLED` is True.

### Use Case

Reduces user confusion when using REMOTE_AUTH.  Netbox currently flashes that you have been logged out, but of course the REMOTE_AUTH_HEADER is still set in the next request, so you are immediately logged back in.

### Optional: logout redirect

To actually perform a logout you need to send some sort of trigger.  For example, using [mod_auth_openidc](https://github.com/zmartzone/mod_auth_openidc/wiki#9-how-do-i-logout-users) you can redirect to the `OIDCRedirectURI` with a parameter `logout=<final-URL>`.  This will logout the session and then redirect you to the given page (presumably not netbox itself, because that would immediately try to log you in again).

Therefore, as a second part of this feature request, you could add a `REMOTE_AUTH_LOGOUT_URL` setting, which re-enables the Logout menu item, and redirects to this URL when selected.

### Database Changes

None

### External Dependencies

None

**Comment by jeremystretch** [comment]
> In the simplest case, I propose that the "Logout" menu item is hidden or disabled when `REMOTE_AUTH_ENABLED` is True.

With remote authentication enabled a user may still authenticate locally, in which case the option to log out is still valid, so referencing the setting alone is not sufficient.
