### ISSUE TITLE
Display 'Stats' for tenant groups as well as tenants

### ISSUE THREAD

**Issue by cpmills1975** [netbox-community/netbox#4486]
### Environment
* Python version:  3.7.7
* NetBox version:  2.8.0

### Proposed Functionality
When clicking on a tenant (/tenancy/tenants/tenant-name), the details of the tenant is shown along with a 'Stats' panel showing the primary objects 'owned' by that tenant. Clicking on one of the 'primary' types, for example 'Devices' takes the user to the devices page pre-filtered with the selected tenant (/dcim/devices/?tenant=tenant-name).

I'd like to suggest that rather than having the tenant group name link to the list of tenants, it directs to a page similar to the tenant display showing the stats panel for all objects assigned to a tenant under that group. Clicking on on one of the boxes in the stats panel will direct to the list view for that type, filtered by tenant group rather than an individual tenant (e.g. /dcim/devices/?q=&tenant_group=group-name)

To address the loss of a view showing lists of tenants within a group, I'd propose adding another item to the stats panel showing 'tenants' - the stats panel currently contains 11 items arranged in four rows of three, so an additional one for tenants would work perfectly.

Alternatively, would a hybrid view be possible?  Perhaps clicking on a tenant group could show the stats panel on the right and a list of contained tenant groups (just like the existing tenant groups list view) on the left?

Obviously the ability to view devices by tenant group already exists, so these enhancements are purely UI enhancements.

### Use Case
Equipment, VMs, etc are usually purchased/requested by a project. A project is usually part of a team and a team is part of a department. This project/team/department modelling is now available using nested tenant groups. Allowing users to view everything 'owned' by a team or a department as well as a project (tenant) would be useful. The functionality to do this already exists by filtering each of the lists by tenant group, but this enhancement reduces the number of clicks to achieve that.

### Database Changes
None required.

### External Dependencies
None.

**Comment by jeremystretch** [comment]
NetBox does not provide dedicated views for organizational models such as tenant groups, rack groups, etc. This may change in the future but the current view structure does not allow for it.
