### ISSUE TITLE
Display sub-group racks in rack elevation view

### ISSUE THREAD

**Issue by ngombert** [netbox-community/netbox#4487]
### Environment
* Python version:  3.6.9
* NetBox version:  2.8

### Proposed Functionality
Since hierachy has been added for groups, the rack elevation view does show any rack which belong to a sub group. we may want to display all the sub-group racks within that view

### Use Case
On the rack elevation view, if a given rackgroup has one or multiple sub-group, thoses groups may be displayed as a new row.

### Database Changes
This is purely a ui change

### External Dependencies
no new dependency

**Comment by jeremystretch** [comment]
> Since hierachy has been added for groups, the rack elevation view does show any rack which belong to a sub group.

Filtering the rack elevations list by rack group will display all racks immediately within that group as well as all racks within child groups. This uses the same query filter as the regular list view for racks.
