### ISSUE TITLE
Rack elevations are offset when racks don't have a facility ID

### ISSUE THREAD

**Issue by cpmills1975** [netbox-community/netbox#4488]
### Environment
* Python version: 3.7.7
* NetBox version: 2.8.0

### Steps to Reproduce
1. Create a rack with a facility ID
2. Create another rack without a facility ID
3. View the elevations view (/dcim/rack-elevations)

### Expected Behavior
One assumes the racks are bottom-aligned as this would make sense when say a 42U rack is located next to a 47U rack but U1 in both racks should be aligned regardless of whether a rack has a facility ID or not.

### Observed Behavior
The rack with a facility ID appears to be pushed up by the text showing the facility ID. In my browser (Safari) this is about the space of a U meaning U41 in the rack with a facility ID appears level with U42 on the rack that doesn't have a facility ID.

Unfortunately I cannot grab a screen shot of this, or I would.

**Comment by jeremystretch** [comment]
This is expected behavior; we don't force whitespace where facility IDs are not in use. People generally either use or don't use facility IDs consistently, so this isn't often a problem.
