### ISSUE TITLE
The contrib systemd unit file can cause first NetBox WSGI start to fail

### ISSUE THREAD

**Issue by bluikko** [netbox-community/netbox#4493]
### Environment
* Python version: 3.6.8
* NetBox version: 2.8.0

### Steps to Reproduce
1. Configure systemd with `contrib/netbox.service`.
2. Make sure Redis takes a few seconds to start.
3. systemd attempts to start NetBox before Redis has completed starting up and loading data and NetBox will error.

### Expected Behavior
NetBox starts only after Redis is ready.

### Observed Behavior
NetBox systemd unit file does not depend on Redis so it will not wait Redis to signal to systemd that it has completed startup.

**Comment by kobayashi** [comment]
Could you share your environment and error message to reproduce?

**Comment by bluikko** [comment]
If Netbox is started before Redis is ready the error is seen:
```
Apr 15 10:00:00 netbox gunicorn[2497]: redis.exceptions.BusyLoadingError: Redis is loading the dataset in memory
```

This should be mitigated (possibly not completely fixed in older Redis, there is a bug up to at least Redis 5.0.6 that signal readiness too early) by starting after Redis and not the generic target. `redis.conf` needs `supervised systemd` option or alternatively on EL7 the stock `redis.service` unit file already starts Redis with `--supervised systemd`.

**Comment by jeremystretch** [comment]
Why are we concerned with Redis specifically and not, for example, PostgreSQL or network connectivity? PostgreSQL is obviously crucial, and any queued webhooks should not be sent until NetBox has network connectivity.

**Comment by bluikko** [comment]
I have not had problem with PostgreSQL or network connectivity. I do not know if for example pgsql can signal its readiness to systemd.
I do have the problem listed in the error message above where Redis takes its time to start.

**Comment by DanSheps** [comment]
I don't know if this is something we want to do, as redis does not have to be on the local NetBox server.  Same with postgresql.

**Comment by jeremystretch** [comment]
@DanSheps that's a very good point. IMO we should leave things as-is, and leave any modifications up to the discretion of the user.

**Comment by DanSheps** [comment]
IMO changing it to Wants= isn't going to break things, Wants= doesn't actually do anything if the wanted service doesn't start.

You need to use the Requires= for that and I don't think we want to get into that.
