### ISSUE TITLE
Azure Options

### ISSUE THREAD

**Issue by colin-small** [netbox-community/netbox#4497]
### Environment
* Python version: 3.6 
* NetBox version: 2.7.6 

### Proposed Functionality

I would like to see options throughout Netbox that are more Azure/cloud friendly for documenting Azure based "devices" and virtual networks.

For Azure specific stuff like maybe a way to assign resource groups or is it a dynamic or static public IP.. vnets... IaaS options.. subscriptions networks live in.. ExpressRoute circuit type and data for private peering/public peering etc.. vnet peering to tie vnets together.. route tables/routes. product SKU's to document the type of object because it may have limitations based on the SKU.

This is a broad topic and I am just doing a brain dump of some useful things that come to mind. If anyone else uses Azure and Netbox maybe they can chime in and add more options that would add value.

If this doesn't paint the picture so to speak, I can start documenting as I add things to Netbox where it would have been nice to have X option each time and start adding them here.

Really I am just saying from a high level that Azure specific options would help me out a lot as I'm living in an onprem/cloud world when it comes to infrastructure/networking.

### Use Case

See above

### Database Changes

I'm not sure.

### External Dependencies

None I am aware of.

**Comment by jeremystretch** [comment]
Thank you for your interest in NetBox. GitHub issues are intended for reporting reproducible bugs and requesting features, and must be submitted using one of the templates provided [here](https://github.com/netbox-community/netbox/issues/new/choose). For general discussion, questions, or assistance with installation issues, please post to our [mailing list](https://groups.google.com/forum/#!forum/netbox-discuss) instead.

**Comment by colin-small** [comment]
Did you close this issue because I didn't provide a list of specific items but rather a broader scope? Just trying to understand. Thanks.

**Comment by jeremystretch** [comment]
Yes; issues are intended for directly actionable work, not general discussion. The mailing list is much better suited to open-ended discussion. Once you've identified specific features you'd like to propose, you're welcome to open individual issues for them.
