### ISSUE TITLE
Custom Fields Groups

### ISSUE THREAD

**Issue by lmgonzalezl** [netbox-community/netbox#4499]
### Environment
* Python version:  Python 3.6.8 
* NetBox version: v2.8.0  

### Proposed Functionality
Sometimes it is convenient to group the custom fields, for example in our case we use the object circuits to register macrolan circuits, RTB telephone lines, FTTH services, etc. Each one of these services requires specific customs fields and it would be interesting to be able to group them in some way in the view.

### Use Case
An example of the utility previous would be to show groups of custom fields as follows

**Custom Fields**
-------------------
**Group VoIP**
     Custom Field 1
     Custom Field 2
...
**Group Macrolan**
     Custom Field 1
     Custom Field 2
...

The groups may or may not be associated with the type of circuit, in this way only the specific custom fields for that group would be shown.

### Database Changes

Yes, but I don't know how to describe it.

### External Dependencies

Its no is necesary.

**Comment by kobayashi** [comment]
Thank you for submitting your idea. We are not currently extending custom fields to other models. Please see the [FAQ](https://github.com/netbox-community/netbox/wiki/Frequently-Asked-Questions#can-we-add-custom-fields-to-more-models) for more detail.
