### ISSUE TITLE
Wrong FQDN on racks devices after upgrade

### ISSUE THREAD

**Issue by ilyamoshkin** [netbox-community/netbox#4500]
### Environment
* Python version: 3.6.8
* NetBox version: 2.8.0

### Steps to Reproduce
1. Upgrade 2.5.13 up to 2.8.0.
2. Take errors with "extras_tag.comments does not exist" and like "unsupported PGSQL version".
3. Downgrade to 2.6.0 and then again upgrade to 2.8.0.

### Expected Behavior
Normal FQDN in focus on racked devices.

### Observed Behavior
https://**netbox.backend**/ in FQDN part of URL where netbox is the 3rd lvl name. 
Please help how to fix that.

**Comment by kobayashi** [comment]
Thank you for your interest in NetBox. GitHub issues are intended for reporting reproducible bugs and requesting features, and must be submitted using one of the templates provided [here](https://github.com/digitalocean/netbox/issues/new/choose). For general discussion, questions, or assistance with installation issues, please post to our [mailing list](https://groups.google.com/forum/#!forum/netbox-discuss) instead.
