### ISSUE TITLE
Show cable colours on all device views

### ISSUE THREAD

**Issue by craigmoscardni** [netbox-community/netbox#4506]
#3823 # Environment
* NetBox version: 2.7.12

### Proposed Functionality

On devices with interfaces such as switches or routers there is a colour patch next to the cable trace button so the cable colour can be seen without leaving the device view. That colour patch doesn't appear on front/back ports or power ports. For those it is necessary to click the cable to view the colour there. Can that be standardised to show the cable colour on all interface types?

### Use Case

Simplify visibility of cable colours

### Database Changes

None expected. Data is already present

**Comment by kobayashi** [comment]
Thank you for submitting this issue, however it appears that this topic has already been raised. Please see issue #3682 for further discussion.
