### ISSUE TITLE
Add CentOS 8.1 to installation documentation

### ISSUE THREAD

**Issue by ariesgeek** [netbox-community/netbox#4507]
### Change Type
[X] Addition
[ ] Correction
[ ] Deprecation
[ ] Cleanup (formatting, typos, etc.)

### Area
[X] Installation instructions
[ ] Configuration parameters
[ ] Functionality/features
[ ] REST API
[ ] Administration/development
[ ] Other

### Proposed Changes

The current CentOS installation instructions reference CentOS 7.5 and appear to be accurate for that OS version. CentOS 8.1 is different from 7.5, in that it includes a new package manager in `dnf`, it now ships with a supported version of PostgreSQL, which serves to simplify the installation overall, and some of the required packages have changed.

I recently installed NetBox in a fresh CentOS 8.1 environment and updated the existing installation documentation as I proceed through the steps.  I can submit a pull request, but wanted to make sure I had this documentation change issue written up first.

**Comment by jeremystretch** [comment]
We don't have the resources to maintain more than one version of the installation documentation per distribution. (Frankly, we barely have the resources to support what we have already.) So the proposal here would be to _replace_ the existing 7.5 documentation with 8.1.

I don't have a strong opinion either way, but I get the feeling 8.1 is probably still too new for many people. Leaving this open for debate.

**Comment by ariesgeek** [comment]
Thank you for your time, Jeremy.

Very valid points! Judging by the sound of the crickets, I am going to assume that we'll stay with the status quo for the time being, but I will continue to maintain CentOS 8.1 documentation in a separate branch off of my fork and will make a little noise when it is looking like 8.x might be overtaking 7.5.

Not to be too presumptive, I won't close this issue right now, but will defer to the judgment of the maintainers as to how long this should remain open for feedback from the community.

**Comment by chicks-net** [comment]
Would it make sense to put this sort of stuff in the [wiki](https://github.com/netbox-community/netbox/wiki) so it doesn't convey the same level of maintenance while still letting useful contributions land somewhere?

**Comment by jeremystretch** [comment]
@chicks-net No; all the documentation for which the core maintainers are responsible must reside within the git repository. We use the wiki to a limited extent for "meta" documentation about the project rather than the application itself.

**Comment by chicks-net** [comment]
We keep running into the core maintainers not wanting to maintain installation documentation for different distributions.  I put the years it took to move from supervisor to systemd in the docs into the same category.  But folks from the non-core community are showing and trying to help.  This seems like the sort of thing that belongs in the wiki to me, but it doesn't sound meta-enough for you.  I don't see the harm in this sort of thing being in the wiki, but I'm not in charge, so I defer to your expertise.  And you're running a really tight ship so I do strongly believe in that expertise.

It sounds like the only clearly acceptable option would be for the community of non-core netbox developers to start a new project to maintain installation docs.  I doubt that will happen, but maybe enough folks will step up.

Another possibility would be allowing for some folks to maintain docs, even if they're not good enough to be a core developer.  Other FLOSS projects have had similar documentation subprojects.  I'd be happy to help with this from writing docs to maintaining docs automation.

**Comment by jeremystretch** [comment]
> This seems like the sort of thing that belongs in the wiki to me, but it doesn't sound meta-enough for you.

It's not meta at all. These are the instructions we're providing for users to install NetBox. We can't tell someone, "if you have CentOS 7.5 go to RTD, but for 8.1 go over here to the wiki, but only for certain parts." That doesn't make any sense.

Additionally, we have and continue to accept pull requests for documentation; there is no need for a formal role. However, it needs to be maintainable so that when the PR author disappears someone else can continue the work.

**Comment by jeremystretch** [comment]
It doesn't seem like there's a strong demand for updating the installation docs for CentOS to 8.1 at this time. We can revisit in the future.

**Comment by ariesgeek** [comment]
> It doesn't seem like there's a strong demand for updating the installation docs for CentOS to 8.1 at this time. We can revisit in the future.

Sounds good. Feel free to reach out to me if and when. I also lurk on the NTC slack.
