### ISSUE TITLE
CustomFieldChoice queryset in custom scripts throws django.urls.exceptions.NoReverseMatch exception

### ISSUE THREAD

**Issue by benjy44** [netbox-community/netbox#4508]
### Environment
* Python version: 3.6
* NetBox version: 2.8.0

### Steps to Reproduce
1. Create a custom field in the administration panel
2. Create a custom script with an ObjectVar using `queryset=CustomFieldChoice.objects.all()`
3. Click on the newly created script in /extras/scripts/

### Expected Behavior
The script form shows up

### Observed Behavior
exception:
```
<class 'django.urls.exceptions.NoReverseMatch'>

Reverse for 'customfieldchoice-list' not found. 'customfieldchoice-list' is not a valid view function or pattern name.
```

It also fails for CustomField and CustomFieldValue, It was working fine at least in 2.7.3

**Comment by DanSheps** [comment]
I don't believe there are any endpoints for custom fields, which is probably the root cause of this.

**Comment by benjy44** [comment]
oh no bot! :)
