### ISSUE TITLE
Enable the import of device types from JSON-formatted definitions

### ISSUE THREAD

**Issue by jeremystretch** [netbox-community/netbox#451]
Currently, each NetBox user must create their own device types. This results in wasted effort because users inevitably end up duplicating work. For instance, ten users who each use Juniper EX4300-48T switches will end up creating identical (or at least exceeding similar) device types.

We don't want to pre-populate device types in NetBox on initial installation, because it's impossible to predict which device types a user will want. Extraneous device types would result in clutter that needs to be deleted.

Ideally, we could begin compiling a library of device type definitions formatted as JSON. A user could select the desired device types from the library and import them into NetBox to create device types.

**Comment by fltchr** [comment]
Is this users per instance (i.e. if I create a device for a Cisco 3560, my boss won't be able to select it), or NetBox users in general (i.e. if I create a device, there is no "device community" to share it with other companies?

If the first point, I haven't noticed yet (haven't tested on more than one user account as of yet), but we'll definitely need that before moving forward., if the second, a user submitted gallery or library would be an awesome resource.

**Comment by rikigst** [comment]
+1 for the user submitted gallery, I think it would be very popular; even
with anybody's particular setting, little tweaks to each device type can
always be done after the import

Il giorno mer 10 ago 2016 alle ore 21:28 Michael Fletcher <
notifications@github.com> ha scritto:

**Comment by jeremystretch** [comment]
@fltchr "User" in this context just means an organization using NetBox. Sorry for the confusion.

Here's a scenario. You just got in a shipment of Juniper QFX5100-48S switches that need to be racked up. You've never used these before, so first you need to create a new device type in NetBox. But rather than creating one manually, you can instruct NetBox to import a definition from a GitHub repo, e.g. `netbox-devicetypes/juniper/qfx5100-48s.json`. NetBox downloads the file and automatically creates a new DeviceType along with its console, power, and interface templates as defined.

I just need to come up with the logic to process JSON and start a library.

**Comment by stianvi** [comment]
@jeremystretch There are also modules for devices that need to be taken into consideration. 

example:
QFX5100-24Q: 32 ports (with hot-swappable expansion modules)
QFX5100-24Q-AA: 32 ports (with hot-swappable expansion modules)

And then there is the cabling too:
QFX5100-48S: 72 ports (48 10GbE SFP/SFP+ ports + 24 10GbE ports using QSFP+ to SFP+ DAC or QSFP+ to SFP+ fiber splitter cables and optics)

**Comment by jeremystretch** [comment]
@stianvi Expansion modules aren't part of the device, so they aren't attached to a device type. They may or may not be installed; that's up to the user to define. And cabling isn't modelled at all.

**Comment by leandroteleco** [comment]
I'm very interested on this feature.
I'm working at important Service Provider and we are testing Netbox at our Demolab,

Thanks you for to do and to improve NetBox, I think could countribute with the device types submitted gallery. :)

**Comment by askbow** [comment]
An export feature for device types might be a good idea too: some of us have already created libraries of devices, sharing them might be useful, given import is implemented.

**Comment by tobymccann** [comment]
This would be extremely useful, including some of the ideas already mentioned such as export.  I imagine some type of verification mechanism to verify the accuracy of each device type, but that could probably be controlled via Github workflow.

**Comment by prolix21** [comment]
This would save so much work. We just setup Netbox and the thought of having to create all these device types gives me a headache.

**Comment by bellwood** [comment]
@jeremystretch I'm not sure the viability, but, Cisco provides Visio stencils for all their hardware.

Providing one could process those VSS files (they are hexadecimal) you might be able to "Easily" convert all the Visio stencils to JSON based on the data provided within.

That said, I'm not sure if the stencils include mgmt or con ports but it might be a place to start.

I would also recommend that users with existing devices templates be able to "upgrade" their devices to the new templates as a method of standardization - if they so chose.

**Comment by askbow** [comment]
@bellwood probably this can be used to convert VSS files to something more open: https://github.com/kakwa/libvisio2svg

these VSS pictures might be somewhat useful for drawing rack faces (_if you want them to look fancy_), but I doubt you can export ports or other sticky points.

**Comment by bellwood** [comment]
I was hoping more for port details than graphics for JSON library building,
just figured it's a somewhat complete provider library we might be able to
process it

Graphics could/would nice though on the rack elevations via another feature
request

**Comment by tb-killa** [comment]
Hi @jeremystretch how about something like this :

```
{
   "dcim.manufacturer":"Cisco",
   "dcim.devicetype.model":"Nexus 2248Tp",
   "dcim.devicetype.u_height":"1",
   "dcim.devicetype.is_full_depth": false,
   "dcim.consoleporttemplate":[
	{
		"name": "Console"
	},
    {
        "name": "RescueConsole"
    }
   ],
   "dcim.consoleserverporttemplate":[
	{
		"name": "Port 1"
	}
   ],
   "dcim.powerporttemplate":[
	{
		"name": "PSU1"
	},
	{
		"name": "PSU2"
	}
   ],
   "dcim.interfacetemplate":[
	{
		"name": "fxp0 (RE0)",
        "form_factor": 1000,
        "mgmt_only": true
	}
   ]
}
```
Maybe I forgot something but this should be first of all a draft. 

I'm not a Django specialist so don't know much about them but maybe we could build some sort of import page with big textbox for input the json based template directly.?

**Comment by tb-killa** [comment]
@jeremystretch I found this nice library: **django-import-export** 
Maybe we could use this or the implementation logic for working with the json in / export ?
I´m not an django expert to implement this stuff but maybe this would help you ?
