### ISSUE TITLE
Add the functionality to disable sorting of keys in the config contexts (json)

### ISSUE THREAD

**Issue by co1dhand** [netbox-community/netbox#4515]
### Environment
* Python version:  3.7.5
* NetBox version:  2.7.11

### Proposed Functionality
Add the option in configuration.py for example, to disable the sorting of keys in the context data (json format) (whether it been a global or a local context).

### Use Case
We are currently automating the deployment of our new DataCenter equipment, so we thought of stocking into Netbox, all of the related static configurations in a json format, which we then dump into a yaml file using ansible and some python scripts, but sadly, since the keys gets sorted out in Netbox, the target file and output differs. 

### Database Changes
None

### External Dependencies
None

**Comment by jeremystretch** [comment]
This is a function of Python's `json` library and AFAICT not configurable. For validation purposes, I suggest also sorting the data with which NetBox data is being compared. This ensures that the ordering is always consistent.

**Comment by co1dhand** [comment]
> This is a function of Python's `json` library and AFAICT not configurable. For validation purposes, I suggest also sorting the data with which NetBox data is being compared. This ensures that the ordering is always consistent.

It is indeed a function of the Json library, I did look into the Netbox code, and found that in the following file, sort_keys was either set to True, or not set at all.

I modified them manually, but after restarting the Netbox service, nothing had changed.

netbox/extras/models.py
netbox/utilities/templatetags/helpers.py
netbox/utilities/forms.py
