### ISSUE TITLE
Bulk edit device type fails

### ISSUE THREAD

**Issue by ognjen011** [netbox-community/netbox#4517]
### Environment
* Python version: 3.6
* NetBox version: 2.7.12

### Steps to Reproduce
1. Click device types
2. Filter for a device type you want to update and click on instances. 
3. Then select multiple devices and click edit selected. 
4. Then on the right click on device type. 

### Expected Behaviour
Search box should show different types and allow you to narrow your search by typing exact device type. 
### Observed Behaviour
Search box is empty event when i try typing a device type i have in the database it just goes back to being blank and i am not able to choose any of the existing options.

**Comment by jeremystretch** [comment]
Sounds like #4474. Please upgrade to v2.8.0.
