### ISSUE TITLE
Add site specific vlans to bulk editing of interfaces

### ISSUE THREAD

**Issue by nathbooth** [netbox-community/netbox#4523]
### Environment
* Python version: 3.7
* NetBox version: 2.7.11

Attempt to bulk edit interfaces and add vlans;
- Device is within a tenant
- VLANs are linked to the same tenant
- Navigate to Devices>Interfaces and bulk edit interfaces
- Set mode to access or trunk
- VLAN lookup returns 'no results found' for tagged and untagged vlans

If i edit the interfaces in the same way but select the interfaces from the device page under /dcim/devices it works correctly and shows the vlans.

### Steps to Reproduce
1. Create a tenant
2. Create device with interfaces and vlans within that tenant
3. Navigate to Devices>Interfaces
4. Bulk edit device interfaces
5. Set mode to access or trunk
6. Observe no results found for vlans.
7. Create new vlan without a tenant attached
8. Repeat step 3-5
9. Global VLAN create in step 7 is available for interface even though the device is within a tenant.

### Expected Behavior
VLAN are shown for the tenant

### Observed Behavior
No results are found and global vlans are shown when only tenant ones should be

**Comment by DanSheps** [comment]
I am not able to recreate this on https://master.netbox.dansheps.com/

Could you please test on there and then revise your steps.  You need to include:

Device:
- Site used
- Rack, if any

Interface:
- Type

VLAN:
- Status
- Site, if any
- Group, if any

For both test cases.

**Comment by nathbooth** [comment]
Well you are running 2.8.0 on there, could it be that it's the same issue as this? [#4474](https://github.com/netbox-community/netbox/issues/4474)

**Comment by nathbooth** [comment]
Have upgraded to 2.8.1 and issue still persists. 
The issue from what i can see is as part of the bulk edit of interfaces the lookup references site=null
GET /api/ipam/vlans/?q=&limit=50&offset=0&brief=&site_id=null
I have managed to replicate this on your test instance now.
If you try and bulk edit interfaces on device NB-TEST-SWITCH you are only able to assign vlan 100 and 101 which are not assigned to a site. 
Edit from dcim/interfaces
![image](https://user-images.githubusercontent.com/1272614/80348121-37f37d00-8865-11ea-9f45-f7f61321e933.png)
Edit from devices page (appears to add site_id=null and site_id-<id>
![image](https://user-images.githubusercontent.com/1272614/80348065-2611da00-8865-11ea-8596-e0df001bb762.png)

**Comment by DanSheps** [comment]
Alright, so it isn't that there are no sites showing, it is that there are only global sites showing.  Which right now is to be expected as bulk edit has no concept of being in a site (mainly because you can bulk edit across many devices).

We can try changing this, but we would have to find a good balance.  Do we only show site vlans when bulk editing devices in the same site?  Do we allow bulk editing of any site a device is currently in and silently ignore invalid site vlan assignments?  Do we throw an error?  Do we attempt to map if the same VID's exist?

A lot of options and each might be perfectly viable.

**Comment by jeremystretch** [comment]
@DanSheps any progress on this?

**Comment by DanSheps** [comment]
I have gotten this working and chosen the following approach:

If the site matches for all interfaces, the site-specific interfaces will display.  If the site does not match, only global vlans will display.  I think this is a nice balanced approach which does not require a lot of further coding to be workable (existing validation logic is still valid).

What we get is this:

Same Device: Shows site vlans
Different Device, Same Site: Shows site vlans
Different Device, Different Site: Only Show Global VLANs
