### ISSUE TITLE
Absolute URL points to wrong link in SVG rack view

### ISSUE THREAD

**Issue by heiko-ma** [netbox-community/netbox#4526]
### Environment
* Python version: 3.6.8
* NetBox version: 2.8.0

### Steps to Reproduce
1. Disable any installed plugins by commenting out the `PLUGINS` setting in
   `configuration.py`.
2. Select a rack through navigation to **Organization** -> **Racks** -> **the rack**
3. Select any device by clicking on it

### Expected Behavior
The properties of the selected device should be opened and I should be able to edit them.

### Observed Behavior
Netbox is redirecting the request to 127.0.0.1:8001 instead of the URL used to access the site itself. Therefore the request can't be completed. This could be related to https://github.com/netbox-community/netbox/issues/4147

### Workaround
Selecting the device through **Devices** -> **Devices** -> **the device** works because in this case, no absolute URL is used.

**Comment by jeremystretch** [comment]
NetBox uses whatever host information gets forwarded to it from the HTTP frontend (e.g. nginx or Apache). It looks like your server isn't configured to forward this information. Check your configuration against the relevant reference configuration provided in [contrib/](https://github.com/netbox-community/netbox/tree/develop/contrib). Please post to the [mailing list](https://groups.google.com/forum/#!forum/netbox-discuss) if you need further assistance.
