### ISSUE TITLE
Config Context by Tag Form broken

### ISSUE THREAD

**Issue by tobikris** [netbox-community/netbox#4527]
### Environment
* Python version: 
* NetBox version: v2.7.8

### Steps to Reproduce
1. Create a tag which contains uppercase letters (e.g. LeafSwitch).
2. Try to add this tag to a config context.

### Expected Behavior
I would expect that the tag can be successfully set in the config context.

### Observed Behavior
The tag is invalid: "Select a valid choice. 2 is not one of the available choices."
The workaround is to only use tags that do not use uppercase letters. I think after some debugging that the form is only working if the tag name is exactly equal to the tag slug.

**Comment by jeremystretch** [comment]
Please specify the exact tag value you are using.

**Comment by tobikris** [comment]
I added an example tag (LeafSwitch). I tried several and the common property of problematic tags is uppercase letters.

**Comment by tweippert** [comment]
I tested it with these tags:

L2:DMZ-DE -> invalid message
l2:dmz-home -> invalid message 
l2-dmz-home -> all fine

HTH, 
tim
