### ISSUE TITLE
Custom Fields / Images import for Device Types

### ISSUE THREAD

**Issue by Sislik** [netbox-community/netbox#4534]
### Environment
* Python version:  3.6.4
* NetBox version:  2.8

### Proposed Functionality
Allow custom fields and image location to be imported for new device types.

### Use Case
I'm creating a yaml of quite lot of server types so i would like to make it properly also for future use.
Images -> Allowing yaml/json creation import of device images from http://www.visiocafe.com/ and put them in devicelibrary in git for everyone to use. Or option to have predefined use for picture based on slug name. (For example slug name proliant-dl360p-gen8 will have automatically picture proliant-dl360p-gen8-front.png and proliant-dl360p-gen-rear.png
Custom Fields -> There are basic informations for server types, which can be handy to have stored in inventory management, like number of dimm slot, maximum number of disk drives (even that this is more flexible value), number of pci slots. Also if this field would be possible to have been propagated to devices itself as that would allow changes of actual configuration -> 6 DIMM slots full, 12 SFF disks... etc.

I hope i'm not just doing something wrong as im new with NetBox, but im planning to use it for quite big enviroment :)

**Comment by jeremystretch** [comment]
> Allowing yaml/json creation import of device images

We intentionally do not support the inclusion of image files in the device type library due to copyright issues.

> There are basic informations for server types, which can be handy to have stored in inventory management

Custom fields are, by definition, custom. It would not make sense to include these in a standardized device type definition.
