### ISSUE TITLE
None Optical Type Interfaces could be selected (https://es.wikipedia.org/wiki/Gigabit_Ethernet)

### ISSUE THREAD

**Issue by jorgeNeutrona** [netbox-community/netbox#4538]
### Environment

3d34e9e34bf1 (v2.8.1)

last version Docker pulled (25/4/2020)

 Interface Template --> Selection --> Optical
Please add optical Interfaces 

1G and 10 Giga models

1000BASE-SX
Fibra Multimodo ....(MMF).
Láser 850 nm.
Distancia < 550 m.

1000BASE-LX
Fibra Multimodo (MMF) y Fibra Monomodo (SMF).
Láser 1310 nm.
Distancia < 10 km.

1000BASE-EX
Fibra SMF.
Láser 1310 nm.
Distancia < 40 km.

1000BASE-ZX
Fibra SMF.
Láser 1550 nm.
Distancia < 80 km.

1000BASE-CX
Cable STP (2 pares).
Distancia < 25 m.

and also por 10Giga standard MMF and SMF
-->
### Proposed Functionality

Expand Interface type selections.

**Comment by jorgeNeutrona** [comment]
https://github.com/netbox-community/netbox/blob/develop/netbox/dcim/choices.py

Could you explain which is the process to manually add optical interfaces o extended interfaces?

**Comment by DanSheps** [comment]
Thank you for your interest in NetBox. GitHub issues are intended for reporting reproducible bugs and requesting features, and must be submitted using one of the templates provided [here](https://github.com/digitalocean/netbox/issues/new/choose). For general discussion, questions, or assistance with installation issues, please post to our [mailing list](https://groups.google.com/forum/#!forum/netbox-discuss) instead.
