### ISSUE TITLE
Release notes link goes to 2.7 and not 2.8

### ISSUE THREAD

**Issue by markkuleinio** [netbox-community/netbox#4541]
### Change Type
[ ] Addition
[ ] Correction
[ ] Deprecation
[X] Cleanup (formatting, typos, etc.)

### Area
[ ] Installation instructions
[ ] Configuration parameters
[ ] Functionality/features
[ ] REST API
[ ] Administration/development
[X] Other

### Proposed Changes
The link in https://github.com/netbox-community/netbox/blob/develop/CHANGELOG.md leads to 2.7 release notes even though 2.8 is the latest series. Some shortcut apparently needs to be modified.

**Comment by jeremystretch** [comment]
The file links to https://netbox.readthedocs.io/en/stable/release-notes/, which is the permanent URL for the current stable docs. It does not change from one release to the next.

**Comment by markkuleinio** [comment]
Please click the URL, and you see that https://netbox.readthedocs.io/en/stable/release-notes/ goes to 2.7, not 2.8.

```
$ curl -s https://netbox.readthedocs.io/en/stable/release-notes/ | grep "Release Notes"
  <title>NetBox v2.7 Release Notes - NetBox Documentation</title>
    var mkdocs_page_name = "NetBox v2.7 Release Notes";
                <p class="caption"><span class="caption-text">Release Notes</span></p>
    <li>NetBox v2.7 Release Notes</li>
                <h1 id="netbox-v27-release-notes">NetBox v2.7 Release Notes</h1>
```
