### ISSUE TITLE
Rack unit tenants

### ISSUE THREAD

**Issue by kmorin18** [netbox-community/netbox#4547]
### Environment
N/A

### Proposed Functionality
Extend the "tenant" feature on a "per U" basis.

Currently, the "tenant" feature only allows users to assign a tenant to a full cabinet.
It would be nice to be able to set tenant X in U's 1-20 in rack A.

A workaround is to set a reservation, but it makes it so the reservation feature can't be used.

### Use Case
Allow  users to set tenants on a "per rack unit" basis. Practical for data center colocation providers.

### Database Changes
N/A

### External Dependencies
N/A

**Comment by jeremystretch** [comment]
Thank you for the suggestion, however this would be too stark a departure from the established data model. It is recommended to assign tenants to racks only when the entire rack belongs to the tenant; otherwise, the tenant assignment is done at the device level.
