### ISSUE TITLE
Netbox conflicting with Python standard library Lib/secrets.py

### ISSUE THREAD

**Issue by diddi-** [netbox-community/netbox#4553]
Netbox does not have a single root `netbox` package so anything inside `netbox/` will be considered a separate package in Python. For example the `secets` package in Netbox conflicts with Python standard library [`secrets`](https://docs.python.org/3.7/library/secrets.html).

### Environment
* Python version: 3.7.7
* NetBox version: 2.8.1

### Steps to Reproduce
1. Create a new custom script `1-test.py`
```from extras.scripts import Script
import secrets
class SecretScript(Script):
    def run(self, data):
        self.log_success(secrets.token_hex())
```
2. Browse to the script from web ui `http://localhost/extras/scripts/1-test/SecretScript/`
3. Hit `Run Script` button

### Expected Behavior
A `success` log with the message containing a random hex string, similar to
```
>>> import secrets
>>> secrets.token_hex()
'95d6e2a2460ffd2fed63d6a78a69ae5a5dd7bf2676e7cd393bc9e80bc261cbe9'
```

### Observed Behavior
Exception:
```An exception occurred: AttributeError: module 'secrets' has no attribute 'token_hex'```

**Comment by diddi-** [comment]
I discovered this while trying to build a Python package that our custom scripts will use. Having all directories under `netbox/` be their own top level packages make imports a bit awkward as Netbox rely on its own `secrets` package for example.

Would it be possible to have a structure like `netbox.secrets` instead?

**Comment by jeremystretch** [comment]
Fun fact: NetBox predates the standard `secrets` library, which was introduced in Python 3.6. We recently had to work around this conflict to accommodate a recent Django release, which you can see [here](https://github.com/netbox-community/netbox/commit/f1b042180536092fa99d67f55fe5d5ab280d0f69).

Unfortunately, I'm not sure there's a palatable solution to this problem. We would need to rename the `secrets` app, which obviously would be [quite disruptive](https://stackoverflow.com/a/8408131/2694522) and probably not worth the negligible gain.

**Comment by jeremystretch** [comment]
I'm going to close this issue as I don't think there's anything actionable in the immediate future. Might be worth revisiting down the road but unless the conflict escalates to a serious problem, renaming the app is unlikely to be worth the disruption to users.
