### ISSUE TITLE
Add Cx type power outlets

### ISSUE THREAD

**Issue by raddessi** [netbox-community/netbox#4554]
### Environment
* Python version:  3.6.2
* NetBox version:  2.7.11

### Proposed Functionality
There is a proprietary power outlet type introduced by ServerTech that accepts either a C14 or C20 connector, they refer to it as Cx. Article [here](https://www.legrand.us/aboutus/press-room/news/server-technologys-hdot-cx-future-proofs-data-center-pdu-investments.aspx). It is receptacle only so we would only need to add the outlet, no ports.

### Use Case
I would like to be able to doc these outlets without jumping through hoops. I actually wrote up the change and was about to send it as a PR before I saw the instruction to open a FR first. If you wish you can see that branch [here](https://github.com/raddessi/netbox/tree/master.cx-power-ports)

### Database Changes
None afaik, the only references to `C13` I saw were fields only.

### External Dependencies
None

**Comment by jeremystretch** [comment]
I'm going to add this under a new "proprietary" group. Doesn't seem right to add it under IEC 60320 since it's not part of the spec.

**Comment by raddessi** [comment]
That's what I had in my change isn't it?

**Comment by raddessi** [comment]
Love it, thanks!
