### ISSUE TITLE
color must be hexa-lowercase (in rack-roles)

### ISSUE THREAD

**Issue by hchybz** [netbox-community/netbox#4558]
### Environment
* Python version: Not Used
* NetBox version:  netbox (v2.7.10)
* CURL : simplest test

### Steps to Reproduce
1. No python needed
2. just a simple CURL POST command
3. curl -X POST "http://mynetbox.home/api/dcim/rack-roles/" -d '{ "name": "Spare2", "slug": "spare2", "color": "089abC", "description": "Spare Rack 2" }'

==> color names are not (yet) supported, neither "#00ff44", at leat "00FF44"
==> should be OK : html colors are accepted both in lowercase/uppercase 
==> should accept html syntax with # or colorname

{
    "id": 16,
    "name": "Spare2",
    "slug": "spare2",
    "color": "089abC",
    "description": "Spare Rack 2"
}

### Observed Behavior

{
    "color": [
        "Enter a valid hexadecimal RGB color code."
    ]

**Comment by jeremystretch** [comment]
This is expected behavior. Only lowercase hexadecimal RGB codes are accepted. There is no need to change this.
