### ISSUE TITLE
Broken repository link in CentOS PostgreSQL Database Installation 

### ISSUE THREAD

**Issue by tehmichalis** [netbox-community/netbox#4562]
### Change Type
[ ] Addition
[X ] Correction
[ ] Deprecation
[ ] Cleanup (formatting, typos, etc.)

### Area
[X ] Installation instructions
[ ] Configuration parameters
[ ] Functionality/features
[ ] REST API
[ ] Administration/development
[ ] Other

### Proposed Changes
In the PostgreSQL Database Installation for CentOS section there's a non working link.

Remove dead link to the CentOS PostgreSQL repo :
https://download.postgresql.org/pub/repos/yum/9.6/redhat/rhel-7-x86_64/pgdg-centos96-9.6-3.noarch.rpm

Replace it by the updated working link
https://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm

From https://www.postgresql.org/download/linux/redhat/

**Comment by jeremystretch** [comment]
Fixed in 6e2c68ef42da87eab9e198b12439e83c27b468a8
