### ISSUE TITLE
Allow non-unique cluster names

### ISSUE THREAD

**Issue by Sislik** [netbox-community/netbox#4565]
### Environment
* Python version:  3.7
* NetBox version:  2.8.0

### Proposed Functionality

Remove unique constrain in Virtualization/Clusters names, same like it was removed for Devices/VMs. There is already relations to Cluster Groups (Vcenter name for example) which allow unique relations.

### Use Case

In cases you have multiple vCenter enviroments on multiple sites, you can have same Cluster Names for VMware clusters.

**Comment by jeremystretch** [comment]
Duplicate of #1943
