### ISSUE TITLE
cannot add secrets on the secrets/secrets page.

### ISSUE THREAD

**Issue by ThomasADavis** [netbox-community/netbox#4566]
### Environment
* Python version: 

python v3.6
* NetBox version: 

netbox 2.8.1

### Steps to Reproduce
1.  Goto /secrets/secrets, there is no 'add' button.

### Expected Behavior

Able to visit that page, and add a secret, like other pages.

### Observed Behavior

The only way to add a secret is via the drop down menu.

**Comment by jeremystretch** [comment]
Secrets are added from the device view.
