### ISSUE TITLE
Trigger webhook on logic

### ISSUE THREAD

**Issue by andershagman** [netbox-community/netbox#4567]
### Environment
* Python version:  3.6.8
* NetBox version:  2.7.12

### Proposed Functionality
Trigger webhook on username or other jinja logic to just send a webhook if criteria is met.

### Use Case
To be able to send information back to Netbox without trigger a webhook loop when using webhook update. In my case we use webhook to update gateway and mask to an asset database from the IPAM IP address part.  At the same time we fetch the CI-name from the asset database and put that into Netbox IP address description field, if not populated. 

Today this triggers an update loop. I have used a hack to send an emty webhook if username eq "the system user" and therefore stops the loop but it still sends a hook.

### Database Changes
Probably

### External Dependencies
No

**Comment by jeremystretch** [comment]
This is beyond the feature's scope in NetBox. Webhooks are intentionally implemented so that NetBox always sends a request when a relevant event occurs. It is up to the receiver how to process that information.
