### ISSUE TITLE
URL port removed while redirecting device from rack

### ISSUE THREAD

**Issue by hakyildiz** [netbox-community/netbox#4570]
### Environment
* Python version: 3.6.8
* NetBox version: v2.8.1

There are devices in a rack. 
In the rack page (dcim/rack/{id}), when clik a device (to go to related device /dcim/devices/{id}/), in the url, port is removed. 
Thus can not be redireted to the related device url.

_http://{netboxip}:[port}/dcim/rack/1/_      then click a device,  then url becoming _http://{netboxip}/dcim/device/1/_

### Steps to Reproduce
1. In a rack page (_http://{netboxip}:{port}/dcim/rack/{id}/_)
2. Click to a device (on front page)
3.  Next URL is _http://{netboxip}/dcim/device/1/_  without port

### What did you expect to happen?
Redirect to the device url with port

### What happened instead?
Redirected to the device url without port

**Comment by jeremystretch** [comment]
You need to configure your HTTP server to pass the external port number to the WSGI backend. Consult your httpd's documentation for how to do this, or post to our [mailing list](https://groups.google.com/forum/#!forum/netbox-discuss) for assistance.
