### ISSUE TITLE
Docker Media Root Issue

### ISSUE THREAD

**Issue by Blackraz0r** [netbox-community/netbox#4574]
### Environment
* Python version: 3
* NetBox version: dont know, latest docker immage

### Steps to Reproduce
1. Fresh install via docker
2. try to upload picture. (for racks or for devices)

### Expected Behavior
i can upload the picture and attach it to the item

### Observed Behavior
i could not upload the picture
it looks like this:
![SfVhdms 1](https://user-images.githubusercontent.com/26622216/81038640-030ba980-8ea7-11ea-8a9e-f2d7ba72e0ef.jpg)

**Comment by DanSheps** [comment]
Thank you for your interest in NetBox. GitHub issues are intended for reporting reproducible bugs and requesting features, and must be submitted using one of the templates provided [here](https://github.com/digitalocean/netbox/issues/new/choose). For general discussion, questions, or assistance with installation issues, please post to our [mailing list](https://groups.google.com/forum/#!forum/netbox-discuss) instead.

**Comment by Blackraz0r** [comment]
i followed your templates for bugs, pls reopen this instead of forcing me to recreate a new one.

**Comment by jeremystretch** [comment]
This project does not provide Docker support. You want https://github.com/netbox-community/netbox-docker
