### ISSUE TITLE
./upgrade.sh fails when /usr/bin/python3 has too old version or does not exist

### ISSUE THREAD

**Issue by elsobrino** [netbox-community/netbox#4576]
### Environment
* Python version: 3.5 respectively 3.8.2
* NetBox version: 2.8.1

### Steps to Reproduce
1. run ./upgrade.sh when /usr/bin/python3 does not exist or has an version <= 3.5

### Expected Behavior
./upgrade.sh should use /usr/bin/env to determine the right python3 executable

### Observed Behavior
./upgrade.sh fails

**Comment by jeremystretch** [comment]
It is the user's responsibility to install a supported version of Python per the installation and upgrade documentation.

**Comment by elsobrino** [comment]
Well, what's the problem of using '/usr/bin/env python3' instead of hardcoding '/usr/bin/python3' as suggested in the PR?
