### ISSUE TITLE
Rack SVG rending oddity when 0U device assigned to an RU

### ISSUE THREAD

**Issue by 2bithacker** [netbox-community/netbox#4578]
### Environment
* Python version: 3.6
* NetBox version: 2.7.12

### Steps to Reproduce
1. Have a DeviceType with a 0U size
2. Assign a device of that type to a rack unit
3. View the Rack

### Expected Behavior

Not really sure what the correct representation of a 0U device in an RU should be, but at least it shouldn't alter the rendering of other devices in the rack.

### Observed Behavior

The 0U device is rendered oddly, with it's name halfway through a U boundary. 1U devices get duplicated in incorrect RUs. Larger devices get 1U dups.

Here's the SVG with the 0U device:
[broken-render.svg.gz](https://github.com/netbox-community/netbox/files/4582390/broken-render.svg.gz)

And with the 0U device changed to be 1U:
[corrected.svg.gz](https://github.com/netbox-community/netbox/files/4582391/corrected.svg.gz)

**Comment by jeremystretch** [comment]
I'm not able to reproduce this with the steps outlined above. It seems you need to:

1. Create a 1U device type
2. Install a device of that type in a rack
3. Modify the device type to be 0U
4. Render the rack SVG

**Comment by fsedano** [comment]
Hello folks - If the fix is to NOT allow a 0U size on a rack, that will break me.

My use case: I have 10s of Access Points in a particular shelf on a rack. They're really piled up, so they're in a rack but they're 0U.
Any suggestion here?

**Comment by jeremystretch** [comment]
@fsedano 0U devices may be assigned to a rack, just not to a specific position. This has always been the case; this fix merely addresses a condition in which the validation could be bypassed by modifying a device type that was previously 1U+.

**Comment by fsedano** [comment]
Thanks Jeremy - If it's not in a specific position, what do you suggest to use for this use case (i.e. a lot of small devices in a shelf in a position in the rack). I.e. raspberry PIs, access points, etc. We have multiple shelves per Rack, each of them at a given position, so we have like 30 RPis on each shelf.

**Comment by 2bithacker** [comment]
You could have a Device Type for a generic rack shelf with a number of device bays for the things on the shelf.

**Comment by fsedano** [comment]
> You could have a Device Type for a generic rack shelf with a number of device bays for the things on the shelf.

Thanks for the hint!
