### ISSUE TITLE
ID field filters for ipaddress, prefix and vlan

### ISSUE THREAD

**Issue by loa** [netbox-community/netbox#4580]
### Environment
* Python version:  3.7
* NetBox version:  2.8.1

### Proposed Functionality

Allow batch fetching of ipaddress, prefix and vlan resources.

### Use Case

Batch fetching

### Database Changes

N/A

**Comment by jeremystretch** [comment]
Thank you for the report. I've opened bug #4584 to more completely capture the scope of the root issue.
