### ISSUE TITLE
API example still using status=1

### ISSUE THREAD

**Issue by Haeki** [netbox-community/netbox#4582]
### Change Type
[ ] Addition
[x ] Correction
[ ] Deprecation
[ ] Cleanup (formatting, typos, etc.)

### Area
[ ] Installation instructions
[ ] Configuration parameters
[ ] Functionality/features
[ x] REST API
[ ] Administration/development
[ ] Other

The example under Overview/Filtering still uses the old status=1 option instead of the new status=active

**Comment by Haeki** [comment]
Also the example to get the available choices for a field isn't working for me.

**Comment by jeremystretch** [comment]
Addressed in 3baf983e
