### ISSUE TITLE
Export CSV file with multiple lines in comments

### ISSUE THREAD

**Issue by thoms27** [netbox-community/netbox#4585]
### Environment
* Python version: 3.6
* NetBox version: 2.8.0

### Steps to Reproduce
When you export circuits from provider, and a circuit has multiple lines (with  2 spaces a the end of the line) in his comment field, a new line is created.

### Expected Behavior
All lines in the comment field should be in the same column.

### Observed Behavior
The others lines in the comment field create new lines in the export csv.

**Comment by jeremystretch** [comment]
This is expected behavior. This is how line breaks within a column are expressed in CSV format. The string is encapsulated inside double quotes.
