### ISSUE TITLE
Site icon / banner / color customization

### ISSUE THREAD

**Issue by fsedano** [netbox-community/netbox#4590]
### Environment
* Python version:  3.6.9
* NetBox version:  2.7.11

### Proposed Functionality

A mean to customize the look and feel of the page. The use case is:

2 Netbox instances, prod and staging. 
It's extremely easy to change things on the prod instance when you want the staging, since the screens look exactly the same. Just being able to change anything to make the staging environment different (differetn color, different logo...) would avoid a lot of confusion.

### Use Case
See above - Different Netbox environments.

### Database Changes
no

### External Dependencies
no

**Comment by jeremystretch** [comment]
Sounds like you want the `BANNER_TOP` and `BANNER_BOTTOM` [configuration settings](https://netbox.readthedocs.io/en/stable/configuration/optional-settings/#banner_top).
