### ISSUE TITLE
1:1 patch panels fail when between 1:n panels

### ISSUE THREAD

**Issue by steffann** [netbox-community/netbox#4591]
### Environment
* Python version: 3.6.9
* NetBox version: 2.8.2

### Steps to Reproduce
1. Disable any installed plugins by commenting out the `PLUGINS` setting in
   `configuration.py`.
2. Create the following setup:

```
                1                                           2
[Device 1] -----------+                               +----------- [Device 2]
      Iface1          |                               |          Iface1
                  FP1 |       3               4       | FP1
                  [Panel 1] ----- [Panel 5] ----- [Panel 2]
                  FP2 |  RP1     RP1     FP1     RP1  | FP2
      Iface1          |                               |          Iface1
[Device 3] -----------+                               +----------- [Device 4]
                5                                           6
```

3. get `Exception: Invalid position for Rear Port 1 (1 positions): 2)`

When writing this issue I created the cables in numerical order, but the order of creation of the cables doesn't really matter. As soon as cables 3 and 5 are in place, NetBox will try to trace the connection from device 3 to determine what its connected endpoint is, and it will raise the exception upon reaching panel 5.

### Expected Behavior
I expected the front ports of panel 1 to correspond to the front ports of panel 2.

### Observed Behavior
NetBox tries to map the front ports of panel 1 to the front ports of panel 5, which doesn't work because it is a 1:1 pass-though panel.

**Comment by steffann** [comment]
For those looking at #3193 and #4548, this is a related issue. I think (hope) this closes the last case where 1:1 patch panels confuse the trace. 🤞🏻

**Comment by jeremystretch** [comment]
@steffann Please extend the recreation steps above to specify exactly how the exception is triggered. Does it occur when replicating the topology, or when initiating a trace? If the later, from what termination are you tracing?

**Comment by steffann** [comment]
It occurs when creating the topology, when the signal handler does a trace after a cable is created. In the example above it occurs when creating cable 5.

The attached PR has a test case that creates the described topology: https://github.com/steffann/netbox/blob/8ff65591d51090b2283bbe912d8f8cd7c1840e69/netbox/dcim/tests/test_models.py#L626

**Comment by steffann** [comment]
The signal handler runs outside the transaction by default, so even though an exception is raised the cable has already been created. Therefore we can still trace from the endpoints:

Behaviour when doing a trace from device 3:
- arrive at Panel 1 through FP2: push 2 into the stack
- arrive at Panel 5 through RP1: pop 2 from the stack
- raise exception because Panel 5 only has 1 position

When tracing from device 4:
- arrive at Panel 2 through FP2: push 2 into the stack
- arrive at Panel 5 through FP1: push 1 onto the stack
- arrive at Panel 1 through RP1: pop 1 from the stack
- arrive at device 1 instead of device 2

**Comment by jeremystretch** [comment]
> It occurs when creating the topology

It's important to spell out the exact steps taken to reproduce the error in the initial report. This allows users troubleshooting an issue in the future to determine whether they've run into the same bug. Saying "Create the following setup" isn't sufficiently detailed as there's a possibility that a different series of steps can arrive at a completed topology without triggering the bug. Please call out the order in which each link is established so that it will be clear to a user how exactly the bug is triggered.

**Comment by steffann** [comment]
The order of creation doesn't really matter. If you want a fixed order then let's assume creation off the cables in numerical order, but any order that causes a trace from device 3 to determine its connected endpoint will cause the exception.

**Comment by steffann** [comment]
This bug does not occur anymore in v2.8.7
