### ISSUE TITLE
Please support ldap bind with users credentials

### ISSUE THREAD

**Issue by ruben-herold** [netbox-community/netbox#4596]
### Environment
* Python version:  3.6.8
* NetBox version:  2.8.3

Please support ldap bind with the credentials from the login from:

Here an example from an other application (kanboard.org):

This method uses the credentials provided by the end-user.

For example, Microsoft Active Directory doesn’t allow anonymous browsing by default and if you don’t want to use a proxy user you can use this method.

define('LDAP_BIND_TYPE', 'user');
define('LDAP_USERNAME', '%s@yourdomainlocal');
define('LDAP_PASSWORD', null);
In this case, the constant LDAP_USERNAME is used as a pattern to the ldap username, examples:

%s@kanboard.local will be replaced by my_user@kanboard.local
KANBOARD\\%s will be replaced by KANBOARD\my_user

This would not require to configure ldap credentials in netbox for better security.

**Comment by hSaria** [comment]
First, your question is better suited for the [mailing list](https://groups.google.com/forum/#!forum/netbox-discuss). 

Second, NetBox uses [django-auth-ldap](https://github.com/django-auth-ldap/django-auth-ldap), for LDAP authentication, so you should check out the in-depth [documentation](https://django-auth-ldap.readthedocs.io/en/latest/) of that project.

And finally, the authentication method you're referring to is called **Direct Bind** which is already supported (see the [documentation](https://django-auth-ldap.readthedocs.io/en/latest/authentication.html)). I used it in a deployment before and can tell you that it works. As the ticket doesn't conform to the appropriate format, I won't put the exact configuration that you're looking for (that would only encourage raising more questions as GitHub issues as opposed to using the [mailing list](https://groups.google.com/forum/#!forum/netbox-discuss) which is meant for exactly that).
