### ISSUE TITLE
ipam/prefixes not persisting requests

### ISSUE THREAD

**Issue by spirrello** [netbox-community/netbox#4597]
### Environment
* Python version:  3.7.3
* NetBox version:  2.8.2
* Helmchart: bootc/netbox-chart (2.1.0)

**This is a brand new install**

### Steps to Reproduce
Using Python 3 to automate the process of loading prefixes:

prefix = {"prefix": "10.1.0.0/24", "vrf": "xyz1"}
headers = { 'Authorization' : 'Token ' + netboxAPIToken } 
r = requests.post('https://mysite.com/netbox/api/ipam/prefixes', headers=headers, data = prefix, timeout=5)

Output:

```

{'count': 1, 'next': None, 'previous': None, 'results': [{'id': 15, 'family': {'value': 4, 'label': 'IPv4'}, 'prefix': '10.0.0.0/8', 'site': None, 'vrf': {'id': 1, 'url': 'http://mysite.com/netbox/api/ipam/vrfs/1/', 'name': 'xyz1', 'rd': None}, 'tenant': None, 'vlan': None, 'status': {'value': 'active', 'label': 'Active', 'id': 1}, 'role': None, 'is_pool': True, 'description': '', 'tags': [], 'custom_fields': {}, 'created': '2020-05-06', 'last_updated': '2020-05-06T22:31:16.706282Z'}]}
```

### Expected Behavior

My expectation is that the submitted prefix in my request would be persisted.

### Observed Behavior

The existing subnet of 10.0.0.0/8 is returned in the HTTP response.   If I delete the existing 10.0.0.0/8 prefix, I receive the following response.

{'count': 0, 'next': None, 'previous': None, 'results': []}

**Comment by jeremystretch** [comment]
Thank you for your interest in NetBox. GitHub issues are intended for reporting reproducible bugs and requesting features, and must be submitted using one of the templates provided [here](https://github.com/netbox-community/netbox/issues/new/choose). For general discussion, questions, or assistance with installation issues, please post to our [mailing list](https://groups.google.com/forum/#!forum/netbox-discuss) instead.
