### ISSUE TITLE
Support for custom fields on cables

### ISSUE THREAD

**Issue by ananace** [netbox-community/netbox#4600]
### Environment
* Python version:  3.7.7
* NetBox version:  2.8.1

### Proposed Functionality

Extend custom fields to also support attaching them to cables.

### Use Case

Our network technicians would like to be able to add some additional requirements on planned - and connected - cables, for example SFP identities for direct-attach cables.

**Comment by jeremystretch** [comment]
We are not currently entertaining proposals to expand the application of custom fields. Please see [the FAQ](https://github.com/netbox-community/netbox/wiki/Frequently-Asked-Questions#can-we-add-custom-fields-to-more-models).

**Comment by bT0mm** [comment]
It's an issue for my organization too, we need the ability to add custom field to cables.
In our case, different groups are sometimes responsible for providing and installing cords and cables, we need a way to document that.

Please reconsider expanding application of custom fields.
Thanks for your work.

**Comment by robbagithub** [comment]
We require to assign security classification to

**Comment by ivanqray** [comment]
We also need to add this feature. To mark the employee and the date of the cable installation...

**Comment by JonasKs** [comment]
>  The relevant distinction is that primary models have dedicated views (e.g. `/dcim/devices/<pk>/` for a device) whereas secondary models do not

@jeremystretch, `dcim/cables/<pk>/` exists, though. We also want to add a few custom fields to the `cable` object.
