### ISSUE TITLE
Display interface type for source and target interfaces in connection screen

### ISSUE THREAD

**Issue by ananace** [netbox-community/netbox#4601]
### Environment
* Python version:  3.7.7
* NetBox version:  2.8.1

### Proposed Functionality

The cable connection display currently only shows the direct names of interfaces/ports, it would be useful to also include the type of the interface/port in both the source and the target selection as well.

### Use Case

Connecting cables between devices with many different types of connectors - for example mixed SFP/copper NICs - can be confusing when the name doesn't also include the port type information. Including the port types as well would make it more obvious for people which connections would be possible/valid.

A quick mockup;
![Screenshot_20200507_163808-1](https://user-images.githubusercontent.com/534460/81307866-6a7d5100-9081-11ea-9de4-34b4b21886da.png)

**Comment by jeremystretch** [comment]
Unfortunately the API-driven form widgets we have in place do not allow for this sort of customization. This is the sort of thing we would need a legitimate UI framework like React or Angular to support. We'll get there one day I'm sure, but it's still a long way off.
