### ISSUE TITLE
Marking prefixes as fully allocated

### ISSUE THREAD

**Issue by ChrisDeh** [netbox-community/netbox#4609]
### Environment
* Python version:  3.8.2
* NetBox version:  2.8.3

### Proposed Functionality
Adding an option to a prefix, for marking every IP within this prefix as "in use" - like there is every IP within the prefix created. Especially for IPv6 prefixes were it is impossible to create every IP within a prefix this could be a solution to document the prefix is fully allocated and can't be used. In the prefix-list view, the Utilization Percentage would be shown as 100%, if the option is used.

### Use Case
This can be used for example to document IPv6 Prefixes used for DHCP Prefix Delegation to Customers. When speaking about IPv4 Prefixes it is possible to create every IP-Address within a Prefix and define it as "DHCP" - this is not possible with IPv6 cause would decrease netbox Performance massively.

**Comment by jeremystretch** [comment]
I do want to note that prefix utilization can be calculated in two ways: For container prefixes, it's calculated based on the number and size of child prefixes. For others, it's calculated based on the number of child IP addresses. If implemented, this flag would imply 100% utilization for either case as appropriate.

**Comment by v0tti** [comment]
I would like to start working on this issue as we need this feature ourself.

As I am not very experienced with Django projects, feedback is very welcome. My current status corresponds to my [fork](https://github.com/v0tti/netbox). Should I create a WIP pull request?

An important consideration is with available IP addresses and available prefixes. Should they be returned as available even if this flag is set?

**Comment by jeremystretch** [comment]
@v0tti No work will be accepted on this issue yet as it is still awaiting milestone assignment.

**Comment by ChrisDeh** [comment]
Are there news regarding a Milestone for this Issue?
