### ISSUE TITLE
Toggle option: IP address: Direct link / Netbox link

### ISSUE THREAD

**Issue by arnoudrut** [netbox-community/netbox#4612]
### Environment
* Python version:  v3.6.9
* NetBox version:  v2.6.11

### Proposed Functionality
When toggled ON, clicking a device's IP address, under interfaces, would open a tab, browsing to the IP address, instead of opening the IP address's Netbox page.

### Use Case
Useful to have 'turned on' in practical cases, like in case of a server crash, to easily jump from looking up the internal IP address to actually connecting to the device's browser based Remote Access window.
As it would be proposed to be a toggle, current use wouldn't be affected.

### Database Changes
No, there's no need for any database changes to add this functionality.

**Comment by sdktr** [comment]
I think this is a slippery-slope to a whole set of link behaviors that will be specific to one or another use case. 
Maybe you want to resort to the Netbox Smart Links? They can lookup any property from the model displayed (like mgmt IP of a device) and build a link to that. We use that to generate SSH and HTTPS links to a device mgmt IP.

In any case, this won't get accepted as a feature request in the current form. A new FR to 'display _interface_ -level smart links within the _device_ GUI' could be attempted (assuming smart links are already available on interface level anyway)

**Comment by sdktr** [comment]
OR: you can create a smart link on the device level that points to the IP-address  of a(fixed) interface name for the link destination.

Someone with more intimate knowledge of the model can propably help out with that on the mailinglist, I guess a syntax like the below  _could_ work:

`{{ obj.interface['IPMI'].ip_address[0] }}`

**Comment by jeremystretch** [comment]
As @sdktr points out, this is precisely the time of use case [custom links](https://netbox.readthedocs.io/en/stable/additional-features/custom-links/) were introduced to address.
