### ISSUE TITLE
Cannot add tags to config contexts

### ISSUE THREAD

**Issue by ebusto** [netbox-community/netbox#4613]
### Environment
* Python version: 3.6.9
* NetBox version: 2.8.3

### Steps to Reproduce
1. Create a new configuration context, and attempt to add an existing tag.

This is reproducible on DanSheps's [demo instance](https://master.netbox.dansheps.com).

### Expected Behavior
The configuration context to be successfully created.

### Observed Behavior
The following exception:
```
<class 'ValueError'>

Field 'id' expected a number but got 'hpe'.
```

**Comment by jeremystretch** [comment]
Related to #4527?
