### ISSUE TITLE
ConsolePort and ConsoleServerPort disconnect generates inconsistent webhooks.

### ISSUE THREAD

**Issue by karrots** [netbox-community/netbox#4614]
### Environment
* Python version: 3.7.7
* NetBox version: 2.8.3

### Steps to Reproduce
1. Disable any installed plugins by commenting out the `PLUGINS` setting in
   `configuration.py`.
2. Create a device with a console port
3. Create a device with a console server port
4. Create webhook attached to **DCIM > console server port**
4.1. Type: update
4.2. Method PUT (though this doesn't matter)
5. Navigate to either the console port or console server port and click the green connect button.
6. Disconnect the two ports

### Expected Behavior
1. Single webhook invocation
2.  `connected_endpoint`, `connection_status`, and `cable` filled fully with data or fully `null`

### Observed Behavior
Connect operation triggers 3 identical webhook invocations.

Remove cable operation triggered from the `ConsolePort` port will create 2 invocations the first showing update with `cable` set to `null` but still showing the `connected_endpoint` and `connection_status` with data. 
The second showing `connected_endpoint`, `connection_status`, and `cable` as `null` (disconnected).

Remove cable operation triggered from the `ConsoleServerPort` port will cause one invocation with data showing `cable` and `connected_endpoint` but the `connection_status` still shows as connected.

**Comment by jeremystretch** [comment]
Please specify the stable NetBox release on which this issue may be replicated.

**Comment by karrots** [comment]
v2.8.3

**Comment by jeremystretch** [comment]
I need to revisit this for v2.10 now that #4900 has been completed.

**Comment by jeremystretch** [comment]
This has been resolved as part of the work on #4900 for the upcoming v2.10 release.
