### ISSUE TITLE
Expanded view for Prefixes doesn't display hierarchy

### ISSUE THREAD

**Issue by abrahamvegh** [netbox-community/netbox#4617]
### Environment
* Python version: 3.7.3
* NetBox version: 2.8.3

### Steps to Reproduce
Create a prefix that is a child of another prefix. e.g. `203.0.113.0/24` and `203.0.113.0/25`

### Expected Behavior
When viewing the list with the ‘Expand’ mode turned on, the prefixes used to display with an indication of their hierarchy.

### Observed Behavior
All prefixes display at the same level in the list, making hierarchy less obvious.
![Screen Shot 2020-05-10 at 3 21 56 AM](https://user-images.githubusercontent.com/53161/81493332-92c9a300-926d-11ea-9b77-278e5201c130.png)
![Screen Shot 2020-05-10 at 3 22 02 AM](https://user-images.githubusercontent.com/53161/81493336-96f5c080-926d-11ea-88df-e5e3720db3eb.png)

### Notes
I’m not sure exactly when this broke, but I'm pretty confident it was very recent, perhaps something in #492?

**Comment by jeremystretch** [comment]
I can confirm that this was broken by the change in #492. It seems that calling `prefetch_related()` on the queryset _after_ `annotate()` wipes out the annotations, though I can't figure out why. AFAIK this shouldn't happen, but we may have run into some obscure caveat of the ORM.

**Comment by jeremystretch** [comment]
So we're not actually using `annotate()` to do this, but rather some convoluted logic in the `annotate_depth()` method on PrefixQuerySet. It's probably best to address this directly (which is already long overdue) rather than coming up with a workaround.

Marking this as blocked by #4639.

**Comment by jeremystretch** [comment]
I spent too much time today digging into #4639 and I'm afraid it isn't going anywhere soon. Going to throw in a "meh" workaround for an immediate fix for the UI.
