### ISSUE TITLE
Typo in CentOS Installation instruction

### ISSUE THREAD

**Issue by fgadot** [netbox-community/netbox#4618]
### Change Type
[ ] Addition
[ X] Correction
[ ] Deprecation
[ ] Cleanup (formatting, typos, etc.)

### Area
[X ] Installation instructions
[ ] Configuration parameters
[ ] Functionality/features
[ ] REST API
[ ] Administration/development
[ ] Other

In the CentOS Section, the documentation regarding adding a net box user says to:
`adduser --system --group netbox`

while it should be
`adduser --system -gid netbox netbox`

Since I'm installing this on CentOS 8, and actually discovered Django a couple of months ago, I'd love to participate in the project and do my first pull request with this issue.

**Comment by BirknerAlex** [comment]
Correct, ran into the same problem and solved it on the same way.
