### ISSUE TITLE
LDAP Install issue with Install django-auth-ldap

### ISSUE THREAD

**Issue by Gorrah** [netbox-community/netbox#4626]
Setting this up on a CentOS 8 box. I've gotten all of the rest of the steps configured and running, but am unable to set up LDAP authentication. I get a large amount of red text when running the 
 cd /opt/netbox/
 source venv/bin/activate
(venv) # pip3 install django-auth-ldap

The error I get is this:
Collecting django-auth-ldap
  Using cached django_auth_ldap-2.1.1-py3-none-any.whl (20 kB)
Collecting python-ldap>=3.1
  Using cached python-ldap-3.2.0.tar.gz (367 kB)
Requirement already satisfied: Django>=1.11 in ./venv/lib/python3.6/site-packages (from django-auth-ldap) (3.0.6)
Requirement already satisfied: pyasn1>=0.3.7 in ./venv/lib/python3.6/site-packages (from python-ldap>=3.1->django-auth-ldap) (0.4.8)
Requirement already satisfied: pyasn1_modules>=0.1.5 in ./venv/lib/python3.6/site-packages (from python-ldap>=3.1->django-auth-ldap) (0.2.8)
Requirement already satisfied: sqlparse>=0.2.2 in ./venv/lib/python3.6/site-packages (from Django>=1.11->django-auth-ldap) (0.3.1)
Requirement already satisfied: asgiref~=3.2 in ./venv/lib/python3.6/site-packages (from Django>=1.11->django-auth-ldap) (3.2.7)
Requirement already satisfied: pytz in ./venv/lib/python3.6/site-packages (from Django>=1.11->django-auth-ldap) (2020.1)
Could not build wheels for python-ldap, since package 'wheel' is not installed.
Could not build wheels for Django, since package 'wheel' is not installed.
Could not build wheels for pyasn1, since package 'wheel' is not installed.
Could not build wheels for pyasn1-modules, since package 'wheel' is not installed.
Could not build wheels for sqlparse, since package 'wheel' is not installed.
Could not build wheels for asgiref, since package 'wheel' is not installed.
Could not build wheels for pytz, since package 'wheel' is not installed.
Installing collected packages: python-ldap, django-auth-ldap
    Running setup.py install for python-ldap ... error
    ERROR: Command errored out with exit status 1:
     command: /opt/netbox/venv/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-p0_pqro5/python-ldap/setup.py'"'"'; __file__='"'"'/tmp/pip-install-p0_pqro5/python-ldap/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-vkpxknoj/install-record.txt --single-version-externally-managed --compile --install-headers /opt/netbox/venv/include/site/python3.6/python-ldap
         cwd: /tmp/pip-install-p0_pqro5/python-ldap/

I'm a newbie when it comes to linux stuff, having only really been in it for a year at most, and I'm unsure what I should be looking for here.

**Comment by lampwins** [comment]
Thank you for your interest in NetBox. GitHub issues are intended for reporting reproducible bugs and requesting features, and must be submitted using the template provided [here](https://raw.githubusercontent.com/digitalocean/netbox/develop/.github/ISSUE_TEMPLATE.md). For general discussion, questions, or assistance with installation issues, please post to our [mailing list](https://groups.google.com/forum/#!forum/netbox-discuss).
