### ISSUE TITLE
Add support for Cisco StackPower

### ISSUE THREAD

**Issue by bhavikbhakta** [netbox-community/netbox#4627]
### Environment
* Python version:  3.6.2
* NetBox version:  2.8.3

### Proposed Functionality

Add Power Port option for Cisco Stackwise and allow connections between two.

### Use Case

Cisco Catalyst switches (3850/9300) allow for Power stacking similar to traditional StackWise ports.
https://www.cisco.com/c/dam/en/us/products/collateral/switches/mgx-8800-series-switches/C22_722458_00_stackpow.pdf

### Database Changes

Adding a new Interface type for PowerPorts or traditional interface.

**Comment by lampwins** [comment]
These are power outlets though, right? Not interfaces. I would think this can be modeled with existing power outlets/power ports and proper naming of the ports.

**Comment by bhavikbhakta** [comment]
There are two PowerStack ports on the back of each switch.  There is no difference in port-type.
It is not possible to do a Power Outlet to Power Outlet connection (or plug to plug).

Additionally, switches are able to detect if there is a connection between them (similar to an interface)

**Example output:**
`    Power Stack           Port 1  Port 1             Port 2  Port 2`
`SW  Name                  Status  Neighbor SW:MAC    Status  Neighbor SW:MAC`
`--  --------------------  ------  ----------------   ------  ----------------`
`1   Powerstack-1          Conn    2:0[redacted]   Conn    2:0[redacted]`
`2   Powerstack-1          Conn    1:0[redacted]   Conn    1:0[redacted]`

This functionality is expandable to 4 switches in a ring topology or higher in a Star topology.

**Comment by DanSheps** [comment]
@lampwins They are a hybrid power outlet/inlet.  It also uses a special cable, the stackpower cable.  If we do add support for it, we would probably want to add the form factor to both power ports and power outlets.

**Comment by jeremystretch** [comment]
> They are a hybrid power outlet/inlet.

IMO this doesn't fit into the current model: NetBox models only deterministic power flow from origin to point of consumption. The power outlet/power port dichotomy doesn't allow for a bidirectional bus.

We could add PowerStack as a type for both power outlets and power ports, however it may not be clear to users how they should be populated on devices. Additionally, the connection of a power outlet to a power port implies that energy is flowing in one direction, when in reality it may be flowing in the opposite direction.

**Comment by DanSheps** [comment]
> Additionally, the connection of a power outlet to a power port implies that energy is flowing in one direction, when in reality it may be flowing in the opposite direction.

This is true, with powerstack it can flow in either direction per segment

**Comment by jeremystretch** [comment]
I'm going to close this as the StackPower product does not conform with traditional power delivery, and attempting to imitate it using directional power port and outlets is only going to lead to confusion.
