### ISSUE TITLE
Interface assignment get lost after IP address "create and add another"

### ISSUE THREAD

**Issue by JulianJacobi** [netbox-community/netbox#4629]
### Environment
* Python version: 3.7 (should be on any)
* NetBox version: 2.8.3

### Steps to Reproduce
1. Disable any installed plugins by commenting out the `PLUGINS` setting in
   `configuration.py`.
2. Navigate to any device with an interface
3. Click the + at the and of the interface row in the interface table to add an IP address to an interface
4. Fill out the form and click "Create and add another"

### Expected Behavior
- Another IP address form with filled out interface assignment appears.
- `interface` GET-parameter is set to the appropriate interface-ID.

### Observed Behavior
- Another IP address form without filled out interface assignment appears.
- `interface` GET-parameter is missing.

### Further information
With the implementation of clone able models in the `ObjectEditView.post()` function the redirection GET-parameters are build only from clone_fields and other maybe existing GET-parameters are fully ignored.

**Comment by jeremystretch** [comment]
Please specify the exact release on which this issue can be reproduced.

**Comment by JulianJacobi** [comment]
The issue first appeared in v2.8.0 but is already there in v2.8.3
