### ISSUE TITLE
Modification to apache.conf in folder "Contrib" for 502 bad gateway error

### ISSUE THREAD

**Issue by SudoBoomer** [netbox-community/netbox#4631]
### Change Type
[ ] Addition
[X ] Correction
[ ] Deprecation
[ ] Cleanup (formatting, typos, etc.)

### Area
[ ] Installation instructions
[X ] Configuration parameters
[ ] Functionality/features
[ ] REST API
[ ] Administration/development
[ ] Other

### Proposed Changes
I'm using CentOS Linux release 7.8.2003 (Core) with  Apache/2.4.6 (CentOS) and it a fresh install of Netbox 2.8.3 following installation procedure.

I used the apache.conf file provided in the "Contrib" folder and got frequent 502 (Bad Gateway) error. A simple refresh process the page correctly. I looked many forum to solve my problem and finished to solved my issue with these 3 parameters added to the httpd netbox.conf file.

I don't know if it's a combinations of the 3 parameters, if only one fixed the issue. Maybe you could run more tests.

- Added "ProxyBadHeader Ignore"
- Added "SetEnv proxy-sendchunked 1"
- Added " SetEnv proxy-nokeepalive 1"

All in the virtual host *:443

**Comment by jeremystretch** [comment]
> I don't know if it's a combinations of the 3 parameters, if only one fixed the issue. Maybe you could run more tests.

Unless you can point to a specific problem with the existing configuration file, which has been thoroughly tested, this is not an actionable issue.
