### ISSUE TITLE
Email: Implement TLS / SSL

### ISSUE THREAD

**Issue by minitriga** [netbox-community/netbox#4632]
### Environment
* Python version:  Not Required
* NetBox version:  2.8.4?

### Proposed Functionality
To add more of the Django email settings that are listed in [docs](https://docs.djangoproject.com/en/3.0/ref/settings/#email).

I specifically need `EMAIL_USE_TLS` and `EMAIL_USE_SSL`. 

### Use Case
This will allow a user to send an email to a service that uses TLS or SSL. Currently this is not supported and when using a provider like Gmail SMTP you have to manually add `EMAIL_USE_SSL=1` to `settings.py`.

### Database Changes
None.

**Comment by minitriga** [comment]
This might look something like:

`configuration.py`
```
EMAIL = {
    'SERVER': 'smtp.gmail.com',
    'PORT': 465,
    'USERNAME': 'username',
    'PASSWORD': 'pass',
    'TIMEOUT': 10,  # seconds
    'FROM_EMAIL': 'test@netbox.com',
    'SSL': True
}
```

`settings.py`
```
EMAIL_USE_SSL = EMAIL.get('SSL', None)
EMAIL_USE_TLS = EMAIL.get('TLS', None)
```

Not sure about the None bit.

**Comment by jeremystretch** [comment]
`EMAIL_USE_SSL` isn't a valid setting as far as I can tell; Django supports only `EMAIL_USE_TLS`.

We'll also add support for `EMAIL_SSL_CERTFILE` and `EMAIL_SSL_KEYFILE`
