### ISSUE TITLE
CentOS8 postgresql installation

### ISSUE THREAD

**Issue by fgadot** [netbox-community/netbox#4636]
### Change Type
[X ] Addition
[ ] Correction
[ ] Deprecation
[ ] Cleanup (formatting, typos, etc.)

### Area
[X ] Installation instructions
[ ] Configuration parameters
[ ] Functionality/features
[ ] REST API
[ ] Administration/development
[ ] Other

### Proposed Changes
While using CentOS8, the way to install the latest version of postgresql is not correct. The current documentation talks about CenOS 7.5 , and postgresql 9.6

Proposed update (add on to current CentOS 7.5):
With CentOS8, run the following command to install postgresql 10.x:
yum install postgresql postgresql-server postgresql-devel

**Comment by fgadot** [comment]
My apologies with all the comments. I am going through the install now on CentOS 8. 
The pg_hba.conf is in /var/lib/pgsql/data/pg_hba.conf  (not pgsql/9.6/)

**Comment by jeremystretch** [comment]
The documentation currently supports only CentOS 7.5. Please see #4507.

**Comment by fgadot** [comment]
I read and understand #4507 
Since I am going through the installation with CentOS 8, how about we update only the differences with CentOS 7.5 and CentOS 8. Not ALL the documentation needs to be redone, and it is not dramatically different. NetBox will work on it, it's just a couple of things here and there. I do not mind editing the documentation source file and submitting a new pull request if you want. One can say that CentOS 8 is "too new" , but in many IT departments (like mine), we test ahead. Whatever I write for the installation now will still be the same thing regardless of the version of CentOS 8.x. Minus start now, no?

**Comment by adamwoolhether** [comment]
@fgadot mind sharing what the other differences are, if any?

**Comment by fgadot** [comment]
@adamwoolhether Sorry, since @jeremystretch didn't seem interested, I just trashed my notes and figured out if I had to reinstall, I will figure it out at the time I will do it again...

**Comment by chicks-net** [comment]
@fgadot Thanks for trying.  I'm sorry there was no community on the Internet ready to preserve the knowledge you gained for us.

**Comment by adamwoolhether** [comment]
@fgadot no worries, it was helpful the bit you shared above. 

I'm kind of confused about the lack of willingness to improve documentation for specific distributions, despite the issue inquiries that come up and willingness of the community to help... The whole section on HTTP server setup explicitly state only ubuntu is included. which again isn't a big deal, but it feels incomplete.

but it's out of my control and isn't a huge issue. thanks for the help!

**Comment by adamwoolhether** [comment]
For anyone interested in an easy way to install NetBox on CentOS 8: I've had to do it a few times, so I decided to automate the process and put it into a playbook. 
Hope it's useful: https://github.com/adamwoolhether/NetBox4CentOS8

Thanks to @fagdot for the above info, helping with my initial install!
