### ISSUE TITLE
PowerPort maximum_draw and allocated_draw is limited to about 32KW.

### ISSUE THREAD

**Issue by ThomasADavis** [netbox-community/netbox#4641]
### Environment
* Python version: 3.6.8
* NetBox version:  2.8.2

### Steps to Reproduce
1. Disable any installed plugins by commenting out the `PLUGINS` setting in
   `configuration.py`.
2.  Create a PowerPort.
3.  Set maximum draw/allocated draw to a value greater than 32kw (ie, 33kw)

We have systems with power ports in the 400kw/300kw range coming in..

### Expected Behavior
setting maximum_draw/allocated_draw to a value higher than 32kw

### Observed Behavior

Maximum power draw (watts)
Ensure this value is less than or equal to 32767.

Allocated power draw (watts)
Ensure this value is less than or equal to 32767.

please change maximum_draw  and allocated_draw from PositiveSmallIntegerField to PositiveIntegerField in dcim/models/device_components.py

**Comment by jeremystretch** [comment]
Please specify your Python version as indicated by the template.

**Comment by jeremystretch** [comment]
Can you cite a real-world example of a piece of equipment that would be in-scope for modeling within NetBox that draws 32KW of power from a single power port?

**Comment by ThomasADavis** [comment]
Cray Shasta Cabinets have 3ea, 150amp, 480v feeds into them, feeding into 6 chassis's.

We have on scheduled delivery of cabinets that will use 300KW or 400KW (GPU based system).  They are water cooled, not air cooled.

We also have dual 550KVA/1.1KVA UPS's feeding the floor.

So, the goal is get a complete Cray Shasta system into netbox.

**Comment by jeremystretch** [comment]
That's a feed though, not an individual power port, correct? Power ports are assigned to discrete devices within a rack.

**Comment by ThomasADavis** [comment]
We use feeds for the substations, so we can model the panels and cabinets as devices.  Our panels are smart devices, not dumb.  Look at them as very expensive pdu strips mounted on the wall, with very expensive power connectors, at very high power (1600amps @ 480v)

I know power cascading calculations are not working.

It also allows us to also draw a power topology, and know what gets turned off when a panel/ups/pdu is shutdown.

**Comment by jeremystretch** [comment]
That explains it then. Power ports are intended to model individual power supplies within a device, hence the limitation. You can associate power feeds with racks though, which sounds like it should work for your use case.
