### ISSUE TITLE
Can't bulk import IP addresses using interface field

### ISSUE THREAD

**Issue by devasmith** [netbox-community/netbox#4649]
### Environment
* Python version: 3.7.3
* NetBox version: 2.8.4

### Steps to Reproduce
1. Disable any installed plugins by commenting out the `PLUGINS` setting in
   `configuration.py`.
2. Go to IPAM -> IP Addresses > Import
3. Add a new object containing interface field, e.g:
`address,status,device,interface`
`192.168.100.1/24,Active,Device1,Ethernet5/1`

### Expected Behavior
I exepcted to be able to import the new IP address.

### Observed Behavior
I received a page containg the following:

The complete exception is provided below:
<class 'KeyError'>
'interface_name'

**Comment by jeremystretch** [comment]
When specifying an interface, you also need to specify the device or VM to which the interface belongs.
