### ISSUE TITLE
Allow configuration of INTERNAL_IPS

### ISSUE THREAD

**Issue by glennmatthews** [netbox-community/netbox#4650]
### Environment
* Python version:  3.7.7
* NetBox version:  2.8.3

Netbox is running inside `docker-compose`.

### Proposed Functionality

The `django-debug-toolbar` should be visible when NetBox is running inside `docker-compose` with `DEBUG=True` and when NetBox views are accessed from localhost.

Currently this does not happen because requests are received as coming from the docker-compose bridge IP (e.g. 172.29.0.1 or 192.168.80.1, etc.), which is not in the hard-coded `INTERNAL_IPS` list defined in `settings.py` and used by `django_debug_toolbar` to decide whether to display the toolbar or not. Additionally, `INTERNAL_IPS` is not one of the properties that can be set in `configuration.py` to override the `settings.py` default values.

A simple solution would be to allow `INTERNAL_IPS` to be overridable with values in `configuration.py` and put the responsibility on the packager to supply the appropriate IP address(s) via `configuration.py`. As a side benefit, this feature would also make it easier for other deployment environments to specify any other `INTERNAL_IP` values desired:

```python
INTERNAL_IPS = getattr(configuration, 'INTERNAL_IPS', {"127.0.0.1", "::1"})
```

A slightly more complex but more automatic [solution](https://github.com/pydanny/cookiecutter-django/blob/master/%7B%7Bcookiecutter.project_slug%7D%7D/config/settings/local.py#L64) would be to have `settings.py` check whether it is running in Docker, and if so, automatically add the `x.x.x.1` gateway IP to `INTERNAL_IPS`:

```python
if DOCKER:
    import socket

    hostname, _, ips = socket.gethostbyname_ex(socket.gethostname())
    INTERNAL_IPS += [".".join(ip.split(".")[:-1] + ["1"]) for ip in ips]
```

A third [solution](https://stackoverflow.com/a/37027879), which may be acceptable for self-contained development and testing environments, would be to have `settings.py` import any `DEBUG_TOOLBAR_CONFIG` defined in `configuration.py`, which allows the configuration to specify that the debug-toolbar simply skips the `INTERNAL_IPS` check and adds the toolbar unconditionally to all views so long as `DEBUG=True`:

```python
DEBUG_TOOLBAR_CONFIG = {'SHOW_TOOLBAR_CALLBACK': lambda _request: DEBUG }
```

### Use Case

Standing up a development/testing environment for NetBox, such as when developing a plugin, can often be done with docker-compose, but not having access to the debug toolbar in this environment is hampering.

### Database Changes

None.

### External Dependencies

Most likely none.

**Comment by jeremystretch** [comment]
Given that we position the `DEBUG` configuration parameter as strictly for development purposes only, I think I'm okay with just hard-coding 

```python
'SHOW_TOOLBAR_CALLBACK': lambda _request: DEBUG
```

in `settings.py`. Doing so does force inclusion of the toolbar whenever `DEBUG` is enabled, but it's difficult to imagine a use case where that's undesirable.

**Comment by glennmatthews** [comment]
I'm fine with that, though I should add I've found that the simple approach didn't work perfectly with `manage.py test`, causing exceptions similar to #1474 to be thrown during the test (apparently because DEBUG is True when we're loading the settings, but False during the actual execution of tests, or something along those lines). I worked around this by explicitly disabling the toolbar during test execution, so the full solution ended up looking like:

```python
import sys
TESTING = len(sys.argv) > 1 and sys.argv[1] == "test"
DEBUG_TOOLBAR_CONFIG = {"SHOW_TOOLBAR_CALLBACK": lambda _request: DEBUG and not TESTING}
```

**Comment by jeremystretch** [comment]
I'm reminded that `INTERNAL_IPS` is not just a toolbar setting, but also controls things such as template context population, so it's not enough to just hack on `SHOW_TOOLBAR_CALLBACK`. I'm just going to expose it as a configurable option (using the current values as the default) and leave it to the user.
