### ISSUE TITLE
Instructions for both ubuntu and CentOS

### ISSUE THREAD

**Issue by TheDealman** [netbox-community/netbox#4653]
### Change Type
[ ] Addition
[ x ] Correction
[ ] Deprecation
[ ] Cleanup (formatting, typos, etc.)

### Area
[ x ] Installation instructions
[ ] Configuration parameters
[ ] Functionality/features
[ ] REST API
[ ] Administration/development
[ ] Other

### Proposed Changes
I noticed that the instructions could use a once over to ensure consistency. The instructions start off by listing commands for both ubuntu and CentOS don't continue to do so at certain points like on this page where it seems to only list ubuntu commands e.g. https://netbox.readthedocs.io/en/stable/installation/4-http-daemon/ i am trying to install netbox on CentOS so it's hard for me to follow along with the instructions

**Comment by jeremystretch** [comment]
The installation instructions are evaluated for accuracy regularly. This is not an actionable issue without more detail.
