### ISSUE TITLE
Device bulk import fails

### ISSUE THREAD

**Issue by dare-to-recurse** [netbox-community/netbox#4656]
### Environment
* Python version: 3.6.8
* NetBox version: v2.8.4 (clean install)

### Steps to Reproduce
1. Disable any installed plugins by commenting out the `PLUGINS` setting in
   `configuration.py`.
2. Create a device
3. Export the device through the export function on the device overview page
4. Delete the device from netbox
5. Open the device import form (tab "Racked Devices")
6. Paste the text from the export into the import form
7. Click the Submit button

### Expected Behavior
The import to succeed

### Observed Behavior
Import fails with error `Unexpected column header "rack_name" found.`

**Comment by jeremystretch** [comment]
This is expected behavior. `rack_name` is not a valid import header.
