### ISSUE TITLE
Importing interfaces error - The fields device, name must make a unique set. 

### ISSUE THREAD

**Issue by ognjen011** [netbox-community/netbox#4661]
### Environment
* Python version: 3.6.9
* NetBox version: 2.8.4

### Steps to Reproduce
1. When i run bulk import interfaces on a set of multiple devices i keep seeing this error:The fields device, name must make a unique set. 
2. Step two would be to update interfaces once created but i the first job never finishes. 
### Expected Behavior
Expected behaviour is that the interfaces are created. This used to work fine prior to 2.8.0 as far as i can tell because that is how i populated most of my netbox install. 

### Observed Behavior
Observed behaviour import hangs indefinitely and multiple errors pop up:  The fields device, name must make a unique set.

**Comment by jeremystretch** [comment]
Please specify the exact steps and import data that someone else can use to reproduce this bug.

**Comment by ognjen011** [comment]
I have a python script that creates a default interface 

        device_id = get_device_id(f"{host}", netbox)
            netbox.dcim.create_interface(
               name=f"{interface_name}",
               interface_type=1000,
               device_id=device_id,

**Comment by jeremystretch** [comment]
A script is not sufficient. Please update your original post to indicate the exact steps someone else can take to reproduce the reported issue, including the exact import data. Without the information, your issue is not actionable and will be closed.
