### ISSUE TITLE
Add nema-l21-30p choice for power-port

### ISSUE THREAD

**Issue by ryanmerolle** [netbox-community/netbox#4665]
### Environment
* Python version:  Example: 3.6.9
* NetBox version:  2.8.4

### Proposed Functionality

Add missing power-port connector type.

### Use Case

Devices that use a NEMA L21-30P power connector type require said connector type as a choice.

### Database Changes

NA

**Comment by jeremystretch** [comment]
There are several more NEMA types that we can add (see [this cheat sheet](http://blog.packetsar.com/wp-content/uploads/Power_and_Cooling_Cheat_Sheet.pdf)). I'm not sure why they were omitted originally. It may have been an oversight but I need to double check that we're not duplicating any types.
