### ISSUE TITLE
IP Address Bulk Import: KeyError interface_name

### ISSUE THREAD

**Issue by alexrsagen** [netbox-community/netbox#4667]
### Environment
* Python version: 3.8.2
* NetBox version: 2.8.4

### Steps to Reproduce
1. Disable any installed plugins by commenting out the `PLUGINS` setting in
   `configuration.py`.
2. Create a device named `Example` with an interface named `Main` (names are not relevant to bug)
3. Create a prefix `192.0.2.0/24`
4. Import the following CSV on the page "IP Address Bulk Import" (/ipam/ip-addresses/import/):
```csv
device,interface,status,address
Example,Main,Active,192.0.2.1/24
```

### Expected Behavior
An IP address `192.0.2.1/24` should have been created and assigned to interface `Main` on device `Example`.

### Observed Behavior
An error page showing the following content appears:
```
There was a problem with your request. Please contact an administrator.

The complete exception is provided below:

<class 'KeyError'>

'interface_name'
If further assistance is required, please post to the NetBox mailing list.
```

![msedge_8PkQYJ0l5b](https://user-images.githubusercontent.com/4870800/82425729-39d8e680-9a87-11ea-8bec-b8e136ac85a3.png)

**Comment by jeremystretch** [comment]
Duplicate #4649
