### ISSUE TITLE
Please add per-user favorites

### ISSUE THREAD

**Issue by patrakov** [netbox-community/netbox#4670]
### Environment
* Python version:  3.7.7
* NetBox version: 2.7.11

### Proposed Functionality

For each user, provide a way to star/unstar any objects that he has access to, and maybe also search queries. This starring should be specific for each user. Then, provide a quick way (e.g. a new menu link at the top) for the user to get a list of his starred objects, and in all searches, put them at the top if they match.

### Use Case

I work mostly with the internal infrastructure VMs but also have access to customer VMs, so need quick access to the 172.31.100.0/24 prefix in order to be able to assign IPs but don't mind if I need to click a lot to get to routers and customer vlans. My colleague works with customers but also has access to the internal infrastructure, so he should be able to go to our routers, customers' vlans and so on (better ask him), but doesn't care if he needs to find the infrastructure VM network through all the menus.

We don't care about each others' favorite objects and don't even want to know that they exist, and definitely don't want to pollute the objects with tags meaningful only for a specific user.

### Database Changes

Yes, we need to store personal favorite objects :)

### External Dependencies

None.

### Other information

I am aware of a closed feature request, #2640, which looks similar. However, the proposed "solution" with tags does not get the requirement that the favorites should be user-private.

**Comment by jeremystretch** [comment]
Why not use browser bookmarks?

**Comment by jeremystretch** [comment]
I don't think this fits as a core feature, though it sounds like a good candidate for a plugin.
