### ISSUE TITLE
Disable change log entry for empty modifications

### ISSUE THREAD

**Issue by charlesozanne** [netbox-community/netbox#4671]
### Environment
* Python version:  N/A
* NetBox version:  2.8.0

### Proposed Functionality
I would like to have an Optional Configuration Setting to either add an entry in change log even is there is no modification done by the user (default value and current feature)  or do not add a new change log entry when there is no modification with the previous status. 

### Use Case
As a netbox admin and when I checking the change log, I'm not interested to have change log information when these is "no changes". I would like to be able to filter or to avoid new entry when there is "No changes".

### Database Changes
No database schema change is required 

### External Dependencies
N/A

**Comment by jeremystretch** [comment]
The current changelog implementation does not allow this, there is no mechanism to compare the current (new) object with its previous version. NetBox cannot tell whether a change has occurred, only that one may have. This may be something we revisit in the future, but no major changes to the change logging middleware are currently planned.
