### ISSUE TITLE
Set default color for device and rack roles

### ISSUE THREAD

**Issue by jkldgoefgkljefogeg** [netbox-community/netbox#4672]
### Environment
* Python version:  python:3.7
* NetBox version:  2.8.4

### Proposed Functionality
when adding a device role, color is currently a mandatory field. I propose making this field optional and auto assign an unused color if none specified

### Use Case
When there are many device roles, it is difficult to pick a unique color.

### Database Changes
N/A

### External Dependencies
N/A

**Comment by jeremystretch** [comment]
The field must remain mandatory. What we can do is set a (non-configurable) default color, but NetBox will not assign colors randomly.

**Comment by jkldgoefgkljefogeg** [comment]
That works too.  
Just curious what is the history with device role label/color, I suspect some don't know what this is useful for

**Comment by czarnian** [comment]
Default color sounds good. Making it configurable in `UserPreferences` would cease discussion about what color to use.

**Comment by jeremystretch** [comment]
@czarnian we won't make it configurable, foremost because it would lead to a nondeterministic condition when creating a role via the REST API with an unspecified color.
