### ISSUE TITLE
add NEMA 1, NEMA 14 power ports/outlets

### ISSUE THREAD

**Issue by jkldgoefgkljefogeg** [netbox-community/netbox#4675]
### Environment
* Python version:  python:3.7
* NetBox version:  2.8.4

### Proposed Functionality
add NEMA 1 and NEMA 14

https://en.wikipedia.org/wiki/File:NEMA_simplified_pins.svg

relate discussion https://github.com/netbox-community/netbox/issues/792

https://github.com/netbox-community/netbox/blob/develop/netbox/dcim/choices.py

### Use Case
uncommon, but some UPS does have NEMA 1-15R outlets

### Database Changes
N/A

### External Dependencies
N/A

**Comment by jeremystretch** [comment]
Please specify the _exact_ values you are proposing to add for power ports and/or outlets.

**Comment by jkldgoefgkljefogeg** [comment]
* nema-1-15p port; nema-1-15r receptacle
  * nema-14-30p, nema-14-50p port; nema-14-30r, nema-14-50r receptacle

**Comment by DanSheps** [comment]
Should do the locking variants as well

**Comment by jeremystretch** [comment]
Super low-hanging fruit, shouldn't be hard to find a volunteer.
