### ISSUE TITLE
Device bulk import error "Unexpected column header" for rack_name

### ISSUE THREAD

**Issue by erdems** [netbox-community/netbox#4677]
### Environment
* Python version: 3.6.8
* NetBox version: 2.8.4

### Steps to Reproduce
1. Create a device including its position in an existing rack.
2. Export devices using web ui.
3. Delete device(s) and try to import from exported CSV.

### Expected Behavior
The import should be successful.

### Observed Behavior

Device import fails with the following message:

Unexpected column header "rack_name" found.

**Comment by jeremystretch** [comment]
This is expected behavior. The import form details the supported column headers.

**Comment by erdems** [comment]
Thanks Jeremy,

 Am I wrong to assume that since "rack" is supported (which references the existing rack name), import should work with "rack"?

 If so, then the problem becomes this error message, for an existing rack name:

Row 1 rack: Object not found.

**Comment by FRebbel** [comment]
> Thanks Jeremy, Am I wrong to assume that since "rack" is supported (which references the existing rack name), import should work with "rack"? If so, then the problem becomes this error message, for an existing rack name: Row 1 rack: Object not found.

I'm facing the exact same problem. When I try to import a device with a rack, I get:
* Row 1 rack: Object not found.

**Comment by FRebbel** [comment]
So I digged a bit deeper. There are two cases:

1. Rack not assigned to a Rack Group
2. Rack assigned to a Rack Group

In the first case, I can import a device with the rack name without a problem. The second case seems to require the rack group. When I add the rack group, the import works for me. 

Maybe this is intended behaviour? On first sight, this wasn't obvious for me.

**Comment by erdems** [comment]
My case was a bit different; I was merely trying to import the data I had exported the same day, from the same setup.

Just tested with 2.8.5 and whatever was the problem, it seems to have disappeared.

**Comment by bcohee** [comment]
> 1.  Rack not assigned to a Rack Group
> 2. Rack assigned to a Rack Group
 
For the first case I had to REMOVE the Rack Group field header if the rack is not assigned a Rack Group

@FRebbel 

For tracking:

https://github.com/netbox-community/netbox/issues/4970

https://github.com/netbox-community/netbox/issues/4429
