### ISSUE TITLE
Mark Subnet as Full Option for statistics

### ISSUE THREAD

**Issue by dmonetto** [netbox-community/netbox#4683]
### Environment
* Python version:  3.6
* NetBox version:  : 2.8.0

### Proposed Functionality
  I'm migrating phpIPAM to netbox, phpIPAM has an option to mark a subnet as a full subnet in terms of utilization.

For example:

192.168.0.0/30 - I can mark as a full subnet and the use of it is 100% no matter if our engineers added 192.168.0.1/30 ans 192.168.0.2/30. If the subnet is created the system automatically set that the subnet is full.

Other options is to create a bulk via API. the problem that I'm facing is that is the subnet is not complete. I need to created ips inside the subnet and netbox is giving differents % of utilization in comparisson with phpIPAM.

https://phpipam.net/api/api_documentation/ 

- Mark subnet as full for statistics options once subnet is created.
- Auto complete Subnet with IP once created.
- API bulk IP creation to complete the subnet.

**Comment by kobayashi** [comment]
Thank you for submitting your idea. Unfortunately, the proposed feature falls outside the scope of functionality that NetBox aims to provide. The usecase should not be part of Netbox. NetBox's intended role is a "source of truth" for network objects and related data. As NetBox is an open source application with limited development resources and a persistent backlog of existing work, it is crucial that we limit the scope of development to ensure it remains a maintainable project for many years to come. Thank you for your understanding.
