### ISSUE TITLE
Controlling of expiring things

### ISSUE THREAD

**Issue by Disinterpreter** [netbox-community/netbox#4686]
### Environment
* Python version:  3
* NetBox version:  2.8.0

### Proposed Functionality
Sorry I'll be rude, but I need the row where I can add things (licenses or ordered VDS or other) which can be expired over the time. 
Like it in ralph: 
![image](https://user-images.githubusercontent.com/3816155/82792234-bf89d700-9e77-11ea-89c1-2d69ec66e1a7.png)

### Use Case

I have several racks in DC. But sometimes we order some VDS or other things (even a hardware, for example a manufacturer send me the hardware for a test). And I need to control it.
It will be the best if I can put the the data into the row and looking of expiring of it.

### Database Changes

I didn't see your code, sorry. But I think about new model.

### External Dependencies
none

**Comment by DanSheps** [comment]
Netbox really isn't meant to track licenses or similar.  This would be something that someone could write a plugin for using the new plugin framework.
