### ISSUE TITLE
Retrieve oversusbcription of IP assigment or % utilization via API

### ISSUE THREAD

**Issue by jorgeNeutrona** [netbox-community/netbox#4687]
### Environment
* Python version:  3.6 
* NetBox version:  28011873b3d2 (v2.8.4)

Get subnet utilization via API for sanity check.

### Proposed Functionality

I would like to retrireve % utilization of Subnet fia API REST CALL. In migration scenarios is useful when a subnet is created and has childs vs the same subnet creation of prefix /32.

For example:

192.168.0.0/26
    192.168.0/29
    192.168.8/29
    192.168.16/29
    etc.

192.168.0.1/26
192.168.0.2/26
192.168.0.3/26
192.168.0.4/26
192.168.0.5/26

etc.

Once this scenarios ocurrs the utilization is more than 100% of the subnet. 

I would like to retrieve % of utilization or a way to debug or clean wrongs assignations.

### Use Case

Retrieve % utilization or a way to review oversubscriptions of IP assigments.

**Comment by kobayashi** [comment]
You can do it by calculating your subnet and result of `/ipam/prefixes/{id}/available-ips/`?

**Comment by jorgeNeutrona** [comment]
> You can do it by calculating your subnet and result of `/ipam/prefixes/{id}/available-ips/`?

Although I can retrieve and calculate, I need to retrieve de calculated value via NETBOX. I'm was seeing some rare values when an /30 is left available between other resevation.

is the calculated value stored? or the calculation is on the fly?
