### ISSUE TITLE
Scripts Run History

### ISSUE THREAD

**Issue by jmanteau** [netbox-community/netbox#4688]
### Environment
* Python version:  3.7.7
* NetBox version:  2.84

### Proposed Functionality
Add a history functionnality on scripts, logging the log outputs of previous runs.
I would add a new tab "Previous Runs" under each scripts view. This tab will be a table with a line per run linking to the log output for each run.

### Use Case
Today, changes inducted by scripts are kept in the individual objects changelog but there is no easy way for administrators to check for one script the previous runs and their outputs.
Standard changelog (90 days default) will be enough to go back in case of a check or analysis.

### Database Changes
As this implies to kept execution history and log output, new models will be involved.

### External Dependencies
None

**Comment by jmanteau** [comment]
PS: as an afterthough, this could be extended to reports or put in a generic way so that plugins could use this functionnality.

**Comment by jeremystretch** [comment]
NetBox does not retain the output of custom scripts, however as the author of the script you have the ability to save the output yourself in any format you like.
