### ISSUE TITLE
Expose choices of cable:termination_a_type and cable:termination_b_type

### ISSUE THREAD

**Issue by christianharendt** [netbox-community/netbox#4695]
### Environment
* Python version:  3.8.3
* NetBox version:  2.8.4

### Proposed Functionality
In older Netbox versions it was possible to get choices for cable:termination_a_type via this api-request:
```
GET '/api/dcim/_choices/'
...
"cable:termination_a_type": [
    {
      "value": "dcim.consoleport",
      "label": "console port"
    },
    {
      "value": "dcim.consoleserverport",
      "label": "console server port"
    },
    {
      "value": "dcim.interface",
      "label": "interface"
    },
...
```

But since #3416 it is not possible to get the choices for termination_a_type with the new OPTIONS request, as there are no choices listed:
```
OPTIONS '/api/dcim/cables/'
...
"termination_a_type": {
  "type": "field",
  "required": true,
  "read_only": false,
  "label": "Termination a type"
},
...
```

### Use Case
API users/developers would know which terminations exist.

### Database Changes
None

### External Dependencies
None

**Comment by sdktr** [comment]
If time is not an issue I’ll take a shot at it

> @christianharendt or @sdktr would one of you like to volunteer for this?

**Comment by jeremystretch** [comment]
@sdktr Can you provide an update on this please?

**Comment by jeremystretch** [comment]
This still needs an owner, it seems.

**Comment by sdktr** [comment]
Sorry that I missed this. If an additional couple of weeks are possible I’d still try and take an attempt at this.

**Comment by DanSheps** [comment]
It is alright, I think I have a solution for this
