### ISSUE TITLE
"add new" option for dropdown menus

### ISSUE THREAD

**Issue by alexjhart** [netbox-community/netbox#470]
Consider you are adding a new device (this applies to other contexts as well, but I'm using device as an example). One will need to set the role, manufacture, type, etc. If you don't have all of those things pre-created, you end up getting forced to fill out the form again after leaving the page to create them. Wouldn't you rather have a way to add those things on the fly so you can just continue setting up the device without the extra headache? If an "add new" option was available at the top of the list or a plus sign next to the dropdown, you could click that to get a modal box style pop up to create the missing option which triggers a dropdown list refresh on save.

**Comment by anthraxau** [comment]
ive fallen victim to this a few times

**Comment by chagara** [comment]
I have to agree. 1+

**Comment by mryauch** [comment]
+1 This has definitely been one of my biggest issues with having just set up the system and manually adding items while a newbie.  As it is now it's pretty much assuming you know everything that will be a required field ahead of time and have already set it up.

**Comment by jeremystretch** [comment]
This is something we should be able to support starting with v2.0, which introduces full write API support.

**Comment by alexjhart** [comment]
Good to hear, especially with the release of v2.0 :)

**Comment by tyler-8** [comment]
With the Select2 dropdown fields is this necessary anymore? Re-selecting the dropdown triggers a new API call which will pick up any newly created entries (in another tab for example).

**Comment by alexjhart** [comment]
Yes, it is still necessary. The workflow is still improved when you can create items that are missing without leaving the page/tab.

**Comment by DanSheps** [comment]
Just to save this for future:  https://stackoverflow.com/questions/38635800/i-need-to-add-add-new-item-option-in-select2/38655413

Various different approaches to "create new" in Select2

**Comment by jeremystretch** [comment]
The development burden for implementing this using the current UI is likely disproportionate to the value gained. Leaving this open for anyone who wants to volunteer. Otherwise, it will be reconsidered during a future overhaul of the UI.

**Comment by jeremystretch** [comment]
With the recent introduction of HTMX (see #8057), I think this is now a real possibility. More investigation is needed to see what's feasible but I'm confident we can come up with something.

**Comment by jeremystretch** [comment]
Disregard; this will be covered under #5858.
