### ISSUE TITLE
Plugin Tool Tip Doc Error

### ISSUE THREAD

**Issue by ryanmerolle** [netbox-community/netbox#4700]
Looks like doc pointers for view tool-tip need to be direct to a plugin directory.  It also looks like we need set a standard in the docs on how plugin developers create place the associated docs in their structure.  This is one of those bugs/feature request type issues.

### Environment
* Python version: 3.6.9
* NetBox version: 2.8.5

### Steps to Reproduce
1. Install Netbox Plugin
2. Within plugin page click tool-tip / doc question mark

### Expected Behavior
Display Plugin Documentation

### Observed Behavior
`Unable to load documentation, file not found: /opt/netbox/docs/<plugin_name>/<plugin_model>.md`

**Comment by jeremystretch** [comment]
This is caused by the `get_docs` template filter, which is used only in `templates/obj_edit.html`. This template is not provided as part of the plugins API.
