### ISSUE TITLE
Allow IP address assignment to console server ports

### ISSUE THREAD

**Issue by chris-mccoy** [netbox-community/netbox#4701]
Great software, thank you for working on it and opening to the community!  💯 

### Environment
* Python version:  3.6.9
* NetBox version:  2.8.4

### Proposed Functionality
Permit the user to assign an IP address to console server ports.

### Use Case
(This is Cisco-specific configurations, but other vendors easily apply)

As a network administrator, I wish to avoid logging into a console server first before choosing a line, so I use features such as [`ip alias`](https://www.cisco.com/c/en/us/td/docs/ios/termserv/command/reference/tsv_book.pdf), `rotary` and `ip ssh port 2001 rotary ...` to assign console ports directly to IP addresses.  This permits greater visibility into who owns the session using SSH which provides a username.  As is today, I could create a Virtual Interface for the corresponding TTY line, but it makes it difficult to trace IPs to console server ports using the UI.  It also makes scripting the NetBox data model into a configuration for the console server easier.

It would be nice to be able to assign an IP address to a console server port to make it easier to note which IPs are assigned to which equipment so cable-tracing is more evident.  It would be nice for this IP to be reflected in the connected device, but this isn't as necessary.

### Database Changes
As necessary to support feature.

### External Dependencies
None.

**Comment by jeremystretch** [comment]
Sorry, this would violate our design philosophy of modeling the real world: IP addresses are assigned only to interfaces, and software handles the transfer of data from interface to console server port. It would not make sense to map IP addresses to console ports directly.

**Comment by chris-mccoy** [comment]
Okay, thank you.

**Comment by wat-doing** [comment]
I agree with Chris' request.  Makes sense to document the IP address used to connect to the Console port.
I guess I'll just keep creating Serial OOB / Console ports as Interfaces.
