### ISSUE TITLE
Device link rack view adds additional '%', breaking the link.

### ISSUE THREAD

**Issue by erdems** [netbox-community/netbox#4703]
### Environment
* Python version: 3.6.8
* NetBox version: 2.8.5

### Steps to Reproduce
1. Add one rack and one device.
2. Assign device to anywhere in the rack.
3. Go to rack view (i.e. https://netbox/dcim/racks/1
4. Clicking on the device inside the rack gives the link.
 

### Expected Behavior

The link should not contain the %25 part.

### Observed Behavior
The redirection is to 'https://netbox/%25/dcim/devices/1', resulting in a "The requested page does not exist" error.

**Comment by jeremystretch** [comment]
This appears to be an error in your httpd configuration. Please see the [included config examples](https://github.com/netbox-community/netbox/tree/develop/contrib) to validate your config, and consider posting on our [mailing list](https://groups.google.com/forum/#!forum/netbox-discuss) if you need further assistance.

**Comment by erdems** [comment]
Hey Jeremy,

 Thanks for the reply. It seems the examples require apache 2.4.10 and centos7 is shipped with 2.4.6. I will sort it out.

 Cheers,
