### ISSUE TITLE
ValidationError when connecting multiple interfaces to one via a multi-position rear port

### ISSUE THREAD

**Issue by steffann** [netbox-community/netbox#4708]
### Environment
* Python version: 3.7.3
* NetBox version: 2.8.5

### Steps to Reproduce
1. Disable any installed plugins by commenting out the `PLUGINS` setting in
   `configuration.py`.
2. Create three devices (A, B, and C) each with at least one non-connected interface.
3. Create a device (X) with two front ports mapped to a single rear port with 2 positions.
4. Connect interface A to the first front port of X.
5. Connect interface B to the second front port of X.
6. Create a device (Y) with one rear port with one position mapped to a single front port
7. Connect interface C to the rear port of Y.
8. Connect the rear port of X to the front port of Y

Alternative that should produce the same result:
7. Connect interface C to the front port of Y.
8. Connect the rear port of X to the rear port of Y

### Expected Behaviour
No errors expected. When this would succeed, I would expect the connected endpoints of all three devices to be empty, as there is no single endpoint for the interface on device C.

### Observed Behavior
In step 8 you get ValidationError "Rear ports with multiple positions may only be connected to other rear ports". 

In the alternative version the ValidationError is "RP has 2 position(s) but RP has 1. Both terminations must have the same number of positions.".

Both are not expected, as the 1-on-1 RearPort/FrontPort is basically a cable extender.

**Comment by jeremystretch** [comment]
The issue title mentions an IntegrityError but the post makes no mention of an exception. Could you please clarify?

**Comment by steffann** [comment]
> The issue title mentions an IntegrityError but the post makes no mention of an exception. Could you please clarify?

You are right, they are ValidationErrors instead. Will fix!

**Comment by steffann** [comment]
The PR is currently being reviewed

**Comment by DanSheps** [comment]
Marking this as accepted so the bot goes away
