### ISSUE TITLE
Comments formatting is display as one long line of text

### ISSUE THREAD

**Issue by autonomic** [netbox-community/netbox#4709]
### Environment
* Python version: 3.6.8
* NetBox version: 2.8.5

### Steps to Reproduce
1. Create or edit circuit and in the comments section create text followed by a new lines (several separate lines of text
2. Click on create or update for that circuit
3. Now when viewing the circuit, the comments show as one long line, instead of separate lines.

### Expected Behavior
I expect to see multiple lines of text in the comments section

### Observed Behavior
Instead I'm seeing a long line of text. I'm also seeing this in other sections (e.g. Circuit Provider - NOC Contact). I think it affects section that allows you to have multiple lines of text.
![nb_editing](https://user-images.githubusercontent.com/13229225/83538866-2e37e780-a4ab-11ea-992a-3f9d22bc5aa5.png)
![nb_display_issue](https://user-images.githubusercontent.com/13229225/83538868-2ed07e00-a4ab-11ea-9d47-37e36f06f981.png)

**Comment by chicks-net** [comment]
This is how Markdown normally works.  Have you tried putting a blank link between them?

**Comment by lampwins** [comment]
This is the expected behavior. The comments field is formatted with markdown.

You need to add an additional blank line:
```
first line
still the first time

a new line
```

**Comment by autonomic** [comment]
How about other free form fields (e.g. **NOC Contact**)? When I add text to the NOC Contact field or any other free form field, it does the same thing with text.

Do all of these fields behave the same way? I seem to remember in past versions that the comments section and other fields used to display the text just as they are entered (with new lines).

**Comment by jeremystretch** [comment]
We changed the library used for rendering Markdown some time ago. The current behavior reflects what is defined in the Markdown specification.

All Markdown-enabled fields render in the same manner.
