### ISSUE TITLE
Standardize on naming for ContentType fields

### ISSUE THREAD

**Issue by jeremystretch** [netbox-community/netbox#4711]
### Proposed Changes
Update models in NetBox to use a standardized name for ForeignKey fields to the ContentType model. The name `object_type` is most appropriate IMO. Applicable fields include:

* dcim.Cable
  * termination_a_type
  * termination_b_type
* ~extras.CustomField~
  * ~obj_type~
* ~extras.CustomFieldValue~
  * ~obj_type~
* extras.CustomLink
  * content_type
* extras.ExportTemplate
  * content_type
* ~extras.Graph~
  * ~type~
* extras.ImageAttachment
  * content_type
* extras.ObjectChange
  * changed_object_type
  * related_object_type
* extras.Webhook
  * obj_type
* users.ObjectPermission
  * content_types (v2.9)

The proposal here is to rename fields named `type`, `obj_type`, or `content_type` to `object_type`. The Cable and ObjectChange models likely need no changes.

### Justification
* Standardizing on a common name readily conveys the purpose of the field.
* `object_type` is more accurate than `content_type` and more apparent than `obj_type`. (`type` alone should be avoided due to its status as a reserved word in Python.)

**Comment by DanSheps** [comment]
My view:

Standardization is good, where we can get away with it.  I know there are going to be places where we can (ObjectPermissions) but we can get close.

I would be worried however about how many instances we call the object_type (or the others) directly.  I don't think there is many but could be wrong.

**Comment by jeremystretch** [comment]
Thought about this some more. Seems fine to just change `obj_type` on CustomField and Webhook  to `content_types`, since these are ManyToManyFields. We can leave the rest as they are.
