### ISSUE TITLE
"Platform" field doesn't fully support lookup expression

### ISSUE THREAD

**Issue by eshcheglov** [netbox-community/netbox#4712]
### Environment
* Python version: 3.6.8
* NetBox version: 2.8.5

### Steps to Reproduce
1. Create Platform with any name. e.x: name: "Windows Server", slug:"windows-server"
2. Create device and set it platform to "Windows Server"
3. Try to apply **"nic"** lookup expression (__nic) to "platform" field:

```
GET /api/dcim/devices/?limit=0platform__nic=Windows

HTTP 200 OK
Allow: GET, POST, HEAD, OPTIONS
Content-Type: application/json
Vary: Accept

{
    "count": 1
```

However, regular "**n**" expression (__n) can be applied:
```
GET /api/dcim/devices/?limit=0&platform__n=windows-server

HTTP 200 OK
Allow: GET, POST, HEAD, OPTIONS
Content-Type: application/json
Vary: Accept

{
    "count": 0
```

### Expected Behavior
Devices with "Windows" in "Platform" parameter filtered out

### Observed Behavior
Devices with "Windows" in "Platform" parameter is still visible

**Comment by jeremystretch** [comment]
Per [the docs](https://netbox.readthedocs.io/en/stable/api/filtering/):

> Certain other fields, namely foreign key relationships support just the negation expression: n

`platform` is a ForeignKey field, from the Device model to the Platform model, as opposed to a CharField on the Device model. Thus, only basic negation is supported.
