### ISSUE TITLE
Update virtual machine's properties using Import

### ISSUE THREAD

**Issue by anutator** [netbox-community/netbox#4720]
### Environment
* Python version: 3.6.8
* NetBox version: 2.8.5

### Proposed Functionality

Virtual Machine Bulk Import -- ability to rewrite fields of existing virtual machines (vcpus,memory,disk). Accept import for machines with the same name. Besides it would be useful to have only one required  field - name (not cluster) if we import existing maсhines.

### Use Case
I have Ansible and check current Memory & hdd capacity, vcpu numbers using Ansible playbook and jinja template. I'd like to renew this sections using import, for example in Virtual Machine Bulk Import:

```
name,vcpus,memory,disk
balancer-01.nso.loc,2,1837,29
pgsql-01.nso.loc,8,15884,329
...
```
People will have fresh data even if ther added hdd/vcpu etc.

### Database Changes

No

### External Dependencies

No

**Comment by DanSheps** [comment]
The amount of work required to provide an update mechanism, I think, is not worth the value.  If you have a desire to update/import existing, I would suggest taking a look at the IP and/or scripting instead.

We have limited development resources and I don't think this is something we can commit development time to right now.  At the very least, it would be blocked until we complete #4347

**Comment by jeremystretch** [comment]
Bulk import is strictly for the creation of new objects only. NetBox provides a separate bulk edit function to address existing objects.
