### ISSUE TITLE
API - MAC address not found for Virtual interface on Virtual Machines, when requesting the API

### ISSUE THREAD

**Issue by etigui** [netbox-community/netbox#4731]
### Environment
* Python version: 3.6
* NetBox version: 2.8.4

### Steps to Reproduce
1. GET request to the route `/api/dcim/interfaces/?mac_address=<MAC>` for a virtual machine

### Expected Behavior

- Virtual machine : `https://XXXXXXX/virtualization/virtual-machines/335/`

![Screenshot from 2020-06-08 17-53-19](https://user-images.githubusercontent.com/32940684/84053459-382d7f00-a9b2-11ea-91b9-295747c93cb2.png)

- API output (`GET /api/dcim/interfaces/?mac_address=52:54:00:09:02:88`) :
```
HTTP 200 OK
Allow: GET, POST, HEAD, OPTIONS, TRACE
Content-Type: application/json
Vary: Accept
```
```
{
  "count": 1,
  "next": null,
  "previous": null,
  "results": [
    {
      "id": 9194,
      "virtual-machines": {
        "id": 335,
        "url": "https://XXXXXXX/api/virtualization/virtual-machines/335/",
        "name": "XXXXXXX",
        "display_name": "XXXXXXX"
      },
      "name": "XXXXXXX",
      "type": {
        "value": "XXXXXXX",
        "label": "XXXXXXX",
        "id": 0
      },
      "enabled": true,
      "lag": null,
      "mtu": null,
      "mac_address": "52:54:00:09:02:88",
      "mgmt_only": false,
      "description": "XXXXXXX",
      "connected_endpoint_type": null,
      "connected_endpoint": null,
      "connection_status": null,
      "cable": null,
      "mode": null,
      "untagged_vlan": null,
      "tagged_vlans": [],
      "tags": [],
      "count_ipaddresses": 0
    }
  ]
}
```
> Data anonymized with `XXXXXXX` for API output

### Observed Behavior
The MAC is present on the interface of the virtual machine, but because it is an `Virtual interface` I see no result.
- API output (`GET /api/dcim/interfaces/?mac_address=52:54:00:09:02:88`) :
```
HTTP 200 OK
Allow: GET, POST, HEAD, OPTIONS, TRACE
Content-Type: application/json
Vary: Accept
```
```
{
    "count": 0,
    "next": null,
    "previous": null,
    "results": []
}
```

**Comment by tyler-8** [comment]
If it's a virtual machine interface, try using `/api/virtualization/interfaces/?mac_address=`

**Comment by etigui** [comment]
> If it's a virtual machine interface, try using `/api/virtualization/interfaces/?mac_address=`

Ahh right, thanks ! :)
