### ISSUE TITLE
Merge report functionality into custom scripts

### ISSUE THREAD

**Issue by jeremystretch** [netbox-community/netbox#4735]
### Environment
* Python version: 3.6.9
* NetBox version: 2.8.5

### Proposed Functionality
Remove the reports feature from NetBox, to be replaced by custom scripts.

### Use Case
Reports were added in NetBox v2.2. They allowed the user to execute custom logic within NetBox and save output comprising discrete log messages to the database as a "report result." NetBox v2.6 introduced custom scripts, which are very similar to reports, but had the ability to process user input. However, they lack the ability to persist any output beyond what is immediately returned to the user upon execution.

As there is substantial functional overlap between reports and custom scripts, it makes sense to merge the two features. Once #2006 has been implemented, we can provide a migration path for converting reports into scripts and eventually drop support for reports entirely. A current report will effectively become simply a script which does not take any user input.

### Database Changes
Removal of the ReportResult model, to be replaced under #2006.

### External Dependencies
None

**Comment by darcynz** [comment]
Will custom scripts be able to visualize the scoring of validation that is used for reports?. Ie # Success, #Warning & #Failed

**Comment by ryanmerolle** [comment]
Bumped to v2.11 because possible larger implications that @lampwins and @jeremystretch would like to hash out.

**Comment by jeremystretch** [comment]
Not sure it makes sense to proceed with this given it hasn't gotten much interest from the community. We should avoid forcing people to rewrite their scripts/reports unless there's a pressing need to do so. I'm going to bump this from v2.11 but keep it open for further discussion.
