### ISSUE TITLE
Enable plugins to inject content within object list views

### ISSUE THREAD

**Issue by JulianJacobi** [netbox-community/netbox#4751]
### Environment
* Python version:  3.7
* NetBox version:  2.8.0

### Proposed Functionality
It would be nice to give plugins the capability to not only inject buttons in object detail views, but also inject buttons to object list views.

### Use Case
My specific use case is to add an additional button to object list view to give options to preseed the object form with automatically generated values, like in our case names, that follows the company's naming convention.

Here a little example screenshot:
<img width="473" alt="Bildschirmfoto 2020-06-12 um 11 57 30" src="https://user-images.githubusercontent.com/3304773/84490916-167b1300-aca4-11ea-911a-2d3932eb103e.png">

### Database Changes
None.

### External Dependencies
None.

**Comment by jeremystretch** [comment]
> It would be nice to give plugins the capability to not only inject buttons in object detail views, but also inject buttons to object list views.

Please expand your issue to specify exactly what changes you are proposing, including example code that a plugin would use.

**Comment by JulianJacobi** [comment]
I would add an additional method to `PluginTemplateExtension` called `list_buttons()` that acts similar to `buttons()` but is not rendered in an object's detail view context but in object's list view.

Plugin example code could be:
```python
from extras.plugins import PluginTemplateExtension

class DeviceListButton(PluginTemplateExtension):
    model = 'dcim.device'

    def list_buttons(self):
        return self.render('sample_netbox_plugin/inc/device_list_buttons.html')

template_extensions = [DeviceListButton]
```

**Comment by JulianJacobi** [comment]
If this would help, I can provide an implementation attempt.

**Comment by ozoid** [comment]
I too would like to see this feature - along with plugin buttons/areas on the interface view - there are some already on the cable view.
p.s. custom fields on interfaces would also be great (https://nifry.com/2020/06/08/custom-fields-on-netbox-interfaces/)
Thank you :-)

**Comment by hellerve** [comment]
i think this sounds fantastic. What feedback needs to be gathered still?

**Comment by jeremystretch** [comment]
What functionality would the buttons provide? Keep in mind that they would not be part of the object selection list: you would not be able to select a few objects and then perform some plugin action, for instance. Bearing this in mind, maybe generic "list header" and "list footer" inclusions would make more sense?

**Comment by JulianJacobi** [comment]
In out (maybe a little bit special) use case, we want to add "shortcuts" to the object creation form with a (vie GET-parameters) preseeded, autogenerated object name. So we can easily create the next unused name that follows a special naming convention, without the need to copy&paste things from netbox to netbox.

So for this use case a button near the "Add" button makes the most sense. But i think i got you point and if you don't want to support both options (what i could understand) i think list header and footer buttons would make more sense in a more generic point of view.

**Comment by ozoid** [comment]
A plugin button on the interface view would allow our plugin to pull/push the data for the specific interface (Observium/SNMP) 
We could also link to the interface charts/detail page on our monitoring systems. 
We have added the custom fields for interfaces to allow us to store the monitoring system interface UID.
Content areas could allow us to augment the interface view with more data/charts/stats.
The cable detail page allows plugin buttons - we have been using another system for our cable database - buttons here allow us to pull in that data - popup some questions - and update the details from the other system (temporary solution).
overall we are extremely impressed with netbox, I would like to see our whole infrastructure detailed - but getting 2 DCs worth of data into netbox is not just a simple import task, hence the plugin to connect our systems and slowly import/update/push to our devices.

**Comment by jeremystretch** [comment]
I've modified the title of this proposal to be more generic, rather than focusing specifically on buttons.

I'm marking this tentatively accepted (pending milestone assignment) with the assumption that its implementation will be limited to extending [the current feature](https://netbox.readthedocs.io/en/stable/plugins/development/#extending-core-templates) to also support list views.
