### ISSUE TITLE
Plugins: Extend Create and Edit Object view to include custom forms.

### ISSUE THREAD

**Issue by minitriga** [netbox-community/netbox#4752]
### Environment
* Python version:  3.7
* NetBox version:  2.8.0

### Proposed Functionality
Allow users to fill out plugin information within the object create/edit view. Currently, we are using Custom Fields to do this but it would be nice to have a form that ties to its own model if required as using Custom Fields means we need to keep track of what custom fields we are using. 

![image](https://user-images.githubusercontent.com/26367336/84517228-e5600a00-acc6-11ea-8818-a5a41f7ff116.png)

```
from extras.plugins import PluginTemplateExtension
from django import forms

class NameForm(forms.Form):
    test_1 = forms.CharField(label='Test 1', max_length=100)
    test_2 = forms.CharField(label='Test 2', max_length=100)

class DeviceTypeListForm(PluginTemplateExtension):
    model = 'dcim.device_type'
    form = NameForm()
    def form(self):
        return form

template_extensions = [DeviceTypeListForm]
```

I'm not sure of the implementation details but let me know if this doesn't make sense. 

Shouldnt need to do anything with the view template as there are already components that allow this detail to be added. 

### Use Case
Ability to populate models that relate within the same view as Netbox Core models. 

### Database Changes
None

### External Dependencies
Netbox Plugins

**Comment by jeremystretch** [comment]
It's a neat idea, but this isn't something we can reasonably support in the core. Forms can be very complex, particularly with regard to validation, and trying to accommodate unknown third party extensions is a non-starter. Further, our goal is to eventually move toward an entirely API-driven UI anyway, which would obviate the need for traditional forms as they currently exist.
