### ISSUE TITLE
IP addresses with overlapping prefixes permitted

### ISSUE THREAD

**Issue by cmacnevin** [netbox-community/netbox#4753]
### Environment
* Python version: 3.7.4
* NetBox version: 2.8.5

### Steps to Reproduce - all steps are in the UI
1. Create a prefix, eg 10.0.0.0/8
2. Create an ip address within that prefix with an arbitrary netmask, eg: 10.0.1.10/24.
3. Create a second ip address with a netmask which creates an overlapping prefix range, eg: 10.0.1.11/25

### Expected Behavior
Expect the second IP address to be rejected. This is not a valid entry in the real world, as it creates overlapping prefixes. Expect logic to anchor ip addresses to prefixes, similar to other IPAMs like Infoblox.

### Observed Behavior
Both ip addresses are accepted. Conflict present in the data.

**Comment by jeremystretch** [comment]
NetBox does not have the necessary contextual information in this case to validate either address: You cannot assume either mask is correct. Thus, NetBox does not treat either as incorrect. Additionally, support for overlapping IP addresses within a table (VRF) would prevent enforcement of such validation even if the required context was present.
