### ISSUE TITLE
Add Interfaces to global search

### ISSUE THREAD

**Issue by JulianJacobi** [netbox-community/netbox#4757]
### Environment
* Python version:  3.7
* NetBox version:  2.8

### Proposed Functionality
Add Interface model to global search.

### Use Case
I think global search should list matching interfaces independently from a special use-case, the current situation is kind of inconvenient.

### Database Changes
None

### External Dependencies
None

### Proposed Solution
Since a global interface table exists it should be sufficient to just add the following to `netbox/views.py`'s `SEARCH_TYPES`:
```python
('interface', {
    'permission': 'dcim.view_interface',
    'queryset': Interface.objects.prefetch_related('device'),
    'filterset': InterfaceFilterSet,
    'table': InterfaceDetailTable,
    'url': 'dcim:interface_list',
}),
```

**Comment by jeremystretch** [comment]
We don't include device components in global search results as they are typically sought within the context of a particular device or set of devices. Additionally, the global interfaces list is already fully searchable.

**Comment by candlerb** [comment]
As of Netbox 2.9, there is no longer a global interfaces list.  You have to search Device Interfaces and VM Interfaces separately, if for example you want to search for a MAC address.
