### ISSUE TITLE
Bad swagger documentation using Nested Serializers

### ISSUE THREAD

**Issue by Dimaqa** [netbox-community/netbox#4758]
### Environment
Python version: 3.6.9
NetBox version: 2.8.5

Bad swagger documentation for Nested Serializers with many=True parameter 

### Steps to Reproduce

With introductions of plugins we can now create our own models with netbox serializers.
So if you have field like
`ips_list = NestedIPAddressSerializer(required=False, many=True)`
Swagger post documentation would be wrong
And it includes every nested serializer.

### Expected Behavior
```
 "ips_list": [ 0
  ],
```

### Observed Behavior
```
 "ips_list": [
    {
      "address": "string"
    }
  ],
```
 But post request himself works as expected with "ips_list": [ 1 ], it's just swagger issue

**Comment by jeremystretch** [comment]
Core serializers are not intended to be used by plugins. Plugin authors are responsible for their own endpoints and the documentation thereof.
