### ISSUE TITLE
Inherit primary child device IP to parent device

### ISSUE THREAD

**Issue by Sislik** [netbox-community/netbox#4764]
### Environment
* Python version:  3.6.9
* NetBox version:  2.8

### Proposed Functionality

Inherit primary IP for chassis from child devices.

### Use Case

If i have HP blade enclousure (parent device), which is made from 16 different server, 8 different switches and 2 different Onboard Admins (Active, Standby).
I would like to see actually the IP of one of the Onboard Admins as primary IP for the Blade enclousure.

As workaround i can create dummy interface (with name of the onboard admin) on the parent, which actually doesn't have any interface. Virtual Chassis doesn't looks like options for this as purpose is to see main IP where to connect for the enclousure.

Or im missing something and there is some way how to do it already?

### Database Changes

Additional field for child devices with option "primary for parent"

**Comment by jeremystretch** [comment]
Child devices do not share a control plane with the parent device, thus there is no way to "share" an IP address among them. The parent device needs to have its own interface and IP address assigned.
