### ISSUE TITLE
Missing Core Template Extensions from Certain Models

### ISSUE THREAD

**Issue by cruse1977** [netbox-community/netbox#4765]
### Environment
* Python version:  3.8
* NetBox version:  dev-2.8.5

### Steps to Reproduce
1.  Clone Animals Plugin
2.  modify template_content.py, changing model=  to 'dcim.interface' (or dcim.device)
3.  install plugin

Display of Animal Count on Interface page.

Based on the documentation: Plugins can inject custom content into certain areas of the detail views of applicable models. This does not suggest this only applies to select models.

Default template displayed.

Issue, missing lines from the .html template for models other than site. 

site.html:
       {% plugin_buttons site %}
        {% plugin_left_page site %}
        {% plugin_right_page site %}
        {% plugin_full_width_page site %}

device.html, nor interface.html has these lines

**Comment by jeremystretch** [comment]
1. We do not accept bug reports for anything other than a stable release.
2. These lines are clearly [present in the template](https://github.com/netbox-community/netbox/blob/v2.8.5/netbox/templates/dcim/site.html#L37) in the v2.8.5 release. If they are missing from your NetBox deployment, it's likely an installation/upgrade issue. Please post to our mailing list if you need further assistance.
