### ISSUE TITLE
Store the last or historic configuration files of the devices 

### ISSUE THREAD

**Issue by enribla** [netbox-community/netbox#4768]
### Environment
* Python version:  3.7.4
* NetBox version:  2.8.0

Getting the configuration of a device in is not very useful for the network engineers in my opinion because there are two things:
- If the device is broken you can access to it
- It takes too long ans we stablish an ssh conection each time

In my opinion it should be much practical to store the config file and get this file and have the possibility to generate a new config file and get track of them with the date

Each time that we want to read the config of a device we need to wait too long so finally its better to go to the linux server where I store the backups and do a 'cat'
In case the router is broken we can't get here the backup file

Yes it should create a link to a file. These backup files could be stored in a special folder that we even could populate externally. (same name of the device with a pattern)

Nothing in particular

**Comment by jeremystretch** [comment]
This is out of scope for NetBox, and there are plenty of tools already which do this.
