### ISSUE TITLE
Custom Field - 'Time' Type

### ISSUE THREAD

**Issue by darcynz** [netbox-community/netbox#4769]
### Environment
* Python version:  3.7 
* NetBox version:  2.8.4

### Proposed Functionality
Add a 'Time' type for custom fields so that a time input could be entered via a widget, eg. 09:00

### Use Case
Being able to set a start or end time for a process, eg a service window.

### Database Changes
None that I am aware of

### External Dependencies
None that I am aware of

**Comment by jeremystretch** [comment]
Development of custom fields is currently frozen pending a reimplementation of the entire model.

**Comment by jeremystretch** [comment]
Tagging as related to #4878
