### ISSUE TITLE
Platform and Device must have the same Manufacturer

### ISSUE THREAD

**Issue by JulianJacobi** [netbox-community/netbox#4777]
### Environment
* Python version: 3.7
* NetBox version: 2.8.6

### Steps to Reproduce
1. Create a `Manufacturer` called "Dell" 
2. Create a `DeviceType` let's call it "R340" with `Manufacturer` "Dell"
3. Create a `Device` "Random Dell Server" from `DeviceType` "R340"
4. Create a `Manufacturer` called "RedHat"
5. Create a `Platform` called "Red Hat Enterprise Linux" with `Manufacturer` "RedHat"
6. Try to assign the `Platform` "Red Hat Enterprise Linux" to `Device` "Random Dell Server"

### Expected Behavior
The `Device` "Random Dell Server" has now `Platform` "Red Hat Enterprise Linux" assigned.

### Observed Behavior
The assignment is not possible because of a stupid check that says, that platforms must have the same manufacturer as the device they are assigned to.\
How is it possible to correctly document any linux based server in Netbox?

I understand the check from an old networking point of view, it makes no sense to run JunOS on Cisco Routers, but in times of Cumulus Linux this check even fails for networking devices.

**Comment by ziggekatten** [comment]
Simple fix. Do NOT assign Redat Linux platform with a manufacturer, and it will be available to any server regardless of manufacturer.

**Comment by JulianJacobi** [comment]
@ziggekatten do you really think it's a fix to **not** document things in a documentation system?

From my point of view this seems to be a little bit shitty. So I can only document the manufacturer of a platform if it's ever matching with the manufacturer of the assigned devices? Maybe i'm getting things wrong here, but for me this makes absolutely no sense.

**Comment by JulianJacobi** [comment]
Additionally the manufacturer locking doesn't prevent you from wrong documentation at all, think about IOS XE and IOS XR both are Cisco platforms but can be installed only on specific Cisco devices.

So here we have a feature that prevents you in some special cases from misconfiguration, but also prevents you from document things completely. So think it's not a feature, it's a bug.

**Comment by ziggekatten** [comment]
I think it is ”Good enough”, not perfect.

**Comment by JulianJacobi** [comment]
Question for me is: Whats the benefit of vendor locking?

There would be one, if e.g. all Cisco platform work with all Cisco devices (replace Cisco with random vendor), but because that's not the case i see no benefit in vendor locking.

**Comment by ziggekatten** [comment]
To minimize dropdown when you like us have 100+ manufacturers and 500+ device types

**Comment by JulianJacobi** [comment]
IMHO not a problem with Select2 and the APISelect Widget

**Comment by ziggekatten** [comment]
Cisco alone have IOS, IOS XR, ACI 4.x ACI 5.x, Firepower etc. Minimizing stuff is essential. 

Also, we have an archtecture tha continiously validate sanity of data and ensure that any deviations are handled. This is something everybody should consider. Never trust a user :-). This is where Netbox Custom scripts com in handy.

**Comment by JulianJacobi** [comment]
You were right if the sanity checking would make sense in this case, but like i showed before the vendor lock doesn't prevent users from selecting wrong stuff, so i think sanity checking is not really an argument here.

**Comment by ziggekatten** [comment]
Sanitychecks are definitively neccessary, especially when integrating with other systems such as ITSM and billing.  In our case, we use netbox all the way out to our project managers and due dilligence people, that are not neccessarily the most technically skilled people, so verification is needed. 

My point here is that you can either stumble on something that is not perfect, or one can look at how to use the tool in a way so that you business benefit from it. 

For us the platform is used to estmimate and plan number of devices that need to be updated from x to y, and for various reports. 

And again, nothing is perfect, but can be good enough.

**Comment by tyler-8** [comment]
@JulianJacobi I'd recommend coming to a free and open-source project run by unpaid volunteers with a bit more civility in your language. We can be frustrated and have a debate without being rude.

**Comment by jeremystretch** [comment]
As other have pointed out, this is intentional. If it's not the behavior you want, NetBox isn't the right tool for you. Closing and locking.
