### ISSUE TITLE
Change Managment

### ISSUE THREAD

**Issue by pboatone** [netbox-community/netbox#4778]
### Environment
* Python version:  2.8.6
* NetBox version:  

### Proposed Functionality
Netbox is a nice tool for documentation, but it would be if there came a change-managment with it. It should be possible to add changes to device such as "20.06.2020 - changed HDD because it was too small" or "20.06.2020 - Deaktivated user" --> maybe as plugin

### Use Case
It is nice to have all in one tool, so you have all information about your devices, ip and co in one tool.

### Database Changes

none

### External Dependencies

none

**Comment by ziggekatten** [comment]
This is where I think we should be careful. I for one do NOT like a core Netbox swelling to a garganruan product horrible to maintain.  This is where the plugin architechure would come in handy. 

As I see it, a plugin that integrates with a change management tool (iTop, Remedy, Snow etc) is useful. 

And normally, a change in terms of ITIL (if we go that interesting route) should start in the ITSM, and update Netbox through the API. 

Now, for those not using ITSM tools for change management today, a custom script with custom field and som python could probably solve it without having to develop Netbox itself.

**Comment by jeremystretch** [comment]
Have a look at #151, as that likely addresses the use case you have in mind.
