### ISSUE TITLE
Prefix as DHCP

### ISSUE THREAD

**Issue by pboatone** [netbox-community/netbox#4779]
### Environment
* Python version:  v2.8.6
* NetBox version:  

### Proposed Functionality
It would be nice if you can add prifixes as dhcp and you can say devices have an ip in this prefix and the free ips will decrese  

### Use Case
So u can see which devices in a dhcp mode and u dont have to bind an ip to device. Because DHCP sometimes change the IP. And u can see how much devices in this prefix and u know how much devices u can add in this prefix/DHCP-area

**Comment by jeremystretch** [comment]
DHCP ranges typically do not equate to exact prefixes. Rather, they are arbitrary ranges; e.g. 192.168.10-254. Thus, it would not make sense to designate an entire prefix for this purpose. There has been some discussion around modeling IP address ranges, however it is not currently being explored further.
