### ISSUE TITLE
Device images in rack redirect to broken URL

### ISSUE THREAD

**Issue by rkclayton** [netbox-community/netbox#4780]
### Environment
* Python version: 3.6.8
* NetBox version: 2.8.6

### Steps to Reproduce
1.  Created new installation of netbox following the official guide.  Configured HTTPS redirect in virtualhost file for port 80.   
2. Create site, rack. device type, add device to rack.  
3. Click image in rack 

Takes me to device page for what was clicked.  

The link is missing a /  -  hovering over the link it looks correct but if you actually click it it sends you to 
"https://domain.dc.localdcim/devices/5/"
instead of 
"https://domain.dc.local/dcim/devices/5/"

If i manually enter the URL it works OK.    I cant find any documentation explaining how to manipulate this

**Comment by jeremystretch** [comment]
This is a configuration issue. Please search closed issues or the mailing list for the remedy.
