### ISSUE TITLE
Support Multi-Chassis LAG Interfaces

### ISSUE THREAD

**Issue by aleheux-tc** [netbox-community/netbox#4782]
### Proposed Functionality

LAG Interfaces should be able to connect to LAG interfaces on multiple devices.

### Use Case

There is a variety of MC-LAG type functionality across many platforms that is widely used, EVPN is one, regular MC-LAG another.

This feature was requested before:
https://github.com/netbox-community/netbox/issues/3033
https://github.com/netbox-community/netbox/issues/2830

EVPN is a standard and definitely relevant. I argue that the fact that regular MC-LAG implementations are proprietary is irrelevant as on the front end they all look the same and they interoperate between vendors just fine. That each vendor implements it their own way in the forwarding and control plane is irrelevant. The same could actually be said of regular LAG: Every vendor implements that their own way too.

If Netbox wants to be able to model network devices and how they're connected, which it clearly is, this is definitely in scope as all the various ways there are to connect one logical LAG port to multiple others are widely used.

If Netbox implements this 1-N (or even N-M) functionality in a generic way, it could also be extremely useful for things like DWDM, 10G breakout, etc.

**Comment by jeremystretch** [comment]
This was already addressed under #2830. Please don't open duplicate issues. This functionality is not something we're exploring at this time.

**Comment by aleheux-tc** [comment]
You have not addressed anything I've said and neither does #2380.

If this project is just not interested in feedback from and/or participation by its users, perhaps this can be clearly stated somewhere so everyone knows to pass it by.

**Comment by steffann** [comment]
It's not that this is a bad idea, but there are other things on the roadmap at the moment that require the focus of the maintainers for the foreseeable future. There is technical debt to be paid off before support for new concepts like EVPN and MC-LAG can be introduced.

So thank you for bringing this up. It is definitely something that occurs in real life, and it would be nice to support modelling it in NetBox. Once the maintainers have more brain cycles available this can be reconsidered.

Help with resolving the open issues and reducing the technical debt is appreciated. The sooner that is done, the sooner new features can be considered!
