### ISSUE TITLE
Virtual Disk Database for virtual machines

### ISSUE THREAD

**Issue by Mordecaine** [netbox-community/netbox#4783]
### Environment
* Python version:  3.6.9
* NetBox version:  v2.8.5

### Proposed Functionality
It would be nice to define virtual disk objects to attach to the virtual machines.
I think it should look like the "Interfaces" part in a virtual machine. You would attach disks to the virtual machine like IP Addresses to the interface.

The virtual disk object could have the following attributes:
Size
Storage Cluster (on which storage the virtual disk is saved)
Partitions
     mountpoint
     filesystem

### Use Case
This feature could be used to import the disk informations into a monitoring system to check the disks. This feature could also be used to get a statistic about the storage and how many disks are attached to.

### Database Changes
I'm not really good in databases. So I definitive should not define database changes.

### External Dependencies
I think there are no new dependencies.

**Comment by jeremystretch** [comment]
NetBox does not intend to replicate discrete system resources beyond the resource fields already provided. Users who need to track more detail than that typically rely on an existing virtualization orchestration tool to do so.
