### ISSUE TITLE
Creation of sub interface of existing device after upgrade lists sub interface above parent interface.

### ISSUE THREAD

**Issue by tigger4life** [netbox-community/netbox#4794]
### Environment
* Python version: 2.7.5 and 3.6.8
* NetBox version: 2.8.6-ldap

### Steps to Reproduce
1. Add components | Interfaces to an existing device
2. Create sub virtual interface (like ge-0/0/1.2). No other changes needed
3. Create interface
This only happens when adding an interface to an existing device. Upgraded from 2.8.4-ldap

### Expected Behavior
I expected the sub interface to show up under it's parent ge-0/0/1.

### Observed Behavior
The sub interface was listed above parent interface not below.

**Comment by jeremystretch** [comment]
> Python version: 2.7.5 and 3.6.8

**Comment by tigger4life** [comment]
Apologies this is my first time reporting anything. My Cent VM has both python versions so I listed them both but NetBox is running with 3.6.8.

 The -ldap is the docker version I'm using. I wanted to make sure I gave you what I was running. I didn't know if that mattered so I included it.

As far as the interfaces, from a device that was already created prior to the update, I had the following interfaces in order of appearance on the device:
xe-0/0/17
xe-0/0/17.2
xe-0/0/17.3
xe-0/0/17.4
xe-0/0/17.5
xe-0/0/17.6
xe-0/0/17.7

After the update, I create 2 new interfaces and the appear in order as follows:
xe-0/0/17.8
xe-0/0/17.9
xe-0/0/17
xe-0/0/17.2
xe-0/0/17.3
xe-0/0/17.4
xe-0/0/17.5
xe-0/0/17.6
xe-0/0/17.7

I expected the 2 new interfaces to fall in line along with the rest. I hope this helps!

**Comment by jeremystretch** [comment]
> The -ldap is the docker version I'm using

Please note that we only accept bug reports which are reproducible on a current stable release of the core NetBox product.

I am unable to replicate this behavior on v2.8.6. I'll also note that we have [tests in place](https://github.com/netbox-community/netbox/blob/develop/netbox/dcim/tests/test_natural_ordering.py#L92) to ensure that this ordering logic is working.

If you can identify a specific series of discrete actions by which this condition can be replicated on a current official release, I'm happy to reopen the issue.
