### ISSUE TITLE
Expand report status to include Warnings

### ISSUE THREAD

**Issue by cpmills1975** [netbox-community/netbox#4801]
### Environment
* Python version:  3.7.7
* NetBox version:  2.8.6

### Proposed Functionality

Expand the 'status' of a report from the current 'Passed'/'Failed' to include 'Warning' when a report returns warnings, but not failures. Effectively reports would result in a proper Red/Amber/Green status.

### Use Case

A report can currently log pass, fail, warn or info for any given test, yet the result of the test is either pass or fail depending on whether any 'fails' were logged or not. I'd like to propose that 'warn' is added for situations where the report writer has deemed something bad enough to warn the user, but not bad enough to fail. Fail will take priority, but should no fails be logged, the logging of at least one warning would make the report result warn rather than pass.

Obviously this overlaps with the work in #2006, specifically the changes to the JobResultStatusChoices class.

### Database Changes

JobResultStatusChoices would need to be further expanded to include a WARN status.

### External Dependencies

None.

**Comment by jeremystretch** [comment]
Let's not get ahead of ourselves. The PR for #2006 hasn't even been merged yet, let alone the v2.9 beta released. Please wait until you have a chance to review the beta, and if you believe this proposal is still relevant we can look at reopening it.

**Comment by cpmills1975** [comment]
So this isn't specifically related to 2.9 or to #2006. It's a general request to expose warnings up to the report result if no errors are logged, but warnings are.

My specific use-case is monitoring. I have an idea where I will run reports periodically using Jenkins and then read the report result in to a monitoring platform using the API. Like most monitoring platforms, it supports Red (error), Amber (warning) and Green (ok) statuses but because reports can only pass or fail, warnings will not be exposed to the monitoring platform making them effectively pointless in my planned scenario.

I mentioned #2006 as I searched for other, matching or potentially conflicting, feature requests first.

**Comment by lampwins** [comment]
@cpmills1975 since you are looking at the report status via the API, you have the ability to look at the log levels of all the log messages for a given report and make the decision yourself.

Said said, let's let the dust settle on #2006 and come back to this if needed.
