### ISSUE TITLE
object changes API does not include what was changed however the web interface does

### ISSUE THREAD

**Issue by baldgeek** [netbox-community/netbox#4810]
### Environment
* Python version:  3.6.8
* NetBox version:  2.8.6

### Proposed Functionality

A change viewed in the web interface includes a "Difference" section. It would be nice if this data was available via the object changes API as well.

### Use Case

It would allow a better collection of changes to outside systems and programmatic review/rollback of changes.

### Database Changes

I do not believe this would require any DB changes since the data is visible on the web site.

### External Dependencies

None that I am aware of.

**Comment by jeremystretch** [comment]
The API is intended to represent each change record discretely. As with any type of object, comparison of two or more records is a function that needs to be implemented by the consumer. As an example, your client might retrieve the two latest change records and then compare them locally using a diffing library.
