### ISSUE TITLE
change ID is returned on API calls that modify data.

### ISSUE THREAD

**Issue by baldgeek** [netbox-community/netbox#4811]
### Environment
* Python version:  3.6.8
* NetBox version:  2.8.6

### Proposed Functionality

Any patch, delete, creation returns the change ID for the change record created so that the object change API can be called to verify or collect data for rollback. 

### Use Case

Be able to find the change record for the work just done to pull change record for rollback or verification. 

### Database Changes

I do not believe this would require and database changes. These records already exist.

### External Dependencies

I don't think there is any external dependencies, however timing of when the change record is created vs when the results are returned to the API call might make this problematic to implement.

**Comment by jeremystretch** [comment]
It's a neat idea, but unfortunately this would require far too much development effort (and a bit of performance impact) to warrant the minor convenience. The way DRF employs serializers doesn't easily allow for the arbitrary attachment of additional information such as this. However, you can easily fetch the most recent change record for any object by querying the `/api/extras/object-changes/` API endpoint.
