### ISSUE TITLE
Add Custom Fields for Power Panels

### ISSUE THREAD

**Issue by proudbro** [netbox-community/netbox#4820]
### Environment
* Python version:  3.6.9
* NetBox version:  2.8.6

### Proposed Functionality
Add Custom fields functionality to Power Panels similar to other primary models 

### Use Case
Since the panels do not even have a field as Description we can't store additional information about Power Panels in NetBox. Would be great to use all potential of custom fields at once

**Comment by jeremystretch** [comment]
As mentioned in many other issues, we are not currently working on extending the custom fields feature, pending a major overhaul of the model.
