### ISSUE TITLE
[language] inclusivity

### ISSUE THREAD

**Issue by drewrothstein** [netbox-community/netbox#4823]
### Environment
* Python version:  `all`
* NetBox version:  `all`

### Proposed Functionality

* Changing all references of `whitelist` (env vars) to `allowlist`.
* PR is trivial/ready once accepted.

### Use Case

* More inclusive language.

### Database Changes

* None.

### External Dependencies

* None.

**Comment by lampwins** [comment]
The only occurrence of whitelist/blacklist in NetBox comes from settings defined by [dango-cors-headers](https://github.com/adamchainz/django-cors-headers). We have no control over these settings. If you feel strongly about this, raise the issue upstream.

**Comment by drewrothstein** [comment]
Understood and thank you for the pointer - they have an open PR: https://github.com/adamchainz/django-cors-headers/pull/531.

**Comment by drewrothstein** [comment]
This is now merged and is available in `3.5.0`.
Opened https://github.com/netbox-community/netbox/issues/5160 for discussion/review.
Happy to send over a PR for this trivial change.

Cheers-
