### ISSUE TITLE
API Change to lags for ansible use

### ISSUE THREAD

**Issue by garbled1** [netbox-community/netbox#4825]
### Environment
* Python version:  3.7
* NetBox version:  2.8

### Proposed Functionality

I've been playing with using netbox as a source of truth for ansible roles.  The idea being I configure a switch in netbox, and then tell ansible "make the real switch look like that".  I've managed to get this working for all the interfaces and the vlans, but the LAG interfaces are giving me fits.

The issue is the API stores the lag members in each interface as being members of lag X.  But ansible needs a structure like:
lag:
  members:
   - eth/1
   - eth/2

I spent about 6 hours trying to generate this dynamically inside ansible using the API, and just due to ansible's structure, unless I write a special plugin (which, I can do, if I have to.. but..) it cannot be done.

So my ask is, can the lag itself have an extra field that contains the members name's or id's?

### Use Case

Ansible integration as source of truth to build LAG interfaces from netbox.

### Database Changes
unknown

### External Dependencies
n/a

**Comment by jeremystretch** [comment]
The REST API representation of an interface intends to be as efficient as reasonably possible. Parent LAG interfaces are already listed under each interface, so including child interfaces under the parent interface would be redundant (and introduce additional overhead).

However, all the data you need is already available in the response; you just need a bit of extra logic within the Ansible module to compile the list of child interfaces for each LAG parent. Such an exercise is out of scope for NetBox, but I encourage you to raise the topic in the #ansible channel on http://slack.networktocode.com/.
