### ISSUE TITLE
DNS CNAMEs for services

### ISSUE THREAD

**Issue by garbled1** [netbox-community/netbox#4826]
### Environment
* Python version:  3.7
* NetBox version:  2.8

### Proposed Functionality

A Service should have a cname field, that lets you set an alternate name for that service.

### Use Case
I can use netbox as a source of truth for my network, such as, create a service named "ZABBIX", and then use it inside ansible when configuring a VM.  Connect to netbox, lookup the ZABBIX service, find the associated device, and configure the server to use that ip/name for it's zabbix server in the conf file.

However, it would also be nice if I had a cname for that service, like "zabbix.foo.com" instead of "machinename.foo.com" or ip.  Then I don't have to rewrite the zabbix conf files on 100 machines if I move that service.  I can do this manually, but there is no way to store this cname in netbox so I can look it up dynamically.

### Database Changes
unknown

### External Dependencies
n/a

**Comment by jeremystretch** [comment]
This sounds a bit redundant, since the corresponding CNAME for a service is likely to be the same as the service's name in many cases.

**Comment by garbled1** [comment]
That depends alot on the complexity of your network.  A good example:

preprod_zabbix:  CNAME = zabbix.uat.garbled.net
prod_zabbix: CNAME = zabbix.garbled.net

I mean, I guess I could just name the services zabbix.uat and zabbix, but what if the cname was zabbix.not_garbled.net ?

I dunno.. I guess I can work around it, I'm just saying it would be nice.  At a certain point, if I have to name the service "zabbix.garbled.net", then there is basically no point in retrieving that from netbox as I've already hardcoded "zabbix.garbled.net" into my automation.

**Comment by steffann** [comment]
I wrote a [plugin](https://github.com/sjm-steffann/netbox-ddns) some time ago which allows you to let NetBox automatically create DNS records using DNS Update messages. It allows for multiple hostnames attached to an IP address. Would that be something you can use?

**Comment by jeremystretch** [comment]
IMO the service record shouldn't have any statically-defined data that isn't directly tied to the service itself. If you include the FQDN as the CNAME record (as opposed to concatenating only the host portion with a domain portion sourced elsewhere), then you need to update all applicable service records in a non-trivial way should the domain change.

It just feels like this is pushing a bit into DNS management territory, which we've intentionally avoided for the sake of limiting scope. It's probably best to just use a custom field on the Service model for this particular use case.
