### ISSUE TITLE
Allow tags for Rack Groups

### ISSUE THREAD

**Issue by soer7022** [netbox-community/netbox#4828]
### Environment
* Python version:  3.6.9
* NetBox version:  v2.8.5

### Proposed Functionality
Allow tags for rack groups, just like sites and racks

### Use Case
We use rack groups to model modules at factories, it would be nice to tag these rack groups as "factory-module" so we don't get the other rack groups at the given site, when we query it.

### Database Changes
Add "tag" field to rack groups

### External Dependencies
None

**Comment by jeremystretch** [comment]
NetBox does not support tags on organizational models, such as rack groups, circuit types, etc. Tags are intended to be used in conjunction with such models to help organize and differentiate primary models (sites, racks, circuits, etc.).
