### ISSUE TITLE
Add NEMA 15/L15 Power Port and Outlet Types

### ISSUE THREAD

**Issue by mandrewdx** [netbox-community/netbox#4829]
### Environment
* Python version:  3.7.7
* NetBox version:  2.8.5

### Proposed Functionality
Add missing power port, and power outlet types

### Use Case
Devices that use NEMA 15 and L15 types can select these

### Database Changes
NA

### External Dependencies
NA

**Comment by mandrewdx** [comment]
References used (also noted in the PR)
https://www.stayonline.com/product-resources/

[NEMA Locking Reference Chart](https://www.stayonline.com/product-resources/nema-locking-reference-chart.asp)
[NEMA Straight Blade Reference Chart](https://www.stayonline.com/product-resources/nema-straight-blade-reference-chart.asp)

There are plenty in the list that are missing, though I'm unsure how common they are. I'm happy to do the extra work to add the all of the remaining types though.

**Comment by jeremystretch** [comment]
> There are plenty in the list that are missing, though I'm unsure how common they are.

There's certainly a balance to be struck between inclusion and usability. For now, we've just been adding new types as requested, since there are no doubt dozens (hundreds?) of esoteric terminations which are no longer in common use.
