### ISSUE TITLE
NAPALM - Support connecting via Hostname

### ISSUE THREAD

**Issue by jvanderaa** [netbox-community/netbox#4831]
### Environment
* Python version:  3.7.7
* NetBox version:  2.8.6

### Proposed Functionality

Support device name NAPALM connectivity when no primary IP address is defined

### Use Case

- Some orgs do not use for IPAM but still would like NAPALM functionality
  - IP Addresses can change and if NetBox is not that source of truth, would be out of date
- Capability exists with minimal additional code to complete a DNS lookup using socket
- Would require name to be reachable by name service within the server NetBox is using

### Database Changes

No changes

### External Dependencies

- Python socket library, built in
- NetBox server ability to query appropriate name server (not a NetBox dependency)

**Comment by jeremystretch** [comment]
Just to clarify, the accepted behavior should be:

- If the device has a primary IP address assigned, use it
- If not, attempt to resolve the device's hostname
- Report either/both failures to the user
