### ISSUE TITLE
Config Context assignment based on Device Type

### ISSUE THREAD

**Issue by robertpenz** [netbox-community/netbox#4833]
### Environment
* Python version:  3.6.9
* NetBox version:  2.8.5

### Proposed Functionality

Add a dropdown box for device type for config context assignment. 

### Use Case

We've switches/routers from multiple vendors and use config context based on platform heavily, but some devices types of the same platform don't support a feature. We now want to override the config context for them based on that. So the platform has the feature enable and then platform + device types does disable it. Also enabling the feature only for platform + device types does not work current as we can't select device types.

### Database Changes

no

### External Dependencies

no

**Comment by ledgley** [comment]
We would like to see this too, please.

**Comment by kilker12** [comment]
Agreed

**Comment by jeremystretch** [comment]
A reminder, per the [contributing guide](https://github.com/netbox-community/netbox/blob/develop/CONTRIBUTING.md):

>  Note that comments with no substance other than a "+1" will be deleted. Please use GitHub's reactions feature to indicate your support.

**Comment by jqueuniet** [comment]
I'd like to add my support to this enhancement, with a different use case.

* Serial console configuration. Some hardware needs COM2/ttyS1, other needs COM1/ttyS0, many of our devices don't support changing the serial port and thus, we can't standardize over one or the other.
* Installation devices for unattended installs, especially for storage servers with loads of block devices. `/dev/sda` might not always be the answer and the specifics are going to be very tied to hardware parameters (number of controllers, PCI slot usage, etc).

Of course, we could use tags for this, but as this use cases are very common this means handing thousands of tags based on device types and basically duplicating the information of the latter. We can't use the platform for this either, as it is already used to store the operating system installed, and here too would mean duplicating the information of device types.
