### ISSUE TITLE
Vlan Members for API

### ISSUE THREAD

**Issue by almostbeef** [netbox-community/netbox#4834]
### Environment
* Python version:  3.6.8
* NetBox version:  2.8.7

### Proposed Functionality
Make Vlan Members available via the API. I don't believe there is a better way to do it via the API than sifting through every interface. The GUI has that functionality, and was hoping to include it in the API

### Use Case
Quickly verify every interface that a vlan is configured, without needing to check every interface.

Currently, I'm trying to verify that if a device has a vlan configured on one of it's interfaces, that a corresponding virtual interface is created.

### Database Changes
I believe the Netbox DB currently has this functionality as the GUI is already doing it. 

### External Dependencies
None.

**Comment by almostbeef** [comment]
I'm dumb....sorry for wasting your time :)

**Comment by jeremystretch** [comment]
For anyone else who happens upon this issue, I assume this is what you ended up doing:

```
GET /api/dcim/interfaces/?vlan_id=<PK>
```

Or:

```
GET /api/dcim/interfaces/?vlan=<VLAN ID>
```

**Comment by almostbeef** [comment]
Yes....Thank You

Thanks,
Austin Lewis
__________________________
Network Systems Specialist
Penn State IT
Data Centers
Office: (814)867-6301
Cell: (814)933-8697

________________________________

**Comment by almostbeef** [comment]
Yes that fixed it.
