### ISSUE TITLE
Use dynamic results for Site create/edit form Region field

### ISSUE THREAD

**Issue by abrahamvegh** [netbox-community/netbox#4836]
### Environment
* Python version: 3.7.3
* NetBox version: 2.8.7

### Proposed Functionality

Modify the Site create/edit form so that the Region choices are retrieved dynamically, rather than rendered statically on page load.

### Use Case

If the desired Region does not yet exist, adding it in another tab and then being able to select it without having to reload the form (losing any already-entered data) is convenient. This functionality already exists for many other fields.

### Database Changes

N/A

### External Dependencies

N/A

### Notes

Yes, it doesn’t happen that often.

**Comment by jeremystretch** [comment]
This is a limitation imposed by the use of static form widgets to represent the nested position of each available option. As this issue has implications beyond the scope of this issue, I've raised #4837 to address this application-wide. Enabling the dynamic selection of regions will be accomplished as part of that work.
