### ISSUE TITLE
Ability to nest power panels [Feature request]

### ISSUE THREAD

**Issue by tydonk** [netbox-community/netbox#4839]
### Environment
* Python version:  3.7 
* NetBox version:  2.8.6 

### Proposed Functionality
The ability to nest power panels. 

### Use Case
 In our datacenter we have subpanels between our main PDU's that have 100 amp breakers.  Inside the subpanel the power is broken into smaller 20 and 30 amp breakers.  Nesting would allow the creation of those subpanels which could contain their own power feeds,

**Comment by jeremystretch** [comment]
NetBox isn't intended to model the power hierarchy beyond what exists today. Expanding the model in the way you've described was considered when power modeling was being implemented, but was determined to be out of scope for the project.

**Comment by Dzordzu** [comment]
> NetBox is not intended to model the power hierarchy beyond what exists today

Actually, I'm really interested why
What are the reasons behind such decision? @jeremystretch
