### ISSUE TITLE
Missing example on REMOTE_AUTH_*** parameters with a generic Oauth provider

### ISSUE THREAD

**Issue by strus38** [netbox-community/netbox#4842]
### Change Type
[X] Addition
[ ] Correction
[ ] Deprecation
[ ] Cleanup (formatting, typos, etc.)

### Area
[ ] Installation instructions
[X] Configuration parameters
[ ] Functionality/features
[ ] REST API
[ ] Administration/development
[ ] Other

The newly available parameters for REMOTE_AUTH are nice, but it lacks details for implementation. It would be very nice to add an example based on a generic Oauth provider like Keycloak.

I am trying to implement that for a netbox running on kubernetes with Keycloak/ Keycloak gateway using OIDC to protect it. Of course, right now, without those headers, I can protect the access to the netbox endpoint, and it works, but then I fall back on the login screen of netbox, which is pointless. 
Trying to use the REMOTE_AUTH parameters is not clear, especially for the REMOTE_AUTH_HEADER, which I cannot understand.

Thanks.

**Comment by jeremystretch** [comment]
Providing details on how to configure the feature to work with any specific provider is outside the documentation's scope. Please consider posting to our discussion list if you'd like assistance with the configuration.
