### ISSUE TITLE
Allow Custom Fields on Platforms

### ISSUE THREAD

**Issue by ledgley** [netbox-community/netbox#4846]
### Environment
* Python version: 3.7.3
* NetBox version: 2.7.x

### Proposed Functionality
Allow creation of custom fields on Platforms

### Use Case
Our organisation is using a custom field on Device Type to track End of Support information regarding device types. We would also like to track this information for Platforms in the same manner

### Database Changes
Unsure

### External Dependencies
None

**Comment by jeremystretch** [comment]
Sorry but development concerning custom fields is currently frozen pending future work to reimplement them entirely.

**Comment by jeremystretch** [comment]
Please see #4878
