### ISSUE TITLE
Reverse Mounted Devices

### ISSUE THREAD

**Issue by h0tw1r3** [netbox-community/netbox#4853]
### Environment
* Python version:  N/A
* NetBox version:  2.8.7 (current)

### Proposed Functionality

Add a device flag to indicate direction it is mounted. Flag would be used in the rack view to automatically swap the front and rear device images.

### Use Case

Devices such as the Opengear IM7200 are often rear rack mounted in reverse so the frequently accessible ports are facing the rear, of the cage. From the device perspective it's still technically considered the rear. Convoluted, hopefully that makes sense.

### Database Changes

I'm not familiar with the database schema, but possibly a new flag on the device object model.

### External Dependencies

None

**Comment by jeremystretch** [comment]
This ability already exists: Devices can be mounted to either the front or rear face of a rack.

**Comment by h0tw1r3** [comment]
I understand, but they can't be reversed in either from or rear position.

**Comment by h0tw1r3** [comment]
Unless I'm missing something, it's currently not possible. Is there some work-around?

**Comment by jeremystretch** [comment]
The front of the device is the face which appears on the rack face in which the device is mounted. For an Opengear IM7200, this would be the face which houses the console server ports, and the device would be mounted on the rear face of the rack.

**Comment by h0tw1r3** [comment]
Which makes sense if you mount the device the same way in every rack, but that's not always the case.
So the work-around would be to create multiple *device types* depending on the installed orientation.
