### ISSUE TITLE
Custom Racks/Elevations device pop-up

### ISSUE THREAD

**Issue by chache35** [netbox-community/netbox#4855]
### Environment
* Python version:  <2.7.5>
* NetBox version:  <2.6.6>

### Proposed Functionality

Currently when the cursor is pointing on a device  from the Racks/Elevations page, a pop-up is displayed showing the "device role", "device type" and "serial number" of the device.
![image](https://user-images.githubusercontent.com/56358900/87464932-393a7780-c614-11ea-8cf6-08930dae1dd9.png)

I would like to be able to customize the values displayed in the pop-up, for example, remove the serial number and add the tenant.

### Use Case

I would like to view the tenant of a devices from the Elevations page just by pointing the mouse on the device.

### Database Changes

No database change.

### External Dependencies

No external dependencies.

**Comment by jeremystretch** [comment]
You're running a rather outdated release of NetBox. The rack elevation diagrams were completely redone in v2.7, and now utilize SVG rendering to provide a much nicer, portable image. However, this does mean that the HTML pop-up no longer exists.
