### ISSUE TITLE
Netbox can't find plugins

### ISSUE THREAD

**Issue by davetayl** [netbox-community/netbox#4859]
### Environment
* Python version: 3.8.0
* NetBox version: v2.8.8-dev
Running on CentOS Linux release 8.2.2004 (Core)
App location /opt/netbox, front end with Apache/WSGI
Firewalld disabled
Selinux Permissive

The instances is working well other than the issue described here 

### Steps to Reproduce
1. pip install nextbox-ui-plugin
2. add netbox-ui-plugin to configuration.py
```
PLUGINS = [
    'nextbox-ui-plugin',
]
```
3. ./manage.py makemigrations
4. fails 
5. if the following code is used, it works.
```
PLUGINS = [
    'nextbox_ui_plugin',
]
```
With other plugins this method doesn't work.

### Expected Behavior
plugin is loaded with no error

### Observed Behavior
Plugin unable to be found.

The behaviour seems somewhat consistent across all the listed plugins (pip search netbox | grep plugin), aside from the couple of plugins that won't load at all, all the others are unable to be found, in the one case listed, the change mentioned solved the issue, however this was not the case for any other plugins.

**Comment by jeremystretch** [comment]
> NetBox version: 2.7.3
Is this correct? Plugins are only supported on NetBox v2.8.0 and later.

**Comment by davetayl** [comment]
Good pickup sorry, somehow I posted the prod system version rather than dev, I've updated the description

**Comment by jeremystretch** [comment]
I'm not sure what you're considering to be a bug here. I was able to install `nextbox-ui-plugin` per [the project's instructions](https://github.com/iDebugAll/nextbox-ui-plugin/blob/master/README.md) on NetBox v2.8.7 without issue. Note that `nextbox-ui-plugin` is the PyPI package name, whereas `nextbox_ui_plugin` is the plugin name.

> With other plugins this method doesn't work.

You need to follow the specific instructions of each plugin for its installation.

**Comment by davetayl** [comment]
Yes, I noted that the UI plugin worked with that tweek, however none of the others did

**Comment by jeremystretch** [comment]
You'll need to address that with the maintainers of those plugins then, I suppose. There's nothing actionable here from the NetBox side.
