### ISSUE TITLE
There was an error rendering the selected export template (): 'None' has no attribute 'rack'

### ISSUE THREAD

**Issue by tikitaru** [netbox-community/netbox#4863]
### **Environment**
Python version: 3.6.8
NetBox version: 2.8.6

I am creating an export template for dcim > cable and whenever I attempt to reference cable._termination_b_device.rack.facility_id I receive the error message in the title. I do not see the error returned on cable._termination_a_device.rack.facility_id though. Using Jinja2 for language

### Steps to Reproduce

This errors
{% for cable in queryset %}
Rack: {{ cable._termination_a_device.rack.facility_id }}
Rack: {{ cable._termination_b_device.rack.facility_id }}
{% endfor %}

But this works fine:
{% for cable in queryset %}
Rack: {{ cable._termination_a_device.rack.facility_id }}
Rack: {{ cable._termination_b_device.rack }}
{% endfor %}

P.S. it functions if I do it from the cli nbshell

**Comment by jeremystretch** [comment]
Thank you for your interest in NetBox. GitHub issues are intended for reporting reproducible bugs and requesting features, and must be submitted using one of the templates provided [here](https://github.com/netbox-community/netbox/issues/new/choose). For general discussion, questions, or assistance with installation issues, please post to our [mailing list](https://groups.google.com/forum/#!forum/netbox-discuss) instead.
