### ISSUE TITLE
View permissions should be reflected on Navbar and initial page

### ISSUE THREAD

**Issue by esoubihe** [netbox-community/netbox#4864]
### Environment
* Python version: 2.8.5
* NetBox version:  2.7.17

### Proposed Functionality
From a UX perspective, the navbar and initial page should respect view permissions in the sense that they should be hidden if the user doesn't have access to them, both for secondary and primary navigation items.

I understand the implications of permissions and the concerns raised on #323 and other similar issues. The proposal here is merely an aesthetic change to avoid confusion and miss clicks.

### Use Case
Company Story: As a bare metal shop, Virtualization is irrelevant to my team.
User Story: As a Support Manager, I want to simplify the interface so support analysts can find information faster.

### Database Changes
None

### External Dependencies
None

**Comment by jeremystretch** [comment]
Navigation menu items for which the user does not have access to view are disabled. We don't remove them from the menu entirely completely because can very easily lead to user confusion in cases where permissions are missing.

**Comment by esoubihe** [comment]
That's the exact reason why you have super admin users. Applying a CSS cursor style to the anchor and not even rejecting navigation is what causes confusion. 

The current implementation is incorrect from a UI and UX perspective and confusion doesn't justify the decision.

**Comment by jeremystretch** [comment]
> Applying a CSS cursor style to the anchor and not even rejecting navigation is what causes confusion.

A bug report to fix this would be valid, so long as there is an understanding that we won't fully remove the navigation items from view.

> confusion doesn't justify the decision.

That's very easy to assert when you're not obligated to answer support requests. I am, so I have a very different opinion.

**Comment by esoubihe** [comment]
Shouldn't we at least gather feedback from the community and weigh the pros and cons? 

Seems like the only con in your argument is that you have to respond to support tickets. I think there are ways around that that could be explored. Also,  what do you mean by surprising navigation menus?
