### ISSUE TITLE
Establish a GitHub repository template for NetBox plugins

### ISSUE THREAD

**Issue by jeremystretch** [netbox-community/netbox#4866]
### Proposed Changes
Create a [GitHub repository template](https://github.blog/2019-06-06-generate-new-repositories-with-repository-templates/) for NetBox plugins. This template should include boilerplate common to all plugins: `setup.py`, `README`, a `PluginConfig`, etc.

### Justification
Providing a repo template allows users to clone a repo directly from the template and avoid having to craft the provided boilerplate by hand.

**Comment by mirceaulinic** [comment]
Just an idea, not sure if you like this approach or the project, but I've used this pattern to great effect: https://cookiecutter.readthedocs.io/. HTH!

**Comment by bcohee** [comment]
It would be nice to have a centralized list where authors could submit their plugins, ideally within the github/netbox-community project

**Comment by jeremystretch** [comment]
@bcohee There is a list here: https://github.com/netbox-community/netbox/wiki/Plugins

We intend to invite the authors of plugins which become mature and popular to join the `netbox-community` GitHub organization, though I don't think anyone's put together a firm list of qualifications yet.

**Comment by lampwins** [comment]
@ryanmerolle also managed to get `netbox-plugin` to be registered as an official github topic, so if authors add that to their repo's topic list, it will show up when searching in github.

**Comment by jeremystretch** [comment]
Going to close this out as it doesn't apply to NetBox itself. Someone else is welcome to take on the task if interested, though by this point there are probably enough plugins in the wild to serve as a reference.
