### ISSUE TITLE
Disable front or rear rack view / slots

### ISSUE THREAD

**Issue by lps-rocks** [netbox-community/netbox#4868]
### Environment
* Python version:  3.7.6
* NetBox version:  2.8.7

### Proposed Functionality

Ability to disallow front or rear rack slots from being used using a drop down or selection on the rack editing page.

### Use Case

Some racks are wall-mounted in a way that you cannot put a device in the rear. However, some devices are half-depth and may exist in multiple places. Might

### Database Changes

Not sure but most likely would require a yes/no flag on the rack model as if the rear of the rack is not able to be accessed.  

### External Dependencies

N/A

**Comment by jeremystretch** [comment]
I'm going to decline this proposal as I don't see much benefit considering the additional validation that would be required, and that there has been no further interest.
