### ISSUE TITLE
Additional Custom Field Sections

### ISSUE THREAD

**Issue by iunderwood** [netbox-community/netbox#4874]
### Environment
* Python version:  3.6.8
* NetBox version:  2.8.8

### Proposed Functionality

This proposal is to add custom fields to additional properties in Netbox, specifically rack groups.

### Use Case

A building on an enterprise campus is represented by a single site.  However, IDFs within that building can be represented by rack groups.  Being able to add fields to rack groups can allow addition of useful information such as access method (key / card), and a facility room number, just to name a couple possibilities.

### Database Changes

Unsure.  This may be a simple extension of custom field functionality that is enabled for other properties.

### External Dependencies

None I am aware of.

**Comment by jeremystretch** [comment]
Development of custom fields is currently frozen pending an overhaul of its current implementation; please see #4878. It's likely that support for custom fields will be expanded in the process of this work, once a solution has been agreed upon.
