### ISSUE TITLE
Bulk assigning tags to interfaces deletes tagged VLANs

### ISSUE THREAD

**Issue by ThomasGiger** [netbox-community/netbox#4880]
### Environment
* Python version: unknown - using a pre-installed system
* NetBox version: 2.8.7

### Steps to Reproduce
1. On a switch or other device with multiple interfaces, assign tagged VLANs to some or all interfaces.
2. Select some interfaces and "edit selected" to assign a tag to them.
3. Revisit the tagged VLAN assigments: they are gone on the interfaces which had tags assigned.

### Expected Behavior
Expected the VLAN tags not to be lost during bulk editing as long as the bulk editing doesn't change the tagged VLANs.

### Observed Behavior
The interfaces where tags were assigned with bulk editing lost their existing tagged VLAN assignments.

**Comment by kobayashi** [comment]
I can reproduce this in the latest version.
