### ISSUE TITLE
DNS name field on the Netbox device view page

### ISSUE THREAD

**Issue by saifk-20786** [netbox-community/netbox#4884]
### Environment
* Python version:  3.6.9 
* NetBox version:  (v2.8.4)

### Proposed Functionality
We are storing the DNS name for the devices under the IP address in Netbox. In the Netbox UI, we can customize the table view with the fields under Devices. Currently, the table customization is missing the dns_name information. Can you please add the dns_name as well to the device's table customization? Please find the attached image for more information on the requirement. Thank you!

### Use Case

![image](https://user-images.githubusercontent.com/57385791/88258167-217e8580-ccdd-11ea-9d00-c0fe24201d47.png)

**Comment by jeremystretch** [comment]
Tables are limited to displaying attributes of the object, or in some cases, immediately related objects. The relationship from device to DNS name spans several relationships: device <- interfaces <- IP addresses <- dns_name. Querying all IPs associated with all interfaces for all devices would impose too much overhead to be feasible. To find all defined DNS names for a device, you can filter the IP addresses list by device.
