### ISSUE TITLE
BTU field and calculation per rack

### ISSUE THREAD

**Issue by TheFrenchCanadianEh** [netbox-community/netbox#4889]
### Environment
* Python version:  
* NetBox version:  

### Proposed Functionality
A new field for every device requesting BTU (heat generation) providing a calculation per rack. This will help in determining heat creation per rack, and make for easy calculations for branch hub room cooling requirements.
A means of calculating BTU based on wattage would also be beneficial

### Use Case
A new branch office is being built, and cooling requirements are needed by the contractor.
If all devices in the rack were assigned a BTU rating, or a means of calculating it based on wattage, a quick per rack calculation would be feasible.

### Database Changes
A new field per device would be required

### External Dependencies
unknown

**Comment by jeremystretch** [comment]
Can you elaborate on the proposed new field please? For example, what would the range of valid values be? Under what circumstances would it be required? How would it be conveyed to the user?

**Comment by lps-rocks** [comment]
To add to the discussion, I believe this should be tracked more similarly to power, have an average value and a maximum value. Since we all know servers can have some pretty outrageous BTU / Wattage ratings based on power supplies and not based on *actual* thermal output and power consumption. 

Intel has a specification here: https://www.intel.com/content/www/us/en/support/articles/000006784/server-products.html - for generating BTUs based on consumed wattage. It boils down to watts * 3.41214 = BTU

Or, if there's an industry standard formula this could be done off the wattage fields like @TheFrenchCanadianEh suggested.

**Comment by TheFrenchCanadianEh** [comment]
Hello Jeremy,

It would be a decimal based field (although you could force an integer)
that would show up when defining every device.
The range of values per device would be from 0 to likely no more than 15000
BTU/hr for a larger chassis switch with multiple blades and power supplies.
It would be required when building a hub room, and calculating the cooling
required for the space. This could feasibly be used to calculate your hot
isle in a DC too.
I would like it to be conveyed as that same BTU field entry for each
device, and a rack summary of all entered BTU's. You could in theory keep
expanding this calculation out for the row if multiple racks are present.
Anything larger than a row, Data Center engineers would be involved and
would be spec'ing cooling for total floor space growth.

Use case: When I spec'd a new hub room for a branch office, the general
contractor always wants a BTU calculation to decide on cooling for the
space.

If you were to look up a current switch, say a Cisco 9300
<https://www.cisco.com/c/en/us/td/docs/switches/lan/catalyst9300/hardware/install/b_c9300_hig/b_c9300_hig_appendix_0110.html>
tech
sheet and search for BTU, each power supply size has a different output.

The formula for *calculating BTU*/hr is: *Heat Dissipation* (Watts) x
3.4192 = *BTU*/Hr. So if a server has a *heat dissipation* (output) of 500
Watts the thermal or *heat* energy generated is 1709.6 *BTU*/hr.

Please let me know if you have further questions or need detail. I
appreciate the quick response to this feature request. It should be quite
easy to implement as an optional field.
If you do create a rack summary, maybe add a warning that "Device X in U32
does not have a BTU value assigned, using 0 for this calculation"

Regards,
David Corriveau
m. 226.988.4019

**Comment by xkilian** [comment]
The BTU field should not be added to device templates. As it will already contain the average and max watts and the value should be derived from this.
These values (Equipement, rack, row, etc. BTUs) should be available to be queried/displayed via the API and UI even though it is a derived value.

**Comment by tb-killa** [comment]
I like the idea of @xkilian but for this we should make the "Maximum draw" field to an required input if device-template created.
if we check the device-template repo we could see there are this values insert:
```
power-ports:
- name: PS1
  type: iec-60320-c16
  maximum_draw: 1100
- name: PS2
  type: iec-60320-c16
  maximum_draw: 1100
```

i personally thinking about the btu calculation could be some part of plugin maybe ?

**Comment by jeremystretch** [comment]
@TheFrenchCanadianEh can you please update your original post to specify the exact changes being proposed?

**Comment by TheFrenchCanadianEh** [comment]
I think xkilian and Oliver identified the better way to proceed. This
should result in completion of the requested behaviour.

**Comment by jeremystretch** [comment]
FYI this issue will soon be closed if the original post is not updated to detail the specific change(s) being proposed.
