### ISSUE TITLE
Swap Terminating Ends of Cable

### ISSUE THREAD

**Issue by iunderwood** [netbox-community/netbox#4890]
### Environment
* Python version:  3.6.8
* NetBox version:  2.8.8

### Proposed Functionality

Add the capability to swap the A and Z end of a terminating cable.

### Use Case

Connecting two devices together is great, but it would be nice to be able to swap the A and Z ends of a connection for the presentation of data uniformity.

For instance, when I build out a cable plant from an IDF to an MDF, I might build that cable out starting from a point in my IDF, and terminating that in my MDF.  That makes the A end in the IDF, when it's really in the MDF.  It would be handy to just swap the ends without having to delete and rebuilt the whole cable.

### Database Changes

None that I am aware of.

### External Dependencies

None that I am aware of.

**Comment by jeremystretch** [comment]
Cables do not imply any direction: there are A and B ends, however these are arbitrary designations and exist as unique values solely to accommodate two terminations. The NetBox UI intentionally does not reveal to the user which end of a cable receives which designation.

**Comment by iunderwood** [comment]
The observation of the A and B ends comes up in the cable list.

I found I built some cables starting in one of my IDFs to the MDF in question and some in the other direction.  It would be nice to make these more uniform without having to rebuild the cable.

It is not a high-priority feature request.

**Comment by jeremystretch** [comment]
> The observation of the A and B ends comes up in the cable list.

That's true, but again, these don't indicate a particular direction. For instance, the Cable model could just as easily use an alternate approach where up to two terminations are assigned to a cable, as opposed using discrete fields on the model. In such a case, we'd still likely label the columns "A" and "B" just to differentiate between them. (I'm not suggesting we're going to do this in the future, but it's a possibility.)

**Comment by wols** [comment]
This is a nice feature and I see two use cases:

- a form of _consitend_ documentation (@iunderwood: A is MDF, B is IDF ever)
- users - like me - can map the signal direction (A: source, B: destination)
-- I have a lot of cables between IN/OUT interfaces

**Comment by cpmills1975** [comment]
IT tends to attract people with certain diverse characteristics.

I've seen people get quite upset at others for using the switch as the A end when it should have been the server or vice versa. Providing a simple means to swap ends would serve to placate some emotions!

**Comment by iunderwood** [comment]
@cpmills1975 - Never underestimate how much someone can be affected by their [CDO](https://www.urbandictionary.com/define.php?term=CDO).

**Comment by jeremystretch** [comment]
Blocked by #4900

**Comment by cpmills1975** [comment]
Is this still blocked?
