### ISSUE TITLE
Limit Selection w/ Cable Rear Ports

### ISSUE THREAD

**Issue by iunderwood** [netbox-community/netbox#4891]
### Environment
* Python version:  3.6.8
* NetBox version:  2.8.8

### Proposed Functionality

When connecting rear ports, after picking my B-Side site and B-Side rack, limit the pull-down selection of devices to ones which only have an available rear port, instead of all the devices in a rack.

This could be automatic, or it could be an option to toggle the view limit.

### Use Case

This makes selection a little cleaner.  I have a fiber plant I am modeling, which will have over 100 devices in some racks.  It would be nice to not see the devices with bays (which have no rear ports), as well as not see device where I have already connected the rear ports.

### Database Changes

None required.  This should be a limit to the selection criteria.

### External Dependencies

None I am aware of.

**Comment by jeremystretch** [comment]
Implementing this would require introducing new filters for the devices API endpoint; something like `has_available_rear_ports=True`. I'm not sure off the top of my head how feasible that is, but it would require a separate feature request.
