### ISSUE TITLE
Changing Device type

### ISSUE THREAD

**Issue by n3rdman** [netbox-community/netbox#4893]
### Environment
* Python version:  3.6.8
* NetBox version:  2.8.7

### Proposed Functionality

Requesting ability to change device type after device has already been created.

### Use Case

New equipment is added to replace old equipment. Want to retain the name and rack it is in. But change device type and bring in associated port mapping with new device type. If IP's, tags and ports could transfer that would be great. But not necessary.

### Database Changes
Don't anticipate database changes.

**Comment by jeremystretch** [comment]
Thank you for submitting this issue, however it appears that this topic has already been raised. Please see issue #3233 for further discussion.
