### ISSUE TITLE
Make MAC an available column on dcim/interfaces

### ISSUE THREAD

**Issue by lps-rocks** [netbox-community/netbox#4899]
### Environment
* Python version:  3.7.6
* NetBox version:  2.8.7

### Proposed Functionality

Make MAC an available column on dcim/interfaces.

### Use Case

This is one of the most common search mechanisms used by networking administrators when tracking down an unknown device or a device that may not be operating properly. 

### Database Changes

None AFAIK

**Comment by jawyoonis** [comment]
Hey guys, is this issue solved . I am having a similar issue in my ansible playbook when try to assign mac address to a device. 
```

['Invalid custom field for dcim | device objects: MAC']}\n",
    "module_stdout": "",

```
