### ISSUE TITLE
Custom fields - mailto: and tel: Field Type

### ISSUE THREAD

**Issue by Dapsy2000** [netbox-community/netbox#4901]
### Environment
* Python version:  3.7.2
* NetBox version:  2.8.4

### Proposed Functionality
Is it possible to extend the custom field types under dcim_site by the types mailto: and tel: like the fields contact mail and contact phone?
So it is possible to click on the mail address in the custom field value and it automatically opens the mail program for example.

### External Dependencies
None

**Comment by jeremystretch** [comment]
You can do this by creating a custom URL field. Just enter the phone number or email address with the appropriate scheme. For example:

![customfield1](https://user-images.githubusercontent.com/13487278/88545452-01a2d680-cfe9-11ea-9b84-6b3edc7fdcb9.png)

This is displayed as:

![customfield2](https://user-images.githubusercontent.com/13487278/88545453-01a2d680-cfe9-11ea-97d6-af32a306c90a.png)

Custom fields don't currently support providing link text that differs from the URL, though that may be something to explore once we start work on #4878.
