### ISSUE TITLE
read-only view without export permission

### ISSUE THREAD

**Issue by Dapsy2000** [netbox-community/netbox#4902]
### Environment
* Python version:  3.7.2
* NetBox version:  2.8.4

### Proposed Functionality
Is it possible to setup read-only views without the permission of exporting prefixes for example via CSV file.

Our users should only have the opportunity to read on netbox but shouldn’t be able to export any data.

**Comment by jeremystretch** [comment]
Permissions can control only four core operations: view, add, change, and delete. There is no granularity for controlling the specific mechanism via which an object is viewed/retrieved. This is actually a fundamental design goal of NetBox: ensuring that user permissions are enforced consistently irrespective of the mechanism being used to exchange data (for example, the web UI versus the REST API).

> Our users should only have the opportunity to read on netbox but shouldn’t be able to export any data.

From a practical standpoint, this is impossible. A user with permission to view these objects necessarily has the option to export data from the system, whether through export templates, the REST API, or copying data from the web UI directly.
