### ISSUE TITLE
Missing total count of front ports on device types view in 2.9-beta1

### ISSUE THREAD

**Issue by dare-to-recurse** [netbox-community/netbox#4905]
### Environment
* Python version: 3.8.0
* NetBox version: 2.9-beta1
* PostgreSQL version: 10.6
* Redis version: 5.0.3
* nginx version: 1.14.1

The following steps were tested in a clean install of netbox 2.9-beta1 on a up-to-date CentOS 8 install.
Verified to occur with the following browsers to (try to) rule out client-side bugs
* Chrome: 83.0.4103.116 (Official Build) (64-bit)
* Firefox: 78.0.2 (64-bit)
* Edge: 84.0.522.44 (Official Build) (64-bit)

### Steps to Reproduce
1. Create a manufacturer 'test'
2. Create a device type 'test'
3. Create rear ports '[1-4]' with one position each
4. Create front ports '[1-4]' corresponding to the created rear ports

### Expected Behavior
Front ports tab on the device type view to display a total count of front ports.

### Observed Behavior
Front ports tab on the device type view does not display a total count.
All other tabs display this correctly.

**Comment by jeremystretch** [comment]
Whoops. This is indeed a template error. Sorry @dare-to-recurse, when I looked at it last week I must have been looking at the device template mistakenly. Apologies, and thank you for the thorough bug report!
