### ISSUE TITLE
Document 'exclude' filter for API calls

### ISSUE THREAD

**Issue by tyler-8** [netbox-community/netbox#4911]
### Change Type
[X] Addition
[ ] Correction
[ ] Deprecation
[ ] Cleanup (formatting, typos, etc.)

### Area
[ ] Installation instructions
[ ] Configuration parameters
[ ] Functionality/features
[X] REST API
[ ] Administration/development
[ ] Other

### Proposed Changes
Similar to https://github.com/netbox-community/netbox/issues/2671 and https://github.com/netbox-community/netbox/issues/4729, the `exclude=config_context` filter was added in [v2.6](https://github.com/netbox-community/netbox/blob/f2d1c7d82a659c1a06381e340dcedfd45edcbd80/docs/release-notes/version-2.6.md) but hasn't been documented outside of the release notes.

I propose adding the same snippet from the release notes under the `Filtering` header on the [API documentation](https://github.com/netbox-community/netbox/blob/3baf983e8610ef62849bd2e5e4011eb3ef67071f/docs/api/overview.md). Many questions and issues are generated from the performance of config contexts (to be addressed by https://github.com/netbox-community/netbox/issues/4559) and until that is improved, I think adding this workaround to the documentation will go a long way in reducing headaches.

Happy to take this one if approved.

**Comment by jeremystretch** [comment]
Thanks @tyler-8!
