### ISSUE TITLE
Clarify the whether default and required plugin configuration parameters are mutually exclusive

### ISSUE THREAD

**Issue by jeremystretch** [netbox-community/netbox#4916]
### Change Type
[x] Addition
[ ] Correction
[ ] Deprecation
[ ] Cleanup (formatting, typos, etc.)

### Area
[ ] Installation instructions
[ ] Configuration parameters
[ ] Functionality/features
[ ] REST API
[ ] Administration/development
[x] Plugins
[ ] Other

### Proposed Changes
The plugins development documentation specifies two mechanisms for defining plugin-specific configuration parameters:

* `required_settings` - A list of any configuration parameters that must be defined by the user
* `default_settings` - A dictionary of configuration parameters and their default values

However, it does not specify whether these lists are mutually exclusive. Is it considered valid to list a parameter in both lists? What are the implications of doing so?

**Comment by jmcgill298** [comment]
I would say that all `default_settings` are required, and therefore making the `required_settings` a special type of required options. This then makes it confusing to have the same variable defined in both sections. This also leads to unnecessary confusion about precedence order and where a user should update the setting.

**Comment by lampwins** [comment]
We can update the wording to be more clear on the purpose and difference of the two settings, but I would shy away from phraseology like "mutually exclusive." It is not an error to define a setting in both. This is the code for default:

```python
        # Apply default configuration values
        for setting, value in cls.default_settings.items():
            if setting not in user_config:
                user_config[setting] = value
```

**Comment by jeremystretch** [comment]
I think confusion arises in the case where a default is provided for a required setting: An ImproperlyConfigured exception will be raised if the parameter is missing from the user's configuration even if the plugin provides a default value.
