### ISSUE TITLE
Allow organize column

### ISSUE THREAD

**Issue by thoms27** [netbox-community/netbox#492]
Hi,

I would to know if it was planed to organize column like under TeemIP tool ?
It will be much appreciate I think.

Thanks in advance.

Thomas V.

**Comment by jeremystretch** [comment]
Do you mean rearranging the order of columns in the table? Why would it matter? If you want to export objects in a different format, you can always create a custom [export template](http://netbox.readthedocs.io/en/latest/data-model/extras/#export-templates).

**Comment by thoms27** [comment]
Hi,

Yes, to choose which column display and the order.

Thanks :-)

**Comment by mryauch** [comment]
Hello,

Just wanted to chime in here.  Picking which columns to display would certainly be helpful in the case that you have important custom fields.  For instance, for circuits we have designated 'primary' 'secondary' 'tertiary' circuits, so I created a Priority custom field.  Since I don't use tenants for circuits, that field is unused and wasted space in the listing of circuits, but I would love to be able to see at a glance which circuits are primary and backups.

Thanks

**Comment by gopal87** [comment]
+1 for what @mryauch said.

**Comment by Armadill0** [comment]
I would love to see this feature, too.

**Comment by hanej** [comment]
Is this currently on track for a release?

**Comment by mryauch** [comment]
Originally I was interested in this feature, but honestly at this point I'm interacting with the API and making my own web interfaces to display this information anyways.  I'm going the Flask route and using Netbox as a source of documentation, then interacting with the environment to compare documentation to reality.

In the circuit example I used before I'm planning on a circuit page that would grab all of the circuits in Netbox and display their BGP status and confirm if they're configured to be the 'primary' 'secondary' etc.

**Comment by hanej** [comment]
I think this is still hugely beneficial for those that would rather have everything in a single site instead of directing users to another site for some data and Netbox for others.  I believe this makes sense as part of the core product.

**Comment by mryauch** [comment]
Absolutely, it would certainly be nice to glance at Netbox and be able to see how everything is configured, but I was just illustrating on why it's not personally as important to me anymore.

This actually reminded me of how Docker allows you to set the format of commands with a simple json template.

```
# cat ~/.docker/config.json
{
  "psFormat": "table {{.Names}}\\t{{.Image}}\\t{{.Status}}"
}

# dps
NAMES               IMAGE                 STATUS
netbox_nginx_1      nginx:1.11-alpine     Up 13 days
netbox_app_1        netbox_app            Up 13 days
netbox_postgres_1   postgres:9.6-alpine   Up 13 days
```

I'm thinking just setting a template or picking columns via the Admin panel would be sufficient, but I could see some power users wanting to be able to set columns themselves.

**Comment by hanej** [comment]
That template isn't a bad idea.  It looks like a form of Jinja2.  I can see doing something like this to create the template and save it as a view could work.  If you take the Templating feature from Grafana and put that at the top of the view, the end user can select things like the prefix or VLAN of what they're interested in and reuse the same view to display that new data.

Also, when exporting from that view, the CSV file output would match the columns displayed on the screen.  We really need this to display custom fields in with our external to internal NATS.

[Grafana Templating Example](https://play.grafana.org/d/000000143/templating?orgId=1)

**Comment by lesinigo** [comment]
My two cents here, we too have a use case involving custom fields and it would be really useful for us to customize default views. For example in the IP Addresses view we usually have three empty or "not really used" columns (NAT, Parent, Interface) but it would really help us to see the custom "fqdn" field.

As a case of columns customization we are already enjoying I'd bring the example of Redmine:

- the [default issues view](https://www.redmine.org/projects/redmine/issues)
- the [same view with customized columns](https://www.redmine.org/projects/redmine/issues?utf8=✓&set_filter=1&f%5B%5D=status_id&op%5Bstatus_id%5D=o&f%5B%5D=&c%5B%5D=tracker&c%5B%5D=priority&c%5B%5D=subject&c%5B%5D=updated_on&c%5B%5D=category&c%5B%5D=cf_4&group_by=)

In Redmine you can edit which columns to see and in what order directly from the page and they get encoded in the URL, while for our NetBox use case (and IMHO for the vast majority of people) it could probably be enough to configure columns from the admin interface.

**Comment by jeremystretch** [comment]
Blocked by #3294

**Comment by havedill** [comment]
+1 for this. We're automatically storing ansible facts into custom fields on the hosts. Would be great to choose these fields as display columns when on the devices/ virtual machines view

**Comment by Grokzen** [comment]
@havedill I have implemented rendering of customfields in our own local netbox fork, and having more then 2-3 customfield columns is not something that you want to go to right now with how the CF:s is structured internally inside the database. The lookups and data fetching through django-tables is horrible in those scenarios and it makes the table rendering horrible slow. Yes i know there is probably a much faster way to render the column and prefetch the data then what i do, which is basically that i use a template column and a class method on the model to get up the CFV for that model object. So for a table with 50 rows, it would make 50 looksup to render one single column and scale that up with more rows and more columns and the performance will drop like a stone in water.

**Comment by Arkasha99** [comment]
Hi guys!
How's it going with this issue? Does anyone work on this? If anyone does, I could help you.

**Comment by Shm013** [comment]
Hi everyone!
We are very interesting of this feature. We'll want to make a special universal wrapper for all lists in netbox that could be configure from django admin panel for all users. Is it suitable conception or not?

**Comment by jeremystretch** [comment]
Blocked by #3294
