### ISSUE TITLE
Ability to clone users/groups along with all applicable permissions

### ISSUE THREAD

**Issue by cpmills1975** [netbox-community/netbox#4920]
### Environment
* Python version:  3.7.8
* NetBox version:  2.9-beta1

### Proposed Functionality

Ability to clone existing users/groups and all their associated permissions to allow easy replication of permissions sets for new users and groups.

### Use Case

In #4919 I wrote about my perceived scalability challenges due to multiple permissions rules being required for each user/group due to the constraints. Providing a way to clone an existing user/group along with all their associated permissions would go some way to addressing the scalability issue.

Example, suppose I create two rules with different constraints to map group-a to devices and device components for tenant-a as follows:

Rule 1:  group-a, read access to dcim > devices with constraint `{'tenant__slug: 'tenant-a'}`
Rule 2: group-a, read access to dcim > interface, dcim > console port, etc with constraint `{'device__tenant__slug': 'tenant-a'}`

It would be nice to be able to simply clone all of these rules when creating 'group-b' who should have read access only to devices, components etc applicable to 'tenant-b'.

### Database Changes

None?

**Comment by jeremystretch** [comment]
How do you envision the end-to-end workflow? Cloning an existing permission is pretty straightforward, but there needs to be a clear step where the user has an opportunity to make changes. For instance, if you clone a permission with the constraint `{'tenant__slug: 'tenant-a'}` and assign it to group B, the constraint is still going to reference `tenant-a`. NetBox can't make any assumption about what, if anything, should change, so we need a human to take care of that.

It might be enough to have a "clone" button on a permission that redirects the user to a pre-populated form to create a new permission. That would be the simplest approach, though it doesn't provide the ability to clone multiple permissions at once.

**Comment by cpmills1975** [comment]
I'm thinking here that the main reason for cloning a user/group in the first place would be to produce a set of permissions similar to those being cloned. Those permissions might be normal CRUD permissions over certain object types, or might include constraints so I guess the right thing to do would be just clone all of the permissions verbatim?

As you have said, NetBox can't make any assumptions about the user's intent in cloning the group/permissions so it would have to be up to the user to modify each rule in turn, add additional ones, perhaps delete some etc. I guess my main thought here is that, along with any possible changes made in #4919, it provides a step towards making sure all the permissions are replicated ready for amendment and #4919 will display them all within the group screen to make it obvious what permissions objects might need to be checked/amended.

I can foresee perhaps a situation where the network team of tenant A might want require write permissions over network objects belonging to tenant A, and the server team might want write permissions over the servers belonging to tenant A. Neither group should have any visibility of the devices belonging to tenant B. Both groups/sets of permissions would likely have a {"tenant__slug": "tenant-a"} constraint along with perhaps a constraint over the device role.
