### ISSUE TITLE
Rack elevations display devices (and details of them) to users without permissions

### ISSUE THREAD

**Issue by cpmills1975** [netbox-community/netbox#4921]
### Environment
* Python version: 3.7.8
* NetBox version: 2.9-beta1

### Steps to Reproduce
1. As admin (or user with adequate permissions) create two devices (device 'a' and device 'b') and rack them, device 'a' should have appropriate attributes such that it will be visible to user 'a' and the device 'b' should have appropriate attributes such that it will NOT be visible to user 'a'.
2. Ensure permissions are created that limit user 'a' to see only device 'a' and not 'device b'
3. Confirm, via the devices screen that user 'a' can see only device 'a' and not device 'b'
4. View the rack elevations. Device 'b' will be visible and, when hovering over it, attributes will be displayed as normal in the tooltip, however clicking on it results in a 404 not found error, presumably, due to inadequate permissions.

### Expected Behavior

While I get that displaying empty rack units doesn't make sense, some way to display occupied rack units but without any details of the device that are using them should be considered. Perhaps something similar to the rack reservation color coding. Alternatively blocking out the units, but displaying no details and either making sure they are not clickable, or if clicked result in a 403 forbidden result would be applicable.

### Observed Behavior

Device 'b' is displayed to the user, along with serial number, asset number, role etc and when clicking it, a 404 is returned. The permissions model correctly prevents access to device 'b' when viewing the device list.

**Comment by jeremystretch** [comment]
Good catch. Here's what it looks like with the fix in place. There are four 1U switches installed, and the current user has permission to view only the top two. The other devices are rendered only as unavailable space.

![rack_screenshot](https://user-images.githubusercontent.com/13487278/88807998-52006c80-d180-11ea-9745-e7fc2a7852c3.png)

**Comment by cpmills1975** [comment]
This looks great @jeremystretch and having tested your latest commits, I can see the devices are indeed hidden. However, the API call for the rack elevation still exposes more information than one might reasonably expect including device ID, name and URL at /api/dcim/racks/id/elevation. Would you prefer a separate ticket opened for this?

**Comment by jeremystretch** [comment]
Good catch. I've opened #4940 to add an `occupied` field to each rack unit. This will allow us to indicate that a unit is occupied without revealing the specific device occupying it.
