### ISSUE TITLE
Optimize VM interface replication in v2.9 schema migration

### ISSUE THREAD

**Issue by jeremystretch** [netbox-community/netbox#4922]
### Proposed Changes
We need to spend more time looking for ways to optimize the `0016_replicate_interfaces` schema migration for the `virtualization` app. There have been reports citing excessive delays when upgrading an installation with large numbers of virtual machine interfaces (150K+).

If we're not able to reduce this time, we should at least provide users with some estimate of the time that running the migration will take (relative to the number of objects being replicated).

### Justification
Database schema migrations typically take very little time, because they typically only modify schema. In this case, we're actually copying objects from one table to another, updating related objects, and deleting the originals. The additional delay imposed in doing so is likely to surprise and frustrate users with a very large number of virtual machine interfaces defined.

**Comment by tyler-8** [comment]
Average rate was roughly 1890 interfaces/minute.
