### ISSUE TITLE
Unable to update secrets

### ISSUE THREAD

**Issue by joaolucasmacedo** [netbox-community/netbox#4927]
### Environment
* Python version: 3.6
* NetBox version: 2.8.8

I'm trying to update some device secrets ant it shows an error. I had to delete the secret and create a new one.
By the way, would be nice to return to the original device page after delete a secret, instead of secrets page.

### Steps to Reproduce
1.  Select device secret.
2. Click "Edit".
3. Chage password and click "Update".

### Expected Behavior
Update password.

### Observed Behavior
Error popup: "Each secret assigned to a device must have a unique combination of role and name"

**Comment by jeremystretch** [comment]
This is a regression introduced in edf15532d25ab94e5e92827f098d6418b8d5be96 for #4702
