### ISSUE TITLE
Add support for Webhooks when accessing objects via the ORM

### ISSUE THREAD

**Issue by dgarros** [netbox-community/netbox#4932]
### Environment
* Python version:  3.7.7
* NetBox version: 2.8.8

### Proposed Functionality
Support a solution to be able to generate Webhooks when objects are changed via the ORM (Create/update/delete). Either automatically or manually.
As I understand, currently webhooks are managed in the class ObjectChangeMiddleware that is only executed in the context of a HTTP request. 

### Use Case
Support Webhooks for all changes done within scripts & plugins executed asynchronously in a worker. (#2006)

### Database Changes
No change to the database

### External Dependencies
I don't think so

**Comment by cpmills1975** [comment]
Yes please! I am working on a script that imports devices and connections and rely heavily on webhooks to populate monitoring and management systems from NetBox. I didn't realise webhooks wouldn't fire and I will need to manage this via documentation and training initially.

**Comment by jeremystretch** [comment]
We discussed this in the maintainers' meeting today. I don't think it's feasible to support in a fully automated fashion, however @lampwins has the excellent idea of introducing a context manager for emulating a web request. This would allow a user to do something like the following (this is pseduo-code):

```python
jstretch = User.objects.get(username='jstretch')
with WebRequestContext(user=jstretch):
    site = Site.objects.get(pk=1)
    site.name = 'Foo'
    site.save()
```

This would essentially be an alternative to the [`change_logging` context manager](https://github.com/netbox-community/netbox/blob/develop/netbox/extras/context_managers.py#L10) used by middleware, with some adjustments to compensate for the absence of an actual HTTP request. More investigation is needed but this seems like a reasonable approach.

**Comment by candlerb** [comment]
Another option would be to use database triggers and stored procedures.  Netbox is welded to Postgres so I would have no issue with using Postgres-specific functionality.

Hooks would then work even for direct SQL manipulation of the database.

**Comment by dBitech** [comment]
Can be quite easily with triggers notify.

See the following as example

https://gist.github.com/colophonemes/9701b906c5be572a40a84b08f4d2fa4e

**Comment by jeremystretch** [comment]
Database triggers aren't something we can reasonably support for several reasons. Any implementation of this feature needs to be done in Python.
