### ISSUE TITLE
Warn user when running downlevel redis server

### ISSUE THREAD

**Issue by drmsoffall** [netbox-community/netbox#4933]
### Environment
* Python version:  3.6.9
* NetBox version:  2.9-beta1

### Proposed Functionality

Enhance the upgrade script or the application to verify the version of redis server installed meets NetBox's minimum requirements.

### Use Case

Typically the upgrade process does a good job of making sure all required packages are installed, but there's a gap when it comes to the new requirement of redis 4+.  While I did eventually figure this out from the redis installation page, it took quite a while because the failure modes are very non-specific, with error messages related to a failure to run a function.

This verification could happen either in upgrade.sh by calling a Python script that reads the configuration and checks the server, or in the startup of the application itself, depending on which is simpler to implement and maintain.  While not a critical functionality, I believe it would save time and minimize frustration.

Alternate solution if effort is too great:  add a specific call-out in the Upgrading documentation.  This wouldn't be as robust, but as long as the user either reads the Upgrading page in advance or falls back to it after experiencing issues, it would get the job done.

### Database Changes

None

### External Dependencies

None

**Comment by kobayashi** [comment]
Is this covered by #4910 ?

**Comment by jeremystretch** [comment]
@kobayashi I don't believe so. That issue concerned the version of the Python package installed; this is to check the version of the Redis service itself.

**Comment by jeremystretch** [comment]
If implemented, we should consider doing something similar for PostgreSQL as well. I know there's a schema migration somewhere that validates the current minimum required version, but it would be more maintainable long-term to have a consistent check in the upgrade script.

**Comment by tb-killa** [comment]
@jeremystretch: 

For Redis-Version: Use Raw Connect with django-redis http://niwinz.github.io/django-redis/latest/#_raw_client_access and use ``INFO`` https://stackoverflow.com/a/22153562

For PostgreSQL: Use Sql Read with ``SELECT version();`` https://stackoverflow.com/a/13733856

What do you think ??

**Comment by drmsoffall** [comment]
Although I don't have experience with Django, and wouldn't presume to make architectural decisions, I've been giving this some thought.  Here are some things to consider:

- Any configuration of PostgreSQL or Redis supported by NetBox should be supported by the version checker
  - This implies support for Sentinel and for separate servers for caching and tasks
- Proper version number comparison isn't simple to implement
  - Could we use [Python packaging](https://packaging.pypa.io/en/latest/version/)'s version parser, since we already get that with setuptools?
- The checker should probably be externally callable only as needed, but how do we avoid reinventing the wheel?
  - How about a Django management command? This sounds like overkill at first, but it would allow us to leverage both Django's database connectivity and NetBox's settings validation/parsing rather than duplicating those functions

P.S., for PostgreSQL, how about using [SHOW SERVER_VERSION](https://www.postgresql.org/docs/7.4/sql-show.html)? Less work to extract the numeric version that way!
