### ISSUE TITLE
API call /ipam/prefixes/{id}/available-prefixes/ returns empty list when there are no child prefixes

### ISSUE THREAD

**Issue by gusmb** [netbox-community/netbox#4935]
### Environment
* Python version: 3.8.2
* NetBox version: 2.8.8

### Steps to Reproduce
1. Create an IP Prefix with no child prefixes
2. API GET call to retrieve the list of available prefixes
   (e.g. curl -X GET "http://localhost:8000/api/ipam/prefixes/1/available-prefixes/")

### Expected Behavior
The result should be a list with a single entry, the entire parent prefix, since no child prefixes are created. 

### Observed Behavior
The returned list is empty instead, which leads to confusion since this could also mean that there are no child prefixes available to allocate.

NOTE: The behavior is correct as soon as there is at least 1 child prefix created. In this case the available-prefixes API call returns a list as expected, ordered from smaller to bigger prefixes.

**Comment by gusmb** [comment]
Closing, the last leading '/' was the problem. Not using the'/' at the end causes an empty return in all cases

**Comment by jeremystretch** [comment]
Be sure to take note of the HTTP response code. In this case, the response is a 302 redirecting the client to the canonical endpoint (with the trailing slash), hence the empty body.

**Comment by gusmb** [comment]
Thanks Jeremy,
Cheers
