### ISSUE TITLE
Interface connections and traces expose details of connected devices regardless of permissions

### ISSUE THREAD

**Issue by cpmills1975** [netbox-community/netbox#4944]
### Environment
* Python version: 3.6.8
* NetBox version: 2.9-beta1

### Steps to Reproduce
1. Create two devices, one with adequate attributes such that it will be hidden to a user, the other visible
2. Connect two interfaces between the two devices
3. Log in with restricted user and observe connection details

### Expected Behavior
While still indicating that a connection exists between the visible device and the hidden device, the details of the device it is connected to in the interfaces table and when performing a cable trace should somehow be hidden.

### Observed Behavior
The device and port names of the 'B' end of the connection is displayed, but clicking on them results in a 404 error.

**Comment by jeremystretch** [comment]
I'm not sure I agree with this. Let's start with the REST API representation of a cable trace. The response is a list of three-tuples, with each representing a (near end, cable, far end) set in the path. The near and far end serializations show a minimal representation of the connected termination and its parent device/circuit. For example:

```json
[
    {
        "id": 1,
        "url": "http://localhost:8000/api/dcim/console-ports/1/",
        "device": {
            "id": 1,
            "url": "http://localhost:8000/api/dcim/devices/1/",
            "name": "device1",
            "display_name": "device1"
        },
        "name": "Console Port 1",
        "cable": 1,
        "connection_status": {
            "value": true,
            "label": "Connected"
        }
    },
    {
        "id": 1,
        "url": "http://localhost:8000/api/dcim/cables/1/",
        "type": ""
    },
    {
        "id": 1,
        "url": "http://localhost:8000/api/dcim/console-server-ports/2/",
        "device": {
            "id": 2,
            "url": "http://localhost:8000/api/dcim/devices/2/",
            "name": "device2",
            "display_name": "device2"
        },
        "name": "Console Server Port 1",
        "cable": 1,
        "connection_status": {
            "value": true,
            "label": "Connected"
        }
    }
]
```

The goal of object-based permissions is not to entirely hide the existence of every non-viewable object: that would be impractical given the tightly integrated nature of NetBox's data model. Rather, it is to prevent an unauthorized use from viewing any specific details of an object beyond its unique identifier (e.g. its name). For example, a user viewing a device will be able to see what site it's assigned to, even if they don't have permission to view the site itself.

> While still indicating that a connection exists between the visible device and the hidden device, the details of the device it is connected to in the interfaces table and when performing a cable trace should somehow be hidden.

How would you accomplish this considering the output above, bearing in mind that the format of the response must remain consistent?

**Comment by yarnocobussen** [comment]
I'd like to add another point into this topic for your consideration.

If a user only sees "hidden" on the far end of a trace, then it lacks an unique identifier for what's on the other end.
For their own administration, they'd have to come up with their own identifier, and somehow store it somewhere. This results in different tenants using different names to refer to the same object, with each using different methods to store that information.

I can't imagine this being in the spirit of Netbox.

**Comment by jeremystretch** [comment]
We discussed this in today's maintainers' meeting, and the consensus was to leave the current behavior as-is to avoid the problems mentioned above. For people who must have the ability to hide this information from individual users/groups, it probably makes sense to introduce a new `dcim.trace_cable` permission to toggle this ability entirely. I'll leave it to someone in the community to propose that in a separate feature request if desired.
