### ISSUE TITLE
Wrong Redirection on Creating Inventory items

### ISSUE THREAD

**Issue by a31amit** [netbox-community/netbox#4951]
### Environment
* Python version:  3.8
* NetBox version:  2.9-beta1

### Steps to Reproduce
1. Go to Inventory Tab of Device
2. create a new inventory item

### Expected Behavior
After successful creation of inventory item, user should stay on the inventory tab only

### Observed Behavior
Got Redirected to Device Tab rather it should stay on the device inventory item tab. 
This behavior is only found when creating an inventory item.

**Comment by jeremystretch** [comment]
We can fix this easily, however I've opened #4956 propose doing away with the separate inventory view altogether, and simply displaying a device's inventory items on the primary device view alongside its other components. Marking this as blocked pending acceptance of #4956.

**Comment by jeremystretch** [comment]
Opted to proceed with the quick fix for this since #4956 may take some time.
