### ISSUE TITLE
Add support for multiple disks on Virtual Machines and attributes for each disk

### ISSUE THREAD

**Issue by ggiesen** [netbox-community/netbox#4957]
### Environment
* Python version:  3.6.8
* NetBox version:  2.8.8

### Proposed Functionality
For Virtual Machines, NetBox currently only has a single field for Disk size, with no ability to specify multiple disks (and their sizes). I propose that disks be treated much like interfaces, where they can be added with various properties (size, datastore, etc). To take the idea to its logical conclusion, you could add physical partitions (much like you add IP addresses to interfaces now) (and track things like partition type, filesystem, etc), and perhaps even as far down as logical partitions (ie. LVM)

### Use Case
I'm currently using NetBox to provision some basic VMs, but it doesn't handle use cases where you have multiple disks. This would expand NetBox's functionality and make it usable for more than just network device provisioning.

### Database Changes
TBD

### External Dependencies
None likely.

**Comment by lampwins** [comment]
Thank you for submitting this issue, however it appears that this topic has already been raised. Please see
issue #1887 for further discussion.
