### ISSUE TITLE
Unexpected error message on device bulk import into non-existing site

### ISSUE THREAD

**Issue by dare-to-recurse** [netbox-community/netbox#4962]
### Environment
* Python version: 3.6.8
* NetBox version: 2.9-beta1

### Steps to Reproduce
1. Log in with an account that's set as a superuser
2. Attempt to import one or more device instances of any device-type into a non-existing site, e.g. asdfasdf

### Expected Behavior
* An error message informing the user that the site does not exist is displayed

### Observed Behavior
* The error message "Object import failed due to object-level permissions violation" is displayed

**Comment by jeremystretch** [comment]
I'm not able to replicate this on the current `develop-2.9` branch. I get a validation error as expected:

> Row 1 site: Object not found.

Correcting the site field results in the device being imported as expected.

**Comment by dare-to-recurse** [comment]
I'm having no luck reproducing the odd error message in a clean install of the beta either whatsoever.
Probably not worth keeping the issue open?

**Comment by jeremystretch** [comment]
Going to close this out, but please do ask that it be reopened if you happen to replicate it again.

**Comment by roundtripdelay** [comment]
I am experiencing the same issue after a recent upgrade from 2.7.8 to 2.9.3 and receive an "Object import failed due to object-level permissions violation" message.

In my case, we swapped out some PDUs and console servers in some racks. I deleted these devices and then attempted to import the new devices but got the object-level permissions message.

Can we reopen or would a new bug be better? Thanks!

**Comment by roundtripdelay** [comment]
Manually adding the device at https://server/dcim/devices/add/ works.

**Comment by JensBavenmark** [comment]
Got the same error as roundtripdelay.

Am importing a lot of devices with the Device Bulk Import to a new setup of Netbox 2.9.3.

**Comment by JensBavenmark** [comment]
Think I found the reason. I was importing some item that had Device Types that wasnt created in Netbox. After creating them the import worked again. So it seems to just be a case of that the error message is not as clear as would be appreciated.

**Comment by marc-rose** [comment]
I had the same problem importing in v2.9.4, but found I was incorrectly importing by Device Type **model** rather than Device Type **name**

**Comment by SelimBF** [comment]
i had the same problem importing my teammat exported backup to my own netbox but it seem like there some devices undefined or unkown colomun that you try to import .
I suggest that you verify that all collumn in csv file are already defined
