### ISSUE TITLE
Netbox upgrade issue  - service can't start (from 2.2.6 to 2.8.9)

### ISSUE THREAD

**Issue by chaputj** [netbox-community/netbox#4965]
### Environment
* Python version: 2.7.5 (I know Python 3.6 is installed but **python ––version** reports 2.7.5)
* NetBox version: 2.8.9
* CentOS Linux release 7.8.2003 (Core)

### Steps to Reproduce
1. Netbox 2.2.6 was directly installed in /opt/netbox so I renamed it /opt/netbox-2.2.6
2. Install Redis (and add Redis configuration to the configuration.py file)
3. Had to remove python34 (so python36 and all requirements could install)
4. Follow the migration procedure with Netbox 2.8.9 (https://netbox.readthedocs.io/en/stable/installation/upgrading/)
4. Upgrade successful without any errors

### Expected Behavior
Upgrade completed successfully and service can start (as before the upgrade)

### Observed Behavior
The netbox service can't start anymore

Installed gunicorn (following https://netbox.readthedocs.io/en/stable/installation/4-http-daemon/#gunicorn-configuration & https://netbox.readthedocs.io/en/stable/installation/4-http-daemon/#systemd-configuration

Same thing

**systemctl status netbox** attached as a screenshot.

![netbox_service](https://user-images.githubusercontent.com/39830707/89648777-b9f43880-d88d-11ea-9eea-a588b83d31de.PNG)

Thank you

**Comment by lampwins** [comment]
Thank you for your interest in NetBox. GitHub issues are intended for reporting reproducible bugs and requesting features, and must be submitted using one of the templates provided [here (https://github.com/netbox-community/netbox/issues/new/choose). For general discussion, questions, or assistance with installation issues, please post to our [mailing list](https://groups.google.com/forum/#!forum/netbox-discuss) instead.
