### ISSUE TITLE
Device export: Wrong field name "rack_name"

### ISSUE THREAD

**Issue by dreng** [netbox-community/netbox#4970]
### Environment
* Python version: 3.7.3
* NetBox version: 2.8.8

### Steps to Reproduce
1. Navigate to "devices"
2. Click "Export" in the upper right corner
3. Notice field name "rack_name"

### Expected Behavior
Field name should be "rack" instead of "rack_name" as it is required to be like that when you import devices.

**Comment by lampwins** [comment]
As pointed out in #4429 there is not always going to be consistency in the import and export field names for a model.
