### ISSUE TITLE
Storing Secrets for NAPALM usage

### ISSUE THREAD

**Issue by jameskirsop** [netbox-community/netbox#4975]
### Change Type
[X ] Addition
[ ] Correction
[ ] Deprecation
[ ] Cleanup (formatting, typos, etc.)

### Area
[ ] Installation instructions
[ ] Configuration parameters
[ ] Functionality/features
[ ] REST API
[ ] Administration/development
[X ] Other

### Proposed Changes

I'm finding it hard to work out how to _functionally_ use the changes implemented to resolve #2113. It seems that I can pass these headers to the API (eg. using Postman) but how does one configure the Netbox web interface to use these dynamic credentials? There doesn't seem to be any documentation to describe how this should be performed.

For more a concrete definition of the problem, as I understand the original issue, the discussion indicated [a desire to be able to store secrets](https://github.com/netbox-community/netbox/issues/2113#issuecomment-405950228) in Netbox, or [in the Contextual Configuration Data](https://github.com/netbox-community/netbox/issues/2113#issuecomment-493911067) and then use these to pass along to NAPALM. If #2113 was indeed resolved according to the issue's discussion, then the `Status` and `LLDP Neighbours` tabs should be sending device credentials (and other NAPALM options if specified) to the API using the `X-NAPALM-*` headers - but I can't find anything to describe how this would be configured in the Netbox interface.

I could be misunderstanding the original issue, or the PR's attempt to address it, so this may need to become a feature request rather than a documentation change.

**Comment by jeremystretch** [comment]
> but how does one configure the Netbox web interface to use these dynamic credentials?

This is not currently supported by the UI. The assumption is that if you're passing unique credentials to each device, you're probably (hopefully) using the REST API endpoint directly.

> If #2113 was indeed resolved according to the issue's discussion

No specific implementation was ever proposed in #2113, but the addition of support for passing NAPALM credentials seemed adequate given the use case cited. If you'd like to open a new feature request for it, you're certainly welcome to do, but bear in mind that you'll need to propose a specific functionality and workflow (which #2113 did not).

**Comment by DanSheps** [comment]
Closing this as it is superseded by #4980
