### ISSUE TITLE
Value expansion in the CSV Field Options

### ISSUE THREAD

**Issue by axlgit** [netbox-community/netbox#4976]
### Environment
* Python version:  3.7.3
* NetBox version:  2.8.8

When proposing the CSV Field Options form provide an expandable list with the accepted values.
### Proposed Functionality
One way to "discover" the values for bulk import is to add one element but for some functionalities the "ADD" button is not there, we cannot import one single element. Currently I'm struggling at guessing which value the CSV bulk import accepts in the form

https://netbox-server/dcim/interfaces/import/

(and I will ask for help in the support group)

Another way would be to have one single page in the tool itself where to find all the values accepted but the in-the-form might be more usable.

Or at least when reporting the error it would be useful to display the values accepted.

### Use Case
When bulk importing the user will know always which values are accepted
### Database Changes
The proposal doesn't require any changes in the DB
### External Dependencies
No new dependencies

**Comment by jeremystretch** [comment]
I'm sorry but I don't follow what you're proposing. Could you please rewrite your initial post above to clearly propose a specific change and provide a detailed use case?

**Comment by jeremystretch** [comment]
Closing due to lack of a response.
