### ISSUE TITLE
Use UUID as primary key for JobResult model

### ISSUE THREAD

**Issue by jeremystretch** [netbox-community/netbox#4981]
### Proposed Changes
#2006 introduced a new JobResult model to enable background processing of reports and custom scripts. Like every other model in NetBox, JobResult includes an auto-incrementing integer field (`id`) which it uses as its primary key in the database. It also includes a randomly-generated UUID field, named `job_id`. I opened this issue to propose using `job_id` as the primary key for the model, and removing the built-in `id` field.

### Justification
- Eliminates a redundant unique field
- JobResult instances are ephemeral in nature, so there's no need for a permanently sequential ID
- The model already has `created` and `completed` timestamp fields to allow chronological ordering in either respect

I'm not 100% sold on the proposal myself, but wanted to open it up for discussion.

**Comment by minitriga** [comment]
I have a plugin that currently utilises the JobResults table and API endpoints. I don't think I have anything that would cause me not to support this change at the moment.

**Comment by jeremystretch** [comment]
In the interest of ensuring consistency across all REST API endpoints, I'm going to leave this as-is. JobResults can still be referenced by UUID, but the integer primary key attribute (`id`) will be used as the primary ID for the model.
