### ISSUE TITLE
Inconsistent Interface ordering after #4336 fix

### ISSUE THREAD

**Issue by JulianJacobi** [netbox-community/netbox#4984]
### Environment
* Python version: 3.7
* NetBox version: 2.8.6

### Steps to Reproduce
1. Start with Netbox Version <= 2.7.9
2. Create device Foo with interfaces [`Po1`, `Po1.155`, `Po1.156`]
3. Update Netbox to version 2.8.6
4. Add Interface `Po.2522` to device Foo

### Expected Behavior
Interface ordering is:
* `Po1`
* `Po1.155`
* `Po1.156`
* `Po1.2522`

### Observed Behavior
Interface ordering is:
* `Po1.2522`
* `Po1`
* `Po1.155`
* `Po1.156`

### Additional Thoughts
After a little bit of research I found #4336 and see that the fix changes the way the `interface._name` field is calculated for ordering. After looking into my database I there was the "old" interfaces has `_name` created with the "old" style and the new interface has `_name` created with the new style:

name | _name
--- | ---
`Po1` | `9999999999999999Po000001000000000000`
`Po1.155` | `9999999999999999Po000001000000000155`
`Po1.156` | `9999999999999999Po000001000000000156`
`Po1.2522` | `9999999999999999Po000001......002522`

**Comment by jeremystretch** [comment]
We may have neglected to include a migration to update the names as part of that fix. Does running `manage.py renaturalize dcim.Interface` fix this?

**Comment by JulianJacobi** [comment]
>Does running manage.py renaturalize dcim.Interface fix this?

Yes, everything is fine now.

Thanks for the help.
