### ISSUE TITLE
Define error responses for endpoints in the swagger spec

### ISSUE THREAD

**Issue by joakimhellum** [netbox-community/netbox#4986]
### Environment
* Python version:  N/A
* NetBox version:  103a0e2b32d1 (v2.8.9)

### Proposed Functionality
Define error responses for endpoints in the swagger spec.

### Use Case
Currently the swagger spec does not have any default / error responses defined for the endpoints. This is an issue for some code generators like `go-swagger` and `AutoRest`.

We are facing some issues using the [official NetBox SDK for Go](https://github.com/netbox-community/go-netbox) which is generated by `go-swagger`. For example, the following error message is not very helpful:
```
unknown error (status 400): {}
```

I think this happens because we cannot obtain the underlying `http.Response` if the StatusCode is not defined in the swagger spec. We could implement workaround which allows `http.Response.Body` to be accessed anyway, but this feels very hacky.

Can we expect default / error responses to be added for the endpoints in the swagger spec in a future version?

Many thanks for your advice!

### Database Changes
N/A

**Comment by lampwins** [comment]
@joakimhellum are you able to take this issue on? We currently only support the swagger spec as best effort due to the way in which it is generated, so without community support, this is not likely to get much traction.

**Comment by joakimhellum** [comment]
@lampwins Yes, happy to take on this issue. We already started experimenting with this at work last week.

**Comment by jeremystretch** [comment]
@joakimhellum Have you been able to make any progress with this?
