### ISSUE TITLE
Prevent devices being added to reserved rack positions

### ISSUE THREAD

**Issue by amuckart** [netbox-community/netbox#5001]
### Environment
* Python version:  3.6.9
* NetBox version: 2.8.9

### Proposed Functionality
When a rack position has a reservation associated with it, it should not be possible to add a device in that position without amending the reservation.

### Use Case
At the moment if a rack position has a reservation, the 'add device' link still shows up and allows a device to be placed there without interacting with the reservation in any way. 

This can lead to reservations being ignored, or reservations not being removed when the related equipment is installed. It can also mean someone can accidentally overlap a reservation by putting a 2U device in the position immediately below a reservation.

It would be good if reservations had to be explicitly removed to allow the placement of devices in the reserved positions, and if reserved positions didn't show up in the selectable list of positions when adding a device.

### Database Changes
I don't know, sorry.

### External Dependencies
None I can think of.

**Comment by jeremystretch** [comment]
This was considered when rack reservations were initially implemented. After some experimentation, I found that forcing the modification or deletion of a reservation prior to the installation of a device was disruptive to the workflow and led to user frustration. Additionally, enabling the reservation of currently occupied units within a rack allows the user to designate a future use without having to delete the devices which are already present. IMO, the current behavior is preferable.

**Comment by xkilian** [comment]
Without changing the current logic. 
I would suggest that the current workflow could be improved by having a popup notification (space is reserved for blah blah by xx) when assigning a device to a position that is reserved, and maybe easing the complete workflow by providing a link to open another browser tab to modify/update the involved reservation (if the change is related to the reservation). 
I haven't worked with reservations so maybe this is already there..

**Comment by jeremystretch** [comment]
@xkilian the current UI framework unfortunately doesn't provide this sort of functionality without a disproportionate amount of effort.

**Comment by xkilian** [comment]
Could a banner message or any other way be used to flag/communitate the information to the user within the workflow that this position is reserved and its state should be updated if applicable?

I would also suggest having the information that a reserved position DDD in rack XXX was assigned/used by ZZZ in the change log.

**Comment by yarnocobussen** [comment]
> Additionally, enabling the reservation of currently occupied units within a rack allows the user to designate a future use without having to delete the devices which are already present. IMO, the current behavior is preferable.

Losing this functionality would probably be detrimental to many organizations. We're using this as well.

I can imagine the proposed behaviour could be added as a switch in configuration.py, in case this goes through. A simple true/false for enforcing or not enforcing clearing reservations first, with the default being not enforcing.
