### ISSUE TITLE
Swagger spec for available-prefixes are incorrect

### ISSUE THREAD

**Issue by joakimhellum** [netbox-community/netbox#5002]
### Environment
* Python version: N/A
* NetBox version: 103a0e2b32d1 (v2.8.9)

### Steps to Reproduce
The swagger spec states that POST `/ipam/prefixes/{id}/available-prefixes/` returns list of `AvailablePrefix` objects, but it seems to actually return list of `Prefix` objects or single `Prefix` object depending on what is requested.  

### Expected Behavior
Expected the following command to return list of `AvailablePrefix` objects:
```
curl -X POST "https://localhost:8000/api/ipam/prefixes/<prefix-id>/available-prefixes/" -H "Authorization: Token <token>" -H "Content-Type: application/json" -d "{ \"prefix_length\": 24}"
```

### Observed Behavior
But instead returned what looks like a single `Prefix` object:
```
{"id":169,"family":{"value":4,"label":"IPv4"},"prefix":"10.0.1.0/24","site":null,"vrf":null,"tenant":null,"vlan":null,"status":{"value":"active","label":"Active","id":1},"role":null,"is_pool":false,"description":"","tags":[],"custom_fields":{},"created":"2020-08-14","last_updated":"2020-08-14T12:27:01.701782Z"}
```

Reference to:
https://github.com/netbox-community/netbox/blob/v2.8.9/netbox/ipam/api/views.py#L83

Happy to create pull create to fix this.

**Comment by lampwins** [comment]
The Prefix serializer is the correct response, so we would want to adjust the spec as such.
