### ISSUE TITLE
NAPALM import error

### ISSUE THREAD

**Issue by githubannie** [netbox-community/netbox#5007]
### Environment
* Python version: 3.7
* NetBox version: 2.7

### Steps to Reproduce
1. sudo -H pip3 install napalm
2. configure the platform with napalm driver, "ios"
3. assign the platform to switch

### Expected Behavior
Netbox should get the configuration from the switch

### Observed Behavior
Error on GUI: "Napalm is not installed. Please see the documentation for instructions."
But actually, Napalm has been installed successfully and the command "napalm 10.1.1.1 --vendor ios --user admin --debug" works.

**Comment by jeremystretch** [comment]
Thank you for submitting this issue. Before any further work can be done, please upgrade to the most recent stable release of NetBox (currently v2.8.9) as this issue may have already been addressed. Please then update your issue to indicate whether further action is needed.

**Comment by githubannie** [comment]
Thanks so much for reply. The issue has been resolved after upgrading to v2.8.9.
The ticket can be closed.

**Comment by githubannie** [comment]
it works after upgrading to v2.8.9
