### ISSUE TITLE
Standardize model name field lengths

### ISSUE THREAD

**Issue by ledgley** [netbox-community/netbox#5011]
### Environment
* Python version:  
* NetBox version:  2.8.9

### Proposed Functionality
Increase `max_length` of the 'name' field under the IPAM.Service model from 30 to 255

```
    name = models.CharField(
        max_length=255
    )
```

### Use Case
We use this model to track services hosted on load balancers, as a one stop view to find a particular farm across a large estate of ADC's. We use the name field as the farm name, which is typically a URL, which is commonly longer than 30 characters. Propose to increase to 255, as the maximum length of a domain name is 253 chars.

### Database Changes
---

### External Dependencies
None

**Comment by DanSheps** [comment]
#4416 didn't appear to increase this

**Comment by jeremystretch** [comment]
> We use the name field as the farm name, which is typically a URL

I don't know what you mean by "farm name," but this field is not intended to represent a URL. The service name should be a human-friendly string.

**Comment by ledgley** [comment]
> I don't know what you mean by "farm name,"

By farm name I mean the name of the 'server farm', which is typically referenced by it's URL, ie. intranet.company.com

**Comment by jeremystretch** [comment]
This issue was originally opened to extend the length of the `name` field for the Service model, but there are probably others to revisit as well.

Tagging this v2.10 so I remember to conduct an audit.
