### ISSUE TITLE
A Exception in Custom Scripts and Reports is not show in the results.

### ISSUE THREAD

**Issue by rebortg** [netbox-community/netbox#5012]
### Environment
* Python version: 3.7 (netbox-docker)
* NetBox version: 2.9-beta2

### Steps to Reproduce

myscryipt.py:

```
class MyScript(Script):
    class Meta:
        name = "Script Test"

    def run(self, data, commit):
        raise Exception

```
 
myreports.py:
```
from extras.reports import Report


class ReportTest(Report):
    def test_one(self):
        raise Exception
```

### Expected Behavior

Script in v2.8.9:
![image](https://user-images.githubusercontent.com/24626486/90479011-52ac7300-e12e-11ea-9deb-c92b0ec176f9.png)

Report in v2.8.9:
![image](https://user-images.githubusercontent.com/24626486/90478883-1416b880-e12e-11ea-98fb-41e3098401f0.png)

### Observed Behavior
Scripts in 2.9-beta2:
![image](https://user-images.githubusercontent.com/24626486/90477900-8090b800-e12c-11ea-9087-b4d86c43aa2e.png)

Reports in 2.9-beta2:
![image](https://user-images.githubusercontent.com/24626486/90479506-1594b080-e12f-11ea-81fd-30067f43b6c0.png)

This make it very hard to debug a custom script or report.

**Comment by dgarros** [comment]
I'm got the same issue and I agree it's hard to troubleshooting what is happening in the reports/scripts (running 2.9-beta2)
Even in the worker log I'm not getting a lot of information, just the error message not the stacktrace

**Comment by jeremystretch** [comment]
@lampwins want to take this one?
