### ISSUE TITLE
Add USB version to USB console port types (interface speed)

### ISSUE THREAD

**Issue by ypid** [netbox-community/netbox#5013]
### Environment
* Python version: 3.7.3
* NetBox version: 2.8.9

### Proposed Functionality

USB console port types should include the interface speed (USB version). Compared to network interfaces, USB is missing interface speed info.

https://en.wikipedia.org/wiki/USB#Receptacle_(socket)_identification

For backwards compatibility, a unspecific USB port (A, B, C) might still be retained.

For new device types, only precise USB ports should be selectable. When importing device types, the unspecific USB ports are probably needed for backwards compatibility also for a while.

Alternative in case this misses the scope of Netbox, maybe add the field "Description" that is present for devices but not device types. So that the admin could pre-populate such details there.

### Use Case

For attaching peripherals, for example attaching an external disk via USB to a NAS or server, the USB interface speed makes a difference.

### Database Changes

Yes.

### External Dependencies

None that I am aware of.

**Comment by DanSheps** [comment]
We generally don't denote speed (A/B/C) however we will denote type (mini, micro, etc).

**Comment by jeremystretch** [comment]
NetBox currently provides the following options for USB console ports:

```
(TYPE_USB_A, 'USB Type A'),
(TYPE_USB_B, 'USB Type B'),
(TYPE_USB_C, 'USB Type C'),
(TYPE_USB_MINI_A, 'USB Mini A'),
(TYPE_USB_MINI_B, 'USB Mini B'),
(TYPE_USB_MICRO_A, 'USB Micro A'),
(TYPE_USB_MICRO_B, 'USB Micro B'),
```

> For attaching peripherals, for example attaching an external disk via USB to a NAS or server, the USB interface speed makes a difference.

This is not a valid use of the console port model, as these are not console connections. NetBox does not support modeling such peripheral components.

**Comment by ypid** [comment]
Fine with me.

> Alternative in case this misses the scope of Netbox, maybe add the field "Description" that is present for devices but not device types. So that the admin could pre-populate such details there.

Would that be an option to allow some forms of "misuse" as I seem to be doing it then with Netbox? I guess it should then also be added to other components. For this I see more "valid" use cases like device types where LAN1 has specific hardware configuration (like with consumer "access points" where one port is usually directly connected to the CPU, the others to a integrated switch so it makes sense to differentiate them even if their name does not tell this technical side of it).

**Comment by jeremystretch** [comment]
A description field was added for all device type components under #4793 for the upcoming v2.9 release, however I don't see how that would be relevant to this issue.

I'm going to close this issue as it seems that the proposed use case is firmly out of scope.

**Comment by ypid** [comment]
#4793 should solve it for me, thanks!
