### ISSUE TITLE
Consider adding support for native redis cluster

### ISSUE THREAD

**Issue by gedia** [netbox-community/netbox#5017]
### Proposed Functionality
Support native redis clusters by migrating to https://github.com/Grokzen/redis-py-cluster which is supposed to be a (mostly) drop-in replacement for redis-py. Functionality should include honouring MOVED responses and auto-discovery of redis cluster nodes if not explicitly provided in netbox configuration.

### Use Case
For installations where there is already a functioning redis cluster deployment, it would be useful to support its use by netbox as well instead of having to deploy a local redis instance just for netbox.

### Database Changes
None that I'm aware of

### External Dependencies
https://github.com/Grokzen/redis-py-cluster

**Comment by DanSheps** [comment]
This does not appear to be a trivial change, nor is it a "drop in" for redis-py (you need specific configuration and utilization for it).  We currently use django-cacheops and not redis-py directly, this is also not supported in django-cacheops.  You will need to raise this upstream in django-cacheops (looks like it might be at Suor/django-cacheops#35)

**Comment by gedia** [comment]
Got it. Thanks!
