### ISSUE TITLE
upgrade.sh doesn't pull setuptools>=36

### ISSUE THREAD

**Issue by konaya** [netbox-community/netbox#5019]
### Environment
* Python version: 3.8.5
* NetBox version: 2.8.9

### Steps to Reproduce
1. Upgrade from v2.6.3 to v2.8.9 using git
2. Run `upgrade.sh`. (I also pulled `django-auth-ldap` since we use LDAP, but I don't know if it's needed for reproducing this issue)
3. Try to visit e. g. a tenant page.

### Expected Behaviour

The tenant page should open.

### Observed Behaviour

The following exception is thrown:

```
<class 'pkg_resources.VersionConflict'>

(setuptools 33.1.1 (/opt/netbox/venv/lib/python3.8/site-packages), Requirement.parse('setuptools>=36'))
```

### Workaround

Either adding `setuptools>=36` to `requirements.txt` and running `upgrade.sh` again or just running `pip install setuptools>=36` within the environment fixed the error.

### Proposed solution

Add `setuptools>=36` to `requirements.txt`.

**Comment by jeremystretch** [comment]
This appears to be an issue with your local environment. Try upgrading pip and then recreating the virtual environment. If you still need further assistance, please post to the [mailing list](https://groups.google.com/forum/#!forum/netbox-discuss).
