### ISSUE TITLE
Rate limiting for error emails sent to admins

### ISSUE THREAD

**Issue by tyler-8** [netbox-community/netbox#5023]
### Environment
* Python version:  3.6.8
* NetBox version:  2.8.8

### Proposed Functionality
Implement rate-limiting of emails sent to admins based on repeat errors. There are a couple existing Django plugins as an option, or a [custom-built](https://stackoverflow.com/a/25889167) implementation that utilizes the redis cache that would work. redis is the ideal method of tracking the error rate for sending emails as it would ensure NetBox deployments of all kinds (load balanced, k8s, docker, standard install) would all be appropriately rate-limited.

I don't think this could be implemented as a NetBox plugin as it would require modifying some of the 'core' Django bits of the NetBox codebase.

### Use Case

- Database or other network maintenance that may affect NetBox environment: if the database isn't reachable/resolvable during a time period, the NetBox admins can be spammed with anywhere from dozens to hundreds (or thousands) of emails within a very short (1-5 minutes) timespan
- Security scanning systems, during their work, will attempt many malformed and known "bad" requests that will succeed through nginx (or whatever reverse-proxy) and be parsed by Django/NetBox and could create an email flood as in the above case

Having a rate-limiting mechanism to reduce the number of emails sent for the same exact error condition in a short time span would significantly reduce error emails. The emails can be extremely useful for admins to troubleshoot valid issues as it contains full stack traces and other environment variables so disabling the feature entirely would be a loss of vital information for debugging problems.

### Database Changes

Depending on implementation there could be changes if any of the configuration was chosen to be exposed through the admin panel, though I think environment variables/configuration parameters would be enough.

### External Dependencies

- redis
- some django plugin, though none of the options ([1](https://github.com/robert-kisteleki/django-email-throttler), [2](https://github.com/krisys/django-error-email-throttle)) I could find were completely up to date or used only the local fileystem to track rate limit

**Comment by tyler-8** [comment]
The more I look at this I think it could actually be done as a part of `configuration.py` with a custom handler. The one possible snag being the interaction with `redis` itself and keeping the key names de-conflicted. I'll tinker and report back in this issue but I suspect this may not require an official feature afterall.

**Comment by jeremystretch** [comment]
@tyler-8 Have you made any further progress regarding your comment above?

**Comment by tyler-8** [comment]
I've been testing with the custom handler and it's not going to be able to live in the `configuration.py` due to the way Django looks up handlers. For now, I'm tinkering with a `netbox/handlers.py` module (same directory as `settings.py`). At the moment it doesn't appear to be working. I'm still receiving the emails but the throttling isn't working yet.

```python
# handlers.py
import datetime
import time

from django.utils.log import AdminEmailHandler
from cacheops.redis import redis_client  # This uses the redis server configured for `caching`


class AdminEmailThrottle(AdminEmailHandler):
    def incr_counter(self):
        c = redis_client()
        key = self._redis_key()
        res = c.incr(key)
        c.expire(key, 300)
        return res

    def _redis_key(self):
        return time.strftime(
            r"error_email_limiter:%Y-%m-%d_%H:%M", datetime.datetime.now().timetuple()
        )

    def emit(self, record):
        try:
            ctr = self.incr_counter()
        except Exception:
            pass
        else:
            if ctr >= 10:
                return
        super(AdminEmailThrottle, self).emit(record)

```

```python
# logging config
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'mail_admins': {
            'level': 'ERROR',
            'class': 'netbox.handlers.AdminEmailThrottle'
        }
    },
    'loggers': {
        'django': {
            'handlers': ['mail_admins'],
            'level': 'ERROR',
            'propagate': True,
            },
        }
}
```

**Comment by tyler-8** [comment]
As far as requiring a built-in feature, I don't think it will be necessary - assuming I can get my above method working. The `handlers.py` would be treated similar to how the `ldap_config.py` is today (as an optional module that the user has to create), and the `configuration.py` logging dict just has to reference its import path.

**Comment by tyler-8** [comment]
Got it working. the `redis_client` object has a [decorator](https://funcy.readthedocs.io/en/stable/objects.html?highlight=LazyObject#LazyObject) on it that changes how you interact with it. So this line `c = redis_client()` was incorrect (and redundant). I tweaked some things but this is basically what was used in the StackOverflow from the OP.

I think this could make for a good feature to build in - however it is possible to do on your own. The below handler could be fleshed out some more to have a setting for the throttling rate in `configuration.py`. This is also a very basic throttler - it's purely based on rate, there's no checking/hashing for throttling repeats of the same exact event, but it definitely gets the job done.

```python
# handlers.py
import datetime
import time

from django.utils.log import AdminEmailHandler
from cacheops.redis import redis_client


class AdminEmailThrottle(AdminEmailHandler):

    THROTTLE_PERIOD_SECONDS = 60  # possibly pull from settings
    MAX_EMAILS_PERIOD = 5  # possibly pull from settings
    COUNTER_CACHE_KEY = "email_admins_counter"

    def increment_counter(self):
        result = redis_client.incr(self.COUNTER_CACHE_KEY)
        redis_client.expire(self.COUNTER_CACHE_KEY, self.THROTTLE_PERIOD_SECONDS)
        return result

    def emit(self, record):
        try:
            counter = self.increment_counter()
        except Exception:
            pass
        else:
            if counter > self.MAX_EMAILS_PERIOD:
                return
        super(AdminEmailThrottle, self).emit(record)

```

**Comment by jeremystretch** [comment]
@tyler-8 thank you for sharing your solution! As this is a general-purpose function in Django and not specific to NetBox, I don't think it makes much sense for us to take on maintenance of it. It would be better suited as a feature implemented within the Django framework itself. And since it's already possible to accomplish as you've demonstrated, I'm going to close this out. Thanks again!
