### ISSUE TITLE
Custom Field filter on e.g. type

### ISSUE THREAD

**Issue by chas0rde** [netbox-community/netbox#5025]
### Environment
* Python version:  2,7,17
* NetBox version:  2.8.8

### Proposed Functionality
Allow custom fields to be shown based on filters

### Use Case
e.g. one could have a custom field "CPU type" which is applied to devices and only shown if the Device Type is e.g. Server
This could allow much more dynamic inventory of datacenter equipment and allow for further tasks like utilizing such information for determining license demand and such

### Database Changes
Don't know

**Comment by kobayashi** [comment]
Is this same as [Filtering by Custom Field](https://netbox.readthedocs.io/en/stable/rest-api/filtering/#filtering-by-custom-field)?

**Comment by DanSheps** [comment]
Are you proposing a API change?  A UI change?  Does the functionality outlined by @kobayashi suit you?

**Comment by chas0rde** [comment]
Hello
No its not the same. I am talking about an UI change I guess.
The idea is based on how Icinga Director handles custom fields. Basically there it is possible to hide a field on the UI if certain criteria are not met. See [https://icinga.com/docs/director/latest/doc/16-Fields-example-SNMP/](https://icinga.com/docs/director/latest/doc/16-Fields-example-SNMP/)
Custom fields in netbox are currently always shown. If you handle several device types in netbox with lots of information it might get hard to use due to lots of not-needed fields.
E.g would a field „CPU type“ be nice for servers but is not required for other racked devices
This way the input can be much more dynamic allowing efficient inventory of Datacenter devices

**Comment by jeremystretch** [comment]
This sounds well beyond the intended scope for custom fields. The need to toggle visibility of a custom field based on other criteria suggests that the data doesn't belong in NetBox to begin with.

**Comment by chas0rde** [comment]
Hello
What specifically is the intended scope?
I always understood netbox as a dcim sort of. Thus I would like to have all relevant information about my Datacenter and idf equipment documented there

Best regards

**Comment by jeremystretch** [comment]
> What specifically is the intended scope?

The proposed enhancement:

> Allow custom fields to be shown based on filters

> I always understood netbox as a dcim sort of.

And it is. However it can fulfill that function without the proposed enhancement.
