### ISSUE TITLE
Allow Racks to show Device Front and Back Images based on Device 

### ISSUE THREAD

**Issue by a31amit** [netbox-community/netbox#5028]
### Environment
* Python version:  3.8
* NetBox version:  2.9

### Proposed Functionality
Currently, Racks view shows Device Front and Back Images based on DeviceType however there is no way to use device image based on the device itself to display in Racks. This will help users see device pictures for customized hardware and commodity vendors.

### Use Case
We are using some custom build hardware also many commodity vendors have allow their customers to use different chassis or form factors with customized hardware. Thus we had to create a custom device type based on their form factor as chassis type is a generic rather very specific model as this allow to put the same Motherboards and hardware parts in different form factor. 

Hence servers with the same specs and same internal parts model can have different form factors for chassis. Allowing per Device Front / Back images would help users to see device images especially to see what are available ports / disks slots supported in chassis.

Example - 

ServerA - 1U form factor with 2 disk slots with Motherboard Model XXXX1111
ServerB - 4U form factor with 24 disk slots with Motherboard Model XXXX1111

Please note that because commodity hardware vendors allow customization of hardware, most of time there is no Chassis Model available to query or see as these form factors are very generic or many times these were never been ever updated in DMI data by commodity hardware vendors. 

Using existing methods to display images from DeviceType would lead users to a lot of custom DeviceType multiple to each Motherboard Model.

### Database Changes
May be extending Models. 

### External Dependencies
Not sure

**Comment by jeremystretch** [comment]
This possibility was discussed under #1529 and it was decided to support images only per the device type model. Images are supported for convenience and cosmetic appeal only; they are not intended to convey meaningful data concerning the devices they represent.

> We are using some custom build hardware also many commodity vendors have allow their customers to use different chassis or form factors with customized hardware.

These would need to be modeled as different device types anyway.
