### ISSUE TITLE
Permission constraints not working

### ISSUE THREAD

**Issue by hyudra** [netbox-community/netbox#5047]
### Environment
* Python version: 3.6.8
* NetBox version:  2.9.1
* Build with latest netbox-docker build-latest.sh

### Steps to Reproduce
Trying apply constraints in permission on GUI. It got error return as 

> Invalid filter for <class 'dcim.models.device_components.ConsolePort'>: Cannot resolve keyword 'tenant' into field. Choices are: _cabled_as_a, _cabled_as_b, _name, cable, cable_id, connected_endpoint, connected_endpoint_id, connection_status, description, device, device_id, id, label, name, tagged_items, tags, type

constraints using:

`{"tenant__group__name": "Test_Group"}`

**Comment by jeremystretch** [comment]
Yes, that's an invalid filter as the error message indicates. There is no direct relation from the a console port to a tenant. Please post to the mailing list for further assistance.

**Comment by hyudra** [comment]
Why it's using console.port class on permission constraints?

**Comment by hyudra** [comment]
So, how to avoid to not have constraints not look into console section?

How can I filter it out?
