### ISSUE TITLE
Display the Device name when editing an Interface

### ISSUE THREAD

**Issue by tristanbob** [netbox-community/netbox#5048]
### Environment 

* Python version:  Unknown
* NetBox version:  2.9.0

### Proposed Functionality

Display the relevant Device name when Editing an Interface.
https://netbox.mydomain.com/dcim/interfaces/1389/edit/

### Use Case

When editing an Interface, there is no way to know which Device you are editing.  I started making changes to an Interface, but then started worrying that I was editing the wrong device.  I had to go back to verify and start over. 

### Database Changes

None.

### External Dependencies

None.

**Comment by DanSheps** [comment]
Are you willing to take this on @tristanbob?

**Comment by tristanbob** [comment]
I spent about 1 hour looking into this, which was enough time to know that it would take me tens of hours to make this minor change.  (I have very basic programming skills, and no experience with Django).

It looks like the change would involve editing "netbox/templates/dcim/interface_edit.html", but I'm not certain what else might need to be changed.

Do you think editing an interface should use the same format as editing a Tenant?  It has a separate table to show the name of the Tenant and the Group it belongs to.  This could show the Interface and the Device it belongs to.

**Comment by bcohee** [comment]
Inline style to add the device name to the would be to check if the obj_type is type interface and add a { obj.device } to the panel title here - https://github.com/netbox-community/netbox/blob/develop/netbox/templates/utilities/obj_edit.html#L19

I do not know the django / model syntax to do so though.

or quick and ugly could add `<h3>{% block title %}Device {{ interface.device }}{% endblock %}</h3>` to the top line of https://github.com/netbox-community/netbox/blob/develop/netbox/templates/dcim/interface_edit.html
