### ISSUE TITLE
LLDP Virtual-Chassis Neighbor

### ISSUE THREAD

**Issue by tobzsc** [netbox-community/netbox#5049]
### Environment
* Python version:  3.6.8
* NetBox version:  2.9.1

### Proposed Functionality
When doing a LLDP query in the frontend on a device connected to a virtual-chassis, the LLDP neighbor is shown as the specific member of the virtual-chassis. NetBox 2.9 now has a virtual-chassis name. It would be nice to use the virtual-chassis name instead of the member name here.

<img width="1614" alt="LLDP Neighbor VC" src="https://user-images.githubusercontent.com/1703330/91187585-9e43bb80-e6f0-11ea-93ab-b848e2c1e45d.png">

### Use Case
Use the new Virtual-Chassis member name and have the LLDP neighbors correctly shown.

### Database Changes
none

### External Dependencies
none

**Comment by DanSheps** [comment]
My question would be, can we be sure 100% of the time that the virtual chassis name would be the neighbor name?

**Comment by tobzsc** [comment]
We are using VC with Juniper devices. Here I configure hostname which is valid for the complete VC. I don't know if there are any options to name a single member of VC.

**Comment by dotpy88** [comment]
I just ran across this same issue.  Using virtual chassis for Cisco stackwise, LLDP neighbor is showing the virtual chassis name and not the device name so you get the RED row indicating something is different.  

![image](https://user-images.githubusercontent.com/31436955/93716815-5f5e2580-fb37-11ea-9c14-054293e2cf4b.png)

**Comment by tobzsc** [comment]
So will this now be closed without further activity? Thought @DanSheps will takeover as he was assigned.

**Comment by DanSheps** [comment]
Sorry, this was something I was going to work on and just haven't had time yet.  I will get working on it shortly.
