### ISSUE TITLE
Global search on Device/VM Interfaces

### ISSUE THREAD

**Issue by candlerb** [netbox-community/netbox#5054]
### Environment
* Python version:  3.6.9
* NetBox version:  2.9.1

### Proposed Functionality

Include "interfaces" in the global search

### Use Case

* Global search by MAC address
* Global search by interface name, e.g. "wl0"
* Global search by interface description

These are currently possible only if you go to "devices" and "virtual machines" (or "devices > interfaces", "virtual machines > interfaces") and search them separately.

### Database Changes

None

### External Dependencies

None

**Comment by jeremystretch** [comment]
Thank you for submitting this issue, however it appears that this topic has already been raised. Please see issue #4757 for further discussion.
