### ISSUE TITLE
Include tags in Device/VM interface list views

### ISSUE THREAD

**Issue by candlerb** [netbox-community/netbox#5055]
### Environment
* Python version: 3.6.9
* NetBox version:  2.9.1

### Proposed Functionality

Device Interface and Virtual Machine Interface models have Tags (by which I mean Netbox organizational tags, not VLAN tags)

However if you go to the listing pages `/dcim/interfaces/` and `/virtualization/interfaces/` and click the `Configure` button, you cannot currently select the Tags as a column to display.

I would like Tags to be available as a display column, as it is for Devices, Virtual Machines, IP Addresses etc.

### Use Case

Browse list of interfaces, quickly identify those with a given tag.

Click on tag to filter to all interfaces with that tag.

### Database Changes

None

### External Dependencies

None

**Comment by jeremystretch** [comment]
Closed by fa73bf8e872a3fb5a4d4508bd82e2a9945484b2d (I typoed the issue number in the commit message)
