### ISSUE TITLE
List items tagged with a specific tag

### ISSUE THREAD

**Issue by marinbernard-pep06** [netbox-community/netbox#5057]
### Environment
* Python version:  3.6.8
* NetBox version:  2.9.1

### Proposed Functionality
Currently, Netbox allows to list the number of items tagged with each tag, but offers no simple way to list those items. I propose to add a view to display a list of all items tagged with a specific tag. The user would access this view by clicking on the tag name.

This feature request was first [discussed on the mailing list](https://groups.google.com/g/netbox-discuss/c/jtNTDfaPSrk).

### Use Case
This change would allow a user to list arbitrary items flagged with a specific tag. Internally, we use tags to flag items needing attention. This would greatly improve the work or our support team.

### Database Changes
None.

### External Dependencies
None.

**Comment by jeremystretch** [comment]
This is because listing various types of objects together often doesn't make sense. Each model has its own set of attributes that help uniquely distinguish it to the user, and these are impossible to combine in a single table. For example, it would not make sense to list the same IP address multiple times without also displaying the VRF to which each is assigned, but that wouldn't make sense when also showing devices. It's also extremely inefficient to pull in arbitrary objects by following every tag assignment.

To find items with a particular tag assigned, you'll need to first navigate to the list view for that model, and then filter by the desired tag. (Also note that when viewing a particular object, clicking on an assigned tag will take you to a list of all objects of that type with the tag assigned.)

**Comment by marinbernard-pep06** [comment]
> To find items with a particular tag assigned, you'll need to first navigate to the list view for that model, and then filter by the desired tag. (Also note that when viewing a particular object, clicking on an assigned tag will take you to a list of all objects of that type with the tag assigned.)

Yes, this is convenient enough as long as the model has a view, but it's not always true: for instance, we would really need a way to list all front ports/rear ports/interfaces flagged a specific tag, regardless of the owning device, as it would allow us to easily tag identify failed/misconfigured ports and list them when needed. Today, we know how many of these ports have a specific tags, but we're unable to know which ones.

**Comment by marinbernard-pep06** [comment]
Well, I just discovered that front ports et al. had a view. Sorry for the noise. Thank you!

**Comment by Tavoons** [comment]
Instead of listing them, just put links to the views.
For example, if I have 100 IPs and 20 devices with the same tag, just put a link to `/ipam/ip-addresses/?q=&tag=TAG` and `dcim/devices/?q=&tag=TAG`
It will help us to remember what objects are tagged

**Comment by exokernel** [comment]
@jeremystretch 

> This is because listing various types of objects together often doesn't make sense. Each model has its own set of attributes that help uniquely distinguish it to the user, and these are impossible to combine in a single table.

I'm really curious as to why this was possible in 2.8 but no longer in 2.9? Was it just extremely inefficient in 2.8 and therefor dropped? Did something change with the models that actually makes it impossible? This was a really nice feature of 2.8 that's now missing. :(

**Comment by jeremystretch** [comment]
> Was it just extremely inefficient in 2.8 and therefor dropped?

**Comment by robbagithub** [comment]
So if you don't know what object has the tag "xyz" then you have to search each object type to find it?

This seems exceptionally inefficient.

**Comment by exokernel** [comment]
@jeremystretch 

I really think this feature needs to come back and it seems I'm not the only one. Personally, I don't care if the query takes a really long time to run or if no information beyond the object type is displayed for each object. We just need a simple way to find all the objects that have a given tag, without having to look through every single object type. If each object in the result set is a link to the view of that object then that's really all we need, I think. There may be other issues I'm not considering but it seems like a desirable feature of any tagging system. Anyway, I understand your reasoning for taking this away and I won't belabor the point further. You're doing great work and Netbox is amazing. I am just really sad to see this missing from 2.9. I used it a lot in 2.8. Thanks again for all your hard work.

**Comment by robbagithub** [comment]
I opened a feature request with a few ideas in there today #5121    https:/
<https://github.com/netbox-community/netbox/issues/5121>
/github.com/netbox-community/netbox/issues/5121
<https://github.com/netbox-community/netbox/issues/5121>
