### ISSUE TITLE
In Rack view "add device" link does not appear when you hover over the rear position

### ISSUE THREAD

**Issue by robbagithub** [netbox-community/netbox#5063]
### Environment
* Python version:  3.6.8
* NetBox version: 2.9.1

### Steps to Reproduce
1. Add a non-full-depth device to front of rack in  dcim/racks view
2. Open rack elevation view or continue viewing rack in dcim/racks view 
3. The "add device" link does not appear when you hover over the rear position

### Expected Behavior
Expected to see 'add device' link and able to add a device in same RU in rear. We were able to perform this in 2.7.11 which we upgraded from earlier this week. 

### Observed Behavior
The 'add device' link did not appear when hovering over the RU in the rear view of the rack

I am still able to add a device if I add the device from the devices view, dcim/devices/add.

**Comment by DanSheps** [comment]
Discussion here: https://groups.google.com/g/netbox-discuss/c/Ab3-2s7V6zs
