### ISSUE TITLE
When physical interfaces belong to a LAG, they should inherit access/trunk detail from the parent lag 

### ISSUE THREAD

**Issue by anubisg1** [netbox-community/netbox#5064]
### Environment

netbox version 2.8.8 (according to bottom of the page) , python version i have no clue i am an application user not a devops, i do not deploy the app on the server

### Proposed Functionality

When physical interfaces belong to a LAG, they should inherit access/trunk detail from the parent lag 

right now i can say that parent lag in access and interfaces belonging to that lag are in trunk. 

this isn't correct. when an interface is in a lag, details like access/trunk and allowed vlan should only be configurable in the parent lag, and children interfaces should only inherit

### Use Case

Any user working with devices. having consistency between devices and documentation without having to verbosely configure every single slave interface, which among the other things is error prone

### Database Changes

No clue really

### External Dependencies

Likely none, i am not a developer, so i don't really know

**Comment by jeremystretch** [comment]
This issue is pending closure as it does not conform to one of the [provided templates](https://github.com/netbox-community/netbox/issues/new/choose) as required by the [contributing guide](https://github.com/netbox-community/netbox/blob/master/CONTRIBUTING.md). If you'd like to request that your issue be re-opened, please first update the content so that it matches the appropriate template (this may require rewriting your issue entirely).

**Comment by anubisg1** [comment]
why is it pending closure? the template was provided with all information.. what else is it missing?

**Comment by jeremystretch** [comment]
It was marked as pending closure because you originally posted only the following:

> When physical interfaces belong to a LAG, they should inherit access/trunk detail from the parent lag
> right now i can say that parent lag in access and interfaces belonging to that lag are in trunk.
this isn't correct. when an interface is in a lag, details like access/trunk and allowed vlan should only be configurable in the parent lag, and children interfaces should only inherit

**Comment by anubisg1** [comment]
Yes, that's the first time... But the i changed it as requested, the bot cleared it up but was placed back as pending closure... Regardless, doesn't matter really, let's stay on topic.

I hope the feedback is clear

**Comment by jeremystretch** [comment]
The proposed behavior relies upon dangerous assumptions concerning the user's intended design, and would introduce a development burden that far outweighs the provided value. Thank you for the suggestion, but I'm going to pass on this.

**Comment by anubisg1** [comment]
Thanks for the response.

Can i ask what "assumption" is that we are making? when a creating a LAG, the slave interfaces cannot have different configurations else they won't belong to a LAG...

this is nothing to do with "intended design", this is how the technology works. is like that we don't want to considered tagged/untagged vlans on a dot1q trunk
