### ISSUE TITLE
sort interfaces so that physical interfaces are listed 1st and virtual/logical interfaces are listed last

### ISSUE THREAD

**Issue by anubisg1** [netbox-community/netbox#5065]
### Environment

netbox version 2.8.8 (according to bottom of the page) , python version i have no clue i am an application user not a devops, i do not deploy the app on the server

### Proposed Functionality

When opening a device, all physical interfaces should be listed first, then all virtual interfaces (like SVIs, loopbacks, LAGs) should be listed.
Right now we sort (i believe alphabetically) without any regards between physical and virtual interfaces

### Use Case

Any user interested in working with a physical device. Having physical interfaces first not only makes it for a more clean user experience but also aligns with the way devices display user information

### Database Changes

Likely none, i am not a developer, so i don't really know

### External Dependencies

Likely none, i am not a developer, so i don't really know

**Comment by jeremystretch** [comment]
This issue is pending closure as it does not conform to one of the [provided templates](https://github.com/netbox-community/netbox/issues/new/choose) as required by the [contributing guide](https://github.com/netbox-community/netbox/blob/master/CONTRIBUTING.md). If you'd like to request that your issue be re-opened, please first update the content so that it matches the appropriate template (this may require rewriting your issue entirely).

**Comment by anubisg1** [comment]
not sure how a couple of "bold" lines make any difference, but updated

**Comment by DanSheps** [comment]
Still doesn't conform, we don't know what version you are using or anything similar.  Please make sure you follow the template.

**Comment by anubisg1** [comment]
version 2.8.8 (according to bottom of the page) , python version i have no clue i am an application user not a devops, i do not deploy the app on the server

**Comment by jeremystretch** [comment]
The logic used for ordering interfaces is rather complex, and extends beyond alphanumeric sorting. The current implementation is the end result of _lots_ of community discussion, so we're not going to make any changes that would upset the consensus.
