### ISSUE TITLE
Upgrade Netbox v2.8.0 to v2.9.2 failed

### ISSUE THREAD

**Issue by thoms27** [netbox-community/netbox#5067]
### Environment
* Python version: 3.6.8
* NetBox version: 2.9.2

Hello, I'm trying to upgrade Netbox v2.8.0 to v2.9.2 but it do not works
The upgrade appends good, but I can not login to the portal :

![image](https://user-images.githubusercontent.com/20238377/91557888-8e68e900-e935-11ea-9a57-f2ef97590e7b.png)

It's works if I disable the caching : CACHE_TIMEOUT = 0

My Redis configuration is basic : 
REDIS = {
    'tasks': {
        'HOST': 'localhost',
        'PORT': 6379,
        'PASSWORD': '',
        'DATABASE': 0,
        'DEFAULT_TIMEOUT': 300,
        'SSL': False,
    },
    'caching': {
        'HOST': 'localhost',
        'PORT': 6379,
        'PASSWORD': '',
        'DATABASE': 1,
        'DEFAULT_TIMEOUT': 300,
        'SSL': False,
    }
}

Could you help me ?

Regards,

Thomas V.

**Comment by marvi** [comment]
I had to upgrade redis to >= 4 when upgrading Netbox.

**Comment by thoms27** [comment]
> 
> 
> I had to upgrade redis to >= 4 when upgrading Netbox.

Thank you for your quick feed back. After upgrading redis to 6.x, it's works fine :-)
