### ISSUE TITLE
Constraints Objectpermission do not work properly 

### ISSUE THREAD

**Issue by thoms27** [netbox-community/netbox#5069]
### Environment
* Python version: 
* NetBox version: v2.9.2

For example I would like to create a group to allow to the members to see only the public IP in applying a constraint filter to the rir object : 
![image](https://user-images.githubusercontent.com/20238377/91576874-34bdea00-e948-11ea-9e8d-6395e2ebcf5f.png)

![image](https://user-images.githubusercontent.com/20238377/91576593-0c35f000-e948-11ea-92b0-b935517d319e.png)

But only number values are allowed : 
![image](https://user-images.githubusercontent.com/20238377/91574089-5c608280-e947-11ea-965e-c1c59a7cc22b.png)

Could you explain me what is wrong ?

Regards

**Comment by jeremystretch** [comment]
Thank you for your interest in NetBox. GitHub issues are intended for reporting reproducible bugs and requesting features, and must be submitted using one of the templates provided [here](https://github.com/netbox-community/netbox/issues/new/choose). For general discussion, questions, or assistance with installation issues, please post to our [mailing list](https://groups.google.com/forum/#!forum/netbox-discuss) instead.
