### ISSUE TITLE
rack front view using (possibly) hardcoded absolute paths

### ISSUE THREAD

**Issue by anubisg1** [netbox-community/netbox#5073]
### Environment
* Python version:  unknown
* NetBox version:  2.8.8

### Steps to Reproduce
Go to a rack view and you'll notice a difference between front and back view.
The back view works correctly while the front view seems to have hard coded links (i'm assuming absolute paths).

In our deployment netbox is installed on an internal server running docker and the "real" installation URL is hidden to users via a load balancer/proxy

this causes the front view to not show images and have all links basically broken

![image](https://user-images.githubusercontent.com/4518931/91689807-1da81380-eb65-11ea-9af2-418fb4e19a7c.png)

doing an inspect of the page, i can see the front view using an absolute path to the internal hidden url, while the rear view is using relative paths (reachable)

### Expected Behavior

front view to behave like rear view 

### Observed Behavior

because of wrongly defined URL, the front view is broken. rear view works correctly

**Comment by jeremystretch** [comment]
Thank you for submitting this issue, however it appears that this topic has already been raised. Please see issue #5058 for further discussion.
