### ISSUE TITLE
Not all interfaces are displayed in virtual chassis

### ISSUE THREAD

**Issue by zelfix** [netbox-community/netbox#5074]
### Environment
* Python version: 3.6.8
* NetBox version:  2.9.2

### Steps to Reproduce
1. Create device TEST_1
2. Create physical interfaces 1/[1-10] on the device TEST_1
3. Create device TEST_2
4. Create physical interfaces 2/[1-10] on the device TEST_2
5. Create Virtual Chassis TEST_VC, include TEST_1 and TEST_2 as members. Make TEST_1 a master of this virtual_chassis.
6. Open device TEST_1

### Expected Behavior
I expected to see all interfaces from both devices, TEST_1 and TEST_2

### Observed Behavior
There are only TEST_1 interfaces.

**Comment by jeremystretch** [comment]
This is expected behavior. Only a device designated as the master for its virtual chassis will display all member interfaces. Non-master members display only their own interfaces. This behavior has not changed since the introduction of virtual chassis in NetBox.

**Comment by zelfix** [comment]
@jeremystretch I opened a master device. This works great on v2.8.9, but on v2.9.2 it doesn't.

**Comment by jeremystretch** [comment]
Sorry, missed that bit.
