### ISSUE TITLE
Support for Bridge type interfaces

### ISSUE THREAD

**Issue by ChrisPortman** [netbox-community/netbox#5079]
### Environment
* Python version: 3.*
* NetBox version:  2.9

### Proposed Functionality

Add a new interface type "Bridge" to devices and virtual machines.
A bridge interface would be distinct from other types in that they can have member interfaces of any type including standard physical, virtual and LAGs. 

A previous FR for a bridge form factor was rejected citing the use of virtual interfaces to represent bridges.
However, virtual interfaces do not have "member interfaces".  This is an important distinction as on many many
setups, IP addresses are configured on the bridge interface, not the member interface, and thus the link from IP address though
to physical is lost.

I had tried to represent a Bridge using a LAG with a naming convention.  However you can not add virtual interfaces (e.g. eth0.100) to a LAG.

### Use Case

Given an example of a virualization host where external interfaces are added to a bridge that connects virtual machines.

```
device:
    br100 (bridge, has IP address):  
        - bond0.100
    br200 (bridge, has IP address):  
        - bond0.200
    br300 (bridge, has IP address):
        - eth3
        - eth4

    bond0.100 (virtual)
    bond0.200 (virtual)

    bond0 {LAG):
        - eth0
        - eth1
  ```
You could, in a pinch, use sensible naming patterns to make the relationships obvious to a human, however, it would very difficult and hacky to try to programmatically consume the information via the API and recreate the intended setup.

**Comment by jeremystretch** [comment]
Thank you for submitting this issue, however it appears that this topic has already been raised. Please see issue #2242 for further discussion.

**Comment by ChrisPortman** [comment]
Hi, yes, I did make reference to the previous request (sorry should have quoted the issue #).  This request includes a clear scenario that can not accurately be represented using virtual interfaces.
