### ISSUE TITLE
AttributeError when creating VM

### ISSUE THREAD

**Issue by syreel** [netbox-community/netbox#5081]
### Environment
* Python version: 3.8.2
* NetBox version: 2.9.2

### Steps to Reproduce
1. Setup fresh install of Netbox
2. Add a custom field, name, description and options are unimportant, but the field type must be "selection"
3. Add a webhook, name, description, and URL are unimportant, but it must be assigned to virtual machines, enabled, and set to trigger on create.
4. Add a cluster type, names etc unimportant
5. Create a VM (names/data unimportant)

### Expected Behavior
VM is created

### Observed Behavior
Error is thrown:
```
Got AttributeError when attempting to get a value for field `value` on serializer `CustomFieldChoiceSerializer`.
The serializer field might be named incorrectly and not match any attribute or key on the `str` instance.
Original exception text was: 'str' object has no attribute 'pk'.
```

Disabling the webhook is a temporary workaround for this issue to create vms.

**Comment by skredder** [comment]
Running 2.9.3 and can confirm that I still see this error, disabling webhooks to workaround the issue

**Comment by syreel** [comment]
We upgraded to v2.9.3 last night and it seems that creating a VM works with the webhook enabled but editing a VM still causes the same error.

**Comment by jeremystretch** [comment]
@syreel you likely need to restart the RQ worker process. Testing prior to release confirmed that this bug has been fixed, so if you continue to experience issues after upgrading and restarting the RQ worker, please open a new bug listing the exact steps that someone else can take to replicate the observed issue.

**Comment by WilliamMarti** [comment]
I still seem to be having as well, opened #5109
