### ISSUE TITLE
Add a "readme" field supporting markdown in custom scripts

### ISSUE THREAD

**Issue by Tavoons** [netbox-community/netbox#5082]
### Environment
* Python version:  3.7.9
* NetBox version:  2.9.2

### Proposed Functionality

Add Markdown support to describe scripts.
It will allows devs to display more details on their scripts.

Description can stay a short description field and you can add a "readme" field supporting markdown in Meta

### Use Case

I'm working with big scripts doing a lot of things.
I would like to display a description of what the script does directly in the Custom Script page
![image](https://user-images.githubusercontent.com/39608697/91850709-43651380-ec5e-11ea-9bdf-c77bdadc54ff.png)

### Database Changes

No changes for database

### External Dependencies

There is already markdown support (for log_success, log_warning, etc) so it wouldn't add others dependencies

**Comment by jeremystretch** [comment]
This issue conflates two different proposals:

> Add markdown support for description field

> add a "readme" field supporting markdown in Meta

Please update your title and/or post above to clarify which is being proposed.

**Comment by Tavoons** [comment]
Hi Jeremy,
As you said, i'm not really clear ! 
I don't want to disturb other people's scripts. So adding a new field is better :)
But if you think that adding markdown support in description is better, it's ok for me.

**Comment by barnebyte** [comment]
Hey @Tavoons , not sure if it's suitable for you, but i encountered the same requirement for one of my huge script and i've made a "workaround" for it by putting the long version of the description to the description of a new BooleanVar at the top of the page, with some "I have read and understand of what this script is doing" label. The description of BooleanVar supports markdown language. I know it's not the same as you were looking for, but for me it was suitable enough, thought i would share.

**Comment by Tavoons** [comment]
@barnebyte  
Interesting, I'll try that now. It's even better to have a boolean to check :) Thanks for sharing :)
