### ISSUE TITLE
None full width devices consume entire rack depth.

### ISSUE THREAD

**Issue by geordish** [netbox-community/netbox#5084]
### Environment
* Python version: Python 3.6.9
* NetBox version: v2.9.2

### Steps to Reproduce
1. Create device type that is not full depth
2. Create instance of that device in a rack
3. You are unable to create a device on the other side of the rack

### Expected Behavior
Where there is a device that is not full width, another device can be added to the rear of the rack at the same U location.

This worked as expected in 2.8.9, but the bug appears to have been introduced in at least 2.9.1 and 2.9.2.

### Observed Behavior
![image](https://user-images.githubusercontent.com/1226821/91853905-cdab7880-ec5a-11ea-908f-66a92754bc4d.png)

![image](https://user-images.githubusercontent.com/1226821/91853845-b53b5e00-ec5a-11ea-92ae-9592691ec6a5.png)

**Comment by jeremystretch** [comment]
Thank you for submitting this issue, however it appears that this topic has already been raised. Please see issue #5063 for further discussion.
