### ISSUE TITLE
Support bulk relabelling of ports in the same manner as bulk renaming

### ISSUE THREAD

**Issue by cpmills1975** [netbox-community/netbox#5088]
### Environment
* Python version:  3.7
* NetBox version:  2.9.2

### Proposed Functionality
It would be helpful if it was possible to bulk re-label ports in a similar fashion to how they can currently be bulk re-named.

### Use Case
Since ports can be bulk created, named and labelled, a typo introduced in the name field while bulk creating them can be resolved fairly quickly through bulk re-naming. A typo in the label field would require each field to be edited individually.

### Database Changes
None

### External Dependencies
None

**Comment by lampwins** [comment]
I suppose we could extend the same logic and expose it through the name re-naming form, so you do both at the same time.

**Comment by cpmills1975** [comment]
Please keep this open, I’d still like to see this functionality in a future version and it seems there is some support for the idea?

**Comment by jeremystretch** [comment]
@cpmills1975 would you like to volunteer to implement it?
