### ISSUE TITLE
Editing ports should return to the device page

### ISSUE THREAD

**Issue by cpmills1975** [netbox-community/netbox#5089]
### Environment
* Python version:  3.7
* NetBox version:  2.9.2

### Proposed Functionality
When creating a new port on a device, clicking the create button returns the browser to the device page. If the port is edited, clicking the Update button takes the browser to the detail page for that port rather than back to the device page. IMHO this doesn't 'feel' right and is probably a bug, but since it's not service affecting, I've raised it as an FR instead.

As an extension to this functionality, it would be nice to return the device page to displaying the table of port types being created/edited, i.e. when returning from adding/editing a console port, the device page should return to displaying console ports not interfaces as it does currently, however I have tried suffixing the URL with the href of the table tab and it doesn't do anything so perhaps this isn't possible or there is some other magic going on when the tab is clicked?

### Use Case
While viewing a device, navigating to the edit page for a port is a single click, but after completing the update (and pressing the update button), returning to whence we came requires an additional click in the 'breadcrumbs' and doesn't feel right.

### Database Changes
None

### External Dependencies
None.

**Comment by jeremystretch** [comment]
> As an extension to this functionality, it would be nice to return the device page to displaying the table of port types being created/edited

To my knowledge, [Bootstrap 3.4](https://getbootstrap.com/docs/3.4/javascript/#tabs) unfortunately doesn't support this. Something to consider for the future, though.
