### ISSUE TITLE
api refrence

### ISSUE THREAD

**Issue by sorushsaghari** [netbox-community/netbox#5092]
### Change Type
[ X ] Addition
[ ] Correction
[ ] Deprecation
[ ] Cleanup (formatting, typos, etc.)

### Area
[ ] Installation instructions
[ ] Configuration parameters
[ X ] Functionality/features
[ ] REST API
[ X ] Administration/development
[ ] Other

### Proposed Changes
there is no detail about built in models or views. for example if I need t extend a view I even don't know how to import it or how what attributes or function does it have this is same about any part in development like extending models or having forgin key to them and ....

**Comment by jeremystretch** [comment]
NetBox internals do not comprise an API and are not intended to be extended, hence the absence of documentation. NetBox is an application, not a framework. The only extensible components (e.g. plugins, custom scripts) are documented.
