### ISSUE TITLE
Tags with empty slugs.

### ISSUE THREAD

**Issue by ebusto** [netbox-community/netbox#5098]
# Environment
* Python version: 3.7.6
* NetBox version: 2.8.9

### Steps to Reproduce
1. Tag an object with a tag named `=`
2. Attempt to view all tags (`/extras/tags/`)

### Expected Behavior
A nice table listing all tags.

### Observed Behavior
`Reverse for 'tag' with arguments '('',)' not found. 1 pattern(s) tried: ['extras/tags/(?P<slug>[^/]+)/$']`

This appears similar to #4028, but in this case the slug is empty rather than non-ASCII.

**Comment by jeremystretch** [comment]
v2.8.9 is no longer under development. Under v2.9.0 and later, tags must now be created manually, which works around this issue entirely. Please upgrade to the latest stable release (currently v2.9.2). As a workaround, you can edit the tag to create a slug.
