### ISSUE TITLE
Extend Virtual Interface functionality to better support SRIOV Virtual Functions

### ISSUE THREAD

**Issue by GR360RY** [netbox-community/netbox#5102]
### Environment
* Python version:  3.8.5
* NetBox version:  2.8.6

### Proposed Functionality

Add ability to specify "Parent Interface" for "Virtual" Interface Type. Allow "Virtual" Interface type to be part of the LAG interface. Use similar UI as for setting "Parent Lag".

See mockup below:

<img width="863" alt="Screen Shot 2020-09-06 at 8 42 49" src="https://user-images.githubusercontent.com/828309/92319718-f4372e00-f023-11ea-8f19-935e32c9fe15.png">
<img width="1613" alt="Screen Shot 2020-09-06 at 8 24 30" src="https://user-images.githubusercontent.com/828309/92319732-087b2b00-f024-11ea-9d86-97facca709c8.png">

### Use Case

In my case SRIOV Virtual Functions are used for Network Adapters (10, 50 and 100Gbit/s) to simplify management, partition traffic and allow granular bandwidth control. For all intends and purposes the virtual function interface behaves similarly to a regular interface that is connected to the switch (with its own MAC, IP and VLAN), but it shares the “same link” as a parent interface (physical function). 

Being able to assign an optional "Parent Interface" to the "Virtual" one will greatly simplify the process of debugging network issues, as I will be able find the exact parent interface the virtual interface "resides on".  Together with that, I use virtual functions as part of the bond interface and the current virtual interface model prevents the virtual interface to be part of the LAG.

As a bonus feature this will also allow to model shared BMC/IMPI interfaces closer to the real world scenario without converting Interface Mac Address field to list as proposed in #4867. 
 

### Database Changes

TBD

### External Dependencies

None

**Comment by candlerb** [comment]
Relates to #1519 (associating a virtual interface to a parent physical interface)

**Comment by jeremystretch** [comment]
Seems like this would be addressed by #1519, so I'm going to close this out. Please feel free to add any additional comments/concerns under that issue.
