### ISSUE TITLE
LDAP logging issue

### ISSUE THREAD

**Issue by chnjackso** [netbox-community/netbox#5103]
### Environment
* Python version: 3.8
* NetBox version: 2.9.2
* django-auth-ldap 2.2.0

### Steps to Reproduce
1. Login with LDAP user auth
2. 
3. 

### Expected Behavior
Success login

### Observed Behavior
502 Bad Gateway

It randomly decides to spew millions of lines into syslog saying the same person is logging in.. gets stuck in some sort of loop

# du -h daemon.log
1.7G	daemon.log
# grep pat daemon.log|wc -l
4404251

Log lines like this
Sep  7 10:51:14 netbox1 gunicorn[515892]: search_s('ou=people,dc=xxxxxxxx,dc=net,dc=au', 2, '(uid=%(user)s)') returned 1 objects: uid=patxxx,ou=people,dc=xxxxxxx,dc=net,dc=au

**Comment by jeremystretch** [comment]
Thank you for your interest in NetBox. GitHub issues are intended for reporting reproducible bugs and requesting features, and must be submitted using one of the templates provided [here](https://github.com/netbox-community/netbox/issues/new/choose). For general discussion, questions, or assistance with installation issues, please post to our [mailing list](https://groups.google.com/forum/#!forum/netbox-discuss) instead.
