### ISSUE TITLE
REDIS Configuration Webhooks to Tasks

### ISSUE THREAD

**Issue by agrrajag** [netbox-community/netbox#5107]
### Change Type
[x] Addition
[ ] Correction
[ ] Deprecation
[ ] Cleanup (formatting, typos, etc.)

### Area
[ ] Installation instructions
[x] Configuration parameters
[ ] Functionality/features
[ ] REST API
[ ] Administration/development
[ ] Other

### Proposed Changes

If upgrading from an older version, you may come across this error:

"REDIS section in configuration.py is missing the 'tasks' subsection."
django.core.exceptions.ImproperlyConfigured: REDIS section in configuration.py is missing the 'tasks' subsection.
root@ipam:/opt/netbox# ls

To resolve:

1. Nano into the configuration file

`sudo nano /opt/netbox/netbox/netbox/configuration.py`

2. Under REDIS, change "webhooks" to "tasks" and save

3. Run ./upgrade.sh again and it should work successfully.

**Comment by jeremystretch** [comment]
The new configuration format has already been updated in the configuration documentation, but I'll add a note to the release notes. There's no need to duplicate the documentation.
