### ISSUE TITLE
extras.scripts.ObjectVar query_params supports lists as value but not tuples

### ISSUE THREAD

**Issue by cloos** [netbox-community/netbox#5111]
### Environment
* Python version: 3.6.9
* NetBox version: 2.9.3

### Steps to Reproduce
1. create a custom script with an ObjectVar

### Expected Behavior
Sets as query_params value works:
```python
device = ObjectVar(
        model=Device,
        query_params=dict(
            role=("blade", "rack-mount-chassis"),
        ),
    )
```

### Observed Behavior
Only lists as query_params value works:
```python
device = ObjectVar(
        model=Device,
        query_params=dict(
            role=["blade", "rack-mount-chassis"],
        ),
    )
```
The necessary change is at line 144 in:
https://github.com/netbox-community/netbox/blob/b4299241fea39b5cd78dffffc3bfd61db54e8430/netbox/utilities/forms/widgets.py#L134-L149

**Comment by jeremystretch** [comment]
```
role=("blade", "rack-mount-chassis")
```

Not to nitpick, but this is a tuple, not a set.
