### ISSUE TITLE
Links not consistent on rack elevation

### ISSUE THREAD

**Issue by alanNutanix** [netbox-community/netbox#5114]
### Environment
* Python version: 3.7.9
* NetBox version: 2.9.3

### Steps to Reproduce
1.  Go to any rack view
2. Look at empty spots vs. populated spots

### Expected Behavior
Expected ALL links to be relative.  Those that are populated are not, those that are empty are.

### Observed Behavior
Links that are populated pick up the WRONG behavior from the bug in django.
(Yes, this is related to #4953 which I believe should NOT be closed but this gives additional information to make it easier to close)

**Comment by jeremystretch** [comment]
> Expected ALL links to be relative.

Per #4147 in v2.7.12, rack SVG links should be absolute URLs to facilitate the use of SVG images outside of the NetBox UI. Why would you expect them to be relative?

**Comment by alanNutanix** [comment]
So that they worked the same as the rest of the links on the page when behind multiple proxies.

However, I discovered the problem with how to get multiple proxies to work.
The nginx.conf file I added the following to:
``` 
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $http_host;
```

I am closing this issue, although I'll open a new one to put those in the sample nginx.conf
