### ISSUE TITLE
Change to sample nginx.conf

### ISSUE THREAD

**Issue by alanNutanix** [netbox-community/netbox#5115]
### Environment
* Python version:  3.7.9
* NetBox version:  2.9.3

### Proposed Functionality
Change only to sample nginx.conf
Add these two lines into the location portion:
``` 
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $http_host;
```

### Use Case
If someone is using netbox with a double proxy, this is what is needed on the outer one.
(My use case: Using netbox in the docker container, with nginx on the vm to handle SSL certs)
 

### Database Changes
None

### External Dependencies
None

**Comment by kobayashi** [comment]
Thank you for submitting your idea. Unfortunately, the proposed feature falls outside the scope of functionality that NetBox aims to provide. As NetBox is an open source application with limited development resources and a persistent backlog of existing work, it is crucial that we limit the scope of development to ensure it remains a maintainable project for many years to come. HTTP configuration especially depends on each user and we would like to provide just simple case of configuration to avoid issues in nginx or apache themselves. Thank you for your understanding.
