### ISSUE TITLE
Add custom fields to tags

### ISSUE THREAD

**Issue by fabi125** [netbox-community/netbox#5116]
### Environment
* Python version:  3.6.5
* NetBox version:  2.9.3

### Proposed Functionality
Tags got a nice upgrade in 2.9 and we would like to store some additional information with tags. It would therefore be great if we could extend tags with custom fields.

### Use Case
Tags usually have a specific meaning when attached to an object. With custom fields this would allow users to attach additional information (e.g. required packages or some additional metadata) with tags.

### Database Changes
None.

### External Dependencies
None.

**Comment by jeremystretch** [comment]
Sorry but there's no way this is happening. It completely disagrees with the intended use for both tags and custom fields in NetBox.
