### ISSUE TITLE
Show /32 allocations in child prefixes list

### ISSUE THREAD

**Issue by amuckart** [netbox-community/netbox#5120]
### Environment
* Python version: 3.6.9
* NetBox version: 2.9.3

### Steps to Reproduce
1. Create a /24 IPv4 prefix
2. Create a pair of /29s with a /29 worth of space between them, e.g. .0/29 and .16/29
3. Create a couple /32 IP addresses from the intervening /29, e.g. .11 and .13
3. Go to the "Child Prefixes" tab of the /24. The .8/29 prefix is shown as available.
4. Create the .8/29 prefix, it will show as partially used.

### Expected Behavior
The /32 allocations should show up in the Child Prefixes list and should break up blocks of free space, creating /32 or /31s etc. as needed.

I realise that /32 isn't technically a "child prefix" but when allocating loopback addresses they do get assigned directly from the containing /24 and it isn't possible (and doesn't make sense) to create a /32 "prefix" to hold the single IP address.

### Observed Behavior
When viewing the "Child Prefixes" tab blocks of space that have /32 IP addresses assigned from inside them show as available and the existence of the /32s doesn't become obvious until you've either created the containing prefix or you check through both the "Child Prefixes" list and the "IP Addresses" list. 

For any prefix length than /32, it's entirely sane to require the containing prefix exist and IPs are allocated out of that but individual IPs are a special case.

**Comment by jeremystretch** [comment]
This is expected behavior. Before allocating the /32s, you should create a /29 container prefix for them. This ensures that the space is allocated for the purpose of provisioning loopback IPs.
