### ISSUE TITLE
Add filter of Object type to Tag view

### ISSUE THREAD

**Issue by robbagithub** [netbox-community/netbox#5121]
### Environment
* Python version: 3.6.9  
* NetBox version:  2.9.2 

### Proposed Functionality
When search for specific objects with tag values it would be very helpful to have one of the below options. 

1. Addition of object type filter in tags view as in the below screen shot
![image](https://user-images.githubusercontent.com/22147754/92678883-4fda2200-f36a-11ea-8818-de69f3bb8d55.png)
or
2. Addition of object type 'tag' in the "All objects" drop down on the main page. 
3. A third option would be to have a column that displays the non-zero counted object types in the tags view, so you would at least know the object types that have this tag.

### Use Case
Unless you know exactly which object type has that tag assigned it is difficult to actually find those objects with that tag.
If I wish to find all objects with a tag called 'Tested-Operational' I need to search each specific object type for that 'tag' value. 

### Database Changes
None required

### External Dependencies
None Required

**Comment by jeremystretch** [comment]
This requires the introduction of a new filter for tags in addition to the UI work.

@robbagithub would you like to volunteer for this this work?

**Comment by robbagithub** [comment]
@jeremystretch Happy to do the leg work in designing the UI and how the logic might work. Not sure I've the skills to get into the code. I'll have a stab at the design and go from there.

**Comment by jeremystretch** [comment]
@robbagithub have you been able to make any progress with this?

**Comment by robbagithub** [comment]
I’ve failed to unfortunately. Not forgotten though.
