### ISSUE TITLE
NetBox 2.9 custom scripts missing Script Data form after execution

### ISSUE THREAD

**Issue by cloos** [netbox-community/netbox#5124]
### Environment
* Python version: 3.6.9
* NetBox version: 2.9.3

### Steps to Reproduce
1. create a custom script
2. run the custom script
3. the **Script Data** form is now missing

### Expected Behavior
Show the **Script Data** form after script execution.

### Observed Behavior
The **Script Data** form isn't shown after script execution.

In NetBox before 2.9, after running a custom script, the **Script Data** form was shown under the **Script Log**, with the previously entered data.
This was especially helpful if you run the script with **Commit changes** disabled, to validate the changes the script would do, and then run the script with the same data and **Commit changes** enabled.

**Comment by jeremystretch** [comment]
Beginning with v2.9, custom scripts are now executed via a background task (see #2006). The redirection in place prevents the original form data from being displayed on the results page. However, you can easily use the browser's back button to return to the original submission view.

**Comment by lampwins** [comment]
We could add a simple button that checks to see what the current referrer is and call `back()`. Soemthing like this works:

```javascript
function runScript(){
    // Check if the user came from the run script form
    if (document.referrer.includes("/extras/scripts/{{ result.name }}/")) {
        window.history.back();
    } else {
        window.location.href = "/extras/scripts/{{ result.name }}/";
    }
}
```

**Comment by cloos** [comment]
As I'm totally fine with using the browser's back button, I'm closing this.
