### ISSUE TITLE
New LDAP Group Permissions failed

### ISSUE THREAD

**Issue by thoms27** [netbox-community/netbox#5125]
### Environment
* Python version: 3.8.2
* NetBox version: 2.9.2

### Steps to Reproduce
1. Create a group on your AD (ex: g_netbox) and a user (ex: netbox)
2. Under Netbox Administration, create a new group (g_netbox)
3. Under Netbox Administration, add a permission to this group (ex: dcim.view_site):
![image](https://user-images.githubusercontent.com/20238377/92722622-27512880-f368-11ea-9469-f7f5c3396bcf.png)

4. Try to logging as user 'netbox' 

### Expected Behavior

Logging established and only view Site is possible

### Observed Behavior

Logging is OK, View Site is not allowed
![image](https://user-images.githubusercontent.com/20238377/92722462-f2dd6c80-f367-11ea-95f2-5f9cd10f4da2.png)

I have an old group (before the last upgrade (v2.8.0) and it's works.
To complete, if I manually attach the new user to the group in Netbox Administration, it's works :
![image](https://user-images.githubusercontent.com/20238377/92723257-1fde4f00-f369-11ea-9bc5-b86872dea6ed.png)

and

![image](https://user-images.githubusercontent.com/20238377/92723294-2b317a80-f369-11ea-9320-5c7699804030.png)

With my old group, it's not necessary to manually attach user to the group.

Regards

**Comment by abenedict** [comment]
I am seeing the exact same issue.

**Comment by crazyman143** [comment]
Same issue on 2.9.4

**Comment by michaelpair95** [comment]
Running into a similar issue in 2.9.9 as well

**Comment by tyler-8** [comment]
I'm running v2.9.10 and have been tinkering with this as I was initially seeing some confusing behavior.

For the most part, everything seems to be working fine with the LDAP group permissions mapping - with the exception of scripts and reports. I can't seem to get a user with View/Add/Change/Delete rights on "scripts" and "reports to be able to access or run either. Both options are greyed out in the menu.

![image](https://user-images.githubusercontent.com/17618971/100163006-c1fad700-2e82-11eb-8cba-f74afba2008d.png)
![image](https://user-images.githubusercontent.com/17618971/100163025-ccb56c00-2e82-11eb-9f96-c3e442769f6f.png)

**Comment by thoms27** [comment]
Any news ?

**Comment by tyler-8** [comment]
Try enabling group mirroring and see if that provides a workable solution. I've tried to summarize a longer thread here: https://github.com/netbox-community/netbox/issues/5442#issuecomment-770997825
