### ISSUE TITLE
Expand the number of Rear Port template positions 

### ISSUE THREAD

**Issue by proudbro** [netbox-community/netbox#5128]
### Environment
* Python version:  3.6.9
* NetBox version:  2.8.9

### Proposed Functionality
Hello
Is it possible to increase the number of positions for rear port template to 288 or more? The limit is now set to 64 which is also written in the [documentation](https://netbox.readthedocs.io/en/stable/core-functionality/device-types/#rear-port-templates)

### Use Case
We create a lot of optical fiber panels with many front ports (more then 64) which are aggregated into one bulk cable. To correctly display such device in Netbox I link a bunch of front ports with one rear port which seems to correspond to reality (at this point i don't care about individual fibers). Further, as a rule, this fiber panel connects to a same device with cable object. With a limit of 64 positions it forces to create more than one Rear Port and more than one Cable but in reality it is not so.

### Database Changes
Have to be

### External Dependencies
None

**Comment by DanSheps** [comment]
I don't see a problem with this, but it could impose some weird performance issues.  I think a deeper look into this might be required.

**Comment by jeremystretch** [comment]
1024 should probably suffice. I don't think we were considering fiber plant modeling with the original implementation of pass-through ports.
