### ISSUE TITLE
Filtering on cable connection page

### ISSUE THREAD

**Issue by top1ing** [netbox-community/netbox#5132]
### Environment
* Python version: 3.7
* NetBox version: 2.9.3

### Steps to Reproduce
1. Create Sites: "Site-1", "Site-2"
2. Create device with any device type: "Dev_1-site1" (Site-1), "Dev_2-site2" (Site-2), "Dev_3-site2" (Site-2) 
3. Create interface ports "Port-1" on created devices.
4. Go to "Dev_2-site2" and connect "Port-1" to interface.

### Expected Behavior
On Cable connection page, when choose Site-2 on "B Side", only "Dev_2-site2" and "Dev_3-site2" must be visible in device list.
And also if choose "Dev_3-site2" in device list, then only "Dev_3-site2" "Port-1" must be available in name list. 

### Observed Behavior
On Cable connection page, if choose Site-2 on "B Side", then "Dev_1-site1" also visible in device list, although "Dev_1-site1" is belong to Site-1.
Also if choose "Dev_3-site2" in device list, then all 3 ports "Port-1" available ("Dev_1-site1","Dev_2-site2","Dev_3-site2").

**Comment by jeremystretch** [comment]
Thank you for opening a bug report. I was unable to reproduce the reported behavior on NetBox v2.9.3. Please re-confirm the reported behavior on the current stable release and adjust your post above as necessary. Remember to provide detailed steps that someone else can follow using a clean installation of NetBox to reproduce the issue. Remember to include the steps taken to create any initial objects or other data.

**Comment by top1ing** [comment]
Thanks for reply!
The latest version (2.9.3) is used.
![NetBox version](https://user-images.githubusercontent.com/66525183/93461021-ce940980-f8ec-11ea-8762-8c38e7c1ac60.png)

**Detailed steps with screenshoots is below:**
**Step 1. Create a new manufacter**
![1-step_create_manufacter](https://user-images.githubusercontent.com/66525183/93461038-d5228100-f8ec-11ea-8b28-e83777a2bdf8.png)

**Step 2. Add a new device role**
![2-step_add_device-role](https://user-images.githubusercontent.com/66525183/93461039-d653ae00-f8ec-11ea-86bc-b37f407ddd17.png)

**Step 3. Create device type** 
![3-step_create_device-type](https://user-images.githubusercontent.com/66525183/93461041-d653ae00-f8ec-11ea-936d-275993cd9262.png)

**Step 4.  Add intreface to created device type**
![4-step_add_interfaces_to_device-type](https://user-images.githubusercontent.com/66525183/93461044-d6ec4480-f8ec-11ea-81da-98a45890ee3c.png)

**Steps 5-7. Create sites (Site-1, Site-2, Site-3)**
![5-step_create_Site-1](https://user-images.githubusercontent.com/66525183/93461046-d784db00-f8ec-11ea-93b4-e2a810042d84.png)
![6-step_create_Site-2](https://user-images.githubusercontent.com/66525183/93461049-d784db00-f8ec-11ea-8010-1e151afc4b4c.png)
![7-step_create_Site-3](https://user-images.githubusercontent.com/66525183/93461050-d81d7180-f8ec-11ea-96fd-66e39695ddc6.png)

**Steps 8-20. Create:**
 - 1 device in Site-1 (Dev_1-site1)
 - 2 devices in Site-2 (Dev_2-site2, Dev_3-site2)
 - 10 devices in Site-3 (site-3_device1, site-3_device2, site-3_device3, site-3_device4, site-3_device5, site-3_device6, site-3_device7, site-3_device8, site-3_device9, site-3_device10)
![8-step_create_Dev-1_site1](https://user-images.githubusercontent.com/66525183/93461051-d81d7180-f8ec-11ea-958a-a05232d196cf.png)
![9-step_create_Dev-2_site2](https://user-images.githubusercontent.com/66525183/93461052-d8b60800-f8ec-11ea-887d-f86d6a5120ed.png)
![10-step_create_Dev-3_site2](https://user-images.githubusercontent.com/66525183/93461054-d94e9e80-f8ec-11ea-97a3-0ad58ae2809f.png)
![11-20-steps_create_Site-3_device1-10](https://user-images.githubusercontent.com/66525183/93461056-d94e9e80-f8ec-11ea-95af-8ab8f8da740f.png)

**Steps 21-23: Make sure that:** 
 - Site-1 contains 1 device
 - Site-2 contains 2 devices
 - Site-3 contains 10 devices
![21-step_view_Site-1_page](https://user-images.githubusercontent.com/66525183/93461059-d9e73500-f8ec-11ea-800b-aae563dc9089.png)
![22-step_view_Site-2_page](https://user-images.githubusercontent.com/66525183/93461060-da7fcb80-f8ec-11ea-9a9b-047447e80650.png)
![23-step_view_Site-3_page](https://user-images.githubusercontent.com/66525183/93461061-da7fcb80-f8ec-11ea-8be8-172aeed8640d.png)

**Step 24:** 
**On Dev2_site-2connect interface to other interface.**
**Choose Site-2.**
In Device list all configured devices available. **Even including Site-3 devices.**
![24-step_Cable_connection_page_Dev2-to-interface](https://user-images.githubusercontent.com/66525183/93461064-db186200-f8ec-11ea-91df-c973ce2e05e9.png)

**Comment by top1ing** [comment]
After upgrading to 2.9.4, the problem no longer appears.
