### ISSUE TITLE
Removing an ip-address from an interface results in no change

### ISSUE THREAD

**Issue by heiko-ma** [netbox-community/netbox#5133]
### Environment
* Python version: v3.6.8
* NetBox version: v2.9.3

### Steps to Reproduce
1. Create a new VM, i.e. 'testvm' and assign it to a cluster
2. Create a new interface, i.e. 'Ethernet0'
3. Create a new ip-address and attach it to the previously created interface
4. Try to remove the ip-address from the interface by removing the vm from the corresponding fields in the ip-address edit dialog

### Expected Behavior
The ip-address is unlinked from the device and no relation to the vm is displayed

### Observed Behavior
I get the tooltip that the ip-address has been modified but no change is visible and the address is still linked to the interface. 

This behavior can also be observed when I try to remove the link from a existing device (not virtual machine) so i think this is a general issue.

I'd be happy to supply you with any additional information

**Comment by jeremystretch** [comment]
It seems that this has been fixed in the `develop` branch as part of the work on #5105.
