### ISSUE TITLE
Request to provide a docker-compose file to deploy Netbox.

### ISSUE THREAD

**Issue by gittur** [netbox-community/netbox#5135]
### Environment
* Python version:  
* NetBox version:  

### Proposed Functionality

- A docker-compose file to setup NetBox in one go.

### Use Case
- Makes deployment and installation very easy.

### Database Changes

- None

### External Dependencies
- docker
- docker-compose.

**Comment by candlerb** [comment]
You mean like this one? https://github.com/netbox-community/netbox-docker/blob/release/docker-compose.yml

(There's a separate "netbox-docker" repository where all the docker-related stuff lives)
