### ISSUE TITLE
IPAM - Available prefixes might list an existing prefix

### ISSUE THREAD

**Issue by mzbroch** [netbox-community/netbox#5138]
### Environment
* Python version: 3.7.9
* NetBox version: 2.9.2

### Steps to Reproduce
1. Create a container Prefix object, and an active Prefix object with the same prefix value as container's.
```
>>> Prefix.objects.create(prefix='192.0.2.0/24', status='container')
<Prefix: 192.0.2.0/24>

>>> Prefix.objects.get(prefix='192.0.2.0/24').get_available_prefixes()
IPSet(['192.0.2.0/24'])

>>> Prefix.objects.create(prefix='192.0.2.0/24', status='active')
<Prefix: 192.0.2.0/24>

>>> Prefix.objects.get(prefix='192.0.2.0/24', status='container').get_available_prefixes()
IPSet(['192.0.2.0/24'])
```

### Expected Behavior
NetBox should not list container's child prefix in `get_available_prefixes` for cases when a child is equal to the container (filter to be used contained or equal, instead of contained only)

### Observed Behavior
NetBox lists existing child prefix (which is equal to the container prefix) as a result of method `get_available_prefixes`

**Comment by jeremystretch** [comment]
This is expected behavior: the second prefix is not a child of the first. You've created two parallel prefixes with different statuses (which _is_ a valid condition). NetBox will report the set of IPs available within each independently.
