### ISSUE TITLE
Changes to interface/console/power port/etc connection template

### ISSUE THREAD

**Issue by cpmills1975** [netbox-community/netbox#5143]
### Environment
* Python version:  3.6
* NetBox version:  2.9.3

### Proposed Functionality

I'd like to propose that the "Name" label in the new connection templates (/dcim/interfaces/n/connect/*) read "Name (Label)" and the drop down list of interfaces/ports showed entries in this format (e.g "ge-1/0/23 (23)" or "eth0 (port 1)")

In a similar vein, I'd like to propose the Device field is shown as "Device (Asset Tag)" and the drop down list showed entries in this format as well (e.g. "mgmt-sw-01 (A12345)") however I appreciate that while Asset Tag is helpful to me, others may prefer a different field so this could perhaps be open to more discussion.

I am not proposing any changes to the existing functionality of these forms, just what and how information is displayed.

### Use Case

When connecting interfaces between devices, we have discovered that it is possible to search for interfaces/ports by typing the label in to the name box and devices by typing the asset tag or serial number in to the device field. This is beneficial as my users who are typically tasked with connecting devices and recording the connections in NetBox are often more used to dealing with the physical rather than the logical side of devices and therefore typically see ports as the names stamped on them and devices by the prominently displayed asset tag rather than the names given to them in config.

### Database Changes

None

### External Dependencies

None

**Comment by jeremystretch** [comment]
We do something like this in a few places by including a property called `display_name` which contains some combination of an object's name and other attributes. For example, the `display_name` of an unnamed device will be its device type and primary key. It might make sense to take a more general approach to this, and simply include a standardized field (e.g. `string` or `repr`) with _every_ object to readily convey how it should render in a dropdown list or similar invocation. This could just be the result of calling `str()` on the Python object.

**Comment by jeremystretch** [comment]
> In a similar vein, I'd like to propose the Device field is shown as "Device (Asset Tag)" and the drop down list showed entries in this format as well (e.g. "mgmt-sw-01 (A12345)")

This has been implemented for v3.1.
