### ISSUE TITLE
Cable Edit

### ISSUE THREAD

**Issue by Paktosan** [netbox-community/netbox#5144]
### Environment
* Python version:  Unknown
* NetBox version:  2.9.3

### Proposed Functionality
Ability to change connected device when editing a cable.

### Use Case
It sometimes happens that we move one end of a cable from one device to another while keeping the other side the same.
Currently one has to delete the old and set up a new cable filling out all details again.

### Database Changes
None as far as I am aware.

### External Dependencies
None as far as I am aware.

**Comment by jeremystretch** [comment]
Thank you for submitting this issue, however it appears that this topic has already been raised. Please see issue #4881 for further discussion.
