### ISSUE TITLE
Add Rack Group field to Device Location form

### ISSUE THREAD

**Issue by garretwest** [netbox-community/netbox#5149]
### Environment
* NetBox version:  2.8.8

### Proposed Functionality
When editing a device's location, you can hierarchically drill down on the following currently:

- Site

- Rack

- Rack Face

- Position

The issue arises when you have the same naming convention in different rack groups (R01, for example). When you choose a site, then go to choose a rack, multiple instances of R01 will show up, with no indication of which rack group they are part of. Example:

![image](https://user-images.githubusercontent.com/29845853/93633903-f2b71f80-f9ac-11ea-8fa3-9a82035a8980.png)

I am proposing to add a **Rack Group** field between the **Site** and **Rack** fields, which would then only list racks that are part of the chosen rack group.

### Use Case
The use case would be to filter out racks that are not part of the chosen rack group when editing a device location.

### Database Changes
The proposal requires adding a new **Rack Group** field to the Device Location form.

**Comment by ebusto** [comment]
This would be very useful for us as well, since we use rack groups for rooms in buildings.

**Comment by garretwest** [comment]
Thanks @jeremystretch !
