### ISSUE TITLE
Update FAQ to reflect changes implemented in #5146

### ISSUE THREAD

**Issue by xkilian** [netbox-community/netbox#5150]
My understanding is that issue #5146  changes the information provided in the : [Netbox FAQ custom fields](https://github.com/netbox-community/netbox/wiki/Frequently-Asked-Questions#can-we-add-custom-fields-to-more-models)
### Change Type
[ ] Addition
[ X] Correction
[ ] Deprecation
[ ] Cleanup (formatting, typos, etc.)

### Area
[ ] Installation instructions
[ ] Configuration parameters
[ ] Functionality/features
[ ] REST API
[ ] Administration/development
[X ] Other

Indicate that cables can now have custom fields and perhaps other information related to the change.

**Comment by jeremystretch** [comment]
#5146 has not yet made it into a release, so the current FAQ is accurate.
