### ISSUE TITLE
Create Common Repo of Mostly Used Devices Images 

### ISSUE THREAD

**Issue by nanisyako** [netbox-community/netbox#5152]
### Environment
* Python version:   3.6
* NetBox version:  2.9.3

### Proposed Functionality
Create a device images pool for mostly used devices across netbox users. 

### Use Case

Instead of downloading each server/network device images seperately, we can select from the drop-down available images when we are creating device types.

**Comment by jeremystretch** [comment]
First, this isn't really the appropriate forum for suggestions like this: GitHub issues should be limited to features/bugs in NetBox itself. The mailing list would be a better place.

Second, this idea has been floated before, however such images are typically not licensed for free redistribution. Rather, they are copyrighted works which only the producer (typically a vendor) has the right to distribute. This precludes the possibility of compiling a community-maintained repository.
