### ISSUE TITLE
Put the Rack location in a clickable floor plan

### ISSUE THREAD

**Issue by nanisyako** [netbox-community/netbox#5153]
### Environment
* Python version:  3.6
* NetBox version:  2.9.3

### Proposed Functionality
Upload a floor plan of the data center and mark the rack location.

### Use Case
during covid-19 most of the companies, uses remote hands. We can mark the rack location inside floor plan, that would be easy for remote hands to find the correct rack and see what is inside the rack just by clicking on it.

### Database Changes
N/A

### External Dependencies
N/A

**Comment by jeremystretch** [comment]
Thank you for submitting this issue, however it appears that this topic has already been raised. Please see issue #114 for further discussion.
