### ISSUE TITLE
Bump Dependency dango-cors-headers from 3.4.0 to 3.5.0

### ISSUE THREAD

**Issue by drewrothstein** [netbox-community/netbox#5160]
### Environment
* Python version: `all`
* NetBox version: `all`

### Steps to Reproduce
1. Not super applicable: I'd like to bump `dango-cors-headers` from `3.4.0` to `3.5.0`.

### Expected Behavior
1. Dependency is bumped to pickup language inclusivity changes ([ref](https://github.com/adamchainz/django-cors-headers/pull/562)).

### Observed Behavior
1. Reviewing the [changes](https://github.com/adamchainz/django-cors-headers/compare/3.5.0...master), nothing seems like it would be problematic.

**Comment by jeremystretch** [comment]
Barring a pressing need, dependencies are re-evaluated updated in the course of every major release. There is no need to open an issue for this.
