### ISSUE TITLE
API: Filtering ip-address by interface_id raises bad request

### ISSUE THREAD

**Issue by hensoko** [netbox-community/netbox#5162]
### Environment
* Python version: 3.7.3
* NetBox version: 2.9.3

### Steps to Reproduce
1. Create a device and add an interface on it
2. Assign ip-address to interface
3. `curl -XGET -I -H "Authorization: Token ..." https://<netbox>/api/ipam/ip-addresses/?interface_id=<id of interface>` or open in browser

### Expected Behavior
HTTP Status 200 and a list of all ip-addresses that are assigned to the given interface

### Observed Behavior
```
HTTP 400 Bad Request
Allow: GET, POST, HEAD, OPTIONS
Content-Type: application/json
Vary: Accept

{
    "interface_id": [
        "Select a valid choice. 1 is not one of the available choices."
    ]
}
```

**Comment by jeremystretch** [comment]
This is the expected behavior. An interface with ID 1 does not exist, hence the error message.

**Comment by jeremystretch** [comment]
Closing this out as it's not a valid bug report.

> I wonder how to filter for assigned_object_id and assigned_object_type, my quick tests show that theses attributes are just ignored.

Please post to the mailing list for general assistance using the REST API.

**Comment by hensoko** [comment]
Well it seems no longer possible to filter ip-addresses, assigned to vms, by interface id. At least this is a regression to Netbox 2.8.x. Filtering by assigned_object_id / assigned_object_type is not possible as these parameters are just ignored.

Should I open another issue for that or am I obviously wrong here and you can maybe point me to some kind of documentation?
