### ISSUE TITLE
Inconsistent rack count behaviour in rack groups in /dcim/sites/site_name

### ISSUE THREAD

**Issue by cpmills1975** [netbox-community/netbox#5164]
### Environment
* Python version: 3.6
* NetBox version: 2.9.3

### Steps to Reproduce
1. Create a site
2. Add a rack group to the site
3. Add a sub rack-group to the rack group created in 2
4. Add another sub rack-group to the rack group created in 3 (may not be required)
5. Add some racks to the rack group created in 4
6. View the rack groups page /dcim/rack-groups and confirm the count of racks cascades correctly from the top level rack group right down to the lowest level rack group.
7. View the site page /dcim/sites/site_name
8. See the count of racks next to each rack group in the Rack Groups panel
9. Compare this to the rack elevation shown when clicking on the "View elevations" button to the right of each row in the Rack Groups panel.

### Expected Behavior
The count of racks in each sub-group should behave in a similar manner to the dcim/rack-groups page in that it should includes both direct descendent racks and all racks from child sub-groups. The rack elevation correctly shows this.

### Observed Behavior
The count appears to be made up only of racks that are a direct descendent of the rack group and does not include the racks contained in child sub-groups yet the view elevation button does.

**Comment by kobayashi** [comment]
The rack group table in site view shows actual rack count of each rack group. IMO displaying cumulative rack-count in parent rack group will be confusing in the site view.

**Comment by jeremystretch** [comment]
> The count of racks in each sub-group should behave in a similar manner to the dcim/rack-groups

I have to agree with this: We should be consistent in conveying rack counts. It would also help to show the rack groups in a hierarchical arrangement under the site view. (This was never updated when support for nested rack groups was introduced in #1754.)
