### ISSUE TITLE
Circuit termination connected endpoint does not show up in API response

### ISSUE THREAD

**Issue by ggidofalvy-tc** [netbox-community/netbox#5165]
### Environment
* Python version: 3.7.3
* NetBox version: 2.9.3

### Steps to Reproduce
1. Create circuit
2. Create A-side termination
3. Connect A-side termination to arbitrary interface on a device
4. Create Z-side termination
5. Connect Z-side termination to arbitrary interface on a device
6. Check web interface + API result of circuit

### Expected Behavior
The web interface and the API shows the connected interfaces/devices on both A and Z sides.

### Observed Behavior
The web interface shows the connected interfaces/devices on both A and Z sides; however, the API only shows the A side as connected.

Deleting the terminations and creating the Z-side termination first, then the A-side termination leads to the A-side termination not showing any connected endpoints when queried through the API.

![NetBox UI correctly shows the connections](https://user-images.githubusercontent.com/69459847/93906788-e8728980-fcfc-11ea-934e-f0b263338e08.PNG)
![NetBox API does not!](https://user-images.githubusercontent.com/69459847/93906845-fa542c80-fcfc-11ea-96ae-f1afff52c7b0.png)

Swapping terminations leads to the API showing the A-side as having nothing connected to it.

![NetBox UI correctly shows the connections after swap](https://user-images.githubusercontent.com/69459847/93907243-60d94a80-fcfd-11ea-9a00-6e6c21350d16.PNG)
![NetBox API still doesn't, now the A-side is affected...](https://user-images.githubusercontent.com/69459847/93907258-66369500-fcfd-11ea-931f-c53cacfeed94.png)

The actual circuit terminations created are also affected by this issue.

![c5](https://user-images.githubusercontent.com/69459847/93907494-ae55b780-fcfd-11ea-835c-6a7c1d9dbfca.png)

The ['fix' for this issue](https://github.com/netbox-community/netbox/commit/1d0b27c99e166744f9732441a17f7d7fb88f7407) did not fix the problem with the model itself, it is a mere workaround, querying the attached cable (and not the connected_endpoint, which can be null).

**Comment by ggidofalvy-tc** [comment]
Seems to be a duplicate of #4851 ?

**Comment by ggidofalvy-tc** [comment]
For developers who ran into this issue: A workaround is to query the cable within the circuit termination, then fetch the termination that isn't the original circuit termination.

**Comment by ggidofalvy-tc** [comment]
Doing another reproduction pass revealed that there are some cases when both circuit terminations show their `connected_endpoint` as null, even when both are connected.

**Comment by jeremystretch** [comment]
This appears to be the same issue described in #4925.
