### ISSUE TITLE
Minimum required Redis version not documented

### ISSUE THREAD

**Issue by jameno123** [netbox-community/netbox#5169]
### Change Type
[ ] Addition
[X ] Correction
[ ] Deprecation
[ ] Cleanup (formatting, typos, etc.)

### Area
[ X] Installation instructions
[ X] Configuration parameters
[ ] Functionality/features
[ ] REST API
[ ] Administration/development
[ X] Other

### Proposed Changes

When upgrading to version 2.9.0  it looks like there is an issue that prevents netbox from working with default ubuntu 16 redis 3.0.6. Upon upgrading to redis 5.x the problem went away. It would seem that there may be a silent dependancy on a specific minimum version of redis which should be documented as a breaking change during upgrade.

**Comment by kobayashi** [comment]
Thank you for submitting this issue, however it appears that this topic has already been raised. Please see issue #5030  for further discussion. You can find it out at [redis section in netbox docs](https://netbox.readthedocs.io/en/stable/installation/2-redis/)
