### ISSUE TITLE
can't create new tags in the Tags input field

### ISSUE THREAD

**Issue by szelga** [netbox-community/netbox#5173]
### Environment
* Python version: 3.7 (official docker image is used)
* NetBox version: 2.9.4

### Steps to Reproduce
1. create a new or edit an existing device.
2. go to the `Tags` field.
3. write in a nonexisting tag.

### Expected Behavior

the new tag would be in the field, after sending out the form it would be created and added to the device.

### Observed Behavior

the `Tags` field is left unchanged.

**Comment by jeremystretch** [comment]
This is expected behavior. Support for automatic tag creation was removed in v2.9.0 (see #3703).

**Comment by szelga** [comment]
understandable. have a great day.
