### ISSUE TITLE
Users with relevant permissions cannot Run Reports or Scripts

### ISSUE THREAD

**Issue by ledgley** [netbox-community/netbox#5177]
### Environment
* Python version: Python 3.6.8
* NetBox version: NetBox 2.9.4

### Steps to Reproduce
1. Create a new permission that includes view, add, change, delete on extras > report and extras > script
2. View reports or scripts
3. See that ability to Run either is missing

### Expected Behavior
User with relevant permissions granted should be able to run reports or scripts

### Observed Behavior
1. Script shows message **You do not have permission to run scripts.**
1. 'Run Report' button is missing from /extras/reports
1. If there are historic report runs, 'Run Again' button is missing from /extras/reports/results/n

**Comment by jeremystretch** [comment]
Executing a script or report requires the model-specific `run` permission. This must be defined on the permission in addition to the default view, add, change, and delete operations.

![Screenshot_2020-09-24 Change permission NetBox](https://user-images.githubusercontent.com/13487278/94154410-d7845e00-fe4b-11ea-837d-30baed27186d.png)

**Comment by jeremystretch** [comment]
I'm going to classify this as a documentation issue since the current documentation is misleading.
