### ISSUE TITLE
ntc-netbox-plugin-onboarding is not creating UserConfig automatically.

### ISSUE THREAD

**Issue by Shash-gowda** [netbox-community/netbox#5179]
### Environment
* Python version:  3.6.8
* NetBox version:   2.9.3

### Steps to Reproduce
1.  With a fresh install of netbox 2.9.3 we imported and upgraded a database from version 2.8.3
2. Installed ntc-netbox-plugin-onboarding - https://pypi.org/project/ntc-netbox-plugin-onboarding/
3.  When I log in to the onboarding plugin and submit the device information, I see an error 

### Expected Behavior
The user's config inside users_userconfig table should be created.

### Observed Behavior
<img width="722" alt="Screen Shot 2020-09-24 at 3 19 35 PM" src="https://user-images.githubusercontent.com/71056312/94199179-6910c180-fe86-11ea-8d46-e3ab89b864ff.png">

**Comment by glennmatthews** [comment]
ntc-netbox-plugin-onboarding 1.3.0 is not compatible with NetBox 2.9. Refer to https://github.com/networktocode/ntc-netbox-plugin-onboarding/issues/85.

**Comment by jeremystretch** [comment]
This issue only serves issues related to NetBox itself. For bugs relating to the installation of specific plugins, please file a bug report against the plugin in question (or raise the discussion on our mailing list if you're unsure).
