### ISSUE TITLE
Installing on CentOS 8 results in error

### ISSUE THREAD

**Issue by andrewm659** [netbox-community/netbox#5181]
### Environment
* Python version:  3.6
* NetBox version: 2.9.4

I have followed the instructions on how to do this.  when I ge to the part of Loading the initial data it fails with the following error:
```
[root@netbox-centos netbox]# python3 manage.py loaddata initial_data
CommandError: No fixture named 'initial_data' found.
[root@netbox-centos netbox]#
``` 

### Steps to Reproduce
1. python3 manage.py loaddata initial_data

**Comment by adamwoolhether** [comment]
Guessing you fixed it? We run Netbox on CentOS 8 here, there's a small (like 1 or 2) amount of differences from the official documentation.

**Comment by andrewm659** [comment]
I haven't fixed but it occurred to me that I as reading OLD documentation....going to start over.  Also trying to get it running on FreeBSD 12.x.

**Comment by adamwoolhether** [comment]
For anyone installing on CentOS 8 without need for LDAP, I made a playbook that does it for you. You can find it here: https://github.com/adamwoolhether/NetBox4CentOS8

**Comment by andrewm659** [comment]
I have not fixed it.  Might blow it away and start over.
    On Thursday, September 24, 2020, 08:42:50 PM CDT, adamwoolhether <notifications@github.com> wrote:  
 
 


Guessing you fixed it? We run Netbox on CentOS 8 here, there's a small (like 1 or 2) amount of differences from the official documentation.

**Comment by adamwoolhether** [comment]
>  I have not fixed it.  Might blow it away and start over.

Check out the playbook I shared above? You can install the whole thing in a matter of minutes...

You're error specifically sounds like you didn't initialize the postgresql database.

**Comment by andrewm659** [comment]
Will do.

Sent from Yahoo Mail on Android 
 
  On Tue, Sep 29, 2020 at 5:43 PM, adamwoolhether<notifications@github.com> wrote:   



I have not fixed it.  Might blow it away and start over.


Check out the playbook I shared above? You can install the whole thing in a matter of minutes...

You're error specifically sounds like you didn't initialize the postgresql database.

**Comment by andrewm659** [comment]
So i'm going through the ansible playbook...any reason you didn't separate this out like a traditional playbook?  I'm trying to do that now.  Otherwise it looks good.

**Comment by andrewm659** [comment]
Also why use pip when python3-psycopg2.x86_64 & python3-pexpect.noarch are available through dnf/yum?

**Comment by jeremystretch** [comment]
I have to ask that you please continue this conversation on the mailing list if needed. This bug has been closed, and further discussion generates unnecessary distractions. Please submit a _new_ issue if you see the need arise.
