### ISSUE TITLE
GraphQL enabled API

### ISSUE THREAD

**Issue by ziggekatten** [netbox-community/netbox#5186]
### Environment
* Python version:  
* NetBox version:  

### Proposed Functionality
Using GraphQL to query the API to get information would simplify a lot of scenarios that today require multiple requests to get neccessary information. Example RootQuery would be: Tenant, IP-address, Prefix, VRF, VLAN, Interface, Virtual Machine, Virtual Interface, Device.

Having these would make life very easy to extract a Tenant's logical topology in one blow.

### Use Case
Minimize number of GET requests to identify ID of object in netbox based on their relations when preparing an external system to update several objects in netbox.

### Database Changes
No changes would be neccessary, as the models already have relations

### External Dependencies
There are a package called Graphene-Django that could do this

**Comment by dgarros** [comment]
I think it makes a lot of sense. 
I think even if the API is Read-Only at first to reduce the amount of work it would be extremely useful. 

Also there is already a project that did some work with Graphene-Django and NetBox that could be used for inspiration if needed https://github.com/ninech/django-netbox-graphql

**Comment by jeremystretch** [comment]
Thank you for submitting this issue, however it appears that this topic has already been raised. Please see issue #2007 for further discussion. This is not something we'll be undertaking in the near future.
