### ISSUE TITLE
RestrictedQuerySet uses user _object_perm_cache directly which is only set by ObjectPermissionBackend

### ISSUE THREAD

**Issue by Urth** [netbox-community/netbox#5187]
### Environment
* Python version: 3.7.9
* NetBox version: 2.9.4

### Steps to Reproduce
1. Authenticate non-superuser user with `RemoteUserBackend` or a custom backend that does not inherit from netbox' `ObjectPermissionBackend`.
2. User will not be able to visit pages that use `RestrictedQuerySet`

### Expected Behavior

Page to load as usual and skip object permissions if the configured authentication backend does not support it.

### Observed Behavior

`AttrributeError("'User' object has no attribute '_object_perm_cache'")`

**Comment by jeremystretch** [comment]
Please share your relevant configuration and the complete stack trace.

**Comment by Urth** [comment]
I thought authentication backends could be omitted if not used but this is not true for permissions which will be loaded from all available backends. So `netbox.authentication.ObjectPermissionBackend` must always be included even when not used to authenticate.
