### ISSUE TITLE
InfiniBand support for virtual interface.

### ISSUE THREAD

**Issue by blackgold** [netbox-community/netbox#5189]
### Environment
* Python version:  3.7.0
* NetBox version:  v2.8.9

### Proposed Functionality
Infiniband devices support SRIOV feature. When creating virtual functions, node and port GUID are empty. Operator sets node and port guid. It will be helpful to keep track of these virtual interfaces and their corresponding node and port GUIDs.

In the current net box, when an interface of Type "virtual" is created, there is no option to specify 
1. that the interface is InfiniBand vf
2. no option to specify node and port guid.

I will be nice to have the ability to specify that the virtual interface is of type InfiniBand, and it has so and so node guid and port guid. This can be interface property or we can have something like GUID-AM (guid address management) and attach GUID object to the interface, just like IP address can be attached to virtual interface.

### Use Case
When creating InfiniBand virtual functions, node and port GUID are empty. Operator sets node and port guid. It will be helpful to keep track of these virtual interfaces and their corresponding node and port GUIDs.  For example when a node reboots, a startup script can read interface information from netbox and set the node and port guids. 

### Database Changes
I am a netbox noob. I suppose it would require to extend interface of type virtual.

### External Dependencies
I don't think there is need for any external dependencies.

**Comment by jsenecal** [comment]
Potentially linked to https://github.com/netbox-community/netbox/issues/5102

**Comment by candlerb** [comment]
Possibly also relates to #1254

**Comment by jeremystretch** [comment]
Need someone familiar with InfiniBand to chime in here. #1519 proposes the ability to associate a virtual interface with a parent physical interface. Would that satisfy this FR? And if not, what would remain to be added assuming #1519 is implemented?
