### ISSUE TITLE
Device interfaces display filter slow

### ISSUE THREAD

**Issue by andershagman** [netbox-community/netbox#5191]
### Environment
* Python version: 3.6.12
* NetBox version: 2.9.3

### Steps to Reproduce
1. create  device with 1500 interfaces (our WAN router)
2. filter on what ever
3. wait for every letter to show ...

### Expected Behavior
Be able to white the filter before the search begin.

### Observed Behavior
Every letter takes 1-2 seconds to appear and makes it hard to write and use.

**Comment by jeremystretch** [comment]
Looks like we just need to bind to the`keyup` event rather than `input` and add a delay wrapper to give it half a second or so before it initiates the filtering.

**Comment by DanSheps** [comment]
I would also add an explicit submit reference perhaps as well so people can press enter to initiate the filter without waiting for the half a second.

**Comment by andershagman** [comment]
Hi

> 29 sep. 2020 kl. 22:47 skrev Daniel Sheppard <notifications@github.com>:
> 
> 
> I would also add an explicit submit reference perhaps as well so people can press enter to initiate the filter without waiting for the half a second.
> 
I would prefer just enter and add search in the description field as well.

/Anders
