### ISSUE TITLE
Long Response Time for Viewing IP Addresses with A Large Number of Duplicate Assignments

### ISSUE THREAD

**Issue by mtbutler07** [netbox-community/netbox#5197]
### Environment
* Python version: 3.6.8 
* NetBox version: 2.8.6

### Steps to Reproduce
1. Create any IP Address in Netbox and assign it to a large number of interfaces (1000+)
2. View the IP Address object

![Capture](https://user-images.githubusercontent.com/33135168/94573233-81426100-0237-11eb-8b08-ff8cc8b3e88f.PNG)

### Expected Behavior
- The page to load faster
- The list of duplicate IP addresses to be paginated (similar to the changelog view on the home page)

### Observed Behavior
- Long response time (3m15s for 16K duplicates)
   - We have a lot of access points....
- Gunicorn worker at 100% for the duration of the response

**Comment by jeremystretch** [comment]
It probably makes sense to just cap the number of duplicates returned to, say, 10, and link to a filtered list to "see all duplicates" if there are more than that.

**Comment by mtbutler07** [comment]
That seems reasonable and would work for my environment. 
Thanks for the quick reply!
