### ISSUE TITLE
Display custom links based on user permission

### ISSUE THREAD

**Issue by bistraque** [netbox-community/netbox#5202]
### Environment
* Python version:  3.6.9
* NetBox version:  2.9.2

### Proposed Functionality
Custom links currently appear unconditionally whether or not the user has permission to follow the link. By having the possibility to associate a _Custom Link_ with a specific _Permission_, it would be possible to hide the corresponding button/link in the UI if the user would ultimately fail using it (e.g. not allowed to execute scripts). A single Permission would suffice as it is possible to create a new specific permission rule if needed. The semantics would be: 
- if null, display custom link
- else if required permission is a subset of user permissions display link/button
- else hide link/button
- if all links in a group are hidden, hide group button

### Use Case
Our Netbox deployment is becoming a central source of truth with contributions from several external tools and environments. We use custom scripts to automate import and export of specific elements/attributes but not all users are involved in this, and not all users have the same domain in charge. This feature is a way to avoid a crowded custom link area if the number of custom script increases with time.

### Database Changes
Not familiar with Netbox DB but I guess a Permission reference, possibly null, in Custom Link table is needed

### External Dependencies
None

**Comment by DanSheps** [comment]
Could you clarify, are you saying a single permission total (can_view_customlink) or a single permission per custom link(can_view_customlink_x)?

Either way, the object based permissions were never meant to be this granular to apply to a single element on a page.  I think the technical requirements for implementation would far out weigh the benefits received.

**Comment by jeremystretch** [comment]
It's possible today to toggle the display of a custom link by rendering an empty link text. We don't currently pass any context to the link template beyond the object itself, though it's possible to change that. Any support for the consideration of permissions when rendering a custom link must be done through the use of template tags/context: We won't be adding any direct relationship between the CustomLink and ObjectPermission models.

**Comment by jeremystretch** [comment]
Permissions available to the current user can now be referenced using the `perms` context variable within a custom link text or URL. For example, to check for the `dcim.add_site` permission, check `{{ perms.dcim.add_site }}`. For more detail on referencing permissions within templates, see [the Django documentation](https://docs.djangoproject.com/en/stable/topics/auth/default/#permissions).

**Comment by bistraque** [comment]
Thanks, this `perms` object is perfect for the intended objective. I admit my approach was a bit naive...

One question: in this implementation, assuming all custom links belonging to a given group render as empty, would the group button be hidden as well?

**Comment by bistraque** [comment]
For the record, tested with v2.9.7: when all custom links of a group render as empty, the corresponding dropdown group button is not rendered.
