### ISSUE TITLE
No emptry text for device components except device bays

### ISSUE THREAD

**Issue by Dimaqa** [netbox-community/netbox#5204]
### Environment
* Python version: 3.8.2
* NetBox version: 2.9-develop

### Steps to Reproduce
Go to device page without components and there will be no empty placeholders 

### Expected Behavior

Shows something like no interfaces found

### Observed Behavior

Nothing displayed

**Comment by jeremystretch** [comment]
I don't know that it makes sense to spend the time on this rather than just commit to implementing #4786.

**Comment by jeremystretch** [comment]
Thinking about this more, yeah, I'd like to see someone tackle #4786 in earnest as it's longer overdue for implementation.
