### ISSUE TITLE
exported CSV cannot be reimported again due to wrong side_a_type & side_b_type

### ISSUE THREAD

**Issue by 4xoc** [netbox-community/netbox#5210]
### Environment
* Python version: 3.7.9
* NetBox version: >=2.8

### Steps to Reproduce
1. go to "Devices" > "Cables"
2. click on export any cable in "CSV (proper formatting for reimport)
3. download csv
4. reimport the CSV after deleting the cables

### Expected Behavior
The import runs through and creates the cables again.

### Observed Behavior
Error message:
```
Enter the list of column headers followed by one line per record to be imported, using commas to separate values. Multi-line data and values containing commas may be wrapped in double quotes.

    Row 1 side_a_type: Object not found.
    Row 1 side_b_type: Object not found.
    Row 1 __all__: Termination A type has not been specified
```
The side_a_type & side_b_type are exported as "dcim|interface" however, the import expects just "interface" for both values. Changing this value allows correct reimports/

Might affect more exports/imports

**Comment by DanSheps** [comment]
Thank you for opening a bug report. It seems that the described functionality is intended behavior. If you meant to open a feature request instead, please close this issue and open a new one using the [feature request template](https://github.com/netbox-community/netbox/issues/new?template=feature_request.md). Otherwise, please revise your post above to elaborate on why you believe the observed behavior is flawed.

**Comment by 4xoc** [comment]
Well, as the export is meant to be "proper format for reimport" and that clearly not being the case I'd consider this an incorrect behavior (even if intended?). Maybe the problem is not with the export itself but the import that rejects the values given from the exported csv and misses support for the "dcim|" prefix?

**Comment by jeremystretch** [comment]
> The side_a_type & side_b_type are exported as "dcim|interface"

This, specifically, is a bug, in that the output format should follow the format `<app_label>.<model>`; e.g. `dcim.interface`.

> Well, as the export is meant to be "proper format for reimport"

This is an erroneous assumption. Import and export are two entirely separate operations, logically. There are many instances where the two formats differ out of necessity to uniquely identify related objects upon import. Further, #4999 (currently a v2.10 objective) would result in fully dynamic export output depending on how the user has configured the table.

**Comment by DanSheps** [comment]
> This, specifically, is a bug, in that the output format should follow the format `<app_label>.<model>`; e.g. `dcim.interface`.

When I tested the export on 2.9.4, I received the proper output:

```
termination_a_type,termination_a_id,termination_b_type,termination_b_id,type,status,label,color,length,length_unit
dcim.interface,228,dcim.frontport,1,CAT6a,Connected,,,2,m
```

**Comment by 4xoc** [comment]
May I ask which type you've selected for the export. Because using 'default' also gives me the correct `dcim.interface` but 'proper format for reimport' does not; also tested on 2.9.4 (ldap docker image).

**Comment by jeremystretch** [comment]
> but 'proper format for reimport' does not

This must be a custom export template created within your installation. It is not part of NetBox. NetBox provides only the default CSV export functionality.

**Comment by 4xoc** [comment]
Oh sorry, I wasn't aware of that being a custom type. Thanks a lot for the help figuring this out.
