### ISSUE TITLE
Add has_primary_ip filtering to virtual machines

### ISSUE THREAD

**Issue by rodvand** [netbox-community/netbox#5211]
### Environment
* Python version:  3.7.5
* NetBox version:  2.9.3

### Proposed Functionality
Add the `has_primary_ip` filter which is currently available for devices to virtual machines as well.

### Use Case
Implementing has_primary_ip can avoid the need of having different setups for dealing with devices and virtual machines. A current use case is importing NetBox object into a third-party system for managing firewall rules. With devices I can easily import only the devices with a primary IP address using the `has_primary_ip` filter, while with virtual machines I have to make the IP lookup on my own and thus creating two different workflows for the same task.

### Database Changes
None

### External Dependencies
None

**Comment by jeremystretch** [comment]
I'm reclassifying this as a bug since it's reasonable to expect that the `has_primary_ip` filter would be available for both devices and virtual machines given that they both have a `primary_ip` attribute.
