### ISSUE TITLE
Drag and Drop Moving of Devices in Rack Elevations

### ISSUE THREAD

**Issue by jameno123** [netbox-community/netbox#5214]
### Environment
* Python version:  3.6
* NetBox version:  2.9.3

### Proposed Functionality
When performing rack migrations it is cumbersome to migrate alot of machines manually requiring several steps in the netbox UI. The purpose of this feature would be to enable drag and drop support inside the rack elevations page so that you can click a server drag it onto a new rack position (in same rack or a different rack) and the netbox system will then set the new rack location in the db.

### Use Case
Consolidating one rack into 3 others in the same rack row reducing rack space foot print servers from 1 rack are going into various different racks drag and drop would speed up the process of moving these servers significantly

### Database Changes
none

### External Dependencies
none

**Comment by jeremystretch** [comment]
Thank you for submitting this issue, however it appears that this topic has already been raised. Please see issue #124 for further discussion.

**Comment by chicks-net** [comment]
Issue #124 is closed to comments from non-collaborators.  Since the current collaborators are not interested in this feature  this seems like a good way to avoid further discussion or potential new contributors that might have the skills and interest to add this feature.  Should #124 be unlocked?

**Comment by jeremystretch** [comment]
No. We've opted not to pursue that feature.
