### ISSUE TITLE
Add Secondary IP To Device

### ISSUE THREAD

**Issue by almostbeef** [netbox-community/netbox#5219]
### Environment
* Python version: Python 3.6.8
* NetBox version: 2.9.4

### Proposed Functionality
Allow Secondary IP Address association for Devices.

### Use Case
We are using Netbox as an inventory source for Ansible. Some of our network gear are using two separate management cards. These are configured with two separate IP Addresses. In the event of a port failure, we would need to connect to the secondary port. My request is that an association is created with another IP as a "Secondary" address.

### Database Changes
Unsure. I believe this would just be a new Device Field with a similar setup as the Primary Address. 

### External Dependencies
Unsure.

**Comment by olant** [comment]
You can add several interfaces to your device and assign separate IP addresses to each of the interfaces. Is this what you are looking for? You can even assig role "secondary" to that IP address.

**Comment by almostbeef** [comment]
The "primary_ip" field of the device is the one used connect to it. Having a second(ary) IP Address on the Interface doesn't allow for the secondary to become associated with device management in the event that it's unreachable. 

I suppose that constantly monitoring the IP Connectivity and updating the device's primary IP in the event of failure would work too. The goal of the feature would be to have a preconfigured "backup" mgmt IP/Port included in the device fields to try if unsuccessful on the Primary.

**Comment by jeremystretch** [comment]
NetBox allows for a primary IPv4 and primary IPv6 address to be assigned to each device and virtual machine. This allows a user to specify the IP by which a device or VM should be primarily accessed (assuming it is not reachable by name). Practically, speaking, it does not make sense to further identify successive IP addresses, because there are myriad failure conditions which may dictate reachability by one non-primary IP versus another. It would also duplicate a large amount of model and validation logic.

**Comment by almostbeef** [comment]
I wasn't suggesting that Netbox do the validation (although I suspect that I'm not fully utilizing this feature, and don't understand it). Only that a new field identifies a backup interface/ip

I will pursue the route of updating the Device IP when we detect a failure.

**Comment by jeremystretch** [comment]
> I wasn't suggesting that Netbox do the validation

By validation, I mean such tasks as ensuring that the assigned IP belongs to the device/VM, checking that the primary and secondary IPs are different, etc.

**Comment by DanSheps** [comment]
You can filter device interfaces by "Is this a management interface".  The flag is `mgmt_only=true`:

https://master.netbox.dev/dcim/interfaces/?mgmt_only=true

vs

https://master.netbox.dev/dcim/interfaces/

**Comment by almostbeef** [comment]
Thanks for the suggestion. I'll work on devising a way to utilize that.

This request can be closed.
