### ISSUE TITLE
Remove the dedicated views and REST API endpoints for console/power/interface connections

### ISSUE THREAD

**Issue by jeremystretch** [netbox-community/netbox#5223]
### Proposed Changes
NetBox currently has dedicated view and REST API endpoints for listing console, power, and interface connections. This proposal seeks to remove these completely, and merge their functionality into the new views and endpoints dedicated to each model.

### Justification
The connection lists, being necessarily decoupled somewhat from their related models, don't offer as much flexibility with regard to ordering, filtering, etc. They are also limited, for instance, in that the power connections list will not display connections from power ports to power feeds.

Attaching connection information to the individual component lists should fully replicate their existing functionality. The only caveat is the interface connections list, which applies filtering to avoid showing both directions of a connection between interfaces. However, we should be able to replicate this by adding a boolean filter to the interfaces list.

**Comment by jeremystretch** [comment]
Blocked by #4999

**Comment by ryanmerolle** [comment]
No objections here if views can replicate "similarish" sort of output.

**Comment by minitriga** [comment]
As long as we can get the data for console, power and interface connections via other API calls that should be fine.

**Comment by jeremystretch** [comment]
I'm going to remove the REST API endpoints for these connections since they're largely redundant, but leave the UI views in place as I can see how having them separate from the component views is convenient. Maybe we'll revisit the UI views once we have a more robust mechanism around table preferences in place (to remember/re-apply saved configurations).
