### ISSUE TITLE
Custom choice fields should be blank initially if no default choice has been designated

### ISSUE THREAD

**Issue by itdependsnetworks** [netbox-community/netbox#5226]
### Environment
* Python version: 3.7
* NetBox version: 2.9.4

### Proposed Functionality

The ability to create a custom field as a selection with no functional default. While there may be no defined defined default, functionally there is a default option .

### Use Case

Giving the administrator the ability to ensure requestors do not blindly accept which ever the first value is in a custom field selection. As an example, an administrator may require a `zone` to be applied, but want to ensure that that users do not ignore the value, and simply save/update the record.

Given:
![image](https://user-images.githubusercontent.com/9260483/95528043-06024d00-09a5-11eb-8b58-4c7f27ff2096.png)

Currently Results in:
![image](https://user-images.githubusercontent.com/9260483/95528498-47472c80-09a6-11eb-9dce-c9c179c39091.png)

Intended state:
![image](https://user-images.githubusercontent.com/9260483/95528583-7cec1580-09a6-11eb-94c2-6ce68ed0c114.png)

### Database Changes

I do not not believe there are any. 

### External Dependencies

N/A

**Comment by jeremystretch** [comment]
I'm going to classify this as a bug since it's fair to say that the current behavior is likely to lead to an unintended state.
