### ISSUE TITLE
Add netmask notation to prefix detail page

### ISSUE THREAD

**Issue by a-d-v** [netbox-community/netbox#5227]
### Environment
* Python version: 3.9
* NetBox version: 2.9.3

### Proposed Functionality
It would be convenient for users to also supply the netmask within the prefix details page.
Current only the slash notation is mentioned. Maybe just adding something like 

192.168.1.0/24 **(255.255.255.0)**
### Use Case
Users registering and obtaining data from NSOT often require the netmask type of notation to configure devices. This would simplify information gathering for the more uncommon subnets.

### Database Changes
No changes needed

**Comment by jeremystretch** [comment]
Expressing the mask in dotted-decimal format is redundant. NetBox uses the CIDR notation (e.g. /24) universally because it is the more efficient expression. If the dotted-decimal format is needed, conversion should be performed by the client.

**Comment by DanSheps** [comment]
This was also raised under: #3236
