### ISSUE TITLE
API virtual-machines only return primary ip address

### ISSUE THREAD

**Issue by vnStrawHat** [netbox-community/netbox#5241]
### Environment
* Python version: 3.6.8
* NetBox version: v2.8.3

### Steps to Reproduce
1. create new Virtual Machine
2. create new Interface
3. assign Interface to Virtual Machine
4. Assign IP 01 to Interface and mark as primary IP
5. Assign IP 02 to interface
![image](https://user-images.githubusercontent.com/4435695/96074481-fd44d600-0ed2-11eb-9614-c85b04ff4103.png)

### Expected Behavior
When access to the API https://netbox.local:8443/api/virtualization/virtual-machines/<id>
the result should include  02 IP address

### Observed Behavior
When access to the API https://netbox.local:8443/api/virtualization/virtual-machines/<id>
The result only have primary IP

How can we get all IP Address of Virtual Machine instead of primary IP only ?

**Comment by jeremystretch** [comment]
This is expected behavior. Please see [the documentation](https://netbox.readthedocs.io/en/stable/rest-api/overview/) for instructions on using the REST API, or post to our [mailing list](https://groups.google.com/g/netbox-discuss) for assistance.
