### ISSUE TITLE
Grouping tcp+udp services

### ISSUE THREAD

**Issue by Matze1224** [netbox-community/netbox#5246]
### Environment
* Python version: 3.7.3
* NetBox version: 2.9.7

I have some services which both listen on TCP and UDP. There are DNS, mumble and some gameservers.

### Proposed Functionality
Instead of creating the service twice for TCP and UDP, it would be better to select both (by marking both in the drop-down) or simply select "TCP+UDP" in the service creation UI. This would assume to store this information in a single entry.

### Use Case
Easier creation instead of repeating the service creation a second time.

### Database Changes
Maybe to allow storing TCP and UDP in the same database entry.

### External Dependencies
n/a

**Comment by jeremystretch** [comment]
This would violate the strict meaning of the `protocol` field. As the service model is often employed for generating firewall rules and similar constructs, allowing this field to convey non-protocol values would introduce undue complexity for API consumers.

For example, if you have a script that generates a firewall policy from services populated in NetBox, you could no longer rely on the protocol field to convey a literal value. In the event it returned a value representing the combination of TCP and UDP, additional logic would be needed to replicate this into two rules (one for each protocol) each with its appropriate literal value.

**Comment by Matze1224** [comment]
And what's about just grouping them in the UI? So there are still two entries, but it's easier to configure.

**Comment by jeremystretch** [comment]
Seems like it would be too much effort for very little value.

**Comment by Matze1224** [comment]
Yes, I understand. My last idea would be to have presets which could create the required services, but I guess this is already covered by custom scripts. So I guess it's not a great pain to copy'n'paste it over (as I'm the first one thinking about it) - just some idea to optimize it a bit.

**Comment by Matze1224** [comment]
Closing it because it doesn't look that something like this will be implemented.
