### ISSUE TITLE
Group Front Ports and Rear Ports in single tab

### ISSUE THREAD

**Issue by jeremmfr** [netbox-community/netbox#5249]
### Environment
* Python version: 2.7.15
* NetBox version: 2.9.7

### Proposed Functionality

Since 2.9 version, the view of components in device (/dcim/devices/1234/) is grouped by type in a corresponding tab.
But for patch-panel devices, looking `Front ports` and `Rear ports` in different tabs can be painful.

Can you group `Front Ports` and `Rear Ports` into one tab (maybe with user preference) ?
Another solution is to have an option to looking all components in the same page (without tab) ?

### Use Case
<img width="1503" alt="Capture d’écran 2020-10-19 à 17 15 37" src="https://user-images.githubusercontent.com/8632778/96470671-d407ab00-122e-11eb-9262-c3b81b31df95.png">

**Comment by jeremystretch** [comment]
> But for patch-panel devices, looking Front ports and Rear ports in different tabs can be painful.

Can you expand on this? What information are you looking for that isn't currently displayed?

**Comment by jeremmfr** [comment]
Hi,

For example, being able to check/add Description or Connection on a `Front Port` and looking description and device/circuit connected on corresponding `Rear Port` in same page (without switch between two tabs).

Best regards

**Comment by jeremystretch** [comment]
Older versions of NetBox originally had the panels side-by-side as you propose. We moved away from that layout for several reasons:

1. Forcing too much content within the screen makes it all difficult to read.
2. Showing both tables on the same view precludes the ability to intuitive order/filter (a planned future feature).
3. It diverges from the view structure for all other components.
4. It yields little benefit for multi-position rear ports as the table rows do not align (and doing so would be non-trivial).

**Comment by fstolba** [comment]
+1 for having a user configurable option to revert to non-tabbed view displaying front and back ports on the same page. They don't need to be aligned next to each other or anything like that, just being able to have the one-page layout we had until 2.8 would suffice. IMHO the old layout was much easier to work with.
