### ISSUE TITLE
Rear port doesn't sync after an edit.

### ISSUE THREAD

**Issue by JulesRe** [netbox-community/netbox#5260]
### Environment
* Python version: 3.7.3-1
* NetBox version: 2.9.7

### Steps to Reproduce
1. Create a device with a first device type.
2. Edit this device and change the device type with another one.
3. You can see the rear port don't sync with the new device types.

### Expected Behavior
I expect to the device to change is rear port to the go device types.

### Observed Behavior
That doesn't sync, so I had to recreate manually all devices with the good device types.

**Comment by jeremystretch** [comment]
This is expected behavior and has been covered in other issues.
