### ISSUE TITLE
MultiObjectVar does not accept initial data via URL

### ISSUE THREAD

**Issue by rodvand** [netbox-community/netbox#5261]
### Environment
* Python version: 3.7.5
* NetBox version: 2.9.7

### Steps to Reproduce
1.  Create a custom script utilising MultiObjectVar. Example ob_var.py:
```
from extras.scripts import *
from virtualization.models import VirtualMachine

class ObjectVarTest(Script):
    vm = MultiObjectVar(
            model=VirtualMachine
            )

    def run(data, commit):
        pass
```
2. Find the ID of one of your Virtual Machines
3. Try using the URL https://your.netbox.install/extras/scripts/ob_var.ObjectVarTest/?vm=13

### Expected Behavior
That the initial field for a Virtual Machine would be pre-filled with my VM number 13.

### Observed Behaviour
Nothing is pre-filled.

Change the MultiObjectVar to ObjectVar and repeat the test - the field is pre-filled with the Virtual Machine.

**Comment by jeremystretch** [comment]
I've dug into this a bit but can't account for the bug: AFAICT the form field is being initialized with the correct data. It may be related to the Select2 library.
