### ISSUE TITLE
Include show images toggle in user preferences

### ISSUE THREAD

**Issue by hansswanson** [netbox-community/netbox#5262]
### Environment
* Python version: 3.8
* NetBox version: 2.9.7

### Proposed Functionality

The change I am proposing is to save if a user toggled the rack elevation images on or off to user preferences when they select the show images toggle.

### Use Case

This allows a user to maintain their preferred elevation version when switching between different racks without having to select the show images button every time.

**Comment by jeremystretch** [comment]
Thank you for submitting this issue, however it appears that this topic has already been raised. Please see issue #5203 for further discussion.
