### ISSUE TITLE
Device Name does not have to be unique when created via script.

### ISSUE THREAD

**Issue by 991jo** [netbox-community/netbox#5269]
### Environment
* Python version: 3.6.8
* NetBox version: 

### Steps to Reproduce
1. add a device.
2. run a script that adds a device with the same name as the device added in 1.

### Expected Behavior
Netbox raises an exception that a device with that name already exists.

### Observed Behavior
Netbox creates the device. Now there are 2 devices with the same name.
When editing one of the devices via the WebUI you get a "a device with this name exists" error

**Comment by jeremystretch** [comment]
As the custom script's author, you are responsible for ensuring the validity of data being written to the database. Please see the [Django documentation](https://docs.djangoproject.com/en/3.1/ref/models/instances/#validating-objects) on model validation for more information.
