### ISSUE TITLE
fix path in cp command

### ISSUE THREAD

**Issue by systeembeheerder** [netbox-community/netbox#5275]
### Change Type
[ ] Addition
[X ] Correction
[ ] Deprecation
[ ] Cleanup (formatting, typos, etc.)

### Area
[ ] Installation instructions
[ ] Configuration parameters
[ ] Functionality/features
[ ] REST API
[ ] Administration/development
[ ] Other

### Proposed Changes

````
# cp -r /opt/netbox-X.Y.Z/netbox/scripts /opt/netbox/netbox/scripts/
# cp -r /opt/netbox-X.Y.Z/netbox/reports /opt/netbox/netbox/reports/
````
will create a directory
``/opt/netbox/netbox/scripts/scripts``  and `` /opt/netbox/netbox/reports/reports``

**Comment by DanSheps** [comment]
What is your proposed change?

**Comment by chicks-net** [comment]
#5276 looks like the fix.

**Comment by DanSheps** [comment]
Unfortunately, that is not a workable solution (we are going to try and stay away from relative paths so that everything is explicit, if you deviate from the recommended configuration it is on you to resolve).

**Comment by systeembeheerder** [comment]
@chicks-net yes, thank you
@DanSheps ok, I can rewrite the patch to absolute paths, no problem. Can we agree the current cp command does copy to the wrong directory?
