### ISSUE TITLE
Move secrets to an official plugin

### ISSUE THREAD

**Issue by DanSheps** [netbox-community/netbox#5278]
### Environment
* Python version: 3.7
* NetBox version: 2.9.7

### Proposed Functionality

Move the secrets app to a dedicated official plugin

### Use Case

There have been a few requests to improve the secrets functionality or to allow integration into a third party secret vault (HashiCorp, etc).  Additionally, we have a naming collision with the "secrets" python standard library (#4553).  Moving the secrets app into a dedicated plugin would allow us to:

* Rename the plugin app to resolve the naming collision with the python standard library
* Increase the ease of updating and modifying the secrets plugin
* Provide a plugin to showcase the capabilities of the NetBox plugins framework
* Provide a plugin to test against for issues with the plugins framework
* Allow plugin developers to integrate their own secret plugins

### Database Changes

Table changes to accommodate moving the app to a official plugin

### External Dependencies

None

**Comment by jeremystretch** [comment]
> Provide a plugin to test against for issues with the plugins framework

Just want to note that we have this already: There's a `dummy_plugin` plugin buried within the `extras` app that's enabled and configured solely for testing. Tests intended to run against a production plugin would probably be too difficult to maintain.

**Comment by jeremystretch** [comment]
This is something we can keep in mind for the future, but for the time being it's not something worth the necessary commitment of time and effort.

**Comment by jeremystretch** [comment]
Reopening this for @DanSheps.

**Comment by jeremystretch** [comment]
@DanSheps and I decided to push this back (slightly) to the v2.12 release. This ensures a quicker release for v2.11, and provides more warning time for users of the secrets functionality.

**Comment by jameskirsop** [comment]
@DanSheps, do you have an update on the plugin? I'd be interested to see it and start working towards implementing something to address #4980 using the _official_ plugin if possible, so that when v2.12 drops we could include this feature at the same time.

**Comment by jeremystretch** [comment]
Closing out this issue as the secrets code has been removed from NetBox core. Work is still underway on the plugin.

**Comment by twexler** [comment]
@jeremystretch is there an issue or repo one can use to track the work on the secrets plugin?

**Comment by jeremystretch** [comment]
@DanSheps has been working on it here: https://github.com/DanSheps/netbox-secretstore

**Comment by n3bojs4** [comment]
Hello !
In my humble opinion, a plugin for hashicorp vault would be a real killer.

**Comment by DanSheps** [comment]
> In my humble opinion, a plugin for hashicorp vault would be a real killer.

you are free to develop one yourself.

Unfortunately this issue is specifically for deprecating secrets.
