### ISSUE TITLE
LLDP Information Not Populating

### ISSUE THREAD

**Issue by magic9669** [netbox-community/netbox#5287]
Hello all.  Not sure if this is the proper area for this issue, but figured I'd start here.

None of my devices are showing LLDP information.  I can't figure out why.  I have tested on the following device types:

Arista, Juniper, Cisco IOS and Cisco IOS-XR

Along with this, for whatever reason, IOS-XR isn't populating any information.  It's not returning any status errors so it's connecting via NAPALM API call, but it's just not returning anything at all.

Any help would be appreciated.

**Comment by jeremystretch** [comment]
Thank you for your interest in NetBox. GitHub issues are intended for reporting reproducible bugs and requesting features, and must be submitted using one of the templates provided [here](https://github.com/netbox-community/netbox/issues/new/choose). For general discussion, questions, or assistance with installation issues, please post to our [mailing list](https://groups.google.com/forum/#!forum/netbox-discuss) instead.
