### ISSUE TITLE
Inherit custom fields from device type to device

### ISSUE THREAD

**Issue by TheNetworkGuy** [netbox-community/netbox#5289]
### Environment
* Python version: 3.8.1
* NetBox version: 2.9.4

### Proposed Functionality
To my knowledge, device types can be seen as "templates" by which a device is created. After that the device is customized with IP address, subinterfaces etc.
However custom fields do not apply to this rule. It would be great to specify a value only related to that device type which gets inherited to the device itself, just like the interfaces and rack U information etc.

### Use Case
Pulling values from Netbox to other applications such as Splunk, Ansible, Zabbix etc. Specifically for Zabbix for managing the template which the device receives. This information is (in my environment) for device types the same which makes propagating it to the device logical. Furthermore it would follow the "template" expectation from device types quite nicely.

### Database Changes
Sorry but i'm not skilled enough on DB level to know this 100%.
I can only guess that its Python code since the functionality for custom fields is already present for both devices and device types.

### External Dependencies
None.

Thanks for reading and considering this FR!

**Comment by jeremystretch** [comment]
I'm not sure I follow. There's no need to replicate the value of a custom field from a device type to a device, because the device object has access to its parent device type's custom fields; e.g. `device.device_type.cf['my_custom_field']`.

**Comment by TheNetworkGuy** [comment]
Completely missed that on my part. In that case this FR seems kind of unnecessary since you can get to the data through the device type. Thanks for the quick response!
