### ISSUE TITLE
Two devices of the same name returns MultipleObjectsReturned

### ISSUE THREAD

**Issue by ledgley** [netbox-community/netbox#5291]
### Environment
* Python version: 3.6.8
* NetBox version: 2.9.4

### Steps to Reproduce
1. Create new device and assign to site, tenant, role. Set status to 'Decommisioning'
2. Create another device of the same name, create with the same attributes, though assign to different site and set status to 'Active'
3. Try to view device detail of either device

### Expected Behavior
Load device detail view for both devices

### Observed Behavior
```<class 'dcim.models.devices.DeviceType.MultipleObjectsReturned'>

get() returned more than one DeviceType -- it returned 2!

Python version: 3.6.8
NetBox version: 2.9.4
```

**Comment by lampwins** [comment]
Thank you for submitting this issue. Before any further work can be done, please upgrade to the most recent
stable release of NetBox (currently 2.9.7) as this issue may have already been addressed. Please then
update your issue to indicate whether further action is needed.

**Comment by jeremystretch** [comment]
FYI I'm not able to reproduce this on v2.9.7.

**Comment by ledgley** [comment]
Apologies, should've tested later release. Cannot reproduce on 2.9.8.
