### ISSUE TITLE
VRRP IP address for Virtual Chassis

### ISSUE THREAD

**Issue by Rosettag** [netbox-community/netbox#5294]
Hi,

thanks for great tool you have created. 
I've just started to transfer my IP addresses into Netbox IPAM. Is that possible to add interface to virtual chassis so that we avoid having duplicate IP address for each slot as VRRP?

**Comment by jeremystretch** [comment]
Thank you for your interest in NetBox. GitHub issues are intended for reporting reproducible bugs and requesting features, and must be submitted using one of the templates provided [here](https://github.com/netbox-community/netbox/issues/new/choose). For general discussion, questions, or assistance with installation issues, please post to our [mailing list](https://groups.google.com/forum/#!forum/netbox-discuss) instead.
