### ISSUE TITLE
Fix SyntaxWarning

### ISSUE THREAD

**Issue by timrabl** [netbox-community/netbox#5296]
**Theoretically this belongs in the housekeeping section.**

### Environment
* Python version: 3.9
* NetBox version: v2.9.8

### Proposed Functionality

Repalce `is` with `==`:

https://github.com/netbox-community/netbox/blob/2424f684b9594355b0f32475cb5a407c3e781872/netbox/utilities/api.py#L116

https://github.com/netbox-community/netbox/blob/2424f684b9594355b0f32475cb5a407c3e781872/netbox/utilities/api.py#L124

### Use Case
Remove errors on running NetBox, `is` raises a `SyntaxWarning` error in python, see the following:

> /opt/netbox/netbox/utilities/api.py:116: SyntaxWarning: "is" with a literal. Did you mean "=="?
>   if obj is '':
> /opt/netbox/netbox/utilities/api.py:124: SyntaxWarning: "is" with a literal. Did you mean "=="?
>   if data is '':

### Database Changes

None

### External Dependencies

None

**Comment by jeremystretch** [comment]
NetBox does not yet officially support Python 3.9. Such issues will be addressed when support is added.
