### ISSUE TITLE
Adding media ports

### ISSUE THREAD

**Issue by pozar** [netbox-community/netbox#5298]
### Environment
* Python version: 3.6.9
* NetBox version: 2.9.8

### Proposed Functionality

Netbox would be perfect for recording and broadcast studios but there needs to be a couple of different categories of media interfaces added such as video and audio.  Of course, there are analog and digital components to each such as:

Audio
    Analog
        RCA Pin Plug - Male
        RCA Pin Plug - Female
        XLR - Male
        XLR - Female
        1/4" TRS - Male
        1/4" TRS - Female
        1/4" TS - Male
        1/4" TS - Female
        3.5mm TRS - Male
        3.5mm TRS - Female
        3.5mm TRRS - Male
        3.5mm TRRS - Female
        ...
    Digital
        SPIDF - Optical
        SPIDF - Coax
        AES3 - Male
        AES3 - Female
        HDMI Type A
        HDMI Type B
        HDMI Type C
        HDMI Type D
        HDMI Type E
        ...
Video
    Analog
        Composite BNC - Male
        Composite RCA - Male
        S-Video - Male
        VGA - Male
        ...
    Digital
        HDMI Type A
        DVI-D Dual-Link
        DVI-D Single-Link
        DVI-I Dual-Link
        DVI-I Single-Link
        Mini DisplayPort
        ...

### Use Case

Recording and Broadcast Studios

### Database Changes

Possibly new tables such as dcim_media*

### External Dependencies

No external libraries or services should be needed.

**Comment by jeremystretch** [comment]
The interface model is intended to model only network interfaces, so it would not make sense to add non-network types. This has been proposed and rejected in prior feature requests.

**Comment by pozar** [comment]
@jeremystretch Netbox supports power and console interfaces/ports that are not network.  Could you suggest another model here for media ports in netbox?

**Comment by pozar** [comment]
@jeremystretch Just to follow up, if I did the work, would it be accepted in the main branch?

**Comment by jeremystretch** [comment]
> Netbox supports power and console interfaces/ports that are not network

Yes, and it has specific models to support those. It does not use the Interface model for that purpose.

>  if I did the work, would it be accepted in the main branch?

No, because this functionality is outside NetBox's scope. Again, this has already been discussed in previous issues.

**Comment by ypid** [comment]
Sounds like a nice scope for a plugin. Go wild @pozar :). From what I see, the docs for plugin development are extensive: https://netbox.readthedocs.io/en/stable/plugins/development/

Ref: #3020, #2865

**Comment by pozar** [comment]
@ypid Thanks for the pointer.  I'll review this.
