### ISSUE TITLE
Unable to filter device types by manufacturer name

### ISSUE THREAD

**Issue by larsks** [netbox-community/netbox#5299]
### Environment
* Python version: Python 3.8
* NetBox version: 2.9

### Steps to Reproduce

I am trying to filter `devices-types` by `manufacturer`. According to [the API docs](https://netboxdemo.com/api/docs/), `GET /dcim/device-types/` supports both `manufacturer` (a string) and `manufacturer_id` (an integer) as query parameters. Querying by manufacturer id seems to work:

```
$ http  "${NETBOX_URL}/api/dcim/device-types/?manufacturer_id=2"   "Authorization:Token $NETBOX_TOKEN"
HTTP/1.1 200 OK
[...]

{
    "count": 1,
    "next": null,
    "previous": null,
    "results": [
            [...]
            "manufacturer": {
                "id": 2,
                "name": "Dell Inc.",
                "slug": "dell-inc",
                "url": "http://netbox-moc-ops.apps.example.com/api/dcim/manufacturers/2/"
            },
            [...]
    ]
}
```

But attempting to query by manufacturer name fails:

```
$ http  "${NETBOX_URL}/api/dcim/device-types/?manufacturer=Dell+Inc."   "Authorization:Token $NETBOX_TOKEN"
HTTP/1.1 400 Bad Request
[...]

{
    "manufacturer": [
        "Select a valid choice. Dell Inc. is not one of the available choices."
    ]
}
```

### Expected Behavior

I expected to be able to filter the list of device types by manufacturer name.

### Observed Behavior

Netbox returned a 400 status with the error message described above.

**Comment by larsks** [comment]
Apparently I can query by `manufacturer_name`, although that doesn't show up in the API documentation:

```
$ http  "${NETBOX_URL}/api/dcim/device-types/?manufacturer_name=Dell+Inc."   "Authorization:Token $NETBOX_TOKEN"
HTTP/1.1 200 OK
[...]

{
    [...]
    "results": [
        {
            [...]
            "manufacturer": {
                "id": 2,
                "name": "Dell Inc.",
                "slug": "dell-inc",
                "url": "http://netbox-moc-ops.apps.example.com/api/dcim/manufacturers/2/"
            },
            [...]
        }
    ]
}
```

I'm not sure if this is a documentation problem, or if I'm just failing to read the API docs correct?

**Comment by jeremystretch** [comment]
The `manufacturer` filter matches on the manufacturer's slug, not the human-friendly name, so you want e.g. `?manufacturer=dell-inc`. Please post to the mailing list if you require any further assistance.

**Comment by larsks** [comment]
There appears to be a doc bug, since the api docs only mention `manufacturer` and `manufacturer_id`. I'd offer to fix it, but you've closed the issue and suggested there's not a problem, so maybe you disagree.
