### ISSUE TITLE
Clarify "Replicating NetBox" section "Cache Invalidation"

### ISSUE THREAD

**Issue by cs-1** [netbox-community/netbox#5300]
### Change Type
[X] Addition
[X] Correction
[ ] Deprecation
[ ] Cleanup (formatting, typos, etc.)

### Area
[ ] Installation instructions
[ ] Configuration parameters
[ ] Functionality/features
[ ] REST API
[X] Administration/development
[ ] Other

### Proposed Changes
We use a staging server to test changes to NetBox and thus replicate our production server regularly using an Ansible playbook. While implementing the replication I realised that the section "Cache Invalidation" of "Replicating NetBox" needs two changes:

- It's not entirely clear from the documentation whether to run `python3 manage.py invalidate all` on the source machine or the destination machine if you're unfamiliar with the internals of NetBox. This should should be explained in this section.
- The command `python3 manage.py invalidate all` doesn't work without prior issuing `source /opt/netbox/venv/bin/activate`. This should be corrected.

**Comment by jeremystretch** [comment]
Fixed in b39019ce
