### ISSUE TITLE
Enable adding contact information to manufacturers

### ISSUE THREAD

**Issue by ozmusic** [netbox-community/netbox#5302]
### Environment
* Python version: 3.6.8
* NetBox version: 2.9.7

### Proposed Functionality
Add additional fields to Device Manufacturer to support adding additional information similar to Circuit Providers, such as: contract, contacts (account manager, support numbers), account/contract number, support portal. Or, enable adding custom fields to dcim.manufacturers

Could link in with issue #1344 for linking account/support contacts

### Use Case
User wants to record details of Account manager and technical account manager for a device manufacturer, along with the account number and support portal so that this information can be shared between team members. 

### Database Changes
Additional fields tied to the manufacturer would be required to store the additional contact information .

**Comment by jeremystretch** [comment]
> User wants to record details of Account manager and technical account manager for a device manufacturer, along with the account number and support portal so that this information can be shared between team members.

This has been proposed in past issues, and we've decided that such functionality is out of scope for NetBox core. (Additionally, the manufacturer model would be a poor location to house this information.) However, you might be interested in developing a plugin that implements this feature.
