### ISSUE TITLE
Repeated ContentType SQL queries in enqueue_webhooks slow down bulk-delete of objects via UI

### ISSUE THREAD

**Issue by glennmatthews** [netbox-community/netbox#5309]
### Environment
* Python version: 3.7
* NetBox version: 2.8.9

### Steps to Reproduce
1. Via the UI, bulk-delete several thousand records (any object type; I observed this with custom models in a plugin but I do not believe that this is a requirement) in a single request
2. Observe how long the request takes to complete and return a new page.

### Expected Behavior

Request should complete within a couple of seconds.

### Observed Behavior

Deleting 2000 records takes approximately 28 seconds in my testing.

### Analysis

It appears that `enqueue_webhooks()` is called for each record being deleted, and each time `enqueue_webhooks()` is called, it makes an SQL query for ContentType objects:

```
SELECT "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model"
FROM "django_content_type"
WHERE (
("django_content_type"."app_label" = 'dcim' AND "django_content_type"."model" IN ('consoleport', 'consoleserverport', 'powerport', 'poweroutlet', 'interface', 'frontport', 'rearport', 'devicebay', 'inventoryitem', 'region', 'site', 'rack', 'rackreservation', 'manufacturer', 'devicetype', 'device', 'virtualchassis', 'powerpanel', 'powerfeed', 'cable'))
OR ("django_content_type"."app_label" = 'circuits' AND "django_content_type"."model" IN ('provider', 'circuit'))
OR ("django_content_type"."app_label" = 'virtualization' AND "django_content_type"."model" IN ('cluster', 'virtualmachine')) 
OR ("django_content_type"."app_label" = 'ipam' AND "django_content_type"."model" IN ('vrf', 'aggregate', 'prefix', 'ipaddress', 'vlan', 'service'))
OR ("django_content_type"."app_label" = 'secrets' AND "django_content_type"."model" IN ('secret'))
OR ("django_content_type"."app_label" = 'tenancy' AND "django_content_type"."model" IN ('tenant'))
); args=('dcim', 'consoleport', 'consoleserverport', 'powerport', 'poweroutlet', 'interface', 'frontport', 'rearport', 'devicebay', 'inventoryitem', 'region', 'site', 'rack', 'rackreservation', 'manufacturer', 'devicetype', 'device', 'virtualchassis', 'powerpanel', 'powerfeed', 'cable', 'circuits', 'provider', 'circuit', 'virtualization', 'cluster', 'virtualmachine', 'ipam', 'vrf', 'aggregate', 'prefix', 'ipaddress', 'vlan', 'service', 'secrets', 'secret', 'tenancy', 'tenant')
```

As a result, deleting 2000 records results in 2000 SQL queries, adding substantially to the request runtime. This appears to be due to the code changes made in #3932 (specifically [here](https://github.com/netbox-community/netbox/pull/3932/files#diff-7908dbffe3012a9b0bec4269853a470b009c95ec4c8a2a8f95e22f87810dabb0L14)). It should be possible to cache the results of the ContentType lookup in some fashion rather than re-executing the same query over and over again, which should resolve this performance issue.

**Comment by jeremystretch** [comment]
This came up during work on v2.10. I believe the root cause is the way FeatureQuery retrieves ContentTypes from the database on each call, bypassing the cached copies. We can probably bypass the ContentType lookup entirely and just match on `app_label` and `model` for the content type of the current instance.

> Request should complete within a couple of seconds.

That's not probably not a fair expectation when deleting thousands of objects, considering that at a _minimum_ NetBox is creating a changelog record and executing an individual SQL query for each item as it is deleted. Improving FeatureQuery performance should reduce the time it takes, but I wouldn't expect it to remove a huge portion of the delay, which is attributable to other functions.
