### ISSUE TITLE
Interface types for older devices (10baseT)

### ISSUE THREAD

**Issue by garbled1** [netbox-community/netbox#5318]
### Environment
* Python version: 3.6
* NetBox version: 2.9.8

### Proposed Functionality
Could we have interface types for older style devices?  For example, AUI (10Base-5) or Coax (10Base-2)

10Base-2 (coax)
10Base-T
10Base-5 (AUI)

### Use Case

Ancient devices that are still in use in my homelab have to be lied about with things like 100BaseT when they clearly don't have them.

**Comment by jeremystretch** [comment]
The litmus for adding an interface type in NetBox is that it must be commercially available and in common use. The interface types you've listed have been obsolete for decades and are no longer in common use on production networks, so they don't qualify for inclusion. As for your lab, I suggest using the "other" designation for these.
