### ISSUE TITLE
Update installation documentation for Raspberry Pi deployments.

### ISSUE THREAD

**Issue by BCurrell** [netbox-community/netbox#5320]
### Change Type
[x] Addition
[ ] Correction
[ ] Deprecation
[ ] Cleanup (formatting, typos, etc.)

### Area
[x] Installation instructions
[ ] Configuration parameters
[ ] Functionality/features
[ ] REST API
[ ] Administration/development
[ ] Other

### Proposed Changes

Whilst setting up Netbox on a Raspberry Pi for testing, I was running into an issue during the database migration part of upgrade.sh:

```none
Applying database migrations (python3 netbox/manage.py migrate)...
SystemCheckError: System check identified some issues:

ERRORS:
dcim.DeviceType.front_image: (fields.E210) Cannot use ImageField because Pillow is not installed.
        HINT: Get Pillow at https://pypi.org/project/Pillow/ or run command "python -m pip install Pillow".
dcim.DeviceType.rear_image: (fields.E210) Cannot use ImageField because Pillow is not installed.
        HINT: Get Pillow at https://pypi.org/project/Pillow/ or run command "python -m pip install Pillow".
extras.ImageAttachment.image: (fields.E210) Cannot use ImageField because Pillow is not installed.
        HINT: Get Pillow at https://pypi.org/project/Pillow/ or run command "python -m pip install Pillow".
```

I confirmed Pillow was installed, but it still wasn't liking it. It turns out that if you install Pillow on a Raspberry Pi (which is from piwheels, not pypi), there are a couple more system dependencies required.

```none
sudo apt install libjbig0 liblcms2-2 libopenjp2-7 libtiff5 libwebp6 libwebpdemux2 libwebpmux3
```

Source:  [https://www.piwheels.org/project/pillow/](https://www.piwheels.org/project/pillow/)

I couldn't find any reference to this when googling around, so I'm not sure if its a rare issue, or people don't tend to deploy Netbox to a Raspberry Pi.

If you're happy with my suggestion, I'll be glad to submit a PR with the changes.

**Comment by BCurrell** [comment]
It looks like there was at least 2 references to this issue actually:

https://www.reddit.com/r/sysadmin/comments/evbpew/netbox_on_raspberry_pi_4/

https://www.techcoil.com/blog/how-to-setup-python-imaging-library-pillow-on-raspbian-stretch-lite-for-processing-images-on-your-raspberry-pi/

I would've seen this earlier but Reddit was down. Whoops.

**Comment by jeremystretch** [comment]
This would not belong in NetBox's documentation because the issue at hand appears to be specific to the Raspberry Pi platform and would affect _any_ Python application which requires the Pillow library, not just NetBox.
