### ISSUE TITLE
SECRET_KEY Addition

### ISSUE THREAD

**Issue by dineshkumarpalanivelu** [netbox-community/netbox#5323]
### Change Type
Addition

### Area
Installation instructions

### Proposed Changes

1) Please mention the point that SECRET_KEY can be generated by running " python3 ../generate_secret_key.py "
2) Then the generated key need to be added(copy and paste) in "configuration.py" file in "SECRET_KEY='  '" line.

**Comment by candlerb** [comment]
Do you mean like here? https://netbox.readthedocs.io/en/stable/installation/3-netbox/#secret_key

This was documented in [June 2016](https://github.com/netbox-community/netbox/commit/df55ec0114416ece684b872d11c08ac80d67dba7).

**Comment by jeremystretch** [comment]
As @candlerb points out both points above are already clearly documented.
