### ISSUE TITLE
Plugin template extensions missing from VM interface view

### ISSUE THREAD

**Issue by minitriga** [netbox-community/netbox#5324]
I'm currently writing netbox_graphs for the inevitable removal of graphs in `2.10` I have graphs functioning in Sites, Devices and Providers to keep the existing functionality of the current graph implementation but some templates do not support plugin buttons. 

### Environment
* Python version:  Python 3.7.7
* NetBox version: v2.9.7

### Steps to Reproduce
1. Create template_content.py and add the following:
```python
## Does not work needs fixing
class VirtualizationVMIntfGraphButton(PluginTemplateExtension):
    model = 'virtualization.vminterface'

    def buttons(self):
        return button_template(self)

## Does not work needs fixing
class IntfGraphButton(PluginTemplateExtension):
    model = 'dcim.interface'

    def button(self):
        return button_template(self)

template_extensions = [VirtualizationVMIntfGraphButton, IntfGraphButton]
```
2. Buttons do not load due to `vminterface.html` and `interface.html` not containing plugin buttons.

### Expected Behavior
Expected buttons to load. 

### Observed Behavior
No buttons are loaded.

**Comment by minitriga** [comment]
#4349

**Comment by jeremystretch** [comment]
Looks like the `vminterface.html` template never had the `plugin_*` template tags added to it for some reason.

```
## Does not work needs fixing
class IntfGraphButton(PluginTemplateExtension):
    model = 'dcim.interface'

    def button(self):
        return button_template(self)
```

`def button()` should be `def buttons()`, plural. Correcting this will render the content as expected.
