### ISSUE TITLE
Let's Encrypt not playing nicely with nginx

### ISSUE THREAD

**Issue by garber-001** [netbox-community/netbox#5330]
### Change Type
[X] Addition
[ ] Correction
[ ] Deprecation
[ ] Cleanup (formatting, typos, etc.)

### Area
[X] Installation instructions
[ ] Configuration parameters
[ ] Functionality/features
[ ] REST  #API
[ ] Administration/development
[ ] Other

### Proposed Changes
Add Let's Encrypt Instructions to HTTP Server Documentation
#5329

**Comment by jeremystretch** [comment]
Let's Encrypt publishes their own [very thorough documentation](https://letsencrypt.org/docs/), which we reference in the installation instructions. It would be redundant for NetBox to duplicate it as there is nothing about the process that's specifically relevant to NetBox.
