### ISSUE TITLE
About Import Icon and Export Icon

### ISSUE THREAD

**Issue by liaocyintl** [netbox-community/netbox#5336]
### Environment
* Python version: 3.6.8
* NetBox version: 2.9.7

### Proposed Functionality
Hi Team, 
I'm not sure it is an issue or not.
I propose the 'Import' button and the 'Export' button on each page, such as /dcim/sites/, the icon of the import button should be 'upload' and the icon of the export button should be 'download'.
But now, there is just the reverse.
Isn't it?

![image](https://user-images.githubusercontent.com/10112615/98755188-6d2f7900-240b-11eb-8fcf-ab7b8359726c.png)

![image](https://user-images.githubusercontent.com/10112615/98755219-80424900-240b-11eb-8f3d-aa81ac454256.png)

Thank you.

### Use Case
NO

### Database Changes
NO

### External Dependencies
NO

**Comment by jeremystretch** [comment]
All of the icons have been changed for the upcoming v2.10 anyway; see #2755.
