### ISSUE TITLE
Add "splice" type for rear ports

### ISSUE THREAD

**Issue by JonathonReinhart** [netbox-community/netbox#5337]
Thanks a lot for building such an awesome tool! This is a minor request.

### Environment
* Python version: v3.? (netbox-docker)
* NetBox version: v2.9.8

### Proposed Functionality
For rear (or front, I suppose) ports, please consider adding a `Splice` Type under `Fiber Optic`.

When modeling a typical enterprise copper cable plant, we have patch panels with 8P8C front ports and 110 punch rear ports. This accurately matches the real world.

But fiber patch panels are often installed by splicing the cable run to the back of an e.g. LC connector.

There is no `Splice` type connector. I'm forced to pick one (e.g. LC), which doesn't reflect the real world. It's not a big deal to work around, but it seems like it wouldn't be too much work to add another type either.

### Use Case
When modeling fiber cable plants, there will often be splices.

Consider the most simple case:
- Rack 1
  - Fiber patch panel 1.1
    - Front port 1: LC connector
    - Rear port 1: Splice
- Rack 2
  - Fiber patch panel 2.1
    - Front port 1: LC connector
    - Rear port 1: Splice

The two "splice" rear ports would be connected together.

### Database Changes
No new models or fields required.

- Add new port type [here](https://github.com/netbox-community/netbox/blob/8ba50d0cf2eeb04ba3cc8b800a142b4bd06c6858/netbox/dcim/choices.py#L816-L832)
- Add new choice [here](https://github.com/netbox-community/netbox/blob/8ba50d0cf2eeb04ba3cc8b800a142b4bd06c6858/netbox/dcim/choices.py#L848-L860)
- May need to augment [this migration](https://github.com/netbox-community/netbox/blob/3eb2d45e8deedfc71cfba9a3c2f919df760b6dca/netbox/dcim/migrations/0082_3569_port_fields.py)

### External Dependencies
n/a

**Comment by jeremystretch** [comment]
> May need to augment this migration

FYI this isn't necessary: The migration only deals with types that existed before the migration was written.
