### ISSUE TITLE
Static Media Failure

### ISSUE THREAD

**Issue by abrand67** [netbox-community/netbox#5339]
### Environment
* Python version: 3.6.8
* NetBox version: 2.9.9

### Steps to Reproduce
1. Install minimal server CentOS 8
2. Upgrade all packages to current
3. Install Netbox per https://netbox.readthedocs.io/en/stable/installation/ using git
4. Install Nginx 

### Expected Behavior
I expected Netbox to work

### Observed Behavior
No errors were encountered during the install.  Using the gunicorn server Netbox loads.  Trying to launch it using NginX I get the following:
Static Media Failure
The following static media file failed to load: bootstrap-3.4.1-dist/css/bootstrap.min.css
Check the following:

manage.py collectstatic was run during the most recent upgrade. This installs the most recent iteration of each static file into the static root path.
The HTTP service (e.g. nginx or Apache) is configured to serve files from the STATIC_ROOT path. Refer to the installation documentation for further guidance.
STATIC_ROOT: /opt/netbox/netbox/static
STATIC_URL: /static/
The file bootstrap-3.4.1-dist/css/bootstrap.min.css exists in the static root directory and is readable by the HTTP process.
Click here to attempt loading NetBox again.

**Comment by jeremystretch** [comment]
Thank you for your interest in NetBox. GitHub issues are intended for reporting reproducible bugs and requesting features, and must be submitted using one of the templates provided [here](https://github.com/netbox-community/netbox/issues/new/choose). For general discussion, questions, or assistance with installation issues, please post to our [mailing list](https://groups.google.com/forum/#!forum/netbox-discuss) instead.

**Comment by abrand67** [comment]
Why did you close this?   I did use the bug template at the location you sited.

**Comment by jeremystretch** [comment]
> For general discussion, questions, or assistance with installation issues, please post to our mailing list instead.
