### ISSUE TITLE
Add parent and child prefixes to API response

### ISSUE THREAD

**Issue by soer7022** [netbox-community/netbox#5340]
### Proposed Functionality
Make the api call /api/ipam/prefixes/ID return the parent and child prefixes for the prefix.

### Use Case
It is currently rendered on the page for the prefix but not in the API, it would be really helpful to be able to make a tree based on these prefixes. Also for use cases where we are only interested in very general or very specific prefixes. For example I would want to get all prefixes with no parents to get the large prefixes.

### Database Changes
This should already be available in the database since it can be displayed on the web version of netbox.

### External Dependencies
None that I'm aware of

**Comment by jeremystretch** [comment]
That would impose an unreasonable degree of overhead to include information that very often isn't needed. Instead, you can simply make two API calls: One to retrieve the prefix, and the second (if needed) to retrieve its children.

**Comment by soer7022** [comment]
> That would impose an unreasonable degree of overhead to include information that very often isn't needed. Instead, you can simply make two API calls: One to retrieve the prefix, and the second (if needed) to retrieve its children.

The main problem is that I can only receive children, not parents. Thus I am unable to find the root of my tree.

**Comment by jeremystretch** [comment]
The `contains` filter is provided for this reason. Please see the REST API documentation for details.

**Comment by soer7022** [comment]
> The `contains` filter is provided for this reason. Please see the REST API documentation for details.

This filter is completely infeasible for cleaning an export of 1600 prefixes.
An example could be:

- Get all prefixes, save these in a set or list
- Find a top level prefix for one of these prefixes
- Remove all the prefixes that share this parent

This is (as far as I can see) not possible with the current api. Without calling contains on all prefixes and removing them if they have a parent.

If this is possible, please enlighten me.

P.S sorry for turning this in to tech support thursday...

**Comment by jeremystretch** [comment]
Please post to the mailing list if you need further assistance.
