### ISSUE TITLE
Support custom fields in user table configuration 

### ISSUE THREAD

**Issue by ypid** [netbox-community/netbox#5344]
### Environment
* Python version: 3.7.3
* NetBox version: 2.9.9 and [develop-2.10](https://github.com/netbox-community/netbox/commit/f3f3993963bac7104edc51bd777887462e7dd5af)

### Proposed Functionality

Support custom fields to be included in list views by making them user configurable (table configuration).

### Use Case

A custom field might be important enough to see it in various list views. This is important to be able to compare it with other objects of the same model. Also, when doing quality assurance, one might want to sort on custom field and then use the bulk edit to normalize the values.

This has been reported before but got closed:

* #492 which is related but did not cover this feature in its initial request, but later in the discussion. Seems it has been overlooked when it got closed.
* #2028 and #2460 asked exactly the same but got closed by #492.
* #1997 Was not clear if #492 was meant.

Cc: @eloquentheit, @sampl3x, @mryauch, @hanej, @lesinigo, @Grokzen, 

### Database Changes

I assume not now that #4878 is done.

### External Dependencies

None.

**Comment by jeremystretch** [comment]
FYI this needs to wait until v2.10 has been released (because of the changes in #4878). @ypid would you like to volunteer to take on this work once is can begin?

**Comment by ypid** [comment]
Count me in :) You can assign me to this issue. I am already watching for new releases and am going to pick this issue up once 2.10 drops. Keep up the awesome work!

**Comment by jeremystretch** [comment]
Cool. Marking this as blocked for now pending the v2.10 release.

**Comment by jeremystretch** [comment]
@TomGrozev would you like to take ownership of this issue so that your PR can be reviewed?

**Comment by TomGrozev** [comment]
@jeremystretch Sure.

**Comment by hyudra** [comment]
May I ask that, will this feature be one of v2.11 milestone?

**Comment by jeremystretch** [comment]
Yes, this has been implemented for v2.11.
