### ISSUE TITLE
How add a new section in NETBOX  I want to create spare devices ! how can I do that ?

### ISSUE THREAD

**Issue by SATadsl** [netbox-community/netbox#5346]
### Environment
Python version: v3.6.8
NetBox version: v2.9.8

**Comment by jeremystretch** [comment]
Thank you for your interest in NetBox. GitHub issues are intended for reporting reproducible bugs and requesting features, and must be submitted using one of the templates provided [here](https://github.com/netbox-community/netbox/issues/new/choose). For general discussion, questions, or assistance with installation issues, please post to our [mailing list](https://groups.google.com/forum/#!forum/netbox-discuss) instead.
