### ISSUE TITLE
Allow planned migration for devices

### ISSUE THREAD

**Issue by Eldiabolo21** [netbox-community/netbox#5348]
### Environment
* Python version: 3.?
* NetBox version: v2.8.6

### Proposed Functionality
For a device it should be possible to migrate it in a planned state. Meaning, i can chose to move a device to a new position with its current values, but I should be able to modify interfaces, connections, and IP-address assignments, without already removing it from its current position with its current values for interfaces, connections, and IP-address assignments. At one point I would like to be able to apply the migration, meaning the device would be removed from the old location and the new location is then current location. 

### Use Case
We recently migrated a couple of servers from on DC to another. They stay pretty much the same, just needed to get somewhere else. I would have liked to kept the same device across the DCs but unfortunately this was not possible. For our use case we have to have a device in Netbox before hand, so our Switches can deploy the right Network-config as well as labels need to be printed so the precabeling can be done. 
As a workaround we created a new device with the same settings as the old device, did the changes to interfaces, cabeling, etc, did the migration and then removed the old device. 

### Database Changes
i can't comment on that, as i'm not a developer

### External Dependencies
i can't comment on that either, as i'm not a developer

**Comment by jeremystretch** [comment]
What you're describing would take a huge amount of effort to implement reliably, while not providing significant benefit. The recommended approach in NetBox (and, I'd imagine, most similar tools), is to simply duplicate the device being moved in its new position. Is there a specific limitation you're running into?

**Comment by Eldiabolo21** [comment]
Okay, wasnt sure how big of a deal it would be. 
the workaround you suggested is actually what what we ended up doing. The downside is, that I will lose all the history of the device and most imporantly, errors happening when creating the device again and manually copying over information. Though now that I write that, I guess I could write a script to duplicate a device more safely

**Comment by jeremystretch** [comment]
You could also just delete the placeholder device and move the original one when the time comes.
