### ISSUE TITLE
Racks list not filtered by selected group when creating a rack reservation

### ISSUE THREAD

**Issue by jeremystretch** [netbox-community/netbox#5350]
### Environment
* Python version: 3.6.9
* NetBox version: 2.9.9

### Steps to Reproduce
1. Create at least one rack with a rack group and one not, both within the same site
2. Open the form to create a rack reservation
3. Select the site and rack group
4. Inspect the list of available racks

### Expected Behavior
The list should display only racks within the selected group.

### Observed Behavior
All racks within the site are displayed.

**Comment by DavidLiedke** [comment]
With Version 2.9.9 all works fine. 

Thank you.
