### ISSUE TITLE
Restore API ability to query all choices via a client without write permissions

### ISSUE THREAD

**Issue by ajknv** [netbox-community/netbox#5352]
### Environment
* Python version: 3.6.8
* NetBox version: 2.9.9

### Proposed Functionality
The API should expose endpoints that are fully functionally equivalent to the old "_choices" endpoints, in that they will return all of the available choices even when queried by a read-only client. The deprecation of the "_choices" endpoints was motivated by the purported claim that the OPTIONS queries could substitute for the existing behavior (https://github.com/netbox-community/netbox/issues/3416), however this is not true given that OPTIONS requests do not return valid information to clients without write permissions.

The simplest approach to addressing this situation therefore is of course to simply resurrect the _choices endpoints. [issues/5351](https://blog.codinghorror.com/thats-not-a-bug-its-a-feature-request/) If there are reasons why that is not preferred, a suggested alternative is to provide endpoints for the choice types that support GET requests and return responses equivalent to what _choices requests previously returned, as an example:

GET https:///api/dcim/cables/status"

### Use Case

Clients implement abstraction wrappers that query for choices and encapsulate them in symbolic references. Those enum-reference objects can then internally handle mapping to actual choice values in later API queries (including as filters in read-only GET queries) or to do things like filter client-side on result sets. This avoids the need to spread constants around in client-side code, and/or maintain manual encodings inside code of all known choices -- which might change on upgrades to Netbox -- or to compromise security posture by giving clients write permissions that aren't otherwise needed.

### Database Changes
None.

### External Dependencies
None.

**Comment by sdktr** [comment]
Would allowing OPTION queries for read only clients suffice? (I'm blindly assuming that a user needs write access for this ATM, as you're stating)

**Comment by ajknv** [comment]
Technically the OPTION queries are "allowed" to a read-only client, it's just that they don't return any information about the choices in the response payload -- namely the choices information is only made available under an ["actions"]["POST"] subkey, and that action, and thus key, is omitted for a read-only client. BTW -- I know this from direct comparison of requests using tokens for a read-only user vs a write-enabled user.

So if the choices information could be allowed (in the sense of made available) via response content delivered under a different subkey -- the obvious candidate would be ["actions"]["GET"] -- then yes that would solve the problem. The output of the queries using a read-only token (which contain no "actions" subkeys) suggest that such a key doesn't even theoretically exist, though.

**Comment by jeremystretch** [comment]
An `OPTIONS` request returns the specific actions permissible for the authenticated client. For example, it would return `PATCH` but not `POST` if the current user has permission to modify but not create records. This is valuable information for the API client, so the existing behavior must remain intact.

**Comment by candlerb** [comment]
On a system that permits read-only access to unauthenticated users, it does seem odd that:

1. `curl localhost/api/dcim/interfaces/` returns all the interfaces
2. `curl -XOPTIONS localhost/api/dcim/interfaces/` _doesn't_ return the choices data:

    ```
    {"name":"Interface","description":"","renders":["application/json","text/html"],"parses":["application/json","application/x-www-form-urlencoded","multipart/form-data"]}
    ```

    To see the available interface choices, I have to provide a valid AP token.

It's odd because case (1) is the "valuable" data, which I'm happy not to restrict.  The choices (2) are nothing more than generic information that I could get from *any* Netbox installation, or the source code, and yet they are restricted.

**Comment by jeremystretch** [comment]
> To see the available interface choices, I have to provide a valid API token.

Right, because an unauthenticated user has no ability to write to this (or any) field, and thus has no choices: By design, an unauthenticated user cannot be permitted to make changes. Again, the API is informing the user of his options.

> The choices (2) are nothing more than generic information that I could get from any Netbox installation, or the source code, and yet they are restricted.

You can, but attempting to write them to a field will obviously fail.

Here's an example that might help clarify the constraint: Suppose a user has permission to create interfaces, but only with Ethernet types (by leveraging the object-based permissions introduce in v2.9). It would be helpful if an `OPTIONS` request initiated by that user returned _only_ the permitted types. By contrast, a user without this restriction would see _all_ possible types. (This doesn't currently work, unfortunately, but it might be worth tackling.)

**Comment by candlerb** [comment]
My use case is: "As a developer, or as someone preparing a CSV file to be uploaded, I want to refer to documentation with a list of permitted interface types".

I can see all the API documentation under `/api/docs/`, but I can't see the allowed constants for the API unless I first authenticate to it.

**Comment by candlerb** [comment]
Update: when logged into the GUI, I do indeed see the Enum choices.

![image](https://user-images.githubusercontent.com/44789/100624821-c0665e80-331b-11eb-9f18-77fde1279795.png)

But this only shows the API values not the descriptions, and unfortunately, CSV upload only works with the descriptions.

**Comment by jeremystretch** [comment]
> My use case is: "As a developer, or as someone preparing a CSV file to be uploaded, I want to refer to documentation with a list of permitted interface types".

That's perfectly valid for justifying some _new_ functionality; e.g. a separate endpoint or other mechanism. I was just explaining why I believe the existing behavior for `OPTIONS` requests should remain intact.

**Comment by candlerb** [comment]
Agreed, and as the OP said, resurrecting the `_choices` endpoint would be one way to do that.

**Comment by jeremystretch** [comment]
Work on #5470 introduced a new [custom MetaData class](https://github.com/netbox-community/netbox/blob/8f4197c0207dd9467dc09b8e89dfcd896b2c8a79/netbox/netbox/api/metadata.py#L11) to support bulk update and delete operations. What we could do is tweak this to check for a specific request parameter (e.g. `?show_all=True` or similar); if present, NetBox would return _all_ supported actions regardless of the user's permissions.
