### ISSUE TITLE
Webhooks issue when modification on multiple sites at the same time

### ISSUE THREAD

**Issue by Yacine8888** [netbox-community/netbox#5357]
### Environment
Docker netbox
* Python version: 2.7.5
* NetBox version: v2.9.9

### Steps to Reproduce
1.  Create a webhook on site object 
2.  Go to the sites page : dcim/sites/ . 
3. Select several sites and click on Edit Selected
4. Do a modification on anything. Then click on apply.
5. Then see the content of the webhook, you will figure only the details of one site is in the webhook.

### Expected Behavior
The details of all updated sites must be in the webhook.

### Observed Behavior
Only the content of one site among many sites updated, is sent in the webhook.

**Comment by jeremystretch** [comment]
A separate webhook is sent for each object being modified. (This behavior was confirmed on v2.9.9.) The receiver must listen for and process each incoming HTTP request.
