### ISSUE TITLE
IP address assignment on Virtual Machine interface not visible in UI

### ISSUE THREAD

**Issue by rodvand** [netbox-community/netbox#5358]
### Environment
* Python version:  3.6.8
* NetBox version: 2.10-beta1

### Steps to Reproduce
1.  Create a virtual machine "Test VM"
2.  Create interface eth0 on the virtual machine
3.  Add an IP address 192.168.1.1/24 to the interface.

### Expected Behavior
Expected to see the IP address under the interface section.

### Observed Behavior
No IP address is seen on the interface. If you mark the address as primary for the device it is shown as a primary IP in the virtual machine section, but is still not seen under the interface section. If you check the IP address itself it is assigned the correct interface on the VM.

**Comment by jeremystretch** [comment]
Thank you for the bug report. It seems that the user configuration button is missing from the VM interfaces table; easy fix. I've also added `ip_addresses` as a default column for the table.
