### ISSUE TITLE
Can't Remove Untagged Vlan from interface with API

### ISSUE THREAD

**Issue by almostbeef** [netbox-community/netbox#5359]
### Environment
* Python version: 2.7.5
* NetBox version: v2.9.7

### Steps to Reproduce
Updating with Ansible uri module:
'''     url: "{{ netbox_url }}/api/dcim/interfaces/{{ INTERFACE.id }}/"
    method: PATCH
    return_content: yes
    status_code: 200
    headers:
      accept: "application/json"
      Authorization: "Token {{ netbox_token }}"
    body:
      device: 10
      name: et-0/0/0
      type: virtual
      untagged_vlan: null
    body_format: json
'''
I have tried several things for the untagged_vlan: null, 0, False all return errors.

### Expected Behavior
Remove the currently configured untagged vlan.

### Observed Behavior
Various errors not allowing untagged_vlan to be removed.

**Comment by jeremystretch** [comment]
Thank you for your interest in NetBox. GitHub issues are intended for reporting reproducible bugs and requesting features, and must be submitted using one of the templates provided [here](https://github.com/netbox-community/netbox/issues/new/choose). For general discussion, questions, or assistance with installation issues, please post to our [mailing list](https://groups.google.com/forum/#!forum/netbox-discuss) instead.

**Comment by almostbeef** [comment]
So I suppose this could be a documentation issue then. I'm not getting any traction on the forum and there is nothing in the docs about what the API expects to remove a field. Is this possible to do?

Thanks,
Austin Lewis
__________________________
Network Systems Specialist
Penn State IT
Data Centers
Office: (814)867-6301
Cell: (814)933-8697

________________________________
