### ISSUE TITLE
Disabling 802.1Q mode on interfaces don't clear untagged vlan assignment

### ISSUE THREAD

**Issue by miaow2** [netbox-community/netbox#5360]
### Environment
* Python version: 3.6.8
* NetBox version: 2.9.4

### Steps to Reproduce
1. set on interface (on device or vm) 802.1Q Mode (any mode) and Untagged VLAN
2. set 802.1Q Mode to None, fields with vlans disapear
3. set any 802.1Q Mode again, field Untagged VLAN will be filled with VLAN from step 1

If you save after step 2, 802.1Q Mode will change, but Untagged VLAN stays on interface.

### Expected Behavior
Untagged VLAN field should be empty

### Observed Behavior
Untagged VLAN field does not clear, with Tagged VLANs field all works fine.

On my enviroment I fix this in file `project-static/js/forms.js` line [351](https://github.com/netbox-community/netbox/blob/develop/netbox/project-static/js/forms.js#L351) by sending empty string to `val()` function. 
```
$('select#id_untagged_vlan').val('');
```
I don't know is this a good solution, so I open this issue

**Comment by jeremystretch** [comment]
[This line](https://github.com/netbox-community/netbox/blob/58668a680754604937bed83591d3505bce7f6da7/netbox/dcim/models/device_components.py#L730) seems to be the problem. Since we moved to slugs for choice fields, the `mode` field now stores an empty string rather than null.
