### ISSUE TITLE
Custom Fields for Device Roles

### ISSUE THREAD

**Issue by shannondstewart** [netbox-community/netbox#5365]
### Environment
* Python version: 
* NetBox version: v2.8.5

### Proposed Functionality
Custom fields for Device Roles

### Use Case
A custom field for a device role could be used to establish standard configuration components for devices based on the role they have in the network. For example, a device might need specific security configurations based on where it sits on the network. A custom field would allow properties like a security score, or a change risk score to be applied to a device via its association with its Device Role.

### Database Changes
Custom Fields in Device Roles

**Comment by jeremystretch** [comment]
When we extend custom fields to additional models, it will be done at broader scale and not on individual models. For instance, we wouldn't enable custom fields on only device roles, but on _all_ organizational models. However, that won't happen until v2.11 at the earliest.

I've opened #5370 to track this work. Going to close out this issue as the model-specific FR is redundant.
