### ISSUE TITLE
Allow filtering VLANs list by minimum/maximum VLAN ID

### ISSUE THREAD

**Issue by PieterL75** [netbox-community/netbox#5367]
### Environment
* Python version: 
* NetBox version: v2.9.9

### Proposed Functionality
I would like to be able to search for a 'range of' vlans.
example : 3000-3500 or 3[0-5]00
and then see what vlans are in use/available in that range.

### Use Case
Our VLANs are 'logically' split up in different purposes (ex: 1-10: reserved; 10-999: Infra; 1000-2000: customers; 3000-3500: storage)
When provisioning VLANs, the new vlan has to come out of that range, and not the first available.

**Comment by jeremystretch** [comment]
This is already possible using the `vid__gte` and `vid__lte` filters. For example, `GET /api/ipam/vlans/?vid__gte=3000&vid__lte=3500` will return VLANs with a VID of 3000-3500, inclusive.

**Comment by PieterL75** [comment]
I see that is an inherited functionality from the django enabled queries..
Good to see that it is possible in the API.

Should it be possible to extend the GUI also with this functionality ? I rather think of regex-like filters.

**Comment by jeremystretch** [comment]
Regex is not ideal for bounding numerical ranges. What if I want to show VLANs 123 through 456? Discrete min/max values are much easier to work with.

**Comment by jeremystretch** [comment]
I'll mark this as `needs owner` in case someone would like to take on the work of adding less than/greater than filter widgets to the VLAN list view. However, the scope of this issue should not be construed to include the introduction of any new filters.
