### ISSUE TITLE
add support to more bond types (not just LACP)

### ISSUE THREAD

**Issue by anubisg1** [netbox-community/netbox#5368]
### Environment
* Python version:  unknown
* NetBox version: 2.8.8

### Proposed Functionality

Today we only support LAG virtual interface and the ability to add physical interfaces to a LAG as members.
This is good for network switches/routers but is not enough for servers.

A server could configure its ports in a bond different than LACP, for example an active/active or active/standby.
Linux supports up to 7 modes, current models only support mode 4 (i.e. LACP)

mode=0 (balance-rr)
mode=1 (active-backup)
mode=2 (balance-xor)
mode=3 (broadcast)
mode=4 (802.3ad)
mode=5 (balance-tlb)
mode=6 (balance-alb)

I'm not saying we need to support all of them, but maybe we can create a "generic bond interface"

### Use Case

Modeling server's connectivity into netbox , connectivity that doesn't fit into LACP bonding.

### Database Changes

add more virtual interface types where a physical interface can belong to.

### External Dependencies

none

**Comment by jeremystretch** [comment]
The LAG interface type does not imply the use of LACP; it is a generic type that merely indicates the bonding of multiple physical groups. NetBox does not model LAG protocols.

**Comment by anubisg1** [comment]
can i at least suggest to rename it then? LAG quiet uniquely identifies Link AGgregaion (lacp or pagp) and it's therefore ambiguous and confusing

**Comment by jeremystretch** [comment]
Again, the term LAG has nothing to do with LACP specifically. I'm not sure where you got that idea.
