### ISSUE TITLE
Add 'created' and 'last_updated' attributes to device component models

### ISSUE THREAD

**Issue by bb-Ricardo** [netbox-community/netbox#5369]
### Environment
* Python version: 3.6.8
* NetBox version: 2.9.9

### Proposed Functionality
Add `created` and `last_updated` attributes to dcim.interface and and virtualization.vminterface model

### Use Case
I use Netbox as source for our monitoring system. There it is important to get interface data for all interfaces of Device/VM. In order to avoid requesting all interfaces of all devices/VMs a caching was implemented to get only interface objects which have changed since last request cycle. This works pretty well for devices, VMs and IP addresses but interfaces don't support these fields. Our NetBox instance contains thousends of interfaces and retreiving them all takes a long time.

This change would speed up the reading of interface data by A LOT.

### Database Changes
Yes. Adding 'created' and 'last_updated' to both models would be necessary.

### External Dependencies
None

### Pull Request
This change would be ready to go: https://github.com/bb-Ricardo/netbox/commit/2b8fce86865f175effefeba16d7a8165f5670adc

**Comment by jeremystretch** [comment]
This change would need to be made for all component models (not just interfaces). I've updated the scope accordingly.

**Comment by bb-Ricardo** [comment]
let me know if I can help with anything.

**Comment by jeremystretch** [comment]
Whoops, looks like this was implemented under #5901.

**Comment by bb-Ricardo** [comment]
Great, thank you very much.

**Comment by bb-Ricardo** [comment]
Well, yes this is implemented for dcim but not for `virtualization`.

Shall I open another issue?
