### ISSUE TITLE
Enable custom fields for organizational models

### ISSUE THREAD

**Issue by jeremystretch** [netbox-community/netbox#5370]
### Environment
* Python version: 3.6.9
* NetBox version: 2.9.9

### Proposed Functionality
Enable support for custom fields on organizational models (e.g. circuit types, rack roles, device roles, VLAN groups, etc.).

### Use Case
Extension of NetBox's custom fields feature has long been demanded by users. Now that custom fields has been reimplemented in a sufficiently performant manner, we can revisit this.

### Database Changes
Add a `custom_field_data` to each applicable model (via subclassing CustomFieldModel).

### External Dependencies
None

**Comment by mngan** [comment]
Can I add a vote for custom fields of `Interfaces` too?

**Comment by jeremystretch** [comment]
@mngan No, that is beyond the scope of this issue.
