### ISSUE TITLE
Remove limitation for circuit connections to interface only

### ISSUE THREAD

**Issue by balkandude** [netbox-community/netbox#5371]
### Environment
* Python version: 3.6.9
* NetBox version: 2.9.4

### Proposed Functionality
Allow for connections of circuits to devices with front/rear ports where rear port is connected to another device with front/rear ports.
> circuit 1 - front port 1 - device A - rear port - rear port - device B - front port 1 - circuit 2

### Use Case
We provide circuits to customers in different sites.  Each site has device with front and rear ports. Sites are interconnected via rear port. Devices are CWDM filters. Customers are buying wavelengths as needed.

When at Site A we provide circuit to customer with side A termintated to a front port of device A.
When at Site B we provide circuit to customer with side A terminated to a front port of device B

### Database Changes
Not sure

### External Dependencies
None

**Comment by jeremystretch** [comment]
The cable tracing logic and validation have been completely overhauled for v2.10 (see #4900). This should no longer be an issue once v2.10 is released, but you can try [the beta](https://github.com/netbox-community/netbox/releases/tag/v2.10-beta1) now if you'd like to help test.
