### ISSUE TITLE
Scrollbar in search results when all columns are visible

### ISSUE THREAD

**Issue by PieterL75** [netbox-community/netbox#5373]
### Environment
* Python version: 
* NetBox version: v2.9.9

### Steps to Reproduce
1. go to the vlan overview
2. enable all colums to be visible
3. make sure to have vlan group, sites and tags on the vlans

### Expected Behavior
The search results show all columns, without a scrollbar

### Observed Behavior
The search result is no showing all columns in one view. There is a scrollbar at the bottom

**Comment by jeremystretch** [comment]
This is expected behavior: horizontal scrolling is necessary to fit the entire table.

**Comment by PieterL75** [comment]
Why would you limit the width of the table, if there is a lot more room on the page ? I have over 1/3th of my whitespace on my page... 
Can it be set, that the scrollbar only shows when if there is no more whitespace ?
It hides info that my fellow users of our netbox instance would like to see without scrolling
