### ISSUE TITLE
Console Ports should have Port Speed

### ISSUE THREAD

**Issue by docsteel** [netbox-community/netbox#5375]
### Environment
* Python version: 3.8.5
* NetBox version: 2.9.9

### Proposed Functionality
Console Ports should include Port Speed in Baud:

9600
14400
38600
115200 

### Use Case
Templating and configure automated Console Server Solutions via API.

### Database Changes
Yes

### External Dependencies
Not aware of any external Dependencies.

**Comment by jeremystretch** [comment]
This needs more detail. For example, are you proposing a fixed list of speeds? Or should it be a customizable value? Only console ports, or console server ports as well? Is it to be measured in baud or bits per second? The more detail you provide, the more likely a feature request is to be considered for adoption.

**Comment by docsteel** [comment]
Port Speed should be a Drop-Down Selection Field as fixed List with the  following Values, measured in Baud:
1200
2400
4800
9600
19200
38400
57600
115200

Default Value should be 9600. This list should cover all default Speed Settings for Switches, Routers, Serial Devices, etc.

If it's feasible this should be added for Console Ports and Console Server Ports as well, because both Ports have a Port Speed Setting in the Real World. With this Setting we could automate the Setup of Serial Console Servers in the Datacenter (e.g. Device 1, Port 1 need Speed 9600 for serial Console of APC USV; Device 1, Port 2 needs Port Speed 115200 for Cisco Switch)

**Comment by jeremystretch** [comment]
Those are bps values, [not baud rate](https://www.linuxjournal.com/files/linuxjournal.com/linuxjournal/articles/010/1097/1097s2.html).

>  With this Setting we could automate the Setup of Serial Console Servers in the Datacenter

What about other parameters, such as parity, flow control, or port pinout?

**Comment by docsteel** [comment]
> Those are bps values, [not baud rate](https://www.linuxjournal.com/files/linuxjournal.com/linuxjournal/articles/010/1097/1097s2.html).

Oh sorry, my fault. Yes you're right this should have been bps and not Baud.

> 
> > With this Setting we could automate the Setup of Serial Console Servers in the Datacenter
> 
> What about other parameters, such as parity, flow control, or port pinout?

For our Templates we don't need Parity, flow control or port pinout, only Port Speed.
But for other Users these could be a Feature.
In this Case I would add:
- Parity (N,O,E,M,S Value) see: https://en.wikipedia.org/wiki/Serial_port#Parity
- Flow Control (Hardware, Software Value) as described here: https://en.wikipedia.org/wiki/Serial_port#Flow_control
Fields for Data Bits and Stop Bits are not needed here, because today's Electronic uses 8 Data Bits and 1 Stop Bit for Communication.

Port Pinout has too many values to image this in compact form in the Console Port Form, so i would not add this here.
