### ISSUE TITLE
Add MANIFEST.in mention to plugins development page

### ISSUE THREAD

**Issue by Thetacz** [netbox-community/netbox#5380]
### Change Type
[ ] Addition
[x] Correction
[ ] Deprecation
[ ] Cleanup (formatting, typos, etc.)

### Area
[ ] Installation instructions
[ ] Configuration parameters
[ ] Functionality/features
[ ] REST API
[x] Administration/development
[ ] Other

### Proposed Changes
When using any templates, the static files will not get collected by `setup.py` `find_packages()`. It needs to be told so. There are 2 steps to do it:

1. add `include_package_data=True` to `setup.py` (already done)
2. add `MANIFEST.in` with `include $plugin_name/templates/$plugin_name/*` (proposed change)

As of now there is no mention about the `MANIFEST.in` in the docs page https://netbox.readthedocs.io/en/stable/plugins/development/ so following the tutorial it will never work with any static files.

The proposal is to add `MANIFEST.in` to Plugin structure section with similar explanations as `setup.py`.

**Comment by jeremystretch** [comment]
The plugins development documentation serves only to document the NetBox plugins API. The packaging and publishing a plugin is not significantly different than any other Python project, and the best practices for doing so are already well-documented in many other places.
