### ISSUE TITLE
interface range naming cisco devices

### ISSUE THREAD

**Issue by oldshield** [netbox-community/netbox#5386]
### Environment
* Python version: 3.6
* NetBox version: 2.9

### Proposed Functionality
When creating interfaces on a cisco switch and doing a range, you seem to only be able to create like gig[1-48]
most of my devices have 3 places for chassis switches and even some routers have multiple x/x/x for interfaces.

ie a 6500 switch stand alone would have a convention gig 1/2  for module 1 port 2, if it were in a vss config it would have 3 places  1/1/2  switch 1 module1 port 2.

I even have fex switches which show like this gig 123/0/1  fex# module0  port 1

I would suggest some sort of ability to add interfaces like gig[x/x/1-x/x-48]
I have even tried gigx/x[1-48] and get only one interface pop up.

when i try this it only populated 1 interface in the device type template and then i have to manually edit this so i can then fill in the inteface's x/x before the port 

Maybe i am just doing something wrong. 

### Use Case
any network engineer

### Database Changes
no idea

### External Dependencies

no clue

**Comment by oldshield** [comment]
i figured it out. sorry for the request.

**Comment by jeremystretch** [comment]
For posterity: NetBox allows using multiple ranges; e.g. `ge-0/[0-2]/[0-47]`.
