### ISSUE TITLE
Apply device specific config contexts from config context menu, not device

### ISSUE THREAD

**Issue by ledgley** [netbox-community/netbox#5389]
* Python version: 3.6.8
* NetBox version: 2.9.10

### Proposed Functionality
It could be seen as counter-intuitive to edit devices individually to assign local config contexts. It may be more appropriate to allow the assignment of config contexts to specific devices (or multiple specific devices) via the config context menu/form, by providing a form option for selecting devices or multiple devices.

### Use Case
We have two more more devices that require the same config context, though there are additional devices, that meet all the same config context matching criteria, that do not require/should not have the config context. This means either
a. Configuring the same config context twice, on two+ local config contexts, posing risk for inconsistencies
b. Configuring a config context across a wider scope of devices that actually need it

It would be possible to do this with tags, though with many of the same scenario repeated, the tag scope becomes unwieldy.

### Database Changes
Cannot answer this, as it is beyond my scope of knowledge.

### External Dependencies
None

**Comment by jeremystretch** [comment]
There are two problems with this. First, as soon as you begin to use the `local_context_data` field for non-unique data, you're inviting abuse and chaos. Attempting to determine what data is set on which devices individually is going to be much, much harder to keep up with than using the centralized ConfigContext model. (Indeed, this concern was the primary motivation for introducing the model to begin with.)

Second, you have the practical limitations. Suppose you have two devices, A and B, with the following local context data defined:

```json
{
    "foo": 123
}
```

```json
{
    "foo": 456
}
```

If I were to bulk edit these devices and specify `{"bar": 789}` as the local context data for both, how does NetBox know whether I want to _append_ the new data or _replace_ the existing data?
