### ISSUE TITLE
Question: Do I have to upgrade version by version or can I just upgrade for example from 2.5.3 to 2.9.10?

### ISSUE THREAD

**Issue by synt8x** [netbox-community/netbox#5390]
Question: Do I have to upgrade version by version or can I just upgrade for example from 2.5.3 to 2.9.10?

**Comment by jeremystretch** [comment]
Thank you for your interest in NetBox. GitHub issues are intended for reporting reproducible bugs and requesting features, and must be submitted using one of the templates provided [here](https://github.com/netbox-community/netbox/issues/new/choose). For general discussion, questions, or assistance with installation issues, please post to our [mailing list](https://groups.google.com/forum/#!forum/netbox-discuss) instead.
