### ISSUE TITLE
Cable import for rear ports failing

### ISSUE THREAD

**Issue by elixdreamer** [netbox-community/netbox#5391]
### Environment
* Python version: 
* NetBox version: 84cbad8821ca (v2.9.9)

### Steps to Reproduce
1. adding cables in bulk for Rear Port is failing: used the following template:
```
side_a_device,side_a_type,side_a_name,side_b_device,side_b_type,side_b_name
P8_409-432,Rear port,5,G10_409-423,Rear port,5

```

### Expected Behavior
Cable to be create

### Observed Behavior

```
Enter the list of column headers followed by one line per record to be imported, using commas to separate values. Multi-line data and values containing commas may be wrapped in double quotes.
Row 1 side_a_type: Object not found.
Row 1 side_b_type: Object not found.
Row 1 __all__: Termination A type has not been specified
```

**Comment by jeremystretch** [comment]
`Rear port` is not a valid type: Use `dcim.rearport`.

**Comment by elixdreamer** [comment]
Could we add a help comment to 'side_a_type' that specifies the available options?
Probably other questions will be raised about this to.

**Comment by jeremystretch** [comment]
@elixdreamer please feel free to open a feature request for it.

**Comment by elixdreamer** [comment]
Still encountering the issue with following import:

`side_a_device,side_a_type,side_a_name,side_b_device,side_b_type,side_b_name,status,type
P8_409-432,dcim.rearport,5,G10_409-432,dcim.rearport,5,Connected,CAT6`

Reply is still the same

**Comment by jeremystretch** [comment]
@elixdreamer please update your original post with the _entire_ set of steps that someone else can follow to reproduce the issue, beginning with the creation of all involved objects.

**Comment by elixdreamer** [comment]
Ok, got it solved. it isn't `dcim.rearport` but just `rearport`.
Will open feature request, @jeremystretch
