### ISSUE TITLE
Can I add an incident management  tool to the NetBox ?

### ISSUE THREAD

**Issue by SATadsl** [netbox-community/netbox#5394]
### Environment
* Python version: 
* NetBox version: 

### External Dependencies

Hello ,

Can I add an incident management  tool to the NetBox ?

I can even pay for it please I need your help ?!

Best Regards

**Comment by jeremystretch** [comment]
Thank you for your interest in NetBox. GitHub issues are intended for reporting reproducible bugs and requesting features, and must be submitted using one of the templates provided [here](https://github.com/netbox-community/netbox/issues/new/choose). For general discussion, questions, or assistance with installation issues, please post to our [mailing list](https://groups.google.com/forum/#!forum/netbox-discuss) instead.
