### ISSUE TITLE
Cable Bulk Import additional info

### ISSUE THREAD

**Issue by elixdreamer** [netbox-community/netbox#5399]
### Environment
* NetBox version: v2.9.9

### Proposed Functionality
Add some additional info to the CSV Field Options for side_a_type and side_b_type.
The info will include all possible ports that can be used to import Bulk cables.
After some digging in the code I found the following list, not sure if it is complete.
`'consoleport', 'consoleserverport', 'interface', 'frontport', 'rearport', 'circuittermination'`

### Use Case
In a bulk cable import that was meant for Rear to rear ports I was unable to find the correct type that need to be used.
after creating a case it came to my knowledge that i had to use `rearport` iso `Rear Port` or `dcim.rearport`.
Probably some confusion could be for other interfaces. I have seen multiple issue reported the `interface` should be set with lower i.

**Comment by jeremystretch** [comment]
This will be added in v2.10.
