### ISSUE TITLE
Custom field support for device components

### ISSUE THREAD

**Issue by mngan** [netbox-community/netbox#5401]
### Environment
* Python version: 3.8.5
* NetBox version: 2.9.9

### Proposed Functionality
Add support for custom fields for Interfaces

### Use Case
I would like to record ESI's for LAG bundles and also external id's to link to `port` objects in our existing DCIM. 

### Database Changes

Adding CustomFieldModel to the Interface/BaseInterface object hierarchy will result in schema changes, and possibly require refactoring if performance is an issue. 

### External Dependencies

None

**Comment by jeremystretch** [comment]
I've tweaked the scope of this to include all device components.

**Comment by candlerb** [comment]
Link to #1254 #2281 #2510 #2789
