### ISSUE TITLE
New Virtual Interface Type - Bridge

### ISSUE THREAD

**Issue by adamboutcher** [netbox-community/netbox#5402]
### Environment
* Python version: 3.6.8
* NetBox version: 2.9.8

### Proposed Functionality
Can we add Bridge as an Interface type that allows parent/child on interfaces.

### Use Case
Would help document virtual bridges much like LAGs.
Would need to accept LAGS to be a child of a BRIDGE.

**Comment by MajesticFalcon** [comment]
Are you creating a software bridge inside of a router? Is it a VLAN aware bridge? If so, would just assigning the vlan memberships be enough to show correlation between ports?

**Comment by adamboutcher** [comment]
It's simply a bridge inside a linux router (eg vmbr0).

Our usecase is that we bond multiple interfaces and then add that bond to a bridge.

eth[0-1] -> bond0 -> vmbr0

**Comment by jeremystretch** [comment]
What would be the practical difference between a "virtual" interface and a "bridge" interface?

**Comment by adamboutcher** [comment]
Nothing if you could parent/child a virtual interface.

LAG can only be a parent. 
Interfaces can only be children. 

If you could make a LAG a child to a Virtual Interface then that would work.

A change to the whole parent/child of interfaces and lags to be less strict would allow for more accurate documentation.

I merely suggested bridge as my use case and kept with the current more strict existing code.

**Comment by jeremystretch** [comment]
Would #1519 address this?

**Comment by adamboutcher** [comment]
Similar but not exact.
The work done for that issue could be applied here though, as long as you can make a LAG a child to a Virtual Interface.

**Comment by BarbarossaTM** [comment]
It would be **really** cool to have an interface type bridge similar to the LAG type so you can set other interface to be part of this bridge. With the already existing functionality of `.1q` settings on interfaces it would thereby even be possible to model vlan-aware-bridges.

**Comment by BarbarossaTM** [comment]
This still would be a really really helpful for modelling network on virtualization hosts and routers <3

**Comment by blazej-czuk** [comment]
> What would be the practical difference between a "virtual" interface and a "bridge" interface?

![image](https://user-images.githubusercontent.com/71962806/110114337-c05f7a00-7db4-11eb-9568-ff312af1557a.png)
![image](https://user-images.githubusercontent.com/71962806/110114580-2b10b580-7db5-11eb-8df4-991a393912d2.png)

**Comment by jeremystretch** [comment]
NetBox v2.11 introduces parent interface assignments (see #1519), which seems like it addresses most of the desired functionality discussed here. I'm going to close this issue out, **however** if there's still a particular feature you believe is _not_ addressed under #1519, I encourage you to open a new feature request (with a detailed description and use case) considering the newly introduced support for parent interfaces.
