### ISSUE TITLE
Add last updated user attribute to models

### ISSUE THREAD

**Issue by imransobir** [netbox-community/netbox#5406]
### Environment
* Python version: 3.6.12
* NetBox version: 2.9.8

### Proposed Functionality
Add last updated user attribute to site, device and other models.

### Use Case
We use NetBox as a data source for a larger system which needs to show last updated user for each model. I understand that this could be achieved by searching through the change log, but the change log can get cleaned up.

### Database Changes
Add last_updated_by field to models.

### External Dependencies
None

**Comment by jeremystretch** [comment]
Implementing this might be more difficult than it seems at first. Assigning a user to the object requires a request context, which is present only with normal UI/API requests. Modifications to an object don't include a user context by default (although it is possible to provide one). Change logging avoids this problem by creating a new record only when the change logging middleware is active, but updating a field on the instance itself is tricky.

Imagine a scenario where user A has modified an object. The object is saved with `last_updated` recording the current time and `last_updated_by` pointing to user A. Now suppose user B modifies and saves the object directly through the NetBox shell. The `last_updated` field will be updated to reflect the most recent change automatically, but the `last_updated_by` field will still point to user A (unless user B had enabled the change logging middleware or set the field manually). This makes it appear as though user A was the last person to modify the object.

I can think of one partial safeguard: If we check whether `last_updated_by` has been set on the instance when `save()` is called, and nullify the field if not, that should avoid reflecting a misattributed change. Though I'm not sure what potential caveats I might be overlooking.

**Comment by imransobir** [comment]
Jeremy,

It is acceptable that the last updated user be updated only through UI/API since all of the requests will be coming through those. Also in our case at least those who have access to NetBox shell already have access to the database directly anyway.

Appreciate if this feature could be implemented even if only for UI/API requests.

**Comment by jeremystretch** [comment]
It may be acceptable to you, but that doesn't mean it's the right choice for everyone who uses NetBox. Many people would understandably be opposed to such behavior, which is why a robust solution would need to be identified in order for the proposed feature to be identified.
