### ISSUE TITLE
Cable type request: LC Simplex

### ISSUE THREAD

**Issue by Infiniverse** [netbox-community/netbox#5409]
### Environment
* NetBox version: v2.9.9

### Proposed Functionality
We have a mix of LC Simplex and LC Duplex cables. Netbox 2.9.9 only supports 'LC' as a port type, but does not distinguish between a single/simplex port LC, or a double/duplex port LC.

### Use Case

Bi-directional optics are now very common, and in networks that use lots of them (FTTP for example) we tend to number ports individually (Simplex) instead of by pair (Duplex). That means that we have a mix of ports that are single port ports, and double port ports. Network doesn't allow us to formally record this distinction. If we use 'LC' as a port type we cannot immedaitely tell whether it's a single cable or a double cable connection.

By allowing a port type to be specified as Simplex or Duplex on fibre connectors (LC) it would greatly aid our ability to formally document the network.

**Comment by jeremystretch** [comment]
This issue is pending closure as it does not conform to one of the [provided templates](https://github.com/netbox-community/netbox/issues/new/choose) as required by the [contributing guide](https://github.com/netbox-community/netbox/blob/master/CONTRIBUTING.md). If you'd like to request that your issue be re-opened, please first update the content so that it matches the appropriate template (this may require rewriting your issue entirely).

**Comment by jeremystretch** [comment]
> Netbox 2.9.9 only supports 'LC' as a port type, but does not distinguish between a single/simplex port LC, or a double/duplex port LC.

The cable media (e.g. OM3 or OS1) is defined independently from the termination type at either end. It would seem more accurate to clarify the cable media as simplex rather than that the termination IMO.

**Comment by Infiniverse** [comment]
We have a mix of simplex and duplex circuits terminating on patch panels. We need to account for all the fibres individually from the rear or the patch panel. All the front ports are labelled individually and interfaces are connected simplex with a single patch cable or duplex with two patch cables.

I am struggling to see how to document this effectively. We definitely have a difference between LC simplex and duplex connections between equipment and patch panels.

Without some distinction to model this we will end up with irregular patch panel models where we need to combine pairs of ports onto single ports with duplex labelling (1/2) along side simplex labelling (3) and (4). This means that a N port patch panel needs to be documented irregularly as a less than N port device. This irregularity makes it much harder to orchestrate against and keep in sync with other databases.

What do you recommend?

**Comment by bryanward-net** [comment]
I also ran into trouble trying to document my fiber plant this way.  I treat all my fiber plant as single strands, but then often use 2 strands to connect devices.  This is getting worse as we now spread out into MPO8 and MPO12 connections for higher speed links.  There was no clean way to bundle multiple fibers into one single "connector".  This concept of bundling should expand beyond just simplex/duplex and allow for individual strands of fiber to be patched ad-hoc at each device (I may have 8 fibers coming in from an MPO8 on a switch to a patch panel, then on the remote patch panel, break that out into 4x duplex connections).  I'd love to model this in netbox, but was unable to find a way and have fallen back to spreadsheets :( with the eventual thought of standing up a separate database to track our fiber plant.

**Comment by DanSheps** [comment]
I think rather then using simplex/duplex it would make more sense to add in a model to permit connecting multiple front ports to a single interface.

**Comment by BarbarossaTM** [comment]
Being able to connect simplex fiber would be helpful indeed.

This seems to be related to #5798

**Comment by gdelanoe** [comment]
I agree with you guys. At work we have the exact same issue : we have a lot of devices connected using bidirectionnal modules (only one fiber) and we can't represent these in Netbox.

Very painful problem for us.

**Comment by jeremystretch** [comment]
> we have a lot of devices connected using bidirectionnal modules (only one fiber) and we can't represent these in Netbox.

You can absolutely model these in NetBox today.

**Comment by jeremystretch** [comment]
> ### Proposed Functionality
> We have a mix of LC Simplex and LC Duplex cables. Netbox 2.9.9 only supports 'LC' as a port type, but does not distinguish between a single/simplex port LC, or a double/duplex port LC.

I'm going to close this issue as it does not convey a specific proposed change and the discussion has not yielded anything that we can act on as developers. People are welcome to submit a new feature request citing _exactly_ what interface/port/cable types they would like to see added, and any related changes that are necessary to support these.
