### ISSUE TITLE
Cable traces do not show cable tags

### ISSUE THREAD

**Issue by Infiniverse** [netbox-community/netbox#5411]
### Environment
* NetBox version: v2.9.9

### Proposed Functionality

The cable trace shows ports and their connecting cables.
The cables tags are not reported.
Cable tags contain very useful data which should be visible in the cable trace.

### Use Case

When looking at a trace between two interfaces it is very useful for the user to see that some of the paths may contain undocumented structure. We signal this by tagging them with #needs-tracing. Other operational and administrative states can also be carried in the cable tags. Having these tags visible on the trace is critically useful.

**Comment by jeremystretch** [comment]
The cable trace display has been redone for the upcoming v2.10 release; we should make sure tags are included there.

**Comment by jeremystretch** [comment]
Added cable tags to the trace view for v2.10.
