### ISSUE TITLE
exception when editing device in chassis bay  v2.10-beta2

### ISSUE THREAD

**Issue by ThomasADavis** [netbox-community/netbox#5417]
### Environment

Python version: 3.6.8
NetBox version: 2.10-beta2

### Steps to Reproduce
1. import from an older version of the db (in this case, it's from v2.8.9)
2. go to an existing chassis type device.
3. try to edit the device in a chassis bay.

### Expected Behavior

takes me to device

### Observed Behavior
an exception appears:

<class 'django.urls.exceptions.NoReverseMatch'>

Reverse for 'device' with keyword arguments '{'pk': ''}' not found. 1 pattern(s) tried: ['dcim\\/devices\\/(?P<pk>[0-9]+)\\/$']

**Comment by jeremystretch** [comment]
Thank you for helping to test the beta! Your participation is very much appreciated!
