### ISSUE TITLE
Adding a VM when Cluster Group is None returns an error

### ISSUE THREAD

**Issue by Gelob** [netbox-community/netbox#5421]
### Environment
Python version: Python 3.6.8
NetBox version: 2.9.7

### Steps to Reproduce
1.  Navigate to Virtualization > VMs > Add (virtualization/virtual-machines/add/)
2.  Fill in the required fields: Name, Cluster, & Cluster Group. Select None for Cluster Group and try to add the VM.

### Expected Behavior
 I expected the VM to get added without a cluster group as None is an option automatically created by Netbox

### Observed Behavior
I got the error "Select a valid choice. That choice is not one of the available choices."
<img width="786" alt="Screen Shot 2020-12-07 at 8 15 10 AM" src="https://user-images.githubusercontent.com/422752/101361437-94d7fc80-3864-11eb-8273-e0e191d419d7.png">

**Comment by jeremystretch** [comment]
This is likely the same underlying issue as in #5315. If you remove "none" from the field and simply leave it blank, it should work.

**Comment by Gelob** [comment]
I confirmed if you remove none and leave it blank, it works.

**Comment by jeremystretch** [comment]
> However if you select a cluster first, than go back to the cluster group dropdown you can select a cluster group that is outside of the cluster and still add the VM.

Yes, that's expected, though it's not terribly intuitive. Due to the way form widgets are populated, the options for the cluster field are refreshed only when it is selected. The cluster group doesn't actually get assigned to the VM being created: the field is only used to filter the options available to the cluster field.

**Comment by jeremystretch** [comment]
Going to close this out since it's essentially the same issue as #5315.
