### ISSUE TITLE
Add list of virtual machines to the cluster detail page

### ISSUE THREAD

**Issue by furlongm** [netbox-community/netbox#5425]
### Environment
* Python version: 3.6
* NetBox version: 2.9.10

### Proposed Functionality
Adding the list of virtual machines in a given cluster to the cluster detail page, underneath the list of host devices. Also, adding an "add virtual machine" button to that table to quickly add virtual machines to a cluster (as with the "add devices" button on the devices table).

### Use Case
Having the list of virtual machines on the cluster page saves having to click the link to the virtual machines page every time you want to see the virtual machines within a cluster. This is a very common operation for us and one of the top complaints of our users.

### Database Changes
None

### External Dependencies
None

**Comment by jeremystretch** [comment]
Clusters can have two types of resources assigned to them: hosts and virtual machines. Currently, the cluster view shows only assigned hosts. We could also display virtual machines, however the pagination system can handle only one type of object. So, we would need to decide for which type of object we'd support pagination.

Typically what we do in that case is to show each type of child object in a separate tab. (You can see an example of this when viewing a prefix, which can have both child prefixes and IP addresses.) That seems like a reasonable approach in this case.

**Comment by furlongm** [comment]
It doesn't look like the current device table has pagination?

**Comment by jeremystretch** [comment]
If not, it should. (All tables should.)

**Comment by furlongm** [comment]
I implemented devices and virtual machines in separate tabs, but have not opened a PR. This is because It does exactly the opposite of the intention of the feature request - which was to reduce the number of clicks required to view the cluster details. Also, the resulting cluster detail page ends up pretty empty so it ends up showing _less_ details about the cluster than previously, which also seems to run counter to the intention of the cluster detail page.

**Comment by jeremystretch** [comment]
Marking this as blocked by the v2.12 UI work (#5893).
