### ISSUE TITLE
Ability to attach images to Circuits

### ISSUE THREAD

**Issue by emajeru** [netbox-community/netbox#5438]
### Environment
* NetBox version: v2.9.10

### Proposed Functionality
When creating circuits, after defining the termination points, provide the ability to attach an image or diagram to the object, extending the functionality introduced in #152. These files will be able to be retrieved within the circuit view without needing to navigate away from the Netbox instance.

### Use Case
* Whenever value can be added by providing a geographical display of a circuit and its termination locations.
* When there is the desire to add annotated diagrams that provide extra detail about a circuit's topology and/or configuration.

### Database Changes
* Circuit model

**Comment by jeremystretch** [comment]
The use cases cited sound like they're better served by a separate document store, with resources linked to from NetBox rather than stored directly.

**Comment by emajeru** [comment]
I agree that a seperate document store can provide the same functionality but I think the same can be said of all attachments in the Netbox UI. If a links component is added to the Circuit interface with the option to use a different `MEDIA_ROOT` or upload directly to an S3 bucket, the use cases can be satisfied.

**Comment by emajeru** [comment]
> The use cases cited sound like they're better served by a separate document store, with resources linked to from NetBox rather than stored directly.

I agree that a seperate document store can provide the same functionality but I think the same can be said of all attachments in the Netbox UI. If a links component is added to the Circuit interface with the option to use a different MEDIA_ROOT or upload directly to an S3 bucket, the use cases can be satisfied.

**Comment by jeremystretch** [comment]
> but I think the same can be said of all attachments in the Netbox UI.

I disagree. The image attachment is intended primarily for photographs of objects to be referenced by someone visiting the site. IMO it makes sense to store these locally within NetBox as each pertains to a specific context. Anything beyond that should be stored elsewhere. Otherwise, we'd just end up replicating a file store application within NetBox.

**Comment by emajeru** [comment]
Okay. I think I have a better understanding of the reasoning behind the decision.
