### ISSUE TITLE
Please add "CS"  and "SN" as a connector type options.   

### ISSUE THREAD

**Issue by heyhogan** [netbox-community/netbox#5439]
### Environment
* Python version: 2.7.5 
* NetBox version: V2.9.10

### Proposed Functionality
Please add "CS"  and "SN" as a connector Type choices for devices and interfaces.  This is a new connector this is a smaller form factor than LC and thus more CS connectors will fit in the same space.  This connector is coming out primarily for higher speed applications like 400G.   You can see this connector alongside a traditional LC at https://www.senko.com/cs-connector/
and https://www.senko.com/sn-connector/

### Use Case
Instead of an LC cassette or patch panel in the rack, there will be a CS (orSN) cassette or patch panel.  This will allow you to model a new device with a CS interface connector and patch it so the patch panel.   My existing cassette (LC) has 6 ports.  The new cassette will have 8 (CS) front ports.  (Both have MPO rear ports).

### Database Changes
None - other than adding CS  and SN as  options if this info is stored in a database.

### External Dependencies
None that I am aware of.

**Comment by jeremystretch** [comment]
Given these appear to be proprietary form factors, should they be prefixed with "Senko"?

**Comment by heyhogan** [comment]
No, I  don't think so.  I work for Panduit and we are launching a full line of CS products.   Senko developed the connector I think and many vendors will license it or be purchasing it from Senko as a raw material for a finished good.  I would prefer to treat it like an LC connector and keep its name simple.    The Panduit SC guide can be found here: [(https://www.panduit.com/content/dam/panduit/en/products/media/2/52/252/3252/110093252.pdf)]
