### ISSUE TITLE
QRCode for API Tokens

### ISSUE THREAD

**Issue by khrys63** [netbox-community/netbox#5443]
### Environment

    * Python version: 3.6.9
    * NetBox version: 2.9.10

### Proposed Functionality

Adding a QRCode on API Tokens screen /user/api-tokens/ for each token with : APItoken value and server name url

### Use Case

We can scan those informations on mobile device for a simple app's configuration

### Database Changes

none

### External Dependencies

none

**Comment by khrys63** [comment]
screen for example :
![netbox-apitoken-screen](https://user-images.githubusercontent.com/21293925/102068443-b6a12880-3dfc-11eb-8922-19ee695474dc.png)
 for example

**Comment by DanSheps** [comment]
I think it might make more sense for us to instead expand plugins to interact with the api token page.  This seems to be a corner case that not everyone could benefit from and the heavy lifting for things like barcodes should not be in the netbox core.

Whereas the plugin could easily be allowed to interact with this in some form or another.

**Comment by khrys63** [comment]
I can reduce it and put it on the right under the three butons.
It's just the API token under a QRCode view.

5 code lines on the core netbox code vs a repo and lot of stuff

with a good UI it can be integrated on the core?

In some day I will present DAMNED : Datacenter Asset Management for Netbox External Device.
This application aimed to allow Asset Management inside the datacenter with a disconnected handheld device. It is synchronized with to Netbox DCIM.
This apps need the APIToken on QRCode to a fast configuration :)

**Comment by DanSheps** [comment]
Yes, I understand it is 5 lines, but those 5 lines the core maintainers are then responsible for maintaining.

Additionally, a plugin only costs us 1 line. Further, this won't be desirable by most and could also result in security breaches (what if someone is looking over your shoulder while you are working in tokens and scans a privileged token?).

Plugins would offer the most customizability.  Not everyone is going to want this functionality and if we keep adding Niche features like this without using the plugin framework our views are going to end up looking cluttered.

Either way, as this is a feature request it isn't going to get actioned right away.

**Comment by jeremystretch** [comment]
> Yes, I understand it is 5 lines

**Comment by khrys63** [comment]
I work on the plugin :)

**Comment by jeremystretch** [comment]
I'm going to close this out in favor a plugin approach. Please note that you'll likely need to open a separate FR to enable plugins to embed content on the API tokens page, which may require further discussion.
