### ISSUE TITLE
Allow all Interface bulk-edit fields to be set to "don't change"

### ISSUE THREAD

**Issue by steffann** [netbox-community/netbox#5444]
### Environment
* Python version: 3.7.3
* NetBox version: v2.9.10

### Proposed Functionality
I noticed that when bulk-editing multiple interfaces there is only an "Enabled" checkbox which affects all the selected interfaces. I propose to change that checkbox so that it becomes possible to leave the enabled state of the interfaces unchanged.

The same is true for the "OOB Management" checkbox.

### Use Case
If you currently want to change a property of multiple interfaces, some of which are enabled and some of which are disabled, you'd either have to do the change twice (once for the enabled and once for the disabled interfaces) or, which happens to me sometimes, I make a change to the interfaces, realise I accidentally enabled some interfaces, and then disable them again.

The "OOB Management" checkbox works in the same way, so I'd suggest changing them both. It would be very useful if the default setting for all the fields in the bulk-edit is "don't change".

### Database Changes
None

### External Dependencies
None

### Implementation volunteering
I'd be happy to

**Comment by steffann** [comment]
That only seems to fix it for the `mgmt_only` field. Am I missing something?

**Comment by jeremystretch** [comment]
Missed that, thanks!
