### ISSUE TITLE
Filter connected interfaces - Netbox-2.10

### ISSUE THREAD

**Issue by Radi85** [netbox-community/netbox#5445]
### Environment
* Python version: 3.7.8
* NetBox version: 2.10-beta3

### Steps to Reproduce
1. `/api/dcim/interfaces/?connected_endpoint_reachable=true`

### Expected Behavior

The interfaces should be filtered and a list of only **connected** interfaces should be returned according to the [release-notes/version-2.10.md](https://github.com/netbox-community/netbox/blob/develop-2.10/docs/release-notes/version-2.10.md#rest-api-changes) 

### Observed Behavior
The interfaces are not filtered and all entries are returned.

after inverstigating the [code](https://github.com/netbox-community/netbox/blob/develop-2.10/netbox/dcim/filters.py#L760-L769), I found that using `connected` instead of `connected_endpoint_reachable` gives the expected result.

**Comment by jeremystretch** [comment]
> NetBox version: 2.10

Please indicate the specific version of NetBox you are running. (NetBox v2.10.0 has not yet been released.)

**Comment by Radi85** [comment]
We are currently using up to date `develop-2.10` branch `43d7d55` which is supposed to be in `v2.10-beta3`.

**Comment by jeremystretch** [comment]
> The interfaces should be filtered and a list of only connected interfaces should be returned according to the release-notes/version-2.10.md

`connected_endpoint_reachable` is a field of the serialized object, not a filter. Per the REST API documentation, the available filters are `cabled` and `connected`; the later indicates whether and end-to-end path exists.

**Comment by DanSheps** [comment]
Looks like this is resolved.  Going to mark this as pending closure.
