### ISSUE TITLE
API serializer foreign count fields do not have a default value

### ISSUE THREAD

**Issue by markkuleinio** [netbox-community/netbox#5450]
### Environment
* Python version: 3.7.3
* NetBox version: 2.9.11

### Steps to Reproduce
1. Create a new tag with any name, like "Testing"
2. Get the same tag via API and see `tagged_items` field

### Expected Behavior
`tagged_items` is 0 (API docs say the field is `integer`)

### Observed Behavior
`tagged_items` is `null`

```
$ curl -s -X GET "http://netbox-test.example.net/api/extras/tags/?name=Testing" -H "Authorization: token xxx" | jq .
{
  "count": 1,
  "next": null,
  "previous": null,
  "results": [
    {
      "id": 4,
      "url": "http://netbox-test.example.net/api/extras/tags/4/",
      "name": "Testing",
      "slug": "testing",
      "color": "9e9e9e",
      "description": "",
      "tagged_items": null
    }
  ]
}
```

**Comment by jeremystretch** [comment]
This happens in other areas, as well, when there are no related objects. Need to force `null` to zero somehow.

**Comment by DanSheps** [comment]
Looks like we can do a default=0 in the serializer.  This could be breaking though, perhaps we want to wait for 2.11?

**Comment by jeremystretch** [comment]
I'd argue that it's really fixing a bug rather than changing previously-desired behavior, so I think it's okay to change now.

**Comment by DanSheps** [comment]
I am going to change all instances of _count = serializer.IntegerField to have default=0.
