### ISSUE TITLE
Custom field multiple selection

### ISSUE THREAD

**Issue by TomGrozev** [netbox-community/netbox#5451]
### Environment
* Python version: 3.8.6
* NetBox version: 2.10

### Proposed Functionality
The ability to be able to select multiple values in custom fields of type "Selection". This is similar to how tags work but the ability to do it for custom selection fields. A new option to allow multiple options to be selected for custom selection fields would be added and using the Django multiple selection form, this can be added.

### Use Case
We use ansible to deploy configurations and NetBox as the source of truth. We need to be able to select multiple applications for a virtual machine and then ansible can use that to deploy the application. In order to do this and install multiple applications, we need to be able to select multiple values from a custom field of type "Selection".

### Database Changes
A new multiple selection field would be added to the custom field model. Since the changes in version 2.10
 store custom field data as JSON, storing a list of values is simple.

### External Dependencies
None

**Comment by jeremystretch** [comment]
With the move to JSON-based custom field data in v2.10, this is now a possibility.

**Comment by hyudra** [comment]
Is it possible to add custom field with JSON / List type? Sometimes our data do not have fixed length data (such as VM with multiple disks).

**Comment by TomGrozev** [comment]
@hyudra In order for multiple fields to be selected, the natural solution is for the items to be stored as a list in JSON.

**Comment by schmitmd** [comment]
I've got the same use case as TomGrozev.  Using Netbox as a dynamic Ansible inventory via the [Netbox Ansible collection](https://docs.ansible.com/ansible/latest/collections/netbox/netbox/index.html).  It looks like #5440  was closed as rejected though.  Is someone going to re-implement it differently for the 2.11 milestone or is PR code actually valid & intended to be pulled in, or...?

**Comment by fabi125** [comment]
> Is it possible to add custom field with JSON / List type? Sometimes our data do not have fixed length data (such as VM with multiple disks).

Having a custom field that can store multiple values (not necessarily from a selection) would be great. Can this FR be expanded to include that or should I open a separate issue?
