### ISSUE TITLE
Cannot create objects with required custom field

### ISSUE THREAD

**Issue by nahun** [netbox-community/netbox#5466]
### Environment
* netbox-docker with latest
* Python version: 3.9.1
* NetBox version: 2.10.0

### Steps to Reproduce
1. Create a new instance of Netbox using the "latest" build of netbox-docker. The quickstart commands are good.
2. Create a new Text custom field for DCIM > Device. Mark it required.
3. Create a new Device, enter anything for the required fields.
4. Type some text in the required custom field.
5. Create

### Expected Behavior
The device be created

### Observed Behavior
Error creating the device: `Missing required custom field 'test'.`
![image](https://user-images.githubusercontent.com/690651/102265493-07338700-3ecc-11eb-8d53-743569d67405.png)

If you mark the custom field as not required, then it takes the value and works fine.

**Comment by jeremystretch** [comment]
> Create a new instance of Netbox using the "latest" build of netbox-docker. The quickstart commands are good.

Please note that bug reports must provide reproduction steps using only the stock code base: We do not support the Docker image.

**Comment by nahun** [comment]
Sorry about that, and thanks for the fix!
