### ISSUE TITLE
Move Coalesce into get_subquery function and rename function to get_related_count

### ISSUE THREAD

**Issue by DanSheps** [netbox-community/netbox#5471]
### Proposed Changes
* Move the Coalescence from the serializer into the get_subquery function
* Rename function from get_subquery() to get_related_count()

### Justification
Since the get_subquery function is only used for annotating a count, it would make sense to add the Coalescence into the function instead of on each instance of get_subquery.

Renaming the function will better describe the purpose of the function.

**Comment by jeremystretch** [comment]
While we're at it, should we rename `get_subquery()` to something that better conveys its purpose? It's only ever used to return a count of related objects: Maybe `get_related_count()` or something similar?

**Comment by DanSheps** [comment]
I will add that to the scope then.

**Comment by jeremystretch** [comment]
Implemented in 91083fd6c52f11a4af163be1978b9a75d66ea639 and 4a066a191318799a48b4e5380feea6774e4ea8fe
