### ISSUE TITLE
Allow customization of job timeout for scripts

### ISSUE THREAD

**Issue by DanSheps** [netbox-community/netbox#5479]
### Environment
* Python version: 3.6.6
* NetBox version: 2.10.1

### Proposed Functionality
* Add JOB_TIMEOUT to Script base class
* Add job_timeout=Script.JOB_TIMEOUT to enqueue_job kwarg (per docs, this is popped out on job start)

### Use Case
With the move towards background job processing, the time constraint on scripts is no longer as restrictive.  I feel allowing customization of the job_timeout per-script would be beneficial (if a job times out, the job is still also listed as "Running", this should be handled separately as a bug)

### Database Changes
None

### External Dependencies
None

**Comment by jeremystretch** [comment]
> Add JOB_TIMEOUT to Script base class

Should this be a `Meta` attribute?

**Comment by DanSheps** [comment]
I think making it a Meta attribute would be reasonable.

**Comment by DanSheps** [comment]
I am going to take a crack at this sometime this month.  Just been a busy month so far.

**Comment by DanSheps** [comment]
This will likely need a re-implementation of the @job decorator, most of it can be superclassed but delay might need to be re-worked (at least a little).

Thoughts @jeremystretch?

**Comment by seros1521** [comment]
Customizable timeout for reports would also be useful.
