### ISSUE TITLE
Long-running rq jobs (often scripts) do not "fail"

### ISSUE THREAD

**Issue by DanSheps** [netbox-community/netbox#5480]
### Environment
* Python version: 3.6.6
* NetBox version: 2.10.1

### Steps to Reproduce
1. Create a job that takes longer then specified timeout (300)
2. Run job
3. Wait

### Expected Behavior

* Job will be marked as failed

### Observed Behavior

* Execution will stop, job will not be marked as failed

**Comment by jeremystretch** [comment]
@DanSheps is this still an issue? If so, it should probably be classified as a bug.

**Comment by DanSheps** [comment]
I will have to double check

**Comment by DanSheps** [comment]
I think this isn't so much an issue with it long-running as it is with it hitting an exception somewhere.  I need to dig more I think.
