### ISSUE TITLE
Counter-intuitive use of icons in column "Tagged" on page VLANs / Device Interfaces

### ISSUE THREAD

**Issue by jbakklund** [netbox-community/netbox#5484]
### Environment
* Python version: 3.7.3
* NetBox version: 2.10.1

### Steps to Reproduce
1. Create at least one VLAN.
2. Add this VLAN to a couple of device interfaces, some in access mode, and others as tagged (switchport mode trunk).
3. Navigate to the VLAN you just created (on page .../ipam/vlans/X/ where X represents the VLANs unique database key).
4. Click on the tab "Device Interfaces".

### Expected Behavior
In the column "Tagged", I would expect to see a kind of positive checkmark or icon for interfaces participating in the given VLAN with its 802.1Q mode set to "Tagged", and a kind of negative icon for interfaces participating in Access Mode.

### Observed Behavior
This seems to have been swapped around: Interfaces where the VLAN is actually tagged are listed with a red X, which I interpret as a "No" - this interface is not tagged, while interfaces not being tagged are listed with a green Checkmark, which I interpret as a "Yes" - this one is tagged.

![ipam_vlans_x_interfaces](https://user-images.githubusercontent.com/33431806/102481800-88bd1d80-4062-11eb-8be0-062a9d9fab9e.png)

The current use of icons seems counter-intuitive for a column named "Tagged". I think the usage should be swapped around, or the column could be renamed "Access Mode", or simply named "Mode" while using text showing "Access" or "Tagged" instead of the icons.

**Comment by jeremystretch** [comment]
Thank you for the detailed bug report!
