### ISSUE TITLE
Assertion error at webserver start

### ISSUE THREAD

**Issue by francescocarzaniga** [netbox-community/netbox#5502]
### Environment
* Python version: 3.8.6
* NetBox version: 2.10.1
* PostgreSQL: 13 (external)
* Redis: 6 (external)
* OS: OmniOS 5.11

### Steps to Reproduce
Follow the steps in the [guide](https://netbox.readthedocs.io/en/stable/installation/). Everything works fine, Netbox connects to database and to Redis cache.
Arrive at the point where you start the Werkzeug web server.
Curl the host at the specified port.

### Expected Behavior

Netbox should start and begin serving the pages. Curl should return the homepage.

### Observed Behavior
Werkzeug crashes with
```
(venv) root@netbox:/opt/netbox/netbox# python3 manage.py runserver 0.0.0.0:8000 --insecure
Performing system checks...

System check identified no issues (0 silenced).
December 19, 2020 - 09:42:43
Django version 3.1.3, using settings 'netbox.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CONTROL-C.
Assertion failed: section != NULL, file prof_tree.c, line 528, function profile_node_iterator
```

**Comment by DanSheps** [comment]
This appears to be a bug in your kerberos package.

I am going to convert this to a discussion, perhaps someone else has seen this issue before.
