### ISSUE TITLE
Default to ISO 8601 date format in UI and add "June 26, 2016" as tooltip

### ISSUE THREAD

**Issue by ypid** [netbox-community/netbox#5503]
### Environment
* Python version: 3.7.3
* NetBox version: 2.10.1

### Proposed Functionality

The current approach seems to be to use ISO 8601

```python
SHORT_DATE_FORMAT = 'Y-m-d'          # 2016-06-26
```

where the logical order matters, for example in the changelog view that is sorted by time. For "free text" dates,

```python
DATE_FORMAT = 'N j, Y'               # June 26, 2016
```

is used. I am proposing to use `SHORT_DATE_FORMAT` everywhere in the UI except in tooltips. And then augment dates as tooltip in `DATE_FORMAT`. This is because ISO 8601 is *the* standard for dates in written form. If the user ever needs to communicate a date via voice, they are expected to translate 2016-06-26 in their head or peek in the tooltip and say "June 26, 2016".

@jeremystretch commented on ISO 8601 in https://github.com/netbox-community/netbox/issues/1412#issuecomment-321318039 already so I assume there is some background to the current default. I still would like to discuss this.

### Use Case

Consistency.

### Database Changes

No.

### External Dependencies

No.

**Comment by xkilian** [comment]
Depending on the language for your region this may or may not be true. For latin based languages, it is more natural to say out loud(or in his head) 26th of June 2016(in the language of choice). Depends on the intent when using the tooltip. Anyway, idea is interesting for the tootip.

**Comment by jeremystretch** [comment]
Marking this as `needs owner` for anyone who wants to do the work. Please ensure that all changes are kept consistent across all objects.

> For latin based languages, it is more natural to say out loud(or in his head) 26th of June 2016(in the language of choice).

The date formats are all [configurable](https://netbox.readthedocs.io/en/stable/configuration/optional-settings/#date-and-time-formatting).

**Comment by ypid** [comment]
I am looking into this now. Not sure how far I get. I will open a PR in the best case.

**Comment by ypid** [comment]
I opened #5764 which implements this.
