### ISSUE TITLE
Custom fields for IP addresses, secrets are not working/storing the data in v2.10.1

### ISSUE THREAD

**Issue by 991jo** [netbox-community/netbox#5507]
### Environment
* Python version: 3.6.8
* NetBox version: 2.10.1

### Steps to Reproduce
1. Create a custom field for IP addresses (I have tested boolean and text fields)
2. add/edit an IP address and populate the field

### Expected Behavior
The custom fields are saved and shown in the Web UI/Django object

### Observed Behavior
The custom fields are empty. (The Django objects `.cf` is also an empty dict)

### Further Observations
Custom fields for other objects (e.g. Prefixes) work as intended.

**Comment by bmhughes** [comment]
Getting the same result here as well.

**Comment by jeremystretch** [comment]
Looks like secrets are also affected.

The problem is a missing call to `super().clean()` on the model forms; an easy fix. Thanks for the report!
