### ISSUE TITLE
Custom field for interfaces and inventory item

### ISSUE THREAD

**Issue by hyudra** [netbox-community/netbox#5511]
### Environment
* NetBox version: 2.10.1

### Proposed Functionality
Refer to #1254 and #2281, it did not implement due to complexity of previous version CustomField Value model. As now each custom field reside within each model, is it possible to have this feature? I knew that many people would like this feature to be available.

### Use Case
I'd like to implement custom field to stored some automated data to it. e.g. dot1x enabled / security-mode

**Comment by jeremystretch** [comment]
Thank you for submitting this issue, however it appears that this topic has already been raised. Please see issue #5401 for further discussion.
