### ISSUE TITLE
extras/changelog/ got 'NoneType' object has no attribute '_base_manager'

### ISSUE THREAD

**Issue by hyudra** [netbox-community/netbox#5515]
### Environment
* Python version: 3.9.1
* NetBox version: 2.10.2

### Steps to Reproduce
1.  Upgrade from v2.9.9 from docker
2.  open /extras/changelog/

### Expected Behavior
Able to see all changelog properly

### Observed Behavior
got error 
><class 'AttributeError'>
'NoneType' object has no attribute '_base_manager'

I can see changelog from homepage and api properly. Not sure where to look for troubleshooting

**Comment by hyudra** [comment]
Found root cause.
Seem relate to ldap configuration populate invalid email address.

**Comment by lordlan31** [comment]
Error after update to netbox-2.10.2:
AttributeError: 'NoneType' object has no attribute '_base_manager'
