### ISSUE TITLE
Config for Caddy Webserver

### ISSUE THREAD

**Issue by ThisIsTenou** [netbox-community/netbox#5519]
### Change Type
[X] Addition
[ ] Correction
[ ] Deprecation
[ ] Cleanup (formatting, typos, etc.)

### Area
[X] Installation instructions
[ ] Configuration parameters
[ ] Functionality/features
[ ] REST API
[ ] Administration/development
[ ] Other

### Proposed Changes
Adding a default config for the [Caddy Webserver](https://caddyserver.com) as well, in addition to Apache & NGINX.

I've successfully tested this one:
```
192.168.15.24 {
  route /static* {
    uri strip_prefix /static
    root * /opt/netbox/netbox/static
    file_server
  }
  @notStatic not path /static*
  reverse_proxy @notStatic 127.0.0.1:8001
  encode gzip zstd
  tls /etc/ssl/certs/netbox.crt /etc/ssl/private/netbox.key
  log {
    level error
  }
}
```
You'd obviously need to change the IP address in the first line to your own IP or domain, but besides that, it's just as plug-and-play as the others.

**Comment by jeremystretch** [comment]
The documentation is intentionally limited to supporting only nginx and Apache, as these are the two most commonly deployed HTTP servers, and extending the documentation would increase the burden of maintaining it. However, if you'd like to publish documentation and a reference configuration for Caddy on your own, I'd be happy to add a link in the wiki.

**Comment by ThisIsTenou** [comment]
Hey there, as you suggested, I've written a small step-by-step guide on how to install and configure Caddy instead of Apache/NGINX. Feel free to link to it, I'll try to keep it updated whenever new releases are coming out.

https://shrt.tenou.de/KLFRte

**Comment by jeremystretch** [comment]
Thanks! I've added it to [the wiki](https://github.com/netbox-community/netbox/wiki/Community-Contributions).
