### ISSUE TITLE
Search by MAC address

### ISSUE THREAD

**Issue by davidestorey** [netbox-community/netbox#5526]
### Environment
* Python version: 3.8
* NetBox version: 2.10.1

### Proposed Functionality
It's possible to search by MAC address for physical devices. It is currently impossible to search by MAC for virtual machines. It would be great to add that to the Interfaces section under Virtual machines. Additionally, adding to the global search would be awesome!

### Use Case
Many times, we find a mac hanging off a switch port and want to identify it. Searching by MAC would make life easier.

### Database Changes
Don't believe this change would require a schema change

### External Dependencies
Should not require any external dependencies.

**Comment by jeremystretch** [comment]
FYI this filter is already present; it was just never added as a field to the search form.

**Comment by OtherSystems** [comment]
Is it possible to do a global search on mac addresses? Would be very handy when trying to figure out what has this mac address I keep running into.

**Comment by stuntguy3000** [comment]
@jeremystretch, following @OtherSystems's comment above and other issues #6435, why would device interfaces not be searchable via the **global search function**?
