### ISSUE TITLE
Tenants have the tenant slug in the url, not the id

### ISSUE THREAD

**Issue by 991jo** [netbox-community/netbox#5528]
### Environment
* Python version: 3.6.8
* NetBox version: 2.10.2

### Steps to Reproduce
1. create a tenant (e.g. with the name marvin)
2. click on the tenant object

### Expected Behavior
the tenant url is `http://netbox.example.com/tenancy/tenants/42`

### Observed Behavior
the tenant url is `http://netbox.example.com/tenancy/tenants/marvin`

### Why is this a problem
afaik all other objects have their id in the url. This means that I can just put a `/api` in the path to see the object via the API.
This does not work with tenants.

**Comment by jeremystretch** [comment]
This is clearly intentional, and several other objects (such as sites) also do this. The web UI and REST API often have very similar URLs, but are not intended to be identical. Any overlap is purely coincidental.
