### ISSUE TITLE
Script variables inherited from superclass are not included in form rendering

### ISSUE THREAD

**Issue by glennmatthews** [netbox-community/netbox#5529]
### Environment
* Python version: 3.7.7
* NetBox version: 2.9.11

### Steps to Reproduce
Create a Script class which defines one or more variables; subclass this script and add extra variables to the subclass. When accessing the input form for the subclass script, only the added variables are present in the form - the variables inherited from the parent class are missing.

```python
from extras.scripts import Script, StringVar

class SimpleScript(Script):
    class Meta:
        field_order = ["simple_variable"]

    simple_variable = StringVar()

class ExtendedScript(SimpleScript):
    class Meta:
        field_order = ["simple_variable", "extended_variable"]

    extended_variable = StringVar()
```

![image](https://user-images.githubusercontent.com/5603551/103017677-f7422580-4511-11eb-85db-7ea3a6fc4845.png)

### Expected Behavior

Both inherited and locally defined variables should be present in the input form. I believe that inherited variables were included in forms prior to commit eaaaaec5a524c76ff2e76192b2cbea5e7445705d, as we were using `field_order` and `getattr` to look up the variables in `_get_vars`, instead of `__dict__` (which doesn't include inherited attributes).

### Observed Behavior

Only variables locally defined on the subclass are included in the input form, regardless of their inclusion in `field_order`.

**Comment by glennmatthews** [comment]
Workaround is to update the script to manually include the parent class's variables, i.e.:

```python
class ExtendedScript(SimpleScript):
    class Meta:
        field_order = ["simple_variable", "extended_variable"]

    simple_variable = SimpleScript.simple_variable
    extended_variable = StringVar()
```

But it would be better if `field_order` were respected.

**Comment by drmsoffall** [comment]
@glennmatthews,
This is a behavior of Python, not of NetBox.  Inner classes of a subclass do not automatically inherit from inner classes of a parent class.  See https://www.codespeedy.com/understanding-inheritance-in-python-inner-class/ for an example.

You could possibly come up with a more clear way to take advantage of this, like inheriting from the parent class' inner class and then using += instead of =, or some variation thereof.

**Comment by glennmatthews** [comment]
Thanks for the comment, but I believe that the behavior of inner classes is not relevant to this issue. `simple_variable` and `extended_variable` are not inner classes, and I'm explicitly setting the `field_order` `Meta` attribute in `ExtendedScript`, not inheriting anything from the `SimpleScript` `Meta` inner class.

**Comment by lampwins** [comment]
I agree with @glennmatthews, and there is a pretty standard pattern for this in the Django world. Django Rest Framework and Django Filters both use a Metaclass that defines a method to traverse all base classes and collect defined fields for Serialiers and Filtersets, respectively. We could do the same thing for Script variables. See https://github.com/encode/django-rest-framework/blob/master/rest_framework/serializers.py#L281

**Comment by jeremystretch** [comment]
Reclassifying this as a proposed feature since the described behavior has never been documented as supported.

This needs a well-formed proposed implementation before any work can proceed.
