### ISSUE TITLE
Request for the option to move a physical to a VM once a device is P2V'd

### ISSUE THREAD

**Issue by waynster** [netbox-community/netbox#5530]
### Environment
* Python version: 3.6
* NetBox version: 2124f31f2d87 (v2.9.7)

### Proposed Functionality
Can it be considered to have a function to transfer (p2v) a physical to a VM entry? We are busy retiring lots of legacy hardare to VMs and currently deleting and creating new entries is cumbersome

    We virtualize a physical system to a VM
    Firstly we go into netbox device entry for the old physical
    Click edit then have a field or button to virtualize host
    Clicking this presents dropdowns/fields for renaming, resizing, new cluster, cluster group region, comments, local configuration context data etc.
    Once submitted, new VM is created, also old physical is marked as offline

### Use Case
    For virtualizing servers as stated

### Database Changes
Not known/N/A

### External Dependencies
Not known/N/A

**Comment by rodvand** [comment]
This sounds like a perfect use case for a custom script.

**Comment by DanSheps** [comment]
As @rodvand mentioned, this would be best handled with a custom script or plugin that creates a VM, creates new data, then deleted the old device.

We are not going to be adding this to the base functionality and this will be pending closure.

**Comment by sdktr** [comment]
@Mathijsvanwilligen tagging for future reference re: migration script
