### ISSUE TITLE
Ability to create Virtual Machine on single node, not cluster

### ISSUE THREAD

**Issue by xcdr** [netbox-community/netbox#5535]
### Environment
* Python version: 3.8.6
* NetBox version: v2.10.2

### Proposed Functionality
Ability to create Virtual Machine on single node, not cluster

### Use Case
Very often VM are created on single nodes (vmware, xen, kvm).

We have mixed environment of clusters and separated single nodes that always should be single nodes.

### Database Changes
Add device_id to virtual machine model and conditional requirements of cluster_id or device_id.

Device should have boolean field such as "vm_support".

**Comment by candlerb** [comment]
What I do is to create a one-node cluster for each VM host, with name equal to the underlying device.

This does the same as your proposed boolean field "vm_support", except that the cluster object also documents the virtualization type (e.g. vmware, xen, kvm).  So if single-node clusters were to be added, adding a nullable "virtualization_type" field would be better.

However this data change doesn't actually enhance the capabilities of Netbox - instead it adds a second way to model something which can already be modelled.  Therefore I'd say it increases complexity for little gain.

**Comment by jeremystretch** [comment]
This was discussed at length when support for virtual machines was initially implemented, and the consensus was to always map a VM to a cluster, even when only one physical device exists, for consistency.

**Comment by xcdr** [comment]
I understand, but still think it's a stretch of reality and confusing for people who want quick overview of infrastructure.

This sounds like: we have that many clusters in our infra? Oh no, these are not clusters but described as clusters :-)

**Comment by jeremystretch** [comment]
They are single-host clusters, which is perfectly valid. It also makes adding future _much_ easier. I'm sorry, but this has been considered settled for a long time.
