### ISSUE TITLE
Requesting option to clone Interfaces when cloning Device Type

### ISSUE THREAD

**Issue by lastwednesday** [netbox-community/netbox#5536]
### Environment
* Python version: 3.8.3
* NetBox version: 2.10.2

### Proposed Functionality
I would like the ability to include the defined Interfaces for a Device Type when cloning it, so that if I have Device Type X and I clone it to Device Type Y then I wouldn't need to re-create all the Interfaces from scratch on Device Type Y. If I were cloning a Device I could just export the Interfaces for that Device then edit and import them for the new Device, but if there is a way to export/import Interface templates for a Device Type I haven't found it so far. As a workaround I can just export the entire device type to yaml then edit it externally and import it again for the new model, although the export does not include the Label or Description fields from the template so those must be entered again after import.

This could just be a dropdown option on the Clone button so that users could determine if they wanted to clone the Interfaces or not.

### Use Case
We have for example about a dozen different models of a vendor's device, which are identical except for things like CPU/Cache and supported firmware levels. I have been cloning them to build each model but even with being able to define Interfaces by pattern it is still pretty tedious to go in and add the identical groups of 47 or so interfaces onto each one after it is cloned.

### Database Changes
I don't believe so.

### External Dependencies
No external dependencies.

**Comment by Starkstromkonsument** [comment]
This would be cool for console ports, power ports and device bays too.

**Comment by jeremystretch** [comment]
This was proposed in #4065 in never gained traction. IMO the effort required to develop a new workflow/pattern to **sustainably** implement the feature isn't going to be worth the development effort, particularly given that device types are easily imported from YAML/JSON definitions. But I'll tag it for volunteers.
