### ISSUE TITLE
Redis Installation under Centos

### ISSUE THREAD

**Issue by Lon1** [netbox-community/netbox#5539]
### Change Type
[X ] Addition
[ ] Correction
[ ] Deprecation
[ ] Cleanup (formatting, typos, etc.)

### Area
[X ] Installation instructions
[ ] Configuration parameters
[ ] Functionality/features
[ ] REST API
[ ] Administration/development
[ ] Other

It appears that you need to install the EPEL package first on Centos as described in https://www.digitalocean.com/community/tutorials/how-to-install-secure-redis-centos-7
### Proposed Changes
Centos
Before we can install Redis, we must first add Extra Packages for Enterprise Linux (EPEL) repository to the server’s package lists. EPEL is a package repository containing a number of open-source add-on software packages, most of which are maintained by the Fedora Project.

We can install EPEL using yum:

sudo yum install epel-release
 
Once the EPEL installation has finished you can install Redis and add to start on boot:

sudo yum install -y redis
sudo systemctl start redis
sudo systemctl enable redis

You may wish to modify the Redis configuration at /etc/redis.conf or /etc/redis/redis.conf, however in most cases the default configuration is sufficient.

**Comment by jeremystretch** [comment]
The installation instructions are for CentOS 8.2. We no longer maintain documentation for earlier releases.
