### ISSUE TITLE
Editing device bay da0

### ISSUE THREAD

**Issue by n4zmz** [netbox-community/netbox#5550]
![Screen Shot 2020-12-29 at 4 23 43 PM](https://user-images.githubusercontent.com/72481599/103314985-48f71e00-49f2-11eb-87a8-93af7ea2dd54.png)
Trying to update the description on a device bay and it reports that the device does not support device bays.
![Screen Shot 2020-12-29 at 4 25 52 PM](https://user-images.githubusercontent.com/72481599/103315071-8d82b980-49f2-11eb-8e28-fa1023b63995.png)

**Comment by candlerb** [comment]
It appears that device "trueNas-01" is linked to device type "Slicestor".

Can you open the "Slicestor" device type, and check what it says for "Parent/child status"?  This can be one of:
- empty (`-----`)
- Parent
- Child

This needs to be set to "Parent" to allow device bays to be created (or edited).

(If this fixes the problem, then the issue becomes one of data consistency: how the device bays were created in the first place when the device wasn't a parent, or how the status was changed from "Parent" to "-----" when bays already existed)

**Comment by n4zmz** [comment]
The device type "Slicestor" was set to "----".  Changing it to Parent fixed
the editing issue.

The type was created with interfaces and device bays with the parent status
blank.  It stills allows this behavior at v2.10.2.

Process:
Device type add
Manufacturer: IBM
Model: store2
Rest left at default (parent/child is ---------)
click create
click add components and select device bays
Name: da[0-11]
click create

I did add interfaces as well, but not necessary to reproduce the issue.

Create a device with the new type and try and edit one of the device bays.
Which will fail due to the parent status not being set.

**Comment by candlerb** [comment]
Good catch.  If the device type template allows bays to be added, even when the device type is not set to "Parent", I think that's a separate bug you can raise, and close this one.

The validation already exists in class DeviceBay in `netbox/dcim/models/device_components.py`:

```
    def clean(self):
        super().clean()

        # Validate that the parent Device can have DeviceBays
        if not self.device.device_type.is_parent_device:
            raise ValidationError("This type of device ({}) does not support device bays.".format(
                self.device.device_type
            ))
```

A corresponding check needs adding to DeviceBayTemplate in `netbox/dcim/models/device_component_templates.py`

**Comment by n4zmz** [comment]
Closing the device issue and creating a device_type/template issue.
