### ISSUE TITLE
can't set a platform with an manufacturer

### ISSUE THREAD

**Issue by greinick** [netbox-community/netbox#5553]
### Environment
* Python version: Python 3.8.5
* NetBox version: netbox-2.10.2

### Steps to Reproduce
1. Add a manufacturer
2. Add a Platform and set the manufacturer (or an already existing one)
3. Try to add that platform to a (new) device.

### Expected Behavior

I'd expect the platform to show up in the drop down box.

### Observed Behavior

The platform dose not show up.

### Notes

I checked with newly created manufactures, platform and device, as well with changing existing ones. All the same behaviour.

Also I checked if I have some hidden/special characters entered or "spaces" etc.

Any Ideas how to debug that further?

**Comment by jeremystretch** [comment]
Per the docs:

> Platforms may optionally be limited by manufacturer: If a platform is assigned to a particular manufacturer, it can only be assigned to devices with a type belonging to that manufacturer.

Does the device you created belong to the same manufacturer?

**Comment by greinick** [comment]
Uh, no. I guess I missed that in the docs. But for example if I do have a server from Dell or Supermicro, how may I add a OS like Red Hat or Microsoft Windows as Platform ... ?

**Comment by jeremystretch** [comment]
In that case, you wouldn't restrict the platform by manufacturer since it can be used by many types of devices. The manufacturer association is intended for software that's bound to certain types of devices. For example, Junos (generally) runs only on Juniper devices.

**Comment by greinick** [comment]
Ah ok, got it! Thanks.
