### ISSUE TITLE
Power Ports draw: add automatic calculation based on connected devices on power outlets

### ISSUE THREAD

**Issue by Starkstromkonsument** [netbox-community/netbox#5560]
### Environment
* Python version: 3.6.9
* NetBox version: 2.10.2

### Proposed Functionality

For devices with power outlets it would be nice to have an option to enable netbox to automatically calculate the maximum draw and allocated draw for Power Ports.

### Use Case

Cascaded PDUs and UPSs on a Power Feed. See example setup in Use Case of #5559

### Database Changes

none?

### External Dependencies

none?

**Comment by jeremystretch** [comment]
Thank you for submitting this issue, however it appears that this topic has already been raised. Please see issue #3377 for further discussion.

**Comment by Starkstromkonsument** [comment]
Sorry!
