### ISSUE TITLE
Power Feeds Connection Cable Trace link opens trace for wrong cable

### ISSUE THREAD

**Issue by Starkstromkonsument** [netbox-community/netbox#5563]
### Environment
* Python version: 3.1.3
* NetBox version: 2.10.2

### Steps to Reproduce
1. Create Power Feed
2. Create Device with Power Port
3. Connect Device Power Port to Power Feed
4. Open Power Feed Device Page
5. Click on Trace-Button of Cable Connection

### Expected Behavior

Open the Trace for the corresponding cable, e.g. https://www.example.org/dcim/power-ports/27/trace/

### Observed Behavior

A wrong trace of type console-port for a different device is being opened, e.g. https://www.example.org/dcim/console-ports/3/trace/

**Comment by DanSheps** [comment]
Thank you for opening a bug report. I was unable to reproduce the reported behavior on NetBox v2.10.2. Please re-confirm the reported behavior on the current stable release and adjust your post above as necessary. Remember to provide detailed steps that someone else can follow using a clean installation of NetBox to reproduce the issue. Remember to include the steps taken to create any initial objects or other data.
