### ISSUE TITLE
Dark Theme

### ISSUE THREAD

**Issue by samip5** [netbox-community/netbox#5567]
### Environment
* Python version: 3.8.5
* NetBox version: 2.10.2

### Proposed Functionality

Dark theme for the UI

### Use Case

When looking at the UI and doing things there with almost no light in your surroundings, it hurts to look at due to being too bright.

### Database Changes

None

### External Dependencies

Possibly something Bootstrap related

### Related issues

#3599

**Comment by jeremystretch** [comment]
This was proposed in #3599 and no one volunteered.
