### ISSUE TITLE
Ability to see the ARPA record name in IP address details, and/or check if PTR record exists

### ISSUE THREAD

**Issue by samip5** [netbox-community/netbox#5568]
### Environment
* Python version: 3.8.5
* NetBox version: 2.10.2

### Proposed Functionality

When checking the details of an IPv6 address, please include a field which would output the arpa entry in full format and possibly check if a PTR exists from the IPv6 range's authorative rDNS nameservers.

### Use Case

Easier rDNS management, when you can easilly check which records are missing and you can just copy the arpa record name from the UI.

### Database Changes

I don't know of any.

### External Dependencies
N/A

**Comment by DanSheps** [comment]
Your best option would be to create a plugin to handle this.  This is not something we are going to look at adding to the core any time soon.
