### ISSUE TITLE
Device Type allows device bays without being set to parent

### ISSUE THREAD

**Issue by n4zmz** [netbox-community/netbox#5574]
### Environment
* Python version:  3.8.5
* NetBox version: 2.10.2

### Steps to Reproduce

1. Device type add
Manufacturer: IBM
Model: store2
Rest left at default (parent/child is ---------)
2. click create
3. click add components and select device bays
Name: da[0-11]
4. click create

### Expected Behavior
Adding device bays should fail until device type is set to parent

### Observed Behavior
Device bays are added, but can not be edited until parent is set.

**Comment by jeremystretch** [comment]
Would there be a significant impact from simply removing the parent role designation from DeviceType entirely? IIRC we used to have similar controls for the assignment of other components but ditched them a long time ago. It doesn't seem necessary.

**Comment by DanSheps** [comment]
I don't see any potential impact.  It would just make it so every parent could be a child.

I think there was 1 stipulation where a child couldn't be racked or something (would have to look at the errors generated) but I don't think it is a needed restriction.

**Comment by jeremystretch** [comment]
Ah, that's true, we do use it to restrict rackability.
