### ISSUE TITLE
Change default table configuration

### ISSUE THREAD

**Issue by TomGrozev** [netbox-community/netbox#5576]
### Environment
* Python version: 3.7.3
* NetBox version: 2.10.x

### Proposed Functionality
Be able to set in the admin panel the default table configuration for columns for all users. This would be on a per model basis, e.g. virtual machines could have a different configuration to vlans. If a user customises the column configuration it would override the default.

### Use Case
This would allow for a default view for new users without having to change the configuration. This is especially useful for custom fields in tables and hence closesly related to #5344 and #5460.

### Database Changes
This could be done with a new model but would be much more efficient to simply store an ordered list in the associated model for the default configuration. Due to the database change this would likely be a candidate for 2.11.

### External Dependencies
N/A

Also, I am happy to have this assigned to me.

**Comment by DanSheps** [comment]
If we went down this route, I would say it would be better to store the configuration in configuration.py.  I don't think it makes sense to make a database query for each page view with a table when the query itself would be rather static.

The problem is each table has different columns so it would need to be a list in a dict or similar for this to work (just off the top of my head).

That said, we already have enough on our plate so someone would have to volunteer to own this.

**Comment by jeremystretch** [comment]
IMO this exceeds the reasonable ratio for developer burden to user value. If you really need a way to set default views for new users, it seems like a custom script would work just fine.

**Comment by xkilian** [comment]
I would personally love to see this go forward, as it may be more burden for devs, but for dozens of users, each having to customize their views to match company documentation/traning material is a bit of a usability problem. As I am sure most companies will make use of custom fields for various needs and should/will want to make that data more accessible. I understand that a custom script could set these values for users, so there is a workaround. Thank you once again fro the excellent work.

**Comment by exc91** [comment]
Tell me please is this feature available in release Netbox 2.10.3? 
I already have installed Netbox 2.10.3 and it's really great product. But I didn't find how to make custom fields take a place to the table Devices with button Configure on a right top in my case...
