### ISSUE TITLE
Leading and trailing spaces ignored when renaming multiple interfaces

### ISSUE THREAD

**Issue by BapRx** [netbox-community/netbox#5577]
### Environment
* Python version: 3.6.9
* NetBox version: v2.7.4

### Steps to Reproduce
1. On a device view, select multiple interfaces
2. Click rename at the bottom of the page
3. Try replacing the regex "$" with the string " test"

### Expected Behavior
The text "example" should have been replaced by "example test"

### Observed Behavior
The text is replace by "exampletest", ignoring any leading and trailing spaces.

Example:
![Sans titre](https://user-images.githubusercontent.com/32563450/103631746-aab00e80-4f43-11eb-9a17-8ac3af25f508.png)

**Comment by DanSheps** [comment]
I have confirmed the behaviour, the BulkRenameForm field needs strip=False.

**Comment by DanSheps** [comment]
After some discussion, this was done intentionally to prevent extraneous whitespace.

**Comment by BapRx** [comment]
I didn't know about this parameter, thank you.

**Comment by DanSheps** [comment]
@BapRx Keep in mind any changes you make to the code will be on you to maintain, and we will not be supporting it.
