### ISSUE TITLE
API - (PUT or PATCH) /dcim/devices/

### ISSUE THREAD

**Issue by RomainGarel** [netbox-community/netbox#5582]
### Environment
* Python version: 3.6.8
* NetBox version: 2.10.2
* CentOS Linux release 8.2.2004

### Steps to Reproduce
1. using a existing "Device"
2. try to change a field value using PATCH method (for example the status)
3. Or simply using netbox API swagger

### Expected Behavior
With this request:
curl --location --request PATCH 'https://x.x.x.x/api/dcim/devices/' \
--header 'Authorization: Token xxxxxxxxx' \
--header 'Content-Type: application/json' \
--header 'Accept: application/json; indent=4' \
--data-raw ' {
    "name": "sr-nbi-ones-test",
    "device_type": 1,
    "device_role": 1,
    "site": 1,
    "status": "failed"
 }'
The status have to change to failed, but it's not working.
Same thing using swagger (see screenshot below).
I tried also using Postman and Ansible...

### Observed Behavior
Answer is always "400 Bad Resquest"
{
    "non_field_errors": [
        "Expected a list of items but got type \"dict\"."
    ]
}

**Comment by RomainGarel** [comment]
![ScreenShot131](https://user-images.githubusercontent.com/36295219/103772198-6434df80-5029-11eb-98bb-5167e96d50a6.jpg)

**Comment by lampwins** [comment]
You are sending a single object to the list endpoint `/api/dcim/devices/`. You have two options, use the bulk functionality of the list endpoint by sending your data as a JSON list that contains one object, or use the single object detail view for PUT/PATCH. This is done by appending the ID of the single object you want to work with to the URL: `/api/dcim/devices/123/`

**Comment by RomainGarel** [comment]
Oh... sorry...
Thanks for your answer
