### ISSUE TITLE
Custom field type boolean changelog representation change

### ISSUE THREAD

**Issue by cloos** [netbox-community/netbox#5585]
### Environment
* Python version: 3.6.9
* NetBox version: 2.10.3 (upgrade from 2.8.9)

### Steps to Reproduce
1. create a boolean custom field for virtual-machine in NetBox **before** 2.10.0
2. create a virtual-machine and set the boolean custom field value to True
3. upgrade NetBox to 2.10.3
4. go to the previously created virtual-machine, click `Edit` and then `Update` **without** making any changes

### Expected Behavior
No changelog record is created.
Or more correct a changelog record is created without showing a change, because currently NetBox still creates a changelog record even if nothing changed.

### Observed Behavior
A changelog record is created who shows a value change from `"True"` to `true`:

![NetBox_change_bool_cf](https://user-images.githubusercontent.com/165430/103805271-a5da8000-5053-11eb-9e68-9ff32529aff1.png)

So every time you change a object which has a boolean custom field assigned you get a unrelated change of the boolean custom field value.

This is a result of the Reimplementation of Custom Fields (#4878).

Maybe it is possible to avoid these changes.

**Comment by jeremystretch** [comment]
This happens because the old custom fields implementation stored booleans (and all other values) as strings, whereas the new one does not. The same behavior likely happens for integers as well. What fix would you propose?

**Comment by cloos** [comment]
I think one option to fix this is to update the records in the `extras_objectchange` table (convert custom field boolean values from string to bool), which maybe could result in a much longer upgrade for NetBox instances with many change records.

Another option would be to cast the custom field boolean values to bool in the WebUI and API when they are displayed or fetched.

But both options could have some side effects, because you can change the type of a custom field e.g. from text to bool, so if the type is now bool, this doesn't mean that all values should be presented as bool.
So I think there isn't much we can do here.

**Comment by jeremystretch** [comment]
It's not ideal but IMO the best option is to just let it be. Eventually it will no longer be an issue as expired change log data gets scrubbed.
