### ISSUE TITLE
Allow search of virtual-chassis using name or master

### ISSUE THREAD

**Issue by FragmentedPacket** [netbox-community/netbox#5586]
### Environment
* Python version: 3.6
* NetBox version: 2.9/2.10

### Proposed Functionality
Allow users to GET `/api/dcim/virtual-chassis` using `name` or `master`.

### Use Case
Since `name` is a required parameter, it would be nice to be able to search for the exact name or even `master` as well.

This would help find a VC that is more unique rather than falling back to the default `q` search.

https://github.com/netbox-community/netbox/blob/develop/netbox/dcim/filters.py#L1014

I can own the implementation as I spoke with @lampwins and he advised me where to look for the filtering.

**Comment by jeremystretch** [comment]
Please be sure to extend the filterset tests appropriately as well.
