### ISSUE TITLE
Show assigned VLAN in interfaces list

### ISSUE THREAD

**Issue by TigerEnteNBG** [netbox-community/netbox#5587]
### Environment
* Python version: 
* NetBox version: 2.10.3

### Proposed Functionality
Add a new field to the interfaces list showing the configured VLANs. Either the VLAN number or "Trunk"/"Tagged all"

### Use Case
You can see directly see the VLAN configuration.

### Database Changes
I think think thats needed, as its just a new display request.

**Comment by TigerEnteNBG** [comment]
I think about something similar to what you can see in cisco switches:
e.g.
```
Switch#show interfaces status

Port    Name               Status       Vlan       Duplex  Speed Type
Fa0/1   PC1                connected    1          a-full  a-100 10/100BaseTX
Fa0/2   Printer-B2         connected    2          a-full  a-100 10/100BaseTX
Fa0/3                      notconnect   1            auto   auto 10/100BaseTX
Fa0/4                      notconnect   7            auto   auto 10/100BaseTX
Fa0/5   Backup             notconnect   1            auto   auto 10/100BaseTX
```

**Comment by jeremystretch** [comment]
You can toggle the tagged and untagged VLAN table columns by clicking the "Configure" button at top right.

**Comment by TigerEnteNBG** [comment]
Perfect! Thanks for the hint.
Any change to edit the default columns for everybody?

**Comment by jeremystretch** [comment]
No, but see #5576
