### ISSUE TITLE
Modular PDU nested utilization/calculation does not work

### ISSUE THREAD

**Issue by fggec** [netbox-community/netbox#5590]
### Environment
* Python version: 3.8.6
* NetBox version: v2.9.8

### Steps to Reproduce
1. Create PDU parent device with some power outlets and assign a feed to the power port
2. create PDU module as child device with some ports like C19 or something and connect it to one power outlet of the parent PDU
3. connect an device with an allocated and maximum draw as known.

### Expected Behavior
the draw from the power port of the module/child should be nested calculated to the parent device so that we could see the current utilization on the parent PDU 

### Observed Behavior
the utilization was not calculated by itself. We had to manually calculate the utilization  and edit the current allocation of the module.

**Comment by jeremystretch** [comment]
PDU modules should not be modeled as child devices. Child devices are fully autonomous entities (e.g. blade servers). You can use inventory items to represent modules within a PDU, but the power ports and outlets must be assigned to the device itself.
