### ISSUE TITLE
Add ability to remove a device type image

### ISSUE THREAD

**Issue by thefreakquency** [netbox-community/netbox#5595]
### Environment
* Python version: 3.8.5
* NetBox version: 2.10.2

### Proposed Functionality
When someone uploaded a wrong image to a device type, there is no apparent way to remove it. Adding a "delete" button would be beneficial without requiring any major back-end changes. 

### Use Case
Someone uploads a wrong image and does not have a better one to replace it with...

**Comment by chuegel** [comment]
This would be nice indeed.

**Comment by k0ste** [comment]
I think we definetly should have ability to delete images...🙄
![Screen Shot 2021-03-09 at 14 46 46](https://user-images.githubusercontent.com/7759548/110466112-5ad9f900-80e6-11eb-8f4c-79120d93c402.png)

**Comment by jeremystretch** [comment]
Looks like this was a regression introduced by 00ca2272925118d33d8925f28a761c55589af0b3 (#5433)
