### ISSUE TITLE
White cables are invisible on cable trace

### ISSUE THREAD

**Issue by Epaphus** [netbox-community/netbox#5603]
### Environment
* Python version: 3.6.8
* NetBox version: 2.10.3

### Steps to Reproduce
1. Have a cable with the colour white
2. View trace of cable

### Expected Behavior
A border or similar around the cable to make it clearer it was a white cable rather than no cable.

### Observed Behavior
Cable connection within a cable trace is invisible when compared with other coloured cable due to a white cable on a white background

![image](https://user-images.githubusercontent.com/720274/104170223-afb80680-53f8-11eb-94cf-8ebf449d4a5d.png)

![image](https://user-images.githubusercontent.com/720274/104170308-d4ac7980-53f8-11eb-940f-03f8eacef6af.png)

**Comment by cpmills1975** [comment]
I've raised a PR for this - hope this is acceptable?

![Screenshot 2021-01-21 at 00 48 55](https://user-images.githubusercontent.com/1878544/105258851-87f83980-5b82-11eb-94da-47e53a7d8903.png)
