### ISSUE TITLE
About IPV6 Subnet  In IPAM-Prefixes

### ISSUE THREAD

**Issue by ixinshang** [netbox-community/netbox#5604]
### Environment
* Python version: Python 3.9.1
* NetBox version: 33e7912c70d3 (v2.10.3) (latest docker image)

### Steps to Reproduce
In IPAM→Prefixes，I add a ipv6 Prefixes,like 1424:876C:C0:171::/72,i choose "1424:876C:C0:171::/72", add a Child Prefixes（/76：1424:876C:C0:171::/76）.
### Expected Behavior
So there are some Prefixes that is available,like this.
![Prefixes-1](https://user-images.githubusercontent.com/10056396/104200273-69e45800-5463-11eb-8fa9-28196ae74324.png)
But there is not entire avialable IPV6 from the list.

### Observed Behavior
![Prefixes-1](https://user-images.githubusercontent.com/10056396/104200273-69e45800-5463-11eb-8fa9-28196ae74324.png)
![3P5aBcpO4i1ymY4.jpg](https://i.loli.net/2021/01/11/e9QNOBfMY2j5SZc.jpg)
But there is not entire avialable IPV6 from the list.

So,i want to have a Child Prefixes list to show all available IPs to choose witch to use. like phpipam. Is there a way to slove it。
![ipam-1](https://user-images.githubusercontent.com/10056396/104200863-18889880-5464-11eb-9a43-0803bd8c1043.png)
Sorry for my poor english.
finally, thanks.

**Comment by ixinshang** [comment]
add a picture.
![0844k7qgnSk7bFD.jpg](https://i.loli.net/2021/01/11/aLBxfYSvMNwVy6s.jpg)

**Comment by jeremystretch** [comment]
This issue is pending closure as it does not conform to one of the [provided templates](https://github.com/netbox-community/netbox/issues/new/choose) as required by the [contributing guide](https://github.com/netbox-community/netbox/blob/master/CONTRIBUTING.md). If you'd like to request that your issue be re-opened, please first update the content so that it matches the appropriate template (this may require rewriting your issue entirely).

**Comment by ixinshang** [comment]
> This issue is pending closure as it does not conform to one of the [provided templates](https://github.com/netbox-community/netbox/issues/new/choose) as required by the [contributing guide](https://github.com/netbox-community/netbox/blob/master/CONTRIBUTING.md). If you'd like to request that your issue be re-opened, please first update the content so that it matches the appropriate template (this may require rewriting your issue entirely).

Thanks,i rewrite it.

**Comment by ixinshang** [comment]
i found the problems.  let me have a try.

**Comment by ixinshang** [comment]
I understood it wrong.
thanks all
