### ISSUE TITLE
Devices overview, sort on ip address breaks

### ISSUE THREAD

**Issue by maartenbollen** [netbox-community/netbox#5605]
### Environment
* Python version: 3.6.8
* NetBox version: 2.10.3

### Steps to Reproduce
1. Click on devices
2. Click on ip address table header 

### Expected Behavior
That it sorts on ip address

### Observed Behavior
<class 'django.core.exceptions.FieldError'>

Cannot resolve keyword 'primary_ip' into field. Choices are: _name, asset_tag, cluster, cluster_id, comments, consoleports, consoleserverports, created, custom_field_data, device_role, device_role_id, device_type, device_type_id, devicebays, face, frontports, id, images, interfaces, inventoryitems, last_updated, local_context_data, name, parent_bay, platform, platform_id, position, poweroutlets, powerports, primary_ip4, primary_ip4_id, primary_ip6, primary_ip6_id, rack, rack_id, rearports, secrets, serial, services, site, site_id, status, tagged_items, tags, tenant, tenant_id, vc_master_for, vc_position, vc_priority, virtual_chassis, virtual_chassis_id

**Comment by jeremystretch** [comment]
Thank you for submitting this issue, however it appears that this topic has already been raised. Please see issue #5597 for further discussion.
