### ISSUE TITLE
Add TERA to port types

### ISSUE THREAD

**Issue by phoerious** [netbox-community/netbox#5612]
### Environment
* Python version: 3.8
* NetBox version: 2.10

### Proposed Functionality
Ports should be configurable as TERA under the "Copper" section. At the moment, I can only select 8P8C, which doesn't even exist for Cat7 (technically it's GG45, which is only backwards-compatible to 8P8C).

### Use Case
Cat7 cabling with TERA connectors.

### Database Changes
New port type.

### External Dependencies
None

**Comment by DanSheps** [comment]
Are you willing to submit a PR for this?

**Comment by phoerious** [comment]
Are you willing to accept one? And do you think it would make sense to add a connector type also to interfaces and not just ports?
