### ISSUE TITLE
Napalm installed but Netbox states "NAPALM is not installed"

### ISSUE THREAD

**Issue by dd1245** [netbox-community/netbox#5613]
* Environment: 18.04.5 LTS 
* Python version: Python 3.6.9 
* NetBox version: NetBox 2.10.3

I cannot seem to get Netbox to use Napalm for gathering device information. 

1. I've configured the NAPALM variables in  configuration.py
2. Setup a platform which the correct Napalm driver. 
3. Created a device with this platform and a primary IP address
4. I can see Napalm is installed (which was via pip3) and I can see the napalm modules listed as available in nbshell. 
5. Ensured that SSH to the device is possible from the Netbox server
 
However, when I click 'status' under devices I see

![image](https://user-images.githubusercontent.com/43221896/104332560-3697dc80-54e8-11eb-92e7-59cc2cda8f63.png)

I get a similar issue on the API

![image](https://user-images.githubusercontent.com/43221896/104332640-4ca59d00-54e8-11eb-8afa-bf1a2852c262.png)

### Steps to Reproduce
1. Click on a device 
2. Click on the status tab

### Expected outcome
Information to be pulled via Napalm.

### Actual result
Error message about Napalm not being installed.

I can't see anything in the Netbox documentation that would suggest Napalm specifically needs enabling anywhere else.

**Comment by DanSheps** [comment]
Thank you for your interest in NetBox. GitHub issues are intended for reporting reproducible bugs and requesting features, and must be submitted using one of the templates provided [here](https://github.com/netbox-community/netbox/issues/new/choose). For general discussion, questions, or assistance with installation issues, please post to the [discussions](https://github.com/netbox-community/netbox/discussions) instead.

**Comment by dd1245** [comment]
Hi. I did use the template you mentioned, apologies If I missed something?
