### ISSUE TITLE
Expose DynamicModelChoiceField to plugin developers

### ISSUE THREAD

**Issue by MajesticFalcon** [netbox-community/netbox#5624]
### Environment
* Python version: 3.8
* NetBox version: 2.10

### Proposed Functionality
As of now, plugins don't seem to be able to import DynamicModelChoiceField to gain the searchable select box. I proposed exposing this functionality as it would greatly increase the user experience of the plugins. 

### Use Case

Plugins that have an address foreign key. The issue becomes either use a searchable select or jump the user between multiple pages to "link" an address. 

### Database Changes

None known.

### External Dependencies

None known

**Comment by lampwins** [comment]
The DynamicModelChoiceField and its siblings underwent a total rewrite not long ago which helped to make the implementation both easier to work with and more stable. I support this being included in the plugins API because it promotes consistent user experiences which ultimately makes end-users happier with NetBox. It does raise a larger question though, of what the process actually looks like to formally expose existing core components to the plugins API?

**Comment by jeremystretch** [comment]
DynamicModelChoiceField is not mature or stable enough for use outside of NetBox core. However, you can certainly replicate its functionality within your plugin.

> It does raise a larger question though, of what the process actually looks like to formally expose existing core components to the plugins API?

That's a question we can ponder once we've worked through the years-long backlog of pending core feature requests. Let's not let the plugins API distract from work on the core product.

**Comment by MajesticFalcon** [comment]
Fair enough. I am still familiarizing myself with the plugin ecosystem. Would you agree that this functionality could be written as a plugin itself and then re-used by other plugins? Or is there some technical barrier preventing such latching between plugins?

**Comment by jeremystretch** [comment]
> Would you agree that this functionality could be written as a plugin itself and then re-used by other plugins?

It wouldn't even need to be a plugin; a Python package would be sufficient.

**Comment by ledgley** [comment]
@MajesticFalcon try this and see if it does what you need
```python
software = DynamicModelChoiceField(
    queryset=Software.objects.all(),
    required=True,
    widget=APISelect(
        api_url='/api/plugins/software/software/'
    ),
    query_params={
        'manufacturer': '$manufacturer'
    }
)
```

**Comment by MajesticFalcon** [comment]
> @MajesticFalcon try this and see if it does what you need
> 
> ```python
> software = DynamicModelChoiceField(
>     queryset=Software.objects.all(),
>     required=True,
>     widget=APISelect(
>         api_url='/api/plugins/software/software/'
>     ),
>     query_params={
>         'manufacturer': '$manufacturer'
>     }
> )
> ```

The API endpoint works but the dynamicchoicefield stays blank. In debug, I can see the correct API endpoint being hit, but the box stays empty

**Comment by MajesticFalcon** [comment]
Looks like all I needed to do was add "display_field." Thank you so much!
