### ISSUE TITLE
Request to add QSFP+ (64GFC) interface type option

### ISSUE THREAD

**Issue by lastwednesday** [netbox-community/netbox#5630]
### Environment
* Python version: 3.8.3
* NetBox version: 2.10.3

### Proposed Functionality
Request is to add the "QSFP+ (64GFC)" interface type as an option.

### Use Case
These interface types are used for Inter-Chassis Link connections for the Brocade DCX SAN directors.
These are 4x16G FC bundled adapters, like the QSFP28 (128GFC) are for 4x32G FC ones which are available in the application.
Here is an example of the part number and description:
57-0000090-01 | QSFP+ SWL 4x16G FC (64G)

### Database Changes
I don't believe this should require database changes.

### External Dependencies
None

**Comment by DanSheps** [comment]
Would you be willing to create a PR for this?

**Comment by lastwednesday** [comment]
> Would you be willing to create a PR for this?

I'd be happy to. In discussion with my data center folks, they'd also like to add cabling options to distinguish OM3/OM4 LC vs MPO if that would be appropriate, as currently there's just a cable type option for OM3 and OM4 themselves. The "LC" cables are used for most of our Fibre Channel cabling, and the "MPO" ones are for the Inter-Chassis Links.

Proposal would be to add in also:
OM3 LC
OM3 MPO
OM4 LC
OM4 MPO

**Comment by ryanmerolle** [comment]
@lastwednesday cable endpoints are not yet tracked by netbox.  I think we should separate that into another feature request to discuss implications.  

Its not that big of a controversy, but would require keeping the generic types as to not impact people who currently use those cable types.  We should just split it out and discuss.

**Comment by lastwednesday** [comment]
@DanSheps You can add me as an owner to this feature request. I have a fork which can include this new interface type.

**Comment by DanSheps** [comment]
Done, thanks for volunteering!
