### ISSUE TITLE
Display virtual interfaces with a different background color

### ISSUE THREAD

**Issue by hoalex** [netbox-community/netbox#5635]
### Environment
* Python version: 3.6.8
* NetBox version: 2.10.2

### Proposed Functionality
Display virtual interfaces on a device's interface table with a different background color (e.g. yellow).

### Use Case
With the new look in Netbox 2.10, virtual interfaces can only be distinguished from physical interfaces by looking at the "Type" column.
On Netbox versions < 2.10, virtual interfaces ("Virtual", "LAG") were shown with a yellow background in a device's interface list. This made it easy to quickly distinguish virtual from physical interfaces, which was especially useful since virtual interfaces may have names that put them in between other physical interfaces. It would be nice to keep this functionality in the future.

### Database Changes
None

### External Dependencies
None

**Comment by lampwins** [comment]
On the one hand, this might be considered a regression, but on the other, the interfaces table has historically been extremely complicated to render. With the refactor of all component tables, this might have actually been intended to reduce the complexity of the template.

**Comment by cpmills1975** [comment]
For what it is worth, I preferred the previous (extremely complicated) interfaces table, although I absolutely understand the desire to move towards a common table model across all component types. Would it be possible to compromise and as the OP requests, show virtual interfaces in a different color?

**Comment by jeremystretch** [comment]
Device components no longer use separate HTML templates; they are rendered using Table classes (from django-tables2). I'll mark this as "needs owner" for anyone who wants to take a shot at it, but please bear in mind that any acceptable solution must be succinct and highly maintainable (no hacking on the table classes, please).

**Comment by cpmills1975** [comment]
I've had a look through the CSS classes and can see that the background colour of the row matches the colour of the cable status - green (success) for 'connected', yellow (warning) for decommissioning and blue (info) for planned.

I recall virtual interfaces were coloured yellow in earlier versions of netbox but of course that would now clash with decommissioning.

Sticking with the bootstrap colour scheme, would there be any mileage in changing rows with cables set to decommissioning to red (danger) and using yellow (warning) for virtual interface rows? Would the colour of the label for decommissioning need to also change to red or would it be acceptable to keep the label yellow but have the rows red? As far as I can see, red isn't currently used for any other cable status, but other areas of the UX use yellow for decommissioning and red for more problematic statuses - failed etc.
