### ISSUE TITLE
Webhook support for tags

### ISSUE THREAD

**Issue by vash666** [netbox-community/netbox#5638]
### Environment
* Python version: 3.6.8
* NetBox version: 2.10.3

### Proposed Functionality
Add webhook support for tags creation, update or delete in GUI **Organization > tags**

### Use Case
Notify via webhook to an external application anytime a tag is added, updated or deleted.

### External Dependencies

**Comment by lampwins** [comment]
There are a couple of other "extras" models that don't support webhooks today, like config contexts. If we were to do this (which I support), I think we should also do it for those other models for which it makes sense.

**Comment by jeremystretch** [comment]
> Notify via webhook to an external application anytime a tag is added, updated or deleted.

That's the raw functionality this would enable, but what is your underlying use case?

**Comment by sdktr** [comment]
if a tag would change (it's name for example), should the related entities that point to this tag all get a change signal (webhook/last_change date update etc) as well?

**Comment by vash666** [comment]
> > Notify via webhook to an external application anytime a tag is added, updated or deleted.
> 
> That's the raw functionality this would enable, but what is your underlying use case?

I need to create host templates based on tags on my network monitoring system via API that's why webhooks will be very useful.

**Comment by jeremystretch** [comment]
But why would you need a webhook when a tag itself changes?

**Comment by vash666** [comment]
> But why would you need a webhook when a tag itself changes?

I was thinking this use case to rename the template when the Nerbox event is "updated" on the tag and create the template if the event is "created".

**Comment by jeremystretch** [comment]
IIRC this is covered under some of the v2.12 standardization work but I need to dig into it.
