### ISSUE TITLE
Filter device components by label

### ISSUE THREAD

**Issue by bcohee** [netbox-community/netbox#5641]
### Environment
* Python version: 3.8
* NetBox version: 2.10.1

### Proposed Functionality

Does not appear to be able to search Interfaces via Label field

### Use Case

List Interfaces via Label field

### Database Changes

None

### External Dependencies

None

**Comment by jeremystretch** [comment]
Searching interfaces (and other device components) by their label values is already supported.

**Comment by bcohee** [comment]
@jeremystretch - I do not seem to be able to search interfaces via Label field from the UI.  Have tried URL param queries as well.  Am I missing it somewhere?   https://netboxdemo.com/dcim/interfaces/?q=&label=te&sort=-label

**Comment by jeremystretch** [comment]
The way your request is worded it sounded like you want the search functionality to match on the label field, which it does. Are you asking instead for a separate filter?

**Comment by bcohee** [comment]
Yes, looking to filter Interfaces by Label on the /dcim/interfaces UI.
