### ISSUE TITLE
Bulk edit of virtual interfaces: no VLANS available to select

### ISSUE THREAD

**Issue by ziggekatten** [netbox-community/netbox#5643]
### Environment
* Python version: Running Docker version
* NetBox version: 2.10.3

### Steps to Reproduce
1. Log in as a normal user or super user
2. Create a site

![image](https://user-images.githubusercontent.com/55629049/105250296-cccba280-5b79-11eb-9097-8cf70e52b270.png)

3. Create a VLAN group and assign to site
![image](https://user-images.githubusercontent.com/55629049/105250382-ee2c8e80-5b79-11eb-966f-6bb05dd704ab.png)

4. Create two VLANs and assign to VLAN group
![image](https://user-images.githubusercontent.com/55629049/105250423-ff759b00-5b79-11eb-8947-ceaa3ee12fc9.png)

5. Cretae a new Cluster and assign to site above
![image](https://user-images.githubusercontent.com/55629049/105250467-14eac500-5b7a-11eb-84d1-70a9950b3322.png)

6. Create two VMs and assign to cluster
![image](https://user-images.githubusercontent.com/55629049/105250530-36e44780-5b7a-11eb-942e-7237daf559e6.png)

7. Add a interface to the vms
![image](https://user-images.githubusercontent.com/55629049/105250611-57ac9d00-5b7a-11eb-826e-f3004f669792.png)

8. Select "Virtualization->Interfaces
9.  tick one or more interfaces
10.  click "edit selected"
11. Set mode to "Access" (or tagged, does not matter
12. Click on "Untagged VLAN" dropdown

### Expected Behavior
Dropdown with a list of my VLANS to be selected

### Observed Behavior
"No results found" in the dropdown. 
![image](https://user-images.githubusercontent.com/55629049/105097203-84907f80-5aa8-11eb-9154-6dfddd44e178.png)

adding an VLAN to a interface by klicking on the VM, then on interface works. Bulk edit is not working

**Comment by jeremystretch** [comment]
Your provided "steps to reproduce" are incomplete. Please detail what VLANs you are creating beforehand and whether they are assigned to sites and/or groups.

**Comment by ziggekatten** [comment]
Updated and added images

**Comment by ziggekatten** [comment]
I have updated to 2.10.4 and the issue persists

**Comment by ziggekatten** [comment]
Bumping this, as it's still an issue in 2.10.6. 

Is there some additional info needed for this to be classified as a bug?

**Comment by jeremystretch** [comment]
Related to #4523
