### ISSUE TITLE
Interfaces tab on VC master shows count of only local interfaces

### ISSUE THREAD

**Issue by cpmills1975** [netbox-community/netbox#5648]
### Environment
* Python version: 2.10.3
* NetBox version: 3.9

### Steps to Reproduce
1. Create two devices with a bunch of interfaces
2. Create a new virtual chassis and add the two devices
3. Inspect the interfaces tab on the VC master - the count shows only the local ports while the table shows all the vc member ports

### Expected Behavior
Either:
* The interface count includes all the interfaces in the virtual chassis, as the table does -or-
* A better way to show local vs chassis member interfaces is needed - perhaps two tables, one showing local interfaces and a second table showing interfaces on other connected virtual chassis members?

To be clear, I don't want to lose the functionality of being able to see all interfaces on the master member somewhere.

### Observed Behavior
The count of interfaces shows the local interfaces while the table shows all interfaces across all connected members.

**Comment by DanSheps** [comment]
I am not sure if this should be a bug or a feature request.

It isn't a bug in that it is correctly listing the count of local interfaces, but since we do list all VC interfaces on the master it is kind of a bug.  Perhaps we need a new view of "VC Interfaces" that comes up just on the master.

**Comment by cpmills1975** [comment]
A view of VC interfaces would work for me I think and would allow the user to differentiate between the interfaces physically present on the master and those that are only logically present on the master.

Question of usability though and something I'd be keen for other users to chime in on, does the VC interfaces view include both the physical ones present on the master AND the interfaces present on other members or just those present on other members?

Could the VC interfaces tab be present on all members of the virtual chassis since all members are technically part of the same managed entity?

Should the interfaces tab show a count of all interfaces across the entire virtual chassis and then break the list in to two tables? Those physically present on this member and those defined on other members? This idea wouldn't have worked well when all interfaces were shown on the one device page, but perhaps now we have a separate page for interfaces there is more space to play with? I think this would be my preferred option. I guess this makes the JS filter box less useful, but I can't get that working anyway!

The big issue here for me at present is that the table might show 480 odd interfaces (assuming a 10 member JunOS VC) but the number on the tab will show 48. It doesn't matter how it's spun, this is misleading.

**Comment by jeremystretch** [comment]
Calling it a bug simply because the number on the tab doesn't match the number of objects in the table.
