### ISSUE TITLE
Document examples of the (Javascript based) interface filter

### ISSUE THREAD

**Issue by cpmills1975** [netbox-community/netbox#5649]
### Change Type
[x] Addition
[ ] Correction
[ ] Deprecation
[ ] Cleanup (formatting, typos, etc.)

### Area
[ ] Installation instructions
[ ] Configuration parameters
[x] Functionality/features
[ ] REST API
[ ] Administration/development
[ ] Other

### Proposed Changes
The regular expression based filter that now appears in the interface tables is not mentioned (as far as I can see) in the documentation. I've tried different search strings in the field and cannot get it to output the list of interfaces I'd expect. Some examples in the documentation would be helpful.

**Comment by jeremystretch** [comment]
@cpmills1975 assigning this to you if you'd like to submit a PR.

**Comment by cpmills1975** [comment]
Would happily write some words @jeremystretch, if I knew how to get it working! See my call for help via discussion item https://github.com/netbox-community/netbox/discussions/5647.

**Comment by jeremystretch** [comment]
@cpmills1975 have you made any progress on this? If not, I'd like to open it back up for volunteers.

**Comment by jeremystretch** [comment]
Going to close this out as it hasn't drawn any interest.
