### ISSUE TITLE
Cable length calculation incorrect when segment lengths are missing

### ISSUE THREAD

**Issue by cpmills1975** [netbox-community/netbox#5650]
### Environment
* Python version: 2.10.3
* NetBox version: 3.9

### Steps to Reproduce
1. Create two devices
2. Create two 'patch panel' devices with front and rear ports
3. Connect the rear ports of the patch panels without specifying the length
4. Connect the two devices to each of the patch panels and specify the length in one or both
5. Trace the cable between the devices

### Expected Behavior
Ideally, the total length should indicate that it is 'at least' n meters long or in some better way indicate that only some of the lengths were populated and therefore the calculated length is somewhat short of the actual.

### Observed Behavior
With only some of the cable lengths specified - perhaps the patch cables between the patch panels and the devices and not the length of the horizontal cable between the patch panels, NetBox outputs a calculated length which is the correct sum of the lengths that it has available in the database. This is obviously incorrect due to missing data, but no indication of this is given to the user who might (not unreasonably) think that the total length as calculated by NetBox is correct.

**Comment by jeremystretch** [comment]
I'm on the fence as to whether this should be considered a bug: NetBox is returning the correct data as far as it knows. I can also imagine a scenario where the user wants to ignore the length of particular cables for some reason.

I'll tag this as "needs owner" for anyone who wants to volunteer.

**Comment by cpmills1975** [comment]
Hi @jeremystretch,

Hope I'm not treading on toes here, but I've raised a PR which I hope addresses this in an appropriate way. If all cables have a length, the display is as current. If not, I prefix the length with a > to indicate that it is 'at least' the length given.
