### ISSUE TITLE
Provide a configuration option to include inventory items in the global search

### ISSUE THREAD

**Issue by cpmills1975** [netbox-community/netbox#5651]
### Environment
* Python version: 3.9
* NetBox version: 2.10.3

### Proposed Functionality
I know that inventory items are explicitly excluded from the global search for efficiency reasons. However, this needs to be balanced with usability and, as a relatively light user of inventory items, I'd like to be able to try and see if adding these in to the global search negatively impacts the speed of the search or not.

Some users will use inventory items extensively and forcing the search to include these may negatively impact the search experience. I do not (4000 odd devices, at the moment maybe <100 inventory items across the entire estate - I am not yet recording every single line card or every single Hard Disk in every single device!).

I'd like the option, through the configuration to globally include or exclude inventory items from the main search.

### Use Case
The only inventory items I have recorded so far are high value line cards that are individually asset labelled - I'd like to be able to search for an asset tag regardless of whether it is a device or an inventory item through the main search form and (assuming I know nothing about an asset tag) not have to search for it twice - once in the main search form or the devices page and again in the inventory items page.

### Database Changes
None

### External Dependencies
None

**Comment by jeremystretch** [comment]
It would not be prudent to introduce a configuration parameter for such a niche change in behavior, especially to deliver relatively little value. (That's how you end up with a thousand little knobs and switches that are nearly impossible to maintain over time.)

A better approach might be to improve the global search form to allow the selection of a subset of models, with the currently available models serving as defaults, and extend it to support inventory items and other models. However, this would need to be fleshed out in a separate FR.
