### ISSUE TITLE
Support of software installations with secrets

### ISSUE THREAD

**Issue by Peter2121** [netbox-community/netbox#5653]
### Environment
* Python version: 3.7
* NetBox version: 2.9.11

### Proposed Functionality
Actually, the secrets are related to devices. It seems that in 2.10 version the support was extended to VMs. But conceptually, neither devices itself nor VMs do not support secrets, the secrets are related to some software, installed on devices/VMs. For example, in case of network switch it would be a firmware, in case of a server it would be an operating system.
I propose to add two concepts in Netbox - _software_ (a dictionary) and _installations_ (related to devices and VMs). The secrets should not be related to devices and VMs, but to installations (for the compatibility with the actual versions - the support of secrets could be just extended to installations).
On the side of devices/VMs the installations should be processed at the same manner that interfaces are actually processed - one could add several installations to any device/VM, the type of installation (software) should be searched in a pre-defined list of available software. Any software can have a list of parameters (version etc.) and one could assign several parameters (related to the software) and secrets (for example, different user/password pairs) to any installation. The support of custom fields for both software and installations would be nice too.

### Use Case
Different versions of switch firmware support different features. It would be great to be able to search in a sub-network all switches with firmware version larger than X.X.
A VM can have different software installed, with user/password pairs related to the installed software and not VM itself. For example, MySQL installed on Debian Linux - there are two accounts 'root' with different passwords, related to two different installations of different software. Even more, one could have multiple instances of MySQL on the same VM, with the same login 'root' and different passwords. It would be great to be able to search the information like this at the simple manner.

### Database Changes
Probably, at least two additional tables should be created - 'installation' and 'software'. In case of tracking of software editors as a dictionary (it would be better) - there is a third table 'editors'. 

### External Dependencies
Probably, not.

**Comment by ryanmerolle** [comment]
It has been at least said in chat that longer term secrets moving to a plugin(ie removed from core) since the majority of users leverage third party services like Ansible Vault, CyberArk, Hashicorp Vault, and etc. for secret/password management.  Besides the slight tweak of extending to virtual_devices (which is basically the same as devices), I do not see this feature getting added.

**Comment by jeremystretch** [comment]
FYI #5278 details the use case for porting the secrets app to a plugin.

**Comment by Peter2121** [comment]
I don't see any conflict between a proposal of moving secrets to a plugin and my proposal. Does not matter - how the secrets are implemented (even better if they are implemented using Vault as an external storage). The key point is that we need to attach secrets to installations and not to hardware. That's why I proposed to implement these new objects.

**Comment by jeremystretch** [comment]
@Peter2121 as @ryanmerolle suggested I'm afraid we won't be undertaking any feature requests relating to secrets in the near future. If this is functionality you require, I encourage you to create your own plugin to support it.

**Comment by Peter2121** [comment]
@jeremystretch yes, it was my error - mention 'secrets' in the title :)
Once again, this proposal is not directly related to secrets. Even if I create an external plugin to manage secrets - I have no objects of type 'installation' to attach my secrets. And even if I create a plugin to manage software/installations - I cannot show this information _as a part_ of VMs/devices car plugins cannot modify models of the core objects. So, basically, my proposal concerns the extension of VMs/devices models to include there the object of type 'installation'.

**Comment by jeremystretch** [comment]
> I cannot show this information as a part of VMs/devices car plugins cannot modify models of the core objects.

No, but you can certainly reference them. I encourage you to read the [plugins documentation](https://netbox.readthedocs.io/en/stable/plugins/development/) to see what's possible. At any rate, managing the particular software packages installed on a particular device/VM would be out of scope for NetBox core anyway, so you would need to write a plugin or fork.
