### ISSUE TITLE
Make devices better to navigate from the rack view displaying the name of the device on top of the image

### ISSUE THREAD

**Issue by KobesM** [netbox-community/netbox#5657]
### Environment
* Python version: 3.8.3
* NetBox version: 2.10.3

### Proposed Functionality
When using images for devices, if you look at the rack layout the name of the device is not displayed on the device like when not showing the images.

I would propose the functionality to display the name of the device on top of the image to make it easier to navigate to devices when using images. For those that do not like to display the name of the devices when using images it should be posible to togle this using a button like the "Show Images" button.

### Use Case
As a user of netbox i can't see straight away which device is which when looking at the rack layout. Especialy when having a lot of the same devices next to eachother. I now have to hover with my mouse pointer over the front of the device to see the name of the object. When the name of the device is displayed on top of the image it will be easier to identify the different devices from eachother.

### Database Changes
None

### External Dependencies
???

**Comment by jeremystretch** [comment]
Thank you for submitting this issue, however it appears that this topic has already been raised. Please see issue #4317 for further discussion.

**Comment by KobesM** [comment]
Hello @jeremystretch, I see the issue #4317 has been closed due to inactivity.

We have used OpenDCIM for some time to manage our datacenter infrastructure. In this application they use a white overlay (maybe with a small black edge), which is good to read most of the time, and to my opinion makes identifying equipement at the rack view a lot better when using images. Yes, I know it is not always perfect since you can't predict the collor of the image used for the device, but I gues it will cover most of the cases.

See the folling image displaying an example from OpenDCIM's implementation:
![DCIM](https://user-images.githubusercontent.com/43916576/105231745-9edd6280-5b67-11eb-8509-6603a1026e49.png)
