### ISSUE TITLE
Rack assigned to rack-group and site, which does not contain that rack-group

### ISSUE THREAD

**Issue by lucker7777** [netbox-community/netbox#5665]
### Environment
* Python version: Python 3.9.1
* NetBox version: 2.10.3

### Steps to Reproduce
1. Click on "Add" in Racks page
2. In "Add a new rack" page, **first** choose "Group"
3. Next, choose a "Site", but choose a site, which does not contain group from the previous step
4. Add a rack name and click "Create"
5. Now you have a rack located in a wrong site, which does not contain chosen RackGroup

### Expected Behavior
I expect Netbox to not allow me to assign a rack to a wrong site.
For example, if you first choose "Site" in the "Add a new rack" page, then Netbox will filter other "Group" options.

### Observed Behavior
Netbox will create the rack with wrong site

![image](https://user-images.githubusercontent.com/8921396/105372990-79ebfc80-5c06-11eb-8ae4-781d8441d86c.png)
![image](https://user-images.githubusercontent.com/8921396/105373079-9425da80-5c06-11eb-9684-7df79358eaa8.png)

**Comment by DanSheps** [comment]
Related: #5311

**Comment by lucker7777** [comment]
Hello,
can anybody estimate the complexity of the fix to this bug? Can this be fixed in a release or two?
I am a SW engineer at a university and we are currently trying to migrate the data from proprietary SW to Netbox and this bug can cause a lot of troubles as our staff is not accustomed to Netbox (or a similar SW), so they could produce a lot of inconsistencies between Sites and RackGroups.

Thanks.

**Comment by DanSheps** [comment]
There are a lot of issues with site/rack/device consistency as far as checking, however one way to handle this would be a custom script that will validate the status of the data in netbox to see if it is consistent or not.

**Comment by lucker7777** [comment]
Thank you all for a quick response and a quick fix :)
