### ISSUE TITLE
Insecure SECRET_KEY generated by generate_secret_key.py

### ISSUE THREAD

**Issue by Alef-Burzmali** [netbox-community/netbox#5676]
### Environment
* Python version: 3.6+
* NetBox version: 2.10.3

### Steps to Reproduce
1. Use generate_secret_key.py to generate a random key
2. Observe the randomness of the result

### Expected Behavior
The generated key is a string of 50 characters chosen randomly among the 76 characters (76^50 = 10^94 combinations).

### Observed Behavior
The generated key is a 50-char-long permutation of the 76 characters of the charset (76 choose 50 = 10^20 possibilities). You can see that no characters are used more than once, e.g.: `gN-DOwkFbQ1Bur89Tlza0v!=#y63U)os2%C_HZdP74IM+cmA5L`

The script should use [random.choices](https://docs.python.org/3/library/random.html#random.choices) instead of [random.sample](https://docs.python.org/3/library/random.html#random.sample). Furthermore, as Netbox already depends on Python3.6, it would be even better to use [secrets.choice](https://docs.python.org/3/library/secrets.html#secrets.choice) instead and avoid SystemRandom.

I understand that this script is only used once (as mentioned in #1092). However, the secrets it generates are currently well within bruteforce territory and are insecure. I suppose it could be abused to steal a session or a user account (based on Django's doc) and I would recommend changing it in current deployments (if it is feasible), if the key was generated with this script during the installation.

**Comment by DanSheps** [comment]
Do you have more information on this supposed weakness?

I will admit my python cryptography is weak but I don't see any issue with using sample over choices according to their documentation.
