### ISSUE TITLE
Bulk import custom fields

### ISSUE THREAD

**Issue by rikigst** [netbox-community/netbox#568]
I'd like the possibility, one some custom fields are defined, to have them importable in bulk.

**Comment by candlerb** [comment]
Example use case:

I have added a custom field "FQDN" to the "ipam > IP Address" model. I'm importing a load of IP addresses in CSV format, and I want to import the corresponding FQDNs at the same time.

**Comment by paravoid** [comment]
I had the same need for the DCIM/Device model. I very naively did:
```diff
--- a/netbox/dcim/forms.py
+++ b/netbox/dcim/forms.py
@@ -777,7 +777,7 @@ class DeviceForm(BootstrapMixin, TenancyForm, CustomFieldForm):
             self.initial['rack'] = self.instance.parent_bay.device.rack_id
 
 
-class BaseDeviceCSVForm(forms.ModelForm):
+class BaseDeviceCSVForm(BootstrapMixin, CustomFieldForm):
     device_role = forms.ModelChoiceField(
         queryset=DeviceRole.objects.all(),
         to_field_name='name',
```
…andi it seems to have done the trick: a new CSV field, prefixed with `cf_` (in my case, `cf_ticket`) appeared on the form. I tried importing while populating that and it just worked :)

Are there complexities I haven't encountered yet or is it just that simple?

**Comment by benclaussen** [comment]
@paravoid I attempted this same thing in the IPAM forms.py (`netbox/ipam/forms.py`) the field appeared... however it also broke the API. When I attempted to load the API docs, I received an `Internal Server Error` and the error emails stated
````
Internal Server Error: /api/docs/

KeyError at /api/docs/
'en-us'

...
````

I don't know for certain if the API actually broke or if it was just Swagger docs...but something was unhappy.

v2.2.8 on Ubuntu server 16.04.3 LTS

**Comment by CDawson1** [comment]
Any update to this?

**Comment by anthonyeden** [comment]
I'm going to have a go at implementing this, and do a pull request. I'm thinking it would also make sense to *export* custom fields via the various CSV templates.

Does this sound good? Is it within scope of this ticket, or should I create a new one?

**Comment by anthonyeden** [comment]
I've created a draft pull request to address Custom Field importing and exporting: #2949

Would a project maintainer be able to take a look and provide feedback?

**Comment by iDemonix** [comment]
After creating a very large CSV of data, mainly custom field data, we've also discovered this functionality isn't yet there.

Thanks for doing the work @anthonyeden, does your PR encompass imports for just Devices? Or does it cover Virtual Machines etc also?

**Comment by anthonyeden** [comment]
Hi @iDemonix,

This pull request now encompasses all different CSV Import models. Would you mind testing it for me and reporting back here?

**Comment by bT0mm** [comment]
Was this issue fixed ? 
I can't find a way to import export custom field with csv.
This feature is crucial to me.
