### ISSUE TITLE
Permissions constraints are not (adequately) applied on cable traces

### ISSUE THREAD

**Issue by cpmills1975** [netbox-community/netbox#5680]
### Environment
* Python version: 3.9
* NetBox version: 2.10.3

### Steps to Reproduce
1. As a user with sufficient permissions, create two devices (device a and device b)
2. Create an interface on each (interface a1 and b1)
3. Link the two interfaces with a cable
4. Create a permissions rule that allows access to another test user to only one of the interfaces (restricting ID with a constraint such as { "id": <id> } is sufficient)
5. Ensure no other permissions are granted - i.e. the test user cannot see the cables, devices, any other interfaces, front/rear ports etc
6. browse to /dcim/interfaces/<permitted_id>/trace/

### Expected Behavior
A lot less information be presented than is!

### Observed Behavior
It appears to me that the only permission that impacts the cable trace is permission to view the interface that the trace is originating from. No permissions are required to the cable or to any device/interface/front/rear port in the chain yet they are all shown. While the permissions setup specified above is bizarre, it serves the purpose in that the entire cable trace is visible as are all the devices, interfaces/front/rear ports etc in the cable path exposing a lot more information than one might reasonably deem necessary or acceptable.

Ideally the user should need permission to view all the elements presented on the cable path with any permission missing being rendered in some suitable way to obscure the information. I'm not quite sure how far this should go, i.e. should devices to which no view permission is still be shown in some obscured way or should they be skipped and a dotted line shown between the two interfaces that do have permissions or perhaps the trace functionality should only work if permissions are granted all the way down the chain?

**Comment by jeremystretch** [comment]
Thank you for submitting this issue, however it appears that this topic has already been raised. Please see issue #4944 for further discussion.
