### ISSUE TITLE
Column width on admin > permissions does not grant enough space to description

### ISSUE THREAD

**Issue by cpmills1975** [netbox-community/netbox#5685]
### Environment
* Python version: 3.9
* NetBox version: 2.10.3

### Proposed Functionality
Grant more space to the description column in the permissions view in the admin backend

### Use Case
I'm generating many permissions rules (in code as there are many!) and giving each a meaningful description of the reason for the rule and what it aims to achieve. The column width for the description column is very narrow compared to the column width for the list of models. Nothing is technically broken, but it makes the description hard to read. I'd like to suggest weighting the columns and granting more of the width to the description column.

### Database Changes
None

### External Dependencies
None

**Comment by jeremystretch** [comment]
Unfortunately, we have a finite amount of screen space to work with. Descriptions will wrap within a cell so you still see the full text.

> I'd like to suggest weighting the columns and granting more of the width to the description column.

No mechanism exists to do this: All columns are weighted by the size of their largest item. I'm sorry but there's nothing we can reasonably do here.
