### ISSUE TITLE
Automate the registration of plugins

### ISSUE THREAD

**Issue by pvinci** [netbox-community/netbox#5686]
### Environment
* Python version: 3.9
* NetBox version: 2.10.3

### Proposed Functionality
Currently, one needs to install a plugin via pip, edit the settings file and restart django.
I propose netbox support an entrypoint such as 'netbox.plugins' that external plugins can register into, eliminating the second step.
If a the entry `netbox.plugins` is configured as an entry in `PLUGINS` in the settings file, netbox will process plugins that have registered to the entrypoint in addition to any static entries. 

If the `netbox.plugins` entry is not present, the current functionality is retained.

### Use Case
1. Integration testing of plugins is simplified if the settings file does not need to be edited. 
2. Deployment within docker is simplified. 
3. A support organization could provide a verified requirements.txt file to deploy a supported configuration.

### Database Changes
None.

### External Dependencies

There are none to netbox.  The necessary functionality is already part of setuptools.  Plugins already require setuptools.  Plugins wishing to take advantage of the feature would need modify setup.py of the plugin to specify the entry point for the plugin.

**Comment by jeremystretch** [comment]
Please specify your NetBox version.

**Comment by jeremystretch** [comment]
We considered this early on when first developing plugin support, but there are a number of reasons we opted not to pursue it:

1. This enables anyone with access to the virtual environment to inject a new plugin without any safeguards or record within NetBox.
2. This does not allow an administrator to easily enable/disable a plugin.
3. You would still need to update `configuration.py` to set any configuration parameters anyway.

I understand the benefit it would be for automate for automated testing and Docker, however those are not our primary interests in developing NetBox. As far as the average user is concerned, I believe this would do more harm than good.

**Comment by pvinci** [comment]
Thank you.

I considered those issues as well.  
For points 1 and 2, my suggestion was that the functionality be enabled only if `PLUGINS` contains 'netbox.plugins' as in:
```
PLUGINS = [
    "netbox_animal_sounds",
    "netbox.plugins", 
]
```

As for point 3, I thought that the plugin already supports that ability via the plugin config, which could be specified in the plugin's setup.py 
```
    # Default configuration parameters
    default_settings = {}

    # Mandatory configuration parameters
    required_settings = []
```

**Comment by jeremystretch** [comment]
> For points 1 and 2, my suggestion was that the functionality be enabled only if PLUGINS contains 'netbox.plugins' as in:

That still doesn't allow a user to toggle individual plugins.

> I thought that the plugin already supports that ability via the plugin config

The PluginConfig class defines what configuration parameters are available/required. They still need to be set by the user in `configuration.py`.

**Comment by pvinci** [comment]
> That still doesn't allow a user to toggle individual plugins.
The existing functionality would be retained so that someone could do:
```
PLUGINS = [
    "netbox_animal_sounds",
   # "netbox.plugins", 
   "netbox_plugin1",   # normally registerable via netbox.plugins
   # "netbox_plugin2",   # normally registerable via netbox.plugins
]
```
And add the dynamic plugins with something similar to: 
```
if "netbox.plugins" in PLUGINS:
   discovered_plugins = {
    entry_point.name: entry_point.load()
    for entry_point
    in pkg_resources.iter_entry_points('netbox.plugins')
}
```
https://github.com/netbox-community/netbox/blob/03e48161a152ed0c6029b1834a7dc44c55f98fcc/netbox/netbox/settings.py#L587

It does not address configuration parameters.  

In looking at this further, it can be as easily implemented by anyone in `configuration.py`. I am closing this.
Thank you!
