### ISSUE TITLE
Add images to device type or resize comments field

### ISSUE THREAD

**Issue by andrexp** [netbox-community/netbox#5695]
### Environment
* Python version: 3.8.5
* NetBox version: 2.10.3

### Proposed Functionality
Add images to device-types
Modify comments field to support image resizing for fitting.

### Use Case
For some device types it is necessary to document some images to get rid of the need to label the devices. In the datasheet e.g. of some blade-server systems the numbering of the blades is shown.
I imagine two possible solutions:

1. Add images to the comments-field.
-already possible but then there is the need to resize images to make it fit into screens. See image below.
<img width="1036" alt="Bildschirmfoto 2021-01-26 um 20 58 16" src="https://user-images.githubusercontent.com/6609851/105899197-a5158800-601a-11eb-952e-febb7e87cf09.png">

2. Ability to add images to device-types.

### Database Changes
No.

### External Dependencies
No.

**Comment by jeremystretch** [comment]
> Add images to device-types

This is already supported.

> Modify comments field to support image resizing for fitting.

The comments panel is already as big as the page size will allow.
