### ISSUE TITLE
vlan assignment to interfaces upon bulk edit clears previouslly assigned ones

### ISSUE THREAD

**Issue by LuPo** [netbox-community/netbox#5710]
### Environment
* Python version: 3.9.1
* NetBox version: 2.10.4

### Steps to Reproduce
1. Configure interfaces 1-5,11-15 on VLAN A
2. Configure interfaces 6-10,16-20 on VLAN B
3. Bulk edit interfaces 1-20 and add VLAN C
4. Do not flag "set null" option

### Expected Behavior
1. Interfaces 1-5,11-15 with taggd VLANS A and C
2. Interfaces 6-10,16-20 with taggd VLANS B and C 

### Observed Behavior
all of the above interfaces have only VLAN C

**Comment by DanSheps** [comment]
I have not dove into it too much, but this might be a limitation of DJango.  I believe the bulk edit is a replace operation, even on multichoice fields.

**Comment by jeremystretch** [comment]
The current behavior simply sets the assigned VLANs, replacing any that were already assigned as @DanSheps alluded. To alter this behavior, we would need to introduce separate "add" and "remove" fields to the bulk edit form, as exist for tags.
