### ISSUE TITLE
Cable Trace on Ports

### ISSUE THREAD

**Issue by gafzgarrr** [netbox-community/netbox#5711]
### Environment
* Python version: 
* NetBox version: v2.5.2

### Proposed Functionality
Traceing a Cable on a Port

### Use Case
I have many interface Ports, which are connected over many Fibre Routing Ports. 

Interface A --- Front Port Device B --- Rear Port Device B --- Rear Port Device C --- Front Port Device C --- Interface D

I want to know, which Interface is connected on the Cable Rear Port B an Rear Port C by just clicking on it.
Also i want to see all ohter Ports in this way. 
Perfect would be a Syncronised Description, which means: Description Interface A is shown on Interface D or Front Port Device C

**Comment by jeremystretch** [comment]
> NetBox version: v2.5.2

I'm afraid your NetBox instance is several years out of date. Please upgrade to the most recent release, and you'll find that tracing cables from pass-through ports is supported.
