### ISSUE TITLE
Custom Fields Validation regex field is too small

### ISSUE THREAD

**Issue by ggiesen** [netbox-community/netbox#5719]
### Environment
* Python version: 3.6.8
* NetBox version: 2.10.2

### Proposed Functionality
Increase the length of the Validation regex field in Custom Fields beyond the current 500 character limit (perhaps to something like 4096)

### Use Case
In attempting to apply a validator to a custom field that defines static routes assigned to an IP on an interface, I use the following format:

\<prefix\>/\<prefixlen\> via gateway[,\<prefix\>/\<prefixlen\> via gateway]

Example:

`192.0.2.0/24 via 203.0.113.1,198.51.100.0/24 via 203.0.113.1`

To validate this accurately, use the following regular expression:

`^\b(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])\.(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])\.(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])\.(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])\b\/\b([0-9]|[1-2][0-9]|3[1-2])\b via \b(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])\.(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])\.(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])\.(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])\b(,\b(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])\.(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])\.(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])\.(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])\b\/\b([0-9]|[1-2][0-9]|3[1-2])\b via \b(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])\.(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])\.(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])\.(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])\b)*$`

Which is 838 characters long.

While the above expression could perhaps be shortened without sacrificing accuracy or increasing complexity, it serves to demonstrate how a regular expression to validate something even relatively simple can grow very long, and the current field length is inadequate

### Database Changes
I expect minor changes to column sizes would be require

### External Dependencies
None

**Comment by jeremystretch** [comment]
This is pretty clearly excessive use of regular expressions. You're trying to leverage a regex to enforce the validity of _several_ data types here, which is just generally a bad idea. You might consider splitting the relevant data into multiple fields or, better yet, writing a plugin to model it independently.

**Comment by DanSheps** [comment]
> While the above expression could perhaps be shortened without sacrificing accuracy or increasing complexity

I think this sentence sums this up pretty well.  You could validate this using a much shorter regex to accomplish the same validation and I don't see any normal circumstance where you need to exceed 500 characters for validation.

**Comment by ggiesen** [comment]
> This is pretty clearly excessive use of regular expressions. You're trying to leverage a regex to enforce the validity of several data types here, which is just generally a bad idea. You might consider splitting the relevant data into multiple fields or, better yet, writing a plugin to model it independently.

I'm not sure how you'd split this into multiple fields and still make it usable. I grant writing a plugin may work but that's a much bigger step from writing a regex.

> 
> 
> > While the above expression could perhaps be shortened without sacrificing accuracy or increasing complexity
> 
> I think this sentence sums this up pretty well. You could validate this using a much shorter regex (repeating patterns and recursion) to accomplish the same validation and I don't see any normal circumstance where you need to exceed 500 characters for validation.

I've got the regex down to 483 chars:

`^\b(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])(\.(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])){3}\b\/\b([0-9]|[1-2][0-9]|3[1-2])\b via \b(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])(\.(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])){3}\b(,\b(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])(\.(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])){3}\b\/\b([0-9]|[1-2][0-9]|3[1-2])\b via \b(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])(\.(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])){3}\b)*$`

It sacrifices a bit of readability, not that the original was terribly readable in the first place. Given that regex processing of things like IP addresses are very complicated, and the relatively simple example above still occupies 483 chars, I thought this was a no-brainer, but I guess I'm wrong. In the meantime I've managed to squeeze the regex down below the limit, and I'll wait for #5720 as the much better solution
