### ISSUE TITLE
Apply multiple instances of a custom field to an object

### ISSUE THREAD

**Issue by ggiesen** [netbox-community/netbox#5720]
### Environment
* Python version: 3.6.8
* NetBox version: 2.10.2

### Proposed Functionality
The current implementation of custom fields only allows for a single value. I propose that we allow to add multiple instances of a custom field much the same tags can be applied to almost anything

### Use Case
To add static routes on a device, I currently use a custom field attached to an interface IP using the following format:

\<prefix\>/\<prefixlen\> via gateway[,\<prefix\>/\<prefixlen\> via gateway]

Example:

`192.0.2.0/24 via 203.0.113.1,198.51.100.0/24 via 203.0.113.1`

This is currently cumbersome for a few reasons:

1) The field length is limited
2) It can be hard to create, read, and edit for large numbers of values
3) It's hard to validate

Instead, it would be cleaner to be able to add multiple instances of a custom field such that each value could be added, edited, removed, and validated individually.

ie.
1) `192.0.2.0/24 via 203.0.113.1`
2) `198.51.100.0/24 via 203.0.113.1`

### Database Changes
I would imagine new tables need to be created for the new 1:M relationships.

**Comment by jeremystretch** [comment]
Thank you for submitting this issue, however it appears that this topic has already been raised. Please see issue #5451 for further discussion.
