### ISSUE TITLE
ST split fiber to same ports

### ISSUE THREAD

**Issue by nikor30** [netbox-community/netbox#5721]
### Environment
* Python version: 3
* NetBox version: v2.10.3

### Proposed Functionality
Sometimes, it is necessary to indicate that one cable (fiber cable) in a switch is connected to two different ports in a patch panel. It should be possible to do that. You can see more information in the "Use Case" section.
Use Case

### Use Case

One fiber cable on one switch interface is connected to port1 in the patch panel but the second fiber cable is connected to port4 in the patch panel. We can fill this situation in NetBox. This is often habbening on ST panels etc.

![grafik](https://user-images.githubusercontent.com/4319444/106306913-fc0b9f00-625e-11eb-9b6f-02a8fe298998.png)

**Comment by jeremystretch** [comment]
> It should be possible to do that. 

This feature request is not actionable without a detailed implementation proposal. Please elaborate on the specific data model changes being proposed.

**Comment by nikor30** [comment]
Hi, a what ? Can you give me a sample how the implementation proposal should look like ?

Regards Niko

**Comment by jeremystretch** [comment]
There are hundreds (if not thousands) of feature requests here on GitHub that you can use as examples. I'm closing this for now due to the lack of activity, but you're welcome to request that it be reopened if you put the time into drafting a sufficiently detailed proposal.
