### ISSUE TITLE
Add config option to change map provider for "Map it" buttons

### ISSUE THREAD

**Issue by Starkstromkonsument** [netbox-community/netbox#5723]
### Environment
* Python version: 3.6.9
* NetBox version: 2.10.4

### Proposed Functionality
Add a configuration option to change the hard coded map provider from google maps to e.g. openstreetmaps.

### Use Case
Avoid the usage of google services for privacy reasons.

### Database Changes
I don't know, sorry.

### External Dependencies
None.

**Comment by jeremystretch** [comment]
I think it makes sense to add a configuration parameter, e.g. `MAP_URL` or similar, with the default value of the current Google Maps link. It will need to support some degree of templatization to pass an address/coordinate pair.
