### ISSUE TITLE
Value identification for custom field Selection

### ISSUE THREAD

**Issue by Thetacz** [netbox-community/netbox#5725]
### Environment
* Python version: 3.6.8
* NetBox version: 2.10.3

### Proposed Functionality
Please re-implement a way of differentiating values of custom field Selection. Discussed here: #5655 
This is something that worked with 2.9 (v2.9.9 now) but got broken in v2.10 (tested with v2.10.3) (see the discussion or Use Case for more details)
The proposed solution is to have permanent `value` and customizable `label` for each choice in Selection.

Note: The current behaviour is considered a regression bug from our side.

### Use Case
We have custom field named `owner` which we use to set business owner of most models. Let's assume only single one, IPAddresses as an example. This field is mandatory and for every IP there must be an owner set. The owner is mostly a team, string consisting of `<team_name> <contact_mail> <manager>`. If any of these change, we change it in admin view and this change gets propagated to every instance of IP with this owner. This is no longer the case, the old value does not get changed. 

Also any scripting now works with ID, which would need to be changed to the value and the value too will have to be changed on every change in admin view.

### Database Changes
If the new label/value gets stored in DB, than there will be a change to CustomField Selection.

### External Dependencies
No external dependencies.

**Comment by DanSheps** [comment]
It sounds like this would be better suited for a plugin with a custom data model associated with it.

**Comment by jeremystretch** [comment]
> The owner is mostly a team, string consisting of <team_name> <contact_mail> <manager>.

It looks like what you need, as @DanSheps hinted, is a separate model to store teams, which can then be referenced using a custom field. Trying to fit all this data into a single field is terribly redundant and should be considered an anti-pattern.

**Comment by Thetacz** [comment]
> > The owner is mostly a team, string consisting of <team_name> <contact_mail> .
> 
> It looks like what you need, as @DanSheps hinted, is a separate model to store teams, which can then be referenced using a custom field. Trying to fit all this data into a single field is terribly redundant and should be considered an anti-pattern.

Yes, having new table of `stake holders` or `owners` table would actually work for this particular field. Though I don't think it is possible to create a new model to extend the core models by myself. I can create new table with plugin, but AFAIK somehow referencing this in the core model is not the best course of actions (understatement).

Also from my point of view this would solve only 1/6 of our custom fields issues since we are using 6 Selections, each of them is vulnerable to change and causing issues in data consistency as a result. Much better course of action would be to solve this for general use.

I can write a plugin to create new tables for each instance of this custom field type, but that would mean basically creating layer above netbox and have everything requiring those fields referencing that layer. Not only API, but UI too since our users are changing those choice fields themselves.

So to fix this in netbox, having custom field Selection (choice) behave as other choices seems like a smart and DRY thing to do. 

Using `utilities.choices.ChoiceSet` for this seems like a good idea in line with the rest of the code base, where user input of `[choice_1, choice_2]` would get transfered to 
```
custom_field_choice (
    (auto_ID_1, choice_1),
    (auto_ID_2, choice_2)
)
``` 
or let the user specify both and than there is no need to have extra serializer, just use the one there is for choice fields if base models.


Note: I agree it is not the best practise to have both name and email in single field, but is is safer than having 2 fields since users can change the owners themselves and sooner or later someone will change only 1 of those instead of both at once.

**Comment by jeremystretch** [comment]
> Using utilities.choices.ChoiceSet for this seems like a good idea

This doesn't make any sense. The ChoiceSet class is used for storing data in the executed code; what you need is a mechanism for storing custom, variable data in the database (i.e. a custom model). The only way to accomplish this is with a plugin.

I'm sorry, but the use case you've described exceeds the intended function of custom fields.
