### ISSUE TITLE
Permissions bug for creating virtual interfaces through API

### ISSUE THREAD

**Issue by RobertH1993** [netbox-community/netbox#5734]
### Environment
* Python version: 3.9.1
* NetBox version: v2.9.10

### Steps to Reproduce
1. Create user without superuser status.
2. Add API token to this user.
3. Try to create a virtual interface through api:
curl -X POST -H "Authorization: Token <CENSORED> " -H "Content-Type: application/json" --data '{virtual_machine: "549", name: "test", enabled: true}' https://ipam.<CENSORED>/api/virtualization/interfaces/
4. Get permission denied error:
{"detail":"You do not have permission to perform this action."}
5. Verify that all permissions are enabled for the user this token belongs to, they are.
6. Enable superuser privileges on this user and try again, interface gets created.

### Expected Behavior
I expected the interface to be created when my user with valid access token sends an API request to create one.

### Observed Behavior
I got a permission denied error.

**Comment by jeremystretch** [comment]
It looks like you skipped assigning permissions to the user account. Just adding a REST API token isn't sufficient. Please add the necessary the permission (`virtualization > interface` in the admin UI) to add VM interfaces to the user and re-test.

**Comment by chriswolske** [comment]
We had the same issue when trying to add permissions via the web; is this a new permission, or is it possible that the permission was not carried forward properly though an upgrade?  (I'm new to netbox, and my team is telling me that they were able to create the virtual interfaces before we upgraded)

**Comment by The-Only-God** [comment]
I confirm that there is impossible to add virtualizaion.interface permission from web.
Workaround: superuser for API account

**Comment by dsobon** [comment]
The problem exists regardless via API or web UI.
If the user is not "Global Admin", 
1) Web UI shows "Virtualization" > "Interface" as grayed out and click returns "You do not have permission to view this page"
2) API call returns "You do not have permission to perform this action."

**Comment by RobertH1993** [comment]
Yeah to add to this, the problem started when I did an upgrade for netbox the permission was not present a version earlier and on update the permission was not granted to the user.

**Comment by jeremystretch** [comment]
This bug was reported for a very old release, and has since been closed due to a lack of reply from the original poster. If you would like to report a similar bug, please submit a new bug report including the detailed steps that can be taken on the current release to reproduced the reported behavior. No further work will be done under this bug report.
