### ISSUE TITLE
Request: Find parent subnets of searched IP

### ISSUE THREAD

**Issue by gramathy** [netbox-community/netbox#5737]
### Environment
* Python version: 
* NetBox version: v2.10.3

### Proposed Functionality

When searching for an IP address, also return prefixes the IP belongs to. This would provide additional information if individual IP information is lacking or the IP is part of a dynamic scope rather than individually recorded.

### Use Case

A device is misbehaving or compromised and is initiating faulty requests. The individual IP is not recorded and a search returns nothing at the moment. Returning parent subnets would provide some information as to where the device might be located on large networks where not everyone might already know where all subnets are. (example: a testing subnet where the IPs would not typically be recorded for use). This should be similar to the behavior of searching for a parent prefix where all child prefixes of the searched prefix are returned.

### Database Changes

none, should only require some masking math

**Comment by sdktr** [comment]
Isn't this the behavior in the GUI already? If a non-existing IP is searched for you'll get the prefixes that match most of the bits in the address as a result?

**Comment by jeremystretch** [comment]
You can use the `?contains=` filter on the prefixes list and API endpoint to return all prefixes that contain (or would contain) a given IP address, whether or not that IP actually exists.
