### ISSUE TITLE
pg_dump requires a username and a host (?)

### ISSUE THREAD

**Issue by bgianpetro** [netbox-community/netbox#5748]
### Change Type
[ ] Addition
[X ] Correction
[ ] Deprecation
[ ] Cleanup (formatting, typos, etc.)

### Area
[ ] Installation instructions
[ ] Configuration parameters
[ ] Functionality/features
[ ] REST API
[ X] Administration/development
[ ] Other

Not sure if this is an issue for everyone or not, but if I use 'pg_dump' as documented without both the -U (username) and -h (hostname) options it errors out on me.  In order to get it to work, I always need to use it as follows:

pg_dump -U netbox -h localhost netbox > netbox.sql

If that issue is not specific to me, maybe update the documentation to include those options.

**Comment by DanSheps** [comment]
This can probably be added as a !!note
