### ISSUE TITLE
Primary IP address variable wrong in the Export Template example

### ISSUE THREAD

**Issue by bgianpetro** [netbox-community/netbox#5750]
### Change Type
[ ] Addition
[X ] Correction
[ ] Deprecation
[ ] Cleanup (formatting, typos, etc.)

### Area
[ ] Installation instructions
[ ] Configuration parameters
[X ] Functionality/features
[ ] REST API
[ ] Administration/development
[ ] Other

In the Export Templates example there is a Jinja2 variable listed as follows:

{{ device.primary_ip.address.ip }}

I believe this is wrong, because it errored out when I used it and was resolved when I removed the trailing '.ip' as follows:

{{ device.primary_ip.address }}

**Comment by DanSheps** [comment]
Do you remember the error?  .address is a IP Address Object from the netaddr library

**Comment by bgianpetro** [comment]
Right, but note that as documented it is '.address.ip' (not just '.address')

So here's the error I receive if I keep the '.ip':

There was an error rendering the selected export template (test): 'None' has no attribute 'address'

**Comment by jeremystretch** [comment]
The example provided in the documentation is just that: an example. It is provided merely for illustration and is not intended to be used directly. We don't need to be certain the example code will work in every situation.
