### ISSUE TITLE
Please add Ansible role from DebOps to Automated Provisioning wiki

### ISSUE THREAD

**Issue by ypid** [netbox-community/netbox#5755]
### Change Type
[x] Addition
[ ] Correction
[ ] Deprecation
[ ] Cleanup (formatting, typos, etc.)

### Area
[ ] Installation instructions
[ ] Configuration parameters
[ ] Functionality/features
[ ] REST API
[ ] Administration/development
[x] Other

### Proposed Changes

We recently made a new DebOps release which brings NetBox support up-to-date. Can you create an entry in:

https://github.com/netbox-community/netbox/wiki/Community-Contributions#automated-provisioning

with something like this?

```
* [Ansible role](https://docs.debops.org/en/master/ansible/roles/netbox/index.html) (via @debops)
```

* [Ansible role](https://docs.debops.org/en/master/ansible/roles/netbox/index.html) (via @debops)

**Comment by jeremystretch** [comment]
Added
