### ISSUE TITLE
Link Between IPv4 Prefix And IPv6 Prefix

### ISSUE THREAD

**Issue by rabin-io** [netbox-community/netbox#5767]
### Environment
* Python version: Python 3.6.8 (CentOS 8 Stream)
* NetBox version: v2.9.10

### Proposed Functionality

An option to link an IPv4 prefix to IPv6 prefix.

### Use Case

In PHP-IPAM we had this option to link between IPv4 and IPv6 prefixes, 
as we started using more IPv6 in our networks, and we run in dual-stack
 (meaning the hosts and services are accessible by IPv4 and IPv6 address), 
So we had to keep track which IPv6 prefix we assigned to which IPv4 prefix (you can see an example pictures below)

### Database Changes

Not sure.

### External Dependencies

Not sure.

**Comment by ypid** [comment]
Aren’t both prefixes assigned to the same VLAN in reality which implicitly links them?

**Comment by jeremystretch** [comment]
> An option to link IPv4 prefix to IPv6 prefix.

This needs _much_ more detail to be worthy of discussion. Please extend your issue to elaborate on what specific changes you are proposing.

**Comment by rabin-io** [comment]
This is an option we have with [phpIPAM](https://phpipam.net/) and it is very simple but very helpful in my opinion. You can link one subnet to another, it's nothing fancy just a pointer to another subnet id, but it gives you a better view of which address are used on each segment.

As you can see in the screen shot 

![2021-02-10_00-30](https://user-images.githubusercontent.com/5116363/107437229-55b17a80-6b37-11eb-88f7-dabef23b38a8.png)

![2021-02-10_00-37](https://user-images.githubusercontent.com/5116363/107437771-264f3d80-6b38-11eb-90fc-a5b116e27563.png)

@ypid , Didn't check the VLAN option, not sure it's the same

**Comment by ypid** [comment]
> @ypid , I didn't check the VLAN option, not sure it's the same

Not the same but it can solve your issue. Check it out :)

**Comment by rabin-io** [comment]
> Not the same but it can solve your issue. Check it out :)

I see, not the same but usable I guess :)

Currently I do not use VLAN's on these networks, So I do not know if I want to solve the problem this way, Because it means I'm declaring something that does not exist, And I'm afraid it might come back and bite me in the ass in the future 😅

**Comment by ypid** [comment]
Ah, so IaaS or similar I assume. Then maybe don’t fake the VLAN because NetBox is meant to replicate the real world. I thought you might actually use VLANs. Then consider using tags.

Also, you really should update your initial comment. More details are needed.

**Comment by rabin-io** [comment]
Hopefully yes, but tagging is defiantly not the right way ;)

**Comment by DanSheps** [comment]
I can see what you want here.  You basically want a way of grouping IP subnets (IPv4 & IPv6) into one "network" (example could be vlans or a point-to-point network on a layer 3 interface).

We already have the vlan piece in place, we could just add a "related subnets" field in the UI to show the related subnets within the vlan.  However this falls down when you use a strictly L3 connection between two devices or any other use case.  Perhaps a "IP Group" option might be needed or similar.

Please re-adjust your FR to propose a solution that suits your needs as well as include detailed use-cases where you can't replicate the functionality with existing tools.

**Comment by rabin-io** [comment]
I guess since I got the option in the previous software, And I did not think about it too much. And the application was sufficient for that time (mainly documentation and allocation management).

But now we want to centralize all the documentation of the networks and infrastructure under NETBOX and build SOURCE-OF-TRUTH for automation and IaaC (NETBOX's API was the main reason for the move).

I understand that the implementation of this feature needs to be clearer, both at the WEB interface level and at the API level.

**Comment by jeremystretch** [comment]
IMO maintaining a direct mapping of IPv4 to IPv6 prefixes is poor practice and should be discouraged: The two are entirely independent address families with different rules and design considerations. As @DanSheps points out, there are already numerous attributes by which IPv4 and IPv6 prefixes can be correlated without adding a direct relationship.

**Comment by rabin-io** [comment]
Maybe in a ideal world where IPv6 took over and IPv4 was a relic of the past, but even now (20+ years after IPv6 was introduced)  we still leaning on IPv4 more then IPv6, and as one of many how have two sets of pools (IPv4 & IPv6) and would like to expose more services over IPv6, The most practical way will be to run in a Dual-Stack mode. And by having this small piece of meta data (which IPv6 prefix was assigned to which IPv4 prefix) helps (a lot). 

And as I mention before, this is nothing new, other tools have this option available in them, meaning there was a need for it. And I think it will be a functionality that many more people will be happy to have. 

🙏

**Comment by jeremystretch** [comment]
I was referring to dual-stack implementations. My point is that there is already effective correlation between the IPv4 and IPv6 prefixes, and that adding an explicit relationship is redundant.

**Comment by rabin-io** [comment]
If you are referring to the use of VLAN to aggregate them, this option is not working for our use case, as we are not using vlans. And I prefer my source of truth to be as close as possible to the real state of my infrastructure.

Also there are cases where you can have the same VLAN number used in several places on the same DC/Cage/Rack, which make the use of VLAN to aggregate the prefix's not usable.

**Comment by jeremystretch** [comment]
In today's maintainers' meeting, the idea was raised to simply display peer prefixes (correlated by assigned VLAN) in the prefix view. That seems like it would serve effectively the same function in most cases without needing to define an explicit relationship between prefixes.

**Comment by rabin-io** [comment]
Will that require to assigned a prefix to a VLAN to make it to work ?
