### ISSUE TITLE
Flag for Review System

### ISSUE THREAD

**Issue by stuntguy3000** [netbox-community/netbox#5768]
### Environment
* Python version: 3.6.8
* NetBox version: 2.10.4

### Proposed Functionality
A function to flag objects for review with/without comments, to then be reviewed by users from an automatically generated "to-do" list.

An expansion on this could be adding in scheduled review dates, for example documentation may need to be verified as correct every x months.

### Use Case
1) Engineers reviewing the documentation may notice mistakes or question certain elements which they believe to be wrong. These mistakes could be flagged for review and checked over in bulk.

2) After a critical ICT incident, infrastructure may change in more uncontrolled ways. Devices/objects could be flagged for review during or shortly after critical incidents to be followed up on.

### Database Changes
Unknown, but likely.

### External Dependencies
Unknown, but not likely.

**Comment by jeremystretch** [comment]
It sounds like you have a very specific workflow you'd like to implement. This is likely highly unique to your own organization and not something that would be reasonable to implement in the NetBox core. However, you might consider [writing a plugin](https://netbox.readthedocs.io/en/stable/plugins/development/) to implement the functionality you seek.

**Comment by stuntguy3000** [comment]
The feature doesn't sound very specific at all, it comes down to being able to flag mistakes within a documentation system. That doesn't sound very specific...

Surely many people would find that useful since it can be used in many ways.

**Comment by jeremystretch** [comment]
All the more reason to write a plugin, then.
