### ISSUE TITLE
Assign existing device from Rack page

### ISSUE THREAD

**Issue by hyudra** [netbox-community/netbox#5769]
### Environment
* NetBox version: 2.10.4

### Proposed Functionality
Able to assign existing device directly from Rack page. Currently, can only add new device, can it do the same to assign current rack and position to device? Same concept as assign existing IP address to interface (which auto filled device and interface field in IP address objects)

### Use Case
It'll be easier to fill in device from rack page and see overall rack spaces.

### Database Changes
None

### External Dependencies
-

**Comment by jeremystretch** [comment]
Thank you for submitting this issue, however it appears that this topic has already been raised. Please see issue #1830 for further discussion.
