### ISSUE TITLE
Preset filters

### ISSUE THREAD

**Issue by vsvetlov** [netbox-community/netbox#5772]
### Environment
* Python version: 3.7.3
* NetBox version: 2.9.11

### Proposed Functionality
By default NetBox shows all objects in a table but in most cases, users are interested only in a specific set of objects.
It would be nice to have the ability to define and save a preset for filter parameters. It could be done as a preset that applies by default per user basis as it is done for the table columns. The more extended version is the ability to save several presets and switch between them.

### Use Case
Every time I visit the devices page I need to filter the list to get only network devices and exclude any servers and any other equipment for example the patch-panels. People in other teams are not interested to see network devices. On an everyday basis, they work only with servers in a specific tenant. At the same time, everybody should have access to everything so it is impossible to resolve with access control functionality. 

### Database Changes
None

### External Dependencies
None

**Comment by jeremystretch** [comment]
This needs far more detail to be actionable. Please elaborate on the specific data model and other changes being proposed.
