### ISSUE TITLE
Can't Read Servername in SVG view of a Rack when Device has an Image

### ISSUE THREAD

**Issue by Exellent1988** [netbox-community/netbox#5773]
### Environment
Browser: Chrome 88.0.4324.146
Netbox-Version:  v2.10.4

### Steps to Reproduce
1.  Have a Device with Image (front and/or Back View)
2.  device has a Name
3.  See in Rackview the Deviceimage but not the text ( both in SVG and Rackview)

### Expected Behavior
See Text in front of Image

### Possible Fix.
in the the Image should be first in dom and then the text. but it's reversed ( Both in SVG and normal Rackview).

**Comment by jeremystretch** [comment]
Thank you for submitting this issue, however it appears that this topic has already been raised. Please see issue #4317 for further discussion.

**Comment by Exellent1988** [comment]
But that's a closed ticket and more a feature request than a bug. Mine is
definitely a bug report so I don't see any connection to the other ticket.

Jeremy Stretch <notifications@github.com> schrieb am Di., 9. Feb. 2021,
19:45:

**Comment by DanSheps** [comment]
This is not a bug, it is an intended feature (you can toggle text with the button).
