### ISSUE TITLE
Add the ability to Sync netbox user Groups and special Privileges with an Remote (HTTP) Auth Backend 

### ISSUE THREAD

**Issue by MaxRink** [netbox-community/netbox#5775]
### Environment
* Python version:  3.8.x
* NetBox version:  2.10.4
altough both n/a

### Proposed Functionality
Adding Group sync functionality to the Remote (HTTP) Auth Backend 
I have a working implementation under https://github.com/MaxRink/netbox/tree/remote_groups

### Use Case
Unlike the LDAP Backend, the RemoteUserBackend wasnt able to Sync Group memberships form the auth Provider.
This brings it up to parity, as the new Settings give you the Option to setup an automatic Group Sync (and revocation) on each User login.
This has been tested with oauth2-proxy
The old behaviopur of just Syncing Users and then manually managing Groups should be unaffected.

### Database Changes
No

### External Dependencies
No, all Django-internal

**Comment by MaxRink** [comment]
Yes, as we are already relying on it for our internal Instance.
@Cellebyte (one of my teamcollegues) would also be willing to take ownership, so thats its not just one person.

**Comment by Cellebyte** [comment]
@MaxRink should we also add an example oauth2-proxy configuration?

**Comment by devon-mar** [comment]
@Cellebyte
How are you handling API access with oauth2-proxy?
Are you bypassing auth_request for `/api`?

**Comment by Cellebyte** [comment]
@devon-mar yep

**Comment by MaxRink** [comment]
Just to reiterate, we arte still willing to maintain this code :D

**Comment by Cellebyte** [comment]
what is the status here?

**Comment by davama** [comment]
Is there a PR for this?

**Comment by MaxRink** [comment]
there was, and i can reopen it
https://github.com/netbox-community/netbox/pull/5771

**Comment by jeremystretch** [comment]
@MaxRink looks like this fell through the cracks. Sorry about that. I've marked it as accepted and assigned you if you'd like to re-open the pull request.

**Comment by mackaybe** [comment]
It would be nice if this auto-created groups(specified as super-users or staff groups). Is there any reason not to? In my testing at least the groups must exist before permissions are assigned.

**Comment by davama** [comment]
Would also be nice if `REMOTE-EMAIL` and `REMOTE-NAME` were included.
Basically expanding proxy auth

**Comment by jeremystretch** [comment]
@MaxRink's PR #6730 for this is still waiting for reviews and feedback. Given the degree of interest in this issue I'd expect to see at least a few people trying it and providing feedback.
