### ISSUE TITLE
Add ability to hide fields from web UI

### ISSUE THREAD

**Issue by thefreakquency** [netbox-community/netbox#5777]
### Environment
* Python version:  3.8.5
* NetBox version: 2.10.2

### Proposed Functionality
Using the config file or any other means, provide a way to hide non-required fields to the end-user when not used by the business in order to simplify the user interface. This would result in a lighter interface and less prone to user error

### Use Case
Some businesses don't use all default fields. Regarding the Sites, in our case, Site Shipping is always empty, so is "AS Number" might always be the physical address. In other cases, some users might not want to track the asset tag of a device or serial number. 

### Database Changes
I don't believe databases changes are necessary. I'm proposing to hide fields, not remove them. 

### External Dependencies
n/a

**Comment by jeremystretch** [comment]
This degree of customizability simply isn't a design goal for NetBox. There's no reason to spend precious development effort on something with such a minimal return on investment.

**Comment by ziggekatten** [comment]
Custom Scripts solve this very nicely!

**Comment by ypid-geberit** [comment]
@ziggekatten Can  you expand on that? I would be interested to know the details.

**Comment by thefreakquency** [comment]
@ziggekatten  Do you mean a script to modify pages? could you explain how you would achieve this?

**Comment by ziggekatten** [comment]
We use custom script to create forms with only needed fields for users to put data into. Static info are populated by the script if needed.
