### ISSUE TITLE
BUGEPORT #5773 closed in reference of an allready closed but unsolved Feature Request  #4317

### ISSUE THREAD

**Issue by Exellent1988** [netbox-community/netbox#5778]
My initial Bugreport #5773 was closed, with refernce to an closed Feature Request #4317 , which was neither solved nor implemented.
So beacause I cant contribute in the old Issue, I crated a new, one which was also closed do to duplication. *meh* ( Not quite a nice way to communicate with the Community). Thats why I'll try again.

### Environment
Browser: Chrome 88.0.4324.146
Netbox-Version:  v2.10.4

### Steps to Reproduce
1.  Have a Device with Image (front and/or Back View)
2.  device has a Name
3.  See in Rackview the Deviceimage but not the text ( both in SVG and Rackview)

### Expected Behavior
See Text in front of Image

### Possible Fix.
in the the Image should be first in dom and then the text. but it's reversed ( Both in SVG and normal Rackview).

**Comment by jeremystretch** [comment]
OP has been banned for 7 days for intentionally opening a duplicate issue.
