### ISSUE TITLE
Direct Current Terminal Type

### ISSUE THREAD

**Issue by macn27** [netbox-community/netbox#5796]
### Environment
* Python version: 3.8.5
* NetBox version: 2.10.3

### Proposed Functionality
Add the functionality to supply and receive DC power to devices.

Using DC to provide power to devices is a common practice in some environments. We would like to model these requirements.

I propose that:
Type 'DC Terminal' is added to Power Outlet Template 
Type 'DC Terminal' is added to Power Port Template

### Use Case
Some devices have the option to install DC power supplies or are powered using DC. 

### Database Changes
I don't believe that there would be a need to add any fields to the database. 

### External Dependencies
None

**Comment by robbat2** [comment]
Do you need more granularity than `DC Terminal`? Screw-type vs other connectors?

**Comment by macn27** [comment]
Although our applications have different termination types (screw connectors/terminal pugs) we don't need the granularity of having each type as an option. I can see how allowing those choices could lead to an endless list of options so I would be cautious adding them.

**Comment by jeremystretch** [comment]
> we don't need the granularity of having each type as an option

But other users presumably might.

> I can see how allowing those choices could lead to an endless list of options so I would be cautious adding them.

Well, let's see just how many it is. We have over 80 types as it is. Need some folks with DC-powered gear to offer more perspective.

**Comment by nicoduck** [comment]
Most devices I usually work with (Nokia, Cisco...) come with a small connector which can be plugged into the power supply which itself has screw terminals for connecting a cable, or they have screw terminals fixed directly at the power supply without a small plug.
None of these connectors are compatible to other devices of a different series or even another vendor, at least that's the case with the devices we use (between 10 and 20 different) so it wouldn't make any sense to try to get the proprietary connector itself into netbox, that would bloat the list. I'd say the plug is mainly useful for swapping devices/power supplies by non-skilled workers (from an electrical point of view) without disconnectint the DC cable itself, it's usually shielded and provides polarity protection. Some countries or companies require skilled workers for all kind of electrical work, which includes the sub 60V DC area.

As the main thing all of those devices have in common is the screw terminal, i'd therefore suggest to add a "DC screw terminal" to the list and maybe a "DC plug with screw terminal" do indicate a connection which can be disconnected by workers with no electrical background and help to dispatch the right people once a faulty device needs to be replaced.
