### ISSUE TITLE
Fiber Interface Types

### ISSUE THREAD

**Issue by robbat2** [netbox-community/netbox#5797]
### Environment
* Python version: 3.6.9
* NetBox version: 2.10.4

### Proposed Functionality
Add fiber port types as interface types, to account for devices with fixed/non-modular fiber connectors.

### Use Case
Accurate modelling of device interfaces with fixed fiber ports.
Examples:
- Arista DCS-7050TX-72 has 2x MXP ports, which are generically MPO-24, and can be split out as 3x40G or 12x10G. 
- Arista 7500E-12CM has 12x MXP, again MPO-24, but can be split as 1x100G/3x40G/12x10G.
See https://www.arista.com/assets/data/pdf/Whitepapers/MXP_Ports_Technical_Guide.pdf

As a user, I could create the Interface with the correct type, rather than just using `Other` as I'm doing right now.

### Database Changes
- Adding all fiber port types to InterfaceTypes.

### External Dependencies
None

### Notes
This was previously requested per #1392 for patch panels, but I'm explicitly requesting it for network switches with fixed fiber ports. At the bare minimum, I would like MPO added to interface types, but I feel if that was being done, adding all other fiber connectors as interface types would also be a good idea, to cover other systems (e.g. Server w/ NIC that has fixed fiber rather than modular port). Media converters are another case where fixed fiber ports are seen.

**Comment by robbat2** [comment]
@jeremystretch  would you accept a minimal patch that added a few MPO port types? 8, 24, and A/B/C types?

**Comment by jeremystretch** [comment]
Looks like this never went anywhere as no specific changes were proposed. You're welcome to open a new FR citing exactly what types you're proposing to add and why.
