### ISSUE TITLE
Fiber data modelling: multi-strand cables, port types

### ISSUE THREAD

**Issue by robbat2** [netbox-community/netbox#5798]
### Environment
* Python version: 3.6.9
* NetBox version: 2.10.4

### Proposed Functionality
Improve the PortType & CableType choices to capture more detail in high-density cabling.
MPO connectors come in multiple densities, and connector variations, which must be mated correctly for intended functionality.

- Fiber cabling should be expanded to include number of fibers & polarity (A/B/C/D)
- MPO connectors should capture male/female and fiber count
- Counts: 8,12,16,24,32,48,72,96,144

### Use Case
Be able to accurate model advanced fiber types.

### Database Changes
Probably need to debate this part; some of this absolutely could be implemented with just more port types, and more cable types, but is that the right way long-term? Should ports and cables get extra fields instead?

### External Dependencies
None

**Comment by BarbarossaTM** [comment]
This might be an option to model patch panels as well if you attach a multi-strand cable with say 48 cores (-> 1 rear port) to 24 LC/SC duplex front ports. Then you have only one cable between the panels which happens to model reality as well. :)
