### ISSUE TITLE
Systemd service

### ISSUE THREAD

**Issue by simo735** [netbox-community/netbox#5799]
### Environment
* Python version: Python 3.6.8
* NetBox version: v2.10.4
* OS: CentOS Linux release 7.9.2009

### Steps to Reproduce
1. systemctl stop netbox  + systemctl start netbox 
2. or systemctl restart netbox

### Expected Behavior
Restarted the netbox service

### Observed Behavior
Netbox service show failed but the application is still running because the process are never killed so impossible to restart the service with systemd.

**Comment by jeremystretch** [comment]
This is an installation issue. Please consider opening a [discussion](https://github.com/netbox-community/netbox/discussions) if you require assistance.
