### ISSUE TITLE
Missing dependency for Pillow build

### ISSUE THREAD

**Issue by letic** [netbox-community/netbox#5803]
### Change Type
[x] Addition
[ ] Correction
[ ] Deprecation
[ ] Cleanup (formatting, typos, etc.)

### Area
[x] Installation instructions
[ ] Configuration parameters
[ ] Functionality/features
[ ] REST API
[ ] Administration/development
[ ] Other

### Proposed Changes
Thanks for the fantastic doc ! I wish more project followed the same trend. While installing netbox on a debian bullseye LXC I noticed that there is a missing dependency while building Pillow. I had to install libjpeg-dev as well.

Patch to follow.

**Comment by jeremystretch** [comment]
The instructions are written only for Ubuntu and CentOS as noted; they may not work for other distributions. Unfortunately we are unable to extend the scope of the documentation given the project's limited resources.
