### ISSUE TITLE
Custom field filters missing for cables, rack reservations

### ISSUE THREAD

**Issue by proudbro** [netbox-community/netbox#5805]
### Environment
* Python version: 3.6.9
* NetBox version: 2.10.4

### Steps to Reproduce
1. Create Custom Field for Cables. Name "Test", type "Selection" or "Boolean"
2. Choose Filter logic "Exact" or "Loose" for Custom Field
3. Go to Cable List (Devices -> Cables)

### Expected Behavior
Among the list of filters on the right panel we see created Custom Filed "Test" as it how is it done for Racks for example.

### Observed Behavior
There is no new filter by Custom Field "Test". This behavior is also possible for other objects

**Comment by jeremystretch** [comment]
> 1. Create Custom Field for Cables. Name "Test"

What kind of custom field are you creating?

> 2. Choose Filter logic for Custom Field

What filter logic did you choose?

Please revise your bug report to be more detailed.

**Comment by proudbro** [comment]
@jeremystretch , I updated description above

**Comment by joaolucasmacedo** [comment]
Environment
    Python version: 3.6.9
    NetBox version: 2.10.4
and    NetBox version: 2.9.9

I have some custom fields and I can see and filter them only in Clusters and Devices page.
I have a "Boolean" custom field on circuit objects and some others on sites like "Type", "Integer" and "Date". But I can't filter sites or circuits using them.

![NetBox cf Clusters](https://user-images.githubusercontent.com/66760118/108069758-7bacb280-7042-11eb-8015-f6ab1f461326.png)


![NetBox cf Devices](https://user-images.githubusercontent.com/66760118/108069782-82d3c080-7042-11eb-9c35-d605fca9abaa.png)

Also, custom fields are not available on "Table Configuration" to select the columns that shows up.
By the way, I have to create custom fields to store the physical disk, memory and CPU cores available on clusters. It would be nice if NetBox take it into account according to the VMs associated with that cluster.

**Comment by proudbro** [comment]
No, it doesn't work.
The filter appeared after updating v.2.10.9 and in see it in URL but cables are not filtered. 
Should I open new bug?
