### ISSUE TITLE
Mapping technicians to a site

### ISSUE THREAD

**Issue by beermann** [netbox-community/netbox#5808]
Environment

    Python version: 3.6.8
    NetBox version: 2.10.4

Proposed Functionality

Associate a technician/staff to a site in order to indicate who has physical access to a site.

Purpose 

In order for quick response when an incident happens and on-call needs to figure out who is able to go to a site.
Auditing to show the audit who has access to what.

**Comment by ryanmerolle** [comment]
This is not a high ROI feature.  It can be solved by pairing with a tool like snipe-it, using a custom field for the site, or using the comments section for a site.

**Comment by ziggekatten** [comment]
Or Config Contexts, which imho is a swiss army knife.
