### ISSUE TITLE
Site's created via API are not honoring supplied Region value

### ISSUE THREAD

**Issue by routetehpacketz** [netbox-community/netbox#5814]
### Environment
* Python version: 3.8.7
* NetBox version: 2.10.4

### Steps to Reproduce
1. Create a Region
2. Get its ID
3. Create a Site via the API with the Region ID supplied

`requests.post('http://10.1.0.254:8082/api/dcim/sites/',headers={'Authorization':'Token 1234567890abcdef1234567890abcd'},data={'name':'NY1','slug':'site-NY1','region':3,'description':''})`

### Expected Behavior

A Site would be created and assigned to the supplied Region.

### Observed Behavior

The Site was successfully created, but its Region was set to null.

**Comment by routetehpacketz** [comment]
I was able to resolve my issue, but did not want to close the comment in case there was still something to be addressed on the Netbox side. I resolved the issue by simply changing the `data` parameter in my Python POST request to `json`.

**Comment by DanSheps** [comment]
Thank you for your interest in NetBox. GitHub issues are intended for reporting reproducible bugs and requesting features, and must be submitted using one of the templates provided [here](https://github.com/netbox-community/netbox/issues/new/choose). For general discussion, questions, or assistance with installation issues, please post to the [discussions](https://github.com/netbox-community/netbox/discussions) instead.

**Comment by routetehpacketz** [comment]
Is that not what I did?
