### ISSUE TITLE
LLDP: recognize cabling correctness via switchport mac

### ISSUE THREAD

**Issue by FlorianHeigl** [netbox-community/netbox#5818]
### Environment
* Python version: 3.8
* NetBox version: current nextbox-docker ba83c86505b3 (v2.10.4)

### Proposed Functionality

The LLDP Neighbors page has a column labeled LLDP Interface.
It is matched on the name of the remote interface to validate cabling.
A remote device can also send the MAC address instead of the interface name.
Currently that MAC address is not used for the matching, only the name.
I suggest it would also be used for matching.
currently, i get a false positive on this connection.

|Interface | Configured Device | Configured Interface | LLDP Device | LLDP Interface|
|-- | -- | -- | -- | --|
|ge-0/0/0 | ers | Port 2 | ers | 00:1f:46:ab:cd:ef|
|ge-0/0/3 | sw01 | GigabitEthernet1/0/3 | sw01 | GigabitEthernet1/0/3|

for linux you can force the expected behaviour by setting up a `/etc/lldpd.d/portid.conf` containing
`configure lldp portidsubtype ifname` followed by a restart of `lldpd`.

### Use Case

A user has a linux host running a stock setup of `lldpd` or i.e. an older Avaya switch.
netbox will show them this connection in red, although it is correctly plugged.
They'll be able to know that netbox correctly recognizes the link.

For the record, to me it seems the most successful strategy would be to reference mac, port id, port descr.

### Database Changes

I think the data is there and just needs to be referenced,
Likely it needs massaging so both mac address formats are of same upper/lower casing.

### External Dependencies

quite certain this has no depedencies :-)

**Comment by DanSheps** [comment]
Thank you for submitting your idea. Although the proposed functionality falls outside the current scope of NetBox's core feature set, it may make a good candidate for a [NetBox plugin](https://netbox.readthedocs.io/en/stable/plugins/), and we encourage you to pursue its development and a standalone project. Please reach out [via our mailing list or Slack channel](https://github.com/netbox-community/netbox/wiki) if you need any assistance.

**Comment by FlorianHeigl** [comment]
`¯\_(ツ)_/¯`
