### ISSUE TITLE
Unable to sort VMs by primary_ip

### ISSUE THREAD

**Issue by stuntguy3000** [netbox-community/netbox#5819]
### Environment
* Python version: 3.6.8
* NetBox version: 2.10.4

### Steps to Reproduce
1. Sort virtual machines by IP Address
https://[address]/virtualization/virtual-machines/?sort=primary_ip

### Expected Behavior
VMs to be sorted.

### Observed Behavior
Application crash.

```
<class 'django.core.exceptions.FieldError'>

Cannot resolve keyword 'primary_ip' into field. Choices are: cluster, cluster_id, comments, created, custom_field_data, disk, id, interfaces, last_updated, local_context_data, memory, name, platform, platform_id, primary_ip4, primary_ip4_id, primary_ip6, primary_ip6_id, role, role_id, secrets, services, status, tagged_items, tags, tenant, tenant_id, vcpus

Python version: 3.6.8
NetBox version: 2.10.4
```

Same bug as #5597

**Comment by Dimaqa** [comment]
This also happens when you sort devices by primary ip

**Comment by stuntguy3000** [comment]
> This also happens when you sort devices by primary ip

This was fixed in #5819, and is resolved in the latest release (2.10.4), see above for details.

**Comment by jeremystretch** [comment]
@stuntguy3000 I don't understand your comment above. #5819 is this issue.

**Comment by stuntguy3000** [comment]
> @stuntguy3000 I don't understand your comment above. #5819 is this issue.

Whoops, corrected - meant to reference 5597 as in the original post.
