### ISSUE TITLE
Increase virtual machine "name" field maximum length from 64 characters

### ISSUE THREAD

**Issue by jrbeilke** [netbox-community/netbox#5822]
### Environment
* Python version: 3.6.11
* NetBox version: 2.10.4

### Proposed Functionality
Tracking AWS EC2 instances in Netbox, but AWS allows `Name` tags up to 256 characters and Netbox only allows 64 characters:
https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/Using_Tags.html#tag-restrictions

Ideally the limit in Netbox would be increased to allow for tracking EC2 instances with their full `Name`.

### Use Case
EC2 instance with name longer than 64 characters cannot be easily tracked in Netbox, and causes conflicts with tracking other EC2 instances/Netbox vms if the 256 character name shortened to 64 characters is not unique.

### Database Changes
Increase character limit for Name field on Virtual Machine model to 256 characters

### External Dependencies
N/A

**Comment by Joezeppe** [comment]
Increasing the max_length parameter of the name field in the Virtual Machine model to 255 looks like a solution to this issue. I

**Comment by jeremystretch** [comment]
Is this truly needed? Do you have virtual machines with **names** greater than 64 characters in length?

This entire sentence is 64 characters long, counting the period. The limit exists today because DNS labels are limited to 63 characters.

**Comment by Joezeppe** [comment]
If there are virtual machines with names greater than 64, I have already changed the max_length here https://github.com/Joezeppe/netbox/commit/7ebd9a4e51670ac197f69cd5b4e00e53c3b32fe7.

**Comment by jeremystretch** [comment]
@Joezeppe FYI introducing a custom migration will break future upgrades. If you want to go that route, you'll definitely want to fork the whole project.

**Comment by Joezeppe** [comment]
@jeremystretch I will not customize existing migration files if that's what you mean. I will add a new migration file. FYI, I have already forked the whole project.
