### ISSUE TITLE
Allow sorting of inventory items table on device's inventory tab

### ISSUE THREAD

**Issue by hoalex** [netbox-community/netbox#5827]
### Environment
* Python version: 3.6.8
* NetBox version: 2.10.4

### Proposed Functionality
Make it possible to sort the items on the inventory table on a device's inventory tab by clicking on the corresponding table headers, similar to how it is done on other table views throughout Netbox.

### Use Case
Currently it seems as if the inventory items are sorted by creation date. This is not always desirable. For example when you add an item with an identical part ID as some previous item, it would improve the readability of the table to have these items next to one another, instead of having new items always at the end of the table.

I understand that one could go to `/dcim/inventory-items/`, apply a device filter, and then sort the table from there. But this adds several more steps to the workflow of the user, if one is looking at the detail page of a specific device.

### Database Changes
None

### External Dependencies
None

**Comment by jeremystretch** [comment]
> Currently it seems as if the inventory items are sorted by creation date.

Inventory items are ordered by their hierarchy: child items are listed under their parents. Within a parent, items are ordered by name.

**Comment by jeremystretch** [comment]
I've opened #6161 to enable ordering of all device components, which should cover this work.
