### ISSUE TITLE
Prefix config context

### ISSUE THREAD

**Issue by Lombra** [netbox-community/netbox#5835]
### Environment
* Python version: 3.9.1
* NetBox version: 2.10.3

### Proposed Functionality
Defining configuration context per prefix, inherited by devices which have an address in the prefix.

### Use Case
Allows for defining configuration commonly shared within subnets, such as default gateway and DNS servers.

### Database Changes
Adds config context field to prefix?

### External Dependencies
N/A

**Comment by DanSheps** [comment]
This is easily accomplished with custom fields, is there any reason why config contexts are needed?

**Comment by Lombra** [comment]
I'm confused. Couldn't the same be said of any of the models that currently support config contexts?

Configuration is what I want to provide, so config context seemed like the appropriate field. As well, of course, it would work with hierarchical rendering.

**Comment by Lombra** [comment]
I see now that I imagined the relationship in the opposite direction. The prefix would be a property of the config context, rather than the other way around? I don't think it affects my request, however.

**Comment by jeremystretch** [comment]
> Defining configuration context per prefix, inherited by devices which have an address in the prefix.

This isn't really practical to implement. You're going to be much better off employing tags. If you'd like to discuss potential solutions further, please consider opening a [discussion](https://github.com/netbox-community/netbox/discussions/new) detailing exactly what you'd like to accomplish.
