### ISSUE TITLE
Adapt HTML Template to add a Tenants Group link like the VLAN Groups when you’re within a Tenants Group.

### ISSUE THREAD

**Issue by Zwordi** [netbox-community/netbox#5837]
### Environment
* Python version: Python 3.6.8
* NetBox version: 2.10.3

### Proposed Functionality

Add a link back to Tenants Groups as it’s the case for example within a VLAN Groups, you can go back by clicking on "VLAN Groups" easily.
![image](https://user-images.githubusercontent.com/8830303/108365410-793f8980-71f7-11eb-86bb-6ac2167466b4.png)

Currently, when you are within a Tenants Group, you can’t go back to the list of Tenants groups the same way than VLAN Groups or Tenants.
![image](https://user-images.githubusercontent.com/8830303/108365662-bf94e880-71f7-11eb-88c1-b5ec80f22b97.png)

### Use Case

When you’re a Tenants Groups, and that you’re seing all the tenants of your Tenants groups, it would be nice to be able to go back to the list of the tenants groups the same way that the others object like VLAN Groups.

### Database Changes

Don’t think that it would require a DB change rather a "small" HTML adaptation on the "netbox/templates/tenancy/tenant.html" template around this block:

```html
<div class="row noprint">
        <div class="col-sm-8 col-md-9">
            <ol class="breadcrumb">
                <li><a href="{% url 'tenancy:tenant_list' %}">Tenants</a></li>
                {% if object.group %}
                    <li><a href="{% url 'tenancy:tenant_list' %}?group={{ object.group.slug }}">{{ object.group }}</a></li>
                {% endif %}
                <li>{{ object }}</li>
            </ol>
        </div>
```

As i’m not an HTML Gourou, i can’t say more about that except that i think that another loop could be made depending if we’re within a Tenants groups to have the href available to the ui.

Please let me know if you need other details.
Thanks

### External Dependencies

- none

**Comment by jeremystretch** [comment]
I believe this has been addressed in v2.11.
