### ISSUE TITLE
Font size slightly wrong in pagination chevrons

### ISSUE THREAD

**Issue by cpmills1975** [netbox-community/netbox#5847]
### Environment
* Python version: 3.9
* NetBox version: 2.10.4

### Steps to Reproduce
1. View any page with a table long enough to span multiple pages.
![Screenshot 2021-02-22 at 00 25 45](https://user-images.githubusercontent.com/1878544/108644000-f2173d80-74a4-11eb-9c22-8db6d8bc5f00.png)

### Expected Behavior
The box size for the chevrons should match the box size for the numbers next to it.

### Observed Behavior
The box for the chevrons is a couple of px larger than it should be.

**Comment by cpmills1975** [comment]
Happy to submit a PR to fix this if accepted and assigned to me.

**Comment by DanSheps** [comment]
Done, thanks!

**Comment by cpmills1975** [comment]
PR submitted.
