### ISSUE TITLE
Cable Trace (frontport to frontport) not available

### ISSUE THREAD

**Issue by PerAndersS** [netbox-community/netbox#5857]
### Environment
* Python version: 3.9.1
* NetBox version: v2.10.4

### Steps to Reproduce
To create two devices, do the following:
1. Create a device Role: "Role"
2. Create a manufactorer: "Cisco"
3. Create a Device type: manufactorer: Cisco, Model: TestModel, Height: 2
4. Create two sites: Name: TestSite1/TestSite2
5. Create one device on each site. 
  Name: TestDevice1/TestDevice2
  Site: TestSite1/TestSite2
  Device type: Cisco TestModel
  Role: Role
6. Create one rear port on each of the two devices:
  Device: TestDevice1/TestDevice2
  Name: rear1/rear2
  Type: SC
  Positions: 1
7. Create one front port on each of the two devices, connected to the rear ports created in step 6.
  Device: TestDevice1/TestDevice2
  Name: front1/front2
  Type: SC
  Rear Port: rear1/rear2
8. Finally, connect the two front ports by clicking "connect -- Front Port -- connect", then creating the cable between the two. Image to illustrate:
![image](https://user-images.githubusercontent.com/46927491/108981380-f9993b00-768c-11eb-97c3-71768fdd88b6.png)

### Expected Behavior
Showing a trace between TestDevice1 and TestDevice2 with a cable in between.  

### Observed Behavior
When trace is clicked, nothing appears. Here is the trace view:
![image](https://user-images.githubusercontent.com/46927491/108981185-c5be1580-768c-11eb-8760-322d7f174e4b.png)

### Additional Infromation
- I have developed some plugins, but they are disabled.
- Initially, I observed that most of the trace where broken. The majority where fixed by running the command: `python manage.py trace_paths`.

Thank you for your time!

**Comment by dreng** [comment]
I can confirm this issue and just want to add that the trace will be successful if "end devices" are connected (via interface). I'm not sure since when it is broken but I'm pretty sure that it has been functional before. My guess is that it's broken since v2.10.  Maybe related to #4900 ?

**Comment by Rock-Y** [comment]
See also: [discussion #5741](https://github.com/netbox-community/netbox/discussions/5741)

**Comment by JonasKs** [comment]
@jeremystretch, do you have any thoughts on this?

**Comment by networkhorse** [comment]
Definitely needed for MMRs and other similar ODFs!

**Comment by proudbro** [comment]
Cable Traces rearport to rearport are not available too

**Comment by jeremystretch** [comment]
This behavior is expected as front and rear ports are pass-through ports. Cable traces are created only when there is at least one non-pass-through endpoint, as all traces must define an origin point. Once you connect an endpoint (interface, console port, etc.) you'll be able to trace the path.
