### ISSUE TITLE
Plugins overview 

### ISSUE THREAD

**Issue by deku-m** [netbox-community/netbox#5870]
### Change Type
[x] Addition
[ ] Correction
[ ] Deprecation
[ ] Cleanup (formatting, typos, etc.)

### Area
[ ] Installation instructions
[ ] Configuration parameters
[ ] Functionality/features
[ ] REST API
[ ] Administration/development
[x] Other

### Proposed Changes
I just wonder many around here use netbox and many developed some nice plugins but you have to search for them on github.
Is it possible to make a section or something where people who developed some nice plugins can link them? Maybe the same as device-library? Or did i miss the section where it is provided.

I know this is a different request below doesnt have anything to do with documentation. But just a mindspin.
Maybe netbox can eventually even implement some sort of plugin section in netbox itself where you can link/find it. 
Like adding a reposity link to github and then install the plugin?

**Comment by minitriga** [comment]
Hello @deku-m, mostly when plugins are created they are tagged on github. I have done one or two plugins and there are several more about. You can find this tag [here](https://github.com/topics/netbox-plugin).

**Comment by ryanmerolle** [comment]
@minitriga is correct.  More info and the link is also in the wiki https://github.com/netbox-community/netbox/wiki/Plugins
