### ISSUE TITLE
Bandwidth or\and custom fields for interfaces

### ISSUE THREAD

**Issue by Dees7** [netbox-community/netbox#5871]
Hello.
We have network for more then 100 sites, and we use DMVPN. We also have limited bandwidth between sites. 
So in NB we'd like to have ability to keep current provider bandwidth. And generate config from NB using this bandwidth.
Also bandwidth used for balansing tunnels' traffic (as a cost link).

We'd love to have bandwidth (as custom fields of regular field), and some cost for interfaces (as custom field). 

Is it possible to do in current NB or might be you have this in roadmap?

Netbox 392e4b068b6b (v2.10.2) (in  Docker)

**Comment by ryanmerolle** [comment]
We have a discussion section for this sort of question.  You have two ways to do this.  Custom fields are able to be applied to a circuit.  Or like how I do it.  You can pull this sort of detail from the built in circuit commit rate, circuit termination port speed, and circuit termination upstream speed.

**Comment by jeremystretch** [comment]
Also, this is likely addressed by #5401: Custom field support for device components
