### ISSUE TITLE
Allow the default cable creation status in the web ui to be changed

### ISSUE THREAD

**Issue by raddessi** [netbox-community/netbox#5874]
### Environment
* Python version: 3.8
* NetBox version: 2.9.10

### Proposed Functionality
It would be nice if you could set the default status selection in the cable creation form in the ui from config. 

### Use Case
The current default of "Connected" is fine, but it would be useful for instances where people plan the majority of cables before actually connecting them to be able to set the default selection  in the web ui to be "Planned" instead of "Connected" via a config option. It would mean two fewer clicks for those cables being created in a planning state, if the default was set to planning by the config.

### Database Changes
I'm not sure of any, I would assume the default is kept in memory.

### External Dependencies
None afaik.

**Comment by raddessi** [comment]
Do I need to submit a PR for this?

**Comment by jeremystretch** [comment]
Closing this as it has not garnered any community interest, and we don't have any mechanism in place to support the proposed feature.
