### ISSUE TITLE
Remove VLAN Name Constraint

### ISSUE THREAD

**Issue by jacp9** [netbox-community/netbox#5877]
### Environment
* Python version: 
* NetBox version: 

### Proposed Functionality

Allow multiple VLANs within the VLAN group to have the same name.  Current constraints require a unique VLAN name within the VLAN group for each object.

### Use Case

We have 100s of VLANs within the same group which do the same function, such as voice signalling, voice media, management etc.  With current constraints, we need to name them in Netbox using the following naming convention `<vlan-id>-<vlan-name>` to achieve name uniqueness between the objects, however, in our network, they're just called `<vlan-name>`.  I don't see the benefit of having a unique VLAN name constraint.

### Database Changes

Don't think so.

### External Dependencies

Again, don't think so.

**Comment by jeremystretch** [comment]
@jacp9 did you mean to close this?
