### ISSUE TITLE
Add a CONTRIBUTORS file

### ISSUE THREAD

**Issue by jeremystretch** [netbox-community/netbox#5880]
### Change Type
[x] Addition
[ ] Correction
[ ] Deprecation
[ ] Cleanup (formatting, typos, etc.)

### Area
[ ] Installation instructions
[ ] Configuration parameters
[ ] Functionality/features
[ ] REST API
[ ] Administration/development
[x] Other

### Proposed Changes
I've opened this issue to propose adding a `CONTRIBUTORS` file, and making it clear that replication of the file is a condition of compliance with the license. Everyone who contributes or has contributed to NetBox in some substantial way (e.g. more than fixing a typo) will have the option of adding his or her name or pseduonym (and possibly email address?) to the file.

I'm proposing this change just in case some external entity decides to fork NetBox and blow away the entire git history, wiping out years of attributions to hundreds of individual contributors, and making it appear as if the related work was all their own. Again.

As for previous contributors, we can try reaching out to those with substantial contributions in the past couple of years to see if they want to add themselves. We could start off with a gist to limit noise in the project initially. I don't want to take the liberty of adding anyone without their knowledge out of respect for their privacy.

(Incidentally, we had discussed this very idea years back, but concluded that maintaining a `CONTRIBUTORS` file was largely redundant since GitHub already does a fantastic job of this natively.)

**Comment by ypid** [comment]
> I'm proposing this change just in case some external entity decides to fork NetBox and blow away the entire git history

With this background maybe https://reuse.software/ could be interesting. Using it, a `CONTRIBUTORS` file could be generated. It will also handle the case that the generated file will only list people with bigger contribution because fixing a typo does not justify a copyright entry.

And not to mention the main advantage https://reuse.software/ brings. Clear and machine readable licensing.

**Comment by DanSheps** [comment]
Interesting idea, however there is also:

* https://github.com/marketplace/actions/list-contributors
* https://github.com/marketplace/actions/contributors-list
* https://github.com/marketplace/actions/contributor_list
* https://github.com/marketplace/actions/auto-add-contributors
* https://github.com/marketplace/actions/contribute-list

Perhaps we enable one of those.

**Comment by cpmills1975** [comment]
Reading through the change proposal I was wondering whether this could be generate automatically from a PR - I'm not a GitHub expert.

**Comment by TheNetworkGuy** [comment]
I don't think generating this file automatically is an option. Jeremy explicitly mentioned the privacy of contributes. When you start auto generating this file its either all or none.

**Comment by jeremystretch** [comment]
Regarding privacy, I just don't want to retroactively add everyone without their consent. It's probably okay to automatically add contributors moving forward provided we communicate that clearly. Though it does raise the issue of how to credit contributors (GitHub name vs. real name), and whether people will be able to opt out.
