### ISSUE TITLE
Add custom links to device components

### ISSUE THREAD

**Issue by JulianJacobi** [netbox-community/netbox#5884]
### Environment
* Python version: 3.7
* NetBox version: 2.10.4

### Proposed Functionality
Add custom links to interfaces.

### Use Case
We use custom links to linking to our grafana dashboards directly out of Netbox. So to link to interface-detail dashboards it would be very nice to have custom links at interfaces as well.

### Database Changes
None

### External Dependencies
None

**Comment by jeremystretch** [comment]
Bumped the scope to include all device components.
