### ISSUE TITLE
Rename RackGroup to Location

### ISSUE THREAD

**Issue by jeremystretch** [netbox-community/netbox#5895]
### Proposed Changes
Rename the RackGroup model to Location (or some similarly generic term). This is a fairly substantial change, as it would entail renaming the model, database table, URLs, and REST API endpoints and serializers. We would also rename the `rack_group` field on the Rack model and add a `location` field to Device.

### Justification
This change would be prudent to accommodate #4971, which seeks to support the direct assignment of devices to rack groups, in a scenario where rack groups are used primarily to subdivide a parent site (e.g. into rooms or floors) rather than to group racks.

**Comment by ryanmerolle** [comment]
People are already using RackGroups as such, so it seems only prudent to rename.

**Comment by jeremystretch** [comment]
My only concern is that this could be a fairly disruptive change. It probably makes sense to retain the current related fields as read-only aliases of the new fields to support backward compatibility for all v2.11 releases. We could even go so far as replicating the API endpoints (to provide both `/dcim/rack-groups/` and `/dcim/locations/`), though I'm not sure how complicated that becomes.
