### ISSUE TITLE
Extend Secrets to Circuits

### ISSUE THREAD

**Issue by cybarox** [netbox-community/netbox#5905]
### Environment
* Python version: 3.8.5
* NetBox version: 2.10.5

### Proposed Functionality
We would like to have the possibility to use secrets under circuits.

### Use Case
We serve over 200 locations. We have 2 DSL connections at each location. We would like to have the possibility in NetBox to store the PPPoE dial-up data of the circuits in Secrets.

### Database Changes
Adding secrets relation to circuits

**Comment by jeremystretch** [comment]
No new work is being on secrets at this time as we plan on moving its functionality to a plugin; see #5278.
