### ISSUE TITLE
Multi-chassis Link Aggregation Group

### ISSUE THREAD

**Issue by mjf** [netbox-community/netbox#5916]
### Environment
* NetBox version: 2.10.5 

### Proposed Functionality
Add support for [MC-LAG](https://en.wikipedia.org/wiki/Multi-chassis_link_aggregation_group), please.

### Use Case
To model MC-LAG.

### Database Changes
Dunno.

### External Dependencies
Dunno.

**Comment by jeremystretch** [comment]
Duplicate of #2830
