### ISSUE TITLE
HTTP 204 response with body - /ipam/prefixes/{id}/available-prefixes/

### ISSUE THREAD

**Issue by stephan-windischmann** [netbox-community/netbox#5917]
### Environment
Python version: 3.7.9
NetBox version: v2.9.3

### Steps to Reproduce
Use the /ipam/prefixes/{id}/available-prefixes/ API endpoint to create a new child prefix of a size that does not fit into the parent prefix anymore, either because it's too big or because the parent prefix no longer has enough space available.

The received response (HTTP 204 NOT FOUND) contains a body and does not conform to the HTTP standard.

Example:
1. Create a new prefix
![image](https://user-images.githubusercontent.com/10330771/109927547-ae061300-7cc4-11eb-9c35-db15a1645991.png)

2. Create a child prefix of the newly created prefix that is too big to fit
![image](https://user-images.githubusercontent.com/10330771/109927584-bb230200-7cc4-11eb-9cce-599e3f659849.png)

We get a HTTP 204 NOT FOUND response. As can be seen the response contains a body with error details. This goes against the HTTP specification.

### Expected behavior
A fully standard compliant response

### Observed Behavior
The /ipam/prefixes/{id}/available-prefixes/ endpoint an HTTP 204 error response when we do a POST request to create a child prefix and not enough space is available in the parent prefix.
This reponse contains a body:
`{
    "detail": "Insufficient space is available to accommodate the requested prefix size(s)"
}`
While some tools and libraries (e.g. Postman) handle this fine, the HTTP standard says that HTTP 204 responses must not contain a message body, so other HTTP libraries will not handle this response body well.

**Comment by jeremystretch** [comment]
This issue is pending closure as it does not conform to one of the [provided templates](https://github.com/netbox-community/netbox/issues/new/choose) as required by the [contributing guide](https://github.com/netbox-community/netbox/blob/master/CONTRIBUTING.md). If you'd like to request that your issue be re-opened, please first update the content so that it matches the appropriate template (this may require rewriting your issue entirely).

**Comment by stephan-windischmann** [comment]
Issue updated to conform to template.

**Comment by jeremystretch** [comment]
@stephan-windischmann thanks, but could you please specify exactly what prefix(es) you're creating and what requests you're making? This will allow someone else to positively reproduce the reported behavior.

**Comment by stephan-windischmann** [comment]
Added steps to reproduce the behavior.

**Comment by DanSheps** [comment]
Looking at this, reviewing the HTTP spec, we probably should not be using HTTP_204_NO_CONTENT.  However, I cannot find a more accurate response without tripping a error condition (which would be a breaking change).

**Comment by jeremystretch** [comment]
> A fully standard compliant response

Which would be what, in your opinion?

**Comment by stephan-windischmann** [comment]
I'd probably use 406 Not Acceptable or 503 Service Unavailable (or the more generic 500 Internal Server Error).

I admit, these responses aren't ideal either, but seem like a better choice than using 204.
2xx responses should only be used if the request was successful.
