### ISSUE TITLE
 Virtual Chassis Cisco interface numbering wrong

### ISSUE THREAD

**Issue by nikor30** [netbox-community/netbox#5918]
### Environment
* Python version: Python 3.8.5
* NetBox version: (v2.10.5)

  On Cisco when you create stacks the second stack member is treated like adding a module to a modular switch.
In Netbox I use the Virtual Chassis to replicate Cisco stacks. Issue is the interfaces are now double
TwentyFiveGigE1/0/1 on stack memeber one and two
![grafik](https://user-images.githubusercontent.com/4319444/109846883-e9fe9100-7c4e-11eb-9516-3484fc196e61.png)
### Proposed Functionality

Solution is that by adding a memeber to the  Virtual Chassis is for Cisco deivecs is:
 stack master => TwentyFiveGigE1/0/1 
1 stack memeber => TwentyFiveGigE2/0/1
2 stack memeber => TwentyFiveGigE3/0/1
.
.
.5 stack memeber => TwentyFiveGigE5/0/1   
### Use Case

Think this is mandatory to reflect as most the reality as possible

###

**Comment by tyler-8** [comment]
You'll need to rename the interfaces yourself, to match the on-box numbering. It's just an unfortunate side-effect of all the vendors using different types of chassis/slot interface naming.

**Comment by jeremystretch** [comment]
Just confirming what @tyler-8 said above. There is no one-size-fits-all approach to this that we can implement blindly; best to handle it on your own to avoid unexpected behavior.

**Comment by DanSheps** [comment]
This also matches the expected behaviour of a Cisco switch.  If you remove  switch 2 from a stack, it will be "slot 2" and not "slot 1" unless you go back and renumber the switch.
