### ISSUE TITLE
Experiencing postgresql database creation failure. 

### ISSUE THREAD

**Issue by TheTrafficNetwork** [netbox-community/netbox#5920]
# Environment
- Ubuntu 20.04.2 LTS
- PostgreSQL 12.6 (Ubuntu 12.6-0ubuntu0.20.04.1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0, 64-bit

# Steps to Reproduce
1) Fresh Installation of Ubuntu 20.04.2
2) sudo apt update
3) sudo apt upgrade
4) Following steps for database creation:
- sudo apt install -y postgresql libpq-dev
-  sudo -u postgres psql
    - postgres=# CREATE DATABASE netbox ENCODING 'UTF8' LC_COLLATE='C.UTF-8' LC_CTYPE='C.UTF-8';

# Observed Behavior
ERROR:  new collation (C.UTF-8) is incompatible with the collation of the template database (en_US.UTF-8)
HINT:  Use the same collation as in the template database, or use template0 as template.

# Expected behavior
CREATE DATABASE

# Note
- Installation instructions show > psql (12.5 (Ubuntu 12.5-0ubuntu0.20.04.1))
- Installation using > psql (12.6 (Ubuntu 12.6-0ubuntu0.20.04.1))
- Changing C.UTF-8 to en_US.UTF-8 allowed the creation of the database, but I do not know if that will affect anything down the line.

**Comment by jeremystretch** [comment]
Looks like we might need to revert #5760
