### ISSUE TITLE
ContentType Permission Needed for API Users

### ISSUE THREAD

**Issue by kvedder-amplex** [netbox-community/netbox#5921]
### Version
  Netbox V2.10.5

### **Expected Behavior**
When calling `ctype = ContentType.objects.get(id=instance.assigned_object_type_id)` in a plugin that is triggered by the API, it should return the requested data.

### **Observed Behavior**
- When querying the ContentType, I get a 403 Denied. 
- From what I can tell the user assigned to the API Key does not have permissions to access the ContentType model. Even if the user was a SuperAdmin.
- I checked my permissions list and did have a user that could access the ContentType model.
![image](https://user-images.githubusercontent.com/44881775/109877650-4955a480-7c41-11eb-9d78-d613bf9d175e.png)
- When I switched the API User mapping to that user, the plugin performed as expected
- I would like to be able to assign other users to be able to access the ContentType Model, and have SuperUsers be able to access it from within the plugin.
- When I go into the Permissions to Add another user to that permission, the ContentType model is not available in the Models List.
![image](https://user-images.githubusercontent.com/44881775/109877919-989bd500-7c41-11eb-84bc-003d09a6e818.png)

**Comment by DanSheps** [comment]
I don't believe we are restricting the ContentType query as this is a builtin DJango model but perhaps @jeremystretch can confirm.

**Comment by jeremystretch** [comment]
This issue is pending closure as it does not conform to one of the [provided templates](https://github.com/netbox-community/netbox/issues/new/choose) as required by the [contributing guide](https://github.com/netbox-community/netbox/blob/master/CONTRIBUTING.md). If you'd like to request that your issue be re-opened, please first update the content so that it matches the appropriate template (this may require rewriting your issue entirely).

**Comment by jeremystretch** [comment]
Closing this as no further information has been provided, but it's evident from your problem description that you're looking for assistance with the development of a plugin. Please consider creating a [discussion](https://github.com/netbox-community/netbox/discussions/new) instead.
