### ISSUE TITLE
Multiples netbox-rq workers

### ISSUE THREAD

**Issue by Trunkol** [netbox-community/netbox#5927]
### Environment
* Python version: 3.8.5
* NetBox version: 2.9.4

### Proposed Functionality
The way that [netbox-rq service](https://github.com/netbox-community/netbox/blob/develop/contrib/netbox-rq.service) it's named today, we are able to get only one worker at a time. Based on [RQ documentation](https://python-rq.org/patterns/systemd/) we should just spawn another process using `systemctl` and the [units files templates](https://www.digitalocean.com/community/tutorials/understanding-systemd-units-and-unit-files#creating-instance-units-from-template-unit-files).  

This will touch on the unit file name and perhaps the description.

### Use Case
If you wanna multiples workers consuming from a queue and perhaps some jobs take some considerable amount of time.

**Comment by jsenecal** [comment]
This comment is based on my experience with netbox 2.9.10 - 

Netbox is currently unable to handle more than one worker as the only available result for a given task is the latest one AFAIK.
This, I believe would require an overhaul of how the scripts are being run and their results accessed.
