### ISSUE TITLE
Alphabetically sort filter options in overview

### ISSUE THREAD

**Issue by soer7022** [netbox-community/netbox#5932]
### Proposed Functionality
Currently the filters on the device page aren't sorted by anything:
![](https://i.imgur.com/UISJY9Z.png)
This makes it difficult to quickly find the desired filter. I propose that these be sorted alphabetically to make it easier to find the correct filter

### Database Changes
None

### External Dependencies
None

**Comment by DanSheps** [comment]
The filters are actually sorted by logical hierarchy.  For example:

Region
  ->  Site
    -> Rack Group
      -> Rack
Status
Role
etc

**Comment by soer7022** [comment]
I'd say an alphabetical sorting would make way more sense here. 
When I want to look for a device with a specific status, it's way more intuitive to scroll to S than to think; "Hmmm which logical position would status be in compared to the other fields"

This is also feedback we've had from multiple of our network engineers who use these filters multiple times a day everyday, and they dont find them intuitive.
