### ISSUE TITLE
Template tags do not take into account plugins

### ISSUE THREAD

**Issue by DanSheps** [netbox-community/netbox#5943]
### Proposed Changes

Wrap reverse() in try/catch statement to test against both plugins and base namespace.

### Justification

Currently, these button tags do not test against the plugins namespace.  This would add testing against the namespace with and preserve the original.

Sample code:

```
    try:
        url = reverse(viewname, kwargs={'pk': instance.pk})
    except NoReverseMatch as e:
        try:
            url = reverse(f'plugins:{viewname}', kwargs={'pk': instance.pk})
        except NoReverseMatch:
            raise NoReverseMatch(e)
```

**Comment by jeremystretch** [comment]
I don't follow. Can you point to an example where this is breaking something in NetBox? IMO it's bad practice to try and "brute force" the URL resolution: The tag should know when it's being called what URL it intends to resolve.

**Comment by DanSheps** [comment]
An example would be ButtonColumn where you resolve the URL automatically for edit/delete/changelog, the button does not take into account the fact that a URL might be in a sub-namespace (plugins:xxx for example) as the resolution is simply `f'{model._meta.app_label}:{model._meta,model_name}'`

**Comment by jeremystretch** [comment]
These tags aren't intended for use within plugins, so we don't check the plugins space. Supporting the use of these internal components within a plugin is a much greater undertaking, involving formally extending the plugins API and documenting their usage.
