### ISSUE TITLE
Cascade delete IP addresses with interfaces 

### ISSUE THREAD

**Issue by proudbro** [netbox-community/netbox#5945]
### NetBox version

v.2.10.5

### Python version

3.6

### Steps to Reproduce

1. Create any device with Interfaces components
2. Add IP address on interface
3. Delete Device

### Expected Behavior

There is no cascade delete. Previously added IP address will return to the list of IP addresses and can be assigned again

### Observed Behavior

It occurs cascading IP address deletion with device and interfaces

This bug looks especially strange if I create "TEST" user with prohibition on IP deletion and do the same steps to reproduce. 
The address will be deleted again. But "TEST" user can't delete adresses via GUI.

**Comment by jeremystretch** [comment]
> There is no cascade delete. Previously added IP address will return to the list of IP addresses and can be assigned again

This is expected behavior, specifically chosen to avoid the unintentional loss of data. If you'd like to change it, please submit a feature request citing your use case and justifying the risk for the community to review.
