### ISSUE TITLE
Add markdown rendering to custom scripts' description

### ISSUE THREAD

**Issue by rodvand** [netbox-community/netbox#5953]
### NetBox version

v2.10.4

### Feature type

Change to existing functionality

### Proposed functionality

In custom scripts, the Meta.description on each custom script is rendered as plain text. I propose to add the template tag |render_markdown in the netbox/templates/extras/script.html and script_list.html wherever the {{ script.Meta.description }} is referenced.

### Use case

Custom scripts can sometimes become a bit "big" and not so easy to understand from a user's perspective and I would like to be able to add a link to a guide in the description of the script. I see this has been suggested before in https://github.com/netbox-community/netbox/issues/5082 but the workaround posted in that is not working, and I can't understand that it has ever worked looking at the code.

### Database changes

None

### External dependencies

None

As Custom Scripts descriptions today are only plain text I can't see the addition of markdown rendering doing any harm.

**Comment by rodvand** [comment]
@jeremystretch If I want to handle this (since you've labeled it "needs owner"), do you have to assign it to me or can I just create a PR?

**Comment by jeremystretch** [comment]
You're all set!
