### ISSUE TITLE
Add Cable Trace option in additional pages

### ISSUE THREAD

**Issue by jcralbino** [netbox-community/netbox#5954]
### NetBox version

v2.10.5

### Python version

3.6

### Steps to Reproduce

1. Create cable connections between devices using devices with front port and rear port.
2. Cable trace option is not shown in the menu 

### Expected Behavior

An option to trace the cable is available in the menu?

### Observed Behavior

There is no way to invoke the trace option for a end-to-end check.

**Comment by DanSheps** [comment]
![image](https://user-images.githubusercontent.com/11049792/110811069-fafd6280-824b-11eb-91fa-fe790506a083.png)

Are you saying the blue cable trace button is missing?  If so, have you collected static?  If not, please provide more concrete steps to reproduce.

**Comment by jcralbino** [comment]
Hello Dan,
Indeed i was not seeing that feature, but i realize now that this is seen only in the interface list of a specific device that is connected. 
Somehow i was expecting to see that option on the Devices Menu ( Under connections, or under interface connections)

But i understand now that it is shown directly within the context of a interface view within a specific device.

I would say that it could be interesting to place this icon in more places. Namely on:
- Within a cable page (https://netbox/dcim/cables/<ID>/ ) 
- Within the Interface connections page (https://netbox/dcim/interface-connections/ ) 

At the moment it seems that is only shown here:
https://netbox/dcim/interfaces/<ID>/
https://netbox/dcim/interfaces/dcim/devices/<ID>/interfaces/

**Comment by jeremystretch** [comment]
I'm going to close this as it's not a valid bug report. You're welcome to submit a separate, detailed feature request if you'd like, but when doing so please be clear on exactly what you're proposing to change and why.
