### ISSUE TITLE
password reset button for users

### ISSUE THREAD

**Issue by azatuni** [netbox-community/netbox#5957]
### NetBox version

v2.10.4

### Feature type

New functionality

### Proposed functionality

"password reset" or "forget password" button in login page

### Use case

users will be able to reset their forgotten passwords without contacting admin staff

Hi,

it will be great if there will be reset password button for not login user if LOGIN_REQUIRED = True, so user who forgot his password will be available to reset it by enter username and go via email link

Thanks beforehand.

BR,
Areg

**Comment by jeremystretch** [comment]
Given NetBox's function as an exclusively inward-facing tool, it doesn't seem prudent to include this sort of "self-help" functionality. IMO wherever the reissuance of credentials is necessary, an administrator should be involved.

**Comment by azatuni** [comment]
It could be a configurable feature, for example USER_PASSWORD_RESET = True / False

**Comment by jeremystretch** [comment]
The problem with configurable features is that they're no less burdensome to maintain (more so, actually).
