### ISSUE TITLE
Site: Add possibilits for Sub-Locations / Nested sites

### ISSUE THREAD

**Issue by c-po** [netbox-community/netbox#5961]
### NetBox version

v2.10.3

### Feature type

New functionality

### Proposed functionality

Currently a site is assigned to a region and or tenent. It would be very good to also support site-in-site or nesting of sites, called a sublocation.

### Use case

Imagine several large campus networks on the globe where region is `EMEA`, and the site name would be `Munich`.

Now the Munich campus network will have several buildings all associated with the particular site, but they run their own AS numbers, may have different contact persons but in the greater good are all managed by the Munich site.

By adding the possibility to specify a sublocation which is bound to a larger site one can also only list "per building" IP addresses or the IP addresses for the entire site.

### Database changes

Probably yes

### External dependencies

No

**Comment by jeremystretch** [comment]
NetBox v2.11 repurposes the RackGroup model (now named Location) for this purpose (#5895) and allows devices to be assigned to locations within a site (#4971). These changes, along with extended support for custom fields, are likely to address your needs. If not, we can consider revisiting the topic after the final v2.11.0 release.

**Comment by c-po** [comment]
Does this also apply to IP prefixes and not only devices? This is definately something we will try with the v2.11 release when it's out.

**Comment by jeremystretch** [comment]
There's no plan for that at this time, no.

> Now the Munich campus network will have several buildings all associated with the particular site, but they run their own AS numbers, may have different contact persons but in the greater good are all managed by the Munich site.

I have to say it really sounds like you'd be better offer designating each building as its own site, within a region representing the campus.

**Comment by jeremystretch** [comment]
Closing this as it's likely addressed by #5895 as mentioned above.
