### ISSUE TITLE
Add info on custom field usage to Custom Links

### ISSUE THREAD

**Issue by mmahacek** [netbox-community/netbox#5965]
### Change Type

Addition

### Area

[ ] Installation instructions
[ ] Configuration parameters
[ ] Functionality/features
[ ] REST API
[ ] Administration/development
[X] Other

### Proposed Changes

Include an additional note in the Custom Links section to indicate the notation for using custom fields.
`{{ obj.cf.FieldName }}`

**Comment by jeremystretch** [comment]
This is already documented under the custom fields documentation. It works the same everywhere; there's nothing special about referencing it from within a custom link. Let's avoid introducing redundant documentation, as it presents an additional maintenance burden.

**Comment by mmahacek** [comment]
While I do agree that the Custom Fields documentation is a better place for this, I don't see anything on that documentation page in regards to using custom fields in jinja templates.  After a bit of digging, the only place I could find a reference to this was hidden on the Export Templates page.

**Comment by jeremystretch** [comment]
My mistake; I could have sworn we added that a while ago. Still, it needs to be documented on the custom fields page, not under custom links.
