### ISSUE TITLE
Add bulk edit views for organizational and nested group models

### ISSUE THREAD

**Issue by jeremystretch** [netbox-community/netbox#5972]
### Proposed Changes

Add bulk edit functionality for the following models:

* circuits.CircuitType
* dcim.DeviceRole
* dcim.Location
* dcim.Manufacturer
* dcim.Platform
* dcim.RackRole
* dcim.Region
* dcim.SiteGroup
* ipam.RIR
* ipam.Role
* ipam.VLANGroup
* secrets.SecretRole
* tenancy.TenantGroup
* virtualization.ClusterGroup
* virtualization.ClusterType

### Justification

Allows users to mass-edit non-unique attributes such as description or color

**Comment by ziggekatten** [comment]
This makes alot of sense for us as we often get initial objects before a transition project begins, and as realiy kicks in, this would put the power of change into UI (project managers) instead of coders (me and my team)

:-)

**Comment by jeremystretch** [comment]
Just to provide a bit of history, the reason this doesn't exist today is that most of these objects originally had no non-unique fields; just `name` and `slug`, so there was nothing that could be edited in bulk. We added `description` fields a while back but overlooked the bulk editing function.
