### ISSUE TITLE
Allow float value for VM cpu

### ISSUE THREAD

**Issue by maximebrun** [netbox-community/netbox#5975]
### NetBox version

v2.9.11

### Feature type

Data model extension

### Proposed functionality

Allow to set cpu in float format for virtual machine.

### Use case

We use virtual machine and set cpu less than 1. For example, 0.5.

### Database changes

Change PositiveSmallIntegerField to DecimalField for vcpus in VirtualMachine model.

### External dependencies

Unknown

**Comment by jeremystretch** [comment]
Tagging this for v2.11 since we're changing the field type from integer to float.

Does it make sense to limit this value to a particular granularity (e.g. 0.5)?

**Comment by ypid** [comment]
@maximebrun 

Can you give a reference which Hypervisor software allows this setting? I have not seen this before.

**Comment by jogulin** [comment]
@maximebrun 

I cannot find a reference to a hypervisor configuration that permits fractional assignments.  Virtual CPUs must be assigned as integer values.  VMware is a drop-down.  KVM is also an integer assignment.  Please provide a reference as to why this change was included.

**Comment by ziggekatten** [comment]
AIX LPARs can do this in 0.25 chunks.

**Comment by maximebrun** [comment]
> @maximebrun
> 
> I cannot find a reference to a hypervisor configuration that permits fractional assignments. Virtual CPUs must be assigned as integer values. VMware is a drop-down. KVM is also an integer assignment. Please provide a reference as to why this change was included. The closest thing I can find is a weight limit for Hyper-V, but you are still assigning whole integer values as the number of vCPUs. You are just limiting how much of the physical CPUs the vCPUs can consume. That is not the same as assigning half of a vCPU.

Sorry for late answer, i missed notifications...

Perhaps we didn't use this field in the same manner. I use it to set the hypervisor cpu reserved for the vm, not the number of cpu the vm see (vcpu).

I am using OpenNebula/KVM.

**Comment by jogulin** [comment]
> AIX LPARs can do this in 0.25 chunks.

People still use AIX?  :)

> Sorry for late answer, i missed notifications...
> 
> Perhaps we didn't use this field in the same manner. I use it to set the hypervisor cpu reserved for the vm, not the number of cpu the vm see (vcpu).
> 
> I am using OpenNebula/KVM.

I thought it was how many virtual CPUs were assigned to the VM itself, or at least that's how we have been using it.  We are migrating away from KVM ingeneral but still have some of it sitting around, and are primarily using VMware now.  In both cases we have it reflect the number of CPUs the VM will show when you sign into the guest OS, not the number of physical CPUs reserved for the VM.

**Comment by ziggekatten** [comment]
Hey, AIX is still king:-)

Linux is good but those of us that want pure performance still use good ol' blue Power systems. 

:-)
