### ISSUE TITLE
Add utilization bar to Power panels

### ISSUE THREAD

**Issue by 991jo** [netbox-community/netbox#5976]
### NetBox version

v2.10.3

### Feature type

New functionality

### Proposed functionality

Power feeds have a utilization bar that shows how much of the power is used by the devices plugged into that feed.
Power panels should also have a maximum power and a utilization bar because the power a panel can deliver is also limited and that limit might be lower than the sum of the feeds that belong to that panel. The allocated power usage of a power panel would be the sum of the allocated power of all it's feeds.

### Use case

make sure that the total amount of power used by all feeds does not exceed the amount a power panel can handle.

### Database changes

Add a "maximum power" field to the power panel

**Comment by robbat2** [comment]
- How do you propose to handle devices with multiple power inputs, which might be driven by different feeds?
- I'm not sure this overall is representative of the real world: e.g. my local panel has a 100A breaker on the supply side, and then 450A worth of 15A/30A breakers.

**Comment by 991jo** [comment]
I assume you mean that you have are talking about devices with multiple power inputs that are redundant and that are connected to different feeds but end up on the same power panel? The way I proposed it each of the inputs would be counted even when n reality only one of them will see that load.

The amount of power your panel has only supply side vs. the allocated power on the feeds/devices on that panel is exactly what I am interesetd in. Of course the amount of power the breakers in your can be bigger that the supply side, but you dont want to connect more devices to that panel has supply for. Currently netbox does not tell you how much power you have allocated in total on a power feed.
