### ISSUE TITLE
Saf-D-Grid Terminal Type

### ISSUE THREAD

**Issue by martink2** [netbox-community/netbox#5980]
### NetBox version

v2.10.6

### Feature type

Change to existing functionality

### Proposed functionality

A power connector type used for many more recent routers (Ex. Cisco ASR9901 etc) is missing as a choice

I propose that:
Type 'Saf-D-Grid' is added to Power Outlet Template
Type 'Saf-D-Grid' is added to Power Port Template

### Use case

Correctly model network equipment using that connector type.

**Comment by PeterGeh** [comment]
Yes I support this request, several new devices require this power cable type.

**Comment by anafieres** [comment]
Thumbs up, we urgently need that for  correct modelling.

**Comment by jeremystretch** [comment]
LOL who names these things

**Comment by jeremystretch** [comment]
Adding this type will probably require introducing a new "proprietary" category of power port/outlet types.
