### ISSUE TITLE
Missing Paging on dcim interfaces causes browser to freeze on large datasets

### ISSUE THREAD

**Issue by rungej** [netbox-community/netbox#5988]
### NetBox version

v2.10.4

### Python version

3.8

### Steps to Reproduce

When having large datasets for interfaces on a device (OLT unit with up to 16,384 ports) browser freezes loading the page due to no paging of interface list.

API supports paging, however feature has not been implemented

### Expected Behavior

Paging of interface list as per other components (such as device list)

### Observed Behavior

browser freezes

**Comment by DanSheps** [comment]
Thank you for opening a bug report. Remember to provide detailed steps that someone else can follow using a clean installation of NetBox to reproduce the issue. Remember to include the steps taken to create any initial objects or other data.

**Comment by rungej** [comment]
@DanSheps 

As per a standard OLT setup, add a new interface (as bulk creation):
Name: 1/1/[1-16]/[1-16]/[1-64]

After creation try to view the interface list. You can also try this with a smaller dataset such as 1/1/[1-2]/[1-16]/[1-64]

API Supports paging of data but just needs to be added to front end

**Comment by jeremystretch** [comment]
@rungej It's a good idea, though not strictly a bug. I've opened #6001 as a feature request for the proposed work.
