### ISSUE TITLE
 Search form edit

### ISSUE THREAD

**Issue by Aaltaher95** [netbox-community/netbox#5996]
### NetBox version

v2.9.0

### Feature type

Change to existing functionality

### Proposed functionality

hi there
i am currently using netbox to automate my company's server list
i added 10 custom fields
i want to edit the devices search form to delete or hide non required fields "for example in my situation there is no need for Has local config context data "

### Use case

when the user clicks on devices link,
a list of all records appears on left
search form appears on the right
the form currently requires drag down the mouse to find the custom fields and search using them
i hope to find a way to hide unrequired fields

**Comment by DanSheps** [comment]
Thank you for opening a bug report. I was unable to reproduce the reported behavior on NetBox v2.10.6. Please re-confirm the reported behavior on the current stable release and adjust your post above as necessary. Remember to provide detailed steps that someone else can follow using a clean installation of NetBox to reproduce the issue. Remember to include the steps taken to create any initial objects or other data.

**Comment by jeremystretch** [comment]
> the form currently requires drag down the mouse to find the custom fields and search using them

Just so I'm clear, the proposal here is to implement some complex mechanism to allow users to customize the form fields displayed just to save a bit of scrolling? That doesn't sound like a worthwhile expenditure of development effort.

**Comment by cpmills1975** [comment]
There are quite a few issues in the pipeline where the suggestion is to add to the UI to make the app easier to use and navigate. Spending a lot of time developing functionality to remove elements of the UI that aren't interesting to a small group of users doesn't make sense IMO.

**Comment by jeremystretch** [comment]
#5893 will introduce a major UI overhaul in v2.12. Let's revisit this then if still needed.
