### ISSUE TITLE
General code cleanup - cleanup HTML var spacing

### ISSUE THREAD

**Issue by matt852** [netbox-community/netbox#6007]
### NetBox version

v2.10.6

### Python version

3.8

### Steps to Reproduce

This is simply general code cleanup.  It is not a specific bug.

### Expected Behavior

n/a

### Observed Behavior

n/a

This is not a reproducible bug.  However in 4 different HTML files, there are some `{% tag %}` tags with incorrect spacing.  While functional, they do not conform to the existing standards for all other tags.

For example, `{% tag %}` can be found written as either `{%tag %}` or `{% tag%}` in some places.

**Comment by jeremystretch** [comment]
The UI is currently being overhauled for v2.11 under #5893. We're not doing any maintenance on the current templates until that initiative has been completed.
