### ISSUE TITLE
Virtual chassis search displays duplicate entries

### ISSUE THREAD

**Issue by maximumG** [netbox-community/netbox#6010]
### NetBox version

v2.10.6

### Python version

3.8

### Steps to Reproduce

1. Create a device named test-vc-1-1
2. Create a device named test-vc-1-2
3. Create a virtual chassis named test-vc-1 and bundle the two device created in 1. and 2.
4. In the virtual chassis view perform a search by name using test-vc-1

### Expected Behavior

The list view should display only one entry for the virtual chassis (check the screenshot of the search using Nebox 2.9 release)

### Observed Behavior

The list view displays twice the same entry for the virtual chassis, one per member (check the screenshot of the search using Nebox 2.10.6 release)

### Expected behaviour in netbox 2.9

![Netbox 2.9](https://user-images.githubusercontent.com/4469833/111668228-d558f600-8815-11eb-9e81-def201f1e744.png)

### Observed behaviour in netbox 2.10

![image](https://user-images.githubusercontent.com/4469833/111668410-033e3a80-8816-11eb-8768-78493606ad7c.png)

### Solution hint

After some code investigation it seems that the `VirtualChassisFilterSet.search` method in `dcim/filter.py` has something wrong with the [forged queryset](https://github.com/netbox-community/netbox/blob/91fe80f73c12bb4182ee892ca612252e9a30126b/netbox/dcim/filters.py#L1078).

```python
    def search(self, queryset, name, value):
        if not value.strip():
            return queryset
        qs_filter = (
            Q(name__icontains=value) |
            Q(members__name__icontains=value) |
            Q(domain__icontains=value)
        )
        return queryset.filter(qs_filter)
```

When you modify the queryset with the following code, the entry is not duplicated anymore in the WebUI.

```python
    def search(self, queryset, name, value):
        if not value.strip():
            return queryset
        qs_filter = (
            Q(name__icontains=value) |
            Q(members__name__icontains=value) |
            Q(domain__icontains=value)
        )
        return queryset.filter(qs_filter).distinct() # adding distinct de-duplicate the VC
```

**Comment by jmanteau** [comment]
I confirm to have seen the same behavior and I indeed would like have it fixed as well ! Nice finding !

**Comment by ziggekatten** [comment]
Yep, funny enough I was demoing netbox for a colleague today and experienced this as well. 

We are running 2.10.6

**Comment by thomas-rotszyld** [comment]
same problem here !!! easy fix

**Comment by jeremystretch** [comment]
Open for volunteers

**Comment by maximumG** [comment]
@jeremystretch I can take the lead on this one if you agree. Quick and easy fix.
