### ISSUE TITLE
Inherit VRF for child prefix from parent prefix

### ISSUE THREAD

**Issue by Ordauq** [netbox-community/netbox#6012]
### NetBox version

v2.10.6

### Feature type

Change to existing functionality

### Proposed functionality

When adding new child prefixes inherit VRF from parent prefix  (/ipam/prefixes/add/?prefix=192.168.0.0/30)

### Use case

In my environment we have many parent prefixes (container type) each of which is in different VRF.
When I or my colleagues creating new child prefix (for example /30 child in /24 parent prefix) VRF field is not inherited from parent which leads to inconsistency. 
We need manually to choose right VRF for every child, otherwise it land to Global default VRF.

### Database changes

I believe it not needed

**Comment by jeremystretch** [comment]
> When adding new child prefixes inherit VRF from parent prefix (/ipam/prefixes/add/?prefix=192.168.0.0/30)

This is already the case when clicking the "add prefix" button when viewing a prefix within the NetBox UI: The link automatically sets the parent's VRF.

**Comment by Ordauq** [comment]
You are right, if I'm clicking on this button everything working as expected. (first available prefix is chose)
Thanks for pointing this out.

But if I'm choosing specific prefix from list it don't work.
For example, first available network is /29 (add prefix button action) but I'm want to create subnet with size /28 or more, so I'm need to find this network manually (url - https://ipam.mng/ipam/prefixes/add/?prefix=availiable_prefix/28)

**Comment by jeremystretch** [comment]
This sounds similar to #5703 then.
