### ISSUE TITLE
Virtual Machine Interfaces table should be moved to separate tab

### ISSUE THREAD

**Issue by cpmills1975** [netbox-community/netbox#6014]
### NetBox version

v2.10.7

### Feature type

Change to existing functionality

### Proposed functionality

All of the component tables on Devices have moved from the device page to separate tabs. I'm proposing that the Interfaces table for Virtual Machines also becomes its own tab to mimic the Device page.

### Use case

While most users probably aren't dealing with huge lists of interfaces on Virtual Machines, the UX should be as consistent as possible between Devices and Virtual Machines.

### Database changes

None

### External dependencies

None

**Comment by jeremystretch** [comment]
I agree, however the UI is currently in flux pending the v2.12 work. Going to mark this as blocked for now and tag it for v2.12.

**Comment by cpmills1975** [comment]
As soon as there is a clone-able version with the UI improvements in it, I'd been keen to take it for a spin in my dev environment. Is this likely to be on the devel branch after the release of 2.11 or are you thinking of running a separate branch for the UI changes?

**Comment by jeremystretch** [comment]
We decided to push the UI overhaul to v2.12, so I'm going to knock this out shortly.

**Comment by jeremystretch** [comment]
Fixing this under v2.11 since we've tweaked the generic templates a good bit already.
