### ISSUE TITLE
Add Cable Trace option in additional pages

### ISSUE THREAD

**Issue by jcralbino** [netbox-community/netbox#6017]
### NetBox version

v2.10.5

### Feature type

Change to existing functionality

The blue cable trace button used for the Cable trace is currently available only on:
- https://netbox/dcim/interfaces/<interfaceID>/
![image](https://user-images.githubusercontent.com/44149262/114060193-6cedb980-9895-11eb-93f1-3a9fa763d061.png)

- https://netbox/dcim/interfaces/dcim/devices/<DeviceID>/interfaces/

![image](https://user-images.githubusercontent.com/44149262/114060131-58a9bc80-9895-11eb-9120-e978d422e678.png)

### Proposed functionality

In order to improve usability we should add this in more places. Namely on:
- Within a cable page (https://netbox/dcim/cables/<CableID>/ ) as shown in the picture
![image](https://user-images.githubusercontent.com/44149262/114060502-bb9b5380-9895-11eb-9dac-c1b82068b22e.png)

- Within the Interface connections page (https://netbox/dcim/interface-connections/ )
![image](https://user-images.githubusercontent.com/44149262/114060648-e1285d00-9895-11eb-88eb-9c4db1d90776.png)

### Use case

Utilization of the Cable trace functionality will be easier, and usability of the product increased.

### Database changes

None

### External dependencies

None

**Comment by jeremystretch** [comment]
What specific changes are you proposing? Screenshots would help. Also note that one of your URLs above is invalid.

**Comment by jcralbino** [comment]
I believe it is more clear now.
thanks.

**Comment by jeremystretch** [comment]
Cable traces have to start from a specific termination point, not the cable itself. The two proposed locations for a "trace" button don't imply a specific termination point.

**Comment by jcralbino** [comment]
Although i do not want to dwell on this, i would like to understand the scenarios where the interface is not a specific termination point. 
I understand your comment in terms of cable page view, where a cable is just one component within an end to end path. But for something within the interface page view that is not correct i believe.
