### ISSUE TITLE
Speed up API Bulk Updates

### ISSUE THREAD

**Issue by fabi125** [netbox-community/netbox#6020]
### NetBox version

v2.10.6

### Feature type

Change to existing functionality

### Proposed functionality

Bring the performance of bulk updates via the API in line with the UI.

### Use case

Updating ~400 devices via the PATCH bulk update endpoint takes on my machine around 40s. Doing the exact same update via the UI takes around 15s.

It would be great if the API could provide the same performance as the UI.

In some very basic tests I tried removing https://github.com/netbox-community/netbox/blob/v2.10.6/netbox/netbox/api/views.py#L82 which resulted in an around 25% speedup, lowering the API time to 30s. So maybe adding a parameter that prevents from all data being returned via the API is a good step?

The API bulk update code looked sufficiently different from the UI bulk update code that I wasn't able to try out more (I'm not as familiar with the NetBox code as I'd like to be).

### Database changes

n/a

### External dependencies

n/a

**Comment by jeremystretch** [comment]
> So maybe adding a parameter that prevents from all data being returned via the API is a good step?

The behavior of the REST API must be consistent, and it must return all affected objects. I'm open to suggestions for optimization, however without a specific proposal that doesn't compromise the preceding two points this isn't actionable.
