### ISSUE TITLE
Allow plugins to inject javascript in all pages

### ISSUE THREAD

**Issue by fabi125** [netbox-community/netbox#6021]
### NetBox version

v2.10.6

### Feature type

New functionality

### Proposed functionality

Currently the types of pages plugins can add content to are limited. I'm proposing to let plugins add javascript in all pages.

### Use case

We want to use this to add little snippets like pressing `/` to jump to the searchbox.

### Database changes

None (I think)

### External dependencies

None

**Comment by jeremystretch** [comment]
My immediate concern with this is that AFAIK there's no feasible way to "scope" the Javascript to avoid it interfering with core or vice versa.

Beyond that though, this should already be doable using template extensions: Your plugin can embed a Javascript inclusion tag on any of the extendable pages.

**Comment by fabi125** [comment]
That's fair. I guess the biggest blocker in doing that for us would be to allow plugins to extend the main/home page.

**Comment by jeremystretch** [comment]
We could potentially look at doing that for v2.12. There's already a huge UI refresh underway for v2.11 as it is, and I'd prefer to avoid introducing any additional change during this time if it can be avoided.

**Comment by jeremystretch** [comment]
Closing this out at least until v2.12 is released, at which point we can re-evaluate options.
