### ISSUE TITLE
BANNER_BOTTOM text does not display

### ISSUE THREAD

**Issue by crouthamela** [netbox-community/netbox#6023]
### NetBox version

v2.10.6

### Python version

3.7

### Steps to Reproduce

1. Enter some text into BANNER_BOTTOM in configuration.py
2. Restart netbox services
3. Refresh main NetBox page

### Expected Behavior

Banner to appear at bottom of the page with defined text

### Observed Behavior

Banner does not appear at bottom of the page with defined text.

The defined text does show in the page source though:

            <div class="alert alert-info text-center banner-bottom" role="alert">
                 Test bottom
            </div>

**Comment by engageant** [comment]
Any chance you have uBlock Origin installed? I can reproduce this behavior when uBlock is enabled for the site. It works as expected when I turn the plugin off.

**Comment by crouthamela** [comment]
Oh wow, good catch. uBlock didn't show a counter in the icon so I didn't consider it.

It looks like it doesn't like the phrase "banner" in the class. I changed the three code references to from "banner-bottom" to "bottom-message" and it now displays correctly with uBlock enabled.

**Comment by jeremystretch** [comment]
Not really a bug, but probably a common enough issue, and a simple fix.

**Comment by crouthamela** [comment]
> Not really a bug, but probably a common enough issue, and a simple fix.

Thanks, I understand it isn't really your problem, but ad blockers are so common and seems like an easy workaround.
