### ISSUE TITLE
REMOTE_AUTH_AUTO_CREATE_USER needs default changed to True

### ISSUE THREAD

**Issue by crouthamela** [netbox-community/netbox#6024]
### Change Type

Correction

### Area

- [ ] Installation instructions
- [X] Configuration parameters
- [ ] Functionality/features
- [ ] REST API
- [ ] Administration/development
- [ ] Other

### Proposed Changes

In Optional Settings:

 REMOTE_AUTH_AUTO_CREATE_USER
 Default: False

should be:

 REMOTE_AUTH_AUTO_CREATE_USER
 Default: True

To match the shipped configuration.py default.

**Comment by jeremystretch** [comment]
The default value for `REMOTE_AUTH_AUTO_CREATE_USER` (which not defined) is indeed `False` as the documentation states; see [`settings.py`](https://github.com/netbox-community/netbox/blob/0321ae0a7f0638487bdfcced8b4feb993ee3e44d/netbox/netbox/settings.py#L106). I'm open to changing either the default value or its value within the example config given a compelling argument, however the documentation is correct as it stands.

**Comment by crouthamela** [comment]
Ah ok. I didn't realize the example config differed from the default settings.py. In that case it was just some confusion on my part and we can close this out.
