### ISSUE TITLE
Tags search or count on each models

### ISSUE THREAD

**Issue by hyudra** [netbox-community/netbox#6038]
### NetBox version

v2.10.4

### Feature type

Change to existing functionality

### Proposed functionality

I remembered that old version can see how many tags it have on each models. Seem gone in v2.10.
Also, sometimes we want to search where's the tags assigned to. But we need to access to each models on GUI. Which sometimes not convenient to find.

### Use case

It'll make better experience to find where tags using and when we'd like to delete the tags.

### Database changes

No Changes

### External dependencies

No dependencies

**Comment by jeremystretch** [comment]
This has been implemented for the upcoming v2.11 release.
