### ISSUE TITLE
Use Postgres' COPY protocol when reserving IPs in a prefix

### ISSUE THREAD

**Issue by jeromer** [netbox-community/netbox#6049]
### NetBox version

v2.8.7

### Feature type

Change to existing functionality

### Proposed functionality

If I'm not mistaken (I'm far from being a Django  expert) in [PrefixViewSet.available_ips](https://github.com/netbox-community/netbox/blob/master/netbox/ipam/api/views.py#L191) Netbox will loop over requested IPs and `INSERT` them one by one. The idea is to use the Postgres [COPY](https://www.postgresql.org/docs/current/sql-copy.html) protocol so all IP addresses are added in one go. Obviously this will only benefit for Postgres users.

### Use case

While this is functional, this becomes slow when a user wants to reserve for example 15 IPs in a given prefix as Postgres will trigger some internal machinery (index updates for example) for each `INSERT`. So the more `INSERT` the slower. Which means an increasing risk of lock contention as the Postgres advisory lock will be released only after all the DB operations (`INSERT`s and subsequent `SELECT` for the output serializer) are executed which increases the risk of lock contention proportionally to the amount of IP which need to be reserved.

Using the `COPY` protocol would help making the creation phase much faster, thus reducing lock contention.

### Database changes

No schema changes are required

### External dependencies

No new dependency is required.

**Comment by jeremystretch** [comment]
Creating each instance individually is necessary to ensure both the enforcement of assigned permissions and the creation of the necessary change records.
