### ISSUE TITLE
Show Status Labels next to racked devices

### ISSUE THREAD

**Issue by nikor30** [netbox-community/netbox#6059]
### NetBox version

v2.10.7

### Feature type

New functionality

### Proposed functionality

Add status lables next to the rendred devices in rack overview
Possibility to hid or show this lables and maybe aextend also with IP or Name

### Use case

It would be better for planing overview to see what kind of status the devices in the racks have and maybe also as mentioned some other label options like IP or Name

![grafik](https://user-images.githubusercontent.com/4319444/112616772-689cb780-8e24-11eb-9fe2-484026af6821.png)

**Comment by jeremystretch** [comment]
This doesn't seem very practical IMO, primarily because it assumes that the viewer has memorized all available device statuses. Also consider #51 which (if we ever get around to implementing) would present half-U devices at 50% of the unit height.

**Comment by nikor30** [comment]
So maybe it´s a flag which you cn blend in or switch of like a lable on the device it self. And regarding memorizing, I think people who work a lot wiht netbox will be able to distinc betweeen the colors depending if it´s planed or not. Point I wanted to make today you don´t have any indication about the status of the devices in rack view. So maybe design wise a other soultion would be nice I am not a GUI expert :-D

**Comment by networkhorse** [comment]
> 
> 
> So maybe it´s a flag which you cn blend in or switch of like a lable on the device it self. And regarding memorizing, I think people who work a lot wiht netbox will be able to distinc betweeen the colors depending if it´s planed or not. Point I wanted to make today you don´t have any indication about the status of the devices in rack view. So maybe design wise a other soultion would be nice I am not a GUI expert :-D

This assumes that people aren't colourblind, but I don't like the idea of forcing people to memorise anything, it makes training painful if people have never touched Netbox.

**Comment by nikor30** [comment]
Hi, so the labele can be shown in the color based on what the users decided and it will just show the short acronmyn to safe space and when you hover over it it can be expant to the full description so no memorycing needed and colorblind can read.

**Comment by networkhorse** [comment]
I really wonder if there is really any need for this. I think the rack overview is nice as a quick "where is everything", but if you need more detail you should use the table instead, in my opinion.

**Comment by jeremystretch** [comment]
Echoing what others have said, the purpose of the elevation diagram is just that: to show a rack's elevation, as if you were standing in front of it. Specific details about the devices within the rack are best conveyed elsewhere.

**Comment by jbakklund** [comment]
I find the shortcut highlighted below, and the resulting list, much better suited to list specific details about all the devices in that specific rack. Considering the shortcuts point of origin though, this link could very well have included the &sort=(+/-)position parameter to make the resulting list mimic the elevation diagram by default.

![Shortcut to list of Devices in rack](https://user-images.githubusercontent.com/33431806/114883752-7c28b600-9e05-11eb-8132-8d4fbecd64f6.png)
