### ISSUE TITLE
Device objects error when deleting its primary IP address

### ISSUE THREAD

**Issue by hyudra** [netbox-community/netbox#6069]
### NetBox version

v2.10.6

### Python version

3.8

### Steps to Reproduce

1. Create device Test_01
2. Create test-interface and binding to to Test_01
3. Create  IPaddress 1.1.1.1/24 and binding to test-interface
4. Set primary IP of Test_01 to 1.1.1.1/24
5. Delete IPaddress 1.1.1.1/24 
6. View Device Test_01 and it'll get an error of IPaddressDoesNotExist

### Expected Behavior

It should automatically remove primary IP address of device and access to device normally

### Observed Behavior

<class 'ipam.models.IPAddress.DoesNotExist'>

IPAddress matching query does not exist.

Python version: 3.8.8
NetBox version: 2.10.6

**Comment by jeremystretch** [comment]
This bug report doesn't contain enough information for someone else to reproduce the bug. Please expand on your steps to reproduce to include detailed instructions.

**Comment by engageant** [comment]
I'm unable to reproduce this on 2.10.8, but it sounds like a browser cache issue.

**Comment by hyudra** [comment]
I already clear all cache , change browser and try reproduce. It happened every time.
I'm using netbox-docker for building.

Weird that I tried on netboxdemo.com which is v2.10.1, but it didn't have same problem

**Comment by jeremystretch** [comment]
I'm also not able to reproduce this on v2.10.8.

**Comment by hyudra** [comment]
I found this issue kinda same as #3304 which resolve since v2.8.5

As I'm using netbox-docker, I'm not sure that it's relate to docker or not. I can view the device after restart whole docker. So, maybe it's a caching issue.

Should I open this issue to netbox-docker instead?

**Comment by hyudra** [comment]
After I upgraded to v2.10.8, seem it fixed.

I'll close this issue now. Thank you all.
