### ISSUE TITLE
Add specifity when deleting objects

### ISSUE THREAD

**Issue by travisperry** [netbox-community/netbox#6076]
### NetBox version

v2.10.4

### Feature type

Change to existing functionality

### Proposed functionality

The delete button when you drill into a prefix should be renamed to prevent confusion.  It is easy to delete the entire prefix when trying to delete a selected IP address since the button for delete selection is at the bottom of the page.  It would be helpful to rename the Delete button here to "Delete Prefix"

### Use case

Select IPAM > Prefixes
Drill into  one of the existing prefixes.
On the screen you intend to delete an address, by selecting the IP check box.  It is easy to mistake the Delete button for the Delete selection button

**Comment by networkhorse** [comment]
I would suggest making this a system-wide change if it happens. Rather than just having it as a one-off for Prefixes and IP Addresses, have it for anything.

`Delete {model.type}` sort of deal.

**Comment by ljb2of3** [comment]
Yes! I've managed to delete prefixes by mistake because I select some IPs I want to delete then mash the big red delete button instead of the bulk actions button I really wanted.

**Comment by jeremystretch** [comment]
I'm not sure I buy the usability argument here. These buttons are in the same place for every object in NetBox; their functionality is very consistent. Additionally, the confirmation dialog explains precisely what is going to be deleted if you continue; I would expect that to be more than sufficient to address simple user error.

> Delete {model.type} sort of deal.

If we expand the delete button, we need to keep it consistent with the other buttons as well:

![Screenshot_2021-04-09 10 112 0 0 15 - NetBox](https://user-images.githubusercontent.com/13487278/114214947-fb644880-9932-11eb-8365-b2ae9559caa9.png)

It gets redundant very quickly (especially for models with longer names) and consumes screen space unnecessarily.
