### ISSUE TITLE
Add additional Status for Racks or Devices

### ISSUE THREAD

**Issue by markuszeiter** [netbox-community/netbox#6078]
### NetBox version

v2.8.9

### Feature type

New functionality

### Proposed functionality

I would like to be able to add (on demand in UI or config file) additional RACK or DEVICE STATUS CHOICES.

### Use case

For the rack use case we have different states from our data center team which we would like to represent in netbox.

### Database changes

not sure

### External dependencies

not sure

**Comment by jeremystretch** [comment]
This has been proposed in the past and we've opted to stick with the hard-coded statuses because they're standardized and more efficient. You also have the option of employing custom fields and/or tags to further classify devices and racks per your needs.

**Comment by markuszeiter** [comment]
@jeremystretch ok, thank you very much for the quick feedback.
