### ISSUE TITLE
VLAN Group Creation Scope Inconsistent

### ISSUE THREAD

**Issue by bryanward-net** [netbox-community/netbox#6098]
### NetBox version

v2.11-beta1

### Python version

3.9

### Steps to Reproduce

1. Create a new VLAN Group with the scope of DCIM>Site.  Note that it asks for a Region, Site Group, and Site.
2. Create a new VLAN Group with the scope of DCIM>Site Group.  Note that it asks for a Site Group only.

### Expected Behavior

VLAN Groups being created in the DCIM>Site Group scope should also ask for a Region.

### Observed Behavior

VLAN Groups being created in the DCIM>Site Group scope only ask for a Site Group and not a Region.

Reproduced on beta.netbox.dev

**Comment by jeremystretch** [comment]
> VLAN Groups being created in the DCIM>Site Group scope only ask for a Site Group and not a Region.

This is intentional. Regions and site groups exist in parallel: there is no relationship between the two. A site can be assigned to a group and/or region, but groups cannot be assigned to regions.
