### ISSUE TITLE
Custom field on device if role

### ISSUE THREAD

**Issue by andershagman** [netbox-community/netbox#6103]
### NetBox version

v2.10.3

### Feature type

Change to existing functionality

### Proposed functionality

Be able to show/hide/disable custom fields on devices if they are of a certain role.

### Use case

We have 5 different groups working in Netbox, Comm, Security, Storage, Appl.
We all have our own custom fields and some of them required. This results in having 10 different custom fields on a patch pannel with a demand on filling in hard drive size.

If combined with device role we can control where the filed will show up.

### Database changes

Probably.

### External dependencies

none

**Comment by jeremystretch** [comment]
That doesn't sound like it would scale very well. What specific changes to the model are you proposing? How would you declare the conditions under which each custom field would or would not be displayed?

**Comment by samschmitt22** [comment]
I would love to see a feature as well, although I'm not sure how it could be implemented easily. Instead of just adding a custom field to the "device role" object , one would need to be able to add a custom field to a specific device role that already exists.

**Comment by jeremystretch** [comment]
Closing this out as further detail concerning the proposed implementation has not been provided.
