### ISSUE TITLE
Rack list includes Group column instead of Location

### ISSUE THREAD

**Issue by rodvand** [netbox-community/netbox#6104]
### NetBox version

v2.11-beta1

### Python version

3.8

### Steps to Reproduce

1. Create Site "Site A"
2. Create Location "Location A" with "Site A" as Site
3. Create Rack A and select Site as "Site A" and Location as "Location A"
4. Go to the Rack view https://beta.netbox.dev/dcim/racks/?site_id=25 and see the column Group instead of Location in the view

### Expected Behavior

The Group column should probably be the Location column.

### Observed Behavior

Column Group is in the list where Location probably should be.

**Comment by jeremystretch** [comment]
Thanks for the detailed bug report!
