### ISSUE TITLE
Check boxes in table Cluster -> Virtual Machines

### ISSUE THREAD

**Issue by rodvand** [netbox-community/netbox#6105]
### NetBox version

v2.11-beta1

### Python version

3.8

### Steps to Reproduce

1. Create a Cluster (type can be any)
2. Assign a Virtual Machine to the Cluster
3. Go to the cluster and select the tab virtual machines (eg https://beta.netbox.dev/virtualization/clusters/9/virtual-machines/)

### Expected Behavior

While Devices can be removed from a Cluster without any issue, I expect the Virtual Machine table here should not include check boxes as cluster is required on a VM.

### Observed Behavior

Check boxes in the table, but no action button on the bottom.

**Comment by jeremystretch** [comment]
Nice, keep these bug reports coming! :slightly_smiling_face:
