### ISSUE TITLE
Interface Assignments to a LAG Parent

### ISSUE THREAD

**Issue by fpessoanunes** [netbox-community/netbox#6114]
### NetBox version

v2.11-beta1

### Feature type

Change to existing functionality

### Proposed functionality

Virtual interfaces can now be assigned to a "parent" physical interface, however is also very common to have subinterfaces on LAG interfaces. I think would be great to permit LAG interfaces as parent from virtual interfaces as well.

### Use case

Examples:
- Assign virtual interface Bundle-Ether100.1234 as children of the LAG interface Bundle-Ether100
- Assign virtual interface Port-channel1.100 as children of the LAG interface Port-channel1
- Assign virtual interface ae0.100 as children of the LAG interface ae0

**Comment by jeremystretch** [comment]
> I think would be great to permit LAG interfaces as parent from virtual interfaces as well.

This was enabled just recently under #6106.
