### ISSUE TITLE
Add stats pane to location view

### ISSUE THREAD

**Issue by dreng** [netbox-community/netbox#6126]
### NetBox version

v2.11.0-dev

### Feature type

New functionality

### Proposed functionality

Please add a stats pane to the location view like it is implemented at the site view.

### Use case

This feature is implemented on the site view already. It would be handy to have it on the location view as well.

### Database changes

none

### External dependencies

none

**Comment by jeremystretch** [comment]
> Please add a stats pane to the location view like it is implemented at the site view.

What specifically would you like to be added? Only racks and devices can be assigned to locations, and the count of each is already included.

**Comment by dreng** [comment]
Good point. I found it useful to have stats on the site view because they count recursively (site + all (sub)locations). I see that stats are not necessary on the locations view while it would be very handy to list devices recursively then. That would be a duplicate of #6124 (see my last comment there).
