### ISSUE TITLE
Change name of existing custom field

### ISSUE THREAD

**Issue by top1ing** [netbox-community/netbox#6127]
### NetBox version

v2.11-beta1

### Python version

3.8

### Steps to Reproduce

1. Create "Text" type custom field with name "cf_text-field" on DCIM > device
2. Go to device, for example "DC-Berlin", and add text "Some text" in created custom field "cf_text-field".
3. Go to Device page and add "cf_text-field" field to table view.
4. Go to Admin page and change name of custom field "cf_text-field" to "cf_text-field_changed".

### Expected Behavior

Value of custom field remains in Device, but with new custom field name.
On Devices page, the "cf_text-field" column name changes to "cf_text-field_changed".

### Observed Behavior

On Device "DC-Berlin" page custom field "cf_text-field_changed" displays with empty value.
On Devices page column "cf_text-field" is still displays, but new custom field "cf_text-field_changed" also available in configure of table view.

**Comment by jeremystretch** [comment]
Thank you for submitting this issue, however it appears that this topic has already been raised. Please see issue #5652 for further discussion.
