### ISSUE TITLE
Thola support to query network devices via SNMP

### ISSUE THREAD

**Issue by nick4me** [netbox-community/netbox#6132]
### NetBox version

v2.10.4

### Feature type

Change to existing functionality

### Proposed functionality

support to query network devices via SNMP and auto-discover (onbording process) using the Thola REST API.

### Use case

it is very practical and useful that napalm is integrated into nautobot.
however, many of (our) existing network devices can only or at least easier be queried via SNMP.

here it would be great if thola were also integrated in addition to napalm:
https://github.com/inexio/thola
Thola supports a very large number of network devices and can be easily integrated via REST API.
Thola can also automatically identify a network device and determine the manufacturer, model and serial number.

### External dependencies

https://github.com/inexio/thola

**Comment by jeremystretch** [comment]
> it is very practical and useful that napalm is integrated into nautobot.

I think you're in the wrong place.
