### ISSUE TITLE
Support for Journal Entry with Bulk Update

### ISSUE THREAD

**Issue by a31amit** [netbox-community/netbox#6136]
### NetBox version

v2.11.0-beta1

### Feature type

New functionality

### Proposed functionality

Currently, a journal entry has to be added or create on each device. but this might lead to so much repeat of work for users when they wanted to add the same journal entries associated with multiple devices. 

for example of a journal entry - "Change request ID - XXXXXX for OS upgrade " 
here change request could include 1 or more servers if users have to add this for 1 device which is fine but if there are more than 1, this became a lot of repeat work for them. 

While I know that 2.11 is still in beta, however, I believe this feature would be worth including in netbox. 

### Use case

Having a feature to associate the same journal entry with multiple devices would ease users where multiple devices should have the same journal entry. 

Feature to add a journal entry with a selection of bulk devices on primary models at least would help users with avoid lot of repeat work. 

### Database changes

I believe no but core maintainers would have a better understanding.

**Comment by jeremystretch** [comment]
The motivation behind introducing this feature was to support recording notes which are _unique_ to individual objects. As soon as you find yourself wanting to apply the same note to multiple objects, this is a sign that you should have a structured system in place to handle this data. Remember, journal entries are just free-form notes: They aren't a good candidate for recording things like planned software updates (as implied by your use case), because you likely want to record things like the OS version in some structured format.

**Comment by a31amit** [comment]
This is true if user document those exact os version, May be my example doesn’t show the proper need here. 

However in enterprise, its standard practice to open changerequest or task that require same nature of small or large work on multiple hosts. 

With that it’s makes to just a standard change or tasks ID with same comments. 

Another better examples could be - 

- if you just updated a single package under the task, we don’t needed version to mentioned in netbox as it’s document under the task but same task or comment reference back to multiple host that were included in this task. Even if users wants to know their package version it can be other source than netbox. 

- now another  task where we swapped server rack unit on multiple server, we can document exact change in netbox device model. But everything was under same task or changerequest so for those there is no different needed to make journal entry unique of specific because model show their current RU but just task ID needed to be added in journal entry. 


The whole point here is in day-to-day work there are many edge cases when similar journal entry would be users correct intention but to allow users to make bulk updates on multiple servers where it needed. There is no restriction if someone would be doing same thing by using api or loop over multiple server to put same journal entry comment . But it would be ease on web ui. That been said I don’t need this on api bulk just in web user interface.
