### ISSUE TITLE
Add Stats and  Images view to Locations

### ISSUE THREAD

**Issue by jcralbino** [netbox-community/netbox#6142]
### NetBox version

v2.11

### Feature type

Change to existing functionality

### Proposed functionality

Much like we have in the Site option (https://beta.netbox.dev/dcim/sites/24/). where a specific page is show for Stats where racks, devices or circuits is shown like the image bellow
![image](https://user-images.githubusercontent.com/44149262/114430636-eef42000-9bbe-11eb-8c1d-368c00632c7f.png)

In the new design where a location may represent a room, or some other nested object( room/aisle), it will be interesting to have the same stats information provided.
When Location represents a DC Room we can easily identify all the Racks inside, and most important we can also use the Images tab to document to room layout. 

### Use case

When Locations represent specific DC Rooms, or technical rooms the introduction of these fields under the Location main page (https://beta.netbox.dev/dcim/locations/8/) can be used to improve the documentation of the environment:

- Images can be used to identify the rack layouts, and details on how to reach the locations
- Stats can be used to summarize the total number of devices and racks inside that location.

### Database changes

Additional fields are required to add the details for Images associated with a location. 

### External dependencies

none

**Comment by jeremystretch** [comment]
> In the new design where a location may represent a room, or some other nested object( room/aisle), it will be interesting to have the same stats information provided.

This was proposed in #6126; please see the discussion there.

> When Location represents a DC Room we can easily identify all the Racks inside, and most important we can also use the Images tab to document to room layout.

Please open a separate feature request for this.
