### ISSUE TITLE
Connection Icon for Power Outlets/Ports

### ISSUE THREAD

**Issue by avidpontoon** [netbox-community/netbox#6145]
### NetBox version

v2.10.8

### Feature type

Change to existing functionality

### Proposed functionality

When connecting power cables, the icon is the same as the one for network cable connections, this should be changed to an icon that resembles power to tidy up the UI.

Current class is mdi-ethernet-cable. Could this be changed for example to something like mdi-power-plug-outline?

### Use case

This would cleanup the UI, rather than adding functionality.

**Comment by jeremystretch** [comment]
It's a neat idea, but this imposes a bit too much overhead for the minimal value delivered, especially considering that we don't have icons to differentiate among other types of cabling.
