### ISSUE TITLE
Background tasks site returns 404

### ISSUE THREAD

**Issue by rodvand** [netbox-community/netbox#6155]
### NetBox version

v2.11-beta1

### Python version

3.8

### Steps to Reproduce

1. Go to Profile -> Admin
2. System -> Background tasks

### Expected Behavior

Expected to see the background tasks site.

### Observed Behavior

Page not found error.

**Comment by rodvand** [comment]
It works if I downgrade Django to 3.1.8.

**Comment by jeremystretch** [comment]
Nice catch! Looks like a [catch-all URL pattern](https://github.com/django/django/commit/ba31b0103442ac891fb3cb98f316781254e366c3#diff-0b9b76020bca57d146eddea5c47e1e6a99744ce287a365e18a0d7685dd268f18) was added to the default Django admin site in 3.2. Rearranging our own URL patterns should fix it.
