### ISSUE TITLE
Change in display half depth devices on Rack Elevations

### ISSUE THREAD

**Issue by proudbro** [netbox-community/netbox#6156]
### NetBox version

2.10.9

### Feature type

New functionality

### Proposed functionality

Add on rack layouts in _Rack Elevations_ section  some visual designation for half depth devices mounted on the opposite side of chosen rack side.
It can be shaded unit or so with a name of device. 

Now only full depth devices can be visually distinguished by diagonal stripes.
 ![Front](https://user-images.githubusercontent.com/60253505/114702563-e0c41200-9d2c-11eb-9fda-bcd2ce5bc721.png)
 ![Rear](https://user-images.githubusercontent.com/60253505/114702619-f802ff80-9d2c-11eb-9501-93206a14d626.png)
 
 _Screenshots were made in Netbox beta v2.11_ https://beta.netbox.dev/dcim/rack-elevations/

### Use case

We often plan to install new equipment via Rack Elevations and have to constantly switch between Front/Rear mode to find really free units for devices.  This feature will save us from additional clicks and simplify capacity planning for all Netbox users.

### Database changes

-

**Comment by jeremystretch** [comment]
> We often plan to install new equipment via Rack Elevations and have to constantly switch between Front/Rear mode to find really free units for devices.

Marking a device as "half-depth" implies that the peer unit on the opposite rack face is available for use. If this is not the case (due to physical depth, airflow requirements, etc.), device should be treated as full-depth.

**Comment by proudbro** [comment]
@jeremystretch , I don't suggest to consider such unit as occupied. I just want to see unit more visually differ somehow from others and at the same time be available to add device. 
Some examples:
- More grey-shaded unit. The most obvious way to make it darker
- Has special markup. Hatching?
- Additional marker

**Comment by fabricat** [comment]
I agree with the proposal: from my point of view, this is exactly one of the few features missing in Netbox 😄 

I think the best solution is in the middle:

- showing half-occupied units (on the opposite side) as blank/free is misleading 👎 
- showing half-occupied units the same way as fully-occupied ones is misleading too 👎 
- using a third way (e.g. 50% opacity or a different texture) should work fine 👍 

Details like device name or image can be omitted.
The aim is just to **not confuse partly occupied units** with free ones.

**Comment by candlerb** [comment]
> Marking a device as "half-depth" implies that the peer unit on the opposite rack face is available for use

But only by another device which is also half-depth.

**Comment by jeremystretch** [comment]
I'm going to close this issue in favor of capturing the discussion under #6961, which seems to cover the same concerns but provides a bit more detail on a proposed modification.
