### ISSUE TITLE
Support Markdown rendering in report logs

### ISSUE THREAD

**Issue by PieterL75** [netbox-community/netbox#6157]
### NetBox version

v2.10.5

### Feature type

Change to existing functionality

### Proposed functionality

Allow HTML code in report messages.

### Use case

I have a report that show the available VLANs in a certain range of a VLAN Group.
Currently, it just shows the vlan ID. However, it would be very nice to change that vlan ID to an AHREF html, so that the we can create the vlan with one click.

This is one example, but I'm sure that more ideas can be found that benefit from an HTML encoded output.

**Comment by jeremystretch** [comment]
I'm going to tweak the scope of this to adding Markdown rendering for report log output. That should enable what you want to do. (We generally avoid encouraging people to write raw HTML for various reasons.)
