### ISSUE TITLE
Adding interface type

### ISSUE THREAD

**Issue by takmiz** [netbox-community/netbox#6163]
### NetBox version

v.2.10.4

### Feature type

New functionality

### Proposed functionality

Add bellow type to interface type. I want to use these type in NetBox.

- 10GBASE-SR
- 10GBASE-LR
- 10GBASE-SX

### Use case

My customer use these interface type.

**Comment by jeremystretch** [comment]
These are all transceiver types that are used with the SFP+ interface type. NetBox doesn't currently track transceiver types explicitly, but you can create them as inventory items in the device.
