### ISSUE TITLE
Add interface type for SFP56 (50GE)

### ISSUE THREAD

**Issue by do9xe** [netbox-community/netbox#6168]
### NetBox version

v2.11.0-beta

### Python version

3.9

### Steps to Reproduce

Hello Team,

we have found a false speed in the transceiver-list of the [public netbox beta](beta.netbox.de).
In the list are two QSPF28 Transceivers with 50G and 100G, but there should be only one with 100G. Also the Transceiver-Type `SFP56 (50G)` is missing. We have proposed an update to this List.

Thanks for the awesome project,
Adrian & Hendrik

![Port-Speed](https://user-images.githubusercontent.com/6275838/114903774-6c19d200-9e17-11eb-83be-9460e462b6d9.png)

### Expected Behavior

Correct values for all interface types

### Observed Behavior

false values for some interface types

**Comment by jeremystretch** [comment]
> In the list are two QSPF28 Transceivers with 50G and 100G, but there should be only one with 100G.

QSFP28 also [supports 50GE](https://www.fs.com/c/50g-qsfp28-3793). It belongs in the list.

**Comment by jeremystretch** [comment]
FYI this was opened against v2.11-beta but has been added under v2.10 (`develop`).
