### ISSUE TITLE
REST API: GET /api/dcim/interface-connections/ doesn't show connections (p.2)

### ISSUE THREAD

**Issue by proudbro** [netbox-community/netbox#6182]
### NetBox version

v.2.10.10

### Python version

3.6

### Steps to Reproduce

This issue based on https://github.com/netbox-community/netbox/issues/6081

1. Create test device "TEST" with interfaces components
2. Create cable connections for interfaces of test device with any other devices
3. Try to GET <your.netbox.url>/api/dcim/interface-connections/?device=TEST OR GET <your.netbox.url>/api/dcim/interface-connections/?device_id=<id>

### Expected Behavior

The list of connections of our TEST device with connected devices

### Observed Behavior

Empty list of connections
```
HTTP 200 OK
Allow: GET, HEAD, OPTIONS
Content-Type: application/json
Vary: Accept

{
    "count": 0,
    "next": null,
    "previous": null,
    "results": []
}
```
This worked for sure in Netbox v2.6.6

**Comment by mshems** [comment]
Likely related to: [#5223](https://github.com/netbox-community/netbox/issues/5223)?

**Comment by proudbro** [comment]
> Likely related to: [#5627](https://github.com/netbox-community/netbox/issues/5627)?

It looks like

**Comment by jeremystretch** [comment]
Okay, marking this as a duplicate then.
