### ISSUE TITLE
Show interfaces of child devices on parent device

### ISSUE THREAD

**Issue by promasu** [netbox-community/netbox#6195]
### NetBox version

v2.11.0

### Feature type

Change to existing functionality

### Proposed functionality

It'd would be nice if the interfaces of all child devices are shown on the parent device. Currently it needs a bunch of clicks to get a list of all interfaces etc. which are available on a device if they are provided by a child device.
This makes it unhandy to manage connections on these devices.

The interfaces should be displayed like they are created on the parent maybe stating the child they belong to. Handling would be the same as if they are not provided by a child.

### Use case

Switches like the HP 5400zl have modules which provide the actual switchports, management interfaces etc.
It would make the workflow easier when we have the complete list of interfaces on a glance to get an overview over all connections and free ports etc. and not have to click through all modules

**Comment by jeremystretch** [comment]
This was proposed and rejected back in #970.

> Switches like the HP 5400zl have modules which provide the actual switchports, management interfaces etc.

Modules should not be modeled as device bays, as the hardware installed within them are not independent devices. Support for modeling modules, line cards, etc. was proposed in #824 but never produced a firm addition to the data model.
