### ISSUE TITLE
Expose SESSION_COOKIE_NAME in configuration.py

### ISSUE THREAD

**Issue by mpalmer** [netbox-community/netbox#6197]
### NetBox version

v2.10.6

### Feature type

New functionality

### Proposed functionality

It would be nice to be able to set the `SESSION_COOKIE_NAME` Django setting from within `configuration.py`.

### Use case

It is sometimes necessary to change the cookie in which the session token is stored, for example due to conflicts with another cookie on the same domain.

**Comment by mpalmer** [comment]
I've got a PR for this all ready to go, BTW; I just need this issue accepted to drop it.

**Comment by jeremystretch** [comment]
@mpalmer all yours!

**Comment by mpalmer** [comment]
Thanks.  #6307 dropped like it's hot.
