### ISSUE TITLE
Region-/sitewide defaults for Power

### ISSUE THREAD

**Issue by martinum4** [netbox-community/netbox#6199]
### NetBox version

v2.11-beta1

### Feature type

Change to existing functionality

### Proposed functionality

- Allow default values Voltage and Amperage to be added to Regions and Sites.

If none is given, the values should be taken from the corresponding "higher" entity.

Example:
Region Germany has 230VAC 50Hz defined as default, it is automatically used for the Subregion of Berlin and all Locations in that Region.

### Use case

The proposed functionality makes it faster and easier to add power feeds since the default values match the region the hardware is located in.

**Comment by jeremystretch** [comment]
> Allow Power feeds to be assigned to a Location.

Please open a separate feature request for this.

**Comment by martinum4** [comment]
Added #6211 as separate proposal.

**Comment by jeremystretch** [comment]
> Allow default values Voltage and Amperage to be added to Regions and Sites.

NetBox doesn't have a mechanism to do this. Could you please elaborate on the specific change(s) you're proposing?

**Comment by martinum4** [comment]
I'm not a coder so i might be wrong, but apparently the default Voltage is coming from the variable `POWERFEED_VOLTAGE_DEFAULT,` which is defined in /netbox/dcim/constants.py .

Since there has to be a site selected when defining a new feed anyway the Voltage-field could be autofilled with the voltage after the selection of a site.

**Comment by jeremystretch** [comment]
I'm going to close this for two reasons:

1. It doesn't make sense to associate a default voltage with a site or region.
2. There's no mechanism in place to support this, and implementing one would be far more trouble than it's worth.

This is something we can revisit when and if NetBox gets some form of per-user default value persistence mechanism.
