### ISSUE TITLE
Rack Reservation descriptions are not searchable

### ISSUE THREAD

**Issue by alexey-kirillov** [netbox-community/netbox#6200]
### NetBox version

v2.11.0

### Python version

3.7

### Steps to Reproduce

Create a rack reservation, fill in list of units and description (e.g. 'server name').

### Expected Behavior

Search for 'server name' and find reservation.

### Observed Behavior

No results found.

This is inconsistent, as for example descriptions for IP Addresses are searchable.
And can be useful in case you've reserved unit(s) for a server and want to find this reservation later.

**Comment by jeremystretch** [comment]
I'm not able to replicate this. Are you using the global search instead of the rack reservation search?

**Comment by alexey-kirillov** [comment]
yes, global search

**Comment by jeremystretch** [comment]
The global search doesn't return rack reservations at all.

**Comment by alexey-kirillov** [comment]
I see, yet this can be useful. 
E.g. in case you've reserved a unit for a particular server and want to find reservation later.
