### ISSUE TITLE
Table Configuration dialog doesn't update Selected Columns correctly

### ISSUE THREAD

**Issue by jbakklund** [netbox-community/netbox#6202]
### NetBox version

v2.11

### Python version

v3.7.3

### Steps to Reproduce

1. List a type of objects, e.g. 'Devices'.
2. Click on the 'Configure' table button.
3. Select one of the available columns e.g. 'Serial number' and click on the green 'Add columns' button.
4. Press the 'Save' button

### Expected Behavior

I would expect to see the selected and highlighted item ('Serial number') from the 'Available column' pane, jump to the bottom of the 'Selected columns' pane when I pressed the 'Add columns' button.

### Observed Behavior

The list of 'Selected columns' remain unchanged, and the resulting list of 'Devices' is still showing only the default columns. 

I then tried to select and remove the column 'Rack' from the list of 'Selected columns' with the resulting list of 'Devices' now only showing one single column; the 'Rack' column. Surely, if I then click the 'Configure' button again, now 'Rack' is the only item listed in the 'Selected columns' pane.

I also tried to rearrange the order of columns by moving 'IP Address' up one step and above 'Rack' with the resulting list of 'Devices' now only showing IP addresses and nothing else.

This bug seems to be valid for all type of objects.

**Comment by jeremystretch** [comment]
It sounds like you're missing the updated Javascript files. What process did you follow when upgrading to v2.11.0?

**Comment by jbakklund** [comment]
I upgraded from v2.10.10 by cloning the git repository and running the ./upgrade.sh script.

**Comment by jbakklund** [comment]
It turns out that the problem is related to my browsers at work profile, as the issue disappear when I switch to my private browser profile in Edge, or simply switch browser to Chrome.
