### ISSUE TITLE
Enable custom fields and tags for journal entries

### ISSUE THREAD

**Issue by maznu** [netbox-community/netbox#6203]
### NetBox version

v2.11

### Feature type

Data model extension

### Proposed functionality

The journal is an absolutely fantastic addition, thank you! If we made a PR, would extending the journal entry model to support custom fields be accepted? I notice that none of the other "Extras" support CFs.

### Use case

We have a semi-public "engineering log" of updates to various VMs, devices, etc.  We've already backported data from that into the Netbox journal.  We'd like to create an interface from our CRM/control panel to sync over our "notes" to Netbox, but those are more private (may contain personal data, software serial numbers, etc).

I'd love to retool our status page and engineering log to pull journal information from Netbox.  It would be great if, when carrying out future maintenances, we could tag or custom-field whether or not a journal entry in Netbox is e.g. "Public" or "Private" so that we're effectively publishing to just one place.

Other use cases could include

* CF "warning/danger in force until [datetime]" — e.g. at-risk or outage maintenance windows
* CF "review [datetime]" — a report could pull out "danger" and "warning" items that may need re-visiting
* tag for "field engineer jobsheet" — the backlog of little "I'll get round to it when I'm next at site" jobs (we use "flags" in our CRM for this kind of todo list)

### Database changes

Add JSON blob for CFs to `journalentry` table, with default `{}`.

### External dependencies

None anticipated.

**Comment by MalfuncEddie** [comment]
I would also like the ability to add kinds (info success,danger ...) like TODO, decision ...
But this can be fixed with a custom_kind field

**Comment by proudbro** [comment]
It would be nice to have some kind of unifying attribute for the tags. It could be custom field or any other field or parent object
