### ISSUE TITLE
Assignment of power feeds to location

### ISSUE THREAD

**Issue by martinum4** [netbox-community/netbox#6211]
### NetBox version

v2.11-beta1

### Feature type

Change to existing functionality

### Proposed functionality

- Allow Power feeds to be assigned to a Location and define default values for Voltage and Amperage.

Examples:
- We define a Location (Room) in Berlin for Telco-Equipment where the defaults are 48VDC.
- We connect a rackmounted PDU to an outlet that is mounted overhead on a ceiling cable tray.

### Use case

By being able to assign Feeds to a location it is easier to map out responsibilities inside a campus-like setting, especially when you see a power feed as an instance of a circuit-breaker, Admin responsibilities usually ends at the circuit breaker and everything beyond that is handled by facility professionals and should be out of scope for Netbox.

**Comment by candlerb** [comment]
Power feeds belong to a power panel, and a power panel can be assigned to a location (formerly rackgroup) - see sketch at #5534.  In essence, a power panel is a grouping of (one or more) power feeds at a physical location.

Could you therefore model it by creating a power panel in each of the different locations where there is a power feed / circuit breaker?

**Comment by tchmnkyz** [comment]
See Personally I would like to see it where i can have a power panel and that has its sources (feeds) and then you can break the panel down and have breaker 01 and 03 goes to rack 001, breaker 02 and 04 goes to rack 002. And then it would be really nice if we could get a visualization of the power panel similar to a rack elevation.

**Comment by candlerb** [comment]
I don't actually use the power features of Netbox, but I thought the model was the other way round: a power feed is not the *input* to a power panel, a power feed is the *output* from a power panel (i.e. a "breaker" in your terminology).

**Comment by jeremystretch** [comment]
>  I thought the model was the other way round: a power feed is not the input to a power panel, a power feed is the output from a power panel

This is correct. The flow is power panel -> power feed -> power port.
