### ISSUE TITLE
Broken UI for user with readonly permissions

### ISSUE THREAD

**Issue by Fikirsiz** [netbox-community/netbox#6229]
### NetBox version

v2.11.0

### Python version

3.8

### Steps to Reproduce

1. Create user with readonly permissions
2. Open table list view for any object. For example IP-addresses

### Expected Behavior

I expect standart UI

### Observed Behavior

A table with information under the search bar.
![Screenshot from 2021-04-21 15-33-30](https://user-images.githubusercontent.com/20380238/115555216-ef27a600-a2b7-11eb-8ef1-88a340736b78.png)

**Comment by jeremystretch** [comment]
Thank you for submitting this issue, however it appears that this topic has already been raised. Please see issue #6196 for further discussion. Should be fixed in the upcoming v2.11.1 release.
