### ISSUE TITLE
Dedicated model for redundancy protocol instances

### ISSUE THREAD

**Issue by WilliamDEdwards** [netbox-community/netbox#6235]
### NetBox version

v2.11.1

### Feature type

New functionality

### Proposed functionality

Dedicated model for e.g. VRRP and HSRP instances.

A typical instance configuration only needs an interface, VRID and VIPs. Keeping track of VRIDs in IP Address objects (as proposed in https://github.com/netbox-community/netbox/issues/2456) would allow us to store these basic attributes in NetBox. Information like tenant and interface could be derived from objects linked to the the IP Address object.

However, some properties are instance-specific, like priority. To use NetBox as Source of Truth for e.g. Keepalived configurations, we have to keep track of these properties, but they cannot be saved in another object.

### Use case

Keeping track of instance information would allow for:

* Using NetBox as Source of Truth for e.g. Keepalived configurations
* Getting the next available VRID (like https://github.com/netbox-community/netbox/issues/1246)

### Database changes

The proposal requires adding a new model.

Many redundancy protocols share basic properties, like priority. Redundancy protocol specific fields (e.g. HSRP `use-bia`) should be added by users themselves to prevent overcomplicating the model.

### External dependencies

Unsure.

**Comment by jeremystretch** [comment]
This is probably a better encapsulation of the intent behind #2456. I'm going to close that one out in favor of this FR.
