### ISSUE TITLE
Add the option to select the "Region" column in the Racks view

### ISSUE THREAD

**Issue by Andreich2010** [netbox-community/netbox#6243]
### NetBox version

v2.10.4

### Feature type

Data model extension

### Proposed functionality

In the Racks view (Host: 8000 / DCIM / Racks /), the "Region" field we use as a "company name", and we use the "SITES" field as "building".
In some enterprises, the identical marking of rack is found. Therefore, we want to request the functionality that displays the "Region" field in the "Rack tab" table view

### Use case

In our organization, more than 25 regions, in some names "Site" the same. When searching for the desired "SITE", the employee does not have to resort to the use of the search filter, which will significantly reduce the time for operational activities.

### Database changes

Probably a simple solution will be a binding "ID Region" in the "DICM_RACK" table.
Or class changes in Racktable (\ OPT \ Netbox \ Netbox \ dcim \ tables \ racks.py) by connecting the desired "ID Region" through Queryset

### External dependencies

No dependencies

**Comment by jeremystretch** [comment]
> In the Racks view (Host: 8000 / DCIM / Racks /), the "Region" field we use as a "company name", and we use the "SITES" field as "building".

Tenancy assignment would be more appropriate for this, as regions are intended to convey geographic location.

**Comment by Andreich2010** [comment]
Yes, it is good, but we use the field "Tenancy" as a "responsible" and "group responsible", it approached us more.
