### ISSUE TITLE
Create interface - Max length of description

### ISSUE THREAD

**Issue by akashha** [netbox-community/netbox#6246]
### NetBox version

v2.11

### Python version

3.9

### Steps to Reproduce

1 - Add interface on device ( /dcim/interfaces/add/?device=24 ), max lenght of description is 100 characters 
2 - Edit the interface, max lenght is 200 (/dcim/interfaces/24/edit/)

### Expected Behavior

Can you set the max directly to 200 in create interface description ?

### Observed Behavior

Hello,

When create :
`<input type="text" name="description" maxlength="100" class="form-control" placeholder="None" id="id_description">`

When edit :
`<input type="text" name="description" maxlength="200" class="form-control" placeholder="None" id="id_description">`

Cordialy.

**Comment by candlerb** [comment]
class ComponentModel has:

```
    name = models.CharField(
        max_length=64
    )
...
    label = models.CharField(
        max_length=64,
        blank=True,
        help_text="Physical label"
    )
    description = models.CharField(
        max_length=200,
        blank=True
    )
```

A similar issue exists for name and label.  When creating an interface, there is no maxlength for these fields in the HTML:

```
<input type="text" name="name_pattern" class="form-control" required="" placeholder="Name" id="id_name_pattern">
...
<input type="text" name="label_pattern" class="form-control" placeholder="Label" id="id_label_pattern">
```

But when editing an interface, it gives maxlength=64 as expected

```
<input type="text" name="name" value="br255" maxlength="64" class="form-control" required="" placeholder="Name" id="id_name">
...
<input type="text" name="label" maxlength="64" class="form-control" placeholder="Label" id="id_label">
```

**Comment by jeremystretch** [comment]
The `name` and `label` fields don't get a maximum length because they allow specifying a pattern (which may be longer than the resulting values).
