### ISSUE TITLE
Unable to remove columns in object overview 

### ISSUE THREAD

**Issue by rodvand** [netbox-community/netbox#6248]
### NetBox version

v2.11.1

### Python version

3.7

### Steps to Reproduce

Use Google Chrome or Microsoft Edge as your web browser.

1. Go to Virtualization -> Virtual Machines
2. Press Configure
3. Remove the column "Name"
4. Save

### Expected Behavior

The column name to disappear from the overview.

### Observed Behavior

The table looks the same.

If I first add some columns (that works) and then try removing a column it resets the whole table.

**Comment by rodvand** [comment]
I see this has already been reported in https://github.com/netbox-community/netbox/issues/6202.

**Comment by rodvand** [comment]
From my own investigation (I'm a javascript noob, so bear with me):
If I set the breakpoint in Chrome at https://github.com/netbox-community/netbox/blob/648b9dd7d81b773258907e16a4d88e13ab3054c4/netbox/project-static/js/tableconfig.js#L48 and look at the variables when I try removing a field, the variable data looks like this:
<img width="258" alt="Screen Shot 2021-04-22 at 21 03 35" src="https://user-images.githubusercontent.com/56864/115771484-46a83d80-a3ae-11eb-82a4-70bf4f09656f.png">

If I do the same exercise when adding a field the variable data looks like this:
<img width="275" alt="Screen Shot 2021-04-22 at 21 05 06" src="https://user-images.githubusercontent.com/56864/115771589-6fc8ce00-a3ae-11eb-8083-d1b16b5b29b5.png">

**Comment by jeremystretch** [comment]
Looks like Chrome et al need to use `prop()` rather than `attr()` when marking an `<option>` selected.
