### ISSUE TITLE
Allow custom jinja filters in export templates

### ISSUE THREAD

**Issue by fabi125** [netbox-community/netbox#6263]
### NetBox version

v2.10.6

### Feature type

New functionality

### Proposed functionality

We would like to add custom filters to our export templates. Ideally one should be able to add them via a plugin and then be able to load them in the export template.

### Use case

We want regex_replace to be available in our export template.

I tried adding filters in a `templatetags` folder to a netbox plugin and `load`ing it in the template (which works for regular templates used within a plugin), but that fails with `There was an error rendering the selected export template (filter_test): Encountered unknown tag 'load'.`

### Database changes

None

### External dependencies

None

**Comment by jeremystretch** [comment]
Please elaborate on the specific change(s) you're proposing to support this functionality.

**Comment by fabi125** [comment]
Is there a way that export templates behave like regular django templates? I feel like that would fix this issue.

Otherwise I'd have to spend some more time reading the code to make a more substantial suggestion on how this potentially could be achieved.
