### ISSUE TITLE
Collapse/Expand button missing after using expand

### ISSUE THREAD

**Issue by nicoschottelius-lf** [netbox-community/netbox#6268]
### NetBox version

git master

### Python version

3.7

### Steps to Reproduce

1. Click on expand
2. both buttons vanish
3. you cannot collapse anymore

### Expected Behavior

Buttons stay there

### Observed Behavior

Screenshot from the installation below:

![2021-04-24-005321_1896x265_scrot](https://user-images.githubusercontent.com/82147122/115937185-8a2aa680-a497-11eb-9d79-3aab7443f3f3.png)

**Comment by jeremystretch** [comment]
> git master

Please specify your NetBox version per the issue template.

> Click on expand

Where do you see an "expand" button?

**Comment by nicoschottelius-lf** [comment]
@jeremystretch It's netbox (v2.11.1) and I did see the button on the prefix screen like it is shown in the README.md on https://github.com/netbox-community/netbox. Above screenshot from me looks different in the prefix view

**Comment by jeremystretch** [comment]
There's no expand button in v2.11.1. The screenshot in the README is from an older release.

**Comment by nicoschottelius-lf** [comment]
@jeremystretch How do you expand/collapse the prefixes in that case? Currently we are having a problem to spot the right prefix, because there are too many (~250) and it is very hard to "zoom in" into a particular area of your network.

The upper prefixes (like /29's or /32's in the IPv6 world) are visually very nearby /48's, so locating the right network for creating a new sub-prefix seems to have changed from "locate visually" to "enter the prefix in the sear and then look at it" - is that correct?
