### ISSUE TITLE
Add support for templateable device-type descriptions

### ISSUE THREAD

**Issue by martinum4** [netbox-community/netbox#6269]
### NetBox version

v2.11.1

### Feature type

Data model extension

### Proposed functionality

As described in the  [documentation](https://netbox.readthedocs.io/en/stable/core-functionality/device-types/#device-component-templates) descriptions are lost when generating a device from a device-type-template.

However in quite a few cases it is beneficial to have the interface or port-corresponding information written into the devices itself.

### Use case

Examples:
- Specifying allowed SFP-Power draw
- Specifying PoE-Wattage
- Marking Combo-Ports (#3189)
- Marking Amperage of power ports (since some connectors e.g. IEC60309 connectors are available for 16/32/63A)
- Informing about port specialties in regard to Crossover/MDI-X

### Database changes

Needs an extra field

### External dependencies

none

**Comment by jeremystretch** [comment]
IMO none of these examples are good uses of the description field, which is merely a string of free-form text and intended to be applied verbatim to an interface's configuration (e.g. `description "what it says in NetBox"`).

> Specifying allowed SFP-Power draw

This is an attribute of the installed optic, rather than the interface itself.

> Specifying PoE-Wattage

This would be covered by #1099 (PoE modeling).

> Marking Combo-Ports

This is a function of the device type; it does not change across instances of the device.

> Marking Amperage of power ports

A custom field would be ideal for this.

> Informing about port specialties in regard to Crossover/MDI-X

Not really sure what you mean here, but a tag would likely be more appropriate.

**Comment by martinum4** [comment]
Oh, these are for configuration use only? I would have taken it more broadly as an information field.

>This is an attribute of the installed optic, rather than the interface itself.

There are two levels defined here, 1W and 1.5W, the latter requires a device-sided heatsink.

> This is a function of the device type; it does not change across instances of the device.

Exactly this is why i want this information to be visible in all port descriptions that are created from the template.

> A custom field would be ideal for this.

I just tried and the custom field does not show up in the port template, only in the final port of a device and thus not prefilled.

> Not really sure what you mean here, but a tag would likely be more appropriate.

As in e.g. "nonstandard behaviour"?

**Comment by jeremystretch** [comment]
> Oh, these are for configuration use only?

Yes, that's the field's intended use.

> Exactly this is why i want this information to be visible in all port descriptions that are created from the template.

It's already available via the device's relationship to the device type. Replicating it is unnecessary and redundant.

I'm sorry but I don't really follow your other questions. Please consider opening a discussion if you'd like assistance with using custom fields and tags, as a feature request isn't the best place for such discussion.
