### ISSUE TITLE
Table Configuration ordering clears selected columns

### ISSUE THREAD

**Issue by eriktm** [netbox-community/netbox#6273]
### NetBox version

v2.11.1

### Python version

3.8

### Steps to Reproduce

1. Go to tenants or devices list (probably others as well)
2. Select Configure
3. Re-order the list in "Selected columns"
4. Click Save

### Expected Behavior

The table should be shown with the selected columns in the specified order

### Observed Behavior

The column which was last re-ordered is the only visible column. When going back to the configure dialog, this column is the only one listed in "Selected columns".

**Comment by jeremystretch** [comment]
Sounds like maybe you've run into #6248, which should be fixed in the upcoming v2.11.2 release. (See if you're able to reproduce the bug on Firefox to be sure.)

**Comment by eriktm** [comment]
When using Firefox I am unable to reproduce it, so it seems to be the same bug.
