### ISSUE TITLE
'speed' attribute of console port model is PositiveSmallIntegerField (cannot cover all values)

### ISSUE THREAD

**Issue by ypid** [netbox-community/netbox#6274]
### NetBox version

v2.11.1

### Python version

3.7

### Steps to Reproduce

1. "Editing console port Serial" of a device.
2. Set "Speed" to "115.2 kbps".
3. Press "Update".

### Expected Behavior

Working.

### Observed Behavior

Port speed in bits per second

    Ensure this value is less than or equal to 32767.

### Credits

Originally found by @drmsoffall in https://github.com/netbox-community/netbox/commit/8de20fcd1fb8e9a775f643d45285a48edd07cedf#r49831954. I found it as well and began searching.

**Comment by drmsoffall** [comment]
Already fixed in dev, we were too slow! :) #6252 / 4939b6b

**Comment by ypid** [comment]
I should have checked that, thanks. Closing.
