### ISSUE TITLE
"Max length" in prefix view cannot be deselected

### ISSUE THREAD

**Issue by candlerb** [netbox-community/netbox#6287]
### NetBox version

v2.11.1

### Feature type

Change to existing functionality

### Proposed functionality

The "max length" drop-down in Prefix listing view has a couple of strange behaviours:

* It's not in the "Search" area where I'd expect it, but next to the "Configure" / "Add" / "Import" / "Export"
* Once you've selected it, you can't deselect it (without navigating away / manually changing URL)

I suggest moving it to the Search area, and having "----" as one of the options. (EDIT: I suggest moving it next to the "Address Family", since selecting a max length of say 48 isn't really useful without also selecting IPv6.  There is already a "Mask Length" selector there, but that matches exact length, not up-to length)

### Use case

Easier control of filtering prefixes

### Database changes

None

### External dependencies

None

**Comment by candlerb** [comment]
Current view at `/ipam/prefixes/?mask_length__lte=16&page=1`
![image](https://user-images.githubusercontent.com/44789/116208124-7ce01700-a738-11eb-9efc-8b62f01f9722.png)

**Comment by jeremystretch** [comment]
I'll add an option to clear any assigned selection, however we'll need to keep the button where it is for now pending the UI overhaul for v2.12.
