### ISSUE TITLE
Unable to assign LAG to interfaces on different virtual chassis member

### ISSUE THREAD

**Issue by KrisShannon** [netbox-community/netbox#6289]
### NetBox version

v2.11.0

### Python version

3.7

### Steps to Reproduce

1. Create a virtual chassis with at least two devices
2. Create a LAG on one of the devices in the virtual chassis
3. Edit an interface on a different device in the virtual chassis

### Expected Behavior

LAG dropdown should include the LAG created in step 2

### Observed Behavior

LAG dropdown does not show the LAG created in step 2

**Comment by KrisShannon** [comment]
It looks like it was the `Clean up parent/LAG interface form validation` (d74c07e1a25b2e6aa440defcf2c4a71cbe32d10c) which lost this functionality.

**Comment by jeremystretch** [comment]
The root issue here is that the `vc_interfaces()` queryset method currently returns interfaces from other VC members _only_ if the specified device has been designated as the VC master. I'm open to loosening this behavior, though we'll need to consider potential consequences of doing so elsewhere in the application.

**Comment by jeremystretch** [comment]
Going to work around this by adding a boolean argument to `vc_interfaces()` to control the "only if master" behavior.
