### ISSUE TITLE
Console speed for device types

### ISSUE THREAD

**Issue by OmriAbu** [netbox-community/netbox#6291]
### NetBox version

2.11.1

### Feature type

Change to existing functionality

### Proposed functionality

Add the `speed` field when creating or editing a `console port` and `console server port` under a device template.

### Use case

All devices come with default console port speeds that vary between vendors and models, it would make sense to add the speed field so any created device from a given type would have the default speed already set,

**Comment by jeremystretch** [comment]
IIRC this was discussed under #5375 and we opted not to add the field to device types because it's purely a configuration item. It can have a default value, yes, but that's defined by the software rather than the hardware type.

**Comment by OmriAbu** [comment]
That makes sense, personally I haven't encountered any case where the same HW across different software versions comes with different default speeds.

Yes most devices can have the console speed changed later on but there should be some way to know what default speed a given device type or platform (or the combination of the two?) is without the need of keeping this info in an external database and manually update on the creation of a new device.

This can be done with a webhook to an external backend on new device creation but it seems like an over complication of something simple.

**Comment by jeremystretch** [comment]
It's a valid use case for sure, but device types aren't the right solution. There are plenty of places you might want to convey a default value that's not tied to the hardware: interface encapsulations, interface descriptions (#6261), assigned VLANs, tags, etc. We don't want to set a precedent of using the device type for this purpose as that approach would fall over pretty quickly.

I'd be happy to entertain a detailed proposal in support of default values for certain attributes, but it would need to be raised as a separate feature request.

> This can be done with a webhook to an external backend on new device creation but it seems like an over complication of something simple.

A [custom script](https://netbox.readthedocs.io/en/stable/additional-features/custom-scripts/) might suit your needs.

**Comment by OmriAbu** [comment]
Understood, thank you for the input.

I'll look into those other options and raise a new request if non pan out.
