### ISSUE TITLE
Add support for "Y" adaptor power cables

### ISSUE THREAD

**Issue by taupehat** [netbox-community/netbox#6295]
### NetBox version

v2.11.1

### Feature type

Change to existing functionality

### Proposed functionality

- Create a cable type "Power (Y type)"
- When this cable type is used, allow multiple power ports to connect to the same outlet
- Calculate power draw to that outlet to be the sum of both ports attached to the cable

### Use case

It's occasionally necessary to use a Y adaptor to power both power supplies on a device when not enough outlets are available. Example of such a Y adaptor:
https://www.tripplite.com/computer-power-extension-cord-y-splitter-cable-10a-18awg-iec-320-c14-to-2x-iec-320-c13-6-ft~P0040062C13

Currently there is no acceptable way to model this cable type within Netbox.

**Comment by jeremystretch** [comment]
Implementing this will likely require overhauling the cable model completely. Which isn't to say we won't do it; just setting expectations. However, we may want to re-cast this as general support for multi-point cabling, as I suspect there's a high degree of overlap with modeling breakout cables (e.g. a 40GE interface connected to four channelized 10GE interfaces).

**Comment by xkilian** [comment]
Great idea Jeremy to make it generic, there are a few other use cases where this pops up. Ex. Copper cabling for telephony that use these types of Y cables.

**Comment by taupehat** [comment]
Post to keep from going stale, also if there's anything I can do to help let me know.
