### ISSUE TITLE
Webhook executing twice on update action

### ISSUE THREAD

**Issue by heiko-ma** [netbox-community/netbox#6301]
### NetBox version

2.11.1

### Python version

3.7

### Steps to Reproduce

1. Configure a webhook in the admin-gui with Event-Type **Update**
2. For the Request URL I've used the built-in webhook receiver -> http://localhost:9000
3. Every other field can stay on default
4. Fire an event on the object specified in **content types**
5. Check the log from the webhook receiver

### Expected Behavior

You receive a webhook request including the json string containing the information about the changed netbox-object.

### Observed Behavior

The webhook request is fired twice:
1. The first time, you get the information about the object-state before the change
2. The second time, you get the actual change-request from the webhook

This behavior causes problems when using netbox with ansible-tools like rundeck which listen on webhook requests and use the incoming json data to execute ansible jobs (e.g. configuring interfaces on switches)

I can attach the log from the webhook receiver if this information is needed.

**Comment by jeremystretch** [comment]
I'm not able to replicate this following the steps provided. Do you happen to have tags assigned to the object? If so, this is expected: please see #6284 for further discussion.

**Comment by heiko-ma** [comment]
Yes this is correct, I've looked at the linked issue and i'm pretty sure, that I'm experiencing the same "error". I'm going to close this issue as this problem has been already adressed. Thank you!
