### ISSUE TITLE
Remove specific data rates from InfiniBand interface choices

### ISSUE THREAD

**Issue by krono** [netbox-community/netbox#6303]
### NetBox version

426e64ae8dd3 (v2.10.4)

### Feature type

Change to existing functionality

### Proposed functionality

The numeric data rates currently displayed for the different InfiniBand "speed generations" should be removed from the user interface.

### Use case

Currently, the interface descriptions for InfiniBand EDR, HDR etc. include a numeric data rate:
![Bildschirmfoto 2021-04-28 um 15 44 09](https://user-images.githubusercontent.com/119279/116414369-b304c000-a838-11eb-88d4-84881c449dcd.PNG)

However, these can be potentially misleading.
The numeric data rates are correct for _one lane_ of the data rate generation.
That is, _one lane HDR_ has a data rate of 50 Gbps. However, next to no InfiniBand-Interface is one-lane; 
most currently sold hardware is four-lane (or "has a port width of four" in [InfiniBand TA parlance](https://www.infinibandta.org/infiniband-roadmap/) ).

This fact is often not even mentioned.   
For example [this HCA](https://store.mellanox.com/products/nvidia-mcx653105a-hdat-sp-connectx-6-vpi-adapter-card-hdr-infiniband-and-200gbe-single-port-qsfp56-pcie-4-0-x16-tall-bracket-sp-indicates-single-pack.html) is a "HDR adapter" and supports a 200Gbps data rate; it is a four-lane HDR adapter, but that fact is nowhere mentioned. Simliarly, [this switch](https://store.mellanox.com/products/nvidia-mqm8700-hs2f-quantum-hdr-infiniband-switch-40-qsfp56-ports-2-power-supplies-ac-x86-dual-core-standard-depth-p2c-airflow-rail-kit.html) supports HDR at 200Gbps (which is four-lane) or 100 Gbps "via splitter", which means, 2 times 2-lane HDR.

On the other hand, users might be temped to select from the interface list by number.
For example, say they have a switch that says "100Gbps" on the tin (and is in fact an EDR swich), so they select "NDR", which does not reflect reality.

Therefore dropping the numeric data rates will reduce the likelyhood of confusion about numeric data rates and InifniBand names.

### Database changes

none

### External dependencies

none

**Comment by krono** [comment]
Ping

**Comment by krono** [comment]
@callumstrubi, you provided the initial Infiniband code, would you agree with my reasoning?

**Comment by krono** [comment]
:(

**Comment by krono** [comment]
This is a simple documentation change wich just 3 days ago bit my colleague.

**Comment by plaurin84** [comment]
I agree with @krono regarding the misleading values of Infiniband.
This issue is relevant to me as well.
