### ISSUE TITLE
Data cache not being invalidated after move to 2.11.1

### ISSUE THREAD

**Issue by karrots** [netbox-community/netbox#6305]
### NetBox version

v2.11.1

### Python version

3.8

### Steps to Reproduce

1. Upgrade from 2.10.x to 2.11.x
2. Move a location from one site to another.
3. Open the old site and view statistics. Rack counts and other item counts will remain in the old site.
4. Click on a statistic to view the filtered list. The filter will show the old site name. The data in the list will show the new site name.
5. Wait for cache to time out. Data will now be in sync.

### Expected Behavior

The cache should be invalidated immediately due to data change. 

### Observed Behavior

Cache not being invalidated.

**Comment by jeremystretch** [comment]
I'm not able to reproduce the reported behavior following the steps provided. Please elaborate on your steps above to start with the creation of each object, and detailing _exactly_ what actions you are taking at each step.

**Comment by karrots** [comment]
Objects existed before the migration to 2.11

Objects moved were rack groups now locations.

I moved the location to a different site as part of a consolidation of
sites. The individual racks assigned to that location showed the new site
in their pages. When opening a rack it showed the updated site. When
looking at the old site stats page it still listed 28 racks when it should
have listed 0. When I clicked on the 28 number a list of the racks was
presented. The site column showed the new site/location in the list. The
search field on the right showed the old site name as the filter.

**Comment by jeremystretch** [comment]
You need to run the provided upgrade script (`upgrade.sh`) per the [documented upgrade process](https://netbox.readthedocs.io/en/stable/installation/upgrading/). This includes a command which clears the entire cache (`manage.py invalidate all`).

**Comment by karrots** [comment]
ok I'll ensure that ran and test. I'm using the netbox-docker container and
I'm pretty sure it runs that script. Can't confirm if it had issues this
time. The moves happened after the upgrade.
