### ISSUE TITLE
Interface query via API returns too many interfaces since v2.11.2

### ISSUE THREAD

**Issue by cs-1** [netbox-community/netbox#6312]
### NetBox version

v2.11.2

### Python version

3.8

### Steps to Reproduce

1. Create at least two devices with the naming scheme "myname/1" and "myname/2" (number after "/" corresponds with the stack member ID in our case).
2. Create a virtual chassis called "myname" and add devices "myname/1" and "myname/2" as members. **Do not** make one of the members a master.
3. Query NetBox using the following GET request:

```
https://<netbox-server>/api/dcim/interfaces/?device=myname%2F1
```

### Expected Behavior

In NetBox v2.11.1 the above query would produce only interface data of the VC member "myname/1".

### Observed Behavior

After upgrading to v2.11.2 this produces the interfaces of **all** devices in the same virtual chassis despite none of the VC members being master. Please note that this query also produces all interfaces of all devices when querying "myname/2"'s interfaces.

We can clearly pin this on some change in v2.11.2. We used a VM snapshot of the v2.11.1 server to verify this and I can confirm that this behaviour was not present in v2.11.1. 

Deleting the virtual chassis "myname" will immediately remedy this problem. So this is related to the fact that the devices are members of a virtual chassis.

This issue can be reproduced in Swagger.

**Comment by jeremystretch** [comment]
Please update your steps to reproduce to use raw API requests. We cannot rely on third party tools for bug reproduction.

**Comment by cs-1** [comment]
Sorry, @jeremystretch , I updated the steps to reproduce giving the raw API call. You can actually reproduce it in the Swagger interface, too.

**Comment by cs-1** [comment]
I've added further clarification. I'll try to find out today which change in v2.11.2 causes this bug. It's quite serious because it breaks API scripts and Ansible playbooks that rely on being able to query interfaces of virtual chassis members.

**Comment by cs-1** [comment]
@jeremystretch I found the problem. The cause seems to be this line:

https://github.com/netbox-community/netbox/blob/1abaa5e60c2ecc15ae57db978d389023c136bdf7/netbox/dcim/models/devices.py#L877

Removing `not if_master or ` (the way it was before in v2.11.1) fixes the problem. I need to read more of the code to understand the reason behind adding `not if_master or `. Maybe I can come up with a patch (I'm not much of a coder so it can take a while).

**Comment by cs-1** [comment]
Hi @jeremystretch ,

I've spent the weekend thinking about the reasoning behind adding the `if_master` attribute. If it's ok with you I'd like to ask you some questions about it to understand where to look for a fix for the issue it introduced.

As far as I understand the reason for adding `if_master` is so that it's possible to query all interfaces of members of the same virtual chassis by using a single call of `vc_interfaces()` so that LAGs can be configured by using any interface of all virtual chassis members even if none of them is designated as a master chassis. To achieve this, you introduced the `if_master` variable. To avoid having to change all code calling `vc_interfaces()` you set it to a default of `False` so that calling `vc_interfaces()` without any parameters would behave as it did before which is to only show the interfaces of a particular virtual chassis member and **not** all interfaces of all chassis members **unless** the chassis being queried is a master chassis. Is this assumption correct? If it is, the expression in

https://github.com/netbox-community/netbox/blob/1abaa5e60c2ecc15ae57db978d389023c136bdf7/netbox/dcim/models/devices.py#L877

needs to be changed to

```
if self.virtual_chassis and (if_master or self.virtual_chassis.master == self):
```

That way the code will behave as in v2.11.1 if `vc_interfaces()` is called without parameter: it will leave the filter untouched an hence only show the interfaces of the virtual chassis member that's being queried and it will only modify the filter to show all interfaces of all virtual chassis members if the chassis queried is the virtual chassis master. If `vc_interfaces(if_master=True)` is called (as is the case in `netbox/dcim/views.py`) it will show all interfaces of all virtual chassis members even if the chassis queried isn't a virtual chassis. If I'm wrong and the intention is that a call of `vc_interfaces()` without parameters will yield all interfaces of all virtual chassis members and it should only return just the interfaces of a virtual chassis member if it's called with parameter as `vc_interfaces(if_master=True)` then I assume that, when issuing the API GET call, `vc_interfaces()` is for some reason called without `if_master=True`.

Sorry for the lengthy post, my insight into the NetBox code isn't very deep hence the questions. I'd really like to help fixing this. The impact of this change is quite dramatic for us because it breaks all of our Ansible playbooks.
