### ISSUE TITLE
Change interface name via API patch removes IP address 

### ISSUE THREAD

**Issue by scetron** [netbox-community/netbox#6319]
### NetBox version

v2.9.9

### Python version

3.7

### Steps to Reproduce

1. Have an existing device with a named interface.
2. Make sure the interface has an IP address.
3. Use an API call to change the Name of the interface

Original interface name: "oldInterfaceName0"

Submit a patch request via the URL:
`[netbox-api] /dcim/interfaces/[interface-id]/`
Body:
```
{
  "name": "new_interface_name_0"
}
```

4. The config is accepted but the interface loses it's IP address association. This is unexpected.

No other interface config is present, but it appears no other interface or device config changes. 

### Expected Behavior

Changing the interface name using the GUI does not cause any other configuration to change. I expect the same outcome using the api to patch update the interface name.

### Observed Behavior

The IP address is removed from the interface when changing the interface name on a device.

**Comment by jeremystretch** [comment]
A couple issues:

1. NetBox v2.9.9 is a bit outdated. Can you try replicating this on the current stable release? (You can try using our [demo instance](https://demo.netbox.dev/).)
2. Please share the complete API request you're sending using a tool such as `curl`.

**Comment by scetron** [comment]
Yup! Tried on the demo instance and doesn't appear to be there. I close this for now.
