### ISSUE TITLE
Interface VLAN Dropdown

### ISSUE THREAD

**Issue by amit177** [netbox-community/netbox#6326]
### NetBox version

v2.11.2

### Python version

3.8

### Steps to Reproduce

1. Create two VLAN groups, "A" and "B"
2. Create VLAN 100 and assign it to group A
3. Create VLAN 200 and assign it to group A
4. Create VLAN 100 and assign it to group B
5. Create VLAN 200 and assign it to group B
6. Create a device and an interface inside it
7. Edit the interface, change 802.1q mode to Access
8. View the dropdown

### Expected Behavior

The dropdown should contain separating lines between each VLAN group when editing the assigned VLAN on a device's interface, as it did before v2.11

### Observed Behavior

All the VLANs are mixed together in the dropdown with no separation between them, even ones with the same name.

**Comment by jeremystretch** [comment]
> The dropdown should contain separating lines between each VLAN group when editing the assigned VLAN on a device's interface, as it did before v2.11

This behavior was intentionally removed for two reasons:

1. Arranging VLANs by group requires a full (versus brief) API request, which takes much longer
2. The UI logic required to accomplish the grouping was quite heavy and difficult to maintain

IIRC the original goal was to enable filtering the VLANs list by group and/or site, but that seems to have fallen by the wayside. This is IMO a preferable approach to the inline grouping, which does nothing to limit the total number of VLANs being returned.

**Comment by ksaegusa** [comment]
Hello.

I'm facing a similar problem.

For example, If we can change the pull-down display to the following, we can solve the problem

`Name (id) (vlan_group_name)`

**Comment by ziggekatten** [comment]
The only issue that currently make us stick with 2.10.x. is this one.

**Comment by ziggekatten** [comment]
Jeremy, will this issue be fixed in version 3.x?

**Comment by jeremystretch** [comment]
You're welcome to try out the the [public demo](https://beta-demo.netbox.dev/) and check for yourself.

**Comment by amit177** [comment]
@jeremystretch great fix, thank you!
