### ISSUE TITLE
Include docs in main release package

### ISSUE THREAD

**Issue by jcralbino** [netbox-community/netbox#6328]
### NetBox version

v2.11

### Feature type

New functionality

### Proposed functionality

Include the HTML rendered online documentation available on https://netbox.readthedocs.io/en/stable/ within the main package of the netbox.

The goal is to adapt the URL <Docs> seen bellow to the HTML local documentation and have it as rendered docs available at /docs on a live instance
 ![image](https://user-images.githubusercontent.com/44149262/116776610-85528d80-aa69-11eb-9543-d234960a13c3.png)

### Use case

The following use cases are applicable:
* Provide the correct documentation that is always related to the specific version being used, instead of the online version that refers the latest version.
* Provide access to the documentation to system installed in a isolated management environment that do not have internet access.

### Database changes

none.
Only file structure changes to create a new /docs directory and changing the url.

**Comment by jeremystretch** [comment]
It seems like the best way to approach this is to have the upgrade script build the docs locally. This means that `mkdocs` and its related packages (see `docs/requirements.txt`) will become required dependencies.

We'll also need to tweak the way static file collection is currently handled, introducing a new `docs/` path for the rendered documentation.
