### ISSUE TITLE
Add Support for Screw terminals (Power Ports)

### ISSUE THREAD

**Issue by martinum4** [netbox-community/netbox#6337]
### NetBox version

v2.11.1

### Feature type

Change to existing functionality

### Proposed functionality

Add "Screw block" or some similar wording in a category "Other" to the power ports and power outlets.

### Use case

A lot of high power devices (mainly UPS and PDU) offer screw terminals as a power connection option.
Netbox already has support for "DC Terminals", however this FR mainly regards AC, but obviously can be used for DC as well.

Example products that have a screw block:
http://powerquality.eaton.com/Products-Services/Backup-Power-UPS/9PX.aspx?cx=75&GUID=E3F7BC15-8BEB-4956-9494-E6CB16EA1652
https://www.apc.com/shop/de/de/products/Rack-PDU-Erweiterung-Basic-2-U-32-A-230-V-4-IEC-C19/P-AP7585
https://www.tripplite.com/28.8kw-3-phase-switched-pdu-lx-platform-interface-220-230-240v-outlets-touchscreen-lcd-hardwire-input-0u-taa~PDU3XEVSRHWB

### Database changes

From what i can tell only new additional values for existing tables.

### External dependencies

None.

**Comment by jeremystretch** [comment]
What is the _exact_ type being proposed?

**Comment by martinum4** [comment]
I'm not an english native speaker, i'd probably go with the same as the manufacturers, which would be "hardwired", is this ok?

**Comment by martinum4** [comment]
Solved via #6785

**Comment by jeremystretch** [comment]
**THIS** was the issue I [was looking for](https://github.com/netbox-community/netbox/issues/6785#issuecomment-884980336)! Thanks. :slightly_smiling_face:

**Comment by bluikko** [comment]
Power Outlet type "Hardwired" is needed as well, as was listed in the OP. Currently the only way to model large UPS - for example - is to leave Type empty.

Large UPS may have bus bars where thick three-phase cables are bolted in - both on input and output side.
