### ISSUE TITLE
Assign configuration context to VLAN

### ISSUE THREAD

**Issue by jcralbino** [netbox-community/netbox#6340]
### NetBox version

v2.11.2

### Feature type

Change to existing functionality

### Proposed functionality

In order to improve the automation capability for the VLAN in a SDN environment it is interesting to provide more details than the ones provided by the object itself.

Using a configuration context mapping, would simplify this as it will provide a structure information related to a L2 domain. 

### Use case

For ACI configuration and related SDN Environment, a VLAN is mapped to a L2 Bridge domain according to specific configuration parameters. 

A configuration context would allow to use netbox to document the required configuration for this VLAN/L2 domain.

### Database changes

Probably creating one additional entry in the VLAN model to allow a mapping to a configuration context.

### External dependencies

none

**Comment by jcralbino** [comment]
@jeremystretch i believe that this is something we can add maintaining the principle behind configuration context 

Do you prefer If a discussion for this is opened before ?

**Comment by jeremystretch** [comment]
Unfortunately I don't think this would be feasible, as there is (intentionally) no relationship from devices/VMs directly to VLANs. This precludes us from rendering config contexts as part of a device/VM queryset, which is a crucial function of the feature.

**Comment by jcralbino** [comment]
Thanks for your feedback.
Indeed I missed that concept of configuration context, but it is true that the object where they are used is mainly with devices. 

So for this specific use case it should a completely new configuration context object, like VLAN configuration context.

The principle behind should be to use this to improve the automation of a l2 broadcast domains ( VLAN, VXLAN,..) across different switches .

**Comment by jeremystretch** [comment]
Can you elaborate on your use case here? Specifically, why wouldn't a custom field on the VLAN and/or VLANGroup model work for this?

**Comment by jcralbino** [comment]
Currently VLANs in the datacenter environment are transported using a layer 3 protocol. Although the object VLAN represented a broadcast domain in the past this was implemented by setting a VLAN id, name, and description. For this simple layer 2 environment the information in netbox is enough to be used for the configuration and automation of this simple broadcast domains.

For the newer environment where a layer 3 protocol is used to extend the broadcast domain additional fields are required for this configuration and automation. 
Using a similar design as done for the device configuration context assigned to a VLAN object will allow us to automate the configuration of this across our infrastructure.
The VLAN configuration context will be assigned based in VLAN groups to the corresponding object. Having a free form JSON Structure for the VLAN configuration context will enable this configuration automation for all this environment. Namely SDN environment where VXLAN is used requiring specific values to be used.

Using a custom field for this will mean that legacy vlans objects ( placed outside this VLAN group) are having a database field that is not going to be used.

**Comment by jcralbino** [comment]
@jeremystretch 

From your previous comments I understood that the issue was related with the way the current model for device is made, where the local context is tied to that model.

Do you see the value of having another field associated with the vlan to improve the way new networks are represented in netbox, after my detailed use case ? 

I have seen in the past request to model l2vpn( that are nothing more than an extended layer 2) that can be also accomplished using this local context that will provide configuration details while using the current vlan fields( name, vlan role,..) we can model this l2 network constructs in netbox better.

**Comment by jeremystretch** [comment]
As I noted above, the proposed feature is not technically feasible given the current data model.
