### ISSUE TITLE
Manufacturer page does not list correct number of device type instances

### ISSUE THREAD

**Issue by royvegard** [netbox-community/netbox#6341]
### NetBox version

v2.11.2

### Python version

3.6

### Steps to Reproduce

1. Create a Manufacturer
2. Create a Device Type for that Manufacturer
3. Create a device of that Device Type

### Expected Behavior

When looking at the Manufacturer page (/dcim/manufacturers/<id>) you see a table of device types for that Manufacturer. This table has a column named Instances that should list 1 instance for our Device Type

### Observed Behavior

The table shows 0 instances for our Device Type.

The table of device types shows 0 instances for all Device Types for all Manufacturers.

**Comment by jeremystretch** [comment]
Thank you for submitting this issue, however it appears that this topic has already been raised. Please see issue #6313 for further discussion.
