### ISSUE TITLE
Interface description is not instantiated from Device Type on Device create

### ISSUE THREAD

**Issue by sdktr** [netbox-community/netbox#6342]
### NetBox version

v2.11.2

### Python version

3.8

### Steps to Reproduce

1. Create Interface on a Device Type, fill Name: 'VLAN1' and Description 'OFFICE', Type: Virtual [(example)](https://demo.netbox.dev/dcim/device-types/3/)
2. Instantiate new Device, referencing this Device Type [(example)](https://demo.netbox.dev/dcim/devices/100/interfaces/)

### Expected Behavior

Interfaces of the Device have the same Type, Name and Description as the Device Type

### Observed Behavior

Name and Type are correct, Description of the Interface is empty

**Comment by jeremystretch** [comment]
Thank you for submitting this issue, however it appears that this topic has already been raised. Please see issue #6261 for further discussion.

**Comment by sdktr** [comment]
Ai! my bad, sorry for the duplicate
