### ISSUE TITLE
Use a custom exception for object permission failures

### ISSUE THREAD

**Issue by jweiher** [netbox-community/netbox#6345]
### NetBox version

v2.11.2

### Python version

3.9

### Steps to Reproduce

1. Create a plugin which hooks to a pre_save signal
2. Have an uncatched ObjectDoesNotExist exception in this plugin
3. See the Error "Object save failed due to object-level permissions violation"

### Expected Behavior

It took us some time to debug this. It would be way nicer if either the object-level permission violation would get their own Exception instead of this re-interpretation of "ObjectDoesNotExist".

### Observed Behavior

There is a re-interpretation of ObjectDoesNotExist to "Object save failed due to object-level permissions violation". This happens here: https://github.com/netbox-community/netbox/blob/develop/netbox/netbox/views/generic.py#L321

**Comment by jeremystretch** [comment]
> 2. Have an uncatched ObjectDoesNotExist exception in this plugin

While we can do some work in core to help mitigate this, it is the plugin author's responsibility to ensure any such exceptions are handled.
