### ISSUE TITLE
Cache the number of each component type assigned to devices/VMs

### ISSUE THREAD

**Issue by jeremystretch** [netbox-community/netbox#6347]
### Proposed Changes

Add the following integer fields to dcim.Device:

* `_console_port_count`
* `_console_server_port_count`
* `_power_port_count`
* `_power_outlet_count`
* `_interface_count`
* `_front_port_count`
* `_rear_port_count`
* `_device_bay_count`
* `_inventory_item_count`

Add the following integer fields to virtualization.VirtualMachine:

* `_interface_count`

These fields would be automatically populated upon creating/modifying/deleting the relevant child components.

### Justification

* Enables efficient filters of devices/VMs based on whether a certain type of component has been created.
* Eliminates the need for additional queries e.g. when display the device view.

**Comment by jeremystretch** [comment]
This might also be a use case for CTE; see #6587.

**Comment by AndMrzv** [comment]
I also like to verify that devices match their device type templates (you know something's up if a 24port 1PSU switch suddenly has 29 interfaces and 3 power ports). So maybe you'll find it useful to add same data to device types, maybe expand the idea to strict matching devices to their types or syncing (now I do this with API and Bash).

**Comment by ryanmerolle** [comment]
pushed to 3.6 milestone
