### ISSUE TITLE
Caching error when swapping A/Z circuit terminations

### ISSUE THREAD

**Issue by cybarox** [netbox-community/netbox#6355]
### NetBox version

v2.11.2

### Python version

3.8

### Steps to Reproduce

Test: https://demo.netbox.dev/circuits/circuits/35/
1. Create new circuit with new circuit id 
2. add Z termination to a site
3. click swap on z termination

### Expected Behavior

A and Z Terminations are swapped

### Observed Behavior

An Error appears: No terminations have been defined for circuit test2.

**Comment by jeremystretch** [comment]
Yet another caching bug...
