### ISSUE TITLE
Enable or disable Verson in footer

### ISSUE THREAD

**Issue by sthierolf** [netbox-community/netbox#6356]
### NetBox version

v2.11.1

### Feature type

New functionality

### Proposed functionality

As optional configuration setting,  I would like to request an EXPOSE_VERSION setting.

EXPOSE_VERSION = True  - The host name and version is displayed in the footer
EXPOSE_VERSION = False  - The host name and version is not displayed or just replaced with netbox

Should work similar to Apache "ServerTokens Prod" or Nginx "server_tokens off" to hide host name and version, especially for netbox installations running in the public Internet.

### Use case

If netbox host is running in the public Internet, the goal for services (Apache, nginx, ...) is always to reduce the attack surface.
Hiding the netbox host name and version increases the security a bit ("Exposure of Information").
Some Institutions like BSI (Bundesamt für Sicherheit in der Informationstechnik / German Federal Office for Information Security) suggests to disable version or banners as well on web based applications

**Comment by jeremystretch** [comment]
> Hiding the netbox host name and version increases the security a bit ("Exposure of Information").

It doesn't really, though: This is a textbook example of [security through obscurity](https://en.wikipedia.org/wiki/Security_through_obscurity).

I think it would make sense to show the hostname and version information only for authenticated users, however introducing a configuration parameter for this would be unnecessary.

**Comment by sthierolf** [comment]
I agree, security through obscurity, but also used to raise the attempts for "unwanted individuals" a little bit higher.

Host + version information after authentication will do, but this information should not be shown on the login page.

**Comment by jeremystretch** [comment]
There's also the `/api/status/` endpoint which currently reveals this information to unauthenticated users. This would also need to be locked down somehow, without sacrificing the basic functionality of the endpoint for unauthenticated users.
