### ISSUE TITLE
Add Search filter to VLAN Group overview

### ISSUE THREAD

**Issue by rodvand** [netbox-community/netbox#6358]
### NetBox version

2.11.2

### Feature type

New functionality

### Proposed functionality

Add the ability to do a text search in the VLAN Group overview <netbox>/ipam/vlan-groups/.

### Use case

With a large number of VLAN groups the ability to search the vlan group name would be very useful.

### Database changes

None

### External dependencies

None

**Comment by rodvand** [comment]
I believe it would be a simple
```
q = forms.CharField(
        required=False,
        label='Search'
    )
```
in `ipam/forms.py` under VLANGroupFilterForm.

**Comment by jeremystretch** [comment]
This requires the introduction of a `q` filter on VLANGroupFilterForm as well, to specify what fields are to be evaluated.
