### ISSUE TITLE
Enable custom links for organizational and nested group models

### ISSUE THREAD

**Issue by darcynz** [netbox-community/netbox#6359]
### NetBox version

v2.11.2

### Feature type

New functionality

### Proposed functionality

Extend Custom Link to locations model.

### Use case

Being able to select custom links, extends location model. Example includes linking it to Topology maps in other plugins or tools.

### Database changes

None

### External dependencies

None

**Comment by jeremystretch** [comment]
I'm going to extend this to _all_ organizational and nested group models. IIRC this was originally planned for v2.11 in conjunction with providing a dedicated view for each model. Looks like it just fell through the cracks.
