### ISSUE TITLE
Tenancy for Plugin Objects

### ISSUE THREAD

**Issue by liquid-metal** [netbox-community/netbox#6365]
### NetBox version

v2.11.2

### Feature type

Change to existing functionality

### Proposed functionality

When creating objects in Plugins with an assigned Tenancy, it should be possible to add them in the tenancy Overview page in the stats as a clickable element count. Currently, the fields are hardcoded and cannot be extended by plugins: netbox/templates/tenancy/tenant.html

### Use case

Specific example: the [netbox-bgp plugin](https://github.com/k01ek/netbox-bgp) adds BGP sessions, which may be assigned to an existing tenant. In the tenant view, the stats should display the count of assigned Sessions as well.

### Database changes

none

### External dependencies

none

**Comment by jeremystretch** [comment]
Please elaborate on the specific implementation you're proposing.

**Comment by liquid-metal** [comment]
In places with stats overviews (Site and Tenant to my knowledge, please correct me if there are more places like that) plugins should be able to insert custom boxes for new elements.

![site](https://user-images.githubusercontent.com/56035107/117299584-00a4ac80-ae79-11eb-9e8d-a1714713b45c.png)


I propose placeholders for optional plugin inserts, just like the `{% plugin_*_page object %}`, e.g. `{% plugin_site_stats %}` and `{% plugin_tenant_stats %}`: (Please excuse incorrect wording, I am not very familiar with Django and Jinja)

```
...
                <div class="col-md-4 text-center">
                    <h2><a href="{% url 'virtualization:cluster_list' %}?tenant_id={{ object.pk }}" class="btn {% if stats.cluster_count %}btn-primary{% else %}btn-default{% endif %} btn-lg">{{ stats.cluster_count }}</a></h2>
                    <p>Clusters</p>
                </div>

-->             {% plugin_site_stats %}

            </div>
        </div>
        {% plugin_right_page object %}
    </div>
</div>
...
```

**Comment by esoubihe** [comment]
This would be an interesting addition. We have plugins that we'd like to add to the tenant overview page too. Willing to contribute if there's enough interest here.

**Comment by 991jo** [comment]
I am also very interested in this change. This would make plugin objects a bit more like a first class citizen in NetBox.

**Comment by jeremystretch** [comment]
I'm afraid that merely expressing interest in a general idea for a feature is not sufficient to move it forward. As no detailed implementation has been proposed despite this issue having been open for several months, I'm going to close it.

If anyone would like to revisit this idea and come with a specific implementation plan, please open a new feature request to present it for discussion.
