### ISSUE TITLE
Stale data in webhook JSON for device or virtual machine after deleting primary IP

### ISSUE THREAD

**Issue by wwijkander** [netbox-community/netbox#6373]
### NetBox version

v2.11.3

### Python version

3.7

### Steps to Reproduce

1. Set up webhook for create, updates and deletes of "virtual machine" or "device" objects
2. Set up a netcat(or similar) listening to the host specified in the webhook above
3. Create VM or Device object with network interface
4. Dualhome the interface with both a IPv4 and IPv6, set as primary addresses for the VM/Device
5. Delete IPv4 address object
6. Observe webhook request

### Expected Behavior

A webhook call with JSON containing only the IPv6 address as primary_ip and primary_ip6, and no primary_ip4

### Observed Behavior

The webhook JSON contains both primary_ip6 and primary_ip4, the latter with the deleted IPv4 that doesn't exist in Netbox anymore

**Comment by wwijkander** [comment]
Same bug occurs when keeping the IPv4 and deleting the IPv6 object, and it also applies to non-VM devices

**Comment by jeremystretch** [comment]
I believe this has been resolved under #6284 in the upcoming v2.11.5 release. Please try upgrading to that release when it becomes available in the near future to see if the problem has been resolved. (If not, please request that this issue be re-opened.)
