### ISSUE TITLE
Add VLANs to Devices

### ISSUE THREAD

**Issue by avidpontoon** [netbox-community/netbox#6386]
### NetBox version

v2.11.3

### Feature type

Data model extension

### Proposed functionality

Within each Device, you should be able to assign VLANs to it. Much like you can do on an interface. Allowing you to track which devices have which VLANs on them. This should then be displayed somewhere within the 'Device' tab to view at a glance.

### Use case

Allowing users to immediately know if a certain device already has a specified VLAN on it or if it needs adding. Could also mean that when you go to assign VLANs to interfaces on a specific device, it only shows VLANs that are configured on that specific device. This could help with accidentally assigning a VLAN that isn't on the device.

### Database changes

New VLAN ID's field would be required for devices.

### External dependencies

None

**Comment by romanstech** [comment]
Agree with this request. Yesterday started thinking where I can save such info on each switch in Netbox.

**Comment by avidpontoon** [comment]
Hi Jeremy,

Is there any documentation on the available_on_device addition?

Thanks
Nick 

> VLANs are difficult to model effectively. While we do "create" VLANs on switches, what we're really doing is partitioning the L2 forwarding table into discrete domains. In reality, VLANs are really link-specific. For example, I can create subinterfaces Gi0/0.100 and Gi0/1.100 both using 802.1Q encapsulation tagged for VLAN 100, but these aren't necessarily in the same VLAN.
> 
> 
> 
> Also, NetBox v2.11 introduced the `available_on_device` and `available_on_virtualmachine` filters which largely obviate the need for the direct assignment proposed here.

**Comment by jeremystretch** [comment]
It's listed as an available filter in the REST API docs, but that's about it.

**Comment by jeremystretch** [comment]
I'm going to go ahead and close this as it would only serve to complicate the data model at this point.
