### ISSUE TITLE
Addition Interface Type for ATM/xDSL Interfaces

### ISSUE THREAD

**Issue by craized** [netbox-community/netbox#6387]
### NetBox version

v2.11.3

### Feature type

Data model extension

### Proposed functionality

Add support for an interface-type that covers DSL connections. Specifically, adding support for `xDSL`

### Use case

My OOB network uses DSL from another provider to provide access to a number of console servers. These circuits have static addresses that cannot be tracked on an accurately classified interface.

For now, I'm using the 'other' interface type, but tracking these as what they actually would be preferable.

### Database changes

No schema changes

### External dependencies

None

**Comment by jeremystretch** [comment]
What is the specific new type being proposed?

**Comment by julianze** [comment]
"xDSL" should be the right one i think.
Maybe an additional "ATM" for old based  connections.

**Comment by craized** [comment]
After considering existing interface types vs connector types in NetBox, I agree that `xDSL` is the appropriate request. Would it be best if I updated the original post?

**Comment by jeremystretch** [comment]
@craized yes please, for the benefit of newcomers.

**Comment by jeremystretch** [comment]
Should we create an ATM group for this interface type?

**Comment by craized** [comment]
I'm all for being able to set up bond groups. If it's not i

+1 to ATM groups

**Comment by bellwood** [comment]
Would we need an entire group for ATM or could we simply use Other as a covering group for xDSL which itself covers a broad number of DSL/ATM connections (ADSL, VDSL, ADSL2, etc)?

**Comment by bellwood** [comment]
Feel free to assign to me. I'm happy to make a PR once we have a consensus on placement.

**Comment by julianze** [comment]
+1 for a dedicated group (as with Cellular) for this purpose:
Group: xDSL

With types:
- ADSL
- ADSL2+
- SDSL
- VDSL
- G.fast
- ISDN
- POTS

**Comment by craized** [comment]
I actually really like the idea of a POTS group to cover DS0 delivered services like xDSL/dial

**Comment by bellwood** [comment]
I guess we need to think about grouping as ATM covers many things outside of xDSL and currently there is no sub-grouping.

DS0, DS1, DS3, etc are just muxed T's which are currently under the Serial grouping, maybe that should fall under TDM?

**Comment by bellwood** [comment]
Thoughts on:

**TDM**
- DSx
- ISDN
- Tx/Ex
- OCx

**xDSL**
- ADSL
- ADSL2
- ADSL2+
- G.fast
- SDSL
- VDSL

**Other**
- Other
- POTS

**Comment by craized** [comment]
That feels pretty good to me, but I'm sure I'm missing something important!

**Comment by bellwood** [comment]
> That feels pretty good to me, but I'm sure I'm missing something important!

I guess it depends on how deep down the rabbit hole you want to go with ITU G.992.x since the xDSL versions all have sub-standards with different throughputs.

We just need to find the right home for everything =)

**Comment by julianze** [comment]
> Thoughts on:
> 
> **ATM**
> 
> * OCx - **Currently in SONET**
> * xDSL (RJ-11)
>   
>   * ADSL
>   * ADSL2
>   * ADSL2+
>   * G.fast
>   * SDSL
>   * VDSL
> 
> **TDM**
> 
> * DSx
> * ISDN
> * Tx/Ex - **Currently in SERIAL**
> * POTS
> 
> Edit: Moving target

+1

**Comment by craized** [comment]
So after a sleep, what's the thought process for moving OCx from SONET to ATM? I think they're both equally correct/incorrect, right?

**Comment by jeremystretch** [comment]
This seems to have stagnated. I'm just going to add a new xDSL type as that's what the original request was for. Happy to entertain additional proposals under a *new* issue.

**Comment by craized** [comment]
Thank you-- this is definitely good enough for my purposes and I appreciate the addition.
