### ISSUE TITLE
Inconsistency in API for field role/device

### ISSUE THREAD

**Issue by leahoswald** [netbox-community/netbox#6391]
### NetBox version

v2.9.9

### Python version

3.6

### Steps to Reproduce

- Open a VM in the API view: The role field is called `role`
- Open a device in the API view: The role field is called `device_role`

### Expected Behavior

I would expect that both fields are called the same (`role`) because they are linking to the same data.

### Observed Behavior

The device field is called `device_role` and the VM field is called `role`

**Comment by jeremystretch** [comment]
It doesn't seem like the hassle of introducing a breaking change like this would be worthwhile just to achieve consistency with another model.

**Comment by leahoswald** [comment]
Of course it's a breaking change. On the other hand it means extra handling for every code that works with both devices and VMs. For example if you want to generate monitoring config from it.

**Comment by jeremystretch** [comment]
> On the other hand it means extra handling for every code that works with both devices and VMs.

These are always going to require separate logic, as they are different models. Renaming the `device_role` field won't change that.

**Comment by jeremystretch** [comment]
Flagging this for milestone assignment to potentially handle in the future. We could potentially implement a getter & setter to maintain backward compatibility across releases, however I'm not sure what potential pitfalls we'd run into regarding Django's ORM's behavior.

**Comment by abhi1693** [comment]
Would it fine if a field is renamed and this is introduced as a breaking change for v3.5? I can submit a PR if that's accepted as a solution

**Comment by ryanmerolle** [comment]
This could be a good candidate for 3.6

**Comment by abhi1693** [comment]
I'm going to try to make the field backward-compaitible for the API access. If that's possible, should be able to ship this with v3.6
