### ISSUE TITLE
Search IP Addresses By Description Via REST API

### ISSUE THREAD

**Issue by coder0xff** [netbox-community/netbox#6393]
### NetBox version

2.11.3

### Feature type

New functionality

### Proposed functionality

https://github.com/netbox-community/netbox/issues/358 requested the ability to search by description, and it was eventually implemented. However, it appears that version 2.11.3 no longer has this ability. Due to being a new major version, I was unsure if this was a regression, so I've made it a feature request.

### Use case

Getting IP addresses by description.

**Comment by jeremystretch** [comment]
Please elaborate on what specifically you're doing, or would like to do.

**Comment by coder0xff** [comment]
I have a bash script with a list of descriptions and would like to programmatically map them to IP addresses. 

```bash
curl -X GET "https://netbox.****.com/api/ipam/ip-addresses/?description=foobar" -H  "accept: application/json" -H  "Authorization: Token *****************************************"  | grep -oP "\"address\":\"\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}\/\d+\"" | grep -oP --color=never "\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}"
```

The query returns the entire collection of ip address objects rather than ones matching the description.

**Comment by DanSheps** [comment]
Is there any reason you cannot use the query to do this (q=foobar).

The query searches:

* DNS Name
* Description
* Address

**Comment by jeremystretch** [comment]
I see no harm in adding the `description` field specifically, although as Dan points out you probably want to use `?q=` in most cases.
