### ISSUE TITLE
Add Cable Type for SAS Copy of old request: #2715

### ISSUE THREAD

**Issue by mha-mega** [netbox-community/netbox#6396]
### NetBox version

v2.9.4

### Feature type

Change to existing functionality

### Proposed functionality

As with previous requests, we require Netobox to track connections between a Head node and a JBOD.

Probably the easiest way to do this would be to take existing functionality of Console Ports and Server Console Ports and duplicate it into SAS Connector and SAS Controller (or something like that).  Then update cable types etc. 

### Use case

Really just need to be able to link 1 server to another that has no network interfaces connected to each other.

### Database changes

Likely

### External dependencies

n/a

**Comment by jeremystretch** [comment]
#2715 was closed as out of scope for the project, and it still is. I don't see this changing any time in the near future, and likely never, as NetBox owes its success largely to focusing on network infrastructure specifically.

**Comment by mha-mega** [comment]
Yet you have a DCIM component which we are using across 20 sites, 120 racks and 1300 devices.  With pointless items like Console and Server Console.  It makes no sense.
