### ISSUE TITLE
Unable to delete a device with a circuit terminated to an interface

### ISSUE THREAD

**Issue by abrahamvegh** [netbox-community/netbox#6398]
### NetBox version

2.11.3

### Python version

3.7

### Steps to Reproduce

1. Create a site
1. Create a circuit located at that site
1. Terminate both ends of the circuit at that site
1. Create a device with at least two interfaces
1. Terminate both ends of the circuit into interfaces on that device
1. Attempt to delete the device

### Expected Behavior

The device is deleted.

### Observed Behavior

The complete exception is provided below: 
```
<class 'AttributeError'>

type object 'NoneType' has no attribute '_meta'
```

**Comment by jeremystretch** [comment]
I'm not able to replicate this following the steps provided. Please enable debugging and post the complete stack trace for analysis.

**Comment by abrahamvegh** [comment]
Updated reproduction steps, sorry about that, this was difficult for me to reproduce in the first place. I confirmed the steps provided do trigger the exception on the public demo instance as well as on my production instance.
