### ISSUE TITLE
Support for importing tags when importing IP addresses via CSV

### ISSUE THREAD

**Issue by leethobbit** [netbox-community/netbox#6420]
### NetBox version

v2.11.3

### Feature type

Data model extension

### Proposed functionality

Currently, it is not possible to specify tags for IP addresses when importing IP addresses via CSV.  It would be great if a tags column (or columns) could be implemented so tags don't require additional steps after import.  The only complicating factor here is support for multiple tags at import - I'm not sure whether it is better to use multiple columns in the CSV import for tags or use some sort of delimiting character in one column. Thank you very much!

### Use case

I ran into this when I decided to import all of my static IP assignments.  Using tags is a great way to categorize devices - I have tags for VOIP, Radio, CCTV, HVAC, Printers, and more.  This leaves room in the Description for specifying other need to know details and allows me to easily filter the view to only see one specific type of device when viewed through the IP address window.  Bulk assignment of tags after import is certainly feasible for smaller deployments, but it would be great to include that in the import step since nearly all other fields are already included there.

### Database changes

I'm still new to this but I don't suspect this would require DB schema changes.  This should just be a matter of passing tag values from the CSV importer to the tag function or Class in Netbox.

**Comment by jaakub** [comment]
Would be nice to see this extended to devices as well. We have a set of standard tags that most devices should be tagged with when created. At the moment, this is a manual/bulk step process once the devices are created.

**Comment by ziggekatten** [comment]
Tip. A custom script with FileVar() and you can upload files and and add whatever you like. We use that for imorting stuff that needs more than what the imports give natively.

**Comment by jeremystretch** [comment]
This should be doable by treating the `tags` field as its own comma-separated list of tag names encapsulated inside double quotes (CSV-in-CSV). However, the implementation will require a proper field to handle this data as well as a set of thorough tests to ensure its operation.
