### ISSUE TITLE
Ability to view users in a group

### ISSUE THREAD

**Issue by candlerb** [netbox-community/netbox#6422]
### NetBox version

v2.11.3

### Feature type

Change to existing functionality

### Proposed functionality

At the moment if you go to `/admin/users/admingroup/` you can see the *number* of users who are in each group. However unless I am being dense, I cannot see any way to *list* who those users are (apart from clicking into every single user, one by one)

I think the obvious place to do this would be to add a "group view" page, e.g. `/admin/users/admingroup/1/`. Currently there is only `/admin/users/admingroup/1/change/`, and that only lets you change permissions on a group.

(As an extension, it would be nice to be able to add/remove users here too, as it would make it easier to add users en-masse into a group, rather than going into each user one by one)

### Use case

When changing the permissions for group X, I want to see which users will be potentially affected so I can check with them.

As a workaround I can do a direct SQL query, but I don't think that should be required:

```
select g.name,u.username from auth_group g, auth_user u, auth_user_groups ug
where g.id=ug.group_id and u.id=ug.user_id and u.is_active order by g.id,u.username;
```

### Database changes

None

### External dependencies

None

**Comment by jeremystretch** [comment]
I'm going to add the ability to filter the users list by assigned group. This should be sufficient until we replace the admin UI entirely under #6466.
