### ISSUE TITLE
Add possibility to assign cluster to Site Group

### ISSUE THREAD

**Issue by ziggekatten** [netbox-community/netbox#6429]
### NetBox version

v2.11.3

### Feature type

Change to existing functionality

### Proposed functionality

Currently a cluster is always tied to a Site. For stretched clusters (nodes in more than one data center) it would make sense to assign the cluster to a site group. 

### Use case

We are running VMware clusters with vSAN over stretched L2 networks between sites. We also run Fortigate FW clusters with nodes in each DC. Being able to model this on site group level would enable us to use the new features on 2.11(Site Groups) that we today can't use, and are today modeling by using one site for both sites, and Rack Groups(Location in 2.11) to distinguish the physical site. 

### Database changes

Probably a relation to Site Group instead of SIte, so I'm not sure any DB-changes are needed

**Comment by jeremystretch** [comment]
Marking as blocked until we figure out whether there's a more optimal way to track multi-model parent assignments (see #6440).

**Comment by mazhead** [comment]
@jeremystretch #6440 got closed, can we maybe revisit this one?
