### ISSUE TITLE
Add a IP to Cluster object 

### ISSUE THREAD

**Issue by ziggekatten** [netbox-community/netbox#6431]
### NetBox version

v.2.11.3

### Feature type

New functionality

### Proposed functionality

When creating a cluster, have the possibility to assign an cluster IP-address of type "Cluster Address"

### Use case

Clusters that have an floating IP address that are not directly assigned to a specific device does not really have a good way of modeling in the current implementation.

### Database changes

Not sure, but there need to be additional relation between Cluster object and IPAddress object

**Comment by jeremystretch** [comment]
A cluster in NetBox is a collection of individual virtual machines. It does not have addresses or interfaces. You'll need to assign IP addresses to individual VMs within a cluster.
