### ISSUE TITLE
Allow search for MAC address

### ISSUE THREAD

**Issue by holtgrewe** [netbox-community/netbox#6435]
### NetBox version

v.2.11.3

### Feature type

Change to existing functionality

### Proposed functionality

Allow searching for interfaces by MAC address.

- Type MAC into search box.
- Press enter.
- Resulting match(es) are displayed.

### Use case

It would help to locate MAC adresses as seen in MAC address tables in routers etc.

**Comment by jeremystretch** [comment]
This ability already exists in NetBox.

**Comment by holtgrewe** [comment]
@jeremystretch Interesting. I'm running Netbox `v2.11.3` via Docker. Could you confirm that it works on your side? Would it work with the provided example data (so we can run a common test, e.g., in Docker, to isolate the problem)?

**Comment by jeremystretch** [comment]
Yes, it works; please see [the associated filter test](https://github.com/netbox-community/netbox/blob/5ca7f375d3bce1826381f91c694f990e825a4e70/netbox/dcim/tests/test_filtersets.py#L1384). You can also test it yourself on the [public demo instance](https://demo.netbox.dev/).

**Comment by holtgrewe** [comment]
I just added `7c:32:66:de:cb:06` to this interface:

- https://demo.netbox.dev/dcim/interfaces/1/edit/?return_url=/dcim/devices/1/interfaces/

typing `7c:32:66:de:cb:06` into the search box yields nothing

![image](https://user-images.githubusercontent.com/521780/118717131-efb74c00-b825-11eb-927b-bf58968d3041.png)

Sorry for being thick here... what am I doing wrong?

**Comment by jeremystretch** [comment]
That's the global search box: You want the interfaces filter (at /dcim/interfaces/). The global search doesn't search for any device components.

**Comment by holtgrewe** [comment]
Excellent! That worked now. Sorry for the noise.
