### ISSUE TITLE
Site Prefix List - Bad Indentation

### ISSUE THREAD

**Issue by networkhorse** [netbox-community/netbox#6436]
### NetBox version

v2.11.3

### Python version

3.8

### Steps to Reproduce
Create the following structure:
![image](https://user-images.githubusercontent.com/22162629/118674854-0643b000-b7f2-11eb-846d-50a1383d10d0.png)
![image](https://user-images.githubusercontent.com/22162629/118674901-0e035480-b7f2-11eb-9132-2e2287ee7ce6.png)

Assign the deepest prefixes to a site.

### Expected Behavior

Hierarchy should be "local", i.e. only relevant to that site's prefixes. It should not show indentation for Netbox as a whole. I expect something like this:
![image](https://user-images.githubusercontent.com/22162629/118675699-b6b1b400-b7f2-11eb-9857-30c4b13bb42a.png)

### Observed Behavior

Prefixes have very misleading indentation, as in the photo below. None of these subnets are related.

![image](https://user-images.githubusercontent.com/22162629/118675099-3f7c2000-b7f2-11eb-83a4-ab3bb350ba0e.png)

**Comment by jeremystretch** [comment]
Please update your post above to indicate the _specific values_ for each object being created, so that someone else can try reproducing the reported behavior.

**Comment by networkhorse** [comment]
Updated @jeremystretch :-)

**Comment by jeremystretch** [comment]
This is expected behavior. 1.0.0.0/26 is indented two places because it is situated at a depth of two in the hierarchy. The applied filter has no bearing on the hierarchy; if it did, the hierarchy would become quite useless in myriad circumstances.

**Comment by networkhorse** [comment]
@jeremystretch I ask that you reconsider closing this ticket because it is highly misleading seeing this
![image](https://user-images.githubusercontent.com/22162629/118712049-3736db80-b818-11eb-81bb-39002eccd187.png)

There must be a better way of displaying this. Perhaps there is some way of showing the context for the indentation without directly saying "this is related to this site".

**Comment by jeremystretch** [comment]
You're welcome to open a feature request detailing a specific proposal to improve the display, however this in itself is not a bug. Also note that #6087 may effect significant changes in the way the prefix hierarchy is rendered in the near future.
