### ISSUE TITLE
Add ipv4 /32 and ipv6 /128 prefix support

### ISSUE THREAD

**Issue by crafty-ua** [netbox-community/netbox#6455]
### NetBox version

v2.10.3

### Feature type

Change to existing functionality

### Proposed functionality

Add ipv4 /32 and ipv6 /128 prefix support

### Use case

While testing netbox I've noticed that it does not allow user to create single-host networks. In my case I would like to use such feature to track end-user IP-unnumbered allocations while also keeping those /32 networks linked to a vlan

**Comment by jeremystretch** [comment]
I think it makes sense to allow this. IIRC we prevented the use of /32 and /128 masks originally to prevent confusion with IP addresses, but that was a long time ago.

**Comment by crafty-ua** [comment]
@jeremystretch 
Cool. I wonder if you would like me to create some sort of initial PR to implement such behavior?

**Comment by jeremystretch** [comment]
@crafty-ua let's leave this open for a bit to gather feedback. If there's no opposition, then yes. We should just need to remove the validation rules that check for /32 and /128 prefix lengths on the Prefix model.

**Comment by crafty-ua** [comment]
Awesome!


// https://github.com/netbox-community/netbox/pull/3396/commits/219d24274ffb3bdd7387252559a32e49470fbb3c -- That PR might be useful

**Comment by jeremystretch** [comment]
@crafty-ua are you still interested in submitting a PR for this? If not, I can take it.

**Comment by crafty-ua** [comment]
@jeremystretch 
Sure. Just returned from a short vacation today

**Comment by crafty-ua** [comment]
Pushed an initial PR fully based on code 219d242. Going to try running some tests in lab later on tomorrow

**Comment by crafty-ua** [comment]
Seems that we might need to update NetHostContained function to looks something similar to
```
class NetHostContained(Lookup):
    """
    Check for the host portion of an IP address without regard to its mask. This allows us to find e.g. 192.0.2.1/24
    when specifying a parent prefix of 192.0.2.0/26.
    """
    lookup_name = 'net_host_contained'

    def as_sql(self, qn, connection):
        lhs, lhs_params = self.process_lhs(qn, connection)
        rhs, rhs_params = self.process_rhs(qn, connection)
        params = lhs_params + rhs_params
        #return 'CAST(HOST(%s) AS INET) << %s' % (lhs, rhs), params
        return 'CAST(HOST(%s) AS INET) <<= %s' % (lhs, rhs), params
```

**Comment by jeremystretch** [comment]
I'm not sure; can a /32 IPv4 prefix actually contain an IP address? I'm open to opinions but IMO I think it's fine to leave as-is.

**Comment by basti1508** [comment]
> I'm not sure; can a /32 IPv4 prefix actually contain an IP address? I'm open to opinions but IMO I think it's fine to leave as-is.

This leads to inconsistent views.

1. e.g. if you habe a /32 aggregate and create a /32 prefix in it, utilization shows 100% but 0 prefixes.
2. A /32 Ip Address in a /32 Prefix will show 0% utilization.
2. If you set unique IPs to true,  IP-Address Tab on a /32 Prefix will tell you that you can create a new IP there, even if it exists already. (error on creation try);
