### ISSUE TITLE
Assigning IP addresses to interfaces connected by a cable only shows on one of the endpoints 

### ISSUE THREAD

**Issue by baguilartech** [netbox-community/netbox#6472]
### NetBox version

v2.11.3

### Python version

3.6

### Steps to Reproduce

1. Create two devices each with their set of interfaces
2. Connect a cable between Device A:Interface A and Device B:Interface B
3. Assign an IP address to Device A:Interface A
4. Navigate to the interfaces tab of Device B and find Interface B connected to Device A:Interface A. IP address will not be assigned under Device B's interface page

Further observations: Happens also when IPs are assigned to interfaces using IP import.

### Expected Behavior

It would make sense that if a cable connects two endpoints together and if there is an address assigned to an interface on either side, then for troubleshooting and route tracing, the IP of the configured interface should be logically visible on both endpoints' interface listing.

### Observed Behavior

Here is a device that has been connected to multiple switches on different interfaces and had IPs assigned to it on it's page:
![Screen Shot 2021-05-21 at 3 39 04 PM](https://user-images.githubusercontent.com/5866029/119205230-90875080-ba4c-11eb-943c-a7c3088a0389.png)

Here is the one of the switches on the interface connected to that device:
![Screen Shot 2021-05-21 at 3 41 45 PM](https://user-images.githubusercontent.com/5866029/119205270-aa289800-ba4c-11eb-8f0e-f1b3fabec934.png)

And another separate switch exhibiting same behavior:
![Screen Shot 2021-05-21 at 3 42 13 PM](https://user-images.githubusercontent.com/5866029/119205285-b6acf080-ba4c-11eb-9c00-fe140527bca3.png)

**Comment by jeremystretch** [comment]
This is intended behavior. Assigning an IP address to an interface in NetBox implies that the IP address is configured on that interface. Each interface would have its own IP address.
