### ISSUE TITLE
Parent device inherits child's primary IP

### ISSUE THREAD

**Issue by CapnCheapo** [netbox-community/netbox#6479]
### NetBox version

v2.11.3

### Feature type

Change to existing functionality

### Proposed functionality

It would be nice if a parent device could inherit a child's primary IP if the primary doesn't already have an address assigned. Either automatically, in the case of a single child having a single primary, or otherwise maybe the child primaries show up in the parent's dropdown box.

### Use case

A chassis-based switch or router often does not have a management interface outside of whatever the supervisors have, but is considered managed by the sup's IP. This doesn't account for advanced setups such as active/standby sups or virtual device partitioning, but would be helpful for many standard use cases.

### Database changes

Unknown

### External dependencies

Unknown

**Comment by jeremystretch** [comment]
In NetBox, child devices have their own control plane and components, IP addresses, etc. From [the docs](https://netbox.readthedocs.io/en/stable/core-functionality/devices/#device-bays):

> Device bays are not suitable for modeling line cards (such as those commonly found in chassis-based routers and switches), as these components depend on the control plane of the parent device to operate. Instead, line cards and similarly non-autonomous hardware should be modeled as inventory items within a device, with any associated interfaces or other components assigned directly to the device.

This model is intended for e.g. blade servers and similar independent devices. Chassis line card should be modeled as inventory items, with their components and addressed added to the chassis device in which they reside.
