### ISSUE TITLE
Copy field data to form on "Create and Add Another"

### ISSUE THREAD

**Issue by Armadill0** [netbox-community/netbox#648]
If you're currently adding a new item, like a device, IP or anything else, it is possible to use the "Create and Add Another" button instead of the "Create" button. The first one leads again to the creation page where you could add another item of the same type. It would be another great enhancement if the field data which has been entered for the first item is getting transported to the "Create and Add another" page.
This would help to fast create multiple devices which are only slightly different from the former ones.

**Comment by Gelob** [comment]
I'd love this for prefixes as well. Being able to create a prefix in one site and then copy it to another but changing some of the data would make life much easier. i.e you have 10.1.0.0/24 in SITEA and define everything underneath that /24. Then you have 10.6.0.0/24 in SITEB and its all the same except the 2nd octet.

**Comment by Armadill0** [comment]
Maybe this can be solved together with #33, because both issues could work like "take data from existing item and copy to create new item page".

**Comment by Armadill0** [comment]
Maybe this can solved together with #33. Both could work like:
* select an item
* take data from existing item e.g. of type device
* jump to create device page
* insert data from selected item into form

**Comment by patrick-livestream** [comment]
+1 following along.

**Comment by candlerb** [comment]
Aside: [Custom Scripts](https://netbox.readthedocs.io/en/latest/additional-features/custom-scripts/) do retain the fields from one invocation to another.  So if you have a specific workflow where you need to use the web UI to create lots of similar objects differing only in a couple of values, making a custom script may be worth the effort.
