### ISSUE TITLE
Netbox Upgrade Script Fails When Python3 is not installed as /usr/bin/python3

### ISSUE THREAD

**Issue by ArcticSnowman** [netbox-community/netbox#6496]
### NetBox version

v2.7.0 to v2.11.12

### Python version

3.6

### Steps to Reproduce

install python3 somewhere other than /usr/bin/python3 
Add to path
run ./upgrade

### Expected Behavior

./upgrade should run using the python3 found in the PATH

### Observed Behavior

```
]# ./upgrade.sh
Creating a new virtual environment at /var/lib/netbox-2.7.12/venv...
./upgrade.sh: line 20: /usr/bin/python3: No such file or directory
--------------------------------------------------------------------
ERROR: Failed to create the virtual environment. Check that you have
the required system packages installed and the following path is
writable: /var/lib/netbox-2.7.12/venv
--------------------------------------------------------------------
```

**Comment by jeremystretch** [comment]
IIRC, we specify the full path to ensure that the system Python executable is used, rather the one from a virtual environment that might happen to be active. I'm not sure this really matters, though.

**Comment by thoms27** [comment]
Same issue with V2.11.6
