### ISSUE TITLE
define default values in openapi spec

### ISSUE THREAD

**Issue by FalcoSuessgott** [netbox-community/netbox#6518]
### NetBox version

v2.11.1

### Feature type

Data model extension

### Proposed functionality

It would be nice if the default values for each property (if any) are also defined in the  Netbox OpenAPI spec. They are, so far I can see, not defined for each and every object.

For example: 

```json
        "status": {
          "title": "Status",
          "type": "string",
          "enum": [
            "planned",
            "provisioning",
            "active",
            "offline",
            "deprovisioning",
            "decommissioned"
          ]
        },
```

 could be defined as

```json
        "status": {
          "title": "Status",
          "type": "string",
          "default": "active",
          "enum": [
            "planned",
            "provisioning",
            "active",
            "offline",
            "deprovisioning",
            "decommissioned"
          ]
        },
```

Since `active` value for status is the default returned by the API.

### Use case

This helps us updating various netbox resources using OpenAPI libs.

**Comment by FalcoSuessgott** [comment]
@jeremystretch we are really interested in that fix/feature.
I would like to give it a try, may you can insist me in where to start? I have a more or less complete list with missing default values. 

Really appreciate your assistance.

**Comment by jeremystretch** [comment]
I'm happy to assign this issue to you but don't have any availability to help at the moment. Maybe someone else would like to step up to help.

**Comment by FalcoSuessgott** [comment]
@jeremystretch nvm, I found an example: 

https://github.com/netbox-community/netbox/blob/28ca815c8855b06e4250e7610fadc7c968c91dcb/netbox/dcim/api/serializers.py#L902-L920

I will look into it this week then
