### ISSUE TITLE
Open searched item if only 1 result is found

### ISSUE THREAD

**Issue by MarcHagen** [netbox-community/netbox#6520]
### NetBox version

v2.11.3

### Feature type

Change to existing functionality

### Proposed functionality

Currently if you enter something in the search box you will end up in the Search Results page.
Cool, now imagine you are searching for a hostname of a device, you know the hostname because it's from another system or ticket. You copy paste it in the search-box and there is only one result. Horray! Now you have to click on the 1 result you get, a device as example, you again need to wait for the page to load. All in all this takes 2-5 seconds total.

My proposal is, if only 1 (not more, not less) result is found just open it.

### Use case

Searching for devices, ranges day in day out without the direct links in netbox just takes time to open a "useless" page to continue to that one device / range  you want to go.
Multiply that time you need to wait (2-5 seconds) to say 25-50 times? worst case you're waiting for 4 minutes.
It just saves time to do another click action on a page with only one result, which again is pretty pointless.

**Comment by jeremystretch** [comment]
Thank you for submitting this issue, however it appears that this topic has already been raised. Please see issue #2668 for further discussion.
