### ISSUE TITLE
Allow to use markdown on report description

### ISSUE THREAD

**Issue by maximumG** [netbox-community/netbox#6527]
### NetBox version

v2.11.3

### Feature type

Change to existing functionality

### Proposed functionality

I'd like to propose an enhancement on the look & feel of the r[eport_list.html](https://github.com/netbox-community/netbox/blob/develop/netbox/templates/extras/report_list.html) page.

Each report is currently presented in a List of 4 columns (_Name_ | _Status_ | _Description_ | _Last Run_). I would propose to render the _Description_ column using markdown support.

The change would be as simple as modifying the report_list.html template and add the class `rendered-markdown` and use the `markdown` django template function on the following line

https://github.com/netbox-community/netbox/blob/8d0a3c8e6932f4c523919180d3e75608cdf54a9b/netbox/templates/extras/report_list.html#L32

The markdown support has already been implemented for each report log messages so it won't be difficult to use the same feature for the Report description (check this [commit](https://github.com/netbox-community/netbox/commit/7c48e3632db052924c80213fc07faa8d3059fe7c))

I can handle this issue and propose a Pull Request.

### Use case

Adding markdown support to each Report description allows to structure the this description easily if we want to explain in more detail the whole test case covered.

### Database changes

None

### External dependencies

None

**Comment by jeremystretch** [comment]
> I can handle this issue and propose a Pull Request.

@maximumG have at it!
