### ISSUE TITLE
Journal Searchs by Comments but not Object

### ISSUE THREAD

**Issue by davekempe** [netbox-community/netbox#6530]
### NetBox version

v.2.11.3

### Python version

3.7

### Steps to Reproduce

Other -> Journal Entries
Enter device or virtual machine name in the Search field - no results found.

Searching for contents of comments works just fine.

### Expected Behavior

Search should search for objects by name or partial match, so we can do things like link to the journal from other systems.

https://netbox/extras/journal-entries/?q=hostname&created_after=&created_before=&kind=

Then I can link to netbox journal entries for this hostname from Icingaweb, or Confluence for example.

### Observed Behavior

No Results Found for Object names.

**Comment by jeremystretch** [comment]
The relationship from a journal entry to its assigned object is a generic foreign key. These cannot be efficiently followed for searching. The recommended path is to first search for the object, and then retrieve its associated journal entries.

**Comment by davekempe** [comment]
OK no worries, I will import the netbox_id as a host variable in Icingaweb, and build the URL from that.
