### ISSUE TITLE
Add Tenant Group to class "ipam.models.vlans.VLAN"

### ISSUE THREAD

**Issue by thoms27** [netbox-community/netbox#6543]
### NetBox version

v2.11.5

### Python version

3.6

### Steps to Reproduce

Hi,

Is it possible to add tenant group name to the class "ipam.models.vlans.VLAN" ?
I would like to filter with a group permission the access to the VLAN view only for the VLAN of a tenant group.

Thank you in advance

### Expected Behavior

Filter the VLAN view for a particular Tenant Group

### Observed Behavior

Actually only theses paramters are allowed:
created, custom_field_data, description, group, group_id, id, interfaces_as_tagged, interfaces_as_untagged, journal_entries, last_updated, name, prefixes, role, role_id, site, site_id, status, tagged_items, tags, tenant, tenant_id, vid, vminterfaces_as_tagged, vminterfaces_as_untagged

**Comment by jeremystretch** [comment]
Hi, it looks like you've opened a bug rather than a feature request. We require different information for each. Please resubmit your proposal as a [feature request](https://github.com/netbox-community/netbox/issues/new?assignees=&labels=type%3A+feature&template=feature_request.yaml). Thanks!
