### ISSUE TITLE
Add Tenant Group to class "ipam.models.vlans.VLAN"

### ISSUE THREAD

**Issue by thoms27** [netbox-community/netbox#6546]
### NetBox version

v2.11.5

### Feature type

Data model extension

### Proposed functionality

Hi,

Is it possible to add tenant group name to the class "ipam.models.vlans.VLAN" ?
I would like to filter with a group permission the access to the VLAN view only for the VLAN of a tenant group.

Thank you in advance

Actually only theses paramters are allowed:
created, custom_field_data, description, group, group_id, id, interfaces_as_tagged, interfaces_as_untagged, journal_entries, last_updated, name, prefixes, role, role_id, site, site_id, status, tagged_items, tags, tenant, tenant_id, vid, vminterfaces_as_tagged, vminterfaces_as_untagged

Thank in advance

### Use case

Filter the VLAN view for a particular Tenant Group

**Comment by drmsoffall** [comment]
You should be able to drill down in permissions with a double-underscore.  Try this constraint if you want to specify the tenant group's slug:

`{"tenant__group__slug": "your_group_slug_here"}`

Check the examples under Constraints here for more help:  https://netbox.readthedocs.io/en/stable/administration/permissions/

**Comment by thoms27** [comment]
Hi,

Thank you for your answer.
It seems working as expected. Thank you :-)
It's works too with tenant__group__name. I'm not familiar with the syntax :-)

Regards,
