### ISSUE TITLE
Support for SSF (Serial Attached SCSI) Interfaces

### ISSUE THREAD

**Issue by sHorst** [netbox-community/netbox#6549]
### NetBox version

v2.11.5-dev

### Feature type

Change to existing functionality

### Proposed functionality

Add Interface types for SAS:
- SFF-8088 (External mini-SAS)
- SFF-8614 (SFF-8644, External mini-SAS HD)

### Use case

Since i want to add our NetApp to my Netbox Setup, it would be great to have the possibility to add SFF Ports (see [https://en.wikipedia.org/wiki/Serial_Attached_SCSI#Connectors](https://en.wikipedia.org/wiki/Serial_Attached_SCSI#Connectors)) Interfaces and Connections.

**Comment by phurrelmann** [comment]
Some Dell Switches use this kind of connectors for stacking
