### ISSUE TITLE
Provider network search doesn't match on name

### ISSUE THREAD

**Issue by markkuleinio** [netbox-community/netbox#6553]
### NetBox version

v2.11.6

### Python version

3.7

### Steps to Reproduce

In the GUI:
1. Add a provider "TestProvider"
2. Add a provider network "TestNetwork" for provider "TestProvider"
3. Go to Provider Networks list
4. Enter "Test" in the search box in the right

### Expected Behavior

It is expected that the "TestNetwork" would be returned with a search of "Test".

### Observed Behavior

No provider networks are returned.

**Comment by proudbro** [comment]
Same behaviour for Journal Entries

**Comment by jeremystretch** [comment]
@proudbro please open a separate issue for that.
