### ISSUE TITLE
Broadcast connectors and cables

### ISSUE THREAD

**Issue by chesronw** [netbox-community/netbox#6555]
### NetBox version

v2.11.3

### Feature type

Change to existing functionality

### Proposed functionality

Hi,

We are migrating all of the documentation from phpIPAM and Patchmanager to Netbox. 
The only problem that we have is that we cannot define the broadcast cabling. 

It would be nice if we can put these devices with the IP address, Rack, Power, Etc in Netbox and also connect/define the broadcast connections like XLR, MADI, COAX/BNC, etc. 

The best way I think is the have an option to customize and add connectors/ports and the cables.
If we have this inside Netbox then we have the full data center documentation in Netbox. 
 
 I already read other requests from other AV partners in this community that they also want to have a solution like this.
 It will help us a lot to have this inside Netbox and it makes Netbox bigger than all the other platforms. 
 
 We are looking forward to working on this with you. 

### Use case

Add of define custom cables and ports will help the broadcast companies to not only add the broadcast equipment as a device in a rack with power and an IP address but also helps us to define the AV connections between each other.

**Comment by jeremystretch** [comment]
Thank you for your proposal. Unfortunately, support for A/V systems modeling is out of scope for NetBox at this point in time, as it focuses primarily on network infrastructure. We may re-evaluate this in the future. Thanks again!
