### ISSUE TITLE
CSV file import

### ISSUE THREAD

**Issue by abigley** [netbox-community/netbox#6560]
### NetBox version

v2.11.6

### Feature type

New functionality

### Proposed functionality

Allows users to upload a csv file of new objects into netbox in addition to the current textbox for bulk import. 

### Use case

Provides an easier way for users to upload large amounts of data into netbox at one time.

**Comment by lashingovender** [comment]
any videos on how to import and submit a csv import?

**Comment by jkuzma07** [comment]
> 
> 
> any videos on how to import and submit a csv import?

In my opinion, the v2.11.10 web UI requires no further explanation:

![image](https://user-images.githubusercontent.com/56645510/127687358-82a1fc61-1743-47f8-bff5-c2649de3cb31.png)

If this doesn't answer the question, you're better off asking in the [discussions](https://github.com/netbox-community/netbox/discussions), or on Slack.
