### ISSUE TITLE
Ability to global search by Journal Entries comments 

### ISSUE THREAD

**Issue by proudbro** [netbox-community/netbox#6567]
### NetBox version

v.2.11.4

### Feature type

New functionality

### Proposed functionality

Journal Entries is one of the best recently added features. I hope it will continue to improve further. A lot of useful and important information can be found in Comments section and I would like to find it as quickly as possible.
Please, add the ability to global search by Journal Entries comments. 

### Use case

1. Add Journal Entry for device with comment with text `TEST`
2. Try to find by text `TEST` by using any of two Global Search field
![image](https://user-images.githubusercontent.com/60253505/121177748-7334ed80-c866-11eb-8b6f-013194602d26.png)
![image](https://user-images.githubusercontent.com/60253505/121177766-79c36500-c866-11eb-907a-d9b619d99fbe.png)
3. It doesn't work

### Database changes

-

### External dependencies

-

**Comment by TheFlyingCorpse** [comment]
Yes, highly desired!

**Comment by ziggekatten** [comment]
Could we have a look at this again?
