### ISSUE TITLE
Export Portmaps and Rack Elevations

### ISSUE THREAD

**Issue by catagris** [netbox-community/netbox#6569]
### NetBox version

v2.9.4

### Feature type

New functionality

### Proposed functionality

It would be great to be able to export portmaps and elevations of racks individually or per site.

### Use case

Exporting a state of a site for a customer.

**Comment by jeremystretch** [comment]
Please elaborate on exactly what you want to do, what you've tried so far, and what specific changes you are proposing.

**Comment by jeremystretch** [comment]
No, NetBox doesn't support anything like that natively, and probably won't because it's likely going to be very subjective in its implementation. Sounds like a good use case for a plugin though.
