### ISSUE TITLE
Filter on custom field via API

### ISSUE THREAD

**Issue by christopheg** [netbox-community/netbox#6572]
### NetBox version

v2.11.6

### Python version

3.7

### Steps to Reproduce

A custom field is created for object 'Device': warranty_expiration of type Date.
When fetching the devices via API an extra condition is added: cf_warranty_expiration__gt=2020-03-21

### Expected Behavior

When applying this filter, I would expect to only see devices with custom field 'warranty_expiration' set to a date after 2020-03-21

### Observed Behavior

The filter is not applied. All devices are returned.

**Comment by jeremystretch** [comment]
> `cf_warranty_expiration__gt=2020-03-21`

I don't believe we support lookup expressions for custom fields. Searching on the field by exact match should work though; does it?

**Comment by christopheg** [comment]
I can confirm thaat an exact match does work. Based on the documentation I expected the expressions to work also for the custom fields but apparently not...
Is that something that could be added?
Also, do you think the 'gt' expression would work for type Date?

**Comment by jeremystretch** [comment]
> Based on the documentation I expected the expressions to work

That's a fair point; we should call out the caveat for custom fields.

> Is that something that could be added?

I'm actually not sure. Custom field values are stored in JSON blobs, so PostgreSQL doesn't actually know e.g. that a date is a date as opposed to just a string. The data type is necessary to perform lookups other than exact match. It does know about the different JSON types (strings, integers, and booleans) though, so we can probably implement filter lookups for those, at least.

**Comment by jeremystretch** [comment]
Thinking about this some more, this might work if we establish a dedicated set of lookups for date/time types (e.g. `before` and `after` rather than greater/less than) to imply the type, and cast the value on lookup.

**Comment by christopheg** [comment]
Maybe this is not related, but there seems to be a similar feature already available: If you go to the web interface to 'devices' and add a column for the custom field with the date, you can sort on it. I suppose somehow this sorting is done on the PostgreSQL side? If so, maybe that technique can be re-used?

**Comment by jeremystretch** [comment]
That's a good point actually. We store datetimes as strings, which are inherently ordered alphabetically, so maybe we don't need anything more complex. I'll need to dig into how the specific lookups actually function at the database level.

**Comment by jeremystretch** [comment]
I've opened #6615 to propose the implementation of lookups for custom fields. Let's concentrate further discussion there.
