### ISSUE TITLE
Canot create child device

### ISSUE THREAD

**Issue by xPakrikx** [netbox-community/netbox#6578]
### NetBox version

v2.11.6

### Python version

3.6

### Steps to Reproduce

1.Add a new device
2.I do not see any option to select Parent for child device

### Expected Behavior

Possibility select Parent device if device type is child

### Observed Behavior

error: A U0 device type (M5424) cannot be assigned to a rack position

**Comment by xPakrikx** [comment]
I dont know if its my problem or bug. Just i have already some devices from older netbox version as a parent and child. But when i want create new child device and select Device bay ... there no option like that. Any help ?

**Comment by drmsoffall** [comment]
When you create the child device, assign it to the same Rack as the parent device (but do not assign it to a Position, leave that blank).  Then go to the parent device, and under Device Bays, click the `+` (Install Device) button on the bay you want to install it in.  Select the child device, then you should be done.

If this doesn't work make sure your Device Types are set up correctly, check the Parent and Child settings for each type.

**Comment by xPakrikx** [comment]
Ou ok ok :) so its working now :) 
Thanks
