### ISSUE TITLE
Nested inventory items are not displayed correctly

### ISSUE THREAD

**Issue by kr3ator** [netbox-community/netbox#6584]
### NetBox version

v2.11.3

### Python version

3.8

### Steps to Reproduce

1. Add an inventory item, e.g. server0
2. Create some more child elements to the previous element, e.g. cpu, ram, slot0, slot1
3. Created new inventory  items (item0, item1) for each of slot0 and slot1

### Expected Behavior

Invetory view should display all inventory items sorted alphabetically starting from the top most item to the last child element adding correct indentation.

server0
-cpu
-ram
-slot0
--item0
--item1
-slot1
--item0
--item1

### Observed Behavior

All items have correct indentation level but they are sorted alphabetically regardless of the structure

-cpu
--item0
--item0
--item1
--item1
-ram
server0
-slot0
-slot1

**Comment by jeremystretch** [comment]
Looks like we were inadvertently overwriting MPTT's ordering logic in the table. Easy fix. Thanks for the heads up!
