### ISSUE TITLE
Support WebP format image uploads

### ISSUE THREAD

**Issue by fknorn** [netbox-community/netbox#6588]
### NetBox version

v2.11.4

### Feature type

Change to existing functionality

### Proposed functionality

Currently, image uploads of a range of "classic" image formates are supported (jpg, png, etc.). However, the WebP-format ist missing in that list. Most modern webbrowser [support this format natively](https://caniuse.com/webp) and its popularity is evergrowing.

### Use case

Upload device type images with transparent background

### Database changes

None

### External dependencies

Not too sure what kind of internal processing is done to the imagery, but any involved libraries would need to support this format.

**Comment by jeremystretch** [comment]
NetBox relies on [Django's ImageField](https://docs.djangoproject.com/en/3.2/ref/models/fields/#imagefield) to model images, which in turn relies on Python's [Pillow](https://pillow.readthedocs.io/en/stable/) image processing library. If Pillow and Django support webp images, NetBox should too. However, [Pillow's documentation](https://pillow.readthedocs.io/en/stable/handbook/image-file-formats.html#webp) warns:

> Pillow reads and writes WebP files. The specifics of Pillow’s capabilities with this format are currently undocumented.

I'll mark this as `needs owner` for anyone who wants to dig into this.

**Comment by jeremystretch** [comment]
Seems like all the library support is already there; we just need to add `image/webp` to the list of accepted image types for DeviceType front and rear images. (Image attachments already support webp files in the current release.)

**Comment by fknorn** [comment]
Thanks, Jeremy ! Happy summer (at least to all the northern hemispherians :-))
