### ISSUE TITLE
half-width devices in rack and create blindpanels / cable guides with using it as an "device"

### ISSUE THREAD

**Issue by chesronw** [netbox-community/netbox#6591]
### NetBox version

V2.11.3

### Feature type

New functionality

### Proposed functionality

Hi,

We would like to add half-width devices without using a parent device.
This because the parent isn't a device but a mounting kit where we can add 2 devices on it. 

To work with nonparent devices we cleaning up all the fake devices that are used as a "device" but are not a device.
It is more rack equipment or tooling.
This is also a good request to add nondevices in racks like blind panels, or cable guides. 

So we keep the device list clean with only real devices. 

hopefully, you also see the value in it. 

### Use case

Use case is verry simple. 
i assume that everyone that is working with netbox are also using this tool to have a complete view of all the racks that they have and how the layout is of the racks. include of all the blind panels and cable managers. 

It's just really weird to create for each blind panel and cable manager an device.. 
Or make the option that you can add a device in multiple racks. 

Then we have also the half-width devices. 
These devices are currently not supported in Netbox.. well with a dirty solution to have a parent (Non-device) but this really creates a huge mess in the device list. 
To prevent this.. it better to give the option that the device is a half-width device that you can add to a rack.. on the left or right. in that case you can add two half-width devices on the same HE in the RACK

**Comment by jeremystretch** [comment]
This was proposed back in #2467 and rejected as it violates one of NetBox's core design tenets: closely modeling the real world.

> This because the parent isn't a device but a mounting kit where we can add 2 devices on it.

But it _is_ a device, and must be modeled as such. It is impossible to physically mount a child device without it, and it is impossible to install a non-child device in a rack unit where such a mount kit has been installed.

The simple solution is to create these mounting kits as parent devices, and model the devices within them as children.
