### ISSUE TITLE
Calling save() on InventoryItem without changes produces unnecessary changelog entry

### ISSUE THREAD

**Issue by bluecmd** [netbox-community/netbox#6599]
### NetBox version

v2.11.6

### Python version

3.7

### Steps to Reproduce

1. Call `save()` on an InventoryItem via Netbox Script:

```python3
it = InventoryItem.objects.all()[0]
it.save()
```

2. Check changelog of the object
3. The changelog only shows "Post-Change Data" and an empty "Pre-Change Data"

If I call `.snapshot()` before the "Pre-Change Data" is populated, and the UI shows "No difference".

### Expected Behavior

- Either mentioning that `.snapshot()` is important for Netbox Scripts on the https://netbox.readthedocs.io/en/stable/additional-features/custom-scripts/ website, or make it automatic, would be appreciated
- That `.save()` with no changes is silent/ignored.

### Observed Behavior

An moot changelog entry is created.

**Comment by bluecmd** [comment]
For now I have worked around this in my scripts by doing this:

```diff
-                iitem.part_id = psu['name']
-                iitem.serial = psu['serialNum']
-                iitem.discovered = True
-                iitem.save()
+                if iitem.part_id != psu['name'] or iitem.serial != psu['serialNum'] or not iitem.discovered:
+                    iitem.snapshot()
+                    iitem.part_id = psu['name']
+                    iitem.serial = psu['serialNum']
+                    iitem.discovered = True
+                    iitem.save()
```

If this is the intended way going forward I am OK with updating my scripts accordingly but ask that e.g. the example Custom Script is updated with this information on how to best do changes.

**Comment by jeremystretch** [comment]
This intended behavior. Even when no data is being modified, there may still be a desire to record that a save event took place.

**Comment by bluecmd** [comment]
Ok thanks for confirming.

I would suggest adding a section to https://netbox.readthedocs.io/en/stable/additional-features/custom-scripts/ describing the semantics around save() and snapshot(). It was quite hard going down the rabbit hole of Django data models and how things are supposed to work together, so that might be useful for people.
