### ISSUE TITLE
Maintain history of daily object counts

### ISSUE THREAD

**Issue by jeremystretch** [netbox-community/netbox#6601]
### NetBox version

v2.11.6

### Feature type

New functionality

### Proposed functionality

Start recording the total count of each type of object in NetBox daily, and make these metrics available within the UI.

### Use case

With #6590 implemented for the upcoming v3.0 release, we can easily record a daily count of all objects, to be displayed as a graph within the UI. For example, a graph showing the 90-day running history for sites, devices, prefixes, etc. on the main view could be very useful. We might also provide a more generalized view where users could select the object types in which they're interested and view a longer period.

### Database changes

This will likely require a new model to store the daily counts. I imagine something simple, such as:

```
class ObjectsCount(models.Model):
    date = models.DateField(unique=True)
    counts = models.JSONField()
```

`counts` would be a JSON field mapping each model name (e.g. `dcim.site`) to an integer. Only one instance may be created per day. (An existing instance may be updated with new counts through the day if needed.)

**Comment by ziggekatten** [comment]
In my view, this is outside the scope for netbox. 

We achive this today already using apache Superset, giving us a daily/weekly/monthly metric based on created date, wich is a brilliant open source solution for all kind of reporting/analytics

Focus on core features, like support for SDN would in my view be more important.

**Comment by tyler-8** [comment]
I agree with @ziggekatten actually. This kind of functionality is useful for sure, but I'm not looking to my SoT for historical metrics. Today I'm using this great plugin https://github.com/networktocode/ntc-netbox-plugin-metrics-ext to get exactly this kind of data.

If anything, I think building that plugin's functionality in to NetBox would be a better direction and would use the existing tooling for exposing the metrics. The advantage to that route is its generating metrics in a common and open metrics format that can be consumed by any number of existing tools (prometheus itself, telegraf, etc) and stored outside of NetBox in a platform designed for precisely these kinds of metrics.

**Comment by jeremystretch** [comment]
Maybe I wasn't clear in my intent. The goal here is to provide some lightweight historical metrics on basic object counts in NetBox e.g. to replace the sparse object counts on the main view. This is intended as a convenience rather than full-featured reporting. Certainly there are other ways of achieving that (including NetBox's built-in support for [Prometheus metrics](https://netbox.readthedocs.io/en/stable/additional-features/prometheus-metrics/). However, IMO it's not acceptable to require users to install and configure an entirely separate tool simply to view some quick stats about their NetBox installation.

**Comment by jeremystretch** [comment]
Gonna bail on this idea as it doesn't seem popular, and likely isn't worth the effort.
