### ISSUE TITLE
Include steps for RHEL distro application checks

### ISSUE THREAD

**Issue by mistabe** [netbox-community/netbox#6612]
### Change Type

Addition

### Area

Installation instructions

### Proposed Changes

Include a brief step to disable Firewalld on RHEL based distros to allow the application test checks to work and then re-enable them here ; https://netbox.readthedocs.io/en/stable/installation/3-netbox/#test-the-application

**Comment by mistabe** [comment]
Happy to be assigned this task. Awaiting submission of a PR afterwards.

**Comment by jeremystretch** [comment]
@mistabe all yours!
