### ISSUE TITLE
Filter on custom field of type Integer via API returns every item

### ISSUE THREAD

**Issue by luitzifa** [netbox-community/netbox#6613]
### NetBox version

v2.11.6

### Python version

3.7

### Steps to Reproduce

1. Create a custom_field "someid" for ip-addresses of type Integer with min value 1 and max value 255. Default is left emtpy which will get filled with "null"
2. Try to filter for ip-addresses with value greater than equal 1 like described in the docs https://netbox.readthedocs.io/en/stable/rest-api/filtering/ => https://netbox/api/ipam/ip-addresses/?cf_someid__gte=1

### Expected Behavior

Get those ip-addresses with custom_field someid containing a number between 1-255.

### Observed Behavior

I get all ip-adresses, even those with 
```
"custom_fields": {
      "someid": null
 },
```

**Comment by luitzifa** [comment]
I don't now if this is related to #6572 because the other issue is strongly focused on the type date.

**Comment by jeremystretch** [comment]
NetBox doesn't currently support lookups on custom fields. I've opened #6615 to propose this feature. Please keep an eye on that issue for updates.
