### ISSUE TITLE
Configuration context assiged by VLAN

### ISSUE THREAD

**Issue by jcralbino** [netbox-community/netbox#6617]
### NetBox version

v2.11.4

### Feature type

Change to existing functionality

### Proposed functionality

Allow the assignment of a configuration context using a vlan.
Whenever a VLAN assigned to a device interface the associated configuration context will be assigned to it

Currently the configuration context is assigned based on Regions, Site Groups, Sites, Device Types, Roles, Platforms, Cluster Groups, Clusters, Tenant Groups, Tenants and Tags.

This will add another field in order to fine tune the utilization of this feature.

### Use case

It allows to document better the required network configuration a device needs to have depending of its associated vlan. 

### Database changes

none

### External dependencies

none

**Comment by jeremystretch** [comment]
What have you opened this in addition to #6340? As I explained [here](https://github.com/netbox-community/netbox/issues/6340#issuecomment-853250277) this is not feasible without making disruptive changes to the data model.

**Comment by jcralbino** [comment]
Indeed it seems a duplicate one.. I just opened yesterday when I was configuring some devices and the change in the filter seemed logic.
Please close this one
