### ISSUE TITLE
Limit the visibility of unused custom fields in the GUI

### ISSUE THREAD

**Issue by jcralbino** [netbox-community/netbox#6618]
### NetBox version

v2.11.4

### Feature type

Change to existing functionality

### Proposed functionality

Currently we can associate custom fields to almost any object in Netbox. 
After they are created they will be shown in the webinterface of that object. 

This would be valid for all custom fields that do not have the flag required enabled. 

I propose to only show the custom fields being used ( not empty) when viewing that specific object. 

### Use case

Reduces the noise on the information provided to the user, when viewing a device.

When editing the device all options would be there

### Database changes

none

### External dependencies

none

**Comment by jeremystretch** [comment]
There is already an open issue for this, which you have commented on: #6296.

**Comment by jcralbino** [comment]
Hello Jeremy. I created this one to have the scope more defined as the previous one had one different initial request. 
In the end I am ok to close this If we can implement the feature in the other one
