### ISSUE TITLE
Activation of "Descending units" in an populated rack ends up with devices in the wrong spots

### ISSUE THREAD

**Issue by martinum4** [netbox-community/netbox#6619]
### NetBox version

v2.11.6

### Python version

3.7

### Steps to Reproduce

1. Create and populate a rack
![rack-normal](https://user-images.githubusercontent.com/18295403/122375627-b0cf0000-cf63-11eb-979a-6414c0176d47.PNG)

2. Edit the Rack, tick the box "Descending units" and save
3. Devices end up in the wrong physical locations, they are not assigned to the new unit number.
![rack-reversed](https://user-images.githubusercontent.com/18295403/122375632-b1679680-cf63-11eb-9e72-1bb9dc93f576.PNG)

### Expected Behavior

I expected the devices to stay in the same spot, not move inside the rack.

### Observed Behavior

See Steps to reproduce

**Comment by jeremystretch** [comment]
Toggling the unit order merely changes the order in which the rack is rendered. You'll need to correct the individual unit assignments of each device, since they were entered incorrectly.
