### ISSUE TITLE
Error when setting default value for multiple selection custom field

### ISSUE THREAD

**Issue by saruter** [netbox-community/netbox#6628]
### NetBox version

v2.11.4

### Python version

3.6

### Steps to Reproduce

1) Add custom field type "Multiple Selection"
2) Add a default value for it, it is a string, for example "red" (with double quotes)
3) Add Choices: red,blue,green
4) Add Content-Type: Site
5) Click Save
6) Error at Default field: "Invalid default value "red": Invalid choice(s) (r, e, d). Available choices are: red, green, blue"

### Expected Behavior

A default value is possible to set for a multiple select custom field.

### Observed Behavior

Error Message at Default-Value-Field:
Invalid default value "red": Invalid choice(s) (r, e, d). Available choices are: red, green, blue

**Comment by drmsoffall** [comment]
The multi-select field wants an array as a default value.  Try setting it like this:
```
["red"]
```
The square brackets are needed, even if the default is only one value.

**Comment by jeremystretch** [comment]
This feels like a bug at first, but I think @drmsoffall's approach is correct. We're specifying the field's default value, which should be a raw JSON value. Since a multi-select custom field may have a default value containing multiple selections, the default value should be specified as a list.

**Comment by proudbro** [comment]
I noticed that if we specify any single value in multiple selection custom field, then we will see it in this form:
`t,e,s,t`

That is, each letter is separated by a comma
