### ISSUE TITLE
VLAN group not preselect when creating VLAN from VLAN group

### ISSUE THREAD

**Issue by tobiasge** [netbox-community/netbox#6637]
### NetBox version

v2.11.7

### Python version

3.8

### Steps to Reproduce

1. Create VLAN group
3. Use "4094 VLANs available" button to add a VLAN

### Expected Behavior

VLAN group in "Assignment" is preselected

### Observed Behavior

VLAN group is not selected

**Comment by jeremystretch** [comment]
This is intended behavior. A scope need not be a site: it may be a region, site group, site, location, or rack. The assignment of a VLAN to both a site-scope VLAN group and a site is redundant.

**Comment by tobiasge** [comment]
From what I have seen in the link, it worked like this before the change to "scope" was made. 
And even when it is not desired to preselect both, the VLAN group should be selected. Have a look at the PR, and you will see the problem.

**Comment by tobiasge** [comment]
I have updated the description above:
It can be re-produce in the demo:
- Open https://demo.netbox.dev/ipam/vlan-groups/3/
- Button "200 VLANs available" has this link: https://demo.netbox.dev/ipam/vlans/add/?vid=1&group=
- Button on top "+ Add VLAN" has this link: https://demo.netbox.dev/ipam/vlans/add/?group=3

The difference is the missing group id in the first link. I hope this makes the problem more understandable.

**Comment by jeremystretch** [comment]
Thanks, I see what you're saying now. AFAICT this has been broken for a while.
