### ISSUE TITLE
Upload device_type images via API

### ISSUE THREAD

**Issue by nyevess** [netbox-community/netbox#6648]
### NetBox version

v2.11.1

### Feature type

New functionality

### Proposed functionality

I suggest implement the method of upload images for device_type via API

### Use case

I'm doing a big migration from OpenDCIM to Netbox, and I need migrate my device_type images via API, and I have not been able to find a way for doing this. 
If this it's possible now, please let me know how to doing.
Thanks

**Comment by jeremystretch** [comment]
> I suggest implement the method of upload images for device_type via API

What specific implementation are you proposing?

**Comment by nyevess** [comment]
I would propose adding to the POST request, two fields:
1. Front image
2. Rear image
And they will processed like the rest of the fields, codifying the image file (jpg,png,etc.) with base64 for example.
I would clarify I'm not an expert programming and I don't know the Netbox code.
Do you see this as possible?
Thank you!
