### ISSUE TITLE
Adding Power Ports to multiple Devices Fails

### ISSUE THREAD

**Issue by AnneWielis** [netbox-community/netbox#6652]
### NetBox version

v2.11.7

### Python version

3.8

### Steps to Reproduce

1. select multiple devices (in my cases: a bunch of switches)
2. choose "Add Components -> Power Ports"
3. Specify some data (name, title, power conumption data, type)
4. Save
![Skærmbillede fra 2021-06-22 15-22-59](https://user-images.githubusercontent.com/41674213/122932314-eb72d700-d36d-11eb-8e49-c56163147de2.png)

### Expected Behavior

Should work

### Observed Behavior

 There was a problem with your request. Please contact an administrator.

The complete exception is provided below:

<class 'AttributeError'>

'PowerPort' object has no attribute 'parent'

Python version: 3.8.5
NetBox version: 2.11.7

**Comment by AnneWielis** [comment]
OK, that was _really_ quick. Thanks for looking into it.

**Comment by jeremystretch** [comment]
Thanks for the bug report!
