### ISSUE TITLE
Custom scripts docs: repetition of optional variables

### ISSUE THREAD

**Issue by bluikko** [netbox-community/netbox#6654]
### Change Type

Cleanup (formatting, typos, etc.)

### Area

Functionality/features

### Proposed Changes

The documentation repeats two times the optionality of variables:
```
Variables allow your script to accept user input via the NetBox UI, but they are optional: If your script does
not require any user input, there is no need to define any variables.
```
and
```
Defining script variables is optional: You may create a script with only a `run()` method if no user input is needed.
```

This seems to me like a repetition of the same statement.

I am unsure which one would be better to keep so the PR just takes one at random.

**Comment by jeremystretch** [comment]
This is fine. It's often beneficial, even necessary, to repeat things in documentation.
