### ISSUE TITLE
Tagged (ALL) exclude VLANs, Tagged Vlan Range

### ISSUE THREAD

**Issue by de-Rick** [netbox-community/netbox#6660]
### NetBox version

v.2.11.7

### Feature type

Change to existing functionality

### Proposed functionality

Sometimes you need to assign all the vlans available (in our usecase 50+) in your netbox project except for 1-2 Vlan-IDs. When you choose "Tagged (All)" this functionality is not implemented yet. Instead you have to add all the allowed vlans one by one to the Interface. After 10 VLANs-ID this really takes long. I tried to build custom field for it, but then it is not connected with the VLAN-IDs. 

And it is also not possible to specify a VLAN-ID range for e.x 1-90 and 95-200. This could also be a solution for the "first issue"

### Use case

It is possible to document the vlan-config more quickly. I think I am not the only one who would profit from this feature.

**Comment by jeremystretch** [comment]
We don't support this for several reasons:

1. This approach is inherently error-prone. If a user adds a new VLAN within the allowed scope, it will be included automatically, whether or not that is intended.
2. There is no reasonable way to declare the scope of permitted VLANs (e.g. by site or VLAN group).
3. It would greatly complicate the modeling.
