### ISSUE TITLE
Custom Fields should gain ability to store hyperlink base URL

### ISSUE THREAD

**Issue by c-po** [netbox-community/netbox#6663]
### NetBox version

v2.11.7

### Feature type

New functionality

### Proposed functionality

There is the functionality for Custom Links which will render a button on the top right location for NetBox. This is very handy but I could not get this to work to reference a custom field from within the object itself (tried using the keys exposed by the NetBox API).

When a new custom field is added which e.g. holds the reference to a ticketing system, it should not only be able to a a constraining regex, but also a base URL.

![image](https://user-images.githubusercontent.com/25299219/123290030-3b3dd380-d511-11eb-991a-93c741af86a3.png)

When the IP address, prefix or whatever this custom field is bound to is displayed, I would like to see a hyperlink which consists out of `http://base.url/foo/bar/VALUE`. Like this is done for the emea tenant in the screenshot below.

![image](https://user-images.githubusercontent.com/25299219/123291155-257cde00-d512-11eb-9b79-a79528905c7d.png)

### Use case

Fast and easy way to back reference to your IT ticketing system - or any other system/information you add to your custom fields.

**Comment by ktims** [comment]
> This is very handy but I could not get this to work to reference a custom field from within the object itself (tried using the keys exposed by the NetBox API).

You can reference them as `obj.cf.name`, e.g. `http://base.url/foo/bar/{{ obj.cf.incident }}` should work.

**Comment by c-po** [comment]
Hi @ktims wow, that works like a charm - I was just looking at the wrong key.

Do you happen to know to have an idea for the other feature request to replace the custom field content with a hyperlink?

**Comment by DanSheps** [comment]
I think the original issue is resolved.  I do potentially see value in a "hyperlink" Customfield where the customfield data input is linkable in some fashion.  For now though, I tihnk we can close this out.
