### ISSUE TITLE
Make data stored in custom fields searchable

### ISSUE THREAD

**Issue by c-po** [netbox-community/netbox#6664]
### NetBox version

v2.11.7

### Feature type

New functionality

### Proposed functionality

Data stored inside custom fields are excluded from the custom search.

This is somewhat related to #6663 as I tried to search my entire NetBox database for all occurances of one incident number I references inside a custom field of an IP address.

The description field is searchable by the global search. Is there any reason this is not supported by the global search on custom fields?

### Use case

List of all documentation changes related to e.g. one IT ticket/incident referenced via a custom field.

**Comment by jeremystretch** [comment]
Marking this as blocked by #7016

**Comment by jeremystretch** [comment]
This is actually covered by #6003.
