### ISSUE TITLE
Use GB (gigabyte) as display unit for virtual machine "Memory" field

### ISSUE THREAD

**Issue by jensrudolf** [netbox-community/netbox#6667]
### NetBox version

v2.11.7

### Feature type

Change to existing functionality

### Proposed functionality

Change the displayed unit of VM memory from MB (megabyte) to GB (gigabyte) or make the unit selectable when creating / editing the VM.

### Use case

We have a lot of VMs documented in NetBox. Many of them are Linux and Windows Servers which today usually have memory resources > 1 GB. Documenting a memory capacity of several gigabytes in MB makes it (at least in my opinion) less readable and harder to import from let's say sources like VMware vSphere. Therefore, I propose to change the unit to gigabyte or let the user select between gigabyte or megabyte.

**Comment by pabe-github** [comment]
@jeremystretch 
Hi there, thanks for this change.
It introduced a small UI bug:
![image](https://user-images.githubusercontent.com/42635243/131511755-1a0e461c-20a5-400d-801a-065cedfd5747.png)

We think the problem results here: 
<th scope="row"><i class="mdi mdi-chip"></i> Memory</th>
<td>
{% if object.memory %}
**{{ object.memory|humanize_megabytes }} MB**
{% else %}
<span class="text-muted">&mdash;</span>
{% endif %}
</td>
seems to always add MB regardless of the result of humanize_megabytes

**Comment by pabe-github** [comment]
@jeremystretch 
https://github.com/netbox-community/netbox/commit/88e382e7a1da2033c7e37e2887d798c090c4abc2#diff-f6bfbfaa26e6babdbc7322fcd237850c6875ba144341128c3978a82e86afcea4
You just need to remove the MB on line 145 becrause humanize_megabytes already includes the unit

**Comment by jeremystretch** [comment]
This issue has been closed for two months and no further action will be taken on it. Please see #7083.
