### ISSUE TITLE
UI Invisible Custom Field

### ISSUE THREAD

**Issue by proudbro** [netbox-community/netbox#6677]
### NetBox version

v.2.11.7

### Feature type

New functionality

### Proposed functionality

Since there is no way to restrict employees' access to editing specific fields I propose to add the ability to create web interface invisible custom fields.
It will be only possible to receive and send data via API. Thus, we will warn against accidental changes to sensitive data for third-party integrations.

### Use case

Example: 
- We have integration between Zabbix and Netbox
- Each Rack in Netbox has Custom Field value with Zabbix host ID related to this rack. Zabbix receives additional data about rack from Netbox (it can be alarms, power limits or so) 
- If someone enters via Web UI incorrect data there it will break the integration

### Database changes

+

### External dependencies

-

**Comment by thefreakquency** [comment]
I would love if this could be happening. I would not limit this to custom properties, but also to "normal" fields. That would be great if we could simplify and make the UI lighter when fields are not to be used (ie: in site page).  Perhaps something feasible in 3.0 with the upcoming UI overhaul?

**Comment by DanSheps** [comment]
I think what you want would be more suitable to moving to a config context and restrict editing of contexts to more "trustworthy" people.

**Comment by proudbro** [comment]
@DanSheps , Rack model doesn't have config context. This is the whole problem
