### ISSUE TITLE
Export Template

### ISSUE THREAD

**Issue by andremschulz** [netbox-community/netbox#6688]
### NetBox version

v2.10.8

### Feature type

New functionality

### Proposed functionality

Add option to export item inventory templates. In Export Template >> Content type 

### Use case

Users can generate item inventory report.

**Comment by jeremystretch** [comment]
Good news! This is already supported in the current release. I believe it was added in v2.11.0. You can create export templates for all device components.

**Comment by andremschulz** [comment]
Thank's @jeremystretch !!
