### ISSUE TITLE
Custom fields at interface creation not displayed

### ISSUE THREAD

**Issue by FredClement91** [netbox-community/netbox#6696]
### NetBox version

V2.11.7

### Python version

3.7

### Steps to Reproduce

1. Configure a custom mandatory field on an VM interface.
2. Try to create an interface

### Expected Behavior

I expect the interface to be created

### Observed Behavior

A error is raised, saying that I haven't filled up the mandatory custom fields. The problem is that these fields are not even shown in the form.

**Comment by jeremystretch** [comment]
Thanks for the bug report. Looks like this was just recently addressed under #6680. Will be fixed in the upcoming v2.11.8 release.
