### ISSUE TITLE
Virtual machine parent interface assignment issue via API

### ISSUE THREAD

**Issue by Toosaman** [netbox-community/netbox#6701]
### NetBox version

v2.11.8

### Python version

3.7

### Steps to Reproduce

1. Trying to create (or update) vm.interface object with parent interface assignment via API:
```
/api/virtualization/interfaces/
{
    "virtual_machine": 2,
    "name": "test1",
    "parent": 172
}
```

### Expected Behavior

Interface successfully created (or updated) and object returned.

### Observed Behavior

Getting an error:
```
{
    "parent": [
        "Related object not found using the provided numeric ID: 172"
    ]
}
```

**Comment by omri-ice** [comment]
Getting a similar issue when using the nested option for the parent `'parent': {'name': parent, 'virtual_machine': nb_dev.id},`

getting the following error:
```json
