### ISSUE TITLE
Extend the image attachments feature to Power panels

### ISSUE THREAD

**Issue by fabricat** [netbox-community/netbox#6708]
### NetBox version

v2.11.7

### Feature type

New functionality

### Proposed functionality

I'd like to attach one or more photos of power panels in Netbox, similarly to what is already possible for racks, devices, etc.

### Use case

Power panels are one of the least considered parts of a data center... until you have an emergency and need to access it.
Panels can have different aspects and could be installed in disparate places.

Having one or more photos available in Netbox would greatly help (a picture is worth a thousand words) in rapidly locating and identifying power panels, and all the related feeds / circuit breakers.

**Comment by jeremystretch** [comment]
We probably want to revisit adding image attachments to other models as well.

**Comment by jeremystretch** [comment]
Also adding images for circuits as proposed in #7322
