### ISSUE TITLE
Devices -> Interface Connections search field only searches A end of Connection

### ISSUE THREAD

**Issue by nmiller2600** [netbox-community/netbox#6712]
### NetBox version

v2.11.7

### Python version

3.7

### Steps to Reproduce

Click on Devices -> Interface connections
Take note of a device that's in the "Device B" column
Enter the name of that device in the device field under "search"

### Expected Behavior

I expect all connected interfaces for a given device to show up when I search for a given device.  
Having to know the A/BNess of a cable makes searching for connections nearly useless.

This looks related to 5223, but I'm not sure that "removing dedicated views" would necessarily provide a fix for usage of the provided GUI.

### Observed Behavior

No results are returned for connections for which the device is in the B end.
You may receive some results if the device in question is on the A-side of other various connections, but this is incomplete data.

**Comment by jeremystretch** [comment]
Thank you for submitting this issue, however it appears that this topic has already been raised. Please see issue #5627 for further discussion.
