### ISSUE TITLE
Device type compontent creation forms do not render

### ISSUE THREAD

**Issue by jeremystretch** [netbox-community/netbox#6714]
### NetBox version

v2.11.8

### Python version

3.7

### Steps to Reproduce

1. Create a device type
2. Attempt to add any type of component (e.g. interface) to a device type

### Expected Behavior

The complete component creation form should render.

### Observed Behavior

The page renders, however the form is empty.

This is due to a bug in the template which attempts to iterate through `form.custom_fields`. For device type components, `custom_fields` is not set. (The exception being raised is apparently swallowed within the template rendering, so our tests never caught it.)

**Comment by mabroze** [comment]
Confirmed fixed in 2.11.9. Thanks for the quick resolution and your commitment to NetBox in general @jeremystretch @candlerb. Hope I'll be able to contribute in a meaningful way myself in the future.
