### ISSUE TITLE
Rights for journy on device

### ISSUE THREAD

**Issue by pboatone** [netbox-community/netbox#6729]
### NetBox version

v.2.11.9

### Feature type

New functionality

### Proposed functionality

Admins allow users to add journies on a device, but not allow users to manage the entire device

### Use case

Not every user can edit a device but can add information to this device. Here the support should add information about the device but not change anything

**Comment by tb-killa** [comment]
Thats something we need too.

**Comment by jeremystretch** [comment]
This is already supported at least on NetBox v3.0.
