### ISSUE TITLE
Improve two minor UI inconsistencies related to Virtual Interfaces

### ISSUE THREAD

**Issue by mabroze** [netbox-community/netbox#6740]
### NetBox version

v2.11.9

### Feature type

New functionality

### Proposed functionality

These are little more than cosmetic inconsistencies, but at the same time I reckon they are easy to fix.

### Inconsistency 1
As far as I can tell, the only was to add an Interface to a VM is by opening the VM and clicking Add Interfaces. However, if manually entering the URL /virtualization/interfaces/add/ takes you to a page that lets you add an interface on an arbitrary VM. I propose
- Adding an Add button for Virtual Interfaces to the menu (Virtualization, behind Interfaces)
- Adding an Add button to the Virtual Interfaces page (/virtualization/interfaces/)
The target for both buttons would be the URL mentioned above.

### Inconsistency 2
Currently it is possible to import Virtual Interfaces via the menu (Virtualization, Import icon behind Interfaces). However, if you go to the Virtual Interfaces page (/virtualization/interfaces/) there is no Import button. I propose adding such a button and have it link to the same target as the menu does (/virtualization/interfaces/import/).

### Use case

Slight improvement to the overall logic and structure of the UI.

### Database changes

None

### External dependencies

None

**Comment by DanSheps** [comment]
We are going to pass on #1, there is no add button for DCIM interfaces page either.

#2 we can look at
