### ISSUE TITLE
Ability to add Resources for Devices

### ISSUE THREAD

**Issue by ValentinPifu** [netbox-community/netbox#6743]
### NetBox version

v2.11.8-dev

### Feature type

Data model extension

### Proposed functionality

It'll be nice to be able to add Resources Section for the Devices, same section like it's on Virtual Machine Tab with Resources. (no custom fields)

Resources:
   CPU:
   Memory:
   Disk Space:

![Screenshot from 2021-07-12 09-06-30](https://user-images.githubusercontent.com/18114871/125239087-d3e59900-e2f0-11eb-9a0d-56926590fdb5.png)

### Use case

On our environment we have some servers, we added manually every physical server but we don't have a field to add how many ram, disk space, process they have. 
It's a feature to see all details more easier.

**Comment by DanSheps** [comment]
I think this is best suited for the "Inventory" section which is already on devices.

We most likely will not add this to the base model as some devices don't always have easily tracked resources (switches, etc).  This doesn't suit a base model.
