### ISSUE TITLE
Fibre Splice Visualisation

### ISSUE THREAD

**Issue by avidpontoon** [netbox-community/netbox#6756]
### NetBox version

v2.11.9

### Feature type

New functionality

### Proposed functionality

Visualisation of a fibre splice point. Currently this is doesn’t appear to be possible.

See attached photo.

in location A there is a fibre panel, with 4 front ports mapped to a single rear port with 4 positions. In locations B and C the fibre panels have 2 front ports mapped to single rear ports with 2 positions. Hence the 8 core fibre and and 4 core fibre (all multimode).

In my example, an 8 core splits into two 4 cores.

I originally created a splice ‘device’ and used a single rear port with 4 positions and connected that to rear port on panel A. Then created two front ports and attached them to their respected positions on the rear port. These were then connected to the rear ports on Panels B and C. However, when front ports on each panel were connected to switchports on each end, a trace says ‘split path’ as the front ports on the splice don’t have multiple positions like the rear ports do, meaning they are merged into one and so fibre using cores are merged too. So netbox can’t tell which front port on the remote fibre panel. 

There may be another way to do it unless I’m missing something.

I suppose this could be achieved by allowing a front port to be mapped to a couple of rear ports to allow the ‘positions’ to pass through and make a successful trace.

![85F42B2B-9283-4F88-B537-4384D88F0591](https://user-images.githubusercontent.com/37943903/125703111-b134107c-84cf-4b1a-8753-4e35c0ae0150.jpeg)

### Use case

Allow modelling of fibre splices

### Database changes

Unsure 

### External dependencies

N/A

**Comment by sleepinggenius2** [comment]
The way I've handled this is to create a splice case device and then:
* Create a rear port _A_ with 8 positions
* Create 8 front ports _A-[1-8]_ mapped to rear port _A_
* Create a rear port _B_ with 4 positions
* Create 4 front ports _B-[1-4]_ mapped to rear port _B_
* Create a rear port _C_ with 4 positions
* Create 4 front ports _C-[1-4]_ mapped to rear port _C_
* Create 4 cables connecting front ports _A-[1-4]_ to front ports _B-[1-4]_
* Create 4 cables connecting front ports _A-[5-8]_ to front ports _C-[1-4]_

It can be a little tedious with something like 144F fiber cables, but using imports has worked pretty well for me.

**Comment by jeremystretch** [comment]
The approach recommended by @sleepinggenius2 is pretty much the way to go. There are no shortcuts, unfortunately, but you can automate this a great deal using device types and custom scripts.
