### ISSUE TITLE
nl2br for comments field

### ISSUE THREAD

**Issue by christopheg** [netbox-community/netbox#6762]
### NetBox version

v2.11.6

### Feature type

Change to existing functionality

### Proposed functionality

The 'comments' field in a virtual machine should reflect the input. 
When filling in comments with newlines, they don't appear in the interface.
The newlines should be replaced by <br> tags 

### Use case

better readable documentation

**Comment by jeremystretch** [comment]
This is a function of Markdown. Ending a line with two trailing spaces will force a line break.
