### ISSUE TITLE
Add Interfaces to Global Search

### ISSUE THREAD

**Issue by darcynz** [netbox-community/netbox#6765]
### NetBox version

v2.11.7

### Feature type

New functionality

### Proposed functionality

When searching via the global search interface data is returned. 

### Use case

Similar to #6200 would like it so that Interface data particularly the description is seachable via the global search. 

We find ourselves having to do an extra search looking for this data, or at times it is overlooked.

**Comment by jeremystretch** [comment]
Thank you for submitting this issue, however it appears that this topic has already been raised. Please see issue #4757 for further discussion.
