### ISSUE TITLE
Filtering on null values for rack group filed

### ISSUE THREAD

**Issue by Begriche** [netbox-community/netbox#6768]
### NetBox version

v2.9.8

### Python version

3.8

### Steps to Reproduce

1. Attempt to filter the racks list by null group value:
``` https://netbox/dcim/racks/?group_id=null ```
or
``` https://netbox/dcim/racks/?group=null ``` 

### Expected Behavior

Only racks that that are not part of a rack group (i.e group: null)

### Observed Behavior

the filter is broken
racks with null group filed are not showed, and only some rack with non-null rack group are showed (3 of 83 in my case)

**Comment by jeremystretch** [comment]
> v2.9.8

I'm afraid your NetBox release is very out of date. We only accept bug reports for the latest stable release (which is currently v2.11.9.) I suspect you'll find that this bug has been addressed in a newer release. (In fact, rack groups have been renamed to locations in v2.11, so the filter itself is different now.)
