### ISSUE TITLE
Be able to see inventoried items from manufactures view

### ISSUE THREAD

**Issue by markd69** [netbox-community/netbox#6771]
### NetBox version

v2.11.9

### Feature type

New functionality

### Proposed functionality

Being able to view the inventoried items or even platforms via the manufacturer's page would be great. Currently, it only shows the devices using that manufacture. I don't see why it couldn't show inventoried items as well.
![image](https://user-images.githubusercontent.com/44349634/126245386-9445dbf3-9511-4ec9-bbc5-cccbbf2d998b.png)
manufacturer's

### Use case

Quickly and easily sort inventoried items by the manufacture.

**Comment by jeremystretch** [comment]
I'll add a count of applicable inventory items with a link to the filtered list. Adding the whole table directly within the manufacturer view might be a bit much. (We can re-evaluate adding it as a separate tab under v3.0.)
