### ISSUE TITLE
Issue when swapping circuit Terminations

### ISSUE THREAD

**Issue by BeArchiTek** [netbox-community/netbox#6774]
### NetBox version

v2.11.9

### Python version

3.8

### Steps to Reproduce

Test: https://demo.netbox.dev/circuits/circuits/10/

1. Add a new circuit
2. Add a new A termination
3. Add a new Z termination
4. Swap the 2 terminations

### Expected Behavior

A and Z Terminations are swapped

### Observed Behavior

A Termination doesn't change
Z Termination is override to be A

Ps : if you deleted A or Z Termination, the other one is deleted

**Comment by jeremystretch** [comment]
Looks like another caching bug. Have you tried disabling caching?

**Comment by BeArchiTek** [comment]
Hello Jeremy,

I doesn't have a working 2.11.9 except the demo at the moment, so can't deactivate the cache on it.

As the default one is 15 minutes, I checked back on the demo 30 minutes after doing the change and the entry is still duplicate.

Regards,

**Comment by jeremystretch** [comment]
In that case, please update your post above to prescribe the exact set of steps someone else can follow to reproduce the reported behavior with caching disabled, and without relying on data in the demo instance.

**Comment by jeremystretch** [comment]
Looks like this and #6775 are the same issue.

**Comment by BeArchiTek** [comment]
Hello,

Edited.

Regards,
