### ISSUE TITLE
PR #6641 breaks text custom field default value

### ISSUE THREAD

**Issue by bmhughes** [netbox-community/netbox#6777]
### NetBox version

v2.11.9

### Python version

3.9

### Steps to Reproduce

1. Create a custom text type field.
2. Try to set a default value.

### Expected Behavior

Default value should be set.

### Observed Behavior

`ValidationError` is raised because `.validate` for a text field tests against `str` when the field is a `django.forms.fields.JSONString`, trying to set a `str` value causes a `Enter a valid JSON.` error.

**Comment by jeremystretch** [comment]
Linking this to #6641
