### ISSUE TITLE
Custom link in table view

### ISSUE THREAD

**Issue by stevenmyhre** [netbox-community/netbox#6782]
### NetBox version

2.11.9

### Feature type

Change to existing functionality

### Proposed functionality

Custom links as available columns to add to the table view of IP Addresses.

### Use case

I have a custom link set up on each ip address that links to the http://{{ obj.address[0] }} browser page. This makes it easy to get the router login page / web site etc with a simple click. It would be nice, just as with the custom fields, you could add a custom link as a **column** to the table view of ip addresses. That way you can click on the link without having to open the object itself. I can see many other uses for links in columns like this... integrating with external websites / other IPAM sites etc.

### Database changes

None that I can see

**Comment by jeremystretch** [comment]
Blocked by #6817. Once we figure that out, we can take this on.

**Comment by jeremystretch** [comment]
Fixed #6817 :slightly_smiling_face:
