### ISSUE TITLE
Connections (cables) - disconnect and reconnect issue

### ISSUE THREAD

**Issue by michalceb** [netbox-community/netbox#6783]
### NetBox version

v2.11.9

### Python version

3.8

### Steps to Reproduce

1. Disconnect circuit or cable from the devices' interface
2. Attempt to re-connect circuit or cable back to the same interface of the device

Notes:
Initially I have tested just with device and circuit termination, however, this also appears to be affecting interface to interface connections.
This was tested on my own Netbox instance, as well as, demo instance.

Workaround:
Restart of netbox services resolves the issue for the affected interfaces.

### Expected Behavior

Circuit or cable should re-connect with no issues.

### Observed Behavior

<class 'dcim.models.cables.Cable.DoesNotExist'>

Cable matching query does not exist.

Python version: 3.8.10
NetBox version: 2.11.9

**Comment by dteknet** [comment]
Please look at #6747

**Comment by michalceb** [comment]
Thanks for that.
Don't know why it hasn't occured to me to check closed bug reports.
