### ISSUE TITLE
Add the choice for AC Direct Wire for power types

### ISSUE THREAD

**Issue by bellwood** [netbox-community/netbox#6785]
### NetBox version

v2.11.9

### Feature type

Change to existing functionality

### Proposed functionality

Add the ability to choose `AC Direct Wire` to power types, similar to `DC Terminal`.

This would be a simple adder to `netbox/dcim/choices.py`

### Use case

Not all devices are connectorized coming off power panels and indicating an end device is directly wired is currently not possible. 

A simply example would be a UPS output breaker wired to a power panel input breaker and then further wired to a PDU input breaker (which would all be direct wired) or a power panel wired to a control panel, annunciator panel, etc.

### Database changes

None

### External dependencies

None

**Comment by jeremystretch** [comment]
I could swear this came up in conversation under a previous issue, but I can't find it now.

At any rate, I think it makes sense.
