### ISSUE TITLE
Device name missing from Device Status tab

### ISSUE THREAD

**Issue by falz** [netbox-community/netbox#6794]
### NetBox version

2.11.9

### Python version

3.6

### Steps to Reproduce

Cosmetic issue.

1. Navigate to or create a device in netbox, ensure it's set to Active.
2. choose Status tab (dcim/devices/ID/status/)
3. witness lack of device name, instead of "DEVICE - Status" it just says " - Status"

![Screenshot from 2021-07-23 07-31-24](https://user-images.githubusercontent.com/707319/126782487-38b98e4a-79c0-4cca-962d-f2395d437515.png)

### Expected Behavior

Device hostname should exist in title area of device status page

### Observed Behavior

No hostname listed on device status page

**Comment by romanstech** [comment]
v.2.11.2 — the same issue confirmed.
