### ISSUE TITLE
Cable trace causes server error

### ISSUE THREAD

**Issue by uow-dmurrell** [netbox-community/netbox#6796]
### NetBox version

v3.0-beta1

### Python version

3.8

### Steps to Reproduce

1. Go to https://beta-demo.netbox.dev/dcim/devices/10/interfaces/
2. Click on the blue trace button for cable  `54 dmi01-stamford-sw01  GigabitEthernet1/0/1`, 
Or the link that the trace button links to: https://beta-demo.netbox.dev/dcim/interfaces/120/trace/

Its worth noting that trace 121 also gives this error.

### Expected Behavior

A cable trace should have been seen like the one at this URL: https://beta-demo.netbox.dev/dcim/interfaces/118/trace/

### Observed Behavior

![image](https://user-images.githubusercontent.com/863147/126787674-e9e6a088-80a3-4af6-9e8e-c579c7a1f0f0.png)

```
<class 'KeyError'>

53


Python version: 3.8.10
NetBox version: 3.0-beta1
```

**Comment by jeremystretch** [comment]
This is a problem with the static data being used to populate the demo instance on rebuild. Looks like the cable paths were inadvertently included with the data when they should have been omitted, resulting in incorrect content type references. I'll fix up the demo data, but no work is needed on NetBox itself to fix this.
