### ISSUE TITLE
Add ability to search for Labels and Description in global search

### ISSUE THREAD

**Issue by Razerlikes** [netbox-community/netbox#6798]
### NetBox version

v2.11.7

### Feature type

Change to existing functionality

### Proposed functionality

Functionality for the global search:
Add the ability to search for fields like "Label and Description" on interfaces and ports in the global search function. 

### Use case

This feature would help to quickly find ports on patch panels by the Label/Description value.

Currently, if we want to find a front port of a patch panel by label, we have to go over the device components view

**Comment by jeremystretch** [comment]
Global search does not support device components. Please see #4757 for further discussion.
