### ISSUE TITLE
v3.0 beta - menu enhancement request

### ISSUE THREAD

**Issue by tomaskir** [netbox-community/netbox#6800]
### NetBox version

3.0

### Feature type

New functionality

### Proposed functionality

Menu should not close each time you change a view. It makes navigation a bit tedious. For example, when in the `Racks` view (and its subviews), keep the `Organization` section of the menu should stay extended.

### Use case

Menu in 2.11 has no animations (faster navigation) and the menus groups being horizontally side-by-side makes visually identifying where things are faster -  building "visual memory" for where to click to get to a particular view is quite easy due to the static positioning and each element having unique position is easier.

In 3.0, due to animations and everything being in the same vertical menu (with dynamic position due to scroll), it means you consciously have to identify where you want to click, scroll to the position, etc. As most workflows usually happen within a menu group, having it extended when you are in a view inside that menu group would help with that.

**Comment by PieterL75** [comment]
I'm not a fan of the new side menu either... Those to dropdown menu have a much faster to navigate and don't mess a round with the position you have to click...
The side menu also takes up space. Most output are tables, where we need the full width of the screen to display..

**Comment by binaryoverload** [comment]
I do like the new menu but I do agree that it does take up a fair bit of space. Perhaps a good solution to this is to make the sidebar collapsible 🤔

**Comment by jeremystretch** [comment]
The tricky part is passing state to the menu, to know which section (if any) should be expanded. We actually did this in much older versions of NetBox to highlight the "active" menu button, but decided it wasn't worth the effort to keep up. I'd like to come up with something a bit more clever than manually specifying the active menu section under each view.

> I'm not a fan of the new side menu either...

FWIW I ran a very informal [Twitter poll](https://twitter.com/jstretch85/status/1412743433681313792) where people preferred a sidebar to a top menu roughly 2:1. I imagine it will start to feel more familiar after a bit of use.

**Comment by thatmattlove** [comment]
FYI, this is fixed as of 3752cb3. The nav menu is now collapsible and determines the state of the current page and highlights the appropriate menu item accordingly.

**Comment by PieterL75** [comment]
What I don't like about sidebars, is that menu Items get dropped off the screen.
If you open 'device's, then you have to close it again before you can go to 'other/reports'.
No, this is not an improvement. 

Navigation has to be quick without extra clicks to find your way

I can understand that the sidebar remains, but that the submenu pops out to the right, as it poped out to the bottom with the top menu. Then the navigation will be more slick

Pieter
