### ISSUE TITLE
Server Error Editing Users - v3.0-beta1

### ISSUE THREAD

**Issue by online-stuff** [netbox-community/netbox#6811]
### NetBox version

v3.0-beta1

### Python version

3.8

### Steps to Reproduce

https://beta-demo.netbox.dev/admin/

Click +Add to the right of "Users"

Enter a username and a password twice,

Click  "Save and Continue Editing"

If you 'Save and Add Another' there is no error but if you try and edit the user, from the list of users, you will get the same error.

### Expected Behavior

A user should have been created without the error message.

I user does get created anyways but you can't edit it.

### Observed Behavior

Server Error

There was a problem with your request. Please contact an administrator.

The complete exception is provided below:

<class 'AttributeError'>

'QuerySet' object has no attribute 'nocache'

Python version: 3.8.10
NetBox version: 3.0-beta1

If further assistance is required, please post to the NetBox mailing list.
Home Page

**Comment by jeremystretch** [comment]
Looks like a remnant of queryset caching that we missed.
