### ISSUE TITLE
Utilization can push up to 200%

### ISSUE THREAD

**Issue by c-po** [netbox-community/netbox#6812]
### NetBox version

v2.11.9

### Python version

3.6

### Steps to Reproduce

1. Create a new prefix `192.0.2.0/30`
2. Import IP addresses via https://<netbox>/ipam/ip-addresses/import/
```
address
192.0.2.0/30
192.0.2.1/30
192.0.2.2/30
192.0.2.3/30
```

### Expected Behavior

An error should be raised as 192.0.2.0/30 and 192.0.2.3/30 are no host addresses

### Observed Behavior

![image](https://user-images.githubusercontent.com/25299219/126975120-05b0549a-85f4-42b6-bc3f-cd998c8f1ef3.png)

![image](https://user-images.githubusercontent.com/25299219/126975144-e0dbd4d1-8175-45c3-826a-5a179b287a33.png)

**Comment by sdktr** [comment]
I don't think we should block the creation of these (subnet/broadcast) IP's. The creation of them might very well be intended to do just that: reflect how the IP's are behaving. Nice excercise for the [new 'CustomValidator' hooks](https://github.com/netbox-community/netbox/issues/5963) :-) 

A utilization above 100% does seem odd as well though. Maybe we could put an artificial limit on that number to cap it at 100?

**Comment by jeremystretch** [comment]
Capping it at 100% seems like the way to go.

**Comment by c-po** [comment]
@sdktr and @jeremystretch I agree that capping would also be a viable option if one want's to document those IP addresses.

What happens if the network and broadcast address is documented but two host addresses are still free? Will it show 100%, too? 

Network and Broadcast addresses can be calculated, so I think the most effective way would be to not take them into account when calculating the host address usage in percent.
