### ISSUE TITLE
Allow Multiple Sites per Prefix

### ISSUE THREAD

**Issue by online-stuff** [netbox-community/netbox#6815]
### NetBox version

v2.11.9

### Feature type

Data model extension

### Proposed functionality

Add the ability to assign a multiple sites to a prefix.

### Use case

Prefixes can be used across current boundaries, an example is PtP links.

Prefix - 192.0.2.32/30
SiteA - 192.0.2.33/30
SiteB - 192.0.2.34/30

Prefix - 192.0.2.36/30
SiteA - 192.0.2.37/30
SiteC - 192.0.2.38/30

SiteA - 198.51.100.0/24
SiteB - 203.0.113.0/24

SiteA's router routes traffic for 203.0.113.0/24 to 192.0.2.34. SiteB's router routes traffic for 198.51.100.0/24 to 192.0.2.33.

The prefix is used at both SiteA and SiteB, so should be able to document it.

### Database changes

Not sure on this one..  More UI interface allowing the field multiple times and displaying it when looking at the UI or reports for either 'site'.

**Comment by jeremystretch** [comment]
Seems like this would be covered by #6414. What do you think?

**Comment by online-stuff** [comment]
> 
> 
> Seems like this would be covered by #6414. What do you think?

Similar yes, sorry I missed that with my searching...  I started by trying to figure out how NetBox wanted me to document it.

From [](https://github.com/netbox-community/netbox/issues/6414) I am not convinced that a site-group is the best way..  If someone does a mesh, every combination of sites may need to be created.
