### ISSUE TITLE
Visual bug. After edited or deleted custom field, bulk create and edit will keep the custom field in display field (not attribute)

### ISSUE THREAD

**Issue by jk-onnet** [netbox-community/netbox#6817]
### NetBox version

v2.11.7 (tested on demo instance too)

### Python version

3.9

### Steps to Reproduce

1. Add custom field "vmid" in virtualization (admin)
2. Edit custom field "vmid" name in virtualization (admin)
3. Add custom field "core" name in virtualization (admin)
4. Delete custom field "core" name in virtualization (admin)
5. Bulk edit or delete in virtualization page

### Expected Behavior

![image](https://user-images.githubusercontent.com/85537520/127088207-cec395d2-0738-4487-bb86-934edf569e65.png)

### Observed Behavior

![image](https://user-images.githubusercontent.com/85537520/127088237-3d230d43-6179-4616-92de-5844429271cb.png)

**Comment by opericgithub** [comment]
#7310 might be similar to this, but not quite same. anyway, i hope this issue will be resolved sometime soon.
