### ISSUE TITLE
Interface (device + vm) mtu is limited to 32767

### ISSUE THREAD

**Issue by julianze** [netbox-community/netbox#6822]
### NetBox version

v2.11.9

### Python version

3.7

### Steps to Reproduce

1. create a device or vm
2. Add a new (vm) interface and set mtu higher than 32767, i.e. 65536 for linux loopback interface

### Expected Behavior

Interface should be creatable with mtu sizes to 65536.
In #2354 the range has been extended to 65536 but this isn't possible anymore

### Observed Behavior

There is an error: "Ensure this value is less than or equal to 32767."

**Comment by candlerb** [comment]
Aside: `INTERFACE_MTU_MIN = 1` is lower than it should be for useful validation.

For IPv4: in 1981, the minimum MTU was technically 68 (RFC791).  Every host had to be prepared to accept IP datagrams of at least 576 bytes, but they could be received in fragments.  However in the intervening time, it has been common practice to assume a minimum MTU of 576, and I think 576 would be a reasonable minimum for Netbox to enforce.

(For IPv6, the minimum MTU is 1280).
