### ISSUE TITLE
Duplex interface to double simplex front port

### ISSUE THREAD

**Issue by chesronw** [netbox-community/netbox#6824]
### NetBox version

2.11.9

### Feature type

New functionality

### Proposed functionality

Hi,

We would like to see if there is an option where you can have one fiber patch panel that you can use for simplex and for duplex fiber. 

In this case, we are able to connect the interface with a simplex SFP module (Bidirectional SFP) to a "duplex" patch panel on a specific fiber X instead of a fiber pair.

**Duplex vs Simplex**
![image](https://user-images.githubusercontent.com/85490348/127165814-16c7c2c1-10e2-47c5-a11c-06086ae94f98.png)

I can imagine that this request is not fully clear. 
Please let me know if you don't fully understand. 

Or maybe it is already possible :) 

### Use case

Let's say we have a normal switch at side A that we connect with a duplex SFP LC via a fiber patch panel
_(This fiber panel is 24 duplex-LC so we have 48 single fibers (simplex) )_ to the side Z where we have also a switch. 

Still not a problem.  until we like to connect a device with a simplex SFP module. 
In this case, we can currently only connect this simplex to a duplex front panel. 

So instead of define 1 front port, we need to define 2 ports in case of a duplex interface to that patch panel. 
When we are using a simplex interface we got only the option to connect with 1 front port X.

I was also thinking on the interface side. 
Maybe we need to define the kind of interface. So you can choose between simplex or duplex interface where we later can define when we connect an interface to a front port to define 2 front ports (X1 and X2 for example)  and in case of the simplex where you only need to define one front port  (X3 for example)

![image](https://user-images.githubusercontent.com/85490348/127165088-3d3457c6-cfe5-4ae0-b0b0-94b285dddfa4.png)

![image](https://user-images.githubusercontent.com/85490348/127164853-95820ae6-a4d8-412c-a303-ac83e81c199e.png)

**Comment by DanSheps** [comment]
I would like to do this at some point, I have a working workaround in my local production instance.

**Comment by chesronw** [comment]
Hi Daniel,

indeed that is a constraint.
In this case, you also going to miss the IP Interface to define the IP address / Management address of a device.

Do you also agree that when we add an extra value to the interface template or where you can choose another type of interface to a simplex or duplex. After this is done we can pick this value to determine if we need one or two front ports to select when we connect an interface to a front port.

**Comment by DanSheps** [comment]
If we decide to take this up, design decisions will be at a later date as far as how to link it to netbox.

**Comment by chesronw** [comment]
Alright, I will wait. 
The last thing a want to say is that in the future you see more and more Bi-Directional SFPs.
This request will also help to work with normal SFP and the BIDI SFPs. 

![image](https://user-images.githubusercontent.com/85490348/127173577-97d21e71-bf13-4f80-b0ba-dc22da2c33be.png)

**Comment by ziply-nick** [comment]
This is a feature that would be highly desirable for all of the implementations I have ever used Netbox in (ISPs, datacenters, etc). I hope we can get this feature implemented.

**Comment by jalmargyyk** [comment]
Is there a workaround for this? I'm really struggling to come up with a proper workaround, since we are extensively using MPO/MTP cassettes, LX and BX optics. I have currently modelled cassettes with two rear ports and each rear port having 12 positions. Then mapping front ports (one port as one fibre in MPO/MTP cable) to rear port and position.

e.g. Front port 1 corresponds to rear port 1, position, front port 13 corresponds to rear port 2, position 1 and so on. 

There's currently no way of mapping two of those fibres to one device interface. It would be really helpful to get support for interface to terminate one or two fibres to it.
