### ISSUE TITLE
v3.0-beta1 mobile UI tweaks

### ISSUE THREAD

**Issue by jeremystretch** [netbox-community/netbox#6828]
### Proposed Changes

This issue serves to track small fixes to the mobile UI in the upcoming version 3.0 release that aren't big enough to justify individual bug reports. Please comment below with any issues you encounter within the mobile UI and we'll add it here.

For desktop UI issues, please see #6797.

- [x] Nav menu scrolling is broken on iOS (@Razerlikes)

### Justification

To improve the mobile UI in preparation for the upcoming NetBox v3.0 release.

**Comment by Razerlikes** [comment]
In the mobile version of the Beta UI, when you try to scroll in the dropdown-menu when there is nothing to scroll or you don't hit a scrollable list by accident, the banner is moving with the pull. That is unexpected behaviour. Example in the video

Found in iOS 14.7


https://user-images.githubusercontent.com/6794999/127382197-d3de4503-5307-4f7f-b940-d70f0e843236.mov

**Comment by bellwood** [comment]
On iPad Air 3rd Gen, Safari:

-Start in portrait mode
-Load the page and scroll down, you can briefly see the footer (links and build detail) the page slightly bounces up, the footer disappears
-Scroll to the top, you get an additional scroll bar above the search bar and login
-Scroll back down and the footer is gone

-Go to landscape mode, does not exhibit this

-Go back to portrait mode, you can no longer scroll down at all

There is considerable lag in the redraws when rotating the viewport, unclear if there is an overburden of css transitions being used?

Side note, thank you for the collapsing sidebar, makes iPad/mobile usage much friendlier.

**Comment by thatmattlove** [comment]
> On iPad Air 3rd Gen, Safari:
> 
> 
> 
> -Start in portrait mode
> 
> -Load the page and scroll down, you can briefly see the footer (links and build detail) the page slightly bounces up, the footer disappears
> 
> -Scroll to the top, you get an additional scroll bar above the search bar and login
> 
> -Scroll back down and the footer is gone
> 
> 
> 
> -Go to landscape mode, does not exhibit this
> 
> 
> 
> -Go back to portrait mode, you can no longer scroll down at all
> 
> 
> 
> There is considerable lag in the redraws when rotating the viewport, unclear if there is an overburden of css transitions being used?
> 
> 
> 
> Side note, thank you for the collapsing sidebar, makes iPad/mobile usage much friendlier.

Are you doing these tests on the public beta demo, or locally? If public demo, please try again. Not all the changes I pushed up yesterday made it into the nightly build, but they're there now.

**Comment by bellwood** [comment]
@thatmattlove Public demo, I will re-visit and follow up, thanks.

**Comment by Razerlikes** [comment]
> 
> 
> In the mobile version of the Beta UI, when you try to scroll in the dropdown-menu when there is nothing to scroll or you don't hit a scrollable list by accident, the banner is moving with the pull. That is unexpected behaviour. Example in the video
> 
> Found in iOS 14.7
> 127347163-603e877a-c938-4e67-865f-e85916de7889.mov

This issue seems fixed with the new mobile sidebar in the current version of the UI. Thanks @thatmattlove

**Comment by bellwood** [comment]
@thatmattlove Everything looks OK sans I still get a scroll bar above the hamburger.

I do occasionally get delays in my ability to scroll down and if I wait a second or two, I'm then able to. 

Unsure if this is a transition issue or a DOM issue with the front end?

It's less noticeable than when I first reported, but still present.

**Comment by thatmattlove** [comment]
Closing this out. I think mobile layouts are now at a reasonable enough state to collapse future issues into #6797, and individual issues after #6797 is closed.
