### ISSUE TITLE
GraphQL support for reverse generic relationships

### ISSUE THREAD

**Issue by ryanmerolle** [netbox-community/netbox#6829]
### NetBox version

v3.0-beta1

### Feature type

Change to existing functionality

### Proposed functionality

It looks like `ForeignKey` relationship are automatically handled in the NetBox implementation of graphql, but any relationship via a `GenericForeignKey` is not created.

From browsing the code I think the following use `GenericForeignKey` relationships:

- [x] ~Cable - termination_a & termination_b~ - Available via the `cable` ForeignKey on termination models
- [ ] ~CablePath - origin & destination~ - We don't currently support cable paths in the GraphQL API, nor do we link to paths directly in the REST API. Probably needs more discussion.
- [x] ~CableTermination - _cable_peer~ - This is accessible as a forward relation from opposite ends of the cable
- [x] ObjectChange - changed_object & related_object
- [x] IPAddress - assigned_object
- [x] ImageAttachment - parent
- [x] JournalEntry - assigned_object
- [x] VLANGroup - scope

### Use case

This would be needed if we truly want to leverage graphql queries to tie separated but related models together.  For example, we cannot currently tie circuit information or ipam data to a device's interfaces.

### Database changes

None

### External dependencies

None

**Comment by jeremystretch** [comment]
This is a great opportunity for some GraphQL power users to get involved with its development in NetBox.

**Comment by jeremystretch** [comment]
I've addressed everything but the cable path item in #6873. (That one probably deserves a deeper discussion as it relates to parity with the REST API.)

**Comment by ryanmerolle** [comment]
Thanks.  I will test and revert if anything.
