### ISSUE TITLE
Renaming custom field does values in UI (yet shows correctly via API)

### ISSUE THREAD

**Issue by ossicoinc** [netbox-community/netbox#6831]
### NetBox version

v2.11.10

### Python version

3.9

### Steps to Reproduce

1. Add custom field to type (I chose VRF item type)
2. Add new item (VRF) with data in the custom field, Save
3. Go back to custom fields and rename the field
4. Go to site and view the VRF

### Expected Behavior

I would expect the data from the renamed field to be shown.

### Observed Behavior

The data is shown as "--"
However, when querying via the API the custom field is renamed and the data is intact.

I have also observed when querying the API that the custom_field is renamed, but if I apply a "tenant=xxxx" filter to the api request, the field is empty:

http://10.132.6.96:8080/api/ipam/vrfs/?name=MY%20VRF

My workaround is to:

1. Add a new object of same time, with a custom field filled in.
2. Run a search with an exact match on a custom field for a record you know.
2. Open the original record, and custom field magically is back to being populated in the UI.

I believe this is probably a caching/db index issue.

**Comment by bellwood** [comment]
> I believe this is probably a caching/db index issue.

If you disable caching in configuration.py, `CACHE_TIMEOUT = 0` does this issue still occur?

**Comment by jeremystretch** [comment]
I'm not able to reproduce this on v2.11.11 when caching is disabled. Definitely seems like a caching bug.
