### ISSUE TITLE
GraphQL: rendered config_context not available on device/VM level

### ISSUE THREAD

**Issue by sdktr** [netbox-community/netbox#6832]
### NetBox version

v3.0-beta1

### Python version

3.8

### Steps to Reproduce

1. Open GraphiQL
2. Fetch a single device [(example query)](https://beta-demo.netbox.dev/graphql/#query=query%0A%7B%0A%20%20device(id%3A%206)%20%7B%0A%20%20%20%20name%0A%20%20%20%20custom_fields%0A%20%20%20%20custom_field_data%0A%20%20%7D%0A%7D%0A)
3. Try to get the rendered config context for the device

### Expected Behavior

The GQL schema presents an attribute that will fetch the rendered config context. No such attribute is found on the generated graphQL schema.

### Observed Behavior

No attribute is available. Note: local_config_context is a directly assigned/attached attribute, but this is not the rendered config_context as present in the REST API.

**Comment by sdktr** [comment]
possible related to https://github.com/netbox-community/netbox/issues/6829 ([slack comment ](https://netdev-community.slack.com/archives/C01P0FRSXRV/p1627504469377200?thread_ts=1627490461.364700&cid=C01P0FRSXRV)from @ryanmerolle )

**Comment by ryanmerolle** [comment]
Yea not being auto rendered, just have to see why.  Issue #6829 is because those items are GenericForeignKeys.  This is not.

**Comment by ryanmerolle** [comment]
This is what the beta is for.  

Thanks for identifying this issue @sdktr.  Please keep hitting the graphql feature and help us identify any more issues before a stable release is cut.  I will be doing the same.
