### ISSUE TITLE
Page title + favicon in API pages

### ISSUE THREAD

**Issue by sdktr** [netbox-community/netbox#6834]
### NetBox version

v3.0-beta1

### Feature type

Change to existing functionality

### Proposed functionality

Add a favicon to both GraphiQL workspace and REST API. Plus add a page title to the GraphiQL playground.

### Use case

When testing Netbox API calls the tabs in a browser do not stand out very recognizable. The page title for the REST API pages reflects the path one is on. The GraphiQL playground has no title so it renders the full query URL in the tab title.

### Database changes

N/A

### External dependencies

N/A

**Comment by jeremystretch** [comment]
@sdktr want to try taking this on? I'm not really sure how involved it would be.

**Comment by jeremystretch** [comment]
While we're at it we should see if it's feasible to serve the GraphiQL UI's static resources locally (as opposed to via a CDN), to better support isolated NetBox deployments.

**Comment by kkthxbye-code** [comment]
@jeremystretch - I'm not sure there is a clean solution for that other than creating a pull request for graphene-django or forking it. Maybe it's possible to overwrite the path to the template and having a local version with the changes (local resources, favicon and title). 

https://github.com/graphql-python/graphene-django/blob/e7f7d8da07ba1020f9916153f17e97b0ec037712/graphene_django/views.py#L58

But that's a very hackish solution.

**Comment by jeremystretch** [comment]
We're already [subclassing the stock GraphQLView](https://github.com/netbox-community/netbox/blob/22d160b1da32e46399a5cd20858b34c9ea4ffa2d/netbox/netbox/graphql/views.py#L11), so it should be pretty easy to swap in our own template. The [template](https://github.com/graphql-python/graphene-django/blob/main/graphene_django/templates/graphene/graphiql.html) actually looks pretty minimal; should be easy to tweak. We just need to ensure we keep resources in sync for future releases; that will be the more tricky part.

**Comment by jeremystretch** [comment]
Ok, I've got the title and favicon sorted in #6847, and we should be able to bundle the necessary static resources using our existing workflow. Just need to sync with @thatmattlove to confirm.

**Comment by jeremystretch** [comment]
#6847 addressed the original issues above. I've opened #6855 to cover serving GraphiQL's static assets locally.
