### ISSUE TITLE
Display field's data as name instead of the numeric value in Change Log

### ISSUE THREAD

**Issue by michalceb** [netbox-community/netbox#6837]
### NetBox version

v2.11.9

### Feature type

Change to existing functionality

### Proposed functionality

Currently in the Change Log, data of certain fields (such as Device's Site, Tenant, Platform, Device Role, or Circuit's Type and Provider) is displayed in the form of their numeric values.

![Screenshot 2021-07-29 094852](https://user-images.githubusercontent.com/67379333/127462122-e5b8ee6b-fa23-4b97-b06c-432d621e16e0.png)

Not sure if this would be difficult to implement, however, I am proposing that these values should be displayed as their name instead.

### Use case

Scrolling through changes in the log just now in attempt to (for example) find out where device was installed previously (which site or tenant), or what was circuit's A or Z end before it was decomissoned and disconnected is quite difficult. 
It is possible to navigate to Sites section of Netbox and add the numeric value to end of the borwsers URL, which in turn will give you site's name. However, this seem like a very roundabout way.

If Change Log fields were displaying names instead of numeric values, looking up a history of the object would be much easier without requiring a user to match numeric values to the object's name.

Hope the above makes sense.

**Comment by jeremystretch** [comment]
When recording a change, NetBox serializes only attributes of the object itself. This is done both as a performance optimization and to ensure the integrity of the data (primary keys never change). For example, if a device's `site` field was recorded as "Site123," but the name of that site was later changed to "Site456", it would no longer be possible to correlate the change record to that site.

**Comment by michalceb** [comment]
> 
> 
> When recording a change, NetBox serializes only attributes of the object itself. This is done both as a performance optimization and to ensure the integrity of the data (primary keys never change). For example, if a device's `site` field was recorded as "Site123," but the name of that site was later changed to "Site456", it would no longer be possible to correlate the change record to that site.

Understood.
It sounds like a bit of a catch 22 situation.
On one hand, it does make sense to record information by the numeric value, since like you said, the name itself can change, and if it does it would be impossible to track the change back to the correct object.
On the other hand, having record use numeric value it takes additional steps for a user to confirm what object is the log referencing.

It would be handy to have a facility that would allow a quick identification of the object that numeric value represents.
Unfortunately, I don't know enough about coding and the implication of even something simple like embedded links in the Change Log on the performance to suggest a creative solution.

At the very least I now understand reasoning behind why was the change log designed this way.

**Comment by jeremystretch** [comment]
> It would be handy to have a facility that would allow a quick identification of the object that numeric value represents.

The unique ID links directly to the related object. For example, if you see `site: 265`, you know that you can access this object at `/sites/265/`.

> even something simple like embedded links in the Change Log on the performance to suggest a creative solution.

My guess is that it would be more trouble than it's worth. You're welcome to submit a feature request for it though to see if anyone wants to volunteer.

I'm going to close this issue since we won't be modifying the serialization format.
