### ISSUE TITLE
Extra info in Prefix information screen 

### ISSUE THREAD

**Issue by chesronw** [netbox-community/netbox#6838]
### NetBox version

v2.11.9

### Feature type

Change to existing functionality

### Proposed functionality

Hi,

Is it possible to define in the prefix information screen also some extra information about that prefix for how to use?
It would be great to define also the default gateway, DNS and NTP information. 

DNS and NTP info could be in a custom field of course. 
But the gateway you want to specify this from the IP address. So also that IP is also marked as the default gateway. 

A good example is that in PHPIpam (Yes Netbox is better)
At a IP address you have a YES/NEW button for the gateway.

![image](https://user-images.githubusercontent.com/85490348/127472001-ce59e34a-8418-4116-9e03-d64fe43592cf.png)

After setting the gateway it is also in de subnet visible in the subnet details 

![image](https://user-images.githubusercontent.com/85490348/127471666-a50c211a-836b-4b73-8f7e-a5736c12ed0b.png)

### Use case

The use case in this is that other departments like system administrators also know what the gateway other needed information is about a subnet.

**Comment by jeremystretch** [comment]
NetBox doesn't have built-in fields for these on the prefix model because it doesn't always make sense to do so. However, if it makes sense for your particular use case, you have the option of adding [custom fields](https://netbox.readthedocs.io/en/stable/additional-features/custom-fields/) to the prefix model to track these values.

**Comment by chesronw** [comment]
Hi Jeremy,

Thanks for your update! 
I agree that is not always make sense. 

But a custom field is possible but you need to double the administration also in the IP address tab

Is it possible to make this as a optional option to mark it as the gateway?
Where in the prefix screen you can see the IP that is marked as gateway?

**Comment by jsenecal** [comment]
That specific requirement could also be baked in as a netbox plugin @chesronw . Have you looked into these ?

**Comment by DanSheps** [comment]
I agree with everything here, I don't see this being implemented in core.

This has also been brought up in the following:

#3109
#2953
#1610

**Comment by julianze** [comment]
DNS and NTP information is best documentated with config contexts. Config contexts aren't linkable to prefix, but for sites or other models.
I think many prefix will have same DNS and NTP informations, so config contexts are the right place. You can see at every device the rendered configs. So the sysadmin (happy sysadmin day 😄 ) will see the right configs for a particular host.

Default gateway: 
The latest discussion about this is in the discussions section. I have made there a proposal which should address all requirements and concerns of both sides (user + maintainer):
https://github.com/netbox-community/netbox/discussions/6030#discussioncomment-591688

Maybe we can discuss further this in the discussion section?

**Comment by jeremystretch** [comment]
I'm going to close this out as the consensus seems to be that it doesn't make sense to pursue at this time.
