### ISSUE TITLE
Error while editing the existing device.

### ISSUE THREAD

**Issue by Narek307** [netbox-community/netbox#6841]
### NetBox version

v2.11.8

### Python version

3.6

### Steps to Reproduce

1. Edit Device
2. Edit any field
3. Click on update

### Expected Behavior

Device has been edited.

### Observed Behavior

Hello,
I am getting the following error: "Unknown field name 'coordinates' in custom field data." while editing the existing device.
Can you please help me to solve this issue?
![Capture](https://user-images.githubusercontent.com/53900129/127483013-30daccc5-d3c1-4dcc-aaf1-42b0131c0c98.PNG)

Below mentioned Workarounds have been tested already.
Workaround 1: create a new custom field called "coordinates" for Device; and then delete it. That should clean up your data. (However it's unclear how it got into this state in the first place)
Workaround 2: fix up the custom_field_data field in dcim.devices using a Django script or direct SQL update

**Comment by jeremystretch** [comment]
Thank you for opening a bug report. I was unable to reproduce the reported behavior on NetBox v2.11.10. Please re-confirm the reported behavior on the current stable release and adjust your post above as necessary. Remember to provide detailed steps that someone else can follow using a clean installation of NetBox to reproduce the issue. Remember to include the steps taken to create any initial objects or other data.

**Comment by Narek307** [comment]
Sorry, that was my bad. It was related to netbox_topology_view plugin activation. The problem has been solved.
