### ISSUE TITLE
Edit-Popup for Fields in a List

### ISSUE THREAD

**Issue by 9er** [netbox-community/netbox#6844]
### NetBox version

v2.11.9

### Feature type

New functionality

### Proposed functionality

Fields in lists should be quickly editable by clicking on them. The UI could open a small popup with a dropdown if it's a ForeignKey or just a text box. This would speed up many small workflows where you would normally click on an entry, go to the edit form, scroll down, etc.

I'm not sure if there's a Django feature that already lets you do this, or if this functionality should even be implemented upstream.

We have features like this in other tools that use flask-admin, so here are some example screenshots for inspiration:

![Screenshot from 2021-07-29 16-52-00](https://user-images.githubusercontent.com/417945/127514398-fe01d222-ea15-4e09-be58-d92247805202.png)

![Screenshot from 2021-07-29 16-52-21](https://user-images.githubusercontent.com/417945/127514428-bcce91a3-4f10-4653-8ddb-fe958c7f996c.png)

### Use case

Plenty of use cases! Generally everything where you just want to edit one thing
  * changing a device status from Planned to Active
  * fixing a typo that you found while scrolling though the list
  * quickly editing a description or a DNS name
  * assigning an IP address to a tenant
  * ...

### Database changes

None.

### External dependencies

Probably no new dependencies.

**Comment by jeremystretch** [comment]
What you're proposing would require an enormous amount of work on the front end, and we're _just now_ finishing up the major overhaul for v3.0. A mature implementation of this sort of functionality outside of an off-the-shelf library such as flask-admin requires adopting a fully API-driven front end (e.g. React, Angular, etc.). It's certainly something we've had in mind for an eventual future release, but unfortunately it's not something we can reasonably undertake in the near future.

**Comment by jeremystretch** [comment]
Closing this out to be revisited for a future release, once we're ready to make the jump with the UI.
