### ISSUE TITLE
v3.0-beta1 - Make ChangeLog Entrys (Count) on HomeScreen configurable

### ISSUE THREAD

**Issue by tb-killa** [netbox-community/netbox#6858]
### NetBox version

v3.0-beta1

### Feature type

New functionality

### Proposed functionality

It would be great if we could modify per User the Count of Showing ChangeLog Entrys on the the HomeScreen.

### Use case

For better Overview it would be great if per User it would be allows to change the Count of Lines of the ChangeLog Entrys on the HomeScreen for better Overview.
If someone prefered 20 Line he could configure themselve.

### Database changes

None.

### External dependencies

None

**Comment by jeremystretch** [comment]
The change log has been present on the main view for years; it's just more visible under v3.0. It is intended merely to offer a convenient look into the most recent changes in NetBox. For anything more than that, you should be looking at the dedicated change log view.
