### ISSUE TITLE
No general search within sections

### ISSUE THREAD

**Issue by rodvand** [netbox-community/netbox#6863]
### NetBox version

v3.0-beta1

### Python version

3.8

### Steps to Reproduce

1. Create a prefix with a description "Branch office"
2. Go to the prefix overview (ipam/prefixes/) and see that there is no option within the advanced search to search for description

### Expected Behavior

Have a Search box within Advanced Search allowing to search across multiple fields (the q filter).

### Observed Behavior

To search for a prefix with a description "branch" you have to either make sure all the prefixes are listed on the prefix overview and use the "Filter" functionality, or use the global search.

In NetBox 2.11 the search section has a general "Search" text box which spans multiple fields.

This seems to be a change for all sections, so for example in Devices it's impossible to search within a device's description without using the global search.

**Comment by thatmattlove** [comment]
Any reason this filter input doesn't work for your needs?

<img width="881" alt="Screen Shot 2021-08-02 at 09 38 55" src="https://user-images.githubusercontent.com/42724207/127895309-232225ee-0985-4f5c-8bb7-8700925104cf.png">

**Comment by rodvand** [comment]
@thatmattlove Yes, because it only filters on the currently shown items. So in this example there is another prefix with the description "Branch", but it's on page 2 so it's not listed using that filter.

Also, the other example of Device. The only way to search for a device's comments is now through the global search whereas earlier you had the search box dedicated to the device in the right hand search column.

**Comment by thatmattlove** [comment]
Fair enough. I'll get this added back into the advanced search/filter panel.
