### ISSUE TITLE
Provide Configure button on Child Prefixes page

### ISSUE THREAD

**Issue by rakeshmohan46** [netbox-community/netbox#6872]
### NetBox version

2.11.6

### Feature type

New functionality

### Proposed functionality

The child prefixes page should provide a Configure button to pick and choose the model attributes. 

### Use case

This helps the user to view any custom fields and reduce load time by removing the utilization column.

### Database changes

None

### External dependencies

None

**Comment by jeremystretch** [comment]
To be clear, this is the same table as the one used on the prefixes list, so the preferences should carry over between the two.
