### ISSUE TITLE
Add Tenant to Location Model

### ISSUE THREAD

**Issue by sleepinggenius2** [netbox-community/netbox#6874]
### NetBox version

v2.11.10

### Feature type

Data model extension

### Proposed functionality

Add a *Tenant* field to the existing *Location* model.

### Use case

In a colocation environment, customers can be assigned their own cages, typically containing one or more racks, as well as other items, like power panels. It would be nice to be able to create a location to represent such a cage within a site and assign racks, power panels, devices, etc. to it, while also tracking the customer assigned to that location. Racks and devices can be assigned to a tenant today, but power panels cannot, and they can all be assigned to a location. Using a site to represent this situation is cumbersome, as a lot of the fields would need to be duplicated among the site objects and it doesn't really seem right conceptually.

### Database changes

Add a *Tenant* field to the existing *Location* model.

### External dependencies

None

**Comment by jeremystretch** [comment]
We already have tenancy assignment for racks and sites. Seems like it would make sense to support locations as well.

**Comment by sdktr** [comment]
Let's add Region tenancy as well?

**Comment by jeremystretch** [comment]
Regions and site groups exist above the site model in the hierarchy, and are intended to group sites. It would not make sense to assign tenants to these models.

**Comment by jcralbino** [comment]
Just found this FR when trying to add a tenant to a location... 
Hope to get this soon :)
