### ISSUE TITLE
v3.0-beta - Sidebar Pinning as User Preferences Value.

### ISSUE THREAD

**Issue by tb-killa** [netbox-community/netbox#6878]
### NetBox version

v3.0-dev

### Feature type

New functionality

### Proposed functionality

in v3.0-dev we have now a sidebar who could be pinned to be fixed or if unpinned it swap out only if we mouseover.
this functionality (pinned / no pinned) should be configured as an "User Preferences" - Setting to be available for the User.

The "Preference" could be called "ui.sidebar.pinned" with value "true" or "false" and could be saved if the User changed this value via Clicking on the "Pin" Icon, behind the Javascript themselve should write to the api with these defined value.
For Rendering the preloaded Value from the Database should be loaded and paste.

### Use case

This allowed the User themselves to defined what "static" Method of Sidebar-Pinning he like and because of an saved Value inside the "User Preferences" it loaded directly.

### Database changes

None.

### External dependencies

None.

**Comment by thatmattlove** [comment]
What benefit does this add over the current functionality of remembering the setting via localStorage? The only benefit I can think of is that it would be persisted across multiple browsers/devices. And even in that case, you might actually want different pinning preferences across different devices. For example, one might have a laptop/desktop with a large screen where you _do_ want it pinned, but an iPad/tablet where you _do not_ want it pinned. If set via user preference, this would be persisted across both devices, which would be annoying.

Am I missing another benefit?

**Comment by jeremystretch** [comment]
I want to echo Matt's comment above. I'd rather have the toggle be device-specific rather than persistent.

**Comment by DanSheps** [comment]
I think the only case where you **might** want this is for the user to have a default that is user specific.  However, I don't see the value in this right now.

**Comment by jeremystretch** [comment]
Let's punt on this one. Maybe something to revisit once we have a more robust preferences system in place.
