### ISSUE TITLE
Adding Power Port Types C21/C22

### ISSUE THREAD

**Issue by Scottsie** [netbox-community/netbox#6883]
### NetBox version

v2.11.3

### Feature type

Data model extension

### Proposed functionality

Adding support in the power port types field for the C21/C22 form factor end points.
Governed under [IEC_60320](https://en.wikipedia.org/wiki/IEC_60320)

### Use case

[Dell MX7000](https://www.dell.com/support/manuals/en-us/poweredge-mx7000/pemx7000_ts_pub/psu-specifications?guid=guid-c478c564-a848-43b4-b4cd-be33d965bace&lang=en-us) chassis and it uses C22 power ports in it's PSUs. C21 would be the connector counter part if that's applicable in another field type.

### Database changes

N/A. New type in existing field.

### External dependencies

N/A

**Comment by bellwood** [comment]
I've got a PR on this, see my note though.
