### ISSUE TITLE
Change 1:1 mapping of an IP address to a device to 1:n

### ISSUE THREAD

**Issue by c-po** [netbox-community/netbox#6888]
### NetBox version

v2.11.10

### Feature type

Data model extension

### Proposed functionality

As of now an IP address can be assigned to an interface of one specific device. In the case of EVPN anycast gateways or any other type of anycast service where the Anycast address is assigned to a loopback port of a device I can not "pin" one IP address to multiple devices.

![image](https://user-images.githubusercontent.com/25299219/128310094-9086486c-d0f2-4918-b15d-f648a3bd2a7c.png)

### Use case

- Anycast DNS service wher multiple servers service the same IP address
- EVPN/VXLAN fabrics with MLAG pairs where the VTEP loopback address is available on both MLAG units

**Comment by sdktr** [comment]
The Anycast role (as well as the FHRP roles) allows to create the same IP Address multiple times. So in the database there will be multiple IDs with the same IP. 
Checkout [this example](https://demo.netbox.dev/ipam/ip-addresses/?q=&parent=&family=&mask_length=&present_in_vrf_id=&role=anycast&assigned_to_interface=) on the demo instance (it will expire every day, so be quick)
![image](https://user-images.githubusercontent.com/19833687/128317469-ed4e71d3-7b0a-4ca0-84e9-07310397c429.png)

**Comment by jeremystretch** [comment]
As @sdktr notes, the supported approach here is to create a discrete instance of the IP address for each assignment. This ensures a greater degree of flexibility, allowing the operator to manipulate the attributes of each individual IP address as needed.

**Comment by c-po** [comment]
Works for me. Thank you for pointing this out!
