### ISSUE TITLE
Assign existing prefix to VLAN, starting from VLAN view

### ISSUE THREAD

**Issue by sdktr** [netbox-community/netbox#6905]
### NetBox version

v2.11.10

### Feature type

Change to existing functionality

### Proposed functionality

When attaching a prefix to a VLAN there are two routes in the GUI:
1) Open the prefix and choose a VLAN using the vlan filters OR
2) Open the VLAN and click 'add prefix'

Scenario 2 closely repeats the workflow for assigning an IP to an interface. In that selector there is an option to assign an already known IP instead of creating a new instance. 
Assigning a prefix to a vlan would benefit from an 'assign' option as well. 

### Use case

When starting from a VLAN, trying to attach an existing prefix requires opening a new set of tabs to look up the prefix and starting the association from there. Attaching an already known prefix would save quite some clicks.

### Database changes

N/A

### External dependencies

N/A

**Comment by rhyser9** [comment]
I can try implementing this.

Using the existing IP Address Add / Assign setup as an example, it looks like this will involve adding a `prefixes/assign` URL, `PrefixAssignView`, `PrefixAssignForm`, `PrefixAssignTable`, `inc/prefix_edit_header.html`, `prefix_edit.html`, and `prefix_assign.html`.

**Comment by DanSheps** [comment]
Assigned to you @rhyser9

**Comment by thefreakquency** [comment]
Is this something that is or will be addressed in 3.5? It would follow the logic behind other processes (i.e assigning an existing IP to an interface instead of creating a new one).

**Comment by jeremystretch** [comment]
It doesn't appear that any feasible solution has been offered, so I'm going to close this out. We might revisit this in the future once the UI has been revamped per #12128.
