### ISSUE TITLE
VLANGroup CSV Import broken

### ISSUE THREAD

**Issue by sdktr** [netbox-community/netbox#6908]
### NetBox version

v2.11.10

### Python version

3.8

### Steps to Reproduce

1. Import VLANGroup CSV using this content
```
name,slug,scope_type,scope_id
DM-NYC,DMNYC,site,1
```

### Expected Behavior

New Vlangroup, scoped to Site with id 1 is created.
The prefered behavior would be that scope could refer other attributes then 'id'. Like the other import options that have 'accessors':
```
name,slug,scope_type,scope.name
DM-NYC,DMNYC,site,mysitename
```

### Observed Behavior

Error is trown:

> Row 1 scope_type: Select a valid choice. That choice is not one of the available choices.
> Row 1 __all__: Cannot set scope_id without scope_type.

This bug is a follow up of:  https://github.com/netbox-community/netbox/discussions/6897

**Comment by jeremystretch** [comment]
This is a bug, however the input value for `scope_type` should be `dcim.site`, not `site`.
