### ISSUE TITLE
some static files not found when `BASE_PATH` is changed

### ISSUE THREAD

**Issue by nolta** [netbox-community/netbox#6912]
### NetBox version

v3.0-beta1

### Python version

3.8

### Steps to Reproduce

1. Set `BASE_PATH = 'netbox/'`
2. Run `upgrade.sh`.
3. Load site in browser.

### Expected Behavior

All static asset files should be found.

### Observed Behavior

Some static files cannot be found (i.e., 404 errors).

For example, the site tries to load `/static/netbox.js.map` instead of `/netbox/static/netbox.js.map`. The problem appears to be this line: https://github.com/netbox-community/netbox/blob/6845fb0f005f0bdc15a258ae2ebd7f9be5341f76/netbox/project-static/dist/netbox.js#L67

Perhaps due to this?
https://github.com/netbox-community/netbox/blob/6845fb0f005f0bdc15a258ae2ebd7f9be5341f76/netbox/project-static/bundle.js#L11

Changing `sourceMappingURL=/static/netbox.js.map` to `sourceMappingURL=netbox.js.map` appears to work, at least for this particular file.

**Comment by jeremystretch** [comment]
I don't have any issues loading Javascript resources using the current `feature` build with a non-default `BASE_PATH`, however I do see that the Material Design Icons font is being hard-coded to `/static/`. It also looks like we're pulling the Inter font from fonts.gstatic.com instead of locally.

**Comment by m2martin** [comment]
Shouldn't it be avoided to have mixed sources (local statics and external includes)?
In case of the font, this shouldn't cause any problems, as the [Open Fonts License](https://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=OFL) for `Inter` grants copying, embedding and redistributing.
Background: I do have Netbox instances where the clients are not allowed to access external resources.
What's your opinion?
