### ISSUE TITLE
Move user-managed assets to own subdirectory tree

### ISSUE THREAD

**Issue by candlerb** [netbox-community/netbox#6916]
### NetBox version

v3.0-beta1

### Python version

3.8

### Steps to Reproduce

This isn't a bug report, but a suggestion for something that could change for v3.0.

Currently the `/opt/netbox/netbox` directory contains a mix of user-managed files (media, reports, scripts) and actual Netbox source code.  Netbox v3.0 is an opportunity to make a clean separation between them.

There are already configuration settings `MEDIA_ROOT`, `REPORTS_ROOT`, `SCRIPTS_ROOT` so this could just be a case of changing how the defaults are calculated.

### Expected Behavior

User-installed data to be in a separate directory tree, perhaps `/opt/netbox/data` or `/var/lib/netbox`.  In the latter case this would give:

* `/var/lib/netbox/media`
* `/var/lib/netbox/reports`
* `/var/lib/netbox/scripts`

It would then be straightforward to backup/restore `/var/lib/netbox`, transfer to another Netbox instance etc.

### Observed Behavior

By default, the user-managed assets are in:

* `/opt/netbox/netbox/media`
* `/opt/netbox/netbox/reports`
* `/opt/netbox/netbox/scripts`

alongside code directories such as

* `/opt/netbox/netbox/circuits`
* `/opt/netbox/netbox/dcim`
* ... etc

**Comment by jeremystretch** [comment]
Could you re-open this as a feature request, please, since it does not describe unexpected behavior? I'm also not clear on the use case.

> something that could change for v3.0.

I'm afraid it's too late in the release cycle to introduce any substantial changes. It would need to be discussed for v3.1.
