### ISSUE TITLE
Clickable link for IPAddress "assigned"

### ISSUE THREAD

**Issue by candlerb** [netbox-community/netbox#6917]
### NetBox version

v2.11.10 and v3.0-beta1

### Feature type

New functionality

### Proposed functionality

In a listing of IP addresses (`/ipam/ip-addresses/`), there is a column "Assigned" which has a green checkmark if it is assigned.

I would like this to be clickable to jump to the interface that it's assigned to - i.e. a link to `/dcim/interfaces/<N>/` or `/virtualization/interfaces/<N>/`

(Ideally I'd like it to show the device/VM name and interface name, but that would be a more expensive database query.  Making it link to the interface is essentially free)

### Use case

A quicker way to navigate to the assigned interface.  Otherwise, you have to first click on the IP address itself, which then shows its assigned device/VM and interface.

### Database changes

None

### External dependencies

None

**Comment by royreznik** [comment]
@jeremystretch I can add it

**Comment by jeremystretch** [comment]
Thanks @royreznik!
