### ISSUE TITLE
Interfaces Table - bring back the visual aids from v2.9

### ISSUE THREAD

**Issue by CironAkono** [netbox-community/netbox#6925]
### NetBox version

v3.0-dev

### Feature type

Change to existing functionality

### Proposed functionality

In v2.9:

1. Virtual interfaces were distinguished by their yellow row color. 
2. Disabled interfaces were distinguished by their red row color.
3. Connected interfaces were distinguished by their green row color.    
4. The interface type was distinguished by different icons before the interface name:
- Circle for virtual interfaces
- "Hamburger" for LAG interfaces
- Wrench for OOB Management interface
- Wifi symbol for wifi links
- Two arrows for ethernet links and others

![image](https://user-images.githubusercontent.com/816267/128840831-c37cd6f1-decf-48da-a0dc-0c4717d8e451.png)

This is something that got lost somewhere in v2.10 or v2.11.

v2.11
![image](https://user-images.githubusercontent.com/816267/128841865-9b0d8145-23fe-4e17-8000-bf1a00684b55.png)

v3.0-dev
![image](https://user-images.githubusercontent.com/816267/128842016-0685ff22-0898-4f4d-a963-743b46192984.png)

- All interfaces, virtual and physical have the same row color. Only connected interfaces get a green row color.
- All interfaces, despite their type, have the same icon before the interface name.
- To find the OOB Management interface, one needs to enable the "Management Only" column.
- To find the enabled interfaces, one needs to enable the "Enabled" column.

This FR proposes to bring back the visual aids that helped get instant information by looking at the interfaces table without overwhelming it with the columns: "Management Only", "Enabled" and "Type". 
This FR does not intent to remove the option of having those columns. They are still useful to order the interfaces.

### Use case

Reduce the need of the columns "Management Only", "Enabled" and "Type" on the Interfaces table by adding some visual aids that were used on past versions (v2.9).

1. Virtual interfaces could be distinguished by their yellow row color. 
2. Disabled interfaces were distinguished by their red row color.
3. Connected interfaces were distinguished by their green row color.    
4. The interface type was distinguished by different icons before the interface name.

With this feature, one can instantly get information about the interface type and status by looking at the interfaces table.
No need to overwhelm the interfaces table with extra columns: "Management Only", "Enabled" and "Type"
These columns should still be available to be added to the interfaces tables. They are useful to order the interfaces.

**Comment by jeremystretch** [comment]
> This is something that got lost somewhere in v2.10 or v2.11.

The change was made when we migrated the device component tables from template-based rendering to proper Table classes using django-tables2. AFAIK it should be possible to replicate the old behavior, however any proposed implementation would need to employ the current classes (e.g. not revert to using raw templates) in an efficient and maintainable manner.

**Comment by CironAkono** [comment]
> @CironAkono are you interested in volunteering to implement this?

@jeremystretch my experience doesn't go beyond simple python scripts. But I can give it a try.

From the Use Case bullet points, I already know how to fix  4.
3. is already working as expected and It may give me some clues on how to fix 1. and 2.
You can sign me up.
