### ISSUE TITLE
Add ID as an exportable column for all object tables

### ISSUE THREAD

**Issue by TigerEnteNBG** [netbox-community/netbox#6930]
### NetBox version

v2.11.9

### Feature type

Change to existing functionality

### Proposed functionality

It would be nice, if we can export the device ID (or even the complete URL) into a csv files using the already available export csv feature.

### Use case

We would like to add the netbox URL into our CMDB to provide direct links.

Can be also useful for other usecases, if you can export the ID.

**Comment by sdktr** [comment]
You can make a custom export template that can contain all the fields you could ever wish for.
Did you try that functionality?

**Comment by TigerEnteNBG** [comment]
Not yet, but I will definitely have a look at this. Thanks for the hint.

**Comment by sdktr** [comment]
Checkout the webhooks as well, if you try to do more then a one-off /manual sync between netbox and another system

**Comment by jeremystretch** [comment]
FWIW we could add an "ID" column to all object tables pretty easily, I think. It would be hidden by default but available.
