### ISSUE TITLE
Add MTP connector type

### ISSUE THREAD

**Issue by bellwood** [netbox-community/netbox#6932]
### NetBox version

v2.10.11

### Feature type

Change to existing functionality

### Proposed functionality

Add MTP to choices.py for fiber connections.

Feel free to assign to me and I will make a PR to whatever branch is desired (Feature and or Develop)

### Use case

MTP *is* different than MPO and it would be great to use the proper connector for modules and cables.

https://ecatalog.corning.com/optical-communications/US/en/Fiber-Optic-Hardware/Panels-Modules-and-Cassettes/EDGE%E2%84%A2-Module/p/ECM-RM12-04-89G

https://community.fs.com/blog/mtp-vs-mpo-cable-what-are-the-differences.html

### Database changes

None

### External dependencies

None

**Comment by DanSheps** [comment]
As per.our contributing guide, we do not accept PRs without a first approved FR

**Comment by DanSheps** [comment]
My view is this:

MTP is a modified MPO which is fully compatible with MPO.  I am not for or against adding the MTP but there is nothing distinctive between MPO and MTP as far as compatibility, it is more just a mechanical mechanism to ensure ease of use and more secure connections.

**Comment by jeremystretch** [comment]
It does seem like splitting hairs. Is there a discernible physical difference between the two, or is MTP merely a trademark?

**Comment by bellwood** [comment]
It's an improved MPO. There is interchangeability with the cables but by specification MTP is higher performing than a standard MPO. In some places we order MPO and others, MTP. Since they are different "in the real world" seemed reasonable to document it as such.

**Comment by DanSheps** [comment]
> It does seem like splitting hairs. Is there a discernible physical difference between the two, or is MTP merely a trademark?

Mostly trademark from what I see with some higher specifications for the mechanical connectors but 100% interchangeable.

**Comment by bellwood** [comment]
> I say we leave this open and see if we get votes for it, if we don't we can always close it out.

It's been included/mentioned in a few FR's if you look back through issues.

> That said, from a data deduplication standpoint, given that they are near identical, I don't see the overall benefit in adding it to the database.

I would be willing to completely agree if this was anything more than a 2-line addition. We aren't duplicating large portions of the codebase or otherwise presenting development with a burden for something trivial.

**Comment by phurrelmann** [comment]
Imho MTP comes into play on the cable side, but not on the connector side. I'm not aware on any distinctions of MTP/MPO on a transceiver or interface. The differences are solely on the cable, but one can't track that in netbox currently.

**Comment by bellwood** [comment]
On the cable side for fiber, we can only pick SMF or MMF and it wouldn't make sense to add another cable just for this, unless we wanted to also talk about tracking the three different cabling polarity types associated with MPO/MTP.

We use a variety of MPO/MTP and polarity depending on the application and site. 

I'm certainly open to suggestion.
