### ISSUE TITLE
 'dcim.models.cables.Cable.DoesNotExist error when trying to recreate cable.

### ISSUE THREAD

**Issue by bordwalk2000** [netbox-community/netbox#6945]
### NetBox version

v2.11.10

### Python version

3.8

### Steps to Reproduce

1. Connect Cable to two entities. (I've tried device to device and device to circuit, both create the same error.)
2. Delete cable because one side was not connected to correct interface. 
3. Re-Create the cable but connecting one side to a different interface. 
4. Bug appears

P.S. I am running NetBox in docker.

### Expected Behavior

A new cable to be create to the two entities.

### Observed Behavior

Following error occurs. 

![image](https://user-images.githubusercontent.com/4552602/129195996-ef4c101e-01c8-4cf2-98b8-1bb4ea1054ab.png)

<class 'dcim.models.cables.Cable.DoesNotExist'>

Cable matching query does not exist.

Python version: 3.8.10
NetBox version: 2.11.10

Note:  A restart of the NetBox docker container containers corrects the problem until the next time I go to delete a cable.

**Comment by bellwood** [comment]
This is a known issue with caching, see: #6636

**Comment by jeremystretch** [comment]
Yep. Please disable caching by setting `CACHE_TIMEOUT = 0` in `configuration.py` and restart NetBox to resolve the issue.
