### ISSUE TITLE
Remove change log tab from change log entry

### ISSUE THREAD

**Issue by rodvand** [netbox-community/netbox#6953]
### NetBox version

v3.0-beta1

### Python version

3.8

### Steps to Reproduce

1. Force a change log entry to be created
2. Navigate to the change log entry

### Expected Behavior

Not really necessary with a change log tab linking to the same change log on a single change log entry?

### Observed Behavior

There is a change log tab on the single change log entry. It links back to the same change log entry.

<img width="696" alt="Screenshot 2021-08-13 at 12 39 53" src="https://user-images.githubusercontent.com/56864/129345225-a177826b-f88a-473b-b955-5f9ad1e78259.png">

**Comment by jeremystretch** [comment]
![We heard you like change logging, so we logged changes to your change log](https://user-images.githubusercontent.com/13487278/129361487-54ff1042-2705-43b7-9e50-5a17365541a8.jpg)
