### ISSUE TITLE
Save sorting settings for individual users under preferences

### ISSUE THREAD

**Issue by florianschendel** [netbox-community/netbox#6954]
### NetBox version

v2.11.11

### Feature type

New functionality

### Proposed functionality

Save sorting settings for individual users under preferences.

Like "pagination": {"per_page": 50}

### Use case

For example, in the IPAM Prefixes overview I want to sort by prefixes and not by VRFs. If I load the the prefixes I get the prefixes always sorted by VRFs and not by prefixes.

**Comment by jeremystretch** [comment]
Blocked by #7759
