### ISSUE TITLE
Developer doc for v3: point out "yarn typecheck"

### ISSUE THREAD

**Issue by candlerb** [netbox-community/netbox#6962]
### Change Type

Addition

### Area

Administration/development

### Proposed Changes

Mention `yarn typecheck` in netbox/project-static/README.md

`yarn bundle:scripts` [does not do type checking](https://esbuild.github.io/content-types/#typescript) so an extra step is required to validate typescript.

**Comment by thatmattlove** [comment]
c221b9b should address this — there's now a Web UI section in the docs that explains much of the front end stack and documents available commands. Additionally, #7024 proposes running these checks via standard development processes (pre-commit hooks and CI).
