### ISSUE TITLE
Static content error on air gapped NetBox

### ISSUE THREAD

**Issue by rodvand** [netbox-community/netbox#6966]
### NetBox version

v3.0-beta2

### Python version

3.8

### Steps to Reproduce

1. Have an air gapped NetBox
2. Install Netbox v3.0-beta2
3. Visit NetBox front page

### Expected Behavior

Front page to load.

### Observed Behavior

```
Static Media Failure
The following static media file failed to load: netbox-external.css
```

The netbox-external.css seems to try loading `https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800&display=swap` in `netbox-external.css`. Removing this reference make the page load again without error.

**Comment by jeremystretch** [comment]
From what I've read, the process to embed a Google font locally seems fairly involved. If this is going to mean jumping through hoops, I'd much rather ditch the custom font for something stock. What's your take, @thatmattlove?

**Comment by bellwood** [comment]
It's not overly complicated and once it's done, you're done, unless you want to load more fonts later on:

https://www.wpmediamastery.com/host-google-fonts-locally/

That being said, I'm all for stock fonts.

**Comment by thatmattlove** [comment]
The best way to self-hosting nowadays is to use something like [fontsource](https://github.com/fontsource/fontsource) and just manage it like any other external dependency. I've just tested this locally and it seems to work perfectly with essentially no hoops.

That said, I don't care about fonts either way. The use of Inter came from our internal discussions about lifting design choices from [Volt](https://demo.themesberg.com/volt/), and that sort of came along with it. I'm open to suggestions about how to move forward.

**Comment by thatmattlove** [comment]
@rodvand @bellwood @jeremystretch Anybody got any opinions on how to proceed with this?

**Comment by bellwood** [comment]
I'm all in favor of ditching external dependancies where possible. 

In a utility app, typography doesn't need to be fancy.

**Comment by jeremystretch** [comment]
Agreed; let's just ditch the external font for v3.0. Happy to revisit in the future.
