### ISSUE TITLE
Exception.message was deprecated in Python 2.6 and removed in Python 3

### ISSUE THREAD

**Issue by cclauss** [netbox-community/netbox#6969]
### NetBox version

master

### Python version

3.6

### Steps to Reproduce

Run the lines of code fixed in #6959 

See #6956 and #6959

### Expected Behavior

Program does not raise AttributeError at runtime.

### Observed Behavior

Program raises AttributeError at runtime.

**Comment by jeremystretch** [comment]
Please provide steps to reproduce

**Comment by cclauss** [comment]
The steps are in #6959
