### ISSUE TITLE
Circuits: add termination: "Create and add another" is useless

### ISSUE THREAD

**Issue by lucix-mich** [netbox-community/netbox#6979]
### NetBox version

v2.11.9

### Python version

3.8

### Steps to Reproduce

1. Create a Circuit
2. In the newly created circuit, click "add" on either Termination A or Termination Z
3. The input mask provides a button "Create and add another" that opens the same input mask a second time, i.e. for the same termination side. But since circuits can only have one each of side A and side Z, the second input mask must (and will) lead to an error and is thus useless.

### Expected Behavior

Button "Create and add another" not shown.

### Observed Behavior

The input mask provides a button "Create and add another" that opens the same input mask a second time, i.e. for the same termination side. But since circuits can only have one each of side A and side Z, the second input mask must (and will) lead to an error and is thus useless.

**Comment by thatmattlove** [comment]
Since this is not a major bug, the fix for this is _only_ going into 3.0 (currently in beta, but to be released soon). 9a8d33e should close this out.
