### ISSUE TITLE
Sticky search/login panel makes elements inaccessible

### ISSUE THREAD

**Issue by erdnaxe** [netbox-community/netbox#6981]
### NetBox version

v3.0-beta2

### Python version

3.9

### Steps to Reproduce

1. Go on any page with a small display
2. Click "filter" button in the top search bar
3. Try to scroll in the list

### Expected Behavior

I would expect to be able to scroll in the list and be able to click elements that are at the end.

### Observed Behavior

![image](https://user-images.githubusercontent.com/2663216/129768916-6aa5d2f8-51c7-463a-97a1-a92b31f81936.png)

The whole page scrolls, but because the search bar is sticky, the filtering list does not scroll.

I believe it would be better to not make this bar sticky at all, but static at the top, as it constantly uses 20% of my screen space and I do not always need search/login.

**Comment by jeremystretch** [comment]
This was actually _just_ fixed in #6977.
