### ISSUE TITLE
Only show one level of locations in SiteView and LocationView

### ISSUE THREAD

**Issue by koh6uawi** [netbox-community/netbox#6986]
### NetBox version

v3.0-beta2

### Feature type

Change to existing functionality

### Proposed functionality

1. Display only locations without parents in `SiteView`.
2. Display only direct children in `LocationView`.

I can open a PR if needed.

### Use case

Some of our sites and locations contains a lot of nested sub-locations. Displaying all of them in one view makes it quite difficult to use the page:

1. one has to scroll a lot before seeing the images in `SiteView`;
2. it is quite difficult to spot a location in the list.

### Database changes

None (I think).

### External dependencies

None.

**Comment by jeremystretch** [comment]
This would make it very tedious to find child locations several levels deep from within the site view.

**Comment by koh6uawi** [comment]
In our case, we have usually at most one or two levels of locations (for each site, one location per floor and then one nested location for rooms (sometimes more than 100 per floor)).

In my opinion, it is always going to be difficult to visually spot one specific location in a list of >100 items, and I think that this is the reason why the search engine exists (we use it quite extensively for these kinds of tasks, and we are very satisfied with it).

The `LocationView` and `SiteView` are useful (at least for us) as a kind of "overview", to give us an overall glance at the structure of a given site/location, and I think that from this point of view, only displaying direct children could make sense.

But I do understand that this may not be the intented purpose of these views.

Maybe it could be possible to add an option in `settings.py` to make it optional (I can implement it if you want, but I don't know if adding opt-in/out config flags for "features" matches the best practices of this project)?

If you decide not to implement this, it could be interesting to update `SiteView` to indent child locations according to their nesting-level (like in `RegionView` for child regions, by replacing the folder icon with bullets). It could make it a bit easier to visually spot locations when there are a lot of them.
