### ISSUE TITLE
Cooling Section

### ISSUE THREAD

**Issue by adamboutcher** [netbox-community/netbox#6987]
### NetBox version

v2.11.10

### Feature type

New functionality

### Proposed functionality

Add a section for cooling. Much like Power connections, water cooled data centres have lots of infrastructure relating to cooling. We require water cooled racks however some people have water cooled servers.

You need a loops similar in high-level function to the current power panel and you need a connection, similar in high-level function to the current power feed.

A rack/device would need an in/out connection but you could combine these into a single database "connection" as long as there was a space to write down notes to flow/return (in/out) details, typically these are a labelled valve, so it would require some freeform text.

For DCs that have water cooled servers, you have cooling into the rack as above but then you distribute this into a server (with a manifold), much like a PDU and so the functionality could be mirrored, although again a free-form text-input for flow/return valve numbering might be required (I've not used a manifold system as I'm unsure to how I'd document it exactly).

### Use case

If its a "green" water cooled DC, then it add extra functionality to maintain connections/locations related to cooling, much like the power section, at the moment this has to be manually extended (we rather simply use custom inputs to include the valve numbers into the rack).

### Database changes

Unknown

### External dependencies

None.

**Comment by bellwood** [comment]
This would essentially be the exact same thing as power. 

Perhaps the way to look at this would be modify the existing power models to be "service" models and let the user flag if the panels, feeds and components are either water or power?

**Comment by adamboutcher** [comment]
That could work, the major difference to power is there's physically two connections that would need documenting in some way, you always have two connections, never just one or three etc.

The key data to capture is cooling capacity (typically in killawatts) , preassure (psi) connection type, flow/return connection (valve) id and maybe operating temp range on the actual loop.

**Comment by bellwood** [comment]
> That could work, the major difference to power is there's physically two connections that would need documenting in some way, you always have two connections, never just one or three etc.

This would be just be another feed no?

**Comment by bellwood** [comment]
> The key data to capture is cooling capacity (typically in killawatts) , preassure (psi) connection type, flow/return connection (valve) id and maybe operating temp range on the actual loop.

This would definitely be a modification/expansion of the existing model.

**Comment by jeremystretch** [comment]
This sounds like the sort of thing that would be best implemented as a plugin initially. Then, once it's seen some real-world use, we can revisit the idea of adding it to NetBox.

**Comment by adamboutcher** [comment]
Thanks! I didn't know plugins were a thing. Will see if I can do it.
