### ISSUE TITLE
Allow circuit termination to provider networks of 3rd party providers

### ISSUE THREAD

**Issue by ktims** [netbox-community/netbox#6989]
### NetBox version

v2.11.11

### Feature type

Change to existing functionality

### Proposed functionality

Allow Circuits to terminate onto Provider Networks of 3rd parties (ie. Provider Network not matching the Circuit Provider).

### Use case

Circuits often terminate into networks that are not controlled by the provider delivering them. For example an AWS DirectConnect / Azure ExpressRoute circuit, a connection to an IXP fabric, even a Transit circuit could be considered this way (terminating to the 'Internet').

Presently, circuits can only terminate to Provider Networks that match the Circuit provider, so the only way to model this is to make the 3rd party network 'owned' by the provider providing connectivity to it. If multiple providers are providing circuits to the same Provider Network (e.g. for HA), it is not possible to model the situation sensibly.

### Database changes

No model changes would be required. I am not sure if this constraint is enforced in the database (probably not...?).

**Comment by sdktr** [comment]
You can chain up several circuits to model what you want?

Circuit 1 (provider: Megaport) -A/Z-termination into: - Circuit 2 (provider: Azure, termination: Azure Provider Network)

**Comment by ktims** [comment]
@sdktr Oooh clever, I didn't realize circuits could be connected to each other. I will give that a try, should work.

**Comment by jeremystretch** [comment]
Looks like you found a solution.
