### ISSUE TITLE
V3: Content-title and Controls wrap on mobile

### ISSUE THREAD

**Issue by bellwood** [netbox-community/netbox#6997]
### NetBox version

v3.0-beta2

### Python version

3.9

### Steps to Reproduce

![IMG_0075](https://user-images.githubusercontent.com/2453632/130109200-8d1e27a7-2312-4725-8e09-6250ee7d2fec.jpeg)

### Expected Behavior

Content-title and Controls should be in the same line / horizontal plane.

### Observed Behavior

In portrait mode, the content title, here "IP Addresses" and the control buttons on the right, are on different lines.

In landscape mode, they share the same horizontal space/plane, reducing whitespace.

**Comment by jeremystretch** [comment]
This is intentional. Some views have longer titles and/or additional buttons, and trying to squeeze them all into a single line looks very bad.

**Comment by bellwood** [comment]
> This is intentional. Some views have longer titles and/or additional buttons, and trying to squeeze them all into a single line looks very bad.

Makes sense. Any thoughts about placing controls in the same vertical plane as the tabs then?
