### ISSUE TITLE
Custom Field relation with Netbox Inventory

### ISSUE THREAD

**Issue by apellini** [netbox-community/netbox#7002]
### NetBox version

v2.11.11

### Feature type

Change to existing functionality

### Proposed functionality

Add the possibility to create a custom field that use Database Inventory as selection list.

For example, on IPAM ==> Prefix I could create a custom field that have a selection menu. Value of this menu are taken from DCIM ==> Device Table.

### Use case

Identify L3 Gateway of a particular network. Identify CPE or root switches.

**Comment by sdktr** [comment]
What you're suggesting is called 'Relationships' in the Nautobot spinoff: https://blog.networktocode.com/post/nautobot-relationships-part-1

Are you requesting the same functionality within Netbox? So you can point models directly to each other that aren't coupled in the core data model?

**Comment by apellini** [comment]
Yes. It’s the functionality that I search.

**Comment by jeremystretch** [comment]
There has been talk of adding a custom field type to reference other objects, however to date no one has submitted a formal feature request. You're welcome to do so, however this would need a new FR as it's obviously more broad than the specific use case cited above.

**Comment by apellini** [comment]
So I have to open a new issue as Feature request with this text:

Adding same feature present in Nautobot fork 'Relationships': https://blog.networktocode.com/post/nautobot-relationships-part-1

Right?

**Comment by jeremystretch** [comment]
No, not at all. That would definitely get rejected. :laughing:

What you want is the ability to reference a different object in NetBox using a custom field, right? Your specific use case happens to focus on inventory items, but really it doesn't matter what kind of model we're looking at. So what you have here is fine; it just needs to be rewritten to be more generic.

I've opened #7006 for this. I like the idea, however we'll need to figure out the exact implementation before it can be assigned a release milestone.
