### ISSUE TITLE
Order Device images by date

### ISSUE THREAD

**Issue by andrewhearn** [netbox-community/netbox#7003]
### NetBox version

v2.11.0

### Feature type

Change to existing functionality

### Proposed functionality

tldr - Images are currently shown in the web UI sorted by Name, can this be changed to Created date (newest at the top?)

Uploading images to a Device is a great way to see what it actually looks like in the real live rack -However, over time things change slightly and so  we take new photos and add them - we like to keep old photos as a reference - but usually just want to look at the newest images - so ordering by Created date would be great here.

### Use case

It makes it easier to see the newest images of a Device.

**Comment by jeremystretch** [comment]
I'm going to close this out in favor of a more general approach to enable this dynamic sorting & pagination on embedded tables. I've opened #8184 to propose this.
