### ISSUE TITLE
Device CSV import doesn't support exported CSV (rack_name)

### ISSUE THREAD

**Issue by m0nkeyc0de** [netbox-community/netbox#7004]
### NetBox version

v2.11.11

### Python version

3.8

### Steps to Reproduce

Same problem as already described in #5238 but closed due to inactivity

Following error messages appears when I try to import the Device CSV I exported on Netbox:
Unexpected column header "rack_name" found

Steps to reproduce:
1. Create a device that's in a rack
2. Export the CSV
3. Import the CSV in another instance
4. Enjoy the error message described above

### Expected Behavior

All exported fields should be imported

### Observed Behavior

Unexpected column header "rack_name" found

**Comment by jeremystretch** [comment]
> All exported fields should be imported

This is not intended behavior. Please see the CSV import form for the list of supported fields.

**Comment by m0nkeyc0de** [comment]
Is it a NetBox intended feature to not be able to import it own exports, or just a side-effect ?
A simple solution (at least on user side) could be to just ignore unsupported columns and throw a warning message.
