### ISSUE TITLE
Nested interfaces table (grouping)

### ISSUE THREAD

**Issue by hiddenman** [netbox-community/netbox#7007]
### NetBox version

3.0-beta2

### Feature type

Change to existing functionality

### Proposed functionality

I'd like to propose a new way of displaying interfaces with nesting/grouping.

For example, we have hundreds of interfaces like:
physical interfaces -> LAG interface -> Virtual interfaces.

Currently Netbox displays all interfaces without any nesting and it's very hard to find out what is linked, where and how.
Of course we can do a little bit of sorting but that doesn't help much.

Here is an example of how it looks on the real hardware:

![image](https://user-images.githubusercontent.com/4009515/130260198-f92fe872-8bf7-4add-907f-b6d8cf6dd033.png)

So maybe adding of some grouping options would be useful for all.

This (closed) issue might be relevant as well: https://github.com/netbox-community/netbox/issues/373

### Use case

In case of hundreds of physical links, tens of LAG interfaces and hundreds of virtual interfaces on top the them it's very hard to track grouping/nesting and levels of abstractions.

**Comment by jeremystretch** [comment]
I'm not sure this would work out as cleanly as you're expecting. Maybe you'd like to try mocking something up using the NetBox UI?

**Comment by hiddenman** [comment]
> I'm not sure this would work out as cleanly as you're expecting. Maybe you'd like to try mocking something up using the NetBox UI?

Thank you.

1. Do you mean just prepare an image with some examples?
2. As other guys said in Slack, it would be better to just add a grouping columns feature, similar to Select columns. Do a user would be able to group interfaces in his own way. For example, 2-3 levels of groups. Is it technically possible in the current UI framework?

**Comment by jeremystretch** [comment]
@hiddenman have you made any progress on this?

**Comment by hiddenman** [comment]
> @hiddenman have you made any progress on this?

Unfortunately, not yet. We were thinking about moving to Netbox and finally decided to do this. So i hope in the nearest future i will be able to think about it.
If you want to close it then go ahead. Will reopen when i'm ready.
