### ISSUE TITLE
Primary IP icon/badge to highlight them in address lists

### ISSUE THREAD

**Issue by bluikko** [netbox-community/netbox#7009]
### NetBox version

2.11.11

### Feature type

Change to existing functionality

### Proposed functionality

In older NetBox there used to be a "Primary" label next to primary IP addresses when viewing device interface list. This was lost in 2.10/2.11 and it would be useful to have some visual cue to signify primary IP addresses.

#6881 is about implementing labels for IP address roles, re-implementing the old feature. In addition to displaying IP address role labels in address lists, the IP addresses set as primary could have an icon, label or other indicator (such as italic text or whatever).

### Use case

Provide a visual cue to quickly identify primary IP addresses lists like interfaces list.

### Database changes

None.

### External dependencies

None.

**Comment by sdktr** [comment]
Related: https://github.com/netbox-community/netbox/issues/6925
