### ISSUE TITLE
Can't set Virtual interface as Parent for LAG

### ISSUE THREAD

**Issue by Zeawiel** [netbox-community/netbox#7013]
### NetBox version

v2.11.11

### Python version

3.8

### Steps to Reproduce

1. Create a LAG
2. Create Virtual Interface
3. Add Virtual interface as Parent Interface for the LAG.

The LAG doesn't accept the parent with this error : 'Only virtual interfaces may be assigned to a parent interface.'

### Expected Behavior

As Nokia physiology which separate L2 and L3 interfaces.
L2 interfaces are called Ports.
L3 interfaces are called Interfaces.

Interfaces are virtual object where Port is assigned.

In the case of LAG, The Lag is assigned to the Interface instead of Ports.

To follow this logic, I would like to recreate this:
Interface --Parent--> LAG --members--> Ports

I just upgraded from 2.8.5 to 2.11.11 to support this Parent Interface feature.
Maybe I'm doing something wrong ?

Regards,
Zeawiel

### Observed Behavior

![image](https://user-images.githubusercontent.com/6941618/130453925-6b1cebda-a9eb-4ce1-9988-917f7b27e2e4.png)

![image](https://user-images.githubusercontent.com/6941618/130453744-c5d92ace-fc20-4f52-94af-82f204502e61.png)

**Comment by jeremystretch** [comment]
> The LAG doesn't accept the parent with this error : 'Only virtual interfaces may be assigned to a parent interface.'

This is intended behavior: A LAG is a collection of physical interfaces, and cannot have a virtual parent interface.

I'm afraid I don't follow your use case, but please consider [starting a discussion](https://github.com/netbox-community/netbox/discussions/new) with a bit more detail around what you're trying to accomplish. Someone more familiar with your environment may be offer to help.
