### ISSUE TITLE
add DNS name per interface

### ISSUE THREAD

**Issue by rafalfitt** [netbox-community/netbox#7026]
### NetBox version

v2.11.7

### Feature type

New functionality

### Proposed functionality

a new option would be useful: DNS name per interface

In my setup I have separately DNS entries (A + AAAA) assigned to specific addresses (for example 192.168.1.2 + xxxx::102) and registered as ip-1-2.example.com - I want to treat it as a fixed triad.

### Use case

it covers a scenario of the multiple ipv4 + ipv6 addresses assigned to a given interface.
+
MS Windows devices have a "Register this connection's addresses in DNS" option

**Comment by DanSheps** [comment]
If you need more advanced DNS management, I think either custom fields or a custom plugin would be best suited for your use case.

**Comment by jeremystretch** [comment]
> In my setup I have separately DNS entries (A + AAAA) assigned to specific addresses (for example 192.168.1.2 + xxxx::102) and registered as ip-1-2.example.com - I want to treat it as a fixed triad.

You'll need to assign DNS entries to the IPs associated with the interface(s). There's no direct correlation between a DNS record and an interface in the real world.

**Comment by rafalfitt** [comment]
"There's no direct correlation between a DNS record and an interface in the real world."

MS Windows devices have a "Register this connection's addresses in DNS" option - is it the real world?

**Comment by rafalfitt** [comment]
"If you need more advanced DNS management, I think either custom fields or a custom plugin would be best suited for your use case."

well, there is a DNS name field in properties of an address. Adding a similar DNS name field as an interface property is not an advanced management, I hope.

**Comment by jeremystretch** [comment]
> MS Windows devices have a "Register this connection's addresses in DNS" option - is it the real world?

Exactly: it's registering the connections _addresses_, not the connection itself. NetBox supports this to the extent that DNS names can be applied to IP addresses. Anything beyond that is out of scope for the product currently.

**Comment by rafalfitt** [comment]
but the setting and the name granularity is per interface, not per IP address.
