### ISSUE TITLE
Increase cable maximum cable length

### ISSUE THREAD

**Issue by tkeeler42** [netbox-community/netbox#7030]
### NetBox version

v2.11.11

### Feature type

Change to existing functionality

### Proposed functionality

Currently the maximum cable length is 32767, please raise the maximum to a value over 75000. Picture of issue is attached. 
![cable length](https://user-images.githubusercontent.com/89475232/130680519-d94b675c-7bed-4dd5-b081-4dbf56ba3396.jpg)

### Use case

Our organization's documentation and fiber optic test equipment measure singlemode cable lengths in feet. I'd like to reflect that in Netbox.

**Comment by jeremystretch** [comment]
NetBox v3.0.0 will introduce kilometer and mile as unit choices (#5806), as well as support for decimal values (#6154). Together, these should solve your issue.

**Comment by tkeeler42** [comment]
I'd like to store the value as 50641ft vs 9.59 miles. Our equipment only records distance measurements in feet. The ability to store decimal values may help, but kilometer and mile choices will not.

**Comment by tkeeler42** [comment]
Appears to be fixed in version 3.0.0.
