### ISSUE TITLE
Add front/rear port URM connector type

### ISSUE THREAD

**Issue by GubblGubbl** [netbox-community/netbox#7032]
### NetBox version

v2.11.12

### Feature type

Change to existing functionality

### Proposed functionality

Please add the [URM connector](https://de.wikipedia.org/wiki/LWL-Steckverbinder#URM) to the list of available types for front and rear ports.

There are URM-P2, URM-P4 and URM-P8 connectors available.

### Use case

Adding those connectors would improve the possibilities to design a data center with a high density of fibre optics with a minimum of needed space.

### Database changes

None

### External dependencies

None

**Comment by jeremystretch** [comment]
One thing I like about maintaining NetBox is that I keep learning stuff like this exists.
