### ISSUE TITLE
Provide a method for import/export of CircuitTerminations

### ISSUE THREAD

**Issue by nniehoff** [netbox-community/netbox#7036]
### NetBox version

v2.11.2

### Feature type

New functionality

### Proposed functionality

Allow import/export of CircuitTerminations.

### Use case

As a user of NetBox there are times when I take a partial export of production data, for example, cables, circuits and devices and import this into a development install of NetBox for testing.  There are reasons which I can't take a full postgres dump of the production data to this test environment.  I would like to also include CircuitTerminations in this partial export for testing in a development environment.

### Database changes

None

### External dependencies

None

**Comment by jeremystretch** [comment]
This is probably best handled via a custom export template for circuits, or by leveraging the REST API.
