### ISSUE TITLE
Use MAC address for LLDP status

### ISSUE THREAD

**Issue by BegBlev** [netbox-community/netbox#7043]
### NetBox version

v2.10.2

### Feature type

Change to existing functionality

### Proposed functionality

Improve the decision algorithm to decide if a "LLDP Neighbors" line should be green or not.
If, in Netbox, a device interface has a MAC adress configured on it and if Napalm returns a MAC address and if both MAC address match then the line should be green.

### Use case

"LLDP Neighbors" panel is very usefull for checking connectivity between switches and routers as we can easily configure LLDP field content in network equipements. Futhermore, network devices are generally managed by the infrastructure team.
![image](https://user-images.githubusercontent.com/27002365/130942771-fbf16ec4-92bf-423b-86fe-195567779866.png)
Regarding servers (Dell, HP...) this is not the same story. Installing an LLDP daemon is not always possible because the server can be used by an other team or because the installed software does not offer LLDP. Futhermore we generally want to check the cabling before providing the server to someone else as a cabling error could prevent the installation itself.
By using the MAC address, cable checking can be done just after racking and cabling.

**Comment by bitcollector1** [comment]
This would be a great feature for the systems that I can't beat into submission for various reasons. On another note LLDP breaks for me when I use a label in netbox since that label does not exist on the host, would be great if that could get looked at too.  Cheers!

**Comment by BegBlev** [comment]
> On another note LLDP breaks for me when I use a label in netbox since that label does not exist on the host...

@bitcollector1 I don't really understand. Could you please elaborate a bit more?

**Comment by bitcollector1** [comment]
Sonic uses Alias for the actual port number so I wanted to use that as a label to make it easy to see what physical port was being used. I've had to use the description instead since the label interferes with LLDP. 

<img width="1524" alt="Screen Shot 2021-08-30 at 8 44 30 AM" src="https://user-images.githubusercontent.com/50723251/131367085-fa8503a5-b246-4bfe-9691-22b96bcdd453.png">

**Comment by bitcollector1** [comment]
FYI - Here is one of the fixes for the Intel NIC cards......only works for a few types. 

 sudo ethtool --set-priv-flags ens6f0 disable-fw-lldp on

As the ethtool toggle does not seems to be persistent across reboots we’ve setup following udev rule.

/etc/udev/rules.d/10-disable-fw-lldp.rules:

ACTION=="add", SUBSYSTEM=="net", ENV{INTERFACE}=="*", DRIVERS=="i40e", PROGRAM="/usr/sbin/ethtool --set-priv-flags $name disable-fw-lldp on"

**Comment by bitcollector1** [comment]
Today I upgraded to 3.0.2 and I was happy to see that my LLDP was playing nicer than previous versions :) 

<img width="1485" alt="Screen Shot 2021-09-09 at 2 10 11 PM" src="https://user-images.githubusercontent.com/50723251/132763196-6a534222-d532-4160-a6f7-82aacce830ba.png">

**Comment by BegBlev** [comment]
I would like to keep this issue open as it looks important to me.
I foresee to work on it soon.
