### ISSUE TITLE
Add ability to bind vlan in vlan group to site

### ISSUE THREAD

**Issue by kovalev94** [netbox-community/netbox#7057]
### NetBox version

v1.2.0

### Feature type

Change to existing functionality

### Proposed functionality

Now if we have a vlan existing in vlan group, we can bind it to some site, even the site is in vlan group scope.
I think a little bit illogical, because vlan groups exist for organizing your vlans, and you don't want to choose between groups or sites.
We may have an ability to bind vlan to some site. If vlan is member of vlan group with specified scope, you may bind the vlan to some site in the specified scope.

### Use case

Now you should choose between site binding or group binding.
With this feature vlan groups will serve as real way to organize vlans without constraints.

**Comment by DanSheps** [comment]
> v1.2.0

We are no longer actively developing the 1.2.x train, please upgrade to the latest 3.0.1 release.

**Comment by kovalev94** [comment]
Sorry, i was wrong - my version is v2.11.12.
