### ISSUE TITLE
Incorrect bulk deletion

### ISSUE THREAD

**Issue by kovalev94** [netbox-community/netbox#7058]
### NetBox version

v1.2.0

### Python version

3.8

### Steps to Reproduce

I have a vlan group(name QinQ 516 inner vlans) with about 1500 vlan. I want to delete all vlans in this group.
1. Go to vlan groups
2. Go to group in which i want delete all vlans(QinQ 516 inner vlans)
3. Toggle a checkbox near id field
4. Toggle a checkbox which appeared above vlans table(Select all 1492 items mathing query)
5. Press Delete all button and wait for response(too long, around 55 seconds)
In result we have a question- "Confirm bulk Deletion", "Warning: The following operation will delete 7447 VLANs. Please carefully review the VLANs to be deleted and confirm below."
And this is all my vlans from other groups and from global view

### Expected Behavior

Deletion only for vlan within specified vlan group.

### Observed Behavior

Deletion all vlans from NetBox

**Comment by DanSheps** [comment]
@kovalev94 Could you please update us as to whether that is your actual version or not?

**Comment by jeremystretch** [comment]
Closing as there has been no response from the poster.

**Comment by kovalev94** [comment]
Sorry for a long answer. My version is v2.11.12. I use netbox in docker

**Comment by jeremystretch** [comment]
Please upgrade to the latest stable release (v3.0.2).
