### ISSUE TITLE
Issue with prefix filters in 3.0

### ISSUE THREAD

**Issue by trrunde** [netbox-community/netbox#7070]
### NetBox version

v3.0

### Python version

3.8

### Steps to Reproduce

Click prefixes, select filters and apply the following filters:
status: Container
Role: some prefix role you have, I used openvpn
mask-length: 23

Apply filter and you will get a TypeError, python is expecting a string but getting an integer

### Expected Behavior

Filter to be applied

### Observed Behavior

The complete exception is provided below:

<class 'TypeError'>

sequence item 1: expected str instance, int found

Python version: 3.8.6
NetBox version: 3.0.0
![Screenshot-20210830214313-655x496](https://user-images.githubusercontent.com/1595396/131395829-d8a951e6-da5a-460e-a6ee-d8fa1321d45f.png)

**Comment by trrunde** [comment]
I also tried to apply a filter where I only filters on Status: Container OR role: openvpn
it gives same TypeError with only one filter applied to.

**Comment by rodvand** [comment]
It seems to be the "mask length" causing the issue. Can reproduce with only selecting a mask length as filter on my test instance, as well as the beta NetBox site (https://beta-demo.netbox.dev/ipam/prefixes/?mask_length__lte=&q=&within_include=&family=&mask_length=4&is_pool=&mark_utilized=&present_in_vrf_id=)
