### ISSUE TITLE
Unable to assign Child Interfaces to the Parent LAG

### ISSUE THREAD

**Issue by Daniel-Dietz** [netbox-community/netbox#7073]
### NetBox version

v3.0.0

### Python version

3.8

### Steps to Reproduce

1 Create a (Parent)Device with minimum two Device Bays
2 Create two (Child) Devices, with each at least one Interface
3 Add Parent to Rack and add Childs to Device Bay
4 Create LAG Interface in Parent
5 Try to add Child-Interfaces to LAG

### Expected Behavior

To be able to add the Child Interfaces to the Parent LAG

This is a required function for example fully modular Switches, as the Parent does not have any interfaces on its one. LAGs are not limited to one Child-Module, but for redundancy are split between two or more Modules.

### Observed Behavior

The Parent LAG is not available to be selected

**Comment by jeremystretch** [comment]
LAG membership cannot span multiple devices. All member interfaces must exist on the same device. (Child devices do not share a control plane.)
