### ISSUE TITLE
Unpinned menu won't fly out in the Devices or Circuits UI

### ISSUE THREAD

**Issue by jhammond-git** [netbox-community/netbox#7075]
### NetBox version

v3.0.0

### Python version

3.8

### Steps to Reproduce

1. Unpin fly-out menu.
2. Navigate to Devices (/dcim/devices/).
3. Try to access the collapsed menu

### Expected Behavior

Menu will fly out (expand to full width) and be clickable.

### Observed Behavior

Menu stays in collapsed form and none of the links are active other than the "home" link at the top (the Netbox icon).

**Comment by jhammond-git** [comment]
As someone pointed out this may be related to custom fields, as Devices have custom fields of "Support Provider" and "Support End Date".

**Comment by thatmattlove** [comment]
I can reproduce this under the following circumstances:

1. Custom Field _with a space_ in the name
2. Custom Field must be of type 'Selection'

The issue appears related to [this](https://github.com/netbox-community/netbox/blob/bf05bc298656270ce28a17cc49e1697b6ce8c7fa/netbox/project-static/src/select/static.ts#L7) and [this](https://github.com/netbox-community/netbox/blob/bf05bc298656270ce28a17cc49e1697b6ce8c7fa/netbox/project-static/src/select/api/apiSelect.ts#L718), i.e.

```typescript
const label = document.querySelector(`label[for=${this.base.id}]`) as HTMLSelectElement;
```

While we could implement a workaround in the backend to enforce whitespace removal/replacement, I think the better solution would be to ensure the selector wraps the ID in quotes, for example:

```typescript
const label = document.querySelector(`label[for="${this.base.id}"]`) as HTMLSelectElement;
```
