### ISSUE TITLE
Enable Child Interfaces to assigned to Parent LAG

### ISSUE THREAD

**Issue by Daniel-Dietz** [netbox-community/netbox#7077]
### NetBox version

v3.0.0

### Feature type

Change to existing functionality

### Proposed functionality

Allow LAG Interfaces to have Child Interfaces as members.

See Closed bug #707

### Use case

This is a required function for example fully modular Switches, as the Parent does not have any interfaces on its one. LAGs are not limited to one Child-Module, but for redundancy are split between two or more Modules.

**Comment by jeremystretch** [comment]
As I explained yesterday in #7013, this limitation is intentional, as child devices do not share a control plane. Switch line cards should not be modeled as child devices; this is clearly called out [in the documentation](https://netbox.readthedocs.io/en/stable/models/dcim/devicebay/).
