### ISSUE TITLE
Mouseover image preview in rack view and other views with images doesn't work anymore

### ISSUE THREAD

**Issue by cs-1** [netbox-community/netbox#7080]
### NetBox version

v3.0.0

### Python version

3.8

### Steps to Reproduce

1. Upload image to an existing rack.
2. Hover mouse over the link to the image in the rack view.

### Expected Behavior

A scaled-down version of the image should appear during mouseover. (Works in v2.11.12 and earlier.)

### Observed Behavior

No preview of the image is shown when doing a mouseover.

This behaviour can also be observed in other views (e. g. "site") where you can upload images.

Thank you very much for the great v3.0.0 release, it looks fantastic.  Also thank you for looking into this, the mouseover preview function is very useful to find the correct image (we use the images to document certain aspects of a rack).

**Comment by thatmattlove** [comment]
I'll be honest, I had no idea this feature existed before 🙂 I'll see what I can do to get it added back.

**Comment by cs-1** [comment]
> I'll be honest, I had no idea this feature existed before 🙂 I'll see what I can do to get it added back.

Thanks, Matt. It's a very useful feature. For documentation purposes we have plenty of images of racks. However, it's quite hard to name the images in a way that establishes clearly what they show. With the mouseover preview it was very easy to pick the image you wanted to look at in detail. Thanks again for looking into this.
