### ISSUE TITLE
Changelog ObjectType does not populate with q filter

### ISSUE THREAD

**Issue by sdktr** [netbox-community/netbox#7089]
### NetBox version

v3.0.0

### Python version

3.8

### Steps to Reproduce

1. Open the filter tab of: https://demo.netbox.dev/extras/changelog/
2. Click 'object type filter'
3. Enter search query: ipam

### Expected Behavior

Result of the dropdown is filtered to IPAM types
![image](https://user-images.githubusercontent.com/19833687/131489887-1cc8eeba-5e97-4900-a55e-9855c3d240b7.png)

### Observed Behavior

No results are displayed. The workaround is to first manually scroll down untill the list is fully populated. After that it can be searched through.
![image](https://user-images.githubusercontent.com/19833687/131489719-6d3ce3f9-5d78-4cbc-8095-4edf19beb6d9.png)

**Comment by jeremystretch** [comment]
This is a general issue with API-backed select fields it seems. I thought we had fixed this recently, but I've confirmed it remains an issue. The selection list _does_ automatically expand when the user reaches the end, however searching for an option that has not yet been loaded is broken.

**Comment by DanSheps** [comment]
This actually looks like the changelog endpoint is not properly filtering using the q filter.

/api/extras/content-types/?brief=true&q=ipam

Returns all entries

**Comment by DanSheps** [comment]
```
  q = django_filters.CharFilter(
        method='search',
        label='Search',
    )

    def search(self, queryset, name, value):
        if not value.strip():
            return queryset
        return queryset.filter(
            Q(app_label__icontains=value || model__icontains=value)
        )
```

Will probably fix this, will do some testing

**Comment by thatmattlove** [comment]
That may be part of it, but not all of it. There's also an issue with how APISelect is handling pagination, so a similar issue occurs when the user reaches the bottom of a list.

**Comment by DanSheps** [comment]
I would say this one is specific to changelog though.

I think that one is #7081, I will add you onto that one.  Gonna take this one as I already have the filter fix.
