### ISSUE TITLE
Table Configuration generate 404 when using BASE_PATH=

### ISSUE THREAD

**Issue by ziggekatten** [netbox-community/netbox#7091]
### NetBox version

v3.0.0

### Python version

3.9

### Steps to Reproduce
Set up an Netbox instance that uses the BASE_PATH variable

1. Click on "Devices"
2. Click on "Configure Table"
3. Select any value in "Available Columns" and click "Add"

### Expected Behavior

The column should be added to "Selected Column"

### Observed Behavior

"Error Updating Table Configuration, 404 Page not found" in a red box.

This also happens when pressing reset button.

Using developer tools in Chrome i can see that URL is missing my BASE_PATH (netbox-dev). in effect, netbox is running at: https://nb.local.dev/netbox-dev/

The URL that generates the 404 are: https://nb.local.dev/api/users/config/

But should be: https://nb.local.dev/netbox-dev/api/users/config/  in essence missing the BASE_PATH

**Comment by jeremystretch** [comment]
@thatmattlove could you take a look at this? Seems like the API request for the table config form is unaware of `BASE_PATH`. There may be some other instances of this elsewhere in the application too.
