### ISSUE TITLE
Tagged VLANs Filter Clears Previous Selection

### ISSUE THREAD

**Issue by cjwagz** [netbox-community/netbox#7099]
### NetBox version

v3.0.0

### Python version

3.7

### Steps to Reproduce

Create/Edit Interface
Set 802.1Q Mode to Tagged
Click Tagged VLANs and select a VLAN
Click Tagged VLANs box again to add a second VLAN
Type in the Filter box and the first VLAN is removed from the Tagged VLANs box.

### Expected Behavior

Filtering to add another VLAN to the Tagged VLANs should not remove any added VLANs on the interface, only filter the selection list.

### Observed Behavior

Previously selected VLAN is removed from the Tagged VLANs selection box when filtering for another VLAN.

**Comment by thatmattlove** [comment]
Duplicate(ish) of #7081 - should be fixed by 093a86b
