### ISSUE TITLE
Represent Servers which are attached to External Storage

### ISSUE THREAD

**Issue by salman79uk** [netbox-community/netbox#7100]
### NetBox version

v3.0.0

### Feature type

New functionality

### Proposed functionality

Hi,

It doesn't appear that there is a currently a way to show the servers which are attached to external storage.

What I would like to propose is a way to show this, in particular on the rack layout page. Essentially, what this needs is a line from a server to another device on the rack diagram page.

Can you advise if this might be possible or another way we can represent this information on netbox.

Many thanks,

### Use case

This would allow the users to visualize via the rack layout page all those servers which are attached to external storage.

**Comment by jeremystretch** [comment]
The rack elevation view is exactly that: a visual representation of the arrangement of devices within a rack. It intentionally does not show _any_ connections, so I'm afraid this feature request must be declined.
