### ISSUE TITLE
Uncaught Exceptions from within `ModelViewSet` are returned as HTML

### ISSUE THREAD

**Issue by thatmattlove** [netbox-community/netbox#7109]
### NetBox version

v3.0.0

### Python version

3.8

### Steps to Reproduce

This can be tricky - something needs to done to trigger an uncaught exception from within `ModelViewSet`. I suppose you could add this...

```python
raise Exception('test')
```

...[here](https://github.com/netbox-community/netbox/blob/d743dc160ab701cb6b92579b5ff164b5ec2eaa9b/netbox/netbox/api/views.py#L199), and then make an API request.

### Expected Behavior

At a minimum, I think we should append useful information to the error. Ideally, however, no HTML would be returned to an API client.

### Observed Behavior

The returned value is something along the lines of:

```json
{
  "error": "<giant unreadable HTML string>"
}
```

**Comment by jeremystretch** [comment]
Any exceptions raised by an API view should get caught and handled by [ExceptionHandlingMiddleware](https://github.com/netbox-community/netbox/blob/f63dcb1f08d85c59eb8b995a0293400036dc83dd/netbox/netbox/middleware.py#L103) (unless debugging is enabled). I can confirm that this works as expected when intentionally raising an exception in `ModelViewSet.dispatch()`.

Can we just extend the middleware to evaluate the request type and act accordingly? I.e. invoke `rest_api_server_error()` only if it's an API request _and_ JSON content was requested?
