### ISSUE TITLE
When editing existing device sites and device type are unselected

### ISSUE THREAD

**Issue by Razerlikes** [netbox-community/netbox#7116]
### NetBox version

v3.0.0 (after Upgrade from 2.11.12)

### Python version

3.8

### Steps to Reproduce
Use any modern browser

1. Look for device you want to edit
2. Open device page
3. click edit
4. Save

(couldn't reproduce in demo.netbox.dev)
### Expected Behavior

All already configured fields, like device type and site, as they are required for a device, should be prepopulated with configured values

### Observed Behavior

Device Type and Site is empty when editing an existing device. When trying to save the device, netbox prompts to fill in the required fields.

**Comment by Razerlikes** [comment]
It's not the only instance where that happens. Also when you add an interface to a device, it doesn't prepopulate the device. Is it worth a separate issue?

**Comment by sdktr** [comment]
Did you try a forced clear of your browser cache? If it can't be reproduced on demo.netbox.dev it leans towards 'something' local?

**Comment by Razerlikes** [comment]
I tried different browsers, which shouldn't share their cache. Maybe there's still some cache on the server side?

**Comment by Razerlikes** [comment]
Reapplying the upgrade.sh and rebooting did the trick... Which I probably should've done first :D
