### ISSUE TITLE
Small VM ressources display bugs

### ISSUE THREAD

**Issue by EHRETic** [netbox-community/netbox#7117]
### NetBox version

v3.0.0

### Python version

3.9

### Steps to Reproduce

Enter information in VM hardware specs and go back to VM main page

### Expected Behavior

- VM vCPU should be displayed with an integer
- Only one unit should be picked (but GB would be nice if memory size is a multiple of 1024)

### Observed Behavior

I noticed when entering the different VM resources info that:
- VM vCPU number is with 2 decimals, I don't think it is necessary
- VM memory size is displayed with 2 units as I entered 2048 MB 

![image](https://user-images.githubusercontent.com/28634810/131651167-80c4fd3b-9b7b-4635-9823-60f569258d93.png)

Not something dramatic of course, but I noticed it, so I pass you the info! 😉

**Comment by jeremystretch** [comment]
Thank you for submitting this issue, however it appears that this topic has already been raised. Please see issue #7083 for further discussion.

**Comment by EHRETic** [comment]
No problem, I didn't see it but if you can still transform CPU count to an integer... 😊
