### ISSUE TITLE
Add service expiration date to circuit model

### ISSUE THREAD

**Issue by iMIMIC** [netbox-community/netbox#7120]
### NetBox version

v2.11.10

### Feature type

Change to existing functionality

### Proposed functionality

**Circuit Contract Management**

The ability to add an expiry date / define contract length of a Circuit **(bonus points)** = display days to expiry.
Ability to put a notification for renewals - i.e. 90 day Notice Period

### Use case

When users of NetBox visit or review a site they will have visibility of the circuit in full i.e. circuits that are nearing end of contract and need renewing or cancelling.

![NetBox-FR](https://user-images.githubusercontent.com/89916008/131670622-769466bd-9ac8-4b90-b2a5-b6c3220dcc95.jpg)

### Database changes

New Field 'Expiry Date' - Date Value
Lookup 'Expiry Date' minus todays date.

**Comment by DanSheps** [comment]
> ### Database changes
> _No response_

Pretty sure you need something here, please update and resubmit.

A detailed implementation plan would also be nice.

**Comment by jeremystretch** [comment]
10/10 on the screenshot though :smile:

**Comment by iMIMIC** [comment]
@DanSheps my apologies, newbie here / will rectify asap. 

@jeremystretch agreed! I/we have been previously tracking this kind of information in excel but are now in the process of documenting everything in NetBox.

![Netbox-FR01](https://user-images.githubusercontent.com/89916008/131691322-4b909a43-b0c6-4ebf-ad27-ec76760cfc8d.png)

I would keep both the Start & Expiry dates as static date values but to get the third (days remaining) a lookup of the expiry date minus todays date.

> 10/10 on the screenshot though

MS Paint is life 😄

**Comment by luhaijiao** [comment]
I would expect this kind of contract management for all devices if possible :-)

**Comment by jeremystretch** [comment]
@luhaijiao that would require a separate FR as it's beyond the scope of the proposal here.

**Comment by ryanmerolle** [comment]
Not trying to pile into this request, but just throwing out some of my common fields for circuits.  COuld be a good discussion for other possible FRs OR just nice for people to take inspiration from for their own custom fields.

Circuit Custom Fields I use:

- Term End Date (basically this FR field)
- Order Date
- Order ID 
- Committed latency
- Decommission Date (Disconnect Date either passed and status is decommissioned OR upcoming disconnec)
- Current Term (useful if you renegotiated circuits - Would be a number of months 12, 24, 36 OR month-to-month)
- Current Term Start date (useful if you renegotiated circuits)
- MRC (Monthly reoccurring cost)
- NRC (non-reoccurring cost / install fee)
