### ISSUE TITLE
Attribute Error when accessing Child Prefixes from Parent

### ISSUE THREAD

**Issue by elmer-dexter** [netbox-community/netbox#7126]
### NetBox version

v3.0.0

### Python version

3.8

### Steps to Reproduce

- In the demo site. 
- Create a new unused prefix
- open the child prefixes from the tab.

This can also be re-produced using a fresh version of netbox-docker 1.3.0 set for netbox 3.0.0

### Expected Behavior

The prefix list should have been generated

### Observed Behavior

Server Error
There was a problem with your request. Please contact an administrator.

The complete exception is provided below:

<class 'AttributeError'>

'str' object has no attribute 'available_columns'

Python version: 3.8.10
NetBox version: 3.0.0
If further assistance is required, please post to the NetBox mailing list.

Home Page

**Comment by jeremystretch** [comment]
Thank you for submitting this issue, however it appears that this topic has already been raised. Please see issue #7072 for further discussion.
