### ISSUE TITLE
Bulk edit of interfaces to add VLANs in VLAN group does not work

### ISSUE THREAD

**Issue by beatjoerg** [netbox-community/netbox#7129]
### NetBox version

V3.0.0.0

### Python version

3.9

### Steps to Reproduce

1. Do a bulk edit and try to assign a VLAN that is part of a VLAN Group (and not associated to a site)
2. The following API Call is done: /api/ipam/vlans/?brief=true&site_id=1, which does not select the VLAN in a VLAN group

### Expected Behavior

VLANs belonging to a VLAN Group need to be shown too

### Observed Behavior

VLANs in a VLAN Group not shown

**Comment by DanSheps** [comment]
Matt, I can take a stab at this one if you don't have the time.

**Comment by DanSheps** [comment]
On the main interfaces table, not from a device itself.

I will be honest, not sure of the best technical way to do this.

**Comment by beatjoerg** [comment]
Probably it is also related to #7124, as parameters for API calls survives requests.
I just tried it with the current dev version (8ede7a9297c19c88d8c8481d2fc2aa3cdaf3c269).
The API Call even from the interfaces tab generates wrong fiters if you do an edit first on device 1 and then on device 2. So the steps to reproduce will vary what you did before.

Just also noted that in bulk edit (form interface tab of a device) the UI selects automatically the first available VLAN, but that seems to be another story.

**Comment by DanSheps** [comment]
> I just tried it with the current dev version ([8ede7a9](https://github.com/netbox-community/netbox/commit/8ede7a9297c19c88d8c8481d2fc2aa3cdaf3c269)).

This appears fixed in 3.0.1, if not, please re-open #7124

**Comment by jeremystretch** [comment]
Closing this out as it appears to have been resolved in a more recent release.
