### ISSUE TITLE
editing IP already associated with device does not auto-fill device/interface details

### ISSUE THREAD

**Issue by michaeldialpad** [netbox-community/netbox#7132]
### NetBox version

v3.0.0

### Python version

3.7

### Steps to Reproduce

1 - navigate to a device
2 - click on interfaces
3 - click on the IP Address associated with an interface
4 - click edit
5 - device and interface are not populated with existing values

### Expected Behavior

when editing an attribute on existing device, it should prepopulate existing values

### Observed Behavior

existing values are not prepopulated in the edit form

**Comment by michaeldialpad** [comment]
I am able to repro the issue in 3.0.1

**Comment by michaeldialpad** [comment]
![image](https://user-images.githubusercontent.com/46693826/131732940-71840428-4438-4bbe-943a-ab0a8e89e20a.png)

**Comment by jeremystretch** [comment]
Try force-refreshing your browser. If that still doesn't work, please elaborate on the steps provided above so that someone else can reproduce the issue, beginning with the creation of the interface.
