### ISSUE TITLE
Device names displayed in rack view don't respect left rack boundary

### ISSUE THREAD

**Issue by cs-1** [netbox-community/netbox#7134]
### NetBox version

v3.0.1

### Python version

3.8

### Steps to Reproduce

1. Create a rack.
2. Create a device without device front image that has a lengthy Vendor, Device Type and name.
3. Add the device to the rack.

### Expected Behavior

Long device names are truncated at rack boundaries when rack is rendered.

### Observed Behavior

Long device names print over / under left rack boundary when being rendered (see screenshot).
![screenshot](https://user-images.githubusercontent.com/12844146/131797980-480eb374-ffeb-414a-a9cc-24aff65d8b2d.png)

**Comment by jeremystretch** [comment]
I'm not able to replicate this. Device labels are cut off as expected. What browser are you using?

**Comment by jeremystretch** [comment]
Closing this as there has been no response from the reporter.

**Comment by cs-1** [comment]
Hi Jeremy, I'm terribly sorry, I completely missed your response.

You actually did reproduce the bug. If you look closely at your screenshot you can actually see the white characters between the 41 and 42. It's very visible if you switch to dark mode.

**Comment by jeremystretch** [comment]
Putting this on hold until #6879 is addressed (to avoid overlap in work).
