### ISSUE TITLE
export & import data via CSV doesn't work (netbox v3.0.0 doker)

### ISSUE THREAD

**Issue by thedauke** [netbox-community/netbox#7139]
### NetBox version

v3.0.0 (2d412f92f34e)

### Python version

3.8

### Steps to Reproduce

1. (first server) click to export -> all data
2. save csv file
3. (second server) click into import -> CSV file -> choose csv file -> submit 

### Expected Behavior

transfer data from the first server with netbox to another server with also netbox. (I'm currently using the docker version of netbox).

### Observed Behavior

no even error message, just nothing happend

**Comment by izabela1337** [comment]
Similar issue here. For me it just refreshes the page. Tried with and without nginx proxy.
Python ver: 3.9.5, podman container installation

**Comment by jeremystretch** [comment]
Please revise your original post above to provide more detail. It is not clear from your description where the failure is occuring, or even what model your are attempting to export.

**Comment by thedauke** [comment]
okay, thank u for the feedback. Actually, no matter what model or section, any data can't to be imported via csv file

**Comment by opericgithub** [comment]
i can confirm this. i tried exporting all tenants from v2 into csv, and then importing them into v3, nothing happens.

**Comment by DanSheps** [comment]
I am going to close this, I can reproduce this, however...  You haven't been able to follow the instructions to provide a valid reproduction.
