### ISSUE TITLE
Error in removing primary IP from device

### ISSUE THREAD

**Issue by miaow2** [netbox-community/netbox#7140]
### NetBox version

v3.0.1

### Python version

3.8

### Steps to Reproduce

1. Start editing IP address which is assigned to an interface and is the primary IP of the device.
2. delete interface in `Interface` field
3. uncheck `Make this the primary IP for the device/VM`
4. press `Save`

### Expected Behavior

IP should be removed from interface and primary ip

### Observed Behavior

Got an error: IP address is primary for device *device-name* but not assigned to it!

**Comment by jeremystretch** [comment]
We might be able to refactor the IPAddressForm logic inside `save()` to clear the primary IP assignment from the parent device/VM prior to saving the IP address.

As a workaround, you can uncheck "Make this the primary IP" without clearing the interface assignment first, or disassociate the IP address as primary by editing the device or VM directly.

**Comment by Carbenium** [comment]
Linking for reference: https://github.com/netbox-community/netbox/issues/7074
