### ISSUE TITLE
When create/editing Device with selected Manufacturer not able to select Platform without Manufacturer.

### ISSUE THREAD

**Issue by amotif** [netbox-community/netbox#7147]
### NetBox version

v3.0.1

### Python version

3.8

### Steps to Reproduce

1. create Platform (e.g. Ubuntu) without Manufacturer.
2. create Device with Manufacturer (e.g. HPE).
3. when editing Device not able to select Platform (e.g. Ubuntu) without Manufacturer.

### Expected Behavior

Allowed to select Platform without Manufacturer to Device with selected Manufacturer as it works in version 2.11.12.

### Observed Behavior

When editing Device with selected Manufacturer not able to select Platform without Manufacturer.

**Comment by thatmattlove** [comment]
Hi,

This has actually already been fixed in `develop` via 113358f, which was raised via #7148. I've confirmed that it's no longer an issue with that fix in place. v3.0.2 will contain the fix.

Thanks!
