### ISSUE TITLE
Device Type images can not be deleted via UI

### ISSUE THREAD

**Issue by m2martin** [netbox-community/netbox#7153]
### NetBox version

v3.0.1

### Python version

3.9

### Steps to Reproduce

1. Create a Device Type or edit an existing one and add a front and/or rear image
2. Device Type is created or edited successfully
3. Edit Device Type in order to delete/remove the front/rear image

### Expected Behavior

I expect a link or any other control element to delete the image or to mark the image to get deleted on save.

### Observed Behavior

No control element to delete an image is visible.
Currently, the only way to remove/delete images seems to be nbshell.

**Comment by jeremystretch** [comment]
I just want to call out that we've had a similar issue in the past (#5595), although this seems to be unrelated.

It looks like we lost the display and deletion functionality when the form widget was updated for [Bootstrap 5](https://getbootstrap.com/docs/5.0/forms/form-control/#file-input).

**Comment by m2martin** [comment]
> It looks like we lost the display and deletion functionality when the form widget was updated for [Bootstrap 5](https://getbootstrap.com/docs/5.0/forms/form-control/#file-input).

I guess, too.
