### ISSUE TITLE
Netbox 3.0.1 doesn't follow system colour theme

### ISSUE THREAD

**Issue by chonty** [netbox-community/netbox#7161]
### NetBox version

v3.0.1

### Python version

3.7

### Steps to Reproduce

1. Log into Netbox and ensure the colour preference is not set in user preferences
2. Change system theme
3. Refresh page.  If your system theme went from light>dark, you'll see Netbox very briefly displayed in the dark theme before switching back to light.

### Expected Behavior

Netbox's colour theme should change to follow the system theme

### Observed Behavior

System theme is only followed one time after netbox-color-mode is deleted after which it will stick.  When stepping through the Javascript, it reaches line 45 where the theme flashes dark then back to light:
![image](https://user-images.githubusercontent.com/20431435/131939207-4f4a4b73-d521-4ffb-8ba0-e56d9d755f67.png)

Tested on Firefox 91 + Edge on Windows 10 and Safari on iOS 14.7.

**Comment by thatmattlove** [comment]
This is resolved as part of the fix for 7373, 14b065c
