### ISSUE TITLE
Failed to load resource, 404 while using BASE_PATH

### ISSUE THREAD

**Issue by silkofix** [netbox-community/netbox#7162]
### NetBox version

v3.0.1

### Python version

3.9

### Steps to Reproduce

1. Go to IPAM -> VLANs
2. Click "Add"

### Expected Behavior

Get all of searching fields like: "Tags", "Role", "VLAN Group"

### Observed Behavior

I used BASE_PATH = 'netbox/'
Get a red box and api error. 
netbox.js:8 GET https://localhost/netbox/netbox/api/ipam/roles/?brief=true 404 (Not Found)
I think the problem is in the link being created, it is duplicated.

When i removed BASE_PATH and use netbox like https://localhost/. 
Link be like: https://localhost/api/ipam/roles/?brief=true and no problems further

**Comment by ziggekatten** [comment]
We use BASE_PATH and do NOT have this problem i 3.0.1.

**Comment by silkofix** [comment]
> We use BASE_PATH and do NOT have this problem i 3.0.1.

ye i was reading #7091 :) But... Same problem was on 3.0.0
Maybe its problem with my proxy, but i don't think so... This problem was not on v2.11.12

**Comment by DanSheps** [comment]
Could anyone else confirm if this is an issue or not?

**Comment by jeremystretch** [comment]
Yes, this is a problem on the current `develop` branch.

**Comment by jeremystretch** [comment]
Looks like this is a regression introduced under #7091. I think I have it sorted.
