### ISSUE TITLE
Filter on multiple values for custom fields

### ISSUE THREAD

**Issue by milonline-eu** [netbox-community/netbox#7163]
### NetBox version

v3.0.1 - Demo instance

### Python version

3.9

### Steps to Reproduce

Create a Custom field, Type: Multiple selection, Assigned models: DCIM > device, Choices: 1,2
Create a device with custom field set to 1
Create a device with custom field set to 2
Go to filter of devices, choose 1 and 2 for the custom field.

Tested on demo v3.0.1:
https://demo.netbox.dev/dcim/devices/?q=&asset_tag=&mac_address=&has_primary_ip=&virtual_chassis_member=&console_ports=&console_server_ports=&power_ports=&power_outlets=&interfaces=&pass_through_ports=&local_context_data=&cf_Test+multiselect+filter=1&cf_Test+multiselect+filter=2

There are two devices with custom field "Test multiselect filter":
https://demo.netbox.dev/dcim/devices/88/ "Test multiselect filter" set to 1
https://demo.netbox.dev/dcim/devices/89/ "Test multiselect filter" set to 2

Filtering "Test multiselect filter" for "1" and "2" shows only device id 89 (cf_Test+multiselect+filter=1&cf_Test+multiselect+filter=2). I would expect both devices 88 and 89 to be shown.

### Expected Behavior

both devices to be shown

### Observed Behavior

second device shown only

**Comment by DanSheps** [comment]
This is consistent with 2.11.x, therefore not a bug.

I suspect, but I haven't looked into it, custom fields are only set to filter a single ID and as such only take the last ID.

**Comment by jeremystretch** [comment]
Per the bug report template:

> Additionally, do not rely on the demo instance for reproducing suspected bugs, as its data is prone to modification or deletion at any time.

You need to provide detailed steps that someone else can follow to reproduce the suspected bug. You haven't even specified the NetBox version.

**Comment by milonline-eu** [comment]
v3.0.1 specified and detailed steps to reproduce it in the description now

**Comment by jeremystretch** [comment]
> This is consistent with 2.11.x, therefore not a bug.

This needs to be resubmitted as a feature request.

**Comment by milonline-eu** [comment]
Just tested on 3.1-beta1 and it works fine.
