### ISSUE TITLE
Configure table doesn't work for virtual machines

### ISSUE THREAD

**Issue by luhaijiao** [netbox-community/netbox#7166]
### NetBox version

v3.0

### Python version

3.7

### Steps to Reproduce

1. click 'configure table' on 'Virtual Machines' page,
2.  User can not either 'Add' or 'Remove' columns.

### Expected Behavior

User shall be able to add or remove columns for the table

### Observed Behavior

No response while user click 'add' or 'remove' button and the following error was noted in web browser console

netbox.js:17 Uncaught DOMException: Failed to execute 'querySelector' on 'Document': 'label[for=id_cf_App Owner]' is not a valid selector.
    at Jg (http://172.17.3.100/static/netbox.js:17:1490)
    at Zg (http://172.17.3.100/static/netbox.js:17:1782)
    at HTMLDocument.kv (http://172.17.3.100/static/netbox.js:17:17674)

**Comment by thatmattlove** [comment]
Please upgrade to v3.0.1 - this was fixed as part of #7075
