### ISSUE TITLE
Inconsistent font type and size of device serial number

### ISSUE THREAD

**Issue by luhaijiao** [netbox-community/netbox#7167]
### NetBox version

v3.0.0

### Python version

3.7

### Steps to Reproduce

1. click any device details
2. Note the serial number of deivce has smaller and different font

![image](https://user-images.githubusercontent.com/19298674/132027112-e6d2a0a1-5147-4ae6-a1ab-8cc8d2844936.png)

### Expected Behavior

consistent font type and size for devie details

### Observed Behavior

inconsistent font type and size

**Comment by thatmattlove** [comment]
The serial number was intentionally rendered as a monospace font for better readability of similar characters. For example: O0, lI, S5 — `O0` `lI` `S5`. I see no reason to change this, unless anyone else wants to chime in.

**Comment by DanSheps** [comment]
Serial Number uses <code>

Looks like the following is set for code:

```
font-family: var(--bs-font-monospace);
```

whereas span/other elements has


```
font-family: var(--bs-font-sans-serif);
```

I just saw Matt replied.  Going to mark this as "feature" and under review.

**Comment by jeremystretch** [comment]
I personally would prefer to keep the field consistent with the others (e.g. use a sans-serif font).
