### ISSUE TITLE
Importation of CSV File fails

### ISSUE THREAD

**Issue by DanSheps** [netbox-community/netbox#7169]
### NetBox version

v3.0.1

### Python version

3.9

### Steps to Reproduce

1. Perform a CSV export from prefixes or create a CSV file for importation.  Some data grooming may be required (prepared data: [netbox_prefixes.csv](https://github.com/netbox-community/netbox/files/7107309/netbox_prefixes.csv))
2. Go to IPAM > Prefixes > Import
3. Select "CSV file"
4. Choose the prepared CSV file
5. Select import

### Expected Behavior

Data should import successfully

### Observed Behavior

If data textbox is left as default, page will reload

If data textbox was cleared, page will reload with error

If data textbox was populated with additional data, import will succeed with only the entered data (CSV file is ignored)

Related: #7139

**Comment by jeremystretch** [comment]
The root cause here was that `enctype="multipart/form-data"` was omitted from the form element. I also took the opportunity to clean up the form a bit.
