### ISSUE TITLE
setting limit=0 param in api request still returns paginated results

### ISSUE THREAD

**Issue by michaeldialpad** [netbox-community/netbox#7171]
### NetBox version

v3.0.1

### Python version

3.7

### Steps to Reproduce

1. navigate to https://<netbox server>/api/circuits/circuits/?limit=0
2. results are still paginated
3. 

### Expected Behavior

results returned should not be paginated when passed limit=0

### Observed Behavior

 results are still paginated

**Comment by jeremystretch** [comment]
This behavior is intended when `MAX_PAGE_SIZE` is non-zero. NetBox will only return the lesser of either the `limit` query parameter or the configured maximum page size. Please see the [`MAX_PAGE_SIZE`](https://netbox.readthedocs.io/en/stable/configuration/optional-settings/#max_page_size) configuration parameter.

**Comment by michaeldialpad** [comment]
I have tried seting MAX_PAGE_SIZE to None and to 0 in configuration.py and restarted netbox service and still the same result

**Comment by michaeldialpad** [comment]
I now set PAGINATE_COUNT to an obscenely high number which prevented pagination but not sure if this is intended.
