### ISSUE TITLE
demo.netbox.dev cable trace error

### ISSUE THREAD

**Issue by ryanmerolle** [netbox-community/netbox#7175]
### Discussed in https://github.com/netbox-community/netbox/discussions/7173

<div type='discussions-op-text'>

<sup>Originally posted by **devon-mar** September  3, 2021</sup>
I was playing around with v3.0 on `demo.netbox.dev` and it seems that the cable trace button is broken for devices from `netbox-demo-data`. I didn't open an issue because I'm not sure if this has to do with NetBox or the demo data. 

### NetBox version

v3.0.1

### Python version

3.8.10

### Steps to reproduce:
1. Open the interface tab on one of the demo devices (eg. `dmi01-akron-sw01`)
2. Click the blue cable trace button on one of the interfaces
3. The following error occurs
```
<class 'KeyError'>

35

Python version: 3.8.10
NetBox version: 3.0.1
```

I also can't delete the cable and recreate it as I get a unique constraint violation:
```
<class 'django.db.utils.IntegrityError'>

duplicate key value violates unique constraint "dcim_cablepath_origin_type_id_origin_id_41b6f814_uniq"
DETAIL:  Key (origin_type_id, origin_id)=(27, 171) already exists.


Python version: 3.8.10
NetBox version: 3.0.1
```</div>

example link https://demo.netbox.dev/dcim/interfaces/170/trace/

**Comment by DanSheps** [comment]
Is this only an issue with demo-data @devon-mar

**Comment by devon-mar** [comment]
> Is this only an issue with demo-data @devon-mar?
> 
> IF you put in data is it fine?

It seems like only interfaces that had a cable connection IN the demo data are affected. I can successfully add a cable to one of the demo device's interfaces that didn't already have a cable connected to it.

**Comment by ryanmerolle** [comment]
Then we can probably move this to demo data repo
