### ISSUE TITLE
Connection type selector under Device>Interfaces can only show selections that can overlap the size of the table

### ISSUE THREAD

**Issue by tombe75** [netbox-community/netbox#7179]
### NetBox version

v3.0.1

### Python version

3.8

### Steps to Reproduce

1. Go to https://demo.netbox.dev/dcim/devices/
2. Clone or edit existing device with interfaces
3. Remove all but one or two interfaces
4. Try to add a connection with the connector button, on one interface while still in the interfaces list view

### Expected Behavior

I expect to see the complete selection menu.
<img width="184" alt="bild" src="https://user-images.githubusercontent.com/50360366/132088441-d988afa1-4074-4ee2-b569-6fa3491d4b67.png">

### Observed Behavior

I see only the number of choices that can fit overlapping the list table.
This is only a problem for interfaces, not front ports, rear ports, console, power
<img width="589" alt="Skärmavbild 2021-09-04 kl  10 25 11" src="https://user-images.githubusercontent.com/50360366/132088476-47577a7a-bee2-44fc-8a5a-c7cc8cd9a4a1.png">

**Comment by jeremystretch** [comment]
AFAICT this only affects interfaces (and not other device components).
