### ISSUE TITLE
UI: Dropdown inside table rows create new scrolling contexts

### ISSUE THREAD

**Issue by ndom91** [netbox-community/netbox#7180]
### NetBox version

v3.0.1

### Python version

3.7

### Steps to Reproduce

Go to a device with interfaces and select the "connect" dropdown. This will give the user a choice of "Interface", "Front Port", "Rear Port", "Circuit Termination". However, this dropdown will cause the interior of the table of interfaces to scroll if the table is shorter the amount of choices in the dropdown, i.e. if there are only 2-3 interfaces.

### Expected Behavior

Interior table area should not scroll inside itself. Maybe something like an `overflow: visible;` on it would help?

### Observed Behavior

See gif:

![2021-09-04-22-20-31](https://user-images.githubusercontent.com/7415984/132107158-586273f0-a10f-4f93-8bc8-b521ef93f88e.gif)

CC: @thatmattlove

**Comment by jbakklund** [comment]
This issue is equal to #7179
