### ISSUE TITLE
Tags get lost when editing

### ISSUE THREAD

**Issue by fansari** [netbox-community/netbox#7191]
### NetBox version

v.3.0.1

### Python version

3.9

### Steps to Reproduce

1. Click on Tags and create some
2. Create a virtual machine
3. Try to add more than one tag

Edit by @jeremystretch: This only happens when using the filter to search for successive tags. Selecting them directly works as expected.

### Expected Behavior

You should be able to add more than one tag for a device like a virtual machine or on interfaces or any other device where tags are possible.

### Observed Behavior

Tags get lost. If you try to set more than one tag the first is removed when you setup the second one. Sometimes the second still works but I did not manage to set more than two tags.

With Netbox 2.10.8 tags did work. We use ansible scripts which rely on tags - so this is a very serious bug for us.

**Comment by jeremystretch** [comment]
I'm not able to reproduce this on v3.0.1. I was able to successfully create a virtual machine with multiple tags on both my local development instance and the [public demo](https://demo.netbox.dev/).

It's possible you need to force a refresh in your browser to update the static content.

**Comment by cjwagz** [comment]
I have updated to v3.0.1 and I am having the same issue it really is annoying for me on the Tagged VLANs that I had a ticket open for #7099 

The issue exists when you use the filter box to search for a tag or vlan. If you click them it doesn't clear the previous selection but typing in the filter box causes the first selection to disappear.

I was able to reproduce the same error on demo.netbox.dev

I'm using Chrome Version 90.0.4430.212

**Comment by jeremystretch** [comment]
Works for me using Chrome 92.0.4515.107

**Comment by cjwagz** [comment]
Here is a screen capture of demo.netbox.dev on Edge Version 93.0.961.38. It does the same thing in Chrome, Firefox, etc.

https://www.youtube.com/watch?v=G1UjO2E32oE

**Comment by jeremystretch** [comment]
And here it is working normally:

https://user-images.githubusercontent.com/13487278/132398346-18b1c65a-115f-4362-9b13-4fa95175581a.mp4

Not sure what to tell you.

**Comment by cjwagz** [comment]
@jeremystretch you did not use the filter to search for the tag. The error only occurs when you type in the filter box like my demonstration video. Clicking and selecting the items does not produce the error.

**Comment by jeremystretch** [comment]
Aha. That was not mentioned in the original report. I can confirm this now, thanks.

I will update the original post to include this detail.

**Comment by thatmattlove** [comment]
I've confirmed while this _is_ present in 3.0.1 (via public demo), it is _not_ present on the `develop` branch. More than likely, one of the fixed for other select-related issues has already fixed this. I'll wait for someone to confirm this, but I think it can be closed.

**Comment by fansari** [comment]
I can confirm this too. When I select the tag directly from the list it works. I did not try this before because we have a very long list...

**Comment by cjwagz** [comment]
@thatmattlove I cloned the develop branch [2a293d5](https://github.com/netbox-community/netbox/commit/2a293d5d02532a55473af14fabc359b0c8bdd8f0) this morning and I still see this bug in my build.

**Comment by jeremystretch** [comment]
Can confirm this is still a problem in `develop` as of 2a293d5d02532a55473af14fabc359b0c8bdd8f0
