### ISSUE TITLE
Plugin Development Documentation Extending Templates section out of date

### ISSUE THREAD

**Issue by 991jo** [netbox-community/netbox#7195]
### Change Type

Correction

### Area

Administration/development

### Proposed Changes

Some NetBox internals regarding the UI have changed in NetBox v3.
I am currently porting my plugins to v3 and have to adopt to the new UI.

The "Extending the Base Template section" (https://netbox.readthedocs.io/en/stable/plugins/development/#extending-the-base-template) is still referring to the old base template. I think this template is no longer called `base.html` but `base/base.html` and some of the blocks have new names. But there is also a `base/layout.html` which implements a lot of the base structure of the NetBox pages.

The documentation should be updated to reflect these changes and comment on what to use and which parts are for what.

**Comment by jeremystretch** [comment]
@991jo would you like to volunteer to update the documentation, given that you're in the ideal spot to do so?

**Comment by jeremystretch** [comment]
> I am not in the position to do that, because that part defines a piece of the plugin development interface.

The documentation doesn't define it, the templates do, if that makes sense. The documentation is just for reference.

> Also I am currently digging through the templates and trying to figure out the changes required for my own plugins.

Exactly. This makes you ideally situated to update the documentation with your own experience.

**Comment by 991jo** [comment]
> > I am not in the position to do that, because that part defines a piece of the plugin development interface.
> 
> The documentation doesn't define it, the templates do, if that makes sense. The documentation is just for reference.

I will quote the documentation regarding plugin development here (the first big WARNING block):

> While very powerful, the NetBox plugins API is necessarily limited in its scope. The plugins API is discussed here in its entirety: Any part of the NetBox code base not documented here is not part of the supported plugins API, and should not be employed by a plugin. Internal elements of NetBox are subject to change at any time and without warning. Plugin authors are strongly encouraged to develop plugins using only the officially supported components discussed here and those provided by the underlying Django framework so as to avoid breaking changes in future releases. 

It basically says "here are a set of things you are allowed to use as a plugin developer. Everything else can be used at your own risk, dont blame is if stuff breaks."

**Comment by jeremystretch** [comment]
Yes, and it needs to be updated to reflect the new templates.

**Comment by dvaccarosenna** [comment]
I've also been looking through the documentation to port some plugins to v3 and it seems referring to the new template is the only required change. If it's agreed that `base/layout.html` is the suggested base template for plugins then I'm happy to submit a PR for this.
