### ISSUE TITLE
Custom Links button / dropdown group should not be in new row

### ISSUE THREAD

**Issue by fknorn** [netbox-community/netbox#7196]
### NetBox version

v3.0.1

### Python version

3.8

### Steps to Reproduce

Create custom link for e.g. a device with group name "External links"

### Expected Behavior

On a device page, the new "External links" dropdown group button should be in the same line as the existing buttons _Clone_, _Edit_, _Delete_ buttons as not to waste vertical space.

![image](https://user-images.githubusercontent.com/4229411/132325626-6c9fb1ae-73c9-49f7-8bdd-7278db8cc7a9.png)

### Observed Behavior

The dropdown button appears in a new row instead of besides.

![image](https://user-images.githubusercontent.com/4229411/132325594-679cac69-737c-4513-a03e-8f0c979f7d00.png)

### Diagnosis

This is due to the fact that the new button group's `.dropdown`-div is placed in a separate, new `.control-group`-div instead of being added to the existing `.control-group` where the other default buttons and dropdowns live.

**Comment by jeremystretch** [comment]
This layout is intentional and consistent with earlier releases. It's also necessary to avoid crowding the top row for many objects.
