### ISSUE TITLE
Include a search/filter tab for all objects which support custom fields

### ISSUE THREAD

**Issue by MarRio81** [netbox-community/netbox#7210]
### NetBox version

v2.11.12

### Feature type

New functionality

### Proposed functionality

filter/search menu on Cluster Group Site (Virtualization)

### Use case

We use Virtualization Cluster Groups as a representation of vCenter servers to group the clusters under the vCenters. Furthermore, we have given the cluster group a custom field to identify which business unit is responsible for the operation of this vCenter. It would therefore be an advantage if these groups get a filter/search menu like the virtual machines and clusters to be able to narrow down the view.

**Comment by jeremystretch** [comment]
This should probably be extended to _all_ models which support custom fields, not just cluster groups. I've taken the liberty of updating the title accordingly.

**Comment by jeremystretch** [comment]
Implemented in cc0830bf281fd0fd85df349d50e3108d06930278
