### ISSUE TITLE
KeyError on Global VRF - "Index out of range"

### ISSUE THREAD

**Issue by florianschendel** [netbox-community/netbox#7216]
### NetBox version

v3.0.1

### Python version

3.9

### Steps to Reproduce

IPAM --> Prefixes --> Klick on the link "Children"
Prefix/Children must be part of the global vrf

### Expected Behavior

No exception

### Observed Behavior

KeyError on Global VRF

![key error](https://user-images.githubusercontent.com/33891080/132499659-47fe0f7c-b051-48aa-b260-d4ab8d306e00.PNG)

**Comment by jeremystretch** [comment]
Please provide complete reproduction steps, beginning with the creation of the parent and child prefixes.

**Comment by florianschendel** [comment]
This instance was upgraded from 2.11.11 to version 3.0.1
We use the netbox docker image in combination with the helm chart from bootc + RedHat Openshift.

There was no change on Prefix content. DB was converted to version 3.0.1.

I klick on IPAM --> Prefixes --> Klick on the Overview with all previxes
On the overview page with all prefixes i klick on "Children" link
After the last klick i get the exception
