### ISSUE TITLE
Edit Interface does not select correct LAG interfaces

### ISSUE THREAD

**Issue by doogienz** [netbox-community/netbox#7219]
### NetBox version

v3.0.1

### Python version

3.8

### Steps to Reproduce

1. Create interface on device with Type 'Link Aggregation Group (LAG)' and create
2. Select Interface from main interface screen of device to individually add to LAG group
3. Edit Interface from within interface detail screen
4. LAG Interface input includes random LAG groups - sometimes from the device, but mostly not.

### Expected Behavior

Have a list of LAG interfaces from this device.  You are able to work around by editing the interface in bulk edit mode, which selects the correct LAG interfaces.

### Observed Behavior

LAG interface selection includes randomly selected LAG devices, sometimes from this device and sometimes not.

**Comment by jeremystretch** [comment]
Please revise your post above to provide detailed reproduction steps, beginning with the creation of the interfaces.

**Comment by doogienz** [comment]
Updated with more detail.

**Comment by jeremystretch** [comment]
I'm not able to replicate this on v3.0.1. I only see LAG interfaces from the assigned device in the list, and I confirmed that the API request being made to retrieve this is filtered by `device_id` as expected.

**Comment by doogienz** [comment]
When requests are made to the API - I'm getting results from other devices - i.e. the device_id here is 300 but this is what is occuring on all devices:

`/dcim/interfaces/edit/?device=300&return_url=/dcim/devices/300/interfaces/` is actually retrieving info from device 46 

```
/api/dcim/interfaces/?brief=true&device_id=46
/api/dcim/interfaces/?brief=true&device_id=46&type=lag
```

I'm getting random results though, the device ID selected is never consistent

Sounds like something might be wrong with our install :(

**Comment by doogienz** [comment]
Rebuild of virtual environment cleared issue.

**Comment by lastorel** [comment]
> Rebuild of virtual environment cleared issue.

I have the same.
Clean installation of venv helps.
