### ISSUE TITLE
Rounding required for °F temperature conversion in Napalm device status tab

### ISSUE THREAD

**Issue by candlerb** [netbox-community/netbox#7228]
### NetBox version

v3.0.2

### Python version

3.8

### Steps to Reproduce

1. Configure napalm
2. Go to a napalm-enabled device which reports temperature (mine's a Mikrotik RB4011)
3. Go to the Status tab: `/dcim/devices/<N>/status/`
4. Look at the °F temperature conversion

### Expected Behavior

°F temperature to one decimal place at most.

### Observed Behavior

I see `42 °C 107.60000000000001 °F`

![image](https://user-images.githubusercontent.com/44789/132686466-4501870e-9c72-473f-a87c-e65f2bfd6210.png)

This isn't always the case - e.g. on another device I see `51 °C 123.8 °F`

**Comment by royreznik** [comment]
@jeremystretch I would like to provide a pr for this issue
