### ISSUE TITLE
Get popup message "Error Fetching Options for field 'site_group'" when try to modifying Device fields

### ISSUE THREAD

**Issue by mauroBell** [netbox-community/netbox#7229]
### NetBox version

v3.0.2

### Python version

3.9

### Steps to Reproduce

1) Click on devices
2) Select a device created on v2.X.X
3) Click on "Edit" button

### Expected Behavior

I'm Admin user, so i may modify all device without "Error Fetching Options for field 'site_group'" popup message

### Observed Behavior

I receive the "Error Fetching Options for field 'site_group'" popup message all time i try to edit a device
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/90396391/132691765-62046b94-8545-4e85-9e05-1ebd7b42f83a.png)

**Comment by jeremystretch** [comment]
Thank you for opening a bug report. Unfortunately, the information you have provided is not sufficient for someone else to attempt to reproduce the reported behavior. Remember, each bug report must include detailed steps that someone else can follow on a clean, empty NetBox installation to reproduce the exact problem you're experiencing. These instructions should include the creation of any involved objects, any configuration changes, and complete accounting of the actions being taken. Also be sure that your report does not reference data on the public NetBox demo, as that is subject to change at any time by an outside party and cannot be relied upon for bug reports.

**Comment by jeremystretch** [comment]
Closing as there has been no further response from the poster.

**Comment by jeremystretch** [comment]
This was misidentified in the unrelated PR above.
