### ISSUE TITLE
Platform field's dynamic research doesn't work after update to 3.0.2

### ISSUE THREAD

**Issue by mauroBell** [netbox-community/netbox#7230]
### NetBox version

v3.0.2

### Python version

3.9

### Steps to Reproduce

1) Click on Device
2) Create new Device or Edit existing one
3) Compile Platform field: "No Results" appear, but I've got many platform created

### Expected Behavior

Writing "Win" on Platform field should display many versions of Windows OS

### Observed Behavior

Cannot search or add any platform
![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/90396391/132692448-e6d35b44-3b19-40ab-9573-2ae2dc6da929.png)

**Comment by jeremystretch** [comment]
Thank you for opening a bug report. Unfortunately, the information you have provided is not sufficient for someone else to attempt to reproduce the reported behavior. Remember, each bug report must include detailed steps that someone else can follow on a clean, empty NetBox installation to reproduce the exact problem you're experiencing. These instructions should include the creation of any involved objects, any configuration changes, and complete accounting of the actions being taken. Also be sure that your report does not reference data on the public NetBox demo, as that is subject to change at any time by an outside party and cannot be relied upon for bug reports.

**Comment by jeremystretch** [comment]
Closing this as no further detail has been provided.
