### ISSUE TITLE
Rack device click ends up at wrong port

### ISSUE THREAD

**Issue by joaquim22** [netbox-community/netbox#7231]
### NetBox version

v3.0.2

### Python version

3.7

### Steps to Reproduce

1. Navigate to any Rack
2. Click on the object 
3. Redirects to the bind port 8001 (i have Nginx running on http-80)
4. Every other option goes to http-80 but an existing device rack click goes to 8001

### Expected Behavior

1.pic attached
![front-hover-add](https://user-images.githubusercontent.com/22074217/132708041-c31e36b6-6a03-4e15-926d-5c8bedef0b1b.png)

### Observed Behavior

1. 8001 pic
2. redirect pic

![front-hover](https://user-images.githubusercontent.com/22074217/132708439-b74aa66c-03a6-49e2-8e3a-bae4ba46eaa2.png)
![redir](https://user-images.githubusercontent.com/22074217/132708272-1c8b415a-9475-4b13-ad7f-4a1e1b043941.png)

**Comment by jeremystretch** [comment]
This is an issue with your nginx configuration. Please see [this wiki article](https://github.com/netbox-community/netbox/wiki/Common-Issues#rack-elevation-links-use-wrong-domain) for more information.

**Comment by joaquim22** [comment]
Thankyou Jeremy. i will check it out
