### ISSUE TITLE
I cannot select multiple tags for the equipment

### ISSUE THREAD

**Issue by trollqaa** [netbox-community/netbox#7244]
### NetBox version

v3.0.2

### Python version

3.9
I use docker image netboxcommunity/netbox

### Steps to Reproduce

1. Click 'Devices'
2.  Add new device
3. Try select multiple tags (if use list - ok, if use filter - selected tags was dropped)

### Expected Behavior

Expect to be able to select multiple tags without both when using a list or using a tag search

### Observed Behavior

non errors. but tags dont save :(

**Comment by jeremystretch** [comment]
This was fixed under #7191 for v3.0.2, and I can confirm that it works both locally and on the [demo instance](https://demo.netbox.dev/). You may need to force-refresh your browser to load the updated Javascript.

**Comment by trollqaa** [comment]
@jeremystretch I check from two browsers including freshly installed mozilla firefox, there is a problem ...

**Comment by jeremystretch** [comment]
Did you try to reproduce the problem using the demo instance?

**Comment by trollqaa** [comment]
I am very sorry.
failed update fron 3.0.1 to 3.0.2
i run manually command in container `/opt/netbox/venv/bin/python manage.py collectstatic` and problem was solved.
sorry. my bad :(
