### ISSUE TITLE
Plugin Nextbox-ui-plugin not use

### ISSUE THREAD

**Issue by hocker96** [netbox-community/netbox#7254]
### NetBox version

v3.0.2

### Python version

3.8

### Steps to Reproduce

Install nextbox-ui-plugin

source /opt/netbox/venv/bin/activate
pip3 install nextbox-ui-plugin
echo nextbox-ui-plugin >> local_requirements.txt
edit configuration.py
PLUGINS = [
    'nextbox_ui_plugin',
]
(venv) $ python3 manage.py migrate

### Expected Behavior

<class 'django.template.exceptions.TemplateDoesNotExist'>

base.html

Python version: 3.8.10
NetBox version: 3.0.2

### Observed Behavior

<class 'django.template.exceptions.TemplateDoesNotExist'>

base.html

Python version: 3.8.10
NetBox version: 3.0.2

**Comment by jeremystretch** [comment]
This is not a NetBox issue. You'll need to raise this with the plugin's maintainers.
