### ISSUE TITLE
"Old-Style" Exports

### ISSUE THREAD

**Issue by stevenshepherd** [netbox-community/netbox#7260]
### NetBox version

3.0.1

### Python version

3.9

### Steps to Reproduce

- Navigate to Racks
- Select specific Rack
- Export does not include comments for the device(s) which was available in the 2.x version of NetBox

### Expected Behavior

The ability to use "old-style" reporting/exports

### Observed Behavior

No ability to use "old-style" reporting/exports

**Comment by jeremystretch** [comment]
Thank you for opening a bug report. Unfortunately, the information you have provided is not sufficient for someone else to attempt to reproduce the reported behavior. Remember, each bug report must include detailed steps that someone else can follow on a clean, empty NetBox installation to reproduce the exact problem you're experiencing. These instructions should include the creation of any involved objects, any configuration changes, and complete accounting of the actions being taken. Also be sure that your report does not reference data on the public NetBox demo, as that is subject to change at any time by an outside party and cannot be relied upon for bug reports.

**Comment by jeremystretch** [comment]
Closing as there has been no reply.
