### ISSUE TITLE
Filter bar only shows results within the current page

### ISSUE THREAD

**Issue by ISNL-PimP** [netbox-community/netbox#7263]
### NetBox version

3.0.2

### Python version

3.8

### Steps to Reproduce

1. Open any view (ex. Devices)
2. Make sure there are more devices than the current page size
3. Type the name of any device on a page beyond the currently visible one in the filter bar
4. The device does not show in the list
![image](https://user-images.githubusercontent.com/59050598/133224121-ab33d1c3-58c8-4f54-bd20-b7ac370f17c6.png)

### Expected Behavior

Devices on pages beyond the currently visible page should also be visible; the 'filter bar' should have the same behaviour as the 'all fields' search field in the 'filters' tab.

### Observed Behavior

The filter bar only shows results from within the current page.

**Comment by jeremystretch** [comment]
This is clearly intended behavior, and predates the v3.0 release. (There was also a filter field on the device interfaces list.)

If you'd like to propose new/modified functionality, please open a feature request detailing the proposed implementation and your use case.
