### ISSUE TITLE
Mark utilized not propagated to parent prefixes

### ISSUE THREAD

**Issue by zombah** [netbox-community/netbox#7267]
### NetBox version

v3.0.2

### Python version

3.9

### Steps to Reproduce

1. Create prefix f.e. 192.168.1.0/24 in vrf Global status Active
2. Create two child prefixes 192.168.1.0/25 and 192.168.1.128/25 in vrf Global status Active
3. Tick "Mark utilized" for child prefix 192.168.1.128/25
4. Check  prefix 192.168.1.128/25 utilization and parent 192.168.1.0/24 utilization

### Expected Behavior

Parent prefix 192.168.1.0/24 utilization 50%

### Observed Behavior

Parent prefix 192.168.1.0/24 utilization 0%

**Comment by zombah** [comment]
@jeremystretch I volunteer to create fix if you dont mind

**Comment by jeremystretch** [comment]
Upon closer inspection, I don't believe this is a bug. The parent prefix (192.168.1.0/24) should have its status set to "container," as it contains child prefixes. Doing so results in the utilization reported as expected.

**Comment by zombah** [comment]
@jeremystretch Oh i see, but then it may lead to some frustration if used without container. 
Maybe we can treat it as not fix, but as small addition to mark_utilized function? 
I think it will make good company for container status and wil not break overall logic scheme
and i see no visible drawbacks. 
I imagine it can be used for granular utilization documentation there prefix known to be fully used
but no need to add all ip's except gateway assigned to interface for example or some mixed
mode there you turn container to  active to how it is utilized on child ip,range and prefix base.

**Comment by jeremystretch** [comment]
>  Oh i see, but then it may lead to some frustration if used without container.

Why would you not simply set the status to container?

**Comment by zombah** [comment]
> Why would you not simply set the status to container?

Yes container is solid solution, but there is coner cases where it may be useful to use
active for prefix which have child prefixes.

For example one host from large prefix moved within small specific prefix to other device, so
original large prefix still have active status role, but in netbox topology it looks like contrainer now
because there is child prefix.

Main thing i like in this that it gives possibility to document more precise utilization
for container prefix, maybe having two utilization counters for container is another way to go, treat all
childs prefixes as utilized as it is now and second counter which counts child ip's,range's and mark_utilized prefixes as
active prefix will do?

**Comment by zombah** [comment]
@jeremystretch I noticed there is issue #6606 which can theoretically 
compensate extra lookup on active prefix with on demand utilization counting. 
Is that a more proper solution? 
I can try to create PR for #6606 with this feature merged inside.

**Comment by zombah** [comment]
After more thinking and experementation i agree, this is not needed functionality, container is definitly enough.
So i close this issue and it's pr.
