### ISSUE TITLE
sort by X and then by Y

### ISSUE THREAD

**Issue by opericgithub** [netbox-community/netbox#7276]
### NetBox version

v3.0.3

### Feature type

New functionality

### Proposed functionality

Regarding newly implemented functionality of sorting tenants alphabetically (#6988), one should have a choice of sorting by one column, then by another column etc. For example, this could be done by clicking the header of the column "tenant group" and then clicking the header of the column "tenant". Optionally there might be displayed numbers 1,2 etc. next to the clicked column header, in the order of clicking/sorting.

### Use case

If there is a need to use the old method of sorting (ie. prior to v3.0.3 tenants in circuits list are sorted by tenant group, not alphabetically), one should sort the list first by tenant group, then by tenant. 

### Database changes

not sure

### External dependencies

not sure

**Comment by jeremystretch** [comment]
django-tables2, which NetBox employs for generating tables in the UI, does [support ordering by multiple attributes](https://github.com/jieter/django-tables2/issues/559) on the backend. However, implementing this in an elegant way on the frontend could be tricky.

For example, if I have sites ordered by tenant, and then click the "name" header, NetBox doesn't know if I intent to apply that as the new primary ordering, or enable it as a secondary ordering after tenant. It would be very tedious to require the user to deselect that active ordering column(s) before choosing a new one. How do you propose implementing this?

**Comment by opericgithub** [comment]
I understand your concerns and it might be really tricky to implement. 

As described here: https://www.codeproject.com/Articles/5166021/Multiple-Column-Sorting-from-Angular-NgExTable-to maybe one of the proposed solutions would be to do single sorting on classic mouse click, and to begin multicolumn sorting on ctrl+click. 

As stated there "With this approach, regularly clicking any sortable column always proceeds with the single column sorting type. When clicking the second sortable column while pressing the Ctrl or Shift key, the process will go to the multiple column sorting workflow. You can remove the sorted columns by clicking the "x" button from the sequence dropdowns until only one sorted column is left on the data grid, which then becomes the single column sorting type. To quickly switch to the single column sorting type, a button, Go to Single Column Sorting, is added onto the multi-sorting command panel."

Of course, I'm not sure if it is feasible at all for you to implement this kind of behaviour.
