### ISSUE TITLE
Internal Server Error on displaying cable trace between Circuit Termination and Rear Port

### ISSUE THREAD

**Issue by clerie** [netbox-community/netbox#7278]
### NetBox version

v3.0.2

### Python version

3.8

### Steps to Reproduce

- Create a Rear Port
- Create a Circuit Termination
- Connect a Cable between
- Try to display cable trace

The cable should look like:
![image](https://user-images.githubusercontent.com/9381848/133571952-3605f5ae-29af-45d5-9554-d7f77e0ef972.png)

### Expected Behavior

I expect to see the complete cable trace, like when the cable connect two interfaces.

### Observed Behavior

When displaying the cable trace page you get the following error:
![image](https://user-images.githubusercontent.com/9381848/133571554-d81f2fe2-b179-4d9a-9966-5e5c1c5a7568.png)

I found the following exception in my logs:
```
Internal Server Error: /circuits/circuit-terminations/5/trace/
Traceback (most recent call last):
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/opt/netbox/netbox/dcim/views.py", line 2392, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/opt/netbox/netbox/utilities/views.py", line 93, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/opt/netbox/netbox/netbox/views/generic.py", line 71, in get
    **self.get_extra_context(request, instance),
  File "/opt/netbox/netbox/dcim/views.py", line 2418, in get_extra_context
    api_viewname = f"{path.origin._meta.app_label}-api:{path.origin._meta.model_name}-trace"
AttributeError: 'NoneType' object has no attribute 'origin'
```

**Comment by jeremystretch** [comment]
Thank you for opening a bug report. Unfortunately, the information you have provided is not sufficient for someone else to attempt to reproduce the reported behavior. Remember, each bug report must include detailed steps that someone else can follow on a clean, empty NetBox installation to reproduce the exact problem you're experiencing. These instructions should include the creation of any involved objects, any configuration changes, and complete accounting of the actions being taken. Also be sure that your report does not reference data on the public NetBox demo, as that is subject to change at any time by an outside party and cannot be relied upon for bug reports.

**Comment by jeremystretch** [comment]
Looks like the same issue as #7279. If you believe this to be a different issue, please update your post above with the required detail to reproduce and ask that it be reopened.
