### ISSUE TITLE
Trying to get in touch regarding a security issue

### ISSUE THREAD

**Issue by JamieSlome** [netbox-community/netbox#7280]
Hey there!

I'd like to report a security issue but cannot find contact instructions on your repository.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by jeremystretch** [comment]
Hi, I'm the lead maintainer for NetBox. I'm afraid we don't have the resources to support a separate triage workflow for security issues. For now, you're welcome to email me directly at jstretch@ns1.com if you're not comfortable opening a bug report for this.
