### ISSUE TITLE
Rack Exports - Include ability to export comment(s)

### ISSUE THREAD

**Issue by stevenshepherd** [netbox-community/netbox#7284]
### NetBox version

3.0.2

### Feature type

New functionality

### Proposed functionality

When exporting a rack layout, it would be nice to have the ability to include the comment(s) on the device(s).  Previous versions did include the comments.

### Use case

Many times there is important data you need to know about a device that are entered in the 'comments' section.  However, if someone relies on this data and they export the device(s), the comments are not shown.

### Database changes

N/A

### External dependencies

N/A

**Comment by jeremystretch** [comment]
I'm pretty sure the intent here is to enable the inclusion of the `comments` field when exporting devices. I'll extend the scope here to do so for all models with a comments field.
