### ISSUE TITLE
Trace does not work between two rear ports, and not between interface -> front port -> rear port

### ISSUE THREAD

**Issue by sliddjur** [netbox-community/netbox#7293]
### NetBox version

v3.0.2 from netbox-docker. 

### Python version

3.8

### Steps to Reproduce

I am trying to document my WDM cabling. 

Steps to reproduce:
Create two devices, both with;
- 1 rear port, 9 positions
- 9 front ports mapped to the rear positions

Connect a cable between the two rear ports.
Go to device, rear ports and press trace

I am given this error message:
![rearports](https://user-images.githubusercontent.com/10002057/133789810-814a300a-5c4e-4c69-9bed-3e5baaa8f599.png)

Now, if I add another device, create a few interfaces.
- Connect one interface to one front port on the device recently created
Go to interfaces, and press trace, 
I am given this trace, which shows me nothing.
![int-front-rear](https://user-images.githubusercontent.com/10002057/133790229-1e8a2bf0-e0ba-4452-a2c7-d0690ee66391.png)

### Expected Behavior

I expected to see trace

both on the rear port only

and also on 
interface -> frontport -> rearport -> rearport 

### Observed Behavior

```
Server Error
There was a problem with your request. Please contact an administrator.

The complete exception is provided below:

<class 'AttributeError'>

'NoneType' object has no attribute 'origin'

Python version: 3.9.5
NetBox version: 3.0.2
```

**Comment by jeremystretch** [comment]
Thank you for submitting this issue, however it appears that this topic has already been raised. Please see issue #7279 for further discussion.
