### ISSUE TITLE
API documentation provide more examples

### ISSUE THREAD

**Issue by georgesnow** [netbox-community/netbox#7296]
### Change Type

Addition

### Area

REST API

### Proposed Changes

I have been attempting to try and use the api via python. And I am finding difficult to find some more specific and clear examples. 

Currently, I am attempting to assign an IP to an interface. However, I am having to look through each object to find the proper method call and value. I had attempted to gleam some insight via CSV import but those fields don’t match all the methods.
I reviewed  one of the other open tickets, but I still wasn’t able to track down the proper way to do it.

I would propose the documentation show simple call to add each of the various attributes. I am willing to contribute examples once I figure them out as well.

**Comment by jeremystretch** [comment]
We're going to need more detail here. What specific examples would you include, and why? Bear in mind that the core documentation must remain maintainable long term, so arbitrary examples should be limited to those that are sure to provide value.

**Comment by jeremystretch** [comment]
Closing as there's been no further response.

**Comment by georgesnow** [comment]
I haven’t had a chance to write up examples. I will open a new ticket when I write up some examples.
