### ISSUE TITLE
Changes in templates block, aren't reflected in documentation.

### ISSUE THREAD

**Issue by renatoalmeidaoliveira** [netbox-community/netbox#7299]
### Change Type

Correction

### Area

Administration/development

### Proposed Changes

In the [plugin development documentation](https://netbox.readthedocs.io/en/stable/plugins/development/) page, the extending base template block refers to:
` {% extends 'base.html' %} `
But that doc was moved to base/base.html so it should be:
` {% extends 'base/base.html' %} `

Another issues are about the content blocks, because is the new base.html there are:

* `head` instead of `header`
* `layout` instead of `content`
*  and a new block `data` that isn't documented.

**Comment by jeremystretch** [comment]
The documentation currently says to extend `base/layout.html`, which is correct. The block names are correct for this template, as well.
