### ISSUE TITLE
deleted custom fields still visible as available table columns

### ISSUE THREAD

**Issue by opericgithub** [netbox-community/netbox#7309]
### NetBox version

v2.11.11

### Python version

3.7

### Steps to Reproduce

1. in the netbox administration section (admin/extras/customfield) create multiselect custom field and make it applicable to dcim>devices
2. edit any device by selecting any value for the custom field
3. delete newly created custom field
4. go to devices->devices page 
5. go to table configuration parameters (configure button in the upper right corner) 
6. check the available colums

### Expected Behavior

one should not expect custom field, that was previously deleted, to appear under "available columns"

### Observed Behavior

In version v.2.11.11 custom field, that was previously deleted, appears under "available columns". 
In version v3.0.2 deleted custom field does not appear under available columns, which is correct and expected behaviour.

**Comment by jeremystretch** [comment]
I'm afraid we are no longer accepting bug reports for v2.11 or earlier releases. Please upgrade to v3.0.

**Comment by opericgithub** [comment]
initially I thought this was bug related to v2 only. 
now i did some testing on v3, and can confirm the same behaviour.
