### ISSUE TITLE
deleted custom fields still visible as available table columns

### ISSUE THREAD

**Issue by opericgithub** [netbox-community/netbox#7310]
### NetBox version

v3.0.2

### Python version

3.7

### Steps to Reproduce

1. in the "other->custom fields" section create new multiselect custom field and make it applicable to dcim>devices
2. go to devices->devices page
3. go to table configuration parameters ("configure table" button in the upper right corner)
4. write down the available colums (new custom field is at the bottom of the list)
5. delete newly created custom field from the "other->custom fields" section
6. repeat steps 2-4 (deleted custom field is at the bottom of the list)

### Expected Behavior

one should not expect custom field, that was previously deleted, to appear under "available columns"

### Observed Behavior

custom field, that was previously deleted, appears under "available columns".
this happens almost everytime. if not, try refreshing the devices->devices page.

**Comment by jeremystretch** [comment]
Thank you for submitting this issue, however it appears that this topic has already been raised. Please see issue #6817 for further discussion.
