### ISSUE TITLE
Search error

### ISSUE THREAD

**Issue by bkakakym** [netbox-community/netbox#7313]
### NetBox version

v3.0.2

### Python version

3.9

### Steps to Reproduce

1. Open a chapter page (eg sites or devices)
2. Try to use local chapter search
3. Seach is made between items listed below in a chapter 

### Expected Behavior

search among all items of chapter is expected

### Observed Behavior

if there is only 25 items per list and searched item by default located on some next page search result will be empty
![image](https://user-images.githubusercontent.com/20533976/134024476-00b4a024-50e0-479c-860c-4b7ced28b58d.png)

but if there more items listed (for example - all of them) - search will work (but if threre are a olt of items it will be lagging (maybe onu our system perfomance but not sure
![search2](https://user-images.githubusercontent.com/20533976/134025332-12dfe4b6-4b1b-46ed-837f-0caf7ac94903.jpg)
)

**Comment by jeremystretch** [comment]
This widget is used to filter the current display of objects only. This is intended behavior.
