### ISSUE TITLE
Add "Serial Number" to device search filters in web UI

### ISSUE THREAD

**Issue by slash-proc** [netbox-community/netbox#7323]
### NetBox version

v3.0.3 (checked demo.netbox.dev this morning)

### Feature type

Change to existing functionality

### Proposed functionality

I propose explicitly adding "Serial Numbers" to the filter list of devices in the web UI. 

### Use case

Currently, searching for serial numbers in the global context finds devices corresponding to the serial number; however "Serial Numbers" is not present in the list of filters on the device page. This can lead to confusion about whether or not serial numbers can be used to find devices. Adding this criteria explicitly to the device filters list in the web UI would help stem such confusion and make it clearer to users that searching for devices via serial number is a valid workflow.

### Database changes

Unsure - probably none?

### External dependencies

Unsure - probably none?

**Comment by jeremystretch** [comment]
Seems like this should be added for racks as well.
