### ISSUE TITLE
Long Journal entried are not displayed correctly (UX/UI bug)

### ISSUE THREAD

**Issue by kotso** [netbox-community/netbox#7338]
### NetBox version

v3.0.3

### Python version

3.9

### Steps to Reproduce

add any journal entry that is bigger then default size of view.

### Expected Behavior

... by end of view displayed but view is not extended, so to see full text you should go to edit mode.

### Observed Behavior

nothing

**Comment by jeremystretch** [comment]
Thank you for opening a bug report. Unfortunately, the information you have provided is not sufficient for someone else to attempt to reproduce the reported behavior. Remember, each bug report must include detailed steps that someone else can follow on a clean, empty NetBox installation to reproduce the exact problem you're experiencing. These instructions should include the creation of any involved objects, any configuration changes, and complete accounting of the actions being taken. Also be sure that your report does not reference data on the public NetBox demo, as that is subject to change at any time by an outside party and cannot be relied upon for bug reports.

**Comment by kotso** [comment]
![IMG_2048](https://user-images.githubusercontent.com/1928528/134487761-405ea2f3-01a9-49f4-aaed-a81691d29f1c.jpeg)

@jsenecal check this please, to see full comment here, only option is to press edit that is not imho correct behavior.

I think, correct behavior would be link on … that would extend area of comment so that full text is shown.

**Comment by DanSheps** [comment]
You click on the creation date.  That gives you more data

**Comment by kotso** [comment]
@DanSheps thank you, it works.

but still as feature request would be great to have possibility to see multiple oversized comments on same page.
