### ISSUE TITLE
Support to move interface to another device

### ISSUE THREAD

**Issue by ypid** [netbox-community/netbox#7346]
### NetBox version

v3.0.3

### Feature type

New functionality

### Proposed functionality

Currently an Interface is bound to a Device. Interfaces cannot be moved to another Device while in reality, this could be possible. For Inventory Items, moving between devices is already supported.

A question is how to handle Interfaces with Cables plugged in. I would suggest to not allow to move such Interfaces. Just like in reality, an Interface (card) is not moved with a cable plugged in.

Front/Rear Ports, this could also be possible in reality (moving Keystones), but I expect this to get tricky so lets leave it out of this feature request.

### Use case

A Interface was installed in Device A and is physically removed from it and installed in Device B.

### Database changes

No.

### External dependencies

No.

**Comment by DanSheps** [comment]
> A question is how to handle Interfaces with Cables plugged in. I would suggest to not allow to move such Interfaces. Just like in reality, an Interface (card) is not moved with a cable plugged in.

Netbox replicates real-life scenarios in most instances.  With Inventory Items, most (Fans, PSU, etc) can be removed and moved.  However an interface on a switch can 99% of the time never be removed (exception is a expansion module like NM's for Cisco, however it is easier to handle the majority then the exceptions).

So, the process of how to handle this is simple:

You create new interfaces, remove the cables and re-attach them to the new interface.

**Comment by ypid** [comment]
I agree that with network equipment like switches and routers, moving Interfaces is uncommon. However, for a Server Device, it happens that you move NICs to another server. The reason I am proposing to support moving is that some attributes like "MAC address" and possibly "Label" and "Description" are attached to the physical NIC.

**Comment by ziggekatten** [comment]
This is where you create a custom script where you select interface, preserve necessary info, delete it on current device and add it to the new device with a press of. Button. 

No need to change basic features in Netbox when there are tools to handle the outliers. 

This is the real feature of Netbox. There is almost always a way to solve the challenges.

**Comment by DanSheps** [comment]
> This is where you create a custom script where you select interface, preserve necessary info, delete it on current device and add it to the new device with a press of a button

This is the way

**Comment by jeremystretch** [comment]
I'm afraid implementing the proposed simply would not be worth the development effort required to do so reliably. As others have mentioned, the preferred approach is to replicate & delete interfaces in the relatively infrequent cases where this is needed.

**Comment by ypid** [comment]
> This is where you create a custom script where you select interface, preserve necessary info, delete it on current device and add it to the new device with a press of a button.

Nice idea. I have not considered that. I will do that and update this comment when I have something working.
