### ISSUE TITLE
SVG cable trace fails with only one end terminated in an interface

### ISSUE THREAD

**Issue by ulilaube** [netbox-community/netbox#7348]
### NetBox version

3.0.3

### Python version

3.9

### Steps to Reproduce

I upgradeded from 2.11.11 to 3.0.3. When clicking on the 'download SVG' Button or directly trying an URL like

https://192.168.122.15/api/dcim/interfaces/1019/trace/?render=svg

I get an error.
This trace has only one endpoint terminated in a switch interface, the one identified in the URL. The other end is "open" in some patch panel front or rear port. If I connect the open end to another switch interface the error goes away and I get the correct SVG. If I delete a patch cable from one of the switch interfaces to a patch panel front port the error reappears.

### Expected Behavior

An SVG of a partial trace would be cool. At minimum a message that a partial trace is not possible.

### Observed Behavior

I get a HTTP 500 internal server error with the following message:

```
<class 'AttributeError'>

'NoneType' object has no attribute 'get_absolute_url'
```

**Comment by DanSheps** [comment]
This should be fixed in #7294
