### ISSUE TITLE
No Dropdown Menus after upgrade

### ISSUE THREAD

**Issue by pthelen91** [netbox-community/netbox#7349]
### NetBox version

v3.0.3 

### Python version

3.8

### Steps to Reproduce

- Upgrade to Netbox v3.0.3 - 2021-09-20
- Select any Server and go to "edit"
- Try to change any value like "site" or "position"
- No dropdown menu appears, only the current option and ------- for delete

I attached 2 screens from the menus and the error shown in the developer options

### Expected Behavior

Dropdown Menus should appear 

### Observed Behavior

See Screenshot
![site](https://user-images.githubusercontent.com/74179101/134509827-3558eacd-55dc-45d1-8489-3f903adf0f38.png)
![position](https://user-images.githubusercontent.com/74179101/134509840-e09c7138-d2c3-4393-840e-caf8961696f9.png)

If I open the developer tools I see a CSRF error:
![devoptions](https://user-images.githubusercontent.com/74179101/134510213-6dc0835e-60e1-4ab4-8f22-0118c1675c4e.png)

**Comment by DanSheps** [comment]
Thank you for your interest in NetBox. GitHub issues are intended for reporting reproducible bugs and requesting features, and must be submitted using one of the templates provided [here](https://github.com/netbox-community/netbox/issues/new/choose). For general discussion, questions, or **assistance with installation issues**, please post to the [discussions](https://github.com/netbox-community/netbox/discussions) instead.
