### ISSUE TITLE
Rename "Report" to "Tests"

### ISSUE THREAD

**Issue by tb-killa** [netbox-community/netbox#7351]
### NetBox version

v3.0.3

### Feature type

Change to existing functionality

### Proposed functionality

Rename "Reports" to "Tests".

### Use case

Reports were added in Netbox to allowed the user to execute custom logic within NetBox and save output comprising discrete log messages to the database as a "report result." But from the Logic themselves, this Logic are more "Tests" as an active "Report". Custom Scripts in Netbox are Parts which are very similar to reports, but had the ability to process user input.
As there is substantial functional overlap between "Reports" and "Custom Scripts" , it could makes sense to merge the two features but from first of all the simplest Solution would be to rename "Reports" to "Tests" or another meaningful Name.

### Database changes

Rename Reports to "Tests" or another meaningful Name.

### External dependencies

None

**Comment by PieterL75** [comment]
To me, these are Reports... I get an overview of IP usage, get free vlans etc..
I dont really 'test' anything with it..

**Comment by tb-killa** [comment]
@PieterL75 Do you use "Reports" or "Custom Scripts" ??
I know that if someone know how to use them it will be usable but from the official stuff its completly more an "test"ing.

From the "https://netbox.readthedocs.io/en/stable/customization/reports/"

> A NetBox report is a mechanism for validating the integrity of data within NetBox. Running a report allows the user to verify that the objects defined within NetBox meet certain arbitrary conditions. For example, you can write reports to check that:

>All top-of-rack switches have a console connection
>Every router has a loopback interface with an IP address assigned
>Each interface description conforms to a standard format
>Every site has a minimum set of VLANs defined
>All IP addresses have a parent prefix
>...and so on. Reports are completely customizable, so there's practically no limit to what you can test for.

i think an "report" show be exactly what you actually mentioned, overviews and much more.

**Comment by jeremystretch** [comment]
The name "reports" is perfectly fine. Renaming it to tests would only introduce confusion.

**Comment by tb-killa** [comment]
What maybe could be an good replacement would be the naming "data integrity".
An Report would be something where an User is allowed to query for needing informations with something like https://pypi.org/project/django-sql-explorer/ (maybe oben new FR for it if you allowed?)
