### ISSUE TITLE
Flicker between light and dark mode

### ISSUE THREAD

**Issue by skalec** [netbox-community/netbox#7373]
### NetBox version

v3.0.3

### Python version

3.8

### Steps to Reproduce

1. Activate light mode in profile
2. Click one point of the left menu

### Expected Behavior

no flicker

### Observed Behavior

Every time I select a link in the menu, the menu briefly flickers in dark mode even though I have set the light mode

**Comment by jeremystretch** [comment]
> 2. Click one point of the left menu

What specifically are you clicking? Also, could you please note your browser & version? This type of issue is often browser-dependent.

**Comment by skalec** [comment]
I'm Using OS X 11.4

Safari Version 14.1.1 (16611.2.7.1.4)
Firefox 91.01

**Comment by zelfix** [comment]
I have the same problem on Firefox 92 and Chrome 93.0.4577.82 (Official Build) (x86_64)
![netbox_flicking](https://user-images.githubusercontent.com/10135380/134951373-30dd1784-2998-44ac-802d-3063d2b37e00.gif)
