### ISSUE TITLE
Device rack position grayed out when non-full depth device are on same RU

### ISSUE THREAD

**Issue by netgab** [netbox-community/netbox#7374]
### NetBox version

v3.0.3 (community docker image)

### Python version

3.9

### Steps to Reproduce

1. Create a standard 19" rack (e.g. 4 post)
2. Create a device type which is not a full-depth device
2. Create two device instances of the device type (deviceA and deviceB)
3. Place deviceA to the rack front RU40
4. Place deviceB to the rack rear RU40

Note: I wanted to reproduce it in the demo instance, but the outlined credentials admin/admin are not valid.

### Expected Behavior

Both devices (deviceA and deviceB) should be placed successfully in the rack.
deviceA => RU40 front
deviceB => RU40 rear

### Observed Behavior

deviceB cannot be placed to rack rear RU40. In the edit device dialog, when the rack and the rack face "rear" is selected, RU40 is not selectable (greyed out).
However in the rack view, RU40 in the rear is still free and a new device may be created there.
Using nbshell, deviceB can be assigned to the rack rear in the desired position.

Also check out the screenshots in the Google groups: https://groups.google.com/g/netbox-discuss/c/zgBhnTUiaHs/m/tMsrXVbrAwAJ

**Comment by DanSheps** [comment]
Thank you for opening a bug report. I was unable to reproduce the reported behavior on NetBox v3.0.3. Please re-confirm the reported behavior on the current stable release and adjust your post above as necessary. Remember to provide detailed steps that someone else can follow using a clean installation of NetBox to reproduce the issue. Remember to include the steps taken to create any initial objects or other data.

**Comment by DanSheps** [comment]
Scratch that.

You can add it from the rack view if you click on the rack u, but it is indeed grayed out in the selection box.

**Comment by netgab** [comment]
Wow, that was fast! Thank you for fixing this @DanSheps !
