### ISSUE TITLE
Change the display name of the "Filter" field at the top of searchable tables to "Search"

### ISSUE THREAD

**Issue by jhammond-git** [netbox-community/netbox#7375]
### NetBox version

v3.0.3

### Feature type

Change to existing functionality

### Proposed functionality

I didn't feel comfortable calling this a bug, but using "Filter" as a display name for the field at the top of searchable tables causes confusion with actual filters useable from the "Filter" tab.

The field could be called "Search", or "Search results", or something similar to separate it from actual filters.

### Use case

This separates the search field from the function of the Filters tab in the UI, and reduces confusion for users trying to take action on a filtered list of objects.

### Database changes

None.  Just a display change.

### External dependencies

None.

**Comment by jeremystretch** [comment]
It's a valid point. Maybe it would make more sense to rename the "Filters" tab to "Search?" I think there's been some confusion over what the filter widget actually does, but IMO "filter" is more accurate for it.

**Comment by jhammond-git** [comment]
In my opinion, "Filter" is fine for the static tab function.  The UI's that I've seen with both types of functions call the static function "Filter(s)", and use the dynamic field for "Search within results..."  Since you always have a dynamic field, I suggested simply "Search", but maybe users would be less confused by "Search within results..." than by "Filter".

I am not a UI designer.

**Comment by DanSheps** [comment]
Perhaps "Filter current displayed results"?

**Comment by jeremystretch** [comment]
I'm going to fold this under #7450 as part of a larger effort to clean up various parts of the UI.
