### ISSUE TITLE
Support the assignment of tags to objects during bulk CSV import

### ISSUE THREAD

**Issue by jeremystretch** [netbox-community/netbox#7376]
### NetBox version

v3.0.3

### Feature type

New functionality

### Proposed functionality

Enable the assignment of tags to objects during bulk import of CSV data. This was originally proposed specifically for IP addresses under #6420, but should apply to all objects which support tags.

### Use case

This would enable users to assign tags directly to objects at the time of creation, and avoid needing to edit objects in bulk later to add the tags.

**Comment by sdktr** [comment]
Probably above my knowledge level, but trying to get this to work and will submit fore review here

**Comment by beezed1** [comment]
Hi,

Are there any thoughts on when (or if) importing of tags would be added to Netbox?

Thanks
Phil

**Comment by sdktr** [comment]
Any hints @jeremystretch why my attempt at solving this results in an 'always required' tags column in the CSVimport?
https://github.com/sdktr/netbox/commit/1a73410d8d840f8c22da0852b1f04144fc1c94e9
