### ISSUE TITLE
Virtual Machine Memory display issue

### ISSUE THREAD

**Issue by adamboutcher** [netbox-community/netbox#7388]
### NetBox version

v3.0.0

### Python version

3.8

### Steps to Reproduce

1. Create/Edit Virtual Machine with a value in Memory.
2. View Virtual Machine.

### Expected Behavior

No extra "MB"

### Observed Behavior

Virtual Machines memory shows a stray "MB"

Values equivalent to Gigabytes
![image](https://user-images.githubusercontent.com/1911435/135140837-61ac02f6-bd5c-49a0-aab3-2400e05c4715.png)
![image](https://user-images.githubusercontent.com/1911435/135140879-c6e38e1d-8d7b-493b-89b4-cf2e4a8537d6.png)

Singular Megabyte Value
![image](https://user-images.githubusercontent.com/1911435/135141030-6037e194-1b67-464d-90a1-e94ff5a97bcb.png)

**Comment by jeremystretch** [comment]
Thank you for submitting this issue, however it appears that this topic has already been raised. Please see issue #7083 for further discussion.

**Comment by adamboutcher** [comment]
Apologies, I couldn't find it via search.
