### ISSUE TITLE
Clickable Tenant Group in Tenant list view

### ISSUE THREAD

**Issue by hagbarddenstore** [netbox-community/netbox#7389]
### NetBox version

v3.0.3

### Feature type

Change to existing functionality

### Proposed functionality

The Tenant Group column should be a LinkColumn instead of just a text column. (It works like this for other models in their list views)

### Use case

UX improvement

### Database changes

None

### External dependencies

None

**Comment by jeremystretch** [comment]
> should be a LinkColumn

Just an FYI, LinkColumn is deprecated. The recommended approach now per django-tables2 is to use `Column(linkify=True)`.
