### ISSUE TITLE
Tracing cables which fork into multiple paths

### ISSUE THREAD

**Issue by dssdss** [netbox-community/netbox#7396]
### NetBox version

v3.0.3

### Python version

3.9

### Steps to Reproduce

Steps to reproduce netbox installation:
docker-compose pull
docker-compose up -d

Some of our fiber mediaconverters have one Gigabit ethernet port and two fiber ports - RX and TX.
![image](https://user-images.githubusercontent.com/14805815/135276010-b2b0e251-7359-4a65-b84a-f58cd72a71fc.png)

So, I've emulated this type of mediaconverter as a path panel (due to your advice in https://github.com/netbox-community/netbox/issues/3442#issuecomment-523571625 I've connected rear ge1 port with 2 fron ports - rx and tx):
![image](https://user-images.githubusercontent.com/14805815/135277267-32ad2603-3107-46e4-91b2-fe38d580dc0b.png)

### Expected Behavior

.

### Observed Behavior

But when I call Cable Tracing from my switch interface, I've got message: "Path split!"
![image](https://user-images.githubusercontent.com/14805815/135277965-f968043a-5232-4024-a581-3a77d0834a62.png)

Is it bug, or I am doing something wrong? Due to https://github.com/netbox-community/netbox/issues/2633 the same situation was fixed...

**Comment by jeremystretch** [comment]
> Is it bug, or I am doing something wrong?

It's not a bug; what you've done with splitting out the Tx and Rx cables into separate paths isn't supported. You've told NetBox to trace from a single cable through a point where it's mapped to two separate cables, so the path split is expected.

You can fix this by modeling each step along the path as a single cable.

> Steps to reproduce netbox installation:
> docker-compose pull
> docker-compose up -d

For future reference, this is not sufficient detail for a bug report.

**Comment by DanSheps** [comment]
> Due to #2633 the same situation was fixed

Unfortunately this work had to be reverted (through a complete rewrite) due to the complexity of the cable trace logic

**Comment by dssdss** [comment]
Its a pity.... It would be great, if you'll can implement this feature. Such types of equipment are often found in the real world...

**Comment by jeremystretch** [comment]
Yes, and they can be accurately modeled in NetBox by using a single cable as I suggested.

**Comment by dssdss** [comment]
Yes, bit it still don't work when I press rx or tx interface on the "Cable trace for Interface GE12", I've got this:
![image](https://user-images.githubusercontent.com/14805815/135286776-fc8fae61-d358-4b0d-b84f-a9e2258a19a5.png)

All connections are presents:
![image](https://user-images.githubusercontent.com/14805815/135286904-30f2a4ad-3c11-4fdd-9255-117377415390.png)

And I've got the same result when I call the Trace from the front ports view of my mediaconverter:
![image](https://user-images.githubusercontent.com/14805815/135287579-5ffd68ba-2b20-4536-bb50-e17aa2b2cadd.png)
