### ISSUE TITLE
module 'dcim.forms' has no attribute 'VCMemberSelectForm'

### ISSUE THREAD

**Issue by cybarox** [netbox-community/netbox#7411]
### NetBox version

v3.0.4

### Python version

3.8

### Steps to Reproduce

1. create new virtual chassis with no members
https://demo.netbox.dev/dcim/virtual-chassis/1/
2. hit the add member button on virtual chassis view

### Expected Behavior

display form for adding new member

### Observed Behavior

Missing Attribute Error
```
<class 'AttributeError'>

module 'dcim.forms' has no attribute 'VCMemberSelectForm'

Python version: 3.8.10
NetBox version: 3.0.4
```

**Comment by jeremystretch** [comment]
Whoops, looks like I omitted this form from `__all__` during the recent refactor.
