### ISSUE TITLE
Error installing child device in vacant bay

### ISSUE THREAD

**Issue by salgua** [netbox-community/netbox#7412]
### NetBox version

v3.0.4

### Python version

3.8

### Steps to Reproduce

1. Open a parent device
2. Click on "device bays" tab
3. Click on the "+" button to install device 

### Expected Behavior

I should see the populate form to select the child device

### Observed Behavior

I receive the following error:

          Server Error
          There was a problem with your request. Please contact an administrator.
          
          The complete exception is provided below:
          
          <class 'AttributeError'>
          
          module 'dcim.forms' has no attribute 'PopulateDeviceBayForm'
          
          Python version: 3.8.10
          NetBox version: 3.0.4

**Comment by jeremystretch** [comment]
Looks related to #7411
