### ISSUE TITLE
Error on deletion of IP Addresses if filtered by tag

### ISSUE THREAD

**Issue by cybarox** [netbox-community/netbox#7417]
### NetBox version

v3.0.4

### Python version

3.8

### Steps to Reproduce

1. Create a tag
2. create one (or more) IP address(es) with assigned tag
3. filter IP addresses via tag
4. check mark all ips
5. click delete
6. confirm deletion
7. Error 

### Expected Behavior

Selected IPs get deleted

### Observed Behavior

Error on delete:
```
<class 'KeyError'>

'tag'

Python version: 3.8.10
NetBox version: 3.0.4
```

**Comment by cybarox** [comment]
Update: The IP addresses are deleted, but the search form is not reset and throws an error because there are no more IP objects with this tag.

**Comment by jeremystretch** [comment]
> 1. got to demo.netbox.dev

Per the bug report template:

> Additionally, **do not rely on the demo instance** for reproducing suspected bugs, as its data is prone to modification or deletion at any time.

Please revise your steps above to no rely on any demo data.
