### ISSUE TITLE
Allow two devices per rack row

### ISSUE THREAD

**Issue by salman79uk** [netbox-community/netbox#7420]
### NetBox version

v3.0.4.

### Feature type

Change to existing functionality

### Proposed functionality

Is it possible to allow two devices to be added to the same row of a rack. There are some devices that do not take up a whole width of the rack, so you can have 2 devices within the same row.
Currently, as far as I can see, only one device can be added to one row of a rack.

### Use case

An example situation, that I am currently facing is we have two Palo Alto PA-220 firewalls which are very small devices and we have two of them racked within the same U no of the rack. 
So we would like to represent this rack layout within netbox.

**Comment by jeremystretch** [comment]
Thank you for submitting this issue, however it appears that this topic has already been raised. Please see issue #6591 for further discussion.
