### ISSUE TITLE
Automatic data completion

### ISSUE THREAD

**Issue by rfl64** [netbox-community/netbox#7421]
### NetBox version

v3.0.4

### Feature type

New functionality

### Proposed functionality

Would be possible to enter Tenant and related data when a Site is selected for a new device?

### Use case

When I enter a new device I always must select Site, Tenant, Tenant Group, etc

I suppose a Site belongs to a Tenant, then selecting Site should be enought.

thanks

**Comment by jeremystretch** [comment]
> Would be possible to enter Tenant and related data when a Site is selected for a new device?

I understand your reasoning, however this requires assuming the user's intent. It's perfectly valid to have a device and its site assigned to different tenants, so we can't automatically make that assumption on behalf of the user.
