### ISSUE TITLE
Unknown field name '1' in custom field data. 

### ISSUE THREAD

**Issue by xsgb** [netbox-community/netbox#7423]
### NetBox version

v3.0.4

### Python version

3.8

### Steps to Reproduce

- Edit a virtual machine ( I change the status value )
- Send the form with Apply

Note: I had this issue on v2.9, I tought migrating to 3 might help but there's the same problem. We have about 15 custom fields for VM's. No one is called '1'.

### Expected Behavior

Value updated in the DB and no error.

### Observed Behavior

- See this error: Unknown field name '1' in custom field data. 
- Entry is not updated

Here's a debug log when I click on Apply", there's suspicious things
[debug.log.a.txt](https://github.com/netbox-community/netbox/files/7268632/debug.log.a.txt)

**Comment by jeremystretch** [comment]
Thank you for opening a bug report. Unfortunately, the information you have provided is not sufficient for someone else to attempt to reproduce the reported behavior. Remember, each bug report must include detailed steps that someone else can follow on a clean, empty NetBox installation to reproduce the exact problem you're experiencing. These instructions should include the creation of any involved objects, any configuration changes, and complete accounting of the actions being taken. Also be sure that your report does not reference data on the public NetBox demo, as that is subject to change at any time by an outside party and cannot be relied upon for bug reports.

**Comment by xsgb** [comment]
Hi,

I greatly appreciate and totally understand your answer. This will take a little time for my team to investigate and provide further information by **re-deploying another separated Netbox instance** and perform our virtual machine synchronization done by https://github.com/bb-Ricardo/netbox-sync to fill VM data. 

Maybe this script I just cited is responsible responsible but I'm not sure how he could alter the _custom_fields_ structure.

I'll append a comment once those information are ready. It's not yet our top priority. Don't mind a 2/3 days lag from our side.

Have a great day!

**Comment by jeremystretch** [comment]
> and perform our virtual machine synchronization done by https://github.com/bb-Ricardo/netbox-sync to fill VM data.

Please bear in mind that we cannot accept bug reports for anything that involves code outside of core NetBox project. Any reported bugs must be fully reproducible without any installed plugins or other ancillary code.

I'm going to close this for now as the required information is not available, but if you are able to reproduce the reported behavior using a stock NetBox installation, please comment again and I'll re-open it.
