### ISSUE TITLE
Filter interfaces/ports on virtualchassis_id

### ISSUE THREAD

**Issue by steffenschumacher** [netbox-community/netbox#7424]
### NetBox version

V2.11.3

### Feature type

New functionality

### Proposed functionality

For the interfaces API endpoint, it would be nice if one could filter on virtualchassis_id, beyond device_id. I imagine it would be fairly simply include, but it would need to be mutually exclusive with filtering on device_id.

### Use case

Efficiency in loading virtualchassis interfaces via one api request vs per-device requests

### Database changes

None

### External dependencies

None

**Comment by rhyser9** [comment]
_"...but it would need to be mutually exclusive with filtering on device_id"_
I don't see that this needs to be the case. In the same way that you could specify a region and then a site within that region, you could specify a virtual chassis and then the device within that chassis. This also could assist with narrowing down the options in the device form field

@jeremystretch I can implement this.

**Comment by steffenschumacher** [comment]
> _"...but it would need to be mutually exclusive with filtering on device_id"_ I don't see that this needs to be the case. 
True - if it’s not custom to in guard rails like this, that’s fine - guess users of the API are grownups😉
