### ISSUE TITLE
Select all -> edit selected on filtered objects causes unwanted objects to be modified

### ISSUE THREAD

**Issue by ziggekatten** [netbox-community/netbox#7427]
### NetBox version

v3.0.4

### Python version

3.9

### Steps to Reproduce

In Other->Tags, create a tag with name Test    
In DCIM -> Devices, add five devices of any kind with name: Bob-1 to Bob-5
In DCIM -> Devices, add five devices of any kind with name: Gupta-1 to Gupta-5
In the DCIM->Device list, select the Filter field ant type in "Gupta"
When the "Gupta" devices have been filtered out, click the tickbox "Name" (toggle all) to select all
Click edit selected
Add the Test tag to the objects an press apply
In the DCIM->Devices, now remove the filter

### Expected Behavior

Only the filtered objects with name "Gupta" should have been modified with the tag Test 

### Observed Behavior

All objects are modified and have the tag Test applied, including Bob-1 to 5

**Comment by ziggekatten** [comment]
Just tested 3.0.5, and this is not fixed.....

**Comment by jeremystretch** [comment]
It's fixed for me. You may need to force-refresh your browser after upgrading.

**Comment by ziggekatten** [comment]
I hate caching.....
