### ISSUE TITLE
Edit selected devices or other items

### ISSUE THREAD

**Issue by maxzapp** [netbox-community/netbox#7430]
### NetBox version

v3.0.3

### Python version

3.8

### Steps to Reproduce

Create 10 devices A1-A5 and B1 -B5
List all devices
You should  see all 10 devices
Got to the filter line (the line were you can enter free text) and enter A and return
You should now see only A1-A5
Check the checkbox close to name this should select all 5 devices A1-A5
Press edit selected devices
Change status to deprecated (expecting they were different before)
Select apply

### Expected Behavior

All devices A1-A5 have status deprecated

### Observed Behavior

All 10 devices A1-A5 and B1-B5 have status deprecated.

This can be found on any othr items not only devices

**Comment by jeremystretch** [comment]
Looks like @ziggekatten beat you to this by a couple hours with #7427.
