### ISSUE TITLE
Login page by default (including some updates)

### ISSUE THREAD

**Issue by EHRETic** [netbox-community/netbox#7431]
### NetBox version

v3.0.3

### Feature type

New functionality

### Proposed functionality

Hi,

When there is no logged on user, the default landing page is not the one with the login.
Giving the option (it is in my opinion good to let the choice) to choose the login page as a default would be a good update. It spares one click to login and feels more logic to first login, then have access to something 😉

Also, it would be nice to not display the internal server name & version in footer for security reasons if server is used externally and user is not logged in. Having this as an option would also be great.

### Use case

- default page to login --> spare one click and feel more standard
- hide the server name/version --> gives less information about the system when no user is logged

**Comment by jeremystretch** [comment]
If you want to force people to log into the UI, you can set `LOGIN_REQUIRED = True` in `configuration.py`. Otherwise, the home view will be displayed and they will have access to any views allowed under `EXEMPT_VIEW_PERMISSIONS`.

**Comment by EHRETic** [comment]
> LOGIN_REQUIRED

Hi,

Sorry for my misunderstanding and the "not trying", I didn't get the LOGIN_REQUIRED would actually do what I want.

But can we still consider the removal of server info as an extra optional security measure? 😉
