### ISSUE TITLE
Alphabetize objects in each subsection under global search

### ISSUE THREAD

**Issue by slash-proc** [netbox-community/netbox#7441]
### NetBox version

v3.0.5

### Feature type

Change to existing functionality

### Proposed functionality

Alphabetizing objects in each subsection under "All Objects" global search.

### Use case

When trying to specify a specific object in the "All Objects" search field at the top of a given netbox page, the objects under the categories Circuits, DCIM, IPAM, Tenancy and Virtualization are not sorted alphabetically. This makes it difficult to quickly pick the appropriate object when a given subsection has many objects in it (for instance under DCIM)

![image](https://user-images.githubusercontent.com/33379854/135992807-42ac11e8-4d49-47d8-9bb8-1dede865da97.png)

**Comment by jeremystretch** [comment]
I think personally I prefer them in the current order, which closely follows how they appear in the navigation menu, but open to other opinions.

**Comment by slash-proc** [comment]
Maybe I still just need to get used to 3.x... I concede that alphabetization is the wrong way to go about things however the DCIM section is cluttered and I found myself repeatedly scrolling up and down to find "Devices" in particular.

I have a couple ideas but nothing concrete so I'll just go ahead and close this issue. 

If I can come up with something better, I'll open a new issue with a properly thought-out suggestion.
