### ISSUE TITLE
"Configure Table" removes row action buttons

### ISSUE THREAD

**Issue by swoga** [netbox-community/netbox#7442]
### NetBox version

v3.0.5

### Python version

3.9

### Steps to Reproduce

1. Create device, with at least one interface
2. In the device properties, switch to the "Interfaces" tab
![image](https://user-images.githubusercontent.com/3697291/136027246-c1748a58-c0e3-4da4-800f-f5803b9b8a1c.png)
3. Click "Configure Table"
4. Add/Remove any field and "Save" or click "Save" without any changes, both trigger the behaviour

### Expected Behavior

Action buttons are still displayed for each row.
![image](https://user-images.githubusercontent.com/3697291/136027349-f386b67f-334b-4b43-9b9b-00583552afd1.png)

### Observed Behavior

A checkbox is shown instead of the buttons.
![image](https://user-images.githubusercontent.com/3697291/136027445-70055fbe-14f9-43e2-8fc8-a278b6b9ed91.png)

**Comment by jeremystretch** [comment]
Thank you for opening a bug report. Unfortunately, the information you have provided is not sufficient for someone else to attempt to reproduce the reported behavior. Remember, each bug report must include detailed steps that someone else can follow on a clean, empty NetBox installation to reproduce the exact problem you're experiencing. These instructions should include the creation of any involved objects, any configuration changes, and complete accounting of the actions being taken. **Also be sure that your report does not reference data on the public NetBox demo**, as that is subject to change at any time by an outside party and cannot be relied upon for bug reports.

**Comment by swoga** [comment]
I have revised the steps for reproduction to not mention the demo, and also added screenshots.

**Comment by cs-1** [comment]
This bug not only affects the Interfaces table but also Front Ports and Rear Ports table (if you don't have the default table view but adjusted it by clicking "Configure Table"). The same is true for the "Devices" view where you list all devices: if you used "Configure Table" to change the Table layout, the checkbox appears in the last row. Clicking "Reset" in "Configure Table" restores the default view without the checkbox in the last column. It's very likely that this occurs in all tables with the "Configure Table" option.
