### ISSUE TITLE
Two checkbox columns in interface view (instead of one)

### ISSUE THREAD

**Issue by cs-1** [netbox-community/netbox#7443]
### NetBox version

v3.0.5

### Python version

3.8

### Steps to Reproduce

1. Open device view of device with interfaces.
2. Open the Interfaces tab.
3. The table of interfaces contains two columns with checkboxes to select interfaces to edit.

### Expected Behavior

Only one column of checkboxes (in the first column of the table) should be present.

### Observed Behavior

Two columns are present that aren't interoperating properly:

- Selecting the "select all checkboxes" box in the header of the first column checks all checkboxes in the last column, too.
- Unselecting single checkboxes in the first column doesn't uncheck the corresponding checkbox in the last column.

This behaviour leads to the unintentional bulk editing of interfaces that shouldn't bet edited

![Screenshot 1: first and last column with checkboxes](https://user-images.githubusercontent.com/12844146/136029099-bdf35385-f169-4ad7-915e-d311ce067296.png)
![Screenshot 2: checking  all checkboxes](https://user-images.githubusercontent.com/12844146/136029107-8254eaf8-edb0-4e40-92ce-8f438c63bacd.png)
![Screenshot 3: unchecking single boxes in first column doesn't unselect box in last column](https://user-images.githubusercontent.com/12844146/136029113-b545520d-3c79-41a2-98b2-4ae492ec7f4f.png)
.

**Comment by jeremystretch** [comment]
Thank you for submitting this issue, however it appears that this topic has already been raised. Please see issue #7442 for further discussion.
