### ISSUE TITLE
GraphQL: timezone inconsistent with REST API

### ISSUE THREAD

**Issue by arjenvri** [netbox-community/netbox#7466]
### NetBox version

v3.0.5

### Python version

3.7

### Steps to Reproduce

1. Open the GraphiQL explorer
2.  Run the below query
```
  query {
    site_list(
      id: "454")
     {
      name
      time_zone
    }

  }
```

### Expected Behavior

GraphQL returns timezones as

AFRICA_LUBUMBASH
AMERICA_CAMPO_GRANDE

### Observed Behavior

The RESTAPI returns timezones in format

Africa/Lubumbashi
America/Campo Grande

For backwards compatibility it would be useful to return the same format or at least provide an option to do so if possible.

**Comment by ryanmerolle** [comment]
I think some of the graphql response need to be formatted more inline with the REST responses.

**Comment by jeremystretch** [comment]
Why would it matter? The two are entirely independent APIs. GraphQL seems to like defining constants for choice fields, so I'm not sure this even qualifies as a bug.

**Comment by ryanmerolle** [comment]
Not sure that its a bug, just a lack of parity given people moving from REST API to GraphQL will notice a lack of parity for items like this.  We can reclassify this as a FR if you prefer.

**Comment by ryanmerolle** [comment]
The fact that the graphql api does not match the output of the ui and rest api is not ideal, but I get a sense it's not a priority or a good ROI.  I'll retry to look into this a little more next week.

**Comment by jeremystretch** [comment]
I'm going to close this out both because no work has been done and because it will likely become moot per #9856.
