### ISSUE TITLE
New model additional_device_data

### ISSUE THREAD

**Issue by cybarox** [netbox-community/netbox#7487]
### NetBox version

v3.0.6

### Feature type

Data model extension

### Proposed functionality

Introduction of a new model type to store additional information about a device. Unlike a custom field (which is applied to the whole object type), sometimes information is needed that is only required by a specific device type. The fields could be defined similar to interfaces in the device type template and would then be inherited by the device. This gives more flexibility to store and filter the data and is a bit less complex than storing data in config_context. In addition, the new model may offer the possibility to restrict permissions via the tenent.

### Use case

Example of possible uses:
- purpose
- login banner
- motd
- company internal information about the device
- edge cases

### Database changes

- Extending object views
- Establish new model 

### External dependencies

no new dependencies

**Comment by cybarox** [comment]
Config contexts limit us in some use cases. For example: there is no way to filter the data in the config context on the server side, so we need additional logic on the client side to read or update individual fields. Also, we need to rewrite the entire context if we want to update only a specific field. The change history for individual fields is another issue. Furthermore, there is no way to set the fields in config context as mandatory.

**Comment by cybarox** [comment]
Developing a plugin would be my less preferred solution. I think that other NetBox users could also benefit from this additional data model. Maybe it also makes sense to extend this to more models than just devices.

**Comment by jeremystretch** [comment]
> I think that other NetBox users could also benefit from this additional data model.

Most probably will not, which is why no one else has proposed this extension. However those that would are sure to be interested in such a plugin.

I'm going to close this out as it's pretty much a textbook use case for a plugin.
