### ISSUE TITLE
Improve efficiency of UI layout

### ISSUE THREAD

**Issue by dreng** [netbox-community/netbox#7497]
### NetBox version

v3.0.6

### Feature type

Change to existing functionality

### Proposed functionality

The new UI offers a modern look but wastes a lot of space. This leads to a view where information seems to become less important than buttons and search fields. I'd like to ask if it is possible to consolidate some parts in order to get back space for interesting data.

Furthermore the font is (and has always been) quite big. I reduce the browser view to 80% since I use netbox in order to see more information. Reducing the font size is not absolutely necessary since it is always possible to reduce the browser view. Nevertheless I integrated the reduction into the following mockup.

This is what I propose:

Original new UI
![2021-09-23 09_58_26-Devices _ NetBox](https://user-images.githubusercontent.com/20901110/136511292-9f5ad6ef-1a39-4bab-be9a-532a5f238bd5.png)

Original new UI reduced to 80%
![2021-09-23 10_01_00-Devices _ NetBox](https://user-images.githubusercontent.com/20901110/136511302-c493be8e-a524-423d-a3a6-bd5a1126d969.png)

Consolidated new UI reduced to 80%
![2021-09-23 10_13_05-Devices _ NetBox](https://user-images.githubusercontent.com/20901110/136511309-7728725a-f24c-4fa5-899e-e4368b2b02c7.png)

Please notice that you can see only 10 lines of data in the original view but 17 with the proposed change.

### Use case

The proposed change leaves more space for the information you're interested in.

**Comment by jeremystretch** [comment]
Tagging this as `needs owner` for anyone who would like to propose specific improvements.
