### ISSUE TITLE
Show addressing info (e.g. first/last IP) under prefix view

### ISSUE THREAD

**Issue by swoga** [netbox-community/netbox#7498]
### NetBox version

v3.0.6

### Feature type

New functionality

### Proposed functionality

In the details of a prefix the last IP should be displayed.

I am unsure if a prefix that is not a pool should display the last usable IP address or the broadcast address.
I lean towards showing the broadcast address in all cases for consistency, but would not call the field the broadcast address, as this is not meaningful in all contexts (e.g., a pool).

![image](https://user-images.githubusercontent.com/3697291/136516504-d5ba67fd-3996-401f-80aa-9efa7027ef72.png)
_(The position in the table was chosen arbitrarily.)_

### Use case

Sometimes you need to assign the last IP of a prefix (e.g. for a gateway) and some subnet sizes (especially for IPv6) are not so easy to calculate in your head.

### Database changes

none

### External dependencies

none

**Comment by jeremystretch** [comment]
I think this has been mostly addressed under #7600, which now shows the first available IP in a prefix (if any).
