### ISSUE TITLE
Use git .mailmap file for consistent spelling of commit authors and emails

### ISSUE THREAD

**Issue by ypid** [netbox-community/netbox#7512]
### Proposed Changes

https://git-scm.com/docs/gitmailmap allows to fix names and Emails of git commits. This is often needed because commits should not be altered after being pushed and Emails and names can change or had typos.

### Justification

```
$ git shortlog -sn --email | grep -i stretch
  2710  Jeremy Stretch <jstretch@digitalocean.com>
  2590  Jeremy Stretch <stretch@packetlife.net>
   602  jeremystretch <jstretch@ns1.com>
   389  Jeremy Stretch <jeremy.stretch@networktocode.com>
   270  Jeremy Stretch <jeremy@netverity.dev>
   131  jeremystretch <jeremy@netverity.dev>
   108  Jeremy Stretch <jstretch@ns1.com>
     3  jeremystretch <stretch@packetlife.net>
```

With a `.mailmap` file, it prints:

```
$ git shortlog -sn --email | grep -i stretch
  6803  Jeremy Stretch <jstretch@ns1.com>
```

**Comment by jeremystretch** [comment]
While I see the benefit, this seems like the kind of thing that will result in a lot of "junk" PRs to update metadata over time.

**Comment by jeremystretch** [comment]
Closing this as there's been no further discussion.
