### ISSUE TITLE
No column VLAN Groups in the Prefixes overview

### ISSUE THREAD

**Issue by 9elfer** [netbox-community/netbox#7541]
### NetBox version

v3.0.7

### Python version

3.9

### Steps to Reproduce

Click on IPAM -> Prefixes
The overview is showing the information, but there is no option to add the VLAN Group to this view.

### Expected Behavior

The Prefixes overview should list the VLAN Group together with the VLAN, just like it is shown if an individual Prefixes entry is displayed.

### Observed Behavior

There is no option to see the VLAN Group, and it is not possible to add it via Table Configuration.

**Comment by jeremystretch** [comment]
This is expected. If you would like to propose adding the column, please resubmit your issue as a [feature request](https://github.com/netbox-community/netbox/issues/new?assignees=&labels=type%3A+feature&template=feature_request.yaml).
