### ISSUE TITLE
VLAN Group information in the Prefixes overview would help

### ISSUE THREAD

**Issue by 9elfer** [netbox-community/netbox#7542]
### NetBox version

v3.0.7

### Feature type

Change to existing functionality

### Proposed functionality

Extend the VLAN information on the Prefixes overview by also showing the VLAN Group information.

### Use case

VLANs can exist multiple times in an IPAM, and the distinguisher is the VLAN Group.
While in an individual Prefixes view the VLAN shows both the VLAN Group and the VLAN information, separated by a slash, in the Prefixes overview the VLAN column only shows the VLAN.
A similar display of VLAN Group/VLAN like in the individual Prefix would greatly improve the overview.

### Database changes

none

**Comment by jskoetsier** [comment]
Yes, would be very helpful!

**Comment by 9elfer** [comment]
I wonder whether this is looked into, as it is much more than just the "display".
As elwonk mentioned, the vlan group is not even exported which makes a reimport/migration of existing data impossible.

**Comment by jeremystretch** [comment]
Sounds like just adding a column for VLAN group to the prefix table (as a non-default column) would address this.

**Comment by rhyser9** [comment]
I can implement this.
