### ISSUE TITLE
Unification of interfaces with front and rear ports

### ISSUE THREAD

**Issue by sleepinggenius2** [netbox-community/netbox#7554]
### NetBox version

v3.0.7

### Feature type

Change to existing functionality

### Proposed functionality

This feature request would have a dependency on the implementation of #6346 and #7552.

The proposal would be be to eliminate the existing front and rear port models and replace them with interfaces and cross-connects. Multi-position rear ports could be implemented with breakout sub-interfaces. The one-to-one bridge connections or cross-connects would link the front and rear interfaces together, just like is done with front and rear ports today. Adding the ability to specify cross-connects as part of a device template would allow for consistency between the old and new implementations.

### Use case

There are a number of scenarios when interfaces have connectors that are currently only available through front and rear ports. Two examples I have seen frequently are F connectors on DOCSIS devices, like cable modems and CMTSes, and fixed fiber connectors on active optical equipment, especially for ROADM and PON.

In order to represent a bridged cable modem in the current platform, the only options I've figured out are to create a rear F Connector port with a front 8P8C port to be able to trace trough the device or an *Other* type interface to represent the HFC side and a regular copper FE or GE port to represent the LAN side. The second option is the only way that I've found to associate MAC and IP addresses to the interfaces. For an eMTA, the phone ports can be represented as 6P4C or 6P2C front ports in the first option, with relatively meaningless rear positions, but would also need to have an *Other* type in the second option. The workarounds for a cable modem are annoying, but trying to represent a CMTS in the current platform has been a real nightmare.

On an optical service card on a ROADM node, there's often a fixed fiber connector (usually LC) for the DWDM trunk and a pluggable for the client interface. Again, the trunk interface would need to be represented as an *Other* type in the current platform in order to document the correct optic type for the client interface. You often see this kind of fixed connector on a PON ONT as well.

Collapsing three models down into one should help from a user experience standpoint, by not having to remember whether it was a front port, rear port, or interface that you need to connect a cable to. I make this mistake all the time, especially when having to have front/rear ports for combiner/splitter or mux/demux, because the use of front and rear ports don't always relate to their actual positions on the device. There often has to be a balance between documentation for the engineering team and potential confusion for the field technicians. Combined with #7553, this could also finally allow us to be able to properly represent WDM networks, which would be amazing.

### Database changes

This shouldn't require any new fields, but might allow for eliminating some existing models.

### External dependencies

None

**Comment by jeremystretch** [comment]
> The proposal would be be to eliminate the existing front and rear port models and replace them with interfaces and cross-connects.

I'm just going to be honest here: This is a non-starter for me. We're not going to upend such a huge chunk of the data model for pretty much any reason as it would be enormously taxing and disruptive. It's just not something we're going to consider giving everything else biding for precious development time. Maybe it's something to consider in the distant future, but it's not worth considering any further at this point I'm afraid.

As @DanSheps points out, there may be better ways to model what you're trying to accomplish. Also of relevance is the new bridging functionality being introduced in v3.1 (#6346). I strongly recommend trying that out.
