### ISSUE TITLE
virtual-chassis position zero

### ISSUE THREAD

**Issue by PieterL75** [netbox-community/netbox#7564]
### NetBox version

v3.0.7

### Python version

3.7

### Steps to Reproduce

1. Create 2 devices
2. Create a new virtual chassis
3. Set the Initial position to zero
4. add the 2 devices
5. Create the Virtual Chassis

Next one, also related
1. Edit the virtual chassis
2. Set the posistions to 0 an 1
3. Save the VC
4. check the overview of devices in the VC

### Expected Behavior

A new VC is created with 2 members. with position 0 en 1.
The GUI shows the 0 and 1 position in a gray box

### Observed Behavior

The members are created with position 1 and 2.
![image](https://user-images.githubusercontent.com/74899468/137729793-9af7e016-45e8-4665-84e4-7e34b9ef8d0d.png)

After correcting: The position 0 is not displayed
![image](https://user-images.githubusercontent.com/74899468/137729634-9271bfcf-418a-4884-aeb6-cbfbc6bc712f.png)

**Comment by PieterL75** [comment]
First issue seems to be related to this : 
https://github.com/netbox-community/netbox/blob/16f5e233d0d779a9bb65d32ee5f2f83a3467d5f3/netbox/dcim/forms/object_create.py#L125
This will cause 'initial_position' to become '1' if the get('initial_position') equals to {int}0
a=0
b=a or 1
b becomes 1
It can be fixed with
```    initial_position = self.cleaned_data.get('initial_position') if initial_position != None else 1```


The second can be solved with this : 
https://github.com/netbox-community/netbox/blob/a1f271d7d9cb1728a5f97379c3af10cae6f3b633/netbox/utilities/templatetags/helpers.py#L378
Change that to 
```        'value': str(value),```

**Comment by PieterL75** [comment]
Junos has 0 for the first chassis id..

Ex
https://www.juniper.net/documentation/us/en/software/junos/virtual-chassis-mx/topics/ref/command/show-virtual-chassis-status-mx-series.html

Pieter


Op ma 18 okt. 2021 22:43 schreef Daniel Sheppard ***@***.***>:

**Comment by jeremystretch** [comment]
Argh. Fixed in 3cb8c5db2 but I typoed the commit message.
