### ISSUE TITLE
Power usage with UPS

### ISSUE THREAD

**Issue by sieuwe** [netbox-community/netbox#7565]
### NetBox version

v3.0.7

### Feature type

New functionality

### Proposed functionality

When using a UPS between a power feed and PDU you currently don't get any load displayed on the power feed or rack.
Power Panel --> Power Feed --> UPS --> PDU --> Device
Currently you should leave the UPS away to get a power usage.
If possible this way without infinite sub levels, only this one.

### Use case

It would be helpful to have this for people who use this as a buffer between PDU and power feed.

**Comment by joaolucasmacedo** [comment]
Looks like netbox traces only one layer of power draw. It would be very nice if it traces power even on series of PDUs between Power feed > UPS and devices.

**Comment by jeremystretch** [comment]
I'm not clear on what's being proposed here. Please take some time to describe in detail the proposed implementation. Examples would be fantastic.

**Comment by sieuwe** [comment]
Sorry for the late reply, but I was on vacation.
We've updated to v3.0.8 and it looks like this was fixed, though it was not mentioned in the release notes.
