### ISSUE TITLE
UI / exclusive filters

### ISSUE THREAD

**Issue by Ren60FHk** [netbox-community/netbox#7587]
### NetBox version

3.0.7

### Feature type

Change to existing functionality

### Proposed functionality

Exclusive filters for devices.

### Use case

I want to find all devices, but for not specific manufacturer. To be able to do this in current version, I must select all vendors, except one. If we have a lot of these, this task could be exhausting. Ability to exceptional filtering will give us more ergonomic search. Probably, this functionality could be extended beyond devices.

**Comment by jeremystretch** [comment]
> Exclusive filters for devices.

Please elaborate on the proposed implementation.

**Comment by Ren60FHk** [comment]
> > Exclusive filters for devices.
> 
> Please elaborate on the proposed implementation.

First of all, I'm talking solely about the UI. For example: if I want to find all devices except the devices by a vendor (manufacturer) A, I do the following:
1. Navigate to **Devices>Filters**.
2. Select all vendors except one, vendor A, and press the **Search** button.

If we have a couple of vendors, it's not a big problem. But if we have a lot of vendors, I find this not ergonomic. I want to be able  _except one_ than _select all except one_.
I propose the following: 
Probably quick and dirty - an ability of prepending the exclamation point to a manufacturer name (with a hint in the UI).
Something like this:
![Screenshot_2021-11-12_09-55-42](https://user-images.githubusercontent.com/54929420/141426157-f9372092-edd2-4f0a-82b1-cc57a2cf8b98.png)

As another solution, I see a drop down list opening by a clicking on the **Manufacturer** field in the **Filters** tab, with a more complicated logic for the selection: select all, select invert, select none, etc., something like in spreadsheets (WPS Office, MS Excel, OpenOffice, etc).
I hope I gave the clear explanation to you!

**Comment by jeremystretch** [comment]
It's not part of the UI, however NetBox does allow you to negate most filters by [appending the `__n` filter lookup](https://netbox.readthedocs.io/en/stable/rest-api/filtering/#lookup-expressions). We can look at adding support for this in the UI but I wanted to point it out.

**Comment by Ren60FHk** [comment]
> It's not part of the UI, however NetBox does allow you to negate most filters by [appending the `__n` filter lookup](https://netbox.readthedocs.io/en/stable/rest-api/filtering/#lookup-expressions). We can look at adding support for this in the UI but I wanted to point it out.

Got it.

**Comment by jeremystretch** [comment]
Actually, let's fold this into #7604, since negation is just one of several available lookups.
