### ISSUE TITLE
Rename optic type 128gfc-sfp28 to 128gfc-qsfp28 (Fibrechannel)

### ISSUE THREAD

**Issue by suom1** [netbox-community/netbox#7589]
### NetBox version

v3.0.7

### Python version

3.8

### Steps to Reproduce

Currently the 128G FC optic type is named `128gfc-sfp28`, which is wrong as it's not a SFP28 formfactor but a QSFP28.

### Expected Behavior

The optic type should be `128gfc-qsfp28` to be correct with the type of optic it is. 

### Observed Behavior

Problem was noticed when working on [netbox-community/devicetype-library#503](https://github.com/netbox-community/devicetype-library/pull/503).

**Comment by jeremystretch** [comment]
I'm going to bump this to v3.1.0 since the corrected value effects a breaking change.
