### ISSUE TITLE
"Unlink" button in interface table

### ISSUE THREAD

**Issue by hagbarddenstore** [netbox-community/netbox#7597]
### NetBox version

v3.0.8

### Feature type

Change to existing functionality

### Proposed functionality

In addition to the Delete button in the interface table on Virtual Machine/Device, add a button to disassociate an IP from the interface. The Delete button currently deletes the IP Address object from the database, something which might not always be desirable.

### Use case

The use case is to be able to keep history of the IP Address, which Devices/Virtual Machines it has been associated with and to be able to move an IP Address from thing A to thing B, without having to re-create it.

### Database changes

No change required, since the behaviour exists today, but from the other direction. (You can Edit an IP Address and de-select the associated object.)

### External dependencies

None

**Comment by jeremystretch** [comment]
Closing this as it's no longer pertinent to the UI in v3.0 and later. (IP addresses no longer appear in a nested table below interfaces.)
