### ISSUE TITLE
Front UI color in homepage

### ISSUE THREAD

**Issue by jk-onnet** [netbox-community/netbox#7602]
### NetBox version

v3.0.8

### Python version

3.9

### Steps to Reproduce

1. Browse NetBox website
2. Observe the homepage

### Expected Behavior

Blue color object name
![image](https://user-images.githubusercontent.com/85537520/138248077-d574e28b-4358-46e7-a767-e4bbbda06385.png)

### Observed Behavior

White color object name
![image](https://user-images.githubusercontent.com/85537520/138247980-d1776b40-ce1c-458d-8ebb-929b4e7bdebb.png)

**Comment by jeremystretch** [comment]
As @kkthxbye-code points out, this was an intentional change and won't be reversed.
