### ISSUE TITLE
Config Context differs between JSON / YAML

### ISSUE THREAD

**Issue by wols** [netbox-community/netbox#7635]
### NetBox version

v2.11.12

### Python version

3.7

### Steps to Reproduce

1. insert JSON data with escaped double quotes
```
{
    "ntp.keys": [
       "501 MD5 no_backslash_\"_in_front_of_double_quotes"
    ]
}
```
2. compare

JSON
```
"501 MD5 no_backslash_\"_in_front_of_double_quotes"
```
YAML
```
- 501 MD5 no_backslash_"_in_front_of_double_quotes
```

Would have been important to #4236
**Idea: save data base64-encoded in the database.**

### Expected Behavior

The same data view.

### Observed Behavior

The backslash is not recognized as an escape character.

**Comment by jeremystretch** [comment]
Closing for lack of response
