### ISSUE TITLE
PATCHing /api/dcim/interfaces/{id}/ without setting tagged_vlans drops tagged_vlans on interface

### ISSUE THREAD

**Issue by afics** [netbox-community/netbox#7652]
### NetBox version

v3.0.8 and v2.11.12

### Python version

3.7

### Steps to Reproduce

`PATCH`ing an interface at /api/interfaces/{id}/ with the "tagged_vlans" field missing removes all tagged VLANs from the interface.

To reproduce, please run [nb-api-bug-requests.py](https://github.com/netbox-community/netbox/files/7425941/nb-api-bug-requests.py.txt) like so `NETBOX_URL=http://netbox/ NETBOX_TOKEN=api-token python3 nb-api-bug-requests.py`

### Expected Behavior

`PATCH`ing an interface without `tagged_vlans` set should preserve already set tagged VLANs.
`nb-api-bug-requests.py` should return the following:
```
[{'display': 'test-vlan-29bed8aa-4cbd-43fa-844b-10e0fd27cf53 (1234)',
  'id': 7520,
  'name': 'test-vlan-29bed8aa-4cbd-43fa-844b-10e0fd27cf53',
  'url': 'http://netbox/api/ipam/vlans/7520/',
  'vid': 1234}]
[{'display': 'test-vlan-29bed8aa-4cbd-43fa-844b-10e0fd27cf53 (1234)',
  'id': 7520,
  'name': 'test-vlan-29bed8aa-4cbd-43fa-844b-10e0fd27cf53',
  'url': 'http://netbox/api/ipam/vlans/7520/',
  'vid': 1234}]
[{'display': 'test-vlan-29bed8aa-4cbd-43fa-844b-10e0fd27cf53 (1234)',
  'id': 7520,
  'name': 'test-vlan-29bed8aa-4cbd-43fa-844b-10e0fd27cf53',
  'url': 'http://netbox/api/ipam/vlans/7520/',
  'vid': 1234}]
[{'display': 'test-vlan-29bed8aa-4cbd-43fa-844b-10e0fd27cf53 (1234)',
  'id': 7520,
  'name': 'test-vlan-29bed8aa-4cbd-43fa-844b-10e0fd27cf53',
  'url': 'http://netbox/api/ipam/vlans/7520/',
  'vid': 1234}]
```

### Observed Behavior

After `PATCH`ing an interface `tagged_vlans` is empty. 
`nb-api-bug-requests.py` returns the following:
```
[{'display': 'test-vlan-29bed8aa-4cbd-43fa-844b-10e0fd27cf53 (1234)',
  'id': 7520,
  'name': 'test-vlan-29bed8aa-4cbd-43fa-844b-10e0fd27cf53',
  'url': 'http://netbox/api/ipam/vlans/7520/',
  'vid': 1234}]
[{'display': 'test-vlan-29bed8aa-4cbd-43fa-844b-10e0fd27cf53 (1234)',
  'id': 7520,
  'name': 'test-vlan-29bed8aa-4cbd-43fa-844b-10e0fd27cf53',
  'url': 'http://netbox/api/ipam/vlans/7520/',
  'vid': 1234}]
[]
[]
```

**Comment by jeremystretch** [comment]
When your script creates the interface, it doesn't specify an 802.1Q mode. The assigned VLANs are being cleared by the PATCH request because the mode is null. I can confirm that if the mode is set to `tagged` the assigned VLANs are preserved as expected.

**Comment by afics** [comment]
Hi @jeremystretch,

> I can confirm that if the mode is set to `tagged` the assigned VLANs are preserved as expected.
True, reproduced locally. I didn't notice that was missing, thanks!


Regards,
Armin
