### ISSUE TITLE
Changeable class on banner bar

### ISSUE THREAD

**Issue by hagbarddenstore** [netbox-community/netbox#7661]
### NetBox version

v3.0.8

### Feature type

Change to existing functionality

### Proposed functionality

Be able to change either the rendered template of the top/bottom banner or be able to set the classes it's rendered with. The cyan colour might not be what's wanted/needed for that banner.

### Use case

We use the banner to differentiate between development and production environments, where different production environments may contain information that's classified differently. It would be very helpful to further visualise the "danger" of each system by changing the background colour of the banners.

### Database changes

None

### External dependencies

None

**Comment by jeremystretch** [comment]
The simplest approach here is probably to just remove the hard-coded `<div>` element surrounding the banner content. For instance:

```
{% if config.BANNER_TOP %}
    {{ config.BANNER_TOP|safe }}
{% endif %}
```
