### ISSUE TITLE
Second vertical scrollbar appears in /virtualization/interfaces/ related to IP role popup

### ISSUE THREAD

**Issue by bluikko** [netbox-community/netbox#7666]
### NetBox version

v3.0.8

### Python version

3.8

### Steps to Reproduce

1. Create Virtual Machines and add Interfaces to those. Assign IP Addresses to Interfaces.
2. Set some IP Addresses to Role that causes a colored background for the IP Address (example: Reserved). The feature in #6881. Leave some IP Addresses with no specific Role so that they do not have the color background. ("bubble"? what to call it?)
2. (don't know if relevant) Set table to show: Name, Virtual Machine, IP Address, Enabled, Parent Interface, Description, Mode, Untagged VLAN, MAC Address. Since I do not use Descriptions each Interface fits on one line and does not wrap. But most Interfaces have both IPv4 + IPv6 address so it causes each Interface row to consist of 2 lines.
3. Go to /virtualization/interfaces/ and scroll around, keep mouse cursor over the IP Address column and don't touch mouse.
  Easiest way to make this issue visible is to first set the mouse over an IP Address with a Role so that the Role name popup appears and then leave mouse alone, start scrolling up/down with pgup/pgdown.
4. Scrolling up and down with pgup/pgdown buttons will cause a second vertical scrollbar to appear on the right and the scrolling is jerky (seems to pause when the second scroll bar appears), as depicted:

![image](https://user-images.githubusercontent.com/14869000/139202636-ba36832c-a737-462f-b58e-b8f792622743.png)

Mouse cursor is depicted with the red star.

This is Win10, Chrome fully updated, 1080p resolution.

### Expected Behavior

There should be only 1 scrollbar and scrolling should be smooth.

### Observed Behavior

A second vertical scrollbar appears to the right of the "real" scrollbar. Additionally scrolling up and down with pgup/pgdown is not smooth and is jerky - pauses when the second scrollbar appears.

The behavior does not happen if mouse is not over the IP Address column.

The second scrollbar seems to appear when the mouse is _scrolled_ with pgup/pgdown so that it hovers over the IP Address with a "Role color background". It does not happen if mouse is just moved around normally.

It is probably somehow caused by the Role name popup that appears when mouse hovers over IP Address with a specific Role from #6881.

**Comment by jeremystretch** [comment]
I'm not able to reproduce this behavior under either Firefox or Chrome. I will note that the display of IP addresses within interface tables was changed fairly recently under #7701, which may have already addressed the issue.

**Comment by bluikko** [comment]
Indeed, of course this does not happen anymore if the whole functionality was removed again.

Back to a wall of IP addresses all looking the same then, oh well.
