### ISSUE TITLE
View rack elevations from Locations

### ISSUE THREAD

**Issue by jasonyates** [netbox-community/netbox#7668]
### NetBox version

3.0.8

### Feature type

Change to existing functionality

### Proposed functionality

When viewing the list of locations (Sites -> Locations) there is the ability to click 'View Elevations' to see an overview of all rack elevations in a given location. 

However when looking at a specific location (e.g. Sites -> Locations -> My Location) there's some brief information about the location but no way to easily see the rack elevations for that location. Proposing either a link or tab to view the rack elevations quickly from this view.

### Use case

Speeds up the ability to find data. If i'm looking at a particular location I find I have to click several times to get to the elevation view, it would be great to speed up the ability to get to this view.

### Database changes

None

### External dependencies

None

**Comment by candlerb** [comment]
> To expand this, should the "View elevations" button apply to sites, site groups, and regions as well (both tables and detail views)? However, that may be a separate wider feature request.

Ref: #3152
