### ISSUE TITLE
Provider Network Service ID

### ISSUE THREAD

**Issue by ryanmerolle** [netbox-community/netbox#7681]
### NetBox version

v3.0.8

### Feature type

Data model extension

### Proposed functionality

Most Service Providers assign a Service ID to the provider networks.  It would be ideal if that were extended in the model.

The alternative is to just set a custom field for this, but I figure it is a common enough use case that the data model extension could be seen as reasonable.

### Use case

For those who setup multiple mesh / provider networks, or need to call out a provider network issue, it is ideal to be able to track the service id of such a network.

**Comment by ryanmerolle** [comment]
> I created a customfield 'line_tag' which can optionally do regex validation, I think this is better to create as a customfield. Circuit IDs and cables should be documented under the section which is made for it.

I'm not sure I understand why it's better as a customfield. That is a good option, I just propose updating the model since many VPLS providers allow you to provision multiple provider networks if you so choose.  They identify said networks with service ids.

**Comment by DanSheps** [comment]
I agree with Ryan, in a round about way.

Our provider has a circuit id and a "BPSO" so I think having an additional field is always good.

**Comment by jeremystretch** [comment]
> I created a customfield 'line_tag' which can optionally do regex validation, I think this is better to create as a customfield

FYI [custom validation](https://netbox.readthedocs.io/en/stable/customization/custom-validation/) was added for all fields in NetBox v3.0.
