### ISSUE TITLE
Example of power topology not shown in documentation

### ISSUE THREAD

**Issue by astifr** [netbox-community/netbox#7685]
### Change Type

Correction

### Area

Installation instructions

### Proposed Changes

Hi, in documentation there are an error when referencing the png here,
https://netbox.readthedocs.io/en/stable/core-functionality/power/
I think that you should change the path from 
`![Power distribution model](/media/power_distribution.png)`
to
`![Power distribution model](/docs/media/power_distribution.png)`

thanks

**Comment by bluikko** [comment]
A similar problem exists regarding cable trace image at:

https://netbox.readthedocs.io/en/stable/core-functionality/devices/

Or https://github.com/netbox-community/netbox/blob/master/docs/models/dcim/cable.md
