### ISSUE TITLE
Assign virtualization Clusters to a Location

### ISSUE THREAD

**Issue by bluikko** [netbox-community/netbox#7699]
### NetBox version

v3.0.8

### Feature type

Data model extension

### Proposed functionality

Virtualization clusters should be assignable to locations.

When the location function was added, clusters missed this option.

The open issue #6429 is similar and is marked as blocked by #6440 for better handling of "multi-model parent assignments". The same issue may affect this feature but I feel the use case is quite strong.

### Use case

Because Clusters are only assignable to Sites and not to Locations, the whole Locations feature is currently unusable for documentation that consist of both physical Devices and Virtual Machines.

It makes integrations very difficult if the physical location of Devices uses the Locations feature but location of Virtual Machines uses the Sites feature. So in practice both Devices and Virtual Machines then need to use Site for the physical location.

Adding Location for Clusters would allow to locate both Devices and Virtual Machines using Location.

### Database changes

Virtualization Clusters would need a parent Location.

### External dependencies

none

**Comment by jeremystretch** [comment]
Similarly, #9969 proposes also extending cluster assignments to site groups.

**Comment by ocient-cliimatta** [comment]
Yes, this makes it very difficult to use a location's config context on a Virtual machine, even though "Cluster" is available.

I assume that location would need to be assignable to a cluster for this to work? Currently it looks like only Sites are supported at that level.
