### ISSUE TITLE
Adjust prefix depth when showing child prefixes

### ISSUE THREAD

**Issue by HeavenBay** [netbox-community/netbox#7700]
### NetBox version

v3.0.8

### Feature type

Change to existing functionality

### Proposed functionality

Hi,

We have super-prefix 192.168.0.0/18 in Site1. And prefix 192.168.25.0/24 in Site2. When I filter prefixes by Site2 I see 192.168.25.0/24 as sub-prefix (with dot before it) but I do not see its parent parent-super-prefix from different site. I think that child prefix should not be as child in this case because I did not add super-prefix to its own Site2
![netbox_issue_2](https://user-images.githubusercontent.com/42742929/139578196-8fb2d017-7816-47ff-844b-5afc41db3017.png)
![netbox_issue_1](https://user-images.githubusercontent.com/42742929/139578197-93576fb3-4b15-411e-be15-834ec7b7a9b4.png)
.

### Use case

For example: I filter my list of prefixes for a Site2 with Depth = 0 and I do not see this child prefix! I also do not see super-prefix from different Site1 because of Site filter. So I started thinking that my Site2 does not have 192.168. prefixes. It is terrible if you try to create summarization for routing.

Thank you.

### Database changes

None

### External dependencies

None

**Comment by jeremystretch** [comment]
This looks like we just need a more flexible way to indicate when a prefix should be listed in the table with or without its hierarchical depth.

**Comment by DanSheps** [comment]
Another option, could we have it check and see if there is a "parent" view and just subtract the two depths?

**Comment by jeremystretch** [comment]
@DanSheps that's a clever idea. Just need to be sure we're passing sufficient context to the table under each view.

**Comment by DanSheps** [comment]
I am going to take this up, when I have time (hopefully soon)
