### ISSUE TITLE
Allow configuration of Netbox powerfeed defaults

### ISSUE THREAD

**Issue by gordonjcp** [netbox-community/netbox#7702]
### NetBox version

v3.0.7

### Feature type

Change to existing functionality

### Proposed functionality

At the moment the POWERFEED_VOLTAGE_DEFAULT, POWERFEED_AMPERAGE_DEFAULT and POWERFEED_MAX_UTILIZATION_DEFAULT are picked up from dcim/constants.py and set for typical US datacentre values.

It would be good to adapt that to allow them to pick up either the defaults in constants.py or defaults supplied from an environment variable or config file instead.

### Use case

This would remove a UX "papercut" for users outside of the US.

**Comment by jeremystretch** [comment]
I think this makes sense, but it probably lends itself more toward user-configurable preferences. Unfortunately we don't have any real framework in place for that yet. v3.1 will introduce support for toggling certain configuration parameters directly within the UI (see #5883); maybe that's a reasonable stopgap for now.

**Comment by jeremystretch** [comment]
Marking this as blocked by #7759 (currently planned for v3.2).

**Comment by jeremystretch** [comment]
This should be easily doable now with v3.2 finalized.

**Comment by huntabyte** [comment]
I will work to support this.

My thoughts are to let the user override the default values via the Preferences page under a 'Power' title.

The values would be prepopulated with the constant defaults and editable by the user.
