### ISSUE TITLE
Missing tags in available column selection from IP range table

### ISSUE THREAD

**Issue by cybarox** [netbox-community/netbox#7717]
### NetBox version

v3.0.8

### Python version

3.8

### Steps to Reproduce

1. Create ip-range with tag
2. open ip-range table
3. click configure table
4. tags is missing from available column seletion
<img width="798" alt="No tags in column selection" src="https://user-images.githubusercontent.com/60612073/139842341-d7542425-22c6-4418-a190-3f4af90a177c.png">

### Expected Behavior

tag column can be selected under available columns

### Observed Behavior

tag column is missing

**Comment by jeremystretch** [comment]
Looks like `'tags'` is missing from `IPRangeTable.Meta.fields`.

**Comment by cybarox** [comment]
@jeremystretch I've created a pull request for this issue

**Comment by jeremystretch** [comment]
Thanks @cybarox!

**Comment by cybarox** [comment]
@jeremystretch I've applied the change on my local installation and it seems there is more missing. `'tags'` is not defined in the table definiton. 
```
    tags = TagColumn(
        url_name='ipam:iprange_list'
    )
```
Do you need another PR for this?
