### ISSUE TITLE
Allow MultiObjectVar to accept input from URL in Custom Scripts

### ISSUE THREAD

**Issue by rodvand** [netbox-community/netbox#7720]
### NetBox version

v3.0.8

### Feature type

New functionality

### Proposed functionality

Allow a MultiObjectVar to be pre-filled using a URL. This currently works for ObjectVar. Example of ObjectVar script:
```
from extras.scripts import *
from virtualization.models import VirtualMachine

class ObjectVarTest(Script):
    vm = ObjectVar(
            model=VirtualMachine
            )

    def run(data, commit):
        pass
```

Here you can pre-fill the variable by passing `?vm=<ID>` like this https://your.netbox.install/extras/scripts/ob_var.ObjectVarTest/?vm=13.

Change the variable to a MultiObjectVar and try passing multiple values (https://your.netbox.install/extras/scripts/ob_var.ObjectVarTest/?vm=13&vm=37) . It does not currently work.

### Use case

Allow a user to go straight to a custom script with some data pre-filled.

### Database changes

None

**Comment by jeremystretch** [comment]
Really a bug rather than a feature. This works as expected with the same type of field elsewhere in NetBox.
