### ISSUE TITLE
Impossible to import data exported

### ISSUE THREAD

**Issue by delattreb** [netbox-community/netbox#7725]
### NetBox version

3.0.3

### Python version

3.7

### Steps to Reproduce

1. Export an object. Option All data
2. Modify name to import another data Example Name: SiteN1 -> SiteN2
3.  import the csv file
4. Error: Unexpected column header "Name" found
5. If I rename all column name in lower case the final error is an error server 

### Expected Behavior

By example: export a custom field data

You obtain a cvs file:
Name,Content types,Label,Type,Required,Description,Choices,Weight,Default,Filter logic
Contact Phone 2,DCIM > site,,Text,False,Téléphone secondaire du contact,[],99,,Loose

Then when you try to import this file you obtain this error:
Unexpected column header "Name" found.

### Observed Behavior

Unexpected column header "Name" found

**Comment by jeremystretch** [comment]
This is expected behavior. The import data must conform to the prescribed format, which often differs from the default export format for various reasons, depending on the model.

**Comment by delattreb** [comment]
Are you killing me ?
Import data just after export don't work.
Your column name doesn't match !

Cordialement
Bruno DELATTRE


Le mer. 3 nov. 2021 à 13:07, Jeremy Stretch ***@***.***> a
écrit :

**Comment by jeremystretch** [comment]
Do you see the CSV import form? Scroll down. There's a complete list of the supported fields. Your import data must match this.

**Comment by michaelmcdonald** [comment]
Why does the system export data in a format that it cannot then immediately import?
