### ISSUE TITLE
Add/Extend Inventory items to be part of a site

### ISSUE THREAD

**Issue by dejantep** [netbox-community/netbox#7726]
### NetBox version

v2.11.12

### Feature type

Data model extension

### Proposed functionality

Today we have inventory items as part of a device and that's fine. In fact you cannot create an inventory item unless it refers to a device.
What i propose is to extend this model with "Site" so that an inventory item can be assigned to either device and/or site.

In site overview there could be a "badge" under Stats stating number of overall inventory items. No need for tab. When you click on it it presents you with a list of ALL inventory items related to that site and its devices. 

### Use case

Use case for this is to have items like spare parts placed on site and be able to track them. I'm aware that this sounds like job for asset management software but it is really lightweight and from my perspective would be just enough. Full fledged asset software is overkill in this case. Not everybody needs huge IT asset management. Those who have it will not bother but those who don't would benefit from functionality

### Database changes

not sure really,

- New field in inventory table with reference to a site table.
- Make it mandatory
- Add badge inventory on site overview
- New view in site model

### External dependencies

none

**Comment by jeremystretch** [comment]
> Use case for this is to have items like spare parts placed on site and be able to track them.

I'm sorry, but we've already decided through past discussion that spares management is out of scope for NetBox. There are plenty of other tools (such as [Snipe-IT](https://snipeitapp.com/)) which fill this role, and trying to incorporate it in NetBox would only distract from the development of features which are better suited to it.
