### ISSUE TITLE
VlanGroup view 'add' vlan buttons broken

### ISSUE THREAD

**Issue by PieterL75** [netbox-community/netbox#7729]
### NetBox version

v3.0.8

### Python version

3.7

### Steps to Reproduce

1. create a vlan group
2. create some vlans in the vlan group
3. go to the vlangroup overview

### Expected Behavior

The 'x vlans available' used to be a clickable button, that creates a new vlan within the vlangroup

### Observed Behavior

![image](https://user-images.githubusercontent.com/74899468/140065834-49b70871-97e4-4c5e-9c60-79f45a4a4c3d.png)

The 'x vlans available' are no longer clickable

**Comment by rhyser9** [comment]
I can work on this.

**Comment by jeremystretch** [comment]
Fixed under PR #7828.
