### ISSUE TITLE
Additional status value on Device/Virtual Machine

### ISSUE THREAD

**Issue by ziggekatten** [netbox-community/netbox#7734]
### NetBox version

v3.0.8

### Feature type

New functionality

### Proposed functionality

Devices and Virtual machines have various statuses. Currently there is one called Decomissioning which makes sense during the work to decomission. What is missing is an status called Decomissioned, in effect when done, this status would be used on the device/vm.

### Use case

We would like to keep journal entries for dekomissioned objects some time, and deleting a device/vm deletes Journal entries. To be able to distinguish if a object are under decomissioning or if it is actually done, an additional Status would be good.

### Database changes

none

### External dependencies

none

**Comment by jeremystretch** [comment]
Both the device and virtual machine models already offer an "offline" status choice. Does this not meet your criteria above?

**Comment by ziggekatten** [comment]
Not really, as we use that for powered off machines (one example root CA servers) etc.

**Comment by DanSheps** [comment]
Related: #2394 #5180 #3401 #2045

(Hope this is all of them)

**Comment by DanSheps** [comment]
I think if you are not removing it from netbox, it should honestly go back to "Inventory" state.

**Comment by ziggekatten** [comment]
Well, inventory makes sense when you have a device/vm actually in existence, but yet not fully active. Example, switch arrived mounted, but yet not active in a sense that it takes traffic. In this state, we add the object to our CMDB. 

Now, since we already have a staus Decomissioning in netbox that by name define a intermediate state, it would in my view make sense to have a final status after decomissioning is done. Tags are great for many things, but clutter objects with tags just in specific cases, when a status field already exists seems ankward. 

Another thing to consider is when looking at Netbox data from the outside (dashboards/analytics), mixing fields with tags to represent the state causes unnecessary logic. 

Issue might seem trivial, but as a source of truth, it also feeds ecosystems outside the bare infra world.

**Comment by DanSheps** [comment]
What happens when you decommission the device?  Does it get disposed of?  Can it be reused?

**Comment by ziggekatten** [comment]
Some devices get reused, and are set to status inventory when so. 

But if they are scrapped, we would like to have status Decomissioned, thus keeping journal entries (for one year), and after that, delete them.

**Comment by jeremystretch** [comment]
Marking this as blocked by #8054. (If implemented, this issue will become moot.)

**Comment by jeremystretch** [comment]
#8054 has been implemented and the ability to define custom status choices will be available in NetBox v3.2.
