### ISSUE TITLE
When attaching an image to a rack "Create & Add Another" yields an error

### ISSUE THREAD

**Issue by cs-1** [netbox-community/netbox#7741]
### NetBox version

v3.0.9

### Python version

3.8

### Steps to Reproduce

1. Open a rack.
2. Click "+ Attach an image".
3. Enter a name for the image, select the image to upload.
4. Click "Create & Add Another"

### Expected Behavior

The first image is added and NetBox displays the mask to attach a second image.

### Observed Behavior

NetBox yields a Page Not Found error after adding the first image:

```
/extras/image-attachments/add/

The requested page does not exist.
```

The first image is added properly, however, it seems like the URL for adding another image is not correct. The path for adding the first image is

```
/extras/image-attachments/add/?content_type=dcim.rack&object_id=13
```

however, the path that "Create & Add Another" uses for the second image is simply

```
/extras/image-attachments/add/
```

with the `content_type` and `object_id` missing.

Adding single images (just clicking "Create") works as expected.

**Comment by danfiscus** [comment]
I encountered this bug on our installation as well, though I didn't quite track down the issue as well as you did! Looking forward to the patch for this
