### ISSUE TITLE
Drop asn field from dcim.Site

### ISSUE THREAD

**Issue by jeremystretch** [netbox-community/netbox#7743]
### Proposed Changes

Remove the `asn` field from the dcim.Site model.

### Justification

A new ASN model was introduced in v3.1 (#6732), to which the Site model has a many-to-many relationship. The static value field is no longer needed.

**Comment by DanSheps** [comment]
Should we deprecate the filter asn= and asn_id= or leave that and have those query against the ASN model instead?
