### ISSUE TITLE
Location Status

### ISSUE THREAD

**Issue by ryanmerolle** [netbox-community/netbox#7744]
### NetBox version

v3.0.9

### Feature type

Data model extension

### Proposed functionality

Add status to location object.  Add the same statuses as site model.

### Use case

Add status to Location.  For users tracking office suites, colocation cages, etc in a larger site that may have multiple locations under it, it would be ideal to allow for status to be associated to a location.

**Comment by DanSheps** [comment]
> Add status to Location. For users tracking office suites, colocation cages, etc in a larger site that may have multiple locations under it, it would be ideal to allow for status to be associated to a location.

What kind of statuses?  The same as site?  (Active, Planned, Staging, Decommissioning, Retired?)

**Comment by ryanmerolle** [comment]
Good catch.  Updated the issue.

**Comment by DanSheps** [comment]
Yeah, what you were posting made me think more about roles (Office, Datacenter, Comm Closet, Hallway, etc) then statuses
.  Maybe that could be an additional FR at some point

**Comment by ryanmerolle** [comment]
Location roles would be interesting.  Could just call it a location group similar to sites.
