### ISSUE TITLE
Select previously-uploaded photo to attach to another device

### ISSUE THREAD

**Issue by danfiscus** [netbox-community/netbox#7749]
### NetBox version

v3.0.8

### Feature type

Change to existing functionality

### Proposed functionality

When uploading a photo to attach to a device, I would like to have the option to select a photo which I have already uploaded and reuse it for another device. This functionality could be further expanded by presenting users the option to select multiple photos at a time to attach, and/or to filter the list of previously uploaded photos by recency or whether the photo was uploaded to another device within the same rack.
Alternatively, this idea could be expressed as sharing the same image between multiple devices, but not between an entire rack.

### Use case

We like to store images of the devices in our rack, but to save time we take photos of a few U at a time and upload the same photo to each device in that section of the rack. Unfortunately right now, attaching the same exact photo means re-uploading the image a second time, rather than being able to select from a list of photos uploaded in the past. Being able to attach the same photo multiple times without uploading and storing it separately saves storage space and reduces the time to attach images to entities in some cases.

**Comment by jeremystretch** [comment]
The ImageAttachment model associates a unique uploaded image with each instance, which aren't intended for reuse among multiple objects. For what you're describing, you're probably better off linking to an externally hosted image.

**Comment by jeremystretch** [comment]
I'm going to decline this proposal for a few reasons:

1. Supporting the reuse of an attachment for multiple objects greatly complicates the existing data model.
2. It's fair to assume this would be a pretty infrequent requirement.
3. A reasonable workaround would be to link to image attachments from within the comment fields of other objects.
