### ISSUE TITLE
Incorrect image link in docs/models/dcim/cable.md

### ISSUE THREAD

**Issue by candlerb** [netbox-community/netbox#7750]
### NetBox version

v3.0.9

### Python version

3.8

### Steps to Reproduce

1. Install v3.0.9 (and observe output of `./upgrade.sh`)
2. Navigate to `/static/docs/models/dcim/cable/`
    * Manual way: click the Docs link, Development, Models, dcim.Cable

### Expected Behavior

Valid links

### Observed Behavior

upgrade.sh gives the following warning:

```
WARNING  -  Documentation file 'models/dcim/cable.md' contains a link to 'models/media/models/dcim_cable_trace.png' which is not found in the documentation files.
```

The page `/static/docs/models/dcim/cable/` shows the broken link:

![image](https://user-images.githubusercontent.com/44789/140415494-e114ad14-a355-4111-a7c9-37921e78dec5.png)

I believe an extra `../` is required in the relative image URL.

**Comment by jeremystretch** [comment]
Unfortunately there's a limitation with the [markdown-include](https://github.com/cmacmackin/markdown-include) extension when included files reference embedded images. In order for the image to load properly at `/docs/core-functionality/devices/`, the path must be set to its current value. I've not identified a way to have it load on both pages reliably.

I think I'll just move the image to the core functionality page to avoid the issue.
