### ISSUE TITLE
VLANs in vLAN Groups with Scope Site group - Assignment issue

### ISSUE THREAD

**Issue by diabolic53** [netbox-community/netbox#7753]
### NetBox version

v3.0.9

### Python version

3.9

### Steps to Reproduce

Create a Cluster with no site 
Create VLAN group with scope Site Group. 
Create VLAN and assign to VLAN Group with scope site group 
Create VM 
Create interface 
allocate VLAN from VLAN Group. 

Scenario: Stretched clusters between 2 sites where the vlans are stretched between the  2 sites so the same VLAN ID is available in both sites and A VM can move freely between the 2 sites. 

### Expected Behavior

tag the vlan from the vlan group assigned to the site group 

### Observed Behavior

No vlans show up

**Comment by jeremystretch** [comment]
Thank you for opening a bug report. Unfortunately, the information you have provided is not sufficient for someone else to attempt to reproduce the reported behavior. Remember, each bug report must include detailed steps that someone else can follow on a clean, empty NetBox installation to reproduce the exact problem you're experiencing. These instructions should include the creation of any involved objects, any configuration changes, and complete accounting of the actions being taken. Also be sure that your report does not reference data on the public NetBox demo, as that is subject to change at any time by an outside party and cannot be relied upon for bug reports.

**Comment by jeremystretch** [comment]
Closing this as there's been no further response.
