### ISSUE TITLE
Status attribute of Virtual IP Address should be mandatory in FHRP group creation form

### ISSUE THREAD

**Issue by hoalex** [netbox-community/netbox#7768]
### NetBox version

v3.1-beta1

### Python version

3.8

### Steps to Reproduce

1. Navigate to "FHRP Groups" --> Add
2. Notice that the attribute "Status" under "Virtual IP Address" is optional

### Expected Behavior

I would expect the field to be mandatory, just as it is already the case in the IPAM IP Address model, where it's not possible to create an IP with an empty status.

### Observed Behavior

It's possible to leave the status field empty, resulting in a new IP address with an empty status (but when editing the IP address, the form defaults to a status of "Active").

**Comment by hoalex** [comment]
Thinking about it, making the status field mandatory would make it necessary to always enter an IP address when creating a new FHRP group, even if corresponding virtual IP addresses may already exist in Netbox.
Instead, what about giving the user the option to either a) create a new virtual IP address during FHRP group creation (like it is the case now) or b) re-use an existing IP address?

This could work similar to the "Add a new IP address" form that appears when assigning an IP to a device interface. This form gives the user the option between "Create" and "Assign IP", the latter allowing the user to search for an already existing IP address.

Let me know if I should close this bug report, and open a feature request instead.

**Comment by jeremystretch** [comment]
We just need to validate that a status has been selected if a new IP address is being created. There's other discussion in #7769 regarding your other point.
