### ISSUE TITLE
Group is required attribute on Contact object when using REST API

### ISSUE THREAD

**Issue by rodvand** [netbox-community/netbox#7771]
### NetBox version

v3.1-beta1

### Python version

3.8

### Steps to Reproduce

```
curl -X POST \
-H "Authorization: Token TOKEN" \
-H "Content-Type: application/json" \
-H "Accept: application/json; indent=4" \
https://NETBOX/api/tenancy/contacts/ \
--data '{
    "name": "Martin"
}'
```

### Expected Behavior

Contact is created.

### Observed Behavior

```
{
    "group": [
        "This field is required."
    ]
}
```

In the API docs the group attribute is set as required, while it is not (at least visibly) required in the NetBox UI.

Adding `"group": null` to the curl command allows the contact to be created.

**Comment by jeremystretch** [comment]
For anyone interested, this is a peculiar quirk of uniqueness validation within DRF. Because the `group` field is part of a uniqueness constraint, the serializer field _must_ have a value for it (even if that value is null).
