### ISSUE TITLE
Prefix search not match

### ISSUE THREAD

**Issue by kangver** [netbox-community/netbox#7779]
### NetBox version

v3.0.9

### Python version

3.8

### Steps to Reproduce

1. Make sure there is prefix in database i.e. 172.30.0.0/16

![image](https://user-images.githubusercontent.com/56177476/140874442-33fc23b3-dc0b-406b-9bd8-89885dff4596.png)

2. Navigate to IPAM > Prefixes > Fill the prefix in the quick find box. but noting found.

![image](https://user-images.githubusercontent.com/56177476/140874835-11f179de-07be-4417-bd77-31d8dafbabba.png)

### Expected Behavior

The prefixes should be appear after fill in the quick search box

### Observed Behavior

No any prefix found

**Comment by rodvand** [comment]
This is something that seems to bring great confusion, but the Quick Find is only searching the prefixes shown on the page. So if you've set the pagination size to be 100 it only searches the 100 prefixes shown, not your total 1571 prefixes. To search all prefixes you need to go to the Filter tab and search there.

**Comment by kangver** [comment]
Ahh.. Ok it really confused, If it work like you said, so it might not classify as a bug.  Thank you @rodvand
