### ISSUE TITLE
Indent child locations in Site view

### ISSUE THREAD

**Issue by jasonyates** [netbox-community/netbox#7783]
### NetBox version

3.0.9

### Feature type

Change to existing functionality

### Proposed functionality

When viewing a site the locations widget lists all parent and child locations with the same level of indentation (none). This can make it difficult to understand the relationship between parent/child locations. 

A few possible proposals:
* Intend child locations. The list is already ordered based on parent/child relationship so intending would improve usability.
* Change the icon of a child location to make it easily distinguishable from a parent.
* Make the location widget expand/collapse. Initially show only parents and allow the row to be clicked to expand to display children

### Use case

We operate a campus with multiple buildings, each building has multiple floors with 1-2 IDF's per floor. In Netbox, each building is defined as location with a child location per IDF. Visually the list when looking at the Site view is difficult to follow as all locations appear with the same hierarchy / indentation level.

**Comment by jasonyates** [comment]
PR submitted to bring this visually in line with /dcim/locations/

Example Before:
<img width="829" alt="Screenshot 2021-11-09 at 15 22 35" src="https://user-images.githubusercontent.com/242483/140952536-898e0161-3e67-4899-998b-084dbb864cfe.png">

Example After:
<img width="1009" alt="Screenshot 2021-11-09 at 15 21 45" src="https://user-images.githubusercontent.com/242483/140952506-8f7e9016-8128-40e7-a021-a190ca54dcd7.png">

**Comment by jeremystretch** [comment]
> The problem appears to be that padding-left no longer works in the site view template. Presumably with the recent changes to the bootstrap version.

Yes, it's rather annoying.
