### ISSUE TITLE
Config Context Support for Cluster Type

### ISSUE THREAD

**Issue by Joshi425** [netbox-community/netbox#7784]
### NetBox version

v3.0.2

### Feature type

Change to existing functionality

### Proposed functionality

Make it Possible to assign a Config Context to a Cluster Type. Currently only Cluster Group and Cluster are supported.
https://netbox.readthedocs.io/en/stable/models/extras/configcontext/

### Use case

It makes sense to support this imo, if you run multiply cluster types and want settings to apply for a cluster type.

**Comment by jeremystretch** [comment]
The implementation here is pretty straightforward, though I worry we may need to revisit the logic behind how context data is rendered before we extend the current model any further.
