### ISSUE TITLE
Device table not sortable by status

### ISSUE THREAD

**Issue by JulianJacobi** [netbox-community/netbox#7791]
### NetBox version

v3.0.9

### Python version

3.8

### Steps to Reproduce

1. Click on sidebar `Devices` -> `Device Bays`
2. On the displayed table's header click on `Status`

### Expected Behavior

Table is displayed reordered, by status

### Observed Behavior

Server Error

**Comment by kkthxbye-code** [comment]
Took a stab at fixing this. My django is pretty rusty, so let me know if I messed something up.
