### ISSUE TITLE
User defined port-types

### ISSUE THREAD

**Issue by vbarelds** [netbox-community/netbox#7793]
### NetBox version

v3.0.8

### Feature type

Change to existing functionality

### Proposed functionality

For the user to be able to add user-defined port types. 
Also asked in **#4371** but this request has been closed without a proper follow up. 

### Use case

In my case there is a device with multiple DVI inputs and outputs.
Since there is no correct port-type that can be selected the port-type cant be seen as a "source of truth".

**_Users are able to create a work around with custom field for Front and Rear ports. But this is not ideal since there are two port-type fields when using this work around_**

Also in the future there can be an new kind of port-types, you can't expect a user to wait until the desired port-type is available trough an update. So it would benefit the user to be able to add custom port-types.

Users should be able to add port-types in the same way tags are added. And when added selectable trough the port-type drop down menu.

### Database changes

A table for user-defined port-types

### External dependencies

None

**Comment by jeremystretch** [comment]
Please see [this answer in the FAQ](https://github.com/netbox-community/netbox/wiki/Frequently-Asked-Questions#how-can-i-add-new-interface-types) regarding why NetBox doesn't permit user-defined device component types.

> In my case there is a device with multiple DVI inputs and outputs.

NetBox's focus is network infrastructure; video is out of scope for the product.
