### ISSUE TITLE
Allow NetBox Homepage Customization

### ISSUE THREAD

**Issue by JFman98** [netbox-community/netbox#7797]
### NetBox version

v3.0.9

### Feature type

New functionality

### Proposed functionality

I am looking to be able to customize the layout of the home page. For example, our organization does not use Power and Circuits. I would like to hide these cards from the home page. Our organization also uses services and would like to see this under the IPAM card. We would also like to remove tenants from the Organization card. I propose creating a fully customizable home page to allow for quicker clicking on items rather than fishing though the side nav bar. This could be done possibly within user preferences.

### Use case

NetBox users would be able to have a dashboard that better corresponds to an organization's use-cases of NetBox.

**Comment by jeremystretch** [comment]
>  I propose creating a fully customizable home page to allow for quicker clicking on items rather than fishing though the side nav bar. This could be done possibly within user preferences.

Please edit your post above to include your detailed implementation proposal.

**Comment by JFman98** [comment]
> > I propose creating a fully customizable home page to allow for quicker clicking on items rather than fishing though the side nav bar. This could be done possibly within user preferences.
> 
> Please edit your post above to include your detailed implementation proposal.

I am not a developer. I am a systems admin looking for newer functionality for NetBox. I am not well versed with the backend of NetBox. What other information would you like me to provide?

**Comment by jeremystretch** [comment]
Unfortunately then it's a bit premature to open a feature request. You might consider starting a [discussion](https://github.com/netbox-community/netbox/discussions) to share your idea and use case, and see if you can find other interested parties to help flesh out a workable proposal. Once you have that prepared, you'll be ready to submit a complete feature request that can be evaluated for feasibility and priority.

**Comment by JFman98** [comment]
I will create a discussion for this. Sorry for putting this in the wrong spot!
