### ISSUE TITLE
Wireless Authentication allows PSK on Enterprise Type

### ISSUE THREAD

**Issue by sdktr** [netbox-community/netbox#7798]
### NetBox version

v3.1-beta

### Python version

3.9

### Steps to Reproduce

1. Create new wireless LAN with Authentication Type: WPA Enterprise and PSK: 1337

![image](https://user-images.githubusercontent.com/19833687/141155121-15724e09-d346-4196-bee4-bab05cefe77c.png)

### Expected Behavior

No PSK to be allowed when WPA Enterprise is chosen. WPA Enterprise dictates (?) the usage of a Radius backend to relay the EAP messages to. This authentication replaces the PreSharedKey.

Would be cool to model the actual radius backend used in this model. With a relation to a Service (property of device)?

### Observed Behavior

PSK can be stored irrespective of the Authentication Type

**Comment by andershagman** [comment]
There is "identity PSK" through RADIUS.

https://www.cisco.com/c/en/us/td/docs/wireless/controller/technotes/8-5/b_Identity_PSK_Feature_Deployment_Guide.html

**Comment by jeremystretch** [comment]
@andershagman that's true, though I'd expect we'd convey that in a field separate from the PSK field on the WLAN model since it has a different function. We don't currently model any RADIUS config, though it's certainly possible that it will be added in a future release.

**Comment by sdktr** [comment]
> There is "identity PSK" through RADIUS.
> 
> https://www.cisco.com/c/en/us/td/docs/wireless/controller/technotes/8-5/b_Identity_PSK_Feature_Deployment_Guide.html

Hm, based on this doc this iPSK is configured as a regular PSK in the wlan controller, but with additional AAA override settings. In that case it is a valid combination after all.

**Comment by jeremystretch** [comment]
Huh, ok. So keep it then?

**Comment by sdktr** [comment]
Doesn't feel logical, but appearantly prohibiting the combo is not matching real world configs as well. So I guess keep as is?
