### ISSUE TITLE
Ability to assign a Tenant to a Device Component

### ISSUE THREAD

**Issue by erdems** [netbox-community/netbox#7801]
### NetBox version

v3.0.9

### Feature type

Change to existing functionality

### Proposed functionality

Add ability to assign a tenant to various device components, mainly:

* Ports
* Device Bays
* Interfaces

### Use case

In a Datacenter Provider environment, some host customer equipment and/or allocate / rent device bays to multiple tenants. A similar scenario goes in case of logical routers where one or more ports are allocated to a logical router that is left for the tenant to manage as they please.

Another scenario is the use of some security-related USB dongles where the provider essentially rents ports for tenant dongles. At the moment, netbox can't plan or keep track of those without potentially excessive use of tags with the same tenant slug. Even so, this approach won't make those ports/dongles/whatever show in tenant's summary page.

### Database changes

Add a tenant_id field for device components, defaulting to NULL.

### External dependencies

None.

**Comment by jeremystretch** [comment]
This doesn't make any sense to me. Tenancy in NetBox implies ownership. It's not practical to have multiple tenants own different parts of a device. I'm afraid you're trying to extend the concept of tenancy beyond its intended purpose. It seems like tags and/or custom fields would better serve your use cases.

**Comment by erdems** [comment]
Understood. However, especially in case of Blade Chassis or GNF or similar devices that support the concept of multi-tenancy within a single chassis, a tenant is solely and directly allocated a blade or a logical router, for instance. Although I understand this may not imply ownership in the generic sense of netbox, as in the tenant can't come and collect that linecard etc., it still his theirs in terms of usage and management.

Do you think it would make sense to enhance the tenant's page to include / report custom fields or tags? IMHO, this would complicate things more.

**Comment by DanSheps** [comment]
> Understood. However, especially in case of Blade Chassis or GNF or similar devices that support the concept of multi-tenancy within a single chassis, a tenant is solely and directly allocated a blade or a logical router, for instance. Although I understand this may not imply ownership in the generic sense of netbox, as in the tenant can't come and collect that linecard etc., that particular part/component still is theirs in terms of usage and management.

In a blade or chassis configuration, the chassis should be modeled separately from the the blades.  The chassis should be owned by the provider (you) and the tenant shoudl be the owner of the blade which is slotted into one of the bays within the chassis.  ONAP/GNF, you should probably be modelling as a virtual device with the appropriate tenant defined.

**Comment by erdems** [comment]
Thanks Dan; indeed I agree blade/chassis configuration could (and possibly should) be handled that way. In case of a GNF for instance, the 'router' is in fact one or more line-cards that are often leased to the tenant but sometimes even owned by them. There's also the case of USB dongles plugged  to an UTN device where the dongles literally belong to the tenant. I guess it would be possible to treat the dongles as devices slotted in the ports, I'll give this a try.

Still, GNF's case looks problematic to me, maybe I'm missing a point.
