### ISSUE TITLE
Pressing return on image attachment form throws 404

### ISSUE THREAD

**Issue by jasonyates** [netbox-community/netbox#7811]
### NetBox version

3.0.9

### Python version

3.8

### Steps to Reproduce

1. Click Attach an Image to a rack / location / site
2. Select image file, give it a name
3. Hit Return to submit the form

The image is uploaded correctly but the form redirects to /extras/image-attachments/add/ and throws a 404 not found instead of back to the previous page

Note this ONLY happens when hitting return to submit the form. Selecting Create or Create & Add Another behaves as expected.

![Screenshot 2021-11-12 at 11 21 21](https://user-images.githubusercontent.com/242483/141459355-815ce925-4bc9-426e-9a44-7f3e5db03e7e.png)

### Expected Behavior

Form submits and redirects to previous page in line with clicking Create

### Observed Behavior

The image is uploaded correctly but the form redirects to /extras/image-attachments/add/ and throws a 404 not found instead of back to the previous page

**Comment by jeremystretch** [comment]
I'm not able to reproduce this on v3.0.10. It was probably fixed under #7741. @jasonyates can you confirm?

**Comment by jasonyates** [comment]
@jeremystretch confirmed, 3.0.10 does not throw a 404 error. Thanks!
