### ISSUE TITLE
redirect_url ignored when editing an interface

### ISSUE THREAD

**Issue by amit177** [netbox-community/netbox#7823]
### NetBox version

v3.0.10

### Python version

3.8

### Steps to Reproduce

1. Go to a device with an interface
2. Editing a field in the interface (ex, MAC Address)
3. Click Save

### Expected Behavior

After clicking Save, the page should redirect to the path in the `return_url` parameter

### Observed Behavior

After clicking Save, the page refreshes and the `return_url` parameter is removed, showing the exact same edit page.

**Comment by jeremystretch** [comment]
I'm not able to reproduce this on v3.0.10. After saving the form, I'm redirected back to the device interfaces list as expected.

**Comment by amit177** [comment]
Seems like it's not happening on the demo either, might be something with my install.

**Comment by amit177** [comment]
I am able to reproduce it again, seems like my steps were wrong.
Instead of clicking Save, click Enter on the keyboard.

**Comment by amit177** [comment]
@jeremystretch are you able to reproduce with the new steps ^?
