### ISSUE TITLE
IPAM Role

### ISSUE THREAD

**Issue by WizCraker** [netbox-community/netbox#7825]
### NetBox version

3.0.10

### Feature type

Change to existing functionality

### Proposed functionality

I was checking out the beta demo and noticed the roles for the IP addressing in the IPAM doesn't have Multicast. since the Help documentation says roles cannot be user defined anyway you could add Multicast as one of the standard roles? 

### Use case

I have been looking for a solution for keeping track of our Video Multicast addresses which are used for video broadcast sources for our IPTV & OTT services to our headend. NetBox looks like the perfect solution as it looks like in addition to the IPAM it will help us also keep track of our server and broadcasting infrastructure. 

It is a complete nightmare trying to keep track of multicast addresses in an organized fashion when dealing with hundreds of different broadcast sources (aka TV channels) which are either packaged in individual multicast (one-to-one) or multiple channels packaged inside of a single multicast. We are currently using spread sheets which you can imagine is a nightmare way to keep track of data since spread sheets is where data goes to die. :)

**Comment by zombah** [comment]
Are you sure multicast role alone will add any more flexibility for multicast documenting?  
There are ASM Multicast which is possible as Point-2-MultiPoint between
one source ip address and many destination addresses and SSM Multicast which is P2MP  
between one destination ip and many source ip addresses, so even for alot addresses  
with Multicast role you will need to connect them with f.e. tag's of channel names and  
tag's of source operator and etc.
Myself i segment them with different tags now.  
So it sounds like multicast is good target for plugin which can add P2MP or   
even MP2MP relations between ip addresses and add channel names to  
these groups and associate them with operator, reciever's tenants and etc.
