### ISSUE TITLE
Maintain backward compatibility with previous releases in REST API

### ISSUE THREAD

**Issue by jeremystretch** [netbox-community/netbox#7835]
### NetBox version

v3.1-beta1

### Feature type

New functionality

### Proposed functionality

Although NetBox's REST API supports versioning, it is limited to the current minor release at the time (e.g. `API-Version: 3.0` under NetBox v3.0); there is no backward compatibility with prior releases. I'd like to propose that, starting with v3.0, NetBox begin maintaining backward compatibility with prior REST API versions.

There are two DRF settings which control versioning support:

```python
REST_FRAMEWORK_VERSION = VERSION.rsplit('.', 1)[0]  # E.g. "v3.0"
REST_FRAMEWORK = {
    'ALLOWED_VERSIONS': [REST_FRAMEWORK_VERSION],
    ...
}
```

Under NetBox v3.1, `ALLOWED_VERSIONS` would become:

```python
['3.0', REST_FRAMEWORK_VERSION]
```

And under v3.2:

```python
['3.0', '3.1', REST_FRAMEWORK_VERSION]
```

Of course, it would be infeasible to support such backward compatibility indefinitely. Regarding how far back we should maintain compatibility, I'm open to suggestions, but two minor releases seems like a reasonable goal. (E.g. backward compatibility for v3.0 would be dropped in v3.3.) Backward compatibility would _not_ be provided across major releases (e.g. from v3.0 to v2.11).

In order to actually effect this support, we would need to retain a compatible version of each serializer for which a breaking change has been introduced. For example, in v3.1 the `cable_peer` field of InterfaceSerializer has been renamed to `link_peer`. If an API client requests v3.0, NetBox will return a serializer referencing this field by its old name.

The [DRF documentation](https://www.django-rest-framework.org/api-guide/versioning/#versioning-with-rest-framework) provides a rough idea how this should work, though we'll still need to figure out the ideal implementation.

### Use case

Enabling support for prior REST API versions will make it easier for users to upgrade NetBox. For example, NetBox can be upgraded from v3.0 to v3.1 while still serving clients which support only v3.0 of the REST API. These clients can [specify the desired API version](https://www.django-rest-framework.org/api-guide/versioning/#acceptheaderversioning), and NetBox will return compatible data.

**Comment by sdktr** [comment]
Sound like a huge benefit to get users to upgrade sooner, allowing old clients to upgrade gradually.

When this was raised earlier you were concerned about the amount of work it would imply on the maintainers. What changed your mind? Is the ns1 offering changing perspectives?

**Comment by jeremystretch** [comment]
I just think (hope?) we're in a much more stable place now than in the past, and better able to plan out API changes.

**Comment by jeremystretch** [comment]
The more I dig into this the more is seems like we would need to migrate to a versioned URL structure, unfortunately. It doesn't look like DRF has any mechanism to exclude new endpoints from old versions using `AcceptHeaderVersioning`. I'll need to spend some more time coming up with a solution for this. We won't be able to implement it for v3.0, but hopefully at some point in the future.
