### ISSUE TITLE
Focus on searchbar

### ISSUE THREAD

**Issue by PieterL75** [netbox-community/netbox#7839]
### NetBox version

v3.0.10

### Feature type

Change to existing functionality

### Proposed functionality

When opening netbox, I always have to click in the searchbox, before I can type.

It would be easier if the searchbox already has focus by default.
Only when there is a form to be completed, then the first field of the form needs to have the focus

### Use case

Less clicking

### Database changes

None

### External dependencies

None

**Comment by sdktr** [comment]
Makes sense, I'm a big fan of having netbox as a search provider in my browser.

When url bar has focus:
netbox <tab> router

Opens search result for 'router'

**Comment by DanSheps** [comment]
I don't think there is anything in here that enables netbox as a search provider in the browser

**Comment by PieterL75** [comment]
Just to clear my request. I don't want a search provider.. I just want to have the search field gets the focus when I open Netbox....


And you can easily add a search provider in modern browsers manually..
net -> https://netbox?q=%s

**Comment by PieterL75** [comment]
@jeremystretch I volunteer to take a shot at this and #8813

**Comment by PieterL75** [comment]
All attempts to use 'autofocus' failed. 
Seems that #7001 (by @thatmattlove) introduced a JS that set the focus to the content-container. If remove that focus, then the autofocus on the input field works perfect....
Now I have to think of a way to only focus on the content-container if no other fields have focus...

**Comment by adamboutcher** [comment]
Topics in this thread are linked to this: https://github.com/netbox-community/netbox/issues/9589
