### ISSUE TITLE
Exception when creating FHRP group

### ISSUE THREAD

**Issue by candlerb** [netbox-community/netbox#7849]
### NetBox version

v3.1-beta1

### Python version

3.8

### Steps to Reproduce

On <https://beta-demo.netbox.dev>:

* Select IPAM > FHRP Groups > Add (`/ipam/fhrp-groups/add/`)
* Select protocol VRRPv2
* Set Group ID 2
* In address enter `11.22.33.44`
* Click "Create"

### Expected Behavior

Either the FHRP group to be created; or a validation error that the given IP address doesn't exist.

### Observed Behavior

A KeyError exception is raised.

![image](https://user-images.githubusercontent.com/44789/142061464-7de9b006-c514-4273-93cb-1aab2363a04c.png)

**Comment by jeremystretch** [comment]
The error occurs because validation of the IP address fails (no mask was specified), however the form's `clean()` method expects a value to be present in the cleaned data.
