### ISSUE TITLE
Improve FHRP Group Assignments documentation in v3.1 beta

### ISSUE THREAD

**Issue by devon-mar** [netbox-community/netbox#7850]
### Change Type

Addition

### Area

Functionality/features

### Proposed Changes

The current documentation on [FHRP Group Assignment](https://netbox.readthedocs.io/en/feature/core-functionality/ipam/#fhrp-group-assignments) mentions that FHRP groups are assigned to device and VM interfaces but doesn't mention where/how to do it. 

I assumed that it would be on the "Edit Interface" or the "FHRP Group" page, but FHRP group assignment is actually done on the "Interface Details Page". This is inconsistent with other NetBox models. For example, IP assignment to devices/virtual machines is done on the "Edit" page, not the "IP Address Details" page.

I propose that the documentation mentions that assignment is done on the VM/device interface details page.

I can open a PR for this if this is a desired change.

**Comment by jeremystretch** [comment]
> This is inconsistent with other NetBox models.

This is very consistent with other models, as the assignment to an FHRP group is not done on the interface model itself, but rather through an intermediate model (FHRPGroupAssignment) which holds additional attributes of the assignment. Contact assignments work similarly, and this is also the reason images are not attached when editing an object, for example.
