### ISSUE TITLE
Interface Speed & Duplex

### ISSUE THREAD

**Issue by ryanmerolle** [netbox-community/netbox#7853]
### NetBox version

v3.0.10

### Feature type

Data model extension

### Proposed functionality

Generally NetBox should support most base functions an interface supports. One obvious function missing in the current model is the ability to set interface speed.

None of the maintainers could recall anyone ever requesting this, which is quite surprising.  I completed a rough search through the backlog of issues, and could not find anything obvious existing.

### Use case

There 2 possible use cases I am thinking of, but there could be more:

- People who want to hard set speed for whatever reason like removing auto-negotiation with fickle peer interfaces.
- People who want a way to track actual speed of a port without going into the granularity of tracking the SFP inserted into the port.  Example: SFP28 capable ports with SFP+ optics installed are currently hard to model.  A lot of people likely do not want to deal with the overhead of SFP management in Netbox, though that could become a thing later.

**Comment by sdktr** [comment]
I was surprised to find no 'auto negotiation'/duplex setting somewhere. Glad it's getting addressed, thumbs up

**Comment by jeremystretch** [comment]
I imagine we'll declare `speed` as a positive integer value, and provide a widget on the UI to select from one of several common predefined values, as we do today with circuit terminations. This will allow users to set the speed conveniently while still allowing the flexibility to define arbitrary speeds where necessary.

**Comment by DanSheps** [comment]
> forced to connect terrible equipment at 100/half

Building Systems
Alarm panels
Door locks

It is all produce from companies with little networking knowledge that rely on archic protocols like BACnet.

**Comment by sdktr** [comment]
+1 for facing a fixed duplex external connection sometimes
