### ISSUE TITLE
Interface filters page should display whether the interfaces are connected

### ISSUE THREAD

**Issue by hiddenman** [netbox-community/netbox#7856]
### NetBox version

v3.0.10

### Feature type

Change to existing functionality

### Proposed functionality

When we search for interfaces using Filters it would be great to see if found interfaces are connected or not.

Interface can be:

1. Not connected at all.
2. Connected but without cable attached
3. Not connected and with cable attached
4. Connected and with cable attached

When we open Interfaces tab of a particular device it's easy to understand connection status of each interface (they have different colors).
When we list them using Filters, it's not possible to understand.  Furthermore, there is a column "Mark connected" and it's always False even for interfaces with cables attached and this confuses users (what is it for?)

So it would be great to display found interfaces with different colors (red and green) and display a special column with "_occupied" option from the API.

### Use case

A simple use case:  

- there are two identical devices with some free ports on each
- we want to find a pair of free ports (not connected) on each device, of the same type to setup main and backup connection to a customer on each device (cluster)
- we also want to know if each port contains an SFP module with required capabilities; however that's not possible at all right now until https://github.com/netbox-community/netbox/issues/7846 is done

Right now it's not possible to find and understand this using built-in Filters UI.

**Comment by DanSheps** [comment]
There is 1 status you forgot.  You can "plan" a connection

**Comment by jeremystretch** [comment]
> When we list them using Filters, it's not possible to understand.

Click the "Configure" button at the top right of the interfaces list. You can add the cable and connection columns to the table to expose this information, just like under the device view.

> Furthermore, there is a column "Mark connected" and it's always False even for interfaces with cables attached and this confuses users (what is it for?)

This column shows the value of the "Mark as connected" field, which is provided to allow denoting that an interface is occupied without modeling the attached cable in NetBox.
