### ISSUE TITLE
In v3.1-beta1 the API version shows just 3, not 3.1 (or similar)

### ISSUE THREAD

**Issue by markkuleinio** [netbox-community/netbox#7893]
### NetBox version

v3.1-beta1

### Python version

3.7

### Steps to Reproduce

```
$ curl -s http://netbox31beta.lein.io/api/ -i -H "Content-Type: application/json" | grep API-Version
```

### Expected Behavior

```
$ curl -s http://netbox31beta.lein.io/api/ -i -H "Content-Type: application/json" | grep API-Version
API-Version: 3.1
```

### Observed Behavior

```
$ curl -s http://netbox31beta.lein.io/api/ -i -H "Content-Type: application/json" | grep API-Version
API-Version: 3
```

Not sure if this is somehow related to https://github.com/netbox-community/netbox/issues/7835 (maintaining backward compatibility).

**Comment by jeremystretch** [comment]
Nice catch. Coincidentally, I just fixed this the other day in 1c9d39d3e6b1dffa46cf84b79566bed260e03401. Probably should have opened a bug for it myself.
