### ISSUE TITLE
Cables Filters -> Search does not search all fields

### ISSUE THREAD

**Issue by jasonyates** [netbox-community/netbox#7908]
### NetBox version

3.0.10

### Python version

3.8

### Steps to Reproduce

Navigate to Connections -> Cables -> Filter
Search using the "All Fields" option.

### Expected Behavior

All fields are searched. Results are returned when a cable matches any A or Z side

### Observed Behavior

Searching using the All Fields option does not return any cables when searching using the device name. It only appears to search the label field.

Example in screenshots below. Searching for all cables from device K1-MDF-RA3-FP1-C1 reveals 6. Searching with that device in the Search field, reveals 0.
<img width="570" alt="Screenshot 2021-11-22 at 16 14 23" src="https://user-images.githubusercontent.com/242483/142953826-34315805-b195-48d8-b121-0541999c2a9e.png">

<img width="841" alt="Screenshot 2021-11-22 at 16 14 34" src="https://user-images.githubusercontent.com/242483/142953829-ad5bdd32-42df-4891-bcb5-d39bf138b789.png">

**Comment by jeremystretch** [comment]
Thank you for opening a bug report. Unfortunately, the information you have provided is not sufficient for someone else to attempt to reproduce the reported behavior. Remember, each bug report must include detailed steps that someone else can follow on a clean, empty NetBox installation to reproduce the exact problem you're experiencing. These instructions should include the creation of any involved objects, any configuration changes, and complete accounting of the actions being taken. Also be sure that your report does not reference data on the public NetBox demo, as that is subject to change at any time by an outside party and cannot be relied upon for bug reports.

**Comment by jeremystretch** [comment]
Closing this as there's been no further response.
