### ISSUE TITLE
Ability to search for cables with specific A & B side

### ISSUE THREAD

**Issue by jasonyates** [netbox-community/netbox#7909]
### NetBox version

3.0.10

### Feature type

New functionality

### Proposed functionality

The search function for cables is very restrictive when large cable plants are modelled. 

I have racks with 600+ terminations and I don't always know the exact device i'm looking for when planing a new A -> B connection. The ability to search for all cables between two specific racks or devices would be useful currently filtering by racks will show all connections within that rack. 

Perhaps expand the search function to have A Side Rack / B Side Rack / A Side Device / B Side Device 

### Use case

The search function for cables is very restrictive when large cable plants are modelled, the currently search feature does not allow for easy searching of a cable run between two specific locations.

**Comment by jeremystretch** [comment]
It's not clear what you're proposing here. Please detail a scenario, what you've tried using the current filters, what filter(s) you're proposing be added, and how the results they return would differ.

**Comment by jeremystretch** [comment]
Closing this as there's been no further response.
