### ISSUE TITLE
Add Form Factor to power outlet/port

### ISSUE THREAD

**Issue by elmmare** [netbox-community/netbox#792]
I'm tracing the power connection between:
     devices - rack PDUs
     rack PDUs - Power Panels
using Power Outlet and Power Port items.

A better description of the real world should include a "Form Factor" field describing the port/outlet connector. (as we have on interface "Form Factor")

Some of the values are:
IEC60320       (usually found on device and pdu outlet)
    C13
    C14
    C19
    C20

IEC60309     (usually found in PDU inlet )
    32A (2P+E)
    32A (3P+N+E)
NEMA
  ...

 
Adding a an "icon" field can further help (http://www.internationalconfig.com/): 
![c-20](https://cloud.githubusercontent.com/assets/25077391/21887480/52b11be6-d8c0-11e6-869e-3fa235266ccb.png)
![c-19](https://cloud.githubusercontent.com/assets/25077391/21887481/52b139be-d8c0-11e6-9074-1223fe7e784a.png)
![iec-60309-20-16amp230-400volt 1](https://cloud.githubusercontent.com/assets/25077391/21887546/a6bb81c2-d8c0-11e6-9c4d-5e2058ac56f6.png)
![iec-60309-30-32amp230-400volt 1](https://cloud.githubusercontent.com/assets/25077391/21887545/a6bb8c62-d8c0-11e6-9c97-8aaa8cda5d06.png)
![iec-60309-20-15amp250volt 1](https://cloud.githubusercontent.com/assets/25077391/21887544/a6bb1a70-d8c0-11e6-8506-6114f5e929ab.png)
![iec-60309-30-32amp230volt 1](https://cloud.githubusercontent.com/assets/25077391/21887547/a6bbe2d4-d8c0-11e6-8b3a-70a96fbeef52.png)

**Comment by jeremystretch** [comment]
This is something I've had on the back burner for a while, but there's a lot more that needs to be added along with this (circuit amperage, voltage, phase, etc.), so I'm going to mark it as a major feature.

**Comment by rc5hack** [comment]
adding also an optional "color" option for each outlet sounds like a good addition here (some PDU could have different colors outlets of the same type, e.g. black outlet is normal, and red outlet is UPS-backuped)

**Comment by jsenecal** [comment]
We also got rack PDUs with a color per phase. black-gray-white

**Comment by bmsmithvb** [comment]
Is it possible to obtain 0U rack PDUs?

**Comment by jeremystretch** [comment]
@bmsmithvb Yes, very easily. Just set the device type's height to 0U.

**Comment by puck** [comment]
If colours per phase are implemented, then they'll need to be customisable. We use different colours in NZ.

**Comment by jasonguy** [comment]
It is common practice in many DCs to mount the long PDUs (like a 24-port APC), vertically on the back of a rack. I set it as an unracked device currently, however it would be cool to add something to the graphical rack view, showing the vertically mounted PDU. This could also simply be displayed on the PDU detail page, along with information from the smart PDU.

**Comment by wrouesnel** [comment]
Technically then you'd like to also mark a vertical PDU by what side of the housing its on (important if you were trying to tell someone which phase to unplug / replug).

**Comment by fischa** [comment]
We use PDUs that have all or some switchable power outlets. Would be nice to have that as Boolean or yes/no field available too.

**Comment by falz** [comment]
Also give consideration to DC power. We recently begun testing Netbox and added some DC fuse panels as power connections. 

Here are a few examples of DC panels that we, and likely others use. Between these two, there are 3 different fuse types. There are certainly many others as well:

http://www.trimminc.com/download/8271001001.pdf - 4x4 TPA + 5x5 GMT
http://www.trimminc.com/download/7272101001.pdf - 8x8 TPM

.. each fuse type can have different amperage (1, 3, 5, 10... etc). In our case everything worked just fine as-is, we labeled the power outlets as "TPA A[1-4] and "TPA B[1-4]".

The only important piece we were unable to document was fuse size (amps) and DC voltage (-48v). Voltage, at least in our case, is always static as we've standardized on -48v DC.

**Comment by DocCox** [comment]
My team primarily works in DC environments - and power mapping is what keeps us considering different DCIM tools. We ended up with a home rolled flask solution but there's just not enough time to maintain it so Netbox is up for consideration

For DC power on the internal tool we used the following
Cable gauge
Cable color (helpful - different standards are everywhere)
Cable length
Cable battery/return
A/Z side terminations (Lug type/length/spacing/holes)

Fuse panels typically support 1 or more type of fuses/breakers now. Fuses had
Amperage
Form factor
Losses

Panels themselves had
Inputs/outputs with the above A/Z termination points
Internal Busses

The buses had
Compatible form factor(s)
Qty of connectors
Maximum amperage (By bus and form factor)
(Ex: In those 4x5 TPA/GMT panels its not uncommon to see 100-200A rating for the TPA bus and a 60A rating on the GMT bus. I see guys loading 60A GMT buses to 80A+ pretty frequently, or throwing 20A GMT fuses in a bus rated for 15A fuses.)



Just glancing over the version of netbox I have locally everything looks pretty close to whats needed
Fuse panels could be treated as chassis, busses would more or less be cards/modules, and the power runs over the existing port setup. Power could calculate fairly accurately from the top most device in the chain with this sort of setup - in some of our locations we own the whole shebang and in other vendors are providing us power to our BDFBs/inverters or straight to fuse panels

**Comment by bluikko** [comment]
I would like to add my 2 cents in this feature request: if 0U vertical devices (my use case is large PDUs) are somehow rendered in rack views, please allow at least 3 of them horizontally and/or on the "depth axis".

**Comment by jeremystretch** [comment]
Adding this as reference material: https://twitter.com/network_phil/status/1181563103034724352

**Comment by pyro3d** [comment]
+1 for more DC support. Have a number of devices off rectifiers+battery strings or off a PDU in a CO where it's needed. Copper grounding bars would also be nice.

**Comment by jeremystretch** [comment]
I'm having a difficult time determining what to include for the plug/outlet types. It seems there are several series of standards:

* [IEC 60320](https://en.wikipedia.org/wiki/IEC_60320) (the CXX types)
* Four (or 12?) different [IEC 60309](https://en.wikipedia.org/wiki/IEC_60309) arrangements
* US [NEMA](https://en.wikipedia.org/wiki/NEMA_connector)
* European [CEE 7](https://en.wikipedia.org/wiki/CEE_7_standard_AC_plugs_and_sockets)
* [ITA letter types](https://www.worldstandards.eu/electricity/plugs-and-sockets/), which overlap with various international standards

Does it make sense to include the ITA types (A through O) as their own types, even though they technically overlap with other standards? (For example, type A is the same as NEMA 1-15.) If not, we could just list individual country-specific types as their own series.

**Comment by swerveshot** [comment]
Hi @jeremystretch! For your information; in the Netherlands we mostly encounter IEC 60320 (C13/14 and C19/C20) in the datacenter. And occasionally a CEE 7 'shuko' type plug.

**Comment by jeremystretch** [comment]
This work is mostly done, but leaving the issue open for additional feedback regarding specific types.

**Comment by bluikko** [comment]
Can you confirm that "universal" outlet sockets are supported?

I have to admit that we have a few rack-mount "PDU"s with these for random power bricks. Here is an example of how the sockets look:
https://www.havells.com/content/dam/havells/consumer/switches/Fabio-modular-range/sockets/AHFKUXW133/cover.png

**Comment by ThomasADavis** [comment]
Ok, just found this..

1) We have racks that have hardwired connections in them - so please add 'hardwired'.

2) We have systems coming in that will have 150A power feeds.  The current feed max is about ~100A - I get:

```
<class 'django.db.utils.DataError'>

smallint out of range
```

Getting into the 1200A or better range for feeds can mean I create feeds from the substations all the way to rack.  In case your wondering what the high current is used for, it's what a supercomputer cabinet pulls.  :)

thanks!
thomas

**Comment by brotherdust** [comment]
I have many devices that use coaxial power connectors. Would it make sense to add these standards as well?
https://en.wikipedia.org/wiki/Coaxial_power_connector

In my use case, the coaxial connectors are feeding from a power brick (usually C14) or they are spliced into a DC power bus. Would it also make sense to have a way to track if the device uses a power brick and the specifications of said power brick?

**Comment by bluikko** [comment]
I thought "barrel connector" is in more wide-spread usage than coaxial power connector. Anyone know which one is more usual?

I'd also still want to see the "multi-standard"/"international" customer/domestic connector... or at least "Other" type.

**Comment by brotherdust** [comment]
Barrel connector is de-facto usage, as you suggest. Coaxial is what’s used in the standard. Either way, same thing. Just didn’t want to confuse matters when I was making reference to Wikipedia article and it’s called coaxial there. 😁
