### ISSUE TITLE
Remove duplication and optimize table space by a combination of the "Cable peer" and "Connection" table fields

### ISSUE THREAD

**Issue by bluikko** [netbox-community/netbox#7926]
### NetBox version

v3.0.11

### Feature type

Change to existing functionality

### Proposed functionality

Currently for tables like "Interfaces" there are two different fields that describe where a cable connected to an interface goes:
- "Cable peer": the immediate neighbor device, etc.
- "Connection": the interface or other termination on the far side when the connection goes through panels etc.

In the simple case of: `interface` -> `cable` -> `interface` both the 2 above fields are the same.  
When both "Cable peer" and "Connection" are visible on a table, then both the fields are the same in the simple case - which could be a lot of the time.  
And in my instance, viewed on 1080p, these 2 fields alone take over one third of the horizontal table space which is extremely significant!

The above repetition wastes a lot of horizontal space on the tables. It would be much more efficient if there was either a new field like "Route" or a change to the current field "Connection" to combine both the current "Cable peer" and "Connection" information:
- If the interface is directly connected to another interface, etc. then print the current "Cable peer".
- If the current "Connection" field differs from the "Cable peer", then additionally print the current "Connection".

This change would allow to keep the same amount of information but remove the duplication in the simple case. Looking at some of the tables on my NetBox instance this could save 20-30 characters worth of horizontal space - again, a very significant amount freed for displaying other data.  
It would be interesting to hear if similar space saving is seen on other instances as well. I believe it depends on naming conventions and how NetBox is used exactly.

It looks like it could be a very simple change and I hope to test it in my instances to give some data on the possible space savings.

If I remember right this is how it worked on very old NetBox versions. And it is among the most useful features that were lost.  
Edit: there used to be additionally a small "globe" (?) icon and then the far side termination I think.

### Use case

Helps save horizontal space on the tables by removing duplication, thus allowing more fields to be displayed on a table.

### Database changes

None?

### External dependencies

None?

**Comment by jeremystretch** [comment]
These two columns convey different information and serve different purposes. If you don't want display one or the other you have the option of hiding either or both. However they will be kept as separate columns because their proposed combination would greatly and unnecessarily complicate the processing of exported data.

**Comment by bluikko** [comment]
Didn't old NetBox show the combination field? I remember the small "globe" icon that separated the two pieces of information that are now the current "Cable peer" and "Connection" fields.

Both fields are indeed important information, didn't think about exported data. That is why I need to keep both fields visible. They just take a lot more horizontal space that the old version did (if I remember it right).
