### ISSUE TITLE
Increase resolution of maximum draw and allocated draw to 3 decimal places e.g 0.001 W

### ISSUE THREAD

**Issue by ypid** [netbox-community/netbox#7937]
### NetBox version

v3.1-beta1

### Feature type

Change to existing functionality

### Proposed functionality

Maximum draw and allocated draw of power ports (device type, device) should support at least be 1 decimal place e.g 0.1 W. If in doubt, lets increase to 3 decimal place which is the resolution of lab power meters. I run into this limit of 1 W resolution multiple times.

This is what I am proposing in code:

```Python
maximum_draw = models.DecimalField(
    max_digits=8,
    decimal_places=3,
    blank=True,
    null=True,
    help_text="Maximum power draw (watts)"
)
```

### Use case

Manufactures and reviews often give power draw with 0.1 W resolution and accuracy. For example [HPE OfficeConnect 1820 Switch Series QuickSpecs.pdf](https://www.dsd-dataservice.de/media/products/HPE%201820.pdf).

### Database changes

Yes.

### External dependencies

No

**Comment by jeremystretch** [comment]
> Manufactures and reviews often give power draw with 0.1 W resolution and accuracy.

Okay, but what's _your_ use case for this degree of granularity? This seems unnecessary to me. One Watt is well within the the margin of error for most power monitoring systems.

**Comment by ypid** [comment]
You are right, I missed really giving a use case above. With that sentence, I just wanted to say that when a manufacture gives me the maximum draw in 0.1 W resolution, than I would like that being represented in my device type. I don’t like rounding just because of technical limitations. My use case is for example single board computers that have a very low power consumption. There it makes a difference if we are talking about 0.7 W or 1.4 W. And for tuning devices to be power efficient. Maybe you found out that disabling 2.4 GHz on an AP saves 0.5 W of power and you would like to track that in NetBox. There are also places were you don’t have plenty of power, like in off-grid/RV were people still want to run networks.

**Comment by jeremystretch** [comment]
I'm going to decline this as I don't think it makes sense to support fractional Watts. As I mentioned, that degree of granularity just isn't relevant for NetBox's intended use.
