### ISSUE TITLE
Composed Custom Fields / Objects

### ISSUE THREAD

**Issue by apiening** [netbox-community/netbox#7938]
### NetBox version

v3.0.11

### Feature type

Change to existing functionality

### Proposed functionality

It would be very powerful to add a type "**Composed / Object**" to Custom Fields.
Instead of one single field, it would allow to add multiple custom fields as sub-entries, basically defining a custom model.
This would enable models to be extended not only with single fields, but with a variable list of entities with a custom type.

The only way to achieve this at the moment would require to develop a plugin, as far as I'm aware of.
But if you just want to extend a model with a sub-model consisting of Custom Fields, this would be a pretty complex task I guess.
Being able to extend a model with Custom Fields of type **Composed / Object** would make it much easier and flexible to do more complex model extensions.

### Use case

Let's say I want to add **Responsible Contacts** to **Devices**.
Each **Responsible Contact** would consist of several fields, for example: **Name**, **Email-Address**, **Phone Number**, **Hourly Rate**.
It would allow me to add any number of **Responsible Contacts** to a device, each entry having the custom fields defined above.

**Comment by jeremystretch** [comment]
NetBox v3.1 adds support for JSON custom fields (see #7452) which may suit your needs. If you need something more structured than this, then a custom plugin is the way to go.
