### ISSUE TITLE
Add multistandard ITA Power Outlet type

### ISSUE THREAD

**Issue by bluikko** [netbox-community/netbox#7940]
### NetBox version

v3.0.11

### Feature type

Change to existing functionality

### Proposed functionality

NetBox has Power Outlet types for all major ITA connector types, but there also exists a "multistandard" outlet type. These are very common in this country - I would say perhaps half to three quarters of all modern outlets are multistandard. We also use exclusively ITA multistandard PDUs in those rare cases where we need ITA outlets (otherwise using 60320 or 60309).

The outlets look similar to this, with some variations on accepted ITA types:
![image](https://user-images.githubusercontent.com/14869000/143521101-2844ea94-07d8-4b5a-89c0-fd7ea4ef6a73.png)

Usually they accept A, B, E, F, G, I and M types at least.

### Use case

Model the ITA multistandard Power Outlet.

### Database changes

None.

### External dependencies

None.

**Comment by bluikko** [comment]
Hmm. The "TYPE_ITA_MULTISTANDARD" Power Outlet would need to be somehow changed to accept connecting (say) any ITA type plug, wouldn't it?

**Comment by DanSheps** [comment]
> Edit: better not comment before morning coffee... it seems there is currently no logic to enforce / way to model how plugs fit into sockets.

Sure there is, it is CustomValidators.  😄

But within Netbox itself, no there is no mechanism saying "All ITA can only plug into this specific ITA or the All ITA receptacle"
