### ISSUE TITLE
Change device position within Rack via Drag and Drop.

### ISSUE THREAD

**Issue by Mic-Pod** [netbox-community/netbox#7957]
### NetBox version

v3.0.10

### Feature type

New functionality

### Proposed functionality

Change device position within Rack via Drag and Drop.
Would it be possible to add such functionality?

### Use case

Sometimes it would be much faster to correct the Device position in Rack via Drag and Drop rather than editing manually or via API.

**Comment by jeremystretch** [comment]
Thank you for submitting this issue, however it appears that this topic has already been raised. Please see issue #6726 for further discussion.

**Comment by Mic-Pod** [comment]
@jeremystretch Thanks for reply, but #6726 is closed and locked and it was related to netbox v2.x.
Is it more possible that this feature could be implemented in v3.X?

**Comment by DanSheps** [comment]
The comment in #6726 is still as relevant right now. We currently have a large backlog and nicities such as this just aren't in the plan right now.
