### ISSUE TITLE
Two-post rack front/rear faces and half-depth devices

### ISSUE THREAD

**Issue by rbahm** [netbox-community/netbox#7958]
### NetBox version

v3.0.8

### Feature type

Change to existing functionality

### Proposed functionality

Add an option to the "Rack" object called "Devices consume both front and rear face of rack." When this option is applied, all devices are treated as if the "full-depth" box was checked on the Device Type page - that is to say, the rack elevations show the front and rear of the device, and it is not possible to choose that specific rack position on either face.

### Use case

Two-post racks support devices, and do have a front and rear, but devices of any depth are typically going to prevent racking devices on both faces of the rack. However, Netbox is unable to model this accurately - instead, users may be led to believe there is free space on a rack which is not available. Simply inputting all device types as "Full-Depth" isn't a viable solution, since the same Device Types may also be used in 4-post racks where the Full-Depth designation is important.

### Database changes

A new column would need to be added to support the proposed flag in the rack object.

**Comment by jsenecal** [comment]
Couldn't that "restriction/behavior" simply be bound to the `type` field of the created `Rack` object ?

**Comment by rbahm** [comment]
@jsenecal I thought about that as well - it could be configured so any "two-post rack" automatically has this behavior. This eliminates the need for an additional database column. However, this would be a breaking change and might be undesirable for some portion of Netbox users - since I couldn't be sure if some organizations want to be able to model non-full-depth devices on both sides of a two-post rack, adding it as a new column results in the behavior being configurable.

All that said, for my use, making "two-post rack" always mean "devices consume both front and rear face of rack" would be 100% correct all the time. I also can't imagine any scenario where you'd need something else.

**Comment by jeremystretch** [comment]
I think it's reasonable to infer this from the rack type.

**Comment by iunderwood** [comment]
This is an interesting request, which could be broken into a couple different parts.

1. An additional field could be added to the rack object to restrict rear mounting.  This way, you could still have devices racked on both sides.  It's unlikely, but I have seen patch panels mounted on both sides of a two-post rack.  Making this restriction based on the rack object could be beneficial for all rack types and not just the 2-posters.

2. An additional field could be added to the device object to indicate which side is mounted.  For example, a terminal server or a horizontal PDU could have images of its front and rear as part of the device type.  However, only the "front" is shown as it is mounted, even if the rack ears allow for a rear mount.  This would be more beneficial to the visual representation of a given rack, but thought it was worth pointing out here.  A two-post rack could show the proper set of front and rear images automatically for all devices if the mounting direction can somehow be pointed out for the object itself.
