### ISSUE TITLE
Group models with null parents allow duplicate names

### ISSUE THREAD

**Issue by DanSheps** [netbox-community/netbox#7960]
### NetBox version

3.1-beta

### Python version

3.8

### Steps to Reproduce

1. Create Region named Test
2. Create Region named Test

### Expected Behavior

The second region creation should fail

### Observed Behavior

The creation is allowed

**Comment by DanSheps** [comment]
With a unique constraint of "unique_together" with (parent, name), this will allow duplicate named due to the way Postgres handles null values (treats each null value as unique).

Two proposals were brought up to handle this previously:

1. A unqiue index which coaleses the parent and the name together, resulting in a string that cannot be unique
2. Solve this in code

**Comment by jeremystretch** [comment]
The same issue exists for site groups as well.

**Comment by jeremystretch** [comment]
I looked into employing Django's [unique constraints](https://docs.djangoproject.com/en/3.2/ref/models/constraints/#uniqueconstraint) for this. While this approach works for effecting database-level validation, violations unfortunately result in an unhandled IntegrityError exception: There is no pre-save validation logic. AFAICT we still need to define a custom `validate_unique()` method on these models to handle the pre-save validation cleanly and prevent the exception.
