### ISSUE TITLE
Performance problems when using quicksearch on chromium based browsers

### ISSUE THREAD

**Issue by promasu** [netbox-community/netbox#7971]
### NetBox version

v3.0.11

### Python version

3.7

### Steps to Reproduce

1. Open Devices Page
2. Type something into the quicksearch field
3. Browser freezes

We can reproduce this behavior on Chrome 96.0.4664.45 and Edge 96.0.1054.41 with a Netbox with about 340 devices

### Expected Behavior

Browser does not freeze

### Observed Behavior

Browser freezes

**Comment by kkthxbye-code** [comment]
Duplicate (#7932) and fixed #7933 - will be included in the next release.

**Comment by DanSheps** [comment]
Duplicate of #7932

**Comment by promasu** [comment]
Hi there,

after i upgraded to 3.1.0 the problem still persists.
In chromium based browsers I get the message
```
[Violation]'setTimeout' handler took 1642ms - netbox.js:4
[Violation]Forced reflow while executing JavaScript took 1609ms
```
in the browser console. Using Firefox I don't get any of those messages.

Can you please take another look at this issue?

Kind regards,
Adrian

**Comment by kkthxbye-code** [comment]
@promasu - Could you provide specific steps to replicate it? I can't replicate it on the demo instance? Are you sure your instance is updated properly, and that you have cleared your browser cache?

I tried on the demo instance as well, adding over 1000 devices and filtering on the device page, and it finishes almost instantly.

https://demo.netbox.dev/dcim/devices/

**Comment by promasu** [comment]
Problem solved. I hardcoded the version in the webserver settings. Sorry for bothering you
