### ISSUE TITLE
Logger name syntax is invalid for authentication events

### ISSUE THREAD

**Issue by markkuleinio** [netbox-community/netbox#7972]
### Change Type

Correction

### Area

Configuration parameters

### Proposed Changes

In https://netbox.readthedocs.io/en/stable/configuration/optional-settings/#available-loggers it says:

> `netbox.auth.*` - Authentication events

But apparently it should be `netbox.authentication.*`:

```
2021-12-03 10:20:19,352 netbox.authentication.RemoteUserBackend DEBUG: trying to authenticate markku with groups None
```
Tested with NetBox 3.0.11.

**Comment by kkthxbye-code** [comment]
You sure the documentation isn't correct?

https://github.com/netbox-community/netbox/blob/e05fa5c30285a7db9c7b80f52c883523401ef01c/netbox/users/views.py#L36-L49

`netbox.authentication.RemoteUserBackend` is the path to the class, not the name of the logger.

**Comment by markkuleinio** [comment]
Yes my logger format is `'%(asctime)s %(name)s %(levelname)s: %(message)s'` so `netbox.authentication.RemoteUserBackend` is the logger name that was used there as you pointed out.

Let me know if a new issue or PR is needed.

**Comment by jeremystretch** [comment]
> I actually think the issue is that the wrong logger is request in RemoteBackend.

Agreed. I'm going to change it to `netbox.auth.RemoteBackend`.
