### ISSUE TITLE
vm duplicates at plugin sync.

### ISSUE THREAD

**Issue by TristisOris** [netbox-community/netbox#7974]
### NetBox version

3.0.11

### Python version

3.8

### Steps to Reproduce

1. have 2 Xen xcp pools. 1st pool was disabled\unavailable for sync, and all VM migrated to 2nd.
2. after syncing all VM appear at NB second time on 2nd pool.
![изображение](https://user-images.githubusercontent.com/1270117/144596861-5a7dc961-9e1f-44d4-ab0c-a6af95d5e63b.png)

### Expected Behavior

move VM from 1st pool to 2nd **based on unique VM ID**.
99.99% its the only possible reason what could happens.

### Observed Behavior

no migration, only duplicate creation.

**Comment by jeremystretch** [comment]
This appears to be related to a NetBox plugin. You'll need to open a bug report against the plugin, as it's not related to NetBox itself.
