### ISSUE TITLE
Markdown code block mode: Everything in between colons is not rendered

### ISSUE THREAD

**Issue by ypid** [netbox-community/netbox#7981]
### NetBox version

* v3.0.11
* v3.0.10

### Python version

3.9

### Steps to Reproduce

1. Create a device type with this comment. I had to use code mode for the `:joy:` to prevent it from getting rendered. Copy the whole text:

\`\`\`
00:14.0 USB controller [0c03]: Intel Corporation Lynx Point-LP USB xHCI HC [8086:9c31] (rev 04)
`:joy:`
\`\`\`

2. Save.

(It is reproducible on the demo instance: https://demo.netbox.dev/dcim/device-types/11/)

### Expected Behavior

It is rendered as follows (like on GitHub):

```
00:14.0 USB controller [0c03]: Intel Corporation Lynx Point-LP USB xHCI HC [8086:9c31] (rev 04)
:joy:
```

### Observed Behavior

It is rendered like this:

```
00:14.0 USB controller [0c03]: 9c31] (rev 04)
:joy:
```

At first I thought that emoji support might be the issue, but that seems not to be the case. Not sure what else acts on the colons here.

### Use case

I like to include the output of various commands like in this case `lspci -nn` in the device type because that often gives more insights than vendor docs.

**Comment by kkthxbye-code** [comment]
Caused by: https://github.com/netbox-community/netbox/commit/a7990942276f125694e7fa33f6d5c58925574aee
