### ISSUE TITLE
please add the predefined/built-in "localhost" in Services -> IP addresses

### ISSUE THREAD

**Issue by rafalfitt-mptv** [netbox-community/netbox#7985]
### NetBox version

v3.0.11

### Feature type

New functionality

### Proposed functionality

the list of IP addresses should contain "localhost" and perhaps even "localhost (IPv4 only)"

### Use case

Sometimes a service is accesible on localhost - I want to add this information in NetBox

**Comment by DanSheps** [comment]
There is a proper method to do this already.  On your device or VM add the appropriate loopback interface (yes, localhost is a loopback interface) and then add an IP address.

**Comment by rafalfitt-mptv** [comment]
sorry, but this proper method is crap: it inflates the interfaces list with these loopback entries.

**Comment by rafalfitt-mptv** [comment]
and AFAIK it is not possible to hide these loopback entries from interface list :-(
unfortunately it is not possible to mark interface as loopback. Only an address can have role: loopback.
IMHO usually you call an *interface* loopback, not address.

**Comment by DanSheps** [comment]
> sorry, but this proper method is crap: it inflates the interfaces list with these loopback entries.

NetBox models real world, almost every OS has a interface for loopback addresses.  Those loopback entries exist in real-life too. 
 As far as inflating the interface list, I don't know too many people that use a unfiltered interface list and loopback interfaces are virtual so you can at least filter on Physical interfaces.  Example:

```
ifIndex InterfaceAlias                  AddressFamily NlMtu(Bytes) InterfaceMetric Dhcp     ConnectionState PolicyStore
------- --------------                  ------------- ------------ --------------- ----     --------------- -----------
1       Loopback Pseudo-Interface 1     IPv6            4294967295              75 Disabled Connected       ActiveStore
```

```
ifIndex IPAddress                                       PrefixLength PrefixOrigin SuffixOrigin AddressState PolicyStore
------- ---------                                       ------------ ------------ ------------ ------------ -----------
1       ::1                                                      128 WellKnown    WellKnown    Preferred    ActiveStore
1       127.0.0.1                                                  8 WellKnown    WellKnown    Preferred    ActiveStore
```

On the windows example, you can even add non-loopback addresses to the loopback interface.  This is going to be the same on Linux as well.

> and AFAIK it is not possible to hide these loopback entries from interface list :-(
> unfortunately it is not possible to mark interface as loopback. Only an address can have role: loopback.
> IMHO usually you call an _interface_ loopback, not address.

Yes, that is unfortuante, however there is a issue to add negation filters (I am not going to look it up but you might want to add a 👍 up if you go and find it to help get it more traction).  You could add in a FR to perhaps somehow denote a loopback address or maybe add a filter to look at the IP's on a interface for a "has loopback" and we could add that.
