### ISSUE TITLE
Wrong link for Dynamic Configuration Updates in https://github.com/netbox-community/netbox/releases/tag/v3.1.0 Changelog

### ISSUE THREAD

**Issue by tioan** [netbox-community/netbox#7987]
### Change Type

Correction

### Area

Other

### Proposed Changes

For a complete list of supported parameters, please see the dynamic configuration documentation, links to https://github.com/netbox-community/netbox/blob/configuration/dynamic-settings.md with http 404.
Correct are https://netbox.readthedocs.io/en/stable/configuration/dynamic-settings/

**Comment by jeremystretch** [comment]
Fixed, thanks!

**Comment by bluikko** [comment]
Similar issue with conditions; from https://github.com/netbox-community/netbox/blob/reference/conditions.md should be https://github.com/netbox-community/netbox/blob/v3.1.0/docs/reference/conditions.md or https://netbox.readthedocs.io/en/stable/reference/conditions/
