### ISSUE TITLE
Ip address/ ip range region 

### ISSUE THREAD

**Issue by Basyuk** [netbox-community/netbox#7991]
### NetBox version

V3.0.8

### Feature type

Change to existing functionality

### Proposed functionality

Hello! I suggest you add region, site and site group fields to IPAM > IP addresses and IPAM > IP address.

### Use case

This feature will help you more flexibly control access to IP addresses and IP ranges.

### Database changes

It is necessary to add the corresponding fields to the ipam_ip and ipam_iprange tables.

### External dependencies

Not required.

**Comment by jeremystretch** [comment]
Any association of IP ranges and addresses to parent regions/site groups/sites is accomplished via the prefix model. Adding a direct relationship would be redundant and unnecessary.

**Comment by Basyuk** [comment]
Sorry, I don’t understand how can I restrict access to IP addresses by region or site?  Can you show me an example? Thank you!

**Comment by DanSheps** [comment]
You should ask this question in discussions.
