### ISSUE TITLE
CSV Export/Re-import of multiple interface cable traces

### ISSUE THREAD

**Issue by maxzapp** [netbox-community/netbox#7992]
### NetBox version

v3.0.11

### Feature type

New functionality

### Proposed functionality

CSV Export of multiple  cable traces.
Cable trace is a logical end to end patching information of two active interfaces over multipel hops passive of cables and patch panels.
Included information should be same as in the graphical cable trace view.
Selection options should  be:
export all traces  from all interfaces of a single device
export all traces from all interfaces of  complete rack. 

### Use case

This helps admins to verify and correct offline their patching information without access to netbox wich is often the case on remote rooms, buildings, locations and sites. 

### Database changes

Mayb each cable trace needs a uniqe id to avoid double listing  (trace A to B is the same as  trace B to A)

### External dependencies

unknown

**Comment by jeremystretch** [comment]
Please take some time to rewrite your feature request so that it clearly conveys what you're proposing. It's not at all clear from what you've written above what you're trying to accomplish.

**Comment by maxzapp** [comment]
sorry english is not my native language, so i try my best.

**Comment by jeremystretch** [comment]
There isn't a standardized way to export cable traces, as each can traverse an arbitrary number of nodes and links. It sounds like your use case would be best served by authoring a [custom script](https://netbox.readthedocs.io/en/stable/customization/custom-scripts/) that would cater to your specific workflow.
