### ISSUE TITLE
Custom menu order

### ISSUE THREAD

**Issue by PieterL75** [netbox-community/netbox#8002]
### NetBox version

v3.1.0

### Feature type

Change to existing functionality

### Proposed functionality

The current menu is in a fixed order. 
Organization - Devices - Connections - Wireless - IPAM - Virtualization - Circuits - Power - Other - Plugins

This order is not optimal for each use case, or some features are not required.

Can it made possible to order the menu structure and optionally hide other ?

### Use case

Not all features of Netbox are used by each implementation.
In our case, we are not documenting Wireless or Virtualization items.

My optimal menu structure would be
Devices - IPAM - Organization - Circuits - Power - Connections - Other - Plugins - Virtualization - Wireless

### Database changes

not really. This could be accomplished in the configuration.py.
Optionally an extra field in the 'admin/groups' to set the order per group of people

**Comment by jeremystretch** [comment]
Sorry, but this degree of customization is not a design goal for NetBox. It would impose significant development burden with relatively little value.
