### ISSUE TITLE
GET parameter 'role' does not set filter

### ISSUE THREAD

**Issue by dreng** [netbox-community/netbox#8007]
### NetBox version

v3.1.0

### Python version

3.7

### Steps to Reproduce

1. Create mandatory date for devices if not done yet (role, device-type and site)
2. Create a new device and assign any role
3. At the "Device" tab of the newly created device, under "Management" click the link right next to the text "Role"
4. A filtered list appears based on the role. URL is like https://netbox.yourdomain.local/dcim/devices/?role=yourrole

### Expected Behavior

I'd expect a filtered list with a set filter you can see at the "filters" tab like this:

![2021-12-08 14_05_21-Window](https://user-images.githubusercontent.com/20901110/145213784-6a4b9124-af8a-4aab-9242-69232c9b9b96.png)

### Observed Behavior

No filter is set but the list appears filtered.
This is not the case if you click a link at the "Device Roles" page. That URL is like https://netbox.yourdomain.local/dcim/devices/?role_id=1

![2021-12-08 14_06_34-Window](https://user-images.githubusercontent.com/20901110/145213886-edd4bdd8-21b9-4aeb-80f4-ce380b001e14.png)

**Comment by jeremystretch** [comment]
This is expected behavior: The UI filter form only recognizes the `role_id` filter.
