### ISSUE TITLE
FHRP group address doesn't honor unique space

### ISSUE THREAD

**Issue by zombah** [netbox-community/netbox#8009]
### NetBox version

v3.1.0

### Python version

3.8

### Steps to Reproduce

1. Create vrf UniqueSpaceVRF and enable Unique space in it
2. Create IP address 192.168.1.1/24 inside vrf UniqueSpaceVRF
3. Create FHRP group with id 100, vrf UniqueSpaceVRF and address 192.168.1.1/24

### Expected Behavior

Error that vrf is unique space

### Observed Behavior

FHRP group creates duplicate ip inside unique space vrf

**Comment by DanSheps** [comment]
This is because the address role for certain roles is exempt from consideration for uniqueness.  I believe Anycast, VIP, VRRP, HSRP, GLBP are all exempt from uniqueness constraints.

I am not sure if this is documented anywhere however.

**Comment by zombah** [comment]
Oh but this is not working if i'm trying to create this address 192.168.1.1/24 with role VIP manualy, receive error duplicate.

**Comment by DanSheps** [comment]
We likely bypass the check, at least that is my guess.

We could add the check, however I am not sure how desireable that is.

**Comment by zombah** [comment]
Imo some check may help as there is no clear create ip or assing ip like inside interfaces and will result in orphaned duplicates in unique ip space.
