### ISSUE TITLE
Exclude /metrics from LOGIN_REQUIRED regression

### ISSUE THREAD

**Issue by craized** [netbox-community/netbox#8019]
### NetBox version

v3.1.0

### Python version

3.7

### Steps to Reproduce

Set LOGIN_REQUIRED = True
Query /metrics endpoint

### Expected Behavior

Receive metrics dump

### Observed Behavior

Redirect to login page

Confirmed disabling LOGIN_REQUIRED allows fetching of /metrics
Reference issue for previous versions: https://github.com/netbox-community/netbox/issues/3123

**Comment by jeremystretch** [comment]
Seems that the URL provided by django_prometheus does not include a trailing slash.

**Comment by craized** [comment]
TYVM! Patch speed is second-to-none
