### ISSUE TITLE
transliterate Umlauts in autogenerated slugs

### ISSUE THREAD

**Issue by lucasteinke** [netbox-community/netbox#8022]
### NetBox version

v3.1.0

### Feature type

Change to existing functionality

### Proposed functionality

Currently, the autogenerated slugs just omit Umlauts, so when you for example enter `Döner GmbH & Co. KG` as tenant name, the slug generated will be `dner-gmbh-co-kg`. It would be nice if Umlauts could be transliterated, so `ä`➔`ae`, `ö`➔`oe`, `ü`➔`ue`.

Maybe you can also transliterate stuff like `&` to `and`. Possibly there are other transliterations possible for other special characters in other languages.

### Use case

There would be readable slugs without having to change the slug manually.

### Database changes

No DB changes.

### External dependencies

No new dependencies.

**Comment by DanSheps** [comment]
Is there a javascript library to handle this automatically?

**Comment by markkuleinio** [comment]
I thought slugs were being phased out, please remind me how it is. I mean, if slugs are here still to stay, then as a Finnish name user I would support this.

Hämäläinen -> `hmlinen`... 😊🇫🇮

**Comment by jeremystretch** [comment]
> I thought slugs were being phased out

I'm not sure to be honest. I think it makes sense, however a number of people do utilize the slug field to store import data (e.g. site codes). It would actually simplify things a good deal if we ditched them, but we need to ensure that anyone who needs slugs has a suitable migration path.

**Comment by mmfreitas** [comment]
> > I thought slugs were being phased out
> 
> I'm not sure to be honest. I think it makes sense, however a number of people do utilize the slug field to store import data (e.g. site codes). It would actually simplify things a good deal if we ditched them, but we need to ensure that anyone who needs slugs has a suitable migration path.

I thought that the slug was for a functional part of netbox such as url creation and querying. If it is not that important maybe it doesn't make sense being there...?
It also doesn´t seem like the type of field to store the type of information that you mentioned, I believe that would be better suited for a custom field and therefore it would be up to the user to migrate this information as you cannot prepare for every use case scenario.

**Comment by markkuleinio** [comment]
My biggest problem with slugs is that they are mandatory fields so I need to generate them in my apps. Currently I use random strings because it's easier than trying to generate the slug based on the object name and then double-checking that it really is unique within the object model.

**Comment by jeremystretch** [comment]
> I thought that the slug was for a functional part of netbox such as url creation and querying.

We standardized all URL paths to use numeric keys only a while back (v2.11 maybe?).

> It also doesn´t seem like the type of field to store the type of information that you mentioned, I believe that would be better suited for a custom field and therefore it would be up to the user to migrate this information as you cannot prepare for every use case scenario.

Agreed; a custom field would probably be the way to go.

**Comment by jeremystretch** [comment]
I've opened #8036 to propose removing slugs entirely.
