### ISSUE TITLE
Platform manufacturer should not depend on hardware manufacturer

### ISSUE THREAD

**Issue by damiankaczkowski** [netbox-community/netbox#8024]
### NetBox version

v3.0.11

### Feature type

Change to existing functionality

### Proposed functionality

Some devices can be loaded with software (netbox platform) from different manufacturers.

For example Cumulus Linux compatible devices: https://www.nvidia.com/en-us/networking/ethernet-switching/hardware-compatibility-list/

But the list expands for many more devices which can load any x86_64 software like pfsense or any other firewall or similar software.

The same goes for more generic devices like servers which can be loaded with Red Hats RHEL, Canonical Ubuntu, Microsoft Windows and so on.

So in other words Hardware Manufacturer != Software Manufacturer (netbox platform).

Unfortunately netbox limits available platform choices according to selected device manufacturer, which is wrong assumption imo. It works for Cisco, Juniper but not for device vendors that allows the device to be loaded with different vendor software.

NetBox should change behavior and split the hardware to platform manufacturer dependency.

The only way to workaround this right now is to not fill any manufacturer in the platform configuration, which is just .... **counter-intuitive** imo.

### Use case

User is not limited to netbox dependency model and he can create the **real life scenarios** where for example the Dell device is loaded with NVIDIAs software/platform.

**Comment by jeremystretch** [comment]
> Unfortunately netbox limits available platform choices according to selected device manufacturer, which is wrong assumption imo. It works for Cisco, Juniper but not for device vendors that allows the device to be loaded with different vendor software.

The assignment of a platform to a manufacturer is entirely optional. In such cases, you simply don't make the assignment, and there is no limitation.
