### ISSUE TITLE
partial database transfer

### ISSUE THREAD

**Issue by someconservator** [netbox-community/netbox#8027]
### NetBox version

v3.1.0

### Feature type

New functionality

### Proposed functionality

Transferring data in parts from the web interface: only ipam, only virtualization, virtualization and ipam, data without custom fields, etc. 

### Use case

Currently, the export and subsequent import (transfer) of the database is performed entirely using the pg_dump/psql OS commands. The problem is that not the entire database needs to be transferred from time to time. For example, the same database contains custom fields. And in the event that an organization has a test and production environment, a periodic dump of the entire base of the production environment (for example, to more closely match to the test environment) leads to the need to destroy custom fields in the test environment. Therefore, it is necessary to be able to transfer the base in parts.
In addition, not all users of netbox (operators, user support) can make a partial transfer with sufficient confidence when using system commands. Or they may not have access to the terminal at all. Hence, having export/import functions in the application can also be helpful in this regard.

**Comment by jeremystretch** [comment]
I'm not sure what you're trying to accomplish, but it seems to be well outside the scope of normal NetBox usage. Any replication of the database, partial or otherwise, will need to be handled by an administrator and is not something that would be performed from within NetBox itself.

**Comment by someconservator** [comment]
OK. We will suffer on our own. :)
