### ISSUE TITLE
VLAN attribute Site Group not saved

### ISSUE THREAD

**Issue by jhammond-git** [netbox-community/netbox#8075]
### NetBox version

v3.1.0

### Python version

3.8

### Steps to Reproduce

1. Create a Site Group
2. Create a VLAN Group, scope type "site group", Site group set to the group created in 1.
3. Create a VLAN and assign it to Group Scope of "site group", and VLAN Group of the group created in 2.
4. Navigate to /ipam/vlans/ and click the Filter tab.  Add a filter for the site group created in 1.

### Expected Behavior

The filtered list will be the VLAN created in 3.

### Observed Behavior

Nothing shows up as "Site Group" doesn't seem to be a retained attribute of a VLAN.

**Comment by jeremystretch** [comment]
Ah, I see the confusion. The `site_group` filter on the VLAN filterset filters on the group of the _site_ to which a VLAN is assigned. Basically, there are two possible relations:

* VLAN -> site -> site group
* VLAN -> VLAN group -> site group

The `site_group` filter matches on the former, which predates support for scoped VLAN groups. We should not alter this as doing so would be a breaking change to the API.

We could introduce a set of new filters to filter by VLAN group scope, but I'm not sure what those would look like.

**Comment by jhammond-git** [comment]
Can the filter not be applied as an OR and grab both sets of data?  I'm sorry I'm not familiar with the back end.

**Comment by jhammond-git** [comment]
"Undesired or Surprising Behavior" is my Motley Crue cover band.

So should this be an FR then instead of a bug, or should they be two separate issues - one to fix "site -> site group" and the other to add "VLAN group -> site group"?

**Comment by jeremystretch** [comment]
I think a new FR to enable filtering VLANs by their group's scope makes sense.

**Comment by jhammond-git** [comment]
Sounds good.  Thank you.

**Comment by jhammond-git** [comment]
https://github.com/netbox-community/netbox/issues/8085
