### ISSUE TITLE
Add 'tunnel' as interface type

### ISSUE THREAD

**Issue by micko** [netbox-community/netbox#8076]
### NetBox version

v3.1.1

### Feature type

Data model extension

### Proposed functionality

Add "tunnel" as an interface type to allow for building of tunnels (gre, ipsec, etc) and allow it to connect a circuit that way you can build A->Z. 

### Use case

Building virtual tunnels

### Database changes

- add "tunnel" as an interface type
- allow for the interface to connect to a circuit type

### External dependencies

none.

**Comment by jeremystretch** [comment]
NetBox does not currently support the concept of a tunnel between interfaces. This has been proposed under #7847, and would include any relevant new interface types. For now, just use the virtual interface type if you need to model tunnel interfaces.
