### ISSUE TITLE
add button to the sidebar to quickly add a service

### ISSUE THREAD

**Issue by heylix** [netbox-community/netbox#8081]
### NetBox version

v3.1.1

### Feature type

New functionality

### Proposed functionality

You can add many objects with a "plus" sign in the sidebar. This is not true for services. I propose to add a plus button which leads to a form to add a service to a VM or device.

### Use case

adding a service quickly without first having to open a VM or device.

### Database changes

none

### External dependencies

none

**Comment by jeremystretch** [comment]
This is actually a limitation in the service creation view: The view currently requires initialization with a specific device or virtual machine to render the form correctly. This is an older pattern though and we should be able to improve it to accommodate a direct link.
