### ISSUE TITLE
Remove/hide related devices

### ISSUE THREAD

**Issue by hagbarddenstore** [netbox-community/netbox#8083]
### NetBox version

v3.1.1

### Feature type

Change to existing functionality

### Proposed functionality

Remove or hide the related devices box on the device page.

### Use case

The current method of finding related devices is quite confusing and not really usable because of which criterions it finds them by.

It is quite common to have several hundred devices of the same role within the same site, of which the related devices box shows only ten, in no particular order.

It would be an improvement if it found them within the same rack or by cable connections or something narrower than role+site.

**Comment by sdktr** [comment]
Would be cool if the query for the definition of 'related devices' could be stored in config. Limiting the amount of results to X-amount and providing a link to the full results.

related_devices_query: ?role={{ obj.role }}&site={{ obj.site }}
related_devices_maxresult = 5

This results in including:  ?role={{ obj.role }}&site={{ obj.site }}&max_result=5 

to be included on the device page. With a link to /devices?role={{ obj.role }}&site={{ obj.site }} in the view as well.

**Comment by ITJamie** [comment]
Following on from the slack chat that started this issue.

In general it would be nice to have a small list of config options for hiding / disabling small ui features. 

For example it would be nice if there was a config option to hide custom fields with no value set. 
The defaults could be to have these panels / options enabled.

So an option for "hide_related_devices" and "hide_unset_custom_fields" for example

**Comment by ITJamie** [comment]
Re: related devices query. Id like to see it be based off devices connected to it or devices in the same rack more than site level. Sites can be huge.

**Comment by DanSheps** [comment]
@hagbarddenstore 

I see two distinct FR's in your request, which one do you actually want to proceed with?

1. Allow hiding of related devices
2. Alter the related devices lookup to show more relevant devices

**Comment by hagbarddenstore** [comment]
@DanSheps Well, no. The feature request is about user experience and discussion around which alternative is the best choice to improve the user experience.

Given the comments here and on Slack, it seems that we should do the second alternative, rather than removing it entirely.

**Comment by hagbarddenstore** [comment]
I like this suggestion :D

**Comment by DanSheps** [comment]
Yeah, sounds like a good idea IMO

**Comment by ITJamie** [comment]
If it is going away. Id really reccomended moving one of the panel items on the left to the right in device view. Custom fields, tags comments. Theres a lot on the left section
