### ISSUE TITLE
UI | Device Types Interfaces tab is missing pagination

### ISSUE THREAD

**Issue by dnikoliouk** [netbox-community/netbox#8084]
### NetBox version

v3.1.0

### Python version

3.9

### Steps to Reproduce

1. Create 50+ interfaces for a Device Type

### Expected Behavior

UI should display pagination options under Device Type interfaces tab.

![image](https://user-images.githubusercontent.com/37638768/146270998-dd10a9ff-7838-4c9c-803b-5a0649c12b93.png)

### Observed Behavior

UI doesn't display pagination options under Device Type interfaces tab.

![image](https://user-images.githubusercontent.com/37638768/146271183-f7f059b5-c3be-4195-819d-65e88fd9866a.png)

**Comment by jeremystretch** [comment]
Thanks for the report. As luck would have it, I just overhauled a whole bunch of object list views under #8057, including this one. This has already been fixed in the `develop` branch and will be included in the v3.1.2 release. Thanks again!
