### ISSUE TITLE
Support filtering of VLANs by parent site group

### ISSUE THREAD

**Issue by jhammond-git** [netbox-community/netbox#8085]
### NetBox version

v3.1.0

### Feature type

Change to existing functionality

### Proposed functionality

I would like to see a search filter under IPAM > VLANs that shows only VLANs that belong to a Site Group through their VLAN Group - i.e., VLAN 10 belongs to VLAN Group "Chicago", which belongs to Site Group "Illinois".  Filtering for Site Group Illinois should include VLAN 10, which it doesn't currently do.

The current site group filter "filters on the site to which a VLAN is assigned..." (per Jeremy Stretch).

### Use case

VLAN groups and site groups let us logically and physically group our network.  If I move my VLANs to a site group scope, they are no longer assigned a Site and I can't get a comprehensive list of VLANs that are in a site group if there's more than one VLAN group within that site group.

### Database changes

None that I can think of

### External dependencies

None.

**Comment by jeremystretch** [comment]
What are the proposed new filters?

**Comment by jhammond-git** [comment]
VLAN Groups' Site Group, where scope is DCIM > site group.  Since there's a filter for Site Group, I'm not sure how this would be termed in the filter list.
