### ISSUE TITLE
Using Contact Object also in IPAM and Tenants

### ISSUE THREAD

**Issue by jchnbckr** [netbox-community/netbox#8087]
### NetBox version

v3.1.1

### Feature type

Data model extension

### Proposed functionality

Using the contact object in the same way like rack oder site by tenants, tenantsgroup and by ipam object (ipaddress, ipprefix vlan)

Using the central refence for persons/personsgroups in all modules

### Use case

In our university departments have managed and securtiy mangers.
We build the departments as tenant and the top departmentlevel as tenant group

ip subnets and address are organizational bind to persons/groups or departmens/tenants

it will be fine when we can bind a contact object to an tenant (in our case using roles like eg. departmentmanager/professor/securitymanger). these are the same persons in some sites or racks or fopr devices.

The contact objects are still a presend for saving a lot of time, to the current way filling many individual customfield.

for devices and rack I changed it and it works fine and looklikes very nice in the object

### Database changes

I does not know, which changes are needed

### External dependencies

no external dep

**Comment by candlerb** [comment]
> it will be fine when we can bind a contact object to an tenant

I don't quite understand that.  You *can* already bind a contact object to a tenant.  You can also bind a tenant to a prefix or an IP address.

Are you saying that there are cases that even when a Prefix is bound to a tenant, you also want to bind contacts directly to the Prefix?

**Comment by jchnbckr** [comment]
okay in combination with tenants it works.
I was blind in the tenant object ... searching for contact
everything is fine
close this please
