### ISSUE TITLE
Error occurs when clicking on "reports"

### ISSUE THREAD

**Issue by FredClement91** [netbox-community/netbox#8095]
### NetBox version

V3.1.1

### Python version

3.7

### Steps to Reproduce

Click on reports in "other"

### Expected Behavior

Display the expected page

### Observed Behavior

An error occurs, see file attached.
![image](https://user-images.githubusercontent.com/11869136/146495393-d64d0676-cfce-455a-b29d-c3ace56c7ac4.png)

**Comment by kkthxbye-code** [comment]
Not a bug, CustomFieldValue was removed in 2.10.0, please make sure that all report files in your report directory doesn't reference CustomFieldValue.

**Comment by FredClement91** [comment]
Hi,

Thanks a lot for your reply.
I’ll check it indeed.

Frederic
