### ISSUE TITLE
FHRP Groups with multiple IPs can not be assigned to interface

### ISSUE THREAD

**Issue by basti1508** [netbox-community/netbox#8096]
### NetBox version

v3.1.1

### Python version

3.8

### Steps to Reproduce

1. Create FHRP Group
2. Add IP Adresses (for this example 10 IPs)
3. Assign FHRP Group to Interface

### Expected Behavior

The FHRP Group should be assigned to the interface

### Observed Behavior

The Group could not be assiged. It may be better to use show/use the ID or a unique description there.
```
<class 'django.db.utils.DataError'>

value too long for type character varying(200)


Python version: 3.8.10
NetBox version: 3.1.1
```

**Comment by jeremystretch** [comment]
There are two issues here:

1. The string representation of an FHRPGroup should not include _all_ assigned IP addresses.
2. The exception is raised because the string representation of the FHRPGroup exceeds the maximum allowed size of the `object_repr` field in the ObjectChange model.
