### ISSUE TITLE
FHRP group type "other"

### ISSUE THREAD

**Issue by candlerb** [netbox-community/netbox#8100]
### NetBox version

v3.1.1

### Feature type

Change to existing functionality

### Proposed functionality

Add a new FHRP group type "Other"

### Use case

Use case 1: a virtual IP which moves between servers by some automated mechanism which is not VRRP/HSRP.  Example: Ganeti cluster management IP address.

Use case 2: a virtual IP which is moved manually between servers, e.g. on manual service failover between primary and secondary server.

(Maybe also for failover between an active/standby secondary firewall pair, but I haven't decided whether this is the best way to model that)

### Database changes

None

### External dependencies

None

**Comment by jeremystretch** [comment]
I hate to be pedantic but would it be more correct to set the protocol to "other" or to make protocol an optional field?

**Comment by candlerb** [comment]
"Other" is consistent with interface types, but to be honest I hadn't even considered the possibility of making it optional.  "Other" feels more like an active choice of "definitely not one of those" rather than "undecided". In the end it amounts to the same thing, so I really don't mind either way.
