### ISSUE TITLE
Return URL is not preserved when using "create and add another" button

### ISSUE THREAD

**Issue by candlerb** [netbox-community/netbox#8101]
### NetBox version

v3.1.1

### Python version

3.8

### Steps to Reproduce

1. Create a device with an interface, say IP 192.168.5.1/24
2. Create FHRP group ID 1, with address 192.168.5.2/24, status Active, "Create and add another"
3. Create FHRP group ID 2, with address 192.168.5.3/24, status Active, "Create"
4. Go to the device, view the interface
5. Click "Assign group". Click "Cancel". This correctly returns to the interface.
6. Click "Assign group". Select group ID 1, priority 0, click "Create and add another"
6. Click "Cancel"

### Expected Behavior

Return to the interface page (`/dcim/interfaces/NNN/`)

### Observed Behavior

Returns to the Netbox home page. It has forgotten the navigation route to the correct place

**Comment by jeremystretch** [comment]
I'm not able to replicate this on v3.1.1. After assigning the FHRP group, I'm redirected to the interface view via a 302 response as expected.

Can you inspect the form submission in the browser when assigning the group to verify whether the `return_url` value is being passed?

**Comment by DanSheps** [comment]
You need to assign the first group, then the return_url on the cancel button does not properly populate.

Additionally, it looks like it populates the wrong return_url on the "create group" button

**Comment by jeremystretch** [comment]
Ah, my mistake. I think I was clicking "create" instead.

**Comment by jeremystretch** [comment]
This doesn't seem to be related to FHRP groups specifically, but rather ObjectEditView in general.

**Comment by jeremystretch** [comment]
This looks like a regression introduced in b95773938d50acdb5404a63c346ca93bee5fdbb9
