### ISSUE TITLE
Asking for the ability to hide certain view elements (e.g., hide NAT from the IP Address form)

### ISSUE THREAD

**Issue by brianmiller** [netbox-community/netbox#8104]
### NetBox version

v3.1.1

### Feature type

New functionality

### Proposed functionality

I'm looking for the ability to "hide" any input item from a view.

### Use case

An engineer navigates to IPAM -> IP Addresses to allocate an IPv4 address. This form is only used for this reason (we use webhooks to do more stuff once this record is created, i.e., head out to BIND and create the relevant DNS A, AAAA and PTR records.   

However, the rest of the form contains all sorts of stuff that isn't applicable to our use and confuses some of our junior engineers. If we were able to simply CSS/HTML "hide" these, it would be fantastic.

We heavily rely on Custom Fields for most of our work and hiding the things we don't use would make everyone's life just that much easier.

Thanks again for the excellent work.  We love netbox!

-Brian

**Comment by jeremystretch** [comment]
I'm afraid this isn't something we'll undertake in NetBox. The development burden induced would be exceedingly disproportionate to what little value might be gained, and there's really no need to hide any part of the UI anyway.

> However, the rest of the form contains all sorts of stuff that isn't applicable to our use and confuses some of our junior engineers.

This seems like it's easily addressed through a bit of user education internally.
