### ISSUE TITLE
Add new power outlet CEE 7/16 (Type C) a.k.a. Europlug

### ISSUE THREAD

**Issue by ypid** [netbox-community/netbox#8115]
### NetBox version

v3.1.1

### Feature type

Change to existing functionality

### Proposed functionality

In #7022, CEE 7/16 was added as power port. A power outlet equivalent is missing. I propose to add `ITA Type C (CEE 7/16)` as power outlet.

### Use case

Support the selection of CEE 7/16 (Type C) "Europlug" for power connections in NetBox.

### Database changes

No.

### External dependencies

No.

**Comment by jeremystretch** [comment]
I don't believe there is a specific corresponding outlet for this type. Per [Wikipedia](https://en.wikipedia.org/wiki/CEE_7_standard_AC_plugs_and_sockets#CEE_7/16_plugs):

> There is no socket defined by EN 50075; neither is there a socket specified in CEE 7 to accept only the Europlug. Instead, the Europlug was designed to be compatible with a range of sockets in common use in Europe. These sockets, including the CEE 7/1, CEE 7/3 (German/"Schuko"), CEE 7/5 (French), and most Israeli, Swiss, Danish and Italian sockets, were designed to accept pins of various diameters, mainly 4.8 mm but also 4.0 mm and 4.5 mm, and are usually fed by final circuits with either 10 A or 16 A overcurrent protection devices.

**Comment by ypid** [comment]
Interesting, I have not read this part of Wikipedia, partly because I saw this kind of socket "in the wild". Wikimedia also has a picture of it: https://commons.wikimedia.org/wiki/File:Europlug_extension_cord.jpg and https://commons.wikimedia.org/w/index.php?search=Europlug+socket&title=Special:MediaSearch&go=Go&type=image

How do you want to handle this?

**Comment by grbeneke** [comment]
There is an international standard developed for sockets which natively match with the Europlug - appears to be https://en.wikipedia.org/wiki/IEC_60906-1. Formal adoption in Europe appears to be very poor but it is actively being used elsewhere in the world and it certainly exists in the wild.

**Comment by jeremystretch** [comment]
So should the proposal here be to add IEC 60906-1 as a port type?

**Comment by ypid** [comment]
IEC 060906-1 could be a separate proposal. It does not address my use case.

> Formal adoption in Europe appears to be very poor

I can confirm this.
