### ISSUE TITLE
Inventory templates

### ISSUE THREAD

**Issue by PieterL75** [netbox-community/netbox#8118]
### NetBox version

v3.1.0

### Feature type

Data model extension

### Proposed functionality

Proposal is to create Inventory Templates that allow us to define an inventory item basics,
The device inventory item will need a reference to the template and extended with unique fields like serial numbers

### Use case

In devices, the inventory can be updated by manually entering the Manu/Partid/name,...
Lots of parts are used multiple times in different devices (like in servers :CPU types, Memory or in routers/switches, linecards, routing engines,...), 
It will keep the inventory 'clean' of typo's, garbage, ...
The inventory items can be limited to the only those that are allowed.

### Database changes

A new model is required
dcim.inventory_template
  - Name
  - Manufacturer (dcim.manufacturer)
  - PartID

The dcim.inventory_item needs to be updated
Remove
- Manufacturer (dcim.manufacturer)
- PartID
Add
- Inventory_template (dcim.inventory_template)

There is no need to enforce the Manufacturer to be the same as or limit to the device the inventory item is added to.

**Comment by jeremystretch** [comment]
> There is no need to enforce the Manufacturer to be the same as or limit to the device the inventory item is added to.

We wouldn't remove the manufacturer assignment as part of this. The InventoryItemTemplate model would replicate the manufacturer field and set its value upon the instantiation of new InventoryItems.

**Comment by PieterL75** [comment]
What I meant is, that it should be possible to (for example) put an Samung HD in a Dell server.
That there should be no restriction in the Manufacturer of the Inventory item and the device

**Comment by jeremystretch** [comment]
It's a bit quick, but I think it makes sense to tackle this in v3.2 as it fits in nicely with some of our other milestones (#3087 and #7846).
