### ISSUE TITLE
IP/device de assiginment not working

### ISSUE THREAD

**Issue by kotso** [netbox-community/netbox#8127]
### NetBox version

v3.1.1

### Python version

3.9

### Steps to Reproduce

1. edit any ip assigned to device/interface
2. remove device/interface
3. save

### Expected Behavior

ip is not associated/linked with device/interface

### Observed Behavior

nothing changed, ip still linked to device/interface. 

additionally changelog entry is created that is identical to initial object  (see attachment)

deployment is in docker, we noticed issue since upgrade to 3.1.0, upgrade to 3.1.1 did not changed anything. (not upgrading to 3.1.2 as at this moment docker script is version 3.1.1)

I think it may be frontend bug but I may be mistaken. (as changelog does not deffer) 

<img width="1234" alt="Screenshot 2021-12-21 at 13 58 41" src="https://user-images.githubusercontent.com/1928528/146911150-68e7abcf-ca0e-4f3b-bc0f-3399033e4fb4.png">

**Comment by kotso** [comment]
UPDATE, 

changing interface/device works, only de-assign of any attached device/interface does not work.

**Comment by kotso** [comment]
Checked in latest version, same result.

**Comment by jeremystretch** [comment]
Thank you for opening a bug report. Unfortunately, the information you have provided is not sufficient for someone else to attempt to reproduce the reported behavior. Remember, each bug report must include detailed steps that someone else can follow on a clean, empty NetBox installation to reproduce the exact problem you're experiencing. These instructions should include the creation of any involved objects, any configuration changes, and complete accounting of the actions being taken. Also be sure that your report does not reference data on the public NetBox demo, as that is subject to change at any time by an outside party and cannot be relied upon for bug reports.

**Comment by kotso** [comment]
@jeremystretch thank you for reply.

You can reproduce same in netbox demo.

https://demo.netbox.dev/ipam/ip-addresses/3/

just tried to detach device from that ip and it did not, and change log entry created.

**Comment by kotso** [comment]
as issue reproducible on demo, I'm not providing more details, if you still need, will cleanup my installation and provide data.

**Comment by DanSheps** [comment]
> as issue reproducible on demo, I'm not providing more details, if you still need, will cleanup my installation and provide data.

Please review the contributing document, we require a step-by-step list to reproduce, starting with creation.

**Comment by kotso** [comment]
@DanSheps 

please find step-by-step reproduction manual. (assuming you have at list single device with single interface, if no - create any device with at list one interface)

1. create ip address (any, example: 1.2.3.4/32, status: active), when creating - in interface assignment/device - select any device with interfaces and interface accordingly.
2. after ip created - press edit button, and remove device and interface, press save
3. message displayed that ip saved successfully.
4. but on same screen you can see that device and interface is still assigned.

**Comment by kotso** [comment]
@jeremystretch thank you very much.
