### ISSUE TITLE
Automatic IP address creation button no longer available

### ISSUE THREAD

**Issue by twrona** [netbox-community/netbox#8131]
### NetBox version

v3.1.2

### Python version

3.9

### Steps to Reproduce

1. On IPAM
2. Prefixes
3. Select a prefix 
4. IP Addresses

### Expected Behavior

Hello,

After an update to version 3.1.2, it is no longer proposed the IP available on the prefixes

See screenshot below between version v3.1.2 and v3.0.10

This functionalized has been removed? Or is it a bug of the new version ?

Below is the screenshot in V3.0.10 where the feature is available

![image](https://user-images.githubusercontent.com/96485903/146952881-47b57bd2-4c9f-454c-a599-c633d594db3e.png)

### Observed Behavior

Below the screenshot in V3.1.2 where the feature is not available

![image](https://user-images.githubusercontent.com/96485903/146953883-1a56e000-b29d-41c7-a55b-12474459f800.png)

**Comment by jeremystretch** [comment]
This looks like a bug introduced during the implementation of `ObjectChildrenView`: `add_available_ipaddresses()` is no longer called when retrieving the child objects. Should be an easy fix.

However, I also noticed in the screenshot that you don't have an "Add IP Address" button at top right either. This is shown on my instance of v3.1.2 as well as the demo and appears unrelated to this bug. Are you sure your user has permission to create IP addresses?

**Comment by twrona** [comment]
Pas de problème au niveau des droits, c'est juste que le préfix était utilisé a 100%

ci-dessous une capture avec un autre préfix

![image](https://user-images.githubusercontent.com/96485903/146959520-3eaaf874-4bc5-4837-822b-4498433a4608.png)

Is there a way to work around this bug or do we have to wait for a fix version?
