### ISSUE TITLE
Cannot bulk select objects after HTMX request

### ISSUE THREAD

**Issue by DanSheps** [netbox-community/netbox#8134]
### NetBox version

3.1.2

### Python version

3.8

### Steps to Reproduce

1. Create x number of sites, where x > 50
2. Set per-page to 25 if not already
3. Attempt pagination navigation
4. Attempt to select all objects on the page

### Expected Behavior

All objects on the new page will be selected

### Observed Behavior

No objects selected

**Comment by DanSheps** [comment]
Screenshot incast it isn't
![HTMX query failure](https://user-images.githubusercontent.com/11049792/146966673-15d20bc4-e68d-4ad1-8db1-e4bcff5fd6ff.PNG)
 clear

**Comment by kkthxbye-code** [comment]
The event listener is probably gone when htmx replaces the table. I see that htmx has `htmx.onLoad` which should probably be used to trigger initSelectAll(). Might require some refactoring though.

**Comment by jeremystretch** [comment]
@thatmattlove can you confirm? Is there an alternate way that we can initialize the listener so that new DOM elements are also caught?
