### ISSUE TITLE
Add new field to Device/VM models for out-of-band management IP address 

### ISSUE THREAD

**Issue by bitcollector1** [netbox-community/netbox#8137]
### NetBox version

v3.1.2

### Feature type

Data model extension

### Proposed functionality

BMC IP address is a key management item we track as a custom field, it would be great if the Device Management Box had an option for this information. 

   

### Use case

Currently I need to drill down into the interfaces to see the BMC IP address. We are creating custom fields so this information is available on the device page for easy reference, same as the primary IPv4 address. 

<img width="656" alt="Screen Shot 2021-12-21 at 10 14 00 AM" src="https://user-images.githubusercontent.com/50723251/146979456-d3c5ca46-958d-4158-8e7f-6b4a77f330ea.png">

**Comment by jeremystretch** [comment]
I think what you're referring to as BMC is more generally known as an out-of-band (OOB) management IP (but correct me if I'm mistaken). NetBox has the concept of management-only interfaces (via the `mgmt_only` boolean attribute), but as you note we don't currently provide a direct link from a device/VM to this IP address.

As seen in the screenshot above, NetBox has two primary IP fields on the device and VM models: `primary_ip4` and `primary_ip6`. The generic `primary_ip` attribute included in the REST API representation of a device or VM points to one or the other depending on the value of the [`PREFER_IPV4`](https://netbox.readthedocs.io/en/stable/configuration/dynamic-settings/#prefer_ipv4) configuration parameter.

I'm not sure we'd want to fully replicate this structure for an OOB IP address, but it might make sense to introduce only a single `oob_ip` ForeignKey field pointing to the desired OOB IP address. I'm open to other opinions.

**Comment by sdktr** [comment]
Seems like a great use case for 'computed fields'. A type of custom field that is rendered when accessed.
Assuming that the IP can be retrieved from the device object, by filtering on type 'mgmt_only', or a user defined tag.

**Comment by jeremystretch** [comment]
> Seems like a great use case for 'computed fields'.

It would need to be a discrete field, as there could be more than one OOB IP address.

**Comment by bitcollector1** [comment]
it's nothing critical, once you explained the model it seemed like it was more effort than it was worth. Thanks for consideration, love everything about NetBox. Hope you have a Merry X-Mas!!

**Comment by bluikko** [comment]
Wouldn't BMC be modeled as just another Interface on a Device, perhaps following a naming convention for a uniform name?

**Comment by jeremystretch** [comment]
> Wouldn't BMC be modeled as just another Interface on a Device, perhaps following a naming convention for a uniform name?

The interface itself would, but I think there's value in introducing a direct relationship to the preferred OOB IP address as well.

I'm going to tag this for milestone assignment with the presumption that it will entail adding a single `oob_ip` ForeignKey field to the Device model.

**Comment by bragatto** [comment]
Wouldn't it make sense to add the BMC as a child device and have the server as the parent device?

**Comment by DanSheps** [comment]
Please continue discussion from #9050 here

**Comment by ITJamie** [comment]
Based on the convo from the other issue. 
We could just look to add the ips of interfaces which have the mgmt_only boolean?

**Comment by bitcollector1** [comment]
just wanted to mention that we tried the workaround for this, the services thing, and it was less than ideal as when the IPMI address is changed it's not reflected in the service template. So this means it's just another thing that needs to be updated :(

**Comment by bitcollector1** [comment]
our users would love to have that IPMI address show up right there on the front page just like the primary IPv4 address does :)

**Comment by ITJamie** [comment]
> > Wouldn't BMC be modeled as just another Interface on a Device, perhaps following a naming convention for a uniform name?
> 
> The interface itself would, but I think there's value in introducing a direct relationship to the preferred OOB IP address as well.
> 
> I'm going to tag this for milestone assignment with the presumption that it will entail adding a single `oob_ip` ForeignKey field to the Device model.

@jeremystretch  Id be happy to attempt this in a PR if this is something you would consider this as acceptable?

**Comment by arthanson** [comment]
@ITJamie Would you still be interested in working  this and submitting a PR, potentially for the upcoming 3.5 release?

**Comment by ITJamie** [comment]
@arthanson  I would be interested in this if it's just another field to the existing models, if the idea is make a new relationships model to do what @jeremystretch mentioned on https://github.com/netbox-community/netbox/pull/11953#issuecomment-1502166006 then its probably best taken on by another maintainer

**Comment by jsenecal** [comment]
After glancing over #13013 I believe I'm actually on the same page as @DanSheps in https://github.com/netbox-community/netbox/pull/11953#issuecomment-1555150918

IMHO this would be better fledged out as a m2m relationship with an intermediary model and some validation to prevent things like duplicate "Primary IPv4" addresses.

**Comment by ITJamie** [comment]
ok. in which case id need a bit more guidance on how we want that to look (eg guidance on what the extra intermediary model should be called, and even some validation decisions, can an ip had multiple relationships).

I would have initially suggested ip roles or ip services but theres kind of already terminology in netbox around both of those right now.

**Comment by ITJamie** [comment]
if we did IPAddressDeviceFunctionalRole it would hint that we would need IPAddressVDCFunctionalRole and IPAddressVirtualMachineFunctionalRole.

would we want that or would we want one relationships table to host all of them

**Comment by jeremystretch** [comment]
As the scope of this FR was limited to introducing a field to track out-of-band IPs, and because I'd like this to ship in NetBoxv3.6, I've merged @ITJamie's PR #13013 mostly as-is. If anyone would like to propose a change to the underlying mechanism for tracking primary/OOB IP relationships, they are welcome to do so in a separate FR.
