### ISSUE TITLE
Tags not available through REST API on Wireless LAN

### ISSUE THREAD

**Issue by rodvand** [netbox-community/netbox#8140]
### NetBox version

v3.1.2

### Python version

3.8

### Steps to Reproduce

Through the Web interface:
1. Create tag "TagA"
2. Create a Wireless LAN "WLAN One" and add the tag "TagA" to the Wireless LAN

### Expected Behavior

To see the tags assigned to the Wireless LAN in the API browser.

### Observed Behavior

The tag is not visible through the API. It is also not assign tags using the REST API. It is visible in the Web UI.

**Comment by rodvand** [comment]
It's the same with the Wireless Link model. Can see the tags in the Web UI, but not create/see with the REST API.

**Comment by jeremystretch** [comment]
Some other fields seem to have been omitted from the serializers as well. It actually looks like an entire line within the `fields` attribute on either serializer was mistakenly deleted at some point.
