### ISSUE TITLE
editing interface form is populated with interface data from different device

### ISSUE THREAD

**Issue by michaeldialpad** [netbox-community/netbox#8155]
### NetBox version

v3.0.1

### Python version

3.7

### Steps to Reproduce

1 - create LAG interface on device
2 - edit the physical interface on device
3 - select LAG interface from list 
4 - click save

### Expected Behavior

the LAG should be associated to the same device interface

### Observed Behavior

it attempts to save and gives the error "the selected LAG interface (ae0) belongs to a different device"
I inspected the form data and the data populated in the associated interface/lag fields is confirmed from a different device

**Comment by jeremystretch** [comment]
> v3.0.1

Please upgrade to a recent stable release of NetBox and test again. It's likely your issue has already been resolved.
