### ISSUE TITLE
Add "els-030" cable type 

### ISSUE THREAD

**Issue by bhunt64848** [netbox-community/netbox#8156]
### NetBox version

v2.10.4

### Feature type

Change to existing functionality

### Proposed functionality

We are requesting the type els-030 be added under the copper choices for cable type. 

### Use case

It is a crossover cable used for T1 connections.

**Comment by jeremystretch** [comment]
Can you reference any documentation for this type? How does it differ from the types of twisted pair copper cabling that NetBox already includes?

**Comment by jeremystretch** [comment]
Closing as there has been no further response.
