### ISSUE TITLE
Fully Random IPv6 IIDs

### ISSUE THREAD

**Issue by itsgottabered** [netbox-community/netbox#8158]
### NetBox version

v3.1.2

### Feature type

New functionality

### Proposed functionality

Addition of a toggle when adding ipv6 addresses to create a fully random IID.
* Toggle at prefix level so any ip address created would be random (GUI tickbox in prefix options)
* Toggle at address creation to select if address should be random (GUI - when in prefix -> ip addressed, maybe an additional button for create random address, or a sub-button on 'add an IP address' to select random)
* Toggle for api endpoint for creating random address, /ipam/ip-ranges/{id}/available-ips/, 
​/ipam​/prefixes​/{id}​/available-ips​/ to allow for programmatic creation of random addresses.

### Use case

RFC7721 outlines use of different IID generation techniques to enhance security. Unpredictable IIDs add another layer of opaqueness to the network and having the ability to create random IIDs from Netbox will assist adoption of these techniques.

**Comment by DanSheps** [comment]
Might make sense to also allow computation based on EUI-64 in addition to this random generation.

**Comment by itsgottabered** [comment]
> Might make sense to also allow computation based on EUI-64 in addition to this random generation.

I did think about some of the other cases in the RFC but thought it might be too niche of a request. However, I was thinking if you added an address from an interface that had a MAC address configured, EUI-64 could be an option there.
