### ISSUE TITLE
Bring back "unassigned" indicators in prefix IP address lists or equivalent functionality

### ISSUE THREAD

**Issue by bluikko** [netbox-community/netbox#8161]
### NetBox version

v3.1.2

### Feature type

Change to existing functionality

### Proposed functionality

Edit: seems #8131 is about this same thing. Very not obvious, it was not even found with search keywords "free" "unassigned".

Up to 3.1.1 (I think?)  when viewing IP address lists of a specific prefix `/ipam/prefixes/#/ip-addresses/` there used to be a clear indicator for unused IP addresses, for example if between 192.0.2.10 and 192.0.2.13 there were two unused IP addresses (.11 and .12) the IP address list show it as "2 free" with an easy-to-notice background.

Now in 3.1.2 the IP addresses list is a wall of text with no indicators for free IP addresses.

This issue proposes to have _some_ functionality to display unused IP addresses within a prefix.
- Bring back the "n addresses unused" indicator.
- Add an additional tab on `/ipam/prefixes/#/` in addition to Prefix, Child Prefixes, Child Ranges, IP Addresses, ... called "Unused Addresses" (or whatever) that lists unused IP addresses in the prefix.
- Or both of the above, or some other way to quickly list available IP addresses of a prefix.

I did not see a relevant change listed in the changelog so maybe this was an unintended consequence of some other change...?

Anyways it is surprising to see the functionality gone, it was very useful. So useful that I'm in fact unsure if I am "using it wrong".

### Use case

Quickly display unused IP addresses within a prefix, without scanning through the whole prefix and having to think each line if the numbers are exactly sequential or if there's a free IP address hiding in there somewhere.

### Database changes

None I believe.

### External dependencies

None.

**Comment by bluikko** [comment]
Duplicate of #8131 despite its totally different title.

**Comment by DanSheps** [comment]
Duplicate of #8131
