### ISSUE TITLE
Bridge members panel in interface view

### ISSUE THREAD

**Issue by candlerb** [netbox-community/netbox#8163]
### NetBox version

v3.1.2

### Feature type

Change to existing functionality

### Proposed functionality

When viewing interface details (e.g. `/dcim/interfaces/3141/`), there is a section for Child interfaces (i.e. other interfaces whose Parent points at this one), and a panel for LAG Members if the interface is a LAG.  But bridge members are not shown.

I propose that if the interface type is "Bridge" then a Bridge Members panel is added - similar to the "LAG Members" panel - showing interfaces whose Bridge attribute points at this interface.

### Use case

Be able to see and navigate to bridge member interfaces.  Consistency with LAG member interfaces.

Workaround: you can manually enter URL `/dcim/interfaces/?bridge_id=3141`

### Database changes

None

### External dependencies

None

**Comment by stephanblanke** [comment]
I can try to implement this

**Comment by BrunoBlanes** [comment]
Quick question, are the changes from 3.1.11 available in 3.2.0 given that both came out on the same day? If not, is there a timeline for it?
