### ISSUE TITLE
Admin: Permissions: virtualization interface permissions not available by default

### ISSUE THREAD

**Issue by geor-g** [netbox-community/netbox#8167]
### NetBox version

v3.1.2

### Python version

3.7

### Steps to Reproduce

1. Navigate to 'Admin' -> 'Permissions' and seach for 'interface'

(Note: I can't tell if people are expected to create these permissions themselves via 'ADD PERMISSION' -- just a heads up that these should be available by default, potentially.)

Thanks for developing NetBox!

### Expected Behavior

Permissions wrt both 'dcim' and 'virtualization' objects are listed.

### Observed Behavior

Permissions only wrt 'dcim' objects are listed.

**Comment by DanSheps** [comment]
Anything in permissions you need to create your self.  Is this a new installation?

**Comment by geor-g** [comment]
> Anything in permissions you need to create your self. Is this a new installation?

Interesting, I wasn't aware. Not a bug then, I suppose, closing this ticket accordingly.

It's not a new installation, it was set up some time ago, v2.6.0.

**Comment by DanSheps** [comment]
I believe we introduced virtualization interfaces after 2.6 (can't be 100% sure though) so it would make sense that it wasn't caught when you upgraded as there would be no existing permissions for that.

Check out the permissions framework, it is pretty cool.

**Comment by geor-g** [comment]
> Check out the permissions framework, it is pretty cool.

Are you referring to assigning specific permissions to specific users and/or groups? If so, I'm doing this, and this lead to this ticket. :)

Great work in this area especially; I'm also already a fan of the 'conditional' webhooks. Thanks!
