### ISSUE TITLE
Unable to update Custom Field via API

### ISSUE THREAD

**Issue by talha700** [netbox-community/netbox#8170]
### NetBox version

v3.1.2

### Python version

3.9

### Steps to Reproduce

Trying to update the custom field via Netbox REST API using python requests

custom field of os_version (text) associated with devices

```
import requests


url = "https://<ip>/api/dcim/devices/10/"

token = "some_token"


device = {
  "name": "some-device",
  "device_type": 1,
  "device_role": 4,
  "site": 1,
  "custom_fields":{"os_version":"55"}
}

response = requests.patch(url,verify=False, headers={'Authorization': f'Token {token}'} ,
                data=device)
        
                
print(response.status_code)      
```

### Expected Behavior

should update the custom field of os_version

### Observed Behavior

return status code of 500

**Comment by DanSheps** [comment]
The information provided is not sufficient to reproduce this issue.  Please provide more detail on how you are reproducing this (Python API, Rest API, pynetbox, etc) and the exact steps to reproduce including what objects need to be created before attempting to recreate.

**Comment by talha700** [comment]
> The information provided is not sufficient to reproduce this issue. Please provide more detail on how you are reproducing this (Python API, Rest API, pynetbox, etc) and the exact steps to reproduce including what objects need to be created before attempting to recreate.

I have updated the issue ,kindly have a look

**Comment by talha700** [comment]
Solved it , I wasn't crafting my request correctly ,closing this.
