### ISSUE TITLE
Cloning an IP address should initialize the next available IP address

### ISSUE THREAD

**Issue by jeremystretch** [netbox-community/netbox#8171]
### NetBox version

v3.1.2

### Feature type

Change to existing functionality

### Proposed functionality

When cloning an IP address, or after creating a new IP address with the "add another" button, the IP address field of the resulting form should be initialized with the next available IP within the parent prefix (if any).

### Use case

It's reasonable to assume that the user likely wants to use the successive IP address immediately following the one just viewed or created. (And if not, the user remains free to enter a different address.)

**Comment by PieterL75** [comment]
Can you do the same for a vlan?
