### ISSUE TITLE
Unable to de-assign IP from interface

### ISSUE THREAD

**Issue by PieterL75** [netbox-community/netbox#8178]
### NetBox version

v3.1.2

### Python version

3.8

### Steps to Reproduce

1. create an ip adress
2. create a device with an interface
3. modify the ip address and assing it to the device and interface
4. save the ip
5. edit the IP
6. remove the assigned device and interface
7. save the IP

### Expected Behavior

The IP should no longer be linked to the devce/interface

### Observed Behavior

The IP is still linked to the device/interface.

**Comment by jeremystretch** [comment]
Thank you for submitting this issue, however it appears that this topic has already been raised. Please see issue #8127 for further discussion.

**Comment by PieterL75** [comment]
I have to improve my bug search skills :-)

Ty for fixing it !

Pieter
