### ISSUE TITLE
Add all interface IP in table view of Devices and Virtual Machines

### ISSUE THREAD

**Issue by FlochonR** [netbox-community/netbox#8180]
### NetBox version

v3.1.2

### Feature type

Change to existing functionality

### Proposed functionality

Currently, in Devices and Virtual Machines table view, we have the possibility to see the primary IP address.
To see the different interfaces linked to our device or virtual machine, we need to open the element and go to "Interfaces".
The new functionality I propose it's to add in the table view a column with the list of IP interface.
Not to give more information about the interface name or other, just a list of all IP linked to our device/virtual machine
For example:
All IP
10.10.10.10/32, 12.11.236.5/32
1.2.14.15/32
172.15.56.23/32, 52.96.1.3/32, 10.10.5.6/32

### Use case

The use case is to have an overview of all IP linked to our device/VM, not only the Primary.
For exemple, we have a Primary IP on our device + a management IP on it we currently must open the device to view the management IP
With the overview, we can see the management IP in the table view.

### Database changes

I don't think that any database changes will be required.

### External dependencies

I don't think that any external dependencies will be required.

**Comment by DanSheps** [comment]
I just want to point out the flaw in this...

Let's say up have a chassis router with 3 48 port line cards (144 ports), each with an IP assigned.  That is potentially a huge database query for just a single device, now add 50 more potential devices.

I think a more wise way to handle this would be to have a custom link that points to the IP address portion of the IPAM that filters on device/VM.

Not to display them in the table itself.

**Comment by jeremystretch** [comment]
Somewhat related, #8112 is already open to explore the feasibility of dynamically embedding additional IP address information in a separate table below each interface role. However, as @DanSheps points out, it would not make sense to include a column of all assigned IP addresses directly within the device/VM tables, and there are more efficient ways to display that information (i.e. by filtering the IP addresses list).
