### ISSUE TITLE
CSV import: accept `slug` values for role and platform

### ISSUE THREAD

**Issue by tacerus** [netbox-community/netbox#8203]
### NetBox version

v3.1.3

### Feature type

Change to existing functionality

### Proposed functionality

I noticed a similar change has been implemented in #5003 and would like to follow up on this by requesting the acceptance of `slug` values for the role and platform fields in virtual machine imports.

### Use case

This would make the machine-creation and import of CSV files easier and avoid quoting issues with values containing a comma in their name.

**Comment by jeremystretch** [comment]
This is already supported. Per the instructions on the import form:

> Related objects may be referenced by any unique attribute. For example, vrf.rd would identify a VRF by its route distinguisher. 

To specify e.g. a role by slug, you would name the header `role.slug`, and specify the desired slug values in each corresponding cell. Same for platform (`platform.slug`). Hope that helps!

**Comment by tacerus** [comment]
Oh! It did not occur to me that this example referred to a slug. Easier than I thought - thank you, much appreciated!
