### ISSUE TITLE
adding license information

### ISSUE THREAD

**Issue by gerardocastaldo** [netbox-community/netbox#8205]
### NetBox version

v3.1.3

### Feature type

Data model extension

### Proposed functionality

I propose to add information about licenses in use on the equipment and them expirations and then a dedicated view to see these list.

### Use case

i think its very interesting to monitor licensing in use on devices and tracking the state. I think, for example, at the dna licensing for Cisco or all non perpetual license.

### Database changes

.

### External dependencies

.

**Comment by jeremystretch** [comment]
Thank you for your interest in extending NetBox. Unfortunately, the information you have provided does not constitute an actionable feature request. Per our [contributing guide](https://github.com/netbox-community/netbox/blob/develop/CONTRIBUTING.md), a feature request must include a thorough description of the proposed functionality, including any database changes, new views or API endpoints, and so on. It must also include a detailed use case justifying its implementation. If you would like to elaborate on your proposal, please modify your post above. If sufficient detail is not added, this issue will be closed.
