### ISSUE TITLE
Swagger descriptions are incorrect in several places

### ISSUE THREAD

**Issue by abhi1693** [netbox-community/netbox#8206]
### NetBox version

v3.1.3

### Python version

3.9

### Steps to Reproduce

Go to https://demo.netbox.dev/api/swagger.json and inspect the description for `GET` `/dcim/power-feeds/`. 

```
"/dcim/power-feeds/": {"get": {"operationId": "dcim_power-feeds_list", "description": "Overrides ListModelMixin to allow processing ExportTemplates.",
```

### Expected Behavior

The descriptions should describe the component

### Observed Behavior

On most `GET` method description, the same text is displayed

```
Overrides ListModelMixin to allow processing ExportTemplates.
```

**Comment by jeremystretch** [comment]
It looks like Swagger is returning the docstring for the viewset method for some reason. IMO this is not desirable behavior, as the docstring is intended for developer use and often not suitable for display to the end user.

**Comment by DanSheps** [comment]
Went down the rabbit hole, unless we override it, this is the function that defines view names:

https://github.com/encode/django-rest-framework/blob/f9ccbad4d910d19e4298300ee90467051fc08f47/rest_framework/views.py#L47

```python
def get_view_description(view, html=False):
    """
    Given a view instance, return a textual description to represent the view.
    This name is used in the browsable API, and in OPTIONS responses.

    This function is the default for the `VIEW_DESCRIPTION_FUNCTION` setting.
    """
    # Description may be set by some Views, such as a ViewSet.
    description = getattr(view, 'description', None)
    if description is None:
        description = view.__class__.__doc__ or ''

    description = formatting.dedent(smart_str(description))
    if html:
        return formatting.markup_description(description)
    return description
```

It looks like we can assign the description with a "description" attribute on the class.

**Comment by abhi1693** [comment]
Still relevant
