### ISSUE TITLE
Webhook object_updated does not return full object

### ISSUE THREAD

**Issue by abhi1693** [netbox-community/netbox#8207]
### NetBox version

v3.1.3

### Python version

3.9

### Steps to Reproduce

1. Create a webhook for `dcim > device` with all operations
2. Go to any device, edit and update
3. Capture the webhook payload

### Expected Behavior

The `platform` data in the webhook payload should be the same as when called over the API. 

### Observed Behavior

The payload is missing several fields including `napalm_driver`, here is an example

```
"platform": {
        "id": 1,
        "url": "/api/dcim/platforms/1/",
        "display": "cisco_ios",
        "name": "cisco_ios",
        "slug": "cisco_ios"
      },
```

**Comment by DanSheps** [comment]
The webhook sends the serialized display of device, which includes the platform information in the device view, not the platform view.

Platform information in the device view uses a nested serialized and not the full serialized which returns what you see here.
