### ISSUE TITLE
Trace functionality not shown bridge or wireless link

### ISSUE THREAD

**Issue by Abulhallaj** [netbox-community/netbox#8209]
### NetBox version

v3.1.3

### Python version

3.8

### Steps to Reproduce

We have some wireless radio devices that connect sites. in every site the **LAN** interfaces on this devices is connected to Switch and documented, also **WLAN** interfaces are connected together via wireless link. In every device we create a **bridge1** interface and bridged the **WLAN** and **LAN** interface into it.

### Expected Behavior

```
------------------
|                |
|      SW01      |
|                |
-----| LAN |------
        |
        | Cable
        |
-----| LAN |------
|                |  \
|WirelessDevice01|   bridge1
|                |  /
-----| WLAN |-----
        |
        | Wireless Link
        |
-----| WLAN |-----
|                |  \
|WirelessDevice02|   bridge1
|                |  /
-----| LAN |------
        |
        | Cable
        |
-----| LAN |------
|                |
|      SW02      |
|                |
------------------

```

### Observed Behavior

The Cable trace just shown the Cable path and not the bridge area or wireless link was shown in trace as excepted. wireless link can traced exclusively but just shown wireless link.

**Comment by jeremystretch** [comment]
This is expected behavior. Any number of interfaces can be attached to a bridge group, so the cable trace cannot assume the next hop. If you'd like to enable tracing directly across these, you can bridge the LAN and WLAN interfaces to one another directly.

**Comment by Abulhallaj** [comment]
>  you can bridge the LAN and WLAN interfaces to one another directly.
I also do that and that's not work
![image](https://user-images.githubusercontent.com/20490198/148009624-d7c0de06-deba-4a9f-91c3-5b5f60411635.png)
![image](https://user-images.githubusercontent.com/20490198/148009669-6fd1445c-2a99-497e-8237-4b43a0f6c3d8.png)
![image](https://user-images.githubusercontent.com/20490198/148009733-2bbdcd8b-4b18-4ea2-bbc4-7c6f0fe0b681.png)
