### ISSUE TITLE
Plugins template errors

### ISSUE THREAD

**Issue by kort3x** [netbox-community/netbox#8211]
### NetBox version

v3.1.3

### Python version

3.8

### Steps to Reproduce

I have two plugins installed - both show this problem

https://github.com/mattieserver/netbox-topology-views
https://github.com/DanSheps/netbox-secretstore

1. Click on Plugins/plugin

### Expected Behavior

Plugin page is shown

### Observed Behavior

Template error gets thrown:

<class 'django.template.exceptions.TemplateDoesNotExist'>

**Comment by jeremystretch** [comment]
You'll need to raise bugs against those plugins. This is out of scope for NetBox itself.
