### ISSUE TITLE
ValueError: 'role' does not resolve to an item that supports prefetching error when selecting Prefix -> IP Addresses

### ISSUE THREAD

**Issue by bmhughes** [netbox-community/netbox#8213]
### NetBox version

v3.1.4

### Python version

3.9

### Steps to Reproduce

1. Upgrade to 3.1.4
2. Open an IPAM prefix.
3. Select the IP address tab.
4. Traceback is observed.

### Expected Behavior

The prefix IP address page should have been rendered.

### Observed Behavior

A server error is returned with the following traceback.

```python
Traceback (most recent call last):
  File "/opt/netbox/venv/lib64/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/opt/netbox/venv/lib64/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/netbox/venv/lib64/python3.9/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/opt/netbox/netbox/utilities/views.py", line 93, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/opt/netbox/venv/lib64/python3.9/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/opt/netbox/netbox/netbox/views/generic.py", line 124, in get
    table = self.table(self.prep_table_data(request, child_objects, instance), user=request.user)
  File "/opt/netbox/netbox/ipam/views.py", line 515, in prep_table_data
    return add_available_ipaddresses(parent.prefix, queryset, parent.is_pool)
  File "/opt/netbox/netbox/ipam/utils.py", line 54, in add_available_ipaddresses
    if not ipaddress_list:
  File "/opt/netbox/venv/lib64/python3.9/site-packages/django/db/models/query.py", line 284, in __bool__
    self._fetch_all()
  File "/opt/netbox/venv/lib64/python3.9/site-packages/django/db/models/query.py", line 1326, in _fetch_all
    self._prefetch_related_objects()
  File "/opt/netbox/venv/lib64/python3.9/site-packages/django/db/models/query.py", line 813, in _prefetch_related_objects
    prefetch_related_objects(self._result_cache, *self._prefetch_related_lookups)
  File "/opt/netbox/venv/lib64/python3.9/site-packages/django/db/models/query.py", line 1721, in prefetch_related_objects
    raise ValueError("'%s' does not resolve to an item that supports "
ValueError: 'role' does not resolve to an item that supports prefetching - this is an invalid parameter to prefetch_related().
```

**Comment by bmhughes** [comment]
Ran into this after upgrading to 3.1.4 to fix #8196 as unfortunately another bug has been introduced.

**Comment by candlerb** [comment]
I see this too, URL is `/ipam/prefixes/NNN/ip-addresses/`

Temporary workaround: navigate to `/ipam/ip-addresses/?q=&parent=1.2.3.0%2F24`

**Comment by jeremystretch** [comment]
FYI this is not related to #8196, it just had not been reported.

**Comment by bmhughes** [comment]
> FYI this is not related to #8196, it just had not been reported.

Apologies, bad wording on my part there

**Comment by bfarver** [comment]
We see this also when navigating to /ipam/prefixes/NNN/ip-addresses/ for both v4 and v6 prefixes that contain IP addresses.  Prefixes that don't have IP address information populated load this page ok, and show 254 available, etc.

We upgraded from 2.11.12 

Netbox Version 3.1.4
Python Version 3.7.5

**Comment by saruter** [comment]
I can confirm this bug. 
Upgraded to 3.1.4 an getting the same error when opening a prefix with used ip-addresses and getting:

```<class 'ValueError'>

'role' does not resolve to an item that supports prefetching - this is an invalid parameter to prefetch_related().

Python version: 3.8.12
NetBox version: 3.1.4``
```
Path is for example /ipam/prefixes/2960/ip-addresses/

Prefixes without ip addresses are working fine.

**Comment by sim0nx** [comment]
```
<class 'ValueError'>

'role' does not resolve to an item that supports prefetching - this is an invalid parameter to prefetch_related().

Python version: 3.9.2
NetBox version: 3.1.4
```

same here fyi

**Comment by przemekjagielski** [comment]
me too...
```
<class 'ValueError'>

'role' does not resolve to an item that supports prefetching - this is an invalid parameter to prefetch_related().

Python version: 3.9.6
NetBox version: 3.1.4
```

**Comment by geor-g** [comment]
Dear people, do you mind attaching emojis to the initial post of this issue, instead of adding 'me too' posts? This would limit the noise for people subscribed to this bug.

Thank you, and sorry for this post, which adds to the noise as well.

**Comment by RobinBeismann** [comment]
Hi @jeremystretch,

sorry to ask, but do you have an idea when you push the next release where this fix will be included? The issue exists on the docker container tagged by latest and therefor already hit quite a few people (including us).

**Comment by jeremystretch** [comment]
@RobinBeismann should have v3.1.5 pushed out shortly.
