### ISSUE TITLE
Show available IP addresses indicators gone

### ISSUE THREAD

**Issue by DerDanilo** [netbox-community/netbox#8225]
### NetBox version

v3.1.2

### Python version

3.9

### Steps to Reproduce

Quoting from https://github.com/netbox-community/netbox/issues/289
```
The current IPAM views only display addresses added to the system. It does not display available addresses within a subnet. It would be helpful to see all addresses within a subnet, noting each address' status. This could be similar to the "status" column on the /ipam/prefixes/ page, indicating "available", "reserved", or "active". Being able to filter the list based on status, and showing all addresses on a page rather than paginated would also be helpful.
```
1. Click on IP addresses of any given prefix
2. Check for available IPs

### Expected Behavior

Having indicators showing available IPs wherever there are free ones. Just like it was before. 

Reference:  
https://github.com/netbox-community/netbox/issues/289#issuecomment-237257185

### Observed Behavior

It's hard to see free IPs within the selected range. The available IPs indicators are gone. It's just like before ( Show available IP addresses #289 ) was implemented.
https://github.com/netbox-community/netbox/issues/289

**Comment by jeremystretch** [comment]
Thank you for submitting this issue, however it appears that this topic has already been raised. Please see issue #8131 for further discussion.
