### ISSUE TITLE
Link Providers NOC & Admin Contact to a Contact object

### ISSUE THREAD

**Issue by jasonyates** [netbox-community/netbox#8234]
### NetBox version

3.1.2

### Feature type

New functionality

### Proposed functionality

The Circuit Providers model has the ability to manually enter a NOC & Admin contact and also the ability to associate Contact objects. 

It would be useful to re-use the contact objects and be able to associate them directly to a NOC and Admin contact of a provider as opposed to NOC & Admin being freeform text.

Use case example, Equinix are a provider of a site (i.e. Colo Space) and a Circuit (i.e Equinix Connect DIA). I have an Equinix NOC Contact created and associated to the site however I cannot use that same NOC Contact in the provider as "NOC Contact" is a freeform text box. 

### Use case

Allows for more efficient re-use of Contact objects and reduction of data duplication. One place to manage NOC & Admin contacts.

**Comment by DanSheps** [comment]
I think instead of linking, as providers are able to hold contact objects, this should be a deprecation of the NOC contact and Admin contact fields.

**Comment by jeremystretch** [comment]
As of v3.2.0 it's now possible to assign contacts (and their corresponding role & priority) to a provider, which I believe addresses the use case here.

As #9046 has been opened to deprecate the provider model's built-in contact fields, I'll go ahead and close this out.
