### ISSUE TITLE
ValueError when listing IP Addresses inside Prefix

### ISSUE THREAD

**Issue by fknorn** [netbox-community/netbox#8241]
### NetBox version

v3.1.4

### Python version

3.8

### Steps to Reproduce

1. Open prefix
2. Click "IP Addresses" tab
3. If (and only if) the prefix has one or more IPs, the following error is thrown:

```
<class 'ValueError'>

'role' does not resolve to an item that supports prefetching - this is an invalid parameter to prefetch_related().

Python version: 3.8.10
NetBox version: 3.1.4
```

### Expected Behavior

The page should show as expected, and as it did prior to this update (I believe I was on 3.1.1 before, there everything worked fine).

### Observed Behavior

Error message show above.

**Comment by jeremystretch** [comment]
Thank you for submitting this issue, however it appears that this topic has already been raised. Please see issue #8213 for further discussion.
