### ISSUE TITLE
Circuits list view to display formatted commit rate

### ISSUE THREAD

**Issue by jasonyates** [netbox-community/netbox#8246]
### NetBox version

3.1.2

### Feature type

Change to existing functionality

### Proposed functionality

The current circuit list view (/circuits/circuits/) has a column called "Commit Rate (kbps) and shows the rate in kbps i.e. 1000000

However when looking at the circuit details, the commit rate is translated into something more human readable i.e 1 Gbps

Proposing either changing the existing Commit Rate (kbps) column to also translate the commit rate or the addition of an extra column simply called Commit Rate that has the human readable version.

### Use case

Easier for non-technical users to quickly see the commit rate of a circuit in the table view. Brings more parity to the circuit details view.

**Comment by jeremystretch** [comment]
> changing the existing Commit Rate (kbps) column to also translate the commit rate

The best way to handle this is probably to introduce a custom column class that displays the human-friendly value on `render()` and the raw number on `values()` (for export).
