### ISSUE TITLE
Enable pinning objects to a user's home page

### ISSUE THREAD

**Issue by jeremystretch** [netbox-community/netbox#8248]
### NetBox version

v3.1.4

### Feature type

New functionality

### Proposed functionality

Include a "pin to homepage" button on the view for (almost?) every object. When clicked, a new record will be created associating the object with the current user as a "pinned" or "favorite" object. The NetBox home page will be extended to display a list of all such objects for the current user. Objects can be "unpinned" from this list as needed.

This idea was originally proposed by @bogdancordos in #8235.

### Use case

This allows a user to compile a list of commonly-viewed objects for near- or long-term use.

It's also somewhat related to #7855, which proposes displaying a history of recently viewed objects.

### Database changes

I imagine the introduction of a simple new model within the users app (e.g. `UserFavorite`) mapping the user object to the "pinned" object via a generic foreign key. We would probably want to track creation date, and _possibly_ assign a numeric weight to aid in reordering objects, depending on how much functionality is needed.

**Comment by hagbarddenstore** [comment]
It would be really nice if this feature also includes models defined in plugins.

**Comment by samschmitt22** [comment]
One small option that would be nice to add to this (although I understand if it doesn't fit the spirit of this): It would be nice to be able to click on a "favorite" on the homepage (or a button on that favorite) and jump directly to the DNS name/IP of that object if there is one. This would make it easy to quickly jump to those items. You would have to assume the protocol, but http/https is probably safe coming from the web.

**Comment by bogdancordos** [comment]
> One small option that would be nice to add to this (although I understand if it doesn't fit the spirit of this): It would be nice to be able to click on a "favorite" on the homepage (or a button on that favorite) and jump directly to the DNS name/IP of that object if there is one. This would make it easy to quickly jump to those items. You would have to assume the protocol, but http/https is probably safe coming from the web.

I guess you can create a custom link for DCIM > device based on the object name or IP. You can even create a link for each protocol you want to connect to those objects PROT://{{ obj.name }} .

**Comment by jeremystretch** [comment]
> You can even create a link for each protocol you want to connect to those objects PROT://{{ obj.name }} .

Just a note: These links will depend on browser support. So for example if you made an `ssh://` link, clicking it wouldn't do anything unless you had something installed or configured in your browser to open an SSH client for it.

**Comment by samschmitt22** [comment]
> > One small option that would be nice to add to this (although I understand if it doesn't fit the spirit of this): It would be nice to be able to click on a "favorite" on the homepage (or a button on that favorite) and jump directly to the DNS name/IP of that object if there is one. This would make it easy to quickly jump to those items. You would have to assume the protocol, but http/https is probably safe coming from the web.
> 
> I guess you can create a custom link for DCIM > device based on the object name or IP. You can even create a link for each protocol you want to connect to those objects PROT://{{ obj.name }} .

Thats a good idea I haven't thought of that. However I guess we'd want those custom links to someone be surfaced on the favorite on homepage.

**Comment by jeremystretch** [comment]
Blocked by #9416
