### ISSUE TITLE
IDs to be searchable

### ISSUE THREAD

**Issue by elpedriyo** [netbox-community/netbox#8250]
### NetBox version

3.1.4

### Feature type

Data model extension

### Proposed functionality

All ID references in netbox, interfaces, front ports, rear ports, cables, and the rest of objects that have an ID refered to, for them to be able to be searched in the main top global search box, and filtered, in each netbox section.
![image](https://user-images.githubusercontent.com/3207791/148306331-94c407f0-8816-46bd-ad99-297797f146cb.png)

### Use case

When I have an ID extracted from logs and need to search for it, so that it makes it quicker to find it, instead of going control+F in the browser.

**Comment by jeremystretch** [comment]
Thank you for your interest in extending NetBox. Unfortunately, the information you have provided does not constitute an actionable feature request. Per our [contributing guide](https://github.com/netbox-community/netbox/blob/develop/CONTRIBUTING.md), a feature request must include a thorough description of the proposed functionality, including any database changes, new views or API endpoints, and so on. It must also include a detailed use case justifying its implementation. If you would like to elaborate on your proposal, please modify your post above. If sufficient detail is not added, this issue will be closed.

**Comment by elpedriyo** [comment]
Hello Jeremy, don't know if it is better understood now :)

**Comment by DanSheps** [comment]
This is a database ID, if you have the database ID you can just simply navigate to the object (example: /dcim/devices/1234/ ).

I don't think this needs to be searchable.
