### ISSUE TITLE
Add power port types EPS7114 and EPS7104 (aka GST 18/3)

### ISSUE THREAD

**Issue by PieterL75** [netbox-community/netbox#8258]
### NetBox version

v3.1.4

### Feature type

Data model extension

### Proposed functionality

Can you please add the power connecters EPS7114 (aka GST 18/3F)  and EPS7104 (aka GST 18/3M)?

### Use case

We use them to interconnect powerbars with the PDU's

**Comment by jeremystretch** [comment]
Could you see if you can track down the formal specs for these please? I can only find vendor info and I'm not 100% confident in their descriptions being unfamiliar with the form factor myself.
