### ISSUE TITLE
Elevation Image Links Not Working Behind Reverse Proxy

### ISSUE THREAD

**Issue by FreeWillyB** [netbox-community/netbox#8264]
### NetBox version

v3.1.0 Docker

### Python version

3.9

### Steps to Reproduce

Use a reverse proxy to access the Netbox Docker. View the elevation of the rack and hover over the devices in the rack and you'll notice that the URL is for "localhost:8000" instead of the URL of the reverse proxy. 

Commenting out lines #60 and #225 in "/netbox/dcim/api/views.py" and then restarting the docker eliminated the issue.

### Expected Behavior

When accessing netbox at https://netbox.mydomain.com, the links for the devices on the elevations should be something like "https://netbox.mydomain.com/dcim/devices/100/"

### Observed Behavior

The link instead has a URL of "http://localhost:8000/dcim/devices/100/"

**Comment by jeremystretch** [comment]
> Use a reverse proxy to access the Netbox Docker.

This repo does not accept issues for the [netbox-docker](https://github.com/netbox-community/netbox-docker) project. If you believe you've encountered a bug, please open an issue there.
