### ISSUE TITLE
Add Cisco StackWise-80/-160/-320/-480 interface types

### ISSUE THREAD

**Issue by michaelklose** [netbox-community/netbox#8265]
### NetBox version

v3.1.4

### Feature type

Change to existing functionality

### Proposed functionality

Currently NetBox already supports the interface types Cisco StackWise and Cisco StackWise Plus please also add newer StackWise types named StackWise-80, StackWise-160, StackWise-320 and StackWise-480

For reference:
StackWise-80 (used e.g. Catalyst 9200L)
StackWise-160 (used e.g.  Catalyst 3650/9200)
StackWise-320 (used e.g. Catalyst 9300L)
StackWise-480 (used e.g. Catalyst 3850/9300)
https://www.cisco.com/c/en/us/products/collateral/switches/catalyst-9300-series-switches/white-paper-c11-741468.html
https://www.cisco.com/c/en/us/products/collateral/switches/catalyst-3650-series-switches/data_sheet-c78-729449.html
https://www.cisco.com/c/en/us/products/collateral/switches/catalyst-9200-series-switches/nb-06-stackwise-architecture-cte-en.html#_Toc13521191

### Use case

New interfaces types to model connections between switch stacks.

**Comment by DanSheps** [comment]
@bluikko Going to ping you to see if I can assign it.

**Comment by bluikko** [comment]
Heh, please excuse me. I was actually looking for this feature myself and went ahead.
