### ISSUE TITLE
Interface Bridges in Device Type

### ISSUE THREAD

**Issue by PaulR282** [netbox-community/netbox#8272]
### NetBox version

v3.1.4

### Feature type

Change to existing functionality

### Proposed functionality

Currently you can only bridge interfaces if the device already exists. It would be nice to "pre-bridge" interfaces in the device Type.

### Use case

When you have devices like mediaconverter, currently you have to manually bridge the 2 interfaces after creating the device for every single device. It would be a lot easier to bridge the interfaces in the device type.

**Comment by sleepinggenius2** [comment]
Just wanted to add that it would be nice to be able to do the same for *Parent interface* and *LAG interface*. I've run into both situations recently. On our aggregation switches, we create a LAG for the uplink and it would certainly save a step to have that already set up in the device template. The bigger issue I had recently was with the parent/child relationship, as we have some devices with bulk connectors that we currently model as a physical connector with virtual child interfaces under it and it's cumbersome having to remember to create those relationships each time a new device is added. Please let me know if I need to open a separate FR or if it's sufficient to update this one to include all the interface relationship types. I assume the implementation for one should be almost identical for the others, but maybe I'm missing something.
