### ISSUE TITLE
More Interface Types

### ISSUE THREAD

**Issue by PaulR282** [netbox-community/netbox#8273]
### NetBox version

v3.1.4

### Feature type

Change to existing functionality

### Proposed functionality

Currently, there are missing Interface types especially for glass fiber, like LC, SC or ST connectors. Those are already front/rearport types but aren't  listed in interface types.

### Use case

There are devices like mediaconverter that have interfaces with those connectors.

**Comment by jeremystretch** [comment]
These aren't listed because they're physical termination form factors, not interface types. This is covered by the documentation.

**Comment by PaulR282** [comment]
But there are devices with interfaces with those physical terminations

**Comment by PaulR282** [comment]
Also, if the interface types are the protocols behind the interface, the glass fiber protocols are missing, like 1000BASE-SX, 10GBASE-LR. This would solve the problem with the mentioned devices.
