### ISSUE TITLE
All paths of device in Related Paths when cable tracing

### ISSUE THREAD

**Issue by PaulR282** [netbox-community/netbox#8275]
### NetBox version

v3.1.4

### Feature type

Change to existing functionality

### Proposed functionality

When you have a device and trace an interface, it would be nice if you see all interfaces traces of the device in the "Related Paths" section of a cable trace.

### Use case

If you have e.g. a switch and want to click through all the cables that are connected to the switch, it would be nice to just have a list in the cable trace and not be forced to go back to the interface overview.

**Comment by DanSheps** [comment]
I think this could be problematic for many reasons, not the least of which is you could have hundreds (or thousands) of interfaces on a single device.

**Comment by PaulR282** [comment]
Then you could make it optional in the device type to ensure performance with devices with a lot of interfaces

**Comment by jeremystretch** [comment]
This seems like it would be very redundant given that every components list already has a "trace" button next to each item already. I don't see much value in implementing this.

**Comment by PaulR282** [comment]
It´s not redundant, because the trace is already in the database. It´s just 2 ways to get it to display.

**Comment by jeremystretch** [comment]
> It´s just 2 ways to get it to display.

Yes, that's what I mean by redundant.
