### ISSUE TITLE
Trace at front-port endpoint

### ISSUE THREAD

**Issue by PaulR282** [netbox-community/netbox#8276]
### NetBox version

v3.1.4

### Feature type

Change to existing functionality

### Proposed functionality

When you have an interface connected to a front-port (or as many front/rear-ports as you wish in between), currently, you can only trace that path at the connected points, but not the last front.port. So it would be nice if the trace button at the front-port would be active although nothing is connected directly to it, only through the rear-port.

### Use case

This would make cable tracing better, because you can see at a front-port overview which front-ports have a connection/interface at the other side

**Comment by jeremystretch** [comment]
You've opened several issues today regarding tracing cables, and honestly I'm not sure what you're trying to do. I'm going to close this one; please share more detail in #8277.
