### ISSUE TITLE
Trace without interface

### ISSUE THREAD

**Issue by PaulR282** [netbox-community/netbox#8277]
### NetBox version

v3.1.4

### Feature type

Change to existing functionality

### Proposed functionality

Currently, you can only trace cables when at least one interface is connected to one side. It would be nice to be able to trace without an interface.

### Use case

When you have cables through multiple segments you would be able to trace those to see all the points where the cable is going through without virtual connection to e.g. a switch.

**Comment by jeremystretch** [comment]
It is already possible to trace cables from both terminations (e.g. interfaces) and pass-through ports. What are you trying to do?

**Comment by PaulR282** [comment]
I have some points where I don´t like how the cable trace is being built:

1. I think it would be good to trace cable paths where no interface is connected
2. (#8276) This may be fixed with the first point, but when you have something like interface -> front-port1 -> rear-port1 -> rear-port2 -> front-port2, you can´t click the trace button (when you are in the front-port overview in the device of front-port2) of front-port2
3. -> #8275

**Comment by emjemj** [comment]
We have a considerable fiber plant documented in netbox and not having the ability to trace without connecting an interface to the path is a real problem. We have thousands of pairs of pre-installed cables and currently I see two options for tracing a "non-used" circuit. 

1. Go hop-by-hop on the odf front/rear ports until you get at the other end. 
2. Create a dummy tracer-device to which you can connect the front-port of the odf port you are tracing enabling the cable trace functionality to work.

Neither of these methods are practical nor elegant. We would really appreciate this functionality.

**Comment by xkilian** [comment]
This is very pertinent for teams modelling fiber plant installations, as the fiber runs are typically installed and documented by one team and the connecting of devices to the fiber front-ports is done by another team. Both teams need to be able to validate paths that are not yet connected by an end device.
As a constraint, such a trace would require that the far end by a connected interface or a front port termination. IMO.

**Comment by jeremystretch** [comment]
Currently, we only store in the database paths which have a concrete originating point, i.e. an interface or similar terminating object. (These are stored as [CablePath](https://github.com/netbox-community/netbox/blob/69eb6b11d0ee288b41d6b905e890b5995273e092/netbox/dcim/models/cables.py#L303) instances.) While it might be feasible to relax this constraint and maintain a CablePath instance for all partial paths, doing so would require a good amount of work to ensure paths are adjusted appropriately as additional cables are installed and removed.

If someone would like to own this initiative and devise an implementation, I'll happily assign it. (However, given the almost certain change to the data model, it implementation would probably need to be assigned a release milestone.)

**Comment by fablabo** [comment]
Last time I checked, in 2.5.13 it was possible to perform cable traces without an interface connected on either end. It's great that newer versions of netbox provide support for modeling WDM etc but it seems that this came with a huge loss.
