### ISSUE TITLE
All interfaces of virtual chassis in api

### ISSUE THREAD

**Issue by PaulR282** [netbox-community/netbox#8278]
### NetBox version

v3.1.4

### Feature type

Change to existing functionality

### Proposed functionality

Currently, when you look up the interfaces of virtual chassis (`/api/dcim/interfaces/?virtual_chassis_id=X`) you only see the interfaces of the master but not the other devices in the virtual chassis. It would be nice to get a list of all interfaces.

### Use case

When writing own plugins/programs that use the api this would be a nice and easy way to get all interfaces of virtual chassis.

**Comment by jeremystretch** [comment]
> Currently, when you look up the interfaces of virtual chassis (/api/dcim/interfaces/?virtual_chassis_id=X) you only see the interfaces of the master but not the other devices in the virtual chassis.

This filter already returns all interfaces assigned to members within the virtual chassis. Here's the [filterset code](https://github.com/netbox-community/netbox/blob/develop/netbox/dcim/filtersets.py#L879-L883) and an [example](https://demo.netbox.dev/api/dcim/interfaces/?virtual_chassis_id=1) on the demo instance.
