### ISSUE TITLE
No virtual chassis name in rack view

### ISSUE THREAD

**Issue by PaulR282** [netbox-community/netbox#8279]
### NetBox version

v3.1.4

### Python version

3.8

### Steps to Reproduce

1. Create a rack
2. Add 2 devices with no name in rack
3. Create virtual chassis
4. Add devices as member
5. Open rack

### Expected Behavior

The name displayed should be something like [virtual-chassis name]:[virtual-chassis position], like in older versions (before 3.1)

### Observed Behavior

Device Type name is being displayed

**Comment by jeremystretch** [comment]
This was changed in #8092
