### ISSUE TITLE
Small Typo in services.md

### ISSUE THREAD

**Issue by tibuski** [netbox-community/netbox#8280]
### Change Type

Cleanup (formatting, typos, etc.)

### Area

Functionality/features

### Proposed Changes

Small typo in first sentence, "four" should be "for":
A service represents a layer **_four_** TCP or UDP service available on a device or virtual machine.

**Comment by DanSheps** [comment]
TCP/UDP is layer 4 of the OSI model, which is why it says `layer four`.

**Comment by tibuski** [comment]
... now I really feel stupid ... sorry for the time you lost on this "issue"
