### ISSUE TITLE
Cluster count missing from tenant api output

### ISSUE THREAD

**Issue by jasonyates** [netbox-community/netbox#8285]
### NetBox version

3.1.5

### Python version

3.9

### Steps to Reproduce

Assign a Cluster to a Tenant. 
Retrieve Tenant details via API i.e. /api/tenancy/tenants/5/

### Expected Behavior

cluster_count is returned as part of the API response

### Observed Behavior

cluster_count is missing from the API response

**Comment by jeremystretch** [comment]
This is a bug. The field is declared on the serializer but its value is not being populated by the view.
