### ISSUE TITLE
How to add tags

### ISSUE THREAD

**Issue by bitshiftnetau** [netbox-community/netbox#8288]
### Change Type

Addition

### Area

Configuration parameters

### Proposed Changes

There does not seem to be anywhere that describes how to add tags through the interface. Adding them dynamically to devices or objects does not seem to work and the docs do not explain how this functionality is supposed to work

**Comment by DanSheps** [comment]
All model data in NetBox has to be manually created, this isn't going to change.

I don't see the need to add an additional "You need to create the tag before it can be used" to the documentation

**Comment by bitshiftnetau** [comment]
Sure, there is a manual process that's cool. I just can't find where the creating of tags actually takes place.

**Comment by DanSheps** [comment]
You can get on slack or open a GitHub discussion for this question
