### ISSUE TITLE
Dynamically add tags

### ISSUE THREAD

**Issue by bitshiftnetau** [netbox-community/netbox#8289]
### NetBox version

v3.1.2

### Feature type

Change to existing functionality

### Proposed functionality

The user should be able to dynamically add tags when none are found. For example, when adding a device. 

### Use case

When I am creating devices and don't wish to abandon the work already done to fill out the form, just to backtrack and create a simple tag of all things. Or to save and come back, it's a waste of time and risks tasks being left half-completed should something more urgent arise.

**Comment by bitshiftnetau** [comment]
Actually I would expand this to dynamically adding most extraneous data such as Manufacturers, Device Roles, etc... basically anything that is an ATTRIBUTE of a device/organization/site and not a central feature of core data input which one would expect from a workflow of this nature.

**Comment by DanSheps** [comment]
We used to allow this until #3703.  This was changed in 2.9.0, with good reason.

This isn't something we are going to add-back.  For adding tags, almost all fields within a specific model that access a related model are dynamic.  You can go to tags in a new window, add a tag and then search for it in the add/edit window you had open.

**Comment by bitshiftnetau** [comment]
Yeh that's fair. Junk tags and unauthorized additions are an organizational nightmare.
