### ISSUE TITLE
Including examples of usage of controls beyond the observation that said controls exist

### ISSUE THREAD

**Issue by bitshiftnetau** [netbox-community/netbox#8290]
### Change Type

Addition

### Area

Other

### Proposed Changes

The docs are rather sparse, to say the least. This is nothing short of the most beautiful irony. 

It would be helpful to include examples of usage, where controls are located, what must precede their creation, etc.. 

Common sense could apply here but I will give a general example:

https://netbox.readthedocs.io/en/stable/models/dcim/virtualchassis/

"To add a virtual chassis, go to X and select Y. In order to create a virtual chassis you will need to do A or B and C"

**Comment by bitshiftnetau** [comment]
Happy to do the work, though I am very new to netbox and don't have some of these answers (hence the request 😅). Will need some guidance.

**Comment by DanSheps** [comment]
Issues are not a place to have answers answered.  There is slack and GitHub discussions for that.

**Comment by bitshiftnetau** [comment]
Nah that's alright. Think I might just use something else. Thanks anyway!
