### ISSUE TITLE
Set "VM Role" to default off

### ISSUE THREAD

**Issue by bitshiftnetau** [netbox-community/netbox#8291]
### NetBox version

v3.1.2

### Feature type

Change to existing functionality

### Proposed functionality

Set "VM Role" to default off for all new devices created, or as an alternative a way to select some kind of global profile so that we can toggle this functionality depending on the deployment scenario

### Use case

In most deployments, there will be a majority network/storage devices or vm devices. Despite hyper-convergence, there are scenarios where the VM devices remain a minority.

**Comment by DanSheps** [comment]
This is a well established default within NetBox, we are not going to change the default at this point
