### ISSUE TITLE
Allow Custom Links to be enabled/disabled

### ISSUE THREAD

**Issue by rodvand** [netbox-community/netbox#8296]
### NetBox version

v3.1.5

### Feature type

Data model extension

### Proposed functionality

Add the option to disable a custom link.

### Use case

When utilising various plugins in NetBox we sometimes use URLs to access the plugin data. Plugins aren't always updated to support the latest and greatest NetBox version straight away so we disable the plugin for upgrades (we must be on the latest NetBox, of course!). To avoid user confusion I remove the custom links referencing the plugin. And when the plugin author updates the plugin I add the custom link back to NetBox. Having an enabled toggle on the custom link would save me some work. 

### Database changes

Have to add a field to the CustomLink model. Something like this I suspect:
```
enabled = models.BooleanField(
        default=True
    )
```

**Comment by jeremystretch** [comment]
Probably something we should have implemented originally, the same way we allow enabling and disabling webhooks. I'm going to tag this for v3.2 as it's very easy to implement (but will effect an API change).
