### ISSUE TITLE
Retain existing filters when clicking a tag

### ISSUE THREAD

**Issue by jasonyates** [netbox-community/netbox#8298]
### NetBox version

3.1.5

### Feature type

Change to existing functionality

### Proposed functionality

When filtering a view i.e. /dcim/devices/ the displayed tags are clickable, however clicking a tag removes any existing filters applied to the view.

Proposing that clicking a tag would retain any existing filters applied to the view. 

### Use case

Allows for quicker filtering of elements within Netbox.

E.g. Clicking through to the Devices list from a sites Stat panel produces the URL dcim/devices/?site_id=XX trying to quickly filter that down further by clicking one of the displayed tags is not possible as clicking a tag produces a URL of /dcim/devices/?tag=network

Proposal is to retain existing view filters when clicking a tag within a view.

**Comment by jeremystretch** [comment]
> clicking a tag removes any existing filters applied to the view.

But there are many cases where that's likely the desired behavior. I'm not sure it makes sense to continue applying pre-selected filters, which may result in surprising behavior.

**Comment by jasonyates** [comment]
> But there are many cases where that's likely the desired behavior. I'm not sure it makes sense to continue applying pre-selected filters, which may result in surprising behavior.

I guess it depends on the context of the filter. If I navigate to the device list from a Site's Stat panel it auto applies the Site filter, I'd expect clicking a tag to further filter the view, not remove the existing filters. With 100's of devices per site and 1000's of devices in Netbox, having clicking a tag remove existing filters makes clicking it largely useless.

Perhaps a modal that asks if you want to retain existing filters or not when clicking a link that would otherwise remove them?

**Comment by DanSheps** [comment]
There is a difference that sites panel is viewing a single object, and when you are click on the devices that takes you to a list view.

I think adding a context menu on right click on a link would be a better way to handle that.  You retain the existing behaviour while introducing the ability to apply the additional filter.
