### ISSUE TITLE
User configurable default filters for tables

### ISSUE THREAD

**Issue by jasonyates** [netbox-community/netbox#8300]
### NetBox version

3.1.5

### Feature type

New functionality

### Proposed functionality

Allow the Netbox administrator and/or logged in user to configure default filters for tables.

This could link with #7759 

### Use case

In some situations it could be beneficial to have administrator defined (or user defined) default filters for certain tables. My use case specifically is with Circuits. We recently migrated all of our circuit data from an in-house tool over to Netbox including historical data. As it stands, we have 300+ circuits however only ~150 are currently active. 9/10 I'm only looking in Netbox for active circuit information so it would be useful to have a default filter applied to that table to only show Active circuits.

**Comment by sdktr** [comment]
Related to userfavorites https://github.com/netbox-community/netbox/issues/8248 ?

**Comment by jeremystretch** [comment]
> Allow the Netbox administrator and/or logged in user to configure default filters for tables.

I find it difficult to imagine the workflow for this. For example, what happens if a user clears any applied filters? Would that clear _all_ filters, or would it restore their default set? How would you distinguish between the two.

Maybe instead of having a default, we could allow users to define and save filter presets, and NetBox would just remember the last-used preset. I'm not sure exactly what a preset would look like, but it would really only need to map a user and object type to a JSON dict of applied filters, with a descriptive name. If this sounds reasonable I can put some more thought into it and open a new FR.

**Comment by jasonyates** [comment]
> I find it difficult to imagine the workflow for this. For example, what happens if a user clears any applied filters? Would that clear _all_ filters, or would it restore their default set? How would you distinguish between the two.

In my mind if a user was to clear filters, it would clear them as opposed to restoring to the default. The intention isn't to stop users getting to data, it's to guide them to the most relevant data by pre-loading a filter.


> Maybe instead of having a default, we could allow users to define and save filter presets, and NetBox would just remember the last-used preset. I'm not sure exactly what a preset would look like, but it would really only need to map a user and object type to a JSON dict of applied filters, with a descriptive name. If this sounds reasonable I can put some more thought into it and open a new FR.

This works too. Perhaps once you have a filter created, on the applied filters section the ability to save it as a default view (and clear it) would be a good first step.

**Comment by jeremystretch** [comment]
> In my mind if a user was to clear filters, it would clear them as opposed to restoring to the admin defined default.

Right, but how would you convey that in the UI? For example, if I have a default filter set for sites and I navigate to `/dcim/sites/`, is it going to apply the default filter? If so, what query parameters would I specify to _not_ apply the filter? I'd want to avoid doing anything to declare a negative (e.g. `?default_filter=False`).

**Comment by jasonyates** [comment]
> Right, but how would you convey that in the UI? For example, if I have a default filter set for sites and I navigate to `/dcim/sites/`, is it going to apply the default filter? If so, what query parameters would I specify to _not_ apply the filter? I'd want to avoid doing anything to declare a negative (e.g. `?default_filter=False`).

Why would you need an option to not apply the filter with a query parameter? As a netbox administrator i'm trying to reduce some of the noise within the application for the majority of my users. In my example for the FR, the data we store around circuits is crucial and we have a genuine use case for keeping historical circuit data (billing disputes months after disconnect etc) but the number of people that need to access that historical data is small compared to our user base.

What i'm proposing is to allow me as an administrator of the system to define a default filter and have that automatically applied for all users when they first visit a table view e.g. /dcim/circuits/ - If a user wants to remove the filter to see all of the data they just clear it as they normally would had they defined it themselves e.g.

<img width="578" alt="Screenshot 2022-01-15 at 09 30 38" src="https://user-images.githubusercontent.com/242483/149629665-369fad3c-9390-464e-8998-90fac44475e1.png">

**Comment by Ryujn91** [comment]
I have a similar use / need for functionality like this. 

Ours is specific to sites / devices. we have hundreds of branches but typically this is fairly static data so is not needed as often, however the DC's are much more dynamic. having a mechanism where when loading these pages it applies a default filter to display a specific site but users were still free to filter anyway they needed. 

This just helps to remove noise from the off, i'm not sure how it would be implemented but just thought id second the desire to see such functionality.

**Comment by jeremystretch** [comment]
Sorry, this fell off my radar.

> Why would you need an option to not apply the filter with a query parameter?

Consider the screenshot above. Presumably, this is what the user sees when visiting `/circuits/circuits/`, without specifying any filters (because they've been defined as defaults). So what happens when they want to deactivate the default filter(s)? You can't just return to the default URL; you need some way to declare that the default filter should no longer be applied.

**Comment by UlrikNN** [comment]
Hi, We would love this functionality :) We are looking to keep our history in the database by tagging deleted/scrapped items as "Deleted" A default, user clearable  filter would ensure thet a user normally sees "live" stuff but still can show historical entities when need arises. Hope this posting avoids the "pending closure" status ;)

Looking forward to any responses!
