### ISSUE TITLE
Delete modal doesn't work on some pages

### ISSUE THREAD

**Issue by kkthxbye-code** [netbox-community/netbox#8301]
### NetBox version

v3.1.6-dev

### Python version

3.9

### Steps to Reproduce

1. Create a device
2. Create interface
3. View device under the interface tab
4. Press delete

### Expected Behavior

Delete modal pops up

### Observed Behavior

Nothing happens.

Cause: #8231

The reason is that some tabs already define the modal block in their template:

https://github.com/netbox-community/netbox/blob/f1472d218e157160306e7007fb3a705208901a71/netbox/templates/dcim/device/interfaces.html#L82-L84

Changing it to:

```python
{% block modals %}
  {% include 'inc/htmx_modal.html' %}
  {% table_config_form table %}
{% endblock modals %}
```

fixes the issue. When the tabs templates define the modal, they don't get the default modal defined in `generic/object.html`

This is an issue in all templates that overwrite the modals block and use the htmx modal.

Examples:

* `dcim/device/interfaces.html`
* `dcim/device/frontports.html`
* `dcim/device/rearports.html`
* `dcim/device/consoleports.html`

etc.

**Comment by kkthxbye-code** [comment]
I guess you could actually just add `{{ block.super }}` to all the offending blocks. Not really sure what is best practice.

**Comment by jeremystretch** [comment]
Yep, `{{ block.super }}` is the way to go. Good catch.
