### ISSUE TITLE
Bulk editing Interfaces doesn't support alphanumeric ranges like when you create them

### ISSUE THREAD

**Issue by lucasteinke** [netbox-community/netbox#8304]
### NetBox version

v3.1.5

### Python version

3.9

### Steps to Reproduce

1. Select multiple interfaces of a device
2. Edit them
3. Enter `test[1-42]` into the "Label" field
4. Save

### Expected Behavior

Like with bulk creation, where there's a hint "Alphanumeric ranges are supported. (Must match the number of names being created.)", I'd expect the labels to be `test1`, `test2`, `test3`, ..., `test42`.

### Observed Behavior

The labels are all the same, namely `test[1-42]`, so alphanumeric ranges aren't supported in bulk editing.

**Comment by jeremystretch** [comment]
This is working as intended. If you'd like to open a feature request, please do so [here](https://github.com/netbox-community/netbox/issues/new?template=feature_request.md). Be sure to include a detailed implementation proposal and use case.
