### ISSUE TITLE
Device: Management: Primary IPv4: 'NAT for ...' link contains erroneous trailing ')', breaks link

### ISSUE THREAD

**Issue by geor-g** [netbox-community/netbox#8315]
### NetBox version

v3.1.5

### Python version

3.9

### Steps to Reproduce

1. Create IPv4 address `192.168.41.101/24`
2. Create another IPv4 address `10.25.220.7/24`
2. Establish NAT mapping between them: `192.168.41.101/24` is `NAT inside` of `10.25.220.7/24`
2. Assign `192.168.41.101/24` as `primary IP` to a device
3. Open this device
4. Below `Management`, next to `Primary IPv4`, click on the link `(NAT for 10.25.220.7/24)`

### Expected Behavior

The link should point to the correct location `<a href="/ipam/ip-addresses/1031/">`.

### Observed Behavior

The link points to the incorrect location `<a href="/ipam/ip-addresses/1031/)">` which breaks it.

![2022-01-11_16-18](https://user-images.githubusercontent.com/8934138/148982527-bdf1f4a7-5750-4f87-977f-c3268f1f841c.png)

**Comment by jeremystretch** [comment]
@mrmrcoleman would you like to take this one?

**Comment by mcoleman-NS1** [comment]
I'll take it!

**Comment by jeremystretch** [comment]
Going to snag this real quick for v3.1.7.
