### ISSUE TITLE
Leave out blank filter items from a URL

### ISSUE THREAD

**Issue by ryanmerolle** [netbox-community/netbox#8318]
### NetBox version

v3.1.5

### Feature type

Change to existing functionality

### Proposed functionality

Currently the url for a object/table/view filter is populated with all possible filter items even if said filter item is empty.  This can be confusing when you forward said URL to someone.

It would be nice to either have a button to click that would "clean" unneeded characters from a url OR just not populate URLs with empty filter items.

This was discussed on slack months ago, and suggested to be entered as a FR, but I forgot to submit it.

### Use case

Example when filter devices by objects you get:
```
https://demo.netbox.dev/dcim/devices/?q=&status=active&serial=&asset_tag=&mac_address=&has_primary_ip=&virtual_chassis_member=&console_ports=&console_server_ports=&power_ports=&power_outlets=&interfaces=&pass_through_ports=&local_context_data=
```

Where the filter you could get away with is:
```
https://demo.netbox.dev/dcim/devices/?q=&status=active
OR
https://demo.netbox.dev/dcim/devices/?status=active
```

### Database changes

N/A

### External dependencies

N/A

**Comment by jeremystretch** [comment]
AFAIK the only way to accomplish this would be by controlling the form submission with Javascript and filtering out "empty" values from the parameters prior to submission. IMO this does not seem like an appropriate place to spend development effort, particularly given how few people we've seen contribute in a substantial way to NetBox's frontend development, but I'll leave it open for volunteers.
