### ISSUE TITLE
Add iec-60320-c15 as power port type

### ISSUE THREAD

**Issue by trrunde** [netbox-community/netbox#8322]
### NetBox version

v3.1.5

### Feature type

Data model extension

### Proposed functionality

It would be nice to have the iec-60320-c15 as an option for the power port. 
I believe typicaly Cisco uses this, for instance cisco asr9903

### Use case

More accurate documentation in netbox

**Comment by jeremystretch** [comment]
C15 is a power outlet type. C16 (or C14) would be the corresponding power port (inlet) type.

**Comment by trrunde** [comment]
Your are right about that. I got confused by the cable I used to connect power.
Will close the issue
