### ISSUE TITLE
server error when try to get IPs for a prefix

### ISSUE THREAD

**Issue by empusas** [netbox-community/netbox#8328]
### NetBox version

v3.1.4

### Python version

3.9

### Steps to Reproduce

1. Go to prefix and lick on IP addresses or use the url /ipam/prefixes/<id>/ip-addresses/

### Expected Behavior

Show the list of IP addresses for that prefix

### Observed Behavior

A new page with server error shows this message:

<class 'ValueError'>

'role' does not resolve to an item that supports prefetching - this is an invalid parameter to prefetch_related().
 
Python version: 3.9.9
NetBox version: 3.1.4

**Comment by rodvand** [comment]
Upgrade to 3.1.5 and it's fixed.
