### ISSUE TITLE
Support the use of NetBox's generic views by plugins

### ISSUE THREAD

**Issue by jeremystretch** [netbox-community/netbox#8334]
### NetBox version

v3.1.5

### Feature type

New functionality

### Proposed functionality

Formally support and document the use of NetBox's generic view classes by plugins. These are to include initially:

- ObjectView
- ObjectEditView
- ObjectDeleteView
- ObjectListView
- BulkImportView
- BulkEditView
- BulkDeleteView

Additional views may also be added or created depending on feedback from plugin authors.

Most of these classes likely must undergo so amount of refactoring and formalization to ensure a degree of maturity suitable for the inclusion in a public framework.

### Use case

Much like Django's own [generic views](https://docs.djangoproject.com/en/stable/ref/class-based-views/), use of these views enables plugin authors to avoid writing a substantial amount of boilerplate code.

**Comment by johannwagner** [comment]
Hey,

we actually implemented this functionality within a quite hacky plugin our my employer. We could contribute an initial implementation. Is this the desired approach?

Best Regards, 
  Johann

**Comment by jeremystretch** [comment]
@johannwagner I think for the most part this amounts to "hardening" the existing view classes to make them suitable for use outside NetBox core. I'd be interested to see what changes you made. Is there a way you could share a summary, short of drafting a whole PR?

**Comment by johannwagner** [comment]
Mostly it's fixing up the url names because of the plugin prefix. The rest "just works" but lacks a lot of documentation, because the public use wasn't intended yet.

**Comment by jeremystretch** [comment]
@johannwagner Roger. I know @DanSheps was working on that recently in the [`6221-pluginviews` branch](https://github.com/netbox-community/netbox/tree/6221-pluginviews); does that look similar to your tweaks?

**Comment by johannwagner** [comment]
Yup, we have similar patches, I just looked it up. 
We have patches for:
- `viewname` and `validated_viewname` template tags for the plugin prefix
- ButtonsColumn also to implement the plugin prefix.

Those patches enables us to write plugin with newly introduced models with almost no boilerplate. Most boilerplate code comes from the `<modelname>.html` of the generic object view, which could be eliminated by some finer block overrides.

**Comment by johannwagner** [comment]
I also would like to see a better method of using different tabs within a detailed view, this is kinda hacky right now.

**Comment by DanSheps** [comment]
Yeah, now that I see you are going the mkdocstring for documenting the API, I will work on cleaning up the view documentation

**Comment by jeremystretch** [comment]
@DanSheps I've started on this in the [`8334-plugin-views` branch](https://github.com/netbox-community/netbox/tree/8334-plugins-views). I still have some work to do around refactoring & documentation; once that's done I'll fold in your changes from #6221. Then we can reassess scope and decide if there's anything else we need to add for #8334 specifically. Sound good?

**Comment by DanSheps** [comment]
Sounds good with me.  I will look into the button class thing, I think I might have covered that, I just need to double check.
