### ISSUE TITLE
created & last_updated fields missing from some REST API calls

### ISSUE THREAD

**Issue by jasonyates** [netbox-community/netbox#8342]
### NetBox version

3.1.6-dev

### Python version

3.8

### Steps to Reproduce

A number of REST API calls are missing created & last_updated fields in their response. No functional impact however for parity across all API calls perhaps it would be useful to have the fields returned consistently.

Examples:
/api/dcim/virtual-chassis/
/api/dcim/cables/
/api/dcim/power-panels/
/api/dcim/rack-reservations/ (Has created but not last_updated)

### Expected Behavior

created & last_updated fields are returned for all relevant objects

### Observed Behavior

created & last_updated are missing some some objects

**Comment by jasonyates** [comment]
Happy to submit a PR for this. 

If accepted, presumably this should be in feature not develop branch due to API changes?

**Comment by jeremystretch** [comment]
Given that it's a bug, and the fix would restore the API's _intended_ functionality, it's fine to handle in the `develop` branch. (New features or functionality would need to be implemented in `feature`.)
