### ISSUE TITLE
Devices > Edit: (get() returned more than one Manufacturer) when using multi custom permissions by tags

### ISSUE THREAD

**Issue by atom-tr** [netbox-community/netbox#8351]
### NetBox version

v3.1.5

### Python version

3.8

### Steps to Reproduce

I want to grant users or groups permissions to view and manage some objects by using tag.  When I use a non-Superuser, I will see multiple result with each permission.
Below is an issue when it's happen.

1. I create 2 permissions for all models have tags with:

  - `[{"tags__name": "READABLE"}]`: for all user can be view
  - `[{"tags__name": "TECH"}]`: for only technician can be create and edit.

2. Technicians will be have both of 2 permissions  above
3. I creat a Manufacturer with 2 tags (READABLE & TECH). One for everyone can see, One for technician can  edit and add to devices (I use admin account)
4. I login to an technician account and create or edit a Device with this Manufacturer

- I create a device with this Manufacturer => False
![Error](https://i.imgur.com/GaNRLAm.png)

- I edit a device with this Manufacturer => False
![Error](https://i.imgur.com/7vLWRiL.png)

### Expected Behavior

I can add multiple permissions for an object. For a group can edit their own objects and share to everyone with tag READABLE

### Observed Behavior

If you use non-admin account, An objects have multiple permissions will return multi results (It's just 1 objeect) for each tag (permission).
In above case, It's raise error because Manufacturer which have Device Type I chosen have 2 tags. And each tags is belong to each custom permission.

**Comment by jeremystretch** [comment]
Hi, could you please revise your post above to be more clear about what objects you're creating? You mention permissions but don't say to which type(s) of object they're assigned. You also mention manufacturers but are creating/editing devices.

**Comment by atom-tr** [comment]
> Hi, could you please revise your post above to be more clear about what objects you're creating? You mention permissions but don't say to which type(s) of object they're assigned. You also mention manufacturers but are creating/editing devices.

I create permissions base on Tags, so i create a permission for all object have tags. So when i create a Device with a manufacturer, netbox return 2 manufacturers with each tag and each permission, which is only one if I login by admin account.

**Comment by atom-tr** [comment]
Of course I can split permisson for some models that everyone can use. Its will fix the problem.

**Comment by jeremystretch** [comment]
Please go back and rewrite your original post above to clearly indicate the steps someone else can take to reproduce the reported problem.

**Comment by jeremystretch** [comment]
Closing this as sufficient reproduction instructions have not been provided.
