### ISSUE TITLE
Python 3.9 is available in AppStream.

### ISSUE THREAD

**Issue by joubbi** [netbox-community/netbox#8354]
### Change Type

Correction

### Area

Installation instructions

### Proposed Changes

The installation instructions here: https://netbox.readthedocs.io/en/stable/installation/3-netbox/
mentions that CentOS 8 does not provide Python 3.7 or later via its native package manager.

It is possible to install Python 3.9 from AppStream.
I installed Netbox on the latest RHEL8 and was able to do `sudo yum install python39`.

If installing Python 3.9 this way the LDAP installation described here https://netbox.readthedocs.io/en/stable/installation/6-ldap/ will fail.
The `pip3 install django-auth-ldap` will fail unless you have done this `sudo yum install python39-devel`.

I think the instructions should be updated with this.

**Comment by ryanmerolle** [comment]
@joubbi would you please take a stab at the documentation update?
