### ISSUE TITLE
Filter view for Locations is missing tags field

### ISSUE THREAD

**Issue by dankotrajkovic** [netbox-community/netbox#8357]
### NetBox version

v3.1.5

### Python version

3.8

### Steps to Reproduce

Navigate to Organization -> Locations.
e.g https://demo.netbox.dev/dcim/locations/
and then open the filters tab.

### Expected Behavior

Under the first search field there should be a field for tags to compliment the Location model which was extended to include a tag field.

### Observed Behavior

Other then the missing GUI field for tags, the filtering is working as expected in the background.
Verified by trying https://demo.netbox.dev/dcim/locations/?tag=my-tag

**Comment by jeremystretch** [comment]
@jasonyates could you comment here so I can assign the issue to you (sine you already have a PR in)?

**Comment by jasonyates** [comment]
Submitted PR for this. Reviewed the other filter forms too and confirmed they all have the tags field available.
