### ISSUE TITLE
Inconsistent styling of custom fields in filter & bulk edit forms

### ISSUE THREAD

**Issue by jeremystretch** [netbox-community/netbox#8358]
### NetBox version

v3.1.5

### Python version

3.7

### Steps to Reproduce

1. Add a custom field for sites (or any model)
2. View the sites list and click the "filters" tab

### Expected Behavior

The custom field should appear at the bottom of the filters form with the same styling as the other fields.

### Observed Behavior

The custom field appears, but is not styled consistently.
![Screenshot 2022-01-14 at 08-35-36 Tenants NetBox](https://user-images.githubusercontent.com/13487278/149523778-0a7e2510-f616-482a-9e36-2a89514ea8c3.png)

**Comment by ryanmerolle** [comment]
wow nice catch... that's a subtle detail I would likely have never caught.

**Comment by jeremystretch** [comment]
I can't take credit for this actually; Danko Trajkovic on the NetDev Slack spotted it. I believe it was due to some recent refactoring of the base form classes.
