### ISSUE TITLE
Filtering for child devices by parent device

### ISSUE THREAD

**Issue by Alestor** [netbox-community/netbox#8365]
### NetBox version

v3.1.5

### Feature type

Change to existing functionality

### Proposed functionality

I think a query option to identify all child devices of a parent device would be a good enhancement. For example to find all blade server associated with an enclosure or all network modules of a networking device. From the Web UI it's currently ok to get such overview by selecting a parent device and look on the device-bay tab for the child devices.
To get such overview from the REST API is currently more tricky. First you have to identify the device id of the parent device. Next it's necessary to get all devices which may be associated with the parent device and filter the JSON for results[].parent_device.id .

### Use case

Being able to query child devices by parent_device_id on the API call, would make some automation tasks more easy to realize. In addition it should slightly reduce the load on the app server, since it's no more necessary to make queries with large result sets.

### Database changes

None that I'm aware of.

### External dependencies

None

**Comment by stephanblanke** [comment]
I can try to implement this

**Comment by jeremystretch** [comment]
@stephanblanke are you still interested in working on this?
