### ISSUE TITLE
Search interfaces in hierarchical structured locations fails

### ISSUE THREAD

**Issue by baschdello** [netbox-community/netbox#8370]
### NetBox version

v3.1.5

### Python version

3.9

### Steps to Reproduce

Create a hierarchical location set like:
block2
    | --- rackrow3
    | --- rackrow4

Create some racks and assign them to location "row3" and "row4".

Add some devices with interfaces in those racks.

After that use the interface search from menu "Devices => Interfaces" and choose filteroption location: "block2"

### Expected Behavior

Interfaces from devices out of parent location "block2" should be listed.

### Observed Behavior

None of device interfaces are listed.

------
Note: this problem is only observed at interface search. If using the device search under menu "Devices => Devices" and choose the parent location "block2" as filteroption like above all devices are listed.

**Comment by jeremystretch** [comment]
Just like the region, site group, and site fields, the location field is there only to filter the list of available devices. It does not filter interfaces directly.

If you'd like to propose enabling a location filter for interfaces, please open a [feature request](https://github.com/netbox-community/netbox/issues/new?assignees=&labels=type%3A+feature&template=feature_request.yaml) citing your use case.
