### ISSUE TITLE
Device display name not showing asset number when name is blank

### ISSUE THREAD

**Issue by duckw** [netbox-community/netbox#8374]
### NetBox version

v3.1.5

### Python version

3.8

### Steps to Reproduce

1. Create a device with no name but with an asset tag.

### Expected Behavior

Display name for the device should be "manufacturer device_type (asset tag)" since asset tag is not null.

### Observed Behavior

Display name for the device shows as "manufacturer device_type (id)".

**Comment by DanSheps** [comment]
There are three possible scenarios here:

1. Display only the Device Type
2. Display the Device Type & the Asset Tag
3. Display the Asset Tag

How do we want to tackle this?

**Comment by bluikko** [comment]
> How do we want to tackle this?

My vote would go to # 1 ("Display the Device Type & the Asset Tag") with perhaps fallback to Serial Number if Asset Tag is also blank.

**Comment by DanSheps** [comment]
Going to knock this out soon.  Will do Device Type & Asset Tag

**Comment by jeremystretch** [comment]
@DanSheps are you still planning to work on this?
