### ISSUE TITLE
Error when creating singular Condition for webhook

### ISSUE THREAD

**Issue by kkthxbye-code** [netbox-community/netbox#8376]
### NetBox version

v.3.1.5

### Python version

3.9

### Steps to Reproduce

1. Click on Other -> Webhooks
2. Add new webhook
3. Enter the following data: name = test, content types = DCIM > Device, URL: http://127.0.0.1/
4. Enter the following condition copied from the documentation:

```
{
  "attr": "name",
  "value": "foo"
}
```
5. Save

### Expected Behavior

Webhook saves

### Observed Behavior

The following error: Ruleset must have exactly one logical operator (found 2)

The following works:

```
{
    "and": [
        {
            "attr": "name",
            "value": "foo"
        }
    ]
}
```

Now looking at the code, I'm not sure if this is a bug or I'm just misunderstanding the documentation. To me the documentation implies that singular conditions are allowed at the root level, and only at the bottom of the page are Condition Sets documented.

If I'm just misunderstanding, is the correct way just to wrap singular conditions in the "and" operator?

Condition documentation: https://netbox.readthedocs.io/en/stable/reference/conditions/

Conditional webhooks documentation: https://netbox.readthedocs.io/en/stable/additional-features/webhooks/#conditional-webhooks

**Comment by jeremystretch** [comment]
IIRC the original intent was to support the simplified expression where only a single AND clause is present, however the implementation to accommodate it proved too unwieldy and was scrapped. The example in the webhook documentation did not get updated to reflect this change.
