### ISSUE TITLE
Missing some object information on Cable Trace View

### ISSUE THREAD

**Issue by mshuttle76** [netbox-community/netbox#8385]
### NetBox version

v3.1.6

### Python version

3.8

### Steps to Reproduce

1 Create a link between two interface.

### Expected Behavior

I see major differences between old version 2.11.12 and version 3.1.6 on cable trace view
With version 2.11.12  you have a lot of information, linked with a URL, about an object like site, location, and rack:

![image](https://user-images.githubusercontent.com/60605051/150094544-8d573713-3103-43f4-a96a-f9ec2b8c25ce.png)

With version 3.1.6 these informations disapperared and you can reach only the main object.
Also type of interface has disappeared

![image](https://user-images.githubusercontent.com/60605051/150095003-d588df55-02db-4d91-aa13-8fe6e3e2a852.png)
I

### Observed Behavior

I dont't know if this is a bug or it's a major difference between 3.1 and 2.11 version.
Thank you,

Davide

**Comment by jeremystretch** [comment]
In v3.0 and later, cable traces are rendered as SVG images. These were intentionally simplified in the interest of readability and portability. You're welcome to propose adding extra information and/or hyperlinks to the trace images, but this will need a [feature request](https://github.com/netbox-community/netbox/issues/new?assignees=&labels=type%3A+feature&template=feature_request.yaml) with a detailed proposal and use case. Thanks!
