### ISSUE TITLE
Circuit Install Date set to NULL exports to csv as â€”

### ISSUE THREAD

**Issue by ryanmerolle** [netbox-community/netbox#8391]
### NetBox version

v3.1.6

### Python version

3.9

### Steps to Reproduce

1. Create a circuit with no Install Date
2. Export circuits to CSV
3. Notice Install Date Field value displayed as `â€”`

### Expected Behavior

Install Date shows as NULL or empty

### Observed Behavior

Install Date shows as `â€”`

**Comment by jeremystretch** [comment]
Weird, I get an emdash symbol (—), which we use as a placehilder in the table. This is still wrong though; it should be null.

**Comment by seulsale** [comment]
HI, I can work on fixing this bug during the weekend.
