### ISSUE TITLE
Quick filter on all visible fields

### ISSUE THREAD

**Issue by PieterL75** [netbox-community/netbox#8394]
### NetBox version

v3.1.6

### Feature type

Change to existing functionality

### Proposed functionality

The 'Quick Filter' of a table currently only filters the first/name column
The filter should apply to all visible fields of the table, including custom added columns

### Use case

More flexible and intuitive filtering of data

### Database changes

None

### External dependencies

None

**Comment by jeremystretch** [comment]
> The 'Quick Filter' of a table currently only filters the first/name column

The quick filter search employs the `?q=` filter for the type of object being filtered. It is not limited to the first column.
