### ISSUE TITLE
Circuit Site not moving when moving device

### ISSUE THREAD

**Issue by Zeawiel** [netbox-community/netbox#8409]
### NetBox version

v3.1.6

### Python version

3.9

### Steps to Reproduce

1. Create site A
2. Create site B
3. Create Device on site A
4. Create Circuit on Site A
5. Connect Terminiation A from circuit to Device 
6. Move Device to Site B

(Tested on demo)

### Expected Behavior

The Circuit should move to Site B with Device

### Observed Behavior

The Circuit is still terminating to Site A, but still connected to the device on Site B.

I don't know if this is a bug, maybe in some case this behavior is expected. What do you think ?
I see this problem because I'm moving from several Sites to one Site with multiple Location.

**Comment by DanSheps** [comment]
The site on the circuit is independant of the device.
