### ISSUE TITLE
Add Neutrik powerCON power ports

### ISSUE THREAD

**Issue by arnogramatke** [netbox-community/netbox#8415]
### NetBox version

v3.1.6

### Feature type

New functionality

### Proposed functionality

Add Neutrik powerCON type connectors to the power port types:

- powerCON TRUE 1 TOP
- powerCON TRUE1
- powerCON 20A
- powerCON 32A
- 
https://www.neutrik.us/en-us/products/power

### Use case

Some of the Luminex GigaCore switches use these types of power connectors.

**Comment by DanSheps** [comment]
Unfortunately, for some reason it isn't letting me select you for assignment @JoeIzzard, not sure why, feel free to proceed with this though.
