### ISSUE TITLE
Change contacts for devices or virtual machines in bulk

### ISSUE THREAD

**Issue by xth0331** [netbox-community/netbox#8419]
### NetBox version

v3.1.6

### Feature type

Data model extension

### Proposed functionality

like bulk modifying tenants.

### Use case

When multiple objects have the same contacts, avoid repeatedly attaching contacts to each object.

### Database changes

N/A

### External dependencies

N/A

**Comment by jeremystretch** [comment]
> like bulk modifying tenants.

Please put some more effort into your proposed implementation.

**Comment by xth0331** [comment]
> > like bulk modifying tenants.
> 
> Please put some more effort into your proposed implementation.

Sorry, I just want to associate contact A with multiple devices. When I select multiple devices at the same time and click "Edit Selected", the Contact cannot be modified, and the netbox api cannot associate the contact with the device or virtual machine.

**Comment by jdavidson2021** [comment]
I had opened a similar discussion on this topic. #8413 
"We have added a few contacts, contact groups, and contact roles, but assigning a contact to a device one at a time in the GUI is not really feasible with 1000s of devices. It would be nice to be able to do a bulk edit on a bunch of existing devices and assign the contact(s). It would also be nice to be able to include the contact(s) details when you do a bulk import of devices."

**Comment by jdavidson2021** [comment]
It could also be useful to include comments/ideas from discussion #8359 about the ability to link a contact group to an object as well as the current contact linkage capability.

**Comment by ITJamie** [comment]
being able to link a contact / contact group to a tenant might be a solution around this.
that way you just have to update the contact assignments to the tenant

**Comment by sincomil** [comment]
[jeremystretch](https://github.com/jeremystretch) it seams that updates in this issue is cleaning 'pending closure' flag. Also I've putted a comment with my thoughts about issue

**Comment by jeremystretch** [comment]
@sincomil the issue is stale and will be closed if someone does not volunteer to own it.
