### ISSUE TITLE
Wrong switching order

### ISSUE THREAD

**Issue by KosenkoIvan** [netbox-community/netbox#8421]
### NetBox version

nexbox (v3.1.5)

### Python version

3.7

### Steps to Reproduce

On the 1st screenshot we see the correct number order 2.3-(1-22)
![1](https://user-images.githubusercontent.com/97949308/150498585-1a961812-6235-4a13-811c-3ec8a7043ea5.png)
But when we go to the rack 2.3-1 and press next
![2](https://user-images.githubusercontent.com/97949308/150498591-ec802959-9bfa-4ecb-b2d9-5498ba619198.png)
we see that the rack number is 2.3-12, although it should be 2.3-2
![3](https://user-images.githubusercontent.com/97949308/150498593-3d79f8ca-d404-427c-859a-e74463719d5a.png)
etc
![4](https://user-images.githubusercontent.com/97949308/150498595-685e4716-e140-406c-94ba-37e3a4190f8a.png)

### Expected Behavior

Must be in the correct nominal order. 
2.3-1
2.3-2
2.3-3
...

### Observed Behavior

2.3-1
2.3-12
2.3-13

**Comment by jeremystretch** [comment]
Thank you for opening a bug report. Unfortunately, the information you have provided is not sufficient for someone else to attempt to reproduce the reported behavior. Remember, each bug report must include detailed steps that someone else can follow on a clean, empty NetBox installation to reproduce the exact problem you're experiencing. These instructions should include the creation of any involved objects, any configuration changes, and complete accounting of the actions being taken. Also be sure that your report does not reference data on the public NetBox demo, as that is subject to change at any time by an outside party and cannot be relied upon for bug reports.

**Comment by jeremystretch** [comment]
Closing as there has been no further response.
