### ISSUE TITLE
Removing a plugin can cause exceptions when viewing change records

### ISSUE THREAD

**Issue by jeremystretch** [netbox-community/netbox#8425]
### NetBox version

v3.1.6

### Python version

3.8

### Steps to Reproduce

1. Install a plugin
2. Create an instance of a model provided by the plugin, resulting in the creation of a changelog entry
3. Uninstall the plugin
4. View the changelog

This has come up a few times in discussion. One recent example can be found in #8418.

### Expected Behavior

The changelog should render successfully.

### Observed Behavior

An exception is raised when the changelog entry relevant to the plugin model is present:

```
<class 'AttributeError'>

'NoneType' object has no attribute '_base_manager'
```

**Comment by jeremystretch** [comment]
@DanSheps have you made any progress on this?

**Comment by DanSheps** [comment]
@jeremystretch I think I captured all locations where this might pop up.
