### ISSUE TITLE
Use MB/GB/TB suffix for VM memory input

### ISSUE THREAD

**Issue by hagbarddenstore** [netbox-community/netbox#8437]
### NetBox version

v3.1.6

### Feature type

Change to existing functionality

### Proposed functionality

Allow inputting memory with a MB/GB/TB suffix instead of defaulting to MB.

### Use case

The use case is to make it easier for users to input the correct amount of memory for the virtual machine.

It is far more common today to input GBs of memory rather than MBs of memory and having to memorize or calculate the correct amount of MBs the wanted GB represent is tedious.

### Database changes

None

### External dependencies

One method of solving it is by changing the form input field to this https://pypi.org/project/django-sizefield/.

**Comment by jeremystretch** [comment]
To clarify, the intent here is to enable the user to enter a value such as "8gb"in the form field and have NetBox automatically convert that to a value of `8192`, correct?

**Comment by hagbarddenstore** [comment]
@jeremystretch Yes exactly, so just a frontend change.

**Comment by jeremystretch** [comment]
Another option would be to keep the integer field and add a separate unit selection dropdown (similar to what we do with circuit speeds). Django's [`MultiValueField`](https://docs.djangoproject.com/en/4.0/ref/forms/fields/#multivaluefield) might be useful for this approach, though I haven't experimented with it myself.

**Comment by hagbarddenstore** [comment]
That works as well.

**Comment by minitriga** [comment]
Managed to get something working without altering the model, the user can select what unit they want to enter the value in and it will convert it on the backend to MB. when you go to edit the form again it will then present you with the value so if you entered 9GB it will show 9216 MB as shown in the picture below. 

![image](https://user-images.githubusercontent.com/26367336/157722551-142b3b5c-7095-40c8-8760-2696319b8048.png)

This implements MultiValueField just got to work on formatting the html properly.

**Comment by juliusrickert** [comment]
@minitriga useful addition :)

I'd like to suggest inlining the `<select>` with the `<input>`.
