### ISSUE TITLE
Show ASNs per RIR

### ISSUE THREAD

**Issue by ryanmerolle** [netbox-community/netbox#8445]
### NetBox version

v3.1.6

### Feature type

New functionality

### Proposed functionality

Currently the page for a RIR record only shows the associated aggregates, and it only has a button to add an aggregate.

With ASNs needing to be associated to a RIR, the RIR object view should be updated accordingly.

### Use case

Enable consistency with regards to object pages in the GUI.

### Database changes

N/A

### External dependencies

N/A

**Comment by PieterL75** [comment]
Maybe an idea to introduce LIRs on to of the RIR?
LIRs own address space and ASN's.

The RIR object has always confused me. There are only 5 RIRs, so why make them dynamic?

Currently I use a RIR rather as a LIR.
A LIR would model the IP world better, because it is the glue between public ASN and the prefixes.

P

**Comment by ryanmerolle** [comment]
That sounds like a feature request to create a way to model LIR membership.  I get your thinking and confusion, but it likely is a low return and high investment feature request.  It can be useful for modeling when there is some reason a company manages multiple LIRs (maybe an MSP with tenants, or a firm that went through some mergers and acquisitions).

This feature request was just to enable some assumed functionality within the NetBox views given this view is in place for most other objects with similar relationship models.

**Comment by DanSheps** [comment]
> LIRs own address space and ASN's.

At least in North America, ASN's are only owned and managed by the RIR.  LIR's do not handle ASNs.  LIR's only handle allocations for sub-delegation.  I don't think this relationship needs a model, as in most cases LIR's could be modelled by a "tenant" on a prefix.

What happens in Europe/Asia/Africa?

**Comment by jeremystretch** [comment]
Whoops, didn't realize @991jo had already submitted a PR for this. Thanks!
