### ISSUE TITLE
Object edit/add GUI does not show some custom fields in a custom field section

### ISSUE THREAD

**Issue by ryanmerolle** [netbox-community/netbox#8446]
### NetBox version

v3.1.6

### Python version

3.9

### Steps to Reproduce

Unlikely most models, there are a few models that do not show custom fields in their own section within the GUI.  Specifically this is referring to the add and edit views for an object. Viewing such an object in in the GUI shows said field in a separate table referenced as Custom Fields.

1.) Create a new custom field for RIR
2.) Edit an existing RIR https://demo.netbox.dev/ipam/rirs/1/edit/
3.) View the existing RIR https://demo.netbox.dev/ipam/rirs/1/

Compared to other objects, RIRs group all custom fields in a section called custom fields in BOTH [the add/edit](https://demo.netbox.dev/tenancy/tenants/1/edit/) and [the view ](https://demo.netbox.dev/tenancy/tenants/1/)object pages.  At least with RIRs, the add/edit object page does not place custom fields in their own section.

### Expected Behavior

I would expect all add/edit forms to behave the same.

### Observed Behavior

At least with RIRs, the add/edit forms do not organize custom fields the same.

**Comment by jeremystretch** [comment]
> there are a few models that do not show custom fields in their own section within the GUI.

This is intentional. For models with very few built-in fields (e.g. RIRs), there was no need to break out custom fields into their own section. You can see in [the template](https://github.com/netbox-community/netbox/blob/develop/netbox/templates/generic/object_edit.html) that only forms with fieldsets explicitly defined are rendered with separate sections.

Happy to leave this open for discussion but I'm going to reclassify it as a feature request.

**Comment by ryanmerolle** [comment]
Totally fair.  I was debating whether it was intentional or not.  I was on a consistency kick.  I am likely overthinking it all.

**Comment by jeremystretch** [comment]
Also: With the move to Django 4.0 in v3.2, we'll have some more flexibility around how forms are rendered. So we should probably take a fresh look at the current approach in general.

**Comment by jeremystretch** [comment]
Reconsidering this, it is probably best to always break out custom fields into their own section to help combat potential confusion.
