### ISSUE TITLE
Journal Entries reference field

### ISSUE THREAD

**Issue by snowie-swe** [netbox-community/netbox#8448]
### NetBox version

v3.1.6

### Feature type

Change to existing functionality

### Proposed functionality

Would like to see Journal entries extended to include a "reference" field.

### Use case

If there is an issue on a VM / Devices that involves a hardware replacement / software hotfix or similar.
It would be very nice to be able to search for a case number / ticket from the vendor "reference"

Same can be used for reference to internal tickets / issues

### Database changes

dont know

### External dependencies

dont know

**Comment by jeremystretch** [comment]
> It would be very nice to be able to search for a case number / ticket from the vendor "reference"

Is this something we should build into core, or would it be more appropriate as a custom field on the JournalEntry model? I'm just considering validation possibilities, but maybe I'm over-thinking it.

**Comment by snowie-swe** [comment]
> > It would be very nice to be able to search for a case number / ticket from the vendor "reference"
> 
> Is this something we should build into core, or would it be more appropriate as a custom field on the JournalEntry model? I'm just considering validation possibilities, but maybe I'm over-thinking it.

In general i believe that extending custom field to more/all modules is a good middle ground.
It allows organizations to add smaller things without requiring additional development from the community.

**Comment by mmfreitas** [comment]
> Is this something we should build into core, or would it be more appropriate as a custom field on the JournalEntry model? I'm just considering validation possibilities, but maybe I'm over-thinking it.

A custom field, custom link and tags could be useful in the JournalEntry model.

I don't think this is what you meant but if journaling were to be built into the core, I would propose having the ability to journal on "create"/"update"/"delete" of anything, and the possibility to journal from the changelog of said event. Keeping this history even if changelog is deleted
