### ISSUE TITLE
Add warning about reserved names for scripts

### ISSUE THREAD

**Issue by hagbarddenstore** [netbox-community/netbox#8452]
### Change Type

Addition

### Area

Functionality/features

### Proposed Changes

The custom scripts documentation should mention that a script can't be named the same as one of the built-in applications since it might clash in quite odd ways.

Example, if you name your script `circuits.py` and work on models in the `circuits` application, whenever you try to save one of those models, you'll get an error `An exception occurred: SerializerNotFound: Could not determine serializer for circuits.Circuit with prefix ''`.

The fix is to rename the script to something other than `circuits.py`.

**Comment by jeremystretch** [comment]
> The custom scripts documentation should mention that a script can't be named the same as one of the built-in applications since it might clash in quite odd ways.

This is nothing unique to NetBox: Such is the case with _any_ Python module. (For example, you also cannot name your script `django`.) I appreciate the suggestions, however keeping our documentation limited in scope is crucial to their long-term maintainability, so I'm going to decline.
