### ISSUE TITLE
"Add device" button on location, site views

### ISSUE THREAD

**Issue by PaulR282** [netbox-community/netbox#8457]
### NetBox version

v3.1.6

### Feature type

New functionality

### Proposed functionality

It would be nice to be able to create a device in a location without assigning it to a rack. 

### Use case

If you have a device in a room, that is not in a rack, currently, it is not possible to display this in NetBox without creating a fake rack or assigning the device to another rack. 

### Database changes

Right now, if you create a non-rack device, the `position` and `face` attributes of the device are set to `null`. Since the location is stored in the device, the `rack` attribute could be set to null to assign it to a location without assigning it to a rack.

**Comment by mmfreitas** [comment]
I have just tested this on the demo. You can create a device, fill the site fiels, assign it to a location (the room you want) and not fill the rack field.
When you look for your device it will show the location but without a rack.

Isn't this what you want?

**Comment by PaulR282** [comment]
I just tested it as you described it and it works, didn´t know that, thanks! I didn´t think this would work since there is nothing like a `Create non-rack device` button in the location. 

Now it would be nice to have a button to directly create a device in the location without needing to create it over the dcim/devices site and an extra `Non-Racked Devices` panel like in the rack view.

**Comment by jeremystretch** [comment]
@PaulR282 I'm not sure I follow what you're suggesting; can you elaborate please?

**Comment by PaulR282** [comment]
Sure, since you can create devices, that are not assigned to racks, it would be nice to have something like a `Create non-rack device` button in the location view, like there is in the rack view. 
The same for the `Non-Rack Devices` panel, which is shown on the rack page, that shows all devices, that are assigned to the rack but have no position in the rack. I would appreciate the same panel in the location view to show all devices in the location, that are not assigned to a rack.

**Comment by jeremystretch** [comment]
Oh, I see, thanks! I think if we do this, we might want to add a similar button to the site view as well for consistency.

**Comment by PaulR282** [comment]
Yes, that would be great!
