### ISSUE TITLE
Request for interface type 100base-x SFP

### ISSUE THREAD

**Issue by Pakkec** [netbox-community/netbox#8464]
### NetBox version

3.1.6

### Feature type

Change to existing functionality

### Proposed functionality

Hi, would it be possible to add the 100base-x-sfp Fastethernet interface type into netbox/dcim/choices.py ?

Code example:

class InterfaceTypeChoices(ChoiceSet):
    # Ethernet
    TYPE_100FE_SFP = '100base-x-sfp'

 CHOICES = (
            'Ethernet (modular)',
            (
                (TYPE_100FE_SFP, 'SFP (100FE)'),
            )

### Use case

These are used quite a lot in FTTx environments for example.

### Database changes

Probably not.

### External dependencies

None.

**Comment by DanSheps** [comment]
Thank you for submitting your idea. Unfortunately, the proposed feature falls outside the scope of functionality that NetBox aims to provide. As NetBox is an open source application with limited development resources and a persistent backlog of existing work, it is crucial that we limit the scope of development to ensure it remains a maintainable project for many years to come. Thank you for your understanding.

More information:

We don't add SFP's, we add the SFP interface (SFP, SFP+, QSFP, etc).

**Comment by apellini** [comment]
Sorry. But currently on Netbox we could insert only Base T fixed interface, but there is the possibility to have an SFP based interface. Also this one is not a big change on the code and it could be helpful to maintain clear the data.

**Comment by DanSheps** [comment]
You should choose SFP (1G) as the SFP is a 1G SFP, the pluggable you are inserting is 100m.

In 3.2, there will be a configurable speed/duplex option.

**Comment by apellini** [comment]
But 1G base X interface (SFP) haven't autonegotiation and also 1G Base X (SX, LX) are fixed to 1G.

**Comment by apellini** [comment]
I add this for reference:

https://www.cisco.com/c/en/us/products/collateral/interfaces-modules/gigabit-ethernet-gbic-sfp-modules/datasheet-c78-366584.html

https://www.juniper.net/documentation/en_US/release-independent/junos/topics/reference/specifications/transceiver-m-mx-t-series-1000base-optical-specifications.pdf (only 1G is autosense)

**Comment by DanSheps** [comment]
Yes, but we aren't tracking SFPs, we are tracking physical interfaces.

**Comment by Pakkec** [comment]
Thank you for the input! Now I understand much better the scope of Netbox and more specific the physical interface approach. The usage of a "100Mbit/s SPF" physical interface does appear but mostly in legacy equipment. 
Thanks for a great product anyway. Its very useful :-)
