### ISSUE TITLE
Add Status to Cluster

### ISSUE THREAD

**Issue by hagbarddenstore** [netbox-community/netbox#8471]
### NetBox version

v3.1.6

### Feature type

New functionality

### Proposed functionality

Just like VirtualMachine, Device and others have a Status field, it would be nice to also add this to Clusters.

I'm proposing the following values:
* Active
* Offline
* Planned
* Staged
* Decommissioning

### Use case

Right now there's no nice way to letting a user know which stage in the lifecycle a Cluster is in.

So, it needs to be manually communicated that a Cluster is not ready for production yet or to be taken out of production, thus making it unsuitable for adding new VirtualMachines to.

### Database changes

Add field `status` to the `virtualization.cluster` model.

### External dependencies

None

**Comment by jeremystretch** [comment]
I was going to ask if this could potentially conflict with the statuses of assigned VMs (where an "active" VM could be assigned to an "offline" cluster), but of course the same scenario exists for devices and sites, and it hasn't been an issue AFAICT.
