### ISSUE TITLE
Add a note to the git hook section that the Web UI dependencies/tooling needs to be set up for the hooks to work.

### ISSUE THREAD

**Issue by 991jo** [netbox-community/netbox#8480]
### Change Type

Addition

### Area

Administration/development

### Proposed Changes

The git pre-commit hooks require the web UI dependencies (yarn, node, typescript) to be set up to work.
It is very frustrating to enable the hooks and have your commit hooks failing because of missing dependencies.
Since the pre-commit hooks are encouraged it would be nice to tell people that the additional tooling described in the Web UI section is also required to run those.

A short note like 

> Install yarn, node, typescript, run `yarn` and `yarn bundle` in `netbox/project-static` to make the UI tooling work
> For more details take a look at the Web UI section.

reduces the amount of time a first time contributor needs to spend debugging the build environment.
Also keep in mind that many people that are just fixing a small bug might not be Frontend-Devs and are not very familiar with all the tooling and how it works. (I include myself in this group.)

**Comment by jeremystretch** [comment]
Looks like this was taken care of under #10139.
