### ISSUE TITLE
Regular expressions no longer work in the 'Quick search' bar

### ISSUE THREAD

**Issue by Mizarv** [netbox-community/netbox#8481]
### NetBox version

3.1.5

### Python version

3.7

### Steps to Reproduce

1. Open https://demo.netbox.dev/dcim/devices/
2. Enter 'PP:B117|PP:B118' into the Quick search bar

### Expected Behavior

Devices PP:B117 and PP:B118 should be displayed

### Observed Behavior

No devices are displayed

**Comment by kkthxbye-code** [comment]
I have seen others mention this before. The quick search bar changed in 3.1.2 in the following PR https://github.com/netbox-community/netbox/pull/8073

The old quick search searched in only the loaded page, but it searched in all fields, with partial matches and regex support. The new way uses the q filter of the object that is being searched to look up all possible matches in the database. In most cases this searches a few fields with no support for partial matches (not sure if this is the case for all objects).

Obviously the old way was broken from a usability standpoint (only searching in the loaded page), sometimes making users increase their pagination setting, causing slow page loads. I could support a feature request for making the quick search better, but it would probably be blocked by the following feature request: https://github.com/netbox-community/netbox/issues/7016

**Comment by jeremystretch** [comment]
#7604 may also be relevant
