### ISSUE TITLE
Add a "Copy to clipboard" button for IP addresses in the Device/id/interfaces

### ISSUE THREAD

**Issue by arthurzinck** [netbox-community/netbox#8483]
### NetBox version

(v3.1.7-dev)

### Feature type

New functionality

### Proposed functionality

I would like to add to netbox a functionnality that is very simple.

It would be the possibility for one to copy the IP address and netmask in cidr notation of a device by clicking on a button.

Intead of highlighting the IP Adress and catching spaces/tab on a dash, which can be frustrating.

![Screenshot from 2022-01-28 14-35-08](https://user-images.githubusercontent.com/43119213/151555928-1f48c278-f46f-49bf-82da-646df0b71cd7.png)

### Use case

This would address a frustrating experience when trying to copy the ip of an interface and copying blank space and the IP

### Database changes

None :+1: 

### External dependencies

Clipboard.js already in the yarn bundle :+1:

**Comment by vin-6** [comment]
This feature could also be added to the server names :rocket:

**Comment by jeremystretch** [comment]
It could probably be added in a _lot_ of places. I think if we're to do this, it's probably best implemented as a template filter that injects the necessary code around a bit of text. IMO, ideally the "copy to clipboard" button should only appear when hovering over the relevant text, to avoid clutter.

**Comment by PieterL75** [comment]
I could add it to the javascript based context menu plugin.

**Comment by Abulhallaj** [comment]
It's also is a good idea to add a button for telnet client to target IP Address

**Comment by PieterL75** [comment]
Abulhallaj, you can edit the nbcm.js in your local netbox depliyment and add items as you like.
