### ISSUE TITLE
Enable journaling for organizational models (e.g. locations)

### ISSUE THREAD

**Issue by ChrisdAutume** [netbox-community/netbox#8485]
### NetBox version

v3.1.6

### Feature type

Data model extension

### Proposed functionality

Add Journal to Location

### Use case

Add Journaling function to Location. For tracking information in a large site that may have a lot of location.

**Comment by jeremystretch** [comment]
We discussed this during today's maintainers meeting and decided to enable journaling support for _all_ organizational models in the interest of consistency.
