### ISSUE TITLE
update social-core-auth dependency version

### ISSUE THREAD

**Issue by oasys** [netbox-community/netbox#8486]
### NetBox version

v3.1.6

### Feature type

Change to existing functionality

### Proposed functionality

Bump social-auth-core dependency in `requirements.txt` to `4.2.0`.

### Use case

Use Okta SSO with Netbox.   A regression in social_auth that prevented this from working is now fixed in python-social-auth/social-core#588 and included in version 4.2.0.

### Database changes

none

### External dependencies

Update requirements.txt:

```diff
-social-auth-core==4.1.0
+social-auth-core==4.2.0
```

**Comment by oasys** [comment]
For reference, here's the error I was receiving 


For reference, here's the symptom I was seeing:

After successful authentication, netbox redirects to `https://<okta custom url>/oauth2/.well-known/openid-configuration?client_id=xxxxxxx` which is a 404.  If I manually go to `/.well-known/openid-configuration?client_id=xxxxxxxx` (without the /oauth2/) in my browser, I see the correct json data.

If you want, assign to me, and I'll submit the (one-line) PR.

**Comment by jeremystretch** [comment]
This will be bumped in the v3.1.6 release.

**Comment by davekempe** [comment]
@jeremystretch do you mean in 3.1.7?
