### ISSUE TITLE
Add poe_enabled check box to dcim.interface

### ISSUE THREAD

**Issue by davama** [netbox-community/netbox#8487]
### NetBox version

v3.1.6

### Feature type

Data model extension

### Proposed functionality

Similar to `enabled` which defines the state of the interface, I wish to add a new checkbox to show if poe is enabled/disabled on X interface. 

### Use case

How will it benefit?
It will provide more data to the user on the state of their network.
What need does it address?
Currently there is no location where one can store the POE state of an interface, so this would add that. 

![poe_enabled](https://i.imgur.com/XHAVwE7.png)

### Database changes

```
ALTER TABLE dcim_interface ADD COLUMN "poe_enabled" BOOLEAN NOT NULL DEFAULT FALSE ;
commit
```

### External dependencies

None

**Comment by davama** [comment]
Please let me know if i missed anything on this request.
Thank you for the awesome support!

**Comment by jeremystretch** [comment]
Anything regarding PoE should be covered under FR #1099 (currently planned for v3.3). I want to avoid adding anything ahead of the "full" implementation so as not to constrain ourselves with its design unnecessarily. Thanks for the FR though!

**Comment by davama** [comment]
Didnt know that FR one existed
Looks more complete.
Looking forward to it!
