### ISSUE TITLE
Be able to group Custom Fields

### ISSUE THREAD

**Issue by hagbarddenstore** [netbox-community/netbox#8495]
### NetBox version

v3.1.6

### Feature type

New functionality

### Proposed functionality

Add a label/group field to a custom field and render a box with all the grouped fields within that box.

The template which renders the custom fields should group all fields with a group set and render a new box with the fields in.

<img width="811" alt="Screenshot 2022-01-29 at 20 07 25" src="https://user-images.githubusercontent.com/1156831/151674214-8bc30463-9155-46b2-a39c-887781a63304.png">

### Use case

To help the user find the information they are looking for.

It makes it easier to sift through lots of fields if they are grouped, because then you only need to focus on finding the right group before diving into each field.

### Database changes

Add a group or label field to the custom field model.

**Comment by hagbarddenstore** [comment]
Issue #4499 suggests the same thing, but was closed with a reference to the FAQ. I can't find the relevant information in the FAQ anymore.

**Comment by snowie-swe** [comment]
Suggesting to add some sort of "custom section"  that the custom fields are added in to.
This would allow for greater customization and decrease the number of request of changes to netbox core modules.

**Comment by jeremystretch** [comment]
Is the proposal here to mimic the `group_name` on CustomLink, which is just an (optional) text field? I think that'd be reasonable.

**Comment by hagbarddenstore** [comment]
Yes that would be sufficient on the model side.

**Comment by jeremystretch** [comment]
This FR was the focus of today's live coding session! The recording is available [here](https://youtu.be/VQCg6bHqF54) for anyone interested.

**Comment by jeremystretch** [comment]
I ended up just splitting the groups into different tables within the same panels, to avoid user confusion over what is and is not a custom field.
