### ISSUE TITLE
Add tenancy to Provider

### ISSUE THREAD

**Issue by polski-g** [netbox-community/netbox#8501]
### NetBox version

v3.1.6

### Feature type

Data model extension

### Proposed functionality

A new field in the Provider creation/edit pages which allows user to assign a Tenant for the Provider.
A new field in the Provider detail and list pages which lists an assigned Tenant for the Provider. 

### Use case

Imagine company **Foobar Corp** has divisions **Bar** and **Foo**. **Bar** and **Foo** might each have a _separate contract_ with a Provider. Therefore they would each have a separate Account Number to give the support personnel at Provider if there is an outage. As of now, Netbox only allows a single Account Number field for a given Provider, regardless of how many contracts your overall **Foobar Corp** has.

**Comment by jeremystretch** [comment]
> Imagine company Foobar Corp has divisions Bar and Foo. Bar and Foo might each have a separate contract with a Provider. 

But there's still only one provider, irrespective of its relationship with the tenants. I assume your intent here is to duplicate the provider, with each instance assigned a different tenant, but I don't think that makes sense.

As an infrastructure tool, NetBox probably isn't the best place to store contract information. If you really need to, you could add a custom field on the tenant model to track this information.

**Comment by polski-g** [comment]
> But there's still only one provider

I agree, which is weird as to why NetBox is asking for Account Number in the Provider page; the Account Number would be unique per contract that the Provider signed with a company (its a number that the Provider created and assigned to you)

**Comment by jeremystretch** [comment]
The account field is provided for convenience, as most organizations only have one account per provider. If you need to manage separate contracts, that should be done outside of NetBox. It wouldn't make sense to create multiple instances of the same provider.

**Comment by darkpixel** [comment]
We have hundreds of accounts numbers with Comcast.  It depends on the circuit, what region it's in, if it's part of their "hierarchy account" structure, etc...

**Comment by DanSheps** [comment]
I think what you need is an "provider account" model, which I don't see adding to core but could be trivial to add as a plugin.  You would use this model to tie both provider and circuits together.

**Comment by jeremystretch** [comment]
I'm going to close this in favor of #9047, which proposes a new Account model that can be used for this purpose.
