### ISSUE TITLE
Group assigned VLAN cannot be assigned individually 

### ISSUE THREAD

**Issue by D1StrX** [netbox-community/netbox#8507]
### NetBox version

v.3.1.6

### Python version

3.8

### Steps to Reproduce

1. Create a VLAN and a VLAN group
2. Assign the VLAN to the VLAN group
3. Try to assign the VLAN individually as tagged or untagged VLAN
You'll see that it won't list the VLAN. It does when it is not used within a VLAN group.

![image](https://user-images.githubusercontent.com/40062371/152005325-c6a12f61-20a8-4b3f-bc65-4b4743aa647a.png)

### Expected Behavior

VLAN both be usable within a group and individually. Not all ports will use the same VLAN(s) every time.

### Observed Behavior

802.1Q Switching won't list grouped VLANs. It does when it is not used within a VLAN group.

**Comment by jeremystretch** [comment]
Thank you for opening a bug report. Unfortunately, the information you have provided is not sufficient for someone else to attempt to reproduce the reported behavior. Remember, each bug report must include detailed steps that someone else can follow on a clean, empty NetBox installation to reproduce the exact problem you're experiencing. These instructions should include the creation of any involved objects, any configuration changes, and complete accounting of the actions being taken. Also be sure that your report does not reference data on the public NetBox demo, as that is subject to change at any time by an outside party and cannot be relied upon for bug reports.

**Comment by D1StrX** [comment]
Issue was that the scope type in "the" vlan group was set to a specific specification. 
![Screenshot_20220202-002546.jpg](https://user-images.githubusercontent.com/40062371/152068942-8976058c-3164-4895-bca7-2a45509173e5.jpg)

Closing this issue.
