### ISSUE TITLE
Enable Custom Fields on Circuit Terminations

### ISSUE THREAD

**Issue by ryanmerolle** [netbox-community/netbox#8511]
### NetBox version

v3.1.6

### Feature type

Change to existing functionality

### Proposed functionality

It may be useful to associate various custom fields to a circuit termination.  You cannot do this currently.

### Use case

Let's say you document cross-connect monthly charges, term length, and install fees.  Right now you would have to associate that to the circuit because circuit terminations do not allow custom fields.  The challenge is that if you have a point to point, you would then associate said custom fields to the related circuit, which is not truly correct.

**Comment by tyler-8** [comment]
I can think of several use cases that would be helped by having Custom Object Fields tied to Circuit Terminations - not to mention the "regular" custom fields.

**Comment by proudbro** [comment]
Very necessary functionality! We are really looking forward to it.
Especially now, when these issues ([1](https://github.com/netbox-community/netbox/issues/9172), [2](https://github.com/netbox-community/netbox/issues/9173))were rejected, it is able to be the only way for modelling interconnections between racks by using related custom fields.

**Comment by jeremystretch** [comment]
> it is able to be the only way for modelling interconnections between racks by using related custom fields.

I describe an approach in my comment on #9172 that would work very well without relying on custom fields.

**Comment by jeremystretch** [comment]
I'm going to add support for tags as part of this work as well.
