### ISSUE TITLE
Housekeeping script file mode is too restrictive

### ISSUE THREAD

**Issue by abrahamvegh** [netbox-community/netbox#8512]
### NetBox version

3.1.6

### Python version

3.9

### Steps to Reproduce

The mode (UNIX permissions) of the housekeeping script included with NetBox is `644`. On Debian (I am running NetBox on Debian 11 'bullseye'), this mode is too restrictive, and `run-parts` does not run the housekeeping script.

### Expected Behavior

The mode of the file included should enable the script to be run automatically, without needing to modify it.

### Observed Behavior

In my installation, if I change the mode to `755`, `run-parts` will execute it. I am currently manually doing this every time I update NetBox.

**Comment by jeremystretch** [comment]
Thanks for taking the time to submit a bug report for this, which incidentally was more effort than the fix. :slightly_smiling_face:

**Comment by abrahamvegh** [comment]
Thanks for I think the fastest resolution + fix I’ve ever seen on a major project issue, although it was admittedly quite a simple fix. 😅
