### ISSUE TITLE
Change the way Role badge is presented for visibility

### ISSUE THREAD

**Issue by ziggekatten** [netbox-community/netbox#8528]
### NetBox version

v3.1.6

### Feature type

Change to existing functionality

### Proposed functionality

Currently the way Role badge is presented in the UI makes it very hard to read, especially on high res monitors since the combined colors melt into each other. I propose that visualization is done in the same way as tags.

This is how it looks today:
![image](https://user-images.githubusercontent.com/55629049/152298800-a7976f89-0b88-4626-b8c9-93180f204bfc.png)
Comparegd to Tags, that are MUCH more readable:
![image](https://user-images.githubusercontent.com/55629049/152298912-3d1153e1-038f-4825-80a5-c52135c8e04e.png)

### Use case

When using monitors with higher resolution, it's nearly impossible to read the test in the role badge without zooming the browser.

### Database changes

Probably not a DB change, rather template/CSS

**Comment by jeremystretch** [comment]
This appears to have been fixed at some point, as the role labels all render with black or white text.
