### ISSUE TITLE
Custom Fields (space between words)

### ISSUE THREAD

**Issue by KosenkoIvan** [netbox-community/netbox#8529]
### NetBox version

nexbox (v3.1.5)

### Python version

3.7

### Steps to Reproduce

1.Other.
2.Add a new custom field.
3.Use a space in the name field
4.Create.
![3](https://user-images.githubusercontent.com/97949308/152314596-2e91f95d-c86f-4bbe-8ee5-1ba730afab26.PNG)
5. Name
Only alphanumeric characters and underscores are allowed.

### Expected Behavior

The fields created earlier supported a space, but now it cannot be added.
![2](https://user-images.githubusercontent.com/97949308/152315204-77546ca8-ff72-4959-9535-ed1e7396dec3.PNG)

### Observed Behavior

5. Name
Only alphanumeric characters and underscores are allowed.
![3](https://user-images.githubusercontent.com/97949308/152314945-4c5c4ff0-f8cf-416e-b227-d7d48737dac3.PNG)

**Comment by jeremystretch** [comment]
This is intentional behavior; please see #8030. Using a space in the field name makes it impossible to reference e.g. from within a custom script. Instead, use only underscores as directed and set a separate human-friendly label (which may contain spaces).
