### ISSUE TITLE
DeviceType Export no longer supports YAML

### ISSUE THREAD

**Issue by jasonyates** [netbox-community/netbox#8530]
### NetBox version

3.1.6

### Python version

3.8

### Steps to Reproduce

1. Navigate to /dcim/device-types/
2. Select device type(s) to export
3. Go to Export 
4. File downloads as CSV, not YAML as per #3801

I have no export templates defined. There appears to be no way to export a device type template as YAML any longer.

### Expected Behavior

Export of a device type is a YAML document as per #3801

### Observed Behavior

CSV file is exported as opposed to a YAML document for each device type.

**Comment by jeremystretch** [comment]
> Select device type(s) to export

FYI the selection boxes are for the bulk edit & delete functions; they don't affect exported data.

> Go to Export

What are you clicking? "Export > Current view" will export the current table view, whereas "Export > All data" will export the device types as a YAML document. I can confirm that this works as expected on v3.1.6.

**Comment by jasonyates** [comment]
I was clicking Export -> Current View.

Confirmed clicking Export -> All Data will export YAML.

Happy to close this if that is the intended behaviour, however is it possible to indicate the difference perhaps with (CSV) (YAML) at the end of each option to make the differences clearer.

**Comment by jeremystretch** [comment]
Yeah I think that's reasonable. I'm going to reclassify this as a FR and add a CSV/YAML label as appropriate.
