### ISSUE TITLE
Visibility switcher for device image

### ISSUE THREAD

**Issue by KosenkoIvan** [netbox-community/netbox#8531]
### NetBox version

nexbox (v3.1.5)

### Feature type

New functionality

### Proposed functionality

Vsibility switcher for device image.
![7](https://user-images.githubusercontent.com/97949308/152318246-19672501-526f-4c7a-8c82-386fc34f2627.png)

### Use case

It is necessary that the user decides for himself whether he needs to display the image in the rack or not. On the example of the Juniper device type, we see its image, but it is not needed in the rack. The visibility switch would solve this in 1 click.
![4](https://user-images.githubusercontent.com/97949308/152318294-03c91eea-2dd0-4e45-9a1e-0bcade1c12ab.PNG)
![5](https://user-images.githubusercontent.com/97949308/152318296-563d2bc0-1ca3-405f-b3f4-a1871b2e2120.PNG)
![6](https://user-images.githubusercontent.com/97949308/152318299-bd0ce13d-4cdb-407a-8885-cf6a656b9002.PNG)

**Comment by jeremystretch** [comment]
Thank you for your interest in extending NetBox. Unfortunately, the information you have provided does not constitute an actionable feature request. Per our [contributing guide](https://github.com/netbox-community/netbox/blob/develop/CONTRIBUTING.md), a feature request must include a thorough description of the proposed functionality, including any database changes, new views or API endpoints, and so on. It must also include a detailed use case justifying its implementation. If you would like to elaborate on your proposal, please modify your post above. If sufficient detail is not added, this issue will be closed.

**Comment by jeremystretch** [comment]
Closing this as no further information has been provided. And if the intent is to not display an image, just don't upload an image for the device type.
