### ISSUE TITLE
Different types of ports are connected

### ISSUE THREAD

**Issue by KosenkoIvan** [netbox-community/netbox#8532]
### NetBox version

nexbox (v3.1.5)

### Python version

3.7

### Steps to Reproduce

When we add switching, we can connect ports of different types, since it selects only by name.
![8](https://user-images.githubusercontent.com/97949308/152321232-c6bf0547-c347-4566-875b-ff9377ffd545.PNG)
![9](https://user-images.githubusercontent.com/97949308/152321236-c7e0cfd7-f487-48b3-a9dc-543af3e0f88f.PNG)

### Expected Behavior

Ports of different types should not be connected.

### Observed Behavior

Connected 1G and 40G ports

**Comment by jeremystretch** [comment]
NetBox does not claim to validate whether two types of connected interfaces will function, and the effort required to compile a set of rules dictating which interface types can interoperate would likely be disproportionate to the value it provides. Still, if you'd like to propose a _specific implementation_ for such a feature, you're welcome to submit a [feature request](https://github.com/netbox-community/netbox/issues/new?assignees=&labels=type%3A+feature&template=feature_request.yaml).
