### ISSUE TITLE
New interface type

### ISSUE THREAD

**Issue by KosenkoIvan** [netbox-community/netbox#8537]
### NetBox version

nexbox (v3.1.5)

### Feature type

Data model extension

### Proposed functionality

New interface type.A new type of multicore cable is needed.

### Use case

For example, we use a 100G port as 4x25G and for this we allocate separate ports, although it is physically one.
![1](https://user-images.githubusercontent.com/97949308/152342637-9fd075ac-1fe1-4afb-8e6f-f524031af71f.PNG)
![image_2022-02-03_14-35-10](https://user-images.githubusercontent.com/97949308/152343931-8ae37baf-6036-47fc-b149-a72500b75ceb.png)

**Comment by jeremystretch** [comment]
Please see [this article in our wiki](https://github.com/netbox-community/netbox/wiki/Data-Model-Limitations#breakout-cables) for guidance on modeling breakout cables.
