### ISSUE TITLE
Virtual Chassis position zero not shown in device page

### ISSUE THREAD

**Issue by tijshuisman** [netbox-community/netbox#8548]
### NetBox version

3.0.11

### Python version

3.8

### Steps to Reproduce

1. Create a device called vc_test_switch (device role, device type, site and status can be anything) 
2. Create a virtual chassis called vc_test, selecting the vc_test_switch as a member, and set the initial position to 0
3. Open the device page for vc_test_switch

### Expected Behavior

The Virtual Chassis section in the device page should list vc_test_switch as a member with position 0

### Observed Behavior

The Virtual Chassis section in the device page lists the device, but shows the position as empty

**Comment by tijshuisman** [comment]
I can submit a PR for this

**Comment by PieterL75** [comment]
I also reported this some time ago https://github.com/netbox-community/netbox/issues/7564
and it was fixed by Jeremy on the VC device page.
Looks like a template was missed there. Good catch !
