### ISSUE TITLE
Enhance delete message

### ISSUE THREAD

**Issue by PieterL75** [netbox-community/netbox#8551]
### NetBox version

v3.1.6

### Feature type

Change to existing functionality

### Proposed functionality

The message showing when deleting something, is pretty simple :
![image](https://user-images.githubusercontent.com/74899468/152535101-28b1c2c0-1e15-48ec-b3de-28743fd85304.png)

It would benefit to make this message more detailed and include what is being deleted.
If the deletion includes other objects to be deleted, then that should be included (like an IP is deleted when a device is deleted; interfaces are deleted when a devicemodule is deleted)

### Use case

Adding more details will prevent accidental deletions

### Database changes

None

**Comment by jeremystretch** [comment]
> Adding more details will prevent accidental deletion of cables

What makes cables different from any other object in this respect?

**Comment by PieterL75** [comment]
Maybe increasing the scope to all delete messages ?
We do have quite some 'accidental' deletes, because the messages are pretty simple.

I catched the toughest ones by removing the delete rights (devices, prefixes, vlangroups, ...)
But I guess everyone would benefit from being able to review what they will delete in a glance.
Also the inherited deletions (Like IP addresses when deleting a device) would be very nice too see

**Comment by PieterL75** [comment]
I changed the scope of the FR to all delete messages rather then only the 'cable' delete message
