### ISSUE TITLE
Provider network, ASN, and contact options missins from global search selector

### ISSUE THREAD

**Issue by zmaster7** [netbox-community/netbox#8553]
### NetBox version

v3.1.7

### Python version

3.8

### Steps to Reproduce

Issue 1:
1. Click on filter selections for global search
2. Look for "Contacts" in the list

Issue 2:
1. ~Search for a name in global search~
2. ~View the "assignments" column~

### Expected Behavior

Issue 1:
"Contacts" should be a selectable option, akin to to all the other searchable models

~Issue 2:~
~Number of assignments should be shown~

### Observed Behavior

Issue 1:
"Contacts" are not listed as a selectable option, although searching for a contact still works (which may or may not include various other results)

![Filter List](https://user-images.githubusercontent.com/46574676/152545484-b92d35da-53f3-4989-93de-674e2d3e9b1f.png)

~Issue 2:~
~Instead of the number of assignments being shown, a hyphen is displayed instead.~

**Comment by jeremystretch** [comment]
> Issue 2:
> Number of assignments should be shown

Please open a separate bug report for this.

**Comment by zmaster7** [comment]
> > Issue 2:
> > Number of assignments should be shown
> 
> Please open a separate bug report for this.

I've created Issue #8577 for this request. Thank you!
