### ISSUE TITLE
Display friendly username in ChangeLog

### ISSUE THREAD

**Issue by mathieu-mp** [netbox-community/netbox#8556]
### NetBox version

v3.1.7

### Feature type

Change to existing functionality

### Proposed functionality

Display friendly user name besides of its raw username, in Change Logs.

In ChangeLog tables, "username - 2020-06-23 14:41" would become "First Last (@username) - 2020-06-23 14:41"

### Use case

We usually need to easily identify which real person is behind a username, to discuss a change with a team-mate or to solve an issue. In corporate Active Directory environment, we sometimes end up with dumb usernames, by chance this comes with the person real name. To display this person real name alongside with its raw username in ChangeLogs would ease this identification.

### Database changes

None

### External dependencies

None

**Comment by mathieu-mp** [comment]
I like what you suggest @jeremystretch , and it sounds way better than what I implemented.

From the GUI at "Other > Change Log", I reconfigured the columns, but it doesn't seem to alter the changelog table as shown in the homepage. Can this be changed ?

Other question: Can we pre-configure tables for all users ?

**Comment by jeremystretch** [comment]
> From the GUI at "Other > Change Log", I reconfigured the columns, but it doesn't seem to alter the changelog table as shown in the homepage. Can this be changed ?

Yep, that's a bug; I've opened #8578 for that. (The dedicated change log view will render the table correctly but the home view does not.) Thanks for the catch!

> Other question: Can we pre-configure tables for all users ?

This will be supported in NetBox v3.2 under FR #7759: Defining a `DEFAULT_USER_PREFERENCES` parameter will allow administrators to define the default columns and ordering for individual tables.
