### ISSUE TITLE
API user impersonation

### ISSUE THREAD

**Issue by steffenschumacher** [netbox-community/netbox#8569]
### NetBox version

v3.1.5

### Feature type

Change to existing functionality

### Proposed functionality

Allow user impersonation for api requests.
Using an http header attribute, eg. “impersonate”=“some-user” along with the api token, and if the user owning the api token is authorized to impersonate users, then the request is authenticated as “some-user” if this user exists.
Furthermore, if an http attribute “impersonate_authorization” is “false”, then the privileges of this request will be those of the api token owner instead of the impersonated user.

### Use case

We have a front end system is issuing requests to netbox for users in a assisted fashion, and we would like the front end to do write operations on behalf of users we don’t want to grant write access to netbox for.

### Database changes

None I think?

### External dependencies

None?

**Comment by jeremystretch** [comment]
User identity is inferred from the token being used, so it wouldn't make sense to override this. Rather, you can just use a token belonging to the desired user. Your front end can leverage [automatic token provisioning](https://netbox.readthedocs.io/en/stable/rest-api/authentication/#initial-token-provisioning) for any users that cannot supply their own API token.

**Comment by steffenschumacher** [comment]
Ok, so when it’s acceptable to grant users the same privileges in netbox as in the front end system, then I agree with our outlined solution.
I guess I weren’t too clear, and I’ll also admit that it’s absolutely a corner case, but I’d like to:
 - allow users to do write operations via the front end system, since it controls how it’s done. 
 - I don’t want them changing stuff directly in netbox, 
 - yet I want their id in the change logs in netbox of the objects change via the front end system
 
 The issue with using tokens of the netbox users, would be that the privileges of the users *in* netbox would need to include write access, which I don’t want them to have..

so is this out of the question, or should I refactor/trim the issue to my specific use case?
