### ISSUE TITLE
Allow Custom Links with the same name for different ContentType

### ISSUE THREAD

**Issue by PieterL75** [netbox-community/netbox#8574]
### NetBox version

v3.1.6

### Feature type

Change to existing functionality

### Proposed functionality

A Custom Link requires the name of the link to be unique.
A CustomLink can only be linked to one ContentType (Device/VM/...)

This means that if you want to provide the same Custom Link to different content types, that the name has to be different.

I would like to be able to create custom links with the same name for different content types
Or allow one CustomLink to select multiple ContentTypes

### Use case

When creating a customlink to a vCenter, I have to create several instances of the same button. One for a VM, one for a Device and one for a Cluster.
In the current implementation, I have to name the button for each different, which can cause confusion.

### Database changes

Change to the unique_key of a custom link
or change of the contenttype to a many-many relation in stead of a one-one

### External dependencies

None

**Comment by jeremystretch** [comment]
This use case seems like it would be addressed by #8274, no?

**Comment by PieterL75** [comment]
Totally ! This one can be closed then.
Sorry for the double FR

Pieter
