### ISSUE TITLE
Device type "All Data" export

### ISSUE THREAD

**Issue by AndMrzv** [netbox-community/netbox#8576]
### NetBox version

v3.0.11

### Feature type

Change to existing functionality

### Proposed functionality

It is more about "observed behavior" rather than "proposed functionality" but classifying this as bug didn't seem quite fitting.
Having export/import for Device Types working the same proper way as it does for any other object would be nice, including multi-record import.

### Use case

For some reason Device Type export/import differs from every other, see pictures attached. It is the same in v3.1.7.
Exporting Device Types using "All data" option now produces YAML file not containing any custom fields data making it effectively useless for further importing (more so if any of omitted custom fields are set as required).
![Снимок экрана от 2022-02-04 18-31-34](https://user-images.githubusercontent.com/99031446/152793202-44130147-33f1-46ed-a2a5-d37c96ecbb48.png)
![Снимок экрана от 2022-02-04 18-32-06](https://user-images.githubusercontent.com/99031446/152793576-c514636b-7bf1-4e1f-a475-0b0fcc113e7a.png)

**Comment by jeremystretch** [comment]
> For some reason Device Type export/import differs from every other

And it's a very good reason: Device type import supports the inclusion of component templates as well, which would not be possible using CSV import.

> Exporting Device Types using "All data" option now produces YAML file not containing any custom fields data making it effectively useless for further importing (more so if any of omitted custom fields are set as required).

There's an argument to be made that custom fields should be included, but it wouldn't make sense to export this data directly back into NetBox.

**Comment by AndMrzv** [comment]
I believe "All Data" export should dump all data, custom fields included (at least this could be an option). I can work around that by creating a new Export Template and then editing the output to YAML but the import for a Device Type seems to not be allowing any custom fields no matter how I try to format them. Is there a way to import custom fields for Device Types?

There are cases for example when we need to add a bunch of Device Types similar to existent and (since "Clone" button would only clone basic fields) I was planning to export, edit a number of values in the file with a script and import the edited file back creating new Device Types. Can you suggest a better workflow I am not aware of without performing directly on the database?
