### ISSUE TITLE
Change log on home page does not honor user's table config

### ISSUE THREAD

**Issue by jeremystretch** [netbox-community/netbox#8578]
### NetBox version

v3.1.7

### Python version

3.8

### Steps to Reproduce

1. Navigate to Other > Change log
2. Configure the table and remove the "request ID" column (for instance)
3. Verify that the request ID column is no longer displayed in the table
4. Navigate to the home page

### Expected Behavior

The request ID column should be omitted from the change log at bottom

### Observed Behavior

The request ID column is still present, because the change log table is rendered without respect to the user's configured preferences.

**Comment by mathieu-mp** [comment]
All object changelog are rendered without respect to the user's configured preferences, apart from Other > Change Log which is the only one to render correctly
