### ISSUE TITLE
Circuit ID should not be mandatory or be allowed empty

### ISSUE THREAD

**Issue by jasonyates** [netbox-community/netbox#8582]
### NetBox version

3.1.7

### Feature type

Change to existing functionality

### Proposed functionality

Proposing that the 'Circuit ID' field should not be mandatory and/or be permitted as a Null value if it is to remain mandatory.

### Use case

A new circuit with a status of Planned or Provisioning is highly unlikely to have a CID assigned by the carrier. At present we have to use our TEM tool's order ID in place of a CID so that we can track a circuit order in Netbox which is less than ideal.

**Comment by jeremystretch** [comment]
I think the major issue you run into here is that you need _some_ form of identifier for the circuit, even if it has yet to be provisioned.

**Comment by jasonyates** [comment]
> I think the major issue you run into here is that you need _some_ form of identifier for the circuit, even if it has yet to be provisioned.

Why? 
If I order a circuit with a carrier, they don't assign a CID until the order is delivered or close to being delivered, in the meantime I have no unique identifier for the circuit and so I can't track it in Netbox as provisioning. I also can't use something generic like "Ordered" or "Unknown" as the model enforces a unique CID.

Is there any reason this couldn't be turned in to a user configuration option similar to ENFORCE_GLOBAL_UNIQUE ? Leave it default to True but allow users to have the flexibility of disabling it and then display something similar to "Unnamed device".

**Comment by jeremystretch** [comment]
> Why?

What does a list of circuits with no circuit IDs look like in a form? How can you tell which is which?

**Comment by jeremystretch** [comment]
Closing this out as it does not seem feasible to implement.
