### ISSUE TITLE
Remote Auth - Name + Email fields missing

### ISSUE THREAD

**Issue by ITJamie** [netbox-community/netbox#8590]
### NetBox version

v3.1.7

### Feature type

Change to existing functionality

### Proposed functionality

Currently the `First Name` `Last Name` and `Email` fields are not populated in remote auth created users.
It would be nice to have user data fully fleshed out

There does not currently appear to be options for this. 
My remote auth system can supply these as headers (well, technically i can supply `Display Name` (firstname and lastname combined).

### Use case

Having all fields filled out in internal db for users

### External dependencies

additional remote auth headers

**Comment by ryanmerolle** [comment]
This works for me using remote auth ldap.  Is this more of a social auth issue?

**Comment by candlerb** [comment]
No: this is about using `netbox.authentication.RemoteUserBackend` with data in HTTP headers, when using `REMOTE_AUTH_AUTO_CREATE_USER`.

The frontend proxy can supply the information in headers like `OIDC_CLAIM_email`, `OIDC_CLAIM_given_name` and `OIDC_CLAIM_family_name`; but there's currently no way to get Netbox pick these up into the created user, in a way corresponding to `REMOTE_AUTH_GROUP_SYNC_ENABLED` and `REMOTE_AUTH_GROUP_HEADER`.

I think this would need at least 4 new settings, such as:

```
REMOTE_AUTH_USER_DATA_SYNC_ENABLED
REMOTE_AUTH_USER_EMAIL_HEADER
REMOTE_AUTH_USER_FIRSTNAME_HEADER
REMOTE_AUTH_USER_LASTNAME_HEADER
```

To meet the original OP's requirement, they also want to accept a combined name header and split it into first name and last name algorithmically.  Personally I think that logic belongs in the proxy, if it can be done there.
