### ISSUE TITLE
Add `webpage` field to Contact model

### ISSUE THREAD

**Issue by bistraque** [netbox-community/netbox#8593]
### NetBox version

v3.1.6

### Feature type

Data model extension

### Proposed functionality

Allow for an optional webpage URL to be associated with a Contact

### Use case

Almost all vendors, telco providers and customers provide a central web portal interface to handle various workflows such as incidents, billing, etc. Since all Contact fields are optional, this will easily fill the gap and provide a generic contact entry point to some Contact portal.

### Database changes

New field of type URL for Contact model.

### External dependencies

None afaik

**Comment by hagbarddenstore** [comment]
Couldn't this be solved by adding a custom field to the contact? I checked and contacts supports custom fields.

**Comment by bistraque** [comment]
Yes correct. I already implemented it as a custom field. But my point is that a Contact is not necessarily a _physical person_, and the above use cases are almost inevitable in a production environment.

**Comment by jeremystretch** [comment]
I'm going to add this as a general-purpose "Link" model for contacts.
