### ISSUE TITLE
Search Prefixes by an exact description via REST API

### ISSUE THREAD

**Issue by djothi** [netbox-community/netbox#8594]
### NetBox version

v3.1.7

### Feature type

New functionality

### Proposed functionality

`curl https://demo.netbox.dev/api/prefixes/?q=CONTAINERS` returns all prefixes that have the string "CONTAINERS" in their description. Queryset: `Prefix.objects.filter(description__icontains=CONTAINERS)`

The proposed functionality is to be able to return all prefixes via the REST API that have an exact `description`:

`curl https://demo.netbox.dev/api/prefixes/?description=CONTAINERS` would return only prefixes that have "CONTAINERS" as a description. Queryset: `Prefix.objects.filter(description="CONTAINERS")`

### Use case

Getting Prefixes using an exact description via REST API.

### Database changes

None

### External dependencies

None

**Comment by jeremystretch** [comment]
I think it's reasonable to enable this; it should involve just adding `'description'` to `Meta.fields` in the FilterSet. However, if we're going to implement it, it should be added for _all_ models with a description field and not just Prefix.

**Comment by djothi** [comment]
Ok, working on it.
