### ISSUE TITLE
Drive support

### ISSUE THREAD

**Issue by QuentinN42** [netbox-community/netbox#8596]
### NetBox version

v3.1.6

### Feature type

Data model extension

### Proposed functionality

Create a new component type in each device : drive slots.

We can now create some drives and assign them to the device's slot.

Drive can have the following props: 
 - SSD /HDD
 - size
 - speed
 - serial number

### Use case

When we have a failed drive (too many dead sectors or undetected), we want to se where the drive is (slot number in the storage shelf).

This feature enables operators to identify drive location more quickly without resorting to blinking leds, if this feature doesn't exist or is unreliable.

### Database changes

- Drives table.
- Drive slot components.

### External dependencies

None

**Comment by dgsardina** [comment]
I am trying to model a disk array with N drive slots to know how many slots are used and by what specific drive. I believe currently the best way to model would be to use the module and module types, which I believe its a bit far fetched. Am I missing something?

**Comment by jeremystretch** [comment]
The recommended approach is to utilize inventory items as noted by @PieterL75 above.
