### ISSUE TITLE
Custom Fields Bug

### ISSUE THREAD

**Issue by dreamage** [netbox-community/netbox#8602]
### NetBox version

v3.1.7

### Python version

3.7

### Steps to Reproduce

1. Add a Custom Fields
Name: 1111    Content types: DCIM > device

2. Add a new device

3. Delete Custom Fields 1111

4.  Edit the device by step 2 and save
get a error
Unknown field name '1111' in custom field data.

### Expected Behavior

edit and save 

### Observed Behavior

Unknown field name '1111' in custom field data.

**Comment by jeremystretch** [comment]
This seems to be reproducible only when the custom field name can be confused with an integer. Repeating the above using a name with at least one alphabetic character works as expected and does not trigger an error. My guess is that the field name is being mistaken for an integer at some point.

It's difficult to image a use case for a numeric-only custom field name. This might be best solved by requiring at least one alphabetic character in a custom field name.

**Comment by dreamage** [comment]
Thank for your replay. 
How can I fix my dirty devices infomation, I can't edit it from WebUI.
Can I edit the postgresql database directly?
table: public.dcim_device -- field: custom_field_data
from {"1111": "test", "abc": "abc"}  change to {"abc": "abc"}
