### ISSUE TITLE
sync contacts with LDAP

### ISSUE THREAD

**Issue by pisaniej** [netbox-community/netbox#8614]
### NetBox version

3.x

### Feature type

New functionality

### Proposed functionality

sync/pull all groups under a specified OU into netbox (along with that group's members).

### Use case

For those that choose to use the contact functionality, they'll be able to specify users/groups as contacts of a server (I think right now only users can be a contact, but the ability to have a contact group as a contact would be nice as well).

**Comment by PieterL75** [comment]
While waiting for the approval and coding : You could create a CustomScript to to that. and schedule it to run once a day/hour/...
I have the same for the Tenant. I import them daily from a LDAP source.

**Comment by jeremystretch** [comment]
Thank you for your interest in extending NetBox. Unfortunately, the information you have provided does not constitute an actionable feature request. Per our [contributing guide](https://github.com/netbox-community/netbox/blob/develop/CONTRIBUTING.md), a feature request must include a thorough description of the proposed functionality, including any database changes, new views or API endpoints, and so on. It must also include a detailed use case justifying its implementation. If you would like to elaborate on your proposal, please modify your post above. If sufficient detail is not added, this issue will be closed.

**Comment by pisaniej** [comment]
@PieterL75 
> While waiting for the approval and coding : You could create a CustomScript to to that. and schedule it to run once a day/hour/... I have the same for the Tenant. I import them daily from a LDAP source.

could you share what you have possibly?

**Comment by jeremystretch** [comment]
Closing this as no further detail has been provided.
