### ISSUE TITLE
Rack Power Utilization always at 0%

### ISSUE THREAD

**Issue by QuentinN42** [netbox-community/netbox#8617]
### NetBox version

v3.1.7

### Python version

3.9

### Steps to Reproduce

1. Create some devices with power ports
![image](https://user-images.githubusercontent.com/32516498/153708756-0586114c-aad1-46f0-b1cd-a11c1e44e28c.png)

2. Create a Rack
3. Add the devices to the rack
![image](https://user-images.githubusercontent.com/32516498/153708768-6896b3fb-36aa-4cf8-9797-79be719d4bbe.png)

4. Create a power panel with some power feeds
![image](https://user-images.githubusercontent.com/32516498/153708784-187702ac-ddae-45b2-83cf-b22108549e74.png)

5. Link all feeds to the created rack 
![image](https://user-images.githubusercontent.com/32516498/153708724-8c050367-f72a-4f9f-b853-e9e9ab81ed60.png)

6. Link all feeds to the devices power ports

Cf. 
- [netbox demo](https://demo.netbox.dev/dcim/racks/43/)
- [Slack thread](https://app.slack.com/client/T01P0D0366B/C01P0FRSXRV/thread/C01P0FRSXRV-1644597945.142099)

### Expected Behavior

The power utilization must have a value.

### Observed Behavior

The power utilization is still at 0%.
![image](https://user-images.githubusercontent.com/32516498/153708710-3cf69f48-ba84-4249-a0bc-cbbc5f1cbfcf.png)

**Comment by jeremystretch** [comment]
The power utilization within a rack calculates power draw from power outlets to power ports. (The expectation is that a PDU within a rack distributes power from a power feed to consuming devices.) In the example above, you've connected power ports directly to individual power feeds, so it does not count as being utilized.

**Comment by markkuleinio** [comment]
> The expectation is that a PDU within a rack distributes power from a power feed to consuming devices.

@jeremystretch can you check the discussion https://github.com/netbox-community/netbox/discussions/8725, I believe I have modelled the power ports+outlets correctly, but the calculation stops at one level. Should I take your comment above that there is no intention to support PDUs connecting to PDUs, or is it worth opening an issue for adding support for hierarchical power calculation?

**Comment by jeremystretch** [comment]
@markkuleinio My comment above applies to the conditions described in this bug report. If you'd like to discuss an alternate setup, you're welcome to open a separate issue.

I'm going to close this out as I believe the OP's issue has been addressed.
