### ISSUE TITLE
Incorrect virtual machine header in virtual machine interfaces list

### ISSUE THREAD

**Issue by hagbarddenstore** [netbox-community/netbox#8623]
### NetBox version

v3.1.7

### Python version

3.9

### Steps to Reproduce

1. Go to virtual machine interfaces list (https://demo.netbox.dev/virtualization/interfaces/)

### Expected Behavior

The virtual machine column header is `Virtual machine`

### Observed Behavior

The virtual machine column header should be `Virtual Machine`

**Comment by jeremystretch** [comment]
I'm going to close this under the assumption it's covered by #8624.
