### ISSUE TITLE
Use Pascal Case for all table column headers

### ISSUE THREAD

**Issue by hagbarddenstore** [netbox-community/netbox#8624]
### NetBox version

v3.1.7

### Feature type

Change to existing functionality

### Proposed functionality

Pascal Case all column headers in all tables.

### Use case

To make the UI more consistent with the somewhat established practice of using Pascal Case for column headers.

### Database changes

None

### External dependencies

None

**Comment by jeremystretch** [comment]
Is the intent here merely to standardize on using grammatical title case for the header text displayed for all column headers? Or are you proposing that we rename the columns themselves?

**Comment by jeremystretch** [comment]
Closing this as there has been no further reply.
