### ISSUE TITLE
Search tags by their description

### ISSUE THREAD

**Issue by BrunoBlanes** [netbox-community/netbox#8629]
### NetBox version

v3.1.7

### Feature type

Change to existing functionality

### Proposed functionality

Allow the search bar at the Tags page to also search through the Description column.

### Use case

One use case for tags is for identifying VLANs and, in our use case, they are abbreviated, e.g., `NWPT` stands for **New Port**.
We'd like to be able to search for the term **New Port**, which is in the `Description` field, without needing to use the browser's  `Ctrl+F`.

### Database changes

None.

### External dependencies

N/A

**Comment by minitriga** [comment]
Do we want this functionality in the API also?

**Comment by jeremystretch** [comment]
@minitriga The UI and REST API use the same filtersets for all models, so they're effectively the same.
