### ISSUE TITLE
Date filter not working with gt lt

### ISSUE THREAD

**Issue by hyudra** [netbox-community/netbox#8636]
### NetBox version

v3.1.7

### Python version

3.7

### Steps to Reproduce

My version still 2.11.10, but as I tested with 3.1.7 on demo website. It got same result.

https://demo.netbox.dev/dcim/devices/?created__lt=2021-12-30
https://demo.netbox.dev/dcim/devices/?created__gt=2021-12-30

The record shown not change with either filter

### Expected Behavior

Filter working same as integer such as.
https://demo.netbox.dev/dcim/devices/?id__lt=10

### Observed Behavior

no change to records

**Comment by jeremystretch** [comment]
Per the REST API documentation, NetBox creates only less than/greater than _or equal_ filters for date objects, so instead use `created__lte` or `created__gte` to find dates earlier or later, respectively.
