### ISSUE TITLE
netbox v3.2-beta1 - dcim/device-types/inventory-items error "'component' does not resolve to an item"

### ISSUE THREAD

**Issue by PieterL75** [netbox-community/netbox#8658]
### NetBox version

v3.2-beta1

### Python version

3.9

### Steps to Reproduce

1. Create a devicetype
2. Create a Module Bay on that device type
3. Create a new inventory item on that device type.
(only complete the mandatory fields, leave the rest default)

### Expected Behavior

The Inventory item is created without errors

### Observed Behavior

After clicking the 'create' button, an error is thrown:

    <class 'ValueError'>
    'component' does not resolve to an item that supports prefetching - this is an invalid parameter to prefetch_related().
    Python version: 3.8.10
    NetBox version: 3.2.0-beta1

When refreshing, the inventory items was created properly.

I noticed that after this, creating inventory items work without errors

**Comment by jeremystretch** [comment]
I'm not able to reproduce this currently, though I recall running into a similar issue with InventoryItemTable (for device items). It has something to do with the table attempting to prefetch `component`, which, as a generic foreign key, cannot be prefetched reliably.

**Comment by jeremystretch** [comment]
@PieterL75 have you uncovered a way to reproduce this reliably? I haven't seen any further reports so far.

**Comment by PieterL75** [comment]
I'm not able to reproduce it... migth have been bad caching or something.

You may close the bugreport.. if I experience it again, I'll create a new bugreport

greetz

Pieter

**Comment by jeremystretch** [comment]
Thanks!
