### ISSUE TITLE
v3.2.0-beta1: Custom Object Field-Relationship "orphaned" after deletion of related object

### ISSUE THREAD

**Issue by moonrail** [netbox-community/netbox#8659]
### NetBox version

v3.2.0-beta1

### Python version

3.8

### Steps to Reproduce

Tested in https://beta-demo.netbox.dev/

1. Create a Custom Field on e.g. `dcim.interface` of type `Multiple objects` to Content-Type `tenancy.tenant`
2. Create a `tenancy.tenant`
3. Create a `dcim.interface`
4. Assign the created Tenant to the Interface on the previously created Custom Field
5. Delete the Tenant
6. Inspect the Interface

### Expected Behavior

Either the deletion of the Tenant should be prohibited, as it is still referenced.
Or the reference is cleaned up correctly on the Interface.

### Observed Behavior

Tenant can be deleted, but the reference is seemingly not being cleaned up on the Interface:

https://beta-demo.netbox.dev/dcim/interfaces/1/
![Screenshot_20220216_103455](https://user-images.githubusercontent.com/40096303/154236428-b2168158-c828-4445-a98f-2caadcb9837b.png)

**Comment by jeremystretch** [comment]
This looks like a simple bug with the template display.
