### ISSUE TITLE
tzdata error when upgrading from 3.1 to 3.2-beta1

### ISSUE THREAD

**Issue by PieterL75** [netbox-community/netbox#8683]
### NetBox version

v3.2-beta1

### Python version

3.9

### Steps to Reproduce

Upgrade from 3.1 to 3.2-beta1

### Expected Behavior

smooth upgrade

### Observed Behavior

An error was thrown related to 'tzdata'

> Applying database migrations (python3 netbox/manage.py migrate)...
> Traceback (most recent call last):
>   File "/usr/lib/python3.9/zoneinfo/_common.py", line 12, in load_tzdata
>     return importlib.resources.open_binary(package_name, resource_name)
>   File "/usr/lib/python3.9/importlib/resources.py", line 88, in open_binary
>     package = _get_package(package)
>   File "/usr/lib/python3.9/importlib/resources.py", line 49, in _get_package
>     module = _resolve(package)
>   File "/usr/lib/python3.9/importlib/resources.py", line 40, in _resolve
>     return import_module(name)
>   File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
>   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
>   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
> ModuleNotFoundError: No module named 'tzdata'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/opt/netbox/netbox/manage.py", line 10, in <module>
>     execute_from_command_line(sys.argv)
>   File "/opt/netbox/venv/lib/python3.9/site-packages/django/core/management/__init__.py", line 425, in execute_from_command_line
>     utility.execute()
>   File "/opt/netbox/venv/lib/python3.9/site-packages/django/core/management/__init__.py", line 401, in execute
>     django.setup()
>   File "/opt/netbox/venv/lib/python3.9/site-packages/django/__init__.py", line 24, in setup
>     apps.populate(settings.INSTALLED_APPS)
>   File "/opt/netbox/venv/lib/python3.9/site-packages/django/apps/registry.py", line 91, in populate
>     app_config = AppConfig.create(entry)
>   File "/opt/netbox/venv/lib/python3.9/site-packages/django/apps/config.py", line 223, in create
>     import_module(entry)
>   File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
>   File "<frozen importlib._bootstrap_external>", line 790, in exec_module
>   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
>   File "/opt/netbox/venv/lib/python3.9/site-packages/timezone_field/__init__.py", line 1, in <module>
>     from timezone_field.fields import TimeZoneField
>   File "/opt/netbox/venv/lib/python3.9/site-packages/timezone_field/fields.py", line 11, in <module>
>     class TimeZoneField(models.Field):
>   File "/opt/netbox/venv/lib/python3.9/site-packages/timezone_field/fields.py", line 41, in TimeZoneField
>     default_zoneinfo_tzs = [ZoneInfo(tz) for tz in pytz.common_timezones]
>   File "/opt/netbox/venv/lib/python3.9/site-packages/timezone_field/fields.py", line 41, in <listcomp>
>     default_zoneinfo_tzs = [ZoneInfo(tz) for tz in pytz.common_timezones]
>   File "/usr/lib/python3.9/zoneinfo/_common.py", line 24, in load_tzdata
>     raise ZoneInfoNotFoundError(f"No time zone found with key {key}")
> zoneinfo._common.ZoneInfoNotFoundError: 'No time zone found with key Pacific/Kanton'

@tobiasge mention : 

> [Tobias Genannt](https://app.slack.com/team/U01QEG4SFMW)  [9 minutes ago](https://netdev-community.slack.com/archives/C01P0FRSXRV/p1645180997892189?thread_ts=1645180110.952929&cid=C01P0FRSXRV)
> With Django 4 the default timezone implementation was changed.
> You need to to install tzdata  in your virtual environment:
> pip install tzdata

After adding the tzdata to my local requirements, did not errorer anymore.

Probably the 'tzdata' has to be added to the base_requirements.txt ?

**Comment by jeremystretch** [comment]
Interesting; thanks for the confirmation. I wonder why `django-timezone-field` doesn't pull in `tzdata` automatically.

At any rate, depending on it directly seems like a reasonable solution, at lease for now. I still need to muddle through the change from `pytz` to `zoneinfo` in Django 4.0.

Aren't timezones fun?

**Comment by gdvalderrama** [comment]
Just wanted to comment I've just had this same issue.

python 3.9.10
from django-timezone-field version 4.1.2
to django-timezone-field version 5.0

Guess I'll add tzdata to my dependencies meanwhile.

**Comment by jeremystretch** [comment]
Here's a relevant [bug report](https://github.com/mfogel/django-timezone-field/issues/82) for `django-timezone-field`. It looks like `tzdata` may become a dependency of that project, but for now I'll just add `tzdata` as a direct dependency for NetBox.
