### ISSUE TITLE
v3.2.0-beta1: Ability to search by Module and Module Type

### ISSUE THREAD

**Issue by mmfreitas** [netbox-community/netbox#8685]
### NetBox version

v3.2.0-beta1

### Feature type

Change to existing functionality

### Proposed functionality

Add searching funcionality for the new models of upcoming version 3.2.0

### Use case

Ability to search for a module / module type through the search bar.

### Database changes

Don't think any are required.

**Comment by jeremystretch** [comment]
Holding off on this until the work under #8553 is merged into `feature`.
