### ISSUE TITLE
v3.2.0-beta1: Removing a module from a module bay deletes the module and its interfaces

### ISSUE THREAD

**Issue by mmfreitas** [netbox-community/netbox#8686]
### NetBox version

v3.2.0-beta1

### Python version

3.9

### Steps to Reproduce

1. Create a device that has module bays
2. Install a module onto a module bay.
3. Attempt to "remove module"

### Expected Behavior

I expected this to function like a device bay, when you remove a child device from the device bay, the child device still exists, its just not installed on a device.

Since there are fields on a module such as Asset Tag and Serial Number I feel like the module should be kept aswell. (maybe delete its interfaces and recreate them when installing onto another device?)

### Observed Behavior

When removing a module from a module bay it deletes the module and all of its interfaces.

**Comment by jeremystretch** [comment]
> When removing a module from a module bay it deletes the module and all of its interfaces.

This is intended behavior. It doesn't make sense to me to model line cards without associating them with a parent device.

> I expected this to function like a device bay, when you remove a child device from the device bay, the child device still exists, its just not installed on a device.

Devices can exist independently of a parent device; modules cannot.

**Comment by mmfreitas** [comment]
> This is intended behavior. It doesn't make sense to me to model line cards without associating them with a parent device.

Ok, let's say I have a module (card) with 20 interfaces installed on a device, and I need that module to be moved to another device. I delete the module (which has the information of the asset_tag and serial_number and lose that info) and then I have to create another module of the same type and fill the same information for the asset_tag and serial_number.
If the module is deleted what difference does it make it having information associated to it?

> Devices can exist independently of a parent device; modules cannot.

IMO both can exist, because when I remove a module from a device I am left with the module either to be reinstalled, or to keep as spare/inventory. Being this the reason that I was expecting the module to be kept on the database.

**Comment by jeremystretch** [comment]
> If the module is deleted what difference does it make it having information associated to it?

I don't follow your question. What you described is exactly what you're expected to do. The alternative would be to store unused modules in NetBox, often with no unique identifier. That information would be useless.

We've long held the position that NetBox is not an inventory management system. If a piece of hardware isn't in use, it should not be modeled.

**Comment by jeremystretch** [comment]
At any rate, this is intended behavior as I mentioned. You're welcome to open a feature request to propose the behavior you describe, but you'll need to provide a very compelling use case.
