### ISSUE TITLE
Contact Objects for Prefixes

### ISSUE THREAD

**Issue by tioan** [netbox-community/netbox#8691]
### NetBox version

3.1.8

### Feature type

Data model extension

### Proposed functionality

It should be possible to assign a Contact Objects to a prefix.
#8087 is unfortunately not a solution, because we have to document different contact persons per prefixes within a tenant.

### Use case

The documentation of contact persons for individual prefixes.

**Comment by jeremystretch** [comment]
I'm going to close this as there's been no further explanation of the use case.
