### ISSUE TITLE
VM interface tab is missing

### ISSUE THREAD

**Issue by abhi1693** [netbox-community/netbox#8692]
### NetBox version

v3.2.0-beta1

### Python version

3.9

### Steps to Reproduce

Go to https://beta-demo.netbox.dev/virtualization/virtual-machines/361/ and notice

### Expected Behavior

Interfaces tab should be visible when the VM has associated interfaces

### Observed Behavior

Interface tab is missing

**Comment by hagbarddenstore** [comment]
Related, the config context tab doesn't show either.
