### ISSUE TITLE
3.2-beta1 Interface sorting on module

### ISSUE THREAD

**Issue by trrunde** [netbox-community/netbox#8695]
### NetBox version

3.2-neta1

### Python version

3.7

### Steps to Reproduce

Import module from yaml file with interfaces from
Ethernet{module}/1
...
Ethernet{module}/48
I used this yaml https://github.com/trrunde/devicetype-library/blob/master/module-types/Cisco/N77-F348XP-23.yaml

The sorting for interface 1,11,22,34 is messed up. See attached screenshots

![image](https://user-images.githubusercontent.com/1595396/154867204-ec5596c0-1579-4076-ad51-ec0cb2dac24a.png)
![image](https://user-images.githubusercontent.com/1595396/154867224-ce1919e5-0cf2-471c-8b2c-730bae4db208.png)

### Expected Behavior

interface to be sorted from 1..48

### Observed Behavior

Some interfaces are put at the bottom in the sorting.

**Comment by jeremystretch** [comment]
`Ethernet` and `Ehternet` are two different words.

The module type definition is incorrect.
