### ISSUE TITLE
FHRP Group creation fails with " This field is required. " without specifing the field that is required

### ISSUE THREAD

**Issue by 991jo** [netbox-community/netbox#8697]
### NetBox version

v3.1.8

### Python version

3.9

### Steps to Reproduce

1. Click the "create FHRP Group" Button
2. Create a new FHRP Group, e.g. with VRRPv3 and Group ID 1 and address "192.0.2.42/24".
3. Create the FHRP Group

### Expected Behavior

A VRRP Group is created.

### Observed Behavior

![image](https://user-images.githubusercontent.com/1368323/154922859-33880ae7-9a54-42e1-af26-6a94597066f8.png)

Creating the same group without the IP address works fine.
Also I suspect, that the IP address selection field should be a drop-down menu and not a text field?

**Comment by hagbarddenstore** [comment]
Status is the name of the field.

**Comment by 991jo** [comment]
:facepalm: well, that would have been an to obvious solution. I can confirm, it works when I set the status field.

Which leads me to an other point: The UI does not make clear, that a new IP Address object will be created. I expected, that I could search an address. Not that one would be created. And if I want to create an IP address directly, I might want to have a more complete version of the IP address form, where I can e.g. set descriptions, custom fields, etc.

**Comment by hagbarddenstore** [comment]
Iirc there was/is a feature request for the enhancing this part of the fhrp ui, can’t remember the number though

**Comment by jeremystretch** [comment]
This is covered by #8058
