### ISSUE TITLE
shift click to select multiple boxes

### ISSUE THREAD

**Issue by kimsystad** [netbox-community/netbox#8704]
### NetBox version

v3.1.8

### Feature type

New functionality

### Proposed functionality

I am fairly new to this, but I want a function where you click the first tic box, hold down shift and click the last tic box you need. Then you have selected all the tickboxes in between.

### Use case

When you are selecting multiple devices, a feature where you can select all by holding in shift after ticking one box, and then clicking on the last box that you need would save some time instead of clicking a tick box on every single device.

**Comment by CroogQT** [comment]
I'd be willing to try my hand at contribution if this could be assigned to me.

**Comment by jeremystretch** [comment]
@CroogQT all yours! I'm pretty weak with Javascript but let me know if there's anything I can help with.
