### ISSUE TITLE
Add Cisco RPS 2300 power connector

### ISSUE THREAD

**Issue by Nothing4You** [netbox-community/netbox#8707]
### NetBox version

v3.1.8

### Feature type

Data model extension

### Proposed functionality

https://www.cisco.com/c/en/us/products/collateral/switches/redundant-power-system-2300/product_data_sheet0900aecd805bbef6.html

> Cisco RPS 2300 to external device connection:
> […]
> - A 22-pin connector on the RPS end, and two varieties of connectors on the switch end:
> 
>   - 22-pin connector for Cisco Catalyst 3750E/3560E, 3750v2/3560v2, 2960/2960S/2960P/2960X Series Switches and 2911/2921/2951 routers (CAB-RPS2300-E=)
>   - 14-pin connector for all other Cisco networking devices (CAB-RPS2300=)

As far as I can tell this is a proprietary connector for Cisco/Cisco Meraki devices.

See also https://www.cisco.com/c/en/us/td/docs/switches/power_supplies/rps2300/hardware/installation/guide/2300hig/rpscable.html

### Use case

Documenting the correct power port types

**Comment by daliokas7** [comment]
I'm using 'DC Terminal' for this purpose. Also I'm specifying how many pins connector have at the switch in Description field. Not very accurate and convenient but works.

**Comment by jeremystretch** [comment]
You have not proposed a specific name for this port type. Please state the proposed name and cite the vendor's documentation for the connector itself.

**Comment by Nothing4You** [comment]
hm, that's a good question.

so far I haven't been able to find anything that would explicitly state names for them.

in Meraki documentation the 22-pin connector is referred to as `22-Pin Redundant Power Supply Connector`
e.g. https://documentation.meraki.com/MS/MS_Installation_Guides/MS225_Series_Installation_Guide#Back_Panel_Components

in Cisco documentation the 22-pin connector is referred to as `RPS Connector`
e.g. https://www.cisco.com/c/en/us/td/docs/switches/lan/catalyst2960x/hardware/installation/guide/b_c2960x_hig/b_c2960x_hig_chapter_01.html#ID622

**Comment by hagbarddenstore** [comment]
Beware, UniFi also calls their redundant power supply connections “RPS”

**Comment by jeremystretch** [comment]
This is the problem with proprietary connectors: Without a canonical name assigned by the vendor, we can't add it to NetBox. Even just looking at Cisco, if they decide to use a different connector on some future RPS product, without names we have no reliable way to distinguish between the two. For this reason, I'd strongly suggest just using the "other" type for connectors without a well-defined form factor.

**Comment by daliokas7** [comment]
Different manufacturers have their rps connectors. Maybe it's possible to name them for example Cisco-RPS-22pin, Cisco-RPS-14pin, HPE-RPS, Unifi-RPS, etc? Or just RPS connector? Because right now there are no suitable power connector option for RPS. It's not DC Terminal, nor Hardwired(under Other).

**Comment by apellini** [comment]
Also consider that Cisco RPS connector is 22-pin male on end A and on end B and also 22-pin on end A and 14-pin on end B.

**Comment by jeremystretch** [comment]
We could add an "other" type, but without a canonical designation for the proprietary type we can't add it specifically to NetBox.

**Comment by Nothing4You** [comment]
Would it maybe make more sense to have an explicit "other proprietary" type?
For me I'd initially have left the types empty for those that are not represented by existing types, my primary objective with this was to be able to provide the correct data in https://github.com/netbox-community/devicetype-library, which requires setting a type.
As netbox itself does not enforce the type to be set, I'm not sure it would add value to have a generic "other" type.

**Comment by cyr0nk0r** [comment]
Related : https://github.com/netbox-community/netbox/issues/9098

**Comment by jeremystretch** [comment]
An "other" type was added in #9098. That will have to suffice in lieu of a canonical name for the connector.
