### ISSUE TITLE
Bulk-rename for devices

### ISSUE THREAD

**Issue by do9xe** [netbox-community/netbox#8723]
### NetBox version

v3.1.6

### Feature type

New functionality

### Proposed functionality

Currently there is no bulk-rename functionality for devices. There is only a bulk-rename for interfaces. I would like to request to get the same bulk-rename functionality with (regex-)search/replace for devices.

### Use case

We are currently facing a renumbering of the rooms and buildings of our organisation to a more unique scheme. As our devices names in netbox contain some location info it would be a big help to rename the devices with the bulk-rename functionality.

**Comment by ydc-dg** [comment]
I‘m missing the bulk-rename functionality for devices as well. Example: When we need to change naming of patch panels.

**Comment by Sawborg** [comment]
This feature would be super useful for us as well. Being able to update the names for multiple devices when they "move" using a search/replace feature (e.g. updating the hostname/location prefix) would helpful.

**Comment by jeremystretch** [comment]
This probably applies to roughly any object with a `name` field; not just devices. (As noted, it exists already for device components.)

**Comment by cpund** [comment]
@jeremystretch  I'll take a crack at this issue.

**Comment by kkthxbye-code** [comment]
@cpund - All yours.

**Comment by cpund** [comment]
Got the initial work for renaming devices done I believe. Just trying to understand how to properly craft the return_url. I could just generically return the user to /dcim/devices/, but if they originally arrived at rename via a filtered /dcim/devices/ page from a site or rack, or whichever, it would just dump them to the general view rather than that original filtered view.

**Comment by cpund** [comment]
@jeremystretch Yeah, I'm going to spend around an hour or so possibly more just reading up further on how template rendering, particularly using variables in template rendering, works with Django, to see if I can achieve this. But as you mention, there may not a feasible approach - I just don't simply know enough about Django to figure out what variables are available for use, or if I could possibly inject them to be used.

**Comment by cpund** [comment]
Figured out how to return. Realized I could just use the request.GET.urlencode to bring that in. However, decided to see what would happen if I tried to rename a device without a name - spoiler: it doesn't like that.

**Comment by cpund** [comment]
@jeremystretch in your opinion, do you think it would be better to just omit any devices with a name not set, or send an error to the user that they cannot select a device with no name for bulk renaming? Or if a device has no name, pass an empty "" for the None value when the renaming function goes into the re module?

**Comment by jeremystretch** [comment]
@cpund please put a PR in with what you have so far (a draft is fine) so we can review together.

**Comment by cpund** [comment]
@jeremystretch pr submitted

**Comment by cpund** [comment]
@jeremystretch any thoughts on this?

**Comment by jeremystretch** [comment]
Sorry, I still need to look into this. Have been trying to keep up with v3.3 work.

**Comment by jeremystretch** [comment]
> Or if a device has no name, pass an empty "" for the None value when the renaming function goes into the re module?

Yep, we should just need to change this line to reference `obj.name or ''`:

https://github.com/netbox-community/netbox/blob/6cee12b1530597bf308ba39c661e456bd1802835/netbox/netbox/views/generic/bulk_views.py#L636
