### ISSUE TITLE
Filter By Device Type

### ISSUE THREAD

**Issue by jasser-chaoued** [netbox-community/netbox#8728]
### NetBox version

v3.1.8

### Feature type

Change to existing functionality

### Proposed functionality

Adding another field in **Filters** on the Device List page, which is the **Device Type** .

### Use case

In Bulk Edit sometimes we need to change only Devices who have the same Device Type. So it would be easier if we filter by that and then select all.
Also sometimes we need to look for Devices who only have the same Device Type.

**Comment by jeremystretch** [comment]
The manufacturer and model fields can be used to filter by device type.

**Comment by jasser-chaoued** [comment]
Thanks that was helpful!
