### ISSUE TITLE
Add LC/UPC and LC/PC port types

### ISSUE THREAD

**Issue by joazif** [netbox-community/netbox#8736]
### NetBox version

v3.1.6

### Feature type

Change to existing functionality

### Proposed functionality

Add LC/UPC and LC/PC port types

### Use case

specification of LC connectors

**Comment by emersonfelipesp** [comment]
## Fiber port types used mainly in FTTx topology (Fiber to the end-user customer)
 Devices like **OLT (Optical Line Terminal)** and **ONT (Optical Network Termination)** use these types of ports.

### Port types
I think it would be great to have the following Fiber port types:
- LC/UPC
- LC/APC
- SC/UPC
- SC/APC

---

### Connector types and Fiber endface
Where **LC (Lucent Connector)** and **SC (Standard Connector)** are different connectors.
![lc-sc](https://user-images.githubusercontent.com/24397251/155722020-7e309608-b5e7-4977-a53e-bab5b47426f4.png)

---

### Fiber endface
While **UPC (Ultra Physical Contact)** and **APC (Angled Physical Contact)** defines the fiber endface.
![image](https://user-images.githubusercontent.com/24397251/155718294-a7969066-52ba-464e-93fd-3d1a1633579b.png)

**Comment by cpmills1975** [comment]
Can these be in addition to rather than a replacement for LC and SC? I'm working with a team of who barely know what an LC connector is let alone could differentiate between UPC and APC (I'll be honest, they are new terms to me too!)

**Comment by joazif** [comment]
Definitely additions to LC and SC.


It'll be in the netbox then:
- LC
- LC/UPC
- LC/APC
- LC/PC

- SC
- SC/UPC
- SC/APC
- SC/PC

**Comment by jeremystretch** [comment]
This link seems to explain the four polish types well: https://www.fiber-optic-tutorial.com/introduction-of-pc-upc-and-apc-connector.html. I'm going to add the PC and UPC types per @joazif's list above; the flat/default and APC types are already defined.
