### ISSUE TITLE
Allow MIN and MAX VLan ID in VLAN_GROUP

### ISSUE THREAD

**Issue by wwerther** [netbox-community/netbox#8737]
### NetBox version

v.3.1.8

### Feature type

Change to existing functionality

### Proposed functionality

It would be great if VLAN groups would have optional support for a min and a max VLAN-ID. Currently when clicking on a VLAN group I always see the amount of free vlans from 1 - 4096. I would prefer to see it only in assigned boundary.
Currently I'm adding this information using two custom fields, but their value is not reflected in the view for the VLAN-group where the amount of availble VLANs is listed.

### Use case

On one site we have several VLAN-blocks that we use for certain purpose. So we try to have a unique VLAN-number on a complete site (even though double usage would be in theorie possible).  
E.g. one building on a site get's VLAN IDs 100 - 199, the next building 200 - 299. Also in DC we have several ranges (e.g. DMZ 1000-1200). So for each building / purpose a special range is reserved.
So it would be very beneficial to open a vlan group and only see the available VIDs within the assigned range (and mabye add a function to get the next free-VID )

### Database changes

add additional column to vlan-group with min and max (defaults to 1 and 4096 when not set otherwise)

**Comment by hagbarddenstore** [comment]
This is already planned in the next release: https://github.com/netbox-community/netbox/issues/8168

**Comment by jeremystretch** [comment]
Yep, this has already been implemented for NetBox v3.2. You can experiment with it in the [beta demo instance](https://beta-demo.netbox.dev/).

**Comment by wwerther** [comment]
Cool :) Then we can close this request!
