### ISSUE TITLE
Add the ability to check if a user is a superuser to the API

### ISSUE THREAD

**Issue by jschewebbn** [netbox-community/netbox#8743]
### NetBox version

v3.1.7

### Feature type

New functionality

### Proposed functionality

The REST API exposes is_staff and is_active, but not is_superuser. 

### Use case

I would like my webhook scripts to be able to check if the user making a change is a superuser. The particular case is that I want to prevent the Tenant of an IP address from being changed, unless it's done by a superuser. It doesn't appear that the permissions model supports this type of permission, so my webhook is doing the check and reverting the change.

**Comment by sdktr** [comment]
Isn't your actual question: how can I prevent a tenant update on ipaddress in the RBAC?

**Comment by jschewebbn** [comment]
I suppose I really have 2 questions:
1) Using the API I can query for is_active and is_staff, why can't I query for is_superuser?

2) Is there a way to configure the RBAC to not allow the tenant of an IP address to be changed, but other aspects of the IP address can be changed?

**Comment by jeremystretch** [comment]
> 1. Using the API I can query for is_active and is_staff, why can't I query for is_superuser?

When the users endpoint of the REST API was implemented, it did not seem prudent to expose this, and arguably still doesn't.

> 2. Is there a way to configure the RBAC to not allow the tenant of an IP address to be changed, but other aspects of the IP address can be changed?

You can create permission constraints that limit the assigned tenant to a specific value or set of values, but it is not possible to restrict changing only a specific field.

**Comment by jeremystretch** [comment]
Why are you tying it to superuser status? A superuser, by definition, has _all_ permissions, so you don't typically want to enable this for regular users. Why not instead create a custom permission, and check whether the user has that permission assigned?
