### ISSUE TITLE
Clone should also prepopulate custom fields

### ISSUE THREAD

**Issue by skvedo** [netbox-community/netbox#8749]
### NetBox version

v3.1.8

### Feature type

Change to existing functionality

### Proposed functionality

When cloning entity, values from custom fields should be also populated in form.

### Use case

Our organization have defined custom fields for prefix with abuse contact to particular tenant IT support staff. When assigning new prefix you usually set these "same as that other segment" so using clone button is obvious approach.

### Database changes

Might be good idea add this fields to prefix form.
We defined 2 fields:
* security abuse contact for case of incident which should be taken case ASAP. Usually creates an incident ticket
* administrative contact if you need contact for particular tenant. Usually this is pointed to teams mailing list.

**Comment by IdRatherStand** [comment]
I also have users coming to me within our org asking if there is an option to turn this on (we have a very similar use case) so gets a thumbs up from me (y)

**Comment by jeremystretch** [comment]
Blocked by #9414

**Comment by arthanson** [comment]
@jeremystretch I'm thinking we wouldn't want this for all custom fields, what about an "is_clonable" flag added to custom fields (default False) if set it will copy over when cloning the related object?

**Comment by hagbarddenstore** [comment]
Arthur, that would suit our use cases perfectly. Some custom fields are used to determine which SLA we’re using, which could be cloned. Other fields are used to store external identifiers, which shouldn’t be cloned as they are unique per object in NetBox.On 4 Nov 2022, at 00:53, Arthur Hanson ***@***.***> wrote:﻿
@jeremystretch I'm thinking we wouldn't want this for all custom fields, what about an "is_clonable" flag added to custom fields (default False) if set it will copy over when cloning the related object?
