### ISSUE TITLE
Can´t access Interface panel in Beta Version

### ISSUE THREAD

**Issue by PaulR282** [netbox-community/netbox#8750]
### NetBox version

v3.2.0-beta1

### Python version

3.9

### Steps to Reproduce

1. Upgrade NetBox from pre 3.2 to 3.2.0-beta1 with data in it (devices etc)
2. Go to old device -> Interfaces

### Expected Behavior

The list of interfaces should be shown

### Observed Behavior

```
<class 'AttributeError'>

'Cable' object has no attribute 'get_status_class'

Python version: 3.9.5
NetBox version: 3.2.0-beta1```

**Comment by PaulR282** [comment]
It works if I create a new device, but not with the already created ones

**Comment by jeremystretch** [comment]
Thank you for submitting this issue, however it appears that this topic has already been raised. Please see issue #8655 for further discussion.
