### ISSUE TITLE
Make the Device Component Bulk Renaming Form allow empty replacements

### ISSUE THREAD

**Issue by 991jo** [netbox-community/netbox#8758]
### NetBox version

v3.1.8

### Feature type

Change to existing functionality

### Proposed functionality

Allow an empty replacement string in the bulk rename form.

### Use case

Removing parts of a component name without having a replacement is currently not allowed, because the form requires a replacement.

e.g. all components are called "MPO-A", "MPO-B", ... and have to be renamed to "A", "B" ...

### Database changes

none.

### External dependencies

none.

**Comment by jeremystretch** [comment]
> Allow an empty replacement string in the bulk rename form.

How, specifically, do you propose implementing this?

**Comment by 991jo** [comment]
simply allow the replacement field to be empty (as in empty string) and replacing as usual (but with an empty string).
