### ISSUE TITLE
Improvement of moving devices

### ISSUE THREAD

**Issue by PaulR282** [netbox-community/netbox#8759]
### NetBox version

v3.1.8

### Feature type

Data model extension

### Proposed functionality

If you want to move a device and plan it in NetBox (Edit the device Location and set the status to `planned`) it would be nice to see the device still active in the current location and the same device in the new location as `planned` and maybe graded greyish. 

Further, it would be nice to plan the device in rackspace that is currently used.

### Use case

Right now, if you move a device like described above, NetBox doesn't represent the real world, because the rackspace of the current location would be free in NetBox, while it is used in real life. Currently, it is difficult to plan bigger moving while documenting the current state.

### Database changes

One way to implement this would be to split the `location` attribute to something like `current_location` and `new_location`.

**Comment by jeremystretch** [comment]
This is easily accomplished by creating a copy of the device to represent the planned installation, or by making a rack reservation. Attempting to represent a single device in two places at once would obviously not be an accurate representation of the real world.

**Comment by PaulR282** [comment]
Yes, this would be one way to solve this, but you can´t name two devices the same. Also, the IP would be duplicated (possible, but not optimal)
