### ISSUE TITLE
Ability to generate / export column configuration

### ISSUE THREAD

**Issue by jasonyates** [netbox-community/netbox#8765]
### NetBox version

3.2-beta1

### Feature type

New functionality

### Proposed functionality

With the welcomed addition of the ability to specify default table columns under DEFAULT_USER_PREFERENCES it would be useful on the Configure Table dialogue box to be able to generate a snippet based on the current table configuration that could be used in the default preference setting.

The barrier to entry currently feels quite high as I need to know the table name and the exact internal naming of the columns in order to generate default preferences.

### Use case

Improves the ease of use for default table columns on DEFAULT_USER_PREFERENCES

**Comment by jeremystretch** [comment]
I struggled with this a bit during the initial implementation. What do you think is the best way to expose this? We could include a compatible representation of the user's current table configurations under their preferences; would that work?

**Comment by jasonyates** [comment]
> I struggled with this a bit during the initial implementation. What do you think is the best way to expose this? We could include a compatible representation of the user's current table configurations under their preferences; would that work?

That would be a neat way to do it.
