### ISSUE TITLE
Automatically adjust documentation theme to match user's preference

### ISSUE THREAD

**Issue by jeremystretch** [netbox-community/netbox#8770]
### Change Type

Addition

### Area

Other

### Proposed Changes

Per the [mkdocs-material documentation](https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#color-palette-toggle), it should be possible to automatically toggle light/dark mode as requested by the user's browser.

**Comment by jasonyates** [comment]
Submitted a PR for this.

Tested it across Safari, Firefox & Chrome on macOS 12.2 successfully. Documentation theme followed my system preference for light/dark mode.

**Comment by jeremystretch** [comment]
Thanks @jasonyates!
