### ISSUE TITLE
Using wildcards in DNS names

### ISSUE THREAD

**Issue by fmlshai** [netbox-community/netbox#8785]
### NetBox version

v3.1.8

### Python version

3.9

### Steps to Reproduce

This is a copy of https://github.com/netbox-community/netbox/issues/4973 because I can't comment there, but the issue is not resolved.

1. Edit IP Address in IPAM
2. Try to save with * in DNS name like: "*.example.local"

Like in https://github.com/netbox-community/netbox/issues/3722 the regex needs to be adjusted.

### Expected Behavior

IP address saved correctly.
https://en.wikipedia.org/wiki/Wildcard_DNS_record

### Observed Behavior

Error: "Only alphanumeric characters, hyphens, periods, and underscores are allowed in DNS names"

**Comment by jeremystretch** [comment]
It appears that you have duplicated #4973, which was closed due to lack of community interest. Are you interested in owning this change and contributing a PR for it?

Also, this needs to be resubmitted as a feature request, not a bug, as the current behavior is expected.

**Comment by fmlshai** [comment]
Yes, it's a duplicate as mentioned above. Well, I'm interested in getting this fixed, and also a wildcard is valid in dns records, so the validator should accept it.
My Python foo isn't strong, but I'll try to create a PR and submit it as a feature request.
Thanks for letting me know about the correct workflow.
