### ISSUE TITLE
Show prefix from VLAN groups view

### ISSUE THREAD

**Issue by snowie-swe** [netbox-community/netbox#8790]
### NetBox version

v3.2

### Feature type

Change to existing functionality

### Proposed functionality

Make it possible to see the assigned IP Prefix to a VLAN from the VLAN Group.
Currently when listing the a VLAN group you are not able to change the table or view the IP prefix assigned to a VLAN.

![image](https://user-images.githubusercontent.com/41901413/156630821-90472e0e-25c3-47ba-9080-d2a06c01a7cd.png)

Suggest to add similar view as is under VLANs tab.
(sorry for my paint skills :) )

![image](https://user-images.githubusercontent.com/41901413/156630949-eed5055d-daad-48c7-b10a-28e72585a1b3.png)

### Use case

Improved UI.

### Database changes

dont know

### External dependencies

dont know

**Comment by hagbarddenstore** [comment]
This column was removed when the details tables were removed. No idea why though.

**Comment by jeremystretch** [comment]
> This column was removed when the details tables were removed. No idea why though.

IIRC this was originally done under the view to save space, before configurable tables were a thing. It's no longer needed now.
