### ISSUE TITLE
netbox-v3.2-beta1 - Cannot create new device bay on device or device-type

### ISSUE THREAD

**Issue by pobk** [netbox-community/netbox#8791]
### NetBox version

v3.2-beta1

### Python version

3.8

### Steps to Reproduce

1. Create a device type or use an existing
2. Open "+Add component" -> "Device Bay"
3. Fill in form. I used "iLO" for name and label and added some fluff in description.
4. Click "Create" 

### Expected Behavior

I would expect a new device bay is created on the device or device-type and I'm redirected to the device-bays tab of the origin device/device-type.

### Observed Behavior

You're redirected to the device tab, however, the device bay list is empty.

**Comment by pobk** [comment]
This is reproducable on the demo-beta.netbox.dev instance.

**Comment by jeremystretch** [comment]
Thanks for the report! It looks like what's happening is that the component form validation is failing (likely because the chosen device type doesn't have the "parent" role to allow the assignment of device bays), but the view is redirecting the user as if the form submission was successful.

**Comment by pobk** [comment]
Aha! Confirmed. I added 'parent' my test type.

**Comment by jeremystretch** [comment]
Fixed in 25dc9cc14aca2caaa1119ec4c36112027c33e5b9 but I typo'd the commit message. :facepalm:
