### ISSUE TITLE
 Configurable kind choices for journal entries

### ISSUE THREAD

**Issue by jcralbino** [netbox-community/netbox#8794]
### NetBox version

v3.2-beta1

### Feature type

Change to existing functionality

### Proposed functionality

Allow NetBox administrators to configure the list of available kind choices for Journal entries

We could follow the same strategy as done in [8054](https://github.com/netbox-community/netbox/issues/8054)

So we would have the following structure to replace the current choices with the ones seen here, leaving only two choices

```
FIELD_CHOICES = {
    'extras.journal-entries.kind': (
        ('value1', 'label1', 'color1'),
        ('value2', 'label2', 'color2'),
    )
}
```

Whereas adding a + to the end of the field identifier will instead extend the available choices:

```
FIELD_CHOICES = {
    'extras.journal-entries.kind+': (
        ('valueX', 'labelX', 'colorX'),
    )
}
```

### Use case

This would allow users to define their own custom values for the journals.

**Comment by jeremystretch** [comment]
For posterity, the implemented syntax is:

```
FIELD_CHOICES = {
    'extras.JournalEntry.kind+': (
        ('foo', 'Foo'),
    )
}
```
