### ISSUE TITLE
Storage (or other devices/configurations) where there is an "Cluster-mgmt IP" and nodes underneath.

### ISSUE THREAD

**Issue by airborneric** [netbox-community/netbox#8798]
### NetBox version

v2.9.3

### Feature type

New functionality

### Proposed functionality

Need to be able to have a cluster management IP "float" to all nodes under that cluster.  Storage needs to have a container or virtual cluster that is not locked to one rack

For example NetApp Cluster 01 starts as a 2 node A800.

cluster-mgmt IP can be on any node e0M.

nodes 01-24 all have an e0M management port and IP (usually on the same subnet, but not always)

Currently, if I add and new NetApp system, that 2 node ha-pair is considered a cluster.  It is physically located in rack-X.  I need to add capacity, I install another NetApp system in rack-Y.  There is no way to expand that cluster to include the newly installed hardware.  I now have a NetApp Cluster 01, and NetApp Cluster 02 in Netbox, when in reality, it is still NetApp Cluster 01, with 2 more nodes added to it.

### Use case

Any enterprise level users needs this functionality.  VMware has a similar case where vCenter is the primary IP to manage all the nodes in the cluster, all those nodes are not necessarily in the same rack.  

Maybe this already exists, but I am not finding any examples of how to accomplish this inside of Netbox, and only 1 discussion of this issue. (referenced)

**Comment by karolyczovek** [comment]
model it as FHRP assigned IP

**Comment by jeremystretch** [comment]
> v2.9.3

I'd strongly recommend upgrading to NetBox v3.2 as many new features have been released that are likely to better address your needs. As mentioned, FHRP groups seem ideal for this.
