### ISSUE TITLE
v3.2.0-beta1: Can't add components to module without "Replicate components" option.

### ISSUE THREAD

**Issue by emersonfelipesp** [netbox-community/netbox#8803]
### NetBox version

v3.2.0-beta1

### Feature type

New functionality

#### Create "Add components" button to 'DCIM > Modules'
**DCIM > Modules > PK (Object)** does not thave the **Add components** button, as **DCIM > Devices > PK (Object)** has. As a result, it is not possible to manually add interfaces to module, just import them from a **Module Type** by using the **Replicate components** option. I don't quite know if it is a bug or made intentionally this way, but if it is supposed to be like that, I don't think is pretty clear on Netbox, maybe adding a warning would be interesting. Also, if there isn't a manual way to add the components, the **Replicate components** should be mandatory, not a option, in my opinion!

#### How it is right now
![image](https://user-images.githubusercontent.com/24397251/156896013-94bdc2b4-678e-4997-b364-dbc2957b3fc2.png)

#### How I think it should be
**OBS:** I put only the **Interface** in the dropdown list, but maybe there are other components to add.
![image](https://user-images.githubusercontent.com/24397251/156895942-05aa24e9-bd15-4f83-835f-91f5c65708c7.png)

---

[My Cisco ASR9K testing device on Netbox (beta)](https://beta-demo.netbox.dev/dcim/devices/108/)

### Use case

Users would be free to add components manually to modules (although I myself don't think it is a good way).

**Comment by jeremystretch** [comment]
Components are added from the device view. There is an option to select an installed module when creating the component.

**Comment by emersonfelipesp** [comment]
> Components are added from the device view. There is an option to select an installed module when creating the component.

I was able to create from the device view as you said. I haven't seen this, thank you.
But I think that adding the option to **Add components** from the **DCIM > Modules** view is still a good option. I don't know if it is possible (or if you agree) to place the button on both views (Device and Module's one).
