### ISSUE TITLE
Search bar contents not retained after submitting

### ISSUE THREAD

**Issue by chonty** [netbox-community/netbox#8813]
### NetBox version

v3.1.8

### Python version

3.8

### Steps to Reproduce

1. Enter a search term into the main search bar and submit
2. See empty search bar

### Expected Behavior

1. Enter a search term into the main search bar and submit
2. Search term should still be present

### Observed Behavior

1. Enter a search term into the main search bar and submit
2. Search bar is empty

**Comment by PieterL75** [comment]
I've been wanting to submit a FR for this, but always forgot about it :-)
Maybe a good one to combine with #7839 (set imput focus on searchbar )

**Comment by PieterL75** [comment]
I have a PR for this ready.. @jeremystretch can you assign this to me ?
