### ISSUE TITLE
ASNs column on Site records is not sortable

### ISSUE THREAD

**Issue by falz** [netbox-community/netbox#8822]
### NetBox version

v3.1.9

### Python version

3.8

### Steps to Reproduce

Ability to see new style ASNs values was added in https://github.com/netbox-community/netbox/issues/8664 (yay!) However one cannot sort the table by this column like we can with other fields.

1. Go to `/dcim/sites`
2. Configure Table -> Add ASNs column
3. Attempt to sort by ASNs column

### Expected Behavior

ASNs clickable/sortable like other column headers

### Observed Behavior

Not clickable/sortable

**Comment by jeremystretch** [comment]
The ASNs column is not orderable because it's a many-to-many relationship.
