### ISSUE TITLE
Export using default CSV options via API

### ISSUE THREAD

**Issue by joachimtingvold** [netbox-community/netbox#8826]
### NetBox version

v3.1.1

### Feature type

Change to existing functionality

### Proposed functionality

Be able to use the default exports ("All Data" and "Current View") from the API.

https://netbox.foo.bar/x/y/?export
https://netbox.foo.bar/x/y/?export=table

Both URLs currently exports CSV (either all, or whatever filter/page you have).

https://netbox.foo.bar/api/x/y/?export
https://netbox.foo.bar/api/x/y/?export=table

Both URLs yield `{"detail":"Not found."}` as response. I'd expect the same CSV to be output via API.

### Use case

Be able to export data quickly without having to define custom export templates. Useful for quick offline access or similar.

**Comment by jeremystretch** [comment]
I'm afraid this isn't something we're going to implement. The CSV export is a function of the table object, which is an entirely separate execution path from how API responses are rendered. The expectation of a REST API in general is that an API consumer will request the data it needs and render it in the desired format locally.

**Comment by joachimtingvold** [comment]
Would it not be fairly simple to mimic the CSV output using Jinja-templates, and just have some default ones for each endpoint that can be used when using `?export` without specifying any export template? (i.e. a built-in default template, more or less).
