### ISSUE TITLE
Changes to rear cables does not update the circuit

### ISSUE THREAD

**Issue by Yohannes988** [netbox-community/netbox#8827]
### NetBox version

3.0.6

### Python version

3.8

### Steps to Reproduce

You need a circuit with devices with front and rear ports.

1. Disconnect the rear cable and connect it to a different rear cable
2. If you now click on circuit you can see that there is no changes done.
3. Go to one of the front ports in the circuit and disconnect and connect it.
4. Then you can see that the circuit changes like it should.

### Expected Behavior

The circuit should change when I do changes to the rear cables.

### Observed Behavior

Circuit did not change even tho changes were made to a rear cable.

**Comment by jeremystretch** [comment]
Thank you for opening a bug report. Unfortunately, the information you have provided is not sufficient for someone else to attempt to reproduce the reported behavior. Remember, each bug report must include detailed steps that someone else can follow on a clean, empty NetBox installation to reproduce the exact problem you're experiencing. These instructions should include the creation of any involved objects, any configuration changes, and complete accounting of the actions being taken. Also be sure that your report does not reference data on the public NetBox demo, as that is subject to change at any time by an outside party and cannot be relied upon for bug reports.
