### ISSUE TITLE
Integrate healthcheck in netbox 

### ISSUE THREAD

**Issue by jcralbino** [netbox-community/netbox#8831]
### NetBox version

v3.1.9

### Feature type

New functionality

### Proposed functionality

In order to improve the monitoring of the netbox infrastructure key components we may be able to leverage the app [django-health-check](https://github.com/KristianOellegaard/django-health-check)

Using a dedicated url <https://netbox.fqdn/healthcheck> we will be able to perform health checks in the applications required to run netbox and eventually its monitoring.

We should be able to check:
- status of DB
- status of Redis and queues
- status of nginx 

other relevant metrics

### Use case

Adding a healthcheck endpoint that is able to validate the status of the database , Nginx service and redis service will provide the necessary information required by admins to confirm that the service is running in good condition 

This is of particular relevance within distributed environment like kubernettes

The information provided in this endpoint can be then consumed via api. Relevant values can be 

- dBstatus : can identify that dB is working and replying to queries from the application 
- redisstatus : can identify that redis is operating well and caching is occurring 
- nginx : can identify if service is providing functional 

### External dependencies

_No response_is

**Comment by jeremystretch** [comment]
> Improve the monitoring of the environment running netbox

We're going to need a more substantial explanation of the use case here, especially if the proposal is to introduce a new dependency. Please elaborate on the specific features you'd like to see and why.

**Comment by okamidash** [comment]
I'm not the original issue creator, but I want to throw my hat into the ring.
Adding a healthcheck endpoint would allow admins using netbox in distributed deployments (such as Kubernetes) to be able to monitor the health and readiness of an application in a more realistic manner. 

As it currently stands, there is no way of knowing whether netbox can accept requests, beyond a tcp socket being open. That doesn't inspire much confidence in the application, regardless of it's actual state.

Please implement this, if you have the time :3

**Comment by riconem** [comment]
Hey,
is the any progress on this feature?

This feature would be great to monitor the status of the netbox and their dependencies. 

In our setup sometimes we have connection issues. But it's hard to say where this issues comes from. With this feature we could simply see if its any failure of the netbox setup or other network elements.

**Comment by jeremystretch** [comment]
We discussed this a bit more in today's maintainers meeting, and the consensus was that a plugin would be a slightly better fit. The primary rationale for this decision was that some subset of users inevitably will want to disable the functionality, and our approach to date of providing a toggle in the form of a configuration parameter is something of an anti-pattern.

Packaging this as a plugin (which is now possible in v3.4 per #9880) has the advantage of allowing users to introduce the new functionality as desired. It might also prompt heightened interested versus a core feature, as plugins are _much_ more accessible to the casual contributor.

@arthanson are you still volunteering to own the plugin creation?

**Comment by stavros-k** [comment]
@jeremystretch Continuing from #10825

I'm working on a helm chart, for TrueNAS Scale catalog.

Healthchecks are needed for:
- Easy testing on CI when upgrade releases.
- Make sure pods/containers are healthy, if not restart them (k8s feature).

It does not have to be an http endpoint.
Even a binary or a script in the container that exits with 0 if everything is fine or 1 if not would be enough.

Healthcheck should be available for worker as well.
I guess for the main container you can hit the `/login` and see if it's up.

For housekeeper, I don't think currently there is a way to health check it.
As it's an infnite loop.
If it crashes, container will exit and k8s will restart it anyway.

**Comment by tobiasge** [comment]
We added some health checks into the [docker-compose.yml](https://github.com/netbox-community/netbox-docker/blob/release/docker-compose.yml) in the last release.
Those also work in Openshift were I use the containers. So you can reuse them in the Helm chart.

**Comment by arthanson** [comment]
Closing as completed a healthcheck plugin: https://github.com/netbox-community/netbox-healthcheck-plugin please add any feature requests or issues there.
