### ISSUE TITLE
Color of navbar under any menu is light with dark theme

### ISSUE THREAD

**Issue by mmfreitas** [netbox-community/netbox#8834]
### NetBox version

v3.1.9

### Python version

3.9

### Steps to Reproduce

1. Select dark theme
2. Navigate to any menu on the sidebar (Ex. Sites)

### Expected Behavior

The color of navbar should be dark.

### Observed Behavior

The color of navbar turns light.

**Comment by jeremystretch** [comment]
Thank you for submitting this issue, however it appears that this topic has already been raised. Please see issue #8820 for further discussion.
