### ISSUE TITLE
Quick Find only filters current page

### ISSUE THREAD

**Issue by gigglestick** [netbox-community/netbox#8839]
### NetBox version

v3.1.9

### Python version

3.9

### Steps to Reproduce

1. This seems to work on any page with a Quick Find search box. Let's say Device Types.
2. Click the Quick Find box.
3. Begin typing the name of anything on the current page.
4. Note that Quick Find does filter the current page for matching results.
5. Next, note the name of any item on page 1.
6. Scroll to the bottom and go to page 2.
7. Enter the name noted from page 1 in the Quick Find box.
8. Note that it shows zero results.
![image](https://user-images.githubusercontent.com/3887144/157566588-02d0b71e-9646-4194-8b2f-7324576b039b.png) ![image](https://user-images.githubusercontent.com/3887144/157566619-da7e8747-2f1f-4b74-918c-0da0bd95468f.png)

### Expected Behavior

As seen in my screenshots, I have 1447 unique device types. 
1. If I have to know that Catalyst items are on page 20, what is the point of this filter box?
2. Of those 1447 device types, 201 are various models of Cisco Catalyst devices, and span pages 13 to 21. If I'm unsure which specific Catalyst model I'm looking for and just want to see them all together, I have to use the top-of-page search box.

### Observed Behavior

Quick Find only filters the current page of the current view. This seems useless if the items I'm filtering for span more than one page or are not listed on the page I'm currently viewing. 

If Quick Find doesn't filter all pages of the current view (e.g. Device Types), what is the point of having this secondary search box? How does this provide value beyond the top-of-page search box? Why not have the top-of-page search box default its filter to the current view?

**Comment by kkthxbye-code** [comment]
I cannot replicate this on version 3.1.9. Can you try in incognito mode to verify that it's not a cache issue? Also, please check the network tab to see what query it makes, if any, when you type in the quick find box.

**Comment by jeremystretch** [comment]
It is evident from your screenshots that you are not running v3.1.9, as the search box was renamed to "Quick search" in v3.1.2. If you upgrade to the current stable release, you'll find that the feature works as expected.
