### ISSUE TITLE
Change of Vlan Group Scope to Add DCIM -> Device

### ISSUE THREAD

**Issue by cruse1977** [netbox-community/netbox#8843]
### NetBox version

v3.2

### Feature type

Change to existing functionality

### Proposed functionality

 In IP Fabrics, vlan relevance is often solely to a single leaf device, with vxlan (VNI) taking over beyond that device -  however its currently not possible to assign a vlan group to a device.
 
 This proposal would add DCIM -> Device to the Scope types of vlan groups

### Use case

Allowing a vlan group to be assigned on a device level would allow a IP fabrics to be further documented within netbox. 

### Database changes

.

### External dependencies

.

**Comment by jeremystretch** [comment]
This might be something to look at once we explore VXLAN/VNI modeling, but it doesn't make sense given the current data model.
