### ISSUE TITLE
Allow images to be attached to Modules and Module Types

### ISSUE THREAD

**Issue by jcollie** [netbox-community/netbox#8846]
### NetBox version

netbox-9959f6cd8-pzbbx (v3.2.0-beta2)

### Feature type

New functionality

### Proposed functionality

Allow images to be attached to modules and module types.

### Use case

Having images of modules will help users identify modules.

### Database changes

Lists of images will need to be added to modules and module types.

**Comment by jeremystretch** [comment]
I think module types makes sense, but why modules?

**Comment by jcollie** [comment]
Allowing on module is mostly for completeness I guess, based on device type/device. It would be good for documenting the installation of a specific module (maybe there are switches on the module that need to be configured in a certain way).  It also just occurred to me that it would be good to be able to attach images to device types other than the front/rear images. That would be good for devices that aren't really rack mountable or for attaching documentation about a device type.

**Comment by jeremystretch** [comment]
Wouldn't it make more sense to attach any images to the parent device, rather than to a specific module?

**Comment by jcollie** [comment]
For an installed module images from the parent device would be OK. However, it would still be nice to attach an image to the module type so that you can say "this is what X looks like" without having to do a web search for it (which can sometimes fail or be ambiguous, depending on the obscurity of the particular module).
