### ISSUE TITLE
Include module bay name when selecting a module

### ISSUE THREAD

**Issue by jcollie** [netbox-community/netbox#8848]
### NetBox version

netbox-9959f6cd8-pzbbx (v3.2.0-beta2)

### Feature type

Change to existing functionality

### Proposed functionality

When creating components on devices, you are given the opportunity to select a module to assign the component to. It would be good to include the module bay name in the selection dropdown. If there are multiple modules of the same type present on the system it will make it easier to choose the correct module.

![Screenshot from 2022-03-10 16-36-36](https://user-images.githubusercontent.com/740022/157767074-e1ff1884-090a-4cce-9351-cdcf1a6c938c.png)
 

### Use case

When there are multiple modules of the same time installed on a device, it could be confusing to pick the correct one.

### Database changes

None

### External dependencies

None

**Comment by jeremystretch** [comment]
Tweaked the API serializer to display the bay name & module type, along with its primary key.

![Screenshot 2022-03-14 at 14-04-24 Add a new interface NetBox](https://user-images.githubusercontent.com/13487278/158233813-21fcca00-c87f-418a-8aa9-8e3231428419.png)
