### ISSUE TITLE
REMOTE_AUTH_DEFAULT_GROUPS not adding new users to group

### ISSUE THREAD

**Issue by andymelichar** [netbox-community/netbox#8854]
### NetBox version

v3.1.9

### Python version

3.8

### Steps to Reproduce

1. Create new group called 'Users' in Netbox admin
2. Add settings to configuration.py for remote auth and default group:
```
# Remote authentication support
REMOTE_AUTH_ENABLED = True

REMOTE_AUTH_BACKEND = 'social_core.backends.azuread_tenant.AzureADTenantOAuth2'

REMOTE_AUTH_DEFAULT_GROUPS = ['Users']

REMOTE_AUTH_GROUP_SYNC_ENABLED = False

SOCIAL_AUTH_AZUREAD_TENANT_OAUTH2_RESOURCE  = '[redacted]'
SOCIAL_AUTH_AZUREAD_TENANT_OAUTH2_KEY       = '[redacted]'
SOCIAL_AUTH_AZUREAD_TENANT_OAUTH2_SECRET    = '[redacted]'
SOCIAL_AUTH_AZUREAD_TENANT_OAUTH2_TENANT_ID = '[redacted]'
```

3. New user authenticates using the Azure auth provider into Netbox
4. User is added to Netbox, but user is not added to 'Users' group

### Expected Behavior

New users should be added to the group(s) indicted by the REMOTE_AUTH_DEFAULT_GROUPS setting.

### Observed Behavior

User is not added to group on sign-on.

**Comment by davidc** [comment]
Can confirm this is also happening for me, also using social auth. Users are created but not added to group. Netbox ccd14dc6bbd5 (v3.1.9) via netbox-docker.

```
LOGIN_REQUIRED=True                                                                                                                                                                             REMOTE_AUTH_ENABLED=True
REMOTE_AUTH_AUTO_CREATE_USER=True                                                                                                                                                               REMOTE_AUTH_BACKEND='social_core.backends.emf.EmfOAuth2'
SOCIAL_AUTH_EMF_KEY='xxx'                                                                                                                                          SOCIAL_AUTH_EMF_SECRET='xxx'
REMOTE_AUTH_DEFAULT_GROUPS=['noc']                                                                                                                                                              
```

**Comment by Nino-Rey** [comment]
Same thing here when using Azure AD. I'm using Netbox v3.1.11

# Remote authentication support
REMOTE_AUTH_ENABLED = True
REMOTE_AUTH_BACKEND = 'social_core.backends.azuread.AzureADOAuth2'
SOCIAL_AUTH_AZUREAD_OAUTH2_KEY = 'xxx'   
SOCIAL_AUTH_AZUREAD_OAUTH2_SECRET = 'xxx'
REMOTE_AUTH_DEFAULT_GROUPS=['AAD-NRE-Apps']
REMOTE_AUTH_HEADER = 'HTTP_REMOTE_USER'
REMOTE_AUTH_AUTO_CREATE_USER = True
REMOTE_AUTH_DEFAULT_PERMISSIONS = {}

**Comment by max-baumgarten** [comment]
Having same issue

**Comment by VirgoCluster** [comment]
Same issue on NetBox 3.2.3

**Comment by mini-man** [comment]
I've tried assigning the role through the App registration side as well didn't work, Users are created with no role/group.
Instead of having a default group it would be good to use the AAD role assignment. Then you can assign users their permissions based off AAD groups/roles not just lump all SSO users together.

**Comment by huntabyte** [comment]
I have a working solution for this, at least for setting the default groups. Need to do a little cleanup/refactoring and I'll submit a PR.
