### ISSUE TITLE
Cosmetic issue (napalm status tab)

### ISSUE THREAD

**Issue by ekrichbaum** [netbox-community/netbox#8861]
### NetBox version

3.2.0-beta2

### Python version

3.9

### Steps to Reproduce

Cosmetic.  Font size of Serial Number doesn't match 14 point fonts on other fields.

### Expected Behavior

Similar look to other fields.

### Observed Behavior

Serial is wrapped in code tag.

**Comment by jeremystretch** [comment]
Fixed in 4eb7cd06b
