### ISSUE TITLE
Netbox installation

### ISSUE THREAD

**Issue by tazboyz16** [netbox-community/netbox#8862]
### Change Type

Addition

### Area

Installation instructions

### Proposed Changes

With the package installations, git should be listed to ensure the upgrade script completes with no issues. 
This is due to not all deploys include a "standard" packaging list like the proxmox ubuntu lxc containers

**Comment by jeremystretch** [comment]
Users are instructed to install git [here](https://netbox.readthedocs.io/en/stable/installation/3-netbox/#option-b-clone-the-git-repository), only if using it for the installation.

**Comment by tazboyz16** [comment]
I didnt do the git clone option, I went with the release installation. Redirecting this to option B is misplaced if option A results on requiring this package due your upgrade script process required to pull a git repo for a module or update.

Would it not be proactive to include the git package in the installation packages prior to the option A\B choice?
