### ISSUE TITLE
API User impersonation

### ISSUE THREAD

**Issue by steffenschumacher** [netbox-community/netbox#8863]
### NetBox version

v3.1.9

### Feature type

New functionality

### Proposed functionality

_(This is a second attempt at arguing for this feature - can't help thinking of a particular Einstein quote, but here goes 😏..)_
**Allow user impersonation for api requests with authorisation override.**
Using an http header attribute, eg. `“impersonate”=“some-user"` and api token, then if the user of the api token is authorised to impersonate users, then the request is authenticated as “some-user”, if this user exists.
Furthermore, if this request has http attribute `“impersonate_authorisation”=“false”`, then the authorisation privileges of this request will be those of the api token owner instead of the impersonated user - otherwise it will be of the impersonated user.

### Use case

We have a homegrown middleware on top of netbox, which enable users to modify assets in netbox in an assisted fashion, and we would prefer if write operations in netbox were done on behalf of users, whom we **don’t want to grant direct write access to netbox**. Users are sync'ed into netbox via LDAP
While it is possible fetch automatically provisioned tokens from preexisting users and use those, then this option would require netbox write privileges for the users. Privileges we prefer to be read only, so we ensure that only valid modifications are done in netbox (via the assisting middleware and directly by a few netbox admins).
To achieve this, I believe it is required to both be able to impersonate some specific user, and then also to indicate whether authorisation should be done using the impersonated user, or the actual 'system' user who is doing the impersonation.

We could merely use the system user, but then we loose out on most of the brilliant change log functionality in netbox, since all changes will be done by the system user.

### Database changes

None

### External dependencies

None

**Comment by PieterL75** [comment]
An idea is to add a 'user group' of users that that token is allowed to impersonate ?
That group can be ldap synced, so no extra maintenance there.
Also if no 'impersonate' user is provided, then the token will use the regular assigned user.
The only caveat I see, is that this one token will get a lot of rights to a lot if users. and that might not be something we want..
The FR #8233 might help securing that token, so that it can only be used from specific source ips

**Comment by steffenschumacher** [comment]
Sure - I think fencing in which users that are allowed to be impersonated is a good thing.
The token allowed to impersonate would have privileges to do pretty much anything even without this feature, so that caveat is not specific to this FR..

**Comment by steffenschumacher** [comment]
Closing as this proved too complex and niche..
