### ISSUE TITLE
Add IPMI to device with link

### ISSUE THREAD

**Issue by unrelatedinfo** [netbox-community/netbox#8864]
### NetBox version

v.3.1.9

### Feature type

New functionality

### Proposed functionality

Adding an IPMI field that is shown on the main view of the device with a clickable link.

### Use case

Will further reduce time when looking for iDRAC/iLO/IPMI and quickly allow you to establish connections.

**Comment by jcralbino** [comment]
Currently i am doing this by using service option.
You have the following steps here:
1. Add the ip address being used by IPMI in the correct interface of the device
2. Add a service association on that ip to the correct port ( name the service template IPMI)
3. You can create a custom link leveraging the service template of the device that would allow you to establish connection from a url.

**Comment by jeremystretch** [comment]
As @jcralbino points out, you can use a [custom link](https://netbox.readthedocs.io/en/stable/models/extras/customlink/) and/or a [service](https://netbox.readthedocs.io/en/stable/core-functionality/services/) to accomplish this. Please open a [discussion](https://github.com/netbox-community/netbox/discussions/new) if you'd like further assistance.

**Comment by martinum4** [comment]
Here, for a custom link, you only have to filter according to manufacturer and interface names:

{{obj.interfaces.get(name="iLO").ip_addresses.first().address.ip}}

**Comment by jeremystretch** [comment]
You could also filter on the `mgmt_only` flag on the interface model.

**Comment by unrelatedinfo** [comment]
Thanks for all the replies here.
However to me this would be a feature that doesnt need to be worked around as 90% of the devices that will be added to netbox will have IPMI or some form of management console tied to it, and today it seems that its mostly based around WebUI's.

**Comment by jcralbino** [comment]
One option could be to improve the existing service mapping to create the custom link 

The workflow would be something like

1. Associate an IP address to the device interface
2. Create a service mapping to this ip detailing the port and name of service 
3. Select a flag to create a custom link based on the service created 

The issue now is that point 3 needs to be done manually. 
But i believe it could be a valid feature to have an option when creating the service mapping to create also a custom link for this service
