### ISSUE TITLE
Exception when search for rack position without defining a rack

### ISSUE THREAD

**Issue by rodvand** [netbox-community/netbox#8866]
### NetBox version

v3.2.0-beta2

### Python version

3.8

### Steps to Reproduce

1. Find a device not racked
2. Edit the device
3. Do not select a rack, but go to rack position and start a search

### Expected Behavior

Expect not to be "allowed" to search for a rack position without defining a rack.

### Observed Behavior

See an error banner showing parts of an exception.

<img width="848" alt="Screenshot 2022-03-14 at 15 16 54" src="https://user-images.githubusercontent.com/56864/158190930-20b02d07-d92e-45fa-ab4d-5c5a6146a32b.png">

It seems that the search for a rack position uses the URL https://beta-demo.netbox.dev/api/dcim/racks/{{ rack }}/elevation/?brief=true&exclude=109&q=12 which mess up the request.

**Comment by jeremystretch** [comment]
This is reproducible on v3.1.9
