### ISSUE TITLE
Download SVG should honor images/labels setting

### ISSUE THREAD

**Issue by jcollie** [netbox-community/netbox#8880]
### NetBox version

netbox-84cb8b95fd-dcfw8 (v3.2.0-beta2)

### Python version

3.9

### Steps to Reproduce

1. Navigate to a rack.
2. Select "Labels only" in the dropdown menu.
3. Click on the "Download SVG" link.

### Expected Behavior

SVG should be downloaded that shows labels only.

### Observed Behavior

SVG is downloaded that includes images.

**Comment by jeremystretch** [comment]
This isn't a bug: The SVG is always generated the same. The toggle you see on the UI is entirely a frontend construct: It hides and displays certain elements of the SVG image in accordance with the selected option. This is much more efficient than generating a new SVG image each time a new option is selected.

You're welcome to resubmit this as a feature request if you have a specific implementation in mind. To be honest though, it doesn't seem like a great place to spend a lot of effort.

**Comment by jeremystretch** [comment]
Closing this out as there's been no further response.
