### ISSUE TITLE
Installation of requirement "graphene-django" via git no longer works

### ISSUE THREAD

**Issue by peteeckel** [netbox-community/netbox#8888]
### NetBox version

v3.2.0 beta2

### Python version

3.8

### Steps to Reproduce

Try to install the requirements via `pip install -r requirements.txt`

### Expected Behavior

Requirements are installed

### Observed Behavior

pip complains that the attempt to pull the `graphene-django` package cannot be installed via git:

```
(netbox) [root@dns ~]# pip3 install -r /opt/netbox/requirements.txt 
Collecting git+git://github.com/graphql-python/graphene-django.git@v2 (from -r /opt/netbox/requirements.txt (line 17))
  Cloning git://github.com/graphql-python/graphene-django.git (to revision v2) to /tmp/pip-req-build-4gpu1gty
  Running command git clone --quiet git://github.com/graphql-python/graphene-django.git /tmp/pip-req-build-4gpu1gty
  fatal: remote error:
    The unauthenticated git protocol on port 9418 is no longer supported.
  Please see https://github.blog/2021-09-01-improving-git-protocol-security-github/ for more information.
  error: subprocess-exited-with-error
  
  × git clone --quiet git://github.com/graphql-python/graphene-django.git /tmp/pip-req-build-4gpu1gty did not run successfully.
  │ exit code: 128
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× git clone --quiet git://github.com/graphql-python/graphene-django.git /tmp/pip-req-build-4gpu1gty did not run successfully.
│ exit code: 128
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

Simply replacing the GitHub URL in `requirements.txt` with a https URL does not work as there does not seem to be a way to specify a specific branch with https URLs.

**Comment by jeremystretch** [comment]
Thanks for the report. Looks like a [recent change by GitHub](https://stackoverflow.com/questions/70663523/the-unauthenticated-git-protocol-on-port-9418-is-no-longer-supported). I'll see about tweaking the requirements line.

Really hoping `graphene-django` v2.16 will be released soon so we can avoid the hack altogether.

**Comment by jeremystretch** [comment]
> Simply replacing the GitHub URL in `requirements.txt` with a https URL does not work as there does not seem to be a way to specify a specific branch with https URLs.

This seems to work fine for me (changing `git://` to `https://`):

```
pip install git+https://github.com/graphql-python/graphene-django.git@v2
```

**Comment by peteeckel** [comment]
> This seems to work fine for me (changing `git://` to `https://`):

My fault, I only tried "https://", not "git+https://", which did not work ... great that it can be fixed that easily!
