### ISSUE TITLE
Support for devices with >1 device bay

### ISSUE THREAD

**Issue by momorientes** [netbox-community/netbox#8889]
### NetBox version

v3.1.9

### Feature type

Change to existing functionality

### Proposed functionality

It should be possible to define if a child device uses >1 device bay.
Otherwise at least marking a device bay as "used" (by the previous device) would be an option.

### Use case

We have some 3RU chassis, which have 14 slots for LGX modules.  Those are either Patch-Panels or small CWDM/DWDM filters.   
The chassis itself is just a piece of metal taking up rack space with 14 device bays. Some of our LGX modules are double-wide and take up 2 slots, which we'd ideally like to document correctly, or at least mark as used (same as a port can be marked as connected).

**Comment by jeremystretch** [comment]
Thank you for your interest in extending NetBox. Unfortunately, the information you have provided does not constitute an actionable feature request. Per our [contributing guide](https://github.com/netbox-community/netbox/blob/develop/CONTRIBUTING.md), a feature request must include a thorough description of the proposed functionality, including any database changes, new views or API endpoints, and so on. It must also include a detailed use case justifying its implementation. If you would like to elaborate on your proposal, please modify your post above. If sufficient detail is not added, this issue will be closed.

**Comment by jeremystretch** [comment]
Closing this as no further detail about the proposed implementation has been provided.
