### ISSUE TITLE
Upgrade to psycopg3

### ISSUE THREAD

**Issue by ndTEC** [netbox-community/netbox#8892]
### NetBox version

v3.1.9

### Feature type

Change to existing functionality

### Proposed functionality

psycopg3 has the ability to connect to a postgresql server using a uri. [docs](https://www.psycopg.org/psycopg3/docs/api/conninfo.html) 
The uri can look like [this.](https://www.postgresql.org/docs/current/libpq-connect.html#:~:text=34.1.1.2.%C2%A0-,Connection%20URIs,-The%20general%20form)

### Use case

This is very useful when you have a cluster of Postgresql with pg_auto_failover
You can pass a link like this:
postgresql://host1:123,host2:456/somedb?target_session_attrs=any&application_name=myapp

### External dependencies

psycopg3

**Comment by jeremystretch** [comment]
From what I understand, Django does not yet support psycopg3, though there is an [active feature request](https://code.djangoproject.com/ticket/33308). I'm sure we'll make it available when and if support is introduced in Django officially.
