### ISSUE TITLE
Show count of assigned IP ranges on tenant view

### ISSUE THREAD

**Issue by hannesNiederwolfsgruber** [netbox-community/netbox#8893]
### NetBox version

v3.1.9

### Feature type

New functionality

### Proposed functionality

It is currently possible to assign IP ranges to a specific tenant. For a specific tenant, however, it is very hard to find out which IP ranges have been assigned to the tenant. It would be advantageous if an overview of the IP ranges that have been assigned to the tenant could also be provided on the tenant's stats page.

### Use case

As with the IP addresses and prefixes, one could also find out under the tenant's stats which IP ranges were assigned to the tenant.

**Comment by jeremystretch** [comment]
> For a specific tenant, however, it is very hard to find out which IP ranges have been assigned to the tenant.

You can very easily filter the list of IP ranges by tenant or tenant group.
