### ISSUE TITLE
Add Parallel Redundancy Protocol(PRP) interface type

### ISSUE THREAD

**Issue by uvinva** [netbox-community/netbox#8904]
### NetBox version

v3.1.9

### Feature type

Change to existing functionality

### Proposed functionality

Add interface type PRP. It is necessary to separate it into a separate type, since the principle of operation of the protocol is different from LAG

### Use case

The functionality is similar to the LAG interface type.

**Comment by DanSheps** [comment]
So, having never used PRP, I took a look at the [wiki](https://en.wikipedia.org/wiki/Parallel_Redundancy_Protocol).

I don't see any reason why we can't add this.

**Comment by jeremystretch** [comment]
We need to give some thought to the impact (if any) this would have on LAG membership modeling. PRP interfaces presumably allow the assignment of multiple physical member interfaces, correct? The current interface model tracks these via its `lag` ForeignKey field. While it's technically feasible to reuse this field, for PRP interfaces, it may be confusing.

**Comment by uvinva** [comment]
> We need to give some thought to the impact (if any) this would have on LAG membership modeling. PRP interfaces presumably allow the assignment of multiple physical member interfaces, correct? The current interface model tracks these via its `lag` ForeignKey field. While it's technically feasible to reuse this field, for PRP interfaces, it may be confusing.

Yes you are right.
