### ISSUE TITLE
Sensitive information, like SSID PSKs, is stored in plain text

### ISSUE THREAD

**Issue by w1tht0uchp4d** [netbox-community/netbox#8909]
### NetBox version

3.1.5

### Python version

3.9

### Steps to Reproduce

1. Have SSIDs with PSKs stored in your Netbox installation
2. Create a pg_dump of the netbox database
3. Observer the pg_dump file in a text editor. The sections public.extras_objectchange and public.wireless_wirelesslan are relevant.

### Expected Behavior

Sensitive information is not present in public.extras_objectchange.
Data in public.wireless_wirelesslan is encrypted.

### Observed Behavior

Data is displayed as plain text in both cases.

**Comment by jeremystretch** [comment]
This is clearly intentional and not a bug. If you need secure storage for this type of data, I suggest using a tool such as [Hashicorp Vault](https://www.hashicorp.com/products/vault). There's even a [NetBox plugin](https://github.com/ffddorf/netbox-vault-secrets) to integrate with it.
