### ISSUE TITLE
3.1.9 Depedency Causes issues on Amazon Linux

### ISSUE THREAD

**Issue by brolewis** [netbox-community/netbox#8911]
### NetBox version

v3.1.9

### Python version

3.8

### Steps to Reproduce

Install NetBox v3.1.9 on EC2 Graviton instance using Python 3.8
Run ugrade.sh
Get gcc error

### Expected Behavior

Dependencies install

### Observed Behavior

The upgrade to django-timezone-field to 5.0 added a new requirement: https://github.com/mfogel/django-timezone-field/blob/main/pyproject.toml#L41

This change requires the library to be compiled on EC2 because no suitable wheel is found, and gcc isn't installed.

Is there a need to upgrade to 5.0 of `django-timezone-field` on a minor point release?

**Comment by jeremystretch** [comment]
This is not a NetBox issue. If you encounter a problem installing a particular Python project, please raise a bug with that project.

**Comment by brolewis** [comment]
When you upgrade a MAJOR library version in a point release it IS a NetBox problem: https://github.com/netbox-community/netbox/commit/a5603c9953bb7540d339a2dab670e73e6a894550#diff-4d7c51b1efe9043e44439a949dfd92e5827321b34082903477fd04876edb7552

**Comment by brolewis** [comment]
And it's also pinned to `5.0`, which means even if it gets fixed, it wouldn't be updated here.
