### ISSUE TITLE
Improve documentation regarding VC masters interfaces

### ISSUE THREAD

**Issue by stephanblanke** [netbox-community/netbox#8913]
### Change Type

Addition

### Area

Functionality/features

### Proposed Changes

Based on some discussions and issues I would suggest to add some information to the Virtual Chassis documentation:

- (In general all virtual interfaces should be added to the master member)
- Only if a VC master is defined, interfaces from all members are displayed when viewing the master member interface overview. This excludes management-only interfaces from members other than the master member

**Comment by NielsFrowiss** [comment]
Virtual Chassis is a feature on Juniper Networks routing or switching devices that provides network resiliency in the form of redundant Routing Engines and network expansion flexibility with minimal impact to a configuration.

Virtual Chassis technology on switches enables you to interconnect supported combinations of EX Series and QFX Series switches into one logical device that you can configure and manage as a single unit. Switches interconnected into a Virtual Chassis are called Virtual Chassis member switches, identified by a member ID within the Virtual Chassis.

Virtual Chassis member switches are interconnected and communicate with each other using Virtual Chassis ports (VCPs).
For more information see[https://www.juniper.net/documentation/us/en/software/junos/virtual-chassis-qfx/topics/concept/virtual-chassis-switches-overview.html]( https://www.juniper.net/documentation/us/en/software/junos/virtual-chassis-qfx/topics/concept/virtual-chassis-switches-overview.html)-[apkbik](https://apkbik.org/).
Thanks

**Comment by johnosseyran** [comment]
Virtual Chassis Basics on Switches. Virtual Chassis is a feature on Juniper Networks routing or switching devices that provides network resiliency in the form of redundant Routing Engines and network expansion flexibility with minimal impact to a configuration. [https://github.com/netbox-community/netbox/issues/8913](https://github.com/netbox-community/netbox/issues/8913) - [Apkbik](https://apkbik.com/)

**Comment by jeremystretch** [comment]
Deleted comments above for spam links.

**Comment by ParsifalBarberi** [comment]
Hey thanks for the super helpful reply. I'm not sure how I missed that thread. I haven't quite mastered the search function on here. I think I'll pass with him this time around. If i want any further guideline we will contact you here [https://github.com/netbox-community/netbox/issues/8913](https://github.com/netbox-)[teatime](https://teatimeresults.co/)[-community/netbox/issues/8913
](https://github.com/netbox-community/netbox/issues/8913).
Thanks
