### ISSUE TITLE
Allow assignment of FHRP groups to tenants, sites, VLAN groups and vlans

### ISSUE THREAD

**Issue by stephanblanke** [netbox-community/netbox#8914]
### NetBox version

v3.1.10-dev

### Feature type

Change to existing functionality

### Proposed functionality

It should be possible to assign FHRP groups to tenants, sites, VLAN groups and VLANs. This should resemble the way it is implemented for prefixes: Each FHRP group can be assigned to zero to one site, zero to one VLAN group, zero to one VLAN (contained in the assigned VLAN group). The assigned site, VLAN group and VLAN should be added as a column to the table view of FHRP groups.

I am willing to create a PR for this.

### Use case

Currently FHRP groups with the same number, protocol and authentication properties cannot be further distinguished. It is pretty common to number an FHRP group by the associated VLAN ID on a specific site. Lets pretend we have an enterprise network with 100 sites, with each site resembling the same VLAN structure. This would lead to multiple FHRP groups with the same id, type and probably authentication properties. By allowing to assign FHRP Groups to organizational elements (sites, vlan groups and vlans) it is easy to find the FHRP group in question. This would make it much easier to automatically create, edit and delete those FHRP groups.

### Database changes

Foreign keys for assigned site, vlan group & vlan

**Comment by stephanblanke** [comment]
Since I need this feature in my local installation, I already implemented this:
https://github.com/stephanblanke/netbox/tree/8914-fhrp-assignments

When this issue is accepted, I will create a PR.

**Comment by johnosseyran** [comment]
It should be possible to assign FHRP groups to tenants, sites, VLAN groups and VLANs. This should resemble the way it is implemented for prefixes: Each FHRP group can be assigned to zero to one site, zero to one VLAN group, zero to one VLAN (contained in the assigned VLAN group). The assigned site, VLAN group and VLAN should be added as a column to the table view of FHRP groups. [https://github.com/netbox-community/netbox/issues/8914](https://github.com/netbox-community/netbox/issues/8914) - [Gosloto](https://gosloto.co/)

**Comment by jeremystretch** [comment]
> It should be possible to assign FHRP groups to tenants, sites, VLAN groups and VLANs.

This would be redundant to the association which exist via assigned IP addresses and (via their interfaces) devices/VMs.

> Currently FHRP groups with the same number, protocol and authentication properties cannot be further distinguished.

They can be distinguished by the interfaces and IP addresses with which they are associated.
