### ISSUE TITLE
Locations not appearing under the correct parent

### ISSUE THREAD

**Issue by gigglestick** [netbox-community/netbox#8915]
### NetBox version

v3.1.9

### Python version

3.9

### Steps to Reproduce

1. Manually create several locations.
2. Create several child locations via CSV import with the parent set to locations in step 1.

### Expected Behavior

Locations should appear under the correct parent and be sorted alphabetically within each level.

### Observed Behavior

I have parents: Area A, Area B, Area C _(Currently appearing in order Area A, Area C, Area B)_
I have lots of children: Row A1-A, Row A1-B, Row A1-C, etc.

- All Row A1-* entries are set to parent Area A, but some are appearing under Area C in the location list. If I click Area C, it shows no children.
- If I assign some to Area C as the parent, they appear under Area B in the location list. If I click Area B, it shows no children.

![20220318_1744_loc_edit](https://user-images.githubusercontent.com/3887144/159098580-adbb1ec4-86aa-4361-8832-9f7d02063227.png)
![20220318_1744_loc_list](https://user-images.githubusercontent.com/3887144/159098595-963610b7-2133-4c39-b5c4-dbd635c17a33.png)

**Comment by gigglestick** [comment]
I've tried clearing the parent and saving, so the children appear without a parent, then reassigning them to Area A again and they return to area C.

**Comment by gigglestick** [comment]
If I assign A1-F to Area C, it appears under Area B.

**Comment by gigglestick** [comment]
All of the Row A1-* locations were created via CSV import where the parent was set to "Area A".

**Comment by gigglestick** [comment]
If I filter the location view where parent is Area A, all the right Row A1-* items show up. When I clear the filter, some appear Area B and appear under Area C.

**Comment by jeremystretch** [comment]
Closing this out as sufficient reproduction steps have not been provided. See #8987 for a potential fix in the absence of a known cause.
