### ISSUE TITLE
Site selection in Prefix creation dialog does not limit VLAN group selection

### ISSUE THREAD

**Issue by stephanblanke** [netbox-community/netbox#8919]
### NetBox version

v3.1.10-dev

### Python version

3.9

### Steps to Reproduce

1. Open the prefix creation form
2. Under "Site/VLAN Assignment" select a site from the list
3. Open selection menu for VLAN Group

### Expected Behavior

Selecting a site from the list should limit the available VLAN Groups, that can be selected from the list.

### Observed Behavior

Selecting a site from the list has no impact on the list of available VLAN Groups.

**Comment by stephanblanke** [comment]
I think the bug is here:
https://github.com/netbox-community/netbox/blob/f64987d0c4ddef473f997bfa71c8bca3d6adbf09/netbox/ipam/forms/models.py#L219-L230

Changing `site_id` to `scope_id` (line 225) and ading `scope_type = 'dcim.site'` (before line 226) would work, but in that case VLAN groups that are not assigned to a specific site would not be displayed anymore. I am unsure, if that would be the desired behaviour.

**Comment by jeremystretch** [comment]
Close; `site_id` should be `site`.
