### ISSUE TITLE
Limit the number of non-racked devices that are listed on the Site and Location pages

### ISSUE THREAD

**Issue by jcollie** [netbox-community/netbox#8920]
### NetBox version

netbox-84cb8b95fd-dcfw8 (v3.2.0-beta2)

### Feature type

Change to existing functionality

### Proposed functionality

Only show a small number (10 or so) of non-racked devices on site and location pages. Include a link that would take you to a device search with pre-populated search that limits the devices shown to that site/location and have not been assigned to a rack.

### Use case

Currently, when you view a site or a location in NetBox, it will list all of the non-racked devices that have been assigned to that site or location. If you have a lot of non-racked devices, the page can take a very long time to generate and is very unwieldy to use. By linking to a device search, you can use the paging functionality or further narrow the search parameters.

### Database changes

None

### External dependencies

None

**Comment by jeremystretch** [comment]
This sounds like it would be addressed by #8184 (allowing the user to paginate through the table without leaving the page).

**Comment by jasonyates** [comment]
@jeremystretch Is this FR approved in it's current form or are you suggesting only #8184 could close it?

I'm happy to pick it up in it's current form if so.

**Comment by jeremystretch** [comment]
@jasonyates both. I think it makes sense in the immediate term to limit the number of devices listed, and once #8184 is in place it will no longer be necessary to do so.

I'll assign this to you, thanks!
