### ISSUE TITLE
List of services associated to IP address on IP address page

### ISSUE THREAD

**Issue by kotso** [netbox-community/netbox#8922]
### NetBox version

v3.1.9

### Feature type

New functionality

### Proposed functionality

Will be very useful to see services on IP address page ( `/ipam/ip-addresses/XXX/` ) associated to this IP.

In same manner as I can see services on device page `/dcim/devices/XXX/`.

### Use case

UX improvement.

### Database changes

no need

### External dependencies

no

**Comment by jeremystretch** [comment]
@DanSheps are you still planning to work on this?

**Comment by kotso** [comment]
@jeremystretch @DanSheps thank you guys, it's great feature
