### ISSUE TITLE
Additional Fields in Device Bay Table

### ISSUE THREAD

**Issue by johannwagner** [netbox-community/netbox#8926]
### NetBox version

v3.1.6

### Feature type

New functionality

### Proposed functionality

We would like to see additional fields within the Device Bays table. In particular, we want to introduce the following fields:
  - Device Type
  - Device Role 

We are also happy to provide the needed PR for this feature!

![Screenshot from 2022-03-21 12-36-24](https://user-images.githubusercontent.com/12380026/159253889-a6a95317-45c3-424f-9739-41600516e7b2.png)

### Use case

We use housings for some devices, which have different types and roles. Therefore a housing can contain various different device types and roles. In the device bay overview, we cannot view the different types and roles within the housing. This results in each device having to be viewed individually to see the type and/or role of the device. We want to resolve this problem to provide a better user experience.

### Database changes

None

### External dependencies

None

**Comment by minitriga** [comment]
PR Open

**Comment by johannwagner** [comment]
Thanks a lot!
