### ISSUE TITLE
Search integration in plugins

### ISSUE THREAD

**Issue by johannwagner** [netbox-community/netbox#8927]
### NetBox version

v3.1.6

### Feature type

New functionality

### Proposed functionality

We would like to introduce a possibility to search within added models of plugins. We would probably add a `search.py` within the plugin root repository that exposes  a similar formed structure as in https://github.com/netbox-community/netbox/blob/6c686af1b70acdc56a8fdbe84451f7012e2b4197/netbox/netbox/search.py#L241, similar to menu items. Therefore, this can be included into `SEARCH_TYPES` on plugin load to to enable a search in plugins.

We would be happy to provide a PR.

### Use case

We do some heavy lifting within Netbox plugins that is going to be extended after the next v3.2 release. Therefore, we need to search in our custom models to ensure a good usability. 

### Database changes

None

### External dependencies

None

**Comment by ecraven** [comment]
This would be relevant for us too.

**Comment by ryanmerolle** [comment]
@jeremystretch If @johannwagner  details out his approach, would you be happy to assign him this issue?

**Comment by jeremystretch** [comment]
This is blocked until we come up with a new global search implementation (currently tracked under #7016).

**Comment by jeremystretch** [comment]
We're flipping this around a bit. The plan now is to introduce a dynamic registration for model search first, and then to implement an improved search engine under #7016.

**Comment by arthanson** [comment]
was already fixed and merged into feature https://github.com/netbox-community/netbox/pull/10489 so closing.
