### ISSUE TITLE
Front & Rear-Port Bulk-Import CSV-Fields swapped

### ISSUE THREAD

**Issue by hwerny** [netbox-community/netbox#8929]
### NetBox version

v3.1.9

### Python version

3.7

### Steps to Reproduce

1. Click on Front Ports / Click on Import
2. There you can see these csv-entries: device,name,type,rear_port,rear_port_position
3. Same with Rear Ports / Import: device,name,type,positions
4. So it seems the CSV-Entries where swapped.

### Expected Behavior

Use of the right Front-Ports-CSV-Entries at Front Ports and use of the right Rear-Port-CSV-Entries at Rear Ports.

### Observed Behavior

When i use the entries from Rear Ports, which should be the right ones, at Front Ports it gaves this error: Unexpected column header "positions" found.
Without "positions" this error: Required column header "rear_port" not found.

**Comment by martinum4** [comment]
Are you using the csv import or csv upload?
I tried the following with csv text import on demo.netbox.dev and it worked as intended:

Rear ports:
```
device.id,name,type,positions
1,RP1,8p8c,1
1,RP2,8p8c,1
```

Front ports
```
device.id,name,type,rear_port,rear_port_position
1,FP1,8p8c,RP1,1
1,FP2,8p8c,RP2,1
```

Results in:

![grafik](https://user-images.githubusercontent.com/18295403/159457170-691c90d2-c3ce-4029-87bc-fe2c81d90f18.png)

**Comment by jeremystretch** [comment]
The import forms are working as they should. If you need help importing pass-through ports, please start a [discussion](https://github.com/netbox-community/netbox/discussions/new).
