### ISSUE TITLE
Cannot create circuit terminations

### ISSUE THREAD

**Issue by cmcknz77** [netbox-community/netbox#8933]
### NetBox version

v3.2.0-beta1

### Python version

3.9

### Steps to Reproduce

Create Circuit
Press either "Termination - A Side" or "Termination - Z Side" buttons
Error: Page Not Found
/circuits/circuits/1/terminations/add/
The requested page does not exist
![image](https://user-images.githubusercontent.com/8886905/159407196-75edd4ff-250c-4277-a1e4-615e5a9a5a57.png)

I'm on Python 3.10

### Expected Behavior

I was expecting to be able to link my Circuit to a device

### Observed Behavior

Page Not Found
/circuits/circuits/1/terminations/add/
The requested page does not exist

**Comment by jeremystretch** [comment]
Thank you for submitting this issue, however it appears that this topic has already been raised. Please see issue #8792 for further discussion. (This has been fixed in v3.2-beta2.)
