### ISSUE TITLE
Enable webhooks for JobResults

### ISSUE THREAD

**Issue by kkthxbye-code** [netbox-community/netbox#8958]
### NetBox version

v3.1.9

### Feature type

Change to existing functionality

### Proposed functionality

Add the @extra_features('webhooks') to the JobResult model.

### Use case

When triggering Netbox scripts via. the API it would be useful to be able to send a webhook when the status changes. This would prevent the need for polling the API for scripts with longer runtime.

### Database changes

None

**Comment by kkthxbye-code** [comment]
I tried just adding `@extras_features('webhooks')` to the model, but it doesn't trigger webhooks. I'm sure there are some pre-requisites for using webhooks I'm not aware of. I wouldn't mind implementing if accepted and with a small pointer as to what is needed to make it work.

**Comment by kkthxbye-code** [comment]
Looking into this more, I guess JobResults would be to be changed to inherit from ChangeLoggedModel. Not sure how feasible that is or if it just works out of the box. The migration would make it a major change I guess.

**Comment by jeremystretch** [comment]
> I guess JobResults would be to be changed to inherit from ChangeLoggedModel

We can enable webhooks for the model separately, without having to inherit the other stuff ChangeLoggedModel provides.

**Comment by jeremystretch** [comment]
@kkthxbye-code would we want to evaluate webhook on _every_ call to `save()`, or only for jobs with a terminal status (e.g. completed or errored)? The former would provide the most flexibility, though I worry about people creating non-conditional webhooks that fire each time a job is created, executed, and completed.

**Comment by kkthxbye-code** [comment]
@jeremystretch - The original issue we were having, was that we had to poll to check for script completion when triggering scripts from external systems. So only triggering for terminal statuses would probably be fine for that use-case. However I don't think it should be an issue doing it on all saves, unless JobResults are saved multiple times during execution? A normal script run would be Pending -> Running -> Completed right?

**Comment by jeremystretch** [comment]
Right, what I mean is that each change to a job's status has to be written to the database (although it might not actually call `save()`), which could in theory trigger a webhook each time.

**Comment by jeremystretch** [comment]
I suppose for the initial implementation at least we can enable webhooks for _all_ statuses, and then constraint to only terminal statuses if needed.

**Comment by jeremystretch** [comment]
I ended up introducing two new event types, `job_start` and `job_end`, which trigger at the beginning and end of a job's execution respectively. These map to the `start()` and (new) `terminate()` methods on the `JobResult` class, which handle triggering webhooks in addition to updating the job's status.
