### ISSUE TITLE
upgrade.sh not cloning the GIT

### ISSUE THREAD

**Issue by joshuajosh59** [netbox-community/netbox#8960]
### NetBox version

v3.

### Python version

3.8

### Steps to Reproduce

sudo /opt/netbox/upgrade.sh

### Expected Behavior

run the packaged upgrade script (upgrade.sh) to perform the following actions:

- Create a Python virtual environment
- Installs all required Python packages
- Run database schema migrations
- Builds the documentation locally (for offline use)
- Aggregate static resource files on disk

### Observed Behavior

 Running command git clone --filter=blob:none --quiet git://github.com/graphql-python/graphene-django.git /tmp/pip-req-build-2563ca_i
  fatal: remote error:
    The unauthenticated git protocol on port 9418 is no longer supported.
  Please see https://github.blog/2021-09-01-improving-git-protocol-security-github/ for more information.
  error: subprocess-exited-with-error
  
  × git clone --filter=blob:none --quiet git://github.com/graphql-python/graphene-django.git /tmp/pip-req-build-2563ca_i did not run successfully.
  │ exit code: 128
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× git clone --filter=blob:none --quiet git://github.com/graphql-python/graphene-django.git /tmp/pip-req-build-2563ca_i did not run successfully.
│ exit code: 128
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by joshuajosh59** [comment]
i am thinking this is the reason -https://github.blog/2021-09-01-improving-git-protocol-security-github/

**Comment by jeremystretch** [comment]
Thank you for submitting this issue, however it appears that this topic has already been raised. Please see issue #8888 for further discussion.
