### ISSUE TITLE
Unable to create custom field of type object or multiobject via API

### ISSUE THREAD

**Issue by squintfox** [netbox-community/netbox#8976]
### NetBox version

v3.2-beta2

### Python version

3.9

### Steps to Reproduce

1. POST the following to: https://<host>/api/extras/custom-fields/
{
	"content_types": [
		"ipam.prefix"
	],
	"type": "object",
        "data_type": "object",
        "object_type": "circuits.circuit",
	"name": "circuit",
	"label": "Circuit"
}

### Expected Behavior

A new custom field should be created.

### Observed Behavior

The API returns:
{
    "object_type": [
        "Object fields must define an object type."
    ]
}

It does not matter what value you supply for object_type or if you don't specify one at all.

**Comment by squintfox** [comment]
I believe (at least in part) the issue is the the field object_type is missing from CustomFieldSerializer in /netbox/netbox/extras/api/serializers.py.  I modified this:

fields = [
            'id', 'url', 'display', 'content_types', 'type', 'data_type', 'name', 'label', 'description', 'required',
            'filter_logic', 'default', 'weight', 'validation_minimum', 'validation_maximum', 'validation_regex',
            **'object_type',** 'choices', 'created', 'last_updated',
        ]

After I restarted netbox, object_type was now shown in API GET queries for custom fields (it was not previously) and I was able to create a custom field by supplying the int id of "circuits.circuit".  Given what I've see of the API and how it handles linked objects, this doesn't seem like a complete solution, but hopefully this is helpful for someone who understands it better than I do.

**Comment by jeremystretch** [comment]
@squintfox yep, that's pretty much it. In this case, we want to make `object_type` a ContentTypeField, so that it returns a human-friendly descriptor (e.g. `"circuit.circuit"`) instead of the PK, adding the missing field was the key. Thanks for the report!
