### ISSUE TITLE
Bulk Image Uploads

### ISSUE THREAD

**Issue by ziply-nick** [netbox-community/netbox#8982]
### NetBox version

v3.1.10

### Feature type

Change to existing functionality

### Proposed functionality

The proposed feature would allow bulk uploading of multiple images to any object that supports image uploads. For example, on site objects.

### Use case

Currently, you can only upload one image at a time to a site. In our case, when we have someone visit a site, they take photos of the entire site, typically 20-30 photos at minimum. To upload all of these one by one becomes time consuming and unnecessarily repetitive. If you could select multiple files at once to upload, this would be much more user friendly.

**Comment by YellowJacket51** [comment]
I would like to have this request reopened.

**Comment by mtkirb** [comment]
I too would like to have this request reopened

**Comment by YellowJacket51** [comment]
@jeremystretch would you guys be willing to take a look at adding this in a future release?

**Comment by jeremystretch** [comment]
@mtkirb @YellowJacket51 this FR was closed because no one volunteered to own its implementation. I'm happy to re-open it if you'd like to commit to owning it.
