### ISSUE TITLE
Add site_group filter everywhere region is set

### ISSUE THREAD

**Issue by ryanmerolle** [netbox-community/netbox#8998]
### NetBox version

v3.1.10

### Feature type

Change to existing functionality

### Proposed functionality

Anywhere region currently exists as a filter, site group should exist as an option.

### Use case

Let's say I want to filter racks in datacenters, I cannot do that today.

### Database changes

N/A

### External dependencies

N/A

**Comment by minitriga** [comment]
I could only find the filter not applied to racks and rack reservation filters. I have added them. Let me know if i'm missing any others.
