### ISSUE TITLE
Allow creating IP range with 1 IP

### ISSUE THREAD

**Issue by PTarakanov** [netbox-community/netbox#9005]
### NetBox version

v3.1.2

### Python version

3.9

### Steps to Reproduce

1. Create IP range with same start and end address

### Expected Behavior

Create new IP range with one IP

### Observed Behavior

Error: Ending address must be lower than the starting address

By the way, think that message should be "Ending address must be **higher** than the starting address"

**Comment by jeremystretch** [comment]
> Create new IP range with one IP

As a range by definition requires two values, this is of course not allowed. You can instead create a single IP address.
