### ISSUE TITLE
Add new types of cable for breakout

### ISSUE THREAD

**Issue by ravenrs** [netbox-community/netbox#9011]
### NetBox version

v3.1.5

### Feature type

Data model extension

### Proposed functionality

Hello.
As NB doesn't have functionality to indicate connection through breakout, please add more cable:
DAC breakout
AOC breakout
MTPtoLC MM
MTPtoLC SM
In current version you can't realise that you are using breakout cable without comparing speed of links, and it's complicated.

### Use case

By adding extra types for breakout you can find that you using breakout just checking cable, without additional checks.

**Comment by jeremystretch** [comment]
This has been discussed in several issues previously; please reference those discussions for why this is not tenable.
