### ISSUE TITLE
Add Aruba and Generic stacking port choices

### ISSUE THREAD

**Issue by cmcknz77** [netbox-community/netbox#9015]
### NetBox version

v3.2.0-beta2

### Feature type

Change to existing functionality

### Proposed functionality

Currently NetBox already supports many Cisco stacking interface types but none for Aruba or other existing manuacturer switches. 

For reference:
The Aruba 2500 and 2900M series of switches use a different stacking cable to the Aruba 3800&3810M series of switches 
https://buy.hpe.com/uk/en/options/cables-cable-kits/stacking-cables/stacking-cables/hpe-switch-stacking-cables/p/4179896

https://support.hpe.com/resource3/docDisplay/pdfjs/web/viewer.html?file=%2Fhpesc%2Fpublic%2Fapi%2Fdocument%2Fa00015161en_us%3FdocVersion%3D6.0&locale=en-US&rangeChunkSize=256000&disableAutoFetch=false&disableCache=false&version=20220308085252#_OPENTOPIC_TOC_PROCESSING_d95e10681

I propose adding interface types for Aruba 2xx0 and 38x0 switch types as well as a generic that could be used for manufacturers that are currently unlisted.

### Use case

New interfaces types to model connections between member switches of stacks (virtual chassis).

### Database changes

I don't believe that database changes are required. I added the 6 lines of code to my "choices.py" and although it took a little while for netbox to restart, that appears to have done the trick.

### External dependencies

None

**Comment by jeremystretch** [comment]
What are the exact name(s) being proposed? We will only add to NetBox proprietary connector types that have been well-defined by their manufacturers. (Using the name of a switch series in place of the connector name is not sufficient.)

**Comment by cmcknz77** [comment]
Hi Jeremy.
Sorry for jumping the gun with the PR.
As far as I understand those suggested are the connector names as defined by the manufacturer Aruba/HPE as shown here: https://buy.hpe.com/uk/en/options/cables-cable-kits/stacking-cables/stacking-cables/hpe-switch-stacking-cables/p/4179896

I have not been able to find any other description for the two connector types but they are the ones used for all of the Aruba & HPE(formerly HP Procurve) switches that use proprietary connectors to stack. I'll ask HPE to clarify.

**Comment by cmcknz77** [comment]
![image](https://user-images.githubusercontent.com/8886905/162036178-0ac1e06b-d927-4d2d-ba7f-ae89de56716a.png)

@jeremystretch  Can't get more clear than the attached. Aruba/HPE (formally HP Procurve) have no name for the proprietary stacking connector types used for the stacking modules for the 2920,2930M,3800 and 3810M series' of switches.

**Comment by cmcknz77** [comment]
![image](https://user-images.githubusercontent.com/8886905/187558440-648167b4-3861-4f8a-9804-cdd061e46890.png)

**Comment by cmcknz77** [comment]
@DanSheps @jeremystretch Hi gents, I understand that you are busy but I need to move this forward and would respectfully request any advise that you have that would allow me to do so. What do I do? Copy the contents to a new issue? If so, by my understanding we're still at the same impasse so how do we resolve it?
Thanks for your momentary attention to this matter.
Clay

**Comment by jeremystretch** [comment]
@cmcknz77 As I noted above, this won't be accepted without a canonical name for the interface type from the manufacturer. If you'd like to modify your NetBox instance to add a fabricated interface type you are free to do so, but we are unable to add any types to the core product that are not backed by an authoritative definition.
