### ISSUE TITLE
Unable to install Netbox v3.2-beta2 from a system without SSH keys added to Github

### ISSUE THREAD

**Issue by robduffy2010** [netbox-community/netbox#9017]
### NetBox version

v3.2-beta2

### Python version

3.7

### Steps to Reproduce

1. Clone the Netbox repo and checkout to 3.2-beta2 
2. Install the requirements

### Expected Behavior

The requirements install should complete without any errors. 

### Observed Behavior

The requirements install fails due to an unauthenticated git clone.  Github stopped supporting this on March 15. 

I realise this was just done temporarily while waiting for a graphene-django fix.  It's not clear how long the fix will take to be released, so in the meantime it might be best to use HTTPS here instead.  Let me know if you'd like me to create a PR.  

https://github.com/netbox-community/netbox/blob/v3.2-beta2/requirements.txt#L17

```
#9 27.63 Collecting git+git://github.com/graphql-python/graphene-django.git@v2 (from -r /opt/netbox/requirements.txt (line 17))
#9 27.64   Cloning git://github.com/graphql-python/graphene-django.git (to revision v2) to /tmp/pip-req-build-fmvxpe1o
#9 27.64   Running command git clone --filter=blob:none --quiet git://github.com/graphql-python/graphene-django.git /tmp/pip-req-build-fmvxpe1o
#9 27.89   fatal: remote error:
#9 27.89     The unauthenticated git protocol on port 9418 is no longer supported.
#9 27.89   Please see https://github.blog/2021-09-01-improving-git-protocol-security-github/ for more information.
#9 27.90   error: subprocess-exited-with-error
#9 27.90   
#9 27.90   × git clone --filter=blob:none --quiet git://github.com/graphql-python/graphene-django.git /tmp/pip-req-build-fmvxpe1o did not run successfully.
#9 27.90   │ exit code: 128
#9 27.90   ╰─> See above for output.
```

**Comment by kkthxbye-code** [comment]
Checkout feature instead, it's already fixed there. Or wait until next week when 3.2 is released.

**Comment by robduffy2010** [comment]
Will do.  Thanks for the quick response.

**Comment by peterbaumert** [comment]
Or change git+git to git+https in requirements.txt
