### ISSUE TITLE
Reports - add return output similar to scripts function to reports

### ISSUE THREAD

**Issue by ITJamie** [netbox-community/netbox#9027]
### NetBox version

v3.1.0

### Feature type

Change to existing functionality

### Proposed functionality

The scripts function has a useful feature that allows returning of data as part of the script. 
I would like to see this function duplicated into the reports feature.

UI changes: adding output section after table of messages
Code changes: add a serialiser to the reports function and parse report job return data.

### Use case

This would allow for return of data eg csv data. or for json data about a set of objects in the report

The scripts example here actually does show using this to make a csv (https://demo.netbox.dev/static/docs/customization/custom-scripts/#example)

This would allow the creation of reports that give an easy to use "export" of csv or json or yaml for consumption outside of netbox

**Comment by ITJamie** [comment]
Still valid

**Comment by kkthxbye-code** [comment]
Please read https://github.com/netbox-community/netbox/blob/master/CONTRIBUTING.md#issue-lifecycle
