### ISSUE TITLE
Transactional APIs

### ISSUE THREAD

**Issue by jeremyrambo** [netbox-community/netbox#9030]
### NetBox version

v3.1.9

### Feature type

New functionality

### Proposed functionality

I would like the ability to BEGIN a transaction (think DB transaction) before I may a series of API calls.  Then when I am done with one more API calls I would like to COMMIT that transaction or ROLLBACK the transaction depending on the response from each request. 

The BEGIN would return a unique transaction ID I would retain; I would then use this ID to commit or rollback the API calls I made.

### Use case

It allows uses to make a series of API calls as if they are occurring under a single call that can be reverted.

**Comment by jeremystretch** [comment]
Thank you for your interest in extending NetBox. Unfortunately, the information you have provided does not constitute an actionable feature request. Per our [contributing guide](https://github.com/netbox-community/netbox/blob/develop/CONTRIBUTING.md), a feature request must include a thorough description of the proposed functionality, including any database changes, new views or API endpoints, and so on. It must also include a detailed use case justifying its implementation. If you would like to elaborate on your proposal, please modify your post above. If sufficient detail is not added, this issue will be closed.

**Comment by jeremystretch** [comment]
Closing as there has been no further reply from OP. If this is something you'd still like to pursue, I invite you to start a [discussion](https://github.com/netbox-community/netbox/discussions/new) to engage with other community members and discuss potential avenues toward implementation. Once sufficient detail has been gathered, you are welcome to request that this FR be re-opened, or open a new FR.
