### ISSUE TITLE
Mapping between used Prefixes and IP Addresses availability

### ISSUE THREAD

**Issue by VictorPetrescu** [netbox-community/netbox#9032]
### NetBox version

v3.1.10

### Feature type

New functionality

### Proposed functionality

You should not be allowed to allocate an IP Addresses from the /30 child Prefix. Or even to mark them as used in the IP Addresses View.

### Use case

[](https://user-images.githubusercontent.com/11586456/161392652-c0c63d8b-a7e3-481f-bc2e-604b2c17d0df.png)Prefix: 192.168.100.0/24
Child Prefix 1: 192.168.100.32/30 (Marked as 100% Utilized)
Child Prefix 2: 192.168.100.36/30 (Marked as 100% Utilized)
Child Prefix 3: 192.168.100.40/30 (Marked as 100% Utilized)

Under the IP Addresses Section in the 192.168.100.0/24 Prefix I should not be allowed to alocate an IP Address from none of the 3 Child Prefixes, or at least to see them used, not available, like in the picture.

192.168.100.34 says is available, and I could add 192.168.100.33/32 and 192.168.100.37/32, even though there part of a fully utilized prefix.

![Screenshot_98](https://user-images.githubusercontent.com/11586456/161742508-777a7e61-0076-4d5c-beb6-e7195df8b371.png)

Also in the IP Addresses Section from the Child Prefix (192.168.100.32/30) there are still Available IPs.

Let's say I give /30 to a customer 1...I have to know that when I allocate an IP Address to another customer 2, I don't use one from the range given to customer 1. 

Thank you.

**Comment by jeremystretch** [comment]
> You should not be allowed to allocate an IP Addresses from the /30 child Prefix. Or even to mark them as used in the IP Addresses View.

Why would this not be allowed? They are valid IP addresses just like any other.

**Comment by jeremystretch** [comment]
Closing due to lack of response.
