### ISSUE TITLE
Rack Reservations View - Highlight the current reservation in the rack view

### ISSUE THREAD

**Issue by ITJamie** [netbox-community/netbox#9035]
### NetBox version

v3.1.10

### Feature type

New functionality

### Proposed functionality

When viewing a Rack Reservation it would be nice if the colours used were brighter or different than other reservations in the same rack. 

### Use case

Making the reservation view more accessible by making the current page reservation stand out on the rack diagrams

**Comment by jeremystretch** [comment]
This is one of several similar FRs that all rely on getting #4434 knocked out.
