### ISSUE TITLE
Remove legacy contact fields from provider model

### ISSUE THREAD

**Issue by ryanmerolle** [netbox-community/netbox#9046]
### NetBox version

v3.2.0

### Feature type

Change to existing functionality

### Proposed functionality

Remove legacy contact fields from provider model:

- Customer Portal
- NOC Contact
- Admin Contact

### Use case

Currently there is the above contact text fields and a contact association field.

### Database changes

Requires a migration to remove the contact fields from providers.

**Comment by jeremystretch** [comment]
Blocked by #8234

**Comment by jeremystretch** [comment]
Disregard; #8234 has already been addressed.
