### ISSUE TITLE
Allow more than 1 Account per provider

### ISSUE THREAD

**Issue by ryanmerolle** [netbox-community/netbox#9047]
### NetBox version

v3.2.0

### Feature type

New functionality

### Proposed functionality

Create an account model allowing more than one account per provider.  The model could include:
- Account Name (where to track where account numbers result due to regional entities being different IE Network Client UK vs Network Client US for only billing/AP purposes) - mandatory
- Account ID- mandatory
- Account Description ( add any additional useful context) - optional

### Use case

Sometimes providers require a different account and circuit id per region, sometimes your firm may have different billed entities per region for AP purposes and the provider cannot link the accounts all together, etc

**Comment by bryanward-net** [comment]
I would ask for the ability to relate "Contact" objects to accounts, as each account may have a different admin/technical/stakeholder.  An arbitrary number of Contacts should be allowed to relate to an Account (as there may be multiple stakeholders who need to be notified for outages, or an escalation path for technical contacts).  The relation of a Contact to an Account should include a Contact Type (i.e. Billing, Technical, Landlord, etc.)

And just to explicitly say it, Circuits should then be related to an Account object instead of directly to a Provider.

**Comment by ryanmerolle** [comment]
I am not against a new account model because that does model real world usage.  The challenge with this is the migrations and impact to users to remove the provider to circuit direct relationship.

**Comment by ryanmerolle** [comment]
might be nice to add to 3.5

**Comment by jbakklund** [comment]
Ref @bryanward-net
> And just to explicitly say it, Circuits should then be related to an Account object instead of directly to a Provider.

The Rack model could use a similar relation.

**Comment by kkthxbye-code** [comment]
@jbakklund - There's no relation between racks and providers. If you meant in a general sense, racks already have tenant group -> tenant.

**Comment by ryanmerolle** [comment]
I think @jbakklund is talking about changing the rack model to relate to providers given some providers provide colocation services and telecom services.  Its sort of a pain to duplicate data and leverage tenants or the facility field to signify a provider/landlord.

It is also a pain point with the netbox circuit maintenance plugin given it can be used to parse colocation provider maintenance that could impact specific site, and right now there is no easy way to model that relationship besides leveraging tenants where it does not always make sense.

Regardless, @jbakklund that would be a separate well thought out feature request.

**Comment by ITJamie** [comment]
+1 to @ jbakklund's request.  
(offtopic, some additional context)
Another example is that we may have racks in a cage in a DC. That cage is directly assigned to us and billed to us by the DC. 
We may also have racks in a cage owned by an ISP or some other company in the same DC. In this case a tenant is still not exactly correct, from an operations POV etc its a completely different account/contacts/access process for those racks. than the rest of the objects in that site/dc

**Comment by ryanmerolle** [comment]
> +1 to @ jbakklund's request.
> (offtopic, some additional context)
> Another example is that we may have racks in a cage in a DC. That cage is directly assigned to us and billed to us by the DC.
> We may also have racks in a cage owned by an ISP or some other company in the same DC. In this case a tenant is still not exactly correct, from an operations POV etc its a completely different account/contacts/access process for those racks. than the rest of the objects in that site/dc

Another off topic item.  I’m not saying this is not necessarily needed or useful, but I’m say this is outside of the scope of this accepted FR.  Please submit a Feature Request to address the problem you touched on.
