### ISSUE TITLE
Missing device field when editing inventory item

### ISSUE THREAD

**Issue by dsl81** [netbox-community/netbox#9055]
### NetBox version

v3.2.0

### Python version

3.9

### Steps to Reproduce

1. Click Edit button on any inventory item.

### Expected Behavior

Device field should exist with choice of devices.
![device_field](https://user-images.githubusercontent.com/3961842/161974008-f84f5e8b-3e17-4ce3-994f-303e6b288faa.png)

### Observed Behavior

Device field is not available.
![no_device_field](https://user-images.githubusercontent.com/3961842/161974057-23f0ac75-4318-4101-9daf-8f192f20e19e.png)

There is no GUI way to change device for inventory item.

**Comment by jeremystretch** [comment]
Thank you for opening a bug report. Unfortunately, the information you have provided is not sufficient for someone else to attempt to reproduce the reported behavior. Remember, each bug report must include detailed steps that someone else can follow on a clean, empty NetBox installation to reproduce the exact problem you're experiencing. These instructions should include the creation of any involved objects, any configuration changes, and complete accounting of the actions being taken. Also be sure that your report does not reference data on the public NetBox demo, as that is subject to change at any time by an outside party and cannot be relied upon for bug reports.

**Comment by dsl81** [comment]
You mean that whole procedure of creating inventory item should be written starting from creating manufacturer of each device?

**Comment by DanSheps** [comment]
> You mean that whole procedure of creating inventory item should be written starting from creating manufacturer of each device?

Please at least start from creation of device, however going back to Site/Manufacturer is helpful for us

**Comment by quixoten** [comment]
This looks like it might be a regression (is that the right way to say it) of https://github.com/netbox-community/netbox/pull/3818. I don't see those changes in the [v3.2.0 version](https://github.com/netbox-community/netbox/blob/develop/netbox/dcim/forms/models.py#L1364-L1404) of the code. Maybe this was intentionally left out?

**Comment by DanSheps** [comment]
For reference, to recreate:

* Create site (Site A)
* Create Manufacturer (Cisco)
* Create Device Type (ISR-4331-K9)
* Create Device Role (Router)
* Create Device (9055-test)
* Create inventory item on device 9055-test (Inventory Item Test)
* Edit inventory item "Inventory Item Test"

**Comment by DanSheps** [comment]
> This looks like it might be a regression (is that the right way to say it) of #3818. I don't see those changes in the [v3.2.0 version](https://github.com/netbox-community/netbox/blob/v3.2.0/netbox/dcim/forms/models.py#L1364-L1404) of the code. Maybe this was intentionally left out?

You are correct

**Comment by DanSheps** [comment]
@jeremystretch Do we want to disable moving for now, as there are now other considerations (the fact that other components can be tied to the inventoryitem) or do we want to fix this and still allow moving?  I got a patch disabling (also have the partial patch for moving, just need to adjust logic to null any inventory tie-ins)

**Comment by dsl81** [comment]
Moving inventory items is essential for tracking things like SFPs. Disabling it will brake accounting of such items for us. If we have to recreate items we will lose history for them. Not to mention that it will be very inconvenient. Besides moving is possible from api, so i hope it will not brake anything.
