### ISSUE TITLE
Add fields to components filter

### ISSUE THREAD

**Issue by mmfreitas** [netbox-community/netbox#9060]
### NetBox version

v3.2.0

### Feature type

Change to existing functionality

### Proposed functionality

Currently we have the following component filters:

![image](https://user-images.githubusercontent.com/91552302/162026716-c52dc82c-6484-4a79-8d40-dd00f449f331.png)

I have noticed that I can't easily filter device types and module types when I want to know if they have device bays or module bays configured. I've been using tags to keep track of this, but I think this should be on the filters tab, so I would propose the addition of the following filter choices:

- Has Device Bays
- Has Module Bays
- Has Inventory Items

### Use case

To be able to filter for components that currently are not possible.

### Database changes

None.

**Comment by minitriga** [comment]
All done
