### ISSUE TITLE
For module components, include helptext under name with variable substitutions

### ISSUE THREAD

**Issue by DanSheps** [netbox-community/netbox#9062]
### NetBox version

3.2.0

### Feature type

Change to existing functionality

### Proposed functionality

Include help_text under the "Name" field, which describes the current (and any future) substitutions that can be made.

### Use case

Currently, you have to go to the "Module" model help to get the allowable substitution (it is not included on the components help) for {module}.  It isn't the most intuitive to find, unfortunately.

### Database changes

None

### External dependencies

None

**Comment by jeremystretch** [comment]
@DanSheps are you still working on this?

**Comment by DanSheps** [comment]
I will try and get to this tonight, sorry, been slammed lately
