### ISSUE TITLE
Add RJ-45 Connector type for Rear ports on patch panels

### ISSUE THREAD

**Issue by cyr0nk0r** [netbox-community/netbox#9066]
### NetBox version

v3.2.0

### Feature type

Change to existing functionality

### Proposed functionality

Currently, there are several different Copper connector types when adding 'Rear' port components to a device type. (110 punch, BNC, F Connector, etc.)

Please add the "RJ-45" connector type to this list.

### Use case

Some copper patch panels are 'pass-through' patch panels that have a female/female couplers for each port on the panel allowing someone to take pre-made RJ-45 patch cables and plug them into both sides of the patch panel to make a connection. 

### Database changes

Add RJ-45 connector type to list of connector types in the rear port template 'Type' dropdown list.

### External dependencies

None

**Comment by martinum4** [comment]
You can already add 8p8c-connectors to front- and backports

**Comment by jeremystretch** [comment]
As commented above, these are 8P8C ports. RJ45 is technically a specific wiring scheme for the 8P8C form factor.
