### ISSUE TITLE
Validation of IP Addresses when of type network or broadcast

### ISSUE THREAD

**Issue by falz** [netbox-community/netbox#9068]
### NetBox version

v3.1.11

### Feature type

New functionality

### Proposed functionality

One of the many ways we use netbox is to assign IP addresses to device interfaces, which are used to push config changes to device.

Currently, one can add any ip address, including the network or broadcast address, to an interface. This is not a valid config from any devices standpoint. There are some obvious exceptions to this:

* /31 - rfc3021
* /32 - In our case, we set these to Role Loopback
* /127 - rfc6164

Are there other use cases other than above where an IP object on a broadcast or network address should be added? 

I would propose that some sort of validation happens when 'invalid' IP addresses are added to netbox. It's not entirely clear what the best validation here is but a few possibilities would be:

* don't accept the IP
* throw a big scary warning, but accept the IP

One could also consider a config knob to disable this sanity check and revert to current behavour.

It sounds like there may be a way to handle this via a custom validator, but it seems to be enough of a common issue that it seems worth discussion built in functionality. 

There is some discussion about this in [this slack thread.](https://netdev-community.slack.com/archives/C01P0FRSXRV/p1649339405458799)

### Use case

Should help with user friendliness of end users using netbox, preventing humans clumsy entering invalid data.

**Comment by DanSheps** [comment]
I think this would be best blocked until we get #7845 implemented

**Comment by jeremystretch** [comment]
@DanSheps I don't think this has any dependency on #7845, since the IP address object has all the necessary information locally.

**Comment by decoupca** [comment]
I'll take this one

**Comment by andretlemos** [comment]
I had a problem with this update, my ipv6 address /127 was not allowed because of broadcast, I downgrade to version 3.5.1.
