### ISSUE TITLE
Allow plugins to inject top-level navigation menu items

### ISSUE THREAD

**Issue by jeremystretch** [netbox-community/netbox#9071]
### NetBox version

v3.2.0

### Feature type

Change to existing functionality

### Proposed functionality

Currently, plugins can define menu items only under the "Plugins" header within the navigation menu. Several plugin authors have proposed the ability for a plugin to "register" its own top-level section in the menu.

IMO the simplest approach would be to allow a plugin to define a menu heading with a title and icon. If defined, its menu items will appear there; if not, they will appear under the general "Plugins" heading.

We'd also want to give some thought to influencing the ordering of top-level menu items; assigning a "weight" to each item might suffice.

### Use case

Greater visibility for plugin functions; control over order of placement (potentially?)

**Comment by peteeckel** [comment]
I thought I'd revisit this now that a couple of months have passed and I implemented our plugin at two customers and in my own environment.

A complaint that I hear quite often is that access to plugins is somewhat hidden from view, which tends to confuse casual users. So I think the option of optionally "promoting" a plugin to be a first class menu entry is still on the wish list.

**Comment by abhi1693** [comment]
There should also be the ability to add our plugin menu under the existing headers like `Virtualization` or `Devices` etc. I have a few plugins that would be much suited under the existing ones rather than creating them as suggested in the description.
