### ISSUE TITLE
Allow plugins to inject sub-tabs on object detail views

### ISSUE THREAD

**Issue by jeremystretch** [netbox-community/netbox#9072]
### NetBox version

v3.2.0

### Feature type

New functionality

### Proposed functionality

Object detail views typically have several tabs: the primary object details, the object change log, and the journal, for example. Some objects have additional tabs. This proposal (borne from discussion in WG8333) seeks to allow plugins to inject arbitrary additional tabs for particular objects.

The exact implementation is open for discussion, but it seems reasonable to assume that a plugin could register one or more (name, view) tuples to specific NetBox models identified by their app label and model name.

One likely blocker here is that we'll need to come up with a way to programmatically declare sub-tabs under a view, but this would serve the existing changelog & journal views as well.

### Use case

Provides a greater degree of integration with core NetBox models and more convenient navigation for the user.

**Comment by kkthxbye-code** [comment]
Such a good addition to the plugin API!

**Comment by jeremystretch** [comment]
Not only that, it also allows us to clean up quite a bit of cruft and redundancy internally!
