### ISSUE TITLE
Designate an exception to gracefully abort under create/edit/delete views

### ISSUE THREAD

**Issue by jeremystretch** [netbox-community/netbox#9075]
### NetBox version

v3.2.0

### Feature type

New functionality

### Proposed functionality

The ultimate goal of this proposal is to support the following workflow:

1. User attempts to create/edit/delete an object in NetBox using one of the standard UI views or REST API endpoints
2. The `pre_save` or `pre_delete` signal is emitted and caught by a receiver interested in the object
3. The receiver determines the operation should not be allowed (example: a plugin enforcing some arbitrary logic)
4. The receiver raises `AbortAction` exception (actual name TBD)
5. The view catches `AbortAction` and returns gracefully without completing the action

There are some implementation details still to iron out, but this should generally parallel the flow we have in place today to enforce permission constraints.

### Use case

This will allow a plugin to participate in the standard CRUD workflows and disrupt them where necessary (e.g. to enforce supplementary validation) and abort the gracefully.

**Comment by sdktr** [comment]
Even more plugin hooks, really nice work!
