### ISSUE TITLE
vlan groups - add an option for "excluded" vlan id's to Child VLANs setting

### ISSUE THREAD

**Issue by ITJamie** [netbox-community/netbox#9083]
### NetBox version

v3.2.0

### Feature type

Change to existing functionality

### Proposed functionality

add a third field, to contain a list of comma seperated vlan id's that should be skipped / not allowed in a vlan group.
add logic so that vlan isnt accepted into the group and not offered as the "next available vlan"

### Use case

there are some vlan id's we would not like to be shown as "available" for certain vlan groups. (eg ciscos pre-resevered vlans 1002 – 1005 )

other examples may be that a certain vlan was in use long before that "range" was assigned a use and needs to be excluded from the list of "available" vlans

**Comment by jeremystretch** [comment]
I'm going to close this in favor of #9627, which seeks to provide the same functionality, but moves the model to a single ArrayField defining valid VLAN IDs.
