### ISSUE TITLE
Add ability to reserve either 'front' or 'rear' of rack units

### ISSUE THREAD

**Issue by cyr0nk0r** [netbox-community/netbox#9090]
### NetBox version

v3.2.0

### Feature type

New functionality

### Proposed functionality

When adding device reservations for a rack there is no distinction between reserving the front U of the rack, or the rear U of the rack. Not all devices are full depth.

Modify existing reservation mechanism to have the 'Rack Face' and 'Full Depth' options to allow someone to reserve either the front or rear of the rack, and either the full depth or not.

### Use case

If I were to have a cable manager on the front of a rack this device is not full depth. This would leave plenty of room in the rear of the rack to mount something else. Another cable manager perhaps, or a patch panel.

This feature would allow someone to have a non full-depth device occupying rack unit 40 in the front, while reserving rack unit 40 in the rear for another non full-depth device.

**Comment by opericgithub** [comment]
bump.
can we have this feature implemented?
