### ISSUE TITLE
Allow ObjectChildrenView to be used by plugins

### ISSUE THREAD

**Issue by hagbarddenstore** [netbox-community/netbox#9092]
### NetBox version

v3.2.0

### Feature type

Change to existing functionality

### Proposed functionality

Officially allow plugins to use the ObjectChildrenView class.

Decide that it's ok to be used and document how to use it in the plugin development documentation.

### Use case

To be able to create models in plugins that have child models (Interfaces to a Firewall, Routes for a Router, etc.) and make them look and feel like any other child models do in "native" NetBox.

Reduces the amount of code that needs to be written for something that "native" NetBox already solves.

### Database changes

None

### External dependencies

None

**Comment by joonajohn** [comment]
Child themes allow you to customize your theme without affecting the parent theme and to keep those modifications even if you update the parent theme. You can generate a child theme manually with a bit of coding or with a plugin. For more detail also see [https://github.com/netbox-community/netbox/issues/9092](https://github.com/netbox-community/)[10eloto](https://10eloto.com/)[netbox/issues/9092](https://github.com/netbox-community/netbox/issues/9092)

**Comment by maximumG** [comment]
I must admit that I already used this `ObjectChildrenView ` class even if not part of the official plugin API. I can take care of the documentation if you planned to make it public.
