### ISSUE TITLE
Add additional options to 'rear ports', 'front ports', and 'power' types

### ISSUE THREAD

**Issue by cyr0nk0r** [netbox-community/netbox#9098]
### NetBox version

v3.2.0

### Feature type

Change to existing functionality

### Proposed functionality

Type 'other' is available for interfaces, but no such generalized option exists for 'front port', 'rear port', or 'power' connector types.
A list of every single possible connector type for these connections would not be feasible, so unless users have the ability to add options themselves (which is outside the scope of this request) the next best option is to add an 'other' type to each of those options drop down lists.

### Use case

There are many more connector types available than what is listed for rear port, front port, and power type connections. Adding an 'other' option to these drop down lists would allow users to select something if their particular connector is not listed, rather than not filling in the data at all.

**Comment by jeremystretch** [comment]
> A list of every single possible connector type for these connections would not be feasible

Sure it is. We see proposals for new types occasionally, but what exists in NetBox today is fairly exhaustive. There is of course a finite set of such hardware in common use, and this approach has enabled us to compile the massive community-sourced [device type library](https://github.com/netbox-community/devicetype-library).

Proposals to add real, well-defined component types that have not yet been added are welcomed and appreciated. Still, adding "other" as a catch-all is fine too.

**Comment by cyr0nk0r** [comment]
How did https://github.com/netbox-community/netbox/issues/9192 make it into 3.2.2 before this one?

**Comment by kkthxbye-code** [comment]
@cyr0nk0r if you hover over the `status: needs owner` label you will see the description:

>This issue is tentatively accepted pending a volunteer committed to its implementation

A volunteer implemented the suggested change in the issue you linked. That's why it was added.

**Comment by bluikko** [comment]
Seems like a very simple change, hope I got it right in the PR.
