### ISSUE TITLE
Add additional phone fields for 'contacts'

### ISSUE THREAD

**Issue by cyr0nk0r** [netbox-community/netbox#9103]
### NetBox version

v3.2.0

### Feature type

Change to existing functionality

### Proposed functionality

Currently when adding a 'contact' there is only 1 phone number field available. However, contacts may have alternate phone numbers. Please add the ability to have more than just 1 phone number for a contact.

Specifically, it would be nice to include phone fields such as:
Desk Number
Extension
Cell Phone
Pager and/or Fax (you never know sometimes)

### Use case

Let's say I have a contact that has both a desk number as well as a cell phone. There is no way to notate that in the existing fields.

**Comment by evatych** [comment]
I'd like to add multiple phones too.
