### ISSUE TITLE
Active/Inactive for contacts

### ISSUE THREAD

**Issue by cyr0nk0r** [netbox-community/netbox#9105]
### NetBox version

v3.2.0

### Feature type

New functionality

### Proposed functionality

Please add the ability to assign contacts to have a status. Initial options would include:
Active, Inactive
Possibly more if you have other ideas.

### Use case

Let's say I have rep for a particular software. He is a sales engineer and his contact information is listed in netbox. Now this person moves to a different role within the company and would then become an inactive contact for us, but we may still want to keep his contact information in netbox to refer to should we ever need to reach them again in the future for something.

**Comment by jeremystretch** [comment]
In such a scenario, you can just remove any assignments for the contact while keeping the contact itself in the database.

**Comment by cyr0nk0r** [comment]
If I remove assignments (EX: group) then I lose visibility into what company or contact group that contact is for. I end up with lots of rouge contacts with little context on what company they represent.
Allowing a contact to be set as 'inactive' for a group gives me the flexibility to keep all information for this contact grouped with other contacts that work at the same company, while letting me know they are no longer a useful person to reach out to immediately, but perhaps a call of last resort if my 'active' contacts aren't responsive.
Just a way to track a lifecycle of interactions with different people within an organization I suppose.

**Comment by jeremystretch** [comment]
It occurs to me that we already have an "inactive" priority available to the contact assignment, which should serve your use case quite well.

**Comment by jeremystretch** [comment]
Going to close this out as a solution has been identified and there's been no further discussion.
