### ISSUE TITLE
Markdown syntax not working correctly within comment fields

### ISSUE THREAD

**Issue by cyr0nk0r** [netbox-community/netbox#9108]
### NetBox version

v3.2.0

### Python version

3.8

### Steps to Reproduce

1. Navigate to any object that has a 'comments' field.
2. Attempt to create a URL using angle brackets < >.
3. Click save.

### Expected Behavior

Netbox should turn the text within the angle brackets into a clickable URL.

### Observed Behavior

Text contained within the angle brackets completely disappears after clicking save.
![1](https://user-images.githubusercontent.com/77940332/162644205-24ec92db-d160-4c81-b3d6-36af76436c57.PNG)
![2](https://user-images.githubusercontent.com/77940332/162644206-5debb1bd-7bce-42df-a9bf-d10ea1d9ebd4.PNG)
![3](https://user-images.githubusercontent.com/77940332/162644207-1be90862-01f1-44cd-9621-af0a649b2122.PNG)

**Comment by bogdancordos** [comment]
The error states above is due to the missing "mailto:" tag `[fake@example](mailto:fake@example.com)`
