### ISSUE TITLE
Filtering for "status" not working in GraphQL

### ISSUE THREAD

**Issue by v0tti** [netbox-community/netbox#9109]
### NetBox version

v3.1.10

### Python version

3.9

### Steps to Reproduce

Execute a GraphQL query filtering for a specific status.

For example query the IP Address List or the Device List:
```
{
  ip_address_list(status: "DHCP") {
    status
  }
  device_list(status: "ACTIVE") {
    status
  }
}
```

### Expected Behavior

I would expect the query to only return IP Addresses with the status "DHCP" and Devices with the status "ACTIVE".

### Observed Behavior

IP Addresses and Devices with all statuses are returned. The filter seems to have no effect.

**Comment by jeremystretch** [comment]
GraphQL uses the same filter sets as the UI and REST API; you need to reference the actual value of the field rather than the equivalent GraphQL constant. For example:

```
{
  device_list(status: "active") {
    status
  }
}
```

**Comment by v0tti** [comment]
Thank you, it works now. However, it is not very intuitive for me.
