### ISSUE TITLE
Searching 'front ports' or 'rear ports' results in an attempt to rename

### ISSUE THREAD

**Issue by cyr0nk0r** [netbox-community/netbox#9113]
### NetBox version

v3.2.0

### Python version

3.8

### Steps to Reproduce

1) Go to Demo site
2) click on a device that has front ports (Ex: any of the patch panels)
3) click on the front ports tab
4) attempt to search using the 'quick search'
5) if you type 14 to try and quick search for port 14 nothing happens
6) if you type 14 and hit 'enter' you are taken to a 'rename' page where netbox wants to rename 0 ports.

### Expected Behavior

Quick search for front ports should filter results like it does when quick searching 'contacts'

### Observed Behavior

When clicking on the 'front ports' or 'rear ports' tabs from within a device the above describe bug manifests. 
If you attempt to search via navigating directly to the 'front ports' or 'rear ports' page under 'device components' then the quick search doesn't do anything at all. It doesn't filter, but it also doesn't attempt to rename a port after hitting enter.

**Comment by jeremystretch** [comment]
Thank you for submitting this issue, however it appears that this topic has already been raised. Please see issue #9061 for further discussion.

**Comment by cyr0nk0r** [comment]
9061 is about filtering, not quick search. These are 2 separate issues.
9061 also doesn't mention the fact that hitting 'enter' on the quick search results in an attempt to rename an object.
