### ISSUE TITLE
Mention that directly upgrading from <2.11 to >3.0 is not supported

### ISSUE THREAD

**Issue by timon-michel-scopevisio** [netbox-community/netbox#9120]
### Change Type

Addition

### Area

Installation instructions

### Proposed Changes

Title says it all.
Would be very helpful to know, i just screwed up a database because of not knowing this.

**Comment by jeremystretch** [comment]
The first line of the [upgrade instructions](https://netbox.readthedocs.io/en/stable/installation/upgrading/) reads:

> Prior to upgrading your NetBox instance, be sure to carefully review all [release notes](https://netbox.readthedocs.io/en/stable/release-notes/) that have been published since your current version was released.

This link leads you to the [release notes for v3.0](https://netbox.readthedocs.io/en/stable/release-notes/version-3.0/#v300-2021-08-30), which starts with the following warning:

> Upgrading an existing NetBox deployment to version 3.0 **must** be done from version 2.11.0 or later. If attempting to upgrade a deployment of NetBox v2.10 or earlier, first upgrade to a NetBox v2.11 release, and then upgrade from v2.11 to v3.0.

I'm afraid your experience highlights the importance of consulting the release notes before beginning an upgrade.

**Comment by timon-michel-scopevisio** [comment]
I've read the release notes and it's not there: https://netbox.readthedocs.io/en/stable/release-notes/

You can only find it, if you read whole release notes, which is very, very time consuming.

I agree with you that the information is somewhere, but it is not intuitive. Why make it that hard to find?

**Comment by ryanmerolle** [comment]
> I've read the release notes and it's not there: https://netbox.readthedocs.io/en/stable/release-notes/

Its mention in the release notes for 3.0.0.  You mentioned you read  the release-notes section, but you missed it at the top of the [release-notes for 3.0.0?](https://github.com/netbox-community/netbox/releases/tag/v3.0.0)  Here is the blurb:

> WARNING: Upgrading an existing NetBox deployment to version 3.0 must be done from version 2.11.0 or later. If attempting to upgrade a deployment of NetBox v2.10 or earlier, first upgrade to a NetBox v2.11 release, and then upgrade from v2.11 to v3.0. This will avoid any problems with the database migration optimizations implemented in version 3.0. (This is not necessary for new installations.)

 As with any other software, if making a major jump (lets say per 2.11 to 3.2), the developers state you should read the release notes for each major (x.x.0) release in between to be sure nothing breaks your integrated scripts and API calls, or the software itself.

I would be happy to put together an FAQ in the wiki for upgrade & install notes, but no one will read it either.  I can even link each of the major release notes x.x.0

>I agree with you that the information is somewhere, but it is not intuitive. Why make it that hard to find?

You are the first person I have seen mention its hard to find.  It seems like you have too much faith in opensource software upgrades by just pushing to prod and not testing.  I do not even trust deploying vendor/commercial software or firmware to prod without testing.
