### ISSUE TITLE
Cached REST API spec introduced in #6423 is stale after updates

### ISSUE THREAD

**Issue by fabi125** [netbox-community/netbox#9122]
### NetBox version

v3.1.11

### Python version

3.8

### Steps to Reproduce

1. Install Netbox v3.0.5+
2. Fetch http://netbox/api/docs/?format=openapi to populate Redis cache
3. Update to another Netbox version.
4. Fetch http://netbox/api/docs/?format=openapi and get the old openapi definition

### Expected Behavior

The correct openapi definition should be returned.

### Observed Behavior

Stale cached version of the openapi definition is returned.

Honestly I'm not 100% sure why this is happening. My reading of the Django cache documentation (https://docs.djangoproject.com/en/4.0/topics/cache/ and https://docs.djangoproject.com/en/4.0/ref/settings/#std:setting-CACHES-KEY_FUNCTION) makes it sound like the cache should use the Netbox version as a key, which would make it a different entry in the cache so this shouldn't be a problem.

Hopefully someone with more knowledge about Django caching can reproduce this and figure out why this is happening.

**Comment by kkthxbye-code** [comment]
@jeremystretch - Would it make sense to clear the entire cache in the upgrade script? It would require re-adding the command for clearing the cache. netbox-docker would probably also have to be adjusted.

The cache is very sparsely used currently.

**Comment by jeremystretch** [comment]
I think that makes sense, yeah. It's probably good practice to clear the cache on upgrade anyway.

Related, I also want to look into pre-rendering the API spec at release time. I'm not sure exactly what that process would look like, but it would avoid the caching issue entirely, and potentially allow us to add the REST API spec to the documentation using [mkdocs-plugins](https://github.com/Neoteroi/mkdocs-plugins). (But that's another discussion.)
