### ISSUE TITLE
Assign custom fields to sections

### ISSUE THREAD

**Issue by KosenkoIvan** [netbox-community/netbox#9126]
### NetBox version

nexbox (v3.1.5)

### Feature type

Change to existing functionality

### Proposed functionality

It would be convenient to choose where to place custom fields. Not all information in the Custom fields section should be located there. We suggest creating a choice of placing a custom field, for example, in the device, management or other sector. We are faced with the problem of finding a custom field. We need to look for many unique data in custom fields, for this we use a filter every time, which slows down the process of work. Search without a filter does not find a custom field.
![image](https://user-images.githubusercontent.com/97949308/163360379-43ca88cb-8f04-40f8-a9d6-dc9c5122eb5c.png)
![image](https://user-images.githubusercontent.com/97949308/163360655-efbba70e-d82a-48a0-ba5b-1d8c0cacc760.png)
![image](https://user-images.githubusercontent.com/97949308/163360769-3ecd0bb6-99a5-4030-a985-02800ad7a7eb.png)

### Use case

We see such solutions to this problem.
1.Custom fields are moved to sections and thus the search finds them without a filter.
2.Custom fields are included in the search without a filter.

This will speed up the search time and make it easier to navigate.

**Comment by jeremystretch** [comment]
> Not all information in the Custom fields section should be located there.

Custom fields are intentionally called out and organized separately to avoid confusion with built-in fields.

> We suggest creating a choice of placing a custom field, for example, in the device, management or other sector.

Not only is this technically infeasible, it would be very difficult to accommodate from a UI design perspective. We're going to keep custom fields in their own section, but you may be interested in #8495, which seeks to provide better control over how the fields are grouped within that section.
