### ISSUE TITLE
Kit list / Cost calculator

### ISSUE THREAD

**Issue by DevilWAH** [netbox-community/netbox#9127]
### NetBox version

v3.2.0

### Feature type

New functionality

### Proposed functionality

The ability to produce kit list and estimated costs for new projects. 

If as part of the "device Type" there was a field "list price", And under regions was an "Exchange rate"   (and for manufactures maybe a "Default and regional discount." as a future enhancement) 

Then if each device type has the list price added globally, as we design the site / racks we could quickly provide the project team a kit list and ballpark cost. using a simple export template in the local currency. 

Because we also have discounts in place with vendors if we could assign these to the manufactures we could apply these in the same way via export template.  

### Use case

When designing a new site a new proposal be able to see live estimate costs for budgeting, and output a kit list to send to suppliers. 

Working in a large company with 100's of sites that are often moved / refreshed we are often asked to create bills of materials and rough costs. we already are using Netbox to do the design and we have to output the list of devices and input it to a spreadsheet. 

Just adding two fields and a simple export template and netbox could do this for us. I know I can do this with "custom" fields but it would be nice to have it built in. 

### Database changes

Add 

1. List price to Device type and all user to select currency
2. Add Currency and conversion rate to region 

### External dependencies

None.

**Comment by DanSheps** [comment]
Just reviewing this, I think this would be more appropriate as a plugin, not a core feature of netbox.

**Comment by DevilWAH** [comment]
Hi,

That's a good point, and your probably right. It does sound like a plug in.

Thank you.

Aaron.

**Comment by jeremystretch** [comment]
I'll echo Dan's sentiments here; while not quite suitable for NetBox core due to the feature scope it opens up, I do think it would make a very intriguing plugin. If you're interested in building it, be sure to check out our [plugin development tutorial](https://github.com/netbox-community/netbox-plugin-tutorial). Thanks for the idea either way!

**Comment by DevilWAH** [comment]
Hi,

thank you for the feed back i will look in to it. Just one question is it possible to run Netbox on raspberry pi? I don't have a spare server at home right now but do have a few pi4's.

seem to be conflicting reports on line so if any one can point me towards and Resorces on this i would be grateful

Thanks



________________________________

**Comment by jeremystretch** [comment]
NetBox itself isn't too resource-intensive aside from the occasional large query, so for development purposes you'll likely have no problem running it on an embedded system. However, you might also consider [netbox-docker](https://github.com/netbox-community/netbox-docker) or a local VM.
