### ISSUE TITLE
Add non devices to a rack

### ISSUE THREAD

**Issue by bribeck** [netbox-community/netbox#9129]
### NetBox version

V3.2

### Feature type

New functionality

### Proposed functionality

Have a rack management section so you can add stuff like rack brush bars, rack drawers, and blank plates to racks. Having to clutter up the device list with these kinds of rack equipment not the ideal. One way this could be done is to allow us to put add a device type to a rack and not have to create a device for it. 

### Use case

This would make it easier to add stuff to racks and make more realistic to what we would have in the real world. Racks don't always contain items that would need to tracked as a device.

### Database changes

Not sure what would be needed

**Comment by grbeneke** [comment]
I currently use the "reservation" option to record space used for these kind of rack accessories. A method to add these as distinct objects without having a device entry created for each one would certainly be useful.

**Comment by jeremystretch** [comment]
> Have a rack management section so you can add stuff like rack brush bars, rack drawers

These are devices and should be treated as such. You don't gain anything by introducing a redundant model to track the same information.

> blank plates

If the assumption is that blanking panels are needed to cover empty rack units, why track them at all?

This was proposed originally back in #417, and the solution ultimately was to just model everything as devices, which is much simpler than trying to juggle "real" and "not real" devices.

**Comment by jeremystretch** [comment]
Going to close this out as I don't believe there's any action to take.
