### ISSUE TITLE
upgrade.sh does not require Python 3.8

### ISSUE THREAD

**Issue by markkuleinio** [netbox-community/netbox#9133]
### NetBox version

v3.2.1

### Python version

3.8

### Steps to Reproduce

1. Run `upgrade.sh` on a system with Python 3.7 only

### Expected Behavior

`upgrade.sh` should complain about the minimum required Python version (3.8 for NetBox 3.2)

### Observed Behavior

```
# ./upgrade.sh
Using Python 3.7.3
...
ERROR: Could not find a version that satisfies the requirement Django==4.0.4
```
so there is no direct error message about the Python version.

In the start of `upgrade.sh` there is a Python version check but it only checks for 3.7+ while Python 3.8+ is required for NetBox 3.2.

**Comment by markkuleinio** [comment]
PR ready to be submitted if issue is accepted.

**Comment by jeremystretch** [comment]
We do have the logic in there but it currently only checks for v3.7+, so it should be an easy tweak. Thanks!
