### ISSUE TITLE
Searching 'front ports' or 'rear ports' results in an attempt to rename

### ISSUE THREAD

**Issue by cyr0nk0r** [netbox-community/netbox#9138]
### NetBox version

v3.2.1

### Python version

3.8

### Steps to Reproduce

1) Go to Demo site
2) click on a device that has front ports (Ex: any of the patch panels)
3) click on the front ports tab
4) attempt to search using the 'quick search'
5) if you type 14 and hit 'enter' you are taken to a 'rename' page where netbox wants to rename 0 ports.

I am recreating this bug since it is still present from my last bug report that was incorrectly marked as a duplicate.
https://github.com/netbox-community/netbox/issues/9113

### Expected Behavior

hitting enter should initiate the quick search and/or do nothing. 
Look at the quick search for 'contacts'. Hitting enter on that quick search does not attempt to rename a contact.

### Observed Behavior

hitting enter on quick search within front ports results in an attempt to rename 0 ports.

**Comment by shatt79** [comment]
This same thing happens when using the "Quick Search" on the Interfaces tab of a device.  And the Quick Search field doesn't work at all when going into the main Interfaces table.
