### ISSUE TITLE
German Umlauts are not possible while creating a new tenant group

### ISSUE THREAD

**Issue by tijuca** [netbox-community/netbox#9153]
### NetBox version

v3.2.1

### Python version

3.10

### Steps to Reproduce

I was trying to add an new tenant group in 3.2.1

1. Go to Organization - Tenant Group
2. Start adding a new tenant group
3. Use e.g. "Mühlenstein" or  "Großmann" as Name
4. Try to finish adding a new group by click the button Create

### Expected Behavior

In Germany ta tenat group can contain the typical German Umlauts "äüö" or also "ß". Also within the Description for a tenant group can contain such letters and I should be able to use them in this dialog.

### Observed Behavior

I'm getting instead a server error page containing this message.
```
<class 'django.db.utils.NotSupportedError'>

conversion between UTF8 and SQL_ASCII is not supported
LINE 1: ..., 'create', 78, 5, NULL, NULL, 'Großmann', NULL, '{"created"...
                                                             ^
```
This error is also happen if you don't use a Umlaut within the name field but do use a Umlaut then within the description field.

I expect this error might be happen in other menus and dialog too but haven't figured out this.

**Comment by kkthxbye-code** [comment]
Not a netbox bug, your database has been created with the SQL_ASCII encoding instead of UTF-8 for some reason.

See https://github.com/netbox-community/netbox/issues/7306

**Comment by tijuca** [comment]
@kkthxbye-code 
Thanks, the linked issue was helpful, after converting the database I can create the wanted tenant groups.
