### ISSUE TITLE
Adding Tenant's ASN selection to an IP address and Circuit

### ISSUE THREAD

**Issue by MarianRychtecky** [netbox-community/netbox#9159]
### NetBox version

v3.1.9

### Feature type

Change to existing functionality

### Proposed functionality

In our case, it would be very useful to have a selection (drop-down) menu for Tenant's ASN within IP address screen. This will allow us to assign certain Tenant ASN to IP address. The Tenant group and Tenant are already on the screen.The same thing would be nice on the Circuit definition screen.

![163609069-f53d52b9-e7a6-4680-aefd-118f3f99bd3d](https://user-images.githubusercontent.com/36925394/163826155-95ab2b5b-1188-4974-be03-d23436aa61a5.png)

![163609244-b6500446-49ea-4e91-91d3-19f6c9cc587d](https://user-images.githubusercontent.com/36925394/163826219-5437b57d-b715-4315-a9ec-d522a1695af5.png)

### Use case

All our members/customers are having a BGP peering with us and our route servers, having ASN associated with an IP address and circuit I can have a configuration parameter for other components. Some members/customers have multiple ASNs therefore we need to extend this association within IP address and Circuit.

### Database changes

Add Tenant's ASN relation to IP address
Add Tenant's ASN relation to Circuit

### External dependencies

Nothing I'm aware of.

**Comment by DanSheps** [comment]
I don't see us adding ASN to these views at all, if I am being honest.

While they may bring value, for service providers in certain circumstances, the majority of our user base are not service providers.  For non service provider users, ASN on IP address (and to a lesser extent Circuits) make no sense.

Additionally, both the Circuit and the IP Address are the wrong place to attempt to model your routing policy.  In the near-term, you are welcome to use a custom field for this which references the ASN model.

**Comment by DanSheps** [comment]
Thank you for submitting your idea. Unfortunately, the proposed feature falls outside the scope of functionality that NetBox aims to provide. As NetBox is an open source application with limited development resources and a persistent backlog of existing work, it is crucial that we limit the scope of development to ensure it remains a maintainable project for many years to come. Thank you for your understanding.

**Comment by tyler-8** [comment]
This can be accomplished using the Custom Object Fields introduced in v3.2 

https://docs.netbox.dev/en/stable/customization/custom-fields/#custom-object-fields
