### ISSUE TITLE
Information about the User who modified the object

### ISSUE THREAD

**Issue by top1ing** [netbox-community/netbox#9160]
### NetBox version

v3.2.1

### Feature type

New functionality

### Proposed functionality

In addition to "created" and "last_updated" info in objects would be useful add "modified_by_user" with username who modified the object in last time.

### Use case

Usage different NetBox user for external scripts (e.g. "script_user") and "modified_by_user" in webhook conditional logic to prevent unneccesary webhook re-triggering in case where script change something of NetBox object.
`{
    "and": [
        {
            "attr": "modified_by_user",
            "value": "script_user",
            "negate": true
        }
    ]
}
`

For example, we are trying to use webhook for autocreating, updating and deleting host in NMS when a device is changed in NetBox. For better integration, after create host in NMS script add value of NMS_host_id in NetBox Device custom field "NMS_HOST_ID". But this leads to another generation of the Update event and the unneccesary Webhook trigerring.

**Comment by sc68cal** [comment]
Doesn't the changelog for objects already store this information, through a couple intermediate links?

**Comment by top1ing** [comment]
This is true.
But the idea was to use a webhook conditional logic to prevent retrigerring webhook target.
Actually, for what webhook conditional logic is used.
