### ISSUE TITLE
Allow hiding custom fields in UI

### ISSUE THREAD

**Issue by PieterL75** [netbox-community/netbox#9166]
### NetBox version

v3.2

### Feature type

Change to existing functionality

### Proposed functionality

Provide a 'ReadOnly' checkbox to custom fields.
If a checkbox is readonly, then the user is not able to edit/update the field, when editing an object.

### Use case

Fields that are populated by automation, should not be editable by end users.
(ex: vcenter, prefix utilization, ...)

### Database changes

New Boolean field on the custom fields.

**Comment by PieterL75** [comment]
We have some scripts that run regularly (contact import for ex), and some that are triggered (prefix utilization calculation) and external scripts that push data into Netbox using API calls.
On the other hand, we have fields on devices (hardwaretag, escalation levels, ...) that are entered manually.

There is no way to 'predefine' what fields are human and what are autopopulated.
But if I can set the readonly-flag then the Edit form will be less cluttered with fields that users are not allowed to enter.

**Comment by proudbro** [comment]
I've created the similar [issue](https://github.com/netbox-community/netbox/issues/6677) 
IMO useful functionality for external integrations

**Comment by jeremystretch** [comment]
> But if I can set the readonly-flag then the Edit form will be less cluttered with fields that users are not allowed to edit/change

I think you're missing my question. What would prevent a human user from modifying a "read-only" custom field e.g. via the REST API, while permitting the change from a system user? It's not sufficient to just omit the custom field from the object edit form.

**Comment by jeremystretch** [comment]
I think the key here is not referring to them as "read-only" fields, but by some other name that more accurately conveys the fact that they're not editable via the UI. It's a subtle but important distinction.

Maybe introduce an "editable via UI" flag (better name TBD) which defaults to true. If set to false, the field won't be editable in the UI, but it will have no impact on changes made via the API.

**Comment by PieterL75** [comment]
Sounds like a good approach !
Maybe 'Only updatable via API'

**Comment by pgnuta** [comment]
I'd like to suggest that a three-way choice option for the custom field:

Name: "Web UI Display" 
Description: "The ability to edit or display the field to users in the web UI, read/write access is always available via API and custom scripts"
Choices: "Read / Write", "Read only", "Invisible"
Default: "Read / Write"

**Comment by jeremypng** [comment]
Would it be possible as part of this feature to allow you to specify what device-types to display the field on if the custom field is assigned to a device object?

**Comment by kkthxbye-code** [comment]
I'm working on this currently. Just need to clean it up and add whatever stuff I missed. I'll create a PR when done to gather feedback.

**Comment by phurrelmann** [comment]
Just a quick idea to make the hiding more natural the "netbox way": could the hiding and/or read-write be handled with jinja2? that way a user would be able to decide based on objects/contents if a custom fields need to be disabled or is editable

**Comment by kkthxbye-code** [comment]
The implementation will be based on @pgnuta's reply. 

Not sure I understand exactly what you are suggesting @phurrelmann. Like a text field where you can write template code? And then what? Is the template code rendered in place of the custom field display both on objects and in edit/create forms? It seems very different than what was suggested in this FR.

**Comment by jeremystretch** [comment]
Thanks @kkthxbye-code!

**Comment by proudbro** [comment]
@jeremystretch , you can link it with [this issue](https://github.com/netbox-community/netbox/issues/6677) as well
