### ISSUE TITLE
Able to assign tenants to Wireless LANs

### ISSUE THREAD

**Issue by joaolucasmacedo** [netbox-community/netbox#9177]
### NetBox version

v3.2.1

### Feature type

Data model extension

### Proposed functionality

been able to assign tenants to Wireless LAN objects. Wireless LAN groups are very nice to aggregate WLANS by functionality os scope, but it would be much better if it is possible to also assign to tenants.  

### Use case

I have a set of wireless LANs and they belong to different entities inside and outside my organization. Some people have access to Netbox and their permissions are based on tenants, so I can't filter which Wireless LAN, and passwords, they can see.

**Comment by jeremystretch** [comment]
It probably makes sense to add tenant assignment for wireless links as well.
