### ISSUE TITLE
FHRP vs NHRP in wiki

### ISSUE THREAD

**Issue by jcralbino** [netbox-community/netbox#9186]
### Change Type

Correction

### Area

Other

### Proposed Changes

In the wiki `[Data modeling ip interfaces ](https://github.com/netbox-community/netbox/wiki/Data-Model-Limitations#nhrp-ip-addressing)

the information is probably not considering the existence of the recent added feature of FHRP Groups 

based on that feature I believe the recommends data model for ip assigned to the interface and part of a “nhrp” would change ?

**Comment by jeremystretch** [comment]
:+1: I've removed this section of the wiki page as it no longer applies.
