### ISSUE TITLE
Enforce Unique Serial Numbers

### ISSUE THREAD

**Issue by lamoni** [netbox-community/netbox#9187]
### NetBox version

v3.2.1

### Feature type

Change to existing functionality

### Proposed functionality

I think an option to enforce unique serial numbers on devices would be useful. I imagine the behavior would be similar to the old strict hostname uniqueness that used to be enforced (i.e. if the serial number is blank, that's an "allowed" duplicate, but if the serial number is non-NULL, then it has to be unique).

### Use case

Right now, we currently have our own external auditing script that checks for duplicate serial numbers and corrects them / flags them to the users/teams that initially imported them. It would be useful for us to stop those from ever being imported in the first place. Given the fact the serial number can (usually...) be relied upon as a "unique identifier", I feel like it would make sense to at least have the option to enforce uniqueness, similar to the ENFORCE_GLOBAL_UNIQUE option for IP/prefixes.

### Database changes

None that I know of.

### External dependencies

None that I know of.

**Comment by pgnuta** [comment]
Could you use custom validation for this instead?
https://demo.netbox.dev/static/docs/customization/custom-validation/

**Comment by lamoni** [comment]
@pgnuta thanks! I've been going over examples I can find online, and they all seem to only reference the instance that is being created (i.e. I can do static validation like my own custom regex or logic. I think for our use case, we would need to be able to reference all of the serial numbers for any of the devices so we can check if the new serial number is already in that list? Please correct me if I am misunderstanding. Thanks!

**Comment by kkthxbye-code** [comment]
He means something like this:

```
from extras.validators import CustomValidator

class MyValidator(CustomValidator):

    def validate(self, instance):
        from dcim.models import Device

        if instance.serial and Device.objects.filter(serial=instance.serial).exists():
            self.fail("Duplicate serial", field='serial')
```

```
CUSTOM_VALIDATORS = {
    'dcim.device': (
        MyValidator(),
    )
}
```

This is tested and working. In this example the validator is defined in the configuration.py file itself. There are other ways to organize it.

**Comment by lamoni** [comment]
@kkthxbye-code  Ah perfect, thank you! And thank you as well, @pgnuta. Closing this
