### ISSUE TITLE
Module creation should fail validation when {module} token is present in a componnet name but no position is set on the bay

### ISSUE THREAD

**Issue by goebelmeier** [netbox-community/netbox#9190]
### NetBox version

v3.2.1

### Python version

3.8

### Steps to Reproduce

1. Create a device with module bays, I had 2 module bays with name `ct0` and `ct1`
2. Create a module type with interfaces named `{module}.eth0`
3. Add the new module to a module bay in the device
4. Add a second module to the second module bay

### Expected Behavior

1. The placeholder should be replaced by module name resulting in `ct0.eth0`
2. The second module should be placed and the interface name should result in `ct1.eth0`

### Observed Behavior

1. First module creates an interface named `.eth0`
2. Second module cannot be created. Error: 
```
<class 'django.db.utils.IntegrityError'>

duplicate key value violates unique constraint "dcim_interface_device_id_name_bffc4ec4_uniq"
DETAIL:  Key (device_id, name)=(4478, .eth0) already exists.


Python version: 3.8.10
NetBox version: 3.2.1
```

**Comment by benhur1999** [comment]
Did you put any value in the "Position" field when creating the module slots?

I had a same error and it was due to the "Position" field not filled. Maybe Position should be mandatory.

**Comment by goebelmeier** [comment]
> Did you put any value in the "Position" field when creating the module slots?
> 
> I had a same error and it was due to the "Position" field not filled. Maybe Position should be mandatory.

That was the issue, thank you @benhur1999 ! So from my point of view, position should be mandatory too.

**Comment by jeremystretch** [comment]
The position field is optional because some devices may have unnumbered module bays, and we don't want to force people to make up arbitrary unique identifiers for them. A compromise might be to check for a `{module}` placeholder when instantiating components, and raise a validation error if the bay into which the module is being installed does not have a position defined.

**Comment by benhur1999** [comment]
Not making position mandatory makes sense in this case, however the validation should definitely be performed when the `{module}` is used. Otherwise you may end up with malformed interface names (e.g `.eth0`) or the `django.db.utils.IntegrityError` exceptions.

**Comment by jsenecal** [comment]
Faced the same issue today thanks @jeremystretch for the clarification :)
