### ISSUE TITLE
Display Rack Reservation text in Rack Elevations

### ISSUE THREAD

**Issue by howard-2020** [netbox-community/netbox#9191]
### NetBox version

v3.2.1

### Feature type

Change to existing functionality

### Proposed functionality

Display text for rack reservations in the rack elevation view. We can either use the description field or create a new field called "Label" that would serve strictly as the display text.

### Use case

There are certain items that we do not want to create a device for, such as horizontal wire managers, ground bars, etc. We would like to give install technicians a print-out of the rack elevations to work from when installing new equipment in racks.  The limitation is that the rack elevations do not list labels or text for reservations.  The alternative is to create a device for each item but that is not ideal.

### Database changes

Possibly add a "Label" field to the model that has a limit on characters.

### External dependencies

None.

**Comment by jeremystretch** [comment]
> There are certain items that we do not want to create a device for, such as horizontal wire managers, ground bars, etc.

It sounds like you're misusing rack reservations here. Anything that gets installed into a rack should be modeled as a device, not a reservation.

**Comment by DanSheps** [comment]
This use case was recently brought up in #9129

**Comment by howard-2020** [comment]
I agree that I may be misusing the rack reservation intended purpose. However I think it would still be helpful to display text for legitimate rack reservations rather than having to hover over the rack elevation.  It looks like the rack elevation would fit about 29 characters without running outside the the rack image.  What if you took the first 29 characters of the reservation description and displayed that on the rack elevations? In that case, there would not need to be a new field created.
