### ISSUE TITLE
Interface Range

### ISSUE THREAD

**Issue by GoodiesHQ** [netbox-community/netbox#9202]
### NetBox version

v3.2-1.6.1

### Python version

3.8

### Steps to Reproduce

1. Create a device (e.g. a switch named CoreSwitch)
2. Import Bulk Interface using a range e.g. "CoreSwitch,A[1-24],1000base-t"

### Expected Behavior

I was expecting it to create multiple interfaces: A1, A2, A3, ... A23, A24

![image](https://user-images.githubusercontent.com/4576046/164781451-afd56b78-1731-4d22-a1c4-4de4ab568d5a.png)

### Observed Behavior

Creates one single interface object named "A[1-24]"
Instead, this is my result:
![image](https://user-images.githubusercontent.com/4576046/164781665-cf389dce-6561-491a-8395-378092ddbbd3.png)

**Comment by jeremystretch** [comment]
Range expansion is supported only through the single object creation form. If you're importing CSV records, the expectation is that you'll already have a record per object.

**Comment by GoodiesHQ** [comment]
Understood! That makes sense. However I did not see an option on the interface for single interface creation... plenty of other items have the green plus sign, but "interfaces" does not:
![image](https://user-images.githubusercontent.com/4576046/164837804-0ec604a4-da7e-4144-9f5e-e6e999eeee26.png)

**Comment by jeremystretch** [comment]
You can add interfaces to a device under the device view (Add components > Interfaces).

**Comment by GoodiesHQ** [comment]
Awesome. Instantly solved, thank you guys!
