### ISSUE TITLE
Expand Custom Fields Object Assignment to support filters in custom field definition

### ISSUE THREAD

**Issue by michael-edobor** [netbox-community/netbox#9220]
### NetBox version

v3.2.1

### Feature type

Data model extension

### Proposed functionality

Introduce the ability to allow users to filter objects in UI (by configurable parameters) while assigning 'objects' as custom fields to various models. This is somewhat similar to the query_set behavior in Custom scripts. To reduce complexities, this feature can be limited to single-selection Objects.

### Use case

A sample use-case is a user trying to assign a parent routed 'interface' to a 'vlan group' as a custom field. The drop-down for selection brings up a list of all 'interface objects' on netbox with their 'names' so the user has a a lot  of interfaces not knowing which devices those interfaces belong to as the label or name 'GigabitEthernet0/1' likely exists across multiple devices. 

![image](https://user-images.githubusercontent.com/97886385/165160673-e84ec2e7-88ea-439f-89ec-3d81d5b9d6d1.png)

A short term fix for this specific use-case could be representing 'interface objects' by '$parent device.name: $interface' or '$interface.id: $interface.name'. A more long-term solution will be giving the option use query_params in the UI. e.g 

`query_params={
            'device': '$device_id',
        }`

Presently, the correct assignment can only be achieved using a custom script to filter that object in UI and then assign the correct interface. 

### Database changes

Not sure

### External dependencies

Not sure

**Comment by darcynz** [comment]
Is it possible to re open this. We came accross this issue and am not sure its even possible to find an object like an interface with out its parent object details.. eg Device..

**Comment by darcynz** [comment]
@michael-edobor hope you dont mind, i raised #10360
