### ISSUE TITLE
Change Log doesn't update in device view when changing device interfaces

### ISSUE THREAD

**Issue by cs-1** [netbox-community/netbox#9227]
### NetBox version

v3.2.1

### Python version

3.8

### Steps to Reproduce

1. Make a change to a device's interface.
2. Open device's Change Log tab.

### Expected Behavior

Interface changes show up in the device's Change Log.

### Observed Behavior

The new changes to interfaces do not appear in the Change Log tab of a device only changes to interfaces before the beginning of April 2022 show up.

However, the new changes do show up in the Change Log of the main NetBox dashboard and also under "Other / Change Log". From what I can tell this issue exists since migrating from 3.1.x to 3.2.x.

**Comment by cs-1** [comment]
While that's true, that is not the way it used to work in 3.1.x. We even still have changes for interfaces in the device's Change Log tab that were made before the upgrade to 3.2.x. From a pure usability point of view it makes perfect sense that changing a device's interface is a change made to the device. Unless I've missed something, there're no hints in the changelog of NetBox that the functionality of a device's Change Log has been changed. That's why I think that this change in behaviour is unintentional.

**Comment by jeremystretch** [comment]
There's a bug in the `to_objectchange()` method on the Interface model that's bypassing the assignment of the parent device as a related object. Interface seems to be the only model affected.

**Comment by cs-1** [comment]
Hi Jeremy!

Thanks for the quick fix. Your help and the effort you put into NetBox is highly appreciated!
