### ISSUE TITLE
Add DOCSIS Interface Type(s)

### ISSUE THREAD

**Issue by sleepinggenius2** [netbox-community/netbox#9229]
### NetBox version

v3.2.1

### Feature type

Data model extension

### Proposed functionality

Add a new interface type for DOCSIS interfaces. Ideally, it would be nice to include the maximum supported version, so we could have ones for the following, though I'm not sure 1.0 or 1.1 would really be relevant anymore:

* DOCSIS 1.0
* DOCSIS 1.1
* DOCSIS 2.0
* DOCSIS 3.0
* DOCSIS 3.1
* DOCSIS 4.0

### Use case

This would be useful when modeling CMTS/CCAP or cable modem devices. While it can be modeled by using the *Other* type today, I see that there is already a type for ATM / xDSL, so I think this would be appropriate as well. Adding multiple types for the maximum supported versions would be useful for reporting purposes, but I also understand just using a single type, like how xDSL was consolidated.

### Database changes

None

### External dependencies

None

**Comment by DanSheps** [comment]
I would be okay adding a single DOCSIS interface type in this fashion:

### COAX
  * DOCSIS

I don't think we need one for every conceivable DOCSIS specification, especially given the precident already set with ATM / xDSL.  My understand (I am not a docsis engineer), the physical interface doesn't change much like it does for example between SFP+ and SFP28.

**Comment by sleepinggenius2** [comment]
I'm good with that. From a physical standpoint, it should always be an F Connector, regardless of the digital or analog RF protocol that is being transmitted. Do you think it would make more sense to make it even more generic to just be an F Connector from a physical standpoint? That would then support DOCSIS, MoCA, CATV, or whatever other RF protocol is being used.

That does go a bit against the current precedent of distinguishing not just physical connector, but also protocol. For example, SFP+ (10GE) is specifically called out as being Ethernet, and SFP+ (8GFC) and SFP+ (16GFC) are specifically called out as FibreChannel, but there is a type for OC-192/STM-64 and no way to also indicate if it is using an SFP+ form-factor optic.

Following a similar convention, we could have something like F Connector (DOCSIS), F Connector (MoCA), F Connector (CATV). Unfortunately, I know DOCSIS and video can coexist together, so that could throw a bit of a wrench into things.

At some point, it would be nice to have the cable type options limited to only the ones that make sense for the interface that they are connecting to, like it being Coax in this case. That's something I've been considering creating a custom validator at least for, and one of the reasons I'm just trying to make sure we set a good precedent going forward on all of this.

**Comment by martinum4** [comment]
> Maybe there's an opportunity to start decoupling the form factor and protocol/signaling for some of these interface types.

Yes, i think now that NetBox supports more wireless features, the coax-connectors could come in handy too.

Maybe this could be handled by a "two-stage-dropdown" (not a developer, so this might not be the right wording) where first the physical connection is selected and after that the protocol which is based on it.
