### ISSUE TITLE
Can't search for empty field using __empty for dns_name for IP addresses

### ISSUE THREAD

**Issue by sol1james** [netbox-community/netbox#9231]
### NetBox version

3.2.1

### Python version

3.10

### Steps to Reproduce

I want to search for records that have no value in a field as per https://github.com/netbox-community/netbox/issues/6138. The url I'm using is:

`https://netbox.mydomain/ipam/ip-addresses/?dns_name__empty=False`

I also tried this with the description field for IP addresses and also the description field for a Device with the same results.

I created a discussion topic at https://github.com/netbox-community/netbox/discussions/9224 and Jeremy says it appears to be a bug.

### Expected Behavior

I get a list of all the IP addresses that have dns_name defined (set to some value)

### Observed Behavior

I get all IP addresses

### Follow on question

Is __empty (or searching for the `null` field value) supposed to work for custom fields?  I tested it in those too and couldn't get it to work

**Comment by jeremystretch** [comment]
This is probably going to require improving our current approach to automatically generating lookup filters, as it needs to add a boolean filter (rather than a character filter).

**Comment by jlownie** [comment]
I'm commenting on this as an attempt to keep it open.  I'm new to Github and didn't know how to update a pull request.  I think I've figured that out now so will have a go at updating the PR according to the feedback I received.

**Comment by jeremystretch** [comment]
This seems to be an issue with our [custom `empty` lookup](https://github.com/netbox-community/netbox/blob/802d9d2b6ec178fbae7bfee1947af3af0589e538/netbox/extras/lookups.py#L4). Even though the lookup succeeds when used directly in a queryset filter, django-filters does not seem to recognize it:

```
django_filters.exceptions.FieldLookupError: Unsupported lookup 'empty' for field 'ipam.IPAddress.dns_name'.
```
