### ISSUE TITLE
Availability of update automatic check

### ISSUE THREAD

**Issue by EHRETic** [netbox-community/netbox#9237]
### NetBox version

v3.2.1

### Feature type

New functionality

### Proposed functionality

Hi,

Don't know if it was already asked before (didn't find by searching) but if possible, I'd love to have a small warning whenever a new version is available.

Something discrete but that would open GitHub repository when clicked.

### Use case

With this functionality, no need to check/rely on GitHub to know if there is a new release 😃

**Comment by jeremystretch** [comment]
> I'd love to have a small warning whenever a new version is available.

You're in luck: Setting the [`RELEASE_CHECK_URL`](https://docs.netbox.dev/en/stable/configuration/optional-settings/#release_check_url) config parameter to `https://api.github.com/repos/netbox-community/netbox/releases` will do just that.
