### ISSUE TITLE
Device/VM name unique enforcement is case sensitive

### ISSUE THREAD

**Issue by Mizarv** [netbox-community/netbox#9242]
### NetBox version

v3.1.9

### Python version

3.8

### Steps to Reproduce

1. Create a cluster
2. Create VM "ABC"
3. Create VM "abc"

### Expected Behavior

Error "A virtual machine with this name already exists in the assigned cluster"

### Observed Behavior

New VM "abc" is successfully created despite VM "ABC" existing.

I believe the bug is applicable to Devices and other models too

**Comment by jeremystretch** [comment]
I'm not sure it's accurate to frame this as a bug: Uniqueness enforcement is exactly that, and "ABC" is different from "abc", though I understand your viewpoint.

You might consider re-submitting this as a feature request with a use case, so the community can debate the merits (and potential pitfalls) of the change in behavior.

**Comment by Mizarv** [comment]
> I'm not sure it's accurate to frame this as a bug: Uniqueness enforcement is exactly that, and "ABC" is different from "abc", though I understand your viewpoint.
> 
> You might consider re-submitting this as a feature request with a use case, so the community can debate the merits (and potential pitfalls) of the change in behavior.

Sure, I have raised  #9249
