### ISSUE TITLE
Apply user table preferences under object detail views

### ISSUE THREAD

**Issue by LHBL2003** [netbox-community/netbox#9260]
### NetBox version

v3.2.1

### Feature type

New functionality

### Proposed functionality

I navigate to the "Devices" and click on "Role" = Patch Panel. Now all patch panels are displayed. However, I cannot display a comment here. Because the button Configure Table does not exist. 

### Use case

Important information for better identification is not displayed. e.g. Comments. The display of additional information makes the work much more efficient.

**Comment by jeremystretch** [comment]
> I navigate to the "Devices" and click on "Role" = Patch Panel. Now all patch panels are displayed. However, I cannot display a comment here. Because the button Configure Table does not exist.

I'm not sure I follow. The table configuration button is present on the devices list.
![Screenshot 2022-05-03 at 09-16-20 Devices NetBox](https://user-images.githubusercontent.com/13487278/166459866-d209e138-ad06-45c5-aaea-9f8008d04595.png)

**Comment by kkthxbye-code** [comment]
@jeremystretch - It is the list shown when viewing a device role.

URL: `/dcim/device-roles/<ID>/`

![image](https://user-images.githubusercontent.com/400797/166464783-af73b8a1-2705-434b-affd-63168d99b1ec.png)

Other examples would be `/dcim/platforms/<ID>/`

**Comment by jeremystretch** [comment]
This is the same table as displayed in the devices list: Any preferences assigned to that table will be applied to this view as well. Does that address your use case?

**Comment by LHBL2003** [comment]
Thx @kkthxbye-code,

@jeremystretch 

If you click on "Patch Panel" in the Role column, you will see that you cannot display comments.

we write general information about the panel in the comments. This tells us which area the panels are for. We don't need to see the panel's connectors first.

So you have to search for Patch Panel in the Device List to see the additional columns.

However, this is not as user-friendly and fast as with roles.

**Comment by LHBL2003** [comment]
> This is the same table as displayed in the devices list: Any preferences assigned to that table will be applied to this view as well. Does that address your use case?


Yes, I would be happy if the same columns are displayed in this view as I have set in the device list.

**Comment by jeremystretch** [comment]
> If you click on "Patch Panel" in the Role column, you will see that you cannot display comments.

Ok, I see the issue. The table under the DeviceRole view is not being initialized with the current user, so the user's preferences are not being applied.

Looking into this further, the ideal approach would probably be to refactor NetBoxTable to apply user preferences under its `configure()` method, obviating the need to pass the user explicitly during instantiation of the table. However, this would be a breaking API change for plugins; it would need to wait for a minor release. In the interim, we can just pass the user where needed under the relevant views.
