### ISSUE TITLE
Linkify device type in manufacturer table

### ISSUE THREAD

**Issue by abhi1693** [netbox-community/netbox#9265]
### NetBox version

v3.2.3-dev

### Python version

3.8

### Steps to Reproduce

1. Create a manufacturer with the name: `Cisco` and slug `cisco`
2. Create a new device type and select the manufacturer as `Cisco`
3. Go to the manufacturer list page and notice that the count is `1` without a link to the device types

![image](https://user-images.githubusercontent.com/5083532/166249700-6e168dd1-dd24-4893-bc37-67b69a68aa06.png)

### Expected Behavior

Device type under manufacturer should be clickable to filter the types by the manufacturer 

### Observed Behavior

Link is not available

**Comment by abhi1693** [comment]
I have updated the description. I'm not sure how the sentence got garbled in there. 

Anyhow, I currently do not have a setup for 3.2.2 since I'm doing active development for my organization. We have not yet deployed the stack in production.

**Comment by DanSheps** [comment]
I don't see this as a bug as much as a feature request.

**Comment by abhi1693** [comment]
Closing this in favor of https://github.com/netbox-community/netbox/issues/9278
