### ISSUE TITLE
Interface Role have extra entry 'r'

### ISSUE THREAD

**Issue by DominicHar** [netbox-community/netbox#9267]
### NetBox version

V3.2.2

### Python version

3.8

### Steps to Reproduce

1: Create / Edit IP address
2: Open Role Drop-down and scroll to bottom

### Expected Behavior

Last entry is "CARP"

![image](https://user-images.githubusercontent.com/2497502/166116153-d646e08a-fc3d-413e-acfe-0c250274500d.png)

### Observed Behavior

Last entry is "r"

![image](https://user-images.githubusercontent.com/2497502/166116051-4621c744-9b09-4a7e-96c2-19817eff8e18.png)

This is observed in both local install and online Demo

**Comment by steffenkremser** [comment]
Seems to be a typo in  b3ea007e0a286ad414162a53b10dc248e134723f

```python
    CHOICES = (
        (ROLE_LOOPBACK, 'Loopback', 'gray'),
        (ROLE_SECONDARY, 'Secondary', 'blue'),
        (ROLE_ANYCAST, 'Anycast', 'yellow'),
        (ROLE_VIP, 'VIP', 'purple'),
        (ROLE_VRRP, 'VRRP', 'green'),
        (ROLE_HSRP, 'HSRP', 'green'),
        (ROLE_GLBP, 'GLBP', 'green'),
        (ROLE_CARP, 'CARP'), 'green',
    )
```
i.e. the `ROLE_CARP` tuple is closed prematurely (after just 2 elements)
.. the leftover literal  `'green'`  is treated as a seperate choice `['g','r','e',...]`
.. and thus displayed as  `r`  (second element is display_value)

.. the obvious fix being
```diff
-        (ROLE_CARP, 'CARP'), 'green',
+        (ROLE_CARP, 'CARP', 'green'),
```

**Comment by kkthxbye-code** [comment]
@steffenkremser - I submitted a PR. Thank you for doing the digging 👍
