### ISSUE TITLE
Expose CSRF_COOKIE_NAME in configuration.py

### ISSUE THREAD

**Issue by tyler-8** [netbox-community/netbox#9277]
### NetBox version

v3.2.2

### Feature type

New functionality

### Proposed functionality

Similar to https://github.com/netbox-community/netbox/issues/6197, allow admins to set an optional `CSRF_COOKIE_NAME` settings in their `configuration.py`.

### Use case

The default `csrftoken` is generic and could overlap with other applications/services running in the same domain as NetBox. Allowing admins to change this would help prevent conflicts in environments that need a unique name.

### Database changes

None

### External dependencies

None

**Comment by tyler-8** [comment]
@jeremystretch I'll take this

**Comment by jeremystretch** [comment]
@tyler-8 are you still working on this?
