### ISSUE TITLE
Linkify device type in manufacturer table

### ISSUE THREAD

**Issue by abhi1693** [netbox-community/netbox#9278]
### NetBox version

v3.2.3-dev

### Feature type

New functionality

### Proposed functionality

Device type under manufacturer list page should be clickable to filter the types by the manufacturer

### Use case

It would make it easier to filter the results directly from the manufacturer page to device types

![image](https://user-images.githubusercontent.com/5083532/166249700-6e168dd1-dd24-4893-bc37-67b69a68aa06.png)

### Database changes

None

### External dependencies

None

**Comment by huntabyte** [comment]
I will implement this.

**Comment by kkthxbye-code** [comment]
@huntabyte - All yours.
