### ISSUE TITLE
Assigning a VLAN that has no site to a prefix that has a site

### ISSUE THREAD

**Issue by schmittvictor** [netbox-community/netbox#9279]
### NetBox version

v3.2.1

### Feature type

New functionality

### Proposed functionality

Possibility to assign a VLAN that has no site assigned to a prefix that has a site.

### Use case

Our company has specific prefixes based on sites but has normalized the VLAN numbering across all our sites, so it would be nice to be able to assign a VLAN that has no site to a prefix that has a site.

**Comment by DanSheps** [comment]
I don't have a specific arguement for or against this proposal in principal.  However, for your specific use case:

> Our company has specific prefixes based on sites but has normalized the VLAN numbering across all our sites, so it would be nice to be able to assign a VLAN that has no site to a prefix that has a site.

The correct way to model this is actually discrete vlans assigned to each site as they are separate l2 segments and not the same VLAN.

Do you perhaps have a different use-case that could be applied to this equally?

**Comment by schmittvictor** [comment]
> I don't have a specific arguement for or against this proposal in principal.  However, for your specific use case:
> 
> 
> 
> > Our company has specific prefixes based on sites but has normalized the VLAN numbering across all our sites, so it would be nice to be able to assign a VLAN that has no site to a prefix that has a site.
> 
> 
> 
> The correct way to model this is actually discrete vlans assigned to each site as they are separate l2 segments and not the same VLAN.
> 
> 
> 
> Do you perhaps have a different use-case that could be applied to this equally?

In our case its actually the same VLAN since we have our proper fiber network across the country.

sorry for expressing myself badly

**Comment by DanSheps** [comment]
To clarify:

You have two prefixes (example: 10.232.10.0/24 at Site A and 10.232.11.0/24 at Site B) and you could have Site B's IP (10.232.11.23/24) configured at Site A and have communication with other devices in Site B (Ex: 10.232.11.21/24)?

**Comment by DanSheps** [comment]
Again, unless the two vlans can talk together (IE, you can configure the prefix for one on the ohter side and still communicate) then they should be modelled as separate vlans in netbox as they are separate L2 domains.

**Comment by schmittvictor** [comment]
> Again, unless the two vlans can talk together (IE, you can configure the prefix for one on the ohter side and still communicate) then they should be modelled as separate vlans in netbox as they are separate L2 domains.


Yes it is a different VLAN but I think that it would be easier that if no site has been attributed to a VLAN it can be assigned to an object with any site. Instead of creating every VLANs for every sites.
Or maybe let the user decide if this can be possible with a Dynamic Setting.

**Comment by max-baumgarten** [comment]
@schmittvictor I agree with you.  We should be able to have a set of universal VLANs that can be applied across all sites, especially if we have standardized VLAN schema's that apply to all prefixes, regardless of site.

**Comment by DanSheps** [comment]
If you are trying to model this properly, it should be a separate L2 segment (VLAN) in NetBox.  I understand you might be trying to save time, but you are comprising the accuracy of your network model in NetBox as when you model it as a single VLAN it looks like it is a single VLAN that the IPs share.

As far as a universal VLANs, speaking from an automation standpoint, how do you know if those VLANs need to be deployed to a specific device on a site?  What if your standard model deviates at one site.

There are valid use cases for assigning a site to a VLAN with multiple sites, but I would honestly rather see the VLAN model change to a many-to-many relationship rather then have site as null.

**Comment by schmittvictor** [comment]
> If you are trying to model this properly, it should be a separate L2 segment (VLAN) in NetBox.  I understand you might be trying to save time, but you are comprising the accuracy of your network model in NetBox as when you model it as a single VLAN it looks like it is a single VLAN that the IPs share.
> 
> 
> 
> As far as a universal VLANs, speaking from an automation standpoint, how do you know if those VLANs need to be deployed to a specific device on a site?  What if your standard model deviates at one site.
> 
> 
> 
> There are valid use cases for assigning a site to a VLAN with multiple sites, but I would honestly rather see the VLAN model change to a many-to-many relationship rather then have site as null.

You are probably right. Thanks for the time given to answer
