### ISSUE TITLE
Require password change on first login when creating new users

### ISSUE THREAD

**Issue by emersonfelipesp** [netbox-community/netbox#9282]
### NetBox version

v3.2.3-dev

### Feature type

New functionality

### Proposed functionality

The functionality is to **allow new users** recently registered on Netbox by the administrator **to change its own password when doing the first login**.
I don't know if it is maybe a "Django issue" or something like that, as we currently use Django Admin to create new Netbox accounts.

But I will let below an example of how it would be great to have on Netbox:
When checking the option **Require password change on first login** the field name of **Password** changes to **Temporary Password** (I got it from requarks.io)

<br>

![image](https://user-images.githubusercontent.com/24397251/166341885-12c7c126-41a6-4d0b-8110-e790df0707e9.png)

### Use case

When adding new users, I don't think it is secure to have Netbox user password known by the Netbox admin in some way.
I think that other than just funcionality, it improves security.

**Comment by DanSheps** [comment]
I believe this would require overriding the default DJango user class.  You should try and expand your implementation details more if you can.

**Comment by emersonfelipesp** [comment]
> I believe this would require overriding the default DJango user class. You should try and expand your implementation details more if you can.

Indeed it is something more like a Django feature than a Netbox feature. I will try to implement it and come back with some code.

**Comment by DanSheps** [comment]
Could you link the discussion here, just for reference?

**Comment by emersonfelipesp** [comment]
> Could you link the discussion here, just for reference?

It's here: [[Django Developers Group] Require password change on first login when creating new users
](https://groups.google.com/g/django-developers/c/7X_DYrkQgZI)

I haven't put a lot of information, but I think it is easy to get the point of what the feature should do.
