### ISSUE TITLE
Update the 'last_updated' timestamp on parent objects

### ISSUE THREAD

**Issue by siemhermans** [netbox-community/netbox#9283]
### NetBox version

v2.11.12

### Feature type

Change to existing functionality

### Proposed functionality

Currently, when updating (for example) a dcim.interface object in Netbox, the parent dcim.device object's `last_updated` timestamp isn't updated. Understandable, as these are separate objects, but for our use case it would be preferable to have an update on a child object also update the timestamp on the parent object. This way we don't have to recursively check all linked objects for updates.
 
I'm uncertain whether this is feasible in Django in the first place, or whether it's desirable from a project standpoint, but I'm interested in your thoughts.

### Use case

We are using NetBox to build a dynamic Ansible inventory. Due to the scale of the environment and the amount of API calls we require to build a full inventory, we've built a caching layer in a separate MongoDB which stores the (JSON) inventory. We check the timestamp of a cached inventory against the `last_updated` timestamp in NetBox. When a device is updated, it is retrieved and replaced in the cache. Otherwise a cached entry is retrieved from MongoDB.

**Comment by jeremystretch** [comment]
I don't think it makes sense to update the `last_updated` time on the parent object, because that would effect a "no-op" change record for the object. Looking at the parent object, it would not be clear to the user what changed because the change is recorded separately, on the child object.

I wonder if a webhook from NetBox to trigger an inventory update is feasible to satisfy your use case.

**Comment by DanSheps** [comment]
> v2.11.12

In the future, you should do FR's against a current version as it makes in unclear as to whether the functionality you desire has been added to a more current version without the maintainers reviewing all change logs to verify.
