### ISSUE TITLE
Add site to IP address/range model

### ISSUE THREAD

**Issue by abhi1693** [netbox-community/netbox#9290]
### NetBox version

v3.2.2

### Feature type

Data model extension

### Proposed functionality

Allow a way to assign the IP address/IP range to a site and/or region and add filtering capabilities for the same. This will add more insight into where the IP address exists in the organizational structure if it is not assigned to an interface or does not have a parent prefix.

### Use case

The IP address model does not have a site (or related) field on the model. When private IPs are used and documented on NetBox which can be on different sites, there is no way to filter them by site or region. One can have the exact same IP in 1 or more sites/regions. The same can be said for the IP ranges. In both cases, the object can be assigned to a tenant, but it is not necessary to have a tenant for the IP addresses.

In my test env, I have close to 300 IP addresses, that are not assigned to anything nor do they have a parent prefix. Without an association to a site, I do not have where in our organization, they should exist.

### Database changes

Add `site` and `region` fields to the IP address and IP range model

### External dependencies

None

**Comment by schmittvictor** [comment]
You can already do it with custom object fields.

**Comment by jeremystretch** [comment]
> In my test env, I have close to 300 IP addresses, that are not assigned to anything nor do they have a parent prefix.

Why aren't they assigned to anything? What are they used for?

**Comment by sc68cal** [comment]
I'm a 👎 on this because individual IP addresses should be tied to a `prefix` object, which already has that information. I don't think having IP addresses also support the site and region attributes and possibly conflict with their parent prefix is a good idea

**Comment by dteknet** [comment]
> I'm a 👎 on this because individual IP addresses should be tied to a `prefix` object, which already has that information. I don't think having IP addresses also support the site and region attributes and possibly conflict with their parent prefix is a good idea

Is there a way to adjust group privileges that way, so that a user only had an access to IP addresses that are related to the prefix that is assigned to the specific site?

**Comment by DanSheps** [comment]
Not easily currently, you would need #7845 to be completed first
