### ISSUE TITLE
Cable without termination (pre-patched)

### ISSUE THREAD

**Issue by mchlrv** [netbox-community/netbox#9300]
### NetBox version

v3.0.8

### Feature type

New functionality

### Proposed functionality

We pre-patch all our switches in the datacenter with fibers, but they are not terminated anywhere yet. After a new cross connect is requested and terminated at a patch panel, we raise a smart hands and ask the field engineer of the datacenter to patch the new cross connect using our pre-patched and labeled fiber after which the cable is connected.

So it would be helpful to have a functionality to have a cable connected to an interface on a device (switch) but not have it terminated on the B-side yet as this is cable is reserved / planned for future use. 

### Use case

By allowing this we can already note the cable specifications (type, label, color, length) in Netbox and only have to select a B side once it is being used.

### Database changes

- Add cable status: reserved (future use)
- Don't make B side mandatory

**Comment by jeremystretch** [comment]
#9102 is currently under development and will result in a significant overhaul of the entire cabling model in NetBox. While we're not taking any additional feature requests in this area at this time, I invite you to experiment with the new model once it has been finalized in the NetBox v3.3 beta (due in August) and provide your feedback prior to the final v3.3 release. Thanks!
