### ISSUE TITLE
Redirect back to rack view when deleting a device

### ISSUE THREAD

**Issue by jasonyates** [netbox-community/netbox#9302]
### NetBox version

3.2.2

### Feature type

Change to existing functionality

### Proposed functionality

When looking at the rack view and subsequently deleting a device, redirect back to the rack view after deletion.

Currently if you navigate from the device view to a device and then delete said device, you are redirected to the full device list and it takes several clicks to get back to the rack view. It would speed up using Netbox if you were redirected back to the rack view.

### Use case

We use Netbox on an iPad to physically audit racks, sometimes it's required to delete a device from Netbox. When doing so you are redirected back to the full device list meaning you either have to hit the back button several times to get back to the rack view or navigate to / search for the rack again to get back to where you were.

**Comment by jeremystretch** [comment]
@hagbarddenstore that's not really feasible: The rack elevations are rendered as embedded SVG documents. I mean I'm sure it's possible with enough front end code but it's not going to be worth the effort required.

**Comment by hagbarddenstore** [comment]
Ah right, forgot about that bit.

**Comment by jeremystretch** [comment]
Absent any technical solution per my comment above, I'm going to close this out. Happy to revisit if someone has a feasible implementation to propose.
