### ISSUE TITLE
Allow as URL link "file://server-xx/FolderXYZ/" for Custom Field

### ISSUE THREAD

**Issue by LHBL2003** [netbox-community/netbox#9305]
### NetBox version

v3.2.2

### Feature type

New functionality

### Proposed functionality

Ein Custom Field kann man als Type URL konfigurieren. 

z.B.
Models: DCIM > device
Name: "DCIM_Device_Dokumentation"
Label: Dokumentation
Type: URL
Description: Pfad zur Dokumentation des Einzelsystems

If I navigate to the Device, the field "Documentation" is displayed.
If I edit the device and write https://www.google.de for documentation, I can open this page in the device.
If I write "file://server-xxx/FolderXXX/"
So the link does not react. 

My local HTML test (C:\temp\Test.html) works with:
`<a href="file://server-xxx/FolderXXX/" target="_blank">Folder XXX</a>`

If it is a limitation by NetBox, I would be happy if URLs like "file://" could be supported.

### Use case

Quickly navigate to documents such as installation instructions and manuals stored in a share directory.

**Comment by kkthxbye-code** [comment]
This is a browser limitation. All the major browsers disallow file:// links unless the page you are visiting itself is a local file (which is why it works when you are testing locally).

Also, in the future, please make sure your issue is in English and you provide clear replication steps.
