### ISSUE TITLE
Configurable Logout URL

### ISSUE THREAD

**Issue by hobbyquaker** [netbox-community/netbox#9316]
### NetBox version

v3.2.2

### Feature type

New functionality

### Proposed functionality

I'd like to have a configuration option to set a custom URL for the Logout Button in Netbox.

### Use case

I'm using Authentik for authentication. This means Netbox is protected by a reverse proxy that handles authentication and hands over the logged in user to Netbox via an HTTP header, configured by the Netbox option `REMOTE_AUTH_HEADER`.

When clicking "Logout" in Netbox Menu nothing happens because no logout in Authentik is made and I'm immediatly re-logged-in in Netbox (the HTTP header set by the reverse proxy is still present because the session in Authentik is still active). To solve this problem a configurable Logout URL is needed, so the click on logout in netbox calls the sign_out URL of Authentik.

Perhaps https://goauthentik.io/docs/providers/proxy/ and https://goauthentik.io/docs/providers/proxy/#logging-out can help to get a full picture of what I'm trying to achieve.

### Database changes

None.

### External dependencies

None.

**Comment by jeremystretch** [comment]
Thank you for your interest in extending NetBox. Unfortunately, the information you have provided does not constitute an actionable feature request. Per our [contributing guide](https://github.com/netbox-community/netbox/blob/develop/CONTRIBUTING.md), a feature request must include a thorough description of the proposed functionality, including any database changes, new views or API endpoints, and so on. It must also include a detailed use case justifying its implementation. If you would like to elaborate on your proposal, please modify your post above. If sufficient detail is not added, this issue will be closed.

**Comment by jeremystretch** [comment]
Closing as there's been no further response.

**Comment by hobbyquaker** [comment]
@jeremystretch is there still something missing in the information i've given or are there other reasons why this can't be reopened?

**Comment by jeremystretch** [comment]
@hobbyquaker please provide a detailed description of the proposed configuration parameter and any changes to the views, etc.
