### ISSUE TITLE
Make MAC-addresses searchable

### ISSUE THREAD

**Issue by ecraven** [netbox-community/netbox#9318]
### NetBox version

v3.2.2

### Feature type

Change to existing functionality

### Proposed functionality

If I just enter a MAC address into the top search bar, nothing is found. It would be great to be able to search for mac addresses and find the matching interfaces.

### Use case

Find matching interfaces for MAC addresses.

### Database changes

none?

### External dependencies

none

**Comment by jeremystretch** [comment]
Thank you for submitting this issue, however it appears that this topic has already been raised. Please see issue #6435 for further discussion.
