### ISSUE TITLE
Default values

### ISSUE THREAD

**Issue by rfl64** [netbox-community/netbox#9323]
### NetBox version

v3.2.2

### Feature type

Data model extension

### Proposed functionality

Could be interesting and time saving setting default values on some items.

### Use case

in general, switches, routers, and other network devices use interfaces in access mode and native vlan 1. Only a few interfaces use tagged mode to uplink to other network devices like aps, other switches, etc.

Why not set default estate or value to interfaces?

### Database changes

set default values based on statistics or user selection

**Comment by jeremystretch** [comment]
Thank you for your interest in extending NetBox. Unfortunately, the information you have provided does not constitute an actionable feature request. Per our [contributing guide](https://github.com/netbox-community/netbox/blob/develop/CONTRIBUTING.md), a feature request must include a thorough description of the proposed functionality, including any database changes, new views or API endpoints, and so on. It must also include a detailed use case justifying its implementation. If you would like to elaborate on your proposal, please modify your post above. If sufficient detail is not added, this issue will be closed.

**Comment by jeremystretch** [comment]
Closing as there's been no further response.
