### ISSUE TITLE
Improve (or cache) Prefix Utilization calculation

### ISSUE THREAD

**Issue by lamoni** [netbox-community/netbox#9336]
### NetBox version

v3.1.5

### Feature type

Change to existing functionality

### Proposed functionality

Had some complaints about the IPAM pages (specifically Prefixes) taking a long time to load.

I realized that if we hide the Utilization column, the page takes ~500ms to load. If we show the Utilization column, it takes ~8 seconds to load that same page. For the 1000 entries, without Utilization column, it takes about 2.5 seconds to load, and with Utilization column it can take up to 20 - 25 seconds.

Can we consider caching the Utilization? Our immediate solution to this is to just hide the Utilization field, but given we should have good ways to invalidate a Utilization cache on CUD, might be something to consider.

### Use case

Improve the time it takes to load Prefixes / IPAM page. We've had complaints about how long IPAM page takes too load, and realized it was due to the Utilization column being shown/calculated.

### Database changes

Not sure

**Comment by jeremystretch** [comment]
Thank you for submitting this issue, however it appears that this topic has already been raised. Please see issue #7845 for further discussion.
