### ISSUE TITLE
Сorrect display of names and comments

### ISSUE THREAD

**Issue by KosenkoIvan** [netbox-community/netbox#9349]
### NetBox version

nexbox (v3.1.5)

### Python version

3.9

### Steps to Reproduce

Long server names go beyond the boundaries of the rack and are superimposed on the unit number
![Screenshot_1](https://user-images.githubusercontent.com/97949308/168050512-71c82e90-2c2c-4aba-8a79-3528d7f0dfb0.png)
![Screenshot_2](https://user-images.githubusercontent.com/97949308/168050523-83b91c36-ea88-4af6-bd13-5e8f1589bd73.png)

The comment field does not display transitions to the next line, this leads to incorrect display of information.
![Screenshot_3](https://user-images.githubusercontent.com/97949308/168051133-b734f082-2625-4aa0-989c-5f6cae6e84dd.png)
![Screenshot_4](https://user-images.githubusercontent.com/97949308/168051153-12d2ef28-c36e-4b13-aacc-918ec9a27157.png)

### Expected Behavior

Long names should either be scaled or scrollable.
Comments should correctly display newline breaks.

### Observed Behavior

-

**Comment by jeremystretch** [comment]
> Long server names go beyond the boundaries of the rack and are superimposed on the unit number

This has already been raised in #7134, however no one volunteered a fix. If you'd like to own that bug I'd be happy to reopen and assign it to you.

> The comment field does not display transitions to the next line, this leads to incorrect display of information.

This behavior is prescribed by the [Markdown specification](https://www.markdownguide.org/basic-syntax#line-breaks). (Use two trailing spaces to force a line break.)
