### ISSUE TITLE
Inventory Item Role filtering problem

### ISSUE THREAD

**Issue by lastorel** [netbox-community/netbox#9365]
### NetBox version

v3.2.3

### Python version

3.8

### Steps to Reproduce

I found it here <https://demo.netbox.dev/>
1. Click Inventory Item Roles
2. Click on "Inventory Items" link of any Role
3. it redirects to /dcim/inventory-items/?role_id=1
4. I see "Filters: 1"
5. But if I open filters tab - there is no any Role field to filter

**So I can't search multiple Roles and null Roles using UI**

### Expected Behavior

Filters tab contains Inventory Item Role field.

### Observed Behavior

there is no any Role field to filter

**Comment by jeremystretch** [comment]
Thank you for opening a bug report. I was unable to reproduce the reported behavior on NetBox v3.2.3. Please re-confirm the reported behavior on the current stable release and adjust your post above as necessary. Remember to provide detailed steps that someone else can follow using a clean installation of NetBox to reproduce the issue. Remember to include the steps taken to create any initial objects or other data.

**Comment by lastorel** [comment]
https://github.com/netbox-community/netbox/blob/3b3247592e7b6aa7e97434f70f960ed861c6d682/netbox/dcim/forms/filtersets.py#L1105

Right there. `role_id` omitted. That's why I don't see Role filtering form.
