### ISSUE TITLE
Changelog Retention: keep last 10 entries

### ISSUE THREAD

**Issue by PieterL75** [netbox-community/netbox#9366]
### NetBox version

v3.2.2

### Feature type

Change to existing functionality

### Proposed functionality

The Changelog retention is not based on a date. All older then (your preference here) days will be removed (60 days in my case)
I now came across an issue, that happened later than 60 days ago. I needed to know who created it and made the last update.

This made me think, it might be useful to always keep the last 10 changelog items of an object, even if they are older than (60) days, and always keep the 'created' item.

### Use case

Sometimes we need to see what happened to an object that had no changes in a long time. Who created it ? when was the last change and what was the change.
If we keep the last 10 items and the creation log item, then we have good forensics to analyze problems in the past

### Database changes

None

**Comment by jeremystretch** [comment]
> The Changelog retention is not based on a date. All older then (your preference here) days will be removed (60 days in my case)

60 days is a very low retention time. Why not set it to something much higher, or unlimited?

> If we keep the last 10 items and the creation log item, then we have good forensics to analyze problems in the past

This wouldn't solve your problem. If there had been ten or more changes to the object already, you'd still have lost the initial creation record.

**Comment by PieterL75** [comment]
Those were examples on what it could be useful for.
Having the last 10 entries will give some more visibility in the history and last modifications, even after a longer time

**Comment by jeremystretch** [comment]
My point is that it's an arbitrary number and ultimately isn't going to be very useful. It sounds like #9160 would better suit your use case. Or, you could set `CHANGELOG_RETENTION` to zero to retain history indefinitely.
