### ISSUE TITLE
Document the suggested order of operations for populating a new NetBox deployment

### ISSUE THREAD

**Issue by jeremystretch** [netbox-community/netbox#9372]
### Change Type

Addition

### Area

Installation instructions

### Proposed Changes

Extend the installation documentation to suggest the first steps for populating data. For instance, show that sites should be populated before racks, and racks before devices. A flow chart might be ideal.

**Comment by candlerb** [comment]
I think this is reasonable, and maybe could be combined with a entity relationship diagram of the key models.

An alternative would be for the UI to present an "Add new..." option when you have to select a related object.

For example: when you create a Device, it might be that the correct Manufacturer or Device Type doesn't yet exist.  It would be really nice to be able to "Add New..." for these mandatory fields, even if that just popped up a separate Netbox window.  (Assuming that the user has permissions to add such items of course).

**Comment by jeremystretch** [comment]
This has been covered as part of the overall docs refresh being worked on in the `docs-refresh` branch.
