### ISSUE TITLE
Add a Description for Module Types

### ISSUE THREAD

**Issue by mgoetze5** [netbox-community/netbox#9377]
### NetBox version

v3.2.3

### Feature type

Data model extension

### Proposed functionality

Add a Description field to dcim.module-types model, similar to the Description field in other models.

### Use case

Here is a sample sysconfig output from a NetApp A700:
```
sysconfig: slot 1 OK: X91440A: 40G high performance  
sysconfig: slot 4 OK: X91440A: 40G high performance  
sysconfig: slot 6 OK: X93140A: NetApp NVRAM10  
sysconfig: slot 8 OK: X91440A: 40G high performance  
sysconfig: slot 9 OK: X92071A: PMC PM8072; PCI-E quad-port SAS (PM8072)  
sysconfig: slot 10 OK: X91135A: HBA,4-Port FCP 32Gb PCIe
```

While it will be pretty obvious what a X91440A or X91135A module type does from the associated interface templates, the purpose of a X93140A or X92071A would be rather harder to discern (especially since NetBox does not currently have a model for SAS ports/cables). It would be nice to have a description field where I could write this module type is a "NetApp NVRAM10" or a "PMC PM8072; PCI-E quad-port SAS (PM8072)".

### Database changes

New field.

### External dependencies

./.

**Comment by jeremystretch** [comment]
The ModuleType model already has a comments field; is that not sufficient?

**Comment by mgoetze5** [comment]
I was thinking of a single-line description rather than a multi-line markdown-capable one but I guess I could use the comments field for this, yes. It just seems inconsistent with how other models work.

**Comment by mgoetze5** [comment]
Fair enough, for me the name has always been enough to understand what a DeviceType is whereas I'm more likely to be confused about various ModuleTypes, but that's subjective.

**Comment by mgoetze5** [comment]
Hi @salvadorb, I believe you're looking for Inventory Items, not Modules.

**Comment by salvadorb** [comment]
Hi @mgoetze5 in certain area yes, but the need for that is to also know if the right optic is connected to the right CWDM/DWDM mux port and using what cable.

**Comment by jeremystretch** [comment]
Please keep discussion on this issue limited to the feature request, thanks.

**Comment by jeremystretch** [comment]
Going to close this out as there doesn't seem to be anything further to discuss.
