### ISSUE TITLE
Disconnect button only works on interfaces with cables, not interfaces with "mark connected"

### ISSUE THREAD

**Issue by mgoetze5** [netbox-community/netbox#9384]
### NetBox version

v3.2.3

### Python version

3.10

### Steps to Reproduce

1. Go to /netbox/dcim/devices/123/interfaces/
2. Mark some interfaces that have "mark connected: true" for bulk editing
3. Click the "disconnect" button redirecting you to /netbox/dcim/interfaces/disconnect/
4. Confirm

### Expected Behavior

Marked interfaces are now "mark connected: false"

### Observed Behavior

A message box pops up saying "0 interfaces disconnected"

**Comment by jeremystretch** [comment]
> I think the disconnect button is for bulkremoving cables.

This is correct. The bulk disconnection function is for removing cables. If you want to instead _mark_ interfaces as connected (or not connected), you can do this using the bulk edit function.

**Comment by mgoetze5** [comment]
I realize that I can use the bulk edit function instead, this would be much more convenient for me though.
