### ISSUE TITLE
Increase character limit from 500 for extras_customlink link_url & link_text

### ISSUE THREAD

**Issue by ryanmerolle** [netbox-community/netbox#9391]
### NetBox version

v3.2.3

### Feature type

Change to existing functionality

### Proposed functionality

Increase character limit from 500 for extras_customlink link_url & link_text.

### Use case

When leveraging jinja to conditionally generate links, it would be ideal to extend out the  link limits to allow for more complex jinja templates.

### Database changes

Increase varchar limit to something like 5k or 10k.

### External dependencies

N/A

**Comment by jeremystretch** [comment]
We can probably just change these to TextFields.

**Comment by jeremystretch** [comment]
Going to tackle this in v3.3 just to avoid disrupting existing migrations.
