### ISSUE TITLE
problem with "?prefix_length=64" limit for "GET /api/ipam/prefixes/<parent_pk>/available-prefixes/"

### ISSUE THREAD

**Issue by tbk2** [netbox-community/netbox#9395]
### NetBox version

v3.2.3

### Python version

3.8

### Steps to Reproduce

We have following prefix defined: 
* prefix: `<ipv6-prefix>`::/48
* id: 11

Following child prefixes are defined:

* `<ipv6-prefix>`::/64
* `<ipv6-prefix>`:1::/64
* `<ipv6-prefix>`:2::/64
* `<ipv6-prefix>`:3::/64

To reproduce the behavior:
1. `GET /api/ipam/prefixes/11/available-prefixes/?prefix_length=64`

### Expected Behavior

```
HTTP 200 OK
Allow: GET, POST, HEAD, OPTIONS
Content-Type: application/json
Vary: Accept

[
    {
        "family": 6,
        "prefix": "<ipv6-prefix>:4::/64",
        "vrf": null
    },
    {
        "family": 6,
        "prefix": "<ipv6-prefix>5::/64",
        "vrf": null
    },
    {
        "family": 6,
        "prefix": "<ipv6-prefix>6::/64",
        "vrf": null
    },
]
```

### Observed Behavior

```
HTTP 200 OK
Allow: GET, POST, HEAD, OPTIONS
Content-Type: application/json
Vary: Accept

[
    {
        "family": 6,
        "prefix": "<ipv6-prefix>:4::/62",
        "vrf": null
    },
    {
        "family": 6,
        "prefix": "<ipv6-prefix>:8::/61",
        "vrf": null
    },
    {
        "family": 6,
        "prefix": "<ipv6-prefix>:10::/60",
        "vrf": null
    }
]
```

Is this a Bug or du I miss something?

**Comment by kkthxbye-code** [comment]
`prefix_length` is only avaliable for POST requests to available-prefixes.
