### ISSUE TITLE
Add query parameters to dcim/module API

### ISSUE THREAD

**Issue by mdoerr2s** [netbox-community/netbox#9396]
### NetBox version

v3.2.3

### Feature type

Change to existing functionality

### Proposed functionality

As discussed in [#9393](https://github.com/netbox-community/netbox/discussions/9393), the REST API for modules (dcim/module) lacks the functionality to query for modules in a specific module_bay. Also the API endpoint for module_bay, does not provide an argument for installed_device, making it hard to query for modules, located in a specific module_bay. 

Since the data model already provides the information, only additional parameters for the API need to be introduced. 

### Use case

Enable users to query for modules, located in a specific module_bay of interest. Increasing usability of API by enabling returning unique responses, without having to query devices and getting a list, where this information needs to be extracted from. 

### Database changes

No, since the data model of module already has all information needed, as can be explored via nbshell.

### External dependencies

None

**Comment by jeremystretch** [comment]
> Also the API endpoint for module_bay, does not provide an argument for installed_device, making it hard to query for modules, located in a specific module_bay.

This needs a separate issue; I've opened bug report #9597 for this.
