### ISSUE TITLE
Allow pluggables as front-port/rear-port type

### ISSUE THREAD

**Issue by netixx** [netbox-community/netbox#9400]
### NetBox version

v3.2.3

### Feature type

Change to existing functionality

### Proposed functionality

We should allow more standard types to be selected for front-port and rear-ports.

Could be either static (in the code) or configurable (eg. the user can ADD new port types in the admin UI or the configuration).

### Use case

While modeling optical devices that do TDM (Time Division Multiplexing) - or other type of MUX - we often need to associate so called "client" interfaces with one "network" interface.

I believe this use-case could be covered by using existing front-port/rear-port functionality (front-port being the "client" port and rear-port being the "network" port. The issue today is that we cannot set the correct type for the ports, since client port are often pluggables (SFP, QSFP, etc...) and that is not allowed for front and rear ports.

This wouldn't be a passive connection (like it is for patch-panels), but I think it's still the best way to model those connections, since optical devices act on the OSI layer 1.

### Database changes

None (i think) - since types are declared in code.

### External dependencies

None

**Comment by netixx** [comment]
I have read this section of the FAQ, however the idea here is not to create new interface types, but to allow front-port and rear-port to use **already existing** types (that are use for interfaces).

For example, we allow "LC/PC" for interfaces, why not allow "QSFP+" for front-ports and rear-ports ?

To clarify what I meant by "the user can ADD new port types in the admin UI or the configuration": we could allow the user to set which types are allowed among the pre-defined (static) list of types already present in Netbox for interfaces and front/rear-ports.

**Comment by AiYoriAoshi** [comment]
I understand reason behind not wanting to add Transceiver types as opposed to Fiber/Cable types which rarely see a new standard the transceivers are constantly evolving, especially QSFP nowadays and adding them all would make a long complex list but I think it would already help having the type "Transceiver" or "Transceiver Slot" with all details going into inventory but that would model the real world better than "Other" Type.

We mainly use AOC cables for DWDM equipment, so I would use "Other" as closest type. If we would use a lot LR/SR transceivers with LC connectors, I wouldn't have such a difficult time with this as technically LC type would be correct, even if it's actually not hard wired but AOC/DAC is just not a connector type now is it.

**Comment by jeremystretch** [comment]
You are conflating _interface_ types with _transceiver_ types. The two are independent attributes and this modeled separately.
