### ISSUE TITLE
Dashboard widgets

### ISSUE THREAD

**Issue by jeremystretch** [netbox-community/netbox#9416]
### NetBox version

v3.2.3

### Feature type

New functionality

### Proposed functionality

Allow customization of the NetBox dashboard (the default view) using content widgets that can be toggled and rearranged per the user's preferences. Some example widgets might include:

- General object stats (similar to what exists today)
- Most recent change log entries
- Pinned objects (#8248)
- Plugin content
- RSS feed from https://netbox.dev

A widget would take the form of a Python class inheriting from some base class provided by NetBox, and would have its own rendering logic and HTML template (similar to a view). It might make sense to have different sizes of widget (e.g. small, medium, large) to enable some control over screen space utilization without getting too granular (perhaps by leveraging Bootstrap's 12-column layout).

Dashboard layout would be tracked as a per-user preference, and administrators can define a default layout.

### Use case

The NetBox homepage currently lists only some statistics for hard-coded objects and the most recent entries from the change log. Moving to a customizable widget-based display affords users the opportunity to customize this view to include only the information most relevant to them.

**Comment by matejv** [comment]
It would be nice to have a way to "save" some list views with filters applied. For example I often found myself working on a set of devices, where I could filter a device list by some criteria. Getting back to that same filtered list is often more time consuming than it should be. (Yes I know multiple browser tabs and bookmarks exist, but... :)

I'm thinking if you could turn a list view into a widget (with one click) that had the same filters applied (essentially used the same URL) and it would show a count of matching objects with a link to that same view. Or even better, display a list of matching objects with perhaps action icons for each or something like that.

**Comment by arthanson** [comment]
Possible suggestion: For re-arrangeable widgets: https://jsfiddle.net/xlaptop2001/of7syvwx/ uses gridstack (pure javascript) and compatible with bootstrap.

**Comment by jeremystretch** [comment]
Unfortunately it doesn't look like we'll be able to squeeze this into v3.4, but hopefully we can tackle it in v3.5.

**Comment by Bierfass** [comment]
Not sure if its my chrome browser, but the headlines look much different from your gif. 
Are there some fonts missing? I like the look from your post much more. My screenshot is from https://beta-demo.netbox.dev/

![image](https://user-images.githubusercontent.com/41152397/229065140-eadf6087-24a4-43bf-bab2-8a1ccc164bb8.png)


> Mostly there. Still have some cleanup to do and more widgets to add.
> 
> ![Screen recording of dashboard widgets prototype](https://user-images.githubusercontent.com/13487278/221186668-422f3240-e047-435f-b7da-86d6172176f3.gif) [ ![Screen recording of dashboard widgets prototype](https://user-images.githubusercontent.com/13487278/221186668-422f3240-e047-435f-b7da-86d6172176f3.gif) ](https://user-images.githubusercontent.com/13487278/221186668-422f3240-e047-435f-b7da-86d6172176f3.gif) [ ](https://user-images.githubusercontent.com/13487278/221186668-422f3240-e047-435f-b7da-86d6172176f3.gif)

**Comment by jeremystretch** [comment]
They look the same to me. No substantial design changes have been made since I posted that GIF. It's likely your system is using different fonts, but I don't believe that's specific to the widgets.

Happy to consider any design changes, but please open a new issue for any proposals as this one was solely to track the feature implementation and has been closed.
