### ISSUE TITLE
Set default manufacturer on module insert

### ISSUE THREAD

**Issue by shatt79** [netbox-community/netbox#9417]
### NetBox version

v3.2.3

### Feature type

Change to existing functionality

### Proposed functionality

When inserting a module into a device, the manufacturer of the module should default to the same manufacturer as the parent device.  Eg, if I'm inserting a module into a Cisco ASR-9010, then the manufacturer of the module should be set to Cisco by default.  

### Use case

Saves time by not having to select the manufacturer of the module.  The manufacturer of the module will almost always be the same as the manufacturer of the parent.  The only exception being things like hard drive slots on servers and passive devices like modular distribution frames/patch panels.  This is why the mfg field should only **default** to the parent's mfg and not be a read-only field.    

### Database changes

None

### External dependencies

None

**Comment by jeremystretch** [comment]
This can be accomplished by pre-populating the device's manufacturer in the "add module" link: `&manufacturer_id={{ object.device_type.manufacturer_id }}` (something like that).

**Comment by shatt79** [comment]
Thanks!  And where would one go to make those changes to the link?

**Comment by jeremystretch** [comment]
Sorry that was just a general note for anyone who would like to implement this. It's a change to be made in one (or more) of the HTML templates.

**Comment by huntabyte** [comment]
I can implement this functionality.
