### ISSUE TITLE
Option to disable Webhooks

### ISSUE THREAD

**Issue by 129828** [netbox-community/netbox#9421]
### NetBox version

v3.2.3

### Feature type

New functionality

### Proposed functionality

An option in any of the option files that disables webhooks completely.

```
WEBHOOK_ENABLE= environ.get('WEBHOOK_ENABLE', 'True').lower() == 'true'
```

### Use case

For developing on a local instance of NetBox, it is useful to import databases from production to have a similar environment. However, I do not want webhooks to run. I can inspect the database import and remove them manually, the manual process is tedious, and a simple boolean option would be nice.

### Database changes

None

### External dependencies

None

**Comment by jeremystretch** [comment]
This seems like a pretty niche use case, especially when you have the option of simply disabling the RQ worker process.

>  the manual process is tedious

Select all, click "edit," set enabled to "no," and submit.

**Comment by mtbutler07** [comment]
I had a similar use case where I also needed to disable webhooks for a local & dev instance of NetBox.
It's fairly straightforward using nbshell.

```python3
webhooks = Webhook.objects.filter(enabled=True)
for hook in webhooks:
    hook.enabled = False
    hook.save()

exit()
```
