### ISSUE TITLE
 Show reservation descriptions in rack model

### ISSUE THREAD

**Issue by mini-man** [netbox-community/netbox#9442]
### NetBox version

v3.2.2

### Feature type

New functionality

### Proposed functionality

Have reservation descriptions show in the rack model

### Use case

When using the DCIM feature I found that rack reservations are a great way to get some temporary registration of what is installed in a rack. At least before you are able to properly model the device types you eventually want to use.

However if you use rack reservations the rack model just shows the rack units as occupied. In my opinion it would be much nicer if it would show the description from the reservation as well.
![60553359-418a8200-9d33-11e9-895f-9f2b1baec98e](https://user-images.githubusercontent.com/11536761/170904105-ddab035c-b5c1-4f6f-b7a1-8ddeab860195.png)

**Comment by jeremystretch** [comment]
The description field for a rack reservation is intended to hold more than a single device name, and would not easily fit into the rack elevation drawing in most cases.

**Comment by mini-man** [comment]
> The description field for a rack reservation is intended to hold more than a single device name, and would not easily fit into the rack elevation drawing in most cases.

Not the full description just an optional ‘label’ field or ‘display’. 

I also note in the example you can clearly see the difference between the different reservations. We’re currently you can also see there’s some reservations in the rack layout with no indication if they are many reservations or just one without hovering over each RU.

**Comment by jeremystretch** [comment]
Your proposal states:

> Have reservation descriptions show in the rack model

If you intended something different, please update it above to reflect your intended change(s). Be sure to note the relevant database changes as well.

**Comment by jeremystretch** [comment]
Closing this out as no further clarification has been made to the proposed change.
