### ISSUE TITLE
Copy Modules while copying device

### ISSUE THREAD

**Issue by saya6k** [netbox-community/netbox#9448]
### NetBox version

3.2.3v

### Feature type

New functionality

### Proposed functionality

Please Copy equipped module with device while device is alreasy filled with modules.

### Use case

While Copying Device with all module equipped(Not device type), I have to insert all the same modules to module bay slot.

However there are many use cases to duplicate Device, such as purchasing same hardware with exact same interface cards to use as same purpose.

**Comment by jeremystretch** [comment]
NetBox currently does not replicate _any_ related objects when cloning an object, partly because of the complex workflow that would be required to do so and partly to avoid unpleasant surprises.

**Comment by mgoetze5** [comment]
I do think that copying all related objects (interfaces, modules, power ports, etc.) would be more useful than copying none of them. If I didn't want to copy them I could create a new device instead of copying an existing one.

**Comment by jeremystretch** [comment]
Closing this out as this FR is not actionable in its current form and there has been no effort to improve it. If anyone would like to devise and propose a detailed implementation plan, you are welcome to do so in a new FR.
