### ISSUE TITLE
Upgrade django-debug-toolbar to 3.3.0+

### ISSUE THREAD

**Issue by jeremystretch** [netbox-community/netbox#9453]
### Proposed Changes

Upgrade `django-debug-toolbar` to the most recent stable release. I've held back on this because upgrading to v3.3.0 or later results in very noisy test output, and I'm not sure why. Need to dig into this some.

### Justification

Keeps the dependency current

**Comment by kkthxbye-code** [comment]
The change responsible:

https://github.com/jazzband/django-debug-toolbar/pull/1603/files#diff-e3e1201763719bc0636597a8ff2b6bf5c2bac11431ea8b59929bf885a2737357R48-R65

When there's no logging handler set, django-debug-toolbar adds one.

Adding something like this:

```
LOGGING = {
    'version': 1,
    'disable_existing_loggers': True
}
```

Or this:

```
LOGGING = {
    'version': 1,
    'disable_existing_loggers': True,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'DEBUG',
        },
    },
}
```

To the logging config prevents the log spam. Not sure if we want any logging in the tests.

We could also just not load django-debug-toolbar when testing, not sure if its useful to load it.
