### ISSUE TITLE
Bulk contacts import error when we have two groups with same name

### ISSUE THREAD

**Issue by 3bruno** [netbox-community/netbox#9460]
### NetBox version

v.3.2.4

### Python version

3.9

### Steps to Reproduce

1 - Create two groups with same name (the group can be child from another group);
2 - Try to import a contact using this group created in step 1;
3 - Gives the following error: "Row 1 group: "Vendas" is not a unique value for this field; multiple objects were found".

![image](https://user-images.githubusercontent.com/72423012/171397085-a771eee2-2945-49b2-aa8b-74bf2f376fb2.png)

![image](https://user-images.githubusercontent.com/72423012/171396958-76f17387-afdc-4ac4-93d0-1e0da062b1da.png)

### Expected Behavior

For groups that have a parent, we should be able to import the contacts.

### Observed Behavior

In Contact Bulk Import we do not have a parent group field then we receive the following error:
"Row 1 group: "Vendas" is not a unique value for this field; multiple objects were found"

**Comment by jeremystretch** [comment]
This isn't a bug, it's just a limitation of the import form: There's no way to reliably indicate a group by name because the name is not unique. Instead, you can specify `group.pk` as the column header and provide the group's database ID. This ensures that you're referencing the correct object.
