### ISSUE TITLE
Add site/location selectors to interface assignment of "Add new IP address"

### ISSUE THREAD

**Issue by dbbnrl** [netbox-community/netbox#9469]
### NetBox version

v3.2.2

### Feature type

Change to existing functionality

### Proposed functionality

I believe this is a GUI-only proposal.

In the "Interface Assignment" section of the "Add a new IP address" screen, I propose adding the usual suite of region/sitegroup/site/location/etc selectors above the Device dropdown.  This allows the user to narrow down the set of devices shown in the dropdown.

### Use case

Currently I'm aware of two workflows for assigning IPs to interfaces:

1. Via the device's interface list, by clicking on the plus icon and selecting "IP Address".  This populates the device/interface for you, but the problem is that you need to already know what to type in the Address field.  (It would be great if there was some kind of search/navigation facility here to help you select an address, but that's not in the scope of this proposal).
2. Via e.g. selecting a Prefix, then "IP Addresses", then the "Add IP Address" button or clicking on an available address.  This facilitates choosing a free address, but requires you to specify the Device.  This is difficult when there are many devices; thus this proposal.

**Comment by ITJamie** [comment]
A modal popup to search for a device might be a better option than adding all those fields to the edit/create view

**Comment by dbbnrl** [comment]
Maybe so, but I was trying to propose something that would require minimal development.

**Comment by jeremystretch** [comment]
> A modal popup to search for a device might be a better option than adding all those fields to the edit/create view

#10054 was opened to capture this initiative, and will deliver a much smoother user experience. We should focus our efforts there rather than continuing to extend already cluttered forms with additional fields.
