### ISSUE TITLE
Child location does not update when Parent location changes

### ISSUE THREAD

**Issue by chadhpaine** [netbox-community/netbox#9481]
### NetBox version

v3.2.2

### Python version

3.9

### Steps to Reproduce

1. Create more than one location, and populate each location with at least one rack with non-zero height of any type.
2. Create a parent-capable device-type with non-zero height. Add a device-bay to the parent-capable device-type.
3. Create an instance of the parent-capable device-type, and insert the device into a rack of sufficient height.
4. Create a child-capable device-type with zero height. Then create an instance of the child-capable type.
5. Insert the child-capable device into the rack and location of the parent-device, without a position.
6. In the Device-Bays tab of the parent-device, associate the child-device with the open device-bay.
7. Move the parent device into a rack of sufficient height in some other location.

### Expected Behavior

The child-device's rack and location should update according to the move associated with the parent-device.

### Observed Behavior

The child-device's rack updated according to the move associated with the parent-device, but the location of the child-device remains as it was before the parent-device was moved.

Example result: The child could have assigned-Location A but be found in a rack associated with Location B.

Example impact: The child-device cannot be updated in the UI until the discrepancy between Assigned-Location and Rack-Location is resolved:
```
Errors: Rack - Rack A15 (A15) does not belong to location B.
```

**Comment by jeremystretch** [comment]
This may be a use case for #9903 (available in v3.3).
