### ISSUE TITLE
Prefix Utilization Percentage should include child prefixes marked as 100% utilized

### ISSUE THREAD

**Issue by gabrieltackitt** [netbox-community/netbox#9489]
### NetBox version

v3.2.3

### Feature type

Change to existing functionality

### Proposed functionality

IN the Prefix view, the Utilization percentage should take into account the child prefixes that are marked as 100 percent utilized. 

### Use case

For Example: 
I have as my prefix allocation 2001:DB8::/32. I delegate out 2001:DB8:1234::/48 to Customer A. This prefix, for my purposes is now 100% utilized, as I have delegated it to A and do not care what they do with that address space, so I mark it as such. 
When calculating the utilization of my original 2001:DB8::/32, it would be nice if the utilization percentage to this child prefix into account.

**Comment by kkthxbye-code** [comment]
If you set the status of the parent prefix to container, all child prefixes will count as utilized. 

Has been discussed before: https://github.com/netbox-community/netbox/issues/8091 https://github.com/netbox-community/netbox/issues/7267

**Comment by gabrieltackitt** [comment]
Thank you for pointing this out, I must have missed it in the documentation, closing this.
