### ISSUE TITLE
Bulk delete of VM interfaces using a filter wants to delete all objects

### ISSUE THREAD

**Issue by whzzz28** [netbox-community/netbox#9499]
### NetBox version

v3.2.3

### Python version

3.9

### Steps to Reproduce

Some values that will help with explanation:

- Total VM interfaces in Netbox: 700
- Total "admin" interfaces 175 

Two methods to reproduce similar results:
**Method 1: Quick Search**
1. Go to Virtualization -> Interfaces
2. Use the Quick Search textbox and search for interfaces by a specific name (for example I have a bunch of interfaces titled "admin" so i search for "admin"). 
3. A list of results is displayed and looks appropriate for the search term. Down the bottom of the page shows it shows the number of results (Showing 1-50 of 175)
4. Click the tickbox next to "Name" to select all. 
5. A new tickbox appears above the tickbox just checked that will say "Select all X interfaces matching query".
6. Click the Delete Selected button.

**Method 2: Filters**
1. Go to Virtualization -> Interfaces
2. Go to the "Filters" tab. In the "Search" textbox type in a query. Click Search
3. A list of results is displayed and looks appropriate for the search term. Down the bottom of the page shows it shows the number of results (Showing 1-50 of 175)
4. Click the tickbox next to "Name" to select all. 
5. A new tickbox appears above the tickbox just checked that will say "Select all X interfaces matching query".
6. Click the Delete Selected button.

### Expected Behavior

Both method's have the same expected behavior.

- The "Results X" at the top of the page should be updated to show the total interfaces found by our search query ("admin" in this instance should show "Results 175")
- The "Select all X interfaces matching query" text should show the number of interfaces as returned by the query (X = 175 in this instance)
- After clicking the "Delete Selected" button, I expect to be greeted with the confirmation page of 175 interfaces based on what I selected on the previous page, based on the search query. I also expect the number of interfaces to match (175)

### Observed Behavior

**Method 1: Quick Search**

- After typing in the query "admin" I expect to see 175 interfaces appear in the list and the "Results X" number to match my query. The list of interfaces is correct and shows all 175 interfaces, but the "Results X" still lists the total interfaces (700).
- After checking the checkbox next to "Name" to select all, the new checkbox appears allowing me to select all interfaces that match my query, however this is telling me that 700 interfaces matched my query, not 175. Text says "Select all 700 interfaces matching query".
- Clicking the "Delete Selected" button loads the Confirm Bulk Deletion page. I expect this page to show all 175 interfaces matching my query that I selected for deletion. Instead I am presented with all 700 interfaces.

**Method 2: Filters**

- After setting the query to "admin" the interfaces page shows "Results 175". This is expected and is different to Method 1 above. Further down the page also shows "Showing 1-50 of 175". So far this is working as expected.
- After checking the checkbox next to "Name" to select all (current page), the new checkbox appears allowing me to select all (all pages) interfaces that match my query. This is working as expected and the text shows "Select all 175 interfaces matching query".
- After putting a check in the box to select all 175 and then clicking "Delete Selected" you are redirected to a summary page. I expect to see 175 interfaces, however instead I have all 700 interfaces in my list to delete.

**Comment by seulsale** [comment]
HI! I can take some time to replicate and fix this.
