### ISSUE TITLE
Add support for jinja2 custom filters for webhooks

### ISSUE THREAD

**Issue by tom0010** [netbox-community/netbox#9501]
### NetBox version

v3.2.3

### Feature type

Change to existing functionality

### Proposed functionality

When using webhooks, I'd like to have the ability to add some custom jinja2 filters. 
Ansible comes with some nice ones, such as `to_nice_yaml` etc. however, I'd like to have the ability to add filters where you see fit. 

Maybe something like https://github.com/tbotnz/netpalm-admin would work, where you can just paste the filter into the GUI and it'll be uploaded to the netbox instance, failing that, we could also add a `jinja2_filters` folder somewhere, where the user could just add the filters there. Similarly to the `scripts` design in Netbox. 

### Use case

It would allow users to customise the payload better when using webhooks. 

### Database changes

Not sure.

### External dependencies

Jinja2

**Comment by kkthxbye-code** [comment]
I think it makes sense to allow injecting custom jinja2 filters. I think the only implementation that would make sense for a feature is this is that we just add a configuration option similar to what we have for Custom Validation (see. [Direct Class Reference](https://docs.netbox.dev/en/stable/customization/custom-validation/)).

Allowing you to have something like this in your configuration.py (the function can of course be included from wherever).

```
def to_lower(input):
    return input.lower()

JINJA2_FILTERS = [to_lower]
````

Would that be fine for your usecase @tom0010 ? Having a field to paste code is a little icky for a feature that will be used by few.

**Comment by tom0010** [comment]
I think that would work.
Thanks @kkthxbye-code 🙂

**Comment by kkthxbye-code** [comment]
@tom0010 - It will be avaliable where jinja2 is used which is: 

* Custom Links (url and label)
* Webhooks (url, headers, body)
* Export templates
