### ISSUE TITLE
Warranty Status

### ISSUE THREAD

**Issue by advaircarvalho** [netbox-community/netbox#9502]
### NetBox version

v3.2.4

### Feature type

New functionality

### Proposed functionality

Most of the time, a device is associated with a warranty contract with an expiry date, for example 1 year.

I would like it to have a field that could put the device's warranty expiration date and another field that would show the warranty status based on the current date, that is, I would have to read the current date and subtract from the warranty expiration date to show how much time the device is still under warranty.

### Use case

This would allow users to quickly obtain strategic information for decision making from the management team.

Keeping a device under warranty is highly recommended in large IT companies, whether public or private.

### Database changes

I'm not sure.

### External dependencies

I'm not sure.

**Comment by hagbarddenstore** [comment]
A custom field and a report that checks that field can do what you need.

**Comment by advaircarvalho** [comment]
@hagbarddenstore 

Hello.  There are many features that could be solved with custom fields, but I believe that these are for peculiar features of each system user.  In this case, features like the one I suggested make sense to most users of the system, I think it could be native to NetBox.

**Comment by kkthxbye-code** [comment]
Similar or identical issues that were denied in the past:

https://github.com/netbox-community/netbox/issues/182 https://github.com/netbox-community/netbox/issues/1539 https://github.com/netbox-community/netbox/issues/4314 https://github.com/netbox-community/netbox/issues/424

I think the reasoning in #182 still applies, that it's a good fit for a plugin.

**Comment by jeremystretch** [comment]
Yep, this has been discussed numerous times and is out of scope for NetBox core. You're welcome to build a [plugin](https://docs.netbox.dev/en/stable/plugins/development/) that suits your needs.
