### ISSUE TITLE
Inconsistency in svg return from api

### ISSUE THREAD

**Issue by ekrichbaum** [netbox-community/netbox#9503]
### NetBox version

v3.2.4

### Python version

3.10

### Steps to Reproduce

1.) call api for rackface elevation (from different machine).
https://netbox.mydomain.com/api/dcim/racks/33/elevation/?face=front&render=svg&unit_width=220&unit_height=22&legend_width=30&expand_devices=true&include_images=true
where 33 is the id of the rack to generate.
2.) view source on the returned rackface.

### Expected Behavior

All references should return full url. Different machine fails on relative links to display graphics.

### Observed Behavior

Some link elements are represented with full url.  

`a fill="black" target="_top" xlink:href="https://netbox.mydomain.com/dcim/devices/89/"`

others are returned with partial.

`a target="_top" xlink:href="/dcim/devices/add/?site=3&amp;location=&amp;rack=33&amp;face=front&amp;position=27"`

As a workaround, I parsed the return and did a string replace to fill in the missing info.

**Comment by jeremystretch** [comment]
Please revise your description above to indicate exactly which element(s) you believe are affected.

**Comment by ekrichbaum** [comment]
devicetype-images are relative. "add" links are relative. device links are absolute.  My preference would be absolute links across the board, but all one way or the other is workable.
