### ISSUE TITLE
Include Network information in Prefix/Aggregate view

### ISSUE THREAD

**Issue by basti1508** [netbox-community/netbox#9505]
### NetBox version

v3.2.4

### Feature type

Change to existing functionality

### Proposed functionality

Inlcude additinal information in the Prefix/Aggregate view to make it easier for admins to get more knowledge to the network.
The example would be the output of sipcalc. For me the most valueable information is boradcast address, quick view on the usable range and cisco wildcard address.

```
$ sipcalc 10.14.0.0/19
-[ipv4 : 10.14.0.0/19] - 0

[CIDR]
Host address		- 10.14.0.0
Host address (decimal)	- 168689664
Host address (hex)	- A0E0000
Network address		- 10.14.0.0
Network mask		- 255.255.224.0
Network mask (bits)	- 19
Network mask (hex)	- FFFFE000
Broadcast address	- 10.14.31.255
Cisco wildcard		- 0.0.31.255
Addresses in network	- 8192
Network range		- 10.14.0.0 - 10.14.31.255
Usable range		- 10.14.0.1 - 10.14.31.254
```

### Use case

Get additional network information more quickly.

**Comment by jeremystretch** [comment]
What specifically are you proposing be added?

**Comment by ITJamie** [comment]
I did some of this in my gateways plugin as it was highly requested internally during our migration from racktables which had similar data. 

https://github.com/ITJamie/netbox_gateways/blob/main/docs/images/prefix_view_gw.png

**Comment by basti1508** [comment]
From the example above the most valuable information would be:

`
Network mask		- 255.255.224.0
Cisco wildcard		- 0.0.31.255
Network range		- 10.14.0.0 - 10.14.31.255
`

**Comment by weidi** [comment]
Would love to add that showing the netmask in addition to the CIDR notation for each IP would help a lot so this might not only help in the prefix view.

**Comment by PieterL75** [comment]
I have this plugin : https://github.com/PieterL75/netbox_ipcalculator
Feel free to use/modify it !

**Comment by renatoalmeidaoliveira** [comment]
Which implementation you think is better?
1 - add model methods that calculate netmask, wildcard and etc,
2 - add templatetags in the helpers that do the same thing?

**Comment by jeremystretch** [comment]
@renatoalmeidaoliveira I'd expect that most such attributes are already available via `netaddr` as properties of the prefix value. But where needed, model attributes and methods would be preferable: Template tags should only be introduced to fill a general need.
