### ISSUE TITLE
Pagination not working to browse past first page or selection item per page

### ISSUE THREAD

**Issue by fullgore** [netbox-community/netbox#9506]
### NetBox version

v3.2.4

### Python version

3.9

### Steps to Reproduce

1. Open an object that got more than 1000 items (behavor is still present with less items) or less and try to select 50 or 25 per page.
2. Second problem is selecting the second page if you have more than 1000 items
![github_issue](https://user-images.githubusercontent.com/13705515/172818867-102a66d3-28fc-4844-b836-9d2facc91eaf.JPG)

### Expected Behavior

1. Be able to select the number of items per page
2. Be able to select the second page

### Observed Behavior

Nothing is changing, selecting item per page or selecting second page have no effect.

If you add manualy in the url the : ?per_page=50 and or &page=2 everything is working, just the UI is not making the calls

**Comment by kkthxbye-code** [comment]
Thank you for opening a bug report. I was unable to reproduce the reported behavior on NetBox v3.2.4. Please re-confirm the reported behavior on the current stable release and adjust your post above as necessary. Remember to provide detailed steps that someone else can follow using a clean installation of NetBox to reproduce the issue. Remember to include the steps taken to create any initial objects or other data.

**Comment by fullgore** [comment]
Ok found that actualy with the stack we are using static files are served by a nginx (that do ssl) in front of the netbox app. As managed.py is not generating static files at startup anymore, and i use a docker volume to share statics with nginx, we where having old static files.
Did a forced managed.py collectstatic and everything is ok now. sorry for the noise.
