### ISSUE TITLE
Tenants table view: additional (computed) column fields (total devices, ips, prefixes, etc)

### ISSUE THREAD

**Issue by ITJamie** [netbox-community/netbox#9507]
### NetBox version

3.2.2

### Feature type

New functionality

### Proposed functionality

It would be great to be able to see a count of how many devices, u's of rackspace, ips/prefixes etc from the tenants table view
these would be available as "additional columns" 

### Use case

Ability to get a rough idea of tenant size / resources used from tenants list

**Comment by jeremystretch** [comment]
Thank you for your interest in extending NetBox. Unfortunately, the information you have provided does not constitute an actionable feature request. Per our [contributing guide](https://github.com/netbox-community/netbox/blob/develop/CONTRIBUTING.md), a feature request must include a thorough description of the proposed functionality, including any database changes, new views or API endpoints, and so on. It must also include a detailed use case justifying its implementation. If you would like to elaborate on your proposal, please modify your post above. If sufficient detail is not added, this issue will be closed.

**Comment by jeremystretch** [comment]
Closing this out as no further clarification has been provided.
