### ISSUE TITLE
Full path in cable trace view.

### ISSUE THREAD

**Issue by SleptsovVV** [netbox-community/netbox#9513]
### NetBox version

v.3.2.4

### Feature type

Change to existing functionality

### Proposed functionality

Add full path in cable trace view. At the moment, we see the path in the format Site/Location/Rack, I think it would be more informative to see the path in the format Site/Parent Location/Location/Rack. Currently, to achieve this effect, you have to name locations in the format ParentLocation/Location, thereby preventing the use of the functionality of parent locations (counting devices, etc.).

### Use case

More informative.

**Comment by jeremystretch** [comment]
Unfortunately there's only so much detail that can reasonably fit into a drawing. Each of the objects within a drawing is a hyperlink to the corresponding object in NetBox; following these links will take you to all other relevant information.
