### ISSUE TITLE
Trace entire cable path from power port to upstream power panel

### ISSUE THREAD

**Issue by LHBL2003** [netbox-community/netbox#9518]
### NetBox version

v3.2.2

### Feature type

New functionality

### Proposed functionality

When I look at the wiring of the power port on the device, I only see the counterpart from the next system. However, I cannot follow the current path to the power panel.

**Idee:**
The entire course up to the Power Panel is displayed. See picture:

![image](https://user-images.githubusercontent.com/46369917/173092125-174868e5-3049-467d-a153-ca507bde4019.png)

**Alternative :**

You can jump to the next Cabel Trace picture by clicking on the bottom.
This is not as nice as the first idea, but it is still helpful.

![image](https://user-images.githubusercontent.com/46369917/173093330-30832bf9-dbae-457a-9e55-481977b21754.png)

### Use case

Faster and better traceability of the circuit diagram.

**Comment by jeremystretch** [comment]
I think this should be feasible, but I need to dig into it more.

**Comment by phurrelmann** [comment]
if the full trace would now be feasible, what about summing the power usage like requested in #3377? maybe this could be realized now much more easily, too?
