### ISSUE TITLE
Location/Rack level config context

### ISSUE THREAD

**Issue by omri-ice** [netbox-community/netbox#9519]
### NetBox version

v3.2.4

### Feature type

Data model extension

### Proposed functionality

Add locations and racks to the `ConfigContext` class to match against those models and provide more granularity then sites

### Use case

In a multi section/multi level datacenter we are using locations and sub-locations to organize the physical position of devices, that also requires us to provide specific data sets depending on the location within the datacenter.

### Database changes

Additional fields to the `ConfigContext` model

**Comment by jeremystretch** [comment]
Thank you for submitting this issue, however it appears that this topic has already been raised. Please see issue #4699 for further discussion.

**Comment by jeremystretch** [comment]
I've reopened this for the location assignment piece.

**Comment by jeremystretch** [comment]
I've opened #9582 to specifically document the addition of location associations.
