### ISSUE TITLE
Add javascript support for custom scripts to dynamically populate/modify on user input on demand

### ISSUE THREAD

**Issue by tom0010** [netbox-community/netbox#9521]
### NetBox version

v3.2.4

### Feature type

New functionality

### Proposed functionality

I'd like to propose support for javascript/typescript support when using custom scripts so that the custom script webpage can be dynamically updated when a user is editing the form, such as checkboxes or selection boxes. 
I have some scripts that can potentially become very large and lengthly depending on the users requirements, however it may become overwhelming to users if the page is extremely long. 
Some more info here: https://netdev-community.slack.com/archives/C01P0FRSXRV/p1652955534907109?thread_ts=1652951978.388159&cid=C01P0FRSXRV 

### Use case

~~Better UX for the end user.~~

Edit:
We are leveraging Netbox scripts for user inputs and to execute code from a nice UI, we couple this with either some Ansible or Python code to do this. We have some scripts that actually require multiple inputs, these inputs can become very big and therefore become quite long in the Netbox script. The length of the script/page is not really an issue from a UI point of view, providing the user is required to input all of the said data. However, in some cases, there are times where a user only needs to input X amount of data, let's say they want to implement a "primary" site. Primary could be viewed as default in the script page with the option to add a "secondary" site with a button. Upon a user clicking a button, that would build the javascript page to "show" the "secondary inputs for the end user.

Another example could be for the user to show just the "required" fields from a Netbox script. 

Main reason behind this is to have a better UI as I already said, however with the current Netbox scripts if a user that is building the script creates a big Netbox script they may become too overwhelming for the end user in some cases. This change would make the Netbox scripts for friendly for the end users. 

### Database changes

~~Not sure.~~
I don't think there are any, I think this would just be leveraging javascript/typscript on top of the existing codebase in the scripts templates upon build.  

### External dependencies

None, I don't think.

**Comment by jeremystretch** [comment]
Thank you for your interest in extending NetBox. Unfortunately, the information you have provided does not constitute an actionable feature request. Per our [contributing guide](https://github.com/netbox-community/netbox/blob/develop/CONTRIBUTING.md), a feature request must include a thorough description of the proposed functionality, including any database changes, new views or API endpoints, and so on. It must also include a detailed use case justifying its implementation. If you would like to elaborate on your proposal, please modify your post above. If sufficient detail is not added, this issue will be closed.

**Comment by tom0010** [comment]
Hey @jeremystretch let me try to provide more info to fulfil that. 
I'm afraid I don't know the code well enough to understand what changes would be needed to actually solve the feature request I am raising, but I hope that with the info I'm providing in the edited OP will be enough. If not, please let me know what else you'd like me to provide :)

**Comment by kkthxbye-code** [comment]
I think we need to consider if we want to support specific use cases for dynamic control of the form, or if we just want to allow the user to pass javascript to the frontend (typescript is probably not going to happen as it would require a transpilation step).

My initial thought was to add an option to custom script fields to dynamically hide/show fields based on the value of other fields. I'm unsure of the feasibility of the implementation, but should probably be possible without too much effort.

**Comment by tom0010** [comment]
> My initial thought was to add an option to custom script fields to dynamically hide/show fields based on the value of other fields. I'm unsure of the feasibility of the implementation, but should probably be possible without too much effort.
This is was exactly what I was thinking.

**Comment by kkthxbye-code** [comment]
@MalfuncEddie - This is already supported and explained in the documentation you linked:
 
> It is also possible to reference the value of other fields in the form by prepending a dollar sign ($) to the variable's name.

```
region = ObjectVar(
    model=Region
)
site = ObjectVar(
    model=Site,
    query_params={
        'region_id': '$region'
    }
)
```

**Comment by MalfuncEddie** [comment]
@kkthxbye-code  tnx for the info.  I've got custom script that work a lot better now. Funny thing is that now it is finished I am also hitting the "it would be nice if a checkbox could hide/unhide certain inputs" fase :)

**Comment by tom0010** [comment]
@kkthxbye-code @jeremystretch I can see this has been under review for a while, any update please?

**Comment by tom0010** [comment]
@kkthxbye-code any chance this can be reviewed? You said you didn’t think it would be that much effort to implement.

**Comment by jeremystretch** [comment]
@kkthxbye-code can you take another look at this? I'm not clear on what work needs to be done (if any).

**Comment by kkthxbye-code** [comment]
@jeremystretch - I've been tinkering with it for a while, but keep running into issues with our frontend js. I'll give it another shot this weekend hopefully, and if I'm still not getting any progress I might throw in the towel and implement something in a plugin instead.

The idea boils down to dynamically disabling/enabling form fields based on other fields. A contrived example:

```
    object_type_choice = (
        ('Virtual Machine', 'vm'),
        ('Physical Device', 'device'),
    )

    object_type = ChoiceVar(choices=object_type_choice)
    device = ObjectVar(
        model=Device,
        depends_on={
            'object_type': 'device'
        }
    )
    vm = ObjectVar(
        model=VirtualMachine,
        depends_on={
            'object_type': 'vm'
        }
    )
```

When loading the form only  the `object_type` would be visible, choose Virtual Machine in the dropdown and the vm field is enabled etc. I'm not really certain of the final design, there's a lot to consider, like if we should support all field types, if we should support negation in the conditions etc. It all depends on how much the js fights me.

Happy to hear any and all input/ideas.

**Comment by davidgwatkins** [comment]
@kkthxbye-code Any progress in your JS fight?  This would be huge!

**Comment by balpoint** [comment]
Was really looking forward to this being implemented one day :(

**Comment by abhi1693** [comment]
Maybe we can take this up in v4.0

**Comment by jeremystretch** [comment]
Maybe, but this was closed as stale because no one picked it up. It can only be re-opened if someone is willing to commit to owning the implementation. Any takers?
