### ISSUE TITLE
Faster editing with 1 click on Edit

### ISSUE THREAD

**Issue by LHBL2003** [netbox-community/netbox#9525]
### NetBox version

v3.2.4

### Feature type

Change to existing functionality

### Proposed functionality

Bulk editing is not always helpful, e.g. when adjusting the VLAN name. Then you have to click on edit. 

I then do this as follows:

- Click on the edit symbol
- Scroll wheel Mouse click on Edit (to open the entry in a new tab.)
- X repetitions on the other lines.
- Edit all open tabs.

The work would be more pleasant if you didn't have to click 2 times each time.
This would work if the Edit button is split:

- Left side directly to edit.
- Right side, selection (Edit, Delete, Changelog etc.)

![image](https://user-images.githubusercontent.com/46369917/173335459-a36320e0-c63a-494b-96a3-e380d7eff676.png)

### Use case

Faster and more pleasant work. By easier clicking for editing.

**Comment by huntabyte** [comment]
@jeremystretch I have a solution to implement this feature request.

I did so by taking advantage of the _extra_buttons_ argument when calling the ActionsColumn inside the NetBoxTable class.

I retained the _warning_ color that is being used on other _edit_ buttons throughout.

If satisfied, please assign me and I'll submit a PR for review.

![netbox-1-click-edit-arrow](https://user-images.githubusercontent.com/64506580/174464017-d8845c9d-6980-42f4-813a-bdeebd90d8ec.png)

**Comment by LHBL2003** [comment]
That would already make the work easier. :)

**Comment by PieterL75** [comment]
The dropdown was made to reduce the number of buttons at the end of a table..  https://github.com/netbox-community/netbox/issues/7679 
and now adding a button there again.

Maybe the auto-open of the menu wasn't a bad idea https://github.com/netbox-community/netbox/issues/8666  :-D

I created this plugin that adds dropdowns to a lot of links, and I could't use netbox without anymore. (Only drawback is the slow loading of a page with a lot of links, at it has to update the DOM)
https://github.com/PieterL75/netbox_contextmenus

**Comment by LHBL2003** [comment]
It would be best if you could split the button in two so that the most important function can be called up immediately.

Currently, the constant double-clicking is rather exhausting. Especially with many adjustments that can't be made through bulk edit.

I need to delete 1% of the time, edit 99%.

**Comment by huntabyte** [comment]
@LHBL2003 I am in the same boat with regard to editing.

Split buttons are best when there is a primary/most frequently used action (the button) and additional, less frequently used actions (drop down).

I feel as though two buttons in a table row is not excessive and doesn't present an eye sore.

**Comment by LHBL2003** [comment]
If a dropdown split button is too difficult to implement. Then I find the version with a main button and a dropdown button to be a good and lean alternative. So I have understanding for both of you.

The optimum is of course a dropdown split button.

**Comment by jeremystretch** [comment]
The proposal here is to split the existing button into one direct link and one dropdown menu, and that is what I marked as "needs owner." You can find an example of this in [the Bootstrap 5 documentation](https://getbootstrap.com/docs/5.0/components/dropdowns/#split-button). We're not going to split it into a separate button as that would defeat the purpose of the dropdown.

This should be very easy to implement by introducing a new parameter which indicates whether the actions list should be split, retaining the first listed action as a direct link.

**Comment by huntabyte** [comment]
@jeremystretch I apologize, it is clear now what the requirements are. I can take care of this if you want to assign it to me.
