### ISSUE TITLE
Last Used field on API tokens

### ISSUE THREAD

**Issue by PieterL75** [netbox-community/netbox#9536]
### NetBox version

v3.2.3

### Feature type

Change to existing functionality

### Proposed functionality

Add a 'Last used' property to the API token

### Use case

I want to know if a token is actively being used.

### Database changes

Add 'Last used' field (datetime) to 'users_token'

**Comment by PieterL75** [comment]
@jeremystretch I have PR ready.
It adds the new field to the model, and updates the last_used when the TokenAuthentication.authenticate_credentials is called.

It does introduce a write for each API call., so it only update once a minute..

**Comment by sdktr** [comment]
Does it stil work when netbox is run in maintenance/readonly mode?

**Comment by PieterL75** [comment]
@sdktr Any request with an API key will update the last_used field, independent of the accesslevel of the API token or state of Netbox

But when reading the docs https://docs.netbox.dev/en/stable/configuration/dynamic-settings/#maintenance_mode and this comment https://github.com/netbox-community/netbox/discussions/6219 , I think we should not update the last_used field when in maintenance mode. 

Thank you for pointing that out, I'll update the PR
