### ISSUE TITLE
IPAM IP Addresses List no Filter Column Device/VM

### ISSUE THREAD

**Issue by LHBL2003** [netbox-community/netbox#9540]
### NetBox version

v3.2.4

### Feature type

Change to existing functionality

### Proposed functionality

Filter the IPAM IP Addresses List by Device/VM.

### Use case

Intuitively, you open the list of IP addresses and want to check which IP addresses are assigned to certain devices. This is not possible in this way because the filter ignores the Device/VM column.

So you have to go to the device and list the interfaces.
But this is more complicated if you want to check many devices.

**Comment by huntabyte** [comment]
I'm working on this issue.
