### ISSUE TITLE
ciscodnacnetbox Device Sync issue

### ISSUE THREAD

**Issue by netzbus** [netbox-community/netbox#9561]
### NetBox version

v3.2.4

### Python version

3.9

### Steps to Reproduce

1. Install ciscodnacnetbox plugin
2. click on status of ciscodnacnetbox plugin
3. click Device Sync or Full Sync

### Expected Behavior

Devices should be imported
Site sync is working

### Observed Behavior

I get an Server Error
<class 'KeyError'>

'FGL245AVBXN'

Python version: 3.9.5
NetBox version: 3.2.4

<html>
<body>

ciscodnacnetbox.ciscodnac.data.full_sync | Traceback (most recent call last): File "/opt/netbox/venv/lib/python3.9/site-packages/rq/worker.py", line 1061, in perform_job rv = job.perform() File "/opt/netbox/venv/lib/python3.9/site-packages/rq/job.py", line 821, in perform self._result = self._execute() File "/opt/netbox/venv/lib/python3.9/site-packages/rq/job.py", line 844, in _execute result = self.func(*self.args, **self.kwargs) File "/opt/netbox/venv/lib/python3.9/site-packages/ciscodnacnetbox/ciscodnac/data.py", line 23, in full_sync devices = Data.sync_devices(**kwargs) File "/opt/netbox/venv/lib/python3.9/site-packages/ciscodnacnetbox/ciscodnac/data.py", line 322, in sync_devices slug=site_members[device.serialNumber], KeyError: 'FGL245AVBXN'
-- | --

</body>
</html>

**Comment by kkthxbye-code** [comment]
Plugins are community made and as such any issues must be reported to the creator and not the main netbox project.
