### ISSUE TITLE
Custom Validator on Tags at Update.

### ISSUE THREAD

**Issue by darcynz** [netbox-community/netbox#9573]
### NetBox version

v3.1.11

### Feature type

New functionality

### Proposed functionality

When validating input, a user should be able to have tags validated when updating an object in real time.

Currently a tag must be saved first before it can be checked by Custom Validators.  

This would then function the same as custom fields.

### Use case

Tags are a powerful feature in Netbox and can be enriched via custom scripts or reports.  Eg we check state of other tools and apply a tag to a device.

If we tags are validated in real time we could check them as a condition to move from one state to another, eg Staged -> Active.

### Database changes

unsure.

### External dependencies

none

**Comment by jeremystretch** [comment]
Thank you for your interest in extending NetBox. Unfortunately, the information you have provided does not constitute an actionable feature request. Per our [contributing guide](https://github.com/netbox-community/netbox/blob/develop/CONTRIBUTING.md), a feature request must include a thorough description of the proposed functionality, including any database changes, new views or API endpoints, and so on. It must also include a detailed use case justifying its implementation. If you would like to elaborate on your proposal, please modify your post above. If sufficient detail is not added, this issue will be closed.

**Comment by darcynz** [comment]
Apologies, I tried to explain it as best as I could. I realize that this might be a problem I'm facing, but see the issue with not being able to validating Tags in real time others will face at some point. 

Our primary use case is that we create a exception tag for corner cases. For example, not all devices have an Asset tag, or we want to mark install date for new devices, but we don't know the install date for existing devices.

If i want to make these fields mandatory then users need a way to account for the exception, and I'd prefer not to put in incorrect information or a fake date for example '1900-1-1'...

Tags would be ideal, but I could also use custom fields, my problem here is that the user can't easily bulk update a custom field. But I might be able to create a custom script for that. Perhaps bulk update of multi list custom field could be a feature request instead?

**Comment by jeremystretch** [comment]
I'm afraid it's still not clear what you're proposing, or really what problem you're trying to solve. Perhaps it would be best to start a [new discussion](https://github.com/netbox-community/netbox/discussions/new) outlining your problem and seeking potential solutions.

I'm going to close this for now as there's no concrete change being proposed.
