### ISSUE TITLE
Unable to create contact with same name and group but with different email

### ISSUE THREAD

**Issue by abhi1693** [netbox-community/netbox#9581]
### NetBox version

v3.2.5

### Python version

3.9

### Steps to Reproduce

1. Create a contact group named `CG1`
2. Create a contact with the following properties

```
name: Abhimanyu
group: CG1
email: abhi1@gmail.com
```

3. Create another contact with the following properties

```
name: Abhimanyu
group: CG1
email: abhi2@gmail.com
```

### Expected Behavior

I should be able to create a contact with a different email address with the same name and group

### Observed Behavior

Unable to create a contact as the unique constraint set on `name` and `group` does not allow it

**Comment by jeremystretch** [comment]
This is desired behavior to protect against duplication. Each contact within a group must have a unique name.

**Comment by DanSheps** [comment]
Are they the same person?

Try to find a way to differentiate their names perhaps?

**Comment by abhi1693** [comment]
@DanSheps Those are different people. This information comes from a 3rd party application which handles invoicing for us. So, we cannot even make changes to the name or email otherwise the same would reflect on their invoices.
