### ISSUE TITLE
Offer search via OpenSearch

### ISSUE THREAD

**Issue by thomas-mc-work** [netbox-community/netbox#9589]
### NetBox version

v3.1.11

### Feature type

New functionality

### Proposed functionality

Offer the search feature according to the OpenSearch standard.

see https://developer.mozilla.org/en-US/docs/Web/OpenSearch

### Use case

This very tiny feature would allow users to add their NetBox instance as a search engine directly in their browser.

### Database changes

Database not affected

### External dependencies

None

**Comment by adamboutcher** [comment]
This could be really helpful, especially for mobile/handheld devices

**Comment by adamboutcher** [comment]
I think something like this might work:

In the global head:
```
<head>
  <link rel="search" type="application/opensearchdescription+xml" title="Netbox Search" href="./NetboxAllOSearch.xml" />
</head>
```

NetboxAllOSearch.xml:
```
<?xml version="1.0" encoding="UTF-8" ?> 
<OpenSearchDescription xmlns="http://a9.com/-/spec/opensearch/1.1/">
     <ShortName>Netbox</ShortName>
     <Description>Netbox All Objects Search</Description>
     <Image width="16" height="16" type="image/x-icon">[https://nextbox.example.com/favicon.ico]</Image>
     <Url type="text/html" template="https://netbox.example.com/search/?q={searchTerms}"/>
</OpenSearchDescription>
```

**Comment by cpund** [comment]
> New functionality
> ### Proposed functionality
> 
> Offer the search feature according to the OpenSearch standard.
> 
> see https://developer.mozilla.org/en-US/docs/Web/OpenSearch
> ### Use case
> 
> This very tiny feature would allow users to add their NetBox instance as a search engine directly in their browser.

If I'm understanding what this means, it is already working, no? At least per Mozilla's featureset, I can right click the search bar in Netbox and give it a keyword (nb, in my case), and then type "nb John Smith" and it'll search Netbox and my contact named John Smith shows up.

**Comment by a084ed22** [comment]
If I'm understanding this issue correctly, what is proposed here is slightly different from Mozilla's option available through right click on the search box, but is rather about the magnifying glass that appears in firefox's search bar, like in this example:
![image](https://user-images.githubusercontent.com/90847254/189121282-1bada6be-cf41-43cf-bbfb-2c92caccd470.png)

**Comment by thomas-mc-work** [comment]
@a084ed22 is right. That is a different feature. The former one works with almost every text field, but it only assigns a shortcut key so be used in the address bar. The latter is the proper search engine integration.
