### ISSUE TITLE
Provide netbox as multi arch container image

### ISSUE THREAD

**Issue by mblaschke-daimlertruck** [netbox-community/netbox#9593]
### NetBox version

v3.2.5

### Feature type

New functionality

### Proposed functionality

Netbox should be provided as multi arch image (at least amd64 and arm64) using docker buildx

### Use case

More and more cloud providers are offering ARM64 machines and also Apple MacBook M1 is only running ARM64 docker

**Comment by jeremystretch** [comment]
This repository does not include any sort of pre-packaged distribution, as it is necessarily limited to the application code itself. You may consider raising your proposal with the [netbox-docker](https://github.com/netbox-community/netbox-docker) project, or starting your own.

**Comment by mblaschke-daimlertruck** [comment]
duplicate of https://github.com/netbox-community/netbox-docker/issues/468
