### ISSUE TITLE
Insert SFP Module in Interface

### ISSUE THREAD

**Issue by adarshharisree** [netbox-community/netbox#9602]
### NetBox version

v3.2.4

### Feature type

New functionality

### Proposed functionality

It will be beneficial to have an option to add SFP module details add to the switch, router or server interfaces. Most of the device's interfaces are SFP or SFP+. Currently, we are mentioning the interface type modular but are not able to mention which type of SFP is inserted.

We are currently connecting the SPF+ Port to the front-rear or to another device.

1. Simplex or Duplex
2. WaveLength
3. WDM/DWDM/CWDM
4. 1G or 10G
5. Connector Type : LC or SC
6. Multimode or Singlemode

As part of inventory, we can add the serial number of each SFP Modules,

### Use case

Based on the SFP Module the connection between interface and front port may change

1. For Duplex SFP+ we need 1:2 mapping for interface to front-port
2. For Simplex SFP+ we need 1:1 mapping for interface to front-port
3. Inventory data of all used SFP Modules 

### Database changes

1. Additional Colum to add the inserted SFP module details in the **Interface table**
2. Additional table to list down the SFP module characteristics.

**Comment by adamboutcher** [comment]
https://github.com/netbox-community/netbox/issues/8980
https://github.com/netbox-community/netbox/issues/9377
