### ISSUE TITLE
Add Location to Circuit Termination

### ISSUE THREAD

**Issue by gjvc** [netbox-community/netbox#9604]
### NetBox version

v3.2.5

### Feature type

Data model extension

### Proposed functionality

When editing a circuit termination, i can specify "Region", "Site group", and "Site", but not "Location".

I would like to specify the "Location" field (optionally) as part of the termination.

### Use case

We have cross-connects between our cage and cages of other tenants in Equinix.  Each tenant's cage is identified by placing the Equinix cage ID in the "Location" field, and this works well in the "Region / Site Group / Site / Location" containment hierarchy.

Right now I am having to specify the tenant's cage as the "Site", because "Location" is not available to me when editing the circuit termination, which makes for something of an impedance mismatch.

### Database changes

add foreign key from `CircuitTerminations` to `Location`, (where `null=True`)

### External dependencies

None

**Comment by gjvc** [comment]
basic diff (no migration or PR yet etc) here https://github.com/netbox-community/netbox/compare/develop...gjvc:9604-add-location-to-circuittermination for clarity

**Comment by eronlloyd** [comment]
As a service provider trying to get better PoP records for interconnects, etc., I think this could help. @gjvc do you think you can complete your code as a PR in the near future?

**Comment by gjvc** [comment]
@eronlloyd Certainly can!   I will make an diff against develop this week and create a PR.  Thank you for your consideration. :-)

**Comment by gjvc** [comment]
@jeremystretch would you be able to provide a milestone for this?

**Comment by GoldyXXD** [comment]
This would be very handy for us as well. For us Sites is more of a 'compound' large area. Whereas Locations is down to the building within that area. And multiple circuits could come into different buildings.

**Comment by lorsung** [comment]
I agree with @GoldyXXD, we have sites with multiple demarcs and this would be really helpful.
