### ISSUE TITLE
API Documentation Updates (Migrate from drf-yasg -> drf-spectacular)

### ISSUE THREAD

**Issue by huntabyte** [netbox-community/netbox#9608]
### Proposed Changes

I would like to work on updating the API documentation, however, the current package used to generate and manage the swagger docs lacks functionality, doesn't support OpenAPI 3.0, and isn't being actively maintained.

[drf-spectacular ](https://github.com/tfranzel/drf-spectacular) is being actively maintained and provides some of the missing functionality.

I'd like to work on making this happen.

### Justification

This would improve the developer's experience when building applications that interact with NetBox.

**Comment by arthanson** [comment]
@huntabyte are you still available and wanting to work on this?

**Comment by huntabyte** [comment]
@arthanson Yes, for sure.

**Comment by arthanson** [comment]
@huntabyte any progress on this so far?  I saw a couple other issues that OpenAPI 3 would be nice for.
