### ISSUE TITLE
Add Contact Phone/Email to quick view panes to save time

### ISSUE THREAD

**Issue by ataylor93** [netbox-community/netbox#9625]
### NetBox version

V3.2.5

### Feature type

Change to existing functionality

### Proposed functionality

Add contact phone number and email to the quickview panes for contacts.

Majority of the time when we look for a contact, we want their contact details - this would save time navigating into the substructure for information.

![image](https://user-images.githubusercontent.com/108404623/176425756-e4344f97-dd51-4412-bd3d-486a8ba2b06b.png)

### Use case

Save time navigating for contact details.

**Comment by barnebyte** [comment]
This looks like a perfect candidate for me to get familiar with contributing to the project. Feel free to assign it to me.

**Comment by barnebyte-timewarp** [comment]
This looks like a perfect candidate for me to get familiar with contributing to the project. Feel free to assign it to me.
