### ISSUE TITLE
VlanGroup - ArrayField rather than a start/end range

### ISSUE THREAD

**Issue by PieterL75** [netbox-community/netbox#9627]
### NetBox version

v3.2.5

### Feature type

Change to existing functionality

### Proposed functionality

a VLAN Group has the option to limit the vlans that can be used in that group.
This FR is to make the vlan-member a comma-separated value and allow more that one range or separate vlans in a vlan group.

### Use case

We have use cases where one group consists of 2 different ranges (1000-1099, 2500-2599 for example).
Currently we have to create a second group, or extend the vlangroup with vlans that should not be used in that group.

### Database changes

- Remove the min_vid, max_vid values
- Replace with a ArrayField of Vlan/VlanRanges ?

**Comment by jeremystretch** [comment]
#9083 proposed something similar, but the transition to a single ArrayField seems more efficient.

**Comment by jeremystretch** [comment]
Need to put a bit more thought into how best to implement this. We do something similar with rack reservation units, however in that case we're actually storing a discrete integer for each rack unit to which the reservation applies. This doesn't scale well to ~4K VLAN IDs. We may be able to leverage an array of PostgreSQL [range fields](https://docs.djangoproject.com/en/4.0/ref/contrib/postgres/fields/#range-fields), but further research is needed.

While I would have liked to pursue this in v3.3, we're running a bit behind with this release as it is.

**Comment by jcralbino** [comment]
Hello Jeremy,
I wanted to know if this scenarios can be supported in this next iteration this range functionality. :
1. Creation of several vlan ranges, that can be assigned to the a vlan pool. 
2. Each vlan range, can be defined with a separate status field to be configurable ( active, reserved.. ) 
3. A vlan pool, can include several different ranges

I would say that the vlan range can be a separate model itself where additional information can also be added to this object, like comments, or even the change log to monitor changes in the range definition.

**Comment by abhi1693** [comment]
Is it possible to take this up in v3.5?

**Comment by jeremystretch** [comment]
It might be possible to employ an ArrayField of RangeFields.

**Comment by jeremystretch** [comment]
Just noting for posterity: PostgreSQL 14 introduces native [multirange types](https://www.postgresql.org/docs/current/rangetypes.html), which would be ideal. However, we would need to drop support for PostgreSQL 12 and 13 to utilize these. Additionally, these types appear [unlikely to be supported by Django](https://code.djangoproject.com/ticket/33238), so we would need to device our own implementation for the ORM.
