### ISSUE TITLE
Implement simple pre-configured user permissions for general use cases

### ISSUE THREAD

**Issue by artiomello** [netbox-community/netbox#9633]
### NetBox version

v3.2.3

### Python version

3.10

### Steps to Reproduce

Try to configure view-only permissions to any logical subset in less than a day.

### Expected Behavior

There should be a way of granting general use case type of permissions **_quickly and easily_** out of the box without spending crazy hours on configuring custom complicated filters.

### Observed Behavior

Currently there's no easy way of creating a simple (e.g. view-only) permission to a specific parent object (e.g. Region) that would encompass all its related child objects without spending a substantial amount of time on creating some overly complicated filter that is next to impossible to plan out in advance due to every component having a distinct set of properties. 

Sure, the level of granularity that this filtering approach provides is a godsend to any infrastructure control freak, but there are many cases where you would simply want to grant view-only to all object in a specific region/location/site that would display all related linked (circuits, devices, connections, etc) and their respective child objects without spending days on figuring out the filtering schema.

Right now if I select DCIM>region I would expect to set a filter to a specific region and see everything, but I end up seeing only that specific region info page void of any other child object information. Adding Circuits with the same region filter breaks everything because there's no such property on these object.

**Comment by jeremystretch** [comment]
This is obviously not a bug. You're welcome to open a [feature request](https://github.com/netbox-community/netbox/issues/new?assignees=&labels=type%3A+feature&template=feature_request.yaml) if you'd like to propose a specific improvement.
