### ISSUE TITLE
Implement simple pre-configured user permissions for general use cases

### ISSUE THREAD

**Issue by artiomello** [netbox-community/netbox#9636]
### NetBox version

v3.2.3

### Feature type

New functionality

### Proposed functionality

Currently there's no easy way of creating a simple (e.g. view-only) permission to a specific parent object (e.g. Region) that would encompass all its related child objects without spending a substantial amount of time on creating some overly complicated filter that is next to impossible to plan out in advance due to every component having a distinct set of properties to filter for.

Sure, the level of granularity that this filtering approach provides is a godsend to any infrastructure control freak, but there are many cases where you would simply want to grant view-only to all object in a specific region/location/site that would display all related linked (circuits, devices, connections, etc) and their respective child objects without spending days on figuring out the filtering schema.

### Use case

Right now if I select DCIM>region I would expect to set a filter to a specific region and see everything, but I end up seeing only that specific region info page void of any other child object information. Adding Circuits with the same region filter breaks everything because there's no such property on these object.

There should be a way of granting general use case type of permissions quickly and easily out of the box without spending crazy hours on configuring custom complicated filters.

Our specific use case is as follows. We have multiple regions with one to several geographical locations within them, each having one or two data DCs with racks, equipment, connections and whatnot. We need to be able to provide typical (e.g. read-only) permissions to local IT personnel within that region/site/location that would grant them the ability to e.g. view ALL their assets without having admins to spend days on figuring out how to do it using convoluted permission/object/filter combination to do so.

That is, I cannot select all object types (or some subset of them), tick the "can view" action and type in "Region=Texas" in the filter as it immediately starts spewing out errors because such and such object collection doesn't have the property region defined. Instead I have to configure the "Texas Region view-only" permissions as if I'm trying to add custom permissions to modify some specific vlan with IDs ranging from 123 to 234 in one specific location that is active and is not reserved and has a tag called purple attached to it with a tenant name that doesn't start from the letter A.

I hope you get the idea - the most obvious general permission use cases, besides "admin" that is, require complex filtering, tagging and a combination of both.

**Comment by jeremystretch** [comment]
Thank you for your interest in extending NetBox. Unfortunately, the information you have provided does not constitute an actionable feature request. Per our [contributing guide](https://github.com/netbox-community/netbox/blob/develop/CONTRIBUTING.md), a feature request must include a thorough description of the proposed functionality, including any database changes, new views or API endpoints, and so on. It must also include a detailed use case justifying its implementation. If you would like to elaborate on your proposal, please modify your post above. If sufficient detail is not added, this issue will be closed.

**Comment by artiomello** [comment]
> Thank you for your interest in extending NetBox. Unfortunately, the information you have provided does not constitute an actionable feature request. Per our [contributing guide](https://github.com/netbox-community/netbox/blob/develop/CONTRIBUTING.md), a feature request must include a thorough description of the proposed functionality, including any database changes, new views or API endpoints, and so on. It must also include a detailed use case justifying its implementation. If you would like to elaborate on your proposal, please modify your post above. If sufficient detail is not added, this issue will be closed.

Hi. I've updated the Use Case in the main post above. I'm not a developer therefore I don't understand how deeply you want me to convey the idea. Same goes for DB changes and APIs - how am I supposed to know what you guys need to change in order for this to work smoothly out-of-the-box. I think it's pretty straight-forward though. Either that or I'm blindly missing some configuration tick or trick to achieve the result. Anyway, hope that helps. Thank you.
