### ISSUE TITLE
Group checks are case-sensitive

### ISSUE THREAD

**Issue by jschewebbn** [netbox-community/netbox#9640]
### NetBox version

v3.1.7

### Python version

3.8

### Steps to Reproduce

Use LDAP as the group authentication provider.
I am adding permissions using the REST API.

### Expected Behavior

If I enter the group name "test" into the API and LDAP returns "TEST" the permission is denied until I modify the permission to reference "TEST". The checking of groups should not be case-sensitive.

### Observed Behavior

Access is denied.

**Comment by jeremystretch** [comment]
Thank you for opening a bug report. Unfortunately, the information you have provided is not sufficient for someone else to attempt to reproduce the reported behavior. Remember, each bug report must include detailed steps that someone else can follow on a clean, empty NetBox installation to reproduce the exact problem you're experiencing. These instructions should include the creation of any involved objects, any configuration changes, and complete accounting of the actions being taken. Also be sure that your report does not reference data on the public NetBox demo, as that is subject to change at any time by an outside party and cannot be relied upon for bug reports.

**Comment by jschewebbn** [comment]
I was hoping that someone would be able to easily say that's expected or not. I'll work on more detailed instructions.
