### ISSUE TITLE
Document how to generate Pre-Change Data for existing objects on the Custom Scripts page

### ISSUE THREAD

**Issue by hagbarddenstore** [netbox-community/netbox#9651]
### Change Type

Addition

### Area

Functionality/features

### Proposed Changes

The documentation page for Custom Scripts covers how to create new objects, but doesn't cover the caveats when updating an existing object.

#### Writing Custom Scripts

....the already existing text...

To generate the correct change log data when editing an existing object, a snapshot of the object must be taken before making any changes to the object.

```python
if obj.pk and hasattr(obj, 'snapshot'):
    obj.snapshot()

obj.property = "New Value"

obj.save()
```

**Comment by candlerb** [comment]
> To generate the correct change log data when editing an existing object, a snapshot of the object must be taken before making any changes to the object.

And if you're going to do this properly, make sure you include a [`full_clean()`](https://stackoverflow.com/questions/4441539/why-doesnt-djangos-model-save-call-full-clean) as well:

```
...
obj.property = "New Value"
obj.full_clean()      # <<<<< NOTE!
obj.save()
```

Otherwise, you can set `obj.property` to an invalid value, and it will still be saved successfully.
