### ISSUE TITLE
Add platform to device type

### ISSUE THREAD

**Issue by powerscooter** [netbox-community/netbox#9653]
### NetBox version

v3.2.3

### Feature type

New functionality

### Proposed functionality

Hello,

is it possible to add the point "management - platform" to the device type, so that this is inherited by the device as soon as it is created?

### Use case

We use this option to document the running system of the devices. For example: Juniper -> Junos

Since this is the same for each device type, you could save the step of entering it manually. 
Another point would be that less mistakes are made when entering data.

**Comment by shatt79** [comment]
Could something like this be expanded out to modules as well?  I'd love to be able to only install certain modules in specific devices.  Eg, only modules in the ASR9K family can be installed in an ASR9K platform/device.

**Comment by jeremystretch** [comment]
I think it makes sense to add an optional "default platform" field to the DeviceType model. If set, this will be automatically populated on instantiated devices, however (as with components) it can still be modified afterward.

> Could something like this be expanded out to modules as well?

Possibly, but please open a separate FR if that's something you'd like to propose.
