### ISSUE TITLE
Quickfilter shows wrong available IPs

### ISSUE THREAD

**Issue by PieterL75** [netbox-community/netbox#9663]
### NetBox version

v3.2.4

### Python version

3.9

### Steps to Reproduce

1. Create an prefix 172.20.200.0/24
2. create a number of ip addresses in that prefix
3. Go to the prefix 172.20.200.0/24 -> ip addresses
4. enter a value in the QuickFilter that wont match any ip address
![image](https://user-images.githubusercontent.com/74899468/177319985-33c92429-780b-4380-a9a4-75ce3e80e277.png)

### Expected Behavior

'Available IP's' should show only the real amount of available ips

### Observed Behavior

The list shows 254 available ips
![image](https://user-images.githubusercontent.com/74899468/177320057-7222148f-5321-4f9f-9d01-9847a9a7df7a.png)

**Comment by jeremystretch** [comment]
> 'Available IP's' should show only the real amount of available ips

This isn't really feasible without performing an entirely separate query in addition to the primary one. It also seems unnecessary, given that if you're searching for a particular IP, you probably aren't interested in seeing the available IP counts.

What we could do to avoid confusion is simply remove the annotations when filtering is applied.
