### ISSUE TITLE
Display FHRP Group Description when assigning the group to an IP address

### ISSUE THREAD

**Issue by jcoeder** [netbox-community/netbox#9673]
### NetBox version

v3.2.5

### Feature type

Change to existing functionality

### Proposed functionality

When assigning an FHRP Group to an IP address the description of the group should be displayed in the drop down alongside the standard information: Protocol, Group ID, and IP address.  It should look something like this.

![image](https://user-images.githubusercontent.com/18300326/177638185-6e5656c9-36c4-4891-af08-02fc8509b094.png)

### Use case

When assigning an FHRP Group to an IP address the only information that is displayed in the drop down is the Protocol and Group number and IP address, if one is assigned.

![image](https://user-images.githubusercontent.com/18300326/177639056-905b92f5-bc8c-4a83-a1fa-c9f0a108ad00.png)

Given a group without any IP addresses assigned, the protocol and group ID is not enough information to determine the exact FHRP group I wish to use.  I think the FHRP group model needs extended in the long run to have some type of site, switch fabric, or VLAN based domain or grouping but this is a quick and easy work around in the meantime and useful regardless.

In my case I have the same VLANs and thus the same FHRP group IDs configured at two different sites (not stretched).  I don't think the same FHRP group should be shared between two distinct sites so I create two groups with the same protocol and ID but a different description.  When I attempt to assign an IP address to a FHRP group the information displayed in the drop down menu is not descriptive enough.  By displaying the description in the drop down we can reference the correct FHRP group.

Another user @jlebherz already attempted to submit this but did not go through the effort to create and issue, thus is was closed.  https://github.com/netbox-community/netbox/pull/8440/files

### Database changes

None.

### External dependencies

None.

**Comment by jeremystretch** [comment]
Thank you for submitting this issue, however it appears that this topic has already been raised. Please see issue #8439 for further discussion.
