### ISSUE TITLE
Add Tenant Group column to tables

### ISSUE THREAD

**Issue by hagbarddenstore** [netbox-community/netbox#9686]
### NetBox version

v3.2.5

### Feature type

New functionality

### Proposed functionality

Add a new column to display the Tenant Group of the records Tenant.

This would require a new column `tenant_group` on all tables which also has the `tenant` column.

It would not be a default column.

It would also require (For performance reasons) that the tenant.group is prefetched in all views.

### Use case

Our use case is that we represent a customer as a Tenant Group and theirs different contracts as Tenants. This means that we end up with a contract number as the Tenant name, which makes it a bit hard to figure out at a glance which customer a thing belongs to.

If we could add the Tenant Group (Which contains the customer name) to the table, it would solve our user experience issue.

### Database changes

None

### External dependencies

None

**Comment by jeremystretch** [comment]
This should probably be done using a mixin class to define both the `tenant` and `tenant_group` columns for each of the relevant tables.

**Comment by hagbarddenstore** [comment]
> This should probably be done using a mixin class to define both the `tenant` and `tenant_group` columns for each of the relevant tables. (`tenant_group` can be a regular column with `linkify=True`.)

I agree, that was actually the first thing I looked for.

Is there a clever way of adding the column to the `Meta.fields` list or should that be up to the table class to define?

Btw, I can implement this FR.
