### ISSUE TITLE
have a permanent link to the latest report/script result

### ISSUE THREAD

**Issue by rebortg** [netbox-community/netbox#9688]
### NetBox version

v3.2.5

### Feature type

New functionality

### Proposed functionality

Have a permanent link to the latest report or/and script result will increase the speed get the result i want.

### Use case

We have a large amout of long running reports. The reports runs at night per script and must check in the morning by some people.

### Database changes

i think none

### External dependencies

none

**Comment by jeremystretch** [comment]
Thank you for your interest in extending NetBox. Unfortunately, the information you have provided does not constitute an actionable feature request. Per our [contributing guide](https://github.com/netbox-community/netbox/blob/develop/CONTRIBUTING.md), a feature request must include a thorough description of the proposed functionality, including any database changes, new views or API endpoints, and so on. It must also include a detailed use case justifying its implementation. If you would like to elaborate on your proposal, please modify your post above. If sufficient detail is not added, this issue will be closed.
