### ISSUE TITLE
Unable to edit IP address after assignment to FHRP group

### ISSUE THREAD

**Issue by Ben0it** [netbox-community/netbox#9692]
### NetBox version

v3.2.5

### Python version

3.9

### Steps to Reproduce

1. Create FHRP group and assign IP address to it
2. Try to edit IP address created in 1.

### Expected Behavior

The IP address should be editable as usual

### Observed Behavior

An error shows up : 

![image](https://user-images.githubusercontent.com/25719453/178007348-6d24e3a1-1f22-48b6-b45d-32a817ec664b.png)

**Comment by jeremystretch** [comment]
Thank you for submitting this issue, however it appears that this topic has already been raised. Please see issue #9575 for further discussion.
