### ISSUE TITLE
List current installed version

### ISSUE THREAD

**Issue by NULLProtogen** [netbox-community/netbox#9693]
### NetBox version

Unknown

### Feature type

Change to existing functionality

### Proposed functionality

As the title says, how do I find out what version is currently installed? I don't see it listed anywhere in the GUI and I was not able to find a CLI command to check.

I may have missed it but if not I would like to see this added.

### Use case

Knowing what version you are currently running and if you should update.

**Comment by peterbaumert** [comment]
Down in the right of the page.

**Comment by kkthxbye-code** [comment]
The version is shown in the footer. If the instance is not running, you can check the settings.py file in your netbox folder.

https://github.com/netbox-community/netbox/blob/a40ab9ffb1bfc9404ceb38d607d98baaaa1ab78e/netbox/netbox/settings.py#L32

**Comment by NULLProtogen** [comment]
Thanks. Not sure how I missed it there. LOL.

**Comment by jeremystretch** [comment]
FYI it's also available via the REST API at `/api/status/`.
