### ISSUE TITLE
Prefetch related properties in `DeviceListView`

### ISSUE THREAD

**Issue by hagbarddenstore** [netbox-community/netbox#9694]
### NetBox version

v3.2.5

### Feature type

Change to existing functionality

### Proposed functionality

Prefetch the related properties that are defined in the `DeviceTable` when used in the `DeviceListView`.

Call `.prefetch_related()` on the Device queryset defined in `DeviceListView` with the following arguments:

```
.prefetch_related('site', 'location', 'rack', 'device_role', 'manufacturer', 'device_type', 'primary_ip4', 'primary_ip6', 'cluster', 'virtual_chassis', 'tenant')
```

### Use case

Provides better performance when accessing lots of different related properties and lessens the load on the database.

### Database changes

None

### External dependencies

None

**Comment by hagbarddenstore** [comment]
Not entirely sure about my accuracy on the properties to prefetch, but those where the ones that are used in the table.

**Comment by kkthxbye-code** [comment]
> Provides better performance when accessing lots of different related properties and lessens the load on the database.

Did you confirm this? I don't see any difference in queries generated.

**Comment by hagbarddenstore** [comment]
I found something clever in NetBox...

https://github.com/netbox-community/netbox/blob/develop/netbox/netbox/tables/tables.py#L76

So, things brings up another question, when should prefetch be used in NetBox?

**Comment by jeremystretch** [comment]
> I found something clever in NetBox...

We added that when introducing configurable tables, to ensure that we're not prefetching everything while displaying only a subset of that data.

> So, things brings up another question, when should prefetch be used in NetBox?

Everywhere it's needed when you're not rendering a table (e.g. for API endpoints). See the [Django docs](https://docs.djangoproject.com/en/4.0/ref/models/querysets/#prefetch-related) for further considerations.
