### ISSUE TITLE
Remove deprecated uses of `prefetch_related` from views

### ISSUE THREAD

**Issue by hagbarddenstore** [netbox-community/netbox#9699]
### Proposed Changes

In views which display their data in a table, the use of `prefetch_related` can be removed since the table itself prefetches the displayed columns internally.

This is the code doing the magic:
https://github.com/netbox-community/netbox/blob/develop/netbox/netbox/tables/tables.py#L76

Example of code that can be removed:
https://github.com/netbox-community/netbox/blob/develop/netbox/circuits/views.py#L194

### Justification

Calling `prefetch_related` on some views but not others, adds confusion to developers whom are fixing bugs or developing new features, as it is unclear when it's needed or not.

**Comment by hagbarddenstore** [comment]
(I discussed it with @kkthxbye-code on Slack)

I can be assigned on this.

**Comment by jeremystretch** [comment]
Bear in mind that _some_ prefetching is still needed. The automatic prefetching looks at the accessor used for the table column, but isn't smart enough to know if additional data is needed. For example, a TemplateColumn might render data from an additional related object, in which case a manual call to prefetch that object in the queryset is still necessary.

**Comment by jeremystretch** [comment]
@hagbarddenstore would you still like to work on this? If not, I can take care of it.

**Comment by jeremystretch** [comment]
Great work @hagbarddenstore, thank you!

**Comment by jeremystretch** [comment]
#9886 has been merged into the `feature` branch.

**Comment by hagbarddenstore** [comment]
I still want to do it. I’ve just been on vacation with the kids :)
