### ISSUE TITLE
VLAN Site as well as Group VLAN

### ISSUE THREAD

**Issue by mclaridge-ptp** [netbox-community/netbox#9703]
### NetBox version

v3.2.5

### Feature type

New functionality

### Proposed functionality

I would like the ability to add a VLAN to sites as well a groups in the VLAN section. Currently I have to pick one or the other

Current error. "VLAN is assigned to group Managment (scope: None); cannot also assign to site [Site Name]"

### Use case

Ability to add VLANs to a spacific site as well as having that VLAN in a group i.e MGNT VLANs 800-899 as an example

**Comment by jeremystretch** [comment]
This is already possible, however the VLAN group must be scoped to the selected site.
