### ISSUE TITLE
Add an InventoryItemType

### ISSUE THREAD

**Issue by ryanmerolle** [netbox-community/netbox#9724]
### NetBox version

v3.2.6

### Feature type

New functionality

### Proposed functionality

Similar to DeviceType, add an InventoryItemType.

### Use case

This would drive InventoryItem Standardization within user's NetBox.

### Database changes

Add a new model for InventoryItemType and create a FK from InventoryItem to InventoryItemType.

### External dependencies

N/A

**Comment by jeremystretch** [comment]
Thank you for your interest in extending NetBox. Unfortunately, the information you have provided does not constitute an actionable feature request. Per our [contributing guide](https://github.com/netbox-community/netbox/blob/develop/CONTRIBUTING.md), a feature request must include a thorough description of the proposed functionality, including any database changes, new views or API endpoints, and so on. It must also include a detailed use case justifying its implementation. If you would like to elaborate on your proposal, please modify your post above. If sufficient detail is not added, this issue will be closed.

**Comment by jeremystretch** [comment]
Closing this as non-actionable, but @ryanmerolle feel free to re-open if you want to flesh it out.

**Comment by ryanmerolle** [comment]
I'll flesh this out with a model soon and look to reopen
