### ISSUE TITLE
Missing Fibrechannel interface types

### ISSUE THREAD

**Issue by martindalum** [netbox-community/netbox#9726]
### NetBox version

v3.2.2

### Feature type

Data model extension

### Proposed functionality

The current list of fibrechannel interface types are, from contansts.py:
1. [IFACE_TYPE_1GFC_SFP, 'SFP (1GFC)'],
2. [IFACE_TYPE_2GFC_SFP, 'SFP (2GFC)'],
3. [IFACE_TYPE_4GFC_SFP, 'SFP (4GFC)'],
4. [IFACE_TYPE_8GFC_SFP_PLUS, 'SFP+ (8GFC)'],
5. [IFACE_TYPE_16GFC_SFP_PLUS, 'SFP+ (16GFC)'],
6. [IFACE_TYPE_32GFC_SFP28, 'SFP28 (32GFC)'],
7. [IFACE_TYPE_128GFC_QSFP28, 'QSFP28 (128GFC)'],

This indicates that eg. a 32GB link must be using the SFP28 form-factor, which is not true.

Brocade have a list of their transciever types here: https://www.broadcom.com/products/fibre-channel-networking/transceiver-modules

This includes eg. 32Gbit SFP+, 64Gbit SFP+ and 64Gbit SFP-DD which are not on the list in Netbox.

Ideally interface types could be moved to the database and added or changed via the webinterface or API, but since that's a quite big change, it would be nice to have the list in contansts.py maintained.

The current list assumes only one transciever type per speed, so an alternative could be to remove transceiver types from the list and add the missing 64GFC speed.

### Use case

This would enable correct documentation of needed transceivers in netbox.

**Comment by DanSheps** [comment]
Please fill out the proposal section with the specific interfaces you are proposing to be added.

**Comment by jeremystretch** [comment]
Closing as there has been no follow-up from the OP.
