### ISSUE TITLE
New Device Components Not Inheriting Description

### ISSUE THREAD

**Issue by dg2assassin** [netbox-community/netbox#9731]
### NetBox version

v3.2.6

### Python version

3.8

### Steps to Reproduce

1. Add a description to a component for a Device Type. 
3. Create a new Device from that Device Type
4. Navigate to the components screen and notice no descriptions have been propagated over from the Device Type.

Device Type
![Device Type](https://user-images.githubusercontent.com/25205963/179076272-763bc9e0-913c-4ce4-87be-23afd0c59f84.PNG)
 
New Device
![New Device](https://user-images.githubusercontent.com/25205963/179076328-bba87340-08e2-4a1e-ad32-cfe3e081af16.PNG)

### Expected Behavior

The description field set in the Device Type should propagate to the new Device instance. 

### Observed Behavior

It seems when the description field for components (Interfaces, Device Bays, Power Ports) are set in the "Device Type", they are not propagating to a new device during creation.

**Comment by jeremystretch** [comment]
This is intended behavior and has been discussed previously. Please search closed issues before submitting a new one.
