### ISSUE TITLE
Rack Face Not Auto Dropping Down

### ISSUE THREAD

**Issue by dg2assassin** [netbox-community/netbox#9732]
### NetBox version

v3.2.6

### Python version

3.8

### Steps to Reproduce

1. Create or edit a Device
3. Select a rack
4. Rack Face is skip, and Position becomes the next field to fill in

### Expected Behavior

Once Rack has been filled in, Rack Face should be the next in the auto drop down list. 

### Observed Behavior

Rack Face is skipped, and Position becomes the next to fill in. If a new device is created, this field will be left blank while the other Location fields will be filled in. This could lead to the user confused why their device is not able to be created when everything looks correct.

**Comment by kkthxbye-code** [comment]
Same issue as #9734 - it's not intended that the next field is opened automatically at all.

While your report is older (missed it first time around), I'll close this in favor of the other one, as I already submitted the fix. Thanks for the report!
