### ISSUE TITLE
Other select fields steal focus if the choice filters other select fields (caused by #9632)

### ISSUE THREAD

**Issue by kkthxbye-code** [netbox-community/netbox#9734]
### NetBox version

v3.2.6

### Python version

3.10

### Steps to Reproduce

1. Create manufacturer test
2. Create devicetype test with manufacturer test
3. Go to create device form
4. Select test under manufacturer

### Expected Behavior

Select field closes.

### Observed Behavior

The devicetype field opens and take focus.

**Comment by abhi1693** [comment]
This is not yet fixed. I ran a test on the `develop` branch to check and I'm still facing the same issue. The drop-downs are still automatically opening
