### ISSUE TITLE
Search for IP adresses: "contains" and "end with" not showing results

### ISSUE THREAD

**Issue by njutec** [netbox-community/netbox#9738]
### NetBox version

v3.2.6

### Python version

3.9

### Steps to Reproduce

1.Create a prefix: 172.16.0.0/24
2.Create a number of IP addresses in that prefix (172.16.0.1, 172.16.0.2, ...)
3.Enter a value in the QuickFilter that contains or end with a value of that IP adresses, but not starts with that value (not showing results).
4.Enter a value in the QuickFilter that start with a value of that ip adresses (showing results).

I got the same results at the demo.netbox.dev setup.

### Expected Behavior

Search for an IP adress, that contains or end with a value should also be found.

### Observed Behavior

For example:

1.No results found for IP adresses (end with):

-Search for: 16.0.1

![grafik](https://user-images.githubusercontent.com/109343876/179194922-60d44f65-b98a-4d52-bc9f-5c0c0f3e2c81.png)

2.No results found for IP adresses (contains):

-Search for: 16.0.

Shows results (Aggregates, Prefixes, ...) - but without IP adresses:

![grafik](https://user-images.githubusercontent.com/109343876/179195033-33198878-33c1-4ed2-8d5b-c14773adc2f3.png)

3.Results are displayed for IP adresses (start with):

-Search for: 172.16.

![grafik](https://user-images.githubusercontent.com/109343876/179195070-a08369c3-f0e4-4c1e-aab4-4a876ba2e9d2.png)

**Comment by jeremystretch** [comment]
Yes, this is intended behavior: These are IP addresses, not strings, thus partial matching is not supported. Searching my partial match is of little practical use as it would return extraneous results.
