### ISSUE TITLE
v3.3-beta1: Only offer half height mounting for devices whose device-type-height is not full increments

### ISSUE THREAD

**Issue by martinum4** [netbox-community/netbox#9751]
### NetBox version

v3.3-beta1

### Feature type

Change to existing functionality

### Proposed functionality

Before the .5-Units are being showed in the selection for available units, there should be a check if the device-type-height actually is uneven.

### Use case

Rack units are divided more ore less into thirds due to the number of mounting holes.
It is therefore impossible to mount a regular 1U-Device at exactly half-height, it would use approximately .3 or .6 of either the lower or upper unit which would collide with other devices.

**Comment by jeremystretch** [comment]
IMO this getting a little too pedantic. Generally, all we really care about is whether a unit is partially occupied. And it's valid (though annoying) to have a single 1U device consuming two units of space by being mounted between them.

**Comment by jeremystretch** [comment]
Going to close this out as there's been no further discussion.
