### ISSUE TITLE
Allow docs endpoint to be behind authentication

### ISSUE THREAD

**Issue by abhi1693** [netbox-community/netbox#9756]
### NetBox version

v3.2.6

### Feature type

New functionality

### Proposed functionality

The `/static/docs/` should optionally be behind a login page. This can be made optional for backward compatibility.

### Use case

The `/static/docs/` should optionally be behind a login page for those setups where the developers have added custom plugins with their own documentation. This documentation may hold sensitive information which should only be visible to those with access to the plugin.

As of today, anyone with the base URL can go through the documentation which is not desirable in production environments.

### Database changes

I don't think so

### External dependencies

I don't know

**Comment by jeremystretch** [comment]
> The /static/docs/ should optionally be behind a login page for those setups where the developers have added custom plugins with their own documentation.

Nothing confidential should appear in the plugin's documentation. Alternatively, you have the option to restrict access to static resources via the frontend HTTP server (e.g. nginx or Apache) configuration, however this is out of scope for NetBox itself.
