### ISSUE TITLE
v3.3-beta1: Connection field in interfaces view of device only shows name of connection not device

### ISSUE THREAD

**Issue by mini-man** [netbox-community/netbox#9758]
### NetBox version

v3.3-beta1

### Python version

3.10

### Steps to Reproduce

1. Open device show connection field in table
2. Connect interface to another device
3. 
![image](https://user-images.githubusercontent.com/11536761/179449552-feb09b15-db6d-4c83-a52d-548e98268067.png)

### Expected Behavior

V3.2.6 connection field shows devicename + port assigned
![image](https://user-images.githubusercontent.com/11536761/179449600-c7bec937-44cb-4191-afc5-046d25ed45e9.png)

### Observed Behavior

Connection field only shows portname instead of device_name > portname

**Comment by jaylik** [comment]
Guess same issue with circuit terminated interfaces which shows "—" as connection on interfaces table.

**Comment by jeremystretch** [comment]
Thank you for opening a bug report. Unfortunately, the information you have provided is not sufficient for someone else to attempt to reproduce the reported behavior. Remember, each bug report must include detailed steps that someone else can follow on a clean, empty NetBox installation to reproduce the exact problem you're experiencing. These instructions should include the creation of any involved objects, any configuration changes, and complete accounting of the actions being taken. Also be sure that your report does not reference data on the public NetBox demo, as that is subject to change at any time by an outside party and cannot be relied upon for bug reports.

**Comment by candlerb** [comment]
The issue still exists with Netbox 3.3-beta2. The steps to reproduce are:
1. Navigate to any device which has at least one cable connection to another device
2. Select the "Interfaces" tab
3. Select "Configure Table" to add the "Connection" column, if it's not already present

Example from Netbox v3.2.9:
![image](https://user-images.githubusercontent.com/44789/185104263-bf10e0d5-0cc8-431e-9198-265ce1d2d6f0.png)

Same example with Netbox v3.3-beta2:
![image](https://user-images.githubusercontent.com/44789/185104706-b21778f6-25a6-4a31-873e-98f1f75f3433.png)
