### ISSUE TITLE
Two Phase Power feeds

### ISSUE THREAD

**Issue by BoudewijnSwen** [netbox-community/netbox#9759]
### NetBox version

v3.1.10

### Feature type

Change to existing functionality

### Proposed functionality

I love the power modeling functionality! I would love to have an extra option though:

Have a PDU with internal circuit breakers show the power utilization per breaker, like with a multi-phase power feed.

### Use case

We have single phase power feeds (230v 32A) and our PDU's (Raritan PX3-5892) contains two 16A circuit breakers. The ports are split 50/50 over those two breakers.
We had the problem before where we connected to many devices to just one of those breakers, so the total of the devices was still under 32A, but on one breaker, it would go over 16A, so it would break and power would go down. So, modeling this is vital for us. Doing this in NetBox would be great! 

I tried to split the ports over Feed Leg A and Feed Leg B, but only if I were to change the Feed type to a three-phase feed, it shows the individual leg utilization. But this setup is incorrect of course, but this got me thinking, that it would be awesome if it was possible to show the utilization per feed leg within the PDU, even though it is connected to a single phase feed. Now I can only see the total utilization.

**Comment by bluikko** [comment]
Sounds like "two phase" is a misnomer here - it just simply has 2 circuits on the PDU.

**Comment by jeremystretch** [comment]
> So, modeling this is vital for us. Doing this in NetBox would be great!

What is the proposed solution?

**Comment by bluikko** [comment]
Model it as 2 separate PDUs, connected to a dummy unit that has 32A upstream and 2x16A downstream?  
Might work if the unit is 2U high - or if it is 1U high then model them as 2x 0.5U units...

**Comment by jeremystretch** [comment]
As of NetBox v3.3.0 you can model this as a single power feed connected to two power ports on the PDU, each mapped to their respective outlets. Without a detailed proposed change to the data model, I don't think there's anything else to do here.
