### ISSUE TITLE
Marking IP ranges as 100% utilized

### ISSUE THREAD

**Issue by nem1989** [netbox-community/netbox#9761]
Posting a new issue since I've noticed the one that I commented is already closed.
What I'm trying to do is to correctly define a DHCP IP range and prevent admins from assigning IP's from that range to devices/VM's, but when I define an IP range, all of it's IP addresses still count as available in it's parent prefix. 

### NetBox version
v3.2.6

### Steps to reproduce
For example let's say we have a subnet (192.168.1.0/24) with a gateway (192.168.1.1) and DHCP range 192.168.1.2 - 192.168.1.99.
Then in Netbox we define:

- a prefix 192.168.1.0/24
- an IP address 192.168.1.1
- an IP range 192.168.1.2 - 192.168.1.99 marked as reserved.

### Expected behavior
In parent prefix I should see available IP's starting from 192.168.1.100 since all others are reserved for an IP range.

### Actual behavior
In IP addresses tab IP ranges are not visible. All IP addresses except 192.168.1.1 are listed as available in prefix 192.168.1.0/24 which is not what I expect to see.
Right now to achieve what I want I have to bulk create individual IP addresses in mentioned range to fill it. Think of it: why do I need ranges if I have to create the whole set of IP's anyway?

### Proposed functionality
Implement a checkbox for IP ranges to mark one as restricted/utilized or atleast make an option to show IP ranges in IP Addresses list. It would prevent admins from assigning IP's from DHCP or reserved ranges to devices or VM's. 

_Originally posted by @nem1989 in https://github.com/netbox-community/netbox/issues/9412#issuecomment-1187057428_

**Comment by jeremystretch** [comment]
Please resubmit your issue using one of the [approved templates](https://github.com/netbox-community/netbox/issues/new/choose).
