### ISSUE TITLE
Add nat_outside to the IPAddress table

### ISSUE THREAD

**Issue by atownson** [netbox-community/netbox#9762]
### NetBox version

v3.2.4

### Feature type

Change to existing functionality

### Proposed functionality

Add the nat_outside field (as NAT (Outside)) to the IPAddressTable class [(netbox/netbox/ipam/tables/ip.py).](https://github.com/netbox-community/netbox/blob/develop/netbox/ipam/tables/ip.py#L343) The nat_inside field already exists.

### Use case

We manage several DMZs. Adding the nat_outside would help in identifying these relationships in the IP Address table as we typically reference these addresses by the inside NAT.

### Database changes

None

### External dependencies

None

**Comment by jeremystretch** [comment]
FYI the `nat_outside` relationship will return a list of objects in NetBox v3.3 and later (see #1202).

**Comment by atownson** [comment]
Thanks for the info @jeremystretch. Will this new one-to-many relationship cause issues implementing this request? If not, I could submit a pull request for this. Thanks.
