### ISSUE TITLE
Deleting device with cable connected leaves cable with only one side terminated

### ISSUE THREAD

**Issue by mini-man** [netbox-community/netbox#9778]
### NetBox version

v3.3-beta1

### Python version

3.10

### Steps to Reproduce

1. Create device A with NIC A
2. Create device B with NIC B
3. Connect NICs with Cable
![image](https://user-images.githubusercontent.com/11536761/179667404-23de6e47-91f1-40d0-bc74-9fc51ee57651.png)
4. Delete device A or B
EDIT*
5. Interact with cable e.g delete cable/remaining device - class error.

### Expected Behavior

~~Delete action, deletes Device A **AND** the cable attached.~~
Delete remaining interface

### Observed Behavior

~~Delete action deletes Device B, leaves cable in the database with only one termination point:~~
![image](https://user-images.githubusercontent.com/11536761/179667593-857c41fe-f66c-4979-8c0c-1b2956441806.png)

Unable to delete cable/or device cable is left
<class 'dcim.models.device_components.Interface.DoesNotExist'>

**Comment by jeremystretch** [comment]
While this is a change in behavior from v3.2 and earlier, I'm not sure I agree with classifying it as a bug. We've had numerous requests for the ability to leave cabling in place with only one end connected, which was not feasible with the old model but is now.

**Comment by mini-man** [comment]
While that's fine - if you try to delete the other device you run into issues:
Same happens if you try to delete the cable.
![image](https://user-images.githubusercontent.com/11536761/179749970-7dd9059b-a7ee-4886-a7d2-27efd4829ec5.png)

**Comment by Miccia94** [comment]
Having the same error as @mini-man

**Comment by jeremystretch** [comment]
Ok, I see the issue. Previously, the cable was being deleted automatically, which was forcing the path to be recalculated. But that doesn't happen now, so we just need to add a receiver to handle that whenever a cable termination is deleted.

**Comment by jeremystretch** [comment]
_Or_ we disable the deletion of the object until the cable has been disconnected. I recall this being proposed in the past, but I'm not sure it went anywhere.

**Comment by jeremystretch** [comment]
I've opened #9837 to discuss the above. Marking this as blocked until we reach a consensus on the desired behavior.

**Comment by jaylik** [comment]
Guess this will have better solution later but temporary workaround below,
```
diff --git a/netbox/dcim/models/cables.py b/netbox/dcim/models/cables.py
index 3f287317b..058b7b2e4 100644
--- a/netbox/dcim/models/cables.py
+++ b/netbox/dcim/models/cables.py
@@ -604,7 +604,13 @@ class CablePath(models.Model):
         """
         Retrace the path from the currently-defined originating termination(s)
         """
-        _new = self.from_origin(self.origins)
+        try:
+            _new = self.from_origin(self.origins)
+        except:
+            try:
+                _new = self.from_origin(self.destinations)
+            except:
+                _new = False
         if _new:
             self.path = _new.path
             self.is_complete = _new.is_complete
@@ -641,7 +647,8 @@ class CablePath(models.Model):
             nodes = []
             for node in step:
                 ct_id, object_id = decompile_path_node(node)
-                nodes.append(prefetched[ct_id][object_id])
+                if ct_id in prefetched and object_id in prefetched[ct_id]:
+                    nodes.append(prefetched[ct_id][object_id])
             path.append(nodes)

         return path
diff --git a/netbox/dcim/views.py b/netbox/dcim/views.py
index 12e070e70..ddaccc5e0 100644
--- a/netbox/dcim/views.py
+++ b/netbox/dcim/views.py
@@ -2848,9 +2848,9 @@ class CableEditView(generic.ObjectEditView):
         if obj.pk:
             # TODO: Optimize this logic
             termination_a = obj.terminations.filter(cable_end='A').first()
-            a_type = termination_a.termination._meta.model if termination_a else None
+            a_type = termination_a.termination._meta.model if termination_a else b_type
             termination_b = obj.terminations.filter(cable_end='B').first()
-            b_type = termination_b.termination._meta.model if termination_b else None
+            b_type = termination_b.termination._meta.model if termination_b else a_type
             self.form = forms.get_cable_form(a_type, b_type)

         return obj
```
