### ISSUE TITLE
Option to exclude api from triggering webhooks

### ISSUE THREAD

**Issue by rizlas** [netbox-community/netbox#9779]
### NetBox version

v3.2.5

### Feature type

New functionality

### Proposed functionality

Add an option to webhooks to enable/disable triggering from api. Currently if you make CRUD operations either via GUI or APIs webhooks are triggered.

### Use case

Currently I have a CI/CD connected to a webhook but I want it to be triggered only for operations made via GUI.

### Database changes

Can't say

### External dependencies

None

**Comment by jeremystretch** [comment]
I'm not sure it would make sense to differentiate between GUI- and API-driven changes, especially if you assume that future releases of NetBox may have an entirely API-driven UI. It also might not be feasible without radically altering the current webhooks implementation that relies on signals, which don't include any context indicating how a change was made.

**Comment by romanstech** [comment]
Just my 5 cents.
I use a separate Netbox user for REST API requests and by checking the payload.username I separate REST API and GUI calls to the same webhook in my backend app.
GUI uses usual usernames (in my case, AD) so I easily recognize REST API calls.

**Comment by rizlas** [comment]
That can be a solution. In my case that doesn't work because users (LDAP) are enabled to use API token.
Anyway, I will further investigate your solution.

Thank you

**Comment by DanSheps** [comment]
Maybe it would make more sense to have a "webhooks=false" option in both the API and GUI.  With the ability to toggle it on and off in the gui

**Comment by rizlas** [comment]
What about a simple custom header that will discriminate between GUI and API? Further actions are delegated to the webhook receiver.
