### ISSUE TITLE
Rack Elevations mapping issue to attached devices

### ISSUE THREAD

**Issue by MatthewKahle** [netbox-community/netbox#9785]
### NetBox version

v3.2.5

### Python version

3.8

### Steps to Reproduce

Under the tab 'Rack Elevations' all the assets mapped to a Rack contains old IP address and non domain/URL if setting a new IP on the host of netbox.

### Expected Behavior

When resetting my netbox instance to a new IP address, and adding a domain name. All links should work with new IP address or domain name.

### Observed Behavior

When I first install netbox, I installed on a host that had DHCP configured. When I statically set to a different IP address that I wanted, I noticed that the assets that can be clicked on in rack view 'Rack Elevations' contained the old IP which the page will time out since that IP address is no longer in use.

**Comment by jeremystretch** [comment]
Thank you for opening a bug report. Unfortunately, the information you have provided is not sufficient for someone else to attempt to reproduce the reported behavior. Remember, each bug report must include detailed steps that someone else can follow on a clean, empty NetBox installation to reproduce the exact problem you're experiencing. These instructions should include the creation of any involved objects, any configuration changes, and complete accounting of the actions being taken. Also be sure that your report does not reference data on the public NetBox demo, as that is subject to change at any time by an outside party and cannot be relied upon for bug reports.

**Comment by bkakakym** [comment]
I have same problem:
Netbox version 3.2.7
Python version 3.9.9

I have such network structure:
Reverse_proxy host( with Nginx listening white address and ssl with a domain name attached to it) <> Netbox host(with nginx reverse proxyng to gunicorn port) with a local(gray address)

In configuration.py I have ALLOWED_HOSTS = ['example.com', '192.168.25.21']

in rack overview and in rack elevations all url`s to device are using gray ip like http://192.168.25.21/dcim/devices/304/ - non like expected https://example.com/dcim/devices/304/

**Comment by jeremystretch** [comment]
This is a configuration issue. Please see [this answer](https://github.com/netbox-community/netbox/wiki/Common-Issues#rack-elevation-links-use-wrong-domain) in the wiki, and reference the installation instructions for the correct configuration.
