### ISSUE TITLE
Circuit commit rate for asymmetric speeds (DL/UL)

### ISSUE THREAD

**Issue by jaylik** [netbox-community/netbox#9790]
### NetBox version

v3.3-beta1

### Feature type

Data model extension

### Proposed functionality

Support for different download and upload speeds >> split "Commit rate (Kbps)" to two fields

### Use case

For example GPON and LTE connections are provided with different DL/UL speeds - for monitoring and QoS we would need to define maximums for both.

**Comment by jeremystretch** [comment]
Thank you for your interest in extending NetBox. Unfortunately, the information you have provided does not constitute an actionable feature request. Per our [contributing guide](https://github.com/netbox-community/netbox/blob/develop/CONTRIBUTING.md), a feature request must include a thorough description of the proposed functionality, including any database changes, new views or API endpoints, and so on. It must also include a detailed use case justifying its implementation. If you would like to elaborate on your proposal, please modify your post above. If sufficient detail is not added, this issue will be closed.

**Comment by jeremystretch** [comment]
Closing as there has been no further response.
