### ISSUE TITLE
Add PoE attributes to interface templates

### ISSUE THREAD

**Issue by PaulR282** [netbox-community/netbox#9793]
### NetBox version

v3.3.0-beta1

### Feature type

Data model extension

### Proposed functionality

In addition to my feature request #8272 it would be nice to be able to configure more in the device type that you can configure when editing an interface that already exists. 
I would suggest the following fields: 
- Interface: Speed
- Interface: Duplex
- all of Operation section
- all of Related Interfaces section (like Bridged interface from the existing feature request)
- all of new PoE section

### Use case

The mentioned fields are attributes that you can often predefine. Currently (in beta), if you have a PoE switch, you would need to configure PoE mode and type every time you create a new switch from the device type. The same goes for the other fields like Speed, Duplex, etc.

**Comment by jeremystretch** [comment]
A device type represents the make and model of a _physical_ device, and thus intentionally does not incorporate any configurable characteristics such as interface speed and duplex: These attributes are assigned after instantiation and vary from one interface to another. The only item in your list above that would make sense to add is the PoE designations, which I agree should have been incorporated under #1099.

**Comment by PaulR282** [comment]
Alright. Testing the new PoE functionality in the beta was the origin of this idea. It makes sense to only model the physical device this way. So I would suggest just adding PoE and #8272.
