### ISSUE TITLE
Asymmetry in cable trace when using bridged interfaces

### ISSUE THREAD

**Issue by bistraque** [netbox-community/netbox#9800]
### NetBox version

v3.2.6

### Python version

3.9

### Steps to Reproduce

Assuming demo.netbox.dev site default data:
- create Device Type "NTU" manufacturer "Generic"
- create Device "Test NTU" device type "NTU" site "DM-NYC"
- Add 2 interfaces "SFP" and "RJ45" to "Test NTU"
- Configure interface "SFP" as bridge to "RJ45" and "RJ45" as bridge to "SFP"
- Create Device "Test RTR" device type "ISR 1111-8P" site "DM-NYC"
- Connect interface "GigabitEthernet0/0/1" to "Test NTU" interface "RJ45"
- Create Circuit "Test Telco" + Circuit Termination A site "DM-NYC"
- Connect circuit termination A to "Test NTU" interface "SFP"
- Display cable trace from "Test RTR GigabitEthernet0/0/1"
- Display cable trace from "Test Telco Termination A"

### Expected Behavior

Cable trace from router "Test RTR GigabitEthernet0/0/1" should be consistent with cable trace from circuit "Test Telco Termination A"

### Observed Behavior

While cable trace from router appears to be complete (bridging through NTU to circuit termination), cable trace from circuit termination stops at NTU interface.
![Clipboard 4](https://user-images.githubusercontent.com/72216107/180014213-196fd3c2-f5bc-47e7-8e3f-19f5f2824353.jpg)
![Clipboard 2](https://user-images.githubusercontent.com/72216107/180014197-0822fe43-14a6-4fbf-a3f8-0668585fb15b.jpg)

**Comment by bistraque** [comment]
Another type of inconsistency appears in device interface table "connection" column and in "circuit termination" panel: when the trace consists of front/rear ports and/or circuits only, connection info displays the trace endpoint instead of the next connected hop. If the trace contains bridged interfaces, connection info displays the first interface in the trace ignoring the bridge. 

Contrary to the asymmetry described above, this happens on both endpoints (device interface and circuit termination). Not sure if these two inconsistencies are one and only bug.

**Comment by jeremystretch** [comment]
Can you test whether this is still an issue on NetBox v3.3?

**Comment by kkthxbye-code** [comment]
@jeremystretch - I used his steps and can confirm that this is still the issue. I am however not sure how it is supposed to work.

When [tracing from the CircuitTermination](https://github.com/netbox-community/netbox/blob/4c51dbba809b6b199a96da30f32f4dd3cd6ea6ed/netbox/dcim/views.py#L2774) it ends up finding any path that contains the CircuitTermination and then  picking the first result.

The result is that the path that is traced has an origin of the SFP. As CircuitTerminations are not a PathEndpoint (right?) the trace cannot start with it. So the logical trace would in my opinion be CT -> SFP -> Through Bridge -> RJ45 -> GBE1 - but you can never start at a CT. As it is reversed it doesn't traverse backwards - so the path is SFP -> CT but it doesn't then check backwards from bridges before SFP.

Maybe a small refresher as to how CT tracing is supposed to work when it's not a PathEndpoint? Should we do the bridge traversal in the PathTraceView when finding the path instead?

**Comment by jeremystretch** [comment]
@kkthxbye-code yep I think you've captured the issue perfectly. Because circuit terminations are pass-through nodes (just like front and rear ports), there is no concept of the path "starting" from the circuit termination. We merely retrieve all paths which traverse the circuit termination. (In this case there is only the one path.)

We only see the path from the SFP interface to the circuit termination because there's no logic in place today to account for bridging at the _beginning_ of a path, only at the end.

> Should we do the bridge traversal in the PathTraceView when finding the path instead?

Here's the big of logic which currently handles traversing bridged interfaces:

https://github.com/netbox-community/netbox/blob/develop/netbox/dcim/models/device_components.py#L223-L228

Accounting for a path starting from across a bridge would be tricky, because we have no context indicating whether that's desired for a given trace.

**Comment by jeremystretch** [comment]
We'll need to determine whether it's feasibly to blindly reverse the path being rendered, so that it appears to be originating from the expected termination point.

**Comment by MrDragon** [comment]
Maybe related, maybe not (see https://github.com/netbox-community/netbox/discussions/11725 - NetBox 3.4.4)
I'm trying to document a "Provider-A-Network <->Carrier-A circuit <-> fiber-panel-A <-> fiber-panel-B <-> Carrier-B circuit <-> Provider-B-Network".
If I use front/rear ports on the panels, the trace doesn't show any results. If I use bridged interfaces on the panels, I can trace "2 sides", but never the whole path.
I might do things wrong, but we have two carriers in their own cages in our data center, and we charge one of them for the cross-connect, so we should document that cable.

I could create a "provider-A/B dummy device" in with interfaces and then use normal front/rear ports of a fiber-panel.
