### ISSUE TITLE
Add DEVELOPER setting to configuration.example.py

### ISSUE THREAD

**Issue by rixx** [netbox-community/netbox#9806]
### Proposed Changes

Adding the `DEVELOPER = False` setting to the configuration.example.py would make it easier to find and better documented (in addition to the developer setup documentation, of course).

### Justification

I'm an idiot and set `DEVELORERS = True` and was very confused for several minutes when I tried to create database migrations. Just creating issue + PR here on the offchance of saving anybody else the trouble in the future.

**Comment by jeremystretch** [comment]
We intentionally don't include this in the example configuration, because it should not never be enabled by anyone not already familiar with the development documentation.
