### ISSUE TITLE
Possibility to add computers as devices

### ISSUE THREAD

**Issue by pboatone** [netbox-community/netbox#9812]
### NetBox version

v3.2.7

### Feature type

New functionality

### Proposed functionality

If there is a customer, that want to document their infrastructure and wants to where their computers are located. 

-> hostnamename
-> location -> as rooms not as rack 
-> user on this computer
-> IP-Adress static or dhcp
-> working system such as Windows 10 

### Use case

You can find computers fast and know which person is working with it

**Comment by jeremystretch** [comment]
NetBox is not designed to track end clients, however there's nothing preventing you from modeling these today should you choose to do so. Please consider starting a [discussion](https://github.com/netbox-community/netbox/discussions/new) if you'd like assistance.
