### ISSUE TITLE
Add checkbox or dropbox on devices for Updates

### ISSUE THREAD

**Issue by pboatone** [netbox-community/netbox#9813]
### NetBox version

v3.2.7

### Feature type

New functionality

### Proposed functionality

A list or checkbox for Updates on this maschine

like 
-> automatic updates
-> manuell updates 
-> no updates

and a filter option in search.

Maybe a additional  commentbox or list with a fixed date for each month like "every 3rd monday of month"

### Use case

For quick search for devices where we have to make updates.

**Comment by DanSheps** [comment]
Given that NetBox's user base is fairly diverse, I don't know if this makes sense to be placed into the NetBox core, it is better off as a custom field.

**Comment by ryanmerolle** [comment]
> Given that NetBox's user base is fairly diverse, I don't know if this makes sense to be placed into the NetBox core, it is better off as a custom field.

That is generally how users have achieved this sort of requirement. @pboatone look into custom fields and you should see it works for your use case.

**Comment by jeremystretch** [comment]
Agreed, this sounds like a prime use case for [custom fields](https://docs.netbox.dev/en/stable/customization/custom-fields/).
