### ISSUE TITLE
Circuit termination on interface not working when accesssed from interface table

### ISSUE THREAD

**Issue by jaylik** [netbox-community/netbox#9818]
### NetBox version

v3.3-beta1

### Python version

3.9

### Steps to Reproduce

1. Create device with interfaces
2. Create circuit with Z-side on same site as device
3. Try to connect interface to circuit termination from interface table
4. Select B Side Cicuit
5. Try to select Side for circuit

### Expected Behavior

On B Side you are able to select side for circuit

### Observed Behavior

Side option menu is empty because.

This is caused because $ is missing for `$termination_{cable_end}_circuit`

https://github.com/netbox-community/netbox/blob/abfa6a325af17d65038304feed2536330d8c60a7/netbox/dcim/forms/connections.py#L141

**Comment by DanSheps** [comment]
@jaylik Do you want to do a PR for this?
