### ISSUE TITLE
Units range in rack reservation return an empty field error if put in decreasing order

### ISSUE THREAD

**Issue by Zeawiel** [netbox-community/netbox#9823]
### NetBox version

v3.2.7

### Python version

3.10

### Steps to Reproduce

1. Create a rack reservation
2. Put a unit range with bigger number first (like 7-2)
3. Click create

### Expected Behavior

The reservation should be created with the good unit values or return a more explicit error.

### Observed Behavior

Netbox gives an error like the field "Units" is empty.
It works if Units are given in the right order (2-7 here).

![image](https://user-images.githubusercontent.com/6941618/180258604-d81617b3-23d3-4cae-84d5-5d80debe385d.png)

**Comment by jeremystretch** [comment]
I agree that the error message should be improved, however support for decreasing units was never intended so the validation failure is expected.
