### ISSUE TITLE
Rack Roles Groups

### ISSUE THREAD

**Issue by dg2assassin** [netbox-community/netbox#9824]
### NetBox version

v3.2.7

### Feature type

Data model extension

### Proposed functionality

Propose grouping of rack roles similar to how locations function. This will better organize the rack roles page and allow grouping racks based on a system's purpose and the function each rack provides within said system. 

### Use case

I work with OT networks where we deal with systems on a functional level. Each system provides a specific role, and each rack usually has a single function that is not replicated in other racks. This has lead us to have a large amount of rack roles with no real way to organize them outside of using tags. While tags work, it would be great to have the ability to group system specific roles into a single group. The idea being similar to how the location page works.

Few examples:

- Digital Control System
    - Primary Data Servers
    - Pump Controls
    - Pressurizer Controls

- Security System
   - Video Management
      - Video Recorders 
      - Encoder Blades 

### Database changes

I'm not overly well versed with the netbox database, but I would assuming the following fields would need to be added to the rack role table:
- parent_id
- parent
- child_id? 

### External dependencies

No external dependencies are needed for this feature request.

**Comment by ryanmerolle** [comment]
IF this were to be evaluated, I would imagine anything with a role would be on the table for either nesting roles or creating a parent group instead of just tackling for racks.

**Comment by dg2assassin** [comment]
ah ok. I was focused on rack role groups, and didn't expand my search for all role groups which is how I missed 9643.
