### ISSUE TITLE
Add Contacts field to Virtual Machines table view

### ISSUE THREAD

**Issue by viroge** [netbox-community/netbox#9825]
### NetBox version

v3.2.7

### Feature type

Change to existing functionality

### Proposed functionality

I would suggest to add contacts field to Virtual Machines table view/export, similarly to what we have in Devices. 
Currently in Devices in the "Configure Table" it's possible to select "Contacts" as a column, but it's not available in Virtual Machines. 

### Use case

When browsing through or exporting Virtual Machines it would be nice to be able to see who the owner/contact is.

**Comment by jeremystretch** [comment]
Hmm, looks like a `contacts` column was mistakenly added to VMInterfaceTable instead.
