### ISSUE TITLE
Rack (inner) depth

### ISSUE THREAD

**Issue by sieuwe** [netbox-community/netbox#9832]
### NetBox version

v3.2.7

### Feature type

Data model extension

### Proposed functionality

Currently we have a width and  height option for inner sizing of a rack.
And the outer width and outer depth is also available.
What we are missing is the possibility to add the inner depth.

### Use case

There are different inner depths possible.
Some hardware only fits from a certain depth.

### Database changes

Depth field needs to be added

**Comment by jeremystretch** [comment]
This is a good idea, but your FR needs much more detail.

* What field(s) are you proposing be added to the rack model?
* Do we want to allow specifying the measurement unit as we do for the outer depth?
* Should the use of this field be limited by rack type?

**Comment by sieuwe** [comment]
- What field(s) are you proposing be added to the rack model?
I'd suggest using 'inner depth' since that would clarify the use and make it not confusing when using depth and outer depth.
- Do we want to allow specifying the measurement unit as we do for the outer depth?
The same measurement unit could apply as for the outer depth.
- Should the use of this field be limited by rack type?
This applies to al rack types.

**Comment by jeremystretch** [comment]
> This applies to al rack types.

What about a freestanding two-post frame?

**Comment by sieuwe** [comment]
> > This applies to al rack types.
> 
> What about a freestanding two-post frame?
Overlooked that one. That shouldn't have an inner dimension, all the other types should have one.

**Comment by thefreakquency** [comment]
Inner depth as in rail-to-rail distance or door-to-door? I would personally like to have rail-to-rail tracked, and maybe even have a min/max rail depth added to the device types. We currently document that through custom properties, but did not script any validation yet... 

Some manufacturers have that information documented ( https://i.dell.com/sites/csdocuments/Business_solutions_engineering-Docs_Documents/en/rail-rack-matrix.pdf ) and we rely on that as we have hundreds of sites across the country with no unique rack model... 

Having all that information added would be a plus, and that would also help to revisit https://github.com/netbox-community/netbox/issues/1627  ?

**Comment by jeremystretch** [comment]
> Inner depth as in rail-to-rail distance or door-to-door?

Rail-to-rail

> Having all that information added would be a plus, and that would also help to revisit #1627?

Possibly, but it would be best to submit a new FR after this one has been implemented.
