### ISSUE TITLE
Allow to model / store circuit segments

### ISSUE THREAD

**Issue by BarbarossaTM** [netbox-community/netbox#9833]
### NetBox version

v3.2.7

### Feature type

Data model extension

### Proposed functionality

Storing circuit information in NetBox is great and provides a lot of value as of today! While thinking about storing Circuits of a large network into NetBox we came across one meta information of especially long haul circuits which might be interesting for a wider audience. I didn't find an issue similar to this idea yet, happy to close this as duplicate if that already exists.

Especially long haul, or even intercontinental circuits, often consists of multiple parts or segments which are chained together to provide the circuit service, being it a dark fiber, wavelength, etc. with a segment being a local-loop sub-contracted by another provider, a under sea cable or similar. Particularly for intercontinental circuits it would be beneficial to store the under sea cable this circuit is carried on to be able to asses the diversity of existing circuits and determine the blast radius if a maintenance is scheduled. The same is true for short circuits where you want to keep track of parts of the path lets say between Frankfurt and and Amsterdam and map that to some segments.

The idea is that segments can be freely created by the user and can mean anything from "under sea cable" to "left of the highway 42 between A and Z", so it's as generic as possible. It might be meaningful to add a Segment Type model as well to be able to differencialte between types of Segments.

### Use case

Explained above :)

### Database changes

This would introduce a new `Segment` or `Circuit Segment` model which I guess should be located within the Circuits section of the UI/API. The model would have a name and potentially slug and can have an n:m relationship with Circuits.

It might make sense to also add a `Segment Type` model to allow the user to model types of segments they care about, for example "under sea cables" or "path left of highway 42". This model would have a name and potentially slug and a 1:n relationship with `Segments`.

### External dependencies

None

**Comment by BarbarossaTM** [comment]
If this is deemed useful I'm happy to work on a PR for this. :-)

**Comment by eronlloyd** [comment]
Ah, this is an interesting take on improving the modeling of the OSP parts of circuits. I see the value in this. At some point I'd like to think this through further and engage the community in a discussion for those that must manage or at least model, as you say, their OSP segments in greater details.

**Comment by BarbarossaTM** [comment]
@jeremystretch Any thoughts on this? As stated before I'm happy to draft a PR for this :-)

**Comment by eronlloyd** [comment]
@BarbarossaTM I'd say draft up a PR if you can to continue the conversation. From my perspective as a circuit provider, the large majority of circuits are nearly always handled as internal records between us and customer demarcs, so that gets completely modeled out.

If you're looking at a circuit as a connection into someone else's network, segments might not actually be as necessary, as I think about it. Perhaps if you can flesh out your concept in a PR it would help.

**Comment by jeremystretch** [comment]
@BarbarossaTM I think the proposed implementation needs a lot more detail before a PR would be appropriate. You've made some high-level notes in the original FR above, but I'm still not clear on exactly how this is intended to operate. Perhaps a draft definition for the model classes would be the best place to start.

**Comment by BarbarossaTM** [comment]
Hey  @jeremystretch I tried drawing up the idea as an ERM, does that make sense?

![image](https://user-images.githubusercontent.com/10324868/218319856-f2678d82-5f8f-4b0a-88c2-ec34a27987a4.png)

So a Circuit could be linked to `n` `Segments`, which each have a `SegmentType` assigned :-)

**Comment by BarbarossaTM** [comment]
@jeremystretch Any thoughts on the ER model I added above? :-)
