### ISSUE TITLE
Prevent the deletion of device components with a cable attached

### ISSUE THREAD

**Issue by jeremystretch** [netbox-community/netbox#9837]
### NetBox version

v3.3-beta1

### Feature type

Change to existing functionality

### Proposed functionality

Prevent the deletion of a device component (e.g. interface, console port, etc.) or other object to which a cable is terminated. The cable must be disconnected before the object can be deleted.

### Use case

This behavior was originally proposed in #5418 but never acted upon. However, it deserves to be revisited in v3.3 because the cabling model has changed. Previously, deleting a terminating object (e.g. an interface) _forced_ the deletion of an attached cable, because each cable must have both its A and B terminations defined. However, in v3.3 and later, this is no longer a strict requirement: It's possible to have a cable with only one end terminated.

Requiring the user to first disconnect any attached cable prior to deleting the terminating object introduces a new step in the workflow, but with the benefits of guarding against inadvertent deletions and preventing "orphaned" cables.

Related: #9778

**Comment by mini-man** [comment]
One possible behavior is:
If deleting interface with cable attached.
- remove that particular endpoint from the cable
- - if no more endpoints exist for the cable, delete the cable
- delete the interface
This for me, would be the 'expected' result.

But having it be a manual step is also consistent with the rest of the Netbox experience.

**Comment by bistraque** [comment]
With this new workflow, there is a possibility to treat cables as a new type of physical asset (not sure if it can "live" without any connection though). This makes sense for "expensive" cables such highspeed AOC or DAC, and for splitter cables of course. It would probably require new attributes such "serial number" and "asset id", but these can be already be implemented as custom fields.

With that in mind I think the proposed workflow (i.e. explicit disconnect before delete) is better than implicit delete because it allows to use netbox to track cable items if needed. Question: can a cable exist without any connection ? (sorry I don't have access to a working v3.3beta version to check)

**Comment by jsenecal** [comment]
In my experience, cables have the following characteristics:

1. Most have manufacturers and model numbers; Not always useful to track, but could be nice to have this information documented where applicable. We could also introduce the "CableTemplate" model to automatically populate cable color/length/etc.
2. Most have serial numbers (could be useful to track them in netbox to inventory those that have a serial number, and find them in netbox by their serial)
3. They are often left in place in the datacenter environment and forgotten... Leaving an unterminated cable in netbox could be useful to track them down and either re-use them or task someone to remove them.

**Comment by eronlloyd** [comment]
I think this is an important conversation. From an optical network engineer's perspective, each cable has specific and important characteristics that are specified in the design, tested in the installation, and updated during operation/maintenance.

To me, cables should be first class objects, as in reality they are a critical part of Layer 1 and warrant that level of treatment as part of the system. The recent changes to 3.3 that allows the editing of cables is an important step in that direction, and tracking link state and protecting against either devices or cables that are attached as part of the link makes sense.
