### ISSUE TITLE
Custom field - object link get lost in object view by updating NetBox to 3.3-beta1

### ISSUE THREAD

**Issue by cybarox** [netbox-community/netbox#9843]
### NetBox version

v3.3-beta1

### Python version

3.9

### Steps to Reproduce

1. Fire up NetBox in version 3.2.7
2. Create new custom field
  - name: IP
  - type: object - IPAM | IPAddress
  - assigned model: Circuits | Circuit
3. Create new IP-address object (e.g 1.1.1.1/32)
4. Create provider
5. Create circuit type
6. Create new circuit with IP-Address set in custom field
  - IP-address is linked in custom field section (object view) and in table view
7. checkout feature branch (3.3-beta1)
8. run upgrade.sh and restart services

**RESULT:** IP-Addess in Custom Field is linked in table view but not in object view of the circuit anymore.

### Expected Behavior

Custom field in circuit object is linked to selected IP address object.
```
<td>
    <a href="/ipam/ip-addresses/1/">1.1.1.1/32</a>
</td>
```

### Observed Behavior

Link to ip address object is missing only shows text without link in object view
```
<td>
    1.1.1.1/32
</td>
```

**Comment by jeremystretch** [comment]
Looks like a regression introduced by #9647. Thanks for the report!
