### ISSUE TITLE
Add a "clear" button for object list quick search fields

### ISSUE THREAD

**Issue by jeremystretch** [netbox-community/netbox#9857]
### NetBox version

v3.2.7

### Feature type

New functionality

### Proposed functionality

Add a button next to the quick search field on object lists to clear the search value and reload the entire object list.

### Use case

Provides a slightly more convenient user experience when utilizing the quick search feature.

**Comment by jsenecal** [comment]
Implementation notes:

Adding...
```html
<button type="button" class="btn bg-transparent" style="margin-left: -40px; z-index: 100;">
      <i class="mdi mdi-close"></i>
</button>
```
... to the input group div along with relevant javascript should do it.


I can tackle this if you need an owner :)

**Comment by jeremystretch** [comment]
Thanks @jsenecal!

**Comment by jsenecal** [comment]
So I was looking for clean ways to achieve this without reinventing the wheel and found out about [::-webkit-search-cancel-button CSS](https://developer.mozilla.org/en-US/docs/Web/CSS/::-webkit-search-cancel-button)

I managed to get it working without much issues but I wonder if its partial support would be a show stopper for NetBox. What are our officially supported browsers ?

**Comment by kkthxbye-code** [comment]
Not working in firefox should make it a no-go in my opinion.

**Comment by jsenecal** [comment]
NetBox aligns with Bootstrap's [supported Browsers and Devices](https://getbootstrap.com/docs/5.1/getting-started/browsers-devices/) list.

So I made changes accordingly.

Looks like that:
![image](https://user-images.githubusercontent.com/1564902/183758209-0d442d58-89f5-4db4-98cb-191833b2a713.png)

![image](https://user-images.githubusercontent.com/1564902/183758066-bd2d0250-b8a5-41ea-b1db-fb61ccf95c31.png)

With cute fade-in animations when the button appears and hovering.

**Comment by jeremystretch** [comment]
Thanks @jsenecal, this is great!

![Peek 2022-08-11 08-54](https://user-images.githubusercontent.com/13487278/184138735-fc7f7756-9aff-47eb-a446-908c06bb2e13.gif)
