### ISSUE TITLE
Consolidate all "Add $object" buttons within object views

### ISSUE THREAD

**Issue by jeremystretch** [netbox-community/netbox#9859]
### NetBox version

v3.2.7

### Feature type

Change to existing functionality

### Proposed functionality

Many object views within NetBox include buttons to create new child objects. For example, the site view has buttons to add a new device, contact, location, etc.

![add_object_buttons](https://user-images.githubusercontent.com/13487278/181355647-b2655839-d348-4133-9f3b-36d8947cb56e.png)

Currently, these buttons are scattered around the page, with each appearing beneath or next to a relevant table of child objects. This issue proposes to move these buttons to a single "Add" dropdown menu toward the top of the page (next to the edit & delete buttons).

### Use case

Consolidating these buttons into a single dropdown menu per object view will help reduce clutter on the page, and ensure that the user can always easily locate a link for the desired action. It will also help to encourage the addition of more links where appropriate.

**Comment by jsenecal** [comment]
What about plugins that inject content/tables in there. Should there be a way to add items to this drop-down?

Not allowing this would make the UX less consistent.
