### ISSUE TITLE
RADIUS/TACACS+ authentication integration

### ISSUE THREAD

**Issue by rommeljantanap** [netbox-community/netbox#9864]
### NetBox version

v3.2.7

### Feature type

New functionality

### Proposed functionality

Support for Tacacs+ Authentication and/or Radius Authentication

### Use case

It would provide more options for setting up remote user authentication.
This will be of much benefit if these can be setup via the Web GUI.

**Comment by jeremystretch** [comment]
You have the option of configuring a custom remote authentication backend for NetBox by setting the [`REMOTE_AUTH_BACKEND`](https://docs.netbox.dev/en/stable/configuration/remote-authentication/#remote_auth_backend) configuration parameter. However, the creation of a backend for RADIUS and/or TACACS+ servers would be out of scope for NetBox itself. You might be interested in crafting your own.
