### ISSUE TITLE
REST API filter for racks not working with site and location filters by name

### ISSUE THREAD

**Issue by empusas** [netbox-community/netbox#9865]
### NetBox version

v3.2.6

### Python version

3.9

### Steps to Reproduce

Make REST API call to /api/dcim/racks with filters for location and site by name.
This can be tested from the API docs as well.

### Expected Behavior

filters should work

### Observed Behavior

if a filter for location or site is used with name like:

/api/dcim/racks/?location=Room10  
/api/dcim/racks/?site=Berlin

give back an error that it would be not a valid choice.  

lookups by ID work fine. The site-group filter works also fine by name and ID.

**Comment by jeremystretch** [comment]
Thank you for opening a bug report. Unfortunately, the information you have provided is not sufficient for someone else to attempt to reproduce the reported behavior. Remember, each bug report must include detailed steps that someone else can follow on a clean, empty NetBox installation to reproduce the exact problem you're experiencing. These instructions should include the creation of any involved objects, any configuration changes, and complete accounting of the actions being taken. Also be sure that your report does not reference data on the public NetBox demo, as that is subject to change at any time by an outside party and cannot be relied upon for bug reports.

**Comment by jeremystretch** [comment]
Closing as there has been no further response.
