### ISSUE TITLE
Function to split Prefix to create multiple child prefixes

### ISSUE THREAD

**Issue by chewborg** [netbox-community/netbox#9866]
### NetBox version

v3.2.2

### Feature type

New functionality

### Proposed functionality

I believe similar was close due to going stale, but previous request asked for additional functionality
[3255](https://github.com/netbox-community/netbox/issues/3255)

It would be useful to be able to split a Subnet Prefix into multiple child prefixes based on the logical division. This is something that I have found very useful and time saving in other IPAMs
For instance you have a /24 prefix as a Container, and you want to subdivide into 8 separate prefixes as /27 subnets
At present, as far as I can see, you must create a prefix for each one of the 8 in turn using the UI

Hoping this request is not replicated elsewhere.

Patrick

### Use case

Reduces repetitive tasks for subdividing prefixes

### Database changes

None required

**Comment by jeremystretch** [comment]
Tagging this as relevant to (but not necessarily blocked by) #7845.

**Comment by elipsion** [comment]
Isn't this more or less the "bulk create" function already implemented for IP addresses?
The only thing that's lacking is the intelligence (or a way to hint) for creating the correct [step](https://docs.python.org/3/library/stdtypes.html?highlight=range#range).
