### ISSUE TITLE
Be capable of adding multiple disks to VMs

### ISSUE THREAD

**Issue by Spezi2u** [netbox-community/netbox#9867]
### NetBox version

v3.2.5

### Feature type

Data model extension

### Proposed functionality

A VM is usually today  what Hardware was 10 years ago. So it may have one or more disks and one or more nics. While we are able today to input the later into netbox, we are still fixed on just one storage device.

It would be great if we could add multiple disks each differing in size and quality. The disk size field today could be used a sum field for the total storage.

Maybe it is possible to think about storage devices in general and adding them as for instance components

### Use case

Documenting the real world is what netbox does. I know netbox is not fixated on storage but those can be also network devices so why not?

Why would you need this. If you are using netbox to document your real world maybe you want to do capacity planing maybe you want to invoice disksizes with different qualities, etc.

### Database changes

probably

### External dependencies

none that I know of

**Comment by jeremystretch** [comment]
> probably

Please elaborate on what specific implementation you're proposing.

**Comment by Spezi2u** [comment]
[#8356](https://github.com/netbox-community/netbox/issues/8356) is in principal the same thing I want. but as discribed in the ongoing discussion of that same issue, maybe VMs should have their own inventory model. Since if I'm understanding it correctly you are using the device NIC model for VMs today since it doesn't not really change from hw.

**Comment by jeremystretch** [comment]
As no further detail has been provided by OP, I'm going to close this out. I invite you to share your use case on #8356 as it seems likely to address your need.
