### ISSUE TITLE
Different Alignment and Decimal Places on Aggregate Usage

### ISSUE THREAD

**Issue by tobikris** [netbox-community/netbox#9871]
### NetBox version

v3.2.7

### Python version

3.10

### Steps to Reproduce

Create multiple Aggregates. Leave some of them empty (without used IP addresses).

### Expected Behavior

The shown percentage of used IP space should look the same for all aggregates.

### Observed Behavior

Some percentages are center-aligned and have more precision than most (it seems to happen for empty aggregates).

![image](https://user-images.githubusercontent.com/2772132/181626751-7e750b5f-5077-4a4d-a1f3-0b28c8cc4cbe.png)

**Comment by PieterL75** [comment]
Looks like #9881 could be combined with this one...

**Comment by atownson** [comment]
I can work on this.

**Comment by jeremystretch** [comment]
Thanks @atownson, but I'm going to fold this one into #9881 as I feel like the rounding issue is better captured there. We can also address the alignment under that issue.

**Comment by tobikris** [comment]
Interesting idea indeed. I am not sure if I prefer this though as it seems to be exaggerating the difference between an unused prefix/aggregate and another one that is empty for all practical use cases. I would be fine with both but would prefer the same look as the left-aligned "0.0%".

**Comment by jeremystretch** [comment]
Fair enough, let's keep things simple.

**Comment by jeremystretch** [comment]
Between this and #9881 it looks much cleaner now:
![Screenshot 2022-08-01 at 11-55-06 Aggregates NetBox](https://user-images.githubusercontent.com/13487278/182189920-f82834ee-a130-43cd-9346-8871e94e2d6f.png)

**Comment by atownson** [comment]
@jeremystretch, you might want to consider increasing the percentage evaluation logic from 25% to 30%, because with the addition of the decimal the progress bar text can look a bit squashed at 25%.
![image](https://user-images.githubusercontent.com/52260120/182193327-425c90c7-61a7-4439-9b19-e9adec394e5e.png)
```
<div class="progress">
  <div
    role="progressbar"
    aria-valuemin="0"
    aria-valuemax="100"
    aria-valuenow="{{ utilization }}"
    class="progress-bar {{ bar_class }}"
    style="width: {{ utilization }}%;"
  >
    {% if utilization >= 30 %}{{ utilization|floatformat:1 }}%{% endif %}
  </div>
  {% if utilization < 30 %}
    <span class="ps-1">{{ utilization|floatformat:1 }}%</span>
  {% endif %}
</div>
```
![image](https://user-images.githubusercontent.com/52260120/182192928-f4164a8d-6215-4bc9-884d-6b6479283645.png)
