### ISSUE TITLE
No cable trace available when using modules

### ISSUE THREAD

**Issue by bjankovich407** [netbox-community/netbox#9879]
### NetBox version

3.2.5

### Python version

3.8

### Steps to Reproduce

Hello,

So I've created a few fiber patch panel devices. Each one utilizes Module Bays to then attack the respective fiber adapter module. Then I've created modules to assign to each bay with the respective number of front and back ports to link cables. I've tried making 12 front ports and linking them to one rear port with multiple positions and I've tried to have equal number of front and back ports. Then linking cabling between interfaces and am unable to get the cable trace functionality working no matter what I try. 

We did recently update from version 3.1.7 and afterwards I am able to confirm that some traces are working and the ones that are not have all been added since version 3.2.25 was installed. I know this is a somewhat new feature and think th at either I'm not following a best practice or maybe there's functionality not fully implemented yet?

### Expected Behavior

Expected for cable trace data to appear when clicking the link.

### Observed Behavior

Netbox says "No paths found'.

**Comment by DanSheps** [comment]
Cables need to be terminated to a fixed termination (interface, console port, etc) for it to generate a cable path.  Are these terminating to something like a interface or are you just using the panels?

https://github.com/netbox-community/netbox/issues/9718 is the relevant FR to re-enable this functionality

**Comment by jeremystretch** [comment]
@DanSheps seems to have identified the root issue here, so I'm going to close this out. Happy to re-open it if this is not the case.
