### ISSUE TITLE
Add an "owner" field to all primary objects

### ISSUE THREAD

**Issue by jeremystretch** [netbox-community/netbox#988]
### Issue type: Feature request

Originally proposed by @CassioFabius in #979. This would entail adding a new optional `ForeignKey` field pointing to the User model. Each primary object type (listed below) could be assigned an owning user. Proposed objects include:

* Circuits
  * Provider
  * Circuit
* DCIM
  * Site
  * Rack
  * DeviceType
  * Device
* IPAM
  * VRF
  * Aggregate
  * Prefix
  * IPAddress
  * VLAN
  * Service
* Secrets
  * Secret
* Tenancy
  * Tenant

**Comment by specialcircumstances** [comment]
Would you propose that the object is inherited of not set... Similar to how tenant is inherited for prefixes?

**Comment by MalfuncEddie** [comment]
Hi,

I suspect this feature originated from itil practices. If so I would replace "owner" with "accountable" and add responsible.

In itil these are not the same.
http://www.itsmprofessor.net/2011/01/accountable-or-responsible.html

PS: I also needed this and solved this by using custom fields (accountable & responsible).

**Comment by jeremystretch** [comment]
With the addition of object-based permissions in v2.9, this doesn't seem particularly useful anymore: the new permissions offer a much more flexible approach to designating "ownership" of objects. I'm going to close this issue, but if anyone still has a need for it, please open a new FR citing your specific use case.
