### ISSUE TITLE
Add Manufacturer column in Module table

### ISSUE THREAD

**Issue by hagbarddenstore** [netbox-community/netbox#9882]
### NetBox version

v3.2.7

### Feature type

Change to existing functionality

### Proposed functionality

Add a column to the Module table for the Modules Module Type Manufacturer field (Puh!).

### Use case

Same use case as for Devices, to know the manufacturer of the Module.

### Database changes

None

### External dependencies

None

**Comment by hagbarddenstore** [comment]
The views already fetch the `module_type__manufacturer` field, so I guess it's just a matter of forgot to add the column to the table.

**Comment by jeremystretch** [comment]
> so I guess it's just a matter of forgot to add the column to the table.

IIRC I think at some point we were including the manufacturer name along with the model under the same column. Best to have it broken out though.
