### ISSUE TITLE
Prefix auto-loads VRF field on creation

### ISSUE THREAD

**Issue by hagbarddenstore** [netbox-community/netbox#9884]
### NetBox version

v3.2.7

### Python version

3.10

### Steps to Reproduce

1. Run NetBox in debug mode
2. Create two or more Prefixes
3. Open the Prefixes list view
4. Observe the SQL queries in the debug toolbar, each prefix loads it's VRF

### Expected Behavior

Instantiating a Prefix should not load the VRF

### Observed Behavior

Instantiating a Prefix loads its VRF automatically

**Comment by hagbarddenstore** [comment]
I understand why the code is doing what it's doing, but perhaps it could use the `vrf_id` field instead of the `vrf` field.

**Comment by jeremystretch** [comment]
Thanks for tracking this down!
