### ISSUE TITLE
Add `child_count` annotation for Aggregate bulk views

### ISSUE THREAD

**Issue by hagbarddenstore** [netbox-community/netbox#9885]
### NetBox version

v3.2.7

### Feature type

Change to existing functionality

### Proposed functionality

The `child_count` annotation is present in the `AggregateListView` but not on `AggregateBulkEditView` and `AggregateBulkDeleteView`.

This causes the `Prefixes` column to show `–` instead of the expected count.

### Use case

Same use case as for the Aggregate list view.

### Database changes

None

### External dependencies

None

**Comment by hagbarddenstore** [comment]
Another way to "solve" it is to simply remove the `Prefixes` column from the table on the bulk views (With `.exclude('child_count')`.

**Comment by jeremystretch** [comment]
This sort of thing should get a lot easier to maintain once #7845 has been implemented.
