### ISSUE TITLE
Include device and site in overlay terminations list view

### ISSUE THREAD

**Issue by dejantep** [netbox-community/netbox#9888]
### NetBox version

v3.3-beta

### Feature type

Change to existing functionality

### Proposed functionality

When looking at the details of certain l2vpn you can see list of terminations. Columns included are "object type" and "Assigned object". It would be much better if you could also include columns device and site. Also add these fields under "filters" section. That would make it possible to quickly find terminations on device or site.
This would improve usability imho.

### Use case

My guess is that this is just matter of displaying whats already there. 

### Database changes

none

### External dependencies

none

**Comment by DanSheps** [comment]
The difficulty with this one is that some terminations can be vlans or vm interfaces, which don't nessicarily have a corresponding "parent" in every case.

**Comment by DanSheps** [comment]
I think I have a workable solution.
