### ISSUE TITLE
Add netbox2netshot to the community contributions page

### ISSUE THREAD

**Issue by kedare** [netbox-community/netbox#9889]
### Change Type

Addition

### Area

Other

### Proposed Changes

Hello.

I created some time ago this tool to synchronize inventory between Netbox and Netshot, I think it would be interesting to add it in the wiki page (it has been running since at Scaleway to manage the whole network inventory and is working great)

https://github.com/scaleway/netbox2netshot

Thank you

**Comment by jeremystretch** [comment]
I've added this, but in the future please use [discussions](https://github.com/netbox-community/netbox/discussions) for anything that doesn't relate directly to the NetBox code base.

**Comment by kedare** [comment]
Thank you, sorry I did not see the discussions feature was enable on this repository.
