### ISSUE TITLE
Changelog entry created when order of tags is changed for an object

### ISSUE THREAD

**Issue by willfurnell** [netbox-community/netbox#9891]
### NetBox version

v3.1.9

### Python version

3.6.8

### Steps to Reproduce

1. Get list of tags from an object using Pynetbox
2. Change the order of the tags in the list
3. Save changes to object

### Expected Behavior

No changlog entry would be made as only the order of the tags changed

### Observed Behavior

A changelog entry is made because the order of the tags has changed:
![image](https://user-images.githubusercontent.com/3112077/182148788-9f06e7f3-42da-4e49-b3a3-877999a4bd53.png)

**Comment by jeremystretch** [comment]
A changelog is going to be created because the object was updated, even if all the attributes are still the same. (This is unrelated to tags.) However, the ordering of the tags in the object's serialized representation should be consistent.
