### ISSUE TITLE
CustomScript Password input field

### ISSUE THREAD

**Issue by PieterL75** [netbox-community/netbox#9894]
### NetBox version

v3.2.7

### Feature type

Change to existing functionality

### Proposed functionality

Create a new input variable that works as a password field and hides then inputted characters.

### Use case

In some cases, I have to enter a password that is provided to the script. Currently the password is shown in cleartext on the screen.
An asterix-box would help to mask the password.

Obviously, the handing of the password in the script is all cleartext and up to the script maintainer to keep it save during the script execution

**Comment by jeremystretch** [comment]
What about displaying the value of the field? Presumably you wouldn't want to show it in the UI. The old secrets app had a widget to unmask the value with a button, maybe that would work?

**Comment by PieterL75** [comment]
The only usecase I see to display the password, is when entering it, to verify that it is correct.
Then that unmask button seems a good addition, indeed.

**Comment by tom0010** [comment]
Is this not the same thing?

https://github.com/netbox-community/netbox/discussions/6406

**Comment by PieterL75** [comment]
Yep, that worked just fine

```
from django.forms import PasswordInput
password = StringVar(widget=PasswordInput)
```
