### ISSUE TITLE
Allow non-master device interfaces to be selectively excluded from virtual chassis master device

### ISSUE THREAD

**Issue by atownson** [netbox-community/netbox#9913]
### NetBox version

v3.2.4

### Feature type

New functionality

### Proposed functionality

I'm proposing to create functionality so that non-master devices in a virtual chassis can have their interfaces selectively excluded from the master device. I'm completely open to implementation. Some implementation paths I thought of are:
1. Flag the interfaces to be excluded on the interfaces themselves
2. Define excluded interfaces per device within the virtual cluster (maybe in the Edit Virtual Chassis page)
3. Provide a text box in the Edit Virtual Chassis page per device for an interface name regex pattern exclusion (or even inclusion with the default being '.+')

Option 1 seems the least plausible to me because it's likely not best practice to include a setting for all interfaces that only applies to interfaces of devices in a virtual chassis. But again, I'm open to suggestions.
The functionality of adding all interfaces by default is great.

### Use case

According to [this document](https://github.com/netbox-community/netbox/wiki/Data-Model-Limitations#data-center-fabric-switches), virtual chassis are the suggested way to model Cisco FEX devices in NetBox, and it works very well. The only issue is that not all FEX interfaces should be inherited by the master device (5K, etc.).
Example: A N2K-C2348UPQ-10GE FEX connected to a Nexus 5696Q should only inherit interfaces Ethernet{fex number}/1/1-48, but by default, inherits Ethernet{fex number}/1/1-48, Ethernet{fex number}/2/1-4, and Ethernet{fex number}/1-2. So, the later 6 interfaces should be excluded.

### Database changes

Likely, but depends on implementation

### External dependencies

None

**Comment by atownson** [comment]
I will model these interfaces as management only. Disregard.

**Comment by jeremystretch** [comment]
Maybe a way around this would be to change the management boolean to a selection field with options revenue, management, and backplane. It would be a breaking change though and certainly would need further thought.

**Comment by DanSheps** [comment]
Honestly, I think FEX modelling requires something different entirely.

Personally, for now, I would model it as a module within the chassis and inventory items (FEXes show as inventory) for the individual components of the FEX.  The reason for this, is if you do any of hte multi-homed vPC technologies, the FEX is individually controlled by each nexus as far as config.  When the config differs, that portion that is affected is controlled by the primary vPC node.

That wiki article was written before we had modules.

That said, FEX's and other remote line cards do require a different model I thinik and it might be time to look at that a little more closely (after we sort out VDC and a few other things)

**Comment by atownson** [comment]
Thanks for the input Jeremy and Dan. NetBox is impressive. Keep up the good work.
