### ISSUE TITLE
Quick Search in aggregate prefixes shows unavailable prefixes as available

### ISSUE THREAD

**Issue by lovedufva** [netbox-community/netbox#9918]
### NetBox version

v3.2.4

### Python version

3.10

### Steps to Reproduce

1. Open IPAM -> Aggregates -> Any aggregate -> Prefixes
2. Quick search for something
3. Compare the resulting prefixes and their availability to the results with no quick search applied. In the screenshots below, 1.0.8.0/21 is taken but shows up as available.

![SCR-20220804-bry](https://user-images.githubusercontent.com/7347780/182779833-80f57214-ec8a-42de-8daa-d4d9f33b3377.png)
![SCR-20220804-bsh](https://user-images.githubusercontent.com/7347780/182779842-a895d3d7-8ea6-4a6f-bfc2-92339c8bd508.png)

### Expected Behavior

I expected only prefixes matching my quick search would show up.

### Observed Behavior

I receive a list of potentially unavailable prefixes showing up as available.

**Comment by jeremystretch** [comment]
Thank you for submitting this issue, however it appears that this topic has already been raised. Please see issue #9663 for further discussion.
