### ISSUE TITLE
Device Import: Rack not found

### ISSUE THREAD

**Issue by opensourceXnetbox** [netbox-community/netbox#9920]
### NetBox version

v3.2.5

### Python version

3.10

### Steps to Reproduce

1. create new Rack
2. import new device with rack specification (i used the correct name of the rack, in my example: Serverschrank-01)
3. i will get an error "Rack was not found"

### Expected Behavior

a new device will be created and is assigned to the correct rack

### Observed Behavior

cannot create a new device over the import function: no racks found

**Comment by jeremystretch** [comment]
Thank you for opening a bug report. Unfortunately, the information you have provided is not sufficient for someone else to attempt to reproduce the reported behavior. Remember, each bug report must include detailed steps that someone else can follow on a clean, empty NetBox installation to reproduce the exact problem you're experiencing. These instructions should include the creation of any involved objects, any configuration changes, and complete accounting of the actions being taken. Also be sure that your report does not reference data on the public NetBox demo, as that is subject to change at any time by an outside party and cannot be relied upon for bug reports.

**Comment by opensourceXnetbox** [comment]
Hey Jeremy, thanks for the answer.
More detailed information here.
I am currently running on Netbox version 3.2.5, which is very freshly installed. 
I have already added my basic structure, like Rack, Site, Site Group, Location, Tenant, Tenant Group, Device Types, Rack Roles and Regions to the Netbox. 
Next, I wanted to create a new "Device" using the Bulk Import function, specifying the following items:

- name
- device_role
- tenant
- manufacturer
- device_type
- status
- site
- rack
- position
- face

As soon as I confirm with "Submit" I get the following error: `Row 1 rack: Object not found. `

In addition, the netbox cannot define a "rack face" without a rack: `Row 1 face: Cannot select a rack face without assigning a rack.`

Thanks for help!

**Comment by jeremystretch** [comment]
You need to specify the **exact steps you're taking,** including the exact data you're sending to NetBox. This is almost certainly a problem with your data, rather than a bug.

**Comment by opensourceXnetbox** [comment]
Hey Jeremy,
I have found the problem. I had two racks with the same name in my testing environment in two different locations. Unfortunately, the error message in the bulk device import didn't make it clear to me, so I tried the whole thing via the API using Ansible. There I had a clear error message.
