### ISSUE TITLE
Tag filtering in the API uses a tag's slug instead of its name

### ISSUE THREAD

**Issue by fabi125** [netbox-community/netbox#9924]
### NetBox version

v3.2.7

### Python version

3.8

### Steps to Reproduce

https://demo.netbox.dev/api/dcim/devices/121/ has the following tags:
```
    "tags": [
        {
            "id": 1,
            "url": "https://demo.netbox.dev/api/extras/tags/1/",
            "display": "Alpha",
            "name": "Alpha",
            "slug": "alpha",
            "color": "aa1409"
        }
    ],
```

### Expected Behavior

The only available filter in the api is `tag=` which I would expect takes a tag's name for filtering (or at least provide a way to provide the database id).

Given discussions like https://github.com/netbox-community/netbox/issues/8113 I wonder if using the slug here is the right thing.

### Observed Behavior

https://demo.netbox.dev/api/dcim/devices/?tag=Alpha fails with
```
{
    "tag": [
        "Select a valid choice. Alpha is not one of the available choices."
    ]
}
```

But using the slug works: https://demo.netbox.dev/api/dcim/devices/?tag=alpha

**Comment by jeremystretch** [comment]
This is working as expected; tags are referenced in filters by their slugs.
