### ISSUE TITLE
DOCSIS Interface Type

### ISSUE THREAD

**Issue by metalshark** [netbox-community/netbox#9933]
### NetBox version

3.2.7

### Feature type

Change to existing functionality

### Proposed functionality

Add an Interface Type for DOCSIS.

### Use case

Being able to articulate a connection over DOCSIS between two devices.

**Comment by jeremystretch** [comment]
Looks like this was already discussed at length in #9229 (which was closed for inactivity) and the consensus was to add a single DOCSIS type as proposed here. Does it make sense to list this under a "Coaxial" type as proposed there?

**Comment by metalshark** [comment]
That seems more than apt, yes. Thank you.
