### ISSUE TITLE
Add 802.11ay and "Other Wireless" interface types

### ISSUE THREAD

**Issue by ZPrimed** [netbox-community/netbox#9935]
### NetBox version

v3.2.7

### Feature type

Data model extension

### Proposed functionality

I am proposing the addition of two types to the Interface model.

[IEEE 802.11ay](https://en.wikipedia.org/wiki/IEEE_802.11ay) is a defined standard (it's an evolution of 802.11ad, which already exists in the list).

I would also like to propose the addition of some sort of "Other (Wireless)" placeholder type, to enable users to document that an interface is some form of "Wireless" rather than just "Other" (which implies one of the cabled types, rather than an RF interface).

### Use case

802.11ay will benefit anybody who has this kind of equpment.

"Other (Wireless)" will give a user a way to cover any other type of proprietary RF interface that isn't already covered by NetBox (e.g. Siklu 8010 P2P radios, which run in the 70-80GHz E-band spectrum at 10Gbps). Without an "Other (Wireless)" option for Interface Type, the "Other" interface must be used which is treated like a cabled interface rather than an RF one.

### Database changes

Uncertain but suspect nothing major is required here - two new types that are both classified as RF/Wireless instead of Cabled.

### External dependencies

n/a

**Comment by jeremystretch** [comment]
Just a reminder: The "Other - wireless" type will need to be added to `WIRELESS_IFACE_TYPES` in `constants.py`.

**Comment by jeremystretch** [comment]
Should "Other - wireless" be listed under "other" or "wireless"? :slightly_smiling_face:

**Comment by ZPrimed** [comment]
Hmmm... That's a tricky one. Since there's only one "Wireless" section, and all of the rest of the RF types are there, I'd lean to putting it at the bottom of the "Wireless" section... But I can see the logic behind putting it under "Other" as well.

There are a bunch of non-standard RF protocols so trying to list everything can get to be ridiculous... It's too bad that there's no way to make the Wireless model extendable by the end-user somehow. 😛

**Comment by jeremystretch** [comment]
> It's too bad that there's no way to make the Wireless model extendable by the end-user somehow.

If it's a real-world piece of hardware we'll happily add it to the list.
