### ISSUE TITLE
Multiple Terminations for Circuits (DOCSIS)

### ISSUE THREAD

**Issue by jahknem** [netbox-community/netbox#9942]
### NetBox version

v3.3-Beta2

### Feature type

Data model extension

### Proposed functionality

Instead of two terminations I'd like to be able to add more than two terminations to a circuit.

### Use case

DOCSIS Circuits are not point to point. While in the beta these are possible to model using cables, for connections spanning multiple sites one would usually use Circuits. With the current circuit model in which only 2 terminations are possibly, DOCSIS cannot be modeled accurately

**Comment by DanSheps** [comment]
I think "Provider Network" is what you are looking for on this one.  Could you check that out and see if that gives you what you need?

**Comment by jahknem** [comment]
Yes, provider networks seem to be what I was looking for, thank you!
