### ISSUE TITLE
new "device role" column in "device types" overview

### ISSUE THREAD

**Issue by opericgithub** [netbox-community/netbox#9953]
### NetBox version

v3.2.7

### Feature type

Data model extension

### Proposed functionality

Users should have choice to add column "device role" into "device types" table.

### Use case

Cisco has AIR-5508 model, which is wireless controller, but there is also ASA-5508 which is firewall. Obviously there is minor two-letter difference between these two models. By adding another column "device role" into "device types" table, users could differentiate more easily between these similar models. For example, firewall role might have red color background and wireless role might have blue color. 

### Database changes

not sure

### External dependencies

not sure

**Comment by jeremystretch** [comment]
There is no relationship between device types and device roles; both relate to the device model. Devices of the same type may serve different roles.
