### ISSUE TITLE
Rack types

### ISSUE THREAD

**Issue by jose-pr** [netbox-community/netbox#9956]
### NetBox version

V3.2.7

### Feature type

Data model extension

### Proposed functionality

A base object type which includes manufacturer, model and any other fields which are can be attributed with a physical device to be used for physical devices. Current devices and racks should be based on this type.

The rack type should also include height, width, depth and the other rack fields.

### Use case

Be able to accurately represent the racks and reuse their configuration when building a site.

**Comment by jeremystretch** [comment]
> Be able to accurately represent the racks and reuse their configuration when building a site.

This is already possible. Please detail your specific use case.

> The rack type should also include height, width, depth and the other rack fields.

This would imply removing all of these fields from the rack model, which would be a rather large breaking change. What would be gained from doing so?

**Comment by jose-pr** [comment]
Similiar to https://github.com/netbox-community/netbox/issues/3400 i am interested in at least having Manufacturer, model. Recorded for each rack, and seeing as  model of  a rack will always have the same dimensions, why the need to store this information per each rack instead of just storing a reference to the type/model.

Then there could be a section in https://github.com/netbox-community/devicetype-library for a rack type.

**Comment by sw8899** [comment]
I would also welcome a Rack Types library. All arguments that speak for a Device/Module Types library also apply to a Rack Types library. It is only a question of the focus of work (Network vs. Datacenter Infrastructure) whether one needs the one or the other library more.

**Comment by postilion** [comment]
I agree that a rack type library would be a nice thing to have.  We have a couple of applications, for example, using either open-frame metal shelving (a/k/a Baker's Rack) or even "IT Workstations" or "Tech Benches" like these photos show.
![tech-bench](https://user-images.githubusercontent.com/4181980/201147378-569cc2b4-6e38-4070-b8df-438a02efd9af.jpg)
![kh5000-3-200-72](https://user-images.githubusercontent.com/4181980/201147407-53b7f402-a911-470a-b1f5-abef8ee16a4d.jpg)
Although this may well lead directly to data-model hell, given how unstructured these are, compared to a normal rack.

Thanks for considering,
-nic

**Comment by ziggekatten** [comment]
My two cents:

- define how you would like to model your setup using built in features of netbox using the GUI. If it is possible to model in netbox according to your business, take onto next point

- automate it using API and/or Custom Scripts. 


If it's possible to define your setup using the features in netbox, there is in my view no need to mess with it. Using the API and/or Custom Scripts is the natural way to adapt the platform to specific needs. 

One thing to consider (my personal view) is to keep netbox as generic as possible, so we don't get into maintenance hell.

**Comment by justin-davisibm** [comment]
From a data-normalization perspective it would seem that this makes a lot of sense.

I have ~500 racks, of which they are primarily 10 different models.

Each of the rack that is of a particular model type shares the following characteristics:
- Weight
- Width (outer and rail-to-rail)
- Height (outer and RU)
- Manufacturer
- Model
- Type (4-post vs 2-post vs. 4 post cab, etc.)

From a purely DCIM perspective, having those fields normalized across all frames would be a significant improvement for data integrity and completeness, very similarly to how hardware MT-M's are handled.
