### ISSUE TITLE
Vlan prefix_count incorrectly reporting via api

### ISSUE THREAD

**Issue by AJNOURI** [netbox-community/netbox#9959]
### NetBox version

v2.8.9

### Python version

3.9

### Steps to Reproduce

- Add one prefix to existing vlan
- Add second prefix to the same existing vlan
- delete the second created prefix
- query vlan via api (/api/ipam/vlans/)

Might be related to:
https://github.com/netbox-community/netbox/issues/4707

### Expected Behavior

API would return a value of the total number of prefixes assigned to the vlan in the "prefix_count" field = 1

### Observed Behavior

"prefix_count" field still = 2

**Comment by jeremystretch** [comment]
Thank you for opening a bug report. Unfortunately, the information you have provided is not sufficient for someone else to attempt to reproduce the reported behavior. Remember, each bug report must include detailed steps that someone else can follow on a clean, empty NetBox installation to reproduce the exact problem you're experiencing. These instructions should include the creation of any involved objects, any configuration changes, and complete accounting of the actions being taken. Also be sure that your report does not reference data on the public NetBox demo, as that is subject to change at any time by an outside party and cannot be relied upon for bug reports.

**Comment by jeremystretch** [comment]
Closing this as no further detail has been provided.
