### ISSUE TITLE
Front port

### ISSUE THREAD

**Issue by abrahamvegh** [netbox-community/netbox#9961]
### Change Type

Correction

### Area

Functionality/features

### Proposed Changes

In [frontport.md](https://github.com/netbox-community/netbox/blob/a2203da1c6fa674a55d3071a287094d70cb1c502/docs/models/dcim/frontport.md):

> A single **rear port** may be mapped to multiple **rear ports** […]

I think it should be:

> A single front port may be mapped to multiple rear ports

or even just:

> A single port may be mapped to multiple rear ports

**Comment by DanSheps** [comment]
It should be "A single rear port may be mapped to multiple front ports"
