### ISSUE TITLE
Allow non-unique VLAN names within a VLAN group

### ISSUE THREAD

**Issue by tea-zup** [netbox-community/netbox#9968]
### NetBox version

v.3.2.7

### Feature type

Change to existing functionality

### Proposed functionality

On IPAM -> VLAN Groups it would be nice to have ID + group as a unique set instead of name + group. I have three vlan segments and in these segments I distinguish vlans by IDs. Multiple vlans in one segment have the same name but different IDs. Therefore they can't be added to the same vlan group. Having ID + group as a unique set would fix my problem. Changing vlan names on switches would be a lot more work.
Is there currently any other way around this problem in Netbox? A similar issue has already been mentioned in [#1823](https://github.com/netbox-community/netbox/issues/1823).

Thanks for all your help.

**Comment by DanSheps** [comment]
So I think it all depends on the platform you use and how you are using Netbox to Automate.   Cisco for example, uniqueneess on both vid+group and name+group make sense because you can't have overlapping VID's but Cisco will also not let you have naming collisions.

**Comment by jeremystretch** [comment]
> It would be useful to have ID + group as a unique identifier of vlan groups instead of name + group. It would be possible to add vlans to groups for those who identify vlans by ID and not by name.

You've just reiterated the proposal above. What is your actual use case?

**Comment by tea-zup** [comment]
Solved the problem by using tags instead of VLAN groups. Thanks anyway :)
