### ISSUE TITLE
Add Inventory Items asset tag to global search

### ISSUE THREAD

**Issue by enno-wattenberg** [netbox-community/netbox#9976]
### NetBox version

3.2.8

### Feature type

New functionality

### Proposed functionality

When doing a global search on asset tags it will not include the inventory items.
It would be helpful to also have the ability to find inventory items by asset tags.

### Use case

Search for inventory items by asset tag in global search and not only for racks and devices.

**Comment by jeremystretch** [comment]
Blocked by #7016

**Comment by jeremystretch** [comment]
This has been completed under #10560 and will be included in NetBox v3.4.
