### ISSUE TITLE
Markdown doesn't render in custom fields in table view

### ISSUE THREAD

**Issue by chcon** [netbox-community/netbox#9979]
### NetBox version

v3.2.8

### Python version

3.8

### Steps to Reproduce

1. Create a custom field of type Text(long) for any content type, e.g. IPAM->IP addresses
2. Add some Markdown or raw HTML to the custom column for an IP address object in the IPAM
3. See that the Markdown/raw HTML is not rendering in the IPAM->IP addresses table view

This was working in v3.2.7, so this is probably due to this merge request:
https://github.com/netbox-community/netbox/commit/38350a102320ea4b1f6bdb81b454c452f9779d2b 

### Expected Behavior

Markdown should render in custom columns in the table view for any content type if field type Text(long) was chosen for the custom column.

### Observed Behavior

Markdown/raw HTML is not rendering for Text(long) custom columns in the table view of any content type like IPAM->IP addresses.

**Comment by chcon** [comment]
Just fixed it in my local environment. If you want to assign me to this one I will create a pull request.

**Comment by jeremystretch** [comment]
Thanks @chcon!

**Comment by chcon** [comment]
No, you are right. Just checked, I am using plain HTML in some custom columns, and not markdown. But plain HTML definitely worked before 3.2.8 (which ultimately led to the XSS flaw).
