### ISSUE TITLE
Support for CA on Redis nodes

### ISSUE THREAD

**Issue by Kerwood** [netbox-community/netbox#9996]
### NetBox version

v3.2.8

### Feature type

New functionality

### Proposed functionality

Adding a path for a certificate authority in the Redis configuration to be able to validate a self signed certificate on the Redis node.

### Use case

If you're using a self signed certificate on your Redis node and want to validate that certificate, you will have to provide a CA certificate. Currently it is not possible and you will have to disable certificate verification.

**Comment by Kerwood** [comment]
A possible solution. 
https://github.com/Kerwood/netbox/commit/2541fd9aa0983655343beae4f53d3089b2c04e1d

**Comment by Kerwood** [comment]
@jeremystretch 
When the status is "need owner", is that one of the core maintainers or any one that wants to give this issue a go ?

**Comment by jeremystretch** [comment]
Per the [labels list](https://github.com/netbox-community/netbox/labels):

> This issue is tentatively accepted pending a volunteer committed to its implementation

**Comment by Kerwood** [comment]
Sign me up.

**Comment by jeremystretch** [comment]
@Kerwood are you still interested in contributing this work?

**Comment by Kerwood** [comment]
@jeremystretch Sorry for the waiting time.. Here it is :)
